### ISSUE TITLE
Cannot connect to online game?

### ISSUE THREAD

**Issue by b-y-f** [tailscale/tailscale#10009]
### What is the issue?

I have set up a remote exit node and a local computer, remote node have no firewall limtation, and I can browse website, ping each other without any problem, but when I want to connect to game server, it won't work.
Why? Is it because game is using different port and wireguard not support?

You can login to steam community and have chat with friends, but in game you cannnot connect to a game.

---

I think game server just public server.
Yes, aws ec2 as exit node server and my local pc as client to access that exit node.

---

exit node is linux and my local is windows

### Steps to reproduce

Download steam, install dota2, login to see server,

### OS

Linux, Windows

### OS version

Debian 10, win11

### Tailscale version

latest

**Comment by bradfitz** [comment]
There's no details here with which which we can help debug or advise. It's also not clear what the connection to Tailscale is.

I might try one of the community forums like the /r/Tailscale subreddit on Reddit?

But closing this for now as this isn't the type of support we provide in a bug tracker.
