### ISSUE TITLE
FR: VPN service like Mullvad for use in South Africa

### ISSUE THREAD

**Issue by dkkr23** [tailscale/tailscale#10006]
### What are you trying to do?

Trying to use a location VPN like Mullvad, which isn’t currently available for South Africa

### How should we solve this?

Possibly integrate with another location VPN like Mullvad, which has a wider range of supported countries

### What is the impact of not solving this?

No workaround

### Anything else?

I use tailscale via home assistant

**Comment by mayakacz** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/9314
