### ISSUE TITLE
It prompts this error, how to solve it? Error: line 33, column 1: invalid character '"' after object value

### ISSUE THREAD

**Issue by itgir** [tailscale/tailscale#10015]
### What is the issue?

Disable some public nodes and add this section in Access Controls settings
"DERPMap": {
"Regions": {
"1": null

It prompts this error, how to solve it?
Error: line 33, column 1: invalid character '"' after object value (expecting ',' or '}')

### OS

Windows

**Comment by DentonGentry** [comment]
The template asks for a bug report because without it we cannot look up telemetry to locate the tailnet or see what happened.

I believe this was also sent as a support request, we'll handle it there.
