### ISSUE TITLE
net/netcheck: only do PCP probes whenever gateway IP or STUN ip:port changes

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1001]
(forking off from #810)

We currently do a PCP probe with every netcheck.

We really only need to do it whenever the gateway IP changes.

miniupnpd likes to log a bunch when PCP sets up a mapping (we create a 1 second lifetime mapping & delete it as part of our probe), which means we generate a bunch of logs somewhat unnecessarily.

**Comment by crawshaw** [comment]
Don't we also need one on nebulous events we can't detect like the gateway router being reset?

**Comment by danderson** [comment]
In NAT-PMP (PCP's precursor), iirc you could subscribe to a multicast group
and get a notification when the gateway restarted. I'm not sure if that
carried over into PCP, I'd have to reread the RFC.

**Comment by bradfitz** [comment]
> Don't we also need one on nebulous events we can't detect like the gateway router being reset?

I figured we'd also change whenever our STUN mapping changes. If the router reboots, you're almost surely going to get a new random ephemeral port.
