### ISSUE TITLE
Set Default Exit-Node Policy

### ISSUE THREAD

**Issue by hydrian** [tailscale/tailscale#10014]
### What are you trying to do?

When a tailscale client connects to a tailnet, the tailscale  client gets the policy define in the admin console. Then the client applies rule to itself. Client ACL needs to be managed outside of this. 

### How should we solve this?

After a tailscale client authentic/verified authentication and downloads tailnet client list, tailscale client downloads tailnet exit-node policy. Tailnet admins can lock clients to specific node or not using an exit node. Tags are used for filtering. Most exact wins. 

Example of exit-node policy in XML. Root exitNodePolicy is default for the tailnet:
```
<exitNodePolicy userLocked="false" >
    <exitNode weight=1>device-name-1</exitNode>
    <exitNode weight=2>device-name-2</exitNode>
    <exitNodePolicy userLocked="true" tags="limited-devices" >
        <exitNode weight=1>device-name-3</exitNode>
        <exitNode weight=2>device-name-4</exitNode>
    </exitNodePolicy>
</exitNodePolicy>
```

Initial tailnet exit-node policy:
`<exitNodePolicy userLocked="false" />`

### What is the impact of not solving this?

Tailnet admins can't automatically apply exit-node policies across a tailnet systematically.

### Anything else?

Also talked about on reddit: https://www.reddit.com/r/Tailscale/s/rbYJc6CAqs

**Comment by DentonGentry** [comment]
The feature request is to be able to require specific nodes to use a specific exit node?

Though the feature request describes this using XML, I gather that XML is not the key request.

**Comment by hydrian** [comment]
> The feature request is to be able to require specific nodes to use a specific exit node?
Yes, and have it automatically be applied on connect, not having to have the user to manually select an exit-node. 

> Though the feature request describes this using XML, I gather that XML is not the key request.

This was just an example of the POSSIBLE configuration setup. This shows that the configuration can support multiple failback exit-nodes, locking the device so it can't change the exit-node configuration, and play exit-nodes by applied by tags.

**Comment by omerf111** [comment]
This is a key feature. I would love to see it implemented.

**Comment by FreeWoRLD83** [comment]
Just setup my entire network and the first thing I wished was to have this feature. It would be well appreciated

**Comment by ludditus-RPI** [comment]
This would be great, especially on mobile devices where you can configure the one-tap connection widgets, but still need several more taps to turn on exit node.

**Comment by serdarcloud** [comment]
It is just weird that IOS app has already this feature. I would understand if this feature is not available on all mobile phones. For sure it is just a simple update as this action does not require the phone to be unlocked or the user needs an authentication.

**Comment by tbgoose** [comment]
Would also appreciate this feature :)

**Comment by revki** [comment]
Would love to have this feature available in Android App as in IOS App.

**Comment by Serpexx** [comment]
I set up an exit node for the first time and was surprised I had to manually assign it in my android client app.

Would be great if we could use the admin web interface to force the use of an exit node by default, or for specific clients

**Comment by SamB-GB** [comment]
I agree, would be great to auto-sign the exit node to a specific group or by default etc.

**Comment by agottardo** [comment]
It seems like you want to deploy a _default_ and not a _forced_ value, and it seems like you want to do this using ACLs... that said, if you're deploying Tailscale to a fleet of devices using MDM, we offer a system policy on Windows, macOS, iOS, and Android that allows you to force the use of a given exit node: https://tailscale.com/kb/1315/mdm-keys#force-an-exit-node-to-always-be-used

> The ExitNodeID policy forces the Tailscale client to always use the given exit node. This can be useful if you wish to route all Internet traffic through a node for inspection or logging purposes. Users won't be able to disable or choose another exit node when this policy is active. A message will be displayed in the client UI informing users about this restriction.

**Comment by hydrian** [comment]
The main issue here is it doesn't support Linux, which is a requirement for me. I'm a home user with about 25ish devices that would need tailscale. Some for exit nodes and others for mobile/laptop. This is a bit big for configuring each separately but I don't also have an MDM either. 

> It seems like you want to deploy a _default_ and not a _forced_ value, and it seems like you want to do this using ACLs... that said, if you're deploying Tailscale to a fleet of devices using MDM, we offer a system policy on Windows, macOS, iOS, and Android that allows you to force the use of a given exit node: https://tailscale.com/kb/1315/mdm-keys#force-an-exit-node-to-always-be-used

**Comment by agottardo** [comment]
cc @kabirsikand

**Comment by SamB-GB** [comment]
I see on this page: https://tailscale.com/blog/auto-exit-nodes

"Customers will soon be able to secure their entire workforce without user input using forced exit nodes, across every platform."

Does this mean that the ability to force an exit node is coming with having to use MDM etc?

**Comment by mrbluecoat** [comment]
I just used https://tailscale.com/kb/1315/mdm-keys#force-an-exit-node-to-always-be-used and it works as advertised: you set an exit node ID and the device uses only that exit ID.

As a follow-up, is there a way to have multiple exit nodes defined in my network and have the app automatically select the fastest one based on latency or some other best-fit algorithm? Something like https://tailscale.com/kb/1392/auto-exit-nodes#use-a-suggested-exit-node but then automatically applying the best result? We have a fleet of devices geographically disperse and we have geo-defined exit nodes but as people travel they may be in a different location than their usual office so hard-coding a specific exit node ID is not ideal.

**Comment by hydrian** [comment]
Still doesn't support Linux...

**Comment by hydrian** [comment]
Still doesn't support Linux...

**Comment by agottardo** [comment]
> unclear if MDM will support the suggest keyword or MDM will continue to only allow a single node ID

@mrbluecoat we're working on it! coming soon, with some advanced configurations options available via MDM. Keep following the change log for updates.

**Comment by mrbluecoat** [comment]
For those who didn't see the news: https://tailscale.com/kb/1392/auto-exit-nodes

**Comment by kabirsikand** [comment]
We now support mandating exit nodes via policies. See [mandatory exit nodes](https://tailscale.com/kb/1413/mandatory-exit-nodes) and the supporting details on [recommended exit nodes](https://tailscale.com/kb/1392/auto-exit-nodes) to get started. Use caution when combining these with policies that mandate Tailscale to be always-on, as captive portals can cause trouble.

**Comment by hydrian** [comment]
Linux support?
