### ISSUE TITLE
Windows tailscale client v1.52.0 will broken after connecting to other node.

### ISSUE THREAD

**Issue by l1nxy** [tailscale/tailscale#10025]
### What is the issue?

After upgrading tailscale to v1.52.0, the `tailscale status` can print the tailscale status correctly, and it will broken if connect to other node by ssh,or by vscode...etc.

There are some screenshot about befor borken and after:

![Snipaste_2023-10-31_14-10-07](https://github.com/tailscale/tailscale/assets/12152770/0407c33a-6ffe-4644-9f21-7edcfbfb5fe9)

![Snipaste_2023-10-31_14-10-57](https://github.com/tailscale/tailscale/assets/12152770/32cb6a18-d6f5-4def-8802-6d9514e6be68)

After broken, the tailscale can not run corroectly, and `tailscale status` print:
```
❯ tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled.exe, pid 6584). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: The system cannot find the file specified.
```
`tailscaled` print:
```
❯ tailscaled
logtail started
2023/10/31 14:43:22 failed to create local log directory; not writing logs to disk: mkdir C:\ProgramData\Tailscale\Logs: Cannot create a file when that file already exists.
Program starting: v1.52.0-t3c2ff1e4a-gfccfad18e, Go 1.21.3: []string{"C:\\Program Files\\Tailscale\\tailscaled.exe"}
LogID: xxxxx
logpolicy: using LocalAppData dir C:\Users\linxy\AppData\Local\Tailscale
logpolicy.ConfigFromFile C:\Users\linxy\AppData\Local\Tailscale\tailscaled.log.conf: open C:\Users\linxy\AppData\Local\Tailscale\tailscaled.log.conf: The system cannot find the file specified.
logpolicy.Config.Validate for C:\Users\linxy\AppData\Local\Tailscale\tailscaled.log.conf: config is nil
flushing log.
logger closing down
safesocket.Listen: namedpipe.Listen: open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: Access is denied.
```

Rebooting the tailscale system service is not work.

If reboot the OS, the tailscale can work again, but can not connect to other node.

### Steps to reproduce

1. Connectiing to other node.

### Are there any recent changes that introduced the issue?

Nothing.

### OS

Windows

### OS version

Win11

### Tailscale version

1.52.0

### Other software

Clash.

**Comment by l1nxy** [comment]
@DentonGentry Hi, sorry to bother you. I would like to try fixing this issue. I am now able to reproduce the invalid call of `UTF16PtrToString`. Could you please help me by allowing me to debug the program?

**Comment by DentonGentry** [comment]
> I am now able to reproduce the invalid call of UTF16PtrToString

So this is almost certainly the same issue as https://github.com/tailscale/tailscale/issues/10052

> Could you please help me by allowing me to debug the program?

We need to figure out where `UTF16PtrToString` is being called from and why. The backtrace appears to be incomplete, probably because it dives into Windows win32 calls.

**Comment by l1nxy** [comment]
> So this is almost certainly the same issue as https://github.com/tailscale/tailscale/issues/10052
Actually, I'm not sure because tailscaled v1.52.0 doesn't work on my home computer, the log same with #10052, but it runs on my work PC. By the way, the locale is the same.

> We need to figure out where UTF16PtrToString is being called from and why. The backtrace appears to be incomplete, probably because it dives into Windows win32 calls.
I am currently debugging, please give me some time to investigate.

**Comment by kegns** [comment]
I am wondering is my error relatated to this issue or #10023 ?

What really bothers me is that downgrading to any version doesn't work

>tailscaled
logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.52.0-t3c2ff1e4a-gfccfad18e, Go 1.21.3: []string{"tailscaled"}
LogID: cfc40e7b694bbba5cdb641ce0949dd0dbb239c49a80604bd71efe5c4338a9db0
logpolicy: using LocalAppData dir C:\Users\gw\AppData\Local\Tailscale
flushing log.
logger closing down
safesocket.Listen: namedpipe.Listen: open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: Access is denied.

**Comment by ReachableCEO** [comment]
This issue is not solved/completed. I have the same error happening on my Windows 10 Pro fully patched system, with tailscale . I uninstalled and re-installed latest version of tailscale.

**Comment by ReachableCEO** [comment]
```
C:\Windows\system32>tailscaled
logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.84.2-t5d271bebf-gfb9977414, Go 1.24.2: []string{"tailscaled"}
LogID: 3a460e887fc5770b2d38369f9fa1ae727421113fefbcce5611dd7bff8e457452
logpolicy: using dir C:\ProgramData\Tailscale
dns: using *dns.windowsManager
running ipconfig /registerdns ...
flushing log.
logger closing down
safesocket.Listen: namedpipe.Listen: open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: Access is denied.

C:\Windows\system32>
```

**Comment by ReachableCEO** [comment]
![Image](https://github.com/user-attachments/assets/9ba1e52d-26c1-45ac-a26c-f0bba9fd8188)
