### ISSUE TITLE
Tailscale With MagicDNS on Host Breaks DNS Within Kubernetes Containers

### ISSUE THREAD

**Issue by quexten** [tailscale/tailscale#1003]
**Describe the bug**
When installing Tailscale on a Kubernetes host with MagicDNS enabled, then
new containers don't have any access to DNS. Pinging the cluster-internal DNS works from within the new container, resolving DNS from it does not. Old containers and the host system can still resolve DNS fine from the cluster internal DNS server. I've not been able to verify this yet, but I assume that Tailscale is somehow preventing Kubernetes from setting up the routing between the containers. Disabling MagicDNS fixes the issue.

**To Reproduce**
1. Install Tailscale with MagicDNS enabled on a Kubernetes host (and Calico as the CNI, not sure if this is relevant)
2. Start a new container
3. Try to resolve DNS, it won't work.

**Expected behavior**
When installing Tailscale on a Kubernetes host system, then 

**Version information:**
 - Kubernetes Version: 1.19.3
 - Tailscale Version: 1.2.8

**Comment by arunsathiya** [comment]
Not too sure if it's the same, but there is another issue where DNS resolution fails. - https://github.com/tailscale/tailscale/issues/993

**Comment by quexten** [comment]
For reference, I was using publicly routable DNS servers in magic DNS (1.1.1.1, 9.9.9.9) unlike in #993 . The cluster-internal DNS server still worked fine, DNS resolution on the host still worked fine, it was just the DNS in containers (that communicate with the cluster internal DNS on the same node) didn't work.

**Comment by bradfitz** [comment]
Yeah, the big problem with Magic DNS at the moment is we don't have support for letting an individual node say: "I want Magic DNS on, to run the DNS server at 100.100.100.100, but if it's resolving a name that isn't a Tailscale name, it should forward to whatever my machine was using otherwise, NOT the network-wide fallback."

The only reason we require network-wide DNS servers specified in order to use Magic DNS at the moment is because we haven't finished implementing support for read-the-DNS-settings-you-had-before code on all platforms. It's surprisingly difficult/annoying/impossible-ish on some platforms. Linux, of course, has 17 ways of doing it.

Personally, Magic DNS breaks my home network's DNS server resolution of my existing home network names, so I also need this fixed before I can use Magic DNS myself.

**Comment by mikeburgh** [comment]
Is there an issue tracking that effort (use what you had before if not a magic dns host) ?

**Comment by mpwolfe** [comment]
Magic DNS breaks my home network's DNS server resolution of my existing home. my home linux servers as well......i had to disable Mdns.

**Comment by danderson** [comment]
This might be fixed as of Tailscale 1.8, which will roll out soon. If you still have a k8s cluster capable of demonstrating the issue, could you give the unstable package a test drive and see if helps? If not, I'll need more details about the network topology and contents of /etc/resolv.conf (and ideally also a Tailscale IP for the node exhibiting the issue) to figure out what's going wrong.

**Comment by quexten** [comment]
I actually can't reproduce most of this issue on Tailscale 1.6.0 anymore. Resolving domains works as expected, so no connectivity loss inside the containers remains.
For reference here is the resolv.conf on my host:
```
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search MY.EMAIL.com.beta.tailscale.net MY-OTHER-DOMAIN.int
```

And inside a freshly started pod:
```
nameserver 10.100.0.10
search default.svc.cluster.local svc.cluster.local cluster.local MY.EMAIL.com.beta.tailscale.net MY-OTHER-DOMAIN.int your-server.de
options ndots:5
```

This also means that Magic DNS doesn't immediately resolve the Magic DNS domains inside the containers since the cluster's DNS is queried first, however this is not an issue for me. So when pinging another Tailscale enabled host from within a Kubernetes pod, this happens:
```
/ # ping styx.MY.EMAIL.com.beta.tailscale.net
ping: bad address 'styx.MY.EMAIL.com.beta.tailscale.net'
/ # ping styx.MY.EMAIL.com.beta.tailscale.net
PING styx.MY.EMAIL.com.beta.tailscale.net (100.126.149.45): 56 data bytes
64 bytes from 100.126.149.45: seq=0 ttl=63 time=72.967 ms
64 bytes from 100.126.149.45: seq=1 ttl=63 time=19.323 ms
```
But again, this is much better than when I last tried Magic DNS on this Kubernetes host.
And here is my Tailscale version:
```
1.6.0
  tailscale commit: ddc975fcb268a06dc39923ec5db93f1c95b8cfc4
  other commit: 995460c32665f1dab78c78512386235d275cf074
  go version: go1.16.2-ts3b83fb3
```

**Comment by DentonGentry** [comment]
Note that 1.8 is bringing a raft of new MagicDNS work, and will be worth trying again.

**Comment by DentonGentry** [comment]
1.8 was released two weeks ago, with a raft of DNS functionality.

**Comment by DentonGentry** [comment]
At this point I think this is done. Tailscale 1.8 added support for the feature described in https://github.com/tailscale/tailscale/issues/1003#issuecomment-741881513, the DNS servers configured by Kubernetes can be used if the name being resolved is not a MagicDNS name.
