### ISSUE TITLE
appc: TestTCPSNIHandler flake

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#10056]
Flake https://github.com/tailscale/tailscale/actions/runs/6717340109/job/18255027051?pr=10042

```
=== RUN   TestTCPSNIHandler
    handlers_test.go:154: EOF
--- FAIL: TestTCPSNIHandler (0.00s)
FAIL	tailscale.com/appc
```

/cc @raggi @catzkorn

**Comment by bradfitz** [comment]
This is still flaking on a good fraction of PRs and being distracting.

@twitchyliquid64, can you take a look?

**Comment by twitchyliquid64** [comment]
Sure thing!

The `inet.af` PR landed, so with a bit of luck all we need is an upgrade. Testing if that fixes it now.
