### ISSUE TITLE
`dpkg --purge tailscale` doesn't purge node state

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1007]
Steps:
- Install tailscale from debian or ubuntu packages
- `tailscale up`
- dpkg -r tailscale
- /var/lib/tailscale/tailscaled.state still exists (as expected with -r)
- dpkg --purge tailscale

Expected:
- /var/lib/tailscale/tailscaled.state and other state files in that directory are removed, since --purge is supposed to remove all trace of the app

Actual:
- state files not removed, so reinstalling the app will give it the same node keys, etc.

Normally the fix for this is an extra couple of commands in the dpkg scripts.

**Comment by danderson** [comment]
Fixed in 128b56840d0352b14e4b2107660809c325365a5a.

Looking at RPM for parity, it appears that it has no equivalent "purge" operation. The only data the postrm script is given is "the number of packages that will remain once the operation has completed" (1 for "uninstall old package during upgrade", 0 for "actual uninstall").

I don't see an obvious common convention on what to do there. It seems "keep cruft around" and "delete state on any uninstall" are about as popular as each other. Thoughts?

**Comment by apenwarr** [comment]
I'm not a big rpm user, so unfortunately I have no idea what the standard is.

Debian's attitude of "automatically losing state is eventually going
to make someone cry, so perhaps that should be a separate command"
kind of appeals to me though :)  If rpm has no separate command and no
convention, then I guess I wouldn't delete the state. If someone can
point out a convention, then I guess we should follow the convention.


On Wed, Dec 9, 2020 at 11:33 PM Dave Anderson <notifications@github.com> wrote:
>
> Fixed in corp repo.
>
> Looking at RPM for parity, it appears that it has no equivalent "purge" operation. The only data the postrm script is given is "the number of packages that will remain once the operation has completed" (1 for "uninstall old package during upgrade", 0 for "actual uninstall").
>
> I don't see an obvious common convention on what to do there. It seems "keep cruft around" and "delete state on any uninstall" are about as popular as each other. Thoughts?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by danderson** [comment]
Likewise not a big rpm user. In the absence of guidance, my rule of thumb is that irreplaceable state (databases, keys, etc.) should not be deleted automatically. Happy to entertain opposing opinions from RPM experts though.
