### ISSUE TITLE
iOS: Tailscale widget always displays connected

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#10072]
### What is the issue?

Tailscale Widget always show status of connected.  

### Steps to reproduce

1. Install TS on iOS
2. Add TS widget to screen
3. Confirm TS not connected
4. Swipe to display TS widget

### Are there any recent changes that introduced the issue?

iOS 17.2b1
TS 1.53.14

### OS

iOS

### OS version

17.2b1

### Tailscale version

1.53.14

**Comment by agottardo** [comment]
Duplicate of #10007, an issue tracking similar widget weirdness. We have a change landing shortly which will overall optimize state management in the widget and should fix this. Thanks for the report!
