### ISSUE TITLE
Package server distributing multiple versions of tailscale_1.52.0_amd64.tgz

### ISSUE THREAD

**Issue by dkaser** [tailscale/tailscale#10078]
### Background

The Unraid plugin installer uses an MD5 hash to verify files being used during installation:

1. As part of the plugin release process, I download the latest tgz from the package server and generate an MD5 hash of the file.
2. The download path and MD5 hash of the tgz are included in the plugin.
3. When users install/update the plugin, their server downloads the installer from the package server, then uses the MD5 hash to verify that it was downloaded correctly.

### Problem

After the plugin was updated to install 1.52.0, multiple users started reporting installation failures due to an MD5 hash mismatch on the Tailscale download. Further research indicated that the package server seems to be distributing a different version of tailscale_1.52.0_amd64.tgz to some users.

When I download 1.52.0 on my network, I get the following md5sum:
```
36ae729bd2834d61068da0091d21abd4  tailscale_1.52.0_amd64.tgz
```

I requested that one of the affected users [download the file and run an md5sum](https://forums.unraid.net/topic/136889-plugin-tailscale/?do=findComment&comment=1322359), which resulted in:
```
b4d15d9908737e08e3f95ed5104603ce  tailscale_1.52.0_amd64.tgz
```

This behavior has not occurred for previous Tailscale releases.

Plugin ref: dkaser/unraid-tailscale#96

### Are there any recent changes that introduced the issue?

Release of 1.52.0

### OS

Linux

### OS version

Unraid

### Tailscale version

1.52.0

**Comment by bradfitz** [comment]
Also reported in https://github.com/tailscale/github-action/issues/97

/cc @DentonGentry @danderson @awly

**Comment by DentonGentry** [comment]
I think we've identified the state the CDN had gotten itself into, and cleared it.
It should repopulate its cache and all nodes return the same SHA256.

**Comment by dkaser** [comment]
This is doing better now; closing :)
