### ISSUE TITLE
FR: No ping

### ISSUE THREAD

**Issue by Chicnac** [tailscale/tailscale#10084]
### What are you trying to do?

I have 2 computers that im trying to use RDP when im not at home

### How should we solve this?

The problem is that tailscale says the machines are connected but they cant ping each other, so it seems that they are not really connected to one another. Even if I checked the firewall rules nothing seems to be out of the ordinary...

Using my internal network IP's I ping and fully use RDP, but not when tailscale is on.

### What is the impact of not solving this?

I cannot connect my two computers together

**Comment by bradfitz** [comment]
You didn't answer half the questions the template asked for so there's nothing we can really investigate.

If you're uncomfortable sharing details, you can file a support request at https://tailscale.com/contact/support/
