### ISSUE TITLE
android: black screen on android go

### ISSUE THREAD

**Issue by SimaKyr** [tailscale/tailscale#1008]
**Describe the bug**
Nothing show up when open Tailscale, just black screen.

**To Reproduce**
1. Open app.
2. Black screen.

**Expected behavior**
See button "Getting started", to start work with app.

**Screenshots**
Info device:
![IMG_20201210_175223](https://user-images.githubusercontent.com/28606130/101796015-32575880-3b11-11eb-8435-c33723ac9e90.jpg)
![IMG_20201210_175243](https://user-images.githubusercontent.com/28606130/101796021-33888580-3b11-11eb-848a-803ef8a859cc.jpg)

**Version information:**
 - Device: Blackview A60
 - OS: Android Go (looks like 8.0)
 - OS version: GO
 - Tailscale version: latest on 09.12.2020

**Additional context**
Tried disable GPU Accel and enable. doesn't work. I think this is just a bug.

**Comment by SimaKyr** [comment]
I tried to reinstall from the Play Store, cleaned the application data, tried to download from the site https://apkcombo.com/ but did not give any result.

**Comment by bradfitz** [comment]
> Device: Blackview A60

"Black view" seems like an appropriate device model for this bug! 😄 

@eliasnaur, can you take a look? You had some software renderer you were falling back to in some cases, IIRC? Do you just need to update the heuristic for when that's used?

**Comment by eliasnaur** [comment]
I have an alternative renderer for phones such as Samsung J2 + Moto C nearly ready. It should be possible to run that on the CPU for the A60. I'll take a look.

**Comment by bradfitz** [comment]
@eliasnaur, how do you select which renderer to use? Does it look at advertised capabilities of the device, or is it a hard-coded table of names?

**Comment by eliasnaur** [comment]
I look at capabilities, and apply workarounds to buggy behaviour. I have yet to need a hard-coded table of names.

**Comment by SimaKyr** [comment]
Please tell me when the bug will be fixed

**Comment by LiJu09** [comment]
Same problem
- Device: Samsung J3 2016
- OS: LineageOS
- OS version: 14.1
- Tailscale version: 1.6.0

**Comment by DentonGentry** [comment]
We're going to build a 1.13.x build on the Open Testing track:

**Comment by DentonGentry** [comment]
In the next bug scrub if there are no further comments, we'll close this issue.

**Comment by DentonGentry** [comment]
I think the 1.14 and 1.16 releases delivered fixes for this issue, notably https://github.com/tailscale/tailscale-android/commit/db77216ead0ed7d745470526f0e53a2ca2933dc2 in late September which went into 1.16.

At this point I'm going to close this as fixed. If it happens again with 1.16 or later, please reopen.

**Comment by cherjr** [comment]
> Same problem
> 
> * Device: Samsung J3 2016
> * OS: LineageOS
> * OS version: 14.1
> * Tailscale version: 1.6.0
> 
> So not only Android GO

still doesn't work (newest Tailscale Beta)

**Comment by DentonGentry** [comment]
@cherjr This issue was closed two years ago. If you are experiencing a problem please file a new bug and include details of what happens when you try to start the Tailscale app.
