### ISSUE TITLE
FR: Local Tailscale ACL policy linting/error detection

### ISSUE THREAD

**Issue by heywoodlh** [tailscale/tailscale#10098]
### What are you trying to do?

I've been using GitHub Actions to deploy my Tailscale ACL (i.e. [GitOps for Tailscale ACLs](https://tailscale.com/blog/gitops-acls/) for quite some time -- I love it! On occasion, I make changes to my ACL that are invalid. However, there is no way for me to know (at least that I'm aware of) that my ACL file contains errors until the GitHub Action runs and fails to apply the invalid ACL.

I would love to know that I have an invalid ACL policy _before_ I commit and push my changes to my Git repository.

### How should we solve this?

I think that this could be implemented through the command line client, something like this:

```
tailscale acl verify policy.hujson
```

I think that a command-line argument as a first step would make it much easier for people to implement ACL linting in their preferred text editor. Or implement a `git` hook that runs the verify before you commit.

### What is the impact of not solving this?

It would be nice to have similar error reporting to the Web-based ACL editor in a local environment. For now, I don't know if I have errors in my ACL until my GitHub Action fails.

**Comment by DentonGentry** [comment]
Does the validate API endpoint do what you're looking for?
https://github.com/tailscale/tailscale/blob/main/api.md#validate-and-test-policy-file

**Comment by heywoodlh** [comment]
Likely! 

I looked a while ago to see if there were any API endpoints I could use like this -- I must have missed this. I will likely try to integrate this this weekend into my Tailscale ACL repo and will report back on how it goes. :smile:

**Comment by heywoodlh** [comment]
Wrote a shell script named `check.sh` to implement this (and am using `lefthook` to prevent me from committing syntax errors to my ACL repo):

```
#!/usr/bin/env bash
root_dir="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
policy_file="$root_dir/policy.hujson"
token="SOMETOKEN"
tailnet="SOMETAILNET"

output=$(curl --silent https://api.tailscale.com/api/v2/tailnet/${tailnet}/acl/validate -u "${token}:" --data-binary "@${policy_file}")

if [[ ${output} == "{}" ]]
then
    echo "No issue detected in policy file"
else
    echo "Error detected"
    echo "${output}"
    exit 1
fi
```

This is my `lefthook.yaml`:

```
pre-commit:
  commands:
    policy-check:
      run: |
        ./check.sh
```

And here's what the output looks like when I try to commit with an error in my ACL -- and this error prevents me from completing the commit:

```
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.5.5  hook: pre-commit │
╰──────────────────────────────────────╯
┃  policy-check ❯

Error detected
{"message":"line 719, column 5: invalid literal: invalidtext"}


  ────────────────────────────────────
summary: (done in 1.53 seconds)
🥊  policy-check
```
