### ISSUE TITLE
IOS: Contradictory notification regarding key expiry

### ISSUE THREAD

**Issue by insert-usernamehere** [tailscale/tailscale#10095]
### What is the issue?

Today within the tailscale app a message appeared warning me that key expiry is disabled but I should reauthenticate in order to remain connected to the tailnet.
Since key expiry is disabled reauthentation is not needed in this case making the notification irrelevant and contradictory to the point of disabling key expiry.
![2A692DC1-58DF-4F13-A893-4A60576BB1C0](https://github.com/tailscale/tailscale/assets/29443173/2b1d3b2f-2dbc-4f06-9041-7e9fa51be7ae)

### Are there any recent changes that introduced the issue?

The introduction of key expiry notifications in the recent beta 

### OS

iOS

### OS version

IPadOS 15

### Tailscale version

1.53.14 (101.53.14)

**Comment by knyar** [comment]
Thank you for reporting this. It seems related to a recent change to the iOS client, cc @agottardo

**Comment by agottardo** [comment]
Oops! This is a regression in unstable. Will push a fix today.

**Comment by agottardo** [comment]
A fix will be landing in the next TestFlight update.
