### ISSUE TITLE
FR: Upload k8s-operator image to ghcr

### ISSUE THREAD

**Issue by Protozoan1369** [tailscale/tailscale#10101]
### What are you trying to do?

The main tailscale docker image is hosted on docker hub and ghcr.  Can we also get the k8s-operator image in ghcr?

### What is the impact of not solving this?

docker hub has a limit on how many image pulls you can make, if you reach that limit the k8s-operator will fail to pull.

**Comment by DentonGentry** [comment]
This won't make sense to anyone outside of Tailscale, sorry.

The operator could be added to sync-containers.

**Comment by Protozoan1369** [comment]
> This won't make sense to anyone outside of Tailscale, sorry.
> 
> The operator could be added to sync-containers.

What is "sync-containers"  I don't see a repo in the tailscale org with that name.  I'd be happy to support a PR if I knew where to do so.

**Comment by irbekrm** [comment]
Hey Chris, it's our private build infra, so unfortunately you won't be able to help, but thanks! It should be pretty straightforward though and I think we should be able to set it up soon-ish

**Comment by irbekrm** [comment]
Thank you for opening the issue @Protozoan1369 .

The operator images are now being synced to `ghcr.io/tailscale/k8s-operator`- all the tags should have been synced.
