### ISSUE TITLE
login.tailscale.com not accessible via IPv6

### ISSUE THREAD

**Issue by jonaharagon** [tailscale/tailscale#1010]
**Describe the bug**
I cannot sign in to Tailscale on an IPv6-only Vultr server (which if I understand should be possible?). `sudo tailscale up` hangs indefinitely.

**To Reproduce**
1. Install tailscale on an IPv6-only machine
2. Run `tailscale up`

**Expected behavior**
I should be given

**Screenshots**

```
Dec 11 14:22:11 <hostname> tailscaled[3058]: Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": dial tcp 3.121.18.47:443: connect: network is unreachable
```

```
~# tailscale netcheck

Report:
	* UDP: true
	* IPv4: (no addr found)
	* IPv6: yes, [<redacted>]:49427
	* MappingVariesByDestIP: 
	* HairPinning: 
	* PortMapping: not checked
	* Nearest DERP: New York City
	* DERP latency:
		- nyc: 19.6ms  (New York City)
		- dfw: 21.8ms  (Dallas)
		- sea: 60.3ms  (Seattle)
		- sfo: 61ms    (San Francisco)
		- lhr: 103.7ms (London)
		- fra: 105.1ms (Frankfurt)
		- tok: 156.4ms (Tokyo)
		- sin:         (Singapore)
		- syd:         (Sydney)
		- blr:         (Bangalore)
```

```
~# nslookup login.tailscale.com
Server:		2001:19f0:300:1704::6
Address:	2001:19f0:300:1704::6#53

Non-authoritative answer:
Name:	login.tailscale.com
Address: 3.121.18.47
```

**Version information:**
 - Device: Vultr VPS
 - OS: Debian
 - OS version: 10 Buster
 - Tailscale version: 1.2.10

**Additional context**
Apologies if this is not the correct forum for central-server issues, was unsure if this issue tracker was client-side only. And while I have your attention, maybe I can convince you guys to run a DERP server in Chicago since I think you use Vultr as well :)

**Comment by bradfitz** [comment]
@danderson, @crawshaw, this is a regression. We used to run on Vultr IPv6-only servers.

Did we lose IPv6 in the control server move?

**Comment by bradfitz** [comment]
I've fixed the DNS record.

We'll also fix our monitoring to add a v6-specific check to make sure this doesn't happen again.

**Comment by bradfitz** [comment]
Done.

**Comment by bradfitz** [comment]
@jonaharagon, thanks for the report!
