### ISSUE TITLE
400 Bad Filename for When Using Taildrop to Send Files with Japanese Characters in Filename

### ISSUE THREAD

**Issue by quexten** [tailscale/tailscale#10105]
### What is the issue?

I'm trying to send a file with the name "新完全マスター　N2　文法.pdf" from a Linux device, to an iOS device. Running the command: `sudo tailscale file cp "新完全マスター　N2　文法.pdf" ipad-pro-2020:`, a brief progress bar appears, then `400 Bad Request: bad filename` appears and the copy cancels. Renaming the file works to circumvent the issue.

### Steps to reproduce

Name a file "新完全マスター　N2　文法.pdf", then try to send it via Tailscale send.

### OS

Linux, iOS

### OS version

Fedora 39, iOS 17

### Tailscale version

1.52.1, 1.50.1

### Bug report

BUG-1bae7f72fc1771111a4c9e751d6df23bb2b502d89a91fc82e7be9502d3254301-20231103093521Z-0cb050344cee38d8

**Comment by bradfitz** [comment]
@quexten, what's your terminal's locale? What does `locale` say? Is it UTF-8 or something else?

/cc @dsnet @rhealitycheck

**Comment by quexten** [comment]
Hi Brad, thanks for the quick response. The locale is indeed utf-8, specifically 
```
➜  ~ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I also tried with jp_JP.UTF-8, but that lead to the same result.

**Comment by quexten** [comment]
I did some more digging, and it seems the filename contains 2 [ideographic spaces](https://en.wiktionary.org/wiki/ideographic_space) (`\u3000`), replacing only these with regular spaces, and leaving the rest of the file name the same already seems to fix the problem.

**Comment by dsnet** [comment]
The error on the receiving end is stemming from this check:
https://github.com/tailscale/tailscale/blob/46fd488a6d682b76fb1e4444f5fd0ef96c9b6747/taildrop/taildrop.go#L171

`unicode.IsPrint` allows characters in the Unicode categories "L, M, N, P, S, and the ASCII space character".
It seems safe to allow category Z, which would include U+3000.
Of particular note, Z does *not* include TAB, LF, and CR.

Allowing Z will probably make it easier to mount homogylph attacks, but that attack vector has always been there even with `unicode.IsPrint`.

**Comment by noncombatant** [comment]
Given the pre-existing problem of Unicode (and even ASCll confusables — that's 2 Ls in ASCII :) ), I confirm from a security perspective that allowing Z does not seem like undue additional risk. Most filesystems already let you name files both "\u00e9.pdf" and "e\u0301.pdf" already.
