### ISSUE TITLE
Android+Tailscale: No internet after moving from wifi to cellular

### ISSUE THREAD

**Issue by williamsdyyz** [tailscale/tailscale#10107]
### What is the issue?

After moving out of range of my WIFI, the phone is connected to cellular. The phone and Tailscale say they are connected, but there is no internet.  Can be resolved by either: Airplane mode on/off OR Tailscale app Active->Stop->Active

### Steps to reproduce

I'm at home connected to WIFI. Tailscale says it's connected. VPN and regular internet is working fine on the phone (Pixel 6, Pixel 7, Android 13 & 14)

When I leave home, WIFI goes out of range and the phone switches to cellular.  The phone says 5G data is connected. The Tailscale app say it's active & connected.

If I try browsing to a website in Chrome, eventually you get the error "This site can't be reached  whatever.com's server IP address could not be found.  DNS_PROBE_FINISHED_BAD_CONFIG"

Internet can be restored by toggling Airplane mode or toggling Talescale from Active to Stop and back.

The problem can sometimes be reproduced by toggling WIFI state Android while connected to Tailscale

### Are there any recent changes that introduced the issue?

Have only been using Tailscale for a few months. Pretty sure it's always happened.

### OS

Android

### OS version

13 & 14

### Tailscale version

1.48.2

### Other software

Nothing else unusual. Two phones owned by different people - Pixel 6 & Pixel 7. The problem existed on Android 13 and still happens on Android 14.

Since the problem happens when away from home / not connected to WIFI and affects all network operations whether VPN or not, the rest of my home network is probably not relevant.

**Comment by svenstaro** [comment]
I have exactly this problem with exactly the same phones and Android versions.

**Comment by theonlyderpderp** [comment]
I have the same issue.

**Comment by cterence** [comment]
I experience the same issue. It does not cut connectivity entirely because I can still reach IP addresses. It rather seems to mess-up the phone's DNS.

Contrary to @williamsdyyz, I'm not able to restore DNS connectivity by toggling tailscale or airplane mode.

Tailscale Android version is 1.53.115, running on up-to-date Android 13 on an Asus Zenfone 10.

**Comment by cterence** [comment]
#8283 
Overriding the local DNS solves the issue for me, although not an amazing workaround to impose this to all the devices in the tailnet.
Other similar issues : #8006 #6739 #6891

**Comment by Boztown** [comment]
I experience this as well with a Pixel 4a. After leaving the house (and wifi) and returning I no longer can access the internet from the device unless I disable or toggle Tailscale.

**Comment by r3n3x** [comment]
Same here, with iOS 17.2 beta and Tailscale for iOS 1.54.1.

Interestingly, when switching FROM CELLULAR DATA TO WIFI then this bug happens SOMETIMES.
When switching from WIFI TO CELLULAR, it happens ALWAYS.

My workarounds are
a. either use mobile data "only" (deactivate Wifi at the iPhone alltogether)
or
b. toggle OFF / ON whenever I switched from Wifi to Cellular data.

I hope Tailscale engineers can find a solution to this bug soonest.  Thanks.

**Comment by WreckingU** [comment]
I'm also running into this same issue on my Pixel 8. Glad it's not just me.

**Comment by r3n3x** [comment]
related bug reports: 
https://github.com/tailscale/tailscale/issues/8691
https://github.com/tailscale/tailscale/issues/6075

**Comment by floco** [comment]
It looks like there are some work being done on related issue for iOS (though it seems mainly for exit node): https://github.com/tailscale/tailscale/pull/10680
But it doesn't speak about android.
Very annoying, have to switch off tailscale to restore my pixel 7 internet connectivity, same on pixel 7 pro, samsung A52s, Xiaomi mi 9. Hope a fix will come as otherwise tailscale is great. 
Anyone found a work around, like automating the restart ?

**Comment by crayonix** [comment]
Running into the same issue on a Pixel 5. Would be great if this gets addressed.

**Comment by agottardo** [comment]
None of the participants to this issue has attached a bug report identifier, which makes it hard for us to pinpoint what is wrong with your configuration. Would you mind reproducing the issue, then generating and attaching one here?

**Comment by MisguidedEmails** [comment]
I've reproduced it -  `BUG-36cb8ecc282ea4078027fe0023866ef36eb2445809730b809caa3e4688daf603-20240109150212Z-1573825aa83a3779`

connectivity wasn't working airplane on/off then it was back, both tailscale comms and internet.

Note: On my old phone provider an on/off of tailscale would fix it. but airplane mode on/off did the trick this time. It could be MVNO related (as previously mentioned https://github.com/tailscale/tailscale/issues/6739)

---

well, as I was typing this, the connectivity dropped, so I guess it was only temporary - `BUG-36cb8ecc282ea4078027fe0023866ef36eb2445809730b809caa3e4688daf603-20240109150415Z-ee4bc373aebb65ac`

pinging via termux still seems to work (I don't have other tools atm installed to test DNS/etc)

**Comment by MisguidedEmails** [comment]
just as a follow-up, `1.58.2` was released on f-droid a few days ago, and cellular/dns/etc is working great now :)

**Comment by 9808us** [comment]
Check DNS in phone settings. For me I was using a custom DNS and then no connection to internet if tailscale is on. Then switched to Auto and now I can use internet.
Very annoying

**Comment by luckylinux** [comment]
I also have `1.58.2` and it's NOT working. Neither using WiFi nor Cellular Connection.

Using some "Ping & Net Tools" I can correctly get the DNS Record **only** if I explicitely set the DNS Server to one within my Tailscale Network (100.64.x.y).

But using the "AUTO" Nameservers (which Tailscale sets on Android to `100.100.100.100`) does NOT work. I cannot get any DNS record at all like that.

**Comment by adgrant93** [comment]
Commenting to say on my Pixel 7 (GrapheneOS) and TailScale version 1.58.2 and DNS setting set to "Auto" it is now working for me.

**Comment by Matt-UKTX** [comment]
I have the exact same issue on the Pixel 7 Pro. Is there a fix for this yet? If so, what is it?

**Comment by luckylinux** [comment]
Probably moving to Netbird. since there is no interest around here ... I am facing some issues with the IDP (tried Keycloak, Zitadel, Authentik). Authentik integration with Netbird gives a weird error, but it's the most promising so far.

**Comment by r3n3x** [comment]
I recommend you create a new bug report and refer to this one. Let the team then merge/reopen this report. Because this one (10107) is already marked as "closed" and it seems we (users) can't re-open.

Just to report that since approx. version 1.60 the same issue was fixed for iOS. Tailscale on iPhone now works great.

**Comment by adgrant93** [comment]
> I have the exact same issue on the Pixel 7 Pro. Is there a fix for this yet? If so, what is it?

Setting my phone's DNS to auto and restarting Tailscale resolved this for me.

**Comment by toteto** [comment]
I also don't have internet if I have custom DNS set on my Samsung Android phone

**Comment by lambdadeltakay** [comment]
Setting a custom dns server in the webui makes the android client very very rarely obey said dns servers.

**Comment by antwal** [comment]
I believe the bug has never been fixed; I use a Custom DNS through services like PiHole / Nextdns. 

If I enable Tailscale it does not allow me to access the internet in any way. 
If I disable the Custom DNS, tailscale works and also allows me to access the internet.

I should use tailscale only to access a private network, not to access the internet. 

How do I solve this problem?

**Comment by agottardo** [comment]
The original root cause of this issue was addressed a long time ago.

If you're using a custom Private DNS on your Android phone, please refer to https://github.com/tailscale/tailscale/issues/915 which explains why that's incompatible with Tailscale due to Android limitations.
