### ISSUE TITLE
Does Huawei Hongmeng 4.0 not support Tailscale?

### ISSUE THREAD

**Issue by liangvip2000** [tailscale/tailscale#10131]
uawei Hongmeng 4.0 cannot use Tailscale. When opening the program, it keeps getting stuck in the loading window and cannot be used.

**Comment by DentonGentry** [comment]
Hongmeng 4.0 is https://en.wikipedia.org/wiki/HarmonyOS ?
We've never tested the Android app running on HarmonyOS.

The entire bug template with any additional information we might look into has been deleted, closing as complete.
