### ISSUE TITLE
wrong `/etc/resolver` file for Split-DNS nameserver using `tailscaled-for-macOS`

### ISSUE THREAD

**Issue by jukna** [tailscale/tailscale#10134]
### What is the issue?

When multiple nameservers are defined for a split-DNS domain, the related resolver file in /etc/resolver is formatted wrongly.
the resolver file includes the nameservers in one nameserver-line. Instead there should be one line for each nameserver.

Excerpt from `man resolver`:
"Up to MAXNS (currently 3) name servers may be listed, one per keyword."

### Steps to reproduce

Add two Split-DNS Nameserver for one domain
tailscale down 
tailscale up

Look at /etc/resolver/<domain>

### OS

macOS

### OS version

macOS Sanoma

### Tailscale version

1.52.1

### Bug report
BUG-92eac11d3f471af83445e7d3d93c321769e53f9ce8d1cd62037da4bb4cb40582-20231106172549Z-29475c8dab33ec86

**Comment by bradfitz** [comment]
Which variant of Tailscale on macOS are you using? There are three. (https://tailscale.com/kb/1065/macos-variants/)

You didn't include the template's requested bugreport so we can't tell.

**Comment by jukna** [comment]
I've added the bugreport to the summary now
It's the tailscale & tailscaled CLI version.

**Comment by bradfitz** [comment]
> "Up to MAXNS (currently 3) name servers may be listed, one per keyword"

You say that's in `man resolver`, but I don't see that in macOS man pages. Where do you see that?

Do you have more than 3 name servers?

**Comment by jukna** [comment]
I  found the man-pages (https://www.manpagez.com/man/5/resolver/) when searching the web and didn't notice that  precisely it's 'man 5 resolver' instead of 'man resolver'

I'm just using 2 nameserver.

i found an additonal hint:
scutil --dns shows just one nameserver when having both nameserver defined in one nameserver line. Having two lines with one namerserver in each line, scutil --dns shows the correct (expected) result.
