### ISSUE TITLE
Any user on a signing node can sign

### ISSUE THREAD

**Issue by lejtmany** [tailscale/tailscale#10141]
### What is the issue?

Hi,

I was suprised to find that on a tailnet with tailnet lock enabled *any* user is able to run `tailscale lock sign`. Is this the desired behavior? Is there any way to lock it down that this can only be done by root?

Thanks!

OS: Fedora 38 (6.5.8-200.fc38.x86_64)
Tailscale version:
```
x@fedora:~$ tailscale --version
1.52.1
  tailscale commit: 75d3c93858d7c9f80495fdae9e88967382ea333e
  other commit: 3e9627f3b3d109a0d99699a683cf457e99379215
  go version: go1.21.3


### Steps to reproduce

1. Enable tailnet lock
2. su other-unpriviliged-user
3. tailscale lock sign <key> <key> 
4. success

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

Fedora 38

### Tailscale version

1.52.1

### Other software

_No response_

### Bug report

_No response_

**Comment by twitchyliquid64** [comment]
Fixed by https://github.com/tailscale/tailscale/commit/f0bc95a066b95bc61e8bcc54b8746b6321cf36c5 (Thanks @awly!) and will be out with the next release.
