### ISSUE TITLE
cmd/k8s-operator: helm chart missing configuration keys

### ISSUE THREAD

**Issue by GMartinez-Sisti** [tailscale/tailscale#10182]
### What is the issue?

Following https://github.com/tailscale/tailscale/pull/9920, I noticed that a lot of configuration keys are not part of `values.yaml`, this is where chart users get to know the available options to configure the helm chart.

On an initial check from [cmd/k8s-operator/deploy/chart/templates/deployment.yaml](https://github.com/tailscale/tailscale/blob/ed1b935238a7c6cce3aa4865aa13181eb679361a/cmd/k8s-operator/deploy/chart/templates/deployment.yaml) at least these are missing:
```
.Values.operatorConfig.podAnnotations
.Values.imagePullSecrets
.Values.operatorConfig.podSecurityContext
.Values.operatorConfig.securityContext
.Values.operatorConfig.resources
.Values.operatorConfig.nodeSelector
.Values.operatorConfig.affinity
.Values.operatorConfig.tolerations
```

Happy to check them all and send a PR, please let me know.

**Comment by irbekrm** [comment]
@GMartinez-Sisti thanks for opening the issue.

We originally took out everything that didn't have a default value.

But I agree about discoverability.

> Happy to check them all and send a PR, please let me know

Happy to review a PR 😄

**Comment by GMartinez-Sisti** [comment]
> Happy to review a PR 😄

I'll create it during the weekend!

**Comment by GMartinez-Sisti** [comment]
@irbekrm took a little longer but it's here 😄
