### ISSUE TITLE
Enable/disable client side settings via admin

### ISSUE THREAD

**Issue by jack1902** [tailscale/tailscale#1019]
**Is your feature request related to a problem? Please describe.**

Currently not an issue but one that might come up depending on the thought process taken for new features in the future.

**Describe the solution you'd like**

I would like to ensure that any `node` options that come along in the future also have the ability to be completely turned off at the `admin` level. This is so that whilst features that might be beneficial to some end-users like "don't use corporate dns" might be desirable, other times this can cause many issues (an end user turns off `corporate-dns` and then wonders why their network no longer works and raises an IT Support ticket)

For example, i am currently looking into the `opt-in` default routes as mentioned in https://github.com/tailscale/tailscale/issues/102 . I didn't want to post this on there as i see this as a seperate issue. I believe it should be possible to make client side features grayed-out based on their settings within the `admin` UI. If in the `admin` UI, i stated that its not possible to turn off the `default-route` when connected to `tailscale` then the option should be greyed out on the client-side.

Another easier one that can exist is the `corporate-dns` when connected to tailscale you will be forced to use the DNS servers set in `admin` and cannot easily override this (there used to be a toggle switch in the MacOS client but i no longer see it [Catalina 10.15.7] (Tailscale 1.2.4)

**Comment by bradfitz** [comment]
> there used to be a toggle switch in the MacOS client but i no longer see it [Catalina 10.15.7] (Tailscale 1.2.4)

See #1014. It's now behind the Option-click menu.

**Comment by jack1902** [comment]
also just saw https://github.com/tailscale/tailscale/issues/863 so will close this issue as i see it as the `network` wide settings
