### ISSUE TITLE
Tailscale for macOS Randomly Logs Off

### ISSUE THREAD

**Issue by aaronbacklund1** [tailscale/tailscale#10217]
### What is the issue?

The Tailscale macOS app logs me out randomly on my Mac mini desktop computer preventing me from being able to remote into the computer since the Tailscale app isn't logged into my Tailnet. I can't log back into the Tailscale desktop app since I am not able to physically access the computer.

### Steps to reproduce

Log into the Tailscale app and give it a few days then check to make sure that the app is still logged in if not then there is the issue.

### Are there any recent changes that introduced the issue?

The issue started appearing Summer 2023 I still had the mac on macOS Ventura and the issue then carried over even with updates to the Tailscale app and my upgrade to macOS Sonoma. 

### OS

macOS

### OS version

macOS Sonoma 14.1

### Tailscale version

1.52.0 Mac App Store Variant

### Other software

Just Dropbox and OneDrive I have no other VPN apps or configurations enabled on the mac.

**Comment by DentonGentry** [comment]
The template asks for a bugreport because without it, we cannot look up any telemetry nor do anything to diagnose the issue. Even a bugreport from another device on the tailnet would allow us to find a Mac on the same tailnet.

**Comment by bradfitz** [comment]
Maybe that low disk space issue where macOS restarts things in desperate attempts to free up disk? (#8220, etc)

**Comment by refrainsclub** [comment]
Hello, I am also experiencing this problem on macOS Sonama 14.0. However I am using the standalone version. This bug occurred as soon as I updated the Tailscale app.

FB12691478 shows up briefly when clicking the Tailscale icon on the system tray. This could be related to #8673?

**Comment by Atemu** [comment]
I'm experiencing this using the app-store app on Ventura. Whenever it happens, the daemon is dead according to the CLI tool.

My space is low but not extremely low. Currently 8G remaining which isn't much but not nothing either.

**Comment by aaronbacklund1** [comment]
Sorry for the delay on the request it seems this issue has been resolved. For those few who are still having this issue, please log in to your Tailscale Admin Console Dashboard from a web browser. First, click on the machines tab then locate the machine that has the issue on the very far right of the machine in the list and click the three dots button. Then click the button "Disable Key Expiry". Only do this on a device you want to always remain logged in like your mobile device or laptop it should be a trusted device. You will need to repeat these steps for every device you want to stay logged in. I hope this info helps! -- Aaron

**Comment by kode54** [comment]
Just FYI, since this tripped me up. macOS automatically disconnects VPN services if you switch user accounts on the machine. Even if you don't log out of the one which is authenticated with Tailscale.
