### ISSUE TITLE
Tailscale iOS widget not updating after MagicDNS "on-demand" connection is initiated

### ISSUE THREAD

**Issue by johannrichard** [tailscale/tailscale#10218]
### What is the issue?

The iOS widget is not updating the connection state from "not connected" when "VPN On-Demand" and "Detect MagicDNS hostnames" are enabled in Tailscale iOS and a MagicDNS connection is established with Tailscale iOS not being the active app. The widget remains in "not connected" state even when Tailscale is opened after having established the connection.

### Steps to reproduce

- Add the Tailscale Widget on iOS Home Screen
- Enable "VPN On-Demand" and "Detect MagicDNS hostnames" 
- Open an app that tries to initiate a connection to a MagicDNS hostname
- Tailscale connects in the background
- The Widget remains on "not connected"
- Open Tailscale iOS
- Return to the Home Screen, Widget still shows "not connected"

### OS

iOS

### OS version

17.1.1

### Tailscale version

1.53.115

### Bug report

BUG-8c4f73d753b76ebb80c2750a608cda9ee624b47fcab3e890617f46ca523c1582-20231112190417Z-c4cc5f4a508f3038

**Comment by agottardo** [comment]
Did the latest 1.54 update fix this for you by any chance?

**Comment by johannrichard** [comment]
> Did the latest 1.54 update fix this for you by any chance?

Unfortunately not.

**Comment by agottardo** [comment]
I was also able to reproduce this. We'll take a look.

**Comment by agottardo** [comment]
I have pushed a fix for this, which should land in the next TestFlight update. It should fix the issue you reported. 

Note however that widgets are not guaranteed to _always_ update so there is a change this might only solve the problem partially. iOS can throttle or block widget update to preserve battery life. This is particularly likely when the widget state is changed from a background process, such as in this case: you're not interacting with the main Tailscale app and the state update is triggered by the VPN framework, so the system deems the update not urgent.
