### ISSUE TITLE
[bug] tailscale fails to parse ip address with `--advertise-routes=`

### ISSUE THREAD

**Issue by ykuksenko** [tailscale/tailscale#10210]
### What is the issue?

According to https://github.com/tailscale/tailscale/issues/370 tailscale should be able to advertise single IPs
- The code seems to imply that it is supposed support single ips https://github.com/tailscale/tailscale/blob/86c8ab7502a38b4de05308355fe0c847e4e78167/net/netutil/routes.go#L50-L53
- The test suite seems to be missing a check for single IPs without a netmask. When actually trying to do this it fails to parse an IP. https://github.com/tailscale/tailscale/blob/86c8ab7502a38b4de05308355fe0c847e4e78167/cmd/tailscale/cli/cli_test.go#L601-L614

```
/ # tailscale --socket /tmp/tailscaled.sock up --advertise-routes=10.10.10.0/24,10.10.11.1 --accept-dns=false --accept-routes --advertise-exit-node --hostname=exit-node --login-server=https://example.com --netfilter-mode=off --snat-subnet-routes=false
"10.10.11.1" is not a valid IP address or CIDR prefix
```
- The IP is an address in my routing table without a `/32`.
- The command works if I add a `/32` to the single IP.
- The problem is that OSPF adds the route without the `/32` in the routing table. I would prefer not to make this a static route with a `/32`.

### Steps to reproduce

Run the mentioned command, it seems to be a parsing error.

### Are there any recent changes that introduced the issue?

Adding the single IP without a netmask.

### OS

Linux, Other

### OS version

Podman with fedora 38

### Tailscale version

1.52.0

### Other software

```
tailscale 1.52.0 docker image
tailscale commit: 31e1690f38c5de5ebe25d7735d368bbe9c7d2f28
go version: go1.21.3
```

**Comment by DentonGentry** [comment]
This is working as intended, please add the /32.
Interpreting a bare IP address as a /32 is too much of a footgun.
