### ISSUE TITLE
Expiry date on ACL rules

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1022]
Suggested by a user: ACL rules could have an expiry date, after which the ACL automatically revokes itself.

This feeds into a general theme where we'd like access-granting operations to expire by default as a security feature (we've talked about doing something similar with node sharing). It's unclear if we want to support this for ACLs, but I'm filing a bug to remember the idea.

**Comment by bradfitz** [comment]
See also: #1023 ("Provide time-limited access to devices for users"), the general problem. This bug is one possible solution for it.

**Comment by DentonGentry** [comment]
At this point because https://github.com/tailscale/tailscale/blob/main/api.md supports get/set on ACLs, I wouldn't recommend we proceed with this. A user with unique needs in their ACLs has sufficient tools to do so without adding to the complexity of the product.

**Comment by DentonGentry** [comment]
Closing during bug scrub.

**Comment by kamalmarhubi** [comment]
@DentonGentry I came across this, and I think that expiry is special enough to be part of the ACL system. Implementing "expiry" via the API means that the desired access controls now depend on some infrastructure that I have to run. If that fails, then short-lived access can become long-lived access.

It's not failing open, but it is "failing ajar" which is pretty undesirable.
