### ISSUE TITLE
Replace syscall package usage with golang.org/x/sys?

### ISSUE THREAD

**Issue by TimothyGu** [tailscale/tailscale#1024]
Hi, I noticed that Tailscale uses the syscall package [quite extensively](https://github.com/tailscale/tailscale/search?q=syscall) right now, especially on Windows. However, it looks like syscall is [deprecated](https://golang.org/s/go1.4-syscall) in favor of [golang.org/x/sys](https://pkg.go.dev/golang.org/x/sys). Would the maintainers be open to a patch to migrate away from syscall as much as possible?

**Comment by bradfitz** [comment]
Maybe not "a patch", which I suspect would require too many review rounds to make it in. But a few small ones (e.g. one per package) might be okay.

**Comment by TimothyGu** [comment]
Sounds good. Will divide into three small PRs, each with a few files.

**Comment by DentonGentry** [comment]
This was opened 9 months ago, and other than a sense of general embetterment there isn't a compelling reason to do it.

Barring further updates or progress on implementation, we'll expect to close this during the next bug scrub,

**Comment by TimothyGu** [comment]
Indeed, there's no need :)
