### ISSUE TITLE
Help/Advice: Feature request

### ISSUE THREAD

**Issue by omar391** [tailscale/tailscale#1026]
Dear maintainers,

I need the following features:

- Bandwidth controlling
- Split tunneling
- Data Limit per month basis
- User/peer registration and auto-config generation
- HTTP request caching via reverse proxy

Which of these features are available or which can be integrated via GO code?

**Comment by danderson** [comment]
Split tunneling is the default for Tailscale. There is no registration beyond having users log in with their SSO credentials (gsuite, office365, okta, ...).

We don't have the other features, and it's not clear why you want them. What are you trying to do? If you want to build a product that integrates with Tailscale somehow, it's probably better to email info@tailscale.com to schedule a call, so we can better understand what you're building and see how we could help.

**Comment by omar391** [comment]
@danderson, To be precise, yes, I want to make a VPN product based on WireHurd rather than OpenVPN. OpenVPN has such features included with its admin panels. But I am having a hard time finding all these features set within any WireGurd admin panels. So, it seems I might need to develop them. So before moving with custom development I need to make sure if tailscale has those.

**Comment by danderson** [comment]
I suggest you try Tailscale for yourself, you can get it at https://www.tailscale.com . You can use the solo version without paying anything, and that'll let you explore and see what the product offers. Once you've given it a try, we can help you more at info@tailscale.com.
