### ISSUE TITLE
Unable to connect after the update to 1.54.0

### ISSUE THREAD

**Issue by dtech77pl** [tailscale/tailscale#10277]
### What is the issue?

After updating from 1.52.1 to 1.54 on the Arch Linux I'm unable to connect with the machine using tailscale. 
I have to ssh to the machine using the local IP address to execute the "tailscale status", and everything is back to normal. The only problem is that for some of the machines I do not have access to a local IP address. 

I have tried a couple time reboots and nothing helps unless the "tailscale status" command is executed. 

### Steps to reproduce

Update from 1.52.1 to 1.54.0

### Are there any recent changes that introduced the issue?

Except update tailscale to the latest version no changes. 

### OS

Linux

### OS version

Arch Linux Kernel 6.5.9

### Tailscale version

1.54.0

### Bug report

BUG-9d28e7d1f16fe65a159a0b31c226923083cc9ae280315055511d278ad66b86cd-20231116115218Z-e87d881ea345895b

**Comment by knyar** [comment]
Based on the bug report, I can see some errors in the logs indicating that the state file (/var/lib/tailscale/tailscaled.state) is on a read-only partition (which is not supported), but currently the node seems to be online.

It's surprising that you see anything change when you run `tailscale status`. Are you able to share the logs indicating what happens at the moment of you running that command? Or perhaps generate another bug report and share the specific time when you ran `tailscale status` and what changes you observed?

**Comment by dtech77pl** [comment]
The system is on the read-only partition by the design, all works are expected. 
I have a second machine which is still not updated. 

This is a bug report taken at 18:05 16.11.2023, just before the update from 1.52.1 to 1.54.0
BUG-8898ea61bb9b9cb857181208300343a4364c246818361258722c37f3880f1600-20231116170457Z-4b4ba3a77a5fd6dd

When I try to get a bug report just after the update:
tailscale bugreport
503 Service Unavailable: no backend

tailscale status
# Health check:
#     - not in map poll
unexpected state: NoState


This is a bug report taken at 18:12 16.11.2023, just after the reboot when tailscale is updated to 1.54.0
BUG-29dc0494cc9ea4d7f07a25dc854f8a5ef25850d74521472c14841e994ee913aa-20231116171240Z-007181e43a2805a3

**Comment by dtech77pl** [comment]
Thanks to the Knyar I found a solution, before updating tailscale to the newer version I setup system files to be RW at all times. 
This allows Tailscale to up services and work as expected. After the validation of the proper update system is back to RO mode. 
This is applicable for PiKVM both V3 and V4.

Issue can be closed.
