### ISSUE TITLE
Can't restrict access to bare hostname so https security warning is still shown

### ISSUE THREAD

**Issue by harrisonfang-helm** [tailscale/tailscale#10289]
### What is the issue?

We are using Tailscale with https enabled and MagicDNS. We have a server running on one of the machines, let's call it `monitoring`. Let's also assume the tailnet is called `yak-bebop.ts.net`. 

This `monitoring` server accepts both http and https traffic (though the http page is really just some documentation explaining that https is necessary). We have used `tailscale cert monitoring.yak-bebop.ts.net` to get the latest TLS certificate and configured our server accordingly. Now, we're observing the following behavior:

* `https://monitoring.yak-bebop.ts.net` works as expected.
* `http://monitoring.yak-bebop.ts.net` redirects to using https and works as expected.
* `http://monitoring/` shows the http version of the page as expected.
* `https://monitoring/` shows up in chrome with the privacy error saying that the connection is not secure (screenshots attached below).

Based on the [tailscale documentation](https://tailscale.com/kb/1153/enabling-https/), it seems like this is a known issue.

<img width="779" alt="Screenshot 2023-11-15 at 3 18 27 PM" src="https://github.com/tailscale/tailscale/assets/88349937/46460c96-4ac7-452f-9c20-6c1284d796ee">

My networking knowledge is a bit limited, but I think the issue is that MagicDNS allows the user to access the server via the bare hostname and our nginx server doesn't know what's in the URL. It only knows whether it's being accessed via the http or https port. Ideally we would want `https://monitoring/` to point to the fully qualified domain at `https://monitoring.yak-bebop.ts.net`. I think this kind of redirect would typically be done using a CNAME entry but we can't customize MagicDNS.

Probably the simplest way to resolve this issue would be to allow people to disable MagicDNS for specific machines. In our case, we would just prevent people from accessing the server with the bare hostname entirely.

![Screenshot 2023-11-16 at 11 55 45 AM](https://github.com/tailscale/tailscale/assets/88349937/39050c91-8c3b-4880-89eb-0ef0f105e0a3)
![Screenshot 2023-11-16 at 11 56 28 AM](https://github.com/tailscale/tailscale/assets/88349937/ec94dc97-6575-483c-a503-7a369ee49368)

### OS

Linux

### OS version

Alpine Linux v3.16.7

### Tailscale version

1.48

### Other software

Our server is running on kubernetes.

```
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.10-gke.2700
WARNING: version difference between client (1.28) and server (1.25) exceeds the supported minor version skew of +/-1
$ 
```

The following containers are running:

* tailscale (ghcr.io/tailscale/tailscale:v1.48)
* nginx (nginx:1.25.1)
* oauth2 proxy (quay.io/oauth2-proxy/oauth2-proxy)
* dex (bitnami/dex)

### Bug report

BUG-deadcd6a12ba21740d5c742931c72f975a257fa2795835202f3e19dc473a8683-20231116194934Z-42c12a28f6361de0

**Comment by knyar** [comment]
> our nginx server doesn't know what's in the URL

I believe that your nginx server actually does know the URL, and if you want https://monitoring/ to redirect to https://monitoring.yak-bebop.ts.net, you should be able to configure a redirect in nginx, e.g.

```
server {
    listen 80;
    server_name monitoring;
    location / {
        rewrite (.*) https://monitoring.yak-bebop.ts.net$1 redirect;
    }
}
```

**Comment by harrisonfang-helm** [comment]
Hi Anton, thanks for the advice. It pointed me in the right direction to resolve our issue. For others who may come across this thread, the key thing to note is that you must use `redirect` instead of `permanent` otherwise your browser will still prevent the server from responding. Here's a truncated version of our nginx config.

```
http {
    server {
        listen              443 default ssl;
        server_name         monitoring;
        ssl_certificate     /etc/nginx/cert.pem;
        ssl_certificate_key /etc/nginx/cert.key;
        add_header          Strict-Transport-Security max-age=2592000;

        location / {
            if ($host == monitoring) {
                rewrite ^/(.*) $scheme://monitoring.yak-bebop.ts.net/$1 redirect;
            }
            # whatever your server should respond with here
        }
    }

    server {
        listen              80 default_server;
        server_name         monitoring-80;

        location / {
            rewrite (.*) https://monitoring.yak-bebop.ts.net$1 redirect;
        }
    }
}
```

**Comment by harrisonfang-helm** [comment]
Oh actually, can we reopen this? It's because I clicked the button to proceed anyways so it remembered my response.

You're right that we can redirect the http server to the https server. But the issue here is that we cannot have the https server redirect itself because the browser will not allow it to respond unless it present the correct certificate.

**Comment by harrisonfang-helm** [comment]
@knyar please see the updates above

**Comment by knyar** [comment]
> You're right that we can redirect the http server to the https server. But the issue here is that we cannot have the https server redirect itself because the browser will not allow it to respond unless it presents the correct certificate.

Yeah, that's expected, since we can only create valid public certs for FQDNs. If you'd like to use HTTPS, I believe you will need to use full hostnames. But if you use HTTP or some other protocol, short names can be more convenient. Note that even with HTTP, traffic between machines are encrypted by Wireguard.

**Comment by harrisonfang-helm** [comment]
@knyar Right, we can use the FQDN for now but maybe this thread can be reopened and converted into a feature request. Ideally in our case we would like to disable the short names because showing a 404 is preferred over the browser's privacy error.

**Comment by harrisonfang-helm** [comment]
I see, thanks for the nginx module pointer. We can give this a try.

Some more context: This has surfaced because we used to copy the URL and share the short name links outside of the browser. At the time, this was fine because we hadn't set up the SSL cert yet so you would get the validation error either way. Now that we do have a valid certificate, we want to disable all of the old short name links that were previously shared. The type of error shown is mostly preference but in our case, the link is shared externally with customers so it seems more professional to show a DNS error which clearly indicates that the link is incorrect.
