### ISSUE TITLE
Invalid value: "ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-6db48787fc": must be no more than 63 characters

### ISSUE THREAD

**Issue by Shaked** [tailscale/tailscale#10284]
### What is the issue?

It's not possible to use cluster egress https://tailscale.com/kb/1236/kubernetes-operator/#cluster-egress when the service's name is too long. When using a 3rd party chart/manifests, it's not always possible to control the name of the service, which might be too long before applying TS' code. 

The problem occurs because of the usage of  `sts.ParentResourceName`. I am not sure why the `tailscale.com/hostname` isn't used here:

https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/sts.go#L182

It would be great to be able to override the name in cases like this.

### Steps to reproduce

1. Create a service with a long name like `prometheus-kube-prometheus-prometheus-thanos` 
2. Apply TS annotations:
```
tailscale.com/expose: true
tailscale.com/hostname: thanos-name
```
3. Check kubernetes events

Expected: it should create a stateseful even when the original service's name is too long using the defined hostname 
Actual: 

```
tailscale       3s          Warning   FailedCreate                 statefulset/ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp     create Pod ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-0 in StatefulSet ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp failed error: Pod "ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-0" is invalid: metadata.labels: Invalid value: "ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-6db48787fc": must be no more than 63 characters
``` 

### Tailscale version

latest chart

**Comment by irbekrm** [comment]
> tailscale       3s          Warning   FailedCreate                 statefulset/ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp     create Pod ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-0 in StatefulSet ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp failed error: Pod "ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-0" is invalid: metadata.labels: Invalid value: "ts-prometheus-kube-prometheus-prometheus-thanos-5n9pp-6db48787fc": must be no more than 63 characters


I think this error is about the autogenerated `controller-revision-hash` label value that by default contains the name of the StatefulSet + a hash so ends up being longer than the max allowed value of Kubernetes labels - see https://github.com/kubernetes/kubernetes/issues/64023.
Our code should not have an issue with long `Service` names - we use [kube name generator](https://github.com/tailscale/tailscale/blob/v1.54.0/cmd/k8s-operator/sts.go#L182) that ensures that the value gets truncated and remains unique.

> I am not sure why the tailscale.com/hostname isn't used here

There is no uniqueness enforcement on hostnames when they are applied. If there are multiple tailnet devices attempting to use the same hostname, the names will get an integer suffix, but the operator has no way of discovering that at a time of creating cluster resources.

**Comment by Shaked** [comment]
@irbekrm 

I have pointed to the same line of code in my original issue: 

https://github.com/tailscale/tailscale/blob/c82fd1256bec9ff55e447a64d9054b9f79b4e1de/cmd/k8s-operator/sts.go#L182

This comes from line 174, which is the service name: 

https://github.com/tailscale/tailscale/blob/dd8bc9ba0379984f8e9111944f920886f609310c/cmd/k8s-operator/svc.go#L173-L178

Doesn't this mean that if the `Service` name is `prometheus-kube-prometheus-prometheus-thanos` (44 chars), adding `ts-` (3 chars) and `5n9pp` (5 chars) then this issue will occur?

**Comment by irbekrm** [comment]
Thank you for spotting the bug and creating the issue @Shaked .

This was fixed in https://github.com/tailscale/tailscale/pull/10343 and the latest operator tag `unstable-v1.55.68` has the fix.
