### ISSUE TITLE
Tailscale commands don't work by default when using docker image

### ISSUE THREAD

**Issue by harrisonfang-helm** [tailscale/tailscale#10290]
### What is the issue?

We're running tailscale with the following docker image: ghcr.io/tailscale/tailscale:v1.48

As mentioned in [this comment](https://github.com/tailscale/tailscale/issues/5072#issuecomment-1214334796), it seems like the docker image uses a different temporary directory instead of the default expected by tailscale. This means that trying to run tailscale commands will fail unless we symlink the two.

```
/ # tailscale bugreport
Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
/ # mkdir -p /var/run/tailscale && ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock
/ # tailscale bugreport
BUG-deadcd6a12ba21740d5c742931c72f975a257fa2795835202f3e19dc473a8683-20231116194934Z-42c12a28f6361de0
/ #
```

### OS

Linux

### OS version

Alpine Linux v3.16.7

### Tailscale version

1.48

### Bug report

BUG-deadcd6a12ba21740d5c742931c72f975a257fa2795835202f3e19dc473a8683-20231116194934Z-42c12a28f6361de0

**Comment by realyangex** [comment]
I encountered the same problem and searched for many solutions, but it still didn't work. When I found the page [](https://github.com/dhermes/tailscale-wsl2) . 
Later, I tried running the command "find/- name tailscale.sock". Find the tailscaled.lock path as "/run/tailscale/tailscale.sock".
 Then I run "tailscale --socket /run/tailscale/tailstage.sock". Unexpectedly, it ran successfully in the end.  Good luck

**Comment by irbekrm** [comment]
Thank you for reporting the issue folks.

We've now symlinked `/run/tailscale/tailscale.sock` to the socket path used in the container (see https://github.com/tailscale/tailscale/pull/10518) so now you should be able to run `tailscale` commands in the container without having to set the socket path. Please let us know if there are any further issues.

`v1.56.0` and newer tags will have this fix.

**Comment by irbekrm** [comment]
Closing as fixed in https://github.com/tailscale/tailscale/pull/10518
