### ISSUE TITLE
FR: gitops-pusher does not support OAuth clients

### ISSUE THREAD

**Issue by timtailscale** [tailscale/tailscale#10301]
### What are you trying to do?

The gitops-pusher tool only supports API keys, which expire after 90 days. Adding support for OAuth clients would allow for access that doesn't expire.

### How should we solve this?

Add support for OAuth clients in the gitops-pusher tool.

### What is the impact of not solving this?

Users have to update the API key every 90 days.

### Anything else?

https://github.com/tailscale/tailscale/tree/v1.54.0/cmd/gitops-pusher

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/blob/c82fd1256bec9ff55e447a64d9054b9f79b4e1de/cmd/gitops-pusher/gitops-pusher.go#L165-L171

**Comment by timtailscale** [comment]
Don't know how I missed that, thanks for pointing it out @DentonGentry!
