### ISSUE TITLE
admin: confirm before removing machines

### ISSUE THREAD

**Issue by hspak** [tailscale/tailscale#1030]
**Is your feature request related to a problem? Please describe.**

I fat fingered trying to Disable Subnet Routing on a machine from the admin panel and I accidentally hit "Remove".

**Describe the solution you'd like**

A confirmation modal or pop-up would be nice just to add some extra safety.

**Describe alternatives you've considered**

Avoiding fat fingers are hard because I'm a mere human.

**Additional context**
This "Remove" button
![Screenshot from 2020-12-15 16-52-04](https://user-images.githubusercontent.com/841216/102277480-37cfec80-3edd-11eb-8b04-138dcc5a3310.png)

**Comment by rosszurowski** [comment]
Related to #984.

Eeep! Sorry. We're thinking about either adding a confirmation (perhaps with a fast opt-out, like "hold Cmd while deleting to skip this confirmation") or allowing undoing node deletion for a short period after taking the action.

**Comment by rosszurowski** [comment]
I'm going to close this issue in favor or #984, since they're effectively the same. Subscribe there for updates!
