### ISSUE TITLE
Share access fluctuating when shifting network from local to LTE.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1031]
Once the share is connected successfully and content of share is accessible using Tailscale IP over Wi-Fi -> change network to LTE -> samba share is unaccessible .
______________________________________________
This issue reproduced with 

100.106.182.107 - Linux samba server Ubuntu 20.04 
100.121.106.116 - IOS device14.1
Tailscale : 1.2.10
_______________________________________________
Issue is reproduced with above network at 2:36 PM UTC on 16th Dec.,2020

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2l8gh)

**Comment by bradfitz** [comment]
I can't reproduce this. I can access my Linux samba server from my iOS phone (using the native Files app) using either Wifi or LTE.

**Comment by darshinimashar** [comment]
This is happening intermittently. I can reproduce and give you access to the machines if that helps

**Comment by darshinimashar** [comment]
Also, can you try to flip over from wi-fi and LTE and vice versa? I am talking about the contents of the shared folder, the connection shows established but files in that folder are not showing.

**Comment by bradfitz** [comment]
Yes, I flipped back and forth. I can navigate directories & list/open files on either.

**Comment by darshinimashar** [comment]
The first scenario:

1. Connect to Tailscale and leave it connected
2. Connect to my local Wi-Fi network
3. Connect to smb://100.106.182.107 ✔
4. Switch to my Wi-Fi hotspot (4G on my phone)
5. Connect to smb://100.106.182.107✔
6. All good :)

The second scenario:

1. Connect to Tailscale and leave it connected
2. Connect to my local Wi-Fi network
3. Connect to smb://100.106.182.107 ✔
4. Switch to my Wi-Fi hotspot (4G on my phone)
5. Connect to smb://100.106.182.107 ❌
6. Disconnect Tailscale and connect again
7. Connect to smb://100.106.182.107 ✔

But reconnecting Tailscale does not work out all the time.

**Comment by DentonGentry** [comment]
User is on MacOS

**Comment by DentonGentry** [comment]
Possibly the same issue, on iOS: https://github.com/tailscale/tailscale/issues/1668
User reports that the most recent instance was after switching Wi-Fi networks. Previous instances may have been as well, didn't think to check

**Comment by DentonGentry** [comment]
User reports every time device shifts between Wi-Fi networks, like 2.4G <-> 5G, connectivity is lost.

**Comment by darshinimashar** [comment]
One of the User reports,

Steps To reproduce:  
    
- tailscale is up and running
- use chrome browser to go to the website to verify internet access
- change networks ( either change from WiFi to LTE (by leaving the house and returning or by switching from 2.4 to 5 on  your router if able)
- go back to the browser and select another page.  If it does not load, stop tailscale
- if the page loads, then tailscale was preventing access

Expected behaviour:  That tailscale recognizes a change in networks and does the change without affecting standard internet access

**Comment by bradfitz** [comment]
One user reports that this no longer happens and we haven't heard recent reports that this is still a problem from other users. So closing for now. Probably fixed.
