### ISSUE TITLE
There are always people I don't know who have joined my users.

### ISSUE THREAD

**Issue by zzffking** [tailscale/tailscale#10316]
### What is the issue?

There are always some other users in my console. They have the same mailbox suffix as me. I can see their login log and their device information. What's the situation?

 organization’s name:  li.cm
The picture below is a user.

### Steps to reproduce

<img width="1089" alt="iShot_2023-11-19_01 11 35" src="https://github.com/tailscale/tailscale/assets/21301606/e77ca2d2-7ffe-427c-9b57-64fac3a8ecf0">

**Comment by DentonGentry** [comment]
It had been categorized as a corporate domain, we've adjusted it to split it up as a service provider.
