### ISSUE TITLE
FR: Something more affordable for someone with a gigantic catholic family

### ISSUE THREAD

**Issue by dmacstack** [tailscale/tailscale#10327]
### What are you trying to do?

I know this probably doesn’t belong here and it should just be closed, sorry, I’m kinda desperate. 

Sooo, I’m part of very large old school catholic family. To give you an idea, if you were to combine the families of my grandparents children and their children’s children, etc, on both sides of my family, the number is easily over 200. I don’t know the exact number. 

I’m trying to create a network of however many of my extended family members want to join without spending a small fortune. There’s plenty of reasons to create the network, but the two main ones are so we can all share a large server where we can store the mostly really old photos we’ve collected of relatives that are no longer with us, plus the regular family photos and stuff. I’d also like to be able to quickly remote in to help my older relatives without much hassle. 

Cloud services are not well-designed for this, they’re designed for a “normal” sized family.
e.g. Apple iCloud only allows you to have 5 family members, which is hilarious to me because I would need 3 separate family plans to cover my mom, myself, and my siblings.
I could do an enterprise plan with one of the big providers but everyone would need new emails and that’s just not a headache I want to deal with.

None of my family members are tech savvy outside of myself and 1 of my cousins, so it needs to be reaaaaally simple. 

I tested Tailscale plus a file share with a couple of siblings and they loved how they just saw the pictures appear in Finder/Explorer/Files App/etc.

I see a light at the end of the tunnel, a very expensive tunnel.

### How should we solve this?

I have no idea. Ideally maybe create a cheaper family plan that doesn’t limit the number of sign in users. The ease of downloading an app and clicking “sign in with google/apple” was a key usability feature for them.

### What is the impact of not solving this?

Nobody shares anything because it’s too hard for them.

### Anything else?

Help?

**Comment by A-z-z-y** [comment]
The free plan allows for 3 users, but more importantly, 100 devices. You can sign in to all devices within two or three separate tailnets to allow for 200 or 300 devices (whilst still under one account), and set up those tailnets to one server (perhaps via containers, see [this](https://hub.docker.com/r/tailscale/tailscale)). The server would be a centralized location between the tailnets, where you could host those photos and such, or possibly route between the tailnets if needed. The obvious caveat is needing to use one or at most a few accounts for all of those devices, but this could be accomplished via a seperate and dedicated google/github/whatever account, where you privately share the credentials.

Obviously, this would be difficult, but if you're looking for something that won't completely break the bank, this is what I could come up with.

**Comment by clarkmcc** [comment]
Hope I don't get skinned alive for suggesting this here but I am using both Tailscale and https://netbird.io/. I'm a paying Tailscale customer but I have a fleet of thousands of IoT agents and after discussing with Tailscale support, there just wasn't a pricing plan option that fit for 1 user and thousands of devices.

Anyways you can self host netbird for $5/mo on any cloud provider and it does mostly the same stuff that Tailscale does. Only takes 5 minutes to setup as well.

**Comment by raggi** [comment]
The sharing feature might work for you here: https://tailscale.com/kb/1084/sharing/
