### ISSUE TITLE
FR: Long lasting use-at-our-discretion ephemeral keys

### ISSUE THREAD

**Issue by michealroberts** [tailscale/tailscale#10337]
### What are you trying to do?

One issue we encounter every 90 days, is the refreshing of our ephemeral auth keys across our nodes.

We operate ~6 remote physical astronomical observatories utilising a Tailscale VPN to allow whitelisted communication between devices.

Rotating the ephemeral auth key is current done manually.

### What is the impact of not solving this?

We currently utilise the manual workflow workaround, which is done on a scheduled basis.

### Anything else?

What might be a nice workaround is a courtesy email to say "you're auth key has / is expiring in 12 hours, please refresh".

**Comment by michealroberts** [comment]
@DentonGentry Fair, but in reality, we setup Tailscale inside a Google Cloud Run process.

I'm thinking we could run a cron process that asks for an ephemeral auth key and updates the environment variable for all of our deployments ...

**Comment by DentonGentry** [comment]
`tailscaled` can accept a `tskey-client-*`, the client-secret portion of an OAuth client, and use it to allocate an authkey to use for itself.

https://github.com/tailscale/tailscale/blob/2c1f14d9e6e785eae8f82e88fe2651cd512d9f67/cmd/tailscale/cli/up.go#L1079-L1088

This has some downsides:
- Where an OAuth client would typically be stored in some kind of vault between uses, to pass it to `tailscale up --authkey=...` will usually mean storing it in an environment variable where it is far easier to get access to.
- As such it is especially important to set that OAuth client's scope tightly, ideally only `device:write` and to only the set of Tags used for this deployment.

**Comment by michealroberts** [comment]
Ok, so the OAuth client setup process looks simple but a little complex in places, we need to setup tags and groups by the looks of things. Are there any guides on how to do this?

**Comment by DentonGentry** [comment]
OAuth clients are not owned by any human User on the tailnet, they are owned by the tailnet as a whole. As such, they cannot create authkeys for a human User, only for Tagged nodes which will be owned by the tailnet as a whole:
- [KnowledgeBase article](https://tailscale.com/kb/1068/acl-tags/)
- [ACL tags are generally available ](https://tailscale.com/blog/acl-tags-ga/)

**Comment by michealroberts** [comment]
Thanks @DentonGentry , I'll give into this today.

**Comment by michealroberts** [comment]
@DentonGentry I would be forever grateful if you could provide me with an example of setting the OAuth ID and the Client Key inside of a Dockerfile via environment variables:

Would I be right in saying we can modify the following:

```
/app/tailscale up --authkey=${TAILSCALE_EPHEMERAL_AUTH_KEY} --hostname=${TAILSCALE_HOST_NAME}
```

to something like

```
/app/tailscale up --oauthclientid=${TAILSCALE_OAUTH_CLIENT_ID} --oauthclientsecret=${TAILSCALE_OAUTH_CLIENT_SECRET}
```

**Comment by DentonGentry** [comment]
```
/app/tailscale up --authkey=${TAILSCALE_OAUTH_CLIENT_SECRET} --hostname=${TAILSCALE_HOST_NAME}
```

`tailscaled` examines the key it is passed to figure out if it is an authkey or an API-key which it should use to allocate an authkey.

https://github.com/tailscale/tailscale/blob/2c1f14d9e6e785eae8f82e88fe2651cd512d9f67/cmd/tailscale/cli/up.go#L1079-L1088

**Comment by michealroberts** [comment]
I think there is something missing from our jigsaw as I am seeing this in the output logs:

```
oauth authkeys require --advertise-tags
```

... help! :)

**Comment by DentonGentry** [comment]
`/app/tailscale up --authkey=${TAILSCALE_OAUTH_CLIENT_SECRET} --hostname=${TAILSCALE_HOST_NAME} --advertise-tags=tag1,tag2`

The OAuth client with the devices:write scope asks for tags that it is allowed to create. The Tags passed to `--advertise-tags=...` need to be amongst the tags which the OAuth client is allowed to create.

**Comment by michealroberts** [comment]
I see. I gave my OAuth client just the read scope, will it need write access as well?

**Comment by michealroberts** [comment]
I'm thinking this:

![CleanShot 2023-11-30 at 16 53 26](https://github.com/tailscale/tailscale/assets/84131395/a92e0227-c48c-4f43-9d79-0de4c92dd59c)

**Comment by michealroberts** [comment]
That's seems to have worked. I am now happy that the 180 days is sufficient enough for auth keys, and if a permanent solution for gathering auth keys is needed - the auth client is the way to go.
