### ISSUE TITLE
Mullvad VPN Exit Node Selection List

### ISSUE THREAD

**Issue by esatkucuk** [tailscale/tailscale#10336]
### What is the issue?

On Windows version of Tailscale,

Mullvad VPN Exit Node Selection List coming longer and need to be tabbed like country on mobile list.

### Steps to reproduce

 need to be tabbed like country on mobile list.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.54.0

**Comment by esatkucuk** [comment]
![exit_node_selection_multivad-vpn-mobile png](https://github.com/tailscale/tailscale/assets/32023864/9bb97a30-d6f3-40da-b74d-6a01bd0192bf)
<img width="158" alt="exit_node_selection_multivad-vpn" src="https://github.com/tailscale/tailscale/assets/32023864/4261509f-2558-45df-943e-a2367dd8daf2">

**Comment by catzkorn** [comment]
Hi,

Mullvad is currently in Beta, and improving the selection process on Windows and Android is on our todo list before moving the feature into GA. We will update this issue once we have made updates to the UI.

**Comment by catzkorn** [comment]
I'm going to close this issue, so we can focus tracking under #9421
