### ISSUE TITLE
MacOS BigSur 11.1 M1 Chip: Excessive CPU usage even when Tailscale is in Disconnected Mode

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#1034]
OS: MacOS/11.1
CPU: M1
Device: Mac Mini M1 16GB
TailScale Version: 1.2.4

Problem: 

Tailscale uses ~4% of CPU in Intel Rosetta mode even when it is in disconnected mode.

Expect:

Tailscale should use close to 0% cpu amortized over time.

To put in perspective, Android M1 (alpha) Android Emulator uses ~5% CPU idle

Attached is the screenshot of above situation. 

![tailscal_mac_min_m1](https://user-images.githubusercontent.com/417764/102428271-345b7300-404d-11eb-88ff-68f54c4a5782.png)
.

**Comment by bradfitz** [comment]
I know there was a bug fix in 1.2.10 (not out yet for macOS) that prevents a local LAN packet flood with some routers that should help reduce CPU but that'd only help the IPNExtension. It's unclear from your screenshot whether the highlighted "Tailscale" row includes its IPNExtension process a few lines below in its numbers. Presumably not. But that's odd, since our GUI process does approximately nothing. It basically only sends menu click events to the IPNExtension.

I see you have XCode installed. Did you try to attach Instruments to it and see what it's doing?

**Comment by diegomontoya** [comment]
@bradfitz Xcode in both Native and Rosetta mode cannot attach to the Tailscale process. ```Error 1``` is the attach fail code.

**Comment by diegomontoya** [comment]
Not sure if it's related but if Tailscale is in "Connected" mode, only Tailscale devices can be reached via network. All other network is down. DNS, ping, everything except for Tailscale devices. Everything returns to normal after Tailscale is "Disconnected" mode.

**Comment by diegomontoya** [comment]
Confirmed. When Tailscale is in enabled mode, port 80/443 traffic to the outside world is closed. Most likely routed by MacOS to TailScale? Strange. PING and DNS are not effected. 

I do not have a non M1 MacOS to test if this is only related to M1 Big Sur.

**Comment by bradfitz** [comment]
That's #923. Big Sur changed VPN/DNS APIs on us. Option click the menu and turn off Corp DNS, or enable Magic DNS in the tailscale web admin panel.

**Comment by diegomontoya** [comment]
@bradfitz  Thanks. Enabling MagicDNS fixed http/https access with TS enabled. Though option click on TS application didn't have the Corporate DNS option

**Comment by bradfitz** [comment]
Sorry, option click on the **menu bar icon**, not the application. It was added in 1.2.1, so you should have it. It works for me here:

<img width="348" alt="Screen Shot 2020-12-16 at 9 02 05 PM" src="https://user-images.githubusercontent.com/2621/102446146-f5440800-3fe1-11eb-84d7-08f5d9084f7b.png">

**Comment by zx2c4** [comment]
Not sure if it's related to this issue, but WireGuardKit supports Apple Silicon now:
https://lists.zx2c4.com/pipermail/wireguard/2020-December/006161.html

**Comment by herver** [comment]
Hello there,

Not sure it is relevant to this particular issue, but I've noted a similar behaviour on a Linux node that has **non-tailscale-related** UDP traffic even with `tailscale` in `down` mode:

 * Ubuntu 20.04.1 LTS
 * Kernel `5.4.0-40-generic` (I know :stuck_out_tongue: )

![image](https://user-images.githubusercontent.com/218323/104152617-580da100-53e0-11eb-978e-9d10d6221fa4.png)

Perf shows the following when attached to the `tailscaled` process:

![image](https://user-images.githubusercontent.com/218323/104152718-a91d9500-53e0-11eb-9e55-32ffc0e0d4bf.png)

**Comment by gnormandin** [comment]
I just wanted to say that these cpu usage issues do no exist when running the iOS version of tailscale on an M1-based Mac. So far, things seem to be working as expected with this version.

**Comment by bradfitz** [comment]
The Android & iOS builds more aggressively go idle for battery reasons.

We discussed it today and plan to make all clients the same now: they'll all go idle aggressively like Android & iOS. They hadn't in the past for NAT traversal / latency reasons (the periodic STUNs keeps your NAT mapping fresh), but we've largely fixed all those issues and know how to fix the remaining bits.

So we'll be working on this soon.

**Comment by bradfitz** [comment]
Update on this. Tailscale 1.4 goes idle the same on all platforms now. (macOS/iOS builds still coming out)

**Comment by sppatel** [comment]
@bradfitz any timeline on when the macOS builds will be out?

**Comment by apenwarr** [comment]
This should be in pretty good shape in v1.8.x. There are still more CPU fixes we can do, but indications are that Tailscale uses very little CPU when (actually) idle now.
