### ISSUE TITLE
FR: allow overriding kubeconfig path for `tailscale configure kubeconfig`

### ISSUE THREAD

**Issue by cterence** [tailscale/tailscale#10346]
### What is the issue?

When running `tailscale configure kubeconfig <k8s-operator>`, the `KUBECONFIG` environment variable is completely ignored. The kubeconfig entry is stored in the default kubeconfig path of the current user.

### Steps to reproduce

```shell
touch /tmp/.kubeconfig
export KUBECONFIG="/tmp/.kubeconfig"
tailscale configure kubeconfig <k8s-operator>
kubectl get pod # fails
cat /tmp/.kubeconfig # empty
```

### Are there any recent changes that introduced the issue?

It's been working this way since the introduction of this command as far as I know.

### OS

Linux

### OS version

Ubuntu 22.04, kernel 6.4.9-060409-generic

### Tailscale version

1.52.1

### Other software

None that could interfere

### Bug report

BUG-177dfdd17a59d6c67734dca9aac180fd8d4dcf06b74b8de8d3f6e71b5d32f071-20231121081242Z-1ada49764ece8a75

**Comment by cterence** [comment]
@dixneuf19 FYI

**Comment by irbekrm** [comment]
This was fixed in https://github.com/tailscale/tailscale/pull/11604
