### ISSUE TITLE
FR: Release Amazon FireTV app in Fire TV App Store

### ISSUE THREAD

**Issue by eric** [tailscale/tailscale#10355]
This is a re-post of #1611: It would be nice to have a Tailscale package be on the Amazon store.

It appears the package was made and it was released to the Google Play Store, but I can't seem to find one for the Amazon Fire TV Store.

**Comment by agottardo** [comment]
The app is now available on the Amazon Appstore for Fire TVs and tablets: https://tailscale.com/kb/1394/install-amazon-fire

**Comment by tommes** [comment]
The knowledge base article should mention, that Fire TV Stick 4K is not compatible, as it uses Android 7, whereas the Amazon Appstore version requires at least Android 8.
I got it running on my First Stick 4K using side loading of version 1.62 apk. It would be great to have a download link for  Version 1.62 on the [Android download page](https://tailscale.com/download/android)
