### ISSUE TITLE
android: cannot sign in with Google on the emulator

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1036]
Running tailscale-debug.apk in a Pixel 3a emulator (which has Play store integration). I signed into the emulated phone with my Google account, then started Tailscale and tried signing in with Google. The system UI popped up to pick my account, but after selecting my account that UI disappears and Tailscale stays stuck on the same sign-in dialog.

Sign-in through the browser (select Other, then Google again) works.

Note that I did not adjust the OAuth credentials in the app, so it's using com.tailscale.ipn and whatever credentials are checked in. Developer mode is enabled on the emulated phone, but I didn't see any obvious errors in `adb logcat`. AFAICT, sign-in goes normally but then nothing else happens.

/cc @eliasnaur @bradfitz @DentonGentry

**Comment by bradfitz** [comment]
Previously: #608 (same-ish bug)

Previously @eliasnaur wrote:

> Hi,
>
> I believe the reason Google sign-in doesn't work is that your developer signing key
> is not listed in the OAuth2 credentials page:
>
> https://console.cloud.google.com/apis/credentials?project=tailscale-android
> 
> Note the two Client IDs, "Tailscale Release" (release signing key) and "Tailscale
> Debug (Elias)" (my signing key).

I'd asked:

> Do you create the signing key from the Google web console there and then download it, or do I create the signing key from the Android SDK and then upload it?

@eliasnaur replied:

> I extracted the Google Play signing key fingerprint from the Play console.
> That's the "Tailscale Release" entry.
>
> For the "Tailscale Debug" entry I generated the fingerprint (on Linux) with
>
>        $ keytool -keystore ~/.android/debug.keystore  -list -v
>
> The debug.keystore is automatically created by Android Studio, I believe.

**Comment by danderson** [comment]
Is there any way to discover this condition and throw up an error? It's quite confusing to have the app just pretend nothing happened.
