### ISSUE TITLE
[Windows] Can't start tailscale when windows is not login

### ISSUE THREAD

**Issue by lyj0309** [tailscale/tailscale#10366]
### What is the issue?

When open the computer , but not login, tailscale is not running, and can't connect

### Steps to reproduce

open the computer , but not login, tailscale is not running

### OS

Windows

### OS version

win11

### Tailscale version

1.54

**Comment by evilhamsterman** [comment]
I recommend you review the very extensive docs before posting issues. This is documented here https://tailscale.com/kb/1088/run-unattended/, you have to check the "Run unattended" box under preferences

**Comment by lyj0309** [comment]
got it ,thanks
