### ISSUE TITLE
ipn floods logs with SetEndPointAddress: <addr> owned by <key>, skipping

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1037]
On my personal network, my emulated phone spams the following line at a very high rate, up to hundreds/sec:

```
68 25210 I com.tailscale.ipn: 26.5M/170.4M [5Reb0] - SetEndPointAddress: [fd00:0:c0:116:e4e0::]:12345 owned by [5Reb0], skipping
```

The key is my test default routing node, but the log entry occurs with or without subnet routes enabled.

**Comment by bradfitz** [comment]
That address, if you don't already know, is from:

```go
// initFakeUDPAddr populates fakeWGAddr with a globally unique fake UDPAddr.                                                                                           
// The current implementation just uses the pointer value of de jammed into an IPv6                                                                                    
// address, but it could also be, say, a counter.                                                                                                                      
func (de *discoEndpoint) initFakeUDPAddr() {
        var addr [16]byte
        addr[0] = 0xfd
        addr[1] = 0x00
        binary.BigEndian.PutUint64(addr[2:], uint64(reflect.ValueOf(de).Pointer()))
        de.fakeWGAddr = netaddr.IPPort{
                IP:   netaddr.IPFrom16(addr),
                Port: 12345,
        }
        de.fakeWGAddrStd = de.fakeWGAddr.UDPAddr()
}
```

**Comment by bradfitz** [comment]
Hah, and once you have a default IPv6 route, the LookupIP inside wireguard-go now fires:

```go
func (peer *Peer) SetEndpointAddress(addr *net.UDPAddr) {
        if peer.disableRoaming {
                return
        }   
        if p := peer.device.allowedips.LookupIP(addr.IP); p != nil {
                peer.device.log.Debug.Printf("%v - SetEndPointAddress: %v owned by %v, skipping", peer, addr, p)
                return
        }
```

**Comment by bradfitz** [comment]
Basically we were previously squatting in a IPv6 ULA space for our synthetic wireguard Device IPs, which it (previously?) seemed to require us to invent.

Maybe we can take advantage of that `disableRoaming`? https://github.com/WireGuard/wireguard-go/blame/master/device/mobilequirks.go isn't very elucidating.

**Comment by danderson** [comment]
More context and analysis.

When using active discovery, we handle all the "pick a target ip:port for the peer and transmit to them". We don't tell wireguard-go about any of it, because its roaming support isn't clever enough to do what we need. Instead, we synthesize a fake endpoint address out of IPv6 ULA space, and tell wireguard-go that the peer is there. That fake address acts as a lookup key between us and wireguard-go, so that we always know what peer we're referring to (without needing wireguard-go to involve us in the cryptographic parts of the system).

(aside: if we could add a wireguard-go API that lets us implement a UDP "socket" that references peers by their keys, that would greatly help us. However it's tricky, because depending on the packet we're looking at the identifier to use varies, so it'd have to be keyed by multiple things on each side)

Separately, when we hand a received packet to wireguard-go, once it's verified it and identified the corresponding peer, it unconditionally calls `peer.SetEndpointAddress`, in order to invoke `endpoint.UpdateDst` on the peer endpoint. The endpoint is a thing we own, and it's what wireguard-go tells us to send to.

This whole codepath exists for the v0 magicsock implementation, because in that code we needed a way for wireguard-go to tell us that yes, the packet you just gave me is valid, so now you may consider that source IP trustworthy for future transmissions. We still have that code in magicsock, but it's only to support the dwindling pre-disco clients. Active discovery clients run path discovery independently of wireguard, and so can present it with a single static fake endpoint.

The codepath tries to be a little bit clever when it comes to avoiding routing loops: prior to firing the callback to make us update the endpoint address, it does an AllowedIPs lookup, to see if, in a naive routing setup, sending to that IP would end up looping back into wireguard-go. If so, it logs noisily about it (once per packet, scream), and doesn't call the callback.

This culminates to what happens here: my test network uses only active-discovery clients, so wireguard-go is given one fake IPv6 address per peer, and we handle all the path discovery outside of wireguard-go. But then, I enable default routes (the feature I'm currently working on), which adds `::/0` to AllowedIPs. Now, suddenly, every packet received by wireguard-go hits the half-baked routing loop sanity check, logs noisily (again, once per packet, scream), and doesn't call the UpdateDst callback. The most fun part is that everything still works fine: active discovery endpoints don't use UpdateDst at all, the call is a no-op (aside from all the extra work wireguard-go has to do in order to reach the no-op, scream). So, the only effect is that we spam logs at a rate of 1 message per received packet, ad infinitum, with no rate limiting. And of course, this being a per-packet hit, throughput tanks hilariously.


Okay, so, how do we fix this?

In the long run, I think we should rip out this UpdateDst stuff from upstream wireguard-go. We contributed it, AFAIK we're the only users of that API, and with the benefit of hindsight, it was the wrong way to go about what we needed. As an aside, it will likely improve wireguard-go performance, due to saving an entire AllowedIPs lookup per packet.

In the short run, we can't rip it out without breaking pre-disco tailscale clients, because our legacy magicsock code still relies on that codepath to make the discovery work right.

We could remove the routing loop check from wireguard-go, and move it over into tailscale's code. That check is insufficient to get proper routing loop avoidance anyway, and that part should be handled at the OS interface layer, rather than within the bowels of wireguard-go. Vanilla wireguard-go doesn't have the problem that check is trying to avoid, because it does good routing loop avoidance outside of the hot packet path anyway.

We could take this opportunity to declare pre-disco clients EOL, and remove the code in question from both magicsock and wireguard-go. Some portion of those pre-disco clients will continue to function by virtue of falling back to DERP, so really we're looking at breaking pre-March 2020 clients that haven't upgraded yet. At a rough glance, changelog.ts says it's about 150 nodes.

We could just remove the logging statement and let the rest of the logic flow as it is. That would make things less debuggable in an extreme corner case that only we would ever encounter, but only when dealing with pre-disco clients. And it would remove a "log per packet" from wireguard-go, which I think is untenable no matter what we want to do with the rest of that code.

And... I think that's about it. Oh, we could also clean up upstream wireguard-go now, and keep the extra code in our fork until we're ready to retire pre-disco support. That way the burden shifts to us, rather than forcing wireguard-go upstream to carry code that should be removed.

**Comment by danderson** [comment]
Expanding this bug slightly to get rid of some of the old hooks we added into wireguard-go to support the old nat traversal code. I think I have a code structure that puts all the fanciness in magicsock, so we can revert a bunch of invasive patches (including the one that causes all this spam).

**Comment by DentonGentry** [comment]
We're down to exactly one patch in wireguard-go, which adjusts some constants. This must have been addressed somewhere along the way, there is no longer a hook in wireguard-go.
