### ISSUE TITLE
Problem with ios when creating a new device from clone of old phone

### ISSUE THREAD

**Issue by LostInSpace132** [tailscale/tailscale#10371]
### What is the issue?

I recently upgraded my iphone and cloned the device using normal apple backups. 

At first i noticed a duplicate node key in the admin console. Which makes sense. Per the troubleshooting guide i deleted the app on one of the phones. And reinstalled. Still cant get a new ip address. I tried deleting the app on both devices to no avail. I also tried deleting the device from the admin console and adding both devices back. 

 Now the system is in a state where there is still a duplicate ip address, but no warning of the duplicate node key, but if i log into one device it disconnects the other device. 
 
What is the recommended way of getting two separate ip addresses and node keys. 

Ive been spending hours on this. Its driving me NUTS 

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

Happened when I upgraded and cloned phones

### OS

iOS

### OS version

Ios 16.1 on one device ans ios 17.1 on the other phone

### Tailscale version

Ive tried the latest ios release on the app store as well as the testflight beta

**Comment by LostInSpace132** [comment]
BUG-c67e4cb4a7f1a5b8939a5af523ae3c514b7a82f17c6d16fea1604b265ed31306-20231123222925Z-470145bf9b56f6d3

**Comment by DentonGentry** [comment]
On the new device, go to the iOS Settings app > Tailscale, and turn "Reset Keychain" on. The next time you start the Tailscale app it will prompt to login again, and will get a new node key.

**Comment by LostInSpace132** [comment]
Fantastic. That did it. Perhaps an ios specific app note in the troubleshooting guide for duplicate node keys would help others in the future. Very grateful on thanksgiving!On Nov 23, 2023, at 4:31 PM, Denton Gentry ***@***.***> wrote:﻿
On the new device, go to the iOS Settings app > Tailscale, and turn "Reset Keychain" on. The next time you start the Tailscale app it will prompt to login again, and will get a new node key.
