### ISSUE TITLE
Consistently high CPU usage on Linux, DNS request queue full

### ISSUE THREAD

**Issue by vduseev** [tailscale/tailscale#10387]
### What is the issue?

Installed tailscale on several debian VMs around Oct 11, 2023. Around a month ago all VMs started exhibiting higher than usual CPU usage with Tailscale being firmly at the top of the total consumed CPU time.

#### When issues started

Running `journalctl -u tailscaled` I can see that up until Oct 23 12:02:51 the logs look pretty normal:

```syslog
Oct 23 12:02:02 lingo-p tailscaled[18533]: Accept: UDP{100.xx.xx.xx:60001 > 100.yy.yy.yy:60976} 112 ok out
Oct 23 12:02:11 lingo-p tailscaled[18533]: Accept: UDP{100.xx.xx.xx:60001 > 100.yy.yy.yy:60976} 108 ok out
```

Then it's just the following non-stop

```syslog
Oct 23 12:11:04 lingo-p tailscaled[18533]: dns udp query: request queue full
Oct 23 12:11:04 lingo-p tailscaled[18533]: dns udp query: request queue full
Oct 23 12:14:42 lingo-p tailscaled[18533]: dns udp query: request queue full
...
Nov 25 13:45:25 lingo-p tailscaled[18533]: dns udp read: read udp 100.100.100.100:53: connection was refused
```

Bug report for the machine from which the logs above were pulled: `BUG-3c8de3999fca25471068c096d5c09f389e30d6707b7c4ed773f442cade76d6f6-20231126221736Z-58e1ffce57e000d1`

#### Very High CPU consumption on beefier machine

Another more beefier machine looks even worse. Logs are full of the following:

```syslog
Nov 08 02:29:39 lingo-s tailscaled[821]: dns udp query: request queue full
Nov 08 02:29:39 lingo-s tailscaled[821]: dns udp query: request queue full
Nov 08 02:29:39 lingo-s tailscaled[821]: dns udp query: request queue full
Nov 08 02:29:39 lingo-s tailscaled[821]: [RATELIMIT] format("dns udp query: %v")
Nov 08 02:29:49 lingo-s tailscaled[821]: dns udp query: request queue full
Nov 08 02:29:49 lingo-s tailscaled[821]: dns udp query: request queue full
Nov 08 02:29:49 lingo-s tailscaled[821]: [RATELIMIT] format("dns udp query: %v")
Nov 08 02:29:56 lingo-s tailscaled[821]: dns udp read: read udp 100.100.100.100:53: connection was refused
Nov 08 02:30:00 lingo-s tailscaled[821]: [RATELIMIT] format("dns udp query: %v") (2 dropped)
```

The machine has 16 vCPUs and 32GM RAM. Every few seconds I see spikes of up to 1000% CPU on tailscale process.

Here is what `htop` looked like:

![htop-before-upgrade](https://i.ibb.co/353YhJY/s.png)

I've tried to upgrade and restart tailscale and executed the following

```bash
sudo apt-get update
sudo apt-get upgrade
tailscale down
tailscale up
```

![htop-after-upgrade](https://i.ibb.co/WxqNk1d/s-restart.png)

Nothing really changed. 

I've also tried restarting dbus through `systemctl restart dbus` but that had no effect.

The CPU and Network graphs on Monitoring system went from being smooth to spiky around Oct 26:

![spikes](https://i.ibb.co/cwcMLd8/s-monitoring.png)

The spikes always happen either around 4am or 7am CET.

#### Empty system

Now, here is what happens on an empty VM. As you can see, almost nothing is running on that system except docker and tailscale. No docker containers are running.

*The screenshot below shows all the processes running on VM. As mentioned, it is, basically, empty.*

![empty-system-htop](https://i.ibb.co/SNVTFjJ/empty-system.png)

Bug report ID for the empty system: `BUG-99eee70f3085800206b880890a5880d858f6606dce11403b2b6bf3a848171db4-20231126225026Z-44c603210be10c14`

The version of Tailscale installed on all machines during the initial setup is

```
1.50.1
  tailscale commit: f45c02bfcf5ee5790c3af278c9e974c9b9b0e771
  other commit: 36a20760a45bd1936686879b34c35146cc0c4ec1
  go version: go1.21.1
```

### Steps to reproduce

1. Installed tailscale 1.50.1 on Debian 12
2. Left it running for more than a month
3. At some point CPU usage grew and stayed consistently high
4. Upgrade to version 1.54 today did not help

### Are there any recent changes that introduced the issue?

No changes

### OS

Linux

### OS version

Debian 12

### Tailscale version

1.54.0

### Other software

On each of the affected machines there are different combinations of software, but what all machines share in common is:

* Docker
* OpenSSH

### Bug report

BUG-467788eac7237043d83fd827385ade278414a09522cba22b3f7f829e234d5145-20231126220455Z-a1a46cb5df6e9dec

**Comment by knyar** [comment]
Based on the bugreport it seems like you are not using `systemd-resolved`, so Tailscale client has to rewrite `/etc/resolv.conf` and forward all DNS requests originating from the machine (see [this blog post](https://tailscale.com/blog/sisyphean-dns-client-linux/) for some background on why we need to do that).

High CPU usage and `request queue full` messages might indicate a high volume of DNS traffic.

I'd suggest to:
* Check the volume of DNS requests originating from the machine. Since you have `100.100.100.100` as the system-wide resolver, a good starting point might be to examine DNS requests being sent to it, e.g. `tcpdump -ni tailscale0 dst 100.100.100.100 and port 53`
* Consider switching to `systemd-resolved` to allow Tailscale to manage DNS configuration on the system more granularly instead of overriding `/etc/resolv.conf`

**Comment by vduseev** [comment]
Thank you @knyar for the valuable recommendations! I will test them out during the weekend.

**Comment by vduseev** [comment]
Switching to `systemd-resoved` worked wonderfully (thank you @knyar!) 🥳 

For those who have the same problem, being on Debian 12 based system, here is what I did:

* Disabled Tailscale's MagicDNS on host system according to [official documentation about resolve.conf](https://tailscale.com/kb/1235/resolv-conf/) by executing `tailscale set --accept-dns=false`
* On each VM that had Tailscale installed, I did the following:
  * Updated tailscale to the latest version
  
    ```shell
    apt update
    apt install tailscale
    ```

  * Installed `systemd-resolved`

    ```shell
    apt install systemd-resolved
    ```

  * Configured default `DNS=` and `FallbackDNS=` for `systemd-resolved`

    ```shell
    # Inside /etc/systemd/resolved.conf    
    [Resolve]
    # Some examples of DNS servers which may be used for DNS= and FallbackDNS=:
    # Cloudflare: 1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
    # Google:     8.8.8.8#dns.google 8.8.4.4#dns.google 2001:4860:4860::8888#dns.google 2001:4860:4860::8844#dns.google
    # Quad9:      9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net 2620:fe::fe#dns.quad9.net 2620:fe::9#dns.quad9.net
    DNS=1.1.1.1 8.8.8.8 9.9.9.9
    FallbackDNS=1.0.0.1 8.8.4.4
    ```

  * Restarted `systemd-resolved`

    ```shell
    systemctl daemon-reload
    systemctl restart systemd-resolved
    ```
