### ISSUE TITLE
FR: Show current network status in tvOS interface

### ISSUE THREAD

**Issue by timtailscale** [tailscale/tailscale#10391]
### What are you trying to do?

View the output of `tailscale status` from an Apple TV device. 

### How should we solve this?

Add an Advanced page or similar to show more in depth tailnet info.

### Anything else?

[go/hs/23359](http://go/hs/23359)

**Comment by agottardo** [comment]
More generally, we should display direct/DERP info in the app UI, on iOS, macOS and tvOS.

**Comment by agottardo** [comment]
Landed in beta.
