### ISSUE TITLE
When stop and exit macos tailscale client, the vpn & filter remains active

### ISSUE THREAD

**Issue by goldfix** [tailscale/tailscale#10406]
### What is the issue?

Hello,

when I try to disable the client vpn and close (exit) the client, the vpn remains active on "VPN & Filter". 

Is this correct?

Thanks
p

### Steps to reproduce

- Active the VPN client
- Switch off the VPN
- Close the VPN client
- Check if the VPN is disabled: System Setting --> Network --> VPN (remians active)

![image](https://github.com/tailscale/tailscale/assets/7403160/7f27bbee-b6fa-4477-b6a7-aa6f4dbd02e1)

### OS

macOS

### OS version

14

### Tailscale version

1.54

**Comment by agottardo** [comment]
Duplicate of #1734

This should be fixed in the [latest unstable release](https://pkgs.tailscale.com/unstable/#macos). Please let me know if the issue persists.
