### ISSUE TITLE
Windows : Logout should have confirmation dialogue.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1040]
**Problem:**

On a Windows machine, it’s easy to log out by accidentally clicking the system tray menu item labelled "Log out (user@gmail.com)."

**UseCase:**

I clicked the "Log out" and the network I was on; it was not safe to log in with Google again.
or 
Getting logged out while data transfer was taking place or working remotely.

**Suggestion**:

Nice to have a confirmation dialogue for logout.

**Comment by rosszurowski** [comment]
We've been discussing this internally, and don't feel like a dialog is the right UI to solve this problem. Instead, we're going to tuck the Log in / Log out… buttons in a less prominent place so they're more difficult to accidentally click.

The proposed new design looks like this. We'll look to emulate the same approach on macOS too.

<img width="1695" alt="windows-menu" src="https://user-images.githubusercontent.com/303731/106656731-15fff700-6569-11eb-8616-d4891999038c.png">

**Comment by DentonGentry** [comment]
Will track this on https://github.com/tailscale/winmin/pull/14 and https://github.com/tailscale/corp/issues/1268
