### ISSUE TITLE
Connectivity issues to one end of the connection

### ISSUE THREAD

**Issue by johnae** [tailscale/tailscale#1043]
**Describe the bug**
I'm having trouble connecting to a machine and the subnets behind it. It works for a while and then I can no longer ping the tailscale ip of the machine, however, if I ssh into that machine (via an alternate route) and ping my laptop - traffic starts flowing between my laptop and the other machine. In fact, even if I ping some other machine on the tailscale network from the problematic one, traffic starts flowing between my machine and the problematic one.

**To Reproduce**
I assume it may have to do with the network the problematic machine is on but the setup is just running tailscale really.

**Expected behavior**
I would expect traffic to flow between machines on the tailscale network, not just initially but continuously as long as there is internet connectivity.

**Screenshots**
See attached video.

**Version information:**
 - Device: laptop and intel nuc
 - OS: NixOS
 - OS version: NixOS Unstable e9158eca70ae59e73fae23be5d13d3fa0cfc78b4
 - Tailscale version: 1.2.8

**Additional context**
The IP of the problematic machine is 100.66.214.66
The IP of my laptop is 100.73.142.22

This happens frequently, after some time where some time is... I would guess 30 mins or so, maybe an hour.

I know you're also interested in dates with timezone when the issue has manifested. The attached video has the dates in it but in short, in the video this issue manifests between `Sat Dec 19 08:42:54 PM CET 2020` and `Sat Dec 19 08:43:10 PM CET 2020`. It is thereafter "resolved" by pinging my laptop from the problematic host.

https://user-images.githubusercontent.com/28332/102698540-5e27bc00-423e-11eb-9d68-a6b4c078eba7.mp4

**Comment by johnae** [comment]
In addition to "pinging any other system on the tailscale network from the problematic node makes it pingable again from any other" - apparently restarting the tailscale daemon also "fixes" the connectivity issue.

**Comment by DentonGentry** [comment]
This roughly looks like an issue fixed in the 1.4.x timeframe, which mostly affected Windows systems but might have been more widespread. An outbound ping from the machine, or restarting tailscale, allowed it to recover.

If there are no further updates we'll close this on the next bug scrub.

**Comment by DentonGentry** [comment]
This was almost certainly an issue fixed in the 1.4.5 release a few months ago, closing.
