### ISSUE TITLE
Automatic Updates not working correctly on MacOS

### ISSUE THREAD

**Issue by michealroberts** [tailscale/tailscale#10437]
### What is the issue?

Since upgrading to version 1.54.0 of Tailscale, installing / upgrading from the MacOS Store, auto-magic updates are not correctly being applied ... I am still on version 1.54.0 rather than the latest 1.54.1 release.

![CleanShot 2023-12-01 at 15 00 15](https://github.com/tailscale/tailscale/assets/84131395/068c4ef6-57b1-422c-9e73-4bdf8d7217ee)

### OS

macOS

### OS version

macOS Monterey v12.6.8

### Tailscale version

1.54.0

### Bug report

BUG-6be653b377328fb71af04d91023423c4b0802437a853bc0d5bb61ce8a61e83aa-20231201145912Z-acc7e2182e758a3e

**Comment by DentonGentry** [comment]
The Apple App Store handles rollouts in stages. 1.54.1 began deployment yesterday, and is currently being offered to 1% of devices. Tomorrow it will be offered to 2%, and so on until December 7 when it should be offered to everyone.

If you go directly to the AppStore from the Mac it should show an update as available even if it is not yet being pushed to your device.

**Comment by michealroberts** [comment]
Ok, but that sounds like our devices will be out of sync across our VPN for about a week between releases, and therefore, if you have a release cadence of one per week, we will probably always be out of sync?

**Comment by agottardo** [comment]
A suggestion: you can use tools like https://github.com/mas-cli/mas to automate Mac App Store tasks via scripting. You can employ that if you want to force more frequent updates using a scheduled task.

Alternatively, if you want to manually manage updates, you can use the Standalone variant of Tailscale instead of relying on the App Store. That will give you full control of updates via the Sparkle framework. The Standalone variant comes with its own auto-updating mechanism, which you can trigger at any time via `tailscale update`.

**Comment by michealroberts** [comment]
@DentonGentry It is now over a month since opening this ticket, and I am still on version 1.54.0 of Tailscale on my Mac.

<img width="337" alt="CleanShot 2024-01-22 at 16 14 33@2x" src="https://github.com/tailscale/tailscale/assets/84131395/3f6da092-f6df-4d30-ab8b-ae313be8df63">

I have gone to the app store, and no updates are available.

**Comment by michealroberts** [comment]
Still waiting for the rollout ... :tumbleweed:

**Comment by michealroberts** [comment]
I'm just seeing this:

<img width="610" alt="CleanShot 2024-01-25 at 16 46 53@2x" src="https://github.com/tailscale/tailscale/assets/84131395/09488b56-8afd-49a2-b89c-dc26d218499a">

**Comment by DentonGentry** [comment]
Unfortunately Tailscale has no visibility into the App Store's handling of each individual user. I don't think we will be able to determine why it isn't offering a version more recent than 1.54.0. Were the Mac running High Sierra or Mojave, it would have stopped at 1.44.

The two suggestions I could make would be:
- uninstall and reinstall the app store app
- switch to the [Standalone downloadable app](https://tailscale.com/kb/1065/macos-variants)

**Comment by michealroberts** [comment]
@DentonGentry Update:

I have uninstalled and reinstalled the app store app, and the update is still not working.

**Comment by michealroberts** [comment]
It's saying an update is available, is there anything else I need to enable here on the Mac store side?

**Comment by gyoza** [comment]
It appears that the 'updates' page does not show tailscale but if you search for 'tailscale' then open up the individual store page after searching for it will show an 'update' button.

**Comment by agottardo** [comment]
Closing as this is un-actionable on our end. If you want control over updates, please use the [Standalone variant](https://tailscale.com/kb/1065/macos-variants).
