### ISSUE TITLE
iOS: using an exit node breaks hotspot tethering

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#10455]
### What is the issue?

When connected to an exit node on an iOS device, the device's hotspot functionality will not work. Any device tethered to the hotspot will have no internet connectivity. Disconnecting from Tailscale resolves the issue.

Unstable version 1.53.115 reportedly is not impacted.

This has been reported internally and in a HS ticket: 24966

### Steps to reproduce

On iOS device:
* connect to Tailscale & select exit node
* enable hotspot in iOS settings

On other device:
* tether to iOS hotspot
* attempt to reach a website (e.g., tailscale.com)

expected: website loads (internet connectivity in general works)
actual: website does not load (no internet connectivity)

### OS

iOS

### OS version

17.1.1

### Tailscale version

1.54.0

**Comment by Touchstone64** [comment]
I have the same issue but in a 'simpler' configuration. There are no Exit nodes configured and the MacBook has no LAN or Wi-Fi connection, the only connection available is the iPhone (via 5G).

The MacBook and iPhone (both on Tailscale 1.56.0, using iOS 17.2 and macOS 13.6.2) are both connected to the tailnet. MagicDNS is enabled everywhere. Use Tailscale subnets is disabled on the Mac (for troubleshooting purposes), and Tailscale DNS Settings is enabled.

Whether the MacBook is connected to the iPhone's Wi-Fi personal hotspot, or using its USB Network device, no DNS lookups work in the browser. At the command prompt:
```
[graham@mbp6 ~]
$ dig bbc.co.uk

; <<>> DiG 9.10.6 <<>> bbc.co.uk
;; global options: +cmd
;; connection timed out; no servers could be reached
```

When Tailscale DNS Settings is disabled, browsing works as expected and at the command prompt:
```
graham@mbp6 ~]
$ dig bbc.co.uk

; <<>> DiG 9.10.6 <<>> bbc.co.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37048
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;bbc.co.uk.			IN	A

;; ANSWER SECTION:
bbc.co.uk.		52	IN	A	151.101.192.81
bbc.co.uk.		52	IN	A	151.101.0.81
bbc.co.uk.		52	IN	A	151.101.64.81
bbc.co.uk.		52	IN	A	151.101.128.81

;; Query time: 51 msec
;; SERVER: fe80::c4c1:7dff:fec6:c164%24#53(fe80::c4c1:7dff:fec6:c164%24)
;; WHEN: Fri Dec 15 15:38:59 GMT 2023
;; MSG SIZE  rcvd: 102
```

The change in behaviour is instant when toggling Tailscale DNS Settings on and off.

Both MacBook and iPhone have been reset, turned on and off, and Tailscale uninstalled and re-installed a couple of times.

**Comment by adipierro** [comment]
I can confirm this happens to me too

**Comment by Touchstone64** [comment]
This morning, now running Tailscale 1.56.1, I can no longer resolve my own tailnet. Screenshot (with `dig <tailnet>` output) attached.

The only unusual thing I can think of is that this computer has both wired and wireless connections to my LAN.

Any advice would be welcome, thank you :)

![Screenshot 2023-12-17 at 09 57 53](https://github.com/tailscale/tailscale/assets/57038415/b42a35ee-c852-4785-9058-941573fef0ff)

**Comment by kharitonovAL** [comment]
I noticed that if I have my iPhone connected to the Tailscale, I can share the cellular data (internet) with my MacBook via hotspot. But if I'll turn on the Tailscale on my MacBook, the connection will be broken on it. on iPhone everything will be ok.

**Comment by syeduali93** [comment]
It's really disappointing that a terrific app like tailscale which had this feature working flawlessly has released an update that has broken this feature completely. I am no longer able to tether to an iPhone that has tailscale running via exit node. Please let me know if this will be fixed anytime soon.

**Comment by jimmybrancaccio** [comment]
I've attempted to replicate this today on an iPhone w/ iOS 17.5.1 connected to my Tailnet and an exit node and my MacBook Pro w/ macOS 14.5.1 tethered to my iPhone hot spot and Internet connectivity, DNS lookups and websites were working. I also tried connecting my MacBook to my tailnet too and everything continued to work. This issue may be resolved now.

**Comment by stefins** [comment]
I'm facing this issue on iOS `17.6.1` . My hotspot won't have internet access until I disconnect from tailscale and toggle the Personal hotspot off and on back again.

**Comment by tarikaltuncu** [comment]
Having this issue on iOS 18.1 with tailscale v1.76.1.

**Comment by lilynet336** [comment]
This issue still exists and it's quite frustrating having to use a different VPN every time I need my hotspot. The issue is closed but it is not solved at all.

**Comment by Fainbrog** [comment]
Got the same issue...

**Comment by lilynet336** [comment]
@agottardo I'm sorry for the mention on this issue but I fear as it's been closed it isn't being checked anymore. The issue is definitely not fixed (or has since reappeared), and is annoying me and the other users who've talked in here since. It would be great if the Tailscale team could take a look into this :)

**Comment by tarikaltuncu** [comment]
Agreed it's always a headache to tether my Mac via iPhone while Android is flawless

**Comment by dafacto** [comment]
Just adding that I'm experiencing this as well. Very frustrating. I have Tailscale configured to always use an exit node, but I have to disable that if I want anything to connect via hotspot.

**Comment by viktor-svirsky** [comment]
+1. The problem exists , Macos Tahoe, IOS 26.2, tailscale 1.92.3

**Comment by marcandrechenier** [comment]
Still not fixed when doing an Hotspot with Tailscale enabled with an exit node.  
Tailscale 1.94.1 on iOS

**Comment by mijowi** [comment]
+1 still an issue
Tailscale 1.94.1 on iOS 18.7.2 and Tailscale 1.94.1 on Arch Linux

**Comment by yhager** [comment]
Definitely still an issue. Happening to me with iOS 18.7.2, tailscale 1.94.2 and a mullvad exit node.

Why was it closed? Can it be reopened?

**Comment by torgeir** [comment]
I second this. I am also still having this issue, it is not resolved.

**Comment by Perchycs** [comment]
Also have this issue

**Comment by n104ap** [comment]
seconding this, iOS 26.5, except turning off tailscale or the exit node doesnt fix it, i need to reboot my iphone to fix it
