### ISSUE TITLE
Running the tailscale connect service example panics with "no safe place found to store log state"

### ISSUE THREAD

**Issue by kurrik** [tailscale/tailscale#10454]
### What is the issue?

I'm trying to run the [cmd/tsconnect](https://github.com/tailscale/tailscale/tree/main/cmd/tsconnect) example to see how tailscale works in a wasm environment.  

However, an unmodified checkout of the tailscale repo causes a panic with "no safe place found to store log state" and the sample is inoperable.

### Steps to reproduce

```
git clone https://github.com/tailscale/tailscale.git
cd tailscale/
go install tailscale.com/cmd/tailscale{,d}
./tool/go run ./cmd/tsconnect build
./tool/go run ./cmd/tsconnect serve
```
Navigate to localhost:9090, which displays an error and the following in the browser's dev console: `panic: no safe place found to store log state`

<img width="758" alt="Screenshot 2023-12-04 at 8 15 32 AM" src="https://github.com/tailscale/tailscale/assets/166424/e8f9db43-2cc0-4325-8ce4-7c0dbca0d409">

### Are there any recent changes that introduced the issue?

Nothing recent seems to have changed in the past 8 months here, but

calling `NewLocalBackend` calls
```
b.sockstatLogger, err = sockstatlog.NewLogger(logpolicy.LogsDir(logf), logf, logID, netMon)
```
in https://github.com/tailscale/tailscale/blob/main/ipn/ipnlocal/local.go#L386

It seems that the particular environment config used for wasm builds (and lack of os.Stat) implies `logpolicy.LogsDir` call doesn't have a successful path in https://github.com/tailscale/tailscale/blob/v1.54.1/logpolicy/logpolicy.go#L202

I'm not sure what the prior behavior was when this sample was working, but `sockstatlog.NewLogger` would return a nil logger in my environment (AFAICT) if `LogsDir` didn't panic.

### OS

macOS

### OS version

macOS Sonoma 14.1.1

### Tailscale version

n/a

### Other software

Arc browser & Chrome browser (both exhibit the same error)

**Comment by anasfanani** [comment]
https://github.com/anasfanani/Magisk-Tailscaled/issues/1#issuecomment-1860837922

**Comment by szc188** [comment]
I ran into this issue too, but I tried his program and it seems to work fine: [https://github.com/hatf0/tailscale](https://github.com/hatf0/tailscale)

**Comment by nom3ad** [comment]
I was able to work around this by patching wasm_exec.js
```bash
sed -i 's|mkdir(path, perm, callback).*|mkdir(path, perm, callback) { callback(path.startsWith("/tmp/tailscaled-log") ? null : enosys()) },|g' wasm_exec.js
```
