### ISSUE TITLE
Tailscale fails to start on RISC-V 64 machine

### ISSUE THREAD

**Issue by plsnotracking** [tailscale/tailscale#10498]
### What is the issue?

RISC-V 64 aka StarFive 2 machine cannot start Tailscale successfully

### Steps to reproduce

- Download the binary from [here](https://pkgs.tailscale.com/stable/tailscale_1.54.1_riscv64.tgz)
- `tar xvf [path/to/tgz]`
- `mv tailscale_1.54.1_riscv64/tailscaled /usr/bin/tailscaled`
- `sudo tailscaled --state=tailscaled.state`

Stacktrace
```bash
$ sudo tailscaled --state=tailscaled.state
logtail started
Program starting: v1.54.1-t0a01efc8f-g3d0598425, Go 1.21.4: []string{"tailscaled", "--state=tailscaled.state"}
LogID: 840df67af56ee18c54fb0de26894e92a47f6eb0015cec5eb483d69e03c3b61e2
logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 5.15.0-starfive
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: FATAL: Module tun not found in directory /lib/modules/5.15.0-starfive
tun module not loaded nor found on disk
wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
getLocalBackend error: createEngine: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
```

### Are there any recent changes that introduced the issue?

No.

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.54.1

### Bug report

840df67af56ee18c54fb0de26894e92a47f6eb0015cec5eb483d69e03c3b61e2

**Comment by DentonGentry** [comment]
> `/dev/net/tun does not exist`

Does `/dev/net/tun` exist?

If not you can use userspace-networking to get started: https://tailscale.com/kb/1112/userspace-networking/
userspace-networking tends to be somewhat less pleasant, since it requires SOCKS5 to make outgoing connections.
You should figure out how to load the tun module and create `/dev/net/tun`

**Comment by bradfitz** [comment]
As of 4 days ago, I see their default kernel includes TUN built-in (CONFIG_TUN=y): https://github.com/starfive-tech/linux/blame/visionfive/arch/riscv/configs/visionfive_defconfig

The 5.15 you're running looks to be 3 years old (https://github.com/starfive-tech/linux/releases). Perhaps they distribute updates elsewhere lately?

But I have Tailscale running on a RISC-V machine (HiFive Unleashed) and it works fine.

**Comment by plsnotracking** [comment]
User needs to update to the latest version of OS/Firmware.

**Comment by jeremiah** [comment]
Just a quick note - this issue is reappearing in the Starfive 6.6.20 kernel as they have commented out CONFIG_TUN for some reason. I will see if I can re-configure it locally.
