### ISSUE TITLE
Left-click to open Tailscale menu in Windows breaks one-click re-authentication

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#10500]
### What is the issue?

Our recent 1.54.0 update to the Windows client menu behavior no longer allows you to open the webpage to re-authenticate in a single click. 

The steps required now are to either:
* click the actual Windows notification when it pops up
or 
* click to open the Tailscale menu
* highlight your account
* select Log out (which prompts another notification)
* click to open the Tailscale menu again
* select Log in, which is now visible

I have two recordings of this behavior shared internally - they can be found at `go/gsupportdrive`

### Steps to reproduce

* Force expiration of a Windows client `tailscale debug set-expire --in 10s`
* After client expires, left-click menu

Expected (prior to 1.54.0) - webpage opens to re-auth
Actual - menu opens and additional steps are required to open the webpage for re-auth

### Are there any recent changes that introduced the issue?

Yes, the implementation of left-click to open the Tailscale menu on Windows, added in 1.54.0. I've searched but was unable to find the exact commit. Prior to this version, left-clicking would open the webpage for re-auth.

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.54.x

**Comment by dblohm7** [comment]
The [human interface guidelines](https://learn.microsoft.com/en-us/windows/win32/uxguide/winenv-notification) suggest that left click should "Display whatever users most likely want to see," so I agree that we can put some of this back in.
