### ISSUE TITLE
curl -fsSL https://tailscale.com/install.sh >> HTTP/2 404 

### ISSUE THREAD

**Issue by stepheneb** [tailscale/tailscale#10512]
### What is the issue?

Running command to install on linux generates an `HTTP/2 404 ` error

### Steps to reproduce

```
curl -fsSL https://tailscale.com/install.sh | sh
curl: (22) The requested URL returned error: 404
```
A simpler test:

```
% curl -I https://tailscale.com/install.sh
HTTP/2 404 
cache-control: public, max-age=0, must-revalidate
content-security-policy: frame-ancestors 'self'
content-type: text/html; charset=utf-8
date: Fri, 08 Dec 2023 15:43:37 GMT
server: Vercel
strict-transport-security: max-age=63072000
x-content-type-options: nosniff
x-frame-options: DENY
x-vercel-id: iad1::7sb7w-1702050217615-299cbad52313
```

### OS

Linux

### OS version

Raspberry Pi Debian Bullseye

**Comment by matti** [comment]
same

**Comment by knyar** [comment]
Thank you for letting us know! We had an event on Friday that resulted in some requests for the installer script returning a 404 at 15:19-15:57 UTC. It has been fixed, and we are working on internal analysis of the event to make sure it does not happen in the future. I am sorry for the inconvenience this has caused, and thanks again for taking the time to report this.

**Comment by Philchek** [comment]
I also came across such a mistake.
curl -fsSL https://tailscale.com/install.sh | sh
curl: (22) The requested URL returned error: 404

**Comment by Philchek** [comment]
curl -fsSL https://tailscale.com/install.sh | sh
The installer cannot reach https://pkgs.tailscale.com/
Please make sure that your machine has internet access.
Test output:
curl: (22) The requested URL returned error: 451

There is Internet access. Other applications work over the Internet.

**Comment by mariano-daniel** [comment]
Also having this issue right now, anyone know the reason and/or how to fix it?

**Comment by Obbaron** [comment]
I have this problem too. Device is online, obviously as I got the command from the browser, yet curl returns a 404.

**Comment by ThinkCode** [comment]
curl -fsSL https://tailscale.com/install.sh | sh

curl: (22) The requested URL returned error: 504
