### ISSUE TITLE
windows: Tailscale uninstall doesn't remove "Tailscale Tunnel" network adapter

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1055]
It seems that uninstalling Tailscale doesn't remove the "Tailscale Tunnel" network adapter, at least on Windows 7.

/cc @alexbrainman

**Comment by bradfitz** [comment]
I tried adding this to our installer:

```go
        tsPool, err := wintun.MakePool("Tailscale")
        if err != nil {
                log.Printf("MakePool: %v", err)
        } else {
                const forceCloseSessions = false
                reboot, errs := tsPool.DeleteMatchingAdapters(func(a *wintun.Adapter) bool {
                        name, _ := a.Name()
                        if name == "" {
                                return false
                        }
                        match := strings.Contains(name, "Tailscale")
                        log.Printf("DeleteMatchingAdapters(%q) = %d", name, match)
                        return match
                }, forceCloseSessions)
                log.Printf("DeleteMatchingAdapters = %v, %v", reboot, errs)
        }
```

But it fails with:

```
[Wintun] NamespaceRuntimeInit: Failed to create private namespace: Access is denied. (Code 0x00000005)
[Wintun] WintunEnumAdapters: Failed to take pool mutex
DeleteMatchingAdapters = false, [Access is denied.]
```

Our NSIS uninstaller runs as Admin and at that point already successfully stopped & removed the service.

@zx2c4, am I holding the wintun API wrong?

**Comment by zx2c4** [comment]
The Wintun documentation identifies a different function for use in uninstallers:

https://git.zx2c4.com/wintun/about/#wintundeletepooldriver

That's available in the Go via:

```go
tsPool, _ := wintun.MakePool("Tailscale")
tsPool.DeleteDriver()
```

Alternatively, you can invoke wintun.dll directly via rundll32. Or, easier, just LoadLibrary it from NSIS and call the function directly.

The reason the invocation above fails is because WintunEnumAdapters fails to call ElevateToSystem(), which usually isn't a problem, but I guess it is here. DeletePoolDriver does elevate, though: https://git.zx2c4.com/wintun/tree/api/adapter.c#n1775

**Comment by bradfitz** [comment]
Wouldn't deleting the driver break a wireguard-windows installation running on the same machine? I was trying to be a friendly neighbor.

**Comment by bradfitz** [comment]
Ah, RTFM. "and if there are no more adapters in any other pools ..."

Okay, thanks!

**Comment by zx2c4** [comment]
As the documentation writes:

> Deletes all Wintun adapters in a pool and if there are no more adapters in any other pools, also removes Wintun from the driver store, usually called by uninstallers.

So if other apps are using it, it won't delete Wintun from the driver store.

**Comment by zx2c4** [comment]
Voila!

**Comment by bradfitz** [comment]
Done. Works great, thanks!
