### ISSUE TITLE
Support managing ssh keys centrally by admin

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1057]
SSH key management should be centralized with Tailscale admin.

SSH keys should be manageable by the admin.

**Comment by bradfitz** [comment]
What's the background here?

If we get into the SSH business at all, I'd imagine it'd be more cmd/tsshd-based?

/cc @apenwarr

**Comment by DentonGentry** [comment]
I think this isn't a feature request we're likely to pursue. We're much more likely to produce SDKs to allow applications to utilize Tailscale's authentication to prove identity of the user.
