### ISSUE TITLE
FR: create a helm repository for the k8s operator 

### ISSUE THREAD

**Issue by aviau** [tailscale/tailscale#10599]
### What are you trying to do?

I would like to be able to install the tailscale k8s operator helm chart form a helm repository.

Ideally one that is compatible with `helm install` and the [terraform resource](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release).

### How should we solve this?

There are ways of using a github repository as a helm repository, that could be an option.

Otherwise, AFAIK hosting tarballs on an http server works.

**Comment by aviau** [comment]
In order to work around this issue, some members of the community began posting the helm chart on third-party repositories:
- https://artifacthub.io/packages/helm/jacobcolvin/tailscale-operator

This exposes users to security risks.

**Comment by irbekrm** [comment]
Hi @aviau thank you for opening the issue.

We have now published a chart and the latest 1.56 Tailscale release has been added, see our updated installation docs https://tailscale.com/kb/1236/kubernetes-operator?q=operator#installation

**Comment by aviau** [comment]
I could install the helm chart successfully using Terraform.

```terraform
resource "helm_release" "tailscale_operator" {
  repository       = "https://pkgs.tailscale.com/helmcharts"
  name             = "tailscale"
  chart            = "tailscale-operator"
  namespace        = "tailscale-operator"
  version          = "1.56.0"
  atomic           = true
  cleanup_on_fail  = true
  create_namespace = true
  values           = [local.helm_release_tailscale_values]
}
```

Thank you!

**Comment by irbekrm** [comment]
Thanks for confirming!
