### ISSUE TITLE
macOS: Alternate coordination server broken

### ISSUE THREAD

**Issue by mschoeffmann** [tailscale/tailscale#10593]
### What is the issue?

Since 1.56.0, the use of an alternate coordination server is broken:

1. Trying to Add/Login via Debug menu does not use the custom URL but redirects to tailscale.com for login instead

2. Using CLI `Tailscale login --login-server` does work as expected, but it does not store the authentication. After disconnect/connect (or profile switch), the whole authentication process has to start again.

### Are there any recent changes that introduced the issue?

Updating from previous 1.55.* to 1.56.0

### OS

macOS

### OS version

14.2 (23C64)

### Tailscale version

1.56.0 - MAS Version

### Bug report

BUG-30e9c22e399c9eb7280683a45bc7ca00d029de6cb5cc4d396eac59f106c65443-20231214103242Z-540a4f9e4b754657

**Comment by samlinville** [comment]
Hi, we're aware of this issue and are working on a fix. We'll post updates here as we have them.

**Comment by samlinville** [comment]
Update: We believe that we have found a fix for the problem. We've submitted the fixed client to our TestFlight track, it will be available within the next day once Apple has reviewed it. We will release a patch to our stable release with the fix (1.56.1) in the next few days.

You can join our TestFlight track here: https://tailscale.com/kb/1083/install-unstable

**If you need a fix immediately to restore connectivity to your alternate coordination server, you can download an unstable package directly from our servers here: https://pkgs.tailscale.com/unstable/Tailscale-1.57.4-macos.zip** If you go this route, uninstall the prior version of Tailscale before installing this.

**Comment by atranchina** [comment]
Same issue on iOS, but no workaround with CLI obviously as stated above.

**Comment by samlinville** [comment]
@atranchina we are tracking the iOS issue in https://github.com/tailscale/tailscale/issues/10592

As noted on that ticket, we have an iOS TestFlight build that has now been released. If you need an immediate workaround before we issue the stable patch, I recommend the TestFlight with version 1.57.4+.

For folks tracking on the macOS issue, the TestFlight fix for macOS is also now live.

**Comment by agottardo** [comment]
1.56.1 is now available on the Mac App Store and should address the issue. We're still waiting on Apple to approve the equivalent iOS update.

**Comment by adipierro** [comment]
still broken if using multiple accounts with headscale

**Comment by adipierro** [comment]
Apparently, I somehow made Tailscale replacing first profile with a new one, overwriting it.
After deleting Tailscale folders in `~/Library/Containers` and `~/Library/Group Containers`, and clearing Keychain entries, it was fixed.
