### ISSUE TITLE
Broken link in message from tailscale up

### ISSUE THREAD

**Issue by tavianator** [tailscale/tailscale#10590]
### What is the issue?

I ran this:

```console
tavianator@tachyon $ sudo tailscale up --reset --advertise-exit-node
Warning: UDP GRO forwarding is suboptimally configured on br0, UDP forwarding throughput capability will increase with a configuration change.
See https://tailscale.com/s/ethtool-config-udp-gro
```

But https://tailscale.com/s/ethtool-config-udp-gro gives a 404

### Steps to reproduce

I'm not sure what caused that message in the first place, I assume some kind of `ethtool` setting.

### OS

Linux

### OS version

Arch Linux

### Tailscale version

1.54.1

**Comment by rosszurowski** [comment]
Sorry about this! It's a bug with a couple website changes we're rolling out. We'll have this fixed shortly.

In the meantime, the URL you're looking for is: https://tailscale.com/kb/1320/performance-best-practices/#ethtool-configuration

**Comment by rosszurowski** [comment]
The link should now be working again. Sorry for the trouble!

**Comment by MekayelAnik** [comment]
I am facing this problem again currently
```
tailscale up --accept-routes --advertise-exit-node --advertise-routes=10.15.36.0/22 --reset
Warning: IP forwarding is disabled, subnet routing/exit nodes will not work.
See https://tailscale.com/s/ip-forwarding
Warning: UDP GRO forwarding is suboptimally configured on eno1, UDP forwarding throughput capability will increase with a configuration change.
See https://tailscale.com/s/ethtool-config-udp-gro
```

**Comment by rosszurowski** [comment]
You should be able to follow the instructions at both of those URLs to resolve it:

* https://tailscale.com/s/ip-forwarding
* https://tailscale.com/s/ethtool-config-udp-gro

This issue was about those URLs not resolving, which I don't think it still the case. They seem to be working fine for me, but let me know if you're having trouble accessing them.
