### ISSUE TITLE
iOS: Alternate coordination server URL not working

### ISSUE THREAD

**Issue by pkrivanec** [tailscale/tailscale#10592]
### What is the issue?

Since the last update, the redirection to the login page no longer works if you have set an alternative coordination server URL.

### OS

iOS

### OS version

iOS 17.3

### Tailscale version

1.56.0

**Comment by pkrivanec** [comment]
I have installed version 1.55.67 from TestFlight, which works without any problems.
The versions after that have the problem.

**Comment by limitlessent** [comment]
Same issue after updating here. It completely ignores what you have set for the coordination server and just goes to the Tailscale.com auth page.

**Comment by samlinville** [comment]
Hi folks, we're aware of this issue and are working on a fix. We'll post updates here as we have them.

**Comment by samlinville** [comment]
Update: We believe that we have found a fix for the problem. We've submitted the fixed client our TestFlight track, it will be available within the next day once Apple has reviewed it. We will release a patch to our stable release with the fix (1.56.1) in the next few days.

You can join our TestFlight track here: https://tailscale.com/kb/1083/install-unstable

**Comment by samlinville** [comment]
The TestFlight build (1.57.4) has been released, if you need an immediate solution before we release the stable patch (1.56.1)

**Comment by nifoc** [comment]
> The TestFlight build (1.57.4) has been released, if you need an immediate solution before we release the stable patch (1.56.1)

Thank you for moving so moving so quickly on this!
I understand it's not a priority, but I hope some basic tests around Alternate Coordination Servers will be added, too.

That being said: Are TestFlight rollouts staged? I'm not seeing the new unstable release yet.

**Comment by sp391607254** [comment]
> 更新：我们相信我们已经找到了解决问题的方法。 我们已经向固定客户端提交了我们的 TestFlight 跟踪，一旦 Apple 对其进行审核，它将在第二天提供。 我们将在接下来的几天内发布稳定版本的补丁，其中包含修复程序 （1.56.1）。
> 
> 您可以在此处加入我们的 TestFlight 课程： [https://tailscale.com/kb/1083/install-unstable ](https://tailscale.com/kb/1083/install-unstable)

with this link  download tailscale  ios  app  the version is  1.56.0  the bug  exist

**Comment by samlinville** [comment]
@nifoc if you aren't seeing a 1.57.x build yet, you can also roll back to 1.55.67 by going to "Previous builds" in the TestFlight settings app, which the original reporter mentioned was working with alternate login URLs.

We're always iterating on our release and testing processes 🙂

**Comment by pkrivanec** [comment]
I have tested version 1.56.1 and 1.57.9, the alternate coordination servers are working again.
Thank you for fixing the problem so quickly.
