### ISSUE TITLE
macOS standalone broke with 1.56.0

### ISSUE THREAD

**Issue by gwillem** [tailscale/tailscale#10594]
### What is the issue?

Since my standalone tailscale autoupgraded to 1.56.0, no devices in my tailnet are pingable anymore, not even my own allocated 100.x address. 100.100.100.100 also unreachable, so no DNS. 

- system restart did not help
- uninstall and reinstall from Mac app store _did_ help

### Steps to reproduce

Wait for auto-upgrade to 1.56. I am not sure which version I was running before, but since I have auto-upgrade enabled, I assume the next latest version. 

NB. the bugreport-ID below was generated with the App Store version (which works)

### Are there any recent changes that introduced the issue?

- 

### OS

macOS

### OS version

MacOS 13.4.1

### Tailscale version

1.56.0

### Other software

multipass 1.11.1-mac
syncthing 1.27.0-1

### Bug report

BUG-9438ce29ba4de89d5e8cbdce1aceb5c873874dd694b93de4dd9c4fffb576096f-20231214105110Z-96ea28096ff2ce93

**Comment by agottardo** [comment]
@gwillem I would like to gather some extra system data to look into this issue. Would you mind creating a sysdiagnose from your Mac (by running `sudo sysdiagnose` in the Terminal)? You can send it to me via email: `andrea (at) tailscale.com`.

**Comment by rybaz** [comment]
Also had this issue, couldn't connect to anything. Switching to the app store variant seems to have fixed it, even though they're both 1.56.0.

**Comment by agottardo** [comment]
@rybaz were you also running macOS 13 (Ventura)?

**Comment by maxcohn** [comment]
Also running into this issue. MacOS 13.5.1 Ventura.

Is there anyway to download a previous version of the standalone MacOS app for the time being? I can't find it on the official site, only the most recent 1.56.

**Comment by aristocrates** [comment]
In our tailnet several users on macOS Ventura (13.*) have experienced the same symptoms here after updating to tailscale >= 1.56.0:
* 100.x unreachable from their machines
* Other people on 14.2 unaffected by the issue were still able to run e.g. `ping -c 2 100.[their tailscale IP]` and `tailscale ping [their machine name]` successfully, but the reverse direction was not possible.

Upgrading macOS to 14.2 fixed the issues for them.

**Comment by huyz** [comment]
@maxcohn I downgraded by manually crafting the URL found at the bottom of https://pkgs.tailscale.com/stable/#macos based on the [changelog](https://tailscale.com/changelog).

The last pre-1.56.0 version works just fine: https://pkgs.tailscale.com/stable/Tailscale-1.54.1-macos.zip

Go and get it, cold off the press!

**Comment by agottardo** [comment]
@maxcohn @aristocrates @huyz  If you're actively hitting this issue or have hit it in the previous 24 hours, it would really help if you could generate a sysdiagnose from the affected Mac (`sudo sysdiagnose` in the Terminal) and send it to me over email: `andrea (at) tailscale.com`. It is hard for us to investigate issues affecting specific macOS configurations without diagnostics from the system.

**Comment by huyz** [comment]
@agottardo There are a lot of files in there, some possibly containing sensitive data (as the Apple pop-up warns). Could you narrow down which files would be helpful to you?

**Comment by agottardo** [comment]
> @agottardo There are a lot of files in there, some possibly containing sensitive data (as the Apple pop-up warns). Could you narrow down which files would be helpful to you?

The information we need is contained in the large .logarchive file at the root of the sysdiagnose. Log entries around the time you launched Tailscale and noticed connectivity failing are what we need to identify the problem. If you want to dig for data itself, the most useful info will likely come from the "kernel" process, the "NetworkExtension" library and the "io.tailscale.ipn.macsys.network-extension" process. But overall, examining data from all processes would be better as there are likely interactions with system daemons at play here. 

If you're concerned about privacy, I would suggest that you open the log archive in Console.app, review the log entries for private data around the relevant timeframe and, once satisfied, send those over exclusively (the easiest way is to select multiple entries and copy them to a new text file).

**Comment by agottardo** [comment]
A change just landed in the unstable release track should potentially resolve this issue on macOS Ventura: https://pkgs.tailscale.com/unstable/Tailscale-1.57.16-macos.zip. It will also land on TestFlight soon, once Apple approves it. 

As always, please make sure to delete old copies of Tailscale on your Mac, and reboot your Mac after installing.

**Comment by huyz** [comment]
@agottardo Thanks! Works for me. I didn't even bother rebooting going from 1.54.1 to 1.57.16

**Comment by Chris-May** [comment]
@agottardo  This worked for me too. Thank you!

**Comment by huyz** [comment]
v1.57.36 broke it again.

I rolled back to 1.57.16 and it's working once more.

**Comment by huyz** [comment]
Oh but the latest v1.57.44 also works.

**Comment by dustinblackman** [comment]
I have a few colleagues who have fallen in to this issue. I've managed to repro it on a clean install of MacOS 13.6 using Tailscale 1.56.1. It works as expected using unstable 1.57.88.

**Comment by rojomisin** [comment]
latest unstable works, ty

here's the system extensions for correlating what could cause this
```
% systemextensionsctl list
5 extension(s)
--- com.apple.system_extension.network_extension
enabled	active	teamID	bundleID (version)	name	[state]
		W5364U7YZB	io.tailscale.ipn.macsys.network-extension (1.56.1/101.56.1)	IPNExtension	[terminated waiting to uninstall on reboot]
*	*	J6S6Q257EK	ch.protonvpn.mac.WireGuard-Extension (3.3.3/2309081240)	ProtonVPN WireGuard	[activated enabled]
*	*	J6S6Q257EK	ch.protonvpn.mac.OpenVPN-Extension (3.3.3/2309081240)	ProtonVPN OpenVPN	[activated enabled]
*	*	W5364U7YZB	io.tailscale.ipn.macsys.network-extension (1.57.88/101.57.88)	IPNExtension	[activated enabled]
--- com.apple.system_extension.endpoint_security
enabled	active	teamID	bundleID (version)	name	[state]
*	*	X9E956P446	com.crowdstrike.falcon.Agent (7.06/177.05)	Falcon Sensor	[activated enabled]
```

**Comment by rojomisin** [comment]
> Switching to the app store variant seems to have fixed it, even though they're both 1.56.0.

curious. why this would the app store version not exhibit the problem? is the os more trusting of dns behavior from app store version?

**Comment by anacrolix** [comment]
I'm seeing this problem with tailscale standalone 1.70.0. It's not configuring DNS correctly. macOS 14.5 (23F79)

**Comment by agottardo** [comment]
> I'm seeing this problem with tailscale standalone 1.70.0. It's not configuring DNS correctly. macOS 14.5 (23F79)

Please open a new issue with a bug report identifier.
