### ISSUE TITLE
[SECURITY] Received error: invalid key: API key *** not valid spammed in logs

### ISSUE THREAD

**Issue by michealroberts** [tailscale/tailscale#10600]
### What is the issue?

I had an API key associated to an OAuth client that I deleted some time ago in the Tailscale web app, however, said key is being repeatedly logged in plain text, which shouldn't exist anymore.

![CleanShot 2023-12-14 at 16 18 15](https://github.com/tailscale/tailscale/assets/84131395/c20a8fd7-153a-433b-a8e5-756e8a65c60b)

### Steps to reproduce

- Delete an OAuth Client in the web application.
- Run Tailscale node with another OAuth Client
- See logs getting spammed with the old key.

### OS

Linux

### Tailscale version

1.54.1

### Bug report

BUG-6be653b377328fb71af04d91023423c4b0802437a853bc0d5bb61ce8a61e83aa-20231214162008Z-bed8a71c8484a149

**Comment by DentonGentry** [comment]
It looks like it is trying to authenticate, using `tailscale up --authkey=tskey-kDRHqaCNTRL-____________`
That the OAuth client was invalidated from the admin panel doesn't get communicated down to nodes, they will use whatever arguments were passed to them.

Only the identifier portion of the key is logged, the same portion of the key which is shown in the admin panel.

**Comment by michealroberts** [comment]
@DentonGentry I didn't make it clear, this value is being passed in as an environment variable which absolutely is not the key that is being referenced in the screenshot above.

The code is as follows:

```
#!/bin/sh
/app/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055 &
/app/tailscale set --auto-update
/app/tailscale up --authkey=${TAILSCALE_OAUTH_CLIENT_SECRET} --hostname=${TAILSCALE_HOST_NAME} --advertise-tags=${TAILSCALE_OAUTH_CLIENT_ADVERTISED_TAGS}
echo Tailscale started
ALL_PROXY=socks5://localhost:1055/ HTTP_PROXY=http://localhost:1055/ http_proxy=http://localhost:1055/ ./app
```

I have checked that the .env that is being passed into the container is correct, and without showing you this as proof, I can confirm that the key being advertised in the logs as incorrect is not the same as in the .env file.

**Comment by DentonGentry** [comment]
Does the container have persistent storage? 

`/app/tailscale up --authkey=... --force-reauth` will force it to abandon the authentication it is trying and start again.

**Comment by michealroberts** [comment]
@DentonGentry I guess it must have, because that seems to have fixed the log spamming ...

**Comment by michealroberts** [comment]
Fixed with the suggested --force flag.
