### ISSUE TITLE
Arguments out of order for `tailscale whois` leads to confusing error message

### ISSUE THREAD

**Issue by thisisparker** [tailscale/tailscale#10605]
### What is the issue?

`tailscale whois` takes an optional `--json` flag, which if present must appear before the IP address being queried. If it comes after, it's treated as a second argument and tailscale returns

```
too many arguments, expected at most one peer
```

As a user I expect to be able to put `--json` after the argument (in practice, I was trying the command first with human-readable output and then wanted to append additional arguments to the end) but if we are opinionated on the order the other way I think we should specify that [in the docs](https://tailscale.com/kb/1080/cli#whois). 

### Tailscale version

1.56.0

**Comment by noncombatant** [comment]
We have to fix this with documentation, because Go's command line options parser does not accept mixed ordering of options and arguments. Historical note: BSD libc's `getopt` behaves this way, but GNU's (hence most Linux') is more flexible in the way you were hoping for. PRs in flight.
