### ISSUE TITLE
Tailscale interface keeps the old IP assigned with a different domain and current domain too in CentOS 8

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1060]
**Describe the bug**
Tailscale keeps the old IP assigned with a different domain and the current domain too in CentOS 8.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Tailscale on CentOS 8.
2. login into Tailscale using xyz@**domain1**.com
3. Get the Tailscale IP address. Make sure admin panel shows the device added to it.
4. Got to Linux Machine and run `tailscale up --force-reauth`.
7.  It will ask you to reauth , where you can login with asd@**domain2**.com
8. now when you look at the `ip addr show tailscale0`
9. it will show you currently assigned Tailscale IP and previously assigned tailscale IP too.

**Expected behavior**
It should remove the prior IP address.

**Version information:**
 - Device: [e.g. iPhone X, laptop]
 - OS: [e.g. Windows, MacOS]
 - OS version: [e.g. Windows 10, Ubuntu 18.04]
 - Tailscale version: [e.g. 0.95-0]

**Additional context**

```
[root@localhost cos2]# ip addr show tailscale0
5: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 100.110.137.77/32 scope global noprefixroute tailscale0
       valid_lft forever preferred_lft forever
    inet 100.106.126.119/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fe80::df0a:4770:2135:4bbc/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

**Comment by DentonGentry** [comment]
There have been no other occurrences of this symptom since this was filed, that I am aware of. Is there still an issue?

Barring further updates, we'll close this during the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT.
