### ISSUE TITLE
DSM6 64-bit spk package for Synology requires DSM7

### ISSUE THREAD

**Issue by thomasmorkeberg** [tailscale/tailscale#10611]
### What is the issue?

The DSM6 64-bit spk package for Synology requires DSM7.

<img width="617" alt="Skærmbillede 2023-12-15 kl  08 54 38" src="https://github.com/tailscale/tailscale/assets/153898650/06066414-00e9-4934-89fa-9424cfb0e571">

Translated: "This package requires DSM 7.0-40000 or later"

### OS

Synology

### OS version

Synology DSM6

### Tailscale version

1.56.0

**Comment by knyar** [comment]
I am not super familiar with Synology, but a quick check of package metadata shows that `7.0-40000` is listed as the maximum version.

```
$ curl -s https://pkgs.tailscale.com/stable/tailscale-x86_64-1.56.0-6000056000-dsm6.spk | tar -axf - INFO -O | grep ver
version="1.56.0-6000056000"
os_min_ver="6.0.1-7445"
os_max_ver="7.0-40000"
```

It's a bit suspicious that the message is saying that the same version *or later* is required.

Are you seeing the same behaviour with different versions of the Tailscale package and/or different versions of DSM?
