### ISSUE TITLE
systemd.service doesn’t load with ProtectClock=true

### ISSUE THREAD

**Issue by Freso** [tailscale/tailscale#1063]
**Describe the bug**
If setting `ProtectClock=true` under `[Service]` in the systemd unit file, systemd.service will no longer load.

**To Reproduce**
1. Run `sudo systemctl edit tailscaled.service`
2. (Potentially) Add new line containing `[Service]`
3. Under `[Service]`, add a line with `ProtectClock=true`
4. Save the file
5. Run `sudo systemctl daemon-reload` and `sudo systemctl restart tailscaled.service`
6. `systemctl status --full tailscaled.service` now returns this for me:
```
● tailscaled.service - Tailscale node agent
     Loaded: loaded (/usr/lib/systemd/system/tailscaled.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/tailscaled.service.d
             └─override.conf
     Active: activating (start-pre) since Thu 2020-12-24 03:06:45 CET; 317ms ago
       Docs: https://tailscale.com/kb/
Cntrl PID: 606540
      Tasks: 10 (limit: 38247)
     Memory: 11.9M
     CGroup: /system.slice/tailscaled.service
             └─606540 /usr/sbin/tailscaled --cleanup

Dec 24 03:06:45 din systemd[1]: Starting Tailscale node agent...
Dec 24 03:06:45 din tailscaled[606540]: logtail started
Dec 24 03:06:45 din tailscaled[606540]: Program starting: v1.2.10-te480f8ddf, Go 1.15.6: []string{"/usr/sbin/tailscaled", "--cleanup"}
Dec 24 03:06:45 din tailscaled[606540]: LogID: ffd4510f022024e02c624c2a1a5025bb8ec426af4ad663db06c5a87ad8ba1288
Dec 24 03:06:45 din tailscaled[606540]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Dec 24 03:06:45 din tailscaled[606540]: dns: using dns.directManager
Dec 24 03:06:45 din tailscaled[606540]: flushing log.
Dec 24 03:06:45 din tailscaled[606540]: logger closing down
Dec 24 03:06:45 din tailscaled[606540]: logtail: dialed "log.tailscale.io:443" in 201ms
```

**Expected behavior**
Since I did (and do!) not expect Tailscale to ever want to alter the system clock, I did not expect this setting to have any impact on Tailscale.

**Version information:**
 - Device: Desktop
 - OS: (Arch) Linux
 - OS version: rolling-release, did `pacman -Syu` earlier today; `Linux din 5.9.15.a-1-hardened #1 SMP PREEMPT Wed, 16 Dec 2020 23:05:56 +0000 x86_64 GNU/Linux`; `systemd 247 (247.2-1-arch)`
 - Tailscale version: 1.2.10

**Additional context**
Came across this while testing out directives for https://github.com/tailscale/tailscale/pull/1062

**Comment by bradfitz** [comment]
I can't think of anywhere where we'd be setting the system clock so I imagine systemd's ProtectClock does more than its docs suggest. Or CAP_SYS_TIME guards more than its docs suggest, and then one of them breaks the Go runtime's reading of the time. 

Can you grab an `strace -f -o /foo/trace.txt` of it failing?

Or if you have time, see if a normal Go program can read the time under systemd with that config.

**Comment by Freso** [comment]
So I edited my override.conf to disable all the protections I had made leading up to #1062 so it just has the `ProtectClock` clause and added the `strace` call (as well as made it not constantly restart on failure and repeatedly overwriting the trace log): 
[override.conf.txt](https://github.com/tailscale/tailscale/files/5743184/override.conf.txt)

This is the strace output: 
[trace.txt](https://github.com/tailscale/tailscale/files/5743182/trace.txt)

I’ve never done any coding with Go, so I’d have to figure that out to do the second suggested test. Maybe… :x

And output of systemctl status (now that it’s not perpetually restarting):
```
● tailscaled.service - Tailscale node agent
     Loaded: loaded (/usr/lib/systemd/system/tailscaled.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/tailscaled.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Sat 2020-12-26 15:02:27 CET; 8s ago
       Docs: https://tailscale.com/kb/
    Process: 49231 ExecStartPre=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
    Process: 49248 ExecStart=/usr/bin/strace -f -o /tmp/trace.txt /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tail>
    Process: 49295 ExecStopPost=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
   Main PID: 49248 (code=exited, status=1/FAILURE)

Dec 26 15:02:26 din systemd[1]: tailscaled.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 15:02:26 din tailscaled[49295]: logtail started
Dec 26 15:02:26 din tailscaled[49295]: Program starting: v1.2.10-te480f8ddf, Go 1.15.6: []string{"/usr/sbin/tailscaled", "--cleanup"}
Dec 26 15:02:26 din tailscaled[49295]: LogID: ffd4510f022024e02c624c2a1a5025bb8ec426af4ad663db06c5a87ad8ba1288
Dec 26 15:02:26 din tailscaled[49295]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Dec 26 15:02:26 din tailscaled[49295]: dns: using dns.directManager
Dec 26 15:02:26 din tailscaled[49295]: flushing log.
Dec 26 15:02:26 din tailscaled[49295]: logger closing down
Dec 26 15:02:27 din tailscaled[49295]: logtail: dialed "log.tailscale.io:443" in 198ms
Dec 26 15:02:27 din systemd[1]: tailscaled.service: Failed with result 'exit-code'.
```

**Comment by danderson** [comment]
Did a bunch of grepping through the trace and couldn't find any obvious smoking gun. But while digging into that, I also found that the log output produced by `systemctl status` seems to be incomplete, we should be logging a fair bit more about startup and the eventual shutdown. Does `sudo journalctl -u tailscaled` have more detail? (start from the last "Program starting" line)

**Comment by danderson** [comment]
In particular, I see in the strace that we're writing out more logs than what systemctl status shows, so I'm hoping there will be an actual error hidden in there somewhere.

**Comment by danderson** [comment]
Okay, after a bit more digging, the smoking gun seems to be:

```
49255 openat(AT_FDCWD, "/dev/net/tun", O_RDWR <unfinished ...>
49255 <... openat resumed>)             = -1 EPERM (Operation not permitted)
```

Can you verify that other sandboxing is disabled, and only ProtectClock is in place? `systemctl cat tailscaled.service` will show you the entire set of config options that are applied to the service.

If ProtectClock is the only thing here, then the conclusion is that protecting the clock makes it impossible to create tuntap devices?! That's definitely, uh, something.

**Comment by bradfitz** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectClock= says:

> ... installs a system call filter to block calls that can set the clock, and `DeviceAllow=char-rtc r` is implied.

Docs for `DeviceAllow` are at:

https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#DeviceAllow=

Is setting it to an implicit `char-rtc r` interfering with the old default of allowing us access to `/dev/net/tun`?

We probably need to explicitly set `DeviceAllow`?

**Comment by bradfitz** [comment]
Ah, bingo, `DevicePolicy`:

https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#DevicePolicy=auto%7Cclosed%7Cstrict

`ProtectClock` sets `DeviceAllow`, so the `DevicePolicy=auto` default then kicks in and prevents access to devices since `DeviceAllow` is then set. (Ignore the buggy docs on `DevicePolicy=auto` about the value needing to be "explicit")

**Comment by Freso** [comment]
> Can you verify that other sandboxing is disabled, and only ProtectClock is in place?

Yes.

Do you still want/need me to do the `journalctl`? It seems like Brad has found the issue.

**Comment by Freso** [comment]
Explicitly allowed `/dev/net/tun` and it seems like that made it work.
[override.conf.txt](https://github.com/tailscale/tailscale/files/5744381/override.conf.txt)
[journalctl.log](https://github.com/tailscale/tailscale/files/5744380/journalctl.log)
