### ISSUE TITLE
How to use forced derper to transit traffic

### ISSUE THREAD

**Issue by VMCoud** [tailscale/tailscale#10634]
### What is the issue?

When I use p2p hole-punch connection in China, the carrier will limit the speed, I want to disable the UDP hole-punch connection and force the traffic to be relayed through the self-built derp server, how do I do it?

### OS

Linux, Windows

### Tailscale version

1.5

**Comment by DentonGentry** [comment]
You could block outgoing UDP frames whose source port is 41641, to prevent direct connections from succeeding.

**Comment by VMCoud** [comment]
> You could block outgoing UDP frames whose source port is 41641, to prevent direct connections from succeeding.

Thank you.
