### ISSUE TITLE
Installing this software for NAS and Openwrt is cumbersome and not as simple as installing other systems

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#1064]
**Is your feature request related to a problem? Please describe.**
1、Installing this software for NAS and Openwrt is cumbersome and not as simple as installing other systems

**Describe the solution you'd like**
1、You want a simple integrated installation solution that doesn't require many steps

**Comment by bradfitz** [comment]
Dup of #724.

But, yes, we want to have nice packages for all popular NASes.
