### ISSUE TITLE
Window increases key activation

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#1065]
**Is your feature request related to a problem? Please describe.**
Windows installation can not use the activation key, we can not use the Google login account in other countries;

**Describe the solution you'd like**
It is recommended that Windows increase the use of activation keys to activate the system;
At the same time, we hope to add servers in China, Japan and South Korea to improve the speed of activation key.
Window adds hidden Settings to the display of task ICONS

**Comment by bradfitz** [comment]
I don't understand what this bug is about.

What's an "activation key"?

**Comment by talway** [comment]
Pre-auth Keys
https://login.tailscale.com/admin/authkeys
https://tailscale.com/kb/1085/auth-keys

Windows adds key input authentication

**Comment by bradfitz** [comment]
You can use the Tailscale CLI (`tailscale up`) on Windows too:

https://tailscale.com/kb/1080/cli

We have no plans to add a GUI for that, though. We think it's a power user feature and using the CLI is appropriate.

**Comment by talway** [comment]
Test OK

"c:\Program Files (x86)\Tailscale IPN\tailscale.exe" up --authkey=tskey-614e7b2c
