### ISSUE TITLE
FR: Providing admx and adml files for MS Intune

### ISSUE THREAD

**Issue by boonedoggle** [tailscale/tailscale#10651]
### What are you trying to do?

Create and manage policy via Microsoft Intune MDM.

### How should we solve this?

Creation of a set of admx and adml administrative template file to make managing of Tailscale simple within MS Intune

### What is the impact of not solving this?

Editing the registry by pushing powershell scripts to endpoints. But this is unpredictable and hard to audit.

**Comment by sailorfrag** [comment]
This is being tracked in #6495 

We are working on this, it is currently considered a requirement for MDM policies GA but I do not currently have an ETA.

**Comment by sailorfrag** [comment]
As a follow-up, #6495 has been resolved and the template is currently available at https://github.com/tailscale/tailscale/tree/main/docs/windows/policy

Packaging for the template is being tracked in #10767
