### ISSUE TITLE
FR: Expose `OPERATOR_INITIAL_TAGS` in Helm chart values

### ISSUE THREAD

**Issue by netthier** [tailscale/tailscale#10659]
### What are you trying to do?

I'm attempting to set up the Tailscale Kubernetes operator in multiple clusters. I don't want one cluster to be able to access the same resources as other clusters, so the operator tags must differ. However, I was not able to modify them.

### How should we solve this?

I found the `OPERATOR_INITIAL_TAGS` environment variable in the code, but no way to set it when using the Helm chart.
I believe the easiest solution here would be to simply make it configurable through the `values.yaml`, similar to how proxy tags can be set already.

### What is the impact of not solving this?

As I'm deploying the chart with kluctl, I can simply patch the environment variable in.
I don't believe this is possible with vanilla Helm installations though (unless one generates the manifests and directly modifies them)

**Comment by netthier** [comment]
@knyar If this is something desirable for the Tailscale project I could open a PR for it

**Comment by irbekrm** [comment]
@netthier you are welcome to open a PR if you have time. 

> I believe the easiest solution here would be to simply make it configurable through the values.yaml

This makes sense, it would also be good to add some comments there with links to our docs explaining how the tag needs to be set up.

**Comment by irbekrm** [comment]
Fixed in https://github.com/tailscale/tailscale/pull/10874
