### ISSUE TITLE
 FR: Expand mullvad vpn to Puerto Rico 

### ISSUE THREAD

**Issue by yordan-flexio** [tailscale/tailscale#10669]
### What are you trying to do?

I tried to add mullvad vpn to my plan in order for my employee's devices to have exit nodes with privacy protection and able to use services that are region locked.

### How should we solve this?

Give a VPN offering with exit nodes to Puerto Rico. Legally it should be the same as US.

### What is the impact of not solving this?

Unable to purchase the plan add-on and also makes part of the vpn solution our team had in mind infeasable.

**Comment by knyar** [comment]
Thank you for reaching out. I believe you should be able to use any of the existing Mullvad locations via Tailscale. However, I am not seeing Puerto Rico listed in [the list of servers](https://mullvad.net/en/servers) that Mullvad provides.

So perhaps they either don't provide a location in Puerto Rico, or it is not publicly available? This is not something that's within our control unfortunately. Barring further comment, we'll expect to close this issue during the next regular bug scrub.

**Comment by yordan-flexio** [comment]
Hi, I think there was a misunderstanding.
It's not that I need an exit node in Puerto Rico, is that as a resident of Puerto Rico I cannot purchase the Mullvad add-on. I would be okay using any exit node in the US, I just don't want to use one of our own servers as an exit node.

PR is a US region, when I try to purchase it, I get forwarded to a page that says to report an issue if my region is not listed. In my experience, it's very common for Puerto Rico IP addresses to be classified separately from the US as an oversight.

![Screenshot 2023-12-22 at 4 26 37 PM](https://github.com/tailscale/tailscale/assets/132277942/590019ad-50f5-4426-9c1a-d868a6a02e50)
![Screenshot 2023-12-22 at 4 28 05 PM](https://github.com/tailscale/tailscale/assets/132277942/75312195-6fbe-4402-b96a-47fab300ee16)
