### ISSUE TITLE
Tailscale Lock - New node approval issue on iOS

### ISSUE THREAD

**Issue by FreeWoRLD83** [tailscale/tailscale#10677]
### What is the issue?

iOS device is already a “signing node”. When trying to add a new node, scanning the QR code successfully opens tailscale ios app and the appropriate approval screen. However, “approve” button does not appear, but only “cancel” button does. Nevertheless, touching the invisible button successfully approves the device.

(Removed Tailscale iOS app completely, rebooted iOS and reinstalled but issue still persists and steps to reproduce was successful)

### Steps to reproduce

In a tailscale lock enabled environment;

* Add a new node
* Login to tailscale admin console - machines
* Sign a new node
* Mobile device QR code
* Scan QR on an iOS device that is “signing node”
* iOS app takes you to approval screen
* On the screen, “Approve” button does not appear that should be on the right side of the “Cancel” button. Though the button still works and approves the device. 

![image](https://github.com/tailscale/tailscale/assets/6927136/8c019234-021c-494b-879d-804f23d54a6e)

### OS

iOS

### OS version

17.2.1

### Tailscale version

1.56.1

### Bug report

BUG-5a902073d512c76de8799012f0ef1dd5922e2764905938c5187214137f7477dd-20231222144552Z-68a5bb4ec22e1e40

**Comment by agottardo** [comment]
Thanks for reporting this! I can confirm the button is there, but the blue color is not rendering in version 1.56. Tapping in the empty area on the right side still works. I have pushed a fix and it will land in TestFlight as soon as it is approved.

<img width="517" alt="Screenshot 2023-12-23 at 10 54 30" src="https://github.com/tailscale/tailscale/assets/9057073/c2727401-e104-42d9-9028-8e141c5b9b2c">

**Comment by FreeWoRLD83** [comment]
Thank you
