### ISSUE TITLE
App connector not following CNAME records

### ISSUE THREAD

**Issue by woutertinusf19** [tailscale/tailscale#10687]
### What is the issue?

I've tried to use the new beta "Apps" feature to connect to an Azure SQL database, but it doesn't seem to work when I add `example.database.windows.net` to the list of domains. This is the only stable endpoint that Microsoft provides, but it's far from the final domain that's being used to actually connect. There's a whole chain of CNAME records to go through before arriving at an IP address, e.g.: `example.database.windows.net` > `dataslicexx.westeurope.database.windows.net` > `dataslicexxwesteurope.trafficmanager.net` > `crxx.westeuropexx.control.database.windows.net` > `20.61.xx.xx`

As a workaround I tried to route the whole `*.windows.net` domain through the app (which also didn't work), but even if it did, the problem with that would be two-fold:
- The minor one being that it's not very fine grained, it would be nicer if it were possible to separate traffic to different SQL servers (e.g. prod/test or different regions). 
- The bigger problem is that this whole chain of CNAME's is outside of my control. If Microsoft decides to switch to `azuresql.com` or anything else for their internal load balancing/traffic management, my database connectivity would be dead.

As a side note, I noticed that the recursive resolution of the `A` record while "trapped" by the Tailnet app logic is very slow (multiple seconds), which is not the case when it's not part of an "app", so it seems to be doing something, but not routing correctly.

As a second side node, it would be nice to have some diagnostics in the admin panel, e.g. which IP's are being routed as part of the app.

### Steps to reproduce

- Create an Azure SQL database
   - Add the connector node(s) egress IP(s) to the firewall
- Create an app in Tailscale 
   - Include the Microsoft-given domain e.g. `example.database.windows.net`
   - Add one or more app connectors (I have two of them, both show green) 
- Add autoApprovers for IPv4/IPv6 for the connectors as per documentation 
- Allow your user to access `autogroup:internet:1433` (SQL Server port)
- Attempt to connect to the Microsoft-given domain from the SQL Server Management Studio
- Get an error that your local IP is not allowed access (this should be the connector IP, which should be allowed)

(Please note that if you check my account based on the bug identifier, you'll find that I've reverted to my original solution based on static subnet routes to restore connectivity, once the static routes are removed connectivity is lost).

### Are there any recent changes that introduced the issue?

N/A

### OS

Windows

### OS version

11

### Tailscale version

1.56.1

### Other software

N/A

### Bug report

BUG-41e50c6bb3e15e6a01c56f60ee7ec7a62764eb20f5349c4bd97aa465a5fe5455-20231223203509Z-23da8c4abaaeaa03

**Comment by danield555** [comment]
confirmed on me as well. this cripples the app connection functionality, as I was hopping to reduce the use of standard exit node with it, as a more user-transparent and flexible option.

**Comment by corrylc** [comment]
I see this issue with Snowflake connections from the CLI/SDK as well, where `ACCOUNT_IDENTIFIER.snowflakecomputing.com` is CNAME'd to an ELB.

**Comment by manibatra** [comment]
Facing the same issue with RDS. And also the above stated connection issue to MongoDB Atlas when using SRV connection string

**Comment by sylr** [comment]
I'm having the same problem with S3. I created a Connector for `*.s3.eu-central-1.amazonaws.com` but it did not work. My bucket DNS is a CNAME to `s3-r-w.eu-central-1.amazonaws.com`, adding `s3-r-w.eu-central-1.amazonaws.com` to the connector works as workaround.

**Comment by manibatra** [comment]
Looks like following CNAMEs is officially [not supported](https://tailscale.com/kb/1332/apps-best-practices?q=app%20connectors#cnames)

**Comment by woutertinusf19** [comment]
😢 that limitation makes the feature useless to me.

**Comment by tateeskew** [comment]
Should we expect CNAMEs to work in the future?

**Comment by WouterTinus** [comment]
Ping to @catzkorn because I noticed you triaged some (more recently reported) app connector issues, I have a feeling this one perhaps slipped through the cracks over the Christmas break?

**Comment by catzkorn** [comment]
Hi! Yup, this one escaped me! 

But good news! This has been resolved and is current available in unstable client versions 1.59.43 or newer, and will be included in our 1.60 stable release.

**Comment by dhade33** [comment]
i have the same issue, my current version is 1.62.1

**Comment by dhade33** [comment]
if any one connected to azure database for postgres, what is the app connector domains used ?

**Comment by xpuska513** [comment]
> I also noticed that it cannot be used with atlas mongodb : mongo uses a srv based redirection so it appears not only cname, but also SRV dns queries are not taken into account : see https://www.mongodb.com/developer/products/mongodb/srv-connection-strings/ for how mongo works

As for mongodb serverless I found the workaround, you can add a wildcard domain that points to the cluster group.
e.g `platform-dev-mongodb.unique_id.mongodb.net` will result in using `*.unique_id.mongodb.net` in the app connector domain list, just verified and seems to be working fine.

**Comment by lorengordon** [comment]
We seem to be encountering this issue in tailscale 1.90.9. Or an issue remarkably similar... When we setup the app connector, we must include every host/domain in the CNAME record chain, including the final A record. If we do not, then it may work one time but then in subsequent connections the final A record will fail to resolve and dns will return a SERVFAIL.

For example, in the below, if we add only `*.{sub}.splunkcloudfed.com` and `{sub}.splunkcloudfed.com` as the app connector domains, then it will fail (intermittently) as described above.

```
❯ dig +noall +answer {sub}.splunkcloudfed.com
{sub}.splunkcloudfed.com. 272 IN CNAME sh1.{sub}.splunkcloudfed.com.
sh1.{sub}.splunkcloudfed.com. 272 IN CNAME sh-i-02162b50244fd6680.{sub}.splunkcloudfed.com.
sh-i-02162b50244fd6680.{sub}.splunkcloudfed.com. 272 IN CNAME ec2-15-205-xx-yy.us-gov-west-1.compute.amazonaws.com.
ec2-15-205-xx-yy.us-gov-west-1.compute.amazonaws.com. 272 IN A 15.205.xx.yy
```

Once we add the final A record host as an app connector domain, then it succeeds consistently. Prior to discovering this, users needed to use the app connector system as an exit node for it to work consistently.

But we do not want to add the host, since that may change as the service is updated over time. And we do not want users to use the app connector as a full exit node for all their traffic.

**Comment by lorengordon** [comment]
Another interesting workaround has been CNAME flattening, as provided by nextdns, since that just returns the final A record, associated to the top-level app connector domain:

```
❯ dig +noall +answer {sub}.splunkcloudfed}.com
{sub}.splunkcloudfed.com. 3600 IN A 15.205.xx.yy
```

But CNAME flattening seems to break DNSSEC, so that's not a panacea...🤦
