### ISSUE TITLE
Unable to log in to 3rd-party servers (Headscale) on Android after restarting the app

### ISSUE THREAD

**Issue by APYYPZMF** [tailscale/tailscale#10700]
### What is the issue?

Restarting the APP cannot automatically log in, as shown below.
![Screenshot](https://github.com/tailscale/tailscale/assets/140040310/9c57d8ed-cb28-44b0-a94b-13a28044fc91)
Running Headscale behind a reverse proxy (Nginx). However, there are no connection attempts in the Nginx log.

This issue appears to have persisted since the last time the change server function was broken, see:

- https://github.com/tailscale/tailscale/issues/6671
- https://github.com/tailscale/tailscale/issues/7818
- https://github.com/tailscale/tailscale/issues/9490
- https://github.com/tailscale/tailscale/issues/9788

### OS

Android

### OS version

Android 13 (MIUI v14.0.25)

### Tailscale version

v1.56.0-tf51793b90-g49ed1df6cc9 (F-Droid)

**Comment by aradng** [comment]
The workaround above is a nuisance and the issue still persists.

**Comment by agottardo** [comment]
Fixed in the new Android app (v1.66 or later).
