### ISSUE TITLE
Nobara-39 install script fail: dnf-5 and configmanager plugin

### ISSUE THREAD

**Issue by HRA42** [tailscale/tailscale#10707]
### What is the issue?

The install script tried to execute:

```bash
sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo
```

If version 5 of dnf is present the dnf command won't find the configmanager plugin, as it is not available for dnf-5

### Steps to reproduce

Try to install tailscale on federoa with dnf-5, or use nobara-39

### Are there any recent changes that introduced the issue?

Nobara-39 uses dnf-5

### OS

Linux

### OS version

Nobara-39

### Tailscale version

1.56.1-1

**Comment by knyar** [comment]
Thank you for reporting this. The support for [alternative RPM distros](https://github.com/tailscale/tailscale/blob/09136e59959e13e3a2437c3c451245652b1a9ee1/scripts/installer.sh#L197) in the installer script is quite minimal, and I [can't repro](https://gist.github.com/knyar/046a5f75c366bdb1df16a0a42b8d0356) this in the `fedora:latest` Docker image, so I suspect this is an area where Nobara diverged from upstream.

What do you think is the easiest way to get access to a system with `dnf-5` to investigate this? We use Docker for [testing the installer script](https://github.com/tailscale/tailscale/blob/main/.github/workflows/installer.yml) and it's usually handy for testing locally, but I've not been able to find a Docker image for Nobara.

**Comment by HRA42** [comment]
@knyar: dnf-5 is not officially integrated into fedora-41, so if you have a fedora-39 container, you would need to include `sudo dnf install dnf5` according to [dnf-5 documentation](https://github.com/rpm-software-management/dnf5?tab=readme-ov-file#installing-dnf5).

I installed it manually via `sudo dnf-3 config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo`

I think the best way would be to look if dnf-5 command is installed and if so, then execute the config-manager via dnf-3

**Comment by HRA42** [comment]
or another option would be to execute `dnf --version | grep "dnf5"` if it returns anything, then the command `dnf-3 --version` should be called to check if that package is present, and then the command should be `sudo dnf-3 config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo`
