### ISSUE TITLE
iOS 14.2: All connections fail while Tailscale is connected

### ISSUE THREAD

**Issue by berwyn** [tailscale/tailscale#1072]
**Describe the bug**
I have an iPad Air running iOS 14.2, and upon connecting Tailscale all connections on the device fail until I disconnect Tailscale. I cannot do name lookups or ping any address, public internet or on the Wireguard mesh. As soon as I disconnect the client, all connections (sans Tailscale ones) start functioning again.

**To Reproduce**
1. Install Tailscale
2. Login to your existing account
3. Connect the client
4. Attempt to load any website in any browser.

**Expected behavior**
Connections succeed, names resolve, and webpages. load.

**Version information:**
 - Device: iPad Air, 4th Generation
 - OS: iOS
 - OS version: 14.2 (18B92)
 - Tailscale version: 1.2.10 (101.2.10)

**Additional context**
I did attempt to reauthenticate and reinstall the app, but neither case managed to solve the problem, and this only seems to occur on the iPad. My Android and Windows devices all seem to be fine, so I'm not sure it's an account issue.

**Comment by bradfitz** [comment]
What's your Tailscale IP?

**Comment by berwyn** [comment]
The iPad is 100.111.146.102

**Comment by bradfitz** [comment]
Did you install it via TestFlight?

**Comment by bradfitz** [comment]
I notice you have your DNS servers both listed twice. Maybe iOS is unhappy about that? Could you try removing the duplicates?

**Comment by berwyn** [comment]
I cleared up the duplicate DNS servers, reinstalled the VPN profile, and rebooted the iPad but no dice. I did install using TestFlight, yes.

**Comment by colek42** [comment]
@bradfitz I am having the same issue.  My Tailscale IP is 100.64.33.105.  iOS 14.2, iPad Pro 12.9 4th Gen.  Tailscale version 1.2.8.

**Comment by darshinimashar** [comment]
The customer has reported the same issue on Tailscale 1.4.5.

From Customer:

On my iPhone, if I stop and restart tailscale ( maybe more than once), all network access is stopped. 
 So, tailscale is running and I can use a browser to access the "normal" internet
Then I stop and restart the tailscale.
Now access to the internet is blocked (but not to the tailscale private network) until I stop and unload the tailscale app
iPhone SE 2020 iOS 14.2 


My phone ip is 100.64.96.24
Also my laptop is 100.66.156.22

**Comment by apenwarr** [comment]
Quite a few reports in the past that our DNS handling was not great. This is heavily revised in v1.8.

@berwyn @colek42 do you mind re-testing on latest v1.8 to see if the problem reproduces? If it does, please post again your tailscale IP and the timestamp.

**Comment by colek42** [comment]
I reset my iPad and never had the issue again.

**Comment by berwyn** [comment]
Yeah, I cleared it up _somehow_ and I honestly can't remember what I did to accomplish that or how to replicate the problem :/

**Comment by DentonGentry** [comment]
I suspect this was fixed by the DNS fixes in release 1.8 and 1.10.
