### ISSUE TITLE
Windows client ignores registry policy LoginURL

### ISSUE THREAD

**Issue by Bert-Proesmans** [tailscale/tailscale#10736]
### What is the issue?

The tailscale desktop client v1.56.1 for windows ignores the LoginURL (HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Tailscale\LoginURL) policy registry key. The symptoms are exactly the same as described in #6879; 

1. interacting with the program icon will always open the browser for login via the **tailscale.com domain**
2. using the CLI and argument --login-server uses the custom domain as expected

Expectation;
The desktop client program should open the browser and browse to the url defined by LoginURL registry key to start authentication.

### Steps to reproduce

1. be on windows
2. create registry key value HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Tailscale\LoginURL with data 'https://tailscale.custom.com'
3. download and install Tailscale for windows, version 1.56.1
4. open tailscale desktop program (if not automatically opened)
5. start tailscale login

Observe that the browser opens for authentication via login.tailscale.com instead of tailscale.custom.com.

### Are there any recent changes that introduced the issue?

I'm not sure, my programming expertise is low.

There is a mention of fixes to this behaviour for the platforms Mac OS, Linux, TVOS in the release notes for version 1.56.1. There is no mention of the windows platform, this might be related?

![image](https://github.com/tailscale/tailscale/assets/2027877/e44434d5-ffb2-49bc-9894-16be488b3537)

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.56.1

### Other software

None of the explicitly mentioned software. We're seeing this happen on machines for general administration purposes.
Software is basically browsers + Intune management + Windows Defender.

**Comment by dariusarnold** [comment]
I also experienced this issue but with a client version which is supposed to include the fix. It is important to restart (stop and start) the tailscale service using `net stop/start tailscale` after modifying the registry values, otherwise the settings won't be applied. Restarting the client is not enough.

**Comment by sailorfrag** [comment]
Yes, most policies are enforced by the service, and for a few reasons, it must be restarted before policy changes will take effect. The client application only applies policies related to UI-related things, such as hiding certain menu items.
