### ISSUE TITLE
Windows: populateTrayLocked: "Unable to setup Tailscale client: Shell_NotifyIcon"

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#1073]
**Describe the bug**
Remote Win10 prompts an error, but can be connected, restart after normal

**Screenshots**
![Snipaste_2020-12-28_10-00-32](https://user-images.githubusercontent.com/10338638/103189960-ec203880-4909-11eb-8ca9-6927d1c4c0d7.png)

**Version information:**
 - Device: [Windows10]
 - OS: [Windows]
 - OS version: [e.g. Windows 10,
 - Tailscale version: [The latest version]

**Additional context**
Relays use distant relays with poor connection quality,

**Comment by talway** [comment]
1, can manually or to choose their own relay, the system is not accurate choice;

In the case of the same network, the relay used by the router is completely different from the relay used by the computer below the router.

I am hung up another agent, do not know is this reason, the standard that chooses relay is how to choose;



2, Win10 remote desktop or another set up the inbound firewall, simple installation software, Win10 or can not be remote, or manual selection;

**Comment by bradfitz** [comment]
What actual version of Tailscale are you using? And Windows?

What type of "distant relay" are you talking about? And what is "remote" about your Win10?

Unfortunately I'm having a hard time understanding this bug report.

I can look into that stack trace, though.

**Comment by talway** [comment]
![Snipaste_2020-12-28_14-09-01](https://user-images.githubusercontent.com/10338638/103193100-4cb57280-4916-11eb-890b-7c8ee388fd4f.png)

Windows10
![333](https://user-images.githubusercontent.com/10338638/103193271-ebda6a00-4916-11eb-8eb6-1b2be87c25be.png)

**Comment by talway** [comment]
The computer where the error occurred, and the version

**Comment by talway** [comment]
After the restart, this error message appears again, close, open the software can be used again;

System is win10

**Comment by peske** [comment]
The main problem here is the fact that the error we're getting isn't descriptive at all. The error comes from https://github.com/lxn/walk/blob/master/notifyicon.go#L102:
```go
if !win.Shell_NotifyIcon(win.NIM_ADD, &nid) {
	return nil, newError("Shell_NotifyIcon")
}
```
So creating the icon fails, but we cannot know why. `win.Shell_NotifyIcon()` function is defined in `lxn/win` package, https://github.com/lxn/win/blob/master/shell32.go#L487, where it calls [Shell_NotifyIconW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyiconw) Windows API function that simply returns true/false. To get more info about the error, https://github.com/lxn/win/blob/master/shell32.go#L487 needs to be extended to include `GetLastError` call on failure.

My wild guess is that the error happens due to localization. @talway , is it possible for you to temporary change the localization settings in Windows and reboot to see if the error will happen again?

**Comment by anaganisk** [comment]
@peske It works only when I've set language to English United Kingdom, not United states.

**Comment by josharian** [comment]
Here's output from the "more descriptive error" from tray creation failing, from Avery's logs on Apr 20:

```
ui: walk.NewNotifyIcon: Shell_NotifyIcon

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x0, 0xc000177850, 0x0)
	runtime/debug/stack.go:24 +0xa5
github.com/lxn/walk.newErr(...)
	github.com/lxn/walk@v0.0.0-20201110160827-18ea5e372cdb/error.go:81
github.com/lxn/walk.newError(0x146c313, 0x10, 0xc00015c300, 0xc000177898)
	github.com/lxn/walk@v0.0.0-20201110160827-18ea5e372cdb/error.go:85 +0x2d
github.com/lxn/walk.NewNotifyIcon(0x1521a20, 0xc000700400, 0x0, 0x0, 0x0)
	github.com/lxn/walk@v0.0.0-20201110160827-18ea5e372cdb/notifyicon.go:103 +0x367
tailscale.io/win/ui.(*app).populateTrayLocked(0xc000178000, 0x40, 0x148d868)
	tailscale.io/win/ui/ui.go:363 +0xa5
tailscale.io/win/ui.RunUI(0xc00001c5c0, 0x40)
	tailscale.io/win/ui/ui.go:1010 +0x265
tailscale.io/win/ui.Main()
	tailscale.io/win/ui/main.go:80 +0x4f5
main.main()
	tailscale.io/win/wg64/main.go:13 +0x27
; windows: <nil>
```

**Comment by bradfitz** [comment]
I have a reliable repro for this now at HEAD.

Repro is user1 starts Tailscale in unattended mode, keeps system tray app running. Then user2 logs in and starts system tray app.

Error ultimately comes from [Shell_NotifyIcon](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyicona) returning false.

```go
// NewNotifyIcon creates and returns a new NotifyIcon.                                                                                                          
//                                                                                                                                                              
// The NotifyIcon is initially not visible.                                                                                                                     
func NewNotifyIcon(form Form) (*NotifyIcon, error) {
        fb := form.AsFormBase()
        // Add our notify icon to the status area and make sure it is hidden.                                                                                   
        nid := win.NOTIFYICONDATA{
                HWnd:             fb.hWnd,
                UFlags:           win.NIF_MESSAGE | win.NIF_STATE,
                DwState:          win.NIS_HIDDEN,
                DwStateMask:      win.NIS_HIDDEN,
                UCallbackMessage: notifyIconMessageId,
        }
        nid.CbSize = uint32(unsafe.Sizeof(nid) - unsafe.Sizeof(win.HICON(0)))

        if !win.Shell_NotifyIcon(win.NIM_ADD, &nid) {
                return nil, newError("Shell_NotifyIcon")
        }
```

/cc @peske

**Comment by bradfitz** [comment]
@sailorfrag, some updates:

* happens even without Unattended Mode enabled: just start it as 1 user, then switch to second user and try to start the frontend.
* adding some log prints, I see the MainWindow being created has different hWnd values for user1 and user2, so it's not like user2 is trying to Shell_NotifyIcon ADD to another user's hWnd.

**Comment by bradfitz** [comment]
Oh, even if I stop tailscale-ipn.exe (and have Unattended off) on my user1, I still get the prompt on user2.

I also get the prompt if I run tailscale-ipn.exe in a Admin user2 cmd.exe (but I got a prompt that user2 isn't an admin and needs user1's admin password)....

So maybe this is about whether the user running tailscale-ipn.exe is a local Admin?

**Comment by bradfitz** [comment]
Well, crap, I logged my user2 out and logged back in, which went through some "Hey, let's set up Windows!" flow (new version of Windows that user2 had never been properly introduced to?) and then it all worked.

So I have no clue.

Maybe the workaround is to tell people to log out and log back in if they see this? Not a very satisfying answer.

We should do some analytics to see how often users are seeing this in practice.

**Comment by bradfitz** [comment]
@dblohm7, can you look into this?

**Comment by dblohm7** [comment]
Yeah, I'll push it onto my queue.

**Comment by dblohm7** [comment]
My current hypothesis is that the client is running before the taskbar has initialized. We're treating the `Shell_NotifyIcon` error as fatal, whereas if we were to continue running and pumping messages, `walk` should receive a `TaskbarCreated` message from the shell. `walk` handles this correctly and will then (re-)populate the icon.

**Comment by dblohm7** [comment]
I have concluded that the best place to fix this is upstream. I'll need to do two PRs: the second is dependent on the first.
The first PR is at https://github.com/lxn/win/pull/123

**Comment by bradfitz** [comment]
@dblohm7, as you might've noticed, it's a little hard/slow to get changes in to that repo. If we need to fork it (as least as a temporary dev fork while working to upstream changes), we can.

**Comment by jaum20** [comment]
I have this same problem

![image](https://user-images.githubusercontent.com/36702273/163299355-2c17a09d-9ead-436b-92cf-fd66b27af667.png)

**Comment by bradfitz** [comment]
@jaum20, we don't track closed issues.

Please file a new bug with complete details.
