### ISSUE TITLE
settings on Android are not persistent between reboots / restarts

### ISSUE THREAD

**Issue by jee-r** [tailscale/tailscale#10748]
### What is the issue?

Hello,

I noticed that when i reboot my phone or restart tailscale app on my android phone,  `exit node` and  `Allow LAN access` are not persistent  they are set to none. 

### Steps to reproduce

- Start the android app
- Set a an exit node 
- Allow LAN access 
- active tailscale
- restart the app or reboot the phone
- active tailscale
- check if it use the exit node set previously 

### OS

Android

### Tailscale version

1.56.0

### Bug report

BUG-bc7c5c068261c5384b43aa5f19cab7fa160b8e28601f621213dbbc46ab040d4f-20240105102924Z-b5b9e0f05ca8852f

---
related to : https://github.com/tailscale/tailscale/issues/9428

**Comment by 12nick12** [comment]
The custom server also is not remembered.

**Comment by vin-blip** [comment]
Is tailscale actively working on this or not?

**Comment by catzkorn** [comment]
Hi,

We recently begun work on Android again, we will update related issues when we have further information.

**Comment by vin-blip** [comment]
Thanks @catzkorn Can't wait for the new updates.

What we desperately need is be able to set defaults such as a favourite exit node and connect to it automatically on launching the tailscale app, as well as automatically reconnect if the connection fails for some reason.

**Comment by jee-r** [comment]
Great, Thank you @kari-ts

**Comment by vin-blip** [comment]
Umm no sorry, the issues still exist on both my android phone and the tablet. I have updated the app to the latest version as well.

**Comment by jee-r** [comment]
@vin-blip  i think changes that has been merged are not deployed yet. so yes issue still exist in 1.58.2 (Added on Feb 11, 2024 on F-Droid)
