### ISSUE TITLE
Expectation: Is it possible to set up a relay node in China? No, it is also possible to set up a relay node in Hong Kong. It is too slow for China to use Japan's relay node.

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#1075]
RT

**Comment by talway** [comment]
We will set up the relay node for our own use, and you can also provide the node software. I hope you can consider it.

Most of our computers are in the internal network, and there is basically no IP of the external network, so we cannot connect directly to each other. We must use fast relay nodes to enhance the connection speed.

Thank you very much!

**Comment by bradfitz** [comment]
We have no current plans to run relay nodes within China ourselves, but the relay code is open source:

https://github.com/tailscale/tailscale/tree/main/cmd/derper

We have plans to let you add your own private relays to your own network.

**Comment by talway** [comment]
Can synchronize to compile a possible application software released, similar to the web site https://pkgs.tailscale.com/stable/

**Comment by bradfitz** [comment]
We've started working on that for some early testers. When it's widely available we'll have downloads & packages, yes.

**Comment by talway** [comment]
I want to test repeater software. I want to be a tester. Please send me an email. Thank you

talwayh@gmail.com
