### ISSUE TITLE
tailscale-cli to tailscaled version mismatch

### ISSUE THREAD

**Issue by CocoXiaoLong** [tailscale/tailscale#10762]
### What is the issue?

tailscale status
```Warning: client version "1.56.1" != tailscaled server version "1.54.1"```

tailscale set --accept-dns=false
```
Warning: client version "1.56.1" != tailscaled server version "1.54.1"
400 Bad Request: json: cannot unmarshal object into Go struct field MaskedPrefs.AutoUpdateSet of type bool
```

### OS

Linux

### OS version

archlinux rolling-release

### Tailscale version

version mismatch

### Bug report

BUG-79b0d7d35306137dfcd12ca17690634f1a0a1ba60243343e7fcccdc839543214-20240105214555Z-907fb7ec2f76a786

**Comment by bradfitz** [comment]
Seems you (or your package manager) updated Tailscale but didn't restart tailscaled. Restart tailscaled and try again?

**Comment by CocoXiaoLong** [comment]
didn't try it
reinstalled tailscale, now it works
