### ISSUE TITLE
FR: Support for ParrotOS

### ISSUE THREAD

**Issue by deandre** [tailscale/tailscale#10778]
### What are you trying to do?

OS=debian
VERSION=lory
PACKAGETYPE=apt
UNAME=Linux parrot 6.5.0-13parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1parrot1 (2023-12-19) x86_64 GNU/Linux

PRETTY_NAME="Parrot Security 6.0 (lorikeet)"
NAME="Parrot Security"
VERSION_ID="6.0"
VERSION="6.0 (lorikeet)"
VERSION_CODENAME=lory
ID=debian
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://www.parrotsec.org/community/"
BUG_REPORT_URL="https://gitlab.com/parrotsec/"

### How should we solve this?

NA

### What is the impact of not solving this?

NA

### Anything else?

NA

**Comment by ajmeese7** [comment]
This would be very useful to me, would love to see this addressed!
