### ISSUE TITLE
Removing PCP mapping fails (logspam with miniupnpd)

### ISSUE THREAD

**Issue by f1sherman** [tailscale/tailscale#1080]
**Describe the bug**

When removing a PCP mapping, it appears that the nonce does not match, resulting in the mapping failing to be removed. With miniupnpd installed, this results in repeated messages like this in syslog:

> Jan  1 18:34:05 router01 miniupnpd[18915]: Unauthorized to remove PCP mapping internal port 37846, protocol UDP

**To Reproduce**
1. tail -f syslog on the router
2. Wait for tailscale to try to remove a PCP mapping (or run `tailscale netcheck` to see it right away)

**Expected behavior**
PCP mapping is removed

**Version information:**
 - Device: PC
 - OS: Linux
 - OS version: Debian Buster
 - Tailscale version: 1.2.10

**Additional context**
I was able to trace the error message back to here in the miniupnpd source:
https://github.com/miniupnp/miniupnp/blob/c7cfe2c51aadc526fa73d5653795b141dbd3c8bf/miniupnpd/pcpserver.c#L1134

...which seems to suggest that the nonce doesn't match. With debugging enabled in miniupnpd, the related messages look like this:

```
Jan  1 17:05:31 router01 miniupnpd[1785]: PCP request received from 192.168.2.4:57869 60bytes
Jan  1 17:05:31 router01 miniupnpd[1785]: get_lan_for_peer(): 192.168.2.4:57869 found in LAN br0 192.168.2.1
Jan  1 17:05:31 router01 miniupnpd[1785]: PCP MAP: v2 Opcode specific information.
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP nonce:   #0115c83ac59680c2efe6ae31aa2
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP protocol:#01117
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP int port:#01157869
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP ext port:#0110
Jan  1 17:05:31 router01 miniupnpd[1785]: MAP Ext IP:  #011::ffff:0.0.0.0
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b2e0, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b4f0, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b70c, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: table_cb(0x7fff8b68b928, 0x7fff8b68c2f0) miniupnpd prerouting 1
Jan  1 17:05:31 router01 miniupnpd[1785]: timestamp entry found (57869, 17, 112341)
Jan  1 17:05:31 router01 miniupnpd[1785]: Unauthorized to remove PCP mapping internal port 57869, protocol UDP
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP 7637f2e52bf76b3edecd0e7c' is not a IGD pinhole
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP af3d46f9883ba950023862c9' is not a IGD pinhole
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP 42297152d72604385dc32ba5' is not a IGD pinhole
Jan  1 17:05:31 router01 miniupnpd[1785]: rule with label 'PCP MAP 867d30e083d14c26eaecc51f' is not a IGD pinhole
```

Interestingly I'm not seeing these from my Macbook, which is running version 1.2.4, probably because of this, which is fixed in 1.2.10:
https://github.com/tailscale/tailscale/issues/810

**Comment by bradfitz** [comment]
We only create a 1 second long mapping right now, just probing whether PCP is available, so perhaps the 1 second is firing and expiring its entry before we go to delete it.

**Comment by bradfitz** [comment]
Actually, I found a lighter way to query for PCP. Fix coming.
