### ISSUE TITLE
I hope the http port of DERP can be customized. We are prohibited from using port 80 in China.

### ISSUE THREAD

**Issue by lizhengaas** [tailscale/tailscale#10815]
### What are you trying to do?

I hope the http port of DERP can be customized. We are prohibited from using port 80 in China.

### How should we solve this?

I hope the http port of DERP can be customized. We are prohibited from using port 80 in China.

**Comment by DentonGentry** [comment]
`derper -http-port=81`

https://github.com/tailscale/tailscale/blob/6540d1f01800d03fa46d467fae777163b8ba3d0d/cmd/derper/derper.go#L43
