### ISSUE TITLE
The custom derp server is not working

### ISSUE THREAD

**Issue by ShCby** [tailscale/tailscale#10817]
### What is the issue?

I have successfully deployed the derp server on my server and can see the #900 derp latency for the device in the device detail.

But I can't ping any device.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.56.1

### Bug report

My computer

[tailscale-service-20240111T000201-1704902521.txt](https://github.com/tailscale/tailscale/files/13897313/tailscale-service-20240111T000201-1704902521.txt)

Another computer(Distance 1000 km+)

[tailscale-service-20240111T113002-1704943802.txt](https://github.com/tailscale/tailscale/files/13897373/tailscale-service-20240111T113002-1704943802.txt)

Another computer(Distance 500 km+)

[tailscale-service-20240111T000031-1704902431.txt](https://github.com/tailscale/tailscale/files/13897437/tailscale-service-20240111T000031-1704902431.txt)

**Comment by DentonGentry** [comment]
The template asks for a bug report because without it, there is nothing to go on. We can not do anything without knowing the tailnet.

**Comment by ShCby** [comment]
> The template asks for a bug report because without it, there is nothing to go on. We can not do anything without knowing the tailnet.

Hello, I have added the log.

**Comment by DentonGentry** [comment]
```
2024-01-11T12:13:04.139+08:00: open-conn-track: flow TCP (TCP 100.111.245.29:9236 => 10.10.10.10:5000) got RST by peer
2024-01-11T12:13:04.647+08:00: open-conn-track: flow TCP (TCP 100.111.245.29:9236 => 10.10.10.10:5000) got RST by peer
2024-01-11T12:13:05.154+08:00: open-conn-track: flow TCP (TCP 100.111.245.29:9236 => 10.10.10.10:5000) got RST by peer
```

Tailscale never sends a TCP reset. Something on the subnet router, likely a local firewall rule, is blocking transit and sending back a reset.

**Comment by ShCby** [comment]
> ```
> 2024-01-11T12:13:04.139+08:00: open-conn-track: flow TCP (TCP 100.111.245.29:9236 => 10.10.10.10:5000) got RST by peer
> 2024-01-11T12:13:04.647+08:00: open-conn-track: flow TCP (TCP 100.111.245.29:9236 => 10.10.10.10:5000) got RST by peer
> 2024-01-11T12:13:05.154+08:00: open-conn-track: flow TCP (TCP 100.111.245.29:9236 => 10.10.10.10:5000) got RST by peer
> ```
> 
> Tailscale never sends a TCP reset. Something on the subnet router, likely a local firewall rule, is blocking transit and sending back a reset.

The remote computer cannot access my subnet, but the ping does not time out, but other devices do time out when they ping other device.

Does the subnet's firewall policy affect the entire tailscale network?

**Comment by DentonGentry** [comment]
The subnet router is operating in tun mode? Not userspace-networking?
If so, then iptables or ufw rules in the subnet router's kernel will impact everything it routes, whether it comes via Tailscale or otherwise.

**Comment by ShCby** [comment]
> The subnet router is operating in tun mode? Not userspace-networking? If so, then iptables or ufw rules in the subnet router's kernel will impact everything it routes, whether it comes via Tailscale or otherwise.

I mean when A is connecting to B, but B is not hava subnet, it is still not connect success at this time.

**Comment by kelivel** [comment]
@ShCby Making this issue a support ticket is probably a better fit so we can gather more information from your tailnet. Reach out to us at http://www.tailscale.com/support and share this GitHub issue, and we can take it from there!
