### ISSUE TITLE
Last Tailscale package for Synology is not up to date

### ISSUE THREAD

**Issue by TheBlusky** [tailscale/tailscale#10819]
### What is the issue?

I have a Synology DS213j : 

| System Model | CPU Model | Synology Package Arch | SynoCommunity Arch | Generic Arch | Latest DSM
|-|-|-|-|-|-
| DS213j | Marvell Armada 370 88F6707 | Armada370 | armada370 | armv7 | 7.1.1-42962

Official latest package is only 1.38.4-700038004 : 

![HwXBdDlT3U](https://github.com/tailscale/tailscale/assets/441709/5b30103c-abe3-4d40-bb1e-6ec76212c1aa)

However, package for this configuration exists for latest version (1.56.1) here :
- https://pkgs.tailscale.com/stable/#spks
- https://pkgs.tailscale.com/stable/tailscale-armada370-1.56.1-7000056001-dsm7.spk

Would it be possible to update official repository with latest version ?

### OS

Synology

### OS version

7.1.1-42962 Update 6

### Tailscale version

1.38.4

**Comment by DentonGentry** [comment]
We wanted the [updated web interface](https://tailscale.com/kb/1325/device-web-interface) to be in the next release submitted to the Package Center. The updated web interface is in 1.56.x.

When we prepare to submit an update to the Package Center we wait a few weeks after the general release on other platforms and [Synology users using our builds](https://pkgs.tailscale.com/stable/#spks) to watch for signs of unexpected trouble or regression. We do not have a way to issue a quick-fix nor rollback, if a release makes it out with a regression then it will remain in the Package Center with that problem for an extended period of time.

Once submitted for testing, it takes about a month for the new release to appear in the Package Center. So we'd expect an update probably before the end of Q1 of 2024.

**Comment by TheBlusky** [comment]
I understand... but in the mean time, I have a red flag in Tailscale webui, with a security warning for current version.

I could install manually last tailscale version, but I'll need to uninstall my current one, and I'll loose all synology package update feature (even though, update should be managed by tailscale for next version ?).

Using community repository wouldn't be a solution for this ?

**Comment by drio** [comment]
> I could install manually last tailscale version,

What is the manual process to install tailscale in synology to ensure you get the latest version (and the auto update feature). 

```
$ curl -fsSL https://tailscale.com/install.sh | sh
Couldn't determine what kind of Linux is running.
You could try the static binaries at:
https://pkgs.tailscale.com/stable/#static

If you'd like us to support your system better, please email support@tailscale.com
and tell us what OS you're running.

Please include the following information we gathered from your system:

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux ds720 4.4.302+ #69057 SMP Mon Nov 13 14:19:30 CST 2023 x86_64 GNU/Linux synology_geminilake_720+

No /etc/os-release
```

**Comment by drio** [comment]
For the future:
I used [these instructions](https://tailscale.com/kb/1131/synology#manual-installation-steps) to install the package manually.
You basically download the [package for your machine](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures) and drop it while doing a manual install (Package center > Manual Install).
