### ISSUE TITLE
Windows remote desktop not working on local network after using Tailscale

### ISSUE THREAD

**Issue by niwazukihon** [tailscale/tailscale#10813]
### What is the issue?

To use windows remote desktop from a remote PC, I changed the firewall rules according to [this article](https://tailscale.com/kb/1095/secure-rdp-windows). Using Tailscale is fine --- I can connect to the PC from local or remote network with Tailscale running. However, now I cannot connect to that PC with Tailscale off, even if the two computers are on the same network.

Those firewall rules doesn't restrict local IP addresses. I checked that windows firewall allows RDP. It worked before using Tailscale.

### Steps to reproduce

1. Use Tailscale for windows remote desktop. It works.
2. Close Tailscale service on both computers.
3. Try to use windows remote desktop without Tailscale on the local network. Doesn't work.

### Are there any recent changes that introduced the issue?

No.

### OS

Windows

### OS version

Windows 11 Home 23H2 build 22631.3007. Windows 11 Pro 23H2 build 22631.3007.

### Tailscale version

1.56.1

### Other software

None.

### Bug report

BUG-79595307fc77b975dd60760c7a02b7f3cecaf2f59525673192e3b021666aeefb-20240111011447Z-08c1fa6461c4ef48

**Comment by hejin** [comment]
@niwazukihon hi man, have u found any solutions? I hit the same issue now and mine ts version is 1.74.0. I tried use freerdp client from my mac OS box and it just succeed to connect to the rdp servers in local network.

**Comment by niwazukihon** [comment]
One can just set the remote IP address in Windows firewall RDP rules to allow anywhere. Or you can reserve IP addresses for your devices in the router settings, and add those to the allowed remote IP addresses.

**Comment by erikz0** [comment]
This is an old issue, but I found that Tailscale had messed with my firewall settings and blocked connections on my LAN. One fix was to disable the private firewall, or add filewall rules allowing 3389:

Set-NetFirewallRule -DisplayGroup "Remote Desktop" -Profile Private -Enabled True
New-NetFirewallRule -DisplayName "Allow-RDP-Private" -Profile Private -Direction Inbound -Protocol TCP -LocalPort 3389 -Action Allow
New-NetFirewallRule -DisplayName "Allow-Ping-Private" -Protocol ICMPv4 -IcmpType 8 -Direction Inbound -Profile Private -Action Allow

I also realized I updated my mac and it disabled outbound local connections through the Windows App, which was also blocking me.
