### ISSUE TITLE
iPhone connectivity issues

### ISSUE THREAD

**Issue by purple-emily** [tailscale/tailscale#10821]
### What is the issue?

iPhone unable to access internet/Tailscale nodes until service is toggled on then off again. 

### Steps to reproduce

On my home WiFi. Tailscale set as connect on demand to everything except my home WiFi. 

Leave home. 
Connection works for 4 minutes.
Connection does not work.
Toggle Tailscale off/on.
Connection fixed. 

Note in this example I am a passenger in a car. 

### Are there any recent changes that introduced the issue?

No. I was advised by Andrea a fix was in the TestFlight build, so I have switched over. The issue still persists. 

### OS

iOS

### OS version

17.2.1

### Tailscale version

1.57.44

### Other software

Nothing

### Bug report

BUG-36799cb0c303eb03303c3cddf7f557882de9d9c19e657e0022895fff872714d7-20240111104610Z-416864e991d8e86d

**Comment by kelivel** [comment]
Hi there! We've freshly released stable version 1.58, which has Andreas fixed rolled in — can you upgrade and let us know if you're still seeing the same behavior? Please generate a new bug report if so, and add that in a reply here, and we'll take a closer look from there.

**Comment by MikeBookham** [comment]
I have the same issue, I originally noticed this the day I initially installed TailScale 24 Aug 2023 but just assumed this was normal operation and until today had been switching TS on only when needed. The issue remains and today I decided to have a look to see if there was a known issue because it is useless if it doesn't work correctly.

My device: iPhone 13 Mini
iOS version: 17.3

**Comment by kelivel** [comment]
Hi folks, can you please generate a bugreport as soon as you notice the issue and post those here?

**Comment by purple-emily** [comment]
> Hi folks, can you please generate a bugreport as soon as you notice the issue and post those here?

BUG-36799cb0c303eb03303c3cddf7f557882de9d9c19e657e0022895fff872714d7-20240209203418Z-d0534a65ff6893ec

**Comment by MikeBookham** [comment]
> BUG-36799cb0c303eb03303c3cddf7f557882de9d9c19e657e0022895fff872714d7-20240209203418Z-d0534a65ff6893ec

I have searched and cannot find any information on how to generate a bug report, please can you provide a link to the instructions?
Also how do I find what these BUG references quoted actually mean?

**Comment by ScuttleSE** [comment]
BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240213100312Z-76e6e884802c3ecb

**Comment by ScuttleSE** [comment]
BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240213155217Z-6f7dd11037491182

**Comment by ScuttleSE** [comment]
BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240214075018Z-6382015cbc9bb53c

**Comment by ScuttleSE** [comment]
BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240214100818Z-c4d87ff1c0cb7be0

**Comment by kelivel** [comment]
@MikeBookham In the Tailscale iOS app, tap on your avatar then tap Bug Report and copy the bug marker displayed there.

Each of the bug reports in this thread have reported DNS issues shortly before the report was generated.
* dns udp query: context deadline exceeded

This would be a different issue from the fix we shipped in 1.58. I'll add the correct labels and we'll take a closer look and will update this issue once we have more to share.

**Comment by cpetzel** [comment]
Here are two more big reports from my iOS device. All apps could not connect to anything until I turned off Tailscale. I used on demand magicdns.

BUG-67626cfbed7a9c89a6c3fe3d7acc7a14a36a59bcb4bfce772bac360f411352f6-20240304012814Z-ca6c31948388f6c7

BUG-67626cfbed7a9c89a6c3fe3d7acc7a14a36a59bcb4bfce772bac360f411352f6-20240304204541Z-cb2bfba2ad9b9961


iOS 17.4
TS 1.60

**Comment by ScuttleSE** [comment]
I tried the latest TestFlight version

BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240309115547Z-2a13bbd883cd26c4

Same issue. Right now Tailscale is completely unusable on iPhone, and I don't even know what the issue is...exc ept that Tailscale seems to die after a few minutes of phone inactivity

**Comment by bithack3r** [comment]
I still have the same iussue on iOS. App is stuck at 'Starting'.

Under Settings > VPN CONFIGURATIONS, it shows 'Connected' while stuck at 'Starting' on the app

Logging out, Deleting the app, Reauthenticating etc also didn't help.

iPhone 11 Pro Max (17.3.1) and iPhone 7 Plus (15.8.1)
Tailscale 1.60.1

BUG-75baacc0fe8ce2f634c24e69a4d25baa42742195212452446e3e840b54faa07a-20240313150021Z-0f44651bbc405986

**Comment by kelivel** [comment]
@bithack3r Hm, this sounds different from what others here are reporting. Can you write in to our support team at support@tailscale.com? We can help sort out what you're seeing there.

@ScuttleSE I suspect your issue could be related to a setting or firewall policing `tailscale0` on your DNS resolver node. When your phone switched from wifi to cellular I see the following error after a few moments:

> CreateEndpoint error for (iPhone) -> (DNS node): connection was refused 

Can you check logs on your resolver for more clues? If you'd like to share more information privately, please drop a line at support@tailscale.com. 

@purple-emily and all others experiencing issues transitioning from wifi to cellular: we'll be releasing stable version 1.62 soon with a DNS improvement that may help here. Please let us know if this new version resolves what you were seeing previously. Thank you!

**Comment by purple-emily** [comment]
Hey @kelivel awesome!

I’m also getting the stuck on starting bug recently but uninstalling and reinstalling fixes it.

**Comment by ScuttleSE** [comment]
> @ScuttleSE I suspect your issue could be related to a setting or firewall policing `tailscale0` on your DNS resolver node. When your phone switched from wifi to cellular I see the following error after a few moments:
> 

I am not quite sure which DNS you are reffering to here. In tailscale I have two DNS-servers defined; 192.168.103.11 and 192.168.103.10. On the exit-node I am using, which has IP 192.168.0.46, those two dns-servers are 100% available. If the tailscale0 interface is using the default gateway, which is 192.168.0.1, it should have not problems reaching the DNS-servers. There are no blocks in my firewall for that.

I have added an explicit route for the 192.168.103.0/24 network incase the tailscale network interface doesn't understand the default gateway somehow... I'll update if there are any changes.

**Comment by dsymonds** [comment]
I’ve been hitting this a lot for a while. Here’s a recent bug report:

BUG-346b2a7e3229fe3959e1e4796e0e17ec72d9f5e3cb2c8778b6dce444ef446782-20240313233518Z-ebcbac522656031b

**Comment by cpetzel** [comment]
I recently updated Tailscale iOS app to 1.62.0, which claims to address the dns issue when switching networks, but I am still seeing this issue when switching between cellular and WiFi. 

BUG-67626cfbed7a9c89a6c3fe3d7acc7a14a36a59bcb4bfce772bac360f411352f6-20240315203052Z-5988cf39599b6b1e

**Comment by ScuttleSE** [comment]
BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240319120331Z-246c89d6c82a9ca6

No change after adding a static route to my DNS-network

**Comment by ScuttleSE** [comment]
Yesterday I took the opportunity to save a few more debug logs

BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240322104557Z-0533bfad26514204

BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240322105318Z-e84dbb0889d2616a

This immediately after the previous one, after I disconnected and reconnected to tailscale and everything worked: After BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240322105342Z-cd5817991505fcf3

BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240322105342Z-cd5817991505fcf3

Again, immediately after the previous one: After BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240322105823Z-e29dd70ccc8a3a41


So, in essence, right now tailscale is unusable on my iPhone....

**Comment by ScuttleSE** [comment]
Me too...is there anything happening here, or should I just abandon Tailscale on iOS?

**Comment by waihankan** [comment]
Having the same issue. Can someone please take a look into it? BUG-5c851465f4274b1175713f6f5122c574dc66d4d795ac4b1787bf7b89fe5a8076-20240714074909Z-5d243f30600fb94d

**Comment by wingcomm** [comment]
> Having the same issue. Can someone please take a look into it? BUG-5c851465f4274b1175713f6f5122c574dc66d4d795ac4b1787bf7b89fe5a8076-20240714074909Z-5d243f30600fb94d

Are you using 1.68.2? I have been seeing improvements with this version.

**Comment by waihankan** [comment]
@wingcomm yes i'm using 1.68.2

**Comment by ScuttleSE** [comment]
Every time there is a comment in this issue I give Tailscale another chance. This time with 1.70.0

Same crap

BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240719064551Z-b04477fe2eea29cc

Is anyone actually looking into this, or am I just screaming into a void?

**Comment by agottardo** [comment]
Sorry for the frustration. We have been actively fixing many DNS issues related to network transitions, you can see that in the changelog. It is just a very hard problem, with many hard-to-hit edge cases, and it is often impossible for engineers to repro reliably, so coming up with a good fix that fixes the problem for _everyone_ is hard. @barnstar is slated to look into https://github.com/tailscale/tailscale/issues/12352 next week, which appears to be the same issue as what you're experiencing (based on your diagnostics it appears you're also using DNS over HTTPS).

**Comment by ScuttleSE** [comment]
> based on your diagnostics it appears you're also using DNS over HTTPS.

Unless it is Tailscale that is using DNS over HTTPS; no I am not...

**Comment by ScuttleSE** [comment]
BUG-2a4af81dad246800c7feb46fc929ffe302b5bfeeea4f4a2e37e451233fa2cbc3-20240722094358Z-a22233c2efad3c70

**Comment by agottardo** [comment]
@ScuttleSE Diagnostics from your tailnet and your client indicate there are no network transitions happening. The issue you're experiencing is not the issue originally mentioned in this thread. The client is hitting timeouts reaching the DNS server you specified on your tailnet. Support will reach out to you privately with troubleshooting steps as it appears a misconfiguration is causing this and I don't want to publish details about your tailnet configuration in a public thread.
