### ISSUE TITLE
FR:  add server status to phone app.  Similar to web page

### ISSUE THREAD

**Issue by stuffa** [tailscale/tailscale#10853]
### What are you trying to do?

See if server links are up and running. And since when from the app

### How should we solve this?

Add the status either on the list or when it is pressed

### What is the impact of not solving this?

Users have to leave the app an login via browser to see if a service is running. For me I have other issues and sometimes the server is not available because the power is off.  Adding this will enhance the usefulness of the app

**Comment by stuffa** [comment]
If I can get access to the source I would be happy to make the change

**Comment by DentonGentry** [comment]
Are you referring to the iOS or Android app, or something else?

**Comment by stuffa** [comment]
In particular i am referring to the android app, But I assume that the ios
app is the same


Cheers

--------------------------------------------------------
Chris Martin
m: +61 419 812 371
e: ***@***.***
--------------------------------------------------------

**Comment by stuffa** [comment]
I just found the source on github.  I'll start working in a patch next
weekend

Cheers

--------------------------------------------------------
Chris Martin
m: +61 419 812 371
e: ***@***.***
--------------------------------------------------------

**Comment by DentonGentry** [comment]
> Users have to leave the app an login via browser to see if a service is running. 

Generally the persistent notification will provide this indication. I don't know what the browser would connect to in order to determine this.

**Comment by aalokkamble** [comment]
> If I can get access to the source I would be happy to make the change
you can do that in following file in 
cmd/tailscale/ui.go repo: https://github.com/tailscale/tailscale-android

**Comment by agottardo** [comment]
Fixed in the new Android app, currently in beta.
