### ISSUE TITLE
macOS 14.2.1 Sonoma When quit Tailscale it keeps open in background

### ISSUE THREAD

**Issue by tonstat** [tailscale/tailscale#10855]
### What is the issue?

On Sonoma, when I quit tailscale (top bar menu > quit) tailscale quits and is out of top bar but when looking on other device, it still is running.

### OS

macOS

### OS version

14.2.1

### Tailscale version

1.56.1 (App Store)

**Comment by agottardo** [comment]
Try updating the app to v1.58.0, released yesterday. We fixed a number of issues related to app and tunnel lifecycle.
