### ISSUE TITLE
FR: AD Group synchronisation

### ISSUE THREAD

**Issue by admrobCToken** [tailscale/tailscale#10859]
### What are you trying to do?

In order to simplify any reporting/recertification of access, we try to ensure we have a single source of group definitions in Entra ID (Active Directory) that we use for access control and synchronise with any application access. This would also simplify any support organisation as Entra ID access control would be all that is required rather than special access to a config file, which some in 1st level support couldn't manage.

### How should we solve this?

Link Entra ID groups and users and sync them into the configuration file.

### What is the impact of not solving this?

Enterprises look for these sort of features. My guess is that you'll have a harder time getting adapted by enterprises with config file only solution.

**Comment by DentonGentry** [comment]
Is there something needed which https://tailscale.com/kb/1249/sso-entra-id-scim does not provide?

**Comment by robCToken** [comment]
Embarrasing. I was just looking at my config and I didn't have SCIM as an option in my config (still don't). I've raised a ticket with support to see how I can get that working with the IdP. The guide states that I should enable provisioning under user management, no such option. Perhaps integration has changed or I need to make some adjustments.
But to answer your question - that's exactly what I was looking for.

**Comment by DentonGentry** [comment]
> I've raised a ticket with support to see how I can get that working with the IdP.

I think we'll address the remaining items in the support ticket.
