### ISSUE TITLE
Support MIPS64 Binary directly in static Binary packages of Tailscale.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1085]
Tailscale should support the MIPS64 binary directly.

e.g., EdgeRouter 6P from Ubiquiti (SKU:  ER-6P) has a MIPS64 processor.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2mqs1)

**Comment by gabefair** [comment]
Please see #735. 
Many people (7.1% of global WLAN market) have MIPS routers and could benefit from official instructions on adding tailscale to run directly on that hardware.

In addition these devices make for very poor source-build machines due to their limited resources. So binaries are the only option for many users.

**Comment by bradfitz** [comment]
> In addition these devices make for very poor source-build machines due to their limited resources. So binaries are the only option for many users.

Oh, I wasn't proposing in email to build directly on the target machine. They are indeed too resource and environment constrained for that.

The Go toolchain supports cross-compilation by default, using only environment variables, so you can build the linux/mips64 binaries from windows/amd64 or openbsd/386, etc.

e.g.:

```
bradfitz@tsdev:~/src/tailscale.com$ GOOS=linux GOARCH=mips64 go install ./cmd/tailscale{,d}
bradfitz@tsdev:~/src/tailscale.com$ file ~/go/bin/linux_mips64/*
/home/bradfitz/go/bin/linux_mips64/tailscale:  ELF 64-bit MSB executable, MIPS, MIPS-III version 1 (SYSV), statically linked, Go BuildID=jMl8YC_NaVLPWIptb13s/lllJY6tspElMAeNg-83O/K2iVog1oMJs8CrvftVfv/9yofkXe6LQW_Wf5WnYh0, not stripped
/home/bradfitz/go/bin/linux_mips64/tailscaled: ELF 64-bit MSB executable, MIPS, MIPS-III version 1 (SYSV), statically linked, Go BuildID=BDIgX5LuVoR1zz1HyhTp/CxvG9mV24K-PI2wMbkE_/db05-GQsfsqUd52Yfsgk/t97Sf35XL_gO01bD7LCw, not stripped
```

**Comment by DentonGentry** [comment]
Builder change submitted, we expect the next step of packages built to include MIPS64 big-endian.

**Comment by danderson** [comment]
Did you check the architecture names used in deb and rpm distros? We default to using the Go arch name, but it often varies in the two package ecosystems.

**Comment by DentonGentry** [comment]
May have gotten lucky, both say mips64 and some searching looks like both deb and RPM expect it to be mips64.

```
$ dpkg -I ./tailscale.deb
 new Debian package, version 2.0.
 size 13628858 bytes: control archive=915 bytes.
      24 bytes,     1 lines      conffiles
     365 bytes,    12 lines      control
     243 bytes,     4 lines      md5sums
     581 bytes,    13 lines   *  postinst
     463 bytes,    17 lines   *  postrm               #!/bin/sh
     121 bytes,     5 lines   *  prerm                #!/bin/sh
 Package: tailscale
 Version: 1.11.3
 Section: net
 Priority: extra
 Architecture: mips64
 Maintainer: Tailscale Inc <info@tailscale.com>
 Installed-Size: 27807
 Replaces: tailscale-relay
 Depends: iptables, iproute2
 Conflicts: tailscale-relay
 Homepage: https://www.tailscale.com
 Description: The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO
```

```
$ rpm -qip ./tailscale.rpm
Name        : tailscale
Epoch       : 0
Version     : 1.11.3
Release     : 1
Architecture: mips64
Install Date: (not installed)
Group       : Network
Size        : 28475253
License     : MIT
Signature   : (none)
Source RPM  : tailscale-1.11.3-1.src.rpm
Build Date  : Sat Jun 26 09:18:45 2021
Build Host  : ubuntu
Relocations : (not relocatable)
Packager    : Tailscale Inc <info@tailscale.com>
Vendor      :
URL         : https://www.tailscale.com
Summary     : The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO
Description :
The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO
```

**Comment by bradfitz** [comment]
Wow, the Edge Router 6P is actually a big endian MISP64 it seems, per:

https://openwrt.org/toh/ubiquiti/edgerouter_6p

That's pretty weird. In general, MIPS64(big endian) is rarely want anybody actually wants.

After x86 everybody only wanted to buy little endian so PPC64 went little endian (or boot-time selectable, IIRC), likewise mips64le. Debian doesn't even support big-endian PPC64 or MIPS64:

https://www.debian.org/releases/stable/

If we're going to support `mips64` we should also support `GOARCH=mips64el` (which Debian also calls `mips64el`:

> Given most MIPS machines have 64-bit CPUs, a debian-mips64el port is currently in development and might be released with Debian GNU/Linux 9.

from https://www.debian.org/ports/mips/)

**Comment by DentonGentry** [comment]
The current Tailscale 1.12.x release now has MIPS64 big and little endian static binaries: https://pkgs.tailscale.com/stable/#static
