### ISSUE TITLE
Tailscale GUI not visible for Windows 11

### ISSUE THREAD

**Issue by bmbmjmdm** [tailscale/tailscale#10867]
### What is the issue?

I ran the tailscale setup that I downloaded from the offical website

tailscale-setup-1.56.1.exe

I was taken to the tailscale website and setup my account. Afterwards, I noticed I could not find the tailscale GUI anywhere.

I searched my taskbar and icon tray, but there is nothing. I tried stopping the services from task manager and restarting it, but still nothing. I tried rebooting, nothing. I tried uninstalling and reinstalling, nothing. I tried running with admin privelidges, as well as installing with admin privelidges, nothing. 

Please advise how to view the GUI on Windows 11. 

![tailscale](https://github.com/tailscale/tailscale/assets/14958305/9612c712-1843-4d5e-a51f-afdfb4e5c81c)

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.56.1

**Comment by guydingmike** [comment]
I have the same problem for **Windows 10**.  In my case it was not a new account setup.  I upgraded to tailscale-setup-1.56.1.exe but there is no GUI available.  I also did a reboot and still no GUI available in the task bar/notification tray.

**Comment by rapus95** [comment]
For me, it is behind that triangle
![image](https://github.com/tailscale/tailscale/assets/5960902/a9f410d0-ae67-42f6-aa36-5cb5800e9eb6)
Given that I don't see the triangle in your image @bmbmjmdm, could it be that some of your applications just won't show up since you disabled that triangle?

**Comment by bmbmjmdm** [comment]
Ah yup, it looks like on Windows 11 you have to go into the System Tray settings and manually enable Tailscale to be visible
