### ISSUE TITLE
Tailscale 1.56 on androidTV gets stuck in About menu

### ISSUE THREAD

**Issue by jbd7** [tailscale/tailscale#10875]
### What is the issue?

One cannot exit the About menu in Android TV once it is shown.

On an android phone, one can tap outside the About content box (made of 3 lines: About title, Version number, and OS licenses). But on android TV, the back button doesn't close that menu, seemingly nothing else does, but depowering the android TV stick physically. 

### Steps to reproduce

- On android TV, launch Tailscale app
- with the TV remote, navigate to the 3dots menu and open
- navigate to the bottom of the menu and open About section
- observe About modal and try to close it with all buttons on the remote

### OS

Android

### OS version

Android TV 12, up to date at time of opening the issue. 

### Tailscale version

1.56

### Bug report

Ran it, but cannot copy it from the clipboard of android TV in an easy way

**Comment by kelivel** [comment]
Hi @jbd7, thanks for reporting! It's likely the same cause as this existing open issue— 

* https://github.com/tailscale/tailscale/issues/7211

I'll close this one to keep progress in one place, and I'd encourage you to follow #7211 issue for updates. 

> the back button doesn't close that menu, seemingly nothing else does, but depowering the android TV stick physically.

In my testing, forcibly stopping the Tailscale app (Settings → Apps → Tailscale → Force stop) is a little faster than rebooting the device and could be a better workaround until we get this addressed.
