### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by BirdInFire** [tailscale/tailscale#10889]
### What is the issue?

i do try to update no update, so I do try the integrated : 
sudo tailscale update : 

This will update Tailscale from 1.56.1 to 1.58.0. Continue? [y/n] y
Last metadata expiration check performed 0:00:20 ago on Fri, Jan 19, 2024 15:49:57.
No match for parameter: tailscale-1.58.0-1
Error : Unable to find a match: tailscale-1.58.0-1

### Steps to reproduce

Try to update on fedora 39

### Are there any recent changes that introduced the issue?

Last update

### OS

Linux

### OS version

Fedora 39

### Tailscale version

1.58.0

**Comment by dennisschoepf** [comment]
Same problem for me on Fedora 39. Cannot start tailscale with `tailscale up` due to not having the latest version. I am getting the same error message as above.

**Comment by dwyart** [comment]
```Note: Rollout of 1.58.0 paused on 21-Jan-2024 while we investigate reports of a regression with portmapping.```
(from https://tailscale.com/changelog)

**Comment by BirdInFire** [comment]
> ```Note: Rollout of 1.58.0 paused on 21-Jan-2024 while we investigate reports of a regression with portmapping.```
> 
> (from https://tailscale.com/changelog)
> 
> 

The issue date from before the pause so the issue remains

**Comment by dwyart** [comment]
I could upgrade a Debian system to 1.58.0 on the 19th, while on RH-compatible, I never saw the update coming. So I guess the "pause" started earlier than what is stated in the Changelog.

Also note I just gave a quick hint, I have no link with Tailscale itself, so no need to reply so harshly.

**Comment by BirdInFire** [comment]
> I could upgrade a Debian system to 1.58.0 on the 19th, while on RH-compatible, I never saw the update coming. So I guess the "pause" started earlier than what is stated in the Changelog.
> 
> 
> 
> Also note I just gave a quick hint, I have no link with Tailscale itself, so no need to reply so harshly.

English is not my native languages if you have understood my tone harshly I do excuse myself it was not my intention

**Comment by dwyart** [comment]
Version 1.58.2 is out now and should fix the issue.

**Comment by dwyart** [comment]
Yes, sorry, I replied a bit quick, 1.58.2 is not yet in the official RPM-based repo (but it in DEB-based one). I guess this is now a matter of hours, as the pause has been lifted.

**Comment by dwyart** [comment]
Issue confirmed here https://github.com/tailscale/tailscale/issues/10947

**Comment by BirdInFire** [comment]
> Issue confirmed here https://github.com/tailscale/tailscale/issues/10947

Thanks for the information since I do work I didn't noticed I will not reopen to avoid duplicate issue
