### ISSUE TITLE
[Perfomance] Relatively high memory usage because many processes are spawned

### ISSUE THREAD

**Issue by paule96** [tailscale/tailscale#10881]
### What is the issue?

I have currently installed the tailscale extension of my router (RutX50 Teltonika) and noticed a weird behavior. Tailscale alone has a relatively low memory usage but it starts itself like 10 times. So alone it has something like 14mb of RAM usage

<img width="1006" alt="image" src="https://github.com/tailscale/tailscale/assets/11291885/458b0b93-213d-44a3-a8e3-9662a1035d30">

but because of that issue it has around 12 times the ram usage.

That's a problem for routers because they are usually low on RAM. (I have for example a bit over 200MB of usable RAM)

It would be nice to to have a single process with 14mb :) 

### Steps to reproduce

Just install the tailscale package and configure it.

### OS

Other

### OS version

OpenWrt 21.02.0 arm_cortex-a7_neon-vfpv4

### Tailscale version

1.50.0

**Comment by bradfitz** [comment]
> but because of that issue it has around 12 times the ram usage.

I don't believe that is accurate.

What you're seeing are threads. But they all share the same memory.
