### ISSUE TITLE
Completly ignore my exit node / client dns

### ISSUE THREAD

**Issue by BirdInFire** [tailscale/tailscale#10890]
### What is the issue?

When I use tailscale my filtered dns of my exit node (who filter dns) and the same filter on my device is totally ignored.

### Steps to reproduce

Add a dns filter on the exit node.
Use the exit node with tailscale dns ON.
The website locked is accessible from time to time even if the dns return nxdomain witch mean that a resolver resolve it somewhere in the loop.

### OS

macOS, iOS

### OS version

IOS 17, MacOs 13

**Comment by kelivel** [comment]
Hi @BirdInFire, we'll need more information in order to troubleshoot. Can you generate a bugreport from the affected devices immediately after the issue occurs?

**Comment by BirdInFire** [comment]
> Hi @BirdInFire, we'll need more information in order to troubleshoot. Can you generate a bugreport from the affected devices immediately after the issue occurs? 

Will do asap

**Comment by BirdInFire** [comment]
After many test I found out it was a local issue based on dns fallback that was triggered systematically I close if someone have the same issue I can reopen later
