### ISSUE TITLE
MAS version of Tailscale 1.58.0 fails to update on macOS 10.15.7 Catalina

### ISSUE THREAD

**Issue by quartermarsh** [tailscale/tailscale#10912]
### What is the issue?

Tailscale won't update to 1.58.0 on macOS Catalina

### Steps to reproduce

Attempt to update Tailscale to 1.58.0 on macOS Catalina vis Mac App Store

### Are there any recent changes that introduced the issue?

Tailscale update to 1.58.0 released

### OS

macOS

### OS version

10.15.7

### Tailscale version

1.56.1

### Other software

n/a

**Comment by quartermarsh** [comment]
Sorry folks, I checked the issues and didn't see a previous report. Obviously you're on it. My thanks!

**Comment by quartermarsh** [comment]
btw @barnstar I tried with TS running, disconnected, and closed. No method worked.

**Comment by quartermarsh** [comment]
BUG-4aacb6c2ee811eb76af1f0d09b8426b267e98b6c06b30eb7ce8e18b6da8985f3-20240120231519Z-160da95c4f98c2cb

**Comment by barnstar** [comment]
Can you provide more detail on exactly what error you're seeing?   We do officially support 10.15 and I have verified that fresh installs on 10.15.7 are working and the client functions as expected.   Older AppStore clients may have trouble upgrading apps which host VPN extensions.   Before upgrading, double check that Tailscale is halted in your system VPN settings.   You may need to go so far as to disable VPN on demand in the system VPN settings (for the Tailscale configuration) and manually delete it - depending on what version of Tailscale you're upgrading from.   You should be prompted to recreate the config when you restart the client.  Failing that, you can also try a fresh install.

If the AppStore continues to give you problems, we do also offer a directly downloadable version of the macOS Tailscale client here:  https://pkgs.tailscale.com/stable/#macos .  You will need to uninstall the AppStore version first however.

**Comment by bkonicek** [comment]
@quartermarsh I was having the same problem on MacOS 11.7.10 - I clicked the "Update" button, it showed the progress wheel, and then went back to showing "Update" instead of "Open". Tried quitting Tailscale, restarting my computer, etc but it wouldn't work. I got it working my uninstalling Tailscale and reinstalling through MAS and it installed 1.58.0 finally, so you might give that a try.

**Comment by quartermarsh** [comment]
Hi Jonathan,

Thanks for the tips. This is the first time I’ve had to disable Tailscale from network settings in order for an update to proceed successfully. I had to disable 'connect on demand' and disconnect tailscale and apply the changes before attempting the update, which was then successful. Up to now, for all previous updates, Tailscale has updated with no issue. Such is life running servers on outdated os’es - workarounds are the order of the day.
Thanks again,

Mark

On Jan 22, 2024, at 6:44 AM, Jonathan Nobels ***@***.***> wrote:


Can you provide more detail on exactly what error you're seeing? We do officially support 10.15 and I have verified that fresh installs on 10.15.7 are working and the client functions as expected. Older AppStore clients may have trouble upgrading apps which host VPN extensions. Before upgrading, double check that Tailscale is halted in your system VPN settings. You may need to go so far as to disable VPN on demand in the system VPN settings (for the Tailscale configuration) and manually delete it - depending on what version of Tailscale you're upgrading from. You should be prompted to recreate the config when you restart the client. Failing that, you can also try a fresh install.

If the AppStore continues to give you problems, we do also offer a directly downloadable version of the macOS Tailscale client here: https://pkgs.tailscale.com/stable/#macos . You will need to uninstall the AppStore version first however.

**Comment by quartermarsh** [comment]
@barnstar I guess this could be closed, with my thanks.
