### ISSUE TITLE
Funnel not working after ACL changes

### ISSUE THREAD

**Issue by bartbutenaers** [tailscale/tailscale#10939]
### What is the issue?

I had setup a tailnet containing agents on both Android smartphones and a Raspberry Pi, and an extra funnel to port xxxx of my Raspberry Pi.   Everything was running fine.

Then I wanted to limit my traffic, to allow it only between the smartphones and the raspberry, but no traffic between the smartphones.   So I updated my ACL.  However as side effect, from then on my funnel was not working anymore. 

So I removed my changes from the old ACL, but the funnel is still not working.  I assume the old ACL is still being used under the cover, but I am not sure because I am quite new to Tailscale...

### Steps to reproduce

0. I had setup a funnel to my Raspberry port xxxx.
1. I added a tag "client" to every smartphone and a tag "server" to the raspberry.
2. I added this in my ACL:
   ```
   "acls": [
      {"action": "accept", "src": ["tag:client"], "dst": ["tag:server:*"]},
      {"action": "accept", "src": ["tag:server"], "dst": ["tag:client:*"]},
   ]
   ```
3. Then my funnel stops working from a device not running an agent.  On devices with an active agent, I can still access it.
4. I revert my ACL to this:
   ```
   "acls": [
        {"action": "accept", "src": ["*"], "dst": ["*:*"]},
   ]
   ```
5. I have still the same problem as in step 3.

BTW If you would have also tips about how I could allow the funnel servers to send requests in the ACL, that would be very appreciated!

### Are there any recent changes that introduced the issue?

I only did change the ACL and reverted that change.

### OS

Linux

### OS version

Debian GNU/Linux 12 (bookworm)

### Tailscale version

1.58.0

### Other software

Node-RED

### Bug report

BUG-3882ad0fcdee85e9c8415037487dcaef863752167ddaaad1e3d50c120199edd8-20240123230645Z-514b891c52d40ca9

**Comment by bartbutenaers** [comment]
Dear,

Not sure if this is a Tailscale issue, or just me not using Tailscale correctly...

I have reduced my access control to the bare minimum that I need:
```
"acls": [
   // Only client to server requests allowed
   {"action": "accept", "src": ["tag:client"], "dst": ["tag:server:*"]},
],
```

Seems I can solve the problem like this:
1. I still had a tag "server" on my raspberry machine. 
2. I did `sudo tailscale logout` on my raspberry in order to be able to remove that tag.
3. Next I did `sudo tailscale up` and `sudo tailscale funnel --bg xxxx`
4. Then my funnel works fine again.

But as soon as I add the label "server" again to my raspberry machine, the tunnel is again not accessible anymore.

So I assume the ACL list is updated correctly, but that the label on my machine makes the funnel unaccessible from the outside world?   It probably has to do something with this part of the documentation:

> Once a device has been tagged, it loses the access permissions of the human user who tagged it, and acquires any access permissions granted to its tags.

Not sure if I understand this correctly.  Because the funnel is arriving in my tailnet via a proxy on the funnel servers.  But I cannot apply a tag to that proxy, so not sure how I can allow this funnel traffic in my ACL.  It is not clear to me if I can add a rule to my ACL to allow traffic from a funnel to a tagged machine?

And the "funnel" label keeps being green in all circumstances:
![image](https://github.com/tailscale/tailscale/assets/14224149/164bce1c-18bf-4544-b0d5-52a3b60bd557)
Not sure whether it is technically possible, but it might be much more self explaining if this label was e.g. orange if the funnel is not accessible from the outside world ?

Thanks for reading!!

**Comment by kelivel** [comment]
Your tailnet uses the [default funnel attribute](https://tailscale.com/kb/1223/funnel#tailnet-policy-file-requirement) which permits funnel only on un-tagged devices.

Edit the attribute to include your tag(s), e.g.: 

```
"nodeAttrs": [
	{
		"target": ["autogroup:member", "tag:server"],
		"attr":   ["funnel"],
	},
],
```

**Comment by bartbutenaers** [comment]
Hi @kelivel,

So the "autogroup:member" refers to ***all*** devices that have been added to the tailnet, ***except*** for the tagged devices.  So if you tag a device (e.g. with the tag "server") you need to tell Tailscale that the "funnel" attribute needs to be added to all devices with that particular tag.

This works fine.  Thanks a lot for your valuable feedback!!!

Bart
