### ISSUE TITLE
Installer script is not working on Ubuntu 23.10 mantic

### ISSUE THREAD

**Issue by eddykaya** [tailscale/tailscale#10933]
### What is the issue?

When running `curl -fsSL https://tailscale.com/install.sh | sh` on Ubuntu 23.10, the installer fails on updating apt sources with "The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 458CA832957F5868" error.

### Steps to reproduce

Run  `curl -fsSL https://tailscale.com/install.sh | sh` on Ubuntu 23.10

### OS

Linux

### OS version

23.10

**Comment by DentonGentry** [comment]
If you use these instructions, does it work?
https://pkgs.tailscale.com/stable/#ubuntu-minotaur

**Comment by eddykaya** [comment]
> If you use these instructions, does it work? https://pkgs.tailscale.com/stable/#ubuntu-minotaur

I also tried this, without success, it leads to the same error as mentioned above.

**Comment by eddykaya** [comment]
Any news on this issue?

**Comment by eddykaya** [comment]
For whatever reason, this command does not download a valid gpg key:

`curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/impish.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null`

Instead, I have to execute the curl command as sudo to make it work:

`sudo curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/impish.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null`
