### ISSUE TITLE
Port serve not working on raspberry pi 

### ISSUE THREAD

**Issue by Sean-Morrison** [tailscale/tailscale#10931]
### What is the issue?

On raspberry pi bullseye with Tailscale 1.56.1 serving any port but 80 is not working. I can serve 80 to any port, but serving any other port doesn’t work, nor does it give any errors. I can serve these ports on a Mac (with Tailscale 1.58.0) on the same network, so it appears to only be an issue with either the version or with the raspberry pi. 

### OS

Linux

### OS version

Raspbian bullseye

### Tailscale version

1.56.1

### Bug report

BUG-763057e114075897808c5175d51f0bce637e5a2cd98e57b7992d5976db0f11db-20240123025340Z-63e00429365bdb15

**Comment by bradfitz** [comment]
Do you have a firewall running on your Pi? What's `sudo iptables -L -n` say?

**Comment by Sean-Morrison** [comment]
Below is the output (with X for the replaced IP address)

> Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ts-input   all  --  0.0.0.0/0            0.0.0.0/0

> Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ts-forward  all  --  0.0.0.0/0            0.0.0.0/0

>Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

> Chain ts-forward (1 references)
target     prot opt source               destination
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK xset 0x40000/0xff0000
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            mark match 0x40000/0xff0000
DROP       all  --  X.X.X.X/10        0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

> Chain ts-input (1 references)
target     prot opt source               destination
ACCEPT     all  --  X.X.X.X       0.0.0.0/0
RETURN     all  --  X.X.X.X/23      0.0.0.0/0
DROP       all  --  X.X.X.X/10        0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:41641

**Comment by bradfitz** [comment]
That looks fine.

> serving any port but 80 is not working. I can serve 80 to any port

How are you serving port 80? What commands did you run?

**Comment by Sean-Morrison** [comment]
Either `tailscale serve --http=80 localhost:80` or `tailscale serve --bg --http=2345 localhost:80` but if I replace the last 80 with any of the other ports that I need to serve, I get a "This page is not working". If I do `tailscale serve 2345` it seems to serve port 80  rather than port 2345.

**Comment by Sean-Morrison** [comment]
It is a webpage that is port-forwarded through ssh. I have some remote development servers that are behind firewalls and can only be accessed through a tunnel. I can view the page locally using my internal X.X.X.X:2345 with no issues, but when I try to access it with the Tailscale IP or URL it is unable to load the page (and gives that page - HTTP ERROR 502). It appears that the port is not being forwarded through Tailscale even though Tailscale message says the proxy is in place for that port.

**Comment by bradfitz** [comment]
Oh, so it didn't literally say "This page is not working". You got a 502 error.

What's `tailscale serve status` say when it's in that 502-serving state?

**Comment by Sean-Morrison** [comment]
Yes, sorry the full message was on the Chrome window was:
> This page isn’t working
\<name\>.\<domain\>.ts.net is currently unable to handle this request.
HTTP ERROR 502

`tailscale serve status` gives the message below while that error is in that state
> http://\<name\>:2345 (tailnet only)
http://\<name\>.\<domain\>.ts.net:2345 (tailnet only)
|-- / proxy http://127.0.0.1:2345

**Comment by bradfitz** [comment]
And when you `curl http://127.0.0.1:2345/` does it work?

**Comment by Sean-Morrison** [comment]
No, if I do `curl http://127.0.0.1:2345/` I get 

> curl: (7) Failed to connect to 127.0.0.1 port 2345 after 0 ms: Connection refused

**Comment by bradfitz** [comment]
That's the problem then.

Tailscale is configured to proxy to `http://127.0.0.1:2345` but that nothing is listening on and serving that port, so Tailscale says 502 (failed to make a connection to the backend).

**Comment by Sean-Morrison** [comment]
Thank you for the help, I had to change my SSH config for port forwarding, which solved it.
Thanks
