### ISSUE TITLE
Cannot enable "Start at login" using macOS client 

### ISSUE THREAD

**Issue by nullstyle** [tailscale/tailscale#10932]
### What is the issue?

I cannot enable "Start on Login" functionality.  Clicking the menu option results in no overt error message, but the items is not checked and no Login Item notification is shown to me from macOS.  I get the following in my console.app:

```
effectiveItemDisposition: record not found: appURL=/Applications/Tailscale.app, url=/Contents/Library/LoginItems/TailscaleLoginItemHelper.app, type=login item, config=(null)
```

### Steps to reproduce

Install, Login, then try to enable "Start at Login"

### Are there any recent changes that introduced the issue?

No, this is a newly purchased and setup machine

### OS

macOS

### OS version

Sonoma 14.3

### Tailscale version

1.58.0

**Comment by agottardo** [comment]
This was caused by a recent refactoring in which we adopted the new SMAppService API from Apple. It appears to be partially broken for some users. We have identified the issue and will push a fix to mitigate it.
