### ISSUE TITLE
Update AUR installation documentation. 

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1093]
The installation instructions for Arch Linux says to install Tailscale
from AUR.

However, the Tailscale package has been added to the community
repository, so you can just install it directly using pacman:

$ pacman -S tailscale

Also, the link on documentation run into 404 - Page Not Found.

![image](https://user-images.githubusercontent.com/75628398/103916046-f72d5280-50d9-11eb-9767-1ebbf0693eed.png)

**Comment by bradfitz** [comment]
@darshinimashar, you want to handle this one?

**Comment by darshinimashar** [comment]
sure

—
Darshini Mashar | Customer Engineer | Tailscale | @tailscale

--- original message ---
On January 7, 2021, 11:20 AM EST notifications@github.com wrote:



@darshinimashar, you want to handle this one?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by bradfitz** [comment]
Be sure to link to https://wiki.archlinux.org/index.php/Tailscale too.

**Comment by darshinimashar** [comment]
I will update that tomorrow because I already updated the step there.


Thank you for your suggession.

—
Darshini Mashar | Customer Engineer | Tailscale | @tailscale

--- original message ---
On January 7, 2021, 11:00 PM EST notifications@github.com wrote:



Be sure to link to https://wiki.archlinux.org/index.php/Tailscale too.

—

You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
