### ISSUE TITLE
Segmentation violation on Debian 12 with Tailscale from Apt

### ISSUE THREAD

**Issue by jpenninkhof** [tailscale/tailscale#10945]
### What is the issue?

I have installed Tailscale on my Debian 12 machine and it fail to start. The log files show this:

RAW-STDERR: ***
RAW-STDERR: *** Lines prefixed with RAW-STDERR below bypassed logtail and probably come from a previous run of the program
RAW-STDERR: ***
RAW-STDERR:
RAW-STDERR: panic: runtime error: invalid memory address or nil pointer dereference
RAW-STDERR: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x494030]
RAW-STDERR:
RAW-STDERR: goroutine 289 [running]:
RAW-STDERR: tailscale.com/util/linuxfw.(*iptablesRunner).HasIPV6(...)
RAW-STDERR:         tailscale.com@v1.58.2/util/linuxfw/iptables_runner.go:85
RAW-STDERR: tailscale.com/util/linuxfw.(*iptablesRunner).getTables(...)
RAW-STDERR:         tailscale.com@v1.58.2/util/linuxfw/iptables_runner.go:135
RAW-STDERR: tailscale.com/util/linuxfw.(*iptablesRunner).AddChains(0x0)
RAW-STDERR:         tailscale.com@v1.58.2/util/linuxfw/iptables_runner.go:208 +0x14
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).setNetfilterMode(0x1516060, 0x2)
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:547 +0x6b8
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).Set(0x1516060, 0x45f0550)
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:367 +0x27c
RAW-STDERR: tailscale.com/wgengine.(*userspaceEngine).Reconfig(0x157c1e0, 0x45b0500, 0x45f0550, 0x45e5b00)
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/userspace.go:920 +0x13e8
RAW-STDERR: tailscale.com/wgengine.(*watchdogEngine).Reconfig.func1()
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/watchdog.go:122 +0x40
RAW-STDERR: tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func2()
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/watchdog.go:82 +0x24
RAW-STDERR: created by tailscale.com/wgengine.(*watchdogEngine).watchdogErr in goroutine 91
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/watchdog.go:81 +0x1e0

### Steps to reproduce

Install Tailscale (on Debian 12):

sudo apt install tailscale
sudo tailscale up (and authenticate)

### OS

Linux

### OS version

Debian 12

### Tailscale version

 1.58.2

### Other software

None. Running the most basic, plain version of Debian. UFW is also not installed.

**Comment by catzkorn** [comment]
Hi,

Does this machine have IPv6 addresses and what kernel version are you using?

**Comment by danderson** [comment]
Looking at the stack trace, we're invoking methods on a nil iptablesRunner. That's the proximal cause of the crash. Now the difficulty is figuring out how the runner ends up nil in the first place.

Debian 12 is also a very common OS for us, so I'm wondering why you're the first to see this - hence the clarifying questions above to try and narrow things down.

**Comment by danderson** [comment]
At a quick inspection of the code, I can't see any way to end up in this stack trace. The firewall runner is initialized and definitely non-nil at router_linux.go:547, and yet we end up with a nil pointer crash accessing the object. I also can't reproduce this.

So, we need to focus on what's different with your debian install that might trigger this, otherwise, I don't see where to go from here. If you have any thoughts of how this machine could be different from every other working debian install we see, I welcome ideas to explore.

**Comment by albsen** [comment]
I'm getting the same on debian testing with kernel 6.7.2.

Here is another error message right above the one attached to this ticket:

```
 UpdateMagicsockPort(port=41641, network=udp6) failed: %!w(*fmt.wrapError=&{could not setup netfilter: could not create new netfilter: could not get iptables version: exit status 1 0x400010e000}) 
```

```
logtail started                                            
Program starting: v1.58.2-t6a2a8457f-g8c7d4563e, Go 1.21.5: []string{"/usr/sbin/tailscaled", "--cleanup"}                                            
LogID: 5302df301f9121e90xxxxxxxxxxx                                                                                
logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"                                            
RAW-STDERR: ***                                            
RAW-STDERR: *** Lines prefixed with RAW-STDERR below bypassed logtail and probably come from a previous run of the program                                            
RAW-STDERR: ***                                            
RAW-STDERR:                                            
RAW-STDERR: panic: runtime error: invalid memory address or nil pointer dereference                                            
RAW-STDERR: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3dca50]                                            
RAW-STDERR:                                            
RAW-STDERR: goroutine 50 [running]:                                            
RAW-STDERR: tailscale.com/util/linuxfw.(*iptablesRunner).HasIPV6(0x40001580b0?)                                            
RAW-STDERR:         tailscale.com@v1.58.2/util/linuxfw/iptables_runner.go:85                                             
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).getV6Available(...)                                             
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:605                                            
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).addrFamilies(...)                                            
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:973                                            
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).delIPRules(0x40001580b0)                                            
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:1192 +0x48                                            
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).addIPRules(0x40001580b0)                                            
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:989 +0x28                                            
RAW-STDERR: tailscale.com/wgengine/router.(*linuxRouter).Up(0x40001580b0)                                            
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/router/router_linux.go:298 +0xf8                                            
RAW-STDERR: tailscale.com/wgengine.NewUserspaceEngine(0x4000404050, {{0xd2ed08, 0x40006c8000}, 0x0, {0xd29798, 0x40001580b0}, {0xd29610, 0x4000216230}, 0x40001bb930, 0x40005a8000, ...})                                            
RAW-STDERR:         tailscale.com@v1.58.2/wgengine/userspace.go:428 +0x1168                                            
RAW-STDERR: main.tryEngine(0xb8bb0d?, 0x4000001d40, {0xb5f09b, 0xa})                                            
RAW-STDERR:         tailscale.com@v1.58.2/cmd/tailscaled/tailscaled.go:693 +0x614                                            
RAW-STDERR: main.createEngine(0x4000404050, 0xb09480?)                                            
RAW-STDERR:         tailscale.com@v1.58.2/cmd/tailscaled/tailscaled.go:591 +0x180                                            
RAW-STDERR: main.getLocalBackend({0x0?, 0x0?}, 0x4000404050, {0x53, 0x2, 0xdf, 0x30, 0x1f, 0x91, 0x21, ...}, ...)                                            
RAW-STDERR:         tailscale.com@v1.58.2/cmd/tailscaled/tailscaled.go:488 +0x100                                            
RAW-STDERR: main.startIPNServer.func2()                                            
RAW-STDERR:         tailscale.com@v1.58.2/cmd/tailscaled/tailscaled.go:454 +0x1e4                                            
RAW-STDERR: created by main.startIPNServer in goroutine 1                                            
RAW-STDERR:         tailscale.com@v1.58.2/cmd/tailscaled/tailscaled.go:442 +0x39c                                            
dns: resolvedIsActuallyResolver error: resolv.conf doesn't point to systemd-resolved; points to [x.x.x.20 x.x.x.222]                                                      
dns: [rc=nm resolved=not-in-use ret=direct]                                            
dns: using "direct" mode                                            
dns: using *dns.directManager                                            
linuxfw: clear iptables: could not get iptables version: exit status 1                                            
linuxfw: clear ip6tables: could not get iptables version: exit status 1                                            
cleanup: list tables: socket: protocol not supported 
```

**Comment by jpenninkhof** [comment]
> Hi,
> 
> Does this machine have IPv6 addresses and what kernel version are you using?

Thanks for looking into this! :)

Yes, it has IPv6 addresses:

```
$ ip -6 addr show dev wlan0
4: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet6 2a02:2f4:824a:fb00:ddc8:e9a2:c84:61e9/64 scope global dynamic noprefixroute 
       valid_lft 7081sec preferred_lft 3481sec
    inet6 fe80::38e2:f7fb:9890:6bea/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

Please find Linux/kernel details below:

```
$ cat /proc/version 
Linux version 4.4.13-ntc-mlc (bamboo@ip-172-31-21-118) (gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu1) ) #1 SMP Tue Dec 6 21:38:00 UTC 2016
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by jpenninkhof** [comment]
> Maybe tailscaled can display a proper error message if iptables isn't working properly. 

I didn't realize that running iptables is a requirement. It's a very tiny IOT-type machine, iptables is indeed not running:

```
# lsmod | grep ip_tables
<nothing>
```

Is it true that iptables is required to run tailscale? If it is, then a warning/error message would be a very good suggestion!

**Comment by albsen** [comment]
I believe iptables is needed to configure the routing changes that tailscale needs to make its magic work.

From your post it looks like you're running debian bookworm (i think that was 12) using an really old ubuntu kernel. Debian has switched some time ago from iptables to nftables. You're kernel might predate NFT.

You have 2 options:

1) update the kernel to 6.* - or at least 5.* (not sure please confirm your self when they added NFT)
2) based on the debian wiki (with amazing backwards compatibility) you can switch to the old iptables ( https://wiki.debian.org/nftables )

From the debian wiki on how to switch to legacy iptables:

```
# remove the # in front before copy / pasting ;)
# update-alternatives --set iptables /usr/sbin/iptables-legacy
# update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
# update-alternatives --set arptables /usr/sbin/arptables-legacy
# update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```

To confirm if NFT is available, once you updated your kernel.
```
sudo modprobe nf_tables
```

Running such an ancient kernel is concerning anyway, also, mixing ubuntu and debian packages points to many more random issues - hopefully you didn't add ubuntu repo's into the mix with debian repos.

**Comment by danderson** [comment]
Tailscale in its default configuration currently requires the iptables _binary_ to configure the firewall, but it can be the iptables-nft shim if you want to use nftables in the kernel. Or of course if you set it up to use iptables-legacy, that works too.

Another alternative if you're willing to try experimental code, is to set the environment variable TS_DEBUG_FIREWALL_MODE=nftables, which will switch to newer code that uses a netlink socket to configure the firewall directly. This is not the current default so may well have bugs or break later on, but if you need to avoid installing the iptables binary, that is an option if you're okay with unstable code.

The crash is still weird, and I still can't find any codepath that could reach a nil pointer dereference via the stack traces you provide, so I'm still not sure what's happening there.

**Comment by jpenninkhof** [comment]
Apologies for the late response. The device is running remotely, so I have to be very careful with what I do. I prepared a similar device in my lab and stared tinkering.

> 1. update the kernel to 6.* - or at least 5.* (not sure please confirm your self when they added NFT)

Unfortunately, that's not an option. The nand of this machine is proprietary and not supported by any newer kernels than the one I'm running.

> 2. based on the debian wiki (with amazing backwards compatibility) you can switch to the old iptables ( https://wiki.debian.org/nftables )
> 
> From the debian wiki on how to switch to legacy iptables:
> 
> ```
> # remove the # in front before copy / pasting ;)
> # update-alternatives --set iptables /usr/sbin/iptables-legacy
> # update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
> # update-alternatives --set arptables /usr/sbin/arptables-legacy
> # update-alternatives --set ebtables /usr/sbin/ebtables-legacy
> ```

That is definitely an option. Debian is awesome! With that I have the legacy iptables back.

> Tailscale in its default configuration currently requires the iptables binary to configure the firewall

Yes! So with iptables back and linked using update-alternatives, tailscale will be able to find the binary as well. And with this, I can report that Tailscale is running! 

I must say, this is quite awesome. Didn't tell you before, but the hardware tailscale is running on is a [C.H.I.P. computer](https://en.wikipedia.org/wiki/CHIP_(computer)), a $9 computer from 2016, consuming slightly more than 1W. It's controlling IOT devices such as blinds, lights etc at my in-laws house in Germany. With Tailscale on it, I can maintain it remotely without having to open any ports.

Thanks, @danderson and @albsen for your great responses and help! Just amazing!
