### ISSUE TITLE
tailscale.com is blocked on Cloudflare / CIPA Filter

### ISSUE THREAD

**Issue by tmaier** [tailscale/tailscale#10948]
### What is the issue?

I am unable to access your marketing websites (https://tailscale.com) when I am connected with the corporate network.

https://radar.cloudflare.com/domains/domain/tailscale.com

<img width="726" alt="image" src="https://github.com/tailscale/tailscale/assets/350038/0888a27f-96fe-445a-8a0d-140842f1a365">

**Comment by DentonGentry** [comment]
Do you know if this happened recently, like did you visit the site periodically but today it does this?

**Comment by tmaier** [comment]
I am not sure... I _think_ it happend 2 days ago...

At least I think I was able to access the page on Tuesday. Since yesterday I can conform it does not work anymore.

**Comment by tmaier** [comment]
I bet the problem are the categorization at Cloudflare Radar. Yesterday I think it was not jus "P2P"

<img width="455" alt="image" src="https://github.com/tailscale/tailscale/assets/350038/a5b31dcc-2378-4b3f-8744-3d6fdd9eca27">

**Comment by agottardo** [comment]
@tmaier is this resolved now?

**Comment by agottardo** [comment]
Closing as it appears the categorization has been changed on radar.cloudflare.com.

**Comment by tmaier** [comment]
I am now back at the office. I can confirm that it is not blocked anymore. Thank you
