### ISSUE TITLE
RPM repository for Fedora doesn't offer latest version

### ISSUE THREAD

**Issue by der-eismann** [tailscale/tailscale#10947]
### What is the issue?

Following the installation instructions [here](https://tailscale.com/kb/1050/install-fedora) and/or [here](https://pkgs.tailscale.com/stable/#fedora), the latest version I can install is `1.56.1`. `1.58.2` was released two days ago, do you need that time for testing? I can't imagine it takes two days to build an RPM after you released the archives for download.

### Steps to reproduce

1. Add RPM repository to Fedora/Red Hat
2. Execute `dnf install tailscale`
3. Get 1.56.1 instead of 1.58.2

### OS

Linux

### OS version

Fedora 39

### Tailscale version

1.56.1

**Comment by awly** [comment]
Thanks for the report!
The RPMs were built 2 days ago along with the rest of the release.
For some reason, our RPM repo is not putting them into the metadata it's serving, and I'm investigating why.

**Comment by awly** [comment]
RPM repo is fixed now.

When addressing https://github.com/tailscale/tailscale/issues/9399 we pushed a new RPM for `tailscale-nignix-auth` to our repo server which confused the indexing code, so the list of packages went stale for a few days.
You should now be able to `dnf install tailscale` on new systems or `dnf upgrade --refresh tailscale` on existing ones.
Sorry for the delay!

**Comment by der-eismann** [comment]
Awesome, thanks for the quick fix!

**Comment by kevinjcliao** [comment]
Hi @awly, the latest version of tailscale I can install on Fedora appears to be 1.84.1-3, which seems quite outdated. Is there a newer RPM built yet? Thanks!

**Comment by der-eismann** [comment]
Can't confirm, I'm running >1.90 on Fedora from the Tailscale repo. Are you installing from the OS repo instead maybe? Versions would match 
https://src.fedoraproject.org/rpms/tailscale

**Comment by awly** [comment]
@kevinjcliao as @der-eismann suggested, the RPM repos we manage can be configured via https://pkgs.tailscale.com/stable/#fedora.
Unfortunately we don't control Fedora's own repos and can't push new versions there.
