### ISSUE TITLE
Tailscale homeassistant addon (hassio) not supporting debian

### ISSUE THREAD

**Issue by haklai** [tailscale/tailscale#10964]
### What is the issue?

when enabling "Accept routes" mode, it is looking for kernel config at /proc/config.gz (according to logs) which is not available on Debian. Then fails to start.

### OS

Linux, Other

### OS version

Debian 12

**Comment by catzkorn** [comment]
Hi,

We are not the developers of the homeassistant add-on, but you can submit an issue for the team [here](https://github.com/hassio-addons/addon-tailscale).
