### ISSUE TITLE
Linux Install - Certificate verification failed

### ISSUE THREAD

**Issue by mahdi357** [tailscale/tailscale#10965]
### What is the issue?

When running the command to install the Linux version, I get the error below for the certificate. I use AWS Ubuntu 20. 

```
After this operation, 48.1 MB of additional disk space will be used.
Err:1 https://pkgs.tailscale.com/stable/ubuntu focal/main amd64 tailscale amd64 1.58.2
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2a09:8280:1::a:1a71 443]
E: Failed to fetch https://dl.tailscale.com/stable/tailscale_1.58.2_amd64.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2a09:8280:1::a:1a71 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Steps to reproduce

`curl -fsSL https://tailscale.com/install.sh | sh`

`sudo apt-get update`

`curl -fsSL https://tailscale.com/install.sh | sh -s -- --no-check-certificate`

```
sudo apt-get install -y apt-transport-https 
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.key | sudo apt-key add -
sudo apt-add-repository "deb https://pkgs.tailscale.com/stable/ubuntu focal main"
sudo apt-get update
sudo apt-get install tailscale
```

None worked. 

### OS

Ubuntu

### OS version

AWS Ubuntu 20 

### Other software

Fresh Install

**Comment by mahdi357** [comment]
The output for 'curl -v -I https://pkgs.tailscale.com/' command is below:

ubuntu@ip-172-26-10-47:~$ curl -v -I https://pkgs.tailscale.com/
*   Trying 2607:f740:fd::d19:443...
* TCP_NODELAY set
* Connected to pkgs.tailscale.com (2607:f740:fd::d19) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=pkgs.tailscale.com
*  start date: Jan 18 13:16:26 2024 GMT
*  expire date: Apr 17 13:16:25 2024 GMT
*  subjectAltName: host "pkgs.tailscale.com" matched cert's "pkgs.tailscale.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55cce8af17c0)
> HEAD / HTTP/2
> Host: pkgs.tailscale.com
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
HTTP/2 200
< content-type: text/html; charset=utf-8
content-type: text/html; charset=utf-8
< strict-transport-security: max-age=63072000; includeSubDomains
strict-transport-security: max-age=63072000; includeSubDomains
< content-length: 1052
content-length: 1052
< date: Sun, 28 Jan 2024 14:15:06 GMT
date: Sun, 28 Jan 2024 14:15:06 GMT

<
* Connection #0 to host pkgs.tailscale.com left intact
ubuntu@ip-172-26-10-47:~$


I also checked the time and tried to sync but nothing changed. 


root@ip-172-26-10-47:/home/ubuntu# date
Sun Jan 28 14:19:45 UTC 2024

root@ip-172-26-10-47:/home/ubuntu# sudo apt install ntp
root@ip-172-26-10-47:/home/ubuntu# sudo systemctl start ntp
root@ip-172-26-10-47:/home/ubuntu# sudo systemctl enable ntp
Synchronizing state of ntp.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ntp
root@ip-172-26-10-47:/home/ubuntu# timedatectl
               Local time: Sun 2024-01-28 14:19:57 UTC
           Universal time: Sun 2024-01-28 14:19:57 UTC
                 RTC time: Sun 2024-01-28 14:19:58
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no
root@ip-172-26-10-47:/home/ubuntu#

**Comment by icio** [comment]
Does curl still succeed if you tell it to use the native OS cert store? `curl -v -I --ca-native https://pkgs.tailscale.com/`. What version of `ca-certificates` do you have installed, and can you please try to install/update/reinstall it?

SSL labs shows the certs are looking OK, but it checked the IP resolved for curl, rather than the IP resolved for apt: https://www.ssllabs.com/ssltest/analyze.html?d=pkgs.tailscale.com

**Comment by mahdi357** [comment]
I needed to update to the latest version of cul.

`apt-get update && apt-get upgrade curl`

After update and upgrade I was able to run the installation.

Alternatively, I also was able to downlod and install the package manually using these commands:

`wget https://dl.tailscale.com/stable/tailscale_1.58.2_amd64.deb
sudo dpkg -i tailscale_1.58.2_amd64.deb
sudo tailscale up`

**Comment by icio** [comment]
That's great. Thanks for letting us know. Did apt also upgrade ca-certificates when you asked it to upgrade curl?

**Comment by mahdi357** [comment]
No, I didn't. I just did `apt-get update && apt-get upgrade curl` and it did the trick.

**Comment by strausmann** [comment]
I had this problem on a Raspberry PI and it was due to an incorrect time setting on the system. The Raspberry PI does not have an internal clock.
