### ISSUE TITLE
iOS Shortcut “Disconnect” option connects Tailscale when not already connected

### ISSUE THREAD

**Issue by le0-VV** [tailscale/tailscale#10961]
### What is the issue?

As title. When iOS devices is not already connected to Tailscale, the shortcut option “Disconnect” will connect the device instead of doing nothing. “Get status” returns text “Tailscale status” instead of the actual state of the connection, so can’t be used to manually control the connection

### Steps to reproduce

1. Create an automation in shortcut that includes “Disconnect”
2. Leave Tailscale disconnected
3. Trigger the automation, running the automated actions doesn’t reproduce this bug

Result: Tailscale would connect

### OS

iOS

### OS version

17.3

### Tailscale version

1.58.2

### Other software

Shortcut

### Bug report

BUG-75a90a0f4722fe183c7fa0b743ae01db66e56599a30ee5225e6fec262a918a3a-20240127044752Z-c49a9f115b357e62

**Comment by catzkorn** [comment]
Hi,

Thanks for the report! We have flagged this with our iOS team.

**Comment by Eaglw** [comment]
I'm having the same issue.

**Comment by lsrmg** [comment]
I have the same problem.

As a workaround you can use an if statement with the Tailscale status.

![image](https://github.com/user-attachments/assets/a51a5945-75cd-412f-8a04-95a3b4324ad6)

**Comment by dominikconrads** [comment]
The problem still exists today in version 1.68.0 on iOS/iPadOS. 
It seems that the „disconnect“ shortcut / app intent is in fact executing the „toggle“ shortcut / app intent. 
The only way to achieve a disconnect at the moment is with the aforementioned workaround.

**Comment by agottardo** [comment]
We are aware of the issue, a fix will land in v1.72.

**Comment by agottardo** [comment]
Fix will land in the next TestFlight build
