### ISSUE TITLE
tailscaled.exe flagged as malicious by ESET on 1.58.2

### ISSUE THREAD

**Issue by NicholasCJL** [tailscale/tailscale#10987]
### What is the issue?

On the latest version (1.58.2) on windows, tailscaled.exe gets flagged by ESET-NOD32

[VirusTotal](https://www.virustotal.com/gui/file/4d853123cc9a3b7170c8304464e38654858c48092b5150a017c7f34780b442fa/detection) 

Reverting to the last publicly available version (1.44.3) fixes this issue.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.58.2

**Comment by Depicus** [comment]
Also on ESET and if you downgrade then it is also picked up seemingly all the way back to 1.52

Error message is




NEW NOTIFICATION
--
Malicious file WinGo/HackTool.ReverseSsh.F was detected on computer xxx
Detection type: TrojanDetection name: WinGo/HackTool.ReverseSsh.F
Computer name: xxx Computer static group hierarchy: xxx: Administrator initiated scanTime of occurrence: 1/31/24, 10:57:41 AM UTCScanner: On‑demand scannerAction performed: DeletedNotification aggregation statistic:The same type of detection occurred 2 times. To see more details, log in to ESET PROTECT and go to Detections.

NEW NOTIFICATION
Malicious file WinGo/HackTool.ReverseSsh.F was detected on computer xxx
Detection type: Trojan
Detection name: WinGo/HackTool.ReverseSsh.F
Computer name: xxx
Computer static group hierarchy:xxx
Logged user: Administrator initiated scan
Time of occurrence: 1/31/24, 10:57:41 AM UTC
Scanner: On‑demand scanner
Action performed: Deleted

Notification aggregation statistic:
The same type of detection occurred 2 times. To see more details, log in to ESET PROTECT and go to Detections.

**Comment by DentonGentry** [comment]
@Depicus Is there a popup message from ESET? Could you take a screenshot?

Tailscale would submit a false positive report to ESET:
https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab#SubmitFile

**Comment by Depicus** [comment]
> @Depicus Is there a popup message from ESET? Could you take a screenshot?
> 
> Tailscale would submit a false positive report to ESET: https://support.eset.com/en/kb141-submit-a-virus-website-or-potential-false-positive-sample-to-the-eset-lab#SubmitFile
> 
> Given the name `WinGo/HackTool.ReverseSsh.F`, I imagine the presence of the Go SSH code in the binary is triggering the report.

These are automated alerts we get so just an email. We didn't want to mark as a false positive because we don't know if the codebase was compromised or not so ESET has slowly been deleting from 300+ machines and we have moved to another VPN provider for now until resolved.

Happy to provide any logs but best I can do for screenshot is 

<img width="1841" alt="Screenshot 2024-01-31 at 14 25 47" src="https://github.com/tailscale/tailscale/assets/343795/fe785e5b-eeae-4371-9e1c-798725aa219c">

**Comment by kgleason** [comment]
Also affecting us:

![image](https://github.com/tailscale/tailscale/assets/2130628/71354092-3007-4d85-afea-f577ec1c6345)

We have submitted a false positive report to ESET, and are rolling back our deployment.

**Comment by Depicus** [comment]
> Also affecting us:
> 
> ![image](https://private-user-images.githubusercontent.com/2130628/301204508-71354092-3007-4d85-afea-f577ec1c6345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTMzNjEsIm5iZiI6MTcwNjcxMzA2MSwicGF0aCI6Ii8yMTMwNjI4LzMwMTIwNDUwOC03MTM1NDA5Mi0zMDA3LTRkODUtYWZlYS1mNTc3ZWMxYzYzNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTQ1NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1OTgwZjgyNDliZmJmZWU1ZGFmY2VlZDA5OWI2NTAwYWE4NDFjMmQ2ZDc4NWQ0OGEwOWE3ZjcyNGUwNDkyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z9Xwk0AVxF7_brB_8f_Arfr8qokns8iULc_MGrixFA4)
> 
> We have submitted a false positive report to ESET, and are rolling back our deployment.

Just be careful on rollback as we tried to go back to 1.56 and ESET picked that as well.

**Comment by kgleason** [comment]
Also affecting us:

![image](https://github.com/tailscale/tailscale/assets/2130628/71354092-3007-4d85-afea-f577ec1c6345)

We have submmited a false positive report to ESET, and are rolling back our deployment.

> > Also affecting us:
> > ![image](https://private-user-images.githubusercontent.com/2130628/301204508-71354092-3007-4d85-afea-f577ec1c6345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTMzNjEsIm5iZiI6MTcwNjcxMzA2MSwicGF0aCI6Ii8yMTMwNjI4LzMwMTIwNDUwOC03MTM1NDA5Mi0zMDA3LTRkODUtYWZlYS1mNTc3ZWMxYzYzNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTQ1NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1OTgwZjgyNDliZmJmZWU1ZGFmY2VlZDA5OWI2NTAwYWE4NDFjMmQ2ZDc4NWQ0OGEwOWE3ZjcyNGUwNDkyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z9Xwk0AVxF7_brB_8f_Arfr8qokns8iULc_MGrixFA4)
> > We have submitted a false positive report to ESET, and are rolling back our deployment.
> 
> Just be careful on rollback as we tried to go back to 1.56 and ESET picked that as well.

Yeah I think we are going back to something like 1.54

**Comment by awly** [comment]
I do not see any signs of tampering with our Windows packages so this indeed looks like a false positive.
We will submit a false positive report to ESET too from Tailscale.

**Comment by inh3** [comment]
An option that can mitigate this issue temporarily while this false positive is being addressed is use [ESET's Detection Exclusion](https://help.eset.com/eav/17/en-US/idh_detection_exclusion.html) feature.  It allows for excluding a single file for a particular detection name/type.

I added one for Tailscale and `WinGo/HackTool.ReverseSsh.F` then scanned the folder and ESET didn't detect or take action to remedy.

**Comment by andy-clee** [comment]
Just adding a few screenshots. We've had the issue today for a few customers. The solution has been to remove and install version 1.56.1 however, one customer's ThreatLocker software also reports issues with this version.

![ESET](https://github.com/tailscale/tailscale/assets/158390359/22ab2c2a-ef0b-428b-b160-9ad04ba7dff6)

![TL](https://github.com/tailscale/tailscale/assets/158390359/0fa43d45-c9d7-4a15-9dcd-0bab831ed941)

**Comment by inh3** [comment]
> An option that can mitigate this issue temporarily while this false positive is being addressed is use [ESET's Detection Exclusion](https://help.eset.com/eav/17/en-US/idh_detection_exclusion.html) feature. It allows for excluding a single file/path for a specific detection name/type.
> 
> I added one for `C:\Program Files\Tailscale\tailscale.exe` (my install location) and `@NAME=WinGo/HackTool.ReverseSsh.F@TYPE=Trojan`, then scanned the folder and ESET didn't detect or take action to remedy.
> 
> Also, I fixed my current install that had `tailscale.exe` deleted by following the [Uninstalling Tailscale guide for Windows](https://tailscale.com/kb/1069/uninstall?tab=windows). A Tailscale uninstaller will pop up and it offers an option "Repair" which recreated `tailscale.exe` and it started up again. Remember, do this after setting the ESET Detection Exclusion.

Will we get a confirmation when Tailscale is no longer flagged as a malware/virus by ESET?

I would like to disable the ESET Detection Exception for Tailscale at that time.

**Comment by awly** [comment]
We received a response from ESET that the false positive has been fixed in the latest update.
Please update your ESET installation and let us know if it stops flagging Tailscale as malicious :pray:

**Comment by Depicus** [comment]
> We received a response from ESET that the false positive has been fixed in the latest update. Please update your ESET installation and let us know if it stops flagging Tailscale as malicious 🙏

Thanks Andrew will you be clearing the other two as well ? [https://www.virustotal.com](https://www.virustotal.com/gui/file/4d853123cc9a3b7170c8304464e38654858c48092b5150a017c7f34780b442fa/detection)

**Comment by awly** [comment]
@Depicus yes, we've sent out false positive reports to those vendors too.

There are many vendors out there that use ML-based detection engines that tend to result in false positives. Every so often, that results in some Tailscale binary getting flagged by some vendor by mistake. It's an ongoing toil that comes with shipping software installed on endpoints.

So, while we try to clear up VT results, it's not unusual for something to be flagged (but it would be very unusual for something to be flagged by the majority of vendors!).

**Comment by Depicus** [comment]
> @Depicus yes, we've sent out false positive reports to those vendors too.
> 
> There are many vendors out there that use ML-based detection engines that tend to result in false positives. Every so often, that results in some Tailscale binary getting flagged by some vendor by mistake. It's an ongoing toil that comes with shipping software installed on endpoints.
> 
> So, while we try to clear up VT results, it's not unusual for something to be flagged (but it would be very unusual for something to be flagged by the majority of vendors!).

Thanks a lot - we are putting it through our test lab now but results very good so far

**Comment by gregg098** [comment]
My workaround for now was to install a test build (1.59.13 from [HERE](https://pkgs.tailscale.com/unstable/#windows)). No detections yet. To get it installed I had to do this:

- Pause ESET detection
- Uninstall Tailscale from Windows
- Verify the C;:\Program Files\Tailscale directory is gone.
- Re-enable ESET detection
- Install new version

**Comment by CamFlyerCH** [comment]
For me a "Repair" worked fine. (Opening Windows Settings, Apps, select uninstall, select repair instead of uninstall in the Installer.) Settings still OK, worked right away.
