### ISSUE TITLE
FR: Multiple IDP support

### ISSUE THREAD

**Issue by ryanofrivia** [tailscale/tailscale#10981]
### What are you trying to do?

We need a way to authenticate multiple Okta OIDC apps into the same tailscale tenant. We need this feature to help scale the complex enterprise environment that we manage.

### How should we solve this?

- Give users the ability to manage multiple OIDC settings in web app or offer support

### What is the impact of not solving this?

We will have to spin up separate Tailscale instances which adds enormous complexity to our environment

**Comment by catzkorn** [comment]
Hi,

We do not currently support this, but it is among the features we are considering in the future. Please contact our sales team if you would like to tell us more about your requirements. 

For an immediate work around, you could use our [Custom OIDC](https://tailscale.com/kb/1240/sso-custom-oidc) feature to multiplex your Okta logins into a singular authentication provider with an IDP who allows this. However this would require setup and maintenance on your side.
