### ISSUE TITLE
Running Tailscale on Bluestacks (Android Emulator) is crashing

### ISSUE THREAD

**Issue by plia7** [tailscale/tailscale#10984]
### What is the issue?

Hello,

I got BlueStacks (Android Emulator) version 5.20.101.1002 on my Windows 11. 
I didn't sign in into Google Play so I'm just installing the apk files directly by drag & drop.
I installed Tailscale version 1.56.0 and when I try to open the app, it crashes.

I saw the tailscale github section for "Running in the Android emulator" and it mentions:

_By default, the android emulator uses an older version of OpenGL ES, which results in a black screen when opening the Tailscale app. To fix this, with the emulator running:_

_Open the three-dots menu to access emulator settings
To to Settings > Advanced
Set "OpenGL ES API level" to "Renderer maximum (up to OpenGL ES 3.1)"
Close the emulator.
In Android Studio's emulator view (that lists all your emulated devices), hit the down arrow by the virtual device and select "Cold boot now" to restart the emulator from scratch.
The Tailscale app should now render correctly._

So I installed Device Info HW app and confirmed that my OpenGL ES version is 3.1.

I also tried to install an earlier version of Tailscale version 1.42 and it still crashes.

Please advise how to resolve.

Thank you.

### Steps to reproduce

See above.

### Are there any recent changes that introduced the issue?

-

### OS

Android

### OS version

BlueStacks version 5.20.101.1002

### Tailscale version

1.56.0

**Comment by catzkorn** [comment]
Hi,

We do not currently support running on Bluestacks. We will keep this issue open, but this is not on our product roadmap.

We suggest installing Tailscale for Windows.

**Comment by fgfg163** [comment]
I find tailscale app 1.12.1 from google
Installed tailscale app 1.12.1 to bluestacks 5.13.220 and work well. And scrcpy connect to tailscale's ip and work well too.
There is a bug: can't edit IP of 1.12.1.

blue stacks version: 5.13.220.1001 P64
hyper-v mode
system: Android 9 x64

tailscale version: 1.12.1-1d7592eb117-g1fc94ccf979
