### ISSUE TITLE
Failed to execute apt and wget after installing tailscale

### ISSUE THREAD

**Issue by Fdsapoawa** [tailscale/tailscale#11018]
### What is the issue?

Failed to execute apt and wget after installing tailscale apt progress bar is 0%.

### Steps to reproduce

reinstall system

### Are there any recent changes that introduced the issue?

kill apt
have no effect

### OS version

Ubuntu 22.04

### Tailscale version

 1.58.2

### Other software

not have

### Bug report

BUG-6e70865a6b27aa24bda0dd31e16e660851b500aafdb85cdaba309ed204a3ba7f-20240202175954Z-d5ed2853dfa3fdc2

**Comment by andrews-jump** [comment]
This is not a bug. You need an external DNS of some sort to resolve addresses as they aren't resolvable through Tailscale's DNS
