### ISSUE TITLE
Fails at boot with wgengine.NewUserspaceEngine: monitorDefaultRoutes, after 143ms: error getting v4 interface: Element not found.

### ISSUE THREAD

**Issue by leonsteenkamp** [tailscale/tailscale#1101]
**Describe the bug**
Tailscale fails to start correctly at boot. A message box with the message below can be seen:

_Tailscale Error
Tailscale backend error:
wgengine.NewUserspaceEngine: monitorDefaultRoutes, after 143ms: error getting v4 interface: Element not found._

After clicking OK on the message box the tray icon dies but the Tailscale service is still running. If you open the Tailscale app again from the start menu it looks like everything starts up OK and you can access other machines.

At the moment this is happening on every boot.

**Version information:**
 - Device: Desktop, wired Ethernet connection
 - OS: Windows
 - OS version: Windows 10 Pro 20H2 19042.685
 - Tailscale version: 1.3.147

**Additional context**
Work around for this at the moment is to just restart Tailscale after it fails to start at boot.

From the log in C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs\ it looks like it tries five times and fails:

2021-01-10T18:17:27.453+02:00: wgengine.NewUserspaceEngine: (try 5) Element not found.
2021-01-10T18:17:27.453+02:00: wgengine.NewUserspaceEngine: Element not found.

**Comment by leonsteenkamp** [comment]
Hi, it looks like this has now gone away after a recent (2021-01-13) Windows update. I made no other changes that would cause the problem to go away. So I am going to close this issue.

**Comment by leonsteenkamp** [comment]
Nope, it is back, still the same issue. I also tried disabling Docker Desktop at boot to see if that makes a difference.


Tailscale Error
Tailscale backend error:
wgengine.NewUserspaceEngine: monitorDefaultRoutes, after 35ms: error getting v4 interface: Element not found.

Tailscale Error
Tailscale backend error:
wgengine.NewUserspaceEngine: monitorDefaultRoutes, after 33ms: error getting v4 interface: Element not found.

**Comment by denisbrodbeck** [comment]
I've got the same error message.

log from `C:\Users\myuser\AppData\Local\Tailscale\tailscale-ipn.log1.txt`:

```json
{"logtail": {"client_time": "2021-01-18T20:42:34.9750057+01:00"}, "text": "backend error: wgengine.NewUserspaceEngine: monitorDefaultRoutes, after 30ms: error getting v4 interface: Element not found.\n\nlogid: 81e92c8fd38eb525fb93ffb39726a2af8617f72e1739e08af7f449c54444ef8c\n"}
```

Win10 Pro 20H2 x64 latest patches installed. Hyper-V, but no Docker installed. Restarting client app fixed it for now. But error gets thrown after every reboot.

**Comment by peske** [comment]
This issue is related with https://github.com/tailscale/tailscale/issues/1187, and chances are that it's solved in v1.3.313. If not please let us know.

**Comment by denisbrodbeck** [comment]
@peske Can confirm. Installed v1.4, error message went away — thanks.
@leonsteenkamp Please try the latest version, if it works this ticket can be closed :)

**Comment by bradfitz** [comment]
Yeah, I think we've sufficiently worked around this for now. More changes coming later but we can track them in other bugs.
