### ISSUE TITLE
FR: Selectable Wi-Fi when adding SSID for VPN On-Demand exceptions

### ISSUE THREAD

**Issue by walchst** [tailscale/tailscale#11011]
### What are you trying to do?

When adding a specific Wi-Fi network name as an exception for VPN On-Demand ie Only On or Except On, it's a free type field. This is slightly cumbersome and lends itself to typos. 

### How should we solve this?

It would be great if you could pull the list of configured Wi-Fi networks (or at least the currently connected one) so that this is a selectable item. I've seen this behaviour with other apps, for example NordVPN.

### What is the impact of not solving this?

Makes the process of configuring exceptions more seamless and removes the likelihood of typos.

**Comment by agottardo** [comment]
This has been on the back of my mind for a bit. However, we can only read the current Wi-Fi network name, and it requires location privacy access, which is a known source of user prompt fatigue.

**Comment by agottardo** [comment]
We have a PR in the pipeline to add this, we expect it should ship in 1.74 (or earlier TestFlight builds).

**Comment by agottardo** [comment]
Will land in the next TestFlight update.
