### ISSUE TITLE
Tailnet devices not all showing on iOS/tvOS TestFlight v1.59.21

### ISSUE THREAD

**Issue by LostInSpace132** [tailscale/tailscale#11020]
### What is the issue?

It seems as if the latest testflight 1.59.21 beta, when you connect in the ios or ipados app, the list of devices is truncated to only the device you are using and all the other inactive devices on the tailnet. All the active devices (green status dot) are not displayed. So I couldn’t find the ip address of my home server today because it wasnt listed even though it was on and active. Same for my apple tv. It was not on the list even though it was active on the tailnet. 

### OS version

17.3

### Tailscale version

1.59.21

### Bug report

BUG-c67e4cb4a7f1a5b8939a5af523ae3c514b7a82f17c6d16fea1604b265ed31306-20240202200126Z-9f41615984d05272

**Comment by agottardo** [comment]
We unfortunately regressed this in yesterday's update, and we have already pushed a fix. It will land in the next TestFlight update. Sorry!

You can downgrade to a previous beta build within the TestFlight app if it helps.

**Comment by agottardo** [comment]
Looking into this

**Comment by epposan** [comment]
Version 1.59.74 appears to show all devices again. Thanks.
