### ISSUE TITLE
FR: Kubernetes Operator - documentation for Connector CustomResource

### ISSUE THREAD

**Issue by bkonicek** [tailscale/tailscale#11023]
### What are you trying to do?

It would be great to add documentation for the Connector CR to the Kubernetes-Operator [documentation](https://tailscale.com/kb/1236/kubernetes-operator) page defining the supported configurations.

### How should we solve this?

Update the documentation page with a reference for the Connector spec

### What is the impact of not solving this?

It's difficult to know how to use it without reading through the CustomResourceDefinition.

**Comment by catzkorn** [comment]
Hi,

I have flagged this with our technical writing team.

**Comment by irbekrm** [comment]
We now autogenerate CRD docs and commit them to https://github.com/tailscale/tailscale/blob/main/k8s-operator/api.md.

This is not yet linked from or synced to the website docs, but eventually should be.

**Comment by bkonicek** [comment]
Thanks, that's perfect!

**Comment by irbekrm** [comment]
I have also linked the auto-generated docs in the GitHub repo from our website docs, hopefully that'll be convenient for folks to use.

Thanks you for opening this issue @bkonicek !
