### ISSUE TITLE
UFW not working on Tailscale interface

### ISSUE THREAD

**Issue by vincentherrera** [tailscale/tailscale#11033]
### What is the issue?

Tested on three separate occasions.
Raspberry Pi 4 with:
- raspbian lite 32bit
- again on fresh install of same
- then on Ubuntu Server 22.04 32bit.

UFW state: default deny incoming; default allow outgoing; enabled. Verified by ```UFW status verbose```
SSH state: active; enabled. Tested with UFW disabled to ensure SSH configured and working as desired.

With UFW enabled as described, and no other rules, all incoming traffic [ports 22; 80; 8080] on Tailscale interface is permitted. This is the same for hosts on same LAN, and separate LANs. However, other interfaces DENY incoming traffic.

### Steps to reproduce

Using Raspberry Pi imager, install OS to SD card.
Insert SD card into RPi 4, and power on.
``` sudo apt-get update && sudo apt-get dist-upgrade -y ```
``` sudo apt-get install ufw ssh -y ```
``` sudo systemctl start ssh && sudo systemctl enable ssh ```
Attempt to SSH to new machine. Should allow ssh connection.
``` sudo ufw default deny incoming ```
``` sudo ufw default allow outgoing ```
``` sudo ufw enable ```
``` sudo ufw reload ```
``` sudo ufw status verbose ``` To ensure no other rules are present.
Attempt to SSH to new machine. Should deny ssh connection.
Use Tailscale provided install script to install Tailscale.
``` sudo tailscale up ```
Copy/paste web link, and confirm node to join Tailnet.
Attempt to SSH to new machine. Should deny ssh connection. At this point, in my experience this and all connections on tailscale interface are allowed despite UFW rules being in place.

### Are there any recent changes that introduced the issue?
No

### OS
Ubuntu Server 22.04 32bit
Raspian Lite 32bit

### OS version
Ubuntu Server 22.04 32bit
Raspian Lite 32bit
[Kernel v6.1](https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2023-12-11/2023-12-11-raspios-bookworm-armhf-lite.img.xz)

### Tailscale version

1.58.2 for all tested hosts

### Other software

Debian/Ubuntu UFW  aka - uncomplicated firewall

### Bug report

BUG-e2aadaa46e3c7a040b5e099fa96e504f20294882f48c70fcb9155ce4f23c2f92-20240204190557Z-492293a30957c25b

**Comment by raggi** [comment]
> Attempt to SSH to new machine. Should deny ssh connection. At this point, in my experience this and all connections on tailscale interface are allowed despite UFW rules being in place.

This is intentional behavior - we install a rule to allow traffic on tailscale0, as there is an ACL controlled filter inside tailscaled itself.

If we remove our rule that allows traffic, it becomes a source of friction for many users who do not know how to manage ufw, and find that connections over tailscale are not working.

**Comment by raggi** [comment]
These docs are out of date and require a refresh: https://tailscale.com/kb/1077/secure-server-ubuntu-18-04#step-4-allow-access-over-tailscale

This relates to https://github.com/tailscale/tailscale/issues/9084

cc @KevinLiang10

**Comment by vincentherrera** [comment]
Thank you for this insight. I will explore Tailscale's ACL documentation and adjust accordingly.
Closing, as this is a feature and not a bug.

**Comment by supertr0n** [comment]
18 months later, the docs are still out of date. [The article mentioned above](https://tailscale.com/kb/1077/secure-server-ubuntu-18-04#step-4-allow-access-over-tailscale) still tells users to add this UFW rule:

`sudo ufw allow in on tailscale0`

On Debian (at least) this appears to do absolutely nothing. Worse, it suggests that UFW is doing filtering of Tailscale traffic when it is not. The decision making behind this change ("user convenience") and lack of attention to detail about this in the docs is a little concerning.

**Comment by vincentherrera** [comment]
> 18 months later, the docs are still out of date. [The article mentioned above](https://tailscale.com/kb/1077/secure-server-ubuntu-18-04#step-4-allow-access-over-tailscale) still tells users to add this UFW rule:
> 
> `sudo ufw allow in on tailscale0`
> 
> On Debian (at least) this appears to do absolutely nothing. Worse, it suggests that UFW is doing filtering of Tailscale traffic when it is not. The decision making behind this change ("user convenience") and lack of attention to detail about this in the docs is a little concerning.

Initially, I felt the same way. However, tailscales ACLs seem to work as advertised, so I am content. I just recently noticed that they have even added a GUI for the ACLs instead of just the json editor, so the barrier of entry is somewhat lower now. [I found this blog post to be the most helpful.](https://blog.patshead.com/2022/10/is-it-time-for-you-to-set-up-tailscale-acls.html)

**Comment by pgervais** [comment]
I ran into the same issue today, and the documentation page previously mentioned (https://tailscale.com/kb/1077/secure-server-ubuntu) still claims that you need to open ports on the local firewall for tailscale to work.

I understand that the very reason for tailscale to exist is to bypass firewalls. However, working around the rules of the *local* firewall broke my mental model which is: tailscale connects machines as if they were on the same local network. Being on the same local network doesn't mean there is no firewall at all.

Taking a slightly different perspective: the fact that tailscale has ACLs proves there is a need for firewall rules on each tailscale node. Why preventing users from using the local firewall they already have and know how to use? One solution could be to have a flag on tailscaled to enable using a local firewall like ufw or shorewall to filter traffic on the tailscale interface.

**Comment by vab2048** [comment]
What rules does tailscale add by default? It is not clear how to inspect these and the documentation does not say either.
Not being able to control this via `ufw` seems wrong.
