### ISSUE TITLE
Tailscale (on Mac) not reconnecting after update

### ISSUE THREAD

**Issue by nim8562** [tailscale/tailscale#11043]
### What is the issue?

I had troubles with connecting to Tailscale and after deleting it and downloading again with new version I cannot connect. 
tailscale status gives `failed to connect to local Tailscale service; is Tailscale running?`
I tried to remove all tailscale files and upload new or unstable version but it did not succeed. It always stands as "Not connected"

### OS

macOS

### Tailscale version

1.58.2

**Comment by agottardo** [comment]
- What macOS version are you running?
- Did you reboot your Mac after reinstalling Tailscale?
- Did you switch from the Mac App Store variant to the Standalone variant of the client, or vice versa?
- Did you try deleting the Tailscale configuration in the macOS VPN settings and re-launching the app?

**Comment by nim8562** [comment]
> * What macOS version are you running?
> * Did you reboot your Mac after reinstalling Tailscale?
> * Did you switch from the Mac App Store variant to the Standalone variant of the client, or vice versa?
> * Did you try deleting the Tailscale configuration in the macOS VPN settings and re-launching the app?

macOS version is Sonoma 14.3
Yes, I rebooted it several times
I used only Standalone variant
Yes, I tried to delete in in VPN in setting and then launch - nothing happened

I thought that there could be some files  left because I first tried to upload it with homebrew, but I deleted everything (I suppose)

**Comment by agottardo** [comment]
Please contact support@tailscale.com, and make sure to attach a sysdiagnose taken from your Mac (you can run `sudo sysdiagnose` in the Terminal app to generate one).

**Comment by ryanwwest** [comment]
I'm having basically the same issue after trying the above steps. Guess I shouldn't have upgraded to Sonoma 14.5.

**Comment by agottardo** [comment]
@ryanwwest 14.5 is fully compatible with Tailscale. There is something else going on with your setup that might have changed since the update. We cannot diagnose system compatibility issues without a sysdiagnose, and you should take one to support since sharing one here is not advisable (sysdiagnose files contain confidential private information).
