### ISSUE TITLE
FR: Greater control of Windows application settings through registry keys

### ISSUE THREAD

**Issue by joel-wraight-ac** [tailscale/tailscale#11042]
### What are you trying to do?

Hi,

We are a business customer and have a reasonably large TS environment. Mostly Windows. I am the sysadmin. We can control some of the settings for Tailscale through registry keys such as hiding the test menu, network devices menu etc. etc.

We are in need of being able to control the last few settings through reg keys that can't currently be controlled. More specifically, enforcing the options in the 'preferences' menu - 'Use Tailscale DNS settings', 'Use Tailscale subnets' and most importantly 'Automatically install updates'. I currently have a PowerShell script to deploy and upgrade Tailscale, but if we can enforce the 'Auto-Update' feature I can take version control out of the PS scripting.

Thanks,

Joel Wraight

### How should we solve this?

New reg key options to enforce client application settings

### What is the impact of not solving this?

Diminished control of product in larger Windows environments. Inability to enforce auto-updates company wide without manually going to each endpoint and ticking the box.

**Comment by timtailscale** [comment]
This functionality is now possible using MDM system policies as described here: https://tailscale.com/kb/1315/mdm-keys. Specifically the `UseTailscaleDNSSettings`, `UseTailscaleSubnets`, `CheckUpdates`, and `InstallUpdates` policy keys should allow control of the preferences that you mentioned.
