### ISSUE TITLE
FR: how to set pre-proxy socks5 

### ISSUE THREAD

**Issue by toohandsome** [tailscale/tailscale#11051]
### What are you trying to do?

My machine exists in a restricted network and requires the use of a socks5 proxy to connect to the network;

But I haven't found any place to set up proxies;

I tried using the proxifier to proxy tailscale traffic, but I received the following error message:
```
Dial TCP: lookup invalid d IP: no such host
```

![image](https://github.com/tailscale/tailscale/assets/46422252/d1a780b5-68da-4e80-a057-3b66047d743c)

The proxifier displays 

 ```
0 bytes sent, 0 bytes received
```

![image](https://github.com/tailscale/tailscale/assets/46422252/7fa2d457-d1de-47d5-9250-0de04a02760c)

V2rayn shows that the traffic has been received and forwarded
 ``` 
accepted TCP: 116. *. 254:1 * * *: 4 [direct]
```

![image](https://github.com/tailscale/tailscale/assets/46422252/e1a3ef02-2fe6-4c0f-9dfb-810036115c39)

### How should we solve this?

support pre-proxy socks5

**Comment by bradfitz** [comment]
tailscaled should be respecting the ALL_PROXY environment variable to use SOCKS5.

**Comment by hellt** [comment]
If I want to set the proxy only for the tailscale service, should I modify the systemd service to have a line like this?

<img width="973" alt="image" src="https://github.com/tailscale/tailscale/assets/5679861/40d56bb4-3e78-4bff-b8cc-332064c19867">


I set it up, but I don't see tailscale using the provided proxy
