### ISSUE TITLE
Start on Login 

### ISSUE THREAD

**Issue by kuki68ster** [tailscale/tailscale#11069]
### What is the issue?

Option "Start on Login" not working on Mac OS Sonoma 14.3 (23D56)...

### Steps to reproduce

1. Install Tailscale
2. Select "Start on Login"

### OS version

14.3 (23D56)

### Tailscale version

1.58.2

### Other software

None, excpet Adguard DNS certificate...

**Comment by comatose-tortoise** [comment]
Same problem here.

**Comment by agottardo** [comment]
This was fixed in the 1.60 update released today. Please let me know here if the issue persists.
