### ISSUE TITLE
FR: Allow custom DoH Servers and add ControlD ID Option

### ISSUE THREAD

**Issue by Coder84619** [tailscale/tailscale#11067]
### What are you trying to do?

I am no longer using NextDNS, and would like to use a custom DoH URL for DNS. Ideally, I'd also like a 'ControlD' configuration option just like NextDNS. 

### How should we solve this?

Allow inputting a HTTPS URL for DoH DNS services. Or input my ControlD ID. 

### What is the impact of not solving this?

Insecure DNS.

**Comment by bradfitz** [comment]
Control D is tracked in #7946.

Generic DoH is tracked in #74.
