### ISSUE TITLE
Can't SSH into device using embedded Tailscale from tsnet package

### ISSUE THREAD

**Issue by Mendes11** [tailscale/tailscale#11075]
### What is the issue?

Hi all,

I'm trying to embed Taliscale in my GO application that runs in a RaspberryPI 4. 
The core functionality is to allow SSH access into the device, and it works great when I manually install Tailscale in the PI OS, log in with `sudo tailscale up --ssh`, and run `tailscale ssh xxx`.

The problem arises when trying to do the same with the embedded version. The first issue is that there's no option to enable SSH in `tsnet.Server`, but this can be fixed if I enable the web UI and toggle the enable SSH option there. Once that's done, the SSH label appears in Tailscale console, but when trying to connect to it, using the same command, it hangs forever. There are no error logs, it just stays there trying to connect forever.

### Steps to reproduce

1 .Create an application that imports `tsnet.Server`.
2. Connect into the Tailnet with the WebUI enabled
3. Open the UI, go to the SSH section, and enable it.
4. Try to SSH in

### OS

Linux

### OS version

PI OS / bullseye

### Tailscale version

1.58.2

### Bug report

BUG-1487c0aaafd39759ce8af8733fde2ffac50426013f28e67faaefdea5d4dea6cb-20240208203100Z-298085f81f717930

**Comment by evilhamsterman** [comment]
It hangs forever because SSH requires a terminal running a shell on the other side. TSNET doesn't provide that and setting SSH on the device doesn't magically enable that, you'd still have to wire up your app to create a pty, load a shell like bash, and then read/write to the pty STDIN/OUT/ERR. Even the tailscale client doesn't do that it just sits between the OpenSSH server and handles authentication and transport. If your goal is to ssh to your device and you can to so with `tailscale up --ssh` why can't you just do that?

**Comment by Mendes11** [comment]
@evilhamsterman 
Thanks for the insight on how tailscale deals with SSH internally. Now it makes sense why it doesn't and won't work. 
`tailscacle up` won't work here because I'm trying to get into a Raspberry PI that somehow failed to install tailscale, and now it has a broken APT that keeps returning the following error:

```
+ mkdir -p --mode=0755 /usr/share/keyrings
+ curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg
+ tee /usr/share/keyrings/tailscale-archive-keyring.gpg
+ + tee /etc/apt/sources.list.d/tailscale.list
curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list
+ apt-get update
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.
```

Given I don't have physical access to it, I'm trying to find a way in and this was my first attempt.

**Comment by evilhamsterman** [comment]
Sorry I think you need to look elsewhere tsnet itsn't going to help you with this issue
