### ISSUE TITLE
Mobile key expiry banner persists after reauth

### ISSUE THREAD

**Issue by sloane-ts** [tailscale/tailscale#11084]
### What is the issue?

When an android or iOS node receives the key expiry notice, after reauth, the banner persists. Closing and reopening the Tailscale mobile app removes the expiry notice banner. This can be reproduced on both iOS and Android. 

Banner:

![image](https://github.com/tailscale/tailscale/assets/133054059/64906d2c-1b43-48ca-a9a1-f9a9183e2bf2)

### Steps to reproduce

- Key expiry notice is triggered on mobile
- Go through prompts for reauth
- expiry banner persists
- close/reopen app to remove banner

Screen recording, iOS:

https://github.com/tailscale/tailscale/assets/133054059/7ecde1c7-c334-4c4b-82f2-da2b2e67e11a

### Are there any recent changes that introduced the issue?

n/a

### OS

iOS, Android

### OS version

iOS 17.3.1, Android 14.0

### Tailscale version

1.58.2

### Other software

n/a

**Comment by agottardo** [comment]
We'll fix this in 1.62 to minimize risk.

**Comment by golly-gosh** [comment]
> We'll fix this in 1.62 to minimize risk.

Looks like it missed 1.62.0 for Apple iOS - do we have a new version on the roadmap for this fix?

**Comment by agottardo** [comment]
Fix is landing in 1.66.

**Comment by golly-gosh** [comment]
> Fix is landing in 1.66.

Changes made in 1.66 and 1.66.3 but now can no longer reauth via the banner at all, as we don't get the pop-out message saying '"Tailscale" Wants to Use "tailscale.com" to Sign In - Cancel | Continue' just has the 9 grey dots change colour and the status bar state "Starting..." forever.

![image](https://github.com/tailscale/tailscale/assets/160804055/ae7c5596-ed7c-4204-bdc2-b03225d6e95e)

**Comment by agottardo** [comment]
Investigating this...

**Comment by garrett-ts** [comment]
An open issue for this is here #12178

**Comment by golly-gosh** [comment]
> An open issue for this is here #12178

**❤**
