### ISSUE TITLE
Usare l'accesso da remoto senza tailnet

### ISSUE THREAD

**Issue by xlucaaz** [tailscale/tailscale#11096]
### What are you trying to do?

Buongiorno, sto usando tailscale per accedere da remoto al mio NAS synology perchè ho la connessione starlink e non posso aprire le porte del router. 
Tailscale funziona egregiamente, ma nel caso volessi condividere qualcosa con un amico, esso dovrebbe far parte della mia tailnet per potervi accedere... c'è il modo di condividere senza usare la tailnet, ma passando comunque da tail scale per aggirare il problema starlink?

**Comment by agottardo** [comment]
Si. Puoi condividere un dispositivo nella tua tailnet con un altro utente. L'unico requisito è che l'utente con il quale condividi il dispositivo deve a sua volta utilizzare Tailscale ed avere una propria tailnet.

Questa funzionalità si chiama node sharing e puoi seguire le [istruzioni](https://tailscale.com/kb/1084/sharing) qui per configurarla. Una volta completata la configurazione, il dispositivo apparirà sia nella tua che nella sua tailnet.
