### ISSUE TITLE
Sonoma 14.3.1 - cannot installed tailscale tailscaled command line

### ISSUE THREAD

**Issue by phillipmcmahon** [tailscale/tailscale#11099]
### What is the issue?

Following the install instructions gives the following error

`➜  ~ sudo $HOME/go/bin/tailscaled install-system-daemon

install-system-daemon not available on darwin
➜  ~ 
`

### Steps to reproduce

Follow the documented installation instructions

### OS

macOS

### OS version

Sonoma 14.3.1

### Tailscale version

Latest pulled

### Other software

I recently updated macOS.

**Comment by bradfitz** [comment]
@oxtoacart, this is a regression from 993acf4475b22d693f210ae08cd8de57e2452d28 which removed the pointers from the registered func in cmd/tailscaled. They were critical for the initialization to work correctly.

**Comment by bradfitz** [comment]
@phillipmcmahon, if you install at a released version or the commit right before (2e404b769dc3164a8e78547c86a3e3451ed3f306) then it'll work.

**Comment by oxtoacart** [comment]
@phillipmcmahon I've merged a fix, you should be good to go as of 55b372a79fd3a23fc4a26af5be08acdb27f52f0f.

**Comment by phillipmcmahon** [comment]
> @phillipmcmahon I've merged a fix, you should be good to go as of [55b372a](https://github.com/tailscale/tailscale/commit/55b372a79fd3a23fc4a26af5be08acdb27f52f0f).

Many thanks for such a quick fix. All is working as expected.
