### ISSUE TITLE
FR: When fast user switching will become available in Tailscale app on Android devices?

### ISSUE THREAD

**Issue by psyhomb** [tailscale/tailscale#11104]
### What are you trying to do?

https://tailscale.com/kb/1225/fast-user-switching

### How should we solve this?

Implement this feature per [documentation](https://tailscale.com/kb/1225/fast-user-switching).

### What is the impact of not solving this?

Tailscale users won't be able to use multiple accounts (tailnets) in easy manner on Android devices.

**Comment by bradfitz** [comment]
Work is underway on overhauling the Android app.

**Comment by psyhomb** [comment]
Thank you for your answer, is there any estimate when this feature might be available?

**Comment by catzkorn** [comment]
We will update this issue when we have an update to share.

**Comment by agottardo** [comment]
Implemented in https://github.com/tailscale/tailscale-android/pull/209

**Comment by psyhomb** [comment]
Thank you, it works like a charm.
