### ISSUE TITLE
Error while importing tailscale.com/tsnet for v1.58.x

### ISSUE THREAD

**Issue by cohix** [tailscale/tailscale#11107]
### What is the issue?

When importing `tailscale.com/tsnet` in a Go project, the following error is reported by the Go language server and `go build`:
```
../../../go/pkg/mod/tailscale.com@v1.58.2/wgengine/netstack/netstack.go:25:2: found packages refs (refcounter.go) and refs_template (refs_template.go) in /Users/cohix-14/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240210010211-cd6c646b1a9a/pkg/refs
```
### Steps to reproduce

Create a Go program, `go get tailscale.com/tsnet`, use the package in `main.go` and run `go build`.

### OS

Other

### OS version

Go 1.21.x and Go 1.22

### Tailscale version

1.58.2

**Comment by cohix** [comment]
Seems like this is technically an issue in gvisor's repo, but it still prevents TS from building.

**Comment by bradfitz** [comment]
Did you update gvisor past what tailscale supports?

**Comment by bradfitz** [comment]
Yeah, looks like you updated gvisor to its Bazel branch, not its cmd/go-compatible "go" branch.

**Comment by cohix** [comment]
That's strange, I never directly updated gvisor, but I think it got caught up in `go get -u ./...`

Reverting the result of that command and just running `go get -u tailscale.com` works just fine so I'll close this. Sorry for the noise!
