### ISSUE TITLE
Need to open app once to make quick tile working

### ISSUE THREAD

**Issue by alexchiu100014** [tailscale/tailscale#11103]
### What is the issue?

Quick tile is not working as normal.
I expected it should enable Tailscale after I toggle it.
But in reality, I need to open the app first or it will not work.

### Steps to reproduce

1. Disable VPN
2. Wait for Android killed Tailscale app (or force stop the app)
3. Then, go to Quick Center and toggle Tailscale
4. And you'll see that nothing happened, VPN indicator didn't appear.

https://github.com/tailscale/tailscale/assets/48598830/57a047a5-5c2d-44ab-8743-d045357c14a8

### OS

Android

### OS version

Android 14 (Nothing OS 2.5.1a)

### Tailscale version

1.58.2

### Other software

Android would disable any currently running VPN if you enable another one.

### Bug report

BUG-4cb6a53c3e5cffff122a43e33ad1f32a55c9f2eb21d848d7b1bad674e0fef525-20240211002110Z-d53200527c53e4de

**Comment by Aaroneisele55** [comment]
+1, I also have the Issue on Android 13 and it's screwing up my Internet connection when the system kills the Tailscale App, even though it is set as Always-On-VPN.

BUG-84f010f405bfba67ac0bb75c99de5f25efd35ea144cb7014854ccfc410a85a6c-20240215043535Z-c43f21780cff3d11

**Comment by kari-ts** [comment]
This is fixed by https://github.com/tailscale/tailscale-android/pull/143
