### ISSUE TITLE
cmd/tailscale: hide alpha "share" from SUBCOMMANDS help output

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#11115]
We should hide the "share" help line from the SUBCOMMANDS section while it's in Alpha.

(To let it only be usable if you know it's there.)

Or include the output line if `envknob.UseWIPCode` is true. (but don't require `envknob.UseWIPCode` to use it...)

/cc @oxtoacart

**Comment by oxtoacart** [comment]
Fixed with https://github.com/tailscale/tailscale/commit/d0ef3a25dfd36ce9634160cf500aa3f7620ac25d
