### ISSUE TITLE
FR: make web address clickable

### ISSUE THREAD

**Issue by jimt** [tailscale/tailscale#11151]
### What are you trying to do?

When exploring the `tailscale web` feature, I see that it displays:
  `starting tailscaled web client at 100.119.131.96:5252`

### How should we solve this?

If the address were rendered as a link:
 `starting tailscaled web client at http://100.119.131.96:5252`
it would be a clickable link in my terminal emulator/desktop environment.

### What is the impact of not solving this?

Currently, I either have to cut/paste the IP address or manually type the hostname.I

**Comment by willnorris** [comment]
fixed in #11164.  Thanks for the suggestion!
