### ISSUE TITLE
Install script on Alpine needs to start the service as well as add it to default

### ISSUE THREAD

**Issue by peterkeen** [tailscale/tailscale#11161]
### What is the issue?

When I run this command on an Alpine 3.19 install, I see the following:

```
home:~# curl -fsSL https://tailscale.com/install.sh | sh
Installing Tailscale for alpine 3.19.1, using method apk
+ apk add tailscale
(1/2) Installing tailscale (1.54.1-r0)
(2/2) Installing tailscale-openrc (1.54.1-r0)
Executing busybox-1.36.1-r15.trigger
OK: 327 MiB in 88 packages
+ rc-update add tailscale
 * service tailscale added to runlevel default
+ set +x
Installation complete! Log in to start using Tailscale by running:

tailscale up
home:~# tailscale up
failed to connect to local tailscaled; it doesn't appear to be running
home:~# rc-service tailscale start
 * Caching service dependencies ... [ ok ]
 * /var/log/tailscaled.log: creating file
 * Starting tailscaled ... [ ok ]
home:~# tailscale up

To authenticate, visit:

        https://login.tailscale.com/a/<TOKEN>
```

Note that the install script runs `rc-update add tailscale`, which is correct, but that does not automatically start the service until the next reboot. The script should also do `rc-service tailscale start` to start up `tailscaled`

### Steps to reproduce

1. Install Alpine 3.19
2. `curl -fsSL https://tailscale.com/install.sh | sh`
3. `tailscale up`

### Are there any recent changes that introduced the issue?

Not that I know of. This has been happening for a while.

### OS

Linux

### OS version

Alpine 3.19 but I think any Alpine will exhibit the behavior

### Tailscale version

1.54.1

### Other software

```
home:~# cat /etc/apk/world
alpine-base
alpine-baselayout
alpine-keys
apk-tools
bash
busybox
curl
doas
docker
libc-utils
logrotate
mc
nano
newt
openssh
rsync
tailscale
home:~# cat /etc/apk/repositories 
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
home:~# 
```

### Bug report

BUG-7b430ce98d446b14a660a83673cdd00a2ab4ea630eef3c793cbd441304a5996b-20240216153545Z-4d8db8dad7dfeae1

**Comment by kelivel** [comment]
Thanks for flagging! We'll get this updated.
