### ISSUE TITLE
Impossible to change server on firestick tv

### ISSUE THREAD

**Issue by ndx1905-github** [tailscale/tailscale#11172]
### What is the issue?

To set up the android client with headscale or any server that is not tailsclae, you are required to click multiple times on the burger icon until it’s possible to add the alternative server URL instead of the Tailscale one. This requires to be able to click on the burger go back click again go back etc.
this gesture is impossible on a firetv stick as you only have a remote that lets you click but when you go back you’re taken out of the app to the app launcher. If you click again you still are at the same place and cannot click multiple times on the burger. If you close the app and redo the burger button it only counts as one.

### Steps to reproduce

Use a firestick tv with a remote control. 
click on the burger icon
Try to go back, it takes you back to the launcher and out of the Tailscale app 
It is not possible to click multiple times on the burger icon which is necessary to access the alternative server url

### OS

Android

### OS version

Firetv OS 6

### Tailscale version

1.58.2

**Comment by linus-ha** [comment]
Workaround: Use a Bluetooth mouse. There are also apps for Android to emulate one, if you don't have one.

I do agree, this should be fixed. In general: The remote's back button is not closing any menus.

**Comment by ndx1905-github** [comment]
Hey thanks for the answer.
I've used a BT mouse and was able to have the change server menu.
However, when I click on the field to add the new server url, the firetvkeyboard pops up and never goes away even after I have typed the server address.
If I click muttiple times on the "delete" button (just because nothing else works), the app crashes and I'm back on the launcher page.

**Comment by ndx1905-github** [comment]
Update :
It works if you use the remote app for the firetv that provides a keyboard. You can then type without the virtual keyboard popping up.

**Comment by agottardo** [comment]
@ndx1905-github This should be resolved in the latest Android app versions (1.68.0+). Please mention me here if you are still experiencing issues and I can reopen this.

**Comment by cat24max** [comment]
Custom coordination servers are still broken in 1.72.

**Comment by levinuss** [comment]
@agottardo Still broken in 1.78.1

**Comment by mathmaniac43** [comment]
I just ran into this as well. With the normal remote or a USB keyboard, it doesn't let me get past the text box for the custom server URL to click the "Add Account" button. I am going to try a mouse now.
