### ISSUE TITLE
iOS App Fast User Switch on Alternate Coordination Server Urls

### ISSUE THREAD

**Issue by dennisoderwald** [tailscale/tailscale#11179]
### What is the issue?

In the macOS version, it is possible to switch between several custom servers. This is not possible on iOS. You always have to change the "Alternate Coordination Server Url" in the settings and then the connection is also possible directly, without re-authentication. However, it is not possible to do this via the iOS app (in the latest version (1.60.0)).

### Steps to reproduce

Set up more than one connection with a custom login server and try to switch users.

### OS

iOS

### OS version

1.60.0

**Comment by agottardo** [comment]
A fix is available on TestFlight, and on the way for 1.66.
