### ISSUE TITLE
Dockerhub tailscale/tailscale:latest and tailscale/tailscale:stable is actually 1.61.11 unstable

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#11204]
### What is the issue?

`tailscale/tailscale:latest` in Dockerhub has always been stable versions (1.58, 1.60, etc). The latest push, though, is of 1.61.11, which is unstable.

In fact, the latest version’s digest, `de3f48c7684c`, shows up as `:latest`, `:v1.61.11`, `v1.61`, and most surprisingly, `:stable`, even though it’s not stable.

### Steps to reproduce

Go to https://hub.docker.com/r/tailscale/tailscale/tags.

Or pull the Dockerhub `tailscale/tailscale:stable` image.

### Are there any recent changes that introduced the issue?

This was pushed yesterday.

### OS

Other

**Comment by irbekrm** [comment]
Hi, thanks for alerting us on this.

This was due to (my) human error, pushing from the wrong tag.
I've now pushed the actual `v1.60` and `latest` too is now `v1.60`.

For the record, there the changes between the two are minimal and should not affect tailscale running in containers.
