### ISSUE TITLE
Docker mod DNS resolution broken

### ISSUE THREAD

**Issue by KienHui** [tailscale/tailscale#11210]
### What is the issue?

Using tailscale docker mod inside `linuxserver/homeassistant:latest`, which is based on Alpine 3.19. Previous version of the container was running on 3.18, and was working fine. Container auto-updated, and DNS resolution broke for MagicDNS. Listed server for namespace resolution is 127.0.0.11 inside the container. NXDOMAIN returned for *.ts.net domains. `tailscale ping` resolves machine name fine.

### Steps to reproduce

1. create `linuxserver/homeassistant:latest` container
2.  install tailscale docker mod (`ghcr.io/tailscale-dev/docker-mod:main`)
3. `nslookup` another node

### Are there any recent changes that introduced the issue?

`linuxserver/homeassistant` updated base image.

### OS

Linux

### OS version

Alpine 3.19

### Tailscale version

1.60

### Bug report

BUG-5882849d0fbd692226ce944f21864a04887cd615e08cf397236c1451608a6a6e-20240223160358Z-6db8f45754385156

**Comment by knyar** [comment]
Thank you for your report. Note that `docker-mod` is part of the [tailscale-dev](https://github.com/tailscale-dev) Github organization that hosts community-led projects, and it's not something that we support via this repo. I would suggest creating a new issue in that repo to make sure it gets attention of other users of `docker-mod`.

You might also consider using our [official docker image](https://tailscale.com/kb/1282/docker) instead.

I'd hate to close this issue without any helpful information, so I did a quick Github search and found some discussion about MagicDNS on Alpine 3.19 in #10540, which I believe is related to nftables. Perhaps forcing the Tailscale client in `docker-mod` to use nftables would be a sensible thing to try (`TS_DEBUG_FIREWALL_MODE=nftables`).

I hope this helps, and thanks again for reaching out.
