### ISSUE TITLE
Wildcard domain name resolution and certificate issuance

### ISSUE THREAD

**Issue by masx200** [tailscale/tailscale#11229]
### What are you trying to do?

Wildcard domain name resolution and certificate issuance

### How should we solve this?

dns resolve *.mydomain.ts.net to my tailscale ip and certificate issuance

**Comment by bradfitz** [comment]
There are a few near dups of this. #7081 is the most explicit.

But doing this in the general case is difficult: different nodes in the tailnet may be owned by different users/tags with different permissions and can't just hand out the wildcard cert to everybody.
