### ISSUE TITLE
DOC: Integrations > NAS > Truenas: incorrect information 

### ISSUE THREAD

**Issue by fabianmuehlberger** [tailscale/tailscale#11237]
### What is the issue?

The [documentation](https://tailscale.com/kb/1307/nas#truenas-and-freenas) states:

> TrueNAS and FreeNAS
> These devices are based on FreeBSD, and users have reported that Tailscale’s FreeBSD version works on these platforms. FreeBSD support for Tailscale is community-maintained, and [the client is available in FreshPorts](https://www.freshports.org/security/tailscale/).

This is not entirely correct since there is a TruenNAS SCALE version based on Ubuntu, and that uses [Tailscale docker](https://hub.docker.com/r/tailscale/tailscale), present on [dockerhub](https://hub.docker.com/r/tailscale/tailscale) and maintained by Tailscale.

**Comment by kelivel** [comment]
Thanks @fabianmuehlberger! We've got your request and have filed it internally with our docs team. We'll take a look to see if we can make some improvements here.
