### ISSUE TITLE
tailscale not loading  web page of my router

### ISSUE THREAD

**Issue by delta010** [tailscale/tailscale#11236]
### What is the issue?

my tailscale set has 2 subnet routes `192.168.0.0/24,192.168.1.0/24`. I can access every service in these subnets without any problem except `192.168.1.1 and 192.168.0.1` these IPs are my modem and router. I can ping `192.168.1.1 and 192.168.0.1` without any problem, but the web UI is not loading 

![Screenshot 2024-02-25 093723](https://github.com/tailscale/tailscale/assets/29528880/8bc4556e-236a-4c68-afc2-001e91052a30)

![Screenshot 2024-02-25 093746](https://github.com/tailscale/tailscale/assets/29528880/ac1c69e1-6758-4d2f-aac5-c0d87cf4b9ee)

ping result 

![Screenshot 2024-02-25 094231](https://github.com/tailscale/tailscale/assets/29528880/ed35b0ae-d764-47f9-a694-d4d14c5a0d5d)

### OS

Linux, Windows, Android

### OS version

Debian 12,Windows 11

### Tailscale version

1.60.0

### Bug report

BUG-9eedd333e40f7220b6d819e5994e401be703419f09c00810d3fdab9669e961c0-20240225040558Z-e5a53049ed8673e7

**Comment by kelivel** [comment]
Can you try opening those pages in a private browser tab to rule out a browser caching issue?

**Comment by delta010** [comment]
after opening it in a private browser no result

**Comment by kelivel** [comment]
Drop a line with our Support team at http://www.tailscale.com/support so we can get a little more information about your devices and tailnet and we'll continue troubleshooting there.

**Comment by jakcyl** [comment]
hi, i have the exact same issue, how was it solved?

**Comment by LuichiP** [comment]
Hello, mee too, i have movistar router, any solution on that? thanks

**Comment by JotaEmeDiaz** [comment]
Same here! Disconnecting Tailscale on my Android phone makes it work on Windows — but I still can't access my router from the phone
