### ISSUE TITLE
Different ACLs based on device trust level

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#1124]
**Is your feature request related to a problem? Please describe.**

A customer has multiple categories of servers, some of which are a test environment and others are a production environment. They would like to institute a policy that employees can use personal devices (BYOD) to access the test environment but should not be able to access the production environment unless using a company-owned device.

**Describe the solution you'd like**

ACL specifications include an optional device trust level and each user's devices is assigned a trust level. Access through an ACL requires both an authorized user and a device with the correct trust level.

**Describe alternatives you've considered**

ACLs based on users are insufficient because this describes a scenario where a user should only sometimes be allowed to access a server, depending on which device they're using.

An alternative implementation of this that's more general would be to allow some sort of named label on each device (separate from groups and tags, which are terms we already use with different meanings), which could map to trust level, or could be used in some other way. ACLs could simply require the presence of a particular label.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nz2p)

**Comment by apenwarr** [comment]
Yup, there are several nice things we could do with this. A slightly different variant is an ACL level for "I trust the machine, but there is no current user." That could let people eg. log into Active Directory on a certified corp device by talking to an isolated AD-server-only network.

Another idea I had was "sudo mode": you could escalate your permissions temporarily by re-authenticating, for doing highly sensitive operations. Or even a "break glass mode" which would sound the klaxons but allow you to bypass ACLs entirely, or something.

**Comment by knyar** [comment]
I believe this has been addressed by [device posture](https://tailscale.com/kb/1288/device-posture) attributes, API and integrations.
