### ISSUE TITLE
[Debian Packages] Dependency on `iptables` is unneeded?

### ISSUE THREAD

**Issue by Kunsi** [tailscale/tailscale#11242]
### What is the issue?

The official debian packages currently have `Depends: iptables` in them. This interferes with people running `nftables` instead of `iptables` (which is the default in newer debian versions).

Looking at the code, tailscale should work directly with nftables as well. The debian packages should reflect that in their dependencies.

### Steps to reproduce

1. Try to install tailscale according to https://tailscale.com/kb/1174/install-debian-bookworm
2. See `iptables` listed as `additional packages that are going to be installed`

### OS

Linux

### OS version

debian 12.4 (arm64)

**Comment by bradfitz** [comment]
It's needed on some systems still.

We previously tried to do this and had to revert it in e499a6bae8f02f9acd4709c0b052ae9e2d2195df which says:

```
			Depends: []string{
				// iptables is almost always required but not strictly needed.
				// Even if you can technically run Tailscale without it (by
				// manually configuring nftables or userspace mode), we still
				// mark this as "Depends" because our previous experiment in
				// https://github.com/tailscale/tailscale/issues/9236 of making
				// it only Recommends caused too many problems. Until our
				// nftables table is more mature, we'd rather err on the side of
				// wasting a little disk by including iptables for people who
				// might not need it rather than handle reports of it being
				// missing.
				"iptables",
```

See #9236
