### ISSUE TITLE
https access not being resolved

### ISSUE THREAD

**Issue by mapemono** [tailscale/tailscale#11240]
### What is the issue?

Setup: tailnet with a asustor nas and nextcloud running on it. Need to access nextcloud with https.
Tailscale on asustor up and running. TLS certificates are generated and shown under machines page in the dashboard.
MagicDNS is resolving "http://machine-name" but "https://machine-name.tailNNNN.ts.net" is not being resolved.

### Steps to reproduce

Install on Asustor NAS.
Create certificate for machine (Asustor).
Try to access in Browser (Windows 11, iOS) "http://machine-name" but not "https://machine-name.tailNNNN.ts.net"

### OS

Linux, Windows

### OS version

Asustor ADM 4.2.6.RPI1

### Tailscale version

1.60

### Bug report

BUG-5b0930c8aa0f6ae3d02b750b03e200a1d7720a58eb95a7b4ea71abfa667dd370-20240225145446Z-947e4d2c914ea00e

**Comment by kelivel** [comment]
After creating the HTTPS certificate did you import it to your Asustor certificate manager? Tailscale doesn't import automatically, and only creates the certificate files on the disk.

**Comment by kelivel** [comment]
After creating the HTTPS certificate did you import it to your Asustor certificate manager? Tailscale doesn't import automatically, and only creates the certificate files in local storage.

**Comment by mapemono** [comment]
When trying to import it into ADM cert manager I get the error: _Invalid certificate. (Ref. 5041)_
Maybe an asustor issue?

**Comment by kelivel** [comment]
Hm, I don't have an Asustor to try, but if you can glean more details from your logs send those to support@tailscale.com and I can take a look.

**Comment by mapemono** [comment]
Thanks for the offer.
Opened a bug with Asustor and got a reply:

![image](https://github.com/tailscale/tailscale/assets/161201483/d3dbd190-c7f0-4652-a3b3-ae0f69e9b204)

Will wait for their fix and close this issue.
Thanks.
