### ISSUE TITLE
Losing access to shared TS clients, when adding a tag to own client

### ISSUE THREAD

**Issue by rhjensen79** [tailscale/tailscale#11269]
### What is the issue?

When  my client is without any tags, then it can see the shared clients, from my other Tailscale net.
As soon as i add a tag to my client, is looses all access to the shared clients.

### Steps to reproduce

- share tailscale client from another tailscale net.
- run tailscale status and see the client is there.
- add tag to client
- run tailscale status and see the client is now gone

### Are there any recent changes that introduced the issue?

not that i know off

### OS

macOS, Other

### OS version

Sonoma 14.3.1, And Qnap latest.

### Tailscale version

1.5.2 and 1.6.0

### Other software

This seams to be generic. 
Running a unifi setup, but i cannot see, that would have anything to do with this.

### Bug report

BUG-9a197c4d760713dbd71772a40a12754d10a8f4c95f4d9fa48684e4241e4c7901-20240227203945Z-3fe98062c5684fd7

**Comment by rhjensen79** [comment]
Thanks @kelivel  

Is there any workaround, or any roadmap that might change that ? 
Trying to understand how to structure my ACL, if i cannot use tags.

**Comment by kelivel** [comment]
No specific workarounds with shared devices right now, but there is a feature request in our backlog for our product teams to triage. Drop a line with our Support team at http://www.tailscale.com/support with details about your use case and we're happy to take a closer look to see if there's a different way to approach this.

**Comment by rhjensen79** [comment]
Thanks. I think i will file in a feature request here, so i can track it as well. 
But thanks for your help.
