### ISSUE TITLE
Unable to Use Exit Node & Subnet Routing Functions in AppleTV tvOS

### ISSUE THREAD

**Issue by jimmybrancaccio** [tailscale/tailscale#11268]
### What is the issue?

This was originally reported by a customer (31661). I attempted to setup my AppleTV as an Exit Node and with a subnet router. I advertised the route `192.168.100.0/22` but couldn't access any devices on those local IPs from a device on a cellular network. I was able to use the Tailscale tailnet IPs though.

I believe this issue to be somewhat related to #10393.

### Steps to reproduce

1. Install Tailscale via the AppStore on your AppleTV. In my case I was using an AppleTV 4k model with the latest version of tvOS (17.3.0).
2. Login to your tailnet within the Tailscale app.
3. Once logged in go to the section in the app to advertise a subnet. In my case I advertised `192.168.100.0/22`.
4. Then enable the AppleTV to be an Exit Node.
5. In your Tailscale admin console make sure the AppleTV has been approved to be an Exit Node as well as the subnet routes its advertising have been approved.
6. On a secondary device not on the same network as the AppleTV, connect to your Tailnet. I used my iPhone on a cellular network.
7. In the Tailscale app on your device (iPhone in my case) select your AppleTV as your Exit Node.
8. I used the Blink.sh app on my iPhone in an attempt to both ping and login via SSH to a system on my local network. Using `ping 192.168.101.1` nor `ssh jimmy@192.168.101.1` worked.

### OS

Other

### OS version

tvOS 17.3.0

### Tailscale version

1.60.0

**Comment by thomamueller** [comment]
Have same issue.  any resolution found?

**Comment by agottardo** [comment]
@thomamueller @opb1978 We cannot diagnose issues without a bug report identifier.

**Comment by thomamueller** [comment]
At what point should I create it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomamueller** [comment]
BUG-56d3428d9af11a6c763e8a5aac11dcbed672e9ed81fd4c1b51c9235582adbbaa-20240504204554Z-e139fd172d4463c1


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomamueller** [comment]
Tried subnet on a second ATV and did not work.  Just to recap, it worked on an Apple MAC.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomamueller** [comment]
Any update on this issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by agottardo** [comment]
The bug report ID you attached was generated on an iPhone. Update the Tailscale app on your Apple TV to 1.66.0, then generate a bug report ID _on the Apple TV_ that is experiencing the problem (scroll down to **About Tailscale for tvOS** > **Report an Issue** button).

**Comment by Summit48** [comment]
@agottardo 
I have ATV-HD tvOS 17.4.0, Tailscale v1.66.0 and Exit Node enabled.

The Exit Node works intermittently, more off than on.

This is a bug report from the ATV:
BUG-374e684e9b4c4ffc57b56943897f3d3ac03c71a76ee0f3c9f2c7c3dc66ae6899-20240512095951Z-b0453a0690b455f6

**Comment by thomamueller** [comment]
BUG-ce4f0a39ff77cfbad68c92340a0f6e4911646e58450de4fbcc421a29438996fb-20240512185949Z-d073319bd2497ce1

From Apple TV

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Summit48** [comment]
This looks to be a DNS issue.

My Router(which is also an Exit Node) is configured for Cloudflare 1.1.1.1 (DNS1) and Google 8.8.8.8 (DNS2). 

If I remove the Google DNS and only configure the Cloudflare DNS then the ATV Exit Node feature works as expected.

I have not tested with using only the Google DNS.

**Comment by Summit48** [comment]
I reinstated Google 8.8.8.8 (DNS2) to my router configuration and the ATV Exit Node intermittent connection issue returned.
I noticed Apple just released tvOS v17.5.0 and after upgrading the ATV Exit Node is now functioning with DNS1 & DNS2 configured on the router.
Using the ATV Exit Node from devices on the same LAN/Wi-Fi network works well. However if I turn the Wi-Fi off on the iPhone, the VPN connection to the ATV Exit Node does not transition to the Cellular Network. The workaround is to first connect the iPhone to the Cellular Network and then enable VPN.
Note, the VPN toggle button in iPhone Settings does not allow the VPN to be turned OFF once the Tailscale App is launched.

**Comment by thomamueller** [comment]
I believe we can close this as related to subnet on ATV.  I was able to logon to the printer from 5G using local 192.168.1.6

**Comment by Summit48** [comment]
@agottardo 

I am still having issues with the ATV Exit Node feature intermittently not working.

Bug report from the ATV:

BUG-374e684e9b4c4ffc57b56943897f3d3ac03c71a76ee0f3c9f2c7c3dc66ae6899-20240524051926Z-6df9d48fdc0d2cb8

**Comment by Summit48** [comment]
Just wanted to report back that the ATV Exit Node has been functioning without issues.

Currently ATV tvOS v17.6.0, Taliscale v17.0.0.
