### ISSUE TITLE
Android disconnecting from exit node

### ISSUE THREAD

**Issue by jacob-horton** [tailscale/tailscale#11289]
### What is the issue?

I have tailscale on my android device set up to use an exit node. I also have tailscale set to have unrestricted battery usage.

Seemingly randomly, it will set the exit node back to `None` without any warning. I expected that it should keep the last exit node I selected

I also found [this reddit post](https://www.reddit.com/r/Tailscale/comments/17lc0nn/android_app_which_is_set_to_exit_node_alwaysonvpn/) from someone who seems to have the same issue

### Steps to reproduce

I haven't worked out any pattern to it unselecting the exit node randomly, but I can trigger it to do so by force closing tailscale. 

It will briefly show this for a few seconds, then the warning disappears and the exit node is set back to `None`
![Screenshot_20240228_203404](https://github.com/tailscale/tailscale/assets/50290314/36e4900c-b882-4a88-babc-e5a5fdc7af8a)

I would expect that it should keep the exit node in this scenario as well

### Are there any recent changes that introduced the issue?

I've been using tailscale for a few weeks now, and I've had the issue since the start

### OS

Android

### OS version

Android 14

### Tailscale version

1.16.0

### Bug report

BUG-00268d3cbae3313862b387271290721fc061708e1e011e4ccbe611e47d85f35f-20240228204944Z-a0bb8239c0b2dd07

**Comment by dblohm7** [comment]
Tagging @kari-ts for follow-up after she talks to @kelivel

**Comment by dmccue** [comment]
Happens to me regularly, works as expected but then after around 20 mins it shows none and a manual selection is required

**Comment by kari-ts** [comment]
The original report says the bug is occurring in version 1.16. Is this still the version you are using, and if not, are you still experiencing this bug?

**Comment by tsmoneta** [comment]
Not happening here anymore on 1.72.0-taa448d5a9-g.

**Comment by kari-ts** [comment]
Thanks for reporting back! I'll close this bug for now, but please reopen if you run into issues.
