### ISSUE TITLE
"run unattended" unchecked but starting at login since upgrade to version 1.6.0

### ISSUE THREAD

**Issue by gpion** [tailscale/tailscale#11280]
### What is the issue?

I just upgraded Windows agent to version 1.6.0
Since, Tailscale service runs automaticaly while "run unattended" option is unchecked

### Steps to reproduce

None, just upgrade Tailscale 1.6.0

### Are there any recent changes that introduced the issue?

Yes, upgraded this morning from 1.58.2 to 1.60

### OS

Windows

### OS version

Version 22H2, build 19045.4046

### Tailscale version

Version I.6.0 (tb36943c9b-g99e84774b)

**Comment by gpion** [comment]
I had to manually remove shortcut  "Tailscale" in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp"

**Comment by dblohm7** [comment]
The GUI client will still start even when the service is in unattended mode; that is expected behaviour.

@gpion, can you confirm that Tailscale is still signing in after you removed the shortcut from `StartUp`?

**Comment by gpion** [comment]
> I going to apply it and check back again after that

Nope, still auto connecting : 
![image](https://github.com/tailscale/tailscale/assets/2971216/e780127d-74ee-42e8-b328-6c60f334b4bb)
@dblohm7 
Is there a way to have the Tailscale icon in the taskbar (I guess it's what your calling "GUI") but disable automatic connection at startup ?

**Comment by nickkhyl** [comment]
The fix for this issue is available in the 1.73.69 [unstable build](https://pkgs.tailscale.com/unstable/#windows) and will be included in the 1.74 release planned for September.
