### ISSUE TITLE
MSI policy properties are not honoured during upgrades

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#11285]
That code is trying to use the [Remember Property Pattern](https://robmensching.com/articles/the-remember-property-pattern/) but that isn't implemented properly.

I think this would also be an excellent opportunity to rewrite the property-handling code in general so that our developers can just declare them in some kind of separate file (json?) and then can run a `go generate` step to rebuild the appropriate WiX markup.

**Comment by sailorfrag** [comment]
Also something to consider: if some properties are set in the installer and then later are overridden by a GPO, or if a GPO exists before the installer is run, I feel like the GPO should probably win? I don't know how practical it is to do that. Maybe the installer properties could actually modify local group policy instead of editing the registry directly?

**Comment by dblohm7** [comment]
I think in terms of practicalities of fixing this in the short term, we won't be able to directly access GPO. Something to consider for future work, methinks.

In the immediate term, [here](https://learn.microsoft.com/en-us/windows/win32/msi/order-of-property-precedence) is the order of precedence for MSI properties.

**Comment by nickkhyl** [comment]
I agree that the installer shouldn't write directly under the SOFTWARE\Policies key, and that modifying the Local Group Policy is probably the best option for the longer term. Theoretically, we could store these install-time policies under our own registry key (SOFTWARE\Tailscale IPN\Policies?), but I believe having them in the Local Group Policy offers the advantage of including these policies in group policy reports (think [gpresult](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/gpresult) and similar tools). This is beneficial for troubleshooting, ensuring compliance, and so on, especially when a customer starts with a small deployment and configures policies at install time but later proceeds with a deployment at a broader organizational level and decides to use GP, MDM, or other solutions to manage the settings.
