### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by DatanoiseTV** [tailscale/tailscale#1129]
I have mutitple accounts for Tailscale and would like to use them in one client. Is there already a way to do it?

**Comment by bradfitz** [comment]
We'd eventually like to support both fast user switching between multiple accounts, as well as simulataenous multi-login. Neither are possible now.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/713
