### ISSUE TITLE
cmd/tailscaled: set default value of --state flag

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#113]
I always forget to specify the tailscaled `--state` flag, then forget what value I used previously.

Let's just make it user-friendly and pick a reasonable, opinionated default.

If it absolutely must be opt-in (can't think of why?), then the error should say why and suggest a reasonable default value. Currently it just says:

```
# ./tailscaled 
logtail started
Program starting: vLONGVER-TODO: []string{"./tailscaled"}
LogID: d8110230555bdb199b48ca6ca71c3802b758e9373cd104d785b8e5c2d1eb8d27
--state is required
```

**Comment by danderson** [comment]
Done in 65e7c
