### ISSUE TITLE
tailscale update: Alpine edge 3.20.0 shows no update needed when a newer package is available

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#11309]
### What is the issue?

After upgrading Alpine to edge 3.20.0, `tailscale update` should pick up the latest available version (currently 1.58.2). Instead, `tailscale update` on version 1.54.1 shows no update needed. 

### Steps to reproduce

With a previous Tailscale version installed, upgrade Alpine repositories to edge and attempt `tailscale update`.

```
alpine:~# cat /etc/alpine-release
3.20.0_alpha20231219
alpine:~# tailscale update
already running stable version 1.54.1; no update needed

alpine:~# apk update && apk info tailscale
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
v20231219-4573-g19247761b6d [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v20231219-4578-g68676dd018e [http://dl-cdn.alpinelinux.org/alpine/edge/community]
OK: 23375 distinct packages available
tailscale-1.54.1-r0 description:
The easiest, most secure way to use WireGuard and 2FA

tailscale-1.54.1-r0 webpage:
https://tailscale.com/

tailscale-1.54.1-r0 installed size:
34 MiB

tailscale-1.58.2-r0 description:
The easiest, most secure way to use WireGuard and 2FA

tailscale-1.58.2-r0 webpage:
https://tailscale.com/

tailscale-1.58.2-r0 installed size:
35 MiB
```

### OS

Linux

### OS version

Alpine 3.20.0_alpha20231219

**Comment by awly** [comment]
Another thing to fix here: detect when `/etc/apk/repositories` has a static version, like 3.19.

**Comment by ckinateder** [comment]
I'm having this issue as well.

**Comment by Lastdough** [comment]
I'm having this issue as well

current version 1.76.6
latest version 1.80.3

and it seems like it affects the DNS connection. I can't connect to the internet whenever tailscale is up
