### ISSUE TITLE
Permission denied (tailscale) when using ssh

### ISSUE THREAD

**Issue by zhh210** [tailscale/tailscale#11313]
### What is the issue?

I've only one user and all devices tagged as tag:container. However when trying to ssh from any device tailscale ssh keeps giving the `Permission denied (tailscale)` error. The only place I can ssh to any of the device now is from the tailscale web console . I wonder what's the simplest possible way of setting up the ACL (one account, all devices can ssh to each other)? Do I really need group/tag in the first place? I was able to ssh once for a device but today all devices are not sshable.

```
// Define the tags which can be applied to devices and by which users.
	"tagOwners": {
		"tag:example":   ["autogroup:admin"],
		"tag:container": ["autogroup:admin", "autogroup:member"],
	},

	// Define access control lists for users, groups, autogroups, tags,
	// Tailscale IP addresses, and subnet ranges.
	"acls": [
		// Allow all connections.
		// Comment this section out if you want to define specific restrictions.
		{"action": "accept", "src": ["*"], "dst": ["*:*"]},
	],

	// Define users and devices that can use Tailscale SSH.
	"ssh": [
		// Allow all users to SSH into their own devices in check mode.
		// Comment this section out if you want to define specific restrictions.
		{
			"action": "accept",
			"src":    ["autogroup:member"],
			"dst":    ["autogroup:self", "tag:container"],
			"users": [
				"autogroup:member",
				"autogroup:nonroot",
				"root",
				"*:*",
			],
		},
	],
```

The related bugreport identifier: `BUG-923d6c43b950c91f36c147af1fde956d173aabdfe9cf322499af20aabb62f17b-20240229214533Z-c1cdd193d7287871`

### Steps to reproduce

sudo tailscale up --ssh --accept-dns=false --advertise-tags=tag:container --auth-key=<tskey-client>?ephemeral=false

### OS

Linux

### OS version

Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

### Tailscale version

1.60.0

### Bug report

BUG-923d6c43b950c91f36c147af1fde956d173aabdfe9cf322499af20aabb62f17b-20240229214533Z-c1cdd193d7287871

**Comment by kelivel** [comment]
> all devices tagged as tag:container

Those devices aren't included in `autogroup:member` anymore, and you'll need to update your SSH source policy to include your tags. Give that a try and see if your connections are successful after.

**Comment by zhh210** [comment]
Seems working after adding `tag:container` to dst. But I have to remove `autogroup:self` otherwise it will pop up an error of `Error: "tag:container" is not allowed in src for autogroup:self` when adding `tag:container`.
