### ISSUE TITLE
computerz: CSRF adding notes from search URL

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#11319]
I can go to http://computerz/?q=bradtop and see my workstation.

But then if I leave a note from that page, I get "Forbidden - CSRF token not found in request".

/cc @awly @patrickod

**Comment by awly** [comment]
Fixed, sorry for the inconvenience

**Comment by bradfitz** [comment]
No inconvenience. I was just screwing around with it and clicking things :)
