### ISSUE TITLE
FR: Allow iOS users to choose which tailnet to connect to even when tailscale is disabled

### ISSUE THREAD

**Issue by bailey-ts** [tailscale/tailscale#11328]
### What are you trying to do?

It was explained in http://go/corp/13981 that this was no longer possible starting in v1.48 because the Tailscale network extension no longer stays running in the background to save battery life, and with no active network extension there are no active accounts to choose from or switch between. 

While fast user switching helps, it still isn't possible to re-enable tailscale and connect directly to your desired tailnet instead of whatever tailnet was last used. This is especially disruptive if an exit node is selected for one or both of the connections and causes a delay in being able to connect to the desired tailnet.

### How should we solve this?

If the app was able to store the active Tailscale logins and allow the user to switch between them before re-enabling the tailscale connection in order to connect directly to the desired tailnet from a disconnected state, I believe that would resolve this issue.

### What is the impact of not solving this?

Multi-tailnet users on iOS that frequently re-enable the tailscale connection with the intent of using a different tailnet than they were on previously have to perform additional steps to first connect to tailscale and then switch tailnets. 

For example, users that access a personal tailnet at home, disable tailscale on cellular service during their commute, and then want to re-enable tailscale on their work tailnet, will have to wait to reconnect to their personal tailnet and then switch tailnets each time instead of it being able to directly reconnect to the work tailnet.

**Comment by agottardo** [comment]
This was fixed in https://github.com/tailscale/corp/pull/19284
