### ISSUE TITLE
`tailscale up --ssh` tells me I need to upgrade, but I am on the latest version

### ISSUE THREAD

**Issue by alilleybrinker** [tailscale/tailscale#11322]
### What is the issue?

When I run `tailscale up --ssh`, I get:

```
Update available: 1.60.1 -> 1.60.1, run `tailscale update` or `tailscale set --auto-update` to update
```

When I run `tailscale update`, I get:

```
already running stable version 1.60.1; no update needed
```

Because of this, I am unable to launch Tailscale SSH on my device.

### Steps to reproduce

1. `tailscale up --ssh` (errors out)
2. `tailscale update` (no updates)
3. `tailscale up --ssh` (still errors out)

### Are there any recent changes that introduced the issue?

I have not changed anything on my device.

### OS

Linux

### OS version

Linux lb-rasb-pi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

### Tailscale version

1.60.1   tailscale commit: a8e06a7df8a712f095e12888ae37bfd3a270c825   other commit: 7c984f40215c90499527bcd251aeda4da6131d62   go version: go1.22.0

### Other software

Homebridge 1.7.0

### Bug report

BUG-39ee4da6ba784229357c8e034faba957410796863486617f92365a386dd6af56-20240302181243Z-aaec198fc5ee3253

**Comment by bradfitz** [comment]
Which distro is that?

cc @awly

**Comment by alilleybrinker** [comment]
It’s Raspbian

**Comment by dragojdw** [comment]
Experiencing same on Ubuntu 22.04.3 LTS

**Comment by davidemyers** [comment]
I've noticed a message like the one above immediately after an upgrade when running `tailscale status`:
```
# Health check:
#     - Update available: 1.60.0 -> 1.60.0, run `tailscale update` or `tailscale set --auto-update` to update
```
If I do nothing the condition clears on its own after a while.

Also Ubuntu 22.04. I've seen this when triggering the upgrade from the admin console, and possibly also when upgrading with `apt` the "old fashioned" way.

**Comment by awly** [comment]
Interesting. Tailscale should report its current version and receive the update notification (if needed) from our control plane on startup.
This behavior suggests that there is a race condition somewhere: either the client reporting an older version on startup, or our control plane ignoring the client-reported version.
I will try to reproduce this in a VM.

> Because of this, I am unable to launch Tailscale SSH on my device.

@alilleybrinker that message should be just a warning. Does `tailscale up --ssh` fail? You can check if SSH is actually enabled using `tailscale debug prefs | grep RunSSH`

**Comment by awly** [comment]
Found the bug in our control plane (we were using the last persisted client version), which is now fixed and waiting for a deployment.

**Comment by alilleybrinker** [comment]
> @alilleybrinker that message should be just a warning. Does `tailscale up --ssh` fail? You can check if SSH is actually enabled using `tailscale debug prefs | grep RunSSH`

Hm, I wasn't able to SSH in from my own machine when I was testing this, though I _was_ able to SSH in from the Tailscale control panel. Perhaps the laptop I was trying to SSH in from had a separate issue with Tailscale SSH. I hadn't changed any config though, and unfortunately I probably won't have a chance to test this again for at least a couple of days.

**Comment by awly** [comment]
@alilleybrinker it may be an issue with your ACLs too, check out https://tailscale.com/kb/1193/tailscale-ssh#prerequisites for what needs to be opened up

**Comment by awly** [comment]
The fix is deployed!

**Comment by alilleybrinker** [comment]
Finally had some time to figure out my own issue. You're right that the version upgrade issue was separate from the connection issue I'd encountered. Turns out I'd manually set an entry in my SSH config which was conflicting with Tailscale SSH, causing `ssh <name>` command (where `name` is both the name set in my SSH config _and_ the name of the device in my tailnet) to bypass Tailscale SSH and try connecting directly, resulting in a password prompt instead of a redirection to Tailscale auth in the browser. Removing the offending SSH config entry fixed the issue.
