### ISSUE TITLE
Tailscale --auth-key doesn't force a re-auth using that authkey.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1133]
1. Install Tailscale
2. tailscale up --authkey X
(authenticate yourself)
3. tailscale down
4. tailscale up --authkey Y (DOES NOT ASK FOR reauth)

**WorkAround**: run tailscale up --force-reauth --authkey Y

**Comment by DentonGentry** [comment]
This was opened on behalf of the user in a support ticket, but the original ticket was not recorded. Nothing to followup on now.
