### ISSUE TITLE
FR: Support for AIX

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [tailscale/tailscale#11361]
### What is the issue?

Hello, I am trying to install the app on OS AIX version 7.3, in the download list, use the other distributions, but none install the application.
My question is, does the client exist for OS AIX?

### Steps to reproduce

Try each one on the list, following the steps mentioned.
![image](https://github.com/tailscale/tailscale/assets/41083269/4588727b-c5d2-4d77-8faa-36ddc0c83bc8)
but I was not successful

### OS

Other

### OS version

AIX 7.3

**Comment by raggi** [comment]
Tailscale does not currently support AIX.

**Comment by CamiloPerezOrtiz** [comment]
@raggi Thanks for the comment.
Do you plan to support AIX at some point?

**Comment by bradfitz** [comment]
@CamiloPerezOrtiz, https://github.com/tailscale/tailscale/pull/11721 is now merged so the Tailscale CLI tool and daemon will now compile for aix/ppc64.

It's unlikely we'll distribute binaries for some time. We'd like to see any users first.

You can cross-compile from macOS or Linux or whatever using:

```
$ GOOS=aix GOARCH=ppc64 go install tailscale.com/cmd/tailscale{,d}@main
```

And the binaries will be in your $HOME/go/bin/aix_ppc64:

```
$ GOOS=aix GOARCH=ppc64 go install tailscale.com/cmd/tailscale{,d}@main
go: downloading tailscale.com v1.65.0-pre.0.20240413180322-a1abd12f351c
$ ls -l ~/go/bin/aix_ppc64 
total 145528
-rwxr-xr-x  1 bradfitz  staff  27506699 Apr 13 11:05 tailscale
-rwxr-xr-x  1 bradfitz  staff  47000312 Apr 13 11:06 tailscaled
$ file ~/go/bin/aix_ppc64/tailscale
/Users/bradfitz/go/bin/aix_ppc64/tailscale: 64-bit XCOFF executable or object module
```

If you don't want to install Go yourself, you can git clone this repo and just run `./tool/go install ...` instead and it'll grab the right Go toolchain.

**Comment by CamiloPerezOrtiz** [comment]
Hi @bradfitz , thank you very much, you carried out the necessary tests and I share the observations found, thank you again for the support

**Comment by bradfitz** [comment]
I fired up a AIX 7.3 VM on IBM Cloud and verified it works.

Because I don't know how to install a system service on AIX, I just ran two SSH sessions: one with tailscaled and one with the tailscale CLI. I'm sure there's a proper way to do it, like all these subsystems:

<img width="1112" alt="Screenshot 2024-04-13 at 7 19 40 PM" src="https://github.com/tailscale/tailscale/assets/2621/e9165cac-1ad2-4017-a4b4-22cd16b89f0c">

**Comment by CamiloPerezOrtiz** [comment]
Hi @bradfitz , I tried to carry out the steps mentioned on a Linux system (Ubuntu), the binary files were generated, but when I wanted to compile on AIX it sent me the following error

![image](https://github.com/tailscale/tailscale/assets/41083269/0f0c503c-1ffb-45b3-8cd0-09f4a676062c)

in aix there is no systemd and I do not have the other tailscaled.services and default for aix

![image](https://github.com/tailscale/tailscale/assets/41083269/3f3190cd-4053-4c56-8669-6ba56dd78219)


Any ideas anyone?

**Comment by bradfitz** [comment]
`chmod +x /usr/bin/tailscale` it first.

**Comment by bradfitz** [comment]
You're not running tailscaled. You need to run tailscaled on the machine and then the tailscale CLI program connects to your local tailscaled.

**Comment by CamiloPerezOrtiz** [comment]
Hi @bradfitz thanks for the comment

We have already validated that if they lift tailscaled services in aix 7.2, we were also able to register on our private headscale and public tailscale servers, but there is no communication between the headscale VPN teams.
We found that the tailscale0 interface is not generated as in other Linux distributions
why is this?
It is normal?
Are any parameters missing?

#############################################################################################

service with its binaries if it works and lifts

![WhatsApp Image 2024-04-23 at 6 49 54 PM](https://github.com/tailscale/tailscale/assets/41083269/ccf76e38-5d85-454a-a37a-af6e9c599cb6)

Yes, connect the equipment to the headscale

![WhatsApp Image 2024-04-23 at 6 50 35 PM](https://github.com/tailscale/tailscale/assets/41083269/a56fb20e-d21e-49e8-8147-2f988b0f5fdd)

Logs that if it connects

![WhatsApp Image 2024-04-23 at 6 52 01 PM](https://github.com/tailscale/tailscale/assets/41083269/3f5a9256-7bd2-4c14-b11a-74ec5e4c0c65)

but there is no communication between the headscale vpn devices

**Comment by ColombianJoker** [comment]
Hello.

I could test `tailscaled` and `tailscale` on AIX 7.2, and 7.3, and document how to create the needed service to manage it.

**Comment by bradfitz** [comment]
@ColombianJoker, that would be great! Could you link it from here when you do so?

**Comment by ColombianJoker** [comment]
Then I would have to: clone or do a pr of the repo, compile the AIX version, and start from there
