### ISSUE TITLE
Create releases with OS packages

### ISSUE THREAD

**Issue by C-Howard** [tailscale/tailscale#114]
**Is your feature request related to a problem? Please describe.**

Currently building out the correct packages for an operating system like Amazon Linux 2 with service files appears to be non trivial.

**Describe the solution you'd like**

I would like to be able to fetch prebuilt packages of the master branch from Github. This would allow testing of tailscaled before it is included as part of a full release.

**Describe alternatives you've considered**

The docker container could be used but being able to directly install on the machine is ideal.

**Additional context**

**Comment by bradfitz** [comment]
@danderson was just working on putting up a package server for distro packages. It might even be ready today-ish. But soon in any case.

**Comment by danderson** [comment]
Done, https://pkgs.tailscale.com .
