### ISSUE TITLE
gokrazy: set sysctl for IP forwarding

### ISSUE THREAD

**Issue by joneskoo** [tailscale/tailscale#11405]
### What are you trying to do?

I’m using https://www.gokrazy.org/ to create a Raspberry Pi appliance and use it as a subnet router

### How should we solve this?

I would like tailscale up to automatically set required sysctls to enable IP forwarding when enabling advertise-routes or advertise exit node.

### What is the impact of not solving this?

User needs to create a go package to set sysctls when using tailscale with gokrazy.

### Anything else?

https://github.com/gokrazy/gokrazy/issues/255

Gokrazy doesn’t have a built in mechanism to set sysctls. Maintainer of gokrazy @stapelberg would expect Tailscale to configure routing.

Even if Tailscale doesn’t do it in general, Tailscale already has special handling for gokrazy (exit code to prevent start loop). It would be well aligned and super nice usability to set simple sysctls for routing on gokrazy platform. Based on testing with breakglass ssh, setting sysctl is all that’s needed to make subnet routing work. I’m guessing this extends to exit node.

cc @bradfitz who was involved with earlier gokrazy integration.

**Comment by bradfitz** [comment]
I don't think we can do this for Linux in general, but for gokrazy I'm totally cool with this.

**Comment by stapelberg** [comment]
> I don't think we can do this for Linux in general

Can you elaborate why not? Does Tailscale not want to interfere with certain parts of the networking config? (I’m asking because Tailscale already touches DNS.)

**Comment by bradfitz** [comment]
Mostly because we haven't historically and changing behavior at this point tends to surprise & anger people.

Our Linux DNS mucking could use a lot of love. It's a frequent point of pain for anything other than the systemd-resolved happy path.

**Comment by joneskoo** [comment]
I've made a pull request #11408  to implement this as discussed in this issue with Brad earlier. As I understand his comment, it should be ok for Tailscale to enable forwarding on gokrazy and it's only matter of Tailscale reviewing if the way I implemented it is good enough.
