### ISSUE TITLE
Tailscale duplicates itself when requesting its status continously

### ISSUE THREAD

**Issue by fernandoflorez** [tailscale/tailscale#11428]
### What is the issue?

I created a tmux plugin that continously checks (every 15 seconds) for tailscale's status in order to display it on tmux' status line.

After some time there are duplicated tailscale running in parallel:

<img width="122" alt="Screenshot 2024-03-15 at 12 42 24 PM" src="https://github.com/tailscale/tailscale/assets/50845/f043170a-2a99-4265-a896-a178d70e3e1d">

<img width="1465" alt="Screenshot 2024-03-15 at 12 41 54 PM" src="https://github.com/tailscale/tailscale/assets/50845/3511f8d9-2a47-4f43-abcb-e02ab430952e">

This happens in Mac OS Sonoma and with tailscale downloaded from the appstore.

### Steps to reproduce

This is tmux plugin: https://github.com/fernandoflorez/tmux-tailscale but Ive been able to reproduce bash looping and sleeping for 10 seconds.

### OS

macOS

### OS version

Sonoma

### Tailscale version

1.62.0

### Bug report

BUG-2316b833ca585b305fee4ab004cae39a5e03649ccd40fffa6176cf6faee0841f-20240315174723Z-423ea62c1eb610e2

**Comment by agottardo** [comment]
Just to clarify: there are several instances _of the GUI process_. There is only one Tailscale daemon running (IPNExtension).

**Comment by agottardo** [comment]
We landed a fix for this, it will be available in unstable builds soon.

**Comment by barnstar** [comment]
Re-opening.  This seems related to invoking the binary from another process.  Needs additional investigation.
