### ISSUE TITLE
VPN not starting when u reboot android phone

### ISSUE THREAD

**Issue by vaihelvette** [tailscale/tailscale#11432]
### What is the issue?

Still havent fixed the "Always on option". VPN i still turned off when you reboot the phone. 
Had to revert to version 1.42.0

### Steps to reproduce

Have always option on active.
Reboot phone

### Are there any recent changes that introduced the issue?

Dont know

### OS

Android

### OS version

Android 14

### Tailscale version

1.60.0

### Other software

No other

### Bug report

Well i installed 1.42.0 again that works. Dont want to install latest again.

**Comment by kelivel** [comment]
Hi @vaihelvette, this behavior will be fixed when version 1.62 is released for Android. We're actively working on getting that shipped so keep an eye out in the near future.

**Comment by agottardo** [comment]
This was fixed in 1.66 (you should test on the latest 1.67.x beta).
