### ISSUE TITLE
Mac OS app version 1.62.0 on MAcOSX 14.4 fails to show login screen after reinstall

### ISSUE THREAD

**Issue by OferLapid** [tailscale/tailscale#11433]
### What is the issue?

I had to reinstall the app on my Mac and now it will not login

### Steps to reproduce

I followed the cleanup instructions
Removed VPN config, removed the items from the container folder, removed key chain items
Reinstalled the app from app store
App creates a VPN config
App shows exclamation mark 
"needs authentication"
And yet Login / Add Account buttons does nothing

### OS

macOS

### OS version

14.4

### Tailscale version

1.62.0

**Comment by j4n-e4t** [comment]
I have the same issue! Does anyone know, how to fix it??? I can't login anymore.

**Comment by JBabyDavies** [comment]
Also having this issue. Fully removed Tailscale according to uninstall instructions. Removed from Keychain Access

**Comment by JBabyDavies** [comment]
Just to add, updated to version 1.64.0 from the App Store and it still doesn't work.

**Comment by agottardo** [comment]
We can't identify this issue without diagnostic information. There is most likely something interfering in your macOS configuration. To allow us to look into that, please reproduce the issue, then take a [sysdiagnose](https://support.kandji.io/support/solutions/articles/72000599404-how-to-generate-a-sysdiagnose-in-macos) and send the generated `.tar.gz` to andrea@tailscale.com. Thanks.

**Comment by agottardo** [comment]
Closing stale issues.

**Comment by Jiayang-21** [comment]
also having this issue...

**Comment by bradfitz** [comment]
@Jiayang-21, you're commenting on a year old closed bug. This is no longer tracked. Your issue is almost certainly unrelated. Please file a new issue with details if needed.
