### ISSUE TITLE
Admin: Cannot see details device. (Cannot read property 'map' of null)

### ISSUE THREAD

**Issue by SimaKyr** [tailscale/tailscale#1143]
**Describe the bug**
Some device imposible to view details and make connection with them.

**To Reproduce**
1. Login in Tailscale Android
2. Try open Details device(impossible).
3. ping device(impossible).

**Expected behavior**
Works command ping and button "Details".

**Screenshots**
![image](https://user-images.githubusercontent.com/28606130/104817756-dc6e8280-582b-11eb-8454-2506764c93b3.png)
![image](https://user-images.githubusercontent.com/28606130/104817774-06c04000-582c-11eb-82e8-05cb364fa485.png)
![image](https://user-images.githubusercontent.com/28606130/104817799-4129dd00-582c-11eb-8871-dcfc850bef1c.png)

**Version information:**
 - Device: ???.
 - OS: Android
 - OS version: ???(I don't know).
 - Tailscale version: 1.2.2

**Additional context**
When try open details next time, error still appears.
I think device need to log out and login.

**Comment by bradfitz** [comment]
The browser name/version and OS version would help.

/cc @rosszurowski @soniaappasamy

**Comment by SimaKyr** [comment]
@bradfitz 
![image](https://user-images.githubusercontent.com/28606130/104836500-ff924400-58b6-11eb-8600-f67aa6b677f3.png)

`
Google Chrome | 87.0.4280.141 (Официальная сборка) (64 бит) (cohort: Stable)
-- | --
Версия | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
ОС | Windows 10 OS Version 2004 (Build 19041.450)
JavaScript | V8 8.7.220.31
Flash | 32.0.0.465 C:\Users\simakyr\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.465\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Командная строка | "C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Путь к исполняемому файлу | C:\Program Files\Google\Chrome\Application\chrome.exe
Путь к профилю | C:\Users\simakyr\AppData\Local\Google\Chrome\User Data\Default
`

**Comment by SimaKyr** [comment]
Tried in Firefox. Shows different error:
![image](https://user-images.githubusercontent.com/28606130/104837463-4e42dc80-58bd-11eb-8123-e5f7db94723d.png)
![image](https://user-images.githubusercontent.com/28606130/104837467-53079080-58bd-11eb-9f75-8264564a919c.png)
![image](https://user-images.githubusercontent.com/28606130/104837474-60247f80-58bd-11eb-8c95-54205ef9cdb1.png)
Windows 10 OS Version 2004 (Build 19041.450)

**Comment by rosszurowski** [comment]
This looks like an issue with our backend returning an invalid value that our admin panel can't handle. That's a bug on our side — I've made a fix which should be deployed tomorrow.

That said, this shouldn't affect your connectivity at all, just what you see in the admin panel. When you say "ping device(impossible)" — are you not able to connect to this device over Tailscale? If so, please email some details about which two devices you're trying to connect between, and a timestamp that you tried to connection at to support@tailscale.com, and we can help you out there.

**Comment by rosszurowski** [comment]
We just deployed the fix for this particular bug. I'll close this issue out, but please let us know if you're still running into this error message! And, as I mentioned above, if you're still having trouble connecting to this device, please email us at support@tailscale.com with details.
