### ISSUE TITLE
FR: `tailscale configure kubeconfig` should honour `KUBECONFIG` env var

### ISSUE THREAD

**Issue by jaxxstorm** [tailscale/tailscale#11441]
### What are you trying to do?

I ran `tailscale configure kubeconfig eks-operator-west-2` and it configured the kubeconfig file in `~/.kube/config` despite having my `KUBECONFIG` env var set

### How should we solve this?

Detect if the env var is set and write to the correct file

### What is the impact of not solving this?

It violates the principal of least surprise

**Comment by irbekrm** [comment]
We should definitely do this 👍🏼 

There is already an issue for it https://github.com/tailscale/tailscale/issues/10346
