### ISSUE TITLE
Operator assumes cluster domain is cluster.local

### ISSUE THREAD

**Issue by microsec-ambrose** [tailscale/tailscale#11445]
### What is the issue?

The Kubernetes Operator assumes the cluster domain is `cluster.local`. In our production environment, we have configured this to a different value, and our Kubernetes operator is unable to connect to [cluster egresses](https://tailscale.com/kb/1236/kubernetes-operator#cluster-egress).

https://github.com/tailscale/tailscale/blob/da7c3d1753d07392281620730fac73384425d130/cmd/k8s-operator/svc.go#L231

### Solution

Parse `/etc/resolv.conf` using [the existing parser](https://github.com/tailscale/tailscale/blob/main/net/dns/resolvconffile/resolvconffile.go#L63). It can be assumed that the Kubernetes Operator is running in the same cluster. 

Otherwise, expose a configuration option for this.

### Steps to reproduce

- Start a cluster with a custom cluster domain (`--dns-domain cluster.lan`)
- Install the Kubernetes Operator
- Set up a service

### Are there any recent changes that introduced the issue?

#9494

### OS

Other

### Tailscale version

1.62.0

### Other software

Kubernetes v1.28.5+k3s1

**Comment by irbekrm** [comment]
Hi @microsec-ambrose thank you for opening the issue.

This should have been fixed in #11512 and I've just cut a `1.65.58` version of our dev Helm chart (or `unstable-v1.65.58` operator image tag if using static manifests) that has this change. Let us know if there are further issues.

**Comment by irbekrm** [comment]
Closing as fixed in #11512
