### ISSUE TITLE
FR: Mullvad VPN on Apple Vision Pro

### ISSUE THREAD

**Issue by shrop** [tailscale/tailscale#11440]
### What are you trying to do?

I would like to use the Mullvad VPN add-on feature with Tailscale (iPad app) on Apple Vision Pro.

### How should we solve this?

I am not sure if this is a limitation of Apple Vision Pro APIs. I do not see the same interface to select a Mullvad VPN as I do on other iOS version of Tailscale.

### What is the impact of not solving this?

I do use the Apple Vision Pro mobile and expect to continue to do this. I depend on Tailscale + Mullvad VPN to secure my network access.

**Comment by agottardo** [comment]
Did you enable the Mullvad add-on for the device in your admin console? All features available on iOS should also be available on visionOS, as we are currently shipping the same binary for both platforms.

**Comment by shrop** [comment]
Thank you! That worked fine. I forgot I did this originally. Here are the docs if anyone else needs them. https://tailscale.com/kb/1258/mullvad-exit-nodes
