### ISSUE TITLE
MacOS - Extension Install issue detected. 

### ISSUE THREAD

**Issue by joem5611** [tailscale/tailscale#11462]
### What is the issue?

![image](https://github.com/tailscale/tailscale/assets/152225779/8b49da42-673f-42d4-b6af-28adc50f8c32)
This was working fine on my mdm until today, we noticed that new installs are getting this error and in order to get the extension working you need to go to show onboarding the follow those steps. Our MDM has been setup with the Team Identifier and everything, this was all working fine until recent. Did a change or update break this? 

### Steps to reproduce

Install via my MDM

### Are there any recent changes that introduced the issue?

0

### OS

macOS

### OS version

14.4

### Tailscale version

1.62.0

### Other software

Crowdstrike
Nothing else out of the ordinary

**Comment by Maaago** [comment]
I had the same issue and a clean install solved everything.

Context: I installed tailscale via homebrew on macOS, upgraded it to the 1.62.0 and had the issue. Uninstalled the app using an app uninstaller to make sure every file got deleted and then I removed the cask from homebrew.
Finally I re-installed the tailscale cask via homebrew again.

**Comment by kelivel** [comment]
Hi folks, we'll be shipping stable version 1.62.1 this week that has a fix for this behavior. If a clean uninstall and reinstall doesn't help, you can grab our latest unstable version with the fix rolled in at https://pkgs.tailscale.com/unstable/#macos.

**Comment by agottardo** [comment]
Closing because a fix was released.
