### ISSUE TITLE
McAfee blocks tailscale from accessing netsh.exe

### ISSUE THREAD

**Issue by hitechever** [tailscale/tailscale#11469]
### What is the issue?

The security software of my computer keeps blocking C:\Program Files\Tailscale\tailscaled.exe from running C:\Windows\System32\netsh.exe. The log from the security software said "Adaptive Threat Protection blocked access because the reputation (Most Likely Malicious) is below the configured Block threshold.". This occurs every minute and doesn't stop since 2024-03-15. The security software inspects this is a Trojan threat (Malware Detected) and blocked the access.

### OS

Windows

### OS version

Windows 11 23H2

### Tailscale version

1.62.0

### Other software

McAfee Endpoint Security

### Bug report

BUG-f58ccb5320c00c6598dc206cc193ca3cb5f0178c94357fe8600525bdb619ecb5-20240320102549Z-567d7209ed1e6b0c

**Comment by bradfitz** [comment]
Thanks for the heads up. We'll send them another false positive email.

(It's a never ending battle, notifying dozens of AV vendors that they have false positives.)
