### ISSUE TITLE
Tailscale blocks Canonical Livepatch

### ISSUE THREAD

**Issue by magikid** [tailscale/tailscale#1148]
**Describe the bug**
With tailscale enabled, Canonical Livepatch can't contact remote server

**To Reproduce**
1. `sudo tailscale up`
2. `sudo canonical-livepatch enable XXXPRIVATEKEYXXX
3. See error: ```server check-in: failed: livepatch check failed: cannot send request: Put https://livepatch.canonical.com/api/machine/91aff5d3efb3424da847de46b9453455: dial tcp: lookup livepatch.canonical.com on [::1]:53: read udp [::1]:57882->[::1]:53: read: connection refused```
4. Alternatively after bringing down tailscale, I get the same message by running `sudo canonical-livepatch status`

**Expected behavior**
I expected a success message from canonical-livepatch.

**Version information:**
 - Device: Server
 - OS: Linux
 - OS version: Ubuntu 20.04.1 LTS
 - Tailscale version: 1.2.10 (commit e480f8ddf6f7334fda1b3d0dd1b500f2f01f961b)

**Additional context**
I'm not even sure how to begin diagnosing this bug.  All I know is that when I run `sudo tailscale down`, my server can reach the canonical service.  I'll be happy to run any sort of diagnostic commands on the server.

**Comment by bradfitz** [comment]
Are you using the MagicDNS beta? When it's broken, what's your /etc/resolv.conf say?

**Comment by magikid** [comment]
I have turned off the MagicDNS beta and removed the nameservers and search domains on that page.  My `/etc/resolv.conf` is autogenerated by `systemd-resolved` so it's pretty boring

```
nameserver 127.0.0.53
options edns0 trust-ad
```

Running `systemd-resolve --status`, I get no global DNS servers set and `67.207.67.2` set for eth0 and eth1 which is the DigitalOcean DNS server.  The `tailscale0` interface has no interface-specific DNS server set (and setting one doesn't seem to change anything).

**Comment by magikid** [comment]
Well, it seems the problem probably isn't with Tailscale after all.  I'm not sure what the actual issue is but I'm currently connected tp Tailscale and it just started succeeding.  I disabled ipv6 and re-enabled it and that seemed to resolve the problem:

```
$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
$ sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
$ sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
$ sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
$ sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
$ sudo canonical-livepatch status --verbose
last check: 38 seconds ago
kernel: 5.4.0-62.70-generic
server check-in: succeeded
patch state: ✓ no livepatches needed for this kernel yet
client version: 9.5.5
architecture: x86_64
cpu model: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
boot time: 5 hours ago
```
