### ISSUE TITLE
--port not being respected with custom login server

### ISSUE THREAD

**Issue by 1dom** [tailscale/tailscale#11487]
### What is the issue?

edit: issue was I also had randomizeClientPort set to true, setting this to false resolves the issue, but breaks things that depend on that setting being true. If you don't need randomised ports, turn this off, and --port should work again

-----

Port specified by --port on tailscaled doesn't seem to be respected if a custom login server is provided. 

I like to specify the port when running in docker so I can expose the port and reliably get a direct connection. I noticed after rebuilding some of my services, I was no longer able to get a direct connection. netstat inside the container showed tailscaled wasn't listening on the requested ports any more with headscale.

Removing the login server and connecting to tailscale, not headscale, resulted in the correct port being listened via netstat.

 A few other notes:
 - containers setup 6 - 12 months ago work fine and listen on the requested port specified in tailscaled command (just checked, tailscaled version 1.44.2)
 - the same containers rebuilt changing only to newer version of tailscale binary listens on random port (tailscaled 1.62.0)
 - I also found this, someone having a similar issue: https://redmine.pfsense.org/issues/14676
 - This might also be related: https://github.com/tailscale/tailscale/issues/11174

In a setup demonstrating the issue, I noticed these logs, which I think show the port initially being set as requested in `onPortUpdate`. Sometime later, during or after joining the network fully, the listening ports being changed away to something not requested.

```
tailscaled --port 12345 # loginserver already setup in profile
logtail started
Program starting: v1.60.1-ta8e06a7df-g7c984f402, Go 1.22.0: []string{"tailscaled", "--port", "12345"}
LogID: 3416366d9562aed4c402a3eef49c963b32d23a9b26095c0e01879f9dff592f02
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
dns: [resolved-ping=yes rc=resolved resolved=nss nm=yes nm-resolved=yes nm-safe=no resolv-conf-mode=stub ret=systemd-resolved]
dns: using "systemd-resolved" mode
dns: using *dns.resolvedManager
link state: interfaces.State{defaultRoute=enp0s31f6 ifs={enp0s31f6:[192.168.0.16/24 llu6]} v4=true v6=false}
onPortUpdate(port=12345, network=udp6)
router: using firewall mode pref 
router: default choosing iptables
router: v6nat = true
onPortUpdate(port=12345, network=udp4)
...
...
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
active login: dom
Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
monitor: gateway and self IP changed: gw=192.168.0.1 self=192.168.0.16
magicsock: SetPrivateKey called (init)
onPortUpdate(port=49164, network=udp6)
onPortUpdate(port=51562, network=udp4)
```

Also posted on [a headscale discord](https://discord.com/channels/896711691637780480/896711692120129540/1219964429064736848) and was directed here.

### Steps to reproduce

Use an old version of tailscaled, provide a login server and port, netstat -taupn will show tailscaled listening on the requested port. (In my setup, if that port is then mapped in docker, I reliably get direct connections in my home network)

Update to a newer version of tailscaled, provide same login server and port, netstat -taupn will show a randomised port. (In my setup, this results in relayed connections via internal derp).

### Are there any recent changes that introduced the issue?

Not entirely sure. Based on the log messages, looks like something is being reloaded at somepoint and reverting to default random allocated port. I feel like the issue maybe something around here:
https://github.com/tailscale/tailscale/blame/main/wgengine/magicsock/endpoint.go#L1800

Possibly changes in that function over the past few months, or changes around when that function is triggered. 

### OS

Linux

### OS version

fedora, rocky and debian

### Tailscale version

1.62

**Comment by bradfitz** [comment]
Yes, `randomizeClientPort` and `--port` are fundamentally incompatible. They're asking for two opposite things.

I don't think we can do anything here. Also, we don't provide Headscale support in this forum, and none of us know Headscale.

**Comment by 1dom** [comment]
Thanks, I hadn't even really considered the meaning of the randomiseclientport - my bad. Although now I'm confident this is the same issue as #11174

I read the docs, and I disagree with your point that the 2 settings are fundamentally incompatible.

 randomClientPort set on the server side is a server asking all clients to **prefer** to listen on a random port. https://tailscale.com/kb/1337/acl-syntax#randomizeclientport

A client side flag on a client side listening port is to tell the client to listen on a particular port: https://tailscale.com/kb/1278/tailscaled

They're 2 different things: one is a server setting a preference which - by definition - could be ignored or overridden if not preferred.  The other is a client saying "yeah, I prefer not to, thanks."

I feel like this is a valid usecase too: I want most of my devices to be randomised ports, because it does help with my mobile connectivity.  I need some of my servers behind certain firewall setups though to use a specific ports so I can set rules in upstream network appliances.

Ultimately, this is the same point raised in #11174. Want me to close this ticket to continue this discussion there?

**Comment by bradfitz** [comment]
I can get our documentation clarified on the precedence between the two options but randomizeClientPort wins. It's a big hammer and should generally not be used. It's a desperate last ditch move to work around arguably broken firewalls.

We're sponsoring some work to get some popular NAT device/software fixed they don't require randomizeClientPort. Details will be announced pretty soon I think.

Yeah, let's close this and dup it into #11174. Thanks.
