### ISSUE TITLE
Not connected to home DERP region 900

### ISSUE THREAD

**Issue by weiyideai520** [tailscale/tailscale#11498]
### What is the issue?

Use custom relay.
I want it connect

### Bug report

BUG-676ba0fc624ce5173de93091a64462bdaf5c2583dc4d31b4aef77251cb60b841-20240322090117Z-7085ff371dc9cd41

**Comment by weiyideai520** [comment]
$ tailscale netcheck
2024/03/22 18:56:12 portmap: [v1] Got PMP response; IP: 100.113.159.101, epoch: 53762
2024/03/22 18:56:12 portmap: [v1] Got PCP response: epoch: 53762
2024/03/22 18:56:12 portmap: [v1] UPnP reply {Location:http://192.168.199.1:5351/rootDesc.xml Server:MiWiFi/x UPnP/1.1 MiniUPnPd/2.1 USN:uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=120\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nEXT:\r\nSERVER: MiWiFi/x UPnP/1.1 MiniUPnPd/2.1\r\nLOCATION: http://192.168.199.1:5351/rootDesc.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: 1711048718\r\nBOOTID.UPNP.ORG: 1711048718\r\nCONFIGID.UPNP.ORG: 1337\r\n\r\n"
2024/03/22 18:56:12 portmap: [v1] UPnP reply {Location:http://192.168.199.1:5351/rootDesc.xml Server:MiWiFi/x UPnP/1.1 MiniUPnPd/2.1 USN:uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=120\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nEXT:\r\nSERVER: MiWiFi/x UPnP/1.1 MiniUPnPd/2.1\r\nLOCATION: http://192.168.199.1:5351/rootDesc.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: 1711048718\r\nBOOTID.UPNP.ORG: 1711048718\r\nCONFIGID.UPNP.ORG: 1337\r\n\r\n"
2024/03/22 18:56:12 portmap: [v1] UPnP reply {Location:http://192.168.199.1:5351/rootDesc.xml Server:MiWiFi/x UPnP/1.1 MiniUPnPd/2.1 USN:uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=120\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nEXT:\r\nSERVER: MiWiFi/x UPnP/1.1 MiniUPnPd/2.1\r\nLOCATION: http://192.168.199.1:5351/rootDesc.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: 1711048718\r\nBOOTID.UPNP.ORG: 1711048718\r\nCONFIGID.UPNP.ORG: 1337\r\n\r\n"
2024/03/22 18:56:12 portmap: UPnP meta changed: [{Location:http://192.168.199.1:5351/rootDesc.xml Server:MiWiFi/x UPnP/1.1 MiniUPnPd/2.1 USN:uuid:40f91860-0a5f-42e3-a92c-35b304de5e8d::urn:schemas-upnp-org:device:InternetGatewayDevice:1}]

Report:
        * UDP: true
        * IPv4: yes, 172.17.0.1:42098
        * IPv6: no, but OS has support
        * MappingVariesByDestIP:
        * HairPinning: false
        * PortMapping: UPnP, NAT-PMP, PCP
        * Nearest DERP: AA
        * DERP latency:
                -  j6: 19.1ms  (AA)

**Comment by kelivel** [comment]
Hi @weiyideai520, this looks like a configuration issue as the bugreport shows a validation issue with your certificate authority.

> derphttp.Client.Send connect to region 900 (myderp): x509: certificate signed by unknown authority

The client devices need to trust the certificate authority issued to the relay in order for Tailscale to make the TLS connection, and Installing the certificate only on the browser, for example, isn't sufficient. This isn't something that we can help troubleshoot directly, unfortunately, but hopefully this gets you on the right path.

If you have other related questions, please feel free to drop a line with our Support team at http://www.tailscale.com/support and we can help guide you in the right direction.

**Comment by weiyideai520** [comment]
Hi, Kelivel.

Thanks for your comments.
Now, I think I can fix it.
