### ISSUE TITLE
TrueNAS jail; fails to install on 13.3-Release

### ISSUE THREAD

**Issue by hatcreek68** [tailscale/tailscale#11507]
### What is the issue?

Fails to install on 13-3 release per typical process (https://www.truenas.com/community/threads/howto-install-tailscale-in-a-jail.98910/) but succeeds on 13-2 release. 

### Steps to reproduce

Attempt to install on 13-3 release. 

### OS

Other

### OS version

Truenas jail, freebsd 13-3-Release

**Comment by milesbarry** [comment]
Did you mean that you can't start the daemon? This is a known issue on TN 13 with a FreeBSD 13.3 jail.

If so, copy the daemon from the host to the jail as per 

https://www.truenas.com/community/threads/warning-dont-upgrade-your-truenas-core-jails-to-freebsd-13-3-just-yet.117018/

**Comment by hatcreek68** [comment]
Looks probable, thank you.  Closing since it seems outside Tailscale's scope?
