### ISSUE TITLE
Subnet Route with "Unapproved Route" state cannot get remove option in UI.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1150]
Unapproved Routes are not getting the option to remove it even after disabling.

![image](https://user-images.githubusercontent.com/75628398/104950686-22902700-598f-11eb-8d6a-47446d05c50f.png)
![image](https://user-images.githubusercontent.com/75628398/104950701-27ed7180-598f-11eb-8ae1-79b5ff4706e2.png)

**Comment by soniaappasamy** [comment]
To actually remove any routes, the user has to stop advertising them via the CLI. The route they want to remove should not be included in `advertise-routes` when running tailscale up.

See https://tailscale.com/kb/1019/subnets?q=subnet

**Comment by darshinimashar** [comment]
Thank you, Sonia, yes I suggested that to the customer, but he was looking for a remove option in UI.

**Comment by rosszurowski** [comment]
I'm going to close this out since it's working as intended. If we see much more confusion around this, we can look to improve our documentation to clarify this.
