### ISSUE TITLE
Fatal error: The current bundleIdentifier is unknown to the registry when running tailscale CLI from symlink on macOS

### ISSUE THREAD

**Issue by averms** [tailscale/tailscale#11510]
### What is the issue?

The CLI aborts before doing anything if I run it using the symlink.

### Steps to reproduce

I installed the Tailscale GUI app (tried both App Store and standalone versions). I read that the CLI is in `/Applications/Tailscale.app/Contents/MacOS/Tailscale`. I ran `ln -s /Applications/Tailscale.app/Contents/MacOS/Tailscale ~/.local/bin/tailscale`. I tried to use the CLI by running `tailscale status` but I got

```
Tailscale/BundleIdentifiers.swift:37: Fatal error: The current bundleIdentifier is unknown to the registry
Trace/BPT trap: 5
```

### OS

macOS

### OS version

macOS 14.4

### Tailscale version

1.62.0

**Comment by tomhjp** [comment]
I stumbled on this error myself, and while I'm not sure of the reason for this error, I did find a few relevant updates worth adding to this issue:

As of 1.68, the standalone Mac app has a utility (within settings) for installing `tailscale` into `/usr/local/bin`: https://tailscale.com/changelog#2024-06-12

More generally, if you're use the App Store version, the recommendation for Mac seems to be to set an alias: https://tailscale.com/kb/1080/cli?q=cli&tab=macos

```bash
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
```

But if neither of those options are appealing for whatever reason, a small executable shell script at `/usr/local/bin/tailscale` is one other alternative (this is pretty close to what the new utility in 1.68 does, but AFAIU App Store review rules wouldn't allow it):

```sh
#!/bin/sh
/Applications/Tailscale.app/Contents/MacOS/Tailscale "$@"
```

**Comment by kelivel** [comment]
Please use the built-in CLI functionality in the application settings. Feel free to reach out if the issue persists.

**Comment by moshekan** [comment]
Hi, using version 1.76.1 from the Appstore, it seems like the `Install Now` button is removed.

**Comment by dlamon1** [comment]
I'm getting this issue on 1.82.5, where is the CLI functionality in the application settings. MacOS

**Comment by bvonsnack** [comment]
I am getting this issue on Mac OS 26.2 and 1.92.2
