### ISSUE TITLE
Incorrect clock prevents DNS resolution when using Tailscale DNS

### ISSUE THREAD

**Issue by rohitsud** [tailscale/tailscale#11518]
### What is the issue?

I have a Macbook with a failing battery. When the power cord gets disconnected, the clock is reset to a time years in the past. At that time, if I have enabled Tailscale (and using its DNS) on my machine, no DNS requests work and all of them timeout. I need to disable Tailscale to let DNS requests work (in order to sync with an NTP server on the internet).

### Steps to reproduce

1. Reset clock to say 5 years in the past (simulate CMOS battery failure)
2. Reboot the machine (tried with OSX only)
3. Notice that on reboot no DNS requests resolve. Try a command like `sudo sntp -sS time.apple.com` to see that DNS resolution fails and does not allow the machine to sync using NTP.
4. Disable Tailscale using the app GUI.
5. Retry the command `sudo sntp -sS time.apple.com` and observe it works now.

### OS

macOS

### OS version

14.4

### Tailscale version

1.62.0

### Bug report

BUG-51aa2f348ddf2199a83ba618f810e5c5f821e8981ae52229acd575f2d8059f32-20240325173436Z-fd8dcd19fcb513b0

**Comment by timsoftgit** [comment]
I get  a similar issue. I can't run ntpdate pool.ntp.org  when my machine has the wrong time by an hour or so and is connected to a tail.
I have to manually change /etc/resolv.conf and put the local dns value in to update the time.

**Comment by rohitsud** [comment]
@kelivel Can TailScale use another mechanism to allow name resolution to bootstrap system time? Making system DNS fails because TailScale cannot allow DNS resolution seems to be something that only TailScale can address.
