### ISSUE TITLE
FR: Display custom DERP server's region name in Admin Panel

### ISSUE THREAD

**Issue by timtailscale** [tailscale/tailscale#11513]
### What are you trying to do?

Currently, the Machine details page only shows the custom DERP region number, rather than name in the **Latency** section: 
<img width="396" alt="image" src="https://github.com/tailscale/tailscale/assets/134532514/46a89199-680e-495d-84f9-35d15bcf26cd">

### How should we solve this?

If a `RegionName` field is specified in the custom DERP map defined in the ACLs, we should display it there instead of the region number.

### What is the impact of not solving this?

The machine details panel does not look as clean, and it is harder to tell which custom DERP server is being used if there are multiple.

### Anything else?

http://go/hs/33836

**Comment by bradfitz** [comment]
Sounds reasonable.

**Comment by Erisa** [comment]
This is done!
![image](https://github.com/user-attachments/assets/5d4eb60e-2360-4d29-ba0d-5424c7e4ccd8)
