### ISSUE TITLE
Docker container restart results in new machine instance in 'Machines' list

### ISSUE THREAD

**Issue by kssxs** [tailscale/tailscale#11527]
### What is the issue?

Whenever my QNAP automatically restarts (scheduled for once a week), and the TS docker container starts up, it creates a new machine in the Machines list with the same hostname, but a sequential number at the end.

I expected the restart to replace the existing machine instance in the list.

As a side note, this doesn't happen to my Raspberry Pi when it restarts, or even other client devices, only to my QNAP NAS docker instance.

I'm a free user, and if I didn't administer my account manually, eventually I would hit the free-user machine limit, potentially causing issues. I don't have a use case for a paid tier because I only access my home network and internal devices remotely as 1 user.

I would like to see a 'Replace Machine On New Instance' option to automatically delete the original instance of the machine, and name the new instance the same as the original hostname, if possible.

I know there are API scripts to programatically delete machines, but that would still require setting something up that should just be an option in the console.

Thanks for your attention to this!

### Steps to reproduce

Restart docker container on my QNAP NAS.

### Are there any recent changes that introduced the issue?

No, this behaviour has existed since I setup the TS docker container about 3 months ago.

### OS

Other

### OS version

QNAP QTS 5.1.5.2679

### Tailscale version

1.62.0

**Comment by kelivel** [comment]
Are you creating your Docker containers using an [ephemeral auth key](https://tailscale.com/kb/1111/ephemeral-nodes)? Docker containers are torn down and rebuilt when restarted, and using an ephemeral auth key will delete the old node from Tailscale after a few moments of no connectivity and replace it with the new container after a reboot.

**Comment by kssxs** [comment]
I am not using an ephemeral auth key.  I'm using a reusable key instead to avoid having the key expire, and also to avoid having to login again from the container on restart, but of course that is causing the issue of the new machine instance with sequential hostname.

Should I use an ephemeral key with a tag instead, and re-generate a key every 90 days?  Would that avoid the weekly restart issue?

**Comment by kssxs** [comment]
@kelivel: Any chance you can answer my questions?  Please and thanks! :)

**Comment by kelivel** [comment]
Sorry, I missed your last reply!

A (reusable) ephemeral key will make sure your old device is removed from the tailnet when restarted and recreated. You may need to add a `tailscale logout` to your script to immediately revoke the node key from the old machine which can speed up the ephemeral deletion process. You could add a tag to the standard ephemeral auth key as well, although that isn't strictly necessary to fix the behavior you reported originally.

Individually created auth keys, like the ones you're creating now, have a maximum 90 day expiry by default. You could create long-lived auth keys owned by the tailnet using an [OAuth client](https://tailscale.com/kb/1215/oauth-clients#generating-long-lived-auth-keys). Those are a little different from standard auth keys as devices created by an OAuth client, and thus owned by the tailnet, must be tagged.

**Comment by kssxs** [comment]
Thanks for that!

I used a new reusable ephemeral key (so not one-time use) and it worked flawlessly!

When I shutdown the container, the machine disappeard in the list within 3 seconds, and when it started up again, it was re-created in the list without any sequential name.

Nothing like hands-off admin for simple things.

I appreciate all your time and input in helping me fix this! :)

**Comment by kssxs** [comment]
Thanks for that!

I used a new reusable ephemeral key (so not one-time use) and it worked flawlessly!

When I shutdown the container, the machine disappeard in the list within 3 seconds, and when it started up again, it was re-created in the list without any sequential name.

Nothing like hands-off admin for simple things.

I appreciate all your time and input in helping me fix this! :)
