### ISSUE TITLE
Unable to Receive Files Taildropped to iOS Devices

### ISSUE THREAD

**Issue by jimmybrancaccio** [tailscale/tailscale#11524]
### What is the issue?

This was initially reported in a support ticket (34588). When sending files via Taildrop to an iOS device the user is unable to tap on the red banner in the Tailscale app to approve/receive the files being sent to them. It doesn't appear to matter what the sending device is (Windows, iOS, macOS). Both sending and receiving devices are using 1.62.0 of the Tailscale app.

**Update:** Customer was able to confirm a workaround is to ensure notifications is enabled for the Tailscale app. When a notification pops up they can tap on that to receive the files. It's just the red banner in the app doesn't work.

### Steps to reproduce

1. From one device select and send a file or files to send to an iOS device.
2. On the iOS device observe tapping on the red banner to receive the files in the Tailscale app does nothing.

### Are there any recent changes that introduced the issue?

It appears this was previously working prior to 1.62.0. @kelivel [noted](https://tailscale.slack.com/archives/C035EKBN72L/p1711467737675869?thread_ts=1711467557.936689&cid=C035EKBN72L) this appears to also be an issue in the unstable iOS build.

### OS

iOS

### OS version

iOS 17.4.1

### Tailscale version

1.62.0

### Bug report

BUG-72bfa60d99263bb6c7f574f1b9d6ea30a7b42f683e0ee19c00d887d61948d7ce-20240326152403Z-b0a0815321369307

**Comment by agottardo** [comment]
A fix will be landing in the next TestFlight update.
