### ISSUE TITLE
Linux after update 1.62.1 tailscaled "panic" return to 1.62.0 OK

### ISSUE THREAD

**Issue by father-mande** [tailscale/tailscale#11549]
### What is the issue?

After update to 1.62.1 from 1.62.0 tailscale crash at start

### Steps to reproduce

Even on other similar system without problem (after update)
... update to 1.62.1 from 1.62.0 
also try after reboot

### Are there any recent changes that introduced the issue?

update tailscale

### OS

Linux, Windows, Android

### OS version

Linux Asustor ... ADM 4.2.7 (last) (Linux level Ubuntu 18.04+) 

### Tailscale version

1.62.1

### Other software

firewall (iptables) but all run as well before update
samba, sftp, ssh, etc. tailscale run in tmux session ...
[tmux-buffer_1620.txt](https://github.com/tailscale/tailscale/files/14792894/tmux-buffer_1620.txt)
[tmux-buffer_1621.txt](https://github.com/tailscale/tailscale/files/14792895/tmux-buffer_1621.txt)

Bug report is for 1.62.0 because no bugreport for failing tailscale 1.62.1

### Bug report

BUG-6b026df1215e9d3c3b149d45ea773ea8ee67ec6fee7b48a4ea5f73917280f604-20240328164432Z-2c49c9540638398a

**Comment by irbekrm** [comment]
Hi @father-mande thanks for opening the issue and providing the logs

>  github.com/coreos/go-iptables@v0.7.0/iptables/iptables.go:213 +0x15b
tailscale.com/util/linuxfw.(*iptablesRunner).AddMagicsockPortRule(0xc0002215f0?,
 0x21b0?, {0x10ca1c8?, 0x2?})

This seems to be the same as https://github.com/tailscale/tailscale/issues/11540- we are looking into fixing that. Meanwhile, downgrading to 1.62.0 should fix it for now.

**Comment by irbekrm** [comment]
Hi @father-mande ,

I would like to be able reproduce your issue and see if https://github.com/tailscale/tailscale/pull/11546 fixed it.

> Linux Asustor 

Is that tailscale running on NAS?

**Comment by father-mande** [comment]
Hi,

I will check #11546 to verify if this help

Asustor community is active and lot of integrator add software to  extend capabilities
tailscale delivered is validated by Asustor in the Asustor store (so open to all)
I am the integrator  ... I use it for my own network ... and manage to package it for all (after Asustor validation)

Tailscale (native so NOT in docker (even an incomplete version is also proposed as is by another guy) or any containers)
it run as well on x86_64 NAS series with new and old ADM version
it run on all arm64 series
it run on armhf (old) series
and at end with some addons on x86 (32 bits) NAS series

ALL can be used as an exit node or subnet router, even it's not first target

tailscale is proposed as an APKG (Asustor package) including for all NAS some kernel modules (ex. mark fpr iptables)
some (old) series require an other version of xtables-multi to be compatible (provide in APKG)
internal update mechanism are provide to get tailscale new version (so no need to wait for a specific APKG update) and restart it, tailscale update works as well to update ... but without systemd ... no restart ... the update mechanism can be automated using cron.
ALL functions are managed using a terminal command line : tailscale_mngt (WebUI is under build)

I am out of my lab, but I will check if I can open an access to a NAS (after isolate it) with the problem (because some NAS of the same series don't have it)

In all case, lot of thanks for your help, I have write post in Asustor forum to help other users in case ... and propose solution to go back (even for non Linux specialist)

Best regards.
Philippe.
NB perhaps you can check with Asustor to try to reproduce the fail ... I don't know if it's possible

**Comment by father-mande** [comment]
Hi,

After reading #11546, I have check ...
seems that system having the problem are configured to use IPv6 when other (update without problem) use only IPv4

So it's seems that it's a correct search way ...
I will build module to support filter table for IPv6 and or IP6_NF_IPTABLES ... to see if this change .... or using your solution when build can be tested.

I will work on it next days.

Philippe.

**Comment by father-mande** [comment]
Hi,
**Some news**
... I have compiled next version github : **1.63.0-dev20240330**
... even I am not a golang user / dev; ... so I just get version for x86_64 **dynamically** linked ... I don't see info to generate static  executable ... the exec I used ... and how generate for other platform ...
... it's a battle (for me) because NAS x86_64 used an relatively old libc ...
________
root@AS5202Taphil:/volume1/.@plugins/AppCentral/tailscale-native/bin # ./tailscaled --version
1.63.0-dev20240330
  track: unstable (dev); frequent updates and bugs are likely
  tailscale commit: e20ce7bf0cc517a9de738f67d2c0e2514e31133e
  go version: go1.22.1
root@AS5202Taphil:/volume1/.@plugins/AppCentral/tailscale-native/bin # ldd tailscaled
        linux-vdso.so.1 (0x00007ffee7357000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb0085b0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb008590000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb0083d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb0085d5000)
root@AS5202Taphil:/volume1/.@plugins/AppCentral/tailscale-native/bin # ./tailscale --version
1.63.0-dev20240330
  track: unstable (dev); frequent updates and bugs are likely
  tailscale commit: e20ce7bf0cc517a9de738f67d2c0e2514e31133e
  go version: go1.22.1
______
I have replaced actual failing version 1.62.1 with this one with your patches
**AND NOW ALL RUN AS WELL**
so your patch seems to solve the lack of ip6 filter table (I continue to work on it to add it to the NAS)

Here after For Your Information ... the status (NAS command line management tool view)
ASxxxx and FSxxxx are Asustor NAS, lr-ts are my own native port on QNAP , keenetic is my own port on keenetic router
_____
---- tailscale version
1.63.0-dev20240330
---- tailscale status
**100.108.xx.119  t-asxxxxtaphil       father.mande@ linux   -** (the failing node)
100.72....    as-202te             father.mande@ linux   offline
100.90....    keenetic-giga        father.mande@ linux   -
100.122.... lr-xxxx            father.mande@ windows offline
100.73....   lr-xxxx            father.mande@ windows offline
100.78....   lr-rp3baphil         father.mande@ linux   offline
100.78.....   lr-ts269aphil        father.mande@ linux   -
100.65.1.... t-as1002taphil       father.mande@ linux   offline
100.126..... t-as5002taphil       father.mande@ linux   -
100.77......   t-as6602taphil       father.mande@ linux   -
100.85.....   t-fs6706taphil       father.mande@ linux   -

\# Health check:
\#    - This is an unstable (development) version of Tailscale; frequent updates and bugs are likely
---- tailscale task running
root      475242       1  0 15:01 ?        00:00:00 /usr/local/AppCentral/tailscale-native/bin/tmux new-session -d -s tailscale-native
root      475256       1  2 15:01 pts/1    00:00:00 /usr/local/bin/tailscaled -state=/var/lib/tailscale/tailscaled.state -socket=/var/run/tailscale/tailscaled.sock -port 41641
root      475452       1  0 15:01 pts/1    00:00:00 /usr/local/bin/tailscale web -listen 0.0.0.0:8089
---- Priority apply to LAN and networks
0:      from all lookup local
2500:   from all to 192.168.10.0/24 lookup main
5210:   from all fwmark 0x80000 lookup main
5230:   from all fwmark 0x80000 lookup default
5250:   from all fwmark 0x80000 lookup unspec unreachable
5270:   from all lookup 52
32765:  from 192.168.10... lookup eth0-table
32766:  from all lookup main
32767:  from all lookup default
===== ACTUAL resolv.conf MUST contains tailscale 100.100.100.100 if DNSMagic is used

nameserver 100.100.100.100
search tail63c8.ts.net myasustor.com
----IPTABLES filter and Nat
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ts-input   all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ts-forward  all  --  anywhere             anywhere
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere

Chain ts-forward (1 references)
target     prot opt source               destination
MARK       all  --  anywhere             anywhere             MARK xset 0x40000/0xff0000
ACCEPT     all  --  anywhere             anywhere             mark match 0x40000/0xff0000
DROP       all  --  100.64.0.0/10        anywhere
ACCEPT     all  --  anywhere             anywhere

Chain ts-input (1 references)
target     prot opt source               destination
ACCEPT     all  --  t-as5202taphil.tail63c8.ts.net  anywhere
RETURN     all  --  100.115.92.0/23      anywhere
DROP       all  --  100.64.0.0/10        anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     udp  --  anywhere             anywhere             udp dpt:41641
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
ts-postrouting  all  --  anywhere             anywhere
MASQUERADE  all  --  172.17.0.0/16        anywhere

Chain DOCKER (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain ts-postrouting (1 references)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere             mark match 0x40000/0xff0000
_____

I will wait for a stable version with your patches.
Many thanks for your work.

best regards.
Philippe.

**Comment by father-mande** [comment]
Hi,

**Last news ...
I have added support for iptables for ipv6**
... seems that problem is also solved ... with version 1.62.1
________
root@AS5202Taphil:/volume1/.@plugins/AppCentral/tailscale-native/bin # tailscaled --version
1.62.1
  tailscale commit: 8ee5801a3d6b669620e38ee4fbe8b93d3b73af96
  other commit: 76428ac0be84b1f0e26cc21f9db2b048dabe2059
  go version: go1.22.1
________
**### BUT** your patch is always useful for "old" NAS if I don't have time or resources to rebuils ip6tables

**PLEASE** can you verify if all ip6 tables are build without error (I don't have running sample)
________
root@AS5202Taphil:/volume1/.@plugins/AppCentral/tailscale-native/bin # ip6tables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ts-input   all      anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ts-forward  all      anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain ts-forward (1 references)
target     prot opt source               destination
MARK       all      anywhere             anywhere             MARK xset 0x40000/0xff0000
ACCEPT     all      anywhere             anywhere             mark match 0x40000/0xff0000
ACCEPT     all      anywhere             anywhere

Chain ts-input (1 references)
target     prot opt source               destination
ACCEPT     all      t-as5202taphil.xxxxxxxx.ts.net  anywhere
ACCEPT     all      anywhere             anywhere
ACCEPT     udp      anywhere             anywhere             udp dpt:41641
root@AS5202Taphil:/volume1/.@plugins/AppCentral/tailscale-native/bin # ip6tables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
ts-postrouting  all      anywhere             anywhere

Chain ts-postrouting (1 references)
target     prot opt source               destination
MASQUERADE  all      anywhere             anywhere             mark match 0x40000/0xff0000
_______

Lot of thanks for you help
I manage to add quickly ip6tables for x86_64 and arm64 series ... for the other ... I wait for your patch in a stable delivery.

Philippe.

**Comment by irbekrm** [comment]
> I have added support for iptables for ipv6

Thank your very much for doing this.

And thank you for confirming that this works with a fix.

We are planning to cut a new Tailscale release next week, which should be tested with NAS too (cc @kelivel, I am actually less familiar with how to test on NAS). I guess that with that perhaps we can wait for the new release rather than cust another patch.

**Comment by father-mande** [comment]
Hi irbkrm,
I have build ip6tables and kernel for x86_64 NAS (including **ip6table_nat** (even if I am not sure of the usage ??)
... it's OK (tested) for "old" and "new" **ADM** (the Asustor Linux embedded delivery) ... 2 different kernel
I have do same for arm64 with -1 and actual kernel ... 
... for last series ... all include **ip6table_nat** 
... for previous series ... only **ip6table_filter**
Same for "old" armhf BUT also only **ip6table_filter**

So patch for bypass lack of ip6tables will be used on 'old" (EOL NAS) arm64 (-2 in term of kernel version) and on "old" (EOL NAS) x86 32 bits series.

I will create soon new APKG (Asustor package) ... just after new tailscale version will be available.

**To test on Asustor NAS,** I can, if you want, send your contact mail to Asustor App. support team ... so you will have an access to some dev. test NAS, support to use it can be directly done by Asustor and by me (no problem to help you if needed) ... for the native version but unfortunately not for docker ... I have definitively stop to use it.

Just remember that Asustor team (as other provider in Asus and other brand) are affected by the earthquake.

Philippe.

**Comment by father-mande** [comment]
Hi,

Just F.Y.I.
... 1.64.0 ignore error (ipv6 filter missing tables) ... so works ...
... ALL Asustor NAS have now possibility to set ip6tables (filter and nat), for all models and for some EOL model (but used by a large number of users)

Thanks.
Philippe.

**Comment by irbekrm** [comment]
Thank you very much for confirming it now works and thank you for your work enabling ip6tables!
