### ISSUE TITLE
Connection issue with docker v1.62.1 

### ISSUE THREAD

**Issue by QGJ37** [tailscale/tailscale#11540]
### What is the issue?

Since the last update 1.62.1, I cannot reach my containers using Tailscale on Docker.
The ping is OK on IPV6 but NOK on IPV4
I have 2 différents servers with the same issue that appeared just after the last update.

### Steps to reproduce

Here is my Docker compose file:
`---
version: "3.7"
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts_omv
    hostname: omv
    environment:
      - TS_AUTHKEY=tskey-auth-********************
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=omv
      - TS_DEST_IP=***************
      - TS_USERSPACE=0
    volumes:
      - /srv/dev-disk-by-label-NAS6T01/AppData/tailscale/varlib:/var/lib
      - /srv/dev-disk-by-label-NAS6T01/AppData/tailscale/tmp:/tmp
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
`
Here is the log:
`boot: 2024/03/27 20:09:14 Starting tailscaled
boot: 2024/03/27 20:09:14 Waiting for tailscaled socket
2024/03/27 20:09:14 logtail started
2024/03/27 20:09:14 Program starting: v1.62.1-t2827330c6, Go 1.22.1: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--statedir=/var/lib/tailscale"}
2024/03/27 20:09:14 LogID: ***************************
2024/03/27 20:09:14 logpolicy: using system state directory "/var/lib/tailscale"
2024/03/27 20:09:14 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2024/03/27 20:09:14 dns: [rc=unknown ret=direct]
2024/03/27 20:09:14 dns: using "direct" mode
2024/03/27 20:09:14 dns: using *dns.directManager
2024/03/27 20:09:14 link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[172.23.0.2/16 llu6]} v4=true v6=false}
2024/03/27 20:09:14 onPortUpdate(port=43219, network=udp6)
2024/03/27 20:09:14 router: using firewall mode pref 
2024/03/27 20:09:14 router: default choosing iptables
2024/03/27 20:09:14 router: ipv6 unavailable due to missing filter table: running [/sbin/ip6tables -t filter -S --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.9 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
2024/03/27 20:09:14 router: v6filter = false, v6nat = false
2024/03/27 20:09:14 onPortUpdate(port=51169, network=udp4)
2024/03/27 20:09:14 magicsock: disco key = d:25e0f173aeba4730
2024/03/27 20:09:14 Creating WireGuard device...
2024/03/27 20:09:14 Bringing WireGuard device up...
2024/03/27 20:09:14 Bringing router up...
2024/03/27 20:09:14 external route: up
2024/03/27 20:09:14 Clearing router settings...
2024/03/27 20:09:14 Starting network monitor...
2024/03/27 20:09:14 Engine created.
2024/03/27 20:09:14 pm: using backend prefs for "profile-a676": Prefs{ra=false dns=false want=true routes=[] nf=on host="****" update=on Persist{lm=, o=, n=[pEV3f] u="***************"}}
2024/03/27 20:09:14 logpolicy: using system state directory "/var/lib/tailscale"
2024/03/27 20:09:14 got LocalBackend in 138ms
2024/03/27 20:09:14 Start
2024/03/27 20:09:14 Backend: logs: be:05993d3ef2acbb70eefc43b2a7b3838f4cee3383c115b27f1f78f2b1b3d236c8 fe:
2024/03/27 20:09:14 control: client.Login(false, 0)
2024/03/27 20:09:14 control: doLogin(regen=false, hasUrl=false)
2024/03/27 20:09:14 health("overall"): error: not in map poll
boot: 2024/03/27 20:09:14 Running 'tailscale up'
2024/03/27 20:09:14 Start
2024/03/27 20:09:15 control: client.Shutdown()
2024/03/27 20:09:15 control: client.Shutdown
2024/03/27 20:09:15 control: updateRoutine: exiting
2024/03/27 20:09:15 control: authRoutine: exiting
2024/03/27 20:09:15 control: mapRoutine: exiting
2024/03/27 20:09:15 control: Client.Shutdown done.
2024/03/27 20:09:15 Backend: logs: be:05993d3ef2acbb70eefc43b2a7b3838f4cee3383c115b27f1f78f2b1b3d236c8 fe:
2024/03/27 20:09:15 control: client.Login(false, 0)
2024/03/27 20:09:15 control: doLogin(regen=false, hasUrl=false)
2024/03/27 20:09:15 control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
2024/03/27 20:09:15 control: RegisterReq: onode= node=[pEV3f] fup=false nks=false
2024/03/27 20:09:15 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2024/03/27 20:09:15 control: netmap: got new dial plan from control
2024/03/27 20:09:15 using tailnet default auto-update setting: true
2024/03/27 20:09:15 EditPrefs: MaskedPrefs{AutoUpdate={Apply=true}}
2024/03/27 20:09:15 active login: ********************
2024/03/27 20:09:15 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
2024/03/27 20:09:15 monitor: gateway and self IP changed: gw=172.23.0.1 self=172.23.0.2
2024/03/27 20:09:15 magicsock: SetPrivateKey called (init)
2024/03/27 20:09:15 wgengine: Reconfig: configuring userspace WireGuard config (with 0/4 peers)
2024/03/27 20:09:15 wgengine: Reconfig: configuring router
2024/03/27 20:09:15 peerapi: serving on http://100.126.101.100:42731
2024/03/27 20:09:15 peerapi: serving on http://[fd7a:115c:a1e0::7c01:6564]:35206
2024/03/27 20:09:15 health("router"): error: could not add magicsock port rule v6: adding [-p udp --dport 43219 -j ACCEPT] in filter/ts-input: running [/sbin/ip6tables -t filter -A ts-input -p udp --dport 43219 -j ACCEPT --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.9 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
2024/03/27 20:09:15 magicsock: home is now derp-8 (lhr)
2024/03/27 20:09:15 magicsock: adding connection to derp-8 for home-keep-alive
2024/03/27 20:09:15 magicsock: 1 active derp conns: derp-8=cr0s,wr0s
2024/03/27 20:09:15 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2024/03/27 20:09:15 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#8 portmap= link="" firewallmode="ipt-default"}
2024/03/27 20:09:15 derphttp.Client.Connect: connecting to derp-8 (lhr)
2024/03/27 20:09:15 magicsock: endpoints changed: 169.155.255.0:51189 (stun), 172.23.0.2:51169 (local)
boot: 2024/03/27 20:09:15 using firewall mode pref 
boot: 2024/03/27 20:09:15 default choosing iptables
boot: 2024/03/27 20:09:15 [v1] kernel supports IPv6 policy routing (found 6 rules)
boot: 2024/03/27 20:09:15 ipv6 unavailable due to missing filter table: running [/sbin/ip6tables -t filter -S --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.9 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
boot: 2024/03/27 20:09:15 v6filter = false, v6nat = false
boot: 2024/03/27 20:09:15 Installing proxy rules
boot: 2024/03/27 20:09:15 Startup complete, waiting for shutdown signal
2024/03/27 20:09:15 magicsock: derp-8 connected; connGen=1
2024/03/27 20:10:23 wgengine: idle peer [mTUM9] now active, reconfiguring WireGuard
2024/03/27 20:10:23 wgengine: Reconfig: configuring userspace WireGuard config (with 1/4 peers)
2024/03/27 20:10:23 magicsock: disco: node [mTUM9] d:2eaae4cf2c27c70c now using 192.168.1.223:41641 mtu=1360 tx=62e22be4fcd9
2024/03/27 20:10:23 Accept: TCP{100.126.222.94:25921 > 100.126.101.100:8080} 52 tcp ok
2024/03/27 20:10:23 Accept: TCP{100.126.222.94:25922 > 100.126.101.100:8080} 52 tcp ok
2024/03/27 20:10:24 Accept: TCP{100.126.222.94:25921 > 100.126.101.100:8080} 52 tcp ok
2024/03/27 20:10:38 Accept: TCP{100.126.222.94:25921 > 100.126.101.100:8080} 52 tcp ok`

### Are there any recent changes that introduced the issue?

Yes, the last update 1.62.1

### OS

Linux

### OS version

Debian with Docker

### Tailscale version

1.62.1

### Bug report

BUG-05993d3ef2acbb70eefc43b2a7b3838f4cee3383c115b27f1f78f2b1b3d236c8-20240327202658Z-6550f78eb71eaf75

**Comment by RefineryX** [comment]
Also getting the same issue and now Tailscale no longer works. I have downgraded to ``v1.62.0`` and it is working again.

**Comment by irbekrm** [comment]
Hi @QGJ37 what host (kernel, OS) are you running your container on? Also, are you able to exec to a working version of the container (perhaps your previous working version) and provide output of `iptables -t filter -L`?

**Comment by QGJ37** [comment]
Hi, the container is running on an OpenMediaVault server:
Linux nas 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

I will try to exec a working version tomorrow

**Comment by rmblau** [comment]
I also have this same issue as well as a few others, however I am unable to successfully downgrade and get things to work so it may be unrelated issues on top of this

**Comment by irbekrm** [comment]
Thank you for reporting the issue folks.
I think #11546 should have fixed this issue. I have cut a new tag `unstable-v1.63.61` with the fix from that PR- if any of you get a chance to try that out and verify whether that worked, it would be much appreciated!

**Comment by QGJ37** [comment]
Hi, thanks for the fix.
I tested the unstable-v1.63.61 this morning.
It works perfectly for me.

**Comment by irbekrm** [comment]
> It works perfectly for me.

Thank you very much for confirming that!

> however I am unable to successfully downgrade and get things to work

@rmblau is this also for a containerized Tailscale? Would you be able to open an issue for this if you still have logs etc? Not being able to downgrade is certainly unexpected.

**Comment by rmblau** [comment]
> > It works perfectly for me.
> 
> Thank you very much for confirming that!
> 
> > however I am unable to successfully downgrade and get things to work
> 
> @rmblau is this also for a containerized Tailscale? Would you be able to open an issue for this if you still have logs etc? Not being able to downgrade is certainly unexpected.

@irbekrm I have opened #11556 with my specific issue. It's with the k8s operator.

**Comment by RefineryX** [comment]
> Thank you for reporting the issue folks. I think #11546 should have fixed this issue. I have cut a new tag `unstable-v1.63.61` with the fix from that PR- if any of you get a chance to try that out and verify whether that worked, it would be much appreciated!

Just to confirm, also tried ``unstable-v1.63.61`` and it works perfectly for me. Keeping myself on this version until it's merged.

**Comment by HomerBeer** [comment]
Got the same issue. Used the tag unstable-v1.63.61 and it works good again. But i try the new update (1.64.0) and i got the same issue again.

**Comment by irbekrm** [comment]
>  But i try the new update (1.64.0) and i got the same issue again.

We haven't released 1.64.0 container images yet

**Comment by HomerBeer** [comment]
> > But i try the new update (1.64.0) and i got the same issue again.
> 
> We haven't released 1.64.0 container images yet

2 days ago, latest 1.64.0

**Comment by irbekrm** [comment]
@HomerBeer we release container images a few days after the main Tailscale release. Currently there is no 1.64 container image available https://hub.docker.com/r/tailscale/tailscale/tags

**Comment by RefineryX** [comment]
Saw there was a release recently. Could anyone confirm if this has been fixed in the recent release?

**Comment by irbekrm** [comment]
> Saw there was a release recently. Could anyone confirm if this has been fixed in the recent release?

This should have been fixed in 1.64.1 that got released just now.
Please let us know either way

**Comment by irbekrm** [comment]
> The latest version don't work for me, i use the unstable again

Can you please add logs/bugreport as well as what host you are deploying the container on?

**Comment by RefineryX** [comment]
> > Saw there was a release recently. Could anyone confirm if this has been fixed in the recent release?
> 
> This should have been fixed in 1.64.1 that got released just now. Please let us know either way

Initial testing, seems to be working. Will report back here if I see any issues relating to this connection issue.

**Comment by irbekrm** [comment]
Seems like this was fixed in 1.64.1, closing
