### ISSUE TITLE
FR: Posturing to be able to discern between Windows 10 and Windows 11 Devices

### ISSUE THREAD

**Issue by andrewgbell** [tailscale/tailscale#11550]
### What are you trying to do?

We've implemented some basicWindows posturing on tailscale with great success.

However We'd like to be able to set a minimum version for Windows 10 and one for Windows 11.

We've set the "node:osVersion >= '10.0.19045.2965'", which will specify a minimum version of Windows 10.

However, this will also impact Windows 11 and allow any Windows 11 device to connect.

### How should we solve this?

It would be great if we could split these into two, e.g. something like 

for Win 10 where we can set a max and min value:
"node:osVersion >= '10.0.19045.2965'" & node:osVersion <= '10.0.19046.9999'

& the same for Win 11
"node:osVersion >= '10.0.22631.3296'" & node:osVersion <= '10.0.5000.9999'

### What is the impact of not solving this?

Unable to specify a minimum version of Windows 11, if there are Windows 10 devices in a tailnet.

**Comment by andrewgbell** [comment]
Should also add this could be applicable to Mac OS and Linux versions as well, to specify the latest update on a particular version.

**Comment by HeyMeco** [comment]
We need this!

**Comment by knyar** [comment]
> for Win 10 where we can set a max and min value:
> "node:osVersion >= '10.0.19045.2965'" & node:osVersion <= '10.0.19046.9999'

I believe you can list several conditions for the same attribute as part of the same posture, e.g.

```
"posture:win10": [
 "node:os == 'windows'",
 "node:osVersion >= '10.0.19045.2965'",
 "node:osVersion <= '10.0.19046.9999'",
],
"posture:win11": [
 "node:os == 'windows'",
 "node:osVersion >= '10.0.22631.3296'",
],
```
