### ISSUE TITLE
K8s operator unable to funnel

### ISSUE THREAD

**Issue by rmblau** [tailscale/tailscale#11556]
Hi all, I am trying to get the k8s operator to funnel correctly and am having some difficulty. I am running the latest unstable version as I had some networking issues that were resolved in that version. However, I am now getting this error regardless of which version of the operator I use.

```
boot: 2024/03/29 12:43:02 error checking get permission on secret ts-longhorn-funnel-5hsd6-0: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": context deadline exceeded
boot: 2024/03/29 12:43:02 error checking update permission on secret ts-longhorn-funnel-5hsd6-0: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": context deadline exceeded
boot: 2024/03/29 12:43:02 error checking patch permission on secret ts-longhorn-funnel-5hsd6-0: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": context deadline exceeded
boot: 2024/03/29 12:43:02 Starting tailscaled
boot: 2024/03/29 12:43:02 Waiting for tailscaled
socket
boot: 2024/03/29 12:43:02 Timed out waiting for tailscaled socket
```
I am not sure how to troubleshoot this and any tips or guidance would be great! Thank you!

**Comment by rmblau** [comment]
> Hi @rmblau 
> 
> > boot: 2024/03/29 12:43:02 error checking get permission on secret ts-longhorn-funnel-5hsd6-0: Post "https://kubernetes.default.svc/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": context deadline exceeded
> 
> This seems to be the proxy not being able to reach Kubernetes API server.
> Is the API server reachable on `kubernetes.default.svc` in your cluster and, if yes, can you confirm that you can reach it from a `Pod` in the `tailscale` namespace?
> 

@irbekrm as best that I can tell is that the cluster is accessible via tailscale. I'm using k3s and I have it joined to my tailnet. This used to work and then I had the issue that you resolved yesterday and it hasn't worked since. I'm fairly new to k8s. How can I get you the information you requested? The API server address appears to be a tailscale address as far as I can tell.

**Comment by irbekrm** [comment]
Is that a single node cluster? If not, is the proxy Pod scheduled on the same node as the operator?
Also, do you have access the Kubernetes API server? Perhaps there is something in the API server logs?

> context deadline exceeded

Unfortunately, this is a very vague message, so it could be any number of cluster issues.

The request that the proxy `Pod` makes is essentially:

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <contents of /var/run/secrets/kubernetes.io/serviceaccount/token in the proxy Pod> https://kubernetes.default.svc/apis/authorization.k8s.io/v1/s
elfsubjectaccessreviews -d '{"apiVersion": "authorization.k8s.io/v1","kind":"SelfSubjectAccessReview", "spec":{"resourceAttributes": {"namespace":"tailscale","verb":"patch","resource":"secrets","name":"secret-name"}
}}'
```
if there is nothing in the API server logs or you cannot access them, as a next step you could try to create another `Pod` in `tailscale` namespace, preferably scheduled on the same `Node` as the failing proxy `Pod` with `proxies` `ServiceAccount`, try to exec to that and see if you can run that `curl`. Let us know how it goes

**Comment by rmblau** [comment]
> Is that a single node cluster? If not, is the proxy Pod scheduled on the same node as the operator?
> Also, do you have access the Kubernetes API server? Perhaps there is something in the API server logs?
> 
> > context deadline exceeded
> 
> Unfortunately, this is a very vague message, so it could be any number of cluster issues.
> 
> The request that the proxy `Pod` makes is essentially:
> 
> ```
> curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <contents of /var/run/secrets/kubernetes.io/serviceaccount/token in the proxy Pod> https://kubernetes.default.svc/apis/authorization.k8s.io/v1/s
> elfsubjectaccessreviews -d '{"apiVersion": "authorization.k8s.io/v1","kind":"SelfSubjectAccessReview", "spec":{"resourceAttributes": {"namespace":"tailscale","verb":"patch","resource":"secrets","name":"secret-name"}
> }}'
> ```
> if there is nothing in the API server logs or you cannot access them, as a next step you could try to create another `Pod` in `tailscale` namespace, preferably scheduled on the same `Node` as the failing proxy `Pod` with `proxies` `ServiceAccount`, try to exec to that and see if you can run that `curl`. Let us know how it goes
> 
> 

@irbekrm I have created a pod in the same namespace on the same node as the failing pod and it gives me the same authorization required error. I've reset iptables and reinstalled k3s on that node and the error persists. I've been able to do an `nslookup` and get back info on the API server but that's about it. Any guidance would be appreciated.

**Comment by rmblau** [comment]
@irbekrm I have figured out the issue. It would appear that the second node fell off of tailscale. After rejoining the node to tailscale it has been able to funnel consistently. Thank you for your help!
