### ISSUE TITLE
IPv6 lazy configuration doesn't work

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1156]
Set up a machine that's never talked to other machines. Ping another node's IPv6 address. Pings time out, tailscale status on the target shows no active tunnels.

Now ping the ipv4 address. Pings work, tailscale status shows a tunnel got set up. Now, IPv6 ping also works.

Looks like lazy wg config isn't triggering correctly on IPv6 traffic.

**Comment by bradfitz** [comment]
Is it triggering disco?

**Comment by danderson** [comment]
Fixed in 9936cff.
