### ISSUE TITLE
FR: Tags for mullvad exit nodes in ACL

### ISSUE THREAD

**Issue by dolceAlka** [tailscale/tailscale#11574]
### What are you trying to do?

ports nonfunctional with tagged devices using ACL without the default allow all rule when using mullvad exit nodes.

### How should we solve this?

Make a tag for mullvad devices to configure over ACL, may be limited but should allow for allowing only mullvad exit nodes to access ports but not untagged devices

### What is the impact of not solving this?

Forced to allow all devices to go be able to do traffic to at least 1 port on some tag.
```{"action": "accept", "src": ["*"], "dst": ["tag:<tag>:<port>"]}```
(appears to have been broken with the 1.66 change in ACL semantics for the wildcard)

### Anything else?

If an existing tag exists, please put it in the docs.

**Comment by felschr** [comment]
This would solve issues like #10845, #11570.

Some other specific issues I've noticed:
- Anytype sync not working
- No server connection in some multiplayer games (e.g. We Were Here series on Steam)
- AusweisApp phone connection not working

**Comment by dolceAlka** [comment]
new patch in 1.66 seems to have broken the workaround as it seems that autogroup:danger-all does not include mullvad nodes

**Comment by dolceAlka** [comment]
no dns over public ip for both linux and windows with dig google.com @1.1.1.1

**Comment by oatmealm** [comment]
How can I use this fix now? running into this problem. Is it something that needs to be done on the client side or the global access control on the service's side?

**Comment by dolceAlka** [comment]
used to work on global ACL, now i think it doesn't work anymore, i'm just using plain wireguard for vpn services and then tailscale between my own devices

**Comment by xiolo** [comment]
Same issue here with 1.66+, to the point where all outbound UDP trackers for P2P, or DNS traffic (dig@1.1.1.1)fails.

**Comment by xiolo** [comment]
Any updates on this? This makes Mullvad usage for torrents/UDP unusable

**Comment by oatmealm** [comment]
It's working for me!!

> It sounds like it was fixed with 1.66.4: https://tailscale.com/changelog#2024-05-20

**Comment by dolceAlka** [comment]
sorry i can't confirm as i'm not on mullvad with tailscale anymore

**Comment by awly** [comment]
I'll mark this as done, based on a few confirmations above.
