### ISSUE TITLE
Check v6 behavior on macOS/iOS

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1157]
Need to check that the IPv6 logic in the common Tailscale codebase doesn't break the mac/ios apps. Unlikely since the VPN frameworks are reasonably good, but still needs testing.

Currently blocked by me not having a mac to test with.

**Comment by crawshaw** [comment]
Tested on macOS, seems to work. I need to push a TestFlight to try on iOS (no cable handy).

**Comment by crawshaw** [comment]
With the latest testflight (1.5.179) I can ipv6 ping both from and to my phone.

V6 address discovery is very hard! Typing it into a phone keyboard is even harder!

**Comment by crawshaw** [comment]
@danderson besides pinging IPv6 addresses, anything else you'd like me to test here? Are you sharing a v6 subnet I could try reaching?

**Comment by danderson** [comment]
Nothing else to check, that's good.
