### ISSUE TITLE
FR: Add ssh terminal access from TailScale web interface

### ISSUE THREAD

**Issue by scouzi1966** [tailscale/tailscale#11576]
### What are you trying to do?

It would be nice if I could login Tailscale account and access a terminal app where I could ssh into the endpoints from the 'web' endpoint

### What is the impact of not solving this?

Cannot install Tailscale agent on my work laptop without violating employer policy.

**Comment by bradfitz** [comment]
https://tailscale.com/tailscale-ssh does already?

However over the "..." and you get a web-based SSH client using Tailscale in wasm:

<img width="276" alt="Screenshot 2024-04-01 at 12 51 03 PM" src="https://github.com/tailscale/tailscale/assets/2621/a447784f-b52d-4a9d-957f-0b00ecc16647">

**Comment by bradfitz** [comment]
> EDIT: Thanks it works now

Glad you got it working!
