### ISSUE TITLE
Bad URL's in release notes

### ISSUE THREAD

**Issue by ronabop** [tailscale/tailscale#11578]
### What is the issue?

Invalid URLS  (maybe only invalid to public/externals) are used in the latest release notes.

### Steps to reproduce

This release note: https://github.com/tailscale/tailscale/releases/tag/v1.62.1 has links for "standalone" and "Kubernetes operator" that point to:
https://tailscale-www-2113cfcf.fly.dev/kb/1065/macos-variants
and
https://tailscale-www-2113cfcf.fly.dev/kb/1236/kubernetes-operator/

Prior release of 1.62.0 had
https://tailscale.com/kb/1065/macos-variants for "standalone".

Using the same URL modification pattern, https://tailscale.com/kb/1236/kubernetes-operator seems like the correct target for the "Kubernetes operator" link

### Are there any recent changes that introduced the issue?

Latest release has bad links, prior release did not.

Going several version back in history, there does not seem to be a consistent pattern for having links, or not, in notes.

Reference:
https://github.com/tailscale/tailscale/releases?page=1

**Comment by bradfitz** [comment]
Thanks. Fixed!
