### ISSUE TITLE
The exit node showed `offline`, but the connection is okay

### ISSUE THREAD

**Issue by wd** [tailscale/tailscale#11587]
### What is the issue?

I saw that the exit node was `offline`. 
```
/Applications/Tailscale.app/Contents/MacOS/Tailscale status
100.87.60.79    exit-node-1  someone@      linux   active; exit node; direct node-ip:41641; offline, tx 181866880 rx 949256916
```

But I can access services only allows traffic via tailscale. And the tailscale ping command also worked. 

```
/Applications/Tailscale.app/Contents/MacOS/Tailscale ping 100.87.60.79
pong from exit-node-1 (100.87.60.79) via node-ip:41641 in 58ms
```

I also checked my IP address on https://ifconfig.me/, it showed the exit node IP. 

### Steps to reproduce

I don't know how to reproduce it. I notice this issue when I saw a red cross on the tailscale icon in the menu bar. 

### OS

macOS

### OS version

13.6.2 (22G320)

### Tailscale version

1.56.1

**Comment by wd** [comment]
> Are you using Headscale?

Nope, I think we are using the Tailscale enterprise plan.

**Comment by wd** [comment]
I forgot to metion. We observed this happened more often for our employes in China. The exit node is in China as well.

**Comment by bradfitz** [comment]
If you have an enterprise plan, let's move this to a ticket with support@. We generally don't debug China connectivity issues in this public forum.
