### ISSUE TITLE
Faster startup of Tailscale daemon on Linux & Systemd

### ISSUE THREAD

**Issue by kernelb00t** [tailscale/tailscale#11599]
### What is the issue?

The issue is that the Tailscale daemon is taking 1.5s off boot time while blocking the boot chain. After waiting for `NetworkManager` and `systemd-resolved` to be up, the daemon starts. It needs 1.5s to boot. As it is `WantedBy = multi-user.target`, it blocks any graphical interface from starting, thus slowing down the perceived boot time. Is there a Type of unit file and dependency setup that can at least allow non blocking startup of the daemon after NM and resolved?

### Steps to reproduce

- Take a stock Arch Linux installed with `arch-install`, with GNOME desktop, NetworkManager installed.
- Install and setup Tailscale.
- Cold start your machine
- Execute `systemd-analyze`, `systemd-analyze blame` and `systemd-analyze critical-chain` to see recorded boot times.
- Disable the `tailscaled.service`, reboot and check boot times.

### Are there any recent changes that introduced the issue?

Nope, has been slow for 2 years (or more, there's a long time I started using Tailscale). Issue started being noticed when I started to try to enhance boot time on my laptop. Doesn't look like a regression to me.

### OS

Linux

### OS version

Arch Linux latest

### Tailscale version

1.62.1

### Other software

The setup does not diverges much from standard Arch Linux. I use systemd, NetworkManager and systemd-resolved for networking. I use Unified Kernel Images or GRUB for boot. GNOME desktop, no Docker nor any VPN running (I have Proton installed as a Flatpak but I made sure it isn't started at boot). I have an HP Probook 650 G8 (i3 11th, 4GB RAM, Intel WiFi).

### Bug report

BUG-b92f6512d24865f61d6bf4390f51d624562d5809be830b25cfaa4ed2d9abb0ca-20240402235819Z-8d396ab30b23aef1

**Comment by bradfitz** [comment]
And presumably if we fixed https://github.com/tailscale/tailscale/issues/11504 it would be even slower.

**Comment by raggi** [comment]
It looks like the root cause is coming from under the pre-start cleanup:

```
ExecStartPre=/usr/sbin/tailscaled --cleanup
```

This is unexpected, it should be a simple function that ensures there are not stale tailscale firewall rules installed.
