### ISSUE TITLE
Unable to share a node between Google Accounts

### ISSUE THREAD

**Issue by akmzero** [tailscale/tailscale#11606]
### What is the issue?

I am trying to share a node with another user, both accounts use Google for auth.

We've tried modifying ACL's and using the default version of it.

The error being give is just 'Failed to Accept Invite'

### Steps to reproduce

Sharing any node, new or old.

Using Google Accounts for Auth.

We've tried accepting the invite from MacOS, Linux, Android, and Windows.

### Are there any recent changes that introduced the issue?

Nope, tried on nodes that have been on my tailnet for months, as well as new nodes added for testing.

### OS

Linux, macOS, Windows, Android

### OS version

Ubuntu 22.04LTS, Proxmox 8.1

### Tailscale version

1.62.1

### Bug report

BUG-f4580ed79c6147facd5c06fd0b38ec03a9f03ac01b0ad566e36c8e6a0195aac2-20240403155445Z-262cfb4ca052d878

**Comment by cesarandreslopez** [comment]
Several users (including myself) reporting this today, April 3rd, here:

https://github.com/tailscale/tailscale/issues/3638

**Comment by jochym** [comment]
The https://github.com/tailscale/tailscale/issues/3638 is closed and old. I think this is a new issue and should be reported in a new thread. I have also submitted a support request about it by tailscale website/bugreport mechanism.

**Comment by kelivel** [comment]
Hi all, we've identified the root cause and will have a fix shipped out soon. Thanks for the patience in the meantime.

**Comment by TumM0reNcE5SsIti** [comment]
I am also experiencing this issue, and want to contribute a bit of my experience, as well. It started when my endpoint (on my tailscale) was "refused" on another tailscale. The device could not interact with my tailscale, from theirs.

They removed my device from my tailscale, I generated a new invite link, and then they couldn't re-add the device to their tailscale. So, now, we have a production issue with my github authenticated device and their microsoft authenticated device.

A huge headache, and looking forward to the fix soon. Thanks team!
PS: Hard down until this is fixed...

**Comment by TumM0reNcE5SsIti** [comment]
Decided to re-write my follow-up since it evidently tracks edits...didn't know that. Thanks GitHub!

My experience has been this so far:
I got user reports outside my tailscale of the following steps.
- User tries to access a resource that worked recently
- The resource shows as completely unavailable to them (cannot be pinged or used)
- The tailscale web gui says they still have access
- A troubleshooting step was to remove the problematic machine and re-add with a new link
- The new link results in a "Failed to add machine" message.

Now, as of this writing, things have changed slightly.
- Users outside my tailscale (tailnet) are still unable to access previously added machines
- New links being generated (since they are still in my ACLs) are being accepted, but they are still unable to connect to the resources, even though the admin center says the devices are online.

This is a huge headache, and don't know how to move forward minus revoking everyones access to old machine "links" and forcing them to re-add all these machines to their tailscales...which is going to be a huge pita.

**Comment by akmzero** [comment]
Just tested and was able to accept the node invite.

**Comment by TumM0reNcE5SsIti** [comment]
I am also able to accept node invites, but connectivity is still broken to the host node.
I've already done the due diligence of resetting dns on the calling machine, but that's not helping. The "new" node (and "old" nodes) are completely inaccessible currently.

Not sure what's happening, but my production environment is inaccessible from outside of my tailnet.
**NOTE**: ACLs haven't changed in two weeks, so I know that's not the issue.

**Comment by akmzero** [comment]
> I am also able to accept node invites, but connectivity is still broken to the host node. I've already done the due diligence of resetting dns on the calling machine, but that's not helping. The "new" node (and "old" nodes) are completely inaccessible currently.
> 
> Not sure what's happening, but my production environment is inaccessible from outside of my tailnet. **NOTE**: ACLs haven't changed in two weeks, so I know that's not the issue.

I was able to connect to the new node without issue.

I know you said that ACL's haven't changed, but have you verified your tags?

Also verify that they haven't expired.

**Comment by TumM0reNcE5SsIti** [comment]
> > I am also able to accept node invites, but connectivity is still broken to the host node. I've already done the due diligence of resetting dns on the calling machine, but that's not helping. The "new" node (and "old" nodes) are completely inaccessible currently.
> > Not sure what's happening, but my production environment is inaccessible from outside of my tailnet. **NOTE**: ACLs haven't changed in two weeks, so I know that's not the issue.
> 
> I was able to connect to the new node without issue.
> 
> I know you said that ACL's haven't changed, but have you verified your tags?
> 
> Also verify that they haven't expired.

No expirations, tags are correct, ACLs are correct (even tested catch all *:* to test).
All external access is currently severed if it's not on my own tailnet.
**All shared resources.**

**Comment by akmzero** [comment]
> > > I am also able to accept node invites, but connectivity is still broken to the host node. I've already done the due diligence of resetting dns on the calling machine, but that's not helping. The "new" node (and "old" nodes) are completely inaccessible currently.
> > > Not sure what's happening, but my production environment is inaccessible from outside of my tailnet. **NOTE**: ACLs haven't changed in two weeks, so I know that's not the issue.
> > 
> > 
> > I was able to connect to the new node without issue.
> > I know you said that ACL's haven't changed, but have you verified your tags?
> > Also verify that they haven't expired.
> 
> No expirations, tags are correct, ACLs are correct (even tested catch all _:_ to test). All external access is currently severed if it's not on my own tailnet. **All shared resources.**

That sounds like a different issue than this one.  

I would make a separate issue as you're having different, as well as additional issues as myself.

**Comment by TumM0reNcE5SsIti** [comment]
> 
> That sounds like a different issue than this one.
> 
> I would make a separate issue as you're having different, as well as additional issues as myself.

Fair enough. Thanks @akmzero

**Comment by vipersl65** [comment]
I just installed it today Feb 22,2026 in my iphone 16 pro max with latest ios and in Windows 11 Laptop .  I tried to send invite to each other and I get a failed to accept invite

**Comment by harishkumar9640** [comment]
I am using iphone 15 pro and macbookpro m3 with all latest OS's. I sent invite via email to my mobile and when accepting the request I have seen the same problem 'Failed to Accept Invite'. Can anyone help on this bug, or is there any workaround for this issue ?

**Comment by richhickson** [comment]
IVe just tried to share a device from one Microsoft authed account (my cleints) to my account authed by Google. When i accept invite I get the "Failed to accept invite" message.
