### ISSUE TITLE
kubernetes ingress node injects non-ascii printable characters in headers

### ISSUE THREAD

**Issue by CosmicToast** [tailscale/tailscale#11603]
### What is the issue?

Tailscale's ingress nodes as created by the kubernetes operator add the `Tailscale-User-Name` header.
This header can contain non-ASCII contents (example: my name).
While the HTTP specification does explicitly allow at least Latin Extended 1 characters, other specifications (such as gRPC) do not.
I'm also tracking this issue against grpc-go here: [grpc/grpc-go#7074](https://github.com/grpc/grpc-go/issues/7074).

### Steps to reproduce

1. Have a name that contains a u8 outside of the printable ASCII range. An é is a good testing point.
2. Expose a kubernetes service that uses a recent grpc-go via an ingress load balancer. A good testcase is argo-workflows-server, since it will cause the problem even just logging in by the webui, not only in the cli.
3. Try to connect to it and observe the error code 13. See the upstream issue report for the exact location where the error generates.

### Are there any recent changes that introduced the issue?

From what I can tell the source for it is https://github.com/tailscale/tailscale/issues/6954.
I haven't looked too deeply into it yet, but my guess is that the ingress nodes run `tailscale serve` under the hood.

### OS

Linux

### OS version

Fedora 39

### Tailscale version

1.62.1

### Other software

I technically have firewalld, some socks5 ssh proxies, and zerotier. I've tested with all of those disabled.
The core part that is shared is with the kubernetes operator and its provisioned ingress nodes.

### Bug report

BUG-ba3edd6b9fcc09ac989d693b7fad4ce37b6cf90bdd88ae338a18c8e7b6535d6a-20240403125305Z-114e7e09b52d6641

**Comment by CosmicToast** [comment]
Some possible resolutions:
* Making it possible to disable those headers via an attribute on the ingress node. This is important since it may be desirable to have it on some services (that are known to behave nicely with such content) vs others.
* Punycode / URL-encode / other encoding system of non-ASCII data in headers.
* Detect non-ASCII data in headers and instead send a `-bin` version of the header that is base64-encoded.

**Comment by bradfitz** [comment]
@CosmicToast, https://github.com/tailscale/tailscale/pull/11605 is now merged. This will be fixed in the next unstable release soon and next stable release in a couple weeks. We probably can't cherry-pick it back to an earlier stable patch release because it's somewhat of a breaking change for non-gRPC users. We'll need to add it to the release notes.

**Comment by irbekrm** [comment]
`1.63.78` helm chart version/`unstable-v1.63.7` image tags have just been pushed and will have Brad's fix

**Comment by CosmicToast** [comment]
LGTM, thanks!
Can I subscribe somewhere to get a ping when I can update the kubernetes operator / loadbalancing nodes to get this fix in?
Otherwise good to close on my end.
