### ISSUE TITLE
`tailscale up` indefinitely hangs on Debian Bookworm, Tailscale version 1.62.1

### ISSUE THREAD

**Issue by VenomousSteam81** [tailscale/tailscale#11608]
### What is the issue?

`tailscale up` indefinitely hangs on Debian Bookworm, Tailscale version 1.62.1.
I expect `tailscale up` to work like normal.

`journalctl -u tailscaled.service` and `systemctl status tailscaled` log output:
```
Apr 03 11:28:08 shitbook tailscaled[1906]: control: LoginInteractive -> regen=true
Apr 03 11:28:08 shitbook tailscaled[1906]: control: doLogin(regen=true, hasUrl=false)
Apr 03 11:28:13 shitbook tailscaled[1906]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
```

Ignore my hostname, I'm actually running this on a Chromebook (shouldn't be the problem as it worked before).

### Steps to reproduce

1. Run the install script
2. Run `sudo tailscale up`
3. Hangs infinitely until I press `ctrl`+`c`. The output given when pressing `ctrl`+`c` is `context canceled`.

### Are there any recent changes that introduced the issue?

I have no idea. I do know that I'm installing on a fresh machine. Tailscale worked fine on the previous install. I had never updated the package so this could be why I'm experiencing this now.
`sudo tailscale login` also hangs indefinitely. I had removed my last install's machine removed from the admin panel, and since I'm not logged in, that wouldn't help anyways.

### OS

Linux

### OS version

Debian Bullseye

### Tailscale version

1.62.1

### Other software

I do not have any extra software.

### Bug report

BUG-70f373e33198105f37a0c5547e166ee0d4ea0ee480add064d13a7af56f428398-20240403162538Z-c3cf4b4356b6ca23

**Comment by VenomousSteam81** [comment]
It also appears that my `/etc/resolv.conf` is not complete. I actually have my old `/etc/resolv.conf` (from the previous install) and the 2 look similar but the current one is missing some things.

Old `resolv.conf`:
```
# resolv.conf(5) file generated by tailscale
# For more info, see https://tailscale.com/s/resolvconf-overwrite
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search (redacted).ts.net lxd
```

Current `resolv.conf`:
```
domain lxd
search lxd
nameserver 100.115.92.193
```
Before I sent this comment, I tried overriding my current `resolv.conf` to my old `resolv.conf` and after a reboot and running `sudo tailscale up`, it changes back to the current output. Any ideas?

**Comment by VenomousSteam81** [comment]
Here's my full `journalctl -u tailscaled.service` log
```
Apr 03 09:11:43 shitbook tailscaled[1192]: logtail started
Apr 03 09:11:43 shitbook tailscaled[1192]: Program starting: v1.62.1-t8ee5801a3-g76428ac0b, Go 1.22.1: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41641"}
Apr 03 09:11:43 shitbook tailscaled[1192]: LogID: 70f373e33198105f37a0c5547e166ee0d4ea0ee480add064d13a7af56f428398
Apr 03 09:11:43 shitbook tailscaled[1192]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Apr 03 09:11:43 shitbook tailscaled[1192]: wgengine.NewUserspaceEngine(tun "tailscale0") ...
Apr 03 09:11:43 shitbook systemd[1]: Started tailscaled.service - Tailscale node agent.
Apr 03 09:11:43 shitbook tailscaled[1192]: router: error querying IP rules (does kernel have IP_MULTIPLE_TABLES?): operation not supported
Apr 03 09:11:43 shitbook tailscaled[1192]: router: warning: running without policy routing
Apr 03 09:11:43 shitbook tailscaled[1192]: dns: [rc=unknown ret=direct]
Apr 03 09:11:43 shitbook tailscaled[1192]: dns: using "direct" mode
Apr 03 09:11:43 shitbook tailscaled[1192]: dns: using *dns.directManager
Apr 03 09:11:43 shitbook tailscaled[1192]: link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[100.115.92.204/28 llu6]} v4=true v6=false}
Apr 03 09:11:43 shitbook tailscaled[1192]: onPortUpdate(port=41641, network=udp6)
Apr 03 09:11:43 shitbook tailscaled[1192]: router: using firewall mode pref
Apr 03 09:11:43 shitbook tailscaled[1192]: router: default choosing iptables
Apr 03 09:11:43 shitbook tailscaled[1192]: router: disabling tunneled IPv6 due to system IPv6 config: kernel doesn't support IPv6 policy routing: querying IPv6 policy routing rules: operation not supported
Apr 03 09:11:43 shitbook tailscaled[1192]: magicsock: [warning] failed to force-set UDP read buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
Apr 03 09:11:43 shitbook tailscaled[1192]: magicsock: [warning] failed to force-set UDP write buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
Apr 03 09:11:43 shitbook tailscaled[1192]: onPortUpdate(port=41641, network=udp4)
Apr 03 09:11:43 shitbook tailscaled[1192]: magicsock: [warning] failed to force-set UDP read buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
...skipping...
Apr 03 12:12:31 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:34 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:34 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:12:39 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:40 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:40 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:12:46 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:48 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:48 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:12:53 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:55 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:55 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:00 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:04 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:04 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:09 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:13 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:13 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:18 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:21 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:21 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:27 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:32 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:32 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:37 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:41 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:41 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:46 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:51 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:51 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:57 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:02 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:02 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:07 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:12 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:12 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:17 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:26 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:26 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:31 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:37 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:37 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:43 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
...skipping...
Apr 03 12:12:31 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:34 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:34 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:12:39 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:40 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:40 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:12:46 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:48 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:48 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:12:53 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:12:55 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:12:55 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:00 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:04 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:04 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:09 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:13 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:13 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:18 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:21 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:21 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:27 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:32 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:32 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:37 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:41 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:41 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:46 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:13:51 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:13:51 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:13:57 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:02 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:02 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:07 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:12 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:12 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:17 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:26 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:26 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:31 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
Apr 03 12:14:37 shitbook tailscaled[199]: control: LoginInteractive -> regen=true
Apr 03 12:14:37 shitbook tailscaled[199]: control: doLogin(regen=true, hasUrl=false)
Apr 03 12:14:43 shitbook tailscaled[199]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded
```

**Comment by kmadaras** [comment]
Same exact issue on Debian Bookworm.  A device that used to be part of my tailnet that I'm trying to re-enroll.

**Comment by dlampa** [comment]
Same exact issue, Ubuntu 22.04, kernel 5.15.0-101.

**Comment by VenomousSteam81** [comment]
> Here's how I solved my issue.
> 
> I am using Netplan. I had different name server entries on my internal and external interfaces. I edited /etc/netplan/netplan.yaml to remove the nameservers and search domain from my LAN interface. I appended the name servers and the seaarch domain to my WAN interface.
> 
> run: netplan apply
> 
> It may not be everyone's solution, yet it did work in my instance. In my case I have 2 nics and a public interface because it's a jumpbox.
> 
> This is a regression as it worked in the past.

I don't have netplan but I'm glad that fixed your issue. My issue could also be related to nameservers as well.

**Comment by dlampa** [comment]
Thanks @kmadaras . Turns out my issue is specific to the network on my end (someone blocked `controlplane.tailscale.com`). Noticed only after windows clients started disconnecting too.

**Comment by VenomousSteam81** [comment]
I'm messing around a little bit and https://controlplane.tailscale.com/key?v=88 doesn't load and instead says that the response took too long (I thought it did but I could be wrong) but I can ping it just fine. I don't believe it's blocked in any way.

**Comment by iskandarluqman** [comment]
It happened to me yesterday while I was setting up my resolv.conf. Its been awhile since my docker containers cannot resolve DNS. Im using Pi-hole as my DNS resolver. Hosted on the same Debian. 

Since I couldnt figure it out, I decided to reset my resolv.conf on Debian by running "sudo apt-get remove --purge resolvconf && sudo apt-get install resolvconf" . and that worked, after putting 127.0.0.1 as the nameserver in resolv.conf, everything was working. The host and dockers containers can resolve DNS .

But somewhat in the process Tailscale failed. I thought it had something to do with me messing with resolv.conf but everything can resolve DNS on host and docker containers with no issues. Ping controlplane.tailscale.com as well, no issue. So I am at a dead end how to fix this issue. 

"Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=88": context deadline exceeded"

**Comment by dlampa** [comment]
Being able to ping/resolve a host is not the same as being able to connect to the specific port/service, eg. HTTPS. I'm also able to ping the controlplane, but the https port is filtered.

**Comment by VenomousSteam81** [comment]
Ok, that makes sense.

**Comment by iskandarluqman** [comment]
@dlampa I see. How do I make sure if my Debian is filtering the https? I should have mentioned previously before messing with the resolv.conf, Tailscale was able to connect. It is currently hosted in Proxmox, which also has Tailscale and the only reason I am still able to manage my Debian server remotely. I also have another Tailscale in a docker container for an exit node for commercial VPN and connects perfectly. I did tried disable the Tailscale in Docker just for good measure, still no luck. It won't connect on the host Debian itself, so I am started to wondering if Tailscale uses other than resolv.conf.

**Comment by cangcn** [comment]
Same issue on 2204 jammy. this happens after I run sudo apt-get update for updating all packages including tailscale.

**Comment by VenomousSteam81** [comment]
Is there any way to downgrade tailscale? I want downgrade until I find a version that works.

**Comment by VenomousSteam81** [comment]
I wonder if this is an issue with servers or something because I just went all the way down to version `1.50.0` and the same issue is still present.

**Comment by VenomousSteam81** [comment]
Even the unstable version does the same thing (I can understand that).

**Comment by cangcn** [comment]
@VenomousSteam81 Hi, I encountered the same issue. After updating Tailscale using "sudo apt-get update", the Tailscale connection was lost. It seems that this issue originates from an authorization problem, where the authorization page is blocked by network administration. Here's a potential solution:

1. Switch your server's internet connection to another ungoverned network, such as a personal hotspot.
2. Start your Tailscale service using this personal connection.
3. Then, switch your connection back to the original governed network.

**Comment by dbogdanov** [comment]
Thank you, @cangcn! Your workaround worked for me, except (it seems) for the MagicDNS.

**Comment by VenomousSteam81** [comment]
@cangcn 
> @VenomousSteam81 Hi, I encountered the same issue. After updating Tailscale using "sudo apt-get update", the Tailscale connection was lost. It seems that this issue originates from an authorization problem, where the authorization page is blocked by network administration. Here's a potential solution:
> 
> 1. Switch your server's internet connection to another ungoverned network, such as a personal hotspot.
> 2. Start your Tailscale service using this personal connection.
> 3. Then, switch your connection back to the original governed network.

Tried this, my phone's hotspot doesn't work. Even while using root to forward the traffic through a vpn.

**Comment by iskandarluqman** [comment]
> @VenomousSteam81 Hi, I encountered the same issue. After updating Tailscale using "sudo apt-get update", the Tailscale connection was lost. It seems that this issue originates from an authorization problem, where the authorization page is blocked by network administration. Here's a potential solution:
> 
> 1. Switch your server's internet connection to another ungoverned network, such as a personal hotspot.
> 2. Start your Tailscale service using this personal connection.
> 3. Then, switch your connection back to the original governed network.

I will give it a try when I get back tommorow. You are right about using Tailscale on a governed network. This issue started when I was diagnosing DNS on my server. Apparently at the same time, my university network might blocking Tailscale (?) So I went on the wrong rabbit hole blaming my DNS. But since a couple of us also cannot connect to Tailscale, either Tailscale change something on their server side, or our governed network is using the same software for firewall idk.

But your workaround should work, as my Tailscale on Proxmox works as expected. Even when my router auto reboot everyday. As soon I tried to reboot my Proxmox, I lost contact to my server. Which I can conclude, once you are connected to Tailscale, you are fine even with network lost and reconnect, but once you reboot the machine, you need to reconnect Tailscale with another Internet connection.

**Comment by VenomousSteam81** [comment]
Now I'm getting this same issue on Android 13. I used `adb logcat | grep tailscale` and its repeatedly outputting `com.tailscale.ipn: 25.9M/177.4M Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=87": context deadline exceeded`, so definitely a network issue. My school must be blocking this kind of stuff.

**Comment by wcypierre** [comment]
Aside from FW blocking, do you guys have improper ipv6 setup? I had this recently where my ipv6 wasn't setup correctly and once I disabled ipv6 then tailscale started working again on tailscale up

**Comment by kmadaras** [comment]
I generally disable IIPV6 on everything.  It's a pain to manage.  I'm always trying to convince myself otherwise, yet I'm stuck with an IPV4 mindet.

**Comment by PicoPlanetDev** [comment]
I was definitely grasping at straws as well. Assuming you're able to reach that endpoint, which I wasn't able to do, does completely removing Tailscale (not just apt uninstall) make any difference?
How long does it hang? I found after getting the Tailscale domain unblocked, it still took about 10s for `tailscale login` to complete.
Sorry, I'm on my phone right now and can't go back and find my logs.

**Comment by stokkumrmv** [comment]
Quick add: same problems. Interestingly enough, I can reach https://controlplane.tailscale.com/key?v=95 through browser on the same system, so I cannot figure out how the Tailscale domain ended up being blocked when running `sudo tailscale up` command. And moreover how to unblock it. 

I also run pihole, but disabling it did not solve the issue. Any hints how I can pinpointing the issue? I'm not on any managed network, purging Tailscale and reinstall did not solve it.

**Comment by wcypierre** [comment]
> Quick add: same problems. Interestingly enough, I can reach https://controlplane.tailscale.com/key?v=95 through browser on the same system, so I cannot figure out how the Tailscale domain ended up being blocked when running `sudo tailscale up` command. And moreover how to unblock it.
> 
> I also run pihole, but disabling it did not solve the issue. Any hints how I can pinpointing the issue? I'm not on any managed network, purging Tailscale and reinstall did not solve it.

Do you have ipv6 and is your ipv6 working? You can test it through websites like https://ipv6-test.com/

**Comment by stokkumrmv** [comment]
> > Quick add: same problems. Interestingly enough, I can reach https://controlplane.tailscale.com/key?v=95 through browser on the same system, so I cannot figure out how the Tailscale domain ended up being blocked when running `sudo tailscale up` command. And moreover how to unblock it.
> > I also run pihole, but disabling it did not solve the issue. Any hints how I can pinpointing the issue? I'm not on any managed network, purging Tailscale and reinstall did not solve it.
> 
> Do you have ipv6 and is your ipv6 working? You can test it through websites like https://ipv6-test.com/

Thanks for your answer. Here the culprit appears, IPV6 is not working. Since it is also not working for my other systems on my network, I assume my ISP is not offering IPV6 (yet)... 

Is IPv6 a hard requirement for using Tailscale?

**Comment by NeoPlayer13** [comment]
I don't think that's the problem, after all even as today IPv6 adoption globally is estimated around 45% globally and 47% in USA. So requiring IPv6 address for tailscale to work it not a smart move. Specially if it has been working for years just fine using IPv4.

In my case I encountered this problem first a month ago in the managed network in my workplace and in college. But in my home that uses IPv4 behind double NAT and hasn't started the adoption process of IPv6 yet it still working just fine.

**Comment by stokkumrmv** [comment]
> I don't think that's the problem, after all even as today IPv6 adoption globally is estimated around 45% and 47% in USA. So requiring an IPv6 address for tailscale to work it not a smart move. Specially if it has been working for years just fine using IPv4.
> 
> In my case I encountered this problem first a month ago in the managed network in my workplace and in college. But in my home that uses IPv4 behind double NAT because the ISP hasn't started the adoption process of IPv6 yet, it still working just fine.

I agree, there is also no mention of some type of IPv6 exclusivity. 

That leaves the interesting problem of the access denied errors.

`sudo journalctl -u tailscaled.service` give the following:

` [RATELIMIT] format("control: bootstrapDNS(%q, %q) for %q error: %v")
jun 04 15:23:06 ordeus tailscaled[14621]: control: trying bootstrapDNS("derp8c.tailscale.com", "206.189.16.32") for "controlplane.tailscale.com" ...
jun 04 15:23:06 ordeus tailscaled[14621]: [RATELIMIT] format("control: trying bootstrapDNS(%q, %q) for %q ...")
jun 04 15:23:08 ordeus tailscaled[14621]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=95": dial tcp 18.159.140.118:443: connect: connection refused
jun 04 15:23:09 ordeus tailscaled[14621]: control: LoginInteractive -> regen=true
jun 04 15:23:09 ordeus tailscaled[14621]: control: doLogin(regen=true, hasUrl=false)
jun 04 15:23:15 ordeus tailscaled[14621]: [RATELIMIT] format("control: bootstrapDNS(%q, %q) for %q error: %v") (7 dropped)
jun 04 15:23:15 ordeus tailscaled[14621]: control: bootstrapDNS("derp9c.tailscale.com", "2001:19f0:6401:fe7:5400:3ff:fe8d:6d9c") for "controlplane.tailscale.com" error: Get "https://derp9c.tailscale.com/bootstrap-dns?q=controlplane.tailscale.com": dial tcp [2001:19f0:6401:fe7:5400>
jun 04 15:23:15 ordeus tailscaled[14621]: [RATELIMIT] format("control: trying bootstrapDNS(%q, %q) for %q ...") (7 dropped)
jun 04 15:23:15 ordeus tailscaled[14621]: control: trying bootstrapDNS("derp4e.tailscale.com", "134.122.74.153") for "controlplane.tailscale.com" ...
jun 04 15:23:15 ordeus tailscaled[14621]: control: bootstrapDNS("derp4e.tailscale.com", "134.122.74.153") for "controlplane.tailscale.com" error: Get "https://derp4e.tailscale.com/bootstrap-dns?q=controlplane.tailscale.com": dial tcp 134.122.74.153:443: connect: connection refused
jun 04 15:23:15 ordeus tailscaled[14621]: [RATELIMIT] format("control: bootstrapDNS(%q, %q) for %q error: %v")
jun 04 15:23:15 ordeus tailscaled[14621]: control: trying bootstrapDNS("derp9b.tailscale.com", "2001:19f0:6401:eb5:5400:3ff:fe8d:6d9b") for "controlplane.tailscale.com" ...
jun 04 15:23:15 ordeus tailscaled[14621]: [RATELIMIT] format("control: trying bootstrapDNS(%q, %q) for %q ...")
jun 04 15:23:16 ordeus tailscaled[14621]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=95": dial tcp 18.159.140.118:443: connect: connection refused
jun 04 15:23:16 ordeus tailscaled[14621]: control: LoginInteractive -> regen=true
jun 04 15:23:16 ordeus tailscaled[14621]: control: doLogin(regen=true, hasUrl=false)
jun 04 15:23:23 ordeus tailscaled[14621]: Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=95": dial tcp 18.159.140.118:443: connect: connection refused
jun 04 15:23:24 ordeus tailscaled[14621]: control: LoginInteractive -> regen=true
jun 04 15:23:24 ordeus tailscaled[14621]: control: doLogin(regen=true, hasUrl=false)
jun 04 15:23:27 ordeus tailscaled[14621]: logtail: dial "log.tailscale.io:443" failed: dial tcp [2600:1f18:429f:9305:823d:72c0:16da:fb33]:443: connect: connection refused (in 1.019s), trying bootstrap...
jun 04 15:23:28 ordeus tailscaled[14621]: trying bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "log.tailscale.io" ...
jun 04 15:23:28 ordeus tailscaled[14621]: bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "log.tailscale.io" error: Get "https://derp1c.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp 104.248.8.210:443: connect: connection refused
jun 04 15:23:28 ordeus tailscaled[14621]: trying bootstrapDNS("derp1d.tailscale.com", "2604:a880:800:10::7fe:f001") for "log.tailscale.io" ...
jun 04 15:23:29 ordeus tailscaled[14621]: [RATELIMIT] format("control: trying bootstrapDNS(%q, %q) for %q ...") (6 dropped)
jun 04 15:23:29 ordeus tailscaled[14621]: control: trying bootstrapDNS("derp9b.tailscale.com", "144.202.67.195") for "controlplane.tailscale.com" ...
jun 04 15:23:29 ordeus tailscaled[14621]: [RATELIMIT] format("control: bootstrapDNS(%q, %q) for %q error: %v") (7 dropped)
`

**Comment by NeoPlayer13** [comment]
I'm not an expert, but your logs say that the server is continually rejecting the connection to get the key form the controlplane server. 
My theory is that some new changes in some managed networks is interfering with the authentication process of the controlplane. So the only way to troubleshoot it locally is contacting someone with administatrive access to the managed network to follow the authentication process to find where if failing exactly to pinpoint the cause of the problem.
As I'm aware the only one that have solved it by identifiying the exact rule in the managed network that caused the problem is @PicoPlanetDev in #12038

**Comment by stokkumrmv** [comment]
Hmm that's interesting.  Since I'm on my own home network, I have access to everyting up to and including my router. To understand a little better, what could the managed network look like? Do you mean like my ISP cracking down on these "proxy violations"? Or something on my end of the network? 

I did check my router, IPv6 is enabled (even though I'm pretty sure not supported by ISP). 
I've opened port 443 hoping that would solve it based on the logs, but that didn't solve anything (and is also propably on Tailscale's end). 

If try to access the urls in the log, e.g.: `https://controlplane.tailscale.com/key?v=95`, through my browser they work fine. Wouldn't those be blocked as well? 

If you guys need more logs to give some meaningful insight, please let me know what commands to use and I'll happily upload the results. 

Thanks!

**Comment by NeoPlayer13** [comment]
The easiest way to test if the problem is your home network or your ISP, is connecting to another network of that uses the same ISP, for example a neighbor and check if tailscale works. If it works in the other network it means that the problem originated from your home network configuration, if it not, it means that the problem is the ISP.
Another way is to check if you really are in total control of your home network router or if your ISP gave you a limited access, the easiest way is by activating ICMP in your router and check if you can ping the public IP of your router from your cellphone or any other device that's is not in the same subnet as your router. This method don't always works as it depends if the ISP follows the standard of blocking the inbound ICMP traffic by default.

**Comment by stokkumrmv** [comment]
Thanks for the input. ICMP is not an option in my router unfortunately. Also no similar users of my ISP I know of. 
Thanks anyways, I'll start looking into setting up Wireguard without Tailscale. Starts looking like the easier solution :)

**Comment by NeoPlayer13** [comment]
> Thanks for the input. ICMP is not an option in my router unfortunately. Also no similar users of my ISP I know of.

That's weird, it's probably named in another way, you can always google your router band and model to see how to enable ICMP. Also if you can portforward to use wireguard you can always try the selfhosting solution of tailscale [https://github.com/juanfont/headscale](url) or if your setup it's pretty simple you can use a similar option like netbird, zerotier, twingate, etc...

**Comment by esotericman** [comment]
I encountered the same issue on Ubuntu 22.04.4 LTS , then ran
```
sudo service packagekit restart
```
It works now

**Comment by stokkumrmv** [comment]
After a clean reinstall of Ubuntu 22.04.4 LTS, everything started working like it should. Not sure what caused the problem, but it works like a charm now. 

> I encountered the same issue on Ubuntu 22.04.4 LTS, then ran
> 
> ```
> sudo service packagekit restart
> ```
> 
> It works now

**Comment by VenomousSteam81** [comment]
Sometimes my internet likes to screw up and I also get this error. Not using Debian anymore. Using ChromeOS with developer mode enabled and the rootfs made r/w. I have to use the `Linux Other` build but it works great! Going to close this issue.
