### ISSUE TITLE
Backport tailscaled --cleanup to NixOS stable

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1162]
In NixOS 20.09, the tailscaled --cleanup invocations are missing from the systemd unit. That means that if tailscaled crashes while magicdns is on, DNS stays broken on the box until operator intervention.

This is already fixed in nixos-unstable, just need to backport a fix into 20.09 to tide us over until 21.05.

**Comment by DentonGentry** [comment]
NixOS 21.05 became the stable release on June 1, 2021. https://nixos.org/blog/announcements.html

I don't think this issue is necessary any more.
