### ISSUE TITLE
Install script fails on Alpine Linux in containers

### ISSUE THREAD

**Issue by Starttoaster** [tailscale/tailscale#11628]
### What is the issue?

Running the tailscale install script on Alpine Linux began failing. You can see some example output from this CI job I just ran:
![image](https://github.com/tailscale/tailscale/assets/13720491/8d60b37f-7aba-4584-87d4-130780991bac)

I then confirmed this in a basic `alpine:latest` container with a few shell commands.

### Steps to reproduce

1) Run an alpine container locally: `docker run -it --rm alpine:latest sh`

2) In the container's shell, install dependencies of the install script: `apk add curl openrc`

3) Run the install script: `curl -fsSL https://tailscale.com/install.sh | sh`

Get the following logs after tailscale is installed:
```
+ rc-update add tailscale
 * service tailscale added to runlevel sysinit
+ rc-service tailscale start
 * WARNING: tailscale is already starting
```
It says warning but actually exits 1 here.

### Are there any recent changes that introduced the issue?

Looks like this https://github.com/tailscale/tailscale/commit/086ef19439bf7861ab364f9aba1790a89fcd30e2

It seems like I never have this issue because I start tailscaled via the CLI in CI jobs to configure userspace networking in containers. edit: I did some investigation below in this Issue thread but the tl;dr is maybe the Tailscale team could clarify their position on the install script for installing Tailscale in containers, as they tend to not have the same init systems that full OS installations do. If it's supported, maybe installing and starting the service could be opt-out. 

FYI @peterkeen @kelivel

### OS

Linux

### OS version

Alpine 3.19.1

### Tailscale version

1.54.1

**Comment by Starttoaster** [comment]
You can also just replace the install script when reproducing this with the individual commands it runs:
```bash
apk add tailscale
rc-update add tailscale
rc-service tailscale start
```
Where that last command always returns `WARNING: tailscale is already starting` and exits 1.

It's also not clear to me yet if this issue only presents in container environments, because I don't have any Alpine VMs laying around.

**Comment by Starttoaster** [comment]
So I did actually spin up a latest Alpine VM to check out if it's an issue there too, and it appears the install script actually works on Alpine Linux in virtualized/baremetal environments, but seemingly does not work on Alpine Linux in docker containers.

**Comment by Starttoaster** [comment]
Oh interesting, I started augmenting that rc-service start command a little to see if I could get it to work in Alpine in Docker, and this is what i got:

```bash
/ # rc-service -Z tailscale start
 * start: * Caching service dependencies ...
Service `hwdrivers' needs non existent service `dev'
Service `machine-id' needs non existent service `dev'                                                             [ ok ]
 tailscale

/ # rc-service tailscale start
mkdir: can't create directory '/sys/fs/cgroup/openrc.tailscale': Read-only file system
 * You are attempting to run an openrc service on a
 * system which openrc did not boot.
 * You may be inside a chroot or you may have used
 * another initialization system to boot this system.
 * In this situation, you will get unpredictable results!
 * If you really want to do this, issue the following command:
 * touch /run/openrc/softlevel
 * ERROR: tailscale failed to start
```

The `-Z` flag performs a dry-run of the start command. Which returned something that doesn't seem especially useful. But after running it as a dry-run, subsequent requests to `rc-service tailscale start` began showing actual error information. I tried it again a second time actually, to make sure, and the same thing happened: after running it as a dry-run, attempting to start it a second time gave me more information.

So yeah, it's because it's a container. And the command it tells you to run in that error message to override this default error state behavior `touch /run/openrc/softlevel` actually does allow the tailscale service to start.

I don't think I should have to start this service though. At least I'd like the ability to opt out of it, because the error message also makes this sound somewhat hacky/unsupported/unsafe.

**Comment by irbekrm** [comment]
Hi @Starttoaster ,

Is there any reason why you can't use our official Docker image https://tailscale.com/kb/1282/docker?

**Comment by Starttoaster** [comment]
> Hi @Starttoaster ,
> 
> 
> 
> Is there any reason why you can't use our official Docker image https://tailscale.com/kb/1282/docker?
> 
> 
> 
> 

CI jobs usually have many dependencies. Tailscale is just one of them for me. But I have an image that I don't personally maintain that contains most of the tools I need at least for that CI job, besides Tailscale. It was easier to install one tool in the job than several.

**Comment by irbekrm** [comment]
Fair enough 👍🏼 Yes, the install script is not aimed at containers.

I would say the most standard way how to build an image with your own base is to use the same build script as we use to build the official image, but provide your own base, that would basically require you to run [this](https://github.com/tailscale/tailscale/blob/main/Makefile#L87-L93) make target from our repo and pass your own [base](https://github.com/tailscale/tailscale/blob/main/build_docker.sh#L34).
That would then give you an image that will run tailscale on start, you can configure it, including making it run in userspace if you need to with [these env vars](https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go#L14-L67).

I don't know what you want to do with the container, if that doesn't work, then you could take a look at the example here https://tailscale.com/kb/1132/flydotio#step-2-configure-your-dockerfile-to-install-tailscale

**Comment by irbekrm** [comment]
Sounds good, as long as you were actually able to create the image that you needed and it fits your workflow 👍🏼

**Comment by Starttoaster** [comment]
Yeah what you suggested sounds reasonable to me. But I'd honestly prefer not to manage my own CI base images for now, so I just have what is essentially the gitlab equivalent of a "Github Action" for installing tailscale in containers on different OS's and using tailscaled to configure userspace networking. Previously that "Action" called on the public tailscale install script, now it calls on one I made since this one can't be expected to work in containers anymore.

**Comment by dav2000** [comment]
Hello!

I have encountered the same issue. I have solved it by appending "exit 0" to the tailscale install command in my dockerfile, to force the script to return 0 on completion:

RUN curl -fsSL https://tailscale.com/install.sh | sh; exit 0

This is not ideal because if the script fails during build time for whatever reason that is not related to the warning, it might go undetected, but its working as a temporary workaround.

**Comment by Starttoaster** [comment]
Yeah, I think that's kind of the expected behavior unfortunately for the Tailscale install script in container environments. I'd recommend just installing Tailscale without the script, like I ended up doing. Maybe someday Tailscale is interested in adding a flag or control variable that stops the script from trying to do init system-y things. But for now it seemed like there was no appetite at Tailscale for it.

**Comment by crypticviper** [comment]
> Yeah, I think that's kind of the expected behavior unfortunately for the Tailscale install script in container environments. I'd recommend just installing Tailscale without the script, like I ended up doing. Maybe someday Tailscale is interested in adding a flag or control variable that stops the script from trying to do init system-y things. But for now it seemed like there was no appetite at Tailscale for it.

Sorry to dig up this old thread. I have a similar issue while trying to install tailscale on my pi-hole container (which happens to run on alpine linux). I executed the below commands.


    - apk update && apk add openrc tailscale

    - mkdir -p /run/openrc/

    - touch /run/openrc/softlevel

    - rc-service -Z tailscale start

    - rc-service tailscale start

These commands seemingly succeed.

![Image](https://github.com/user-attachments/assets/e309cdd6-66e3-4a4a-8e3d-354b404caf69)

After this, if I issue any tailscale command (even status command), I get below error.

`failed to connect to local tailscaled; it doesn't appear to be running`

Does this have something to do with the read only file system warning or am I missing something obvious?
