### ISSUE TITLE
Tailscale allows unprivileged Linux users to control the network

### ISSUE THREAD

**Issue by tavianator** [tailscale/tailscale#1163]
WIth the default tailscale systemd service, a regular non-root user can do `tailscale down` or `up`.  This seems like something that shouold require administrator privileges, probably by membership in a tailscale group or something.

The rest of the subcommands look fine for unprivileged users.

**Comment by bradfitz** [comment]
This was fixed recently. It'll be in the upcoming release.

**Comment by tavianator** [comment]
Ah okay, thanks!

**Comment by bradfitz** [comment]
@tavianator, the changes, BTW, were d6e9fb1df0fd67d08065c2277e7c4f4a82b7930f and 5611f290eb118eddc256560eaaa69f509347b4de
