### ISSUE TITLE
tailscale still trying to run after uninstalled in ubuntu

### ISSUE THREAD

**Issue by albertxiao** [tailscale/tailscale#11634]
### What is the issue?

i'm uninstalling tailscale in ubuntu by using command

`sudo apt-get remove tailscale
`

but after it's uninstalled it still trying to run or creating new process in background

`root@zippy:~# ps aux | grep tailscale`
`root     1680978  0.0  0.1   7008  2144 pts/0    S+   11:26   0:00 grep --color=auto tailscale`
`root@zippy:~# ps aux | grep tailscale`
`root     1681010  0.0  0.1   7008  2032 pts/0    S+   11:27   0:00 grep --color=auto tailscale`

### Steps to reproduce

1. install using 
`curl -fsSL https://tailscale.com/install.sh | sh`

2. connect to tailscale server
3. uninstall with `sudo apt-get remove tailscale`

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.56.1

**Comment by bradfitz** [comment]
Um, that's your grep process finding itself.

I see no evidence here that Tailscale is still running. Do you have any?

**Comment by albertxiao** [comment]
I see, sorry for the misunderstanding and thank you, i'll close this.
