### ISSUE TITLE
openSUSE signed with unknown key!

### ISSUE THREAD

**Issue by profetik-777** [tailscale/tailscale#11635]
### What is the issue?

repo is not signed issuing warning. 

https://paste.opensuse.org/pastes/8eb051d69e43

### Steps to reproduce

zypper ref command after adding repo from instructions found here: 

https://tailscale.com/download/linux/opensuse-tumbleweed 

### Are there any recent changes that introduced the issue?

no

### OS

Linux

### OS version

tumbleweed - opensuse

**Comment by patrickod** [comment]
Thank you for the report! We recently toggled signature checks for our repository but forgot to update the install instructions to include the additional `rpm --import $KEY` step. This is now reflected in our documentation.

**Comment by patrickod** [comment]
Upon reflection the installer script also needs to be updated to include this step.

**Comment by profetik-777** [comment]
Thanks for the quick fix / turnaround those who were able to jump on this! :D
