### ISSUE TITLE
FR: Kubernetes sessions recording

### ISSUE THREAD

**Issue by rguliyev** [tailscale/tailscale#11637]
### What are you trying to do?

It'd be extremely valuable to have Kubernetes sessions recording / capturing the entire PTY output for `kubectl exec` invocations for audit / forensic purposes.

### How should we solve this?

I assume capture the entire PTY output for `kubectl exec` invocations similarly to how you do SSH session recordings.

### What is the impact of not solving this?

The easiest solution would be to use a different vendor which provides Kubernetes sessions recording capability, for example [Teleport](https://goteleport.com/docs/architecture/session-recording/#kubernetes-sessions)

### Anything else?

Looking forward to testing Kubernetes sessions recording capability

**Comment by irbekrm** [comment]
This feature is now available in private alpha. Please reach out to our sales or support folks to try it out 
https://tailscale.com/contact/sales
https://tailscale.com/contact/support
