### ISSUE TITLE
FR: use exit node only for ipv4

### ISSUE THREAD

**Issue by madisp** [tailscale/tailscale#11646]
### What are you trying to do?

I'm operating a few ipv6-only machines at home and would like to give them ipv4 connectivity with tailscale. I can use exit nodes for this, but it'll also start using the exit node for ipv6 traffic.

### How should we solve this?

Ideally maybe a few options to control whether exit node is used for ipv4, ipv6 or both? I can also see value in vice versa - giving ipv4-only machines ipv6 connectivity by using an exit node only for ipv6 traffic.

### What is the impact of not solving this?

I haven't tried yet, but I'm pretty sure I could do a workaround by adding client machine routes manually?

**Comment by bradfitz** [comment]
Dup of #11316 basically. See discussion there.
