### ISSUE TITLE
--accept-routes disables local eth0

### ISSUE THREAD

**Issue by SiM22** [tailscale/tailscale#1164]
**Describe the bug**
On Ubuntu 20.04, when starting tailscale with `sudo tailscale up --accept-routes`, there is a change in iptables which seems to block/drop packets trying to enter via `eth0`, if i run `sudo tailscale up` all packets will hit eth0 and work as expected.
I had this issue before which I reported but never opened an issue and forgot about it.

**To Reproduce**
1. run `sudo tailscale up --accept-routes`
2. ping/ssh/nmap the local ip (eth0 interface), nothing gets through
3. run `sudo tailscale up`
4. Everything works as expected but no routes added

**Expected behavior**
I expect `--accept-routes` to add routes and also should still be able to hit the local IP

**Version information:**
 - Device: Server
 - OS: Ubuntu 20.04
 - OS version: 20.04
 - Tailscale version: 1.2.10

**Additional context**

iptable logs

```
Jan 19 14:43:39 bob kernel: [ 2198.089460] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=35005 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=73
Jan 19 14:43:40 bob kernel: [ 2199.112790] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=35041 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=74
Jan 19 14:43:41 bob kernel: [ 2200.137817] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=35158 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=75
Jan 19 14:43:42 bob kernel: [ 2201.161226] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=35374 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=76
Jan 19 14:43:43 bob kernel: [ 2202.185514] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=35596 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=77
Jan 19 14:43:44 bob kernel: [ 2203.209251] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=35825 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=78
Jan 19 14:43:45 bob kernel: [ 2204.233297] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36003 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=79
Jan 19 14:43:46 bob kernel: [ 2205.257479] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36033 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=80
Jan 19 14:43:47 bob kernel: [ 2206.281155] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36218 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=81
Jan 19 14:43:48 bob kernel: [ 2207.305503] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36256 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=82
Jan 19 14:43:49 bob kernel: [ 2208.329555] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36440 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=83
Jan 19 14:43:50 bob kernel: [ 2209.353560] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36654 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=84
Jan 19 14:43:51 bob kernel: [ 2210.376856] IN=eth0 OUT= MAC=02:b7:b4:13:63:a0:0e:c5:6e:9c:5b:35:08:00 SRC=192.168.1.203 DST=192.168.1.103 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=36814 DF PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=85
```

**Comment by TimDowker** [comment]
Can confirm this is also an issue with OpenWRT.  I know it's not officially supported but I have it working but whenever I try to add the --accept-routes option, all internet access is cut off.

Sorry I can't supply more details.

**Comment by DentonGentry** [comment]
Most commonly when --accept-routes breaks LAN connectivity it is because of overlap, that (for example) the LAN uses 10.1.1.0/24 and one of the subnet routes is also 10.1.1.0/24.

**Comment by 24788329** [comment]
I'm experiencing the same issue with v1.12.1 despite everything working fine prior to v1.10.0 with the same network setup. Did Tailscale change how this feature works?

**Use case:** access LAN devices via the same LAN IPs (192.168.1.x) whether I am at home or on another network. 

With `tailscale up` on its own, I can access devices via both LAN and Tailscale IPs. Once `--accept-routes` is added, I can no longer connect via LAN and must use Tailscale IPs.

When setting up Tailscale, my LAN and `--advertise-routes` use the same 192.168.1.0/24 subnet, but isn't this what I need for this use case? If I change `--advertise-routes` to be different from my LAN subnet, how can I still reach LAN devices via 192.168.1.x from outside my LAN?

**Comment by DentonGentry** [comment]
I think the issue reported is essentially the feature request in https://github.com/tailscale/tailscale/issues/1227, to rationalize what happens when a subnet route overlaps with the local LAN.

Dup of https://github.com/tailscale/tailscale/issues/1227

**Comment by mkono87** [comment]
> I think the issue reported is essentially the feature request in https://github.com/tailscale/tailscale/issues/1227, to rationalize what happens when a subnet route overlaps with the local LAN.
> 
> Dup of https://github.com/tailscale/tailscale/issues/1227

Yet no reply in that request
