### ISSUE TITLE
HOW to pass correct argument in docker

### ISSUE THREAD

**Issue by joebnb** [tailscale/tailscale#11657]
### What is the issue?

how to pass mutiple argument in docker?
im tring pass mutiple TS_EXTRA_ARGS but there no any multiple example and i got error

this is docker command:
```
docker run -d --name=tailscale -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --restart=unless-stopped --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW -e TS_EXTRA_ARGS="--accept-routes true --netfilter-mod off" -e TS_AUTHKEY=tskey-auth--authkey1234567 tailscale/tailscale
```

and i'm trying:

-e TS_EXTRA_ARGS="--accept-routes true --netfilter-mod off"
-e TS_EXTRA_ARGS="--accept-routes=true --netfilter-mod=off"
-e TS_EXTRA_ARGS="accept-routes true netfilter-mod off"
-e TS_EXTRA_ARGS="accept-routes=true netfilter-mod=off"

no one works

<img width="854" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/07fadaa4-c6f0-4cc4-888f-a30e71fcbf70">

<img width="1097" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/548f6c3d-8c05-4dc5-8769-ccff7fdfd485">

**Comment by bradfitz** [comment]
You forgot the `e` in `mode`.

`-e TS_EXTRA_ARGS="--accept-routes --netfilter-mode=off"`

(For boolean parameter you can say either `--foo=true` or `--foo` but not `--foo true`)

**Comment by joebnb** [comment]
> You forgot the `e` in `mode`.
> 
> `-e TS_EXTRA_ARGS="--accept-routes --netfilter-mode=off"`
> 
> (For boolean parameter you can say either `--foo=true` or `--foo` but not `--foo true`)

docker run -d --name=tailscale -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --restart=unless-stopped --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW -e TS_EXTRA_ARGS="--accept-routes true --netfilter-mod off" -e TS_AUTHKEY=tskey-auth--authkey1234567 tailscale/tailscale

-e is incuded

**Comment by bradfitz** [comment]
You wrote "mod" instead of "mode". That's the e I'm talking about.

**Comment by joebnb** [comment]
sorry for this mistake
