### ISSUE TITLE
Renaming the machine name gets applied only partially

### ISSUE THREAD

**Issue by mbertschler** [tailscale/tailscale#11651]
### What is the issue?

Editing the machine name in the admin console with **Machine Settings > Edit machine name...** doesn't lead to the expected results. At first there is some kind of optimistic UI update happening where the new name is reflected, but a bit later and after a page refresh, the old name is still shown.

In my case I tried to rename a machine that was called `web-server-2` (its hostname) to `web2` for simplicity.

### Inconsistent Results
- The **Machine name** **Short domain** and **Full domain** fields still contain `web-server-2` string
- Changing the name to `web2` again isn't allowed and fails with `Name "web2" is already taken`
- `tailscale status` shows the machine as `web2`
- `tailscale status --json | grep DNSName` shows `web2.xxx-xxx.ts.net` (while the Admin UI still shows `web-server-2.xxx-xxx.ts.net`
    - the DNS name that `tailscale status` reports is the one actually working, the UI one doesn't resolve

### Steps to reproduce

- Change the name of a machine from the default host name to a custom one with this dropdown:
    - **Machine Settings > Edit machine name...**
- Check the machine list to see if the new name is reflected everywhere
- Check machine details fields
    - Machine name
    - OS Hostname
    - Short domain
    - Full domain 
- Check the output of `tailscale status` and `tailscale status --json` 

### OS

Linux, macOS

### OS version

macOS 14.4.1, Debian 12, Ubuntu 18.04

### Tailscale version

1.62.0

### Other software

-

### Bug report

BUG-92eeb7e731c955008f3b47d3473ace94fef26e2edda23fa0f2c24d67c9f2d65c-20240406213802Z-84e4d787c9116e7d

**Comment by mbertschler** [comment]
I just checked the UI again, the machine name + DNS names were now correct.

But changing it to another name now again still results in the same issue. After modifying the name it shows the newly chosen name in the list, but after reloading the page it still is the old one.

**Comment by bradfitz** [comment]
@mbertschler, we were unable to reproduce this.

What browser was this on?

And ever after a reload in the browser, it's still stuck wrong?

Do you have any proxies (notably caching proxies) in your network?

**Comment by bradfitz** [comment]
That helps a lot, thanks.

Smells like a caching problem within our backend.

cc @maisem

**Comment by bradfitz** [comment]
@mbertschler, thanks again. With these details we were able to find the bug. It's not deployed yet, but should be soon.
