### ISSUE TITLE
Account login name change detected

### ISSUE THREAD

**Issue by flyweb291** [tailscale/tailscale#11654]
### What is the issue?

Because the user name of my github account has been changed, when I used the github associated account to log in to tailscale, the user name was inconsistent, and I could not log in to the account.

REQ-1a17266eb-e08a-4c90-bdf2-bb1286f25d80

### OS

macOS

### OS version

14.4.1 (23E224)

### Tailscale version

1.62.1

### Bug report

REQ-1a17266eb-e08a-4c90-bdf2-bb1286f25d80

**Comment by bradfitz** [comment]
This is probably best handled by emailing support@ where you can share personal information, unlike this public issue tracker.

**Comment by kelivel** [comment]
Solved with go/hs/36033

**Comment by TrueBankai416** [comment]
> Solved with go/hs/36033

how did you solve this?

**Comment by kelivel** [comment]
@TrueBankai416 Our Support team migrated the tailnet to use the new GitHub username. If you also need a hand with this, drop a line at https://tailscale.com/contact/support and share the old and new usernames, and we can help.
