### ISSUE TITLE
Unable to Log In/Add Account on MacOS (AppStore) 1.62.0 client

### ISSUE THREAD

**Issue by estilles** [tailscale/tailscale#11652]
### What is the issue?

Unable to Log In/Add Account
I see the following errors:
```
control: bootstrapDNS("derp3.tailscale.com", "68.183.179.66") for "controlplane.tailscale.com" error: Get "https://derp3.tailscale.com/bootstrap-dns?q=controlplane.tailscale.com": dial tcp 68.183.179.66:443: connect: network is unreachable
control: bootstrapDNS("derp12.tailscale.com", "2001:19f0:5c01:289:5400:3ff:fe8d:cb5e") for "controlplane.tailscale.com" error: Get "https://derp12.tailscale.com/bootstrap-dns?q=controlplane.tailscale.com": dial tcp [2001:19f0:5c01:289:5400:3ff:fe8d:cb5e]:443: connect: no route to host
```

I am able to login from IOS (iPhone and iPad) and Ubuntu on the same network.

### Steps to reproduce

- Installed 1.62.0
- Restarted MacBook
- Opened Tailscale client
- Allowed client to add VPN
- Attempted to click "Add Account" (now Tailscale icon slows small triangle warning image)

### Are there any recent changes that introduced the issue?

Upgraded MacOS client to 1.62.0

### OS

macOS

### OS version

Sonoma 14.4.1

### Tailscale version

1.62.0 (from App Store)

### Bug report

BUG-c64f511071c1f39db95e635801967eb5f9931c8258fcfca17c3aafd8ba1942fb-20240406234636Z-93c589f423fdf440

**Comment by bradfitz** [comment]
Any reason to believe the network is blocking Tailscale or have some security/restrictions on it?

**Comment by estilles** [comment]
No network issues that I'm aware of. I have other devices on the network (an iPhone, an iPad, several Ubuntu servers, and a Windows laptop on the same network.

No security/restrictions I'm aware of. I checked every security setting I could find on Sonoma. 

I forgot to mention above I also recently upgraded Sonoma to 14.4.1 (from 14.3)

**Comment by estilles** [comment]
FYI ... this is what I see on my end. Clicking on either the `Add Account...` or the `Sign in to your network` buttons does nothing.

![image](https://github.com/tailscale/tailscale/assets/5514878/5e257511-498e-4a16-a9e3-f9583ccd9ad9)

![image](https://github.com/tailscale/tailscale/assets/5514878/cecf3f10-f17d-42db-9ee8-106c53e65653)

**Comment by estilles** [comment]
Seems like something similar has already been reported. #11433

**Comment by lgzcoollg** [comment]
I get the same issue at 1.66.4

**Comment by agottardo** [comment]
This is most likely caused by third-party software interfering with Tailscale. 

Please contact `support@tailscale.com` and attach a bug report identifier and a macOS Configuration Report (Settings > About Tailscale > Report an Issue > Export Configuration Report).

**Comment by jackordman** [comment]
Also having this issue, reached out to support with requested info.

**Comment by kelivel** [comment]
@jackordman We've got your report, thanks for sending that over.

```
2024-06-12 17:52:33 | control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
2024-06-12 17:52:33 | control: sendStatus: authRoutine-report: state:authenticating
2024-06-12 17:52:33 | control: authRoutine: backoff: 3046 msec
2024-06-12 17:52:33 | Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
```
cc @agottardo diagnostic report at http://go/tss/40479

**Comment by leftmove** [comment]
For me, this was an issue with the App Store version of Tailscale.

By reinstalling with the DMG given on the [website](https://tailscale.com/download), login, while it was unusually slow, did work.

**Comment by james-auror** [comment]
I reinstalled Tailscale and still had the same issue. I just had to reboot to fix it.

**Comment by doomspork** [comment]
@kelivel I saw this was closed but wanted to share that I'm getting this issue on 1.82.5 which I downloaded from the Tailscale site. Were there steps to unblock this?

**Comment by mnofrizal** [comment]
i have this issue to from app store, the issue in my case becasue i use cloudfalre vpn, when i disable cloudflare it work now

**Comment by aisleuhery1976** [comment]
Same issue here. I removed a working account from tailscale, and after that, wasn't able to add a new one.

**Comment by DrewWalkup** [comment]
Crazy how this has been a problem for folks since March 2024 and there is zero public workaround. And it's STILL an issue.

Here's the solve:

- On the Tailscale website dash, go to `Settings` > `Personal Settings: Keys`
- Generate an Auth Key, copy it

- Install the MacOS Tailscale client
- Open the Tailscale client settings
- At the bottom, click "Show me how" next to "CLI Integration" (optional for shortcut)
- Install the Path shortcut (optional for shortcut)
- Open terminal
- Type `tailscale status` (optional, make sure its working)
- Type `tailscale up --auth-key <paste your key here>`

Done.
