### ISSUE TITLE
Tailscale iOS interrupting certain iCloud/Photos features

### ISSUE THREAD

**Issue by timkelty** [tailscale/tailscale#11653]
### What is the issue?

Weird one:

So, I recently enabled "iCloud Photos" in the Apple Photos to start storing photos in iCloud (previously was using Google Photos).

I also tried to enable a "Photo Shuffle" wallpaper, but every time I tried, it said "Photo Shuffle is Processing":
![IMG_0414](https://github.com/tailscale/tailscale/assets/18329/073d26d1-8ab5-437e-aa98-ca3bfb4bc368)

Internet searches pointed to the usual setting resets, etc, but nothing worked. With photos, alot of this processing happens on your device when its locked/charging and on wifi, so I gave it some time.

2 weeks later, I break down and hop on Apple chat support.

The first thing they ask me "have you tried it on a different network"…which I had. But then it dawns on me: Tailscale is running.

I turn Tailscale off, and almost immediately the feature begins working.

So, it would seem that Tailscale was interfering somehow. How, now idea.

Possibly related: https://github.com/tailscale/tailscale/issues/6099

### OS

iOS

### OS version

17.3.1

### Tailscale version

1.62.0

### Bug report

BUG-5ce5cebccd0bb65a7abbbee84c7f0ef29d729813a26c4b1651251f1b13fefe25-20240407004159Z-d54e119e923bb898

**Comment by kelivel** [comment]
We've tried this in the latest version and we can't reproduce. If you're still experiencing this behavior, feel free to open a new issue and include a link to a sysdiagnose.
