### ISSUE TITLE
Which app should we publish on F-Droid?

### ISSUE THREAD

**Issue by linsui** [tailscale/tailscale#11662]
### What is the issue?

Now there is a new android app and a legacy android app. Which one should we publish on F-Droid?

### OS

Android

**Comment by bradfitz** [comment]
See https://goomics.net/50/

**Comment by linsui** [comment]
Do ping me when the new app is ready. :) Thanks!

**Comment by licaon-kter** [comment]
FYI not all androidx libs are FOSS, eg [`androidx.navigation:navigation-dynamic-features`](https://github.com/tailscale/tailscale-android/blob/a9ff722b024870c4a0e82d8260de539e0d8067c8/android/build.gradle#L102) depends on proprietary Google libs https://mvnrepository.com/artifact/com.google.android.play/feature-delivery/2.0.1
