### ISSUE TITLE
cmd/tailscale: confusing "subcommand required" error message

### ISSUE THREAD

**Issue by mvdan** [tailscale/tailscale#11672]
### What is the issue?

```
$ tailscale --version
1.62.1
  tailscale commit: 8ee5801a3d6b669620e38ee4fbe8b93d3b73af96-dirty
  go version: go1.22.1
$ tailscale exit-node
exit-node subcommand required; run 'tailscale exit-node -h' for details
$ tailscale exit-node ls
exit-node subcommand required; run 'tailscale exit-node -h' for details
$ tailscale exit-node -h
USAGE
  exit-node [flags]

Show machines on your tailnet configured as exit nodes

SUBCOMMANDS
  list  Show exit nodes
$ tailscale exit-node list

 IP                HOSTNAME                   COUNTRY     CITY      STATUS     
[results]

# To use an exit node, use `tailscale set --exit-node=` followed by the hostname or IP
```

Note how in `tailscale exit-node ls` I misremembered the name of the subcommand. The error should be along the lines of "unknown subcommand", not "subcommand required".

### Steps to reproduce

See above.

### Are there any recent changes that introduced the issue?

Not sure.

### OS

Linux

### Tailscale version

1.62.1

### Bug report

BUG-819bb4055bd569aa8efa72d1b77e98ebba7caf6fb891c8f7ac97803abde84513-20240409065253Z-047f29104245bcc7

**Comment by icio** [comment]
Thanks for reporting this @mvdan! I've just merged a change that should clarify what's gone wrong:

```
$ tailscale exit-node ls
tailscale exit-node: unknown subcommand: ls

$ tailscale exit-node
tailscale exit-node: missing subcommand: list, suggest
```

and tidied this up for other similar commands.

(While I'm at it - thanks for your other great libraries and contributions to the Go community over the years ☺️)

**Comment by mvdan** [comment]
Thanks for the quick fix :)
