### ISSUE TITLE
Tailscale on Linux (Fedora) continually tries to configure IPv6 on a non-IPv6 host

### ISSUE THREAD

**Issue by tsmoneta** [tailscale/tailscale#11676]
### What is the issue?

Apr 09 13:33:01 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683981.8818] platform-linux: do-add-ip6-address[2: fe80::ed78:b87f:3fb:1159]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:01 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683981.8820] l3cfg[418156aee4f37add,ifindex=2]: unable to configure IPv6 route: type unicast fe80::/64 dev 2 metric 1024 mss 0 rt-src ipv6ll
Apr 09 13:33:03 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683983.8831] platform-linux: do-add-ip6-address[2: fe80::dea8:dc1e:779:268c]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:05 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683985.8844] platform-linux: do-add-ip6-address[2: fe80::5fca:ef0d:b5a0:b853]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:07 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683987.8859] platform-linux: do-add-ip6-address[2: fe80::c20e:e2d8:78ac:1b69]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:09 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683989.8864] platform-linux: do-add-ip6-address[2: fe80::56cd:9376:b24c:ea41]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:11 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683991.8868] platform-linux: do-add-ip6-address[2: fe80::3d12:9109:5832:b9f7]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:13 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712683993.8871] ipv6ll[0f3b1bcb02dff35e,ifindex=2]: changed: no IPv6 link local address to retry after Duplicate Address Detection failures (back off)
Apr 09 13:33:23 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684003.8885] platform-linux: do-add-ip6-address[2: fe80::ed78:b87f:3fb:1159]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:23 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684003.8887] l3cfg[418156aee4f37add,ifindex=2]: unable to configure IPv6 route: type unicast fe80::/64 dev 2 metric 1024 mss 0 rt-src ipv6ll
Apr 09 13:33:25 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684005.8895] platform-linux: do-add-ip6-address[2: fe80::dea8:dc1e:779:268c]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:27 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684007.8902] platform-linux: do-add-ip6-address[2: fe80::5fca:ef0d:b5a0:b853]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:29 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684009.8912] platform-linux: do-add-ip6-address[2: fe80::c20e:e2d8:78ac:1b69]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:31 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684011.8925] platform-linux: do-add-ip6-address[2: fe80::56cd:9376:b24c:ea41]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:33 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684013.8930] platform-linux: do-add-ip6-address[2: fe80::3d12:9109:5832:b9f7]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Apr 09 13:33:35 rocket.moneta.optonline.net NetworkManager[789]: <warn>  [1712684015.8931] ipv6ll[0f3b1bcb02dff35e,ifindex=2]: changed: no IPv6 link local address to retry after Duplicate Addr
.
.
.
Forever

### Steps to reproduce

Bring up Tailscale on the host. Check the journalctl log

### Are there any recent changes that introduced the issue?

Unknown

### OS version

Fedora 39, current as of April 9th 2024, Kernel 6.8.4

### Tailscale version

1.62.1   tailscale commit: 8ee5801a3d6b669620e38ee4fbe8b93d3b73af96   other commit: 76428ac0be84b1f0e26cc21f9db2b048dabe2059   go version: go1.22.1

### Bug report

BUG-c2f071e7028f1660b6c0c8c2a7760ed39fe50e729a5729c4938fa2e7fd59b42f-20240409173842Z-b8e8a62f8c020314

**Comment by tsmoneta** [comment]
While IPv6 was disabled on the host (/proc/sys/net/ipv6/conf/all/disable_ipv6 is 1), it was not disabled in NetworkManager. Disabling IPv6 in NetworkManager and rebooting stopped the continuous configuration requests.

**Comment by tsmoneta** [comment]
Configuration issue.

**Comment by kelivel** [comment]
Hi @tsmoneta, were you able to get this one resolved based on your last update?

**Comment by tsmoneta** [comment]
> Hi @tsmoneta, were you able to get this one resolved based on your last update?

Yes. It looks like NetworkManager not having IPv6 disabled caused the problem. If anything Network Manager should not have had it enabled, if the kernel had it didsabled. I think Tailscale was just an innocent bystander in this case.

**Comment by kelivel** [comment]
Great, glad to hear it's sorted now!
