### ISSUE TITLE
Under certain conditions, group information for an active directory user (linux/sssd) is not complete

### ISSUE THREAD

**Issue by snemir2** [tailscale/tailscale#11682]
### What is the issue?

When sshing to linux host via tailscale ssh from warp or vscode remote terminal, only primary gid is associated with the user (and other group membership is lost)

The correct group membership is 
```
uid=870201159(sergey) gid=870201162(datascience) groups=870201162(datascience),870201629(datascience_systems_admins)
```

However, when vscode/warp etc are used as terminal, only primary gid is returned
```
id
uid=870201159(sergey) gid=870201162(datascience) groups=870201162(datascience)
```

Strong indication that the issue is within tailscaled and overriding getent https://github.com/tailscale/tailscale/blob/main/util/osuser/user.go#L32

Clearly, when not a complete group infor is return it breaks our "sudo" and file access 

### Steps to reproduce

1. Setup systems with ldap/sssd
2. configure tailscale/ssh
3. Use vscode over ssh or warp to connect to host via ssh

### OS

Linux

### OS version

ubuntu-22.04

### Tailscale version

latest

**Comment by jimmybrancaccio** [comment]
Related support ticket - 35925.
