### ISSUE TITLE
pkgs: link to release notes, changelogs for downloads

### ISSUE THREAD

**Issue by HaxNobody** [tailscale/tailscale#1169]
The downloads & pkgs pages for Tailscale do not appear to have any way to discover the changes between versions. As an example, I currently have 1.2.10 installed, and the About dialog says it is up to date, but there is a newer release with unknown changes currently available for download (1.3.147).

**Comment by bradfitz** [comment]
1.3.147 is an unusual pre-release for the upcoming 1.4.0. Normally only even middle numbers are stable releases (1.0.x, 1.2.x., 1.4.x) and we document+blog the stable releases.

I'll keep this bug open about linking to the release notes + changelog from the download site, though.

**Comment by danderson** [comment]
Depending on our mood and release decisions, pkgs can be serving a variety of different versions at any one time. Rather than try to track those in detail, I'm going to link to our fancy new changelog, which lists both client and SaaS changes in a nice format.

**Comment by danderson** [comment]
https://pkgs.tailscale.com/stable/ now links to the changelog.
