### ISSUE TITLE
Android client on ChromeOS displaying "Loading..." and never getting any further.

### ISSUE THREAD

**Issue by noseshimself** [tailscale/tailscale#11696]
### What is the issue?

The Android client is not starting on ChromeOS without any indication of anything being wrong anymore.

The only thing that is looking strange hitting the logs is

```
04-12 12:47:43.998  3337  3337 W Thread-7: type=1400 audit(0.0:246): avc: denied { read } for name="route" dev="proc" ino=4026532049 scontext=u:r:untrusted_app:s0:c183,c256,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.tailscale.ipn
04-12 12:47:44.041   378  7774 E keystore2: keystore2::error: In generate_key.
04-12 12:47:44.041   378  7774 E keystore2: 
04-12 12:47:44.041   378  7774 E keystore2: Caused by:
04-12 12:47:44.041   378  7774 E keystore2:     0: While generating Key without explicit attestation key.
04-12 12:47:44.041   378  7774 E keystore2:     1: Binder exception code ILLEGAL_STATE, 0
04-12 12:47:44.056   378  7774 E keystore2: keystore2::error: In generate_key.
04-12 12:47:44.056   378  7774 E keystore2: 
04-12 12:47:44.056   378  7774 E keystore2: Caused by:
04-12 12:47:44.056   378  7774 E keystore2:     0: While generating Key without explicit attestation key.
04-12 12:47:44.056   378  7774 E keystore2:     1: Binder exception code ILLEGAL_STATE, 0
04-12 12:47:44.058  3337  3368 I com.tailscale.ipn: fatal error: runBackend: NewLocalBackend: calling ReadState on state store: java.security.GeneralSecurityException: Keystore key generation failed
```

### Steps to reproduce

1. Install Tailscale client.
2. Launch it.
3. Confirm initial message.
4. There is no 4.

### OS

Other

### OS version

ChromeOS m123 with Android SDK 33 (ARC version 11661914)

### Tailscale version

1.60.1

### Bug report

BUG--20240412104240Z-b6195d9ff2017c0c

**Comment by gmcz** [comment]
I believe I'm getting a crash before the loading screen when installing from f-droid. I do see this loading screen when installing via Obtanium on two different GrapheneOS devices. If I can provide any useful logs or test anything I'm happy to.

**Comment by noseshimself** [comment]
> Hi @noseshimself, can you paste the full contents of the bugreport without redaction? It's a marker to help us locate your logs in our records.

That will take considerable time as I don't have the slightest idea which other subsystems are involved in this (besides entries tagged as "com.tailscale.ipn"). The ChromeBook in question is not set to developer mode either so a lot might be missing here, too. This is the reason why I added the feature request to display relevant output in the clients main window (obviously in some field that can be scrolled and copied from). The entire log is not really intended for public consumption either... I'd say a *log* of developers should exercise a bit more restraint seeing what is ending in that log.

Is there anything special I should be looking for?

**Comment by kelivel** [comment]
@noseshimself I'm sorry, I definitely should have phrased my ask better! I'll need the full BUG- report _string_, your original submission string is redacted:

> Bug report
BUG--20240412104240Z-b6195d9ff2017c0c

The redacted portion of your string is the unique machine ID that helps us locate your device in our logs. With your current redaction the report only gives us the time period, but no machine to check.

**Comment by noseshimself** [comment]
> @noseshimself I'm sorry, I definitely should have phrased my ask better! I'll need the full BUG- report _string_, your original submission string is redacted:
> 
> > Bug report
> > BUG--20240412104240Z-b6195d9ff2017c0c
> 
> The redacted portion of your string is the unique machine ID that helps us locate your device in our logs. With your current redaction the report only gives us the time period, but no machine to check.



> @noseshimself I'm sorry, I definitely should have phrased my ask better! I'll need the full BUG- report _string_, your original submission string is redacted:
> 
> > Bug report
> > BUG--20240412104240Z-b6195d9ff2017c0c
> 
> The redacted portion of your string is the unique machine ID that helps us locate your device in our logs. With your current redaction the report only gives us the time period, but no machine to check.

Sorry; I can't even run the Tailscale app anymore; now it's opening a window and immediately closing it again.

**Comment by noseshimself** [comment]
Working again at version 1.67.105-t916c...

**Comment by kari-ts** [comment]
Please re-open if you see this issue again
