### ISSUE TITLE
MDM Managed client UX

### ISSUE THREAD

**Issue by nuna-alan** [tailscale/tailscale#11697]
### What is the issue?

We have pushed out a macOS MDM profile to configure several settings within the client, but the GUI still appears to allow modifying those settings.

### Steps to reproduce

Here are the MDM profile settings:
```
<dict>
	<key>AllowIncomingConnections</key>
	<string>never</string>
	<key>KeyExpirationNotice</key>
	<string>1h</string>
	<key>PayloadDisplayName</key>
	<string>Tailscale</string>
	<key>PayloadIdentifier</key>
	<string>io.tailscale.ipn.macos.85C0EDC0-7DE7-4505-B590-66E55B61FC51</string>
	<key>PayloadType</key>
	<string>io.tailscale.ipn.macos</string>
	<key>PayloadUUID</key>
	<string>85C0EDC0-7DE7-4505-B590-66E55B61FC51</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
	<key>PostureChecking</key>
	<string>always</string>
	<key>SUAutomaticallyUpdate</key>
	<true/>
	<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>TailscaleStartOnLogin</key>
	<true/>
	<key>UseTailscaleDNSSettings</key>
	<string>always</string>
	<key>UseTailscaleSubnets</key>
	<string>always</string>
</dict>
```

and yet the GUI doesn't lock these settings/gray them out?
![Screenshot 2024-04-12 at 10 56 35 AM](https://github.com/tailscale/tailscale/assets/11576538/9fb64106-09a9-4072-8fc8-81660ca647f7)

### OS

macOS

### OS version

14.4.1

### Tailscale version

1.64.0

### Other software

Network related: Crowdstrike Falcon, LuLu (firewall), Cisco AnyConnect.

MDM provided by Kandji.

### Bug report

BUG-87f3bb26581b4387b70616b95a4fdc0007fb1590a6d192edbea9d70381bf5219-20240412161552Z-1ce4c22387b0c001

**Comment by nuna-alan** [comment]
I should add, I am able to toggle all of those checkboxes... despite the image above matching what is in the profile.

e.g. 
![Screenshot 2024-04-12 at 11 20 34 AM](https://github.com/tailscale/tailscale/assets/11576538/a6c7f5b2-e7a5-4eab-98da-80abe8c8c28e)

**Comment by icio** [comment]
Hi @nuna-alan, the clients currently only read MDM settings when they start up. If you restart the MacOS client in question, do the MDM settings you pushed take effect?

**Comment by nuna-alan** [comment]
They do not. I turned off all those settings, quit the app, started it back up, and they were still turned off.

**Comment by icio** [comment]
Ah, well spotted 👍
