### ISSUE TITLE
Tailscale local web interface login doesn’t work

### ISSUE THREAD

**Issue by purple-emily** [tailscale/tailscale#11707]
### What is the issue?

Updated to latest Tailscale which now enables `tailscale web` by default on 100.100.100.100. 

The page loads and recognises me as the user I am. I can’t change any changes to the settings. I press the login button and nothing happens. In the console I get this error:

```
tailscale web failed request: failed to create web client session
```

with a ID code which I’m guessing is a session id. 

It works correctly if I access the web interface of my Linux homelab from my phone 

### Steps to reproduce

Navigate to 100.100.100.100

Press login

???

No profit ☹️

### Are there any recent changes that introduced the issue?

No this has been an issue for a while for me. 

### OS

Windows

### OS version

11

### Tailscale version

1.64.0

**Comment by Khalilsqu** [comment]
could someone please fix the login button, it does nothing, no error is shown, 

In Windows, I cannot log in, I have been clicking the login button but nothing is shown.

**Comment by kelivel** [comment]
Hi folks, I'm currently investigating this. I've tested this on my end on the latest 1.64.2 client in Windows 11, navigating to http://100.100.100.100 in my browser and choosing the "Sign in to confirm identity" button. My login prompt opens successfully each time. 

@Khalilsqu Can you open your browser's dev tools Console tab, reproduce the login prompt failure behavior, then send back what errors the console reported? Here are the steps to opening the [Developer Tools menu in Chrome](https://developer.chrome.com/docs/devtools/open#last), other browsers should be similar.

**Comment by Khalilsqu** [comment]
Thanks, indeed it is working on my end, I believe the issue was due to some bad configuration from my end.

Appreciate your efforts
