### ISSUE TITLE
Android: contradictory notification regarding key expiry

### ISSUE THREAD

**Issue by insert-usernamehere** [tailscale/tailscale#11701]
### What is the issue?

Android version of #10095
There is a notification about key expiry despite it being disabled 

### Steps to reproduce

Disable key expiry for an android node
Look in the app and observe a notification about key expiry

### Are there any recent changes that introduced the issue?

The app redesign 

### OS

Android

### OS version

Android 14

### Tailscale version

1.65.0-t220764331

### Other software

![Screenshot_20240412-154044](https://github.com/tailscale/tailscale/assets/29443173/eff571af-141b-465e-b46d-888135f62606)

### Bug report

N/A

**Comment by agottardo** [comment]
205 (1.65.4-t7a77a2edf-gfab2f183b34) is now rolling out on the Play Store open testing track including a fix for this.
