### ISSUE TITLE
[BUG] Android: Storage Permissions

### ISSUE THREAD

**Issue by LeaderbotX400** [tailscale/tailscale#11705]
### What is the issue?

Modal in app stating "We use storage in order to receive files with Taildrop" Continue button does nothing, and the in android app manager does not show the app asking for storage permissions. 

App becomes unsable as there is no way to dismiss the modal. Reinstall did not fix

### OS

Android

### OS version

Android 10

### Tailscale version

1.65.0-t220764331-g50bb25aca2d

### Bug report

Unable to generate as the modal blocks access to bug report button

**Comment by bradfitz** [comment]
Which phone is this?

**Comment by LeaderbotX400** [comment]
> Which phone is this?

Samsung Galaxy S9

**Comment by LeaderbotX400** [comment]
Manage to grab a bug report before the app gave me the pop up

BUG-8f03e0eb2eaa50b1a6c639e5782d2f81ca901a9ffcc956d9eb0163ca98c7fd81-20240413174835Z-beabe0940d6c871f
