### ISSUE TITLE
Non-expiring key shows as .1f years ago in Android re-design

### ISSUE THREAD

**Issue by danbracey** [tailscale/tailscale#11706]
### What is the issue?

When viewing a node in the new Android re-design, 'Key expiry' shows .1f years ago if the node is set to Expiry disabled.

### Steps to reproduce

Ensure Android client is on new beta
Create or set a node to expiry disabled 
![Screenshot_20240412_232327](https://github.com/tailscale/tailscale/assets/16801642/e55c156c-b679-4815-88ee-4e2bbdf61c22)

### Are there any recent changes that introduced the issue?

Only on new Android client (Beta)

### OS

Android

### OS version

Android 13, OneUI 5.1

### Tailscale version

Version 1.65.0-t220764331-g50bb25aca2d

### Other software

N/A

### Bug report

BUG-fb3f135440b15d4f70e8b34b8392e6606121d59ed303036ce7c044ba8771fafa-20240412222503Z-0da9395ec64a4c43

**Comment by agottardo** [comment]
Will be fixed by https://github.com/tailscale/tailscale-android/pull/320 once merged

**Comment by agottardo** [comment]
Fix is rolling out to testing Play Store users in build 206 (1.65.4-t7a77a2edf-gf95428f7fa4)
