### ISSUE TITLE
FYI: tailscale 1.64.0 released on Homebrew bottle and cask prior to release here in tailscale repo

### ISSUE THREAD

**Issue by adamfeldman** [tailscale/tailscale#11718]
### What is the issue?

https://github.com/Homebrew/homebrew-core/pull/168674#issuecomment-2053656365

### OS

macOS

**Comment by bradfitz** [comment]
Thanks. Looks like the GitHub release step wasn't done.

I see the 1.64.0 binary at https://pkgs.tailscale.com/stable/#macos but no 1.64.0 release at https://github.com/tailscale/tailscale/releases

/cc @phirework

**Comment by phirework** [comment]
Thanks for reporting! This has been corrected, sorry about the confusion.
