### ISSUE TITLE
F-droid Version 1.61.105-t7429e8912-g12210d3f26b crashes at launch

### ISSUE THREAD

**Issue by joetul** [tailscale/tailscale#11719]
### What is the issue?

The tailscale android  app crashes immediately upon launching on both my nvidia shield and pixel phone. 

### Steps to reproduce

1. Install Tailscale F-droid version 1.61.105-t7429e8912-g12210d3f26b
2. Attempt to open the app.

### OS version

Android 14

**Comment by ozls** [comment]
Same thing here with up to date GrapheneOS, Pixel 6a, no Google services

**Comment by bradfitz** [comment]
That's the old version of the app. A rewrite is launching soon and is available as of yesterday for beta testing. 

(These sorts of crashes are why the app UI was rewritten.)

**Comment by linsui** [comment]
@bradfitz Should we switch to the new UI? I was told to continue publishing the legacy app. Should I stop the update until the new app is ready?

**Comment by bradfitz** [comment]
Ideally F-Droid would pause for a bit until the new app is ready. It won't be long.

**Comment by linsui** [comment]
OK. :ok_hand:

**Comment by Zocker1999NET** [comment]
I understand & acknowledge that errors, in any way, can & will happen, so I don’t want to blame anyone with my comment. But in my opinion, this issue is critical & should deserve more immediate actions:

- on F-Droid, select the former, working version as suggested immediately, to prevent more users from running into this issue
- rebuild the last working version (`1.58.2-tb0e1bbb62-gcd1f0649958`) and push it to F-Droid as version something like `1.61.106-really1.58.2`

I think those immediate actions are reasonable because this issue breaks Tailscale for all users using F-Droid & it is hard to revert that issue:
- Android, I think starting with version 13, has an app downgrade protection enabled. So it prevents users from just downgrading the app.
- Because the app [prevents being part of system backups](https://github.com/tailscale/tailscale-android/blob/a1d97baeb02948b842645394dcd8a3b81132e9d1/android/src/main/AndroidManifest.xml#L29), I also cannot just remove the app & install a former version and then am good to go. Rather, I need to:
  - reauthenticate in the app
  - the app gets a new IPv4 assigned (admins may change that to the old one)
  - because the "old app" was not properly signed out, it still blocks the MagicDNS hostname, so I get there a new one as well (admins can fix that)
  - if Tailscale Lock is enabled, the app needs to be resigned



> Ideally F-Droid would pause for a bit until the new app is ready. It won't be long.

@bradfitz can you maybe estimate more exactly when the new app release will happen? I cannot really determine if you mean something like 1-2 days or 1-2 weeks. (in case pushing the latest working version is not possible)

**Comment by bradfitz** [comment]
@Zocker1999NET, we at Tailscale are not involved in the F-Droid packaging or release decisions. We put code on GitHub and other people put it on F-Droid.

Our version numbering scheme is minor numbers that are even are stable (58) and odd are unstable dev releases (like 61). Apparently somebody put a random snapshot of in-progress code on F-Droid (61 is odd) that we never released or tested ourselves and it crashes. That's not code we would ship (and didn't ship to the Google Play Store).

So, yes, F-Droid should probably roll back to a stable release that worked. But that's not in my power.

I won't speak for the Android team on their schedule. But it seems to be moving very rapidly so I don't think it'll take two weeks. F-Droid should probably be ready to package it within a week.

**Comment by linsui** [comment]
I have disabled the crashed versions. But the users have to reinstall the old versions manually since Android doesn't allow downgrading. I checked that `1.64.0-t78dc8622d-gfd2ca6fa940` also crashes so it's not a problem of unstable version but it seems the legacy app has some problems. I'll wait until the new app is ready.

**Comment by bradfitz** [comment]
@linsui, we also never released 1.64.x to the Play Store. Or 1.62.x.

If you want to match what most our users are currently running on Android, you want `1.60.1-t2caffeeb4-g6f7ae79a31c`. That's the non-beta Play Store version.

**Comment by linsui** [comment]
We don't check Google Play. all the versions are build against the published tags. So IIUC, the tag is only for the new app.

**Comment by bradfitz** [comment]
Which tag was F-Droid built against?

**Comment by Zocker1999NET** [comment]
> Which tag was F-Droid built against?

As visible [in this file](https://gitlab.com/fdroid/fdroiddata/-/blob/10dd6efbd96609326b5a4e19e2e1405eb6f3c0d3/metadata/com.tailscale.ipn.yml), IIUC:
- version `1.61.105-t7429e8912-g12210d3f26b`, the one which was released, was built against tag [1.63.93-t1fbaf2610-ge0020f8c4bf](https://github.com/tailscale/tailscale-android/releases/tag/1.63.93-t1fbaf2610-ge0020f8c4bf) but using the subdir `android_legacy` ([src](https://gitlab.com/fdroid/fdroiddata/-/blob/10dd6efbd96609326b5a4e19e2e1405eb6f3c0d3/metadata/com.tailscale.ipn.yml#L1293-1297))
- version `1.64.0-t78dc8622d-gfd2ca6fa940` was build against commit [97cc00210ee30d4f1ca5cbe67bb7642b31629de4](https://github.com/tailscale/tailscale-android/commit/97cc00210ee30d4f1ca5cbe67bb7642b31629de4) also using the subdir `android_legacy` ([src](https://gitlab.com/fdroid/fdroiddata/-/blob/10dd6efbd96609326b5a4e19e2e1405eb6f3c0d3/metadata/com.tailscale.ipn.yml#L1329-1333))

**Comment by linsui** [comment]
Yep, the build from android failed so I checked the source code and found that the old code is moved to android_legacy. Then I [was told](https://github.com/tailscale/tailscale/issues/11662) that I should continue building the old app.

**Comment by mikelococo** [comment]
> I have disabled the crashed versions. But the users have to reinstall the old versions manually since Android doesn't allow downgrading.

@linsui Can I confirm that the workaround is:

1. There's no possibility of a direct-downgrade via F-Droid.
2. The app must be uninstalled, then when we attempt to reinstall, the suggested version will be `1.58.2-tb0e1bbb62-gcd1f0649958` published on 2/10/24 (or eventually something newer that isn't broken) will be the suggested version?
3. We should expect to deal manually deal with the fallout of the issues described by @Zocker1999NET related to having to re-register the tailscale client and get a new identity/ip?

**Comment by linsui** [comment]
> There's no possibility of a direct-downgrade via F-Droid.

It's not allowed on Android.

> The app must be uninstalled, then when we attempt to reinstall, the suggested version will be 1.58.2-tb0e1bbb62-gcd1f0649958 published on 2/10/24 (or eventually something newer that isn't broken) will be the suggested version?

Yep, after about 1 week.

> We should expect to deal manually deal with the fallout of the issues described by @Zocker1999NET related to having to re-register the tailscale client and get a new identity/ip?

If you don't want to unintall tailscale you need to wait until the new version is available. I don't know how long it would take. I don't know if you can set the same ip.

A workaround is releasing an old version with a higher version code. Should I do that?

**Comment by mikelococo** [comment]
> A workaround is releasing an old version with a higher version code. Should I do that?

I won't weigh in on this question. I can imagine reasons why this would be a good idea, and reasons why it could make things more complicated in the future. I'm not familiar enough with the tailscale release processes to have a sensible opinion about the tradeoffs.

Thanks for your work packaging this, and trying to get to the bottom of how to recover.

**Comment by Zocker1999NET** [comment]
> A workaround is releasing an old version with a higher version code. Should I do that?

Assuming that it is relatively easy and faster than waiting until a working next version is found/released, I say yes. If possible, please test if Tailscale is working after that "downgrade" before its released as "suggested" on F-Droid. (If I can download a F-Droid signed apk, I am ready to test that as well.)

In that context, how long does it typically take until a signed F-Droid build is compiled & published?

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14867 You'll be able to update to a working version in about 1 week.

**Comment by bradfitz** [comment]
> A workaround is releasing an old version with a higher version code. Should I do that?

That sounds fine to me, at least. As long as you're not picking a version code greater than what's in the tree now. But there should be a handful of numbers free to choose from.

**Comment by bradfitz** [comment]
Does a human test new Tailscale versions in F-Droid or can the F-Droid bot auto-bump things from git and release it to everybody without checking that the app even starts without crashing?

I suspect something got broken in the move from `android` to `android_legacy` and that's why `libgio.so` is crashing on start.

**Comment by linsui** [comment]
I picked 203 which should be OK.

I didn't test the apk. When the bot update the metadata generally no one tests the apk.

**Comment by mikelococo** [comment]
@linsui Was `1.64.0-t78dc8622d-gfd2ca6fa940` released on the 14th with the intent of fixing the crash, or do we still expect things to be broken? It's seems to be the same behavior for me after upgrading... the tailscale app still immediately crashes after tapping to start it.

**Comment by e-zk** [comment]
Just to be clear, the delayed releases issue is a known issue with F-Droid. The onus shouldn't be on the Tailscale team to release the previous version at a higher version level. That isn't fair on them.

**Comment by linsui** [comment]
@mikelococo No, it's a version updated before I found this problem. The fixed version will be published in the next update.

**Comment by Atemu** [comment]
I think the real bug here is that dev/beta releases are indistinguishable from real releases to outside packagers.

Would it be possible to distinguish these in the git tags or utilise Github's release feature (which supports pre-releases)?

**Comment by mikelococo** [comment]
For anyone watching here for status...

`1.60.1-t2caffeeb4-g6f7ae79a31c` released to fdroid yesterday on 4/17 addresses the issue for me and Tailscale no longer crashes on startup. If you waited the issue out and did NOT uninstall, the client "just" connects as normal. If you uninstalled, then presumably you had to re-register your client.

**Comment by sethro2** [comment]
All is well again and thank you.

**Comment by agottardo** [comment]
@linsui @Atemu note that [1.66.3 has been tagged](https://github.com/tailscale/tailscale-android/releases/tag/1.66.3-teae73f821-g63a2bbc8e71) on the tailscale-android repo. You can release that tag to F-Droid users if you wish.

In general, at any given time, the latest commit tagged with an even minor version number is always safe to release to users (1.62.1, 1.64.0, 1.66.3), etc. Any release with an odd minor version number should be ignored.

**Comment by linsui** [comment]
Why is the new client so large? The 1.60.1 apk is 40M and the 1.66.3 apk is 90M.

**Comment by Atemu** [comment]
(Note that I'm not involved with F-droid but I do help maintain a different distro.)

> In general, at any given time, the latest commit tagged with an even minor version number is always safe to release to users (1.62.1, 1.64.0, 1.66.3), etc. Any release with an odd minor version number should be ignored.

Thank you for that piece of information!

I also just noticed that odd releases aren't published as GH releases and that their tags are distinguished via a `pre` suffix. This looks like an issue of F-droid's updater, not Tailscale.

**Comment by linsui** [comment]
There is no issue from F-Droid side, no worries. And you are looking at a wrong repo.

**Comment by namaneko** [comment]
Is the version in the Play Store different from the F-Droid version?

I am experiencing the same issue. Crashes almost immediately after opening. This is on a Pixel 5 running the latest version of LineageOS.

I am downloading F-Droid now to test and see if there's any difference.

**Comment by Atemu** [comment]
@namaneko you're likely experiencing a different issue then.

**Comment by SolderFish** [comment]
I'm having the same issue now too. Crashes on connect.

Steps to reproduce
Install Tailscale Google Play version 1.66.3-teae73f821-g63a2bbc8e71
Attempt to connect to Tailscale after signing in.

Are there any recent changes that introduced the issue?
No response

OS
Google Pixel Stock Rom (No Root)

OS version
Android 14

Device
Google Pixel 7a

Tailscale version
Google Play version 1.66.3-teae73f821-g63a2bbc8e71

Other software
Windscribe VPN (not running or connected)

Bug report
No response

**Comment by agottardo** [comment]
If you're experiencing issues with crashes, I recommend testing the latest unstable version from the Beta channel on the Play Store, or the [pkgs](https://pkgs.tailscale.com/unstable/#android) server. We resolved a number of crashes on launch since 1.66.3 was released.

Please open a **new** issue to report crashes with newer versions of the app.
