### ISSUE TITLE
[F-Droid] Client immediately crashes after updating

### ISSUE THREAD

**Issue by ORIOLESFan02** [tailscale/tailscale#11727]
### What is the issue?

I updated from F-Droid and tailscale won't open. 
[Error in Tailscale 38fdc3b533d0 (4-13-24).txt](https://github.com/tailscale/tailscale/files/14969047/Error.in.Tailscale.38fdc3b533d0.4-13-24.txt)

Here is a log file that GrapheneOS Provided

### Steps to reproduce

1. Go to the F-Droid store
2. Search for Tailscale
3. Download (or Update) Tailscale
4. Run Tailscale

### Are there any recent changes that introduced the issue?

Updated via F-Droid

### OS

Android

### OS version

GrapheneOS (Android 14)

### Tailscale version

1.61.105-t7429e8912-g12210d3f26b

### Other software

N/A

### Bug report

N/A

**Comment by ORIOLESFan02** [comment]
If you'd rather not download the text file. 

```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240405.002/2024040900:user/release-keys
package: com.tailscale.ipn:201
process: com.tailscale.ipn
processUptime: 0 + 0 ms
installer: org.fdroid.fdroid

signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------

backtrace:
      #00 pc 00000000005258d8  /data/app/~~krijucjawBcCy9hFy1e5FQ==/com.tailscale.ipn-GY7UNRiGNEOF7wVaDC4OFg==/lib/arm64/libgio.so
```

**Comment by ORIOLESFan02** [comment]
Although if you want a complete log, you'd have to download this
[Tailscale log 812e0e84b7c5 (4-13-24).txt](https://github.com/tailscale/tailscale/files/14969078/Tailscale.log.812e0e84b7c5.4-13-24.txt)

**Comment by bradfitz** [comment]
Dup of #11719
