### ISSUE TITLE
[Android Beta Client] cannot ping (and connect to) other devices in tailnet through Android client

### ISSUE THREAD

**Issue by Ziomal12** [tailscale/tailscale#11731]
### What is the issue?

When connected to self-hosted Headscale instance android client cannot ping nor initiate connections to other devices on tailnet. (Checked with Termux ping command, Ping tools and CX file explorer for SMB and ConnectBot for SSH).

The only scenario I was able to get a ping was when pinging exit node that the android client was currently using.

Other devices in tailnet can ping android client without issues all the time.

No ACL is present.

### Steps to reproduce

1. ~~Build android client (see #11716 and [tailscale/tailscale-android#325](https://github.com/tailscale/tailscale-android/pull/325)~~ Download Android Beta Client `1.65.4-t7a77a2edf-gf95428f7fa4` from Play Store.
2. Login to self hosted tailscale instance.
3. Enable tailscale.
4. Try to ping other device in tailnet from Android client (fails).
5. Enable exit node.
6. Try to ping currently used exit node from android client (successful).

### Are there any recent changes that introduced the issue?

Android beta client, self built beta app.

### OS

Android

### OS version

Android 14

### Tailscale version

~~1.65.0-t220764331-g50bb25aca2d (with [tailscale/tailscale-android#325](https://github.com/tailscale/tailscale-android/pull/325))~~
1.65.4-t7a77a2edf-gf95428f7fa4

### Other software

Headscale v0.23.0-alpha5 (also tested with v0.22.3)

### Bug report

BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

I'm more than happy to provide logs in other way, given instructions how.

**Comment by Ziomal12** [comment]
**I'm able to ping all devices using hostnames** but still cannot ping using ips.

I might be looking in wrong place but with `adb logcat | grep com.tailscale.ipn` what caught my eye was in:
(with exit node connected)
`04-14 11:09:08.983  2037  9026 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{network{122}  handle{527391707149}  ni{VPN CONNECTING extra: VPN:com.tailscale.ipn} created=2024-04-14T09:09:08.983Z Score(Policies : IS_UNMETERED&IS_VPN ; KeepConnected : 0)   lp{{InterfaceName: tun0 LinkAddresses: [ 100.64.0.10/32,fd7a:115c:a1e0::a/128 ] DnsAddresses: [ /100.100.100.100 ] Domains:  MTU: 1280 Routes: [ 0.0.0.0/0 -> 0.0.0.0 tun0 mtu 0,::/0 -> :: tun0 mtu 0,100.100.100.100/32 -> 0.0.0.0 tun0 mtu 0 ]}}  nc{[ Transports: VPN Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED TransportInfo: <VpnTransportInfo{type=1, sessionId=null, bypassable=false longLivedTcpConnectionsExpensive=false}> Uids: <{0-10444, 10446-10469, 10471-20444, 20446-20469, 20471-99999}> OwnerUid: 10749 AdminUids: [10749] UnderlyingNetworks: Null]}  factorySerialNumber=6}
04-14 11:09:08.984  2037  9026 I Vpn     : Established by com.tailscale.ipn on tun0`

And
(withoit exit node connected)
`04-14 11:09:31.683  2037  3502 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{network{123}  handle{531686674445}  ni{VPN CONNECTING extra: VPN:com.tailscale.ipn} created=2024-04-14T09:09:31.683Z Score(Policies : IS_UNMETERED&IS_VPN ; KeepConnected : 0)   lp{{InterfaceName: tun0 LinkAddresses: [ 100.64.0.10/32,fd7a:115c:a1e0::a/128 ] DnsAddresses: [ ] Domains:  MTU: 1280 Routes: [ 100.100.100.100/32 -> 0.0.0.0 tun0 mtu 0 ]}}  nc{[ Transports: VPN Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED TransportInfo: <VpnTransportInfo{type=1, sessionId=null, bypassable=false longLivedTcpConnectionsExpensive=false}> Uids: <{0-10444, 10446-10469, 10471-20444, 20446-20469, 20471-99999}> OwnerUid: 10749 AdminUids: [10749] UnderlyingNetworks: Null]}  factorySerialNumber=6}
04-14 11:09:31.684  2037  3502 I Vpn     : Established by com.tailscale.ipn on tun0`

There's no route for 100.64.0.0/24 (only /32 routes)

**Comment by bradfitz** [comment]
> There's no route for 100.64.0.0/24 (only /32 routes)

Why should there be a /24 route? Are you advertising such a route from a node? Are you accepting routes on the client?

**Comment by Ziomal12** [comment]
> Why should there be a /24 route? Are you advertising such a route from a node? Are you accepting routes on the client?
What I meant was I don't see any route being applied for other peers ( i.e. 100.64.0.3/32). But that might be wrong place to look.
I don't have any routes applied nor advertised except for exit node on linux machine.

**Comment by MulverineX** [comment]
I'm using headscale `0.22.3` and the [build](https://drive.google.com/file/d/1xBgJkeLtAONTT5Lc7gEYG4ACHAYKBjzy/view?usp=drivesdk) Ziomal posted from https://github.com/tailscale/tailscale-android/pull/325 . I *am* able to ping other nodes in the tailscale network, however, I cannot load webpages being hosted by a node, which is a direct regression from the Tailscale Android version I was using before, `1.54`.

**Comment by MulverineX** [comment]
@agottardo it looks like your PR doesn't completely solve the connectivity issues with self-hosted tailscale.

**Comment by agottardo** [comment]
> @agottardo it looks like your PR doesn't completely solve the connectivity issues with self-hosted tailscale.

Unfortunately because you're using Headscale we cannot gather any diagnostics from your tailnet. You also did not attach any logs for us to diagnose the issue, so it is very hard to understand what is going on. You'll need to run `adb logcat | grep com.tailscale.ipn` and report any errors you see while attempting to ping the remote device. 

When you fail to connect to the devices, do they appear in the devices list in the app, or are they also missing there?

**Comment by Ziomal12** [comment]
Here are the logs, sorry for not attaching them earlier.

Other nodes are correctly displayed in app: their status, hostnames and ip's, all informations are correct. I'm able to ping the android device from other nodes however I cannot ping _from_ android.


[tailscale-exit-node.log](https://github.com/tailscale/tailscale/files/14984374/tailscale-exit-node.log) - I opened app, connected to tailnet, chose exit node, later switched apps and was able to ping exit node and could not able to ping other nodes.

[tailscale-no-exit-node.log](https://github.com/tailscale/tailscale/files/14984375/tailscale-no-exit-node.log) -  I opened app, connected to tailnet,  switched apps and could not able to ping other nodes.

**Comment by Norodix** [comment]
I have the exact same issues. Devices show up in the android client, the connected devices are displayed green. I can use tailscale ping to ping the phone from the PC but I cannot use regular ping to access it.

**Comment by Ziomal12** [comment]
@Norodix also using Headscale? If so what version?

**Comment by Norodix** [comment]
yes, v0.22.3

**Comment by agottardo** [comment]
@Norodix can you please attach some logs?

**Comment by Norodix** [comment]
I'm not very familiar with android, if you can give me some instructions I can provide the exact logs you need. I printed some logs with adb logcat and grepped for tailscale, this is what I got. I hope it helps somewhat.

[adb_log_tailscale.txt](https://github.com/tailscale/tailscale/files/15015959/adb_log_tailscale.txt)

**Comment by Ziomal12** [comment]
When compering logs from when connected to headscale and tailscale server something caught my eye (both servers have a few nodes connected):

Headscale:
`04-18 09:09:41.835  2003  3673 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{network{107}  handle{462967197709}  ni{VPN CONNECTING extra: VPN:com.tailscale.ipn} created=2024-04-18T07:09:41.835Z Score(Policies : IS_UNMETERED&IS_VPN ; KeepConnected : 0)   lp{{InterfaceName: tun0 LinkAddresses: [ 100.64.0.4/32,fd7a:115c:a1e0::4/128 ] DnsAddresses: [ ] Domains:  MTU: 1280 Routes: [ 100.100.100.100/32 -> 0.0.0.0 tun0 mtu 0 ]}}  nc{[ Transports: VPN Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED TransportInfo: <VpnTransportInfo{type=1, sessionId=null, bypassable=false longLivedTcpConnectionsExpensive=false}> Uids: <{0-10444, 10446-10469, 10471-20444, 20446-20469, 20471-99999}> OwnerUid: 10726 AdminUids: [10726] UnderlyingNetworks: Null]}  factorySerialNumber=6}`

Tailscale's server:
`04-18 09:10:26.069  2003  2106 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{network{109}  handle{471557132301}  ni{VPN CONNECTING extra: VPN:com.tailscale.ipn} created=2024-04-18T07:10:26.069Z Score(Policies : IS_UNMETERED&IS_VPN ; KeepConnected : 0)   lp{{InterfaceName: tun0 LinkAddresses: [ 100.103.30.79/32,fd7a:115c:a1e0::ed01:1e4f/128 ] DnsAddresses: [ /100.100.100.100 ] Domains: tail43353.ts.net rednas.ovh MTU: 1280 Routes: [ 100.76.31.70/32 -> 0.0.0.0 tun0 mtu 0,100.87.172.75/32 -> 0.0.0.0 tun0 mtu 0,100.91.28.81/32 -> 0.0.0.0 tun0 mtu 0,100.119.22.118/32 -> 0.0.0.0 tun0 mtu 0,fd7a:115c:a1e0::/48 -> :: tun0 mtu 0,100.100.100.100/32 -> 0.0.0.0 tun0 mtu 0 ]}}  nc{[ Transports: VPN Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED TransportInfo: <VpnTransportInfo{type=1, sessionId=null, bypassable=false longLivedTcpConnectionsExpensive=false}> Uids: <{0-10444, 10446-10469, 10471-20444, 20446-20469, 20471-99999}> OwnerUid: 10726 AdminUids: [10726] UnderlyingNetworks: Null]}  factorySerialNumber=6}`

Seems like when connected to Headscale server the app doesn't create routes:
headscale: `Routes: [ 100.100.100.100/32 -> 0.0.0.0 tun0 mtu 0 ]`
tailscale: ` Routes: [ 100.76.31.70/32 -> 0.0.0.0 tun0 mtu 0,100.87.172.75/32 -> 0.0.0.0 tun0 mtu 0,100.91.28.81/32 -> 0.0.0.0 tun0 mtu 0,100.119.22.118/32 -> 0.0.0.0 tun0 mtu 0,fd7a:115c:a1e0::/48 -> :: tun0 mtu 0,100.100.100.100/32 -> 0.0.0.0 tun0 mtu 0 ]`

**Comment by Ziomal12** [comment]
Issue still present on `1.65.95-t71e9258ad-g5ea9a50ba57`

**Comment by oxtoacart** [comment]
Okay, the problem is that we're passing the ControlURL as part of ipn.Notify.UpdatePrefs in the call to the `start` API. This has the effect of setting prefs that don't enable single IPs nor subnet routes, so as a result, none of the peer's AllowedIPs make it into our routes.

This was not a problem with the old client because it didn't use that option, it manually updated prefs.

Old

```
state.Prefs.ControlURL = e.URL
				b.backend.SetPrefs(state.Prefs)
				// Need to restart to force the login URL to be regenerated
				// with the new control URL. Start from a goroutine to avoid
				// deadlock.
				go func() {
					err := b.backend.Start(ipn.Options{})
					if err != nil {
						fatalErr(err)
					}
				}()
```

New

```
Client(viewModelScope).addProfile { addProfile ->
      addProfile.onFailure(fail).onSuccess {
        prefs.ControlURL = controlURL
        val options = Ipn.Options(UpdatePrefs = prefs)
        login(options, completionHandler)
      }
    }
```

**Comment by Ziomal12** [comment]
On `1.65.182-t80df8ffb8-g6a15347453c` after loging out and back in the issue seemed resolved however after phone reboot the connection wouldn't go back up and would be stuck at `starting...`. After loging out I was not able to log back in again. The app would go to server login screen and after authentication wouldn't do anything. The only way to connect is to wipe tailscale data and then log in (essential creating a new node in tailnet as node key changes). After rebooting again the same problem appears (stuck at connecting)
Bug report `BUG-edd5c1449d1713c8d4d2109d16abaefbc75d7284f04a9133535f423bb600bd5e-20240508061002Z-02f583d655b4034f`

**Comment by Ziomal12** [comment]
In headscale logs after successful authorisation I see `2024-05-08T08:07:39+02:00 INF home/runner/work/headscale/headsc
ale/hscontrol/poll.go:657 > node has an open stream(0x4000a8c48
0), rejecting new stream node=localhost node.id=6 omitPeers=fal
se readOnly=false stream=true`
After force closing the app and restarting headscale I'm able to log back in.

**Comment by Ziomal12** [comment]
@K900 try login out and back it. I've tested just now with `1.66.0-te2a0fc0bc-g6bd50e8026d` and it works. If still no luck try clearing app data and log again.

**Comment by K900** [comment]
OK for some reason it worked after a clean reinstall.

**Comment by MulverineX** [comment]
Can confirm, it works now 🎉🚀. If it's intended for authorization to be invalidated/broken in the refactor, ideally they would be automatically removed upon upgrade, either way though this should be a separate issue. Huge thanks to all the work/support from the Tailscale team for FOSS users!
