### ISSUE TITLE
Chromecast incompatible

### ISSUE THREAD

**Issue by ttoille123** [tailscale/tailscale#11768]
I noticed that chromecast at least HD is labeled as unsupported. I was wondering if this was intentional or not

**Comment by bradfitz** [comment]
Can you elaborate?

Where'd you try to install from? What version? What Chromecast?

**Comment by ttoille123** [comment]
On chromecast it's self it doesn't show up and when I try to install it with my phone it says it's not compatible with Tailscale. Latest version of google tv

**Comment by bradfitz** [comment]
Could you try the new in-progress beta app for Android? See https://www.reddit.com/r/Tailscale/comments/1c2jdhp/android_users_can_you_keep_a_secret

**Comment by ttoille123** [comment]
Still nothing

**Comment by ttoille123** [comment]
Even Tailscale for Fdroid refuses to run

**Comment by minime9854** [comment]
Tailscale from Fdroid is also failing to run at all on Fire stick 4k and 4k MAX on any version after 1.58.2

**Comment by bradfitz** [comment]
F-Droid is broken for unrelated reasons. That is https://github.com/tailscale/tailscale/issues/11719.

**Comment by bradfitz** [comment]
You have to wait ~4 hours for Google/Android to move you to the beta testing track.

A coworker just tried the new app on his Chromecast HD and it works fine.

So this seems done. It'll be in the Play Store in time, once it gets published and through Google review.

**Comment by ttoille123** [comment]
It's been a while now and it still lists as incompatible

**Comment by bradfitz** [comment]
The metadata on a future build will be set appropriately. But rest assured it does work when using an APK built from source today.

**Comment by ttoille123** [comment]
Is there any way to due to myself and use it right now?

**Comment by bradfitz** [comment]
The source is at https://github.com/tailscale/tailscale-android/ ... see the README and the Makefile for instructions.

**Comment by jbddc** [comment]
hi, I can confirm the app is not present on the google play store on the nvidia shield either...
