### ISSUE TITLE
syncs: TestWatchMultipleValues flake

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#11766]
Oh, GitHub Actions, never change:

```
 === RUN   TestWatchMultipleValues
    watchdog_test.go:62: uncontended mutex did not lock in under 1ms
--- FAIL: TestWatchMultipleValues (0.14s)
FAIL	tailscale.com/syncs
```

(on Windows)

**Comment by sword-jin** [comment]
Since there is no real caller of this function, maybe we can remove it.

**Comment by bradfitz** [comment]
Hah, indeed.

/cc @dsnet @maisem @raggi --- any memory why this exists?

**Comment by bradfitz** [comment]
Ah, it was for our ancient database, monitoring mutex contention. It was deleted in Jun 2023.
