### ISSUE TITLE
Default routes should block LAN access by default

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1177]
Came up while designing/implementing default routing: an interesting use case is being able to share an "exit node" with friends and family. However, that feels much safer to do if that sharing doesn't also grant access to your LAN. In other words, "share my internet" should mean "share access to the internet", not "share access to whatever my subnet router happens to have access to".

In practice, that would mean that enabling default routing on a node would offer access to 0.0.0.0/0 and ::/0, but explicitly block access to:
 - RFC1918 and RFC6598 IPv4 space (LAN and CGNAT)
 - IPv6 ULA space
 - The IP space of directly-connected ethernet segments (e.g. the IPv6 /64 assigned to the LAN by the local internet router)

This would mean that, if I share my internet connection with you, you can access e.g. google.com through my node, but you can't load 192.168.0.1 and get to my router's admin panel.

This is a default only, overridable by explicitly advertising the above-filtered routes in addition to default routes.

Part of #102.

**Comment by danderson** [comment]
Additional note: we should get a new TSMP error code for this, so that we can eagerly reject disallowed connections, and point users to the appropriate documentation for changing the default, if they want to.

**Comment by bradfitz** [comment]
Would you carve out those ranges from what you advertise, or advertise the /0s and then reject packets to the private subranges once they arrived? Sounds like the latter? Otherwise the admin UI would be super ugly having to approve a bunch of fractal of CIDRs.

**Comment by danderson** [comment]
Yes, the latter. The UIs show just default routes, and the router applies additional local policy to protect local endpoints. It's also necessary because the local segments might change at runtime (e.g. ISP router reboot changes the assigned v6 /64), and we don't want to require a reapproval when that happens.
