### ISSUE TITLE
Add Windows Server flag to hostinfo

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#11785]
Some editions of Windows server share the same build number as their client counterpart; it's the `ProductType` field of [`OsVersionInfoEx`](https://pkg.go.dev/golang.org/x/sys/windows#OsVersionInfoEx) that distinguishes between them.

(Note that domain controllers are also implicitly servers)

We should get this info into `hostinfo` somehow. Change the format of the `OS` field? Use `Distro` or `Desktop` to store this information? A new field?

**Comment by bradfitz** [comment]
I'm always torn between adding new fields and grossly reusing existing fields, but "Distro" is pretty close if not perfect. It's really only the strong Linux association that gives me pause, but the actual word is totally correct. Let's go with that unless you super hate it?

**Comment by dblohm7** [comment]
WFM!
