### ISSUE TITLE
v1.64.1 and v1.64.2 are not released on yum registry

### ISSUE THREAD

**Issue by gnuletik** [tailscale/tailscale#11795]
### What is the issue?

Github releases contains two new releases not published on yum registry.

### Steps to reproduce

```
docker run --platform linux/amd64 -it --rm amazonlinux:2 /bin/bash
yum install -y yum-utils
yum-config-manager --add-repo https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo
yum list tailscale --showduplicates
```

Results
```
...
tailscale.x86_64                                                                                    1.60.1-1                                                                                        tailscale-stable
tailscale.x86_64                                                                                    1.62.0-1                                                                                        tailscale-stable
tailscale.x86_64                                                                                    1.62.1-1                                                                                        tailscale-stable
tailscale.x86_64                                                                                    1.64.0-1                                                                                        tailscale-stable
```

### OS

Linux

### OS version

Amazon Linux 2

### Tailscale version

1.64.2

**Comment by gnuletik** [comment]
As a general question: what is the current workflow to release updates on the yum registry? Isn't it automated
We were using Github releases as a source of truth to trigger updates but doesn't seems to be a source of truth.

Thanks!

**Comment by bradfitz** [comment]
There were no Linux-specific changes in those point releases. One fix was specific to Synology and one was specific to the Windows installer.

**Comment by gnuletik** [comment]
Ah OK, makes sense thanks!

However, it seems a bit non-idiomatic to have a "last version" set as 1.64.2 without a release for all platforms.
For example, we can see many versions flagged as out of date here: https://repology.org/project/tailscale/versions

WDYT of having the same version released on all platforms, even if there are no specific changes?
I guess that it would be easier to track for maintainers.

Thanks!

**Comment by bradfitz** [comment]
We have https://pkgs.tailscale.com/stable/?mode=json and `tailscale update --dry-run` at least.
 
I defer to @awly for the overall question, though.

**Comment by awly** [comment]
Yep, `TarballsVersion` https://pkgs.tailscale.com/stable/?mode=json is the best source we have right now for "latest version on Linux".

>  For example, we can see many versions flagged as out of date here: https://repology.org/project/tailscale/versions

We maintain deb and rpm repos, but we can't realistically maintain Tailscale packages in all of the Linux distros. It's an unfortunate side-effect of the Linux ecosystem being so fractured.

> As a general question: what is the current workflow to release updates on the yum registry? Isn't it automated

It is automated for most types of packages (including RPMs). Our build tooling lets us choose which packages to rebuild for any release though, and we typically exclude the platforms that have no changes. 

> WDYT of having the same version released on all platforms, even if there are no specific changes?

That's a good question. We could pretty easily build Linux (including containers), Windows and Mac packages for every release, even if there are no changes. Android/iOS are a bit more work, and they have to go through their respective app store reviews/validations. NAS platforms like Synology have a very long review cycle, so we can't even release every major version. And we don't control things like Alpine at all.

So there will always be some straggler platforms, it's just a question of where to draw the line.

@gnuletik other than it being confusing with github releases, are there any other implications of not releasing Linux packages? We could mention more explicitly in github release notes when we're not building that version for some platforms. I would prefer not to force unnecessary updates on people, which just consumes energy and bandwidth for no benefit.

**Comment by hamishforbes** [comment]
This caught me for 1.64 too.
I'm subscribed to releases on this repo and saw the 1.64 release, also the Tailscale admin panel was telling me my nodes are out of date.
I tried to update my k8s deployments and found the container image didn't exist for 1.64.x so i got a bunch of failed pods in ImagePullBackoff.

**Comment by bradfitz** [comment]
The Tailscale admin panel saying nodes are out of date is a bug then. We should never scare people like that if an update isn't actually available.

**Comment by hamishforbes** [comment]
The 1.64.0 release has changed for All Platforms but there wasn't and still isn't a container for it?
Is that also a bug?

```
> docker pull ghcr.io/tailscale/tailscale:v1.64.0
Error response from daemon: failed to resolve reference "ghcr.io/tailscale/tailscale:v1.64.0": ghcr.io/tailscale/tailscale:v1.64.0: not found
```

There's an image for 1.64.1 - which only has a synology change, but also nothing for 1.64.2
I can't figure the logic for when a container does or does not get published?

**Comment by awly** [comment]
@hamishforbes containers are another special case in our release pipeline :sweat_smile: 
We generally release them a few days after the main release, because some downstream consumers use `:stable` or `:latest` tags, which will effectively cause them to update as soon as images are available. By delaying, we try to catch any significant user-reported issues in a new release that our testing didn't catch.

Now here's what happened with 1.64:
* 1.64.0 was build, without containers as described above
* 1.64.1 was cut with a Synology fix
* by the time we were comfortable with 1.64.0 stability, the latest release tag was 1.64.1, so that ended up in the container tag; this is why you see 1.64.1 but not 1.64.0
* 1.64.2 containers were also not yet built, since that's a newer release

This is definitely sub-optimal, so we went back and build 1.64.0 and now 1.64.2 as well. You should see all the tags, and `:latest` is `:1.64.2`.
I will document this scenario in our release process so we don't end up in this situation again.

**Comment by gnuletik** [comment]
> Yep, TarballsVersion https://pkgs.tailscale.com/stable/?mode=json is the best source we have right now for "latest version on Linux".

Thanks for that `?mode=json`! That'll help us, I'll make a CI step to check that the version is valid.

> We maintain deb and rpm repos, but we can't realistically maintain Tailscale packages in all of the Linux distros. It's an unfortunate side-effect of the Linux ecosystem being so fractured.

Yeah, I agree that this is not possible to make sure that the version available on every distribution is the latest because of how the ecosystem works.

> We could pretty easily build Linux (including containers), Windows and Mac packages for every release, even if there are no changes. Android/iOS are a bit more work, and they have to go through their respective app store reviews/validations. NAS platforms like Synology have a very long review cycle, so we can't even release every major version. And we don't control things like Alpine at all.
>
> So there will always be some straggler platforms, it's just a question of where to draw the line.

It looks like a fair trade-off to have common version released on every platform and have some version skipped on proprietary platforms. Especially as these platforms usually have their own upgrade mechanisms.

> @gnuletik other than it being confusing with github releases, are there any other implications of not releasing Linux packages? We could mention more explicitly in github release notes when we're not building that version for some platforms.

I think that:
- it creates confusion
- it leads to deployment issues if people uses Github release to deploy on other platforms

Mentioning the impacted platforms on the Github Release Note is a first good step I think.

> I would prefer not to force unnecessary updates on people, which just consumes energy and bandwidth for no benefit.

That's a fair point. I'd vote in favor of more versioning consistency, at the price of a bit of energy / bandwidth.
Especially as it looks like the platform specific updates are quite rare. But I'd understand your choice if you prefer to avoid unnecessary releases.

Thanks for your constructive answers!

**Comment by gnuletik** [comment]
For anyone interested, I configure renovate with the following rules in order to catch updates:

`renovate.json`
```json
{
  "customManagers": [
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "[ ]*# renovate: datasource=tailscale\n.*[ ]*:[ ]*\"(?<currentValue>.*)\".*"
      ],
      "depNameTemplate": "tailscale",
      "datasourceTemplate": "custom.tailscale",
      "versioningTemplate": "semver-coerced"
    }
  ],
  "customDatasources": {
    "tailscale": {
      "defaultRegistryUrlTemplate": "https://pkgs.tailscale.com/stable/?mode=json",
      "transformTemplates": [
        "{\"releases\": [{\"version\": $join([\"v\", Version])}]}"
      ]
    }
  }
}
```

This will update any .yaml containing the following rules:
```yaml
# renovate: datasource=tailscale
TAILSCALE_VERSION: "v1.62.1"
```

I also made a small Github Action to check that the given Tailscale version is installable:
```yaml
on:
  workflow_call:

jobs:
  test-install:
    name: Test Tailscale installation
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
      env:
        # renovate: datasource=tailscale
        TAILSCALE_VERSION: "v1.62.1"
    steps:
      - name: Install yum
        run: yum install -y yum-utils

      - name: Configure repo
        run: |
          yum-config-manager --add-repo https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo

      - name: Install Tailscale
        run: yum install -y tailscale-"$(echo $TAILSCALE_VERSION | sed 's/v//')"
```

@bradfitz do you have warranty that the schema of https://pkgs.tailscale.com/stable/?mode=json won't have breaking change?
