### ISSUE TITLE
FR: DNS Settings for Apple TVOS

### ISSUE THREAD

**Issue by vovchykbratyk** [tailscale/tailscale#11809]
### What are you trying to do?

I'd like to avoid using Tailscale DNS settings while my Apple TV is connected to Tailscale.  I would like to be able to use my Apple TV as an exit node, but I would like the TV itself to use my local DNS server for its own originating traffic.

### How should we solve this?

Offer an option in the Tailscale TVOS app that is the same as the iOS apps; an on/off selector for "Use Tailscale DNS Settings."

### What is the impact of not solving this?

My Tailscale mesh utilizes a VPS for DNS resolution.  When the TV is forced to use Tailscale DNS for its own originating traffic, it sends all DNS requests to the VPS.  While marginal, it still ends up accruing cost that I would prefer to avoid.

### Anything else?

Feel free to close this if the option exists, and let me know how to access it.  I just spent 10 minutes going through the TVOS TS menu though, and didn't see this option.  Let me know if I'm missing anything!  Thanks!

**Comment by agottardo** [comment]
This is not currently supported, however it should be very straightforward for us to bring over the existing iOS UI and allow you to configure DNS settings on Apple TV. Stay tuned!
