### ISSUE TITLE
tsnet documentation is out of date

### ISSUE THREAD

**Issue by ptxmac** [tailscale/tailscale#11823]
### What is the issue?

The documentation hosted on https://tailscale.com/kb/1244/tsnet does not match the latest generated docs: https://pkg.go.dev/tailscale.com/tsnet. 

Some fields have been renamed, others added.

### Steps to reproduce

Try the various samples on the tailscale.com site, not all of them compile.

**Comment by kelivel** [comment]
Created internal issue for team tracking: http://go/www/5476
