### ISSUE TITLE
Cannot add ACL grants for kubernetes operator via gitops-pusher

### ISSUE THREAD

**Issue by rfc1459** [tailscale/tailscale#11835]
### What is the issue?

When trying to push via gitops-pusher an ACL that contains a grant for the k8s operator, the API rejects the new ACL with the error `capability name must not be in the tailscale.com domain`. As a result, the ACL modification is rejected and the GitHub action fails.

### Steps to reproduce

Create an ACL file containing the following grants and then push it using gitops-pusher:
```jsonc
{
  "grants": [
    // Allow members of sysadmins group to act as admin on k8s clusters
    {
      "src": ["group:sysadmins"],
      "dst": ["tag:k8s-operator"],
      "app": {
        "tailscale.com/app/kubernetes": [{
          "impersonate": {
            "groups": ["system:masters"],
          },
        }],
      },
    },
  ],
}
```

### Other software

GitHub Action tailscale/gitops-acl-action@v1

**Comment by kelivel** [comment]
Hi @rfc1459! Looks like there's a typo in your ACL file: 

>  "tailscale.com/app/kubernetes"

`app` should be `cap`.

Try replacing that URL with `"tailscale.com/cap/kubernetes"` instead to see if that clears up the issues you're seeing.

**Comment by rfc1459** [comment]
Thanks for spotting this _very embarrassing_ case of PEBKAC on my end (the error message from the API led me astray), fixing the typo solved the issue.
