### ISSUE TITLE
"last seen" show as always online in dark mode

### ISSUE THREAD

**Issue by rxbynerd** [tailscale/tailscale#11841]
### What is the issue?

Whilst viewing the Tailscale UI in dark mode, the connection statuses show as green, despite the machines being disconnected from the tailnet:

<img width="1164" alt="Screenshot 2024-04-23 at 09 13 23" src="https://github.com/tailscale/tailscale/assets/816243/e970ca36-c959-4a2c-908c-64d5253dfb1d">

In light mode, machines are indicated as disconnected with a grey dot instead of green:
 
![IMG_0111](https://github.com/tailscale/tailscale/assets/816243/3a72d686-abbe-43b5-8e30-895c98eca640)

To assist in fixing this issue, the HTML for indicating a disconnected machine states grey under normal/light, but green under dark mode: `bg-gray-300 dark:bg-green-400`

<img width="716" alt="Screenshot 2024-04-23 at 09 33 53" src="https://github.com/tailscale/tailscale/assets/816243/2d2c582f-2005-4579-9353-918317517acd">

---

Thank you for implementing dark mode, it's a very welcome change.

Related to #2634.

### Steps to reproduce

1. Configure system preferences to dark mode
2. Open Tailscale in Chrome with a disconnected machine

### Are there any recent changes that introduced the issue?

N/A.

### OS

macOS

### OS version

macOS 14.4.1 (23E224)

### Tailscale version

login.tailscale.com

**Comment by rosszurowski** [comment]
Whoops! Looks like dark mode slipped out a bit before it was ready. Thanks for the thorough report, we'll get this fixed!

**Comment by rosszurowski** [comment]
Fix just went in, should go out shortly. I also added you to the feature flag @rxbynerd! Let us know if you spot anything else funky.
