### ISSUE TITLE
windows: "route subnets" unchecked for some users?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1184]
A user in the forum reported that subnets weren't working on Windows, but only on some Windows machines.
 
I noted that their "Route subnets" option was unchecked in the debug menu (for which you need to hold shift and right click the tray icon) on one of their machines.

They reported that indeed, it was off, and that checked it fixed it. But oddly, they didn't even know about the debug menu until I'd explained how to show it.

So how did it get unchecked for them in the first place?

Are we losing or zeroing that setting incorrectly somewhere?

/cc @peske @alexbrainman

**Comment by alexbrainman** [comment]
Two crazy ideas.

1. tailscale command changed it - see:

```
cmd/tailscale/cli/up.go:201:    prefs.RouteAll = upArgs.acceptRoutes
```

2. We had problem with corrupted pref file. Perhaps setting got corrupted.

Alex

**Comment by bradfitz** [comment]
I just re-audited the win/ui/ui.go and ipn.Prefs code for (2), but it all looks fine, as do corruption fixes in 1.2.x.

But (1) is definitely possible. I consider that the leading theory.

**Comment by bohannin** [comment]
FYI, this is the only Windows machine I had used the CLI on.

**Comment by bradfitz** [comment]
@bohannin, and did you use `tailscale up`, or just `tailscale status`?

**Comment by bohannin** [comment]
Likely did both.

**Comment by DentonGentry** [comment]
I just used `tailscale down` and `tailscale up` on a Windows 10 system running Tailscale 1.10, without impacting the accept routes setting. The saving of preferences from the tailscale command was substantially revamped in 1.8.

I'm going to close this as I think it got addressed along the way. Please feel free to reopen if it happens again.
