### ISSUE TITLE
Windows DNS leak. Client not working for custom domain

### ISSUE THREAD

**Issue by PR4SAN** [tailscale/tailscale#11847]
### What is the issue?

So I have an Ubuntu server running immich container on [192.168.0.30](https://192.168.0.30/) which I can access locally.
I have set up Tailscale + Cloudflare DNS + Nginx proxy manager so I can access the immich dashboard with the custom domain name.
I can access the Immich dashboard on all my devices with tailscale IP(100.XX.XX.XX) after connecting to the client app.
Now the problem is I am only able to access the immich dashboard with a custom domain([photos.xyz.com](https://photos.xyz.com/)) from all devices when I am connected to the client except the Windows PC. Even though I am connected to the client app on my PC custom domain doesn't work. I have checked firewall tailscale is allowed. i even checked with a different Windows laptop same issue.

Also nslookup from mac returns tailscale IP where nslookup from windows returns cloudflare DNS which is set up in my router.

- dark mode image mac where both tailscale IP and custom domain works after connected to client
- light mode windows PC where custom domain doesn't work

![Merged_document (1)](https://github.com/tailscale/tailscale/assets/20751006/61b3b6ef-6d29-465b-8ff4-d01e5af390e0)

![Screenshot 2024-04-23 184648](https://github.com/tailscale/tailscale/assets/20751006/1a25f39a-1979-4b96-a41a-9ba2e9776c0a)

<img width="1790" alt="Screenshot 2024-04-23 at 18 49 50" src="https://github.com/tailscale/tailscale/assets/20751006/fc5d6660-11c5-4af0-9c67-50e8d9596396">

### Steps to reproduce

mentioned above in issue section.

### OS

Windows

### OS version

 Microsoft Windows 11 Pro | 10.0.22631 N/A Build 22631

### Tailscale version

1.64.2

**Comment by willnorris** [comment]
What is the DNS record for `photos.xyz.com` ?  If it's a CNAME to your Tailscale magicdns hostname, that won't work on Windows (or Android) due to how their network stack handle the NXDOMAIN response.  More details here: https://github.com/tailscale/tailscale/issues/7650

If that's the case, you should probably be able to change it to an A record of your actual Tailscale IP address and have it work.

**Comment by PR4SAN** [comment]
Yes in Cloudflare I was pointing CNAME to Tailscale magicdns hostname. It worked after I deleted CNAME and created A record.

**Comment by willnorris** [comment]
awesome, that's great to hear it's working for you now.
