### ISSUE TITLE
Exit Node doesn't work

### ISSUE THREAD

**Issue by marcinjahn** [tailscale/tailscale#11848]
### What is the issue?

I have two machines in my tailnet:
- Fedora 39 PC
- iPhone

I enabled my Fedora PC as an Exit Node (set on the client itself, and confirmed in the Admin Panel). When I select my Fedora PC as an exit node on my iPhone, I am no longer able to browse the internet. Every trial to load webpages via Safari ends up with an error:

> Safari couldn't open the page because the server stopped responding.

My PC has internet connection obviously.

### OS

Linux, iOS

### OS version

Fedora 39, iOS 17.4.1

### Tailscale version

1.64.0

### Bug report

BUG-e75df7e9a917df61bd3b4c6244e8924e06db465d45115a81747489e4fae37b8c-20240423152254Z-64c3cd3ada6512d8

**Comment by kelivel** [comment]
Hi @marcinjahn, while setting up your exit node did you [enable IP forwarding](https://tailscale.com/kb/1103/exit-nodes?tab=linux#step-2-advertise-a-device-as-an-exit-node)? I was able to set up an exit node a few moments ago and connect with my iPhone successfully, so it doesn't seem to be a widespread issue at least. If IP forwarding doesn't help, I'd suggest reaching out to our Support team at http://www.tailscale.com/support who can help sort out configuration issues.

**Comment by marcinjahn** [comment]
Of course you're right, I forgot to do that. Closing, thanks!
