### ISSUE TITLE
Can't "sign in with other"

### ISSUE THREAD

**Issue by P1ck0rz** [tailscale/tailscale#11846]
I tried to sign in on android 14 with other account, and Tailscale just hangs. (The wheel goes round and round, but nothing happens). I'm using a Samsung Z Flip 3 5G.

**Comment by agottardo** [comment]
This is likely fixed now. Please try installing the [beta version](https://play.google.com/apps/testing/com.tailscale.ipn) of the app. If you don't want to install the beta, you'll need to wait for the 1.66 update to be released later this month. Thanks!
