### ISSUE TITLE
K8S operator fails without IPV6

### ISSUE THREAD

**Issue by disconn3ct** [tailscale/tailscale#11860]
If ipv6 is disabled, the sysctler container errors out: `sysctl: error: 'net.ipv6/conf/all/forwarding' is an unknown key`

https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/manifests/proxy.yaml#L20

**Comment by irbekrm** [comment]
I guess your Kubernetes nodes don't have the IPv6 kernel module at all.
Could you verify that by running `sysctl -a | grep ipv6` on the node?
Out of interest, what Kubernetes distribution/what OS is this?

**Comment by disconn3ct** [comment]
Home lab, made of RPI 4 under K3S. IPV6 is explicitly disabled in the kernel commandline.

**Comment by irbekrm** [comment]
I don't have a VM at hand with IPv6 module compiled out to test, but I believe https://github.com/tailscale/tailscale/pull/11867 should fix this

**Comment by irbekrm** [comment]
#11867 has been merged and should fix this, I've also cut a new dev release (chart version "1.65.117", app version "unstable-v1.65.117) with this change. Let us know if it fixes your issue

**Comment by disconn3ct** [comment]
Where is that chart version hosted?

**Comment by disconn3ct** [comment]
Where is that new chart hosted? Alternately, how do I tell the stable chart which image to use? I'm not finding it in https://github.com/tailscale/tailscale/blob/main/k8s-operator/api.md

**Comment by irbekrm** [comment]
Thanks for confirming @disconn3ct !
We will release a stable (1.66) chart that includes the fix soon
