### ISSUE TITLE
Can't log out or in: fetch control key: Get "https://controlplane.tailscale.com/key?v=90": context deadline exceeded

### ISSUE THREAD

**Issue by torarnv** [tailscale/tailscale#11873]
### What is the issue?

❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale logout                                                                                                                                  13s
2024/04/25 19:09:21 500 Internal Server Error: fetch control key: Get "https://controlplane.tailscale.com/key?v=90": context deadline exceeded

### Are there any recent changes that introduced the issue?

Upgraded Tailscale

### OS

macOS

### Tailscale version

1.64.0

### Bug report

BUG-63601a056145aba07eae2b269b666e8c5bbea5309f98e682d8788e89ca774659-20240425171018Z-445a90adb06cd65a

**Comment by agottardo** [comment]
`500 Internal Server Error: fetch control key: Get "https://controlplane.tailscale.com/key?v=90": context deadline exceeded` indicates that Tailscale cannot reach the control server. Do you have any security tools, firewall, web filter running on your machine? Is this a work computer? Is your router a Fortinet FortiGate?

**Comment by torarnv** [comment]
Things worked again after I changed to a different network, so there might have been some temporary problem with the initial network, like you described. Let's close this bug, but would be nice if the Tailscale UI would give some indication of what the problem is. As it was now, the UI told me I was both logged out, and that I could not log out, and that I also needed to reauth :)

**Comment by agottardo** [comment]
> would be nice if the Tailscale UI would give some indication of what the problem is

We're working on detailed warnings about connectivity issues as we speak :)
