### ISSUE TITLE
Kubernetes Operator throws TLS error

### ISSUE THREAD

**Issue by fritterhoff** [tailscale/tailscale#11880]
### What is the issue?

We're using the tailscale operator to access the api-plane of our k8s cluster. The function was working several weeks pretty fine until the let's encrypt cert expired. Now, renewing the cert fails obviously and some strange errors are thrown by the operator:

```

2024/04/26 04:50:48 http: TLS handshake error from 100.85.16.20:60035: 500 Internal Server Error: your Tailscale account does not support getting TLS certs
2024/04/26 04:50:49 http: TLS handshake error from 100.85.16.20:60030: 500 Internal Server Error: your Tailscale account does not support getting TLS certs
```

### OS

Linux

### OS version

Kubernetes

### Tailscale version

tailscale/k8s-operator:v1.64.2

**Comment by Rumbles** [comment]
Turn it on in the DNS tab:

https://tailscale.com/kb/1153/enabling-https

**Comment by fritterhoff** [comment]
It is enabled: 
![image](https://github.com/tailscale/tailscale/assets/32478819/c78b217b-6280-4452-a93b-9aa3b0ab2ebe)

**Comment by Rumbles** [comment]
read the docs I linked to

**Comment by fritterhoff** [comment]
Ah the relevant issue was the missing MagicDNS setting...
