### ISSUE TITLE
NextDNS dns over https request do not use mullvad exit node

### ISSUE THREAD

**Issue by wowowowuk** [tailscale/tailscale#11900]
### What is the issue?

When using NextDNS via tailscale and a mullvad exit node, the dns over https requests to NextDNS do not go via the mullvad exit node but direct from the client. Therefore NextDNS records the real ip as the source of the dns requests. This would seem counterintuitive to using a privacy vpn service such as mullvad. 

Is this by design? I would expect the https requests to NextDNS to use the mullvad exit node along with all other traffic. 

### Steps to reproduce

Tested in iOS. 
1 Use mullvad exit node and NextDNS
2 Set NextDNS to log source IP and observe real IP being logged. 
3 Monitor iOS traffic using wireshark and observe connections to NextDNS outside the mullvad tunnel. 

### Are there any recent changes that introduced the issue?

No

### OS

iOS

### OS version

17.4.1

### Tailscale version

1.64.0

### Other software

None

**Comment by vantech14** [comment]
Same issue here, the DNS requests are encrypted by NextDNS but you'd expect them to leave the device via the tunnel and then on to NextDNS.

**Comment by cblinq** [comment]
Same issue happening with Control D. I do not think it is by design, because if you use a Wireguard config alongside NextDNS profile (on iOS) the requests come from Mullvad Exit node and not your client.

**Comment by nickkhyl** [comment]
@wowowowuk, @vantech14, @cblinq: can you please edit (or create) the [nodeAttrs](https://tailscale.com/kb/1337/acl-syntax#node-attributes-nodeattrs) section in the policy file to apply the `user-dial-routes` attribute, and see if that resolves the issue?
```
"nodeAttrs": [
    {
        "target": ["*"],
        "attr":   ["user-dial-routes"],
    },
],
```

**Comment by cblinq** [comment]
@nickkhyl this works! But I had to assign the user-dial-routes attribute to every device connected to Mullvad. It this the expected way? Or is your snippet supposed to force it to every device? Because that way did not work for me.

**Comment by vantech14** [comment]
@nickkhyl i am using the TestFlight TS app and the routing of DNS seems to be working without this fix. When I connect to TS my DNS goes via Mullvad.

On a different device, with the standard TS app for iPhone, the DNS works as expected even without this fix. 

Strange as previously, it didn't work. If you need any further testing please let me know.

**Comment by sefidel** [comment]
FWIW I'm using TF build of Tailscale iOS (1.71.74) and it didn't work out of the box.

Applying `user-dial-routes` to `*` seems to fix the issue.

**Comment by cblinq** [comment]
> @nickkhyl this works! But I had to assign the user-dial-routes attribute to every device connected to Mullvad. It this the expected way? Or is your snippet supposed to force it to every device? Because that way did not work for me.

@sefidel there's an extra comma at the end of attr of [*], that's why it didn't work for me.

Here's my nodeAttrs:

```
	"nodeAttrs": [
		{"target": ["*"], "attr": ["user-dial-routes"]},
		{"target": ["device1"], "attr": ["mullvad"]},
		{"target": ["device2"], "attr": ["mullvad"]},
		{"target": ["device3"], "attr": ["mullvad"]},
		{"target": ["device4"], "attr": ["mullvad"]},
	],
```
This way works for me. I previously had a user-dial-routes for every device because the code snippet provided by nickkhyl didn't work,  but this seems to work.

**Comment by sefidel** [comment]
I got it working again after restarting the client several times, looks like something went wrong when I rapidly switched between exit nodes to see if it worked on my personal exit nodes.
