### ISSUE TITLE
FR: Mullvad availability for Brazil

### ISSUE THREAD

**Issue by Vassopoli** [tailscale/tailscale#11904]
### What are you trying to do?

Join Mullvad VPN service

### How should we solve this?

Add availability for Brazil. I see on Mullvad's site there are 4 [Mullvad servers in Brazil](https://mullvad.net/en/servers).

### What is the impact of not solving this?

Brazilian users cannot register

**Comment by gabrielrinaldi** [comment]
I would also want support for Brazil as part of our workforce works from there.

**Comment by plenusredemptio** [comment]
Bump

**Comment by borgesip** [comment]
Bump
