### ISSUE TITLE
FR: Mullvad availability for Israel

### ISSUE THREAD

**Issue by gadd1** [tailscale/tailscale#11902]
### What are you trying to do?

Join Mullvad VPN service 

### How should we solve this?

Add availability for Israel. I see on Mullvad's site there is no limit and can register. there are also Mullvad servers in Israel.

### What is the impact of not solving this?

Israeli users cannot register

**Comment by bradfitz** [comment]
Work is still underway on this, but this is a dup of https://github.com/tailscale/tailscale/issues/9314. We'll post updates on that issue as we expand the list of countries where you can purchase the Tailscale/Mullvad add-on.
