### ISSUE TITLE
QNAP Setup Working - but with a issue with facetime call

### ISSUE THREAD

**Issue by traian658** [tailscale/tailscale#11927]
### What is the issue?

I have successfully set up Tailscale on my QNAP, and all traffic is being routed through the exit node, as confirmed by the new IP address. However, while WhatsApp functions correctly using this connection, FaceTime does not work. This issue persists across all my devices, including Apple TV, MacBook Pro, and iPhone 15. What could be the problem?

### Steps to reproduce

Steps to reproduce:

Connect Tailscale on a QNAP device in Qatar with the location tunnel set to Romania.
Test the connection on Apple TV, MacBook, and iPhone 15.
Observe the issue where the devices behave as if they are not connected to the VPN, indicating that the connection may not be secure.

### Are there any recent changes that introduced the issue?

I'm new to the service and noticed is not working. If i make my mac an exit node and my mac connected to other vpn server is functioning. 

### OS

macOS

### Tailscale version

14.4.1 

### Other software

Used apple tv, macbook pro 14.4.1 , iphone 15 latest OS

**Comment by kelivel** [comment]
Hi @traian658, can you generate a [bug report](https://tailscale.com/kb/1227/bug-report/) immediately after FaceTime fails to connect and paste that BUG marker here?

**Comment by traian658** [comment]
BUG-31e50536efb2cba3e337d10837374eee547bb40462dd55b74cc6c1fd878dc18f-20240502174935Z-a8a8cc301a21684d

**Comment by kelivel** [comment]
We've tested extensively with FaceTime and we can't reproduce this. If you're still able to reproduce this on a recent Tailscale version and on iOS 18, please grab a new bugreport and create a new issue.
