### ISSUE TITLE
Tailscale creates hosts entries multiple times on Windows

### ISSUE THREAD

**Issue by junglivre** [tailscale/tailscale#11939]
### What is the issue?

I often edit my hosts file to access my websites locally, and I've noticed that, whenever a new device is added to my account, or the client is updated, it will recreate the hosts entries corresponding to the devices on my tailnet.

And this issue is pretty annoying since it messes up with my hosts file.

### Steps to reproduce

Add a new device to the tailnet.

### Are there any recent changes that introduced the issue?

Unknown.

### OS

Windows

### OS version

Windows 10 - Build 19045.4046.

### Tailscale version

1.64.2, but the issue also happened on previous versions.

### Other software

Not related.

**Comment by junglivre** [comment]
P.S.: Also happens when I put any entry below the Tailscale ones and restart the Tailscale app

![2024-04-30_15-27](https://github.com/tailscale/tailscale/assets/58450254/1371a0b5-a96e-4978-948d-71ecec18ad8e)

**Comment by junglivre** [comment]
Any news on this? still happening on latest updates....

**Comment by junglivre** [comment]
Still happening.

**Comment by dblohm7** [comment]
@junglivre what is that GUI program you're using to edit your hosts file?

**Comment by junglivre** [comment]
@dblohm7 Microsoft PowerToys' Hosts File Editor
