### ISSUE TITLE
Tests with different srcPostureAttrs conflict

### ISSUE THREAD

**Issue by halfninja** [tailscale/tailscale#11940]
### What is the issue?

I have started using a srcPosture in an ACL. I've tried to write two tests, one with passing srcPostureAttrs and one with insufficient attributes.

Individually, each test passes. However when both tests are present, one test fails ("want: Accept, got: Drop").

### Steps to reproduce

```
// ACL with posture tests.
{
	"postures": {
		"posture:recentStable": [
			"node:tsReleaseTrack == 'stable'",
			"node:tsVersion >= '1.60'",
		],
	},

	"acls": [
		{
			"action": "accept",
			"src":    ["autogroup:member"],
			"dst":    ["autogroup:self:*"],
		},
		{
			"action":     "accept",
			"src":        ["autogroup:member"],
			"srcPosture": ["posture:recentStable"],
			"dst": [
				"autogroup:internet:*",
			],
		},
	],

        // ** THESE TESTS FAIL UNLESS EITHER IS COMMENTED OUT **
	"tests": [
		{
			"src": "xyz@live.warwick.ac.uk",
			"srcPostureAttrs": {
				"node:tsReleaseTrack": "stable",
				"node:tsVersion":      "1.61",
			},
			"accept": [
				"40.0.0.1:443",
			],
			"deny": [
				"10.0.0.1:443",
			],
		},

		// outdated client
		{
			"src": "xyz@live.warwick.ac.uk",
			"srcPostureAttrs": {
				"node:tsReleaseTrack": "stable",
				"node:tsVersion":      "1.59",
			},
			"deny": [
				"10.0.0.1:443",
				"40.0.0.1:443",
			],
		},
	],
}
```

### OS

Other

### Tailscale version

1.64.0

### Bug report

BUG-9051aba81056c6eca2f21923d10420bb3935f032c837cea2dad0bab4d5a84cf1-20240430185407Z-d8e93bc2092f9df5

**Comment by icio** [comment]
Thanks for reporting this, @halfninja. It looks like when multiple tests have the same `src`, the last observed `srcPostureAtts` is being used in all test cases (even if omitted). We'll get working on a fix for this.

**Comment by halfninja** [comment]
Confirmed I can save both tests together now, thanks for the fix!
