### ISSUE TITLE
Identity provider support for Duo

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1197]
Tracking bug for adding Duo (https://duo.com/) as an identity provider for Tailscale, as requested by some users.

**Comment by DentonGentry** [comment]
Noting: https://duo.com/docs/oauthapi

At the time of this writing, OIDC is not supported.

**Comment by DentonGentry** [comment]
Noting: Duo 2FA can be part of a login flow with Okta or Azure Active Directory, which then communicates the authentication decision to Tailscale.

**Comment by giezi** [comment]
Duo is now supporting OIDC:
https://duo.com/docs/oauthapi

It would be awesome if you can add the support for Duo :)

**Comment by skizzerz** [comment]
I was able to set this up using Tailscale’s Custom OIDC feature in conjunction with [Duo SSO](https://duo.com/docs/sso). Seems to work well so far, although I did need to make my own Webfinder endpoint as Duo doesn’t provide one.

**Comment by catzkorn** [comment]
Closing this issue - using Duo as an identity provider is now supported via [custom OIDC](https://tailscale.com/kb/1240/sso-custom-oidc/)
