### ISSUE TITLE
Sign in using Google Workspace doesn't identify admin

### ISSUE THREAD

**Issue by tailaiw** [tailscale/tailscale#11982]
### What is the issue?

I was trying to sign in using my company's Google Workspace. I have a super admin role in the workspace, but after I signed in I got the following page. I let another admin try and she got the same. We don't have the same issue with our GitHub sign-in or Microsoft sign-in, but Google workspace is the one we really want to use.

<img width="456" alt="image" src="https://github.com/tailscale/tailscale/assets/29800495/e846839d-a26a-48fe-a0a2-bd74214887de">

### Steps to reproduce

Signed up using our Google Workspace email (an admin user) and went to https://login.tailscale.com/admin

### OS

macOS

**Comment by kelivel** [comment]
Hi @tailaiw, the individual who creates the tailnet initially by signing in to Tailscale is assigned the tailnet Owner role (and administrator) by default, and users without an admin role can't log into the admin console. These roles are specific to Tailscale and aren't inherited from your identity provider.

I took a quick look at our records and your org's tailnet was created a few years ago, so the Owner role has already been assigned to someone else. Drop a line with our Support team at http://www.tailscale.com/support and the team can help identify the right person at your organization who can transfer ownership or assign admin permissions to your account.
