### ISSUE TITLE
Link github from tailscale.com

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#12]
https://tailscale.com/ should have a link to this GitHub repo somewhere.

Header? Footer? Get Started?

I have no strong opinions.

Anybody? @dfcarney @apenwarr @danderson @crawshaw

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687028005949) by [Unito](https://www.unito.io/learn-more)

**Comment by rosszurowski** [comment]
Our Github account is linked in the [blog header](https://tailscale.com/blog/) and [footer](https://tailscale.com/) across the site. So I think we're good here.

**Comment by bradfitz** [comment]
Cool, closing.
