### ISSUE TITLE
IPv6 NAT table missing in nftables mode (regression in 1.64)

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#12008]
### What is the issue?

IPv6 NAT table no longer gets created for Linux hosts that support IPv6 running in tun mode with netfilter in nftables mode since 1.64.

One possible side effect (user reported) is that routing to IPv6 targets via exit nodes in tun mode is broken.

### Steps to reproduce

Set up a Tailscale client (in the example, running in a container so no pre-existing tables) with firewall in nftables mode, observe that the nat table for ip6 is missing altogether:
<details>
<code>
/ # nft list ruleset
table ip filter {
        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                counter packets 0 bytes 0 jump ts-forward
        }

        chain INPUT {
                type filter hook input priority filter; policy accept;
                counter packets 99 bytes 23734 jump ts-input
        }

        chain ts-forward {
                iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept
                oifname "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop
                oifname "tailscale0*" counter packets 0 bytes 0 accept
        }

        chain ts-input {
                iifname "lo*" ip saddr 100.110.115.23 counter packets 0 bytes 0 accept
                iifname != "tailscale0*" ip saddr 100.115.92.0/23 counter packets 0 bytes 0 return
                iifname != "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop
                iifname "tailscale0*" counter packets 0 bytes 0 accept
                udp dport 41943 counter packets 46 bytes 3312 accept
        }
}
table ip6 filter {
        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                counter packets 0 bytes 0 jump ts-forward
        }

        chain INPUT {
                type filter hook input priority filter; policy accept;
                counter packets 215 bytes 2784089 jump ts-input
        }

        chain ts-forward {
                iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept
                oifname "tailscale0*" counter packets 0 bytes 0 accept
        }

        chain ts-input {
                iifname "lo*" ip6 saddr fd7a:115c:a1e0::df01:7317 counter packets 0 bytes 0 accept
                iifname "tailscale0*" counter packets 0 bytes 0 accept
                udp dport 49489 counter packets 43 bytes 3956 accept
        }
}
table ip nat {
        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                counter packets 58 bytes 7426 jump ts-postrouting
        }

        chain ts-postrouting {
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 masquerade
        }
}
</code>
</details>
For comparison, on a 1.62 Linux node:
<details>
<code>
/ # nft list ruleset
table ip filter {
        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                counter packets 0 bytes 0 jump ts-forward
        }

        chain INPUT {
                type filter hook input priority filter; policy accept;
                counter packets 89 bytes 22796 jump ts-input
        }

        chain ts-forward {
                iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept
                oifname "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop
                oifname "tailscale0*" counter packets 0 bytes 0 accept
        }

        chain ts-input {
                iifname "lo*" ip saddr 100.110.115.23 counter packets 0 bytes 0 accept
                iifname != "tailscale0*" ip saddr 100.115.92.0/23 counter packets 0 bytes 0 return
                iifname != "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop
                iifname "tailscale0*" counter packets 0 bytes 0 accept
                udp dport 35163 counter packets 43 bytes 3096 accept
        }
}
table ip6 filter {
        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                counter packets 0 bytes 0 jump ts-forward
        }

        chain INPUT {
                type filter hook input priority filter; policy accept;
                counter packets 199 bytes 2782509 jump ts-input
        }

        chain ts-forward {
                iifname "tailscale0*" counter packets 0 bytes 0 meta mark set meta mark & 0xffff04ff | 0x00000400
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 accept
                oifname "tailscale0*" counter packets 0 bytes 0 accept
        }

        chain ts-input {
                iifname "lo*" ip6 saddr fd7a:115c:a1e0::df01:7317 counter packets 0 bytes 0 accept
                iifname "tailscale0*" counter packets 0 bytes 0 accept
                udp dport 56475 counter packets 40 bytes 3680 accept
        }
}
table ip nat {
        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                counter packets 53 bytes 7021 jump ts-postrouting
        }

        chain ts-postrouting {
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 masquerade
        }
}
table ip6 nat {
        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                counter packets 23 bytes 2023 jump ts-postrouting
        }

        chain ts-postrouting {
                meta mark & 0x0000ff00 == 0x00000400 counter packets 0 bytes 0 masquerade
        }
}
</code>
</details>

### Are there any recent changes that introduced the issue?

This will have been introduced in https://github.com/tailscale/tailscale/pull/11546, specifically [here](https://github.com/tailscale/tailscale/commit/5fb721d4ada3dc96fc35bceff63747178a65cc0a#diff-a3bcbcd1ca198799f4f768dc56fea913e1945a6b3ec9dbec89325a84a19a85e7R570-R623) - I removed setting of `nftables.v6NatAvailable` field in favour of a new method (that was introduced to fix another issue), but we actually still use it in some places directly, i.e [here](https://github.com/tailscale/tailscale/blob/release-branch/1.64/util/linuxfw/nftables_runner.go#L828)

We should remove the field and the direct references altogether (see https://github.com/tailscale/tailscale/pull/11353 where we remove logic for the separate IPv6 NAT availability check for nftables)

We should also add tests that can catch issues like this.

### Tailscale version

1.64.0

**Comment by gitlankford** [comment]
at first read I was wondering if they just moved to INET family instead of IP family, but I guess not.

**Comment by irbekrm** [comment]
No, for nftables we need to explicitly create tables, it's missing because we skipped creating it.
Should be fixed in #12009

**Comment by irbekrm** [comment]
Fixed in #12009
