### ISSUE TITLE
wgengine/router: make IPv6 work in macOS tailscaled

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#1201]
**Describe the bug**
I compiled latest tailscale/tailscaled command line from source under MacOS. Version info is as follow:
```
1.3.306
  tailscale commit: a98538f84a9850c52351876bc73ecfe01b041d4e
  go version: go1.15.6
```
Run `tailscaled` and `tailscale up` from command line, then login from Google. Everything looks fine, tailscaled doesn't print any error message. But the tun interface doesn't have IP address and I can't ping anywhere. 
```
$ifconfig utun8
utun8: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1280
```

```
$ip route show
default via 192.168.2.1 dev en0
10.37.129.0/24 dev vnic1  scope link
10.211.55.0/24 dev vnic0  scope link
127.0.0.0/8 via 127.0.0.1 dev lo0
127.0.0.1/32 via 127.0.0.1 dev lo0
169.254.0.0/16 dev en0  scope link
224.0.0.0/4 dev en0  scope link
255.255.255.255/32 dev en0  scope link
```
`sudo ./tailscale status -json` output looks fine to me. BackendState is Running. All the peers are there. My tailscale IP is 100.83.74.57. If needed I can paste the full output.

**To Reproduce**
1. `sudo ./tailscaled -state t.state -cleanup`
2. `sudo ./tailscaled -state t.state -tun utun8`
3. `sudo ./tailscale up`
4.  Login through Google

**Expected behavior**
utun8 interface has IP address assigned; `ip route show` has 100.x.x.x routes; can ping hosts in my network.

**Screenshots**

**Version information:**
 - Device: [mac mini]
 - OS: [MacOS]
 - OS version: [Catalina 10.15.7]
 - Tailscale version: [1.3.306  tailscale commit: a98538f84a9850c52351876bc73ecfe01b041d4e]

**Additional context**
Previously I use 1.2.4 from App Store, which worked fine.

**Comment by bradfitz** [comment]
@mkramlich, can you reproduce?

**Comment by mkramlich** [comment]
reproduced. yes this is a new problem. I'l bisect

**Comment by mkramlich** [comment]
confirmed here its good/expected in v1.2.3. bad by a98538f. bisecting for tne culprit commit...

**Comment by mkramlich** [comment]
found it

good last: 03a039d4 Dec 19 danderson "go.mod: bump wireguard-go version"

bad first: ca676ea6 Dec 19 danderson: "tailcfg: introduce map version 8, for clients that support v6 node config"

I'll dig in...

@danderson

**Comment by bradfitz** [comment]
Oh, that makes sense. The wgengine/router implementation needs to be updated to be taught about IPv6 addresses on macOS.

**Comment by mkramlich** [comment]
thats consistent with my guess. only thing commit does is bump the tailcfg version to 8. that version mentions routes. and in "ifconfig" the routes appear to no longer have been set on my utun8 entry. were in the prior, last good, commit. so, either serverside not sending the routes down to it. or, it is but the mac node drops the ball. not compared logs yet

**Comment by danderson** [comment]
Yup, this is my fault. I forgot that we have a non-IPNExtension version of the macos router code, which needs updating to correctly handle IPv6 configuration. I can take it if you want, or leave it to you @mkramlich.

**Comment by bradfitz** [comment]
> only thing commit does is bump the tailcfg version to 8. 

.... which causes the server to send IPv6 addresses down, because the client is advertising it's capable of it.

**Comment by mkramlich** [comment]
@bradfitz sounds reasonable. except, in my Mac node's tailscale netcheck, it says "IPv6: no". also says no in the central web admin panel entry for it

@danderson if you want it fixed ASAP maybe you or Brad should do it. however I'd love to take a shot, give me more familiarity with the. I had been spelunking thru those parts of the code back in August when I fixed a Mac routing delete bug, which was also triggered somewhere under the wgengine userspace/router reconfig call graph. (in fact, this gives me flashbacks. thankfully not like in Apocalyose Now.) also, this kinda sorta blocks my #177 Homebrew anyway

**Comment by danderson** [comment]
I'm happy to leave it to you, if you want to give it a shot. Until we ship Tailscale on Homebrew, the "run on macOS yourself" support is not terribly well supported anyway, so it makes sense to work on that as part of getting Homebrew working.

What you see in netcheck's reports is a report about the "underlay" network, i.e. the network conditions that we have to work with in order to establish tunnels between peers. The IPv6 problem here is on the "overlay" network, i.e. the tailscale interface itself. As of that mapversion, the control plane tells Tailscale clients to configure IPv6 addresses on the overlay network in addition to IPv4, and that works regardless of whether IPv6 is usable at the underlay level (we can forward overlay IPv6 traffic over an IPv4 tunnel connection).

**Comment by mkramlich** [comment]
@danderson ah, great info, helps clarify. thx

I'll take a shot. looking at the offending code regions now. I'll try to have a fix candidate up in the next day or three. if I give up I'll say so here, or just ask for tips

**Comment by mkramlich** [comment]
found a specific flaw in the code which is the proximate cause. there may be 3+ breaking flaws, some of which are eclipsed in my testing at moment, but 1 I have confirmed would cause what we're seeing

I'll test a candidate fix/upgrade this afternoon

**Comment by mkramlich** [comment]
FIXED it on my box. I think. rough. next I'll cleanup and test and ensure I do the right way. will PR once ready

**Comment by awsong** [comment]
@mkramlich your fix wasn't merged right? I didn't see it in git log. But yesterday I found my Mac version worked again after pulling the latest and recompile.

**Comment by mkramlich** [comment]
correct. I'm still polishing up a clean fix to deliver up for Mac. I believe Brad said they were turning off something server-side temporarily (related to the IPv6 rollout) as a quick shotgun fix for folks.

we'll update here once my Mac fix is ready and you can pick it up.
