### ISSUE TITLE
Machine name edit does not reflect in ios devices.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1202]
When you edit the admin panel's machine name,  for example, change it from desktop-utu4gh to desktop-VM.

IOS devices still show the old auto-generated name.

![image](https://user-images.githubusercontent.com/75628398/105862647-078c6b00-5fbe-11eb-8d18-9233591e0056.png)

![image](https://user-images.githubusercontent.com/75628398/105862683-12470000-5fbe-11eb-8fe9-04d625e0330f.png)

Please refer to the machine with IP 100.89.88.88.

**Comment by soniaappasamy** [comment]
The fix for this is included in 1.4 (which we are in the process of releasing)
