### ISSUE TITLE
FR: Add quick settings toggle to android app

### ISSUE THREAD

**Issue by MulverineX** [tailscale/tailscale#12065]
### What are you trying to do?

Toggle the Tailscale connection from the android quick settings menu, similarly to other VPN apps

### How should we solve this?

https://developer.android.com/develop/ui/views/quicksettings-tiles

### What is the impact of not solving this?

Having to find the app, open it, toggle on the connection, and switch back to what you were trying to do

**Comment by agottardo** [comment]
From https://tailscale.com/changelog:

> The Quick Settings tile has been temporarily disabled, pending resolution of an issue.

This PR will re-add it: https://github.com/tailscale/tailscale-android/pull/377
