### ISSUE TITLE
FR: Release Android APKs on Github

### ISSUE THREAD

**Issue by pjv** [tailscale/tailscale#12071]
### What are you trying to do?

I’d like to be able to install arbitrary versions of tailscale on Android without any intervening “App Store”. I use [obtanium](https://github.com/ImranR98/Obtainium) to manage installs of many open source projects on my Android devices and prefer that to alternatives like F-Droid. I will not install anything from the Google Play Store. 

Is there any objection to supplying tailscale-built APK’s on the [tailscale-android](https://github.com/tailscale/tailscale-android) repo?

### How should we solve this?

Set up the necessary github actions to build and deploy tailscale releases on the [tailscale-android](https://github.com/tailscale/tailscale-android) repo.

### What is the impact of not solving this?

Currently have to get tailscale from F-Droid where I am limited to whatever version they happen to be hosting. No betas. No older stuff. I also have to trust F-Droid.

**Comment by bradfitz** [comment]
Work is underway on this.

We avoided it in the past because we didn't want to manage the signing keys and manage APKs per-device and sign them all so we always used Google Play Store's signing service. But that meant we actually didn't have the signed APKs ourselves (or all 82 of them).

But @barnstar is working on this.

**Comment by pjv** [comment]
<img width="315" alt="SCR-20240509-irwj" src="https://github.com/tailscale/tailscale/assets/327716/8936f421-2714-4f59-9bdd-409baf7592cb">

**Comment by 18637** [comment]
Hi, Is there any movement on this. I also would like to download tailscale .apk without signing up to the play store. Cheers

**Comment by agottardo** [comment]
Unstable APKs are now available at https://pkgs.tailscale.com/unstable/#android. Stable releases will also follow once the next release (1.68) goes out.

**Comment by 18637** [comment]
Not that 1.68 is released does that mean there is a stable apk now? I couldn't find it in the release, so perhaps im looking in the wrong spot?

**Comment by agottardo** [comment]
It's coming. We are waiting for the Play Store to approve the release first.

**Comment by 18637** [comment]
Yep looking in the wrong spot. Thank you @agottardo !

**Comment by kinghat** [comment]
while there are apks provided for use outside of the play store now, why dont the stable releases have up to date apk builds for android on github or https://pkgs.tailscale.com/stable/#android?
