### ISSUE TITLE
After update to 1.66, docker containers cannot access Tailscale IPs

### ISSUE THREAD

**Issue by Zaelnorth** [tailscale/tailscale#12070]
### What is the issue?

Running Tailscale on the host, upgraded to 1.66 this morning. 

Right after the update, my Uptime Kuma Docker container stopped being able to ping my Tailscale IPs. I am able to ping them from the host without a problem, but not from the containers themselves (tried via container console etc). 

Interestingly enough, I can ping the host's Tailscale IP from containers without a problem, but not any other Tailscale IP elsewhere.

What to do?

### Are there any recent changes that introduced the issue?

Upgrade to 1.66

### OS

Linux

### OS version

Ubuntu 22.04.4

### Tailscale version

1.66

### Other software

Docker
Uptime Kuma

### Bug report

BUG-9d84fdefb594944f730cf924acfe7eeb840969eb879e03040299d486a9d800a8-20240509115120Z-6c1d2962b34ab51f

**Comment by geberl** [comment]
Saw a similar thing in my setup. Seems to be related to https://github.com/tailscale/tailscale/issues/12066

Workaroud (for me): `tailscale up --stateful-filtering=false`

**Comment by Zaelnorth** [comment]
Perfect @geberl that fixed it, thanks so much!

**Comment by knyar** [comment]
Looking at the bugreport attached to the issue, the node in question is using iptables (rather than nftables), so this appears to be unrelated to #12066.

@Zaelnorth, could you please share more details on how you expose Tailnet addresses to your Docker containers? Are you announcing container IP range into your tailnet as a subnet route? Do you configure SNAT on traffic going to tailscale0? If you could share the output of `iptables-save`, `ip rule` and `ip route show table all` that would be helpful too.

**Comment by aaronjrodrigues** [comment]
Just got this issue when updating, thank you @geberl for the workaround!

**Comment by Zaelnorth** [comment]
@knyar haven't adjusted anything with respect Tailnet/Docker, it just used to work.. Did not configure any SNAT stuff, that's beyond my paygrade... 

Please find attached the requested files

[ip_rule.txt](https://github.com/tailscale/tailscale/files/15263283/ip_rule.txt)
[iproute_show_tables.txt](https://github.com/tailscale/tailscale/files/15263285/iproute_show_tables.txt)
[iptables-save.txt](https://github.com/tailscale/tailscale/files/15263286/iptables-save.txt)

**Comment by fate8383** [comment]
tailscale up --stateful-filtering=false fixed it, thanks a lot!

**Comment by fritterhoff** [comment]
The changelog (https://tailscale.com/changelog#2024-05-08)  mentions the following:

> Note: This change can break existing setups that depend on forwarding connections from external hosts (internet, LAN, Docker containers, etc.) into the tailnet through a Tailscale node. If your setup depends on such forwarding, you can disable stateful filtering with the tailscale up --stateful-filtering=false command.

**Comment by litori** [comment]
Yep this broke my Caddy docker.  As of 1.66.1, still broken with stateful filtering.

**Comment by awly** [comment]
We added a release note warning retroactively. Sorry about the breakage!
When you disable stateful filtering, please also update your ACLs to restrict src IPs that are allowed to reach your nodes. See https://tailscale.com/security-bulletins#ts-2024-005 for more context.

Unfortunately, we will have to keep this new behavior. In 1.66.1 we added a health warning when you run `tailscale status` on a subnet router host that also has docker installed about this possible problem.

**Comment by litori** [comment]
> The changelog (https://tailscale.com/changelog#2024-05-08) mentions the following:
> 
> > Note: This change can break existing setups that depend on forwarding connections from external hosts (internet, LAN, Docker containers, etc.) into the tailnet through a Tailscale node. If your setup depends on such forwarding, you can disable stateful filtering with the tailscale up --stateful-filtering=false command.

This is actually false.  It breaks Docker container to Docker container forwarding as well.  I have a Caddy setup as a reverse proxy into different containers, none of them are on tailnet, and it straight up does not forward container to container.

**Comment by awly** [comment]
@litori that sounds strange. Stateful filtering shouldn't touch packets that are not going to `tailscale0`. Can you show the output of `iptables -L -v`?

**Comment by litori** [comment]
`Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
78894   81M ts-input   all  --  any    any     anywhere             anywhere
2670K  282M f2b-sshd   tcp  --  any    any     anywhere             anywhere             multiport dports ssh

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
24525   18M ts-forward  all  --  any    any     anywhere             anywhere
24503   18M DOCKER-USER  all  --  any    any     anywhere             anywhere
24503   18M DOCKER-ISOLATION-STAGE-1  all  --  any    any     anywhere             anywhere
10897 1439K ACCEPT     all  --  any    br-eed4f3f7923f  anywhere             anywhere             ctstate RELATED,ESTABLISHED
  476 22620 DOCKER     all  --  any    br-eed4f3f7923f  anywhere             anywhere
13130   17M ACCEPT     all  --  br-eed4f3f7923f !br-eed4f3f7923f  anywhere             anywhere
    0     0 ACCEPT     all  --  br-eed4f3f7923f br-eed4f3f7923f  anywhere             anywhere
 126K  144M ACCEPT     all  --  any    br-df464c1228c9  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    7  1232 DOCKER     all  --  any    br-df464c1228c9  anywhere             anywhere
 129K  150M ACCEPT     all  --  br-df464c1228c9 !br-df464c1228c9  anywhere             anywhere
    0     0 ACCEPT     all  --  br-df464c1228c9 br-df464c1228c9  anywhere             anywhere
  335 44564 ACCEPT     all  --  any    docker0  anywhere             anywhere             ctstate RELATED,ESTABLISHED
   69  3588 DOCKER     all  --  any    docker0  anywhere             anywhere
  333 23594 ACCEPT     all  --  docker0 !docker0  anywhere             anywhere
    0     0 ACCEPT     all  --  docker0 docker0  anywhere             anywhere

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (3 references)
 pkts bytes target     prot opt in     out     source               destination
    7  1232 ACCEPT     udp  --  !br-df464c1228c9 br-df464c1228c9  anywhere             172.20.0.2           udp dpt:51820
  237 11208 ACCEPT     tcp  --  !br-eed4f3f7923f br-eed4f3f7923f  anywhere             172.31.0.2           tcp dpt:https
    0     0 ACCEPT     udp  --  !br-eed4f3f7923f br-eed4f3f7923f  anywhere             172.31.0.2           udp dpt:https
  239 11412 ACCEPT     tcp  --  !br-eed4f3f7923f br-eed4f3f7923f  anywhere             172.31.0.2           tcp dpt:http

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
13130   17M DOCKER-ISOLATION-STAGE-2  all  --  br-eed4f3f7923f !br-eed4f3f7923f  anywhere             anywhere
 129K  150M DOCKER-ISOLATION-STAGE-2  all  --  br-df464c1228c9 !br-df464c1228c9  anywhere             anywhere
  333 23594 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  anywhere             anywhere
 240M  428G RETURN     all  --  any    any     anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (3 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  any    br-eed4f3f7923f  anywhere             anywhere
    0     0 DROP       all  --  any    br-df464c1228c9  anywhere             anywhere
    0     0 DROP       all  --  any    docker0  anywhere             anywhere
  83M   11G RETURN     all  --  any    any     anywhere             anywhere

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
 240M  428G RETURN     all  --  any    any     anywhere             anywhere

Chain f2b-sshd (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 REJECT     all  --  any    any     vps-0557d265.vps.ovh.ca  anywhere             reject-with icmp-port-unreachable
2568K  275M RETURN     all  --  any    any     anywhere             anywhere

Chain ts-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
   40  4300 MARK       all  --  tailscale0 any     anywhere             anywhere             MARK xset 0x40000/0xff0000
   40  4300 ACCEPT     all  --  any    any     anywhere             anywhere             mark match 0x40000/0xff0000
    0     0 DROP       all  --  any    tailscale0  100.64.0.0/10        anywhere
   40  2800 ACCEPT     all  --  any    tailscale0  anywhere             anywhere

Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     any     l2.snowy-monitor.ts.net  anywhere
    0     0 RETURN     all  --  !tailscale0 any     100.115.92.0/23      anywhere
    0     0 DROP       all  --  !tailscale0 any     100.64.0.0/10        anywhere
   14  1356 ACCEPT     all  --  tailscale0 any     anywhere             anywhere
    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:41641`

It is very simple to replicate.  Setup a docker container for nginx and another with caddy to forward to nginx and check that it works.  Spin up tailscale 1.66 and caddy will stop forwarding.

**Comment by awly** [comment]
@litori thanks. That looks like iptables without `--stateful-filtering`, which I assume you've disabled to make forwarding work.
Could you send a few other pieces of information:
* exact `docker` commands that reproduce your setup with caddy
* output of `iptables -L -v` with `--stateful-filtering=true`
* output of `tailscale version --daemon`
* the output of `tailscale bugreport`

**Comment by neilschelly** [comment]
I found another workaround that doesn't require disabling stateful-filtering.

```sudo iptables -I ts-forward 1 -i docker0 -d 100.64.0.0/10 -j MARK --set-xmark 0x40000/0xff0000```

*Longer explanation:*

Here's the ts-forward chain from nftables (`nft list ruleset`):
```
chain ts-forward {
        iifname "tailscale0" counter packets 0 bytes 0 meta mark set mark and 0xff00ffff xor 0x40000
        meta mark & 0x00ff0000 == 0x00040000 counter packets 0 bytes 0 accept
        oifname "tailscale0" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop
        oifname "tailscale0" ct state ! related,established counter packets 550 bytes 46102 drop
        oifname "tailscale0" counter packets 0 bytes 0 accept
}```

Packets from docker containers on the default docker bridge expect to NAT out to the internet using the docker0 as their default gateway. When the containers try to reach a 100.64.0.0/10 carrier-grade NAT IP, routing rules will atempt to send that traffic out the tailscale0 interface. They will match the 4th rule in this chain because they are attempting to route out the tailscale0 interface, and they are not part of a related/established connection state.

The first rule in this chain marks traffic to be accepted only if the incoming interface is tailscale0. The iptables command basically duplicates that mark line in the chain, but it marks any packets coming into the docker0 interface and destined for the carrier-grade NAT address space.

```sudo iptables -I ts-forward 1 -i docker0 -d 100.64.0.0/10 -j MARK --set-xmark 0x40000/0xff0000```

**Comment by neilschelly** [comment]
Another workaround, and maybe this is the actual bug really...

Here's the FORWARD chain from nftables (`nft list ruleset`):
```
chain FORWARD {
        type filter hook forward priority filter; policy drop;
        counter packets 2935 bytes 256404 jump ts-forward
        counter packets 13868 bytes 90667843 jump DOCKER-USER
        counter packets 13868 bytes 90667843 jump DOCKER-ISOLATION-STAGE-1
        oifname "docker0" ct state related,established counter packets 8321 bytes 90336047 accept
        oifname "docker0" counter packets 0 bytes 0 jump DOCKER
        iifname "docker0" oifname != "docker0" counter packets 5544 bytes 330944 accept
        iifname "docker0" oifname "docker0" counter packets 0 bytes 0 accept
}
```

The first rule in there (second line) just jumps all traffic to the `ts-forward` chain. That chain only really handles traffic coming from the tailscale0 interface. Traffic from anywhere else (like docker0) will just get dropped. That rule can be adjusted to only send traffic to ts-forward IF it comes from the tailscale0 interface since it doesn't seem that it's intended to handle traffic from other interfaces. I'm less familiar with how this might work on either exit nodes or nodes that are advertising routes and forwarding traffic to/from other interfaces.

This could be done with:
```
sudo iptables -D FORWARD 1
sudo iptables -I FORWARD 1 -i tailscale0 -j ts-forward
```
This would yield a FORWARD chain like:
```
chain FORWARD {
        type filter hook forward priority filter; policy drop;
        iifname "tailscale0" counter packets 0 bytes 0 jump ts-forward
        counter packets 0 bytes 0 jump DOCKER-USER
        counter packets 13868 bytes 90667843 jump DOCKER-ISOLATION-STAGE-1
        oifname "docker0" ct state related,established counter packets 8321 bytes 90336047 accept
        oifname "docker0" counter packets 0 bytes 0 jump DOCKER
        iifname "docker0" oifname != "docker0" counter packets 5544 bytes 330944 accept
        iifname "docker0" oifname "docker0" counter packets 0 bytes 0 accept
}
```

I didn't bother adjusting the IPv6 rules for this workaround because there are no IPv6 FORWARD rules for docker to interfere with.

**Comment by kaivol** [comment]
> We added a release note warning retroactively. Sorry about the breakage! When you disable stateful filtering, please also update your ACLs to restrict src IPs that are allowed to reach your nodes. See https://tailscale.com/security-bulletins#ts-2024-005 for more context.
> 
> Unfortunately, we will have to keep this new behavior. In 1.66.1 we added a health warning when you run `tailscale status` on a subnet router host that also has docker installed about this possible problem.

I had the same problem with `podman`, so you might consider adding a warning for `podman` users as well. 

Also, I'm not sure if I have correctly understood what the recommended approach is to make the host's `tailscale` connection available to `docker` or `podman` containers.
If I deactivate _stateful filtering_, how should I update my ACLs? 
I understood the [change log](https://tailscale.com/changelog#2024-05-08) to mean that the default `{"action": "accept", "src": ["*"], "dst": ["*:*"]}` as already secure.
Also, what exactly is the meaning of

> With this change, `*` expands to all [Tailscale IP addresses](https://tailscale.com/kb/1015/100.x-addresses) and all IP addresses from approved [subnet routes](https://tailscale.com/kb/1019/subnets).

Does _all Tailscale IP addresses_ refer to all addresses in the 100.64.0.0/10 subnet, or only to those actually in use by devices in my tailnet?

**Comment by mt104** [comment]
Same problem here. I'm running Tailscale in a Linux VM on Proxmox (not that the VM or Proxmox should be relevant?) with IP forwarding turned on. My router has a static route for my Tailscale network pointing at the VM so that other devices on my LAN can access my Tailscale network without needing to be nodes themselves. Until  I updated to 1.66.1 today this worked fine. Not sure what version I was on before. With 1.66.1 I need to use the --statefule-filtering=false workaround.

**Comment by masterwishx** [comment]
Same issue on Ubuntu servers after update

**Comment by masterwishx** [comment]
`tailscale set --stateful-filtering=false` fixed the issue for me

**Comment by masterwishx** [comment]
but seems Magis DNS host names still cant be accesses ony ips working after the fix

**Comment by neilschelly** [comment]
> > This could be done with:
> > ```
> > sudo iptables -D FORWARD 1
> > sudo iptables -I FORWARD 1 -i tailscale0 -j ts-forward
> > ```
> 
> is this can fix also host names not reachable?

It sounds like you are conflating too problems at the same time. If you want to resolve MagicDNS names from inside a container, you'll want to be using 100.100.100.100 as your DNS resolver inside the container. That can be done several ways. For example, the docker daemon can default to duplicating your workstation's DNS resolution settings inside the containers.

The problem being discussed in this issue is that your containers won't be able to reach 100.100.100.100 for MagicDNS resolution or any other 100.64/10 addresses for anything else in your tailnet.

**Comment by masterwishx** [comment]
> > > This could be done with:
> > > ```
> > > sudo iptables -D FORWARD 1
> > > sudo iptables -I FORWARD 1 -i tailscale0 -j ts-forward
> > > ```
> > 
> > 
> > is this can fix also host names not reachable?
> 
> It sounds like you are conflating too problems at the same time. If you want to resolve MagicDNS names from inside a container, you'll want to be using 100.100.100.100 as your DNS resolver inside the container. That can be done several ways. For example, the docker daemon can default to duplicating your workstation's DNS resolution settings inside the containers.
> 
> The problem being discussed in this issue is that your containers won't be able to reach 100.100.100.100 for MagicDNS resolution or any other 100.64/10 addresses for anything else in your tailnet.

So this fix only ip's without ` --stateful-filtering=false`?

**Comment by awly** [comment]
@masterwishx 
For problems with DNS resolution from within containers, please see https://github.com/tailscale/tailscale/issues/12108.
For problems with reaching tailnet IPs other than 100.100.100.100 from containers or other LAN hosts, this is the right issue.
And yes, for DNS problems the current recommendation is to use `--stateful-filtering=false` for now. We are thinking about potential fixes or alternatives.

> Same problem here. I'm running Tailscale in a Linux VM on Proxmox (not that the VM or Proxmox should be relevant?) with IP forwarding turned on. My router has a static route for my Tailscale network pointing at the VM so that other devices on my LAN can access my Tailscale network without needing to be nodes themselves. Until I updated to 1.66.1 today this worked fine. Not sure what version I was on before. With 1.66.1 I need to use the --statefule-filtering=false workaround.

@mt104 your setup sounds exactly like the attack we were fixing with stateful filtering and https://tailscale.com/security-bulletins#ts-2024-005 :)
If you understand the risks and wish to keep using this configuration, running with `--steateful-filtering=false` is the way to do it.

**Comment by masterwishx** [comment]
I'm using headscale 100.64.0.0/16 by default
Also found in one node Ubuntu 22.04 in portainer I can reach other node by Magic DNS host name. But from this other node where Ubuntu 20.4 Magic DNS hostnames not working. But I set everywhere `--stateful-filtering=false`

**Comment by mt104** [comment]
> @mt104 your setup sounds exactly like the attack we were fixing with stateful filtering and https://tailscale.com/security-bulletins#ts-2024-005 :) If you understand the risks and wish to keep using this configuration, running with `--steateful-filtering=false` is the way to do it.

I'm the only person with access to any of the nodes and any of the LANs involved, so I'm happy with the risk. Thanks for mentioning it though, and I did go read the bulletin.

**Comment by masterwishx** [comment]
> @masterwishx For problems with DNS resolution from within containers, please see #12108. For problems with reaching tailnet IPs other than 100.100.100.100 from containers or other LAN hosts, this is the right issue. And yes, for DNS problems the current recommendation is to use `--stateful-filtering=false` for now. We are thinking about potential fixes or alternatives.
> 
> > Same problem here. I'm running Tailscale in a Linux VM on Proxmox (not that the VM or Proxmox should be relevant?) with IP forwarding turned on. My router has a static route for my Tailscale network pointing at the VM so that other devices on my LAN can access my Tailscale network without needing to be nodes themselves. Until I updated to 1.66.1 today this worked fine. Not sure what version I was on before. With 1.66.1 I need to use the --statefule-filtering=false workaround.
> 
> @mt104 your setup sounds exactly like the attack we were fixing with stateful filtering and https://tailscale.com/security-bulletins#ts-2024-005 :) If you understand the risks and wish to keep using this configuration, running with `--steateful-filtering=false` is the way to do it.

@awly `--stateful-filtering=false` fixed issue in docker for ips but not for Magic DNS host names (nodes) ,
using headscale in docker and tailscale clients on Ubuntu servers + Unraid with plugin.
in ubuntu have  `resolv.conf`:  
`nameserver 127.0.0.53
search vcn0xxxxxx.oraclevcn.com 
masterwishx.headscale.mysite.net`

**Comment by awly** [comment]
@masterwishx thanks. Could you please report DNS-related issues to https://github.com/tailscale/tailscale/issues/12108 and include:
* where tailscale is installed (host/container/both)
* which domain name is failing to resolve, from where, and with what error message

**Comment by martinjgrunwald** [comment]
On the same VM where my Tailscale client runs there is a portainer instance. After adding `--accept-routes` I can't reach the Portainer Web UI on that VM. Adding `--stateful-filtering=false` does not change this behaviour either, only running the `tailscale -up` command without `--accept-routes` lets me access the UI again

**Comment by awly** [comment]
@martinjgrunwald that sounds like a different issue (connectivity to the container, not from the container).
Could you open a new issue and specify:
* the IP of Portainer Web UI you're trying to reach
* the subnet routes configured in your tailnet
* what error are you getting (timeout or connection denied)
