### ISSUE TITLE
docker image version (almost never) is synced with all other updated platforms

### ISSUE THREAD

**Issue by fate8383** [tailscale/tailscale#12073]
### What is the issue?

docker image is not synced with all other updated platforms, it is still on 1.64.2 with red upgrade flag due to vulnerability next to my node in the tail scale manage page but i cannot, image for 1.66 is not there.

### OS

Linux

### Other software

linux, using docker image tail scale

**Comment by nickoneill** [comment]
Hi @fate8383, we typically wait a few days before pushing out container updates. If you can't mitigate the issue via the details in the post, we should have an unstable docker image that will contain the fix sometime out sometime today.

**Comment by fate8383** [comment]
> Hi @fate8383, we typically wait a few days before pushing out container updates. If you can't mitigate the issue via the details in the post, we should have an unstable docker image that will contain the fix sometime out sometime today.

I understand, perfectly fine to wait for any other update, but this one is pushed as vulnerability security update, I would expect that it is updated on all platforms at the same time. I cannot use any other way of upgrading so I have to wait for docker image. Thanks

**Comment by dhermes** [comment]
@nickoneill We're in the same boat. (We use https://registry.terraform.io/modules/hardfinhq/tailscale-subnet-router/aws/latest to manage our subnet routers, so we need a Docker image.)

Any updates here?

**Comment by tinazhouhui** [comment]
Looks like new version 1.66.3 was just released 🙌 https://github.com/tailscale/tailscale/pkgs/container/tailscale/216702756?tag=v1.66.3

**Comment by nickoneill** [comment]
Thanks for waiting folks, we wanted to make sure a few items were resolved for containers before pushing the latest release

**Comment by johanneskastl** [comment]
As I am falling into the same trap, please allow a related question:

Is a there a RSS feed for the package releases, like there is for "normal" releases?
`https://github.com/tailscale/tailscale/releases.atom`

That way I could follow that and get notified when new packages/images are released...
