### ISSUE TITLE
FR: SSH into Kubernetes containers

### ISSUE THREAD

**Issue by ruhatch** [tailscale/tailscale#12085]
### What are you trying to do?

I have a console interface to a Java application that is running on Kubernetes. I want my operations users to be able to access the console container via Tailscale SSH, so that they don't need any local setup other than Tailscale. Is this possible with the current kubernetes operator/tailscale ssh implementation?

### How should we solve this?

I'd like to be able to add an annotation to a kubernetes service that points to a container with kubernetes installed, which will then proxy SSH traffic to that container.

### What is the impact of not solving this?

Right now I'll need to either install some Java files locally or install kubectl and AWS credentials whenever I need to setup an ops user

**Comment by irbekrm** [comment]
Hi, if you can `kubectl exec` to your running `Pod`s then you can use the operator's API server proxy and `kubectl exec` over that https://tailscale.com/kb/1236/kubernetes-operator#accessing-the-kubernetes-control-plane-using-an-api-server-proxy.

That also gives you the ability to map your tailnet identities to Kubernetes roles.

**Comment by ruhatch** [comment]
That works perfectly, thanks for pointing me towards that resource!
