### ISSUE TITLE
v1.66.x breaks MagicDNS without --stateful-filtering=false

### ISSUE THREAD

**Issue by icebladerage** [tailscale/tailscale#12087]
### What is the issue?

Upgrading to 1.66.x causes Tailscale to stop controlling DNS without setting stateful-filtering to false.

The endpoint in question does not function as a subnet router or exit node. Docker is not installed.

As soon as tailscale upgrades, this is logged:

May  9 23:53:21 machine tailscaled[223811]: health("overall"): error: router: adding [-o tailscale0 -m conntrack ! --ctstate ESTABLISHED,RELATED -j DROP] in filter/ts-forward: running [/usr/sbin/iptables -t filter -I ts-forward 4 -o tailscale0 -m conntrack ! --ctstate ESTABLISHED,RELATED -j DROP --wait]: exit status 2: iptables v1.8.7 (nf_tables): Couldn't load match `conntrack':No such file or directory

This does not occur in 1.64.0. In order for this to work in 1.66.x, tailscale needs the stateful-filtering=false flag set.

### Steps to reproduce

Upgrade tailscale to 1.66 or 1.66.1

### OS

Linux

### OS version

PopOS 22.04

### Tailscale version

1.64.0-1.66.x

**Comment by masterwishx** [comment]
I have same issue on Ubuntu servers , the tailscale set `--stateful-filtering=false` fixed the issue for me only for ips, but not for nodes host names .

**Comment by awly** [comment]
@icebladerage it appears that your host does not have conntrack installed, which is typically present on most Linux systems these days.
Can you try `sudo apt install conntrack` and see if that allows `tailscale set --stateful-filtering=true` to work?

**Comment by icebladerage** [comment]
Installed and set. So far so good. If I get time, I will install a blank popos and see if that is a default, as I cannot' recall ever messing with that on this install.

**Comment by awly** [comment]
Thanks for confirming! Please reopen this issue if you find that a fresh install has the same problem. We currently assume that conntrack is installed by default in most distros.

**Comment by Rongronggg9** [comment]
> We currently assume that conntrack is installed by default in most distros.

Instead of assuming this, should the packages distributed by Tailscale depend on/recommend `conntrack`?

```
Package: tailscale
Version: 1.66.4
Priority: extra
Section: net
Maintainer: Tailscale Inc <info@tailscale.com>
Installed-Size: 50.6 MB
Depends: iptables
Recommends: tailscale-archive-keyring (>= 1.35.181), iproute2
Conflicts: tailscale-relay
Replaces: tailscale-relay
Homepage: https://www.tailscale.com
Download-Size: 27.3 MB
APT-Manual-Installed: yes
APT-Sources: https://pkgs.tailscale.com/stable/debian bookworm/main amd64 Packages
Description: The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO
```
