### ISSUE TITLE
Ignore zerotier interfaces when collecting endpoints

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1208]
ZeroTier is another popular mesh networking system, so it's not uncommon for people to have both ZT and Tailscale installed at once to evaluate both. Currently, this results in a lot of badness happening, because Tailscale and ZT can pick each other's tunnels as the best path between two nodes, resulting in hilarious amounts of traffic amplification and non-connectivity.

To break the cycle, we should skip ZT interfaces when collecting local endpoints for NAT traversal, so that we never select ZT as a datapath for Tailscale traffic. On Linux at least, ZT interfaces have a distinctive naming pattern that we can match on. I expect/hope we can do the same on Windows and non-IPNExtension macOS.

cc @bradfitz

**Comment by danderson** [comment]
Older zerotier used zt0, zt1 etc. Newer versions use `zt<deterministic hash of network ID>`. Based on that, our filter should just be strings.HasPrefix(iface, "zt").

**Comment by bradfitz** [comment]
Per https://github.com/zerotier/ZeroTierOne/issues/892, on Windows it contains "ZeroTier", so adding that too.
