### ISSUE TITLE
taildrive: writes do not arrive on a writeable mount

### ISSUE THREAD

**Issue by pitust** [tailscale/tailscale#12097]
### What is the issue?

When writing to files in taildrive (davfs 1.7.0-2, tailscale 1.66.1) the writes do not ever appear on the remote. 

### Steps to reproduce

1. Share a folder with taildrive
2. Mount the folder with `sudo mount -t davfs  -o uid=1000,gid=1000 http://100.100.100.100:8080 /mnt/taildrive`
3. Create a file with nonempty contents, e.g. `echo hi > /mnt/taildrive/<path>/foo`
4. Observe that these writes do not propagate to the remote although the file itself is created.
5. After some time, observe the file contents disappearing with an error: `taildrive: access: PUT from [hFhH/] to [UQBjF]: status-code=412 ext="unknown" content-type="unknown" content-length=20 tx=5 rx=0 err=""`

The entire mechanism in general seems to love traveling back in time, although it is unclear if it is truly tailscale's fault.

Directly writing with -X PUT does appear to work, however; this seems to be tied to the WebDAV `If` header which is not handler correctly on the server.

### OS

Linux

### OS version

ArchLinux

### Tailscale version

1.66.1

### Other software

davfs 1.7.0-2

### Bug report

BUG-fd8a885f0f6ff803bba155080ca2e2a87503df9e2374760caf3cbe1cebc6792c-20240510210525Z-6bc6c5b062227591

**Comment by agottardo** [comment]
cc @oxtoacart

**Comment by oxtoacart** [comment]
I'm not able to reproduce this on the HEAD of `main`. @pitust I see that your client is Linux with davfs2. What platform is your server running on?

**Comment by pitust** [comment]
@oxtoacart Synology; Tailscale 1.66.0. I can confirm in pcaps that the client acquires a lock and then correctly sends it over peerapi, but the write fails on the remote end with "precondition failed".

**Comment by oxtoacart** [comment]
@pitust Ahh, sounds like there might be some goofiness with locks. Out of curiosity, if you set `use_locks 0` in your `davfs2.conf`, does the problem go away?

**Comment by pitust** [comment]
@oxtoacart Yes, setting `use_locks 0` in davfs2.conf does resolve the issue (although this is not an ideal solution for obvious reasons).

**Comment by oxtoacart** [comment]
@pitust This should be resolved on [unstable](https://pkgs.tailscale.com/unstable/) now. Please let me know if it works for you.
