### ISSUE TITLE
When regaining network connectivity, tailscale-relay has to be restarted to get connection to mesh

### ISSUE THREAD

**Issue by jhaygood86** [tailscale/tailscale#121]
**Describe the bug**
When changing networks or losing and regaining network connectivity, i.e., moving from home to work, changing access points, etc.., tailscale-relay loses connectivity to all mesh nodes until the service is restarted (with systemctl restart tailscale-relay for instance)

**To Reproduce**
1. Connect to mesh network on a laptop
3. Test mesh network, i.e., via ping hello.ipn.dev
2. Lose and regain network connectivity
3. Test mesh network again, i.e., via ping hello.ipn.dev
4. No connectivity

**Expected behavior**
Connectivity should be regained automatically

**Version information:**
 - Device: Dell Inspiron XPS 7590
 - OS: Fedora Workstation 31
 - OS version: Fedora Workstation 31, Linux kernel 5.5.6-201.fc31.x86_64
 - Tailscale version: tailscale-relay-0.94-236.x86_64

**Additional context**
This happens very reliably.

**Comment by crawshaw** [comment]
cc @danderson

**Comment by danderson** [comment]
Known issue with relaynode. We've addressed it from multiple angles in tailscaled, so I think this is going to be fixed by the upcoming release.

I'm not sure how we track "this is not fixed in released versions yet", so I'm going to close this, since that's what we've been doing so far.
