### ISSUE TITLE
FR: Machine Online Indicator on mobile apps

### ISSUE THREAD

**Issue by pigeon-msngr** [tailscale/tailscale#12106]
### What are you trying to do?

To see if a machine is online, I need to login into web interface and switch to desktop mode just to see if machine is online. This makes process of knowing if system is online way too long.

### How should we solve this?

by giving system online/offline indicators on mobile clients itself.

### What is the impact of not solving this?

Long road to be taken just to see if system is online

**Comment by agottardo** [comment]
It's not clear what platform you're using. The online status indicator has been available on iOS for the past 10 months; we just shipped it on Android in version v1.66.0 (and is currently being rolled out).
