### ISSUE TITLE
Tailscale >= 1.66.0 breaks DNS name resolution in Docker containers on Linux

### ISSUE THREAD

**Issue by ferrarimarco** [tailscale/tailscale#12108]
### What is the issue?

After upgrading to Tailscale `1.66.0` or `1.66.1`, DNS name resolution breaks inside newly created Docker containers.

I'm experiencing this on a Debian 11 host.

This doesn't occur on the same machine with Tailscale 1.64.0

Thanks for your support!

### Steps to reproduce

1. Install Tailscale 1.64.0 on the Linux machine: `apt install tailscale=1.64.0`
2. Start a Docker container: `docker run --rm -it debian:12`
3. Ping an external service from inside the container: `ping google.com` -> WORKS
4. Stop the Docker containr: `exit`
5. Install Tailscale 1.66.0 or 1.66.1 on the Linux machine: `apt install tailscale=1.66.1`
6. Start a Docker container: `docker run --rm -it debian:12`
7. Ping an external service from inside the container: `ping google.com` -> Cannot resolve name

### Are there any recent changes that introduced the issue?

Upgrade Tailscale from 1.64.0 to 1.66.1 using the system package manager.

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.66.1

### Other software

Docker version 26.1.2, build 211e74b

### Bug report

BUG-c7f85e39b9c72709e39b2f333de28e65a0d5875a2e351ab851dae9f245cea271-20240512175341Z-c93cbe3beb3e255b

**Comment by awly** [comment]
1.66 added stateful filtering for packets going via the `tailscale0` interface, see https://tailscale.com/changelog#2024-05-08. But that should not affect packets from docker containers to the Internet.

Another notable thing is that this node is also a subnet router for the `10.0.0.0/8` range. Again, this should not affect docker containers, but noting it for others reading the issue.

Some things to check are:
* check whether `tailscale set --stateful-filtering=false` on 1.66.1 resolves the issue
* check if your docker configuration uses CGNAT IPs (in the 100.64.0.0/10 range) by chance? You can run something like this to view the config for all docker networks:
  ```sh
  docker network ls --format '{{.Name}}' | xargs docker network inspect
  ```

**Comment by chennin** [comment]
In the container, what does `getent hosts google.com` print, on both versions?

I also ran in to this, in my case my _tailnet_ address resolved to ipv6, but the container did not have an ipv6 address.  One way to solve it is by [enabling ipv6 for the container](https://docs.docker.com/config/daemon/ipv6/)

**Comment by danielrusco** [comment]
I had the same issue, which showed up as Service Widgets from my [Homepage](https://gethomepage.dev/latest/) instance not connecting to their source (e.g. Proxmox, Jellyfin, etc). 

The problem was solved by running `tailscale up --stateful-filtering=false` on my host machine.

**Comment by miroslavbucek** [comment]
I had the same problem which he solved:
`tailscale set --stateful-filtering=false`

You owe me a good night's sleep :-(

**Comment by ylbeethoven** [comment]
+1 

`--stateful-filtering=false` solve the problem

**Comment by masterwishx** [comment]
i have same issue but for Magic DNS host names . 
`tailscale set --stateful-filtering=false`  fixed issue with ips but not for node host names

**Comment by ferrarimarco** [comment]
> 1.66 added stateful filtering for packets going via the `tailscale0` interface, see https://tailscale.com/changelog#2024-05-08. But that should not affect packets from docker containers to the Internet.
> 
> Another notable thing is that this node is also a subnet router for the `10.0.0.0/8` range. Again, this should not affect docker containers, but noting it for others reading the issue.

Correct, it's a subnet router for that range

> 
> Some things to check are:
> 
> * check whether `tailscale set --stateful-filtering=false` on 1.66.1 resolves the issue

It works if I update to 1.66.1, and disable stateful filtering, for both internal and external names. So, stateful filtering is likely interfering with this?

> * check if your docker configuration uses CGNAT IPs (in the 100.64.0.0/10 range) by chance? You can run something like this to view the config for all docker networks:
>   ```shell
>   docker network ls --format '{{.Name}}' | xargs docker network inspect
>   ```

I checked, and it doesn't appear to be the case. That range is not in use by any network that Docker creates.

> In the container, what does `getent hosts google.com` print, on both versions?

Tailscale 1.64.0: `2a00:1450:4002:402::200e google.com`
Tailscale 1.66.1 (before disabling stateful filtering): Timeout
Tailscale 1.66.1 (after disabling stateful filtering): `2a00:1450:4002:411::200e google.com`

Thanks for your support!

**Comment by ferrarimarco** [comment]
From the https://tailscale.com/security-bulletins#ts-2024-005 page:

> The attack only works on a LAN because:

> * it relies on next-hop routing, which only works in a LAN
> * **destination IPs are in the subnet router's approved range**, or in the [CGNAT range](https://tailscale.com/kb/1015/100.x-addresses) 100.64.0.0/10, which are not routable over the Internet.

This appears to be the case because both the resolvers I'm using are in the 10.0.0.0/8 range. Additionally, one of those (10.0.0.2) runs in a container.

> On Linux packet-forwarding nodes we added stateful packet filtering. This means that these nodes keep track of forwarded connections and only allow return packets for existing outbound connections. Inbound packets that don't belong to an existing connection are dropped.

And from https://tailscale.com/kb/1080/cli:

> `--stateful-filtering` Enable stateful filtering for subnet routers and exit nodes. When enabled, inbound packets with another node's destination IP are dropped, unless they are a part of a tracked outbound connection from that node. Defaults to enabled, but can be disabled for site-to-site networking use cases.

This doesn't appear to work as intended, at least in this case?

**Comment by awly** [comment]
Thanks for the details, I reproduced the issue.
Right now, `tailscale set --stateful-filtering=false` is the only workaround. Running it on a regular node (not exit node and not subnet router) should be safe.

The reason this happens is because Docker will by default use `resolv.conf` from the host, which points at 100.100.100.100 (served by local tailscaled) as the nameserver. Since this IP lands in the `tailscale0` interface, DNS request packets become subject to stateful filtering. And because the source IP is not localhost, but something like `172.17.0.2` (from the docker network range), it's interpreted as "incoming request from another host" and thus rejected.

**Comment by blueskea** [comment]
> I had the same problem which he solved: `tailscale set --stateful-filtering=false`
> 
> You owe me a good night's sleep :-(

Thanks, and no need to restart tailscale

**Comment by blueskea** [comment]
> I had the same problem which he solved: `tailscale set --stateful-filtering=false`
> 
> You owe me a good night's sleep :-(

Thanks, and no need to restart tailscale and docker.

**Comment by ErebusBat** [comment]
Dropping an updated command from what was posted above (https://github.com/tailscale/tailscale/issues/12108#issuecomment-2107156997) to view docker network names / IP ranges if you have [jqlang/jq](https://github.com/jqlang/jq) installed:

```shell
docker network ls --format '{{.Name}}' | xargs docker network inspect | jq '.[] | [.Name, .IPAM.Config]'
```

![Cursor_and_zsh](https://github.com/tailscale/tailscale/assets/93973/2b125f80-c248-444d-93a5-02ace2c2db2c)

**Comment by masterwishx** [comment]
@awly for me MagicDns nodes names still not not working in docker  in Unraid and one Ubuntu 20.4 client, other Ubuntu 22.4 client working fine. 3th Ubuntu 22.4 still don't have docker installed. 
Using headscale + 3 Ubuntu servers + unraid server with plugin. But dns is OK also full MagicDns nodes name are working.
host.user.headscale.mysite.com

**Comment by awly** [comment]
@masterwishx just to clarify:
* resolving full names, like `host.headscale.mysite.com` works
* resolving short names, like `host` does not work

If that's correct, that sounds like a different issue.
Can you show the contents of `/etc/resolv.conf` on the hosts that servers that don't work, and those that do work?

**Comment by masterwishx** [comment]
> @masterwishx just to clarify:
> 
> * resolving full names, like `host.headscale.mysite.com` works
> * resolving short names, like `host` does not work
> 
> If that's correct, that sounds like a different issue. Can you show the contents of `/etc/resolv.conf` on the hosts that servers that don't work, and those that do work?

Yes all right ,maybe i should open another issue for it , in previous version of tailscale all works fine
short host NOT works:

`instance-mysite-cloud`   Ubuntu 20.04.6 LTS
`/etc/resolv.conf`
`nameserver 127.0.0.53
search vcn02152127.oraclevcn.com masterwishx.headscale.mysite.com`

`unraidhost:2375`
![image](https://github.com/tailscale/tailscale/assets/28630321/20ba5b94-883e-44a9-9a48-6a34200793e1)

![image](https://github.com/tailscale/tailscale/assets/28630321/83b3c5b4-453b-400c-82b9-9bca0e217137)

![image](https://github.com/tailscale/tailscale/assets/28630321/39d88d20-b2a0-448b-95dd-dd497f3cdca1)

![image](https://github.com/tailscale/tailscale/assets/28630321/db4846f3-0427-4e3b-b4da-ae6e4d317951)


When using ip instead its fine : 

![image](https://github.com/tailscale/tailscale/assets/28630321/0dd662d7-8f56-434d-8617-5eb360616322)

<br>
<br>

`instance-mysite-cloud2`   Ubuntu 22.04.4 LTS
`/etc/resolv.conf`

`nameserver 127.0.0.53
options edns0 trust-ad
search masterwishx.headscale.mysite.com vcn12281520.oraclevcn.com`

http://instance-mysite-cloud:9768 for s3 backup in portainer working fine 

<br>
<br>

`nasname` Unraid 6.12.10
`# Generated by rc.inet1
nameserver 9.9.9.9
nameserver 149.112.112.112
nameserver 192.168.0.1`

![image](https://github.com/tailscale/tailscale/assets/28630321/60153a90-dc60-4614-9e28-bdea3424bc53)
![image](https://github.com/tailscale/tailscale/assets/28630321/0ddb711e-52ab-4e2d-9fe7-3081fb65a9a4)

**Comment by masterwishx** [comment]
Fixed in Ubuntu by :
`tailscale set - - accept-dns=false` then
`tailscale set - - accept-dns`
In Unraid it's not helped

**Comment by masterwishx** [comment]
> Fixed in Ubuntu by : `tailscale set - - accept-dns=false` then `tailscale set - - accept-dns` In Unraid it's not helped

Forgot to mention that also tryed to make Adguard home as dns in docker then goes back to local dns. So was also reload dns/stundns for resolve.conf

**Comment by awly** [comment]
1.66.4 is available and disables stateful filtering by default.
We discussed doing more clever things, like detecting container runtimes and allowlisting their interfaces in our iptables/nftables rules, but that gets pretty hairy. Instead, @maisem pointed out that other mitigations for https://tailscale.com/security-bulletins#ts-2024-005 cover most cases except for `autogroup:danger-all`, so stateful filtering is not strictly required except for that case.

If you run 1.66.0-1.66.3, you still need to manually disable stateful filtering with `tailscale set --stateful-filtering=false`.
If you install a brand new 1.66.4, or upgrade from 1.64 or older versions, stateful filtering will be off by default.

**Comment by ferrarimarco** [comment]
Thanks for the update!

**Comment by derpda** [comment]
I still experience this problem on Arch Linux. The update to 1.66.4-2 did NOT fix this for me, but setting `tailscale set --stateful-filtering=false` did. Maybe this setting is not reliably applied when updating (possibly distro dependent)?

**Comment by awly** [comment]
@derpda the default change only applies to new installs. When you update from 1.66.3 (or older) to 1.66.4, the `--stateful-filtering` value has already been set and does not revert to the new default. For existing installs that update to 1.66.4 running `tailscale set --stateful-filtering=false` is indeed the solution.

**Comment by Boerny41** [comment]
How do I set stateful filtering to false when tailscale runs inside a container?

**Comment by awly** [comment]
@Boerny41 if you start a brand new tailscale instance inside of the container, stateful filtering is false by default.
If you have an existing instance, you can run `tailscale set --stateful-filtering=false` inside of the container.

**Comment by reuben** [comment]
How/where should I run `tailscale set --stateful-filtering=false` when using the K8s operator?

**Comment by irbekrm** [comment]
> How/where should I run tailscale set --stateful-filtering=false when using the K8s operator?

We disable stateful filtering by default in the operator egress proxies. We haven't seen a need to disable it for the other proxy types. Have you ran into issues with that?

**Comment by reuben** [comment]
I'm exposing a service using the K8s operator by using the `tailscale.com/expose` annotation. Then, on a different machine, connected to the same Tailnet using tailscaled managed by systemd, I'm trying to connect to the service from inside a Docker container. On the machine I've already done `tailscale set --stateful-filtering=false`, but inside Docker containers there I still get `[Errno -2] Name or service not known`

**Comment by reuben** [comment]
In the host:

```
❯ cat /etc/resolv.conf
# Generated by NetworkManager
search fritz.box
nameserver 127.0.0.53
```

In the container:

```
# cat /etc/resolv.conf
nameserver 192.168.178.1
search fritz.box tailbde2.ts.net
```

**Comment by awly** [comment]
@reuben stateful filtering only applies on the machine where requests originate from - in this case that's the host running the docker container and not the k8s service or operator.
Something else is likely misconfigured on your host running the docker container.

Could you please open a new issue?

**Comment by reuben** [comment]
@awly yea I think I was conflating issues, the DNS resolution issues are intermittent and seem unrelated to this. Thanks for the help.

**Comment by mukhtarkv** [comment]
Assuming you are running containers within a host that is added to tailnet and you would like to use magic dns lookup of host machine, then you can reference the following docker compose file. I recently had a problem where I wanted to call host machine on tailnet but couldn't use magic dns lookup because docker containers are run in different network_mode and do not use host dns lookup by default. As a bonus I am showing you how to use inter container communication.
```
services:
  container_using_magic_dns:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host # if you want to communicate with other containers, 
                       # you have to use localhost and expose port on different container
    environment:
      URL: 'http://localhost:1234' # you would provide 'different_container:5678' 
                            # with default network_mode

  different_container:
    image: image:tag
    ports:
      - 1234:5678
```

**Comment by Radiergummi** [comment]
what if I'm running a Swarm mode cluster though, and rely on the network mode *not* being host networking, but the swarm mesh instead..?

**Comment by Radiergummi** [comment]
While I don't fully understand why yet, adding an additional resolve configuration to my `/etc/systemd/resolved.conf` seemingly fixes the issue:
```ini
[Resolve]
DNS=100.100.100.100
Domains=your-tailnet-name.ts.net
```

**Comment by gabrielelucci** [comment]
Hello. Just wanted to add to this thread that I was able to reproduce the issue while using Mullvad VPN as an exit node, even with stateful filtering set to false. 

Docker containers can't resolve DNS, but if I disable Mullvad as the exit node, it works normally.

**Comment by mukhtarkv** [comment]
> While I don't fully understand why yet, adding an additional resolve configuration to my `/etc/systemd/resolved.conf` seemingly fixes the issue:
> 
> [Resolve]
> DNS=100.100.100.100
> Domains=your-tailnet-name.ts.net

Hi @Radiergummi . Where you able to use magic dns name? I got it to work only when I use `my_device_name.my-tailnet-name.ts.net`
```
services:
  container_using_magic_dns:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 100.100.100.100 # Tailscale MagicDNS resolver
    dns_search:
      - my-tailnet-name.ts.net
    environment:
      remote_tailscale_host: my_device_name.my-tailnet-name.ts.net # with network_mode: host you don't need to append my-tailnet-name.ts.net
```

UPDATE: you don't need dns and dns_search if you provide full host name.
```
services:
  container_using_magic_dns:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      remote_tailscale_host: my_device_name.my-tailnet-name.ts.net # with network_mode: host you don't need to append my-tailnet-name.ts.net
```

**Comment by speedrapide10** [comment]
I think setting a custom DNS for Docker containers will be much more secure and safer
https://dev.to/darnahsan/set-custom-dns-for-docker-to-use-2h9c

Please correct me if I'm wrong, but it did fix the issue for me without tinkering or impacting current Tailscale settings.
