### ISSUE TITLE
[Android] Auto connectting

### ISSUE THREAD

**Issue by CrazyWolf13** [tailscale/tailscale#12104]
### What is the issue?

Hi
Since a recent release my vpn is always auto-connecting, which would be a good idea, but if I manually disconnect the vpn and 5 min later it's already connected again, this is extremely annoying.

If I disconnect th vpn I don't want it to connect again like 5 min later, or at least a setting toggle would be nice.

### Steps to reproduce

- Connect the vpn with dns routed to a specific ip inside tailnet.
-  connect the vpn
- do something inside tailnet
- disconnect
- notice that it's connected again
- this gets extremely annoying, because in my setup traffic is rouged compledtely different through tailnet.

### Are there any recent changes that introduced the issue?

This problem exists most likely since the recent big update on the app.

### OS version

android 14

### Tailscale version

1.66.0-te2a0fc0bc-g6bd50e8026d

### Other software

Nothing that special

### Bug report

BUG-5ee122f54727797d98ac41289c3688ee7a4abc2e385068f9a539769f2fa8aacb-20240511212021Z-2b66adfb435374fa

**Comment by kari-ts** [comment]
Thanks for flagging! We merged a [fix](https://github.com/tailscale/tailscale-android/pull/377) for an autoconnecting issue. If you would like to [become an open tester](https://play.google.com/store/apps/details?id=com.tailscale.ipn), could you try the latest build and let us know if this resolves your issue? Thanks!

**Comment by CrazyWolf13** [comment]
Wow, I'm seriously impressed!
48h and already fixed + released 👏

Yes, am already a beta-tester :)
Thanks, works flawlessly now as far as I can tell, even the Quick-Setting toggle is back.
