### ISSUE TITLE
Tailscale should NOT hidden rewrite resolv.conf when package upgrades

### ISSUE THREAD

**Issue by evrial** [tailscale/tailscale#12102]
### What is the issue?

This practice is bad. My docker containers lost DNS for several days while I spent time reading Docker changelogs to find the issue. Don't waste my time such stupid way please, god bless you and your families.

### OS

Linux

### OS version

Debian GNU/Linux 12 (bookworm)

### Tailscale version

1.66.1

### Other software

Docker version 26.1.2, build 211e74b

### Bug report

BUG-7ad3987d9514279aa11bab6320a4b2ccb3eca8f9cd5039f2586c2fad2cb51f9d-20240511140105Z-128c080ebbe91cc6

**Comment by bradfitz** [comment]
I don't quite understand what this issue is in regards to.

Can you elaborate?

**Comment by evrial** [comment]
Basically both Tailscale and Docker updated almost at same time 3 days ago and containers lost the DNS resolving. This is not a fault from my part, I did only upt upgrade and nothing else. I tried to downgrade the Docker to 25 version and that didn't work. So I had to revent to original resolv.conf which I have found about modification today. If this was more explicit I would downgrade the tailscale and saved some time.

**Comment by bradfitz** [comment]
See https://tailscale.com/kb/1235/resolv-conf for how to avoid Tailscale touching that file.

If you can share more details about you Linux DNS config, perhaps we can do better even with your environment.

Otherwise I'm afraid there's nothing much more to do here.

**Comment by evrial** [comment]
I use Tailscale for a while and confident I didn't break anything. DNS config is minimal. Original resolv.conf:
```
nameserver 1.1.1.1
nameserver 1.0.0.1
```
I run pi-hole with unbound but they used only for remote hosts and working as expected.

**Comment by evrial** [comment]
Isn't this change?
https://github.com/tailscale/tailscale/compare/v1.66.0...v1.66.1#diff-46b19335a9ce02c5a93966e1b93d9d8407ffda6f6f7571acfb811c11f9241c41R436
