### ISSUE TITLE
Is insecure DERP secure?

### ISSUE THREAD

**Issue by hellodword** [tailscale/tailscale#12107]
- https://tailscale.com/security#tailscale-sees-your-metadata-not-your-data
- https://github.com/tailscale/tailscale/issues/3701#issuecomment-1010206678

> DERP relay servers do not log your data — you can confirm this yourself as the code is open-source. Even when your connection uses a DERP relay server, the only data Tailscale could see and capture is encrypted.

> InsecureForTests might go away in the future. It's really just for tests.

I'm curious about what's the worst thing when:

1. The connection is insecure, I mean, not protected by well-configured TLS, so bad guy is able to do MITM attack.
2. The DERP relay server is insecure, bad guys may do MITM attack on it.

So will people be well protected by the end-to-end encryption feature of tailscale in these cases?

**Comment by bradfitz** [comment]
Yes, it's still secure without https. The second layer of encryption isn't required.

Well, one place it's required: the web based wasm SSH client runs Tailscale in the browser where there's no UDP available to wasm so it can only use DERP. And the browser won't permit a websocket connection to http from https (at least without increasingly scary warnings)

And some firewalls only permit outbound TCP 443.

So https it is.
