### ISSUE TITLE
FR: Being back the app easy access window option

### ISSUE THREAD

**Issue by faslanetech** [tailscale/tailscale#12110]
### What are you trying to do?

you used to be able to see the app in the pull down quick settings area on Samsung to toggle it on and off quickly. can you PLEASE bring that back? Love the app and loved that feature in my S23uktra

### How should we solve this?

update or bug fix I assume.

### What is the impact of not solving this?

no impact of not doing it, just that it was super awesome.

### Anything else?

thanks for an awesome app!!!

**Comment by bradfitz** [comment]
It's coming back soon and is tracked in other open issues.
