### ISSUE TITLE
Failing to update tailscale on aarch64 Ubuntu 24.04

### ISSUE THREAD

**Issue by KGrewal1** [tailscale/tailscale#12112]
### What is the issue?

Attempting to update the apt package on a raspberry pi, running Ubuntu 24.04, from 1.64.0 to 1.66.1 is failing to find a newer package: 

```
sudo apt-get install tailscale
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tailscale is already the newest version (1.64.0).
```

### OS

Linux

### OS version

Ubuntu 24.04

### Tailscale version

1.64.0

**Comment by ScribeOfGoD** [comment]
I'm having the same issue with 2 computers both running x64 24.04 that aren't finding updates and are sitting on 1.64.0. I've tried to manually update which doesn't find any new versions and also tried to update through the website which doesn't seem to do anything as well. The other nodes in my tailnet seem to have updated without issue which includes a raspi and iOS devices
