### ISSUE TITLE
Need a mirror for instal on  Armbian_community 24.5.0-trunk.608 Bookworm with Linux 6.6.30-current-sunxi64

### ISSUE THREAD

**Issue by SMiK1** [tailscale/tailscale#12126]
### What is the issue?

I successfully use the program on two smart home servers with HAOS. However, installation there occurs from their repositories.
However, I am unable to install the program on the host that manages the mooracker printer.
When installing from an official source curl -fsSL https://tailscale.com/install.sh | sh, a message appears:

The installer cannot reach https://pkgs.tailscale.com/
Please make sure that your machine has internet access.
Test output:
curl: (22) The requested URL returned error: 451

The site is blocked, to bypass it you need to install something, but I don’t have experience working in Linux to deal with this problem

### OS

Linux

### OS version

Armbian_community 24.5

**Comment by bradfitz** [comment]
HTTP 451 means you're apparently in a country where we can't legally serve binaries. Sorry.
