### ISSUE TITLE
Tailscale on google play is not updated in timely

### ISSUE THREAD

**Issue by jiz4oh** [tailscale/tailscale#12122]
### What is the issue?

[tailscale on google play](https://play.google.com/store/apps/details?id=com.tailscale.ipn&hl=en_US) is not updated in timely, it's still `1.60.1-t2caffeeb4-g6f7ae79a31c` and the update available icon is still showing on my dashboard.

![image](https://github.com/tailscale/tailscale/assets/41264693/cf274624-201e-44de-be15-1f4db67eb40e)

I can not wait to use the newest tailscale. could you please update the google play or f-droid version?

### Steps to reproduce

N/A

### Are there any recent changes that introduced the issue?

N/A

### OS

Android

### OS version

Android13

### Tailscale version

1.60.1

### Other software

N/A

**Comment by jiz4oh** [comment]
thank you very much@agottardo, happy to join the beta channel as a tester

**Comment by agottardo** [comment]
v1.66.3 is rolling out to everybody.
