### ISSUE TITLE
Lack of `--wait` option in `systemd-run` before version 232 causes automatic updates to fail

### ISSUE THREAD

**Issue by noncombatant** [tailscale/tailscale#12136]
### What is the issue?

https://man7.org/linux/man-pages/man1/systemd-run.1.html says `--wait` was added in version 232, so people with versions older than that see this:

```
2024-05-07 00:28:59	c2n: running "systemd-run --wait --pipe --collect /usr/bin/tailscale update --yes"
2024-05-07 00:28:59	c2n: update command failed: exit status 1, output: systemd-run: unrecognized option '--wait'
```

We could make including `--wait` in the command conditional on a version check (`systemd-run --version`). I don't know whether the lack of the `--wait` feature would cause explosions; maybe it's safe but we'd have to test.

### OS

Linux

### OS version

At least CentOS 7.

**Comment by awly** [comment]
Not fixed yet since `--pipe` and `--collect` were added even later in systemd-run.
