### ISSUE TITLE
Android App - Cannot remove notification

### ISSUE THREAD

**Issue by kpcenti** [tailscale/tailscale#12132]
### What is the issue?

I used to be able to swipe away the notification for Tailscale - Connected and clear up my notification shade. Now I cannot. 

![Screenshot_20240514_131548](https://github.com/tailscale/tailscale/assets/10696951/e3131e17-fde4-44cf-af1a-ec91a8d446b5)

### Steps to reproduce

Connect to Tailscale Network

### Are there any recent changes that introduced the issue?

New notification from Tailscale. This was not previously here. 

### OS

Android

### OS version

Android 13

### Tailscale version

1.65.95-t71e9258ad-g5ea9a50ba57

### Bug report

BUG-1babe8d75264dac267d805d7f780b17070ea6867740f20136663c6172241a600-20240514171819Z-929fb6e2313f5188

**Comment by agottardo** [comment]
If this is bothering you, you can hold down on the notification to bring up your system notification settings. Disable notifications for the "VPN Status" category.

**Comment by kpcenti** [comment]
This wasn't an issue previously. I was able to swipe it away just yesterday. What changed? It seems like it's a bug

**Comment by agottardo** [comment]
What version are you running? I can swipe it away just fine on 1.67.13.

**Comment by kpcenti** [comment]
It seems to have updated to Version 1.67.13-t7b3e30f39-g46cdbb7b9b2 and I'm still not able to swipe it away.

**Comment by kelivel** [comment]
Hi @kpcenti, what device model are you using? I'm on a Pixel 8, and no trouble swiping away the notification here.

**Comment by kpcenti** [comment]
> Hi @kpcenti, what device model are you using? I'm on a Pixel 8, and no trouble swiping away the notification here.

Samsung Galaxy Note 20 Ultra 5G

**Comment by kpcenti** [comment]
I can swipe it away if I'm disconnected but not when I'm connected. 

Previously I was able to swipe way at either state

**Comment by sim642** [comment]
> If this is bothering you, you can hold down on the notification to bring up your system notification settings. Disable notifications for the "VPN Status" category.

I hoped that there was a separate notification category, but when I went into Tailscale's notification settings, there was nothing about categories, which led me to this issue.
Apparently, since Samsung One UI 6.1, notification categories are an "advanced" feature that's disabled by default: https://www.androidpolice.com/one-ui-61-disables-notification-channels/. After re-enabling them, the categories showed up and disabling "VPN Status" worked.

**Comment by joshvocal** [comment]
I believe that I have a fix - https://github.com/tailscale/tailscale-android/pull/477

cc: @kari-ts @agottardo

**Comment by kari-ts** [comment]
https://issuetracker.google.com/issues/237894785, https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications: interesting, it looks like in Android 13, notifications were made non-dismissable, and then this was reversed in Android 14. 
Thank you @joshvocal!

**Comment by kpcenti** [comment]
This is happening again. 
I'm on version. 1.80.0-t4f4686503-gb1405a1d1 

I cannot swipe away the notification while connected

**Comment by kpcenti** [comment]
The button to reopen the issue is grayed out for me.
