### ISSUE TITLE
tvOS exit node disconnects during speedtest

### ISSUE THREAD

**Issue by jrajahalme** [tailscale/tailscale#12139]
### What is the issue?

Tailscale VPN on AppleTV disconnects from the tailnet during a Speedtest running through it. Tailscale VPN reconnects after some time (seconds to minutes), but only if "Connect on demand" is selected in Tailscale VPN config. Depending on how late the reconnect happens, the Speedtest.net app on the iPhone reports a failure.

### Steps to reproduce

- tvOS (tailscale 1.66.0, tvOS 17.4.0) in home network configured as an exit node
- Run speedtest from an iPhone (tailscale 1.66.0, iOS 17.5.0) in the same tailnet, with the AppleTV selected as the exit node, from another network
- Initially download test starts to progress at normal (for tailnet) speed
- Tailscale app on the AppleTV shows the tailnet connection disconnecting
- Soon after the Tailscale VPN AppleTV reconnects, but only if "Connect on demand" is selected in Tailscale VPN config
- Depending on how late the reconnect happens, the Speedtest.net app on the iPhone reports a failure

### Are there any recent changes that introduced the issue?

First noticed related symptoms (streaming from another AppleTV stalling) a few weeks ago, on Tailscale 1.64.0.

### OS

Other

### OS version

tvOS 17.4.0

### Tailscale version

1.66.0

### Other software

Home network runs via Microtik SB5009, UDP port 41641 opened in FW/NAT config.

### Bug report

BUG-31979349133e34fc344f0ef1b114ce4e31ea98800f02ed32d6db32aa8ba3f313-20240515115415Z-b5288f5df3b43f86

**Comment by agottardo** [comment]
Hi, can you send me a sysdiagnose taken on the Apple TV to andrea@tailscale.com? Thanks.
