### ISSUE TITLE
Operator doesn't clean up egress proxy pod doesn't properly when FQDN doesn't exist

### ISSUE THREAD

**Issue by gjhenrique** [tailscale/tailscale#12146]
### What is the issue?

We're using Tailscale as our networking backbone for connecting developers local environments with other services running in Kubernetes.
We need ingress for the local application to communicate with the other ones, but also need to expose local traffic with the egress annotation `tailscale.com/tailnet-fqdn`. 

The order is:
1. An egress proxy pod is created with the `tailscale.com/tailnet-fqdn` annotation pointing to the future local FQDN
2. The local process starts and registers that FQDN
3. The proxy pod listens to those changes and configures the firewall rules and registers its node key on the Kubernetes secret

The bug lies when 2 has an issue and no fqdn is registered. The machine doesn't store its device information correctly, and the Tailscale operator can't clean up the device properly. It becomes a zombie.

In the codebase, if [this condition](https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go#L446-L449) is true, the code never reaches [the part](https://github.com/tailscale/tailscale/blob/6877d4496585adb75da5efa2eb528684aa71f24f/cmd/containerboot/main.go#L525-L529) where the proxy registers itself on the kubernetes secret.

A quick fix could be to move the registration part before the check if the FQDN is present.

I would also understand if it's a Tailscale requirement to have the service already registered.
That means we would need to coordinate ourselves to add the annotation *only after* the local service is running.

### Steps to reproduce

- Add the `tailscale.com/tailnet-fqdn` annotation with a FQDN that doesn't exist
- Remove the annotation
- The Tailscale operator should clean up the device properly

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.66.0

**Comment by irbekrm** [comment]
Thanks for the detailed issue description and instructions on how to reproduce @gjhenrique !

We can move the device ID part storage earlier (similar to what you suggested).  #12425 does that and should fix this issue.

**Comment by gjhenrique** [comment]
Hi @irbekrm 

Thanks a lot for the fix :pray: :smile_cat:

**Comment by irbekrm** [comment]
Going to close this as the original issue was solved
