### ISSUE TITLE
When encountering errors while using Tailscale 1.44.3 on Windows 7, how should I configure it correctly?

### ISSUE THREAD

**Issue by lizhengaas** [tailscale/tailscale#12163]
### What is the issue?

The error you encountered when you tried to install Tailscale 1.44.3 on Windows 7 SP1(6.1.7601) prevented Tailscale from starting properly. I have looked up the guide on GitHub to install the corresponding Win7 package, but the problem still persists.
`2024/05/17 16:19:22 tshttpproxy: winhttp: GetProxyForURL("https://controlplane.t
ailscale.com/"): ERROR_INVALID_PARAMETER [unexpected]
logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.44.3-te295bec6c-g08b3ae7fc, Go 1.20.5-ts40dc4d8: []string{"
C:\\Program Files\\Tailscale\\tailscaled.exe"}
LogID: 5a6de7b5422d16202d5c96ed376617eb6c364b76f5fb057707262f9c46d9ff49
logpolicy: using dir C:\ProgramData\Tailscale
wgengine.NewUserspaceEngine(tun "Tailscale") ...
Using existing driver 0.14
Creating adapter
Failed to setup adapter (problem code: 0x34): 由于硬件错误，显示设备需要重新初始
化。 (Code 0x0000048C)
Removed orphaned adapter "Tailscale"
Using existing driver 0.14
Creating adapter
Failed to setup adapter (problem code: 0x34): 由于硬件错误，显示设备需要重新初始
化。 (Code 0x0000048C)
Using existing driver 0.14
Creating adapter
`

### 
![image](https://github.com/tailscale/tailscale/assets/86937297/3f130fb9-95f1-4f0c-a2a2-6132553cfd25)

### Steps to reproduce

The error you're encountering when trying to install Tailscale 1.44.3 on Windows 7 SP1 (6.1.7601) is preventing Tailscaled from starting properly. You've already consulted the guide on GitHub for installing the corresponding packages for Win7, but the issue persists.

### Are there any recent changes that introduced the issue?

The error is caused by a newly installed Windows 7 system.

### OS

Windows

### OS version

windwos Service Pack1  6.1.7601

### Tailscale version

1.44.3

**Comment by dblohm7** [comment]
We're currently in the process of ending Windows 7 and Windows 8 support.
