### ISSUE TITLE
Update 1.66 and higher breake nginx proxy manager

### ISSUE THREAD

**Issue by Boerny41** [tailscale/tailscale#12167]
### What is the issue?

After upgrading to 1.66.3-stable, my self-hosted web services were no longer available. The web services run on a local server connected via Tailscale to a VPS with Internet access. This remote server also hosts a reverse proxy (nginx proxy manager) that redirects the subdomain.mydomain to the Tailscale IP corresponding to the web service. 
The problem occurs when updating the tailscale instance on the VPS, the instance on the personal server runs fine on 1.66.3. Both are docker containers using the official docker hub build - https://hub.docker.com/r/tailscale/tailscale

I've tried v1.66.3 and 1.67.15, but both result in this error.
The last stable version 1.64.2 works fine, as did everything before it.

### Steps to reproduce

I'm not exactly sure what goes wrong where, but I'd say with a setup similar to the one described above, it should be reproducible. I've tried different web services with different versions of the nginx proxy manager. All either worked or failed depending on the tailscale version.

### Are there any recent changes that introduced the issue?

tailscale update

### OS

Linux

### OS version

Ubuntu 22.04.4 LTS - Linux 5.15.0-107-generic

### Tailscale version

≥1.66.3

### Other software

npm - https://hub.docker.com/r/jc21/nginx-proxy-manager

### Bug report

Not sure how to get it from a container. Will look into it if needed.

**Comment by litori** [comment]
This has been confirmed.  New 1.66 breaks docker.  https://github.com/tailscale/tailscale/issues/12108
