### ISSUE TITLE
Unable to reauthenticate using notification banner button on iOS

### ISSUE THREAD

**Issue by Xenfo** [tailscale/tailscale#12178]
### What is the issue?

When clicking the reauthenticate button on iOS, it sends the app into an infinite loading state.

https://github.com/tailscale/tailscale/assets/46873232/225f1714-cb4b-44a7-b85c-a94181211c00

### OS

iOS

### OS version

iOS 17.5

### Tailscale version

1.66.3, 1.67.29

### Other software

Disabled custom DNS settings and iCloud Private Relay.

### Bug report

BUG-48a610950694519ba5b30db2a83aa890307cd5b8fd32a4f081c1d051b2507635-20240518123117Z-6862ab870e3db96e

**Comment by agottardo** [comment]
Do you have any on-demand settings enabled?

**Comment by Xenfo** [comment]
No I don't. I was actually able to reauthenticate but only one my phone expired from Tailscale and I was logged out of the app (not by clicking logout, simply because of the expiry). So something must be broken when trying to reauthenticate before the device actually expires.

**Comment by garrett-ts** [comment]
@agottardo I can repro this on my device as well

@Xenfo one way to workaround this for now is to not use the Reauthenticate button in the expiry warning. In my exp, that seems to specifically lead to the infinite loading state. You can instead Reauthenticate from your Account settings section. Steps:

1. connect to tailscale
2. tap the profile pic
3. select your account
4. select Reauthenticate

![IMG_1810](https://github.com/tailscale/tailscale/assets/110842475/2c654d27-b9d3-45fa-9c78-c104eadea214)

**Comment by agottardo** [comment]
Thanks for the report, I have pushed another fix that will land in TestFlight once approved.
