### ISSUE TITLE
Machines are not showing up in the web admin UI

### ISSUE THREAD

**Issue by cpuuntery** [tailscale/tailscale#1218]
When use the command 
`tailscale status`
 the Machines show up in the list like this
[![brob1.png](https://i.postimg.cc/sXtgQHHk/brob1.png)](https://postimg.cc/wyQpn2p2)
 but when I go to the browser the Machines are not there in the list
[![Capture.png](https://i.postimg.cc/ZKzqJgd3/Capture.png)](https://postimg.cc/4nwG5WwN)

the browser is Google Chrome Version 88.0.4324.104

**Comment by bradfitz** [comment]
You're using two different email addresses. The top screenshot is about your s***** gmail and the bottom one is about yousifstarco (as seen in the screenshot).
