### ISSUE TITLE
Installer script automatically does a partial upgrade on Arch Linux.

### ISSUE THREAD

**Issue by threeoh6000** [tailscale/tailscale#12186]
### What is the issue?

Arch Linux _heavily_ discourages the use of `pacman -Sy` due to the fact that this refreshes the package repositories and could cause newer libraries to be installed. This is a huge issue due to the fact that tailscale may update dependencies and break other applications depending on this automatically without any user intervention and could be huge source of headache for users of `pacman`-based distros.

Tailscale's installer should only install the package and should not be updating the repository information on the system nor upgrading any other packages.

At present, [the Tailscale automatic installer does a partial upgrade and this should not happen ever](https://github.com/tailscale/tailscale/blob/13e13555461a9b5490e97af875751ad14fb209a7/scripts/installer.sh#L516).

### Steps to reproduce

1. Install Tailscale using `install.sh`

### OS

Linux

### OS version

Arch Linux

### Tailscale version

latest

### Bug report

BUG-594969113a09ccd7f3c3109e4e29b3fefd6d4177e423a3513a8c02f6d6ade868-20240519004900Z-bd878ed37aceaa17

**Comment by SylvKT** [comment]
under "Recent Changes" you can put https://github.com/tailscale/tailscale/commit/1f4a34588be4b0da4838667f11fe4fef6c285d1f#diff-18fc04ba55d297cbc1fdff9261485e3c842ede50a33207632c3e08bb254f7ef2R497
