### ISSUE TITLE
gitops-pusher apply fails with INTERNAL_ERROR received from peer

### ISSUE THREAD

**Issue by aarontc** [tailscale/tailscale#12198]
### What is the issue?

Using the `gitops-pusher` Go package as documented for [GitLab CI](https://tailscale.com/kb/1254/gitops-acls-gitlab), the application of ACL changes is intermittently failing with this message:

```
Post "https://api.tailscale.com/api/v2/tailnet/[REDACTED]/acl": stream error: stream ID 5; INTERNAL_ERROR; received from peer
```

The failure occurs intermittently both in CI and when running locally. It doesn't seem to be a permission problem, as successes can also be observed by waiting a few minutes and rerunning the command.

For troubleshooting, I've tested gitops-pusher@latest (v1.66.3), and @v1.64.2 in case the newer version is an issue

### Steps to reproduce

1. Make an edit to a policy.hujson file
2. export TS_OAUTH_ID=<redacted>
3. export TS_OAUTH_SECRET=<redacted>
4. export TS_TAILNET=redacted
5. go install tailscale.com/cmd/gitops-pusher@latest
6. gitops-pusher --policy-file ./policy.hujson apply

### OS

Linux

### OS version

Debian 12

### Tailscale version

n/a

### Other software

go version go1.22.3 linux/amd64

**Comment by mrkwtz** [comment]
Same here, started occurring from May, 16th for us.

**Comment by chernogorsky** [comment]
same here

**Comment by kelivel** [comment]
Hi folks, thanks for reporting this and sorry for the disruption. We're actively working on a fix that should be shipped out today!

**Comment by kelivel** [comment]
Hi all, this should be resolved now. Please let us know if you're still seeing an error!

**Comment by aarontc** [comment]
> Hi all, this should be resolved now. Please let us know if you're still seeing an error!

We've seen a couple of successful CI runs now; I'll close the issue. Thanks!
