### ISSUE TITLE
Feature Reuqest: Windows - Auto Update Tailscale Client

### ISSUE THREAD

**Issue by war59312** [tailscale/tailscale#1221]
Hi,

I'm always frustrated with having to manully update windows machinces when a new Tailscale client version is released.

Would be wonderful if the Windows Tailscale Client could auto update itself.

Alternative solution could be to at least notify admin when new build is aviviable, such as by emailing admin.

Yes I see it shows about an update on the admin page. Sure not only one NOT looking a that page offten.

For know I just get the github relese email letting me know, which is cool too. Would just be cool if the client was always up to date.

For sure, do NOT show anything on end user systems about an update, That will only lead to confusion.

Thank you,

Will

**Comment by bradfitz** [comment]
Dup of #755.
