### ISSUE TITLE
Android app crashe if you already have a VPN set up.

### ISSUE THREAD

**Issue by learnyouapp** [tailscale/tailscale#12226]
### What is the issue?

App crashes

### Steps to reproduce

1 Install a VPN app For example ProtonVPN 

2 Enable always-on VPN, Block connections without VPN.

3 Install tail scale app and try setting up an account

4 App continuously crashes when you try to open it.

My phone is running GrapheneOS. On a pixel 7

### Are there any recent changes that introduced the issue?

NA

### OS

Android

### OS version

14  GrapheneOS

### Tailscale version

1.66.3 that should be the latest version, I just installed it from f-droid

### Other software

NA

### Bug report

BUG-9780d3e590d94dfad6a68222fd50e23bb9e79ea7dbd68b542f58b9ac1b8d5c21-20240523090550Z-5028e0538c6e1f7e

**Comment by agottardo** [comment]
@kari-ts is this the thing you already fixed? :)

**Comment by kari-ts** [comment]
This looks a lot like https://github.com/tailscale/tailscale/issues/12220, I'm looking into this!

**Comment by agottardo** [comment]
GrapheneOS enables "Block connections outside the VPN" by default, which breaks any attempt to do split-tunneling.

**Comment by learnyouapp** [comment]
@kari-ts  my issue is definitely different to 12220.
I was able to fix the issue, By going to my settings and turning off ProtonVPN. 
All you need to do to fix the issue is set up a tailscale app Launch check! That checks to see if a VPN is already set up by a different app. And if the response comes back as true,  tailscale Should have a pop-up banner which says Android does not allow multiple VPNs, Please disable your VPN

**Comment by jzazo** [comment]
I have a work profile controlled by MSDefender, that monitors web (in the work profile). I cannot disable MSDefender which I think sets up a VPN for the work profile.

The new version of Tailscale does not work with this setup, but the previous one was working. More precisely, the first beta release was working, but not the latest one. I am not sure Android does not allow multiple VPNs, that did not seem the case a few weeks ago.

**Comment by barnstar** [comment]
The crash here has been fixed in 1.67

**Comment by jzazo** [comment]
It works for me, thanks!

**Comment by barnstar** [comment]
We will continue to look into issues with multiple VPNs and at the very least, warn via the interface that you may be running a conflicting VPN.   We are tracking this with an internal bug.
