### ISSUE TITLE
Android 1.66.4: DNS loss when "Block connections without VPN" is enabled

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#12220]
### What is the issue?

http://go/tss/39140

This behavior may not be specific to pihole but is reproducible with one. When I set my tailnet DNS override to my pihole's Tailscale IP and enable "Block connections without VPN", attempting to resolve a website returns
`ERR_NETWORK_ACCESS_DENIED` in the browser.

DNS resolution is successful again when "Block connections without VPN" is disabled.

Logs show `dns udp query: waiting for response or error from [100.86.252.108]: context deadline exceeded`

### Steps to reproduce

1. Add pihole device to the tailnet
2. Set global DNS resolver as pihole's Tailscale IP (e.g. 100.86.252.108) with local override enabled
3. In Android settings, enable `always on vpn` and `Block connections without VPN`
4. Browse to any website

**Expected**: DNS resolution is successful
**Reality**: DNS resolution fails with`ERR_NETWORK_ACCESS_DENIED`

### OS

Android

### OS version

Android 14

### Tailscale version

1.66.4

### Bug report

BUG-316d64388b399833336398eee65064f7e7a38a4401b1fa1b35d615e17ef9187a-20240522161405Z-25aeac833a4d5ea1

**Comment by kelivel** [comment]
I'm also able to reproduce the same behavior with a global override of 9.9.9.9 or with Tailscale DNS disabled, both happens only when "Block connections without VPN" is enabled.

**Comment by kari-ts** [comment]
"Block connections without VPN" forces all traffic to go through the VPN tunnel and makes pihole or public DNS servers like 9.9.9.9. unreachable. Disabling this allows direct local network access. Closing this as WAI.
