### ISSUE TITLE
Unattended Mode: Machines don't retain login information after reboot

### ISSUE THREAD

**Issue by sloane-ts** [tailscale/tailscale#12239]
### What is the issue?

Win 10 and 11 machines aren't maintaining login information in Unattended Mode between reboots.

### Steps to reproduce

1. Clean install Dell Optiplex 
2. Joined to ADDS 
3. GPO installed CWise Automate and PDQ Connect 
4. CWise Automate installed Cwise Manage Agent and Webroot Secure Anywhere 
5. Triggered Tailscale deployment via PDQ Connect (deployment log attached) 
6. Verified device exists in Tailscale machine list with "gss-user" tag as expected from authkey in deployment package 
7. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
8. Ran "tailscale status," showed nodes as expected 
9. Rebooted 
10. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
11. Ran "tailscale status," showed "logged off" 
12. Repeated reboot and status check a couple of times 
13. Switched to console and logged in as "rbadmin" user 
14. Logged in to GUI, successful 
15. Logged off, logged back in, Tailscale connection status persisted 
16. Rebooted, status persisted 
17. Logged off of GUI, rebooted 
18. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
19. Ran "tailscale up --authkey[key] --unattended", connected successfully 
20. Ran "tailscale status," saw nodes as expected 
21. Rebooted 
22. Connected via Cwise Screen Connect to "Backstage" SYSTEM environment 
23. Ran "tailscale status," showed "logged off"

### OS

Windows

### OS version

10, 11

### Tailscale version

1.66.4

### Bug report

BUG-ef3ec0babba93027eaf61bbf379a62e48517dbf49bea50e497d2cd0d8a026d47-20240524172514Z-275b5add996ac947

**Comment by SerGinger** [comment]
I am continuing to test this and need to reformat and attempt a couple more times before I'm certain of consistency. It _appears_ that if a user is actively logged in, that running the Tailscale Up + authkey + unattended will persist. If they are not logged in (i.e. at machine image time) it will not persist. This appears to be true regardless of whether user profiles exist on the machine or not (meaning if you uninstall Tailscale, wipe programdata, then freshly install using deployment software and run Tailscale Up as SYSTEM, it will fail to persist).

Again, I need to test a few more times, but I've made approximately 10 attempts at this point with the two successes I believe being under the circumstances of a user already being logged in to the device when the code is run via the deployment software.

**Comment by SerGinger** [comment]
We have tested this a few more times and have consistently been able to make it work with this workaround. The exact steps:

- Fresh install of Tailscale using deployment manager (in this case PDQ Connect) with no users logged in
- Deployment is simple MSI installation, no additional code run post-install
- Log in as any valid user to the console
- Open TS GUI, log in, set Unattended Mode via GUI
- Reboot
- Log in to Windows as same user, log in state should be preserved on TS
- Log out of TS using GUI
- Run "Tailscale Up" command with authkey and unattended flags set via deployment tool or other SYSTEM-level command line
- Reboot
- Run "tailscale status" with SYSTEM-level command line, should show tailnet information as expected

**Comment by nickkhyl** [comment]
The fix for this issue is available in the 1.73.69 [unstable build](https://pkgs.tailscale.com/unstable/#windows) and will be included in the 1.74 release planned for September.
