### ISSUE TITLE
Tailscale for iOS can't connect if there's another VPN configuration

### ISSUE THREAD

**Issue by hellodword** [tailscale/tailscale#12245]
### What is the issue?

I use wireguard, so there's a VPN configuration named wg0 in the settings. Tailscale for iOS can't connect if I selected the wg0 (**without connected**).

### Steps to reproduce

1. Run Tailscale for iOS, login and connect, and open the System Settings - VPN, you'll find a VPN configuration named `Tailscale`
2. Add a VPN configuration whatever you want
3. Select the new VPN configuration, then the `Tailscale` will be disconnected, and make sure **no VPN is connected now**
4. Back to Tailscale for iOS and try to connect, it shows `Starting...` forever

### OS

iOS

### OS version

iOS 17.5.1

### Tailscale version

1.66.3

**Comment by varenc** [comment]
I can reproduce this.  Though oddly if just try to connect in Tailscale, abort that connection attempt, then try to connect again this second attempt works fine.
