### ISSUE TITLE
Android: Quick settings state inverted/out of sync

### ISSUE THREAD

**Issue by Majr-** [tailscale/tailscale#1225]
**Describe the bug**
The quick settings tile on the Android app gets out of sync with the actual state of the VPN, and always seems to show the state inverted, i.e.: tile is active when VPN is disconnected, and vice versa.

**To Reproduce**
1. Add the Tailscale tile to your quick settings
2. (extra bug) Pressing it won't do anything if the Tailscale app is closed, so open the app
3. Enable Tailscale in the app, check the quick setting tile and its state will not have changed
4. Tap the quick setting tile and it's state will change to active (or stay active if already), but disable Tailscale
5. Tap again, state will change to inactive, but enable Tailscale

**Expected behavior**
The quick settings tile should always indicate the actual state of the VPN, regardless of if it's changed within the app, within VPN settings, or on the tile itself.

**Screenshots**
Video showing the quick settings tile out of sync, and not updating when state is changed elsewhere. The VPN tile next to it shows the actual state of the connection.

https://user-images.githubusercontent.com/880296/106242000-1a6f9b80-625b-11eb-9f1b-b9fb0a9b0812.mp4

**Version information:**
 - Device: OnePlus 5T
 - OS: Android
 - OS version: 10
 - Tailscale version: 1.3.267

**Comment by eliasnaur** [comment]
Released version 1.4.0-t3d7cff91b-g33cf7c0aa19 with the fix. Thank you for the detailed report, @Majr-!

**Comment by R9anSmart** [comment]
Getting this issue again on Android
