### ISSUE TITLE
 https://pkgs.tailscale.com SSL connection is broken

### ISSUE THREAD

**Issue by pozar** [tailscale/tailscale#12250]
### What is the issue?

# curl -fsSL https://pkgs.tailscale.com/stable/debian/stretch.asc
curl: (35) error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)

### Steps to reproduce

Aim any browser at https://pkgs.tailscale.com

### OS

Linux, macOS, Windows, iOS, Android, Synology, Other

### OS version

All

### Tailscale version

All

**Comment by bradfitz** [comment]
Works for me from a number of different machines and OSes.

I suspect something in your network is messing with the cert if it affects that many OSes.

What does `openssl s_client -connect pkgs.tailscale.com:443` say?

**Comment by pozar** [comment]
```
$ openssl s_client -connect pkgs.tailscale.com:443 
CONNECTED(00000006)
40F2030102000000:error:0A0003E8:SSL routines:ssl3_read_bytes:reason(1000):ssl/record/rec_layer_s3.c:1586:SSL alert number 0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 320 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
Tims-MBP:~ pozar$ 
```
Very odd as I get from Chrome...
```
This site can’t provide a secure connectionpkgs.tailscale.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```
And from Firefox...
```
Secure Connection Failed

An error occurred during a connection to pkgs.tailscale.com. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

[Learn more…](https://support.mozilla.org/1/firefox/124.0.2/Darwin/en-US/connection-not-secure)
```

**Comment by bradfitz** [comment]
Yeah, something's messing with you.

What network you on? Got a traceroute?

**Comment by pozar** [comment]
Ya...  Something is odd with this network.  On other networks it is fine.  Let's close this.
