### ISSUE TITLE
Battery Usage.... 

### ISSUE THREAD

**Issue by daviedude1975** [tailscale/tailscale#12269]
### What is the issue?

Forgive me for voicing here as I know this isn't the proper channel, but I emailed your sales/support guys and have got no response. That was WEEKS ago.

I am interested in purchasing Tailscale for our environment, but because they are mostly Apple decvices we naturally have many iOS devices. I have been following this: https://github.com/tailscale/tailscale/issues/3363 for sometime, and it looks like the TS team have now locked it and it has gone stagnant again.

Forgive me again, but how do you expect potentially paying users to feel confident with a purchase decision when your support line just doesn't bother answering their emails and the battery drain issue is very much NOT fixed. Months later..... again....... Every time someone says "yeah yeah we're on it" it fizzles out again....

On one of our test devices:

24 hours:

![24 hours](https://github.com/tailscale/tailscale/assets/171092156/0fc08976-fc15-4be4-92ba-289a13414758)

10 days:

![10 days](https://github.com/tailscale/tailscale/assets/171092156/acb91cd7-9088-4cde-8ed2-c4dfaf9c8a01)

From what we can tell, on this particular device, the drain seems to happen when on cellular.

I've been watching this for over a year. Critical unfixed issues + a year of time past does not a good future business relationship make. Some users seem to have reported now perfect usage, others not so perfect usage. For us it's totally unusable still. 

And locking the issue then stopping working on it again? (The only reason I created this new issue instead of submitting helpful bug report IDs to the above issue.) And ignoring warm sales lead emails? This is just _silly_ at this point!!

### Steps to reproduce

Use the app.

### Are there any recent changes that introduced the issue?

N/A

### OS

iOS

### OS version

iOS 17.5.1

### Tailscale version

1.66.3

### Other software

N/A

**Comment by bradfitz** [comment]
Battery work continues, both client & server side. We'll publish details on #3363 but in summary we're not happy with it yet either.

We actually had a contact form outage a couple weeks ago where submissions for almost an hour were lost during a migration. It's possible you mailed us during that time. I'd say try to email again, but perhaps you should wait until battery's in a better state as that sounds like it's a blocker for you.

Closing this as a dup of #3363.

**Comment by daviedude1975** [comment]
Hi @bradfitz, thank you for the prompt reply and for the update. 

I appreciate your time taken to explain the situation and yes, it would seem perhaps I had used the contact form at that point.

I won't email again now as it is clear that the focus is still on this issue. The battery is indeed a blocker for us, so I will continue to monitor https://github.com/tailscale/tailscale/issues/3363 for updates then make contact at a more appropriate time.

Many thanks, 

David
