### ISSUE TITLE
docs(k8s): remove warning that says you don't support ExternalName

### ISSUE THREAD

**Issue by aviau** [tailscale/tailscale#12266]
### What is the issue?

[This page](https://tailscale.com/kb/1236/kubernetes-operator#exposing-a-kubernetes-cluster-workload-to-your-tailnet-cluster-ingress) says
> We currently do not support exposing a cluster workload using a [Service of type ExternalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) neither directly nor as an Ingress backend.

But this is false as of 1.66:
- https://github.com/tailscale/tailscale/issues/10606

And even the same page says the opposite under "Expose a cloud service using a Kubernetes ExternalName Service"

Cheers :)

**Comment by irbekrm** [comment]
Thanks a lot for spotting that @aviau , will remove 👍🏼

**Comment by irbekrm** [comment]
Done https://tailscale.com/kb/1236/kubernetes-operator#exposing-a-kubernetes-cluster-workload-to-your-tailnet-cluster-ingress
