### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by Cokemancola69696** [tailscale/tailscale#12261]
### What is the issue?

When I go to get on the app it says I have a bug and report it to support

### Steps to reproduce

I didn't take no steps but it said and report to the support team immediately

### Are there any recent changes that introduced the issue?

Not that I noticed

### OS

Android

### Bug report

BUG-06591c2c58d6c834e96c2b400a825de91fcbe96947a932ac1673e96ce68d74ae-20240528052937Z-f34c5cb3d8bd65e7

**Comment by agottardo** [comment]
There is no need to file a bug report or to provide an identifier unless there is a compelling reason for you to do so, such as a network connectivity issue, or a feature is broken.
