### ISSUE TITLE
Update functionality broken Windows

### ISSUE THREAD

**Issue by kellytrinh** [tailscale/tailscale#1228]
**Describe the bug**

Machines running windows 1.2.9 and 1.2.10 do not show update availalbe (to 1.4.0) when right click on system tray icon and selecting 'about'

**Expected behavior**
Get the 'update available' option to install without needing to manually go to website

**Comment by bradfitz** [comment]
That's intentional. We're doing a slow rollout to 1.2.10 clients for a few days (hiding the 1.4.0 update) to make sure 1.4.0 has no surprise bugs.

We do suggest updates to 1.2.9 clients.
