### ISSUE TITLE
FR: Configurable WireGuard Toggle for Tailscale

### ISSUE THREAD

**Issue by Arc-2023** [tailscale/tailscale#12286]
### What are you trying to do?

Given that WireGuard does not obfuscate traffic, its cryptographic properties and distinctive signatures can make it inconvenient for use in certain contexts, such as within educational networks and corporate intranets. The inability to decrypt such traffic may draw unwanted attention from network administrators or ISPs, especially when hole punching fails and the traffic passes through international DERP relay servers.
Therefore, in many cases, disabling WireGuard to allow for unencrypted transmission can be a preferable option, offering better performance. Furthermore, utilizing SSL/TLS certificates from reverse proxy servers for authentication and encryption can be less prone to being inadvertently blocked by anti-censorship systems compared to WireGuard.

### How should we solve this?

just give us a menu

### What is the impact of not solving this?

have told above

### Anything else?

non

**Comment by bradfitz** [comment]
> just give us a menu

We do not plan on offering a "turn off crypto" option.

**Comment by Arc-2023** [comment]
> "turn off crypto"

Using web TLS certificates instead of WireGuard does not "turn off" encryption; on the contrary, it might be more secure.
