### ISSUE TITLE
Integration with Rethink DNS app

### ISSUE THREAD

**Issue by milesmcclane** [tailscale/tailscale#12280]
### What are you trying to do?

I would really like to be able to use my Tailscale network (plus Mullvad) along with Rethink DNS app on Android. 

https://github.com/celzero/rethink-app/issues/1047

**Comment by agottardo** [comment]
@milesmcclane Can you expand on this a little bit? What does the Rethink app do, and what kind of integration should Tailscale build? What features do you desire? What are you unable to do right now because of this missing integration?

**Comment by milesmcclane** [comment]
Hey there. Thanks for the response. 

I didn't try to offer any suggestions because, well I don't really know much about how it all works. 

However, Rethink is an app that offers connection monitoring and blocking like little snitch or even wire shark. It also allows one to configure various DNS filters. It allows me much more granular control on what connections my phone is making.  

The problem is, it uses androids only VPN slot to work. The app has a special function whereby you can integrate a wireguard VPN if you like, (or orbot if one prefers tor). After experimenting somewhat using my protonvpn sub, I find rethink just an incredible piece of software. 

However, so is Tailscale plus Mullvad! More so in fact, as I need to access my home lab on all my devices. 

I would like the ability to somehow integrate Tailscale to Rethink so i can run Tailscale whilst running rethink, as I did with proton using wireguard. 

I'm sure I went on a bit, sorry for my lack of succinct knowledge!

What do you think?

**Comment by agottardo** [comment]
Unfortunately we can't build that _on our side_, as Android only supports using one VPN at a time. There is no way for the Tailscale tunnel to operate while Rethink is also running its own tunnel.

**Comment by milesmcclane** [comment]
> Unfortunately we can't build that _on our side_, as Android only supports using one VPN at a time. There is no way for the Tailscale tunnel to operate while Rethink is also running its own tunnel.

Thanks for the reply!  I'm not a technical when it comes to networking, but rethink is also a wireguard client, and so can run wireguard commercial vpns though it. It can also run socks5 proxies. There are other things that aren't relevent that you can proxy, orbot for tor and https connect. 

So is there any situation can Tailscale be forcd to work together with rethink in any respect? Is there already a route I can try that _could_ work? Or is it completely out of your hands and I must chat with the developer of rethink?

Thanks for your help.

**Comment by agottardo** [comment]
Rethink would more or less need to incorporate a copy of the Tailscale client within its app in order for this to work: handling the login flow, maintaining a connection to the Tailscale control server, exchanging keys, keeping alive a connection to a DERP server, taking care of MagicDNS resolution, then routing traffic through the Tailscale tunnel interface as needed. Lots of moving pieces, and it's a lot of work. The initial comment on the issue you posted is a good start: "May be possible to run tailscale in its "usermode" setting", that sounds like what you need to do.

It's not something we can handle on our side, it must be done within Rethink.

**Comment by milesmcclane** [comment]
Thank you so much for your input. I'm sure the devs of rethink are probably aware, but I'll rely the info nonetheless. Have a good day.

**Comment by ignoramous** [comment]
> It's not something we can handle on our side, it must be done within Rethink.

If Mr. Pennarun wants to sponsor this work, let us know! (:
