### ISSUE TITLE
[Taildrive] sudo must be installed in order to share a directory

### ISSUE THREAD

**Issue by kjrobrien** [tailscale/tailscale#12282]
### What is the issue?

I'm running tailscale on a linux host that only has BusyBox. I'm trying to share a directory with Taildrive and it does not work. The error includes `"root" is root`. Looking at the code here: https://github.com/tailscale/tailscale/blob/main/drive/driveimpl/remote_impl.go#L335-L350 it looks like there's a requirement that `sudo` be installed which is not included with BusyBox.

### Steps to reproduce

Run `tailscale drive share` on a host without sudo.

### OS

Linux

### Tailscale version

1.66.4

**Comment by oxtoacart** [comment]
@kjrobrien If you grab the latest unstable, it should be using `su` instead of `sudo` now. Please let me know how it goes.
