### ISSUE TITLE
FR: Instructions for static build

### ISSUE THREAD

**Issue by smst329** [tailscale/tailscale#12283]
### What are you trying to do?

I would like to make a static build for linux. I tried some common build commands for go static builds and ldd is still showing a linked binary. I may have overlooked it, but the repo does not seem to cover static builds.

### How should we solve this?

If something could be added to the build_dist script, the makefile or documentation showing the command that the tailscale team runs for static builds that would be awesome!

### What is the impact of not solving this?

The binary is not portable.

**Comment by bradfitz** [comment]
The trick with Go is to set the environment variable `CGO_ENABLED=0`. That's also the default when you're cross-compiling from a different system.

You can also use your `./tool/go` wrapper in the tree, which sets that automatically. You'll note that the `build_dist.sh` also has an an environment variable `TS_USE_TOOLCHAIN` to control whether our Go toolchain+wrapper are used, so you can get it that way as well.

Example:
```
bradfitz@tsdev:~/src/tailscale.com$ git rev-parse HEAD
0acb61fbf835857d5c7a9ec594a1b3c5bf7cacd5
bradfitz@tsdev:~/src/tailscale.com$ go version
go version go1.22.3 linux/amd64
bradfitz@tsdev:~/src/tailscale.com$ go install ./cmd/tailscaled
bradfitz@tsdev:~/src/tailscale.com$ ldd $(go list -f {{.Target}} ./cmd/tailscaled/)
        linux-vdso.so.1 (0x00007fff60faa000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f64ed7c2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f64ed7a0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f64ed5cc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f64ed7f4000)
bradfitz@tsdev:~/src/tailscale.com$ CGO_ENABLED=0 go install ./cmd/tailscaled
bradfitz@tsdev:~/src/tailscale.com$ ldd $(go list -f {{.Target}} ./cmd/tailscaled/)
        not a dynamic executable
bradfitz@tsdev:~/src/tailscale.com$ ./tool/go install ./cmd/tailscaled
bradfitz@tsdev:~/src/tailscale.com$ ldd $(./tool/go list -f {{.Target}} ./cmd/tailscaled/)
        not a dynamic executable
```

**Comment by smst329** [comment]
Perfect and thank you!!

**Comment by AGSPhoenix** [comment]
It took me about an hour of work over the course of a day to find this GitHub issue. IMO, the original intent of the issue is not resolved - how do you expect users to find this info? Based on a quick skim through the codebase, the meaning of the flag isn't explained *anywhere*, the [small Tailscale](https://tailscale.com/kb/1207/small-tailscale) KB article doesn't mention it at all, and  Google search results for Go static builds largely focus on the `extldsflags` build parameter.

Please consider reopening this issue.
