### ISSUE TITLE
Outdated "github.com/tailscale/netlink" dependency blocks "tailscale.com/tsnet" import

### ISSUE THREAD

**Issue by gyuho** [tailscale/tailscale#12298]
### What is the issue?

We are importing `tailscale.com@v1.66.4` to run `tsnet`, and the `netlink`:

```go
policy.Src = msg.Sel.Saddr.ToIPNet(msg.Sel.PrefixlenS)
```

fails the linux builds:

```
296.6 /go/pkg/mod/github.com/tailscale/netlink@v1.1.1-0.20211101221916-cabfb018fe85/xfrm_policy_linux.go:223:37: not enough arguments in call to msg.Sel.Saddr.ToIPNet
296.6 	have (uint8)
296.6 	want (uint8, uint16)
```

https://github.com/vishvananda/netlink/blob/v1.1.0/nl/xfrm_linux.go#L134

```go
func (x *XfrmAddress) ToIPNet(prefixlen uint8) *net.IPNet {
	ip := x.ToIP()
	if GetIPFamily(ip) == FAMILY_V4 {
		return &net.IPNet{IP: ip, Mask: net.CIDRMask(int(prefixlen), 32)}
	}
	return &net.IPNet{IP: ip, Mask: net.CIDRMask(int(prefixlen), 128)}
}
```

vs.

https://github.com/vishvananda/netlink/blob/4d4ba1473f21ca0ccdecc301adbe4315db42718b/nl/xfrm_linux.go#L134-L142

```go
func (x *XfrmAddress) ToIPNet(prefixlen uint8, family uint16) *net.IPNet {
	empty := [SizeofXfrmAddress]byte{}
	if bytes.Equal(x[:], empty[:]) && prefixlen == 0 {
		if family == FAMILY_V6 {
			return &net.IPNet{IP: net.ParseIP("::"), Mask: net.CIDRMask(int(prefixlen), 128)}
		}
		return &net.IPNet{IP: net.ParseIP("0.0.0.0"), Mask: net.CIDRMask(int(prefixlen), 32)}
	}
```

 

### Steps to reproduce

Import `tailscale.com@v1.66.4` and build on Linux

### Are there any recent changes that introduced the issue?

https://github.com/vishvananda/netlink/issues/815 needs to be backported

### Tailscale version

1.66.4

**Comment by oxtoacart** [comment]
We're looking into getting caught up with the latest upstream. As a temporary workaround, you can pin an older version of netlink:

```
go get github.com/vishvananda/netlink/nl@b10eb8fe5cf6ad397bcebe30a53d8607d9191b09
```
