### ISSUE TITLE
FR: Integrating IPinfo.io's IP to Country ASN database

### ISSUE THREAD

**Issue by abdullahdevrel** [tailscale/tailscale#12294]
### What are you trying to do?

Tailscale currently uses a semi-updated database for location data. However, as Tailscale grows, it needs more accurate data, particularly for IP-based security, and location issues arise. I think IPinfo's free IP data can help with that.

### How should we solve this?

I am requesting to add support for [IPinfo's IP to Country database](https://ipinfo.io/products/free-ip-database) to the project. The database has the following features:

- It includes country and ASN information in the same database.
- It is updated daily, with zero compromise to accuracy. There is no range clustering, and the database provides full accuracy.
- The data granularity reaches individual IP levels.
- The database comes in MMDB database format.
- It is licensed under CC-BY-SA 4.0, permitting commercial usage.
- Available file formats include: CSV, MMDB, JSON
- The data is tabular and unnested, making it very easy to use. The dataset includes both IPv4 and IPv6 in a single file.

## Database schema

| Field Name       | Example                      | Data Type | Description                                       |
|------------------|------------------------------|-----------|---------------------------------------------------|
| `start_ip`       | 1.0.16.0                     | TEXT      | Starting IP address of an IP address range        |
| `end_ip`         | 1.0.31.255                   | TEXT      | Ending IP address of an IP address range          |
| `country`        | JP                           | TEXT      | ISO 3166 country code of the location             |
| `country_name`   | Japan                        | TEXT      | Name of the country                               |
| `continent`      | AS                           | TEXT      | Continent code of the country                     |
| `continent_name` | Asia                         | TEXT      | Name of the continent                             |
| `asn`            | AS2519                       | TEXT      | Autonomous System Number                          |
| `as_name`        | ARTERIA Networks Corporation | TEXT      | Name of the AS (Autonomous System) organization   |
| `as_domain`      | arteria-net.com              | TEXT      | Official domain or website of the AS organization |

Documentation: https://ipinfo.io/developers/ip-to-country-asn-database

### What is the impact of not solving this?

Security issues are the main concerns. Accurate location data is crucial for VPN software, especially if you want to add a layer of IP-based metadata for security purposes. Additionally, Tailscale recently [introduced auto-exit nodes](https://tailscale.com/blog/auto-exit-nodes) that rely on good and reliable IP location metadata. Moreover, as the database includes ASN information, this can help further strengthen security and access policies.

**Comment by bradfitz** [comment]
We've already purchased a IP location database license. That work is proceeding server-side in another (private) repo.
