### ISSUE TITLE
Docker Tailscale version 1.66.3 is still latest

### ISSUE THREAD

**Issue by seanob86** [tailscale/tailscale#12297]
### What is the issue?

1.66.4 was released over a week ago with 1.66.3 still latest in dockerhub. 

1.66.4 changed stateful filtering to off by default and documentation such as [site-to-site](https://tailscale.com/kb/1214/site-to-site) have been updated to remove the stateful filtering flag. 

Given that 1.66.3 has stateful filtering on by default and no indication if 1.66.4 will be released for docker, will the update come to docker? 

I know the docker updates lag a few days but it’s already elapsed that. 

### Steps to reproduce

Pull Tailscale with either `latest` or `stable` tag

### OS

Other

### OS version

Docker

### Tailscale version

1.66.3

**Comment by miki725** [comment]
same appears to be in github container registry

https://github.com/tailscale/tailscale/pkgs/container/tailscale

<img width="780" alt="image" src="https://github.com/tailscale/tailscale/assets/932940/ba63fe0d-d4ed-4c92-9d94-37c464f495f9">

even though both docker hub and github container registry are listed as sources where tailscale can be downloaded in https://tailscale.com/kb/1282/docker

> Tailscale has a published Docker image that Tailscale manages and builds from source. It's available in [Docker Hub](https://hub.docker.com/r/tailscale/tailscale) and [GitHub Packages](https://github.com/orgs/tailscale/packages/container/package/tailscale).

**Comment by bkonicek** [comment]
Agreed - there also still hasn't been a new version of the helm chart published for 1.66.4

**Comment by awly** [comment]
This was an oversight on our end, sorry.
1.66.4 containers are now built.

For context: we intentionally delay container releases by a few days, similar to auto-updates. This allows some time for user bug reports to come in and for us to spot any major regressions. Once we release new images, anyone using mutable tags like `tailscale/tailscale:stable` would automatically update, and we don't want to avoid surprise regressions.

However, this process relies on the release manager to remember to build new images, which is prone to human error. I will add some internal alerting to surface when container images are behind the official release for too long.

**Comment by awly** [comment]
Note: we've reset `:latest`, `:stable`, and `:v1.66` tags back to `v1.66.3` due to https://github.com/tailscale/tailscale/issues/12307.
`:v1.66.4` is still available though.

**Comment by seanob86** [comment]
> Note: we've reset `:latest`, `:stable`, and `:v1.66` tags back to `v1.66.3` due to #12307. `:v1.66.4` is still available though.

Thanks. No issues here with `v1.66.4` tag. Just removed the stateful filtering flag pre upgrade for a smooth upgrade 👍
