### ISSUE TITLE
FR: implement container env var trigger for rx-udp-gro-forwarding toggle

### ISSUE THREAD

**Issue by jwhited** [tailscale/tailscale#12295]
### What are you trying to do?

https://tailscale.com/kb/1320/performance-best-practices#ethtool-configuration instructs users on how to toggle netdev features for optimal UDP forwarding throughput. Doing this in a container is messy with CMD/ENTRYPOINT overrides.

### How should we solve this?

The cmd/containerboot wrapper supports tailscale configuration/behavior applied via environment variable. We could add a new environment variable that automatically toggles netdev features.

### What is the impact of not solving this?

Users cannot easily optimize configuration for peak UDP forwarding throughput in container environments.

**Comment by maisem** [comment]
cc @irbekrm

**Comment by irbekrm** [comment]
Should we, instead of adding a toggle, just do it for each container instance that is a subnet router/exit node?

We can tell if a container is a subnet router/exit node by reading the `TS_ROUTES`, `TS_EXTRA_ARGS` env vars.

**Comment by irbekrm** [comment]
Hmm, perhaps this will require extra permissions (if we also need to do it for userspace subnet routers/exit nodes)

**Comment by irbekrm** [comment]
This was implemented in #12410 .

I've cut a new unstable release with this change `unstable-v1.67.114`
