### ISSUE TITLE
Tailscale crashed upon system boot and make my taskbar varnish

### ISSUE THREAD

**Issue by bolavefasfas** [tailscale/tailscale#12299]
### What is the issue?

![image](https://github.com/tailscale/tailscale/assets/82230241/2dafbe31-fcc8-456a-b305-387a072d45a2)

### Steps to reproduce

Install win 24h2 and install taiscale after 3 days of that this happened

### Are there any recent changes that introduced the issue?

nothing,
was using tailscale on 2 accounts.

### OS

Windows

### OS version

Version 24H2 (OS Build 26100.712)

### Tailscale version

1.66.4

### Other software

none
no other software vpn nothing 

### Bug report

BUG-f61a934b8b8344cc8ca2f8e2d2331d710395a09da16721f7bfe3c25d8a087468-20240531045757Z-8c361feeff605ef4

**Comment by dblohm7** [comment]
24H2? @bolavefasfas, I take it you're running an insider build?

It looks like Explorer crashed and the GUI was subsequently unable to re-create the icon. We're going to be getting rid of that modal message box.

**Comment by bolavefasfas** [comment]
> 24H2? @bolavefasfas, I take it you're running an insider build?
> 
> It looks like Explorer crashed and the GUI was subsequently unable to re-create the icon. We're going to be getting rid of that modal message box.

Thanks idk why my taskbar is not showing up formatted my device from 24h2 to 23h2 
24h2 was faster than 23h2 like a lot
