### ISSUE TITLE
[MacOS] Network is completely down on macbook waking up.

### ISSUE THREAD

**Issue by qoega** [tailscale/tailscale#12302]
### What is the issue?

I have a corporate tailscale account enabled. 
MagicDNS is needed to access resources within tailnet and I can't disable it as recommended.
Every time I open my macbook I have to wait several minutes for my internet to stop working.
Tailnet has no exit nodes so it should not try to route traffic via exitnodes.
It is not only DNS as it looks you intercept ip access as well.

This is how ping works during this time period 
```
ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
64 bytes from 1.1.1.1: icmp_seq=0 ttl=59 time=6653.764 ms
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
64 bytes from 1.1.1.1: icmp_seq=4 ttl=59 time=7281.998 ms
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13
Request timeout for icmp_seq 14
Request timeout for icmp_seq 15
64 bytes from 1.1.1.1: icmp_seq=9 ttl=59 time=7629.168 ms
64 bytes from 1.1.1.1: icmp_seq=11 ttl=59 time=6652.161 ms
64 bytes from 1.1.1.1: icmp_seq=14 ttl=59 time=4383.294 ms
Request timeout for icmp_seq 19
64 bytes from 1.1.1.1: icmp_seq=17 ttl=59 time=3411.534 ms
Request timeout for icmp_seq 21
Request timeout for icmp_seq 22
64 bytes from 1.1.1.1: icmp_seq=18 ttl=59 time=5359.381 ms
Request timeout for icmp_seq 24
Request timeout for icmp_seq 25
Request timeout for icmp_seq 26
Request timeout for icmp_seq 27
Request timeout for icmp_seq 28
Request timeout for icmp_seq 29
Request timeout for icmp_seq 30
64 bytes from 1.1.1.1: icmp_seq=24 ttl=59 time=7036.874 ms
64 bytes from 1.1.1.1: icmp_seq=25 ttl=59 time=7245.397 ms
Request timeout for icmp_seq 33
64 bytes from 1.1.1.1: icmp_seq=27 ttl=59 time=7221.212 ms
64 bytes from 1.1.1.1: icmp_seq=29 ttl=59 time=6438.700 ms
Request timeout for icmp_seq 36
64 bytes from 1.1.1.1: icmp_seq=30 ttl=59 time=7144.637 ms
Request timeout for icmp_seq 38
Request timeout for icmp_seq 39
Request timeout for icmp_seq 40
64 bytes from 1.1.1.1: icmp_seq=34 ttl=59 time=7243.518 ms
Request timeout for icmp_seq 42
Request timeout for icmp_seq 43
Request timeout for icmp_seq 44
64 bytes from 1.1.1.1: icmp_seq=41 ttl=59 time=4706.126 ms
64 bytes from 1.1.1.1: icmp_seq=43 ttl=59 time=3372.147 ms
64 bytes from 1.1.1.1: icmp_seq=44 ttl=59 time=2674.041 ms
64 bytes from 1.1.1.1: icmp_seq=45 ttl=59 time=2379.560 ms
Request timeout for icmp_seq 49
Request timeout for icmp_seq 50
Request timeout for icmp_seq 51
64 bytes from 1.1.1.1: icmp_seq=46 ttl=59 time=6167.279 ms
Request timeout for icmp_seq 53
64 bytes from 1.1.1.1: icmp_seq=47 ttl=59 time=7422.721 ms
64 bytes from 1.1.1.1: icmp_seq=48 ttl=59 time=6798.955 ms
64 bytes from 1.1.1.1: icmp_seq=51 ttl=59 time=5057.675 ms
64 bytes from 1.1.1.1: icmp_seq=53 ttl=59 time=5012.829 ms
Request timeout for icmp_seq 58
Request timeout for icmp_seq 59
64 bytes from 1.1.1.1: icmp_seq=54 ttl=59 time=6388.643 ms
Request timeout for icmp_seq 61
Request timeout for icmp_seq 62
Request timeout for icmp_seq 63
Request timeout for icmp_seq 64
64 bytes from 1.1.1.1: icmp_seq=57 ttl=59 time=8612.183 ms
Request timeout for icmp_seq 66
Request timeout for icmp_seq 67
Request timeout for icmp_seq 68
Request timeout for icmp_seq 69
Request timeout for icmp_seq 70
Request timeout for icmp_seq 71
Request timeout for icmp_seq 72
Request timeout for icmp_seq 73
Request timeout for icmp_seq 74
Request timeout for icmp_seq 75
Request timeout for icmp_seq 76
Request timeout for icmp_seq 77
Request timeout for icmp_seq 78
Request timeout for icmp_seq 79
Request timeout for icmp_seq 80
Request timeout for icmp_seq 81
64 bytes from 1.1.1.1: icmp_seq=72 ttl=59 time=10711.228 ms
Request timeout for icmp_seq 83
Request timeout for icmp_seq 84
Request timeout for icmp_seq 85
64 bytes from 1.1.1.1: icmp_seq=77 ttl=59 time=9333.189 ms
64 bytes from 1.1.1.1: icmp_seq=79 ttl=59 time=8135.852 ms
^[[A64 bytes from 1.1.1.1: icmp_seq=80 ttl=59 time=7468.492 ms
^C
--- 1.1.1.1 ping statistics ---
89 packets transmitted, 28 packets received, 68.5% packet loss
round-trip min/avg/max/stddev = 2379.560/6355.091/10711.228/1916.205 ms
➜  ~ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
64 bytes from 1.1.1.1: icmp_seq=1 ttl=59 time=7137.190 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=59 time=7472.581 ms
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13
Request timeout for icmp_seq 14
Request timeout for icmp_seq 15
Request timeout for icmp_seq 16
Request timeout for icmp_seq 17
Request timeout for icmp_seq 18
Request timeout for icmp_seq 19
Request timeout for icmp_seq 20
Request timeout for icmp_seq 21
Request timeout for icmp_seq 22
64 bytes from 1.1.1.1: icmp_seq=13 ttl=59 time=11031.224 ms
```

And I can't access local ip addresses as well (for example I try to open router webinterface).

Swithing off/on of tailscale, wifi etc do not help to resolve it.

This is very annoying and I see multiple reports looking similar. I am ready to reproduce, but I need to know which telemetry to collect while in broken state, I can't write comments and ask for help when there is no connectivity.

### Steps to reproduce

Just close macbook and open it again while tailscale is running.

### OS

macOS

### OS version

14.5 (23F79)

### Tailscale version

1.66.4

### Bug report

BUG-ee401464c7a6b64199a7bce249b59d3aec8c3db5fc13f78d30d16e1b7febda6d-20240531114939Z-c01234a8c5268c30

**Comment by agottardo** [comment]
Having MagicDNS enabled or disabled has no impact on the latency you see when pinging 1.1.1.1, as DNS is not involved in that process.

Additionally, unless an exit node is used, Tailscale only routes traffic bound for Tailscale IP addresses. You can verify that yourself by running `netstat -rn` in the Terminal, and observing that the utun* interface for Tailscale is not associated with anything other than routes in the 100.x.y.z space. Actually, would you mind posting the output of that command while Tailscale is running so we can ensure there is no misconfiguration?

If you're an enterprise customer using a work computer, we strongly recommend you contact our support team directly (support@tailscale.com) instead of posting here. A private conversation would allow support to gather more detailed diagnostic information from your Mac.

**Comment by qoega** [comment]
I send additional information in TSS-39875

**Comment by qoega** [comment]
It is possible that something what MagicDNS does on start kills my provider connection. 

I tried enabling MagicDNS when my Tailscale connection was already on and internet was working. Second image of me connecting Tailscale with MagicDNS enabled in settings. Both result in some crazy connectivity issues. 
<img width="400" alt="Screenshot 2024-06-01 at 22 58 40" src="https://github.com/tailscale/tailscale/assets/2159081/f6297230-89c9-49c6-88b2-2e8730a9dbeb">
<img width="400" alt="Screenshot 2024-06-03 at 11 14 10" src="https://github.com/tailscale/tailscale/assets/2159081/b2f82aa4-be33-404e-9939-539e1d3f8575">

So I expect it is not 100% problem in Tailscale, but more probable incompatibility with some provider setup.

When everything works
```
traceroute 1.1.1.1
traceroute to 1.1.1.1 (1.1.1.1), 64 hops max, 40 byte packets
 1  192.168.2.254 (192.168.2.254)  19.683 ms  19.367 ms  18.816 ms
 2  195-190-228-113.fixed.kpn.net (195.190.228.113)  36.022 ms  33.611 ms  41.404 ms
 3  * * *
 4  * * *
 5  141.101.65.14 (141.101.65.14)  40.587 ms
    141.101.65.115 (141.101.65.115)  40.714 ms
    141.101.65.93 (141.101.65.93)  43.455 ms
 6  one.one.one.one (1.1.1.1)  45.746 ms  35.606 ms  36.989 ms
```

When network is unresponsive
```
traceroute 1.1.1.1
traceroute to 1.1.1.1 (1.1.1.1), 64 hops max, 40 byte packets
 1  192.168.2.254 (192.168.2.254)  93.035 ms  65.487 ms  24.741 ms
 2  195-190-228-113.fixed.kpn.net (195.190.228.113)  4814.084 ms  3194.165 ms *
 3  * * *
 4  * * *
 5  * * 141.101.65.113 (141.101.65.113)  4245.241 ms
 6  * * *
 7  * * *
 8  * * *
 9  * one.one.one.one (1.1.1.1)  3887.302 ms  4242.512 ms
```

**Comment by qoega** [comment]
Hi. More diagnostics.
Do you have any dns cache logic that tries to resolve some list of previously used endpoints? I have seen really hard issues over previous days when I was waking up laptop or connecting to tailscale. Network was down. But then I had to reboot and it stopped reproducing - I still see latency increase of pings on connect/wake, but not as bad as was before update. I do not expect something to be updated so I start to suspect some sort of caching that leads to DNS DDOS on some local level.

When it happens I can see in router logs something like
```
Error | PPPOE | Connection has been terminated: remote station is not answering to LCP Echo requests.
SYS | TR-069 connectivity to (hengelo0.cust.kpn.net) has failed

```

**Comment by kelivel** [comment]
Customer provided information that revealed this was caused by a third-party software.

**Comment by qoega** [comment]
It should not lead to such issues anyway. All other applications do not lead to such issues and it is only on tailscale side possible to fix the load that leads to DDoS of client hardware

**Comment by kwargs** [comment]
> Customer provided information that revealed this was caused by a third-party software.

I'm with colleges affected by similar issue.
Could you provide any details or recomendation how to find such software?

**Comment by qoega** [comment]
From me no other software is involved. It was just closed without solution. Issue remains

**Comment by agottardo** [comment]
@kwargs @qoega

This problem is better addressed by discussing privately with our support team: we need to look at logs from other processes on your system. Please follow these steps:

1. Make sure you're running the Standalone variant of the Tailscale app (not the App Store one).
2. Generate a macOS Configuration Report with extended logging enabled (Settings > About > Report an Issue).
3. Provide the generated archive to our support team. Reference this GitHub issue in your support ticket. Do NOT upload that archive here on GitHub: it will most likely contain confidential information about your Mac and the software it is running.
