### ISSUE TITLE
Sometimes-misleading error message in tsnet when enabling https serving

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#12303]
### What is the issue?

A customer ran into an issue with the error message
```
tsnet: you must enable HTTPS in the admin panel to proceed. See https://tailscale.com/s/https
```

Looking at the underlying implementation, MagicDNS is also required so tsnet should mention that in the error message.

### Steps to reproduce

Attempt to use tsnet https serving on a tailnet with HTTPS enabled but MagicDNS disabled

### Are there any recent changes that introduced the issue?

No

**Comment by SequoiaGod** [comment]
@sailorfrag Hi mate, would it be possible to assign this issue to me? By the way, It seems like only need mention MagicDNS in the error message, is that correct?

**Comment by sailorfrag** [comment]
> @sailorfrag Hi mate, would it be possible to assign this issue to me? By the way, It seems like only need mention MagicDNS in the error message, is that correct?

Ideally it would check if MagicDNS is enabled or not, and then have a separate error for that. Otherwise, yeah mentioning it in the existing error message will probably suffice. The goal is to make it so that people can solve this problem themselves (it's easy once you know where to look) without having to wait for an answer from support.

**Comment by SequoiaGod** [comment]
@sailorfrag 
Hi mate, I added a separate error for the condition when the HTTPS is enabled, but MagicDNS was disabled. Hope this change will meet your requirements. I also have a quick question that I found out the issuebot workflow in my PR failed, does it matters?
