### ISSUE TITLE
No response when clicking login via Tailscale window icon

### ISSUE THREAD

**Issue by Zerodusk92** [tailscale/tailscale#12300]
### What is the issue?

nothing happen when i click login via the window icon below. 

running latest window 11 and latest tailscale 1.66.4

C:\Windows\System32>tailscale debug ts2021
14:21:25.863551 Fetching keys from https://controlplane.tailscale.com/key?v=95 ...
14:21:26.405164 Do: Get "https://controlplane.tailscale.com/key?v=95": tls: failed to verify certificate: x509: certificate signed by unknown authority
Get "https://controlplane.tailscale.com/key?v=95": tls: failed to verify certificate: x509: certificate signed by unknown authority

have tried uninstall and installing multiple times

### Steps to reproduce

Install tailscale and click login

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.66.1

### Bug report

BUG-c6a398f279bf661800a0414bb2e595b73673cc69eb126bc7b96c2d680c2f87a1-20240531063151Z-d62b9e010562cbfa

**Comment by bradfitz** [comment]
Looks like something's intercepting your TLS connections. That could be software on your machine (either security software or malware) or the network you're on. Is this a corp environment? Does the wifi have a captive portal?

**Comment by Zerodusk92** [comment]
i have tried switching the network to my mobile network, also tried uninstalling my PIA VPN but still having the same issue

**Comment by Zerodusk92** [comment]
update: it suddenly work now that im home with my home network
