### ISSUE TITLE
Calls in messaging apps like signal and telegram aren't connecting.

### ISSUE THREAD

**Issue by scientiac** [tailscale/tailscale#12317]
### What is the issue?

When I am using Tailscale on my De-googled android (Lineage OS) I am experiancing that I cannot cnnect to the calls (neither calling or recieving) I have tested it with signal and telegram.

When I get a call it says 'connecting' and I cannot pick it up, the picking buttons never show up on signal. On, telegram I can pick the call but when I pick the call it'll be stuck on 'connecting'.

I installed turbo vpn and tested with that being on which didn't have a problem, which makes me sure that vpn in general isn't the problem.

### Steps to reproduce

Enable tailscale on android.
Try calling via signal or telegram.

(I have a degoogled OS with lineage os running)
The calls work fine when tailscale is turned off.

### Are there any recent changes that introduced the issue?

I just updated to android 14.

### OS

Android

### OS version

14

### Tailscale version

version 1.66.3-teae73f821-g63a2bbc8e71 com.tailscale.ipn

### Other software

I am not using any other service.

### Bug report

BUG-e633234b90553f4a16e961db03826d11ed87edd66f4db0f6804b3923f3276486-20240601154108Z-a56c3b2e730587b8

**Comment by agottardo** [comment]
Are you using an exit node when this happens?

**Comment by scientiac** [comment]
No I am not using my android as an exit node.

**Comment by agottardo** [comment]
I didn't ask whether you're running an exit node on your phone, I just wanted to know if you're using an exit node. We fixed a bug related to UDP traffic over exit nodes recently, which might be related to this. The fix is already deployed in the beta version and you'll get it in 1.68 when it ships.

**Comment by scientiac** [comment]
No I am not running an exit node on any of my device.

**Comment by agottardo** [comment]
Fixed in 1.68.x.
