### ISSUE TITLE
DNS issue on self build arm64 android binary

### ISSUE THREAD

**Issue by anasfanani** [tailscale/tailscale#12326]
### What is the issue?

All function is fine except dns.
Running in android root, dns can't set because no `/etc/resolv.conf`.
```
2024/06/03 00:28:27 health("dns-os"): error: open /etc/resolv.conf: no such file or directory
2024/06/03 00:28:27 health("overall"): error: dns-os: open /etc/resolv.conf: no such file or directory
2024/06/03 00:28:27 health("dns"): error: open /etc/resolv.conf: no such file or directory
```

### Steps to reproduce

Build with ndk
Install, Run.

### OS

Android

### OS version

Android 13

### Tailscale version

1.66.4-dev20240603

### Other software

1.66.4-dev20240603
  tailscale commit: 7827217e24077a78b17125f5d9fd50ccb6df34d3
  go version: go1.22.3

### Bug report

BUG-89327a79b36cc2276e8304c138f3a0fd8f077eff1e6995aab1d4d771b7bd08d2-20240603005505Z-d1b32d05963fc60b
```[tasklist]
### Tasks
```

**Comment by bradfitz** [comment]
This repo doesn't have an Android implementation of the Tailscale DNS manager interfaces. Those are implemented in Java/Kotlin in the tailscale-android repo and registered with this repo. They necessarily require Binder calls and such.

**Comment by anasfanani** [comment]
Some android device also doesnt work well without /etc/resolv.conf while use -tun=tailscale0, after start daemon, log message show network  unreachable because /etc/resolv.conf issue.

My android rooted with Magisk, can't directly edit/modify system files, so I try link /data/local/tmp/etc/resolv.conf to /etc/resolv.conf , connection works but in logs keep showing error cant edit file /etc/resolv.conf 

Is there any setting for this ?

**Comment by bradfitz** [comment]
We regret to inform you that we do not support custom Android builds or nonstandard Android environments. Our support is limited to the APK provided. However, as our project is open source, feel free to explore and modify it as you wish. Have fun!
