### ISSUE TITLE
windows: make the service just be open source tailscaled(.exe)

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1232]
Currently the Windows system tray app is the same binary as the Windows service, which is just linking in the same open source code as cmd/tailscaled.

We should separate the closed-source GUI app into its own binary which is only that helper GUI thing and make the Windows service just be stock cmd/tailscaled binary code.

Because Windows binaries are marked in the PE header as either a GUI vs console binary, this also means we can run the tailscaled.exe on Windows much easier without the `start /w tailscale-ipn.exe` business that messes up shell redirection, etc.

It also makes it easier for people to hack on tailscaled on Windows, not worrying about the slight differences between the two.

/cc @alexbrainman @peske

**Comment by bradfitz** [comment]
Wheee...

<img width="1185" alt="Screen Shot 2021-02-05 at 10 36 47 AM" src="https://user-images.githubusercontent.com/2621/107074862-2d73f580-679e-11eb-8726-e3b27a1055bb.png">

**Comment by alexbrainman** [comment]
@bradfitz how do I install tailscaled.exe on a new PC? What is the plan for that?

Thank you.

Alex

**Comment by bradfitz** [comment]
What do you mean "install"? The service installation? That's still done via tailscale-ipn.exe for now. Feel free to move that into tailscaled.exe if you think that'd be more convenient.

**Comment by alexbrainman** [comment]
> What do you mean "install"? The service installation? 

Correct. Service needs to be installed before you can run it. Similarly when you want to stop using the service, you have to uninstall it.

> That's still done via tailscale-ipn.exe for now.

I assumed that tailscaled.exe user is not supposed to have access to tailscale-ipn.exe.

> Feel free to move that into tailscaled.exe if you think that'd be more convenient.

I will try.

Alex

**Comment by bradfitz** [comment]
Go for it. It's not a critical piece to move (it's easy for users to do by hand, and they don't need a service installed to hack on tailscaled.exe locally), but it's also fine if we move that.

**Comment by alexbrainman** [comment]
@bradfitz

If we want tailscaled be able to install and uninstall itself as a service, we need to provide some way for user to invoke these actions from tailscaled executable.

I looked at the source code, and it is a mixed bag of command line parameters.

For example, it has bunch of flags, like `-verbose` and `-version`. But `-version` prints tailscaled version and exits, while `-verbose` changes tailscale process setting.

There are also `debug` and `/subproc`. These 2 commands are not documented.

We can add `-install`, or `/install` or `install`. Similarly for uninstall. These commands need to be documented. If we make them as flags, `-install` and `-uninstall`, then we can document them in flag definition strings.

What do you propose we do here? Should we rearrange all commands instead?

Thank you.

Alex.
