### ISSUE TITLE
tailscale-operator: DNS server created by `DNSConfig` returns NOTIMP for AAAA records

### ISSUE THREAD

**Issue by embik** [tailscale/tailscale#12321]
### What is the issue?

(this is a continuation of me testing out the next and experimental internal DNS resolver feature; #12230 was the first issue I ran into)

I noticed that the DNS server created with `DNSConfig` (from the `tailscale/k8s-nameserver` image) returns `NOTIMP` when queried for IPv6 DNS (AAAA) records:

```sh
$ nslookup -type=aaaa zitadel.<tailnet>.ts.net 10.98.70.25
Server:		10.98.70.25
Address:	10.98.70.25:53

** server can't find zitadel.<tailnet>.ts.net: NOTIMP

$ nslookup -type=a zitadel.<tailnet>.ts.net 10.98.70.25
Server:		10.98.70.25
Address:	10.98.70.25:53

Name:	zitadel.<tailnet>.ts.net
Address: 10.244.1.16
```

I understand that IPv6 is currently not supported and that "not implemented" is technically correct in advertising that fact, but it seems to me that this creates problems for applications running in the Kubernetes cluster querying both `AAAA` and `A` records to determine which IP address to use. Cluster operators (like me) do not always have full control over this (example: I'm trying to get a node.js application running that has to talk to a service exposed via this feature, but it seems I cannot restrict it to do only `A` record lookups).

Be aware that my Kubernetes cluster isn't IPv6 or dual stack. It's IPv4 only for the pod and service CIDRs.

It seems to me that some frameworks look up both `AAAA` and `A`. Since a DNS server might not be offering any IPv6 entries, the `AAAA` list would be empty and the application would use the `A` records. This is also the behaviour of Kubernetes' default CoreDNS:

```sh
$ nslookup -type=a kubernetes.default.svc.cluster.local 10.96.0.10
Server:		10.96.0.10
Address:	10.96.0.10:53

Name:	kubernetes.default.svc.cluster.local
Address: 10.96.0.1

$ nslookup -type=aaaa kubernetes.default.svc.cluster.local 10.96.0.10
Server:		10.96.0.10
Address:	10.96.0.10:53

# (empty response here, but no error)
```

It seems to me that the `NOTIMP` error (instead of an empty response) is tripping up the node.js application I'm trying to get running, and I could not find a way to force it into IPv4-only queries. Would it be possible to properly return on `AAAA` queries and just don't offer any entries for the queried names?

### Steps to reproduce

Deploy tailscale-operator 1.66.3 with the following values:

```yaml
operatorConfig:
  hostname: "raspi"
apiServerProxyConfig:
  mode: "noauth"
```

Create a DNS config:

```yaml
apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: ts-dns
spec:
  nameserver:
    image:
      repo: tailscale/k8s-nameserver
      tag: unstable
```

Expose some `Ingress` resources via that DNS server and query that name.

### OS

Linux

### OS version

Debian GNU/Linux 12 (bookworm)

### Tailscale version

1.66.3

### Other software

- Kubernetes 1.27.13, deployed with KubeOne 1.7.3
- CNI: Canal (Flannel v0.21.3, Calico v3.26.3)

### Bug report

BUG-87f57f70fd6d04359b0a4287c0bd348488b099cf0b41268e5838f28ed75c7518-20240602102246Z-72c5a20be40dbcb2

**Comment by irbekrm** [comment]
Thanks for opening the issue @embik .

I agree, looking at https://datatracker.ietf.org/doc/html/rfc4074 (and a similar issue by weave folks https://github.com/weaveworks/weave/pull/2252) it seems like we should:

- for AAAA queries for DNS names that we have an A record for, we should return NOERROR + empty response

- for AAAA queries for DNS names that we don't have an A record for, we should return NXDOMAIN (because we are an authoritative nameserver, same behaviour as we currently have for A record queries)

(And, we should add support for IPv6, but this seems like a quicker fix till we do that).

**Comment by irbekrm** [comment]
Thanks for opening the issue @embik (and thank you for your continuous feedback!) , hopefully #12412 was a sufficient fix for the IPv6 issue for now.

I've cut a new dev operator release with this change (Helm chart version `1.67.114`, image version `unstable-v1.67.114`). Do let us know if this works

**Comment by embik** [comment]
@irbekrm works like a charm! Thank you so much for looking into this and fixing it. The feature is amazing, I'm really blown away by Tailscale in general :)
