### ISSUE TITLE
MagicDNS should have PTR records for tailscale service machines

### ISSUE THREAD

**Issue by normanr** [tailscale/tailscale#1233]
MagicDNS should respond with PTR records for 100.100.100.100 and 100.101.102.103. It should also have A records for whatever hostnames are returned.

This would help any admins when they're looking at things like netstat to be able to find what those addresses are related to.

I tried looking up various forms of `hello.ipn.dev` (`hello-ipn-dev`, `hello.ipn.dev.beta.tailscale.net`, `hello-ipn-dev.tailscale.net.beta.tailscale.net`, etc) at 100.100.100.100, but nothing worked. Unexpectedly I discovered that `hello.ipn.dev` resolves perfectly fine using regular dns (which was a surprise to me).

**Comment by apenwarr** [comment]
The most likely fix for this will be that hello.ipn.dev will be renamed. We ended up not using the ipn.dev domain for anything else.

**Comment by normanr** [comment]
Note that doesn't fix PTR requests for 100.100.100.100

**Comment by normanr** [comment]
From #4361:
> * ~Should we provide a PTR record for `100.101.102.103` (hello) as well? Afaict its optional?~ Already works thanks to the existing PTR implementation for nodes on the tailnet

Note: Reverse lookup for `100.101.102.103` doesn't work for me (maybe because the node is external?). Nor do PTR requests for ip6.arpa records for IPv6 addresses for nodes that are on my tailnet.

**Comment by twitchyliquid64** [comment]
Do you have [`hello.ts.net`](https://tailscale.com/kb/1073/hello/) as part of your tailnet? Thats what `100.101.102.103` is meant to map to, but i don't think the hello service is added to tailnets by default (so if you haven't added it it won't show up).

What command are you using to reverse-lookup on ipv6? For instance this works for me (this is the ipv6 service IP), (if I'm running a tailscaled binary that includes #4361):

```shell
[xxx@tslptp:~]$ dig -x 'fd7a:115c:a1e0::53'

; <<>> DiG 9.16.27 <<>> -x fd7a:115c:a1e0::53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2018
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;3.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. IN PTR

;; ANSWER SECTION:
3.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 600 IN PTR magicdns.localhost-tailscale-daemon.

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Sat Apr 09 08:52:41 PDT 2022
;; MSG SIZE  rcvd: 211
```

**Comment by normanr** [comment]
I have `hello` listed at https://login.tailscale.com/admin/machines, but it's addresses are different:
```
Tailscale IPv4: 100.101.102.103
Tailscale IPv6: fd7a:115c:a1e0:ab12:4843:cd96:6265:6667
```

Based your snippet above, `fd7a:115c:a1e0::53` is the IPv6 address for `magicdns`, and it looks like #4361 only handled records for `magicdns`, not `hello`.

I was testing with `1.22.2`, which looks like it doesn't include #4361. It's hard to tell because the commits listed by `tailscale --version` (`tailscale commit: 60b67195554487df2b40d49ad8bfc77f8c734b4e, other commit: ecc5d9846cc040f4443e7b12e6dc1b2b4c7ef994`) don't appear in the tailscale git commit history anywhere.

`1.23.144` (the latest unstable) doesn't seem to have the changes either (it only has `tailscale commit: 6fecc16c3b49b3b0cb1d71cae541823c1c038807, other commit: 06cb12c79aab655874e4debf5d69ed3177be11b0`). It seems to produce similar results to `1.22.2` (not too surprising if it doesn't include #4361).

Does `dig -x fd7a:115c:a1e0:ab12:4843:cd96:6265:6667` work for you? What about with the IPv6 address of other nodes?

**Comment by bradfitz** [comment]
> tailscale commit: 60b67195554487df2b40d49ad8bfc77f8c734b4e don't appear in the tailscale git commit history anywhere

That's a tagged commit:

```
bradfitz@tsdev:~/src/tailscale.com$ git rev-parse v1.22.2
60b67195554487df2b40d49ad8bfc77f8c734b4e
bradfitz@tsdev:~/src/tailscale.com$ git cat-file -p v1.22.2
object 6f700925cef22d8b2a100840c8d9eb084dadfece
type commit
tag v1.22.2
tagger Denton Gentry <dgentry@tailscale.com> 1647567624 -0700

Release 1.22.2

$ git show 60b67195554487df2b40d49ad8bfc77f8c734b4e
tag v1.22.2
Tagger: Denton Gentry <dgentry@tailscale.com>
Date:   Thu Mar 17 18:40:24 2022 -0700

Release 1.22.2

commit 6f700925cef22d8b2a100840c8d9eb084dadfece (tag: v1.22.2, origin/release-branch/1.22)
Author: Denton Gentry <dgentry@tailscale.com>
Date:   Thu Mar 17 18:40:04 2022 -0700

    VERSION.txt: this is v1.22.2
    
    Signed-off-by: Denton Gentry <dgentry@tailscale.com>

diff --git a/VERSION.txt b/VERSION.txt
index 6245beec..6fee2fed 100644
--- a/VERSION.txt
+++ b/VERSION.txt
@@ -1 +1 @@
-1.22.1
+1.22.2
```

Maybe you didn't have that ref pulled locally?

**Comment by DentonGentry** [comment]
The VERSION.txt commits which appear in `tailscale version` only exist in `release-branch/1.22`, not in `main`

**Comment by bradfitz** [comment]
I filed https://github.com/tailscale/tailscale/issues/4439; let's move discussion there for the remaining pieces.

**Comment by normanr** [comment]
I was just trying `https://github.com/tailscale/tailscale/commit/60b67195554487df2b40d49ad8bfc77f8c734b4e` which shows a 404.

I tried `1.23.207` and still get no reply for `hello`:
```
$ dig +short -x 100.100.100.100
magicdns.localhost-tailscale-daemon.
$ dig +short -x 100.101.102.103
$
```

I note that I don't see `hello` in `tailscale status` or `ip route` either:
```
$ tailscale status
localip4   localmachinename            normanr@     linux   -
... 4 other machines ....
$ ip route ls table tailscale
100.100.100.100 dev tailscale0
... 4 other machines ....
```

So unsurprising https://hello.ts.net/ doesn't load (but I remember it worked previously when I tested it after I first signed up).

I also tried to remove `hello` from my tailnet, and re-add it via the invite link at https://tailscale.com/kb/1073/hello/. I haven't changed my tailnet's Access Controls, they're just the default.

**Comment by normanr** [comment]
I did not. It is still listed at https://login.tailscale.com/admin/machines as:

| MACHINE | IP | OS | LAST SEEN |    |
| ------- | -- | -- | --------- | --- |
| hello (?) |  100.101.102.103 | Linux | Connected | ... |
| services@tailscale.com |  |  1.18.2 | |
| [External] [No expiry] |
