### ISSUE TITLE
Version upgrade issue

### ISSUE THREAD

**Issue by shenmadouyaowen** [tailscale/tailscale#12340]
### What is the issue?

Uninstalled and reinstalled, but the version still shows 1.66.0
Ubuntu 20.04.6 LTS
![image](https://github.com/tailscale/tailscale/assets/12426724/6cdd0c38-4d18-49f4-a9bb-48e471db7fa3)

### Steps to reproduce

When you use other commands, it prompts that the version is too low. When you upgrade, it prompts that you are already the latest version. Even after uninstalling and reinstalling, it still remains the same

**Comment by timtailscale** [comment]
This error occurs when Tailscale is updated, but the update process doesn't restart the `tailscaled` process to update to the newer version. Did you update using `tailscale update`, or via `apt`?

**Comment by shenmadouyaowen** [comment]
> This error occurs when Tailscale is updated, but the update process doesn't restart the `tailscaled` process to update to the newer version. Did you update using `tailscale update`, or via `apt`?

Both commands were used, and in the end, reinstalling and restarting resolved the issue
