### ISSUE TITLE
tailscale status -web causes issues for tailscale status on Nth execution

### ISSUE THREAD

**Issue by normanr** [tailscale/tailscale#1234]
After starting `tailscale status -web` you can only run `tailscale status` 32 times. On the 33rd run it hangs until `tailscale status -web` is terminated.

1. run `tailscale status -web`
2. run `tailscale status` 32 times,
3. run `tailscale status` again, it waits forever
4. terminate `tailscale status -web` to complete the previous command

 - OS: [e.g. Windows, MacOS]
 - OS version: Linux 5.6 x86_64 and 5.4 armv6l (RPi0w)
 - Tailscale version: 1.4.1
   - tailscale commit: dde7ba4ecfa6dd044255047c9e8157448d6eba4a
   - other commit: b807661ab78812520d9979ddb1e07b834e04114b
   - go version: go1.15.7-ts02f50cd

**Comment by bradfitz** [comment]
Hah. I can't wait to debug this one.

**Comment by Smittyvb** [comment]
It seems the number of repeats needed is random to some extent. When I tried this it took me 45 tries to before `tailscale status` would lock up.

**Comment by normanr** [comment]
That doesn't surprise me. Initially I thought it might be related to the listen socket backlog, but i don't think it is. I tried changing how quickly I ran the status commands, and it didn't seem to change how many times it needed to run to get stuck. The ipnserver code has some comments that mention locking, but I'm not sure if those bits of code are the cause or not.

**Comment by bradfitz** [comment]
Thanks for the report!

Couple problems.

tailscaled supports multiple clients subscribed to the event bus (e.g. tailscale status + tailscale status -web), but tailscaled block forever (while holding a mutex) when writing to clients. So if a client isn't reading from the bus and is blocked, the server locks up:

```
goroutine 128 [semacquire, 1 minutes]:
sync.runtime_SemacquireMutex(0xc000180f8c, 0x98ae00, 0x1)
        /home/bradfitz/sdk/go1.15/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000180f88)
        /home/bradfitz/sdk/go1.15/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /home/bradfitz/sdk/go1.15/src/sync/mutex.go:81
tailscale.com/ipn/ipnserver.(*server).writeToClients(0xc000180f60, 0xc000922000, 0x12f9a, 0x14000)
        /home/bradfitz/src/tailscale.com/ipn/ipnserver/server.go:464 +0x22f
tailscale.com/ipn.(*BackendServer).send(0xc00020a9c0, 0xc52b70, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc00052a240, 0x0, 0x0, ...)
        /home/bradfitz/src/tailscale.com/ipn/message.go:113 +0x222
tailscale.com/ipn.(*LocalBackend).send(0xc00045e000, 0xc52b70, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc00052a240, 0x0, 0x0, ...)
        /home/bradfitz/src/tailscale.com/ipn/local.go:711 +0xd8
tailscale.com/ipn.(*LocalBackend).setClientStatus(0xc00045e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00032e180, 0xc00052a240, 0x0, 0x5)
        /home/bradfitz/src/tailscale.com/ipn/local.go:353 +0x485
tailscale.com/control/controlclient.(*Client).sendStatus(0xc0004622a0, 0xc597c2, 0x15, 0x0, 0x0, 0x0, 0x0, 0xc00052a240)
        /home/bradfitz/src/tailscale.com/control/controlclient/auto.go:646 +0x347
tailscale.com/control/controlclient.(*Client).mapRoutine.func2(0xc00052a240)
        /home/bradfitz/src/tailscale.com/control/controlclient/auto.go:541 +0x1de
tailscale.com/control/controlclient.(*Direct).sendMapRequest(0xc00045e1c0, 0xd42c40, 0xc000260700, 0xffffffffffffffff, 0xc000523eb0, 0x0, 0x0)
        /home/bradfitz/src/tailscale.com/control/controlclient/direct.go:845 +0x2539
tailscale.com/control/controlclient.(*Direct).PollNetMap(...)
        /home/bradfitz/src/tailscale.com/control/controlclient/direct.go:530
tailscale.com/control/controlclient.(*Client).mapRoutine(0xc0004622a0)
        /home/bradfitz/src/tailscale.com/control/controlclient/auto.go:512 +0x573
created by tailscale.com/control/controlclient.(*Client).Start
        /home/bradfitz/src/tailscale.com/control/controlclient/auto.go:202 +0x65
```

Second problem, but lesser: tailscale status -web should be reading all the time.

Some upcoming "local API" changes will mean `tailscale status` (in either CLI or web mode) won't need to use the subscribe-to-the-event-bus mode at all, though.

**Comment by bradfitz** [comment]
Btw, it's not 33rd for me. It's more like 3 or 4. It depends on the size of your network.
