### ISSUE TITLE
Tailscale ping status is abnormal

### ISSUE THREAD

**Issue by JacobLi11** [tailscale/tailscale#12374]
### What is the issue?

I pinged my destination directly in the tailscale pod, and the communication was normal. But I ping the target through tailscale and cannot communicate
![image](https://github.com/tailscale/tailscale/assets/109325689/86b3127e-84fe-483c-bc0b-8841df023e0a)
tailsclae client log
![image](https://github.com/tailscale/tailscale/assets/109325689/7925c416-bd9e-44a0-8cfb-29b8e0d72c45)

### Steps to reproduce

Not yet

### OS

Linux

**Comment by bradfitz** [comment]
There's not enough information to help you debug anything here.

But from that IP address I suspect you're using Headscale and a custom DERP server, neither of which we're qualified nor resourced to help support in this forum.

I think you should probably ask in a Headscale forum.

**Comment by JacobLi11** [comment]
> There's not enough information to help you debug anything here.
> 
> But from that IP address I suspect you're using Headscale and a custom DERP server, neither of which we're qualified nor resourced to help support in this forum.
> 
> I think you should probably ask in a Headscale forum.

Thanks~
