### ISSUE TITLE
control, admin UI: "1 minute ago" and "less than a minute ago" mixed & updating are distracting

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1237]
This is my current admin panel's "last seen" column:

<img width="252" alt="Screen Shot 2021-01-30 at 6 57 05 PM" src="https://user-images.githubusercontent.com/2621/106373307-12802c00-632d-11eb-86bc-99f83bc94d02.png">

There is no semantic difference between "less than a minute ago" and "1 minute ago", yet even now as I'm watching this page, it keeps flip flopping between those two labels seemingly randomly. Here's one with "2 minutes ago" that showed up for a second and then changed to "less than a minute ago", but mostly they're flipping between "last than a minute" and "1 minute":

<img width="265" alt="Screen Shot 2021-01-30 at 6 59 21 PM" src="https://user-images.githubusercontent.com/2621/106373323-452a2480-632d-11eb-82bc-1fd22fc0db2d.png">

Anything under 5 minutes should probably just say "connected" or something.

Or really: the control server knows who's connected, so it could map "under N minutes + connected" to a very recent last seen date.

/cc @rosszurowski @crawshaw

**Comment by rosszurowski** [comment]
Mm, this is a good bug to call out. It's what I was mentioning in https://github.com/tailscale/corp/issues/1217#issuecomment-766429598:

>  I'm hoping to revise the "last seen" timestamp to be more helpful anyways. It's a pretty low signal-to-noise ratio right now, and customers I've spoken with say they use it primarily to tell if a device is online. I think we probably want to convert it to an indicator (with text) with a few buckets instead (<1 min, <5min, <1h, <6h, <1 day, <3 days, <7 days, <2 weeks, <1 month, <3 months, <6 months, I'll post in #eng to debate specifics). We can surface the actual timestamp in a tooltip instead.

**Comment by rosszurowski** [comment]
The latest update to the admin panel introduces a new "connected" status that should make this much more clear. Closing out this issue, but feel free to re-open if this approach doesn't completely cover the intended bug.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/303731/109094997-ec119e80-76e8-11eb-80b3-7aa7d4127c88.png">
