### ISSUE TITLE
FR: Mullvad availability for Uruguay

### ISSUE THREAD

**Issue by gabrielrinaldi** [tailscale/tailscale#12378]
### What are you trying to do?

Use Mullvad VPN service with servers in Uruguay

### How should we solve this?

Add availability for Uruguay. [I could not find on Mullvad's site any servers in Uruguay](https://mullvad.net/en/servers).

### What is the impact of not solving this?

Uruguayan users have a big latency when connecting, making most servers unusable.

**Comment by bradfitz** [comment]
Sorry, you would have to ask Mullvad for this. We are 100% uninvolved with where Mullvad puts its servers.
