### ISSUE TITLE
FR: Tapping on android notification should open the app

### ISSUE THREAD

**Issue by Birdheezy** [tailscale/tailscale#12376]
### What are you trying to do?

When the notification is displayed on my android phone, I'd like to tap on it and be taken into the app.

### How should we solve this?

a tap on the notification should open the app

### What is the impact of not solving this?

longer navigation to the app

### Anything else?

Great work! I love this product!

**Comment by agottardo** [comment]
Fixed in the current beta version, fix will roll out to everyone in the next stable release.
