### ISSUE TITLE
FR: Mullvad availability for Argentina

### ISSUE THREAD

**Issue by gabrielrinaldi** [tailscale/tailscale#12380]
### What are you trying to do?

Use Mullvad VPN service with servers in Argentina

### How should we solve this?

Add availability for Argentina. [I could not find on Mullvad's site any servers in Argentina](https://mullvad.net/en/servers).

### What is the impact of not solving this?

Argentinian users have a big latency when connecting, making most servers unusable.

**Comment by bradfitz** [comment]
We don't have influence over where Mullvad runs their servers. I'd recommend contacting Mullvad to let them know.
