### ISSUE TITLE
FR: Sharing of subnet's to external user

### ISSUE THREAD

**Issue by edenhome** [tailscale/tailscale#12392]
### What are you trying to do?

Trying to share subnet to external user, for use with devices where its imposible to install talesacle

### How should we solve this?

add a selection to allow subnet's to be shared

### What is the impact of not solving this?

Tailscale is not usable for sharing remote devices to external service enginers that need to access devices without tailscale installes

**Comment by agottardo** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/1390
