### ISSUE TITLE
GUI: Mullvad Exit Nodes show up in tagged devices list

### ISSUE THREAD

**Issue by sloane-ts** [tailscale/tailscale#12405]
### What is the issue?

On Windows and macOS, TS version 1.66.4, Mullvad exit nodes display in the Tailscale GUI under the tagged nodes section in addition to Exit Nodes section > Mullvad VPN

### Steps to reproduce

1. Open GUI
2. Select "Network Devices"
3. Scroll to and select "Tagged nodes"
4. Mullvad exit nodes display here along with tailnet's tagged nodes

### OS

macOS, Windows

### OS version

Win 10&11, macOS 14.5.0

### Tailscale version

1.66.4

**Comment by nickkhyl** [comment]
Fixed on Windows: https://github.com/tailscale/corp/issues/21982

@agottardo: would you like to keep this open for macOS?

**Comment by agottardo** [comment]
@nickkhyl this has been fixed on macOS as of v1.70.
