### ISSUE TITLE
k8s operator minor error string formatting bug

### ISSUE THREAD

**Issue by AdamJacobMuller** [tailscale/tailscale#12411]
### What is the issue?

`unable to provision proxy resources: invalid Service: only one of annotations %s and %s can be set, tailscale.com/tailnet-ip, tailscale.com/tailnet-fqdn`

missing a Sprintf somewhere

in the operator version v1.66.4

**Comment by irbekrm** [comment]
Thanks for opening the issue! Marking as good first issue, in case someone wants to pick it up. There might be a couple more formatting issues in the operator logs.
https://github.com/tailscale/tailscale/tree/main/cmd/k8s-operator

**Comment by SequoiaGod** [comment]
Hi mate, 
@irbekrm Can you assign this issue to me for my 2nd contribution to tailscale?

**Comment by SequoiaGod** [comment]
@irbekrm  Good afternoon mate, it has already for reviewed now. I appreciate it for assigning this issue to me.
