### ISSUE TITLE
Tailscale DNS cannot correctly fallback to DNS-over-TCP on truncated response

### ISSUE THREAD

**Issue by Zocker1999NET** [tailscale/tailscale#12417]
### What is the issue?

In some cases, my upstream DNS server, which I have configured in the Tailscale UI, answers to a normal DNS/UDP A query for my own domain with the TrunCated bit set. (I do not know why, but assuming I interpret RFCs 1035 & 7766 correctly, the DNS server is allowed to behave like that.) Because of Tailscale's current DNS literal "forwarding" implementation, this can lead to following issue:

- Original client (C) sends a query `example.com A` to Tailscale (T) via UDP
- T 1:1 forwards the query to its configured upstream DNS (U) via UDP
- U answers to T with an empty answer but with the TrunCated flag set (via UDP)
- T 1:1 forwards the answer to C (via UDP)
- because C received an answer with the TrunCated flag set, C retries its query to T now via TCP
- T again 1:1 forwards the query to U, **but via UDP**
- U basically sends the same answer again, empty with TrunCated flag set (via UDP)
- T 1:1 forwards the answer (via TCP)
- C has no idea on how to continue because the TrunCated flag is not expected via TCP because no realistic upper limit is required

I have recorded this behavior in a Wireshark capture, which I do not want to publish. I can send it to Tailscale's support stuff directly.

### Steps to reproduce

(I do not why this can happen on a normal A query to me, but I have created a stable reproducing example, which I intend to keep online until this issue is resolved. Further, this issue is always reproducable with EDNS disabled on the original client side, probably because otherwise Tailscale can just forward the overlong answers correctly.)

0. prepare a DNS query where the answer will exceed the DNS maximum of 512 bytes per UDP query/response
	- e.g. `tailscale.banananet.work. 3600  IN      TXT     "resdxomsbdumnvcfqnkxraktxmhhrfakfmtncosscgpdvxrttdogbnwfgmqfkuxgqdbawdmdxrpendrqbggawfhcvwdsbacbppwxrnrxcosekkbgacnxwvddkxnvcbsqqcwdvkfhuubunoeoqxdeuxcxvtrpqvdcqfprtfmongobbvqefacsgvetvtocmrdkunkpgxgwbnekdsfoeodofncgeaodprfpcdaapwseopmmuvnswfuorhangn" "resdxomsbdumnvcfqnkxraktxmhhrfakfmtncosscgpdvxrttdogbnwfgmqfkuxgqdbawdmdxrpendrqbggawfhcvwdsbacbppwxrnrxcosekkbgacnxwvddkxnvcbsqqcwdvkfhuubunoeoqxdeuxcxvtrpqvdcqfprtfmongobbvqefacsgvetvtocmrdkunkpgxgwbnekdsfoeodofncgeaodprfpcdaapwseopmmuvnswfuorhangn"`
1. query Tailscale DNS for this problematic answer
	- e.g. `dig +noedns tailscale.banananet.work. TXT @100.100.100.100`

### Are there any recent changes that introduced the issue?

Not that I am aware of.

### OS

Linux

### OS version

Debian trixie/testing

### Tailscale version

1.66.4

### Other software

My local PC is running systemd-resolved, but the steps to reproduce explicitly try to evade systemd-resolved. The upstream DNS server in my case is a BIND9 instance I operate myself, however I think this is mostly irrelevant here as any DNS query could potentially lead to this behavior (the responding server answers with TrunCated flag set, expecting the client to retry via TCP).

Further note: I do not seek any technical support, I am aware of how I can workaround that behavior for me. I wrote this bug report because with my current understanding of the RFCs I think this is a faulty behavior by the current Tailscale implementation and may lead to problematic behavior in other scenarios.

### Bug report

BUG-e368c955bd989272e81f7d5dcd20010e4b61bd3dba0ccddb42aa9cd3b658a5f7-20240610220803Z-6ef8e36dbaa74d57

**Comment by XciD** [comment]
Up this one, we have the same issue. We are using magicdns for atlas mongo, and they add servers in SRV records, after N amount of servers, dns resolution wont work anymore.

**Comment by nickkhyl** [comment]
@Zocker1999NET, @XciD: can you please edit (or create) the [nodeAttrs](https://tailscale.com/kb/1337/acl-syntax#node-attributes-nodeattrs) section in the policy file to apply the `user-dial-routes` attribute, and see if that resolves the issue?
```
"nodeAttrs": [
    {
        "target": ["*"],
        "attr":   ["user-dial-routes"],
    },
],
```

**Comment by XciD** [comment]
Work perfectly well. Thanks @nickkhyl.

What side effect we can expect ?

**Comment by nickkhyl** [comment]
Slightly higher memory consumption, depending on the size of your tailnet. We’re talking about hundreds of KiB, even in moderately large tailnets. However, for example, iOS has [very low](https://developer.apple.com/forums/thread/73148?answerId=732711022#732711022) memory limits for network extensions, and it all adds up.

**Comment by Zocker1999NET** [comment]
@nickkhyl that works for me as well, thanks, this makes this issue’s workaround solution more bearable. I couldn’t find any documentation on what `user-dial-routes` changes, may you give a short insight or link to the corresponding code? (maybe this can help to develop a long-term fix for this issue)

**Comment by nickkhyl** [comment]
@Zocker1999NET:  the attribute changes the behavior of [`(*Dialer).UserDial`](https://github.com/tailscale/tailscale/blob/2e32abc3e23ac51fc9a437d0855b650b88cf781d/net/tsdial/tsdial.go#L421) to dial Tailscale and non-Tailscale routes differently.

This allows us to use `UserDial` instead of `SystemDial` for DNS-over-TCP. `SystemDial` cannot dial IPs that should be routed via Tailscale, which led to the issue you've observed with your internal upstream DNS server. From Tailscale's perspective, the server wasn't reachable over TCP.

Routing in `(*Dialer).UserDial` requires us to maintain a routing table, resulting in slightly higher memory consumption. We plan to merge it with a BART we have elsewhere to make this improvement GA. However, this requires additional plumbing as the two tables differ due to their different purposes, and we don't have any estimates to share at this time.
