### ISSUE TITLE
Subnet routes are leaked to machines that have no access to them via ACLs

### ISSUE THREAD

**Issue by farcaller** [tailscale/tailscale#12415]
### What is the issue?

(potentially a dup of #12218)

Subnet routes are leaked to machines that can't access those routes per ACLs but can access some services on the tailnet nodes that announce such rules. This causes issues with routing if those routes are reachable by other means for those nodes.

Tailsscale shouldn't inject routes if they aren't allowed to be routed to.

### Steps to reproduce

Have three nodes, A, B, C.

on A, advertise `10.224.1.0/24`
on B, advertise `8.8.8.8/32`

have the following ACL in place:

```
{
	"src":    ["*"],
	"dst":    ["A:53"],
	"action": "accept",
},
{
	"src":    ["tag:C"],
	"dst":    ["autogroup:internet:*"],
	"action": "accept",
},
```

expectation: C will have the route for `8.8.8.8/32` injected.
actual behavior: C has routes to both `10.224.1.0/24` and `8.8.8.8/32` injected.

### Are there any recent changes that introduced the issue?

N/A

### OS

Linux

### OS version

nixos unstable

### Tailscale version

1.66.4

### Bug report

BUG-1ca3c315ce832186ecf31d75a1fa0692c901437495b511fd3f783a07b8f4f07b-20240610154340Z-fae3bdedae701d59

**Comment by timtailscale** [comment]
Similar to #12218, we recently introduced subnet route trimming with the new [via grant routing](https://tailscale.com/blog/via) feature, so devices that don't have access to subnet routes will not be sent the routes that they cannot access. @farcaller can you confirm that you are still seeing the extra routes being setup on clients without access to them?

**Comment by farcaller** [comment]
Extra routes are now gone, as expected.
