### ISSUE TITLE
Unable to install Tailscale again after uninstallation

### ISSUE THREAD

**Issue by Phanledangdoan** [tailscale/tailscale#12433]
### What is the issue?

Unable to install Tailscale again after uninstallation

### Steps to reproduce

I uninstalled Tailscale, deleted it from every folder I can find. And now when I try to reinstall it I am told that it failed
because I already have it installed.

I even run a create point, but did not work
![chem](https://github.com/tailscale/tailscale/assets/92423043/7087b420-5491-4093-90f5-6ff44cd3ecfd)
![music](https://github.com/tailscale/tailscale/assets/92423043/0826516d-a4f1-4801-b93c-92beb8908400)

### Are there any recent changes that introduced the issue?

Uninstalling and installing are only changes leading to this issue.

### OS

Windows

### OS version

Window 11

### Tailscale version

1.66.4_2

### Other software

Nothing!!!!

**Comment by agottardo** [comment]
What's in the log file mentioned in the error message?

**Comment by Phanledangdoan** [comment]
Couldn't open log file!!!

https://photos.app.goo.gl/tAuy6WEpA3VRt6kr7

**Comment by Phanledangdoan** [comment]
Fresh installation

https://photos.app.goo.gl/hGUJ3xPfY42aFHk76

**Comment by kelivel** [comment]
Hi @Phanledangdoan, this is likely a configuration problem on the device and our Support team would be happy to take a look. Drop a line at http://www.tailscale.com/support to open a support ticket, and we'll get back with you soon with next steps.
