### ISSUE TITLE
netstack: could not connect to local server at 127.0.0.1:443: dial tcp 127.0.0.1:443: connect: connection refused

### ISSUE THREAD

**Issue by anandt-ini8labs** [tailscale/tailscale#12435]
### What is the issue?

I am using the tailscale k8s operator and following this tutorial to test tailscale with ingress
https://gist.github.com/clarkezone/f99ea7f0c08a4f0f7a2487cc73871b89

I am using kind cluster on macOS

### Steps to reproduce

Deploy k8s operator uisng the helm chart version `tailscale-operator-1.66.4`

apply this https://gist.githubusercontent.com/clarkezone/f99ea7f0c08a4f0f7a2487cc73871b89/raw/b8c9db34d6251d442fba39379c8bcdc7d62908e8/tsingresstest.yaml

### Are there any recent changes that introduced the issue?

NA

### OS

macOS

### OS version

MacOS Sonoma 14.5

### Tailscale version

1.66.4

**Comment by irbekrm** [comment]
Hi, I think this is similar to https://github.com/tailscale/tailscale/issues/12079

If anyone still has the setup that was failing, it would be good if you could provide us some extra info, see https://github.com/tailscale/tailscale/issues/12079#issuecomment-2330665018

**Comment by irbekrm** [comment]
I believe this should have been fixed in 1.78, see https://github.com/tailscale/tailscale/issues/12079#issuecomment-2558519112
