### ISSUE TITLE
4via6 routes advertised by 1.68.0 subnet routers unusable

### ISSUE THREAD

**Issue by keeleysam** [tailscale/tailscale#12448]
### What is the issue?

Using a 4via6 subnet route from any Tailscale client which is served by another peer running Tailscale 1.68.0, at least for HTTP/HTTPS TCP traffic, is not possible with identical configuration to 1.66.4.  All attempted connections end up getting reset, though ICMP does appear to work to those endpoints. Advertised IPv4 routes work fine.

### Steps to reproduce

Advertise a 4via6 route from one node, with a completely open ACL.   On 1.66.4 this works fine and is usable from the second node.  In this example, reaching a random google.com ipv4 endpoint via site id 123.
```
% curl -vI '[fd7a:115c:a1e0:b1a:0:123:8efa:bfae]'
*   Trying [fd7a:115c:a1e0:b1a:0:123:8efa:bfae]:80...
* Connected to fd7a:115c:a1e0:b1a:0:123:8efa:bfae (fd7a:115c:a1e0:b1a:0:123:8efa:bfae) port 80
> HEAD / HTTP/1.1
> Host: [fd7a:115c:a1e0:b1a:0:123:8efa:bfae]
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Thu, 13 Jun 2024 02:22:11 GMT
Date: Thu, 13 Jun 2024 02:22:11 GMT
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< 

* Connection #0 to host fd7a:115c:a1e0:b1a:0:123:8efa:bfae left intact
```

Update first node to 1.68.0. 

Attempts to use these routes will reset in connections getting reset by peer.  

```
% curl -vI '[fd7a:115c:a1e0:b1a:0:123:8efa:bfae]'
*   Trying [fd7a:115c:a1e0:b1a:0:123:8efa:bfae]:80...
* Connected to fd7a:115c:a1e0:b1a:0:123:8efa:bfae (fd7a:115c:a1e0:b1a:0:123:8efa:bfae) port 80
> HEAD / HTTP/1.1
> Host: [fd7a:115c:a1e0:b1a:0:123:8efa:bfae]
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
* Recv failure: Connection reset by peer
* Closing connection
curl: (56) Recv failure: Connection reset by peer
```

### OS

Linux

### OS version

Debian 13

### Tailscale version

1.68.0

**Comment by irbekrm** [comment]
Thank you for opening the issue.

I can reproduce this with a subnet router `v1.68.0` and both with a client at `1.66` as well as with a client at `1.68`
Downgrading the subnet router to `1.66.4` fixes the issue.

We'll take a look at fixing this.

**Comment by ch9hn** [comment]
Hello, 
we have similar issue, since today the Subnet Routes stopped working out of nowhere. 
All Subnet Router connections are not working anymore.

**Comment by ch9hn** [comment]
We installed the hotfix version 1.68.1, this fixed the issue.

**Comment by irbekrm** [comment]
Thank you for confirming!
