### ISSUE TITLE
Can not Tailscale SSH into hosts running older Tailscale with 1.68.0 as client - flag provided but not defined: `-login-cmd`

### ISSUE THREAD

**Issue by mikispag** [tailscale/tailscale#12444]
### What is the issue?

I am unable to Tailscale SSH into hosts  running older versions of Tailscale after updating the client to 1.68.0. When I SSH, I get:

```
flag provided but not defined: -login-cmd
Usage:
  -cmd string
    	the cmd to launch, including all arguments (ignored in sftp mode)
  -debug-test
    	should debug in test mode
  -force-v1-behavior
    	allow falling back to the su command if login is unavailable
  -gid int
    	the gid of local-user
  -groups string
    	comma-separated list of gids of local-user
  -has-tty
    	is the output attached to a tty
  -local-user string
    	the user to run as
  -login-shell string
    	path to the user's preferred login shell
  -remote-ip string
    	the remote Tailscale IP
  -remote-user string
    	the remote user/tags
  -sftp
    	run sftp server (cmd is ignored)
  -shell
    	is launching a shell (with no cmds)
  -tty-name string
    	the tty name (pts/3)
  -uid int
    	the uid of local-user
Connection to host closed.
```

While this behavior might be unavoidable, be aware that this forces users to update Tailscale on their machines and restart the systemd service or reboot their machines in order to be able to Tailscale SSH again into them. If they disabled `sshd` and they don't have other out-of-band ways to get into the machines to do that, they might be locked out.

### Steps to reproduce

1. Update Tailscale to 1.68.0 on the client.
2. `ssh host_running_older_tailscale`

### Are there any recent changes that introduced the issue?

Updating Tailscale to 1.68.0 on the client.

### OS

Linux

### OS version

Arch Linux

### Tailscale version

1.68.0

### Bug report

BUG-c7aba7848365629664aa7cf46d4b5f2d77f2d991532c8cd8399b8a63b1d6c303-20240612224107Z-49c6181f9ac57fd4

**Comment by jimmybrancaccio** [comment]
I was able to replicate this too on [Gentoo where the version is 1.66](https://packages.gentoo.org/packages/net-vpn/tailscale) at the moment.

**Comment by webshammo** [comment]
I am having this issue with 1.70.0, so I downgraded both client and server to 1.68.2 and I still get the same error.
`debug1: channel 0: new session [client-session] (inactive timeout: 0)
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: Sending environment.
debug1: channel 0: setting env LC_TERMINAL_VERSION = "3.5.2"
debug1: channel 0: setting env LANG = "en_US.UTF-8"
debug1: channel 0: setting env LC_TERMINAL = "iTerm2"
flag provided but not defined: -login-cmd
Usage:
  -cmd string`

**Comment by webshammo** [comment]
> I am having this issue with 1.70.0, so I downgraded both client and server to 1.68.2 and I still get the same error.
> 

I rebooted both systems and it works now.  Since I had ssh running, tailscale was still running older version even tho new version was installed.  Probably killing tailscale process would have fixed it.
