### ISSUE TITLE
Tailscale SSH broken on SELinux

### ISSUE THREAD

**Issue by cshei** [tailscale/tailscale#12442]
### What is the issue?

https://github.com/tailscale/tailscale/commit/08a9551a73adb220dc0ed1b71a2d5845efc754b8 appears to have removed some SELinux related workarounds and results in a "no shell: Permission denied" error when using Tailscale SSH to a Fedora 40 host.

### Steps to reproduce

Ssh to Fedora 40 machine (with default SELinux settings) using Tailscale SSH.  This fails with a "no shell: Permission denied" error.

### Are there any recent changes that introduced the issue?

Updated to 1.68

### OS

Linux

### OS version

Fedora 40

### Tailscale version

1.68.0

**Comment by oxtoacart** [comment]
Looking into this now.

**Comment by tswfi** [comment]
happens on rockylinux9 also.

ssh as root to the machine works.
as a regular user gives the `no shell: Permission denied` error

 `dnf downgrade tailscale` helps (well at least for a while until automatic updates update it back up :)

**Comment by andrewbenton** [comment]
I'm running into the same issue, also with Fedora 40 machines.  I've found that the workaround mentioned in #4908 where you use `tailscale ssh <host> -t /bin/bash` gets around the issue for now.

**Comment by oxtoacart** [comment]
The workaround should no longer be needed as of Tailscale 1.70.

**Comment by cshei** [comment]
@shawnyeager This bug has been fixed and it is still working for me on the exact same 1.72.1 version as you, so you are probably running into a different issue?

**Comment by shawnyeager** [comment]
@cshei Thanks. I suppose it could be a different (likely SELinux-related) problem.

**Comment by oxtoacart** [comment]
@shawnyeager can you please trigger the problem you're seeing, [generate a bug report](https://tailscale.com/kb/1227/bug-report) and share the bug report identifier with me?

**Comment by shawnyeager** [comment]
Thanks, @oxtoacart. It appears that it may be a power management related problem. I'll keep prodding on my end, and if I can't narrow it down to anything else, I'll submit a report.
