### ISSUE TITLE
Re-attempt systemd lockdown

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1245]
#1062 and #1071 tried to lock down our systemd unit for tailscaled, but we hit problems when rolling out Tailscale 1.4.

The first problem was not permitting /run for iptables, fixed by de497358b84f4b368ce9b637b98ea8899d6b337e

But then we found it didn't work at all on Debian 9 (Stretch), systemd 232.

So we're backing it out for now, and then we can re-add it later. Perhaps we'll need distro/version-specific unit files or something.

Tailscale 1.4.2 will be equivalent to Tailscale 1.2.x and prior versions in terms of systemd lockdown.

/cc @danderson @Freso

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/77 (which was never closed)
