### ISSUE TITLE
FR: 请求Android端显示在线功能

### ISSUE THREAD

**Issue by gzfa** [tailscale/tailscale#12460]
### What are you trying to do?

请求开发者给Android app端增加显示设备在线功能

**Comment by bradfitz** [comment]
"Request the developer to add the function of showing device online to the Android app"

**Comment by agottardo** [comment]
This is already supported, the online status is displayed in the devices list. The user is probably using a very old APK.

**Comment by bradfitz** [comment]
Closing as done. @gzfa, you didn't say what version you're running. But try upgrading.
