### ISSUE TITLE
Docker no longer updates.

### ISSUE THREAD

**Issue by mrmuiz** [tailscale/tailscale#12482]
### What is the issue?

I guess its not reaLy a bug but. Since the last few versions Docker no longer updates.
Tailscale updated all machines exept the one running on Docker. Tailscale keeps saying there is an update ; 
![afbeelding](https://github.com/tailscale/tailscale/assets/118138382/8a0d23ff-54ee-4d94-b18c-7467f1e8c40a)

### Steps to reproduce

Went to see if there is such version on Docker. But its removed??

### OS

Synology

### OS version

DSM 7.2

### Tailscale version

1.66.3

**Comment by agottardo** [comment]
From our changelog:

> The Tailscale client releases for containers such as the [Kubernetes operator](https://tailscale.com/kb/1236/kubernetes-operator), [Docker](https://tailscale.com/kb/1282/docker) image, and [tsrecorder](https://tailscale.com/kb/1246/tailscale-ssh-session-recording) are typically released a few days after the initial client release. A separate changelog will be published when client updates for containers are available.

**Comment by mrmuiz** [comment]
It was available for  a while then it was removed. But  Oke, thanks ill gues we have to wait.
