### ISSUE TITLE
Cannot connect to nodes and the internet when using Tailscale DNS settings

### ISSUE THREAD

**Issue by nguyentoanit** [tailscale/tailscale#12504]
### What is the issue?

<img width="595" alt="image" src="https://github.com/tailscale/tailscale/assets/19872073/88df5503-56ad-4783-81da-1cdd0f4cbb11">

When using Tailscale DNS settings, I lost the internet connection and could not connect to the nodes as well.

### Are there any recent changes that introduced the issue?

No. There wasn't any changes.

### OS

macOS

### OS version

macOS Sonoma 14.4.1

### Tailscale version

1.68.1

### Bug report

BUG-af89e3be7aa0853b41e2b6e65d8bf11b00a9713ba73a2ed1b9b0181388567158-20240617134056Z-1b4e1a47cd7f9829

**Comment by kelivel** [comment]
`dns udp query: resolving using "127.0.2.3": write udp4 0.0.0.0:60989->127.0.2.3:53: sendto: network is unreachable dial tcp4 127.0.2.3:53: connect: can't assign requested address`

Tailscale is trying to use `127.0.2.3` for DNS. Are you using any other software that could be changing your local DNS settings to `127.0.2.3` or `127.0.2.2`?

**Comment by nguyentoanit** [comment]
Looks like, Cloudflare didn't rollback DNS settings after exiting.
So, just Open Cloudflare -> Connect -> Disconnect. 🤷

**Comment by Explosion-Scratch** [comment]
This happened to me as well - I had to run `sudo ip route add default via 192.168.12.1`
