### ISSUE TITLE
(io.tailscale.ipn.macos.network-extension[23378]): Service exited with abnormal code: 2

### ISSUE THREAD

**Issue by quartermarsh** [tailscale/tailscale#12519]
### What is the issue?

Tailscale v1.44 logs out daily with above error code. I have two identical machines at the destination location and this is only happening on one of them. This has been happening for at least 30 days. Sleep is disabled with `caffeinate`. Key expiry is disabled.
For now I have the workaround of accessing the machine that’s logged out of Tailscale by screensharing locally from the other machine on the same network and logging back in to Tailscale.
Is anyone familiar with this launchd error? I haven’t had any luck searching on it.

### Steps to reproduce

Run Tailscale v1.44 on macOS 10.14.6 and access the machine/server remotely from a machine running TS 1.68.1 on macOS 14.5 using Screen Sharing.

### Are there any recent changes that introduced the issue?

No.

### OS

macOS

### OS version

Source machine on 14.5. Destination on 10.14.6

### Tailscale version

Source on 1.68.1. Destination on 1.44

### Other software

Little Snitch.

### Bug report

BUG-ff6ecff97ffa02f858dd86006305b4e9b16821711093d531dfbdc2adbfc0dab4-20240617190652Z-c1c777a7cb5b98a6

**Comment by barnstar** [comment]
Unfortunately, 10.14.6 is no longer supported so we have no way of investigating this.  If it's possible, update the older node. 
 Newer versions of the client (circa 1.58 or so) should be more resilient with respect to restarting the Tailscale daemon in the case of system termination (or a crash) - and should be more stable in general.
 
 We do still support macOS 10.15 as of 1.68 (though only for the next few releases).
