### ISSUE TITLE
Apple shortcuts broken on iOS/iPadOS 16 with Tailscale 1.68

### ISSUE THREAD

**Issue by Erisa** [tailscale/tailscale#12521]
### What is the issue?

On Apple devices running iOS 16/iPadOS 16, the Shortcuts integration is broken and reports an internal error.

### Steps to reproduce

1. Get a device on iOS or iPadOS 16 with Tailscale 1.68
2. Login to and disconnect from Tailscale.
3. Create a Shortcut that uses the "Connect" action in the Tailscale app,
4. Run the shortcut.

You will see "The action "Connect" could not run because an internal error occurred."

![IMG_E19C7F8B1452-1](https://github.com/tailscale/tailscale/assets/14004943/ffb7a151-457e-4e90-8209-c0a34b221edc)

### Are there any recent changes that introduced the issue?

Appears to have started with Tailscale 1.68.

### OS

iOS

### OS version

Reproduced on iOS 16.7.8 and iPadOS 16.6.1

### Tailscale version

1.68.0

### Other software

N/A

### Bug report

N/A - The logs do not appear to be relevant and cannot be collected when disconnected from Tailscale.

See also: go/tss/40525

**Comment by Erisa** [comment]
Upon further checking I discovered this is not unique to the "Connect", action, I was also able to consistently (100% of the time) reproduce the error using the "Use Exit Node" shortcut action. The bug report ID is `BUG-a8f6fdf176820bb4b74cd7abf9f11b3ca2ad0cd5f264637862f3bbb4af0b5777-20240618151915Z-876bef0cf86048d6`. It was not possible to create one for "Connect" as you cannot create one while Tailscale is not connected. Connecting and using exit nodes both work perfectly in the app.

**Comment by ev-w** [comment]
In the app, selecting a Mullvad exit node shows the Country/City, but in Shortcuts it's showing every individual exit node.

![IMG_2102](https://github.com/user-attachments/assets/ca16ecf3-bda3-4599-bfc7-0e1656968912)

I'm frequently encountering errors with this in an automation, where it says that the exit node isn't valid. Is there a way to better handle the Mullvad exit node connections, like a "best available in ____ city"?

Regardless, there definitely is something funky going on with Shortcuts and Tailscale, though it wouldn't shock me if it's an Apple bug; Shortcuts hasn't gotten much attention or love from Apple in a while.

**Comment by kelivel** [comment]
Shortcut support on iOS 16 is best effort.
