### ISSUE TITLE
Stuck on DERP

### ISSUE THREAD

**Issue by VelocipedeRider** [tailscale/tailscale#12548]
### What is the issue?

Tailscale will stick on DERP routing until I down and up the connection and then it will get a direct connection to my peer. Tailscale ping will not trigger a direct connection most of the time. 

### Steps to reproduce

Normal operation.

### OS

Linux

### OS version

Manjaro

### Tailscale version

 1.66.4

**Comment by agottardo** [comment]
We cannot diagnose connectivity issues until we have a bug report identifier.

**Comment by VelocipedeRider** [comment]
It's an ISP issue with the other client. Close this out.

Side note, how can we get some sort of keep-alive so it's not hunting through DERP until it gets a direct connection?

**Comment by ftruzzi** [comment]
> It's an ISP issue with the other client.

@VelocipedeRider how did you figure this out? can you provide more details?

I'm experiencing the same where clients can't direct connect to my Unraid server unless I restart tailscale on it

**Comment by VelocipedeRider** [comment]
We don't have 100% confirmation, but I have a local ISP and the other end
has ATT fiber.

The ATT fiber person, whom is an accomplished IT engineer, as am I, cannot
get ours to direct connect. We can direct connect to any other shared
device like a 3rd party random Cable user, but not to each other. The ISP
is the only thing we can't direct test like client versions, UPNP, NAT port
forwarding etc. So we concluded this is an ISP issue. Which knowing ATT,
isn't a surprise.

**Comment by ftruzzi** [comment]
Hey @VelocipedeRider thanks for your reply. In my case it was something else – there was another Tailscale device (my Apple TV) listening on the same port I had forwarded to my server (41641), so I guess Tailscale was choosing another random port after a while. You can check this on the Tailscale admin console by going through each device.
