### ISSUE TITLE
An error occurred when using the derper built by oneself

### ISSUE THREAD

**Issue by Calcifer97** [tailscale/tailscale#12558]
### What is the issue?

![image](https://github.com/tailscale/tailscale/assets/37408196/28ec86a9-38c2-44f0-ad94-430a498dcfa4)

**Comment by agottardo** [comment]
Why are you attempting to run a DERP server, and how did you install it?

Note from the [documentation](https://github.com/tailscale/tailscale/tree/main/cmd/derper):

> - If using --verify-clients, a tailscaled must be running alongside the derper.
>
> - If using --verify-clients, a tailscaled must also be running alongside your derpprobe, and derpprobe needs to use --derp-map=local.

**Comment by Calcifer97** [comment]
> 为什么您尝试运行 DERP 服务器，并且可以安装它？
> 
> [文档](https://github.com/tailscale/tailscale/tree/main/cmd/derper)中的注释：
> 
> > * 如果使用 --verify-clients，tailscaled 必须与 derper 一起运行。
> > * 如果使用 --verify-clients，tailscaled 也必须与 derpprobe 一起运行，并且 derpprobe 需要使用 --derp-map=local。

I understand. The derp version I compiled myself is ahead of tailscaled. Thank you

**Comment by bradfitz** [comment]
Dup of #12617 which was "fixed" by updated error messages and docs.
