### ISSUE TITLE
Microsoft live.cn public domain security problem

### ISSUE THREAD

**Issue by JohnnySun** [tailscale/tailscale#1256]
I login tailscale with microsoft oauth. use @live.cn email. (it's an old microsoft public email domain in china).

these day, i found there are some new member(other users login with @live.cn) in my team. and i can found and ping there computers.

Its an huge security problem, @live.cn its a public domain like @gmail.com. why i can find and reach other peoples computers.
 
I am solo plan. other @live.cn user just appear in my team, and can reach eachother.  it's incredible.
![image](https://user-images.githubusercontent.com/6197733/106726257-21285500-6645-11eb-86d6-e77d37abbc87.png)

Even i dont known who they are!! (yangloft and maxsped)

**Comment by sailorfrag** [comment]
Hello, I apologize for the problem. We have a large list of domains used by shared e-mail providers (including many live.{country code} domains), but this one was not on any of the lists we consulted. I have reconfigured live.cn to separate users from each other and applied this retroactively to the existing accounts on there.

Our original strategy of joining users in domains together by default works pretty well for workplaces, but is obviously a huge problem in situations like this, so we are working on changing the account creation process to prevent this from happening in future. I don't have a precise ETA for that, but it is fairly high priority.

If you log in again, you should not see anybody else's devices anymore.
