### ISSUE TITLE
macOS MAS client silently defeats iCloud Private Relay

### ISSUE THREAD

**Issue by mattieb** [tailscale/tailscale#12567]
### What is the issue?

I noticed that when my Tailscale connection is on, Safari begins sending traffic over my normal Internet connection.

### Steps to reproduce

1. Using [Vallum](https://vallumfirewall.com)'s Flows Monitor and Tailscale MAS running but "Not Connected",
2. Safari is making no outgoing connections,
3. I turned on my Tailscale connection,
4. Further browsing in Safari begins making outgoing connections visible in the Flows Monitor. At no point did macOS inform me that iCloud Private Relay was disabled.
5. If I turn off my Tailscale connection and quit Safari,
6. Further browsing in Safari will resume making no outgoing connections.

### Are there any recent changes that introduced the issue?

I have not observed this before beginning to use Vallum, so I can't say.

### OS

macOS

### OS version

Sonoma 14.5

### Tailscale version

1.68.1 Mac App Store variant

### Other software

- Malwarebytes 5.3.1

### Bug report

BUG-ad1efa4a365e199c785dd01b316b2644811335112b480c985d17c50bb778cf36-20240620233604Z-c95d80ed6fcff5de

**Comment by agottardo** [comment]
This sounds like a Safari-specific behaviour and you should discuss this with Apple. We integrate with the system NetworkExtension.framework, so Tailscale behaves like any other VPN app on macOS would do. 

Are you using an exit node with Tailscale? Can you explain what the expected behaviour here is? We don't set routes to route your traffic until you choose to use an exit node. It feels like Safari is changing its routing behaviour when it sees a VPN enabled.

**Comment by mattieb** [comment]
You know what—I think there's something that I was simply misunderstanding here and I've jumped the gun.

If I tcpdump traffic, nothing actually changes whether Tailscale is on or off. I see QUIC traffic run to Apple when triggering page loads etc., as I'd expect, for an active iCloud Private Relay session.

I think this may be chalked up to some strange interaction with multiple network extensions (Vallum is another) where network flows appear differently in Vallum's monitor depending on whether Tailscale is on or off. As you say, might be in Apple's domain. It's still very strange, but also not a functional concern as far as I can tell.

My apologies. I support closing this.

To answer your question just in case it's helpful, in case anyone else has a similar question—no, I do not have an exit node configured or indeed any present on my tailnet.

I did notice when digging more deeply that netstat -rn does show default routes configured for utun8 when Tailscale is connected, but I have no evidence there's anything to that.

**Comment by agottardo** [comment]
`netstat -rn` should exclusively show routes for IP addresses in your tailnet when an exit node is not being used. On the other hand, when an exit node is used it should show that all traffic is routed to utun, unless you have "Allow LAN Access" enabled, in which case routes to local IP ranges won't go to the utun interface.
