### ISSUE TITLE
iOS: implement vpn on-demand for apps

### ISSUE THREAD

**Issue by Blue-Code252** [tailscale/tailscale#12574]
### What are you trying to do?

Hey, I would like to be able to add an app to the Tailscale VPN so that it automatically opens my Plex app, for example. 

So far it's not too difficult, I can solve that with Apple Shortcuts.

But there's one thing I don't have. When I close the Plex app completely, the VPN should disconnect. (That's what I'm going for).

Yes, there is a possibility that it works with Apple Shortcuts, but that is not really user friendly and we already have VPN on demand. It should already support automated connections (not just with WiFi and Mobildata).

I mean, it tells me "automated".

It would be really helpful if the app supported this feature. (Even for free users, pls)

Anyway, so far I love the way the Tailscale VPN works, thanks for such a great project.

I hope this feature will be supported. (In some way)

### How should we solve this?

Add the feature in built or add an Instruction
How to do it with apple Shortcuts.

### What is the impact of not solving this?

Not fully automated 

### Anything else?

Pls make it happen

**Comment by agottardo** [comment]
We cannot build this on iOS. It's an Apple restriction. Apps cannot know when other apps are opened/closed for privacy reasons. Shortcuts integration is the best we can do, unfortunately.
