### ISSUE TITLE
hello.ipn.dev takes a long time to start up due to number of /32 routes

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1258]
tailscaled on hello.ipn.dev takes a long time to start up because it has to run the `ip` command a bazillion times to add /32 (and now also /128) routes to everybody.

We should probably just register the whole CGNAT+ULA ranges.

Explicit flag/env for now probably. Or a heuristic, like if number of /32 routes is over N thousand.

At least for the IPv6 ULA, though, why are those all /128s as opposed to the whole /48?

/cc @danderson

**Comment by DentonGentry** [comment]
I think this is done: https://github.com/tailscale/tailscale/pull/1451

Barring further updates, we'll plan to close this during the next bug scrub.

**Comment by bradfitz** [comment]
#1451 basically fixed it, but then we also went and made hello only able to see peers that were online, which dropped its peers down quite a bit.

Many people delete hello from their network once they're up & running, so the massive peer count from before was from old/abandoned nodes.

Now that hello's peer count is down, it's actually below the 10,000 threshold at which #1451 switched to one big route, so somewhat ironically it's back to being a little slower to start up than it was months ago, but it's still under a second, so closing.
