### ISSUE TITLE
FR: Allow to purchase Mullvad Add-on from Uruguay

### ISSUE THREAD

**Issue by martinlarosa** [tailscale/tailscale#12584]
### What are you trying to do?

Purchase Mullvad Add-On from Uruguay

### How should we solve this?

Allow to Purchase Mullvad Add-On from Uruguay

### What is the impact of not solving this?

Not being able to use Mullvad Add-on

**Comment by bradfitz** [comment]
Dup of #12378

**Comment by martinlarosa** [comment]
I opened this because the other was requesting better servers for Uruguay, this was just for being able to purchase it from Uruguay.

**Comment by martinlarosa** [comment]
oh I see you already figured that out :P 
thanks!

**Comment by bradfitz** [comment]
Yeah, I searched too quickly and didn't realize at first that they were different.

**Comment by martinlarosa** [comment]
Is there any update on this? Is this something that is possible or is it not in your plans?

Thanks

**Comment by bradfitz** [comment]
Still underway. Dup of #9314. We'll post updates on that issue as we expand the list of countries where you can purchase the Tailscale/Mullvad add-on.
