### ISSUE TITLE
The 'Override local DNS' feature is not working.

### ISSUE THREAD

**Issue by Zhy946644** [tailscale/tailscale#12595]
### What is the issue?

I encountered some issues when using the 'Override local DNS' feature; it seems that it didn't take effect.

I have a private DNS server (192.168.28.34) within my local network. My own computer (Windows 11) is installed and logged into Tailscale.
![image](https://github.com/tailscale/tailscale/assets/77084258/3486d1f6-3256-44d5-a77a-5f6ed12296aa)

I have also added a global DNS in the control panel and enabled 'Override local DNS'.

![image](https://github.com/tailscale/tailscale/assets/77084258/629cab07-2e10-475a-b30e-a6465a58ec0d)

I have added a resolution for 'qq1.com' to '100.100.100.1' on the private DNS server. However, when I access qq1.com on my local machine (Windows 11), DNS does not resolve to 100.100.100.1.
In my ideal scenario, when I ping qq1.com, the IP address should be 100.100.100.1 instead of 69.163.180.165.
![image](https://github.com/tailscale/tailscale/assets/77084258/2aec8ae5-176e-4913-b62f-d64fa62c508a)

### Steps to reproduce

If I remove the global DNS settings and enable 'Split DNS', then it works.
![image](https://github.com/tailscale/tailscale/assets/77084258/2619b116-c22e-43ce-b561-fc6c22b37cab)
![image](https://github.com/tailscale/tailscale/assets/77084258/916825d9-8e35-418d-826b-c4c883819489)

When both 'Split DNS' and 'Override local DNS' are enabled at the same time, it doesn't work when I ping.
![image](https://github.com/tailscale/tailscale/assets/77084258/7f29fc0a-e4e4-48a5-b3cd-f08927ad5516)

### OS

Windows

### Tailscale version

Version 1.68.1(tf02ad8397-g8f9cb4763)

**Comment by nickkhyl** [comment]
Hi @Zhy946644! We believe this issue has already been fixed, and the fix will be included in the next stable release scheduled for mid-July. In the meantime, can you please try it out in an [unstable build](https://pkgs.tailscale.com/unstable/#windows)?

**Comment by Zhy946644** [comment]
> Hi @Zhy946644! We believe this issue has already been fixed, and the fix will be included in the next stable release scheduled for mid-July. In the meantime, can you please try it out in an [unstable build](https://pkgs.tailscale.com/unstable/#windows)?

Okay, I downloaded version 1.69.66 from the website, and the 'Override local DNS' feature is now working properly.  Thank you!

**Comment by nickkhyl** [comment]
Thank you for confirming!
