### ISSUE TITLE
iphone client only connected to one subnet

### ISSUE THREAD

**Issue by ms8x8x** [tailscale/tailscale#12596]
### What is the issue?

I built a tailnet in a site-to-site mode succesfully, which means LAN A and LAN B could access each other freely. But after my iphone 15 pm added in, I just could access LAN A only through iphone.  Tested by tracerouting using other App in iphone, it seemed that only LAN A's routing table was accepted, while LAN B's NOT.

In iphone client, I could see both registered subnet router, but only could access LAN A. 
Any possible info I missed for this problem?

### OS

iOS

### OS version

17.5.1

### Tailscale version

1.68.0

**Comment by kelivel** [comment]
Can you please generate a bug report after the connection to LAN B fails and add that bug marker here?

**Comment by ms8x8x** [comment]
thanks for your reply, I found the router of LAN B was not configured as UPnP enabled. That would make LAN B's routes information be not advertised correctly. After fixing that, my iphone can access both subnetworks as expected.

maybe your guys need to put this requirement in your site-to-site document, :-P
