### ISSUE TITLE
Machine renamed despite no clash

### ISSUE THREAD

**Issue by kellytrinh** [tailscale/tailscale#1259]
**Describe the bug**

One of my machines has hostname 'core'.
In the past, Tailscale would adopt the hostname for the TS network.
For some reason, tailscale has recently renamed it 'core-1' (detecting some clash?)
There is no other machine on my network using the name core.
When I try to manually rename back via web interface - it fails with error "Name "core" is already taken"

**Expected behavior**

I should be able to rename back?

**Version information:**
Windows version 1.40

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2u89d)

**Comment by bradfitz** [comment]
Yeah, this is a known issue after some recent changes we made in how we set, change, and store names. We have some records in the database to clean up for names created (implicitly) in our old naming system.

/cc @soniaappasamy @rosszurowski @sailorfrag @crawshaw

**Comment by kellytrinh** [comment]
the odd naming of 'core-1' is on web interface (and works from desktop) but on the ipad app; it does show 'core' - it shouldn't be inconsistent right?

**Comment by mikaelf** [comment]
👀  following! :)

**Comment by mikaelf** [comment]
I'm also affected by this bug. Following! 👀  :)

**Comment by rosszurowski** [comment]
Issue #1200 already covers this same issue, so I'm going to close this one out in favour of that. Please subscribe for updates there.
