### ISSUE TITLE
Tailscale CLI - Exit Node suggestion ID not working.

### ISSUE THREAD

**Issue by Valien** [tailscale/tailscale#12618]
### What is the issue?

When using `tailscale exit-node suggest` from the CLI you receive a suggested exit node name and a sample command to run with the exit node ID.

When running the sample command the client will error out and say you need to use the IP or unique node name.

See screenshot:

![image](https://github.com/tailscale/tailscale/assets/1424442/e0303065-0746-41d2-82f9-a61a94562f5c)

### Steps to reproduce

From MacOS:

1. Open terminal
2. Type in `tailscale exit-node suggest`
3. Copy and run the suggested command.
4. See the error message.

### OS

macOS

### OS version

Sonoma 14.5

### Tailscale version

1.69.75

**Comment by sailorfrag** [comment]
It should be fixed in any unstable build at least 1.69.83 (it looks like the last unstable build is 1.69.66 but a new one will likely be built in the next few days), or stable 1.70.0.

**Comment by sailorfrag** [comment]
It turns out that the earlier fix was still not quite correct, but I'm confident that it's working properly this time around. It is still expected to be resolved in stable 1.70.0.
