### ISSUE TITLE
derper verification fails with Bad Request: invalid 'addr' parameter 

### ISSUE THREAD

**Issue by vsarunas** [tailscale/tailscale#12617]
### What is the issue?

It looks like latest version of derper published under https://hub.docker.com/r/fredliang/derper/tags?page=&page_size=&name=&ordering=last_updated is a bit newer than the latest release of Tailscale which is not yet released:
```
./derper -version
1.69.0-ERR-BuildInfo
```

Latest release for Linux packages:
```
1.68.1
  tailscale commit: f02ad839770b7d1453e88d64b02162ce81cdd7a8
```

This prevents derp from verifying clients via `-verify-clients=true` and passing traffic:
```
derp: client_ip: client nodekey: nodekey rejected: failed to query local tailscaled status for nodekey: nodekey: 400 Bad Request: invalid 'addr' parameter
```[](url)

### Steps to reproduce

1) Run derper with `-verify-clients=true` version 1.69
2) Run  Tailscale client 1.68.1
3) Connect via custom derp

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

_No response_

### Tailscale version

1.68.1

### Other software

_No response_

### Bug report

_No response_

**Comment by raggi** [comment]
the current HEAD derper has a change in semantics for `-verify-clients` that requires a tailscale client of 1.69.10+ or so.

**Comment by bradfitz** [comment]
That Docker image is not from Tailscale.

And like James said, derper and its verification mode against tailscaled require running builds from the same revision. You're running a dev version of derper against a stable (old) version of tailscaled.

We could perhaps make it work anyway but that's not really interop matrix combination we've supported in the past and I'm reluctant to set precedent and commit to testing all combinations down the road.

**Comment by vsarunas** [comment]
Yep understandable compatability version is hard to test; but with the improved logging it will be greatly clearer once deployments are slowly upgraded. Thanks!
