### ISSUE TITLE
Exit-node suddenly quit after a period of time

### ISSUE THREAD

**Issue by jiz4oh** [tailscale/tailscale#12635]
### What is the issue?

The exit node change to `None` sometimes

### OS

Android

### OS version

Android13

### Tailscale version

1.69.75-t27033c627-gb6cacdfd6a2

### Bug report

BUG-97e58b393a68a3210791f771338028897375590a6f92f7c1ede8b3f5ff824cee-20240627060537Z-cec558822df0bd51

**Comment by agottardo** [comment]
There have been recent changes in unstable related to exit nodes presentation, so this might be a regression introduced in a this release.

**Comment by dblohm7** [comment]
@agottardo have any fixes landed for this in a related issue? Is this one closeable?
