### ISSUE TITLE
if nat traversal failed , use own derp or own server (relay node)

### ISSUE THREAD

**Issue by oxcz** [tailscale/tailscale#1263]
Sorry, English is not very good.

**Is your feature request related to a problem? Please describe.**
In china, connecting derp delays are always high.
And the existence of the Great Firewall of China.
If i have my own server,I want to use him if nat traversal failed .
**Describe the solution you'd like**
use own derp or own server (relay node)
Not just associated subnets

**Describe alternatives you've considered**
https://tailscale.com/kb/1021/install-aws
https://tailscale.com/kb/1019/subnets

**Additional context**

**Comment by bradfitz** [comment]
We do have plans for this. I thought we had a public bug about it already but couldn't find one, so I created #1264. I'll close this one as a dup of that one. You can subscribe there.

That said, this wouldn't necessarily solve your [GFW](https://en.wikipedia.org/wiki/Great_Firewall) problem, which is an enormously large and never-ending problem, and is not our focus.

**Comment by talway** [comment]
@oxcz  Dude, can you package this open source repeater software；I see you can use GO language
