### ISSUE TITLE
FR: Apple Shortcuts action to enable/disable "Use Tailscale DNS settings" option

### ISSUE THREAD

**Issue by adamfeldman** [tailscale/tailscale#12641]
### What are you trying to do?

Tailscale has many Apple Shortcuts actions available. There is not yet an action to enable/disable the "Use Tailscale DNS settings" toggle in the macOS or iOS app. 

For my workflow, I keep this toggle off except when I am occasionally using an exit node. I am able to start/stop using an exit node from Shortcuts, but have to go into Tailscale settings to toggle Use Tailscale DNS settings".

### How should we solve this?

Add 2 Apple Shortcuts actions: "Start Using Tailscale DNS settings" and "Stop Using Tailscale DNS settings".

### Anything else?

Thank you!

**Comment by agottardo** [comment]
This should really be one shortcut with Set/Toggle parameters, but yes, this would be great to have.

**Comment by agottardo** [comment]
<img width="1312" alt="Screenshot 2024-06-27 at 10 31 42" src="https://github.com/tailscale/tailscale/assets/9057073/9608716e-bee1-477e-b6e9-cef8714991f2">

Done, we aim to land this in the 1.70 release next month (and probably the next TestFlight build).

**Comment by adamfeldman** [comment]
Amazing! Thank you @agottardo and team!
