### ISSUE TITLE
Let users add/replace DERP servers for their network

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1264]
Tailscale (the company) runs DERP relays around the world, such that there's always one near users, but various users/organizations have requested the ability to modify the DERP map for their network, either:

* augmenting our DERP map with DERP nodes that they run (using the open source https://pkg.go.dev/tailscale.com/cmd/derper server)
* removing certain DERP servers from our set (e.g. remove some in certain countries, for regulatory reasons), including removing all but certain geos
* some combination of both: like removing all ours, and only using the ones the user supplied.

An easy way to this is to add some fields to the ACL JSON object (which we could rebrand as the "tailnet policy config" or "Tailnet ACL and policy config").

(We've discussed this in various forums, but creating this public tracking bug)

**Comment by crawshaw** [comment]
Should the DERP server be part of tailscaled? A user could enable a DERP server in the admin panel (and we could surface test results for "is this machine publicly reachable?" that all DERP servers should meet).

**Comment by bradfitz** [comment]
Yeah, that could be cool!

**Comment by talway** [comment]
Derp Relays can be packaged and installed directly or optionally

**Comment by talway** [comment]
Is there any new progress? The network connection speed is too slow now. I hope this function can be realized as soon as possible
@bradfitz

**Comment by bradfitz** [comment]
Any progress would be posted here. We have many things we'd like to do. This, while somewhat easy and fun, isn't super high on the list. Many more critical or impactful projects are above it. That prioritization could change at a moment's notice, though, particularly if a customer requires it. We'll post updates here when something is available.

**Comment by hronro** [comment]
This is the feature I want most.

And is there a suggestion about how to contribute to this? And then I can see if I can contribute to this in my spare time.

**Comment by talway** [comment]
Is there any new progress?

**Comment by talway** [comment]
> 这是我最想要的功能。
> 
> 是否有关于如何为此做出贡献的建议？然后，我可以看到，如果我可以贡献这一点，在我的业余时间。

Can you compile standalone server software?

**Comment by DentonGentry** [comment]
This issue is not being actively worked on at this time.

It seems like you're enthused about the possibility of adding a DERP server. Could I ask where you'd want it to be? Have you noticed long latency reaching one of the existing DERP servers?

**Comment by talway** [comment]
Yes, we need fast connection speed, which you cannot meet at present, so we hope to integrate and package this function.

**Comment by talway** [comment]
Could you please speed up the implementation of this function or simply put it online? Thank you

**Comment by DentonGentry** [comment]
Additional DERP servers are not likely to improve throughput, though they can improve latency. If you are located somewhere with no nearby DERP server, the latency to reach a distant server can be significant.

Could I ask where you are located? This particular issue tracks supporting DERP servers operated by users of the service, which is not something we're prepared to implement at this time. However we do add DERP servers operated by Tailscale, in order to improve latency for users in that region.

**Comment by talway** [comment]
It is China. At present, you are Japan and Singapore, but our delay is relatively large. But you don't want to set up servers in China; So I ask you to add your own servers; I'm looking to see if I can actually use it, most of it is done on the server, otherwise I can't connect to it; You just add this function, to your business has no impact, we just use transit public or their own server;

**Comment by talway** [comment]
@apenwarr Do you have a specific plan for this? Similar this kind of sync file software, https://relays.syncthing.net/

**Comment by DentonGentry** [comment]
Allowing addition of third-party DERP servers is not currently being worked on nor do I expect to be working on it in the next several months. That could change in the future, and if it does we will post updates here.

**Comment by DentonGentry** [comment]
Notes from discussion:
- we'd add a field to the ACL JSON (which we'll now refer to as the Policy JSON) to define new DERP servers, either in addition to or instead of the DERPers that Tailscale runs. Should also include a way to specify capabilities of DERPer in the JSON. This would change the DERPMap for that one Tailnet.
- We've held off on doing this because of concerns about constraining what Tailnets can do and how the control protocol can evolve. There are still some concerns in that, but the protocols are more mature now than when we first considered this idea.
- Access Control:
    - Enterprise customers would require a way to control access.
    - DERPer already generates a token, and if you put that into the Policy JSON then the client includes it in its request, Maybe hash it to the user ID so everyone gets a unique token.
    - Alternately, maybe have the DERP log into control, and then we send it the list of nodes allowed to connect to it. However this doesn’t make it easy to share DERPs amongst multiple tailnets.
    - Could have both, or start with one and add the second.
    - Maybe make DERPER a separate binary but have a flag if you are running it co-resident with a local tailscaled. Default open to all, but set the flag to restriuct it to the tailnet. Don’t even need the token then.

We have multiple use-cases:
- users in regions where we're unlikely to deploy servers
- various enterprise customers wanting to operate their own relays

To answer the immediate question: work on this is not scheduled and we don't have an expected date to deliver it, but it is still something which we intend to do.

**Comment by talway** [comment]
The core value of tailscale is safety, speed and stability;
1. Security, if you have a relay, you can use your own machine to ensure that all data is in your own hands; although you said that the data goes through your relay, and you did not intercept or tamper with the data, you can't tell it clearly and go directly to your own server. The safest; you can appoint your own relay server;
2. Speed: In most cases, the network has a complex structure and basically needs to be transferred. You can see the file relay. The daily volume and speed of the transfer and the number of shared relay nodes. Look at the file synchronization relay. Node map; there is no relay, the connection speed of the two machines is very poor; the relay map of the synchronization software has a lot of public data, you can refer to the analysis, there are many valuable conclusions that can be analyzed; one is file synchronization, One is connection, the goal is the same;
3. Stable, that is the test work that is being done consistently;

I think relay is an important function to solve the speed and stability of this software;

I think that the functions that meet the value of the software should be prioritized and done;

The above is for reference.

**Comment by wogong** [comment]
Waiting for this feature.
Maybe one day I'll drop TailScale due to the high latency.

**Comment by talway** [comment]
> Waiting for this feature.
> Maybe one day I'll drop Tailscale due to the high latency.

You can try N2N. You can build your own node. The principle is similar and the speed is very fast. I don't know when this will be.
https://github.com/ntop/n2n/tree/2.8-stable

Maybe this is part of the function of their charging scheme; This is what the company has to be profitable; Otherwise, the project can not go on, understandable

**Comment by bradfitz** [comment]
Update: we now have this working in production.

After a bit more testing and writing some documentation, we'll start accepting our first batch of beta testers.

**Comment by fengkaijia** [comment]
I would also like to see the ability to force a client to be always on DERP, even when that client can reach others via UDP.

The use case would be when having a remote client in an unstable network.

We have a China office, which has poor international routing to our other teams in Europe/NA and our AWS VPC (high ping and losses). It does have a good routing to some data centers in Hong Kong, so we would love to set up a private DERP in that DC, that can dramatically improve our connection quality (bigger companies might use leased lines, etc.). However, to my understanding, as our China office still can reach other teams via UDP, even if we have this fast DERP relay in HK, it won't kick in. Therefore, I would love to see a way to force a client to be always on DERP (better to configure it in ACL) even when UDP is available.

**Comment by bradfitz** [comment]
@fengkaijia, all clients are always on DERP. That's the sideband channel for two peers to use to negotiate a direct UDP connection through stateful firewalls. Even after getting a direct connection, the DERP channel stays up.

**Comment by fengkaijia** [comment]
I see, sorry for the confusion, let me make the use case more precise: "the ability to force a client always use _the relay to transmit packets_ (or forcibly disable UDP), even when that client can reach others via UDP". This is useful for a tailored DERP relay is way faster (in terms of bandwidth, etc.) than a direct connection between two points.

**Comment by talway** [comment]
> Update: we now have this working in production.
> 
> After a bit more testing and writing some documentation, we'll start accepting our first batch of beta testers.

Great job! Whether to add functions:

1. The relay server can be independently deployed;

2, you can choose to specify the relay server, can share the relay server;

**Comment by talway** [comment]
Can we test it now?

**Comment by bradfitz** [comment]
@fengkaijia, see the recently filed #2270 for what you probably want.

**Comment by talway** [comment]
Can we test it now?

**Comment by DentonGentry** [comment]
I promise that we will update the bug with instructions when it is ready to use.

**Comment by JulianKnodt** [comment]
The feature should now be available to test for all users!
In order to run your own DERP server, you'll need Go 1.16, as Tailscale currently depends on that version.

To set up your own DERP server, you can run

`go install tailscale.com/cmd/derper@latest`

`derper -c=$HOME/derper.conf --hostname=<your hostname> -stun`

Where `$HOME/derper.conf` is the place you want your private key,
it will be created on the first run of the server and be used by subsequent runs.
The machine should have port 443 open for TCP connections, and port 3478 for UDP connections for the STUN server.
At least one node in a region must have a STUN server, so for the common case of only one node, it is necessary to have the
STUN server.
In addition, hostname needs to be a DNS name, not an `ip:port`.




To specify it as a DERP server, add it to your [policy/acl JSON](https://login.tailscale.com/admin/acls):
```
{
  ...omitted fields
  
  "DERPMap": {
    // This field will remove all of Tailscale's default DERP servers.
    // It's for convenience to remove current and future Tailscale DERPs, and is not a required field.
    //"OmitDefaultRegions": true,
    
    "Regions": {
      // This adds a custom DERP server visible to nodes on the Tailnet.
      // Valid regions for custom nodes are in the range 900-999, anything outside of that will be invalid and not parse.
      "900": {
        "RegionID": 900,
        "RegionCode": "me",
        "Nodes": [{
            "HostName": "<your hostname>",
            "Name": "1",
            "RegionID": 900,
        }],
      },
      
      // Specifying null for one of Tailscale's DERPs will remove it from use for the Tailnet.
      // To list all of Tailscale's DERP regions, use `curl --silent https://login.tailscale.com/derpmap/default | jq .`
      "1": null,
    },
  }
}
```
Full docs for DERP map fields are [here](https://github.com/tailscale/tailscale/blob/main/tailcfg/derpmap.go).


After saving the policy JSON, you should start seeing traffic on your DERP server, if no other regions are lower latency.

**Comment by talway** [comment]
@JulianKnodt  Could you please simplify the update installation and policy setting? Thank you!

**Comment by bradfitz** [comment]
@talway, we have no plans to simplify this. This is a power user feature that's rarely needed. When it's needed, we want you to have access to all the knobs.

**Comment by fengkaijia** [comment]
Great! One minor question, it seems that in the policy JSON config, DERP servers are fixed at port 443 as there's no option to change it (there's `STUNPort` to set a different port for STUN UDP)? As not everyone can get access to port 443, due to company security requirements, gov/DC regulation, or simply the fact that it's hard to get a dedicated IPv4 address for running DERP server, maybe the ability to manually set port for DERP in the policy should be added.

**Comment by bradfitz** [comment]
@fengkaijia, perhaps, but you also need a TLS cert. Are you able to get a TLS cert but not run on 443? If so, how are you getting your cert without 443? LetsEncrypt DNS challenges, I suppose?

**Comment by maddie** [comment]
@bradfitz one scenario I can think of is sharing the 443 port with other services, running with an HAProxy frontend.

**Comment by DentonGentry** [comment]
SNI should handle all such cases.

**Comment by bradfitz** [comment]
@maddie, something else can terminate the TCP connection in front of `cmd/derper`, that's fine. But be aware that the clients don't speak regular HTTP or even WebSockets. Once they get a TLS connection they switch to a custom protocol.

As @DentonGentry says, you can mux on SNI using something like https://github.com/inetaf/tcpproxy too.

**Comment by abreis** [comment]
>       // Specifying null for one of Tailscale's DERPs will remove it from use for the Tailnet.
>       // To list all of Tailscale's DERP regions, use `curl --silent https://login.tailscale.com/derpmap/default | jq .`
>       "1": null,
>     },

Is this line (in @JulianKnodt's example policy JSON) disabling the NYC derp server? Is it required to run your own derp server or is it just an unrelated config example? Just asking in case someone copies it blindly.

**Comment by bradfitz** [comment]
@abreis, yes, that disables NYC.

The policy JSON lets you:

1. just add your own
2. remove certain regions of ours
3. remove all of our regions

If you do (3), then you also need to do (1). Otherwise you can just do (1) or just do (2). Or both (1) and (2). Or (1) and (3).

**Comment by fengkaijia** [comment]
@bradfitz I suppose DNS challenge is doable. For this particular non-443 port usage, I can think of barriers coming from regulation (both inner or outer) to limit the use of 443. And, for personal users, one might use a NAT server (normally a cloud VM/VPS) that shares an IPv4 for multiple VMs, which is rather common in east Asia; in this case, this user has no access to 443, only a given range of ports.

**Comment by bradfitz** [comment]
@fengkaijia, I sent out https://github.com/tailscale/tailscale/pull/2378.

Note that because it's a client change, you'll have to wait until Tailscale 1.12 to be able to use it. Or until it's included in an unstable (1.11.x) build at https://pkgs.tailscale.com/unstable/ after that change is submitted. It will also require us to update our control plane server.

**Comment by talway** [comment]
I don’t think this is how advanced it is to use as an advanced user;
This is the most basic function of this type of software;
I believe you have investigated similar software in the market;
DERP is added independently and freely, sharing this service is the most basic function;
The most important thing for this is to improve the connection speed of the network environment. If you have a good network environment, you don't need this function at all;
This function is for specific needs and is needed for poor network connection speed; if the network is good, this is not necessary at all;
This is the most basic and basic function;

**Comment by DentonGentry** [comment]
I understand the input and thank you for advocating for it, but on this point I need to be firm: this feature has met the initial set of goals. Tailscale users can add DERP servers to their Tailnets, for use by their users. We do not intend to do further work on this feature at this time.

If we do spend additional engineering effort in this area in the future, it would be aimed at users for whom deploying and maintaining a set of servers is a normal part of their daily operations.

Closing as fixed.

**Comment by vysecurity** [comment]
Waiting eagerly for this release as I need t set up my own DERP server with 20 ms ping. Any ETA on the full thing? I'm not sure I can use the unstable build if the web UI doesn't let me control it?

**Comment by DentonGentry** [comment]
The unstable release can join a Tailnet with other nodes, be controlled by the admin panel, and everything else. It is just built from HEAD instead of a release branch.

In most cases Tailscale traverses NAT firewalls to make direct connections. DERP exists for a) firewalls which are too locked down to traverse and b) the first packets sent to a host you haven't been in contact with, while DISCO probes for a direct connection.

**Comment by talway** [comment]
Whether this DERP can be shared with other users, or need special Settings, or just the domain name is ok

**Comment by DentonGentry** [comment]
The DERP server is added to the JSON file in the DERPMap field as described above.

Multiple Tailnets could specify the same hostname as their DERP server, nothing stops you from doing so.

It does not need other special settings, run cmd/derper and add it to the DERPMap.

**Comment by talway** [comment]
https://tailscale.com/kb/1118/custom-derp-servers/
derper -hostname your-hostname.com     Not available, hint  “derper: command not found”
You must use the：
derper -c=$HOME/derper.conf --hostname=<your hostname> --stun
Could you elaborate the document?

**Comment by hronro** [comment]
Hi guys, I'm facing TLS handshake errors, any ideas about this?

![CleanShot 2021-08-09 at 11 20 44](https://user-images.githubusercontent.com/15059605/128657304-0ed14483-f36a-4848-9d11-e66f15e630e0.png)

**Comment by vysecurity** [comment]
> @talway, we have no plans to simplify this. This is a power user feature that's rarely needed. When it's needed, we want you to have access to all the knobs.

I beg to differ. If you have a own private network, why wouldn't it automatically detect nodes that can be used as DERP servers? This would be more optimal and use all resources to maximize efficiency.

**Comment by vysecurity** [comment]
What does it mean if the DERP server shows up as : 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/3596242/128979077-f3937d37-8c91-4a5c-8378-9846d15ae1ed.png">

**Comment by DentonGentry** [comment]
Followed up in https://github.com/tailscale/tailscale/issues/2632

**Comment by Yubih** [comment]
> > @talway, we have no plans to simplify this. This is a power user feature that's rarely needed. When it's needed, we want you to have access to all the knobs.
> 
> I beg to differ. If you have a own private network, why wouldn't it automatically detect nodes that can be used as DERP servers? This would be more optimal and use all resources to maximize efficiency.
---------------------------
The most difficult core features are already done, the rest is logical page optimization; Should be made as used as the exit node; I think it's for the sake of the company's business. Speculation: This could be used as a paid feature in the future;

**Comment by thinker007** [comment]
> @fengkaijia, I sent out #2378.
> 
> Note that because it's a client change, you'll have to wait until Tailscale 1.12 to be able to use it. Or until it's included in an unstable (1.11.x) build at https://pkgs.tailscale.com/unstable/ after that change is submitted. It will also require us to update our control plane server.

So Now we can use custom DERPPort  now？ because in our country the 443 port is forbidden，so I have to use a different port.

**Comment by DentonGentry** [comment]
The current release is 1.16. There are users using custom DERP ports now.

**Comment by jorgejams88** [comment]
Hi:

I'm trying to configure my own DERP with low latency, the https server responds correctly (with a valid certificate). I also modified my acl file to look like this:

    "derpMap": {
      "Regions": { "900": {
        "RegionID": 900,
        "RegionCode": "myderp",
        "Nodes": [{
            "Name": "1",
            "RegionID": 900,
            "HostName": "my.host.com"
            }]
          }
        }
      }

But when I run tailscale status, I get this

    tailscale netcheck
    
    Report:
    	* UDP: true
    	* IPv4: yes, xx.xx.xx.xx:4027
    	* IPv6: no
    	* MappingVariesByDestIP: true
    	* HairPinning: false
    	* PortMapping:
    	* Nearest DERP: New York City
    	* DERP latency:
    		- nyc: 92.6ms  (New York City)
    		- ord: 107.8ms (Chicago)
    		- dfw: 115.3ms (Dallas)
    		- sao: 143.7ms (São Paulo)
    		- sea: 158ms   (Seattle)
    		- lhr: 161.2ms (London)
    		- sfo: 162.1ms (San Francisco)
    		- fra: 172.6ms (Frankfurt)
    		- tok: 257.7ms (Tokyo)
    		- syd: 296.6ms (Sydney)
    		- sin: 308.1ms (Singapore)
    		- blr: 312.2ms (Bangalore)
    		- myderp:         ()

Is there anything I'm missing?

**Comment by jorgejams88** [comment]
This issue was opened in response to my comment. Another port is needed for the Derp to work.

https://github.com/tailscale/tailscale/issues/3419

**Comment by talway** [comment]
> I would also like to suggest the ability to force a client to be always on DERP, even when that client can reach others via UDP.
> 
> The use case would be when having a remote client in an unstable network.
> 
> We have a China office, which has poor international routing to our other teams in Europe/NA and our AWS VPC (high ping and losses, slow speed). It does have a good routing to some data centers in Hong Kong, so we would love to set up a private DERP in that DC, that can dramatically improve our connection quality (bigger companies might use leased lines, etc.). However, to my understanding, as our China office still can reach other teams via UDP, even if we have this fast DERP relay in HK, it won't kick in. Therefore, I would love to see a way to force a client to be always on DERP (better to configure it in ACL) even when UDP is available.

@fengkaijia 
I think this is still not mandatory relay, they imagine the network is too idealized, our actual network is very complex; We need to force the relay

**Comment by bradfitz** [comment]
This bug is closed and has since become a chat room, distracting people who were subscribed to it for its original purpose.

Also, closed bugs aren't tracked on dashboards, so I'm going to lock this. Please open new forum posts or issues as needed for outstanding feature requests or bugs.
