### ISSUE TITLE
Inconsistent routing table metric settings on Windows

### ISSUE THREAD

**Issue by epposan** [tailscale/tailscale#12657]
### What is the issue?

The metric value assigned to the tailscale network adapter after the use of an exit node is not updated to the same value it had before the exit node was enabled.

### Steps to reproduce

As described in FR #12248, I have issues with Local LAN traffic being routed through the local subnet router when no additional action is taken.

Currently I work around the issue by having a permanent route to the Local LAN having a metric that is lower than the default TS metric of **5**.

I have disabled the windows **automatic metric** logic, which _automagically_ increments the user requested metric by a value depending on de network interface 'quality'.

The permanent route that I add,  requests for a metric of **2**, but it ends up a **4** in the routing table. So, even with **automatic metric** disabled, the o/s still adds **2** to the requested metric (I have not been able to find any documentation on this behavior)

After each action:
- I show the current **metrics** for the Local LAN
- I show the current **route** using `pathping -n -q 1 192.168.0.222`

```
IP addresses in use
- this machine Local LAN	192.168.0.111
- this machine Tailscale	100.89.34.84
- local subnet router		100.101.246.33	(advertises local subnet for remote clients)
- local Target machine		192.168.0.222

#--
# 1. after reboot, tailscale connected, no exit node
#--
destination			gateway		metric
192.168.0.0	/24		100.89.34.84	5			<- ok
192.168.0.0	/24		192.168.0.111	4

pathping result:
Tracing route to eppo-ds [192.168.0.222]
  0  192.168.0.111
  1  192.168.0.222

#--
# 2. remote exit node enabled, local local lan access disabled
#--
destination			gateway		metric
192.168.0.0	/24		100.89.34.84	0			<- ok
192.168.0.0	/24		192.168.0.111	4

Tracing route to eppo-ds [192.168.0.222]
  0  100.89.34.84
  1  100.101.246.33
  2  192.168.0.222
  
#--
# 3. remote exit node enabled, local local lan access enabled
#--
destination			gateway		metric
192.168.0.0	/24		100.89.34.84	0			<- not ok
192.168.0.0	/24		192.168.0.111	4

Tracing route to eppo-ds [192.168.0.222]
  0  100.89.34.84
  1  100.101.246.33
  2  192.168.0.222
  
#--
# 4. tailscale disconnected
#--
destination			gateway		metric
192.168.0.0	/24		192.168.0.111	4

Tracing route to eppo-ds [192.168.0.222]
  0  192.168.0.111
  1  192.168.0.222
  
#--
# 5. tailscale reconnected, without exit node
#--
destination			gateway		metric
192.168.0.0	/24		100.89.34.84	0			<- not ok
192.168.0.0	/24		192.168.0.111	4

Tracing route to eppo-ds [192.168.0.222]
  0  100.89.34.84
  1  100.101.246.33
  2  192.168.0.222
```

### Are there any recent changes that introduced the issue?

I don't think so, just not tested as detailed.

### OS

Windows

### OS version

Windows 10 Pro version 22H2

### Tailscale version

1.68.1

### Bug report

BUG-f4aa272f5679eb6ab6fdf6ad9ed379297619652ed1c89fa9e5fe31cd205d93c6-20240628115614Z-ee4d530e0ec1d7a6

**Comment by dblohm7** [comment]
I think we're going to have to tie this in with the feature request you referenced. We don't currently explicitly specify route metrics, so any such functionality will have to be built alongside the feature.

**Comment by epposan** [comment]
Thanks for taking the time to look into this.

You state that you don't explicitly specify route metrics, but, besides adding a default route with its metrics set to zero, also the metrics for the local network route is modified and explicitly set to zero, once an exit node is enabled

When the exit node is disabled, the additional default route is removed correctly, but the metrics of the local route is not restored to its previous value.

Leaving me with all traffic to the local lan passing by the local tailscale node.

```
situation before exit node is enabled:
0.0.0.0     0.0.0.0         192.168.0.2     192.168.0.111   4   
192.168.0.0 255.255.255.0   192.168.0.111   192.168.0.111   4   
192.168.0.0 255.255.255.0   100.100.100.100 100.89.34.84    5   <- ok

situation after exit node is enabled:
0.0.0.0     0.0.0.0         192.168.0.2     192.168.0.111   4
0.0.0.0     0.0.0.0         100.100.100.100 100.89.34.84    0
192.168.0.0 255.255.255.0   192.168.0.111   192.168.0.111   4
192.168.0.0 255.255.255.0   100.100.100.100 100.89.34.84    0

situation after exit node is disabled:
0.0.0.0     0.0.0.0         192.168.0.2     192.168.0.111   4
192.168.0.0 255.255.255.0   192.168.0.111   192.168.0.111   4
192.168.0.0 255.255.255.0   100.100.100.100 100.89.34.84    0   <- bug ?
```
For me personally, once I found out that this is happening, it is easy to restore the metric to the desired value, however for other participants on this ts (family) network this is not reasonably doable.

**Comment by Codelica** [comment]
I don't think this issue should have been closed.  

The problem is that when Windows Tailscale connects (without using an exit node) it's interface and all associated routes have a metric value of 5.  

When an exit node is enabled it's interface and all associated routes (including a new default route) are giving a metric of 0, which is fine for using an exit node.  

Hoever, when the exit node is disabled the default route is removed, but the interface and associated routes do not return to their previous metric of 5.  

This makes it literally impossible to create static routes to local LAN/vLAN segments that would override Tailscale subnets offered.
