### ISSUE TITLE
Support encrypted DNS (over TLS or HTTPS)

### ISSUE THREAD

**Issue by henrywallace** [tailscale/tailscale#1265]
**Is your feature request related to a problem? Please describe.**

Not able to configure DNS over TLS or HTTPS in https://login.tailscale.com/admin/dns dashboard. Instead have to choose either ipv4 or ipv6.

**Describe the solution you'd like**

I would like to be able to specify a path or URL for my DNS server that supports encrypted traffic. For example I use NextDNS which has created these (https://help.nextdns.io/t/m1hmv0k/which-setup-type-to-use).

**Describe alternatives you've considered**

I can just use unencrypted ipv6 in the dashboard.

**Additional context**

On linux, without tailscale I normally run the nextdns local server, which overrides my /etc/resolv.conf. But that conflicts with tailscale, so I think I'm forced to choose between the two.

Somewhat related to https://github.com/tailscale/tailscale/issues/690, in that I want to use an encrypted private DNS server in conjunction with tailscale. FWIW I also have that using private DNS is borked when used in conjunction with android app.

**Comment by DentonGentry** [comment]
Also relevant: https://github.com/tailscale/tailscale/issues/915, where we're likely going to need DNS-over-TLS to fully resolve it.

**Comment by DentonGentry** [comment]
I think this is the same feature request as #74, which has a number of updates about progress. I'm going to close this one to use #74 instead.
