### ISSUE TITLE
`tailscale drive delete` is an "unknown subcommand"

### ISSUE THREAD

**Issue by rweirtbg** [tailscale/tailscale#12663]
### What is the issue?

Following the instructions here:

https://tailscale.com/kb/1369/taildrive?tab=linux#delete-taildrive-shares

`tailscale drive delete <share-name>` results in:

`tailscale drive: unknown subcommand: delete`

### Steps to reproduce

Try `tailscale drive delete <share-name>`

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Ubuntu 22.04 LTS

### Tailscale version

1.68.1

### Other software

None

### Bug report

BUG-2f4e9162655862bc28471e19f14b848a3c3a7912682ac9176fea0ccef6f89c33-20240629055349Z-9105882db050f60d

**Comment by agottardo** [comment]
cc @oxtoacart
