### ISSUE TITLE
Please add com.ricohimaging.imagesync to the VPN bypass list

### ISSUE THREAD

**Issue by filviu** [tailscale/tailscale#12670]
### What is the issue?

The Image Sync app (used to download images from the Ricoh GR III line of cameras) is not able to connect to the camera if Tailscale is active.

### Steps to reproduce

- poweron camera
- attempt to download pictures using Image Sync

https://github.com/tailscale/tailscale/issues/2554 explains the issue and https://github.com/tailscale/tailscale-android/pull/50 fixed this for other apps.

### OS

Android

### OS version

Android 14 OneUI 6.1

### Tailscale version

1.68.1

### Other software

Ricoh Image Sync: https://play.google.com/store/apps/details?id=com.ricohimaging.imagesync

**Comment by filviu** [comment]
While there I would also add jp.co.canon.ic.cameraconnect which is the same type of camera companion app for a long list of Canon DSLRs and Mirrorless cameras.

**Comment by agottardo** [comment]
We're not going to do this because in https://github.com/tailscale/tailscale-android/pull/435 we're adding a dedicated settings page to configure a custom list of apps to be excluded.
