### ISSUE TITLE
Ping/session RDP OK with Linux/Android, NOK Windows 10/11 (random OK)

### ISSUE THREAD

**Issue by accnetdev** [tailscale/tailscale#12682]
### What is the issue?

Hi, my Linux/Android machines are responding to ping commands and are giving RDP sessions very well all the time.
Using the same free Tailscale account, all my Windows 10 or 11 machines are very rarely/randomly responding to ping (ICMP) and RDP.
I noticed that to get a RDP session on my Windows machines, the ping must be OK. 

### OS

Linux, Windows, Android

### OS version

Win 10/11 Ubuntu 20.04 ARM, Debian 12 ARM

### Tailscale version

1.68.1

**Comment by nickkhyl** [comment]
What does the [`tailscale ping`](https://tailscale.com/kb/1023/troubleshooting?q=tailscale+ping#how-do-i-know-if-my-traffic-is-being-routed-through-derp) command return? Can you please also generate [bug reports](https://tailscale.com/kb/1227/bug-report) on the source and destination Windows devices and post report IDs here?

**Comment by accnetdev** [comment]
For one Win11 PC with ESET Endpoint Security 11.0.2044.0, I have fixed my problem with this article :
https://github.com/tailscale/tailscale/issues/8781

I will go back for a Win10 with built-in firewall, when fixed.

I suspect Windows Firewall/Antivirus issue, this was why on Linux/Android Nodes it worked using standard Ufw config.

**Comment by dblohm7** [comment]
Sounds like this is ESET again.
