### ISSUE TITLE
Can't use Shared Exit Node belonging to Tailnet Lock-ed tailnet

### ISSUE THREAD

**Issue by samuel-tay** [tailscale/tailscale#12681]
### What is the issue?

I am trying to share a node with my family members to use as exit node, and followed all instructions as per the support docs. I have tested two different nodes, one remote and one local to the device's network. Devices are unable to access the internet after enabling either exit node. The internet works for devices approved and signed on my tailnet (my own devices).

After disabling tailnet lock, family members' devices could use the exit nodes as per normal.

This was tested on iphone and ipad with latest tailscale app.

### OS

iOS

### OS version

17.5.1

### Tailscale version

1.68.0

### Bug report

BUG-5d4ca78854ede4abe86db41a5e8b873254d2479995d9f2925fa75c75a08316e9-20240702031603Z-3e2008f38711f668

**Comment by knyar** [comment]
As mentioned in [the docs](https://tailscale.com/kb/1226/tailnet-lock#sharing), shared nodes are not exempt from Tailnet Lock, and need to be signed as well.

I believe running `tailscale lock status` should indicate that a peer needs to be signed, and provide a command to be run on a signing node. Note that this command needs to be run on a device that has Tailnet Lock enabled, irrespective of what side of the share the device is on (whether the device itself is being shared, or it's being used to access a shared node).

We got #9103 tracking UX improvements around this, so I will close this issue to avoid duplicates.
