### ISSUE TITLE
Account login name change

### ISSUE THREAD

**Issue by mohannandigam** [tailscale/tailscale#12697]
### What is the issue?

I log in to Tailscale with my GitHub account
Recently I changed my GitHub user name, and then I was not able to log to the new device

### Steps to reproduce

1. Create Tailscale with GitHub
2. Login to Tailscale in one browser with a GitHub account
3. Change the GitHub user name
4. Try to log in to Tailscale with another browser
5.  User got the error: Account login name change detected (from xxxxxxx to xxxxxxy) that requires a login and tailnet rename, please contact support to resolve this issue
REQ-1eb67171b-3590-4f22-8dee-a636b5aafac3

**Comment by timtailscale** [comment]
As mentioned in the error message, please reach out to support to get this resolved: https://tailscale.com/contact/support#support-form.
