### ISSUE TITLE
exitr nodes no longer seem to function correctly on 1.68.2

### ISSUE THREAD

**Issue by MonoChromancer** [tailscale/tailscale#12708]
### What is the issue?

you still seem to be able to set exit nodes, but you just cant assign them in windows on 1.68.2. this was not present on 1.68.1

### Steps to reproduce

Update to 1.68.2

right click the tailscale icon in the bottom right of your screen, go to exit nodes, select any active exit node, 

go back to the exit node menu, observe that the exit node is not being used,

Use What is my IP, Observe that your IP is not the exit node you wished to assign.

Repeat steps above as many times as necessary even after reboot. Install the update on all machines being used including the exit nodes. Repeat the above steps, Observe that exit nodes fail to be assigned and utilized properly,

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.68.2

### Other software

I did a fresh windows install last week so not many. Gog, parsec, steam epic launcherv discord, nvidia app, spotify obs docker wsl, thats about it

**Comment by agottardo** [comment]
There were no changes in exit node functionality in 1.68.2 (see the [changelog](https://tailscale.com/changelog#2024-07-02), the only changes affect Tailnet lock and macOS/iOS DNS resolution). There is something else in your setup that is causing this, the update was not responsible for it.

We cannot gather any diagnostics to investigate the issue if you do not attach a bug report identifier.

**Comment by MonoChromancer** [comment]
Ok, I think I figured it out:

 the issue started when my 2 open wrt routers suddenly stopped being available as exit nodes, so I set  PC1 to be an exit node (right after the update) but it seems like as though it cannot connect to PC2's exit node, if it is first set as an exit node (it shows it just fine, but silently fails to start using it. the UI is not clear it looks like it just silently fails to connect to the perfectly available exit node. if I first connect to PC2's exit node, -THEN- set PC1 to be an exit node then everything "works fine" (although PC2 can never see PC1's exit node for some reason.  
 
 The issues here are (all separate issues) 1: whatever halted both of my OpenWRT routers from no longer being available as exit nodes pushed me to set my main desktop machines as exit nodes, which caused, 2. you cannot connect to an exit node while your machine is currently an exit node (it looks like you can but it silently fails)
 3. trying to get help with my issue when clicking on "help" in the prompt that comes up when setting your machine as an exit node hard crashes tailscale. 
 
 I will bug all of these separately and include proper logging.
 
 I will update this issue to be issue #2 which is " you cannot change to using an exit node while you are set as an exit node, unless you were already connected to that exit node prior to setting yourself as an exit node"

**Comment by garrett-ts** [comment]
The MacOS client appears to handle this correctly and grey out the exit node options if the device is advertising as an exit node:

![CleanShot 2024-07-10 at 13 51 49](https://github.com/tailscale/tailscale/assets/110842475/6603e8cd-b1eb-4e44-a019-65445afb27fc)


The Windows client menu does not (no screenshot for this one). You can attempt to select an exit node but it fails silently.

Trying via the CLI on either OS shows a proper warning:

![Untitled](https://github.com/tailscale/tailscale/assets/110842475/628cd3d7-b434-4e0c-a473-39adb3811764)
![CleanShot 2024-07-10 at 14 28 59](https://github.com/tailscale/tailscale/assets/110842475/a84ffb14-2f44-47d3-bf5b-040085154fda)

>  you cannot change to using an exit node while you are set as an exit node, unless you were already connected to that exit node prior to setting yourself as an exit node

To be clear, chaining of exit nodes is not supported - historical info here:

* #3569 
* #9520

**Comment by dblohm7** [comment]
We've got issues on file for fixing up the Windows GUI when the node is already advertising as an exit node. Closing this in favour of #12771
