### ISSUE TITLE
Unable to Login On Windows 23H2

### ISSUE THREAD

**Issue by JustAiden9** [tailscale/tailscale#12710]
### What is the issue?

When I click login nothing happens, it worked before I updated. 

### Steps to reproduce

Try to click login

### Are there any recent changes that introduced the issue?

Nope

### OS

Windows

### OS version

23H2

### Tailscale version

1.68.2

### Other software

Nothing with networking and nothing with security.

### Bug report

BUG-67884bb074281ec983eb6194673343f6b53d32973e85df325e35e22fc47a8204-20240705003350Z-frontend8f50b5c6

**Comment by JustAiden9** [comment]
I did the "tailscale debug ts2021" and got this:
C:\Users\aiden>tailscale debug ts2021
20:29:01.015908 Fetching keys from https://controlplane.tailscale.com/key?v=95 ...
20:29:01.463166 Dial("tcp", "[2a05:d014:386:202:f041:44b6:9559:668]:80") ...
20:29:01.463166 Dial("tcp", "[2a05:d014:386:202:f041:44b6:9559:668]:80") = dial tcp [2a05:d014:386:202:f041:44b6:9559:668]:80: connectex: A socket operation was attempted to an unreachable network.
20:29:01.463166 Dial("tcp", "18.194.180.142:80") ...
20:29:01.584522 Dial("tcp", "18.194.180.142:80") = 192.168.10.138:51850 / 18.194.180.142:80
20:29:01.707286 controlhttp.Dial = 0xc00007e598, <nil>
20:29:01.707286 did noise handshake
20:29:01.707286 final underlying conn: 192.168.10.138:51850 / 18.194.180.142:80

**Comment by IlgazC** [comment]
I am having a similar issue although I have "virtualbox" "vmware workstation pro" and "cloudflare warp+" installed.
Here is the output from here:
 tailscale debug ts2021
11:26:46.897308 Fetching keys from https://controlplane.tailscale.com/key?v=97 ...
11:26:48.158795 Dial("tcp", "[2a05:d014:386:202:b88b:3cda:3907:3f2b]:80") ...
11:26:48.461966 Dial("tcp", "3.78.132.46:80") ...
11:26:48.494182 Dial("tcp", "3.78.132.46:80") = 172.16.0.2:55355 / 3.78.132.46:80
11:26:48.494182 Dial("tcp", "[2a05:d014:386:202:b88b:3cda:3907:3f2b]:80") = dial tcp [2a05:d014:386:202:b88b:3cda:3907:3f2b]:80: operation was canceled
11:26:48.640224 Dial("tcp", "[2a05:d014:386:202:b88b:3cda:3907:3f2b]:443") ...
11:26:48.708006 controlhttp.Dial = 0xc00021a2d8, <nil>
11:26:48.708517 did noise handshake
11:26:48.708517 Dial("tcp", "[2a05:d014:386:202:b88b:3cda:3907:3f2b]:443") = dial tcp [2a05:d014:386:202:b88b:3cda:3907:3f2b]:443: operation was canceled
11:26:48.708517 final underlying conn: 172.16.0.2:55355 / 3.78.132.46:80

**Comment by JustAiden9** [comment]
When I try to use Tailscale CLI I get this error now.
---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.



Version 1.68.2 (tc3ed2ce8b-g789e6d2f8)



LogID: 01b33e3a38f9ecbe19114dace7dd39557dc86f4cd82cf32890c090b6cb841968

(Ctrl-C to copy this text)


---------------------------
OK   
---------------------------

**Comment by dblohm7** [comment]
Frontend is having problems talking to tailscaled, but that's all I see here...

**Comment by nickkhyl** [comment]
It appears that the issue might have been resolved on 2024-07-10.

Prior to that, I regularly see these errors in the backend logs:
```
2024-07-10T22:17:04Z | Creating adapter
2024-07-10T22:17:19Z | Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2024-07-10T22:17:19Z | Failed to setup adapter (problem code: 0x38, ntstatus: 0x0): The device is not ready for use. (Code 0x000010DF)
```

The most common cause of this error so far has been a VMware product (e.g., VMware Workstation) whose files were removed without proper uninstallation. As a result, when Windows tries to load one of its components, it fails because the DLL is missing, preventing the configuration of the virtual network adapter. Of course, it doesn't have to be VMware—any product that implements and registers a [network component notify object](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/about-notify-objects) and is then abruptly removed from the system can cause this issue.

I'll update the logging and installer to help users identify issues like this on their own. In the meantime, the script below can help with that by reporting missing components, if any.

```powershell
$keyPaths = "HKLM:\SYSTEM\CurrentControlSet\Control\Network\*\*"
$keys = Get-ChildItem -Path $keyPaths -ErrorAction SilentlyContinue
foreach ($key in $keys) {
     $ndiKeyPath = $key.PSPath + "\NDI"
     $clsid = (Get-ItemProperty -Path $ndiKeyPath -ErrorAction SilentlyContinue).CLSID
     if ($null -ne $clsid) {
         $componentId = (Get-ItemProperty -Path $key.PSPath -ErrorAction SilentlyContinue).ComponentId

         # Determine the path to the In-Proc COM Server .DLL
         $dllpath = ""
         try {
             $inprocServer32path = "HKLM:\SOFTWARE\Classes\CLSID\$clsid\InprocServer32"
             $dllpath = (Get-ItemProperty -Path $inprocServer32path)."(Default)"
         } catch {
             Write-Output "WARNING: The DLL registration not found for $clsid ($componentId)"
             continue
         }

         # Check if the path exists
         if (Test-Path -Path $dllpath) {
             Write-Output "Found the DLL for $clsid ($componentId) at $dllpath"
         } else {
             Write-Output "WARNING: The DLL for $clsid ($componentId) does not exist at $dllpath"
         }
     }
}
```
