### ISSUE TITLE
Update custom server documentation

### ISSUE THREAD

**Issue by sugoidogo** [tailscale/tailscale#12721]
### What is the issue?

When using the instructions at https://tailscale.com/kb/1118/custom-derp-servers, the command to install derper is:
`go install tailscale.com/cmd/derper@main`
however this seems to install from the main dev branch instead of the release branch:
```
$ go/bin/derper --version
1.69.0-ERR-BuildInfo
```
When running the install command without a version, the following prompt appears:
```
~$ go install tailscale.com/cmd/derper
go: 'go install' requires a version when current directory is not in a module
        Try 'go install tailscale.com/cmd/derper@latest' to install the latest version
```
Upon following the prompt, the correct version is installed:
```
~$ go install tailscale.com/cmd/derper@latest
go: downloading tailscale.com v1.68.2
```
The documentation page should be updated to give the correct command.
I don't know if this is the correct place to report this issue, if not please direct me where I should post.

### Steps to reproduce

`~$ go install tailscale.com/cmd/derper@main`
```
$ go/bin/derper --version
1.69.0-ERR-BuildInfo
```

### OS

Linux

### OS version

Fedora 40

### Tailscale version

1.68.2

### Bug report

BUG-d39459a302742ff943d9a4bd23a792e12cdd1b567b2f960c1ffb0d1c32ae9032-20240706174240Z-3b382305090640e7

**Comment by bradfitz** [comment]
Thanks for the report! Will fix.
