### ISSUE TITLE
Magic DNS breaks other DNS domain resolution

### ISSUE THREAD

**Issue by basile-henry** [tailscale/tailscale#1273]
**Describe the bug**

I have a VPN setup using OpenVPN, and I use the DNS provided by the VPN for a specific search domain. The domains usually resolve perfectly fine (even when tailscale is up).

The domains start to fail to resolve on that VPN if I enable Magic DNS in tailscale's web UI. Actually it even goes further than that, even if I have Magic DNS disabled but at least 1 nameserver entered it fails to resolve on the VPN's DNS.

I don't think this bug has anything to do with the VPN and that local DNS resolution is broken as well but I am unable to verify that at the moment.

**Expected behavior**

Ideally both the DNS provided by tailscale and the one from my VPN would work at the same time. I understand it may require extra configuration on my side to achieve that. At the very least when Magic DNS is disabled setting a nameserver entry or not in that UI shouldn't affect how domains get resolved.

**Screenshots**

![image](https://user-images.githubusercontent.com/3369034/107026631-4931c880-67ab-11eb-828f-ac399350d5b2.png)

**Version information:**
 - Device: Desktop
 - OS: Ubuntu
 - OS version: Ubuntu 20.04
 - Tailscale version: 1.4.2 (tailscale commit: a9f58fe8222120423979efb2f59a83751786e44a)

**Additional context**

I am not sure what kind of data you might need to be able to reproduce this but I can give more information about how the VPN is setup if that helps.

Using `resolvectl status` and toggling the Magic DNS (and nameserver entry) it looks like it's changing the `Global` DNS settings instead of the tailscale one as I would expect (in my case the one named: `Link 3 (tailscale0)`)

**Comment by canselcik** [comment]
I am pretty sure this issue affects me as well.

Also noticed some quirks around this in Big Sur, especially if Little Snitch is running, even when configured to whitelist everything remotely related to Tailscale including the `IPNExtension.appex`.

**Comment by t3rminalVel0city** [comment]
I believe this also might be affecting me.

I have two Nameservers set in the Tailscale Admin UI, which both correspond to internal domain controllers (both on an RFC1918 address space, with a tailscale subnet router in the same space).

If I connect to tailscale on my phone via LTE, when magic dns is enabled, no inernal DNS names will resolve. If I disable magic DNS, they immediately start resolving again, I can toggle magic DNS off and on in the UI and the DNS queries will fail and start working again as I'm doing it.

Happy to assist in any troubleshooting.

**Comment by danderson** [comment]
I believe this is fixed in 1.8.0, which will roll out in a few weeks. The issue you're hitting is that we didn't have support for split DNS configurations on OSes where facilities exist to gracefully combine multiple split DNS configurations. Starting in 1.8, you'll be able to specify a config that integrates gracefully with other things configured in systemd-resolved.

**Comment by basile-henry** [comment]
I saw the blog post. Amazing work! 😄
Looking forward to trying it out in 1.8.0 👌

**Comment by basile-henry** [comment]
I have just updated tailscale to version `1.8.0`. Unfortunately it doesn't look like this new version has fixed this issue for me. :cry: 

Here I have a [gist](https://gist.github.com/basile-henry/983f787ffdfafc02d5d422f4171b8185) showing my `systemd-resolve --status` both with and without _Magic DNS_ enabled (as well as the halfway state where a nameserver is entered but _Magic DNS_ isn't enabled).

If there's any more information I can give you do tell me, I'd love to help. Tailscale is great and it'd be awesome to have DNS working with it! :smile:

**Comment by ofer-dev** [comment]
I'm having similar issue on windows with tailscale 1.8.0. Magic-dns breaks OPNsense (PFsense fork) unbound dns override (for internal name resolution). If I can help in any way do tell me.

**Comment by danderson** [comment]
@ofer-dev can you open a separate bug and include the output of `tailscale bugreport` in there, so I can take a look at logs? Windows and Linux have very separate DNS stacks, so it's probably distinct issues.

Keeping this one open for the linux issue. @basile-henry Can you run `tailscale bugreport` on the machine that's doing this and paste the output? So I can look at logs and figure out what DNS config decisions your system made. In general, from your output, it seems like Tailscale is programming the right things, but something else is deleting OpenVPN's DNS configuration (not us, we don't touch other interfaces). The key is going to be figuring out why that is happening.

**Comment by danderson** [comment]
My current guess is that you're on an older Ubuntu, and one of the pieces of software in the stack doesn't understand split DNS correctly, but we assume it does, and end up overriding all DNS instead of doing a split. I'll dig after the weekend, thank you for the detailed reports and testing!

**Comment by basile-henry** [comment]
It's Ubuntu 20.04, I try to stick to LTS releases of Ubuntu. I can find out the versions of other software in this stack for you whenever you're looking at the bugreports.

Have a nice weekend 😊

**Comment by danderson** [comment]
hmm, 20.04 is recent enough, there are no major weird things I know about... Are you using NetworkManager? If yes, are you configuring OpenVPN via the NetworkManager VPN plugin?

**Comment by basile-henry** [comment]
Yes I am using `NetworkManager`:

```bash
➜ NetworkManager --version
1.22.10
```

I use the "Import VPN connection..." option which imports from a config file. I believe that it then uses the OpenVPN plugin.
One aspect that might be relevant is that I have manually entered the associated DNS setup for that connection:

![image](https://user-images.githubusercontent.com/3369034/117566131-1dc5bf00-b0b5-11eb-8394-623f551f5508.png)

Without this DNS config for that VPN connection the VPN DNS doesn't work.

**Comment by basile-henry** [comment]
I have just updated `tailscale`:

```
➜ tailscale --version
1.8.5
  tailscale commit: 118cf0cd75f92bbe3d994a5b1587c9ea3553221b
  other commit: c6fd9c9d5657e82c2d7888804ebce0e8bd6a4556
  go version: go1.16.4-ts1b677aa
```

And everything seems to work perfectly. Great job! :smile: Thanks for this great tool!
