### ISSUE TITLE
FR: Notify users when key has expired or is about to expire.

### ISSUE THREAD

**Issue by rjhammond13** [tailscale/tailscale#12745]
### What are you trying to do?

Have users be notified that their key will expire and/or is about to expire. The notification should include direction to logout and log back in to renew their key.

### How should we solve this?

Ideas:
1. An email or app notification alerting users when their key will expire within 24 hours.
2. Log a user out when a key expires, force users to re-authenticate.

### What is the impact of not solving this?

Instead of re-authenticating, company users tend to report that either Tailscale or company file shares volumes aren't working.

### Anything else?

If an account setting exists that would notify a user of an expired key or if there's an open issue already on the topic, please let me know and close this.

**Comment by rjhammond13** [comment]
@agottardo - v1.58.2 and macOS. I can't believe I didn't check notification settings! Thank you very much for the reminder, I appreciate it.

**Comment by agottardo** [comment]
We do suggest that you allow notifications during onboarding, but we know how that goes... 🥲

**Comment by bringert** [comment]
It would be great to get (optional) email notifications before a device key expires, e.g. to avoid remote devices breaking without having to disable key expiry. A system notification isn't very useful in that situation.

**Comment by agottardo** [comment]
@bringert good idea, please open a separate issue!
