### ISSUE TITLE
Windows 11 leaks local DNS Servers

### ISSUE THREAD

**Issue by xcpn** [tailscale/tailscale#12754]
### What is the issue?

I have setup Headscale on a VPS and configured the clients to use a specific DNS service (quad9, configured both IPv4 & IPv6 addresses).

I have 2 Exit Nodes residing in different countries and when connected to Tailscale via a Windows 11 machine I leak my local DNS Servers, which leaks my country of origin. This is not happening when using an Android phone or a Linux machine.

To resolve this issue I have to manually change my Windows 11 machine's DNS to the ones listed in the Tailscale adapter settings, then there is no leaks, but obviously this is not an actual fix and probably Tailscale should be doing this by itself.

### Steps to reproduce

1. Connect to Tailscale via the tray icon
2. Choose an Exit Node (preferably one located in a different country)
3. Go to [BrowserLeaks](https://browserleaks.com/dns) and look at the listed DNS Servers

### Are there any recent changes that introduced the issue?

No.

### OS

Windows

### OS version

Windows 11 Pro - 23H2

### Tailscale version

1.68.2

**Comment by nickkhyl** [comment]
Hi @xcpn. We believe this issue has already been fixed in the [latest unstable](https://pkgs.tailscale.com/unstable/#windows), and the fix will also be included in the upcoming 1.70 release expected later this month.

**Comment by xcpn** [comment]
Thanks for letting me know @nickkhyl!
