### ISSUE TITLE
Problem with login in tailscale MacOS app

### ISSUE THREAD

**Issue by CrusherBurn** [tailscale/tailscale#12755]
### What is the issue?

When I try to login in Tailscale app on Macos, or add an account, I click the button but nothing happens, I have tried to contact support a week ago but they never replied.

### Steps to reproduce

Install Tailscale app on MacOS Monterey 12.7.5 and try to login or add an account.

### Are there any recent changes that introduced the issue?

No.

### OS

macOS

### OS version

MacOS Monterey 12.7.5

### Tailscale version

1.68.1

### Other software

I'm not running any other VPN or antivirus software. I was running cyberghost, but when Tailscale didn't login, I searched the issue on GitHub and find that other VPNs can make this problem happen, I uninstalled Cyberghost but it didn't work.

### Bug report

BUG-de208c044326c6a7631a0d28dc034fdaa608450b4f5f2b8dc41e6748282352ee-20240709113611Z-978386c12a4204ab

**Comment by agottardo** [comment]
There is something on your Mac preventing Tailscale from launching. Do you have any MDM profiles installed? Do you have Screen Time enabled? What's the output of `system_profiler SPManagedClientDataType`?

Note you're also using a really outdated macOS version.

**Comment by CrusherBurn** [comment]
The output of the code is this: Managed Client:

    com.apple.applicationaccess:

        allowExplicitContent:

          Value: 0
          State: always
          Source: com.apple.applicationaccess (User)

        PayloadUUID:

          Value: 9C543535-F7EF-4442-ABC4-B96DF4DAA5C8
          State: always
          Source: com.apple.applicationaccess (User), com.apple.applicationaccess (User), com.apple.applicationaccess (User), com.apple.applicationaccess (User), com.apple.applicationaccess (User), com.apple.applicationaccess (User)

        ratingMovies:

          Value: 100
          State: always
          Source: com.apple.applicationaccess (User)

        forceAssistantProfanityFilter:

          Value: 1
          State: always
          Source: com.apple.applicationaccess (User)

        allowBookstoreErotica:

          Value: 0
          State: always
          Source: com.apple.applicationaccess (User)

        allowedGameCenterOtherPlayerTypes:

          Value: 1
          State: always
          Source: com.apple.applicationaccess (User)

        forceAutomaticDateAndTime:

          Value: 1
          State: always
          Source: com.apple.applicationaccess (User)

        ratingTVShows:

          Value: 100
          State: always
          Source: com.apple.applicationaccess (User)

        allowAppRemoval:

          Value: 0
          State: always
          Source: com.apple.applicationaccess (User)

        allowInAppPurchases:

          Value: 0
          State: always
          Source: com.apple.applicationaccess (User)

    com.apple.familycontrols.contentfilter:

        restrictWeb:

          Value: 1
          State: always
          Source: com.apple.familycontrols.contentfilter (User)

        useContentFilter:

          Value: 1
          State: always
          Source: com.apple.familycontrols.contentfilter (User)

        filterWhitelist:

          Value: ( "http://www.google.com", "http://www.youtube.com", "http://www.virtualbox.org", "http://www.xbox.com", "http://consent.yahoo.com", "http://www.tartaglini.com", "http://www.retrostic.com", "http://www.luxitalia.eu", "http://apkpure.net", "http://www.iotitaly.net", "http://electronicstime.it", "http://support.rockstargames.com", "http://phoenixnap.com", "http://forum.italiamac.it", "http://www.movavi.com", "http://admin.aruba.it", "http://betawiki.net", "http://discord.com", "http://www.lonebullet.com", "http://www.win-rar.com" )
          State: always
          Source: com.apple.familycontrols.contentfilter (User)

        PayloadUUID:

          Value: 2148ED1F-7F85-4CB9-9F5C-9A4126D6297F
          State: always
          Source: com.apple.familycontrols.contentfilter (User)
----------------
I don't have MDM profiles, I know I'm using an outdated version of macOS...

**Comment by agottardo** [comment]
Yes, the problem is that you have Screen Time enabled. Disable web filtering in the macOS settings **and reboot your Mac** (you need to actually reboot to fix the issue).

**Comment by CrusherBurn** [comment]
I tried that and now it works. Thanks!
