### ISSUE TITLE
Tailscale Icon Is Almost Invisible While Using Light Theme

### ISSUE THREAD

**Issue by catuhana** [tailscale/tailscale#12752]
### What is the issue?

Title. The blank looking one is Tailscale's tray icon.
![image](https://github.com/tailscale/tailscale/assets/108196023/77a4ed45-dc50-4d81-91df-1e0e095e54d2)

### Steps to reproduce

1. Install Tailscale Windows app
2. Have it running in the background
3. Have Light mode enabled
4. Look at system tray

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.68.1

**Comment by dblohm7** [comment]
Our GUI framework needs to handle notification of transition between light mode and dark mode. Closing in favour of https://github.com/tailscale/walk/issues/97.
