### ISSUE TITLE
Windows client should grey out exit node selections if the device is advertised as an exit node

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#12771]
### What is the issue?

Advertising a Windows device as an exit node still shows other exit nodes in the tailnet or via Mullvad as selectable. Attempting to select an option closes the menu, silently failing.

![Untitled 1](https://github.com/tailscale/tailscale/assets/110842475/4de001fc-70c6-4258-8e9d-c5c2fd6878f2)

The devices should be greyed out to indicate they can't be used while it is running as an exit node. This is the behavior seen in the MacOS client. Additionally, attempting the same steps via the CLI generate a proper warning.

![Untitled](https://github.com/tailscale/tailscale/assets/110842475/aa720558-e885-4db8-aaa1-69e597d54ad6)

### Steps to reproduce

1. Advertise a Windows device as an exit node
2. Attempt to select an exit node from the client menu

### OS

Windows

### OS version

10

### Tailscale version

1.68+

**Comment by catmur-tvt** [comment]
I have two users with the same/similar issues... both Windows users (one on Win 10, the other on Win 11) who have only recently been onboarded with Tailscale. 
Both installed 1.68.2 and when they select an exit node, tailscale silently fails to select the exit node. I'm asking them to try 1.68.1 ... will post how that works out.

**Comment by catmur-tvt** [comment]
> I have two users with the same/similar issues... both Windows users (one on Win 10, the other on Win 11) who have only recently been onboarded with Tailscale. Both installed 1.68.2 and when they select an exit node, tailscale silently fails to select the exit node. I'm asking them to try 1.68.1 ... will post how that works out.

Rolling back to 1.68.1 made no difference. 
Have also got another win11 machine running successfully on 1.68.2, so suspect this might be a different issue :-/

**Comment by kelivel** [comment]
@catmur-tvt Can they try the latest Windows unstable at https://pkgs.tailscale.com/unstable/#windows? Generate bug reports from each and send those to support@tailscale.com. We can take a closer look from there, and can add more details to this issue if it seems your issue is related.

**Comment by catmur-tvt** [comment]
> @catmur-tvt Can they try the latest Windows unstable at https://pkgs.tailscale.com/unstable/#windows? Generate bug reports from each and send those to [support@tailscale.com](mailto:support@tailscale.com). We can take a closer look from there, and can add more details to this issue if it seems your issue is related.

Hi @kelivel - updates were sent through on ticket TSS-42242. FYI here, the unstable release (1.69.162) experienced the same issues. VPN access is up, but the selection of an exit node fails silently.

**Comment by dblohm7** [comment]
I'm in the middle of a bunch of work on the exit node menu anyway, so I'll look into this.
