### ISSUE TITLE
K8s operator does not start

### ISSUE THREAD

**Issue by j-p-k** [tailscale/tailscale#12781]
### What is the issue?

On one of my clusters, the kubernetes operator tailscale/k8s-operator:v1.68.1 deployed from the Helm chart of the same version, does not appear to start properly. The log file has a single line

`2024/07/11 13:56:02 tsnet starting with hostname "operator-name", varRoot "/root/.config/tsnet-operator"`

The operator does not show as connected on the Tailscale console nor does it update resources in the cluster.

Tailscale has previously worked on this cluster. There are two stateful sets, created by a previous version of the operator, still present and the cluster. Those are still connected to Tailscale.

### Are there any recent changes that introduced the issue?

Replaced v1.62.1 by v1.68.1. This was applied using ArgoCD with the Tailscale Helm chart.

### OS

Linux, Other

### OS version

Kubernetes 1.25, Ubuntu 20.04

### Tailscale version

1.68.1

**Comment by irbekrm** [comment]
Could you try to increase the operator log level (should be [`operatorConfig.logging=debug`](https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/chart/values.yaml#L33) if using Helm) and let us know the full log from the start?

**Comment by irbekrm** [comment]
Also, worth verifying that the OAuth credentials are valid. Have you changed anything in the operator's config when upgrading including passing different OAuth creds?

**Comment by j-p-k** [comment]
I have solved the issue by deleting the operater secret (not the oauth secret). From there, everything recovered.

**Comment by irbekrm** [comment]
Thank you for letting us know that it now works.

I've tested the `v1.62` -> `v1.68.1` upgrade via `helm install` and was not able to reproduce this.

At the moment I am not sure how to reproduce or debug this issue. If anyone else encounters it, keen to hear more.

It would also be good to know how old was the operator installation at the point when it broke.

**Comment by j-p-k** [comment]
First, let me say that I cannot reproduce the issue myself. I've seen this on one cluster only and this cluster is used for development. On this cluster, tailscale-operator v1.62 was running for 7 weeks before the failed upgrade attempt.

As far as I'm concerned, you can close the ticket. I'm not sure if I can add anything of value. Thanks for your help.

**Comment by irbekrm** [comment]
Sounds good, thank you. Do let us know if this occurs again.
