### ISSUE TITLE
FR: WordPress to work with it?

### ISSUE THREAD

**Issue by RaymondDay61** [tailscale/tailscale#12780]
### What are you trying to do?

I can ssh but like to use the WordPress app on my Android phone to log in to my WordPress at home.

### How should we solve this?

Got port 80 and 443 to work and see that though any app running.

### What is the impact of not solving this?

It's hard to post on WordPress. I have to use a text app on my phone when I get home plug in the phone to my PC and copy and paste the text in WordPress when on on my LAN.

### Anything else?

The SSH works super and it's grate that it's only device to device not the whole web that can get on it. Just wish it work for Apache to log in to a webpage ate home though your phone.

**Comment by RaymondDay61** [comment]
Wow I looked it up and installed a Plugins name "Multiple Domain" and said "Add domain" and typed in the IP of tailscale the one that starts with 100 and went on my WordPress app on my cellphone and said add a site and typed that 100 IP /blog and it works!

Turn off my Wi-Fi just to test and it still works That's grate just what I wanted. I can still get to it on my LAN PC too.

Maybe some how post this so it can help others.

**Comment by agottardo** [comment]
Seems like this is resolved? If not, feel free to reopen this.

**Comment by RaymondDay61** [comment]
On my Squarespace domain name I added the 100 IP to it and on my cell phone I can got to it's host name now. On my ubuntu server I added tailscale cert and it worked and then I had to edit the WordPress app https and it works. But when I look at the WordPress media it don't see it but if I edit it I can see the photo. I don't know why I can see the photo but if I say look at my WordPress not edit it sees the photo.

**Comment by RaymondDay61** [comment]
Just wanted to test a little video to upload it to to WordPress. I turn off Wi-Fi and got a DJI video camera and plug it in my phone with USB-C and picked a video from there to upload.

It did it. I can see it in my media but it's blank in the post.

Edit it with HTML code and it looks like this:

<figure class="wp-block-video"><video controls src="file:///data/user/0/org.wordpress.android/cache/DJI_20240711134344_0005_D.MP4"></video></figure>

The file src is wrong. Why does it do this? Any way to fix it?

But I can said add video and go to the media and pick it and add it like that.

OK I guess I can show this because no one else can use this domain name just what I have tailscale on.

The HTMI code that works looks like this:

<figure class="wp-block-video"><video controls poster="http://rday.me/blog/wp-content/uploads/2024/07/DJI_20240711134344_0005_D-mp4-image.jpg" src="http://rday.me/blog/wp-content/uploads/2024/07/DJI_20240711134344_0005_D-1.mp4"></video></figure>

But it don't have a https. Installed tailscale on my Windows 11. I though it come up with some window but have to go to Windows PowerShell and set it up there. I did the tailscale cert "desktop-XXXX and it worked.

But I can't go to https://rday.me/blog but can go to http://rday.me/blog

Seen in the Windows 11 C:\Windows\System32\drivers\ect\hosts file that Tailscale added parts. It does have the 3 Cellphone, Ubuntu server with WordPress on it and now Windows 11. Shows 3 100. IP's.

Put a # like this in the host file that looks like this:

#192.168.86.248		rday.me rday.lan rday

Saved it and now with Tailscale installed it still works! But not the https?

How do I set it up so it can use https on my Windows 11?
