### ISSUE TITLE
derp: 21.221.23.122:53654: client nodekey:09a***13d rejected: tailscaled version is too old (out of sync with derper binary)

### ISSUE THREAD

**Issue by chdeast** [tailscale/tailscale#12804]
### What is the issue?

dear:
Linux 5.16.17-sun50iw6 aarch64 GNU/Linux system, after upgrading the derper self built node installed in Docker to the latest version, cannot connect successfully. Using the "tailscale status" command displays: # Health check:
#     - not connected to home DERP region 901
Use the 'tailscale netcheck' command to check if the display is normal:
Report:
* UDP: true
* IPv4: yes, 112.20.75.201:53735
* IPv6: no, but OS has support
* MappingVariesByDestIP:
* PortMapping: UPnP
* Nearest DERP: tong
* DERP latency:
- dtae: 1.3ms   (tong)

The Derper log consistently shows that the tailscale version used is too old and rejected. Upgrading tailscale to the latest version 1.168.2 still remains the same:
2024/07/14 03:44:36 derp: 37.110.125.20:21391: client nodekey:885***22 rejected: tailscaled version is too old (out of sync with derper binary)
2024/07/14 03:44:37 derp: 37.110.125.20:21394: client nodekey:b5b***827 rejected: tailscaled version is too old (out of sync with derper binary)
2024/07/14 03:44:38 derp: 37.110.125.20:21396: client nodekey:fa9a***65b rejected: tailscaled version is too old (out of sync with derper binary)
2024/07/14 03:44:38 derp: 21.221.23.122:53654: client nodekey:*** rejected: tailscaled version is too old (out of sync with derper binary)
May I ask what the reason is and how to solve it.
thank you.

### Steps to reproduce

Remove the upgrade and use the old version of Derper and Tailscale 1.68.1 to ensure normal operation.

### Are there any recent changes that introduced the issue?

无

### OS

Linux

### OS version

orangepi3-lts 5.16.17-sun50iw6 #3.0.8 SMP Tue Sep 6 18:22:49 CST 2022 aarch64 aarch64 aarch64 GNU/Linux，Client: Docker Engine - Community  Version:    26.1.3  Context:    default  Debug Mode: false

### Tailscale version

1.68.2

**Comment by bradfitz** [comment]
Dup of #12617

"tailscaled version is too old (out of sync with derper binary)" means that the `tailscaled` you have on on the machine is older than the `derper` binary. If you're using `--verify-clients`, the version of the two pieces matters.

> upgrading the derper self built node installed in Docker to the latest version

We do not distribute derper via Docker, so I don't know what you're using, but it's not official. You can file a bug report with that repo.
