### ISSUE TITLE
tailscale 连接，系统却无法连接连接网络

### ISSUE THREAD

**Issue by 464917671** [tailscale/tailscale#12808]
### What is the issue?

tailscale 连接，系统休眠后唤醒却无法连接连接网络，关闭 tailscale ，再打开 tailscale ，网络恢复。

### Steps to reproduce

设置完tailscale，并登陆后，休眠电脑，再唤醒电脑，网络无法使用， down 再 up 网络恢复。

### OS

macOS

### OS version

14.2.1 (23C71)

### Tailscale version

1.68.1

### Other software

安全软件：avira ，但以前也使用这个软件，没有问题。现在有问题了。

**Comment by 464917671** [comment]
问题似乎解决了，把 按需 vpn 关闭就可以了，我的黑苹果 把网卡拔了。所以不能用WiFi ，按需时就行了，但还是希望 tailscale 能改进这一问题。

**Comment by agottardo** [comment]
To ensure effective communication for all users, please use English to discuss on this platform. This ensures that everyone can follow and contribute to the conversation, and helps future users find and reference your contributions. Thank you for your cooperation.
