### ISSUE TITLE
Cannot click login, tailscaled shows an error

### ISSUE THREAD

**Issue by DwifteJB** [tailscale/tailscale#12814]
### What is the issue?

Updated my windows 11 system and tailscale stopped working.

The login button no longer does anything.

Tests:

```
C:\Windows\System32>tailscale debug ts2021
10:02:10.757700 Fetching keys from https://controlplane.tailscale.com/key?v=97 ...
10:02:10.988072 Dial("tcp", "[2a05:d014:386:202:4d:f871:20f3:6602]:80") ...
10:02:11.294934 Dial("tcp", "18.159.140.118:80") ...
10:02:11.302901 Dial("tcp", "18.159.140.118:80") = 172.16.0.2:56402 / 18.159.140.118:80
10:02:11.303357 Dial("tcp", "[2a05:d014:386:202:4d:f871:20f3:6602]:80") = dial tcp [2a05:d014:386:202:4d:f871:20f3:6602]:80: operation was canceled
10:02:11.395605 controlhttp.Dial = 0xc000208110, <nil>
10:02:11.395605 did noise handshake
10:02:11.396133 final underlying conn: 172.16.0.2:56402 / 18.159.140.118:80
```

```
C:\Windows\System32>tailscaled
logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.68.2-tc3ed2ce8b-g789e6d2f8, Go 1.22.4: []string{"tailscaled"}
LogID: 0742b67da68d1cc09955c7ef6772719f05a1e70f601e2b958f9ed9d4ccb1fa51
logpolicy: using dir C:\ProgramData\Tailscale
dns: using *dns.windowsManager
running ipconfig /registerdns ...
flushing log.
logger closing down
logtail: dial "log.tailscale.io:443" failed: dial tcp [2600:1f18:429f:9305:823d:72c0:16da:fb33]:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions. (in 57ms), trying bootstrap...
WSL: found 1 distributions
trying bootstrapDNS("derp6.tailscale.com", "68.183.90.120") for "log.tailscale.io" ...
bootstrapDNS("derp6.tailscale.com", "68.183.90.120") for "log.tailscale.io" error: Get "https://derp6.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp 68.183.90.120:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
trying bootstrapDNS("derp12b.tailscale.com", "2001:19f0:5c01:48a:5400:3ff:fe8d:cb5f") for "log.tailscale.io" ...
bootstrapDNS("derp12b.tailscale.com", "2001:19f0:5c01:48a:5400:3ff:fe8d:cb5f") for "log.tailscale.io" error: Get "https://derp12b.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp [2001:19f0:5c01:48a:5400:3ff:fe8d:cb5f]:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
trying bootstrapDNS("derp4c.tailscale.com", "134.122.77.138") for "log.tailscale.io" ...
bootstrapDNS("derp4c.tailscale.com", "134.122.77.138") for "log.tailscale.io" error: Get "https://derp4c.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp 134.122.77.138:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
trying bootstrapDNS("derp8c.tailscale.com", "2a03:b0c0:1:d0::e1f:4001") for "log.tailscale.io" ...
bootstrapDNS("derp8c.tailscale.com", "2a03:b0c0:1:d0::e1f:4001") for "log.tailscale.io" error: Get "https://derp8c.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp [2a03:b0c0:1:d0::e1f:4001]:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
trying bootstrapDNS("derp12.tailscale.com", "216.128.144.130") for "log.tailscale.io" ...
bootstrapDNS("derp12.tailscale.com", "216.128.144.130") for "log.tailscale.io" error: Get "https://derp12.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp 216.128.144.130:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
trying bootstrapDNS("derp8b.tailscale.com", "2a03:b0c0:1:d0::ec1:e001") for "log.tailscale.io" ...
bootstrapDNS("derp8b.tailscale.com", "2a03:b0c0:1:d0::ec1:e001") for "log.tailscale.io" error: Get "https://derp8b.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp [2a03:b0c0:1:d0::ec1:e001]:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
logtail: upload: log upload of 17634 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/7870040d8cf9c3023a37e62fcfd70c38fcac2da3cdcc377c0de9b335775f9a69": dial tcp [2600:1f18:429f:9305:823d:72c0:16da:fb33]:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
safesocket.Listen: namedpipe.Listen: open \\.\pipe\ProtectedPrefix\Administrators\Tailscale\tailscaled: Access is denied.
```

### Steps to reproduce

1. Update windows
2. Try to run tailscale, get "please restart tailscale service"
3. Remove all tailscale files from computer, update tailscale
4. Login button breaks, tailscaled shows an error

### Are there any recent changes that introduced the issue?

Updating 

### OS

Windows

### OS version

Windows 11 Pro 23H2 (OS Build 22631.3880)

### Tailscale version

1.68.2

### Other software

Windows defender and sunshine

### Bug report

BUG-0742b67da68d1cc09955c7ef6772719f05a1e70f601e2b958f9ed9d4ccb1fa51-20240715090415Z-af273066e1abc80d

**Comment by fantian666** [comment]
I also encountered this problem. I tried entering the website directly“ https://login.tailscale.com/admin/machines ”, and logged into Google Mail on the webpage, but still couldn't display Connected, and the log in button still didn't respond, nor did it display the login status

**Comment by DEROOOOOO** [comment]
Me 2！What should we do？

**Comment by DwifteJB** [comment]
Still not fixed, tried reinstalling a few times, I can't reset windows at the moment

**Comment by hwenwur** [comment]
Same problem. I changed the --login-server, but stilll get this error. Many logs show that "dial xxxx:443 failed,  context canceled", but I can open the url from browser and curl. It may be the issue from Windows Firewall

**Comment by dblohm7** [comment]
@DwifteJB which user are you starting `tailscaled` as? I see a lot of errors in your log suggesting that it does not have the correct access rights. At the very least you need to be running as a member of `Administrators`, though some features require running as `LocalSystem`.

**Comment by liarchgh** [comment]
Same problem. I solved it by closing vEthernet adapter created by hyper-v.

**Comment by tcadd** [comment]
Had this issue, found a VPN running I thought had been disabled on that particular machine. Once it was disabled I was able to use Tailscale normally. Weird that it wouldn't even allow the app to open a web browser.

**Comment by lisiupython** [comment]
Same issue, click on windows version tailscale Log in button, nothing happens. Version1.76.6（t1edcf9d46-gd0a6cd8b2）

![image](https://github.com/user-attachments/assets/400e86b8-fce4-4d57-9f32-6e34606e5c16)

**Comment by geekeritcom** [comment]
same issue
version: 
![image](https://github.com/user-attachments/assets/e508b734-136d-46f0-8ff8-e26a2362cab9)
and I try use cmd running tailsacled show some message 
![image](https://github.com/user-attachments/assets/fd6fe0c5-8715-42d6-9884-51298675616c)

**Comment by geekeritcom** [comment]
> same issue version: ![image](https://private-user-images.githubusercontent.com/46914342/390666050-e508b734-136d-46f0-8ff8-e26a2362cab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODMzMjMsIm5iZiI6MTczMjc4MzAyMywicGF0aCI6Ii80NjkxNDM0Mi8zOTA2NjYwNTAtZTUwOGI3MzQtMTM2ZC00NmYwLThmZjgtZTI2YTIzNjJjYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OTgzMDI1YzE1ODIwYmMyNGJiMGM1MmVhYjk2NDQzY2IxMzZmMTQ2Mzg5ZTU4YWM1MTRjYzUyMzZhYzVmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5XvaeVL7VS-wN36NJb044q2Ax9JDPGCmm8cF95l1yiU) and I try use cmd running tailsacled show some message ![image](https://private-user-images.githubusercontent.com/46914342/390666580-fd6fe0c5-8715-42d6-9884-51298675616c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODMzMjMsIm5iZiI6MTczMjc4MzAyMywicGF0aCI6Ii80NjkxNDM0Mi8zOTA2NjY1ODAtZmQ2ZmUwYzUtODcxNS00MmQ2LTk4ODQtNTEyOTg2NzU2MTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNzRmZGQ4ZWIzMWEyYzFkZjYzNzYxNDExNDg3ZjhlMmQzMzIxMjQ0YmJjYTRjYjQyMDUwYjg5OGM3ZmQ1MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p4qNEQYLvbrVEOK6VjDZSt8WaiKkK-ADV90Ja6_n0Fs)

now I solved this issue and share the reason, hope help some people like me : I try everyThing on web don't solve my problem,but one idea just tips me(https://github.com/tailscale/tailscale/issues/13886#issuecomment-2433764104)
I change my conputer network from company to my phone hot,and login success.
