### ISSUE TITLE
Outgoing connection on Synology no longer working

### ISSUE THREAD

**Issue by steevehuin** [tailscale/tailscale#12839]
### What is the issue?

I've had the version on Synology Package Center (I think 1.58), and that was working perfectly. I've decided to upgrade my Synology NASes to the latest version (i.e. 1.68.2) and now outgoing connection are no longer working.

### Steps to reproduce

Upgrade to 1.68.2 from 1.58.0 - it is successfully connected to the network, and it is possible to use it as an exit node and to ping it from a client (windows client for example).

I have successfully executed /var/packages/Tailscale/target/bin/tailscale configure-host and synosystemctl restart pkgctl-Tailscale.service

The service seems to be running in non user mode:
`tailsca+  8831  0.6  0.3 1250580 29028 ?       Sl   15:50   0:00 /volume1/@appstore/Tailscale/bin/tailscaled --state=/volume1/@appdata/Tailscale/tailscaled.state --socket=/volume1/@appdata/Tailscale/tailscaled.sock --port=41641`

/dev/net/tun seems accessible:
```
drwxr-xr-x 2 root root 60 Jul 17 14:12 /dev/net
crw-rw-rw- 1 root root 10, 200 Jul 17 14:12 /dev/net/tun
```
It can ping itself:
sudo ping 100.82.224.15
```
PING 100.82.224.15 (100.82.224.15) 56(84) bytes of data.
64 bytes from 100.82.224.15: icmp_seq=1 ttl=64 time=0.051 ms
64 bytes from 100.82.224.15: icmp_seq=2 ttl=64 time=0.048 ms
64 bytes from 100.82.224.15: icmp_seq=3 ttl=64 time=0.037 ms
^C
--- 100.82.224.15 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 3ms
rtt min/avg/max/mdev = 0.037/0.045/0.051/0.008 ms
```

But pinging another device in the network fails
```
 sudo ping 100.65.238.33
PING 100.65.238.33 (100.65.238.33) 56(84) bytes of data.
^C
--- 100.65.238.33 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1001ms
```

```
 sudo traceroute -d 100.65.238.33
Password:
traceroute to 100.65.238.33 (100.65.238.33), 30 hops max, 60 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  *^C
```

These are the ip routes set by tailscaled:
```
ip route show table all | grep tail
100.65.238.33 dev tailscale0  table 52
100.91.104.36 dev tailscale0  table 52
100.100.100.100 dev tailscale0  table 52
100.104.51.88 dev tailscale0  table 52
100.127.56.106 dev tailscale0  table 52
local 100.82.224.15 dev tailscale0  table local  proto kernel  scope host  src 100.82.224.15
fd7a:115c:a1e0::/48 dev tailscale0  table 52  metric 1024
fd7a:115c:a1e0::cc01:e011 dev tailscale0  proto kernel  metric 256
ff00::/8 dev tailscale0  table local  metric 256
```

Firewall rules are in place to allow any traffic on any interface 100.64.0.0 with subnet mask 255.192.0.0.

I am out of ideas on what the problem is - and see no path forward since upgrading/downgrading is not fixing the problem (I've also tried 1.68.0)

### Are there any recent changes that introduced the issue?

Upgrade from 1.58 to 1.68.2. 
Downgrade does not fix the issue (deleting the package and reinstalling 1.58)

### OS

Synology

### OS version

7.2-64570 update 1

### Tailscale version

1.68.2

### Bug report

BUG-d7989ede746ff7cd07283efdf1cefef15dd3a2e278bc55bcc9d75aff2afcb6a2-20240717141435Z-7120a27a148e8396

**Comment by markstos** [comment]
Tailscale quit working for me today, too. 

Arch Linux. Package history says I upgraded from 1.68.1.

With `1.68.2`, `systemctl status` would still report "Connected", the TailScale web console would report "connected", set SSH connections would fail.

**Comment by steevehuin** [comment]
I've upgraded to 1.70.0 and the issue persists. I suspect something gets "permanently" corrupted (i.e. that is not fixed by uninstall or upgrade) on the system during the upgrade and now I am stuck with Tailscale partially working.

**Comment by steevehuin** [comment]
The issue has been resolved but it's unclear what the issue was.

**Comment by markstos** [comment]
If the issue is a general Linux issue and not specifically a Synology issue, I am still not able to connect to a Tailnet on Arch Linux and do not consider the issue resolved.

**Comment by markstos** [comment]
My issue may have been that I dared to re-authenticate. My access is restored. Guess what? TailScale removes all your ACL tags upon re-authentication and doesn't tell you, breaking your access to anything that requires your node to be tagged. You'll need to notify a TailScale admin and wait for them get online and add back your tags. 

https://github.com/tailscale/tailscale/issues/6997
https://github.com/tailscale/tailscale/issues/6058
