### ISSUE TITLE
FR: Container Login Server option

### ISSUE THREAD

**Issue by ddanon** [tailscale/tailscale#12831]
### What are you trying to do?

I host a Headscale server and would like to use the Tailscale container to mesh connect my decentralized services and hardware. Unfortunately, it is unclear to me how to change the login server when running the container. 

It appears as though only options related to the `tailscale set` command are exposed, whereas I appear to need access to `tailscale login` flags to achieve what I'm after.

### How should we solve this?

Ideally, there would be a new environment variable. Something like `LOGIN_SERVER` would be perfect. 

### What is the impact of not solving this?

I am currently maintaining a long list of nodes and ports to ensure that I can make use of all elements on my tailnet. To be fair -- the only cost is time, not functionality.

### Anything else?

Here are the main pages where I've been getting information:
- [dockerhub](https://hub.docker.com/r/tailscale/tailscale)
- [tailscale container documentation](https://tailscale.com/kb/1282/docker)
- [tailscale cli docs](https://tailscale.com/kb/1080/cli#login)

**Comment by irbekrm** [comment]
@ddanon I haven't tried this, but I think you should be able to achieve this using tailscaled configfile https://github.com/tailscale/tailscale/blob/v1.69.0-pre/ipn/conf.go#L19

Tailscale containers can be given a dir in which a configfile is mounted (as an alternative to providing separate args for tailscaled) via [`TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR`](https://github.com/tailscale/tailscale/blob/v1.69.0-pre/cmd/containerboot/main.go#L55) env var. This is currently mostly used by the Kubernetes operator, but in future we want to document and better support this configuration mechanism

**Comment by ddanon** [comment]
Wow, thanks for the quick response! I would agree, the following line in the file you linked looks like a winner:

 `ServerURL *string  `json:",omitempty"` // defaults to https://controlplane.tailscale.com`

I will give it a go and post a write up with what I find.

**Comment by ddanon** [comment]
A minor update, but some progress. 

Quick aside: I'm not sure that my HuJSON config file is valid and I can't find a good way to validate it. For now I'm just using straight JSON since I understand HuJSON to be a superset. I got a start on writing my own in a fork. I'm planning on adding some example config files and associated tests with them if I get time. 

Anyway, back to the progress.

I found the following in `cmd/containerboot/main.go`:

```go
//     TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR: if specified, a path to a
//     directory that containers tailscaled config in file. The config file needs to be
//     named cap-<current-tailscaled-cap>.hujson. If this is set, TS_HOSTNAME,
//     TS_EXTRA_ARGS, TS_AUTHKEY,
//     TS_ROUTES, TS_ACCEPT_DNS env vars must not be set. If this is set,
//     containerboot only runs `tailscaled --config <path-to-this-configfile>`
//     and not `tailscale up` or `tailscale set`.
//     The config file contents are currently read once on container start.
//     NB: This env var is currently experimental and the logic will likely change!
```

By process of elimination I have determined that `the config file needs to be named cap-<current-tailscaled-cap>.hujson` means that the config file must be named `cap-[some integer??].hujson`. As I'll show later, I have the same file under two other names (`cap-alpha0.hujson` and `config.hujson`) which correspond to the output below.

```bash
[tailscale-nginx] | boot: 2024/07/18 03:42:18 skipping file "cap-alpha0.hujson" in tailscaled config directory "/custom_config": expected integer
[tailscale-nginx] | boot: 2024/07/18 03:42:18 skipping file "config.hujson" in tailscaled config directory "/custom_config": input does not match format
```

This led me to produce the following cap-1.hujson (name critical!) and compose.yml files respectively:

```cap-1.hujson
{
  "Version": "alpha0",
        "Locked": true,

        "ServerURL": "hs.hemge.org",
        "AuthKey": "changeme",
        "Enabled": true,

        "Hostname": "contailner",

        "AcceptDNS": true,
        "AcceptRoutes": false

}
```

```compose.yml
services:
  tailscale-nginx:
    image: docker.io/tailscale/tailscale:latest
    hostname: tailscale-nginx
    environment:
      # The following 'must not be set' along with a config file
      # according to cmd/containerboot/main.go, otherwise:
      # `tailscale set` and `tailscale up` fail to run
      #- TS_HOSTNAME
      #- TS_ROUTES
      #- TS_ACCEPT_DNS
      #- TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR=/custom_config
    volumes:
      - ./tailscale-nginx/state:/var/lib/tailscale:rw
      - ./config:/custom_config:Z
      - /dev/net/tun:/dev/net/tun:ro
    cap_add:
      - net_admin
      - sys_module
    privileged: true
    restart: unless-stopped

  ## Insert service here
  nginx:
    image: docker.io/nginx
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
```

I have a meaningful error, but still trying to fix it.

```bash
$ podman-compose up --force-recreate 
hd-client_nginx_1
hd-client_tailscale-nginx_1
hd-client_nginx_1
hd-client_tailscale-nginx_1
6f030b618eda9a1cf045ec067bc0b5df4138e56eca03d38d338d010622166cbf
e951774208d06eb643ae21b2289c2b361bf31f5312c729ca57890e3f201c06d5
9ef9787b99becd39bf9d20e0e6128e6644b81b0cd1731b9a70a29f58c442769b
0aa7f3f470440e9ec9999f31b9e2069d0406661600af47fbfff0a6527964260a
[tailscale-nginx] | boot: 2024/07/18 03:42:18 skipping file "cap-alpha0.hujson" in tailscaled config directory "/custom_config": expected integer
[tailscale-nginx] | boot: 2024/07/18 03:42:18 skipping file "config.hujson" in tailscaled config directory "/custom_config": input does not match format
[tailscale-nginx] | boot: 2024/07/18 03:42:18 Using tailscaled config file '\x01' for capability version 'a'
[tailscale-nginx] | boot: 2024/07/18 03:42:18 invalid configuration: error validating whether tailscaled config directory "/custom_config/" contains tailscaled config for current capability version "tailscaled": stat /custom_config/tailscaled: no such file or directory. If this is a Tailscale Kubernetes operator proxy, please ensure that the version of the operator is not older than the version of the proxy
[nginx]           | Error: unable to start container 0aa7f3f470440e9ec9999f31b9e2069d0406661600af47fbfff0a6527964260a: cannot get namespace path unless container 9ef9787b99becd39bf9d20e0e6128e6644b81b0cd1731b9a70a29f58c442769b is running: container is stopped
```

There also seems to be a capability number in  `tailcfg/tailcfg.go` which acts as a simplified version increment, but changing the config name to `cap-102.hujson` (the most recent capability number in that file is 102) does not work.

Solution TBD but I'm happy to see the comments are clear and helpful. I think I should be able to get through this pretty quickly once I'm a little more familiar with the codebase. As always any help or feedback is greatly appreciated!

**Comment by irbekrm** [comment]
Hi @ddanon sorry for the difficulty in getting it working - we are currently only using this in our own automation for kube, but should come up with better docs and easier usage for other users.

> There also seems to be a capability number in tailcfg/tailcfg.go which acts as a simplified version increment, but changing the config name to cap-102.hujson (the most recent capability number in that file is 102) does not work.

That does not work because it's too new I think- we haven't yet released stable containers from a version that bumps it to 102.
The latest cap version that the `latest` image tag works is [97](https://github.com/tailscale/tailscale/blob/v1.68.2/tailcfg/tailcfg.go#L141).

Apart from that your configs look correct- keen to hear if it works with a `cap-97.hujson` file?

**Comment by ddanon** [comment]
Thanks again for the quick response! I'll give 97 a shot later today

**Comment by ddanon** [comment]
Final instructions for anyone following behind me.

Assumptions:
- you want to create a services user to run these under
- you're using rootless podman(-compose) for both the headscale server and the tailscale container client (like I did)
- you already have a running headscale server, built from: _**docker.io/headscale/headscale:0.23.0-alpha12-debug**_

1. [on the running server] create the user

```bash
# assuming your headscale container is called headscale-ct
podman exec headscale-ct headscale users create services
```

3. [on the running server] create the authkey

```bash
# assuming your headscale container is called headscale-ct
podman exec headscale-ct headscale authkey create -u services
```

5. [on the client] copy the compose.yml (now with pinned sha hash so this shouldn't break later)

```compose.yml
services:
  tailscale-nginx:
    image: docker.io/tailscale/tailscale@sha256:a0d1a9ed2abfacf905c0e3423aea00181064162e548f875f422a03924b9cc5c4
    hostname: tailscale-nginx
    environment:
      # The following 'must not be set' along with a config file
      # according to cmd/containerboot/main.go, otherwise:
      # `tailscale set` and `tailscale up` fail to run
      #- TS_HOSTNAME
      #- TS_ROUTES
      #- TS_ACCEPT_DNS
      #- TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR=/custom_config
    volumes:
      - ./state:/var/lib/tailscale:rw
      - ./config:/custom_config:Z
      - /dev/net/tun:/dev/net/tun:ro
    cap_add:
      - net_admin
      - sys_module
    privileged: true
    restart: unless-stopped

  ## Insert service here
  nginx:
    image: docker.io/nginx
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
```

6. [on the client] copy the cap-97.hujson to ./config/ relative to the compose.yml file, replacing the ServerURL and AuthKey values.

```json
{
  "Version": "alpha0",
        "Locked": true,

        "ServerURL": "https://[your domain here!!]",
        "AuthKey": "replace this string with the authkey from step 3!!",
        "Enabled": true,

        "Hostname": "contailner",

        "AcceptDNS": true,
        "AcceptRoutes": false

}
```

Final file structure is as follows:

```
(some directory)
|___ compose.yml 
|___ config/
|      |___ cap-97.yml
|___ state/
|   |___ (some autogenerated stuff)
```

As always, don't take my word for it. Read the docs if anything seems off!

- [headscale - running on docker docs](https://github.com/juanfont/headscale/blob/main/docs/running-headscale-container.md)

**Comment by ddanon** [comment]
Last note, I made a [repo](https://github.com/ddanon/hd-client) to hold these files and share with others. I'm happy to improve this as needed. Feel free to file an issue over there.

**Comment by irbekrm** [comment]
Thank you for leaving all the comments and instructions!

I think we need to work on making the configfile easier to use

**Comment by ddanon** [comment]
If you'd like some help I would be glad to contribute! Seems like something that needs a little planning and coordination though.

Currently working on a little tool (partially to learn Go) to generate config files by pulling from dockerhub docs rather than storing a finite set of static configs (like in my hd-client repo).
