### ISSUE TITLE
How users log in to your tailnet. Contact support to change this. --- We are changing from one OKTA tenant to another OKTA tenant

### ISSUE THREAD

**Issue by vvangaebsi** [tailscale/tailscale#12845]
### What are you trying to do?

Currently the users are using the OKTA Enspire tenant and now we want to move it to OKTA goempyrean Tenant

### How should we solve this?

Help us make this change as currently Im admin and I coudln't see any SSO settings

### What is the impact of not solving this?

We are retiring enspire OKTA and this will break the SSO

**Comment by agottardo** [comment]
This is an issue tracker and customer-specific matters cannot be addressed here. You can contact support at https://tailscale.com/contact/support#support-form
