### ISSUE TITLE
go.mod checksum mismatch when using GOPROXY=direct

### ISSUE THREAD

**Issue by paralin** [tailscale/tailscale#12859]
### What is the issue?

When using GOPROXY=direct we get the following checksum error:

```
verifying [fybrik.io/crdoc@v0.6.3](http://fybrik.io/crdoc@v0.6.3): checksum mismatch
    downloaded: h1:Awi+v+URtj5DvPr0LLdVrW2Nn9/G1Y7aGpUPG1IATE4=
    go.sum:     h1:jNNAVINu8up5vrLa0jrV7z7HSlyHF/6lNOrAtrXwYlI=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

### Steps to reproduce

```
git clone https://github.com/tailscale/tailscale
cd tailscale
export GOPROXY=direct
go mod vendor
```

### OS

OS Agnostic, both Linux & Mac are affected.

### Tailscale version

main: 54f58d114332c1075133061764265d30455f6348
v1.70.0 is also affected.

### Steps to fix

While not a solution for the Tailscale repo as this breaks "go install" see https://github.com/golang/go/issues/44840

add to go.mod:

```
replace fybrik.io/crdoc => github.com/fybrik/crdoc edcf4b04e3c32859db138552b39e93bb56b96046 // v0.6.3
```

then go mod tidy

### References

Issue was first seen on [buildroot mailing list](https://patchwork.ozlabs.org/project/buildroot/patch/20240719030537.3156999-1-james.hilliard1@gmail.com/#3348553)

**Comment by paralin** [comment]
Issue was first seen on buildroot mailing list: https://patchwork.ozlabs.org/project/buildroot/patch/20240719030537.3156999-2-james.hilliard1@gmail.com/

**Comment by bradfitz** [comment]
@irbekrm, @maisem, can we just remove that `//go:generate` (from 45d27fafd6ff) and its tool dep for now until we know what's up with that dependency changing its tag?

**Comment by irbekrm** [comment]
@bradfitz we can remove it https://github.com/tailscale/tailscale/pull/12862 and I can replace it with another tool in a follow up.

I cannot reproduce this issue, but I am assuming that it can only be reproduced if someone has the offending version in local cache. I don't see anything in their issues, but looking at [this](https://github.com/fybrik/crdoc/commit/a7342680303bf41e726018714ea1021d6f4cfaaf) and the [0.6.2](https://github.com/fybrik/crdoc/commits/v0.6.2) commit sequence perhaps they changed what the `0.6.2` tag points at.

**Comment by tomhjp** [comment]
https://github.com/elastic/crd-ref-docs might be worth considering as a fairly like-for-like replacement. The official k8s generator seems to take OpenAPI specs as input.

**Comment by paralin** [comment]
@irbekrm It works now on the latest master commit for that dependency, however,

I am now seeing a different error with:

GOPROXY=direct go mod vendor

```
go: tailscale.com/internal/tooldeps imports
        github.com/golangci/golangci-lint/cmd/golangci-lint imports
        github.com/golangci/golangci-lint/pkg/commands imports
        github.com/golangci/golangci-lint/pkg/lint/lintersdb imports
        github.com/golangci/golangci-lint/pkg/golinters imports
        github.com/go-critic/go-critic/checkers tested by
        github.com/go-critic/go-critic/checkers.test imports
        github.com/go-critic/go-critic/checkers/internal/linttest imports
        github.com/go-toolsmith/pkgload: gvisor.dev/gvisor@v0.0.0-20240306221502-ee1e1f6070e3: invalid version: unknown revision ee1e1f6070e3
```

**Comment by paralin** [comment]
I am seeing a lot of other checksum misses on other projects... For example with goreleaser I get:

- github.com/anchore/go-macholibre => checksum mismatch
- github.com/anchore/quill => checksum mismatch

This is after `go clean -modcache` (no module cache locally).

Is something broken on a deeper level with the checksums and GOPROXY=direct ??

**Comment by paralin** [comment]
Issue reproduction:

```bash
docker run --rm -it library/golang:1.22.5-bookworm

git clone https://github.com/tailscale/tailscale
cd ./tailscale
git checkout 
export GOPROXY=direct
go mod tidy
```

Results in:

```
verifying fybrik.io/crdoc@v0.6.3: checksum mismatch
        downloaded: h1:Awi+v+URtj5DvPr0LLdVrW2Nn9/G1Y7aGpUPG1IATE4=
        go.sum:     h1:jNNAVINu8up5vrLa0jrV7z7HSlyHF/6lNOrAtrXwYlI=
```

This is causing issues as we try to integrate Tailscale into a [buildroot](https://buildroot.org) package, because we use GOPROXY=direct there to always clone deps from Git.

**That said, this is now fixed on the latest main branch!**

So I will close this issue, but please spin a new v1.70.1 release soon @irbekrm @bradfitz so we can release it in Buildroot.

Thanks again-

**Comment by tomhjp** [comment]
Thanks for confirming @paralin! If all testing goes smoothly, a new client release is due this week.

OOI what are the specific reasons for requiring `GOPROXY=direct` in this case? I don't think it's an unreasonable thing to do, but interested to learn about the requirements in this use case.
