### ISSUE TITLE
"Connect" button on Tailscale Android app is unresponsive when "Always-on VPN" is set for non-Tailscale VPN apps

### ISSUE THREAD

**Issue by joshuacwnewton** [tailscale/tailscale#12850]
### What is the issue?

When following the [Android installation instructions](https://tailscale.com/kb/1079/install-android), I expected to see "prompts to install a VPN configuration". However, no prompts appear -- after "Get Started", it sends me right to the main screen:

<details>

![image](https://github.com/user-attachments/assets/f04d9333-3b5f-43eb-b73f-87f046e454d5)

</details>

Clicking "Connect" (or "Connect to VPN") gives no response (no pop-ups, no error messages).

I would expect it to still be possible to setup a VPN configuration. Or, if it's mandatory to uninstall other VPN apps, I would expect a pop-up of some kind providing guidance.

### Steps to reproduce

Have NextDNS installed, and configure NextDNS as the "always-on VPN".

Due to the fact that NextDNS conflicts with Tailscale re: the "VPN" settings, I figured that NextDNS was probably the culprit. So, I removed NextDNS's configuration from the VPN settings page within Android, but the problem persisted. (Note that NextDNS re-inserts itself into the VPN settings page on reboot, but still, the VPN settings page was entirely empty in between reboots.)

It was only when I fully uninstalled the NextDNS app entirely that Tailscale's behavior changed. (After removing NextDNS, "Connect" now prompts the VPN configuration popup. And, installing Tailscale from scratch prompts the VPN configuration on first launch as well.) After following the prompts, Tailscale works exactly as expected with 0 issues.

((Side note: I was planning on uninstalling NextDNS anyway, as I had already set up the Tailscale-NextDNS integration. But, I didn't realize that uninstalling NextDNS was a mandatory step prior to setting up Tailscale.))

### OS

Android

### OS version

LineageOS 20/21 (Android 13/14)

### Tailscale version

1.68.2-tc79c500c7=g242d97ac2ac

### Other software

NextDNS, of course! (Might be worth mentioning this on the "non-exhaustive other software" list.)

### Bug report

BUG-546b60f1216d37521bff1fe8cdabdc50e5bbee29115e7b37dbc8f0e57637e5bf-20240718031709Z-d5c1dc26b0d5382d

**Comment by brokenalarms** [comment]
Was led here looking for a fix for this issue. Mine happens with Proton VPN - it looks like the issue is 'connect' button just doesn't work at all if the "always on" option is chosen for any other VPN.

Fine to turn it off if needed, but without any indication of what the issue was, Tailscale just appears broken and I only happened to find a solution by stumbling across this thread.

![Screenshot_20240722-102421](https://github.com/user-attachments/assets/bd2107fd-3716-4b23-b5a4-5c1ec04ce887)

**Comment by coopbri** [comment]
Same issue, this "fix" makes sense and is no problem but the Tailscale UI should indicate this on the Android build (either as a dialog or just add a note in the copy on the connect screen).

**Comment by ridai260** [comment]
Same issue, Android 15.

**Comment by felipereyel** [comment]
Same issue. Samsung s23 Android 14

**Comment by ashy1227** [comment]
I'm having this same issue despite not not even having another VPN installed—does anyone know what's wrong? :(

**Comment by fazen** [comment]
Same issue. Motorola g85 Android 15. I uninstalled NordVPN and reboot before trying again.

**Comment by ashy1227** [comment]
I also have a Motorola phone, and after looking up the issue initially, I found a Reddit thread describing the same issue by someone who actually had the exact same model phone as me (2023 Moto G Stylus 5G) I'm wondering if it's a Motorola-specific issue?

**Comment by ashy1227** [comment]
Found the Reddit thread: <https://www.reddit.com/r/Tailscale/comments/1ezgj3p/android_cannot_get_past_this_screen/>

Same exact issue– I press the button and get no feedback whatsoever :(

**Comment by brokenalarms** [comment]
I have a Pixel 8, not a Motorola phone. It's a software issue, the hardware shouldn't really have anything to do with it.

**Comment by ashy1227** [comment]
> I have a Pixel 8, not a Motorola phone. It's a software issue, the hardware shouldn't really have anything to do with it.

Yeah, but you said yours resolves itself when you turn off protonVPN—I dont even have a VPN installed and it still doesn't work, so I'm wondering if maybe motorola's version of android messes with how VPNs work or something that causes it to not work properly? I'm not really sure what else the issue could be

**Comment by pgk83** [comment]
I have a same error and I found glass wire is the cause on my pixel9 phone.
