### ISSUE TITLE
iOS: Finder "Tailscale" not available

### ISSUE THREAD

**Issue by Haarolean** [tailscale/tailscale#12868]
### What is the issue?

Hi, on my ios/ipados devices, I got "Tailscale" in Finder. Clicking there says "authentication required" first, proceeding says "the feature is currently unavailable". I'm not even sure what I am supposed to see there.
P.S. Taildrop is enabled on my network and generally works on all devices.

<details>
  <summary>Screenshots</summary>

![IMG_8882](https://github.com/user-attachments/assets/96a477ef-a600-4e4e-8c3d-b0c2f79cc762)

![IMG_8883](https://github.com/user-attachments/assets/2c32b3d1-5ce3-4d49-b628-40370d0daf2c)
  
</details>

### OS

iOS

### OS version

17.5.1

### Tailscale version

1.68.2

### Bug report

BUG-116f0ab36d3a4cc6296ee2e17ff817d6832b8270ca2097e14296116ed21fe7da-20240719201554Z-b71ea7f074dbc931

**Comment by agottardo** [comment]
You're looking at unfinished UI for the [Taildrive](https://tailscale.com/kb/1369/taildrive?tab=ios) feature. It will start working if you enable it in ACLs.
