### ISSUE TITLE
Ability to use as a proxy (without VPN)

### ISSUE THREAD

**Issue by avently** [tailscale/tailscale#1287]
**Is your feature request related to a problem? Please describe.**

Hello. I made an app with client-server architecture which can be used on PCs and Android. In some situations (mobile networks) I need to have a connection through CGNAT and tailscale is the best tool here (because DDNS can't help in this case). It works correctly but the problem is that I need to setup VPN connection on both sides. This limiting the ability to use another VPN service which may be needed for my life scenarios. Also having enabled VPN on Android all the time is not something I want to see in status bar and to deal with inability to use DNS-over-TLS.

**Describe the solution you'd like**

In my case I have an HTTPS connection between client and server (self-signed certs) so I don't need another layer of encryption. Same applies to situation when users use SSH: the data is safe anyway without VPN. So the solution of the problem would be an ability to disable VPN but enable proxy with locally bound remote peers to, for example, 127.0.0.1:12345. The same thing as you do now but without globally enabled VPN connection. I read some articles about how tailscale works and looks like the encryption that is used before successfully initiated connection can still be used here without problems even without VPN so disabling VPN will not break privacy.

**Describe alternatives you've considered**

I'm not sure what alternatives to the proxy can be considered. Maybe you know such alternatives.

What do you think?

**Comment by bradfitz** [comment]
Not sure I follow. Would a pure userspace version with a SOCK5 proxy for outgoing connections work? That's #707.

**Comment by avently** [comment]
@bradfitz interesting idea. I'm not sure how you made such feature but does it mean I will be able to connect to remote device without specified proxy server directly like I can do with any IP address? Or I need to setup socks5 proxy in the app first?
I mean, can I just enter IP address of remote machine bound to current machine in a browser and get an answer from remote machine? Like https://127.0.0.123:4567? If so, this is great.

Currently your changes aren't merged upstream, right? Do you plan to merge them?

**Comment by josharian** [comment]
If you’re looking for peer to peer communication without the vpn part, webrtc might work for you. Pion is a Go implementation.

**Comment by avently** [comment]
@josharian I don't need webrtc at all. The text I wrote about an access via browser is just an example of the idea proxyless access via using just a local ip and port for accessing remote device. 
So the idea is to access remote device by using any port and any service in it without VPN.

**Comment by DentonGentry** [comment]
The SOCKS5 proxy mentioned in an earlier comment has had some amount of work done on it and is still being worked on now, but has not merged nor available for use quite yet.

I don't fully understand the original request but just in case: the subnet router may be relevant if you haven't already seen it: https://tailscale.com/kb/1019/subnets
A system with the Tailscale client installed can route to its local LAN. This allows the connection to go over the Tailscale network until the last hop and then be routed to the destination, to communicate with endpoints that don't have a Tailscale client installed.

**Comment by bradfitz** [comment]
Closing this as a dup of #707. If we misunderstand, let us know.
