### ISSUE TITLE
Account login name change detected (from Mango1151 to Lemon1151) that requires a login and tailnet rename, please contact support to resolve this issue REQ-1a4b72b51-28b7-4027-8f19-55d14c4e39cc

### ISSUE THREAD

**Issue by Lemon1151** [tailscale/tailscale#12881]
### What is the issue?

Account login name change detected (from Mango1151 to Lemon1151) that requires a login and tailnet rename, please contact support to resolve this issue
REQ-1a4b72b51-28b7-4027-8f19-55d14c4e39cc

**Comment by kelivel** [comment]
Hi @Lemon1151, our Support team can help sort out the GitHub username change on your tailnet. Drop a line at http://www.tailscale.com/support and someone will be in touch soon.
