### ISSUE TITLE
Uninstall does not remove Tailscale Wintun interface on Windows 10

### ISSUE THREAD

**Issue by jucor** [tailscale/tailscale#1290]
**Describe the bug**
After uninstalling Tailscale, the Tailscale interface remains in the list of interfaces and cannot be deleted.

**To Reproduce**
1. Install Tailscale on Windows 10.
2. Uninstall it with the provided uninstaller.
3. Check the list of interfaces in "Network connections" .
4. See Tailscale interface still there.
5. Right-click, see "Delete" is blocked.
6. Click "Properties", get "unexpected error".

**Expected behavior**
Expecting the interface to be removed after uninstall.
Expecting any leftover interface to be deletable with context menu.
Expecting properties box to show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/660037/107144840-bffacd00-6935-11eb-8b65-63bf965eaca5.png)
![image](https://user-images.githubusercontent.com/660037/107144845-cab56200-6935-11eb-90d8-67b3ba4f7468.png)

**Version information:**
 - Device: Lenovo Thinkpad Carbon X1 6th Gen
 - OS: Windows 
 - OS version: Windows 10 20H2
 - Tailscale version: confirmed with 1.4.0, 1.3.13, and 1.2.0

**Additional context**
Might be linked to #474 and "Error creating interface: cannot create a file when that file already exists".
Logs sent by email today to support@.

**Comment by bradfitz** [comment]
I thought that was fixed sometime in the 1.3.x dev series for 1.4.0. We'll take a look. Thanks for the report!

/cc @peske

**Comment by 33b5e5** [comment]
@jucor FYI as a workaround, I discovered you can remove the interface via Device Manager > Network Adapters. This will also remove it from Network Connections.

**Comment by jucor** [comment]
Nice, did you manage a fix?

**Comment by bradfitz** [comment]
Yes. The windows installer isn't open source so you can't see the link. It'll be in a future release.

**Comment by jucor** [comment]
Awesome, thanks!

**Comment by lingmann** [comment]
> @jucor FYI as a workaround, I discovered you can remove the interface via Device Manager > Network Adapters. This will also remove it from Network Connections.

This helped me when I encountered this issue when running Tailscale 1.6.0 and having to do a windows 10 recovery rollback of the most recent 'quality' updates. After the rollback and rebooting, I was unable to successfully start Tailscale or fully uninstall it (the interface persisted). However removing the interface via Device Manager and then re-installing Tailscale worked like a champ.

**Comment by cleverestx** [comment]
I cannot remove the tunnel adapter and it does not appear in Device manager > Network adapter...what else can I do?

**Comment by DentonGentry** [comment]
So you uninstalled Tailscale.
You still see it in Network Connections?

<img width="518" alt="Screen Shot 2021-09-16 at 3 37 36 PM" src="https://user-images.githubusercontent.com/1140756/133694473-86212d31-daf7-40af-9a7a-cd3dd22b3f9a.png">

and you don't see it in the Device Manager?
<img width="309" alt="Screen Shot 2021-09-16 at 3 38 46 PM" src="https://user-images.githubusercontent.com/1140756/133694570-ccb870cb-8e9b-4110-982d-714670ed29a9.png">

**Comment by cleverestx** [comment]
Sorry NM I didn't see the uninstaller in control panel so I thought it was
uninstalled...but it wasn't... I had to find it in the actual programs
folder to remove it. It's gone. Thanks
