### ISSUE TITLE
Tailscale hide real domain name so Clash can not work properly anymore

### ISSUE THREAD

**Issue by shenmo7192** [tailscale/tailscale#12903]
### What is the issue?

Clash is a traffic proxy tool. It can get the domain name I'm visiting and forward the traffic to different nodes as I wish. After the upgrade of tailscale, I found clash can not get real domain name anymore. Instead get only IPs. It works well on 1.68.2, but after i tried to downgrade it to 1.68, it does not works too

### Steps to reproduce

Install Clash for Windows , install Service mode and start TUN mode

### OS

Linux

### OS version

Debian 12

### Tailscale version

1.70.0

### Other software

Clash for Windows

**Comment by uwuja** [comment]
The maintainers of this project: You don’t need to fix this ‘issue’ , which is garbage.The animal ([@shenmo7192](https://github.com/shenmo7192) )did not use Debian 12.It used a garbage Chinese domestic system ‘ deepin’ , which is based on Debian 12. He hates America and he likes the CCP.He even uses the cloud servers in the US to distribute garbage debian packages, which have computer viruses and garbage softwares.He is very evil. I know Go is a good language,I am learning it too.But this animal isn’t deserve to use any software written in Golang.
The issue probably only happens on Chinese garbage systems like deepin , UOS , and kylin. Other systems based on debian probably don’t have this issue.
So you don’t need to care it , just ignore and close the issue. God bless America!✝️🇺🇸

**Comment by bradfitz** [comment]
> It works well on 1.68.2, but after i tried to downgrade it to 1.68, it does not works too

There were no changes between 1.68 and 1.68.2 in this area.

I'm not sure what to tell you. We always send SNI in TLS requests and Host headers in the HTTP cleartext upgrades to ts2021 Noise. That isn't obscured.

Maybe Clash doesn't handle the ts2021 upgrade and the race is sometimes going one way vs the other way. Try setting env `TS_FORCE_NOISE_443=1`?

**Comment by shenmo7192** [comment]
> > It works well on 1.68.2, but after i tried to downgrade it to 1.68, it does not works too
> 
> There were no changes between 1.68 and 1.68.2 in this area.
> 
> I'm not sure what to tell you. We always send SNI in TLS requests and Host headers in the HTTP cleartext upgrades to ts2021 Noise. That isn't obscured.
> 
> Maybe Clash doesn't handle the ts2021 upgrade and the race is sometimes going one way vs the other way. Try setting env `TS_FORCE_NOISE_443=1`?

Roger. Will try it later. 

It's strange that it can only show in one of my device, others works well.

**Comment by lwabish** [comment]
Met this too on my macbook with clash x 1.118.1.1 and tailscale 1.70.0

**Comment by shenmo7192** [comment]
> Met this too on my macbook with clash x 1.118.1.1 and tailscale 1.70.0

This situation happen when I connect to my home wifi.But does not happen when I change to my phone wifi hotspot or use wired connection. Wierd.
