### ISSUE TITLE
Add SetOfFunc to set package

### ISSUE THREAD

**Issue by marwan-at-work** [tailscale/tailscale#12901]
I've run into a few instances to make a Set out of a "non comparable" list where the type has a comparable field within. 

For example: 

```golang
type User struct {
  ID string
  // other non comparible fields.
}
users := []*User{...}
SetOfFunc(users, func(e *User) { return e.ID }) // should return a set.Set[string]
```

**Comment by bradfitz** [comment]
I'd rather wait on Go 1.23 and iterators to do this differently: one thing to return an iterator from a slice+func (in slicex maybe) and then something in set to make a set from an iterator.
