### ISSUE TITLE
Tail scale -VPN

### ISSUE THREAD

**Issue by reddeppa-eddala** [tailscale/tailscale#12918]
### What is the issue?

I have PIKVM Device and it has been connected laptop -A and also  it has been installed tail scale -VPN and could login with public network without any issue. 

Laptop -A is connected with **PIKVM** and Tail scale has been installed in laptop B and could login with public net work and working fine. 

Now question to you, If i want to login with laptop -C, is it required  to install tail scale software and also need to follow same steps as below 

**https://tailscale.com/kb/1292/pikvm.**

If some other laptop does not allow tail scale. Any suggestion from your end . 

Regards, 
Reddeppa 

### Steps to reproduce

I have PIKVM Device and it has been connected laptop -A and also  it has been installed tail scale -VPN and could login with public network without any issue. 

Laptop -A is connected with **PIKVM** and Tail scale has been installed in laptop B and could login with public net work and working fine. 

Now question to you, If i want to login with laptop -C, is it required  to install tail scale software and also need to follow same steps as below 

**https://tailscale.com/kb/1292/pikvm.**

If some other laptop does not allow tail scale. Any suggestion from your end . 

Regards, 
Reddeppa 

### Are there any recent changes that introduced the issue?

I have PIKVM Device and it has been connected laptop -A and also  it has been installed tail scale -VPN and could login with public network without any issue. 

Laptop -A is connected with **PIKVM** and Tail scale has been installed in laptop B and could login with public net work and working fine. 

Now question to you, If i want to login with laptop -C, is it required  to install tail scale software and also need to follow same steps as below 

**https://tailscale.com/kb/1292/pikvm.**

If some other laptop does not allow tail scale. Any suggestion from your end . 

Regards, 
Reddeppa 

### OS

Linux

**Comment by bradfitz** [comment]
This seems like a continuation of your earlier https://github.com/tailscale/tailscale/issues/12878

Per that issue, you can use Tailscale Funnel to expose a Tailscale node to the public internet to not require Tailscale, but then it's on the public internet without the protections of a small, trusted, encrypted+auth'ed Tailscale network. So only use Funnel if you're absolutely sure that your PiKVM is safe to put on the internet.

**Comment by reddeppa-eddala** [comment]
Sorry for any confusion I may have caused. I realize I may not have communicated my requirements clearly.

I have a PiKVM device that is connected to Laptop A. Additionally, Tailscale has been installed on Laptop B, and I am able to log in to Laptop B over a public network without any issues."

"If I want to log in to Laptop C over a public network, do I need to install Tailscale on Laptop C and follow the same steps as I did for Laptop B?"

If yes, what if Laptop C does not allow Tail scale to be installed? How can I handle the situation?"

**Comment by reddeppa-eddala** [comment]
I realize I may not have communicated my requirements clearly.

I have a PiKVM device that is connected to Laptop A.  Additionally, Timescale has been installed on Laptop B, and I am able to log in to Laptop B over a public network without any issues and could access laptop A through laptop B

"If I want to log in to Laptop C over a public network to access laptop -A, do I need to install Tailscale on Laptop C and follow the same steps as I did for Laptop B?"

If yes, what if Laptop C does not allow Tail scale to be installed? How can I handle the situation?

**Comment by vempatisiva** [comment]
@reddeppa-eddala I completely understand your struggle i worked around the same project as you did. you can expose the pikm web interface over the internet anyone can access the pikvm just through the website.
Conflict is you need to install tailscale on pi kvm and then turn on serve and funnel within the pikvm.
__> The problem is everytime you run/reboot the pikvm you need to start pikvm manually as there is an issued need to fix port 443 is used by both tailscale and localhost (nginx) pikvm.
