### ISSUE TITLE
当指定--accept-routes参数后无法访问该主机

### ISSUE THREAD

**Issue by Dripman** [tailscale/tailscale#12916]
### What is the issue?

![image](https://github.com/user-attachments/assets/0a8e2172-58bb-4e07-bea1-ad74f30a9a70)
有三台linux服务器，其中10.10.11.170 作为虚拟路由宣告子网10.10.8.0/22，172.16.1.111 作为虚拟路由宣告子网172.16.0.0/16，并且headscale derp搭建在该机器上。在这两台主机上可以访问两个子网任何服务器。另一台主机10.10.11.156 也安装了tailscale ，当指定--accept-routes时 ，该主机可以访问两子网内任意额地址，但是从10.10.11.170 无法访问该主机。请问这是什么问题？

**Comment by bradfitz** [comment]
Sorry, but supporting self-hosted coordination servers, such as Headscale is not within our scope of support, per https://tailscale.com/kb/1250/support-options . We simply don't have many people who know Headscale. It's also a bit more challenging to do this across languages.

This might be a better question for https://www.reddit.com/r/Tailscale/

**Comment by Dripman** [comment]
thx
