### ISSUE TITLE
FR: Add HTTP/SOCKS proxy support for running Tailscale

### ISSUE THREAD

**Issue by lespromtehkms** [tailscale/tailscale#12933]
### What are you trying to do?

Please excuse any errors in my English, as I am using a translator.. 

Run Tailscale behind an HTTP or SOCKS proxy server.

Currently, there is no built-in support for HTTP/SOCKS proxies in Tailscale. This makes it impossible to use Tailscale in environments where all network traffic needs to be routed through a proxy server.

### What is the impact of not solving this?

Currently, I am using `tun2socks` locally to route Tailscale traffic through my corporate proxy (http). However, this is not an ideal solution as it adds complexity and may not be suitable for all users.

### Anything else?

Please consider adding this functionality to the Tailscale mobile application as well.

**Comment by agottardo** [comment]
From an old post:

> Tailscale respects the HTTPS_PROXY or ALL_PROXY environment variables if they specify an HTTP or SOCKS5 proxy.

Alternatively:

> specify HTTPS_PROXY and HTTP_PROXY in /etc/default/tailscaled

Does this help?

**Comment by lespromtehkms** [comment]
> From an old post:
> 
> > Tailscale respects the HTTPS_PROXY or ALL_PROXY environment variables if they specify an HTTP or SOCKS5 proxy.
> 
> Alternatively:
> 
> > specify HTTPS_PROXY and HTTP_PROXY in /etc/default/tailscaled
> 
> Does this help?

Thanks for the info, but I'm on Windows, so environment variables won't help. Currently I'm using tun2socks, but it's a workaround, not a solution. Native proxy support would be awesome, especially for mobile, because using a corporate proxy on mobile is a nightmare right now.

**Comment by lespromtehkms** [comment]
![image](https://github.com/user-attachments/assets/d6573a94-48a8-42e5-9588-ca15cecab300)

ALL_PROXY and HTTPS_PROXY and HTTP_PROXY environment - unfortunately does not work (at least in Windows)

**Comment by yqs112358** [comment]
any solution about socks/http proxy on windows? 😢

**Comment by yqs112358** [comment]
> ![image](https://private-user-images.githubusercontent.com/176746122/353675065-d6573a94-48a8-42e5-9588-ca15cecab300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDM2NjYsIm5iZiI6MTcyNDg0MzM2NiwicGF0aCI6Ii8xNzY3NDYxMjIvMzUzNjc1MDY1LWQ2NTczYTk0LTQ4YTgtNDJlNS05NTg4LWNhMTVjZWNhYjMwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMTA5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGUwN2EyZWFiMzI4M2JmYTFmYjM3ZDViZDc0YmViNjNhMzliNjBlNGYyODBlZTc3YTc1YzNjNDJjYmU3OGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNozKy4aVTOsFr_20DdIQcZy4Fc1uTUs6bi4RIHAXSc)
> 
> ALL_PROXY and HTTPS_PROXY and HTTP_PROXY environment - unfortunately does not work (at least in Windows)

Sorry but, does windows version have a built-in socks proxy? It seems that only linux version supports it currently🤔

**Comment by ethaniel** [comment]
Tailscale's `ALL_PROXY` works in Windows (found out the hard way via NetLimiter)

1. Use notepad to create a file in this hidden path: `C:\ProgramData\Tailscale\tailscaled-env.txt` with only 1 line: `ALL_PROXY=http://10.0.0.1:3128/`
2. Start `cmd` as administrator
3. run `net stop Tailscale`, then `net start Tailscale`

Done.
