### ISSUE TITLE
Windows 11 desktop application cannot "Log In" 

### ISSUE THREAD

**Issue by ghost** [tailscale/tailscale#12944]
### What is the issue?

I have a Tailscale account. I can log in to my dashboard MANUALLY inside of Firefox. The desktop app needs to Log In in order to connect to my Tailscale account. The desktop app does not provide a response when I click Log In. I checked the Log file and it's in a foreign language that froze Notepad. 

### Steps to reproduce

Install TS
TS opens in my taskbar
I right-click the TS icon
I click Log In
Nothing happens (and therefore no logging in happens and my computer does not connect to my Tailnet [because nothing happens after clicking Log In])

### Are there any recent changes that introduced the issue?

No. The desktop app has never allowed me to Log In

### OS

Windows

### OS version

11 22H2

### Tailscale version

1.70.0

### Other software

I am using Windscribe VPN and ControlD. Windows Defender is my only security software. 

### Bug report

BUG-f6328a8d090166f4653ad7a30423089dbb367d48b32506d6593a2cba414b7bc6-20240729063420Z-a3df13d16c13e88b

**Comment by agottardo** [comment]
Diagnostics indicate that the `WindscribeWireguard` interface is active. Can you please try uninstalling Windscribe and then rebooting to determine if that's causing the issue?

**Comment by jelielshinta** [comment]
Same thing happened to me. On desktop/laptop that has tailscale previously running on it, tailscale is working. But on the newly installed tailscale on a different machine tailscale log-in doesn't cause the browser to popup

**Comment by Tom-Teamo** [comment]
Same!!! . And my Ubuntu machine goes well, but in Windows11 it does not work.

**Comment by jelielshinta** [comment]
As for me its akready fixed. Mostly my problem is with our firewalls

**Comment by Tom-Teamo** [comment]
I have changed my VPN to `global mode`, however it didn't work at all. Can you tell me how you make it work? Tks :)

**Comment by jelielshinta** [comment]
I really dont have problem on windows 10 and above except firewalls really.
You dont need to edit anything after tailscale installation.

**Comment by Tom-Teamo** [comment]
Yeah, I also think it's about the firewall. My problem is the traffic inside the tailscale software does not seem to go through the proxy, for example, when I click `log in`. But I can access the tailscale official website in the browser. This is very strange. I have tried reinstall tailscale, just keep the same problem... This is maddening(AhAhAhAh

**Comment by jelielshinta** [comment]
Sorry i cant help you with that bro but im pretty  sure its your firewall

**Comment by dblohm7** [comment]
to Nick to see if this has been fixed yet

**Comment by nickkhyl** [comment]
Most issues where "nothing happens when I click Log In" are related to a firewall blocking the connection, and the best we can do is improve error reporting.

However, there's also a known bug where clicking Log In multiple times, or clicking it after the 'Tailscale Authentication Needed' notification was displayed and missed/ignored, results in no observable behavior. It can be worked around by restarting the GUI, and we're currently working on a fix.

I'm closing this issue as the OP deleted their GitHub account, and in the other two cases, it appears to be a firewall issue.

**Comment by Tom-Teamo** [comment]
fine, Thanks~

**Comment by nickkhyl** [comment]
@Tom-Teamo: based on the logs, it looked like you've resolved the issue on your own.

If that's not the case, I would suggest configuring Tailscale to use your proxy via `HTTPS_PROXY`/`ALL_PROXY` environment variables.

You should be able to do that via either the [`tailscale-env.txt`](https://tailscale.com/kb/1278/tailscaled#environment-variables) file, or by setting a system (machine-global) environment variable via [`setx /m`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setx) from an elevated command prompt or in the Environment Variables dialog.

**Comment by Tom-Teamo** [comment]
Yes, I have figured it out. It works well now. Thanks for your advice.

**Comment by tbcbcabral** [comment]
I couldn't login either (log-in button didn't open browser) because I am on a PC from my university (I think). What worked:

- Closing the application from the system tray;
- Opening a PowerShell with Admin privileges;
- tailscale up
- The login link shows up, copy to a browser, paste, login.
- Start application on windows.

Hope this helps.

**Comment by jelielshinta** [comment]
As for me firewall is blocking tailscale. But thanks for this. This is
still useful.

**Comment by 381sm016** [comment]
+1 on Windows 11

**Comment by tluyben** [comment]
For other people having this and the above did not fix it; make sure your date/time is correct. If it's off, the login button will do nothing. Might be a good idea to actually show some kind of error though.

**Comment by 381sm016** [comment]
For people using Tailscale to bypass firewall restrictions for SSH shells (specifically FORTINET) try using wireguard with a WSTunnel script that packages your UDP Wireguard packages into a WebSocket connection

Also, I have become aware that most networks using FORTINET block the login panel of Tailscale fully.
