### ISSUE TITLE
Change "LogIn" option in UI disabled after successful login.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1294]
A little confusing is "Log in" is active even if already logged in. 

![image](https://user-images.githubusercontent.com/75628398/107274606-9f5a7200-6a1e-11eb-968d-f0f1f0436444.png)

When we click Log in (when already logged in) but do not complete the authentication, the client cannot work well. To resolve, customers have to log out and logged back in after that connection is restored.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2rklt)

**Comment by rosszurowski** [comment]
Two issues here:
1. The UI confusion of the "Log in…" button still being active when already logged in. This should be addressed by the design scoped out in #1040.
2. The client gets stuck when starting a new authentication but not completing it. When this happens, the menu is stuck in a strange state where you're not logged into the old network, but still see some details about the old network (eg. your email). The "connecting" animation also plays without stopping.

**Comment by apenwarr** [comment]
This has been replaced with "Log in as a different user" which is more clear.
