### ISSUE TITLE
What are the best practices for accessing devices on different networks using Tailscale?

### ISSUE THREAD

**Issue by ukhack** [tailscale/tailscale#12971]
### What is the issue?

Here's a simplified overview of my network setup:

* **Desktop A:** Located at my company.
* **Desktops B（DSM7.2）, C, and D:** Located at my home. Desktop D runs Windows 7 and cannot install Tailscale.
* **Home network gateway:** 192.168.8.1

To access Desktop D, I've configured Tailscale on Desktop B with the following command:
```
sudo tailscale up --advertise-routes 192.168.8.0/23 --advertise-exit-node --reset
```

I also need to access Desktop A remotely from Desktop C, so I've installed the Tailscale client on Desktop C as well.

Here's the issue I'm facing:

* Desktop A can access all devices on my home network without any problems.
* **Desktop C frequently experiences slow internet speeds and cannot ping the gateway. The only solution is to disconnect from Tailscale, but then I lose access to Desktop A.**
* It seems like Desktop B is intercepting traffic intended for Desktop C.

What are the best practices for configuring Tailscale in this scenario to ensure smooth access between all devices?

### Steps to reproduce

install two client in a network and set one as exit node

### OS

Synology

### OS version

DSM7

### Tailscale version

1.70

**Comment by bradfitz** [comment]
> What are the best practices for configuring Tailscale

We don't use our issue tracker for general discussion topics like this. The Reddit subreddit at https://www.reddit.com/r/Tailscale/ is probably a better venue.

Or, for commercial support, see https://tailscale.com/kb/1250/support-options
