### ISSUE TITLE
cosmetic: user photo not showing (anymore) in macOS app

### ISSUE THREAD

**Issue by ldemailly** [tailscale/tailscale#12999]
### What is the issue?

I recently updated my photo in google sso and while that new photo shows up fine in web console, the macOS app shows me a default (I assume) green icon

<img width="78" alt="Screenshot 2024-08-02 at 1 47 36 AM" src="https://github.com/user-attachments/assets/b1653ce3-f7b4-42dc-a33b-52d03a13609b">

ps: works fine on iOS for instance

### Steps to reproduce

I tried logging out and back in but that didn't resync

### Are there any recent changes that introduced the issue?

change of picture in sso provider

### OS

macOS

### OS version

Sonoma 14.5

### Tailscale version

1.70.0 App Store

### Bug report

BUG-0b3e07e8182fb142f2d213f142cc2a74aaf6ec7b16ccd12fb0c2ca091b2000ef-20240802084955Z-389a4832fc037901

**Comment by agottardo** [comment]
Reproduced this by clearing the cache.

**Comment by agottardo** [comment]
Is this still happening? We haven't received any further reports. If you're still hitting this, please mention me and we'll re-open.

**Comment by ldemailly** [comment]
my picture did show up eventually, not sure how to "clear the cache" to confirm it's indeed fixed
