### ISSUE TITLE
Windows magicdns.localhost-tailscale-daemon lookup failure

### ISSUE THREAD

**Issue by alexraskin** [tailscale/tailscale#13004]
### What is the issue?

I am experiencing an issue with my reverse proxy setup. All non-Windows clients can connect without any problems, but I encounter an error when trying to connect from a Windows machine. The Windows client should be able to connect to the reverse proxy without any issues, similar to the Linux and Mac clients. 

I have tried changing my adapter DNS to `100.100.100.100` and `1.1.1.1`. 

My setup is loosely based on your [video](https://youtu.be/Vt4PDUXB_fg?si=dXeHv2sQMfnr7SGj)

### Steps to reproduce

1. Set up a Caddy reverse proxy 
2. Create DNS records in Cloudflare with Tailscale machine FQDN
I have a wildcard in Cloudflare - EX: `*.example.example.dev` 
4. Attempt to connect using a non-Windows client (Linux/Mac/iPhone/iPad) - connection is successful.
5. Attempt to connect using a Windows client - connection fails with the following error:

[![Image from Gyazo](https://i.gyazo.com/ae56b69a6d194853fd5378cbdad44356.png)](https://gyazo.com/ae56b69a6d194853fd5378cbdad44356)

Running `nslookup` on my Windows machine
```
C:\Users\me>nslookup <Cloudflare domain with Tailscale FQDN CNAME>
Server:  magicdns.localhost-tailscale-daemon
Address:  100.100.100.100

*** magicdns.localhost-tailscale-daemon can't find <Cloudflare domain with Tailscale FQDN CNAME>: Non-existent domain
```

Running `dig` on my Mac shows the correct info:
```
:: ~ » dig <Cloudflare domain with Tailscale FQDN CNAME>

; <<>> DiG 9.10.6 <<>> <Cloudflare domain with Tailscale FQDN CNAME>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37836
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;<Cloudflare domain with Tailscale FQDN CNAME>.        IN    A

;; AUTHORITY SECTION:
<FQDN>.        1800    IN    SOA    nick.ns.cloudflare.com. dns.cloudflare.com. 2347505710 10000 2400 604800 1800

;; Query time: 557 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Thu Aug 01 09:22:11 MST 2024
;; MSG SIZE  rcvd: 110
```

### OS

Windows

### OS version

Windows 10 Pro 22H2

### Tailscale version

1.70.0

### Bug report

BUG-26977e813e5e0ea1cbb67dcccdb5a85d9f9e8cd97ccdaa2f39be664457600e60-20240802190011Z-44cb45b6efd001fa

**Comment by WouterTinus** [comment]
I've had a similar experience with 1.70 on Windows, domain didn't resolve consistently (success rate about 10-20%) as long it was part of an app (as in the app connector feature). Also a domain with several CNAME's to get to the final IP. 

As soon as removed from the app connector (and therefore, I suppose, split DNS) the domain resolved with 100% reliability again.

**Comment by alexraskin** [comment]
> As soon as removed from the app connector (and therefore, I suppose, split DNS)

I am currently running NextDNS, but no spilt DNS or app connectors setup.

**Comment by alexraskin** [comment]
Another update: 


I share the reverse proxy machine out with a few people. 

One of those people is an Android user. He is also unable to connect.

He is using default DNS settings and even adding cloudflare override he cannot connect. 

![image](https://github.com/user-attachments/assets/11228d00-401a-4679-a778-fb1a5de4c540)

**Comment by googie-g15** [comment]
Similar issue for me, started out of the blue this afternoon when it was working correctly this morning. Discord broke and wouldn't connect at all and after combing through things I found that Tailscale DNS (`100.100.100.100`) can find `discord.com` but not `discord.gg`, which means that Discord can't connect until I turn Tailscale off and switch to another DNS server. What's weird is that this is the only host I've found so far that fails to resolve when using Tailscale. `discord.com` & `discordapp.com` both resolve correctly, as well as every other site I've tested.

I've tested various DNS servers using 'nslookup discord.gg x.x.x.x` as follows:

Tailscale: 'nslookup discord.gg 100.100.100.100` = `*** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available for discord.gg`
NextDNS: 'nslookup discord.gg 45.90.28.0` = `Non-authoritative answer Name: discord.gg Addresses: 162.159.134.234`
Pi-Hole: 'nslookup discord.gg 192.168.0.xxx` = `Non-authoritative answer Name: discord.gg Addresses: 162.159.134.234`
Cloudflare: 'nslookup discord.gg 1.1.1.1` = `Non-authoritative answer Name: discord.gg Addresses: 162.159.134.234`

The issue even persists through both `ipconfig /flushdns` & `Restart-NetAdapter Wi-Fi` & completely rebooting the machine. I can also confirm that Tailscale was able to correctly handle this lookup on my Ubuntu machine so I know this isn't a network config error on my end. My DNS routing is set up as follows:

Client (Windows 11) > Tailscale (100.100.100.100) > Pi-Hole (100.100.xxx.xxx) > Stubby > NextDNS
Windows 11, Ubuntu, & Pi-Hole all run Tailscale 1.70

I can also confirm that the `discord.gg` requests are not getting blocked in either my Pi-Hole or NextDNS as the logs on those apps both show the requests as successfully passed on (I even tried whitelisting those domains but it didn't change anything).

**Comment by jalapeno933** [comment]
Also running into this exact issue using a `.io` domain. I can't get it to resolve at all.

**Comment by jalapeno933** [comment]
@alexraskin were you able to fix your issue?

**Comment by alexraskin** [comment]
> @alexraskin were you able to fix your issue?

nah, I got a reply from email support: 

```
The behavior that you are seeing here is a result of how Windows handles DNS lookups compared to macOS and Linux. 
More details can be seen in the following issue on our GitHub: https://github.com/tailscale/tailscale/issues/7650. 
This limitation is also mentioned in the pinned comment of the YouTube video when we demonstrate this as an option.

We would like to support using custom domains for MagicDNS some day, and it is on our roadmap as a feature to add, 
but I don’t have a timeline for when that feature will be available at this time.
```
