### ISSUE TITLE
Firefox on Android doesn't resolve anymore MagicDNS entries 

### ISSUE THREAD

**Issue by rdbisme** [tailscale/tailscale#13025]
### What is the issue?

Not sure what changed, possibly a security update on my Motorola G52. But now only on Firefox I can't resolve MagicDNS domains.

Termux works. Chrome works.

Any idea where I might check what's happening?

This used to work at least up to three weeks ago. 

### Are there any recent changes that introduced the issue?

Potentially a security update on my android phone. Or tailscale app upgrade. 

### OS

Android

### OS version

13

### Tailscale version

1.70.0

### Bug report

BUG-713570c6641e00344c031a1d4a6112ac795e6670d130be2ccad94d81b041f69b-20240804134647Z-7f951e4a48e8964a

**Comment by bradfitz** [comment]
What version of Firefox? Maybe it's using its own DNS and not using the phone's DNS settings?

**Comment by rdbisme** [comment]
128.0.3 (Build #2016034663)

I don't seem able to access any particular DNS config on the app?

**Comment by rdbisme** [comment]
Ok, doesn't seem to reproduce anymore. :/
