### ISSUE TITLE
Using DERP when UDP performance is poor

### ISSUE THREAD

**Issue by jzelinskie** [tailscale/tailscale#1303]
**Describe the bug**

UDP over congested LTE networks are unusably slow.

**To Reproduce**

1. Escape the city to a cabin in the Poconos
2. Be forced into using an unlimited LTE modem for internet
3. Attempt to download a file over WebDAV
4. Quit Tailscale and scp the file for 10x the speed

**Expected behavior**

DERP currently only gets used when UDP isn't available, but you really want to use it when UDP performance is below a particular threshold.

**Screenshots**

N/A

**Version information:**
 - Device: MBP native macOS app <-> Synology NAS with Tailscale in a container
 - OS: macOS, Linux
 - OS version: Big Sur, Linux 4.4.59+
 - Tailscale version: macOS 1.2.4, Linux 1.4.2

**Additional context**

N/A

**Comment by bradfitz** [comment]
Your unlimited LTE modem gives you good TCP performance but crappy UDP?

**Comment by jzelinskie** [comment]
"Good" and "better" are two different things, but yes, haha. I suspect it has to do with packet loss.
I'm not there right now, but if you want me to run some tests this weekend, I can.

**Comment by DentonGentry** [comment]
I'm going to close this as a dup of https://github.com/tailscale/tailscale/issues/2270 because it has a paper linked explaining more of the motivation.
