### ISSUE TITLE
How to install tailscale on Android 6.0？

### ISSUE THREAD

**Issue by Goldenbeef** [tailscale/tailscale#13045]
### What is the issue?

I have an old Android device, its system is Android 6.0.1, I want to add it to my tailscale network, and use adb to remotely control the devices at home. But it cannot install apk. I read on the official website that the minimum version is 8.0. Is there an apk suitable for lower versions of Android?

### Steps to reproduce

I read on the official website

### Are there any recent changes that introduced the issue?

no

### OS

Android

### OS version

6.0.1

**Comment by agottardo** [comment]
Unfortunately not. There might be older APKs available online, but we do not support this and we strongly recommend that users only use the latest available version. Old versions may contain security vulnerabilities, may have bad performance and will lack many of the features and reliability improvements added in recent versions.

**Comment by Goldenbeef** [comment]
> If you like to tinker it is possible to use the latest static binaries of tailscale on android. I use them to repurpose my old android 6 phone as a tailscale gateway and share VPN connection using hotspot (with root). I run them (tailscale, tailscaled) under termux (any other terminal should also work) and expose socks5 proxy on interface 127.0.0.1. Then I use proxifier app to connect to this proxy. This way I can route all system traffic to different exit nodes and access tailscale network. More info in [termux/termux-packages#10166](https://github.com/termux/termux-packages/issues/10166)

Thank you for your reply. My current solution is to use an old version of the installation package. I will try it based on your suggestion.

**Comment by mohit0121** [comment]
@Goldenbeef  were you able to install it on android 6 ? if yes, would you be kind enough in sharing the apk with me as well?

@Pawloland if you were successful, would you mind sharing the apk with us please? that would really help me repurpose my old android

**Comment by Pawloland** [comment]
As I already mentioned I used static binaries, not tailscale app. Read the linked issue, it walks through setting it up.
