### ISSUE TITLE
Low speed using cutom DERP servers

### ISSUE THREAD

**Issue by sheey11** [tailscale/tailscale#13047]
### What is the issue?

the derp server has maximum ~200Mbps outbound speed, as iperf3 shows(`ssh -R` forwards local `5201` port to server)

![image](https://github.com/user-attachments/assets/b89c5cf4-faca-4af4-bf9b-9a38988ab2ea)

so the direct connection from derp server to `goose` machine(from where I `ssh` to derp server) is ~200Mbps. And here's iperf3 via tailscale

![image](https://github.com/user-attachments/assets/303eead5-6f02-423c-8b65-b36eb724f583)

The speed have downgraded to ~10Mbps. Also notice there's more retransmission happened.

### OS

Windows

### Tailscale version

1.70.0

### Bug report

BUG-fe003d092fd5538a5c852e645336face970500c8592c2e6305fc1b412b1c49ef-20240806124155Z-7471bba1230ae69e

**Comment by bradfitz** [comment]
Sorry, but we don't have the resources to help support optimizing people's customer server setups.

If you find a concrete problem of something we can improve, feel free to reopen or open a new issue with details.

**Comment by cesaryuan** [comment]
Hello, have you solved this issue? I'm experiencing the same problem, and it only occurs on Windows
