### ISSUE TITLE
Tailscale operator's dns reconciler is broken in a dual-stack cluster

### ISSUE THREAD

**Issue by farcaller** [tailscale/tailscale#13056]
### What is the issue?

The operator expects a [single EndpointSlice](https://sourcegraph.com/github.com/tailscale/tailscale@main/-/blob/cmd/k8s-operator/dnsrecords.go?L173), but in a dualstack cluster, there will be at least two of those: one with `addressType=IPv4` and another with `addressType=IPv6`. Because of that, the dns reconciler is always broken.

### Steps to reproduce

Add a DNSConfig and a tailscale ingress to a dualstack cluster. Observe no dns records and an error:

```json
{
  "level": "error",
  "ts": "2024-08-07T07:08:05Z",
  "msg": "Reconciler error",
  "controller": "dns-records-reconciler",
  "namespace": "tailscale-operator",
  "name": "ts-ts-vault-egress-5k5cd",
  "reconcileID": "16a77d83-45c7-47c5-946c-4d999f16becf",
  "error": "error getting the EndpointSlice for the proxy's headless Service: found multiple matching *v1.EndpointSlice objects",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"
}
```

### Are there any recent changes that introduced the issue?

N/A. Broken code logic.

### OS

Linux

**Comment by farcaller** [comment]
The [doc](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ownership) referenced in the comment next to that code points out:

> Clients of the EndpointSlice API must iterate through all the existing EndpointSlices associated to a Service and build a complete list of unique network endpoints. It is important to mention that endpoints may be duplicated in different EndpointSlices.
> You can find a reference implementation for how to perform this endpoint aggregation and deduplication as part of the EndpointSliceCache code within kube-proxy.

**Comment by irbekrm** [comment]
Thanks a lot for reporting this @farcaller #13057 should fix this.
Let us know if you see any further issues with dual-stack, at the moment we also don't support AAAA records.

**Comment by irbekrm** [comment]
@farcaller `v1.71.123` dev Helm chart has the fix (we should also have a stable release next week).

Let us know if you further issues

**Comment by farcaller** [comment]
@irbekrm can confirm the problem is solved, thanks.
