### ISSUE TITLE
Tailscale's handling of DNS-over-HTTPS queries with a Mullvad VPN Exit Node breaks Control D DNS Traffic Redirection feature.

### ISSUE THREAD

**Issue by dongha28** [tailscale/tailscale#13065]
### What is the issue?

When using Control D DNS as the 'Global Nameserver' with the 'Override Local DNS' function enabled in the Admin Console, and with a Mullvad VPN Exit Node selected in the Tailscale client application, the DNS-over-HTTPS queries to Control D DNS are sent over the network the device is connected to, NOT through the Mullvad VPN Exit Node.

This completely breaks the [Traffic Redirection](https://docs.controld.com/docs/feature-traffic-redirection) feature of Control D DNS, available on their [Full Control](https://controld.com/plans?step=plans) paid plan, wherein the user can selectively redirect their network traffic through Control D's network of transparent proxies.

The Traffic Redirection feature functions by comparing the source IP of the DNS-over-HTTPS query to the IP of the device that is attempting to access the Control D transparent proxy. If there is a [mismatch between these two IPs](https://docs.controld.com/docs/ip-mismatch-between-dns-and-proxy) this breaks the Traffic Redirection feature.

I've searched through other bug reports and found that a NextDNS customer has also filed a [bug report](https://github.com/tailscale/tailscale/issues/11900) with the same fundamental issue, however, in that case a DNS query leak happens and no functionality of NextDNS is broken.

Considering the fact that the Tailscale integration with Control D DNS is now official, as indicated in both the [documentation](https://tailscale.com/kb/1403/control-d) and the [blog post](https://tailscale.com/blog/controld), it is a bit frustrating to see a major selling point of Control D DNS's paid plan not functioning properly with Tailscale's existing integrations...

### Steps to reproduce

1. Have an active subscription to both the Control D DNS 'Full Control' plan AND the Tailscale Mullvad VPN addon.
2. Follow the steps from 1 ~ 5 in the Tailscale [documentation](https://tailscale.com/kb/1403/control-d) to configure Control D DNS as the 'Global Nameserver' with the 'Override Local DNS' function enabled.
3. Make sure the 'Use Tailscale DNS Settings' option in the Tailscale client, which should be enabled by default.
4. Connect to any Mullvad VPN Exit Node and open up the Control D DNS [Status Page](https://controld.com/status).
5. The 'DNS' section of the Status Page shows that my device is 'Using Control D', however the 'Proxy' section of the Status Page shows 'Not Authorized', which means that my device is not authorized to access Control D's network of transparent proxies.

### Are there any recent changes that introduced the issue?

None.

### OS

Windows

### OS version

IoT Enterprise LTSC 24H2

### Tailscale version

1.70.0

### Other software

None.

### Bug report

BUG-69c3869994a6a35c0648f67ce72213906754e1df21a5f0acbdb62014aca27410-20240808142717Z-371f64e6640ad6c4

**Comment by nickkhyl** [comment]
@dongha28: can you please edit (or create) the [nodeAttrs](https://tailscale.com/kb/1337/acl-syntax#node-attributes-nodeattrs) section in the policy file to apply the `user-dial-routes` attribute, and see if that resolves the issue?
```
"nodeAttrs": [
    {
        "target": ["*"],
        "attr":   ["user-dial-routes"],
    },
],
```

**Comment by dongha28** [comment]
@nickkhyl That solved my issue! All of my DNS queries are now going through the Mullvad VPN Exit Node, and Traffic Redirection works in Control D! Is it okay to keep using ```user-dial-routes``` for devices in my Tailnet? I can't find any mention of ```user-dial-routes``` inside the Tailscale documentation...

**Comment by nickkhyl** [comment]
@dongha28: thank you for confirming! The main side effect of the attribute is a slight increase in memory consumption. This usually isn't a problem, as we're only talking about a few hundred KiB, even in moderately large and complex tailnets. However, certain environments have very strict memory limits (e.g., [iOS](https://developer.apple.com/forums/thread/73148?answerId=732711022#732711022)), and it all adds up. So we'd like to reduce memory usage before enabling the attribute by default for all nodes. In the meantime, you can keep it enabled unless you have a huge tailnet and are concerned about the additional memory footprint.

**Comment by iurab** [comment]
I tried the step mentioned in here, but for me the problem is still present.

**Comment by dongha28** [comment]
@iurab I am using the following Tailscale ACL configuration, under the 'Access Controls' section of the Tailscale Admin Console. I also logged out and logged back in on all my devices to force Tailscale to pull in the new ACL configuration. Make sure to set the IP addresses for your devices before deploying it!

```
{
	"acls": [
		{"action": "accept", "src": ["*"], "dst": ["*:*"]},
	],
	"ssh": [
		{
			"action": "check",
			"src":    ["autogroup:member"],
			"dst":    ["autogroup:self"],
			"users":  ["autogroup:nonroot", "root"],
		},
	],
	"nodeAttrs": [
		{"target": ["*"], "attr": ["user-dial-routes"]},
		{"target": ["<IP Address of Device #1>"], "attr": ["mullvad"]},
		{"target": ["<IP Address of Device #2>"], "attr": ["mullvad"]},
		{"target": ["<IP Address of Device #3>"], "attr": ["mullvad"]},
		{"target": ["<IP Address of Device #4>"], "attr": ["mullvad"]},
		{"target": ["<IP Address of Device #5>"], "attr": ["mullvad"]},
	],
}
```

**Comment by iurab** [comment]
I forgot to mentioned that I tried this on my Android device. On Windows it is working.

**Comment by dongha28** [comment]
@iurab Hmm, I don't use Tailscale on Android so I can't help debug further. I suggest you open an issue for the problem you're having. The ```user-dial-routes``` feature flag is undocumented so it may not work across all platforms as of now...
