### ISSUE TITLE
IPv6 nameserver on MacOS

### ISSUE THREAD

**Issue by tiri** [tailscale/tailscale#1306]
IPv6 Nameservers doesn't get populated to the MacOS Client.

**To Reproduce**
1. Login to Admin Console
2. Add IPv6 nameserver

**Expected behavior**
IPv6 nameserver defined in the Admin Console should be added to the DNS configuration on macOS. IPv4 nameservers and Linux Client works as expected.

**Version information:**
 - Device: MacBook
 - OS: macOS
 - OS version: 11.2
 - Tailscale version: 1.2.4

**Comment by DentonGentry** [comment]
This should be fixed in the 1.8 release, due soon.
