### ISSUE TITLE
Helm Kubernetes Operator - apiServerProxyConfig override not working in Terraform with Set

### ISSUE THREAD

**Issue by s-sy-y** [tailscale/tailscale#13074]
### What is the issue?

When doing Helm chart install through Terraform with resource "helm_release" and using "set" functionality to do value override for `apiServerProxyConfig.mode`, the install fails with a template comparison error. Override works as expected for another parameter called `operatorConfig.hostname`. Override also works, when specifying the parameter values across multiple lines as seen below on examples.

### Steps to reproduce

The following code snippet will throw an error.

Terraform 1.5.7

```
resource "helm_release" "tailscale" {
  provider   = helm.main_eks
  name       = "tailscale"
  repository = "https://pkgs.tailscale.com/helmcharts"
  chart      = "tailscale-operator"
  version    = "1.70.0"
  namespace  = "tailscale"

  atomic          = true
  cleanup_on_fail = true

  #values = []

  set {
    name  = "operatorConfig.hostname"
    value = "tailscale-${var.account_identifier}-${var.environment_identifier}-eks-operator"
  }

  set {
    name  = "apiServerProxyConfig.mode"
    value = "true"
  }
}
```

`Error: template: tailscale-operator/templates/apiserverproxy-rbac.yaml:4:6: executing "tailscale-operator/templates/apiserverproxy-rbac.yaml" at <eq .Values.apiServerProxyConfig.mode "true">: error calling eq: incompatible types for comparison`

For a workaround, the following code works

```
resource "helm_release" "tailscale" {
  provider   = helm.main_eks
  name       = "tailscale"
  repository = "https://pkgs.tailscale.com/helmcharts"
  chart      = "tailscale-operator"
  version    = "1.70.0"
  namespace  = "tailscale"

  atomic          = true
  cleanup_on_fail = true

  values = [
    <<EOF
    apiServerProxyConfig:
      mode: "true"
    EOF
  ]

  set {
    name  = "operatorConfig.hostname"
    value = "tailscale-${var.account_identifier}-${var.environment_identifier}-eks-operator"
  }
}
```

### Are there any recent changes that introduced the issue?

No, first time customer installing a fresh version of the latest chart.

**Comment by bkonicek** [comment]
Have you tried removing the quotes around `"true"` to pass it as a boolean value?

**Comment by s-sy-y** [comment]
Yes, I tried when first troubleshooting it, made no difference. This can also be validated through the [Helm Playground](https://helm-playground.com/#t=MQAgwg9gDgngTgSwOYAsAuIAUBjAlCAFQEMEAbAZ2yNIFMQBJAO2xADIQBBAVQIAkB5AEoBlAFChhABQAiADQC0AGQTYajcjXn0AJmrQIAZghpwAXCABCw6fIDM8sKSIBXDaNEBvDyEMgaARxAAOgA1amcaciCiKARhEwA3E0k4CAAPGEhGIyQggFsIXRAAIjQ4COKQAF8q0RiEEJNyBAhGczgAIyJsaOc0FAhEAC8ifVaggGsADiiWgHoEgEZRCYRGbXNHVzQTQQhaUTyaNCJtUaJTURAQRiIj8xOySmpNF375KFSM0XLackv5CB6gBxVLOKD-EAAbWKxQAulcQHBIhBnHBVJCYa4msUADQlJBgiHwxFJTqY4oIPJQJqtUY0EnyJl1WKNODNVrtLo9N4DYajFqMSYzILzJYrNYbcCkba7fY0CyStZIQ7HU7nS7XW73ECPChUWjyXkfL4wUTkZwdABWNGwaH%2BokBq3W5nicASKhoHGw2FRjDQiO1NHM0BMo0GgbukSg3WDIC8wUENFoRA0QQAclHyDHVNVaqlaEmDJqQM6pVtyDs4HsDlqow8SPqXka%2BigTekzdcQUSud1ev1BggRmMhdNZhBPN41No80A&v=IYBwlgygpgTgbrACjA9gDwJ4GEUDsBmYA5gFwBQABFRQLYoAmUJFARAC4wCuULQA)

**Comment by irbekrm** [comment]
`apiServerProxyConfig.mode` has to have a value of type string (this is for historical reasons, we originally had a bool true/false there, but then a third mode was added).

I suspect that the failure is because the value you are passing gets translated to boolean at some point.
I am not very familiar with the Terraform Helm provider- when using the Helm CLI, this field must be set via `--set-string` rather than `--set`. From a very brief look, I don't a `set_string` stanza in the Helm provider docs, but perhaps you could try to explicitly specify the type:

```
set {
    name  = "apiServerProxyConfig.mode"
    value = "true"
    type = string
  }
```

interested to hear if this works

**Comment by s-sy-y** [comment]
Good catch, the following worked. Thanks

```
  set {
    name  = "apiServerProxyConfig.mode"
    value = "true"
    type  = "string"
  }
```
