### ISSUE TITLE
FR: Easy to set own domain name with https

### ISSUE THREAD

**Issue by RaymondDay61** [tailscale/tailscale#13091]
### What are you trying to do?

Been trying for about 3 weeks now. Installed Caddy and xcaddy Got CloudFlare for my domain name and the keys named "Site Key", "Secret Key", "tunnel token", "Zone ID", "Account ID", "Global API Key", and "Origin CA key" put them all one at a time in the /etc/caddy/Caddyfile and ran "caddy run --config /etc/caddy/Caddyfile" but all ways get errors. Lots more I could tell because been working on this for 3 weeks now.

### How should we solve this?

Making it as easy as you do https with the giving domain name tailscale gives you. But have it so can use your own domain with https.

### What is the impact of not solving this?

I got WordPress and can't display it because it wants https. With CloudFlare got my "A" Type Name rday.me Content 100.124.69.73 and Proxy Status DNS only - reserved IP with my WordPress has videos on photos in it that will not show up on my Cellphone because they had https links and or the tailscale line they auto gave me.

### Anything else?

It's to hard to get https with your own Domain name I hope you can make this easy with some update.

**Comment by bradfitz** [comment]
Dup of #4515 and #11655

**Comment by RaymondDay61** [comment]
Got https working with tailscale super easy with 3 commands on Ubuntu server. Like this:

apt install certbot
certbot --manual --preferred-challenges dns certonly -d [rday.me](http://rday.me/)
certbot --apache

You have to copy a big number it gives you to a txt file were you have your domain name. I have it on CloudFlare and then have to type some answers on the 2nd command it will ask for something were you put in like /var/www/html I for get how it asked.

I hope they include this on a tailscale install to ask if you want to use your own domain name and with https.
