### ISSUE TITLE
when use custom derp with --verify-clients other tailnet still can connect ?

### ISSUE THREAD

**Issue by peng5545** [tailscale/tailscale#13097]
### What is the issue?

run custom 
./derper --hostname=xxx --verify-clients

the same tailnet connect with no errors. other tailnet connect with the log info 
"client nodekey:021ff47873fca4ed021550f56b2e5b2f5c194797c93c1e0e448c4834fc3e1f2c rejected: peer nodekey:021ff47873fca4ed021550f56b2e5b2f5c194797c93c1e0e448c4834fc3e1f2c not authorized (not found in local tailscaled)",

but still can connect? it is a bug or i do something wrong?

### Tailscale version

tailscale version
1.70.0
tailscale commit: 0e0a212418fbf8243cb3f06634367b61e81ea9db
other commit: 26f80df929d9ae698931e4dd1fbdf05f2138ff6f
go version: go1.22.5

tailscaled -version
1.70.0
tailscale commit: 0e0a212418fbf8243cb3f06634367b61e81ea9db
other commit: 26f80df929d9ae698931e4dd1fbdf05f2138ff6f
go version: go1.22.5

derper -version
1.70.0-ERR-BuildInfo

_No response_

**Comment by bradfitz** [comment]
> but still can connect? it is a bug or i do something wrong?

No, it can't still connect.

What makes you think it can?

**Comment by peng5545** [comment]
I login Tailscale use other account(2 devices),modify ACLs,i can see RELAYS show at page [machines](https://login.tailscale.com/admin/machines), and run some commond like "tailscale netcheck / ping" works fine.
ALCs with "OmitDefaultRegions": true so i am not use official derp server.

**Comment by peng5545** [comment]
Thanks for your explanation

**Comment by ciandonovan** [comment]
I might have ran into this issue.

Custom DERP servers with `--verify-clients` and `OmitDefaultRegions": true`

Everything worked fine until I restricted inter-device access with ACLs, and got lots of `not authorized (not found in local tailscaled)` messages on the DERP server.

It seems to be fixed by allowing all sources access to the DERP server on port 80,443

```
{
	"action": "accept",
	"src":    ["*"],
	"dst":    ["tag:tailscale-infra:80,443"],
},
```

Is this expected behaviour? Cannot find any documentation for this.

**Comment by bradfitz** [comment]
For `--verify-clients` mode, derper needs ACL access to the coresident `tailscaled` on the box.

**Comment by ciandonovan** [comment]
Is there documention for this? What ports are required?

derper isn't a listed machine, just the `tailscaled` instance on the box, between what nodes am I allowing access?

**Comment by bradfitz** [comment]
It doesn't need any ports open necessarily, but the tailscaled on the derper box needs to know the identity of any public key connecting to that derp.

That is, you should be able to run `tailscale status` on the machine and see all the peers that might use that machine's derper process. Normally Tailscale's control plan will trim the netmaps (see "netmap trimming" at https://tailscale.com/kb/1087/device-visibility) and thus that tailscaled won't be able to answer questions about peers connecting to derper that have been trimmed away from the tailscaled's netmap.

To work around, you can add some dummy access like permitting IP [protocol 146 or something useless](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml) and not even permit any TCP or UDP or ICMP access. Or only permit ICMP and no TCP/UDP (useful for ping testing, perhaps).
