### ISSUE TITLE
iOS still notifies of expiry after reauthentication

### ISSUE THREAD

**Issue by sellout** [tailscale/tailscale#13104]
### What is the issue?

My phone still received a notification saying my key expired after I reauthenticated when I received the “expiring soon” notification.

### Steps to reproduce

I got a notification on my iPhone 12 mini “Tailscale authentication expires soon” and immediately re-authenticated. This morning I got another notification “Tailscale authentication expired”, opened the app to see what happened, but everything was fine and it showed Key expiry was in the future.

### OS

iOS

### OS version

iOS 17.5.1

### Tailscale version

1.70.0

### Bug report

BUG-8e2646c8a75a0cc31aedf9f8e5ec889fea9ddf378aab5c75d2ea01a8019e965d-20240812133247Z-e7e178785ad3014b

**Comment by agottardo** [comment]
We just landed a fix for this issue that will be released in an upcoming app update. Thank you for reporting.
