### ISSUE TITLE
FR: MTU probing

### ISSUE THREAD

**Issue by dolceAlka** [tailscale/tailscale#13102]
### What are you trying to do?

MTU probing per peer to increase throughput, alternatively pick lowest of the two MTU based on peer's MTU.

### How should we solve this?

Either negotiate MTU over the control server or implement MTU probing on tailscaled.

### What is the impact of not solving this?

It seems that wireguard-go with tailscale is constrained by MTU, testing on host to docker container with iperf3 on a 6900HS only yields 3.2gbps per side on 1280, but 10.3 on 9000. This would just be another feature above just wireguard.

### Anything else?

I understand that there has been an effort to move away from the current 1280 MTU to have a stable way to change MTU without TS_DEBUG_MTU. This is probably low priority since most aren't able to get multi gig or jumbo frames.

**Comment by bradfitz** [comment]
Dup of #311, etc.

This is something we still intend to work on.
