### ISSUE TITLE
wgengine/router: add Windows firewall rule to let LAN access tailscaled on UDP/41641

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1312]
Two tailscaled nodes on a LAN cannot currently connect directly as we are missing a windows firewall rule.

**Comment by bradfitz** [comment]
@sailorfrag, we need to figure out how to do this with the `netsh` CLI (see wgengine/router/router_windows.go).

I can do it with the GUI, but the CLI doesn't give me hints about how to create it with the CLI:

<img width="1105" alt="Screen Shot 2021-02-10 at 10 34 13 AM" src="https://user-images.githubusercontent.com/2621/107555198-ba96c000-6b8b-11eb-9e97-85b9a231ba7f.png">

/cc @peske

**Comment by sailorfrag** [comment]
there seem to be some docs here https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/netsh-advfirewall-firewall-control-firewall-behavior

**Comment by sailorfrag** [comment]
btw `netsh advfirewall firewall show rule name=Tailscale-Process-In verbose` should show the stuff it's hiding like process name

`netsh advfirewall firewall add rule ?` gives the list of options available
