### ISSUE TITLE
FR: Enable DoH for other Global Nameservers

### ISSUE THREAD

**Issue by udf2457** [tailscale/tailscale#13121]
### What are you trying to do?

For some incomprehensible reason Tailscale seem to only list NextDNS and Control D as DoH options.

Other public services (e.g Quad9 DNS) have DoH options and those should be provided, not plaintext unencrypted !

In addtion, when adding a custom DNS server, the option should be provided to require DoH or DoT.

**Comment by agottardo** [comment]
> public services (e.g Quad9 DNS) have DoH options and those should be provided, not plaintext unencrypted

This is already supported. Tailscale performs automatic DoH upgrade when you use any of the well-known DNS resolvers listed [here](https://github.com/tailscale/tailscale/blob/84adfa1ba311a4ed2b274458e379bc95e08e699b/net/dns/publicdns/publicdns.go#L165). For instance, 9.9.9.9 is already upgraded to `https://dns.quad9.net/dns-query` automatically.

Adding the ability to specify custom DoH/DoT servers is tracked in https://github.com/tailscale/tailscale/issues/74.
