### ISSUE TITLE
pfSense CE: Admin Console Reported Installed Version Mismatch

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#13134]
### What is the issue?

Version displayed via Admin console does not match actual installed version

### Steps to reproduce

1. Install TS package via pfSense CE 2.7.2  packages
2. Manually update to 1.70.0_1 

`pkg add -f https://pkg.freebsd.org/FreeBSD:14:amd64/latest/All/tailscale-1.70.0_1.pkg
`

<img width="1162" alt="Screenshot 2024-08-14 at 5 55 05 AM" src="https://github.com/user-attachments/assets/798f174e-3573-454f-b213-9d74ca5d7c50">

> tailscale version
1.70.0
go version: go1.22.6

 
> pkg info | grep -i tail 
pfSense-pkg-Tailscale-0.1.4    pfSense package Tailscale 
tailscale-1.70.0_1             Mesh VPN that makes it easy to connect your devices

<img width="1014" alt="Screenshot 2024-08-14 at 6 02 43 AM" src="https://github.com/user-attachments/assets/cf8620ac-bc8c-4e0f-930c-2e97e9d884d7">

### Are there any recent changes that introduced the issue?

TS FreeBSD package was incremented to "_1" 

### OS

Other

### OS version

pfSense CE 2.7.2

### Tailscale version

1.70.0_1

### Bug report

BUG-7aa04bfe873caa6fde5e1d023864e56d987989ccda68b7752bad3cfb4e4ed684-20240814095618Z-aa058d62c006c51c

**Comment by bradfitz** [comment]
The `_1` part is some pfSense-specific packaging suffix presumably. Tailscale doesn't have such a component in its version, so Tailscale isn't reporting that to the control plane.

From your bugreport:

> 2024-08-14 09:56:18.795652865 +0000 UTC: user bugreport hostinfo: {"IPNVersion":"1.70.0","OS":"freebsd","OSVersion":"14.0-CURRENT","Distro":"pfsense","DistroVersion":"2.7.2-RELEASE","Hostname":"pfSense","Machine":"amd64","GoArch":"amd64","GoArchVar":"v1","GoVersion":"go1.22.6"}

So that's all we can show.

I'm not sure there's anything more we can do here. We don't own the pfSense packages.

**Comment by bradfitz** [comment]
We also don't maintain the FreeBSD ports.
