### ISSUE TITLE
"Failed to connect to Tailscale Service" on Windows 10 during early system start

### ISSUE THREAD

**Issue by war59312** [tailscale/tailscale#1313]
---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.

Version 1.4.3 (td2c1ae7ed-g0fa8d8bb3)

LogID: 5eefe6c33dd52233694efcfc66e5b2b2eeb1196a397ea9710da158eb6ec26abe

(Ctrl-C to copy this text)

---------------------------
OK   
---------------------------

Was an upgrade from working 1.4.0 to 1.4.3. Even going back to 1.4.0 and still broken now.

Win 10 20H2 fully up to date

**Comment by war59312** [comment]
Well, looks like it fixed itself after a reboot. Looks good now, on 1.4.3.

**Comment by war59312** [comment]
---------------------------
Tailscale Error
---------------------------
Tailscale service not installed on this machine.

Version 1.4.0 (t3d7cff91b-g62ff3b5c4)

LogID: 433f73371798e61818b177641b1a242c73eff5394950c403acbc7c3a672dbd55

(Ctrl-C to copy this text)

---------------------------
OK   
---------------------------

Happened on a 2nd Win10 computer, this time Win 10 1909

**Comment by bradfitz** [comment]
It's a misleading error message. It's actually fine, but on Windows 10 machines with auto-login (& especially with Unattended Mode), the Tailscale GUI tries to connect to soon while the Windows networking stack is still starting up.

We have a plan for fixing this, though.
