### ISSUE TITLE
iPadOS: TS 1.71.46+ Does Not Connect on iPadOS 16.7.10

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#13144]
### What is the issue?

Cannot connect

### Steps to reproduce

1. Install TS 1.71.46 or greater on iPadOS 16.7.10
2. Try to connect

![IMG_0087](https://github.com/user-attachments/assets/c0058306-5d35-496d-86a9-4a5749e32558)
![IMG_0088](https://github.com/user-attachments/assets/2096fc22-db00-4107-a0b0-dde89e1b0f1d)
![IMG_0089](https://github.com/user-attachments/assets/4a6f8c9d-d999-4137-81e6-5a8d1fdce690)

3. Install TS 1.70.0
4. Connects sucessfully

 

### Are there any recent changes that introduced the issue?

Something changed after 1.70.0 to break compatibility.

### OS

iOS

### OS version

iPadOS 16.7.10

### Tailscale version

1.71.46+

### Other software

1.70.0 works, but anything 1.71.46 or greater does not work.

### Bug report

Cannot generate BUG link because TS client cannot connect.  BUG button greyed out. 

BUG link for successful connection using 1.70.0
BUG-cae59688a55344b6134ba9ce1fb350af85e3148c8377bddf8e2538e4dcde5cbb-20240814173640Z-dc443c22f1f8e46c

**Comment by agottardo** [comment]
We are aware of the issue, it's been fixed in internal builds, but those haven't yet been approved by Apple for distribution to external TestFlight testers.

**Comment by elvisimprsntr** [comment]
Confirmed fixed in 1.71.121

BUG-cae59688a55344b6134ba9ce1fb350af85e3148c8377bddf8e2538e4dcde5cbb-20240815095808Z-6f260de47b801fdf
