### ISSUE TITLE
Log is spammed with "portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router"

### ISSUE THREAD

**Issue by ce-dot** [tailscale/tailscale#13145]
### What is the issue?

My system log contains many (hundreds+) messages saying `portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router`.

UPnP and PCP are intentionally disabled in my router (in my FRITZ!Box 7490 you can't configure these features individually). I'd prefer to be able to disable the mechanism causing this or at least hide the message, as it's not useful information in my case.

### Steps to reproduce

1. run `tailscale up --ssh` (don't think the `--ssh` matters)
2. have UPnP/PCP disabled in the router
3. watch journalctl

### OS

Linux

### OS version

NixOS 24.05

### Tailscale version

1.66.4

**Comment by bradfitz** [comment]
You can set TS_DISABLE_PORTMAPPER=1 in the environment for now. It's not guaranteed to stick around forever, but it exists.

Tailscale gets many more direct connections (avoiding DERP) when portmapping is in use, though.

**Comment by bradfitz** [comment]
> I could manually port-forward in case there's problems.

If you do, you need to make sure to use the `--port` flag to tailscaled and make it match the port you manually forward.

**Comment by rstoll21** [comment]
I have the same issue on my proxmox ve behind a fritz box. If I allow port forwarding for this device in my router, I don't get this messages. Is it possible to open just defined ports for tailscale? I can't make nothing out of the support site [What firewall ports should I open to use Tailscale?](https://tailscale.com/kb/1082/firewall-ports)

**Comment by boennhoff** [comment]
I have my logs spammed with this message as well, same reason like the author. I would rather see this once, or a few times but silenced afterwards (or coming less and less over time)... journalctl does not provide any means to block this message... very annoying

**Comment by n0valis** [comment]
I just wondered why my syslog/daemon.log grew about 3GB in size within 24 hours. Guess what, most of it was tailscaled spaming all sorts of messages. I think it is fine to have some warnings in syslogs. but this? This is far beyond what is good and neccessary.

**Comment by baumheld** [comment]
This issue is not resolved.
In a standard setup with tailscale on a proxmox node, I get spammed with the same message as OP.
> portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router

If I enable UPNP in my router and disable the proxmox node firewall (just for testing) the message spam changes to 
> tailscaled[790]: portmapper: failed to get PCP mapping: PCP response not ok, code 8

If I add `TS_DISABLE_PORTMAPPER=1` to `/etc/environment` nothing changes

What can I do? Please help

[log.txt](https://github.com/user-attachments/files/18310687/log.txt)

**Comment by Chr1s70ph** [comment]
Its absolutely not resolved, my raspberry-pi logs are spammed with this message. My poor SD-Card can only handle so much logs...

**Comment by ilf** [comment]
I am also experiencing this and have two questions:

1. Why does tailscale print this message every ~10 seconds? Wouldn't once at startup be enough?

2. Can tailscale get a real option/swetting to disable portmapper, instead of the (unstable) environment variable workaround?

Thanks.

**Comment by SamThilmany** [comment]
With `TS_DISABLE_PORTMAPPER=1` (as suggested by @bradfitz), the message changes from 

> portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router

to

> netcheck: probePortMapServices: port mapping is disabled

This is not even a workaround for preventing massive log files. Please reopen this issue, as it is *NOT* solved!

**Comment by ilf** [comment]
I can confirm this. The spammy log message does not go away, only change. Please provide an option to stop this. Thanks

**Comment by kafmees** [comment]
Same issue. I can't even tail my logs because of the continuous spam tailscaled gives me.

**Comment by AaronBeier** [comment]
Still happening, arch linux
```
1.80.2
  tailscale commit: 62b8bf6a082c4bea1b9e6ee1962c81c6ee5263d3-dirty
  go version: go1.24.0
```

**Comment by Arnigon** [comment]
Still persists, running Home Assistant OS 15.2 on Proxmox 8.4 with the Tailscale addon 0.25 and Tailscale version 1.80.
Log gets spammed about 10 - 15 messages every minute.

**Comment by m3e-g** [comment]
This is still present in the tailscale 1.96.4 running on Ubuntu 24.04.4 LTS (6.17.0-19-generic). 

These two messages are logged every ~5 minutes
```
Apr 01 14:06:16 <...> tailscaled[726]: portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router
Apr 01 14:08:32 <...> tailscaled[726]: portmapper: PMP probe failed due result code: {OpCode:128 ResultCode:NetworkFailure SecondsSinceEpoch:2393781 MappingValidSeconds:0 InternalPort:0 ExternalPort:0 PublicAddr:invalid IP}
```
