### ISSUE TITLE
CLI integration "Show me how" button non-functional on macOS 12

### ISSUE THREAD

**Issue by keeleysam** [tailscale/tailscale#13158]
### What is the issue?

The Tailscale GUI contains a button labeled "Show me how" for setting up the CLI integration on macOS. 

On macOS 14/15, this button shows the sheet on how to set it up.  On macOS 12.7.6, nothing happens.  I didn't test on macOS 13 as I don't have any devices running that version.

The "Manage..." button for Tailnet lock which is right above this button does work, however.

### Steps to reproduce

Install Tailscale 1.70.0 on macOS 12.7.6 (latest versions), open Tailscale Settings, click "Show me how", nothing happens.

### OS

macOS

### OS version

macOS 12.7.6

### Tailscale version

1.70.0

### Other software

n/a

**Comment by agottardo** [comment]
Fix will land in a future update, thanks for the report.
