### ISSUE TITLE
Apple TV/tvOS - Using custom control server not possible

### ISSUE THREAD

**Issue by cat24max** [tailscale/tailscale#13170]
### What is the issue?

This is basically an exact clone of #9088.

The problem still exists, even on older and the latest TestFlight builds.

### Steps to reproduce

Download tvOS app, open. QR code is displayed and cannot be closed.

### OS

Other

### OS version

tvOS 17.6

### Tailscale version

1.71.74

**Comment by agottardo** [comment]
> Download tvOS app, open. QR code is displayed and cannot be closed.

@cat24max Did you configure the custom coordination server in the Settings app?

**Comment by cat24max** [comment]
> @cat24max Did you configure the custom coordination server in the Settings app?

Meh. Didn't even know this needs to be done as it works differently on iOS. Actually, I didn't even know tvOS had app settings in Settings.app

It's now working, even on the app store release version.
