### ISSUE TITLE
Losing internet when Tailscale is connected on iOS

### ISSUE THREAD

**Issue by eliabir** [tailscale/tailscale#13177]
### What is the issue?

When I connect to my Tailnet from my iPhone 13 Pro Max I can reach other devices on my Tailnet but I completely lose normal internet access. If I have Tailscale DNS enabled then webpages just hang loading forever. If I disable Tailscale DNS then my browser says I have no internet. Other VPN services work fine.

### Steps to reproduce

Connect to Tailnet on iPhone 13 Pro Max.

### Are there any recent changes that introduced the issue?

No, it has been like this since i first installed Tailscale.

### OS

iOS

### OS version

iOS 17.5.1

### Tailscale version

1.70.0

### Bug report

BUG-7aafcbebadd0ef8855eab3c479a3f1330e38672250d4cd78bc3961fb1626f7f6-20240819090423Z-544a7eea6075d21b

**Comment by agottardo** [comment]
A number of DNS-related fixes went into recent app updates that should have resolved the issue you were experiencing. If you're still hitting this, please mention me here and attach a bug report identifier.
