### ISSUE TITLE
Google Fi Wi-Fi calling doesn't work when tailscale is on

### ISSUE THREAD

**Issue by mrzv** [tailscale/tailscale#13189]
### What is the issue?

I use Google Fi service on my Android phone (Google Pixel 5). When Tailscale is turned on, the phone won't use Wi-Fi calling. As soon as I turn it off, it goes to Wi-Fi calling without a hitch.

### OS

Android

### OS version

14

### Tailscale version

1.70.0

### Bug report

BUG-d74564722af4cbef63c5c66b185de1cd13ef2574d6c1a04745b2c9715fec75a8-20240820005818Z-1c423aca3041bc23

**Comment by agottardo** [comment]
@mrzv are you able to determine if selecting any telephony-related apps in app-based split tunneling within the app settings resolves the issue? I unfortunately do not have a device with a Wi-Fi calling enabled plan to verify this.

**Comment by mrzv** [comment]
I just tried, but it didn't seem to help. I added Phone (com.google.android.dialer), Phone Calls (com.android.server.telecom), Phone Services (com.android.phone), Phone and Messaging Storage (com.android.providers.telephony), and Google Fi itself (com.google.android.apps.tycho). Anything else I should try?

**Comment by mrzv** [comment]
Actually, I'm wrong. It does seem to place calls over wifi with those apps excluded; it just doesn't always show the icon. I need to experiment with this more.

**Comment by agottardo** [comment]
The overwhelming majority of resources online tells me that Wi-Fi Calling traffic should never routed via any VPN on Android devices.

**Comment by mrzv** [comment]
I don't think it's the matter of getting routed over the VPN. It's just that when the VPN is on, it chooses not to use WiFi calling. How it makes that choice is unclear to me.

**Comment by agottardo** [comment]
It would be helpful if you could use `adb logcat` to collect logs from the device when you start Tailscale or notice Wi-Fi Calling dropping. If you spot any relevant error messages, we can investigate further. Unfortunately, Android APIs don't provide us with any observability or flags related to Wi-Fi Calling: it's handled entirely by the OS and we can't control it.

**Comment by mrzv** [comment]
Let me observe it some more with these new exclusions. Maybe they fixed the problem.

**Comment by mrzv** [comment]
As far as I can tell, this is now working consistently. Many thanks for your help! I'm going to close this issue.
