### ISSUE TITLE
Redundant  drive shares notify

### ISSUE THREAD

**Issue by jqknono** [tailscale/tailscale#13195]
### What is the issue?

Each time a network map changes, a drive shares notifies.

### Steps to reproduce

1. Run headscale control server
2. Subscribe notify with localapi `watch-ipn-bus`
3. Send a netmap response to the client

The subscribed notification gets two, 
- notify netmap change
- notify drive share change

which should be only one, since no drive share changes.

**Comment by agottardo** [comment]
cc @oxtoacart

**Comment by jqknono** [comment]
Fixed with #13196 , please review.
