### ISSUE TITLE
PAM session not opened when connecting via SSH

### ISSUE THREAD

**Issue by bigon** [tailscale/tailscale#13198]
### What is the issue?

When connecting via SSH, it seems that there are no PAM session opened

That means that the user is not registered in `wtmp` or there is no logind session or the loginuid is not set (this is a problem for auditing purpose)

```
$ cat /proc/$$/loginuid
4294967295
```
```
$ w
 14:18:40 up 19 days,  2:00,  0 users,  load average: 0.21, 0.08, 0.04
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
```
```
$ loginctl 
SESSION  UID USER    SEAT TTY   STATE  IDLE SINCE
     c5 2000 laurent      pts/2 active no    
```
(note the "c" before the session id)

Opening a PAM session might also fix the SELinux issue where the used is not running on the proper context (https://github.com/tailscale/tailscale/issues/4908#issuecomment-2298709142)

### Steps to reproduce

1. Install tailscale with SELinux enabled
2. Allow SSH access
3. Connect using SSH via tailscale

### OS

Linux

### OS version

Almalinux 9

### Tailscale version

1.72.0

**Comment by bigon** [comment]
Actually all of this is blocked by SELinux and works when SELinux is in permissive.

So this bug might be closed in favor of a more general SELinux bug

**Comment by bradfitz** [comment]
Yeah, #4908 seems to be the existing bug for this. We can use that. See https://github.com/tailscale/tailscale/issues/4908#issuecomment-1400254802 on that issue.
