### ISSUE TITLE
FR: ADD Australia to Available regions for Mullvad Add-on

### ISSUE THREAD

**Issue by conalex4488** [tailscale/tailscale#13190]
### What are you trying to do?

FR: ADD Australia to Available regions for Mullvad Add-on

### How should we solve this?

FR: ADD Australia to Available regions for Mullvad Add-on

### What is the impact of not solving this?

proxy server

### Anything else?

FR: ADD Australia to Available regions for Mullvad Add-on

**Comment by agottardo** [comment]
Duplicate of tailscale/tailscale#9314
