### ISSUE TITLE
filch: consider O_SYNC (macOS: F_NOCACHE) for log files

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1320]
A long-shot reason why we think we see occasional panics without logs on macOS is that write(2) from the Go runtime to the fd followed by exiting quickly without a proper close(2) is dropping the write. I don't have any good analysis of darwin that shows this is likely, but I believe the POSIX spec says its possible.

On Linux there is an O_SYNC option for open(2) that would make the write(2) call to the log txt file reliable. There is no direct equivalent on macOS (it's relatively-new POSIXness), but it does have an fcntl option F_NOCACHE that, while under-documented, Googling suggests is similar. Perhaps we should enable it?

**Comment by bradfitz** [comment]
We could probably write a stress test on macOS that shows whether this is the case.

**Comment by crawshaw** [comment]
At this point I’m convinced we weren’t losing logs. Can try this again if we ever do find evidence of log loss.
