### ISSUE TITLE
Tailscale could not establish an encrypted connection with '"controlplane.tailscale.com"': likely intercepted connection; certificate is self-signed by CN=self-signedKey,O=Sagemcom Ca,C=FR

### ISSUE THREAD

**Issue by nalzok** [tailscale/tailscale#13212]
### What is the issue?

On macOS, I got a warning message:

<img width="388" alt="SCR-20240821-liuh" src="https://github.com/user-attachments/assets/42edd017-a866-48c6-8957-314c94cd7be5">

<img width="612" alt="image" src="https://github.com/user-attachments/assets/1b7b9368-a972-45ee-a9ec-7fdf4c00ed4d">

This is echoed by the Tailscale CLI:

```
/Applications/Tailscale.app/Contents/MacOS/Tailscale status

... (machines omitted)

# Health check:
#     - Tailscale could not establish an encrypted connection with '"controlplane.tailscale.com"': likely intercepted connection; certificate is self-signed by CN=self-signedKey,O=Sagemcom Ca,C=FR
```

### Steps to reproduce

Install Tailscale through the Mac App Store, log in through the app, and check the GUI after a while.

### Are there any recent changes that introduced the issue?

I have been using Tailscale for ~2 years, and the warning only popped up a few weeks ago. Around the same time I upgraded from macOS Monterey to Ventura 13.6.9, but I cannot remember if the warning first appeared before or after the upgrade. I don't think I did any weird certificate-signing operations.

### OS

macOS

### OS version

macOS 13.6.9 (22G830)

### Tailscale version

1.72.0

### Bug report

BUG-b39889e0e73ec2ac6a16e595144c029bfeb44010007d9eababd6059b6efd4e72-20240821164425Z-4d8ccdd92cb1a20d

**Comment by nalzok** [comment]
I see. This is my home network. Recently I saw some maintenance personnel from our ISP ([Spectrum](https://www.spectrum.com/)) around the neighborhood, and perhaps they made some changes to the network configuration. I'll see if I can disable that "firewall" on my router/modem.

**Comment by agottardo** [comment]
It's unlikely this was caused by network maintenance; more likely, they might have enabled some kind of 'safe browsing' service at the ISP level, which is blocking Tailscale. Check in your account settings for a family filter-related feature.

**Comment by aarons** [comment]
I'm having this exact same issue. Everything worked well for years, now I'm getting that error message popping up. This is also a home setup.

Mac OS - running Sonoma 14.7
Using tailscale installed via Mac App Store
Also a spectrum customer 
Also see Sagemcom in the error message

<img width="474" alt="image" src="https://github.com/user-attachments/assets/b7169228-33e0-4b24-89db-218a6324a9ff">

I haven't enabled any safe browsing options at the modem/ISP level. But I do use nextdns and that has some content filters enabled. 

NextDNS is setup as a global nameserver in my tailscale config and the local tailscale client is set to use DNS settings from tailscale, and I see the nextdns resolver set. Queries from the mac do run through nextdns when connected to tailscale, so it seems setup correctly.

My router is also set to use nextDNS for DNS lookups. That hasn't been an issue in the past, but I'll try removing that configuration to see if there was something conflicting.

**Comment by aarons** [comment]
Just a follow up, Spectrum had a "Security Shield" setting toggled on.

Disabling it fixed the issue from occurring (it took a few hours for the setting to stick).

**Comment by xorroproprop** [comment]
@aarons This ended up being the same error for me, thanks!
