### ISSUE TITLE
Searching for machines on Android does not work

### ISSUE THREAD

**Issue by joshvocal** [tailscale/tailscale#13218]
### What is the issue?

Typing into the input field does not filter results

### Steps to reproduce

1. Launch the app and connect
2. Type into the search input field
3. Observe

**Expected result:**
* Typing into the input field correctly filters machines

### OS

Android

### OS version

Android 13

### Tailscale version

1.73.13-taf3d3c433-g536e1adcc42

### Bug report

BUG-c90774fc8cb8af8b320ef05e554c7d2a7e64ef90d9484eebc67187954d5b2ecb-20240822004042Z-328864b40fdc7623

**Comment by agottardo** [comment]
cc @kari-ts
