### ISSUE TITLE
Cannot do a clean uninstall of tailscale App Store (MacOS) to switch to tailscale.pkg

### ISSUE THREAD

**Issue by spkis** [tailscale/tailscale#13222]
### What is the issue?

Hey there!
I have a couple of macs which I would like to be able to use Tailscale.
So far so good - the new pkg installer works fine on fresh macbooks.
My macbook had the app store app installed. 

I removed it, but still got two packages through pkgutil visible. 
I was able to remove them with:
sudo pkgutil --forget com.tailscale.ipn.macsys
Password:
Forgot package 'com.tailscale.ipn.macsys' on '/'.

user: kissinger ~/FleetDM-Installer
➜ pkgutil --pkgs|rg tailscale
io.tailscale.ipn.macos

user: kissinger ~/FleetDM-Installer
➜ pkgutil --pkgs|rg tailscale^C

user: kissinger ~/FleetDM-Installer
➜ sudo pkgutil --forget io.tailscale.ipn.macos
Forgot package 'io.tailscale.ipn.macos' on '/'.

### Steps to reproduce

Unclear, however even after all is removed and deleted, it's not asking to add system extension and the application does start, but doesn't start UP into the task bar etc.
If I try to start again, it says "please check the icon is hidding in menu!"

I think the issue is that the system extension is somehow not 100% removed or broken?
If I now try to uninstall the pkg version, I get:
<img width="566" alt="image" src="https://github.com/user-attachments/assets/7738b52a-6589-4f33-8644-0f6bf780d566">

### OS

macOS

### OS version

15.0 - but happened before beta

### Tailscale version

1.72.0

**Comment by spkis** [comment]
I also saw, that I have the system extensions here:
<img width="852" alt="image" src="https://github.com/user-attachments/assets/73080e1b-d2a8-4613-bed8-fbcda2a11ce4">

but nothing is actual showing up here:
<img width="493" alt="image" src="https://github.com/user-attachments/assets/7acfd827-efcf-457f-adb7-a1bfda86774d">

**Comment by spkis** [comment]
I was able to remove the system extension stuff etc. however, now I have the app in this state that it doesn't find/connect to the tailscaled server :(

**Comment by agottardo** [comment]
We provide [instructions](https://tailscale.com/kb/1069/uninstall?tab=macos+%28app+store%29) to completely remove any trace of the macOS App Store distribution. Please follow those steps, and make sure you reboot your Mac to erase any caches that might still be referencing the App Store extension. If you're still experiencing issues, we recommend you contact support so they can help you address the problem.

**Comment by songkeys** [comment]
> I also saw, that I have the system extensions here: <img alt="image" width="852" src="https://private-user-images.githubusercontent.com/114989348/360502291-73080e1b-d2a8-4613-bed8-fbcda2a11ce4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkwODIzNzUsIm5iZiI6MTc1OTA4MjA3NSwicGF0aCI6Ii8xMTQ5ODkzNDgvMzYwNTAyMjkxLTczMDgwZTFiLWQyYTgtNDYxMy1iZWQ4LWZiY2RhMmExMWNlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyOFQxNzU0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjNlN2JiYzRmYzNmZWJjMjU0YmVkYTkzZTM0NTQ2ZjdmYzg3YjQ1ZDQ1M2U3NGZkYWQxMDJmZGU4NWRhZmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sB6XOlSrrbfjN4YhQEHK_4MJs-4cT78L0Hy8-qTAzzI">
> 
> but nothing is actual showing up here: <img alt="image" width="493" src="https://private-user-images.githubusercontent.com/114989348/360502720-7acfd827-efcf-457f-adb7-a1bfda86774d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkwODIzNzUsIm5iZiI6MTc1OTA4MjA3NSwicGF0aCI6Ii8xMTQ5ODkzNDgvMzYwNTAyNzIwLTdhY2ZkODI3LWVmY2YtNDU3Zi1hZGI3LWExYmZkYTg2Nzc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyOFQxNzU0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjA4NjcyZWEzODA5ZDA1ODM0Yzg0NDNlYzU4NTBmNjViNTAyNTU4M2Y4MTVjZjZjOTlkNjcxZTc0NWI2YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z6bDolbRQiTl5PCJgsTzP5o-Tmn7dEaR_Wecc5C0POA">

Do you know how to remove the system extensions here?

I tried the [instructions](https://tailscale.com/kb/1069/uninstall?tab=macos+%28app+store%29), also tried delete it manually with `sudo`, it says `The operation can’t be completed because you don’t have permission to access some of the items.`

**Comment by guibracco** [comment]
I'm having the same problem (standalone app) with a stubborn system extension. Removing a system extension seems to involve disabling the System Integrity Protection (SIP), which is _hardly_ recommendable. There should be an easier way.
