### ISSUE TITLE
add a manual page for documentation

### ISSUE THREAD

**Issue by lfarkas** [tailscale/tailscale#1322]
it would be required as for all linux program a few manual pages. at least for tailscale and tailscaled. eg is there anywhere documented this command:
tailscale up --accept-dns=false
imho this should have to be the minimum.
￼
￼

**Comment by B-LUC** [comment]
I second that request.

**Comment by bradfitz** [comment]
Between our website's docs (e.g. https://tailscale.com/kb/1080/cli) and the tools' built-in docs (`tailscale --help`, `tailscale up --help`, etc), I don't think we want to maintain a third set of docs.

If we want to be officially supported in a distro that required man pages (such as Debian) then we might reconsider, but I don't think we'll be doing man pages.

As a compromise, we'd accept minimal "see this URL or run --help" man pages if somebody contributed them.

Feel feel free to file other bugs about specific documentation omissions and we'll fix in our two supported places. Just not in manpages.
