### ISSUE TITLE
add a possibility to run a program/script after the tailscale interface bring up

### ISSUE THREAD

**Issue by lfarkas** [tailscale/tailscale#1323]
it'd be very useful to add a possibility to run a program/script after the tailscale interface bring up. eg:
systemd-resolve --interface tailscale0 --set-dns 192.168.208.1 --set-domain example.com --set-domain example.org
currently it's not possible.

**Comment by bradfitz** [comment]
As of Tailscale 1.4 we now use systemd-notify, so you should be able to do your own systemd units that depend on us being up.

**Comment by bradfitz** [comment]
But also this sounds like https://xyproblem.info/ ... your real issue is something about DNS not working?

**Comment by lfarkas** [comment]
my real issue is that there is an internal network, dns and domains behind one of the tailscale node. but i do NOT like to use this internal dns for all of my domain only for this internal domains. this works perfectly with resolvectl. but i'd like to add the above dns only for tailscale interface and only when it's up.
and yes i know i can do it with systemd-networkd too, but it can be used without it.
anyway i'l look into systemd-notify.
