### ISSUE TITLE
tailscale stop on /e/ OS

### ISSUE THREAD

**Issue by jo2904** [tailscale/tailscale#13239]
### What is the issue?

I've been using tailscale on /e/ OS (a fork of lineage) since the 2.2 update. Tailscale starts up, connects, the VPN logo appears, then after a few seconds it disappears but the app still tells me I'm connected. I've noticed that when I change the tailscale version to 1.68.1 it runs for a few minutes but then stops.

### Steps to reproduce

Install /e/ OS 2.3-t-20240819...-bluejay
install tailscale from F-Droid or App lounge
Log in to tailscale
wait a few seconds

### Are there any recent changes that introduced the issue?

Yes
Either upgrade tailscale to 1.68.2 and then to 1.70
Update /e/ OS to 2.2 then 2.3
The two were concomitant and the updates were automatic, so I don't remember the order.

### OS

Android

### OS version

/e/OS 2.3-t-20240819427106-dev-bluejay

### Tailscale version

1.68.2 and 1.70.0

### Other software

The default /e/ OS app

### Bug report

BUG-e36031bc91af806e700fb12d6ca1a90e54452053cd48281d0a0d3d360917680b-20240823073751Z-5354d3361f77f4ed

**Comment by agottardo** [comment]
Your logs show:
```
2024-08-23T07:56:35Z | 5.9M/240.4M authReconfig: ra=true dns=true 0x02: VPN service not prepared or was revoked
2024-08-23T07:56:35Z | [unexpected] VpnService.protect(118) returned false
```

- Do you have other VPN apps installed? If so, which ones? Can you try uninstalling, then rebooting your phone, and see if the issue persists?
- Do you have Always-on VPN enabled in the Android settings? 
- Do you have 'Block connections without VPN' enabled?

**Comment by mattiascockburn** [comment]
I can reproduce this issue on /e/OS 2.5 and Tailscale 1.76.1, which is the most current release.

**Comment by agottardo** [comment]
@mattiascockburn 1.76**.6** is the most current release. Please provide a bug report identifier or a crash trace.

**Comment by mattiascockburn** [comment]
Cheers,

here is the info i obtained from `adb logcat`:

```
12-02 20:02:58.856  1697  2045 I ActivityManager: Start proc 27673:com.tailscale.ipn/u0a226 for top-activity {com.tailscale.ipn/com.tailscale.ipn.MainActivity}
12-02 20:02:58.877 27673 27673 E m.tailscale.ipn: Not starting debugger since process cannot load the jdwp agent.
12-02 20:02:58.888  1697  5840 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10226; state: DISABLED
12-02 20:02:58.888  1697  5840 D CompatibilityChangeReporter: Compat change id reported: 273564678; UID 10226; state: DISABLED
12-02 20:02:58.892 27673 27673 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10226; state: ENABLED
12-02 20:02:58.905 27673 27673 V GraphicsEnvironment: ANGLE Developer option for 'com.tailscale.ipn' set to: 'default'
12-02 20:02:58.905 27673 27673 V GraphicsEnvironment: ANGLE GameManagerService for com.tailscale.ipn: false
12-02 20:02:58.905 27673 27673 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
12-02 20:02:58.907 27673 27673 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-02 20:02:58.907 27673 27673 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-02 20:02:58.915 27673 27673 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
12-02 20:02:58.918 27673 27673 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
12-02 20:02:58.918 27673 27673 D WM-Schedulers: Created SystemJobScheduler and enabled SystemJobService
12-02 20:02:58.931 27673 27689 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10226; state: ENABLED
12-02 20:02:58.947 27673     0 E Go      : panic: binary built with tailscale_go build tag but failed to read build info or find tailscale.toolchain.rev in build info
12-02 20:02:58.947 27673     0 E Go      :
12-02 20:02:58.947 27673     0 E Go      : goroutine 1 [running]:
12-02 20:02:58.947 27673     0 E Go      : tailscale%2ecom.init.0()
12-02 20:02:58.947 27673 27698 E GoLog   : panic: binary built with tailscale_go build tag but failed to read build info or find tailscale.toolchain.rev in build info
12-02 20:02:58.947 27673     0 E Go      : 	/home/vagrant/go/pkg/mod/tailscale.com@v1.76.1-0.20241015182059-24929f6b6111/assert_ts_toolchain_match.go:17 +0x190
12-02 20:02:58.947 27673 27698 E GoLog   :
12-02 20:02:58.948 27673 27695 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27695 (m.tailscale.ipn), pid 27673 (m.tailscale.ipn)
```

I only have access to tailscale 1.76.1, as provided by the default F-Droid repository and/or the AppLounge of /e/os.

**Comment by agottardo** [comment]
> `panic: binary built with tailscale_go build tag but failed to read build info or find tailscale.toolchain.rev in build info`

You're using an outdated version of the app distributed by a third party. Back in October, F-Droid released an APK that crashes on launch (details [here](https://github.com/tailscale/tailscale/issues/13850)). The broken APK was later pulled, but it still made it to many users, especially since F-Droid doesn't do phased rollouts for app updates.

As outlined in our documentation, we do not create or verify APKs released by third parties, and we are not responsible for their content. To resolve your issue, and more generally for a more reliable experience, we recommend using the official builds provided by Tailscale, which are tested by our QA team before release. If you prefer not to use the Play Store, you may download the latest APK directly from [pkgs.tailscale.com](https://pkgs.tailscale.com/stable/#android).
