### ISSUE TITLE
Tailscale for iOS requests to reinstall VPN configuration if started without being active slot

### ISSUE THREAD

**Issue by BionicBison05** [tailscale/tailscale#13230]
### What is the issue?

If other VPNs are configured on iOS and one of those happens to be selected in iOS VPN settings instead of Tailscale (not necessarily active, just selected), Tailscale requests to reinstall the VPN configuration upon starting the app (usually after force close). Denying this request leads to the Tailscale VPN configuration being uninstalled.

### Steps to reproduce

- Configure a second VPN in iOS
- Force close the Tailscale app
- Make sure the second VPN is selected in iOS VPN settings instead of Tailscale
- Launch Tailscale and observe that you must reinstall the VPN configuration
- Additionally, you can force close and relaunch Tailscale while the active VPN configuration is Tailscale and observe that there is no request to reinstall, but problem immediately occurs once Tailscale is launched without being the active VPN

### Are there any recent changes that introduced the issue?

This only started occurring in 1.72.0.

### OS

iOS

### OS version

iOS/iPadOS 17.6.1

### Tailscale version

1.72.0

### Other software

Any non-Tailscale VPN being configured should trigger this issue.

### Bug report

BUG-2912e56cc2dfef4495a7d11918f99d824f24d73ebafa99130500b74cb02f3724-20240822200240Z-b86f64270e8470af

**Comment by agottardo** [comment]
Reproed. Appears to be a recent regression. If the NETunnelProviderManager belonging to Tailscale is disabled by another VPN app, recently introduced logic is determining that such configuration is outdated, and reinstalling the VPN configuration is necessary, which is wrong.

**Comment by agottardo** [comment]
We have a fix (in a private branch, so you can't really see it). It requires testing before we can ship it.

**Comment by agottardo** [comment]
A build with a fix has been submitted to TestFlight and will be available once Apple approves it.

**Comment by agottardo** [comment]
Fix shipped in TestFlight v1.73.19.

**Comment by agottardo** [comment]
Submitted in v1.72.2 to Apple for the App Store release, will be available pending approval.
