### ISSUE TITLE
cmd/gitops-pusher: check local file formatting

### ISSUE THREAD

**Issue by awly** [tailscale/tailscale#13249]
Tailscale API formats the ACL file on save. This means that you can POST one version and then GET a different one: semantically the same, but not byte-by-byte identical. This causes the next push attempt to fail because local old ACL version hash differs from the one that API returns.

It should check for formatting diffs and fail to test/apply the new ACLs.

cc @creachadair @fylie

**Comment by creachadair** [comment]
It looks like `gitops-pusher` is already doing the right thing in this case—we investigated and discovered the problem was in a separate script that we had running in CI. We fixed that script, and I think the Go program is already OK.
