### ISSUE TITLE
derper HTTPS on non-standard port

### ISSUE THREAD

**Issue by ImpostorKeanu** [tailscale/tailscale#13242]
For derper, it looks like LetsEncrypt procurement over a non-standard port is currently unsupported.

https://github.com/tailscale/tailscale/blob/3c66ee3f57a6e5161fa518b45b1b3f5c64e9878e/cmd/derper/derper.go#L54
https://github.com/tailscale/tailscale/blob/3c66ee3f57a6e5161fa518b45b1b3f5c64e9878e/cmd/derper/derper.go#L169

I have a use case where HTTPS via LetsEncrypt over port 8443 is required, so I applied a [little patch here](https://github.com/tailscale/tailscale/compare/main...ImpostorKeanu:tailscale:main). It adds a `disable` option to `-certmode`, thereby allowing the user to actively disable HTTPS when needed.

Would a PR for this change be beneficial to the project?

**Comment by bradfitz** [comment]
I don't understand your problem or use case.

Your patch doesn't seem to line up with your comment above.

Do you want TLS at all?

Where are you getting your certs?

If LetsEncrypt, note that ACME `tls-alpn-01` only works over port 443. That's not derper's restriction.

**Comment by ImpostorKeanu** [comment]
Thank you for pointing out my misunderstanding.

I didn't realize `tls-alpn-01` required port 443 and I accidentally left a certificate cached while testing my patch, so it seemed as though it was working as expected.

Apologies for taking up your time or creating any confusion.
