### ISSUE TITLE
Tailscale on Android is out of date

### ISSUE THREAD

**Issue by marek22k** [tailscale/tailscale#13240]
### What is the issue?

Hello,

it seems that version 1.72.0 has not been tagged in the Android repo, which is why F-Droid is not updating it. Maybe this could be made up for?

See also https://gitlab.com/fdroid/fdroiddata/-/issues/3343

**Comment by agottardo** [comment]
We recently implemented some changes in our build infrastructure that caused this. Namely, the release got tagged with a version, but we didn't increment the `versionCode`. I'm addressing this now by pushing a new commit that increments it, and moving the tag.

**Comment by yparitcher** [comment]
@agottardo 
This appears to not have been fixed in a automated way, as the version code for 1.74 is still 241
https://github.com/tailscale/tailscale-android/blob/release-branch/1.74/android/build.gradle

Therefore fdroid has not updated yet.

**Comment by agottardo** [comment]
cc @kari-ts
