### ISSUE TITLE
FR: Allow use of Mullvad DNS Content Blockers

### ISSUE THREAD

**Issue by ScrollPoet** [tailscale/tailscale#13256]
### What are you trying to do?

Mullvad vpn has dns content blocking options that can be enabled. This can provide basic content blocking options to block ads, trackers, malware, adult content, gambling and social media. Mobile device content blocking is not able to block as effectively on iOS and native Mullvad’s content blocking has been much more powerful.

### How should we solve this?

Add the different dns content blocking options in the client apps.

### What is the impact of not solving this?

Using local software content blocking.

**Comment by machineh3d** [comment]
I'm already a mullvad user so I had no problem paying the extra 5 bucks to use mullvad with tailscale but was severely disappointed to see I couldn't use mullvads content blocking through tailscale mullvad exit node

**Comment by felschr** [comment]
@timtailscale I would like to set the nameservers separately for clients using Mullvad exit nodes than for the rest of the tailnet. "Override local DNS" forces the nameservers onto all devices in the tailnet.
