### ISSUE TITLE
iOS: No Home Relay Server/Relay Server Unavailable

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#13265]
### What is the issue?

Get the following error messages when attempting to connect to Tailnet.  Unable to access devices on my Tailnet using local IP.  

![IMG_2635](https://github.com/user-attachments/assets/b01f5450-46ce-4a2f-96eb-72a8bea836ce)

### Steps to reproduce

Install 1.73.19

### Are there any recent changes that introduced the issue?

Installed 1.73.19

### OS

iOS

### OS version

18.0b7

### Tailscale version

1.73.19

### Other software

Dropped back to 1.72.0 and problem did not reoccur.
Also dropped back to 1.73.14 and problem did not reoccur.

### Bug report

1.73.19
BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240826203157Z-09efb1039c60e5f8
Sysdiagnose iCloud link sent to Andrea at tailscale dot com 
1.72.0
BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240826204723Z-2338651cd363436d
1.73.14
BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240826205139Z-23ad99f0504827f2

**Comment by elvisimprsntr** [comment]
Same issue with 1.73.114
BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240912111517Z-5da339666c517d68

![19B6BFBA-A3A8-43D7-A380-7185C4B973C2_1_102_o](https://github.com/user-attachments/assets/24f22f4e-36a0-48c2-87ff-23a9502a573a)


No issue when dropped back to 1.73.14
BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240912111743Z-7410cba6ed28ed99

**Comment by Maronato** [comment]
I'm seeing the same issue on 1.74.0.

It was working fine on 1.72.x.
Reinstalling and reauthenticating doesn’t fix it.

**Comment by atton16** [comment]
Same issue since updated to 1.74.0.

iOS 17.6.1

**Comment by hassila** [comment]
Also on macOS Sonoma 14.6.1 since today:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/8072e05f-bcf5-4d61-be76-a2bb576cb423">

**Comment by hassila** [comment]
updated to latest `1.74.0`, still same problem

**Comment by hamlynt** [comment]
Same issue on `1.74.0`

**Comment by djsamlb** [comment]
Same issue on ### 1.74.0

**Comment by rfoxxxy** [comment]
Same issue on `1.74.0` on `iOS 18.1b3`

**Comment by elvisimprsntr** [comment]
Same issue on 1.75.15

BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240920094030Z-6f8c1ac80ac2e5ff

**Comment by ekadic7** [comment]
The same issue on the Macbook
<img width="494" alt="Screenshot 2024-09-20 at 12 08 04" src="https://github.com/user-attachments/assets/a926da7d-4552-43e4-80c1-76bfac5149e2">

macos 15.1 Beta (24B5046f)
tailscale 1.74.0

**Comment by ekadic7** [comment]
> The same issue on the Macbook <img alt="Screenshot 2024-09-20 at 12 08 04" width="494" src="https://private-user-images.githubusercontent.com/157036762/369381030-a926da7d-4552-43e4-80c1-76bfac5149e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDM2NjYsIm5iZiI6MTcyNjg0MzM2NiwicGF0aCI6Ii8xNTcwMzY3NjIvMzY5MzgxMDMwLWE5MjZkYTdkLTQ1NTItNDNlNC04MGMxLTc2YmZhYzUxNDllMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNDQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzlhMGQ5YzQzYTgzNGRjYmJiMTc0MmQwNDZiNjcwNGYzYTFjODVmMGVlYTk5Y2MxNGFhNTE5NTBiNzJlZTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U4sU4hN8jyFwTMrDX5xC6c-HVA0TpshSBY5RAynf99Q">
> 
> macos 15.1 Beta (24B5046f) tailscale 1.74.0

Interestingly, this is only happening on WIFI with strong security Sophos Firewall is blocking it, in my understanding, cause when I connect to the hotspot, it works fine...

**Comment by bedr0** [comment]
This same issue began happening with my iPhone 15 running iOS 17.6.1 a few weeks ago, when this happens I get no connection on many apps, having to disconnect Tailscale to have connectivity again.

![IMG_6196](https://github.com/user-attachments/assets/42314422-8088-4d3e-890c-34eb6e84339c)

**Comment by alexl4321** [comment]
same ios18 1.74.0.

**Comment by panthole** [comment]
same ios18 1.74.0.

**Comment by benhovinga** [comment]
Same issue just started today. iOS 17.7, Tailscale 1.74.0.

![image](https://github.com/user-attachments/assets/4ab91c82-6d5b-4311-ba0e-4a50469b91e5)

Bug report
`BUG-9089315768581210bb12750876a595679d576033b8a8d0d3c2f7688d9402fec2-20240923145809Z-885c45de28f1cc6`

**Comment by elvisimprsntr** [comment]
Same issue with 1.74.15 on iOS 18.1b5.

BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240924091457Z-7e244c6f88091af2

Had to drop back to 1.73.14

**Comment by piavgh** [comment]
I got this issue today.

Is it because of the client software or the relay server has issue?

**Comment by elvisimprsntr** [comment]
Unknown.   Doesn't seem to be getting any traction, even with the large number of reports.

**Comment by hamlynt** [comment]
> Is it because of the client software or the relay server has issue?
No issues with iPad and MacBook on the same physical network and on the same DNS, which would suggest it's specific to the iPhone app.

**Comment by ScoobyDoo27** [comment]
How are you rolling back to a previous version on iOS? I'm having the same issues with my iPhone 16 Pro Max on iOS 18.0 running tailscale version 1.74.0

**Comment by elvisimprsntr** [comment]
> How are you rolling back to a previous version on iOS? I'm having the same issues with my iPhone 16 Pro Max on iOS 18.0 running tailscale version 1.74.0

https://tailscale.com/kb/1083/install-unstable

**Comment by agottardo** [comment]
We're investigating this and hope to have a fix available soon. It seems to only affect some subset of users and only on iOS, which is making it tricky to reproduce. 

One finding is that by disconnecting and reconnecting with the toggle in the app UI, Tailscale will eventually connect successfully. I haven't found any evidence that reinstalling the app again or logging in from scratch is going to help with this issue.

If you're experiencing this, please make sure to attach a bug report identifier.

**Comment by cybrnook** [comment]
Also getting this issue

BUG-09272fd290cbc4b4d4ba10eb72d010a5a1041762d397b44a03bdd5ce9c7d20d4-20240925033143Z-9dbb09199f43afe6

**Comment by cybrnook** [comment]
> > How are you rolling back to a previous version on iOS? I'm having the same issues with my iPhone 16 Pro Max on iOS 18.0 running tailscale version 1.74.0
> 
> 
> 
> https://tailscale.com/kb/1083/install-unstable
> 
> 
> 
> Not sure if it will list older versions prior to signing up for TestFlight builds.

Thankfully it does 😮‍💨

**Comment by elvisimprsntr** [comment]
> We're investigating this and hope to have a fix available soon. It seems to only affect some subset of users and only on iOS, which is making it tricky to reproduce.
> 
> One finding is that by disconnecting and reconnecting with the toggle in the app UI, Tailscale will eventually connect successfully. I haven't found any evidence that reinstalling the app again or logging in from scratch is going to help with this issue.
> 
> If you're experiencing this, please make sure to attach a bug report identifier.

I am also seeing this problem on 1.74.1 docker container running on TrueNAS SCALE.  

`2024-09-25 01:16:35.225459+00:002024/09/25 01:16:35 health(warnable=no-derp-home): ok
2024-09-25 01:16:35.225552+00:002024/09/25 01:16:35 health(warnable=no-derp-connection): ok'


BUG-754ae15aa81e49192db33b1a04b6dbed8ba16127800a40ba0fc45d6637be579f-20240925060602Z-b91aabd419f05d3a


<img width="481" alt="Screenshot 2024-09-25 at 2 03 30 AM" src="https://github.com/user-attachments/assets/53a1c450-e9fd-490a-a43d-b96c6c0972d1">

**Comment by alexl4321** [comment]
> We're investigating this and hope to have a fix available soon. It seems to only affect some subset of users and only on iOS, which is making it tricky to reproduce.
> 
> One finding is that by disconnecting and reconnecting with the toggle in the app UI, Tailscale will eventually connect successfully. I haven't found any evidence that reinstalling the app again or logging in from scratch is going to help with this issue.
> 
> If you're experiencing this, please make sure to attach a bug report identifier.

experiencing the same on all macos machines too

**Comment by bradfitz** [comment]
I think `Tracker.updateBuiltinWarnablesLocked`'s at fault here.
 
It has a number of paths that return before it gets to `t.setHealthyLocked(noDERPHomeWarnable)`.

**Comment by elvisimprsntr** [comment]
I suspect I am seeing the same issue on pfSense.  

`tailscale version
1.74.1
  go version: go1.23.1
`

`tailscale status
Health check:
Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.`

BUG-7aa04bfe873caa6fde5e1d023864e56d987989ccda68b7752bad3cfb4e4ed684-20240925170006Z-ee53d18c237044ef

**Comment by agottardo** [comment]
We just submitted Tailscale v1.75.34 to Apple for TestFlight testing on iOS and macOS. It includes mitigations for this issue, so please give it a try once Apple approves it and let us know your feedback.

macOS Standalone users can already download the update at https://pkgs.tailscale.com/unstable/#macos. As always, if you’re using the App Store version and want to switch to the Standalone variant (recommended), you’ll need to uninstall the App Store version, reboot your Mac, and only then install the Standalone variant.

**Comment by cybrnook** [comment]
Thanks for the fast response, eager to test.

**Comment by cybrnook** [comment]
Unfortunately issue still exists.

BUG-09272fd290cbc4b4d4ba10eb72d010a5a1041762d397b44a03bdd5ce9c7d20d4-20240926004147Z-46ea2f32b4377b4e

![image](https://github.com/user-attachments/assets/ed9bcdef-c711-448e-bed8-e69ca50ccfb8)

**Comment by ckuburlis** [comment]
> Tailscale v1.75.34 is now available on TestFlight for iOS and macOS. It includes mitigations for this issue, so please give it a try and let us know your feedback.

I seem to still be getting no-derp-home errors on iOS, can't seem to tunnel through my Apple TV that is behind a double NAT - but can use Mullvad fine

BUG-09a33c527e6c3b613b7334b5c232bc65c8fd8975f6aac406e1af1f406b642e3f-20240926003847Z-714344129d81d7e3

**Comment by elvisimprsntr** [comment]
Same issue with 1.75.34

BUG-a27cb3c67fbab4f4c5f1eebf9f0d04a5fffac445fc32c6e37a6e4108ecfc6d83-20240926013013Z-e193d5f2d14f5111

![554C00CC-D2CA-42B0-9F20-F085B0CF7B76](https://github.com/user-attachments/assets/33ebbec3-cd57-49db-870b-912ad025d4d8)

**Comment by a2cworks** [comment]
I have upgraded Tailscale on my iPhone and iPad from 1.72.2 to 1.74.0 and had the same issue.
(And then I found this page. Should have checked it out first...)

### Devices and OS version:
1. iPhone12 Pro : iOS 17.7.0 
2. iPad 10th Gen : iOS 17.7.0 

### Tailscale version:
1.74.0
note : Upgraded from 1.72.2. 1.72.2 was working fine.

**Comment by nsmith543** [comment]
Just encountered this bug again (occurred about 5 min prior to my generating the below bug ID). I had to toggle the connect slider a few times before reconnection occurred.

Tailscale 1.74.0
iOS 18.0 (22A3354)

BUG-af7cf71348d2276551d93fc1284369bbbe6fb03190a368db2591079372da4ab5-20240926121603Z-158e520b368bffae

**Comment by agottardo** [comment]
Thank you for the feedback, we’re continuing to investigate this. Please avoid sending bug reports from versions 1.74.0 or 1.74.1: we’re already aware of the issue in those releases. What we really need are bug report IDs from users on version 1.75.34 or later, where we’ve started to introduce changes to address the problem. This will help us validate and refine those updates and catch the remaining edge cases.

---

@ckuburlis thanks for the bug report ID, we're looking at your logs

---

@elvisimprsntr same. Probably unrelated to this, but logs indicate your DNS server is returning failures for some queries and you might want to look into it (I modified the IP in the log line here, but it is your tailnet DNS resolver):

```
2024-09-26T01:29:41Z | dns udp query: resolving using "http://100.90.x.x:46767/dns-query": 500 Internal Server Error
2024-09-26T01:31:57Z | dns udp query: resolving using "http://100.90.x.x:46767/dns-query": 500 Internal Server Error
2024-09-26T01:31:59Z | dns udp query: resolving using "http://100.90.x.x:46767/dns-query": 500 Internal Server Error
```

**Comment by cybrnook** [comment]
> BUG-09272fd290cbc4b4d4ba10eb72d010a5a1041762d397b44a03bdd5ce9c7d20d4-20240926004147Z-46ea2f32b4377b4e

@agottardo this was also from 1.75.34, FYI: BUG-09272fd290cbc4b4d4ba10eb72d010a5a1041762d397b44a03bdd5ce9c7d20d4-20240926004147Z-46ea2f32b4377b4e

**Comment by agottardo** [comment]
I identified the most likely root cause of the issue. I made a fix in #13598 which will be landing in v1.75.44, coming soon to TestFlight (submitted to Apple, waiting for approval).

A recurring log line in all bug reports here, which you can only see on iOS devices running Tailscale, is:

```
attempting to do captive portal detection on interface ipsec*
```

iPhones with Wi-Fi Calling or VoLTE enabled use an IPsec tunnel to encrypt voice/text communication between the device and the carrier network. The log line above was suspicious. Why would Tailscale try to [detect Wi-Fi captive portals](https://tailscale.com/kb/1457/captive-portals) on an IPsec tunnel? Turns out we were lacking logic to exclude IPsec interfaces from captive portal detection. Attempting to [dial a connection](https://github.com/tailscale/tailscale/blob/69be54c7b65421af5cf23ce17288e1a11d73fcf9/net/captivedetection/captivedetection.go#L210) on any of these IPsec interfaces results in the captive portal detection logic hanging for a period of approximately 30-45 seconds until the attempt to connect fails. This was causing the spinning `Starting...` state when launching the client. The DERP warning was just a result of this: there was no issue with anything DERP-related at all. The Wi-Fi Calling root cause tracks with the issue reproducing in particular on iOS devices.

I'll keep monitoring to see if anything else comes up. In the meantime, please try the v1.75.44 update once it becomes available for testing.

**Comment by cybrnook** [comment]
@agottardo  when testing this, is there any scenarios we need to be aware of like on WiFi vs off WiFi?

**Comment by agottardo** [comment]
> @agottardo  when testing this, is there any scenarios we need to be aware of like on WiFi vs off WiFi?

No, if your carrier supports VoWiFi you most likely also use VoLTE, which means the issue will repro on either WiFi or off WiFi.

**Comment by cybrnook** [comment]
@agottardo  initial feedback is connections are fast and without issue.

**Comment by JtMotoX** [comment]
1.75.44 is working great! Even connecting via the Widget is fast and reliable now. Thanks @agottardo !

**Comment by elvisimprsntr** [comment]
1.75.44 no more connection issues.

**Comment by PowerPCFan** [comment]
Sounds weird but I had this issue and after letting my phone sit on the error screen for 5 mins it fixed itself

**Comment by agottardo** [comment]
[v1.74.2](https://tailscale.com/changelog#2024-10-02) is now rolling out on the App Store to deliver the fix to customers not running TestFlight builds.

**Comment by beenum22** [comment]
I just got the same error on version `1.76.2-t088d78591-g`.

BUG-de6b6b9f6965508d374617fb372ab27648d2794b308d12d6f286b54354ab9f31-20241031200933Z-d339f80d762bc8aa

![Screenshot_20241031-210910.png](https://github.com/user-attachments/assets/da935ef8-2cb4-46a6-820a-e42c30e914f8)

**Comment by InnocentRain** [comment]
I have the same problem on android with the app version 1.76.2 and the "Frankfurt" relay server. I've had this problem on and off since i started using tailscale but it has come to a point where it fails to connect at least once a day wich is incredibly annoying when i have to disable my vpn constantly and because i rely on a connection to my services running at home.

**Comment by beenum22** [comment]
> I have the same problem on android with the app version 1.76.2 and the "Frankfurt" relay server. I've had this problem on and off since i started using tailscale but it has come to a point where it fails to connect at least once a day wich is incredibly annoying when i have to disable my vpn constantly and because i rely on a connection to my services running at home.

The issue was fixed for as soon as I upgraded my Tailscale and started using the Testflight version `1.77.44-tc0a1ed86c-g`.

**Comment by SdoggaMan** [comment]
Just to chip in, this is happening frequently on Android 13, V 1.76.6!

**Comment by subcidr** [comment]
Happening very frequently on Pixel 9 Pro, Android 15.

**Comment by AntiMatterDotA** [comment]
Just adding to the reports, this is happening on Pixel 8 (Android 15)
"No home relay server: Tailscale could not connect to any relay server. Check your internet connection."

**Comment by agottardo** [comment]
@brendanlees we identified an issue that was causing this message to appear for more users than expected. We deployed the fix to the unstable version only for now and it will land for everyone in v1.78, I'm glad it's fixed for you.

**Comment by mrmuiz** [comment]
Only when i use the docket version. The Synology version runs fine.

**Comment by mrmuiz** [comment]
1.78.1  same story

**Comment by Fe2-O3** [comment]
Still happening in 1.78.1 for me. Very frustrating.

**Comment by flipbit03** [comment]
Still happening for me on 1.78.3

**Comment by mrmuiz** [comment]
Even in the latest betas this is happening. 1.79.9. Time for another solution then Tailscale.

**Comment by herder** [comment]
I also have had this error until just now, when I reconfigured my split tunneling settings. Once I did that the error seems to have disappeared.

Could anyone else confirm if this fixes the error for them? All I did was adding an app to the split tunneling list.

**Comment by swooldri** [comment]
Same issue on MacOS Sequoia 15.2 with Tailscale 1.78.1. Only appears when trying to use an Exit Node.

**Comment by TomerGamerTV** [comment]
Same as above but I also can't reach controlpanel.tailscale.com

**Comment by mrmuiz** [comment]
Still the same. Dns error and relay. Time to uninstall Tailscale and go gor another option.

**Comment by midpoint** [comment]
Tailscale could not connect to the '*' relay server

version 1.80.2
