### ISSUE TITLE
FR: k8s-operator supports proxy sts with configurable tolerations

### ISSUE THREAD

**Issue by ysicing** [tailscale/tailscale#13268]
### What are you trying to do?

Currently, the k8s-operator does not support configuring tolerations for proxy stateful sets (sts). This feature is essential for users who need to deploy proxy  in tainted nodes.

### How should we solve this?

```yaml
proxyConfig:
  taintToleration: ":NoSchedule"
```

**Comment by irbekrm** [comment]
Hi @ysicing it is already possible to configure tolerations for the proxy `StatefulSet`s via `ProxyClass` https://tailscale.com/kb/1445/kubernetes-operator-customization. Let us know if this solves your issue.

**Comment by ysicing** [comment]
@irbekrm   thank you. That solves my problem.
