### ISSUE TITLE
FR: no official repo for opensuse 15.6

### ISSUE THREAD

**Issue by rernenwein** [tailscale/tailscale#13293]
### What are you trying to do?

i upgraded opensuse to current 15.6 version, 
i found that you provide no official 15.6 version exist so i tried the version for opensuse 15.5 which seems to work

### How should we solve this?

will you provide an official opensuse 15.6 version ?

### What is the impact of not solving this?

future problem ?

**Comment by Erisa** [comment]
Duplicate of #13293
