### ISSUE TITLE
netns: finish routing loop prevention on tailscaled-mode darwin

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1331]
See whether netns works on darwin.

/cc @danderson @mkramlich

**Comment by mkramlich** [comment]
I'll check now... if I can't tell by tomorrow I'll ask here for tips

**Comment by bradfitz** [comment]
This is more of a heads up. I'd like to see some progress on Homebrew before you get too distracted by less important polish bugs.

**Comment by bradfitz** [comment]
Notes:

* IP_BOUND_IF:
```
int index = if_nametoindex("en0");
setsockopt(fd, IPPROTO_IP, IP_BOUND_IF, &index, sizeof(index))
```

* getifaddrs (`man getifaddrs`) ... as we'll also need to fix our `net/interfaces.GetState` to find the default route on darwin

**Comment by mkramlich** [comment]
I spent only like 1 hour yesterday researching this, before I stopped and resumed my focus on brew, but the IP_BOUND_IF thing is consistent with what I found too

**Comment by bradfitz** [comment]
Untested, but https://github.com/tailscale/tailscale/pull/1335. Will test later.
