### ISSUE TITLE
Tailscale for macOS suddenly not launching on login

### ISSUE THREAD

**Issue by winterqt** [tailscale/tailscale#13328]
### What is the issue?

I'm not 100% sure what caused this (maybe the recent update?), but all of a sudden, Tailscale refuses to launch on login like it always has, despite the setting being enabled. I can try to toggle the setting to see if that fixes it, but I won't do that yet in case that fixes the bug and nobody is able to reproduce it.

### Steps to reproduce

1. Update Tailscale? (Or macOS? I don't know.)

### OS

macOS

### OS version

14.6.1 (23G93)

### Tailscale version

1.72.0

### Other software

Little Snitch

### Bug report

BUG-b6db70ca2aa300a4b4634cc457f7d72f17cafcfb53546ff26b8943b7fd8849c4-20240830210441Z-09d6bde0a8102a86

**Comment by agottardo** [comment]
When did you install Little Snitch? It is known to have incompatibility issues.

```
2024-08-30T21:02:19Z 	Keychain.loadData: tailscale-serve/ea47, not available error: -25291: No keychain is available. You may need to restart your computer.
2024-08-30T21:02:19Z 	ipn-go-bridge.ReadState("_serve/ea47") error: SecureStorageError.notAvailable(status=-25291, message=No keychain is available. You may need to restart your computer.) 
```

Please try restarting. I also suggest you switch to the [Standalone variant](https://tailscale.com/kb/1065/macos-variants) of the client. It is less likely to experience incompatibility issues such as this one.
