### ISSUE TITLE
MagicSock function ReceiveDERP not running

### ISSUE THREAD

**Issue by danka621** [tailscale/tailscale#13322]
### What is the issue?

When connecting to an open WIFI with my iphone, Tailscale presents the following warning:
"Warning Magicsock Function Not Running
The MagicSock function ReceiveDERP is not running. You might experience connectivity issues.
Code: magicsock-receive-func-error
Magicsock Function Name: ReceiveDERP"

Pinging any of my devices fails. (pinging with Net Analyzer resp Tailscale app)

Tried restarting Tailscale and tried disconnecting/connecting to tailscale.

### Steps to reproduce

Connected to wifi.

### OS

iOS

### OS version

iPhone 12. iOS 17,6,

### Tailscale version

1.72.0

### Other software

Home Assistant

### Bug report

BUG-dc656708d8f0eda72fda191676a2177199d0bae3e5ccce8b0c86954716b9eb4d-20240830085716Z-0faafc2ece84768b

**Comment by danka621** [comment]
Problem persists even after upgrading to Tailscale 1.72.2.

**Comment by kradalby** [comment]
Probably related (possibly duplicate) of #13204

**Comment by danka621** [comment]
> Probably related (possibly duplicate) of #13204

Maybe, but in my case, I also have connection issues. Restarting the iPhone has also not helped.

**Comment by danka621** [comment]
I am not seeing the issue right now. Think I saw it earlier today, but just now I can't provoke the problem. Only tried with my home wifi now, will try another one later.
