### ISSUE TITLE
Package for Home Assistant (HassIO)

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#1336]
**Is your feature request related to a problem? Please describe.**

Though https://www.home-assistant.io/ runs on what appears to be Debian, neither deb nor apt are present and all add-on functionality is expected to be done via Home Assistant plugins.

**Describe the solution you'd like**

It would be great to have Tailscale support as a HassIO plug-in for Home Assistant.

**Describe alternatives you've considered**

Though possible to run on a separate base system like Ubuntu or a standard Debian, installing Home Assistant is challenging and using their VM images is appealing for that reason.

**Additional context**

There is a community supported Wireguard plugin for Home Assistant, demonstrating how a Tailscale plugin might work:

- https://community.home-assistant.io/t/home-assistant-community-add-on-wireguard/134662
- https://github.com/hassio-addons/addon-wireguard

**Comment by bradfitz** [comment]
Took me too long to find docs, so a link:
https://developers.home-assistant.io/docs/add-ons/tutorial/

**Comment by bradfitz** [comment]
And https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config contains:

> privileged ... Privilege for access to hardware/system. Available access: NET_ADMIN, SYS_ADMIN, SYS_RAWIO, SYS_TIME, SYS_NICE, SYS_RESOURCE, SYS_PTRACE, SYS_MODULE or DAC_READ_SEARCH

and 

> full_access .... Give full access to hardware like the privileged mode in Docker. Works only for not protected add-ons.

Between the two of them, should be able to do all the right tun stuff.

**Comment by rubiojr** [comment]
https://github.com/tsujamin/hass-addons worked for me, including the unmerged PR to bump Tailscale to 1.4.4

**Comment by DentonGentry** [comment]
Thanks! I hadn't found that add-on. I've installed 1.2.10 using https://github.com/tsujamin/hass-addons
It seems like it is working. I'll try forking the repository and applying the 1.4.4 PR next.

**Comment by mlangenberg** [comment]
I used https://github.com/ClayKaiser/hass-addons for a few weeks, and while the setup was a breeze, I am experiencing stability issues on my rPi running Home Assistant OS. 

Without any known reason, the rPi just stops working. No automations run, no remotes work anymore. It does respond to ping, but the web interface, and SSH server (both on port 22 and 22222) don't accept any connections.

I need to power cycle to get it to work again. This setup ran for years without issues, so it's pretty weird. I did update Home Assistant Core and OS, before installing Tailscale, so maybe that's the cause. 

For now I disabled Tailscale to see if it runs stable for a week. Reporting this here for people to find with similar issues.

**Comment by colemickens** [comment]
@mlangenberg Do you use their supervisor setup? I had my dad install tailscale via deb, and then later found that the Pi's configuration (due to supervisor?) was causing dhcpcd to trash, aggressively re-leasing many times per second. Eventually the Pi just falls over. I'm not sure what exactly is the cause of the thrashing. But now I'm mentioning it since it sounds like you might have a similar issue. (`journalctl --follow` was enough to see it)

**Comment by mlangenberg** [comment]
No it's actually home-assistant/core#47928, so totally unrelated.

**Comment by jseadragon** [comment]
Is someone actively working on this? If not, I might be able to help out.

**Comment by DentonGentry** [comment]
https://github.com/tsujamin/hass-addons works quite well, to the point that I don't think we should track more effort here. I'm going to close this.

**Comment by pdecat** [comment]
There's https://github.com/hassio-addons/addon-tailscale too nowadays.

**Comment by ovizii** [comment]
> There's https://github.com/hassio-addons/addon-tailscale too nowadays.

I've been using this one for quite some time now: https://github.com/tsujamin/hass-addons/blob/main/tailscale/README.md
