### ISSUE TITLE
Can't log in via GitHub on Android with Firefox

### ISSUE THREAD

**Issue by szmarczak** [tailscale/tailscale#13373]
### What is the issue?

https://github.com/user-attachments/assets/7ee2b682-1dc4-4643-9813-795e2e2cc298

If you see `Video can't be played because the file is corrupt` above, use VLC:
1. Media -> Open Network Stream
2. https://github.com/user-attachments/assets/7ee2b682-1dc4-4643-9813-795e2e2cc298

### Steps to reproduce

See above.

### Are there any recent changes that introduced the issue?

None that I know of.

### OS

Android

### OS version

Android 14

### Tailscale version

1.72

### Other software

N/A

**Comment by tendstofortytwo** [comment]
Hi! Are you sure your default browser is set to Firefox? The screen at 0:05 looks like Chrome, but then something (the GitHub app..?) asks you for a browser, and only then Firefox seems to open. Doing half the auth flow in one browser and half in another would not work.

You can check your default browser in Settings -> Apps -> Default apps in Android 14.

**Comment by szmarczak** [comment]
Indeed my default browser is Chrome and it looks like the browser intent is created by the GitHub app. Thanks.
