### ISSUE TITLE
KB Article has a non-existent path.

### ISSUE THREAD

**Issue by bogosj** [tailscale/tailscale#1337]
**Describe the bug**
https://tailscale.com/kb/1069/uninstall has an error in a path.

**To Reproduce**
C:\Windows\USERNAME\AppData\Local\Tailscale doesn't exist.

**Expected behavior**
C:\\**Users**\USERNAME\AppData\Local\Tailscale does

**Comment by bradfitz** [comment]
Thans, fixed! It'll come along in the next regularly scheduled docs deploy, either tomorrow or (because a number of people are out for the holiday) Tuesday.
