### ISSUE TITLE
FR: remove three dots button in Accounts for Android

### ISSUE THREAD

**Issue by szmarczak** [tailscale/tailscale#13374]
### What are you trying to do?

Use an auth key. Currently the flow is like this: Accounts -> Three dots -> Use an auth key

### How should we solve this?

Accounts -> Use an auth key

### What is the impact of not solving this?

Finding the button is hard AF. No reason to have the three dots button.

### Anything else?

![image](https://github.com/user-attachments/assets/2dd34995-d41c-4e8b-97cc-7cc989fbb0a3)

The three dots button is bad DX as it hides functionality.

**Comment by agottardo** [comment]
Thank you for the effort in explaining your suggested change, but we are not going to move forward with this. These options are intentionally kept in a context menu because they are relevant to only an extremely small portion of our users. Displaying them more prominently would likely confuse the majority who don't need or use these features.

**Comment by szmarczak** [comment]
@agottardo Logging in via an auth key is much simpler given my troubles logging in: #13377 and #13373

Even Discord has log in via QR code done right.

I spent at least 15 minutes trying to log in for the first time so the UX is terrible for me. I'd like this to be a non 1-person decision. I'd highly appreciate it if you could bring this up to the appropriate team and reopen this. If you decide to not proceed with this as a team, then fine. Although please consider better solutions than the current one at production.

I'm not pinned to this specific proposal. The three buttons approach sucks. There may be other suggestions that will make logging in easier.

**Comment by bradfitz** [comment]
> I'd highly appreciate it if you could bring this up to the appropriate team and reopen this.

We discussed it as a team before @agottardo replied.

**Comment by sonovawolf** [comment]
@szmarczak  we might explore alternatives in the future (see image below) but we don't want to show those buttons right away as they are very rarely used and the more choices we present by default, the slower/more confused the majority of people will be.

![CleanShot 2024-09-04 at 16 40 15@2x](https://github.com/user-attachments/assets/e91be35c-ea7b-4921-99e7-a5e73dcc62ea)

**Comment by szmarczak** [comment]
> We discussed it as a team before @agottardo replied.

Woah, that was unexpectedly fast! Thanks a lot!

> we might explore alternatives in the future (see image below)

This looks great! Thanks to you all, you're the best :)

I can't wait to see this live.
