### ISSUE TITLE
云服务器上的tailscale只能安装full版本，点击login不弹窗

### ISSUE THREAD

**Issue by liujc196** [tailscale/tailscale#13387]
### What is the issue?

为什么我的tailscale只能安装full版本，还无法login，就连查看个about，还和我本机不一样，显示不了最新版本信息。
![117](https://github.com/user-attachments/assets/dcb0f27a-99f5-496b-b95c-1b547897294c)
![112](https://github.com/user-attachments/assets/464b7a4a-798d-482c-871f-adeb0fed3a09)
![1112](https://github.com/user-attachments/assets/83cc3528-2b45-4c94-b9db-7a9d468d6fd1)

### OS

Windows

### OS version

win10

**Comment by bradfitz** [comment]
The "Latest stable version" information is retrieved from the network. Perhaps those network checks are being blocked.

Given that this GitHub issue is written in Chinese, are you perhaps in China? Perhaps the Great Firewall of China is blocking the request?

Without a Bug Report identifier, there's not much we can look at to debug further.

**Comment by cqmiao** [comment]
chrome version is Portable，so the tailscale app can't calling it. I changed the default browser in win10 to the built-in IE.This will fix the problem.
