### ISSUE TITLE
Failed to install on windows

### ISSUE THREAD

**Issue by a15355447898a** [tailscale/tailscale#13384]
### What is the issue?

When I am installing tailscale, it prompts that it cannot be installed

![image](https://github.com/user-attachments/assets/792d8776-6c92-4e12-a096-0e7a027337a5)

[Tailscale_20240906000035.log](https://github.com/user-attachments/files/16897276/Tailscale_20240906000035.log)
[Tailscale_20240906000035_000_MsiAMD64.log](https://github.com/user-attachments/files/16897277/Tailscale_20240906000035_000_MsiAMD64.log)

One of the lines in the log is:
```
Custom Action CheckServiceDependencies (PID 0x3DB4 (15796)) [23:45:43.734]: Error: Obtaining Config for "iphlpsvc": The system cannot find the file specified.
```

But I'm sure the service is working.

![image](https://github.com/user-attachments/assets/8f12d662-6c5b-4781-b0c6-629a62298985)

### OS

Windows

### OS version

win11

### Tailscale version

1.72.0

**Comment by bradfitz** [comment]
What specific version of Windows are you using? Is it a legal, unmodified version? Did you explicitly disable or delete `iphlpsvc`?

**Comment by a15355447898a** [comment]
> What specific version of Windows are you using? Is it a legal, unmodified version? Did you explicitly disable or delete `iphlpsvc`?

I am using the official Microsoft windows 11 23h2

![image](https://github.com/user-attachments/assets/35b23398-8a34-4303-8606-ac7222b86ccc)

I think `iphlpsvc` is running.

![image](https://github.com/user-attachments/assets/c2e7e78b-1cbe-439e-962e-d7202cc517ea)

**Comment by a15355447898a** [comment]
I figured out the cause and solution and am putting it here to help others who come after me

https://www.bilibili.com/read/cv28774573/
