### ISSUE TITLE
wgengine/router: Windows machines without IPv6 fail to start if other node is sharing default route

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1339]
A user with 1.4.4 on Windows was hitting this error path:

```go
        var routes []winipcfg.RouteData
        foundDefault4 := false
        foundDefault6 := false
        for _, route := range cfg.Routes {
                if (route.IP.Is4() && firstGateway4 == nil) || (route.IP.Is6() && firstGateway6 == nil) {
                        return errors.New("Due to a Windows limitation, one cannot have interface routes without an interface address")
                }
```

Turns out their Windows machine didn't have IPv6 enabled and a Debian machine on their network was exporting a default route (including IPv6 `::/0`), which then caused the Windows client to say "oh, I can't do v6 routes, I fail now" before doing any other work.

Blocker for IPv6 + default routes.

/cc @danderson 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2sfkh)

**Comment by bradfitz** [comment]
@danderson, I think this was fixed?

**Comment by danderson** [comment]
Wasn't, but is now.
