### ISSUE TITLE
Using 'Block connections without VPN' Function on Android Prevents Local Device Access

### ISSUE THREAD

**Issue by jimmybrancaccio** [tailscale/tailscale#13407]
### What is the issue?

When connecting from an Android device to an exit node that is on the same local network, and having Allow LAN access toggled on and Block connections without VPN toggled on, I can no longer access devices on my local LAN. It looks like it could be related to [12220](https://github.com/tailscale/tailscale/issues/12220) but this seems limited to DNS.

### Steps to reproduce

This requires an Android device and exit node to be connected to the same local network.

1. Make sure Android device is connected to WiFi and internet.
2. Connect Android device to tailnet.
3. Connect Android device to exit node, ensure allow lan access is toggled on.
4. In a terminal or something see if you can ping another local device by its local IP or try to SSH into it via local IP. This should work.
5 On Android device, go to Settings > Connections > More connection settings > VPN, tap the cog/gear icon next to Tailscale, toggle on the Always on VPN and Block connections without VPN.
6. Back in Terminal or SSH app, try to ping or SSH to the local IP of the device that previously worked. This fails.

### Are there any recent changes that introduced the issue?

I am not aware of any.

### OS

Android

### OS version

Android 14

### Tailscale version

Tailscale 1.72.1

### Other software

None that I can think of would cause this issue. I have a mostly stock Android install on my phone.

### Bug report

BUG-e571249de9d900e9e983433bb5ee8ef81bff06415cf1f59e0fc76e25cc6c44dd-20240825214459Z-ab0028cc83f9fc90

**Comment by kari-ts** [comment]
This is WAI: if you're using an exit node, LAN traffic becomes inaccessible because all network traffic, including LAN traffic, is routed through the exit node instead of being handled locally. "Allow LAN access" makes an exception for LAN traffic, ensuring that local devices remain accessible. However, if you toggle "block connections without VPN," it overrides this setting and forces all traffic through the VPN.
