### ISSUE TITLE
FR: Make app connectors optional/opt-out

### ISSUE THREAD

**Issue by ishmam-mahmud** [tailscale/tailscale#13401]
### What are you trying to do?

We created an app connector for GitHub so that we can restrict the egress IPs that our customers on GitHub see. This allows our GitHub app to advertise specific IPs, regardless of the fact that we have a macroservice architecture with deployments in many places. All those deployments are in our tailnet and all *.github.com traffic ends up going through the app connector.

However, this also affects all our employees too when they are connected to the same tailnet. As github is a public SaaS also accessible through the public internet, we were wondering if it's possible to create an optional variant of app connector where if a particular tailnet machine is not allowed to connect to the connector machines through ACLs, they can still connect to github.com through the public internet.

Right now, if we use ACLs to restrict access to the app connector machines for any reason, see something like
```
{
  "action": "accept",
  "src": [
    "*",
   ],
  "dst": [
    "tag:github:*",
  ],
},
```

Then replace the `*` in `src` with `autogroup:admin`, all of our users with role member lose access to github.

### How should we solve this?

Maybe it could just be a boolean in app connector settings when you create an app connector, or perhaps it could be done in the `nodeAttrs` section of the policy file with something like this
```
{
  "target": [
    "*",
   ],
   "app": {
      "tailscale.com/app-connectors": [
        {
	  "name": "github",
	  "connectors": [
	    "tag:github",
          ],
	  "presetAppID": "github",
	},
    ],
  },
}
```
where the `*` in `target` is replaced with an array of the devices that's affected by the app connector. This would enable us to make an app connector only impact traffic originating from specific devices.

### What is the impact of not solving this?

Not much really.
So far we just ensure `*` has access to `tag:github:*` in the acls to avoid this, as we don't have a use case yet for restricting the origin of traffic. We are still only using app connectors only to restrict the egress IP up to now. This is a nice-to-have.

**Comment by clstokes** [comment]
@ishmam-mahmud you can do this today with [route filtering with via](https://tailscale.com/kb/1378/via). That page includes an [example using app connectors at the bottom](https://tailscale.com/kb/1378/via#route-users-through-app-connectors). If I missed part of your question or this does not fully address your need, please feel free to re-open the issue with additional detail.
