### ISSUE TITLE
FR: Mullvad selection UI on Windows could be better?

### ISSUE THREAD

**Issue by Crypss22** [tailscale/tailscale#13413]
### What are you trying to do?

When manually selecting a Mullvad VPN server on a Windows machine, the length of the list takes up the entire screen and to scroll down to the US servers is very time-consuming (considering the amount of servers Mullvad has) and not efficient. 

### How should we solve this?

I think a better UI when selecting one of Mullvad's VPN servers could solve this issue or implement some type of way you can scroll the list because currently it's not an option.

### What is the impact of not solving this?

Not necessarily a major impact, but would just be a smoother experience for the end-user when changing VPN servers.

### Anything else?

I'm a big fan of Tailscale and love everything you guys are doing!

**Comment by bradfitz** [comment]
They're not grouped by country for you? Can you include a screenshot of what you see?

What version are you running?

**Comment by Crypss22** [comment]
Hey! I'm on version 1.72.0 and they're not grouped by country for me. I've included a screenshot, thanks!
![Screenshot 2024-09-07 194220](https://github.com/user-attachments/assets/1d13f68b-ee92-4238-9bed-03ecb830f6c3)

**Comment by bradfitz** [comment]
Cc @dblohm7 @nickkhyl

**Comment by dblohm7** [comment]
https://github.com/tailscale/corp/issues/21973

Mostly fixed in unstable. I've got one more cleanup PR.
