### ISSUE TITLE
tailscale netcheck: nil pointer when there are no DERP responses

### ISSUE THREAD

**Issue by Sc-Eric-B** [tailscale/tailscale#13429]
### What is the issue?

tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 120.229.144.251:5004
        * IPv6: no, but OS has support
        * MappingVariesByDestIP:
        * PortMapping:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x665eb1]

goroutine 1 [running]:
tailscale.com/cmd/tailscale/cli.printReport(0xc000008078, 0xc0001c2d00)
        tailscale.com@v1.68.1/cmd/tailscale/cli/netcheck.go:157 +0x4f1
tailscale.com/cmd/tailscale/cli.runNetcheck({0x8b78e0, 0xcca280}, {0x64?, 0x64?, 0xc00009c820?})
        tailscale.com@v1.68.1/cmd/tailscale/cli/netcheck.go:97 +0x5a5
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc00008d730?, {0x8b78e0?, 0xcca280?})
        github.com/peterbourgon/ff/v3@v3.4.0/ffcli/command.go:153 +0x15a
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0x7a5511?, {0x8b78e0?, 0xcca280?})
        github.com/peterbourgon/ff/v3@v3.4.0/ffcli/command.go:157 +0x106
tailscale.com/cmd/tailscale/cli.Run({0xc0000983b0?, 0x17701d?, 0x0?})
        tailscale.com@v1.68.1/cmd/tailscale/cli/cli.go:144 +0x310
main.main()
        tailscale.com@v1.68.1/cmd/tailscale/tailscale.go:22 +0xfd

### Steps to reproduce

No response

### Are there any recent changes that introduced the issue?

No response

### OS

Linux

### OS version

ubuntu_22_04

### Tailscale version

v1.73.0-pre.0.20240910014213-a228d77f8620

### Other software

No response

### Bug report

No response

**Comment by bradfitz** [comment]
I think this was already fixed (dup of #12661). Upgrade and try again?
