### ISSUE TITLE
Doubts about setting up a self-hosted derper.

### ISSUE THREAD

**Issue by firekirin67** [tailscale/tailscale#13424]
### What is the issue?

When I set up a self-hosted derper service and start it with the following command:
```
./derper -hostname=1.1.1.1
```
I encounter the following message:
```
2024/09/10 14:54:15 http: TLS handshake error from 113.87.130.38:56621: acme/autocert: host "****.******.com" not configured in HostWhitelist
```
Where does this domain information come from?

### OS

Linux

### OS version

Ubuntu22.04

**Comment by agottardo** [comment]
What is `"****.******.com" and what IP is `113.87.130.38`?

**Comment by bradfitz** [comment]
ETIMEOUT.

But this just looks like normal Internet noise that happens when you run a service open to the Internet. Lots of junk connects to it.
