### ISSUE TITLE
FR: ACL notifications

### ISSUE THREAD

**Issue by jonathan-wondereur** [tailscale/tailscale#13438]
### What are you trying to do?

I would like to know when any change is made to my ACL.

When using Gitops I have a history of all changes made to my ACL file. However there is the option to update the ACL file directly, this is okay, but I would like to know somehow when this has happened and ideally know what was changed.

### How should we solve this?

Send a notification when the ACL file is changed directly when Gitops is enabled, or submit a pull request to my Git repo.

### What is the impact of not solving this?

Not being able to depend on the history of Gitops to know the status of the ACL at any time.

**Comment by agottardo** [comment]
The existing webhooks should already support this if you subscribe to the policyUpdate event (https://tailscale.com/kb/1213/webhooks#events). Did we miss anything there?

**Comment by jonathan-wondereur** [comment]
Wow, I didn't know this was already here. Tailscale is awesome!
