### ISSUE TITLE
interfaces: route.FetchRIB: sysctl: cannot allocate memory (darwin)

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1345]
On macOS tailscaled mode, sometimes (but not always!?), I see:

```
netns: DefaultRouteInterfaceIndex: route.FetchRIB: sysctl: cannot allocate memory
```

Investigate.

**Comment by mkramlich** [comment]
I've started seen those too, during my brew candidate testing of recent main. just noted, not dug in

**Comment by bradfitz** [comment]
I still see this sometimes.

https://lists.freebsd.org/pipermail/freebsd-current/2014-February/048416.html says:

>  I think the cause is just a race when length of the sysctl's output
> is changed in kernel after the buffer allocation in userspace, not
> memory shortage.  Size of the routing table can quickly change.

So maybe a retry loop on our side would help.

**Comment by bradfitz** [comment]
Somewhat confirmed:

If I run this in a loop and toggle my wifi on & off, I hit it:

```
crow5k:tailscale.com $ while go test -count=500 -failfast ./net/interfaces/; do echo -n; done
2021/04/23 13:06:11 routerIP/FetchRIB: sysctl: cannot allocate memory
--- FAIL: TestLikelyHomeRouterIPSyscallExec (0.01s)
    interfaces_darwin_test.go:22: syscall() = invalid IP, false, netstat = 10.0.0.1, true
FAIL
FAIL    tailscale.com/net/interfaces    1.031s
```

**Comment by bradfitz** [comment]
Filed https://github.com/golang/go/issues/45736 in Go to add the loop there.

But will do the retry loop in our tree meanwhile.
