### ISSUE TITLE
FR: k8s-operator make connections as ephemeral nodes

### ISSUE THREAD

**Issue by eadwu** [tailscale/tailscale#13453]
### What are you trying to do?

`k8s-operator` manages connections and disconnections of the services/pods but since the connections are not ephemeral unclean shutdowns are left behind to be manually deleted.

### How should we solve this?

Not sure how it works internally but maybe adding option for `Ephemeral nodes` for OAuth as well and as Helm option.

### What is the impact of not solving this?

Manually deleted 10 services.

Otherwise impact doesn't really exist since for now I can just let it stack up offline nodes till > 100, though cleanup will be annoying.

**Comment by eadwu** [comment]
Or just run `kubectl drain ...`

**Comment by irbekrm** [comment]
Hi @eadwu I don't really understand what you mean.

Do you mean that there are tailscale nodes left behind? The operator does delete devices as Kubernetes Services are deleted, so that should not be the case?
Could you give a reproducible example?

**Comment by eadwu** [comment]
The simplest example is just running the tailscale-operator
```
helm upgrade \
  --install \
  tailscale-operator \
  tailscale/tailscale-operator \
  --namespace=tailscale \
  --create-namespace \
  --set-string oauth.clientId=<OAauth client ID> \
  --set-string oauth.clientSecret=<OAuth client secret> \
  --wait
```

which creates a `tailscale-operator` connection in Tailscale

The following commands all don't remove it from the list (which is also the case for more Services)
- `kubectl drain "$(hostname)" --ignore-daemonsets --delete-emptydir-data --force`
- `helm uninstall tailscale-operator`
- `shutdown now`

I've only seen the operator disconnect nodes when the operator itself is still online after the operation - while the above commands mostly are for bringing it down.

**Comment by eadwu** [comment]
Being able to mark them as ephemeral nodes allows them to automatically cleaned up (for my use case) and I think it probably should at least be exposed since you guys also allow it if somebody didn't use the k8s-operator and instead used the auth keys. 

My environment is spinning up k8s clusters that join and drop abruptly.

**Comment by eadwu** [comment]
https://github.com/tailscale/tailscale/issues/10166
