### ISSUE TITLE
Package for QNAP

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1346]
Tailscale packages for QNAP exist: https://github.com/ivokub/tailscale-qpkg

... but they're stuck at 0.97.

As part of packaging Tailscale for everything, we should investigate doing automated builds for QNAP, so users stop install 0.97.

Looks like with QuTScloud you can run QTS (the QNAP Linux OS userspace) on a cloud instance, which would ease development for me, as I don't have QNAP hardware:

* https://www.qnap.com/solution/qutscloud-hypervisor/en-us/
* https://software.qnap.com/qutscloud.html
* https://www.qnap.com/en/how-to/tutorial/article/how-to-deploy-and-install-qutscloud-on-vm-platforms/

**Comment by DentonGentry** [comment]
https://www.qnap.com/en-us/live-demo can also start up a demo QTS VM (for free), however I don't find a way to get it to be helpful for this. It is on an isolated subnet without a way to reach it via ssh.

**Comment by bradfitz** [comment]
I now have two QNAP NAS models for testing, an ARM and an x86 one.

Just installed the TS-230 ARM one. Firmware 2.5.2.1630.

tun seems available, even without installing the QVPN package as https://github.com/ivokub/tailscale-qpkg#installation says is a prereq. (Maybe that's old?)

```
[~] # uname -a
Linux qnap230arm 4.2.8 #1 SMP Tue Apr 6 01:56:11 CST 2021 aarch64 GNU/Linux
[~] # lsmod | grep tun
[~] # modprobe tun
[~] # lsmod | grep tun
tun                    21396  0 
```

**Comment by ivokub** [comment]
Hi, I am author of the QNAP package of Tailscale. I have updated the package to point to recent(-ish) version of Tailscale, but I haven't still had possibility to automate the releases yet.

Is there anything I could contribute? It would be nice to have Tailscale as an official package in QTS App Center with automatic updates. There is also unofficial qnapclub repository, which isn't completely transparent.

**Comment by GoetzGoerisch** [comment]
As mentioned here: https://github.com/ivokub/tailscale-qpkg/issues/22#issuecomment-970676303

QVPN is not required for QTS 5.0.0. 

Would love to have a working qpkg for tailscale from you?

**Comment by bradfitz** [comment]
@ivokub, sorry, looks like nobody replied to you earlier.

We still have our 3 QNAP devices for our little QNAP test lab, but we haven't gotten around to automating the build yet. It's still on our list. We're still working on things like the web admin panel UI (`tailscale web`) for Synology which we'll also use for QNAP and other such platforms.

Does QTS let people install alternate app feeds so they can add some Tailscale XML/etc feed once and then stay updated through our packages distributed via pkgs.tailscale.com? But, yes, getting in the official store would also be nice, especially if they let us updated it on our own schedule. (One thing that's slightly painful about Synology is we're not in control of the release cycle, so if there are bugs, we hear from users about the same bugs for months before Synology updates their store to a newer version with the fix done months ago)

**Comment by ivokub** [comment]
> Does QTS let people install alternate app feeds so they can add some Tailscale XML/etc feed once and then stay updated through our packages distributed via pkgs.tailscale.com? But, yes, getting in the official store would also be nice, especially if they let us updated it on our own schedule. (One thing that's slightly painful about Synology is we're not in control of the release cycle, so if there are bugs, we hear from users about the same bugs for months before Synology updates their store to a newer version with the fix done months ago)

Yes, it should be possible. I think the most popular store is [QNAPClub](https://www.qnapclub.eu/en) (with feed at https://www.qnapclub.eu/en/repo.xml).

**Comment by GoetzGoerisch** [comment]
@bradfitz please be aware that there is already a community tailscale qpkg: https://www.qnapclub.eu/en/qpkg/1162

**Comment by GoetzGoerisch** [comment]
@bradfitz @maisem anything I could assist? Would love to see this in the QNAP repo soon.

**Comment by dragon2611** [comment]
> @bradfitz please be aware that there is already a community tailscale qpkg: https://www.qnapclub.eu/en/qpkg/1162

Sadly a fairly old version, but it does have the advantage that you can move it to another volume (Which you might want to do if your system vol is encrypted and doesn't auto unlock, otherwise it won't auto start on a nas reboot)

**Comment by TonyAble** [comment]
So will tailscale for QNAP get an official package like Synology?

**Comment by DentonGentry** [comment]
Should have mentioned this issue in a few recent pull requests:
- https://github.com/tailscale/tailscale/pull/5071
- https://github.com/tailscale/tailscale/pull/5073
- https://github.com/tailscale/tailscale/pull/5163

**Comment by DentonGentry** [comment]
> Hi, I am author of the QNAP package of Tailscale. I have updated the package to point to recent(-ish) version of Tailscale, but I haven't still had possibility to automate the releases yet.

@ivokub I'd like to talk about how we might proceed, we've done some work in a fork of your repository. If you could email dgentry at tailscale.com we can discuss it.

**Comment by DentonGentry** [comment]
Since the last update:
- ivokub graciously transferred the https://github.com/tailscale/tailscale-qpkg repository
- a GUI login has been added
- Tailscale is working with QNAP to get into the QTS App Center

**Comment by groenator** [comment]
How can I accept routes when I use the console?

**Comment by DentonGentry** [comment]
Tailscale package appeared in the QNAP App Center on July 31: https://tailscale.com/kb/1273/qnap/

**Comment by LoshtaAudrino** [comment]
Ok I am a n00b, which one of the packages is suitable for QNAP TS230?!

**Comment by gecastro** [comment]
> Ok I am a n00b, which one of the packages is suitable for QNAP TS230?!

I have similar question. I have a QNAP TS230 and I don't see the app in the AppCenter, is it possible to install tailscale manually?

**Comment by gecastro** [comment]
> Ok I am a n00b, which one of the packages is suitable for QNAP TS230?!

I also have the TS230 and I couldn't find the app in the AppCenter, I was able to install it from https://www.myqnap.org/ since qnapclub seems to be dead now.
