### ISSUE TITLE
Windows "Tailscale" service keeps running even after exiting the application from tray icon

### ISSUE THREAD

**Issue by AdamJel** [tailscale/tailscale#13479]
### What is the issue?

When user decides to close/exit the Tailscale application and does so by clicking `exit` from tray icon menu:

![image](https://github.com/user-attachments/assets/11479ab8-bbad-4e54-ab16-d20f2a83edd5)

The "Tailscale" Windows service should be stopped as well. But it keeps running.

### Steps to reproduce

Exit the application from Windows tray icon menu.

### OS

Windows

### OS version

Windows 11; 23H2; 22635.4145

### Tailscale version

1.74.0

**Comment by dblohm7** [comment]
This is by design. The `tailscaled` service remains running but disconnected from the tailnet when the GUI either not running or disconnected.
