### ISSUE TITLE
Does not support automatic startup in the background after Windows 11 system restart

### ISSUE THREAD

**Issue by ukhack** [tailscale/tailscale#13478]
### What is the issue?

After each restart of the window, I have to use other internal network penetration services to remotely access the desktop to the server. After completing the "login to the desktop" operation, Tailscale can complete the startup

### Steps to reproduce

reboot windows
not login

### OS

Windows

### OS version

11 23h2

### Tailscale version

1.72

**Comment by dblohm7** [comment]
You'll probably want to use [unattended mode](https://tailscale.com/kb/1088/run-unattended).
