### ISSUE TITLE
Mullvad exit nodes no longer appearing in app

### ISSUE THREAD

**Issue by trijste** [tailscale/tailscale#13472]
### What is the issue?

I'm unable to access Mullvad exit nodes. The setting is enabled and configured for each device (Mac, iPad). Option not appearing in menu as it has in the past.

<img width="283" alt="image" src="https://github.com/user-attachments/assets/80de5eff-6ce9-4a6f-bfeb-02d95662d313">

<img width="358" alt="image" src="https://github.com/user-attachments/assets/a1a77924-ab15-42f8-a665-959e2535edfd">

### OS

macOS

### OS version

macOS 14.6.1 (23G93)

### Tailscale version

1.75.3

### Bug report

BUG-35f8dc83fbedddb70325e0f67a7353c64569a652c340ea39b2f7dcb820876854-20240914163052Z-bbb685c99422ddaa

**Comment by MrNoooobie** [comment]
Exact same thing happened to me.

Funny thing is I was configuring an exit node last night and I had thought that I put in the wrong command somewhere. 

Seems like the recent update broke something.

**Comment by Takordy** [comment]
I had the same issue but in linux mint 22, tailscale does not show a list of mullvad exit-nodes in terminal, but my pc and phone are configured and are added to mullvad vpn list in tailscale admin console. Now i have 1.74.0 version, i have tried to install previous version of tailscale which is 1.72.1, but i had the same issues with exit-nodes :(
![Screenshot from 2024-09-14 23-26-35](https://github.com/user-attachments/assets/e09e48ce-ceed-42c1-a75d-ddd8e898b741)

**Comment by BadDownload** [comment]
I'm experiencing the same on a Windows 11 device today. "No exit node available" displays where I would expect to find the Mullvad option.

OS: Windows 11 (22631.4037)

Tailscale version: 1.74.0 (t28e0bab29-gbfc27063c)

Bug report: BUG-efad30ec321858d5620e6670d5e806f9a336db56d1a30662fcfba29079ebc104-20240914222037Z-d3590f8e689d0a4a

**Comment by DigitalKodama** [comment]
I'm also experiencing this, on multiple versions of Tailscale on Arch, iPhone, and Android. The version doesn't seem to meaningfully affect the exit node list.

**Comment by N3MO11977** [comment]
It is happening on my AppleTV (latest model, tvos and app are up to date): mullvad exit nodes disappeared.

**Comment by kylejoiner** [comment]
Same here.  iOS, Android, Windows and Linux.

**Comment by jpalcantara** [comment]
Same here!

**Comment by ShrimpyChips** [comment]
Experiencing this too, on a new Android tablet that I just setup. My phone (android also) is however still able to connect to Mullvad. On the tablet it asks me to enable in the admin console which I have reenabled for the device multiple times and reboot the tablet multiple times to no avail.

**Comment by adamfeldman** [comment]
This affected me on the macOS App Store and Standalone apps, v1.74.0

**Comment by timtailscale** [comment]
We are currently investigating this, and will post an update once we have more to share. You can follow along on our status page here: https://status.tailscale.com/.

**Comment by timtailscale** [comment]
We expect this to be resolved now, and will update the status page accordingly. If you are still having issues with seeing Mullvad exit nodes, please let us know!

**Comment by trijste** [comment]
I can confirm they have reappeared for me. Thank you to everyone who confirmed the issue and to the team responsible for fixing it and maintaining this excellent software.

**Comment by FloatingLizard** [comment]
All working!  Thank you

**Comment by FloatingLizard** [comment]
Windows does not work.  All the other device are working.
