### ISSUE TITLE
App doesnt work if proton vpm is enabled.

### ISSUE THREAD

**Issue by HrudayRudraraju** [tailscale/tailscale#13489]
### What is the issue?

The android app is unable to sign in if the proton vpn app is either installed or set to a kill switch.

### Steps to reproduce

Install proton vpn and set the app to the kill switch feature.
try to login to the tailscale app
no login option provided.

### OS

Android

### OS version

14

### Tailscale version

1.72.0 on playstore

### Other software

proton vpn

**Comment by agottardo** [comment]
Only one VPN app can be used at the same time on Android. It sounds like the ProtonVPN kill-switch is working properly in this case? I don't think we should be able to toggle the settings of another app, and I don't think that'd be a desirable thing for us to do either. Please let me know if I'm misunderstanding the problem. Thanks.

**Comment by HrudayRudraraju** [comment]
Yup that makes sense. I made the ticket more so to update the documentation for apps that don't work together. Since I spent a lot of time trying to figure out why I couldn't log in. If any error message could be added or if this could be updated incase anyone else gets stuck on that step that would be great!. https://tailscale.com/kb/1023/troubleshooting#interoperability-with-other-software

**Comment by agottardo** [comment]
@HrudayRudraraju that's a good call, thank you for the feedback. We avoided including commercial, personal-usage VPNs like Proton in that list, otherwise we would need to add hundreds of different services there, but we can probably make an exception for Proton.
