### ISSUE TITLE
Unable to deselect exit-node

### ISSUE THREAD

**Issue by Rumbles** [tailscale/tailscale#13506]
### What is the issue?

When using tailscale 1.74.0 on MacOS, I am unable to deselect my exit node, previously (1.70.0) I was able to turn it off and on in the UI and using the cli, now selecting "none" in the UI or `tailscale set --exit-node ""` results in no change in my exit node config, it is always on

### Are there any recent changes that introduced the issue?

Updated to 1.74.0 (I also updated my MacOS around the same time)

### OS

macOS

### OS version

Sonoma 14.7

### Tailscale version

1.74.0

### Bug report

BUG-2e61c7d6946eb60376bdf0de9d9fe315886a1efb52d9cbbac06cb0a79c9f0c35-20240918152612Z-8f1571ab7ba0a05a

**Comment by agottardo** [comment]
Did you reboot your Mac since updating? I'm wondering if your GUI got updated, but the backend didn't.

**Comment by Rumbles** [comment]
I just tested @agottardo , it does not change the behaviour after power cycling. I have also noticed that the app no longer starts on launch, and when I try to tick the option in settings, it unticks itself (other options seem to work still, it's just it won't let me select start on launch any more). 

Something seems to be a bit broken

**Comment by fernandomora** [comment]
Some members of my team and me are having the same problem deselecting exit node with 1.74.0

**Comment by Rumbles** [comment]
This is an MDM issue, not a tailscale issue, sorry

**Comment by agottardo** [comment]
@Rumbles if able, can you share steps you took to solve the problem for posterity? Thanks.

**Comment by Rumbles** [comment]
The MDM admin had set a control policy that forced all users to use an exit node, reverting that fixed the issue
