### ISSUE TITLE
unable to select exit node in windows

### ISSUE THREAD

**Issue by abuschel** [tailscale/tailscale#13526]
### What is the issue?

I have a laptop running windows 11, tailscale version 1.74.0 . My exit node choice is none. I want to change to an existing exit node, via the tray menu, but it does not work. My machine is running as an exit node as well. When I try to set the exit node via the cli, the error is clear, not so via the tray UI.

### OS

Windows

### OS version

11

### Tailscale version

1.74.0

**Comment by kelivel** [comment]
We'll be making changes to the exit node menu in a future update that will make this restriction a little more apparent in the UI. In the meantime, keep an eye on progress at https://github.com/tailscale/tailscale/issues/12771. Closing as duplicate.
