### ISSUE TITLE
Tailnet Lock - My nodes are all suddenly locked out ?

### ISSUE THREAD

**Issue by R-Nabil** [tailscale/tailscale#13539]
Hi,

I've been trialling Tailnet Lock and it worked well until suddenly yesterday all my nodes were locked out of the node. Is that a desired feature or a bug ?

I was able to re-authorise them so it's not a catastrophic issue.

Thanks.

**Comment by raeraex2** [comment]
Same issue. I reauthorized them, but they were locked out again after a few hours.

**Comment by alexraskin** [comment]
Having the same issue, signed a new node last night, and it was locked out this afternoon.

**Comment by udf2457** [comment]
I think perhaps someone needs to close this issue and point everyone to #13541 ?

**Comment by R-Nabil** [comment]
> I think perhaps someone needs to close this issue and point everyone to #13541 ?

Done
