### ISSUE TITLE
tailscale up --help show wrong params

### ISSUE THREAD

**Issue by lfarkas** [tailscale/tailscale#1353]
`tailscale up --help`
show all flags started with "-" while all of them use double "-" ie. "--". it sould have to fixed. 
on the other hand
`tailscaled --help`
also show single dash but i don't know is it right or bad.

last but not least docs never shows whether use 
`--accept-dns true`
or
`-accept-dns=true`
or both are good.

**Comment by bradfitz** [comment]
Both styles work the same way.

**Comment by lfarkas** [comment]
> Both styles work the same way.

you mean the last case, but what about the double dash?

**Comment by bradfitz** [comment]
`--foo` and `-foo` are the same.

**Comment by bradfitz** [comment]
and for booleans, `--foo` means `--foo=true`, so `--foo true` or `--foo false` both mean `--foo=true` followed by an argument "false" or "true".

**Comment by lfarkas** [comment]
nice that different docs use different format:-(
