### ISSUE TITLE
Tailscale Relay Server Unavailable - Macos

### ISSUE THREAD

**Issue by ekadic7** [tailscale/tailscale#13530]
### What is the issue?

<img width="494" alt="Screenshot 2024-09-20 at 12 08 04" src="https://github.com/user-attachments/assets/5ad09bb5-9851-4d5b-b03d-9fc2cad86953">

### OS

macOS

### OS version

15.1 Beta (24B5046f)

### Tailscale version

1.75.15

### Bug report

BUG-5bd6975a8ad58c1f5ffc677055f26fda93135beb4e8f0c7370a22173ecc8c2bc-20240920112500Z-b618e0cfe04943fa

**Comment by Maronato** [comment]
Related/duplicate #13265

**Comment by agottardo** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/13265
