### ISSUE TITLE
flag provided but not defined: -minimum-validity (tailscale cert)

### ISSUE THREAD

**Issue by aesth-real** [tailscale/tailscale#13534]
### What is the issue?

I tried using common fixes like checking an equals to sign made sure to check the format of time is correct as given in the documentation, no matter what i do i cant seem to define the duration with this tag 

### Steps to reproduce

run this command as root :tailscale cert --cert-file=cert.pem --key-file=domain.key --minimum-validity=120h domain

### Are there any recent changes that introduced the issue?

Not sure

### OS

Linux

### OS version

archlinux 2024.09.01

### Tailscale version

1.74.1

```[tasklist]
### Tasks
```

**Comment by icio** [comment]
Hi @aesth-real, the flag is `-min-validity`. You can see what flags are available for a command by checking `tailscale cert --help`. In this case:

```
$ tailscale cert --help
Get TLS certs

USAGE
  tailscale cert [flags] <domain>

FLAGS
  --cert-file string
        output cert file or "-" for stdout; defaults to DOMAIN.crt if --cert-file and --key-file are both unset
  --key-file string
        output key file or "-" for stdout; defaults to DOMAIN.key if --cert-file and --key-file are both unset
  --min-validity duration
        ensure the certificate is valid for at least this duration; the output certificate is never expired if this flag is unset or 0, but the lifetime may vary; the maximum allowed min-validity depends on the CA (default 0s)
  --serve-demo, --serve-demo=false
        if true, serve on port :443 using the cert as a demo, instead of writing out the files to disk (default false)
```

**Comment by bradfitz** [comment]
I feared that maybe our docs were wrong and said "minimum-validity" somewhere (instead of "min") but I can't find anything, so I'm going to close this.

But @aesth-real, let us know if there's something misleading somewhere documentation wise.
