### ISSUE TITLE
Unable to login on macOS 15.0 Sequoia

### ISSUE THREAD

**Issue by BuckarooToo** [tailscale/tailscale#13547]
### What is the issue?

When attempting to login, a browser window does not open
I receive the following error: "Error: fetch control key: Get "https://controlplane.tailscale.com/key?v=106": context canceled

### Steps to reproduce

Attempt to log in

### Are there any recent changes that introduced the issue?

MacOS 15.0

### OS

macOS

### OS version

15.0

### Tailscale version

1.74.0

**Comment by agottardo** [comment]
This is not an issue specific to Sequoia, as Tailscale already supports it. Please attach a bug report identifier.

**Comment by raggi** [comment]
Ensure that tailscale is allowed in your firewall settings - Sequoia has been blocking apps that were previously allowed for a lot of users.

**Comment by agottardo** [comment]
Closing due to lack of info.

**Comment by theMackabu** [comment]
<img width="612" alt="Screenshot 2024-10-11 at 2 24 08 PM" src="https://github.com/user-attachments/assets/e5a29f27-ce0c-48cf-9f73-4323318891
<img width="1184" alt="Screenshot 2024-10-11 at 2 24 33 PM" src="https://github.com/user-attachments/assets/682acc14-6870-4037-b28c-42ac4b2a193b">
ed">

having the same exact issue, any logs that I could provide?

**Comment by theMackabu** [comment]
tailscale bugreport output
```
Recording started; please reproduce your issue and then press Enter...

BUG-2771e8107696381ca62d5eef72ee1b1940d1525085478efdc877b17909fdceb0-20241011220316Z-9a5be5981a6ac2de
BUG-2771e8107696381ca62d5eef72ee1b1940d1525085478efdc877b17909fdceb0-20241011220327Z-9367a72a6adfd79c

Please provide both bugreport markers above to the support team or GitHub issue.
```
