### ISSUE TITLE
Add ability to specify network interface

### ISSUE THREAD

**Issue by brodyhoskins** [tailscale/tailscale#13545]
### What are you trying to do?

I’m trying to run multiple Tailscale (exit) nodes on the same machine. I’ve tried it both at the host level and using Docker but it doesn’t work because Tailscale always expects the network interface to be `/dev/tailscale0`.

### How should we solve this?

Add the ability to specify a network interface name to use (like `/dev/tailscale1`).

### What is the impact of not solving this?

I have to run multiple VPS instances to support multiple exit nodes rather than running one with multiple Tailscale instances (with separate network interfaces).

**Comment by raggi** [comment]
`tailscaled -tun tailscale3` is already available. You will also need to pass a new `state` path and `-socket` path to avoid collisions with those as well.

**Comment by brodyhoskins** [comment]
Ah shucks, just when I migrated everything back to two VPSes. I didn’t look hard enough for documentation apparently. Appreciate it!
