### ISSUE TITLE
derper behind nginx proxy manager 

### ISSUE THREAD

**Issue by cz19860416** [tailscale/tailscale#13568]
### What is the issue?

Hi all,
      I used niginx proxy manager for a while.
      This time, what I did is to let NPM to proxy the http port of derper, e.g. 8088.
      On the subdomain site, https://derper.XXX.com:12345, I can see, the server is worked.
      But, When I double check the network condition, by using command: tailscale status, got a report of "not connected to home DERP region XXX".
      Also, I check the tailscale netcheck, I can get the information of the region XXX.
Report:
        * UDP: true
        * IPv4: yes, xxx.xxx.xxx.xxx:14644
        * IPv6: yes, [xxxxxxxxxxxxxxxxxxxxxxx]:43377
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping: UPnP
        * CaptivePortal: false
        * Nearest DERP: home server
        * DERP latency:
                                .......

Thank you very much.

### Steps to reproduce

name: fervent_emily
services:
  derper:
    cpu_shares: 90
    command: []
    container_name: derper
    deploy:
      resources:
        limits:
          memory: 3800M
    environment:
      - DERP_ADDR=:80
    image: fredliang/derper
    ports:
      - target: 80
        published: "8088"
        protocol: tcp
      - target: 3478
        published: "3478"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/tailscale/tailscaled.sock
        target: /var/run/tailscale/tailscaled.sock
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
networks:
  default:
    name: fervent_emily_default
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: ""
  index: /
  port_map: "8088"
  scheme: http
  store_app_id: fervent_emily
  title:
    custom: derper

### OS

Linux

### OS version

ubuntu 20.04

### Tailscale version

1.44.0

### Bug report

BUG-c0d9dd3df40669ab9ec81e86262cda99b157a592cffa431764ed872685f1566c-20240925090920Z-8fc9df0a96a54280

**Comment by bradfitz** [comment]
nginx proxies HTTP. DERP only speaks HTTP briefly and then switches protocols to something that's not HTTP. That breaks nginx.

As described at https://github.com/tailscale/tailscale/tree/main/cmd/derper#readme , do not put derper behind an HTTP-assuming proxy.

You also need to get UDP to the derper.

**Comment by bradfitz** [comment]
Oh, I see you're using "tcp" mode at least. Maybe that's sufficient.

From that doc URL, note the `tailscale debug derp 900` command. You can use that to debug your custom DERP.

**Comment by javito1081** [comment]
For some reason when i disable this in the config file

# List of externally available DERP maps encoded in JSON
  urls:
    - https://controlplane.tailscale.com/derpmap/default

my derp server gets latency and my clients r able to connect to it, but if i leave it enable, my derp server shows up but without latency, is there a way to fix this?
