### ISSUE TITLE
Informazione

### ISSUE THREAD

**Issue by Rofigiu** [tailscale/tailscale#13581]
### What are you trying to do?

Ciao mi sono  registrato e per provare ho aggiunto 3 dispositivi android e un server Linux  a me interessa il Linux perché ne ho molti e ad ogni server c'è collegato un DvR  per telecamere ho provato ad accedere al server ed tutto ok ma devo accedere alla sua sottorete e arrivare al dvr per far sì che posso creare una rete personalizzata  e per ogni server uso anche vpn mullvad

**Comment by agottardo** [comment]
Ci aspettiamo che tutte le conversazioni su questo issue tracker siano in inglese. Questo non è un forum di supporto: per assistenza nell’uso di Tailscale, segui le istruzioni su https://tailscale.com/contact/support.
