### ISSUE TITLE
Add log convention for "this should never happen"

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#136]
We should have a log convention for "this should never happen" sort of defensive check logs, then we can uniformly grep for them and fix mysterious things that do happen.

**Comment by bradfitz** [comment]
(Using `[unexpected]` substring for now in https://github.com/tailscale/tailscale/pull/135)

**Comment by crawshaw** [comment]
Ooh a bike shed.
- `[perplexing]`
- `[flummoxed]`

**Comment by danderson** [comment]
`[unexpected]` seems fine.

An existing convention I'm aware of is the kernel's `BUG:`, which has the double edged property of being highly visible in logs.
