### ISSUE TITLE
Add tag visibility in the API

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1360]
A customer shared the use case for this feature, was for tag discovery via the API using custom CoreDNS plugin - since they can't know a compute resources Tailscale IP at the moment they spin it up using terraform they can't at that point add it's Tailscale IP to route53 or other DNS services. However, they could use a tag to identify machines for which the CoreDNS plugin could resolve queries.

**Describe the solution you'd like**

Add the tag parameter in API support.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2t5xt)

**Comment by bradfitz** [comment]
Copying @DentonGentry's comment from the other bug:

> https://api.tailscale.com/api/v2/tailnet/example.com/devices?fields=all does not return the tags assigned to a device, and it would be quite useful if it did.

**Comment by abh** [comment]
I made a small tool that can inventory the tailscale devices and generate DNS data and not having this was a surprising roadblock for my use case.
