### ISSUE TITLE
FR: install client and cli

### ISSUE THREAD

**Issue by dengshenkk** [tailscale/tailscale#13618]
### What are you trying to do?

Since three install ways on mac has different functions, I want to install the stand alone client and cli. The use case is: the client has the easiest taildrop and the cli has the startup function when the computer has crashes or something will restart. I can use VNC or other services to remote the computer

### How should we solve this?

install the different clients and work

**Comment by agottardo** [comment]
This is not something we can support. The two versions use different macOS APIs to configure routes and DNS resolution.

> the cli has the startup function when the computer has crashes or something will restart

VPN On-Demand set to On with auto-login enabled on your Mac will do the same thing, as a workaround.
