### ISSUE TITLE
Uninstalled Tailscale MACOS Sequoia 15 and unable to connect to the internet

### ISSUE THREAD

**Issue by FloatingLizard** [tailscale/tailscale#13619]
### What is the issue?

Uninstalled  the stand alone Tailscale app on MACOS Sequoia 15 and unable to connect to the internet.
It will connect for about 15 Seconds and then will no longer connect. If I delete the service, then it reconnects for 15 Sec then drop and the same if I disconnect the Wifi and forget the WIFI SSID< 
The script provided was used to uninstall Tailscale 
brew uninstall --cask --zap --force tailscale

And all the following are not present
~/Library/Application Scripts/*.io.tailscale.ipn.macsys
~/Library/Application Scripts/io.tailscale.ipn.macsys
~/Library/Application Scripts/io.tailscale.ipn.macsys.login-item-helper
~/Library/Application Scripts/io.tailscale.ipn.macsys.share-extension
~/Library/Caches/io.tailscale.ipn.macsys
~/Library/Containers/io.tailscale.ipn.macsys
~/Library/Containers/io.tailscale.ipn.macsys.login-item-helper
~/Library/Containers/io.tailscale.ipn.macsys.share-extension
~/Library/Containers/Tailscale
~/Library/Group Containers/*.io.tailscale.ipn.macsys
~/Library/HTTPStorages/io.tailscale.ipn.macsys
~/Library/Preferences/io.tailscale.ipn.macsys.plist
~/Library/Tailscale

### Steps to reproduce

Unable to do that 

### Are there any recent changes that introduced the issue?

Installed Tailscale standalone version.

### OS

macOS

### OS version

Sequioa 15

### Tailscale version

Latest stand alone

### Other software

Not applicable 

### Bug report
BUG-24b31f101ec3eb6e9551dffdd04ec451c181969827b715e5d35ab02c7742d0de-20241001080600Z-f91fb4b4a5fe32d5
Not running Tailscale

**Comment by FloatingLizard** [comment]
I have restored the device and reinstalled Tailscale and it it working 80% percent of the time.  But if I uninstall tailscale then I loose connectivity. 

  One thing I did is to turn off "Private Wifi- Address"  and now the connectivity is stable.   But then issue persist where 20% of the time the connection drops.

**Comment by agottardo** [comment]
If you uninstalled Tailscale and there is no Tailscale VPN listed in the VPN section of System Settings, our network extension is not running, and Tailscale cannot be interfering with your network configuration anymore. The connectivity problem is likely caused by something else on your system that doesn't play nice with Sequoia (do you have any adblockers, other VPN apps, network filters, etc.?)

**Comment by FloatingLizard** [comment]
Well it was uninstalled and the problem started.  I reinstalled tailscale and the issue disappeared.  So?

**Comment by FloatingLizard** [comment]
So can I get instructions on resolving this issue?

**Comment by agottardo** [comment]
Please generate a macOS configuration report from the 'Report an Issue' view in the Tailscale app, and attach it here. If it contains confidential stuff, you can email it at `andrea@tailscale.com`.

**Comment by FloatingLizard** [comment]
What do you mean "Confidential Stuff"  Is it not just a bug report?

**Comment by FloatingLizard** [comment]
What is this?  
MacBookAir.tail4e57d7.ts.net\ lan

tail4e57d7

**Comment by FloatingLizard** [comment]
I did update to the latest OS 
https://discussions.apple.com/thread/255759948?sortBy=rank

**Comment by FloatingLizard** [comment]
I found the issue...  It was Zerotier...  Now the connectivity is stable..  Thanks
