### ISSUE TITLE
unable to sing machine

### ISSUE THREAD

**Issue by chadray73** [tailscale/tailscale#13621]
### What is the issue?

all prior machines have been removed from the admin console and I get circled in a signing loop with no way to sing a new device without an existing... please advise

### Steps to reproduce

remove existing machines from admin console, add new machine and attempt to sign.

### OS

Linux, macOS, iOS

### OS version

macOS sequoia, IOS and Openwrt

### Tailscale version

1.74.0

**Comment by knyar** [comment]
I assume this is referring to [Tailnet Lock](https://tailscale.com/kb/1226/tailnet-lock). If you removed all your signing nodes from Admin Console or using the API, I believe you will first need to re-authenticate one of the previously removed signing nodes, with a Tailnet Lock key that has been recorded in the [Tailnet Key Authority](https://tailscale.com/kb/1230/tailnet-lock-whitepaper#the-tailnet-key-authority). This node can later be used to sign other nodes, and to change the TKA.

If you no longer have keys of your signing nodes, you will need to either [disable tailnet lock](https://tailscale.com/kb/1226/tailnet-lock#disable-tailnet-lock) or delete your tailnet.

Being able to remove all signing nodes in Admin Console is not a great UX here; I have added an internal work item for us to address this.
