### ISSUE TITLE
FR: app-based split tunneling on iOS

### ISSUE THREAD

**Issue by justinLia** [tailscale/tailscale#13646]
### What are you trying to do?

Having app-based split tunneling feature on iOS, such that users are able to let some apps/websites connect the network directly (without passing the VPN/exit node)

### How should we solve this?

Add the app-based split tunneling feature on iOS

### What is the impact of not solving this?

We can't use the app-based split tunneling feature on iOS. It will cause some inconvenience, for example: can't use Safari iCloud private relay(it will disable when using VPN); slower speed with a safety connection that doesn't need passthrough the VPN/exit node; etc.

**Comment by agottardo** [comment]
We cannot build this; Apple doesn't allow it.
