### ISSUE TITLE
Cannot change exit node through Shortcuts when popup still open

### ISSUE THREAD

**Issue by martijnarts** [tailscale/tailscale#13647]
### What is the issue?

When you build a Shortcut to change the exit node, and trigger it, a popup opens saying that the exit node has changed. However, this popup (for me) usually opens below other windows, meaning I don't notice it. Then, when another Shortcut triggers to disable the exit node it doesn't work. It seems to be because the exit node popup is still open.

### Steps to reproduce

Create two shortcuts: one connecting to an exit node, one disconnecting. Trigger the connecting shortcut, don't interact with the popup, trigger the disconnecting popup.

### OS

macOS

### OS version

macOS Sonoma 14.6.1

### Tailscale version

1.74.0

**Comment by agottardo** [comment]
This is a bug for Apple; we don't have control over the behavior of the Shortcuts app. Please use the Feedback Assistant app to report an issue to them.

**Comment by martijnarts** [comment]
I'm confused, the Shortcuts app is working just fine from what I can tell. It's Tailscale's shortcut that opens the popup, right?

This is the popup in question:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/532676b6-b6d4-4ae0-998a-c2a7256a4c09">

Whenever that's open, changing the exit node is blocked. Looking into this did help me figure out how a workaround. I can disable opening the popup, which will make Tailscale properly change the exit node again:

<img width="619" alt="image" src="https://github.com/user-attachments/assets/cfec22a2-d5fd-42da-8286-c4b37ee48789">

Untoggling "Show when run" works around this bug.

**Comment by agottardo** [comment]
We give the string to Shortcuts, it is then Shortcuts that blocks execution until you hit 'Done'. Yes, that's a good workaround (although you won't get a confirmation prompt anymore).
