### ISSUE TITLE
iOS: Can't remove account with 451

### ISSUE THREAD

**Issue by Haarolean** [tailscale/tailscale#13662]
### What is the issue?

Trying to remove an account, getting 'could not log out: fetch control key: 451'. Perhaps related to #13660. Some of the family members' devices using tailscale are located in Russia, that's perhaps the reason for you denying the service. But I believe this shouldn't stop me from *removing* accounts.

### OS

iOS

### OS version

18.0

### Tailscale version

1.74.0

### Bug report

BUG-9fb3e733cf59f96651938aea965b16354c25d29d674717b0bb329d2337d09e7a-20241002225718Z-edf5c0bfcae0ea80

**Comment by agottardo** [comment]
Can you attach a screenshot of where you're seeing the error appear? Even when unable to connect to the control server, you should still be able to remove accounts... this is strange.
