### ISSUE TITLE
admin: allow labelling and bulk adding nameservers

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1366]
There should be an additional admin UI field where you could annotate the server IP with what NS record it came from (for external NS use-case). Also useful to just let me paste the NS record list into the field, as opposed to the single name server IP.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_385ap)

**Comment by rosszurowski** [comment]
To put in more Tailscale-specific terms, I believe this feature request was the ability to label DNS Nameserver records in our admin panel, as well as the ability to add them in bulk (eg. by copy-pasting)

**Comment by DentonGentry** [comment]
To set expectations: it is unlikely that we will do this.

**Comment by DentonGentry** [comment]
The API can manipulate the list of nameservers: https://github.com/tailscale/tailscale/blob/main/api.md
That is the right way to handle issues like this.
