### ISSUE TITLE
Support subnet routing ("relay node") functionality in tailscaled on macOS

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1367]
tailscaled runs reasonable well on macOS (https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS), but there are a few missing features compared to the Linux version. One is being a subnet router ("relay node").

This bug tracks adding subnet routing to `tailscaled`-on-macOS. (This is **NOT** about the GUI version of Tailscale on macOS)

Related tracking bug for Windows: https://github.com/tailscale/tailscale/issues/835

One option is doing it purely in userspace: https://github.com/tailscale/tailscale/issues/707

But this bug is specifically about having the macOS kernel do the work, using `pfctl` or whatnot:

* https://apple.stackexchange.com/questions/363099/how-to-forward-traffic-from-one-machine-to-another-with-pfctl
* https://serverfault.com/questions/791181/redirecting-traffic-to-a-specific-address-and-port-using-pf-on-macos
* etc

**Comment by vincentlu** [comment]
Is this not the same as recently closed #911? #911 is the one referenced in https://tailscale.com/kb/1019/subnets.

**Comment by bradfitz** [comment]
@vincentlu, thanks! It is a dup. #911 should not have been closed. I was confused about the state of the world at the time, misreading people's reports perhaps.

I'll reopen #911 instead and close this one.
