### ISSUE TITLE
“System Extension Install Failed” from .pkg install

### ISSUE THREAD

**Issue by jlucktay** [tailscale/tailscale#13670]
### What is the issue?

Hi there, I just installed Tailscale 1.74.0 from the pkgs page: https://pkgs.tailscale.com/stable/#macos

Following this install, my Tailscale won’t start up properly, and is flickering with an error message from the menubar icon.
I captured a small video here: https://youtu.be/hG1VyzL7Fso

There aren’t any notices in System Settings > Privacy & Security about allowing Tailscale to install its extension, per this help page: [Authorizing the Tailscale system extension on macOS · Tailscale Docs 1](https://tailscale.com/kb/1340/macos-sysext)

Is there anything else I can check to try to make my Tailscale healthy, so that I can connect?
I’m on an Apple M1 Pro MacBook.

### Are there any recent changes that introduced the issue?

I did have a previous installation on this same laptop that was removed a while ago, and this is a separate fresh installation.

### OS

macOS

### OS version

macOS 14.7 (23H124)

### Tailscale version

1.74.0 standalone variant

### Other software

Cloudflare WARP 2024.6.474.0 (20240730.24)
FortiClient 7.0.3.0131

### Bug report

2024/10/03 09:55:10 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscaled.socket: connect: no such file or directory

**Comment by agottardo** [comment]
Is this a work computer? The message indicates that Tailscale asked macOS to install its system extension, but the system turned down the request. It is most commonly caused by restrictions imposed by your administrator.

**Comment by jlucktay** [comment]
It is a work machine, yeah, with MDM. The `system_profiler SPManagedClientDataType` command output is very useful, thank you for that! 🙏
I think I can see enough in the output there to chase it up internally. Cheers!
