### ISSUE TITLE
Validate that tailscale.com/tailnet-ip annotation for the Kubernetes operator egress proxies contains a valid IP address

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#13671]
### What is the issue?

We should validate that the value passed to [`tailscale.com/tailnet-ip`](https://github.com/tailscale/tailscale/blob/6f694da91286ba5b86912d7237f57cd3216739bb/cmd/k8s-operator/sts.go#L64) annotation to egress proxies is a valid IP. 
That should be put in the [`validateService`](https://github.com/tailscale/tailscale/blob/6f694da91286ba5b86912d7237f57cd3216739bb/cmd/k8s-operator/svc.go#L206) method so that `Service` can be set to invalid if the value is not an IP.

**Comment by NRKirby** [comment]
I'd like to pick this up @irbekrm. 

Should be able to get a PR up in next few days if that works?

**Comment by irbekrm** [comment]
@NRKirby - yes, you are very welcome!

**Comment by NRKirby** [comment]
Hey @irbekrm, I've made the change. Could you help me with writing a test? 

I believe we need a test `TestTailnetTargetIPAnnotation_InvalidIP` around line 432 of `operator_test.go`, would you agree with that?

**Comment by NRKirby** [comment]
Can this be closed now @irbekrm as this was merged in https://github.com/tailscale/tailscale/pull/13836

**Comment by irbekrm** [comment]
Closing as this was implemented in https://github.com/tailscale/tailscale/pull/13836

1.78 release has this change
