### ISSUE TITLE
Auto exit node switching

### ISSUE THREAD

**Issue by DigitalSerpant** [tailscale/tailscale#13697]
### What are you trying to do?

On the tail-scale android app, I was wondering how to make my exit node auto shuffle to another online one in case one goes down.

### How should we solve this?

In the app, It could have a option to enable exit node persistence to always have a exit node enabled and switch to another online on if it goes down.

### What is the impact of not solving this?

Currently, I manually have to switch it due to my network configuration which stops any network when it goes down.

### Anything else?

I would greatly appreciate any pointers you could provide to help me make this change on my own.

Thanks for any help!!!

**Comment by agottardo** [comment]
Along with [regional routing](https://tailscale.com/kb/1115/high-availability#regional-routing), this feature is already available to users on _business_ plans: https://tailscale.com/blog/auto-exit-nodes
