### ISSUE TITLE
FR: a way of configuring tailscale so that we can run funnels as a service not as a forground process

### ISSUE THREAD

**Issue by VincentJGeisler** [tailscale/tailscale#13692]
### What are you trying to do?

run tailsscale funnel automatically when i perform >tailscale up

### How should we solve this?

add a way of setting the parameter with tailscale set funnel :portnum:

### What is the impact of not solving this?

the connection dies as soon as the ssh session drops. setting it to background using & only allows it to run a short time before its silently killed off by the kernel.

**Comment by bradfitz** [comment]
See the `--bg` flag

**Comment by bradfitz** [comment]
See https://tailscale.com/kb/1311/tailscale-funnel#funnel-command-flags
