### ISSUE TITLE
TS only dns server

### ISSUE THREAD

**Issue by bcookatpcsd** [tailscale/tailscale#13701]
FreeBSD bare metal machine, 14.1-p5 

em0 is LAN ip and running AdGuardHome only on em0 ip and loopback. 

Install dnscrypt-proxy2 bind it to its ts ip 100.75.66.254:53 start dnscrypt proxy confirm everything is listening and bound to intended IPs. 

TailNet is to use 100.75.66.254 for dns, which should be dnscrypt. Queries are still showing in AdGuardHome em0 and not tailscale0.

Restarted ts and didn't make a difference. 

Binding dnscrypt to em0 LAN ip did work for ts clients.. But was not the intention for LAN interface to run dnscrypt. 

Is this possible? 

Thank you in advance.

**Comment by bcookatpcsd** [comment]
*disabling* the exit node seems to change things depending if the end point is FreeBSD or Linux..

**Comment by bcookatpcsd** [comment]
BUG-d88ca3d8b83c69a510217e97dae0a683369b92376c3a5789b06b55680c979cd4-20241007021910Z-754d9a0001a85a5b

Disable FreeBSD exit node works with linux dns. 

Enable linux exit node, linux dns stops working. 

Enable FreeBSD exit node, freebsd dns works. 

Disable exit node freebsd or linux dns works. 

Enable FreeBSD exit or Linux exit, disable dns; no dns

FreeBSD exit node and linux dns, gets some other dns (nextdns)..

**Comment by sevenrats** [comment]
use resolv.conf to point your host at dnscrypt-proxy. use daemon.json to point docker at it as well.  add the immutable attribute to your host resolv.conf just in case (this is good dnscrypt-proxy practice anyway).  run tailscale in a docker container with host networking and --accept-dns.  should work how you want at that point.
