### ISSUE TITLE
FR: ts-chat

### ISSUE THREAD

**Issue by cou645** [tailscale/tailscale#13700]
### What are you trying to do?

use taildrop to group chat. Each device send a file "$ip"-ts-chat.txt, the contents of which are appended to the group chat log. Each line of chat is prefixed with the device nickname or ip "$ip": "$line". After the received file has been catted into the group chat log it is removed, ready to receive the next update from given ip. Group chat log is saved locally on each device.

' tailscale file get' runs as a daemon or in a while loop for chat, on receiving a ts-chat its contents are appended to the group chat log.

The chat interface has an input field and a text display field showing the accumulated text, using tail. Very simple.
Translation function would be nice too....maybe using my own transtext function along with trans.sh google/bing api.

### How should we solve this?

add to acl tags which can accept true/false devices from receiving chats. Provide a simple in app chat interface for all supported operating systems.

### What is the impact of not solving this?

stagnation

**Comment by bradfitz** [comment]
This is unlikely to be a direction we'll be taking in the foreseeable future.

There are enough chat tools out there. We'd rather be a platform for others to write atop.

Taildrop is barely special: it's mostly just an HTTP request across the tailnet. Any third-party chat app could do that as well.

**Comment by cou645** [comment]
it's understandable ...

I have already completed scripting ts-chat.sh
fyi
https://forum.puppylinux.com/viewtopic.php?t=12647
