### ISSUE TITLE
FR: iOS app can't determine/ relay whether it's on cellular or wifi

### ISSUE THREAD

**Issue by sohojmanush** [tailscale/tailscale#13703]
### What are you trying to do?

Here is the scenario, I have couple of Google map offline maps downloaded on my device. Google map was set to update those maps only in wifi. But as soon I turn on tailscale, it thinks I am in a wifi and starts downloading all the maps. As soon as I turn of tailscale, it stops downloading. All the while I was in cellular data.

### What is the impact of not solving this?

More cellular data usage.

**Comment by bradfitz** [comment]
That seems like a bug in Google Maps. I don't believe a VPN application on iOS could even pretend to be a Wi-Fi connection if it wanted to be.

Google Maps probably sees a network interface present it doesn't recognize and gets confused.

I doubt we can do much here.

/cc @agottardo

**Comment by agottardo** [comment]
This really depends on what APIs Google Maps is using to determine whether it is on Wi-Fi or not. This is not something Tailscale can address, it's something broken in Google Maps.

**Comment by sohojmanush** [comment]
Thank you very much, for explaining.
