### ISSUE TITLE
Cannot add account on MacOS standalone version of Tailscale

### ISSUE THREAD

**Issue by argumemnon** [tailscale/tailscale#13738]
### What is the issue?

MacOS Sonoma 14.6.1
Download and install standalone version of Tailscale 1.74.0.
Launch it.
Click "Settings..."
Click "Add Account..." to get started...nothing happens...

### Steps to reproduce

1. Download and install standalone version of Tailscale 1.74.0 for macOS.
2. Launch it.
3. Click "Settings..."
4. Click "Add Account..."...nothing happens...

### OS

macOS

### OS version

Sonoma 14.6.1

### Tailscale version

1.74.0

### Bug report

BUG-3041090089280fd223411040df681f61e88fa9c5f4cc27205430599c58e4d450-20241009000833Z-6ac3ca0f22f7fbf5

### Additional info

Mac App Store version worked fine.

## video of issue

![addaccount](https://github.com/user-attachments/assets/ad3b8a00-31c1-4c6a-956d-5e6fed2d662a)

**Comment by agottardo** [comment]
Is this a work computer? Do you have any restrictions that could be preventing the Tailscale network extension from starting? Please generate a macOS Configuration Report from the 'Report an Issue' window and send it to `andrea@tailscale.com`. Also provide the output of `system_profiler SPManagedClientDataType`.

**Comment by argumemnon** [comment]
Root cause: my user account did not have the correct permissions to read a required file by the client (/Library/Tailscale/sameuserproof-XXXXX). My account was not a member of the **staff** group. My account was originally a domain joined/"mobile" account and later converted to a local account, and its default group id was a string of numbers (gid=187936349) instead of staff (gid=20). 

Resolution: Added myself to the **staff** group via `sudo dseditgroup -o edit -a myusername -t user staff`, quit and relaunched Tailscale client.

**Comment by ScreamingPict** [comment]
Excellent- thanks for finding this @argumemnon  - Several of us at work have been bumping into this and that was the exact issue.
