### ISSUE TITLE
No connections reported when upgrading to version v0.23.0 from version v0.22.3

### ISSUE THREAD

**Issue by simonlock** [tailscale/tailscale#13737]
### What is the issue?

OS: Debian GNU/Linux 12 (bookworm) x86_64

Once updated all tailscale nodes show offline (Connected: offline) when running

> sudo headscale nodes list

and 

> https://headscale.domainname.com/windows

 is also inaccessible (I am using tls_letsencrypt_challenge_type: TLS-ALPN-01)

The service runs on a restart

> sudo systemctl restart headscale.service

I have migrated my config file to align with your new example config.
I have migrated my acl.yml policy file to the new huJSON format (acl.hujson).
I have tried disabling the use of ACLs by setting path: "" under the policy.
I have tried preventing Headscale from managing DNS by setting all fields under dns to empty values.
I’ve also tried disabling UFW.
I am using the latest version of Tailscale on all of my nodes.

However, all my attempts have failed. When I roll back to v0.22.3, everything works.

Are there any known issues with using v0.23.0 on Debian 12?
Please could you suggest where I might be going wrong?

Thanks in advance.

### Steps to reproduce

Install version v0.23.0 on Debian 12

### Are there any recent changes that introduced the issue?

Upgrade to v0.23.0

### OS

Linux

### OS version

Debian 12

### Tailscale version

1.74.1

### Other software

ufw
fail2ban

### Bug report

BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

**Comment by bradfitz** [comment]
You've got the wrong repo? This issue tracker is not about Headscale.

**Comment by simonlock** [comment]
I'm reporting an issue regarding Headscale? https://github.com/juanfont/headscale/releases/tag/v0.23.0

**Comment by simonlock** [comment]
sorry you're right
