### ISSUE TITLE
FreeBSD.. Traffic rate for "tailscale0" higher than set maximum 1000 Mbit

### ISSUE THREAD

**Issue by bcookatpcsd** [tailscale/tailscale#13769]
### What is the issue?

updated and restarted tailscale.

/var/log/messages

Oct 10 07:14:00 fbsdi5 vnstatd[63641]: Traffic rate for "tailscale0" higher than set maximum 1000 Mbit (20s->2673868800, r4291373345 t4290753235, 64bit:0), syncing.

### Steps to reproduce

FreeBSD, 1.74.1, restart

### Are there any recent changes that introduced the issue?

not sure.. 

### OS

Other

### OS version

FreeBSD 14.1-p5

### Tailscale version

1.74.1

### Bug report

BUG-77f14181bc1967fafa3b22ccaddedd7958bedfd90b6e16b64d2d4be3239bcc3f-20241010112050Z-609029dc6f956187

**Comment by bradfitz** [comment]
I'm lost. I don't know what vnstatd is ("the alternative for cron based updating" ... huh?).

Anyway, is this because of that fake link speed we set on a TUN device? Something is noticing it's doing more throughput than a made-up TUN link speed we set?

/cc @raggi @tendstofortytwo

**Comment by raggi** [comment]
This seems like a vnstat configuration issue, it's making assumptions which are unsound. Somewhat related bug https://github.com/vergoh/vnstat/issues/234.

As far as I can tell this is relatively harmless noise from vnstat.

**Comment by raggi** [comment]
@bcookatpcsd is there a problem here? If so can you describe it in the form of:

I observed X
I expected to instead observe Y
This causes problem Z
