### ISSUE TITLE
FR: Please Open UDP ports (20000-40000) to use Pikvm via Funnel

### ISSUE THREAD

**Issue by edwinrivera19955** [tailscale/tailscale#13771]
### What are you trying to do?

I am trying to connect to Pikvm over Internet.
I made a funnel and 443 port works well. However, I need to use H264 streaming in Pikvm and Funnel needs to listen to 20000-40000 ports for UDP.

### How should we solve this?

Please make Funnel listen to 20000-40000 ports.

### What is the impact of not solving this?

I can't expose Pikvm service over Internet.

**Comment by agottardo** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/6953
