### ISSUE TITLE
Tailscale Launch Failure after update to v1.76.0

### ISSUE THREAD

**Issue by lukaslindnermusic** [tailscale/tailscale#13794]
### What is the issue?

After the new update of the client on macOS, I sometimes get a "Tailscale Launch Failure" when trying to connect.

"Oops! The Tailscale network extension failed to start. This could be caused by another VPN or security software, a bug in Tailscale, or an issue in this version of macOS. Restarting your MacBook may resolve this problem. If the issue persists, contact our support team."

Please note that I have a custom coordination server (headscale) set up.
The connecting error (the topbar menu hangs at "Waiting for Network...") only appears, if the client was connected before, then disconnected but still opened, and then connected again. 
Simply quitting the client and re-opening it helps. Sometimes, an error message gets shown right after the restart as well, but it connects in the background. 
The first "Connect" of the client launch works, but every subsequent reconnect fails until I restart the client completely.

I don't know if this is because I use headscale or if it is a general issue with the latest client update.
But I guess it is a problem with the client, as I have kept my headscale installation untouched and before the client update, it worked like a charm.

### Steps to reproduce

1. (Maybe: Use a custom Headscale server????)
2. Launch Tailscale Client on macOS (latest version)
3. Connect
4. Disconnect
5. Connect again and the error pops up and the connect fails.

### Are there any recent changes that introduced the issue?

not in my setup, I just installed the latest tailscale client version 

### OS

macOS

### OS version

macOS Ventura 13.6.9 (but also tested on the latest OS version)

### Tailscale version

1.74.0

### Other software

Headscale, Version v0.23.0-beta1

### Bug report

BUG-2b582d185b0c10fe6ca1c87cff5e42490308e6e80d8ad2b67546de0cbee43e85-20241011205820Z-b3a6399463493e07

**Comment by lukaslindnermusic** [comment]
Edit: Issue persists with 1.76.0

**Comment by daniel-ai2** [comment]
We also are running into this, using Tailscale 1.76.0 on macOS 13.6.6. Same steps to reproduce, and when opening Tailscale see: 
![Screenshot 2024-10-11 at 4 25 01 PM](https://github.com/user-attachments/assets/51b7eaaa-ff69-45cb-8742-023d744be272)
and sometimes a few seconds later:
![Screenshot 2024-10-11 at 4 38 17 PM](https://github.com/user-attachments/assets/c8009c65-143c-49c1-8afa-0435568d651a)

**Comment by lukaslindnermusic** [comment]
> We also are running into this, using Tailscale 1.76.0 on macOS 13.6.6. Same steps to reproduce, and when opening Tailscale see: ![Screenshot 2024-10-11 at 4 25 01 PM](https://private-user-images.githubusercontent.com/93166319/375908160-51b7eaaa-ff69-45cb-8742-023d744be272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTE0MjMsIm5iZiI6MTcyODY5MTEyMywicGF0aCI6Ii85MzE2NjMxOS8zNzU5MDgxNjAtNTFiN2VhYWEtZmY2OS00NWNiLTg3NDItMDIzZDc0NGJlMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDIzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OWVlN2QyOWI3ZDZlMGVhODBkODE2NDQzNDY3MGZhYzM4MWRlOTlmMmU2NGQ3ODBiMjBmZDZhODhkODk2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.46deRkSxWe3FrfLmQRbISQ3z8tsPjE8ZflHBKpIZZr0) and sometimes a few seconds later: ![Screenshot 2024-10-11 at 4 38 17 PM](https://private-user-images.githubusercontent.com/93166319/375908242-c8009c65-143c-49c1-8afa-0435568d651a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTE0MjMsIm5iZiI6MTcyODY5MTEyMywicGF0aCI6Ii85MzE2NjMxOS8zNzU5MDgyNDItYzgwMDljNjUtMTQzYy00OWMxLThhZmEtMDQzNTU2OGQ2NTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDIzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNDA0ZTc0OGFjYjk5Zjc4MTYxNjIzZTU1YmFkMTI2MjIzNDFjYTg0M2MyZTUzYTJhNzY2OGQyMjRkZTEzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i1BkHFMWeM0-R6dDD-0yE7FbJ3PN6d-ZdjvQ9wKY24k)

are you using headscale as a custom coordination server, too, or are you using the normal Tailscale Admin Console?

**Comment by daniel-ai2** [comment]
the normal Tailscale Admin Console, so it seems to definitely be an issue with the Tailscale client

**Comment by agottardo** [comment]
Can you please look for any crashes of the Tailscale network extension in the Console app, and attach the stack traces here (`.ips` files)? Thanks.

**Comment by lukaslindnermusic** [comment]
@agottardo Unfortunately, there are no crash reports in the console app :/ 
Yes, I rebooted several times since this issue first appeared. Sadly, it did resolve nothing.
The problem also exists on multiple devices with macOS (for me it appeared on an iMac as well as a Macbook Air and a Macbook Pro).

**Comment by agottardo** [comment]
We need some diagnostics to understand what's going on. Please send a sysdiagnose from your Mac to andrea@tailscale.com. Attach date and time the issue last verified.

**Comment by lukaslindnermusic** [comment]
@agottardo I have re-tried using the Console to identify any problems, and while there are no "crash reports" happening, the logs for the process "Tailscale" are indeed showing some errors. 

I have exported the logs covering following actions:
- Launched Tailscale
- First Connection Attempt worked
- Disconnected
- Second Connection Attempt failed with Error Message popup
- „Disconnected"
- Third Connection Attempt failed without Error Message popup, just shows „Waiting for Network“ and „Tailscale Launch Failure“ in the topbar menu icon menu.
- „Disconnected“
- Closed the app

I have sent you the logs to the mail you provided and I hope that it helps. If not, I can also send you the sysdiagnose if you need it.

**Comment by nalzok** [comment]
I'm getting the exact same error on macOS 13.7 (22H123) and Tailscale 1.76.0 from Mac App Store. I'm not using headscale, and there are no crash reports for the Tailscale network extension in Console.app.

In case it helps, I generated the bug report `BUG-b39889e0e73ec2ac6a16e595144c029bfeb44010007d9eababd6059b6efd4e72-20241016155534Z-90e9e476c97cdf62`. I'm also sending the `sysdiagnose` output to andrea@tailscale.com.

**Comment by agottardo** [comment]
@nalzok in the sysdiagnose you submitted, macOS is refusing to start the network extension due to a failed signature check:
```
NetworkExtension	0x5f048	2024-10-16 12:04:26.609463 -0400	IPNExtension	Signature check failed: code failed to satisfy specified code requirement(s)
```

Please upgrade your OS if possible. It's a OS bug we no longer see in macOS 14 or 15, usually caused by switching between TestFlight and stable builds; or switching from Standalone to App Store variant. Something gets macOS confused when you do so. Sometimes a reboot fixes it. If not, please uninstall Tailscale, ensure no copy of `Tailscale.app` is stored anywhere on your system, reboot your Mac, then install the Standalone variant with the `.pkg` installer.

**Comment by lukaslindnermusic** [comment]
Ok, @nalzok was faster with the sysdiagnose and it looks like the .pkg is working 😊

Unfortunately, I can't upgrade all of my macOS devices due to dependencies on software that does not run on the latest macOS versions. I also have always used the App Store version as far as I can remember.

However, I uninstalled it, rebooted, installed the .pkg version and re-connected to my tailnet and - for now - I can confirm, that it looks like this solves the issue.

I will keep an eye on it and will get back in touch if the issue comes again.

Until then, thank you @agottardo 😊

**Comment by nalzok** [comment]
Cool! The solution suggested by @agottardo works for me as well. However, switching to the standalone version changes my machine's identity, i.e. now I have both `dhcp-vl2041-54545` (Mac App Store) and `dhcp-vl2041-54545-1` (Standalone), but they are really the same machine. This causes problems because I'm sharing this node to other people.

Can I make the Standalone version "inherit" the identity of the Mac App Store version, e.g. by crazy hacks like copying some "node key" over? I have root access to this node in case it makes things easier.

**Comment by lxndrp** [comment]
I experienced the same behaviour. For me, I just had to reauthorise Tailscale under "System Settings / Privacy & Security / Extensions / Added Extensions / Tailscale / Network". After restarting the app, it worked again.

Why this authorisation is lost between upgrades is beyond me. I solely use the Mac App Store version.

**Comment by rsnodgrass** [comment]
@lxndrp removing and re-adding the extension solved this exact problem for me as well (on latest MacOS, latest stable version of Tailscale).  Thank you!

**Comment by zhangguanzhang** [comment]
same issue on Linux, back to v1.74.1 works on headscale

**Comment by agottardo** [comment]
@zhangguanzhang your issue _might_ be fixed by https://github.com/tailscale/tailscale/pull/14564, give it a try (it'll land in v1.80).
