### ISSUE TITLE
tailscale status output

### ISSUE THREAD

**Issue by RealYukiSan** [tailscale/tailscale#13798]
### What is the issue?

The machines that are connected to the tailnet is not shown in the `tailscale status --active --self=false` command.

the connected list show only if I ping each machine first :"

### OS

Linux

**Comment by bradfitz** [comment]
That is expected, because you used `--active`.

**Comment by RealYukiSan** [comment]
@bradfitz is there a way to list connected device that are active (poweron, have internet access, or whatnot) without need to ping the device first?
