### ISSUE TITLE
Opt-out of accepting subnet routes on mac

### ISSUE THREAD

**Issue by Julusian** [tailscale/tailscale#1380]
**Is your feature request related to a problem? Please describe.**

On linux you have to opt in to accepting subnet routes (`--accept-routes`), but on mac you always get given the routes with no way to opt out.

In my homeoffice setup, I have tailscale running on a few key machines. I also have a pi as a relay to expose the rest of the network to tailscale (subnet route 10.0.0.0/16).
For the lan segment (10.0.1.0/24) of my network this is fine, the routing on the mac appears to prefer local to tailscale. However, I also use various vlans which are exposed to tailscale too (eg 10.0.2.0/24)
With tailscale disconnected the vlans are handled by the router (via the default route).When tailscale is connected, it becomes the preferred route for this traffic via the subnet route (10.0.0.0/16).

**Describe the solution you'd like**

Having an option in the tailscale menu to toggle accepting subnet routes.

Ideally, it would be nice to be able to choose which routes to accept (grouped by relay?), but that is not supported on linux so should probably be a later task. 

**Describe alternatives you've considered**

I can work around the issue by using network profiles, and manually defining a local 10.0.0.0/16 route, but this is more error prone and a more complex workflow than being able to do it inside tailscale

**Additional context**

**Comment by bradfitz** [comment]
If you Option-click the Mac menu bar icon, you'll see extra options including the checkbox you're looking for. Perhaps that one shouldn't be hidden and we should address the UI simplicity by instead hiding it when a network doesn't have any advertised subnets.

**Comment by Julusian** [comment]
Ah, I did not think to option-click

Yeah, I think that is a good idea

**Comment by bradfitz** [comment]
Thoughts, @rosszurowski?

**Comment by rosszurowski** [comment]
We've got a new menu design in the works (https://github.com/tailscale/corp/issues/1268 for reference) that should address the discoverability of these features. It puts settings like "use subnet routes" into a "Preferences" drop-down so folks should be able to find it by just exploring the menu without any hidden shortcuts.

Here's the design we're working off of, in case you're interested.

![image](https://user-images.githubusercontent.com/303731/108733265-59aca780-74fc-11eb-8a28-04fe535381fa.png)

**Comment by DentonGentry** [comment]
Since the original issue is resolved via the debug menu, and the new UI (tracked elsewhere) should make it more discoverable, I'm going to close this now.
