### ISSUE TITLE
Enable tailscale dns settings causes web browsers to return dns_probe_possible

### ISSUE THREAD

**Issue by pinkyellowed** [tailscale/tailscale#13838]
### What is the issue?

tailscale macos app causes internet connection unreachable.
 

### Steps to reproduce

using tailscale app, specifically the use tailscale dns settings.
 

### Are there any recent changes that introduced the issue?

no

### OS

macOS

### OS version

sequoia 15.0.1

### Tailscale version

1.76.1

### Other software

LuLu block, Pihole-unbound. 
i have other extensions that prompts if something is occurring and asks me to connect first before even reaching my server, so i run all firewalls down at an system/kernel level.
lulu block - i have allow connections on port 53 and allowed all apps that have been parsed through the apple store
https://imgur.com/a/3DXpfr7

### Bug report

BUG-18db0a6ef268c1b5f191536f69fcbec04bdecec44b89988fae3c3eefe4819916-20241016223535Z-a4a5047a7c5c2046

**Comment by pinkyellowed** [comment]
ok i fixed it... i just turned off pihole for 30seconds and they are both working now.
possible that my macos had old dns caches pointing to old servers....

**Comment by pinkyellowed** [comment]
my fault. i still had a dns filter on my brave browser.
i had 2 dns servers conflicting

**Comment by edyta1111** [comment]
I had a similar issue, also on a MacBook and the Brave browser. The deployed app loaded fine on Safari.
What helped was in Brave's settings, going to Privacy and security > Security > Disable 'Use Secure DNS'
