### ISSUE TITLE
Decide what to do with older clients re: default routes

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1383]
With the launch of v6 + default routes, we're changing the semantics of 0.0.0.0/0: previously (<=1.4), if you advertised 0.0.0.0/0 into your tailnet, all clients that are accepting routes would pick that up and start using it. Some would then immediately break due to missing/insufficient routing loop avoidance.

With 1.6, default routes are separately opt-in from subnet routes, and off by default. The problem that arises is that with 1.6, multiple nodes can offer a default route simultaneously. Empirically, when older clients get such a netmap, they freak out and connectivity breaks.

We need to decide how we're going to handle default routes in older clients, given the change in semantics. Options:

1. We never promised that default routes worked before 1.6, so we make control filter out 0.0.0.0/0 when speaking to older clients. If you were using default routes before, they will silently turn off until you upgrade to 1.6 and use that version's default routes.
2. In control, when a network has multiple default routes on offer, filter all but one when sending to old clients. Preserves the semi-broken pre-1.6 default route behavior for users currently using them, but introduces a surprising failure mode for people who want to use 1.6's good default route support, but have only upgraded part of their network: the other part will unconditionally pick up the default routes meant for 1.6.
3. Do some kind of server-side thing where we refuse to accept new default routes for any network that's not entirely 1.6. Users on old versions using that broken default routing continue working, but we prevent new users from entering the confusing, bad state.
4. Using feature flags, add users currently using 0.0.0.0/0 to a "legacy feature" group. They continue receiving their existing default routes on all clients. Everyone else gets the behavior described in (1), where you must have 1.6 in order to use default routes. Retire the feature flag once all the "legacy" networks are upgraded to 1.6.

Personally, I'm leaning (1) or (4), because they both have easy to explain and predict semantics.

Thoughts @bradfitz?

**Comment by bradfitz** [comment]
(4) is a little overkill in that if you're allow-listing all current users into it, it's not like you're going to get many "old" (1.4 and below) users later using it. People only download new stuff and upgrade pretty quickly.

I'm fine with (1). It'll be easier to support.

But if we look at the usage numbers and too many (or important?) users are depending on it, then perhaps a blend of the above:

* no new feature flags.
* all 1.4 users continue to work, unchanged
* once a network has 2+ approved default route advertisements, 1.4 clients get nothing sent to them from control (bonus points: big warning badges/UI/confirmation prompt in admin panel?). Notably, this means it's an admin that's breaking 1.4 networks by their actions, not a software update from a user or from automatic updates.

**Comment by danderson** [comment]
Going to go with a modified (1): I'll add a feature flag that allows quick reverting to the old behavior, so that if important users trip over it, we can quickly get them back on their feet. But we'll start with the "feature" turned off for everyone.
