### ISSUE TITLE
mullvad/windows 1.76: New UI doesn't always show available nodes, can't see device list

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#13845]
### What is the issue?

We shipped a new Mullvad UI for Windows in 1.76 and I'm hearing reports that while the Mullvad option is visible in the Exit Node menu, the menu to choose your device doesn't actually open. Users are seeing "no exit node available" in the UI, but connecting to a Mullvad exit node using the CLI works. I'm unfortunately not able to reproduce this behavior currently.

----

**How can you help?**

If you're experiencing the same issue, please comment with a `tailscale bugreport` generated from the affected Windows machine and paste that in a comment on this issue. Thank you!

**Comment by BadDownload** [comment]
Thanks for filing a tracking bug. I'm seeing this behavior on two Windows machines. I see the behavior on both 1.76.0 and 1.76.1, and generated bug reports for each version on each impacted machine.

Machine 1: Windows 11 23H2 (22631.4169)
* 1.76.0: BUG-efad30ec321858d5620e6670d5e806f9a336db56d1a30662fcfba29079ebc104-20241018214021Z-f0b91695af0bcdc1
* 1.76.1: BUG-efad30ec321858d5620e6670d5e806f9a336db56d1a30662fcfba29079ebc104-20241018214251Z-27bd28e781efa2a7

Machine 2: Windows 11 23H2 (22631.4037)
* 1.76.0: BUG-c73594cfa65f0a55504b902cc0a51be6ec64bd87e700b55d0010a35ee8abdaf0-20241018214515Z-12051de1bd71f397
* 1.76.1: BUG-c73594cfa65f0a55504b902cc0a51be6ec64bd87e700b55d0010a35ee8abdaf0-20241018214731Z-0d6f83fe457163aa

Thanks for investigating.

**Comment by ikhatri** [comment]
I am also seeing this issue on my machine using Windows 10, after updating to Tailscale 1.76.1
```
BUG-c3234ac71b01a6d5dff139f235cbf3bcf5dd682674ae3cce78b9914a21750304-20241019063748Z-321bc85500f54059
```

**Comment by des0lat10n** [comment]
holy shit so its not just me thank god. my dropdown hasn't appeared since the last update.

**Comment by kelivel** [comment]
Thanks for the bug reports, folks! We're still investigating this, and there's two options in the meantime to connect to your Mullvad exit nodes:

1. Downgrade to stable 1.74.0 at https://pkgs.tailscale.com/stable/?v=1.74.0#windows
2. Connect via cmd.exe: `tailscale exit-node-list`, find the exit node you want to use (example NYC), and run `tailscale set --exit-node=us-nyc-wg-301.mullvad.ts.net`.

**Comment by dblohm7** [comment]
If you're willing, please give [unstable build](https://pkgs.tailscale.com/unstable/#windows) 1.77.27 a try and post your results to this issue.

**Comment by freeform99** [comment]
> If you're willing, please give [unstable build](https://pkgs.tailscale.com/unstable/#windows) 1.77.27 a try and post your results to this issue.

I had the same problem, this works for me, I got the selection of exit nodes back in the GUI and the "no exit node available" message is no longer there

![{82884017-1508-4144-A63C-982B83E8CFAC}](https://github.com/user-attachments/assets/a724c84a-07d0-468d-800b-81977a45c4a3)

**Comment by kelivel** [comment]
Great to hear! We've just shipped [v1.76.3](https://pkgs.tailscale.com/stable/#windows) with this fix rolled in. If the problem reappears, please re-open this issue or create a new one and we'll take a look.

**Comment by vysecurity** [comment]
How do you get the Mullvad exit node IP address for --exit-node=?

**Comment by kelivel** [comment]
> How do you get the Mullvad exit node IP address for --exit-node=?

`tailscale exit-node list`
