### ISSUE TITLE
Error setting up iptables masquerading on tailscale exitnode on openwrt 23.05.3.

### ISSUE THREAD

**Issue by lizhengaas** [tailscale/tailscale#13841]
### What is the issue?

#     - adding [-m mark --mark 0x40000/0xff0000 -j MASQUERADE] in nat/ts-postrouting: running [/usr/sbin/iptables -t nat -A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE --wait]: exit status 2: iptables v1.8.8 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.

### Are there any recent changes that introduced the issue?
I used this luci project
https://github.com/asvow/luci-app-tailscale

### OS

Other

### OS version

openwrt23.05.3

### Tailscale version

1.76.0

### Other software

none

**Comment by irbekrm** [comment]
Thank you for opening the issue.

I don't have an OpenWRT device to try this out and am not familiar with the linked project, but from the error message it looks like Tailscale is not able to configure firewall with iptables, perhaps due to some missing kernel modules.

Could you show us the output of `lsmod` on the host?

Could you try to explicitly configure nftables instead of iptables and let us know if that works?
https://tailscale.com/kb/1294/firewall-mode#how-to-set-the-firewall-mode

**Comment by lizhengaas** [comment]
root@ImmortalWrt:~# lsmod
af_alg                 28672  4 algif_skcipher,algif_rng,algif_hash,algif_aead
algif_aead             16384  0
algif_hash             16384  0
algif_rng              16384  0
algif_skcipher         16384  0
aquantia               24576  0
arc4                   16384  0
asn1_decoder           16384  1 nf_nat_snmp_basic
authenc                16384  2 crypto_safexcel,authencesn
authencesn             16384  0
cfg80211              294912  4 mt7915e,mt76_connac_lib,mt76,mac80211
compat                 16384  2 mac80211,cfg80211
crc_ccitt              16384  2 ppp_async,aquantia
crypto_safexcel       122880  0
crypto_user            16384  0
cryptodev              53248  0
des_generic            16384  0
gpio_button_hotplug    16384  0
ip_tables              28672  2 iptable_mangle,iptable_filter
ip_tunnel              28672  1 sit
ipt_REJECT             16384  0
iptable_filter         16384  0
iptable_mangle         16384  0
leds_gpio              16384  0
libcrc32c              16384  1 nf_tables
libdes                 24576  2 crypto_safexcel,des_generic
mac80211              577536  3 mt7915e,mt76_connac_lib,mt76
macvlan                24576  0
md5                    16384  1 crypto_safexcel
mt76                   77824  2 mt7915e,mt76_connac_lib
mt76_connac_lib        53248  1 mt7915e
mt7915e               143360  0
nf_conntrack           90112 26 nft_redir,nft_nat,nft_masq,nft_fullcone,nft_flow_offload,nft_ct,nf_nat_t                                                                   ftp,nf_nat_snmp_basic,nf_nat_sip,nf_nat_pptp,nf_nat_irc,nf_nat_h323,nf_nat_ftp,nf_nat_amanda,nf_nat,nf_f                                                                   low_table,nf_conntrack_tftp,nf_conntrack_snmp,nf_conntrack_sip,nf_conntrack_pptp,nf_conntrack_netlink,nf                                                                   _conntrack_irc,nf_conntrack_h323,nf_conntrack_ftp,nf_conntrack_broadcast,nf_conntrack_amanda
nf_conntrack_amanda    16384  3 nf_nat_amanda
nf_conntrack_broadcast   16384  1 nf_conntrack_snmp
nf_conntrack_ftp       16384  3 nf_nat_ftp
nf_conntrack_h323      49152  5 nf_nat_h323
nf_conntrack_irc       16384  2 nf_nat_irc
nf_conntrack_netlink   40960  0
nf_conntrack_pptp      16384  2 nf_nat_pptp
nf_conntrack_sip       28672  3 nf_nat_sip
nf_conntrack_snmp      16384  2 nf_nat_snmp_basic
nf_conntrack_tftp      16384  3 nf_nat_tftp
nf_defrag_ipv4         16384  1 nf_conntrack
nf_defrag_ipv6         20480  1 nf_conntrack
nf_flow_table          32768  4 nf_flow_table_ipv6,nf_flow_table_ipv4,nf_flow_table_inet,nft_flow_offloa                                                                   d
nf_flow_table_inet     16384  1
nf_flow_table_ipv4     16384  0
nf_flow_table_ipv6     16384  0
nf_log_syslog          20480  0
nf_nat                 36864 12 nft_redir,nft_nat,nft_masq,nft_fullcone,nft_chain_nat,nf_nat_tftp,nf_nat                                                                   _sip,nf_nat_pptp,nf_nat_irc,nf_nat_h323,nf_nat_ftp,nf_nat_amanda
nf_nat_amanda          16384  0
nf_nat_ftp             16384  0
nf_nat_h323            16384  0
nf_nat_irc             16384  0
nf_nat_pptp            16384  0
nf_nat_sip             20480  0
nf_nat_snmp_basic      16384  0
nf_nat_tftp            16384  0
nf_reject_ipv4         16384  3 nft_reject_ipv4,nft_reject_inet,ipt_REJECT
nf_reject_ipv6         16384  2 nft_reject_ipv6,nft_reject_inet
nf_tables             172032281 nft_fib_inet,nf_flow_table_ipv6,nf_flow_table_ipv4,nf_flow_table_inet,nf                                                                   t_reject_ipv6,nft_reject_ipv4,nft_reject_inet,nft_reject,nft_redir,nft_quota,nft_objref,nft_numgen,nft_n                                                                   at,nft_masq,nft_log,nft_limit,nft_hash,nft_fullcone,nft_flow_offload,nft_fib_ipv6,nft_fib_ipv4,nft_fib,n                                                                   ft_ct,nft_counter,nft_compat,nft_chain_nat
nfnetlink              20480  3 nft_compat,nf_tables,nf_conntrack_netlink
nft_chain_nat          16384  4
nft_compat             20480  0
nft_counter            16384 21
nft_ct                 20480 18
nft_fib                16384  3 nft_fib_inet,nft_fib_ipv6,nft_fib_ipv4
nft_fib_inet           16384  0
nft_fib_ipv4           16384  1 nft_fib_inet
nft_fib_ipv6           16384  1 nft_fib_inet
nft_flow_offload       16384  1
nft_fullcone           57344  4
nft_hash               16384  0
nft_limit              16384  5
nft_log                16384  0
nft_masq               16384  0
nft_nat                16384  0
nft_numgen             16384  0
nft_objref             16384  0
nft_quota              16384  0
nft_redir              16384  1
nft_reject             16384  3 nft_reject_ipv6,nft_reject_ipv4,nft_reject_inet
nft_reject_inet        16384  2
nft_reject_ipv4        16384  0
nft_reject_ipv6        16384  0
ppp_async              24576  0
ppp_generic            49152  4 pppoe,ppp_async,pppox,ppp_mppe
ppp_mppe               16384  0
pppoe                  28672  0
pppox                  20480  1 pppoe
seqiv                  16384  0
sha1_generic           16384  1 crypto_safexcel
sit                    32768  0
slhc                   16384  1 ppp_generic
ts_bm                  16384  0
ts_fsm                 16384  0
ts_kmp                 16384  6
tun                    49152  2
tunnel4                16384  1 sit
x_tables               32768 14 nft_compat,iptable_mangle,iptable_filter,ipt_REJECT,ip_tables,xt_time,xt                                                                   _tcpudp,xt_multiport,xt_mark,xt_mac,xt_limit,xt_comment,xt_TCPMSS,xt_LOG
xt_LOG                 16384  0
xt_TCPMSS              16384  0
xt_comment             16384  0
xt_limit               16384  0
xt_mac                 16384  0
xt_mark                16384  0
xt_multiport           16384  0
xt_tcpudp              16384  0
xt_time                16384  0
![image](https://github.com/user-attachments/assets/9dd505e1-93ba-4418-b7bc-9977ac5871d1)
The firewall is using Nftable mode. I suspect that there is a conflict with the network interface configuration of the luci project I mentioned. 
When I close this code, tailscalecan configure the routing policy normally, but it will issue a health alert.
When using luci network interface configuration, a similar problem occurred when restarting tailscaled service with luci.
Snippets from https://github.com/asvow/luci-app-tailscale：
		ts0=$(ifconfig | grep 'tailscale' | awk '{print $1}')
		if [ -z "$(uci -q get network.tailscale)" ];  then				
			uci set network.tailscale='interface'
			if [ "$ts0" = *$'\n'* ]; then
				echo "tailscale:$ts0"
				uci set network.ts_lan='device'
				uci set network.ts_lan.type='bridge'
				uci set network.ts_lan.name='ts-lan'
				for port in "${ts0}"; do
					uci add_list network.ts_lan.ports=$port
				done
				uci set network.tailscale.proto='none'
				uci set network.tailscale.device='ts-lan'
			else
				echo "tailscale:$ts0 $(tailscale ip)"
				ts_ip=$(tailscale ip -4)
				uci set network.tailscale.proto='static'
				uci set network.tailscale.ipaddr=$ts_ip
				uci set network.tailscale.netmask='255.0.0.0'
				uci set network.tailscale.device=$ts0
			fi
		fi

**Comment by lizhengaas** [comment]
![image](https://github.com/user-attachments/assets/8810cedb-67a5-4bae-8c1a-1e0f44257210)
Routing policy when an exception occurs.

**Comment by irbekrm** [comment]
Thank you for the lsmod output. From a brief look it seems to me that [xt_MASQUERADE](https://github.com/torvalds/linux/blob/master/net/netfilter/xt_MASQUERADE.c) is missing and I assume that is why Tailscale is not able to create the rule.

> When using luci network interface configuration, a similar problem occurred when restarting tailscaled service with luci.

You can take a look at tailscaled logs to understand if tailscale is using iptables or nftables, i.e:
```
journalctl  -u tailscaled | grep -E 'iptables|nftables'
tailscaled[1048]: router: default choosing iptables
tailscaled[1048]: router: netfilter running in iptables mode v6 = true, v6filter = true, v6nat = true
...
```

**Comment by lizhengaas** [comment]
Thu Oct 17 18:02:08 2024 daemon.err tailscaled[5930]: 2024/10/17 10:02:08 router: default choosing iptables
Thu Oct 17 18:02:08 2024 daemon.err tailscaled[5930]: 2024/10/17 10:02:08 router: disabling tunneled IPv6 due to missing ip6tables: path not found: exec: "ip6tables": executable file not found in $PATH
Do I need to install ip6tables?

**Comment by irbekrm** [comment]
> Thu Oct 17 18:02:08 2024 daemon.err tailscaled[5930]: 2024/10/17 10:02:08 router: default choosing iptables


That confirms that this particular installation was using iptables not nftables, so it doesn't look like the `TS_DEBUG_FIREWALL_MODE` env var was being passed to tailscaled.

I think you should try to get tailscaled running with nftables instead of iptables and see if that works. I am not familiar with https://github.com/asvow/luci-app-tailscale - perhaps check with the authors how to pass an env var to tailscaled via their packaging mechanism.

**Comment by lizhengaas** [comment]
Thank you very much.  After configuring TS_DEUTE_FIREWALL_MED correctly, Tailscale can be used normally.
Iptable can also be supported, and "iptables-nft" and "ip 6 tables-nft" need to be installed in openwrt.
