### ISSUE TITLE
FR: Release official Android builds to GitHub

### ISSUE THREAD

**Issue by TheDcoder** [tailscale/tailscale#13862]
### What are you trying to do?

With the recent F-Droid issue (#13850) it's clear that Tailscale users who'd want more reliability should use the official builds, however the Android app is not available for download via GitHub releases.

The website just points towards the Google Play Store page for the app but this might not be a good or even viable option for some folk who have de-Googled their phones.

I believe there is a semi-official page with a link to the universal APK, but it's not as accessible as GitHub.

### How should we solve this?

For each version, release all of the official builds to GitHub. This would allow people to use apps like Obtainium to fetch it from an offical source without relying on any other 3rd-party (aside from GitHub itself, of course) with automatic updates.

I would also like to see platform-specific builds for people who have enough know-how (or use an app) to pick only the version that's required for their device, this is the reason why I currently don't use the universal package which is bloated due to containing several different versions of the same app.

### What is the impact of not solving this?

If not solved users are stuck between a rock and a hard place:

1. Option A: Get it from a closed-source proprietary app store made by a data-stealing corporation.
2. Option B: Get unofficial builds from F-Droid which are not quality tested (as it has been made evident recently).

**Comment by bradfitz** [comment]
Our official binaries are at:
* Stable: https://pkgs.tailscale.com/stable/#android
* Dev: https://pkgs.tailscale.com/unstable/#android (note that we actually test these before release, so they're less of a mystery than F-Droid builds)

JSON metadata for those is e.g. https://pkgs.tailscale.com/stable/?mode=json

**Comment by TheDcoder** [comment]
@bradfitz Nice! Thanks for the info, but is this "official" or is this just a temporary thing with no availability guarantee (i.e. it could go away or change at any time).

I'd still prefer GitHub over a custom first-party source since the former is a somewhat standardized form of distribution.

**Comment by bradfitz** [comment]
That is our official (with no quotes) release site (with our domain name and everything!) and we haven't gotten rid of it for 5 years now. We have no plans to drop it.

We could probably mirror the releases to GitHub as well, I suppose.

/cc @kari-ts @barnstar @agottardo

**Comment by TheDcoder** [comment]
> we haven't gotten rid of it for 5 years now. We have no plans to drop it.

Wow, certainly didn't expect that. You folks should've a link to that on your downloads page, I went through your website hoping to find a direct APK download but I was left empty handed until I saw someone mention that site in the other ticket.

My impression was that it was some temporary thing that was setup recently.

> We could probably mirror the releases to GitHub as well, I suppose.

That would be much appreciated :)

**Comment by Georift** [comment]
I also ran into the f-droid issue described here. The official apk links provided were enough for me to plug them into Obtainium to automatically update tailscale.

[Add tailscale to Obtainium](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.tailscale.ipn%22%2C%22url%22%3A%22https%3A%2F%2Fpkgs.tailscale.com%2Fstable%2F%23android%2F%22%2C%22author%22%3A%22pkgs.tailscale.com%22%2C%22name%22%3A%22Tailscale%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22((%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.)%7B2%7D%5C%5C%5C%5Cd%2B)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%240%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3Anull%7D)

**Comment by FloatingLizard** [comment]
Impossible to install...

**Comment by bradfitz** [comment]
@FloatingLizard, you're going to have to use more words if you want us to understand your concern.

**Comment by TheDcoder** [comment]
@Georift That's a workable solution, but it has two at-least big disadvantages that I can think of from the top of my head:

1. Since Tailscale only provides the universal package, the "Filter by Arch" option becomes useless
2. To check for an update Obtainium has to download the APK file in order to check the version since it's coming from a custom source without versioning info.

It wastes bandwidth unnecessarily, especially if you're on a mobile network as you often are on your phone.

**Comment by Georift** [comment]
> To check for an update Obtainium has to download the APK file in order to check the version since it's coming from a custom source without versioning info.

I'm not sure if the link shared included this, but I believe I crafted a version string regex correctly to prevent the duplicate downloads.

I don't want to take away from the discussion here, I'd still appreciate seeing the releases mirrored to Github. I only wanted to share a solution that's helping me.

**Comment by agottardo** [comment]
The latest APK is now available at https://github.com/tailscale/tailscale-android/releases. We will post APKs on GitHub once we've made them available at https://pkgs.tailscale.com/stable/#android.

**Comment by TheDcoder** [comment]
@agottardo Awesome, thank you for the quick response!

Any chance we can get platform-specific packages as well? (armhf, aarch64, x86 etc.)
