### ISSUE TITLE
F-Droid: App instantly crashes since Version 1.76.x

### ISSUE THREAD

**Issue by pmffromspace** [tailscale/tailscale#13878]
### What is the issue?

unable to Start app.

### Steps to reproduce

Im on eOS Android (without google)

### Are there any recent changes that introduced the issue?

Update

After downgrade to 1.72 works again

### OS version

2.4.1-t-20241008439851-official-FP5

### Tailscale version

1.76.*

**Comment by nagisa** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/13850
