### ISSUE TITLE
MacOS Network Extension UI Update Request

### ISSUE THREAD

**Issue by kmanwar89** [tailscale/tailscale#13879]
### What is the issue?

On a M3 MacBook Pro, after installing Tailscale from the official website using the .pkg installer, the user is prompted to allow the system network extension.  There are a few UI updates needed in this flow, outlined below:

1. Clicking the "open settings" box of the dialog box directs the user to the "Privacy & Security" pane of the Settings app, not the "General" pane the user is actually instructed to navigate to

2. The actual item that needs to be enabled is found under General --> Extensions --> Network Extensions, and is called "IPNExtension".  Is it possible to update the UI to contain this info, or perhaps rename this to be more aligned to something related to Tailscale? It is not clear what this extension is upon first glance.

<img width="827" alt="Screenshot 2024-10-22 at 7 50 14 AM" src="https://github.com/user-attachments/assets/24b1c08e-5476-429c-8c3e-c01fec2aaf5a">
<img width="827" alt="Screenshot 2024-10-22 at 7 50 08 AM" src="https://github.com/user-attachments/assets/e2ccc471-cd3c-4553-be9d-83cbfc90741f">
<img width="372" alt="Screenshot 2024-10-22 at 7 49 54 AM" src="https://github.com/user-attachments/assets/293577d7-841f-44b1-8a73-745f74c97dde">

### Steps to reproduce

1. Install Tailscale on MacOS
2. Click the icon in the bar at the top-right, and select "System extension approval required"
3. Click "open settings"
4. Navigate to General --> Extensions --> Network Extensions, and click the (i) icon next to "IPNExtension"
5. Click the toggle slide to enable the extension (though I'm still having issues with it not actually working)

### Are there any recent changes that introduced the issue?

None that I'm aware of.   I can't run the bugreport command as I don't have the tailscale binary installed - I installed using the .pkg installer.

### OS

macOS

### OS version

MacOS Sequoia 15.0.1

### Tailscale version

1.76.1

### Other software

I'm not sure which application would contribute to this issue, but I've attached a system information report of all installed applications as a .PDF

[Installed_applications.pdf](https://github.com/user-attachments/files/17476867/Installed_applications.pdf)

**Comment by agottardo** [comment]
Thanks for the report, we have fixes landing soon in unstable for both these issues.

**Comment by agottardo** [comment]
Fixed in v1.77.34.

**Comment by kmanwar89** [comment]
Thanks @agottardo  - any ETA on when that version will be released, or is there an early access/beta I can test to validate the fix? Thanks!

**Comment by agottardo** [comment]
It is already available on pkgs.tailscale.com.

**Comment by kmanwar89** [comment]
I just tested this and the changes are MUCH better, thank you for getting this addressed!
