### ISSUE TITLE
Tailscale Fails on PC Boot: last login error=fetch control key x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dsposito** [tailscale/tailscale#13886]
### What is the issue?

On PC boot up, the tailscale client fails to connect to the control plane:
not logged in, last login error=fetch control key: Get "https://controlplane.tailscale.com/key?v=82": x509: certificate signed by unknown authority

This issue only occurs on boot up if I'm connected to a specific WiFi network. If tailscale is successfully running and I switch to the troublesome customer WiFi network afterwards then the tailscale network continues to function fine - even if tailscale client is restarted.

### Steps to reproduce

- Connect to my customer's WiFi network at a facility on my Linux PC
- Reboot PC
- Run `tailscale status` to see the error above
- Connect to a different, public WiFi network
- run `sudo tailscale up` (this will work)
- Switch back to the customer's private WiFi network
- Run `sudo tailscale down` and `sudo tailcale up` (tailscale network continues to work fine)

### Are there any recent changes that introduced the issue?

Is there anything I can configure for my tailscale install to bypass this issue? For example, I tried using the flag `sudo tailscale up --accept-risk all` but no luck.

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.56.1

### Other software

No additional networking, firewall, etc sw is setup on my PC. It's just vanilla Ubuntu 20.

### Bug report

BUG-0fcd7c04fd8d36ed5b9f50d3611d9b1ddd5118352fd368bcfff2aa78fbd4b484-20241022194106Z-ac16b4190022f633

**Comment by agottardo** [comment]
That means the Wi-Fi is tampering with the HTTPS connection, most likely to block Tailscale. Open `https://controlplane.tailscale.com/key` in a browser and check whether you're able to load it or not.

**Comment by dsposito** [comment]
@agottardo Thanks for your response. When I load `https://controlplane.tailscale.com/key` on the browser while connected to the specific WiFi network it does not trust the SSL cert.

![image](https://github.com/user-attachments/assets/384fa481-b750-45ed-a3d1-58e7c001b804)

Are there any specific network/firewall configs I should mention when I reach out to the IT team? I will share the above info with them.

**Comment by agottardo** [comment]
I recommend looking at the details of the SSL certificate in Chrome and in particular the issuer name, it can reveal the manufacturer of the equipment that is performing the blocking. A common one is Fortinet.

Just ask your IT admin to allow any connections to *.tailscale.com on any port.

**Comment by geekeritcom** [comment]
> I recommend looking at the details of the SSL certificate in Chrome and in particular the issuer name, it can reveal the manufacturer of the equipment that is performing the blocking. A common one is Fortinet.
> 
> Just ask your IT admin to allow any connections to *.tailscale.com on any port.

It's work for me,the company IT admin block the domain *.tailscale.com,Tks
