### ISSUE TITLE
wgengine: pinger does not find right peer IP

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#139]
```
tailscaled[25860]: ERROR: peer [pub:…ubek] has unexpected AllowedIPs: [{10.2.0.0 fffffc00} {100.90.141.72 ffffffff}]
```

Note the CGNAT address comes last. We were assuming (in wgengine/userspace.go:174) that the IPs come out in the AllowedIPs order of the config file, but instead they come out in the order the trie gives them to us in. So we need to hunt for the CGNAT address.

**Comment by apenwarr** [comment]
Side note: I would really like to minimize the number of places where our code makes assumptions about:
- 100.x addresses being a special case
- Only one /32 per node
- Only one tailscale address per node (imagine eg. an haproxy-like address that moves around)
- Any special meaning behind the order of provided addresses, routes, or subnets

It'll probably take a while to hunt down all the offending parts of the code, but hopefully we won't add any extra ones. Customers are already asking about ways to define custom or restricted subnets for their tailscale addresses.
