### ISSUE TITLE
Tailscale-cli broken  on 1.77.36 version  mac

### ISSUE THREAD

**Issue by tianshuo** [tailscale/tailscale#13920]
### What is the issue?

tailscale in command  line should work. any command, such as  `tailscale status`, `tailscale  --help`.
Doesn't work  at  all.

Outputs: `Could not dlopen extension`

### Steps to reproduce

Update to mac 1.77.36, where command line worked last  version.
Run `tailscale status` in command  line

Outputs: `Could not dlopen extension`

### Are there any recent changes that introduced the issue?

Updated to  1.77.36.

Never seen this before.

### OS

macOS

### OS version

13.6.9 (22G830)

### Tailscale version

 1.77.36

### Other software

nothhing else

### Bug report

tailscale bugreport failed.

**Comment by bradfitz** [comment]
This was discovered elsewhere and is being worked on.

/cc @tailscale/genius-bar

**Comment by agottardo** [comment]
Fixed in tailscale/corp#24129, fix will be landing to unstable soon.
