### ISSUE TITLE
Microsoft Defender claims clients that do not have mullvad VPN enabled are still reaching out to mullvad service

### ISSUE THREAD

**Issue by joshspicer** [tailscale/tailscale#13939]
### What is the issue?

I pay for the Mullvad addon for my tailnet.  I also use tailscale on my work machine, which is managed by Microsoft Intune/Microsoft Defender.  My work machine is _not_ one of the 5 devices i've "opted-in" to use mullvad. 

My IT department does not prohibit tailscale, but it does prohibit "third-party VPN providers" which included Mullvad.  When enabling tailscale client on my work machine I see the following Defender warnings:

![Image](https://github.com/user-attachments/assets/aac0cc03-5c53-4f82-a28e-68654a349518)

Since this tailscale client is not opted-in to use mullvad VPN, it doesn't seem (to me) like Tailscale should be reaching out to mullvad

![Image](https://github.com/user-attachments/assets/61c1a00d-084b-48fe-a68b-80611eb36f56)

This didn't repro before I started paying for the Mullvad add-on.  Unless I was really unlucky with the timing, it seems tat this can be avoided by not using the VPN addon.

It would be great if internally Tailscale did not reach out to mullvad, except on clients where the feature is enabled.

### Are there any recent changes that introduced the issue?

Paying for mullvad VPN.

### OS

macOS

### OS version

14.7 (23H124)

### Tailscale version

1.76.1

### Other software

Microsoft Defender

### Bug report

BUG-5d4c1b1575bd4cf6df117cae374fd192c41895d527c6567223ce0c588804874b-20241028200127Z-c24c29dc20111393

**Comment by agottardo** [comment]
I’m not aware of any component in the client that would connect to Mullvad servers if the service isn’t enabled on your account. The client should only establish one connection to a Mullvad server once you select one as the current exit node. Could you provide details on the connections you’re seeing to Mullvad servers, specifically IP addresses/hostnames and port numbers?

**Comment by joshspicer** [comment]
I've installed [Little Snitch](https://www.obdev.at/products/littlesnitch/download.html) to try and get a better idea of what is going on here.  As soon as I enable tailscale I see connections to these domains (not seeing the string `mullvad` anywhere)

![Image](https://github.com/user-attachments/assets/ce77627f-4273-4146-ac13-79258e14a289)

I also used this tool to generate a pcap of that process, and the following command to extract out destination IP address data:

```
tshark -r /Users/jospicer/Desktop/IPNExtension\ 2024-10-29\ at\ 14.59.35.pcap -T fields -e ip.dst -e tcp.dstport -e udp.dstport > mullvad-dest-ips
```

[mullvad-dest-ips.txt](https://github.com/user-attachments/files/17563603/mullvad-dest-ips.txt)


I'm not sure if Defender is blocking the requests before they would be captured by little snitch (and I don't see a way to get that information from Defender itself).  

If you have any other ideas or things that would help I try, please let me know :)

**Comment by agottardo** [comment]
I see outgoing connections in the file you attached to `194.242.2.2`, which is a Mullvad DNS server IP, on port 443, which makes me believe you're using Mullvad for DNS over HTTPS. Do you have Mullvad DNS selected as your DNS provider in the Tailscale admin console?

**Comment by joshspicer** [comment]
Ahh, I do!

I've removed that entry and so far no more Mullvad popups.  I think you've solved my problem - thank you!
