### ISSUE TITLE
FR: Tailscale not yet supported on openSUSE Leap 15.6

### ISSUE THREAD

**Issue by Budgie2** [tailscale/tailscale#13943]
### What are you trying to do?

I am trying to install Tailscale on openSUSE Leap 15.6 machine.  Please can you enable your script to work with Leap 15.6 as I have a pressing need.  I already have Tumbleweed working but not Leap 15.6.

### What is the impact of not solving this?

I am using another machine which has Tumbleweed but parts of our network are inaccessible.

### Anything else?

This should not be too difficult because Tailscale already runs on Tumbleweed

**Comment by Erisa** [comment]
Duplicate of #12541
