### ISSUE TITLE
FR: Local Only

### ISSUE THREAD

**Issue by SephReed** [tailscale/tailscale#13945]
### What are you trying to do?

I'm trying to understand Tail Scale as a service.  I was chatting with GPT.  My understanding:
- helps with setting up local networks
- tries local networks first
- has the ability to treat remote networks like they are local if it doesn't find local
- has DNS stuff too

I asked if it was possible to set something up to only allow local (same router) connections.  No remote.  GPT said no, and it confused me because I would think that's an obvious use case.  

> Yes, Tailscale allows you to control how connections are handled by adjusting settings, although you don’t have an explicit toggle for “local-only” vs. “remote-only.” Here are a couple of ways to approximate each setup:
>
> Local-Only:
>
> If you want to restrict Tailscale to only allow connections when devices are on the same local network, you could disable NAT traversal by restricting specific firewall ports or configurations, but this requires advanced network setup and could limit remote access unintentionally.
Alternatively, you could disable Tailscale on your device when off the local network, effectively preventing remote connections.
Remote-Only:
>
> To enforce remote-only connections, you could set up firewall rules or access control lists (ACLs) in the Tailscale admin panel to limit connections based on location or network conditions.
For example, you could block local network discovery if devices are reachable only through specific IP ranges, forcing connections to rely on Tailscale’s mesh even if on the same Wi-Fi.
Currently, Tailscale automatically manages this “local-first, remote-fallback” behavior, so fine-grained control requires workarounds at the network or device level rather than a built-in setting.

>You’re absolutely right; having a simple toggle for "local-only" connections within Tailscale’s settings would align well with use cases where users want easy local access without remote connectivity. However, Tailscale’s focus is on providing seamless, always-available connectivity across various networks, aiming to remove the distinction between local and remote access altogether, so devices are accessible regardless of where they are.
>
>The lack of a local-only option likely reflects this philosophy. Tailscale’s approach simplifies remote connectivity, especially for non-technical users, but the trade-off is reduced control over local vs. remote access toggling. Your suggestion of a centralized setting for local-only connections could be valuable feedback for Tailscale, as it would address a common preference for fine-grained network management in a way that aligns with user control.

### How should we solve this?

This seems like a "checkbox" kind of thing.  Disable some code if a boolean is false.

### What is the impact of not solving this?

For me, the point of the project is unintuitive.  It's a way to manage some, but not all, of my local network configurations.

### Anything else?

Have a nice day!

**Comment by awly** [comment]
https://tailscale.com/blog/how-tailscale-works is a better reference than ChatGPT.
Tailscale manages private network overlays over any type of underlying network (LAN or WAN, doesn't matter).

If you want to block connections between your nodes over Internet, please explain why.
If you're simply confused by some information that ChatGPT provides, you can submit feedback to them.

**Comment by agottardo** [comment]
Unactionable, closing issue.
