### ISSUE TITLE
Subnet routing broken on Linux 6.6.58, 6.11.4, 6.11.5 

### ISSUE THREAD

**Issue by simonctrlz** [tailscale/tailscale#13962]
### What is the issue?

Our subnet routers were patched today and with that came Linux kernel 6.11.4. Subnet routing seemingly broke.
Reverting back to Linux kernel 6.11.3 restores functionality. I've also tried 6.11.5 and 6.6.58 (LTS) for good measure with which subnet routing also does not work.

### Steps to reproduce

Run Linux kernels more recent than 6.11.3, e.g.  6.6.58, 6.11.4, 6.11.5.

### Are there any recent changes that introduced the issue?

kernel upgrade

### OS

Linux

### OS version

Fedora 40

### Tailscale version

1.76.1

### Bug report

BUG-85d3a03361a6795dc5a4ed6866a5bef095ca4fa08a04d44ce76890844cb62cd7-20241029202937Z-0e085bc3d74078a6

**Comment by shladek** [comment]
This is probably a duplicate of #13863

**Comment by simonctrlz** [comment]
Fixed with kernel `6.11.6`
