### ISSUE TITLE
Debian Stretch update: Could not resolve host: pkgs.tailscale.com

### ISSUE THREAD

**Issue by picree** [tailscale/tailscale#13972]
### What is the issue?

Unable to update from 1.74.1 to 1.76.1

### Steps to reproduce

run sudo apt-get install tailscale

### Are there any recent changes that introduced the issue?

E:  Failed to fetch https://pkgs.tailscale.com/stable/debian/pool/tailscale_1.74.1_mipsel.deb  Could not resolve host: pkgs.tailscale.com
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### OS

Linux

### OS version

Debian Stretch Linux 4.14.54-UBNT

### Tailscale version

1.74.1

**Comment by picree** [comment]
Clarification:  This is ultimately an issue with 'sudo apt-get update'.

Err:1 https://pkgs.tailscale.com/stable/debian/stretch/main stretch InRelease
  Could not resolve host: pkgs.tailscale.com
Reading package lists... Done
W: Failed to fetch https://pkgs.tailscale.com/stable/debian/stretch/main/dists/stretch/InRelease  Could not resolve host: pkgs.tailscale.com
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by bradfitz** [comment]
Do you use NextDNS or some DNS filtering software?

**Comment by picree** [comment]
I do but I have turned it all off and still get the error.  Maybe turn it off and flush the cache?

**Comment by bradfitz** [comment]
Yeah this is probably due to nextdns recently blocking us by default.

**Comment by picree** [comment]
I don't think so.  I have DNS filtering but not NextDNS.  I shutdown my DNS filtering server, changed the DNS setting to 8.8.8.8, rebooted, and it still errors out.

**Comment by bradfitz** [comment]
I don't know how to help you debug this. If it works in your browser, at least your desktop has working DNS.

Is your apt-get using apt-proxy or something and going through another machine that has borked DNS?

**Comment by picree** [comment]
Thanks for trying.  The Desktop and the Linux EdgeRouterX gateway are both using the same DNS server.  Not using apt-proxy AFAIK.  both have been restarted several times.  FWIW - I can ping pkgs.tailscale.com just fine.

**Comment by picree** [comment]
Well, on the Linux ERX I replaced this command:

set system package repository tailscale url '[signed-by=/usr/share/keyrings/tailscale-stretch-stable.gpg] https://pkgs.tailscale.com/stable/debian'

with this command:

set system package repository tailscale url '[signed-by=/usr/share/keyrings/tailscale-stretch-stable.gpg] https://199.38.181.239/stable/debian'

which is the IP from ping and the update worked.  I have no idea why the DNS is messed up though or why the URL won't work.
