### ISSUE TITLE
Windows: default route switching is unclean.

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1398]
Empirically, when Windows has multiple default routes, already established connections continue to use the default route that was initially picked, even if another default route with a better metric shows up later.

Concretely, this means that when I select a Tailscale default router in the GUI, we do everything right, the correct default route appears in the routing table... And chrome keeps using the old default route for any sockets it already has cached. You can demonstrate this trivially by loading https://ifconfig.co before switching default routers, and hitting reload after switching. Your geolocation information will still be your "previous" information, because Chrome is reusing a cached socket. If you then load chrome://net-internals and flush the socket pool, a further refresh will now show the correct IP information.

After a quick search, I couldn't find any way to tell the Windows network stack "hey, break all existing connections", or a way to make it behave more like linux, where routing changes take effect on a per-packet basis immediately (causing differently-weird behavior).

Looking around, we do the same route programming as wireguard-windows, but wireguard-windows additionally installs a firewall that blocks all outbound traffic that doesn't go over the wireguard interface. It seems this is sufficient to break existing connections and have everything switch over. Unfortunately, I don't think we can use that technique, because it may not be correct for us to force _all_ traffic into the tailscale interface when a default route is selected.

I don't know what to do about this. As-is, Windows's empirical behavior makes our default routing pretty terrible, so we do need to do something about it.

**Comment by danderson** [comment]
cc @bradfitz @crawshaw @apenwarr, any ideas? I recall we used to make chrome freak out with ERR_NETWORK_CHANGED errors constantly, and did... something to make that stop. Anyone remember what it was? We may need to bring that back when manipulating default routes.

**Comment by danderson** [comment]
A quick terrible idea before bed: https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/delete-active-connections-from-local-computer

**Comment by danderson** [comment]
Last update tonight for real, I think I found it: https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-flushippathtable

No docs say what the IP Path Table is, but the struct defs look an awful lot like a conntrack entry with a cached interface LUID. Hoping that flushing that will do the right thing.

**Comment by crawshaw** [comment]
Why is it not correct for us to force all traffic through the interface when a default route is set?

**Comment by danderson** [comment]
I should have said: in our current implementation, without significant unplanned work, that's how windows behaves. We can make it differently broken by implementing what wireguard-windows does, but not make it do what we want.

We can talk about making windows do what we want (possible, but annoyingly hard), in a separate bug that should also cover the BSDs, linux sans policy routing, and what iOS/macOS/android do. We haven't done a good job of providing a consistent experience there, to date.

**Comment by danderson** [comment]
No luck with flushing the IP path table, Chrome/Edge continue to use the old default route for cached sockets.

At this point, I'm out of ideas. It seems to me like network change detection should be making chrome do the right thing, but it's really not.

Things tried:
 - Install /1 routes instead of /0. No change.
 - Flush IP path table. No change.

The problem only happens when the desired default route jumps between interfaces. Switching from tailscale to !tailscale results in delays until the cached sockets time out, at which point the browsers retry and everything works out. Switching from !tailscale to tailscale, the cached sockets continue using the !tailscale route.

**Comment by bradfitz** [comment]
Query all open TCP/UDP connections via https://pkg.go.dev/tailscale.com/net/netstat#Get and then nuke them all with [SetTcpEntry](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-settcpentry) (ala http://wkillcx.sourceforge.net/)?

**Comment by danderson** [comment]
Wow, that's metal. I guess so.

BTW, my current hypothesis is that the active connections have been assigned a source address, and that source addr is constraining route selection. Netstat's a good way to check on that.

**Comment by danderson** [comment]
Bad news: SetTcpEntry only works on IPv4, and there is no corresponding IPv6 API. Yeah, seriously.

So, afaict, and assuming that it actually works, the "firewall killswitch" option is the only thing we can do. Going to test that out and see if that even works.

**Comment by danderson** [comment]
Some notes as I run out of smart for today.

wireguard-windows addresses this issue by setting up a firewall to block non-vpn traffic. I can't use its firewall package directly because it hardcodes some assumptions about the wg-windows application, which results in config errors. That said, we can definitely adapt the code (and maybe make a Go package for manipulating the Windows firewall? That would be a really useful thing to have...).

Out of curiosity, I installed another VPN service to see how it behaves on start/stop, and its behavior is consistent with firewall-based route control: established sockets in chrome/edge hang and timeout if they were established before VPN bringup, so after you start the VPN there's a little dead air while the browsers all notice that things have moved around. Based on that, there doesn't seem to be any silver bullet for this, the solution truly seems to be "make existing connections time out/fail, so that when the apps retry they get the correct route."

**Comment by bradfitz** [comment]
Random idea: Microsoft loves IPsec, and I'd like to believe that Microsoft has found/fixed this same problem for when an IPsec tunnel is enabled. Maybe internally when IPsec is enabled, Windows kills all other connections. Could we turn IPsec on & off for a second just for the side-effect of the connection nuking?

&lt;/longshot>

**Comment by bradfitz** [comment]
> Bad news: SetTcpEntry only works on IPv4, and there is no corresponding IPv6 API. Yeah, seriously.

Other random idea: still use SetTcpEntry for IPv4 entries (to make a quick clean break), but do something else with IPv6: either the firewall thing (where apps need to time out), or could we toggle IPv6 off & on on the whole system to break those connections?

**Comment by danderson** [comment]
Going to focus on the firewall thing for now, because it seems to be a sure bet and how everyone else does it - which also suggests to me there are no better options around.

IPSec: no idea how to toggle that programmatically. I wouldn't be surprised if it also just did the wrong thing for default routes, honestly. Microsoft's attraction to ipsec is e2e between hosts, rather than in a hub-and-spoke setup.

Toggle IPv6: afaik, windows doesn't have a global "turn ipv6 off" knob, it's a per-adapter setting. We could try toggling stuff, but to address things in both ways we'd have to start messing with network adapters we don't own, which feels like a risky thing.
