### ISSUE TITLE
Windows: router configuring interface with no IPv4 address

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1399]
Seen in the logs of a Windows 1.4.5 device. Its netmap has a standard CGNAT-range address and several peers:

```
router: ConfigureInterface: Due to a Windows limitation, one cannot have interface routes without an interface address
```

This error comes from wgengine/router, and it looks like it means the router.Config passed in has routes but no LocalAddr set.

cc @bradfitz @danderson

**Comment by crawshaw** [comment]
I don't really see a pathway here. router.Config.LocalAddrs is filled from netmap.Addresses (via wgcfg). So to see that error message, we should see a netmap with an empty Addresses field. But I can't find any logs that match that.

**Comment by bradfitz** [comment]
I bet the IPv4 address family is still being initialized on the adapter. It gets available later. This early boot? Logid and time?

Cc @peske

**Comment by danderson** [comment]
Mat also be a v6 default route issue I found last night, though that would require people trying to advertise a v6 route in that tailnet

**Comment by sarahhodne** [comment]
Coming here from [the community forum](https://forum.tailscale.com/t/tailscale-on-windows-not-connecting-and-getting-169-254-0-0-16-ip/424), I think I may be (one of) the people affected by this.

> Mat also be a v6 default route issue I found last night, though that would require people trying to advertise a v6 route in that tailnet

I had just added a v6 route when this started happening, but didn't connect the dots. Disabled the route in the admin console and within seconds my Windows machine now has an IP address on the Tailscale interface and everything seems to work again. So I think that's what caused it for me.

**Comment by bradfitz** [comment]
Assigning to @danderson because he's either recently fixed this or was at least just in this area.

**Comment by peske** [comment]
Chances are that this one is solved when we implemented waiting for interface to come up (https://github.com/tailscale/tailscale/commit/daf6de4f14cc898bb59932e927e946fd8b9ca4bf). But let's see if anyone will report it again...

**Comment by danderson** [comment]
I think some fixes I made to support IPv4 or IPv6 being unavailable may have fixed this, at least partially. Moving to Done but keeping open to monitor.

**Comment by DentonGentry** [comment]
Noting for the next time bugs are scrubbed: if there are no further reports, we should close this.

**Comment by fairbanksm** [comment]
I might be having this issue too.  I'm having an issue that seems very similar to what @sarahhodne posted in the forum, which is what lead me here.  Running Tailscale v1.6.0 on Win 10.  Any time I reboot the machine, tray icon shows connected, but I get a 169.x.x.x IP address.  If I tell the client to disconnect and reconnect, everything comes back fine.  Nothing obvious in event viewer, not sure where to find the logs mentioned above though.

**Comment by ankitkk** [comment]
Just ran into this. Solution from @megdotnet worked for me.

**Comment by megdotnet** [comment]
@ankitkk I would call what I did a workaround not a solution, but I'm glad it helped.

**Comment by crawshaw** [comment]
Moving this from 1.10 because this is an intermittent issue that's been happening since 1.4, with no obvious leads. But I'll take some time to try and reproduce during the 1.12 cycle.

**Comment by DentonGentry** [comment]
This hasn't been reported nor noticed for a year and a half, and we've made several changes in wintun and the plumbing of interfaces. Barring further updates, we'll expect to close this during the next regular bug scrub.
