### ISSUE TITLE
tailscaled install-system-daemon broken on new M1 MacBook install

### ISSUE THREAD

**Issue by zachlatta** [tailscale/tailscale#1400]
**Describe the bug**
On a new M1 MacBook Air install, I attempted to follow the directions in https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS to get an M1-native build of Tailscale running.

Everything worked until running `$ sudo tailscaled install-system-daemon`, where I got the following error:

```
$ sudo tailscaled install-system-daemon

open /usr/local/bin/tailscaled.tmp: no such file or directory
```

I noticed that the `/usr/local/bin` directory didn't exist. I was able to fix this bug by creating that directory with `sudo mkdir /usr/local/bin` and then running the `install-system-daemon` command again.

**To Reproduce**
1. Have a fresh macOS install on an M1 MacBook Air (no Homebrew yet)
2. Run `sudo tailscaled install-system-daemon` from https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS
3. See error

**Expected behavior**
No error.

**Version information:**
 - Device: M1 MacBook Air
 - OS: macOS
 - OS version: Big Sur 11.1
 - Tailscale version: `date.20210218 go version: go1.16`

**Comment by bradfitz** [comment]
Thanks! Will fix.
