### ISSUE TITLE
Tailscale DNS in Windows 11 breaks docker compose in WSL 2

### ISSUE THREAD

**Issue by steveiliop56** [tailscale/tailscale#14010]
### What is the issue?

Hello,
I noticed that for some reason when I turn on the Tailscale DNS feature under the preferences menu on the Windows GUI, the docker compose plugin on my WSL 2 instance running Debian fails every single time with IO timeout errors. Nothing else is affected in the instance except the compose plugin. For example if I run a docker container using the `docker run` command or pull an image with the `docker pull` command everything works perfectly, but when I go to my compose project and run `docker compose pull` or `docker compose up` after 10 seconds it will fail with an IO timeout. I installed docker using the official install script (`curl -fsSL get.docker.com`).

### Steps to reproduce

1. Install Tailscale on a Windows 11 machine
2. Make sure you are using Tailscale DNS in the preferences menu of the Windows GUI
3. Install a WSL 2 distro (I have tested both Ubuntu and Debian)
4. Make sure `systemd` is enabled for the docker daemon to start, check [here](https://learn.microsoft.com/en-us/windows/wsl/systemd)
5. Install docker with `curl -fsSL get.docker.com | sh`
6. Verify regular docker works with `docker run hello-world`
7. Go to a docker compose project and run `docker compose pull` or `docker compose up` 
8. After around 10 seconds it will fail with an error like `Error response from daemon: Head "https://registry-1.docker.io/v2/library/traefik/manifests/v3.0": dial tcp: lookup registry-1.docker.io on 10.255.255.254:53: read udp 10.255.255.254:42939->10.255.255.254:53: i/o timeout`

### Are there any recent changes that introduced the issue?

I am not really sure, it worked perfectly fine before like 1-2 months so something broke very recently.

### OS

Windows, Other

### OS version

Windows 11 23H2 (OS Build 22631.4317) and Debian 12 on WSL2 `5.15.153.1-microsoft-standard-WSL2`

### Tailscale version

v1.76.3-t02acaa00e-g551df6588

### Other software

I have configured in my Tailscale Admin dashboard to use my AdGuard instances for global nameservers and have the override local DNS option set to true. AdGuard isn't the problem because a) I have tried disabling it and still have the same issue b) all the other machines with docker compose work perfectly.

### Bug report

BUG-1038ca6e8dede01b19930694e73cb55c5a44f72302a9cfbe04e6813c2997d380-20241103161304Z-1bc102ed74afcb8d

**Comment by steveiliop56** [comment]
It was AdGuard.

**Comment by cameronj86** [comment]
> It was AdGuard.

Do you remember what the issue was? I'm running Debian on my server & routing all traffic through AGH myself w/o issue for months and suddenly all of the containers have lost internet connectivity
