### ISSUE TITLE
Default route UI for android

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1401]

**Comment by bradfitz** [comment]
@eliasnaur, Tailscale 1.6 will let you route all your non-Tailscale traffic out one of your Tailscale node (like a traditional VPN).

We haven't decided a UI yet, but something like this perhaps:

![screenshot](https://user-images.githubusercontent.com/2621/109227382-1446df00-7775-11eb-9810-31337cd577f6.png)

Can you do something appropriate for Android?

(with one menu item being "Off (Local)" or equivalent)

Ultimately you need to set a pref. Here's how the CLI does it for `tailscale up`:

https://github.com/tailscale/tailscale/blob/ebf3f2fd9f5760b3cd7a143529e95c385d8b9aec/cmd/tailscale/cli/up.go#L225

**Comment by eliasnaur** [comment]
I've implemented this on the `tailscale-1.6` branch, using tailscale tip. See below for implementation details.

How do I coordinate the release with you? Will you notify me when 1.6 is out?

I couldn't get route-all-traffic to work between my Android emulator and Pixel device. Is the feature supposed to work yet? If so, I can dig deeper and provide logs if they're helpful.

I opted for integrating the feature in the peer list that is always displayed anyway. A default route is selected by tapping one of your peers:

![2021-02-28-131008_grim](https://user-images.githubusercontent.com/524812/109418067-b3aee080-79c6-11eb-92be-3e2c4886eae3.png)

The routing peer will be marked and appear first in the list of peers:

![2021-02-28-131016_grim](https://user-images.githubusercontent.com/524812/109418076-ba3d5800-79c6-11eb-9b89-71000e4fa400.png)

Tapping it allow you to stop routing through it:

![2021-02-28-131021_grim](https://user-images.githubusercontent.com/524812/109418094-d2ad7280-79c6-11eb-8b96-e1290ce453a1.png)

**Comment by bradfitz** [comment]
@eliasnaur, an exit node can't be used until two things happen first: a node itself has to "advertise" (offer) the route (e.g. `tailscale up --advertise-routes=0.0.0.0/0,::/0` or a simpler UI) and then a network admin has to approve the route.

@soniaappasamy, can you share your iOS video with @eliasnaur?

**Comment by soniaappasamy** [comment]
Sure - @eliasnaur this is what we have on the iOS side (note that some design details may change around a bit once @rosszurowski takes a design review)

It would be good to align our iOS and Android UX for exit nodes. @rosszurowski for thoughts on this


https://user-images.githubusercontent.com/9019214/109531540-056a7000-7a86-11eb-9bcd-860a6ea9dacd.mp4

**Comment by eliasnaur** [comment]
Ok, thanks @soniaappasamy. I'll wait for @rosszurowski to approve your design to avoid redoing the UI more than once.

**Comment by rosszurowski** [comment]
Yep. Just talking with @soniaappasamy about the design to see what the different considerations / states we need to build are. I should have something to share later today (early tomorrow EST at the latest).

**Comment by tux21b** [comment]
I personally like Elia's design more, by using the same list of peers. It looks much simpler and I do not have to scan a different list than already present on the screen. But I guess if the ratio of non-exit nodes to exit-nodes is very large, Sonia's design might be better. Otherwise I prefer the single list.

**Comment by eliasnaur** [comment]
FWIW, we could add an "exit nodes" section early in the peer list so they're easy to locate.

**Comment by rosszurowski** [comment]
@eliasnaur here's the design we're thinking for iOS. Android should follow the same general structure in a way that makes sense for Android. For example, swapping out iOS's AlertMenus for Android Menus. For the exit node picker itself, it makes the most sense to me to use a single-choice list AlertDialog, like Gmail's "Move to" feature. You know Android better than I do, and I trust your judgement on the translation. But if it'd save you time, I can prep Android specific mocks too.

<img width="3974" alt="route-traffic-via" src="https://user-images.githubusercontent.com/303731/109670128-cd743300-7b40-11eb-85a8-efbc6512a90b.png">

The notification text and exit node icons are placeholders for now, but they should be easy to swap out. I'll get you and Sonia proper versions of both of those at some point today.

**Comment by eliasnaur** [comment]
Thanks, @rosszurowski. I've implemented the iOS design for Android, sans the completed exit node icon and notification text.

However, I still can't quite get default routing to work.

I ran `tailscale up --advertise-routes 0.0.0.0/0,::/0` on my Fedora machine, and selected that machine as my Android emulator's exit node. `ping google.com` inside `adb shell` works, but unfortunately Chrome reports that google.com is unreachable.

I'm pretty sure `ping` is routed through my machine, because `echo 0 | sudo tee /proc/sys/net/ipv4/ip_forward` blocks it, and `echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward` unblocks it.

Perhaps my Linux tailscale (1.4.4) is simply too old act as default router?

Android's routing table when default routing is enabled:

```
$ ip route show table 0                                                                                                                                   
default dev tun0 table 1217 proto static scope link 
100.72.96.110 dev tun0 table 1217 proto static scope link 
100.75.238.88 dev tun0 table 1217 proto static scope link 
100.79.134.64 dev tun0 table 1217 proto static scope link 
100.81.132.94 dev tun0 table 1217 proto static scope link 
100.89.247.103 dev tun0 table 1217 proto static scope link 
100.99.151.70 dev tun0 table 1217 proto static scope link 
100.100.100.100 dev tun0 table 1217 proto static scope link 
100.101.102.103 dev tun0 table 1217 proto static scope link 
default dev dummy0 table 1002 proto static scope link 
default via 10.0.2.2 dev wlan0 table 1015 proto static 
10.0.2.0/24 dev wlan0 table 1015 proto static scope link 
default via 10.0.2.2 dev radio0 table 1017 proto static mtu 1500 
10.0.2.0/24 dev radio0 table 1017 proto static scope link 
10.0.2.0/24 dev radio0 proto kernel scope link src 10.0.2.15 
10.0.2.0/24 dev wlan0 proto kernel scope link src 10.0.2.16 
broadcast 10.0.2.0 dev radio0 table local proto kernel scope link src 10.0.2.15 
broadcast 10.0.2.0 dev wlan0 table local proto kernel scope link src 10.0.2.16 
local 10.0.2.15 dev radio0 table local proto kernel scope host src 10.0.2.15 
local 10.0.2.16 dev wlan0 table local proto kernel scope host src 10.0.2.16 
broadcast 10.0.2.255 dev radio0 table local proto kernel scope link src 10.0.2.15 
broadcast 10.0.2.255 dev wlan0 table local proto kernel scope link src 10.0.2.16 
local 100.79.134.64 dev tun0 table local proto kernel scope host src 100.79.134.64 
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 
fd7a:115c:a1e0:ab12:4843:cd96:6248:606e dev tun0 table 1217 proto static metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:624b:ee58 dev tun0 table 1217 proto static metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:624f:8640 dev tun0 table 1217 proto kernel metric 256 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:624f:8640 dev tun0 table 1217 proto static metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:6251:845e dev tun0 table 1217 proto static metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:6259:f767 dev tun0 table 1217 proto static metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:6263:9746 dev tun0 table 1217 proto static metric 1024 pref medium
fd7a:115c:a1e0:ab12:4843:cd96:6265:6667 dev tun0 table 1217 proto static metric 1024 pref medium
fe80::/64 dev tun0 table 1217 proto kernel metric 256 pref medium
default dev tun0 table 1217 proto static metric 1024 pref medium
fe80::/64 dev dummy0 table 1002 proto kernel metric 256 pref medium
default dev dummy0 table 1002 proto static metric 1024 pref medium
fe80::/64 dev wlan0 table 1015 proto kernel metric 256 pref medium
fe80::/64 dev wlan0 table 1015 proto static metric 1024 pref medium
fec0::/64 dev wlan0 table 1015 proto kernel metric 256 expires 86246sec pref medium
fec0::/64 dev wlan0 table 1015 proto static metric 1024 pref medium
default via fe80::2 dev wlan0 table 1015 proto ra metric 1024 expires 1646sec hoplimit 64 pref medium
fe80::/64 dev radio0 table 1017 proto static metric 1024 pref medium
fec0::/64 dev radio0 table 1017 proto static metric 1024 pref medium
default via fe80::2 dev radio0 table 1017 proto static metric 1024 mtu 1500 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local fd7a:115c:a1e0:ab12:4843:cd96:624f:8640 dev tun0 table local proto kernel metric 0 pref medium
local fe80::486:76ff:fe29:6624 dev radio0 table local proto kernel metric 0 pref medium
local fe80::1020:5f8f:8306:5f85 dev tun0 table local proto kernel metric 0 pref medium
local fe80::6055:12ff:feb3:759b dev dummy0 table local proto kernel metric 0 pref medium
local fe80::7c59:4202:24fd:2512 dev wlan0 table local proto kernel metric 0 pref medium
local fec0::486:76ff:fe29:6624 dev radio0 table local proto kernel metric 0 pref medium
local fec0::5098:ac10:8ef2:814e dev wlan0 table local proto kernel metric 0 pref medium
local fec0::55da:dc3e:6243:851b dev wlan0 table local proto kernel metric 0 pref medium
local fec0::a901:d2a4:d8a:3283 dev radio0 table local proto kernel metric 0 pref medium
local fec0::ec42:c168:9a17:cb1a dev radio0 table local proto kernel metric 0 pref medium
ff00::/8 dev dummy0 table local metric 256 pref medium
ff00::/8 dev radio0 table local metric 256 pref medium
ff00::/8 dev wlan0 table local metric 256 pref medium
ff00::/8 dev tun0 table local metric 256 pref medium
```

**Comment by bradfitz** [comment]
@eliasnaur, I see in our debug admin panel that your Fedora 33 (themachine) has IP forwarding disabled at the kernel level.

See the sysctl notes at https://tailscale.com/kb/1019/subnets

**Comment by eliasnaur** [comment]
Are you sure you didn't look while I experimented with toggling it while writing my previous message? `cat /proc/sys/net/ipv4/ip_forward` says `1` now.

**Comment by bradfitz** [comment]
I still see it. I bet this is wrong for you, as it is for me by default:

```
# sysctl -n net.ipv6.conf.all.forwarding
0
```

@danderson, I imagine we'll want to update that subnets KB article, eh?

/cc @rosszurowski @darshinimashar

**Comment by eliasnaur** [comment]
I enabled ipv6 forwarding; still doesn't work. Besides, I'm pretty sure my internet provider doesn't assign an IPv6 address to me.

```
$ sysctl -n net.ipv6.conf.all.forwarding
1
$ sysctl -n net.ipv4.conf.all.forwarding
1
```

**Comment by bradfitz** [comment]
For the purposes of this, it doesn't matter if you have a working global IPv6 connection.

**Comment by bradfitz** [comment]
@eliasnaur, did you restart tailscaled after changing the sysctl?

**Comment by rosszurowski** [comment]
> I imagine we'll want to update that subnets KB article, eh?

Sure. Is it just a matter of adding the 0→1 change for `/proc/sys/net/ipv6/conf/all/forwarding`? I can make that update.

> I still can't quite get default routing to work.

I'll leave this for @bradfitz and @danderson, since I'm probably not much help debugging this.

> I've implemented the iOS design for Android, sans the completed exit node icon and notification text.

Perfect! For the icon and notification text, here's an updated design:

<img width="3974" alt="default-routes-ui" src="https://user-images.githubusercontent.com/303731/109879778-0943f100-7c44-11eb-92da-0e0643ef6699.png">

And here's the "menu" icon used in the banner: [list.zip](https://github.com/tailscale/tailscale/files/6079542/list.zip)

After trying to design an icon that communicated everything we need, we realized there's too much info to share with solely an icon. We were also concerned the icon wasn't prominent enough for such a big, temporary behavior change. So instead of an icon, we have a tap-able banner to indicate if a default route is being used, or if there's an error. This notification copy is now safe to use too.

We may need to tweak the terminology (is this a default router? traffic router? exit node? something else?) to align with the other platforms before launch, but the rest of the design should be stable.

Tag me as a reviewer on the PR when you put it up!

**Comment by eliasnaur** [comment]
> @eliasnaur, did you restart tailscaled after changing the sysctl?

Restarted both Linux and Android machines, made sure both ipv4 and ipv6 forwarding set to 1 before starting tatilscaled. No luck.

**Comment by eliasnaur** [comment]
@rosszurowski, I've added you as reviewer for the PR that implements your final design.

**Comment by DentonGentry** [comment]
I was able to build an Android debug APK using the code in https://github.com/tailscale/tailscale-android/pull/7, and signed in to a Tailnet with a node offering routes to 0.0.0.0/0,::/0

Nifty.

----

### **Menu selection to Route Traffic Via:**
![RouteTrafficVia](https://user-images.githubusercontent.com/1140756/110864562-2b0e2b00-8277-11eb-9955-81122f80aed5.png)

----

### **Selecting the node to route via:**
![RouteTrafficViaSelection](https://user-images.githubusercontent.com/1140756/110864581-31040c00-8277-11eb-93d5-db6b2910fc5c.png)

----

### **Relaying through that node:**
![RelayingTraffic](https://user-images.githubusercontent.com/1140756/110864585-319ca280-8277-11eb-95af-38fd5575f2f8.png)

----

### **Disabling Routing via the node:**
![DisableRouteTrafficVia](https://user-images.githubusercontent.com/1140756/110864588-319ca280-8277-11eb-985b-b40a4125519e.png)

----

I think I am running into some weird things related to using a FreeBSD system as the exit node, which affect my MacOS laptop (and clearly unrelated to the Android build I'm running). I'll try again using a Linux system as the exit node.

**Comment by DentonGentry** [comment]
After turning off the FreeBSD system and using an Ubuntu system to advertise routes to 0.0.0.0/0,::/0

I think default route is working for me, at least for IPv4. I've turned off Wi-fi on this phone, to make it use LTE. whatismyipaddress.com says my phone is 2607:fb90:X:X:X:X:X:X and 172.58.X.X.

2607:fb90 and 172.32.0.0/11 are T/Mobile IP ranges.

When I enable routing via my Ubuntu machine in the Tailscale app, whatismyipaddress.com says my IPv4 address is 135.180.X.X, and that IPv6 is not detected.

135.180.X.X is my sonic.net address, so the phone went over LTE to get to the house to the Ubuntu machine to route it back out.

IPv6 being broken is weird, I'll look into that more.

**Comment by DentonGentry** [comment]
With Tailscale disconnected, using the Wi-Fi in the house, https://ipv6test.google.com/ says that I have an IPv6 address.

With Tailscale connected but not using an exit node, using the Wi-Fi in the house, https://ipv6test.google.com/ says that I have an IPv6 address.

With Tailscale connected and using the Ubuntu system as an exit node, using the Wi-Fi in the house, https://ipv6test.google.com/ says that I do not have an IPv6 address.

**Comment by eliasnaur** [comment]
Indeed I had problems getting the exit node to work (macOS). So what I meant is that the UI is ready, and I assume the remaining problem(s) is fixed in a Tailscale module upgrade.

**Comment by DentonGentry** [comment]
Yes. It is quite late here now, we expect to work on this tomorrow.
