### ISSUE TITLE
tailscale status "health check" section failing with missing kernel module error on Fedora 41

### ISSUE THREAD

**Issue by pghpete** [tailscale/tailscale#14018]
### What is the issue?

**Fedora 41
Kernel 6.11.5-300.fc41.x86_64
tailscale-1.70.0-1
tailscale-1.76-1-1**

When you run `tailscale status` the health check section fails with the following error in regards to the ip6tables command...

```
# Health check:
#     - adding [-i tailscale0 -j MARK --set-mark 0x40000/0xff0000] in v6/filter/ts-forward: running [/usr/sbin/ip6tables -t filter -A ts-forward -i tailscale0 -j MARK --set-mark 0x40000/0xff0000 --wait]: exit status 2: Warning: Extension MARK revision 0 not supported, missing kernel module?
ip6tables v1.8.10 (nf_tables): MARK: bad value for option "--set-mark", or out of range (0-4294967295).

Try `ip6tables -h' or 'ip6tables --help' for more information.
```

### Steps to reproduce

Simply run `tailscale status` on a tailscale host and you will see the error at the bottom in the 'health check'  secton.

### Are there any recent changes that introduced the issue?

I did upgrade from Fedora 40 to Fedora 41 a few days ago. I tried to downgrade the tailscale package from 1.76 to 1.70 but had the issue on both versions.

### OS

Linux

### OS version

41

### Tailscale version

1.76

**Comment by irbekrm** [comment]
This seems to be the same as https://github.com/tailscale/tailscale/issues/13863

**Comment by pghpete** [comment]
@irbekrm ah, ty. Looks like I need to improve my searching skills. :)

Thanks for your assistance. Reading that other thread it was solved upstream in Fedora Kernel 6.11.6.  The currently available kernel for Fedora 41 is 6.11.5 so it appears I may need to wait a bit until the newer kernel is available for general release.

Appreciate your assistance.

**Comment by Procsiab** [comment]
Today updating to kernel 6.11.6 fixed this issue for me (Fedora 41 Workstation)

**Comment by pghpete** [comment]
Updating this morning to the kernel mentioned solved the issue for me. TY!
