### ISSUE TITLE
Q: Using `cmd/testwrapper` as a third-party CLI

### ISSUE THREAD

**Issue by agis** [tailscale/tailscale#14030]
Not sure if this belongs here, since it's merely a question, not a bug report.

So, https://github.com/golang/go/issues/62244 brought my attention to the `testwrapper` utility you use. Then, I've figured I could use that in my job's own project (private GH repo).

But before doing that, I wanted to make sure that this is a good idea. I guess there are no stability guarantees, since it's not actually meant to be consumed by third parties (or is it?). Bearing that in mind, are there any other caveats I should be aware of, if I import it as a package in my own CI?

Thanks in advance!

**Comment by icio** [comment]
You seem to be aware of the main caveats and status of testwrapper. If you're going to make use of it at your company, please be aware that we're not likely to offer the same level of support to them as we will to users of the actual Tailscale product. You might want to consider just copy-pasting it into your project to make the separation clear.

I feel on this topic there always needs to be a voice saying: you should actually double-check if you can fix the flakes first, and run the tests with `-race` to help. You should be wary that real racey test failures will be obscured by having these kinds of retry in place -- everyone makes mistakes and that will include marking real test failures as flakes, overall contributing to lower quality 

But with that said - if you just need a couple of understood test failures to be retried, testwrapper can do that for you, and yes we do it too. Hope it helps and don't forget to adopt whatever comes out of https://github.com/golang/go/issues/62244 when it ships 👍

**Comment by icio** [comment]
https://github.com/golang/go/issues/62244
