### ISSUE TITLE
Build DERP,not available on android side

### ISSUE THREAD

**Issue by Eacgh** [tailscale/tailscale#14041]
Build DERP,not available on android side
![Screenshot_20241108_163648](https://github.com/user-attachments/assets/0fbf5045-ee3d-4589-a886-2b09021b92ac)

**Comment by raggi** [comment]
This screenshot shows a health warning that a custom DERP could not be reached.

There are no logs here, no diagnostic information, and not even a description of the environment or a problem statement.

We can't proceed with this bug as-written.
