### ISSUE TITLE
Wrong information in documentation / KB for windows subnet router

### ISSUE THREAD

**Issue by Mereck13579** [tailscale/tailscale#14055]
### What is the issue?

On this page: [https://tailscale.com/kb/1019/subnets?tab=windows#connect-to-tailscale-as-a-subnet-router](https://tailscale.com/kb/1019/subnets?tab=windows#connect-to-tailscale-as-a-subnet-router)

Windows instructions for connecting tailscale as a subnet router are the same as macOS, asking to use sudo tailscale up which obviously won't work on Windows...

### OS

Windows

**Comment by kelivel** [comment]
Thanks for reporting this! I've created an internal issue with our Docs team and we'll make sure to get an update out.
