### ISSUE TITLE
Fallback DNS mechanism for Tailscale startup

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1405]
Often times a client fails to start up because its DNS is broken for a handful of reasons. (e.g. #1403) It's big enough that we see dips in our connected user graphs after macOS updates. We've also had a number of support requests about this.

Some potential solutions:

(a) hard-code the `login.tailscale.com` etc IP address(s), but that's scary if we have to move IP addresses and clients in the field are not updating and using an old version. (Arguably it's less scary if we only hard-code an IP address as a fallback, still preferring system DNS if available.)

(b) have clients locally cache a previous DNS lookup for `login.tailscale.com` etc on disk to use as a fallback if a later startup fails (e.g. after a macOS App Store update). This assumes the DNS works the very first time they ran Tailscale, which is a pretty safe assumption considering they just downloaded it. But this doesn't fix the very first macOS update. We'd still a bunch of stuck users (again), because the cache file doesn't exist on disk yet.

(c) hard-code a well-known public DNS server into the Tailscale client and fall back to that when the system DNS is broken. Hard-coding 8.8.8.8 or 1.1.1.1 as a fallback DNS server would probably be fine in a different market, but it's not universally popular with the sort of network/security folk who use Tailscale.

(d) like (c), but instead of hard-coding 8.8.8.8 or 1.1.1.1 or other popular DNS server, instead use our DERP fleet of IPs. We'd still bake in a dozen (hostname,IP)s into the client, but the client can randomly try them, doing an HTTPS DNS lookup over them, including verifying TLS certs, until one works.

From talking with @crawshaw, it sounds like the top contenders are (b) and/or (d).

**Comment by DentonGentry** [comment]
Noting for next time bugs are scrubbed: I think https://github.com/tailscale/tailscale/pull/1407 resolved this, and notification of remaining failures we cannot recover from is tracked in https://github.com/tailscale/tailscale/issues/1415
If there are no further comments, this can be closed on the next scrub.

**Comment by bradfitz** [comment]
This shipped so I think it's safe to close. If there are problems with it, we'll open new bugs to address.
