### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by Stonecroissant** [tailscale/tailscale#14050]
### What is the issue?

Tailscale crashes on first launch after pressing 'Get Started,' and after that, it crashes on launch.

### Steps to reproduce

Install from the Play Store, launch the app, press 'Get Started,' and the app crashes.

### OS

Android

### OS version

Android 11

### Tailscale version

1.76.2

### Other software

Magisk 27007

**Comment by bradfitz** [comment]
Got `adb logcat` output as it crashes?

**Comment by Stonecroissant** [comment]
How can I output it here?

**Comment by bradfitz** [comment]
Paste the relevant part, or attach a text file or zip file to the comment.

**Comment by craftxbox** [comment]
Encountering the same issue for a few weeks now.
Google Pixel 3 running LineageOS 21 (android 14) and Magisk 27007. Tailscale version 1.76.1-t24929f6b6-ga20b1114dd5 installed via FDroid

Here's the logcat I pulled:
[tailscale.txt](https://github.com/user-attachments/files/17686342/tailscale.txt)

**Comment by Stonecroissant** [comment]
[logcat.txt](https://github.com/user-attachments/files/17687973/logcat.txt)

**Comment by bradfitz** [comment]
The crash is:

```
11-09 00:53:08.994  3231  3231 E AndroidRuntime: FATAL EXCEPTION: main
11-09 00:53:08.994  3231  3231 E AndroidRuntime: Process: com.tailscale.ipn, PID: 3231
11-09 00:53:08.994  3231  3231 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}; have you declared this activity in your AndroidManifest.xml?
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2256)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5326)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at c.l.startActivityForResult(SourceFile:2)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at c.k.b(Unknown Source:273)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at f.f.Q(Unknown Source:101)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at g4.O.k(Unknown Source:16)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at f4.u0.a(Unknown Source:28)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at f4.n0.x(Unknown Source:9)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at n4.a.k(Unknown Source:8)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at P5.L.run(Unknown Source:114)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at w0.Q.T(Unknown Source:23)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at w0.P.run(Unknown Source:2)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8035)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
11-09 00:53:08.994  3231  3231 E AndroidRuntime: 	Suppressed: U5.g: [w0.p0@d47340d, O.g@83b4fc2, x0{Cancelling}@59a41d3, Q@eee8110]
```

But that's odd, because our https://github.com/tailscale/tailscale-android repo contains no mention of `ConfirmDialog` or `vpndialogs` anyway.

Are you sure this isn't Magisk interfering?

**Comment by Stonecroissant** [comment]
Well, I haven't added Tailscale to the denylist, and I'm pretty sure that none of my modules are to blame.

**Comment by Stonecroissant** [comment]
Here is a list of all my installed modules:
![Screenshot_20241110-013513](https://github.com/user-attachments/assets/19037593-1c2d-4c53-9651-4b0895ddf0a1)
![Screenshot_20241110-013532](https://github.com/user-attachments/assets/01283e32-ecbe-411e-9c51-dbdc59784caa)

**Comment by kari-ts** [comment]
We don't directly reference `ConfirmDialog` or `vpndialogs`. I'm guessing the issue is coming from some device-specific configuration that is interacting with `VpnService.prepare` in an unexpected way.  Since this is the first time launching Tailscale, `VpnService.prepare` will return an intent to start the system confirmation dialog (probably `com.android.vpndialogs`). I'm wondering if the OEM has removed or blocked access to `com.android.vpndialogs`.

**Comment by Stonecroissant** [comment]
I think it's an OEM issue because I also had problems with NordVPN and couldn't get it to work. Is there a way to use Tailscale via the VPN profile in settings?
![image](https://github.com/user-attachments/assets/4a8017e3-4251-495b-9f36-dcc7a15f43cc)

**Comment by agottardo** [comment]
@Stonecroissant No, that's not possible. We have plenty of users with a OnePlus setup like yours. Did you modify the device or the OS in any way that could have caused the `com.android.vpndialogs` package to be uninstalled?

**Comment by Stonecroissant** [comment]
I found out that I found out that **com.android.vpndialogs** was on the list in the debloater module, and after removing it, I can now connect without any problems.
