### ISSUE TITLE
`tailscale help` should be an alias for `tailscale -h`

### ISSUE THREAD

**Issue by mvdan** [tailscale/tailscale#14053]
Perhaps this is me being used to `go help`, but I type `tailscale help` somewhat regularly, and it's terribly unhelpful:

```
$ tailscale help
tailscale: unknown subcommand: help
```

It would seem pretty easy and reasonable to make it an alias for `tailscale --help`. Note that this doesn't need to be a proper subcommand listed in the help text.

**Comment by bradfitz** [comment]
SGTM

**Comment by mvdan** [comment]
Thanks!
