### ISSUE TITLE
Android Settings icon disappears in latest version

### ISSUE THREAD

**Issue by wx2020** [tailscale/tailscale#14060]
### What is the issue?

When I upgraded the latest version in Android, the settings icon that was on the top right corner disappeared.
![image](https://github.com/user-attachments/assets/dd2d33d5-a63a-48a1-a945-791a53da3017)
Clicking on the original settings icon area actually takes you to the settings page, but the lack of an icon is really confusing.
![image](https://github.com/user-attachments/assets/8a476b62-8f18-4c21-b74b-d9e7e558b096)

### Steps to reproduce

N/A

### Are there any recent changes that introduced the issue?

Update APK

### OS

Android

### OS version

Android 13

### Tailscale version

1.76.2

### Other software

Is this a specially modified UI or is this a bug?

### Bug report

BUG-96a8edeb339f87daf5e9bc33e7bbf10d33d8ab1b152df5720f6f09527818e5a0-20241111060834Z-5f4c2526b10ca2eb
```[tasklist]
### Tasks
```

**Comment by numericOverflow** [comment]
Same issue here.

I can't connect to self-hosted setup (headscale) because it's forcing me to the wrong server, and with settings option gone, app is stuck in unfixable loop.  

This version is unusable in current state, please fix ASAP.

**Comment by dblohm7** [comment]
We believe this has been fixed in https://github.com/tailscale/tailscale-android/pull/558
