### ISSUE TITLE
Adding multiple PiKVM hardware devices overwrites the others lease on tailnet

### ISSUE THREAD

**Issue by bmcminn** [tailscale/tailscale#14088]
### What is the issue?

I've had this issue since Fall 2023 when I first installed these BliVKM PCIev2 devices on different network locations and adding both of them to my tailnet.

Adding one KVM with `tailscale up --auth-key=XXXXXXXX` works fine, but when I add the other device `tailscale up --auth-key=YYYYYYY` the new KVM overwrites the existing KVM's lease on my tailnet.

They are both based on the same hardware rev and latest OS/firmware.

I found this existing issue, however in my case neither device was imaged with tailscale preinstalled.
- https://github.com/tailscale/tailscale/issues/13178

I've reviewed any parity info I can find between the two devices and have tried to differentiate them as best I can:
- updated both KVMs to the latest firmware/OS
- have run `sudo apt update/upgrade` on both
- both devices are on geographically different network locations
- set different `hostname`s per device
- verified they have different mac addresses
- verified they each have their own unique `machine-id` values in `/etc/machine-id` and `/var/lib/dbus/machine-id`
    - per this reddit thread comment: https://www.reddit.com/r/netsec/comments/lr61p4/comment/golbnvj/ 
- both devices produce different Node keys in tailscale when connecting
- tried running `tailscale up --auth-key=ZZZZZZZ --hostname=<unique_hostname>` on both devices, yet the lease conflict still persists

The only similarities I can reasonably see now are the Tailscale version, Tailscale node ID, OS name, OS version

So my question is what other information could Tailscale be using to identify these devices as the same device and overwrite their lease on my tailnet?

### Steps to reproduce

Followed BliKVMs Tailscale install instructions located at https://wiki.blicube.com/blikvm/en/tailscale/

- `ssh` into the KVM device
- `sudo apt update`
- `sudo apt upgrade -y`
- login to tailscale admin console in my browser and "add device" -> linux server
    - tags: false
    - ephemeral: false
    - use as exit node: false
    - reusable: false
    - expiration: 7 days
- generate install script
- copy/paste into shell console
- repeat for the other device on a completely separate network
- both devices will just take over the others lease

### OS

Linux

### OS version

Linux 6.1.21-v8+

### Tailscale version

1.76.6

### Other software

BliKVM client device software and firmware v.1.5.0
https://github.com/ThomasVon2021/blikvm/releases/tag/v1.5.0

### Bug report

BUG-e134c41c286225b798106ac7b17f69fbadc04cec94fb6c533fa9a2e33d6a2273-20241114021943Z-057a06152159f82f

**Comment by stevetrease** [comment]
Have you tried shutting down tailscale on each node; then deleting the contents of /var/lib/tailscail; then restarting the taillscale and relogging in?

**Comment by bmcminn** [comment]
Tried deleting `/var/lib/tailscale`, reset both `/etc/machine-id` and `/var/lib/dbus/machine-id`, rebooted, and reinstalled tailscale and that seemed to work :)

I'm going to ref this in an issue on the BliKVM repo that they may want to add a script that modulates the machine-id so these devices are more unique on first deployment.
