### ISSUE TITLE
Custom DERPPort Option not working due to `forcing port 443 dial due to recent noise dial`

### ISSUE THREAD

**Issue by Dustella** [tailscale/tailscale#14089]
### What is the issue?

I self-hosted a DERPER server, running HTTPS port at 8443, my ACL configuration include nodes like:

```
{
        "Name":      "Alice",
        "RegionID":  900,
	"HostName":  "derper.example.net",
	"DERPPort":  8443,
	"IPv4":      "11.11.11.111",
	"IPv6":      "2408:4.....:.......:fb0f",
	"STUNPort":  3478,
					},
```

I works on most of my machines, but one machine will continuously attempt to use 443 rather than 8443.

By checking `journalctl -xeu tailscaled`, we can find it is due to `forcing port 443 dial due to recent noise dial`:

```
11月 14 10:09:15 mercury tailscaled[20322]: control: controlhttp: forcing port 443 dial due to recent noise dial
11月 14 10:09:15 mercury tailscaled[20322]: control: controlhttp: forcing port 443 dial due to recent noise dial
11月 14 10:09:15 mercury tailscaled[20322]: control: controlhttp: forcing port 443 dial due to recent noise dial
11月 14 10:09:15 mercury tailscaled[20322]: control: controlhttp: forcing port 443 dial due to recent noise dial
11月 14 10:09:16 mercury tailscaled[20322]: control: controlhttp: forcing port 443 dial due to recent noise dial
11月 14 10:09:16 mercury tailscaled[20322]: [RATELIMIT] format("control: controlhttp: forcing port 443 dial due to recent noise dial")
11月 14 10:09:19 mercury tailscaled[20322]: derphttp.Client.Recv: connecting to derp-900 (CN_ALI)
11月 14 10:09:19 mercury tailscaled[20322]: derphttp: CONNECT dial to derper.example.net:443: 200 Connection established

``` 

It should 

### Are there any recent changes that introduced the issue?

This `forcing port 443 dial due to recent noise dial` comes from 

https://github.com/tailscale/tailscale/blob/f593d3c5c0eee55fdf988085d27aa991dbfd5fd6/control/controlhttp/client.go#L281 , 

so it is because of `d.HealthTracker.LastNoiseDialWasRecent()` that it is force using 443.

### OS

Linux

### OS version

Linux 6.10.14-1-MANJARO

### Tailscale version

1.76.6

### Bug report

BUG-f8f68b40ce3f8f8a30f5a4e02447481cc0723a197ff0db27f6e4a690e937183f-20241114024006Z-d350c86d669a0118

**Comment by Dustella** [comment]
I hope `d.HealthTracker.LastNoiseDialWasRecent()` and the force443 thing can respect custom derper port settings, thanks

**Comment by bradfitz** [comment]
`LastNoiseDialWasRecent` is about the control plane. It doesn't impact DERP, which you're talking about here.

**Comment by Dustella** [comment]
After a full reinstall it is using the correct port
