### ISSUE TITLE
UDP packet not return in the same path of source

### ISSUE THREAD

**Issue by ArcticLampyrid** [tailscale/tailscale#14092]
### What is the issue?

For IPv6 hosts with multiple addresses, the UDP packet does not return via the source path:
- The host has both `aa::a` (eth0) and `bb::b` (eth1) addresses.
- Policy routing is configured: all to `aa::/48` via eth0, src `aa::a`.
- Default route (except for `aa::/48`): via eth1, src `bb::b`.
- When receiving an inbound UDP packet from `bb::b` (eth1), if a response is required to a host in the `aa::/48` subnet, the response is not sent according to the source path but always via `aa::a` (eth0), causing asymmetric routing.
- If the peer has a firewall with address-based restrictions, the response will be dropped.

### OS

Linux

**Comment by bradfitz** [comment]
Dup of #2187, #2331, etc

Right now magicsock only has one socket and uses `net/netns` to bind it to one interface explicitly. It can't trust the OS's routing table, because when exit nodes are in use, we have a default route back into Tailscale.

That's what those other bugs track.

**Comment by ArcticLampyrid** [comment]
> Right now magicsock only has one socket and uses `net/netns` to bind it to one interface explicitly. It can't trust the OS's routing table, because when exit nodes are in use, we have a default route back into Tailscale.

This doesn't require trusting the system routing table; you just need to create multi socket for each NIC (except for Tailscale's own tun device) and bind it to the device.
