### ISSUE TITLE
Random Wi-Fi disconnects on Google Pixel phones 

### ISSUE THREAD

**Issue by jess-sch** [tailscale/tailscale#14128]
### What is the issue?

Turning on Tailscale in default configuration makes my Pixel randomly lose Wi-Fi connectivity. I have also observed this on the Pixels of my family members.

This is most likely caused by Adaptive Connectivity Services (com.google.android.apps.scone) thinking the Wi-Fi is broken, since excluding this app in the split tunnel settings solves the issue reliably.

My proposed solution would be to add this app to the list of forcibly excluded apps.

### Steps to reproduce

1. Install Tailscale on a freshly installed Google Pixel device
2. Observe random disconnects from your Wi-Fi network 

### OS

Android

### OS version

Android 15 (Google)

### Tailscale version

1.76.2

### Other software

none

### Bug report

BUG-d8f9709b8684f35ac9551bc3608685ca8ef922d35a866fc60d469da4591f44ce-20241116212119Z-90d1f107bbea935a

**Comment by kari-ts** [comment]
@jess-sch, thank you for flagging this to us. We really appreciate your taking the time to help us improve Tailscale!
