### ISSUE TITLE
Tailscale android app closes immediately upon opening

### ISSUE THREAD

**Issue by MarcelRobitaille** [tailscale/tailscale#14134]
### What is the issue?

Recently, the app started to close immediately when I open it. I see the logo for a second, then I see my home screen again. I tried rebooting my phone and clearing the app cache and storage.

[Error in Tailscale eccb95505f2c.txt](https://github.com/user-attachments/files/17789953/Error.in.Tailscale.eccb95505f2c.txt)

### Steps to reproduce

Try to open the app 

### Are there any recent changes that introduced the issue?

Potentially an app update and/or OS update. 

### OS

Android (graphene OS) 

### OS version

Android 14

### Tailscale version

version 1.76.0-t51fb4ce51-g5f19730c7a4

**Comment by agottardo** [comment]
Please update to v1.76.6 which should have resolved this.

**Comment by MarcelRobitaille** [comment]
That does indeed work. F-Droid had me on an old version. Classic
