### ISSUE TITLE
tailscale can't handle overlapping subnets

### ISSUE THREAD

**Issue by lfarkas** [tailscale/tailscale#1413]
We've got a few tailscale endpoint let call them A and B and we has a client node C. There are 2 different network behind these 2 nodes:
- A has 192.168.0.0/24
- B has 192.168.241.0/16
if I connect from C then I'm not able to ping all access any host behind B since all these packet goes to A (one can trace it with tcpdump).

This is a very normal network scenario and by default linux use the smallest network to use by default. but it seems tailscale can't handle this very basic situation.

**Comment by lfarkas** [comment]
Imho it's all networking routing daemon should have to follow the standard internet routing /networking policy.

**Comment by bradfitz** [comment]
Your 100.100.155.27 node is reporting that its IP forwarding is broken.

See https://tailscale.com/kb/1104/enable-ip-forwarding

**Comment by lfarkas** [comment]
it's used to be that each project/people reply to me as to some average joe user....first...later when i show them i've got right they used to accept my argument even if i do not have right:-)

first of all it's nice that you can see my network setting..suppose it just some kind of anonymous data collection (it's not since you know which is my ips without i wrote:)
second it's not about that node!
third it's obvious you don't even look into the problem and not even test it.
last but not least it has nothing to do with ip forwarding since routing (as in this case) can fail without ip forwarding. we talk about ip forwarding when an INCOMING packet send OUT and neither the source not the destination is the given host. and this is not the case here!

anyway it's working with openvpn (which is not a proof that it's the right way but at least worth to think about it).

so please reopen since it's a BUG not a feature!  

I assume you understand the core problem from the above description but if not let me

- describe the problem
- show an example and what is the problem
- show what your program do in a wrong way.

so let me describe how the routing works on linux at the basic.
- basically there is only one routing table.
- in this table there can be networks (an ip range which can be described by it's first ip and a netmask). 
- each network can be routed through a network interface or gateway.
if comes a new packet the routing process try to find out through which interface or gateway the given packet send out. if more networks contain the same ip address then the smallest one will be chosen if  the have the same precedence.

- now suppose i do NOT like to forward any ip packet (eg this is my laptop).
- my company has a large internal network with 192.168.0.0/24 range and advertise this network.
- my tailscale try to connect to there.
- i go to an internet coffee which give my a wifi address from it's network 192.168.241.0/16 let it be 192.168.241.22 with gateway 192.168.241.1
- what's happened when i ping 192.168.241.1 (no response) 
- what's happened when i traceroute 192.168.241.1 ? it goes into my company's internal network and try to reach 192.168.241.1 from there

do you understand the problem?
it's in my laptop local routing table which was crippled by tailscale while try to use some very advanced routing with it's table 52 but even the basic routing not working in this case.
of course if it's my home network i can assign a different network for my home router but i can't reconfigure each wifi network where i go.

i hope it's help to understand the problem.

**Comment by bradfitz** [comment]
I like to keep bugs open for actionable things with details.

Feel free to write in to support@tailscale.com with full details, including Tailscale IPs of affected nodes.

**Comment by lfarkas** [comment]
the above details was not enough? probably i can't write longer story! may be shorter:

suppose you try to accept routing for a network 192.168.0.0/24 through tailscale.

and your local routing table looks like before tailscale up:
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.241.1    0.0.0.0         UG    100    0        0 enp3s0
192.168.241.0    0.0.0.0         255.255.255.0   U     100    0        0 enp3s0

than it's not working.

**Comment by bradfitz** [comment]
Dup of #1344
