### ISSUE TITLE
forum.tailscale.com/ login disabled while in read only mode

### ISSUE THREAD

**Issue by GalacticPrez** [tailscale/tailscale#14133]
### What is the issue?

It seems your forum is either offline or that installing Tailscale stops me logging in? I checked the status page here (https://status.tailscale.com/) but none of the servers listed was specifically forum.tailscale.com so I do not know if it is just offline or there is a bug

### Steps to reproduce

N/A I just installed tailscale, no idea whether installing it is involved or not, but no other pages fail to work, I just cannot login or sign up to that forum page

### Are there any recent changes that introduced the issue?

only installing software and connecting 4 devices: this laptop, other laptop, QNAP NAS, and iPhone

### OS

Other

### OS version

various

### Tailscale version

latest

### Other software

I checked, but nothing else is blocking, I just get the message that login is disabled while in read only mode, regardless of whether I try to sign up or login ... so either the server is down, or there is something else wrong

**Comment by bradfitz** [comment]
That forum has been shut down.

The community has mostly moved to Reddit.
