### ISSUE TITLE
No internet access on Tailscale after logout and log back in

### ISSUE THREAD

**Issue by GalacticPrez** [tailscale/tailscale#14136]
### What is the issue?

I was wondering if Tailscale was interfering with something else, which it wasn't, but to test it, I logged out of Tailscale on this machine from the system tray icon (Win10pro) and after the test showed it wasn't Tailscale and other measures showed the problem was something else (a server online being down for maintenance), I logged back in to Tailscale, but even after a reboot of the machine, Tailscale still has no internet access ... nothing was wrong until I logged out, but I do not know what to do to test and diagnose what is wrong. I need advice on what things to check, or whether this is a known issue that has a solution.

Note: there are no exit nodes or subnet nodes, all I have are 2 laptops, an iphone, and a qnap nas registered to tailscale, and the only other device powered up at the moment is the mobile phone ... when Tailscale was installed on the QNAP, it did ask me at the end of the installation if I wanted to announce it as an exit node, but I did not confirm this choice, as I didn't yet understand whether or not I would want an exit node ... so the only way that is involved, is if this question of announcing it as an exit node isn't asking if I want it to be one, but only asking if I want it to be announced as one, hence a little vagueness of the language during those instructions, when it should have told me that it was automatically selected as one, and this was only asking me whether I wanted that announced on the network, but otherwise, so far as I know, it is not one (it takes ages to boot up, so I haven't tested that yet on the assumption this is not the issue). But I did not notice anything having no internet access after it was shut down last night, not that I looked, but I didn't see any such thing.

### Steps to reproduce

All I did was logout of Tailscale from the system tray icon and log back in, nothing else.

When I look at the /admin/machines console on github, it says this machine is connected, the tailscale system tray icon says it is connected, but the windows system tray icon for internet says it is connected but no internet access 

### Are there any recent changes that introduced the issue?

Only logging out as far as I know, it was fine before that I think.

### OS

Windows

### OS version

Win10pro latest release

### Tailscale version

1.76.6

### Other software

It is a new laptop install having formatted hard drive recently, using memtechtips and chris titus tech tool to minimise / debloat windows install and minimise background services, and the only other things installed that use networking are steam games and AVG anti-virus suite, but I have the network inspector switched off, and the enhanced firewall was not interfering previously.

All of this was working fine last night after I installed it and shut it down to go to sleep, now on waking and doing as I said above, it can login, connect, but no internet access ... so that is all I know, and I am new to this since just yesterday so I do not fully understand it yet

**Comment by GalacticPrez** [comment]
Sorry the bug report delivered this:
BUG-8e3595563aab94420c912f564d510918272f923ae3012e79cb528fb14b7ac655-20241117214743Z-ea644c8d5d9aaf01

**Comment by GalacticPrez** [comment]
UPDATE: if I go into the tailscale network adapter settings in windows, under IPv6 I can see the IP address, but under IPv4 I only get this: 

<img width="303" alt="tailscale no internet access ipv4" src="https://github.com/user-attachments/assets/a30195b4-a50c-42ee-bd26-84b7a5abdef4">

So is it possible the problem is that for some reason it is not fetching its IPv4 address when I log back in?

**Comment by GalacticPrez** [comment]
Is it possible that if the key expiry coincides with a computer being logged out at the time (assuming I am interpreting this correctly), that the computer never receives the new key, and thus isn't properly connected after login?

<img width="416" alt="key expirey" src="https://github.com/user-attachments/assets/36478692-1704-4c74-8b93-9269130d0fa0">

**Comment by GalacticPrez** [comment]
[EDIT/UPDATE]: I was going to walk to the cafe to test something else (connecting from my phone to the other laptop, both of which had been switched off during this whole thing, and therefore shouldn't have been affected) ... but when I switched on the other laptop, it too had the exact same issue, so instead of just looking at the IPv4 settings for that tailscale adapter, I also right clicked to look at its status, and then selected details from the general tab (see screen capture below):

<img width="1143" alt="tunnel ethernet adapter status details" src="https://github.com/user-attachments/assets/771c8e2f-8e76-4a22-9452-339e8298b23c">

... and as you can see, despite the IPv4 settings being told to use specific settings rather than DHCP, and not having any of those settings actually set, yet here on the status for that adapter, it somehow seems to know the IP address, subnet mask, and DNS ... 

So this is very strange to me, how can it have none of it set yet still have these details here, and if they are here, then how come it cannot see the internet? So I will try adding these details to the IPv4 configuration, but it also makes me wonder, what exactly is meant by "logging out" if this is what happens?

My assumption was that "logout" meant that either the current device would be logged out of the tailnet OR that the current user would be logged out, but either way the same result from the perspective of the laptop - ie: tailscale remains installed and configured, but I am just not using it once I log out ... does it mean something else? If so, then I think this needs to be clearer at the point of usage, since this is what I think most users would assume, and they certainly wouldn't expect to log back in and have such troubles, and no other function and no other information as to why the adapter is connected but cannot access the internet.

**Comment by GalacticPrez** [comment]
[EDIT/UPDATE]: it seems there is no way to tell it the IPv4 or IPv6 DNS ... is this happening because that information is managed by the tailscale application? It seems to know that it is me logged in, it knows all my devices, it can reach the admin console, the console says the devices are all connected, but logging out seems to have prevented them from accessing the internet, despite the fact it seemed to have no issue logging back in ... I am giving up for now and going for a walk, I hope someone understands what is going on here, because I am out of ideas.

**Comment by GalacticPrez** [comment]
Has anyone looked at this yet? I have run out of ideas myself, and received no feedback.

**Comment by kelivel** [comment]
Hi @GalacticPrez, what you're seeing is actually expected! Windows sends active probes (in the form of HTTP requests) through all the available interfaces, and since no response is received over Tailscale, unless an exit node is in use, it reports "No Internet". We'll be updating our [Troubleshooting kb](https://tailscale.com/kb/1023/troubleshooting?q=troubleshooting#windows) with a small addition about this soon.

If you have any other questions, don’t hesitate to reach out to our [Support team](http://www.tailscale.com/support)!

**Comment by GalacticPrez** [comment]
> Hi @GalacticPrez, what you're seeing is actually expected! Windows sends active probes (in the form of HTTP requests) through all the available interfaces, and since no response is received over Tailscale, unless an exit node is in use, it reports "No Internet". We'll be updating our [Troubleshooting kb](https://tailscale.com/kb/1023/troubleshooting?q=troubleshooting#windows) with a small addition about this soon.
> 
> If you have any other questions, don’t hesitate to reach out to our [Support team](http://www.tailscale.com/support)!

I don't quite understand, are you saying that the software is working fine, but just on some networks it will be limited to the local network and won't give me access to anything outside the LAN (for some reason), or are you saying it doesn't work on public wifis, or something else ... I don't quite follow the explanation.

**Comment by GalacticPrez** [comment]
> Hi @GalacticPrez, what you're seeing is actually expected! Windows sends active probes (in the form of HTTP requests) through all the available interfaces, and since no response is received over Tailscale, unless an exit node is in use, it reports "No Internet". We'll be updating our [Troubleshooting kb](https://tailscale.com/kb/1023/troubleshooting?q=troubleshooting#windows) with a small addition about this soon.
> 
> If you have any other questions, don’t hesitate to reach out to our [Support team](http://www.tailscale.com/support)!

What am I supposed to do about this? Is there a work around, do I uninstall and reinstall, start from scratch ..?
