### ISSUE TITLE
Tailscale  should show failure information in case of can't resolve login.tailscale.com.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1415]
The customer upgraded to Tailscale v1.4.5 from the Appstore. The app is logged out, and clicking on “Log in” in the menu does nothing. 

After the debug, he found out using the Console.app in macOS that was failing to resolve login.tailscale.com.

We should show an error if login fails due to this issue.

**Comment by bradfitz** [comment]
Related: https://github.com/tailscale/tailscale/pull/1407 was already merged for #1405 and #1403.

This is specifically about showing notification upon backend errors?

@rosszurowski, @crawshaw, have either of you given any thought to UI/policy there?

**Comment by DentonGentry** [comment]
This was filed to followup on a support request, but the specific support request was not recorded and we don't know where the followup would go. Closing as not useful any more.
