### ISSUE TITLE
FR: Make deployment of tailscale IngressClass by k8s operatorm optional

### ISSUE THREAD

**Issue by Rumbles** [tailscale/tailscale#14152]
### What are you trying to do?

We have tailscale operator installed in a cluster with multiple tennant vclusters

We want to be able to deploy tailscale via the operator without deploying the IngressClass, as the ingress class is inherited from the parent cluster and causes us to have sync issues in ArgoCD.

**Comment by irbekrm** [comment]
Hi @Rumbles thank you for opening the issue.

> We have tailscale operator installed in a cluster with multiple tennant vclusters

Out of curiosity, how come that `IngressClass` is the only one that causes issues (and not other operator resources if it is syncing those too?) and specifically what is the issue - does it clash with other `IngressClass` resources predefined in the tenant clusters or is it that Argo is trying to delete it?

**Comment by Rumbles** [comment]
Hi @irbekrm 

Good question, I'm not sure. I currently see the warning for the IngressClass in argocd:

```
IngressClass/tailscale is part of applications argocd-infrastructure/my-demos-tailscale and argocd-infrastructure/tailscale
```

Previously we installed the operator using the manifest files in your repo and a colleague used kustomize to delete that part of the manifest. I am trying to figure out how I would do the same thing so I can move the vclusters on to the helm chart like the parent cluster.

I asked Claude 3.5 and it suggested:

```
vcluster has specific syncing behaviors for different resource types. For cluster-scoped resources like IngressClass, vcluster often syncs these from the host cluster to the virtual cluster to maintain consistency and functionality.
```

So I think the resource exists outside of the scope of a vcluster, which means it clashes with the one in the parent cluster.

**Comment by irbekrm** [comment]
@Rumbles it looks like you could disable that sync behaviour in vcluster https://www.vcluster.com/docs/vcluster/next/configure/vcluster-yaml/sync/from-host/ingress-classes#enable-syncing-ingressclasses-from-the-host-to-virtual-cluster

Would doing that make sense for you or do you rely on that behaviour?

**Comment by Rumbles** [comment]
Hi, we reuse ALB Ingress Class from our parent cluster to save on us creating a new load balancer for each vcluster as that would make it really expensive for the little demos we need to expose. 

Sadly we wouldn't want to disable that sync behaviour
