### ISSUE TITLE
wgengine/monitor: on Darwin, failed to parse RIB: message too short

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1416]
golang.org/x/net/route.ParseRIB is returning its `errMessageTooShort` parsing these 50 bytes of a route message we read from the kernel:

```
monitor: read 50 bytes (32 00 05 10 30 00 00 00 00 00 00 00 04 00 00 00 14 12 04 00 06 03 06 00 65 6e 30 ac 87 a3 19 7f 82 00 00 00 0e 12 00 00 00 00 06 00 91 e0 f0 01 00 00),
  ....  failed to parse RIB: message too short
```

But it uint16_nativeendian(0x32 0x00) is 50, which is how many bytes are there. 0x05 is the RTM_VERSION byte for darwin,

```
zsys_darwin.go: sysRTM_VERSION = 0x5
```

And the final byte of the 4 byte header is 0x10, the type: sysRTM_DELMADDR, deleting a multicast address:

```
        ifmam := &wireFormat{extOff: sizeofIfmaMsghdrDarwin15, bodyOff: sizeofIfmaMsghdrDarwin15}
        ifmam.parse = ifmam.parseInterfaceMulticastAddrMessage
```

It seems that parser is returning the `errMessageTooShort` why? It assumes it only reads the RTM messages via sysctls with its alignment rather than via a AF_ROUTE socket?

Figure out.

**Comment by bradfitz** [comment]
Filed Go bug https://github.com/golang/go/issues/44740 too.

**Comment by DentonGentry** [comment]
This has not come up again in almost two years. Barring further comment, we'll expect to close this during the next regular bug scrub.
