### ISSUE TITLE
Admin: provide an audit log of actions taken.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1418]
A few users have requested an audit log for the admin panel, letting them see what actions have been taken by who:

> Promoting other users to admins, editing the ACL or DNS pages, Inviting new users, manually approving devices, etc.

Audit Logs for any ACL changes on an admin dashboard would help figure out when and why the user made the changes.

**Comment by tjstansell** [comment]
This should include API activity as well.  Basically, any administrative activity, regardless of where/how it was done.

**Comment by DentonGentry** [comment]
Work on implementing this feature has started.

**Comment by DentonGentry** [comment]
Work on implementing this feature is proceeding.

**Comment by DentonGentry** [comment]
Launched: https://tailscale.com/kb/1203/audit-logging/
