### ISSUE TITLE
win11 client shows as connected but not as a taildrop client in android

### ISSUE THREAD

**Issue by strebor71** [tailscale/tailscale#14203]
Just as title states a windows 11 client shows as a connected device with an ip address and green dot  in the android app ver 1.76.6, but when sending a file via taildrop from same android device, the windows 11 client doesnt show  in the "My devices" list in the Send with Taildrop screen (doesnt show at all, other non connected devices show but greyed out). other devices are shown and work fine.  when on the same windows 11 machine using send with taildrop, the android device is shown and can be sent files. 

windows 11 22H2 bld 22621.4317
Windows app ver. 1.76.6
android pixel 9 pro 
android ver 14  app ver.  1.76.6

[screenshot1](https://www.vidble.com/78C1jIuWTX.png)
[screenshot2](https://www.vidble.com/Zim7G3sIjK.png)

**Comment by strebor71** [comment]
uninstalled, removed from admin panel, re-installed fixed problem.

**Comment by skywalker478** [comment]
Hello! I'm facing the same problem and reinstalling is not solving the problem.

These screenshots are taken after reinstalling...
![Screenshot_20241203-105852](https://github.com/user-attachments/assets/cb14ba0f-9c0d-4504-b441-b8709d5d6002)
![Screenshot_20241203-105931](https://github.com/user-attachments/assets/f3392df8-d5da-4bc8-b163-a0132e71510f)
