### ISSUE TITLE
"Device Name" menu not available on new setup until app restart

### ISSUE THREAD

**Issue by mattieb** [tailscale/tailscale#14250]
### What is the issue?

The "Device Name" menu is unavailable on a new app install on iOS until the app is restarted once.

![IMG_0046](https://github.com/user-attachments/assets/9351c02b-e4e4-43ab-9ea8-1f39a62d5618) ![IMG_0047](https://github.com/user-attachments/assets/f9ab724d-738d-4d36-bcf8-a2401b1efb52)

### Steps to reproduce

1. Install Tailscale 1.76.1 on iOS 18.1.1
2. Sign in to tailnet with Apple ID
3. Allow tailnet to connect successfully
4. Open settings menu (profile 👤 icon, upper-right of screen)
5. "Device Name" menu is disabled
6. Tapping shows "Not Available" dialog

The "Not Available" dialog says "Tailscale is offline" but this is not in fact the case. Toggling the online switch on the main screen off and on does not resolve this issue. Killing and restarting the Tailscale app does resolve the issue and makes the "Device Name" menu available and functional.

### OS

iOS

### OS version

18.1.1

### Tailscale version

1.76.1

### Other software

None

### Bug report

BUG-c6d33f8b194118b26b3edea2dbcca5e7856e06ac3b7cfd090f2cc21d800f2cd4-20241129142627Z-f173d5e89a2180bd

**Comment by agottardo** [comment]
Thanks for reporting this. We have pushed a fix that will land in the next app update.
