### ISSUE TITLE
FR: Updated TrueNAS Snippet

### ISSUE THREAD

**Issue by linzi-ix** [tailscale/tailscale#14271]
### What are you trying to do?

https://tailscale.com/kb/1307/nas?q=truenas

The above link has a short snippet about TrueNAS and FreeNAS. Due to our new releases, this snippet could use a refresher to retain accuracy.

### How should we solve this?

We no longer use the term "FreeNAS" and our newest releases are Linux-based. Updating the snippet to include this information could clear up any confusion for readers and broaden its usage to Tailscale/TrueNAS users who might be utilizing an updated Linux-based software.

**Comment by ironicbadger** [comment]
We've just published a new TrueNAS page. Hopefully this addresses your concerns.

https://tailscale.com/kb/1483/truenas?q=truenas
