### ISSUE TITLE
Diagnostics incorrectly report no UDP connectivity in 1.77 for some nodes

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#14287]
### What is the issue?

In some cases seems that for a node that reportedly had UDP access in 1.76, the probe fails when the node is upgraded to 1.77.x (I've tested with `1.77.165` and a few more recent unstable versions)

I've done a bit of debugging and it seems that we get a `sendto: invalid argument` from [here-ish](https://github.com/tailscale/tailscale/blob/74069774bee3aeb52637a58587ddfb0369f69676/wgengine/magicsock/rebinding_conn.go#L158) where we send the probe packet.

With some more debugging, it seems like the client sends the STUN packets to DERP server's port 0 which would explain the error message.

### Steps to reproduce (with a Linux client)

1. Run `sudo tailscale update --track unstable` (currently `1.77.165`)
2. Observe netcheck errors in logs and netcheck reporting no UDP:
```
$ journalctl -u tailscaled -n 50
tailscaled[305852]: derphttp.Client.Recv: connecting to derp-8 (lhr)
tailscaled[305852]: control: NetInfo: NetInfo{varies= hairpin= ipv6=false ipv6os=true udp=false icmpv4=true derp=#8 portmap= link="" firew>
tailscaled[305852]: netcheck: netcheck: UDP is blocked, trying HTTPS
tailscaled[305852]: netcheck: UDP is blocked, trying ICMP
...
```
3. Observe `UDP: false` in Admin console
4. Downgrade to `1.76`  `sudo tailscale update --track stable`
5. Observe that netcheck now reports UDP connectivity as true:
```
$ journalctl -u tailscaled -n 50
...
tailscaled[309713]: control: NetInfo: NetInfo{varies=false hairpin= ipv6=false ipv6os=true udp=true icmpv4=false derp=#8 portmap= link="" >
```
6. Observe `UDP: true` in Admin console

### OS

Linux

### OS version

Tested with containerized nodes on Kubernetes and an Ubuntu client

### Tailscale version

1.77.x

**Comment by tomhjp** [comment]
This also reproduces for me with the client's `unstable` tag in a local container. Repro steps:

1. Create any old auth key, `export TS_AUTHKEY=ts...`
2. `docker pull tailscale/tailscale:unstable && docker run --rm -e TS_USERSPACE=false -e TS_AUTHKEY --device /dev/net/tun --cap-add NET_ADMIN --cap-add NET_RAW tailscale/tailscale:unstable`
3. Observe logs:

    ```
    2024/12/05 09:44:03 netcheck: netcheck: UDP is blocked, trying HTTPS
    2024/12/05 09:44:03 netcheck: UDP is blocked, trying ICMP
    ```
