### ISSUE TITLE
FR: Allow tailscaled to ignore specific interfaces

### ISSUE THREAD

**Issue by jaysonsantos** [tailscale/tailscale#14306]
### What are you trying to do?

When using k3s with wireguard and connecting nodes through tailscale, eventually tailescale uses the wireguard network and that makes it sort of infinite loop and disrupting the connection between machines

### How should we solve this?

it would be nice to have on the config something like `ignored interfaces = flannel-wg`

### What is the impact of not solving this?

I need to restart tailscaled from time to time so it picks up the main network card

**Comment by dionorgua** [comment]
duplicate of https://github.com/tailscale/tailscale/issues/1552

**Comment by jaysonsantos** [comment]
Closing in favor of the other issue and trying the following to see if it works

              My current solution around this is with the `IPAddressDeny` option to tailscale's systemd unit. Fortunately, this option doesn't need a systemd compiled with BPF_FRAMEWORK at all.

Just for reference:

```ini
# /etc/systemd/system/tailscaled.service.d/override.conf
[Service]
# avoid forming links over kubernetes overlay network
IPAddressDeny = 10.42.0.0/16
```

I believe this option is equivalent to dropping any packet the program sent to the given network. Try `systemd-run -t -p IPAddressDeny=1.1.1.1 ping 1.1.1.1` and see for yourself.

Tailscale would still advertise through the interface but it will not get anything out of it. It works fine for me so far.

_Originally posted by @shouya in https://github.com/tailscale/tailscale/issues/1552#issuecomment-1991237756_
