### ISSUE TITLE
Update to 1.78.0 not working on Synology DSM 7.2.2

### ISSUE THREAD

**Issue by spaceg00se-r** [tailscale/tailscale#14304]
### What is the issue?

Tailscale update to 1.78.0 not working on Synology DSM. In my case I own two Synology NAS and both run into the same problem.
The console reports the following log:
`This will update Tailscale from 1.76.1 to 1.78.0. Continue? [y/n] y
Downloading "https://pkgs.tailscale.com/stable/tailscale-x86_64-1.78.0-700078000-dsm7.spk"
Download size: 30032384
Downloaded 512/30032384 (0.0%)
Downloaded 30032384/30032384 (100.0%)
Downloading "https://pkgs.tailscale.com/stable/tailscale-x86_64-1.78.0-700078000-dsm7.spk.sig"
Signature OK
synopkg install failed: exit status 1
output:
{"error":{"code":0},"results":[{"action":"upgrade","beta":false,"betaIncoming":false,"error":{"code":277,"description":"failed to run preupgrade script"},"finished":true,"installReboot":false,"installing":true,"language":"enu","last_stage":"started","package":"Tailscale","packageName":"Tailscale","pid":28525,"scripts":[{"code":0,"message":"","type":"stop"},{"code":1,"message":"","type":"preupgrade"},{"code":0,"message":"","type":"start"}],"spk":"/tmp/tailscale-update1068947846/tailscale-x86_64-1.78.0-700078000-dsm7.spk","stage":"install_failed_and_started","status":"running","status_description":"translate from systemd status","success":false,"username":"","version":"1.76.1-700076001"}],"success":false}
`

### Steps to reproduce

Run "sudo tailscale update"

### OS

Synology

### OS version

DSM 7.2.2-72806 Update 2

### Tailscale version

1.76.1

**Comment by agottardo** [comment]
Thanks for the report. See https://github.com/tailscale/tailscale/issues/14299#issuecomment-2521711295
