### ISSUE TITLE
Failed to update customer info 

### ISSUE THREAD

**Issue by doc123307** [tailscale/tailscale#14311]
### What is the issue?

I want to buy an additional tariff plan for $5, but when I click “continue to payment derails” I get the error “Failed to update customer info.”. Am I filling out the contact information incorrectly or is the error related to something else? 
![Безымянный](https://github.com/user-attachments/assets/7997eab9-43e9-4efe-aa2f-e68637720638)

Thank you!

### OS

Other

### OS version

 umbrelOS 1.3

### Tailscale version

 1.76.6

**Comment by agottardo** [comment]
Thank you for your report.

Please contact our support team at https://tailscale.com/contact/support as they're the only ones who can look into billing issues. I suggest providing the tailnet name, date-time and IP address you used when you last attempted to perform the purchase.
