### ISSUE TITLE
FR: Use icons to denote connectivity status in `tailscale status`

### ISSUE THREAD

**Issue by Justinzobel** [tailscale/tailscale#14322]
### What are you trying to do?

Make it easier to quickly see which TS nodes are online and which aren't.

### How should we solve this?

Use something similar to systemd's status output:
```
systemctl status some.service
● some.service - Some Service
```
When the service is active (in TS case, online) it shows a nice green dot like above.

When a system service is failed, it uses a red cross:
```
× some.service - Some Service
```

Obviously the colours don't show on GitHub but you get the idea.

### What is the impact of not solving this?

No impact, just a nice ease of use improvement that costs very little.

### Anything else?

N/A

**Comment by Justinzobel** [comment]
I put this together for my usage:
![image](https://github.com/user-attachments/assets/6909b7f7-24e4-4258-b15e-44b71062bd0e)

**Comment by Justinzobel** [comment]
For me green is anything that is not offline.

**Comment by bradfitz** [comment]
What does "offline" mean? There are several definitions.

**Comment by Justinzobel** [comment]
Not connected to the network. I'm not sure what other definitions there are.

**Comment by bradfitz** [comment]
"the network" ... what is "the network"? :)

Some ways you can be both online and offline at the same time:

* your connection to the control plane is broken. You can't get new updates, but metadata for existing peers is fine, and new connections can be established between them.
* your key is expired, but you're connected to the control plane. So you have internet, but nobody can talk to you.
* your connection to your DERP relay is broken. So you can only talk to peers that don't require any NAT traversal.

Or variants of those, like:

* your home/office LAN is up, but the internet is down, so you can only reach Tailscale peers over the LAN.

One little green happy dot doesn't adequately express the various states.

**Comment by Justinzobel** [comment]
I have made my own solution so I'm not really motivated to debate it any further. Good luck with the project!
