### ISSUE TITLE
FR: 'm having trouble seeing all the devices in my network.

### ISSUE THREAD

**Issue by Deridder-TailScale** [tailscale/tailscale#14335]
### What are you trying to do?

Good evening,
I'm having trouble seeing all the devices in my network.

I have configured this: https://tailscale.com/kb/1019/subnets

I can only see the devices on which I have installed Tailscal

Can you help me?

Thanks in advance

### What is the impact of not solving this?

I can't use printers

**Comment by bradfitz** [comment]
For support, see https://tailscale.com/kb/1250/support-options

The issue tracker is primarily for bugs and feature requests. This is labeled as a feature request, but I imagine that was accidental.

**Comment by bradfitz** [comment]
> I have configured this: https://tailscale.com/kb/1019/subnets
>
> I can only see the devices on which I have installed Tailscal

The device list doesn't include devices behind subnet routers. But if you e.g. ping them, that'll go via subnet routers.

In the future we plan to surface devices/services we find on the network behind subnet routers, but we're trying to be careful in how we do that without being too aggressive/spammy.

**Comment by Deridder-TailScale** [comment]
Good evening Brad,

As you can see on the screenshots below, all subnet routes are well configured.

On the 10.0.17.0 network, I have a scanner in 10.0.17.240 that needs to access the server in 10.2.0.13 via an SMB share in order to do a scan to folder.
In this case, I only see devices that have tailscale installed.  Why can't I reach 10.2.0.13 from my printer?
Thank you in advance
JMI


***@***.******@***.******@***.***


[https://storage.letsignit.com/626bbca07211c0b9b0c951ef/generated/effects_cda592f99d79d0197ac96be541764752b01b0f8a71570167f034fcc3.png]

Jean‑Marc Idon

Responsable de pôle

System & Networking ‑ Cloud

Contacter le support system & networking :

+32 4 344 65 35

***@***.******@***.***>

[Site web Brainstorming]<https://cloud.letsignit.com/collect/bc/62ab38b2c2d900731be2251e?p=ePGtUVI194IYcErLiElHkDgk40GmYpnS3ITTHem_0zTfy2uGfLilYEthFxmbFSi15FEeKYeTezZ3amP0vZXbJu1zL-Di9ysePn4oOgVT1opIpI4TD97gA3EUioQJxtdZekYWtSbeF8r9F32QayeOrBQTTmPUjJGaiVnQ6FKPiPw=>

Rue de l'Avancée Numérique 1 à 4430 ANS<https://cloud.letsignit.com/collect/bc/62ab38b2c2d900731be2251e?p=ePGtUVI194IYcErLiElHkDgk40GmYpnS3ITTHem_0zTfy2uGfLilYEthFxmbFSi15FEeKYeTezZ3amP0vZXbJu1zL-Di9ysePn4oOgVT1oqvPNOCsDTx5fL_-B-UteovdO082whvXdt9NAdww6ST0QYo1kgb0Mi9ltW0dO_ioYlOqsIOmPht4Cv2T2UvH4Iql5U9InviM-kHCQrp6KfB-eXsx_lLuLbTUD0H9EcXQ4zd7G3DS1MH8SO4FRqSlePdp8ardSE4tP2E7QG2Y-_Dn9J2_c8OcKRzn_a-8t7NQSdtz7sgBXGYJoI6eVlBYILXr-mJouEf-m3OXhp28Kmk6yjSEO22Kd-63lkO6GfCb3iJiblqWwDIE1hqp5UVPoGR>

+32 4 342 22 21

www.brainstorming.be<https://cloud.letsignit.com/collect/bc/62ab38b2c2d900731be2251e?p=ePGtUVI194IYcErLiElHkDgk40GmYpnS3ITTHem_0zTfy2uGfLilYEthFxmbFSi15FEeKYeTezZ3amP0vZXbJu1zL-Di9ysePn4oOgVT1oqTBpvcYXE-QRWrXfgocc-C3u7aoYdJaPDtAGgqxvIH9g==>

[Facebook]<https://cloud.letsignit.com/collect/bc/62ab38b2c2d900731be2251e?p=ePGtUVI194IYcErLiElHkDgk40GmYpnS3ITTHem_0zTfy2uGfLilYEthFxmbFSi15FEeKYeTezZ3amP0vZXbJu1zL-Di9ysePn4oOgVT1oqR9mDprgJhWMsqBPSJHm4Un_feTHVvhOM62d1TN254yw0Q-lAyaCpUSpnR0OPJGRpYUlReY_cJtqEaVpPlKXZ8>

[LinkedIn]<https://cloud.letsignit.com/collect/bc/62ab38b2c2d900731be2251e?p=ePGtUVI194IYcErLiElHkDgk40GmYpnS3ITTHem_0zTfy2uGfLilYEthFxmbFSi15FEeKYeTezZ3amP0vZXbJu1zL-Di9ysePn4oOgVT1ophTcVwPAe6mQ680D3ZWm5xcwy4NhiuTo2DOVCl340_smdCBxCFb-tZ8hrVSmTZWUMqE-X6bunOofUbKvZrSb4r>

[Youtube]<https://cloud.letsignit.com/collect/bc/62ab38b2c2d900731be2251e?p=ePGtUVI194IYcErLiElHkDgk40GmYpnS3ITTHem_0zTfy2uGfLilYEthFxmbFSi15FEeKYeTezZ3amP0vZXbJu1zL-Di9ysePn4oOgVT1oqBiOsyK5odmINK1IeEpuGTQzYfPb0uCGXxkcTIVjRIZ2e0dG4K_dc5vIEnFq1Wcvn5wjd_xxzFBgFjkdjwdiur>



De : Brad Fitzpatrick ***@***.***>
Envoyé : lundi 9 décembre 2024 20:17
À : tailscale/tailscale ***@***.***>
Cc : Brainstorming - System & Networking ***@***.***>; Author ***@***.***>
Objet : Re: [tailscale/tailscale] FR: 'm having trouble seeing all the devices in my network. (Issue #14335)


I have configured this: https://tailscale.com/kb/1019/subnets

I can only see the devices on which I have installed Tailscal

The device list doesn't include devices behind subnet routers. But if you e.g. ping them, that'll go via subnet routers.

In the future we plan to surface devices/services we find on the network behind subnet routers, but we're trying to be careful in how we do that without being too aggressive/spammy.
