### ISSUE TITLE
android: consider setting DevicePolicyManager.setAlwaysOnVpnPackage

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1433]
An Android VPN can set itself to be always-on:

https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setAlwaysOnVpnPackage(android.content.ComponentName,%2520java.lang.String,%2520boolean)

Should we?

cc @eliasnaur

**Comment by eliasnaur** [comment]
I don't think there's anything to do, unless the Android app doesn't work in always-on mode for some reason. The API you link to is meant for device managers to enable always-on, not for VPNs to configure themselves.

**Comment by DentonGentry** [comment]
That is in Settings, and it seems to work.
![Screenshot_20210318-080755](https://user-images.githubusercontent.com/1140756/111649256-6c479300-87c1-11eb-981b-a8e781ccc444.png)
