### ISSUE TITLE
TailscaleLoginItemHelper-sys crashes on macOS 11 due to invalid @rpath.

### ISSUE THREAD

**Issue by crystall1nedev** [tailscale/tailscale#14356]
### What is the issue?

Not sure when this issue first appeared, but it seems that `TailscaleLoginItemHelper-sys` does not have proper rpaths to function on macOS 11. Swift Concurrency on macOS 10.15 and 11 require developers to include a copy of `libswift_Concurrency.dylib` in a location that is accessible from the executable, and actively referenced. I had noticed that on my machine, I was getting this error:

```
Dyld Error Message:
  can't resolve symbol _swift_task_create in /Applications/Tailscale.app/Contents/Library/LoginItems/TailscaleLoginItemHelper-macsys.app/Contents/MacOS/TailscaleLoginItemHelper-macsys because dependent dylib @rpath/libswift_Concurrency.dylib could not be loaded
```

I then used objdump to show the rpaths of the executable, and it was revealed that it only checks for `/usr/lib/swift`. On macOS 11, `/usr/lib/swift/libswift_Concurrency.dylib` doesn't exist - therefore, the crash occurs.

Tested with the latest current release as of writing (1.78.1), on both x86_64 and arm64.

Here's a crash log just for good measure:
[TailscaleLoginItemHelper-sys.txt](https://github.com/user-attachments/files/18088566/TailscaleLoginItemHelper-sys.txt)

### Steps to reproduce

- Install macOS 11.
- Open Tailscale, set it up, etc.
- Enable "Launch Tailscale at login"
- Check /Library/Logs/DiagnosticReports for `TailscaleLoginItemHelper-sys`

### Are there any recent changes that introduced the issue?

Not sure.

### OS

macOS

### OS version

macOS 11.2.3, macOS 11.7.10

### Tailscale version

1.78.1

### Other software

N/A in this case.

### Bug report

N/A in this case.

**Comment by agottardo** [comment]
Thanks for reporting this. We're investigating... it's a straightforward fix, this was likely regressed by a bad build flag in Xcode.

**Comment by agottardo** [comment]
We pushed a fix for this, thanks for reporting! Please test using unstable release v1.79.9 or newer (download [here](https://pkgs.tailscale.com/unstable/#macos)).

**Comment by crystall1nedev** [comment]
Will do! Downloading now.

**Comment by crystall1nedev** [comment]
Works perfect!

**Comment by shomeax** [comment]
what exactly was the build flag, if you can share the information. I'm trying to rebuild an application for MacOs 11
