### ISSUE TITLE
FR: Custom IP DNS Android APP VPN

### ISSUE THREAD

**Issue by invitadosgarpei** [tailscale/tailscale#14361]
### What are you trying to do?

I am trying to set an IP for the DNS on the mobile other than 100.100.100.100. I do not want the address 100.100.100.100 to forward the DNS requests but rather have the requests reach my DNS server directly.

### How should we solve this?

on the dns settings screen add a new option to select to be able to write an ip

**Comment by agottardo** [comment]
You may already configure a custom DNS server in the admin console.
