### ISSUE TITLE
Tailscale SSH encountered an error during the session, the machine may be offline.

### ISSUE THREAD

**Issue by eliskovets** [tailscale/tailscale#14371]
### What is the issue?

Can't connect to an instance with `tailscale ssh`
Need some support. 
The machine is visible in the Tailscale admin console, but i'm getting `Tailscale SSH encountered an error during the session, the machine may be offline.` when trying to connect to it via web interface. 
Bug report - BUG-1f328b51db43bacaa4a0ddee5f9cded3e395e2413a63fc8311fcbe85bfce1ead-20241212153133Z-b08d2319a30692f1

### OS

Rocky Linux 

### OS version

Rocky Linux release 9.4 (Blue Onyx)

### Tailscale version

1.78.1

### Bug report

BUG-1f328b51db43bacaa4a0ddee5f9cded3e395e2413a63fc8311fcbe85bfce1ead-20241212153133Z-b08d2319a30692f1

**Comment by venkatamutyala** [comment]
@eliskovets did you find a solution? I am having this issue often

**Comment by eliskovets** [comment]
> @eliskovets did you find a solution? I am having this issue often

I ended up configuring https://tailscale.com/kb/1146/pfsense#static-nat-port-mapping and it did solve the issue for me.
