### ISSUE TITLE
Ship Tailscaled-on-macOS static binaries on pkgs.tailscale.com

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1438]
tailscaled can now function on macOS (sans GUI), as an alternative to running the app store version. We should build and push stable+unstable builds to pkgs.tailscale.com.

**Comment by bradfitz** [comment]
I looked into this a bit a few weeks ago.

It seems the way to do cross-compile darwin cgo binaries from Linux is xgo: https://github.com/karalabe/xgo ... but it's not been maintained in awhile. 

The guts of it, though, are https://github.com/karalabe/xgo/blob/master/docker/base/Dockerfile (search for "macos") which led me to:

https://github.com/tpoechtrager/osxcross "The goal of OSXCross is to provide a well working macOS cross toolchain for
Linux, FreeBSD, OpenBSD, and Android (Termux)."

Then I convinced myself it was all possible but annoying and went back to working.

**Comment by bradfitz** [comment]
Alternatively, we build on a Mac and have our CI upload binaries somewhere.

**Comment by bradfitz** [comment]
Many great replies on how to build macOS binaries from Linux in this thread:

https://twitter.com/bradfitz/status/1370462639831146497

Notably, this looks intriguing:

https://dev.to/kristoff/zig-makes-go-cross-compilation-just-work-29ho

**Comment by DentonGentry** [comment]
I think this is done, albeit not discoverable right now.

**Comment by DentonGentry** [comment]
There is not an ETA for the static binaries.

The expectation is that the binaries built in this way will be feature complete, but they use a more recent MacOS technology called a System Extension and thus will only work on very recent MacOS versions. The Network Extension used in the current App Store build is able to support several years back to MacOS 10.13.

**Comment by jjo93sa** [comment]
Thanks for the reply. If general shipping hasn't got an ETA, is it possible to get access to an early release somehow? I'd like to include evaluation of Tailscale at work, but can't install from the App Store, and installing through go leaves me with a version that I can't get DNS working in.

**Comment by DentonGentry** [comment]
Since this bug was filed, homebrew added a tailscale package: https://formulae.brew.sh/formula/tailscale

I think this meets the need: it provides a proper package manager for the tailscaled-on-macOS package, with an uninstaller and mechanism to keep it updated.
