### ISSUE TITLE
Deleting S3 audit log streaming dialog has missing text

### ISSUE THREAD

**Issue by abeluck** [tailscale/tailscale#14394]
### What is the issue?

![image](https://github.com/user-attachments/assets/211ad7bc-05f6-4723-a14d-8cbe2511e828)

The dialog says "Are you sure you want to delete the endpoint at:" but there is nothing after it.

### Steps to reproduce

1. Have S3 log streaming enabled
2. Click the "Delete" option under "..."

### OS

Linux

### Tailscale version

n/a

**Comment by dsnet** [comment]
\cc @oxtoacart @mpminardi

**Comment by mpminardi** [comment]
Thanks for reporting this @abeluck! This should now be fixed with the dialog showing an endpoint of the form:

`https://[bucket-name].s3.[bucket-region].amazonaws.com`
