### ISSUE TITLE
after upgraded to version 1.78.1 and reboot devices, almost all of devices are using "relay" network not "direct network..."

### ISSUE THREAD

**Issue by huangsen365** [tailscale/tailscale#14396]
### What is the issue?

after upgraded to version 1.78.1 and reboot devices, almost all of devices are using "relay" network not "direct network..."

### Steps to reproduce

after upgraded to version 1.78.1 and reboot devices, almost all of devices are using "relay" network not "direct network..."

### Are there any recent changes that introduced the issue?

after upgraded to version 1.78.1 and reboot devices, almost all of devices are using "relay" network not "direct network..."

### OS

Linux, macOS, Windows, iOS

### Other software

after upgraded to version 1.78.1 and reboot devices, almost all of devices are using "relay" network not "direct network..."

**Comment by bradfitz** [comment]
There's no information here from which we can debug anything. You did not include a `tailscale bugreport` identifier.

**Comment by bradfitz** [comment]
I'm going to close this for now until there's something to work from.
