### ISSUE TITLE
Health check ip6tables error: unknown option "--set-mark"

### ISSUE THREAD

**Issue by aspurr** [tailscale/tailscale#14410]
### What is the issue?

Running Tailscale on Ubuntu 22.04.5 for about a year with no issues. All of a sudden the exit node no longer works and I'm getting the following error at the end of Tailscale status:

Health check:
    - adding [-i tailscale0 -j MARK --set-mark 0x40000/0xff0000] in v6/filter/ts-forward: running [/usr/sbin/ip6tables -t filter -A ts-forward -i tailscale0 -j MARK --set-mark 0x40000/0xff0000 --wait]: exit status 2: ip6tables v1.8.7 (nf_tables): unknown option "--set-mark"

### OS version
Ubuntu 24.04.5

### Tailscale version
1.78.1

### Bug report
BUG-26775a60ecdff16e8244929aa75109ce161dceb8e5a098b1906d4e70dc0a5a99-20241217181330Z-1126d14895d33e98

**Comment by masterwishx** [comment]
same issue on oracle cloud with ubuntu 20.4, maybe related to https://github.com/tailscale/tailscale/issues/13863

**Comment by Kemichal** [comment]
Same problem here after update with Canonical Ubuntu 22.04 kernel
`5.15.0-128-generic #138-Ubuntu SMP Sat Nov 30 22:28:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vladimir-ch** [comment]
It seems Canonical backported the kernel bug in "netfilter: xtables: avoid NFPROTO_UNSPEC where needed" to their 5.15.0-127 kernel and the fix is still not present in 5.15.0-128. For now we had to downgrade to 5.15.0-126.

**Comment by timtailscale** [comment]
Thanks for bringing this to our attention! This appears to be the same bug as in #13863 as previously discussed. As a workaround instead of downgrading to a previous kernel you can instead swap Tailscale into `nftables` mode by adding `TS_DEBUG_FIREWALL_MODE=nftables` to the file at `/etc/default/tailscaled` and restarting Tailscale with `sudo systemctl restart tailscaled.service`.

Hopefully a patched kernel is released soon so this workaround is not necessary.

**Comment by aspurr** [comment]
> Thanks for bringing this to our attention! This appears to be the same bug as in #13863 as previously discussed. As a workaround instead of downgrading to a previous kernel you can instead swap Tailscale into `nftables` mode by adding `TS_DEBUG_FIREWALL_MODE=nftables` to the file at `/etc/default/tailscaled` and restarting Tailscale with `sudo systemctl restart tailscaled.service`.
> 
> Hopefully a patched kernel is released soon so this workaround is not necessary.

Thank you! That did the trick.

**Comment by msteroreo1** [comment]
> Thanks for bringing this to our attention! This appears to be the same bug as in #13863 as previously discussed. As a workaround instead of downgrading to a previous kernel you can instead swap Tailscale into `nftables` mode by adding `TS_DEBUG_FIREWALL_MODE=nftables` to the file at `/etc/default/tailscaled` and restarting Tailscale with `sudo systemctl restart tailscaled.service`.
> 
> Hopefully a patched kernel is released soon so this workaround is not necessary.

OMG I've been going crazy for 2 days changing any linux config file and parameters I could and this just did the work. God bless you @timtailscale

**Comment by steled** [comment]
For Ubuntu a new kernel version is released which fixed the problem: [5.15.0-130.140](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2091990)

**Comment by masterwishx** [comment]
> TS_DEBUG_FIREWALL_MODE=nftables

for ubuntu-oracle will be fixed only in monday , so we need to move to nftables or just make change it so tailscale will not use iptables ?

**Comment by j-ckal** [comment]
Same issue on 6.8.0-56

**Comment by kquinsland** [comment]
> Same issue on 6.8.0-56

I found this thread while diagnosing a calico/k8s issue but the underlying cause appears to be the same.
I did an `apt update` and a reboot and came back to a similar error spewing in logs.

A quick look at what kernel(s) I have:

```shell
me@node:/boot$ ls -lah initrd*
lrwxrwxrwx 1 root root  27 Mar 31 07:52 initrd.img -> initrd.img-6.8.0-56-generic
-rw-r--r-- 1 root root 66M Mar 31 07:52 initrd.img-6.8.0-55-generic
-rw-r--r-- 1 root root 66M Mar 31 07:52 initrd.img-6.8.0-56-generic
lrwxrwxrwx 1 root root  27 Mar 31 07:52 initrd.img.old -> initrd.img-6.8.0-55-generic
```

I updated my grub config to boot off of the .55 and rebooted and that seems to have done the trick.

WORKING:

```
Linux node 6.8.0-55-generic #57-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 12 23:42:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by adamf-kela** [comment]
> Thanks for bringing this to our attention! This appears to be the same bug as in [#13863](https://github.com/tailscale/tailscale/issues/13863) as previously discussed. As a workaround instead of downgrading to a previous kernel you can instead swap Tailscale into `nftables` mode by adding `TS_DEBUG_FIREWALL_MODE=nftables` to the file at `/etc/default/tailscaled` and restarting Tailscale with `sudo systemctl restart tailscaled.service`.
> 
> Hopefully a patched kernel is released soon so this workaround is not necessary. Kernel 5.15.0-130-generic is confirmed to fix this issue, please update rather than applying the above workaround if possible!

this issue just started occurring for me now (i've had no trouble until now), this solution still works 🙏

**Comment by bloodstiller** [comment]
> > Thanks for bringing this to our attention! This appears to be the same bug as in [#13863](https://github.com/tailscale/tailscale/issues/13863) as previously discussed. As a workaround instead of downgrading to a previous kernel you can instead swap Tailscale into `nftables` mode by adding `TS_DEBUG_FIREWALL_MODE=nftables` to the file at `/etc/default/tailscaled` and restarting Tailscale with `sudo systemctl restart tailscaled.service`.
> > Hopefully a patched kernel is released soon so this workaround is not necessary. Kernel 5.15.0-130-generic is confirmed to fix this issue, please update rather than applying the above workaround if possible!
> 
> this issue just started occurring for me now (i've had no trouble until now), this solution still works 🙏

Can confirm same issue, with: Linux 6.8.0-57-generic #59-Ubuntu, used fix above and it resolved it for me.

**Comment by kmanwar89** [comment]
Just chiming in with another "me too!" for this issue on 24.04.1 running 6.8.0-57-generic #59

```
❯ uname -a
Linux shadowserverprod 6.8.0-57-generic #59-Ubuntu SMP PREEMPT_DYNAMIC Sat Mar 15 17:40:59 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
❯ date
Sat Apr 19 04:23:06 PM EDT 2025
```

Confirming applying the workaround has removed those errors from the output of `sudo tailscale status`

Any ideas if/when a permanent fix might be put into place @timtailscale ?

**Comment by timtailscale** [comment]
The main issue that this is being tracked on is #13863, but the issue is in the kernel not with Tailscale. Please reach out to your kernel maintainers to pull in the fix discussed in the other issue, as the permanent fix will come from a kernel patch.

**Comment by lorenzbaum** [comment]
> The main issue that this is being tracked on is [#13863](https://github.com/tailscale/tailscale/issues/13863), but the issue is in the kernel not with Tailscale. Please reach out to your kernel maintainers to pull in the fix discussed in the other issue, as the permanent fix will come from a kernel patch.

Yes, that is correct. Though I suggest that Tailscale should detect this problem and automatically switch to nftables or, at least, recommend the fix. Otherwise, for the average user, Tailscale suddenly stops functioning for no reason.

**Comment by tpetry** [comment]
For anything finding this: I encountered this problem. Some servers in my fleet had the issue, some not. It was just a missing kernel module for me.

`sudo modprobe xt_mark` reported that the module is missing, a simple `sudo dnf install -y kernel-modules-extra` solved the issue.
