### ISSUE TITLE
Allow easily specifying "all internal users" in ACLs

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#1447]
With the introduction of sharing, the semantics of `Users: ["*"]` in ACLs have changed slightly. While `*` has always meant "all users of my network", it's ambiguous whether shared users are included in that or not. (They are.) Many users have (naturally, expectedly) understood `*` to mean only members of their network.

We provided `autogroup:shared` to allow users to easily write ACLs targeted users invited to share specific machines, but we haven't yet followed through on our proposals for a `autogroup:members` or `autogroup:internal`, which is an explicit list of all internal users of your network.

Users shouldn't have to maintain a manual `Group` of all users in their network, which is prone to error. Instead, we should either update `*`'s meaning or add an `autogroup:internal`-like tag.

**Comment by mayakacz** [comment]
Continuing from internal Slack discussion.

We already have:
* `autogroup:self` to allow ACLs for users to access their own devices
* `autogroup:shared` for users who have access to a given shared device (is that the right meaning?)

#### Use case

There's a few use cases for additional autogroups of users:
* I would like to write an ACL to refer to all humans in my network, without including tagged devices. For example, I might write an ACL allowing all humans to access their own devices, and all humans to access tagged devices, but not allow tagged devices to access humans' devices. This needs a "human in my network" group.
* I would like to write an ACL to refer to all humans in my network, without including shared users. For example, I might want everyone in my organization to access everything on port 80, but not contractors who I shared the device with, who I restrict to a different port. In this case, as noted above, `*` does not work. This needs a "human in my network but not shared" group.
* I would like to write an ACL to refer to all tagged devices in my network. Right now, this _is_ possible by applying the same tag, say, `tag:server`, to all those devices.

#### Need

So it sounds like we may be missing a way to refer to all humans (well, users with SSO) in an organization _without_ including shared users.

* If we create such a group, then a user can always specify they want all humans plus shared users with group + `autogroup:shared`. We could consider simplifying this in the future.
* We might consider adding something like `autogroup:tagged` to refer to all tagged devices as well. 

#### What to call this?

We discussed the options `autogroup:users`, `autogroup:untagged`, `autogroup:members`, and `autogroup:humans`. Some points that were brought up in Slack:
* `users` could be unclear as it's used in several places already. Namely, Tailscale's ACL file permits the use of "users" for sources.
* `untagged` could be easily misread as `tagged`.

**I propose that we introduce `autogroup:members` for all humans in an organization without shared users.** Members signifies being part of the organization. This is preferable to "users", although entities in SSO are generally called "users". If we did add `autogroup:tagged` in the future, however, it's not obvious that `members` is the opposite of `tagged`.

**Comment by maisem** [comment]
> ```* =  autogroup:members + autogroup:shared + autogroup:tagged```

This makes the special `autogroup:self` a little weird. It currently only works for `*` as the src and would now be inconsistent with the new definition of `*`.

**Comment by TomSpidge** [comment]
> > `* =  autogroup:members + autogroup:shared + autogroup:tagged`
> 
> This makes the special `autogroup:self` a little weird. It currently only works for `*` as the src and would now be inconsistent with the new definition of `*`.

Would `autogroup:self` not be a subset of `autogroup:members` though? In the same way that `tag:some-tag` would be included in `autogroup:tagged`.
So I would think having members included in the src and allowing self as the host would be consistent,

**Comment by bradfitz** [comment]
> `* =  autogroup:members + autogroup:shared + autogroup:tagged`

`*` also includes IPs behind subnet routers that don't map to Tailscale users or nodes, no?

**Comment by darshinimashar** [comment]
How about "autogroup:admin" as well, as we are focusing on tailnet roles, we should include this as well.

**Comment by mayakacz** [comment]
> I propose that we introduce autogroup:members for all humans in an organization without shared users.

This still makes sense.

This would allow someone to write: all humans to access their own devices, and all humans to access tagged devices, but not allow tagged devices to access humans' devices. Great!

---

Separately, I think we're discussing, what is the total sum of groups that someone might need to write policy?

>> * = autogroup:members + autogroup:shared + autogroup:tagged

> This makes the special autogroup:self a little weird. It currently only works for * as the src and would now be inconsistent with the new definition of *.

Right now, `autogroup:self` only works for `members`. This is confusing as saying `*` can access `autogroup:self:*` isn't universally true. To do the same with tags, an ACL would have to be for `tag:a` to access `tag:a:*` for example. There isn't a generalized way to do this for *all* tags.
I think this is right? Although some users will want everything tagged `prod` to access everything else tagged `prod`, there are definitely some users who will *not* want this, and want `prod` to only access `logging`. If we were to change this, that would be a breaking change, and we would need to give those users a way to still implement the more restrictive policy.

> * also includes IPs behind subnet routers that don't map to Tailscale users or nodes, no?

I would assume it does? I'm not sure. I'm not sure how we would apply policy to these.

So, it doesn't seem that `*` can really be defined as above. It's more like,
```
All Tailscale IPs in your subnet = autogroup:members + autogroup+shared + autogroup:tags
* = autogroup:members + autogroup+shared + autogroup:tags + devices in subnets without Tailscale IPs
```
but `autogroup:self` only applies to `members`, not `*`. That's confusing.

Does that match what folks are thinking?

---

Open questions:
* Should we have `autogroup:tags`? (I think `tags` makes more sense than `tagged` if we're using `members`.) This is already possible today by using the same tag on every tagged device.
* Should `autogroup:self` or something like it apply to tagged devices? This is possible with one ACL per tag, and changing this would be a breaking change.

These are both possible today, but not ideal experiences. Suggest tracking these as new potential FRs.

**Comment by mayakacz** [comment]
Chatted with @darshinimashar that using `members` might be confusing as we also refer to the role of a user who can access a tailnet as a Member. I think this is OK:
* It maps in concept. An individual who is in `autogroup:members` would be in the tailnet, with at least Member permissions.
  + They could be a role other than 'Member', but would have at least Member permissions
  + They might not *yet* exist in the tailnet, but would get these permissions upon joining. But that's also true for Member
* If we introduced a way to refer to user roles in ACLs, we could use a different syntax, e.g., `role:admin`. This _would_ be potentially confusing, to have something like `role:member` and `autogroup:members`.
  +  The intent isn't to use user role groups in ACLs, but define groups in ACLs.

**Comment by mayakacz** [comment]
`autogroup:members` shipped yesterday: https://tailscale.com/changelog/#2022-03-10-service

Closing this issue. Will track `autogroup:tags` (https://github.com/tailscale/tailscale/issues/4148) and `autogroup:self` applying to tags (https://github.com/tailscale/tailscale/issues/4149) in new issues.
