### ISSUE TITLE
build_docker.sh doesn't quote properly in some shells?

### ISSUE THREAD

**Issue by tanuck** [tailscale/tailscale#1449]
**Describe the bug**
I wanted to build a container for v1.4.5 using the "official" Dockerfile in this repo, but I get the following error:

```
....
Step 9/13 : RUN echo $GOFLAGS
 ---> Running in ba3b67d33470
'-tags xversion -ldflags -X tailscale.com/version.Long=1.4.5-tb89c65304 -X tailscale.com/version.Short=1.4.5 -X tailscale.com/version.GitCommit=b89c653046881cd6ce3758d1bc2741de940831f8-dirty'
Removing intermediate container ba3b67d33470
 ---> cdd494dfbd0d
Step 10/13 : RUN go install -v ./cmd/...
 ---> Running in 30963113b424
go: parsing $GOFLAGS: non-flag "'-tags"
The command '/bin/sh -c go install -v ./cmd/...' returned a non-zero code: 1
```

**To Reproduce**
1. Go to root of repo
2. Run `./build_docker.sh`

**Expected behavior**
Container to build successfully.

**Version information:**
 - Device: [e.g. iPhone X, laptop]
 - OS: Ubuntu
 - OS version: 20.10
 - Tailscale version: v.1.4.5

**Comment by bradfitz** [comment]
Yeah, I see the same thing.

That script was added in fec9490378604bf9acfecbdac915bebee66cac8c. @StevenACoffman, which `sh` do you use? Maybe your shell's quoting rules make this work:

```
GOFLAGS='-tags xversion -ldflags '"-X tailscale.com/version.Long=${VERSION_LONG} -X tailscale.com/version.Short=${VERSION_SHORT} -X tailscale.com/version.GitCommit=${VERSION_GIT_HASH}"
docker build --build-arg goflags_arg="'""${GOFLAGS}""'" -t tailscale:tailscale .
```

But it doesn't work for me with `dash`.

/cc @danderson

**Comment by tanuck** [comment]
I also tried with zsh v5.8 and bash v5.0, both had the same failure.

**Comment by StevenACoffman** [comment]
It doesn't matter what shell you are using by default, as the script shebang on line 1 forces it to run in a posix shell, which does not support brace expansion. Brace expansion worked in bash, zsh and ksh. I changed the shebang to be consistent but then unthinkingly failed to retest. PR forthcoming to fix it to be portable (and generally less brittle without all the complicated quoting).

My bad, sorry.

**Comment by mkramlich** [comment]
I had to fix an equivalent issue in brew. the nested ldflags are Fun to get quoting just right
