### ISSUE TITLE
STUN lookups seem very aggressive with DNS lookups

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#145]
User report on twitter that that tailscaled is responsible for 7/10 of the most frequently queried DNS names on their LAN (https://twitter.com/33b5e5/status/1235461382054662144). Most of those are derpX.tailscale.com, with stun.l.google.com mixed in. The latter makes me think that all these queries are coming from the STUN logic, but I haven't dug yet.

**Comment by bradfitz** [comment]
Go doesn't have an in-process DNS cache by default.

We could add one, which would be useful & fun to write & share in general, but I should stay focused on other stuff right now. Usually people have a caching resolver very nearby.

**Comment by bradfitz** [comment]
Actually this is amazingly terrible watching my home CoreDNS logs.

I'm getting a number of REFUSED (rate-limited errors?):

```
Mar 05 08:47:54 gw coredns[25999]: 10.0.47.1:57817 - [05/Mar/2020:08:47:54 -0800] 518 "AAAA IN derp3-v6.tailscale.com. udp 40 false 512" REFUSED qr,rd,ra 40 21.3077ms
Mar 05 08:47:54 gw coredns[25999]: 10.0.47.1:59509 - [05/Mar/2020:08:47:54 -0800] 50420 "A IN derp2.tailscale.com. udp 37 false 512" REFUSED qr,rd,ra 37 21.29898ms
Mar 05 08:47:54 gw coredns[25999]: 10.0.47.1:47087 - [05/Mar/2020:08:47:54 -0800] 3287 "A IN derp1.tailscale.com. udp 37 false 512" REFUSED qr,rd,ra 37 20.33371ms
Mar 05 08:47:54 gw coredns[25999]: 10.0.47.1:52420 - [05/Mar/2020:08:47:54 -0800] 42412 "A IN derp4.tailscale.com. udp 37 false 512" REFUSED qr,rd,ra 37 20.708337ms
Mar 05 08:47:54 gw coredns[25999]: 10.0.47.1:39839 - [05/Mar/2020:08:47:54 -0800] 46679 "AAAA IN derp2.tailscale.com. udp 37 false 512" REFUSED qr,rd,ra 37 21.164249ms
Mar 05 08:47:54 gw coredns[25999]: 10.0.47.1:41003 - [05/Mar/2020:08:47:54 -0800] 63981 "AAAA IN derp4.tailscale.com. udp 37 false 512" REFUSED qr,rd,ra 37 21.045294ms
```

So upping priority here.

**Comment by danderson** [comment]
Yeah, I think this is also the root cause of your netchecks yesterday failing to resolve some random subset of derp DNS names - we're so aggressive that with just a few tailscaled's on the LAN, lookups are getting rate-limited.

Switched label to bug, because I think this is causing problems more than just cosmetic.

**Comment by 33b5e5** [comment]
Y'all still generate _a lot_ of DNS queries. 6 out of the top 10 on my LAN (I cropped the rest for privacy). This is from my pi-hole.

<img width="370" alt="noise" src="https://user-images.githubusercontent.com/2781306/78632825-dedf8d00-7854-11ea-94b2-53268edc1102.png">

I have a few clients connected to Tailscale, but this seems a bit much. Are the records expected to change often?
