### ISSUE TITLE
tailscale ping responds with "server misbehaving" when hostname doesn't exist

### ISSUE THREAD

**Issue by namansood** [tailscale/tailscale#1452]
**Describe the bug**
`tailscale ping magnesium` responds with `error looking up IP of "magnesium": lookup magnesium on 127.0.0.53:53: server misbehaving`, where magnesium is a device not present on this tailnet.

**Expected behavior**
It should say "no matching peer" or "no such host".

**Version information:**
 - Device: laptop
 - OS: Linux
 - OS version: Ubuntu 20.04
 - Tailscale version: 1.5.120

**Additional context**
`tailscale ping 123456` (any numeric string) says "no such host", while `tailscale ping 100.200.200.100` (an IP address) says "no matching peer". It would be nice to have the same error message, but maybe that's not so important?

**Comment by DentonGentry** [comment]
In 1.8.x:
```
$ tailscale ping magnesium
error looking up IP of "magnesium": lookup magnesium on 100.100.100.100:53: no such host
```
