### ISSUE TITLE
Should netstack mode make localhost services available by default?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1454]
Currently tailscaled in `--tun=userspace-networking` (netstack) mode allows incoming connections to all anything listening on localhost.

@danderson suggests maybe we shouldn't.

#1121 is open about making that opt-in for the normal TUN mode. Perhaps we should also require an explicit opt in like #1121 even for netstack mode.

So then in netstack mode, before doing the forwarding localhost dial, we'd need to ask the kernel whether that address is bound on the unspecified address or not, which sadly is not portable.

/cc @namansood

**Comment by DentonGentry** [comment]
At this point it would be difficult to change this behavior, people now depend on it.

**Comment by DentonGentry** [comment]
Barring further comment, we'll expect to close this during the next bug scrub. The userspace-networking mode has made localhost services available by default for a year now, realistically I don't believe we can change this behavior now.

**Comment by DentonGentry** [comment]
At this point I do not believe we could reasonably change this default behavior in `--tun=userspace-networking` mode
