### ISSUE TITLE
Running tailscale form inside debian:buster container (device or resource busy)

### ISSUE THREAD

**Issue by aiqency** [tailscale/tailscale#1457]
I cannot run tailscale inside my debian buster container.
The host: Linux  4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

Dockerfile:
```dockerfile
FROM debian:buster

LABEL name "test-tailscale"

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    apt-transport-https \
    gnupg \
    ca-certificates \
    apt-utils \
    curl \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists*

RUN curl -fsSL https://pkgs.tailscale.com/stable/debian/buster.gpg | apt-key add - > /dev/null \
 && curl -fsSL https://pkgs.tailscale.com/stable/debian/buster.list | tee /etc/apt/sources.list.d/tailscale.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends tailscale \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists*

CMD ["tailscaled"] 
```

Docker command:
```shell
~ $ uname -r
Linux  ... 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

~ $ docker run -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged --cap-add=SYS_MODULE --cap-add=NET_ADMIN tailscale-test
```
Error:
```bash
2021/03/05 12:17:15 logtail started
2021/03/05 12:17:15 Program starting: v1.4.5-tb89c65304-gf09ac28c2, Go 1.15.7-ts02f50cdc: []string{"tailscaled"}
2021/03/05 12:17:15 LogID: 42e1f4f5c504eba32ec0a4c9cc60fb42f1e3c9dd6fb249640be40080051bfa41
2021/03/05 12:17:15 logpolicy: using system state directory "/var/lib/tailscale"
2021/03/05 12:17:15 Starting userspace wireguard engine with tun device "tailscale0"
2021/03/05 12:17:15 Linux kernel version: 4.19.0-13-amd64
2021/03/05 12:17:15 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with:
2021/03/05 12:17:15 logtail: dialed "log.tailscale.io:443" in 170ms
2021/03/05 12:17:15 CreateTUN: device or resource busy
2021/03/05 12:17:15 wgengine.New: device or resource busy
2021/03/05 12:17:15 flushing log.
2021/03/05 12:17:15 logger closing down
```

ifconfig:

```bash
tailscale0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet6 fe80::4b7b:a67f:61ff:5430  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 84  bytes 4032 (3.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
modprobe is not available from the container but tun kernel module is runnig on the host

How tailscale manages tun interfaces and what it detects as error?

**Comment by DentonGentry** [comment]
These are likely relevant:

- https://github.com/tailscale/tailscale/issues/504
- https://github.com/tailscale/tailscale/labels/containers

**Comment by aiqency** [comment]
Yes, thanks for sharing these links. I've been through but didn't help much.
The error is slightly different `device or resource busy`.
However I'm still looking through it.

**Comment by DentonGentry** [comment]
I think Tailscale works in containers as of 1.6. If the container has a /dev/net/tun device it can use Tailscale normally, if there is no tun then the userspace-networking + SOCKS5 approach can be used: https://tailscale.com/kb/1112/userspace-networking/

**Comment by scyto** [comment]
I am running a swarm stack, is there a command i can issue into the container to ensure it doesnt exit and i can attach a terminal
(i can run docker run -it  with a shell if i know what shell it has?)

**Comment by scyto** [comment]
I tried a couple of things:

`sudo docker run -it --rm  -v /dev/net/tun:/dev/net/tun -v /var/lib:/var/lib -v /lib/modules:/lib/modules -e ROUTES=192.168.1.0/24 -e AUTHKEY=redacted  --privileged=true tailscale/tailscale /bin/sh` ran with no issues (in that the were no errors, but it didnt register with tailscale cloud

sudo docker run -it --rm --network host  -v /dev/net/tun:/dev/net/tun -v /var/lib:/var/lib -v /lib/modules:/lib/modules -e ROUTES=192.168.1.0/24 -e AUTHKEY=kJVMVF6CNTRL  --privileged=true tailscale/tailscale /bin/sh` errored in the same way as my stack
`

**Comment by bradfitz** [comment]
@scyto, we don't track closed bugs. Especially bugs that have been closed for a year.

Find an existing open bug or open a new one if you want any attention. There's also https://forum.tailscale.com/ for general discussion.
