### ISSUE TITLE
Connectivity - some machines can connect some cannot

### ISSUE THREAD

**Issue by kellytrinh** [tailscale/tailscale#1458]
Check out your logs for this - 10:25PM at GMT+8

LGGRAM - 100.85.3.43
IntelNUC - 100.98.2.42
Core - 100.97.19.34

LGGRAM can do ping to IntelNUC but not to Core
IntelNUC and Core cannot ping to LGGRAM but can to each other

All running tailscale windows 1.45

**Comment by bradfitz** [comment]
Why did you close this? What was the resolution?

Please always update issues if you're going to close them.
