### ISSUE TITLE
netcheck, magicsock: hermetic testing

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#146]
Right now `magicsock_test.go` contains package-internal logic to swap out DERP/STUN for the magicsock package so the tests don't require a network connection. But they still make network connections because of the netcheck dependency.

Similarly, `ipn/e2e_test.go` connects to network DERP/STUN servers through both magicsock and netcheck.

The magicsock-specific testing needs to be factored out so other packages can use it, and netcheck needs something similar to use in-process DERP/STUN servers.

cc @bradfitz

**Comment by danderson** [comment]
Generalizing slightly: to fix other things in how the linux daemon behaves, we are soon going to have to run custom code for every socket tailscaled creates, which implies plumbing custom dialers and "listener factories" throughout. It happens to also greatly aid testing, but there's at least 2 reasons to do this.

**Comment by bradfitz** [comment]
This was done at some point (mostly with derpmap package in 39c0ae1dba26193f66d9848aa8a2bee4b941ee67).

And pulling stuntest out into a package in b9c6d3ceb8ade5be275b989b8e8ae24b7bc63339

Closing for now. Feel free to reopen with details of what remains, or open new bugs.
