### ISSUE TITLE
cmd/tailscale: add "bugreport" subcommand

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1466]
We want to add a "bugreport" subcommand that gathers a bunch of data from the local machine and uploads it (or prepares a zip or something to mail)

And insert log lines so we can find timezones. Perhaps with a little optional note argument:

```
$ tailscale bugreport --insert-note="start demo"
$ tailscale bugreport --insert-note="end demo"
```

/cc @crawshaw

**Comment by DentonGentry** [comment]
We'll use this as a starter project for someone, assigning it to myself in the interim.
