### ISSUE TITLE
Can BSDs and darwin really be subnet routers / exit nodes?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1475]
cmd/tailscale/cli/up.go contains:

```go
if runtime.GOOS == "linux" || isBSD(runtime.GOOS) || version.OS() == "macOS" {
      upf.StringVar(&upArgs.advertiseRoutes, "advertise-routes", "", "routes to advertise to other nodes (comma-separated, e.g. 10.0.0.0/8,192.168.0.0/2\
4)")
      upf.BoolVar(&upArgs.advertiseDefaultRoute, "advertise-exit-node", false, "offer to be an exit node for internet traffic for the tailnet")  
}
```

The `macOS` check was added in 08949d4ef1082a4373b552d3901351e7a297c62d but I don't think the router_darwin.go code properly handles setting up SNAT with pfctl. (that's #911)

And the BSD routers likewise seem very minimal. The `isBSD` check was added in 2a8e06470569aa2d6add87172072268489a12114. @cynix, are you actually using that code? If so, did you configure your machine's NAT separately?

Oh, I found @danderson's PR comment on that:

https://github.com/tailscale/tailscale/pull/459#pullrequestreview-436828842

> I'm merging this, but note however that we recently revamped the linux router implementation to automatically configure the firewall appropriately for whatever subnet routing was requested. The BSD router implementation lacks this, so as it stands this will just drop packets for subnets out the tuntap interface, and it's up to the system administrator to get the filtering and routing right from there. We (Tailscale) are okay with this for now since we expect BSD users to be aware that some assembly is required, but if you want to keep contributing, making the router more automagic would be a good place to go.

Seems a bit misleading.

Perhaps we can add a big fat warning when those options are used on BSDs to tell them that it won't work automatically as expected?

I'm planning on removing the Darwin support, as I don't think it was ever tested.

**Comment by mkramlich** [comment]
background on darwin/macOS and 08949d4: yes I only added the porcelain up in the CLI, and did no work on any plumbing which it might have needed. I tried to make that clear in the commit message but apparently not. :-) I did test that the porcelain worked and I confirmed that it seemed to take effect in the internal config state of tailscaled. I believe @apenwarr had suggested to me that I add this, in private, in the context of giving me ideas of super simple things to do to start contributing. between him and then you reviewing the code and merging it in, I assumed then that the plumbing was ready and/or it was at least "ok" to surface that advertise option

**Comment by cynix** [comment]
@bradfitz I do indeed have separate routing configs on my machines. It works fine for my use case, so all I needed (and implemented) was for the subnet to be advertised.

I haven’t looked at the Linux implantation too closely, but you mentioned NAT. Is that configured automagically on Linux? What if the user doesn’t want NAT?
