### ISSUE TITLE
Support other IP space (custom) for Tailscale network than 100.64/10. 

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1477]
Customers have started using some of the 100.64/10 space, and they need to change their tailscale client IP addresses.  

Tailscale should be able to support other IP spaces.

**Comment by DentonGentry** [comment]
Moving most internal Tailnet addressing to IPv6 is more likely to be feasible.

**Comment by PaulMcMillan** [comment]
I'll chime in here and mention that I can't use tailscale because you're not my only carrier and I work for a company that (among other things) is a carrier and has legitimate uses for the cgnat space.

**Comment by patrickbeam** [comment]
I work for a large enterprise that is also starting to use this IP space.  I think that IPv6 is feasible assuming we can perform some 6 to 4 natting.

**Comment by DentonGentry** [comment]
Since this issue was filed, an experimental DisableIPv4 setting was added in https://login.tailscale.com/admin/acls:

```
{
  "DisableIPv4": true,
  "ACLs": [
    {
```

**Comment by DentonGentry** [comment]
At this point I do not expect to implement this. We are more likely to recommend `DisableIPv4` for these uses.

**Comment by PaulMcMillan** [comment]
I wanted to follow up here and say that `disableIPv4` seems to be working well for me to solve this problem. Thank you!
