### ISSUE TITLE
Black screen on android go devices

### ISSUE THREAD

**Issue by rugwirobaker** [tailscale/tailscale#1479]
Last year it was impossible to install the tailscale android app on Android Go devices but this has come to pass even though there is a new issue. When you open the app it doesn't go beyond an initial black and blank screen.

**Comment by DentonGentry** [comment]
I'm going to close this as a duplicate of #1008, but could you add some details on #1008 about the type of device, the Android Go version it is running, how much memory it has and, if you know details, the OpenGL ES support?
