### ISSUE TITLE
req: ability to share routes to external users from shared machines

### ISSUE THREAD

**Issue by nergdron** [tailscale/tailscale#1481]
basically, I'm trying to eval tailscale as a replacement for more traditional VPN clients into our cloud / dc networks. given folks are already using tailscale at home, and tailscale doesn't let you use multiple accounts in any reasonable way (issue #713), we need to be able to share our gateway machines for each network, including routes, to users outside out dns domain org.

however, it seems like by intentional design, tailscale blocks this behaviour, even though it's really necessary for any standard vpn use case.

**Describe the solution you'd like**
I want at least an override so I can expose routes from hosts to external users that a host is shared with.

**Describe alternatives you've considered**
we could manually set up firewall management and forwarding on each gateway box, but on the client end there doesn't seem to be any equivalent to wireguard's [pre/post]-[up/down] sections to script adding / removing routes. given tailscale handles all of this nicely and automatically internal to an org, fighting with end user deployment scenarios seems like the wrong path to go down.

**Comment by DentonGentry** [comment]
I may be missing something, but does https://tailscale.com/kb/1019/subnets provide some of this functionality?

**Comment by bradfitz** [comment]
> I may be missing something, but does https://tailscale.com/kb/1019/subnets provide some of this functionality?

This bug is specifically about _sharing_ + subnets ("need to be able to share our gateway machines for each network, including routes, to users outside out dns domain org").

@nergdron, the sharing functionality as launched doesn't yet permit sharing routes, but it's on the roadmap.

**Comment by nergdron** [comment]
@bradfitz cool! I think we'll def wanna use tailscale org wide once that's available, but until then it's gotta remain just a test deployment. looking forward to seeing this land, hopefully sometime soon! :smile:

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1390
