### ISSUE TITLE
admin: add an easier way to copy IP addresses

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#1484]
We show IP addresses throughout the UI, and it's common to want to copy and use those addresses elsewhere for testing in a browser, in the terminal, etc. We should provide an easier mechanic for copying IP addresses, whether it's auto-selecting the text, click-to-copy, or a separate "copy" affordance.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1300
