### ISSUE TITLE
Setting an exit node fail all resolutions on OpenSuse Tumbleweed — /etc/resolv.conf symlink not accepted

### ISSUE THREAD

**Issue by Flameeyes** [tailscale/tailscale#1495]
**Describe the bug**

Nodes:

 - A: exit node running tailscale 1.5.221 on Ubuntu 20.04.
 - B: node running tailscale 1.5.221 on OpenSuse Tumbleweed in a VM, selecting A as exit node.

When selecting A as exit node for B, the routing is set up correctly, but no resolution happens with no DNS traffic happening.

I tracked it down to `/etc/resolv.conf` being a symlink — changing it into a regular file worked like a charm. As far as I could tell the file and the symlink appear to have all the right permissions, so that's not the issue. Maybe an apparmor problem?

**Comment by talway** [comment]
DNS resolution issue not handled，I have the same problem

**Comment by talway** [comment]
https://www.whatismyip.com/ 
This website can be resolved, the other can not be resolved

**Comment by danderson** [comment]
This is likely a variant on https://github.com/tailscale/tailscale/issues/683 . Various software has hardcoded assumptions about /etc/resolv.conf either being a file, or being a symlink into somewhere in /run (for NetworkManager and systemd-resolved). Our current DNS manager setup breaks these assumptions, so things that do sandboxing tend to break.

No trivial fix, unfortunately, but I'm working on revamping our DNS logic for Tailscale 1.8, and I'll include this in the bug family.
