### ISSUE TITLE
Exit Nodes ：Only one web site can be accessed

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#1497]
I installed the unstable version to test the dropout node functionality;

1. American KVM server

2. Local WIN machine

3. Installation Steps Installation

Testing:

You can open the website you gave, but no other website can be opened. DNS error is indicated, please check it, thank you!

The browser says DNS error

KVM version:
1.5.221
  tailscale commit: 1bc3c03562f26bfa9e4e6ad5ef71132ef2cc1847
  other commit: bb10a5700fc3e18264f09c74bb7bb704767249de
  go version: go1.16-tsc76071c0

win10 version:
v1.5.221

**Comment by DentonGentry** [comment]
I don't understand what "website you gave" means; you're able to access only one website?

Can I ask if you have:
+ Nameservers configured in https://login.tailscale.com/admin/dns
+ MagicDNS enabled in https://login.tailscale.com/admin/dns

?

**Comment by talway** [comment]
I'm WIN10 switch to exit node, open a browser and visit the web site, can only open the https://www.whatismyip.com/, other web site can not open, when the browser prompts DNS error

**Comment by talway** [comment]
Same problem as this one

https://github.com/tailscale/tailscale/issues/1495

**Comment by talway** [comment]
Same problem as this one

https://forum.tailscale.com/t/pi-as-vpn-router-to-access-tailscale-and-use-exit-node/455

**Comment by DentonGentry** [comment]
Can I ask if you have:

- Nameservers configured in https://login.tailscale.com/admin/dns
- MagicDNS enabled in https://login.tailscale.com/admin/dns

?

**Comment by talway** [comment]
Not set. Does this have to be set? But your documentation doesn't say it has to be set?

**Comment by talway** [comment]
Instead of using this setting, can I use the exit node's own DNS?

**Comment by DentonGentry** [comment]
No, it does not have to be set. I'm just looking for factors which might be involved in the problem. Since DNS stops working, the DNS settings in Tailscale seem relevant.

The exit node should work, even with no Nameservers configured in https://login.tailscale.com/admin/dns
We'll have to look into what is going wrong.

**Comment by talway** [comment]
I checked the problem raised by your lock today and configured DNS, but it still didn't work. If you test it, it's just me

**Comment by talway** [comment]
Magic DNSBeta
You've enabled Magic DNS to get automatic DNS names for devices on your network. Disabling this feature removes all automatic DNS names.

Disable Magic DNS

------------------------
Nameservers
Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.

100.100.100.100
Magic DNS

**Comment by talway** [comment]
chrome Prompt error：

DNS_PROBE_STARTED

DNS_PROBE_FINISHED_NO_INTERNET

**Comment by 0xbkt** [comment]
Same problem here. That should have something to do with routing, I guess. 

```
# resolv.conf
nameserver 127.0.0.53
```

```shell
fuck@pc:~$ resolvectl status wlp7s0 
Link 3 (wlp7s0)
      Current Scopes: DNS         
DefaultRoute setting: yes         
       LLMNR setting: yes         
MulticastDNS setting: no          
  DNSOverTLS setting: no          
      DNSSEC setting: no          
    DNSSEC supported: no          
  Current DNS Server: 192.168.43.1
         DNS Servers: 192.168.43.1
          DNS Domain: ~.          
```

```shell
fuck@pc:~$ ping -w5 192.168.43.1
PING 192.168.43.1 (192.168.43.1) 56(84) bytes of data.

--- 192.168.43.1 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4073ms
```

**Comment by DentonGentry** [comment]
So 192.168.43.1 is the DNS server, and it is on the local LAN?

I suspect this is an instance of https://github.com/tailscale/tailscale/issues/1527, that the exit-node feature as currently designed aims to effectively teleport your node to where the exit node is. The node can no longer access IP addresses on its local LAN.

https://github.com/tailscale/tailscale/issues/1527 also tracks the feature request to allow this to be changed: to have a teleport mode for when one is in coffeeshops and public venues where the local Wi-Fi is not trusted, and also support the current mode where the node teleports to the location of its exit node.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/1527
