### ISSUE TITLE
Add São paulo region

### ISSUE THREAD

**Issue by gerardo-junior** [tailscale/tailscale#1499]
In Latin America the latency is over 150ms, it would be very useful to have a better latency

one more relay point in Brazil would make the difference for ssh connections

**Comment by bradfitz** [comment]
We just started working on that recently actually.

**Comment by gerardo-junior** [comment]
very cool!  thanks!

**Comment by gerardo-junior** [comment]
@bradfitz has the sao paulo region been removed? 
![image](https://user-images.githubusercontent.com/9096410/135951268-591ce56f-e81f-4a4d-86ef-c4822bb9e4c2.png)

**Comment by bradfitz** [comment]
@gerardo-junior, nope. Still there:

```
$ curl https://login.tailscale.com/derpmap/default | jq .
...
    "11": {
      "RegionID": 11,
      "RegionCode": "sao",
      "RegionName": "São Paulo",
      "Nodes": [
        {
          "Name": "11b",
          "RegionID": 11,
          "HostName": "derp11b.tailscale.com",
          "IPv4": "15.228.50.175",
          "IPv6": "2600:1f1e:26e:2f01:fca6:2392:ea86:c768"
        }
      ]
    },
```

The `netcheck` subcommand doesn't wait for all regions. After it's got enough results, it stops after a certain time/count cutoff.

**Comment by gerardo-junior** [comment]
I don't know what's happening @bradfitz , I tried with 4 different ISPs, when pinging I get between 20~30ms

I also tested on several proxies in several countries the only one that disappeared was sao paulo.

1.15.196
  tailscale commit: 173bbaa1a11d49adb370c1c9e02b20e7cf6c598b
  other commit: d1f547c37a4d6347ebd2e90c4f5d2eb25cfc76da
  go version: go1.17.1-ts097d1284f9


is there any setting to force a region?

**Comment by bradfitz** [comment]
We don't track closed bugs so this bug isn't the right place to get support. 

Please open a new bug, forum post, or support ticket with more more information, including at least the full netcheck output, and a "tailscale bugreport" marker.
