### ISSUE TITLE
Log access for Tailscale application.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1501]
The customer asks for pulling out logs of the system and using API or some other means. 

They wanted to manage their logs and use them.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2wr4h)

**Comment by stevelitras** [comment]
I'm the customer mentioned here - we want to be able to get logs of our tailscale activity down to the user level (connections, disconnections, logins, errors, etc.). We have a variety of ways to ingest data, so if it can be via a REST API, that'd be great, but could also be via a variety of other methods.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/415
