### ISSUE TITLE
iOS Unable to reauthenticate

### ISSUE THREAD

**Issue by foxware00** [tailscale/tailscale#1510]
**Describe the bug**
I've received a notification to reauthenticate Tailscale on my iOS device, however it won't allow me to do anything.
I've tried rebooting, uninstalling, but not matter what. Tapping "Reautheticate" is just a no-op and does nothing

**To Reproduce**
1. Open Tailscale
3. Tap "Reauthenticate"
4. Nothing happens

**Expected behavior**
Reauth and be able to use Tailscale

**Screenshots**
![photo](https://user-images.githubusercontent.com/4174528/111289459-1518b580-863d-11eb-97e9-339cd556a35b.jpg)

**Version information:**
 - Device: iPhone X
 - OS: iOS
 - OS version: 14.4
 - Tailscale version: 1.4.5

**Comment by DentonGentry** [comment]
Could you send email to support@tailscale.com, using the email address where you signed up for Tailscale? We can use the email address to look up more state about what is happening.

**Comment by foxware00** [comment]
@DentonGentry Sent and email, thank you

**Comment by apenwarr** [comment]
We had several bugs like this before v1.8. I think the whole batch of them should now be fixed. Please reopen if you find otherwise.
