### ISSUE TITLE
wgengine/filter: support SCTP, let users distinguish TCP vs UDP

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1516]
Tracking bug for SCTP.

And as a dependency probably: let users target specific protocols in their ACL rules, which would include allowing TCP-vs-UDP specific rules.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2wzf5)

**Comment by bradfitz** [comment]
Its packets are at least easy to parse: https://en.wikipedia.org/wiki/SCTP_packet_structure

**Comment by bradfitz** [comment]
This is just about done.

Need to do a server deploy (to permit writing ACLs for it), and cut a new unstable build.

Then some docs.

**Comment by apenwarr** [comment]
Probably makes sense to make the over-the-wire packet filters support distinguishing TCP vs UDP.

However, I've only extremely rarely heard people ask us about the lack of a user-exposed option to choose which protocol to allow. And that has happened more out of curiosity than out of a security concern. Until we hear a compelling use case, I suggest not making the distinction visible to users.

I have no idea if the SCTP port space is considered similar to TCP and UDP though. Maybe a global "allow SCTP" option in the ACL config makes more sense than a per-port config?

**Comment by evelbodevil** [comment]
Kenny, would you have anything to offer regarding the best way to
support SCTP in Tailscale?

Scott Foster
512-590-0186
***@***.***

**Comment by bradfitz** [comment]
@evelbodevil, SCTP now works with Tailscale. You need to do two things, though:

* all peers wishing to send or receive SCTP need to be using a version of Tailscale greater than 1.6.x, so for now use the unstable packages: https://pkgs.tailscale.com/unstable/ (currently the 1.7.x dev series)
* explicitly allow SCTP in your Tailscale ACL at https://login.tailscale.com/admin/acls with a rule like:

```
    {
      "Action": "accept",
      "Users": ["*"],
      "Proto": "sctp",
      "Ports": ["*:*"],
    },
```

(by default, only TCP and UDP are allowed)

**Comment by evelbodevil** [comment]
thank you for the update I will test it today.


Scott Foster
512-590-0186
***@***.***

**Comment by DentonGentry** [comment]
So far as we know, the SCTP support added in 1.8.0 is fine. Please reopen if you find something problematic.

**Comment by evelbodevil** [comment]
@DentonGentry I never got around to testing this.  So this is what the ACL should look like?  

  },
  // Access control lists.
  "acls": [
    // Match absolutely everything. Comment out this section if you want
    // to define specific ACL restrictions.
    { "action": "accept", "users": ["*"], "ports": ["*:*"] },
    {
      "Action": "accept",
      "Users": ["*"],
      "Proto": "sctp",
      "Ports": ["*:*"],
    },
  ]
}

**Comment by DentonGentry** [comment]
There is no proto, just:
{ "action": "accept", "users": ["\*"], "ports": ["\*:1234"] },

**Comment by bradfitz** [comment]
No, you need a proto for sctp. See my comments above: https://github.com/tailscale/tailscale/issues/1516#issuecomment-810457246
