### ISSUE TITLE
Break out gvisor netstack to a separate package

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1518]
The current netstack, for google organizational reasons, ships as part of gvisor. This means that trying to update netstack also pulls in gRPC and a bunch of other gvisor-only dependencies.

This is silly, and causes problems because nothing in this ecosystem is ever stable or compatible with other things.

As a result, I had to commit 84aba349d9a8d4e43585856c8155385f2569d35a to revert d42f8b7f9a29a288058a03ebdf740e11b843bf26. We tried to bump netstack to pick up a bugfix for 32-bit platforms, and that ended up making the etcd client fail to compile because of conflicting gRPC versions. Tailscale 1.6.0 is going to ship with broken 32-bit userspace networking as a result.

We want to make inet.af/netstack, which will be just the netstack code yanked out of the gvisor repo with a script. That should lead to a much smaller (maybe even nil?) go.mod, which will be much nicer for projects that just want to do userspace networking (like us) and not G all the visor.

/cc @namansood, @bradfitz to note the gvisor revert.

**Comment by bradfitz** [comment]
The commit cross-reference didn't work, but: https://github.com/inetaf/netstack

Mostly done.

Need to clean up the sync automation scripts a bit and add to the repo.

**Comment by bradfitz** [comment]
Current shell script hack job is: https://gist.github.com/bradfitz/889d7c3db6d0907f3653a56a88c38415

**Comment by bradfitz** [comment]
Not quite done. The shell script isn't great yet and it's not automated or even included in the repo.

**Comment by DentonGentry** [comment]
Is https://github.com/inetaf/netstack considered enough for this purpose?

**Comment by bradfitz** [comment]
I wanted to keep this open until the repo at least has my hacky update script. But it's really hacky so I kept hoping I'd clean it up a bit.

**Comment by bradfitz** [comment]
Latest iteration of the hacky script: https://gist.github.com/bradfitz/4ccf99a80820b3811683fa4803c64979

But we should really rewrite that to be robust.

Also, we should probably get some automated CI on that, doing it for every gvisor commit and running our tests, to prevent other regressions like https://github.com/google/gvisor/issues/6839

**Comment by DentonGentry** [comment]
gvisor added tests to build on multiple platforms: https://buildkite.com/gvisor/pipeline/builds/10194

**Comment by bradfitz** [comment]
As of Go 1.17 with its lazy module loading, we no longer need netstack in its own module. We can use the upstream gvisor module without breaking our corp build now.

So, closing this.
