### ISSUE TITLE
Selecting an exit node that has a public-facing endpoint IP blocks access to that endpoint IP

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1522]
Steps:
- On a cloud VM with a public IP assigned, install tailscale (v1.6.0 in my case) with --advertise-exit-node
- Select that exit node (in my case, from a Windows PC)
- Try to ping the public IP (not tailscale IP) of the newly selected exit node

Expected:
- The public IP can be reached, presumably via the exit node route

Actual:
- The public IP is unreachable.

I suspect this happens because of the feature where we intentionally block "private" subnets from being routed through the exit node, and any locally-directly-attached subnet counts as private for this purpose. However, the client side is still routing that subnet through the exit node, so it ends up blackholed.

Although the blocking mostly is wise, we should probably still accept packets to the specific /32 owned by the exit node itself.

**Comment by danderson** [comment]
What about non-public IPs? If the exit node is 192.168.1.82 on its LAN, should Tailscale let clients dial into that IP over Tailscale?

We've thought about this for IPv6 as well, in that the exit node might have a public /64, but we probably don't want to let clients access that, since it's conceptually a LAN even though it's a global IP. Thoughts?

I'm mildly worried about this "LAN firewalling" getting more difficult to predict than it already is.

**Comment by danderson** [comment]
Hm. Currently the code tries to handle this case, but only does so if the public IP is defined as a /32 or /128. That still fails in situations like DigitalOcean, where you get a public IP in a /24, and obviously all IPv6 where /64 is the norm. So, sounds like there is precedent for _wanting_ this to work, and it's just fixing to actually work.

I'll continue blocking all RFC1918 IPs for now.

**Comment by danderson** [comment]
Revised behavior: the default route filter does the following operations in sequence, starting with the set of all IPs:
 - Remove all local subnets (obtained by listing local interfaces). This strips out your local v4 /24, v6 /64, and so forth.
 - Add back all host IPs. This adds back single IPs from the ranges we just removed.
 - Remove all "forbidden" subnets (RFC1918, Tailscale, CGNAT). This incidentally removes e.g. RFC1918 host IPs from the allowlist.

At the end of this process, the default route is transformed into "the entire internet minus local LANs, minus well-known private networks", but still includes the host's public IP(s) if any.

**Comment by apenwarr** [comment]
Hmm, yeah, this sounds like it would fix my particular situation and generally not create unexpected behaviour that I can think of.

**Comment by danderson** [comment]
Done.
