### ISSUE TITLE
Magic DNS and other DNS servers via Tailscale

### ISSUE THREAD

**Issue by sphr2k** [tailscale/tailscale#1523]
**Describe the bug**
With Magic DNS enabled, DNS lookups for Tailscale Magic DNS hostnames (<domain>.beta.tailscale.net) **do** work, but lookups using custom DNS servers (100.121.171.9, 100.68.39.54) **don't**. With Magic DNS disabled, DNS lookups using do work. 

On Windows and Linux endpoints, Magic DNS works as expected.

This is my config:

![image](https://user-images.githubusercontent.com/1213706/111464816-947fb500-8721-11eb-845e-d16a5e8d8d7d.png)

**Version information:**
 - Device: Google Pixel 5
 - OS: Android
 - OS version: 11
 - Tailscale version: 1.4.5 (Beta)

**Comment by danderson** [comment]
This is a known issue with MagicDNS at the moment: specifying DNS servers accessible over Tailscale doesn't work in combination with MagicDNS. We're planning to fix this in the next release cycle.

**Comment by leowmjw** [comment]
Happens with OSX Catalina (10.15.6) too. Tailscale 1.4.5. Custom DNS works again with Magic DNS disabled.

**Comment by t3rminalVel0city** [comment]
I believe this also might be affecting me.

I have two nameservers set in the Tailscale Admin UI, which both correspond to internal domain controllers (both on an RFC1918 address space, with a tailscale subnet router in the same space).

If I connect to tailscale on my phone via LTE, when magic dns is enabled, no inernal DNS names will resolve. If I disable magic DNS, they immediately start resolving again, I can toggle magic DNS off and on in the UI and the DNS queries will fail and start working again as I'm doing it.

Happy to assist in any troubleshooting.

**Comment by edaniels** [comment]
If there's any pointers for where in the code this issue is happening, I'd be happy to lend a hand. Hitting this at work now (have a workaround) but would be very helpful to get it working.

**Comment by DentonGentry** [comment]
I think this is resolved in 1.8. I have Magic DNS enabled and am using a Tailscale IP address for my main DNS server as well.

In the next bug scrub if there are no further comments, we'll close this.
