### ISSUE TITLE
Make headless version for Windows Server Core / Nano

### ISSUE THREAD

**Issue by sphr2k** [tailscale/tailscale#1524]
**Is your feature request related to a problem? Please describe.**

Currently, it does not seem possible to run Tailscale on Windows versions that only provide a minimal (Windows Server Core) or no UI (Windows Server Nano). Setup succeeds, but it's not possible to set up the host using the CLI and a pre-auth key. When running `tailscale up -authkey tskey-...`, the CLI just hangs and nothing happens - no error message.

**Describe the solution you'd like**

It should be possible to run Tailscale headless under Windows, just like on Linux. For this to work, it would also be necessary to expose the "run unattended" option via the CLI, which does not seem to be the case so far.

**Comment by bradfitz** [comment]
> Currently, it does not seem possible to run Tailscale on Windows versions that only provide a minimal (Windows Server Core) or no UI (Windows Server Nano).

How do I get one of those environments for development & testing? Is there something I can buy or rent on the cloud?

> For this to work, it would also be necessary to expose the "run unattended" option via the CLI, which does not seem to be the case so far.

That's the default with "tailscale up". The Windows tailscaled + GUI are unique in their desktop-session-scoped sessions.

**Comment by bradfitz** [comment]
https://aws.amazon.com/marketplace/pp/B07R3C9RPW has two reviews, both complaining that it's not actually a core image.

**Comment by sphr2k** [comment]
@bradfitz  I can provide an Azure-hosted instance of Server 2019 Core (fresh/unused) if you want. Let me know if you want to use it and I'll email you the credentials.

**Comment by DentonGentry** [comment]
We've been working on this in https://github.com/tailscale/tailscale/issues/2137
Though it was filed after this one, it has quite a bit of state already, so I'd like to keep it and close this one.
Dup of #2137
