### ISSUE TITLE
cmd/tailscaled: start/stop Windows service on demand using Service Trigger Events

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1530]
Windows services can be configured such that they start on demand.

"Service Trigger Events"
https://docs.microsoft.com/en-us/windows/win32/services/service-trigger-events

They seem new enough:
> ... are not supported until Windows Server 2008 R2 and Windows 7. 

A user was surprised that even with the Tailscale GUI closed, the service process was still running. (without "Run Unattended" checked)

Ideally we could use this too, as long as we can make starting the GUI app (as an unprivileged user) somehow fired such a "Service Trigger Event" to wake up the service.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2x781)

**Comment by DentonGentry** [comment]
I think related (though using a different mechanism): https://github.com/tailscale/corp/pull/6115
This only addresses starting the service, not stopping it.

**Comment by DentonGentry** [comment]
I think the point of this issue was substantially addressed by https://github.com/tailscale/corp/pull/6115
(which most of y'all won't be able to see, sorry)
