### ISSUE TITLE
cmd/tailscale: status --json should include stable ID

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1532]
User notes about `tailscale status --json`:

> The only field that I can't find in the json output, though, is a deviceId that I could pass directly to the REST API.
>
> I see that I can use the REST API to gather the list of all devices, and match up the tailscale IP address or other details to find the deviceId, but it would be nice to avoid the extra work!

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2x7bl)

**Comment by rosszurowski** [comment]
I believe the REST API uses the legacy IDs. We'll want to make sure it supports both before ever exposing StableID to end users.

**Comment by DentonGentry** [comment]
It looks like we did this, somewhere along the way:
```
    "nodekey:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef": {
      "ID": "nabc012CNTRL",
      "PublicKey": "nodekey:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      "HostName": "server1",
```

**Comment by bradfitz** [comment]
Done in e72ed3fcc2fd865b75d4ef52ff3f910f60578751
