### ISSUE TITLE
Installing Tailscale on an AWS AMI results in a shared machine key.

### ISSUE THREAD

**Issue by Haegin** [tailscale/tailscale#1538]
**Describe the bug**
Installing Tailscale as part of the setup for an Amazon Machine Image (AMI) bakes the machine key into the AMI. This causes any instances that are created from the AMI to appear as a single machine in the Tailscale network.

**To Reproduce**
1. Set up an AWS AMI with Tailscale installed
2. Start 2 instances from the AMI
3. Connect both instances to Tailscale
4. Look at the list of machines - only one will appear.
5. Run `ip addr` on both machines and the tailscale address will be the same.

**Expected behavior**
Each machine started from the AMI would appear separately.

**Version information:**
 - Device: VPS
 - OS: Linux (Ubuntu)
 - OS version: Ubuntu 20.04.2 LTS
 - Tailscale version: 1.6.0 (ddc975fcb268a06dc39923ec5db93f1c95b8cfc4)

**Additional context**
My AMI was generated using Packer with a setup script that installed Tailscale using
```
# Tailscale VPN
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo apt-key add -
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list
sudo apt-get update
sudo apt-get -y install tailscale
```
Tailscale was not started during the AMI set up process.

**Comment by bradfitz** [comment]
> Tailscale was not started during the AMI set up process.

You mean `tailscale up` wasn't run. But `apt-get install tailscale` starts it up by default.

Perhaps we could lazily delay generating the machine key until first `up`.

/cc @danderson @crawshaw

**Comment by DentonGentry** [comment]
I believe a workaround for now is to add a cleanup step to remove /var/lib/tailscale/tailscaled.state from the filesystem image.

**Comment by Haegin** [comment]
@DentonGentry ah perfect, thanks.

**Comment by DentonGentry** [comment]
I'm going to close this with the workaround. We do have a task we'd like to get to in order to handle this better, handling nodes which are understood to be ephemeral. However keeping this issue open would just sit, we're tracking that effort elsewhere.
