### ISSUE TITLE
No v1.6 on App Store

### ISSUE THREAD

**Issue by kellytrinh** [tailscale/tailscale#1539]
User in HK here.  Latest version is still v1.45 on App Store.  Is the roll out staggered by region???

**Comment by danderson** [comment]
Apple hasn't approved 1.6 for release yet. Hopefully it'll roll out everywhere in the next few days.

**Comment by DentonGentry** [comment]
The MacOS app is still in review, everywhere. No region has it in the app store yet. Hopefully it will happen this week.

We don't have a way to make all platforms appear at the same time, as even MacOS and iOS reviews complete at their own schedule and not at the same time.

**Comment by kellytrinh** [comment]
Wow you guys are fast.  Noted need a week of lead time; all the webpages refer to 1.6 and given that HK needed some special help to roll out/approve previously I wondered needed a look.

Can close the support ticket then.

**Comment by danderson** [comment]
HK should be fine in future (unless Apple policies change), we don't geo-restrict more than that, so once it's approved and released it should reach you quickly. Thanks for checking in!

**Comment by talway** [comment]
Can I download the installation package directly for Android?

**Comment by DentonGentry** [comment]
On https://github.com/tailscale/tailscale-android there is a "Get it on F-Droid" button which may do what you want.
