### ISSUE TITLE
Node Sharing should be allowed to more than 10 people.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1541]
Customer is using the Tailscale for their employee while working from home. With remote working, they have most people working with their private laptops/machines.  

They are running into the issue because of the Beta version limitation of 10 people allowed for node sharing.

**Comment by apenwarr** [comment]
Drive-by CEO comment: if you need to share a node with more than 10 external people, please email support@ and ask. We can be flexible, but we'd love to hear what you're up to.

**Comment by DentonGentry** [comment]
I'm going to close this: though we may raise the limit later as part of a plan for the next step in node sharing, I don't think we'd agree to just change it right now.
