### ISSUE TITLE
DNS not resolving in MacOS with exit node

### ISSUE THREAD

**Issue by morpig** [tailscale/tailscale#1544]
**Describe the bug**
Running latest Tailscale 1.6.0 on exit nodes + client

Client running macOS Big Sur 11.2.1 (20D74)

After choosing an exit node, browser + OS is unable to resolve any types of domains. No DNS changes made from client side (using dns servers provided by local network dhcp). Magic DNS is also disabled.

Ping to local dns server works also to external dns servers (over the exit node network).

Running dig/nslookup directly does not work, but if I specify the dns servers (given from dhcp), it works.

<img width="575" alt="Screen Shot 2021-03-19 at 05 59 57" src="https://user-images.githubusercontent.com/4915643/111708444-7082b780-8878-11eb-9a14-6ce3dce0b07f.png">

<img width="484" alt="Screen Shot 2021-03-19 at 06 02 39" src="https://user-images.githubusercontent.com/4915643/111708594-ba6b9d80-8878-11eb-8496-90ca74cbc401.png">

<img width="610" alt="Screen Shot 2021-03-19 at 06 05 54" src="https://user-images.githubusercontent.com/4915643/111708852-2fd76e00-8879-11eb-8fed-27a42d30a340.png">

**To Reproduce**
1. Update to v1.6.0
2. Pick exit nodes
3. Try to access any websites

**Comment by DentonGentry** [comment]
172.16.0.5 and 172.16.0.10 look like they might be servers on the local LAN with the Mac, is that correct?

If so this may be https://github.com/tailscale/tailscale/issues/1527. The exit-node feature as designed will "teleport" the Mac to the location of the exit node. It doesn't allow access to the local LAN.

If 8.8.8.8 or 1.1.1.1 or similar would work, you could add those as Nameservers in https://login.tailscale.com/admin/dns. Those would be reachable from the exit node.

**Comment by flamingcow66** [comment]
Same problem here on two separate machines, with 8.8.8.8 and 8.8.4.4 as the locally-configured DNS servers. Setting 8.8.8.8 in the tailscale DNS servers immediately causes all resolution to time out until I disconnect tailscale.

**Comment by morpig** [comment]
> 172.16.0.5 and 172.16.0.10 look like they might be servers on the local LAN with the Mac, is that correct?
> 
> If so this may be #1527. The exit-node feature as designed will "teleport" the Mac to the location of the exit node. It doesn't allow access to the local LAN.
> 
> If 8.8.8.8 or 1.1.1.1 or similar would work, you could add those as Nameservers in https://login.tailscale.com/admin/dns. Those would be reachable from the exit node.

Correct, 172.16.0.0/24 is my local LAN IP.

But the weird thing is, I can still access my servers on those IPs while using exit node. I can still query dns over it, ssh, even accessing http server.

I tried changing manually the DNS servers to 8.8.8.8 in my network settings, but still, it won't resolve.

<img width="915" alt="Screen Shot 2021-03-19 at 08 45 24" src="https://user-images.githubusercontent.com/4915643/111720043-ba2acc80-888f-11eb-95ef-e5021abaa7db.png">

**Comment by sshaman1101** [comment]
Met the same issue today, the whole DNS thing looks dead on macOS when the exit node is used.
I played with DNS settings in the admin console and found out that Linux clients receive new DNS servers immediately and everything works fine, but macOS doesn't. 

In my case:
`scutil --dns` shows the DNS config only for the wifi interface (en0), same as on @morpig's screenshot. 
System Preferences does not allow you to configure the DNS for the VPN interface (on Catalina 10.15.7)

So I had to use the `scutil` itself to set the DNS for tailscale. [The link to how-to](http://hints.macworld.com/article.php?story=20050621051643993). 

Now `scutil --dns` on my machine shows this and everything works perfectly.
<img width="496" alt="Screen Shot 2021-03-19 at 2 57 12 PM" src="https://user-images.githubusercontent.com/5667740/111763066-c411f700-88b2-11eb-847b-5132dd37f505.png">

Hope this might be helpful.

**Comment by morpig** [comment]
> Met the same issue today, the whole DNS thing looks dead on macOS when the exit node is used.
> I played with DNS settings in the admin console and found out that Linux clients receive new DNS servers immediately and everything works fine, but macOS doesn't.
> 
> In my case:
> `scutil --dns` shows the DNS config only for the wifi interface (en0), same as on @morpig's screenshot.
> System Preferences does not allow you to configure the DNS for the VPN interface (on Catalina 10.15.7)
> 
> So I had to use the `scutil` itself to set the DNS for tailscale. [The link to how-to](http://hints.macworld.com/article.php?story=20050621051643993).
> 
> Now `scutil --dns` on my machine shows this and everything works perfectly.
> <img alt="Screen Shot 2021-03-19 at 2 57 12 PM" width="496" src="https://user-images.githubusercontent.com/5667740/111763066-c411f700-88b2-11eb-847b-5132dd37f505.png">
> 
> Hope this might be helpful.

Ah, so the OS is trying to resolve DNS via tailscale's interface, but no resolver is set?

looking at the guide, quite PITA just to set a dns resolver ip 😅

**Comment by sylr** [comment]
I can confirm that when Exit Nodes is used /etc/resolv.conf becomes empty:
```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
```

It comes back to normal once Exit Node is disabled:

```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 10.10.40.11
nameserver 10.10.40.1
```

**Comment by 33b5e5** [comment]
I'm able to reproduce this on Big Sur 11.2.3 with Tailscale 1.6.0. With the exit node disabled:

```bash
$ grep nameserver /etc/resolv.conf
nameserver 10.0.0.8
nameserver 10.0.0.9
$
```

With the exit node enabled:

```bash
$ grep nameserver /etc/resolv.conf
$
```

**Comment by DentonGentry** [comment]
More debugging state on https://github.com/tailscale/tailscale/issues/1647
