### ISSUE TITLE
Do not let users select an exit node if it will break their internet

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1547]
Users should not be able to use an exit node in “privacy vpn” mode if it will break their access to their DNS server.

If they already have an exit node selected and we have no route to their private IP DNS, they should get a system notification that explains that’s why their internet is broken.

cc @danderson

**Comment by danderson** [comment]
This assumes that we know what their DNS server is, which we currently don't. That's the set of work planned for 1.8.

"Read the current DNS config" is the first part of the 1.8 work though, so we can ship a nicer error with that. Later on, I'd like to implement relaying DNS requests to the exit node, for it to resolve per the local DNS config. That fits better to the mental model of what exit nodes are doing.

**Comment by DentonGentry** [comment]
1.12 added support for (optionally) accessing the local LAN, allowing use of DNS servers from the next-hop router.

1.19.x builds in https://pkgs.tailscale.com/unstable/ include functionality to forward DNS queries to the exit node.

**Comment by DentonGentry** [comment]
This issue was filed to cover DNS:
>Users should not be able to use an exit node in “privacy vpn” mode if it will break their access to their DNS server.

This was addressed in Tailscale 1.20: when an exit node is activated, we forward all DNS queries to the exit node to be resolved.
