### ISSUE TITLE
incorrect info on pkgs.tailscale.com

### ISSUE THREAD

**Issue by zhsj** [tailscale/tailscale#157]
It says:

```
Debian Stretch (stable)
Debian Buster (testing)
```

As of 2020-03-07, Strech is oldstable, Buster is stable, Bullseye is testing.

ref: https://www.debian.org/releases/

**Comment by danderson** [comment]
Woops, I'm behind the times :) Thanks for reporting, I'll fix now and add a Bullseye release.

**Comment by danderson** [comment]
Fixed. Thanks again!
