### ISSUE TITLE
cmd/tailscaled: lazily generate machine key, lazily connect to control

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1573]
(pulled out of https://github.com/tailscale/tailscale/issues/1538#issuecomment-801580514 which was closed)

Right now, if a user does `apt-get install tailscale`, the `tailscaled` daemon starts up, immediately generates a new machine key, and immediately starts its long poll to the coordination server ("control").

This causes problems for people e.g. creating AMIs for reuse later, as the machine key gets cloned.

But it also seems wasteful to keep that HTTP request to control open if there's no node key and hasn't been a request to do "tailscale up".

I think we should both lazily generate the machine key and lazily connect to control.

We could then also surface any HTTP connect error to control in the `tailscale up` output.

**Comment by Kirrus-Indiestone** [comment]
I've just had a machine key conflict caused by tailscale generating keys on installation, so reusing an existing node key. Was this fix deployed / is it still in place?
