### ISSUE TITLE
Support auto-updates of DMG image

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#1574]
The DMG MacOS image allows a set of users to run versions in advance of what is released in the app store. We'd like a way to automatically update users running the DMG App. https://sparkle-project.org/ is a framework we are familiar with, though if there is a reason to prefer a different mechanism we can discuss it.

I think we'd want multiple tracks, however that would be handled:
- unstable track, built at any time
- beta track, relatively feature complete images built as we approach a new major release
- stable track, we'd build from the same release point where the AppStore binary is built

We'd also want users to be able to opt-out of automatic updates.

**Comment by DentonGentry** [comment]
From status update this week: we'll need to use Sparkle's 2.0 beta in order to support the SysExt.

**Comment by DentonGentry** [comment]
Current status:
- macsys image implemented Sparkle 2.0 autoupdate support
- pkgs.tailscale.com added an AppCast RSS feed
- put them together, and something still isn't working. A 1.19.42 macsys image doesn't notice that a 1.21.50 macsys image is available.

**Comment by case** [comment]
Fwiw, it looks like Sparkle finally got to an official v2 release: https://github.com/sparkle-project/Sparkle/releases/tag/2.0.0

**Comment by DentonGentry** [comment]
We're using one of the earlier builds now, we should update.

I doubt it will resolve the current issue though, I think this is us holding it wrong.

**Comment by DentonGentry** [comment]
Fixed by:
- https://github.com/tailscale/corp/pull/4991
- https://github.com/tailscale/corp/pull/4560
- https://github.com/tailscale/corp/pull/4505
(which won't be visible because they are in a private repo, but are related to this issue)
