### ISSUE TITLE
Exitnode doc should be updated with the DNS configuration needed in order to work.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1580]
We should update the document with details on users have to configure a nameserver here: https://login.tailscale.com/admin/dns otherwise, DNS queries have nowhere to go. Or possibly an improvement to the exit node functionality would be to use a fallback public DNS server if none are set? The customer got hung up for a while after creating a new Tailscale account without having the nameservers configured.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2y8lt)

**Comment by gps949** [comment]
> We should update the document with details on users have to configure a nameserver here: https://login.tailscale.com/admin/dns otherwise, DNS queries have nowhere to go. Or possibly an improvement to the exit node functionality would be to use a fallback public DNS server if none are set? The customer got hung up for a while after creating a new Tailscale account without having the nameservers configured.
> 
> <img alt="Front logo" width="16" height="16" src="https://camo.githubusercontent.com/e63d7a8fdbca6b03d6395c4af74022fd7299adcf8f9431678eb1b8c6f594ba02/68747470733a2f2f66726f6e746170702e636f6d2f6173736574732f696d672f66617669636f6e732f66617669636f6e2d33327833322e706e67"> [Front conversations](https://app.frontapp.com/open/top_2y8lt)

Maybe a fallback will be better. By current tailscale can't set a DoT or DoH ( I saw there's issues about this point since 2020 but no progress about it). If set the DNS to a public ipv4 or ipv6, sometimes it can't meet the security requirement and the DNS may be polluted.

**Comment by mayakacz** [comment]
Hit the same issue - for others, found my solution here: https://forum.tailscale.com/t/no-dns-when-using-exit-node/477/11 . Would be great to include this in docs.

**Comment by DentonGentry** [comment]
In the 1.10 release, DNS servers can be set using Tailscale 100.x.y.z IP addresses and will work even while the exit node is active.

In the 1.12 release, for fallback DNS servers we recognize like CloudFlare or dns.google, MagicDNS will automatically use DNS-over-HTTPS so the DNS packet is not sent unencrypted over the Internet.

**Comment by DentonGentry** [comment]
1.19.x builds in https://pkgs.tailscale.com/unstable/ include functionality to forward DNS queries to the exit node, which is expected to resolve most issues like this. This functionality will be in the 1.20 release build.

**Comment by DentonGentry** [comment]
I believe 1.20 forwarding DNS queries to the exit node effectively resolved this.
