### ISSUE TITLE
Avoid IP forwarding warning when correct per-interface forwarding is configured

### ISSUE THREAD

**Issue by joneskoo** [tailscale/tailscale#1586]
**Describe the bug**

I'm unable to enable exit node feature when my Linux router enables forwarding by interface, not globally.

**To Reproduce**

```
net.ipv4.ip_forward = 0
net.ipv4.conf.wan0.forwarding = 1
net.ipv4.conf.guest0.forwarding = 1
net.ipv4.conf.lan0.forwarding = 1
net.ipv4.conf.tailscale0.forwarding = 1
```

```
# tailscale up -accept-dns=false -accept-routes=false -advertise-routes=172.24.100.0/24 -netfilter-mode=off
Warning: net.ipv4.ip_forward is disabled. Subnet routes won't work.
Warning: netfilter=off; configure iptables yourself.
```

**Expected behavior**

Exit node can be enabled in review routes.

**Screenshots**

![image](https://user-images.githubusercontent.com/305104/112521111-098f6200-8d94-11eb-8a38-24458639ce46.png)

**Version information:**

Debian 10, Tailscale from Debian package `deb https://pkgs.tailscale.com/stable/debian buster main`

1.6.0
  tailscale commit: ddc975fcb268a06dc39923ec5db93f1c95b8cfc4
  other commit: 995460c32665f1dab78c78512386235d275cf074
  go version: go1.16.2-ts3b83fb3

**Additional context**
https://tailscale-users.slack.com/archives/C019ZEXDFEH/p1616694996013700

**Comment by danderson** [comment]
Hmm, you should be able to enable the exit node anyway. Are you actually unable to turn it on? I thought we just presented a warning that "this probably won't work".

**Comment by joneskoo** [comment]
🤦  You're right. Good catch. Indeed I was missing `-advertise-exit-node=true`  and just confused the forwarding warning from subnets. It does let me enable after all despite the warning. Since this is probably an uncommon configuration, I think you're fine to say that you avoid the warning setting the global forwarding. But it's not required to enable, so it's just cosmetic.

My bad.

**Comment by danderson** [comment]
We should still try to detect that the forwarding config is okay, if we can. It's a bit complicated, so I don't think we're going to prioritize it, but I'll keep the bug open to track it. Thanks for reporting!
