### ISSUE TITLE
systemd-networkd removes tailscale routing table entries

### ISSUE THREAD

**Issue by pfactum** [tailscale/tailscale#1591]
**Describe the bug**

If during the boot the networking/DNS is not available yet at the moment tailscaled starts, the tailscale interface never comes up and stucks in a loop like:

```
Mar 26 12:25:01 rain tailscaled[283]: logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io: Temporary failure in name resolution (in 1ms)
Mar 26 12:25:01 rain tailscaled[283]: logtail: upload: log upload of 307 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/…": dial tcp: lookup log.tailscale.io: Temporary failure in name resolution
Mar 26 12:25:01 rain tailscaled[283]: logtail: backoff: 39 msec
…
Mar 26 12:26:14 rain tailscaled[404]: trying bootstrapDNS("derp3.tailscale.com", "68.183.179.66") for "login.tailscale.com" ...
Mar 26 12:26:14 rain tailscaled[404]: bootstrapDNS("derp3.tailscale.com", "68.183.179.66") for "login.tailscale.com" error: Get "https://derp3.tailscale.com/bootstrap-dns?q=login.tailscale.com": dial tcp 68.183.179.66:443: connect: network is unreachable
…
Mar 26 12:26:14 rain tailscaled[404]: control: authRoutine: backoff: 10588 msec
Mar 26 12:26:18 rain tailscaled[404]: logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: connect: network is unreachable (in 3ms)
Mar 26 12:26:18 rain tailscaled[404]: logtail: upload: log upload of 422 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/…": dial tcp 34.210.105.16:443: connect: network is unreachable
Mar 26 12:26:18 rain tailscaled[404]: logtail: backoff: 12570 msec
Mar 26 12:26:24 rain tailscaled[404]: control: authRoutine: state:authenticating; wantLoggedIn=true
Mar 26 12:26:24 rain tailscaled[404]: control: direct.TryLogin(token=false, flags=0)
Mar 26 12:26:24 rain tailscaled[404]: control: doLogin(regen=false, hasUrl=false)
```

even if the networking is up and running a little bit later, and required hosts are perfectly available through telnet.

Restarting tailscaled fixes the issue.

**To Reproduce**
1. install tailscaled on Arch Linux
2. in my case, local DNS resolver is used (_systemd-resolved+dnscrypt_)

**Expected behavior**
tailscaled should restore connectivity once networking is up and running.

**Screenshots**
N/A

**Version information:**
 - Device: various machines
 - OS: Arch Linux
 - OS version: latest
 - Tailscale version: v1.6.0

**Additional context**
I'm not using MagicDNS/nameservers/anything else available in the webadmin.

It seems I've managed to work around the issue by overriding unit dependencies:

```ini
Wants=network-online.target
After=network.target network-online.target
```
so that the daemon starts *after* networking/DNS is available.

I'm not sure this is a proper solution though, so please help.

Thanks.

**Comment by danderson** [comment]
Unfortunately network-online.target is a misleading target in systemd, in that "is the network up enough" is an undecidable problem in general. It probably helps a little bit by reducing the window for a race to occur, but tailscaled should really be robust to changing network conditions - including unavailable network at startup.

**Comment by hspak** [comment]
I want to share that I've never run into this during boot, but I run into this consistently now on system resume.

I don't think I ran into this problem pre 1.6.0, but I never paid close enough attention to know for certain.

My system config is similar to the OP (Arch, 1.6.0), also using the following network stack:
- systemd-networkd
- systemd-resolved
- iwd

**Comment by pfactum** [comment]
Yes, a similar thing happens after suspend/resume cycle for me as well. The interface still has IP-addresses assigned, but all I see is `Destination Net Unreachable` while trying to ping hosts via it. Once daemon is restarted, it works again.

**Comment by amxj9** [comment]
As described in https://github.com/tailscale/tailscale/issues/1134#issuecomment-848696019, the "network is unreachable" error stems from tailscale's ip policy routing rules being removed on suspend/resume.

I believe this issue is caused by systemd-networkd (v247) removing any "foreign" policy routing rules (i.e. not set by itself) when it (re)configures the network.  I think rule 5250 remains because there is no support for the "unreachable" destination in systemd-networkd v247. 

The issue was discussed upstream here: https://github.com/systemd/systemd/issues/19106, resulting in the latest release of systemd-networkd (v248) able to be configured to ignore foreign ruies (```ManageForeignRoutingPolicyRules=false```) which could solve this, although I haven't installed and tried it yet.

Obviously this will still be an issue for older systems, so one workaround could be to set the policy rules with "proto kernel" as I believe systemd-networkd will ignore rules flagged as installed by the kernel.

**Comment by mil-ad** [comment]
I'm running systemd-networkd v248 and setting `ManageForeignRoutingPolicyRules=false` did not make a difference for me. 

when waking up from sleep I do see error below in `journalctl`. After a while the overall status goes back to healthy but I still need to manually restart tailscale service before I can connect to any of my machines.

```
Jun 18 18:48:26 milad-ryzen tailscaled[88208]: health("overall"): error: not in map poll
Jun 18 18:48:29 milad-ryzen systemd-resolved[87976]: Clock change detected. Flushing caches.
```

**Comment by alteriks** [comment]
@mil-ad Please try updating systemd to version 249 ManageForeignRoutingPolicyRules is new feature and it's not available in 248 release - https://github.com/systemd/systemd/commit/d94dfe7053d49fa62c4bfc07b7f3fc2227c10aff

**Comment by mil-ad** [comment]
@alteriks thanks! Will do as soon as it hits arch repos

**Comment by hhtpcd** [comment]
I've been following this and have had the same problem, restarting `tailscaled.service` after suspend has become tiresome!

Arch Linux has systemd 249 in core now so I thought I would give it a go.

```
$ pacman -Q systemd
systemd 249-3
```

I have added the following configuration in `/etc/systemd/networkd.conf`

```
[Network]
ManageForeignRoutingPolicyRules=false
```

After suspend I've got all the rule sets I had before suspend and tailscale routing works without issue, where it did not before.

```
$ ip rule list
0:	from all lookup local
5210:	from all fwmark 0x80000 lookup main
5230:	from all fwmark 0x80000 lookup default
5250:	from all fwmark 0x80000 unreachable
5270:	from all lookup 52
32766:	from all lookup main
32767:	from all lookup default
```

**Comment by mil-ad** [comment]
I'm on the same systemd version as @hhtpcd and tried doing the same thing but waking up from suspend  still removes tailscale rules. 😞

**Comment by bradfitz** [comment]
@mil-ad, which distro+version are you using?

I tried to replicate this with Debian Bullseye (which has `systemd 247 (247.3-5)`) but couldn't get it to delete the rules on suspend.

**Comment by bradfitz** [comment]
> I tried to replicate this with Debian Bullseye (which has systemd 247 (247.3-5)) but couldn't get it to delete the rules on suspend.

Oh, I didn't have networkd even running. Will try to replicate again after doing https://wiki.debian.org/SystemdNetworkd

**Comment by mil-ad** [comment]
> @mil-ad, which distro+version are you using?

Arch (Kernel 5.10.50-1-lts) +  systemd (with systemd-resolvconf) 249-3

**Comment by bradfitz** [comment]
Wow, I just installed Arch... what a blast from the past. I had expected a more modern installer.

Anyway, it exhausted all my patience when it rebooted post-install and lost its network.

@Xe, you know Arch, right? Maybe you can reproduce.

If there's repro instructions on Debian or Ubuntu or Fedora or some distro that has an installer and gives me networking post-reboot then I can dig into this more. I was running it in a VM with stock emulated hardware. Pretty impressive it failed to find the network driver.

**Comment by Xe** [comment]
I'll try and reproduce this tomorrow morning

**Comment by bradfitz** [comment]
I can repro it in an Arch VM under Proxmox.

I used the "basic" qcow2 image from https://mirror.pkgbuild.com/images/v20210619.26314/ (user: arch, password: arch, passwordless sudo) and then rsync'ed over (after `pacman -S rsync`) a `tailscaled` binary.

Then I just ran `tailscaled` in the foreground and ran `ip rule` in another window:

```
[root@archlinux arch]# ip rule
0:	from all lookup local
5210:	from all fwmark 0x80000 lookup main
5230:	from all fwmark 0x80000 lookup default
5250:	from all fwmark 0x80000 unreachable
5270:	from all lookup 52
32766:	from all lookup main
32767:	from all lookup default
```

Then:

```
# systemctl suspend
```

Then in the proxmox QEMU monitor:

```
# system_wakeup
```

After which my ssh connections comes back alive and tailscaled (still "down", as I never ran `tailscale up`) emits:

```
monitor: RTM_DELROUTE: src=10.0.107.32/0, dst=10.0.0.1/32, gw=, outif=2, table=254
monitor: RTM_DELROUTE: src=10.0.107.32/0, dst=, gw=10.0.0.1, outif=2, table=254
monitor: RTM_DELROUTE: src=10.0.107.32/0, dst=10.0.0.0/16, gw=, outif=2, table=254
monitor: RTM_DELROUTE: src=10.0.107.32/0, dst=10.0.255.255/32, gw=, outif=2, table=255
monitor: RTM_DELROUTE: src=10.0.107.32/0, dst=10.0.0.0/32, gw=, outif=2, table=255
[RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5210 Table:254 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5270 Table:52 Mark:0 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5250 Table:0 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5230 Table:253 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
control: setPaused(true)
control: mapRoutine: context done.
control: mapRoutine: awaiting unpause
LinkChange: all links down; pausing: interfaces.State{defaultRoute= ifs={} v4=false v6=false}
magicsock: SetNetworkUp(false)
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=eth0 ifs={eth0:[10.0.107.32/16]} v4=true v6=false}
magicsock: SetNetworkUp(true)
control: setPaused(false)
control: mapRoutine: unpaused
control: mapRoutine: state:new
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=eth0 ifs={eth0:[10.0.107.32/16 2602:d1:b4cf:cxxxxx0:xxx:xxxx:c577/64]} v4=true v6=true}
```

**Comment by bradfitz** [comment]
Thanks, all. This is now fixed. It'll be in the next unstable build we roll (so 1.11.126+), or 1.12.0 soon enough.

**Comment by mil-ad** [comment]
I'm afraid this has started happening for me again 😢

**Comment by bradfitz** [comment]
@mil-ad, we don't track closed bugs so please file a new one, with details.
