### ISSUE TITLE
wgengine: TestWatchdog fails on Big Sur systems with a content filter Network Extension installed

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#1598]
On Big Sur systems with a content filter Network Extension installed (not necessarily even active), the close syscall blocks for about a second. We don't understand why.

This causes TestWatchdog to fail, because it expects to be able to close a magicConn in 150ms.

**Comment by josharian** [comment]
Workaround submitted. Leaving this issue open for a deeper fix.

**Comment by DentonGentry** [comment]
macOS 12.4 and 12.5 substantially fixed interactions between Network Extensions.
