### ISSUE TITLE
Connection failure following Windows 10 update - tailscaled not running

### ISSUE THREAD

**Issue by vsajip** [tailscale/tailscale#1600]
**Describe the bug**

Following a Windows 10 update, Tailscale no longer works - the machine doesn't connect to anything. It had been running 1.4.4 - then I uninstalled it and installed 1.6.0. This version doesn't work either.

**To Reproduce**
Not sure you can reproduce it, other than by installing 1.6.0 on the OS (version below). After installing 1.6.0 (a process which appears to complete normally), right-clicking on the Tailscale icon in the system tray shows "Please restart the Tailscale Windows Service." When looking at services, the Tailscale service shows up as "Running" and "Automatic". After restarting the service, the system tray menu remains unchanged - it still asks you to restart the service. The tooltip for the Tailscale icon says: "Tailscale: Windows service not running." If you try and tailscale ping a host, it fails with:

C:\Users\Me> tailscale ping t-rpi2
local tailscaled stopped

**Expected behavior**
The affected computer should be able to connect to other machines through Tailscale.

**Version information:**
Device: Lenovo IdeaPad S340 laptop
Edition	Windows 10 Home
Version	20H2
Installed on	‎24/‎03/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

Tailscale version:
C:\Users\Me> tailscale --version
1.6.0
  tailscale commit: ddc975fcb268a06dc39923ec5db93f1c95b8cfc4
  other commit: 995460c32665f1dab78c78512386235d275cf074
  go version: go1.16.2-ts3b83fb3

**Additional info**
Tailscale has worked fine on this machine before the Windows upgrade - for a period of months.

c:\Users\Me\AppData\Local\Tailscale has two files, tailscale-ipn.log1.txt and tailscale-ipn.log2.txt, both zero bytes in length.

**Comment by bradfitz** [comment]
What's your Tailscale IP? Look it up at https://login.tailscale.com/admin/machines if you can't get to it from Windows.

**Comment by vsajip** [comment]
It's 100.66.118.55. Just to see what happened, I started a Command Prompt as Administrator and ran tailscaled from the command line in the Program Files subdirectory where Tailscale is installed. It seemed to run (in the sense that it printed some output, with no obvious errors, and then appeared to be waiting). However, the system tray menu still said the service wasn't running. Not sure if that info is of any use, but just in case ...

**Comment by bradfitz** [comment]
I don't see any logs from you running 1.6.0.

Can you paste some here?

Or attach some from C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs ?

**Comment by vsajip** [comment]
Here you go:

[tailscale-service-20210330T082459-1617089099.txt](https://github.com/tailscale/tailscale/files/6232020/tailscale-service-20210330T082459-1617089099.txt)
[tailscale-service-20210329T000006-1616972406.txt](https://github.com/tailscale/tailscale/files/6232021/tailscale-service-20210329T000006-1616972406.txt)
[tailscale-service-20210328T000019-1616889619.txt](https://github.com/tailscale/tailscale/files/6232023/tailscale-service-20210328T000019-1616889619.txt)
[tailscale-service-20210327T132825-1616851705.txt](https://github.com/tailscale/tailscale/files/6232046/tailscale-service-20210327T132825-1616851705.txt)
[tailscale-service-20210327T133002-1616851802.txt](https://github.com/tailscale/tailscale/files/6232045/tailscale-service-20210327T133002-1616851802.txt)

**Comment by washchuk** [comment]
Don't know if this is related, but I'm only having this issue on a machine with Win 10 21H1 update. All other machines are on 20H2 and working just fine.

2021-05-23T16:42:22.512-07:00: 2021/05/23 16:42:22 tailscaled: getting engine... (try 15)
2021-05-23T16:42:22.517-07:00: 2021/05/23 16:42:22 [Wintun] IsPoolMember: Reading pool devpkey failed, falling back: Element not found. (Code 0x00000490)
2021-05-23T16:42:22.517-07:00: 2021/05/23 16:42:22 [Wintun] WintunOpenAdapter: Adapter 2 named Tailscale is not a member of Tailscale pool
2021-05-23T16:42:22.517-07:00: 2021/05/23 16:42:22 [Wintun] CreateAdapter: Creating adapter
2021-05-23T16:42:22.517-07:00: 2021/05/23 16:42:22 [Wintun] CreateAdapter: Requested GUID {37217669-42DA-4657-A55B-0D995D328250} has leftover residue
2021-05-23T16:42:22.587-07:00: 2021/05/23 16:42:22 [Wintun] SelectDriver: Using existing driver 0.10
2021-05-23T16:42:22.792-07:00: 2021/05/23 16:42:22 [Wintun] CreateAdapter: Failed to setup adapter (code: 0x0, status: 0xc0000035): The operation completed successfully. (Code 0x00000000)
2021-05-23T16:42:22.968-07:00: 2021/05/23 16:42:22 tailscaled: engine fetch error (try 15) in 403ms (total 403ms, sysUptime 9m31s): TUN: Error creating interface: Cannot create a file when that file already exists.

**Comment by washchuk** [comment]
Following the advice from this thread (https://github.com/tailscale/tailscale/issues/1128), I found that uninstalling Tailscale, deleting the *two* wintun drivers I had loaded in Device Manager, and then reinstalling Tailscale solved my issue.

**Comment by vsajip** [comment]
I uninstalled Tailscale, but then couldn't see any wintun drivers in Device Manager. There was no wintun.dll I could find. I then installed Tailscale 1.8.5, with the same problem as before :disappointed: While the failing machine is running 20H2, I have another 20H1 machine which doesn't exhibit the problem.

**Comment by vsajip** [comment]
Still failing with 1.8.7:

---------------------------
Tailscale Error
---------------------------
Tailscale service stopped.

Version 1.8.7 (te1571ed7e-g2f595b1b6)

LogID: 4bd25517b84467ac7d4d11a6467efdf492bbf63564a168e77a8f76b50c9850af

**Comment by vsajip** [comment]
[tailscale-service-20210610T000014-1623279614.txt](https://github.com/tailscale/tailscale/files/6631902/tailscale-service-20210610T000014-1623279614.txt)
[tailscale-service-20210610T144533-1623332733.txt](https://github.com/tailscale/tailscale/files/6631903/tailscale-service-20210610T144533-1623332733.txt)
[tailscale-service-20210610T144634-1623332794.txt](https://github.com/tailscale/tailscale/files/6631905/tailscale-service-20210610T144634-1623332794.txt)

**Comment by JohnDDuncanIII** [comment]
> but then couldn't see any wintun drivers in Device Manager.

@vsajip wintun only displayed in my Device Manager on my Windows 10 21H1 machine after I clicked `View => Show hidden devices`.

> There was no wintun.dll I could find. 

I believe this is located in `"C:\Program Files (x86)\Tailscale IPN\wintun.dll"`. I could be wrong, but my understanding is that this service is responsible for installing the wintun driver (accessible from the Device Manager) if it does not already exist. I did not need to manually modify this file.

---

I ran into the same `TUN: Error creating interface: Cannot create a file when that file already exists.` error after renaming my machine from its autogenerated name in the https://login.tailscale.com/admin/machines web interface.

I was able to get my Tailscale working again after I successfully uninstalled the wintun driver in Device Manager.

See https://github.com/tailscale/tailscale/issues/1600#issuecomment-846646386, https://github.com/tailscale/tailscale/issues/1128#issuecomment-759868046, and https://github.com/tailscale/tailscale/issues/1128#issuecomment-863718133.

**Comment by DentonGentry** [comment]
I suspect this was an early report of https://tailscale.com/blog/windows-updates/ which we didn't correctly diagnose at the time.

Tailscale versions 1.14.4 and later move the storage of their state to `C:\ProgramData\Tailscale` where it will not be affected by Windows upgrades.

**Comment by vsajip** [comment]
I'll check when I'm at that location with the most recent Tailscale version and see what happens.

**Comment by vsajip** [comment]
Tried again by uninstalling Tailscale and installing 1.18.2. The problem is still there, I'm afraid. I tried restarting the Tailscale service which seems to restart, but the menu still says "Please restart the Windows Tailscale service". Not sure where the logs go now, since in the old location (mentioned above) there are no logs from today.

**Comment by DentonGentry** [comment]
https://tailscale.com/blog/windows-updates/#:~:text=and%20re%2Dauthenticate.-,See%20instructions,-for%20several%20options is likely to help recover.
