### ISSUE TITLE
The exit node uses another exit node as the exit node

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#1604]
After the client uses exit node 1, let exit node 1 use exit node 2, and let node 2 be the final exit node. It needs to transit through exit node 1. Exit node 1 is a domestic node, and exit node 2 is a foreign node. The main purpose is to improve the speed of exit node. It is slow to directly use exit node 2. Exit node 1 is a domestic dedicated high-speed server. Can it be realized Now, thank you

**Comment by bradfitz** [comment]
We're not trying to build Tor.

**Comment by talway** [comment]
No, it's just a way to increase speed, a way to forward traffic internally;

**Comment by bradfitz** [comment]
Sorry, but I don't see us prioritizing this anytime soon enough to warrant keeping a tracking bug open for it.
