### ISSUE TITLE
Android Tailscale Client disconnects when screen rotates.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1608]
From Customer Reporting : 

For some reason when my Android phone screen rotates the VPN goes from “Active” to “Stopped”.

Android: v11
Phone: Samsung S20+
Provider: T-Mobile

It happens every single time. I am unsure how to stop this from happening. When I am looking at a video from my Plex server, the video switches the screen orientation and stops the vpn, preventing playback.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2yrgx)

**Comment by eliasnaur** [comment]
This is the same phone model (S20+) and Android version (11) as the other report I've seen. @bradfitz would it be possible to give me device logs from the users experiencing this problem?

**Comment by bradfitz** [comment]
I see nothing interesting in the logs, other than some SetPrefs calls.

I'd guess it's not managing the Android Activity lifecycle correctly? Activities start & end all the time on Android, and shouldn't result in any mutating action. Only if there's an explicit action like a button push.

**Comment by darshinimashar** [comment]
[log1.log.zip](https://github.com/tailscale/tailscale/files/6229500/log1.log.zip)

Logs from customer: https://app.frontapp.com/open/cnv_eg5c0sx

**Comment by bradfitz** [comment]
Logs from customer: https://app.frontapp.com/open/cnv_eg5c0sx

**Comment by ElGordito** [comment]
Just to keep you all in the loop...  My phone accepted the latest security patch yesterday and not the screen rotation does not turn off Tailscale.  I will be watching closely to see if the problem comes back. :-)

**Comment by eliasnaur** [comment]
Thanks for letting us know, @ElGordito. @darshinimashar can you please relay the workaround (upgrading to latest security patch) to the other S20+ customer having the same problem?

**Comment by DentonGentry** [comment]
I followed up with the other user who reported the issue.
