### ISSUE TITLE
Test flake: Bursts of lost packets wgengine/magicsock.TestTwoDevicePing

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#161]
As we grind down the issues revealed by the new magicsock test, a new failure mode has bubbled to the top: the test reports bursts of 10-20 packets missing during ping tests.

The root cause (confirmed by DERP_DEBUG_LOGS=1 on the failing test run) is a race in the establishment of DERP connections in the test harness: we have no way to wait for the two test devices to handshake with their home DERP server before we begin DERP testing. If we start transmitting pings before the home connections are established, the DERP server (correctly) drops the relayed packets, since it has no viable forwarding target.

The code itself is working as intended, there is a small startup time during which we may be unable to route packets. It does not affect normal operation of Tailscale, but the tests obviously trigger this reliably.

For testing purposes, we either need a helper that can block on a magicsock Conn until home DERP connections are up, or we must relax the test to allow for initial packetloss until there is reliable transmission, and then switch to its current strict "no loss" behavior.

@bradfitz thoughts on which is preferable? Altering the test feels better to me, as it'll be accurately testing the real-world behavior of magicsock, rather than add a synchronization crutch that only tests use... OTOH I see the value in being able to eliminate known, by-design startup races from tests so that our synthetic cases can more precisely test specific behaviors.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687244221453) by [Unito](https://www.unito.io/learn-more)

**Comment by crawshaw** [comment]
This could happen in real life communication, right? We are racing the connection of home DERP and away DERP.

Should the DERP server, if a packet is bound for an unknown key, hold on to it for a second or two to give the other side a chance to connect?

**Comment by danderson** [comment]
It definitely happens in real life communication, but we just rely on retries to fix things. If we can get away with that, I would strongly prefer to not add buffering along the packet path.

**Comment by apenwarr** [comment]
This reproduces the flake for me on macOS and Linux, but it takes quite a lot of iterations (20+ iterations, times count=10), which makes it a pain to test.

i=0; while go test -failfast -cpu 1,2,4,8 -count=10 ./wgengine/magicsock/  ; do i=$((i+1)); echo "done $i"; done
