### ISSUE TITLE
Support custom records in MagicDNS

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1610]
Occasionally it would be useful to add custom records to MagicDNS, e.g. to provide short names for subnet-routed things we cannot auto-discover. This issue is to track adding that, probably as a zonefile snippet in the control server to start out.

**Comment by DentonGentry** [comment]
Very similar to https://github.com/tailscale/tailscale/issues/1543 which has some discussion and linked bugs.

Dup https://github.com/tailscale/tailscale/issues/1543

**Comment by bradfitz** [comment]
0debb99f0852e8fa53ab6c725966f8dd99b3fbc9 added client support for a new ExtraRecords field. It's not yet supported server-side.

(I also commented on #1543)
