### ISSUE TITLE
Add cloudflare support as an identity provider.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1614]
A user requested that we support Cloudflare as an identity provider.

OPen the FR to track in case we consider it in future.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2yya9)

**Comment by DentonGentry** [comment]
It doesn't appear that Cloudflare offers its own OIDC endpoint to serve as an identity provider, it expects to talk to backend providers like Okta or Google or Microsoft Azure. I don't think we can directly support Cloudflare, we can support the backends a particular customer is using with CloudFlare.
