### ISSUE TITLE
Home DERP server glitches

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#162]
Plotted a new DERP graph, of home connections over time by DERP location. It reveals that 1 node appears to be glitching occasionally between SF and NYC:

![derp](https://user-images.githubusercontent.com/1918/76153716-a0538880-6084-11ea-8950-d20e16d03325.png)

The glitch doesn't last very long, but there's fairly clearly a decrease by 1 in SF, matched by an increase of 1 in NYC, and then the reverse a short time later.

This is likely contributing to additional netmap updates, and probably DERP packetloss stats during the window where the home connection has migrated but other nodes haven't updated yet.

Hypotheses for cause:
 1. SFO sometimes fails to respond, causing node to flip to next best DERP?
 2. Node is roughly equidistant to SFO and NYC, occasional latency fluctuations cause a flip?
 3. Incorrect home DERP selection logic? (feels unlikely, or we'd see a lot more glitching)

If 1 or 2 is true, tracking a window of probes and having some hysteresis for switching home DERPs may be indicated.

**Comment by bradfitz** [comment]
It's almost certainly 1 and 2. There are TODOs in the code iirc. It keeps no history and the stunner retry scheduling needs a bit of love. I was going to do that as part of integrating netcheck and stunner together more and sharing magicsock's udp socket.
