### ISSUE TITLE
MacOS: GUI enters wrong state if using Settings-> Network to "Connect/Disconnect"

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#1624]
**Describe the bug**
MacOS: Tailscale GUI enters wrong state if using Settings-> Network to "Connect/Disconnect". 

Tailscale v1.6.0
MacOS Big Sur 11.2.3
M1 Apple Air

**To Reproduce**
1) Connect to Tailscale using MacOS Tailscale icon drop down menu.
2) Go to System Settings -> Networks -> Tailscale 
3) Click on Tailscale disconnect.
4) Click on Tailscale connect

Both 3) and 4) causes Tailscale MacOS menu icon and drop down menu to enter disjointed state. 

After 4) The service is connected but the Tailscale menu shows "connecting" spinning icon and drop down menu shows non-connected status.

**Comment by apenwarr** [comment]
This should be fixed in v1.8.0.
