### ISSUE TITLE
Tailscale 1.6.0 installation on windows platform failed to start until restart.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1627]
Windows client with version20H2 is asking for a service restart for the Tailscale. 

![image](https://user-images.githubusercontent.com/75628398/113182599-14794500-9221-11eb-84d5-15b7ecb3368f.png)

Even if we restart the service from services.msc, it gives an error. Attached here.

![image](https://user-images.githubusercontent.com/75628398/113182639-20fd9d80-9221-11eb-93cc-5d2b928cdca1.png)

It requires restarting the machine.

**Version information:**
 - Device: Laptop
 - OS: Windows
 - OS version: Windows 10 pro 20H2
 - Tailscale version: 1.6.0

**Comment by ethanhs** [comment]
This occured to me when I had another VPN running, might want to check that.

**Comment by darshinimashar** [comment]
I do not have any other VPN running on laptop.

**Comment by darshinimashar** [comment]
workaround:
Restart Tailscale services from the services window.
From Tailscale Tray Icon > click on Admin Console > login with your Id . after that login option in Tray icon will show up where you log in again and all will start working.

**Comment by DentonGentry** [comment]
An updated Wintun was included in Tailscale 1.8, which resolved issues like this on recent Windows 10 updates.

Barring further comments, we'll expect to close this during the next bug scrub.
