### ISSUE TITLE
Weird DERP connection spikes

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#163]
Occasionally, some DERP servers report sharp increase in the number of connections, and then drops back to baseline. Example of the DERP SF server:

![derp](https://user-images.githubusercontent.com/1918/76154051-b106fd00-608a-11ea-99d4-942ba1b9f622.png)

Looks like either some kind of monitoring error, or maybe some kind of DERP client bug where everyone reconnects en masse?

**Comment by bradfitz** [comment]
This was fixed by 3df1b97ea8225829110553a73d2581ae617a35d8 and e838b3fb596a49dd3611c5a4fa385736b452b4b3
