### ISSUE TITLE
LXC detection no longer working

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#1633]
**Describe the bug**
inContainer expects LXC to have the string "/lxc/" in /proc/1/cgroup:
```
func inContainer() (ret bool) {
        lineread.File("/proc/1/cgroup", func(line []byte) error {
                if mem.Contains(mem.B(line), mem.S("/docker/")) ||
                        mem.Contains(mem.B(line), mem.S("/lxc/")) {
```

However somewhere along the way this stopped working, neither privileged nor unprivileged LXCs have that string now:
```
root@zoneminder ~# cat /proc/1/cgroup
12:freezer:/
11:rdma:/
10:cpuset:/
9:pids:/
8:blkio:/
7:devices:/
6:perf_event:/
5:net_cls,net_prio:/
4:memory:/
3:hugetlb:/
2:cpu,cpuacct:/
1:name=systemd:/init.scope
0::/init.scope
```

**To Reproduce**
Code examination.

**Expected behavior**
Detect LXC containers.

**Version information:**
 - Device: [e.g. iPhone X, laptop]: 
 - OS: Linux
 - OS version: proxmox 6.3
 - Tailscale version: 1.6

**Comment by diegomontoya** [comment]
@DentonGentry for linux lxc I can confirm this works `cat /proc/1/environ`.  should get `container=lxc` string.

**Comment by DentonGentry** [comment]
Excellent!

Could I ask if /proc/mounts in your LXC contains fuse.lxcfs? Right now, that is what https://github.com/tailscale/tailscale/pull/1643 proposes to do.

```
lxcfs /proc/cpuinfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/diskstats fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/loadavg fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/meminfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/stat fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/swaps fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/uptime fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /sys/devices/system/cpu/online fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
```

**Comment by diegomontoya** [comment]
On latest snap lxd version 4.12. here are my fuse related proc mounts

`bash-5.1# cat /proc/mounts | grep fuse
udev /dev/fuse devtmpfs rw,nosuid,noexec,relatime,size=131985632k,nr_inodes=3299640
8,mode=755,inode64 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
lxcfs /proc/cpuinfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_
other 0 0
lxcfs /proc/diskstats fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allo
w_other 0 0
lxcfs /proc/loadavg fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_
other 0 0
lxcfs /proc/meminfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_
other 0 0
lxcfs /proc/stat fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_oth
er 0 0
lxcfs /proc/swaps fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_ot
her 0 0
lxcfs /proc/uptime fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_o
ther 0 0
lxcfs /sys/devices/system/cpu/online fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,
group_id=0,allow_other 0 0`

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/1643
