### ISSUE TITLE
MacOS: Failed to recover after WIFI disconnect/reconnect and triggers packet sent stats explosion

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#1645]
**Describe the bug**
Tailscale cannot recover connection from wifi disconnect/reconnect event. 

**To Reproduce**
1) Connect to wifi and tailscale. Verify tailscale works.
2) Toggle wifi off. 
3) Toggle wifi on.
4) Unable to connect and Tailscale is in connected state. 
5) Tailscale SENT stats goes haywire. 

At this state, must diconnect tailscale and reconnect for connection to work.

**Expected behavior**
Recover connection after wifi reconnect. Stats should not go haywire.

**Screenshots**
Check the "sent" stats from the 3 screen captures only  ~10 seconds apart during the failed to recover from wifi toggle event. Sent stats goes zoom zoom!

<img width="328" alt="Screen Shot 2021-04-02 at 8 14 08 PM" src="https://user-images.githubusercontent.com/417764/113414663-1d6c4100-93f0-11eb-8dd4-67d8b9dd1698.png">
<img width="330" alt="Screen Shot 2021-04-02 at 8 14 22 PM" src="https://user-images.githubusercontent.com/417764/113414666-20673180-93f0-11eb-82a6-0f593a4f9d82.png">
<img width="333" alt="Screen Shot 2021-04-02 at 8 14 33 PM" src="https://user-images.githubusercontent.com/417764/113414670-20ffc800-93f0-11eb-85cf-9a04ef0f2dec.png">

**Version information:**
M1 Macbook Air
OS X: 11.2.3
Tailscale: 1.6.0

**Comment by bradfitz** [comment]
@danderson, perhaps this is a repro for #1526 ?

**Comment by DentonGentry** [comment]
I suspect this is either https://github.com/tailscale/tailscale/issues/2595 or https://github.com/tailscale/tailscale/issues/1526, both of which now have fixes as of 1.16.0.

Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
Closing during bug scrub.
