### ISSUE TITLE
Tailscale app is returning unknown state and toggling switch from active to stop does not work.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1646]
The user is reporting that the app is in a non-working state but claims to be active, and toggling the switch doesn't fix it.

It should detect that the other VPN app is active and report that it's no longer running as a result, and presumably toggling the switch should shut down the other VPN app to give Tailscale control again.

**Expected behaviour:**

The IOS behaviour we can't control, but we can make it show an accurate view of what's going on.

**Version information:**
 - Device: IOS
 - Tailscale version: 1.6.0

**Comment by DentonGentry** [comment]
This sounds like the state machine between the front end and back end, which is something we've substantially fixed in 1.8.x (though more state machine fixes are going in to 1.8.4 still).

**Comment by apenwarr** [comment]
iOS state machine was greatly fixed in v1.8.x. Probably fine now.

**Comment by DrSpaldo** [comment]
I am getting the same issue on my wife's phone but not mine. A few hours after installing tailscale on her iPhone, the whole phone either wouldn't connect to anything or was super slow. I had to install the tailscale app to fix it. 

Tailscale version: 1.22.0
iOS: 15.4.1

**Comment by DentonGentry** [comment]
The symptoms don't match what was originally described in this bug, and we're also not likely to followup on a comment left on a closed bug.

The next time the iPhone cannot connect or is super slow, please send its Tailscale IP address to support@tailscale.com with a description of that it is doing.

**Comment by zero-pytagoras** [comment]
having the same issue on ubuntu20.04 server
