### ISSUE TITLE
macOS icon animates forever if NetworkExtension is externally terminated

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1649]
Version: 1.6.0

Reported by a user on twitter.

Steps:
1. Start tailscale, login, and connect
2. Use the Network system preferences panel (outside Tailscale) or the Network dropdown menu (if enabled) to stop the VPN.

Expected:
- Tailscale stops and can be re-connected by picking "connect" in the tailscale menu, or by restarting it in the preferences panel.

Actual:
- Tailscale's backend stops as expected
- The icon starts animating, and Connect and Disconnect are both dimmed out. You can pick Login, which re-connects and stops the animation (without actually ever asking me to login...)
- Instead of using the Tailscale UI, if I click "Connect" in the system preferences pane, the NetworkExtension restarts and the routes all start working, but the UI icon *still* continues animating, and the Connect/Disconnect options are still not available.

Workaround:
- Disconnect using the Tailscale UI instead.
- ...which used to kill the IPNExtension, as far as I know. But in v1.6.0 it doesn't. Even when disconnected, if I push the Disconnect button in the network preferences pane, the icon animates forever.

**Comment by diegomontoya** [comment]
dup of #1624
