### ISSUE TITLE
Create a Nix derivation and Nixos module for tailscaled

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#165]
https://github.com/NixOS/nixpkgs/pull/78008 was my initial attempt, using the old pre-OSS relaynode binaries. Now that we have an OSS linux client, it makes sense to build the derivation directly from this repo.

One thing we need to watch out for when making those packages: when building from just the OSS repo, currently we don't build a very good version stamp into the binaries. This is important for us because we use that version stamp to track the state of the Tailscale fleet (what versions are active), so it'd suck to start distributing `vTODO` binaries :). Options for this:
  - In the derivation build, overwrite version/version.go with a generated file that uses `git describe --always` to embed the OSS commit ID.
  - Use the version stamp that's currently in there. It's a date-based stamp that's occasionally updated by @bradfitz. It's easy (no magic needed in nix derivation), but the version stamp is less precise than the option above.
  - Don't build from source, instead grab the static binary tarballs from https://pkgs.tailscale.com/ and just repackage those binaires. They have no external dependencies, so it would be easy, and those binaries contain the version info generated from our corp (non-OSS) repo. But, those binaries aren't 100% reproducible from source, so, :/.

cc @martinbaillie, who expressed interest in nix/nixos packaging.

**Comment by danderson** [comment]
The version stamping thing is already a problem for people building from OSS themselves, btw, it's not a problem unique to Nix. But I would personally like Nix/NixOS to be a first class supported distro, which means I want to get the versioning approximately right, at least :).

This also just connects to a larger issue where, for linux/bsd binaries, we should just be using a version stamping system that uses the OSS repo's information, instead of our corp information. The corp repo version info is literally the only non-OSS thing we burn into those binaries, and we should just... stop :)

I'll file a bug in our corp repo to fix up this version management somehow.

**Comment by martinbaillie** [comment]
Sounds good @danderson. I'll get something basic working to build from source [here](https://github.com/martinbaillie/nixpkgs/commits/add-tailscale) and seek guidance on flags, versioning etc. before PRing to nixpkgs.

**Comment by danderson** [comment]
Thank you! My NixOS servers look forward to it :D

**Comment by martinbaillie** [comment]
Hey @danderson, I have a working derivation and module here: https://github.com/martinbaillie/nixpkgs/commit/d0edc21deb436ca9219d99e62cd7a48716015598

Take a look when you get a spare minute. A few things I wanted to get your input on are:
- I only expose a few flags of `tailscaled` in the systemd unit, leaving out the `--debug/--fake` options and `--tun` (based on my knowledge of that flag probably going away). I could instead add these.
- I was starting to go about the `version.go` patch in the derivation but noticed you cut a tag last night so codified to that instead for now as felt more official?

**Comment by danderson** [comment]
Thank you! I sprinkled some comments on the commit. It looks like there's a lot of them, but it's just me being verbose. It looks great already!

Are you planning to send the PR upsteam? I'm also happy to do the PR process with nixpkgs if you prefer (they can be very slow to review, and I know who to poke :) ), up to you.

**Comment by martinbaillie** [comment]
Thanks @danderson, the verbosity was much appreciated and I am happy to shepherd this in with a PR as I've been meaning to get more involved with Nix upstream packaging in general (having been using NixOS at home for a while but lazily never contributed back!).

I have made all the suggested changes in this commit: https://github.com/martinbaillie/nixpkgs/commit/6fd4a587bdf66622400743b817cc98386f29bf57 (I just got rid of the redundant `systemPackages` reference in the end).

Just before I PR it to Nixpkgs and given we've moved back to git hashes for now, I wonder then if:
- I should patch the `version.go`?
- In your experience, they're likely to accept a PR along the lines of `tailscale: init at <hash>` (rather than tag)

**Comment by danderson** [comment]
Left one more tiny comment, but I think this is ready to go!

  - Don't patch version.go for this upload. I've put "fix version.go nonsense" on my todo list for next week, so for future package updates we can switch to the common format with other distros. In the meantime, the existing package version we have is good enough.
  - As an alternative to using the hash as a version, how about using "0.96-33" ? That's the version number we would burn into packages for the other distros, for this particular build. That way it's an easy identifier for us to figure out the version in the nix source, at least.

cc me on the nixpkgs PR, I can help answer tailscale-ish questions if the reviewers have any!

**Comment by martinbaillie** [comment]
Cheers. I've fixed up (not sure why I didn't believe you first time around re. `unitConfig` — learn something new everyday and all that!). I've raised a PR using 0.96-33 as a version :crossed_fingers:

**Comment by danderson** [comment]
https://github.com/NixOS/nixpkgs/pull/82537 has been merged into nixpkgs master. Thank you @martinbaillie !

If you feel up to another long review turnaround, it would probably be good to cherry-pick the commit into release-19.09 and release-20.03, once master has been released to the unstable track (as soon as Hydra rebuilds the world and verifies that everything works, O(hours)).

**Comment by danderson** [comment]
(I'm also happy to do the backport work, you've done the hard part now and I'm happy to shepherd simple things around, your call :) )

**Comment by danderson** [comment]
Actually, we also need a version bump to 0.97-0, which fixes subnet routing. I sent https://github.com/NixOS/nixpkgs/pull/82824 for that. Once that's in, we can backport init + this to the stable tracks.

**Comment by danderson** [comment]
Update: can't backport to release-19.09, because it runs Go 1.12 and we require Go 1.13 :(.

Looking at "sideporting" into 20.03 now.

**Comment by martinbaillie** [comment]
Doh. Yep I was planning on getting right on to backporting once it got merged. Let me know if I can help! (I see your PRs; looks like they might even be keen for 19.09).

**Comment by danderson** [comment]
Yeah, sorry, I did my daily nix tidying up and got carried away :) I managed to get 19.09 working, at the cost of a minor mass-rebuild. We'll see if the release managers are game.

**Comment by danderson** [comment]
https://github.com/NixOS/nixpkgs/pull/82827 and https://github.com/NixOS/nixpkgs/pull/82831, for those following along.

**Comment by worldofpeace** [comment]
I would be cool to have a nixos integration test for this also.
I don't think we need to require that though, but it's a good thing to encourage.

**Comment by misuzu** [comment]
Just tried out tailscale module on NixOS unstable, followed instructions on [download page](https://tailscale.com/download). `Authenticate and connect your machine to your Tailscale network` step says i need to run `sudo tailscale up`, but there is no `tailscale` binary in path so module should also add `tailscale` package to `environment.systemPackages`.
Also `tailscaled` writes a lot of text to `journald` which is quite annoying and there is no option to make it quiet .

**Comment by martinbaillie** [comment]
> I would be cool to have a nixos integration test for this also.
> I don't think we need to require that though, but it's a good thing to encourage.

Agreed! I don't mind looking at this soon as have never written one.

**Comment by martinbaillie** [comment]
> Just tried out tailscale module on NixOS unstable, followed instructions on [download page](https://tailscale.com/download). `Authenticate and connect your machine to your Tailscale network` step says i need to run `sudo tailscale up`, but there is no `tailscale` binary in path so module should also add `tailscale` package to `environment.systemPackages`.

Hm, `tailscale` is available through my user profile and by extension when I do `sudo tailscale`. I'm still relatively new to NixOS but I couldn't see any examples of using `environment.systemPackages` in services based modules so it seemed like it wasn't convention and users are perhaps expected to add the package themselves if they want system-wide?

**Comment by danderson** [comment]
This bug is about the original packaging, so I think we can close it.

I'll open a followup bug for environment.systemPackages.

Re: VPN-in-VPN routing, there's no general solution to this because we can't reliably tell what is and isn't a "desirable" path, we have to trust the kernel routing table for that. Sorry.

Re: logging volume, we're working on that, but it's going to take a little bit longer. We want to keep the verbosity the same (it helps a _lot_ when debugging weird mesh failures), but make tailscaled do less repeat work. The end result will be less logging when nothing interesting is happening.

**Comment by misuzu** [comment]
> Re: VPN-in-VPN routing, there's no general solution to this because we can't reliably tell what is and isn't a "desirable" path, we have to trust the kernel routing table for that. Sorry.

How about user-configurable interface blacklist? `zerotier-one` has one.
