### ISSUE TITLE
Contribute support for WinTun in wireshark/npcap

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1660]
Wireshark on windows can't see WinTun adapters. This makes it quite hard to debug things on Windows, because I can't as easily dump traffic into Tailscale and see if anything weird shows up.

IIUC, the missing piece of support is in npcap, which needs to become aware of WinTun somehow. I'm fuzzy on the details, but assuming it's not actually impossible to make work, we should make it work and upstream it, both for WireGuard users in general, and for our own sanity in specific.

**Comment by DentonGentry** [comment]
Noting: https://github.com/nmap/npcap/issues/173

Last week I emailed one of the Wireshark maintainers who I've previously met, asking about people in the ecosystem who do contract work. No response yet.

**Comment by bradfitz** [comment]
From their LICENSE:

```
Even though Npcap source code is publicly available for review, it is
not open source software and may not be redistributed without special
permission from the Nmap Project.  The standard version is also
limited to installation on five systems. We fund the Npcap project by
selling two types of commercial licenses to a special Npcap OEM
edition:
```

So rather than do work for them, the other thing we could do is just pay that company to do it.

**Comment by DentonGentry** [comment]
Inquired with sales@nmap.com on 4/15, awaiting response.

**Comment by DentonGentry** [comment]
No response from sales@nmap.com. Looking for other options.

**Comment by DentonGentry** [comment]
Resorted to tweeting. https://twitter.com/dgentry/status/1387418324452003840

**Comment by DentonGentry** [comment]
Response from Fyodor: https://github.com/nmap/npcap/issues/173#issuecomment-829488286

In the next release they'll make the change to include NdisMediumIP in the list of adaptors they scan for, which might be enough to fix it. The next release should be some time in May.

**Comment by DentonGentry** [comment]
Wireshark 3.4.5 was released 4/21, which is too long ago to have included an updated npcap. We'll check the next release.

https://www.wireshark.org/docs/relnotes/

**Comment by DentonGentry** [comment]
https://github.com/nmap/npcap/commit/14b9b023f314ecb15a383fe03fc4f0c58f01937a is the commit in npcap which we think should resolve wireguard interface support. It was submitted 4/29/2021. [Npcap 1.3.1](https://github.com/nmap/npcap/releases/tag/v1.31) was released 4/22/2021, so does not contain it. At the time of this writing, no new Npcap release has been made since 1.3.1.

[Wireshark 3.4.6 was released June 2nd](https://github.com/wireshark/wireshark/releases/tag/wireshark-3.4.6), but still contains Npcap 1.3.1 and does not list the tailscale0 interface on Windows.

**Comment by DentonGentry** [comment]
[npcap 1.5.0](https://github.com/nmap/npcap/releases/tag/v1.50) was released June 23, 2021 and contains https://github.com/nmap/npcap/commit/14b9b023f314ecb15a383fe03fc4f0c58f01937a

Now we wait for a future wireshark release to pull in npcap 1.5.0.

**Comment by DentonGentry** [comment]
[Wireshark 3.4.7 was released July 14](https://github.com/wireshark/wireshark/releases/tag/wireshark-3.4.7) but still contains Npcap 1.3.1 and does not list the tailscale0 interface on Windows.

**Comment by DentonGentry** [comment]
Wireshark has updated to npcap 1.5: https://gitlab.com/wireshark/wireshark/-/merge_requests/3479
We'd expect the next wireshark release to include it.

**Comment by DentonGentry** [comment]
https://github.com/nmap/npcap/issues/173#issuecomment-908545946 indicates that Wireshark will update to the current HEAD of the libpcap tree. We expect the Wireshark 3.5 final release to support WinTun.

**Comment by DentonGentry** [comment]
According to https://github.com/nmap/npcap/issues/173#issuecomment-916289095 npcap-1.55 contains the needed libpcap support for NdisMediumIP.

Now we need wireshark to update from npcap-1.50 to npcap 1.55.

**Comment by DentonGentry** [comment]
https://www.wireshark.org/download/automated/win64/
Wireshark-win64-3.5.1rc0-164-g8b614c6a1cd8

Is correctly decoding packets from the Windows 10 Tailscale interface.
Marking this done.

<img width="694" alt="Screen Shot 2021-09-11 at 2 54 49 PM" src="https://user-images.githubusercontent.com/1140756/132962476-7b7e735d-fcca-482a-91fa-17c2d66588ed.png">
