### ISSUE TITLE
iOS GUI app's toggle switch doesn't stop IPNExtension (Settings shows it still running)

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1662]
Tailscale iOS does not seem to disconnect when changing the toggle from Active to Stopped in the app.

After toggling to Stopped and then going to the Settings > VPN section, it still shows the Tailscale tunnel is connected.

The connection does stop and unable to reach, but the VPN toggle shows active, but the device is not reachable.

**Comment by bradfitz** [comment]
Yeah, it's done this forever on iOS, sadly.

The system-level VPN switch stops the whole IPNExtension. The app-level switch just updates the Tailscale state machine to `WantRunning=false` to bring it down (which removes its network config from the system), but the process is still running, consuming a bit of battery too.

@nickoneill, another thing for your plate?

**Comment by starlessblack** [comment]
Thank you for looking into this.

**Comment by apenwarr** [comment]
https://github.com/tailscale/tailscale/issues/539 is a duplicate, let's use that bug instead.
