### ISSUE TITLE
Use a consistent definition of FQDN throughout the code.

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1664]
In some places, a DNS FQDN requires a trailing dot. In others, FQDNs are provided sans trailing dot.

This leads to some irritating "randomly add or remove a dot" logic strewn through the code. We should adopt a single style and stick to it.

**Comment by DentonGentry** [comment]
I'm not sure this issue is really actionable. Maybe I've developed blindness to it, but I don't know of cases where we need to add a dot to the end of names.

**Comment by DentonGentry** [comment]
In the 2.5 years since this bug was filed, I don't think it has come up again. Closing as not planned.
