### ISSUE TITLE
tailscale up --force-reauth broken

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1671]
First noticed this when working on Synology, but also came up on debian.

If you have a tailscaled sitting in state `WaitLoginURL` and you run `tailscale up --force-reauth`, it will generate a new node key and get a new auth URL. **But**: it will print out the previous auth URL. You go through the signin flow, which appears to work, but your machine is not logged in.

**Comment by bradfitz** [comment]
I just hit a variation of this too.

First time `tailscale up --force-reauth` gave me a URL and I authenticated, but the CLI tool never completed.

Second time it worked immediately, without giving me a URL.
