### ISSUE TITLE
No Internet connection while EXIT Node set from IOS

### ISSUE THREAD

**Issue by lemonsz15** [tailscale/tailscale#1674]
As titled, I have tried to set my exit node to my Armbian Buster ( No issues with firewall, as I’m able to access my Wireguard connection through this server ) . Besides Internet, everything seems running well, I could ping other ‘LAN’ nodes, but just no internet connection when I set the Exit Node from my iPhone, a few app works but most of them down. Chrome browser shows ‘ ERR_NAME_NOT_RESOLVED ‘ for all website, maybe DNS issue ? Internet connection back to normal once I set the Exit Node back to None. Please advise. Thanks !

**Comment by vysecurity** [comment]
Same here...

**Comment by mrogojanu** [comment]
Same here .. any follow-up on this? Thanks.

**Comment by yosefbernal** [comment]
Same here. Why was this issue closed?
