### ISSUE TITLE
How to switch user account in CLI ? 

### ISSUE THREAD

**Issue by lemonsz15** [tailscale/tailscale#1675]
could not find any related guide on  switching user account in CLI . Please advise. Thanks !

**Comment by DentonGentry** [comment]
Typically:
```
tailscale down
tailscale up --force-reauth
```

**Comment by lemonsz15** [comment]
Thanks mate!

**Comment by lemonsz15** [comment]
> Typically:
> 
> ```
> 
> tailscale down
> 
> tailscale up --force-reauth
> 
> ```
> 
> 

Btw, does a node need to be on a Public IP in order to work as an Exit Node ?
