### ISSUE TITLE
Disable ability to toggle off the connection (always-on VPN)

### ISSUE THREAD

**Issue by mrbluecoat** [tailscale/tailscale#1698]
**Is your feature request related to a problem? Please describe.**

The Android app allows the user to stop the connection (toggling "Active")

**Describe the solution you'd like**

We enforce Always On VPN via MDM and the app is forced to always run, but if someone toggles the setting from "Active" to "Stopped" Android says:

```
*Can't connect to always-on VPN*
Tailscale is set up to stay connected all the time, but it can't connect right now. Your phone will use a public network until it can reconnect to Tailscale.
```

**Describe alternatives you've considered**

I've tried checking for a config page or override option but haven't found anything. I also checked the issues list but didn't find a match (apologies if I somehow missed it)

**Additional context**

We'd like to install on corporate owned devices which must use VPN, however if the user can simply open the app and toggle it to "Stopped" it defeats the entire security premise.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3j6fl)

**Comment by DentonGentry** [comment]
Generally environments which require an always-on VPN also require that the VPN be used for all traffic. Tailscale is generally a split-VPN, only traffic destined for VPN-hosted IP addresses will go via Tailscale and traffic destined for other IP addresses goes over the regular Internet.

There is an exit node feature in Tailscale which can make all traffic go over the encrypted tunnel. Would you be using exit nodes?

**Comment by mrbluecoat** [comment]
Yes, we're using an exit node.

**Comment by mrbluecoat** [comment]
The centralized VPN gateway is set up as an exit node but there's no setting in the mobile app to set `--exit-node=MYIPADDRESS`

**Comment by mrbluecoat** [comment]
Perhaps it's because I'm testing on the Solo plan. I just noticed my mobile top-right menu looked different than the guide (no option for "Use exit node...") and the pricing page mentions the "Connectivity" plan supports "Subnet routes and relay nodes" (precursors to exit nodes)

**Comment by mrbluecoat** [comment]
FYI, gateway is running Debian Buster and Android is version 11 (Google Pixel 3a). Both are using the Tailscale 1.6.0 client.

**Comment by DentonGentry** [comment]
The Solo plan doesn't enforce a restriction about use of exit nodes, it is useful for people to be able to test out the feature without having to sign up.

I suspect the exit node has been configured, but https://login.tailscale.com/admin/machines hasn't approved it. You'd see a small exclamation point next to "exit node" in the machine list if it hasn't been approved. The "Review route settings..." menu item next to the exit node would allow its routes to be approved.

**Comment by mrbluecoat** [comment]
I could have sworn I enabled the exit node option in the aboard. It was listed as blue (no exclamation mark) but in the menu it was disabled. Enabling allowed the mobile app to use it. So that tangent is resolved.

Let me know when/if an Always On mobile option will be available (e.g. disable the ability to toggle off and defaulting or configurable to use the exit node)

**Comment by DentonGentry** [comment]
This is something we'll likely do eventually (on all platforms) to enforce security policies, but it isn't imminent and there are a number of things which I'd need to put higher on the priority list to work on. So I think you'll need to make decisions  based on not having it available for the time being.

**Comment by Xalaxis** [comment]
This would also be useful to make the VPN auto-start on boot.

**Comment by DentonGentry** [comment]
@Xalaxis This is done in the Settings > Network & Internet > VPN.
With Tailscale connected, you can select the gear icon next to its name and enable "Always-on VPN"

![Screenshot_20210720-213728](https://user-images.githubusercontent.com/1140756/126432933-f543daf5-5940-44e3-9807-465cde3b5b36.png)

**Comment by Xalaxis** [comment]
@DentonGentry Unfortunately that setting doesn't work for me. Toggling it on doesn't actually start the Tailscale VPN like it should. I'm running the same version you show in your screenshot, does it behave properly for you?

![Screenshot_20210721-125236~2.jpg](https://user-images.githubusercontent.com/12937964/126484637-2801d783-fa7d-4670-891d-78286b060965.jpg)

**Comment by DentonGentry** [comment]
It does work for me. I don't usually keep it selected, but I toggled it to be always-on and rebooted the phone and Tailscale started automatically.

@Xalaxis could you file a new bug? Please include:
- Android version
- device type

We'll be pretty limited in how much help we can provide, though. The app won't know why it didn't get started at boot.

If you're comfortable running adb, `adb logcat -s "com.tailscale.ipn:*"` while the phone starts up may be illuminating.

**Comment by darshinimashar** [comment]
**From: maximilian@mimi.io**

We are currently evaluating tailscale, and we are trying to solve two use cases with it.

Use case 1: Give selected people access to certain internal resources.
Those people are mostly tech-savvy, and this works quite well. They understand (more or less) what an exit node or DNS is, and generally the configuration here on the admin side also seems to be very flexible and easy. This is where tailscale really shines, and traditional VPN providers struggle or fail. Here we are quite happy so far.

Use case 2: Protect all employees (in a simple & easy way) from evil public networks – like a traditional VPN
This is where we are having issues with tailscale. The majority of our employees are on macOS and just want to (& should) install the tool and "forget about it". They should not need to remember to select an exit node, and maybe un-select it when being at home or in the office. They should also not have access to disable tailscale DNS or subnets and such, and probably also maybe don't need to know about the "network devices" section.
From experience with providing other "abstract" technical tools to end-users, exposing such settings just causes a lot of support issues, and people to start disliking tailscale and turning it off entirely.

So, I hope I'm not stepping on your toes if I describe them this way – as you of course know a lot better how to achieve this –, but from what I can tell I'd probably describe the needed features like so:
Add toggles to the admin interface for the following options [Prio: High or N/A, see below] 
Enforce the use of exit nodes [Prio: High]
Hide the "Exit node: None" option
Auto-select the first exit node when connecting
Hide the "Exit node: Allow local network access" option
Optionally, add an option for white-listed networks/SSIDs where no exit node is used
Enforce tailscale network settings [Prio: High]
Hide "Use tailscale DNS settings"
Hide "Use tailscale subnet settings"
Hide "Allow incoming connections"
Enforce "Start at login" [Prio: Medium] 
Hide "Start at login" from UI
Hide the network device information [Prio: Low]
Hide "Network Devices" section
Hide "This device" entry
[Bug] Fix the UI showing being "logged out" when disconnecting the tunnel from the IPNExtension
It probably makes sense to allow controlling all this granularly from the admin interface. However, from what I can tell, this could also entirely be achieved on client side only, by providing an alternative tailscale client app.In fact, we have been thinking already of "simply" taking your open source implementation and creating our own custom macOS wrapper around it to provide to our employees. However, as that would be quite a bit of waste of resources (as we'd need to recreate 90% of what you did already), we first wanted to reach out to you and ask for your opinion on the above features.

In case those don't fit your current product feature roadmap, or you're limited by internal resources, we could alternatively also offer to implement them ourselves (in alignment with you), either by contributing them publicly (in case open sourcing the client(s) is an option for you), or under NDA for our internal use only.


https://app.frontapp.com/open/cnv_hl7g2c1

**Comment by mrbluecoat** [comment]
> This is something we'll likely do eventually (on all platforms) to enforce security policies, but it isn't imminent and there are a number of things which I'd need to put higher on the priority list to work on. So I think you'll need to make decisions based on not having it available for the time being.

Just a friendly ping on whether this might happen soon..

**Comment by mrbluecoat** [comment]
Ref: https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/mdm-deployment/parameters/#switch_locked

**Comment by mrbluecoat** [comment]
> This is something we'll likely do eventually (on all platforms) to enforce security policies, but it isn't imminent and there are a number of things which I'd need to put higher on the priority list to work on. So I think you'll need to make decisions based on not having it available for the time being.

friendly ping a couple years later...

**Comment by DentonGentry** [comment]
We understand the requested feature. We don't work simultaneously on every open issue, and though this one is closer to being worked on we are not ready to post updates about it yet.

**Comment by mrbluecoat** [comment]
More extensive discussion and tracking of this issue is on https://github.com/tailscale/tailscale/issues/9428, closing as a duplicate of https://github.com/tailscale/tailscale/issues/9428
