### ISSUE TITLE
DNS via NetworkManager deletes the tailscale IPv6 addr

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1699]
When programming via NM, we seem to be holding something wrong now that IPv6 is present, and NM seems to delete our v6 addr. Needs fixing before 1.8.

**Comment by danderson** [comment]
This doesn't appear to be a regression from 1.6, at first glance. AFAICT it's a regression from "we used to not have v6 addrs, so what we did to configure DNS worked without side-effects." Still digging.

**Comment by danderson** [comment]
Unfortunately, I've replaced one breakage with another, and it's not clear I can fix this new one.

NetworkManager only lets you specify DNS configuration if you place the interface in "manual" or "auto" mode. If you do, you must tell NetworkManager about interface IPs you want to keep around, or it'll blow them away when applying interface settings and break Tailscale.

But, when you tell NetworkManager about a v6 address that's already on the interface and that you want to keep, NM will still delete the address from the interface and re-add it. That wouldn't be a problem, except that deleting the interface address implicitly also deletes our v6 route in table 52, so when we apply DNS settings in NM we end up deleting our v6 connectivity regardless.

**Comment by DentonGentry** [comment]
This is specific to a version of Network Manager, more recent releases do not do this. Only happens on older Linux machines.

Network Manager fixed the bug that made us do this in 11/2020.

**Comment by danderson** [comment]
Confirming after further digging: we cannot fix this properly, because the only option that would work would be to make NetworkManager manage our entire network configuration rather than just DNS, and old NM doesn't have the ability to express our network config (in particular policy routing and separate route tables).

This would be fine if we could always _not_ use NM, but there are paths in the graph of possible configs where NM is unavoidable to get functioning DNS configuration, so... We're pretty stuck.

The next best thing I can do is to alter our linux configurator selector to use NM as rarely as possible, which results in technically-less-good configurations in several cases, but those configs don't have harmful side effects. The remaining cases where we _must_ use NM will result in broken IPv6 tailscale configs, but we're unfortunately stuck with that.

**Comment by DentonGentry** [comment]
This bug is addressed as well as I think it can be. Our long term plan is for distributions to update to current Network Manager versions, where we can get better behavior.

This bug is still discoverable for documentation purposes while closed, going to close it now.
