### ISSUE TITLE
Yum signature check fails on Amazon Linux 2

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#170]
Amazon Linux 2 ships a GnuPG with some kind of bug that makes it hate our signing key. It has the same issue with GCP's signing key, so we're in good company, I guess?

Nothing we can do about this right now. You should definitely, definitely not disable signature checks to work around this (which is apparently what the entire Kubernetes world has been doing?!). Amazon is working on fixing their gpg, so it should just be a matter of sitting tight.

**Comment by bradfitz** [comment]
Are we signing with gnupg's gpg binary or with Go? If Go, we could at least massage the format enough to make their old gpg happy. But agreed not worth it if they're just going to fix it soon. (Do they have just one update track?)

**Comment by danderson** [comment]
We sign with Go's, but we also don't know the root cause, I didn't get precise details from Amazon folks (partly because gpg's troubleshooting tools aren't good enough to pinpoint precisely).

There's a single release track afaik.

**Comment by danderson** [comment]
Now fixed by Amazon. I've added docs on tailscale.com's KB telling people to update gnupg2 in case of signature errors.
