### ISSUE TITLE
D-Bus API for tailscaled

### ISSUE THREAD

**Issue by lrewega** [tailscale/tailscale#1709]
**Is your feature request related to a problem? Please describe.**

It would be convenient to have programmatic way to listen for state changes in tailscaled.

**Describe the solution you'd like**

While I am generally not a big user of D-Bus, I think it would be appropriate to expose some slots for other clients to register signals for state changes. In particular, this would enable a pretty trivial implementation for #1708 

**Describe alternatives you've considered**

There's a billion other ways state changes could be published (HTTP/unix socket? polling? some sort of gross run-parts?). I don't feel strongly here. In particular, systemd targets seem inappropriate as it's difficult to cross system/session boundaries. While D-Bus is similar, session-to-system-bus is at least a common pattern.

**Additional context**

I'd be willing to contribute to this to enable #1708

**Comment by bradfitz** [comment]
Our unix socket is already also an HTTP server implementing a local API, and it already does some streaming stuff, which is how our Windows/Mac/iOS/Android clients work, connecting and subscribing to state changes.

Extending that a bit for #1708 seems easy. Maybe D-Bus is also easy, but we don't have much of that currently.

**Comment by danderson** [comment]
D-Bus is relatively easy, but it'll be another protocol on top of the one we already have, unless we implement some translation glue. It'd be nice to fit more seamlessly into a linux desktop though.

**Comment by lrewega** [comment]
Ah I hadn't seen the streaming stuff, cool. I had originally assumed the new client API would be the way to go, but I suppose it makes more sense to be like the rest of the GUI clients. It's a shame I can't peek at their code!

I'll close this out for now.

**Comment by bradfitz** [comment]
@lrewega, the Win/Mac GUI clients are super thin wrappers atop Go code.

To see how to subscribe to the real-time "IPN bus" from Go, see https://github.com/tailscale/tailscale/blob/50b309c1ebc73b8e3470633cb94b3803b5805c63/cmd/tailscale/cli/debug.go#L90 (`tailscale debug --ipn`).
