### ISSUE TITLE
Forward DNS traffic to exit node

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1713]
Our user suggested the feature for 1.8+ , When using the MagicDNS/100.100.100.100 local DNS resolver within Tailscale, AND if an exit node is currently configured to be active, then the local tailscaled resolver should forward DNS requests to the exit node tailscaled resolver, and allow the exit node to resolve the name on behalf of the client. This would generally allow geo-DNS based records to return an IP that is “closer” to the exit node (vs. “closer” to the client). 

***** One could argue this is actually a security and/or privacy requirement, as it further masks the location of the actual client and furthers the appearance that the exit node represents the actual client.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_319zl)

**Comment by danderson** [comment]
Yes, this is the plan, and I hope to get it working for 1.8. It looks like I never filed a bug for it, so this is a great tracking bug.

**Comment by DentonGentry** [comment]
This feature is present in 1.19.x builds in https://pkgs.tailscale.com/unstable/ and will be in the 1.20 release build.

**Comment by bradfitz** [comment]
This shipped in 1.20.0.
