### ISSUE TITLE
/etc/resolv.conf not update on OSX

### ISSUE THREAD

**Issue by renaudhager** [tailscale/tailscale#1714]
**Describe the bug**
Hi guys,
I openning this beause https://github.com/tailscale/tailscale/issues/907 has been closed. 
What is the solution for people that are not on Big Sur?
I have the same issue, tailscale client does not update `/etc/resolv.conf`.

**To Reproduce**
1. Connect the tailscale client
2. Read `/etc/resolv.conf`

**Expected behavior**
`/etc/resolv.conf` should be updated.

**Comment by crawshaw** [comment]
Sorry, there is no solution for older macOS versions. The Tailscale app runs in a sandbox and does not have permission to edit /etc/resolv.conf.

**Comment by DentonGentry** [comment]
There is another way to run Tailscale, outside of the AppStore, which does not run within the sandbox and may work better for you: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS
This runs tailscale in a similar way as Linux, with a CLI and no menu bar icon.

There is also progress being made on https://github.com/tailscale/tailscale/issues/718 which would be more similar to the current AppStore version in that it appears in the menu bar, but may not be subject to the same sandboxing limits (I'm not sure).
