### ISSUE TITLE
magicsock: NotePreferred call only partially works

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#172]
On trying to send a packet to a DERP server, we call `derphttp.NewClient`. It is then immediately followed by a NotePreferred call, which sets the preferred field in the derphttp client. But as the
connection is established lazily, c.client  == nil. That means the bit is not sent to the server until `connect` is called. But that only sends the bit if preferred==true.

Moreover, later when `NotePreferred` is called again, the preferred field in the derphttp client has already been set, so then the bit is never sent to the DERP server.

The result is we do not send preferred==false to DERP servers.

**Comment by bradfitz** [comment]
Intentionally. Preferred==false is the default so it doesn't need to be sent.

**Comment by crawshaw** [comment]
OK no worries then.
