### ISSUE TITLE
Fresh install won't allow `tailscale up` without reset

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#1725]
**Describe the bug**
I updated the Cloud Run image to HEAD. The image has no /var/lib/tailscale/tailscale.state file, so no saved options. `tailscale up --authkey=${TAILSCALE_AUTHKEY}` fails with:

`'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --accept-routes is not specified but its default value of false differs from current value true`
`'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --advertise-routes is not specified but its default value of [] differs from current value []`

Adding `--reset` allows it to start but I suspect this wasn't intended.

**To Reproduce**
I think any system which does not have a /var/lib/tailscale/tailscaled.state file is likely to run into this.

**Version information:**
 - Device: Cloud Run instance
 - OS: Linux-ish
 - OS version: N/A
 - Tailscale version: HEAD as of 17 Apr 2021.

**Comment by bradfitz** [comment]
Whoops, GitHub got confused by my commit body test `before I actually fix #1725`. I forgot how lax its parsing is.
