### ISSUE TITLE
Is constant disk i/o necessary?

### ISSUE THREAD

**Issue by MarkoPaasila** [tailscale/tailscale#1732]
**Describe the bug**
Disk reads and writes almost all the time - looking at iotop. I'm not sure if it matters, but trying to find out how to make a hdd based system less slow, tailscaled seems to be accessing the drive much more than other background programs.

**Reproduce**
1. Install and run tailscale on Linux
2. observe iotop

**Expected behavior**
Writes to disk rarely, if ever.

**Version information:**
 - Device: Laptop, i5-3320M, spinning disk, 4GB ram.
 - OS: Arch Linux
 - OS version: up to date
 - Tailscale version: 1.6.0

**Additional context**
Some 5 active peers

**Comment by bradfitz** [comment]
It's almost certainly log output.

https://github.com/tailscale/tailscale/issues/1548 tracks reducing it and adding more user-tunable knobs for controlling it.

Without more details here indicating that this is unique in some way, I'm going to close this one as a dup of #1548.

If you see something obviously broken in your logs that's spamming a lot, let us know and we can reopen this for that specific problem. Or if you give us your Tailscale IP we could take a look at the logs on our end.

**Comment by tshcherban** [comment]
@bradfitz 
I have tailscale on my raspberry with a Stdout=null configured, so no logging should go to disk. however i get quite a lot of writes to the 

> tailscaled --state=/var/lib/tailscale/~tailscale/tailscaled.sock

can that behavior be controlled somehow?

**Comment by kwando** [comment]
I also see this is writing to disk a lot on my raspberry pi, this will wear out the SD card quite quickly.  Any ideas on how to tune this?

<img width="1224" alt="Image" src="https://github.com/user-attachments/assets/e491cbed-20fa-4e30-9a95-ab4a2275cfce" />
