### ISSUE TITLE
Download host list as dns A records.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1733]
One of the users would suggest a feature to be able to download the host list as DNS A records.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31ij5)

**Comment by bradfitz** [comment]
In the admin panel? (cc @rosszurowski @soniaappasamy @catzkorn)

Would `jq` work instead?

```
$ tailscale status --json | jq -r '.Peer[] | .DNSName + " A " + .TailAddr'
```

**Comment by charlieh0tel** [comment]
yes,  originally, i was asking for this in the admin panel,  but that pipe will do fine.
