### ISSUE TITLE
macOS/IOS: on disconnect from tray icon , still shows Tailscale connected in network preferances.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1734]
If the user connects through Tailscale and then chooses Disconnect from the Apple menubar icon, it seems Tailscale does not actually Disconnect.A quick trip to Network preferences shows this:
<img width="729" alt="Connected-NotConnected" src="https://user-images.githubusercontent.com/75628398/115265414-30c41f80-a105-11eb-8c0d-802a1f9ffbfa.png">

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31jf5)

**Comment by bradfitz** [comment]
> from the Apple menubar icon

To be clear, this but is about hitting "Disconnect" from the *Tailscale* menu bar icon, not the Apple-provided "VPN" menu bar icon.

That is, **not** this one:

<img width="42" alt="Screen Shot 2021-04-19 at 9 12 55 AM" src="https://user-images.githubusercontent.com/2621/115268731-6e1db280-a0ef-11eb-94ae-931033495898.png">

**Comment by thellum** [comment]
Correct. This is hitting Disconnect from the Tailscale menubar, and then still showing as connected in Apple System Preferences.

**Comment by neophit** [comment]
This is true for iOS (both iPad and iPhone) as well; Tailscale app shows `Stopped`, and `Settings -> VPN` shows status `Connected` with `Tailscale Tunnel` as the active VPN Configuration. Selecting the `Tailscale Tunnel` configuration to view additional details shows `Connected Time` accumulating seconds.

**Comment by morpig** [comment]
Having this issue too on 12 Pro (14.5.1), was unable to connect to all my tailscale-connected devices.

Tried disconnect/connect multiple times from the tailscale app (no errors shown, normal UX), turning on/off airplane mode, not working. 

I found out that when it's in disconnect state (on the Tailscale app), it is still shown as connected (through the VPN logo on the status bar, and on settings). Fixed it by manually disconnecting it from the VPN setting.

Hard to reproduce, but what I remembered was trying to add another VPN profile while tailscale is running, hopefully that helps.

**Comment by vdovhanych** [comment]
Also seeing same behavior on my iOS and macOS devices. When you use the tailscale app to disconnect it shows as disconencted and vpn stops working. But if you go in to the settings Tailscale vpn shows you're still connected. 
If you discoonetct it in the iOS or macOS settings it then shows you're not logged in if that helps somehow. Can send any logs or screenshots if needed.

**Comment by elyscape** [comment]
The issue at hand is that, when the user selects "Disconnect" in the Tailscale app, the Network Extension doesn't actually terminate. This results in the VPN connection remaining connected, even if Tailscale isn't doing anything. Incidentally, this means that the iOS app doesn't play well with other VPN apps; if another VPN Network Extension is active, they generally (reasonably!) assume that another VPN is active and will refuse to connect. Currently, to connect to another VPN on iOS, you often need to go to Settings.app and manually disconnect the Tailscale VPN, even if you've already disconnected in the Tailscale app.

**Comment by vvuk** [comment]
This is still an issue with the released iOS 16/16.1. Quite frustrating, even if I disconnect from the OS settings vpn panel, it doesn't actually disconnect. Only workaround I've found was to switch to a different vpn profile, which actually causes a disconnect.

**Comment by h3nrique** [comment]
This is still an issue with the released iOS 16 (16.2/16.3).

I can do user tests on TestFlight build if necessary.

**Comment by haitrr** [comment]
this is still happening to me on iOS 16.4

**Comment by agottardo** [comment]
Fix will land in iOS TestFlight soon. Leaving this open because macOS needs a separate PR.

**Comment by benniekiss** [comment]
The most recent testflight build (1.47.37) appears to work well on iOS.

One lingering issue, maybe just a feature, is that if the tailscale client is disconnected and force-closed (removed from app switcher) and then re-opened, it will automatically activate the VPN connection. When the app hasnt been force-closed, reopening the app does not automatically connect.

**Comment by agottardo** [comment]
@benniekiss Glad it works for you. Please report any bugs! 🙏🏻 

> if the tailscale client is disconnected and force-closed (removed from app switcher) and then re-opened, it will automatically activate the VPN connection

This is an interesting user experience thing: all our UI clients connect automatically at launch for a more seamless experience. Out of curiosity, what's your use-case for opening the Tailscale app without connecting the tunnel? The app can't do much when the tunnel is disconnected (at least for now).

**Comment by benniekiss** [comment]
> @benniekiss Glad it works for you. Please report any bugs! 🙏🏻
> 
> > This is an interesting user experience thing: all our UI clients connect automatically at launch for a more seamless experience. Out of curiosity, what's your use-case for opening the Tailscale app without connecting the tunnel? The app can't do much when the tunnel is disconnected (at least for now).

No use case in particular, and the UX reasoning makes sense! One case I could think of would be accidentally opening the app, and reducing system changes without direct user consent/input. maybe an "auto-connect on app launch" setting. 

Also, it might be changed with the next macOS release, but currently, if you disconnect from the tailscale client, quit the tray icon, and relaunch the app, the tailscale client will be disconnected, but if you quit the tray icon while connected and relaunch the app, it will auto-connect. This is essentially the behavior I was expecting of the iOS app.

**Comment by agottardo** [comment]
A fix for this issue on macOS has been pushed to unstable. Please try this on version 1.55.72 or newer.

**Comment by nwidynski** [comment]
This appears to have regressed for me? 

OX Tahoe 26.2
Tailscale 1.94.1
