### ISSUE TITLE
Android as exit node

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#1738]
**Is your feature request related to a problem? Please describe.**

A customer requested a way to access the internet on their iOS device via a SOCKS proxy server running on an Android device. This looks like a complicated way of achieving the same effect as making the Android device an exit node.

**Describe the solution you'd like**

Make Android able to act as an exit node.

**Describe alternatives you've considered**

Running a SOCKS server on Android that is accessed via Tailscale could achieve similar results, but for this particular customer, iOS would not allow running a VPN application and SOCKS client at the same time.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31lch)

**Comment by DentonGentry** [comment]
Hybrid netstack mode would provide a way to do this. I believe we hooked it up for MacOS and Windows, could probably do so for Android as well.

How to enable --advertise-exit-node on Android would be a problem. For MacOS and Windows we require use of the command line, as the UI does not provide a way to do so. On Android the CLI is not available.

**Comment by DentonGentry** [comment]
Blocked by https://github.com/tailscale/tailscale/issues/1970

**Comment by bradfitz** [comment]
Okay, this is now done, at least enough for a [BETA] label. It's hidden by default, though. You need to search for "debug" once to make the secret menu option appear.

It will be in the next 1.19.x build and probably 1.20.0, unless we find problems and pull it.

<img width="548" alt="Screen Shot 2022-01-07 at 10 22 03 AM" src="https://user-images.githubusercontent.com/2621/148589116-c78cd63c-2fa8-4cee-8692-b76ea9390e90.png">

**Comment by cyrus104** [comment]
I'm testing this function right now and even though it looks like it is running an exit node other device are not able to see it.
I'm running this on a Pixel 6 Pro and also on a OnePlus 7 with the same results.

Other tailscale devices get node 100.*.*.* is not advertising an exit node.

**Comment by DentonGentry** [comment]
If you paste in the line from the Bug Report menu item during the time the Android device has the exit node feature turned on, we can look into what it is reporting.

**Comment by bradfitz** [comment]
@cyrus104, remember that you also need to approve the exit node in the web admin console at http://login.tailscale.com/admin/machines

**Comment by cyrus104** [comment]
@bradfitz, you were correct in that I did not approve it in admin panel.. RTFM

@DentonGentry 
I am still getting a similar error. After doing additional reading, I have have used tailscale ping and can get pong from <exit node> (internal ip) via DERP(sea) in 200ms. What I get from this is that I am going need to go through a relay because the device are not? able to directly talk? Which technically for testing purposes they can. They are both inside my home lab on different vlans but there is a route that lets them talk. No sites are loading though, ping to the site ip works but no other traffic. 

BUG-4ab0854226c742e3d4ca193566696dc1ac8d667175807e29f0706ed8a7657da1-20220220023919Z-49240ffdcfa6270f

Thanks a bunch.

**Comment by bradfitz** [comment]
@cyrus104, why don't you file a separate bug about this, so we don't disrupt this meta bug? In your new bug, include a lot more details, like the CIDRs of your VLANs and what IP/DNS name you were pinging, the bug report of both sides right after it doesn't work, and the results of `dig @100.100.100.100 google.com` from your Ubuntu box.

**Comment by cyrus104** [comment]
@bradfitz, rgr

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale-android/pull/49 moves the exit node function to Android's main menu, not hidden behind a magic "debug" search.
