### ISSUE TITLE
ACLs have no way to represent "allow user to use this exit node" without completely opening all traffic

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1742]
Right now, to allow access for user a@example.com to access the Internet through an exit node, you need to write an ACL such as:
```
{
  "Action": "accept",
  "Users": ["a@example.com"],
  "Ports": [0.0.0.0/0],
}
```

Which is a lot more generous than actually intended: such a rule would entitle the user to access *all* exit nodes, and also every port on every server inside the Tailscale network.

We would like a new kind of ACL semantics, which say only "you can access every IP address through node X, but not private networks, and you're not allowed to access those same IP addresses through Y and Z."

A temporary workaround is to put a list of all non-private subnets in the Ports[] section, but that ends up being a very long, very ugly list and is extremely fiddly.

The lack of this feature mostly makes exit nodes incompatible with heavy users of ACLs. However, it seems like most users of exit nodes are separate from most users of ACLs (for now), so it's less urgent than it might seem at first. And technically this is not a regression vs v1.6, since this missing feature has been missing since exit nodes first entered public beta.

cc: @danderson @sailorfrag 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_35udt)

**Comment by apenwarr** [comment]
Forum post: https://forum.tailscale.com/t/user-cant-use-exit-node-but-it-works-in-admin-account/571/3

**Comment by bradfitz** [comment]
(Related internal bug: https://github.com/tailscale/corp/issues/1578)

**Comment by thinkst-todor** [comment]
ACL user here. First thing we did when on-boarding with Tailscale was to switch the ACL policy from default-permit to default-deny with explicit permits.

This renders exit nodes useless for us.

**Comment by bradfitz** [comment]
@thinkst-todor, as a temporary workaround, you can add allows for all IPs that aren't Tailscale IPs or other things you have rules for, like:

https://play.golang.org/p/jt_dt-oPeV8

**Comment by thinkst-todor** [comment]
@bradfitz thanks! That's workable. 

Modified source code slightly to produce output compatible with `"Ports":` declarations: https://play.golang.org/p/gWNsOaKskWV

Or if anybody just wants to copy/paste the output

```
{
    "Action": "accept",
    "Users" : [ "*" ],
    "Ports" : [ "0.0.0.0/2:*",
"64.0.0.0/3:*",
"96.0.0.0/6:*",
"100.0.0.0/10:*",
"100.128.0.0/9:*",
"101.0.0.0/8:*",
"102.0.0.0/7:*",
"104.0.0.0/5:*",
"112.0.0.0/4:*",
"128.0.0.0/1:*",
"::/1:*",
"8000::/2:*",
"c000::/3:*",
"e000::/4:*",
"f000::/5:*",
"f800::/6:*",
"fc00::/8:*",
"fd00::/10:*",
"fd40::/11:*",
"fd60::/12:*",
"fd70::/13:*",
"fd78::/15:*",
"fd7a::/20:*",
"fd7a:1000::/24:*",
"fd7a:1100::/26:*",
"fd7a:1140::/28:*",
"fd7a:1150::/29:*",
"fd7a:1158::/30:*",
"fd7a:115c::/33:*",
"fd7a:115c:8000::/35:*",
"fd7a:115c:a000::/40:*",
"fd7a:115c:a100::/41:*",
"fd7a:115c:a180::/42:*",
"fd7a:115c:a1c0::/43:*",
"fd7a:115c:a1e1::/48:*",
"fd7a:115c:a1e2::/47:*",
"fd7a:115c:a1e4::/46:*",
"fd7a:115c:a1e8::/45:*",
"fd7a:115c:a1f0::/44:*",
"fd7a:115c:a200::/39:*",
"fd7a:115c:a400::/38:*",
"fd7a:115c:a800::/37:*",
"fd7a:115c:b000::/36:*",
"fd7a:115c:c000::/34:*",
"fd7a:115d::/32:*",
"fd7a:115e::/31:*",
"fd7a:1160::/27:*",
"fd7a:1180::/25:*",
"fd7a:1200::/23:*",
"fd7a:1400::/22:*",
"fd7a:1800::/21:*",
"fd7a:2000::/19:*",
"fd7a:4000::/18:*",
"fd7a:8000::/17:*",
"fd7b::/16:*",
"fd7c::/14:*",
"fd80::/9:*",
"fe00::/7:*" ]
}
```

**Comment by gleb-jiji** [comment]
Perhaps ACLs could support allowing traffic to certain IPs via particular hosts (or hosts with a particular tag), e.g. _allow users X ports `0.0.0.0/0:*` via `100.123.45.67`_. I wonder if this could also make separate "Subnet routes" and "Use as exit node" controls redundant.

**Comment by damomurf** [comment]
@bradfitz @apenwarr Aren't the ipv6 addresses in these allow lists redundant because they're not able to be specified in ACLs currently? Is that on the radar?

**Comment by damomurf** [comment]
Also, the Playgrounds above don't compile any more, so I fixed them: https://play.golang.org/p/NY2mhyGqYZE

**Comment by bradfitz** [comment]
We now support `autogroup:internet` as a magic host that means public IP space. e.g., an ACL that permits foo@bar.com to access any port 443 or port 22 out on the internet:

```
{
  "ACLs": [
    {
      "Action": "accept",
      "Users": ["foo@bar.com"],
      "Ports": ["autogroup:internet:443,22"],
    },
  ],
}
```

**Comment by gleb-jiji** [comment]
> ```
>     {
>       "Action": "accept",
>       "Users": ["foo@bar.com"],
>       "Ports": ["autogroup:internet:443,22"],
>     },
> ```

How does this interact with subnet routes? If I expose from some host an internet routable subnet, say, `90.1.1.0/24`, is `foo@bar.com` going to get access to it?

**Comment by sailorfrag** [comment]
> > ```
> >     {
> >       "Action": "accept",
> >       "Users": ["foo@bar.com"],
> >       "Ports": ["autogroup:internet:443,22"],
> >     },
> > ```
> 
> How does this interact with subnet routes? If I expose from some host an internet routable subnet, say, `90.1.1.0/24`, is `foo@bar.com` going to get access to it?

Yes.

`autogroup:internet` is currently defined as
add 0.0.0.0/0
add 2000::/3

remove 10.0.0.0/8
remove 172.16.0.0/12
remove 192.168.0.0/16
remove fc00::/7

remove 100.64.0.0/10
remove fd7a:115c:a1e0::/48

remove 169.254.0.0/16
remove fe80::/10

We may adjust the exact list as necessary, but that should be infrequent.
