### ISSUE TITLE
cli: provide better errors for new explicit flag behavior

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#1746]
In 9972c02b60d74f177eee6a5214573cf7a8dcfc5e we introduced a new approach to `tailscale up` which requires every option to be explicitly mention, avoiding a common pitfall where users would forget a flag they previous used, and end up changing their Tailscale settings.

As a part of that commit, we introduced a new error message that's a little… verbose. For example:

```console
$ tailscale up --accept-dns=true

encountered multiple errors:
	... 'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --accept-routes is not specified but its default value of false differs from current value true
	... 'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --advertise-routes is not specified but its default value of [] differs from current value [10.0.0.0/8]
	... 'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --snat-subnet-routes is not specified but its default value of true differs from current value false
	... 'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --netfilter-mode is not specified but its default value of "on" differs from current value "off"
```

Before we release v1.8 we should refine this error message so that it's more actionable and easier to parse. Let's collapse all the duplicated text and provide users with a copyable command they can run, like so:

```console
$ tailscale up --accept-dns=true

'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned:

  tailscale up --accept-dns=true --accept-routes=true --advertise-routes=10.0.0.0/8 --snat-subnet-routes=false --netfilter-mode=off
```

/cc @bradfitz

**Comment by bradfitz** [comment]
I imagine this will be a little confusing to people:

> 'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned:

They'll probably think "but they're not changing".

Maybe instead:

> 'tailscale up' without --reset requires all preferences with non-default values to be explicitly mentioned:

But that's likewise not accurate for the case where for example somebody's removing, say, advertised routes:

```
  tailscale up --accept-dns=true --accept-routes=true --advertise-routes=
```

(that's still the default value)

So in that case, "changing" is more correct. Pretty hard to describe succinctly.

Thoughts on including both the copy/pasteable `tailscale up` command that will work, alongside the details about the daemon current value vs flag default value?

(In any case, I do love the copy/pasteable `tailscale up` command in the output.)

Maybe say both things:

> 'tailscale up' without --reset requires explicitly mentioning all non-default or changing values:

🤷
