### ISSUE TITLE
"tailscale up" arg checking doesn't check --advertise-exit-node

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1767]
```
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node=false
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node=true 
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node=false
~ $ sudo ~/bin/tailscale up --advertise-exit-node
'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; --advertise-routes is not specified but its default value of [0.0.0.0/0 ::/0] differs from current value [10.0.42.0/24]
```

Expected:
Forgetting --advertise-exit-node when supplying --advertise-routes, if --advertise-exit-node had previously been set, should produce the same error as forgetting --advertise-routes when it was previously set.

**Comment by bradfitz** [comment]
This is working as designed. We don't track tristates on the backend.

We only prevent you from making changes that aren't mentioned. In this case, you didn't mention something, but it didn't result in a change so it's okay.

Issue #1746 will make these error messages easier to understand.

**Comment by apenwarr** [comment]
I don't think you're correct. I tried several different combinations in the flow above. One of them enabled exit nodes, followed by one that mentions advertise-routes but not exit nodes.

**Comment by apenwarr** [comment]
Oh, sorry, I sort of see what you mean: I mentioned only a subset of the previous options, but not all of them, so since it's considered unchanged, it doesn't care that I only mentioned a subset? I don't think that behaviour is desirable. Shouldn't it be "specify anything at all, and we'll reject it if you forgot the other things"?

**Comment by bradfitz** [comment]
It's only an error if it's both not mentioned and changing. #1746 tracks explaining that better.

**Comment by bradfitz** [comment]
In the second line here, `--advertise-exit-node` isn't mentioned, but it's default value is already `false`, so it wouldn't be a change, so it's not an error.

```
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node=false
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 
```

**Comment by apenwarr** [comment]
Yes, but that's not true in this combination further down, which also didn't throw an error:

```
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node=true 
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 
```

**Comment by apenwarr** [comment]
Oh, I just tried this and it also didn't report a problem:

```
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.42.0/24 --advertise-exit-node=true
~ $ sudo ~/bin/tailscale up --advertise-routes=10.0.41.0/24 
```

**Comment by bradfitz** [comment]
Ugh, sorry, I'd stopped reading at line 3 and dup-bug-knee-jerked. And I also forgot that `--advertise-exit-node` handled specially in the code:

```go
        case "advertise-exit-node":
                // This pref is a shorthand for advertise-routes.                                                                                                                                                  
```

In this case, it's still working as designed, but in an unfortunate way:

Because `--advertise-routes` just modifies `--advertise-routes`, and you specified `--advertised-routes` on the next line, it's happy.

The problem is we don't even track an "advertise exit node" pref at all. That is, we don't store the difference between:

```
    up --advertise-routes=10.0.42.0/24 --advertise-exit-node=true
    up --advertise-routes=10.0.42.0/24,0.0.0.0/0,::/0
```

I guess we should add a bool pref to track `--advertise-exit-node` explicitly. Sigh.

**Comment by bradfitz** [comment]
Actually, I should be able to pretend a server-side pref exists, based on whether the set of advertised routes contains both the /0 ones.
