### ISSUE TITLE
Provide apt sources list for Ubuntu 21.04 Hirsute Hippo

### ISSUE THREAD

**Issue by tdalbo92** [tailscale/tailscale#1773]
**Is your feature request related to a problem? Please describe.**

It seems like https://pkgs.tailscale.com/stable/ubuntu/hirsute.list hasn't been created yet.  I'm not sure if packages are being generated for Ubuntu 21.04 yet, or if that file just needs to be created. 

**Describe the solution you'd like**

Support for packages in Ubuntu 21.04

**Describe alternatives you've considered**

Currently Tailscale works in Ubuntu 21.04, it just won't get updates.

**Additional context**

**Comment by vielmetti** [comment]
same question here!

**Comment by DentonGentry** [comment]
We've added an entry for Hirsute Hippo in the pkgserver code, which will go live on the next prod deploy.

**Comment by bradfitz** [comment]
Pushed: https://pkgs.tailscale.com/unstable/#ubuntu-hirsute

**Comment by tdalbo92** [comment]
Awesome thanks for the quick turnaround on this

**Comment by vielmetti** [comment]
Install instructions are erroring out, here's a transcript

```
root@hippo-c3:~# curl -fsSL https://pkgs.tailscale.com/unstable/ubuntu/hirsute.gpg | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
curl: (22) The requested URL returned error: 404
gpg: no valid OpenPGP data found.
```

Looks like apt-key has some changes in this release too related to being deprecated, so that looks like a future problem to be addressed.

**Comment by tdalbo92** [comment]
@vielmetti You're hitting two separate issues:

- the 404 (which should be now resolved, try it again) 
- the deprecated `apt-key` usage (it'll still work fine, it's just a warning)

**Comment by vielmetti** [comment]
@tdalbo92 thanks - I am just copying the install instructions from https://pkgs.tailscale.com/unstable/ - perhaps this is better described as a documentation bug. I'll try the groovy GPG key.

**Comment by tdalbo92** [comment]
Sorry to resurrect a dead issue here, but it looks like https://pkgs.tailscale.com/stable/ubuntu/hirsute.list is 404ing for me again.

**Comment by swift13** [comment]
> Pushed: https://pkgs.tailscale.com/unstable/#ubuntu-hirsute

and this sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 458CA832957F5868
