### ISSUE TITLE
tailscale up doesn't let you remove exit nodes

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1777]
```
sudo tailscale up --exit-node=
'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; this command would change the value of flagless pref "ExitNodeID"
```

... Yes, it would. But that's what I'm trying to do.

**Comment by bradfitz** [comment]
The confusion here is between ExitNodeID and ExitNodeIP. There are special case hacks for the special case weirdness between those two prefs but apparently not enough.

**Comment by danderson** [comment]
There are no hacks at all that I could find for those two prefs. Adding some now.

**Comment by bradfitz** [comment]
Two special-cases for that flag:

```
        addPrefFlagMapping("exit-node", "ExitNodeIP", "ExitNodeIP")
....
                case "exit-node":
                        if !didExitNodeErr {
....

**Comment by danderson** [comment]
Yeah, there's a typo in that mapping, which is one issue. The other is EditPrefs not clearing exit node ID correctly. Changes incoming.
