### ISSUE TITLE
Tailscale DNS resolver interferes with NextCloud snap refresh

### ISSUE THREAD

**Issue by say4n** [tailscale/tailscale#1783]
**To Reproduce**

Running a `snap refresh` with any old version of the NextCloud snap installed causes it to fail with the error message: 
`Run pre-refresh hook of "nextcloud" snap if present (run hook "pre-refresh": Unable to refresh: apps.nextcloud.com seems to be down, please try again later).`

Removing the tailscale generated etc/resolv.conf (`apt remove tailscale`) solves the issue. Do note that pinging apps.nextcloud.com with tailscale installed succeeds.

**Expected behavior**
The snap should refresh without any issues to the latest version.

**Version information:**
 - Device: Hetzner VM
 - OS: Linux
 - OS version: Debian GNU/Linux 10 (buster)
 - Tailscale version: 1.6.0

**Additional context**
Source [tweet](https://twitter.com/thenamessayan/status/1385630459326042127).

**Comment by DentonGentry** [comment]
Odd. I can't immediately produce a problem with resolving apps.nextcloud.com on Debian 10, though it was just a quick check.

We're very close to a Tailscale 1.8 release which reworks a lot of the DNS handling for Linux platforms. I think we'd like to see if the problem remains in 1.8, and if so we'll dig into what is happening.

**Comment by apenwarr** [comment]
@say4n, if you don't mind trying our latest unstable tailscale build (1.7.x) from pkgs.tailscale.com, we believe it fixes this problem. Can you confirm?

**Comment by say4n** [comment]
Just tried it again with v1.7.403, the problem has been fixed! 🚀

**Comment by apenwarr** [comment]
Thanks for confirming!
