### ISSUE TITLE
DNS configuration fails with NetworkManager >=1.26.6

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1788]
A recent change to NetworkManager makes it ignore all DNS settings provided for "external" interfaces, i.e. interfaces that NetworkManager doesn't 100% manage itself. This unfortunately breaks tailscale's networkmanager DNS configurator, since we were relying on being able to push just DNS configuration into NM and have it propagate it outwards.

If NM >=1.26.6 is in use, our DNS management heuristic MUST NOT select it as the DNS management implementation. Fortunately, this should be okay, because the only reason we _had_ to use NetworkManager <1.26.6 was due to a NM bug in how it interacts with systemd-resolved, which forced us to push DNS configuration through NM and not to resolved directly. So, we should be able to bypass NM successfully if NM is recent-enough.

**Comment by DentonGentry** [comment]
NetworkManager is not getting a Christmas card from us this year.

**Comment by danderson** [comment]
The galling thing is... the fix is actually correct and very good. The new behavior is better than the old one, and results in an OS that allows pieces to interoperate better.

Just... now NetworkManager has split into two mutually exclusive timelines, and tailscale needs to support both :(

Should anyone wish to be entertained, my journey of discovery through DNS purgatory: https://twitter.com/dave_universetf/status/1385720122107588610
