### ISSUE TITLE
Node picked a different DERP server than did other nodes on the same LAN

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1789]
This happened today a bit before 2020-04-23 18:36 ET.

Steps:
- My nodes are all in Montreal, so nearest the nyc derp server.
- Upgrade tailscale to 1.7.357 on three nodes in this order: whirl-6 (macOS), glide (windows), flow (Linux)
- After upgrading whirl-6 but before upgrading the other two nodes, configure whirl-6 to use an exit node in California (dream).

I noticed that whirl-6 (macOS) in its `tailscale status`, said:

100.122.98.51   flow                 apenwarr@    linux   active; relay "dfw", tx 25693752 rx 1185000
100.93.73.114   glide                apenwarr@    windows active; direct 10.0.42.43:41641, tx 276 rx 220

I'll file a separate bug for the fact that the connection between whirl and flow is through a relay even though they're side by side on the LAN. I think that one is a problem with flow, not whirl.

For this bug, the oddity is that whirl's connection to flow is through relay "dfw" rather than "nyc". In contrast, `tailscale status` on flow says:

100.93.73.114   glide                apenwarr@    windows active; relay "nyc", tx 4148 rx 92
100.97.154.72   whirl-6              apenwarr@    macOS   active; relay "nyc", tx 3885116 rx 38759812

When there's asymmetric DERP routing, I'm not 100% sure whether a node prints the DERP server it sends to or the one it receives from. It looks like the routing is asymmetric in this case.

But it shouldn't be asymmetric: both nodes are in the same location. Maybe whirl has selected the wrong DERP server because "dfw" is the one closest to its exit node? If so, that's a bug.

**Comment by apenwarr** [comment]
Looking at the logs for whirl-6 in this example, it appears that several of my nodes ended up alternating between derp1 (nyc) and derp9 (dfw). netcheck shows them as my top two in latency, although nyc is still a clear winner:

```
	* DERP latency:
		- nyc: 37.5ms  (New York City)
		- dfw: 61.2ms  (Dallas)
```

But my exit node is actually closest to sfo, not dfw, so this is probably not exit node related. Thus, not a regression in v1.8.

**Comment by DentonGentry** [comment]
We're not going to be able to reconstruct what happened two years ago.
https://github.com/tailscale/tailscale/issues/6187 tracks a similar set of symptoms, we'll followup more there.
