### ISSUE TITLE
magicsock doesn't rebind IPv6 sockets

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1799]
Extracted from #1796, it looks like we may not be rebinding IPv6 on network change, which would likely cause some incorrect fallbacks to DERP or IPv4.

Waiting on @josharian to work out the rebinding stuff in general before fixing.

**Comment by bradfitz** [comment]
IIRC the omission of IPv6 from rebind was intentional at the time; I thought it didn't ever matter.

(Thinking being that it wasn't subject to NAT changes or something.)

But doesn't hurt to also do.
