### ISSUE TITLE
Ping recipient takes a long time to renegotiate after Down->Up cycle

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1826]
Version: 1.7.401

bugreports:
whirl: BUG-1b57f15d6fc0818cc8e1393b7683a2e44000267afc7de1d4eb8d3b23287eb4cf-20210430104439Z-a2467666a85288a3
glide: BUG-3a1dc7ae3aa0a06453a2175256eb29b70d7a48de53d9eeae8928bae6516fde2a-20210430104431Z-0cf846de29cec29c

Steps:
- Start pinging from whirl (macOS) to glide (Windows). Latency: <1ms.
- On whirl, click Disconnect
- On whirl, click Connect
- Notice that pings resume within a second or two. Latency: <1ms
- On glide, click Disconnect
- On glide, click Connect

Expected:
Pings resume within a second or two

Actual:
- Pings take at least 10 seconds to resume.
- After they resume, latency is >40ms and throughput is slow. This probably means DERP is in use.
- tcpdump on whirl indicates that every packet being sent to glide is going out *both* DERP and a direct UDP socket.
- `tailscale.exe status` on glide reports the connection to whirl as direct, or idle, even though the pings continue to flow.
- If I then ping glide from flow (Linux), suddenly the pings from whirl are fast again, and stay fast until we repeat the test.

Reverse direction:
Running the ping in the opposite direction, I see the same delay when I down/up the recipient and not when I down/up the sender. (Except that on Windows, network reconfigs always take ~4 seconds, so toggling it as the sender doesn't recover quiet as fast.) In this direction however, it doesn't seem to keep using DERP for a long time.

I haven't checked yet if this is a regression from v1.6.

cc: @josharian, who has been playing with magicsock code lately.

**Comment by apenwarr** [comment]
I'm going to check this in v1.6.0 and see if it's a 1.8.0 regression or not. If not, this shouldn't block v1.8.0.

**Comment by apenwarr** [comment]
Reproduces easily on v1.6.0. Not a blocker for v1.8.0, though it's fishy enough that I'd argue it belongs in a v1.8.x patch.

**Comment by llewxam-kache** [comment]
```
tailscale --version
1.8.7
  tailscale commit: e1571ed7e0e84aed16f267be24fe408150109af6
  other commit: 2f595b1b68943e7c7670bb9c10147d81d034f6fd
  go version: go1.16.4-ts1b677aa
```
I believe we are experiencing some of this as well, and is causing some headaches for the impatient:
Local ping, Tailscale off
```
PING fileServer.company.co(192.168.1.143): 56 data bytes
64 bytes from 192.168.1.143: icmp_seq=0 ttl=64 time=1.193 ms
64 bytes from 192.168.1.143: icmp_seq=1 ttl=64 time=2.176 ms
64 bytes from 192.168.1.143: icmp_seq=2 ttl=64 time=4.138 ms
64 bytes from 192.168.1.143: icmp_seq=3 ttl=64 time=4.738 ms
64 bytes from 192.168.1.143: icmp_seq=4 ttl=64 time=2.310 ms
64 bytes from 192.168.1.143: icmp_seq=5 ttl=64 time=40.550 ms
64 bytes from 192.168.1.143: icmp_seq=6 ttl=64 time=82.896 ms
64 bytes from 192.168.1.143: icmp_seq=7 ttl=64 time=136.046 ms
64 bytes from 192.168.1.143: icmp_seq=8 ttl=64 time=10.767 ms
64 bytes from 192.168.1.143: icmp_seq=9 ttl=64 time=2.547 ms
64 bytes from 192.168.1.143: icmp_seq=10 ttl=64 time=2.980 ms
64 bytes from 192.168.1.143: icmp_seq=11 ttl=64 time=2.271 ms
^C
```

Local ping Tailscale on:
```
PING fileServer.company.co.beta.tailscale.net (100.82.175.42): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
64 bytes from 100.82.175.42: icmp_seq=0 ttl=64 time=5042.111 ms
64 bytes from 100.82.175.42: icmp_seq=1 ttl=64 time=4037.922 ms
64 bytes from 100.82.175.42: icmp_seq=2 ttl=64 time=3033.672 ms
64 bytes from 100.82.175.42: icmp_seq=3 ttl=64 time=2029.193 ms
64 bytes from 100.82.175.42: icmp_seq=4 ttl=64 time=1024.875 ms
64 bytes from 100.82.175.42: icmp_seq=5 ttl=64 time=19.933 ms
64 bytes from 100.82.175.42: icmp_seq=6 ttl=64 time=3.672 ms
64 bytes from 100.82.175.42: icmp_seq=7 ttl=64 time=4.817 ms
64 bytes from 100.82.175.42: icmp_seq=8 ttl=64 time=4.374 ms
64 bytes from 100.82.175.42: icmp_seq=9 ttl=64 time=3.822 ms
64 bytes from 100.82.175.42: icmp_seq=10 ttl=64 time=6.454 ms
64 bytes from 100.82.175.42: icmp_seq=11 ttl=64 time=23.924 ms
64 bytes from 100.82.175.42: icmp_seq=12 ttl=64 time=63.403 ms
^C
```
Local ping again leaving Tailscale on:
```
PING fileServer.company.co.beta.tailscale.net (100.82.175.42): 56 data bytes
64 bytes from 100.82.175.42: icmp_seq=0 ttl=64 time=6.605 ms
64 bytes from 100.82.175.42: icmp_seq=1 ttl=64 time=16.997 ms
64 bytes from 100.82.175.42: icmp_seq=2 ttl=64 time=4.431 ms
64 bytes from 100.82.175.42: icmp_seq=3 ttl=64 time=16.435 ms
64 bytes from 100.82.175.42: icmp_seq=4 ttl=64 time=94.521 ms
64 bytes from 100.82.175.42: icmp_seq=5 ttl=64 time=3.777 ms
64 bytes from 100.82.175.42: icmp_seq=6 ttl=64 time=5.097 ms
64 bytes from 100.82.175.42: icmp_seq=7 ttl=64 time=3.497 ms
64 bytes from 100.82.175.42: icmp_seq=8 ttl=64 time=2.871 ms
64 bytes from 100.82.175.42: icmp_seq=9 ttl=64 time=3.755 ms
64 bytes from 100.82.175.42: icmp_seq=10 ttl=64 time=3.787 ms
64 bytes from 100.82.175.42: icmp_seq=11 ttl=64 time=149.526 ms
64 bytes from 100.82.175.42: icmp_seq=12 ttl=64 time=102.220 ms
64 bytes from 100.82.175.42: icmp_seq=13 ttl=64 time=3.226 ms
64 bytes from 100.82.175.42: icmp_seq=14 ttl=64 time=17.037 ms
64 bytes from 100.82.175.42: icmp_seq=15 ttl=64 time=67.912 ms
64 bytes from 100.82.175.42: icmp_seq=16 ttl=64 time=2.920 ms
64 bytes from 100.82.175.42: icmp_seq=17 ttl=64 time=4.807 ms
^C
```
This happens for many devices, and on my MacOS device, does adhere to the down/up delay; after some ping is returned, usually ping times stay low(er), but not as low as they should be across a wifi network. It feels like this became an issue midway last week (6/16/21), and had not been noticed before then.
