### ISSUE TITLE
CentOS7 Install Failed (Repo Issue?)

### ISSUE THREAD

**Issue by lemonsz15** [tailscale/tailscale#1827]
I've got this error msg while installing tailscale in CentOS7.

Please advise.

> [root@localhost ~]# sudo yum install tailscale
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                                     | 6.6 kB  00:00:00     
 * base: ossm.utm.my
 * epel: mirrors.thzhost.com
 * extras: ossm.utm.my
 * updates: ossm.utm.my
base                                                                                                                                     | 3.6 kB  00:00:00     
extras                                                                                                                                   | 2.9 kB  00:00:00     
https://pkgs.tailscale.com/stable/centos/7/tailscale.rep/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

>https://wiki.centos.org/yum-errors

>If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

 >One of the configured repositories failed (added from: https://pkgs.tailscale.com/stable/centos/7/tailscale.rep),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=pkgs.tailscale.com_stable_centos_7_tailscale.rep ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable pkgs.tailscale.com_stable_centos_7_tailscale.rep
        or
            subscription-manager repos --disable=pkgs.tailscale.com_stable_centos_7_tailscale.rep

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=pkgs.tailscale.com_stable_centos_7_tailscale.rep.skip_if_unavailable=true

> failure: repodata/repomd.xml from pkgs.tailscale.com_stable_centos_7_tailscale.rep: [Errno 256] No more mirrors to try.
https://pkgs.tailscale.com/stable/centos/7/tailscale.rep/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by danderson** [comment]
How did you add the tailscale repo as a source? Please share exactly what commands you ran. At first glance, it's looking like yum is asking for completely the wrong URL, so we need to figure out why that is and which part of our docs need fixing.

**Comment by DentonGentry** [comment]
If there are no further updates, we will close this issue in the next bug scrub.

**Comment by DentonGentry** [comment]
Timed out.
