### ISSUE TITLE
windows: NotepadURLs prevents CLI "up" usage on Windows

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1830]
If a Windows user shift-right-clicks and enables the "Use Notepad for URLs" debug option, that sets the NotepadURLs pref.

The `tailscale up` CLI command doesn't know about that pref, so it fails with:

> 'tailscale up' without --reset requires all preferences with changing values to be explicitly mentioned; this command would change the value of flagless pref "NotepadURLs"

Probably harmless. Few people use that option (it's mostly for Windows 7 testing by us) and few people use the CLI on Windows. The intersection is small.

But tracking bug so I have a URL to reference.

**Comment by apenwarr** [comment]
NotepadURLs is not just for Windows 7. It's used by users of even the newest Windows Server (which has its default browser set to block everything by default) and various users of VMs.

However, I agree that the intersection with CLI users is pretty small.

Does https://github.com/tailscale/tailscale/pull/1834 fix this anyhow?

**Comment by bradfitz** [comment]
#1834 does not. That's about when a setting that only applies to another OS changes. This is about a Windows setting changing on Windows.

**Comment by DentonGentry** [comment]
We fixed this somewhere along the way. With the debug setting to use Notepad for URLs set, I'm able to change other options using the CLI:

```
C:\Users\dgentry>tailscale up

C:\Users\dgentry>tailscale up --exit-node=dgentry-tor1 --exit-node-allow-lan-access

C:\Users\dgentry>tailscale up --exit-node= --exit-node-allow-lan-access
--exit-node-allow-lan-access can only be used with --exit-node

C:\Users\dgentry>tailscale up --exit-node= --exit-node-allow-lan-access=false

C:\Users\dgentry>
```
