### ISSUE TITLE
Detect and report lack of support for WSL1

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1873]
While setting up a dev environment on Windows+WSL, we hit the issue that tailscaled doesn't work on WSL1, due to the halfway implementation of the network stack emulation. It's unlikely we'll ever work very well on WSL1 (whereas we work fine on WSL2), but the errors were all quite obscure, and boiled down to SO_BINDTODEVICE not being implemented correctly.

We should add WSL1 to our existing distro detection logic, and fail with a more friendly error pointing people at WSL2.

**Comment by ramyfication** [comment]
In case it makes keyword searches easier, here's a snippet from the log:

link state: interfaces.State{defaultRoute= ifs={eth0:[192.168.0.7/24] eth3:[172.27.144.1/20]} v4=true v6global=false}
magicsock: unable to bind udp4 port 0: listen udp4 :0: setting SO_BINDTODEVICE: protocol not available
wgengine.NewUserspaceEngine(tun "userspace-networking") error: wgengine: magicsock: initialBind IPv4 failed: failed to bind any ports (tried [0])

Quick steps to check WSL version (& switch between the two) are in https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by kellytrinh** [comment]
Is this bug starting from 1.8 and affect all functionality?  Coz tailscale and WSL1 work fine for me.

**Comment by DentonGentry** [comment]
I don't really expect to do more work on WSL1 at this point, our response for literally any WSL1 issue would be to ask to update to WSL2. I'm not even sure we can set up a WSL1 test environment to test this proposed error message at this point.

Barring further comment, we'll expect to close this during the next regular bug scrub.
