### ISSUE TITLE
Sign Fedora packages in addition to repo metadata

### ISSUE THREAD

**Issue by gleb-jiji** [tailscale/tailscale#1882]
Is there a reason Fedora packages aren't being signed? (The repository metadata is signed, `repo_gpgcheck=1`, only the packages aren't, with `gpgcheck=0`).

Qubes OS has recently started requiring RPM signatures in its Fedora templates. See [QSB-067](https://www.qubes-os.org/news/2021/03/19/qsb-067/), https://github.com/QubesOS/qubes-core-admin-linux/commit/a94ec97fe412afc72e4817bf15273db9dee07a3f.

This makes it difficult to install the Tailscale package:
```
Package tailscale_1.8.0_x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

As noted in the QSB ("Side effects"), this can't be overridden with `--nogpgcheck`, which is not an appropriate workaround anyway.

Please consider signing the packages as well.

**Comment by danderson** [comment]
Thanks for the report. At the time we made the repository generator, it was easier to sign the metadata root file (which is a hash tree that implicitly verifies the packages as well), but in the next few weeks we're rewriting that code to sign individual packages as well.

**Comment by danderson** [comment]
In more detail: the rpm tools are a bit cumbersome to use in build automation, since they mutate the package in-place which breaks a bunch of build dependency logic. Since the repo signature verifies the package hashes, I went with a simpler codebase (one GPG signature after generating the hash tree, no in-place mutation of files), and skipped package signing.

In the next iteration of our package serving infrastructure, we'll provide signatures for everything.

**Comment by gleb-jiji** [comment]
Thanks for the detailed explanation. Insight into packaging issues and tradeoffs is appreciated!

**Comment by goshansp** [comment]
It seems that `1.26.2` ist still not signed. Is there an ETA for signing of Fedora packages?

**Comment by DentonGentry** [comment]
I promise we will update this bug when work on it progresses.

**Comment by eugene1g** [comment]
I understand this is a relatively low priority, and don't want to push for a fix. 
Just to add another dimension on why this matters beyond being an administrative nuisance - infosec audits for PCI DSS  require all repositories to have `gpgcheck` enabled. If Tailscale repository does not support that, automated scanners will register this as a failure and I need to discuss Tailscale & the situation with the auditors. 

The failure looks something like this -
<img width="600" alt="CleanShot 2022-09-17 at 10 05 53@2x" src="https://user-images.githubusercontent.com/147496/190861371-3bbf87a3-d635-4f6f-82e6-18b38c44cee9.png">

This failure is just security theater and has no impact on the actual risk, but if Tailscale can do anything to reduce the number of times we have to "discuss" it with auditors it would be much appreciated 🙏

**Comment by tartansandal** [comment]
Has there been any progress or decisions made about this over the past year?  🙏

**Comment by DentonGentry** [comment]
We understand that this is important for a subset of deployments, and is something we expect to address but have not begun development for.

**Comment by GoetzGoerisch** [comment]
@DentonGentry having tailscale installed on a regular Fedora Workstation 37 as per https://tailscale.com/download/
The missing package signing breaks auto-upgrades with Gnome Software.

Sorry for the screenshot in german:

Download unsigned software?

![Bildschirmfoto vom 2023-01-26 10-32-34](https://user-images.githubusercontent.com/47734341/214808493-c6902a6b-6507-4248-bf78-91a894542102.png)

**Comment by awly** [comment]
Tailscale RPMs are now signed on the [unstable track](https://pkgs.tailscale.com/unstable/).
Stable track will be signed starting with next release (1.48).

I will keep this ticket open until the next stable release, mainly to remember to set `gpgcheck=1` there.

**Comment by awly** [comment]
Reopening this because we had to disable `gpgcheck` in the repo because 1.48.0 release was withdrawn for Linux.
Also, we might need to repackage all old RPM packages, with signing, because you can't easily sign them retroactively?

**Comment by awly** [comment]
`gpgcheck` is enabled again on stable RPM repo.

All releases since 1.48.1 are signed. Older releases are not and their installation will fail.
Please report if you get installation failures due to signature validation failure.
You can temporarily work around that by setting changing `gpgcheck=1` to `gpgcheck=0` in `/etc/yum.repos.d/tailscale.repo`, but we encourage you to update to newer versions.
