### ISSUE TITLE
tailscale up doesn't wait for ipn.Running

### ISSUE THREAD

**Issue by tavianator** [tailscale/tailscale#1889]
I have a GitHub Actions runner that recently started failing once it started using 1.8.0.  After looking at the [logs](https://github.com/tavianator/bfs/runs/2539062744?check_suite_focus=true), it seems like tailscale hasn't finished connecting by the time it tries to use it.  Is there a way to make `tailscale up` wait for the connection to finish?  Or is there another command that will wait?

**Comment by DentonGentry** [comment]
tailscale up does block until the network connection itself is up, but it is quite possible that the timing of when the DNS servers are configured and /etc/resolv.conf updated has changed in 1.8. There have been a number of changes in the DNS implementation for the 1.8 release. That could lead to the behavior seen of a hostname not resolving immediately after "tailscale up" completes.

**Comment by tavianator** [comment]
I tried with hardcoded IPs too, but it times out: https://github.com/tavianator/bfs/runs/2538977411?check_suite_focus=true

On the other hand, running `tailscale status; tailscale netcheck` first made it work: https://github.com/tavianator/bfs/runs/2539035192?check_suite_focus=true

**Comment by DentonGentry** [comment]
Ok, that's odd.

**Comment by tavianator** [comment]
Running `sudo tailscale up && ping 100...` locally works fine.  The gh actions runner is doing `tailscale up --authkey=...` though.

**Comment by tavianator** [comment]
My latest attempt to work around this ran into "unexpected state: Starting" from `tailscale status`: https://github.com/tavianator/bfs/runs/2605558790?check_suite_focus=true

**Comment by tavianator** [comment]
So I see here that `tailscale up` seems to wait for either `Starting` or `Running`: https://github.com/tailscale/tailscale/blob/85df1b0fa7d565f5b3deddd825fd08eafbd71632/cmd/tailscale/cli/up.go#L383-L393

Should it be changed to just wait for `Running`?  If that's the right fix I can send a PR

**Comment by calderonth** [comment]
I can confirm I'm seeing the same issue when running from a Github action workflow, used to work with `1.6.0` now not working.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/2763
Fix will appear in Tailscale 1.16.
