### ISSUE TITLE
Windows: Unable to start Tailscale 1.6 and 1.8 after installation.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1890]
After installation Tailscale 1.6 does not work. even after restarting the service or re-installation or reboot do not fix the issue.

---------------------------
Tailscale Error
---------------------------
Tailscale backend error:

wgengine.NewUserspaceEngine: Error creating interface: Cannot create a file when that file already exists.

logid: b6*********************
---------------------------
OK   
---------------------------

![image](https://user-images.githubusercontent.com/75628398/117665723-24197100-b171-11eb-8e3a-33cdfd7d1bb5.png)

Workaround: 

1. remove Tailscale with Add/Remove Programs....
2. deleted the two Tailscale folders in Windows App folders
3. removed my device from Tailscale admin portal
4. uninstalled the Wintun device from the Windows Device manager. (https://www.online-tech-tips.com/computer-tips/unable-delete-network-adapter-windows-10/ )
5. rebooted machine
6. installed Tailscale and authenticated

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_34n0x)

**Comment by dbensmith** [comment]
Version 1.8.3 fixed my issues across multiple Windows systems all exhibiting the same behaviour. Thanks!

**Comment by apenwarr** [comment]
Fixed in 1.8.3.
