### ISSUE TITLE
Add API access to make it easier to monitor/notify when users need to upgrade their devices

### ISSUE THREAD

**Issue by dfcarney** [tailscale/tailscale#1894]
Knowing which users/devices are active would also be helpful. Metrics such as the following would help:

- Tailscale version
- Last seen timestamp
- Bytes rx/tx

**Comment by dfcarney** [comment]
A customer asked for this. They review things in the admin console now and then, but would really like API access to automate things further.

Perhaps we should just skip the API part and add an admin feature to prompt/force users to ugprade their Tailscale clients.

**Comment by crockpotveggies** [comment]
App Store doesn't seem to update the client in a timely manner. An admin feature (and/or a feature built in to the client) would make more sense to prompt/force the user to upgrade. Just experienced a related issue this morning.

**Comment by rAtKeyboard** [comment]
This ticket is mostly handled at this point. The only thing left is bytes rx/tx, everything else shows in the API.

**Comment by DentonGentry** [comment]
The client software does not currently communicate tx/rx byte counts to the coordination server at all, so it isn't a matter of just adding it to the API. Is there a specific use for byte counts in mind?

**Comment by DentonGentry** [comment]
I think this is as done as it is going to get. TX/RX byte counts through the API is in conflict with battery life concerns about clients communicating more often with the coordination server.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Closing during bug scrub
