### ISSUE TITLE
Incorrect $env:PATH when installed in non-default directory

### ISSUE THREAD

**Issue by ato2** [tailscale/tailscale#1904]
When I change the defult install dir to other than default "C:\Program Files (x86)\Tailscale IPN"
installer still appends default value do $env:PATH.

**Comment by DentonGentry** [comment]
We're currently considering packaging the installer as an MSI instead of NSIS, and the tool we'd use to build MSI would handle this cae.

**Comment by DentonGentry** [comment]
Looking through the NSIS installer... I don't even see where we add to the PATH at all. We may be relying on a default behavior.

**Comment by bradfitz** [comment]
> Looking through the NSIS installer... I don't even see where we add to the PATH at all. We may be relying on a default behavior.

It's not a default behavior. It required code: `func updatePath` originally from https://github.com/tailscale/corp/commit/39b7f78e1b752966a9fe9e1cd7c6c1bb8b8bb2f0 which indeed hard-codes `";%PROGRAMFILES(X86)%\Tailscale IPN"` etc. We should use `os.Executable`'s dir probably.

**Comment by DentonGentry** [comment]
This is fixed in the MSI installer. I installed the app in `C:\Program Files (x86)\Tailscale IPN b1904`, and it set %PATH% correctly for `cmd.exe` to find it.

```
C:\Users\dgentry> where tailscale
C:\Program Files (x86)\Tailscale IPN b1904\tailscale.exe
```
