### ISSUE TITLE
Tailscale 1.8 client talking to tailscaled 1.6 gets mysterious JSON decoding error

### ISSUE THREAD

**Issue by pmaene** [tailscale/tailscale#1905]
First off, I wanted to thank you again for the wonderful service! After the following the simple steps documented by https://github.com/jamesog/tailscale-edgeos, I noticed some `systemd` errors related to Tailscale's service file in my ER-X's logs. I believe this might be the result of a relatively recent change, because v1.6 did come up. More specifically, these are the related log lines.

```
systemd[1]: [/config/tailscale/systemd/tailscaled.service:17] Unknown lvalue 'StateDirectory' in section 'Service'
systemd[1]: [/config/tailscale/systemd/tailscaled.service:18] Unknown lvalue 'StateDirectoryMode' in section 'Service'
systemd[1]: [/config/tailscale/systemd/tailscaled.service:19] Unknown lvalue 'CacheDirectory' in section 'Service'
systemd[1]: [/config/tailscale/systemd/tailscaled.service:20] Unknown lvalue 'CacheDirectoryMode' in section 'Service'
```

Not sure if this is helpful, but `systemctl --version` outputs the following on an ER-X running the latest firmware. Let me know if you need any other information!

```
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

Somewhat related to this issue, the error returned by `tailscale up` when `tailscaled` is not running, was quite confusing to me at first.

```
can't fetch status from tailscaled: invalid character 'a' in literal true (expecting 'r')
```

**Comment by danderson** [comment]
Hmm, those directives have been there since at least 1.4, I think. And usually, systemd ignores unknown lvalues, so this shouldn't be a problem... What does `systemctl status tailscaled` say? I'm wondering if tailscaled is starting, but is crashing for some other reason related to 1.8 changes.

**Comment by pmaene** [comment]
Should've thought about looking at the actual service status, sorry about that! `systemctl status tailscaled` reported that tailscaled was up, but I noticed it had been running for a longer time than that had passed since the update. I'd simply forgotten to restart the service while updating. After doing so, everything came up happily afterwards!

I'm not sure if this could be caught by the CLI to show a prettier error? The structure of the messages sent between the CLI and daemon probably changes between versions to allow for new features?

**Comment by danderson** [comment]
Phew, that's good news!

I agree that our error should be better when versions mismatch. I'll update this bug to be about that.

**Comment by pmaene** [comment]
Thanks for your quick replies and for looking into improving the error message!
