### ISSUE TITLE
minor taildrop iOS gui issue

### ISSUE THREAD

**Issue by dcoombs** [tailscale/tailscale#1906]
Taildrop is glorious, of course.  Minor issue: after sending a file in iOS (on an iPhone 8), the confirmation checkbox is half off the edge of my screen.  I've just taildropped myself a screenshot that shows it, attached.

![IMG_3300](https://user-images.githubusercontent.com/44320/117838576-75486400-b248-11eb-88fe-c1ec92f2e466.PNG)

**Comment by soniaappasamy** [comment]
@dcoombs thanks for reporting, we'll get that fixed up! Glad you can at least partially see it 😆
