### ISSUE TITLE
wgengine/wgcfg: optimize FromUAPI

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#1912]
Lots of allocations, generally heavy-weight, and we use it a lot.

**Comment by DentonGentry** [comment]
Yesterday in https://github.com/tailscale/tailscale/pull/5451 we said,
_"The idea at the time was that UAPI was slow but we could probably make it faster, which we did, over a number of rounds. But I think we made it about as fast as we can."_

Closing this as completed.
