### ISSUE TITLE
app crashing on android AOSP

### ISSUE THREAD

**Issue by GlidLov** [tailscale/tailscale#1915]
Hi,

i'm trying to run tailscale app on an appliance based on LG Optimus (device is "herelink" remote controller, running android 7) which does not have play store installed, so i pull APK from my phone then i move apk onto it and install it.

app opens on the welcome screen then go to login page where i can choose a google auth or "other". If i tap on google, it load for a second then stays there, while tapping on "other" crashes app.

i tried 1.4.5 , 1.6.0 and 1.6.2  with same result.

Strange thing is that with another device, same model but older, it worked OK. I have many other newer (1-2 months old) devices and it crashes on everyone. I dunno if there's some "hidden" setting which may fix this, maybe in the "developer options" menu?

**Comment by DentonGentry** [comment]
A device running Android 7 with no Play Store isn't something we'd be able to truly support, however the builds are made available on https://f-droid.org/en/packages/com.tailscale.ipn/ with no Google Play Services dependency and may work better on this kind of device.

**Comment by GlidLov** [comment]
Thanks Denton, i tried the APK from F-droid, and it's still crashing just after the login page, but it's slightly different from the ones i tried, it shows a single button "sign in" rather than two, with no logo or whatsoever. I tap it and it crashes. I'm suspecting some auth lib underneath app are missing.. So i'm trying to find a play service apk and install it

**Comment by DentonGentry** [comment]
When using the F-Droid app, choosing the "Login with other" button will open a browser to log into an identity provider. Browser login is more likely to work on a device which lacks Google Play Services. You'll need to make sure a suitable browser is installed.

**Comment by DentonGentry** [comment]
I'll assume that "Login with other" worked, as it redirects to a browser to handle login.
Users have reported success with the Puffin browser.
https://play.google.com/store/apps/details?id=com.cloudmosa.puffinFree

Please reopen the bug if there is still an issue.
