### ISSUE TITLE
Assign multiple IPs to a single node

### ISSUE THREAD

**Issue by ItalyPaleAle** [tailscale/tailscale#1917]
(Forgive me if the option exists already, I couldn't find it)

It would be great if Tailscale could assign multiple static IPs to the same host. This is particularly helpful for exposing multiple services running on the same port.

For example, in my network (not using Tailscale), I have a server which has a single network interface and multiple IPs, manually added on `/etc/network/interfaces`:

```sh
# ip addr show eno1
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.1.1.5/16 brd 10.1.255.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet 10.1.1.6/16 brd 10.1.255.255 scope global secondary eno1:0
       valid_lft forever preferred_lft forever
    inet 10.1.1.7/16 brd 10.1.255.255 scope global secondary eno1:1
       valid_lft forever preferred_lft forever
```

Thanks to this, I can have multiple apps (in my case running in Docker) that are listening on port 443, and they are bound to different IPs. So, `https://10.1.1.6/` brings me to one app, and `https://10.1.1.7/` to another one.

Would it be possible to do something like this with Tailscale?

**Comment by ItalyPaleAle** [comment]
Thanks. #713 is about a different issue, having multiple users share the same box or having a node accessing multiple Tailscale "networks". 

My problem is more about having multiple services exposed by a single node, creating "virtual interfaces" such as what one would do on bare metal. I am aware that I could run multiple Tailscale daemons using Docker, but that makes the setup significantly more complicate to set up and to manage.

Yes I'm aware that there are alternatives, but they don't work for every app. As it happens, I am working with an app that I need deployed twice, both need to use the same port, and it's not HTTP-based so layer-7 proxies (hostname-based) can't be used.

Why are you talking about IP exhaustion? In the /10 range there are over 4 million IPs, I don't think it's a very common thing for many individual Tailscale users to need more than that? (Even for a large organization, a /10 block is a lot of nodes!)

**Comment by ItalyPaleAle** [comment]
I just realized that in Tailscale, IPs are globally unique. Now I understand your concerns about contributing to IP exhaustion... A /10 is not _that_ big anymore :)

**Comment by DentonGentry** [comment]
I'm going to close this as I don't think we'd provide a way to add arbitrary numbers of IPv4 addresses, as you note they are a globally shared pool.

We might do so for IPv6 addresses, but should open a new feature request when there is a more solid use-case of what would be needed.

**Comment by ItalyPaleAle** [comment]
@DentonGentry given that now Tailscale doesn't use a globally-shared pool of IPs anymore, any chance this could be reconsidered?

**Comment by Hypnotist1148** [comment]
Agree with @ItalyPaleAle would be really nice and usefull especially for running k0s! @DentonGentry

**Comment by patricklucas** [comment]
I'm a new Tailscale user and got stung by this. I have a server that runs both microk8s with ingress controller and Nginx outside of K8s. Not supporting multiple IPs makes it quite difficult to terminate TLS in both places on the same machine which is otherwise very easy.

Edit: I worked around this by disabling the microk8s ingress controller and using NodePort services instead, terminating TLS with Nginx and proxying to them, but being able to use the ingress controller would certainly be more convenient.

**Comment by dolceAlka** [comment]
you can do this in a way by running an l3 service on services and then assigning that ip to tailscale0 so it's bindable
