### ISSUE TITLE
Windows OS: Error occurred after upgrade from 1.6 to 1.8.3 on windows server environment.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1920]
Customer upgraded environment on SCCM or other windows server and getting following error on startup failure,

A fatal error occurred while creating a TLS client credential. The internal error state is 10013. (source Schannel)
Initialization failed because the driver device could not be created. Use the string "0000000001003200000002000000000000000000000000000000**********" to identify the interface for which initialization failed. It represents the MAC address of the failed interface or the  Globally Unique Interface Identifier (GUID) if NetBT was unable to map from GUID to MAC address. If neither the MAC address nor the GUID was available, the string represents a cluster device name. (source NetBT)
The server could not bind to the transport \Device\NetBT_Tcpip_{************************} because another computer on the network has the same name.  The server could not start. (source Server)

![untitled (1)](https://user-images.githubusercontent.com/75628398/118147133-46afc200-b3dd-11eb-8506-49e5da041155.png)

When error appears it unable to get bug report too,
![image](https://user-images.githubusercontent.com/75628398/118143737-aad08700-b3d9-11eb-8d80-0de519c69c16.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_357td)

Platform: Windows server 2016

**Comment by darshinimashar** [comment]
Bugreport marker created:
BUG-bbe2e1538db7dd00aad95b72d54ff18689e623f334ef4af8881d7afa45a81950-20210513142502Z-226f488cc0c259e4

From another customer from the front conversation: https://forum.tailscale.com/t/tailscale-stops-working-after-1-8-0-3-update-windows-server-rds-issue-mutliple-users/635

**Comment by darshinimashar** [comment]
One more customer reported the issue,https://forum.tailscale.com/t/windows-server-2016-and-2019-rds/318/11.

**Comment by evilhamsterman** [comment]
I get the "Failed to connect to Tailscale service." error on Windows 10 whenever we do a fast user switch from my account to my wife's account. Tailscale will be running fine in my account but when she switches to her account she will get repeated alerts from Tailscale and I have to end up killing the service and all Tailscale processes to clear it.

**Comment by a-sorochak** [comment]
I have the same issue on Windows 10 after Tailscale update from 1.6.0 to 1.8.3. 
Tailscale was installed with "Run unattended" option and when any other Windows user logs in, he sees multiple error messages "Failed to connect to Tailscale service". Tailscaled is running meanwhile. 

Fragment of Tailscale's log
`2021-05-16T10:07:02.223+03:00: panic: runtime error: invalid memory address or nil pointer dereference
2021-05-16T10:07:02.223+03:00: [signal 0xc0000005 code=0x0 addr=0x40 pc=0x129ee2b]
2021-05-16T10:07:02.223+03:00: 
2021-05-16T10:07:02.223+03:00: goroutine 502 [running]:
2021-05-16T10:07:02.223+03:00: tailscale.com/ipn.NewBackendServer(0xc0000888a0, 0x0, 0x0, 0xc0000aa078, 0x173cf30)
2021-05-16T10:07:02.223+03:00: 	tailscale.com@v0.0.0-00010101000000-000000000000/ipn/message.go:108 +0xcb
2021-05-16T10:07:02.223+03:00: tailscale.com/ipn/ipnserver.(*server).serveConn(0xc0001867e0, 0x1737b30, 0xc000036040, 0x173cf30, 0xc0001ce018, 0xc0000888a0)
2021-05-16T10:07:02.223+03:00: 	tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnserver/server.go:255 +0x330
2021-05-16T10:07:02.223+03:00: created by tailscale.com/ipn/ipnserver.Run
2021-05-16T10:07:02.223+03:00: 	tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnserver/server.go:729 +0x917
2021-05-16T10:07:02.304+03:00: BabysitProc: backoff: 7 msec
2021-05-16T10:07:02.476+03:00: 2021/05/16 10:07:02 Program starting: v1.8.3-td0e86b08c-g03346d1fb: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe", "/subproc", "32167d78dac5e623d6ddab1526511cda953abd4a92514cdaa714c2a817ac7db0"}
2021-05`

I have found workaround by removing `tailscale-ipn.lnk` from common Windows startup directory (`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`).

**Comment by crawshaw** [comment]
There are several code paths in `ipn/ipnserver/server.go` that are wrong. We are calling `NewBackendServer` with a nil `b Backend` and a set `sendNotifyMsg` parameter, which immediately trips over this code:

```
        if sendNotifyMsg != nil {
                b.SetNotifyCallback(bs.send)
        }
```

That causes the panic above.

**Comment by crawshaw** [comment]
OK the panic is in error cases, and is easily fixed. Unfortunately, fixing it doesn't necessarily fix the underlying problem.

**Comment by darshinimashar** [comment]
This should resolve:  https://github.com/tailscale/tailscale/issues/1953 & https://github.com/tailscale/tailscale/pull/1775

**Comment by bradfitz** [comment]
@darshinimashar, did you mean #1775 or https://github.com/tailscale/corp/issues/1775?

**Comment by bradfitz** [comment]
Emailed customer, but I think this is done.
