### ISSUE TITLE
cmd/tailscale: add ip -1?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1921]
As of Tailscale 1.8 we have:

`tailscale ip` (show all Tailscale IPs)
`tailscale ip -4` (show all Tailscale IPv4 addresses)
`tailscale ip -6` (show all Tailscale IPv6 addresses)

But there's no portable way to get a single IP. The Unix-y way of course is `$(tailscale ip | head -1)`. That doesn't help Windows users and OS-specific docs makes docs harder to write.

I propose we add a `-1` flag that returns one IP, which can be optionally combined with `-4` or `-6`.

Thoughts?

**Comment by rosszurowski** [comment]
Since getting a single IP seems to be the more common workflow, what if we inverted the approach? By default, `tailscale ip` returns a single address (preferring IPv4 to IPv6). If you want more than one, use `tailscale ip --all` or something.

**Comment by josharian** [comment]
> we just released it in v1.8, I don't suspect too many people have set up scripts that rely on it

I think we've missed the window for that. :P
