### ISSUE TITLE
Connect Existing IP

### ISSUE THREAD

**Issue by IzumiSena** [tailscale/tailscale#1926]
Hello I Was Thinking If This Feature can be implemented! 

Suppose I am using my old machine as a server and i shared that machine name to multiple people via "share machine" feature.... 

but now i want to change my server and setup everything from start! 
but at this moment if i download and type `tailscale up` new server get new machine name and new ip.... and i have to invite in this new machine to my friends and family again.... 

so i want a way to connect existing IP or machine name ...like Sample if i type `tailscale up -c 100.101.102.103` whice will connect to a old machine name which ip was 100.101.102.103!
and those people who using my old machine by shared feature don't need to do anything and access server without issue

Sorry for my bad english...

**Comment by DentonGentry** [comment]
For a Linux host, you can copy the /var/lib/tailscale/tailscaled.state file from the old machine to the new machine. Please delete it from the old machine, if two nodes both try to use the same address then neither will work very well.

**Comment by IzumiSena** [comment]
> For a Linux host, you can copy the /var/lib/tailscale/tailscaled.state file from the old machine to the new machine. Please delete it from the old machine, if two nodes both try to use the same address then neither will work very well.

So first i have to download tailscale on new device then copy and paste /var/lib/tailscale/tailscaled.state file from old device to new device and uninstall tailscale from old device and then run "sudo tailscale up" on new device and done?

**Comment by DentonGentry** [comment]
Yes.

You don't have to completely uninstall Tailscale on the old device, but please move /var/lib/tailscale/tailscaled.state to a different filename or delete it. If the old device powers on and connects to Tailscale while the new device is also active, they'll fight over the IP address and neither will work well.

**Comment by Oujiii** [comment]
Just passing by to thank you for that. I am about to reprovision a node and using the same IP is awesome. Thank you!

**Comment by IzumiSena** [comment]
> Just passing by to thank you for that. I am about to reprovision a node and using the same IP is awesome. Thank you!
> 
> I have a script that automatically joins my machines to the network, so i should run it normall, do `sudo tailscale down`, change the file and then up and it should identify the node?

i did that but its not working

**Comment by IzumiSena** [comment]
> Yes.
> 
> You don't have to completely uninstall Tailscale on the old device, but please move /var/lib/tailscale/tailscaled.state to a different filename or delete it. If the old device powers on and connects to Tailscale while the new device is also active, they'll fight over the IP address and neither will work well.

not working in my debian buster!

**Comment by Oujiii** [comment]
Did not work for me either, not sure if you have to do it BEFORE doing  `sudo tailscale up` which I didn't because my script requires me to joithe network upon running. Either way, I just coped with a new IP. Might try to do on a new node I will reprovision later, but without joining first.

**Comment by IzumiSena** [comment]
> Did not work for me either, not sure if you have to do it BEFORE doing `sudo tailscale up` which I didn't because my script requires me to joithe network upon running. Either way, I just coped with a new IP. Might try to do on a new node I will reprovision later, but without joining first.

i did it before running tailscale but did not work... first installed tailscale copy and paste that file then run tailscale up command but no luck

**Comment by IzumiSena** [comment]
Its not working any help?

**Comment by DentonGentry** [comment]
@IzumiSena you've also been contacting support@tailscale.com and we're working with you there. I don't immediately know why it isn't working for you, but we'll continue to work on it via support@tailscale.com.

I'm going to close the public issue because I think the issue has a solution which is working for most.
