### ISSUE TITLE
sudo tailscale --reset disables all connectivity on ARM

### ISSUE THREAD

**Issue by Oujiii** [tailscale/tailscale#1927]
So I have I Pi 4 which was I testing the exit node feature, now I don't want it anymore and I want to disable it totally, so I run `sudo tailscale up --reset` so it can get disabled, but when I do that, sometimes it gives me a success message, but then the connectivity drops and I have to reboot a Pi manually or it doesn't give my any message and the same issue happens.

When I boot it up again, I notice that the exit node wasn't disabled at all, that also means that I'm stuck with my current options as well, because if try to add any flags, it complains about the `--advertise-exit-node`

I didn't try to remove it, but I might as being on a SD card Pi doesn't like to be forced off power and I don't have a cable to troubleshoot using console access.

**Comment by DentonGentry** [comment]
I'm not entirely clear on what the CLI is complaining about, however: in 1.8 the CLI saves the options it has been invoked with, and will only change them if explicitly told to do so. In prior releases if one had used: `tailscale up --accept-routes` and then later used `tailscale up --advertise-exit-node`, the --accept-routes would be silently discarded and this led to bad outcomes.

You should be able to use `tailscale up --advertise-exit-node=false` to explicitly clear the flag if it is no longer wanted.

**Comment by Oujiii** [comment]
Yes, I figure it that using false as the value would a way to disable the exit node feature, but unfortunately this is not a solution to the problem, but rather a workaround. If this can't be fixed, maybe adding something to the articles that refer to `tailscale up --reset` mentioning this issue, as while this might not seem a lot, it can be really troublesome.

**Comment by bradfitz** [comment]
Sorry, I'm lost. What's the issue here?

What's the series of events that has a bogus error message and the exact input/output? Or is this just about the change in behavior being surprising and not documented somewhere?

**Comment by Oujiii** [comment]
>  I don't have a cable to troubleshoot using console access.
I'm unable to see what happens after I use `sudo tailscale up` since I lose all connectivity and I don't have console access.

> Or is this just about the change in behavior being surprising and not documented somewhere?
You can say it like that. There is no place documenting that if I run `sudo tailscale up` on a Raspbian I'm gonna lose connectivity and the command will fail (I know this because when I force the reboot tailscale runs with the other arguments).

**Comment by bradfitz** [comment]
> So I have I Pi 4 which was I testing the exit node feature, 

Is your Pi being an exit node or using an exit node?

> now I don't want it anymore and I want to disable it totally, so I run sudo tailscale up --reset so it can get disabled, but when I do that, sometimes it gives me a success message, but then the connectivity drops

Which connectivity drops? Are you SSHing to it over Tailscale? Using an exit node or to its Tailscale IP directly?

**Comment by Oujiii** [comment]
> Is your Pi being an exit node or using an exit node?

I set up my pi as an exit node.

> Which connectivity drops? Are you SSHing to it over Tailscale? Using an exit node or to its Tailscale IP directly?

I was over SSH, but not using Tailscale, as the Pi is on my LAN. The SSH was through the LAN, does this have any impact? This only happens with the `--reset` flag. For instance, right now, my Pi has the exit node feature  as the last time I ran with `--advertise-exit-node=false`

**Comment by bradfitz** [comment]
Well, tailscale should not be impacting your LAN connectivity.

When it does that, can you still ping your Pi? 

/cc @danderson for ideas.

**Comment by Oujiii** [comment]
I updated to the latest version and it worked now. Not sure what was wrong before.

```bash
:~ $ sudo tailscale up --reset
Success.
```

I will now close this.
