### ISSUE TITLE
macOS: tailscale backend crashes when I do File|Share|Tailscale in TextEdit app

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1929]
Version: 1.7.458

BUG-1b57f15d6fc0818cc8e1393b7683a2e44000267afc7de1d4eb8d3b23287eb4cf-20210514165505Z-e74d020a1e28d50a

Steps: 
Not exactly sure what triggered it. I was playing with File|Share|Tailscale in the TextEdit app at the time, but that might not be relevant.

The backend disconnected and the frontend went back into "Needs login" state. Upon logging back in, all seems well.

**Comment by apenwarr** [comment]
Crashed twice more: BUG-1b57f15d6fc0818cc8e1393b7683a2e44000267afc7de1d4eb8d3b23287eb4cf-20210514170443Z-d9012699375d73cd

**Comment by apenwarr** [comment]
Okay, I think these are some repro steps:
- Start textedit
- Type some text into a file (in my case, an rtf file)
- save the file to disk (in my case, desktop)
- inside the TextEdit app, pick File|Share|Tailscale

Expected:
The regular tailscale sharing pane

Actual:
The sharing pane says something about there not being any devices available, which is not accurate.
The backend dies immediately (Tailscale icon starts animating)
Picking "login" in the frontend brings it back.

This didn't reproduce every single time. At least once, I was able to File|Share|Tailscale the text from inside TextEdit.

**Comment by apenwarr** [comment]
cc @soniaappasamy @nickoneill

**Comment by DentonGentry** [comment]
Can not reproduce with Tailscale 1.18.2 and macOS 12.0.1 on an M1 Mac.

**Comment by DentonGentry** [comment]
Still cannot reproduce, with Tailscale 1.21.50. I think this got fixed at some point.
