### ISSUE TITLE
TODO: how to log client context cancellation?

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#193]
**Describe the bug**

```
		// No need to inform client, but still log the
		// cancellation.
		//
		// TODO(bradfitz): this 499 thing is weird and
		// undocumented. [...]
		msg.HTTP.Code = 499 // nginx convention: Client Closed Request
```

The context here is that an HTTP request was canceled by the client. This means the client is gone, and the request processing is now unwinding. At this point in the code, we want to log something for the request.

Prior to this change, we logged `HTTP.Code==0`, for this and a few other cases. In trying to remove `Code=0` from our logs, I looked around for a way to record the fact that the client canceled the request, and found that nginx uses the nonstandard 499 HTTP response code for that in its own logs. That felt reasonable to me: 4xx means "client did something wrong" in HTTP, and vanishing mid-request falls under that category. It means we can trivially filter those entries out of our logs, as they won't clash with other "unexpected" codepaths that might log Code==0.

@bradfitz you added this TODO. What would you prefer to log to reflect that a request was cancelled partway through?

**Comment by bradfitz** [comment]
The full comment I added was:

```
// TODO(bradfitz): this 499 thing is weird and                                                                                                                                            
// undocumented. Also, shouldn't it be "err != nil &&                                                                                                                                     
// r.Context().Err() == context.Canceled" instead?  If                                                                                                                                    
// they just return an error, it could've been from                                                                                                                                       
// the handler's own context cancel.                                                                                                                                                      
```

The weird part is that `err == context.Canceled` does not necessarily mean that the remote user's browser/agent canceled the request. That could be from any context cancellation.

If we want to log 499 to mean the remote end hung up on us, I think we want `r.Context().Err() == context.Canceled` instead.

**Comment by danderson** [comment]
Right. I left out that part of the comment because I had no objection to that bit, that's completely reasonable (and a bug in our current HTTP logging logic). My question was more: do you object to the use of 499 because it's non-standard? If so, how would you prefer to log canceled requests?

**Comment by bradfitz** [comment]
499 is fine.
