### ISSUE TITLE
macOS: can't click on anything in the sharing pane, but keyboard shortcuts work

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1930]
Version: 1.7.458 (running for several days without changes; I'm pretty sure sharing pane was working before today)

Bugreport entry (note: this was a while after experiencing the problem, after the backend crashed in #1929)
BUG-1b57f15d6fc0818cc8e1393b7683a2e44000267afc7de1d4eb8d3b23287eb4cf-20210514165505Z-e74d020a1e28d50a

Steps:
- Finder | right click on file | Share | Tailcale
- Try to click on a tailscale node to send to, or the cancel button

Expected:
It works

Actual:
My click doesn't register.
Clicking outside the share pane doesn't close the share window. (Update: Actually I thought that's supposed to work, but it doesn't work normally either.)
Pressing the ESC key closes the share pane.
On a second attempt, I tried using the arrow keys to navigate the dialog box. This highlighted my devices one by one, sending the file to each of them. So sending itself was not broken.

cc: @soniaappasamy @nickoneill

**Comment by apenwarr** [comment]
After the backend crash-and-restart in #1929 (but notably *not* a restart of the frontend), the problem went away. I doubt I can reproduce it easily.

This reminds me of the symptoms in the earlier https://github.com/tailscale/corp/issues/1620

**Comment by DentonGentry** [comment]
To my knowledge this hasn't been reported again in the last year.

**Comment by DentonGentry** [comment]
We're approaching two years since this was filed without further reports. At this point I do not expect to figure out what happened.
