### ISSUE TITLE
"tailscale status" doesn't always reflect a change in hostname

### ISSUE THREAD

**Issue by milesstoetzner** [tailscale/tailscale#1933]
I am currently writing a puppet module to install and configure tailscale on linux.
I am having trouble accessing the current state of the client.
`/var/lib/tailscale/tailscaled.state` and `tailscale status --json` seem not to provide the same data considering hostname.

What is the expected way to evaluate the current state?
Is there some time to wait until the state is updated?
Should the `tailscaled` service be restarted after running `tailscale up`? 

In the following I will describe some scenarios. 
I have the feeling that there are some problems when using an empty string or the actual hostname as value for `--hostname`.
Overall after playing around a little bit I could not find a consistent wrong behaviour.

Btw I would really appreciate an official puppet module.

---
Example A: 

We have a host with hostname "one.two.tree.four".
When upgrading from tailscale version ~1.2.x to 1.8.3 the hostname reported to tailscale had been "one".
I require to have the full hostname reported to tailscale.

My puppet module accesses the current state by using the following command:
```
cat /var/lib/tailscale/tailscaled.state | jq -r "._daemon" | base64 --decode | jq
```

And executes the following command if `Hostname` (or actually `AdvertiseRoutes`) is not as expected.
```
tailscale up --authkey=$AUTH_KEY --hostname=one.two.tree.four --advertise-routes=
```

The hostname is correctly updated in `tailscale status --json` but not in `/var/lib/tailscale/tailscaled.state`.
Therefore on the next puppet run `tailscale up` is executed again.

---
Example B: 

When setting the hostname, the hostname is updated in the `tailscaled.state` but not in `tailscale status`.
But after a restart, it seems to work.

```
# Returns "one.two.three"
tailscale status --json | jq -r '.Self.HostName | values' 

tailscale up --hostname=VALUE

# Still returns "one.two.three"
tailscale status --json | jq -r '.Self.HostName | values'

# Returns "VALUE"
cat /var/lib/tailscale/tailscaled.state | jq -r "._daemon" | base64 --decode | jq -r '.Hostname  | values'

systemd restart tailscaled.state


# Returns "VALUE" as expected
tailscale status --json | jq -r '.Self.HostName | values'

# Returns "VALUE" as expected
cat /var/lib/tailscale/tailscaled.state | jq -r "._daemon" | base64 --decode | jq -r '.Hostname  | values'
```

---

Example C: 

Kind of the reverse of Example B.
When setting the hostname, the hostname is updated in `tailscale status` but not in `tailsclae.state`.
But I think after restarting the `tailscaled` service the hostname got resetted to the value in `tailscale.state`.

I could not reproduce this misbehaviour for this bug report but it happened a few times.

---

System:

```
# Ubuntu 18.04.5 LTS

tailscale version 
1.8.3
  tailscale commit: d0e86b08c99d23686e2c2416f1e3c93d5c00863a
  other commit: 03346d1fbc21a0ae7e02abc7a7b5e62569c4bc55
  go version: go1.16.4-ts1b677aa
```

**Comment by DentonGentry** [comment]
> Should the tailscaled service be restarted after running tailscale up?

No, the service shouldn't be restarted. The tailscale CLI command communicates with tailscaled using a unix domain socket, tailscaled will act on it directly.

> The hostname is correctly updated in tailscale status --json but not in /var/lib/tailscale/tailscaled.state

In general we'd want scripts to use the output of `tailscale status --json` and not expect to parse the tailscaled.state file.

It looks like `tailscale status` may be caching the output somewhere, and changes in hostname don't immediately appear. That would be a bug.

**Comment by danderson** [comment]
Still happens. Reproduced with:

```
# System hostname is vega, tailscale is up with no hostname override set\
tailscale up --hostname=other
tailscale status --json | jq .Self.HostName # correctly shows "other"
tailscale up --hostname=vega
tailscale status --json | jq .Self.HostName # still shows "other"
systemctl restart tailscaled
tailscale status --json | jq .Self.HostName # shows "vega" again
```

**Comment by danderson** [comment]
Tracing through the code, EditPrefs does appear to update the hostInfo data that the status endpoint consults, so I'm currently confused.

**Comment by danderson** [comment]
Okay. Weirdly, the self hostname is set allllll the way down inside the bowels of magicsock, rather than in the ipn LocalBackend, and magicsock pulls the hostname from its currently applied network map, i.e. the hostname that control sent over.

So, my suspicion is that we're suppressing a netmap update somewhere even though the hostname has changed, and so magicsock doesn't get the update it needs.

**Comment by bradfitz** [comment]
> In general we'd want scripts to use the output of tailscale status --json and not expect to parse the tailscaled.state file.

Yeah, that's really not a stable interface. The base64 had some reason at one time, but as far as I'm concerned the main purpose of the base64 there is to dissuade people from looking at it because it's subject to change.
