### ISSUE TITLE
tailscale not working on Windows

### ISSUE THREAD

**Issue by jpathy** [tailscale/tailscale#1938]
OS Version: 10.0.21382.0
Tailscale version: 1.8.3

It doesn't work after the insider update. It says Service not running but the service is running. The log files in `AppData\Local\Tailscale` are empty.

**Comment by apenwarr** [comment]
Possibly the same as https://github.com/tailscale/tailscale/issues/1792. Can you run `tailscale bugreport` from the windows command line and paste the output here?

**Comment by jpathy** [comment]
`BUG-7c975edf13bac1028eb813a5817dc5ac10fa4271da4e4f5cfd321e6dce4f96d8-20210518091452Z-0eb32bd3b54aa6f5`

**Comment by monkiely** [comment]
> `BUG-7c975edf13bac1028eb813a5817dc5ac10fa4271da4e4f5cfd321e6dce4f96d8-20210518091452Z-0eb32bd3b54aa6f5`

same error:
BUG-32bf933aa6bdfb52724ae818679899af763d6efd67db2c3ef80473e43543bba0-20210521025754Z-017c57ea7d3a98f5

**Comment by monkiely** [comment]
> > `BUG-7c975edf13bac1028eb813a5817dc5ac10fa4271da4e4f5cfd321e6dce4f96d8-20210518091452Z-0eb32bd3b54aa6f5`
> 
> same error:
> `BUG-32bf933aa6bdfb52724ae818679899af763d6efd67db2c3ef80473e43543bba0-20210521025754Z-017c57ea7d3a98f5`

This occurred after my Win10 upgraded to 21H1

**Comment by monkiely** [comment]
> > > `BUG-7c975edf13bac1028eb813a5817dc5ac10fa4271da4e4f5cfd321e6dce4f96d8-20210518091452Z-0eb32bd3b54aa6f5`
> > 
> > 
> > same error:
> > `BUG-32bf933aa6bdfb52724ae818679899af763d6efd67db2c3ef80473e43543bba0-20210521025754Z-017c57ea7d3a98f5`
> 
> This occurred after my Win10 upgraded to 21H1

Resolved by cmd "tailscale logout" and relogging in.

**Comment by apenwarr** [comment]
Possibly already fixed in v1.8.7. Can someone re-test please?

**Comment by monkiely** [comment]
> Possibly already fixed in v1.8.7. Can someone re-test please?

Thank you for the update, but my issue has been fixed already by relogging.

**Comment by apenwarr** [comment]
Thanks @monkiely! I'll close this for now unless/until someone can reproduce on v1.8.7 or later. We fixed a bunch of issues that could have caused this during the v1.8.x cycle.

**Comment by monkiely** [comment]
> Thanks @monkiely! I'll close this for now unless/until someone can reproduce on v1.8.7 or later. We fixed a bunch of issues that could have caused this during the v1.8.x cycle.

Much obliged!
