### ISSUE TITLE
Article on how to introduce VNC as default program on device to access throughTailscale services.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1943]
From Customer:

vnc://

links work in MS Windows. The customer is trying to edit my registry to add vnc:// as a protocol, so that can assign a VNC program to it as a default. Win 10 seems to not support it out of the box. If I want other users to use this function,we really don't want to have to explain registry editing to folks. 

Ask here is ..... making an article explaining how to do this. Or, even create some small executable that would set it up for users.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_35mj5)

**Comment by DentonGentry** [comment]
At this point I don't expect to document HKEY_CLASSES_ROOT\VNC on our own site, we've focused documentation how to use RDP over Tailscale.
Guide for how to set a VNC helper: https://community.xibo.org.uk/t/adding-vnc-protocol-windows/12007/2
