### ISSUE TITLE
Allow cross-sharing using the Tailscale node sharing.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1946]
Bi-directional sharing of node.

Example from one of our customer:

Two networks:

OPS with one shared node: OPS-node1. That’s the one which needs bidirectional connections.
CLIENT-A: with two nodes (CLIENT-A-node1 and CLIENT-A-node2). These nodes will need to talk with OPS-node1. Some checks are initialized by CLIENT-A-node* and others are initialized by OPS-node1.Now as a workaround we can share both ways.

But what happens when another network (CLIENT-B) comes into play. I would need to share OPS-node1 to CLIENT-B network and share CLIENT-B-node1 to OPS network.

Would shared CLIENT-A nodes see shared CLIENT-B nodes? I would say no, because only OPS-node1 is shared to CLIENT-B.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_35qj5)

**Comment by DentonGentry** [comment]
It is not clear to me that we should do this: explicitly sharing each time makes the intent clear. Implicitly sharing a node more widely could easily do something the sharer didn't intend.

**Comment by bartmichu** [comment]
I believe I'm the one who originally asked about this feature.

On second thought, I think it's better how it currently works i.e. without bidirectional share. Like @DentonGentry said, when I accept an invitation I want to be SURE that it means I can access one particular node, period. Especially with no ACLs on solo plan.

**Comment by DentonGentry** [comment]
Ok, closing bug.

**Comment by SGprooo** [comment]
> Ok, closing bug.

I'd just like to ask, is this part of the "bidirectional connections" feature request?
If I shared my device onto a friend's tailnet, shouldn't there be an option for him to explicitly allow me to make outgoing connections to nodes on his tailnet?
This quarantine "feature" seems somewhat unfinished.
