### ISSUE TITLE
portlist: filter out tailscaled's own ports

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#195]
I notice that MapRequest contains tailscaled's own ports in the portlist.

Can probably filter those out, yeah?

/cc @crawshaw @apenwarr @danderson

**Comment by crawshaw** [comment]
Are there standard lists of ports we can filter out? So many ports.

**Comment by apenwarr** [comment]
I still think "burn it all to the ground and only look for specific
whitelisted ports" is the least crazy plan at this point. I will not have
any hard feelings if people delete most of my portlist code.

**Comment by bradfitz** [comment]
Fixed in 51b669e4bdb14dcb31a7a237606539d701ef97c5

More work remains. Looks like a dozen blacklisted Windows entries is enough to get things reasonable looking.

Again, I don't want to move to a whitelist quite yet. I really do want my arbitrary dev servers to show up by default if possible. It's worth trying.
