### ISSUE TITLE
peerapi: peer listeners are brought up too early on Android

### ISSUE THREAD

**Issue by eliasnaur** [tailscale/tailscale#1960]
While working on https://github.com/tailscale/tailscale/issues/1809, I encountered the erros:

```
[unexpected] peerapi listen("100.86.189.59") error: listen tcp4 100.86.189.59:0: bind: cannot assign requested address
[unexpected] peerapi listen("fd7a:115c:a1e0:ab12:4843:cd96:6256:bd3b") error: listen tcp6 [fd7a:115c:a1e0:ab12:4843:cd96:6256:bd3b]:0: bind: cannot assign requested address
```

The root cause is that Android has immutable tunnel devices, which means that the app recreates a tunnel every time the configuration changes. It also means that the initial device isn't created before state Started is reached, leading to the socket listener errors above.

I've hacked around the problem by adding InitPeerAPIListener,

```
diff --git ipn/ipnlocal/local.go ipn/ipnlocal/local.go
index d766c312..b2c5c2ab 100644
--- ipn/ipnlocal/local.go
+++ ipn/ipnlocal/local.go
@@ -1868,6 +1868,10 @@ func (b *LocalBackend) closePeerAPIListenersLocked() {
        b.peerAPIListeners = nil
 }
 
+func (b *LocalBackend) InitPeerAPIListener() {
+       b.initPeerAPIListener()
+}
+
 func (b *LocalBackend) initPeerAPIListener() {
        b.mu.Lock()
        defer b.mu.Unlock()
```

and calling it whenever the tunnel is (re-)created. Of course, a better solution is needed here.

CC @bradfitz

**Comment by bradfitz** [comment]
@eliasnaur, I just pushed cc6ab0a70f8660b0051ad18d8006b715740f454b which I imagine will make it work on Android. Seems like the same-ish issue that we had on Windows.

Let me know?

**Comment by eliasnaur** [comment]
Seems to work. Thanks!
