### ISSUE TITLE
Tailscale does a request to log.tailscale.io even when not in use

### ISSUE THREAD

**Issue by jvoisin** [tailscale/tailscale#1964]
I've got tailscale (1.8.5) installed on my Ubuntu 21.04, and it's doing a request *every two minutes* to log.tailscale.io, even when not in use, and not configured as an exit-node.

Would it be possible to tone it down, or even get rid of it?

**Comment by DentonGentry** [comment]
We've been reducing the log reporting in the last several releases, primarily to benefit battery life of mobile devices. If it is truly not in use one could `systemctl stop tailscaled` until the next time it is needed, to avoid any activity.

**Comment by DentonGentry** [comment]
Tailscale 1.32 added a `--no-logs-no-support` argument to tailscaled. If you want to not have any logging activity, that ill turn it off.
