### ISSUE TITLE
Nested VM on Azure connects over DERP only ,while they are on same LAN.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1967]
We've been experiencing DERP rather than peer-to-peer traffic in a nested VM environment. where the hypervisor is running, which in turn is a VM in Azure hosting VMs running Windows 10 Enterprise running tailscale as well) and the client, a Windows 10 Pro device, both running the 1.8.3 version.

Linux Host: 

BUG-1556331971e24d8340ffeaadce5614c24f6c49978e9944361707be81b134a0e1-20210519152744Z-95297b72d212dd23
/ BUG-1556331971e24d8340ffeaadce5614c24f6c49978e9944361707be81b134a0e1-20210519153410Z-9b30155f5042bbce

Windows Pro client:

BUG-a0ecfa835d79e5021414afba9a3f3147bd6e5ed97d5a6ec98ae07f41fbf8439a-20210519153209Z-abb3b4adf5f99e21

At the time we collected the bug report, the Windows 10 Pro device was connected to the Windows 10 Enterprise VM via RDP over a peer-to-peer tailscale tunnel as seen below and simultaneously via SSH to the Linux host but in DERP rather than peer-to-peer as seen below:

PS C:\Users> echo "this command was ran on the Windows 10 Pro device"; tailscale status; tailscale bugreport
this command was ran on the Windows 10 Pro device 
100.89.17.54 desktop-j8m3isv redacted@ windows -
100.99.142.40 redacted.com.beta.tailscale.net netadmin@ windows idle, tx 1303800 rx 1358288
100.101.102.103 ("hello") services@ linux - 
100.76.193.101 redacted.beta.tailscale.net netadmin@ windows active; direct 51.103.64.202:1025, tx 18566320 rx 48707840
100.94.163.34 redacted.beta.tailscale.net netadmin@ linux active; relay "fra", tx 14576 rx 15184

BUG-a0ecfa835d79e5021414afba9a3f3147bd6e5ed97d5a6ec98ae07f41fbf8439a-20210519153209Z-abb3b4adf5f99e21
PS C:\Users>

**Comment by wizzard0** [comment]
Observed the same behavior between OSX laptop and Linux VMs too (having LAN IP addresses in the same /24 subnet)

**Comment by DentonGentry** [comment]
This was filed to followup on a support request, but the specific support request was not recorded and we don't know where the followup would go. Closing as not useful any more.
