### ISSUE TITLE
GSuite avatar missing after recreating GSuite account

### ISSUE THREAD

**Issue by shadowfox1991** [tailscale/tailscale#1975]
I noticed that when I recreated my GSuite account and signed up for Tailscale again, the account was unable to pull my avatar from Google. Not really an issue, just wanted to report the small bug!

![screenshot](https://i.imgur.com/8Fvk1Lb.png)

**Comment by DentonGentry** [comment]
Right now the name and picture are only pulled once, the first time an account signs in to Tailscale. If anything goes wrong, or if the name or picture change, it won't be updated.

We're expecting to deploy a feature this week which will have the coordination server re-fetch the name and picture on each login, intended to handle name changes and the like. Once that deploys to production, I expect it will resolve the broken picture the next time you login.

**Comment by DentonGentry** [comment]
The updated coordination server deployed earlier today. If you go to https://login.tailscale.com and log out (if necessary), then log in, it should re-fetch the name and picture.
