### ISSUE TITLE
Repeated push notifications on mac that machine is going to expire / no statement of where to take action to update

### ISSUE THREAD

**Issue by wasauce** [tailscale/tailscale#1977]
I’m getting a push notification on my mac for the attached — repeatedly. So far 10 of them. 

When I click the notification, nothing happens. When I login to the admin UI — it says this machine is going to expire in 24 hours — but doesn’t say where to take action. 

I am on MacOS 10.15.7 with build 1.8.1

![Screen Shot 2021-05-18 at 4 25 43 PM](https://user-images.githubusercontent.com/41729/119385905-ae86c800-bc7b-11eb-8717-99fadadd2016.png)

**Comment by DentonGentry** [comment]
Ah. We need to improve the notification text. To get it to stop bugging you: from the Tailscale menu bar icon please log out, and log back in.

![LogOut](https://user-images.githubusercontent.com/1140756/119388929-c6f8e180-bc7f-11eb-8609-c0b8eb76c4c9.jpg)

**Comment by wasauce** [comment]
Thanks @DentonGentry 

This solves the problem. I suppose the text could either say "Logout and log back in" but you could add another option there that says "Re-authenticate" -- that is what I as a user was looking for.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/corp/pull/4217 disabled the notifications in 3/2022, which went into the 1.24 release. Notifications may come back when they behave better.
