### ISSUE TITLE
Magic DNS not working on Android

### ISSUE THREAD

**Issue by mightymatth** [tailscale/tailscale#1985]
### Issue Description

In the recent version of the Android client application, IP addresses cannot be resolved by another machine's name, meaning that Magic DNS probably stopped working.

### How to reproduce
* open port 22 on Linux machine to enable ssh connections,
* log in to Tailscale on your Android phone,
* open ConnectBot application to connect via ssh
* enter connection details: `ssh username@machine-name`

### How it behaves

It fails to connect via ssh by machine name and throws a message:
```
Connecting to machine-name:22 via ssh

Connection Lost
Unable to resolve host "machine-name": No address associated wit
android_getaddrinfo failed: EAI_NODATA (No address associated
```

### How it should behave

It should find the machine's IP by resolving the "machine-name" hostname and connect to the machine.

### Additional notices

It works fine if I try to connect via IP address directly. Also, Magic DNS works fine on macOS. 
It's important to say that Magic DNS on Android worked for months until the recent update.

### Versions

Android:
* phone: Samsung Galaxy S8,
* Tailscale version: 1.8.3,

Machine with name "machine-name":
* OS: Raspbian (on Raspberry Pi 4),
* Tailscale version: 1.8.3,
* Additional configuration:
  * advertised subnet,
  * exit node.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1956
