### ISSUE TITLE
derp: check that no v1 clients are around, remove v1 protocol code branches

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#199]
Small cleanup. I believe v1 was never in the wild outside Tailscale Inc. machines, so we should be able to strip out the small protocol deviations and complications. This is just a reminder to do that, at some point.

**Comment by bradfitz** [comment]
I see it was added in `bf704a5 oss derp: protocol negotiation, add v2: send src pub keys to clients in packets` in 0.96-22, along with nearly all the DERP support.

The only older clients in the wild are 52 Windows users running 0.95 which didn't have DERP.

So, yes, safe to delete. I'll do that, as I'm in there now.
