### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference after authenticating (build this repo on Win64)

### ISSUE THREAD

**Issue by dd121** [tailscale/tailscale#1996]
On Win 10 amd64 os build 19042.985

reproduce steps
building this repo on win64 machine
adding wintun.dll to system (download from https://www.wintun.net/)
run tailscaled
run tailscale up --authkey xxx

directly after authenticating tailscaled crashed with enclosed error 

[nil pointer reference.txt](https://github.com/tailscale/tailscale/files/6555461/nil.pointer.reference.txt)

**Comment by bradfitz** [comment]
What version of Tailscale? Which git commit did you build from?

**Comment by bradfitz** [comment]
How are you running tailscaled? In cmd.exe in the foreground? As an admin?

**Comment by dd121** [comment]
Latest build, in cmd.exe as admin.

**Comment by dd121** [comment]
First in foreground, goal is as a service.

**Comment by dd121** [comment]
And tailsale up in cmd normal.

**Comment by bradfitz** [comment]
Please provide an exact git commit. Your line numbers don't make sense based on current HEAD.

**Comment by dd121** [comment]
I dowloaded the code in a zip file. Where can I find the git commit?

**Comment by dd121** [comment]
Just cloned last version #35749ec2 (if that is the commit) 
[error.txt](https://github.com/tailscale/tailscale/files/6556517/error.txt)
and got same error.
