### ISSUE TITLE
illegal instruction running tailscale on old IMac running High Sierra v10.13.6

### ISSUE THREAD

**Issue by agrw** [tailscale/tailscale#2013]
$ sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale up --advertise-exit-node
Illegal instruction: 4

**Comment by bradfitz** [comment]
@agrw, is it a 32-bit machine?

I just ran Tailscale on an old MacBook Air 2011 running 10.13 and it worked fine.

**Comment by agrw** [comment]
Hmm, let me get back to you tomorrow, machine is remote and I have to get access.

**Comment by agrw** [comment]
It's a 64 bit Mac, I was able to get tailscale setup as an exit node using your excellent instructions - https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS .
So I'm going to close this issue.
