### ISSUE TITLE
Issue setting up Tailscale on Ubuntu 20.04

### ISSUE THREAD

**Issue by tamugo** [tailscale/tailscale#2017]
I am following the [instruction](https://tailscale.com/kb/1039/install-ubuntu-2004/) on setting up Tailscale on Ubuntu 20.04, but whenever I get to step 3 I always get the error message below:
`can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory`

I am not sure how to move past this, and help would be appreciated.

**Comment by DentonGentry** [comment]
Could you check if tailscaled is running?
Use: `ps auxw | grep tailscaled` and you should see something like:
```
$ ps auxw | grep tailscaled
root     38763  0.0  0.1 1826740 21048 ?       Ssl  May25  66:48 /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641
```

Also please check its local logs:
```
$ sudo journalctl -u tailscaled
[sudo] password for dgentry:
-- Logs begin at Sun 2021-01-17 15:34:01 PST, end at Sun 2021-05-30 19:25:19 PDT. --
Jan 20 16:14:37 ubuntu systemd[1]: Starting Tailscale node agent...
Jan 20 16:14:37 ubuntu tailscaled[1061]: logtail started
Jan 20 16:14:37 ubuntu tailscaled[1061]: Program starting: v1.2.10-te480f8ddf-g7b8c9553a, Go 1.15.4-tsf9db43b: []string{"/usr/sbin/tailscaled", "--cleanup"}
```

**Comment by tamugo** [comment]
I'm not completely sure, but it does not seem to be runnin:
`tamugo     592  0.0  0.0   8160   668 pts/0    S+   23:21   0:00 grep --color=auto tailscaled`

And my local logs were empty:
`No journal files were found.
-- No entries --`

**Comment by DentonGentry** [comment]
I guess check whether the tailscale binaries even got installed:
```
$ ls -l /usr/bin/tailscale
-rwxr-xr-x 1 root root 10787564 May 21 22:17 /usr/bin/tailscale
$ ls -l /usr/sbin/tailscaled
-rwxr-xr-x 1 root root 16597143 May 21 22:16 /usr/sbin/tailscaled
$
```

**Comment by DentonGentry** [comment]
If there are no further updates, we'll close this issue on the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT.
