### ISSUE TITLE
Ability to specify default folder to download the files transfer over Taildrop.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2018]
The ability to specify a default folder to receive files in might be nice (e.g. PC1 specifies that they want files to be received in C:\Users\{username}\Documents) and the sender does not need to know where the receiver wants to receive files.

**Comment by DentonGentry** [comment]
This was filed to followup on a support request, but the specific support request was not recorded and we don't know where the followup would go. Closing as not useful any more.
