### ISSUE TITLE
Add "Learn More" link besides the taildrop feature option in admin console.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2019]
There’s no “Learn more” link to the docs next to the description of Send Files, so it’s not immediately obvious how one might use it, and they’ll either have to have had the email regarding Taildrop already open, or they’d have to search the docs manually for it.

**Comment by DentonGentry** [comment]
A Learn More link could lead to https://tailscale.com/taildrop or https://tailscale.com/kb/1106/taildrop/

**Comment by WalterHub** [comment]
There's a Learn More link, point to /kb/1106/taildrop, in the admin console now.

![Screen Shot 2022-04-05 at 4 20 53 PM](https://user-images.githubusercontent.com/1179333/161866725-5e099dd6-e92a-466e-a122-b54cd187de14.png)
