### ISSUE TITLE
Raspberrypi 4: tailscaled.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by war59312** [tailscale/tailscale#202]
Hi,

No luck getting tailscale to work on my Raspberrypi 4.

The same error below goes for stable vs unstable builds, tried both.

Here is the latest unstable build attempt. Has not changed in days.

Installs fine, but when I try to then run it:

```
sudo tailscale up
[sudo] password for pi: 
logtail started
Program starting: v0.97-38-ga4b33970: []string{"tailscale", "up"}
LogID: ddb9dc397b87fb08f7820212323fa79386499adf91dd1840978f138d682ed272
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)
```

**To Reproduce**
1. Following guide @ https://tailscale.com/kb/1043/install-raspbian-buster
2. Errors out @ Step 4

**Expected behavior**
Expected for tailscale to run and give the url for first time login

**Version information:**
- Raspberrypi 4
- Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
- Tailscale v0.97-38-ga4b33970

**Comment by danderson** [comment]
That error means `tailscaled` is not starting correctly. What does `journalctl -u tailscaled --since="1 hour ago"` say?

My initial guess is your rpi is missing the tuntap kernel module, but the logs will say for sure.

**Comment by war59312** [comment]
Thanks for getting back to me.

Log shows this over and over again:

```
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 logtail started
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 Program starting: v0.97-38-ga4b33970: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "41641"}
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 LogID: cd2912cc22f5d89f7df5dc909418c2597c33e218fcec6c6eca3b51d7653efb2d
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 14.8M/19.1M Starting userspace wireguard engine.
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 14.8M/19.1M external packet routing via --tun=tailscale0 enabled
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 14.8M/19.1M CreateTUN: no such device
Mar 20 15:51:37 raspberrypi tailscaled[14018]: 2020/03/20 15:51:37 wgengine.New: no such device
Mar 20 15:51:37 raspberrypi systemd[1]: tailscaled.service: Main process exited, code=exited, status=1/FAILURE
Mar 20 15:51:37 raspberrypi systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Mar 20 15:51:37 raspberrypi systemd[1]: tailscaled.service: Service RestartSec=100ms expired, scheduling restart.
Mar 20 15:51:37 raspberrypi systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 4852.
Mar 20 15:51:37 raspberrypi systemd[1]: Stopped Tailscale node agent.
Mar 20 15:51:37 raspberrypi systemd[1]: Started Tailscale node agent.
```

**Comment by bradfitz** [comment]
I just installed it on a Raspberry Pi 4 (with Raspbian Buster) and it worked fine.

How are our two systems different?

I didn't need to do anything special to make tun available:

```
pi@piosk:~ $ lsmod | grep tun
tun                    45056  2
$ ls -l /dev/net/tun
crw-rw-rw- 1 root root 10, 200 Mar 20 13:21 /dev/net/tun
```

... it was just there.

Are you running a custom kernel?

**Comment by apenwarr** [comment]
Side note: sounds like the tailscale command could provide better
diagnostics by printing a specific error whenever /dev/net/tun is missing
on Linux?

**Comment by bradfitz** [comment]
@apenwarr, already done days ago... https://github.com/tailscale/wireguard-go/commit/fc0d3b3791f3a173ca5cb6475f5855b1e32d96ce

(well, 2 days ago)

**Comment by war59312** [comment]
I just installed a clean Raspbian Buster the day it was publicly released for raspi 4. Nothing custom at all.

I get nothing back when I run "lsmod | grep tun".

And same as you:

```
$ ls -l /dev/net/tun
crw-rw-rw- 1 root root 10, 200 Mar 12 21:09 /dev/net/tun
```
So tired this:

```
pi@raspberrypi:~ $ sudo modprobe tun
[sudo] password for pi: 
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.75-v7l+/modules.dep.bin'
modprobe: FATAL: Module tun not found in directory /lib/modules/4.19.75-v7l+
```

Perhaps the day 1 release was bad. :( Guess not too surprising.

Rather not reinstall, this seems to be the only thing broken at the moment.

**Comment by war59312** [comment]
Success, it was a broken kernel. Now just have to open up firewall rules. But it's showing up correctly @ https://login.tailscale.com/admin/machines and can ping itself.

Well, hopefully, this will help the next poor soul who runs across this.

**Comment by bradfitz** [comment]
FWIW, I didn't need to modify any firewall rules on my Raspberry Pi for it to work. Actually, in general you shouldn't have to when using tailscale.

**Comment by war59312** [comment]
Yea not sure, /var/log/syslog doesn't show getting blocked.

On the pi it can ping its own 100 tailscale address but nothing can ping it and it cant ping others. Also browsing to its 100 ip in browser not working either, so its not working correctly.

yes web service running on port 80 on the pi so expect to see its homepage.

**Comment by bradfitz** [comment]
Is /var/log/syslog where you normally see firewall blocked messages?

Are you using a custom firewall? Which?

**Comment by war59312** [comment]
Yes, Gufw and log also @ /var/log/ufw.log

Already tried disabling it and no change. And ufw log does not show it being blocked.

**Comment by bradfitz** [comment]
Not sure how you disabled it, but you might still have iptables rules around from an earlier run of it.

What does `sudo iptables -L  -n -v` say? To see whether it's firewall-related, uninstall your firewall, reboot, and then try?

**Comment by war59312** [comment]
I disabled iptables and ufw completely and same problem.

Just noticed this in log `journalctl -u tailscaled --since="1 hour ago"`

` Handshake did not complete after 20 attempts, giving up`

Sanitized log:

```
Mar 21 18:43:34 raspberrypi tailscaled[457]: 2020/03/21 18:43:34 magicsock.Conn: starting endpoint update (periodic)
Mar 21 18:43:34 raspberrypi tailscaled[457]: 2020/03/21 18:43:34 netcheck: derp1.tailscale.com:3478 says we are 162.193.202.40:34242 (in 29ms)
Mar 21 18:43:34 raspberrypi tailscaled[457]: 2020/03/21 18:43:34 netcheck: derp2.tailscale.com:3478 says we are 162.193.202.40:33458 (in 66ms)
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 netcheck: derp4.tailscale.com:3478 says we are 162.193.202.40:19929 (in 113ms)
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 netcheck: derp3.tailscale.com:3478 says we are 162.193.202.40:14576 (in 233ms)
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 magicsock: found local 162.193.202.40:34242 (stun)
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 magicsock: found local X.X.X.164:41641 (localAddresses)
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 75.8M/78.9M control: Hostinfo: &{0.97-45-g02c73501  cd2912cc22f5d89f7df5dc909418c2597c33e218fcec6c6eca3b51d7653efb2d linux raspberrypi [] [{tcp 22 sshd} {tcp 80 lighttpd} {tcp 443 lighttpd} {tcp 3000 ntopng
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 75.8M/78.9M control: cancelMapSafely: synced=true
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 75.8M/78.9M control: PollNetMap: context canceled
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 75.8M/78.9M control: mapRoutine: state:authenticated
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 75.8M/78.9M control: PollNetMap: stream=-1 :0 [162.193.202.40:34242 X.X.X.164:41641]
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M control: new network map[0]:
Mar 21 18:43:35 raspberrypi tailscaled[457]: netmap: self: [eFV8S] auth=machine-authorized :0 [100.71.138.86/32]
Mar 21 18:43:35 raspberrypi tailscaled[457]:  [f3e4p]    100.123.189.110 :  162.193.202.40:28388  162.193.202.40:5437    192.168.147.1:63058  X.X.X.105:63058
Mar 21 18:43:35 raspberrypi tailscaled[457]:  [MNw8B] D2 100.101.102.103 :   54.214.102.89:41641   172.31.25.118:41641      172.17.0.1:41641
Mar 21 18:43:35 raspberrypi tailscaled[457]:  [YJ82T]    100.77.189.124  :    45.79.202.26:41641 192.168.196.199:41641
Mar 21 18:43:35 raspberrypi tailscaled[457]:  [HhYI8] D1 100.71.140.61   :   X.X.X.19:60226
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M control: mapRoutine: netmap received: state:synchronized
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M control: sendStatus: mapRoutine2: state:synchronized
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M netmap diff: (none)
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M netmap packet filter: [*=>*:*]
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M Configuring wireguard connection.
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M reconfig: ra=false dns=true 0x01
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M Reconfig(): configuring userspace wireguard engine.
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M ...unchanged config, skipping.
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M SetPrefs: Prefs{ra=false mesh=true dns=true want=true notepad=false derp=true pf=true routes=[] Persist{m=[HxBGB], o=[AAAAA], n=[eFV8S] u="me@gmail.com"}}
Mar 21 18:43:35 raspberrypi tailscaled[457]: 2020/03/21 18:43:35 77.9M/78.9M [HhYI8] - [eFV8S] Send handshake init [127.3.3.40:1, X.X.X.19:60226]
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 79.6M/78.9M control: Hostinfo: &{0.97-45-g02c73501  cd2912cc22f5d89f7df5dc909418c2597c33e218fcec6c6eca3b51d7653efb2d linux raspberrypi [] [{tcp 22 sshd} {tcp 80 lighttpd} {tcp 443 lighttpd} {tcp 3000 ntopng
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 79.6M/78.9M control: cancelMapSafely: synced=true
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 79.6M/78.9M control: PollNetMap: context canceled
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 79.6M/78.9M control: mapRoutine: state:authenticated
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 79.6M/78.9M control: PollNetMap: stream=-1 :0 [162.193.202.40:34242 X.X.X.164:41641]
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M control: mapRoutine: netmap received: state:synchronized
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M control: sendStatus: mapRoutine2: state:synchronized
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M netmap diff: (none)
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M netmap packet filter: [*=>*:*]
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M Configuring wireguard connection.
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M reconfig: ra=false dns=true 0x01
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M Reconfig(): configuring userspace wireguard engine.
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M ...unchanged config, skipping.
Mar 21 18:43:36 raspberrypi tailscaled[457]: 2020/03/21 18:43:36 81.7M/78.9M SetPrefs: Prefs{ra=false mesh=true dns=true want=true notepad=false derp=true pf=true routes=[] Persist{m=[HxBGB], o=[AAAAA], n=[eFV8S] u="me@gmail.com"}}
Mar 21 18:43:38 raspberrypi tailscaled[457]: 2020/03/21 18:43:38 81.8M/78.9M [YJ82T] - [eFV8S] Send handshake init [45.79.202.26:41641, 192.168.196.199:41641]
Mar 21 18:43:38 raspberrypi tailscaled[457]: 2020/03/21 18:43:38 81.8M/78.9M [f3e4p] - [eFV8S] Send handshake init [162.193.202.40:28388, 162.193.202.40:5437, 192.168.147.1:63058, X.X.X.105:63058]
Mar 21 18:43:40 raspberrypi tailscaled[457]: 2020/03/21 18:43:40 82.0M/78.9M [HhYI8] - [eFV8S] Send handshake init [127.3.3.40:1, X.X.X.19:60226]
Mar 21 18:43:43 raspberrypi tailscaled[457]: 2020/03/21 18:43:43 82.1M/78.9M [YJ82T] - [eFV8S] Send handshake init [45.79.202.26:41641, 192.168.196.199:41641]
Mar 21 18:43:43 raspberrypi tailscaled[457]: 2020/03/21 18:43:43 82.1M/78.9M [f3e4p] - [eFV8S] Send handshake init [162.193.202.40:28388, 162.193.202.40:5437, 192.168.147.1:63058, X.X.X.105:63058]
Mar 21 18:43:45 raspberrypi tailscaled[457]: 2020/03/21 18:43:45 82.2M/78.9M [HhYI8] - [eFV8S] Send handshake init [127.3.3.40:1, X.X.X.19:60226]
Mar 21 18:43:48 raspberrypi tailscaled[457]: 2020/03/21 18:43:48 82.4M/78.9M [YJ82T] - [eFV8S] Send handshake init [45.79.202.26:41641, 192.168.196.199:41641]
Mar 21 18:43:49 raspberrypi tailscaled[457]: 2020/03/21 18:43:49 82.4M/78.9M [f3e4p] - Handshake did not complete after 20 attempts, giving up
Mar 21 18:43:51 raspberrypi tailscaled[457]: 2020/03/21 18:43:51 82.5M/78.9M [HhYI8] - [eFV8S] Send handshake init [127.3.3.40:1, X.X.X.19:60226]
```

**Comment by war59312** [comment]
Well, it's odd for sure. Some computers can see others and others cant seem them. It's a mess.

Routing messed up somewhere. 2 computers have "Relay-1", 1 computer has "Relay-2".

TailScale client is installed on all the systems, so not sure why Relay is even being used.

**Comment by danderson** [comment]
Relay connections are always set up as a last resort when NAT traversal fails. In this case you're very likely using them for some connections, because netcheck reports `MappingVariesByDestIP: true`, which means your NAT is hostile to p2p traversal. It's also fine for machines to be homed at different relays, but it does mean you could be falling victim to a bug we recently fixed. What version of the package are you running? I'm looking for 0.97-45 or newer for some DERP fixes.

Pushing tailscaled logs to log.tailscale.io is always on right now, DNS/firewall blocking's your best bet. It'll also make it impossible for us to debug your connectivity issues, since tailscaled logs are the primary tool we use for that. Happy to delete the logs already collected if you drop us a line at support@tailscale.com with the account you used to auth to tailscale.

**Comment by war59312** [comment]
Thanks for the info, good to know.

I think I just came into the scene at a bad time and had a few old versions with bugs.

I got my Windows Client updated. Was on 0.95, upgraded now to 0.96.1.0

Linode box got updated from 0.94-236 to 0.97.0~45

Mac running latest as installed from app store, version 0.97.78

Much better results now. Oddly MAC still can't ping it's own TailScale IP but all other devices can, even with mac firewall off.

**Comment by danderson** [comment]
Mac being unable to ping itself is a known quirk of how mac implements VPN support (basically our network engine runs in a little sandboxed universe managed by macOS, and macOS is in charge of the routing between the OS and that sandbox... And for some reason self-pings don't work). It's on our list to figure out if we can work around it, but for now that's "working as designed" from macOS's POV.

Glad to hear it's all working now! We definitely made huge improvements to connectivity in the last few weeks, so I'm not surprised upgrading the older nodes helped a bunch.

I'll open a new bug for the Windows about screen and version stuff. I wouldn't be surprised to find a `// TODO` in there about that, we got popular a little ahead of schedule and have been catching up since.

**Comment by drasch** [comment]
I ran into this with a missing tun device after an initial install (PLUS an `apt ugprade`) I think that during the apt upgrade it upgraded the kernel (and perhaps moved the DKMS modules) so it couldn't find the `tun` module. After a reboot (and now using the new kernel), everything is happy! Just hoping this helps someone else!

**Comment by smp4488** [comment]
I ran into this issue today. My issue was that I forgot that I disabled the `tailscaled.service` a while back.
```
sudo systemctl enable tailscaled.service
sudo systemctl start tailscaled.service
```
