### ISSUE TITLE
Updated tailscale cli status output table to be width-aligned and formatted

### ISSUE THREAD

**Issue by emattiza** [tailscale/tailscale#2028]
# Situation
When invoking tailscale status from a peer to get a list of peers, i had a peer where the first ip found was its ipv6 address. The output of the command exceeded the expected width of 16 characters set in the standard output formatter, and was jumbled visually.
# Resolution
I applied some formatting from the go-pretty library and its table module to the standard output to produce a cleaner table in the status command output. I have a fork I am maintaining currently, and am curious if this is a visual polish that would be valuable in your upstream.
## Before
![Second](https://user-images.githubusercontent.com/11719476/120376945-17a4b600-c2e2-11eb-9ea2-63b3f2d466d4.jpg)

## After
![First](https://user-images.githubusercontent.com/11719476/120376958-1b383d00-c2e2-11eb-8fc4-84127d6d82a0.jpg)

**Comment by bradfitz** [comment]
What other unixy tools format output like this?

**Comment by emattiza** [comment]
column(1) from coreutils would do something very similar. I'll consider this redundant then, and free to close!
