### ISSUE TITLE
cmd/tailscale: clarify error message when tailscaled not running

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2029]
Users get confused by:

```
:~$ sudo tailscale up
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

They understandably think that `tailscale up` starts `tailscaled`.

Let's make tailscale detect when tailscaled is not running and give a better error message.

**Comment by rugwirobaker** [comment]
What's the best way to start tailscaled when running inside a minimal alpine docker container anyway?
