### ISSUE TITLE
cmd/tailscale: confusing error from ping when peer node is not authorized

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#2030]
100.n.n.n is an as-yet unauthorized node.

```
go run ./cmd/tailscale --socket /Users/josh/t/sock ping 100.N.N.N
exit node found but not enabled
exit status 1
```

This is a weird error message.

**Comment by bradfitz** [comment]
That error is from `(*userspaceEngine).peerForIP` which answers the question about "which node handles this IP?" 

It found that there's no node with a route to that IP in the current wireguard config. But it's saying "FYI, even though I didn't find a node that'd handle it, I did find an exit node in your netmap that you're not using... if you were using an exit node, then there'd be a route!"

**Comment by bradfitz** [comment]
I'd probably change this,

```
        if bestInNMPrefix.Bits() == 0 {
                return nil, false, errors.New("exit node found but not enabled")
        }
        return nil, false, fmt.Errorf("node %q found, but not using its %v route", bestInNM.ComputedNameWithHost, bestInNMPrefix)
```

to:

```
        if bestInNMPrefix.Bits() == 0 {
                if tsaddr.IsTailscaleIP(ip) {
                         return nil, false, nil
                }
                return nil, false, fmt.Errorf("no node has active route to %v; an exit node is available but not selected", ip)
        }
        return nil, false, fmt.Errorf("node %q found, but not using its %v route to %v", bestInNM.ComputedNameWithHost, bestInNMPrefix, ip)
```

**Comment by josharian** [comment]
SGTM

**Comment by DentonGentry** [comment]
All of this code appears to be different now, and there is no string "exit node found but not enabled" in the codebase any more.

**Comment by DentonGentry** [comment]
I think this code was all removed a year ago or more.
