### ISSUE TITLE
win: Tailscale icon not used in "add/remove programs" menu

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2041]
Windows 10, Tailscale 1.8.5 released version. No dots.
![no-ts-icon](https://user-images.githubusercontent.com/161319/120563373-3e83ea80-c3bd-11eb-81fa-ec7043cb1dae.png)

**Comment by crawshaw** [comment]
This doesn't appear to work here. Win10, building from HEAD.

**Comment by DentonGentry** [comment]
Huh. Weird.

**Comment by crawshaw** [comment]
Is Win10 always 64-bit? I see there's a `SetRegView 32` in the nsh file, and a suspicious shortage of registry keys like those in my windows machine.

**Comment by crawshaw** [comment]
Yeah I think that's it. Is your VM 32-bit? Because with this I now see an icon:

```
diff --git a/win/installer/ipn.nsh b/win/installer/ipn.nsh
index bb43e842e..9b5b47849 100644
--- a/win/installer/ipn.nsh
+++ b/win/installer/ipn.nsh
@@ -140,6 +140,7 @@ Section "Install" InstDriver
     SetRegView 64
     WriteRegStr HKLM "Software\${REGNAME}" "" "$INSTDIR"
     WriteRegStr HKLM "Software\${REGNAME}" "seed" "value"
+    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${REGNAME}" "DisplayIcon" "$INSTDIR\tailscale-ipn.exe"

     WriteUninstaller "$INSTDIR\Uninstall-Tailscale.exe"
     SetRegView 32
```

**Comment by crawshaw** [comment]
Do we, uh, need all those other registry keys? :)

**Comment by DentonGentry** [comment]
According to Settings > System > About: "64-bit operating system, x64-based processor"
I dunno why the `SetRegView 32` setting worked for me, but it seems fine to set it in both. 

I've no idea which of the other registry settings might be load bearing.

**Comment by DentonGentry** [comment]
Fixed by the MSI installer.
<img width="467" alt="Screenshot 2023-02-12 at 7 42 30 AM" src="https://user-images.githubusercontent.com/1140756/218321103-e7265d0d-6cce-41ae-898c-cdf84b22414e.png">
