### ISSUE TITLE
tailscale HTTP calls fail after 30min when using IPv6 privacy addrs on linux

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#2045]
On a linux system with IPv6 connectivity and `net.ipv6.conf.$IFACE.use_tempaddr = 2`, the global IPv6 address rotates periodically to preserve privacy. This breaks Tailscale's HTTP traffic to control, because we seem to hang onto a client socket that's still trying to send using an old IPv6 source address that was since deleted:

```
logtail: dial "log.tailscale.io:443" failed: dial tcp [2600:1f14:436:d603:342:4c0d:2df9:191b]:443: connect: network is unreachable (in 1ms)    
```

(that was a logtail connection, but control conns fail the same way)

Looks like we need to somehow get our HTTP client to flush its sockets when we hit HTTP errors, so that a fresh bind() gets a hold of the new source addr.

This is especially problematic because most "desktop" linux distros enable IPv6 privacy addresses by default these days, so there's a good chance many linux desktop users with v6 connectivity are hitting this.

cc @bradfitz for net/http expertise on how we should do this.

**Comment by danderson** [comment]
This no longer seems to be happening. My daily driver machine uses temporary addresses, and seems perfectly happy.

**Comment by DentonGentry** [comment]
Has not been seen for some time.
