### ISSUE TITLE
Use AWS Cognito as an Identity provider

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2046]
The customer is looking forward to having an option to use AWS Cognito as an Idp.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3n3kh)

**Comment by bradfitz** [comment]
Related-ish bug for AWS SSO is https://github.com/tailscale/tailscale/issues/920

**Comment by DentonGentry** [comment]
Since this issue was filed, support for Custom OIDC providers has been added: https://tailscale.com/kb/1240/sso-custom-oidc/

**Comment by catzkorn** [comment]
Cognito works with our Custom OIDC feature.
