### ISSUE TITLE
Restore version/version.sh

### ISSUE THREAD

**Issue by TimothyGu** [tailscale/tailscale#2058]
Some recent versioning improvements done by @danderson (e.g., aa6abc98f30df67a0d86698b77932d4d9cc45ac0) removed version/version.sh. Distributors are instead encouraged to run build-dist.sh directly to get proper version stamping. However, for the [tailscale-git](https://aur.archlinux.org/packages/tailscale-git/) AUR package, we were previously using version/version.sh to implement the [pkgver](https://wiki.archlinux.org/title/PKGBUILD#pkgver) function, which simply prints the package version without building the package. Now that version/version.sh and build-dist.sh are combined, we can't get the version alone without building the re-implementing the logic ourselves.

It would be great to re-introduce a versioning script that produces an eval-able shell script that defines variables like `VERSION_LONG` and `VERSION_SHORT`.

**Comment by danderson** [comment]
Makes sense. Rather than have a second shell script floating around the repo, is it okay if we make it some mode of build_dist.sh? That way all the version stamping logic stays in one place. Not a hugely strong feeling either way though.

**Comment by TimothyGu** [comment]
Yeah that'd be great. My suggestion would be something like

```sh
./build_dist.sh --print-version=long
```

to print only the long version (the only one we use).

**Comment by danderson** [comment]
Hmm, don't you also need the git hashes? I suppose you can get those easily without our help :)

**Comment by TimothyGu** [comment]
FWIW, the "long" version actually includes the Git hash:

https://github.com/tailscale/tailscale/blob/e92fd1948439be7c5f714ea7eac943ee593af347/build_dist.sh#L32-L35

**Comment by danderson** [comment]
Done, `./build_dist.sh shellvars` plops out the same envvars as before (with the ones that only make sense in our closed-source builds removed, e.g. XCode and Windows versions)

**Comment by danderson** [comment]
The long version includes a shortened hash, but in our builds we also set a different var to the full hash, just in the unlikely event of collisions. Either's okay though, as long as there's some way of pinpointing the build hash. Thanks for the report!
