### ISSUE TITLE
Taildrop files not found when notifications are turned off on iOS

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#2060]
The Tailscale folder on the `Files` app is visible only when I click on the Tailscale notification after receiving a Taildrop. If I don't click on the notification and open `Files` app directly, `Tailscale` folder is not found.

#### Steps to reproduce 

- On the iOS settings app, open Tailscale from the left menu.
- Click on notifications section.
- Turn notifications off.
- Send files from another Tailscale device to this iOS device using [Tailscale](https://tailscale.com/blog/sending-files-with-taildrop/) feature.
- Open `Files` app on iOS.
- Notice that Tailscale folder is not visible.

**Comment by arunsathiya** [comment]
An idea is to show a notice within the Tailscale iOS app UI that new files are available, but do folks actually open the iOS app often? 

More importantly, the bug being reported here is the missing `Tailscale` folder on `Files` app if I don't click on the notification. I tried re-opening the `Files` app as well but the folder isn't available.

**Comment by DentonGentry** [comment]
We're working on a better long-term fix, but as a way to access the files: send another file, any file. When you click on the notification for the new file, all of the pending transfers will be copied to the Tailscale folder including the ones sent earlier.

**Comment by arunsathiya** [comment]
It's great that a fix is planned. Yup, that's precisely the workaround I am using at the moment, but when someone turns off Tailscale app's notifications altogether (on iOS settings), there is no way to identify how to access the files. A different UI to identify incoming files would be nice.

Perhaps I am overthinking the situation but something to consider when a fix is being developed.

Happy for this GitHub issue to be closed.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/corp/pull/3810, which will be in 1.24.
