### ISSUE TITLE
Avoid relying on synchronous disk access at runtime

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2062]
From this tweet: https://twitter.com/lukegb/status/1401579365121544195
Someone has a disk that is sometimes non-responsive, and tailscale stops responding when that happens.

We don't do a lot of disk access (reads of a fresh file, or f.Sync()). As far as I can see, the only code path that is probably relevant is the f.Sync() in atomicfile, which is used when writing the log config in logpolicy, or the prefs in ipn, and the OS dns config files in net/dns.

Some options:
- Write files a lot less often. It's unlikely the tailscale prefs file actually needs to be rewritten, but we might be doing so unnecessarily. Same with DNS.
- Remove the sync operation for files that don't need it. This is rather tricky to get right, since we don't want to lose our keys across reboots, but it's not impossible if we use an sqlite-like WAL journal technique, for example.
- Make the synchronous file replacement parts of the code (eg. prefs writing) happen in a single goroutine so the program can continue, but only the fsync part blocks in its own thread.
-

**Comment by DentonGentry** [comment]
Similar to https://github.com/tailscale/tailscale/issues/2084

**Comment by apenwarr** [comment]
Oops, forgot I filed this one. I think the other one is better :)
