### ISSUE TITLE
About overriding the client DNS settings after starting the DNS server

### ISSUE THREAD

**Issue by odyf** [tailscale/tailscale#2063]
This problem has appeared in Synology and OPenwrt soft routing, which affects the dns resolution of other programs. Attach a screenshot.
![Snipaste_2021-06-06_19-29-15](https://user-images.githubusercontent.com/72725679/120966325-a3ae5600-c798-11eb-9c9f-2788eda05c67.png)

**Comment by DentonGentry** [comment]
That looks like https://login.tailscale.com/admin/dns has Magic DNS enabled, using the 1.8 release.

If you don't want this, a couple options:
- disable Magic DNS in https://login.tailscale.com/admin/dns which will disable it for all devices
- if you only want Synology and OpenWRT to not get the DNS settings, use "tailscale up --accept-dns=false"

**Comment by apenwarr** [comment]
Looks like it's working as intended. Please reopen if you disagree.

**Comment by Qifcn** [comment]
![image](https://user-images.githubusercontent.com/34029055/123500032-9a185f80-d66d-11eb-9540-248fd5c7e9ce.png)
Normal use of private DNS screenshots, it should be a logical misunderstanding, thinking that it needs to be enabled Magic DNS

**Comment by DentonGentry** [comment]
@Qifcn I don't quite understand: with the 1.10 release, do you see anything broken when using 100.76.193.103 as a DNS server?

**Comment by Qifcn** [comment]
> @Qifcn我不太明白：使用1.10版本时，您是否看到任何损坏时，使用100.76.193.103作为DNS服务器？

I built a dns service on nas, its address is this intranet address,
