### ISSUE TITLE
Probe for DERP latency over HTTPS if UDP is blocked

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#207]
In a UDP-blocked network, DERP latency checking fails. This is expected, and we have a fallback: use a random DERP server. This guarantees connectivity, but potentially at the cost of higher latency if we pick the wrong one (75% probability currently).

If we get zero response from UDP during netcheck, we should switch to a fallback where we check DERP latency using HTTPS queries to derpX.tailscale.com. This check will take longer (many RTTs), but it should give us good data for UDP-blocked networks.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686843366403) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
Yup, there's a TODO in the code about that:

```
        // TODO: if UDP is blocked, try to measure TCP connect times                                                                                                                             
        // to DERP nodes instead? So UDP-blocked users still get a                                                                                                                               
        // decent DERP node, rather than being randomly assigned to                                                                                                                              
        // the other side of the planet? Or try ICMP? (likely also                                                                                                                               
        // blocked?)                                                                                                                                                                             
```

The other thing we can do, rather than totally random selection, is pick where most the peers in the domain are.

**Comment by leoluk** [comment]
An HTTPS endpoint on the DERP server that returns tcpinfo_rtt should be very accurate.
