### ISSUE TITLE
macOS: tailscale v1.6 doesn't register DNS correctly when in splitdns mode

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2075]
Steps:
- Install macOS tailscale v1.6 from xcode
- Log in
- Setup your domain to use split dns + magicdns

Expected:
- magicdns names can be looked up, eg. in your browser or with `ping`

Actual:
Tailscale somehow doesn't register itself as a DNS server.

For macOS this isn't super important since people can't downgrade. But it's likely the same on iOS (where old testflights will now be broken) and possibly other platforms too.

We don't really want to debug this functionality in v1.6. Control should probably just always use fallback dns -> global dns for pre-v1.8 versions, and not attempt to provide split dns settings at all.

**Comment by danderson** [comment]
Reproduced. Puzzling. 1.6 is completely unaware of split DNS configuration, and I was certain we'd told control to backport to non-split as needed...

**Comment by danderson** [comment]
Ah, we never plumbed fallback resolvers into legacy response construction, that's where we went wrong. We expected the global DNS configuration to always be non-empty, and so we hand down a "do nothing" configuration when we intend to hand out a global config that uses fallbacks. Fixing.

**Comment by DentonGentry** [comment]
I'm not finding a pull request which lines up with this timing, not clear whether the fallback config is resolved.

**Comment by crawshaw** [comment]
I believe this is https://github.com/tailscale/corp/pull/1946. Needs a control push and then someone with macOS Tailscale v1.6 to confirm

**Comment by DentonGentry** [comment]
Control push to deploy this happened June 17.
