### ISSUE TITLE
CLI: `tailscale logout` doesn't release the machine name

### ISSUE THREAD

**Issue by Pluies** [tailscale/tailscale#2076]
Hello!

We've been using Tailscale to expose services in a Kubernetes cluster, where our Tailscale containers come & go.

In order to ensure consistent [Machine Names](https://tailscale.com/kb/1098/machine-names/) for access over Magic DNS, we use `tailscale up` with the `--hostname` flag, which works perfectly... The first time a pod comes up.

Then, if the pod gets cycled for any reason, the first machine name will not be released, and the new machine will come up with a `-1` suffix, breaking Magic DNS.

We've tried cleaning up resources on shutdown by using `tailscale down`, to no effect, and the newer `tailscale logout` as per https://github.com/tailscale/tailscale/issues/466 (thanks @namansood & @DentonGentry !). `tailscale logout` indeed disconnects the machine, but it never releases the machine name, and still leads to clashes.

We've also tried using [Ephemeral Nodes](https://tailscale.com/kb/1111/ephemeral-nodes/), but ran into the same issue. I assume everything would work if we waited until the ephemeral node was cleaned up before re-provisioning a new one with the same name, but it won't help for pod disruptions where a new pod usually comes back up in a few seconds.

The only workaround we've found at this stage is to delete the disconnected machine through the API before logging in:

```bash
#!/usr/bin/env bash

set -euo pipefail

echo "Removing the machine through the API..."
TAILSCALE_CLIENT_IDS=$(curl \
  -u "${TAILSCALE_API_KEY}:" \
  "https://api.tailscale.com/api/v2/tailnet/${TAILSCALE_TAILNET}/devices" \
  | jq -r '.devices[] | select(.hostname=="'"$TAILSCALE_HOSTNAME"'").id')

echo "Found client id(s):"
echo "${TAILSCALE_CLIENT_IDS}"
for CLIENT_ID in ${TAILSCALE_CLIENT_IDS}
do
  echo "Removing client id $CLIENT_ID"
  curl \
    -u "${TAILSCALE_API_KEY}:" \
    -X DELETE \
    "https://api.tailscale.com/api/v2/device/${CLIENT_ID}"
done
```

Which obviously isn't a great solution as it forces us to use both an auth key and an api key, and interact with Tailscale through the CLI and the API separately.

Shouldn't `tailscale logout` also remove the machine, freeing the hostname to be reused?

(Note: I'm pretty new at Tailscale, so I may have missed a better way to do this – if so please let me know! 😄  )

**Comment by DentonGentry** [comment]
There are two keys involved:
- the machine key, generated when the device first joins the Tailnet and never changed
- the node key, which is a user logged in

"tailscale logout" revokes the node key, logging the user out, but it only expires the machine key without completely deleting it.
![Screen Shot 2021-06-08 at 5 15 21 AM](https://user-images.githubusercontent.com/1140756/121183284-c1bb9b00-c818-11eb-9931-df55523af6e0.png)

This is the reason that the hostname is still taken. The machine key can be temporarily extended from the admin panel:
![Screen Shot 2021-06-08 at 5 17 50 AM](https://user-images.githubusercontent.com/1140756/121183487-fa5b7480-c818-11eb-872a-562184681cc3.png)

We'll have to look at whether this should be re-thought.

**Comment by Pluies** [comment]
Hi @DentonGentry ,
Thanks for your answer! It makes sense now 👍 
It would be awesome to be able to remove a machine key & delete it straight away without needing to use the API. Potentially with an additional CLI flag to `tailscale logout`? Something like `--force-delete` or `--expire-machine`, to drive in the point that it's unreversible.
- Florent

**Comment by DentonGentry** [comment]
At this point, I don't expect we'll implement this. I understand the motivation for wanting a CLI command from the device which can remove a node from the Tailnet, but the source of truth of Tailnet membership is not the device. The coordination server is, and the API is the way to remove a node.

I recognize that the initial statement expressed not wanting to use the API, but nonetheless that is the way to do it.

**Comment by Yokutto** [comment]
Sorry to bump a closed issue, but...

I think this is still worth discussing. Even though the contributor have said he won't add a "logout and release hostname" feature, I feel like it's something that deserves another look

I have an autonomous systems that rely on their machine hostnames (resolved through MagicDNS), and it works great… until an ephemeral container restarts for some reason. Then, the hostname changes to something like `machine-name-1` because of [this behavior](https://tailscale.com/kb/1098/machine-names#how-machine-names-are-determined)

That's why I agree with @Pluies that adding a `--release-hostname` flag to `tailscale logout` would be super helpful. It would let the hostname get cleaned up properly so when the container comes back, it registers with the right name

Containers that use a `pre_stop` hook for `tailscale logout` or `--state=mem:` in `tailscaled`, could re-join tailscalenet with the correct hostname and avoid these inconsistencies
