### ISSUE TITLE
tstest/integration --race does not work on Mac

### ISSUE THREAD

**Issue by JulianKnodt** [tailscale/tailscale#2080]
The integration tests under `tstest/integration` do not seem to work on darwin because the STUN server shuts down:
![image](https://user-images.githubusercontent.com/7675847/121264742-7e8b1780-c86c-11eb-9aa8-f21fe2103f5f.png)

It's not immediately clear why this is the case, and tests pass when `--race` is not passed.

**Comment by DentonGentry** [comment]
Somewhere along the way this got fixed:
```
dgentry@Dentons-MacBook-Air integration % go test --race
PASS
ok  	tailscale.com/tstest/integration	8.352s
dgentry@Dentons-MacBook-Air integration %
```
