### ISSUE TITLE
Version not embedding with -ldflags

### ISSUE THREAD

**Issue by herbygillot** [tailscale/tailscale#2081]
Trying to build Tailscale v1.8.7 with the following command line:

```
go build -ldflags " -X tailscale.com/version.Long=1.8.7 -X tailscale.com/version.Short=1.8.7 " ./cmd/tailscale{,d}
```

It builds fine, no issues, but unfortunately version information does not seem to be properly embedding:

```
./tailscale version
date.20210505
  go version: go1.16.5
```

Anything I'm missing? Trying to add Tailscale to [MacPorts](https://ports.macports.org/port/tailscale/summary).

**Comment by danderson** [comment]
Works here. Are you building each binary separately? If you specify both binaries on the same line, Go builds the binaries in its build cache, but doesn't write the output to the local directory. So you might be looking at an older tailscale binary. Try as separate commands:

```
go build -ldflags "-X tailscale.com/version.Long=1.8.7 -X tailscale.com/version.Short=1.8.7 " ./cmd/tailscale
go build -ldflags "-X tailscale.com/version.Long=1.8.7 -X tailscale.com/version.Short=1.8.7 " ./cmd/tailscaled
```

Also, you can potentially use the `build_dist.sh` script, which does some of this for you if you're in a git checkout: `./build_dist.sh ./cmd/tailscale`

**Comment by herbygillot** [comment]
Thanks @danderson; doing both fixed the issue (building each binary one by one, in addition to using `build_dist.sh`).  Closing and much appreciated.
