### ISSUE TITLE
iOS: no way to see who you're logged in as

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2083]
Version: v1.8.x

After logging in, there is nowhere in the UI that shows you your current user account. At least one end user complained to me that they had trouble testing taildrop because they were accidentally logged into the wrong account on iOS, and there was no easy way to tell.

**Comment by agottardo** [comment]
This was fixed in v1.46. User profile picture is displayed prominently at the top-right of the app UI, and in the Settings view as well.
