### ISSUE TITLE
tailscaled hangs after a while, no connections accepted till restart

### ISSUE THREAD

**Issue by omeryagmurlu** [tailscale/tailscale#2091]
Tailscale freezes after a while if it's not connected to a client for a while (~30 minutes). Pinging from clients result in packet losses, no connection can be established at all.

Connecting via OpenVPN to the server, I can see that the tailscaled systemd service is still in the active (running) state and systemd journal is filled with the following:

```
Jun 09 22:53:50 REDACTED tailscaled[257604]: Accept: TCP{100.78.X.X:443 > 100.98.X.X:54472} 40 ok out
Jun 09 22:53:50 REDACTED tailscaled[257604]: Accept: TCP{100.98.X.X:54472 > 100.78.X.X:443} 174 tcp non-syn
Jun 09 22:54:20 REDACTED tailscaled[257604]: Accept: TCP{100.98.X.X:54472 > 100.78.X.X:443} 994 tcp non-syn
Jun 09 22:54:20 REDACTED tailscaled[257604]: Accept: TCP{100.78.X.X:443 > 100.98.X.X:54472} 40 ok out
Jun 09 22:54:20 REDACTED tailscaled[257604]: Accept: TCP{100.98.X.X:54472 > 100.78.X.X:443} 174 tcp non-syn
```
where `100.78.X.X` is the servers IP, other one that of the client. Timestamps line up with my (failed) connection attempts.

Running tailscale status and/or netcheck on the frozen tailscaled service or restarting tailscaled seems to fix the issue, I couldn't debug this further. This problem has been going for ~2 weeks right now.

Let me know if you need more information.

System: Arch Linux 5.12.9-arch1-1 with ipv6 disabled in kernel.

**Comment by omeryagmurlu** [comment]
Now that I've scrolled through the list of issues, I've found this issue (https://github.com/tailscale/tailscale/issues/1924), which is probably the cause of my issue.

I'll ask package maintainers on arch to downgrade to 1.6 if possible after testing with that version.

**Comment by omeryagmurlu** [comment]
Downgrading to 1.6 didn't fix the issue as I had the same problem with it this morning again. These issues probably not related then.

**Comment by DentonGentry** [comment]
After ~30 minutes? Could you look at the symptoms in https://github.com/tailscale/tailscale/issues/2045 ?

That would also explain why 1.6 now shows the same symptom when it did not before, if the change which triggered the behavior was in IPv6 privacy address handling after some kind of update.

**Comment by omeryagmurlu** [comment]
I don't think it's related. IPv6 is disabled on the kernel level (My ISP has deployed IPv6 somewhat problematically, so I just forego it), and tailscale is also aware of this fact:

```
Report:
        * UDP: true
        * IPv4: yes, <IP>:59576
        * IPv6: no
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: Frankfurt
        * DERP latency:
                - fra: 6.5ms   (Frankfurt)
                - lhr: 19.3ms  (London)
                - nyc: 97.1ms  (New York City)
                - dfw: 127.5ms (Dallas)
                - blr: 148.5ms (Bangalore)
                - sea: 159.7ms (Seattle)
                - sfo: 165.3ms (San Francisco)
                - tok: 223.3ms (Tokyo)
                - sin: 260.6ms (Singapore)
                - syd:         (Sydney)
```

The ~30 minutes was just an estimate, since I have no way of reproducing the problem reliably. Sometimes 30 minutes without any connections is enough for tailscaled to not accept any new connections, sometimes it works even if I try to establish a new connection after ~2 hours.

The only consistent thing about this is that I have to restart tailscaled via OpenVPN everyday after waking up, or else it doesn't accept any connections.

**Comment by DentonGentry** [comment]
The 1.12.1 release resolved a number of issues about Linux suspend and network reconfig. Does the problem still happen with 1.12?

**Comment by omeryagmurlu** [comment]
It's been running without a problem for ~36 hours without a problem after the latest update, so it seems like the problem's solved. I'll reopen this issue if it happens again.
