### ISSUE TITLE
Declining GitHub Authorization causes a 500 error

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#2094]
![image](https://user-images.githubusercontent.com/529003/121533491-55829800-c9ce-11eb-9896-6370ff3a1e6d.png)

Reproduction steps:
1. Log in with GitHub
2. Decline the prompt
3. Control 500's

**Comment by DentonGentry** [comment]
Fixed in Jan 2023 by @clairew in https://github.com/tailscale/corp/pull/8617 (which most of y'all won't be able to see, sorry).

<img width="404" alt="Screenshot 2023-02-12 at 8 10 01 AM" src="https://user-images.githubusercontent.com/1140756/218322568-cd5d9709-b9ac-4496-aff0-12aefd7e4a52.png">
