### ISSUE TITLE
Registry Keys

### ISSUE THREAD

**Issue by havedill** [tailscale/tailscale#2097]
I know placing a key for "AllowIncomingConnections" should work at this location: "HKEY_LOCAL_MACHINE\SOFTWARE\Tailscale IPN" 

My question is, what would the other keys be for DNS settings, subnet settings?

Also - is there a way to remotely turn on unattended mode for a workstation, without having to log in as the end user? via a registry key or something similar?

**Comment by DentonGentry** [comment]
DNS settings and subnet routes are pushed from the coordination server to the Tailscale client, and do not come from registry keys.

To enable Unattended Mode you can set a `UnattendedMode` key in `HKLM\SOFTWARE\Tailscale IPN` to "always", "never", or "user-decides"
