### ISSUE TITLE
Allow setting a suffix for MagicDNS single-label domains

### ISSUE THREAD

**Issue by xSke** [tailscale/tailscale#2099]
I noticed you can currently access devices on your network just with their hostname (`http://laptop/`, etc). However not everything plays the nicest with single-word domain names like that.

Could it be possible to configure a suffix to use instead? so I can instead address my hosts as `laptop.local` or `desktop.local` (if I set the suffix as eg. `.local`)

**Comment by DentonGentry** [comment]
I'm going to close this on the assumption that the FQDN will work. Please reopen if not.
