### ISSUE TITLE
Automatically remove HTTP prefix when DNS server addresses are pasted

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#2100]
When my friends copy my node address (from a chat app like Signal) and paste it on their DNS servers field, it adds the HTTP prefix. Could we automatically remove that prefix? 

![image](https://user-images.githubusercontent.com/18581859/121574952-6968e100-ca44-11eb-901a-25189c13fbde.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_38tu9)

**Comment by rosszurowski** [comment]
Yep, this shouldn't be hard to do. We'll need to be cautious when we end up launching DNS-over-HTTP which may require this prefix (not sure), but for now, it's an easy improvement we can make.

**Comment by rosszurowski** [comment]
I just merged a fix for this, which should go live the next time we deploy (today? likely by the end of the week)
