### ISSUE TITLE
Exit nodes get firefox stuck in mostly-broken state on windows

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2105]
Windows 10, Tailscale 1.9.157

Turning on an exit node on Windows, then turning it off, to the point where basic pings and DNS lookups on the command line work, leave _existing_ Firefox tabs broken. New tabs can be open that successfully connect to pages.

The existing tabs break even navigating between pages on a site they have already loaded (e.g. pressing 'Submit new issue' on github) so my first guess isn't DNS.

This may be a firefox bug reacting to network changes, but this may be linked to the fact that turning on/off exit nodes has a lot of lag in the taskbar icon. The menubar shows the exit node changed immediately, but the little arrow -> takes a minute to appear and disappear.

cc @danderson @maisem

**Comment by crawshaw** [comment]
Sometimes new tabs get stuck too.

**Comment by DentonGentry** [comment]
Likely same root cause as https://github.com/tailscale/tailscale/issues/2106
