### ISSUE TITLE
macOS CLI should failed for -advertise-exit-node.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2110]
The customer is trying to create the macOS exit node which is not supported but the command to enable the exit-node in macOS works successfully. which misguide the customer.

/Applications/Tailscale.app/Contents/MacOS/Tailscale up --advertise-exit-node --accept-routes 

We should disable or make it fail in macOS , until it will be supported.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_38zkh)

**Comment by bradfitz** [comment]
@crawshaw, should we just do hybrid netstack mode on macOS too?

**Comment by bradfitz** [comment]
Decision from meeting: yes, but for Tailscale 1.12.

**Comment by bradfitz** [comment]
So now this is a dup of #911
