### ISSUE TITLE
Tailscale packages missing for Ubuntu

### ISSUE THREAD

**Issue by ethanhs** [tailscale/tailscale#2111]
I recently did an `apt update`, and it seems that the apt repo for ubuntu is missing from pkgs.tailscale.com.

I went to https://pkgs.tailscale.com/stable/ to check, and the instructions for Ubuntu Focal, which I am running, are to download https://pkgs.tailscale.com/stable/ubuntu/focal.list

The contents of that file are:
```
# Tailscale packages for ubuntu focal
deb https://pkgs.tailscale.com/stable/ubuntu focal main
```

However, when I go to https://pkgs.tailscale.com/stable/ubuntu, I get a 404.

**Comment by bradfitz** [comment]
That's a base URL to which the Debian family of tools have a known structure underneath. It's okay that that root URL serves a 404.

I guess we could serve some informational sort of page there, though? (cc @danderson)

But that doesn't address whatever problem you're having. Did it work after you followed the instructions for adding the repo and running `apt-get update` and `apt-get install tailscale`?

**Comment by ethanhs** [comment]
@bradfitz No, I get

```
E: The repository 'https://pkgs.tailscale.com/stable/ubuntu focal Release' no longer has a Release file.
```

It seems the needed Release/InRelease files 404 as well. (I guessed their location)

**Comment by DentonGentry** [comment]
Weird, a system I previously set up is able to fetch updates:

```
$ sudo apt update
[sudo] password for dgentry:
Get:1 https://pkgs.tailscale.com/stable/ubuntu focal InRelease
Get:2 https://packages.cloud.google.com/apt cloud-sdk InRelease [6739 B]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:5 https://packages.microsoft.com/repos/azure-cli focal InRelease
Get:6 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1031 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [283 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [781 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [330 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2468 B]
Get:12 http://archive.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [58.3 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [2468 B]
```

**Comment by ethanhs** [comment]
FWIW, if I try to go to https://pkgs.tailscale.com/stable/ubuntu/focal/InRelease on my system that also 404s. If there is a different url to test I can maybe debug this better.

**Comment by bradfitz** [comment]
@danderson, @maisem, did the pkgserver reindexing get borked?

**Comment by maisem** [comment]
@ethanhs can you try again?

**Comment by danderson** [comment]
Note the correct URL for the releases files is https://pkgs.tailscale.com/stable/ubuntu/dists/focal/InRelease and https://pkgs.tailscale.com/stable/ubuntu/dists/focal/Release (your URL was missing a `/dists/` in it, but apt should be adding that in)

**Comment by ethanhs** [comment]
Hm yeah those seem to work locally on my laptop. This appears to be a network issue with my server on my end, I'll have to investigate. Sorry for the trouble! And thank you for a really cool tool :)

It might be nice to enable indexing so people can browse the apt repo, I think I would have realized this was my fault sooner had I been able to prove the file was available to me. Anyway, cheers and thanks for the help debugging.
