### ISSUE TITLE
FR: go/ links as a tailnet service

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2115]
We like go/ links. Lots of companies have their own go/ server implemented. We could build it into Tailscale as an automatic service that appears on your tailnet.

**Comment by DentonGentry** [comment]
We might consider separating additional services out from the Tailscale app, to avoid any potential destabilization of the connectivity service.

For example for a go link service, we might provide it as a [one-click Deploy to Heroku button](https://devcenter.heroku.com/articles/heroku-button) which creates a container containing a [link shortener like koochooloo](https://github.com/1995parham/koochooloo) together with a userspace tailscaled, sets the hostname to "go", and authorizes it with a one-time authkey. The free Heroku tier could handle the load of a link shortener for personal use and even many organizations. Persistent storage for the links database would need to be figured out.

**Comment by Xe** [comment]
Heroku has a free tier for its hosted Postgres product (and for its hosted Redis project even), so that could be a viable road to go down.

**Comment by DentonGentry** [comment]
Launched in November 2022: https://tailscale.com/blog/golink/
