### ISSUE TITLE
Tailscale Error when starting

### ISSUE THREAD

**Issue by NriotHrreion** [tailscale/tailscale#2117]
![image](https://user-images.githubusercontent.com/50199130/121799671-f76ce380-cc5f-11eb-9e69-d176980251c1.png)

**Comment by DentonGentry** [comment]
For future reference: 64970734d8cf7dea2dafd713c59c30144c37e7aa2297d569939dc6ae13ee0c38
Running v1.9.164 on Windows.

It is failing almost immediately, registry keys it expects to be there are not present:

`[Wintun] RegistryQuery: Querying registry value \REGISTRY\MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0016\NetCfgInstanceId failed: 系统找不到指定的文件。 (Code 0x00000002)`

(系统找不到指定的文件 == The system can not find the file specified)

Could I ask:
- what version of Windows is it?
- it isn't finding entries for network interfaces, like Wi-Fi and Ethernet. What network interfaces are present?

**Comment by NriotHrreion** [comment]
My version is `Windows 2004`.
And when I use it, I had connected to the wifi. By the way, I didn't use vpn.

**Comment by NriotHrreion** [comment]
The error pops up shortly after I start Tailscale

**Comment by DentonGentry** [comment]
Something is blocking access to the registry.

Tailscale doesn't usually require running as an Administrator account, but for troubleshooting it might be worth trying. If it works as an Administrator then there may be anti-virus or endpoint security software blocking access to parts of the registry.

**Comment by NriotHrreion** [comment]
I tried to run it as an admin, but it still can't work.

**Comment by NriotHrreion** [comment]
Can you tell me what I should do now???

**Comment by DentonGentry** [comment]
Something is blocking access to the registry. There may be anti-virus or endpoint security software blocking access to parts of the registry.

**Comment by NriotHrreion** [comment]
There isn't any anti-virus on my computer

**Comment by NriotHrreion** [comment]
It said "The system can not find the file specified", so what file does it want?

**Comment by NriotHrreion** [comment]
When I start it in cmd
![image](https://user-images.githubusercontent.com/50199130/121831166-61859700-ccf9-11eb-89e1-2fac10be22e7.png)
