### ISSUE TITLE
Android client is inaccessible with TalkBack

### ISSUE THREAD

**Issue by mwcampbell** [tailscale/tailscale#2118]
The Tailscale Android client is completely inaccessible with the TalkBack screen reader for blind users. It appears that this app is using the Gio UI toolkit, which doesn't yet have accessibility support. The most practical way to solve this problem may be to rewrite the UI as a native Android UI, or using a web view.

**Comment by DentonGentry** [comment]
We've begun the planning for a substantial UI rewrite, likely using native widgets, and expect to address this as part of that effort.

**Comment by bradfitz** [comment]
Dup of #1004
