### ISSUE TITLE
Create riscv packages

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2119]
I wanted riscv packages today on a board I run, and another user did too:

https://twitter.com/olofj/status/1404288660099321863

Tracking bug to create them.

Any objections?

/cc @danderson

**Comment by danderson** [comment]
PR looks good. We might have to adjust the package server depending on how the distros name the riscv64 architecture. @bradfitz got any clues? I hear you have a riscv board.

**Comment by bradfitz** [comment]
In practice, all the hardware and all the distros seem to use "riscv64" (which is also the GOARCH): https://wiki.debian.org/RISC-V#Hardware_baseline_and_ABI_choice

**Comment by danderson** [comment]
Did a spot check of Fedora as a representative of the rpm world, and indeed it looks like for once they settled on the same arch names. Given that, pkgs.tailscale.com should start serving the packages at the correct location with a regular deploy.

**Comment by bradfitz** [comment]
And a report that the packages do indeed work: https://twitter.com/olofj/status/1404467123234111491

> Thanks, can confirm it works here (once I turned on netfilter and tun kernel configs, which the Unmatched didn't come with enabled by default).

**Comment by DentonGentry** [comment]
RISC-V binaries delivered starting in the 1.10 release: https://pkgs.tailscale.com/stable/#static
