### ISSUE TITLE
If an ACL permits routing a subnet through a particular node, don't require manual approval?

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2121]
Suggestion from a customer: if you have to write an ACL anyway to grant access to subnet relaying, perhaps doing that should mean subnets should be automatically approved in the admin panel without a separate step.

This is related to https://github.com/tailscale/tailscale/issues/1742, where we observe that right now, ACLs only specify subnet access, but not which nodes you're allow to route those subnets through, which is very problematic for exit nodes (since granting "exit node" access effectively grants full access to everything).

See also https://github.com/tailscale/tailscale/issues/555, which considers auto-approving subnet advertisements based on a similar mechanism to TagOwners.

To do this, we'd need a new ACL syntax that specifies not just subnets, but also which relay(s) can be used for those subnets. When used, this syntax would then auto-approve the subnets in question, from the relay(s) in question. The relays could perhaps be specified using user identifiers or ACL tags, just like identifying any other kind of machine.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3o841)

**Comment by DentonGentry** [comment]
In the meantime, the API can be used to set approved routes: https://github.com/tailscale/tailscale/blob/main/api.md#post-apiv2devicedeviceidroutes---set-the-subnet-routes-that-are-enabled-for-a-device

**Comment by DentonGentry** [comment]
From #2425:

_Currently to share a subnet, you have to run tailscale up --advertise-routes=<whatever> and then separately approve the routes in the admin panel. This is for security and privacy reasons (double opt-in). However, it makes automation more difficult, especially when used with authkeys and eg. Terraform._

_As a way to relax the restriction without creating a security risk, we could pre-grant subnet relaying permissions to particular users or tags in the ACL policy, similarly to the TagOwners section. The rule could say something like "allow ops@example.com to advertise any subnet in 10.0.0.0/8" or "allow tag:router to advertise subnets 192.168.0.0/24 or 192.168.10.0/24". If a subnet advertisement (and its owner) matches such a rule, we could skip the admin panel activation step._

**Comment by hamishforbes** [comment]
This would immediately solve the only snag I have left with Tailscale in our deployment.
Similar to #555 I am deploying tailscale nodes as relays to AWS VPC subnets, automating the authentication and configuration of subnets to each node is pretty easy but then I have this annoying extra step of having to approve the subnet relaying.

I know it can be achieved via the API now (and that's on my TODO list), but it doesn't look particularly simple or easy from the functionality available in the API.
i'd need to 
* Pass in an additional secret (api token) with more capabilities than just authorizing a node
  * Alternatively call out to another system that has those credentials, maybe a cronjob that polls the api for unapproved subnets?
* Figure out the device ID
  * is there an easy way for a tailscale node to get its own ID, machine key or IP to match against the tailnet devices response? Preferably something programmatic (e.g. a JSON response)
* Retrieve the list of advertised routes
* POST the list back to enable them

I'd love to be able to pre-approve subnets somehow, either tied to the auth key or via ACLs somehow

**Comment by rayjanoka** [comment]
@hamishforbes here is an example we use to enable routes with the API

[tailscale-enable-advertised-routes.sh ](https://gist.github.com/rayjanoka/cf91f32b3625bd28e009bb76c7198452)

**Comment by rayjanoka** [comment]
This feature would be cool because currently I have to manually rotate API keys every 90 days as that is the forced expiration.

**Comment by DentonGentry** [comment]
I think this need has been met by adding autoApprovers: https://tailscale.com/blog/auto-approvers/
