### ISSUE TITLE
MacOS built from HEAD split DNS not working

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2128]
With https://login.tailscale.com/admin/dns of:
Magic DNS enabled
Split DNS: ts-dns.test 100.120.55.47
Global DNS: 100.92.61.18 with Override local enabled

MacOS is unable to look up constantine.ts-dns.test:
```
% dscacheutil -q host -a name constantine.ts-dns.test
%
```

I was expecting to see 100.120.55.47 in the DNS configuration, but it does not appear:

```
% scutil --dns
DNS configuration

resolver #1
  search domain[0] : geekhold.com.beta.tailscale.net
  search domain[1] : ts-dns.test
  search domain[2] : localdomain
  nameserver[0] : 100.100.100.100
  if_index : 17 (utun2)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101400

resolver #2
  nameserver[0] : 2602:248:7b4a:ff60::1
  nameserver[1] : 10.1.10.1
  if_index : 12 (en0)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000

resolver #3
  domain   : geekhold.com.beta.tailscale.net.
  nameserver[0] : 100.100.100.100
  if_index : 17 (utun2)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101401

resolver #4
  domain   : ts-dns.test.
  nameserver[0] : 100.100.100.100
  if_index : 17 (utun2)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101402

resolver #5
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #6
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #7
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #8
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #9
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #10
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : localdomain
  nameserver[0] : 2602:248:7b4a:ff60::1
  nameserver[1] : 10.1.10.1
  if_index : 12 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  search domain[0] : geekhold.com.beta.tailscale.net
  search domain[1] : ts-dns.test
  nameserver[0] : 100.100.100.100
  if_index : 17 (utun2)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
```

**Comment by DentonGentry** [comment]
Possibly related: https://github.com/tailscale/tailscale/issues/2003
However the final update in that bug shows the search domain being added to the global resolver, which doesn't appear to be the case here.

**Comment by crawshaw** [comment]
Something very unusual about this bug. From my linux machine I can successfully lookup that name by querying quad100:

```
$ dig constantine.ts-dns.test @100.100.100.100
; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> constantine.ts-dns.test @100.100.100.100
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50337
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;constantine.ts-dns.test.	IN	A

;; ANSWER SECTION:
constantine.ts-dns.test. 1800	IN	A	100.120.55.47

;; Query time: 56 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Wed Jun 16 16:35:41 EDT 2021
;; MSG SIZE  rcvd: 68
```

But if I do the same from my macOS machine, quad100 does not return the path. Instead it times out!

```
$ dig constantine.ts-dns.test @100.100.100.100
; <<>> DiG 9.10.6 <<>> constantine.ts-dns.test @100.100.100.100
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Looking up MagicDNS paths like `dig monitoring.tailscale.com.beta.tailscale.net @100.100.100.100` works fine. So there's something OS-specific about quad100!

**Comment by gerred** [comment]
I'm running into this exact issue as well. Also on iOS. On Linux and Windows (both direct and via WSL2 w/ tailscaled running) it works just fine.

**Comment by DentonGentry** [comment]
Summarizing what we think the problem is:
- the NetworkExtension for MacOS has loop avoidance. We add routes for Tailscale IP addresses, but packets sent from within the Network Extension are not allowed to use routes added by the Network Extension.
- the Split DNS server we've been testing with is a Tailscale address, 100.120.55.47

To fix this, we'll need to make MagicDNS consult an internal routing table to decide whether the destination is public and it should use a MacOS socket, or whether the destination is reached via Tailscale and we need to hand the packet straight to wireguard-go. Note that the check isn't just going to be for 100.64/10, https://github.com/tailscale/tailscale/issues/1887 concerns cases using subnet relays where non-Tailscale addresses are supposed to traverse the Tailnet.

Getting the packet sent via wireguard-go is the easier part, grabbing the responses out of wireguard-go to hand back to Magic DNS is likely to be more difficult.

**Comment by dgivens** [comment]
I am having a similar issue with split DNS and override local enabled, but Magic DNS disabled. No DNS resolution works when there are any split DNS zones configured, but works as soon as I remove all split DNS zones.

**Comment by DentonGentry** [comment]
Can you say the names of the Split DNS domains and the IP addresses of those servers? You can send it via email to support@tailscale.com if you don't want to put it into a public bug report.

We have not been able to produce a symptom of all DNS failing with MacOS, the only symptom I've been able to produce is the Split DNS domain not working.

**Comment by dgivens** [comment]
@DentonGentry I emailed support with the specific IP's, domains, and examples of what I'm seeing.

**Comment by dgivens** [comment]
However, it looks like difference between when split DNS is configured and not is the nameserver on my local system changes to 100.100.100.100 when split DNS is enabled.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/2226
