### ISSUE TITLE
Exitnode is having misconfigure; it should shows up in other colour highlight to recognize easily.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2131]
In the Tailscale login page, fully active exit nodes are shown in the blue highlighted text. Still, if there’s an issue (either it’s advertised but not enabled yet, or it was previously fully active but has since stopped being advertised), a little exclamation mark icon shows up next to “Exit Node.” However, the text is still highlighted blue, so it’s easy to miss that something’s up. It would be great if there were a colour change to identify that something has changed more easily.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/2347
