### ISSUE TITLE
DERP selection problem.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2134]
Customers are reporting that there is frequent changes in derp servers. Also, a couple of customers reported that the derp selected for their location is belongs to the other part of the world, for example, a machine in NYC choosing derp in blr or Sydney for connection.

We do not find the specific logs or issue, this is to track the issue with different customers.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39ivl)

**Comment by DentonGentry** [comment]
I think this was resolved July 14th with the DERP Mesh reconfig.
