### ISSUE TITLE
Split DNS not working on a systemd-resolvconf Ubuntu system

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2136]
Using tailscale version 1.9.164 on Ubuntu 20.04, with https://login.tailscale.com/admin/dns of:
Magic DNS enabled
Split DNS: ts-dns.test 100.120.55.47
Global DNS: 100.92.61.18 with Override local enabled

resolvctl shows 100.100.100.100 as configured:

```
$ resolvectl
Global
       LLMNR setting: no
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 10.1.10.1
         DNS Servers: 10.1.10.1
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 6 (tailscale0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: no
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 100.100.100.100
          DNS Domain: geekhold.com.beta.tailscale.net
                      ts-dns.test
                      ~.

Link 4 (docker0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (eth0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 10.1.10.1
          DNS Domain: localdomain
```

Note the tilde-dot output in DNS Domains for tailscale0 really is there in the output. I don't know why.

constantine.ts-dns.test should be handled by the split DNS server at 100.120.55.47, but fails:
```
$ dig constantine.ts-dns.test

; <<>> DiG 9.16.1-Ubuntu <<>> constantine.ts-dns.test
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7904
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;constantine.ts-dns.test.       IN      A

;; AUTHORITY SECTION:
test.                   10800   IN      SOA     localhost. nobody.invalid. 1 3600 1200 604800 10800

;; Query time: 0 msec
;; SERVER: 10.1.10.1#53(10.1.10.1)
;; WHEN: Tue Jun 15 12:59:11 PDT 2021
;; MSG SIZE  rcvd: 111
```

I think this happens because /etc/resolv.conf doesn't point to either Magic DNS nor a 127.0.0.1:53 resolver to handle split DNS, it just points to the eth0 nameserver:

```
$ cat /etc/resolv.conf
# systemd-resolved
nameserver 10.1.10.1
```

**Comment by danderson** [comment]
Is this machine a container of some kind? The resolv.conf says the word "systemd-resolved", which leads us to think that systemd-resolved is in charge of DNS... but it's not, it's just a random static file with the right trigger words in it, doing something completely other. I'm a bit befuddled as to what/why/how.

**Comment by DentonGentry** [comment]
It is the same LXC container you were working with earlier today, running within Proxmox. I disabled the feature where Proxmox writes its own config to /etc/resolv.conf, so this should be what the software within the LXC is writing.

**Comment by danderson** [comment]
I have no clue what's writing this file. It's not resolved (otherwise it'd be a symlink into /run), it's not resolvconf (not installed), I don't _think_ it's NetworkManager. I'm wondering if the LXC file has just stayed put like this since you disabled the automatic feature.

I can add more logic in our DNS selection to only use resolved if the resolv.conf also points to 127.0.0.53, although that will break other corner-case configurations. So I'm eager to figure out where this resolv.conf came from.

**Comment by danderson** [comment]
For reference, if the file were actually managed by resolved, this is what it'd look like:

```
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search localdomain
```

Whereas the file on this machine is:

```
# systemd-resolved
nameserver 10.1.10.1
```

**Comment by DentonGentry** [comment]
I keep a changelog: I made Proxmox stop writing its own DNS config by creating `/etc/.pve-ignore.resolv.conf` on May 22. The /etc/resolv.conf file was created June 8. There is nothing in my Changelog on June 8, I don't know what triggered its creation.

```
$ ls -l /etc/.pve-ignore.resolv.conf
-rw-r--r-- 1 root root 0 May 22 21:22 /etc/.pve-ignore.resolv.conf
$ ls -l /etc/resolv.conf
-rw-r--r-- 1 root root 40 Jun  8 06:06 /etc/resolv.conf
```

**Comment by danderson** [comment]
Do you know where the network interface configuration comes from? It's not in /etc/network/interfaces*, not in NetworkManager. I'm wondering if that's the potential source.

Removing and rebooting would be interesting, although keep a copy of the file around and be prepared for the possibility of having no DNS when the machine comes back.

**Comment by DentonGentry** [comment]
The proxmox Network tab for this LXC says to create an eth0 with the given MAC address on vmbr0. I don't exactly know how proxmox does that, but I imagine that is where the network interface config comes from.

**Comment by danderson** [comment]
My question was more "who adds the IP address to eth0 during boot". There doesn't seem to be a DHCP client, NetworkManager isn't doing it. I assume it's some LXC-specific shell script, but I can't find it. I was wondering if whatever that thing is is also the thing setting DNS.

**Comment by danderson** [comment]
Aha, eth0 is configured by systemd-networkd, obeying DHCP. Allegedly, this should also be configuring DNS, although I _think_ it would only configure systemd-resolved and expect it to handle resolv.conf...

**Comment by danderson** [comment]
So, I'm back to the conclusion that I have no idea what set that configuration. systemd-resolved explicitly never tries to alter /etc/resolv.conf directly, systemd-networkd tells resolved about stuff, and that leaves... Someone who mangled /etc/resolv.conf and cut the other two out of the equation.

To fix up the container, the right resolved-using configuration is: `ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf , followed by `systemctl restart systemd-resolved` to make it notice that it's now in control of DNS.

**Comment by DentonGentry** [comment]
With last night's unstable release, split DNS is working:

```
$ dig constantine.ts-dns.test

; <<>> DiG 9.16.1-Ubuntu <<>> constantine.ts-dns.test
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1431
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;constantine.ts-dns.test.       IN      A

;; ANSWER SECTION:
constantine.ts-dns.test. 1800   IN      A       100.120.55.47

;; Query time: 59 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jun 16 06:39:23 PDT 2021
;; MSG SIZE  rcvd: 68
```
