### ISSUE TITLE
Windows:  auto-updates for the Windows client.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2138]
Auto-updates are essential for usability by end-users and Tough to deploy Tailscale in an organizational setting without them.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39jtd)

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/755
