### ISSUE TITLE
Update Copyright on https://login.tailscale.com/admin

### ISSUE THREAD

**Issue by war59312** [tailscale/tailscale#214]
Hi,

Don't forget to update copyright @ https://login.tailscale.com/admin ;)

I'd also forward https://login.tailscale.com/ to https://login.tailscale.com/admin .

Use a little javascript or something to have the date auto update so this wont happen again.

Thanks,

Will

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686849238288) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
Wow, never saw that before. Can we just delete that copyright in the footer, @dfcarney @crawshaw?

**Comment by dfcarney** [comment]
There's nothing on there worth copyrighting, is there? I think it's safe to remove that notice from the admin console. We might want to add it back down the road if there's material we'd be worried about people duplicating....but I can't envision what that would be.

**Comment by rosszurowski** [comment]
Closing this out since we no longer have a copyright notice on the admin panel.
