### ISSUE TITLE
MacOS from HEAD with exit node allows LAN when it shouldn't

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2153]
With a MacOS app built from HEAD (currently 85241776ed772867c8c21c17cf4af9cf9c711a82 in corp), when using an exit node with "Allow local network access" unchecked, I'm still able to reach webservers running on devices on my local LAN.

<img width="535" alt="Screen Shot 2021-06-16 at 2 41 57 PM" src="https://user-images.githubusercontent.com/1140756/122298040-1d3cf700-ceb1-11eb-8f0b-61e96b30cbf5.png">

**Comment by maisem** [comment]
Verified that this works now. Toggled "Allow local network access" while pinging to a local LAN machine.

![image](https://user-images.githubusercontent.com/3953239/122326385-a9006300-cf45-11eb-8128-625f1898b9cd.png)

**Comment by DentonGentry** [comment]
Pulled from head, rebuilt, confirmed it works now.
