### ISSUE TITLE
iOS: add DNS/routing prefs like on desktop

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2154]
Several customers noted that they would like to be able to leave tailscale on all the time, even though they are also using DNS through their PiHole at home and sometimes need to turn that off.

Regardless of the use case, it's always been odd that iOS doesn't support the same preferences settings as Windows and macOS, so we should add them.

* [ ] Allow incoming connections
* [x] Use Tailscale DNS
* [ ] Use Tailscale Subnets
* [x] New: Exit nodes: allow LAN access

**Comment by blahgeek** [comment]
> Registering my interest in the iOS app having the ability to allow LAN access on exit nodes.

FYI I found that this can be achieved by adding subnets (alongside with exit node)

**Comment by Empty2k12** [comment]
I have implemented this in https://github.com/tailscale/tailscale-android/pull/86 which can probably be cherry-picked into iOS.

**Comment by agottardo** [comment]
We just added "Allow Local Network Access" for iOS. Feature will land in the next TestFlight update.

**Comment by agottardo** [comment]
The latest version of the iOS app now available on TestFlight includes a DNS Settings view. It provides a switch to toggle Use Tailscale DNS Settings.
