### ISSUE TITLE
Android add DNS/routing prefs like on desktop

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2155]
Several customers noted that they would like to be able to leave tailscale on all the time, even though they are also using DNS through their PiHole at home and sometimes need to turn that off.

Regardless of the use case, it's always been odd that Android doesn't support the same preferences settings as Windows and macOS, so we should add them.

* [ ] Allow incoming connections
* [ ] Use Tailscale DNS
* [ ] Use Tailscale Subnets
* [x] New: Exit nodes: allow LAN access (done in https://github.com/tailscale/tailscale-android/commit/e3f71232380211b3dd3cce2c6f0f489cb054ff00)

See also https://github.com/tailscale/tailscale/issues/2154 for iOS.

**Comment by Blightwidow** [comment]
Shouldn't this be reopened as it was reverted for 12 versions now ?
