### ISSUE TITLE
Mac machine fail to connect other nodes and use exit node too

### ISSUE THREAD

**Issue by Kinghack** [tailscale/tailscale#2157]
do an upgrade of tailscale for 3 client; Mac(1.8.5)/android(1.8.6)/pi(1.8.7);

android could connect to pi and use it as exit node successfully;

but Mac couldn't. ip for Mac(10.15.7): 

100.87.176.84

Thanks.

**Comment by Kinghack** [comment]
adding the global name service. everything going well;
removing the global name service. it works for connecting to other machine; but continue fail to using exit node;

**Comment by DentonGentry** [comment]
The exit node feature as currently defined is intended for cases where one is out in public, perhaps using a public Wi-Fi hotspot, where that Wi-Fi network is not really trusted. Once enabled, all traffic goes to the exit node and access to the local LAN is blocked. If the DNS server is on the local LAN, it would no longer be accessible. We're actually about to change this in the 1.10 release, making local LAN access be optionally available with a selection in the menu bar.

In the current release, you'll need to use a global nameserver like 8.8.8.8 or 1.1.1.1. Most likely, Android is set to use a global nameserver (there are several features in Android which can cause it to switch to global nameservers).

**Comment by Kinghack** [comment]
yea. got it.
just it works well before version upgrade actually. anyway, could close issue first. 
thanks for responding quickly.
