### ISSUE TITLE
iOS: still displays the list of nodes when in Stopped state

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2160]
Steps:
- Install iOS app
- Log into a busy network
- Move the slider to Stopped state

Expected:
UI clears out everything but an option to logout/login and the start/stop slider

Actual:
UI still shows all the nodes that were in your network when you "stopped."

It's easy to understand how we got here, since we already have a list of nodes that we can still display. But on macOS and Windows, the node list disappears when stopped, so we should do the same on iOS.

**Comment by agottardo** [comment]
This was fixed in v1.46.
