### ISSUE TITLE
GRE L2/L3 tunneling protocol support

### ISSUE THREAD

**Issue by tinoue** [tailscale/tailscale#2163]
I made PR to support GRE tunneling protocol over tailscale. This supports L2/L3 tunneling over IPv4 (GRE over IPv6 is not functional because tailscale MTU is 1280 which is minimum value for IPv6).

https://github.com/tailscale/tailscale/pull/2162

**Comment by bradfitz** [comment]
Thanks! We're about to cut a 1.10 release, so we can merge this after 1.10 is out for the 1.12 release. (But there will be unstable builds out earlier)

**Comment by DentonGentry** [comment]
The 1.10 release branch was created yesterday, this feature can go into the tree (after PR review) for the 1.12 release.

**Comment by DentonGentry** [comment]
Fixed in 1.20 by https://github.com/tailscale/tailscale/commit/69de3bf7bfddb37b4c0e076c93115f82a51ec407
