### ISSUE TITLE
Windows Server 2019 RDS admin panel does not work when Tailscale is running

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#2166]
A customer reported that on Windows Server 2019, the Remote Desktop Services admin panel does not load when Tailscale is installed. I have reproduced the issue but not yet found the cause.

![image](https://user-images.githubusercontent.com/70300501/122485358-aaad4380-cfa4-11eb-9555-910ee56400ad.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39x8x)

**Comment by sailorfrag** [comment]
Poking around some more, I have a more descriptive error:
![image](https://user-images.githubusercontent.com/70300501/122485538-332be400-cfa5-11eb-89a5-93fa91bbbda3.png)

Maybe it's related to DNS.

**Comment by sailorfrag** [comment]
It fails if the Tailscale service is started (even if not logged in), and works ok with the Tailscale service stopped.

**Comment by tosie** [comment]
For some of our customers it is not just the admin panel. Also, when connecting via Remote Desktop the step "Securing Connection" takes a long time. Feels like it is running into some kind of timeout when trying to connect to a (server) local service via Tailscale IP instead of using the LAN IP.

**Comment by DentonGentry** [comment]
I think the original issue was a symptom of https://github.com/tailscale/tailscale/issues/1682, fixed in Tailscale 1.26.

@tosie regarding "For some of our customers it is not just the admin panel", please file a new bug and describe what is broken. We can't act on it without knowing what is not working.

**Comment by tosie** [comment]
What I meant probably involved #1682 as well.

I just tried to open the RDS admin panel with tailscale 1.28 on a Windows Server 2019 and it worked flawlessly. Seems like this issue has been resolved (@DentonGentry).

**Comment by DentonGentry** [comment]
Fixed at the same time as https://github.com/tailscale/tailscale/issues/1682
