### ISSUE TITLE
tailscaled.service has to be reloaded after waking from sleep

### ISSUE THREAD

**Issue by mil-ad** [tailscale/tailscale#2173]
I noticed that every time my machine wakes up from sleep I have to manually restart the `tailscaled.service` before I can connect to other machines on my tailscale network.

I'm not quite familiar with the convoluted DNS system in Linux so not quite sure what's going on but it looks some state is not restored correctly. I'm running `systemd-resolved` with `systemd-resolvconf` and  `/run/systemd/resolve/stub-resolv.conf /etc/resolv.conf` symlinked to `/etc/resolv.conf`.

Linux kernel: 5.10.44-1-lts

**Comment by DentonGentry** [comment]
Please subscribe to #1591, particularly comment https://github.com/tailscale/tailscale/issues/1591#issuecomment-850823112, for updates. systemd-networkd removes our rules after suspend/resume, we're going to need to re-install the rules whenever the network config changes.
