### ISSUE TITLE
Windows Hyper-V Server 2019  can't start Tailscale after installation

### ISSUE THREAD

**Issue by wizzard0** [tailscale/tailscale#2174]
> tailscale status

unexpected state: NoState

> tailscale up

(hangs)

> tailscale up --authkey tskey=... 

(hangs)

> tailscale-ipn.exe
```
Unable to setup Tailscale client:
walk.NewNotifyIcon: Shell_NotifyIcon
(...)
```
OS: Windows Hyper-V Server 2019 build 10.0.17763.1999

Note Hyper-V server has no GUI (well, you can RDP there but no Explorer, no taskbar etc)

Reproduces fairly easily, use a vanilla hyper-v server and run the installer (in VM, on real hardware, whatever)

**Comment by DentonGentry** [comment]
I believe this is likely the same problem as https://github.com/tailscale/tailscale/issues/2137, where Windows Server 2019 Core (with no GUI) hangs in `tailscale up` even when an authkey is used so no browser is run.

**Comment by DentonGentry** [comment]
Closing as a dup of #2137

**Comment by wizzard0** [comment]
re: dup: could we bump #2137 L1 Very Few to L2 Few? :)

**Comment by DentonGentry** [comment]
Sure. We have a pain table where these labels turn into a ranking, so it does make a difference.

We're currently trying to get a 1.10 release out in the next few days, we're not likely to make progress on Server 2019 Core & Hyper-V environment support until that is done.

**Comment by wizzard0** [comment]
Sure, no prob. Just making sure it won't get lost as otherwise Tailscale looks like an ideal solution for bridging branch office Windows networks without having to introduce some dedicated VPN cloud node/appliance.

**Comment by DentonGentry** [comment]
For anyone finding this issue later, to run Tailscale on a headless Windows Server like Hyper-V you install the Tailscale client, then in a cmd.exe or Powershell run: `tailscale up --unattended`

It will print a URL that you need to visit from a browser which is logged into the Google/Microsoft/Github/etc authenticator you use with Tailscale. It can be any machine: you don't need to figure out how to run a browser on Windows Server Core.

You can also use an authkey: `tailscale up --unattended --authkey tskey-0123456789abcdef`
You won't get a URL to visit in a browser, instead it will [use the authkey](https://tailscale.com/kb/1085/auth-keys/)

This is supported in Tailscale 1.12 and later.

**Comment by wizzard0** [comment]
Confirmed working on Hyper-V Server 2019. Thanks a lot!

**Comment by wizzard0** [comment]
Um, nope. 1.12.3 does not work for Hyper-V Server 2019. To be precise, it does work until reboot, but the key is not persisted (?), and on next reboot `tailscale status` says `Logged out` and you need to re-authenticate the machine. Both with authkey and without it.

**Comment by wizzard0** [comment]
Logout after reboot persists with 1.20.4 :(

**Comment by wizzard0** [comment]
@DentonGentry Logout after reboot on Hyper-V server 2019 persists with 1.20.4 :(

**Comment by PowershellScripter** [comment]
The unattended flag running as system account logging out upon reboot or restart of service still persists with 1.60.0 in windows
