### ISSUE TITLE
One ping issues, but this time on Linux

### ISSUE THREAD

**Issue by pnunn** [tailscale/tailscale#2176]
Hi Guys,

I think I'm hitting the old "One ping" issues again, but this time on Linux Mint rather than WSL2 as it was previously.

I'm setting up a laptop on mint and just tried connecting to a remote network via a tailscale machine which is advertising the routes and got the old, one ping then nothing routine.

I just tested it again on my WSL2 box, and no issues at all there.
`sudo tailscale version
[sudo] password for pnunn:                 
1.8.7
  tailscale commit: e1571ed7e0e84aed16f267be24fe408150109af6
  other commit: 2f595b1b68943e7c7670bb9c10147d81d034f6fd
  go version: go1.16.4-ts1b677aa
`
Any ideas what else is needed to debug?

**Comment by DentonGentry** [comment]
There are two more ping implementations at increasingly lower layers of the protocol stack. Trying these during a time when regular ping is failing would be useful.

```
$ tailscale ping 100.99.98.97
$ tailscale ping -tsmp 100.99.98.97
```

**Comment by pnunn** [comment]
OK, I have no idea what's changed, but it is all working now... I'll close this.

Thanks for the input @DentonGentry.

Peter.
