### ISSUE TITLE
MagicDNS on Windows doesn't work with `nslookup`

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#2178]
![20210620_15h45m49s_grim](https://user-images.githubusercontent.com/529003/122686468-2a265700-d1df-11eb-9c73-7de76fc26256.png)

Does `nslookup` bypass the local split DNS/Magic DNS config?

**Comment by DentonGentry** [comment]
There is a Powershell command which appears to use the full Windows resolver: https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=windowsserver2019-ps

**Comment by DentonGentry** [comment]
I don't think we can fix this, Windows nslookup's implementation is not something we control. The Powershell resolve-dnsname is an alternative which does use the Windows resolver.

Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT
