### ISSUE TITLE
Taildrop on Synology

### ISSUE THREAD

**Issue by simondarren** [tailscale/tailscale#2179]
Could not find the drop. Turned on home dir.

**Comment by DentonGentry** [comment]
The available releases are at: https://github.com/tailscale/tailscale-synology/releases

1. In the Synology DSM web admin UI, open the Package Center.
1. Press the Manual install button and provide the SPK file downloaded from https://github.com/tailscale/tailscale-synology/releases
1. Follow the wizard until done.
1. At this point tailscaled should be up and running.
1. SSH into the machine, and run sudo tailscale up to get a URL, visit this URL with a browser to authenticate the Synology NAS.

**Comment by bradfitz** [comment]
I interpreted the super-minimal bug report about being unable to find the files Taildropped to a Synology NAS.

@simondarren, could you elaborate?

**Comment by simondarren** [comment]
ty @bradfitz yes.  

@DentonGentry I have it running on my Synology fine. I just could not locate the taildrop. I get no error on the drop, I see nothing in the synology logs.

**Comment by bradfitz** [comment]
Only on Mac and Windows do we automatically put the files somewhere useful.

On Linux (which includes Synology) they remain in the tailscaled-owned /var directory until they're "picked up".

But I suppose we could/should do something better on Synology, perhaps moving them to the user's home directory, or a "Tailscale" subdirectory thereof.

**Comment by jpm** [comment]
@bradfitz I don't know how much you guys are willing to customize this behavior on Synology, but it would be very nice if there was some configuration parameter so users can set the location for the drops. I would perhaps choose my existing "Downloads" shared folder, maybe on a "Tailscale" subdirectory or something.

We could then add the write permission to the `tailscale` user on that shared folder, and it's all set up. That would allow the software to inject the files into the "regular" flow of how files are stored / shared within DSM.

**Comment by jpm** [comment]
@bradfitz That sounds great.

**Comment by bradfitz** [comment]
Sent https://github.com/tailscale/tailscale/pull/3525 implementing this.

**Comment by DentonGentry** [comment]
Fixed in the 1.18.2 Synology release by https://github.com/tailscale/tailscale/commit/6c44133d8f1cfe06c33ac924daf425d8dc7f5fab. You can sideload it from https://github.com/tailscale/tailscale-synology/releases now, or we expect it to appear in the Package Center in (hopefully) January.
