### ISSUE TITLE
Astroturfing on HN

### ISSUE THREAD

**Issue by gh67uyyghj** [tailscale/tailscale#218]
How do you guys manage to do such an extensive astroturfing on HN? I knew that DDG had insiders and do organized upvoting for their posts. But I've never seen anything like you're doing, people pay hundreds of thousands for less effective advertising. I am really stunned, especially with a low quality project like yours can milk HN so much.

**Comment by crawshaw** [comment]
This is a repeat of #217, and as I wrote there, it is inappropriate content for the issue tracker.
