### ISSUE TITLE
Multi-user Android devices cannot connect, VpnService.Builder lacks android.permission.INTERACT_ACROSS_USERS

### ISSUE THREAD

**Issue by JPoid** [tailscale/tailscale#2180]
I have Tailscale set up on a Samsung Galaxy Tab S3 (SM-T820) running Android 9.

I can open the app, login fine and can see my other devices listed like normal. When I first try to connect, I get a message "Connection Request: Tailscale is requesting to setup a VPN connection that will allow it to monitor the network traffic. Only allow this if you trust the source." I click "OK" to allow it. Whenever (including this first time) I go to active the VPN using the button at the top left, it flickers to "Starting..." then "Active" and then "Stopped".

Tailscale shows up as a VPN under Settings > Connections > More connection settings > VPN

I have it working on other Android devices fine - so can't figure out why it doesn't work for this device. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3a55d)

**Comment by DentonGentry** [comment]
(From followup emails, there are two accounts on this device)

The main error is: `VpnService.Builder.establish: java.lang.SecurityException: getPackageUid: Neither user 10258 nor current process has android.permission.INTERACT_ACROSS_USERS.`

android.permission.INTERACT_ACROSS_USERS is a system permission, not one we can request in the manifest. I'm not sure we can address this issue.

**Comment by JPoid** [comment]
So the latest Android update (1.10.0 - "Fix MagicDNS forwarding #2102") fixed the issue and it is now working fine. Thanks.

**Comment by DentonGentry** [comment]
...it did?

Ok. I've no idea how, but ok.

**Comment by andrew-d** [comment]
Updating this bug with more information: this appears to be a bug in Android on some devices with multiple users. As Denton mentioned above, the `INTERACT_ACROSS_USERS` permission is a system permission and not something we can request in the manifest. Some searching shows that other projects have the same error:
* https://github.com/trojan-gfw/igniter/issues/238
* https://git.frostnerd.com/PublicAndroidApps/smokescreen/-/issues/245
* https://github.com/AdguardTeam/AdguardForAndroid/issues/173
* https://github.com/TrackerControl/tracker-control-android/issues/124

This issue provides more information on the underlying cause and has mention of an `adb` command that could be used to manually grant this permission to the Tailscale app, which we not tested but may be an option:
https://github.com/AdguardTeam/AdguardForAndroid/issues/3299#issuecomment-667160839

I've sent [a PR](https://github.com/tailscale/tailscale-android/pull/65) that attempts to detect this error and will show a message pointing users to this GitHub issue.
