### ISSUE TITLE
Windows doesn't show all devices in the right click menu

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#2181]
![image](https://user-images.githubusercontent.com/529003/122790931-c6576900-d286-11eb-8e5c-beb41bd2d877.png)

This should show many other devices in the network, not just the ones that run windows.

**Comment by darshinimashar** [comment]
@Xe which version of Tailscale?

**Comment by DentonGentry** [comment]
This is related to LastSeen, which doesn't update as frequently in 1.10 as it previously did.
Windows needs to use LastSeen || Online, a similar fix was applied in the MacOS Swift code.

**Comment by bradfitz** [comment]
The definition of LastSeen changed slightly recently: #2107

LastSeen is now only sent & updated for offline nodes, saying when they were last online.

**Comment by darshinimashar** [comment]
On Tailscale Unstable: 1.9.185. Does not shows the My Devices option, as well as the devices, show under the tailnet user are only windows one or macOS with 1.8 or higher version.

**Comment by DentonGentry** [comment]
<img width="502" alt="Screen Shot 2021-06-22 at 3 12 11 PM" src="https://user-images.githubusercontent.com/1140756/123006281-473c6080-d36c-11eb-819e-d81700a7320f.png">
