### ISSUE TITLE
Exit node IPv6 is broken on Windows 7 64 bit

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#2182]
![20210621_11h52m42s_grim](https://user-images.githubusercontent.com/529003/122791622-631a0680-d287-11eb-8bbc-41c35b0a76a1.png)

**Comment by judge2020** [comment]
My exit node supports v6:

```
$ ping6 dns.google -c 4
PING dns.google(dns.google (2001:4860:4860::8888)) 56 data bytes
64 bytes from dns.google (2001:4860:4860::8888): icmp_seq=1 ttl=116 time=7.65 ms

$ tailscale netcheck
Report:
        * UDP: true
        * IPv6: yes, [2600::]:55784
```
(truncated my ipv6 for privacy)

On the Windows box:
```
> ping 2001:4860:4860::8844

Pinging 2001:4860:4860::8844 with 32 bytes of data:
Request timed out.

>tailscale ip
100.88.4.77
fd7a:115c:a1e0:ab12:4843:cd96:6258:44d

```


Exit node bugreport `BUG-8879607fe31d7229ba6cefd70ef9405b211f067c98b514088d2a2118a350ded9-20210904025749Z-1fb05f9a7ed37ca8`

Windows bugreport `BUG-9a36c646311ce9381728176468601d7ab06e0adea0acc0b6300a465665120dd9-20210904025723Z-09294694aa8e1037`

**Comment by DentonGentry** [comment]
The problem in the original report is that Google Public DNS is 2001:4860:4860::8888, not 2001:...

Windows 7 IPv6 through an exit node is working now.

<img width="779" alt="Screen Shot 2022-10-30 at 4 31 30 AM" src="https://user-images.githubusercontent.com/1140756/198876379-f55ee179-5333-45fd-bad8-14bb8a1fe6d2.png">
