### ISSUE TITLE
218+ SEGFAULT with no restart of daemon

### ISSUE THREAD

**Issue by dustin-hawkins** [tailscale/tailscale#2203]
**Description**

I've noticed that TailScale will suddenly stop on my DS218+. Looking at the logs, it seems to segfault, and does not autorestart. 

Attached are logs, would it be possible to have the process auto-restart on non-zero exit code? 

**Steps to reproduce**
```
2020/08/23 07:07:14 magicsock: closing connection to derp-1 (idle), age 4m18s
2020/08/23 07:07:14 magicsock: 1 active derp conns: derp-2=cr4s,wr4s
2020/08/23 07:07:34 magicsock: starting endpoint update (periodic)
2020/08/23 07:07:36 netcheck: netcheck: no IPv4 UDP STUN replies
2020/08/23 07:07:36 netcheck: udp=false v6=false mapvarydest= hair= derp=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x884b78]

goroutine 25596 [running]:
tailscale.com/wgengine/magicsock.(*Conn).setNearestDERP(0xc0001009a0, 0x9, 0xc000591d00)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:474 +0x188
tailscale.com/wgengine/magicsock.(*Conn).updateNetInfo(0xc0001009a0, 0xaaa640, 0xc002a44180, 0x0, 0x0, 0x0)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:356 +0x379
tailscale.com/wgengine/magicsock.(*Conn).determineEndpoints(0xc0001009a0, 0xaaa5c0, 0xc00001eac0, 0x1, 0x1, 0xc001604358, 0x8a3300, 0x8a89e6, 0xc0001006e0)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:498 +0x5d
tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints(0xc0001009a0, 0x9dfe30, 0x8)
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:297 +0x125
created by tailscale.com/wgengine/magicsock.(*Conn).ReSTUN
        /home/dave/tail/corp/oss/wgengine/magicsock/magicsock.go:1446 +0x1ee

```

**Expected behavior**

A restart of the service on an unexpected exit.	

**Synology NAS model**
E.g. DS218+

**Comment by DentonGentry** [comment]
There have been a number of updates to the Synology release package since this was filed, is it still happening?
I think this was likely https://github.com/tailscale/tailscale/issues/2129

Barring further updates, we'll expect to close this during the next bug scrub.

**Comment by jucor** [comment]
Tailscale has been running very smoothly on my DS218+ for a long while now :)
But I doubt it was #2129: DS218+ , unlike DS218j, is not an ARM architecture, but a Celeron, x86_64.
In any case, not a problem anymore that I can see!
