### ISSUE TITLE
Upload packages to Package Center?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2207]
Do you want us (@Tailscale) to do the various Synology paperwork and start uploading these builds to the Package Center so users don't need to do manual installs?

We can also help contribute to this repo here, or we can move it under the tailscale org too (with history, and you can keep access/contributing)?

Let us know what you'd like and how we can help.

Personally I've love to see it included in the Package Center by default.

**Comment by DentonGentry** [comment]
Done. https://www.synology.com/en-us/dsm/packages/Tailscale
