### ISSUE TITLE
 /sbin/tailscale: /sbin/tailscale: cannot execute binary file

### ISSUE THREAD

**Issue by talway** [tailscale/tailscale#2209]
**Description**
/sbin/tailscale: /sbin/tailscale: cannot execute binary file
**Steps to reproduce**

 sudo tailscale up
/sbin/tailscale: /sbin/tailscale: cannot execute binary file

**Expected behavior**
/sbin/tailscale: /sbin/tailscale: cannot execute binary file

**Synology NAS model**
esxi  j3455 install 
uname -a
Linux nas-esxi 3.10.105 #23739 SMP Sat May 19 03:23:49 CST 2018 x86_64 GNU/Linux synology_broadwell_3617xs
DS3617xs
DSM 6.2-23739
use https://github.com/nirev/synology-tailscale/releases/tag/v1.2.10

**Comment by DentonGentry** [comment]
There have been several updates of the Synology release since this was filed, is there still a problem?

Barring further updates, we'll plan to close this during the next bug scrub.
