### ISSUE TITLE
magicsock: seeing IPv6 roaming from fe80:...%ens18 

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#221]
We currently don't add IPv6 interface addresses to our endpoints. (Only the STUN-discovered IPv6 global address.)

But I just saw this in my logs:

```
2020/03/25 08:54:59 magicsock: rx [5v1Zt] from roaming address [fe80::1cc0:3e8b:119e:c2e1%ens18]:53823, set as new priority
```

Two IPv6 VMs on my LAN over their global IPv6 addresses, but a reply came over the `fe80` link-local address, which was unknown to magicsock, so it went into roaming mode.

Perhaps we should add the interface link-local IPv6 addresses to endpoints. (Do we need to do the whole %zone thing too or can we ignore that and not send it to tailcontrol?)

/cc @danderson

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686740189991) by [Unito](https://www.unito.io/learn-more)

**Comment by crawshaw** [comment]
I believe zones are necessary. If you hand a machine an ipv6 link-local address without a zone and say "send a packet to it", the machine does not know which of its network interfaces to send the packet over.

**Comment by bradfitz** [comment]
Oh, right.

**Comment by danderson** [comment]
Yeah, link-local is, well, link-local :) Potentially overlapping namespaces on each L2 segment.

Peering over link-local where available would be fairly slick, although it will require us to carry a full https://golang.org/pkg/net/#UDPAddr or equivalent around with us (note the Zone field).

**Comment by danderson** [comment]
It's not clear to me how we managed to end up roaming to a link-local address though, if magicsock is not spreading those. How did we end up transmitting from that addr?

**Comment by bradfitz** [comment]
Our udp6 listener is just bound to `:0` and not a particular address/interface. So perhaps when we sent to the global IPv6 address, the kernel had a more specific link-local route for that global address? (I'm totally guessing.)

**Comment by danderson** [comment]
We ended up stripping out v6 link-local addresses from the endpoints list for now. Also, active discovery happened after this bug, so behavior is now entirely different and this is N/A.
