### ISSUE TITLE
Synology: ARM manual install/upload to SRM (DSM 5.2 or earlier) is missing digital signature

### ISSUE THREAD

**Issue by poswald** [tailscale/tailscale#2219]
**Description**

I'm trying out the 1.8.3 package on an MR2200ac router running SRM

**Steps to reproduce**

1. In package center, click manual install
2. choose the `tailscale_1.8.3_arm.spk` file downloaded from the releases page.
3. Click "Next"
4. Error: "This package does not contain a digital signature"
<img width="397" alt="image" src="https://user-images.githubusercontent.com/49721/119095967-ed373b00-ba4d-11eb-80bf-b332df5da436.png">

**Expected behavior**

this process worked for me on a Synology NAS.

**Synology Router model**

MR2200ac router running SRM 1.2.4-8081 Update 2

**Comment by angyen** [comment]
I tried to install in SRM as well on my RT1900ac but it failed to install. 
@john-jz How to change compression parameter? Have you got it works in your RT1900ac?

**Comment by john-jz** [comment]
> I tried to install in SRM as well on my RT1900ac but it failed to install.
> @john-jz How to change compression parameter? Have you got it works in your RT1900ac?

@angyen :
Oops! Sorry, didn't think to mention it at the time.

Edit line 80 in build-package.sh:

From:   `ls --color=no "$tmp_dir" | tar -cJf $dest_pkg -C "$tmp_dir" -T /dev/stdin`

To:    `ls --color=no "$tmp_dir" | tar -czf $dest_pkg -C "$tmp_dir" -T /dev/stdin`

Then compile!

This will allow you to get past the "Invalid file format." error message, but will still face the other issues that I [mentioned](https://github.com/tailscale/tailscale/issues/2219#issuecomment-846282859).

**Comment by angyen** [comment]
@john-jz thanks for the swift reply and clear guide. hopefully the other issues will be sorted out soon.

**Comment by DentonGentry** [comment]
To set expectations, I do not expect to add support for DSM versions prior to DSM6.

**Comment by DentonGentry** [comment]
Closing, won't fix.

**Comment by poswald** [comment]
Just as an update to anyone who tracks this issue... I previously contacted Synology and they wouldn't confirm/deny anything about SRM updates to me. Yesterday, during their conference they announced new hardware coming in Q1 2022 which would [include a new SRM 1.3 version](https://www.blackvoid.club/2022-and-beyond-event-news/) with many new features.

I have not yet found any indication that this version is based on DSM7 or have the updated packaging system but I suspect it would be.

> SRM 1.3 will debut on the RT6600ax router in Q1 2022. Support for RT2600ac and MR2200ac will be added in Q2 2022.

So it might be possible to get a beta version and revisit this issue soon.
