### ISSUE TITLE
Offer the option of not logtailing via disk

### ISSUE THREAD

**Issue by ethulhu** [tailscale/tailscale#2221]
The Tailscale client on Linux logs using 2 files ([`tailscaled.log1.txt` & `tailscaled.log2.txt`](https://github.com/tailscale/tailscale/blob/38be964c2bfc650a69a5c92b75185eac94b388ae/logtail/filch/filch.go#L131)), repeatedly writing to them then truncating them. These are currently put in the systemd [`$STATE_DIRECTORY`](https://github.com/tailscale/tailscale/blob/38be964c2bfc650a69a5c92b75185eac94b388ae/logpolicy/logpolicy.go#L131).

To reduce disk IO for systems that need it (e.g. Raspberry Pis with dodgy SD cards), can it be easily configurable to put those two files somewhere else (e.g. `$CACHE_DIRECTORY`? settable via some flag?). This way they should still persist between tailscale restarts, but not touch physical disk.

PS: Thank you for teaching me the correct plural, "systems d" 😄

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1463
