### ISSUE TITLE
Windows 8.1: DNS search paths don't work when in split DNS mode

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2237]
Version: 1.8.7 and 1.9.204

BUG-0add4d7ac11f97bb8bad885f2dc3952547b8d15a846b8638c21d34d3c3017a9f-20210624001246Z-c7cbbafb2768b24f

`ping flow` or visiting `http://flow` from IE in my Windows 8.1 test VM fails the DNS lookup when DNS is configured with "Override local DNS" == false. When I set it to true, it works.

In both modes, if I enter the full hostname `flow.tailscale.com.beta.tailscale.net` it works fine.

Windows 7 and 10 work in both modes.

Tailscale v1.6.0 works on Windows 8.1 in both modes (but because it didn't support split DNS, it's effectively just using the global DNS setting in v1.6.0 I assume).

Technically a regression, but almost nobody uses Win8.1.

**Comment by apenwarr** [comment]
confirmed fixed in v1.9.205

**Comment by realyukii** [comment]
Hello, do you know what Tailscale version for Windows 8.1 and where to download it?

**Comment by realyukii** [comment]
I'm planned to build the tailscale from source, however I'm [informed](https://github.com/juanfont/headscale) that the source code for proprietary OS is closed:
> Everything in Tailscale is Open Source, except the GUI clients for proprietary OS (Windows and macOS/iOS), and the control server.
