### ISSUE TITLE
Subnet relays don't work for iOS clients when using mobile data

### ISSUE THREAD

**Issue by tanuck** [tailscale/tailscale#2238]
Hi,

I've previously spoken to @DentonGentry about this via email.

We've noticed this week that iOS devices aren't able to reach resources via any subnet relays on our tailscale network when disconnected from Wifi and using the carrier network. On Wifi everything works fine. I've had a brief look at the routing table on my device and I haven't spotted any overlaps (I will send this info to support via email so someone can double-check). I've confirmed that this affects every subnet relay on our network, and all ranges that are advertised.

So far we've confirmed this on the following devices:
- iPhone XR, iOS 14.6, tailscale 1.8.7
- iPhone 11, iOS 14.6, tailscale 1.8.7

Cheers

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3azpt)

**Comment by tanuck** [comment]
Just confirmed that this issue still persists on iOS after updating to 1.10.

**Comment by apenwarr** [comment]
We corrected a DERP relaying issue yesterday that might be related to this. Can you retry? You shouldn't need to upgrade your client software.

**Comment by DentonGentry** [comment]
I think this was resolved via DERP update in 7/2021.
