### ISSUE TITLE
Allow changing names of services

### ISSUE THREAD

**Issue by doamatto** [tailscale/tailscale#2240]
So far, I'm enjoying the services tab. It would be great to see an addition to rename services in the future. The main reason is, in the case of things such as Docker, you'll have `com.docker.backend` or similar for all of your containers, which can make things confusing in terms of then remembering which port corresponds to which container.

**Comment by DentonGentry** [comment]
I think this is covered in https://github.com/tailscale/tailscale/issues/2516, which has had a bit more discussion.
