### ISSUE TITLE
cmd/tailscale: 'tailscale netcheck' should use current DERP map, if available

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2249]
As part of #1264, the `cmd/tailscale netcheck` subcommand should be updated to prefer to use the currently-running tailscaled's active DERP map, instead of the baked-in fallback one (that's currently only used for `netcheck`). Perhaps we even remove it, and if tailscaled is not running, we ask the default control plane server for one.

**Comment by bradfitz** [comment]
Also, some command to just dump out the full map as JSON probably. Perhaps as a `tailscale debug` subcommand/flag.

**Comment by JulianKnodt** [comment]
Initial issue fixed in #2253, will add a `tailscale debug` subcommand
