### ISSUE TITLE
Add UI to allow access to the local LAN with exit node on Windows

### ISSUE THREAD

**Issue by cepera-ang** [tailscale/tailscale#2250]
Hello, the latest version (1.10) release note says that there should be Windows specific addition: 

> add UI to allow access to the local LAN while using an exit node

I'm updated to that version and the new UI option is nowhere to be found (I tried to look in the menu and in admin console).

It would be great to have this option available and on related note, there probably should be a remark in documentation on exit nodes that activating one cuts almost all LAN traffic (it was unpleasant surprise to cut home server from all other devices by activating exit node).

**Comment by DentonGentry** [comment]
We made a mistake, the Windows UI update isn't in the release. I've removed it from the release notes. We expect to be able to add that function soon.

**Comment by cepera-ang** [comment]
Thanks for the clarification. I thought it might be the case. Well, wait for the actual release with that fuction then.

**Comment by DentonGentry** [comment]
In the 1.12 release Windows now has an "Allow local network access" item in the exit node menu.

<img width="554" alt="Screen Shot 2021-07-30 at 10 13 29 PM" src="https://user-images.githubusercontent.com/1140756/127730956-a4df5686-7570-43d0-a9be-05cb3c9b61b8.png">
