### ISSUE TITLE
Multiple global IPs in Endpoint list of a node

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#2255]
Currently any node only has one global IPv4 and one IPv6 listed in its endpoint list. If I'm in a big enterprise with multiple internet connections, I might use different public IP addresses when connecting to different peers. 

Say I'm connecting to peer A with public IP a and connecting to peer B with public address b at the same time. My endpoint list will look like this: [a, 192.168.x.x, ...]. When B sees this list it will try to connect through IP a, which may not be optimal or even worse can't connect.

Could we add multiple IPv4/IPv6 endpoint to node endpoint list?

**Comment by DentonGentry** [comment]
Do you mean the endpoints listed in https://login.tailscale.com/admin/machines/w.x.y.z, the public IP addresses at which a node can be reached?

It already does allow multipathing. For example this is a node with two WAN links which is reporting the IPv4 and IPv6 addresses of each WAN link, plus the two 10.x.y.z LAN addresses it has.

<img width="205" alt="Screen Shot 2021-06-26 at 1 11 12 AM" src="https://user-images.githubusercontent.com/1140756/123506899-71677a00-d61b-11eb-879e-762708f0e063.png">

**Comment by awsong** [comment]
Yes I did mean that.  Maybe I was looking at the wrong place in the code base. 

I was looking at [here](https://github.com/tailscale/tailscale/blob/main/wgengine/magicsock/magicsock.go#L1012). Seems only one global IPv4 and one IPv6 address is added to the endpoint list.

**Comment by awsong** [comment]
Some observation: 
I have a node (100.122.76.55) that's behind a router which may route some packets through transparent proxy. When I run `tailscale netcheck` command and `tailscale status -json` command, sometimes the IPv4 address reported by netcheck is not included in the "Addrs" list of status command. 
![9751624845221_ pic_hd](https://user-images.githubusercontent.com/787544/123568978-150d8180-d7f8-11eb-9bbe-e78306137dd0.jpg)
![9761624845223_ pic_hd](https://user-images.githubusercontent.com/787544/123568986-19d23580-d7f8-11eb-87c1-fb9eea2bb66f.jpg)
![9771624845226_ pic_hd](https://user-images.githubusercontent.com/787544/123568996-1ccd2600-d7f8-11eb-9723-b1c357abc4a4.jpg)

**Comment by bradfitz** [comment]
`tailscale netcheck` doesn't include interface addresses. It only shows the STUN-discovered ones.

**Comment by awsong** [comment]
But should `tailscale status -json` show IP addresses discovered by STUN? If yes, then an IP address shown in netcheck will also show up status output.

**Comment by bradfitz** [comment]
I think this is a dup of #1066 and/or #2256, to use+STUN over multiple links. I'm going to close this one.
