### ISSUE TITLE
Android Hotspot traffic does not go through exit node

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2259]
With Android configured as a Wi-Fi hotspot with clients connected, traffic from the clients goes straight to the LTE network and does not go to the exit node. Traffic generated from Android apps goes through the exit node.

Need to evaluate whether this is what is expected or desired.

**Comment by Erisa** [comment]
Hotspot traffic on Android by default bypasses any VPN application. I believe this intended, I just don't know why.

Some (very few) ROMs/derivatives/skins of Android include an extra setting (Called something like "Allow clients to use VPNs") which reverses this behaviour and routes Hotspot traffic over the VPN.

As far as I'm aware from an app point of view there isn't anything that can be done about this. The only applications that bypass this behaviour require root access on the Android device.

A lot of this is from my memory and personal experiences, but a couple sources that support my claims can be found at
https://protonvpn.com/support/share-vpn-connection-android-hotspot/ (they say theres nothing they can do)
https://www.xda-developers.com/vpn-hotspot-share-vpn-connection/ (root app that lets you bypass restriction)
https://review.aosip.dev/plugins/gitiles/AOSIP/platform_packages_apps_Settings/+/2a072b450daa80386aeb6170a519413f7983e50c/res/values-ar/aosip_strings.xml#57 (the Settings string, its present in other forks of Android but this is the first one i could find)

Hope it helps! Sorry I can't give more information than just that.

**Comment by DentonGentry** [comment]
Thank you @Erisa !

We got a similar indication from a different source, indicating that there are too many instances of accidentally giving (for example) the kids in the backseat with their iPads access to corporate resources. Having tethered Wifi go to the underlying cell network and not the VPN is deliberate, and not something Tailscale can easily change.

I'm going to close this now, the issue can serve as documentation for anyone searching about it.
