### ISSUE TITLE
Customer is failing to upgrade from Connectivity plan to team plan.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2263]
The customer tries to upgrade to the new team plan instead of the legacy Connectivity plan, but he gets the following error when he tries to do so.

---
Error: currencyDisplay must be either "code", "symbol", or "name"
An unknown error occurred. You can refresh the page to try again, or if the error continues, please contact us for help.

---

When he refreshes the page, the error returns.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3b5ch)

**Comment by rosszurowski** [comment]
This sounds like a browser support issue. We’re using [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format) with a property their browser doesn’t support. I was under the impression this API was widely supported by all browsers, so I'll have to see what's not working and why.

**Comment by rosszurowski** [comment]
Looks like this issue [affects Safari users](https://github.com/mdn/browser-compat-data/issues/8985), where versions less than 14.1 don't support the `currencyDisplay: "narrowSymbol"` property, but this isn't evident from MDN. I've made a fix to our admin panel code, which we'll deploy shortly here.
