### ISSUE TITLE
Support Subnet Routes In userspace-networking Socks5 Proxy

### ISSUE THREAD

**Issue by alex-richman-onesignal** [tailscale/tailscale#2264]
Currently when running in the userspace-networking mode the Socks5 server only supports proxying connections to Tailscale IPs (and external IPs, see https://github.com/tailscale/tailscale/issues/1617).  The server should be able to proxy to subnet routes advertised to the tailscale network by other nodes.

There's a comment in the codebase to this effect already:
https://github.com/tailscale/tailscale/blob/088b90b15f4a3b18b0938f04b9c08e979f9381bb/cmd/tailscaled/tailscaled.go#L254

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3b85t)

**Comment by jakedgy** [comment]
This could be a workaround for Tailscale devices that accept routes within an advertised subnet (https://github.com/tailscale/tailscale/issues/2590).

You pick up a bit more control in that you get to decide if network traffic is even sent to the proxy.
