### ISSUE TITLE
Disable setBypassMark In userspace-networking Mode

### ISSUE THREAD

**Issue by alex-richman-onesignal** [tailscale/tailscale#2265]
So far as I understand from the codebase, the tailscaleBypassMark config is to paint packets flowing through the Linux route tables to avoid sending packets back out to the tailscale network and creating loops etc.

Is this still required for userspace-networking mode, which does not configure any Linux route tables?

If it can be removed then tailscaled with userspace-networking will no longer require CAP=NET_ADMIN which will make it usable in a completely unprivileged environment.

I've tested a custom build locally (just commenting out the SetsockoptInt lines) and this seems to work fine for outbound traffic.

**Comment by DentonGentry** [comment]
The implementation we've been working on puts the support in net/netns. If neither SO_MARK nor SO_BINDTODEVICE succeeds, then have it fall back to just Dial/Listen a socket in the regular way. This allows it to work without CAP_NET_ADMIN.

**Comment by bradfitz** [comment]
@alex-richman-onesignal, are you running as UID 0 without CAP_NET_ADMIN?

Because if you're not running as UID 0, we ignore the netns sockopt failures.

**Comment by alex-richman-onesignal** [comment]
@bradfitz, currently running as an unprivileged user (1001), with CAP_NET_ADMIN.  Ideally would like to run as the same unprivileged user without CAP_NET_ADMIN.

The context here (and for https://github.com/tailscale/tailscale/issues/2264) is that I'm configuring a docker env in CI that needs to hit some resources on our internal subnet.  We have a separate tailscale node advertising routes to the internal subnet.

Our CI does not support /dev/net/tun passthrough (hence userspace-networking), and I would like the image to run as unprivileged as possible (hence UID 1001, no CAP_NET_ADMIN).

Thanks!
- Alex.

**Comment by bradfitz** [comment]
If you're not running as uid 0, then we don't make the sockopt failure a fatal error. It's not even logged it looks like.

So back up: what doesn't work today?

**Comment by alex-richman-onesignal** [comment]
@bradfitz Sorry, you are correct - I've retested locally and with non-root, no CAPs this does work without issue.  I suspect I was getting mixed up with some k8s config and the Socks5 routing issues raised ealier.

Thanks,
- Alex.
