### ISSUE TITLE
Installing tailscale-synology 1.10.0 double installed builds for Intel/AMD/ARM

### ISSUE THREAD

**Issue by Markmaster** [tailscale/tailscale#2266]
On my three Synology NAS, I install the new build and I can see that the app is doubled in DSM.

NAS models:
DS1621+ - tailscale-x86_64-1.10.0-001-dsm6.spk
DS918+ - tailscale-x86_64-1.10.0-001-dsm6.spk
DS416 - tailscale-armv7-1.10.0-001-dsm6.spk
DSM version: 
DSM 6.2.4-25556

<img width="344" alt="CleanShot 2021-06-28 at 18 26 53@2x" src="https://user-images.githubusercontent.com/4227967/123663507-229a2a00-d83f-11eb-9a50-526cd3a18d52.png">
<img width="784" alt="CleanShot 2021-06-28 at 18 27 04@2x" src="https://user-images.githubusercontent.com/4227967/123663511-23cb5700-d83f-11eb-92cb-f093b005187c.png">
<img width="753" alt="CleanShot 2021-06-28 at 18 27 14@2x" src="https://user-images.githubusercontent.com/4227967/123663513-2463ed80-d83f-11eb-8791-00f3848bc368.png">

**Comment by bradfitz** [comment]
That might be expected due to some app metadata changes as we prepare to get into the Synology Package Center.

You probably need to uninstall the old one first.

/cc @crawshaw @maisem

**Comment by Markmaster** [comment]
> That might be expected due to some app metadata changes as we prepare to get into the Synology Package Center.
> 
> You probably need to uninstall the old one first.
> 
> /cc @crawshaw @maisem

@bradfitz at first my congratulation if you can enter in Synology Package Center. It's a big move.
Do I need to uninstall both apps and install the new one, which is signed by TailScale? Or just remove the previous build?
Maybe it's better to add some readme to 1.10.0 Release, to uninstall the previous build, before installing this, current one?

**Comment by DentonGentry** [comment]
Please remove the previous build.

The Tailscale package is now available in the Synology package center: https://www.synology.com/en-us/dsm/packages/Tailscale

**Comment by Hk92a** [comment]
> On my three Synology NAS, I install the new build and I can see that the app is doubled in DSM.
> 
> 
> 
> NAS models:
> 
> DS1621+ - tailscale-x86_64-1.10.0-001-dsm6.spk
> 
> DS918+ - tailscale-x86_64-1.10.0-001-dsm6.spk
> 
> DS416 - tailscale-armv7-1.10.0-001-dsm6.spk
> 
> DSM version: 
> 
> DSM 6.2.4-25556
> 
> 
> 
> <img width="344" alt="CleanShot 2021-06-28 at 18 26 53@2x" src="https://user-images.githubusercontent.com/4227967/123663507-229a2a00-d83f-11eb-9a50-526cd3a18d52.png">
> 
> <img width="784" alt="CleanShot 2021-06-28 at 18 27 04@2x" src="https://user-images.githubusercontent.com/4227967/123663511-23cb5700-d83f-11eb-92cb-f093b005187c.png">
> 
> <img width="753" alt="CleanShot 2021-06-28 at 18 27 14@2x" src="https://user-images.githubusercontent.com/4227967/123663513-2463ed80-d83f-11eb-8791-00f3848bc368.png">

**Comment by DentonGentry** [comment]
The Synology package center's current release is 1.16.
The 1.22 release is available at https://pkgs.tailscale.com/stable/#spks
Please try one of those, not 1.10.
