### ISSUE TITLE
Support Socks5 Ipv4 Subnet Routes Over Exclusively Ipv6 node (e.g. Ephemeral Nodes)

### ISSUE THREAD

**Issue by alex-richman-onesignal** [tailscale/tailscale#2268]
Somewhat related to https://github.com/tailscale/tailscale/issues/2264
Also related to https://github.com/tailscale/tailscale/issues/1952

When using an ephemeral key to authenticate a node it only assigns an Ipv6 address (no Ipv4 address).  This is sensible to avoid Ipv4 exhaustion (as noted in #1952), and it makes sense that in this mode you would not be able to directly hit Tailscale Ipv4 addresses.

However, it would be useful if when using the Socks5 proxy it would transparently proxy to both the Ipv4 Tailscale addresses and (re #2264) allow routing to advertised Ipv4 subnet routes.  This is key when using userspace-networking + socks5 proxy in a CI environment where you are authenticating with ephemeral keys.

**Comment by bradfitz** [comment]
FWIW, we've been rethinking the ephemeral-nodes-are-IPv6-only restriction. We think we can make IPv4 also work with them, using a pool of IPv4 addresses that all networks can share, as long as those ephemeral nodes aren't shared between networks. We might start by disabling sharing ephemeral nodes, but later we could just make sharing ephemeral nodes only share the globally unique IPv6 address, and their IPv4 would only work within owner's tailnet.

But in the meantime, this looks fixable.

**Comment by bradfitz** [comment]
Oh, we even fail to select the right IP address when you connect via hostname.

We should at least let you use the MagicDNS hostnames and select the IPv6 address of it when the local node only has an IPv6 address.  (But we can also support connecting to the IPv4 address, mapping it to the corresponding IPv6 address)

**Comment by bradfitz** [comment]
@alex-richman-onesignal, it's a bit better now. It at least resolves DNS names to the appropriate address family now.

More later.

**Comment by bradfitz** [comment]
@alex-richman-onesignal, https://github.com/tailscale/tailscale/pull/2808 is now submitted too, fixing the DNS issue looking up IPv6-only nodes in the non-SOCKS case.

**Comment by DentonGentry** [comment]
We now provide IPv4 addresses for ephemeral nodes. It was a sharp edge in the product: people would spin up an ephemeral node and tell it to contact 100.x.y.z, and it didn't work. I don't expect to add cases in the near future where a Tailscale node would have only an IPv6 address.

As such: I don't think this needs to be resolved at this point. Barring further comments, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
Closing during bug scrub.
