### ISSUE TITLE
Support tailscaled in networks requiring HTTP(s)/SOCKs proxies

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#227]
Currently tailscaled (probably) doesn't support networks that require HTTP(s) or SOCKS proxies to access the Internet.

But all the Go packages we use can pretty much handle that already, so it shouldn't be much effort of us to support it. (at least for a DERP-only mode) We don't dial out in too many places.

**Comment by apenwarr** [comment]
While we're replacing the dialer anyway, let's also force it to use a fixed DNS server and implement #144 (prevent routing loops).

**Comment by bradfitz** [comment]
Closing, as this is done. (other issues can/do track related things)

**Comment by EmiiKhaos** [comment]
Is there any docs how to use this? I tried with 1.0.5 and the current unstable, setting the proxy vars in /etc/default/tailscale but tailscale doesn't come up. Or is it enough that proxy environment variables are only configured where to call tailscale up? With the second case, tailscale comes up, tailscale status shows all nodes, but no ping is possible.

**Comment by bradfitz** [comment]
Only tailscaled uses the environment variables. They would go in /etc/default/tailscaled, not /etc/default/tailscale.

The client tailscale process (e.g. `tailscale up`) just talks to tailscaled over a local unix socket. But all the real work is being done by tailscaled.

**Comment by EmiiKhaos** [comment]
Sorry, I meant /etc/default/tailscaled, that was a typo above

**Comment by bradfitz** [comment]
Why don't you file a new bug with complete details? Old closed issues like this one aren't tracked and it's too easy to let things slip through the cracks if it's not on our various dashboards.

**Comment by EmiiKhaos** [comment]
Will do that, just thought I'm missing some docs, because this is not in the KB
