### ISSUE TITLE
win: clean up /etc/wsl.conf on uninstall

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2271]
https://github.com/tailscale/tailscale/pull/2252 introduced editing /etc/wsl.conf once when Tailscale is configuring DNS. The uninstaller should revert the change and restore the /etc/resolv.conf backup if not done already.

**Comment by DentonGentry** [comment]
Fixed in 1.20 by [#3687](https://github.com/tailscale/tailscale/pull/3687)

We may make another attempt to better support WSL in the future. I do not believe this bug will be useful in that, we won't do so until we have something better. Closing this bug.
