### ISSUE TITLE
cmd/tailscale: ip reports an IP even when logged out, down

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2273]
Investigate when `tailscale ip` prints, and consider when it should.

Currently it seems to output an IP even when logged out and down, which is maybe not right.

**Comment by DentonGentry** [comment]
When one assigns a static IP address to an Ethernet interface, `ip addr` shows the address even if the link is down. I would think Tailscale IP addresses are akin to static IP addresses in that regard: even while disconnected, the address belongs to this node.

**Comment by DentonGentry** [comment]
For Ethernet interfaces:
- a dynamic IP address like DHCP is released when the link goes down
- a static IP address is retained, and one can still find the IP address even while the link is down

Personally I think the `tailscale ip` behavior to show the IP address even while down is correct, it is more akin to a static IP than it is to DHCP. Barring further comment, we'll expect to close this during the next regular bug scrub.
