### ISSUE TITLE
cherry pick: SOCK5s DNS resolution when IPv6 only

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2274]
Candidate for cherry-picking to 1.10 branch:

https://github.com/tailscale/tailscale/commit/722859b47628cf7cc7ceb7c989919ececd10188f

Only affects SOCKS5 dialing out with a hostname, making names resolve to IPv6 addresses if the local node doesn't have an IPv4 address.

Thoughts, @crawshaw @danderson?

**Comment by crawshaw** [comment]
Seems OK to cherry-pick, but not worth a point release on its own?

**Comment by bradfitz** [comment]
It seems like something that's worth coming along for a ride but doesn't need to cause a release just for it. Maybe we plan on one on Friday or Monday and see what else arises meanwhile.

**Comment by DentonGentry** [comment]
This went into 10.1.
