### ISSUE TITLE
Synology systems no longer match the Tailscale architecture names

### ISSUE THREAD

**Issue by poswald** [tailscale/tailscale#2277]
The list of [Synology architectures](https://github.com/tailscale/tailscale-synology/blob/main/docs/platforms.md) now lists architectures names that no longer match the releases created by [the packaging system](https://github.com/tailscale/tailscale-synology/releases). It would be nice to update that doc with the new Tailscale Package Arch names used by the build system.

As an example, which package is to be downloaded and used for an `amd64` system? I would submit a PR but I actually don't know what maps to what.

**Comment by bradfitz** [comment]
Synology uses the name `x86_64` for `amd64`.

See https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

We made this change in prep for getting into the official Synology Package Center.

**Comment by bradfitz** [comment]
Updated the release page with a link. Thanks for the report!
