### ISSUE TITLE
Per app configuration/exit node on android

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/tailscale#2280]
Many VPN apps for android (wireguard included) has the ability to selectively apply firewall to certain apps.
It would be great to see this feature with tailscale on android especially now with exit nodes being available.

A cherry on top would be the ability to specify exit node in this per-app configuration.

**Comment by JayDoubleu** [comment]
+ android tv UI/version would be a nice touch ;)

**Comment by DentonGentry** [comment]
Never say never I suppose, however providing the level of configurability to support per-app use of exit nodes would likely result in a very complex product and user interface, and I'm having trouble seeing that as solving enough actual use-cases to be a good tradeoff.

**Comment by JayDoubleu** [comment]
@DentonGentry I agree, it looks like a lot to ask for however, ability to route specific apps would likely have larger appetite for consumption by users ?

Exit node per app doesn't have to be difficult from UX perspective, just the list of apps which we could click and select Tailscale enabled and exit node toggle buttons. I like this idea from perspective of having different streaming services going via different exit nodes to get around geo-restrictions. I know it doesn't sound very kosher but looks like most VPN providers are using geo-restriction avoidance as one of the features and have large user base just for those features. 
Again, it's a "nice to have" :)

**Comment by DentonGentry** [comment]
Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
Closing during bug scrub.
