### ISSUE TITLE
Android app fails to connect to Tailscale if any particular nameserver doesn't provide a DNS response

### ISSUE THREAD

**Issue by scottcwang** [tailscale/tailscale#2285]
*Steps to reproduce*

1. To the nameserver list, add an IP that won't respond to DNS queries from the Android device, such as 0.0.0.0 or 127.0.0.1. Doesn't matter what position in the list
2. Toggle on Override Local DNS
3. Log out of the Tailscale app, log back in, and try to activate Tailscale in the app

*Observed*
Tailscale activates but then immediately deactivates without error

*Expected*
Tailscale activates and behaves similarly to Linux: skips over any nameservers that aren't responding to it

**Comment by bradfitz** [comment]
What's your Tailscale IP?

It sounds like you have MagicDNS off. If you enable MagicDNS, then your DNS on Android will actually be set to 100.100.100.100 (an on-device DNS server implemented inside Tailscale) that'll handle the failing DNS servers.

It sounds like Android, when told about multiple DNS servers, doesn't handle the case where one fails and the other succeeds.

**Comment by iball** [comment]
I'm seeing the same issue on my android devices and have MagicDNS enabled.  
Doesn't matter if it's enabled or disabled, Tailscale client fails to connect to Tailscale.

**Comment by bradfitz** [comment]
@iball, sounds like you were hitting #2290, unrelated to this bug.

**Comment by scottcwang** [comment]
@bradfitz I do indeed have MagicDNS off. Tailscale IP is 100.94.186.97.

It's been this way for at least a few versions (months). I just hadn't got around to investigating until now.

**Comment by bradfitz** [comment]
Looks like you turned it on now. Does it work with MagicDNS on?

**Comment by scottcwang** [comment]
Yep, it works now with Magic DNS on. Thanks!

In any case, it would be nice if the app behaved nicely with Magic DNS off.

**Comment by bradfitz** [comment]
I'm not sure there's anything we can do here. 

We are moving towards having MagicDNS always on, though, which would fix this.

But when it's off and we just tell the OS the DNS settings that you told us in the admin panel, then Tailscale is out of the serving path on DNS and it's up to the OS to handle.

**Comment by iball** [comment]
> @iball, sounds like you were hitting #2290, unrelated to this bug.

Brad, yes indeed it does.  Apologies.

**Comment by scottcwang** [comment]
OK. But I guess I'm not sure I understand why the Tailscale app immediately disconnects without showing an error message if one of the nameservers isn't responding, even if the nameservers higher in the list do respond.

For instance, if the nameserver list is 1.1.1.1, then 0.0.0.0, the app disconnects immediately. Shouldn't the app still connect and ask the OS to use 1.1.1.1 for resolving everything? Having 0.0.0.0 later in the list doesn't seem like a good reason to disconnect, unless there's something I didn't think of.

**Comment by DentonGentry** [comment]
The remaining question of why did the app exit with a DNS server of 127.0.0.1 is https://github.com/tailscale/tailscale/issues/2033, that `VpnService.Builder.addDnsServer` fails.
