### ISSUE TITLE
my server provider use same 100 subnet

### ISSUE THREAD

**Issue by 81pla** [tailscale/tailscale#2286]
my server provider use same 100 subnet (100.100.2.136 for local dns server ), i want to use 100.100.2.136 to access server provider's repos. when talscale up , i can't access it. what should i do?

**Comment by DentonGentry** [comment]
There is an experimental feature coming to turn off all use of IPv4 in the Tailscale network and only use IPv6, which may be a way to handle this.

It will be a bit before the feature to do this is ready to document.

**Comment by DentonGentry** [comment]
Track overall issue in https://github.com/tailscale/tailscale/issues/1381
