### ISSUE TITLE
IOS resolve private addresses on public DNS 

### ISSUE THREAD

**Issue by digaround** [tailscale/tailscale#2287]
Hello,

observed some issue related to the DNS resolve.

I have Cloudflare DNS where I am hosting some A records pointing to the private address from 192.168.X.X range.

Resolving this private records in web browser (chrome, safari) on IOS does not work, get ERR_NAME_NOT_RESOLVED, on the other devices works correctly.

When activate Override local DNS server option in Tailscale admin portal (with Cloudflare global dns 1.1.1.1, or Google 8.8.8.8) resolving DNS stop workong globally, for all DNS queries on IOS.

IOS version 14.6
Tailscale app version: 1.10.0

**Comment by digaround** [comment]
Done some test, which may help:

1) It seems that problem with resolve private A record on public DNS does not work only on mobile connection (WIFI works OK)

On the other hand, I found working configuration, private records are correctly resolved for my public DNS only if:

1) I have enabled magic DNS on tailscale admin portal and
2) I set "Override local DNS" option in tailscale admin portal

If I set only "Override local DNS" (without activate Magic DNS), all DNS queries stop working on iOS, same situation for Split DNS, only above combination works correctly.


Issue looks very fimilar to #1891, I suspect that DNS on the tailscale admin portal is not preffered even "Override local DNS" is set without activate Magic DNS.

Created some record for test priv.digaround.cloud if someone could test it on diffrent device and confirm issue.

**Comment by DentonGentry** [comment]
Private IP addresses do not work if:
1. Using LTE, and
2. Tailscale is set to not override the DNS servers supplied from the ISP.

So... the wireless carrier's DNS servers refuse to serve private IP addresses?

**Comment by digaround** [comment]
> Private IP addresses do not work if:
> 
> 1. Using LTE, and
> 2. Tailscale is set to not override the DNS servers supplied from the ISP.
> 
> So... the wireless carrier's DNS servers refuse to serve private IP addresses?

It seems yes, but I'am wonder, why setting "Override local DNS" with custom DNS (1.1.1.1 and 8.8.8.8) does not work. I have to set "Override local DNS" AND Enable magic DNS.

Only this two combination works correctly with resolving public DNS records pointing to private addresses.

Shouldn't Tailscale overide DNS for VPN just by setting "Override local DNS" and pointing to the custom 1.1.1.1 and 8.8.8.8, without need to enable Magic DNS ?


Just installed Cloudflare WARP app, which provides VPN as well, and with WARP app does not observe this problems on the LTE connection. After activate VPN on WARP it resolves addresses correctly. (WARP overide DNS to 1.1.1.1 for LTE as well)

So it seems that, tailscale does not Overide local DNS for VPN connection properly without Magic DNS enabled ?

**Comment by DentonGentry** [comment]
My suspicion is:
- with only "Override local DNS" enabled, Tailscale.app sets 1.1.1.1 and 8.8.8.8 as resolvers but iOS continues to send UDP DNS queries to port 53, which the ISP can intercept and see the contents up
- enabling MagicDNS on iOS is implemented by setting the DNS resolver to 100.100.100.100. iOS sends UDP frames, only within the phone, to 100.100.100.100. MagicDNS will forward these frames upstream to global resolvers but, crucially, will automatically use DNS-over-HTTPS to do so. The ISP can no longer see nor modify the DNS queries.
- Installing CloudFlare's app similarly results in the ISP not being able to see the DNS frames. CloudFlare is a traditional VPN, all packets go through the VPN to CloudFlare.

So I'm guessing the ISP intercepts and sends all DNS queries through its own servers. It might have to, if it is using something like 464XLAT and doesn't actually have IPv4 addresses for client devices.

**Comment by DentonGentry** [comment]
I think this is the ISP interfering with unencrypted DNS, likely because they use 464XLAT and are trying to return only AAAA records whenever they can.
