### ISSUE TITLE
Switch logtail to send concatenated JSON

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#229]
logtail currently submits batches of log entries as a single JSON array. This makes it a bit annoying to decode on the server side, because we have to do a bit of a dance to do a streaming decode.

We should make logtail instead use "concatenated JSON", i.e. a sequence of standalone JSON blobs with no separators. This is trivial to decode incrementally with the stdlib JSON decoder.

**Comment by bradfitz** [comment]
The dance is tiny nowadays: https://play.golang.org/p/KZmVFYCp5f9

(It used to be so much worse.)

**Comment by danderson** [comment]
Yeah, I think I've decided this isn't worth it. It's an xkcd "there are 15 standards" problem anyway given our version spread.
