### ISSUE TITLE
Windows client unaware it can update

### ISSUE THREAD

**Issue by bogosj** [tailscale/tailscale#2291]
Going back to https://github.com/tailscale/tailscale/issues/1305, I've seen in my [web dashboard](https://login.tailscale.com/admin/machines) that my client has an update available. The context menu in the system tray has no offer to update, and when I click on "About..." I see this:

![image](https://user-images.githubusercontent.com/10186620/123973976-3e5e1700-d98a-11eb-9aa9-e6c840f4fe63.png)

I know I can manually update but if you'd like me to pull any logs from the device before I do to diagnose let me know. I can leave it in this state for a few weeks.

**Comment by bradfitz** [comment]
This is intentional. We've started hiding updates for a few days to people who are fully updated, just in case there's a surprise bug we didn't find in testing.

**Comment by bogosj** [comment]
Well I refuse to not be on the bleeding edge (or at least what you consider stable), so I'll manually update now. Thanks.
