### ISSUE TITLE
Android on ChromeOS: taildrop can't seem to receive files

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2296]
Logid: 06f0da62aa0659ee69286152cc2c1b22162522535ed74c99e81da5f53403f1b5

Steps:
- Upgrade chromebook-aceb (100.91.31.91) to tailscale android  to v1.10.0-405ea978f8b-g242c936b2cd
- In the Files app, right clicked a file, Share, Tailscale, averys-iphone-12, worked fine. Notification showed up on iOS, file was readable. Good.
- On averys-iphone-12, send from my photo gallery back to chromebook-aceb using the Share|Tailscale pane. Tried both a photo and a video (several times).
- Completion bar on iOS did its thing and claimed success.
- On chromebook-aceb, I didn't get a notification about the received file, nor can I find it in my various Files folders (although I'm not sure where I should expect to see it on ChromeOS, since there are separate ChromeOS Files and Downloads folders, and the Android subsystem also has "Play files" exported to Android. All of those don't show the files having been received though).
- Looked at the Tailscale app permissions. I noticed that Storage permission was not granted, although it was available. Tried granting that, then resending the file: same result.

Based on the symptoms, I assume the files are being successfully received into the local holding area (as on Linux), and either not being transferred out of there, or being transferred to somewhere I don't know to look.

@rosszurowski told me there should be a notification when the file is received. I didn't see that, although I do (always) have the perma-notification that the Tailscale app is providing VPN services.

**Comment by DentonGentry** [comment]
With Android app 1.13.19-td37451bac-g82b6b8dbd36 on ChromeOS, Copying from Linux says `Put "http://100.q.r.s:56293/v0/put/go.mod": dial tcp 100.x.y.z:56293: connect: connection refused`

Copying from MacOS shows a red exclamation point.
<img width="440" alt="Screen Shot 2021-07-30 at 5 50 01 PM" src="https://user-images.githubusercontent.com/1140756/127723544-163491b6-2929-4962-b25a-0e868b9844e0.png">
