### ISSUE TITLE
Unused closure of code in logtail

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#23]
In investigating #22, staticcheck reported a fairly large closure of code that's unused in logtail.

It's all unexported symbols, and I can't find any reference in either the OSS or corp repo, so I'm fairly sure it's right... Unless this was preparation for some radical new thing, and I'll cheese someone off by deleting it.

@apenwarr you'd know! Can I remove these bits and bobs?

```
logtail/logtail.go:235:5: var clientSentinelPrefix is unused (U1000)
logtail/logtail.go:238:2: const noSentinel is unused (U1000)
logtail/logtail.go:239:2: const stopSentinel is unused (U1000)
logtail/logtail.go:246:6: func newSentinel is unused (U1000)
logtail/logtail.go:260:6: func readSentinel is unused (U1000)
logtail/logtail.go:346:5: var errHasLogtail is unused (U1000)
```

**Comment by crawshaw** [comment]
Sentinels should be gone, not sure how this code remains. Will check it out tomorrow

**Comment by danderson** [comment]
Sounds like it was just left behind after sentinels stopped being used. I don't think there's any need for you to take a look, you've confirmed that this code isn't part of an upcoming WIP, so I'll just remove it :)
