### ISSUE TITLE
Alpine Linux packages

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#230]
Requested by user: build Alpine Linux apks.

Main question I don't know the answer to yet is how serving apk repositories works.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2cdu9)

**Comment by joneskoo** [comment]
You should create an APKBUILD essentially following https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

Then you submit it to Alpine Linux testing repository and they handle building it. I got my own project into Alpine so they're not too picky about accepting packages into their official testing repository.

Build it locally (maybe easiest in a container?) and submit the APKBUILD and their CI will crunch it through and tell you what you missed.

After it's got some visibility there they may consider inclusion into main, but already being into testing makes it easy to install and you don't have to worry about building for all Alpine Linux platforms etc. Just keep the APKBUILD up to date.

**Comment by robertgzr** [comment]
I sent a merge request here: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16400

**Comment by Xe** [comment]
I added some comments on that merge request. Thank you for putting in the effort to package tailscale for alpine!

**Comment by lmagyar** [comment]
Will this Alpine package be available on arm/armv7 architecture?

**Comment by bradfitz** [comment]
@lmagyar, the merge request linked above contains:

```
arch="all !mips !mips64"
```

So I'd assume so.

**Comment by DentonGentry** [comment]
I think this is done.

**Comment by Xe** [comment]
It is not: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/17397

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/1292 is relevant about the Alpine integration.

**Comment by Xe** [comment]
This was merged! You can now install Tailscale with `apk add tailscale` as long as you have the testing repo enabled. This probably only works on Alpine Edge.

**Comment by Xe** [comment]
On second thought this is for us having our own APK repo (instead of putting it in Alpine's upstream repos). Re-opening.

**Comment by joneskoo** [comment]
I'm curious, why own repo? Any benefit over the upstream testing repo built for alpine supported platforms?

**Comment by mcristina422** [comment]
I can confirm I can install from testing 
```
$ apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing tailscale
```

**Comment by Xe** [comment]
@mcristina422 I would really suggest not mixing edge and stable if you can avoid it. That is likely to incur ABI conflicts.

**Comment by Oujiii** [comment]
Any ETA of when it will be available on your own repo? Really looking forward to connecting a few services on Alpine.

**Comment by hronro** [comment]
I just notice in http://dl-cdn.alpinelinux.org/alpine/edge/testing the version is `1.8.5-r1`, however the latest version should be `1.10.1`.
Is it possible to keep the alpine repo up to date?

**Comment by xxb** [comment]
> jfyi the tailscale package assumes systemd: `failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)`
> 
> It's moved from testing to community, anyone coming for **quick workaround** here may use:
> 
> ```
> echo "@edge_community http://dl-cdn.alpinelinux.org/alpine/edge/community" | tee /etc/apk/repositories
> apk add tailscale@edge_community
> rc-update add tailscale
> rc-service tailscale start
> tailscale up
> ```
> 
> `@repository` should be more elegant (updates) than specifying `-X, --repository`

It worked, thank you !

**Comment by jtagcat** [comment]
### GitHub Etiquette

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by DentonGentry** [comment]
This bug tracked the possibility of Tailscale maintaining a separate repository, in addition to the package maintained by Alpine. I don't think this is something we're likely to do at this point. Closing during bug scrub.

**Comment by cphuntington97** [comment]
Please also note that https://pkgs.alpinelinux.org/package/v3.15/main/x86/ip6tables is required if Tailscale's IPv6 functionality is desired.

**Comment by panekj** [comment]
> Please also note that [pkgs.alpinelinux.org/package/v3.15/main/x86/ip6tables](https://pkgs.alpinelinux.org/package/v3.15/main/x86/ip6tables) is required if Tailscale's IPv6 functionality is desired.

`tailscale` now depends on `ip6tables` in v3.15 branch (sorry it took so long)

**Comment by frankievalentine** [comment]
> 

I'm affected by this, but this workaround no longer works.

**Comment by panekj** [comment]
> > https://github.com/tailscale/tailscale/issues/230#issuecomment-948162461
> 
> I'm affected by this, but this workaround no longer works.

what exactly doesn't work

**Comment by frankievalentine** [comment]
> > > [#230 (comment)](https://github.com/tailscale/tailscale/issues/230#issuecomment-948162461)
> > 
> > 
> > I'm affected by this, but this workaround no longer works.
> 
> what exactly doesn't work

There was a specific issue with the tailscaled service not starting in an Alpine LXC container in Proxmox, but I figured it out. Here is a link to the [issue](https://gitlab.alpinelinux.org/alpine/aports/-/issues/14961#note_308947
) and explanation.

**Comment by DentonGentry** [comment]
There is also:
- [Tailscale in LXC containers](https://tailscale.com/kb/1130/lxc-unprivileged/)
- [Tailscale on Proxmox host](https://tailscale.com/kb/1133/proxmox/)

**Comment by frankievalentine** [comment]
Thank you @DentonGentry I missed this completely.
