### ISSUE TITLE
Tailscale is setting an invalid DNS server

### ISSUE THREAD

**Issue by gowthamgts** [tailscale/tailscale#2301]
I'm having around 6 devices connected to my network and all devices are able to successfully talk to each other. Today when I tried to use tailscale for connecting to remote server on my macbook, it stopped working. While debugging, I found out that only DNS is not working. Tried clean uninstall and installed it again, but no luck.

I'm having a pi setup at home and it's also connected to tailscale network and my network have magic DNS enabled with my pi's tailscale ip as the global nameserver. Although, I'm not overriding devices' default DNS settings. When I did a `cat` on `/etc/resolv.conf`, I found the following:

```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search gowthamgts.github.beta.tailscale.net router-ac59-v2
nameserver 100.68.246.1
``` 

This is weird because I don't have a tailscale device in my network having 100.68.246.1 IP. When I disconnect from the network, it's being restored to this:

```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search router-ac59-v2
nameserver 192.168.1.4
```

I thought may be it's an older device IP in my own network and tried doing a clean install again. Looks like DNS server is getting replaced with my current macbook pro's tailscale IP but it replaces the last 8 bits of the IP. On the sample provided above, `100.68.246.81` was my device tailscale IP but it assigned `100.68.246.1`. This happened every time I did a clean install.

For some reason, on my other macbook pro, `/etc/resolv.conf` is not changed and working as expected since I'm not overriding local DNS setting. I'm not how to resolve this. Please assist. 

Let me know if you need any more info.

**Comment by gowthamgts** [comment]
any update on this. I restarted my mac and it worked. It's not overwriting the `/etc/resolv.conf` file now. This started happening after I connected to a TunnelBear VPN. Let me try whether I can reproduce this.

**Comment by DentonGentry** [comment]
TunnelBear breaks Tailscale:
- even if not connected, TunnelBear adds what it thinks is its own DNS server whenever the *Tailscale* link comes up, breaking Tailscale DNS
- https://github.com/tailscale/tailscale/issues/2000 sounds like what you are running into

Because TunnelBear has processes active which overwrite the Tailscale DNS handling, even when TunnelBear is not connected, people have generally had to fully uninstall Tunnelbear in order to work.

**Comment by gowthamgts** [comment]
Ah yes. I'm able to reproduce this now and fix it without a machine restart. I killed tunnelbear process and it's not overwriting the file anymore. Weird.

Here's my `/etc/resolv.conf` at various stages

1. Before starting Tunnelbear:
```
# omitted banner for brevity
search gowthamgts.github.beta.tailscale.net router-ac59-v2
nameserver 192.168.1.4
```

2. After starting Tunnelbear:
```
# omitted banner for brevity
search router-ac59-v2
nameserver 172.18.12.1
```

3. Stopped Tunnelbear:
```
# omitted banner for brevity
search router-ac59-v2
nameserver 192.168.1.4
```

4. Connected to Tailscale network:
```
search gowthamgts.github.beta.tailscale.net router-ac59-v2
nameserver 100.68.246.1
```

5. Disconnected from Tailscale network:
```
search router-ac59-v2
nameserver 192.168.1.4
```

7. Killed tunnelbear process and now connected to TS network:
```
search router-ac59-v2
nameserver 192.168.1.4
```

@DentonGentry - Please close this issue if you're tracking this on #2000

**Comment by DentonGentry** [comment]
Closing as dup of #2000
