### ISSUE TITLE
userspace-networking Subnet Relay drops UDP traffic

### ISSUE THREAD

**Issue by alex-richman-onesignal** [tailscale/tailscale#2302]
We have a Tailscale node advertising a 10/8 route, there's a DNS server sitting on 10.x.x.x which we would like to send traffic to.
However, Tailscale seems unable to reach the server over UDP.  DNS over TCP works fine, all other TCP traffic works fine.  UDP DNS from the relay box locally (not over tailscale) works fine.

In the Tailscale relay logs at the time of the request this message is repeated:
```
2021/07/01 14:42:38 acceptUDP: could not create endpoint: no route
2021/07/01 14:42:38 acceptUDP: could not create endpoint: no route
2021/07/01 14:42:38 [RATELIMIT] format("acceptUDP: could not create endpoint: %v")
```

I do occasionally also see these messages indicating some sort of successful UDP traffic, but this doesn't seem to manifest as actually successfully routing traffic:
```
2021/07/01 14:42:47 Accept: UDP{100.x.x.x:40484 > 10.x.x.x:53} 112 ok
```

TCP DNS works fine:
```
2021/07/01 14:44:09 Accept: TCP{100.x.x.x:49211 > 10.x.x.x:53} 60 tcp ok
2021/07/01 14:44:10 Accept: TCP{100.x.x.x:49211 > 10.x.x.x:53} 52 tcp non-syn
2021/07/01 14:44:10 Accept: TCP{100.x.x.x:49211 > 10.x.x.x:53} 138 tcp non-syn
```

Bugreport from the relay:
`BUG-08c6d6900a1bdc6a1c2f0f04882fa5263cc92ec88944717b2229068f50dab4e3-20210701143839Z-d46ced45970c3638`

Bugreport from my laptop, which was making the DNS queries:
`BUG-5b8b2ccb4ec4f5399726d4344f02d46c2718a5864813af8f00481a2b33db4884-20210701144648Z-7ee63f5b0704c13a`

Thanks!
- Alex.

**Comment by DentonGentry** [comment]
From the subnet relay:

```
2021-07-01 14:38:44.721578857 +0000 UTC: Accept: UDP{100.x.x.x:y > 10.x.x.x:53} 69 ok
2021-07-01 14:38:44.721783347 +0000 UTC: [RATELIMIT] format("acceptUDP: could not create endpoint: %v") (3 dropped)
2021-07-01 14:38:44.721838831 +0000 UTC: acceptUDP: could not create endpoint: no route
```

The `could not create endpoint` message comes from https://github.com/tailscale/tailscale/blob/805d5d3cdeaaeb943c8a9e3c96d1bffbdd20d9b4/wgengine/netstack/netstack.go#L554

That is the netstack code, used for userspace networking. The startup arguments confirm this:

2021-06-29 12:58:14.424951974 +0000 UTC: Program starting: v1.11.8-xxxxxxxx, Go 1.16.1: []string{"tailscaled", "--state=/app/state/tailscaled.state", "--socket=/app/tailscaled.sock", "--tun", "userspace-networking", "--socks5-server=127.0.0.1:1055"}

Also it is running a build from the unstable track, https://pkgs.tailscale.com/unstable/

The use of /app path names and the SOCKS5 server on port 1055 imply it was created following the KB articles about serverless, like https://tailscale.com/kb/1107/heroku/

A couple questions:
- do you need to use userspace networking mode (aka netstack) for the subnet relay? netstack can do routing, but the relay feature has gotten far less testing in netstack mode versus [using TUN.](https://tailscale.com/kb/1031/install-linux/)
- Can we help in getting /dev/net/tun created on that system? userspace-networking mode is great in allowing connectivity in environments which otherwise could not use Tailscale at all, but for this application I think you'd be better off letting the kernel handle routing.

**Comment by alex-richman-onesignal** [comment]
@DentonGentry 

Yep this is running userspace-networking, sorry I should have been clearer about that in the OP.

Unfortunately in this case the relay is running inside K8s in an unprivileged container - Binding /dev/net/tun in and granting CAP NET_ADMIN would be a very undesirable configuration for us (if even possible given the node level security constraints).

Excepting this issue (and the few others we've posted) userspace networking has been working very successfully.  I'm happy to progress debugging the netstack routing with you further.

**Comment by DentonGentry** [comment]
The root cause is that it ends up in the acceptUDP() function at all. From the description, it is supposed to recognize that the packet is to be routed and call forwardUDP instead.

https://github.com/tailscale/tailscale/blob/805d5d3cdeaaeb943c8a9e3c96d1bffbdd20d9b4/wgengine/netstack/netstack.go#L569

**Comment by DentonGentry** [comment]
Working on setting up a subnet relay using userspace-networking to reproduce the issue, as code inspection only goes so far.

**Comment by DentonGentry** [comment]
https://github.com/inetaf/netstack/blob/29b14ebc044e18fc9c888c633d6ea4177e3333f2/tcpip/transport/udp/forwarder.go#L71

Adding a printf in CreateEndpoint where it is returning a failure:

```
// CreateEndpoint creates a connected UDP endpoint for the session request.
func (r *ForwarderRequest) CreateEndpoint(queue *waiter.Queue) (tcpip.Endpoint, tcpip.Error) {
        netHdr := r.pkt.Network()
        route, err := r.stack.FindRoute(r.pkt.NICID, netHdr.DestinationAddress(), netHdr.SourceAddress(), r.pkt.NetworkProtocolNumber, false /* multicastLoop */)
        if err != nil {
                fmt.Printf("NICID: %v dest: %v src: %v proto: %v\n", r.pkt.NICID, netHdr.DestinationAddress(), netHdr.SourceAddress(), r.pkt.NetworkProtocolNumber)
                return nil, err
        }
```

We see:
```
Accept: UDP{100.114.111.87:37792 > 10.1.11.2:5300} 40 ok
NICID: 1 dest: 10.1.11.2 src: 100.114.111.87 proto: 2048
acceptUDP: could not create endpoint: no route
```

These look ok. The protocol number is 0x0800, the protocol number for IPv4.

**Comment by DentonGentry** [comment]
https://github.com/inetaf/netstack/blob/29b14ebc044e18fc9c888c633d6ea4177e3333f2/tcpip/stack/stack.go#L1205

chosenRoute does equal (tcpip.Route{}), so the routing lookup is skipped and the code returns ErrNoRoute.
https://github.com/inetaf/netstack/blob/29b14ebc044e18fc9c888c633d6ea4177e3333f2/tcpip/stack/stack.go#L1249

**Comment by DentonGentry** [comment]
https://github.com/inetaf/netstack/blob/29b14ebc044e18fc9c888c633d6ea4177e3333f2/tcpip/stack/stack.go#L1195
```
			if onlyGlobalAddresses && chosenRoute == (tcpip.Route{}) && isNICForwarding(nic, netProto) {
				chosenRoute = route
			}
```

isNICForwarding is false, so chosenRoute is nil, so no route lookup is done and it returns ErrNoRoute.

**Comment by DentonGentry** [comment]
https://github.com/inetaf/netstack/blob/29b14ebc044e18fc9c888c633d6ea4177e3333f2/tcpip/stack/stack.go#L1090
```
func isNICForwarding(nic *nic, proto tcpip.NetworkProtocolNumber) bool {
	switch forwarding, err := nic.forwarding(proto); err.(type) {
```

nic.forwarding(0x800) is false. IPv4 forwarding is disabled in netstack.

**Comment by DentonGentry** [comment]
To summarize: netstack is not forwarding UDP frames because forwarding is disabled.

To be honest: the real bug is not that it declines to forward UDP, but that it agrees to forward TCP.

**Comment by bradfitz** [comment]
> the real bug is not that it declines to forward UDP, but that it agrees to forward TCP.

I don't think it does forward TCP. Don't _we_ do that? We dial and stitch them together.

**Comment by DentonGentry** [comment]
The test network I've setup is:
+ Tailscale node in Digital Ocean (outside of the home, no sneaky LAN connections possible)
+ Tailscale in a container with `./tailscaled --tun=userspace-networking` and `tailscale up --advertise-routes=10.1.11.0/24`. Its eth0 has two IP addresses, my normal LAN address and a 10.1.11.1 address
+ Another container ("stranded") whose only connectivity is 10.1.11.2. It does not have Tailscale installed, it relies on the subnet router.

Using netcat between the Digital Ocean node and "stranded"

Using `nc w.x.y.z 5300` to make a TCP connection, whatever I type from DigitalOcean appears at the stranded container.
Using `nc -u w.x.y.z 5300` to use UDP, nothing appears at the stranded container and the subnet router logs `acceptUDP: could not create endpoint: no route` every time.

My setup is kindof artificial that I'm routing between two alias IP addresses on eth0. Setting up a container with multiple eth# interfaces and a new vmbridge is possible but will take longer. I also haven't verified that the tailscale subnet router is actually the thing forwarding TCP, if there is some other sneaky thing going on.

Nonetheless, that TCP and UDP behave differently is unexpected.

**Comment by DentonGentry** [comment]
Notes from bug scrub:
- we think this used to work, when first written. Naman (engineer who developed it) tested these cases.
- Naman was likely working on hybrid mode, where the kernel handles endpoint addresses and netstack handles subnet routing
- This case is slightly different in that it is not hybrid mode it is pure userspace-networking.

**Comment by bradfitz** [comment]
> Naman was likely working on hybrid mode

Unlikely, since I added hybrid mode Apr 1 (d488678fdc928def9caa6fb261093066bdaa8980).

He added UDP forwarding March 8th (7325b5a7ba1e2d36ebe59c74e0328d6510da5654)

**Comment by DentonGentry** [comment]
There is more to it than just enabling forwarding. Adding this did not fix it:

```
diff --git a/wgengine/netstack/netstack.go b/wgengine/netstack/netstack.go
index 4bd00f04..73ae376d 100644
--- a/wgengine/netstack/netstack.go
+++ b/wgengine/netstack/netstack.go
@@ -122,6 +122,8 @@ func Create(logf logger.Logf, tundev *tstun.Wrapper, e wgengine.Engine, mc *magi
                        NIC:         nicID,
                },
        })
+       _ = ipstack.SetForwardingDefaultAndAllNICs(ipv4.ProtocolNumber, true)
+       _ = ipstack.SetForwardingDefaultAndAllNICs(ipv6.ProtocolNumber, true)
        ns := &Impl{
                logf:                logf,
                ipstack:             ipstack,
```

https://github.com/inetaf/netstack/blob/29b14ebc044e18fc9c888c633d6ea4177e3333f2/tcpip/stack/stack.go#L1222
```
// Use the specified NIC to get the local address endpoint.
if id != 0 {
    if aNIC, ok := s.nics[id]; ok {
        if addressEndpoint := s.getAddressEP(aNIC, localAddr, remoteAddr, netProto); addressEndpoint != nil {
```
getAddressEP returns nil.

The routing table within netstack may not be populated from the Tailscale routes. We install a function to handle TCP, we may need to install a similar function to handle UDP.
https://github.com/tailscale/tailscale/blob/7e7c4c1bbe24f998e76c1d32ef870187829a103d/wgengine/netstack/netstack.go#L149

**Comment by DentonGentry** [comment]
Hrmpf. Adding this:
```
dgentry@ubuntu:~/Documents/Code/tailscale/tailscale/cmd/tailscaled$ git diff
diff --git a/wgengine/netstack/netstack.go b/wgengine/netstack/netstack.go
index 4bd00f04..b75f5252 100644
--- a/wgengine/netstack/netstack.go
+++ b/wgengine/netstack/netstack.go
@@ -164,7 +166,24 @@ func (ns *Impl) Start() error {
                }
                return tcpFwd.HandlePacket(tei, pb)
        })
-       ns.ipstack.SetTransportProtocolHandler(udp.ProtocolNumber, udpFwd.HandlePacket)
+       ns.ipstack.SetTransportProtocolHandler(udp.ProtocolNumber, func(tei stack.TransportEndpointID, pb *stack.PacketBuffer) bool {
+               addr := tei.LocalAddress
+               var pn tcpip.NetworkProtocolNumber
+               if addr.To4() != "" {
+                       pn = ipv4.ProtocolNumber
+               } else {
+                       pn = ipv6.ProtocolNumber
+               }
+               ip, ok := netaddr.FromStdIP(net.IP(addr))
+               if !ok {
+                       ns.logf("netstack: could not parse local address %s for incoming UDP connection", ip)
+                       return false
+               }
+               if !ns.isLocalIP(ip) {
+                       ns.addSubnetAddress(pn, ip)
+               }
+               return udpFwd.HandlePacket(tei, pb)
+       })
        go ns.injectOutbound()
        ns.tundev.PostFilterIn = ns.injectInbound
        return nil
```

Results in a very hopeful-looking log message on the relay node:
`Accept: UDP{100.114.111.87:46521 > 10.1.11.2:5300} 52 ok`

But the UDP frames do not arrive at the destination machine on the remote subnet.

**Comment by alex-richman-onesignal** [comment]
@DentonGentry Thanks for your efforts on this - FWIW I did a bit of experimenting with your patches and think that the IP resolution is a bit off for UDP forwarding.  It seems to be trying to send traffic to 127.0.0.1:53 rather than the actual forward target.

I tested this by setting up a staging deployment of the relay, using a local build of tailscaled from current main with your patches applied.  Config is identical to our production relay except I'm only advertising a route to 216.146.35.35/32 (because no one uses Dyn anymore).

Logs from the relay:
```
2021/07/12 16:26:26 Accept: UDP{100.x.x.x:43541 > 216.146.35.35:53} 79 ok
2021/07/12 16:26:26 packet in (from 100.x.x.x:43541): ...
2021/07/12 16:26:26 UDP ForwarderRequest: 100.x.x.x:43541 -> 216.146.35.35:53
2021/07/12 16:26:26 netstack: forwarding incoming UDP connection on port 53
2021/07/12 16:26:26 wrote UDP packet 100.x.x.x:43541 -> 127.0.0.1:53
...
2021/07/12 16:28:09 netstack: UDP session between {%!s(tcpip.NICID=1) 100.x.x.x %!s(uint16=56492)} and 127.0.0.1:53 timed out
```

Staging relay bug report:
`BUG-8d8a96c8c6e23dba6de413ba409a352001f5c118fca1df9f9d2c80ec60793c0e-20210712163036Z-4e75a2177b77284b`

Also here's the logs for the successful tcp connection, if those are of any use:
```
2021/07/12 16:33:06 Accept: TCP{100.x.x.x:41449 > 216.146.35.35:53} 60 tcp ok
2021/07/12 16:33:06 packet in (from 100.x.x.x:41449): ...
2021/07/12 16:33:06 TCP ForwarderRequest: 100.x.x.x:41449 -> 216.146.35.35:53
2021/07/12 16:33:06 packet Write out: ...
2021/07/12 16:33:06 Accept: TCP{100.x.x.x:41449 > 216.146.35.35:53} 52 tcp non-syn
2021/07/12 16:33:06 packet in (from 100.x.x.x:41449): ...
2021/07/12 16:33:06 packet in (from 100.x.x.x:41449): ...
2021/07/12 16:33:06 netstack: forwarding incoming connection to 216.146.35.35:53
```

Let me know if I can do anything else to help debug.

Thanks!
- Alex.

**Comment by DentonGentry** [comment]
My test case consists of running `nc -u 10.1.11.2 5300` on a remote node on my Tailnet whose address is 100.114.111.87, through a userspace-networking tailscaled told to advertise 10.1.11.0/24, to a VM on a new subnet at 10.1.11.2.

When I send some bytes over the netcat connection I see:
```
Accept: UDP{100.114.111.87:45037 > 10.1.11.2:5300} 50 ok
```
so the flow establishment appears to be working.

In `wgengine/netstack/netstack.go:forwardUDP()` there are two calls to `startPacketCopy()`. Adding printfs to both of them:

On [line 602](https://github.com/tailscale/tailscale/blob/7e7c4c1bbe24f998e76c1d32ef870187829a103d/wgengine/netstack/netstack.go#L602): `netstack: startPacketCopy 100.114.111.87:45037`
This is sending the packet back to the node which sent it?

On [line 606](https://github.com/tailscale/tailscale/blob/7e7c4c1bbe24f998e76c1d32ef870187829a103d/wgengine/netstack/netstack.go#L606): `netstack: startPacketCopy 127.0.0.1:5300`
This sends it to the correct destination port number, but on localhost. I think this is why @alex-richman-onesignal sees packets going to 127.0.0.1:53.

Neither of these looks correct.

Unfortunately setting it to send to what looks like the correct address still doesn't work:
```
        ns.logf("netstack: startPacketCopy %v:%v", clientLocalAddr.Addr.String(), clientLocalAddr.Port)
        startPacketCopy(ctx, cancel, client, &net.UDPAddr{
                IP:   net.ParseIP(clientLocalAddr.Addr.String()),
                Port: int(clientLocalAddr.Port),
        }, backendConn, ns.logf, extend)
```

It prints `netstack: startPacketCopy 10.1.11.2:5300`, which would be correct, but still no packet arrives at netcat on 10.1.11.2.

**Comment by DentonGentry** [comment]
Iterating on this idea did start to get UDP frames delivered in one direction, from the Tailscale node to the external subnet node, though not reliably. It is definitely on the right track.

**Comment by DentonGentry** [comment]
Notes from discussion about this:
- netstack initially only handled local UDP. Subnet routing was added for TCP later, but doesn't look like UDP was done at that time. The backend* code in acceptUDP reflects this, that localhost support was the focus.
- we've also updated netstack from upstream one or more times since then.
- HandleFunc used to work for forwarding, should look at what happened that broke it.

**Comment by DentonGentry** [comment]
Patching in https://github.com/tailscale/tailscale/pull/2482, when I use netcat to send a UDP frame through my userspace-networking subnet router:

```
wgengine: idle peer d:d9b0bc30a8df7814 now active, reconfiguring wireguard
wgengine: Reconfig: configuring userspace wireguard config (with 1/22 peers)
magicsock: ParseEndpoint: key=[4bDH0]: disco=d:d9b0bc30a8df7814 ipps=
magicsock: DERP packet received from idle peer [4bDH0]; created=true
magicsock: adding connection to derp-4 for [4bDH0]
magicsock: 2 active derp conns: derp-2=cr5s,wr5s derp-4=cr0s,wr0s
derphttp.Client.Recv: connecting to derp-4 (fra)
magicsock: derp-4 connected; connGen=1
Accept: UDP{100.114.111.87:33717 > 10.1.11.2:5300} 34 ok
write packet to 100.114.111.87:5300 failed: write udp4 127.0.0.1:33717->100.114.111.87:5300: sendto: invalid argument
```

I typed the message in to netcat on 100.114.111.87, and sent it to 10.1.11.2:5300.
The message did not appear in netcat on 10.1.11.2.
The error message makes it look like it is trying to send a response back, but I did not send anything from 10.1.11.2.

**Comment by bradfitz** [comment]
oh, I didn't unbind it from 127.0.0.1 for the local addr

**Comment by bradfitz** [comment]
@DentonGentry, I pushed an update. Try again?

**Comment by DentonGentry** [comment]
When I send a UDP frame netcat on 100.114.111.87 to 10.1.11.2:5300, the log messages look promising but tcpdump on 10.1.11.2 shows no packet arriving.

I've double checked that the same tailscaled run in regular /dev/net/tun mode does forward frames to 10.1.11.2 and back, so the network topology is working.

```
wgengine: idle peer d:d9b0bc30a8df7814 now active, reconfiguring wireguard
wgengine: Reconfig: configuring userspace wireguard config (with 1/22 peers)
magicsock: ParseEndpoint: key=[4bDH0]: disco=d:d9b0bc30a8df7814 ipps=
magicsock: DERP packet received from idle peer [4bDH0]; created=true
magicsock: adding connection to derp-4 for [4bDH0]
magicsock: 2 active derp conns: derp-2=cr7s,wr7s derp-4=cr0s,wr0s
derphttp.Client.Recv: connecting to derp-4 (fra)
magicsock: derp-4 connected; connGen=1
Accept: UDP{100.114.111.87:50469 > 10.1.11.2:5300} 58 ok
```

**Comment by bradfitz** [comment]
I can repro now.

We're getting the destination out of the wrong part. It's in the `udp.ForwarderRequest.ID()` (the `reqDetails` variable), not `ep.GetRemoteAddress`.

```
Accept: UDP{100.123.101.40:57032 > 10.2.0.230:53} 66 ok
packet in (from 100.123.101.40:57032): 45 00 00 42 3f 8b 00 00 40 11 66 95 64 7b 65 28 0a 02 00 e6 de c8 00 35 00 2e 38 b7 bf 02 01 20 00 01 00 00 00 00 00 01 05 64 61 6e 67 61 03 63 6f 6d 00 00 01 00 01 00 00 29 10 00 00 00 00 00 00 00
UDP ForwarderRequest: 100.123.101.40:57032 -> 10.2.0.230:53
netstack: forwarding incoming UDP connection on port 53
XXX forwardUDP: listen=0.0.0.0:57032, remote=100.123.101.40:53, remoteAddr=100.123.101.40
wrote UDP packet 100.123.101.40:57032 -> 100.123.101.40:53
magicsock: disco: d:d800117d8eb0678d<-d:82dc1ed354d16d46 ([IQ8uB], [2602:d1:b4cf:c100:f915:42c7:7aaa:1341]:57228)  got ping tx=0c408207917f
Accept: UDP{100.123.101.40:57032 > 10.2.0.230:53} 66 ok
packet in (from 100.123.101.40:57032): 45 00 00 42 03 09 00 00 40 11 a3 17 64 7b 65 28 0a 02 00 e6 de c8 00 35 00 2e 38 b7 bf 02 01 20 00 01 00 00 00 00 00 01 05 64 61 6e 67 61 03 63 6f 6d 00 00 01 00 01 00 00 29 10 00 00 00 00 00 00 00
wrote UDP packet 100.123.101.40:57032 -> 100.123.101.40:53
LinkChange: minor
magicsock: starting endpoint update (link-change-minor)
netcheck: report: udp=true v6=true mapvarydest=false hair=false portmap=MC v4a=209.180.207.193:43386 v6a=[2602:d1:b4cf:c100:2482:adff:fe4c:7b67]:56187 derp=10 derpdist=2v4:19ms,2v6:57ms,9v4:42ms,10v4:2ms,10v6:72ms
Accept: UDP{100.123.101.40:57032 > 10.2.0.230:53} 66 ok
packet in (from 100.123.101.40:57032): 45 00 00 42 49 be 00 00 40 11 5c 62 64 7b 65 28 0a 02 00 e6 de c8 00 35 00 2e 38 b7 bf 02 01 20 00 01 00 00 00 00 00 01 05 64 61 6e 67 61 03 63 6f 6d 00 00 01 00 01 00 00 29 10 00 00 00 00 00 00 00
wrote UDP packet 100.123.101.40:57032 -> 100.123.101.40:53
```

**Comment by alex-richman-onesignal** [comment]
Thank you both @bradfitz @DentonGentry for your work on this.  Tested in our environment and it's working great :+1:
