### ISSUE TITLE
Proxy `.local` TLDs from another LAN in addition to regular magic DNS

### ISSUE THREAD

**Issue by nicksahler** [tailscale/tailscale#2308]
multicastDNS and some routers implement the automatic resolution of `.local` domains to their respective machines by host-name; so the machine with hostname `my-desktop` would get the  domain `my-desktop.local`. Lots of local workflows depend on this automatic domain configuration and it makes things convenient. It would be cool if tailscale also evaluated these domains on top of the other generated hostname based domains so flows that work on the LAN would continue to work when I leave the house (for example, I have an NAS on `my-desktop.local`, connecting to tailscale when I leave would keep that NAS mounted at that domain name).

edit: er - I meant to tag this as a feature request but it won't  let me :)

**Comment by bradfitz** [comment]
@nicksahler, on which platform(s) in particular would you want this?

On some it might be as easy as saying, "Hey, OS, you handle *.local and I won't.", which is the ideal answer. We might already do that effectively on macOS, @danderson?

**Comment by nicksahler** [comment]
Basically macOS but ideally wherever possible! I currently am able to access my NAS via my iphone, macbook, and linux machine. That said, if it just worked on iDevices to start, I cant't complain 😉

**Comment by bradfitz** [comment]
I guess I'm confused now. Do you just want your local mDNS *.local names to keep working on the same LAN, or do you want a node on your LAN to re-export those LAN *.local names over Tailscale so Tailscale nodes on different networks can use them?

Because on the Mac I'm no now, *.local names still work, even with MagicDNS on:

```
crow5k:~ $ hostname
crow5k.local

crow5k:~ $ ping book1pro.local
PING book1pro.local (10.0.107.5): 56 data bytes
64 bytes from 10.0.107.5: icmp_seq=0 ttl=64 time=9.262 ms
64 bytes from 10.0.107.5: icmp_seq=1 ttl=64 time=3.229 ms
^C
--- book1pro.local ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 3.229/6.245/9.262/3.017 ms

crow5k:~ $ ping monitoring
PING monitoring.tailscale.com.beta.tailscale.net (100.88.178.64): 56 data bytes
64 bytes from 100.88.178.64: icmp_seq=0 ttl=64 time=88.411 ms
64 bytes from 100.88.178.64: icmp_seq=1 ttl=64 time=20.503 ms
64 bytes from 100.88.178.64: icmp_seq=2 ttl=64 time=20.240 ms
^C
--- monitoring.tailscale.com.beta.tailscale.net ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 20.240/43.051/88.411/32.074 ms

crow5k:~ $ uname -a
Darwin crow5k.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

**Comment by nicksahler** [comment]
Oh - no - I want it to re-export them basically - it would be cool if when I am _away_ from home I could continue to communicate with the same machines as if I had not left, essentially. I guess the other alternative is to add the non`.local` DNS to my home router (the other direction essentially).

**Comment by bradfitz** [comment]
Gotcha. I think we have a bug for that already open but I'll keep this one open until we find it, if we do.

**Comment by nicksahler** [comment]
Ok! Awesome :) Thanks for the quick response.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1482
