### ISSUE TITLE
tailscale-synology v1.10.0 reserves/squats on port 443

### ISSUE THREAD

**Issue by fspadini** [tailscale/tailscale#2310]
Issue: 
tailscale-synology v1.10.0 installed on DSM 6.2.4-25556 interferes with the synology reverse proxy and causes port 443 to be marked "in use by an application".

Steps to Reproduce:
1) Install tailscale-synology (I only tried this while logged in to tailscale)
2) Control Panel -> Application Portal -> Reverse Proxy -> Create
General:
Source:
Protocol: HTTPS
Hostname: a subdomain or different hostname than the synology itself
Port: 443
#Destination:
Protocol: HTTP
Hostname: localhost
Port: XXX

3) Click OK

At this point you should get an error that the port is being used by "another application"

Workaround:
1) Uninstall Tailscale
2) Create the desired reverse proxy rule on port 443
3) Reinstall Tailscale

Potential Diagnosis:
Port 443 is declared in tailscale.sc dst.ports, according to https://help.synology.com/developer-guide/integrate_dsm/ports.html the dst port can create port conflicts.

**Comment by bradfitz** [comment]
@maisem, you added that in https://github.com/tailscale/tailscale-synology/commit/b85a46d1#diff-4c2f783b0930ce46704e2367ad9d4643d61fa6551d2486374e339bfba97b81ceR6 ... do you remember why?

**Comment by hamlynt** [comment]
Can confirm this issue and the steps to reproduce above. 

In my testing, neither running `sudo tailscale down` nor manually stopping the package in Synology DSM package manager were enough to release the ports. As noted above a full uninstall of the package is required for Synology reverse proxy to detect that port 443 is released. 

The apparent port conflict also prevents modifying any existing reverse proxy entries, and generates the same error as occurs when creating new ones.

**Comment by maisem** [comment]
I believe this is just bad configuration. There was some confusion about which ports we need to list. I'll send a pr to remove 443.

**Comment by hwbai** [comment]
Ran into the exact same issue ... hope this would be gone in the next version

**Comment by maisem** [comment]
Fixed in tailscale/tailscale-synology#74
