### ISSUE TITLE
--reset with tailscale up is not resetting "--advertise-route=" information.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2313]
Customers try to reset the advertised route with the "tailscale up --reset " command, but it failed to reset unless you advertise an empty route.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3c0lt)

**Comment by DentonGentry** [comment]
No longer reproducible: `tailscale up --advertise-routes=192.168.144.0/24` followed by `tailscale up --reset` stops advertising the routes.
