### ISSUE TITLE
FR: Show Device Last Seen for Android

### ISSUE THREAD

**Issue by mcristina422** [tailscale/tailscale#2317]
In the android app, under `My Devices`, there is no way to tell if a device is online or not. 

Maybe we can add an indicator of if the device is online? A status dot next to each device maybe? 
 
Add when it was `Last Seen`? I could see this as making the interface too busy as well though.

**Comment by DentonGentry** [comment]
Similar iOS request in https://github.com/tailscale/tailscale/issues/2771

**Comment by pzerone** [comment]
Any updates on this feature on Android? Since IOS already has it.

**Comment by agottardo** [comment]
Implemented in https://github.com/tailscale/tailscale-android/pull/191
