### ISSUE TITLE
Synology build for 88f6282 missing

### ISSUE THREAD

**Issue by danharvey** [tailscale/tailscale#2319]
I've got Tailscale running on a DS411 Synology which uses the old Marvell 88f6282 chipset which is armv5. I'm currently running 1.8.3 which had an armv5 build.

The new build now seem to have more targets but the older arm versions is missing. Is this a bug or is it not possible to build for that version now?

Thanks!

**Comment by DentonGentry** [comment]
We did change the names to align with what Synology needs for getting into the official Synology Package Center.
https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

However you're right that there is no 88f6282 build now, let's see if we can do that.

**Comment by danharvey** [comment]
Thanks that would be great please!

**Comment by brettbuddin** [comment]
Oh man, this would be great. I had v1.8.3 running perfectly on my older DS213. Would like to upgrade Tailscale.
