### ISSUE TITLE
After system crash, tailscale came back up with an old or truncated --advertise-routes config

### ISSUE THREAD

**Issue by markonen** [tailscale/tailscale#2321]
We’re running tailscale 1.10.0 on a Debian 10.9 system that is advertising a total of 15 routes (/32s on the loopback interface) using `--advertise-routes`.

This system suffered a power outage and came back with four of the most recently added routes missing. I noticed these routes where down after the outage and then saw a notice on the Tailscale web UI that the host had stopped advertising the routes. Sure enough, the `tailscale up` output of the existing config omitted these four routes.

I’m not sure whether the config reverted to a (several weeks) old version that had fewer routes, or if the list of routes was truncated to some maximum size. Regardless, this seems to be an issue with the state persistence mechanism.

**Comment by bradfitz** [comment]
Okay, I can reproduce now.

Diagnosis at https://github.com/tailscale/tailscale/issues/2383#issuecomment-877734825 (another bug like this one)

I have local script `blank-tailscaled` that starts a new wiped tailscaled world, and then `blank-tailscale` to talk to it.

If tailscaled is up, then `tailscale up` to edit preferences correctly writes the prefs to disk.

But if tailscaled is down (so the new LocalBackend.Start.UpdatePrefs is used), then it doesn't get persisted to disk:

```
bradfitz@tsdev:~$ blank-tailscale up
bradfitz@tsdev:~$ blank-tailscale debug -prefs
{
        "ControlURL": "https://controlplane.tailscale.com",
        "RouteAll": false,
        "AllowSingleHosts": true,
        "ExitNodeID": "",
        "ExitNodeIP": "",
        "ExitNodeAllowLANAccess": false,
        "CorpDNS": true,
        "WantRunning": true,
        "LoggedOut": false,
        "ShieldsUp": false,
        "AdvertiseTags": null,
        "Hostname": "blanktest",
        "OSVersion": "",
        "DeviceModel": "",
        "NotepadURLs": false,
        "AdvertiseRoutes": [
                "0.0.0.0/30"
        ],
        "NoSNAT": false,
        "NetfilterMode": 2,
        "Config": {
                "PrivateMachineKey": "privkey:0000000000000000000000000000000000000000000000000000000000000000",
                "PrivateNodeKey": "privkey:0000000000000000000000000000000000000000000000000000000000000000",
                "OldPrivateNodeKey": "privkey:0000000000000000000000000000000000000000000000000000000000000000",
                "Provider": "google",
                "LoginName": "bradfitz@tailscale.com"
        }
}
bradfitz@tsdev:~$ blank-tailscale up --advertise-routes=0.0.0.0/31 --hostname=blanktest
bradfitz@tsdev:~$ blank-tailscale debug -prefs | jq .AdvertiseRoutes
[
  "0.0.0.0/31"
]
bradfitz@tsdev:~$ cat ~/.config/tailscale-blank/tailscale.state | jq -r ._daemon | base64 -d | jq .AdvertiseRoutes
[
  "0.0.0.0/31"
]
bradfitz@tsdev:~$ blank-tailscale down
bradfitz@tsdev:~$ blank-tailscale up --advertise-routes=0.0.0.0/29 --hostname=blanktest
Success.
bradfitz@tsdev:~$ blank-tailscale debug -prefs | jq .AdvertiseRoutes
[
  "0.0.0.0/29"
]
bradfitz@tsdev:~$ cat ~/.config/tailscale-blank/tailscale.state | jq -r ._daemon | base64 -d | jq .AdvertiseRoutes
[
  "0.0.0.0/31"
]
```

/cc @schopenhauer @apenwarr @crawshaw

**Comment by bradfitz** [comment]
This looks broken starting at 1.8.0.

**Comment by bradfitz** [comment]
I'm a little amused it also only prints "Success." in the path where it doesn't work. We should probably also remove that print (The Rule of Silence, etc), at least in the case where that's the only output and no login or machine auth is needed.

**Comment by Xe** [comment]
I rely on that "Success" for integration tests.

**Comment by bradfitz** [comment]
@Xe, the integration tests can be updated. :)

**Comment by bradfitz** [comment]
@apenwarr, you want to take this one?
