### ISSUE TITLE
taildrop: receive files on linux needs sudo

### ISSUE THREAD

**Issue by mcristina422** [tailscale/tailscale#2324]
The [docs](https://tailscale.com/kb/1106/taildrop/) currently make it clear that `sudo tailscale file get .` is the proper way to receive files on linux. Although the error presented when missing `sudo` doesn't really make that apparent to the user.

```
$ tailscale file get .
getting WaitingFiles: HTTP 403 Forbidden: file access denied
 (expected 200)
```

related to https://github.com/tailscale/tailscale/issues/2312, where this UX confusion will get improved 
version: 1.10

**Comment by DentonGentry** [comment]
I think #2312 is sufficient to track the issue, closing as a dup.
