### ISSUE TITLE
Documentation for "tailscale web"

### ISSUE THREAD

**Issue by vielmetti** [tailscale/tailscale#2326]
In https://github.com/tailscale/tailscale/commit/c14dba105accbcbfd88b7d1382018e4dfe0c5b51 there is new code for a "tailscale web" command, which promises to provide a web interface for controlling Tailscale.

I am not sure if this has a documented use (I couldn't find any specific docs for it), and it's very much not clear if this is intended for use outside of Synology (?).

```
pi@pisdr:~ $ tailscale version
1.10.1
  tailscale commit: 6b6016130a794dd7332ff79abbb0a63a220d1dec
  other commit: 49e1dcc205c8e95f667a7d66b5f2484282041965
  go version: go1.16.4-tsa2a536c
```

**Comment by DentonGentry** [comment]
For now at least, it is intended for use with Synology and QNAP NAS devices.

**Comment by DentonGentry** [comment]
I think documenting tailscale web is premature at this point, its use is still evolving.

**Comment by bradfitz** [comment]
That said, we have a LongHelp field we weren't populating, so I added a few more words there in https://github.com/tailscale/tailscale/commit/a9fc58321198cf1b31b4a55ed0da017cf7039e80
