### ISSUE TITLE
Builds above 1.8.3 - tailscaled exits with error 'can't change --login-server without --force-reauth'

### ISSUE THREAD

**Issue by deasmi** [tailscale/tailscale#2335]
Hi. 
I look after a version of talscale for use with Unraid. 
https://github.com/deasmi/unraid-tailscale
https://forums.unraid.net/topic/90719-support-tailscale-support-thread/

It is essentially minor tweaks to the standard Dockerfile and some XML to make unraid happy.

Builds after 1.8.3 using existing state files exit with the following message 

'can't change --login-server without --force-reauth'

If the state file is removed everything works, although you have to re-authenticate and get a new IP address.
For many users this isn't ideal as servers tend to be pinned.

I cannot find reference to this message, can anyone point me in the right direction to troubleshoot this?

deasmi/unraid-tailscale#6

Thanks

**Comment by DentonGentry** [comment]
I guess the first question is if you know of any way that --login-server could be passed to `tailscale up` at any point? Looking at https://github.com/deasmi/unraid-tailscale the only way I could see that is if UP_FLAGS contained --login-server, but I doubt that is happening.

From https://github.com/deasmi/unraid-tailscale/commits/master it looks like 1.8.3 was the prior version used, then 1.10.1, so we don't know whether other 1.8.x releases had a problem (which is fine, you don't have to run every version, just making notes for the future).

Could you:
- get a machine in this state
- copy the long _daemon string from /state/tailscaled.state
- echo long_daemon_string | base64 -d.  <-- should produce a JSON struct
- REMOVE the Config section, which has things like PrivateMachineKey and PrivateNodeKey and things that shouldn't be put into a public bug report
- paste everything else here?

**Comment by deasmi** [comment]
Sorry I should have been more specific. I tracked this down to 1.8.4. So any build above 1.8.3 has this issue. 
There are builds on DockerHub but I didn't commit code to github.

You are correct, I am not passing any --login-server in UP_FLAGS.

```
{
        "ControlURL": "https://login.tailscale.com",
        "RouteAll": false,
        "AllowSingleHosts": true,
        "ExitNodeID": "",
        "ExitNodeIP": "",
        "CorpDNS": true,
        "WantRunning": true,
        "ShieldsUp": false,
        "AdvertiseTags": null,
        "Hostname": "",
        "OSVersion": "",
        "DeviceModel": "",
        "NotepadURLs": false,
        "AdvertiseRoutes": [],
        "NoSNAT": false,
        "NetfilterMode": 2,
}
```

**Comment by deasmi** [comment]
On a hunch I removed the ControlURL line, base64 encoded again and put back into the state file ( with the removed section ).

It now works, 

Stopping the container the config now includes 

'''
"ControlURL": "https://controlplane.tailscale.com",
'''
So clearly the logon server has changed.

Still question why tailscaled exits rather than prompting for a logon again though.

**Comment by deasmi** [comment]
https://gist.github.com/deasmi/01fe35c9d80589890b3757d181e424e6

This script can fix a tailscaled.state file, it just removes the ControlURL line.

**Comment by crawshaw** [comment]
The controlplane.tailscale.com URL is only in unstable. If you're seeing it mentioned in 1.10 that's a bug. The current server is still https://login.tailscale.com.

Is a login server reported in the error you see about force-reauth?

**Comment by DentonGentry** [comment]
[The Dockerfile](https://github.com/deasmi/unraid-tailscale/blob/master/Dockerfile) builds from source at the v1.10.1 tag point, so I think it will get a date.2021XXYY version not 1.10.1.

**Comment by DentonGentry** [comment]
The Dockerfile might instead install the release *.deb files adapting the steps in https://tailscale.com/kb/1039/install-ubuntu-2004/

If that doesn't work, If you want to consider using the release binaries, that would be something like:
```
FROM alpine:latest as tailscale
WORKDIR /app
COPY . ./
ENV TSFILE=tailscale_1.10.1_amd64.tgz
RUN wget https://pkgs.tailscale.com/stable/${TSFILE} && \
  tar xzf ${TSFILE} --strip-components=1
COPY . ./
```

**Comment by DentonGentry** [comment]
Oh, hang on: `git checkout -b v1.10.1` doesn't check out from the 1.10.1 release tag, it makes a new branch from HEAD and names the new branch "v1.10.1"

That is probably not what is intended, every user using this Dockerfile gets whatever was at HEAD at that moment.

**Comment by deasmi** [comment]
How embarrasing. 

Back to git 101 for me it seems, it's only been ten years...

That will explain a lot, and yes building HEAD and pretending it's 1.10.1 is certainly not what I intended.

I think perhaps to square one on this, using release binaries as you suggest, may well be the best way forward. 

So I will close this. Thank you @DentonGentry
