### ISSUE TITLE
Can't resolve names after connecting on macOS

### ISSUE THREAD

**Issue by rubenfonseca** [tailscale/tailscale#234]
**Describe the bug**
After connecting Tailscale on macOS, I can ping and connect to other nodes by IP but all DNS resolutions stopped working.

**To Reproduce**
1. Connect tailscale
2. Try to open any website
3. DNS fail

**Expected behavior**
I expect my local resolver to still be used instead of forcing to use Tailscale's.

**Screenshots**

Output of `scutil --dns` after connecting:

![image](https://user-images.githubusercontent.com/10713/77820352-f0e95f00-70e1-11ea-84cc-f29dbbb217d4.png)

The `100.90.7.1` doesn't resolve any name.

**Version information:**
 - Device: MacBook Pro 15 ice 2016 
 - OS: MacOS
 - OS version: 10.15.4
 - Tailscale version: 0.97.78 from App Store 

**Additional context**
First time trying Tailscale. No DNS settings in admin. As I said above, connectivity on the IP level is working fine.

**Comment by rubenfonseca** [comment]
Problem solved itself after rebooting.

**Comment by sigil66** [comment]
Not sure if this should be closed. Have experienced the same issue on another MacOS client system.
