### ISSUE TITLE
Exit node with overlapping subnet fails to access client behind subnet.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2350]
Is it possible to disconnect or selectively connect to specific machines from the client so that we are not connected to both at the same time? Then we could at least access the resources behind as required.

Engineering Analysis:

The client side code for selecting exit node just uses it to filter which 0/0 and ::0/0 routes are permitted: if the exit node ID matches, then they are allowed in, otherwise they are filtered out. It doesn't affect processing any route that's not a /0. On the other hand, Control passes along all /0 routes but invokes the HA subnet router logic for non /0 routes. So to support selecting which overlapping subnet router to use based on the exit node chosen will require both server and client side changes (and they'll be meaningfully large).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3clu9)

**Comment by DentonGentry** [comment]
Notes from bug scrub:
- on client device, using `tailscale up --accept-routes=false` might actually work. Select an exit node, and expect all traffic to go to it. However this is likely to be fragile as it relies on the intersection of undocumented behaviors.
- otherwise, need iptables DNAT

**Comment by elwood-djones** [comment]
I have tried the following with the suggested flag and the behaviour is the same:

Exit Node/subnet 1: `tailscale up --accept-routes=false --advertise-routes=10.0.0.0/8 --authkey=tskey-123 --advertise-exit-node --accept-routes=false`

Exit Node/subnet 2: `tailscale up --accept-routes=false --advertise-routes=10.0.0.0/8 --authkey=tskey-123 --advertise-exit-node --accept-routes=false` 

No matter which exit node that I connect to, I can only connect to instances behind whichever exit node was started first.

**Comment by bradfitz** [comment]
@elwood-djones, are you disabling accept-routes on your client?  e.g. on Mac, it's:

<img width="507" alt="Screen Shot 2021-07-09 at 8 27 08 AM" src="https://user-images.githubusercontent.com/2621/125101785-743c8300-e08f-11eb-9186-7def9af6e6c5.png">

"Use Tailscale Subnets". You want that unchecked.

The trick here is to make your subnet traffic leave your client via the exit node, not the HA subnet router currently handling that route. Then once it gets to the exit node, it should forward to the right place since that node is also advertising that route.

**Comment by elwood-djones** [comment]
@bradfitz - Thanks, that setting works.

**Comment by bradfitz** [comment]
@elwood-djones, so to confirm: you're able to switch exit nodes and hop between VPCs?

**Comment by elwood-djones** [comment]
Yes, that is correct. Turned off 'Use Tailscale Subnets' and used the same previous commands.

**Comment by DentonGentry** [comment]
At this point I don't see more to do for this issue, closing as fixed.
