### ISSUE TITLE
Tailscale isn't always playing nice with Wireguard

### ISSUE THREAD

**Issue by gregg098** [tailscale/tailscale#2354]
Running Tailscale 1.10.1 on Windows 10 Pro. I frequently switch between VPNs, mostly actual Wireguard and Tailscale. Lately, I've had a number of times where after I disconnect from the Wireguard connection and reconnect Tailscale, nothing connects. 

From a command prompt, if I issue a `tailscale ping <nodename>` I get the message:
`internal error: failed to create endpoint for discokey`

Disconnecting/reconnecting and re-opening the Tailscale app doesnt work. Restarting the Tailscale Windows service usually does however. If not, it requires a reboot.

Here is a bug report from right after I restarted the Windows service and it started talking again to other nodes.

BUG-61ce2ee8bb0e795527e34d5946c0df9155be4381fc2d9ca633f17aeadcf97f66-20210708022237Z-28a0b4f0338ebf93

EDIT: Also note that there are times I have both Wireguard and Tailscale running together at the same time (different routes, endpoints, IP ranges, etc.) and they play together just fine. Then others Tailscale just doesn't recover.

**Comment by crawshaw** [comment]
Thanks for the report. Which version of WireGuard?

**Comment by gregg098** [comment]
> Thanks for the report. Which version of WireGuard?

App version 0.3.16. Latest Windows version.

**Comment by DentonGentry** [comment]
At this point I don't expect to figure out the original issue. If a problem with a current Wireguard and Tailscale is noted, please file a new issue.
