### ISSUE TITLE
safesocket: TestBasics fails, unable to bind

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#2367]
On my linux VM:

```
$ go test ./safesocket/
--- FAIL: TestBasics (0.00s)
    basic_test.go:15: listen unix test: bind: operation not permitted
FAIL
FAIL	tailscale.com/safesocket	0.002s
FAIL
```

Input requested. cc @bradfitz

**Comment by bradfitz** [comment]
Distro, version? Regular user?

**Comment by josharian** [comment]
```
$ uname -a
Linux u 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:56:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Reproduces with both regular user and root.

**Comment by josharian** [comment]
Aha! This happens because the test tries to open a socket in the current working dir, and in this case that working dir is on a remotely mounted drive. Easy fix: open a socket in a temp dir. Fix coming.
