### ISSUE TITLE
Admin panel suppresses users with no devices, even Admin users

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2380]
A user with no devices does not appear in https://login.tailscale.com/admin/users, such as a user created by logging into https://login.tailscale.com directly not using a client application to log in.

Even a user with Admin privileges doesn't appear in the list if they have no devices. As the reporting user noted, "we have a stealth admin which is not what anyone wants."

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3d0k1)

**Comment by bradfitz** [comment]
Oh, I bet I know what this is.

**Comment by bradfitz** [comment]
Fix + tests (to prevent this from regressing again in the future) are submitted. It'll be deployed within the next couple days.
