### ISSUE TITLE
wireguard-windows rewrote its git history or something?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2381]
I just got a build failure:

```
go: tailscale.com@v1.1.1-0.20210709193031-7e7c4c1bbe24 requires
	golang.zx2c4.com/wireguard/windows@v0.3.15-0.20210525143335-94c0476d63e3: invalid version: unknown revision 94c0476d63e3
Error: Process completed with exit code 1.
```

And sure enough, that doesn't exist:

```
toe5k:wireguard-windows bradfitz$ git remote -v
origin	git://git.zx2c4.com/wireguard-windows (fetch)
origin	git://git.zx2c4.com/wireguard-windows (push)
toe5k:wireguard-windows bradfitz$ git pull
Already up to date.
toe5k:wireguard-windows bradfitz$ git show 94c0476d63e3
fatal: ambiguous argument '94c0476d63e3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

But it does exist if you look it up here:

https://git.zx2c4.com/wireguard-windows/commit/?id=94c0476d63e3

It's just no longer referenced by any heads?

But we reference that commit:

https://github.com/tailscale/tailscale/blob/38be964c2bfc650a69a5c92b75185eac94b388ae/go.mod#L42

So, @zx2c4, what's up with that? You rewriting history?

**Comment by zx2c4** [comment]
That repo rebases above tags, but never bellow. Use the tags and you'll be good. It's not a repo you want to be bleeding edge on anyway, as Windows stuff is tricky and finicky. `go get` should default to that anyway.

**Comment by bradfitz** [comment]
Okay. Curious, though: why?
