### ISSUE TITLE
Chromebook MagicDNS: consistently fails after sleeping for a few hours

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2382]
Version: v1.10.0-405ea978f8b (android)

Steps:
- Install tailscale using MagicDNS + SplitDNS (but not global override)
- Seems to work fine (both tailscale MagicDNS names, and other DNS)
- Close Chromebook for a few hours
- Resume

Expected:
Still works fine

Actual:
- DNS doesn't work anymore (MagicDNS or regular DNS). Web browser sits for a long time waiting for name resolution.
- In the Tailscale GUI, move the slider to Stopped
- Browser tab immediately says "connection interrupted" but if I reload, it's fine
- Move the Tailscale app GUI slider back to Active
- Browser still works fine

I think this suggests we need to rebind 100.100.100.100 after a suspend/resume or network change or something. I'm not sure why the problem triggers sometimes, or doesn't other times.

I'm not sure if this is new in v1.10 or not, since it's been a while since I seriously used my laptop for anything (thanks to COVID).

**Comment by mayakacz** [comment]
Need to test if this is still occurring since 1.20.

**Comment by DentonGentry** [comment]
I've tried for the last two nights to reproduce this on a Chromebook using the 1.28.0 version of the Android app, leaving the Chromebook sleeping overnight. Upon waking there is a delay before the tailnet starts to work of about 5 seconds, but it does recover. ChromeOS runs Android apps in a VM or Container and it might just take a moment for them to get fully spun up again.

I think we fixed this with the DNS changes made in 1.20.0. The app reacts to LinkProperties changes from Android and will turn them into minor LinkChange events.

**Comment by DentonGentry** [comment]
I don't think I can test this more:
- the Play Store doesn't allow download of the 1.10.x version
- Uploading a new build is required to target API level 30, the 1.10.x APK was built to API level 29
- Updating the 1.10.x code to API level 30 breaks the app (https://github.com/tailscale/tailscale/issues/2290). We'd have to backport the new Interfaces handling

I don't have a Chromebook where I can reasonably sideload a debug-build 1.10.

**Comment by DentonGentry** [comment]
I think this is fixed, probably in 1.20. I have not been able to produce it after leaving the Chromebook asleep overnight several times.
