### ISSUE TITLE
Tray icon/applet for Tailscale app in Linux

### ISSUE THREAD

**Issue by schopenhauer** [tailscale/tailscale#2387]
It would be nice to see a tray icon/applet for the Tailscale app in Linux environments, similar to the one in MacOS (see below).

![image](https://user-images.githubusercontent.com/2085103/125186310-ecd74700-e229-11eb-84d6-952b42fcdb03.png)

**Comment by DentonGentry** [comment]
There are a couple that have been developed, one I know of is https://github.com/muchobien/tailscale-ui

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1708
