### ISSUE TITLE
Cannot Access Internet Through Exit node on iOS

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2388]
Hi there,

Can't access the internet from Exit node using iOS client. Works fine on MacOS.

Thanks!

**Comment by bradfitz** [comment]
What versions? What Tailscale IPs?

**Comment by vysecurity** [comment]
MacOS Client: 1.10.1
iOS Client: 1.10.1 (latest App Store version)
Server: 1.10.1

Server TS IP: 100.69.172.108

**Comment by DentonGentry** [comment]
Do you have other VPN clients installed? I think that iOS device is trying to use an ipsec tunnel, which isn't something Tailscale creates.
