### ISSUE TITLE
Subnet routes no longer working with 1.10.1

### ISSUE THREAD

**Issue by 24788329** [tailscale/tailscale#2389]
I previously had Tailscale subnet routes working wonderfully with a Raspberry Pi subnet router by following the [Tailscale docs](https://tailscale.com/kb/1019/subnets/). I was able to directly access machines using their LAN IPs both within and outside of my network. 

After upgrading to 1.10.1, subnet routes are no longer working. LAN IP connections are blocked both within and outside my network. For example, with subnet routes enabled, I can no longer SSH to a LAN machine using its LAN IP. I can only SSH using its Tailscale IP. I've tried deleting and reinstalling without success. I've also tried using a non-Pi Ubuntu Linux server as the subnet router with the same results. Tested using Linux and iOS clients.

The only machine I can still connect to using both LAN and Tailscale IPs with subnet routes enabled is whichever device is acting as the subnet router.

What can I try to fix this problem?

**Comment by apenwarr** [comment]
Is there a chance your subnet relay's firewall configuration has changed? If the OS is dropping packets in iptables (ufw, etc), then Tailscale won't be able to get them through. Also make sure kernel-level sysctl for IP forwarding is enabled.

One thing to try would be to ping the subnet IP of the relay itself, via Tailscale. If that works, then the routing is working, but forwarding on the subnet relay itself is not, and is probably blocked by the kernel.

**Comment by DentonGentry** [comment]
This might be https://github.com/tailscale/tailscale/issues/2321 impacting the subnet router machine.

If so, we expect to fix it in 1.10.2. In the meantime, you should be able to restore it on the Raspberry Pi by:
`tailscale up --reset --force-reauth --advertise-routes=w.x.y.z/q,etc`

This will make it go through a state transition which does properly write out the preferences.

It would be best to do this using an SSH session to a LAN IP address, if anything goes wrong the tailscale interface is likely to be left in a down state.

**Comment by 24788329** [comment]
> If so, we expect to fix it in 1.10.2. In the meantime, you should be able to restore it on the Raspberry Pi by:
> `tailscale up --reset --force-reauth --advertise-routes=w.x.y.z/q,etc`

1) I upgraded to 1.10.2 but the issue still persisted
2) I then tried the above command on the Pi (subnet router) alone and it still didn't work
3) After running `tailscale up` with the `--reset` and `--force-reauth` flags on all Tailscale machines, subnet routing is now working again

Thanks for the helpful suggestion.
