### ISSUE TITLE
Connectivity issue with Tailscale 1.10.0.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2393]
Few customers reported the connectivity issue with Tailscale 1.10.0/1.10.1.

A pair of nodes where connectivity can be established if node A initiates but not if node B does, but once A has established a connection then B can reach A.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3d61d)

**Comment by DentonGentry** [comment]
Though there will be little activity on this bug, we have multiple engineers actively working on it.

Much of the work involves information from trouble reports communicated to support@, which we cannot put in a public bug report.

**Comment by llewxam-kache** [comment]
Thanks @DentonGentry , let me know whatever is needed, we'd love to find a solution as fast as possible!

**Comment by DentonGentry** [comment]
We've managed to reproduce an issue in-house which matches many of the symptoms reported. A cannot contact B until B contacts A.

**Comment by bradfitz** [comment]
For those following this bug, things should be all working now. More updates later.

**Comment by llewxam-kache** [comment]
Hi, we're still seeing some minor connectivity issues, but a majority of the issues have been solved.

**Comment by DentonGentry** [comment]
I'll close this as the more widespread issue has been resolved as of Monday at 4pm Eastern time, with no sign of recurrence since.

@llewxam-kache if you could either file a separate issue with details, or send to support@tailscale.com, we can followup.
