### ISSUE TITLE
Tags not available in API

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2403]
https://api.tailscale.com/api/v2/tailnet/example.com/devices?fields=all does not return the tags assigned to a device, and it would be quite useful if it did.

**Comment by neilisaac** [comment]
This would be very useful.  A concrete use case I have is to write an Ansible dynamic inventory plugin with machines automatically grouped by tag.

**Comment by DentonGentry** [comment]
Duplicate of #1360
