### ISSUE TITLE
Synology - Creation of interface tailscale0 - Permission denied

### ISSUE THREAD

**Issue by voiddaek** [tailscale/tailscale#2407]
I recently updated my NAS (DS218+) from DSM 6 to DSM 7 as well as tailscale from 1.8.3 to 1.10.
Everything went perfectly fine. The tailscale ip changed but it was expected from what the repo mentions.

After changing the tailscale ip that were configure in some docker to the new ones. I noticed that I was getting timeouts on the new tailscale ip. For information the docker were running on the NAS and trying to reach the NAS tailscale IP.
This used to work prior to the updates. I can't say if it is because of the tailscale update or the NAS but nonetheless thanks to @DentonGentry  I found "a reason".

Looking at the tailscale log:
```txt
Program starting: v1.10.0-t766ae6c10-g3e6822772, Go 1.16.4-tsa2a536c: []string{" /volume1/@appstore/Tailscale/bin/tailscaled", "--state=/volume1/@appdata/Tailscale/tailscaled.state", "--socket=/volume1/@appdata/Tailscale/tailscaled.sock", "-port=41641"}
LogID: d812eacc441e2d019144d582bcb87c5c528333014c372cbf28cf5a093222015b
logpolicy: using $STATE_DIRECTORY, "/volume1/@appdata/Tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 4.4.180+
'modprobe tun' successful
/dev/net/tun: Dcrw-------
wgengine.NewUserspaceEngine(tun "tailscale0") error: permission denied
wgengine.NewUserspaceEngine(tun "userspace-networking") ...
dns: using dns.noopManager
```
**`wgengine.NewUserspaceEngine(tun "tailscale0") error: permission denied`**
It appears that when I start the service with the ui, it will fail to create the tailscale0 interface. But if I start tailscale service manually in combination with sudo then the interface is created without problem.

So it seems like there is a problem of privilege for creating those interface.
Tailscale is coming with [this](https://github.com/tailscale/tailscale-synology/blob/main/src/privilege-dsm7): 
`"capabilities": "cap_net_admin"`
Maybe it's not working anymore in DSM 7 ? Maybe it needs more ? 

On a other note, in the script [start-stop-status](https://github.com/tailscale/tailscale-synology/blob/main/src/scripts/start-stop-status) there is 
```bash
ensure_tun_created() {
    if [ "${SYNOPKG_DSM_VERSION_MAJOR}" -eq "7" ]; then
        # TODO(maisem/crawshaw): Disable the tun device in DSM7 for now.
        return
    fi
    # Create the necessary file structure for /dev/net/tun
    if ([ ! -c /dev/net/tun ]); then
        if ([ ! -d /dev/net ]); then
            mkdir -m 755 /dev/net
        fi
        mknod /dev/net/tun c 10 200
        chmod 0755 /dev/net/tun
    fi
    # Load the tun module if not already loaded
    if (!(lsmod | grep -q "^tun\s")); then
        insmod /lib/modules/tun.ko
    fi
}
````

It did not seems to create the /dev/net/tun file as well when I start tailscale.
But I could create it manually using the same script. So again maybe some privilege issue.

I don't know if this problem is only relevant to myself (DSM configuration) or if other people have the same issue.

**Comment by voiddaek** [comment]
Apparently setting root in the privilege file fixed the issue for me. So basically using [privilege_dsm6](https://github.com/tailscale/tailscale-synology/blob/main/src/privilege-dsm6) file instead of [privilege_dsm7](https://github.com/tailscale/tailscale-synology/blob/main/src/privilege-dsm7)

### privilege_dsm7
```bash
{
  "defaults":{
    "run-as": "package"
  },
  "username": "tailscale",
  "groupname": "tailscale",
  "capabilities": "cap_net_admin"
}
```
### privilege_dsm6
```bash
{
  "defaults":{
    "run-as": "root"
  },
  "username": "tailscale",
  "groupname": "tailscale",
  "capabilities": "cap_net_admin"
}
```

Only the run as is different but it allows tailscaled to create tailscale0 interface.
For people looking for the privilege file in the synology, it's in /var/packages/Tailscale/conf

**Comment by bradfitz** [comment]
@voiddaek, Synology won't accept that into their official store, but we're working with them on finding a way to create the TUN node with minimal capabilities without going all the way to being root.

/cc @maisem

**Comment by ThomasDalla** [comment]
> @voiddaek, Synology won't accept that into their official store, but we're working with them on finding a way to create the TUN node with minimal capabilities without going all the way to being root.
> 
> /cc @maisem

Is there any progress running Tailscale official package on DSM7 without running as root?

**Comment by bradfitz** [comment]
See https://tailscale.com/kb/1152/synology-outbound/ for instructions.

It requires Tailscale 1.12.4 which should appear in the Synology Package Center very soon, if not today.

**Comment by ThomasDalla** [comment]
Great news, thanks for the update!

I'm using the Entware oPKG version for now (`1.12.3`) until the package is available.
```
$ opkg info tailscale
Password: 
Package: tailscale
Version: 1.12.3-1
Depends: libc, libssp, librt, libpthread, ca-bundle
Status: install user installed
Section: lang
Architecture: armv7-2.6
Size: 7089269
Filename: tailscale_1.12.3-1_armv7-2.6.ipk
Description: Zero config VPN. Installs on any device in minutes, manages firewall rules for you, and works from anywhere
Installed-Time: 1630944521
```

**Comment by voiddaek** [comment]
I updated to the newly released version of Tailscale synology in the package manager (1.12.4-2006).
But unfortunately for me it did not correct my initial problem. 
`wgengine.NewUserspaceEngine(tun "tailscale0") error: permission denied`
I am still forced to use my previously stated solution.

**Comment by bradfitz** [comment]
@voiddaek, did you see https://tailscale.com/kb/1152/synology-outbound/ ?

**Comment by bradfitz** [comment]
We won't be breaking that link.

And, yes, as the instructions say:

> This step is required every time you upgrade Tailscale

We're still working with Synology to be able to request enough permissions that we won't need to make users do this step in the future. DSM7 locks things down for us a bit too tightly.
