### ISSUE TITLE
Lots of `rejected` logs in DERP server with `verify-clients` on

### ISSUE THREAD

**Issue by maddie** [tailscale/tailscale#2408]
I have a server that runs `tailscaled` as a node and `derper` as a DERP server.

When I have `-verify-clients` option turned on, a lot of these lines being printed in the system log:

```
derp: 127.0.0.1:35730: client xxxxxxxxxxx rejected: client [11 22 33 44 55 66 ] not in set of peers
```

`xxxxxx` is the server's public key (runs `tailscaled` and `derper`), as confirmed with `tailscale status --json`.

Also another question, how can I check to see if the DERP server is running properly?

**Comment by DentonGentry** [comment]
Most likely:
You are now running a server on the open Internet. It came under attack within minutes of being put online.
The ssh logs will be similarly full of unsuccessful login attempts.

For monitoring:
You could run a Nagios instance, or a service like cloudradar.io. Monitoring of a server like this is outside of the scope of what Tailscale would provide.

**Comment by maddie** [comment]
Looking into it a bit, from the output of `tailscale status --json`, it seems that the Self node's public key isn't in the `Peer`s, maybe it's because the DERP server only checks for keys in the `Peer`s map, and when the node itself connects to the DERP server on the same machine, it won't be present in the `Peer`s?

**Comment by bradfitz** [comment]
Good find. @JulianKnodt, want to send a fix to also permit the self node?

**Comment by maddie** [comment]
@bradfitz I added the following line in `derp/derp_server.go`'s `verifyClient` receiver function and it works:

```go
func (s *Server) verifyClient(clientKey key.Public, info *clientInfo) error {
	if !s.verifyClients {
		return nil
	}
	status, err := tailscale.Status(context.TODO())
	if err != nil {
		return fmt.Errorf("failed to query local tailscaled status: %w", err)
	}
        // I added this here
	if clientKey == status.Self.PublicKey {
		return nil
	}
	if _, exists := status.Peer[clientKey]; !exists {
		return fmt.Errorf("client %v not in set of peers", clientKey)
	}
	// TODO(bradfitz): add policy for configurable bandwidth rate per client?
	return nil
}
```

I can send a PR if that's the right place to add this code.

**Comment by bradfitz** [comment]
Yup, that's the fix. Feel free to send a PR.
