### ISSUE TITLE
net/nettest: TestPipeTimeout flake

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2419]
This is back:

https://github.com/tailscale/tailscale/pull/2417/checks?check_run_id=3061069641
```
--- FAIL: TestPipeTimeout (0.04s)
    --- FAIL: TestPipeTimeout/block-write (0.03s)
        pipe_test.go:64: i/o timeout
FAIL
exit status 1
FAIL	tailscale.com/net/nettest	0.629s
```

Previously: #873 #1044

**Comment by josharian** [comment]
ARGH.

I just ran this test several hundred thousand times on the builder without failure: https://github.com/tailscale/tailscale/pull/2420.

I'll look again if it flakes again. Until then, I'm calling this cosmic rays. GitHub Actions Neutrinos strike again.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/3451 a few months after this was filed.
