### ISSUE TITLE
Auto-approve subnet routes if permitted based on ACL policy

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2425]
Currently to share a subnet, you have to run `tailscale up --advertise-routes=<whatever>` and then separately approve the routes in the admin panel. This is for security and privacy reasons (double opt-in). However, it makes automation more difficult, especially when used with authkeys and eg. Terraform.

As a way to relax the restriction without creating a security risk, we could pre-grant subnet relaying permissions to particular users or tags in the ACL policy, similarly to the TagOwners section. The rule could say something like "allow ops@example.com to advertise any subnet in 10.0.0.0/8" or "allow tag:router to advertise subnets 192.168.0.0/24 or 192.168.10.0/24". If a subnet advertisement (and its owner) matches such a rule, we could skip the admin panel activation step.

(I thought we had a bug for this already but I can't find it)

**Comment by DentonGentry** [comment]
In the meantime, the API can be used to set approved routes: https://github.com/tailscale/tailscale/blob/main/api.md#post-apiv2devicedeviceidroutes---set-the-subnet-routes-that-are-enabled-for-a-device

**Comment by DentonGentry** [comment]
I think the prior bug you're remembering is https://github.com/tailscale/tailscale/issues/2121

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2121
