### ISSUE TITLE
MIPS packages/binaries

### ISSUE THREAD

**Issue by jaxxstorm** [tailscale/tailscale#243]
**Is your feature request related to a problem? Please describe.**

Not a problem, but some network gear like Unifi is MIPS based:

```
admin@ubnt:~$ uname -a
Linux ubnt 3.10.107-UBNT #1 SMP Fri May 17 16:26:51 UTC 2019 mips64 GNU/Linux
```
It might be desirable to run tailscale on perhaps your router, and then do forwarding that wat

**Describe the solution you'd like**

Ideally I'd to see the packages/binaries built with goreleaser, so adding new architectures isn't hard! I managed to successfully build a binary with go build that worked as needed on a MIPS device pretty easily though:

```
GOOS=linux GOARCH=mips GOMIPS=softfloat go build -o /tmp/tailscale ./cmd/...
```

**Describe alternatives you've considered**

Buying different network hardware? Seems like overkill ;-)

**Comment by danderson** [comment]
We're using redo rather than goreleaser, but MIPS shouldn't be too hard given that Go supports it. I'll give it a spin in a little bit.

**Comment by bradfitz** [comment]
Most of the Tailscale team have lots of Unifi gear, so this would be interesting. Did you actually get it working usefully on Unifi?

(the build part is pretty easy, but we don't want to release binaries that aren't useful)

**Comment by jaxxstorm** [comment]
Yep, it works without much issue. The biggest hassle is getting the stuff to stick around after provisioning. I managed to run `tailscaled` and `tailscape up -advertise-routes` and then confirmed they're working as expected, so I don't think it'd be be an issue

**Comment by danderson** [comment]
Done, https://pkgs.tailscale.com/unstable now has a MIPS tarball. I didn't make debs or rpms, because MIPS support is shaky at best there :/.

mips-linux is now in our CI too, so we'll catch build problems.

**Comment by georgebashi** [comment]
Could you also add a `GOARCH=mipsle` target please? Some common EdgeOS devices (like the ER-X) run that architecture.

**Comment by mazzy89** [comment]
Hey @danderson did you make any progress in forcing to stick around Tailscale? I'm running it but at every provision, it just disappears and expect to build something like this https://github.com/WireGuard/wireguard-vyatta-ubnt I do not see any other possibilities.

**Comment by mikeburgh** [comment]
I think to get around the reboot/provision issue you need to look at something like this: 
https://github.com/mafredri/vyatta-wireguard-installer

Obviously ported to install TailScale instead, and not sure how you re auth it after the reboot/provision yet, still tinkering with getting it installed in a UDM Pro.

**Comment by bradfitz** [comment]
@georgebashi, done: https://pkgs.tailscale.com/unstable/#static now has both mips and mipsle.

**Comment by jasondinh** [comment]
@georgebashi Are you able to start tailscaled on your ER-X?

**Comment by georgebashi** [comment]
@jasondinh Yep! I just upgraded my EdgeRouter 12 and 10X to the latest unstable, `1.1.335-g35ef2b4f8`, working great. ER-12 is `mips` and ER-10X is `mipsle`.

**Comment by jasondinh** [comment]
@georgebashi Thanks, I forgot `admin` user is not a superuser. Ran with sudo and it's all good now. This thing is god damn magic.

**Comment by lg** [comment]
wrote a quick gist on how to install it in a way that should survive system upgrades: https://gist.github.com/lg/6f80593bd55ca9c9cf886da169a972c3

**Comment by dtel** [comment]
Issues on UDM (arm64) using v1.4.3. 

After executing ```sudo tailscaled && sudo tailscale up --advertise-routes=192.168.1.0/24 --accept-routes``` i do not get a url to authenticate, but just blocks and prints nothing. I have tried adding tskey, but facing same issue.

Looked at ```tailscaled``` logs and getting a batch of errors:
```
control: authRoutine: backoff: 30573 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: connect: network is unreachable (in 1ms)
logtail: upload: log upload of 12664 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/103733847adf5a4cdd580c6773e6985700820d8b5dcb24123d023c3e6f8b684c": dial tcp 34.210.105.16:443: connect: network is unreachable
logtail: backoff: 43662 msec
control: authRoutine: state:authenticating; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": dial tcp [2a05:d014:386:203:f8b4:1d5a:f163:e187]:443: connect: network is unreachable
control: authRoutine: backoff: 22231 msec
control: authRoutine: state:authenticating; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
Received error: TryLogin: fetch control key: Get "https://login.tailscale.com/key": dial tcp [2a05:d014:386:203:f8b4:1d5a:f163:e187]:443: connect: network is unreachable
control: authRoutine: backoff: 29072 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: connect: network is unreachable (in 17ms)
logtail: upload: log upload of 12664 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/103733847adf5a4cdd580c6773e6985700820d8b5dcb24123d023c3e6f8b684c": dial tcp 34.210.105.16:443: connect: network is unreachable
logtail: backoff: 37215 msec
```
Please assist.

**Comment by bradfitz** [comment]
@dtel, we don't use bugs that are closed. Open a new one for a new/different issue.

**Comment by sashkavas** [comment]
dtel, upgrade to 1.4.4
