### ISSUE TITLE
subnet routes still advertised if tailscaled is not running

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2430]
Reported by a user:
_There seems to be a bug with multiple subnet routers in which routes are still advertised if Tailscale is down on the oldest subnet router. The routes should not be advertised if Tailscale is down. Seems to affect the failover. I was not able to route until I disable the routes on the admin console._

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3dpjl)

**Comment by kelcya** [comment]
Just to clarify. I had 2 subnet routers advertising 2 different routes.

E.g
Relay A - 10.0.0.0/16, 172.16.0.0/16

Relay B- 10.0.4.0/24, 10.0.5.0/24, 172.16.1.0/24, 172.16.4.0/24, 172.16.5.0/24

I downed tailscale on relay A. The Relay A routes were still advertised on my local tailscale client.

**Comment by DentonGentry** [comment]
I think we'll address #2434 (filed partly in response to this) and it will also handle this symptom.

**Comment by DentonGentry** [comment]
The fix for https://github.com/tailscale/tailscale/issues/2434 should have resolved this.
Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT
