### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by TechBear74** [tailscale/tailscale#2432]
{"logtail": {"client_time": "2021-07-15T07:44:18.3155899+02:00"}, "text": "backend error: TUN: Error creating interface: Cannot create a file when that file already exists.\n\nlogid: 521aef8a35b8835ed34aea4250c653cf40b5025da94a0528f7e845f11315cfe7\n"}

**Comment by Xe** [comment]
Why did you close the issue?

**Comment by TechBear74** [comment]
Hi because I reinstalled and when that didn't work I rebooted the PC then
everything worked.
