### ISSUE TITLE
Tailscale and HackerNews gaming allegations

### ISSUE THREAD

**Issue by gophobic** [tailscale/tailscale#244]
Hi and thanks for the great project. This isn't really a bug report but for I apologize I am not really familiar with it but I cannot find anywhere else to contact you about this. It seems Tailscale has been featured suspiciously very frequently throughout the past few weeks. It seems that a few noticed that this is really unnatural especially for a community like HN. Is this true and you're gaming the website with organized upvoting or this is some really good streak of coincidences that almost every post that's about this company becomes featured?

**Comment by bradfitz** [comment]
We're not gaming anything. Please let's keep this issue tracker only about bugs.
