### ISSUE TITLE
util/deephash: ambiguous hashing when using AppendTo

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#2443]
In this snippet: https://github.com/tailscale/tailscale/blob/391207bbcf11171bd3fbf6a8667f94fea0b1e23f/util/deephash/deephash.go#L141-L147
we blindly use the `AppendTo` without any form of framing.

Hashing shares many properties with formatting/parsing. If the format used for hashing cannot be parsed in an unambiguous way, then it implies that two different values may hash to the same thing.

Here's an example of two different values with the same hash:
```go
type bytes []byte

func (p bytes) AppendTo(b []byte) []byte {
	return append(b, p...)
}

func main() {
	fmt.Printf("%x\n", deephash.Hash([]bytes{{}, {0, 0, 0, 0, 0, 0, 0, 1}})) // b716e801d6be55e4999e0f72dc570689b8b002775af6cdb2344103187aed5dbe
	fmt.Printf("%x\n", deephash.Hash([]bytes{{0, 0, 0, 0, 0, 0, 0, 1}, {}})) // b716e801d6be55e4999e0f72dc570689b8b002775af6cdb2344103187aed5dbe
}
```

A trivial way to fix this is to prepend the size to the `AppendTo` output.

\cc @bradfitz

**Comment by josharian** [comment]
I'm not sure that prepending the size is a complete fix. You might still get collisions with other kinds of hashed output, exactly because AppendTo allows arbitrary output. We probably need a (type, length) tuple, where type is itself probably a (length, data) tuple.

(E.g. do we correctly distinguish between `uint16(1)` and `int16(1)` right now?)

The other question is whether we aim for correctness against adversarial inputs. The existing system is probably "good enough for government work" in that the likelihood of accidents is very low, albeit not as a low as the probability of a collision from the underlying sha256 hash function.

**Comment by bradfitz** [comment]
I'd rather we do it correctly so we don't have to worry about whether future use cases are suitable for the "good enough" implementation.

**Comment by dsnet** [comment]
The principle for collision-free hashes (assuming the `hash` itself is a sufficiently conflict-free hashing algorithm) is whether the format written to `hash.Write` can be unambiguously parsed. For a given Go type, every record written should either always be fixed size, or variable length with sufficient information to denote when the record terminates. If either condition is met, then unambigious parsing is possible since we know the Go type for every record written.

Other cases of ambiguous parsing:
* [Interfaces are formatted as is without any type information](https://github.com/tailscale/tailscale/blob/e2eaae8224faf5ba2e5ae494e9ee357a60af2799/util/deephash/deephash.go#L328). This means any two values of different concrete types that happen to format the same way will have the same hash.

Cases of unnecessary disambiguation:
* It is unnecessary to [write the index for every slice element](https://github.com/tailscale/tailscale/blob/e2eaae8224faf5ba2e5ae494e9ee357a60af2799/util/deephash/deephash.go#L192) since we already [write the length for the entire slice](https://github.com/tailscale/tailscale/blob/e2eaae8224faf5ba2e5ae494e9ee357a60af2799/util/deephash/deephash.go#L175).
* The [struct field index](https://github.com/tailscale/tailscale/blob/e2eaae8224faf5ba2e5ae494e9ee357a60af2799/util/deephash/deephash.go#L166) would only be necessary unless we permitted sparse formatted of structs, which we don't seem to do.

**Comment by josharian** [comment]
> we know the Go type for every record written.

I don't think we do record this right now. But I agree that we need to.

> The principle for collision-free hashes [...] is whether the format [...] can be unambiguously parsed. 

This could get expensive with cyclical data structures. Is there anything cheaper we can do for them?

**Comment by dsnet** [comment]
Here's another hashing collision:
```go
i1 := 1
i2 := 2
v1 := [3]*int{&i1, &i2, &i1}
v2 := [3]*int{&i1, &i2, &i2}

fmt.Println(reflect.DeepEqual(v1, v2)) // false
fmt.Printf("%x\n", deephash.Hash(v1))  // 64c9e899b57d9ba6242e2559b43d672b9a222cc6ca19ce26fd480bc0dd64e06c
fmt.Printf("%x\n", deephash.Hash(v2))  // 64c9e899b57d9ba6242e2559b43d672b9a222cc6ca19ce26fd480bc0dd64e06c
fmt.Println(cmp.Diff(v1, v2))          /*
	  [3]*int{
	  	&1,
	  	&2,
	- 	&1,
	+ 	&2,
	  }
*/
```

This occurs because the current cycle detection logic naively assumes that having seen a pointer before implies that it was equal.

**Comment by dsnet** [comment]
> (E.g. do we correctly distinguish between uint16(1) and int16(1) right now?)

Sometimes yes, and sometimes no.

Here's a collision:
```go
fmt.Printf("%x\n", deephash.Hash(float64(0))) // 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9
fmt.Printf("%x\n", deephash.Hash(int64(0)))   // 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9
```
