### ISSUE TITLE
Provisioning large number of servers with no key expiry

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2446]
A user provisioning a large number of servers using authkeys asks for a way to automate the disabling of node key expiration.

This might be done via the API, or perhaps via properties of the authkey.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3dzo1)

**Comment by kpfleming** [comment]
Looks like a duplicate of #2418.

**Comment by DentonGentry** [comment]
Dup of #2418, forgot I'd already filed it.
