### ISSUE TITLE
ChromeOS+crostini installation steps are confusing and crash crostini

### ISSUE THREAD

**Issue by dg9999cn** [tailscale/tailscale#245]
I try to install tailscale in chromeos at its linux terminal by using debian stretch. When run tailscale up, I got the following error;sudo tailscale up
logtail started
Program starting: v0.97-45-g02c73501: []string{"tailscale", "up"}
LogID: 802........................a85
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686714302087) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
You need to be running tailscaled before you can run tailscale.

**Comment by skarra** [comment]
Just to be clear, per the Linux installation instructions there is no explicit action to start tailscaled.

![image](https://user-images.githubusercontent.com/633395/78420574-266fda00-7605-11ea-8a32-8e836c96c6f0.png)

I ran into the same issue as OP in Crostini on a corp Pixelbook. I am not sure if something is blocked per our corp policy, or something about Crostini itself. Also on a "proper" debian box your instructions just worked.

@bradfitz  - is tailscale known to work with Crostini?

**Comment by bradfitz** [comment]
Yes, I've heard tailscale works in Crostini. @apenwarr uses it IIRC, and we've heard a number of reports of people using it successfully. I haven't tried it myself as I don't have a ChromeOS device at the moment.

There's no explicit docs to start tailscaled because `apt-get install tailscale`'s post-install step should be doing that automatically. I don't know which distro/init system Crostini uses. Perhaps it's different enough that the post-install isn't working.

/cc @danderson

**Comment by dg9999cn** [comment]
> You need to be running tailscaled before you can run tailscale.
Sorry, I am not English native speaking. 
Do you mean to sudo tailscaled before sudo tailscale up? 
This is what I got, still don't work.

~$ sudo tailscaled
2020/04/04 19:13:45 logpolicy.Read /root/.cache/Tailscale/tailscaled.log.conf: open /root/.cache/Tailscale/tailscaled.log.conf: no such file or directory
logtail started
Program starting: v0.97-45-g02c73501: []string{"tailscaled"}
LogID: 5d.............41
17.8M/31.9M Starting userspace wireguard engine.
17.8M/31.9M external packet routing via --tun=tailscale0 enabled
17.9M/31.9M CreateTUN ok.
18.1M/31.9M Routine: event worker - started
18.2M/31.9M Interface set up
magicsock.Conn: starting endpoint update (initial)
18.3M/32.3M Device closing
19.0M/33.0M UDP bind has been updated
19.0M/33.0M Routine: event worker - stopped
magicsock.Conn.determineEndpoints: updateNetInfo: got STUN error: context canceled; missing replies from: derp1.tailscale.com:3478, derp2.tailscale.com:3478, derp3.tailscale.com:3478, derp4.tailscale.com:3478
magicsock.Conn: endpoint update (initial) failed: got STUN error: context canceled; missing replies from: derp1.tailscale.com:3478, derp2.tailscale.com:3478, derp3.tailscale.com:3478, derp4.tailscale.com:3478
18.9M/33.0M Interface closed
18.9M/33.0M NewUserspaceEngineAdv: exec: "iptables": executable file not found in $PATH
panic: close of closed channel

goroutine 1 [running]:
github.com/tailscale/wireguard-go/tun.(*NativeTun).Close(0x4000112200, 0x1a, 0x400001e0a0)
        /home/bradfitz/src/tailscale.io/wireguard-go/tun/tun_linux.go:377 +0xc4
tailscale.com/wgengine.NewUserspaceEngine(0x40000feaa0, 0x56a93a, 0xa, 0x0, 0x6, 0x73, 0x4000157ec8, 0x1)
        /home/bradfitz/src/tailscale.io/oss/wgengine/userspace.go:88 +0x2b0
main.main()
        /home/bradfitz/src/tailscale.io/oss/cmd/tailscaled/tailscaled.go:73 +0x710
dg9999@penguin:~$ sudo tailscale up
logtail started
Program starting: v0.97-45-g02c73501: []string{"tailscale", "up"}
LogID: 802........a85
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

**Comment by bradfitz** [comment]
> 18.9M/33.0M NewUserspaceEngineAdv: exec: "iptables": executable file not found in $PATH

Install iptables. I filed #254 so our packages depend on that and so apt-get will auto-install it.

**Comment by dg9999cn** [comment]
After install iptables, Control connection done. Ping work, I can see my device in admin console. but can't access my other device(100.x.x.x) via chrome. I guess it's about the linux and chrome is separated in some way in chromeos design. my other device(100.x.x.x) is web server.
~$ ping 100.x.x.x 
PING 100.x.x.x 56(84) bytes of data.
64 bytes from 100.x.x.x: icmp_seq=1 ttl=64 time=15.0 ms

**Comment by bradfitz** [comment]
> I guess it's about the linux and chrome is separated in some way in chromeos design.

Yes. In Crostini, only the sandbox can access the Tailscale network, not Chrome itself.

This will be fixed with our upcoming Android app.
