### ISSUE TITLE
Android: streamline login process

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2451]
In the Android app when you sign in you are presented with:
![Screenshot_20210718-072706](https://user-images.githubusercontent.com/1140756/126071031-4e544a10-e2d6-4956-bd63-3cc011d344f6.png)

If you select "Sign in with Other" you are redirected to a browser which gives the full set of options:
![Screenshot_20210718-073144](https://user-images.githubusercontent.com/1140756/126071181-b39cd94c-7188-4495-b721-3696f9064f0e.png)

I don't think the native Google login is really helpful, and I don't see a downside to having it always redirect to browser login. That would work better for the F-droid version as well.

**Comment by bradfitz** [comment]
The extra UI step sucks but the auth mechanism it uses should remain at least, when available. It's much lower effort and thus more likely to succeed than a user entering a password into a web form.

Maybe we can pass a "use device auth for Google" bit through the auth flow if they pick Google and then have the device auth flow take over.

Or we just add a GitHub button to the Android native UI and skip a web step if they click that.
