### ISSUE TITLE
Exit Node does not block local LAN on Windows 7

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2453]
On Windows 7 (32 bit) when using an exit node with the "Allow local LAN access" setting unchecked, expecting to block access to the local LAN, LAN access is not blocked. I can ping the node, connect to it via RDP, etc.

I'm using a tailscale.exe built from HEAD on 18 Jul 2021.

This may happen on Windows 7 (64 bit) as well, I've never managed to get a Win7-64 system working in a VM here.

<img width="431" alt="Screen Shot 2021-07-18 at 8 33 45 AM" src="https://user-images.githubusercontent.com/1140756/126073206-20a0297e-1bb4-4794-aedb-9e6a9a8b7fbb.png">

**Comment by DentonGentry** [comment]
I installed the 1.10.2 release on the Win7-32 system, it does not block the local LAN either (and it is supposed to). I think we just missed that in 1.10 testing, where optionally blocking the local LAN was not a thing.

**Comment by darshinimashar** [comment]
This is the same behaviour in Windows 7 64bit too , exit node does not block local LAN.

**Comment by DentonGentry** [comment]
This appears to be fixed in 1.20, Windows 7 now enforces the allow local LAN access setting. I don't immediately know what fixed it.

**Comment by DentonGentry** [comment]
Somewhere along the way we must have fixed this. In Tailscale release 1.34 allowing or blocking local LAN access with an exit node is working.
