### ISSUE TITLE
iOS 1.11.x exit node not working

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2454]
Running a 1.11.111 build from 18 Jul 2021 (via XCode) with an exit node in Germany selected, whatismyipaddress.com still shows my California IP address. The exit node does not appear to work.

Reinstalling 1.10.1 from the App Store, the exit node does work and whatismyipaddress.com shows the addresses in Germany.

**Comment by DentonGentry** [comment]
This needs to be retested once a 1.11.x build is available through Testflight. Right now Testflight has 1.9.

**Comment by darshinimashar** [comment]
I have tested this on 1.11.137 build for IOS.  It shows me the correct IP address according to exitnode selection.

**Comment by DentonGentry** [comment]
Great. Original problem was an artifact of the FakeNetworkExtension from XCode builds.
