### ISSUE TITLE
iOS 1.11.x Taildrop not working

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2455]
Running a 1.11.111 build from 18 Jul 2021 (via XCode):

- attempting to share a file using Taildrop results in a "Downloading" dialog that I've never seen before, which never completes.
- attempting to share a file from MacOS to the iOS device fails (screenshot from MacOS attached)

<img width="465" alt="Screen Shot 2021-07-18 at 9 28 03 AM" src="https://user-images.githubusercontent.com/1140756/126074912-7d687200-757c-4e0a-8bf8-a0f90f4f0bad.png">

Reinstalling 1.10.1 from the App Store allows me to send files from the MacOS to iOS. However attempting to send files still brings up a "Downloading" dialog which apparently sits there forever.

**Comment by DentonGentry** [comment]
This needs to be retested once a 1.11.x build is available through Testflight. Right now Testflight has 1.9.

**Comment by darshinimashar** [comment]
Taildrop from macOS to IOS and vice versa works well with 1.11.137 testflight.

**Comment by DentonGentry** [comment]
Great. Original problem was an artifact of the FakeNetworkExtension from XCode builds.
