### ISSUE TITLE
Tailscale doesn't run in the Vast instance sandbox

### ISSUE THREAD

**Issue by xiyiyia** [tailscale/tailscale#2456]
Hi! I rent some instance on vast, and I try to make two machines reach each other.
So I install the tailscale, but there is still an error when I run 'tailscale'. 
I tried so many instances. I don't know what's wrong.

> can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

When I run 'tailscaled',

error:

> logtail started
Program starting: v1.10.2-t50371bb8f-g80dcd5480, Go 1.16.6-ts3297502: []string{"tailscaled"}
LogID: d48503b8b22e8398b3b685f612e19394be1cc99b44acad7e854aeb458b875399
logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.Read /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 3.10.0-1062.el7.x86_64
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: 
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 20ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 14 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 1ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 43 msec
tun module not loaded nor found on disk
wgengine.NewUserspaceEngine(tun "tailscale0") error: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
wgengine.New: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 1ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 84 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 1ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 90 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 3ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 273 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 1ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 217 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 1ms)
logtail: upload: log upload of 334 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10f9f3f11889777f5297ac911d3b213ac6b62c8d8dee8dffe1f18f84d4598c6b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 673 msec

Thanks a lot!

**Comment by DentonGentry** [comment]
There is no /dev/net/tun device, which Tailscale uses. There are two possibilities:
- you need to get a container host from Vast with /dev/net/tun. Searching for "OpenVPN" in the hosting provider's support docs will often turn up how to get this, as OpenVPN also uses /dev/net/tun.
- The userspace networking mode https://tailscale.com/kb/1112/userspace-networking/ can work without /dev/net/tun. In this mode you wouldn't get a tailscale0 network interface, you'd get a SOCKS5 proxy and need to make your applications use the proxy.

Overall it would be a smoother experience to get /dev/net/tun working.

**Comment by xiyiyia** [comment]
> There is no /dev/net/tun device, which Tailscale uses. There are two possibilities:
> 
> * you need to get a container host from Vast with /dev/net/tun. Searching for "OpenVPN" in the hosting provider's support docs will often turn up how to get this, as OpenVPN also uses /dev/net/tun.
> * The userspace networking mode https://tailscale.com/kb/1112/userspace-networking/ can work without /dev/net/tun. In this mode you wouldn't get a tailscale0 network interface, you'd get a SOCKS5 proxy and need to make your applications use the proxy.
> 
> Overall it would be a smoother experience to get /dev/net/tun working.

Thanks a lot, sir! I tried the methods, however, I made a mess again.

The first method, when I install OpenVPN, also met some errors. I will try it again. 

Please give me some suggestions for the second method.
The second method, when I run 

`tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
until tailscale up --authkey=tskey-8fd32be2811537....
do
    sleep 0.1
done`

It reports

> [1] 18142
logtail started
Program starting: v1.10.2-t50371bb8f-g80dcd5480, Go 1.16.6-ts3297502: []string{"tailscaled", "--tun=userspace-networking", "--socks5-server=localhost:1055"}
LogID: 37611d827ada8a2cc032eeb8479b460351020b3eaff3326daef4b421784f159b
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "userspace-networking") ...
dns: using dns.noopManager
link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[172.17.0.2/16]} v4=true v6=false}
magicsock: unable to bind udp4 port 0: listen udp4 :0: setting SO_MARK bypass: operation not permitted
wgengine.NewUserspaceEngine(tun "userspace-networking") error: wgengine: magicsock: initialBind IPv4 failed: failed to bind any ports (tried [0])
wgengine.New: wgengine: magicsock: initialBind IPv4 failed: failed to bind any ports (tried [0])
flushing log.
logger closing down
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 9ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 10 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 4ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 52 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 4ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 58 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 4ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 197 msec
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 5ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 146 msec
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 4ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 478 msec
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 4ms)
logtail: upload: log upload of 747 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/78a954cae6372c04d081ba6916c8e2f7b10e432524a66ce70f024d3aa404316b": dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted
logtail: backoff: 410 msec
[1]+  Exit 1                  tailscaled --tun=userspace-networking --socks5-server=localhost:1055
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory


Does it seem like something is wrong with the port? Maybe it can work well on Vast instance?

**Comment by DentonGentry** [comment]
"The first method, when I install OpenVPN, also met some errors. I will try it again."

I don't mean you need to install OpenVPN, I mean that OpenVPN also uses a /dev/net tun device and searching Vast's knowledgebase for how to run OpenVPN may provide a way to get a container with /dev/net/tun enabled.

----

Regarding the errors with userspace-networking:
`logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 5ms)`

This means the container does not have CAP_NET_ADMIN. We added support for this kind of environment in the upcoming Tailscale 1.12 release, you can install the packages from https://pkgs.tailscale.com/unstable/ to geat an early version which should work.

**Comment by bradfitz** [comment]
It appears that the Vast environment is way too restrictive for Tailscale.  Even in userspace mode, it's reporting:

> wgengine.New: wgengine: magicsock: initialBind IPv4 failed: failed to bind any ports (tried [0])

It appears that Vast only allows outbound connections and not listening on anything.

**Comment by xiyiyia** [comment]
> "The first method, when I install OpenVPN, also met some errors. I will try it again."
> 
> I don't mean you need to install OpenVPN, I mean that OpenVPN also uses a /dev/net tun device and searching Vast's knowledgebase for how to run OpenVPN may provide a way to get a container with /dev/net/tun enabled.
> 
> Regarding the errors with userspace-networking:
> `logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_MARK bypass: operation not permitted (in 5ms)`
> 
> This means the container does not have CAP_NET_ADMIN. We added support for this kind of environment in the upcoming Tailscale 1.12 release, you can install the packages from https://pkgs.tailscale.com/unstable/ to get an early version which should work.

Thank you! I try to install that package on my instance, it works! 
But I'm still confused that how to make machines reach each other. Hope you can give me some suggestions again!
After I complete the configuration, I try to use the command 'ping' to make a test.
First I run `sudo tailscale ping 100.83.231.65`, it looks like it is working.

> ipnserver: conn9: connection from userid 0; root has access
[RATELIMIT] format("ping(%v): sending %v ping to %v %v ...") (4 dropped)
ping(100.83.231.65): sending disco ping to [SeNhf] plab-pc1 ...
magicsock: adding connection to derp-7 for [SeNhf]
magicsock: 2 active derp conns: derp-4=cr49m0s,wr49m0s derp-7=cr0s,wr0s
derphttp.Client.Send: connecting to derp-7 (tok)
logtail: dialed "log.tailscale.io:443" in 251ms
magicsock: derp-7 connected; connGen=1
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 824ms
ping(100.83.231.65): sending disco ping to [SeNhf] plab-pc1 ...
magicsock: want call-me-maybe but endpoints stale; restunning
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 273ms
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
ping(100.83.231.65): sending disco ping to [SeNhf] plab-pc1 ...
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 273ms
ping(100.83.231.65): sending disco ping to [SeNhf] plab-pc1 ...
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 275ms
ping(100.83.231.65): sending disco ping to [SeNhf] plab-pc1 ...
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 273ms
ping(100.83.231.65): sending disco ping to [SeNhf] plab-pc1 ...
[RATELIMIT] format("ping(%v): sending %v ping to %v %v ...")
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 270ms
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 272ms
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 273ms
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 276ms
pong from plab-pc1 (100.83.231.65) via DERP(tok) in 291ms
direct connection not established

However, when I use bash to run `ping 100.83.231.65`, it reports:

> magicsock: want call-me-maybe but endpoints stale; restunning
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
magicsock: want call-me-maybe but endpoints stale; restunning
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
magicsock: want call-me-maybe but endpoints stale; restunning
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
magicsock: want call-me-maybe but endpoints stale; restunning
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
magicsock: closing connection to derp-7 (idle), age 3m15s
magicsock: 1 active derp conns: derp-4=cr39m0s,wr39m0s
PING 100.83.231.65 (100.83.231.65) 56(84) bytes of data.
--- 100.83.231.65 ping statistics ---
62 packets transmitted, 0 received, 100% packet loss, time 62455ms

Does it make a connection? Is it because of physical reasons that there is no packet received?
By the way, I find that **Ephemeral Machines** have no IP on the Tailscale website. 
Ah, in my code, I think I have to get the IP and port of the two machines to make them organize as a cluster.
I'm sorry for these so many problems. Thanks for your help!

**Comment by DentonGentry** [comment]
The VM you are using does not have a /dev/net/tun device. That means we can't create a tailscale0 interface. You won't see this on your VM:
```
$ ip addr show tailscale0
798: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 100.99.98.97/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:1234:1234:1234:1234/128 scope global
       valid_lft forever preferred_lft forever
```

We do have a way to make Tailscale work on VMs like this, but it is more limited:
https://tailscale.com/kb/1112/userspace-networking/ using `tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &`

This means Tailscale is functioning as a SOCKS5 proxy server. Common CLI utilities like ping don't work, because there is no tailscale0 network interface, and your application code will need to use a SOCKS5 proxy to connect to whatever you are trying to reach over Tailscale.


> By the way, I find that Ephemeral Machines have no IP on the Tailscale website.

Nodes authorized using an Ephemeral key are only issued an IPv6 address. There is a limited pool of IPv4 addresses available, and some of the use-cases for Ephemeral keys create nodes at a very high rate.

If you need IPv4 connectivity, please use a Reusable or One-time authkey.

**Comment by xiyiyia** [comment]
Thanks a lot! I ran `export ALL_PROXY=socks5://localhost:1055/`  with two machines. 
I tested whether the machine could reach another one by ssh, it didn't work, but I thought this error is not made by tailscale.
I have to set the public key on Vast, however, I still can't connect with them, I have no idea about that. 

These reports were made when I tried so many ports, like services in tailscale website: tailscale, ssh? 
I didn't know whether it was right, so I also tried other ports, like 1056 and so on.
In fact, I'm not sure the error is in my code or somewhere else. 


> Received error: PollNetMap: EOF
control: mapRoutine: backoff: 24 msec
Received error: PollNetMap: EOF
control: mapRoutine: backoff: 83 msec
Received error: PollNetMap: EOF
control: mapRoutine: backoff: 93 msec
magicsock: home is now derp-4 (fra)
magicsock: adding connection to derp-4 for home-keep-alive
magicsock: 1 active derp conns: derp-4=cr0s,wr0s
control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false udp=true derp=#4 portmap= link=""}
magicsock: endpoints changed: 188.126.62.18:44967 (stun), 172.17.0.5:44967 (local)
derphttp.Client.Connect: connecting to derp-4 (fra)
control: client.newEndpoints(0, [188.126.62.18:44967 172.17.0.5:44967])
Switching ipn state Starting -> Running (WantRunning=true, nm=true)
socks5: client connection failed: dial tcp [2a03:b0c0:3:e0::36e:9001]:443: connect: cannot assign requested address
magicsock: derp-4 connected; connGen=1
health("overall"): ok
control: HostInfo: {"IPNVersion":"1.11.125-tb6d70203d-gc25743567","BackendLogID":"42e3511563b2750e3dc26223bbb5e9c47559fb4ce5f80bfea6fd35e185d0700c","OS":"linux","OSVersion":"Ubuntu 18.04.5 LTS (Bionic Beaver); kernel=5.8.0-36-generic; container","Hostname":"180d2e7fb8ef","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd"},{"Proto":"tcp","Port":56790,"Description":"python"},{"Proto":"tcp","Port":65435,"Description":"tailscaled"},{"Proto":"peerapi4","Port":65435},{"Proto":"peerapi6","Port":65435}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":4,"DERPLatency":{"1-v4":0.114703087,"10-v4":0.180353544,"11-v4":0.239410867,"2-v4":0.177007415,"3-v4":0.191391993,"4-v4":0.049120149,"5-v4":0.306324821,"6-v4":0.1737327,"7-v4":0.265871918,"8-v4":0.062794035,"9-v4":0.146837588}}}
wgengine: idle peer d:9cb837c12cd08505 now active, reconfiguring wireguard
wgengine: Reconfig: configuring userspace wireguard config (with 1/4 peers)
magicsock: ParseEndpoint: key=[SeNhf]: disco=d:9cb837c12cd08505 ipps=
magicsock: DERP packet received from idle peer [SeNhf]; created=true
magicsock: adding connection to derp-7 for [SeNhf]
magicsock: 2 active derp conns: derp-4=cr19s,wr19s derp-7=cr0s,wr0s
derphttp.Client.Recv: connecting to derp-7 (tok)
socks5: client connection failed: dial tcp [2401:c080:1000:467f:5400:2ff:feee:22aa]:443: connect: cannot assign requested address
magicsock: disco: node [SeNhf] d:9cb837c12cd08505 now using 163.143.95.247:41641
magicsock: derp-7 connected; connGen=1
Accept: TCP{100.83.231.65:37292 > 100.80.95.72:65435} 60 tcp ok
Accept: TCP{100.83.231.65:37292 > 100.80.95.72:65435} 52 tcp non-syn
Accept: TCP{100.83.231.65:37292 > 100.80.95.72:65435} 53 tcp non-syn
Accept: TCP{100.83.231.65:57720 > 100.80.95.72:1055} 60 tcp ok
Accept: TCP{100.83.231.65:57720 > 100.80.95.72:1055} 52 tcp non-syn
Accept: TCP{100.83.231.65:57720 > 100.80.95.72:1055} 53 tcp non-syn
socks5: client connection failed: incompatible SOCKS version
proxy connection closed with error: read tcp 127.0.0.1:55196->127.0.0.1:1055: read: connection reset by peer
magicsock: closing connection to derp-7 (idle), age 1m0s
magicsock: 1 active derp conns: derp-4=cr1m0s,wr1m0s

> control: HostInfo: {"IPNVersion":"1.11.125-tb6d70203d-gc25743567","BackendLogID":"42e3511563b2750e3dc26223bbb5e9c47559fb4ce5f80bfea6fd35e185d0700c","OS":"linux","OSVersion":"Ubuntu 18.04.5 LTS (Bionic Beaver); kernel=5.8.0-36-generic; container","Hostname":"180d2e7fb8ef","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd"},{"Proto":"tcp","Port":65435,"Description":"tailscaled"},{"Proto":"peerapi4","Port":65435},{"Proto":"peerapi6","Port":65435}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":4,"DERPLatency":{"1-v4":0.114703087,"10-v4":0.180353544,"11-v4":0.239410867,"2-v4":0.177007415,"3-v4":0.191391993,"4-v4":0.049120149,"5-v4":0.306324821,"6-v4":0.1737327,"7-v4":0.265871918,"8-v4":0.062794035,"9-v4":0.146837588}}}
magicsock: closing connection to derp-7 (idle), age 1m45s
magicsock: 1 active derp conns: derp-4=cr15m0s,wr15m0s
magicsock: adding connection to derp-7 for [SeNhf]
magicsock: 2 active derp conns: derp-4=cr20m0s,wr20m0s derp-7=cr0s,wr0s
derphttp.Client.Recv: connecting to derp-7 (tok)
socks5: client connection failed: dial tcp [2401:c080:1000:467f:5400:2ff:feee:22aa]:443: connect: cannot assign requested address
Accept: TCP{100.83.231.65:44778 > 100.80.95.72:22} 60 tcp ok
logtail: dialed "log.tailscale.io:443" in 245ms
Accept: TCP{100.83.231.65:44778 > 100.80.95.72:22} 52 tcp non-syn
Accept: TCP{100.83.231.65:44778 > 100.80.95.72:22} 93 tcp non-syn
magicsock: derp-7 connected; connGen=1
Accept: TCP{100.83.231.65:44796 > 100.80.95.72:22} 60 tcp ok
Accept: TCP{100.83.231.65:44796 > 100.80.95.72:22} 52 tcp non-syn
magicsock: closing connection to derp-7 (idle), age 1m0s
magicsock: 1 active derp conns: derp-4=cr21m0s,wr21m0s
magicsock: want call-me-maybe but endpoints stale; restunning
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
magicsock: adding connection to derp-7 for [SeNhf]
magicsock: 2 active derp conns: derp-4=cr21m0s,wr21m0s derp-7=cr0s,wr0s
derphttp.Client.Recv: connecting to derp-7 (tok)
socks5: client connection failed: dial tcp [2401:c080:1000:467f:5400:2ff:feee:22aa]:443: connect: cannot assign requested address
magicsock: derp-7 connected; connGen=1
Accept: TCP{100.83.231.65:44828 > 100.80.95.72:22} 60 tcp ok
Accept: TCP{100.83.231.65:44828 > 100.80.95.72:22} 52 tcp non-syn
Accept: TCP{100.83.231.65:44828 > 100.80.95.72:22} 93 tcp non-syn
Accept: TCP{100.83.231.65:44840 > 100.80.95.72:22} 60 tcp ok
Accept: TCP{100.83.231.65:44840 > 100.80.95.72:22} 52 tcp non-syn
magicsock: want call-me-maybe but endpoints stale; restunning
Accept: TCP{100.83.231.65:44914 > 100.80.95.72:22} 60 tcp ok
magicsock: STUN done; sending call-me-maybe to d:9cb837c12cd08505 [SeNhf]
Accept: TCP{100.83.231.65:44914 > 100.80.95.72:22} 52 tcp non-syn
Accept: TCP{100.83.231.65:44914 > 100.80.95.72:22} 93 tcp non-syn

Thanks for your help.

**Comment by DentonGentry** [comment]
ssh, ping, and other shell utilities are not going to work, because the container on Vast does not have /dev/net/tun.

Setting ALL_PROXY=socks5://localhost:1055/ means your applications need to be written to use a proxy. You clearly are looking for shell commands to work. Setting ALL_PROXY will not make shell commands like ssh work.

I would advise finding a different hosting provider, and checking for whether they have TUN support before signing up.

**Comment by xiyiyia** [comment]
> ssh, ping, and other shell utilities are not going to work, because the container on Vast does not have /dev/net/tun.
> 
> Setting ALL_PROXY=socks5://localhost:1055/ means your applications need to be written to use a proxy. You clearly are looking for shell commands to work. Setting ALL_PROXY will not make shell commands like ssh work.
> 
> I would advise finding a different hosting provider, and checking for whether they have TUN support before signing up.

I'll keep trying.
Thanks, sincerely.
