### ISSUE TITLE
dns: skipping bad resolver: [unexpected] non-IP resolver "0.0.0.0/0"

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2459]
Seen in user's logs, macOS 1.10.1-t6b6016130-g49e1dcc20 ....

> skipping bad resolver: [unexpected] non-IP resolver "0.0.0.0/0"

Which comes from `ipn/ipnlocal/local.go`'s:

```go
        if uc.CorpDNS {
                addDefault := func(resolvers []tailcfg.DNSResolver) {
                        for _, resolver := range resolvers {
                                res, err := parseResolver(resolver)
                                if err != nil {
                                        b.logf("skipping bad resolver: %v", err.Error())
                                        continue
                                }
                                dcfg.DefaultResolvers = append(dcfg.DefaultResolvers, res)
                        }
                }

// ....

func parseResolver(cfg tailcfg.DNSResolver) (netaddr.IPPort, error) {
        ip, err := netaddr.ParseIP(cfg.Addr)
        if err != nil {
                return netaddr.IPPort{}, fmt.Errorf("[unexpected] non-IP resolver %q", cfg.Addr)
        }
        return netaddr.IPPortFrom(ip, 53), nil
}
```

How did the admin panel let such a value flow down to the client?

/cc @danderson 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3e32p)

**Comment by bradfitz** [comment]
Ping @danderson for ideas.

**Comment by DentonGentry** [comment]
The coordination server currently has a `skipResolverOnRead()` function to filter out inoperable DNS configurations which might have gotten stored in the database. We could add 0.0.0.0 to it.

**Comment by DentonGentry** [comment]
Checking current DB: there are no tailnets with a saved 0.0.0.0 DNS server.
We should add a check to `skipResolverOnRead()` to ensure it stays that way, and then close this bug.
