### ISSUE TITLE
wgengine: suspicious use of deephash on wgcfg.IPPortSet

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#2463]
In userspace.go we [perform a deep hash of wgcfg.Config](https://github.com/tailscale/tailscale/blob/36fe8addc39281423576c9011e81ce714b6f8e44/wgengine/userspace.go#L770).

One of the types reachable from [`wgcfg.Config`](https://pkg.go.dev/tailscale.com/wgengine/wgcfg#Config) is [`wgcfg`](https://pkg.go.dev/tailscale.com/wgengine/wgcfg).[`Config`](https://pkg.go.dev/tailscale.com/wgengine/wgcfg#Config).[`Peers`](https://pkg.go.dev/tailscale.com/wgengine/wgcfg#Config.Peers).[`Endpoints`](https://pkg.go.dev/tailscale.com/wgengine/wgcfg#Peer.Endpoints).[`IPPorts`](https://pkg.go.dev/tailscale.com/wgengine/wgcfg#Endpoints.IPPorts) which is an [`IPPortSet` type](https://pkg.go.dev/tailscale.com/wgengine/wgcfg#IPPortSet).

The `IPPortSet` type has no exported fields, and the name "set" and the presence of an `EqualUnordered` method seem to imply that it should be conceptually treated as a set, rather than an ordered list. Since the `deephash` package automatically introspects unexported fields, it will hash the `wgcfg.IPPortSet` by traversing the unexported [`ipp` field of `[]netaddr.IPPort`](https://github.com/tailscale/tailscale/blob/36fe8addc39281423576c9011e81ce714b6f8e44/wgengine/wgcfg/config.go#L61) and hash the slice. Such a hashing will be order dependent, which seems to go contrary to the purpose of the type.

Is such behavior expected?

\cc @josharian @bradfitz

**Comment by josharian** [comment]
Yeah, we should fix that, by implementing AppendTo. The good news is that the failure mode here is false positives (spurious reconfig due to reordering), which isn't terrible, unlike false negatives.

**Comment by bradfitz** [comment]
I think it's fine.

Both because it happens to always be sorted IIRC, but also that field is basically never used anymore:

```
	// IPPorts is a set of possible ip+ports the remote node can be reached at.
	// This is used only for legacy connections to pre-disco (pre-0.100) peers.
	IPPorts IPPortSet `json:"ipp,omitempty"`
```

**Comment by bradfitz** [comment]
Definitely worth cleaning up, though.

Earlier we were talking about making deephash fail if it encounters an unsupported type: https://github.com/tailscale/tailscale/issues/2348

**Comment by dsnet** [comment]
Closing as `IPPortSet` no longer exists.
