### ISSUE TITLE
"Logout" action should cancel --request-tags

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2485]
Reported by a customer:

Steps:
- `tailscale up --request-tags=tag:x` (and login)
- `tailscale logout`
- `tailscale up` (and login as a different user)

Expected:
--request-tags setting is dropped since it's irrelevant to the new account

Actual:
--request-tags has been retained since we keep all the options from the previous `tailscale up` run.

As part of a bigger redesign, we actually should forget everything related to auth (currently just --authkey and --request-tags, I think) after a successful authrequest, and should not transition our auth status unless someone explicitly asks for it in a particular `tailscale up` instance. See also #2300 which has scary behaviour. But that's probably hard to do right now, so a quicker workaround is to forget the --advertise-tags setting on the client.

**Comment by DentonGentry** [comment]
This got fixed during the tags-v2 effort. If I follow the same steps:
```
1. tailscale up --advertise-tags=tag:example
1. tailscale logout
1. tailscale up
```

On the second tailnet the node did not try to advertise `tag:example`
