### ISSUE TITLE
Kernel-mode vs user-mode of WireGuard?

### ISSUE THREAD

**Issue by schopenhauer** [tailscale/tailscale#2487]
Is there a possibility to use kernel-mode WireGuard, if installed on the system, and fallback to user-mode only when necessary. I assume this would come with performance benefits, compared to using user-mode only.

**Comment by DentonGentry** [comment]
Kernel mode has been considered, but comes with it the support burden of more platform differences. We're working to finish [io_uring support](https://github.com/tailscale/tailscale/issues/2303), to get the benefit of avoiding data copies and reduced system call overhead but yet still be in userspace.
