### ISSUE TITLE
DNS Requests Cause Unstable Connections

### ISSUE THREAD

**Issue by gregg098** [tailscale/tailscale#2488]
I setup some PiHole servers on two of my VPSs and connected them to Tailscale. Everything works just fine normally, but I found that if I open say 50 tabs at once from a bookmark folder on my computer with all DNS requests going to the PiHoles, the entire Tailscale connection with that machine essentially dies. This doesn't happen every time, but I have repeated at least a few times.

1) Open lots of tabs
2) Try to refresh PiHole web GUI over Tailscale to ensure requests are coming in but it just sits there trying to reload
3) Try to connect via SSH over Tailscale fails
4) Direct SSH connection works fine. System resources are not high and nothing suggesting its overloaded.

If I restart the tailscaled service on the remote machine and also on my Windows machine, the connection usually comes back. It takes a few minutes sometimes.
This morning, I reproduced this on the primary PiHole. Most requests failed over to the secondary PiHole OK. Did the same thing again and the secondary PiHole connection went down the same way. These both run Ubuntu 20.04

Here are some bug reports:

Windows 10:
BUG-0eb27742e9ee83b5d832bcff4bfe17197e45ae1c2f1bd99d652c105a1ea8c75c-20210722145217Z-31fcb91fdb0cf319

VPS1 - Primary DNS on Tailscale network. This bug report is after I was able to get the connection back.
BUG-8c58770b036650965694d2dc65950a44914c063d11cee438a1384b26b4584fc1-20210722145210Z-5494d3b774410353

VPS2 - Secondary DNS. Gathered after connection was suffering through a direct SSH connection.
BUG-b49d94bad3c8b6fbb9359d7e319cc4ae26e4e8a7b4a093acda14771f92ee387f-20210722145155Z-9fd6a38a651e0536

EDIT: Just to clarify, I do not believe that PiHole is to blame here (but correct me if you find other information). The VPS is still running and serving other services just fine. Only the Tailscale connection itself is affected.

**Comment by gregg098** [comment]
After experimenting a little more, I'm convinced its the Windows service causing the issues, but can't prove it. When my connection fails, a restart of the Windows Tailscale service seems to fix it most of the time, even after I've restarted the VPS tailscaled services.  Both Windows laptops I've experienced this on are running 1.10.2.

**Comment by DentonGentry** [comment]
MagicDNS creates a number of goroutines to forward DNS queries, an initial guess is that the sheer number of queries makes it run out of goroutines.

**Comment by gregg098** [comment]
I opened up 41641/udp on the VPS instances and this seemed to have improved connectivity. The VPS has a public IP and my home setup is the normal behind a router setup with no ports open for Tailscale. No double NAT or anything crazy.  I would think its a pretty typical setup and not hard to connect to.

**Comment by DentonGentry** [comment]
This is almost certainly a symptom of a DNS resource leak which was fixed in Tailscale 1.28.
