### ISSUE TITLE
Support FreeBSD as an exit node

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2498]
FreeBSD systems, including pfSense and opnSense, currently can not function as [exit nodes](https://tailscale.com/kb/1103/exit-nodes/). This issue tracks the effort to implement that support. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3h041)

**Comment by bradfitz** [comment]
We could at least do hybrid netstack mode on FreeBSD trivially like we do on Windows, synology, etc.

Wouldn't be super efficient, but would work for lite usage.

**Comment by DentonGentry** [comment]
Verified that enabling hybrid netstack mode allows my OPNsense (FreeBSD 12.1) node to function as an exit node for both IPv4 and IPv6.

**Comment by bradfitz** [comment]
ship it :)

**Comment by DentonGentry** [comment]
Report from the user who initially requested this, after compiling tailscaled from head for OPNsense:

_After a reboot, I'm able to use the opnSense router as an exit node!_

_I'll put some traffic through it and see if we run into any issues. Currently it seems I'm capped at around 130Mbps (tested through speedtest.net and fast.com. Home bandwidth is 600mbps but realistically get about 300, datacenter is 10gig) which I'm happy with for a full tunnel VPN connection, but I feel like it should theoretically be higher._

_I don't see any spikes in CPU or RAM usage, so we're probably good. I'll try to do some iperf tests later this week._

**Comment by 0xSteeW** [comment]
Hello, I'm trying to get Tailscale working as an exit node on my FreeBSD Vps, however, the log points out "some manual modifications" are needed for getting it to work. Is there any place where I can find how to do that?

**Comment by 0xSteeW** [comment]
Nevermind! It just works after creating a NAT from tailscale IPs to the external interface with pf.

**Comment by lipidity** [comment]
@oezh using normal PF config. This kind of thing worked for me on OpenBSD: https://www.openbsd.org/faq/pf/nat.html

**Comment by mats852** [comment]
> @oezh using normal PF config. This kind of thing worked for me on OpenBSD: https://www.openbsd.org/faq/pf/nat.html

Could you provide an example? That would be really appreciated! Thanks in advance.

**Comment by FiloSottile** [comment]
For posterity, this is the `/etc/pf.conf` that works for me to enable exit nodes on OpenBSD 7.0.

```
set skip on lo0

# Block spoofed packets not actually coming from Tailscale,
# and packets from other interfaces to Tailscale.
block in on ! tun0 from 100.64.0.0/10 to any
block in on ! tun0 from any to 100.64.0.0/10

# Enable NAT for Tailscale exit node.
pass out on egress inet from 100.64.0.0/10 to any nat-to (egress)
```

**Comment by mats852** [comment]
> For posterity, this is the `/etc/pf.conf` that works for me to enable exit nodes on OpenBSD 7.0.
> 
> ```
> set skip on lo0
> 
> # Block spoofed packets not actually coming from Tailscale,
> # and packets from other interfaces to Tailscale.
> block in on ! tun0 from 100.64.0.0/10 to any
> block in on ! tun0 from any to 100.64.0.0/10
> 
> # Enable NAT for Tailscale exit node.
> pass out on egress inet from 100.64.0.0/10 to any nat-to (egress)
> ```

Thanks @FiloSottile, your solution works perfectly!

One thing I initially forgot was to enable IP forwarding, as a friendly reminder for future readers.

It's mentionned in the first step of this guide: https://tailscale.com/kb/1103/exit-nodes/

For reference:
https://www.openbsd.org/faq/pf/nat.html#ipfwd
