### ISSUE TITLE
No easy way to delete migrated search domains in split DNS panel

### ISSUE THREAD

**Issue by pbnjay** [tailscale/tailscale#2501]
Running Amazon Linux 2, I just ran a simple upgrade to 1.10.2 and some of my web services stopped working.
After a short investigation I found that `/etc/resolv.conf` had been overwritten by tailscale, but thankfully I could replace with `/etc/resolv.pre-tailscale-backup.conf` - but I am concerned that this might happen again in future upgrades?

I did not expect tailscale to even touch the DNS config on my server since I have magic DNS disabled for my account.

```
tailscale version
1.10.2
  tailscale commit: 50371bb8fa07fd302bc2429907de6f8197f3fedd
  other commit: 80dcd5480a46fe819462fdbc4564379e18bc6566
  go version: go1.16.6-ts3297502
```

**Comment by DentonGentry** [comment]
Can you send either the email address used with Tailscale or the IP address of this system to support@tailscale.com, so we can look up the configuration of the Tailnet?

**Comment by pbnjay** [comment]
Sent. thanks!

**Comment by bradfitz** [comment]
MagicDNS off alone doesn't mean to not touch DNS settings. Tailnet admins can say "Use 1.2.3.4 for DNS" and tailscaled sets that DNS on machines, but doesn't use 100.100.100.100 with MagicDNS entries.

To ask tailscaled to not manage /etc/resolv.conf etc at all, use `tailscale up --accept-dns=false ....`

To confirm that's on you for you, look at `tailscale debug -prefs` and see if your `"CorpDNS"` is `true` currently.

**Comment by pbnjay** [comment]
Hmm yeah debug says that CorpDNS is true, but I guess the concern here is that I never turned that on, and this upgrade left me with no functional DNS whatsoever.

**Comment by DentonGentry** [comment]
On that system:
- it thinks that none of systemd-resolved nor resolveconf or any other DNS config system is in place, so it should rewrite /etc/resolv.conf
- it think it has a search domain to configure, so it writes out an /etc/resolv.conf containing the search domain. No nameservers, since none were configured, but it writes the search domain.

However I don't understand why it is trying to write a search domain at all. The DNS config for the domain appears to be empty.

When you removed the /etc/resolv.conf file: did it contain a search domain and did you recognize it? Was it ever conceivably set in the Tailscale DNS config?

**Comment by pbnjay** [comment]
I see something in the web admin panel about split DNS for my domain, but I don't see any way to delete it if that's what causing it. The domain listed for split DNS was listed as the search domain in the tailscale-generated resolve.conf (but yes, no nameserver).

**Comment by pbnjay** [comment]
I found this FAQ here, this must be part of what's going on:
https://tailscale.com/kb/1054/dns/
> **How can I define a search domain without a nameserver?**
> Previous versions of the DNS settings page allowed defining search domains separately from nameservers. However, due to cross-platform compatibility reasons, this is no longer possible. To define a search domain, you’ll need to add at least one nameserver along with it.

**Comment by DentonGentry** [comment]
Does the menu from clicking on the three dots to the right of the Split DNS domain have a Delete selection?

<img width="479" alt="Screen Shot 2021-07-22 at 10 04 02 PM" src="https://user-images.githubusercontent.com/1140756/126739438-db33b5d2-6af7-4bbe-8dac-f65ec07be3e7.png">

**Comment by pbnjay** [comment]
There are no dots to click on...
![Screen Shot 2021-07-23 at 1 14 22 AM](https://user-images.githubusercontent.com/161552/126740029-c0ed274b-521f-464e-ae2d-4cc4b45f9df6.png)

But I had success! I added a new nameserver w/ the same domain as a "split dns" and then was able to delete that.

**Comment by DentonGentry** [comment]
From investigation on https://github.com/tailscale/corp/issues/1818 (which you won't be able to see, sorry) I think there are 72 tailnets in this state.

**Comment by DentonGentry** [comment]
Fixed by https://tailscale.com/kb/1054/dns/#search-domains
