### ISSUE TITLE
FR: iOS/MacOS Shortcut support

### ISSUE THREAD

**Issue by gilbertbw** [tailscale/tailscale#2504]
On apple platforms (macOS/iOS/iPadOS) I would like to be able to turn my Tailscale on and off using an action.

This would be especially useful with iOS 15, as you can create a 'Focus' for work, and run your shortcut when it starts/stops.

This would also provide a workaround for #1534, as discussed in that issue.

**Comment by stevetrease** [comment]
This would be exceptionally useful to script actions

Connect to Tailscale; use Secure Shellfish app to copy files; disconnect from Tailscale.

Alternatively support for iOS's VPN-on-demand feature - specify a domain name that should be accessed over Tailscale and when the device requests that domain, connect to Tailscale....

**Comment by wscott** [comment]
Agreed. My use case is that I don't normally run with tailscale enabled, but a few places I go have good wifi, but they filter access to block things I use. I want to enable tailscale with an exit node whenever that wifi SSID is active and disconnect tailscale when I leave.
Shortcuts can do the automation already, I just need the ability to turn tailscale on and off.

**Comment by briandela** [comment]
Would love to be able to use iOS shortcuts to quickly select the Exit Node too.

**Comment by dvcrn** [comment]
Copying the usecases over what I wrote in #6106 

### What are you trying to do?

- Connect Tailscale when iPhone is connected to power
- Disconnect tailscale when battery is low (it's a battery hog)
- The OS sometimes disconnects tailscale, so I want to automate reconnecting it if that happens before I run stuff that needs my tailnet
- Use a Shortcut to connect to the tailnet when opening an app that requires it

### How should we solve this?

Provide Siri Shortcut integration to: 

- Connect tailscale
- Disconnect tailscale
- Get current connection status

### What is the impact of not solving this?

- Tailscale randomly getting disconnected on iOS (reliability)
- Less control over when the network is up

**Comment by DaLuggi** [comment]
Pleeeease do this, it would make things so much simpler for all Apple users! :)

**Comment by susheel** [comment]
@DentonGentry - We meet again!! It's been a while :). I would dearly love to add my support to this feature to help with automating connections to my homelab, work and personal iOS automations

**Comment by dvcrn** [comment]
Been using the Tailscale iOS app more these days and the connections are very unpredictable/unreliable. Sometimes it disconnects, sometimes it doesn't. The battery drain is also pretty big, so can't leave it on all the time (not that it would stay enabled)

Even without Shortcut support, some setting to make sure it stays connected when connected for a power adapter for example would already be sweet

**Comment by mihaip** [comment]
Shortcuts support is now available in the latest iOS unstable build on TestFlight (version 1.35.126, build 102): https://testflight.apple.com/join/tLcYLZJV 

There are actions for connecting, disconnecting and using an exit node. It should be possible to pair this with automations like leaving a location or connecting to a WiFi network:

![IMG_5065](https://user-images.githubusercontent.com/513813/211885822-d53d5575-4aad-4c74-9724-e26b63a14576.png)

Let us know (by commenting on this bug) how it's working out for you -- we hope to include it in the next stable build.

(macOS support is also being worked but, but is being held up while we fight with an App Store Connect build issue -- I will update this bug when it's available)

**Comment by pascaliske** [comment]
Just tested it with iOS back tap feature - works great! Thanks!

**Comment by DaLuggi** [comment]
It works great! Awesome work, thank you!

**Comment by dvcrn** [comment]
I tried a few simple automations like: connect when power connects and connect at time of day, and so far it's working great! 

Super stoked to see this feature make it into the app! ❤️ This should hopefully help with battery drain

**Comment by dvcrn** [comment]
I played with it a bit and left my automations running in the background

Here's a little quality of life improvement that would be nice to have in addition: have a way for shortcuts to pull the status of tailscale, whether currently connected or not

**Comment by DaLuggi** [comment]
> I played with it a bit and left my automations running in the background
> 
> Here's a little quality of life improvement that would be nice to have in addition: have a way for shortcuts to pull the status of tailscale, whether currently connected or not, to be used in conditional statements

Yes @dvcrn, that would be amazing.

I used a workaround with a shortcut named "Memory by Wonky Logic", that uses the "Reminders" app for storing sort of global variables. Each time I connect to Tailscale using a shortcut, I set a variable called "tailscale_status" to either on or off.
Of course, it is just a workaround. 
(As soon as I switch the slider in the app itself, the variable is set wrong until I use the shortcuts again.)

In my use-case, I use "FE - File Explorer" to access my ressources such as my NAS. When I'm not using my home wifi while opening or closing FE, I get a prompt if I want to connect/disconnect to Tailscale. 
I don't want to do this automatically without a prompt as there might be situations in wich I want to stay connected, for example if I play a movie with picture-in-picture. 

Also, firing a "disconnect" each time I close the app is also not an option, because I don't need Tailscale for every connection I have in FE, (therefore these prompts are a great solution again). Otherwise the disconnect prompt would fire ignoring the fact that I didn't even connect in the first place, so checking the status would come in handy here.

**Comment by mihaip** [comment]
This is now available in Mac unstable builds as well (installation instructions at https://tailscale.com/kb/1083/install-unstable/). In addition to the iOS actions (connecting, disconnecting and using an exit node) there is also an action for [switching between accounts](https://tailscale.com/kb/1225/fast-user-switching/).

@dvcrn and @lukaslindnermusic: That's a good point about being able to get the current state, I will look into adding support for that.

**Comment by lukaslindnermusic** [comment]
@mihaip it works great on the Mac as well!
Thank you again for adding that feature! 
I hope that the feature makes it to the next stable builds :)

**Comment by mihaip** [comment]
> @dvcrn and @lukaslindnermusic: That's a good point about being able to get the current state, I will look into adding support for that.

This is now available in the iOS and macOS TestFlight builds that just went out (1.35.158). There is now a "Get Status" action for Tailscale that lets you query the connected state, account and exit node status. 

You can use it for implementing "toggle" shortcuts, and I'm guessing other things too.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/513813/213015982-67bed3c2-dd9a-4a90-b5dc-8c8b89a5d6a9.png">

**Comment by lukaslindnermusic** [comment]
Just tested it, it works great!
Thank you, @mihaip !

**Comment by dvcrn** [comment]
This is awesome, thanks for adding this!

Btw you mentioned testflight for mac, do you still have slots free for that one?

**Comment by DentonGentry** [comment]
Yes, there are slots open. The macOS TestFlight is here: https://testflight.apple.com/join/7ExrFq00

**Comment by mihaip** [comment]
This has now been picked up in the 1.36 release, see [the blog post](https://tailscale.com/blog/ios-macos-shortcuts/) and [documentation](https://tailscale.com/kb/1233/mac-ios-shortcuts/) for details.

If there are additional shortcuts actions or issues with the implementation (#7063 is one we're aware of), please file them as separate issues.

**Comment by highincolorado** [comment]
I have tried setting up automatic connection when leaving my home and automatic disconnect when getting back home on my iPhone. I get an alert on the phones screen that the automation triggered but must manually touch the alert to actually connect or disconnect. Is this the way it’s supposed to be? If so how is this better than manually connecting/disconnecting. What am I missing?

**Comment by highincolorado** [comment]
Well after much tinkering I found a way to get a connection through an automation by using the When CarPlay Connects trigger. It does not force notification and therefore can get me connected. Still no way found to disconnect once I get back home on my trusted wifi.

**Comment by lukaslindnermusic** [comment]
> Well after much tinkering I found a way to get a connection through an automation by using the When CarPlay Connects trigger. It does not force notification and therefore can get me connected. Still no way found to disconnect once I get back home on my trusted wifi.

@highincolorado what I did is setting up a sort of cronjob that runs every 15min.
Unfortunately, there is no easier way to do this within the shortcuts app, so I added an automation every 15min that executes one shortcut called "Cronjob ( I did this so that you can edit it easier later on). All actions (or other shortcuts) that you want to execute every 15min you can add within this Cronjob shortcut.
I needed this for two other shortcuts projects, so I had this set up already. All i did was adding a WIFI check, and if I am on my home wifi network and the tailscale status is connected, I disconnect. 
Luckily, a time-based automation does not give you a notification, so this works brilliantly.

**Comment by highincolorado** [comment]
> > Well after much tinkering I found a way to get a connection through an automation by using the When CarPlay Connects trigger. It does not force notification and therefore can get me connected. Still no way found to disconnect once I get back home on my trusted wifi.
> 
> @highincolorado what I did is setting up a sort of cronjob that runs every 15min. Unfortunately, there is no easier way to do this within the shortcuts app, so I added an automation every 15min that executes one shortcut called "Cronjob ( I did this so that you can edit it easier later on). All actions (or other shortcuts) that you want to execute every 15min you can add within this Cronjob shortcut. I needed this for two other shortcuts projects, so I had this set up already. All i did was adding a WIFI check, and if I am on my home wifi network and the tailscale status is connected, I disconnect. Luckily, a time-based automation does not give you a notification, so this works brilliantly.

More details on how this can be done on an iPhone would be appreciated.

**Comment by lukaslindnermusic** [comment]
> > > Well after much tinkering I found a way to get a connection through an automation by using the When CarPlay Connects trigger. It does not force notification and therefore can get me connected. Still no way found to disconnect once I get back home on my trusted wifi.
> > 
> > 
> > @highincolorado what I did is setting up a sort of cronjob that runs every 15min. Unfortunately, there is no easier way to do this within the shortcuts app, so I added an automation every 15min that executes one shortcut called "Cronjob ( I did this so that you can edit it easier later on). All actions (or other shortcuts) that you want to execute every 15min you can add within this Cronjob shortcut. I needed this for two other shortcuts projects, so I had this set up already. All i did was adding a WIFI check, and if I am on my home wifi network and the tailscale status is connected, I disconnect. Luckily, a time-based automation does not give you a notification, so this works brilliantly.
> 
> More details on how this can be done on an iPhone would be appreciated.

as said, you create a shortcut that checks your current WIFI (there is an action that can do that), and then you can add an automation within the Shortcuts app every 15min, in those automations you add the action to run another shortcut and you select the one you created.

**Comment by highincolorado** [comment]
> > > > Well after much tinkering I found a way to get a connection through an automation by using the When CarPlay Connects trigger. It does not force notification and therefore can get me connected. Still no way found to disconnect once I get back home on my trusted wifi.
> > > 
> > > 
> > > @highincolorado what I did is setting up a sort of cronjob that runs every 15min. Unfortunately, there is no easier way to do this within the shortcuts app, so I added an automation every 15min that executes one shortcut called "Cronjob ( I did this so that you can edit it easier later on). All actions (or other shortcuts) that you want to execute every 15min you can add within this Cronjob shortcut. I needed this for two other shortcuts projects, so I had this set up already. All i did was adding a WIFI check, and if I am on my home wifi network and the tailscale status is connected, I disconnect. Luckily, a time-based automation does not give you a notification, so this works brilliantly.
> > 
> > 
> > More details on how this can be done on an iPhone would be appreciated.
> 
> as said, you create a shortcut that checks your current WIFI (there is an action that can do that), and then you can add an automation within the Shortcuts app every 15min, in those automations you add the action to run another shortcut and you select the one you created.

Well, I don’t see an option or know how to create a repeating 15 minute automation within the shortcut app. If it’s an option I just don’t see it.

**Comment by mar627** [comment]
https://github.com/user-attachments/assets/1516edac-2917-4858-9b0c-e9b41f60895e

Hey @mihaip, feels a little wonky the logic in the video I shared.. Status can be true for connected, but fail to ping.
- Connect to TS
- get status (says it’s running)
- ping device (fails because not running, but really ts is still starting up)

I will add a wait action, to give ts time to g fully start up, but I do want to be able to catch those odd times that it hangs and doesn’t end up connecting, then proceed with other actions instead of a hard fail in shortcuts.

Thank you, I love ts ✨

**Comment by mihaip** [comment]
@mar627 I'm no longer working at Tailscale, so your best bet is to file a new issue describing what you're running into.
