### ISSUE TITLE
Error when running on Teltonika 955

### ISSUE THREAD

**Issue by APhanSpAARC** [tailscale/tailscale#2505]
Hi All,

I am attempting to install Tailscale on a Teltonika 955 router by following this [blog post](https://willangley.org/how-i-set-up-tailscale-on-my-wifi-router/), and making sure to use the correct build for my hardware (MIPS). Unfortunately when i attempt to run `./tailscaled` I receive the following error.

```
root@Teltonika-RUT950:/tmp/tailscale_1.10.2_mips# ./tailscale up
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

Has anyone experienced a similar issue in the past? 
I am using the following build:
-  mips: tailscale_1.10.2_mips.tgz

**Comment by DentonGentry** [comment]
The `tailscale` command doesn't start tailscaled, it just attempts to communicate with tailscaled via a unix socket. The error means that tailscaled is not running so there is no socket open.

We typically use systemd to start tailscaled. The blog post you referenced shows a rc.common script for procd, but If the Teltonika 955 does not use either systemd or procd then you'll need to start tailscaled some other way. When run from systemd we generally start it with the following arguments:
`/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641`

There s nothing special about the path names, please move the socket and state file wherever appropriate. The socket can be in a tmpfs, the state file needs to go in stable storage to persist across reboots.

**Comment by APhanSpAARC** [comment]
Hi @DentonGentry 

Thanks for the support. I'm not sure if i'm following you correctly due to my limited knowledge of Linux. I have run the following command with the following results.

```
root@Teltonika-RUT950:/tmp/tailscale_1.10.2_mips# /tmp/tailscale_1.10.2_mips/tailscaled --state=/var/lib/tailscale/tails
caled.state --socket=/run/tailscale/tailscaled.sock --port 4164
logtail started
Program starting: v1.10.2-t50371bb8f-g80dcd5480, Go 1.16.6-ts3297502: []string{"/tmp/tailscale_1.10.2_mips/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "4164"}
LogID: d5c18b05d31ad546cecfc31de70a622bda95282b7fa33db0f14bcd6f765675a2
logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.Read /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: disabling tunneled IPv6 due to system IPv6 config: disable_ipv6 is set
dns: [rc=unknown ret=dns.directManager]
dns: using dns.directManager
link state: interfaces.State{defaultRoute=eth1 ifs={br-lan:[192.168.1.1/24] eth1:[192.168.0.227/24]} v4=true v6=false}
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
external route: up
logtail: dialed "log.tailscale.io:443" in 303ms
Clearing router settings...
Starting link monitor...
Starting magicsock...
Engine created.
Listening on /run/tailscale/tailscaled.sock
netmap packet filter: (not ready yet)
Start
using backend prefs
created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
got initial portlist info in 0s
magicsock: disco key = d:a29db7380622dc9b
control: HostInfo: {"IPNVersion":"1.10.2-t50371bb8f-g80dcd5480","BackendLogID":"d5c18b05d31ad546cecfc31de70a622bda95282b7fa33db0f14bcd6f765675a2","OS":"linux","OSVersion":"Other; kernel=3.18.44","Hostname":"Teltonika-RUT950","GoArch":"mips","Services":[{"Proto":"tcp","Port":22,"Description":"dropbear"},{"Proto":"tcp","Port":53,"Description":"dnsmasq"},{"Proto":"tcp","Port":80,"Description":"uhttpd"},{"Proto":"tcp","Port":443,"Description":"uhttpd"}]}
Backend: logs: be:d5c18b05d31ad546cecfc31de70a622bda95282b7fa33db0f14bcd6f765675a2 fe:
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:map[] SearchDomains:[] Hosts:map[]}
dns: Resolvercfg: {Routes:map[] Hosts:map[] LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
health("overall"): error: state=NeedsLogin, wantRunning=false
monitor: RTM_NEWROUTE: src=, dst=ff02::16/128, gw=, outif=3, table=255
netmap packet filter: (not ready yet)
monitor: RTM_NEWROUTE: src=, dst=ff02::fb/128, gw=, outif=3, table=255
monitor: RTM_DELROUTE: src=, dst=ff02::1/128, gw=, outif=3, table=255
control: HostInfo: {"IPNVersion":"1.10.2-t50371bb8f-g80dcd5480","BackendLogID":"d5c18b05d31ad546cecfc31de70a622bda95282b7fa33db0f14bcd6f765675a2","OS":"linux","OSVersion":"Other; kernel=3.18.44","Hostname":"Teltonika-RUT950","GoArch":"mips"}
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:new
monitor: RTM_DELROUTE: src=, dst=ff02::16/128, gw=, outif=3, table=255
```

What I was expecting to see was a URL in the terminal guiding me to a login page. This is what happens when I install tail scale on my ubuntu desktop machines. Am I prehaps misunderstanding something?

**Comment by DentonGentry** [comment]
On your Ubuntu machine, tailscaled was set to run automatically at boot by a process called systemd. On Ubuntu you ran "tailscale up" and it communicated with the tailscaled that systemd had run for you.

The Teltonika 955 does not appear to use systemd. Running it yourself in an ssh shell is a way to get started, eventually you'll want to find a way to make it run automatically at boot.

Having "tailscale up" segfault isn't awesome. Are you able to run strace?
```
strace tailscale up
```

and paste the last ~200 lines?

**Comment by APhanSpAARC** [comment]
Thanks @DentonGentry,

With your help I managed to get this working. It seem like when you run `tailscale up` it requires tail scale to run from a copy of the files in `/usr/sbin` directory however the files had failed to copy over due to insufficient flash in the teltonika router. Instead I ran tail scale using the command below form the temp directory containing all the files extracted from the tar.gz using  `./tailscale up`

Installing tail scale on the router allowed me to access the router web interface form its tail scale IP address as described in  [blog post](https://willangley.org/how-i-set-up-tailscale-on-my-wifi-router/). However I was also hoping it would all all devices connected to the router to access/ping devices on my tail scale network without the need to install tail scale on every individual device. Is there an additional configuration needed to achieve this?

**Comment by DentonGentry** [comment]
https://tailscale.com/kb/1019/subnets/

You'll want to:
1. `tailscale up --advertise-routes=192.168.1.0/24`   (or whatever your LAN subnet is)
1. In https://login.tailscale.com/admin/machines, select "Review route settings" for the Teltonika and approve the routes

Your other Tailscale nodes should receive a 192.168.1.0/24 route and be able to access devices on your LAN by IP address. Note that Linux clients do not accept routes by default, if you have other Linux systems they'll need to be started with `tailscale up --accept-routes`.

We do recommend installing the Tailscale client app wherever possible, to make the encryption be end-to-end and to allow things like Magic DNS to work.

Since the main thing seems to be working, I'm going to close the bug now. Feel free to reopen if something isn't right.

**Comment by APhanSpAARC** [comment]
Hi @DentonGentry,

My understanding is relay node/subnet routing will allow my tail scale devices (outside my network) to access any device in my local network attached to the router, however this is different to having any device behind my routing being able to communicate to other Tailscale clients outside the local network.

The main use case for me installing tailscale on the router was so all devices connected to the router would be able to access tail scale clients outside my local network, otherwise a relay node on any computer on the network would of sufficed.

**Comment by DentonGentry** [comment]
By default, the subnet router NATs remote IP address to its own. For example if the remote Tailscale client is 100.99.98.97, the subnet router will forward those packets onto the LAN with its own source IP address instead like 192.168.1.1.

If you want devices on the LAN to be able to reach remote Tailscale nodes, you can start the subnet router with `tailscale up --snat-subnet-routes=false --advertise-routes=...`

This means that packets from remote Tailscale nodes will appear on the LAN with IP address 100.99.98.97, and nodes on your LAN will be able to initiate connections to 100.99.98.97.
