### ISSUE TITLE
Tailscale without TUN

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2509]
Just tried Tailscale without Tun. It works, and connects, however, IP Forwarding is not working inside a Docker container.

I cannot seem to forward any traffic and ping does not work when it's set as an exit node.

Any idea what logs I can provide?

**Comment by vysecurity** [comment]
```
netstack: forwarder connection to X:443 closed
netstack: forwarding incoming connection to X:443
netstack: forwarding incoming connection to X:443
[RATELIMIT] format("netstack: forwarding incoming connection to %s")
netstack: could not connect to local server at [X]:443: dial tcp [X]:443: connect: network is unreachable
netstack: forwarder connection to X:443 closed
[RATELIMIT] format("acceptUDP: could not create endpoint: %v") (35 dropped)
acceptUDP: could not create endpoint: no route
acceptUDP: could not create endpoint: no route
[RATELIMIT] format("acceptUDP: could not create endpoint: %v")
netstack: could not connect to local server at [X]:443: dial tcp [x]:443: connect: network is unreachable
netstack: forwarder connection to X:443 closed
[RATELIMIT] format("acceptUDP: could not create endpoint: %v") (45 dropped)
acceptUDP: could not create endpoint: no route
acceptUDP: could not create endpoint: no route
[RATELIMIT] format("acceptUDP: could not create endpoint: %v")
[RATELIMIT] format("netstack: forwarding incoming connection to %s") (5 dropped)
netstack: forwarding incoming connection to [X]:443
netstack: could not connect to local server at [X]:443: dial tcp [X]:443: connect: network is unreachable
```

**Comment by vysecurity** [comment]
Seems to be a problem with UDP and DNS?

**Comment by vysecurity** [comment]
Using unstable build works:
```
# tailscaled -version
1.11.150
  tailscale commit: 7b295f3d2163f6327f6cf531b9996903ad9fa025
  other commit: 63439d256128ddaa97c427270459d1a31395584d
  go version: go1.16.6-ts6fa85e8
```

**Comment by vysecurity** [comment]
But, ICMP doesn't forward. UDP works now.

Looks to be an extension of https://github.com.cnpmjs.org/tailscale/tailscale/issues/2302

**Comment by vysecurity** [comment]
Odd, ICMP suddenly started working.

**Comment by DentonGentry** [comment]
The fix for UDP forwarding with --tun=userspace-networking will be in the 1.12.0 stable release. The 1.11.x builds should work until then.

**Comment by rugwirobaker** [comment]
@vysecurity have you managed to make this work? If you are running an exit node inside a docker container, can you share your setup?

**Comment by vysecurity** [comment]
I'm not sure if the provider helped me to get the CAP privileges or if it
just worked out on it's own.

**Comment by DentonGentry** [comment]
Tailscale 1.12 can function in a container environment where it does not have CAP_NET_ADMIN.

Earlier releases did not, you'd see errors about SO_MARK and tailscaled would exit.

**Comment by rugwirobaker** [comment]
@danderson I put together this. It starts and receives packets from my other nodes but doesn't forward them. https://github.com/tailscale/tailscale/issues/1970#issuecomment-877452753

**Comment by vysecurity** [comment]
I had the forwarding problem earlier but not sure how it fixed

**Comment by vysecurity** [comment]
I've confirmed that forwarding works, but ping packets are not being sent.

**Comment by mbroadhead-nr** [comment]
Where can `Tailscale without Tun` be downloaded from?

**Comment by wmanley** [comment]
> Where can `Tailscale without Tun` be downloaded from?

I assume it's referring to https://tailscale.com/kb/1112/userspace-networking
