### ISSUE TITLE
How to distinguish IP for the same device

### ISSUE THREAD

**Issue by cowrturn** [tailscale/tailscale#2510]
Hello, I have 2 Raspberry Pi 4B, the same ubuntu20.04 installed, and the device names are different. After adding tailscale to get the same IP, what's the problem?

**Comment by DentonGentry** [comment]
I suspect that Tailscale was installed on one system, and then cloned the SD card to the other system. Is that correct?
This cloned their Tailscale identity. To fix it, on one of the devices:
1. `sudo systemctl stop tailscaled`
2. `sudo rm -rf /var/lib/tailscale/`
3. `sudo systemctl start tailscaled`
4. `sudo tailscale up`

It will print a URL to authenticate again, and it will get a unique IP address.

**Comment by DentonGentry** [comment]
I'm going to close this given the symptoms exactly resemble what happens when an existing node is cloned. Please feel free to reopen if the steps in the previous comment do not resolve it.

**Comment by cowrturn** [comment]
Yes, I cloned the system from the SD card, I will try your suggestion. thank you very much!
