### ISSUE TITLE
Missing command to disable exit node?

### ISSUE THREAD

**Issue by schopenhauer** [tailscale/tailscale#2511]
Given there is no UI in Linux environments, I am looking for the CLi command to disable the use of a currently active exit node. While it's easy to enable the exit node using the `--exit-node=x.x.x.x` flag, disabling seems less straight-forward.

**Comment by DentonGentry** [comment]
`tailscale up --exit-node=`
(i.e. leave it empty)

This is the same pattern used for other 2-part arguments like `--advertise-routes=`

**Comment by DentonGentry** [comment]
I'll close this, if there is still a problem please feel free to reopen.
