### ISSUE TITLE
/api/v2/tailnet/tailscale.com/devices does not return IPv6 addresses

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2521]
https://twitter.com/jc00ke/status/1419816439213559815
reports that IPv6 addresses, like for ephemeral nodes, do not appear in the API devices list. Only IPv4 addresses do.

As an alternative for now, the output of `tailscale status --json` from a node on that Tailnet does contain IPv6 addresses.

**Comment by bradfitz** [comment]
(dup from author was https://github.com/tailscale/tailscale/issues/2522)
