### ISSUE TITLE
MacOS Monterey intermittent stops due to other network extensions

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2524]
Hi there,

On Monterey, the Tailscale app seems to intermittently stop and completely fail. I have to kill the Tailscale app so that the network is fixed, then re-launch and enable it to fix the network issue.

Basically everything stops routing.

Any logs I can provide to help identify the cause?

**Comment by bradfitz** [comment]
What's your Tailscale IP?

See anything in Console.app logs?

**Comment by vysecurity** [comment]
I'll have a look later today.

**Comment by medecau** [comment]
I'm having a similar issue.

Machines from different LANs loose routing for long periods very often.
_I've been running ping and auto-ssh to one of the remote machines for a few hours._
Machines in the same LAN can ping and SSh with no issues. 
The OS is macos Big Sur on all machines.

The dashboard indicates that the machines are connected.

When I tried to ping the phone while it was disconnected from WiFi it timed out until I disconnected/reconnected the Tailscale client.

I'm writing this from `100.87.40.14` and trying to ping `100.69.72.19`.

**Comment by mike-hearn** [comment]
I think this is similar/the same to the issue I'm having?

I'm on Big Sur but my situation is the same: after some indeterminate amount of time, Tailscale stops working (though the UI appears to still be connected). Can't send or receive a ping from any other device in the network. Closing Tailscale/re-opening fixes the issue, temporarily, until it dies again.

Very curious to see what the fix is for this, if any. It doesn't happen on any other Mac I own, only my M1 Macbook Air.

**Comment by DentonGentry** [comment]
What would be most useful is to send a bug report during a time when it isn't working, to let us focus on that moment in the telemetry. To do that:
1. With Tailscale 1.12.x (currently in App Store review) hold Option while clicking on the Tailscale icon in the menubar, then select Debug > Bug report...
1. With Tailscale 1.10 or earlier, open Terminal.app and run: `/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport`

Then paste the resulting string here.

**Comment by medecau** [comment]
I have been running `ping -a <host>` for awhile. _Where host points to 100.69.72.19_
The following bug report was collected moments before some ping replies came back.

BUG-478ebbe70b9758d68ee29365d8b8d9c528bb830b8a73046cd4eb6b34c1febb6e-20210801133408Z-aec42f0bd68b5059

**Comment by mike-hearn** [comment]
Two things - first, I just sent the bug report to with the ID `BUG-415e15b8c286c906cf0c65cfefe2a4ab355740289c8eddd53126b151c9f8e95c-20210802005107Z-5ec094e4314190a8`

Second, this issue may actually be specific to me and doesn't overlap with the other folks in this thread. In my case, it seems in some way related to Little Snitch. After having this issue for a couple of months, yesterday I removed the Little Snitch entry from my Network settings, and thereafter had no disconnects for over 24 hours. I re-added Little Snitch earlier today and the disconnect issues returned. So, for the time being my solution is just not to concurrently run Tailscale with the Little Snitch firewall.

**Comment by bradfitz** [comment]
Little Snitch is also a Network Extension: https://www.obdev.at/products/littlesnitch-big-sur/index.html says

> The previous version 4 of Little Snitch intercepted network traffic by means of a Network Kernel Extension. This type of kernel extension is deprecated in macOS Big Sur and no longer loads in the default configuration.
>
> Little Snitch 5 is based on the new Network Extension framework instead, which is fully supported on macOS Big Sur.

But Tailscale is also a Network Extension.

We've also seen interop problems with CrowdStrike Falcon (also necessarily now a Network Extension).

Reportedly macOS 11.5 contains some networking changes that might fix some bugs around involving multiple Network Extensions running at the same time. Which macOS version (of Big Sur) are you on?

**Comment by mike-hearn** [comment]
Looks like the machine is still on 11.3 (oops). I'll upgrade and see if that resolves it. Thanks.

**Comment by medecau** [comment]
Machines for BUGs mentioned in https://github.com/tailscale/tailscale/issues/2524#issuecomment-890523182 have no software similar to LittleSnitch and OS version is `11.5.1`.

**Comment by medecau** [comment]
Was able to get a longer ssh session to one of the remote machines thanks to autossh. Then used the first machine as JumpHost to the second one.

They're both on older versions of macOS. The first on 11.4 and the second on 11.3.
I'll carefully try to bump them to 11.5 as @bradfitz mentioned and will report later.

Neither machine has LittleSnitch, Falcon, or similar tools/extensions.

**Comment by DentonGentry** [comment]
Though updating to 11.5 might nonetheless be a good idea, the specific fix we know of is for multiple Network Extensions with Tailscale plus {other VPNs, CrowdStrike Falcon, Little Snitch, etc}.

**Comment by medecau** [comment]
Thanks for the heads-up @DentonGentry.
Anyway, updating macos Big Sur is turning out to be [harder than I expected](https://apple.stackexchange.com/questions/425005/update-macos-version-over-ssh).

**Comment by vysecurity** [comment]
The fix doesn't seem to be the fix as I'm on Monterey. What I do now after machine sleep is just close Tailscale and reopen it.

**Comment by medecau** [comment]
I noticed that machines seem more reliably available after enabling the "Prevent computer from sleeping automatically when the display is off" in the power management section of System Settings.

**Comment by telotortium** [comment]
I'm also seeing this issue. Here's a Bug Report after Tailscale stops working (MacOS 11.6 x86_64, Tailscale 1.14.6):

```
BUG-14d33f96882af1786a5a4bcc2ce3a34e5443ebe90db35a9acf5da848a0729ac7-20211020013217Z-2e964f3cb8a53ea4
```

Interestingly, I appear to have another Network Extension running (work computer).`systemextensionsctl list` shows another Network Extension (under `com.apple.system_extension.network_extension`), but not anything related to Tailscale (even after I restart Tailscale and Tailscale networking works again). Is this expected?

**Comment by telotortium** [comment]
I don't see that. I'm running from App Store - I should see it still, right?

**Comment by zonpantli** [comment]
Found this issue after figuring out that running together with CrowdStrike Falcon broke the Tailscale connectivity. It was working fine for couple of days and then seemed to stop working after we added a new Tailscale node to the network and updated the ACLs. Not sure though, if it was exactly this change that triggered the behaviour. I'm running Monterey and Tailscale 1.18.0. Started to work again after uninstalling the Falcon Agent. 

My co-worker is running Big Sur and Tailscale 1.18.0 and that still seems to be working fine for now.

Would it be useful to try to reproduce with some logging? Or do you think we should also rise issue at the CrowdStrike end?

**Comment by lenfree** [comment]
I had to downgrade the Sensor to v6.30.143 to make it work with M1 and Monterey and also affects some on BigSur. I've reported this to Falcon support but have yet to hear back from them.

**Comment by ryanofrivia** [comment]
Can confirm exact same issues for me

https://github.com/tailscale/tailscale/issues/2524#issuecomment-978311205
https://github.com/tailscale/tailscale/issues/2524#issuecomment-978284428

**Comment by bradfitz** [comment]
We're hearing that CrowdStrike fixed the Tailscale interop issue in Sensor Version 6.32.14507.

Can anybody else confirm?

**Comment by felixn-unity** [comment]
That sounds great, I have an ongoing support case with CrowdStrike and needed to do some wireshark stuff. @DentonGentry has access to my test setup, I will get that one upgraded ASAP

Felix

**Comment by felixn-unity** [comment]
I have not been able to make it fail with Tailscale 1.18.0 and Crowedstring 6.32 (145.07)

Will test tomorrow when I pack my laptop and goto the office - it always used to fail there

Felix

**Comment by felixn-unity** [comment]
Update: when I came into the office today, connected my laptop to my screen, and Tailscale was not working, was unable to use the menus, had to exit it and restart and traffic was flowing again - so bascially the same as before :(

I will upload diag files to CrowedStrike again

Felix

**Comment by ryanofrivia** [comment]
I can confirm that CrowdStrike version 6.32.14507.0 is now working with the TailScale App Store app. However, the CLI version installed via homebrew still does not work.

**Comment by vysecurity** [comment]
Tailscale VPN dies / hangs when the laptop sleeps. Then once you resume, you have to close Tailscale completely and re-open it.

**Comment by vysecurity** [comment]
I upgraded but still happens. You have to disconnect and reconnect after sleep.

**Comment by wingcomm** [comment]
I'm still seeing this here on macOS Monterey 12.5.1 and tailscale 1.30.0

BUG-01deeb523b3f156423d6c2bef9f667b8000f4a39bb42f4f8e1d457b5fc1dedaa-20220911071152Z-8bf0d4e62b58221a

**Comment by c10l** [comment]
I've switched to the open source version and haven't seen any issues since. CLI only but works!

https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

**Comment by DentonGentry** [comment]
macOS releases from 12.2 through 13.0 gradually fixed the conflicts between Network Extensions. At this point we don't see this happening much in user reports any more, and this bug accumulated a lot of updates, some contradictory, during the timeframe when Network Extensions were known to fight with each other.

I'm going to close this bug as resolved, I don't think we'd be able to disentangle any new reports from all of the previous state. If new issues with intermittent stops are noted, please open a fresh issue instead of reopening this one.
