### ISSUE TITLE
Ubuntu 18.04 installation guide should include wget instead curl.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2526]
On the minimal server install (vm),  wget comes with ubuntu as pre-install while curl needs to be installed for installing Tailscale.

The customer is requesting to update the installation guide by including wget for pkgs instead of curl.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ez9t)

**Comment by DentonGentry** [comment]
Fixed in install.sh: https://github.com/tailscale/tailscale/blob/3dedcd16408cd93ca4fc3456163d40fa67367278/scripts/installer.sh#L384
