### ISSUE TITLE
Subnet flapping when multiple nodes advertise the same subnet

### ISSUE THREAD

**Issue by derektamsen** [tailscale/tailscale#2535]
I have been running two tailscale nodes that export the same list of subnets. They serve as a high available gateway into the networks they are connected to. For several months this had been working as intended, if one node goes offline, clients automatically use the routes published from the other node. The deployment is the same as described in #299. During normal operation traffic would always pass through the same node.

Yesterday, I upgraded the linux tailscale binary on the nodes publishing the subnets from 1.8.3 to 1.10.2 and I started seeing client flap between the two nodes. The clients are running macos tailscale version 1.10.1. Typically, the errors the client sees are related to network topology changes when the route flaps between the two nodes publishing the subnet.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3gb4h)

**Comment by DentonGentry** [comment]
That's odd. Could you put the IP addresses of one of the subnet routers either on this bug or send to support@tailscale.com? We can find the account, and then find the other subnet router to investigate.

The client version shouldn't impact the choice of which one is the primary, the coordination server determines that.

**Comment by derektamsen** [comment]
@DentonGentry thanks for taking a look. I emailed support@tailscale.com the details.

**Comment by DentonGentry** [comment]
Based on subsequent developments, I think we can close this now. Feel free to reopen if there is more to be done.
