### ISSUE TITLE
Android F-Droid build is failing

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2536]
Forking the project and running the GitLab CI, the failure is: `./version/tailscale-version.sh: 10: set: Illegal option -o pipefail`

**Comment by crawshaw** [comment]
I believe pipefail is a bash feature. Is it running under a different shell?

**Comment by DentonGentry** [comment]
Apparently, probably dash.

**Comment by DentonGentry** [comment]
Forked F-Droid's fdroiddata repo on GitLab, we can see the CI output now https://gitlab.com/DentonGentry/fdroiddata/-/jobs/1459019935

```
2021-07-28 13:27:37,326 DEBUG: > /opt/android-sdk/tools/bin/apkanalyzer dex packages --defined-only build/com.tailscale.ipn/android/build/outputs/apk/fdroid/release/android-fdroid-release-unsigned.apk
2021-07-28 13:27:43,158 INFO: success: com.tailscale.ipn
2021-07-28 13:27:43,159 INFO: Finished
2021-07-28 13:27:43,159 INFO: 1 build succeeded
++ ./tools/build-contains-signatures.py com.tailscale.ipn:54
no signatures found, skipping publish
++ continue
++ echo '$ ./tools/audit-gradle.py $CHANGED;'
$ ./tools/audit-gradle.py $CHANGED;
++ ./tools/audit-gradle.py com.tailscale.ipn
```

*no signatures found, skipping publish* seems key. Signing got broken somehow.

**Comment by DentonGentry** [comment]
`no signatures found, skipping publish` comes from https://gitlab.com/DentonGentry/fdroiddata/-/blob/master/tools/build-contains-signatures.py#L21

I think it is looking for metadata/com.tailscale.ipn/signatures/1.12.1-1d7592eb117-g1fc94ccf979/*

**Comment by DentonGentry** [comment]
Oh: this is likely because I'm running the CI in my fork, which of course won't have the signing keys.
https://gitlab.com/DentonGentry/fdroiddata/-/jobs/1459019935

Shoot.

**Comment by DentonGentry** [comment]
I think https://github.com/tailscale/tailscale-android/commit/67c2869ec6985ac9feadfc00ad9470205b708390 is likely to fix this.

I'm expecting to build another 1.13.x unstable release tomorrow, after https://github.com/tailscale/tailscale-android/pull/17 does in, which will trigger another F-Droid build. We'll see.

**Comment by DentonGentry** [comment]
We just pushed https://github.com/tailscale/tailscale-android/commit/3575ef712abdeda6a708b595c864d6ccaef3a260, for 1.13.19-td37451bac-g82b6b8dbd36, which will kick off a new F-Droid build sometime in the next 24 hours, whenever the bot notices.

It has not noticed yet: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.tailscale.ipn.yml

**Comment by DentonGentry** [comment]
https://f-droid.org/en/packages/com.tailscale.ipn/ still shows 1.11.106 as the current version.

**Comment by DentonGentry** [comment]
I asked for help from F-Droid: https://gitlab.com/fdroid/fdroiddata/-/issues/2446

**Comment by DentonGentry** [comment]
F-Droid developers responded quickly on the issue: the builder has a large backlog. It isn't that our builds are failing, it is that the builder is behind. It sounded like something happened that slowed it or stopped it for a few days, so now it has to chrun through extra work to catch up.

There are two issues in the build scripts printing errors which I'll fix, but those errors aren't causing the build to fail just complaining during the build.

Yesterday the F-Droid builder released Version 1.11.151-d145c594ad6-g7b2e61e80cd. We'll just monitor it for a while as it progresses.

**Comment by DentonGentry** [comment]
1.13.19 is available at https://f-droid.org/en/packages/com.tailscale.ipn/

**Comment by DentonGentry** [comment]
Release 60, 1.13.53-t8bdf87883-g30324736c98 available for download: https://f-droid.org/en/packages/com.tailscale.ipn/
