### ISSUE TITLE
net/dns/resolver: allocs test failing on Go 1.17

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2545]
```
$ go test -v -run=TestAllocs ./net/dns/resolver
=== RUN   TestAllocs
    tsdns_test.go:945: forward: allocs = 3; want 2
--- FAIL: TestAllocs (0.00s)
FAIL
FAIL    tailscale.com/net/dns/resolver  0.003s
FAIL
```

cc @josharian

**Comment by bradfitz** [comment]
Which GOOS?

**Comment by crawshaw** [comment]
linux/amd64 (inside WSL2)

**Comment by josharian** [comment]
Interestingly, I can't reproduce on my linux/arm64 VM, but can on my linux/amd64 nixos machine...except that the Go toolchain doesn't work correctly past about 250 commits back, so I'm figuring out how to get past that breakage so that I can bisect.

**Comment by josharian** [comment]
First broken commit is https://go-review.googlesource.com/c/go/+/310175, which enabled regabidefer, which explains why this is amd64 only. The extra allocation is reported from this line:

```go
	go r.handleQuery(p)
```

RegabiDefer is:

```go
	// RegabiDefer enables desugaring defer and go calls
	// into argument-less closures.
	RegabiDefer bool
```

So making that `go` call now allocates a closure.

I don't see anything reasonable to do about that. I'm going to change the allowed allocs to 3.
