### ISSUE TITLE
Unable to find local sonos devices when connected to Tailscale

### ISSUE THREAD

**Issue by drnikcuk** [tailscale/tailscale#2548]
Not sure if this is a tailscale issue or not to be honest, from a usage perspective its a pain that's for sure.

Running latest tailscale client on windows 10, when launching Sonos it claims no devices are found on the local network, disconnect from tailscale and try again and all the devices are suddenly available.

Like i say, not sure if this is a tailscale or sonos issue, but though i'd try here before talking to Sonos.

**Comment by crawshaw** [comment]
Are you using an exit node? By default, exit nodes block access to your local LAN. As of 1.12, there is an "Allow local network access" button for this.

**Comment by drnikcuk** [comment]
Nope not using an exit node anywhere.

**Comment by DentonGentry** [comment]
I think Sonos uses SSDP to discover speakers. Maybe the SSDP packets are being sent to tailscale0? Because it is the first interface, perhaps.

Do you use the S1 app, S2 app, or something else?
https://support.sonos.com/s/downloads?language=en_US

**Comment by drnikcuk** [comment]
It's the V2 App on windows.

Just tested on the android app and it seems to behave in the same was as windows.

**Comment by DentonGentry** [comment]
I don't have any Sonos devices, but installed the Solos S2 app on a Windows host, disconnected Tailscale, and could see the SSDP M-SEARCH frames for Zoneplayer going out on the Wifi network.

Nothing changed when I tried again after connecting Tailscale, I still see SSDP frames going out on the Wifi.

So whatever is happening, it doesn't appear to be misdirected SSDP frames.

**Comment by johnsheehan** [comment]
Are you using advertise routes on any of your Tailscale nodes? Once I enable a subnet, my Sonos breaks. But if I turn off the subnet, it works again.

**Comment by DentonGentry** [comment]
Are you comfortable running Wireshark? https://wireshark.org/

The main thing we don't know is whether SSDP packets to discover local Sonos devices are not making it onto the LAN at all, or whether the requests are making it but responses are being lost/blocked/etc. Using Wireshark to monitor the Wi-Fi or Ethernet, it would be good to know whether you see SSDP with the subnet routes and without the subnet routes.

**Comment by bradfitz** [comment]
FWIW, I use both Tailscale and Sonos at the same time, but I've only ever tried on iOS & macOS. I don't control Sonos from other platforms.

**Comment by johnsheehan** [comment]
Up until I enabled advertise routes today, I had no issues with iOS and macOS controllers for my Sonos system. I emailed Wireshark captures to support.

**Comment by drnikcuk** [comment]
> 
> 
> Are you using advertise routes on any of your Tailscale nodes? Once I enable a subnet, my Sonos breaks. But if I turn off the subnet, it works again.

Yup, i have multiple routes getting advertised within my network.

**Comment by johnsheehan** [comment]
@drnikcuk If you disable them from the Tailscale admin, does the Sonos start working?

**Comment by johnsheehan** [comment]
I seem to have resolved my issue. I'm not sure why it's working, but it is. I'll try to keep this short. I recently changed routers. My old router used 192.168.7.x for DHCP IPs, the new one uses 192.168.1.x. To deal with some old devices, I had temporarily set the subnet mask on the new network to 255.255.0.0 so the new IPs could talk to the old IPs. The old devices being all updated with new IPs, I went back today and updated the subnet mask on the router to 255.255.255.0 and now Sonos works just fine, even with one of my Tailscale nodes set to advertise routes.

**Comment by tfer6** [comment]
@orrc did you by chance ever resolve this issue?  

Just started using Tailscale and am experiencing the same issue with my Android .  Regardless of if I have exit node/or subnet switched on/off.   I did notice that if I toggle Tailscale on after I've opened the Sonos android app it seems to work fine.  Guessing the problem is with the initial discovery of the Sonos system.

**Comment by orrc** [comment]
@tfer6 Nope. So long as Tailscale is enabled, regardless of whether I start the Sonos app before or after, the Sonos app cannot see any of my devices.

**Comment by DentonGentry** [comment]
Support for the v2 Sonos app went into 1.34.x.

The Sonos S1 app will be added in 1.36.0.
https://twitter.com/dgentry/status/1612939151632134144

**Comment by helloiamoliver** [comment]
I've still got this issue on Windows & MacOS - did anyone manage to solve it?

**Comment by p-rintz** [comment]
This issue still appears if you have a subnet router in the same network as your Sonos.

Currently, setting "--accept-routes=false" on your PC will fix this.

It would be great if Tailscale would not accept routes for local subnets.

```
[philipp@nixos:~]$ ip r get 10.1.0.1
10.1.0.1 dev tailscale0 table 52 src 100.94.158.155 uid 1000 
    cache 

[philipp@nixos:~]$ ip -4 a
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    altname enp0s31f6
    inet 10.1.0.171/24 brd 10.1.0.255 scope global dynamic noprefixroute eno1
       valid_lft 5500sec preferred_lft 5500sec
```

Seems to be a long running issue: https://github.com/tailscale/tailscale/issues/1227

**Comment by DocNaes** [comment]
New tailscale user (v1.80.0) and having this same problem with sonos discovery on my pc (but not on iOS). My NAS is advertising my home subnet. Consistent with above comments within my PC tailscale menu preference setting I turned "use tailscale subnets" off and that seemed to fix it.

**Comment by Louminati** [comment]
...still consistent with the comments here more than a year after the last post I can confirm that the fix for this on a Windows PC where the Sonos desktop app will not discover the local system is to right-click the Tailscale icon running in the background on the system tray, choosing "preferences" and unchecking "Use Tailscale subnets."  I'm on version 1.94.2.  Cheers!
