### ISSUE TITLE
NixOS: add tailscale to environment.systemPackages in NixOS module.

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#255]
users need to run `tailscale up` after enabling the tailscale NixOS module. We need to add `tailscale` to `environment.systemPackages` in the module to make this Just Work.

Technically you can solve this by adding the tailscale pkg to your user profile, but this will lead to version skew between the CLI and daemon.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686555540091) by [Unito](https://www.unito.io/learn-more)

**Comment by dfcarney** [comment]
Hello from Asana!

**Comment by FRidh** [comment]
This is done on master/unstable.

**Comment by danderson** [comment]
Given that the next release is now scheduled for May, I need to backport this for 20.09 users in the meantime.

**Comment by DentonGentry** [comment]
I think this is done. During the next bug scrub if there are no further comments, we'll close this issue.

**Comment by DentonGentry** [comment]
I think this is done, closing issue.
