### ISSUE TITLE
Tailscale connected prevents GoPro app from working

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2554]
https://twitter.com/scottalaird/status/1421137488534380545

Steps to reproduce:

GoPro: Hero9, with v1.52, v1.6, and v1.6 "GoPro labs"
Android: Galaxy S20 Ultra, Android 11, Tailscale v1.10.2-36fe8addc39

Install GoPro Quik app.  Connect to GoPro.  Click on "start preview".

Tailscale active: 100% failure.
Tailscale stopped: 100% success.

**Comment by scottlaird** [comment]
To clarify very slightly, I've tested this with a GoPro Hero9 and 3 different firmware revs: v1.52, v1.6, and the v1.6 "GoPro Labs" release which has a bunch of beta features enabled.  All behaved identically.

**Comment by DentonGentry** [comment]
Was there anything interesting in adb logcat?

We do not have a GoPro here, it will be difficult to work on this in the near future.

**Comment by 2m** [comment]
I also have the same problem with GoPro9. Phone successfully switches to GoPro camera Wi-Fi network, but after showing spinner for a while in the GoPro Quick app, it fails to connect to camera when Tailscale is active.

adb logcat does not show any errors from the GoPro app. Let me know if I can take some steps and capture information relevant to this issue.

**Comment by zeroZshadow** [comment]
What ip does your phone get when connected to the GoPro camera Wi-Fi network? (Is it perhaps using a non-standard address range)

**Comment by 2m** [comment]
My phone gets `10.5.5.101` and GoPro9 has `10.5.5.9`.

**Comment by DentonGentry** [comment]
In the 1.30 release we're adding a number of apps to a list to bypass the VPN, apps which need to connect directly to local devices. The first few went into https://github.com/tailscale/tailscale-android/pull/50.

We need to identify the app string for the GoPro app of concern here. It is likely something like com.gopro.quik. If you have ADB connected, the app name will be printed on all of its log lines.

Can someone post the string to use for the GoPro app?

**Comment by 2m** [comment]
Its `com.gopro.smarty`.

**Comment by DentonGentry** [comment]
The code to fix this has been submitted. It will first appear in a 1.29.x developer release on the Open Testing track in the Play Store.
- Join via web: https://play.google.com/apps/testing/com.tailscale.ipn
- Join via Play Store app: https://play.google.com/store/apps/details?id=com.tailscale.ipn

The GoPro fix is not in the 1.29.0 build which is there now, but will be in the next 1.29.x build.
