### ISSUE TITLE
Ability to enroll servers in the network without associating them with a 'user'.

### ISSUE THREAD

**Issue by daankets** [tailscale/tailscale#2555]
It seems strange that, once someone adds a host - for example a test server - this device is forever associated with the user that authenticated it. It should be possible for admins to enroll hosts without permanently associating them to a user. An association to a team for example, or an ACL group, would make more sense.

**Comment by DentonGentry** [comment]
We're likely to address this by making nodes with ACL Tags applied be disassociated from the user who created them. We already do this for the ACLs applied, only considering the Tag not the identity of the User.

**Comment by DentonGentry** [comment]
This was delivered as part of the tags-v2 effort: https://tailscale.com/blog/acl-tags-ga/
Nodes with a Tag are disassociated from the user who created them, they are owned by the Tag.
