### ISSUE TITLE
MacOS Version build still 1.10.1

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2558]
Hi team!

MacOS version build seems to be still 1.10.1. Is this as designed? I've noticed all other agents are now 1.12.1 or above.

**Comment by DentonGentry** [comment]
The MacOS and iOS apps have been submitted for review at the App Store. The review process takes however long it takes, we have no control over it.

**Comment by vysecurity** [comment]
Is there any build guide so I can make one myself? Keen to get bleeding edge updates and test stuff ahead of time.

**Comment by DentonGentry** [comment]
For MacOS the [Tailscaled-on-MacOS](https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS) version is buildable by cloning this repository and following the same steps as Linux. You would quit the Tailscale from the menubar, and run it from the command line.

**Comment by vysecurity** [comment]
Ah right, seems that it'll be difficult for me to build a MacOS App out of just tailscaled and Tailscale. I have a certificate which I can sign for own use.

**Comment by DentonGentry** [comment]
I'm going to close this as I don't think there is anything to address. The update will appear in the App Store soon, whenever Apple completes its review.
