### ISSUE TITLE
Ability to combine tags

### ISSUE THREAD

**Issue by daankets** [tailscale/tailscale#2559]
It would be convenient if it would be possible to combine tags in ACL rules, for example:

```json
"TagOwners": {
    "tag:financeApp":["group:admins","group:security"],
    "tag:production":["group:admins", "group:devOps"],
    "tag:acceptance":["group:admins", "group:devOps"],
    "tag:test":["group:admins", "group:devOps"],
    "tag:development":["group:admins", "group:devOps"]
},
"ACLs": [
  { "Action":"accept", "Users":["group:financeAppDevTeam"], "Ports":["AND(tag:financeApp,OR(tag:development,tag:test)):443,22", "AND(tag:financeApp,tag:acceptance:443"]},
  { "Action":"accept", "Users":["group:finance"], "Ports":["AND(tag:financeApp,OR(tag:production, tag:acceptance)):443"]}
]
```

This would allow combinations of specifying environments (dev, test, acceptance, production etc) with projects or device roles.

**Comment by daankets** [comment]
@DentonGentry Is there any workaround for this at the moment: for example, can I setup an ACL that would allow devices tagged 'internal','prd','server' to access other servers with the same tags?

**Comment by DentonGentry** [comment]
To set expectations: I do not expect to implement this feature request, I don't think it is the tradeoff we want between expressive power of the ACLs versus being able to reason about what the ACL will do.

Multiple tags can be applied to a node, handling such logical conditions by defining a specific tag instead.

**Comment by DentonGentry** [comment]
I am declining to implement this.
