### ISSUE TITLE
derp/derp_server: unbalanced {register,unregister}Client() calls.

### ISSUE THREAD

**Issue by stablebits** [tailscale/tailscale#256]
**Describe the bug**

`unregisterClient()` isn't called in `accept()` when `s.sendServerInfo()` fails. Also, it looks like peers shouldn't be notified with `framePeerGone` when unregistering "replaced" client connections.

**To Reproduce**
Noticed while looking at the code.

**Additional context**

Possible fix:

```
diff --git a/derp/derp_server.go b/derp/derp_server.go
index 274d002..9e4a09f 100644
--- a/derp/derp_server.go
+++ b/derp/derp_server.go
@@ -198,20 +198,20 @@ func (s *Server) unregisterClient(c *sclient) {
        if cur == c {
                c.logf("removing connection")
                delete(s.clients, c.key)
+
+               // Find still-connected peers to notify that we've gone away
+               // so they can drop their route entries to us. (issue 150)
+               for pubKey, connNum := range c.sentTo {
+                       if peer, ok := s.clients[pubKey]; ok && peer.connNum == connNum {
+                               go peer.requestPeerGoneWrite(c.key)
+                       }
+               }
        }
 
        s.curClients.Add(-1)
        if c.preferred {
                s.curHomeClients.Add(-1)
        }
-
-       // Find still-connected peers to notify that we've gone away
-       // so they can drop their route entries to us. (issue 150)
-       for pubKey, connNum := range c.sentTo {
-               if peer, ok := s.clients[pubKey]; ok && peer.connNum == connNum {
-                       go peer.requestPeerGoneWrite(c.key)
-               }
-       }
 }
 
 func (s *Server) accept(nc Conn, brw *bufio.ReadWriter, remoteAddr string, connNum int64) error {
@@ -254,11 +254,12 @@ func (s *Server) accept(nc Conn, brw *bufio.ReadWriter, remoteAddr string, connN
                c.info = *clientInfo
        }
 
-       s.registerClient(c)
        err = s.sendServerInfo(bw, clientKey)
        if err != nil {
                return fmt.Errorf("send server info: %v", err)
        }
+
+       s.registerClient(c)
        defer s.unregisterClient(c)
 
        return c.run(ctx)
```

**Comment by stablebits** [comment]
On a semirelated note:

This pattern in `derp/derphttp/derphttp_client.go` can result in `closeForReconnect()` redundantly closing an already reestablished connection. In the worst (mostly theoretical) case, `Send()` and `Recv()` (running in concurrent loops) would be running `connect()` and `closeForReconnect()` calls in lockstep endlessly.

```
237 func (c *Client) Send(dstKey key.Public, b []byte) error {
238     client, err := c.connect(context.TODO(), "derphttp.Client.Send")
239     if err != nil {
240         return err
241     }
242     if err := client.Send(dstKey, b); err != nil {
243         c.closeForReconnect()
244     }
```

**Comment by bradfitz** [comment]
@stablebits, thanks!

> In the worst (mostly theoretical) case, Send() and Recv() (running in concurrent loops) would be running connect() and closeForReconnect() calls in lockstep endlessly

Whoa, I think you might've just solved an old mystery of ours! We did see that a couple times and never properly chased it down yet. (/cc @crawshaw @danderson)

Do you want to send PRs for these? (ideally as 3 separate changes)

**Comment by stablebits** [comment]
@bradfitz sure, I'll send PRs.

**Comment by stablebits** [comment]
Regarding this:

> Also, it looks like peers shouldn't be notified with framePeerGone when unregistering "replaced" 
> client connections.

the approach suggested by the patch above is incorrect. Please see:
https://github.com/tailscale/tailscale/pull/263

**Comment by bradfitz** [comment]
Closing; #262 and #263 were merged.
