### ISSUE TITLE
tailscale 1.12.1 breaks name resolution on Big Sur 11.5.1

### ISSUE THREAD

**Issue by pcarrier** [tailscale/tailscale#2561]
Name resolution seems to time out:
```
pcarrier@cat ~/r/monorepo (pcarrier/tailscale)> ping google.com
ping: cannot resolve google.com: Unknown host
```

with seemingly straightforward DNS settings:

![image](https://user-images.githubusercontent.com/8641/127785102-7bc17720-fe44-4403-b0f6-f821af773d9a.png)

```
pcarrier@cat ~/r/monorepo (pcarrier/tailscale)> /Applications/Tailscale.app/Contents/MacOS/Tailscale status
100.94.213.13   cat                  pierre@      macOS   -
100.126.253.21  tailscale-0          pierre@      linux   -
100.100.231.123 tailscale-1          pierre@      linux   -
100.123.195.21  tailscale-2          pierre@      linux   -
```

**Comment by DentonGentry** [comment]
100.94.213.13 is reporting a number of errors like:

```
2021-07-30 18:09:12.650075 +0200 +0200: dns: enqueue: request queue full
2021-07-30 18:09:12.650126 +0200 +0200: dns: enqueue: request queue full
2021-07-30 18:09:12.650193 +0200 +0200: dns: enqueue: request queue full
2021-07-30 18:09:12.650258 +0200 +0200: dns: enqueue: request queue full
2021-07-30 18:09:13.494828 +0200 +0200: dns: error: context deadline exceeded
2021-07-30 18:09:13.494894 +0200 +0200: dns: error: context deadline exceeded
2021-07-30 18:09:13.494914 +0200 +0200: dns: error: context deadline exceeded
2021-07-30 18:09:13.494933 +0200 +0200: dns: error: context deadline exceeded
```

**Comment by DentonGentry** [comment]
Could you:
1. in a Terminal, `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug -daemon-goroutines=true >~/goroutines.txt`
1. Either attach goroutines.txt here, or email it to support@tailscale.com

It looks like all of the goroutines for forwarding requests to upstream DNS servers are tied up.

**Comment by DentonGentry** [comment]
In the Tailscale menubar icon, deselecting "Preferences > Use Tailscale DNS Settings" will likely resolve the DNS timeout problem, though at the cost of breaking the Split DNS you've added.

**Comment by pcarrier** [comment]
Without any changes, https://pcarrier.com/support/goroutines.txt

Turning off "Use Tailscale DNS Settings" doesn't seem to help.

**Comment by DentonGentry** [comment]
> Turning off "Use Tailscale DNS Settings" doesn't seem to help.

That is unexpected. It should leave DNS entirely to MacOS to handle.

Could you paste `scutil --dns` output, with "Use Tailscale DNS Settings" selected and with it deselected?

My best guess for why DNS resolution breaks with "Use Tailscale DNS Settings" involves a feature added in 1.12.1 to automatically use DNS-over-HTTPS for well-known global resolvers like 8.8.8.8 and 8.8.4.4. I guess I could imagine that resulting in overflowing the queue for DNS resolution.

Unfortunately Apple's app store provides no way to rollback to the 1.10.2 version, which is why I'd hoped that disabling "Use Tailscale DNS Settings" would let the app at least limp along until we can diagnose the problem and get it fixed.

**Comment by pcarrier** [comment]
https://pcarrier.com/support/scutil_dns_selected.txt and https://pcarrier.com/support/scutil_dns_unselected.txt

I'll happily install outside of the App Store if that helps.

**Comment by DentonGentry** [comment]
scutil shows:
```
resolver #1
  search domain[0] : home
  nameserver[0] : 100.94.213.1
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)
  order    : 101600

resolver #2
  nameserver[0] : 100.94.213.1
  flags    : Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)
  order    : 200000
```

100.94.213.1 is within the CGNAT range that Tailscale uses, but is not a Tailscale address. I think your ISP uses CGNAT, and there is a conflict (https://github.com/tailscale/tailscale/issues/1381). For example, Starlink uses CGNAT addresses. When you connect Tailscale, Tailscale is trying to use the same IP address range as the DNS server supplied by the ISP, and ends up breaking access to it.

You have a router/residential/gateway/etc connecting to the ISP, with WiFi or Ethernet within the home? We can probably make this work: in https://login.tailscale.com/admin/dns, enable the "Override local DNS" selector. This means that when Tailscale connects, the 100.94.213.1 supplied in the ISP's DHCP response will be replaced by 8.8.8.8 and 8.8.4.4 and there won't be a conflict over the 100.x.y.z IP addresses. When Tailscale disconnects, the 100.94.213.1 DNS server supplied by the ISP will be restored.

**Comment by pcarrier** [comment]
Still no connectivity with "Override local DNS". Uploaded https://pcarrier.com/support/2_disconnected_scutil.txt and https://pcarrier.com/support/2_connected_scutil.txt under the regimen.

**Comment by DentonGentry** [comment]
Given the screenshot in the first comment showing nameservers 8.8.8.8 and 8.8.4.4, I would expect after enabling "Override local DNS" that 2_connected_scutil.txt would show 8.8.8.8 and 8.8.4.4 as nameservers. Instead the most recent 2_connected_scutil.txt shows:
- 10.51.240.10, which comes from the split DNS server configured for cluster.local in https://login.tailscale.com/admin/dns,
- 172.24.255.1, and I don't know where that comes from.

Something, somewhere has to offer a route to 172.24.255.1, as that is a private IP address in the 172.16.0.0 range. Do you know what that DNS server is?

**Comment by DentonGentry** [comment]
ETIMEDOUT.

**Comment by pcarrier** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2000
