### ISSUE TITLE
Installing Hyper-V Feature on Windows 10 goes haywire if Tailscale service active

### ISSUE THREAD

**Issue by StraightfaceStudios** [tailscale/tailscale#2565]
If you have tailscale running and you install the Hyper-V role the new Virtual Switch will attempt to attach to the tailscale virtual network adapter instead of your hardware adapter. Hilarity and pain ensues until you disable the tailscale service and reboot.  The Hyper-V role will then finish setup and installation, bind to the hardware NIC and you can re-enable tailscale.

**Comment by DentonGentry** [comment]
Possibly a symptom of [#1682](https://github.com/tailscale/tailscale/issues/1682), fixed in Tailscale 1.26.

**Comment by DentonGentry** [comment]
I believe this was a symptom of https://github.com/tailscale/tailscale/issues/1682. Please reopen if still seen with Tailscale 1.26 or later.
