### ISSUE TITLE
admin UI: RDP session link doesn't work from services page

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2585]
There is an issue opening RDP connections using the Launch button via a browser on MAC. 

rdp://full%20address=s%3A100.75.24.19:3389
![image](https://user-images.githubusercontent.com/75628398/128244941-29777e61-3734-4fd7-9692-97a343b6a80c.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3fv9t)

**Comment by roozbehk** [comment]
changing it to below URL works
rdp://full%20address=s=x.x.x.x:3389

**Comment by bradfitz** [comment]
Looks like you don't even need the 3389. Docs:

https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/ff393661(v=ws.10)

What a weird URL format: there is no authority part at all, despite the double slash. It starts with the scheme and then after `rdp://` it is apparently immediately URL query params, one of which is literally named `full address` (which needs to be escaped as `full%20address`, and then its value is `s:<IP-or-hostname>[:<PORT>]`.

I wonder if that weird URL format is tripping up something server-side in our context-aware template autoescaping or something.

**Comment by mihaip** [comment]
Fixed by tailscale/corp@aad7f565c5676a4c222378cdab93b52698569109 (once deployed)
