### ISSUE TITLE
macOS sometimes does not cleanly update from App Store

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2587]
Getting an error after upgrading the macOS Tailscale app to 1.12.10.

![image](https://user-images.githubusercontent.com/75628398/128255067-8d80cbe5-6265-4d15-9937-699d5363d99a.png)

Workaround : 

Restart Tailscale App fix the issue.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3fvpt)

**Comment by DentonGentry** [comment]
Sometimes the frontenv (non-sandbox) process keeps running while the sandbox IPN process is replaced. We haven't figured out how to reliably kill it during an update.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2377
