### ISSUE TITLE
synology: upgrading the tailscale package from DSM6 to DSM7 doesn't copy over state

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#2592]
When I upgraded my DSM6 synology to DSM7, Tailscale wouldn't start and had to be upgraded to the DSM7 build.
However, the state wasn't copied over resulting in an unregistered node.

I was able to manually copy over state by doing the following:
1. Stop tailscale via the UI
2. SSH into the machine
3. Run
```
sudo cp /var/packages/Tailscale/etc/* /var/packages/Tailscale/var/
sudo chown -R tailscale:tailscale /var/packages/Tailscale/var
```
4. Start tailscale from the UI

**Comment by SylvainDx** [comment]
Maybe I did something wrong, I'm not use to ssh.
I logged with an admin account an use sudo in front of the command line above.
however it change nothing.

**Comment by maisem** [comment]
@SylvainDx did you add `sudo` to both commands? I've updated the instructions to work with sudo instead.

**Comment by SylvainDx** [comment]
I think i did ... i'm on holiday now ;) i'll test again in 2 weeks and let you know

**Comment by SylvainDx** [comment]
ok I did it again.
but i've got no improvement on my syno.
I'm always stuck on the login page with Failed to log in: Failed to fetch if refreshed

**Comment by SylvainDx** [comment]
is it possible to "clear" the package and install it from scratch again?
