### ISSUE TITLE
Forward DNS traffic to exit node

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2596]
Today, any device using an exit node needs to be configured to use a DNS server that is reachable via the exit node. If you setup Tailscale in its default configuration, and your machine's DNS is still your local router (192.168.1.1:53), your connection to it will break when you turn on exit nodes.

Instead, we should forward all DNS traffic to the exit node for it to resolve. We can do this by having the exit node server DNS-over-HTTP via the peer API.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1713
