### ISSUE TITLE
100.100.100.100 DNS forwarding fails when server canonicalizes responses

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#2597]
A user reported an instance where a query of the form `ABCD.example.com` fails to resolve through 100.100.100.100 but works correctly if sent directly to the DNS server. After examining packet captures, @danderson and I discovered that the DNS server's response modified the question section: the response referred to `abcd.example.com`.

For historical reasons, we hash the DNS question and combine that with the original DNS transaction ID, so if the response's question is modified, DNS forwarding will drop the packet.

In the logs, this appears as `dns: error: txid doesn't match`. If you encounter this error, as a workaround try using a completely lowercase hostname. Failing that, if you can capture the response packet from the server (e.g. with tcpdump or wireshark), look the contents of the question section of the server's response.

The workaround is somewhat awkward, instead we should solve the problem by simply passing the original transaction ID through rather than performing hashing -- it is not needed with the current implementation.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3g029)

**Comment by bradfitz** [comment]
Either of you want to fix it? Sounds like we could make our fake test DNS server also do that to make a new unit test?

**Comment by sailorfrag** [comment]
I'm planning to work on this today.
