### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [tailscale/tailscale#2603]
```
+ make -C .. release_aar
make: Entering directory '/home/vagrant/build/com.tailscale.ipn'
find: ‘/home/vagrant/.cache/tailscale-android-go-6fa85e8201f1f75fb7323eb48a0b24274a6e33b2’: No such file or directory
find: ‘/home/vagrant/.cache/tailscale-android-go-6fa85e8201f1f75fb7323eb48a0b24274a6e33b2’: No such file or directory
want: e336267ea2a637426c0302945d0c1f8fa2f2f627
got: 5cd337198ead0768975610a135e26257153198c7
rm -rf /home/vagrant/.cache/tailscale-android-go-*
wget https://github.com/tailscale/go/releases/download/build-6fa85e8201f1f75fb7323eb48a0b24274a6e33b2/linux.tar.gz -O "/tmp/tmp.cIl4qYDSFH.tgz"
--2021-08-06 05:49:53--  https://github.com/tailscale/go/releases/download/build-6fa85e8201f1f75fb7323eb48a0b24274a6e33b2/linux.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-06 05:49:54 ERROR 404: Not Found.

Makefile:42: recipe for target 'toolchain' failed
make: *** [toolchain] Error 8
make: Leaving directory '/home/vagrant/build/com.tailscale.ipn'
```

It seems since 1.13.42-tfd7b738e5-ga68462ec65f tailscale-android uses your own go fork. But it seems the go binary hosted on GItHub is removed? And if it works with the origin go?

**Comment by DentonGentry** [comment]
We started using a local fork of the Go 1.16 toolchain with 1.12.1 to pull in https://github.com/tailscale/go/commit/6fa85e8201f1f75fb7323eb48a0b24274a6e33b2 in order to fix https://github.com/tailscale/tailscale/issues/2478 and https://github.com/tailscale/tailscale/issues/2450.

I imagine the toolchain release got removed yesterday when we switched HEAD to use Go 1.17. I'll adjust the Android build to use that same toolchain.

**Comment by DentonGentry** [comment]
Updated toolchain: https://github.com/tailscale/tailscale-android/commit/d81f8a03b654f42e04a55f222084247b1f4684c4

**Comment by DentonGentry** [comment]
I just committed a 1.13.53-t8bdf87883-g30324736c98 build using Go 1.17, we'll expect https://monitor.f-droid.org/builds/log/com.tailscale.ipn/60 in the next few days.

**Comment by linsui** [comment]
Thanks!

**Comment by DentonGentry** [comment]
Build 67 succeeded: https://monitor.f-droid.org/builds/log/com.tailscale.ipn/67
Build 68 was on a release branch, which F-Droid doesn't build.
Build 69 failed but it looks like a LetsEncrypt certificate issue https://monitor.f-droid.org/builds/log/com.tailscale.ipn/69

I think the F-Droid build has been fixed for a while.
