### ISSUE TITLE
synology: investigate what the HTTP proxy option does

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2605]
Synology supports using an HTTP proxy but not SOCKS. What is this used for?

<img width="1084" alt="Screen Shot 2021-08-06 at 8 13 15 AM" src="https://user-images.githubusercontent.com/2621/128532543-98fe08d0-0fda-4648-9428-4877326262fb.png">

In userspace mode we already support being a SOCKS5 proxy in tailscaled and we have an open tracking bug IIRC to also be an HTTP proxy in tailscaled. 

Maybe this would let people use things like Hyper Backup on Synology without TUN.

/cc @maisem @crawshaw

**Comment by nadenf** [comment]
HTTP proxy support in Tailscaled is being tracked here: https://github.com/tailscale/tailscale/issues/2289
