### ISSUE TITLE
Support for ipv6-only hosts

### ISSUE THREAD

**Issue by mosajjal** [tailscale/tailscale#2610]
Hi,

previously, `login.tailscale.com` used to work (although somewhat unreliably) with ipv6-only networks, but after the switch to the new default (`https://controlplane.tailscale.com`), it won't work at all. is there plans to support ipv6 for this server.

appreciate your great project! 

Cheers, 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3g58x)

**Comment by DentonGentry** [comment]
Ah: there is no AAAA record for controlplane.tailscale.com. We can look into that.

**Comment by DentonGentry** [comment]
We've added an IPv6 address for controlplane.tailscale.com which should fix support for IPv6-only hosts.
Please reopen this issue if there is still a problem, in testing here it looks like it is working.

**Comment by jpluscplusm** [comment]
A peripheral issue I've found is with machines that have both v4 and v6 default routes, but where only v6 grants Internet access. The login fallback to the v6 address you added does eventually work, but it takes a good 60-120 seconds ... during which time it can definitely _appear_ like nothing's working :-) If there were a `-4` or `-6` option on the appropriate tailscale/d CLI, that would be handy.
