### ISSUE TITLE
High CPU usage during large transfers between Windows nodes

### ISSUE THREAD

**Issue by rageshkrishna** [tailscale/tailscale#2612]
Running  version 1.12.3 (td91ea7286-ge1bbbd90c) on two Windows 10 nodes. My backup agent started running on my laptop and began transferring a huge amount of data over the tailscale adapter to my desktop. Both machines are now showing very high CPU usage from Tailscale. Is this expected? 

![image](https://user-images.githubusercontent.com/1134972/128622793-66484968-4100-43c4-8b34-fd9438fa7bbc.png)

![image](https://user-images.githubusercontent.com/1134972/128622890-d235eacf-1664-4ab7-bfea-a09176a5f4dd.png)

Please let me know if you'd like me to collect more information.

**Comment by DentonGentry** [comment]
Is this correct?
- there really is a lot of data being exchanged, the backup program is backing up a lot of data
- the backup is proceeding at 395 Mbps
- tailscaled is using 43% if the CPU. The kernel is using another 30%.
?

If so: that does take considerable CPU time. Tailscale runs wireguard in userspace via wireguard-go, all of the encryption overhead will be charged to the tailscale process. If the kernel is using 30% moving this amount of data around, 43% to encrypt all of it doesn't seem out of line.

**Comment by rageshkrishna** [comment]
Yes to all three questions, so it sounds like this is expected. Maybe WireGuardNT will improve things. I'm sure this must already be on your roadmap.

Feel free to close the issue if there's nothing to investigate here. Thanks!
