### ISSUE TITLE
Raspberry Pi install - invalid repository signature

### ISSUE THREAD

**Issue by CJKohler** [tailscale/tailscale#2617]
I'm updating an older Raspberry Pi (linux kernel 4.19.66-v7+)  and when I run:
`sudo apt update && sudo apt full-upgrade -y`

I get:
```
W: GPG error: https://pkgs.tailscale.com/stable/raspbian buster Release: The following signatures were invalid: BADSIG 458CA832957F5868 Tailscale Inc. (Package repository signing key) <info@tailscale.com>
E: The repository 'https://pkgs.tailscale.com/stable/raspbian buster Release' is no longer signed.
```

I have updated other Pi's today, so I know it is not a universal problem. 
I have done tried these commands, but it didn't help:
```
pi@pi14:~ $ curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.gpg | sudo apt-key add -
OK
pi@pi14:~ $ curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.list | sudo tee /etc/apt/sources.list.d/tailscale.list
# Tailscale packages for raspbian buster
deb https://pkgs.tailscale.com/stable/raspbian buster main
```

**Comment by DentonGentry** [comment]
Do you know what Raspbian version it is running? I don't immediately know what that kernel version corresponds to.

**Comment by CJKohler** [comment]
it was on ""Raspbian GNU/Linux 9 (stretch)", but I can't replicate the issue anymore, and Tailscale did get updated on that machine. So as far as i'm concerned you can close it
