### ISSUE TITLE
Support Digital Ocean Elastic IP's (IP block lists)

### ISSUE THREAD

**Issue by cliedeman** [tailscale/tailscale#2620]
Digital Ocean has different way of mapping outgoing traffic over a static ip using an internal anchor ip. 

I managed to get this working with using wireguard directly but could not find a way with tailscale.

```
iptables -t nat -A POSTROUTING -p all -o eth0 -j SNAT --to-source <anchor_ip>
```

References 

- https://docs.digitalocean.com/products/networking/floating-ips/how-to/find-anchor-ips/

**Comment by DentonGentry** [comment]
Do you notice a problem, is Tailscale unable to find the public IP address? We use Digital Ocean VMs for a number of purposes. Tailscaled uses [STUN](https://en.wikipedia.org/wiki/STUN) to find the public IP associated with a private internal IP.

`tailscale ping` will say whether it was able to establish a direct tunnel or had to go through a relay. We generally see Digital Oceam VMs able to make direct tunnels, meaning that they do figure out their public IP.

**Comment by cliedeman** [comment]
Hi @DentonGentry, sorry I should have mentionted that my IP Block list setup is working using the machines public ip.
But I would like to use an elastic ip for failover purposes.

**Comment by DentonGentry** [comment]
If you set up an Elastic IP: does it work? Is Tailscale able to make direct connections?

You likely will need to allow UDP port 41641 and 3478 in: https://tailscale.com/kb/1082/firewall-ports/

I just don't immediately understand what tailscaled would need to do differently.

**Comment by cliedeman** [comment]
Hi @DentonGentry I am not 100% sure what you mean.

Tailscale is working for me using the machines public ip. I can access machines behind ip blocks lists using the machines public IP (No Configuration needed tailscale picks this up).

From what I can tell the ping indicates I am not using a relay

I don't understand it well but the postrouting SNAT `--to-source` flag overrides the source ip. The outgoing traffic ends up with the elastic ip as the source (Some Digital Ocean internal magic)

OpenVPN Example:
- https://blog.programster.org/openvpn-digitalocean-ip-alias

Ciaran

**Comment by cliedeman** [comment]
@DentonGentry I confirmed that both the elastic ip and public ip of the machine are listed in endpoints

**Comment by DentonGentry** [comment]
At this point I'm going to close this, as I don't think additional work is needed to enable the Digital Ocean Elastic IPs. They appear to work as is.
https://github.com/tailscale/tailscale/issues/1066 tracks a feature request to specify interfaces to bind to, which would allow the public IPs for each VM to be omitted from the Endpoints.
