### ISSUE TITLE
Allow making Tailscale tray icon image static

### ISSUE THREAD

**Issue by cliedeman** [tailscale/tailscale#2621]
This is definitely a minor nit
Tray icons on mac are mostly commonly static 

![image](https://user-images.githubusercontent.com/3578740/128835945-1fcee579-46cb-4566-a93b-741cbfbe2e37.png)

The tailscale icon is animated and constantly catches my eye making me think something needs my attention.

Possible Solutions:
Allow the user to disable the animation or make it static by default on mac

**Comment by bradfitz** [comment]
It should only animate while initially connecting and then be static. Are you saying it's always animating even when Tailscale is up and working?

What's your Tailscale IP? Which version?

**Comment by cliedeman** [comment]
@bradfitz you are correct. There must have been a different issue on my network because I can't reproduce it now.

Thanks
