### ISSUE TITLE
Minor visual glitch on macOS client 1.12.3

### ISSUE THREAD

**Issue by abreis** [tailscale/tailscale#2623]
<img width="264" alt="tail" src="https://user-images.githubusercontent.com/95046/128877766-999688ae-acd4-42c8-94b4-ac34a5908c9d.png">

The second menu item is blank.

**Comment by abreis** [comment]
So, after the update I was also unable to connect, and when I logged out I was unable to log back in. This was while connected to a restricted network that had to use DERP.

I switched to an unrestricted network (personal hotspot) and was able to log back in. Everything works again (also in the restricted network), and the glitch no longer appears.

My guess is that the update left the app in an undefined state.

**Comment by DentonGentry** [comment]
Possibly related to the update, if it happens again please update the bug.
We're tracking other symptoms about not starting up cleanly after an update in https://github.com/tailscale/tailscale/issues/2587, so we'd handle the investigation on that bug.

Barring further updates, we'll expect to close this during the next bug scrub.
