### ISSUE TITLE
Possible login retry issue when there is no node key

### ISSUE THREAD

**Issue by mtlynch** [tailscale/tailscale#2624]
I just reinstalled my Win10 OS, but when I tried to reinstall Tailscale on my new build, I can't log in. After installation, I saw a toast notification saying I needed to authenticate to Tailscale, so I did (using Google Auth). But the Tailscale icon in the notification tray still said I needed to log in.

If I right-click the Tailscale icon and click "Log in," nothing happens. Sometimes, after ~15 seconds, it sends my browser to the Tailscale login page. If I complete the login, it says the login is successful and I can close the window, but then Tailscale on my local system doesn't change state. But sometimes, after I click "Log in" from the Tailscale system tray icon, it doesn't do anything at all.

I've tried closing and relaunching the Tailscale app: no change. I've tried rebooting my system: no change.

There are two log-looking files in `%LocalAppData%\Tailscale\` but they're both empty:

```powershell
>ls "$env:LOCALAPPDATA\Tailscale\"


    Directory: C:\Users\Michael\AppData\Local\Tailscale


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         8/10/2021   9:40 AM            438 prefs.conf
-a----         8/10/2021   9:33 AM            209 tailscale-ipn.log.conf
-a----         8/10/2021   9:49 AM              0 tailscale-ipn.log1.txt
-a----         8/10/2021   9:49 AM              0 tailscale-ipn.log2.txt
```

```powershell
> Get-Content "$env:LOCALAPPDATA\Tailscale\tailscale-ipn.log1.txt"
> Get-Content "$env:LOCALAPPDATA\Tailscale\tailscale-ipn.log2.txt"
```

I'm on version 1.12.3 (td91ea7286-ge1bbbd90c) on Win10.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3glap)

**Comment by DentonGentry** [comment]
Could you send the email address used for this account to support@tailscale.com? We may be getting some telemetry from that Windows system even if it isn't able to log in.

**Comment by DentonGentry** [comment]
The time yesterday when this was reported was during a time we were working on the authentication servers. I would have expected the node to keep retrying until it worked, I think we should look at the retry logic when a device has no node key and is logging in for the first time.

**Comment by DentonGentry** [comment]
At this point I don't expect to make further progress on the incident from 8/2021. Since then we've made a few changes in the IPN state machine that handles authentication, which might have resolved this.
