### ISSUE TITLE
Non-atomic apt upgrade

### ISSUE THREAD

**Issue by umanwizard** [tailscale/tailscale#2625]
When upgrading an Ubuntu system with `apt upgrade`, all the installation steps happen before all the "setup" steps. For example, if your system needs to upgrade both "foo-package" and tailscale, it will proceed as follows:

* Install new foo-package over old version
* Install new tailscale over old version
* Run any setup scripts for foo-package
* Run any setup scripts for tailscale.

This causes issues if the setup script for foo-package hangs waiting for user input (as does, for example, the docker.io package, which asks if you want to restart your running docker containers). If the user does an `apt upgrade` over an ssh connection (on a tailscale interface), the connection will go down when the new tailscale is installed over the old tailscale, but it will never be restarted, since the setup scripts for the new tailscale never get a chance to run.

Concretely, tailscale's `prerm` script stops the service, and its `postinstall` script restarts it.

**Comment by DentonGentry** [comment]
I think this is the same issue as https://github.com/tailscale/tailscale/issues/3009, which has the steps we'd need to do to fix it.

Dup of https://github.com/tailscale/tailscale/issues/3009
