### ISSUE TITLE
Cannot access hello.ipn.dev over https.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2626]
Customers can access other nodes on my Tailnet (good!) but can't access hello.ipn.dev in a browser; it just loads forever. Everything else works fine. Here is a seemingly relevant thing from my logs:
**open-conn-track: timeout opening (TCP x.x.x.x:56822 => 100.101.102.103:443) to node [MNw8B]; online=yes, lastRecv=never**

Customers have tried doing it both ways. I've also tried connecting using nc and curl to no avail. In an email, attached is a PCAP (*fail.pcap) from Wireshark of a customer trying to connect to 100.101.102.103 over the tailscale0 interface. (the DNS request to host.example.com is unrelated). For comparison, he has also attached a PCAP (tailok.pcap) of a successful request to a non-hello node within my tailnet.

Please find pcap from email, as it has personal info of customer.

Client OS : POP_OS
Tailscale Version : 1.13.57 (unstable)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3gg7l)

**Comment by sailorfrag** [comment]
I think hello is missing information about many devices; I can't ping it or open it in a web browser on my personal tailnet. Running `tailscale status` on hello, it has one of my devices but none of the rest. That device can connect fine.

We may have bumped into a maximum device limit for hello, this needs further investigation.

**Comment by sailorfrag** [comment]
To be clear: for anybody encountering this issue, it appears to be a problem with hello, not a problem with your device.

**Comment by bradfitz** [comment]
Hello's netmap is dynamic based on who's online nowadays. So if you have unconnected devices in your personal tailnet, they won't be in Hello's netmap until they connect.

**Comment by sailorfrag** [comment]
One missing device on my personal tailnet is currently connected. Perhaps its netmap isn't being refreshed often enough?

**Comment by bradfitz** [comment]
"often enough" suggests there are timers or something involved, but everything in Control happens in response to other events. (for clarity for others on this public bug)

The thing to investigate then is whether a node coming online generates the right events (or in the right order). Perhaps a node coming online first wakes up Hello, but then afterwards marks itself online. In that case there might be a race where Hello generates its netmap using the wrong online/offline info.

**Comment by Smittyvb** [comment]
(bug reporter here) Now I can access `hello.ipn.dev` from one computer on Tailscale, but not from another computer also on Tailscale.

**Comment by DentonGentry** [comment]
At this point we have discontinued use of the ipn.dev domain. Renewing the certificate for hello.ipn.dev was a manual process which we several times neglected to do.

hello.ts.net is now present, for the Early tailnets which had the hello node auto-populated. *.ts.net certificate renewals have automation available.
