### ISSUE TITLE
admin: add dark mode support

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#2634]
It'd be nice if the admin panel provided a dark mode so that we can fit in more naturally for users working late at night, or simply those who prefer not to be blinded by a thousand suns worth of #fff.

Please add a 👍 to this issue if it matters to you.

**Comment by bradfitz** [comment]
This is affecting our Twitter scores. We just got zero points: https://twitter.com/tjhorner/status/1466806113622450181

**Comment by mayakacz** [comment]
Additional considerations:
* In addition to dark mode, we should consider adding other modes at the same time. Specifically, a high-contrast mode is often required by some large customers for accessibility. Currently, the admin console has (non-functional) text that would likely not perform well.
* We should consider syncing colour scheme to system, e.g., dark if dark, or light in day / dark at night.
* We should also add dark mode to mobile apps, and any desktop functionality present beyond a menu (e.g., onboarding screens)

**Comment by coreybruce** [comment]
This would be a nice dark theme example for it
![image](https://user-images.githubusercontent.com/8393780/211723296-909622d1-451a-4798-8e56-49471f562ff1.png)

**Comment by SPDurkee** [comment]
Any ETA on this?
Almost all websites/admin interfaces have a dark/light theme option.

**Comment by rosszurowski** [comment]
This launched today! Enjoy! https://x.com/Tailscale/status/1790763549700112408

**Comment by coreybruce** [comment]
Yess! thank you so much! :smiley: :heart: 
![yes.gif](https://www.icegif.com/wp-content/uploads/2023/07/icegif-441.gif)
