### ISSUE TITLE
Please support Ubuntu 21.04 for Raspberry pi

### ISSUE THREAD

**Issue by clarkezone** [tailscale/tailscale#2640]
To get 64bit ubuntu server on a RaPi, I need to be on the Hippo release 21.04.  Tailscale doesn't appear to support this currently.  Please consider adding support

**Comment by DentonGentry** [comment]
What happens when trying to use https://pkgs.tailscale.com/stable/#raspbian-buster ?

**Comment by ananthb** [comment]
I'm using https://pkgs.tailscale.com/stable/#ubuntu-hirsute on my pi 4 with no issue.

**Comment by danderson** [comment]
The repositories are all multi-architecture, so if you're running Ubuntu 21.04, follow the install instructions for Ubuntu 21.04 and it should work fine. We only list Raspbian separately because it's a distinct distro from the others (debian + rpi-specific stuff).
