### ISSUE TITLE
userspace-networking incoming TCP doesn't always work right away

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2642]
I've noticed a few times now, most recently with 1.12.3, that a tailscaled running in userspace-networking mode doesn't always forward incoming TCP connections to localhost reliably for a bit after the process is started.

Note that I can ping it and the first curl fails, but then it works a bit later: 
```
crow5k:~ $ ping foo
PING foo.tailscale.com.beta.tailscale.net (100.127.0.49): 56 data bytes
64 bytes from 100.127.0.49: icmp_seq=0 ttl=64 time=161.106 ms
^C
--- foo.tailscale.com.beta.tailscale.net ping statistics ---
2 packets transmitted, 1 packets received, 50.0% packet loss
round-trip min/avg/max/stddev = 161.106/161.106/161.106/0.000 ms

crow5k:~ $ curl http://foo:8383/debug/varz
curl: (7) Failed to connect to foo port 8383: Connection refused

crow5k:~ $ curl http://foo:8383/debug/varz
[works, output omitted]
```

**Comment by michaelyork** [comment]
+1, have seen this exact same behavior. Happy to share logs if helpful.

**Comment by bradfitz** [comment]
Maybe related to lazy wg config, @danderson? Or some lazy/async netstack config?

Example today:

logs: fceaf5a9b386893703e09cd23941b959ebdde1fd05e324206bcc35be29ea585e
starting at: 2021-09-23 20:55:34.683177622

My desktop to server's ssh:
```
2021-09-23 20:55:43.479715179 +0000 UTC: Accept: TCP{100.123.101.40:61047 > 100.127.0.48:22} 64 tcp ok
```

... only one filter log line, but it failed quickly several times in a row, getting immediate connection resets.

Me taking a bug report:
```
2021-09-23 20:55:57.782114316 +0000 UTC: user bugreport: BUG-fceaf5a9b386893703e09cd23941b959ebdde1fd05e324206bcc35be29ea585e-20210923205557Z-868457bada3f20f2
```

Me trying again and it then working:

```
2021-09-23 20:56:02.777491432 +0000 UTC: Accept: TCP{100.123.101.40:61053 > 100.127.0.48:22} 64 tcp ok
2021-09-23 20:56:02.927086398 +0000 UTC: netstack: forwarding incoming connection to 127.0.0.1:22
```

**Comment by bradfitz** [comment]
The 255.255.255.255/32 thing didn't fix it.

SSHing from my mac laptop to a prod userspace machine, the client side sees RSTs for 3-4 seconds, and then it works:

<img width="998" alt="Screen Shot 2022-01-06 at 3 41 30 PM" src="https://user-images.githubusercontent.com/2621/148467913-8a8aa500-96dd-4092-b07d-9aa810fc7fc0.png">

So the WireGuard bits are working (we're getting packets). And netstack is working enough to reply with RSTs.

I ssh'ed in without Tailscale to the target before that above and captured a pair of bugreport markers before the first SSH and right after it worked:

```
$ tailscale bugreport
BUG-fceaf5a9b386893703e09cd23941b959ebdde1fd05e324206bcc35be29ea585e-20220106233936Z-5fb533e8ea2e0ad2
$ tailscale bugreport
BUG-fceaf5a9b386893703e09cd23941b959ebdde1fd05e324206bcc35be29ea585e-20220106233950Z-58757c230158a379
```

**Comment by michaelyork** [comment]
@bradfitz I'm still able to consistently reproduce as well if additional bugreports are helpful.

**Comment by bradfitz** [comment]
@michaelyork, I can too, at least on certain pairs of machines. Can you make it happen 100% of the time? If so, any trick?

This is a top bug of ours that's blocking some other features, so I keep trying to work on it a bit whenever it bites me again or I think I might have a new lead.

**Comment by michaelyork** [comment]
@bradfitz Happy to help - your product is probably the single most magical piece of software I use on a daily basis these days :)

Yes, I can reproduce 100% of the time when connecting to at least one particular host. Let me know if it's easiest to connect live for a minute. Happy to demo.

**Comment by bradfitz** [comment]
@michaelyork, I'm free for the next 2 hours if you're around.

Can you try unstable build 1.19.187 and set TS_DEBUG_NETSTACK=true in tailscaled environment on the target (userspace) machine? You can add a line to /etc/default/tailscaled like...

```
$ grep NETSTACK /etc/default/tailscaled
TS_DEBUG_NETSTACK="true"
```

Then restart tailscaled to pick up that setting.

Then `tailscale bugreport` on that same target machine before you try to connect to it, then connect to it from another machine to cause the problem a few times until it works, and then `tailscale bugreport` on the same target machine again.

With those two bugreport markers and the verbosity turned up, I should be able to see what's happening.

**Comment by michaelyork** [comment]
Sweet. Up to do it live right now? Can be reached via https://t.me/michael_york

**Comment by bradfitz** [comment]
(@michaelyork and I got his Synology NAS updated to a bleeding edge unreleased SPK running with extra debugging; he'll try to catch it next time it happens)

**Comment by bradfitz** [comment]
The new logging caught one:

```
# fceaf5a9b386893703e09cd23941b959ebdde1fd05e324206bcc35be29ea585e
2022-01-19 03:18:26.81426081 +0000 UTC: TCP ForwarderRequest: 100.123.101.40:58613 -> 100.127.0.48:22
2022-01-19 03:18:26.970302437 +0000 UTC: CreateEndpoint error for 100.123.101.40:58613 -> 100.127.0.48:22: connection was refused
...
2022-01-19 03:18:30.292829093 +0000 UTC: TCP ForwarderRequest: 100.123.101.40:58619 -> 100.127.0.48:22
2022-01-19 03:18:30.493404601 +0000 UTC: netstack: forwarding incoming connection to 127.0.0.1:22
```

So, what does `connection was refused` mean? Where's that come from?

Also odd: it took me five tries to connect (first four failed quickly), but there are only two total (one failure + one success) in the logs. Were there 3 failures of some unlogged type, followed by the `connection was refused`, followed by it working?

/cc @crawshaw

**Comment by bradfitz** [comment]
That error is:

```go
// ErrConnectionRefused indicates the connection was refused.
//
// +stateify savable
type ErrConnectionRefused struct{}

func (*ErrConnectionRefused) isError() {}

// IgnoreStats implements Error.
func (*ErrConnectionRefused) IgnoreStats() bool {
        return false
}
func (*ErrConnectionRefused) String() string { return "connection was refused" }
```

There are two places it can come from, both in `tcpip/transport/tcp/connect.go`:

```go
// synRcvdState handles a segment received when the TCP 3-way handshake is in
// the SYN-RCVD state.
func (h *handshake) synRcvdState(s *segment) tcpip.Error {
        if s.flags.Contains(header.TCPFlagRst) {
                // RFC 793, page 37, states that in the SYN-RCVD state, a reset
                // is acceptable if the sequence number is in the window.
                if s.sequenceNumber.InWindow(h.ackNum, h.rcvWnd) {
                        return &tcpip.ErrConnectionRefused{}
                }
                return nil
        }
```

and

```go
// synSentState handles a segment received when the TCP 3-way handshake is in
// the SYN-SENT state.
func (h *handshake) synSentState(s *segment) tcpip.Error {
        // RFC 793, page 37, states that in the SYN-SENT state, a reset is
        // acceptable if the ack field acknowledges the SYN.
        if s.flags.Contains(header.TCPFlagRst) {
                if s.flags.Contains(header.TCPFlagAck) && s.ackNumber == h.iss+1 {
                        // RFC 793, page 67, states that "If the RST bit is set [and] If the ACK
                        // was acceptable then signal the user "error: connection reset", drop
                        // the segment, enter CLOSED state, delete TCB, and return."
                        h.ep.workerCleanup = true
                        // Although the RFC above calls out ECONNRESET, Linux actually returns
                        // ECONNREFUSED here so we do as well.
                        return &tcpip.ErrConnectionRefused{}
                }
                return nil
        }
```

**Comment by bradfitz** [comment]
I just noticed in the Wireshark screenshot in https://github.com/tailscale/tailscale/issues/2642#issuecomment-1007017504 that in the four initial SYNs that failed, the `ECN` (Explicit Congestion Notification ) and `CWR` (Congestion Window Reduced).

And in the one where it worked, thost bits are absent.

The article https://www.catchpoint.com/blog/ece-cwr-tcp says:

> During the synchronization phase of a connection between client and server, the TCP CWR and ECE flags work in conjunction to establish whether the connection is capable of leveraging congestion notification. In order to work, both client and server need to support ECN. To accomplish this, the sender sends a SYN packet with the ECE and CWR flags set, and the receiver sends back the SYN-ACK with only the ECE flag set. Any other configuration indicates a non-ECN setup.

So the client side supports ECN and is trying to handshake with it but the netstack side doesn't support it (or we haven't enabled it?) so the connection setup fails or something. Not sure whether it's supposed to, or is supposed to retry.

More research needed, but that seems like the best lead so far.

**Comment by bradfitz** [comment]
Ah....

`// TODO(gvisor.dev/issue/995): ECN is not currently supported,`

https://github.com/google/gvisor/issues/995 -- "Support ECN (Explicit Congestion Notification) in TCP endpoints"

**Comment by bradfitz** [comment]
Debugging notes:

To see ECN stats on macOS, run (as root!)....
```
crow5k:~ $ sudo netstat -sp tcp | grep -i ecn
	13465 client connections attempted to negotiate ECN
		8766 client connections successfully negotiated ECN
		3315 times graceful fallback to Non-ECN connection
		8157 times lost ECN negotiating SYN, followed by retransmission
		0 server connection attempted to negotiate ECN
		0 server connection successfully negotiated ECN
		0 time lost ECN negotiating SYN-ACK, followed by retransmission
		740 connections using ECN have seen packet loss but no CE
		0 connection using ECN have seen packet loss and CE
		2 connections using ECN received CE but no packet loss
		2 connections fell back to non-ECN due to SYN-loss
		30 connections fell back to non-ECN due to reordering
		0 connection fell back to non-ECN due to excessive CE-markings
```

Various knobs:

```
# sysctl  -a | grep -i ecn
net.inet.tcp.ecn_timeout: 60
net.inet.tcp.ecn_initiate_out: 2
net.inet.tcp.ecn_negotiate_in: 2
net.inet.tcp.ecn_setup_percentage: 100
net.inet.ipsec.ecn: 0
net.inet.mptcp.probecnt: 5
net.inet6.ipsec6.ecn: 0
```

**Comment by bradfitz** [comment]
https://lists.bufferbloat.net/pipermail/ecn-sane/2020-January/000594.html is interesting too:

> IIRC Padma said they shut it off for something like an hour or 3
> whenever they notice an "anomaly", according to a bunch of heuristics
> that can occasionally hit false positives:

Apple slides: https://datatracker.ietf.org/meeting/98/materials/slides-98-maprg-tcp-ecn-experience-with-enabling-ecn-on-the-internet-padma-bhooma-00.pdf

**Comment by bradfitz** [comment]
I CAN REPRODUCE IT!!! Only on Linux, but good enough to convince me that https://github.com/tailscale/tailscale/pull/3770 is the fix.

On Linux:

```
$ sudo sysctl net.ipv4.tcp_ecn=1
```

(For me, it was set to 2 before, which means "Enable ECN when requested by incoming connections but do not request ECN on outgoing connections")

But once you force ECN on on Linux, then modified that PR to log when it removed it:

```
        if p.RemoveECNBits() { // Issue 2642 
                ns.logf("XXX netstack removed ECN")
        }
```

Then you'll see curl to the userspace tailscaled IP work every time, with the logging that it removed ECN:

````
2022/01/19 18:41:23.014481 XXX netstack removed ECN
2022/01/19 18:41:23.048391 netstack: forwarder connection to 127.0.0.1:8080 closed
2022/01/19 18:41:23.496088 XXX netstack removed ECN
2022/01/19 18:41:23.531139 netstack: forwarder connection to 127.0.0.1:8080 closed
2022/01/19 18:41:23.812847 XXX netstack removed ECN
2022/01/19 18:41:23.846999 netstack: forwarder connection to 127.0.0.1:8080 closed
```

But if you comment out the `RemoveECNBits` line instead, it fails every time:

```
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
root@tsbi:/home/bradfitz# curl 100.70.219.120:8080
curl: (7) Failed to connect to 100.70.219.120 port 8080: Connection refused
```

Seems 100% reproducible, which is great.

macOS does its weird 5% or 50% or automatic thing with ECN which makes it really hard to debug when ECN is actually being used. I think there's a ioctl/sockopt to force ECN, but I'm not exactly sure what it is. But for now I don't care, since I can reproduce perfectly from Linux.

Still not sure why gVisor hates ECN so much, but at least we have a workaround.

cc @danderson @DentonGentry

**Comment by bradfitz** [comment]
Now on to debugging netstack to understand what's happening more.

If I add this to gvisor (base https://github.com/inetaf/netstack/commit/8aa80cf23d3cced44d45a31a5d8b841fae949dcf)

```patch
diff --git a/tcpip/transport/tcp/protocol.go b/tcpip/transport/tcp/protocol.go
index b4500025..b1be7ea4 100644
--- a/tcpip/transport/tcp/protocol.go
+++ b/tcpip/transport/tcp/protocol.go
@@ -193,6 +193,7 @@ func (p *protocol) tsOffset(src, dst tcpip.Address) tcp.TSOffset {
 //
 // If the passed TTL is 0, then the route's default TTL will be used.
 func replyWithReset(st *stack.Stack, s *segment, tos, ttl uint8) tcpip.Error {
+       panic("Boom")
        route, err := st.FindRoute(s.nicID, s.dstAddr, s.srcAddr, s.netProto, false /* multicastLoop */)
        if err != nil {
                return err
```

I get:

```
2022/01/19 19:11:19.219099 Accept: TCP{100.108.65.105:57232 > 100.70.219.120:8080} 60 tcp ok
panic: Boom

goroutine 326 [running]:
inet.af/netstack/tcpip/transport/tcp.replyWithReset(0xc000198400, 0xc0004fc000, 0x4, 0x0)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/transport/tcp/protocol.go:196 +0x32
inet.af/netstack/tcpip/transport/tcp.(*protocol).HandleUnknownDestinationPacket(0xc0004e6000, {0x1f90, {0xc0004fc020, 0x4}, 0xdf90, {0xc0004fc00c, 0x4}}, 0xc00014e480)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/transport/tcp/protocol.go:168 +0x13a
inet.af/netstack/tcpip/stack.(*nic).DeliverTransportPacket(0xc00013a000, 0x6, 0xc00014e480)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/stack/nic.go:886 +0x29b
inet.af/netstack/tcpip/network/ipv4.(*endpoint).handleValidatedPacket(0xc000469100, {0xc000832040, 0x14, 0x40}, 0xc00014e480, {0x0, 0x0})
        /home/bradfitz/gohack/inet.af/netstack/tcpip/network/ipv4/ipv4.go:1068 +0xfd6
inet.af/netstack/tcpip/network/ipv4.(*endpoint).HandlePacket(0xc000469100, 0x871b95)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/network/ipv4/ipv4.go:854 +0x2b0
inet.af/netstack/tcpip/stack.(*nic).DeliverNetworkPacket(0xc00013a000, {0xc00088dbf0, 0x1}, {0x0, 0x0}, 0x800, 0xc00014e480)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/stack/nic.go:788 +0x2d6
inet.af/netstack/tcpip/link/channel.(*Endpoint).InjectLinkAddr(...)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/link/channel/channel.go:207
inet.af/netstack/tcpip/link/channel.(*Endpoint).InjectInbound(...)
        /home/bradfitz/gohack/inet.af/netstack/tcpip/link/channel/channel.go:202
tailscale.com/wgengine/netstack.(*Impl).injectInbound(0xc00047a090, 0xc000622900, 0xc000235320)
        /home/bradfitz/src/tailscale.com/wgengine/netstack/netstack.go:525 +0x73c
tailscale.com/net/tstun.(*Wrapper).filterIn(0xc0002d4000, {0xc0000de010, 0x3c, 0xffef})
        /home/bradfitz/src/tailscale.com/net/tstun/wrap.go:615 +0x78d
tailscale.com/net/tstun.(*Wrapper).Write(0xc0002d4000, {0xc0000de000, 0xc0001e4140, 0x1}, 0x10)
        /home/bradfitz/src/tailscale.com/net/tstun/wrap.go:628 +0x7c
golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0xc000452380)
        /home/bradfitz/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/receive.go:477 +0x4d1
created by golang.zx2c4.com/wireguard/device.(*Peer).Start
        /home/bradfitz/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/peer.go:199 +0x295
```

**Comment by bradfitz** [comment]
Found it!

```go
func (f *Forwarder) HandlePacket(id stack.TransportEndpointID, pkt *stack.PacketBuffer) bool {
        s := newIncomingSegment(id, f.stack.Clock(), pkt)
        defer s.decRef()

        // We only care about well-formed SYN packets.                                                                        
        if !s.parse(pkt.RXTransportChecksumValidated) || !s.csumValid || s.flags != header.TCPFlagSyn {
                return false
        }
```

Note the `s.flags != header.TCPFlagSyn`.

😂

**Comment by bradfitz** [comment]
I dug through the git history on google/gvisor and it goes all the way back to the first code dump from the Google tree to github when the code at the time was:

```
commit d02b74a5dcfed4bfc8f2f8e545bca4d2afabb296
Author: Googler <noreply@google.com>
Date:   Fri Apr 27 10:37:02 2018 -0700

    Check in gVisor.
    
    PiperOrigin-RevId: 194583126
    Change-Id: Ica1d8821a90f74e7e745962d71801c598c652463
```
...
```go
func (f *Forwarder) HandlePacket(r *stack.Route, id stack.TransportEndpointID, vv *buffer.VectorisedView) bool {
       s := newSegment(r, id, vv)
       defer s.decRef()

       // We only care about well-formed SYN packets.
       if !s.parse() || s.flags != flagSyn {
               return false
       }
```

**Comment by bradfitz** [comment]
Filed upstream https://github.com/google/gvisor/issues/7075

**Comment by bradfitz** [comment]
Fixed (with workaround) in 1.20.2 and 1.21.x unstable builds at the same time.

Keeping this open to track removing our workarounds and using the upstream fix (https://github.com/google/gvisor/commit/0b81b32c95f6643936d0894671d0b00809fe22d6) instead.

**Comment by bradfitz** [comment]
When the 1.22 tree is branched I'll remove our ECN bit masking workaround on main and close this bug.

**Comment by DentonGentry** [comment]
I believe the gvisor fix for ECN bits was pulled in by https://github.com/tailscale/tailscale/pull/4222

**Comment by bradfitz** [comment]
Yeah, but per the Feb 23 comment, I wanted to remove our workaround first.
