### ISSUE TITLE
cmd/tailscale: up complains about login-server changing from login to controlplane again

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2644]
Sorry, @crawshaw, the controlplane CLI issues persist.

At head, d2d55bd63cfafe2234764856c35018f07b5f82b6 ...

```
bradfitz@tsdev:~/src/tailscale.com$ go run ./cmd/tailscale up --advertise-routes=10.2.200.75/32
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --advertise-routes=10.2.200.75/32 --advertise-exit-node

exit status 1
bradfitz@tsdev:~/src/tailscale.com$ tailscale up --advertise-routes=10.2.200.75/32 --advertise-exit-node=false
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --advertise-exit-node=false --advertise-routes=10.2.200.75/32 --login-server=https://controlplane.tailscale.com

```

**Comment by crawshaw** [comment]
You tried to run `--advertise-exit-node` and it told you to run `--advertize-exit-node=false`?

**Comment by bradfitz** [comment]
> You tried to run --advertise-exit-node and it told you to run --advertize-exit-node=false?

I wanted to turn it off anyway. I'd forgotten I had it on.

The bad part is that:

a) it didn't tell me about the missing `--login-server` change in the first step but it did in the second step
b) it told me about the changing login server at all; it shouldn't have in either step.

**Comment by crawshaw** [comment]
I get that, but there’s some other bug I’m trying to understand. The command you pasted was for advertise-exit-node=true and then it said, in addition to the bogus login server line, to run advertise-exit-node=false. Was that a typo in the original issue text, or something that the cli code messed up?

**Comment by crawshaw** [comment]
Oh nope, I misread it

**Comment by crawshaw** [comment]
Will take a look

**Comment by crawshaw** [comment]
One more Q: the first command you run is `go run ./cmd/tailscale` and the second is `tailscale`. Can you confirm your binary in your PATH is also built at HEAD?

**Comment by bradfitz** [comment]
> One more Q: the first command you run is go run ./cmd/tailscale and the second is tailscale

🤦  I bet that was it. It was a very smokey day yesterday and I wasn't quite thinking straight.

Closing until I see this again.
