### ISSUE TITLE
Update Ubuntu and Debian install instructions

### ISSUE THREAD

**Issue by ananthb** [tailscale/tailscale#2645]
Installation instructions for Debian and Ubuntu systems instruct the user to use apt-key, but it is deprecated. Keys should instead be placed in a location outside of /etc/apt. Somewhere like /usr/local/share/keyrings will work. 

The apt list file for Ubuntu hirsute looks like this

```
# Tailscale packages for ubuntu hirsute
deb https://pkgs.tailscale.com/stable/ubuntu hirsute main
```

If the new key is installed to /usr/local/share/keyrings/tailscale.asc, the list file should be

```
# Tailscale packages for ubuntu hirsute
deb [signed-by=/usr/local/share/keyrings/tailscale.asc] https://pkgs.tailscale.com/stable/ubuntu hirsute main
```

The reason for this change is that putting a keyring in `/etc/apt/trusted.gpg` or under `/etc/apt/trusted.gpg.d` means that the keyring will be trusted for all apt sources and not just tailscale.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1876

I have a partially complete implementation of the updates needed, need to finish the tests.
