### ISSUE TITLE
Android quick settings tile does not work

### ISSUE THREAD

**Issue by ananthb** [tailscale/tailscale#2646]
I'm using tailscale on an Android 10 device. I have a tailscale quick setting tile set up. If the app hasn't been opened for some time, clicking the quick setting tile does not activate the tailscale VPN. The tile itself changes colour but the tailscale connection notification does not show up. The only way to start the connection is to open up the app.

**Comment by DentonGentry** [comment]
A quick settings tile == a widget on the home screen? To my knowledge we don't implement a widget for the Tailscale app. When I long-press on the home screen to add a Widget, Tailscale is not one of the choices.

Could you clarify what that is, and send a screenshot?

**Comment by ignoramous** [comment]
Quick setting tiles are icons in the notification drawer; impl using https://developer.android.com/reference/android/service/quicksettings/package-summary

**Comment by ananthb** [comment]
![Screenshot_20210814-171006](https://user-images.githubusercontent.com/3133350/129445194-55974481-98a5-4f64-b02a-bac6142ee043.png)
The tailscale quick settings icon is in the middle and I haven't pressed it yet. I'd force closed tailscale just before taking this.

![Screenshot_20210814-171017](https://user-images.githubusercontent.com/3133350/129445198-89d2d66f-4d97-417a-b7b5-a0ec3deaa688.png)\
This is after pressing the tailscale button. This is supposed to activate the VPN, but the tailscale notification isn't present and the VPN isn't connected. Although the quick settings icon is lit up.

![Screenshot_20210814-171035](https://user-images.githubusercontent.com/3133350/129445276-b3b87f12-92a0-4e35-afbb-4f78baf41e2a.png)
This is after manually opening tailscale. Once I do this, the quick settings button works as it should. It stops working if tailscale isn't running in the background.

**Comment by zeroZshadow** [comment]
After pressing the tile, it lights up and tailscale prints the following according to logcat
```
12-22 21:32:42.357 26808 26828 I com.tailscale.ipn: 5.8M/90.7M SetPrefs: Prefs{ra=true dns=true want=true exit=niRmoz2CNTRL lan=false host="MyHostName" Persist{lm=, o=, n=[KxnOj] u="myemailhere@domain.com"}}
12-22 21:32:42.358 26808 26828 I com.tailscale.ipn: 5.8M/90.7M transitioning to running; doing Login...
12-22 21:32:42.358 26808 26828 I com.tailscale.ipn: 5.8M/90.7M control: client.Login(false, 0)
12-22 21:32:42.365 26808 26828 I com.tailscale.ipn: 5.8M/90.7M control: setPaused(false)
12-22 21:32:42.367 26808 26828 I com.tailscale.ipn: 5.9M/90.7M control: mapRoutine: unpaused
12-22 21:32:42.367 26808 26828 I com.tailscale.ipn: 5.9M/90.7M Switching ipn state Stopped -> Starting (WantRunning=true, nm=true)
12-22 21:32:42.368 26808 26841 I com.tailscale.ipn: 5.9M/90.7M control: authRoutine: state:authenticated; wantLoggedIn=true
12-22 21:32:42.370 26808 26841 I com.tailscale.ipn: 5.9M/90.7M control: direct.TryLogin(token=false, flags=0)
12-22 21:32:42.390 26808 26841 I com.tailscale.ipn: 5.9M/90.7M control: doLogin(regen=false, hasUrl=false)
12-22 21:32:42.412 26808 26830 I com.tailscale.ipn: 5.9M/90.7M control: mapRoutine: state:authenticating
12-22 21:32:42.431 26808 26828 I com.tailscale.ipn: 5.9M/90.8M control: RegisterReq: onode= node=[KxnOj] fup=false
12-22 21:32:42.473 26808 26834 I com.tailscale.ipn: 5.9M/90.8M control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
12-22 21:32:42.473 26808 26834 I com.tailscale.ipn: 5.9M/90.8M control: No AuthURL
12-22 21:32:42.474 26808 26834 I com.tailscale.ipn: 5.9M/90.8M Switching ipn state Starting -> Running (WantRunning=true, nm=true)
```

But the VPN and it's connection does not seem to start (the key icon does not show).
If I then open the app, directly or by tapping and holding the tile, the vpn instantly starts.

When started, I start seeing the usual logs from wgengine configuring the router and dns and kicking off the whole process.

Please let me know if you want additional logs.

**Comment by zeroZshadow** [comment]
This broken feature is something I run into daily, as the android app does not (yet) allow lan access. So I have to toggle tailscale for everything that require lan access (such as controlling my lights, or NAS)

**Comment by cwilliams5** [comment]
Came here to report this bug, found it already here. +1. No big deal for us technical users, but try explaining this to a non technical user that barely knows their phone.

**Comment by zeroZshadow** [comment]
> We still need to fix this, but FWIW the Android app does have an LAN Access checkbox in the Exit Node menu now.

Sadly the checkbox has not allowed me any LAN access. While that is a different issue, being able to toggle with the quick title would let me work around this in the mean time.

**Comment by CommanderRedYT** [comment]
> We still need to fix this, but FWIW the Android app does have an LAN Access checkbox in the Exit Node menu now.

Offtopic: I don't see anything except "Copy my IP address", "Bug report", "Reauthenticate" and "Logout".

On my Phone (Android 11, Tailscale Android 1.20.2), when I press the button in the toolbar, it connectes to my tailscale network as soon as I open the app. (I believe that this is Androids Sleep function that puts Apps into "power-safe-mode")

Maybe if the app would ask the user to deactivate power-safe-mode for this particular app (and this is the problem), I think it would really enhance the user experience. (Android has a special popup for doing this exact thing, i think it is something with *ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS*)

**Comment by maxenceleduc92** [comment]
Same here, I always need to open the app for the VPN connection to establish.

**Comment by CommanderRedYT** [comment]
What I would find interesting is if everything works if the app continuously display a notification, as this would keep android from putting it into sleep / non priority state. 

Then the question that remains is, why do other apps don't have a notification, but also don't have this problem?

**Comment by nicolabeghin** [comment]
Hi everyone, jumping on the thread some months later. As far as I understand there's no workaround at the moment, even disabling battery optimization does not work, am I correct?

thanks

![Screenshot_20221203-122905.png](https://user-images.githubusercontent.com/2743637/205439441-48dffac5-3b94-4a07-af14-f77b729d1587.png)

![Screenshot_20221203-122914.png](https://user-images.githubusercontent.com/2743637/205439447-33b7b914-5a76-4b32-827e-3361a8cb9b85.png)

![Screenshot_20221203-122928.png](https://user-images.githubusercontent.com/2743637/205439453-45e46862-f20f-4531-9ffa-14155b5ea7c3.png)

**Comment by GertBurger** [comment]
Same experience with me, the workaround I am using atm is long-pressing the tile when this situation occurs.

This opens the tailscale app in the foreground, which completes the VPN activation.

**Comment by nicolabeghin** [comment]
> Same experience with me, the workaround I am using atm is long-pressing the tile when this situation occurs.
> 
> This opens the tailscale app in the foreground, which completes the VPN activation.

good catch! thanks

**Comment by ananthb** [comment]
I think there's some in-memory state that's needed for the VPN connection that is lost when the app becomes "cold". Opening the app seems to load this state and then when it is 'warm", the widget works perfectly.

**Comment by damomato** [comment]
Is there a work around to this problem apart from having to open the app (e.g. long pressing the tile)? Does removing battery optimization or anything like that solve the problem?

**Comment by taha-yassine** [comment]
I have the same problem. Removing battery optimization doesn't solve it.

**Comment by CommanderRedYT** [comment]
I guess one solution could be to display a fixed notification which the user cannot remove/delete. Apps like some SIP clients etc use this so they will never be killed. The problem with battery optimization is that background apps can still get killed if some other app uses too many resources (to free those resources for the current app)

**Comment by ananthb** [comment]
Tailscale does create a persistent notification when the VPN is active. This is required of any Android app that needs to run something in the background. 

The issue is that, cold starts don't work correctly when initiated from the quick settings tile.

**Comment by taha-yassine** [comment]
I think I found a temporary fix for this issue. Go to Settings > Internet & Network > VPN > Tailscale > Turn on Always-on VPN. I'm using a Nothing Phone (1), settings may be different for you. Although it says always on, you can still toggle Tailscale in the quick settings. It's worked perfectly for me so far.

**Comment by CommanderRedYT** [comment]
This is a fix, but sadly Android is too stupid to let me turn off the notification that pops up when I'm not connected (Slider is greyed out)

**Comment by kpcenti** [comment]
I am having this issue also. The app would just toggle on and off in the panel, but nothing ever starts.

**Comment by patriiiiiiiiiick** [comment]
> I think I found a temporary fix for this issue. Go to Settings > Internet & Network > VPN > Tailscale > Turn on Always-on VPN.

Not a fix for me on Android 13, Pixel 6.

**Comment by Mincka** [comment]
Not related to this on my side. It was already disabled for a long time and enabling Tailscale from the tile without launching the application is not working.

**Comment by ilkersigirci** [comment]
The issue has been open for more than 2 years and it still doesn't work. I hope it will be fixed soon

**Comment by Mincka** [comment]
The hard way to workaround this is to use Tasker to react to a custom quick settings tile that sends the intents `com.tailscale.ipn.CONNECT_VPN` and `com.tailscale.ipn.DISCONNECT_VPN`.

The intents to enable / disable the VPN[ are relatively new](https://tailscale.com/changelog/#2023-04-26-client).
I know this works because I use the intents with Tasker to Enable/Disable Tailscale while I am on a specific Wi-Fi network.

The [current code](https://github.com/tailscale/tailscale-android/blob/main/android/src/main/java/com/tailscale/ipn/QuickToggleService.java) does not use these intents and this could be a solution.

**Comment by nicolabeghin** [comment]
> The hard way to workaround this is to use Tasker to react to a custom quick settings tile that sends the intents `com.tailscale.ipn.CONNECT_VPN` and `com.tailscale.ipn.DISCONNECT_VPN`.
> 
> The intents to enable / disable the VPN[ are relatively new](https://tailscale.com/changelog/#2023-04-26-client). I know this works because I use the intents with Tasker to Enable/Disable Tailscale while I am on a specific Wi-Fi network.
> 
> The [current code](https://github.com/tailscale/tailscale-android/blob/main/android/src/main/java/com/tailscale/ipn/QuickToggleService.java) does not use these intents and this could be a solution.

Submitted PR https://github.com/tailscale/tailscale-android/pull/143

**Comment by bradfitz** [comment]
Fixed by https://github.com/tailscale/tailscale-android/pull/143

**Comment by GertBurger** [comment]
This is broken again after the last big release. Quick tile toggling doesn't activate VPN if it hasn't been used in a while.

**Comment by Dale-CDL** [comment]
The same goes for me. When I tap on the tile to connect to my tailnet. It claims I am connected. However, when I open Tailscale from my app drawer, it shows I am disconnected.

**Comment by ananthb** [comment]
I'm using a Pixel 6 now and the tile works perfectly for me. 

With the app force closed, I'm able to connect to my tailnet just by clicking on the tile.

**Comment by GertBurger** [comment]
On a oneplus 10 pro. Forceclose + quick tile works but waiting till the next day doesn't.
Wireguard quicktile and Warp quicktile works as expected.

**Comment by kelivel** [comment]
Hi folks, we don't monitor closed issues so we'll move the conversation over to https://github.com/tailscale/tailscale/issues/12489.
