### ISSUE TITLE
Forced to stop/start every ≈ 24h since moving to Big Sur M1 (now 11.5.2)

### ISSUE THREAD

**Issue by diligiant** [tailscale/tailscale#2647]
I've had a MacBookPro M1 for 3 weeks now. Ever since, I've found it in a strange state every morning (as I digged it's ≈ 24h)
- 2 tailscale'd ssh connection dropped
- Plex web disconnected (not tailscale'd)
- …

Basically, my network stack being a mess. Web browsing works but ssh won't (`kex_exchange_identification: Connection closed by remote host. Connection closed by UNKNOWN port 65535`)

The remedy is simple: I stop/start Tailscale and I'm good.

But that's not good so I'd like to help and report back what you'll ask me to.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3h8lt)

**Comment by DentonGentry** [comment]
Can you tell us either the Tailscale IP address of the Macbook, or the email address the Tailscale account is associated with? You can email it to support@tailscale.com if you're not comfortable pasting it into a public bug.

**Comment by DentonGentry** [comment]
Looking through telemetry, I don't immediately see anything that stands out.

The next time it happens, before stop/start Tailscale could you:
- hold option while clicking on the Tailscale menubar icon
- select Debug > Bug report...

That will print a string, which can be pasted here. That will give us an exact moment in the telemetry to focus on.

Then go ahead and stop/start the Tailscale app.

**Comment by diligiant** [comment]
Frédéric Miserey thinks that’s a great idea.

**Comment by diligiant** [comment]
BUG-a9b9b56d7b0155a826485497c4cf0c94c80998dab4f3805e68c4880f6bda66d3-20210823174116Z-d8a3a13c9553856d

**Comment by diligiant** [comment]
BUG-a9b9b56d7b0155a826485497c4cf0c94c80998dab4f3805e68c4880f6bda66d3-20210829065446Z-eeb6d7f55e28353b

**Comment by diligiant** [comment]
BUG-a9b9b56d7b0155a826485497c4cf0c94c80998dab4f3805e68c4880f6bda66d3-20210901073640Z-ff8fde6bcb95ae95

**Comment by DentonGentry** [comment]
I think this was likely related to Network Extension issues in macOS versions through about 12.4. If similar issues are noted with newer macOS releases than that, please open a new bug
