### ISSUE TITLE
Taildrop: no notification appears after sending file to Android 6

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2660]
Running Android 6.0.1 on a Nexus 7 (2013), attempting to taildrop files from other devices on the Tailnet shows the usual file transfer progress and success checkmark, but no notification appears on the Android 6 device to receive the file.

Using Tailscale 1.13.72.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kdqp)

**Comment by DentonGentry** [comment]
No notification appears using Tailscale 1.12.x either, this is not a regression in 1.13. We did not test 1.12 on an Android 6 device, we only tested Android 12.

We started testing Android 6 because the Pixel 3a running Android 12 is unusable for testing: https://www.androidpolice.com/2021/08/13/vpns-are-completely-broken-in-android-12-beta-4/

**Comment by jucor** [comment]
No notification on Tailscale 1.14.0 on Android 9 either, on Samsung S8  :/ Where can I find the received files, please? They don't appear in the Download folder either.

**Comment by DentonGentry** [comment]
Fixed in 1.16.0, released Oct 8 in the Play Store.
