### ISSUE TITLE
API: 403 forbidden when trying to set device subnet routes

### ISSUE THREAD

**Issue by davidsbond** [tailscale/tailscale#2662]
When making a call to `/api/v2/device/<id>/routes`, I get back a 403 response that states `Forbidden: CSRF token invalid`.

I'm not sure if I need to be providing a CSRF token, since it doesn't occur on any other endpoints. The `Content-Type` for the response is also set to `application/json` despite the response body just being text.

**Comment by bradfitz** [comment]
@davidsbond, I don't see how this can happen. We don't do CSRF token checking for API calls.

Anything HTTP requests with path starting with `/api` go into an API handler code path on our side which doesn't involve any CSRF code.  The CSRF validation is only invoked for non-API stuff.

Can you share some of your client code that's making these requests?

**Comment by davidsbond** [comment]
@bradfitz I just went to the code performing the request and found the issue. 

https://github.com/davidsbond/terraform-provider-tailscale/blob/master/internal/tailscale/client.go#L261

I've accidentally put a whitespace character at the start of the path, which was likely causing it to POST to some other non-api route. Just corrected this and double checked and I'm no longer having the same issue.

Thanks for the quick look, I'll close this :)
