### ISSUE TITLE
control/controlclient: remove defensive tailcfg.Node.Clone?

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#2673]
There's a defensive cloning of all tailcfg.Nodes in controlclient:

https://github.com/tailscale/tailscale/blob/e199e407d22aa18302ac523602ea1ba12953513a/control/controlclient/map.go#L80

resp.Peers does escape off into the ether--it gets put into a netmap that gets passed around all over the place.

However, I don't think anyone is mutating it. And if they were, their changes could get overwritten next time there was a map response. So while this clone is comforting and safe, I think we could do without it.

It accounts for a double-digit percentage of allocation on the client, and is one of the places where it is possible to get rapid memory usage growth on iOS. Being in a large network exacerbates this: The clone is both larger (proportional to number of peers) and more frequent (we clone the entire thing on every single update).

I played with adding a NodeView, but it infects a lot of data structures.

I'm tempted to remove it entirely, at the beginning of a release cycle.

Thoughts?

cc @bradfitz @danderson

**Comment by bradfitz** [comment]
@JulianKnodt was also looking at this in the past few days and I told him to go audit where it was used to see if anybody is writing to it.

If we're not going to do the view thing, we should at least have scary comments on every type and func through which these nodes flow.

**Comment by JulianKnodt** [comment]
I didn't search exhaustively for places where it was used, but the chain of things reading it is quite long and I didn't see anything that modified it at the few ends I looked at. I would also hope that some test could pick up if it was modified, rather than relying on comments, but that's probably too ideal.

**Comment by josharian** [comment]
I added an immutability checker to our toolchain (https://github.com/tailscale/go/pull/19) and applied it here, and it didn't find any writes during tests or regular usage. That's not a guarantee--it can only catch writes that occur, and there could easily be bugs in my tooling--but it's at least a strong hint that the clone is not necessary.

All that said, I think we (probably me) should plan to do the work to add an immutable API and use that, so we can be sure it remains safe.

**Comment by JulianKnodt** [comment]
Maybe as a good intermediate, is there any sort of `CloneOnWrite` pointer in Go? That might be an effective way to ensure that any future writes will not cause any explosions, while avoiding the cost of any current allocations.

**Comment by DentonGentry** [comment]
defensive clone is still there: https://github.com/tailscale/tailscale/blob/741ae9956e674177687062b5499a80db83505076/control/controlclient/map.go#L82

**Comment by DentonGentry** [comment]
I don't expect to do this, barring further comment we'll expect to close this during the next regular bug scrub.
