### ISSUE TITLE
Add the confirmation dialogue on removed of machine from admin console.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2674]
When we remove a machine from the dashboard, there is no confirmation. Thinking it would make sense to add an “Are you sure?” confirmation dialogue for actions that affect a node like this. 

This will help users to avoid deletion of node by mistake and get double confirmation before deleting it.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2842 (which has more discussion)
