### ISSUE TITLE
FR: Support FusionAuth as an identity provider

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2685]
Feature request to add FusionAuth as an identity provider.
FusionAuth has an OIDC front-end available.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3hle9)

**Comment by ebanDev** [comment]
Hey ! That would be amazing :D

**Comment by DentonGentry** [comment]
Since this issue was filed, support for Custom OIDC providers has been added: https://tailscale.com/kb/1240/sso-custom-oidc/

**Comment by catzkorn** [comment]
Closing this issue out as FusionAuth should be supported by our Custom OIDC feature.
