### ISSUE TITLE
Allow sharing the Exit Node in Tailscale.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2691]
This is the feature request for allow to share the exitnode over node sharing functionality.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ho7l)

**Comment by grantwwu** [comment]
This is the last piece of the puzzle, I think, for being able to use Tailscale as a VPN server for friends and family. (Being able to use the Wireguard kernel modules would be a great performance improvement, but not strictly necessary.)

The current workaround I'm considering is to run `tailscaled` in a container with ipvlan networking.

**Comment by mayakacz** [comment]
This shipped last week: https://tailscale.com/changelog/#2022-03-04-service
