### ISSUE TITLE
Unoptimized cryptographic routines for ARM32 impact Raspberry Pi CPU usage

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#2696]
I use tailscale on my 3D printer rpi (3B+), and streaming a modest amount of data (mjpeg stream from the printer, about 10-13Mbps) makes tailscaled eat a lot of CPU. I was at 70% CPU according to top (i.e. 0.7/4 cores).

First issue I figured out is that raspbian only distributes 32-bit images by default, forcing the CPU to run in ARMv7 emulation mode, meaning we lose all the nice optimized x/crypto implementations
[pprof.tailscaled.samples.cpu.003.pb.gz](https://github.com/tailscale/tailscale/files/7029405/pprof.tailscaled.samples.cpu.003.pb.gz) shows significant boxes for both ChaCha20 and Poly1305. Having an armhf asm implementation for ChaCha20Poly1305 in x/crypto would help significantly.

Switching to a 64-bit beta image of raspbian dropped the CPU to 30-40% (0.3-0.4/4 cores [pprof.tailscaled.samples.cpu.004.pb.gz](https://github.com/tailscale/tailscale/files/7029404/pprof.tailscaled.samples.cpu.004.pb.gz) shows red boxes for syscalls on UDP send, tun write, and the runtime finding runnable goroutines. It's unclear to me how that translates to 40% CPU, the profile seems to say we're doing basically nothing.

cc @bradfitz @josharian if there's anything that jumps out, or that you'd like me to try. The pi in question is hooked to a remote controlled hot glue gun, so I can't safely share it, but happy to experiment.

**Comment by Chaphasilor** [comment]
I'm having a similar problem on a Raspberry Pi 4 (4 GB). `tailscaled` is jumping up and down between 40% and 300% CPU usage after running for ~36h.

Disconnecting and reconnecting it with `tailscale down` and `tailscale up` brought the usage down to 3%, but immediately starts slowly ramping up again, reaching up to 17% again after just a few minutes.

I also disconnected all my other machines from my tailnet before reconnecting, so there shouldn't be any traffic between devices running through tailscale.

I'm running tailscale v1.12.3

**Comment by bradfitz** [comment]
@Chaphasilor, that doesn't sound like the same issue. This issue is about 32-bit ARM builds (as used by most people's Raspberry Pis) not having optimized crypto routines. Sounds like you're hitting something where there's traffic or CPU even when it should be idle.

**Comment by Chaphasilor** [comment]
@bradfitz yeah I thought about opening a separate issue, but I only noticed the behavior today and there *was* traffic when I had the high CPU usage. If this keeps happening even when disconnected, I'll create a new issue for it; I simply can't tell for sure yet :)

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/7053 has several possible paths forward, will close this one in favor of that one.
