### ISSUE TITLE
tailscale stops working after wake up from sleep on Windows 10

### ISSUE THREAD

**Issue by vanc** [tailscale/tailscale#2698]
I'm running the latest stable version 1.12.3. Started experiencing the issue a couple of days ago.

So basically, after the PC wakes up from sleep, traffic couldn't go through the tunnel. From other peers, the PC wasn't connected.

If I restart the app, the menu bar will have a message "Please restart the Tailscale Windows Service". But if check the tailscale Windows service via the "Service" app, it's actually running. If check the process list from task manager, the process tailscald is right there.

![image](https://user-images.githubusercontent.com/588742/130476929-5c6cf755-2b0b-40de-bb8c-818503aab440.png)

![image](https://user-images.githubusercontent.com/588742/130477079-0fb2eec6-84ff-48cc-bfe2-d555adfc9f69.png)

My Windows version is 21H1 (OS Build 19043.1165). On Aug 15, [KB5005033 ](https://support.microsoft.com/en-us/topic/august-10-2021-kb5005033-os-builds-19041-1165-19042-1165-and-19043-1165-b4c77d08-435a-4833-b9f7-e092372079a4) was installed. I suspect the issue was related this update.

I also tried install/reinstall the tailscale app when issue happened, with the same issue. The only solution is to reboot the PC. But that's apparently very inconvenient as I need to restore all kinds of VMs and my dev environments.

Please let me know if any other information is needed.

**Comment by bradfitz** [comment]
What's your Tailscale IP?

**Comment by vanc** [comment]
> What's your Tailscale IP?

For the problemic Windows instance, it was 100.88.64.72.

**Comment by bradfitz** [comment]
@vanc, your logs were never uploaded with that bug report.

Can you email support at tailscale.com with your logs from C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs?  (and reference this github bug in your email)

**Comment by DentonGentry** [comment]
No recent reports and cannot reproduce.
return -ETIMEDOUT;
