### ISSUE TITLE
tailscale up should block until tailscaled is ready

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#2708]
In our guides for running Tailscale on serverless environments, we often use a block like this:

```sh
/app/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &
until /app/tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname=fly-app
do
    sleep 0.1
done
```

We do this because we need to wait for tailscaled to spin up and be ready before we pass control on to the next commands. 

We should change the default behavior of `tailscale up` to block until `tailscaled` is ready. It seems like it should have a negligible effect on the CLI experience in most cases, and would make scripting much easier.

Crawshaw warns that there are tricky edge cases and we'll need to more accurately define what "ready" looks like.

**Comment by bradfitz** [comment]
@DentonGentry and I were discussing this earlier in https://github.com/tailscale/tailscale-www/pull/291#pullrequestreview-730066992

**Comment by bradfitz** [comment]
> We should change the default behavior of tailscale up to block until tailscaled is ready. It seems like it should have a negligible effect on the CLI experience in most cases, and would make scripting much easier.

Or we do the thing that's been discussed elsewhere and not require such cases to even use two binaries. Let's remove `cmd/tailscale` from the picture entirely and just teach `cmd/tailscaled` to come up fully on its own.

**Comment by rosszurowski** [comment]
Will this make it into the next point release or minor release (1.14.1 vs. 1.16)? Once we have decent uptake of a new client that supports it, I'll revise our guides to remove the `until` checks.

**Comment by bradfitz** [comment]
> Will this make it into the next point release or minor release (1.14.1 vs. 1.16)? Once we have decent uptake of a new client that supports it, I'll revise our guides to remove the until checks.

Added to today's eng meeting agenda to decide.
