### ISSUE TITLE
Cannot access hello.ipn.dev without flapping tailscaled

### ISSUE THREAD

**Issue by danobi** [tailscale/tailscale#2713]
After installing tailscale on 2/3 of my computers (fedora and arch linux), I cannot access hello.ipn.dev without first `sudo tailscale down && sudo tailscale up`. Then I can access hello.ipn.dev. On my third computer everything worked out of the box (arch linux).

**Comment by DentonGentry** [comment]
I think this was resolved by a round of work on hello.ts.net mid 2022, automating its certificate renewal and other items.
