### ISSUE TITLE
DERP relay selection

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2726]
Hi there,

When doing the netcheck, I found that if the tailscale is connected with an exitnode, it does the ping check THROUGH the exit node?

This means if the exit node is miles away, it would use the further away one as opposed to the closer one to the client. The point of the DERP is to break through NAT, why would you use the further away one?

I'm not sure if it's a bug, but if it is, I would recommend changing so that it picks the DERP relay based on the latency found WITHOUT an exit node.

**Comment by bradfitz** [comment]
It actually doesn't. When netcheck is running from within tailscaled, it uses net/netns and the existing socket(s) that are open and uses the underlying network. When using netcheck via the CLI, that's not (currently) making an RPC to the tailscaled daemon to ask for it to do a netcheck; it's instead doing a netcheck from outside the network namespace (using the host's default routes).

We've slowly been moving more of the Tailscale CLI commands into tailscaled, invokved via an RPC, primarily to reduce code duplication between the two binaries. But this will also have the side effect of making this less confusing later.

For now you can see your netcheck info from the Tailscale admin panel, or looking at local tailscaled logs.
