### ISSUE TITLE
tailscale.com/util/deephash fail on armhf & armv7

### ISSUE THREAD

**Issue by panekj** [tailscale/tailscale#2727]
https://github.com/tailscale/tailscale/tree/release-branch/1.14, https://github.com/tailscale/tailscale/tree/v1.14.0 and https://github.com/tailscale/tailscale/tree/main all fail on `armhf` & `armv7` mostly on `TestArrayAllocs`
tested on Raspberry Pi 3B+ Raspbian 11 (bullseye) & Alpine in Docker + qemu
with Go 1.16.7 & 1.17
```
pi@bengal ~/tailscale (main)> ~/sdk/go1.17/bin/go test tailscale.com/util/deephash
--- FAIL: TestArrayAllocs (0.01s)
    deephash_test.go:343: allocs = 2; want 0
FAIL
FAIL    tailscale.com/util/deephash     1.004s
FAIL
```
additionally `tailscale.com/tstime/rate` randomly fails
```
--- FAIL: TestLongRunningQPS (5.04s)
    rate_test.go:205: numOK = 599, want 602 (ideal 603.006834)
FAIL
FAIL	tailscale.com/tstime/rate	8.104s
```
additional logs
https://gitlab.alpinelinux.org/panekj/aports/-/jobs/472227
https://gitlab.alpinelinux.org/panekj/aports/-/jobs/472226

**Comment by bradfitz** [comment]
@dsnet, you want to look at this?

**Comment by dsnet** [comment]
Able to reproduce on `GOARCH=arm`, but not on `GOARCH=arm64`:
```
$ GOARCH=arm go test -c && qemu-arm deephash.test 
--- FAIL: TestArrayAllocs (0.01s)
    deephash_test.go:343: allocs = 2; want 0
FAIL

$ GOARCH=arm64 go test -c && qemu-aarch64 deephash.test 
PASS
```
