### ISSUE TITLE
Raspberry Pi "CreateTUN: no such device"

### ISSUE THREAD

**Issue by CJKohler** [tailscale/tailscale#273]
I followed directions from: https://tailscale.com/kb/1043/install-raspbian-buster

When I did "sudo tailscale up", I got the following error:

> pi@xhostnamex:~ $ sudo tailscale up
2020/04/08 23:51:14 logpolicy.Read /root/.cache/Tailscale/tailscale.log.conf: open /root/.cache/Tailscale/tailscale.log.conf: no such file or directory
logtail started
Program starting: v0.97-45-g02c73501: []string{"tailscale", "up"}
LogID: f27d855f482af59334f580e454b000f5eee50e43154101ee713be103a552xxxx
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

When I do:
`lsmod | grep tun`
it returns nothing.

Looking at the logs I see:

> pi@xhostnamex:~ $ journalctl -u tailscaled --since="1 hour ago"
-- Logs begin at Sat 2020-01-18 11:35:01 GMT, end at Thu 2020-04-09 00:03:29 BST. --
Apr 08 23:51:04 xhostnamex systemd[1]: Started Tailscale node agent.
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 logpolicy.Read tailscaled.log.conf: open tailscaled.log.conf: no such file or directory
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 logtail started
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 Program starting: v0.97-45-g02c73501: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--soc
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 LogID: 2e6c57bd22a7715b1b8738c3c5f141d9a966e187f4bf7ad437407ee02edexxxx
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 18.8M/29.0M Starting userspace wireguard engine.
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 14.8M/29.3M external packet routing via --tun=tailscale0 enabled
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 14.9M/29.3M CreateTUN: no such device
Apr 08 23:51:04 xhostnamex tailscaled[13188]: 2020/04/08 23:51:04 wgengine.New: no such device
Apr 08 23:51:04 xhostnamex systemd[1]: tailscaled.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 23:51:04 xhostnamex systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Apr 08 23:51:04 xhostnamex systemd[1]: tailscaled.service: Service RestartSec=100ms expired, scheduling restart.
Apr 08 23:51:04 xhostnamex systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 1.
Apr 08 23:51:04 xhostnamex systemd[1]: Stopped Tailscale node agent.
Apr 08 23:51:04 xhostnamex systemd[1]: Started Tailscale node agent.
Apr 08 23:51:04 xhostnamex tailscaled[13202]: 2020/04/08 23:51:04 logtail started

I don't have a firewall running. Rasbian version: 4.19.66-v7l+ #1253

What do I have to do to get TUN working?

Thanks

**Comment by bradfitz** [comment]
Here's what I see on my Raspberry Pi:

```
pi@piosk:~ $ lsb_release  -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@piosk:~ $ lsmod  | grep tun
tun                    45056  2
pi@piosk:~ $ uname -a
Linux piosk 4.19.102-v7l+ #1295 SMP Thu Feb 6 15:49:36 GMT 2020 armv7l GNU/Linux
pi@piosk:~ $ dpkg -S tun  | grep tun.ko
raspberrypi-kernel: /lib/modules/4.19.97-v7+/kernel/drivers/net/tun.ko
raspberrypi-kernel: /lib/modules/4.19.97+/kernel/drivers/net/tun.ko
raspberrypi-kernel: /lib/modules/4.19.97-v8+/kernel/drivers/net/tun.ko
raspberrypi-kernel: /lib/modules/4.19.97-v7l+/kernel/drivers/net/tun.ko
pi@piosk:~ $ ls -l /dev/net/tun
crw-rw-rw- 1 root root 10, 200 Apr  4 15:17 /dev/net/tun
```

How's your differ?

**Comment by CJKohler** [comment]
Very similar, except I didn't get anything back from 'lsmod | grep tun'.
I rebooted (hadn't rebooted the pi in 160 days), and now it is working.

**Comment by danderson** [comment]
Sounds like a new kernel got installed during those 160 days, and with it a new set of modules. Debian (and most linux distros) get terribly confused about module loading in this state, until they're rebooted and the running kernel is consistent with what the package manager thinks is the latest kernel.

Not sure how to detect this, but it seems more prevalent on rpis than other systems. I wonder if Raspbian comes with unattended upgrades enabled out of the box?

**Comment by bradfitz** [comment]
Nice theory! That should actually be easy to detect.

**Comment by CJKohler** [comment]
It probably wasn't an 'unattended upgrade' in my case.
I regularly run:
```
sudo apt-get -o Acquire::ForceIPv4=true update
sudo apt-get -o Acquire::ForceIPv4=true -y dist-upgrade
```
Thanks @danderson for pointing out the module loading issue with not rebooting.

**Comment by CJKohler** [comment]
I have some other pi's that haven't been rebooted for a while, if you want me to test your fix
