### ISSUE TITLE
cmd/tailscale: logout subcommand

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#274]
Keep machine key, remove node key and provider/loginname.

**Comment by JayDoubleu** [comment]
I have re-logged by removing node from admin console and ran tailscale up. This allowed me to login as different user. However, tailscale logs still show old username in live log.

**Comment by apenwarr** [comment]
We should also bring back relaynode's --always-refresh option, which forces an interactive login to refresh the key, even if it isn't expired yet.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/1673
