### ISSUE TITLE
Tailscale Userspace Networking Cannot use Exit node?

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2740]
Hi there,

I just created a docker, and installed tailscaled with userspace networking mode, then used tailscale up.

I assigned the exit node, and its not showing the right IP address? E.g. it's not going through the exit node.

Thanks!

**Comment by bradfitz** [comment]
I think https://forum.tailscale.com/ might be a better venue for discussion.

We try to reserve the GitHub issue tracker for concrete bugs with details.

There are no details here from which to debug.

**Comment by vysecurity** [comment]
```ip addr```

Also shows no tailscale interface for some reason.

**Comment by bradfitz** [comment]
In userspace networking mode the kernel isn't involved and there is no tailscale interface. You need to use the SOCKS5 proxy to dial out.

See https://tailscale.com/kb/1112/userspace-networking/
