### ISSUE TITLE
windows: support "server mode" (headless, without GUI session active)

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#275]
A popular feature request we keep getting recently is for the Windows client to support running as an always-running service, even if nobody's logged in.

We'd need to figure out what that means in terms of ownership on a multi-user machine. And when/how to reauth for key expirations.

/cc @apenwarr

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2a9u9)

**Comment by bradfitz** [comment]
One workaround we imagine might work is running the open source tailscaled on Windows instead of the GUI. We haven't tried that yet, but it'd probably work.

**Comment by bradfitz** [comment]
(A user reportedly got it working yesterday using tailscaled.)

**Comment by bradfitz** [comment]
New plan as of today: we're going to make the Tailscale CLI be the way you configure this on Windows and not add any GUI. Then the CLI will let you add ACL tags (https://tailscale.com/kb/1068/acl-tags) too, so the user isn't effectively running as the admin who logged it in.

The Tailscale CLI will ship in 0.100.0-107 (https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-0.100.0-107.exe) but not in its final form. I'll update this bug when a build is available for testing.

For now you can run the open source tailscaled which runs on Windows but you'll have to create the service entry yourself.

**Comment by jspraul** [comment]
> For now you can run the open source tailscaled which runs on Windows but you'll have to create the service entry yourself.

Can anyone point me to the documentation on how to do this? I can't recommend Tailscale to my company until this works smoothly.

**Comment by bradfitz** [comment]
> Can anyone point me to the documentation on how to do this? I can't recommend Tailscale to my company until this works smoothly.

You're not alone. This is one of our top requests lately and we're working on it.

There are no docs; it'll be faster for us to finish this feature than it would be to document & help debug convoluted manual workarounds. :)

**Comment by bradfitz** [comment]
As an update: I made a bunch of progress on this last week. Not done yet, but much closer.

**Comment by bradfitz** [comment]
I just uploaded version 1.1.535 with support for "Server mode" on Windows:

https://pkgs.tailscale.com/unstable/#windows

Please try it out and let me know any bugs or confusion encountered along the way!

**Comment by chrisbrownie** [comment]
Installed on two machines and it works a treat. Really glad to see this feature coming!

**Comment by apenwarr** [comment]
it works!

**Comment by chrisbrownie** [comment]
@bradfitz I'm finding since enabling this on one machine that it seems to just...stop from time to time. System tray icon is still there, app still seems to be running, but cannot receive connections over Tailscale.

Restarting the application in the tray doesn't fix it, but the first time it broke I logged out and back in, that fixed it.

Is this issue still appropriate or should I raise a new one? Can I grab you some logs? I've left a machine in this broken state in the hope it helps to troubleshoot.

**Comment by bradfitz** [comment]
@chrisbrownie, I have no way to map from your GitHub username to your account to look at things.

Why don't you email support@ with details?

**Comment by ceebee108** [comment]
Have a some machines running with this now, seems to work.
When will this go into stable release?

**Comment by apenwarr** [comment]
Stable release is imminent. We're just fixing the last few bugs.

On Thu, Oct 29, 2020 at 6:02 AM ceebee108 <notifications@github.com> wrote:
>
> Have a some machines running with this now, seems to work.
> When will this go into stable release?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by chrisbrownie** [comment]
> @chrisbrownie, I have no way to map from your GitHub username to your account to look at things.
> 
> Why don't you email support@ with details?

Apologies -- I was waiting a few days to see if it would break again, and it hasn't. Will be in touch if things get weird again.
