### ISSUE TITLE
derp: handle duplicate derp connections better

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2751]
Overall tracking bug for handling DERP dup connections better.

See #2745 for background.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/2745 merged some time ago and has been deployed to all derpers.
https://github.com/tailscale/tailscale/issues/2746 tracks making the derper send an unhealthy status to the client.

I'm not clear if there is more that we might do here. Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/2745
