### ISSUE TITLE
Samsung's Voicemail app doesn't work when Tailscale is connected

### ISSUE THREAD

**Issue by dstaley** [tailscale/tailscale#2761]
Okay I'll be honest: this is a really strange one.

When Tailscale is connected, the Voicemail app on my unlocked Samsung Galaxy S21 connected to Verizon stops working, throwing up the error "Something went wrong. Sorry, we ran into a problem. Please try again later. If there is still a problem, please contact Customer Service." This also means that notifications for new voicemails do not work.

Once Tailscale is disconnected, notifications come through, and the Voicemail app can download and play new messages.

I'm unsure if this is a fault of Tailscale, Samsung, Android, or Verizon. Therefore, I don't exactly expect a response/resolution from Tailscale; I'm mostly posting this so that if someone else searches the error message, they stumble upon this. However, if there is something I could try to track down the exact cause, I'm more than willing to help!

**Comment by bradfitz** [comment]
We broke voicemail!? That sounds like a _Feature_!

Are you using exit nodes?

In somewhat maybe related #2322, @DentonGentry guessed it might be MTU related.

**Comment by dstaley** [comment]
> Are you using exit nodes?

Nope! I don't think I have any non-default Tailscale features in use.

**Comment by DentonGentry** [comment]
A factor in some cases like this has been MTU size: the tailscale MTU is 1280 bytes, versus a typical 1500 bytes for Wi-Fi or LTE. A protocol which deliberately sets the DontFragment bit but sends > 1280 bytes won't be able to make it through the tunnel.

**Comment by DentonGentry** [comment]
Since this was filed, we've added a bugreport selection in the Android app. If someone produces the issue with the Samsung Voicemail app not working with Tailscale connected, please generate a bugreport to paste here.

**Comment by dstaley** [comment]
Here you go! This was via a manual refresh of the Voicemail app, which resulted in an error. _Usually_ the error I run into is immediately after someone leaves a voicemail, so if this bug report doesn't have anything useful I'll give that a shot and report that as well.

```
BUG-d58a8424fd1832f543f44ab24e45513e3de46a6abdb8d8050dd2daac1e206da9-20221030181046Z-445d5f87e7ab0124
```

**Comment by markrousseau** [comment]
Visual voice mail on samsung and tailscale enabled seems to block 
BUG-72437838277065bf6619a4306a72a4df8a71d6516ec44c8cd6d836beb8c556af-20230128141536Z-e50c130536ddd711

**Comment by DentonGentry** [comment]
The main thing I notice near the bug line from @markrousseau is use of DNS-over-TLS:
```
2023-01-28 21:50:16.581764267 +0000 UTC: 25.6M/139.5M Accept: TCP{100.109.67.204:39412 > 100.100.100.100:853} 60 ok out
2023-01-28 21:50:18.596353225 +0000 UTC: 25.7M/139.7M Accept: TCP{100.109.67.204:39412 > 100.100.100.100:853} 60 ok out
```

port 853 is DNS-over-TLS. If set to "On" the Android device requires the DNS server to support DNS-over-TLS and present a valid certificate, which we don't currently have a way to support: https://github.com/tailscale/tailscale/issues/915

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/915

**Comment by Jason-Coyne** [comment]
@DentonGentry  I am having this issue currently, so it may have resurrected.

**Comment by almighty-loaf** [comment]
FYI this problem still persists, though it can be worked around by going to _Settings > App split tunneling_ and checking the box next to Voicemail (com.samsung.vvm).

I expect most people would not need to access voicemail through Tailscale anyway.
