### ISSUE TITLE
derp: listen on server host for port 80 and stun port 3478

### ISSUE THREAD

**Issue by chuangbo** [tailscale/tailscale#2767]
When using custom derp on the server with multiple IP addresses, we would like to bind derp 80, 443 and stun 3478 to a certain IP.

```sh
$ derper --hostname your-hostname.com -a 10.240.240.10:443
2021/09/01 13:37:24 no config path specified; using /var/lib/derper/derper.key
2021/09/01 13:37:24 derper: serving on 10.240.240.10:443 with TLS
2021/09/01 13:37:24 listen tcp :80: bind: address already in use
```

Luckily derp command provides flag `-a` to customize which address to bind for port 443. But port `:80` and `:3478` are hard-coded at the moment.

https://github.com/tailscale/tailscale/blob/7a7aa8f2b0887761ef51d66634b1f3bf730c71be/cmd/derper/derper.go#L227-L231

https://github.com/tailscale/tailscale/blob/7a7aa8f2b0887761ef51d66634b1f3bf730c71be/cmd/derper/derper.go#L251-L254

It'd be great if derp command listens to all the ports on the address from flag `-a`.

**Comment by bradfitz** [comment]
The problem with this, as I noted on the #2768 PR, is that it locks you in to either IPv4 or IPv6.

Maybe that's okay, but I'd like to understand the situation here a bit more.

If you're listening on 10.240.240.10, how do you plan to get this server on the internet? Do you have a reference proxy in front of it? How are you getting the TLS cert?

**Comment by bradfitz** [comment]
Also, why do you want to bind to a certain IP? You're describing solutions only, but I'd like to see the problem stated first before we jump to solutions.

Do you have multiple NICs? Or ... ?

**Comment by chuangbo** [comment]
Thank you for the reply. The reason for binding to a certain IP is that we want to use other IPs for other services, such as nginx.

All the IPs on the server appear to be internal IPs, but they are actually mapped to public IPs through something like Elastic Cloud IPs.

If we don't want to lock in either IPv4 or IPv6, we can specify the -a parameter with just the port, like the default :443. What do you think?

**Comment by chuangbo** [comment]
And yes the derp command is still able to get TLS cert automatically.

**Comment by bradfitz** [comment]
Sounds good. If you're using something like Elastic Cloud IPs then I also suppose you can just map public IPv6 to that internal IPv4 too.
