### ISSUE TITLE
iOS: show connection status in machines list

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2771]
User is looking to have status on the iOS Tailscale App (such as device is disconnected since "last seen") so that they do not need to go to admin console to check if device is disconnected since what time.

The idea of showing status is so one can easily see from their respective device (no need to log into admin control panel just to see status.)   Consider a status indication in the apps themselves. 
![image](https://user-images.githubusercontent.com/75628398/131715439-c6360d73-d9c0-4adb-a5bc-1f77027fecf6.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3iqfl)

**Comment by pixelrogue1** [comment]
Connected time not required. 

Show status on all platforms including iOS.

**Comment by bradfitz** [comment]
I'm not sure we want to show the connected time. That's kinda stressful/worrying, like you're accruing billable time or something. 

/cc @rosszurowski

**Comment by pixelrogue1** [comment]
Right - need to know you are connected. 

Anything more it is ok for the user to locate elsewhere in the app/admin pa el or logs. 

>

**Comment by rosszurowski** [comment]
Yes, introducing similar status indicators to the admin panel is something we'd like to achieve at some point! I suspected we'd tackle this as part of a larger change to the iOS UI, but having this issue for it seems good too.

As you two mentioned, connected time probably isn't necessary.

**Comment by DentonGentry** [comment]
Similar admin panel feature request tracked in https://github.com/tailscale/tailscale/issues/698

**Comment by pixelrogue1** [comment]
Yes, however specific only the platform applications such as iOS - not admin panel.

**Comment by DentonGentry** [comment]
Assigning to @sonovawolf regarding iOS UI feature request

**Comment by agottardo** [comment]
Closing as this was implemented in the new iOS redesign.

<img src="https://github.com/tailscale/tailscale/assets/9057073/9fa59c5e-a897-4d34-a210-0f9f46ad9ba8" width="250" />

**Comment by jflattery** [comment]
Has this been published to the AppStore or will this be in a future release?

**Comment by agottardo** [comment]
> Has this been published to the AppStore or will this be in a future release?

It is currently available on [TestFlight](https://testflight.apple.com/join/tLcYLZJV) and will be published on the App Store in a future release.
