### ISSUE TITLE
Add collapse/hide block of  advertised subnet routes in admin console display

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2779]
The user requested to change the display of advertised routes in the machine dashboard to either hide the routes or at least collapse them? He got a couple of nodes we’re using for routing to some pretty large blocks of addresses, and it’s getting really irritating to scroll through the entire list in the machine list on the dashboard.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3iu1d)

**Comment by DentonGentry** [comment]
Subnet routes no longer appear in the admin panel machines list.
