### ISSUE TITLE
fail to revoke access for node sharing

### ISSUE THREAD

**Issue by Kinghack** [tailscale/tailscale#2790]
add external user for sharing;
user accept the invitation and could ping the node;
but admin fail to revoke access from admin portal -> click node -> share machine -> revoke access

Thanks. 

<img width="487" alt="Screen Shot 2021-09-03 at 10 36 36 AM" src="https://user-images.githubusercontent.com/1154775/131942261-3d4e879a-6b9f-4303-891a-28f9399fef4b.png">

**Comment by bradfitz** [comment]
There's not enough information here to help debug.

Why don't you email support at tailscale.com with account details?  (rather than potentially share public stuff here)  I'll close this bug and we can handle it over email.
