### ISSUE TITLE
Restarting the tailscale service on windows resets ControlURL

### ISSUE THREAD

**Issue by nicka101** [tailscale/tailscale#2798]
Restarting the tailscale service (or the system) on Windows causes tailscale to reset the ControlURL (--login-server) to the default value of https://controlplane.tailscale.com.

The behavior can easily be reproduced with the following steps:

1. Run "_tailscale up_" with a custom login server
2. Verify that tailscale nodes respond as expected (optional)
3. Confirm **%LOCALAPPDATA%\prefs.conf** has saved the **ControlURL**
4. Restart the tailscale service or Windows
5. Observe that tailscale is no longer logged in, and **prefs.conf** has saved https://controlplane.tailscale.com as its **ControlURL** again

This is inconsistent with the behavior of tailscaled on Linux, where **ControlURL** persists with the active session.

**Comment by DentonGentry** [comment]
I agree that it is inconsistent. The Windows client was the first one to support an alternate control server. It has registry keys in `HKEY_LOCAL_MACHINE\SOFTWARE\Tailscale IPN`, and creating a string key named `LoginURL` containing the desired URL will be persistent.

**Comment by bradfitz** [comment]
The registry seems unrelated. I don't see why this bug would happen and I'd prefer we just fix it instead of recommending the registry hack for a not understood bug.

**Comment by bradfitz** [comment]
This might be a good starter project, @dblohm7.

**Comment by Bastika07** [comment]
Are there any news to this issue?

**Comment by DentonGentry** [comment]
We'll post updates to the bug; it hasn't been actively worked on recently.
As a workaround, in cmd.exe `tailscale up --login-server=...` can be used to set the login server again.

**Comment by bradfitz** [comment]
I looked into this and think I know what you're hitting.

On Windows, Tailscale runs in client-driven mode by default, where the GUI client delivers the preferences to the tailscaled daemon.

So when the GUI client disconnects, the daemon resets and drops its settings.

If I stop the GUI and then run `tailscale up --login-server=http://10.1.2.3/ --unattended`, I see (via `tailscale debug prefs`) that the settings took server-side. And then I can (as an admin) run `net stop Tailscale` and `net start Tailscale` to restart the `tailscaled.exe` service and run `tailscale debug prefs` again to see that my alternate login server control URL is still there.

But without `--unattended` (which `debug prefs` calls `ForceDaemon`), then it will reset settings when clients disconnect.

The `%LOCALAPPDATA%\prefs.conf ` file is the prefs as seen by the GUI. It looks like the GUI always overrides the on-disk prefs with the control URL from the registry and if the registry is empty, it sets it to `https://controlplane.tailscale.com`. That's too aggressive. That's an easy fix and I'll send that out, but I don't think the problem's in tailscaled.
