### ISSUE TITLE
Question: Key difference between nebula and tailscale

### ISSUE THREAD

**Issue by alinz** [tailscale/tailscale#28]
Hello, 

During the recent months I've seen similar projects (Mesh VPN in particular) are coming up and as you guys probably know,  around November, [nebula](https://github.com/slackhq/nebula) from slack became open sourced which solve the similar problem domain.

So my main question is, What makes tailscale stand out? 

Cheers,

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687416953737) by [Unito](https://www.unito.io/learn-more)

**Comment by apenwarr** [comment]
We recently added this article that might help answer this class of question: https://tailscale.com/kb/1062/reviewer-guide
