### ISSUE TITLE
prevent TS from accepting a valid json but not valid for acl policy

### ISSUE THREAD

**Issue by asdffdsazqqq** [tailscale/tailscale#2807]
hello and thanks,

in my testing, ts will save a policy that is valid json but not valid for ts.
ts will save a set of ACL rules formatted as a set of Hosts

this policy, only the last rule is active
```
    "ACLs": [
      {
         "Action": "accept", "Users": ["en08"], "Ports": ["pi4:8096"],
         "Action": "accept", "Users": ["en08"], "Ports": ["server02:3389"],
         "Action": "accept", "Users": ["en08"], "Ports": ["pi4:22"]
      }
    ]
```

this policy, all rules are active
```
    "ACLs": [
        {"Action": "accept", "Users": ["en08"], "Ports": ["pi4:8096"]},
        {"Action": "accept", "Users": ["en08"], "Ports": ["server02:3389"]},
        {"Action": "accept", "Users": ["en08"], "Ports": ["pi4:22"]}
    ]
```

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3jaq9)

**Comment by asdffdsazqqq** [comment]
@bradfitz,
hi, sorry, not sure what your last post means?
thanks

**Comment by dsnet** [comment]
It means that he would like me to take a look at this :smile:

**Comment by asdffdsazqqq** [comment]
@dsnet, 
if you need a beta tester, let me know...

**Comment by DentonGentry** [comment]
I believe the current status is that HuJSON (which parses the JSON from the ACL tab) has the support to reject an ACL with multiple Action definitions, but the backend of the admin panel is not hooked up to enable it.

**Comment by dsnet** [comment]
I believe this is fixed.

In the original post, this JSON:
```json
    "ACLs": [
      {
         "Action": "accept", "Users": ["en08"], "Ports": ["pi4:8096"],
         "Action": "accept", "Users": ["en08"], "Ports": ["server02:3389"],
         "Action": "accept", "Users": ["en08"], "Ports": ["pi4:22"]
      }
    ]
```
has a JSON object with duplicate names.

I implemented server-side logic to reject inputs that have duplicate names.

**Comment by dsnet** [comment]
Verified as fixed:
![image](https://user-images.githubusercontent.com/6354026/146831370-9ec430c5-a931-4c61-8d11-4a562decaebd.png)

**Comment by asdffdsazqqq** [comment]
did a quick test, seems to be fixed.
