### ISSUE TITLE
API: Cannot delete node using API device-delete.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2811]
User is unable to remove the machine using API;

 https://github.com/tailscale/tailscale/blob/main/api.md#device-delete

{'addresses': ['100.x.x.x', 'fd7a:115c:a1e0:ab12:4843:cd96:626b:4b42'],
'authorized': True,
'blocksIncomingConnections': False,
'clientVersion': '1.12.3-td91ea7286-ge1bbbd90c',
'created': '2021-09-04T15:56:14Z',
'expires': '2022-03-03T15:56:14Z',
'hostname': 'gitnfs',
'id': '71946936529866647',
'isExternal': False,
'keyExpiryDisabled': False,
'lastSeen': '2021-09-04T15:56:16Z',
'machineKey': 'mkey:a41fb07bbd0df28d46abb6de77c568724a96c30407ac22016e14dd6e680b6451',
'name': 'z-sadjfklsadjfiowe-gitnfs-5.ssargent.gmail.com',
'nodeKey': 'nodekey:811bcdc84a857fb52605e7d68c567a22743e0921869778d59096f3c7c2eb4b41',
'os': 'linux',
'updateAvailable': True,
'user': 'xxxxxx@gmail.com'}

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3j80h)

**Comment by soniaappasamy** [comment]
Fix deployed
