### ISSUE TITLE
delete/change a rule, need option to kill open connections

### ISSUE THREAD

**Issue by asdffdsazqqq** [tailscale/tailscale#2816]
hello and thanks,

need option that that when a rule is deleted, an open connection is killed.

current behavior
1. have rule - {"Action": "accept", "Users": ["en08"], "Ports": ["pi4:22"]}
2. have open connection from `en08` to `pi4:22`
3. delete rule
4.the connection stays open

proposed behavior  
1. have rule - {"Action": "accept", "Users": ["en08"], "Ports": ["pi4:22"]}
2. have open connection from `en08` to `pi4:22`
3. delete rule
4.the connection is killed

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/859
