### ISSUE TITLE
Excessive tailscale logging in system log

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#282]
Report from a friend, as well as a couple of users: tailscaled is the single most verbose thing in their system logs, by a very long way. This is a problem for them because they do centralized logs collection, and so extremely verbose tailscaled logs multiplied by many machines depletes the central logstore's disk space at alarming rates.

We've heard this from several quarters, and our general plan for this is "do less stuff, because this will generate less logs". Filing this bug (a) to track that and (b) to decide whether that's enough. Even with things like eager handshaking disabled, we're still likely to log a _lot_ more than the rest of the system combined, because we intend these logs to be debug-level stuff.

Unfortunately we don't use log levels, so it's not a simple matter of "lower the syslog spamminess and only push debug logs into logtail". Unless we add some kind of log levels, our only option is to turn off syslog output entirely.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686582685930) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
FWIW, I submitted https://github.com/tailscale/tailscale/commit/73249f8032c3553a914785f0c76294807a0d4bd3 yesterday which addresses a lot of the log spam.

Turning off automatic handshakes will do a lot too.

But, yes, our log spamminess is one of my pet peeves too.

**Comment by wogong** [comment]
Really hope there is an option to turn off these logs.

**Comment by wogong** [comment]
I open a window in tmux showing real-time logs, `sudo journalctl -f`.
tailscale output too many logs to journal making it meaningless.
I found no option in journalctl to filter out logs of certain service, but you can achieve the same by
`sudo journalctl -f | grep -v 'tailscaled'`

**Comment by lfarkas** [comment]
when this will be released? in the latest 1.4.5 it's still not working ie at least tailscale fill up my journal.

**Comment by lfarkas** [comment]
is this normal? 
why we can't simple disable the whole logging?
```
# ls -al /var/lib/tailscale/
total 30663616
drwxr-x---   2 root root        4096 febr  16 07.17 .
drwxr-xr-x. 78 root root        4096 márc   1 11.07 ..
-rw-r--r--   1 root root  9682715930 márc   5 08.36 tailscaled.log1.txt
-rw-r--r--   1 root root 21716739232 márc   5 08.35 tailscaled.log2.txt
-rw-------   1 root root         209 2020 ápr   19 tailscaled.log.conf
-rw-------   1 root root        1168 febr  16 07.17 tailscaled.state
```

**Comment by luismanson** [comment]
Hello, is this bug active? I have been poking with syslog on a Raspberry Pi and noticed Tailscale logging being too verbose. 
Can we have some form of logging control, please?

**Comment by mich2k** [comment]
I currently face almost 200GB of only tailscaled logs

![image](https://github.com/tailscale/tailscale/assets/13397578/3e377401-86a4-4d06-b917-7be73be2b72a)

**Comment by aadityabhatia** [comment]
My systemd journal is being flooded. No idea how to make it stop besides killing tailscale.

```
Feb 16 01:30:07 lucifer tailscaled[165704]: [unexpected] magicsock: derp-16 does not know about peer [z4HWt], removing route
Feb 16 01:30:09 lucifer tailscaled[165704]: [RATELIMIT] format("dns: resolver: forward: recv: response code indicating server failure: %d") (3 dropped)
Feb 16 01:30:09 lucifer tailscaled[165704]: dns: resolver: forward: recv: response code indicating server failure: 2
Feb 16 01:30:09 lucifer tailscaled[165704]: dns: resolver: forward: recv: response code indicating server failure: 2
```

Firewall is configured to allow NAT-PMP. I am not connected to any machine that requires DERP. This has been appearing every 2-3 seconds for several months now.

Possibly related to #10430?

**Comment by physkets** [comment]
This seems to still be true. The log is filled with messages from `tailscaled`. Could this issue be re-opened?

It would be nice if there were log-levels and if the default maximum was set to Notice or Warning.

**Comment by iluvatyr** [comment]
I agree. My syslog is full of tailscale logs. Would be nice to reduce to only necessary ones.

**Comment by aadityabhatia** [comment]
My workaround is to redirect logs to a temp file.

```
$ cat /etc/systemd/system/tailscaled.service.d/override.conf
[Service]
StandardOutput=file:/tmp/tailscaled.log
```

**Comment by neitsab** [comment]
[Solution offered by Reddit user 2bluesc on r/Tailscale](https://reddit.com/r/Tailscale/comments/vholvd/turn_of_excessive_logging_in_syslog/j52g3no/) for systemd-based systems:

> Use an override drop-in and the symbolic name so you follow the changes by your distro package. This level cut off the noise for me:

```
cat /etc/systemd/system/tailscaled.service.d/override.conf
[Service]
LogLevelMax=notice
systemctl daemon-reload && sudo systemctl restart tailscaled
```

To create the override file, either use `systemctl edit tailscaled` and paste the content shown above, or use this one-liner:

```shell
printf "[Service]\nLogLevelMax=notice\n" | sudo tee -a /etc/systemd/system/tailscaled.service.d/override.conf
```

I confirm it works 👍🏻

**Comment by yellowsink** [comment]
I currently have 2 gigabytes of tailscaled.log, this definitely is still an issue. Maybe add an option for log rotation? I do not need tailscaled logs from *checks notes* well over a year ago, and it would be nice if tailscaled would clear out old logs to make room for new ones automatically.
