### ISSUE TITLE
Removing machine from admin console is failing.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2820]
Failed to remove the machine from the admin console.

![image](https://user-images.githubusercontent.com/75628398/132574385-ef639056-b477-49c3-a128-8cd85b71ccc3.png)

![image](https://user-images.githubusercontent.com/75628398/132574460-1004683d-7f0c-4aa8-9295-948b36adc390.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3jaxd)

**Comment by bradfitz** [comment]
Dup of #2811, no?

**Comment by soniaappasamy** [comment]
Fixed
