### ISSUE TITLE
synology: Add info about coreutils for building on MacOS 

### ISSUE THREAD

**Issue by palmamartin** [tailscale/tailscale#2829]
In reference to https://github.com/tailscale/tailscale-synology/pull/77 what about adding a note to the Readme that `coreutils` is required for building on MacOS?

**Comment by DentonGentry** [comment]
Would you like to send a pull-request to https://github.com/tailscale/tailscale-synology ?

**Comment by palmamartin** [comment]
Sure. Just send a PR.
