### ISSUE TITLE
Android: show key expiration date and status in devices list

### ISSUE THREAD

**Issue by pdecat** [tailscale/tailscale#2830]
It would be awesome if the Android app could display each device's key expiry status in the devices list, like it is done in the admin UI.

Ability to extend an expired key from Android app would be nice too.

**Comment by bradfitz** [comment]
@pdecat, note that the web admin UI is for admins. The client apps (Windows, macOS, Android, iOS) are for end users.

For many individual users, those are the same thing (the one user is both an admin and a user). But for corporate users, most users are not admins.

**Comment by DentonGentry** [comment]
I don't expect we would implement this as described. We're more likely to focus on the admin panel rendering on mobile form factor screens.
