### ISSUE TITLE
Packets not getting routed on fly.io

### ISSUE THREAD

**Issue by FiloSottile** [tailscale/tailscale#2833]
I am running tailscale on fly.io, and everything seems to work, except packets from the system don't get routed.

Magic DNS is enabled, and requests for regular domains to 100.100.100.100 work perfectly. However, when any packet is sent for a Tailscale IP, it doesn't make it to the other side. Running tcpdump on the Tailscale interface on the remote node doesn't show the packets arriving. Still, `tailscale ping` works.

```
/ # tailscale bugreport
BUG-46be1ac89f33dbadabf3a760d9b50e5da353af1ffd4dc0cd0aabc693214d540d-20210911125208Z-59e524f08f91c546
/ # tailscale ping damogran
pong from damogran (100.114.190.103) via DERP(lhr) in 84ms
pong from damogran (100.114.190.103) via DERP(lhr) in 83ms
pong from damogran (100.114.190.103) via DERP(lhr) in 83ms
pong from damogran (100.114.190.103) via DERP(lhr) in 82ms
pong from damogran (100.114.190.103) via DERP(lhr) in 83ms
pong from damogran (100.114.190.103) via DERP(lhr) in 83ms
pong from damogran (100.114.190.103) via DERP(lhr) in 82ms
pong from damogran (100.114.190.103) via DERP(lhr) in 82ms
pong from damogran (100.114.190.103) via DERP(lhr) in 83ms
pong from damogran (100.114.190.103) via DERP(lhr) in 81ms
direct connection not established
/ # ping damogran
PING damogran (100.114.190.103): 56 data bytes
^C
--- damogran ping statistics ---
32 packets transmitted, 0 packets received, 100% packet loss
/ # ip route get 100.114.190.103
100.114.190.103 dev tailscale0  src 172.19.0.250
/ # iptables -nvL
Chain INPUT (policy ACCEPT 2736 packets, 246K bytes)
 pkts bytes target     prot opt in     out     source               destination
 2738  246K ts-input   all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ts-forward  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 8292 packets, 906K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain ts-forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  tailscale0 *       0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x40000
    0     0 DROP       all  --  *      tailscale0  100.64.0.0/10        0.0.0.0/0
    0     0 ACCEPT     all  --  *      tailscale0  0.0.0.0/0            0.0.0.0/0

Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  !tailscale0 *       100.115.92.0/23      0.0.0.0/0
    0     0 DROP       all  --  !tailscale0 *       100.64.0.0/10        0.0.0.0/0
```

**Comment by DentonGentry** [comment]
It looks like the node which reported `BUG-46be1ac89f33dbadabf3a760d9b50e5da353af1ffd4dc0cd0aabc693214d540d-20210911125208Z-59e524f08f91c546` was authenticated using an [ephemeral authkey](https://tailscale.com/kb/1111/ephemeral-nodes/) which means it only has an IPv6 address. It would be able to contact the IPv6 address of other Tailscale nodes, which can be looked up:
- using `tailscale ip -6 name`
- In the admin panel hover over the IPv4 address, and there will be a button to copy the IPv6 address to the clipboard

<img width="372" alt="Screen Shot 2021-09-11 at 6 38 57 AM" src="https://user-images.githubusercontent.com/1140756/132949823-b8b148af-821f-429e-8326-d8367e2bd5cf.png">


(*) ephemeral authkeys are convenient for container workloads, but need to handle cases where containers are created and destroyed at a very high rate which would burn through a sizable fraction of the more limited IPv4 pool.

**Comment by FiloSottile** [comment]
Ah, that makes sense. However, does that mean ephemeral nodes just don’t work with IPv4 subnet routes?

I could add IPv6 addresses to that subnet, make the services bind to v6 too, and add the v6 addresses to the client application, but it kind of defeats the simplicity of just exposing things over Tailscale.

By the way, it would have helped debug if tailscaled didn’t add routes for the IPv4 addresses it was not willing to route.

**Comment by DentonGentry** [comment]
Bug scrub
