### ISSUE TITLE
Support Gitlab as an identity provider

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2839]
The user is requesting GitLab as identifier support.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3jpg1)

**Comment by bradfitz** [comment]
https://docs.gitlab.com/ee/integration/openid_connect_provider.html

**Comment by DentonGentry** [comment]
To set expectations: supporting self-hosted GitLab instances as an authentication provider for the public Tailscale service would open several questions regarding how to support the product, for example:
1. If a user cannot log in and contacts Tailscale support... what do we do? Working with public authentication services like GitLab SaaS at least keeps the responsibility clear, Tailscale is responsible for working out any difficulty with GitLab SaaS.
1. One can see the potential of accidental circular dependency, that the self-hosted GitLab somehow adds a use of Tailscale which in turn has a dependency on the self-hosted GitLab. Things might work until a key expires or something else fails, then be completely intractable.

It is more straightforward to consider support for the Gitab SaaS.

**Comment by jtdressel** [comment]
> To set expectations: supporting self-hosted GitLab instances as an authentication provider for the public Tailscale service would open several questions regarding how to support the product, for example:
> 
>     1. If a user cannot log in and contacts Tailscale support... what do we do? Working with public authentication services like GitLab SaaS at least keeps the responsibility clear, Tailscale is responsible for working out any difficulty with GitLab SaaS.
> 
>     2. One can see the potential of accidental circular dependency, that the self-hosted GitLab somehow adds a use of Tailscale which in turn has a dependency on the self-hosted GitLab. Things might work until a key expires or something else fails, then be completely intractable.
> 
> 
> It is more straightforward to consider support for the Gitab SaaS.

"Just" supporting Gitlab SaaS would be amazing. I'm interested in having the ability to log-in with gitlab for a few reasons.

- GitLab is free and easy to sign up for
- GitLab is benign. I don't know of anyone who would object to using GitLab as an identity provider. (I'm sure such people exist. I think there are more people who would object to Facebook / Twitter)
- I don't want to use GitHub. The permission screen for adding GitHub as a provider looked scary and required thought. (I don't understand the ramifications of granting "Organization access" to Tailscale.)
- I refuse to use google accounts. I've seen too many stories of google locking people's accounts without recourse. I don't want to give google the ability to deny me access to my network. 
- Microsoft account management seems wonky. I think I have had a few accounts fused together, which can behave strangely.

**Comment by DentonGentry** [comment]
I promise that if progress is made on this, we'll update the bug. It is a good idea but is not currently at the top of the list of things to put engineering time into.

**Comment by catzkorn** [comment]
Closing this issue - using GitLab as an identity provider is now supported via [custom OIDC](https://tailscale.com/kb/1240/sso-custom-oidc/)
