### ISSUE TITLE
admin panel: verify machine removal

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#2842]
A few times now I accidentally clicked "Remove" instead of "Disable key expiry", which correctly results in my machine being deleted. Given that "Remove" is a relatively destructive action, perhaps we should have a pop-up window confirming the action?

@rosszurowski @sonovawolf

**Comment by mayakacz** [comment]
This makes sense to me.
An alternative (but less preferred to me) would be to only show this for machines belonging to another user, or for multiple machines at once, etc. - reason I dislike it is it woudn't be consistent.

**Comment by dsnet** [comment]
As a data point: the ones I accidentally deleted were my own :) oops

**Comment by rosszurowski** [comment]
Ideally we'd provide some kind of undo mechanism which makes it less arduous if you have to delete many machines. But a confirmation is a good first step towards something like that.

**Comment by sonovawolf** [comment]
+1 to what Ross said. Ideally we wouldn't require another step and just be able to undo. An "easy" way to undo is to keep the request somewhere for a few seconds, just long enough for a toast with an "undo" option to disappear. I don't know how easy that would be with the current infrastructure?

**Comment by dsnet** [comment]
If we want to support undo, then this seems like an operation that should be supported by the API. In a sense, deletion would be equivalent to something like "suspend the machine; if the machine stays suspended for N period of time, then delete it permanently".

**Comment by sonovawolf** [comment]
I think we are talking more about being able to "undo my last click" than "undo deletion". Purely because humans are fallible and error-prone, _not_ because we need a suspension workflow.

**Comment by dsnet** [comment]
Would this be a front-end only thing? or is there state being changed in the back-end?

(assuming front-end only) If the delay is too long, then we have a situation where I delete a machine on my laptop, switch over to my desktop, and I still see the machine as present.

(assuming the back-end is involved), then the complexity of this just got much more complicated as you need to persist state across sessions.

**Comment by josharian** [comment]
> (assuming front-end only) If the delay is too long, then we have a situation where I delete a machine on my laptop, switch over to my desktop, and I still see the machine as present.

I think front-end only is definitely the sane way to go. I think people are fairly used to short delays in information propagating between different machines. But if you're really worried about it, we could have the toast say something like "Deleting in 30 seconds, click here to undo", similar to gmail's undo send. Then it's clear that you see it on your other machine because it's still in the undo grace period. We could even have a second "delete now" link for when people really want to see it gone now now now.

**Comment by dsnet** [comment]
> But if you're really worried about it, we could have the toast say something like "Deleting in 30 seconds, click here to undo", similar to gmail's undo send. Then it's clear that you see it on your other machine because it's still in the undo grace period.

I'm fairly certain the "undo" feature in gmail involves state changes in the backend as closing the gmail tab still ensures that the email gets sent eventually.

**Comment by sonovawolf** [comment]
Closing, fixed in https://github.com/tailscale/corp/pull/3241 see also https://github.com/tailscale/tailscale/issues/3298#issuecomment-988331378
