### ISSUE TITLE
cmd/tailscale/cli: ability to set hostname on the "up" command

### ISSUE THREAD

**Issue by codenoid** [tailscale/tailscale#2846]
## Case:

default hostname: only "database"

```sh
# command option?
tailscale up --set-name appname-database

tailscale up --name appname-database

tailscale up --hostname appname-database
```

**Comment by DentonGentry** [comment]
I don't understand what this is intended to mean.
`tailscale up --hostname name` is what is currently implemented.
You're asking for:
- `--name` and `--set-name` to be added as other options, or
- that the default change from the hostname of the system to appname-hostname

?

**Comment by codenoid** [comment]
sorry, I didn't do `tailscale up --help` before, btw I close the issue faster than your comment :p
