### ISSUE TITLE
Unable to remove machine using API : delete-node .

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2848]
A user reported he is unable to delete nodes using delete node API.

From User: 
Error: 
xhr.js:178 POST https://login.tailscale.com/admin/api/machines 500

machines.ts:111 Uncaught (in promise) Error: delete-node failed
    at machines.ts:111

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3jt1t)

**Comment by darshinimashar** [comment]
Edg/93.0.961.47","referer":"https://login.tailscale.com/admin/machines","code":500,"bytes":47,"err":"delete-node failed: cfgdb.Tx.Get: /cfgdb/nodekeydata/nodekey:8ffc5684bedcba529a67466a04d2e3e594eedbd9c802d13499dff88b5529715f not found"}

$ echo -n '8ffc5684bedcba529a67466a04d2e3e594eedbd9c802d13499dff88b5529715f' | xxd -r -p | base64
j/xWhL7culKaZ0ZqBNLj5ZTu29nIAtE0md/4i1UpcV8=

**Comment by nikanorov** [comment]
Hi! This issue is reported by me. Please ask me about any additional information.

**Comment by nikanorov** [comment]
The issue is marked as closed, but issue is still reproducible on the login.tailscale.com.

**Comment by bradfitz** [comment]
@nikanorov, hasn't been deployed yet. It was auto-closed by GitHub when the commit (to a separate repo) was submitted.

**Comment by bradfitz** [comment]
It's deployed now.

**Comment by nikanorov** [comment]
@bradfitz @sailorfrag  oh, excellent. Thank you so much.
