### ISSUE TITLE
Tailscale not working in FreeBSD jails

### ISSUE THREAD

**Issue by patmaddox** [tailscale/tailscale#2858]
When trying to run `tailscaled` in a FreeBSD jail, it produces this error:

```
# tailscaled
logtail started
Program starting: v1.10.0, Go 1.16.7: []string{"tailscaled"}
LogID: 2a3b18aa8ca610c035fa561e92de5aa2113e31ea008a574d5e7a89a3690d212e
logpolicy: using system state directory "/var/db/tailscale"
creating link monitor: devd dial error: dial unixpacket /var/run/devd.seqpacket.pipe: connect: no such file or directory
```

It doesn't matter if you use `tailscaled -tun "userspace-networking"`.

The error seems to come from [this line](https://github.com/tailscale/tailscale/blob/670838c45f232f2355c9f2ea587cbcef348410f4/wgengine/monitor/monitor_freebsd.go#L29). To my knowledge, devd is not available in FreeBSD jails.

**Comment by bradfitz** [comment]
Regardless of TUN vs userspace-networking, without the link monitor, Tailscale doesn't know when network conditions change.

What do you want us to do here? I suppose it could detect that it's running in a jail and that devd isn't available and fall back to polling mode. It won't be super efficient, but maybe that's good enough?

**Comment by bradfitz** [comment]
Feel free to send a change for that. We maintain FreeBSD primarily to the extent that OPNsense and pfSense continue to work. But neither of those use jails, AFAIK.

**Comment by patmaddox** [comment]
> What do you want us to do here?

I don't know, a lot of this stuff is currently beyond my understanding. I tried to run tailscale in a FreeBSD jail, and that's what happened.

**Comment by jzelinskie** [comment]
Many months ago I also tried to see if I could get devd into a jail, which is no-go (and maybe a fools errand in retrospect).

>fall back to polling mode

Would that basically look like just adding a ticker here and returning an unspecifiedMessage{} when it fires?
https://github.com/tailscale/tailscale/blob/670838c45f232f2355c9f2ea587cbcef348410f4/wgengine/monitor/monitor_freebsd.go#L41-L53
