### ISSUE TITLE
Is there any way to downgrade the Tailscale version on OPNsense?

### ISSUE THREAD

**Issue by Strider3000** [tailscale/tailscale#2862]
Since subnet routing in 1.14.2 is broken on OPNsense (https://github.com/tailscale/tailscale/issues/2758) is there a way to use an older working version of Tailscale, such as 1.12?

There are instructions for Tailscale on opnsense here (https://tailscale.com/kb/1097/install-opnsense/) but no instructions for downgrade.

**Comment by DentonGentry** [comment]
https://www.freshports.org/ports-mgmt/portdowngrade/ maybe?
In any case, FreeBSD ports is out of scope for this repository.
