### ISSUE TITLE
FR: Allow hostnames defined for ACLs to be used with MagicDNS

### ISSUE THREAD

**Issue by dfcarney** [tailscale/tailscale#2866]

**Comment by DentonGentry** [comment]
Hostnames defined in ACLs are typically used to provide a name for an IP address reachable via a subnet router, not usually to provide an alternate hostname for a Tailscale IP address.

Do we know the original reason for this request? Presumably a user inquiry around Sept 16, 2021, but there is no Front link.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/3800
