### ISSUE TITLE
Windows 11: "Log in..." from the tray icon's menu does not do anything at all

### ISSUE THREAD

**Issue by Thauxeeb** [tailscale/tailscale#2867]
_Windows 11 Pro Insider Preview
Build 22485.rs_prerelease.2109-1430
Microsoft Windows [Version 10.0.22458.1000]_

Hi!
I'm a first time user, wanting to try this out.

I've installed the latest build (tailscale-ipn-setup-1.14.3.exe), but when I try to click Log in... from the tray app, nothing happens.

![kép](https://user-images.githubusercontent.com/3326575/133732653-a2a7b1f0-f6aa-47c1-b503-0c36475c636f.png)

Can You help me please? Can I log-in from the console?

Thanks!

**Comment by Thauxeeb** [comment]
When I run tailscale up, the login URL does not show up, or from running the Web GUI, the login link points to _http://localhost:8088/#_ and does nothing either.

![kép](https://user-images.githubusercontent.com/3326575/133734770-0b1938d0-873c-45e0-813c-20755ac194ed.png)

![kép](https://user-images.githubusercontent.com/3326575/133734808-2ea1ea7e-dd8f-4c8a-8a0e-48176d061133.png)

**Comment by Thauxeeb** [comment]
I was using iPhones USB Ethernet adapter, and on the main Ethernet adapter there was a link to my MikroTik router, but without internet access. I've disabled the Realtek PCIe adapter, rebooted Windows and got it working.

**Comment by DentonGentry** [comment]
I'm glad it is working.

This looks like https://github.com/tailscale/tailscale/issues/2707, but release 1.14.3 contains the fix for that issue and you still ran into it here.

**Comment by DentonGentry** [comment]
This would be resolved by implementing https://github.com/tailscale/tailscale/issues/2187

**Comment by scorwin** [comment]
The same thing just happened to me...
