### ISSUE TITLE
Magicsock sometimes does not recover from internet outages

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#2869]
The setup: have tailscale on various devices in a home LAN, behind an ISP-provided internet router. Restart the ISP router, or have some kind of internet outage that is "soft" from the Tailscale client's POV (interface doesn't go down, packets just stop flowing). Upon recovery of the internet link, I've observed both magicsock being stuck on DERP, as well as a fairly prolonged inability to communicate at all.

I'm unsure if this is a regression, or if we always reacted poorly to that specific case of upstream outage. Either way, filing this tracking bug to characterize things a bit more and see what we can do about it.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kdjl)

**Comment by danderson** [comment]
And of course, now that I try to reproduce this by (accidentally) breaking my internet briefly, it doesn't repro and Tailscale recovers fine. Grmbl.

**Comment by agneevX** [comment]
After updating to 1.14.4 on machines exhibiting this issue, I haven't been able to reproduce this, so far 👍

**Comment by apenwarr** [comment]
Ah. Possibly related or the same bug: https://github.com/tailscale/tailscale/issues/2994 (that bug refers to iOS but there is not yet a reason to assume it's iOS-only)

**Comment by DentonGentry** [comment]
Since all former reproduction cases no longer produce a problem, I'll say this got fixed along the way.

Please don't reopen this bug: if you notice a problem which seems similar, open a new bug so we don't conflate old symptoms with new.
