### ISSUE TITLE
Allow hosts on the same network to talk over layer2

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/tailscale#287]
**Is your feature request related to a problem? Please describe.**
Hosts on the same network don't seem to talk to each other directly 
**Describe the solution you'd like**

Since the internal IP address is already available in admin console I would like tailscale to prioritise private network ranges for p2p connection.

**Comment by danderson** [comment]
We already do that, if the hosts can talk through rfc1918 IPs, that takes priority over all other paths. If you're seeing something different, please contact support@tailscale.com with details of which machines, so we can look at logs?

**Comment by JayDoubleu** [comment]
I see, thanks. 
My rfc1918 double/nested NAT might be to blame for this then.
I'll contact support. Feel free to close.

**Comment by danderson** [comment]
It's possible, yeah. If the "local" machines have to talk through a NAT, there can be configurations that are basically impossible to handle without relaying over the internet, or modifying router configs. We can debug more in email.

**Comment by bradfitz** [comment]
With recent versions of tailscale, you can run `tailscale status` to see which paths are being used between peers.
