### ISSUE TITLE
App Store Broken?

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2876]
The MacOS version is still 1.12 a month later. Assuming Apple isn't taking 1 month to do a notarization, did the build get stuck in the pipelines?

Thanks!

App store screenshot:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/3596242/133916997-4eb7ca41-a768-4dd5-bdc3-d94fa7b82904.png">

Current version is 1.14.3, but appstore is 1.12.3

**Comment by DentonGentry** [comment]
Apple rejected the 1.14.0 app in review, and we've been trying to address it since.
