### ISSUE TITLE
High CPU Usage in Linux

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2877]
Hi there,

I am using a Linux exit node, and the CPU usage is constantly stuck at 100%, used by 4 Tailscaled process/threads. Is this normal?

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/3596242/133917534-77fc4e2a-5ed7-4199-b6bb-e0e7a713cf20.png">

Wanted to see if there's any way to further optimize or resolve this.

**Comment by DentonGentry** [comment]
Is there a lot of DNS-related messages in the `journalctl -u tailscaled` output?
https://github.com/tailscale/tailscale/issues/2729 has had one root cause fixed but there may be other cases where a DNS packet can end up looping between MagicDNS and an upstream resolver.

**Comment by vysecurity** [comment]
No DNS related messages there hmm.

Just plenty of these:

`Sep 18 11:57:36 REDACTED tailscaled[3868]: netcheck: probePortMapServices: skipping portmap; gateway range likely lacks support
Sep 18 11:57:36 REDACTED tailscaled[3868]: magicsock: STUN done; sending call-me-maybe to d:REDACTED [eAUsR]`

**Comment by bradfitz** [comment]
What Tailscale version? What's your Tailscale IP? Or a `tailscale bugreport` marker? How much traffic is passing through it? Is it a 32-bit Raspberry Pi?

Use `perf top` to see what it's doing, or in `/etc/default/tailscaled` set the line:

```
FLAGS="-debug=localhost:52355"
```

And the restart tailscaled and run:

```
$ go tool pprof http://localhost:52355/debug/pprof/profile?seconds=15
```

And run `top 40` or `top 40 --cum` to see what it's doing.

There's nothing to go on to help debug, so I'll close this for now until we have more info.
