### ISSUE TITLE
ACL: announced tags not working for rules using IPv6 nodes

### ISSUE THREAD

**Issue by BrianAdams** [tailscale/tailscale#2879]
Host running version 1.14.0 on linux.  
Client used 1.14.0 on Android and Linux.

## Steps:
1. Add an ACL based on tag for allowing permissions to a port on tagged service
```
  "ACLs": [
    { "Action": "accept", "Users": ["group:admin"], "Ports": ["tag:server-myservice:8081"]},
  ...
  ]
```
2. Add node using ephemeral key announcing tag from above
3. Verify that the tailscale machines page shows the node with the announced tags
3. Attempt to hit a service running on the node with chrome http://[ipv6]:port

## Expected result:
See the page

## Actual result:
No connection made
In the logs on the node we see the packet was dropped

### Workaround
Add the IPV6 address to Hosts and then use the host name instead of the tag name in the ACL, now I can hit the service
```
  "Hosts": {
    "myservice": "fd7a:115c:a1e0:efe3:fa3c:d83e:808d:d01e"
  },
  "ACLs": [
    { "Action": "accept", "Users": ["group:admin"], "Ports": ["tag:server-myservice:8081"]},
    { "Action": "accept", "Users": ["group:admin"], "Ports": ["myservice:8081"]},
  ...
  ]
```

**Comment by bradfitz** [comment]
Thanks for the report. I see the problem.

**Comment by bradfitz** [comment]
@BrianAdams, this bug will close shortly when I submit the fix to our control plane server's repo but it won't be visibly fixed for you until we do a control server deploy later in the day.

**Comment by BrianAdams** [comment]
@bradfitz Just a FYI, just tried again right now, and the problem still persists.  Fully get that the control server deploy may not have happened, just following up based on the last comment that it was expected to deploy yesterday.

**Comment by bradfitz** [comment]
It hasn't been deployed yet. Yesterday was full of distractions for everybody.

Probably later today.

**Comment by BrianAdams** [comment]
Confirmed fixed. Thanks!
