### ISSUE TITLE
Add iOS Widgets

### ISSUE THREAD

**Issue by pewter77** [tailscale/tailscale#2881]
Widgets provide an easy way to check status and turn on/off tailscale without having to go back into the app. Also generally an easy way to easily launch tailscale as well.

General iOS widget would have:

- Status (on/off, which exit node is in use)
- Button to turn tailscale on/off
- If you click outside the button area launches the full app

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1935
