### ISSUE TITLE
Refuse to unmarshal key types into a non-zero value?

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#2888]
Comment from https://github.com/tailscale/tailscale/pull/2884: should our key types have Unmarshal* methods that refuse to unmarshal into a non-zero value?

I guess it could be seen as a code smell to overwrite an existing key. OTOH, the only bad thing that would happen is that you can no longer do crypto if you still expect the value to be the old key, which... shrug? I don't know, it feels potentially useful to be able to update a type in place through unmarshaling, but I'm unsure.

Empirically, our unit tests say that nothing currently tries to unmarshal NodePrivate into a non-zero value.

If we choose to make non-zero unmarshaling invalid, we should do so consistently for all our key types.

cc @josharian @bradfitz

**Comment by bradfitz** [comment]
FWIW, this is one of the unique things we added to netaddr Unmarshal methods that Russ flagged as weird and that we'd probably want to remove for consistency before it goes into std.

**Comment by danderson** [comment]
Our current code is undecided on this. Some of our key types refuse to overwrite non-zero keys, others allow it (worse, some allow it only for some deserialization methods but not others, sigh). I don't have a compelling argument for being non-idiomatic, but I'm happy with either choice as long as we're consistent.

**Comment by josharian** [comment]
I inspected all our unmarshal methods. All of them allow overwriting non-zero values. Calling this done.
