### ISSUE TITLE
pkgs.tailscale.com inaccessible from China Telecom

### ISSUE THREAD

**Issue by csloz** [tailscale/tailscale#289]
Doesn't seem to be GFW related, as it hops past that successfully.  

---
 ping pkgs.tailscale.com
PING pkgs.tailscale.com (165.227.17.164) 56(84) bytes of data.
^C
--- pkgs.tailscale.com ping statistics ---
35 packets transmitted, 0 received, 100% packet loss, time 34792ms

traceroute 165.227.17.164
traceroute to 165.227.17.164 (165.227.17.164), 30 hops max, 60 byte packets
 1  192.168.0.1 (192.168.0.1)  0.368 ms  0.438 ms  0.519 ms
 2  116.233.140.1 (116.233.140.1)  2.855 ms  3.424 ms  3.186 ms
 3  61.152.3.81 (61.152.3.81)  8.712 ms 61.152.3.85 (61.152.3.85)  3.105 ms 61.152.51.29 (61.152.51.29)  7.042 ms
 4  202.101.63.134 (202.101.63.134)  3.650 ms 101.95.88.10 (101.95.88.10)  5.800 ms 61.152.24.34 (61.152.24.34)  3.112 ms
 5  * 202.97.64.182 (202.97.64.182)  20.110 ms 202.97.48.14 (202.97.48.14)  37.572 ms
 6  202.97.74.5 (202.97.74.5)  8.513 ms * *
 7  * 202.97.89.142 (202.97.89.142)  202.958 ms *
 8  * 202.97.90.114 (202.97.90.114)  197.685 ms 202.97.50.58 (202.97.50.58)  149.683 ms
 9  218.30.54.245 (218.30.54.245)  139.426 ms 218.30.53.109 (218.30.53.109)  176.891 ms  178.135 ms
10  * ae-11.r00.lsanca07.us.bb.gin.ntt.net (129.250.2.105)  215.835 ms ae-9.r01.lsanca07.us.bb.gin.ntt.net (129.250.2.117)  157.759 ms
11  ae-3.r23.lsanca07.us.bb.gin.ntt.net (129.250.4.106)  199.042 ms ae-2.r23.lsanca07.us.bb.gin.ntt.net (129.250.3.237)  183.144 ms  190.833 ms
12  ae-12.r22.snjsca04.us.bb.gin.ntt.net (129.250.4.150)  183.260 ms * *
13  ae-19.r01.snjsca04.us.bb.gin.ntt.net (129.250.3.27)  181.858 ms  181.463 ms *
14  ae-4.r05.plalca01.us.bb.gin.ntt.net (129.250.5.32)  156.422 ms * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by bradfitz** [comment]
It's up for me.

You can use this site to tell if it's actually down or just for you: https://downforeveryoneorjustme.com/pkgs.tailscale.com

I have to assume this is just China's GFW. Not much we can do there, sorry.

**Comment by csloz** [comment]
Respectfully, it doesn't seem to be GFW related, as it hops past that successfully.  Typically this will show up earlier for ip blocks.

Also have beijing based traceroute

traceroute to pkgs.tailscale.com (165.227.17.164), 30 hops max, 60 byte packets
 1  _gateway (192.168.167.33)  0.374 ms  0.502 ms  0.692 ms
 2  222.129.240.1 (222.129.240.1)  13.916 ms  14.070 ms  14.160 ms
 3  123.126.27.53 (123.126.27.53)  6.026 ms  5.795 ms  6.096 ms
 4  124.65.57.93 (124.65.57.93)  5.437 ms  8.954 ms  9.167 ms
 5  202.96.12.93 (202.96.12.93)  14.995 ms  15.078 ms  15.149 ms
 6  219.158.5.154 (219.158.5.154)  10.476 ms  9.874 ms 219.158.5.146 (219.158.5.146)  10.546 ms
 7  219.158.3.142 (219.158.3.142)  6.649 ms  6.738 ms  6.764 ms
 8  219.158.16.98 (219.158.16.98)  212.713 ms  212.919 ms  220.997 ms
 9  219.158.40.190 (219.158.40.190)  187.959 ms  188.064 ms  188.092 ms
10  if-ae-2-2.tcore2.lvw-los-angeles.as6453.net (66.110.59.2)  191.440 ms  191.527 ms  190.401 ms
11  if-ae-35-2.tcore1.sf9-san-francisco.as6453.net (64.86.252.178)  191.706 ms  191.792 ms  191.786 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *


--
Typically GFW blocks would not let things get to the US - eg

Example of something that is blocked by GFW 

 traceroute google.com
traceroute to google.com (8.7.198.46), 30 hops max, 60 byte packets
 1  192.168.0.1 (192.168.0.1)  0.489 ms  0.455 ms  0.433 ms
 2  * * *
 3  61.152.51.29 (61.152.51.29)  7.475 ms 61.152.51.25 (61.152.51.25)  9.163 ms  9.165 ms
 4  61.152.24.38 (61.152.24.38)  5.476 ms 61.152.24.26 (61.152.24.26)  6.854 ms 202.101.63.214 (202.101.63.214)  7.328 ms
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *


traceroute facebook.com
traceroute to facebook.com (174.37.154.236), 30 hops max, 60 byte packets
 1  192.168.0.1 (192.168.0.1)  0.351 ms  0.414 ms  0.288 ms
 2  116.233.140.1 (116.233.140.1)  7.517 ms  6.909 ms  7.190 ms
 3  61.152.50.29 (61.152.50.29)  12.541 ms 61.152.3.85 (61.152.3.85)  5.143 ms 61.152.50.29 (61.152.50.29)  12.538 ms
 4  101.95.120.218 (101.95.120.218)  6.667 ms 101.95.120.234 (101.95.120.234)  5.121 ms 61.152.86.142 (61.152.86.142)  6.173 ms
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

You'll note that they don't bother letting traffic go international to saturate links.

I checked your AS number for the IP to see the peering.
Your ip peering is via AS14061, will raise this with Digital Ocean, as they'll have a better idea., might be bad BGP routing.

Cheers.

**Comment by csloz** [comment]
Ok, not bad routing, as others around you are routable from here - 

ping  165.227.17.163
PING 165.227.17.163 (165.227.17.163) 56(84) bytes of data.
64 bytes from 165.227.17.163: icmp_seq=1 ttl=51 time=134 ms
64 bytes from 165.227.17.163: icmp_seq=2 ttl=51 time=133 ms
^C
--- 165.227.17.163 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 133.393/133.796/134.200/0.403 ms
root@nas:/opt# ping  165.227.17.165
PING 165.227.17.165 (165.227.17.165) 56(84) bytes of data.
64 bytes from 165.227.17.165: icmp_seq=1 ttl=51 time=178 ms
64 bytes from 165.227.17.165: icmp_seq=2 ttl=51 time=178 ms
64 bytes from 165.227.17.165: icmp_seq=3 ttl=51 time=178 ms


Perhaps you're doing blocking your end?

**Comment by bradfitz** [comment]
We have no firewall rules configured. We're not blocking anybody.

That server is on DigitalOcean. Maybe DigitalOcean blocks them?  I just searched for "China Telecom Digital Ocean" and a top result was:

https://arstechnica.com/tech-policy/2020/04/citing-bgp-hijacks-and-hack-attacks-feds-want-china-telecom-out-of-the-us/

So maybe they are blocking it?

In any case, it's not us.

**Comment by csloz** [comment]
Ok, thank you for checking again.

We have servers at DO that are accessible from China.  Might potentially want to look at another ip if that one is blocked, and revisit.  I'm happy to assist with testing if necessary.

**Comment by csloz** [comment]
I see that the servers work correctly from China, can mark this resolved now.
