### ISSUE TITLE
Alias domains for a tailnet

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2890]
From User:
" different client networks will not talk to one another.  Only my consulting staff need to access all the client networks as do the respective staff from each client company.
Providing shared nodes defeats the purpose of managing the networks as we do not want to track all the individual users needing to connect to every individual machine.  Nor do we want to add emails for every consultant inside of every client domain."

The user is looking forward to having 1  major domain that can access all other domains, but the other 2 or multiple domains should not be able to access other domains. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3klzl)

**Comment by DentonGentry** [comment]
This would be an enormous project.

**Comment by anupmurarka** [comment]
The description is more complex than the original simple request:  Support user emails from more than a single domain for a given VPN network/account.  Instead of sharing individual hosts (which defeats the purpose of managing access via the network resources and ACL), I'd asked the status of the feature work referenced in existing blog/help article posts about allowing users from multiple email domains to be added to an account.

**Comment by DentonGentry** [comment]
We do have a way to alias multiple domains together, so example1.com and example2.com can both end up in the same Tailnet. It is a manual process for us and takes several days to get into production.

**Comment by andyt10** [comment]
Just got really excited to try tailscale after hearing so much about it, but this lack of 'aliasing' or 'more than a single domain' feature was an immediate deal breaker for my use case. :( 

The company I work for sits under many brands, and we don't all have a common email as the docs suggest:

> If you’d like to invite other members to your network, sign up for a new account using an email address domain that your whole team shares (see the example at the beginning of the article).

Having each brand in my case set up their own network(s) is not ideal or practical for the initial single use case

Look forward to giving Tailscale a go in a personal context at some time in future.

**Comment by DentonGentry** [comment]
Please feel free to contact support@tailscale.com about it. We do have a way to alias multiple domains together, just not in a self-service way. It is a manual process for Tailscale support to set up.

**Comment by DentonGentry** [comment]
I think the original request is met: there is a way to alias multiple domains together. support@tailscale.com can help.
