### ISSUE TITLE
ICMP responses should be allowed even with no permitted ACLs

### ISSUE THREAD

**Issue by sylr** [tailscale/tailscale#290]
**Describe the bug**

I have an ACL to let some users access a synology NAS (`nas1`) via a node (`pi1`) running tailscale and advertising the subnet the NAS is on.

```javascript
{
  // Declare convenient hostname aliases to use in place of IP addresses.
  "Hosts": {
    "pi1": "10.10.40.15",
    "nas1": "10.10.40.10",
  },

  // Access control lists.
  "ACLs": [
    { "Action": "accept", "Users": ["osmc-devices@domain.fr"], "Ports": ["nas1:*"] },
    { "Action": "accept", "Users": ["sylvain@domain.fr"], "Ports": ["*:*"] },
  ]
}
```

With this enabled I'm not able to ping nas1.

I've the following log on the node I'm pinging from:

```
Apr 11 16:52:37 osmc1 tailscaled[8180]: 2020/04/11 16:52:37 Drop: ICMP{10.10.40.10:0 > 100.64.52.95:0} 84 no rules matched
```

It is only working when I have the default allow all from all users rule.

**Version information:**
 - OS version: debian 9.12
 - Tailscale version: 0.97.0~45

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686566386770) by [Unito](https://www.unito.io/learn-more)

**Comment by sylr** [comment]
Also I am trying to do some snmp from a node which user has the allow all ACL but it does not work:

```
{ "Action": "accept", "Users": ["sylvain@domain.fr"], "Ports": ["*:*"] },
```

I need to restore the following ACL to make it work again:

```
{ "Action": "accept", "Users": ["*"], "Ports": ["*:*"] },
```

It seems that non TCP flow between users do not work when there are some non default ACLs.

**Comment by danderson** [comment]
This is a limitation of our current ACL data model: ICMP only works if ACLs allow _some_ traffic to flow in both directions. Your ACLs only allow flow in 1 direction (from tailscale "clients" to end hosts), so ICMP is filtered.

We're working on fixing the data model so you can express more things. In the meantime, a workaround is to add an ACL that allows traffic from all users to some unused port (e.g. TCP port 1). That will make the ACL engine unblock ICMP.

**Comment by sylr** [comment]
@danderson thank you for the tip 👍
