### ISSUE TITLE
DNS setup (on Linux)

### ISSUE THREAD

**Issue by sh0rez** [tailscale/tailscale#291]
Currently, it does not seem as if Linux hosts pick up the DNS config from the admin panel when connecting to tailscale.

I guess this is because it is disabled in the code (`TODO`):
https://github.com/tailscale/tailscale/blob/a7e7c7b548dd7903326360b4d9740a0412779433/wgengine/router_linux.go#L155-L159

Looking at what it would attempt if enabled, it seems as if tailscale **replaces `/etc/resolv.conf`** with it's own version.

Wouldn't that cause issues with other files modifying `resolv.conf` as well? It might be a better idea to use `resolvconf` if available (https://wiki.archlinux.org/index.php/Openresolv), like `dhcpd` does and only fallback to hard replacing?

**Comment by jjo93sa** [comment]
I think this is a bug not an enhancement? It appears to be very similar to #101 in that the DNS entry in the Admin console simply doesn't appear in the Linux configuration as far as I can tell. I've tested this with the latest Tailscale version (v0.97-45-g02c73501) and Ubuntu 18.04.3. Once Tailscale is up & authenticated, `/etc/resolv.conf` is unchanged. The DNS server was configured in the Admin console before installing this node:

```
cat /etc/resolv.conf

nameserver 127.0.0.53
options edns0
```

Which is the default for 18.04.3, IIRC. And `systemd-resolved` says:

```
ansible@graylog:~$ sudo systemd-resolve --status
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 3 (tailscale0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (ens2)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 10.10.20.1
                      1.1.1.1
```

The configured IP address for my internal DNS server (100.124.118.27) is absent, at least from any file under `/etc`.

**Comment by bradfitz** [comment]
@jjo93sa, I just marked it as an Enhancement because DNS is just something we haven't focused on much yet. We know there are DNS TODOs everywhere. But sure, I can mark it as a bug too.

**Comment by jjo93sa** [comment]
@bradfitz Understood & thanks. I suggest the bug flag purely for non-altruistic reasons that I'd really like to get a working DNS system sooner than perhaps an enhancement might indicate ;-)

As with #101, I'm more than happy to help test/debug with Linux/iOS/macOS if it'd help.

**Comment by danderson** [comment]
Specifically, DNS on linux is a known TODO. We just don't apply DNS configuration at all. So, it's not really a bug in that it's working exactly as implemented ;). DNS is something we want to get working soon though, for the obvious reasons.

**Comment by jjo93sa** [comment]
@danderson Fair point! Is there an estimate for when the DNS feature will be released?

**Comment by cyrilgdn** [comment]
> @danderson Fair point! Is there an estimate for when the DNS feature will be released?

Sorry for the noise but I'd also like to have this rough estimate. We're looking for a new way to connect to our cloud environments and Tailscale would have been a perfect fit but as our developers mostly have Linux workstations and we need to contact internal DNS names (so to automatically setup a specific DNS server when connecting to the VPN), it seems we cannot use it (unless I misunderstood something?).

Thanks in advance.

**Comment by bradfitz** [comment]
Yeah, this is all mostly done. @dshynkev, do you want to keep this open or do you have more specific bugs open for the remaining items?

**Comment by matschges1cht** [comment]
Isn't this a Problem wireguard solved already? Wireguard DNS on Ubuntu doesn't work until resolvconf is installed. Maybe tailscale can use a similar approach? See https://github.com/StreisandEffect/streisand/issues/1434

**Comment by blmhemu** [comment]
Even I have problems with DNS (MacOS). 
I have setup an adguard DNS server on an RPi and am able to access it via tailscale. But when I add it as a nameserver, I cannot access my internal domains.
Also my preferences show old DNS servers not the ones setup in tailscale.

**Comment by DentonGentry** [comment]
Regarding MacOS, there are other issues tracking a couple problems like https://github.com/tailscale/tailscale/issues/923 (specific to Big Sur, and seems resolved now).

There are also some issues open tracking specific Linux DNS issues like the various mechanisms different distributions have for per-interface resolv.conf.

This issue was about implementing the overall feature, and I think this is done. Using it to track somewhat different followon issues is not really useful. @dshynkev hasn't responded about remaining items and it has been a few months, closing this now.
