### ISSUE TITLE
install.sh: Adding distributions issue tracker

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2915]
OS=fedora
VERSION=
PACKAGETYPE=dnf
UNAME=Linux fedora 5.13.13-200.fc34.x86_64 #1 SMP Thu Aug 26 17:06:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

--------

OS=opensuse
VERSION=leap/15.3
PACKAGETYPE=zypper
UNAME=Linux jarfx 5.3.18-59.19-preempt #1 SMP PREEMPT Tue Aug 3 14:11:23 UTC 2021 (055c4fd) x86_64 x86_64 x86_64 GNU/Linux

NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3l5qp)

**Comment by darshinimashar** [comment]
Below is the info from curl command:

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux pop-os 5.11.0-7633-generic #35~1630100930~21.04~ae2753e-Ubuntu SMP Mon Aug 30 18:26:54 UTC  x86_64 x86_64 x86_64 GNU/Linux

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Comment by darshinimashar** [comment]
Please include the following information we gathered from your system:

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux ZOS-virtual-machine 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Zorin OS"
VERSION="16"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://zorin.com/help/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by DentonGentry** [comment]
Fedora Silverblue

OS=fedora
VERSION=
PACKAGETYPE=dnf
UNAME=Linux precision 5.14.9-300.fc35.x86_64 #1 SMP Thu Sep 30 11:54:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Fedora Linux"
VERSION="35.20211008.n.0 (Silverblue Prerelease)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35.20211008.n.0 (Silverblue Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='35.20211008.n.0'

**Comment by darshinimashar** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux think 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.1"
VERSION_ID="20.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyssa
UBUNTU_CODENAME=focal

**Comment by darshinimashar** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux god-optiplex-7010-desktop-kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.4"
VERSION_ID="2021.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by titpetric** [comment]
Debian 9, stretch?

```
root@serenity:~# curl -fsSL https://tailscale.com/install.sh | sh
sh: 49: VERSION_CODENAME: parameter not set
root@serenity:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

```
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

May be a bit dated, but a go static binary should run on this.

**Comment by darshinimashar** [comment]
OS=other-linux

VERSION=

PACKAGETYPE=

UNAME=Linux vuzero4k 4.1.20-1.9 #1 SMP Mon Nov 1 01:03:26 UTC 2021 armv7l GNU/Linux

 

ID="openatv"

NAME="openatv"

VERSION="6.4"

VERSION_ID="6.4"

PRETTY_NAME="openatv 6.4"

**Comment by DentonGentry** [comment]
openatv is sufficiently different from desktop/server Linux platforms that we're not likely to be able to support it in install.sh.

It looks like openatv uses start-stop-daemon scripts in its init system? We developed one for GitHub Codespaces in https://github.com/tailscale/dgentry-codespace/blob/main/tailscaled which might be helpful.

**Comment by darshinimashar** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux radar 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux

ID=pureos
NAME=PureOS
PRETTY_NAME=PureOS

VERSION_ID=10.0
VERSION_CODENAME=byzantium

HOME_URL="https://pureos.net/"
SUPPORT_URL="https://puri.sm/faq/#faq-WherecanIfindoutmoreaboutPureOS"
BUG_REPORT_URL="https://tracker.pureos.net/"

LOGO=pureos-logo-icon

**Comment by JayWStapleton** [comment]
OS=ubuntu
VERSION=uma
PACKAGETYPE=apt
UNAME=Linux styromaniac-Studio-XPS-1645 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

**Comment by DentonGentry** [comment]
OS=ubuntu
VERSION=uma
PACKAGETYPE=apt
UNAME=Linux hostname 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

----

Devuan GNU+Linux, fork of Debian Linux
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux hostname 5.13.19-1-pve #1 SMP PVE 5.13.19-2 (Tue, 09 Nov 2021 12:59:38 +0100) x86_64 GNU/Linux

PRETTY_NAME="Devuan GNU/Linux ascii"
NAME="Devuan GNU/Linux"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"

**Comment by darshinimashar** [comment]
OS=other-linux

VERSION=

PACKAGETYPE=

UNAME=Linux photon-machine 5.10.83-5.ph4-esx #1-photon SMP Tue Jan 4 02:55:19 UTC 2022 x86_64 GNU/Linux

 

NAME="VMware Photon OS"

VERSION="4.0"

ID=photon

VERSION_ID=4.0

PRETTY_NAME="VMware Photon OS/Linux"

ANSI_COLOR="1;34"

HOME_URL=https://vmware.github.io/photon/

BUG_REPORT_URL=https://github.com/vmware/photon/issues

**Comment by darshinimashar** [comment]
CentOS 9 is not supported with install.sh

OS=centos
VERSION=9
PACKAGETYPE=dnf
UNAME=Linux ip-172-16-30-81.eu-central-1.compute.internal 5.14.0-44.el9.aarch64 #1 SMP Mon Jan 17 18:42:00 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

**Comment by darshinimashar** [comment]
Alpine Linux support

> OS=other-linux
> VERSION=
> PACKAGETYPE=
> UNAME=Linux deckard-pinephone 5.15.13 #2-postmarketos-allwinner SMP PREEMPT Sun Jan 16 22:48:42 UTC 20 aarch64 GNU/Linux
>
> PRETTY_NAME="postmarketOS v21.12.1"
> NAME="postmarketOS"
> VERSION_ID="v21.12.1"
> VERSION="v21.12.1"
> ID="postmarketos"
> ID_LIKE="alpine"
> HOME_URL="https://www.postmarketos.org/"
> SUPPORT_URL="https://gitlab.com/postmarketOS"
> BUG_REPORT_URL="[https://gitlab.com/postmarketOS/pmaports/issues”](https://gitlab.com/postmarketOS/pmaports/issues%E2%80%9D)

**Comment by darshinimashar** [comment]
OS=other-linux

VERSION=

PACKAGETYPE=

UNAME=Linux SynologyRouter 4.4.60 #8227 SMP Sat Jul 17 01:18:45 CST 2021 armv7l GNU/Linux synology_ipq806                       x_rt2600ac

 

No /etc/os-release

**Comment by darshinimashar** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux exitnode0 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 09:17:08 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"

**Comment by JayWStapleton** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux steamdeck 5.13.0-valve10.1-1-neptune-02144-g7fffaf925dfb #1 SMP PREEMPT Sat, 19 Feb 2022 22:46:17
+0000 x86_64 GNU/Linux

NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck
VERSION_ID=snapshot
BUILD_ID=20220227.3

**Comment by DentonGentry** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux webserver.thestrangeland.net 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Thu Mar 10 11:31:47 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"

**Comment by DentonGentry** [comment]
Parrot OS.

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux wc-folio 5.16.0-12parrot1-amd64 #1 SMP PREEMPT Debian 5.16.12-2parrot1 (2022-03-11) x86_64 GNU/Linux

PRETTY_NAME="Parrot OS 5.0 (Electro Ara)"
NAME="Parrot OS"
VERSION_ID="5.0"
VERSION="5.0 (Electro Ara)"
VERSION_CODENAME=ara
ID=parrot
ID_LIKE=debian
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://community.parrotsec.org/"
BUG_REPORT_URL="https://community.parrotsec.org/"

**Comment by DentonGentry** [comment]
Linuxmint LMDE (we added support for the Ubuntu based linuxmint, LMDE is Debian):

OS=ubuntu
VERSION=elsie
PACKAGETYPE=apt
UNAME=Linux rootofauthority 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux

PRETTY_NAME="LMDE 5 (elsie)"
NAME="LMDE"
VERSION_ID="5"
VERSION="5 (elsie)"
ID=linuxmint
ID_LIKE=debian
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=elsie
DEBIAN_CODENAME=bullseye

**Comment by DentonGentry** [comment]
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux parrot1 5.15.0-15parrot1-amd64 #1 SMP Debian 5.15.15-15parrot2 (2022-02-15) x86_64 GNU/Linux

PRETTY_NAME="Parrot OS 5.0 (LTS)"
NAME="Parrot OS"
VERSION_ID="5.0"
VERSION="5.0 (LTS)"
VERSION_CODENAME=lts
ID=parrot
ID_LIKE=debian
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://community.parrotsec.org/"
BUG_REPORT_URL="https://community.parrotsec.org/"

**Comment by t3kg33k** [comment]
Is there anything I can do to assist with testing Tailscale on AlmaLinux 8?

**Comment by DentonGentry** [comment]
Alma Linux support is currently in a pull request, in https://github.com/tailscale/tailscale/pull/4430. Once submitted, install.sh will be updated to support installing on AlmaLinux.

**Comment by DentonGentry** [comment]
This issue has gotten long and unwieldy enough that I think this is a good time to close it. We added all of the distributions listed here which are possible to add to install.sh. As user reports come in for more distributions, we'll open new bugs for each one so that we can more easily track what is done and what is left to try to add.

**Comment by warloxian** [comment]
Im so sorry, but I have looked at the script. I am no coder , but I am trying to force install on Linux parrot 6.5.0-13parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1parrot1 (2023-12-19) x86_64 GNU/Linux
, but i do not know where to add or subtract this version #deb https://deb.parrot.sh/parrot lory main contrib non-free
#deb-src https://deb.parrot.sh/parrot lory main contrib non-free

**Comment by Justinzobel** [comment]
I see Silverblue mentioned above but nothing in the installer.sh to support it or the other immutable variants like Kinoite.

**Comment by Justinzobel** [comment]
Tailscale on Fedora Kinoite/Silverblue

wget is on the base image
wget https://pkgs.tailscale.com/stable/tailscale_1.92.3_amd64.tgz (or relevant architecture based on uname -a = Linux fedora 6.17.11-300.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Dec  8 23:20:36 UTC 2025 x86_64 GNU/Linux)

sudo mkdir /opt/tailscale

mv binaries into there
sudo chown -R root:root /opt/tailscale

move systemd service into /etc/systemd/system/
move defaults file into /etc/default/

Push `tailscale` PATH into user's shell script (with instructions on how to do it for other users if they are to be able to access the binary.

If someone wants to add this to the script, that would be great.

Edit: Change the paths in the systemd file for the binaries.
