### ISSUE TITLE
Tailscale for MacOS flooding subnet router

### ISSUE THREAD

**Issue by maxburke** [tailscale/tailscale#2917]
One of our users was reporting that their connection was feeling a little slow so I jumped onto one of the subnet routers and checked their status and noticed:

```
100.99.140.44   XXX-macbookpro-2  XXX@      macOS   active; direct 10.128.0.170:41641, tx 1998908 rx 24046677652
```

The RX amount seems crazy high especially because he just recently started for the day. Watched it for a bit and the value was ticking up by about 1GB per minute

He noticed on his machine that the IPNExtension process was going crazy:

![image](https://user-images.githubusercontent.com/253368/134549678-7bb4b2bd-9e6f-4f14-b1ab-350cd21df57f.png)

After quitting and restarting tailscale everything was back to normal.

**Comment by bradfitz** [comment]
Dup of #1526. We're actively working on this. (I'm sending a debug build out later today to a customer who can repro this on demand...)

We're getting closer.

It looks like it might be a macOS bug around VPNs & network changes, either changing wifi or resuming from sleep, etc.

**Comment by bradfitz** [comment]
Can you comment on #1526 with more details of your system? Exact macOS version, CPU type, what other network/VPN/firewall/antivirus stuff you have?
