### ISSUE TITLE
Invalid /etc/resolv.conf after enable https

### ISSUE THREAD

**Issue by zhsj** [tailscale/tailscale#2918]
Version: 1.14.3
OS: Debian

MagicDNS is not enabled and no nameserver is set on admin pannel. After enable https, my /etc/resolv.conf is overwritten with following:

```
zsj@debian:~$ cat /etc/resolv.conf 
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

search xxx.ts.net
```

The nameserver is empty on my machine now.

**Comment by bradfitz** [comment]
You'll need MagicDNS to use HTTPS certs. We'll document that better and not send an altered DNS config to your nodes if you're not otherwise getting a MagicDNS config.
