### ISSUE TITLE
macOS installation instructions a bit off - no prompt to install VPN configuration

### ISSUE THREAD

**Issue by skarra** [tailscale/tailscale#292]
**Describe the bug**
The macOS installation instructions are slightly off (based on a single data point from my personal machine). After completing step 1 in the instructions, I was waiting for some prompt, but nothing happened. After thinking the installation failed for some reason, I eventually realized I could go directly to Step 3 and login and connect the device my tailscale network.

**Screenshots**
<img width="677" alt="tailscale" src="https://user-images.githubusercontent.com/633395/79060810-64d94a80-7c3e-11ea-9ec9-4c1bd411c7f4.png">

**Version information:**
 - Device: Macbook Pro c. 2015
 - OS: Mojave 10.14.6
 - Tailscale version: 0.97.98

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686410117854) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
Maybe the prompt was added in Catalina (macOS 10.15).

I suppose we could hedge and say "Accept any prompt to install...".

@rosszurowski?

**Comment by rosszurowski** [comment]
I've just updated it to the following, to avoid the implication that the prompts will _definitely_ appear.

> Accept any prompts to install VPN configurations that may appear

If we know it's only in Catalina I'll update it to include the version (ie. _only appears on macOS 10.15 and higher_), but I have a hazy recollection of getting that prompt in older versions of macOS too.
