### ISSUE TITLE
Synology DSM6 x86_64 package (1.14.3) stops working after 1 minute

### ISSUE THREAD

**Issue by traktuner** [tailscale/tailscale#2920]
Hello,
I installed the new package 1.14.3 (tailscale-x86_64-1.14.3-008-dsm6.spk) over the existing 1.12.1 version on my DS3617xs. That worked, NAS showed as "online" on the Tailscale website and after approx. 1 minuted the status went to "offline". I checked the NAS and the package was stopped - restarted the package, and it worked for roughly 1 minute again.
Please let me can provide any logs. I deleted it and installed 1.12.1 again.
Thank you!

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kykx)

**Comment by DentonGentry** [comment]
One initial thing we'd need is some way to look up telemetry from the device: the account name or Tailscale IP address. If you're not comfortable putting that on the bug, it can be sent to support@tailscale.com.

**Comment by traktuner** [comment]
Just sent you a support email. Thanks in advance!

**Comment by DentonGentry** [comment]
Unfortunately though the telemetry shows the daemon restarting, it doesn't contain information as to why:

```
2021-09-24 06:37:53.610509601 +0200 +0200: magicsock: starting endpoint update (periodic)
2021-09-24 06:37:53.863896072 +0200 +0200: netcheck: report: udp=true v6=false mapvarydest=false hair=false ...
2021-09-24 06:38:02.27832173 +0200 +0200: LinkChange: minor
2021-09-24 06:39:12.79067618 +0200 +0200: logtail started
2021-09-24 06:39:12.790823941 +0200 +0200: Program starting: v1.14.3-t3a762776e-g75eaf27e5, Go 1.17-tsdd6b269c77: []string{"/volume2/@appstore/Tailscale/bin/tailscaled", "--state=/var/packages/Tailscale/etc/tailscaled.state", "--socket=/var/packages/Tailscale/etc/tailscaled.sock", "--port=41641"}
```

Note the 1+ minute gap between 06:38:02 and 06:39:12. tailscaled exited during that time, and then was restarted.

My guess would be being unable to allocate memory and being killed. DS3617xs has 16 Gigs, but it is mostly a question of what else might be consuming memory.

**Comment by traktuner** [comment]
Hello,
Is there any local log I can send you?
RAM is more than enough available. 12% used out of 48GB.
Also, version 1.12.1 is working very fine.
Thank you,
Thomas

**Comment by traktuner** [comment]
Hello,
Is there any local log I can send you?
RAM is more than enough available. 12% used out of 48GB.
Also, version 1.12.1 is working very fine.
Thank you!

**Comment by DentonGentry** [comment]
Can you look in /var/packages/Tailscale/var/tailscaled.stdout.log for anything that looks like a crash, segfault, out of memory, or other bad crash? It isn't getting sent to us in telemetry but may be in the local log file.

**Comment by traktuner** [comment]
Hey,
I already found the log and sent it to your support address.

**Comment by DentonGentry** [comment]
(no private information in the backtrace)

```
panic: call to ReSTUN before Start

goroutine 417 [running]:
tailscale.com/wgengine/magicsock.(*Conn).ReSTUN(0xc0001222c0, {0xac006e, 0x0})
	tailscale.com@v1.14.3/wgengine/magicsock/magicsock.go:2547 +0x3dc
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc00011e900, 0x0, 0xc00007e870)
	tailscale.com@v1.14.3/wgengine/userspace.go:1129 +0x3a8
tailscale.com/wgengine.NewUserspaceEngine.func1(0x0, 0x0)
	tailscale.com@v1.14.3/wgengine/userspace.go:282 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
	tailscale.com@v1.14.3/wgengine/monitor/monitor.go:328 +0x565
```

**Comment by bradfitz** [comment]
Oh, that's already fixed in the 1.4.x branch but untagged. And Start is gone in 1.6.x.

**Comment by maisem** [comment]
@traktuner Just published https://github.com/tailscale/tailscale-synology/releases/tag/v1.14.4. Can you please try that?

**Comment by traktuner** [comment]
@maisem 1.14.4 is working on all my Synology boxes - thank you for the quick fix!

**Comment by SuperMan-Lfj** [comment]
Issue still occurs on my DSM6, tailscale version is 60.
