### ISSUE TITLE
Move test state directories into a subdir of /tmp

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#2923]
We cannot currently return a proper `error` from `paths/ensureStateDirPerms` because some tests are using `/tmp` as the state directory. We go to `chmod` `/tmp`, that obviously fails, etc.

I'd like to tweak a few paths that we set up in our harnesses so that the state info is dumped into a subdirectory of `/tmp`, thus enabling successful `chmod`s and allowing me to fix that function to return errors.

**Comment by bradfitz** [comment]
Which test is failing? Got a log?

**Comment by dblohm7** [comment]
@bradfitz Linux VM tests that are triggered on pull request were failing on an earlier revision of the https://github.com/tailscale/tailscale/pull/2893 PR. 

Log showed failure `creating state directory: /tmp` due to the new `MkStateDir` failing because it couldn't chmod `/tmp`.

**Comment by bradfitz** [comment]
I can't find any failures. Can you paste either the failing test output or a URL to it?

**Comment by dblohm7** [comment]
```
dblohm7@localhost:~/src/tailscale$ go test tailscale.com/ipn
--- FAIL: TestFileStore (0.00s)
    store_test.go:102: creating file store failed: creating state directory: chmod /tmp: operation not permitted
FAIL
FAIL    tailscale.com/ipn       0.010s
FAIL
```

As manifested during PR:
https://github.com/tailscale/tailscale/actions/runs/1263259216
