### ISSUE TITLE
Relax chmod of server state directory

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2925]
As of 9ebb5d4205d50d54c1874b404b0a7d83cdaa77ca we now chmod the parent directory of the server-state.conf file to 0700.

But that means if a user runs:

```
$ tailscaled --tun=userspace-networking --state=$HOME/foo.state
```

... now we're doing chmod 0700 on their $HOME.

I think we should change that before release, to only chmod the parent if it's a directory we would've otherwise created. (easy heuristic: is the parent base named "Tailscale" or "tailscale" ?)

/cc @DentonGentry @dblohm7 @danderson

**Comment by DentonGentry** [comment]
Yeah, we should do something. /tmp is another common choice for some of the container systems.

**Comment by dblohm7** [comment]
Since I'm working on a follow-up for the perms thing, I might as well work this issue into that fix.
