### ISSUE TITLE
Add search domains for shared nodes

### ISSUE THREAD

**Issue by tomprince** [tailscale/tailscale#2929]
Since shared machines require using domain, tailscale should ensure that those domains will resolve, even if they are used as search domains.

**Comment by bradfitz** [comment]
I'm having a hard time understanding this bug title & body. Can you elaborate?

Can you give an example of something that doesn't work?

**Comment by tomprince** [comment]
If I have two accounts associated with domains `source.example` and `recipient.example`, and have shared a machine `shared.source.example` to a user in `@recipent.example`, I'd expect to be able to access that machine via `machine.source.example.beta.tailscale.net`. However, currently tailscale adds `recipient.example.beta.tailscale.net` as a search domain, and doesn't add `beta.tailscale.net` or `source.example.beta.tailscale.net` as match domains to the DNS configuration for the recipient machines.

**Comment by danielphan2003** [comment]
Is this also the case for tailnet https? I'm currently have to workaround this using DNS to resolves `*.domain-alias.ts.net` whenever I have to share an https node to other people.

**Comment by DentonGentry** [comment]
Not implemented yet as far as I can see. I see my own MagicDNS and HTTPS domains, not that of the node shared to the tailnet.

```
root@mc-survival:~# cat /etc/resolv.conf 
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search tails-scales.ts.net example.com.beta.tailscale.net
```

**Comment by bradfitz** [comment]
I think this is all done. We are explicitly not going to add the sharer's search domain(s) to the recipient. That can shadow short names of the recipient and is a security problem.

**Comment by DentonGentry** [comment]
I remember that now. It will look like this in `tailscale status`:
```
# tailscale status
100.104.59.4    server                       server.my-tailnet.test linux   -
100.119.117.66  server.other-tailnet.test.beta.tailscale.net        dgentry@       linux   idle; offers exit node
```

You'll need to use `server.other-tailnet.test.beta.tailscale.net`
