### ISSUE TITLE
Wrong domain in tailscale.io go-import meta tag

### ISSUE THREAD

**Issue by dmgk** [tailscale/tailscale#293]
Looks like `go-import` meta tag returned by tailscale.io has wrong domain and it breaks `go mod vendor`:

```
tailscale-0.97 $ go mod vendor
go: finding module for package tailscale.io/control
tailscale.com/control/controlclient tested by
        tailscale.com/control/controlclient.test imports
        tailscale.io/control: cannot find module providing package tailscale.io/control: unrecognized import path "tailscale.io/control": parse https://tailscale.io/control?go-get=1: no go-import meta tags (meta tag tailscale.com did not match import path tailscale.io/control)
```

```
$ curl -Lv https://tailscale.io/control?go-get=1
...
<head>
  <meta name="go-import" content="tailscale.com git https://github.com/tailscale/tailscale">
</head>
...
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686510253744) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
tailscale.io is our private git repo. Some of it wasn't cleaned up / detangled for release.

What are you trying to do?

Where are you trying to run `go mod vendor` and why?

**Comment by dmgk** [comment]
I found this while testing new tailscale FreeBSD port. `go mod vendor` is a step in creating a new port.

**Comment by DentonGentry** [comment]
I think this was resolved long ago, the FreeBSD port was published last year. I'm going to close this now, feel free to reopen if something remains to be done.
