### ISSUE TITLE
FR: Allow exposing HTTPS domain alias DNS entries to sharing recipients.

### ISSUE THREAD

**Issue by tomprince** [tailscale/tailscale#2930]
I want to be able to share HTTPS services with other users, which requires them using the tailscale domain alias to access the resource. This requires both updating 100.100.100.100 to be able to serve those records to sharing recipients, and configuring the domains as match domains when setting up DNS for the recipients.

**Comment by DentonGentry** [comment]
Similar to https://github.com/tailscale/tailscale/issues/3767 and https://github.com/tailscale/tailscale/issues/3756

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/3767 and https://github.com/tailscale/tailscale/issues/3756 are both resolved now via having the control server push entries to the sharee. I think that also resolves this feature request, please reopen if not.
