### ISSUE TITLE
Add tailscaled flag for server state directory, deprecate --state?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2932]
As background, two of `tailscaled`'s current flags are `--state=<file>` and `--socket=<file>`.

On a typical Linux system, they default to values:

```
  -socket string
        path of the service unix socket (default "/var/run/tailscale/tailscaled.sock")
...
  -state string
        path of state file; use 'kube:<secret-name>' to use Kubernetes secrets (default "/var/lib/tailscale/tailscaled.state")
```

Our systemd config explicit sets them to:

```
 --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock
```
 
On Synology they're currently set (from https://github.com/tailscale/tailscale-synology/blob/main/src/scripts/start-stop-status#L13) like:

`--state=/volume2/@appdata/Tailscale/tailscaled.state --socket=/volume2/@appdata/Tailscale/tailscaled.sock`

But tailscaled stores more than just a state file and a socket.

It also stores:

1. logtail keys, buffered logs
2. Taildrop-received files until they're received into a user directory
3. LetsEncrypt certs

Those three continue to be problematic. We don't have a great story on how we derive those paths. Sometimes we do it relative to the `--state` file, sometimes we use the parent directory of the `paths.DefaultTailscaledStateFile` (which caused #2927 where cert fetching doesn't work on Synlogy), etc. And it's caused problems like #2925, where we assume we owned the state file's parent, and had to add a heuristic about whether the parent directory was `"tailscale"` or `"Tailscale"`, which was gross.

So, proposal: we deprecate `--state` and instead add a flag for a directory, and plumb that explicit value around everywhere, rather than trying to derive it for those three things above.

Alternatively, redefine `--state` to either be a directory or, for compatibility, a file, in which case we define the directory derivation precisely: the parent directory must be named "Tailscale" (case insensitive) or it's a fatal error and tailscaled refuses to start. For instance, this would stop people in the future using `--state=$HOME/foo.state`, unless their $HOME base was `tailscale`.

/cc @crawshaw @danderson @maisem @DentonGentry @dblohm7

**Comment by danderson** [comment]
SGTM, either adding --statedir, or amending --state's behavior to deterministically give us a whole directory to play with.
