### ISSUE TITLE
Unable to use tailscaled on read-only filesystem

### ISSUE THREAD

**Issue by mdevaev** [tailscale/tailscale#2934]
The current release broke run on a read-only filesystem on embedded Linux. Previous releases (like 1.12.0) worked fine, but I can't say from which version it broke.

Previously, it was possible to use the following algorithm:
1. Remount the file system to RW.
2. Run the tailscaled daemon.
3. Perform tailscaled up
4. Reboot.
5. After a reboot, the entire root file system becomes read-only (this is a feature of our distribution), but tailscale worked fine.

The new version has completely broken this use case.
1. At startup, it tries to make a [`chmod /var/lib/tailscale`](https://github.com/tailscale/tailscale/blob/21e9f98fc12d767c2408195da19d9893f9de9224/paths/paths_unix.go#L65) and if this did not work, it refuses to continue working.
2. The log1 and log2 files are also written in /var/lib, but there is no way to place them somewhere else in the directory. Could you please move them to /var/log or provide an option that does this - this location is usually mounted in tmpfs on embedded Linux systems. Logs in /var/lib also violate the FHS standard.

At the moment, tailscale is actively used by [PiKVM](https://github.com/pikvm/pikvm/blob/master/pages/tailscale.md) as a recommended method of cloud access. Updating to a new version breaks access to user's devices.

**Comment by srepac** [comment]
version 1.14.0-1 tailscale doesn't have the issue reported here.

Here's the md5sum and file info for the previous working tailscale package for reference:
```
# md5sum tailscale-1.14.0-1-armv7h.pkg.tar.xz
8bd53995127f74f34a27a632c8097dd0  tailscale-1.14.0-1-armv7h.pkg.tar.xz

# ls -l tailscale-1.14.0-1-armv7h.pkg.tar.xz
-rw-r--r-- 1 root root 4803728 Aug 24 13:06 tailscale-1.14.0-1-armv7h.pkg.tar.xz
```
I hope this helps to resolve the issue.

**Comment by srepac** [comment]
Here's proof that tailscale down and up works with readonly FS of pikvm using the 1.14.0 version

```[root@usbkvm ~]# mount | grep mmc
/dev/mmcblk0p2 on / type ext4 (rw,relatime)
/dev/mmcblk0p3 on /var/lib/kvmd/msd type ext4 (ro,nosuid,nodev,noexec,relatime,nodioread_nolock,nodelalloc,errors=remount-ro,data=journal)
/dev/mmcblk0p1 on /boot type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
[root@usbkvm ~]# tailscale down
[root@usbkvm ~]# tailscale up
[root@usbkvm ~]# tailscale status
100.66.x.x    usbkvm               ```

**Comment by DentonGentry** [comment]
That happened in https://github.com/tailscale/tailscale/pull/2926. The permission setting is pretty important for Windows but not as necessary for Linux, we can look at changing that.

**Comment by mdevaev** [comment]
As far as I understand, logging was not a problem before. Apparently, logging errors were ignored, I don't have an old package to check this now. In any case, it would be great if there was some kind of option to disable logs.

**Comment by srepac** [comment]
Logging worked on read only file system before because tailscale actually used /var/log (which is a tmpfs mount in pikvm).  I believe the newest version moved the logs to /var/lib instead as per the issue reported.

```
[root@usbkvm ~]# df -h /var/log
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           845M  8.0K  845M   1% /var/log

```

**Comment by mdevaev** [comment]
Oh my :(

**Comment by srepac** [comment]
Well this is interesting.  version 1.14.0 is fine creating the log1 and log2 files in /var/lib/tailscaled/  
```
[root@usbkvm tailscale]# pwd
/var/lib/tailscale
[root@usbkvm tailscale]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  3.9G  2.8G  958M  75% /
[root@usbkvm tailscale]# ls -l
total 16
drwx------ 3 root root 4096 May 17 10:56 files
-rw------- 1 root root  209 Mar 20  2021 tailscaled.log.conf
-rw------- 1 root root    0 Sep 26 05:20 tailscaled.log1.txt
-rw------- 1 root root  558 Sep 26 05:20 tailscaled.log2.txt
-rw------- 1 root root 1184 Sep 26 05:17 tailscaled.state
[root@usbkvm tailscale]# cat tailscaled.log2.txt
{"logtail": {"client_time": "2021-09-26T05:20:18.815898924-07:00"}, "text": "dns: [rc=unknown ret=dns.directManager]\n"}
{"logtail": {"client_time": "2021-09-26T05:20:18.816996109-07:00"}, "text": "dns: using dns.directManager\n"}
{"logtail": {"client_time": "2021-09-26T05:20:18.817146959-07:00"}, "text": "flushing log.\n"}
{"logtail": {"client_time": "2021-09-26T05:20:18.817206291-07:00"}, "text": "logger closing down\n"}
{"logtail": {"client_time": "2021-09-26T05:20:19.142013466-07:00"}, "text": "logtail: dialed \"log.tailscale.io:443\" in 320m
s\n"}
[root@usbkvm tailscale]# date
Sun Sep 26 05:41:54 PDT 2021
[root@usbkvm tailscale]# uptime
 05:41:56 up 21 min,  1 user,  load average: 0.21, 0.19, 0.18
```  
As you can see, the tailscale.log1 and log2.txt files were created around boot time in /var/lib.  The log files will not get updated after boot due to read-only FS, but yes, the issue was introduced in tailscale 1.14.4

**Comment by DentonGentry** [comment]
We have withdrawn 1.14.4 from further distribution on Linux platforms.

It will continued to be distributed for Windows, Synology, macOS, and iOS.
The Android 1.14.4 release hadn't been built yet.

**Comment by mdevaev** [comment]
Thanks! Please make it possible in the next release to disable logs and not set access rights.

**Comment by bradfitz** [comment]
I see no changes to logging on Linux between 1.14.3 and 1.14.4. The logging files in /var/lib/tailscale are no traditional Linux log files; they're buffered logs that get uploaded to Tailscale for debugging. So the FHS isn't exactly applicable. In any case, changes to its behavior seem unrelated to this bug. I suggest opening a separate bug about that, unrelated to 1.14.x.

I sent https://github.com/tailscale/tailscale/pull/2935 to skip the Chmod if `/var/lib/tailscale` already has the right permissions. I assume that'll work for you? You can fix it to 0700 once before you remount the filesystem read-only?

**Comment by mdevaev** [comment]
>  I assume that'll work for you? You can fix it to 0700 once before you remount the filesystem read-only?
Yes, of course. Thank you.

> The logging files in /var/lib/tailscale are no traditional Linux log files; they're buffered logs that get uploaded to Tailscale for debugging. So the FHS isn't exactly applicable.
FHS does not describe the format of logs, they can be any. For example, journal puts its binary logs in /var/log. Your logs are even text, so they belong there. However, I do not insist. For read 0-only, you need a way to either move them somewhere from /var/lib, or disable them altogether.

> I suggest opening a separate bug about that, unrelated to 1.14.x.
Sure: #2936

**Comment by mdevaev** [comment]
Also please change default permissions here: https://github.com/tailscale/tailscale/blob/ac07ff43bf534e5d2c2d3d8a2f18723a615b65ff/cmd/tailscaled/tailscaled.service#L18

**Comment by mdevaev** [comment]
If possible, please make a new release including this fix as soon as possible. This is necessary for arch linux maintainers.

**Comment by bradfitz** [comment]
Tailscale 1.14.6 is out with these changes.

**Comment by mdevaev** [comment]
Thanks!

**Comment by thesuperzapper** [comment]
There is one big issue still remaining which needs to be upstreamed into `tailscale-pikvm` or at least documented in [the tailscale docs for using with pikvm](https://tailscale.com/docs/integrations/pikvm#use-tailscale-serve-to-access-your-pikvm-device).

Specifically you CANT use `tailscale serve` without being blocked by lets-encrypt for making too many requests.

See this issue for a workaround (with tempfs mount), which could be added to the docs, or included in the package (or we make `tailscale-pikvm` swap from ro to rw when updating the cert):
- https://github.com/tailscale/tailscale/issues/17028
