### ISSUE TITLE
Option to move logs from /var/lib or disable it at all

### ISSUE THREAD

**Issue by mdevaev** [tailscale/tailscale#2936]
Following #2934. In order for tail scale to be used on a read-only filesystem on embedded Linux, we need the option to disable logs or the ability to move them somewhere else, for example in /var/log/tailscale.

**Comment by bradfitz** [comment]
From #2934, you say it's a regression from 1.14.3. But I see no changes to logging in 1.14.4.

Does 1.14.3 work on a read-only filesystem?

**Comment by bradfitz** [comment]
Also, if you set the environment variable `STATE_DIRECTORY`, then `tailscaled` will store its log upload buffered logs there. Does that work for you?

**Comment by bradfitz** [comment]
Actually, STATE_DIRECTORY probably explains the confusion about logs.

I bet you were originally running under systemd. Then you hit the chmod problem and tried to debug by hand outside of systemd, but then you didn't have STATE_DIRECTORY set (which systemd 240+ sets) so logs went to a different place and you hit what you thought was a second problem with 1.14.4, but was actually just it configuring itself differently based on the different environment.

Does that sound like what happened?

**Comment by mdevaev** [comment]
> From #2934, you say it's a regression from 1.14.3. But I see no changes to logging in 1.14.4.

I didn't say about 1.14.3, but...

> Does 1.14.3 work on a read-only filesystem?

Yes, I've just tested it. It looks like you were right about the state directory. Logging is disabled if the files are not writable. For me, this is acceptable behavior if it continues to work like this. But I would still recommend making settings for placing logs in another place. Of course, this remains at your discretion. Thank you for helping me figure it out.

**Comment by DentonGentry** [comment]
Tailscale 1.32 added a `--no-logs-no-support` argument to tailscaled to disable upload altogether.

**Comment by Fuseteam** [comment]
i ran into this on a readonly rootfs, after enabling tailscale to start on boot

i seems to work after chowning the state directory to my user

it should be noted that i had configured the state directory to be in `~/.local/state`.

**Comment by Fuseteam** [comment]
seems that even if i pass 

```
--state=/home/phablet/.local/state/tailscale/tailscaled.state --statedir=/home/phablet/.local/state/tailscale
```

i still get
```
tailscaled.service: Failed to set up special execution directory in /var/lib: Read-only file system
```

This is my current systemd service file:
```
[Unit]
Description=Tailscale node agent
Documentation=https://tailscale.com/kb/
Wants=network-pre.target
After=network-pre.target NetworkManager.service systemd-resolved.service

[Service]
EnvironmentFile=/home/phablet/.config/crackle/default/tailscaled
ExecStartPre=/home/phablet/.local/sbin/tailscaled --cleanup
ExecStart=/home/phablet/.local/sbin/tailscaled --state=/home/phablet/.local/state/tailscale/tailscaled.state --statedir=/home/phablet/.local/state/tailscale --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS
ExecStopPost=/home/phablet/.local/sbin/tailscaled --cleanup

Restart=on-failure

RuntimeDirectory=tailscale
RuntimeDirectoryMode=0755
StateDirectory=tailscale
StateDirectoryMode=0700
CacheDirectory=tailscale
CacheDirectoryMode=0750
Type=notify

[Install]
WantedBy=multi-user.target
```

**Comment by Fuseteam** [comment]
found it: looks like i needed
```
StateDirectory=
```
