### ISSUE TITLE
Force DERP connection

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2937]
Is there a way to force a connection from point A to point B, through DERP relay C?

A---C--->B
instead of:
A-------->B

Right now I even put in UDP block rules for 41641 to inbound on B, and outbound on A to IP B. Why is it still trying direct connections? I think your NAT traversal technology is too good, I can't even seem to block it.

**Comment by vysecurity** [comment]
Added more IPTables rules, fixed. But would be good to know if there's a better way to handle connection routes.

**Comment by vysecurity** [comment]
Ok, issue returned. Firewall rules unchanged. Maybe this NAT Traversal magic is too good. Is blocking 41641 alone not enough?

**Comment by bradfitz** [comment]
Sorry, DERP isn't supposed to be multi-hop or onion routed. That's not something we're likely to add anytime soon.

If you're getting direct connections instead of DERP, it sounds like everything is working as intended.

**Comment by vysecurity** [comment]
Got it.
