### ISSUE TITLE
Architecture documentation for Synology packages

### ISSUE THREAD

**Issue by KevinGaudin** [tailscale/tailscale#2939]
Hi,

I'm happy to see new 1.14 releases coming to https://github.com/tailscale/tailscale-synology/releases, though there are now less build variations for all CPU architectures.

For example, I'm using a DS715 which was using the 'alpine' build but this build is not available anymore.

I did some research and tried to install the armv7 package after reading this : https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures
It worked, but ideally an update of the documentation page related to Synology versions or just using this link as the reference would help.

Thanks a lot for the great work on Tailscale !

Kevin

**Comment by DentonGentry** [comment]
Tracking this in https://github.com/tailscale/tailscale/issues/3925
