### ISSUE TITLE
Easy unattended installations, for example with Ansible

### ISSUE THREAD

**Issue by jjo93sa** [tailscale/tailscale#294]
**Is your feature request related to a problem? Please describe.**

I would like to have unattended installations of Tailscale, which don't seem possible at the moment.

**Describe the solution you'd like**

Currently, the last step for installing and starting Tailscale is to run `tailscale up`. This command blocks until the URL presented in the shell is visited. This makes unattended installations, for example bringing up multiple clients from an Ansible play, difficult. It would be nice to have a form of command that would automatically register the client with the server:

`tailscale up <unique-server-url>`

**Describe alternatives you've considered**

Clearly, security is a concern. Perhaps a separate url could be pre-generated on the admin console for each new client ahead of installing them? Or the server url would only be valid for hosts with a particular name?

Another possibility would be to make the process more asynchronous by outputting the current text, but backgrounding the process that waits for the registration. (I'm assuming here that Ansible would then return the text as stdout and I could parse it for the URL.)

**Additional context**

I think that just about covers it.

**Comment by bradfitz** [comment]
Is this a dup of #270?

We do have a new auth token system rolling out now.

**Comment by jjo93sa** [comment]
@bradfitz Apologies, #270 does seem to have morphed into a similar suggestion, starting from a different point (having the same installation mechanism across multiple O/S). Happy for you to close this one if it helps.

**Comment by bradfitz** [comment]
Yeah, let's close. It'll happen regardless. (It's mostly already done but not documented) No need to have near identical bugs open for it.

**Comment by jjo93sa** [comment]
Close as duplicate of #270
