### ISSUE TITLE
Auto disable the Tailscale while detected the home network.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2943]
The user requested the feature :

`It would be terrific if there was an option in the mobile app to automatically disable the VPN while on configured and trusted home WiFi network. This could save a bit more on the battery and the private network is available at home! :)`

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3l5xt)

**Comment by bradfitz** [comment]
Dup of #1227, etc?

**Comment by DentonGentry** [comment]
Duplicate of #1227

**Comment by taisph** [comment]
The Google VPN on Pixel app simply disables the VPN on user selected SSIDs. #1227 seems a lot more complex than necessary to solve the feature request here.
