### ISSUE TITLE
Tailscale not working after Synology DSM upgrade 6 -> 7.0.1

### ISSUE THREAD

**Issue by traktuner** [tailscale/tailscale#2960]
Hello,
after upgrading my DS3617xs from DSM 6 to DSM 7.0.1, outgoing Tailscale connections are not possible.
Before the upgrade I uninstalled the DSM 6 package and after upgrading I installed the DSM 7 package.
even pinging another Tailscale device does not work - ingoing pings do work.
I've sent the log from /var/packages/Tailscale/var/ and my IP/user to your support address.
Thank you!

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3m0up)

**Comment by traktuner** [comment]
Additional infos:
sudo tailscale status shows all devices correctly, netcheck also ok

**Comment by maisem** [comment]
@traktuner DSM7 changed the way packages work, this interferes with the way tailscale is setup. We have a fix for this pending release in the Synology Package Center. However, if you'd like to work around it please see https://tailscale.com/kb/1152/synology-outbound/

**Comment by traktuner** [comment]
Great, thank you very much! Outgoing connections are working now with the latest Tailscale version from GitHub.
