### ISSUE TITLE
Allow configuration of login server on iOS and MacOS distributions

### ISSUE THREAD

**Issue by wpeckr** [tailscale/tailscale#2965]
It is [mentioned by a contributor ](https://news.ycombinator.com/item?id=28573354) that it is possible to configure the iOS client using MDM profiles to use a different login server (such as on premises, self hosted headscale master), but there's no documentation for how to do this anywhere public.

It would be substantially more convenient if it were a (even hidden hidden) option that a determined end user could reach without using MDM. The MacOS version does have a alt menu which allows for selection, but not configuration of a different master. Close, but no dragons here. 

<img width="588" alt="r" src="https://user-images.githubusercontent.com/60858013/135323357-3f823ada-65b5-415a-980d-6e6e7491c386.png">

**Comment by wpeckr** [comment]
Is the key for MDM configuration on iOS documented anywhere?

**Comment by DentonGentry** [comment]
On MacOS:
`defaults write io.tailscale.ipn.macos ControlURL -string "https://controlplane.example.com"`
and restart the Tailscale app.

To undo this later if needed:
`defaults delete io.tailscale.ipn.macos ControlURL`

--------

For iOS, the MDM support is mostly present but not fully working. We don't currently send iOS devices to alternate coordination servers.

**Comment by fdelucchijr** [comment]
I think this issue should keep open until all apple clients supports MDM 🤔
