### ISSUE TITLE
FR: get notification when Linux tailscaled receives files

### ISSUE THREAD

**Issue by fr233** [tailscale/tailscale#2968]
I‘m currently writing a gnome shell extension and a nautilus plugin which provide an indicator and a menu for taildrop. (although I haven't upload it to github or extension.gnome.org or somewhere)
The file sending function works fine, you can right click some files and click the menu item to send it, and the indicator provide a popup menu, showing the files you are sending (of course you can click the cancel button to cancel it), had sent and send failed.

This extension work by calling tailscale(1) cmd.

Now I want to add one more function to my extension:  show a notification when tailscaled is start receiving files and receive had completed.  

Solved, Thanks @bradfitz

**Comment by bradfitz** [comment]
Have you seen `tailscale file get --wait <dir>` ?

**Comment by fr233** [comment]
> Have you seen `tailscale file get --wait <dir>` ?

Oh thanks, I didn't see it the day before yesterday.

**Comment by bradfitz** [comment]
There' a lower-level unix socket mechanism you can use instead of shelling out to that command, but it's not as stable of an interface. I'd recommend using that CLI command for now until we have a documented stable localhost HTTP interface for it.

**Comment by DentonGentry** [comment]
I think `tailscale file get --wait <dir>` is sufficient for this, at least for a while.
