### ISSUE TITLE
Tailscale and k3s don't play nice together

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#297]
Tracking bug to figure out teething issues with running k3s and tailscale together, using Tailscale to provide a secure inter-node mesh for Kubernetes traffic.

Setup: bring up a k3s cluster on Ubuntu, with one controller and a couple of nodes. Install tailscale on all of them, and edit k3s's systemd unit to add `--flannel-iface tailscale0` to all nodes. This'll make k3s use the Tailscale mesh for inter-node traffic, which is swanky.

Probably need to adjust MTUs on tailscale0, k3s does vxlan which doesn't play well with our default MTU settings.

Main problem is that restarting tailscaled breaks the k3s overlay network. My suspicion is that flannel doesn't like it when tailscale0 vanishes then comes back, and doesn't correctly restore routes it had configured - but I have no proof.

In the other direction, restarting k3s seems to make tailscaled spin and consume all the CPU, for reasons not obvious. May be worse on 0.97-45 than on the latest unstable, but we have reports of it happening with both versions.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686400769930) by [Unito](https://www.unito.io/learn-more)

**Comment by damomurf** [comment]
Technically speaking (I've been chatting to Dave about this) - just a controller and single agent node is enough to replicate. The controller itself runs pods that require the CNI to be able to route stuff properly over tailscale0.

**Comment by damomurf** [comment]
After trying out 0.98.0~331 (on ubuntu) that fixes Docker routing to the Tailscale network, this is all now working happily for me. I have k3s configured to use tailscale0 as the flannel interface and its working very nicely.

Feel free to close from my perspective.

**Comment by damomurf** [comment]
As requested by dave, output of iptables:

iptables -L -n -v:
https://gist.github.com/damomurf/0c5c748f7f095f17f2d3f216a974cf7f

iptables -L -n -v -t nat
https://gist.github.com/damomurf/dc9e74cfd5ad8f434217448d306717be

**Comment by apenwarr** [comment]
Awesome! Thanks for letting us know.

**Comment by thdxr** [comment]
I'm continuing to see issues issues with nodes losing network until I restart the k3s agents

**Comment by DentonGentry** [comment]
I think the specific issue discussed in this bug a year ago is resolved, what you're running into is possibly something else. Could you open a new issue, and include as much detail as you can about symptoms or errors being logged?
