### ISSUE TITLE
Android: detect ChromeOS specifically

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2971]
Currently we can only do stats on ChromeOS usage by looking at the device_model field ("Google Dell Latitude 5400 Chromebook Enterprise") and hope that it contains "Chomebook".

It'd be nicer to have a boolean to definitively tell us whether an Android device is ChromeOS.

https://stackoverflow.com/questions/39784415/how-to-detect-programmatically-if-android-app-is-running-in-chrome-book-or-in contains some heuristics.

There's no great field in ipn.Hostinfo to put this now, but we could just prepend it to DeviceModel. So instead of:

```
Google Dell Latitude 5400 Chromebook Enterprise
```

We can set it to:

```
ChromeOS: Google Dell Latitude 5400 Chromebook Enterprise
```

/cc @eliasnaur @mayakacz @crawshaw

**Comment by DentonGentry** [comment]
I think this will do it: https://github.com/tailscale/tailscale-android/pull/20

I have a Chromebook where I've loaded the Android app from the Play store. I have to figure out how to sideload it to be able to test it.

Honestly even if I can't get it sideloaded, it is probably still fine to go in. Elias had already developed an isChromeOS() function to work around a difference in behavior in VpnService.Builder.addDnsServer:
```
        boolean isChromeOS() {
                return getPackageManager().hasSystemFeature("android.hardware.type.pc");
        }
```

**Comment by eliasnaur** [comment]
> I have a Chromebook where I've loaded the Android app from the Play store. I have to figure out how to sideload it to be able to test it.
> 

I ended up unlocking the Chromebook, enabling its builting Linux support and develop from that. `adb install` automatically targets the host.
