### ISSUE TITLE
Can't login in android devide

### ISSUE THREAD

**Issue by chemuki205** [tailscale/tailscale#2974]
Since 2 days ago it was not possible to log in from an android device, it is allowed to select the google account but it does not register correctly while remaining on the login screen

Device: Redmi 4
OS version: 6.0.1
Tailscale version: latest stable / beta

**Comment by SirNoish** [comment]
Hello, I have the same problem as chemuki205, for 2 days I have tried to log in and it does not load anything, nor does it give any error, the screen simply blinks for a second and nothing more.

Device: OnePlus 3
OS version: 6.0.1
Tailscale version: 1.15.196-t173bbaa1a-g0637d599af4

**Comment by DentonGentry** [comment]
We released 1.15.210 on the Open Testing track this morning.
I've tested it on a Nexus 7 running Android 6.0.1.

**Comment by DentonGentry** [comment]
I'm going to close this as 1.15.210 should work on Android 6.0.1, please reopen if issues remain.

**Comment by chemuki205** [comment]
Checked, it works properly :)
