### ISSUE TITLE
Windows: failure in populateTrayLocked

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2975]
Tailscale did not immediately start after install on windows 11. Following errors are reported.

![image](https://user-images.githubusercontent.com/75628398/135631768-d6411382-111b-4c07-8c0d-b97cd06d3940.png)

![image](https://user-images.githubusercontent.com/75628398/135631822-0aedd08f-92a9-48bc-a370-650861b5feff.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3mgup)

**Comment by bradfitz** [comment]
Dup of #1073.
