### ISSUE TITLE
Support authentik as an identity provider

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2979]
https://goauthentik.io/ is an on-premises OIDC provider. It requires at least one implementation quirk, the .well-known URL is not at the usual well-known location: https://auth.example.com/application/o/tailscale/.well-known/openid-configuration

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3mij5)

**Comment by bradfitz** [comment]
That `/.well-known` location does not [give me warm fuzzies](https://twitter.com/bradfitz/status/1042093411287932930).

**Comment by catzkorn** [comment]
Closing this issue - using Authentik as an identity provider is now supported via [custom OIDC](https://tailscale.com/kb/1240/sso-custom-oidc/)
