### ISSUE TITLE
Magic DNS records for SSHFP

### ISSUE THREAD

**Issue by tedb** [tailscale/tailscale#2987]
It would be amazing if Tailscale's Magic DNS were to publish SSH fingerprint records for nodes, in the form of SSHFP records.  This would enhance the security of the initial SSH connection between two nodes, by allowing the host fingerprint to be discovered by DNS.  In practice, I suspect most people probably just blindly trust that the presented host fingerprint is correct.

An SSH client can fetch a host's keys from DNS via the `VerifyHostKeyDNS` option, as in:

`ssh -o "VerifyHostKeyDNS ask" host.example.com`

Would it make sense for Magic DNS to obtain these fingerprints by integrating with the "Services" detection of an SSH listener?

More information:
https://en.wikipedia.org/wiki/SSHFP_record
https://man.openbsd.org/ssh#VERIFYING_HOST_KEYS
https://man.openbsd.org/ssh-keyscan.1
https://linux.die.net/man/1/sshfp

**Comment by danderson** [comment]
Yes, this could make sense to do. I don't know when we'll get to it, as I don't _think_ the service list is quite flexible enough to carry additional metadata between nodes beyond port numbers, but making this work would be a nice quality of life thing for SSH sessions. Thanks for suggesting!

**Comment by qbit** [comment]
For this to be useful wouldn't you also need DNSSEC to be in place?

**Comment by danderson** [comment]
No, because MagicDNS serves records directly from your local machine, without going out to the network. We can rely on the existing secure connection between tailscale devices and the tailscale control plane to carry the fingerprints between machines. This does mean you have to trust the tailscale control plane, but that's already the case (and we're working on options to make that problem go away in general)

**Comment by DentonGentry** [comment]
Since this bug was filed, the Tailscale SSH feature was introduced: https://tailscale.com/blog/tailscale-ssh/
This provides a different mechanism to be certain of the node being connected to.

**Comment by sixcorners** [comment]
Even with tailscale ssh it still prompts you with the whole "The authenticity of host x can't be established." message. I kind of wish that SSHFP records could still be added but for that to work I think you need DNSSEC and that seems kind of weird in this case.
