### ISSUE TITLE
DS Cam mobile push notifications while disconnected from Tailscale

### ISSUE THREAD

**Issue by HopeSilent** [tailscale/tailscale#2995]
I am receiving mobile push notifications on LTE despite being disconnected from my tailscale network.

Phone: Pixel 5
Android version: 11, build number RQ3A.210905.001
Tailscale version: 1.14.6-tdfc4042ec-gb1b53ce7b58
App: DS Cam, version 3.5.0

Synology NAS: DS718+
DSM version: DSM 7.0-41890
Tailscale version: 1.12.4-2006

Tailscale on the NAS is configured to advertise my internal subnet (192.168.1.0/24).

I am unable to login when I open the app, I also do not receive preview images in the notifications like I do when tailscale is enabled. I have replicated the issue on another android phone in my household, a Samsung Galaxy S10E.

I'm not sure why I would be receiving anything if tailscale is off, the NAS is not configured in any way for remote access other than via tailscale.

**Comment by bradfitz** [comment]
This sounds like it's all working as expected.

DS Cam doesn't send push notifications to your phone via Tailscale in any case; it always sends them via Google. So even if Tailscale is off, both DS Cam and your phone can talk to Google and get the camera push notifications. The previews don't load, though, when you're not connected to Tailscale, as those are apparently generated on-device referencing a direct URL to your camera.

**Comment by HopeSilent** [comment]
Well, I'm obviously out of my depth with regards to the way push notifications work on android. I assumed the android push notification was an open API of sorts but that the network side was still dependent on your configuration, clearly I was wrong. Sorry to have taken your time, thanks for explaining how it works!
