### ISSUE TITLE
Knowledge base is mangling double hyphens in install docs to ndash entities

### ISSUE THREAD

**Issue by eeeple** [tailscale/tailscale#300]
**Describe the bug**
Instructions for enabling tailscale on openSUSE Tumbleweed state:
`sudo systemctl enable –now tailscaled`
_-now_ is not recognized on the latest Tumbleweed.

**To Reproduce**
1. Go to https://tailscale.com/download/linux/opensuse-tumbleweed
2. Follow instructions
3. See error on 

> 3- Use systemctl to enable and start the service 

**Expected behavior**
Should enable and start tailscale service

**Screenshots**
![image](https://user-images.githubusercontent.com/2037523/79320180-aa7d6800-7f09-11ea-8216-d742e28664e7.png)

**Version information:**
 - Device: PC
 - OS: openSUSE Tumbleweed
 - OS version: 
```
maxren@stroustrup:~|⇒  cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20200413"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20200413"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20200413"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"
```

 - Tailscale version:
```
maxren@stroustrup:~|⇒  sudo zypper info tailscale
[sudo] password for root: 
Loading repository data...
Reading installed packages...


Information for package tailscale:
----------------------------------
Repository     : Tailscale stable                                                                
Name           : tailscale                                                                       
Version        : 0.97.0-45                                                                       
Arch           : x86_64                                                                          
Vendor         :                                                                                 
Installed Size : 22.8 MiB                                                                        
Installed      : Yes                                                                             
Status         : up-to-date                                                                      
Source package : tailscale-0.97.0-45.src                                                         
Summary        : The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO
Description    :                                                                                 
    The easiest, most secure, cross platform way to use WireGuard + oauth2 + 2FA/SSO

```

**Additional context**
Should split enable and start service

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686311778318) by [Unito](https://www.unito.io/learn-more)

**Comment by danderson** [comment]
Oops, that should say `--now`, I'll fix the articles. Can you confirm that `systemctl enable --now tailscaled` works?

**Comment by eeeple** [comment]
Hi @danderson. Yup, that'll do the trick `with --now`.
Thanks a lot.

**Comment by eeeple** [comment]
By the way, it seems that it affects also the following linux guides:

- Amazon Linux 2
- Arch
- CentOS 7 & 8
- Fedora
- OpenSUSE (all)
- RHEL8

**Comment by bradfitz** [comment]
@rosszurowski, @apenwarr, I confirmed that this problem is because the Python knowledge base HTMLifier code is mapping double hyphen into `&ndash;` in the API handler:

```
$ curl  --silent https://tailscale.com/api/kb?id=install-amazon-linux-2 | jq -r .content | grep add-repo
  <pre><code class="language-bash">sudo yum-config-manager &ndash;add-repo https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo
```

It's correct on disk and confirmed not a caching issue. (If I modify the Markdown file directly on the server it shows up right away on a browser release 🤠)

**Comment by rosszurowski** [comment]
Oh shoot — I recently enabled Smartypants to correct some typographic issues with our docs, but usually it's smart enough not to touch code blocks. I'll fix this.

**Comment by bradfitz** [comment]
Thanks. If you add it back, let's add some regression tests.

(I've been meaning to add some tests to the full web stack now that we have the Dockerfile.)

**Comment by rosszurowski** [comment]
I've removed Smartypants for now, and these instructions should now be fixed ([example](https://tailscale.com/download/linux/amazon-linux-2)).

Agree about the testing. I'll look into that today.

**Comment by apenwarr** [comment]
looks fixed.
