### ISSUE TITLE
util/groupmember: delete package once we use Go 1.18

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3001]
The util/groupmember package will become redundant once we have:

https://github.com/golang/go/commit/30faf968b1f348e944db3bde24c13462125007b1

... in our tree.

Either via Go 1.18 or cherry-picking it into tailscale/go.

/cc @maisem @josharian

**Comment by DentonGentry** [comment]
I believe we've switched to Go 1.18 now.

**Comment by bradfitz** [comment]
@maisem, want to delete your old code? :)
