### ISSUE TITLE
Windows: enable tailscaled to be able to look for backed-up copies of machine config info

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#3011]
In support of our efforts to recover from Windows upgrades clobbering our pre-1.14.4 data, it would be good if we could attempt to restore that data from system restore points.

**Comment by DentonGentry** [comment]
I think at this point, we're not going to finish this effort. The steps to move AppData to C:\ProgramData\Tailscale proved sufficient to head off the issue.
