### ISSUE TITLE
doc: document in KB how to enable DERP client restrictions

### ISSUE THREAD

**Issue by gdtv** [tailscale/tailscale#3024]
I followed this  documentation to build my custom DERP server: https://tailscale.com/kb/1118/custom-derp-servers/

I have a question, It seems no authentication on custom DERP server, so anyone who knows the IP of my server can use my custom DERP server for his tailscale private network, He only need to add this code to his Access Controls:
```
  "derpMap": {
    "Regions": { 
      "900": {
        "RegionID": 900,
        "RegionCode": "a",
        "Nodes": [{
            "Name": "a1",
            "RegionID": 900,
            "IPv4": "the IP of my custom DERP server"
        }]
      }
    }
  }
```

How to make my custom DERP server more safer?

**Comment by zhbrcn** [comment]
> Ah, I guess we didn't document that.
> 
> If you run `derper --help` you'll see:
> 
> ```
>   -verify-clients
>         verify clients to this DERP server through a local tailscaled instance.
> ```
> 
> You need to run tailscaled and derper on the same machine and then run derper with that flag and it'll restrict access.
> 
> I'll keep this bug open for documentation.

Hello:
I have tailscale and DERP on the same instance, and they works good.
But when I try to add  "-verify-clients" flag to start DERP,  the log keeps saying `"rejected: failed to query local tailscaled status: key hex string doesn't have expected type prefix nodekey:"`,don't know the reason why.
(system:debian11,tailscale runs on :5**** port)

**Comment by DentonGentry** [comment]
@danderson is this possibly related to the key type refactoring in `main` ?

@zhbrcn `git checkout release-branch/1.16` may allow you to build to get your custom DERP into service, while we fix `main`

**Comment by A1pha2er0** [comment]
If I use docker to deploy a derper instance，so how to define 'same machine' to verify the clients? Is it OK to enable the tailscale client out of the docker?

**Comment by DentonGentry** [comment]
derper uses the tailscaled localapi for this. tailscaled would need to be running within the container.
