### ISSUE TITLE
[FR]: Allow tailscale applications to follow symbolic links for (some) directory transversal

### ISSUE THREAD

**Issue by marcb** [tailscale/tailscale#3039]
### Tell us about your idea!

Allow for redirecting tailscale applications to other directories without having to patch / rebuild from source

### What are you trying to do?

While exploring [Erase your darlings](https://grahamc.com/blog/erase-your-darlings) approach to configuring a nixos host I tried the following approach.

```nix
services.tailscale.enable = enable;
systemd.tmpfiles.rules = [
   "L /var/lib/tailscale - - - - /persist/var/lib/tailscale"
];
systemd.services.tailscaled.after = [ "systemd-tmpfiles-setup.service" ];

```

After a lot of troubleshooting I discovered that `tailscaled` & `tailscale` don't seem to like following symbolic links…either during the `--cleanup` phase or when running.

### How should we solve this?

I understand that unbridled following of symbolic links can be a security issue, but in this case it would be good to be able to (selectively or via an option) allow following symbolic links.

Since NixOS utilises symbolic links to much it would be good that at least on that OS the above configuration could be supported, as it can for many other daemons.

### What is the impact of not solving this?

Right now I have explicitly mounted a ZFS file system on `/var/lib/tailscale` as a work-around. The only other approach I can think of is to patch / build the package with overridden paths or run the daemon (and command line) in a container...

**Comment by DentonGentry** [comment]
I am declining to implement this feature request.

**Comment by jlmeeker** [comment]
@marcb I was recently looking for a way to do this and came up with another solution that doesn't require any changes.  Posting it here for others looking for help.
`
  fileSystems."/var/lib/tailscale" = {
    device = "/persist/var/lib/tailscale";
    options = [ "bind" ];
  };
`

**Comment by marcb** [comment]
@jlmeeker yes, a great option. I settled on that approach with the addition of `noCheck = true;`. The hardest part about `systemd` is finding out all the capabilities it has…
