### ISSUE TITLE
Renaming device name in control panel breaks Magic DNS for Linux client 1.16.0

### ISSUE THREAD

**Issue by gwillem** [tailscale/tailscale#3042]
### What is the issue?

After editing my laptop machine name in the TS control panel and opening my laptop in a different location (uplink/wifi network):

- My laptop traffic is still routed through the configured exit node
- Magic DNS no longer works on the laptop (normal DNS does) 
- The Tailscale control panel shows my laptop as no longer connected. 

I could fix the issue by manually running `sudo tailscale up --hostname <new_machine_name>`
I would have expected Tailscale to recognize my laptop not solely based on its self-reported machine name though. 

### Steps to reproduce

- Change machine name in Tailscale GUI
- Switch wifi networks

### Are there any recent changes that introduced the issue?

n/a

### OS

Linux

### OS version

Xubuntu 20.04.03

### Tailscale version

1.16.0

### Bug report

BUG-84aa07fca68905e3641fcc795be3089e7bda866c1cd7b266340391ad9e01b7ec-20211011113953Z-c92cb1f23ad4ef02

**Comment by DentonGentry** [comment]
> I would have expected Tailscale to recognize my laptop not solely based on its self-reported machine name though.

It does not use the self-reported hostname, it uses the machine key and node key generated when the node was installed.

My guess would be that opening the laptop on a new Wi-Fi network resulted in dhclient overwriting /etc/resolv.conf with the new DNS server retrieved from DHCP, and this resulted in breaking MagicDNS (https://github.com/tailscale/tailscale/issues/2334). I don't immediately understand why it would lose connectivity with the control server.

**Comment by DentonGentry** [comment]
I believe this happened when opening the laptop on a new Wi-Fi network resulted in dhclient overwriting /etc/resolv.conf with the new DNS server retrieved from DHCP.
