### ISSUE TITLE
Silent flag install caused frontend version mismatch

### ISSUE THREAD

**Issue by havedill** [tailscale/tailscale#3047]
### What is the issue?

I upgraded tailscale from 1.12.3 to 1.16 using pdqdeploy and the /S flag.

Seems like it doesn't upgrade the frontend properly

![image](https://user-images.githubusercontent.com/34009509/136858081-ec96d538-9399-4519-a1c5-580e85c28dd3.png)

### Steps to reproduce

Tailscale upgrade using /S flag 

### Are there any recent changes that introduced the issue?

Upgrading.

### OS

Windows

### OS version

Win 10

### Tailscale version

1.16.0

### Bug report

BUG-eb7c75bcafdf94224d020bed32cd7b0cfa989df4bab00447ff248c0aaf7a9d84-20211011213316Z-f922d90bedc366e2

**Comment by otherjoel** [comment]
I received this on a Windows Server 2019 machine today, upgrading from 1.16.1 to 1.16.2. 

![image](https://user-images.githubusercontent.com/1553115/140194957-c7c53e1a-e6ca-4c54-8e63-50435c31e637.png)

I did not use any flags on the installer. The existing 1.16.1 install was configured to “run unattended”.

I followed a similar fix to that in the forums: stop the service, ensure no running tailscale processes, and re-run the installer.

The only other thing I notice (unsure if related) is that `tailscale status` still shows the following:

    PS C:\Program Files (x86)\Tailscale IPN> .\tailscale.exe status
    # Health check:
    #     - network-category: SetCategory: Exception occurred.
    
    [list of IPs as usual ...]

**Comment by TheCakeIsNaOH** [comment]
I have seen this on multiple windows 10 machines when upgrading via the Chocolatey package. 
It seems to be resolved by force upgrading the package which runs the installer again.

**Comment by bradfitz** [comment]
Maybe the NSIS `/S` flag skips the uninstallation step?

In any case, we're going to be moving away from NSIS to an MSI, so this will probably get fixed as part of that. (or it probably is already)

**Comment by Madydri** [comment]
On Windows Server 2019 Datacenter version 1809
![2021-12-25_14-49-53](https://user-images.githubusercontent.com/70443803/147386396-eb2dedd8-33e8-421b-8c46-edc5469ca566.png)
Just using normal install after update prompt

**Comment by Madydri** [comment]
Note : was updating using a remote connection over tailscale
a third install solved the problem.
Have installer output if helpful.

**Comment by DentonGentry** [comment]
Noting: as of the 1.36 release, though the NSIS installer is still built it is not linked from pkgs.tailscale.com. The main installer is now MSI.

**Comment by DentonGentry** [comment]
Believed to be fixed in the MSI installers.
