### ISSUE TITLE
"Open" button in "Services" tab should open https:// instead of http://

### ISSUE THREAD

**Issue by mattn** [tailscale/tailscale#3048]
### What is the issue?

This is a problem on Tailscale web site. "Services Collection" collect HTTPS correctly but "Open" button open browser with "http://100.xxx.xxx.xxx:443". This should be "https://100.xxx.xxx.xxx".

### Steps to reproduce

1. Start https server on the device
2. Enable Service Collection
3. Click Open button in Services tab

**Comment by bradfitz** [comment]
We do that: https://tailscale.com/blog/tls-certs/

But that's not an answer by itself. Might be a reasonable default but the user can have their own DNS and certs. We really need to detect it on each machine and advertise it with the portlist. But then there are a dozen popular web servers whose config we'd need to read. Or we sniff SNI packets and learn. Not pretty.

**Comment by mattn** [comment]
Yeah, maybe what I want is the bookmark feature of the browser. And I want to open the URL from Android app like a launcher. So feel free to close this. Thanks.
