### ISSUE TITLE
Taildrop does not work from Android to oracle cloud Linux VM

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3053]
### What is the issue?

From User:

I'm trying to send a file from my Android phone to my linux machine.  When I click my linux box in the list of machines to share with, a red "i" with a circle around it pops up; however, there is no error message or further information

Tailsdrop failed from Android Phone -> Oracle Cloud VM .

More details refer to the front conv. 

### Steps to reproduce

Try to send file from Android Phone -> Oracle Cloud VM .

### OS

Other

### OS version

Oracle Cloud Linux Vm , Android 

### Tailscale version

1.14.6

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3nsgh)

**Comment by DentonGentry** [comment]
The peerapi uses netstack in the 1.21.x unstable releases: https://pkgs.tailscale.com/unstable/
It will be in the 1.22 stable release.

Installing the unstable release on the Oracle VM will likely allow taildrop to work.

**Comment by DentonGentry** [comment]
I believe this was fixed in the 1.22 release, by making the peerapi use netstack.
