### ISSUE TITLE
Android app doesn't accept pen/stylus input

### ISSUE THREAD

**Issue by dstaley** [tailscale/tailscale#3059]
### What is the issue?

The Android client doesn't respond to touch events that are the result of pen/stylus input.

I'm not completely sure if the issue here is due to Gio UI, or is due to Tailscale's specific implementation, so I figured I'd cover my bases and submit an issue to both.

[Upstream issue](https://todo.sr.ht/~eliasnaur/gio/291)

### Steps to reproduce

Pre-condition:
Using an Android device that utilizes pen input (Samsung Galaxy Tab S, Microsoft Surface Duo, etc...)

1. Open the Tailscale application.
2. Using the pen, tap on UI elements.

Expected Result:
The UI responds to pen input.

Actual Result:
The UI does not respond to the inputs.

### OS

Android

### OS version

Android 11

### Tailscale version

1.16.0

**Comment by bradfitz** [comment]
Yeah, this is almost certainly Gio.

/cc @eliasnaur

**Comment by dstaley** [comment]
Good news everyone! This is now fixed [upstream](https://git.sr.ht/~eliasnaur/gio/commit/4d22a926).

**Comment by eliasnaur** [comment]
Thanks to @dstaley for the swift fix, https://github.com/tailscale/tailscale-android/pull/22 is the update for the app.
