### ISSUE TITLE
safesocket: warn against sudo on macOS

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3063]
If a user tries to use the macOS GUI binary as the CLI, it's sandboxed, and we have a whole complicated mechanism to make it work.

But if you use e.g. `sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale cert xxxxx.ts.net`

Then you get:

```
Get "http://local-tailscaled.sock/localapi/v0/cert/xxx.ts.net?type=pair": safesocket: failed to connect to /var/run/tailscaled.socket: dial unix /var/run/tailscaled.socket: connect: no such file or directory; failed to connect to Tailscale IPNExtension: no sameuserproof token found in TS_MACOS_CLI_SHARED_DIR "/private/var/root/Library/Group Containers/W5364U7YZB.group.io.tailscale.ipn.macos”
```

... because sudo makes the "sameuserproof token" not available.

We should modify safesocket to detect if sudo was used on macOS and if we were otherwise going to return an error like that, instead tell them to try again without sudo.

/cc @DentonGentry

**Comment by josharian** [comment]
To be clear, we want to check whether `sudo` was used, not whether uid == 0, correct? Looks like sudo sets a few env vars (SUDO_COMMAND, SUDO_USER, SUDO_UID, SUDO_GID), so this detection should be straightforward.
