### ISSUE TITLE
Notifications icons fuzzy on Windows

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3066]
The Windows notification icons are fuzzy on at least Windows 11 with Tailscale 1.16.0:

![fuzzy](https://user-images.githubusercontent.com/2621/137050827-49267816-77ba-4741-afd0-01e55237c3ac.png)

/cc @tailscale/frontend @dblohm7

**Comment by dblohm7** [comment]
@bradfitz which display density are you using?

This could be a few things. From what I've learned from reading the Walk source code, it tries to use `FindWindow` to locate the shell, and then obtain that Window's DPI. Given that this is Windows 11 and there have been significant changes made to the shell, it is quite possible that this detection code no longer works.

This also makes me wonder why the DPI is being sniffed out that way when there are much better ways...

**Comment by dblohm7** [comment]
Also interesting that our manifest does not specify awareness for per-monitor DPI, which also affects how various APIs respond. Fixing up the manifest is probably the first thing to do, however I want to test a few things such as the TailDrop window to ensure that Walk can handle that correctly.

**Comment by bradfitz** [comment]
> @bradfitz which display density are you using?

How do I look that up?

**Comment by dblohm7** [comment]
Right-click on desktop -> `Display Settings`
That settings window should tell you your scaling as a percentage.

**Comment by bradfitz** [comment]
125%, apparently. (I have no memory of changing this... but that sounds like a weird default? Maybe its default is computed based on laptop's hardware.)

**Comment by dblohm7** [comment]
Yes, it's based on hardware. Its default value should be your ideal scale factor.

**Comment by dblohm7** [comment]
> Also interesting that our manifest does not specify awareness for per-monitor DPI, which also affects how various APIs respond. Fixing up the manifest is probably the first thing to do, however I want to test a few things such as the TailDrop window to ensure that Walk can handle that correctly.

Okay, this looks good. PR forthcoming.

**Comment by DentonGentry** [comment]
The change to support per-monitor DPI went into Tailscale 1.20.

**Comment by DentonGentry** [comment]
Per monitor DPI support went into Tailscale 1.20. Not clear whether there is more to do here.

Barring further comment, we'll expect to close this during the next regular bug scrub.
