### ISSUE TITLE
Mysql server 5.7 Drops all incoming connections after Tailscale Install Ubuntu 18.04

### ISSUE THREAD

**Issue by bleikg90** [tailscale/tailscale#3068]
### What is the issue?

After installing Tailscale on four ubuntu servers running 18.04 - with a GMT-5 timezone and lower_case_table_names=1 variable the servers stop receiving connections on both my Java server and my Node.js server. All three run in the same machine.

Tailscale 1.16.0
  tailscale commit: 86bcf6a964468c86ac4cc97adadc7d7a47c10178
  other commit: f787a582e80a6baed9ff81d9dd2db06ba789df3e
  go version: go1.17.1-ts097d1284f9

My Java driver is version 5.1.38 
My Node Drive is mysql 2.15.0

Both exceptions show a: 
Error: connect ECONNREFUSED 192.168.XX.XX:3306,
code: 'ECONNREFUSED',

Looking at my mysql workbench everything seems to run ok. If i ssh into the machines I can still log into mysql with out an issue but the drivers for the servers can't connect. After uninstalling Tailscale and restarting mysql everything returned to normal. However during the installation and  uninstalling this issue came up. 
`Checking system database.`
`mysql.columns_priv                                 OK`
`mysql.db                                           OK`
`mysql.engine_cost                                  OK`
`mysql.event                                        OK`
`mysql.func                                         OK`
`mysql.general_log                                  OK`
`mysql.gtid_executed                                OK`
`mysql.help_category                                OK`
`mysql.help_keyword                                 OK`
`mysql.help_relation                                OK`
`mysql.help_topic                                   OK`
`mysql.innodb_index_stats                           OK`
`mysql.innodb_table_stats                           OK`
`mysql.ndb_binlog_index                             OK`
`mysql.plugin                                       OK`
`mysql.proc                                         OK`
`mysql.procs_priv                                   OK`
`mysql.proxies_priv                                 OK`
`mysql.server_cost                                  OK`
`mysql.servers                                      OK`
`mysql.slave_master_info                            OK`
`mysql.slave_relay_log_info                         OK`
`mysql.slave_worker_info                            OK`
`mysql.slow_log                                     OK`
`mysql.tables_priv                                  OK`
`mysql.time_zone                                    OK`
`mysql.time_zone_leap_second                        OK`
`mysql.time_zone_name                               OK`
`mysql.time_zone_transition                         OK`
`mysql.time_zone_transition_type                    OK`
`mysql.user                                         OK`
`The sys schema is already up to date (version 1.5.2).`
`Checking databases.`
`Error occurred: Error during call to mysql_check.`
`mysql_upgrade failed with exit status 4`
`dpkg: error processing package mysql-server-5.7 (--configure):`
 `installed mysql-server-5.7 package post-installation script subprocess returned error exit status 1`
`Errors were encountered while processing:`
` mysql-server-5.7`
`E: Sub-process /usr/bin/dpkg returned an error code (1)`

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.16.0

### Bug report

BUG-928797d21b38e53499032380b976816e5e86b1f10fc1833b2231835fd06eb550-20211013152119Z-7d34c6d62dc5784d

**Comment by DentonGentry** [comment]
I would advise looking for access control configuration in MySQL, it may now be receiving incoming connections from 100.64.0.0/10 but be configured to only accept from 192.168.0.0/24, or vice-versa.

**Comment by bleikg90** [comment]
Thanks! will look into it.

**Comment by finnie2006** [comment]
Did you fix it and if yes how @bleikg90
