### ISSUE TITLE
Dry-run support for testing --authkey

### ISSUE THREAD

**Issue by artis3n** [tailscale/tailscale#307]
**Is your feature request related to a problem? Please describe.**

In order to test #270 with CI tests, I created a new Tailscale account and use an auth key from that account for all of my tests. I would love to be able to test Tailscale against this account without generating "real" machines that I need to manually go in and clean up later.

**Describe the solution you'd like**

Something like Let's Encrypt's [staging environment](https://letsencrypt.org/docs/staging-environment/) would be great. Some CLI flag like `--dry-run` that lets me test creating machines against my Tailscale account to validate whether I've configured my server/device/authentication correctly without actually generating those servers in my account.

**Describe alternatives you've considered**

This is a pretty low priority request. As people incorporate Tailscale into their environments, the ability to "test" their setup without registering their server could be beneficial, however.

**Additional context**

Tailscale is :tada: , thanks for your work to put together this product.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171889175755037) by [Unito](https://www.unito.io/learn-more)

**Comment by DentonGentry** [comment]
I think ephemeral node keys substantially meet this need: https://tailscale.com/kb/1111/ephemeral-nodes/
Nodes created via an ephemeral key are automatically removed shortly after we stop hearing from them (where "shortly" is currently defined as 48 hours).
