### ISSUE TITLE
Setting --state path in tailscaled does not also set tailscaled.log.conf path

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#3073]
### What is the issue?

Steps:
* tailscaled --state /data/tailscaled.state &

Expected:
* No more files in /var/lib/tailscale, which is not persistent on many systems (in particular, many container systems)

Actual:
* Tailscale's state file moved, but there's a bunch of stuff in /var/lib/tailscale:

```
# ls /var/lib/tailscale/
certs                tailscaled.log.conf  tailscaled.log2.txt
files                tailscaled.log1.txt
```

tailscaled.log.conf is the most problematic one since it means the logid will rotate every time the container restarts, even though the nodekey remains the same.

### OS

Linux

### Tailscale version

1.6.0

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/2932
