### ISSUE TITLE
windows: turning off exit node doesn't update systray icon immediately

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3090]
Turning off the exit node in version 1.16.0 on Windows via the systray menu doesn't update the systray icon away from the exit node arrow icon variant to the normal icon.

Or sometimes it does, but much much later. Or only over mouseover?

I haven't figured out when/how it updates, but it's not immediately.

Tested on Windows 11.

/cc @dblohm7

**Comment by bradfitz** [comment]
It also happens on Windows 10.

https://user-images.githubusercontent.com/2621/137402205-f320400f-7782-4f1e-96c8-b1b2c1865f1d.mov

**Comment by bradfitz** [comment]
@danderson and I are reading through the code and it seems to be be in the Windows client, not in LocalBackend.  The systray icon is only updated on netmap change, not on prefs changes it seems.

**Comment by bradfitz** [comment]
I just did a build today (using tailscale 43983a4a3b9d5b984872961be040466afbf71f57) to debug this again and it's no longer super slow at least. It's now sub-second, but not ~instant (so maybe 300-500ms?). Maybe it's acceptable now, if the fix to #3447 did in fact help this.

But I only tested on one Windows 11 machine too.

**Comment by DentonGentry** [comment]
Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Believed resolved.
