### ISSUE TITLE
Menu bar icon "spins" forever when aborting switching to a different account

### ISSUE THREAD

**Issue by sonovawolf** [tailscale/tailscale#3092]
### What is the issue?

Clicking "log in to a different account" and not logging in will make the menu bar icon "spin" forever

### Steps to reproduce

1. Click on the menu bar icon
2. Hover your email
3. Click on "Log in to a different account…"
4. Don't log in to a different account

https://user-images.githubusercontent.com/3002490/137399176-ae90ac3d-532a-4259-bcc2-bd6b451eacc4.mov

### OS

macOS

### OS version

macOS Big Sur 11.4

### Tailscale version

1.12.3

### Bug report

BUG-b2779102d21ca078a79fb5b96a42d3505a449856a4b769be6914e6002358c9d8-20211014213713Z-65505a2a0994a6ca

**Comment by bradfitz** [comment]
Any reason you're reporting bugs against an old version?

> Click on "Log in to a different account…"
> Don't log in to a different account

Also, what do you want to happen? It to stop animating? Then click "Disconnect".

**Comment by bradfitz** [comment]
Web cookie auth (logged into Tailscale in your browser) is unrelated to whether you're logged into Tailscale the app.

@darshinimashar was also confused by this the other day, so I guess it's a common confusion.

I guess the confusion is that Google, Microsoft, and GitHub all have web-based auth flows, so you're using a browser to log in to the desktop app.

**Comment by sonovawolf** [comment]
I see now. You can be logged in into the admin console without being on the tailnet and vice-versa. That actually makes a lot of sense.

Part of the confusion is the menu bar app it looks like you're still connected, because the "connect" button is disabled and your email is still there:
![image](https://user-images.githubusercontent.com/3002490/137423496-42e9ed8d-a371-47e1-b327-4e5c6389781d.png)

Are they connected to control but not to that tailnet anymore?

What I would expect to happen is that there isn't really a time when the app stops working: if you click "log in to a different account…" you stay logged in with this account until you've started the login for the other account. Until that happens, nothing changes to the current setup.

**Comment by agottardo** [comment]
I think this should be fixed now.
