### ISSUE TITLE
write Caddy module for getting TLS certs from tailscaled

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3096]
Tracking bug for writing a Caddy module to get TLS certs from the machine's tailscaled via the localapi. (using https://pkg.go.dev/tailscale.com/client/tailscale#GetCertificate)

@mholt, any pointers on what type of module we'd need to be? Got an example of a similar one?

Grepping around backwards from `tls.Config.GetCertificate` ....

`ConnectionPolicy` ...https://caddyserver.com/docs/json/apps/http/servers/tls_connection_policies/

`AutomationPolicy` .... https://caddyserver.com/docs/json/apps/tls/automation/policies/

"Fulfilled by modules in namespace: `tls.issuance`"

I guess we want to be one of these? https://caddyserver.com/docs/json/apps/tls/automation/policies/issuers/

So e.g.
https://github.com/caddyserver/caddy/blob/master/modules/caddytls/acmeissuer.go
https://github.com/caddyserver/caddy/blob/master/modules/caddytls/internalissuer.go

Do we really have to do all the CSR stuff? https://pkg.go.dev/github.com/caddyserver/certmagic#Issuer

We already do that, and handle caching for certs that are still valid.

The hook I really want is given the SNI name, choose to give you a cert pair or not.

**Comment by DentonGentry** [comment]
I think this is being done in https://github.com/caddyserver/caddy/pull/4541
Interested parties should subscribe to that issue instead.
