### ISSUE TITLE
FR:Tailscale on TrueNAS Scale (Linux)

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3097]
### Tell us about your idea!

Tailscale support with TrueNAS.

### What are you trying to do?

From User 

"I tried installing tailscale on Truenas Scale (Debian Bullseye based) and while it installed and worked correctly, it broke Turenas Scale's ability to install containerized apps from the app catalog. Can you work with the Truenas folks to integrate tailscale properly into Truenas Scale as that would make secure remote access extremely simple?"

**Comment by etrigan63** [comment]
Any news on this? Should this be brought up to the TrueNAS folks?

**Comment by DentonGentry** [comment]
There is no update as yet. We understand there is a desire for TrueNAS Scale support but no work has been done on it.

**Comment by mayakacz** [comment]
See also FR in TrueNAS at https://jira.ixsystems.com/browse/NAS-110540

**Comment by zeroZshadow** [comment]
Has this been retried now that TrueNAS Scale has officialy released?

**Comment by DentonGentry** [comment]
Implemented by the TrueCharts community https://tailscale.com/changelog/#2022-08-24-service
