### ISSUE TITLE
Mediacom customers can't access control

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3100]
The ISP Mediacom Communications (50.80.0.0/14 and 173.16.0.0/12, probably others) seems to be having trouble accessing AWS eu-central-1 where login.tailscale.com and controlplane.tailscale.com reside (among other things), but AWS us-west-2 where log.tailscale.com resides seems to be fine.

The problem appears to be that packets near the maximum Ethernet MTU (<=1480 bytes Ethernet payload is fine; the problem is somewhere between 1481 and 1500 bytes) are dropped as they enter the Mediacom network somewhere.

Coincidentally, @sailorfrag can curl https://www.mediacomcable.com/ from log.tailscale.com but not login.tailscale.com or either of his home ISPs, however that may be a red herring: the failure there is that there is no response to the outgoing TCP SYN, and the SYN/ACK shouldn't be large enough to trigger this problem (plus that would imply a drop as the packet leaves Mediacom). That web site is hosted inside their network according to traceroute.

This appears to be unrelated to IPv6.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ob2p)

**Comment by sailorfrag** [comment]
For anybody that thinks they are affected by this, please use the UI to generate a bug report (or run `tailscale bugreport` on the command line) and reply here (or send an e-mail to support@tailscale.com) and I'll investigate. No other action is required as this is a server-side workaround for an issue inside a particular ISP's network.

**Comment by sailorfrag** [comment]
According to one of the affected users, the problem may be fixed on Mediacom's end (or one of Mediacom's transit providers). I'm going to leave our workaround in place for now; it will automatically expire on Oct 22 at slightly different times for each of our servers. If anybody starts having problems again, feel free to update here or contact support@tailscale.com.
