### ISSUE TITLE
Multiple nodes behind pfsense NAT, only one gets direct

### ISSUE THREAD

**Issue by dave-andersen** [tailscale/tailscale#3105]
### What is the issue?

I have multiple machines on a subnet ("dave-net") behind a pfsense-based NAT with NAT-PMP and UPnP enabled, and multiple machines "out there" on the internet with various states of NAT or not. The behavior I think I'm observing is that one external node is only able to establish a direct connection to one node on "dave-net", and connections to other nodes on "dave-net" end up going through a DERP.

Example: ping external1 from both internal-server and internal-laptop; show tailscale status:

internal-laptop (macbook-pro-8):
```
522 dga@MacBook-Pro-8:~$ /Applications/Tailscale.app/Contents/MacOS/Tailscale status
100.109.xxx.yyy macbook-pro-8        dga@         macOS   -
...
100.66.mmm.ooo   external1             dga@         linux   active; direct 137.186.yyy.xxx:41641, tx 744 rx 568
```

internal-server:
```
dga@nvgpu23:~$ tailscale status
100.84.xxx.yyy   internal-server              dga@         linux   -
...
100.66.mmm.ooo   external1             dga@         linux   active; relay "sea", tx 840 rx 696
```

If I restart tailscale, sometimes I can get it to connect directly to a different internal node, but not multiple.

The pfsense PMP/UPNP status shows:

```
WAN | udp | any | 41647 | internal-server-IP | 41646 | NAT-PMP 41647 udp -- | -- | -- | -- | -- | -- | --
WAN | udp | any | 41642 | internal-laptop-IP | 41641 | NAT-PMP 41642 udp -- | -- | -- | -- | -- | -- | --
```

Without understanding tailscale a little more, I'm at a loss to debug from this point.

internal-server1 and external1 are runninig Linux with 1.16; internal-laptop is MacOS running 1.14.6.

Bug does not need MacOS to replicate; we've replicated it on only linux machines all running 1.16.

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

I'm not sure if the problem was happening before 1.16 or not, sorry. I don't _think_ we were seeing it before a few days ago but we're very new to tailscale.

### OS

Linux, macOS

### OS version

Ubuntu 20.04

### Tailscale version

1.14.6 and 1.16

### Bug report

BUG-1850bb631d6cee07a8937001f4a1e00b81d5bd471cbc28e0a577bdb5fae80ac6-20211016003558Z-6c249a456769cedc

**Comment by dave-andersen** [comment]
(Sorry, that transcription of the pfsense nat-pmp status is poor. Here's the full snapshot:
![image](https://user-images.githubusercontent.com/827870/137566921-372304f0-db41-41c1-b3fd-5f03d1db8f78.png)
where 192.168.49.224 is internal-server1-ip and 192.168.49.168 is internal-laptop1)

**Comment by crawshaw** [comment]
If you turn on port randomization in your ACLs do you get multiple direct connections?

**Comment by crawshaw** [comment]
We intend to automate this, but I didn’t realize it would help with pfsense. Thanks for the report.

**Comment by bradfitz** [comment]
pfSense's FreeBSD NAT strikes again. ☹️

**Comment by apenwarr** [comment]
Do we believe NAT-PMP is buggy on freebsd if multiple devices use port 41641? If so that sounds like it would be a high priority for the pfsense team if we report it, compared to convincing them to switch NAT types. 

Is there a chance we misinterpret the NAT-PMP response and assume it opened public port 41641 even when it mapped us to a different port?

**Comment by bradfitz** [comment]
What are 222's routes and interfaces? Maybe it's using the wrong interface for PMP.

**Comment by dave-andersen** [comment]
Possibly relevant is that I don't see any packets destined for port 5351 when I run `tailscale netcheck` (I do on other machines).  I did verify that my little test go-nat-pmp program can correctly open a port on the firewall, and its NAT-PMP packets to port 5351 are visible in tcpdump. Does suggest that the gateway identification is somehow going awry.

**Comment by dave-andersen** [comment]
```
2021/10/17 21:20:53 Starting link change monitor; initial state:
{
    "InterfaceIPs": {
        "enp134s0f0": [
            "192.168.49.222/24",
            "fe80::a242:3fff:fe2e:cbba/64"
        ],
        "enp134s0f1": null,
        "lo": [
            "127.0.0.1/8",
            "::1/128"
        ],
        "tailscale0": [
            "100.117.xxx.yyy/32",
            "fd7a:115c:a1e0:ab12:4843:qqqq:ssss:rrrr/128",
            "fe80::fbab:e17a:d384:520f/64"
        ],
        "wg0": [
            "192.168.66.1/24",
            "fc00:dad1:6600::1/64"
        ]
    },
    "Interface": {
        "enp134s0f0": {
            "Index": 2,
            "MTU": 1500,
            "Name": "enp134s0f0",
            "HardwareAddr": "oEI/Lsu6",
            "Flags": 19,
            "AltAddrs": null
        },
        "enp134s0f1": {
            "Index": 3,
            "MTU": 1500,
            "Name": "enp134s0f1",
            "HardwareAddr": "oEI/Lsu7",
            "Flags": 18,
            "AltAddrs": null
        },
        "lo": {
            "Index": 1,
            "MTU": 65536,
            "Name": "lo",
            "HardwareAddr": null,
            "Flags": 5,
            "AltAddrs": null
        },
        "tailscale0": {
            "Index": 10,
            "MTU": 1280,
            "Name": "tailscale0",
            "HardwareAddr": null,
            "Flags": 25,
            "AltAddrs": null
        },
        "wg0": {
            "Index": 4,
            "MTU": 1420,
            "Name": "wg0",
            "HardwareAddr": null,
            "Flags": 9,
            "AltAddrs": null
        }
    },
    "HaveV6": true,
    "HaveV4": true,
    "IsExpensive": false,
    "DefaultRouteInterface": "enp134s0f0",
    "HTTPProxy": "",
    "PAC": ""
```

**Comment by DentonGentry** [comment]
By setting [`"randomizeClientPort": true`](https://tailscale.com/kb/1181/firewalls/) and setting static port mapping in Firewall > NAT > Outbound, pfSense and OPNsense can be turned into an Easy NAT case and make direct connections on multiple clients.

![image](https://user-images.githubusercontent.com/1140756/173205299-a3d3a1f6-61ed-4f3e-94a2-99e2803f3f12.png)
