### ISSUE TITLE
【derper】How to judge whether a custom DERP server is working properly?

### ISSUE THREAD

**Issue by Creling** [tailscale/tailscale#3110]
Hi:

~~I want to make derper coexists with nginx (which occupies port 443), so I need to assign another port to derper. It seems that I could achieve it by using flag `-a`.~~
![image](https://user-images.githubusercontent.com/43109504/137585900-bbc97c9a-2e0e-47ad-a122-53e97dfb34db.png)

~~My question is, how could I specify hostname of the derper server in this situation? Does `<IP>:<Port>` work?~~

Btw, how could I judge whether a derper is working since derper itself doesn't print any logs?

**Comment by DentonGentry** [comment]
On a node on your Tailnet, `tailscale netcheck` will print the round-trip times to all of the DERP servers. If you have a custom DERP configured in https://login.tailscale.com/admin/acls, the custom DERP will show up in the list. If it has a round-trip time is listed, then everything is working.

```
$ tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, w.x.y.z:1511
        * IPv6: no
        * MappingVariesByDestIP: true
        * HairPinning: false
        * PortMapping: NAT-PMP, PCP
        * Nearest DERP: San Francisco
        * DERP latency:
                - sfo: 5.9ms   (San Francisco)
                - sea: 24ms    (Seattle)
                - dfw: 45ms    (Dallas)
                - ord: 53.7ms  (Chicago)
                - nyc: 74.1ms  (New York City)
                - tok: 111.1ms (Tokyo)
                - lhr: 139.4ms (London)
                - syd: 152.7ms (Sydney)
                - fra: 153.1ms (Frankfurt)
                - sin: 182.1ms (Singapore)
                - sao: 190.1ms (S_o Paulo)
                - blr: 218.6ms (Bangalore)
```

**Comment by Creling** [comment]
> If it has a round-trip time is listed, then everything is working.

Hi, my custom DERP server is in the list but the round-trip time is empty, could you help me?

Following is my configuration in tailscale admin panel:
![image](https://user-images.githubusercontent.com/43109504/137606678-a0de7f3e-f3c6-4208-b4f6-ce01b60bdda7.png)

And I run my DERP server like this:
![image](https://user-images.githubusercontent.com/43109504/137606685-597008be-65d8-41cc-96be-c492046cfb49.png)

**Comment by Creling** [comment]
update: solved it. the `-c` flag is required. The default ` /var/lib/derper/derper.key` seems not work.
