### ISSUE TITLE
FR: Publish Docker image for arm64

### ISSUE THREAD

**Issue by jwillikers** [tailscale/tailscale#3112]
### Tell us about your idea!

Publish Docker image for arm64

### What are you trying to do?

Run tailscale from a Docker container on the ROCKPro64, an arm64 SBC.

### How should we solve this?

Publish the Docker image for arm64.

### What is the impact of not solving this?

Have to manually build locally and repeat for updates.

**Comment by DentonGentry** [comment]
The Dockerfile builds from source: https://github.com/tailscale/tailscale/blob/main/Dockerfile

What stops it from working now?

**Comment by bradfitz** [comment]
Nothing much. We just need to publish multiarch images. There was another request for that yesterday somewhat IIRC. Perhaps on Twitter.

**Comment by agneevX** [comment]
`arm64` images for v0.18.0 are live on Docker Hub.

**Comment by mayakacz** [comment]
arm and arm64 images are now available on [Docker Hub](https://hub.docker.com/r/tailscale/tailscale) and on [GitHub Packages](https://github.com/orgs/tailscale/packages/container/package/tailscale).
