### ISSUE TITLE
Cancelling GitHub login results in a server error

### ISSUE THREAD

**Issue by Smittyvb** [tailscale/tailscale#3118]
### What is the issue?

Trying to login to the admin console with GitHub, then changing your mind and clicking the cancel button causes an internal server error.

### Steps to reproduce

1. Go to https://login.tailscale.com/login
2. Click "Sign in with GitHub"
3. Click "Cancel"
4. Look at a page with just the contents "internal server error", with a 500 status code.

It seems this happens whenever `/a/oauth_response` is navigated to with a URL containing a `state` parameter but without a access token ([as is the case when the "Cancel" button is used](https://docs.github.com/en/developers/apps/managing-oauth-apps/troubleshooting-authorization-request-errors#access-denied)).

### OS

Linux

### OS version

Pop_OS! 20.10, Firefox 92 (Ubuntu)

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2094
