### ISSUE TITLE
Feature request: Webhook notifications for important tailnet events

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#312]
User requested via email a feature where the control server could send a Webhook Notification when a new machine is enrolled.

/cc @crawshaw

**Comment by DentonGentry** [comment]
Not exactly a webhook, but I believe device authorization was added since this was filed: https://tailscale.com/kb/1099/device-authorization/

**Comment by rnhurt** [comment]
It's been almost 2 years since this request and two other duplicate requests.  Is there any progress on this?  How can we help?

**Comment by DentonGentry** [comment]
I promise the bug will be updated when there is progress, at the moment the engineering team is working on other things.

In the mean time, the API could be used to periodically poll for devices: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-devices-get

**Comment by DentonGentry** [comment]
Implementation of this feature has started. We expect it by the end of the Northern hemisphere summer.

**Comment by zlepper** [comment]
I know this probably doesn't need to be stated or even asked, but better safe than sorry, will this also include events when things like ephemeral nodes being auto-removed?

**Comment by soniaappasamy** [comment]
Released https://tailscale.com/kb/1213/webhooks/
