### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3126]
### Tell us about your idea!

Documentation for Debian 11 install

### What are you trying to do?

From User:

The installation instructions is slightly out of date. The command apt-key is soon deprecated and I would recommend the following instructions for Debian 11.

curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.gpg | sudo gpg --dearmor -o /usr/share/keyrings/tailscale-archive-keyring.gpg
curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.list | sudo tee /etc/apt/sources.list.d/tailscale.list

This method of adding the signing key also applies to Ubuntu.

### How should we solve this?

Update for documentation.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/1937
