### ISSUE TITLE
wireguard-go dependency breaks updating Go project

### ISSUE THREAD

**Issue by jlelse** [tailscale/tailscale#3127]
### What is the issue?

`tailscale.com v1.16.0` is in the dependencies of my Go project (using tsnet and `tailscale.GetCertificate`). Trying to update all dependencies with `go get -u all` fails with the following error:

```
go get all: module golang.zx2c4.com/wireguard@upgrade found (v0.0.0-20211017052713-f87e87af0d9a), but does not contain package golang.zx2c4.com/wireguard/tun/wintun/memmod
```

### Are there any recent changes that introduced the issue?

I suspect it's due to this commit in wireguard-go: https://git.zx2c4.com/wireguard-go/commit/?id=ba9e364dab402cfc104eb00669f7fdfd9259559e

### OS

Linux

### Tailscale version

1.16.0

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/4191 updated wireguard-go to the latest upstream. If this is still a problem, please reopen.
