### ISSUE TITLE
Ability to deauthorize machines via device management solutions

### ISSUE THREAD

**Issue by shrkmz** [tailscale/tailscale#313]
**Is your feature request related to a problem? Please describe.**

Anticipating there will be instances when a device starts off compliant and so is authorized to join a TS network but then falls out of compliance as reported through some kind of device management tool, say JAMF, Intune, Airwatch, SCCM reports, etc.

**Describe the solution you'd like**

It would be nice to have the various DM solutions be able to kick a device off the TS network automagically (API call, event driven system?)

**Describe alternatives you've considered**

At this point I would expect to manually check compliance on devices and ensure they are deauthorized if necessary.

Another option that comes to mind is just having the DM solution block the TS service from running or uninstall it. Uninstalling it seems a little overkill and, more to the security aspect, we would want to ensure that device couldn't connect to the network if someone got around the DM solution.

**Comment by DentonGentry** [comment]
In case useful: there is now an API which can adjust ACLs, which could be hooked up to a posture check result: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-acl-post

**Comment by DentonGentry** [comment]
I think the API is the way we would want to support this item, closing the issue now.
