### ISSUE TITLE
Android app doesn't fully render on Xiaomi Redmi Note 4 with Android 7.0

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3134]
### What is the issue?

Tailscale app stopped working (1-2 weeks ago). I reinstalled it but it did not help, I can see only a black screen. I have Xiaomi Redmi Note 4, Android 7.0 NRD90M.

Upgrading to latest unstable 1.17.52 does not fix the issue.

![image](![image](https://user-images.githubusercontent.com/75628398/137808644-727803e5-8ca5-4a30-9443-569306e69a04.png)
### Steps to reproduce

Try to bring Tailscale up on a Xiaomi Redmi Note 4, with Android 7.0.

### Are there any recent changes that introduced the issue?

![image](https://user-images.githubusercontent.com/75628398/137808158-567ea813-461f-4d96-83d0-36873d3cee01.png)

### OS

Android

### OS version

Android 7

### Tailscale version

1.16.0

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3oksx)

**Comment by DentonGentry** [comment]
1.18 updated Gio again. Does the app work on Xiaomi Redmi Note 4 now?

**Comment by DentonGentry** [comment]
Fixed in 1.18.
