### ISSUE TITLE
Alternate CI support for Drone

### ISSUE THREAD

**Issue by engineeringsys** [tailscale/tailscale#3148]
I have a use-case where I'm using drone locally but would like to have builds that can utilize ephemeral keys and nodes to do some work.  I know this is possible with github actions but am wondering if there's a pattern or guide to get this to execute and join a tailnet via drone.

**Comment by DentonGentry** [comment]
Looking at the docs in https://docs.drone.io/, I suspect the best fit will be https://tailscale.com/kb/1112/userspace-networking/ as /dev/net/tun is usually not available in Docker containers. userspace-networking means tailscaled in the container will be running as a SOCKS5 and/or HTTP proxy, and other processes will have an ALL_PROXY or HTTP_PROXY environment variable set to have them use the proxy.

There are examples of doing this:
- for serverless https://tailscale.com/kb/1108/cloudrun/
- for Circle CI https://blog.threecomma.io/circleci-meet-tailscale
- with Kubernetes https://github.com/tailscale/tailscale/tree/main/docs/k8s

**Comment by engineeringsys** [comment]
@DentonGentry Thanks for the response on this, I'm working on this specific to drone and if there's an interest will create a repo and/or a pr for the docs.
