### ISSUE TITLE
Ship a keyring package for debian

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3151]
### Tell us about your idea!

pkgs.tailscale.com should serve a tailscale-archive-keyring package

### What are you trying to do?

New style key management for 3rd party repos on Debian derivatives requires a separate keyring from the primary Debian archive keyring. We now install one of those during the initial setup process, but we have no way to roll keys over time.

### How should we solve this?

Debian's policies say that we should ship an additional `tailscale-archive-keyring` package that owns and manages /usr/share/keyrings/tailscale-archive-keyring.gpg and keeps it up to date.

### What is the impact of not solving this?

In some amount of years when the current key expires, people will be unable to download updates from pkgs.tailscale.com. We also can't do basic hygiene key rotations, which would be nice.

**Comment by knyar** [comment]
> make the tailscale package depend on the keyring package, so that the next update pulls in the keyring package and starts maintaining keyring entries automatically.

The [packaging policy](https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends) says that `Depends` "declares an absolute dependency" and should be used for packages that are required "to provide a significant amount of functionality". So I'd probably use `Recommends` instead.
