### ISSUE TITLE
[DS216J] wgengine.NewUserspaceEngine(tun "tailscale0") error: permission denied

### ISSUE THREAD

**Issue by ThomasDalla** [tailscale/tailscale#3154]
### What is the issue?

Tailscale comes up and is healthy (can `tailscale ping others`) but the `tailscale0` interface does not exist so can't ping the IP directly from outside.

```
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 3.10.108
'modprobe tun' successful
/dev/net/tun: Dcrw-------
wgengine.NewUserspaceEngine(tun "tailscale0") error: permission denied
wgengine.NewUserspaceEngine(tun "userspace-networking") ...
dns: using dns.noopManager

...
```

### Steps to reproduce

Start the package from Synology package manager.

### Are there any recent changes that introduced the issue?

Upgraded to spk version 1.16.1 (from opkg 1.14.1).

### OS

Linux

### OS version

Synology DSM7 on Linux 3.10.108 (armada38x)\
Linux DS216J 3.10.108 #41890 SMP Fri Jun 25 02:39:15 CST 2021 armv7l GNU/Linux synology_armada38x_ds216j

### Tailscale version

1.16.1

### Bug report

BUG-d174b795bb45b4b0e3de513ed0c6e6cf4d82a2104274cc869824a1994039da98-20211020163801Z-0f11a07fbaa496ea

**Comment by bradfitz** [comment]
We'll be making this more prominent in the Synology web UI, to tell people the mode it's in and give links to docs on changing modes.
