### ISSUE TITLE
Run Tailscale in the browser

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3157]
Tracking bug for running Tailscale in the browser with WebAssembly, with the goal of doing end-to-end WireGuard w/ netstack from the browser to a remote peer, doing SSH/VNC/RDP (with e.g. xterm.js, https://github.com/novnc/noVNC, etc), where private keys etc all live in the browser session.

**Comment by bradfitz** [comment]
@mihaip finished this up. It shipped: https://tailscale.com/blog/ssh-console/ Thanks, Mihai!

(Improvements will be tracked in separate issues.)

**Comment by teaalltr** [comment]
What's the status of this? Has it been implemented?

**Comment by d1vanloon** [comment]
@teaalltr see the previous comment. This shipped as part of the web-based Tailscale SSH Console.
