### ISSUE TITLE
tailscaled's RSS looks high

### ISSUE THREAD

**Issue by jtrakk** [tailscale/tailscale#316]
**Is your feature request related to a problem? Please describe.**

It seems like `tailscaled` is using a lot of memory.  E.g.
```
$  ps -eo rss,comm | grep tailscale
116948 .tailscaled-wra
```
I interpret this as 116.9M. Is this a normal amount, or is something wrong with my system? If that's normal, I'd rather it use less because I have limited RAM.

**Additional context**

I'm on NixOS 19.09, using the version that's in nixpkgs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1172467214633980) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
The RSS doesn't necessarily report an interesting value in many cases.

See https://golang.org/doc/go1.12#runtime :

> On Linux, the runtime now uses MADV_FREE to release unused memory. This is more efficient but may result in higher reported RSS. The kernel will reclaim the unused data when it is needed. To revert to the Go 1.11 behavior (`MADV_DONTNEED`), set the environment variable `GODEBUG=madvdontneed=1`.

If you want to see a lower number you could try setting `GODEBUG=madvdontneed=1` in your environment, but it'll cost more CPU and won't actually decrease the memory available to Linux to take back when Linux needs it.

**Comment by jtrakk** [comment]
Ok, I'll leave it how it is then.
