### ISSUE TITLE
FR: Publish container image for sidecar

### ISSUE THREAD

**Issue by mayakacz** [tailscale/tailscale#3163]
### Tell us about your idea!

Publish the Tailscale container sidecar image

### What are you trying to do?

More easily deploy Tailscale as a sidecar

### How should we solve this?

Publish the content at https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md#sample-sidecar on Docker Hub & GHCR

### Anything else?

This came up in our K8s office hours

**Comment by stealthybox** [comment]
This seems like it's done now, but the example doc needs to be updated.

**Comment by dghubble** [comment]
There is only a single tagged versioned release v1.16. These aren't yet getting published with Tailscale releases (e.g. no v1.16.2)

**Comment by mayakacz** [comment]
`tailscale/tailscale` on Docker Hub is now getting published with Tailscale releases: https://hub.docker.com/r/tailscale/tailscale/tags

**Comment by maisem** [comment]
They are also on published to ghcr.io - https://ghcr.io/tailscale/tailscale
