### ISSUE TITLE
FR: Subnet routes in userspace networking

### ISSUE THREAD

**Issue by mayakacz** [tailscale/tailscale#3164]
### Tell us about your idea!

Subnet routes in userspace networking

### What are you trying to do?

Today, you can't use a subnet router (or an exit node) with userspace networking. This may be an issue when trying to connect containers with VPC peering across clouds.

### How should we solve this?

Fix subnet routes over SOCKS proxy

### Anything else?

This came up in our K8s office hours

**Comment by bradfitz** [comment]
Dup of #2264 (for which #2907 is pending)
