### ISSUE TITLE
Windows 11 Internet Connectivity break while using Exit-node

### ISSUE THREAD

**Issue by jiahaowu** [tailscale/tailscale#3180]
### What is the issue?

I have two different exit nodes on Ubuntu and two windows machine as client. When choosing those exist node on client machines, the internet connectivity breaks.   This bug appears since upgrading to 1.14.3 and persist in recent upgrade to 1.16.1.  

I tried deregister the client and login again, remove local configuration, uninstall and reinstall tailscale, but none of those approaches help.  Other MacOS, Android,, IOS client works fine with exist-node, only those windows 11 clients broken since the upgrade. 

### Steps to reproduce

Clean install on Windows 11 and chose an exit node.  Visit Google.com, failed.  Ping 1.1.1.1 no response.

### Are there any recent changes that introduced the issue?

Upgrading to 1.14.3 introduced this issue.  Before that, everything is fine. 

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.16.1

### Bug report

BUG-22b1073db1c6bbd2fe83fb2680a0bf831b6631e67ae70d1d024c8e9c5783c89c-20211025052521Z-c6da008f2923e765

**Comment by jiahaowu** [comment]
Recovered since upgrading to 1.16.2

**Comment by srberard** [comment]
This is still failing for me.  I've upgraded my Windows machine as well as by two exit node hosts to 1.16.2.

**Comment by VictorTomaili** [comment]
Still failing for me either. exit node is 1.16.2 ubuntu linux

**Comment by jiahaowu** [comment]
It seems worked only for a single time right after upgrading to 1.16.2. I also tried on another win11 laptop, still failing...

**Comment by dobacco** [comment]
I seem to be having this issue too. It is disrupting access to our secured systems. 

After enabling exit node on Windows 11:

```
 .\tailscale.exe netcheck

Report:
        * UDP: false
        * IPv4: (no addr found)
        * IPv6: no
        * MappingVariesByDestIP:
        * HairPinning:
        * PortMapping:
        * Nearest DERP: unknown (no response to latency probes)
```

**Comment by VictorTomaili** [comment]
Seems fixed in the latest release, I can connect to exit node about 2 weeks without any problems

**Comment by VictorTomaili** [comment]
Still, I can use it without any problem. ver 1.18 - My opinion is this issue can be closed.

**Comment by dobacco** [comment]
1.18 seems to resolve this issue so yeah it can be closed.

**Comment by DentonGentry** [comment]
Seems to be resolved.

**Comment by TomerGamerTV** [comment]
Nope its still bugged
