### ISSUE TITLE
FR: Show Network Device grouped by Tag instead of User

### ISSUE THREAD

**Issue by jhult** [tailscale/tailscale#3183]
### Tell us about your idea!

Show Network Device grouped by Tag instead of User

### What are you trying to do?

In the desktop app, you can view Network Devices. Right now, it shows these grouped by the User who auth'd the device. It would be nice to show this by Tag (or allow an option to show by either User or Tag).

### How should we solve this?

Add an option in the Tailscale app UIs to show Network Devices by either User or Tag.

### What is the impact of not solving this?

An unwieldy list of servers

**Comment by jhult** [comment]
As you can see from the below image (machine names blurred), the list for a user can quickly become unwieldy. Notice the scroll arrows at both the top and bottom.

<img width="482" alt="list" src="https://user-images.githubusercontent.com/9849069/141131632-f1855e87-f43e-4fc9-9a66-e01d6df55637.png">

**Comment by jhult** [comment]
So I now see a "Tagged Devices" section (macOS 1.20.1).

![tagged_devices](https://user-images.githubusercontent.com/9849069/151612115-91588610-c0f3-4105-9a98-b434ff1cc533.png)

However, the list is still unwieldy. It would be preferable to have each tag as its own section.

**Comment by bradfitz** [comment]
This is a work in progress. The current "Tagged Devices" menu is a protocol compatibility hack for old clients that aren't aware of nodes that can be owned by only tags and not users. @maisem is currently working on all this.

**Comment by maisem** [comment]
@jhult we considered having each tag show up separately but it didn't look right when devices had multiple tags. How would you expect those to work?

**Comment by DentonGentry** [comment]
If there is additional feedback about grouping of tagged devices, whether separated by tag or something else, please open a new bug. Since the original feature request from this issue has been addressed, I'm closing it as completed.
