### ISSUE TITLE
MacOS Firewall blocks DNS resolution even with the Tailscale app set to "Allow Incoming Connections"

### ISSUE THREAD

**Issue by shshe** [tailscale/tailscale#3185]
### What is the issue?

This week, myself and a couple other engineers have found that DNS resolution when "Use Tailscale DNS settings" is enabled times out locally. We traced the issue back to the MacOS Firewall. However, DNS resolution was working with the MacOS firewall enabled in the past. I'm not sure if this is an issue with a MacOS update.

### Steps to reproduce

1. Enable Security & Privacy -> Turn on Firewall.
2. Block all incoming connections is off.
3. Add Tailscale to the list with "Allow incoming connections.
4. DNS resolution seems to timeout.

### OS

macOS

### OS version

10.15.7

### Tailscale version

1.16.1

**Comment by DentonGentry** [comment]
Is this still happening?

I have the macOS firewall on, and have no issues using DNS.

**Comment by DentonGentry** [comment]
ETIMEDOUT.
