### ISSUE TITLE
"Needs authentication" after disabling VPN via iOS settings

### ISSUE THREAD

**Issue by brandonweeks** [tailscale/tailscale#3189]
### What is the issue?

When disabling the Tailscale connection via the Tailscale app the status transitions from "Active" to "Stopped." When the Tailscale connection is disabled from the iOS settings, the status transitions from "Active" to "Needs authentication."

### Steps to reproduce

1. Start a Tailscale connection from the Tailscale iOS app
2. Open the iOS settings app, stop the VPN connection
3. Return to the Tailscale app, observe the status at the top of the app

### OS

iOS

### OS version

15.1

### Tailscale version

1.16.1

**Comment by arunsathiya** [comment]
My connection drops often these days: 

- sometimes when I turn it off to access something without a VPN and turn it back on, it doesn't work, 
- sometimes I switch to Cloudflare Warp VPN and then I try to activate Tailscale VPN again, but it doesn't work

I am not too sure when this started, or what causes this, but based on my research, the limited memory that iOS gives Tailscale is a cause? - https://tailscale.com/blog/go-linker/

Here's a screenshot of how the app looks when Tailscale VPN drops:

![IMG_0709](https://user-images.githubusercontent.com/18581859/141804344-2eea41bd-a15b-45ee-8e48-89421681c8b4.PNG)

The most important part is, no amount of force-closing and restarting the app helps. I restart the device for Tailscale to work again. 

Happy to submit debug logs if they help troubleshoot, but I am not sure how to generate one on iOS: https://tailscale.com/kb/1011/log-mesh-traffic/?q=debug%20logs

**Comment by kverb** [comment]
I emailed tailscale support with my tail IP and they asked to comment here. I don't have much to contribute other than this is definitely happening to me too, and is reproducible with the adguard (local) VPN on an iPhone 13 mini (iOS 15). The only work-around I can reliably use is to restart the device. I don't have a mac so i don't think there's a way to pull logs. As soon as I enable the adguard VPN, the tailscale app is immediately unusable and just shows the "needs reauthentication" prompt. Attempting to reauth just spins and seemingly does nothing.

**Comment by kverb** [comment]
Follow up with a work-around: 

Based on the advice of tailscale support, I disabled my tailnet's exit node. Now, I can switch back from VPN 1 (adguard, in my case) to Tailscale VPN. The caveat, which is fairly annoying, is that I have to first disable the adguard VPN, and usually have to force-close the tailscale app. This also seems to work with the exit node enabled

**Comment by agottardo** [comment]
This is fixed now. When the VPN tunnel is killed by switching to another VPN app, the app UI shows the 'Disconnected' lockout state.
