### ISSUE TITLE
FR: expose Tailscale iOS app version within the app

### ISSUE THREAD

**Issue by brandonweeks** [tailscale/tailscale#3190]
### Tell us about your idea!

It would be helpful if the Tailscale app version was displayed within the app somewhere.

### What are you trying to do?

File a bug against the Tailscale iOS app, which asks for the version of the app.

### What is the impact of not solving this?

Inferring the app version from the iOS App Store release notes.

**Comment by DentonGentry** [comment]
The version is also available in https://login.tailscale.com/admin/machines

**Comment by DentonGentry** [comment]
The Mac App Store is supposed to be doing this automatically. As the large majority of the fleet of macOS devices out there does update to the latest version promptly after release, I think there must be something going on with that one specific Mac.

**Comment by mayakacz** [comment]
> It would be helpful if the Tailscale app version was displayed within the app somewhere.

We are redesigning the iOS app and this is included in the new design.

**Comment by agottardo** [comment]
This was fixed in v1.46.
