### ISSUE TITLE
FR: authorize exit nodes using the API

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3196]
### Tell us about your idea!

API for authorizing the Exitnode.

### What are you trying to do?

Authorize(Enable) exitnode without opening the admin console.

### How should we solve this?

Add the API support for authorizing Exit Node.

### What is the impact of not solving this?

Can't fully automate the Exitnode creation process as it involves manual authorization from admin console.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pljl)

**Comment by praneetloke** [comment]
This would be spendid to have! Selfishly this would make my personal VPN infrastructure fully autonomous.

**Comment by mayakacz** [comment]
This is still not possible via the API.
Note that we recently launched auto approvers, to allow you to have certain users automatically approve exit nodes: https://tailscale.com/blog/auto-approvers/

**Comment by DentonGentry** [comment]
I believe the need for this has been met by autoApprovers. https://tailscale.com/blog/auto-approvers/
