### ISSUE TITLE
ACL tags do not work with ACL tests

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3224]
### What is the issue?

ACL tags do not work with ACL tests. The example ACL given in your docs indicates that one should be able to use a tag in a test:

  "tests": [
    // […]
    // dave@tailscale.com can SSH into vega and the lab.
    {
      "user": "dave@tailscale.com",
      "allow": ["vega:22", "tag:lab:22"],
    },
    // […]
  ],
Which is failing with error 👍 
Error: test(s) failed

test(s) failed for user:test@example.com

·         address tag:lab:22: too many colons in address.

### Steps to reproduce

 Try to add the test in ACL and save the changes.

  "tests": [

    { "user": "test@example.com", "allow": ["tag:lab:22"] },

  ],

### OS version

any

### Tailscale version

1.16.1

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rlxt)

**Comment by mayakacz** [comment]
I can reproduce this.
Sample error message:

<img width="1087" alt="Screen Shot 2021-11-01 at 15 49 31" src="https://user-images.githubusercontent.com/15946341/139752225-74413114-ae15-4d84-b2ac-13cf2959ef16.png">
