### ISSUE TITLE
WSL resolv.conf setting appears broken on Windows 11

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#3229]
Logs show: `WSL: could not list distributions: wslRun([wsl.exe -l]): An attempt was made to reference a token that does not exist.: ""`

This suggests something has gone wrong with our use of `WTSGetActiveConsoleSessionId`.

**Comment by DentonGentry** [comment]
Fixed in 1.20 by https://github.com/tailscale/tailscale/pull/3687
