### ISSUE TITLE
Allow grouping in admin portal.

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/tailscale#324]
**Is your feature request related to a problem? Please describe.**

It's difficult to manage multiple clients from within admin portal.

**Describe the solution you'd like**

Possible solutions, implemented within admin portal:
- Allow creation of groups and assigning machines to them
- Implement tagging feature and add the group BY column in machines view.

**Comment by DentonGentry** [comment]
We've added an API which can automate tasks involving fleet management: https://github.com/tailscale/tailscale/blob/main/api.md

At this point I don't expect to aim the admin panel at managing large numbers of devices.
