### ISSUE TITLE
FR: Support build and release on pushed tags

### ISSUE THREAD

**Issue by chrisgoffinet** [tailscale/tailscale#3250]
### Tell us about your idea!

Build docker containers and push them to ghcr when releasing tag

Should support at least ghcr, linux/amd64 and linux/arm64

**Comment by chrisgoffinet** [comment]
Here is an example run from my fork:

https://github.com/ThreeCommaIO/tailscale/runs/4088041678

**Comment by DentonGentry** [comment]
Could be implemented in build server.

**Comment by chrisgoffinet** [comment]
I'll close this out
