### ISSUE TITLE
High CPU Usage on MacOS 11.6 Big Sur

### ISSUE THREAD

**Issue by hadican** [tailscale/tailscale#3252]
### What is the issue?

![tailscale-high-cpu](https://user-images.githubusercontent.com/10237009/140040157-edd87e1b-b178-4d09-b644-19d1fc832b0c.png)
Sometimes, CPU goes up to 300% usage and stuck there. I cannot do anything, computer freezes.

As far as I've checked, IPNExtension belongs to Tailscale.

The attached bug report taken after 30 mins / 1 hour later when the problem occurred.

MacOS 11.6 Big Sur
2,2 GHz 6-Core Intel Core i7
16GB DDR4 Memory
Tailscale 1.16.1

### Steps to reproduce

It's an intermittent issue. I don't know when it happens or what triggers it.

### OS

macOS

### OS version

Big Sur 11.6

### Tailscale version

1.16.1

### Bug report

BUG-e720101fcf6a69fecc4544e0bd30706d26b833ce0f33ac7cc48103088e215c5b-20211103100242Z-73745b90b3126eff

**Comment by DentonGentry** [comment]
This looks similar to #1526, though a workaround was delivered in 1.16 which was expected to keep it from manifesting. Could you run `systemextensionsctl list` ? This show the version of the network extension on your system; we'd expect to see 1.16. If we see an earlier version has gotten stuck, that would explain why the symptom still occurs.

**Comment by hadican** [comment]
@DentonGentry Returns: `0 extension(s)`

**Comment by hadican** [comment]
Another bug report, while its happening:
`BUG-e720101fcf6a69fecc4544e0bd30706d26b833ce0f33ac7cc48103088e215c5b-20211104090724Z-4ae2798375e836dd`

**Comment by alimoeeny** [comment]
A similar HUGE cpu usage happens to me when I am connected to iphone hotspot and using exit node at the same time, ONLY when I disconnect from the hotspot and reconnect.

**Comment by DentonGentry** [comment]
MacOS app version 1.32.1 and later contain a fix for [#5879](https://github.com/tailscale/tailscale/issues/5879), which looks like it might have the same root cause as this.

I'm going to mark this fixed because several of the earlier reports look very much like https://github.com/tailscale/tailscale/issues/5879. If you note new instances of high CPU usage please open a new bug, there are too many issues conflated in this one.
