### ISSUE TITLE
No checksums on packages download page

### ISSUE THREAD

**Issue by MarkoPaasila** [tailscale/tailscale#327]
I was looking to verify the sha256 sum of the tar.gz the Archlinux [pkgbuild](https://aur.archlinux.org/packages/tailscale/) downloads but found none on https://pkgs.tailscale.com/. I would expect it to be there as a good security practice, especially for security related software like tailscale.

**Comment by bradfitz** [comment]
I suppose that's easy enough to add, but curious: what's your threat model?

/cc @danderson

**Comment by DentonGentry** [comment]
Closing during bug scrub.
