### ISSUE TITLE
Package tailscale_1.16.2_x86_64.rpm is not signed

### ISSUE THREAD

**Issue by santschi** [tailscale/tailscale#3276]
### What is the issue?

The fedora repo contains at least one unsigned package: tailscale_1.16.2_x86_64.rpm

`dnf install tailscale ` fails when GPG check is enabled.

### OS

Linux

### OS version

fedora 34

### Tailscale version

1.16.2

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1882
