### ISSUE TITLE
Magic DNS very unstable on Chrome OS/ARC

### ISSUE THREAD

**Issue by leo60228** [tailscale/tailscale#3281]
### What is the issue?

On a Samsung Chromebook 3 (`celes`) Tailscale DNS generally has much higher latency than the system resolver, and frequently drops out entirely requiring Tailscale to be disabled and reenabled. When this happens, Tailscale itself generally still works.

### Steps to reproduce

Use Tailscale on a Chromebook for a few hours.

### OS

Android, Other

### OS version

Chrome OS 94.0.4606.104

### Tailscale version

1.16.0

### Bug report

BUG-e719cfbb6a28825a1e2e2419648a9748f924f7741813159669ce9eb268d952e3-20211108140109Z-8f547f2f6390bff8

**Comment by bradfitz** [comment]
Is this related to suspends/resumes? Or is that a few hours of uninterrupted (non-sleeping) use?

**Comment by leo60228** [comment]
From what I've noticed, there are frequently issues after a resume, but this isn't a guarantee (resumes are sometimes fine, and identical issues sometimes occur during uninterrupted use).

**Comment by DentonGentry** [comment]
I think we'll handle this as part of https://github.com/tailscale/tailscale/issues/2382
