### ISSUE TITLE
win: add Manufacturer metadata?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3287]
Our binary/service apparently has a Publisher, but not a Manufacturer?

<img width="557" alt="manufacturer" src="https://user-images.githubusercontent.com/2621/141206590-f9746c25-141a-4c7a-9f29-1acce7820368.png">

/cc @dblohm7

**Comment by DentonGentry** [comment]
Our software is artisanal, bespoke, hand-crafted with love and not mass produced in some factory.
Good to see the Task Manager acknowledging this.

**Comment by bradfitz** [comment]
Oh, this might be a dup of #1286.

**Comment by dblohm7** [comment]
Highly likely.

**Comment by DentonGentry** [comment]
Dup of https://github.com/tailscale/tailscale/issues/1286
