### ISSUE TITLE
After removing the node from network, it still shows the connected in admin console.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3297]
### What is the issue?

The customer is reporting the device is removed from the network but still shows connected in the admin console

From Customer :
I'm using your API to check if my machines are still connected. To be specific I'm using the property "lastSeen" which is also visible on the https://login.tailscale.com/admin/machines page. 
But for some odd reason even if I completely remove my device from the network, tailscale is still under the impression that it is still somehow connected.

It is taking much longer than 10mins. I disconnected my devices an hour ago and tailscale is still frequently updating the "last seen" value every 1-2minutes. 
Should the "last seen" value not just have the timestamp where the device was detected by tailscale? 

### Tailscale version

1.16.2

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3u3m9)

**Comment by bradfitz** [comment]
This is because the keep-alive loop in control bumps LastSeen unconditionally right now. The code to check tcpstats and send ping challenges (to cause new http2 requests on same TCP connection) if tcp acks don't seem advancing was never finished.

**Comment by DentonGentry** [comment]
I think this was addressed by adding `{"KeepAlive":true}` mapresponses.

Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
Next bug scrub; closing.
