### ISSUE TITLE
FR: Machine List UI and Removal Message

### ISSUE THREAD

**Issue by MIKEPArA** [tailscale/tailscale#3298]
### Tell us about your idea!

More spacing between machine names in Machine List UI. Actions are performed on the machine name or within that same column. Include Machine Name In Removal Message.

### What are you trying to do?

AWS EC2 instances spawn randomly and can pile up in machine list UI. For those not using ephemeral keys it would be nice to remove them manually without accidentally removing another machine (which has happened). 

Actions are performed on the far right and not near the machine name. 

Also would be nice to have a the machine name in the removal message. 

### How should we solve this?

* Display the machine name in the removal message. 
* Place actions near machine name or have multi select checkbox for machine you wish to remove or perform actions on?

### What is the impact of not solving this?

* When aligning my cursor up with the action bar on the far right, I don't have to pray to the almighty tailscale gods that I am not removing a production deployed machine in Japan when in reality I'm trying to remove an EC2 instance machine that is no longer alive.

* If the alert notification/message after removing a machine included the machine name in the message it will help lower my blood pressure by confirming to me which machine I just removed. 

### Anything else?

Everything else is dandy! Thank You Tailscale Team!

**Comment by sonovawolf** [comment]
Thank you, this is all good feedback! Low-hanging fruit would be to show a gray background for the hovered row, which should help remove some of the guesswork. Here's a very quick mock:

![image](https://user-images.githubusercontent.com/3002490/141533073-17b82dcc-dcc6-471b-89de-733b1fae8ef4.png)

Roger on showing the name, we should just do that.

**Comment by sonovawolf** [comment]
Happy to report that we've added the row highlighting on hover in https://github.com/tailscale/corp/pull/3082, the machine name in all the dialog titles in https://github.com/tailscale/corp/pull/3173, and a confirmation dialog for the removal of machines in https://github.com/tailscale/corp/pull/3241.

Kudos to @rosszurowski for going the extra mile: holding the `alt` button will make the "Remove" option instantaneous (instead of bringing up the confirmation dialog).

**Comment by rosszurowski** [comment]
We've made the change in our codebase. It should be live on login.tailscale.com/admin the next time we do a deploy, sometime in the next day or so.
