### ISSUE TITLE
Nodes created using ephemeral key show "Copied Tailscale IPv6 address" when the IPv4 address is actually copied

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#3300]
### What is the issue?

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/18581859/141653910-95f449c9-7410-42ac-a8bb-320d7c37ab1d.png">

I added Tailscale to my Fly.io app using an ephemeral key. As far as I know, nodes created using ephemeral keys must be IPv6 only but I see a IPv4 address. Clicking on the copy button shows a message on the bottom right that IPv6 address is copied, which isn't the case.

On the main node page, copying the addresses looks okay:

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/18581859/141653973-b43a0ebb-db30-4af3-b983-eb6f908447f8.png">

**Comment by DentonGentry** [comment]
When first introduced, ephemeral authkeys would only allocate an IPv6 address. This led to enough difficulty in using them that we changed this a few weeks ago to allocate both an IPv4 and IPv6 address. So the IPv4 address shown is real, and can be used.

That the message says "Copied Tailscale IPv6 address" is a visual bug we should fix.

**Comment by arunsathiya** [comment]
@sonovawolf Just to confirm, will it be a while for changes to reflect on the website? I am still seeing the incorrect message when I copy the IP address for an ephemeral node:

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/18581859/142441210-ea8907dd-0cd3-406b-975e-6ba2c347f5cc.png">

**Comment by DentonGentry** [comment]
The code is checked in but not deployed to production. I'd expect it to deploy by the end of the week.
