### ISSUE TITLE
derper@main -verify-clients failes with "key hex string doesn't have expected type prefix nodekey:"

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#3305]
### What is the issue?

Splitting out from #3024 :

-verify-clients flag to start DERP, the log keeps saying "rejected: failed to query local tailscaled status: key hex string doesn't have expected type prefix nodekey:"

### OS

Linux

### Tailscale version

main branch

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ujkh)

**Comment by bradfitz** [comment]
@danderson anticipated this (to some degree) when he changed the serialization of nodekeys away from base64 to hex. We considered it might break some people, but we forgot about it breaking derper.

The answer is they can rebuild derper, which we already warn somewhere that they'll need to occasionally do.

One day we should ship derper in its own Linux package (or in our existing tailscale package)

**Comment by danderson** [comment]
Yeah, this was anticipated/accepted breakage of an unstable API. My mistake on not realizing that standalone derper would be affected. Rebuilding derper from head should fix.

**Comment by mudlee** [comment]
Guys, I'm really struggling with this, may I ask your help? I'm trying to register my node via headscale's http API like this:

```bash
curl -v -H "Authorization: Bearer MY_API_KEY" -X POST http://localhost:8080/api/v1/machine/register?user=my_user&key=nodekey:a07f2555e53a9e08ff1b670d4579902fa395c28d59ffba49029f51fe20d45b27
```

The string `a07f2555e53a9e08ff1b670d4579902fa395c28d59ffba49029f51fe20d45b27` came out from the command below:
```bash
tailscale up --login-server https://my server --reset

To authenticate, visit:
	https://my_server/headscale/register/nodekey:a07f2555e53a9e08ff1b670d4579902fa395c28d59ffba49029f51fe20d45b27
```

What do I mess up? I get this error:
```bash
{"code":2,"message":"key hex string doesn't have expected type prefix nodekey:","details":[]}
```
