### ISSUE TITLE
FR: Prioritization of DNS Servers

### ISSUE THREAD

**Issue by jonathan-wondereur** [tailscale/tailscale#3317]
### Tell us about your idea!

Prioritize DNS servers based on proximity (or latency).

### What are you trying to do?

I have several servers spread over the world set up to act as DNS servers using PiHole. I have set their Tailscale IPs as the DNS servers in the DNS settings of Tailscale. However, there seems to be no way to give priority to the DNS servers with the lowest latency (those closest to the Tailscale client).

### How should we solve this?

Prioritize the DNS servers with the lowest latency and fall back to other DNS servers (if some are not working). 

### What is the impact of not solving this?

Some DNS requests can be slow. Currently, I am just waiting for the slower DNS requests.

**Comment by bradfitz** [comment]
The Tailscale client doesn't use your DNS servers in order: it races them all at once and picks the fastest.

In the future we plan to make it adaptive to learn which is the fastest but for now it just duplicates the DNS queries across all of them (with some special cases for recognizing popular big DNS providers and knowing when it's redundant to send them out duplicated)

So any slowness you're seeing isn't related to ordering.

**Comment by jonathan-wondereur** [comment]
Good to know, the slowness must all be related to #3318 then. Thanks.

**Comment by DentonGentry** [comment]
Closing based on https://github.com/tailscale/tailscale/issues/3317#issuecomment-971711107
