### ISSUE TITLE
Tailscale doesn't reprogram systemd-resolved after a restart

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3327]
### What is the issue?

When systemd-resolved restarts, it drops all its dynamic configuration and expects clients to notice + resubmit their config. We don't, so if systemd-resolved restarts, tailscale's DNS settings are broken until either a tailscaled restart, or until a network reconfiguration event makes us reprogram DNS.

We should set up a DBus watch on the resolved service, and resubmit DNS configuration when it changes state.

### OS

Linux

### OS version

All recent distros

### Tailscale version

1.16.2

**Comment by danderson** [comment]
When systemd-resolved restarts, DBus emits the following broadcast signals that we can listen for:

```
signal time=1637108900.195203 sender=org.freedesktop.DBus -> destination=(null destination) serial=524 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.resolve1"
   string ":1.300"
   string ""
signal time=1637108900.258928 sender=org.freedesktop.DBus -> destination=(null destination) serial=527 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.resolve1"
   string ""
   string ":1.301"
```

Strings like `:1.300` are ephemeral bus names that every bus client gets, whereas strings like `org.freedesktop.resolve1` are well-known service names that a client can claim for themselves. These signals indicate the change in ownership of the well-known name, from the old ephemeral bus ID to nil (nobody has this name) to a new bus ID (the restarted resolved reclaiming its service name).

Watching for this signal and reprogramming DNS whenever NameOwnerChanged fires with a non-empty `new` field should do the trick.

**Comment by danderson** [comment]
Complexity: ideal place to set this up is inside the resolvedManager, at the lowest layer of the stack. But that means errors won't propagate cleanly any more, because all the DNS management stuff is assumed to be stateless. But to do it "right" with the current setup would involve bubbling that notification all the way back up to wgengine, and then all the way back down through the DNS stack... Which is where the notification first came from.

Maybe just health.SetDNSHealth from inside the resolvedManager instead?...

**Comment by bradfitz** [comment]
Which error needs to propagate?

Naively, I assumed resolvedManager would both always track whatever its last desired config is and also start a goroutine listening to the dbus broadcast signals, and upon any restart, replay the last thing it got.

**Comment by danderson** [comment]
Yes, that's my plan. But what if one of the 4-5 RPCs needed to restore state fails? Currnently those RPCs only get invoked from the SetDNS codepath, which bubbles errors back up to wgengine. Once we start running a gorouting and doing async reconciliation, that error path goes away. Enough to just log? That means the health(dns) output may not be accurate any more.

This is a general problem in wgengine, where the leaf components were assumed to be stateless and driven by wgengine, when in fact most of them need to monitor the system and reconcile asynchronously a bunch.

**Comment by bradfitz** [comment]
Oh, gotcha. Now I understand this:

> Maybe just health.SetDNSHealth from inside the resolvedManager instead

Yeah, that works. We might need to add another key or something, so both entities can own it.

Or maybe some registration mechanism to ask `health` for a handle that you can then set health vs error (with a message), so then just `resolvedManager` can ask for a health handle and use that private one.

**Comment by danderson** [comment]
Someday, a neat thing to mimick would be an idea from Illumos's Fault Management Architecture, which is to have a hierarchy of things reporting health/unhealth. That makes it a bit easier to reason about "if this node in the tree is sad, probably all its children are too". So, what you said wrt registration, but with the ability to hook off a parent, so you can have something like engine/dns/resolver, engine/dns/os, engine/router, ...

Anyway, for now, I'll make a new DNSOSHealth or somesuch and hook things up that way.

**Comment by bradfitz** [comment]
> which is to have a hierarchy of things reporting health/unhealth. That makes it a bit easier to reason about "if this node in the tree is sad, probably all its children are too"

I have such a hierarchical dependency tracking system for my home monitoring.  :)
