### ISSUE TITLE
FR: Untrusted nodes

### ISSUE THREAD

**Issue by mayakacz** [tailscale/tailscale#3352]
### Tell us about your idea!

Untrusted nodes

### What are you trying to do?

Lock down nodes so that they can only receive communications and not initiate them.

From [Twitter](https://twitter.com/arturoleon/status/1461476014740045826):
> Those are nodes that I only want to use as exit nodes, and I don't need them to access other nodes. Those nodes are open to the internet (serving traffic), and I'm concerned that if someone compromises them, they will have access to my network.

### How should we solve this?

'Quarantine' nodes within a network.

### What is the impact of not solving this?

Workaround is using a second user & sharing a node, or putting the node behind a subnet router.

**Comment by bradfitz** [comment]
We do that already for shared nodes. Any shared nodes added to your tailnet are quarantined.

As for the exit node case within their own tailnet: they can tag them + use ACLs, no?

**Comment by mayakacz** [comment]
>As for the exit node case within their own tailnet: they can tag them + use ACLs, no?

But that would still allow bi-directional traffic. I believe the ask is uni-directional traffic.

**Comment by bradfitz** [comment]
No, ACLs are about limiting who can initiate flows.

Of course you always need bidi traffic to e.g. ACK TCP packets or even being an exit node. But ACLs prohibit opening new TCP flows from the side that's not allowed.

**Comment by apenwarr** [comment]
Right, it would be a serious security problem if ACLs allowed, say, production servers to make outgoing connections back to client devices just because end users are allowed to make connections into production servers.

**Comment by mayakacz** [comment]
Having a bit of a non-caffeinated moment this morning then, closing this.

**Comment by renchap** [comment]
I am commenting here as I have the same need, but cant find a way to make it work.

One server is shared with multiple users, not using Tailscale (ssh login allowed over public internet).
I would like this server to join my Tailnet, but only for me to be able to connect to it using Tailscale, not allowing the other users of this server to connect to the other devices in my tailnet.
All other devices in my tailnet should still be allowed to connect to each other.

Allowing to manually quarantine this server would allow me to do this. With ACLs, I dont see a way to do it while allowing the other devices to connect to each other (except by assigning specific tags to each device, which would be burdensome).

Am I missing something?

**Comment by bradfitz** [comment]
@renchap, we don't track closed bugs on any dashboards, etc. I saw your comment, but it'd be better if you opened a new issue.

It sounds like you want support for multi-user Linux systems, which is unrelated. Currently we assume that a machine is used by one human on both Linux and Windows. But let's discuss on a new bug.
