### ISSUE TITLE
Switching GitHub users on iOS app doesn't work

### ISSUE THREAD

**Issue by mayakacz** [tailscale/tailscale#3354]
### What is the issue?

When you log in with a GitHub account on the iOS app, then `Reauthenticate` to log in again, you aren't able to log in as a different GitHub user.

This persists after deleting & re-installing app.
* Not sure if there is an iOS level setting to clear (couldn't find it)
* The `cancel` option in GitHub auth serves `internal server error`. Not sure if it's supposed to offer a step back

### Steps to reproduce

https://user-images.githubusercontent.com/15946341/142652986-01ecf837-263d-4a98-a169-3cc8ff52404a.mov

### Are there any recent changes that introduced the issue?

Recently switched from unstable 1.17 release to stable 1.16 release

### OS

iOS

### OS version

iOS 15.1

### Tailscale version

1.16.1

**Comment by mayakacz** [comment]
This blocks me from demo'ing Tailscale on mobile with my demo environment in GitHub.

**Comment by jeremiahpeel** [comment]
Also affected by this - have changed Github account, and dologin to Github app on iPad with the new account, but am unable to authenticate in Tailscale app, as the Oauth screen remembers the old account only.
iOS 15.4
Tailscale 1.22.0

**Comment by DentonGentry** [comment]
> have changed Github account

If you mean changed the name of your GitHub profile, that is a slightly different issue which support@tailscale.com can resolve.

**Comment by DentonGentry** [comment]
> iPad: Settings, Safari, Advanced, Website Data, Search "github"
> Then delete the github.com entry - it is these Safari cookies that the Tailscale app is using.

We have since reduced the lifetime of those cookies to a handful of seconds.

I believe this issue was fixed in Jan 2023.

**Comment by biel-michael** [comment]
> Also affected by this - have changed Github account, and do login to Github app on iPad with the new account, but am unable to authenticate in Tailscale app, as the Oauth screen remembers the old account only. iOS 15.4 Tailscale 1.22.0
> 
> **Update: I found a workaround** iPad: Settings, Safari, Advanced, Website Data, Search "github" Then delete the `github.com` entry - it is these Safari cookies that the Tailscale app is using. Then the next attempt at `Reauthenticate `gives a fresh Github login screen!!

At the end I still used this fix for iPhone logins!
