### ISSUE TITLE
Tailscale not working on Unraid after upgrade to 1.18

### ISSUE THREAD

**Issue by 0xcd0e** [tailscale/tailscale#3358]
### What is the issue?

Tailscale fails to start after the upgrade with error:

```
2021/11/19 19:04:13 logtail started
2021/11/19 19:04:13 Program starting: v1.18.0-t71f1dd5aa, Go 1.17.3: []string{"tailscaled"}
2021/11/19 19:04:13 LogID: 5xxx83
2021/11/19 19:04:13 logpolicy: using system state directory "/var/lib/tailscale"
2021/11/19 19:04:13 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2021/11/19 19:04:13 router: v6nat = true
2021/11/19 19:04:13 dns: [rc=unknown ret=direct]
2021/11/19 19:04:13 dns: using *dns.directManager
2021/11/19 19:04:13 link state: interfaces.State{defaultRoute=br0 ifs={br0:[XYZ] docker0:[172.17.0.1/16] virbr0:[192.168.122.1/24]} v4=true v6=true}
2021/11/19 19:04:13 magicsock: disco key = d:4XXX0
2021/11/19 19:04:13 Creating wireguard device...
2021/11/19 19:04:13 Bringing wireguard device up...
2021/11/19 19:04:13 Bringing router up...
2021/11/19 19:04:13 external route: up
2021/11/19 19:04:13 wgengine.NewUserspaceEngine(tun "tailscale0") error: address family not supported by protocol

2021/11/19 19:04:13 wgengine.New: address family not supported by protocol
2021/11/19 19:04:13 flushing log.
2021/11/19 19:04:13 logger closing down
2021/11/19 19:04:13 logtail: dialed "log.tailscale.io:443" in 469ms
```

Seems to me like to check _checkIPRuleSupportsV6_ does not work correctly, on 1.16.2 it returned false, but on 1.18 it returns true but the call to NewUserspaceEngine fails.
Even when using the TS_DEBUG_USE_IP_COMMAND env var, _checkIPRuleSupportsV6_ does not use the ip command, the code has been removed completely

### Steps to reproduce

Deploy the docker container on Unraid 6.9.2

### Are there any recent changes that introduced the issue?

Upgrade to 1.18, worked fine before

### OS

Linux

### OS version

Unraid OS 6.9.2

### Tailscale version

1.18

### Bug report

BUG-5d912d4d04915d05d38423fbd11ab174d5a2fa9201c59b9a20ed888e0a393783-20211119191035Z-90ad5c9ebbc7b097

**Comment by 0xcd0e** [comment]
The log on version 1.16.2 says
router: disabling tunneled IPv6 due to system IPv6 config: kernel doesn't support IPv6 policy routing: ip -6 rule failed: RTNETLINK answers: Address family not supported by protocol
instead of 
router: v6nat = true

**Comment by bradfitz** [comment]
I sent https://github.com/tailscale/tailscale/pull/3359 to fix this.

We'll then roll an unstable build you can test and then we'll cherry-pick it to 1.18.1.

**Comment by apocnz** [comment]
Funny enough mine did that with IPv6 enabled in the kernel.  Removed Ipv6 support and its happy as now,

**Comment by bradfitz** [comment]
Okay, 1.19.10 is built now for unstable at https://pkgs.tailscale.com/unstable/ (which is effectively 1.18.0 with these fixes). Can you try that and see if it works now?

**Comment by 0xcd0e** [comment]
I cant deploy those packages directly on unraid, but i have cloned the master branch at commit def659d1ec914ac8a47a056534cf7ef54a30d295 and created a docker image from that. It looks like its working now, even without TS_DEBUG_USE_IP_COMMAND

**Comment by bradfitz** [comment]
1.18.1 is now out with the fix. I'm going to close this, but let me know if 1.18.1 doesn't work for some reason.
