### ISSUE TITLE
iOS: incorrect message "No Internet Connection. Tailscale is paused while your device is offline."

### ISSUE THREAD

**Issue by sa1** [tailscale/tailscale#336]
**Describe the bug**
Tailscale loses connection after enough time in background, either killed or because of network changes. 

**To Reproduce**
1. Activate vpn through Tailscale
2. Don’t open app again for some indefinite long amount of time, say 1 day. 
3. Reopen app after seeing that vpn is no longer active.
4. See error: `No Internet Connection. Tailscale is paused while your device is offline. Please reconnect to the internet.`

**Expected behavior**
The vpn connection should always remain on.

**Screenshots**
After opening app again, this error is shown:

![IMG_0460](https://user-images.githubusercontent.com/557509/80595497-5ba8f580-8a14-11ea-9451-f8d4f15b6356.PNG)

Then the vpn reconnects.

**Version information:**
 - Device: iPhone X
 - OS: iOS
 - OS version: 13.4.1
 - Tailscale version: 0.98.12

**Additional context**
There is an on-demand mode for vpn's in iOS, maybe tailscale can use it to remain always on - or at least have it an option.

**Comment by apenwarr** [comment]
This is two separate bugs. I've split the one about the VPN backend crashing in the first place into #337. Let's leave this bug open for the separate problem that the Tailscale UI lies about the online connection status.  The above screenshot is from Tailscale 0.98-12.

**Comment by rajatjindal** [comment]
Hi @apenwarr 

Could you please help identify a workaround (beside restarting iphone, which works but is very painful)

If anything i can do on my phone to help identify root cause, i will try to do my best.

I cant wait to show this off (and other side projects i am doing on my personal laptop) to friends and family while not on my laptop

Many thanks
Rajat Jindal

**Comment by bradfitz** [comment]
Have you tried disable VPN in the iOS Settings app and the swiping away the Tailscale (frontend) app from the list of recent apps?

**Comment by rajatjindal** [comment]
Yeah i tried that but still does not work. Rebooting phone always work

**Comment by rajatjindal** [comment]
Are there plans to opensource tailscale ios app? I am no expert, but would be very happy to try debugging the app

**Comment by bradfitz** [comment]
This is actually already fixed. It's just not released or through approvals and in the store yet.

No plans to open source the iOS app. The Android app will be open source, though.

**Comment by rajatjindal** [comment]
Got it, thank you. Will wait for new version

**Comment by apenwarr** [comment]
New version is released, please try again :)

**Comment by rajatjindal** [comment]
Thank you for releasing new version. I can confirm it works for me now. :thumbsup:
