### ISSUE TITLE
wgengine/router test fails on ppc64le 

### ISSUE THREAD

**Issue by panekj** [tailscale/tailscale#3360]
### What is the issue?

`wgengine/router` test fails on ppc64le due to `netlink` dependency

```
--- FAIL: TestDebugListRules (0.00s)
    --- FAIL: TestDebugListRules/v4 (0.00s)
        router_linux_test.go:796: address family not supported by protocol
FAIL
FAIL	tailscale.com/wgengine/router	0.037s
```

https://gitlab.alpinelinux.org/panekj/aports/-/jobs/542353

### Steps to reproduce

Run `go test ./...` on ppc64le architecture

### Are there any recent changes that introduced the issue?

https://github.com/tailscale/tailscale/commit/d36c0d3566ee097fe69882771835a2f1434d0fbc

### OS

Linux

### OS version

Alpine Linux 3.15_rc4 (Edge)

### Tailscale version

1.18.0

**Comment by bradfitz** [comment]
Does the test pass in your CI on other platforms?

**Comment by panekj** [comment]
Yes, you can see [here](https://gitlab.alpinelinux.org/panekj/aports/-/pipelines/100233) all other arches pass successfully

**Comment by bradfitz** [comment]
Well that's weird.

Maybe the netlink package has a bug on that platform.

I guess for now we can make that arch fall back to the code path that runs the "ip" command instead. (We kept that code in out of paranoia)

**Comment by bradfitz** [comment]
@panekj, do you have the Linux kernel config for your ppc64le builder machine? Maybe it just lacks policy routing support altogether.

Does it have IP_MULTIPLE_TABLES set?

**Comment by bradfitz** [comment]
1.18.1 is out now. Try again?

**Comment by panekj** [comment]
@bradfitz that seems to fix the issue, but it also broke s390x now
```
--- FAIL: TestIgnoreLocallyBoundPorts (0.00s)
    portlist_test.go:43: didn't expect to find test's localhost ephemeral port
FAIL
FAIL	tailscale.com/portlist	0.031s
```

**Comment by bradfitz** [comment]
> @bradfitz that seems to fix the issue

Thanks for confirming! I'll close this bug.

> but it also broke s390x now

We didn't change anything about s390x or the portlist code in 1.18.1 or even between 1.16.0 and 1.18.0.

I suspect it's just a test flake. Normally I'd care more about tracking to down (we hate flaky tests) but in this case s390x isn't an architecture we have access to and thus don't support, so unfortunately debugging that probably falls to you. Or you can just kick the CI to make it run again?

**Comment by panekj** [comment]
I'll try figuring it out
