### ISSUE TITLE
Tailscale cannot start on Windows7 -64bit

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3372]
### What is the issue?

Tailscale installation fails with DLL error.

Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\Windows\system32>tailscaled
logtail started
2021/11/22 15:56:32 winhttp: Open: Parametro non corretto.
tshttpproxy: winhttp: GetProxyForURL("https://log.tailscale.io/c/tailnode.log.ta
ilscale.io/b09ea3567e31d8240a49eac01ae51f89ac093647ed51d17612d5f75ac2b93458"): E
RROR_INVALID_PARAMETER [unexpected]
Program starting: v1.18.0-t22d969975-g7022e5a4c, Go 1.17.2-ts7037d3ea51: []strin
g{"tailscaled"}
LogID: 337e174fa56dcb8c833c8824b5c8e4ab74da2e50504f3bb086b7d9b893a1b9f4
logpolicy: using dir C:\ProgramData\Tailscale
logtail: dialed "log.tailscale.io:443" in 247ms
wgengine.NewUserspaceEngine(tun "Tailscale") ...
flushing log.
logger closing down
panic: Error loading wintun.dll DLL: Unable to load library: Parametro non corre
tto.

goroutine 1 [running]:
golang.zx2c4.com/wintun.(*lazyProc).Addr(...)
        golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/dll.go:60
golang.zx2c4.com/wintun.CreateAdapter({0x11af486, 0xc8f42a}, {0x11af486, 0x9}, 0
xc000033130)
        golang.zx2c4.com/wintun@v0.0.0-20211104114900-415007cec224/wintun.go:92
+0x1a5
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID({0x11af486, 0xc05f09c8
93d57808}, 0x0, 0x500)
        golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/tun/tun_wi
ndows.go:71 +0x46
golang.zx2c4.com/wireguard/tun.CreateTUN(...)
        golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/tun/tun_wi
ndows.go:63
tailscale.com/net/tstun.New(0xc8fbbf, {0x11af486, 0x9})
        tailscale.com@v1.18.0/net/tstun/tun.go:64 +0x74
main.tryEngine(0x11cd75a, 0xc000010000, {0x11af486, 0x9})
        tailscale.com@v1.18.0/cmd/tailscaled/tailscaled.go:447 +0x1dc
main.createEngine(0xc00000e000, 0x12a05f200)
        tailscale.com@v1.18.0/cmd/tailscaled/tailscaled.go:398 +0x1ce
main.run()
        tailscale.com@v1.18.0/cmd/tailscaled/tailscaled.go:308 +0x4dc
main.main()
        tailscale.com@v1.18.0/cmd/tailscaled/tailscaled.go:172 +0x77f

C:\Windows\system32>

### Steps to reproduce

Isn't reproducible in all environments. The user had one of the other Windows 7 64 bit working fine and this one has an issue.

Also, the user had Radwin VPN installed which we ended up uninstalling and reinstalling Tailscale again, still issue persists.

Tailscale does not show tray icon or create Tailscale adapter.

### OS

Windows

### OS version

7-64bit

### Tailscale version

1.18

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3vro1)

**Comment by bradfitz** [comment]
Ignore the `tshttpproxy: winhttp: GetProxyForURL(...): ERROR_INVALID_PARAMETER [unexpected]` for the purpose of this bug.

That's a separate bug.

**Comment by dblohm7** [comment]
@darshinimashar Do you know whether the user originally installed a previous version, and then upgraded to 1.18, or did they start with 1.18?

**Comment by DentonGentry** [comment]
The original email says, "hello , i ve tried to install tailscale (v1.16.2 / 1.8.7 / 1.8.3) on my laptop with win 7 64bit..."

They didn't exactly say, but I'd suspect they installed each version on top of the other without uninstalling.

**Comment by dblohm7** [comment]
I have tried to reproduce this but cannot.

I am suspicious about the missing `wintun.dll`. Could that machine be running an AntiVirus program that flagged wintun as a false positive and quarantined it?

**Comment by DentonGentry** [comment]
Cannot reproduce
