### ISSUE TITLE
Enable HSTS on DERP servers

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3373]
### Tell us about your idea!

DERP servers need HSTS.

### What are you trying to do?

The automated security scanners we use for compliance things keep panicking when they discover that our DERP servers, which do not serve anything of value over HTTPS to _browsers_, don't set HSTS headers. Since HSTS has no effect on non-browser clients, and those are the only ones talking to DERP servers for non-debug purposes, we might as well enable HSTS to quiet the automation, rather than have to continually mark them as "exceptions" requiring paperwork to justify.

**Comment by bradfitz** [comment]
This would break plain HTTP access to http://derp10.ts.tailscale.com/debug/varz access over Tailscale from browsers, no?

**Comment by danderson** [comment]
It shouldn't, because you don't access derp10.ts.tailscale.com over HTTPS (no certs have that name), so HSTS will never kick in. URLs need to be reachable over HTTPS for HSTS to kick in, so it'll only happen for the public URLs (e.g. https://derp10.tailscale.com).

But to be sure, I'm deploying this the same way I did HSTS on our other properties: start with a 10min HSTS timeout, so we can look around and see if anything breaks.

**Comment by bradfitz** [comment]
Oh, so it's not wildcard `*.tailscale.com`? I'm confusing an earlier proposal I guess.

**Comment by danderson** [comment]
Yeah, HSTS works based on whatever domain you use to access the site. What I'm doing here is making visits to derpX.tailscale.com say "force HTTPS for derpX.tailscale.com and *.derpX.tailscale.com".

The tricky one you're thinking of is HSTS on https://tailscale.com, because if I `includeSubdomains` there, then it would force HTTPS on everything in our domain, including the semi-private ts.tailscale.com tree. I'm not doing that in this change :)

**Comment by danderson** [comment]
Deployed with a 10min HSTS lifetime to derp10.tailscale.com as a canary. If all goes well, will crank the expiry up to 2y (HSTS best practice) and roll out to all derps.

/cc @mayakacz
