### ISSUE TITLE
consider coalescing netmap diff application

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#3377]
### What is the issue?

Investigating other logs, I found:

> monitor: time jumped (probably wake from sleep); synthesizing major change event

followed by 32 stanzas like `magicsock: got updated network map`, `wgengine: Reconfig done` over the course of the next 600ms.

It looks like the machine slept for a little while, managed to resume its TCP connection to control, received a slew of incremental netmap updates, and then applied them one at a time.

We (presumably) got to the correct state at the end but it is pretty inefficient, and the thrashing of the wireguard-go magicsock statement machine definitely seems like it is temping fate.

We should consider waiting up to (say) 100ms before applying a network map, in case a new network map is going to immediately displace it. (Each inbound netmap shouldn't reset that clock, so that receiving a new network map every 90ms doesn't starve updates forever.)

cc @bradfitz @dan

**Comment by DentonGentry** [comment]
I think this was resolved in 5/2022 by a substantial rearrangement of the coordination server. It no longer produces long sequences of incremental netmap updates.
