### ISSUE TITLE
iOS: TestFlight Beta

### ISSUE THREAD

**Issue by nfrede** [tailscale/tailscale#338]
Any chance of getting a public or other TestFlight ring going for iOS? It would be nice not to have to wait around for the AppStore approval process for testing improvements in the future ;)

**Comment by danderson** [comment]
Sadly we need approval from Apple even for a beta track. We do have a beta track, but it really just _adds_ delays to releases, rather than cutting them down.

There is one TestFlight track that requires no approval to push to, but it's meant explicitly for internal use by Tailscale, and I'm told Apple gets cranky if you use it as an external testing channel.

**Comment by nfrede** [comment]
Understandable, thanks for taking the time to respond. Loving the new DNS iOS features. Ez PiHole everywhere!

**Comment by apenwarr** [comment]
This link should work nowadays for joining our iOS Beta Testflight: https://testflight.apple.com/join/tLcYLZJV

**Comment by bradfitz** [comment]
I think the main TODO item here is to document this somewhere.

Maybe a FAQ item like "How do I beta test?" with the various links.

/cc @rosszurowski

**Comment by rosszurowski** [comment]
I'll add a KB article, or heading in some document about it. It'd be handy to reference in articles like our [Magic DNS overview](https://tailscale.com/kb/1081/magic-dns) too.

Long-term, it'd be nice to have an option on [the download page](https://tailscale.com/download) for opting into the beta track, but KB seems like the right place to start.

**Comment by rosszurowski** [comment]
An article about [installing beta clients](https://tailscale.com/kb/1083/install-beta) (including iOS) is now live on the site. It's linked from the [Magic DNS article](https://tailscale.com/kb/1083/install-beta) which, as of lately, is the primary reason people are asking for betas.
