### ISSUE TITLE
FR: Distribute tailscale-k8s container image

### ISSUE THREAD

**Issue by ankushg** [tailscale/tailscale#3385]
### Tell us about your idea!

Distribute a pre-built `tailscale-k8s` container image (just like you already distribute `tailscale`)!

### What are you trying to do?

I'm trying to run tailscale in a lightweight k8s cluster with minimal setup

The current steps require me to build a container image and publish it to my own container registry: https://github.com/tailscale/tailscale/tree/main/docs/k8s#setup

This is cumbersome for folks who don't have container registries already setup.

I could understand if the container is supposed to be customized or modified to include secrets or other configuration. But the steps say to publish the image with zero changes to the Dockerfile in that directory - secrets and configuration are read from k8s!

Since no changes to the Dockerfile are needed to support the usual setup, why not publish the prebuilt container image?

### How should we solve this?

Pre-build and distribute the `tailscale-k8s` container image just like you already do with the `tailscale` one!

### What is the impact of not solving this?

Makes running tailscale in k8s more accessible for folks who don't have the resources/time/knowledge to publish their own container images.

**Comment by DentonGentry** [comment]
Do the parameters documented in https://hub.docker.com/r/tailscale/tailscale provide enough to do what you want?
