### ISSUE TITLE
iOS user interface whitespace bug

### ISSUE THREAD

**Issue by eh8** [tailscale/tailscale#3388]
There's a blue gap between the search widget and the list of Tailscale nodes.

<img src="https://user-images.githubusercontent.com/22990581/143038642-5ef5a228-0b82-40c6-970e-a68f5e99ed81.jpeg" width="200">

_sensitive information omitted from above photo_

I'm on iOS 15.1 but it's been a persistent user interface glitch for a few months, back when I was using iOS 14. Happens on both iOS devices I use to test Tailscale with.

For reference, this is what the UI is supposed to look like (taken from App Store page)

<img src="https://user-images.githubusercontent.com/22990581/143039174-70e4196a-4cb2-44e2-946a-b7bf5ca741e6.jpeg" width="200">

**Comment by josharian** [comment]
cc @nickoneill

**Comment by ceiphr** [comment]
Bump.

Experiencing this too.

Lmk if a bug report ID is needed.

**Comment by mihaip** [comment]
Fix should be picked up in the 1.28 release.
