### ISSUE TITLE
Accept Non-CIDR IP ranges in advertise-routes

### ISSUE THREAD

**Issue by ankushg** [tailscale/tailscale#3389]
I'd like to advertise IPs 192.168.1.200-250 on my subnet router, but I can only input routes with CIDR notation

It would be great to support more flexibility here!

**Comment by DentonGentry** [comment]
Could I ask the use-case? You have a set of what are really individual servers to provide connectivity to, which all have IP addresses in the 200-250 range?

The motivation is that `--advertise-routes=10.0.0.200/29,10.0.0.208/28,10.0.0.224/28,10.0.0.240/29,10.0.0.248/31,10.0.0.250/32` is long and not clear what it is doing?

**Comment by DentonGentry** [comment]
192.168.1.200 - 192.168.1.250 as a collection of CIDR routes would be `192.168.1.200/29,192.168.1.208/28,192.168.1.224/28,192.168.1.240/29,192.168.1.248/31,192.168.1.250/32`

https://www.ipaddressguide.com/cidr is useful for this.

**Comment by bradfitz** [comment]
> Maybe for my particular use case, there's a CIDR format that roughly covers 192.168.1.200+?

The ranges that @DentonGentry gave above are the CIDRs that cover your range.

See https://go.dev/play/p/6L0C5J39yAP

**Comment by DentonGentry** [comment]
I think tools like https://www.ipaddressguide.com/cidr or https://go.dev/play/p/6L0C5J39yAP will answer this concern.

**Comment by ankushg** [comment]
Yup those tools are great and can confirm that they worked for my use case!
