### ISSUE TITLE
Test flake: portlist_test.go:33: addProcesses: readdir: readdirent: no such file or directory

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#339]
This error shows up in CI sometimes on Linux. Looks like the way we're using readdir() in /proc on Linux requires us to restart the readdir() operation if the dir changes. We're using this to read through a list of process fds, so if the process being scanned opens or closes a fd during our activity, we'll need to work around it to make this test flake go away.

**Comment by bradfitz** [comment]
Hmmm, weird. I'll look more.
