### ISSUE TITLE
macOS: DNS delay issue while using global nameservers overriding local dns.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3399]
### What is the issue?

 DNS delay issue while using global nameservers overriding local DNS from macOS client. When Tailscale is connected initially, dns queries do not resolve through the global nameservers until ~65 seconds later.

This is not reproducible 100% of the time. There are times when it works right away. But most of the time, the queries do not route to the nameservers right away.

We have 2 global nameservers with a split DNS configured. The 2 nameservers are aws inbound endpoint resolvers.

Client OS : MacOS 10.15.7, with Tailscale DNS settings enabled.
Tailscale : 1.16.2

### Steps to reproduce

Test the DNS resolve after enabling "Override Local DNS".

### OS

macOS

### OS version

10.15.7

### Tailscale version

1.16.2

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3wevl)

More details and troubleshooting can be found in Front.

**Comment by DentonGentry** [comment]
This bug manifested when using the compliance control server, which at the time the bug was filed was running a binary substantially behind the regular control server. We've rectified that now, and I think likely resolved the delay in applying DNS config.
