### ISSUE TITLE
do STUN lookup periodically

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#34]
Copying bug from @apenwarr elsewhere:

> STUN should re-run sometimes, not just at startup time, in case local IP address or NAT changes.
>
> This matters on Linux especially because the local network might not be up at boot time.

We just had a bug report from a user whose ISP gives them a new IP pretty regularly and they had to manual restart the tailscale service for it to unbreak after those ISP changes.

/cc @danderson

**Comment by danderson** [comment]
From that old bug you copied, the second paragraph is N/A, we now reconfigure on address and route changes.

Still need to re-stun periodically to detect changes in the NAT setup.

**Comment by crawshaw** [comment]
Is there anything else we can do here but a timer?

If we are maintaining an active TCP session to DERP, could the DERP server inform us if our remote-addr changes? (Will it even change, or will the TCP connection reset? If so, that would be easy to detect.)

**Comment by bradfitz** [comment]
> could the DERP server inform us if our remote-addr changes?

Well, TCP won't survive an IP address change (for our initial DERP-TCP-HTTPS-"WebSockets-not-WebSockets").

But we could just make the client notice when the DERP (and/or tailcontrol) connection fails (either TCP RST, or heartbeat timeouts), then also STUN.

**Comment by happyalu** [comment]
I think I'm seeing a lot of "Handshake did not complete after 20 attempts, giving up" messages when the connection breaks. I'll run the latest tailscaled, monitor this for a few broken connections along with my IP addresses and what ports the tailscale admin page displays. Will report back soon.

**Comment by crawshaw** [comment]
I think taking our cue from DERP connection failures might actually cover all needs to STUN again, without a timer. \o/

(Though I think in the current DERP code, keepalives only flow in one direction, as discussed earlier, they need to be bi-directional for reliability.)

**Comment by danderson** [comment]
If we have DERP around, then yes, that should be enough. I can think of some byzantine setups in which TCP and UDP don't change together, but let's delay complexity until we find one of those in the wild.

**Comment by ernado** [comment]
Btw if you need anything in `gortc.io/stun` just let me know.

Also you can use [ICE](https://tools.ietf.org/html/rfc8445) for automatic peer-to-peer connectivity, but it is very complicated and will require to invest a lot of time to be done right.

**Comment by bradfitz** [comment]
> Also you can use ICE for automatic peer-to-peer connectivity, but it is very complicated and will require to invest a lot of time to be done right.

Oh, @danderson knows all about ICE. That's #3.

**Comment by happyalu** [comment]
Not sure how much this is helpful:

My IP address hadn't changed, but i had resumed from a suspend and noticed the tailscale nodes were not accessible.

Tailscale console showed this for my machine: 
```
100.115.179.60
123.201.8.59:18384
192.168.0.189:54244
```

The following log messages were seen a few times:
```
Received keepalive from 104.37.250.224:41641
```

as well as:
```
Handshake did not complete after 20 attempts, giving up
```

After restarting `tailscaled` and running `tailscale` again the console showed:

```
100.115.179.60
123.201.8.59:17654
192.168.0.189:40152
```

**Comment by apenwarr** [comment]
y'all are way too optimistic about TCP's ability to detect connection
failures. If your network configuration changes, any RSTs will
probably not even be allowed back to reach you through the NAT,
because NAT holes only open up when they see a SYN. What happens
instead is the TCP session just dies.

We see that with logtail's http connection when switching networks
(listed in a separate bug). It just gets stuck basically forever.  Any
TCP session without an explicit heartbeat cannot be guaranteed to ever
return any status at all.

Meanwhile, for this bug: even if a TCP connection *could* report
problems, the lack of that report would still not tell you whether
your UDP port's firewall mapping has changed. NATs do whatever they
want. You could end up remapped at any time. There could be multiple
layers of NATs, so you would get absolutely no notice from the kernel
or operating system when the router you're eventually NATting through
suddenly changes. If you aren't periodically re-STUNning, the only
indicator you have is whether any traffic is *currently* getting
through (which is an indicator that it *isn't* broken). If you don't
have any traffic getting through, you really have to periodically
re-STUN or find some reason (eg. a DERP notification) to STUN at a
particular time.

We are way too cautious about re-STUNning right now, considering that
we try wireguard handshakes to every node every couple of seconds.

**Comment by happyalu** [comment]
Ok, I think this maybe why I'm encountering the issue. I can reproduce this fairly reliably. This seems to be related to tailscale attempting the STUN, but getting no timely response.

I'm on OpenSUSE 15.1 using NetworkManager, and not wicked. Connected to wifi.

Tailscale running -> `ping node` running -> Stop wifi -> Connect wifi. 

I see the following logs from tailscaled: I'm including only part of the log here. Let me know if I can email the logfile privately if that might be helpful.

```
122.2M/140.5M LinkChange(isExpensive=false): rebinding socket
magicsock: link change, binding new port
magicsock: CreateEndpoint: key=...
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:56268->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:53053->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:33236->[::1]:53: read: connection refused
magicsock: link change, binding new port
122.8M/140.5M [Nq2N…lYCg] - Stopping...
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun3.l.google.com:19302: lookup ip addr: operation was canceled
stunner: no STUN response from stun3.l.google.com:19302
122.8M/140.5M [HCnl…FNBE] - Stopping...
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: no STUN response from stun.l.google.com:19302
magicsock: found local 192.168.0.189:38480 (localAddresses)
...
123.6M/140.5M vLONGVER-TODO peers: x x x x x x x x x x x x x
123.6M/140.5M control: client.newEndpoints(0, [192.168.0.189:38480])
123.6M/140.5M control: cancelMapSafely: synced=false
123.6M/140.5M control: cancelMapSafely: channel was full
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:34427->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:47924->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:41307->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:56333->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:52606->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:49179->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:47008->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:55064->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:47750->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:51681->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:41694->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:49008->[::1]:53: read: connection refused
stunner: stun3.l.google.com:19302: lookup ip addr: lookup stun3.l.google.com on [::1]:53: read udp [::1]:59242->[::1]:53: read: connection refused
stunner: stun.l.google.com:19302: lookup ip addr: lookup stun.l.google.com on [::1]:53: read udp [::1]:54304->[::1]:53: read: connection refused
111.2M/140.5M LinkChange(isExpensive=false): rebinding socket
magicsock: link change, binding new port
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: stun.l.google.com:19302: lookup ip addr: operation was canceled
stunner: no STUN response from stun.l.google.com:19302
```

And then, when it works eventually:
```
logtail: backoff: 6381 msec
STUN server stun3.l.google.com:19302 reports public endpoint 123.201.8.19:2607
stunner: slow STUN response from stun3.l.google.com:19302: 8 retries
magicsock: found local 123.201.8.19:2607 (stun)
STUN server stun.l.google.com:19302 reports public endpoint 123.201.8.19:2607
magicsock: found local 123.201.8.19:2607 (stun)
stunner: slow STUN response from stun.l.google.com:19302: 8 retries
magicsock: found local 192.168.0.189:38264 (localAddresses)
112.9M/140.5M vLONGVER-TODO peers: x x x x x x x x x x x x x
113.0M/140.5M control: client.newEndpoints(0, [123.201.8.19:2607 192.168.0.189:38264])
113.0M/140.5M control: cancelMapSafely: synced=false
```

And later proceeds to print the netmap diff and things start working.

**Comment by crawshaw** [comment]
@apenwarr derp has an explicit heartbeat (though only in one direction right now iirc, it will need one the other way too).

**Comment by happyalu** [comment]
I was affected by this earlier (v0.95*) but the latest release has solved this for me.

**Comment by bradfitz** [comment]
Closing this. This has been addressed over a dozen or so magicsock commits.
