### ISSUE TITLE
Ubuntu node is intermittently losing connectivity for sometime and restore itself.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3400]
### What is the issue?

From Customer :
From time to time, I am unable to SSH into some of our nodes. After waiting a while I suddenly get access, not knowing what happened. Completely left in the dark :-/
 
Log shows 

2021-11-24 06:17:28.578113758 +0100 +0100: failed to disable DoT: Unknown method 'SetLinkDNSOverTLS' or interface 'org.freedesktop.resolve1.Manager'.
2021-11-24 06:17:28.578664288 +0100 +0100: authReconfig: ra=false dns=true 0x01: <nil>
2021-11-24 06:17:29.353747813 +0100 +0100: dns: error: upstream nameservers not set
2021-11-24 06:17:29.35380567 +0100 +0100: dns: error: upstream nameservers not set

Linux version :"Ubuntu 18.04.5 LTS (Bionic Beaver);

systemd-resolve --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

### OS

Linux

### OS version

Ubuntu 18.04.5 LTS (Bionic Beaver)

### Tailscale version

1.18.1

### Bug report

BUG-feb2501e336313e482c73cbdbaa3b0d6b16ae5c583aa8b8662146f1bc7a7e3c3-20211124052510Z-1bfe709696c7a98f

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3wfip)

**Comment by DentonGentry** [comment]
The symptoms match an overly aggressive netmap suppression issue we fixed at the end of 2021. Nodes would be unable to connect in one direction, but if the other node tried to make a connection back to the first it would instantly work.

I'm going to close this based on the netmap fix likely having resolved this.
