### ISSUE TITLE
FR: Store and Update ACL Rules via Git Repository

### ISSUE THREAD

**Issue by strausmann** [tailscale/tailscale#3405]
### What are you trying to do?

I would like to Store the ACL Rules into to a Git Reposizory and not in the Web Editor there are currently it is.

What are the benefits?

- with git you can integrate a approval process for rule Updates.
- you can compare the current Rules with the git history.
- you can Go back to a rule Set thats works.
- you can See, who has changed the Rules and which Part of the Rules. 

### How should we solve this?

Add the Option to manage the ACL Rules not only via the Web Editor. Add the Option to setup a Git based repository. GitHub, GitLab or so on. 

### What is the impact of not solving this?

Nothing can replace this Feature.

**Comment by DentonGentry** [comment]
There is an API which can get, validate, and set the ACL JSON content: https://github.com/tailscale/tailscale/blob/main/api.md

We may not develop specific integrations like fetching from git directly, but sites have developed integrations with their git workflows using the API.

**Comment by DentonGentry** [comment]
At this point I do not expect to implement this feature request. [The API](https://github.com/tailscale/tailscale/blob/main/api.md) can be used to push ACL JSON, and can be hooked up to push from a git repository.
