### ISSUE TITLE
FR: Support to Split ACL Rules in different files

### ISSUE THREAD

**Issue by strausmann** [tailscale/tailscale#3406]
### What are you trying to do?

Based on my Request #3405 is very nice to Split the ACL Rules in different files. Both for the Web Editor and the Git based managed configuration.
In large Networks this can help to give a better overview of all Rules by Split the Groups, and the Access definitions to more files.
On git based managed ACL Rules you can use the file CODEOWNERS to manage the permission to change the ACL Rules. 

### How should we solve this?

Allow the Split of ACL Rules. Use the include methode

### What is the impact of not solving this?

Any admin can change the complete ACL Rules.

**Comment by DentonGentry** [comment]
There is an API which can get, validate, and set the ACL JSON content: https://github.com/tailscale/tailscale/blob/main/api.md

Sites have developed integrations with their git workflows using the API, I think that would be the way to get the behavior described here.

**Comment by DentonGentry** [comment]
At this point I do not expect to implement this feature request. [The API](https://github.com/tailscale/tailscale/blob/main/api.md) can be used to push ACL JSON, and can be hooked up to combine from multiple files as needed.

**Comment by mattklein123** [comment]
@DentonGentry I was hoping this old issue can be reconsidered. Let me know if I should open a new one.

Having multiple files/merging is very useful when the different ACLs are produced by different systems. For example, terraform might be producing some and a different automated system might produce a different set. With this support it forces all automation to be done by a single system which makes it much more difficult to support certain scenarios.

Thank you.
