### ISSUE TITLE
FR: Permanent download link for static binaries

### ISSUE THREAD

**Issue by kevinfengcu** [tailscale/tailscale#3414]
### What are you trying to do?

Static binaries can be used for Tailscale deployment in the userspace networking mode, but unlike release delivered through package repository, they have to be downloaded through the [website](https://pkgs.tailscale.com/stable/#static) and the link changes w.r.t. the version number. Automation of this process would be nice.

### How should we solve this?

Serve latest static binaries through a permanent link, something like `https://pkgs.tailscale.com/stable/<ARCH>/latest.tgz`

### What is the impact of not solving this?

Manually downloading the package.

**Comment by DentonGentry** [comment]
Does this help? https://pkgs.tailscale.com/stable/?mode=json

**Comment by kevinfengcu** [comment]
> Does this help? https://pkgs.tailscale.com/stable/?mode=json

This also works. Thank you!

**Comment by bradfitz** [comment]
FYI, we now support the magic version number `latest` in any of our URLs that will redirect to the latest version, e.g.:

```
$ curl -I https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-latest.exe
HTTP/2 302 
content-type: text/html; charset=utf-8
location: /unstable/tailscale-ipn-setup-1.21.26.exe
date: Tue, 25 Jan 2022 22:36:57 GMT

```
