### ISSUE TITLE
version release routings

### ISSUE THREAD

**Issue by frankli0324** [tailscale/tailscale#3415]
### What are you trying to do?

I was trying to upgrade to 1.18.1 on my mac with homebrew, but homebrew/core fails to keep up with the latest version.
I'm proposing to list the routing works to be done when issuing a new release.

### How should we solve this?

Make a list of what should be done on version release, and who's responsible for doing that. Make use of the GitHub actions not only to build and test, but also to synchronize repos like ubuntu ppa and homebrew.

### What is the impact of not solving this?

Well, users like me not getting the latest version. Yes we can download from the release/CI or simply clone&build, but not from a package manager.

### Anything else?

related: https://github.com/Homebrew/homebrew-core/pull/89953

**Comment by bradfitz** [comment]
The Tailscale 1.18.1 release was unique in that it only contained Linux-specific fixes, so we didn't go through our usual release dance. We didn't want to e.g. build for all platforms and make Windows/macOS users go through the upgrade process.

There's no real reason for Homebrew to update to 1.18.1, but you can. It was a "real" release, kinda.

**Comment by frankli0324** [comment]
Homebrew works for Linux too. It's "[Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux)".

**Comment by DentonGentry** [comment]
I see that homebrew has updated to 1.18.1.

I realize this feature request asks for more, like moving the autobuilder to GitHub Actions and changing how checklists are handled, but I'd consider those sorts of process changes as outside of what is reasonable in a feature request. Closing as resolved.
