### ISSUE TITLE
FR: Readonly API key (or API key scopes)

### ISSUE THREAD

**Issue by joonas-fi** [tailscale/tailscale#3418]
### What are you trying to do?

I am doing service discovery from Tailscale network: I want device IPs and hostnames.

Currently Tailscale's API token gives ultimate root access to your network, even allows configuring subnet routers to your devices so it would allow an attacker gaining access to the API key to even expose any internal networks the Tailscale devices are connected to.

I just want to do device discovery with an readonly auth token that exposes a subset of device data. This way if the token gets exposed it is not a big deal.

### How should we solve this?

Support restricting the API token to non-dangerous levels

### What is the impact of not solving this?

Security risk

I worked around by creating https://github.com/function61/tailscale-discovery

### Anything else?

I believe this project would also benefit from this: https://github.com/cfunkhouser/tailscalesd

**Comment by DentonGentry** [comment]
Work on adding a readonly attribute and scopes to API keys has started.

**Comment by willnorris** [comment]
OAuth is now live (in beta) for all tailnets, which provides fine-grained (including read-only) scopes.

https://tailscale.com/blog/oauth/
