### ISSUE TITLE
Ask Microsoft to add IPv6 policy routing to WSL2 kernel

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3420]
At startup, Tailscale probes IPv6 policy routing and finds that it fails on WSL2, so we turn off IPv6 overall.

We could do something different, but perhaps we can just ask Microsoft to change their WSL2 kernel config.

/cc @apenwarr @danderson @crawshaw

**Comment by bradfitz** [comment]
Looks like it's CONFIG_IP_MULTIPLE_TABLES + CONFIG_IPV6_MULTIPLE_TABLES.

Anything else, @danderson?

**Comment by bradfitz** [comment]
https://github.com/microsoft/WSL/issues/6850 is already open to track adding IPV6_MULTIPLE_TABLES

**Comment by DentonGentry** [comment]
https://github.com/microsoft/WSL/issues/6850 is still open.
I don't think we have anything more to do here.
