### ISSUE TITLE
FR: Start Tailscale Android as an HTTP proxy with root access 

### ISSUE THREAD

**Issue by qwerzl** [tailscale/tailscale#3424]
### What are you trying to do?

Is it possible for the Android app to run as an HTTP proxy with root like what Adguard does? This will be incredibly helpful to use another VPN at the same time.

**Comment by DentonGentry** [comment]
Most of the functions of the main Android app rely on features of the Android VpnService https://developer.android.com/reference/kotlin/android/net/VpnService
It is doubtful the main Android app could function in the way described.

The Android app source code is available at https://github.com/tailscale/tailscale-android, and it would be possible to leverage that code to develop a `userspace-networking` version which functions as a proxy.

**Comment by DentonGentry** [comment]
I am declining to implement this.
