### ISSUE TITLE
FR: Allow configuration of auth key expiration to shorter intervals

### ISSUE THREAD

**Issue by artis3n** [tailscale/tailscale#3427]
### What are you trying to do?

I'd like to create one-off, reusable, and ephemeral auth keys that expire earlier than the current 90-day limit. For example, when creating infrastructure in an IaC pipeline I may want to use a reusable auth key but I don't want the key to persist beyond the 1 day of use in that pipeline. I currently have to remember to go in and revoke the API key once I'm done, or let it sit for 90 days.

### How should we solve this?

When creating an Auth Key (my use case is via the UI console but I'd imagine via API would be useful for other users), I'd like to be able to configure an arbitrary revoke date. I don't want to persist beyond the 90-day limit, but I'd like to configure a week, or a few days, one day, etc. as my need arises.

### What is the impact of not solving this?

Auth keys persist in my account longer than I'd like them to, or I need to remember to manually go in to the UI and revoke a key once I'm done with it. Doing this via Tailscale's API is currently [not supported](https://github.com/tailscale/tailscale/issues/3243).

**Comment by DentonGentry** [comment]
Since this bug was filed, a DELETE method for authkeys has been added to the API: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-keys-key-delete

**Comment by artis3n** [comment]
Yeah, I think this ticket is covered by existing functionality at this point. Thanks!

**Comment by DentonGentry** [comment]
This was ultimately implemented, tracked in https://github.com/tailscale/tailscale/issues/4570
