### ISSUE TITLE
Can't reach port 4449 on browser

### ISSUE THREAD

**Issue by Stephen988** [tailscale/tailscale#3429]
### What is the issue?

Hello,
I need to reach a local service hosted in my device, it work perfectly with local_ip:4449 but with tailscal_ip:4449 I have error blank page.
I have traied with remote ssh terminal and FTP and tailscale ip work, so what is the problem with this specific port? there is a way to release it?
Thanks

### Steps to reproduce

- Installing Tailscale
- activate the service
- try to reach tailscale_ip:4449
- error blank page

### Are there any recent changes that introduced the issue?

nothing

### OS

Linux

### OS version

Debian 10 arm

### Tailscale version

1.18.1

### Bug report

BUG-dbb6b85dffbcf49725c14d7f2cfe2624948de20c94d90ab220768979293d0945-20211128222254Z-5a38c46e81939937

**Comment by DentonGentry** [comment]
Whatever that process is on port 4449 has called listen() on `localhost` specifically. Other interfaces are not allowed to reach the port.

In many cases there is a configuration file of what to bind to. That process could be configured to bind to:
- 100.x.y.z instead of localhost
- 0.0.0.0, which means "any interface." Be aware that this would make it reachable from the Ethernet/Wi-Fi/etc as well, which is probably fine if it is within an office or home but not fine if the machine roams out onto public networks. The OS firewall could be used to block port 4449 from Ethernet/Wi-Fi and only allow localhost and 100.x.y.z to reach it.

**Comment by Stephen988** [comment]
> Whatever that process is on port 4449 has called listen() on `localhost` specifically. Other interfaces are not allowed to reach the port.
> 
> In many cases there is a configuration file of what to listen on. That process could be configured to listen on:
> 
> * 100.x.y.z instead of localhost
> * 0.0.0.0, which means "any interface." Be aware that this would make it reachable from the Ethernet/Wi-Fi/etc as well, which is probably fine if it is within an office or home but not fine if the machine roams out onto public networks. The OS firewall could be used to block port 4449 from Ethernet/Wi-Fi and only allow localhost and 100.x.y.z to reach it.

Hello,
I have changed from /etc/hosts 127.0.0.1 for localhost and hostane to 0.0.0.0 but still not work

**Comment by DentonGentry** [comment]
> I have changed on /etc/hosts 127.0.0.1 for localhost and hostane to 0.0.0.0 but still not work

Please change /etc/hosts back to 127.0.0.1, or it is likely to lead to weird behavior. Unfortunately that likely didn't change whether the process on port 4449 listened on localhost or not, as the default is often compiled in.

What is the process listening on port 4449? It might also take a command line argument, like `--listen=0.0.0.0`

**Comment by Stephen988** [comment]
> port

Hi Denton, I have run the following command:
`sudo netstat -peanut | grep ":4449"
tcp        0      0 192.168.43.133:4449     0.0.0.0:*               LISTEN      999        18097      679/myst          tcp        0      0 127.0.0.1:4449          0.0.0.0:*               LISTEN      999        16384      679/myst`

So how to open this page on browser with tailscale ip? thanks.

**Comment by DentonGentry** [comment]
That confirms that the myst process is listening on 192.168.43.133:4449 and 127.0.0.1:4449 specifically. It is not listening on 100.x.y.z:4449.

Somewhere in the myst process, either in a configuration file or in code, it is deciding to only listen on the Ethernet or Wi-Fi interface (whatever 192.168.43.133 is) and on localhost. That needs to be changed to either add 100.x.y.z as a listen address, or listen on 0.0.0.0 which means all interfaces.

**Comment by Stephen988** [comment]
> That confirms that the myst process is listening on 192.168.43.133:4449 and 127.0.0.1:4449 specifically. It is not listening on 100.x.y.z:4449.
> 
> Somewhere in the myst process, either in a configuration file or in code, it is deciding to only listen on the Ethernet or Wi-Fi interface (whatever 192.168.43.133 is) and on localhost. That needs to be changed to either add 100.x.y.z as a listen address, or listen on 0.0.0.0 which means all interfaces.

Thanks a lot Denton for clarification, I try to submit this request to the dev team of the myst service, probably I know how to do.

Thanks again,
Stephen

**Comment by bradfitz** [comment]
People who like this bug also like https://github.com/tailscale/tailscale/issues/1121 ("export localhost").
