### ISSUE TITLE
Extremely high latency when using custom DERP

### ISSUE THREAD

**Issue by hronro** [tailscale/tailscale#3430]
### What is the issue?

I have two nodes, one is my MacBook running Tailscale 1.18.0, another is my desktop (Arch Linux) running Tailscale 1.18.1.

I also have a custom DERP server,  which is build from commit 25525b77.

When I check the latencies of nodes to the DERP server, both of them are about 5ms (check my screenshots below, and you can identify which is macbook/linux by checking the shell prompt):
![CleanShot 2021-11-29 at 13 17 40](https://user-images.githubusercontent.com/15059605/143813773-70014906-195d-4871-a2f8-5526bc84db1e.png)
![CleanShot 2021-11-29 at 13 17 23](https://user-images.githubusercontent.com/15059605/143813795-18b87087-f77a-4c58-b81d-dd304ba8bbea.png)

However, when I try to `ping` the arch linux node (`104.21.89.78`) from MacBook, the latency is extremely high. (using `tailscale ping` works fine though):
![CleanShot 2021-11-29 at 13 24 58](https://user-images.githubusercontent.com/15059605/143814132-9c7174ed-c8fa-4131-94a7-60e5d1770e23.png)
![CleanShot 2021-11-29 at 13 16 55](https://user-images.githubusercontent.com/15059605/143814151-c611e7fb-18c2-4528-ade2-456680516805.png)

### OS

macOS

### OS version

macOS 10.13 and Arch Linux

### Tailscale version

1.18.0 on macOS and 1.18.1 on Arch Linux

### Bug report

BUG-f3189c3a2fd120ee3896ddbf32e020d62bf2b1898689305dc95ffee21a7a7bd4-20211129052051Z-baaa8557e61aca95

## Edit:

Many said it's caused by GFW, but I think it's not.

As you can see, when I run `tailsacle status`, it shows the connection between my MacBook and my Linux machine are using my custom DERP server. When I run `tailscale ping <linux-machine-ip>`, it works perfectly and the latency is also good. But when I run normal `ping <linux-machine-ip>` (instead of `tailscale ping`), it seems like Tailscale is using another DERP server (not the one shown  in the `tailscale status`) to handle this connection, and the latency is very high.

**Comment by bradfitz** [comment]
The IP address shown in the screenshot, 171.217.93.31, is owned by China Telecom: https://whatismyipaddress.com/ip/171.217.93.31

I'm going to assume that any latency you're experiencing here is related to the Great Firewall. We get a decent number of reports that Tailscale doesn't work as well in China as it does elsewhere, or things are blocked, or things work for a bit, and then slow to a crawl, etc.

We are not in China and don't have a way to debug this further, so I don't think we can help.

If you learn anything, let us know, though!

**Comment by hronro** [comment]
Hi @bradfitz, thanks for your reply, but I don't think this is caused by GFW though.

I far as I know, GFW only exist when the one machine in China want to connect another machine outside China. All my nodes and my custom DERP are in China, so then they try to communicate with each other, there shouldn't be GFW at all.

**Comment by DentonGentry** [comment]
The MacBook has chosen Tokyo as its home DERP. I don't immediately know why, but that results in transiting the GFW.

On MacOS you can run the application bundle from the CLI to run things like netcheck: `/Applications/Tailscale.app/Contents/MacOS/Tailscale netcheck`

Something in there may be illuminating, to get it to use the custom DERP as its home.

**Comment by talway** [comment]
I have the same problem he has; Why did I propose to force the relay

**Comment by hronro** [comment]
@DentonGentry 
I already run that, you can check my screenshots above.

Another thing make me think this is not caused by GFW, is that `tailscale ping` works perfectly (also see my screenshots above), using the proper DERP server and the latency seems good. However normal `ping` somehow seems link is not using the same DERP server.

**Comment by talway** [comment]
@hronro  You wait for a while, will change over, you observe, will use your Chengdu relay; Mine is just like this. It started from Japan and then changed back to China. It needs some time to negotiate

**Comment by talway** [comment]
It's the same question, why is relay mandatory
https://github.com/tailscale/tailscale/issues/1303

**Comment by hronro** [comment]
@talway 

For me, the connection became `direct` instead of `relay` after waiting for a time. The `direct` connection quality is not good, but that's not the same problem though (see #2270).

**Comment by lberezy** [comment]
I'd like to +1 this and say that I'm experiencing the same symptoms for nodes in Australia.

Node A is in Azure SYD, the other is on a restricted connection only allowing *:443/TCP.

Node A us using relay "ord" (Chicaco, ~200 ms RTT away), and Node B has selected "blr" (Bangalore, ~150 ms RTT away) to communicate.

The network performance between the two nodes is consequently terrible. I can't work out why they don't pick "syd", especially when `tailscale netcheck` lists this relay region as a very clear winner in terms of raw latency. Is the DERP selection policy more complicated than this (load/capacity at each DERP)?

**Comment by hronro** [comment]
UPDATE:

I upgrade tailscale to v1.20.2 and derper server to f5ec9162, and now it seems all works fine now.

**Comment by DentonGentry** [comment]
Seems resolved in 1.20.

**Comment by hronro** [comment]
@steve1977 Sure. You can contact me in Telegram. My Telegram id is also @hronro

**Comment by steve1977** [comment]
Thanks @hronro. Any other way? Telegram is one of the few things I am not on. Maybe something as easy as email? ;-)
