### ISSUE TITLE
Windows: Updated wsl.conf is nowhere to be found

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#3437]
### What is the issue?

On my personal/test tailnet, I set up MagicDNS. My WSL2 install contains a `resolv.pre-tailscale-backup.conf`, but I do not see a `wsl.conf` generated, my WSL2 was never shut down, and my `resolv.conf` is the WSL2-generated one.

Error logs show an entry for a failed `cat` of `/etc/wsl.conf`, which we expect since one doesn't exist. No errors for actually writing out the new file though. `SetDNS` claims to have succeeded.

To me, all this evidence points to `wsl.conf` failing to be written, but we didn't realize that for some reason and proceeded as if we could now backup and overwrite `/etc/resolv.conf`.

### Steps to reproduce

See above.

### OS

Linux, Windows

### OS version

Windows 10 10.0.19043.1348 (21H1), Ubuntu focal WSL2

### Tailscale version

1.18.0

**Comment by jdgiddings** [comment]
I've experienced this in the past. Reinstalling Ubuntu from the Microsoft Store fixed it for me
