### ISSUE TITLE
cmd/tailscale: add status --exit-nodes ?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3446]
I wanted to use an exit node from Linux, but forgot which we were running on our tailnet.

On the Windows/Mac GUI the options are presented in the UI.

On Linux you kinda just need to know.

It'd be nice to make `tailscale status` either take a flag to filter the nodes, matching only exit nodes, or print them out specially so you can grep.

Even `tailscale status --json` doesn't have any fields that are useful for finding them.

**Comment by crawshaw** [comment]
the `tailscale status` format is not fixed, right? so appending `(exit node)` to exit nodes would make it easily greppable.
