### ISSUE TITLE
Google Stadia controller not wirelessly pairing with tablet when connected to tailscale

### ISSUE THREAD

**Issue by NimdaBE** [tailscale/tailscale#3460]
Hello,

I have a Samsung android tablet (Galaxy Tab 5se) with tailscale connected. To connect the Google Stadia controller wirelessly you have to open the Stadia app. This will show a linking code (a combination of buttons to press on the controller). When doing this the app then indicates that the controller could not be connected.

The controller has to be on the same wireless network for Stadia to work and i think the initial pairing process uses bluetooth. The Stadia app itselfs works without any problems when connected to tailscale. With the controller connected wired via usb to the tablet all is working fine as well... When i disconnect the tailscale connection i can connect the controller wirelessly and game like normal.

In my tailscale network i have no exit nodes defined nor specific dns settings configured... I don't exactly know how Stadia works exactly but somehow with tailscale connected and the controller connected to wifi it cannot properly see each other on the same wifi network.

Maybe a solution might be to have an option in the tailscale app to exclude some apps from using the tailscale network? Even though i'm not exactly sure if the Stadia app is even trying to establish a connection over the tailscale network, maybe with some udp broadcast or other connection-trickery they have up their sleeves...

Many thanks for the great software, and i hope i have explained my issue clearly.

Best regards

**Comment by sailorfrag** [comment]
I also have a Samsung Android tablet and Stadia with controllers so I can try to repro.

Unless something significantly changed in the last year (unlikely), my understanding is that the initial Bluetooth-based process is only used to configure the wifi network settings. Once the controller is on wifi, it directly interacts with the cloud server running the game, rather than your tablet. If you have headphones plugged into the controller then game audio may go through the tablet first for decompression.

The linking codes are short and rely on the internet address of both the controller and the display device (computer, chromecast, tablet, etc.) being similar enough that they get mapped into the same discovery instance. I think that part is the most likely to be what broke here, but I'd only expect that to be an issue when using an exit node.

**Comment by NimdaBE** [comment]
I have experimented a bit further with settings in tailscale but things like enable/disable magicdns or changing the global dns server don't change anything... I also can't find any network related settings in the Stadia app so maybe it's looking at the local android system, noticing that there is a vpn active and trying to force the connection over the vpn but not finding any route to the google infrastructure...?

**Comment by sailorfrag** [comment]
I just tried this on my Galaxy Tab S6 lite (not officially supported by Stadia) and a Pixel 5 (officially supported by Stadia) and see similar results.

In both cases, the controller seems to acknowledge a valid pairing code (the controller will immediately vibrate and flash to reject the code if it's incorrect) but then after several seconds the controller goes back to wanting a pairing code. The phone/tablet does not show that the controller has been registered when this happens.

Oh, I seem to recall that for navigating the menus, the controller sends button presses directly to the display device; it only sends directly to the cloud for games (this might have changed over time, not sure). So perhaps it is related to Android VPN framework somehow making direct local connections not work right? It will require more investigation.

I can't guarantee how quickly I'll be able to look at this further, but I'll try to characterize the problem better with some packet captures soon.

**Comment by sailorfrag** [comment]
As a workaround, I'm pretty sure the Stadia controller can connect via USB to phones and tablets. I don't anticipate having much time to spend on this for now.

**Comment by NimdaBE** [comment]
> 

Yes, i mentioned this in my original post as well: wired usb connection from controller to tablet works fine, both with tailscale enabled and disabled.

My main concern is that, if this issue occurs with stadia, then maybe other apps might have a similar issue as well (for example apps from different devices that link to each other directly).

Maybe this is a super difficult issue to solve and maybe not worth the time (because usb connection works) but i thought it was worth mentioning the issue

**Comment by sailorfrag** [comment]
Stadia does some particularly interesting things. At my previous employer, I made some Stadia Controller improvements as a side project. As a result, I was present for some meetings discussing this aspect of the controller, but I was not directly involved in implementing that part.

I strongly suspect this is a problem that only affects Stadia but I do think it's worth investigating at some point to see if it may affect some non-Stadia use cases too.

**Comment by DentonGentry** [comment]
Stadia is believed to be resolved in the 1.29.0 unstable build available on the Open Testing track in the Play Store.
Join via web: https://play.google.com/apps/testing/com.tailscale.ipn
Join via Play Store app: https://play.google.com/store/apps/details?id=com.tailscale.ipn
