### ISSUE TITLE
UI ACL's preview "Error: Cannot read properties of null (reading 'map')"

### ISSUE THREAD

**Issue by Pilskalns** [tailscale/tailscale#3463]
### What is the issue?

If I add too minimal / incomplete ACL rule (sample below), then the preview tab breaks.

![image](https://user-images.githubusercontent.com/6931156/144224601-2237543e-6760-4e96-ad0d-66345d9a065c.png)

While this rule gives you nothing, the UI shouldn't break because of it.

### Steps to reproduce

1. Add ACL rule
```
{
      "action": "accept",
      "users": ["group:eng"]
}
```
2. Save - OK
3. Open Preview rules tab
4. Select user that is in the `group:eng`
5. Profit

### OS

Windows

**Comment by catzkorn** [comment]
Thanks for flagging this @Pilskalns, I have been able to reproduce this error.
