### ISSUE TITLE
MacOS illegal hardware instruction

### ISSUE THREAD

**Issue by taylorsmithgg** [tailscale/tailscale#3467]
### What is the issue?

Can't log in, as daemon isn't running:
```
➜  ~ /Applications/Tailscale.app/Contents/MacOS/Tailscale status
2021/12/01 13:46:58 failed to connect to local Tailscale service; is Tailscale running?
```

```
➜  ~ /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension
[1]    1046 illegal hardware instruction
```

### Steps to reproduce

Running v1.18.0

Mac specs:
![image](https://user-images.githubusercontent.com/6597925/144319358-845f3cad-0fca-490e-91f1-a55a4223cad5.png)

### Are there any recent changes that introduced the issue?

No

### OS

macOS

### Tailscale version

11.6

### Bug report

➜  ~ /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport 2021/12/01 13:48:20 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial tcp [::1]:56043: connect: connection refused

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3xump)

**Comment by josharian** [comment]
Well that's exciting. What does `file /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension` say?

**Comment by taylorsmithgg** [comment]
IPNExtension is the one giving me the illegal hardware instruction message. 
The client just behaves as if the daemon never starts. 
We have tried rebooting multiple times and reinstalling with no luck.

**Comment by josharian** [comment]
Right. If you run the command

`file /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension`

what does it output?

**Comment by DentonGentry** [comment]
On an older x86 MacBook running macOS 10.15.3, where Tailscale 1.18 is logged in and working, running `/Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension` exits with `Illegal instruction: 4`

I don't know that the IPNextension can just be run from the CLI like that.

**Comment by taylorsmithgg** [comment]
```
➜  ~ file /Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension
/Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Tailscale.app/Contents/PlugIns/IPNExtension.appex/Contents/MacOS/IPNExtension (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by josharian** [comment]
Thanks. That all looks fine.

@DentonGentry has a good observation. How are you running these executables? For the regular macOS build (which you have), it is intended to be launched as a regular GUI, which then installs a networking extension managed by the OS.

You can run things purely from the command line on macOS using a different build, but it doesn't have the full bells and whistles of the GUI version. (IIRC, it is missing some DNS support.)

**Comment by taylorsmithgg** [comment]
I only started attempting to run them from terminal after GUI and reinstall.
Just updated to Big Sur 11.6.1 to verify there's no issues there, but the issue persists.

**Comment by josharian** [comment]
Hmm. OK, let's try this: Run them as GUI, and open Console.app. Filter to "IPN" or "IPNExtension" and see whether there are any useful looking log lines there. If there's anything sensitive, feel free to email support instead. (And if not, let's keep the conversation here.)

**Comment by taylorsmithgg** [comment]
Cannot launch the IPNExtension to get the logs unfortunately.

**Comment by josharian** [comment]
If you open Tailscale.app and log in, that'll take care of launching the IPNExtension.

**Comment by taylorsmithgg** [comment]
Cannot log in, that's what lead to this while goose chase.

**Comment by josharian** [comment]
So it at least tried to launch the extension. There ought to be something in the console, then, under either IPN or Tailscale. Or maybe look at the unfiltered console output while launching Tailscale.app.

**Comment by taylorsmithgg** [comment]
IPN can't launch either, otherwise I would use it to get logs.
To be clear, IPN is the one throwing the illegal instructions error.

**Comment by bradfitz** [comment]
@taylorsmithgg, Josh is saying you should:

* reboot your machine (can't hurt at this point; macOS gets confused and stuck often with Extensions)
* Start `Console.app`
* Search for `Tailscale` in `Console`
* Press `Start` in `Console`, to start recording/streaming logs
* Stare the Tailscale GUI app, even if it doesn't work. The point is to get logs & details.
* See what it says in `Console` (crash output, errors, etc)

**Comment by taylorsmithgg** [comment]
I've rebooted several times, no change.
Console.app:
```
default	13:25:59.224771-0800	Tailscale	Requesting container lookup; class = 2, identifier = <private>, temp = 0, create = 0, euid = 501, uid = 501, personaid = -1, type = NOPERSONA, name = <unknown>
default	13:25:59.225492-0800	Tailscale	container_create_or_lookup_for_platform: success
default	13:25:59.239533-0800	Tailscale	CHECKIN: pid=12810
default	13:25:59.248513-0800	Tailscale	CHECKEDIN: pid=12810 asn=0x0-0x81081 foreground=0
default	13:25:59.262767-0800	Tailscale	FRONTLOGGING: version 1
default	13:25:59.262820-0800	Tailscale	Registered, pid=12810 ASN=0x0,0x81081
default	13:25:59.265726-0800	Tailscale	BringForward: pid=12810 asn=0x0-0x81081 bringForward=0 foreground=0 uiElement=1 launchedByLS=1 modifiersCount=1 allDisabled=0
default	13:25:59.266051-0800	Tailscale	BringFrontModifier: pid=12810 asn=0x0-0x81081 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	13:25:59.267040-0800	Tailscale	Current system appearance, (HLTB: 2), (SLS: 1)
default	13:25:59.267972-0800	Tailscale	Received configuration update from daemon (initial)
default	13:25:59.269269-0800	Tailscale	No persisted cache on this platform.
default	13:25:59.270128-0800	Tailscale	Failed to copy the SysCfgDict MG key with error: 0
default	13:25:59.272295-0800	Tailscale	Post-registration system appearance: (HLTB: 2)
default	13:25:59.295942-0800	Tailscale	Registering for test daemon availability notify post.
default	13:25:59.296139-0800	Tailscale	notify_get_state check indicated test daemon not ready.
default	13:25:59.296252-0800	Tailscale	notify_get_state check indicated test daemon not ready.
default	13:25:59.297055-0800	Tailscale	Recieved DFR status change 0. status = 0x5
default	13:25:59.297684-0800	Tailscale	Recieved DFR status change 1. status = 0x5
default	13:25:59.298888-0800	Tailscale	SignalReady: pid=12810 asn=0x0-0x81081
default	13:25:59.299566-0800	Tailscale	SIGNAL: pid=12810 asn=0x0x-0x528513
default	13:25:59.309540-0800	Tailscale	Reacting to DFR status change 0. status = 0x5
default	13:25:59.309653-0800	Tailscale	Reacting to DFR status change 1. status = 0x5
default	13:25:59.316148-0800	Tailscale	Requesting app group container lookup; identifier = <private>, euid = 501, uid = 501, platform = 1, personaid = -1, type = NOPERSONA, name = <unknown>
default	13:25:59.316752-0800	Tailscale	container_create_or_lookup_app_group_path_by_app_group_identifier: success
default	13:25:59.317078-0800	Tailscale	NOGO-LOG: app introduction skipped
default	13:25:59.317101-0800	Tailscale	NOGO-LOG: registerExtension skipping unknown bundleID, assuming AppEx not SysEx
default	13:25:59.321609-0800	Tailscale	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x6000015c8980
 (
    "<NSDarkAquaAppearance: 0x6000015c8900>",
    "<NSSystemAppearance: 0x6000015c8580>"
)>
default	13:25:59.369363-0800	Tailscale	NOGO-LOG: BackendClient.create
default	13:25:59.373096-0800	Tailscale	Sending load command to nehelper
default	13:25:59.373161-0800	Tailscale	Clearing EEFEA33F-300D-4F6E-9F15-DBD8F106E7AA from the loaded configurations
default	13:25:59.374274-0800	Tailscale	Adding EEFEA33F-300D-4F6E-9F15-DBD8F106E7AA to the loaded configurations
default	13:26:09.313572-0800	Tailscale	LSExceptions shared instance invalidated for timeout.
default	13:26:44.802238-0800	Tailscale	NOGO-LOG: BackendClient.create
```

**Comment by taylorsmithgg** [comment]
This one was being caused by an interaction w/a third-party application (Crowdstrike Falcon) locking some security/networking permissions. Unfortunately had to wait ~1 week to get support on a call and needed a full reinstall to reinitialize permissions sets. Check with your IT department and make sure their security software isn't interfering w/tailscale!

**Comment by nazgul** [comment]
I've just hit this error with an old machine that won't run anything newer than Catalina. It's working fine from the menubar, but I need to add an internal route from the command line, and that gets me this.

```sh
% sudo  /Applications/Tailscale.app/Contents/MacOS/Tailscale up --advertise-routes=10.0.201.0/24
zsh: illegal hardware instruction  sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale up 
```

Any advice on how to debug this? Build my own from source?

**Comment by DentonGentry** [comment]
@nazgul What Tailscale app version is that? I doubt the issue you're running into is the same as this, apparently this one is related to an interaction with Crowdstrike.

Could you:
- file a new issue about the illegal instruction
- if the UI running in its normal mode works to get a bugreport (hold Option while clicking on the menubar, then select Debug > Bugreport) please include that
