### ISSUE TITLE
Document how 'tailscale up' preserves previously provided auth credentials

### ISSUE THREAD

**Issue by cespare** [tailscale/tailscale#3482]
### What is the issue?

As part of scripting a tailscale relay install, I wanted to first manually configure a one-time key using

    tailscale up --authkey xyz

and then later have my tools run

    tailscale up --advertise-routes 172.x.y.z/24

or whatever other configuration settings are appropriate.

The output of `tailscale up -h` says:

```
USAGE
  up [flags]

"tailscale up" connects this machine to your Tailscale network,
triggering authentication if necessary.

With no flags, "tailscale up" brings the network online without
changing any settings. (That is, it's the opposite of "tailscale
down").

If flags are specified, the flags must be the complete set of desired
settings. An error is returned if any setting would be changed as a
result of an unspecified flag's default value, unless the --reset
flag is also used.

FLAGS
...
  --authkey string
        node authorization key; if it begins with "file:", then it's a path to a file containing the authkey
...
```

This (particularly the bit about "the flags must be the complete set of desired settings") seems to suggest that my plan wouldn't work: I wouldn't be providing `--authkey` after the initial `tailscale up`. And in fact, the documented behavior seems somewhat incompatible with one-time keys at all, since you'll only be providing them once.

Happily, the actual behavior is exactly what I'd want: once tailscale is authorized, it just remembers the authorization if you reconfigure it using other flags. So my plan works fine.

So I just think the help output could be clearer that `--authkey` is exempted from the rule about "the complete set of the desired settings".

(I also feel like a dedicated `tailscale login` command would be clearer. The way that tailscale is configured by passing flags to `tailscale up` which are sticky is clever, but definitely surprised me at first, and having a subset of flags that work differently adds even more opportunity for confusion.)

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.18.1

**Comment by bradfitz** [comment]
> The way that tailscale is configured by passing flags to tailscale up which are sticky is clever, but definitely surprised me at first, and having a subset of flags that work differently adds even more opportunity for confusion

FWIW, it used to be much worse and more confusing. 😬 

The current design is a compromise between not breaking old users & not surprising anybody, but it's probably not what we would've arrived at today if we were starting over.

But, yes, we should document which flags are "prefless" as we call them in the code:

```go
// preflessFlag reports whether flagName is a flag that doesn't
// correspond to an ipn.Pref.
func preflessFlag(flagName string) bool {
        switch flagName {
        case "authkey", "force-reauth", "reset", "qr":
                return true
        }
        return false
}
```

**Comment by cespare** [comment]
Thanks!
