### ISSUE TITLE
Create, deploy new control key type for protocol v2

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3487]
Filing as a reminder to myself: for the new control protocol, we can reuse the client's machine key as the client key in the Noise session, but to avoid some cryptographic smells, we should _not_ reuse a control key that was previously used for naclbox traffic, even though the keys are "mathematically compatible".

To do:
 - New types/key type to represent this new control key, such that the old and new keys can't be mixed up
 - Make the new control protocol APIs require that key type in constructors
 - Generate, deploy and serve new keys for all control instances, such that clients can obtain both the old naclbox key and the new noise key as needed.

**Comment by danderson** [comment]
Related to #3488 .

**Comment by danderson** [comment]
https://github.com/tailscale/tailscale/pull/2261 was the initial chunk of code for this, with more to come.

**Comment by bradfitz** [comment]
This was done a number of years ago.
