### ISSUE TITLE
Implement 2021 Control Protocol

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3488]
We have a design for a new control protocol that uses Noise and other nice things. This is the tracking bug to wire it up and transition the client over to it incrementally.

**Comment by danderson** [comment]
https://github.com/tailscale/tailscale/pull/2261 was the initial chunk of code for this, with more to follow.

**Comment by ericlagergren** [comment]
How does this relate to https://tailscale.com/blog/tailscale-key-management/

Is there a white paper or design document?

**Comment by danderson** [comment]
It's a revised version of what's described in that post. Uses a different base layer transport, and lays the groundwork for some nice security features (but that aren't going to materialize immediately, this bug is about getting the basics online). The design's not public yet, but will be once this is something the clients actually use.

**Comment by DentonGentry** [comment]
The ts2021 control protocol design shipped with client version 1.24.0 and is in use by a majority of the device fleet.

I'm going to mark the issue as fixed. We've mostly been using it as a reference for PRs relating to the feature, and we can continue to do so for further work even after it is closed.

**Comment by ericlagergren** [comment]
> The design's not public yet, but will be once this is something the clients actually use.

Since it has shipped does this mean a white paper or design document is available? 😃

**Comment by frankli0324** [comment]
I also landed here looking for some material on the new control protocol.
