### ISSUE TITLE
redo fails

### ISSUE THREAD

**Issue by sylr** [tailscale/tailscale#349]
I don't know if I'm doing this correctly but `redo` in `version/` gives me an error.

```
$ redo
redo  all
redo    (ver.go)
redo    long.txt
fatal: not a git repository (or any of the parent directories): .git
redo    ver.go
redo      short.txt
redo    version.xcconfig
redo    version.h
```

I believe this `cd ../..` should only be `cd ..`

https://github.com/tailscale/tailscale/blob/0a50ecbad3c46f166dc754516c9c7b1c7d25d3f1/version/long.txt.do#L1

**Comment by bradfitz** [comment]
Sorry, those redo files are meant for when this repo is included as a submodule in our parent "corp" repo. They don't work standalone.

You don't need redo for the open source Go build. (What are you trying to do?)

**Comment by sylr** [comment]
When doing #347 I got into errors saying the version of the frontend and the backend mismatched and thus it crashed.

I tried to overwrite `version.LONG` with `-ldflags "-X version.LONG"` while building the frontend but it turns out it works only for vars not consts.

So then I tried things to see how you do thing.
