### ISSUE TITLE
ACL Preview rules shows additional column to the right when a user is selected

### ISSUE THREAD

**Issue by catzkorn** [tailscale/tailscale#3491]
### What is the issue?

![Screen Shot 2021-12-03 at 10 48 05 AM](https://user-images.githubusercontent.com/46385858/144631700-cdb5569c-cab1-4346-bdc2-0fbc294b7bd9.png)

**Comment by DentonGentry** [comment]
I think we fixed this somewhere along the way.
Barring further comment, we'll expect to close this during the next regular bug scrub.

<img width="1142" alt="Screenshot 2023-02-16 at 10 00 32 PM" src="https://user-images.githubusercontent.com/1140756/219553503-39de423f-503e-4624-a85e-a2e769420264.png">
