### ISSUE TITLE
tailscales will not connect on Pi when a Cellular Hat is used as its connection to the internet

### ISSUE THREAD

**Issue by Mr-Frank-Jaeger** [tailscale/tailscale#3494]
### What is the issue?

I have a Raspberry Pi running Tailscale with now issue when connected over LAN and/or Wifi. However, when I use a Celluar Pi Hat (Six Fab) as the sole internet connection, Tailscale will not get an IP address. I have no other issue with services running over the cell hat. When I run Wireguard on its own it can use the cell hat just fine. 

I thought it might be a socket issue but when i tried to view tailscale.sock i get a permission denied even as root.

Ideas?

### Steps to reproduce

Run tailscales on a Pi with a Celluar Hat as the sole internet connection

### OS

Linux

### OS version

Ubuntu 20.04 Focal

### Tailscale version

tailscale 1.18.1

### Bug report

BUG-ea6a5c0aa706e9bd85a08719a757475196c8cb7637b1036056307f898183774f-20210907184829Z-cc68207efa2ac06c

**Comment by bradfitz** [comment]
Tailscale will use whatever your default route is. When you say you're using your cell hat (`wwx224a23991a00` it looks like) "as the sole internet connection", how are you doing that? What are you using/typing to switching back and forth?

Do you mind if I paste some of your bug report details into this public bug?

**Comment by DentonGentry** [comment]
ETIMEDOUT.
