### ISSUE TITLE
Docker image shows image version 1.18.0 while upgraded to 1.18.1

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3496]
### What is the issue?

Docker image upgraded to 1.18.1 But that image still shows v1.18.0. Please update the official docker image to v1.18.1.

### OS

Other

### OS version

Docker

### Tailscale version

1.18.1

**Comment by bradfitz** [comment]
> Docker image upgraded to 1.18.1 But that image still shows v1.18.0. Please update the official docker image to v1.18.1.

Can you elaborate? How was the image upgraded to 1.18.1?

I don't see 1.18.1 published: https://hub.docker.com/r/tailscale/tailscale/tags

So how did you try to update to it?

**Comment by DentonGentry** [comment]
I imagine that was the phrasing in the email request.
Maisem just updated the dockerhub and ghcr images to 1.18.1.
