### ISSUE TITLE
FR: Filter Machines view by tag

### ISSUE THREAD

**Issue by secure411dotorg** [tailscale/tailscale#3502]
### What are you trying to do?

Filter the machines view by tags

### How should we solve this?

Tag AND tag OR tag etc logic to filter display of machines

### What is the impact of not solving this?

Hard to get a list of machines with or without certain tag combinations

**Comment by rosszurowski** [comment]
You can do this today. We haven't built a UI for it yet (tracked in #2540), but if you search for `tag:foo` in the machines search bar, you'll see all machines tagged with `foo`.

Here's an example link for `tag:server`: https://login.tailscale.com/admin/machines?q=tag%3Aserver

**Comment by mayakacz** [comment]
This is now documented as well: https://tailscale.com/kb/1176/filter-devices/
