### ISSUE TITLE
Slow debian mirror from french Orange ISP

### ISSUE THREAD

**Issue by sylr** [tailscale/tailscale#351]
It takes ages to download tailscale package over a FTTH subscription from the french Orange ISP.

From my home I get this:

```
$ wget https://pkgs.tailscale.com/stable/debian/pool/tailscale_0.98-0_armhf.deb
--2020-05-05 09:12:50--  https://pkgs.tailscale.com/stable/debian/pool/tailscale_0.98-0_armhf.deb
Resolving pkgs.tailscale.com (pkgs.tailscale.com)... 165.227.17.164, 2604:a880:2:d0::61c:d001
Connecting to pkgs.tailscale.com (pkgs.tailscale.com)|165.227.17.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11465610 (11M) [application/x-debian-package]
Saving to: ‘tailscale_0.98-0_armhf.deb.3’

tailscale_0.98-0_armhf.deb.3    100%[====================================================>]  10.93M  40.7KB/s    in 3m 53s

2020-05-05 09:16:44 (48.1 KB/s) - ‘tailscale_0.98-0_armhf.deb.3’ saved [11465610/11465610]
```

I don't have the problem from a cloud instance located in Paris.

I brought the problem to a french networking related mailing list and they asked if I could provide **a reverse traceroute, from the mirror to my IP**.

Could someone with access to the mirror could mail me so that I can share my home IP in order to do a traceroute ?

Regards.

**Comment by danderson** [comment]
Email support@tailscale.com and I can help you.

**Comment by danderson** [comment]
Received on support@, closing here.
