### ISSUE TITLE
FR: Allow billing email to be specified

### ISSUE THREAD

**Issue by michael-careplanner** [tailscale/tailscale#3510]
### What are you trying to do?

Currently the invoice / receipts for our plan go to the email address of the owner. The owner of the account is part of the ops team and is not responsible for the accounting of the plan. Therefore the owner has to either set up an auto-forward rule to forward the bills to the responsible person or forward them manually each month.

### How should we solve this?

It would be great if you could specify one or more emails to send this billing information to, so that we could have billing info sent directly to the responsible person in the accounts dept.

### What is the impact of not solving this?

Having to forward the emails manually or set up auto-forwarding rules for the bills specifically.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_43s5t)

**Comment by DentonGentry** [comment]
In the meantime, you're welcome to contact support@tailscale.com to update the billing address.

**Comment by mayakacz** [comment]
> It would be great if you could specify one or more emails to send this billing information to, so that we could have billing info sent directly to the responsible person in the accounts dept.

This is possible as of May 2022: https://tailscale.com/changelog/#2022-05-19-service

https://tailscale.com/kb/1182/billing-information/#billing-email
