### ISSUE TITLE
Install script needs to make debian tailscale install non-interactive

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3528]
### What is the issue?

https://www.youtube.com/watch?v=qe9gLZu1izQ found that the install script just runs `apt-get install tailscale`, which will prompt interactively if additional dependencies are required (e.g. if you're in a minimal container and don't have iptables installed yet), which fails if you're following the website instructions because you don't get to provide interactive input.

We should add `-y` to the install command, and also set `DEBIAN_FRONTEND=noninteractive` to disable dpkg config prompting (we don't have any, but our dependencies might).

**Comment by DentonGentry** [comment]
We did something similar for RPM in https://github.com/tailscale/tailscale/pull/3541
