### ISSUE TITLE
`tailscale status --json` returns `0001-01-01T00:00:00Z` for node `LastSeen`

### ISSUE THREAD

**Issue by hmaurer** [tailscale/tailscale#3533]
### What is the issue?

Running `tailscale status --json` often returns `0001-01-01T00:00:00Z` for `LastSeen`, both under `Self` and `Peer`. It would appear that if a machine has been disconnected for a little while then it will return a sensible timestamp (the time when it disconnected), but if the machine is online it will return `0001-01-01T00:00:00Z`. Note that the Tailscale dashboard (`login.tailscale.com/admin/machines`) always shows a sensible `lastSeen`: the API this dashboard uses (`https://login.tailscale.com/admin/api/machines`) seems to return the correct timestamps.

Also note that `LastHandshake` and `LastWrite` appear to exhibit a similar issue.

### Steps to reproduce

Connect a few machines to Tailscale and run `tailscale status --json` on one of the machines. You should see `"LastSeen": "0001-01-01T00:00:00Z"` in places where you'd expect a timestamp matching what can be seen on the dashboard (e.g. if a machine is connected, the timestamp should be current-ish). 

### OS

Linux

### OS version

Debian 11.1

### Tailscale version

1.18.1

### Bug report

BUG-3342af652b3e43b9cd37ee32ba8f0a5aa33e81a96f6681823126c3b30346c200-20211208142817Z-f88bd32615d64f4f

**Comment by bradfitz** [comment]
When you run "tailscale status", that's the CLI asking the tailscaled daemon on the same machine for information; it's not hitting our control plane servers.

For battery/bandwidth reasons, the control plane only sends down LastSeen times to nodes for peers that are offline, otherwise the LastSeen time would always be changing (if your peers are online, they're continuously last seen)

So this is pretty much working as intended, I think.

Would you prefer `LastSeen` just being omitted from the JSON entirely? Or set to `null`?

**Comment by hmaurer** [comment]
@bradfitz ah I see, thanks for the quick reply and sorry for the mistaken bug report! Is this documented anywhere? My apologies if I missed it.

I'm not sure I would prefer having it set to `null` or omitted. If I saw it sometimes containing a timestamp, sometimes being `null` or omitted I'd have opened an issue here as well. 

To get up to date information I should hit the control plane directly via https://github.com/tailscale/tailscale/blob/main/api.md, correct?

**Comment by hmaurer** [comment]
@bradfitz Perhaps I should describe my use-case to you instead: I intended to use `tailscale status --json` to automatically discover online peers whose name match a certain pattern, which is why I'm looking for an up-to-date `LastSeen` timestamp.

**Comment by bradfitz** [comment]
> Perhaps I should describe my use-case to you instead:

And deprive me of the opportunity to send people to https://xyproblem.info/ !? Alas. :)

> to automatically discover online peers whose name match a certain pattern, which is why I'm looking for an up-to-date
> LastSeen timestamp

Oh! The `status --json` doesn't have the `Online` boolean field. Tailscaled knows that internally. We can add that.

**Comment by hmaurer** [comment]
@bradfitz That'd be wonderful! Thanks for being so responsive. And that issue aside, my experience so far with Tailscale has been flawless.

**Comment by bradfitz** [comment]
I sent https://github.com/tailscale/tailscale/pull/3534
