### ISSUE TITLE
Expired SSL Cert (hello.ipn.dev)

### ISSUE THREAD

**Issue by Joshua-Noakes1** [tailscale/tailscale#3535]
### What is the issue?

I'm unable to check that im properly connected to Tailscale due to Brave and Firefox are both showing that the SSL Cert for hello.ipn.dev which has expired on the 6th of December.

Firefox
![image](https://user-images.githubusercontent.com/53623449/145259048-f24332f0-8a5a-4df1-9591-fc7d9464bb59.png)
Brave
![brave_BHfPtiiWY3](https://user-images.githubusercontent.com/53623449/145258643-250d48ff-87e2-4d9f-bf83-2d4a1798c49c.png)

### Steps to reproduce

1. Access [hello.ipn.dev](https://hello.ipn.dev)
2. See SSL Cert Issue

### OS

Windows

### OS version

Windows 11 21H2

### Tailscale version

1.16.2

### Bug report

BUG-2e1c2838fb8be3d615792913a6e20d46eb3616f0b4a37ca77e3622930d0d3945-20211208175506Z-729faedaca852df1

**Comment by wbolster** [comment]
also seeing this on chrome+linux, which shows a page containing this info:

```
Your connection is not private
Attackers might be trying to steal your information from hello.ipn.dev (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
Subject: hello.ipn.dev

Issuer: Gandi Standard SSL CA 2

Expires on: 7 Dec 2021

Current date: 3 Jan 2022

PEM encoded chain:
[...]
```

**Comment by DentonGentry** [comment]
<img width="487" alt="Screen Shot 2022-01-03 at 5 15 51 PM" src="https://user-images.githubusercontent.com/1140756/147997345-f8c6f106-e239-451d-af1e-7a8adbf7cb92.png">
