### ISSUE TITLE
Android 1.19.116 after a time says "No Internet connection" and stops working

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#3542]
### What is the issue?

Reported in Beta user feedback: "Says no internet on this new build after so long and stops working"

### OS

Android

### OS version

Android 10

### Tailscale version

1.19.116

**Comment by DentonGentry** [comment]
The previous code was:
```
        private void registerNetworkCallback() {
                BroadcastReceiver connectivityChanged = new BroadcastReceiver() {
                        @Override public void onReceive(Context ctx, Intent intent) {
                                boolean noconn = intent.getBooleanExtra(ConnectivityManager.EXTRA_NO_CONNECTIVITY, false);
                                onConnectivityChanged(!noconn);
                };
                registerReceiver(connectivityChanged, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
```

However, [EXTRA_NO_CONNECTIVITY has not worked since Android 4](https://stackoverflow.com/questions/29677852/connectivitymanager-extra-no-connectivity-is-always-false-on-android-lollipop). 

Since we only run on Android 5 and later, in versions of the Android app prior to 1.19.116 the previous code would always call onConnectivityChanged(true). It couldn't actually detect when connectivity was lost, so the "No Internet connectivity" message could never have appeared. I've certainly never seen it, didn't even know it was there.

The new code is:
```
                ConnectivityManager cMgr = (ConnectivityManager) this.getSystemService(Context.CONNECTIVITY_SERVICE);
                cMgr.registerNetworkCallback(new NetworkRequest.Builder().build(), new ConnectivityManager.NetworkCallback() {
                        @Override
                        public void onLost(Network network) {
                                onConnectivityChanged(false);
                        }
 
                        @Override
                        public void onLinkPropertiesChanged(Network network, LinkProperties linkProperties) {
                                onConnectivityChanged(true);
                        }
                });
```

This code does detect when connectivity is lost.

I can make it happen by turning off both Wi-Fi and LTE.
![NoInternet](https://user-images.githubusercontent.com/1140756/145515168-455c1162-c929-441e-86f0-13ef9ea54c82.jpg)

**Comment by DentonGentry** [comment]
I'm thinking of just removing the "No internet connection" code. We're quite well aware that a phone can go out of connectivity range, we don't need Tailscale calling attention to it.

**Comment by bradfitz** [comment]
That seems like a step in the wrong direction. Ideally our GUIs would show a bunch more detail about what link(s) are up and what paths are being taken. Currently the Android (and mac/iOS?) apps have about 1 bit of information: internet up or down. Bit sad to lose even that. But I guess if it's not accurate, that's even worse.

**Comment by DentonGentry** [comment]
The user report is from Android 10. I haven't managed to resurrect a device which can run Android 10, just a Nexus 5X with Android 8.1 (which works fine and does not get stuck at "No internet connection")

**Comment by DentonGentry** [comment]
I've been trying to reproduce this for days, on Android 12 and Android 8. No luck so far, I've only been able to make it appear by deliberately turning off all network interfaces.

The user who reported it hasn't responded further. At this point I suspect that the app isn't out of connectivity more often than it was before, the difference is that now it says so where before that UI function was broken.

**Comment by DentonGentry** [comment]
I think I've produced it today, after being in a spot with bad Wifi for a couple hours. The Wifi network kept coming and going. I'm running a build which added a log message when the LostInternet state changes: true means it has lost Internet, false means it has Internet. We see:

```
12-12 16:12:35.029 26735 27011 I com.tailscale.ipn: LostInternet state change: false -> true
12-12 16:12:35.751 26735 26755 I com.tailscale.ipn: LostInternet state change: true -> false
12-12 16:12:41.600 26735 28863 I com.tailscale.ipn: LostInternet state change: false -> true
12-12 16:12:44.872 26735 26761 I com.tailscale.ipn: LostInternet state change: true -> false
12-12 16:12:48.891 26735 26767 I com.tailscale.ipn: LostInternet state change: false -> true
12-12 16:12:52.006 26735 26755 I com.tailscale.ipn: LostInternet state change: true -> false
12-12 16:12:57.453 26735 27011 I com.tailscale.ipn: LostInternet state change: false -> true
12-12 16:13:00.707 26735 26760 I com.tailscale.ipn: LostInternet state change: true -> false
12-12 16:13:30.830 26735 26767 I com.tailscale.ipn: LostInternet state change: false -> true
```

This means that the last event it received was an onLost event. It did not receive a LinkProperties event after that, even though the Wi-Fi was up. Because the last event it received was onLost, it put up the "No Internet connection" in the UI.

Tailscale is up and working. I'm able to resolve DNS and reach devices on the tailnet. This happens because even after we received that last onLost event, the app detected a time jump and synthesized a LinkChange. The LinkChange event found the Wi-Fi network up and found its DNS servers, so tailscale is working.

```
10983 12-12 16:13:30.830 26735 26767 I com.tailscale.ipn: LostInternet state change: false -> true
10986 12-12 16:13:30.866 26735 17122 I com.tailscale.ipn: 20.1M/98.8M monitor: time jumped (probably wake from sleep); synthesizing major change event
10987 12-12 16:13:30.867 26735 17122 I com.tailscale.ipn: 20.1M/98.8M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={rmnet_data1:[XXX/64] rmnet_data2:[XXX/64] tun0:[w.x.y.z/32 XXX/128] v4-rmnet_data1:[192.0.0.4/32] wlan0:[10.1.10.131/24 XXX/64 XXX/64]} v4=true v6=true}
10988 12-12 16:13:30.867 26735 17122 I com.tailscale.ipn: 20.1M/98.8M dns: Set: {DefaultResolvers:[] Routes:{example.com.beta.tailscale.net.:[] :[w.x.y.z:53] :[]}+65arpa SearchDomains:[example.ts.net. example.com.beta.tailscale.net. ] Hosts:58}
10989 12-12 16:13:30.876 26735 17122 I com.tailscale.ipn: getDnsConfigFromLinkProperties: XXX 10.1.10.1 ;localdomain
10994 12-12 16:13:30.877 26735 17122 I com.tailscale.ipn: getDnsServersFromSystemProperties:
10995 12-12 16:13:30.879 26735 17122 I com.tailscale.ipn: getDnsServersFromNetworkInfo: 10.1.10.1
10996 12-12 16:13:30.887 26735 17122 I com.tailscale.ipn: 20.1M/98.8M dns: Resolvercfg: {Routes:{.:[[XXX]:53 10.1.10.1:53] ts-dns.test.:[w.x.y.z:53]} Hosts:58 LocalDomains:[example.com.beta.tailscale.net. ts.net.]+65arpa}
10997 12-12 16:13:30.887 26735 17122 I com.tailscale.ipn: 20.1M/98.8M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[example.ts.net. example.com.beta.tailscale.net. localdomain.] MatchDomains:[]}
```

Looking through the events, we're making an assumption that they will arrive in order and that, if there is a link up, that it will be the last link event received. For example, we're expecting that the LTE network onLost will arrive before the Wi-Fi onLinkPropertiesChanged arrives. I don't think the ConnectivityManager guarantees this.

In API level 24 (Android 7) a `registerDefaultNetworkCallback` was added. I think this is closer to what we want: we don't really want to monitor the state of all interfaces, we just want to know if there is connectivity and what its DNS servers are.

I think instead we should:
1. use the same callback for onLost, onAvailable, and onLinkPropertiesChanged, anything indicating a change in network state.
1. in the callback, check whether there is an active network connection. `ConnectivityManager.getActiveNetwork()` may work for this.
1. Decide what to pass to `onConnectivityChanged`, up or down, based on the active network info not the type of event.

![NoInternet](https://user-images.githubusercontent.com/1140756/145750944-dff07902-bb8e-44d9-84c9-59b593d474fb.jpg)
