### ISSUE TITLE
Hibernation not working on Synology with tailscale 1.16.2

### ISSUE THREAD

**Issue by denngituse** [tailscale/tailscale#3551]
### What is the issue?

Usually all hard drives should be off, if the Synologybox is not used. With the installation of tailscale I noticed that the hard drives are always on. s that a wanted behaviour, if not how could I change it?

### OS

Synology

### OS version

DSM 6.2.4-25556 Update 2

### Tailscale version

1.16.2-013

**Comment by bradfitz** [comment]
Interesting. I didn't even know Synology NAS disks spun down ever.

It's probably our logging keeping them awake.

What's your Tailscale IP? (it's safe to share them publicly; nobody else can do anything with them)

**Comment by denngituse** [comment]
Yes they do and by that lifespan extend quite a lot.

My IP is 100.117.36.65

**Comment by mback2k** [comment]
I am affected as well and can share these links about Synology hibernation which may help understand the situation a bit better. I also think it is most likely the continues logging preventing it from hibernating disks from observing disk LEDs.

https://kb.synology.com/en-vn/DSM/help/DSM/AdminCenter/system_hardware_hibernation?version=6
https://kb.synology.com/en-vn/DSM/tutorial/What_stops_my_Synology_NAS_from_entering_System_Hibernation

**Comment by rzeidler** [comment]
Same here. If Tailscale is enabled on my Synology NAS there seems to be HDD activity every couple of minutes even if the NAS is not used and no other services are running. After disabling the Tailscale service this ceases and HDDs go to sleep after the chosen time.

**Comment by DentonGentry** [comment]
This is most likely related to collecting telemetry in a file on disk.
Writing to a ramdisk instead might be a way to address this.

**Comment by deerhunter91** [comment]
This is an ongoing problem. It looks like Tailscale on Linux has a configuration file to reduce logging (https://github.com/tailscale/tailscale/issues/282), but I cannot find either a configuration file or a way to set a configuration file.  

Not being able to hibernate drives will reduce their lifespan and increase power consumption.

**Comment by DentonGentry** [comment]
This is expected to be resolved in the upcoming Tailscale 1.26.0 release for Synology platforms.

**Comment by isaackwan** [comment]
Hello - I hope that it's fine to re-post in this ticket
I still notice that my Synology would get waken up by Tailscale logs every now and then
It seems that there is a stdout log file under /var/packages/Tailscale/var/tailscaled.stdout.log
Wonder if we can put it under /tmp too or even discard it completely?
