### ISSUE TITLE
doc: document arbitrary IP protocol support

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3554]
Tracking bug to remind us to document support for arbitrary IP protocols in ACL rules.

/cc @mayakacz

**Comment by bradfitz** [comment]
Previously: SCTP (in #1516), for 1.8.0.

And https://github.com/tailscale/tailscale/commit/69de3bf7bfddb37b4c0e076c93115f82a51ec407 that's in, due to be in 1.20.0 (or in 1.19.x unstable builds).

**Comment by mayakacz** [comment]
Two questions after looking at https://github.com/tailscale/corp/pull/3270:

1. Is this part implemented too, or can you can have an ACL that specifies both protocol and ports?

> But in December 2021, in tailscale/tailscale@69de3bf,
for 1.20.0, the client was updated to support any IP protocol number,
even without parsing support, so long as the accept rule destinaton port
is for all ports.


2. Can protocols also be used in ACL tests?

**Comment by bradfitz** [comment]
(1) your ACL can specify IP protocols and ports independently with no restricts on control's side, but 1.19.x (1.20.0) clients will only permit traffic for a protocol they don't know how to parse if the ACL port range is the set of all ports. For TCP, UDP, and SCTP, they'll look at the ports. But for everything else it says "IP protocol number 16? No clue what that is. Not going to allow. Oh, but the ACLs say that all ports on that proto are allowed, so whatever it is, sure... I don't need to know how to parse its ports out. Maybe it doesn't even have ports!"

(2) no. You can't even write UDP or SCTP tests today; they're always TCP right now. (by default, rules omitted protocol mean TCP & UDP)  I filed #3561 to track supporting that.
