### ISSUE TITLE
ghcr.io Container Image Tagging lacks `stable` as an option

### ISSUE THREAD

**Issue by guest42069** [tailscale/tailscale#3555]
### What is the issue?

Hi,

https://github.com/orgs/tailscale/packages/container/package/tailscale

At the moment `v1.18.0` holds the `latest` tag, while the Tailscale admin interface will (correctly) notify you that an update to `v1.18.1` is available for devices running the `latest` image.

A `v1.18.1` tag is available, and seems to also be tagged for `v1.18` in general (I.E. obsoleting `v1.18.0`) but it does not hold the (normally default) `latest` tag which is still associated with the `v1.18.0` image.

Maybe this isn't in error and it's intended that I should be more explicit in my versioning? I understand this could be desirable under some circumstances. If it is, please let me know and I'll be happy to close this issue.

Thanks.

### Steps to reproduce

run `docker pull ghcr.io/tailscale/tailscale:latest` and received `v1.18.0` rather than the expected `v1.18.1`.

### OS

Linux

### OS version

Containers

**Comment by maisem** [comment]
We recently updated our docs on https://hub.docker.com/r/tailscale/tailscale.

This is how we are going to be setting container tags going forward:

###  Supported tags
* `stable`, `latest` to get the latest stable version.
  * `v1.20.1`, `v1.20` to get a specific stable version.
* `unstable` to get the latest unstable version.
  * `v1.21.26`, `v1.21` to get a specific unstable version.


I'll try to figure out how to put this on https://ghcr.io/tailscale/tailscale as well

**Comment by DentonGentry** [comment]
This is fixed, there is now a stable tag. It currently points to 1.36.1: https://github.com/tailscale/tailscale/pkgs/container/tailscale
