### ISSUE TITLE
FR: Allow hinting to the client as to which IdP to use

### ISSUE THREAD

**Issue by AdrianFletcher** [tailscale/tailscale#3562]
### What are you trying to do?

We have most (all) of our users on machines joined to Azure AD. As part of deployment of TailScale it would be nice to provide something akin to a 'hint' to TailScale that the user is on a particular IdP.

As our users are already authenticated with Azure AD, modern authentication should allow the client to 'automatically' connect, assuming it knows which IdP to attempt to log on with.

### How should we solve this?

A hint could be provided via the installer, for example:

TailScale.exe /S /IDP_HINT=AZUREAD
or as an MSI property IDP_HINT=AZUREAD

The client could automatically attempt to log on via the suggested identity provider (e.g. the UPN of the user is available from whoami.exe /UPN).

It could also mean showing AzureAD as the default (or highlighted) on the login page.

### What is the impact of not solving this?

Currently we provide screenshots and documentation to our users on how to log on and which IdP to select when logging on. Our goal would be to deploy the TailScale client (e.g. via Endpoint/Intune) and have the software install and users automatically connect) without any user involvement.

**Comment by bradfitz** [comment]
We do already have a handful of Windows-specific registry settings that change the behavior of the Windows client.

Adding a `IDPHint` registery key that gets appended (by the client, even) to the login URL as provided by the control plane could be feasible. Control could send `https://login.tailscale.com/a/xxyxyxyxy` and then the client instead opens `https://login.tailscale.com/a/xxyxyxyxy?idphint=ms`

/cc @dblohm7 @sailorfrag @crawshaw @mayakacz

**Comment by AdrianFletcher** [comment]
Brad, do you know if these Windows-specific registry settings are documented? I'm having trouble finding them.

**Comment by sailorfrag** [comment]
@AdrianFletcher This has become somewhat out of date (both for service data directory which we moved in 1.14.4 to avoid Windows Update problems, and for some more recently added policy options), but https://tailscale.com/kb/1102/windows-config-and-log-files/

**Comment by AdrianFletcher** [comment]
That's great thanks @sailorfrag, I'll keep an eye on that FAQ in case it gets updated.

**Comment by DentonGentry** [comment]
There is some overlap with https://github.com/tailscale/tailscale/issues/942

**Comment by sailorfrag** [comment]
> That's great thanks @sailorfrag, I'll keep an eye on that FAQ in case it gets updated.

I just updated the KB article.

**Comment by kvanbere** [comment]
Hi, we really love Tailscale, but deployment to Windows workstations is difficult at the moment. If it could somehow be signaled to just automatically sign-in with the users 365 Azure AD creds, that would be a huge win because we integrate Tailscale installation with the Windows Autopilot unboxing experience.

This translates to you selling heaps of licenses to orgs because it's pushed to every computer.

**Comment by DentonGentry** [comment]
A control server update about two weeks ago will at least tell users if they've used the wrong IdP and which IdP they should use, to minimize support tickets from getting the wrong one.

**Comment by DentonGentry** [comment]
The coordination server now says: "Incorrect identity service: use google for example.com"
