### ISSUE TITLE
Better Android TV support

### ISSUE THREAD

**Issue by karnauskas** [tailscale/tailscale#3568]
### What is the issue?

Can't click on "Get Started" to start configuration.

### Steps to reproduce

Open Tailscale on Amazon FireTV Stick and try configure it.

### Are there any recent changes that introduced the issue?

IDK if this ever worked before, trying first time. 

### OS

Android

### OS version

Latest Fire OS

### Tailscale version

1.19.127-tcced414c7-ga3d2dc95dbc

**Comment by DentonGentry** [comment]
The Android app doesn't have TV support implemented for the remote control to work, but other users have reported success using Mouse Toggle https://www.firesticktricks.com/mouse-toggle-firestick.html

There is a reddit post which may help: https://www.reddit.com/r/fireTV/comments/r5fiom/guide_on_how_to_get_tailscale_working_with_a_fire/

**Comment by karnauskas** [comment]
Apparently, this was know issue https://github.com/tailscale/tailscale/issues/1611

**Comment by bradfitz** [comment]
Closing this in favor of #1611

I'll post updates there.
