### ISSUE TITLE
IPv6 problems with vxlan and tailscale

### ISSUE THREAD

**Issue by manuelbuil** [tailscale/tailscale#3575]
### What is the issue?

I installed tailscale and I have a tailscale0 interface. Now, I want to create a vxlan interface. If I choose the tailscale0 interface, things work for ipv4:
```
sudo ip link add vxlan-testing type vxlan id 10 dstport 4789 dev tailscale0
sudo ip addr add 192.168.0.12/32 dev vxlan-testing
```

But they don't for ipv6:
```
sudo ip link add vxlan-testing type vxlan id 10 dstport 4789 dev tailscale0
sudo ip addr add 2001:abcc:99::/128 dev vxlan-testing
RTNETLINK answers: Invalid argument
```
Unfortunately, the error does not help much and I don't know why it is not working

### Steps to reproduce

```
curl -fsSL https://tailscale.com/install.sh | sh
tailscale up
sudo ip link add vxlan-testing type vxlan id 10 dstport 4789 dev tailscale0
sudo ip addr add 2001:abcc:99::/128 dev vxlan-testing
```

### Are there any recent changes that introduced the issue?

Not that I know

### OS

Linux

### OS version

Ubuntu 20

### Tailscale version

1.18.1

### Bug report

BUG-85905593bc00fe3e5f97ee613b41fe860eb871e2851beb440fe8dac1732ec1f5-20211215210835Z-4bca1a2133a0e5df

**Comment by DentonGentry** [comment]
You're trying to create a VXLAN overlay to run through the Tailscale network?

IPv6 might fail because of MTU size. The MTU of the tailscale0 interface is 1280 bytes, which is the minimum for IPv6. So after the underlay headers and VXLAN header, the MTU is smaller than 1280 and might be rejected somewhere within the stack.

**Comment by manuelbuil** [comment]
> You're trying to create a VXLAN overlay to run on top of the Tailscale network?
> 
> IPv6 might fail because of MTU size. The MTU of the tailscale0 interface is 1280 bytes, which is the minimum for IPv6. So after the underlay headers and VXLAN header, the MTU is smaller than 1280 and might be rejected somewhere within the stack.

Thanks! That was it. After increasing the MTU of the tailscale0 interface, I was able to create the vxlan interface and add an ipv6 address. Is it ok to increase the MTU of the tailscale0 interface or will that break the connectivity?

**Comment by DentonGentry** [comment]
One difficulty would be that Tailscale is itself an overlay. The 1280 byte MTU it uses by default allows 1500-1280 = 220 bytes of room for the outer IP + UDP header (48 bytes in the case of an IPv6 outer header), plus wireguard headers which are variable size. (220 - 48) = 172 bytes is plenty for Wireguard, but the more you increase the MTU the more chance it will break if Wireguard needs to do some kind of renegotiation which needs more room.

**Comment by manuelbuil** [comment]
> 



> One difficulty would be that Tailscale is itself an overlay. The 1280 byte MTU it uses by default allows 1500-1280 = 220 bytes of room for the outer IP + UDP header (48 bytes in the case of an IPv6 outer header), plus wireguard headers which are variable size. (220 - 48) = 172 bytes is plenty for Wireguard, but the more you increase the MTU the more chance it will break if Wireguard needs to do some kind of renegotiation which needs more room.

Understood, thanks!
