### ISSUE TITLE
FR: An option to force Tailscale to use DERP for all data transfers.

### ISSUE THREAD

**Issue by solderwire** [tailscale/tailscale#3579]
### What are you trying to do?

To force enable DERP connection for all clients, instead to try to build P2P connections first in network environments where UDP connection is faulty but TCP is stable.

### How should we solve this?

- Add an option on the client application to temporarily use this feature if user knows UDP connection is available but unstable.
- Automatically enable this feature if Tailscale detects faulty UDP connection like which described in the next section.
- Add an option on the custom DERP server to enable this feature globally. If enabled, the DERP server will broadcast a message to all clients connected to it to switch to this mode. Clients in the same LAN will still try to do P2P, but fallback to DERP mode if an unstable UDP connection is detected.

### What is the impact of not solving this?

Some ISPs apply strict QoS rules on UDP traffics for home broadband. If there's an UDP connection consuming higher bandwidth, such as transferring files from my NAS, the ISP will frequently "fuses" this connection for a few seconds. P2P-based solution like Tailscale will set up a P2P network (which is based on UDP) properly, but will fail quickly if there's a bigger data transfer. Another common way is to lower your UDP connection speed to a very small number like 10 kbps, making Tailscale nearly unusable. However, TCP connection doesn't have this issue.

I'm currently using [Tinc](https://www.tinc-vpn.org/) to solve this issue, which can force all clients to use TCP to communicate with the server but it's configuration is just too troublesome.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/2270 concerns automatically remaining with DERP when it is faster than UDP, as described here. I understand this request is for a manual control, however I don't expect to implement that functionality to be manually adjusted.

Dup of https://github.com/tailscale/tailscale/issues/2270

**Comment by talway** [comment]
Do you disagree with manual control, or do you have a better solution? Would you like to know what solution can solve this problem

**Comment by DentonGentry** [comment]
I do not believe manual control is a good solution, the product should do this automatically.
[#2270 ](https://github.com/tailscale/tailscale/issues/2270) tracks that effort.

**Comment by vysecurity** [comment]
Try use host-based firewall to manually block 41641?

**Comment by Thoxvi** [comment]
I think this feature is necessary, our ISP will do QoS and the UDP packets will probably not reach the server correctly

**Comment by ex3ndr** [comment]
It doesn't work on QubesOS, tries to establish a direct connection, but only outgoing stuff is working.

**Comment by DentonGentry** [comment]
@ex3ndr if you believe the product can do something to better support QubesOS please file it as a new feature request, this one is not related.

**Comment by mfat** [comment]
Another vote for manual control since in some countries ISPs mess with UDP packets.

**Comment by gdtv** [comment]
Is there a solution now, please?
