### ISSUE TITLE
Tailscale Windows registry (policy) settings should be under HKLM\Software\Polices\

### ISSUE THREAD

**Issue by AdrianFletcher** [tailscale/tailscale#3584]
### What are you trying to do?

I'm trying to manage the Windows policies of Tailscale in an automated and predictable fashion.

### How should we solve this?

It's generally considered best practice to locate software policies under the HKLM\Software\Policies registry folder. Tailscale currently stores these under [HKLM\Software\Tailscale IPN](https://tailscale.com/kb/1102/windows-config-and-log-files/).

This allows the software policies to play nicely with Group Policy and Endpoint/InTune should your team wish to push out any ADMX files or a sysadmin create their own.

### What is the impact of not solving this?

I'm pushing out configuration changes via a custom installation script (reg add, and reg delete on removal). This does not (easily) allow differentiation of settings depending on the machine/user however.

**Comment by DentonGentry** [comment]
Presumably we would check HKLM\Software\Policies first, then look in HKLM\Software\Tailscale IPN?
Or is there a way to alias a registry key in two locations, for migrations like this?

**Comment by dblohm7** [comment]
Unfortunate the public API for the registry does not allow for any kind of alias/symlink type of thing.

Probably the best way to deal with this is to have policy retrieval code that always accesses the "right" location and migrates if necessary.

**Comment by AdrianFletcher** [comment]
If memory serves, the Policy key cannot be written to except by an elevated process (e.g. the System account), so you might need to read from both, or perhaps log an error/deprecated warning on reading the keys from HKLM\Software\Tailscale IPN?

**Comment by dblohm7** [comment]
We can do it from `tailscaled`

**Comment by dblohm7** [comment]
Policies will be read from `HKLM\Software\Policies` starting with the next unstable build.

**Comment by boonedoggle** [comment]
Are there any plans to provide ADMX for Intune configuration?
