### ISSUE TITLE
"Untrusted node" use case is hindered by ability to re-tag without reauthenticating

### ISSUE THREAD

**Issue by Fysac** [tailscale/tailscale#3590]
### What is the issue?

The use case is described by this now-closed issue: https://github.com/tailscale/tailscale/issues/3352. To limit the impact of a server compromise, an untrusted node should not be able to initiate flows to other nodes.

The solution suggested in that issue is to set up ACL tags to restrict the node's ability to communicate with the Tailscale network. However, as acknowledged in [the documentation for server role accounts](https://tailscale.com/kb/1068/acl-tags/), it's currently possible for the root user on the node to modify or delete the tag without providing any authentication, which could bypass the ACLs and completely negate this security boundary.

It's my understanding that the lack of a reauthentication step for re-tagging is a known issue internally (https://github.com/tailscale/tailscale/issues/2300#issuecomment-880161699). However, I do feel it's worth pointing out that the solution of using ACL tags doesn't fully address the untrusted node use case, and that this issue significantly limits the security properties of server role accounts.

**Comment by DentonGentry** [comment]
In the near future we're expecting to deliver:
1. Allow the tags to be specified on the authkey to authorize a node https://github.com/tailscale/tailscale/issues/1369
2. Not allow the node to remove tags without reauthentication by a TagOwner.

**Comment by DentonGentry** [comment]
I believe this is done now:
1. https://login.tailscale.com/admin/settings/keys allows creation of an authkey with tags associated
1. Re-authentication is required in order to change tags from the device. Tags can also be changed from the admin panel.
