### ISSUE TITLE
tailscaled - netns: DefaultRouteInterfaceIndex: ambiguous gateway interfaces found: map[12:1 13:13 17:196]

### ISSUE THREAD

**Issue by nova876** [tailscale/tailscale#3593]
### What is the issue?

I'm trying to setup an exit node on macOs BigSur and tailscaled cannot find the default gateway interface. Exact same setup works fine on two other macs running BigSur and Monterey. 

[tailscaled startup logs, ifconfig and netstat -rn.md](https://github.com/tailscale/tailscale/files/7739870/tailscaled.startup.logs.ifconfig.and.netstat.-rn.md)

### Steps to reproduce

I suspect that bug is specific to this machine and I couldn't reproduce it on two other machines. I've attached ifconfig and netstat -rn logs.

### Are there any recent changes that introduced the issue?

It tried v1.19.0-date.20211101

### OS

macOS

### OS version

11.6.1

### Tailscale version

v1.19.0-date.20211101

**Comment by DentonGentry** [comment]
This is most likely https://github.com/tailscale/tailscale/issues/3192 or https://github.com/tailscale/tailscale/issues/2524
