### ISSUE TITLE
API: `api/v2/device/<id>/routes` endpoint does not include single IP routes (`/32` in CIDR) in enabled routes

### ISSUE THREAD

**Issue by victorluft** [tailscale/tailscale#3600]
### What is the issue?

When hitting the `api/v2/device/<id>/routes` endpoint, single IP routes (ending with `/32` in the CIDR) are not included in `enabledRoutes` field, even though they're enabled in the UI and successfully routing. They _are_ included in the `advertisedRoutes` field.

`/api/v2/device/<id>` endpoint exhibits the same behavior when `?fields=all` is set.

Example:

```
{
  "advertisedRoutes": [
    "10.0.64.0/24",
    "<not-a-private-use-IP-redacted>/32",
    // big ol' pile of other IPs redacted
  ],
  "enabledRoutes": [
    "10.0.64.0/24"
    // big ol' pile of other IPs redacted, but not including any /32
  ]
}
```

### Steps to reproduce

Brought up a node with `--accept-routes` including a bunch of /32 routes, then started using [David Bond's terraform provider](https://github.com/davidsbond/terraform-provider-tailscale) to manage my subnet routing. This would always detect a change in the enabled route set and want to re-add those routes, so I poked at the API and discovered the above behavior.

### Are there any recent changes that introduced the issue?

Unknown; have not attempted to use the API before this bug.

### OS

Linux, iOS

### OS version

NixOS unstable, mostly; machine forwarding the subnet routes is on Ubuntu 18.04.6.

### Tailscale version

1.18.2 on all devices

### Bug report

BUG-be5d2459349fe5f85aaa1564cff7d24faa9346228e349e32b713e8038bcb0378-20211220174547Z-f9c1b4ea3e77a473

**Comment by bradfitz** [comment]
Thanks, fixed! It's not yet deployed, but should be soon-ish.
