### ISSUE TITLE
2 of my IPs changed when they shouldn't have

### ISSUE THREAD

**Issue by kevjustice** [tailscale/tailscale#3601]
### What is the issue?

At least 2 (that I know of) of my tailscale IP's changed.  per the documentation this should not happen.  

### Steps to reproduce

I have no idea - I could connect days ago, tried today and it failed.  Went into interface and found IPs were different.

### OS

Linux, Windows

### OS version

Win 11, Ubuntu 20.04

### Tailscale version

1.18.2, 1.16.2

### Bug report

BUG-fe17c0bb3d87a76b1e8438af20054d7beb5f43bf9ae725f9a1980dde9c0eb53c-20211220193535Z-f98135e301f53c86

**Comment by DentonGentry** [comment]
You'll need to actually say the IP addresses you expected to be present on the account. You can send them to support@tailscale.com if you don't want to put them in a public bug (though it is safe to put them in the bug, your ability to connect to a Tailscale IP address is based on having its encryption keys not based on the obscurity of the IP address).

**Comment by DentonGentry** [comment]
ETIMEDOUT, cannot investigate.
