### ISSUE TITLE
Trend Micro PUA.Win32.TScaleVPN.A

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#3603]
### What is the issue?

Trend Micro has created a PUA.Win32.TScaleVPN.A definition specifically for the Tailscale installer: https://www.virustotal.com/gui/file/eb4ed5f6140aa6e26adf5408f9924e5263b9c0fa3b66cec699f7e50eb893537c/detection

This was reported by a user in tailscale/tailscale#3181 (comment)

We're starting with a request for re-evaluation: https://www.trendmicro.com/en_us/about/legal/detection-reevaluation.html
submitted Dec 20, 2021 at approximately 4:40pm Pacific time.

Creating this issue for public tracking of any progress.

**Comment by bradfitz** [comment]
Also, as I've mentioned previously on other such bugs, to give people some peace of mind: our Windows binaries are not built on Windows. They're built in hermetic Linux environments, so the normal contamination risk (infected Windows build machine infecting the built software) isn't there.

**Comment by hiatsu0** [comment]
F-Secure also seems to flag the latest installer as `Trojan:W32/Generic.4afa6d150e!Online`

**Comment by JayWStapleton** [comment]
> F-Secure also seems to flag the latest installer as `Trojan:W32/Generic.4afa6d150e!Online`

Thanks for pointing that out. On which platform are you seeing that?

**Comment by hiatsu0** [comment]
> On which platform are you seeing that?

Windows 10

**Comment by JayWStapleton** [comment]
> F-Secure also seems to flag the latest installer as `Trojan:W32/Generic.4afa6d150e!Online`

I have heard back from F-Secure. They have confirmed that it was a false positive and have master a fix on their end.

**Comment by DentonGentry** [comment]
1.20.x is not flagged as PUA.
