### ISSUE TITLE
accept-routes and advertise-routes on host doesn't allow network access

### ISSUE THREAD

**Issue by 12nick12** [tailscale/tailscale#3610]
### What is the issue?

When enabling accept-routes and advertise-routes on host, the host can no longer access the local network, but has access to the internet. 

### Steps to reproduce

Tailscale up with advertise-routes and accept-routes enabled.

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.18.2

**Comment by DentonGentry** [comment]
For anyone to be able to look at this there will need to be details of what was configured and ideally a `tailscale bugreport` from the node during the time when there is no local network connectivity.

**Comment by 12nick12** [comment]
I think w
