### ISSUE TITLE
Problems with Clipboard on Windows

### ISSUE THREAD

**Issue by NicolaP8** [tailscale/tailscale#3611]
### What is the issue?

Tailscale 1.18.0 and 1.18.2 on Windows 8.1
When copying an IP from the Tailscale app the Clipboard continue to contains a previous item of type "Text".
This can be seen with ClipBoardViewer from an old Windows version or a similar utility.
Tailscale put a "Unicode text" in the Clipboard that some program will detect and paste but other (eg. Firefox :-( ) will not.

### Steps to reproduce

Copy a text,
from the Tailscale menu copy the IP of a device,
paste in Firefox

### OS

Windows

### OS version

Window 8.1

### Tailscale version

1.18.0 1.18.2

### Bug report

BUG-bc524f832b3e7583e1251655d7a9e703e453dc44f5ad1e7c924fbe9094456bc9-20211223171 232Z-4281c833119a9705

**Comment by bradfitz** [comment]
Fun bug report! :)

I suppose we could detect whether the copied text is plain ASCII (as it always is so far for our uses) and change the type between Unicode vs text.

/cc @dblohm7 (for multiple reasons :))

**Comment by NicolaP8** [comment]
> I suppose we could detect whether the copied text is plain ASCII (as it always is so far for our uses) and change the type between Unicode vs text.
I suppose that is not useful: Tailscale si sending the text to the Clipboard using the wrong function... 
There is no need to do nothing before, like ALL other software!
https://docs.microsoft.com/en-us/windows/win32/dataxchg/using-the-clipboard#copying-information-to-the-clipboard

**Comment by dblohm7** [comment]
The clipboard allows for a copy operation to contain multiple formats. The most sensible thing to do here is to modify `walk` so that it sets the data in both `CF_UNICODETEXT` and `CF_TEXT`, thus covering all bases.

**Comment by dblohm7** [comment]
Though I also put my Firefox developer cap on and took a look at its code, and it should be handling this correctly. I might need to file a bug over there, too! 😉

**Comment by dblohm7** [comment]
I can reproduce this locally.

**Comment by DentonGentry** [comment]
Note that the fix will appear in Tailscale 1.20.0.
