### ISSUE TITLE
Switching tabs closes some dialogs in the single machine page

### ISSUE THREAD

**Issue by sonovawolf** [tailscale/tailscale#3613]
### What is the issue?

Switching browser tabs closes some dialogs—not _all_ dialogs, _Edit machine name_ seems immune—_only_ in the single machine page (not in the table view).

**Comment by DentonGentry** [comment]
I think we fixed this somewhere along the way. In a single machine page I can open the Edit Route Settings or Edit ACL Tags dialogs, switch to a different tab, and they do not get closed.

Barring further comment, we'll expect to close this during the next regular bug scrub.
