### ISSUE TITLE
FR: Website admin interface should show IPv6 addresses by default when `disableIPv4` is true.

### ISSUE THREAD

**Issue by PaulMcMillan** [tailscale/tailscale#3615]
### What is the issue?

When I set `disableIPv4`, I expect the website admin interface to show me IPv6 addresses by default.

https://login.tailscale.com/admin/machines

I'm ambivalent about whether it also shows the IPv4 addresses (I understand they're still there, and I know some subset of my machines still have them until I restart the client), but I'd also like to see the v6 addresses by default, rather than having them hidden behind a mouseover menu.

### Bug report

BUG-55b0c13bbdb64a8c56de94d8f3690b61e21e348a40a976acb644739a7fb0bd41-20211224051458Z-9fb382d2c3ac9ef9

Related: #1381

**Comment by bradfitz** [comment]
Fixed, but not yet deployed. Probably live later today.
