### ISSUE TITLE
FR: Support IPv4 subnet routes even when `disableIPv4` is true

### ISSUE THREAD

**Issue by PaulMcMillan** [tailscale/tailscale#3616]
### What are you trying to do?

This is a bit of a tricky one.

I need to use `disableIPv4` to prevent Tailscale's 100.64/10 addresses from conflicting with existing CGNAT in other networks I access. I'm happy to use Tailscale's IPv6 addresses for talking to devices running Tailscale.

However, I also desire the ability to use tailscale to route IPv4 subnets.

Experimentally, v4 subnet routing seems to stop working when I set `disableIPv4` to true. This isn't unreasonable, but I want to have my cake and eat it too!

### How should we solve this?

Can we route IPv4 subnets over Tailscale's IPv6 addressing scheme?

### What is the impact of not solving this?

I can't use both `disableIPv4` and IPv4 subnet routing at the same time.

Subnet routing is a killer feature (it's why I pay for a personal account), so I'll probably go back to `disableIPv4: false` and manually stopping Tailscale when I access a network with conflicting CGNAT addresses.

Related: #1381

**Comment by DentonGentry** [comment]
I really don't see a way to do this in a reasonable way. If the node has no Tailscale IPv4 address, I don't see what we would put in the IP source address field of the packet we send to the subnet router.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by PaulMcMillan** [comment]
Yeah, I agree it's kinda a weird ask, and may not be technically feasible.

What about using one of the 6 to 4 mappings? I could probably live with using an IPv6 mapped address rather than the native IPv4 ones if the tailscale router node knew how to forward that traffic.

**Comment by normanr** [comment]
Is the plan to do IPv6-to-IPv4 at the "egress" site? Something like [tayga](http://www.litech.org/tayga/) (but built into `tailscaled`)?

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/826#issuecomment-1120251404 describes one such mechanism available now.

**Comment by normanr** [comment]
ahh, I wasn't obvious to me at first glace that #4330 also included the code to do the v6-to-v4 mapping (I thought it was only reserving the address space). It looks like netstack is doing _exactly_ what tayga could do, just integrated within tailscaled.

**Comment by DentonGentry** [comment]
I think this works; without an IPv4 address I don't know what else we could do. Barring further comment. we'll expect to close this during the next regular bug scrub.

**Comment by PaulMcMillan** [comment]
I'm going to go ahead and mark it as closed, #4330 looks like exactly what I needed here :)
