### ISSUE TITLE
Android: Blank Screen on Asus ZenPad Z8s

### ISSUE THREAD

**Issue by asjoyner** [tailscale/tailscale#3618]
### What is the issue?

Tailscale starts, but displays nothing.  I assume it is having difficulty rendering its user interface.  It seems similar to these previous issues: https://github.com/tailscale/tailscale/issues/471 https://github.com/tailscale/tailscale/issues/1008

(I will send the output of adb logcat to support@tailscale.com, and reference this bug number.)

### Steps to reproduce

1. Acquire an Azus ZenPad Z8s
2. Install Tailscale
3. Open the app
4. If you gaze for long into an abyss, the abyss gazes also into you.

### OS

Android

### OS version

7.0

### Tailscale version

1.18.0-t71f1dd5aa-g6e464cc68f9

**Comment by DentonGentry** [comment]
Presumably OpenGL ES version or hardware.

**Comment by eliasnaur** [comment]
Neither AWS Device Farm nor Firebase offers z8s in their test services. I wonder whether it runs Vulkan? For example, can https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer&hl=en&gl=US run on it? If so, perhaps https://github.com/tailscale/tailscale/issues/3973#issuecomment-1056774981 will work this device as well.

**Comment by DentonGentry** [comment]
We're expecting the 1.24 release for Android to disable vulkan.

**Comment by DentonGentry** [comment]
Fixed in 1.24.0, released yesterday.
