### ISSUE TITLE
FR: Taildrop should print progress after 1 second elapsed

### ISSUE THREAD

**Issue by riking** [tailscale/tailscale#3621]
### What are you trying to do?

There was a strange network path issue when I attempted to download a certain large file from home, so I downloaded it to a server and used `tailscale file cp` to move it to my computer.

The command provided no feedback and took several minutes to complete.

### How should we solve this?

After a certain amount of time has elapsed (1 second?), the command should stop being silent and print a progress report to the TTY.

The timer should probably start after the first byte has gotten an acknowledgement: high initial latency for small files is a separate diagnostic from simply being a large file transfer.

### What is the impact of not solving this?

User anxiety.

**Comment by Xalaxis** [comment]
I'd also like to suggest that the progress report includes an estimated time to complete as well.

**Comment by harupong** [comment]
I can confirm that this has been already implemented with the latest version of tailscale.

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
$ tailscale version
1.48.1
  tailscale commit: 528f95da6a5e12961b36a39bb3fa512c093d2330
  other commit: c4e4acad7220e23eb6f835e2b846c0378612d43a
  go version: go1.21.0
$ sudo tailscale file cp alpine-standard-3.18.3-aarch64.iso mypc:
alpine-standard-3.18.3-aarch64.iso  		197528/197528 kb	100.00%	1784 kb/s
```

It would be great if it could show ETA as well, but it's still far better than the command being silent.
