### ISSUE TITLE
 Major bug: the derper server reports an error after running for a period of time, and then each client transfers through derper

### ISSUE THREAD

**Issue by chenxudong2020** [tailscale/tailscale#3626]
### What is the issue?
After a period of time, the derper server cannot access HTTPS: / / my domain name
An error is reported in the background. Each client cannot transfer data through derper
![image](https://user-images.githubusercontent.com/61214170/147528959-ddfd81a1-91aa-4110-a1e9-1d1075d5310d.png)
Normal after restart:
![image](https://user-images.githubusercontent.com/61214170/147528985-8d8b2469-6820-4adf-bdcd-1f247dfefaca.png)
![image](https://user-images.githubusercontent.com/61214170/147529006-de80721f-8895-4e29-b993-10af1fd673ad.png)

### OS

Linux

### OS version

centos8.2

### Tailscale version

derper最新版通过go命令安装的deper服务

**Comment by DentonGentry** [comment]
This isn't really appropriate to handle as a public bug, please email support@tailscale.com.

As an initial guess if the derper works for a while and then stops working: possibly the Great Firewall.

**Comment by chenxudong2020** [comment]
> This isn't really appropriate to handle as a public bug, please email [support@tailscale.com](mailto:support@tailscale.com).
> 
> As an initial guess if the derper works for a while and then stops working: possibly the Great Firewall.
I have sent an email through QQ email
