### ISSUE TITLE
Can't ssh to other devices from Synology

### ISSUE THREAD

**Issue by rolisz** [tailscale/tailscale#3627]
### What is the issue?

If I try to ssh into other devices on my Tailscale network from my Synology NAS I get a Connection timed out

```
ssh pi@100.84.160.119
ssh: connect to host 100.84.160.119 port 22: Connection timed out
```
But a tailscale ping works fine:

```
sudo tailscale ping raspberrypi
pong from raspberrypi (100.84.160.119) via DERP(fra) in 88ms
pong from raspberrypi (100.84.160.119) via DERP(fra) in 71ms
pong from raspberrypi (100.84.160.119) via DERP(fra) in 73ms
pong from raspberrypi (100.84.160.119) via 82.76.29.163:41641 in 9ms
```

### OS

Synology

### OS version

Synology DSM 7

### Tailscale version

1.18.2

### Bug report

BUG-fe812c2c9b4669d2ba51534d4b8b25ea875f2c080d958d5e53b3ebd1d703cc3c-20211228080837Z-c5d06f2f94ecec1e

**Comment by DentonGentry** [comment]
Is this a new device, or recently upgraded to DSM7?

If so, could you check the steps in https://tailscale.com/kb/1152/synology-outbound/ ?

**Comment by rolisz** [comment]
It was recently upgraded to DSM7. That link solved it, thanks!
