### ISSUE TITLE
Can the derper server use custom certificates on port 443

### ISSUE THREAD

**Issue by chenxudong2020** [tailscale/tailscale#3635]
### What is the issue?

derper服务器在443端口能否使用 自定义证书 

设置发现443端口 默认使用了LetsEncrypt 使用 certmode manual 无效

这样443端口 使用LetsEncrypt  在中国被干扰 请修改 能在此端口使用自定义证书

Can the derper server use custom certificates on port 443
Setting discovery port 443 uses letsencrypt by default. Using certmode manual is invalid
In this way, the use of letsencrypt on port 443 is disturbed in China. Please modify the user-defined certificate that can be used on this port

### OS

Linux

### OS version

centos8.2

**Comment by DentonGentry** [comment]
Custom certificate support was added in https://github.com/tailscale/tailscale/issues/2794
