### ISSUE TITLE
Chromecast configuration apparently blocked by having Tailscale active on Android phone

### ISSUE THREAD

**Issue by davewsmith** [tailscale/tailscale#3636]
### What is the issue?

After factory reseting a first-gen Chromecast, the Google Home app will discover the Chromecast and will apparently connect to the Chromecast's private Wifi, but with the Tailscale app enabled, configuration is blocked. Disabling the Tailscale app, and restarting the config process via the Google Home app, configures the Chromecast successfully.

I suspect that this is a "nothing we can do on our side, just document it" problem.

### Steps to reproduce

As above

### Are there any recent changes that introduced the issue?

None

### OS

Android

### OS version

Latest Android, fully updated

### Tailscale version

1.18.0

### Bug report

BUG-aa06267126fb1b7af83dc9a50343ae5e58056d753fea5c5c774f209ee3503cea-20211229180910Z-da45c1d9e0c4cd20

**Comment by sailorfrag** [comment]
Another example of the Android client interacting poorly with Google apps is #3460. Perhaps they have the same root cause related to discovery when a VPN app is active? This might be outside our control but it would be nice to address.

**Comment by DentonGentry** [comment]
@askeuhd please file a separate bug, the Windows issue is not likely related.

**Comment by DentonGentry** [comment]
We added a number of Android apps which need to always probe the local LAN in https://github.com/tailscale/tailscale-android/pull/53

We could add the Google Home app as well, if we can identify its app signature.

**Comment by sailorfrag** [comment]
It's `com.google.android.apps.chromecast.app` https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app
