### ISSUE TITLE
Not able to renew expired TLS certificate

### ISSUE THREAD

**Issue by LouisFaure** [tailscale/tailscale#3640]
### What is the issue?

Accessing my devices via https lead to a security warning from browsers (Firefox: SEC_ERROR_EXPIRED_CERTIFICATE), even after renwal, am I missing something? Also, shouldn't certificates be automatically requested for renewal within the weeks before its expiry?

### Steps to reproduce

Access a page on the concerned machine via https using domain name provided by tailscale.

### Are there any recent changes that introduced the issue?

My certificates expired on 29/12/2021, so I attempted to renew these using `sudo tailscale cert` on the concerned machine, which updated both `.crt` and `.key` files. But I am still encountering the expired certificate issue.

### OS

Linux

### OS version
Ubuntu 20.04

### Tailscale version

1.18.2

**Comment by DentonGentry** [comment]
The `tailscale cert` command places the new key and crt files in the current directory, but this is almost certainly not where the files need to be to work with the software which is using them. It sounds like three months ago you have moved the files into place, and the old files are still there while the new files are in the current directory.

**Comment by LouisFaure** [comment]
I have checked more in detail and while crt and key files where still renewed at the same location, I realized that I had to restart nginx to take in account these new files. Apologies for my oversight of how nginx works!
