### ISSUE TITLE
FR: Tailscale for Chromebook without SSO

### ISSUE THREAD

**Issue by ericlagergren** [tailscale/tailscale#3642]
### What are you trying to do?

Add Tailscale to my wife's Chromebook without using SSO and without enabling developer mode (to use Linux directly).

The back story is I needed to transfer some files to my wife's Chromebook and I figured Taildrop would be easier and more secure than e-mailing the files. However, signing into my Google account on her Chromebook isn't straightforward (I'd have to configure my 1Password on the Chromebook then go and buy a dongle to be able to plug in my security key for 2FA).

### How should we solve this?

Allow authentication using the device authentication flow (e.g., an auth URL or auth key) like you can on Linux or macOS (via the CLI).

### What is the impact of not solving this?

I had to e-mail the documents 😞

**Comment by bradfitz** [comment]
Seems like dup of #675 

We have another bug too about just adding a QR code option to the login page so can finish from your phone. That's what I effectively did for the Amazon Fire Stick bug.
