### ISSUE TITLE
FR: Show transfer speed on Taildrop

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#3645]
### What are you trying to do?

Transferring a file using Taildrop shows a progress bar, but it's be nice to be able to see the transfer speed too.

### How should we solve this?

Show a transfer speed next to the progress bar.

### What is the impact of not solving this?

Sending a large file, say 2GB, doesn't explain how long it might take. It has been a little over 20 minutes since I started sending the file, but it hasn't completed yet. About 70% done. So, having a transfer speed shown may give me a better idea of how long the source device has to remain available.

**Comment by DentonGentry** [comment]
Covering this in https://github.com/tailscale/tailscale/issues/3621
