### ISSUE TITLE
FR: Use IPs instead of domain names for custom DERP server?

### ISSUE THREAD

**Issue by tranqkhue** [tailscale/tailscale#3647]
### What are you trying to do?

Hello all, many thanks for reading
Recently I have been trying to deploy a custom DERP server. However, it seems like Tailscale requires the custom server to be linked to a domain with TLS certification. If I only use the IP, this error would happen
```
sudo ./derper -stun
2022/01/02 17:41:46 no config path specified; using /var/lib/derper/derper.key
2022/01/02 17:41:46 derper: serving on :443 with TLS
2022/01/02 17:41:46 running STUN server on [::]:3478
2022/01/02 17:41:48 http: TLS handshake error from xxx.xxx.xxx.xxx:26228: acme/autocert: missing server name
```

### How should we solve this?

Maybe just using IP for a custom DERP server. It seems like for ZeroTier, we could do that.

**Comment by DentonGentry** [comment]
DERP carries traffic via TLS (aka HTTPS). The error means that your TLS certificate doesn't list the IP address given as one of its valid names. It only lists FQDN domain names.

It actually is possible to get a certificate issued for a raw IP address. Let's Encrypt won't do so, but there are certificate authorities which will. The derper supplied by Tailscale always uses Let's Encrypt but has a way to manually supply your own certificates.

So: if you get a certificate which will work with raw IP addresses, I think this will work.

I'm going to close this feature request, we're not going to put effort into making it automatic.

**Comment by bradfitz** [comment]
LetsEncrypt makes it not worth the effort, but what we could do in the future if needed is make derper auto-generate its own self-signed TLS cert and then let you put that cert signature in the derpmap to be distributed to all peers to use for validation, rather than the root CAs.

**Comment by tranqkhue** [comment]
Many thanks for clarifying this :D

**Comment by wwqgtxx** [comment]
> LetsEncrypt makes it not worth the effort, but what we could do in the future if needed is make derper auto-generate its own self-signed TLS cert and then let you put that cert signature in the derpmap to be distributed to all peers to use for validation, rather than the root CAs.

Any process of `self-signed TLS cert` and `the cert signature in the derpmap`?

In some specific regions (such as mainland China), when using TLS links with SNI headers, IPs within the territory need to register the domain name in SNI with the government department, otherwise the TLS connection will be blocked, as in https://github.com/tailscale/tailscale/issues/4082 . 

The easiest solution to this problem is to use a self-signed certificate and initiate a TLS connection without the SNI header. This can greatly simplify the deployment of custom DERPs within specific regions.

**Comment by DentonGentry** [comment]
We would review a pull request which adds this support. I do not expect us to work on implementing it in-house any time soon.

If we do start work on it, I promise we will update relevant issues. Do not poll for status in the meantime.

**Comment by PatrickHuang888** [comment]
I have noticed derper has certMode 'manual' now, which can use self-signed certification, and I used it successful

**Comment by itsalongstory** [comment]
> I set up a derper server without hostname domain following this tutorial: https://blog.handsomehans.uk/Tailscale-bu-xu-yao-yu-ming-he-SSL-zheng-shu--zi-jian-DERP-zhong-ji-fu-wu

```
"InsecureForTests": true, // 😰😰😰
```

**Comment by yqs112358** [comment]
For custom derper servers with self-signed certificates, it seems to be a convenient way to set `"InsecureForTests": true` in derp map file. 
Is there any security risk to do so? Or, is there a better way to skip certificate validation for custom derper servers?

**Comment by bradfitz** [comment]
See https://github.com/tailscale/tailscale/issues/11776 for the latest updates on all this.
