### ISSUE TITLE
Feature: support Apple TV (tvOS)

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3655]
From https://www.reddit.com/r/Tailscale/comments/rv4j6d/appletv/

> Is there any plan to port it to TVOS (AppleTV)?

And comment: 

> will cool that could use Apple TV as exit node. :)

Yes, that would be cool.

/cc @nickoneill @crawshaw

**Comment by nickoneill** [comment]
tvOS doesn't support network extensions or VPN at all currently! Maybe in the future if Apple provides some alternative ways for content providers to verify location, i imagine they've intentionally omitted it for regional content detection.

**Comment by bradfitz** [comment]
&lt;sad-trombone/&gt;

Okay, thanks for researching. Will close this for now.

**Comment by agottardo** [comment]
This is now being tracked in https://github.com/tailscale/tailscale/issues/8282
