### ISSUE TITLE
MagicDNS does not work in IPv6 only mode

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#3660]
### What is the issue?

When IPv4 is disabled, there is no mechanism for a host to contact 100.100.100.100 for MagicDNS resolution. 

### Steps to reproduce

Set  `"disableipv4": true,` in ACL
tailscale device automatically sets nameservers to auto-discover ({fec0:0:0:ffff::1, fec0:0:0:ffff::2, fec0:0:0:ffff::3})
tailscale sets a route to 100.100.100.100 for MagicDNS, but that fails because there's no IPv4 address on that interface
Cannot access tailnet computers by machine name. 
tailscale will still resolve machine names - `tailscale ping mymachine` works but `ping mymachine` does not

**Comment by bradfitz** [comment]
This is mostly a problem on Windows.

On all platforms, we unconditionally add a 100.100.100.100/32 route for MagicDNS (there is no Tailscale Service IP for IPv6 yet) and then the Windows router code that programs the interface addresses/routes fails on seeing a v4 route without a v4 address and bails out early before programming anything.
