### ISSUE TITLE
macOS: Tailscale cert returns 500 failed to get cert dir

### ISSUE THREAD

**Issue by jeffreylo** [tailscale/tailscale#3667]
### What is the issue?

**What happened?**

Running the following returns a 500 due to a missing cert dir:

```
λ /Applications/Tailscale.app/Contents/MacOS/Tailscale cert ****.tailnet-****.ts.net
2022/01/05 21:06:33 HTTP 500 Internal Server Error: failed to get cert dir
 (expected 200)
```

**What did you expect to happen?**

Retrieve a cert for Tailscale-enabled HTTPS.

### Steps to reproduce

Using Tailscale@1.18.2 and macOS@12.0.1 (21A559):

```
DOMAIN=****.****.ts.net
# fails on no cert dir
/Applications/Tailscale.app/Contents/MacOS/Tailscale cert $DOMAIN
# retry with sudo also fails
sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale cert $DOMAIN
```

### Are there any recent changes that introduced the issue?

No recent changes.

### OS

macOS

### OS version

macOS Monterey 12.0.1 (21A559)

### Tailscale version

1.18.2

### Bug report

BUG-9d45f0cd1a15c902190867c2cbc427cd90d059d5275ca9d758a03a0c91e3a575-20220106021034Z-ca91377e71f694d6

**Comment by rgaudin** [comment]
Same here

``` sh
/Applications/Tailscale.app/Contents/MacOS/Tailscale cert ***.***.ts.net
2022/01/06 10:01:20 HTTP 500 Internal Server Error: failed to get cert dir
 (expected 200)
```

Trying with sudo:

``` sh
sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale cert ***.***.ts.net
Password:
2022/01/06 10:01:30 Get "http://local-tailscaled.sock/localapi/v0/cert/***.***.ts.net?type=pair": safesocket: failed to connect to /var/run/tailscaled.socket: dial unix /var/run/tailscaled.socket: connect: no such file or directory; failed to connect to Tailscale IPNExtension: no sameuserproof token found in TS_MACOS_CLI_SHARED_DIR "/private/var/root/Library/Group Containers/W5364U7YZB.group.io.tailscale.ipn.macos"
```

There's no tailscale socket in `/var/run`. It actually looks like the macOS app is not starting a *regular* tailscaled with a socket so everything inside the UI works but the CLI tools, such as the web iface don't.

**Comment by bradfitz** [comment]
Thanks. This will be in our next release.
