### ISSUE TITLE
FR: Force a server to be quarantined

### ISSUE THREAD

**Issue by renchap** [tailscale/tailscale#3673]
### What are you trying to do?

My use-case : one server is shared with multiple users, not using Tailscale (ssh login allowed over public internet).

I would like this server to join my Tailnet, but only for me to be able to connect to it using Tailscale, not allowing the other users of this server to connect to the other devices in my tailnet.

All other devices in my tailnet should still be allowed to connect to each other.

### How should we solve this?

Allowing to manually quarantine this server would allow me to do this.

With ACLs, I dont see a way to do it while allowing the other devices to connect to each other (except by assigning specific tags to each device, which would be burdensome).

### What is the impact of not solving this?

My current workaround is to not join this server to my tailnet, and SSH to it from a server that only I have access to and is in the tailnet.
But I would like to have services running on this shared server and being able to access them from the tailnet and currently it involves port-forwarding, which is a pain.

### Anything else?

This is related to #3352, but this one is closed and I was asked to open a new one :)

**Comment by danderson** [comment]
You can do this with ACL tags. Add --advertise-tags=tag:quarantine to your tailscale up command. That will make the logged-in identity of the server tag:quarantine instead of your human identity, and you can then write ACLs that work with this, e.g. allowing renchap@whatever.com to connect to tag:quarantine:*, but not allow tag:quarantine to connect to anything.

See https://tailscale.com/kb/1068/acl-tags/ and https://tailscale.com/kb/1018/acls/ for more details on combining tags and ACLs to achieve what you want.

**Comment by renchap** [comment]
@danderson Thanks, I completely missed those ACL tags!

So it would require an ACL policy like this:
```
// Example/default ACLs for unrestricted connections.
{
  // Declare static groups of users beyond those in the identity service.
  "groups": {
    "group:admin": [ "renchap@github" ],
    "group:humans": [ "renchap@github", "other@github" ]
  },
  // Declare convenient hostname aliases to use in place of IP addresses.
  "hosts": {
  },
  // Access control lists.
  "acls": [
    // Match absolutely everything. Comment out this section if you want
    // to define specific ACL restrictions.
    { "action": "accept", "users": ["group:humans"], "ports": ["*:*"] },
  ],
  "tagOwners": {
    "tag:shared-server": [
      "group:admin"
    ]
  }
}
```

The only drawback I can see is that you need to add all users to `group:humans`, as using `users: ["*" ]` will also allow the shared server, and there is no autogroup for all human identities.

Quarantining the node allows this without listing all human users.

**Comment by renchap** [comment]
Also it looks like ACL tags can not be used as `users` in tests:

```
  "tests": [
    {
      "user": "tag:shared-server",
      "allow": ["100.100.100.100:22"],
    },
  ]
```

makes an error when

**Comment by bradfitz** [comment]
So can we close this bug?

ACL tests for tags is tricky and is probably worth its own bug if you want to file that. I'd prefer to not reuse this bug for that, as it makes the bug history hard to read.

**Comment by DentonGentry** [comment]
ETIMEDOUT. Feel free to open a new bug about the tests.
