### ISSUE TITLE
FR: set machine name from the cli

### ISSUE THREAD

**Issue by dfcarney** [tailscale/tailscale#3679]
### What are you trying to do?

Would like ability to set/override the machine name from the cli.

**Comment by DentonGentry** [comment]
`tailscale up --hostname=name`
is one way to do this, would that suffice?

**Comment by dfcarney** [comment]
It should. Honestly, I should have checked https://tailscale.com/kb/1080/cli/ before I filed this for a customer. I'll confirm with them and circle back.

**Comment by SamuelNorbury** [comment]
> `tailscale up --hostname=name` is one way to do this, would that suffice?

This would be perfect!
