### ISSUE TITLE
Single-label queries are sent to split DNS as FQDN queries

### ISSUE THREAD

**Issue by neic** [tailscale/tailscale#3683]
### What is the issue?

I have setup a split DNS server. When I make single-label queries that don't match MagicDNS, they are sent to the split DNS server as FQDN queries. 

My DNS server it setup to respond to a wildcard of all subdomains of the domain. This results in _all_ single-label queries being answered regardless if they are valid.

I would expect the server configured as split DNS to either:
- not receive single-label queries at all or
- receive them as only single-label queries, not transformed into FQDN queries.

I think this is related to #1667, but if this is a duplicate I don't think the conclusion is correct. In a setup with only MagicDNS and no split DNS, it works as expected. A single-label query for a something that is not a Tailscale machine returns an empty response correctly. That indicates there is some mechanism with a distinction between search domains and routing domains.

### Steps to reproduce

With 
- a tailscale machine called `machine`,
- MagicDNS enabled
- a split DNS server setup for `example.com` and
- `1.1.1.1` configured as a global nameserver.

The split DNS server runs `dnsmasq` with the configuration `address=/*.example.com/100.101.102.103`.

All queries are run from another machine running macOS.

```sh
# Correctly handled by the global nameserver
dscacheutil -q host -a name tailscale.com
name: tailscale.com
ipv6_address: 2606:4700::6810:f34e
ipv6_address: 2606:4700::6810:f44e

name: tailscale.com
ip_address: 104.16.244.78
ip_address: 104.16.243.78

# Correctly handled by the split DNS server
$ dscacheutil -q host -a name machine.example.com                                                                                                                                      
name: machine.example.com
ip_address: 100.101.102.103

# Correctly handled by MagicDNS
$ dscacheutil -q host -a name machine
name: machine.example.com.beta.tailscale.net
ip_address: 100.101.102.103

# Incorrectly assumed to a valid single-label query and sent to the Split DNS as a garbage.example.com query
$ dscacheutil -q host -a name garbage
name: garbage.example.com
ip_address: 100.101.102.103

# Handled by the split DNS server as expected even if nonsense.
$ dscacheutil -q host -a name garbage.example.com
name: garbage.example.com
ip_address: 100.101.102.103
```

### OS

macOS

### OS version

macOS 10.15.7

### Tailscale version

1.18.2

**Comment by danderson** [comment]
That's just how DNS works. DNS servers never receive single-label queries, they're expanded by the client resolver into FQDNs using the search paths, and sent to DNS servers as FQDNs.

**Comment by neic** [comment]
Ok. That makes sense. It would leave out the "receive them as only single-label queries, not transformed into FQDN queries"-solution.

It should still be possible to not forward the query. Similar to if only MagicDNS is enabled. Or am I missing something?

**Comment by bradfitz** [comment]
Not forward which query? Got a concrete minimal example?

**Comment by neic** [comment]
> Not forward which query? Got a concrete minimal example?
Yes,
```sh
# With only MagicDNS
$ dscacheutil -q host -a name garbage
# No result as expected

# With MagicDNS and Split DNS.
$ dscacheutil -q host -a name garbage
name: garbage.example.com
ip_address: 100.101.102.103
# Result answered by my DNS server. It's received by the server as garbage.example.com.
```
I do not expect the last query to my DNS server.

I'm sorry if it is not clear what I try to achieve.

**Comment by DentonGentry** [comment]
ETIMEDOUT. Nothing further.
