### ISSUE TITLE
admin: DNS nameserver drag-and-drop doesn't work

### ISSUE THREAD

**Issue by zombiezen** [tailscale/tailscale#3684]
### What is the issue?

I can't reorder the nameservers: they snap back into the same place after I drop them. Browsing in web inspector seems to indicate that the resulting `POST https://login.tailscale.com/admin/api/dns` request is not attempting to change the order at all.

### Steps to reproduce

1. Go to https://login.tailscale.com/admin/dns
2. Drag DNS entries around Global Nameservers

### OS

Windows

### OS version

Windows 10, Chrome 96.0.4664.110

**Comment by DentonGentry** [comment]
The order of the nameservers has no functional impact, so the admin panel doesn't set the ordering.

When the MagicDNS server at 100.100.100.100 (which is actually running in your local tailscaled) needs to recursively resolve a DNS name, it:
1. Combines all DNS server aliases into buckets. For example, 8.8.8.8 and 8.8.4.4 are combined into a bucket.
2. Sends queries to each eligible bucket in parallel. It does not walk through them one by one in order.

**Comment by zombiezen** [comment]
Makes sense, but the UX confused me a little. Feel free to close as WAI.

**Comment by bradfitz** [comment]
Assigning to @rosszurowski to decide what to do here. Ross, why can they be reordered?

**Comment by rosszurowski** [comment]
Looks like this is a bug with our UI that crept in somewhere. I'll take a look.

**Comment by rosszurowski** [comment]
This was an oversight in our re-ordering logic. A fix should be live with our next deploy of the control server. Thanks for reporting!

**Comment by DentonGentry** [comment]
Fix deployed a couple days ago.
