### ISSUE TITLE
Android VPN Toggle Widget

### ISSUE THREAD

**Issue by essteewhy** [tailscale/tailscale#3689]
Would love to see an Android widget for Tailscale app to toggle the VPN on/off

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2646

**Comment by Chaz6** [comment]
I do not think that this is a duplicate of #2646. That issue seems to be about the quick settings tile. I too would like a proper widget on the home screen.

**Comment by ryanwwest** [comment]
I agree, this is not a quick settings tile and should be reopened.

**Comment by olderbag** [comment]
Still waiting for reopening...

**Comment by xStrat0S** [comment]
Would love to see this too

**Comment by piratatijuanero** [comment]
Would really like to see this

**Comment by v4ng3n** [comment]
+1

**Comment by eeshaan** [comment]
+1

**Comment by alexfornuto** [comment]
@DentonGentry please consider reopening this.

**Comment by oreze** [comment]
Would love that feature
