### ISSUE TITLE
WSL resolv.conf issues with tailscale status change

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#3690]
### What is the issue?

Disconnecting/Reconnecting to tailscale crashes WSL Ubuntu and deletes resolv.conf 

### Steps to reproduce

New install of wsl ubuntu 20.04.

```
jay@Nautilus:~$ cat /etc/resolv.conf                                                                                    
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:                                                                                                            
# [network]                                                                                                             
# generateResolvConf = false                                                                                            
nameserver 172.17.32.1   
```
On the Windows system: Disconnect/Reconnect to tailscale.

```
jay@Nautilus:~$ cat /etc/resolv.conf
cat: /etc/resolv.conf: No such file or directory
jay@Nautilus:~$ sudo touch /etc/resolv.conf
jay@Nautilus:~$
```
On the Windows system: Disconnect/Reconnect to tailscale.

```
jay@Nautilus:~$ cat /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search corp.ts.net tailscale.com.beta.tailscale.net ts.tailscale.com ts-dns.test
```

After rebooting, resolv.conf disappears again, and must be manually created or touched before tailscale will set nameservers. 

### OS

Windows

### OS version

wsl Ubuntu 20.04 on Windows 11

### Tailscale version

1.19.180

**Comment by JayWStapleton** [comment]
Behaviour is also observed in 1.18.2
1.16.2 does not have this bug.

**Comment by dblohm7** [comment]
These symptoms might also have been masked because of https://github.com/tailscale/tailscale/issues/3437 -- once that was fixed, it probably opened the floodgates with respect of triggering the code in question.

**Comment by voltagex** [comment]
As I mentioned in the other bug on this, I don't think Tailscale should be touching things it doesn't own - at least not without asking first.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/commit/a14d445fc7220c7c827a93a8a8c4970b45cf449c means that resolv.conf will only be written if a TS_DEBUG_CONFIGURE_WSL environment variable exists. I'm going to close this issue as resolved.
