### ISSUE TITLE
1.19.180 MSI Build fails on uninstall

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#3691]
### What is the issue?

When uninstalling 1.19.180 MSI, it hangs on "Gathering Required Information" This window pops under:

![image](https://user-images.githubusercontent.com/95231559/148788645-740c8f0e-8980-4991-b9b2-53e8708bc38f.png)

### Steps to reproduce

Uninstall 1.19.180

### OS

Windows

### Tailscale version

1.19.180

**Comment by dblohm7** [comment]
That's...  really strange, in the sense that the Windows Installer should have automatically elevated us. I'll circle back around to this in a bit.

**Comment by JayWStapleton** [comment]
Uninstalling by right-clicking the MSI and selecting uninstall works. Uninstalling from Apps & Features does not.

**Comment by dblohm7** [comment]
@JayWStapleton if you get a chance, can you try reproducing by initiating the uninstall via the command line?
`msiexec /log path_to_log.log /x path_to_msi.msi`

**Comment by JayWStapleton** [comment]
It worked with that command. 
[uninst.log](https://github.com/tailscale/tailscale/files/7981888/uninst.log)

It also uninstalls properly from Apps & Features now.

**Comment by dblohm7** [comment]
Okay. I'm going to close this for now, but feel free to reopen with a log if you see it again. I also added info about `msiexec` to the support section in Notion.
