### ISSUE TITLE
RedHat EL9 Repository

### ISSUE THREAD

**Issue by ooraini** [tailscale/tailscale#3699]
Currently, the [download page](https://tailscale.com/download/linux/centos-8) only has CentOS 7 and 8. Stream 9 was release last month. I have tested the EL8 package with Stream 9 and it works just fine.

EL 8:
`https://pkgs.tailscale.com/stable/centos/8/x86_64/repodata/repomd.xml`

EL9(404 not found):
`https://pkgs.tailscale.com/stable/centos/9/x86_64/repodata/repomd.xml`

Looking at the `deplist tailscale`:
```
package: tailscale-1.18.2-1.x86_64
  dependency: iproute
   provider: iproute-5.13.0-5.el9.x86_64
  dependency: iptables
   provider: iptables-nft-1.8.7-26.el9.x86_64
   provider: iptables-legacy-1.8.7-26.el9.1.x86_64
```

I only have the `nft` package of iptables installed. No issues so far.

**Comment by DentonGentry** [comment]
Fixed 1/26 by Xe.
https://pkgs.tailscale.com/stable/centos/9/x86_64/repodata/repomd.xml exists now.
