### ISSUE TITLE
Add builds for other GOOSes to CI

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#37]
CI currently builds GOOS=linux. We should build other platforms, just to make sure we don't let syntax errors and other obvious compile failures rot in the repo.

GOOS=darwin and GOOS=windows don't produce useful binaries, but we can at least check that the packages compile.

We're likely to have GOOS=openbsd and GOOS=freebsd soonish.

**Comment by bradfitz** [comment]
I'd also like to cross-compile all the tests for other geese (even if we can't run them), but we can't easily (I opened https://github.com/golang/go/issues/15513 about 4 years ago)

So we'll need a bit of shell or helper program to enumerate all packages and `GOOS=foobsd go test -c` each package one by one.

**Comment by evalexpr** [comment]
@danderson can probably close this now, though adding a build to linux.yml for openbsd wouldn't be a terrible idea either?

**Comment by danderson** [comment]
@bradfitz is adjusting the cross-goose builds now to parallelize harder, and will add an openbsd build as part of that. I'll let him close this issue with his commit.

Thanks for getting cross-builds setup! It caused us to fix 2 builds right out the door, very much appreciated :)
