### ISSUE TITLE
--advertise-routes only takes CIDRs

### ISSUE THREAD

**Issue by ShantanuNair** [tailscale/tailscale#370]
Issue is with the --advertise-routes option. Eg: `tailscale up --advertise-routes=8.8.8.8,8.8.4.4`
I'm not sure if it's the documentation that's gone out of date here - [Connecting to external services with IP block lists via Tailscale](https://tailscale.com/kb/1059/ip-blocklist-relays?q=aws), or if the --advertise-routes option is supposed to be able to take individual IPs.

**Expected behavior**
IPs can be advertised, and not just CIDRs

**Current Behavior**
> $ "8.8.8.8" is not a valid CIDR prefix: invalid CIDR address: 8.8.8.8

**Comment by danderson** [comment]
Arguably it's a documentation error, because we only support CIDR prefixes. You can pass 8.8.8.8/32 to route a single IP.

That said, it's an easy change to allow bare IPs as well, so I'll go do that.

**Comment by ShantanuNair** [comment]
@danderson Thanks! On a related note, is there any way to list what routes are being advertised by a relay either via the admin dashboard or via the tailscale command on the relay?
