### ISSUE TITLE
Derper Selfsigned cert?

### ISSUE THREAD

**Issue by dragon2611** [tailscale/tailscale#3701]
### What is the issue?

It's finding the key/cert as if they're not there I get a different error but it seems derper doesn't like them for some reason
originally had a 4096 bit key but retried with a 2048 bit.

openssl req -x509 -newkey rsa:2096 -keyout key.key -out cert.pem -sha256 -days 3650 -nodes

docker run -d \
--name derp \
--restart=always \
-p 10443:443 \
-p 3478:3478/tcp \
-p 3478:3478/udp \
-v /dockerpersist//derp/cert.pem:/cert/intderp.dragon2611.net.crt \
-v /dockerpersist/derp/key.key:/cert/intderp.dragon2611.net.key \
e45d9ab0391e

2022/01/11 12:22:33 no config path specified; using /var/lib/derper/derper.key
2022/01/11 12:22:33 derper: serving on :443 with TLS
2022/01/11 12:22:33 running STUN server on [::]:3478
2022/01/11 12:22:33 derper: can not start cert provider: refuse to load cert: hostname mismatch with key

CMD /app/derper -hostname intderp.dragon2611.net -certmode manual -certdir /cert -stun

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            14:3e:bf:fa:14:06:e4:b7:72:36:6e:93:09:8c:f4:f6:ae:a6:87:1b
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = intderp.dragon2611.net
        Validity
            Not Before: Jan 11 12:22:23 2022 GMT
            Not After : Jan  9 12:22:23 2032 GMT
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = intderp.dragon2611.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2096 bit)

### Steps to reproduce

Start derper with selfsigned cert.

### OS

Linux

Edit: Noticed they keysize error above, regenerated with 2048 and no difference.

**Comment by bradfitz** [comment]
IIRC, you need DNS alternative names set in your cert. It doesn't look like you set any name for your cert?

I sent https://github.com/tailscale/tailscale/pull/3703 to improve the error message that it's failing with, to give you more information.

In any case, once you get past this, the next problem you'll hit is that the tailscaled binary will fail to validate the connections since it's self-signed. It has no way to add alternate trust roots. Or are you adding your custom CA's roots to your client machines yourself?

**Comment by dragon2611** [comment]
Let me try the DNS alt name and see if I can get it running, then i'll look into that.

Ideally everything would direct connect but the chromebook is stubbonly refusing to, if it wernt for the fact the iphone on the same VLAN is with both IPv4 and IPv6 Id assume a firewall issue.

**Comment by bradfitz** [comment]
Update your derper binary and you'll get a better error message now.

**Comment by dragon2611** [comment]
Thanks is   "InsecureForTests" : true a vaild ACL option, the sourcecode comments seemed to suggest so.

**Comment by dragon2611** [comment]
Either way I think the better approach was edit the init script on the Nas to make tailscale listen on a specifc port then it's easier to do the firewall rules for direct connections.

Was a learning experience playing with derp and I'm still glad I did, as it might come in handy at somepoint (If so I'll set one up with a proper cert)

**Comment by bradfitz** [comment]
InsecureForTests might go away in the future. It's really just for tests.

**Comment by dragon2611** [comment]
Yep, even with that set it didn't seem to want to connect anyway so maybe I messed something up.
Either way if i can get direct connect working without allowing All UDP traffic between vlans that's the better option ;-)

**Comment by bradfitz** [comment]
I'm going to close this now, as I don't think there's anything left to be done around self-signed certs now that the error message has been clarified.

You can set the UDP listen port with the port flag to tailscaled.
