### ISSUE TITLE
FR: Relay all traffic to a specific domain/IP address through an Exit Node, similar to Split-DNS

### ISSUE THREAD

**Issue by jdgiddings** [tailscale/tailscale#3704]
### What are you trying to do?

I would like Tailscale to route all traffic destined for a specific domain/IP through an Exit Node, the way that Split-DNS works with DNS servers

I work in the healthcare technology sector, and some of the businesses we work with are not up-to-date with their security. Some of them have servers that are only accessible from our office's IP, the problem being that we are mostly a work from home company. This forces users to switch to an Exit Node located in our office to access these servers, then disable the exit node when they are done. This process works, but is very clunky. 

It would be nice if Tailscale could automatically capture traffic destined for a specific domain and route it through the Exit Node in our office so that employees don't have to worry about switching the Exit Node on and off

### How should we solve this?

This could be implemented similar to Split-DNS. A list of domains under an Exit Node. Here's a mock-up

![image](https://user-images.githubusercontent.com/79322633/148983140-f11ec743-ad8f-40af-8fe1-ba014aefcdad.png)

### What is the impact of not solving this?

The impact is not huge, but it would save users the trouble of switching an Exit Node on and off constantly, making the networking experience that much smoother

**Comment by bradfitz** [comment]
I thought we had a bug for this already but in a few quick searches I'm not finding it.

In any case, this is a frequent request and we've been moving towards making this possible. Some of the low-level bits are there now for a few releases but it's not entirely exposed yet.

The two main parts are:

1) fake DNS for, say, `healthcareservices.net` to point to `100.x.y.z`, and then
2) make `100.x.y.z` look at the SNI (or Host) headers in the port 443 or port 80 traffic and TCP proxy it to the target.

That only works for HTTP. There are fancier options for arbitrary protocols (e.g. allocating a Tailscale IPv6 address per relayed service)

The first part, the DNS stuff, the client can somewhat already do now. The HTTPS LetsEncrypt support added recently added support for the client to have arbitrary DNS record overrides. But it doesn't yet handle stuff like overriding `healthcareservices.net` but not `foo.net` or `bar.healthcareservices.net`.

For now we tell people to run their own DNS server over Tailscale and hard-code the records they want to override to another host, then use something like https://github.com/inetaf/tcpproxy to inspect the SNI headers and forward the TCP connections to the right place. In the future we'll probably build that into tailscaled.

**Comment by jdgiddings** [comment]
Apologies, didn't realize it was a common request. Feel free to close this issue if this is tracked somewhere else :)

**Comment by bradfitz** [comment]
Well, we'll keep this one open until/unless we find the other one. Maybe it was only in our private corp repo.

**Comment by bradfitz** [comment]
@DentonGentry found it: #1748
