### ISSUE TITLE
add mechanism for macOS users to set IPNExtension environment variables

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3707]
Like b03170b901b1bb89f815e589750a76ea4a2254bf did for  #3688, we should have the same for macOS GUI users.

**Comment by DentonGentry** [comment]
Progress in https://github.com/tailscale/tailscale/pull/5665

**Comment by reteps** [comment]
waiting on this! https://github.com/tailscale/tailscale/blob/main/envknob/envknob.go#L398
