### ISSUE TITLE
First request to subnet router routed IP fails after install

### ISSUE THREAD

**Issue by zenazn** [tailscale/tailscale#3708]
### What is the issue?

After installing Tailscale (by following the process at https://login.tailscale.com/start), three of my coworkers (Mac, Monterey, Tailscale 1.18.2) have been unable to make a TCP connection to a host (`10.131.224.x`) that sits behind a subnet router (`10.131.0.0/16`, Linux, Tailscale 1.18.2) immediately after install.

This only happens on initial install—if they disconnect and reconnect (2 of 3), or log out and back in (1 of 3), the connection works just fine. Trying the connection again doesn't work; only one of the actions in the previous sentence seem to work. I haven't had any reports of issues going forward after this initial install.

Possibly confounding factor: the DNS name they are using to connect uses Tailscale's split DNS feature, although I can tell from the error messages that they are seeing that they are correctly resolving the `10.131.224.x` IP.

### Steps to reproduce

Per above:
- Create new account on login.tailscale.com/start
- Download and install tailscale
- Attempt to connect to a host behind a subnet router

### OS

macOS

**Comment by bradfitz** [comment]
Is the subnet router running in userspace mode? What's its Tailscale IP?

**Comment by zenazn** [comment]
I believe so. We're specifically running a lightly modified version of https://github.com/render-examples/tailscale (modified to bump the version number). I believe [this is the relevant part](https://github.com/render-examples/tailscale/blob/159c5c044d8f28bda13f41a9f9d2c76d27312675/run-tailscale.sh#L3-L6).

The subnet router's IP is 100.75.129.77

**Comment by zenazn** [comment]
In case it's helpful, a fourth coworker (i.e., 4 of 4 folks who have tried the repro flow above; all running macos) reported the following:

```
1. Clicked “Test” connection in TablePlus a few times, didn’t work [ed: TablePlus is a postgres GUI]
2. Tried disconnect / connect as in the doc [ed: a troubleshooting doc I wrote that advised folks to try disconnecting / reconnecting]
3. Clicked “Test” again, didn’t work
4. Clicked “Connect”, didn’t work the first time
5. Clicked “Connect” again, it worked!
```

**Comment by bradfitz** [comment]
I think this is a dup of #2642 which we're actively debugging and is a top priority.

It's been improved and is much better since 1.18.x but we're still trying to understand it.

**Comment by zenazn** [comment]
Reading through that issue, it seems like a match. Anything I can do to help debug it?

**Comment by DentonGentry** [comment]
The root cause of https://github.com/tailscale/tailscale/issues/2642 has been identified as an issue in the userspace-networking implementation in dealing with ECN bits.

**Comment by bradfitz** [comment]
Can you try the 1.20.2 build? It has the ECN fix.

**Comment by zenazn** [comment]
Of course! I installed it on our subnet router, and will follow up with the coworkers who have run into issues. I'll report back in a week or so

**Comment by zenazn** [comment]
@bradfitz I think 1.20.2 fixes it—I haven't heard of any issues in the past week. Thank you so much! ✨
