### ISSUE TITLE
Using Tailscale 1.19.187 on an aarch64 Synology in Userspace Mode Doesn't Work as an Exit Node

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#3710]
### What is the issue?

I tried to use my synology as an exit node. It failed to let me search things on google. Changing to another exit node in my network let me confirm the outgoing IP address as well as search things on google.

### Steps to reproduce

1. Enable exit node on your synology
2. enable it as an exit node in the web panel
3. try to use it
4. internet traffic doesn't work

### OS

Synology

### OS version

Synology DSM 7

### Tailscale version

1.19.187

### Bug report

BUG-302bab5de9dd81635703607289caa4bebdcbce06ed44706f8f08886d0bbf24e2-20220111213157Z-2041ae85c824ff3f

**Comment by bradfitz** [comment]
I think this is sufficiently fixed now.
