### ISSUE TITLE
 Android to have the same features as windows client to toggle between different devices.

### ISSUE THREAD

**Issue by sontjer** [tailscale/tailscale#3712]
### What are you trying to do?

 I have two openwrt devices with different subnodes enabled. On windows client, it's pretty easy to toggle between them. The latest Android version offers a list of my devices, however, I cannot choose which one to connect to.  The only feature that I can do about the listed the devices is that I can copy the IP address.

### How should we solve this?

 Add a feature, like on windows on Mac OS  to let the users to toggle between different devices.

### What is the impact of not solving this?

Always stays connected on the first device that Android client used to connect to.

### Anything else?

 Should import the same features like on windows and Mac OS system.

**Comment by bradfitz** [comment]
I don't follow. Which part of the Mac/Win clients are you referring to?

**Comment by sontjer** [comment]
![mydevices to choose from](https://user-images.githubusercontent.com/43029800/149050535-ae50f96a-1b14-483c-ad5d-1235135f72a0.png)
Thanks for your rapid respond, this is what I referred to, on windows I can choose which of the following devices I want to connect to, so I can get access to specific subnet. But android appears doesnt have the feature so far.

**Comment by sontjer** [comment]
The following **openwrt-jy and openwrt-xh** already deployed different subnet, I hope to switch between them freely on Android device.

**Comment by DentonGentry** [comment]
That isn't what that UI does on Windows. In the following screenshot, my tailnet has nodes named terraria, ubuntu, unifi, and zoneminder. I have a web browser open connecting to the Tailscale address for zoneminder, so there is a Wireguard tunnel established to connect to it.

<img width="357" alt="Screen Shot 2022-01-11 at 6 17 33 PM" src="https://user-images.githubusercontent.com/1140756/149052075-37581f9c-400c-4da1-aee4-aab96abe7f1a.png">

I'm not actively connected to terraria, ubuntu, or unifi, so they don't have dots in the UI.

Then I connected to a service on the terraria node, and it got a dot for an active connection
<img width="266" alt="Screen Shot 2022-01-11 at 6 20 21 PM" src="https://user-images.githubusercontent.com/1140756/149052321-46a9eb28-76f7-4d89-b4bf-6d9523e3b699.png">

Selecting the node in the Windows UI copies its IP address to the clipboard, the same as what the Android client does.

**Comment by sontjer** [comment]
Yes, on winodws everthing works like a charm! This is what I need on Android devices. Only a list of connect devices, no way I can toggle between openwrt-xh and openwrt-jy...
![android1](https://user-images.githubusercontent.com/43029800/149053250-94eec0ef-0e23-4555-979b-06e100af6e9f.jpg)

**Comment by DentonGentry** [comment]
The Windows UI does NOT toggle between openwrt-xh and openwrt-jy.
All the Windows UI does is copy the IP address to the clipboard.

What happens when you select openwrt-jy in the Windows UI?

**Comment by sontjer** [comment]
> The Windows UI does NOT toggle between openwrt-xh and openwrt-jy. All the Windows UI does is copy the IP address to the clipboard.
> 
> What happens when you select openwrt-jy in the Windows UI?

Nope, everything works like a charm in Windows UI! I mean on Android verion, no way I can switch to different subnet or ‘openwrt-xh’  and 'openwrt-jy' subnodes which I created.

**Comment by DentonGentry** [comment]
Can you describe what happens when you select openwrt-xh in the Windows UI?
You believe it switches to subnets from openwrt-xh?

And when you select openwrt-jy, you believe it switches to using subnets from openwrt-jy?

openwrt-xh and openwrt-jy use `--advertise-routes`? Are they both exporting the same routes, like 192.168.0.0/24, but two different LANs using the same IP addresses?

**Comment by sontjer** [comment]
Thanks for heads-up! I already used 'use --advertise-routes' on both openwrt-xh and openwrt-jy, and their subnet doesn't overlap. Upon selection of openwrt-xh or openwrt-jy, subnets changes accordingly and correctly in the Windows 10 UI. My qustions is on Android verion, I CANNOT switch between them, there's literally NO function to let me do that. Hopefully I made myself clear already...

**Comment by bradfitz** [comment]
What we're telling you is that the Windows and macOS clients do not have code to even start to do what you think they do. The menu is purely wired up to copy their IP addresses to the clipboard. That's it. There's no subnet selection functionality anywhere in the GUIs.

**Comment by sontjer** [comment]
> What we're telling you is that the Windows and macOS clients do not have code to even start to do what you think they do. The menu is purely wired up to copy their IP addresses to the clipboard. That's it. There's no subnet selection functionality anywhere in the GUIs.

Thanks for reply, I got it. Anyway, really appreciate the ingenious work.
