### ISSUE TITLE
admin: editing ACL file should produce more specific error messages

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#3714]
### What is the issue?

When there is an error in the ACL editor, save fails in an unhelpful manner:
```An unknown error occurred while saving your file. Please copy your changes and try again later. If the error persists, please contact us for support.```

We should be able to surface a more helpful error.

**Comment by mayakacz** [comment]
I specifically experienced this this morning when I missed a comma. I don't think I've seen that before.

<img width="1103" alt="Screen Shot 2022-01-12 at 07 29 23" src="https://user-images.githubusercontent.com/15946341/149191805-01a97bbe-888e-4404-8c38-50e04b4386b3.png">

**Comment by jdgiddings** [comment]
I experienced this issue when I added a tag with a "_" or "-" in it

**Comment by soniaappasamy** [comment]
The fix for this has gone in https://github.com/tailscale/corp/commit/bad21025d7bcff1201b52a4548116be767b90588. We were dropping our errors due to an execption in our API interceptors logic. Will go live the next time the control server is deployed.
