### ISSUE TITLE
Support relaying a default route through Tailscale

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#372]
We support subnet routes. However, default routes fall prey to #144, so we can't relay all of a node's traffic through another node.

This is an obviously desirable feature, and we need to make it work. Filing this so we can track it in our user pain tracker, even though we can't fix it until #144 is done (which itself is blocked on #320 currently).

**Comment by apenwarr** [comment]
Whoops, I incorrectly claimed earlier that we hadn't filed this bug, but apparently we had, with a hard-to-find name: https://github.com/tailscale/tailscale/issues/102. I'll close this one as a duplicate.
