### ISSUE TITLE
Multiple tailscale network adapters in Control Panel 

### ISSUE THREAD

**Issue by alminisl** [tailscale/tailscale#3724]
### What is the issue?

When opening Control panel i saw multiple network adapters from tailscale. 37 to be correct. 

![image](https://user-images.githubusercontent.com/6343910/149317007-8367e412-2c31-4afb-9717-3e39e5b006ab.png)

Anyone has a idea why this happened? Is there a way to delete those? Because when I try right clicking on them I get a grayed out delete

![image](https://user-images.githubusercontent.com/6343910/149317110-751f71be-7c22-4e96-9f2f-5f69eb1c86db.png)
 
 
 Thanks! 

### Steps to reproduce

No idea

### Are there any recent changes that introduced the issue?

Not that I'm aware of. 

### OS

Windows

### OS version

Windows 11 - build 22000.434

### Tailscale version

1.14.4

**Comment by bradfitz** [comment]
That makes it go 37 times faster! 😂 

Does a new one get added every time you restart the Tailscale service? (net stop Tailscale, net start Tailscale)

Have you tried newer versions of Tailscale?

/cc @dblohm7

**Comment by dblohm7** [comment]
@alminisl Since 1.14.4 there have been changes to how the Tailscale Tunnel devices are installed and removed. As @bradfitz  suggested, could you please try the newest version of the Tailscale client?

**Comment by alminisl** [comment]
Hi, 

I did update, issue persistet, however, I did an uninstall of tailscale completely, restarted my PC and then installed the new version and now it seems to be fine. 

Not sure if the new version or uninstall fixed it but that seems to have done the trick. 

![image](https://user-images.githubusercontent.com/6343910/149520554-fe5e508e-d4bf-415a-bf97-596969f1f787.png)
 
 Thanks for the responses!

**Comment by bradfitz** [comment]
"network 51" still isn't a great name, though.

**Comment by DentonGentry** [comment]
![Grey_alien](https://user-images.githubusercontent.com/1140756/149541757-0ce2da67-5f65-4ac4-ab8c-20fadb3faa85.jpg)

**Comment by alminisl** [comment]
> "network 51" still isn't a great name, though.

Its autogenerated, I'm not thinking of touching it anymore :D Works as expected!

**Comment by DentonGentry** [comment]
Marking as resolved.
