### ISSUE TITLE
tstime/rate: TestLongRunningQPS test flake

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3733]
At just above a076aaecc6cba71f6869a26cabcf6644071877cc on the CI ...

```
--- FAIL: TestLongRunningQPS (5.00s)
    rate_test.go:208: numOK = 596, want 597 (ideal 600.327094)
FAIL
exit status 1
FAIL	tailscale.com/tstime/rate	5.042s
```

**Comment by josharian** [comment]
Drat. That's the second time, so it's real. (cc @crawshaw)

This first showed up right after upgrading to Go 1.17.6. It seems unlikely that that would have caused it, but...?

I'll investigate.

**Comment by josharian** [comment]
I can reproduce on a heavily loaded machine, both before/after the 1.17.6 upgrade. Which is...good?
