### ISSUE TITLE
FR: pre-shared key that nukes any previous host with the same name

### ISSUE THREAD

**Issue by christopher-cavnue** [tailscale/tailscale#3741]
### What are you trying to do?

I am provisioning embedded devices.

We use a preshared key to bring up tailscale.

I'd like a flag in the key that will nuke any host of the same name on the tailnet (or the equivalent).

In other words;  if I use the key on a host named foo and there's already a host foo on tailscale,  I don't want the new foo to be foo-1.

### How should we solve this?

dealer's choice.

### What is the impact of not solving this?

i have to take care to delete the old foo.

there's an API so i'd try that.

**Comment by DentonGentry** [comment]
Is the node with "hostname" still active on the tailnet when the new node is assigned hostname-1 ?

**Comment by christopher-cavnue** [comment]
no.  it is the same device but re-flashed.

Christopher Hoover  |  V.P. Hardware Engineering

www.cavnue.com

**Comment by DentonGentry** [comment]
One other possibility then: for a typical embedded device the complete state for the tailscale service is stored in /var/lib/tailscale/tailscaled.state. If your process to reflash a device could be changed to:
1. preserve /var/lib/tailscale/tailscaled.state somewhere
1. re-flash the device
1. restore /var/lib/tailscale/tailscaled.state
1. boot and start tailscale

It would come back up with the hostname "foo" and retain the Tailscale IP address which it had before.

I bring this up because I think its unlikely we'd implement the feature exactly as described, an authkey which deauthorizes other nodes, but I do sympathize with the difficulty.

**Comment by christopher-cavnue** [comment]
yep, understood.

that can't work without off-device storage for not great reasons.

before i reflash, can i do something that will logout the device and kill
the registration ?

i could probably work that into our SOPs.


Christopher Hoover  |  V.P. Hardware Engineering

www.cavnue.com

**Comment by DentonGentry** [comment]
You might be able to use:
1. `tailscale up --force-reauth --authkey=tskey-... --hostname=foo-delete-me`
1. wipe the flash and reinstall
1. `tailscale up --authkey=tskey-... --hostname=foo`

https://login.tailscale.com/admin/machines would gradually accumulate dead foo-delete-me-1 nodes which would need to be periodically cleaned up. [The API](https://github.com/tailscale/tailscale/blob/main/api.md#device-delete) could be used to clean them up, or use [ephemeral authkeys](https://tailscale.com/kb/1111/ephemeral-nodes/) to have the control server clean them up after they've been out of contact for a while.

**Comment by christopher-cavnue** [comment]
I'll try that.   Thank you.

Christopher Hoover  |  V.P. Hardware Engineering

www.cavnue.com

**Comment by christopher-cavnue** [comment]
i missed the suggestion for  an ephemeral key.

i think i can safely make an ephemeral key that is tagged dead (w/acls set
so it can't do anything).

that key will not be sensitive.

that will let me write a decommision script that includes this key.  and it
will clean up after itself.

does that seem correct?


Christopher Hoover  |  V.P. Hardware Engineering

www.cavnue.com

**Comment by DentonGentry** [comment]
I think that would be reasonable, I don't see an obvious issue with it.

**Comment by DentonGentry** [comment]
I'm going to close this since I think there is a solution, and it is unlikely that a feature would be developed that would allow one node to deauthorize another node.

**Comment by christopher-cavnue** [comment]
SGTM.

Christopher Hoover  |  V.P. Hardware Engineering

www.cavnue.com

**Comment by DentonGentry** [comment]
As of Thursday,tailscale logout on an ephemeral node will immediately clean it up: https://tailscale.com/blog/ephemeral-logout/
