### ISSUE TITLE
Tailscale failed to register 100.100.100.100 to systemd-resolved

### ISSUE THREAD

**Issue by nodakai** [tailscale/tailscale#3742]
### What is the issue?

```
$ resolvectl status              
Global                                 
           Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: foreign
  Current DNS Server: fdre:dact:ed3f
         DNS Servers: fdre:dact:ed3f 777.777
Fallback DNS Servers: 9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net
          DNS Domain: node.internalconsuldomain service.internalconsuldomain service.internalconsuldomain2

Link 2 (enp2s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (wlxec086b14b199)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.254
       DNS Servers: 192.168.1.254

Link 9 (tailscale0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

### Steps to reproduce

```
~# tailscale down
/etc# ln -sfn ../run/systemd/resolve/stub-resolv.conf resolv.conf
/etc# nmcli con down mywifi
/etc# nmcli con up mywifi
# tailscale up
```

```
$ head -99 /etc/resolv.* 
==> /etc/resolv.conf <==
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search mydomain.com.beta.tailscale.net node.internalconsuldomain service.internalconsuldomain service.internalconsuldomain2

==> /etc/resolv.pre-tailscale-backup.conf <==
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search node.internalconsuldomain service.internalconsuldomain service.internalconsuldomain2
```

I'm using NetworkManager primarily for managing WiFi connections and tried enabling systemd-resolved hoping it integrates better with Tailscale

```
$ head -99 `find /etc/systemd -path '*resolved*' -type f`
==> /etc/systemd/resolved.conf <==
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation; either version 2.1 of the License, or (at your option)
#  any later version.
#
# Entries in this file show the compile time defaults. Local configuration
# should be created by either modifying this file, or by creating "drop-ins" in
# the resolved.conf.d/ subdirectory. The latter is generally recommended.
# Defaults can be restored by simply deleting this file and all drop-ins.
#
# Use 'systemd-analyze cat-config systemd/resolved.conf' to display the full config.
#
# See resolved.conf(5) for details.

[Resolve]
# Some examples of DNS servers which may be used for DNS= and FallbackDNS=:
# Cloudflare: 1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
# Google:     8.8.8.8#dns.google 8.8.4.4#dns.google 2001:4860:4860::8888#dns.google 2001:4860:4860::8844#dns.google
# Quad9:      9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net 2620:fe::fe#dns.quad9.net 2620:fe::9#dns.quad9.net
#DNS=
FallbackDNS=9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net
#Domains=
#DNSSEC=no
#DNSOverTLS=no
MulticastDNS=no
LLMNR=no
#Cache=yes
#CacheFromLocalhost=no
#DNSStubListener=yes
#DNSStubListenerExtra=
#ReadEtcHosts=yes
#ResolveUnicastSingleLabel=no

==> /etc/systemd/resolved.conf.d/internalconsuldomain.conf <==
[Resolve]
DNS=fdre:dact:ed3f
Domains=node.internalconsuldomain service.internalconsuldomain

==> /etc/systemd/resolved.conf.d/internalconsuldomain2.conf <==
[Resolve]
DNS=777.777
Domains=service.internalconsuldomain2
```

### OS

Linux

### OS version

Debian testing bookworm

### Tailscale version

1.20.1

### Bug report

BUG-d65f3ed605ae772cf548e0c16f6fcd1e054b1d8a64abcd969e48ad00f2af9337-20220115061233Z-970b5d739fea53c1

**Comment by DentonGentry** [comment]
I see all of the output of the various files but I honestly don't understand what you think is wrong.
systemd-resolved is running, but tailscaled overwrote /etc/resolv.conf to use 100.100.100.100 instead?

**Comment by bradfitz** [comment]
Yeah, the report is that it's picking directManger:

```
2022-01-14 22:07:01.857921914 +0800 +0800: dns: [rc=nm resolved=not-in-use ret=direct]
2022-01-14 22:07:01.857979675 +0800 +0800: dns: using *dns.directManager
```

@danderson, you said you hit this too recently and had an idea what's happening?

**Comment by nodakai** [comment]
I'm using Debian which, in my understanding, provides resolved only on a provisional basis. Let me know if you need more info from my side

**Comment by maleadt** [comment]
I'm hitting this too on both Debian Stable and Arch Linux, both configured to use systemd-resolved (with resolv.conf a symlink to /run/systemd/resolve/resolv.conf), but as soon as tailscale starts resolv.conf gets overwritten (logs mentioning `dns: using *dns.directManager`).

```
 cat /etc/resolv.pre-tailscale-backup.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 100.100.100.100
search redacted.beta.tailscale.net
```

```
$ resolvectl
Global
         Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: foreign
Current DNS Server: 100.100.100.100
       DNS Servers: 100.100.100.100
        DNS Domain: tim-besard.gmail.com.beta.tailscale.net

Link 2 (eth0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (tailscale0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

**Comment by nodakai** [comment]
When the system was experiencing the issue, I got this

```
$ gdbus introspect --system --dest org.freedesktop.NetworkManager --object-path /org/freedesktop/NetworkManager/DnsManager
...snip...
  interface org.freedesktop.NetworkManager.DnsManager {
    methods:
    signals:
    properties:
      readonly s Mode = 'default';
      readonly s RcManager = 'symlink';
      readonly aa{sv} Configuration = [{'nameservers': <['192.168.1.254']>, 'interface': <'wlxec086b14b199'>, 'priority': <100>, 'vpn': <false>}];
  };
};
```

However after some experiments involving `systemctl restart tailscaled`, now I get this

```
  interface org.freedesktop.NetworkManager.DnsManager {
    methods:
    signals:
    properties:
      readonly s Mode = 'systemd-resolved';
      readonly s RcManager = 'unmanaged';
      readonly aa{sv} Configuration = [{'nameservers': <['192.168.1.254']>, 'interface': <'wlxec086b14b199'>, 'priority': <100>, 'vpn': <false>}];
  };
```

and `resolvectl status` as well as name resolution of Tailscale-managed host names are working just fine.

I'll post more info once the problem comes back.

**Comment by bradfitz** [comment]
@nodakai, can you try unstable build 1.21.26 and try again and share a `tailscale bugreport`? We added some logging that would help us understand what's happening. Thanks!

**Comment by danderson** [comment]
Notes from a talk with gdentry and danderson:
This appears to be a race condition, tailscaled chooses a DNS mechanism to use once at startup. We set the systemd unit ordering for tailscaled to start after resolved, but it is still possible for tailscaled to start before the actual DBus portion of resolved has registered itself. If this happens, tailscaled will conclude that resolved isn't actually running and will decide to use the Direct management instead (and will overwrite /etc/resolv.conf).

The fully general solution would be to make the choice of DNS mechanism dynamic, not just once at startup. We already monitor various DBus notifications, we could watch for a new bus service to appear and respond when it does. We'd do this for a number of services for resolved and NetworkManager. If we see one that impacts the choice of DNS manager we'd tear down DNS and set it back up, giving us a second chance to choose the manager. (Ideally we'd dynamically adjust the DNS config for the new manager, but that opens a vast number of transitions we'd need to test and we'd probably not be able to fully test it)

A more immediate alternative:
systemd units have a way (I think) to depend on DBus service readiness. The tailscaled systemd file could delay startup until the resolved dbus channel is actually available. It isn't clear that would be safe to do on all systems (what if they don't use systemd-resolved at all?) but could be done on individual systems which otherwise run into this problem.

An even more immediate alternative:
This is a fairly narrow race condition between when systemd-resolved starts its daemon and when the daemon opens its DBus channel. Adding a one second delay to the tailscaled systemd file would likely avoid the problem.

**Comment by maleadt** [comment]
> This appears to be a race condition, tailscaled chooses a DNS mechanism to use once at startup. We set the systemd unit ordering for tailscaled to start after resolved, but it is still possible for tailscaled to start before the actual DBus portion of resolved has registered itself. If this happens, tailscaled will conclude that resolved isn't actually running and will decide to use the Direct management instead (and will overwrite /etc/resolv.conf).

I'm not sure that's the case, as I can reproduce _after_ start-up, without touching systemd-networkd:

```
$ sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf                                                                                                                                  

$ sudo systemctl restart tailscaled.service

$ head /etc/resolv.conf
# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).
# Do not edit.

$ sleep 1

$ head /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN
```

**Comment by durind** [comment]
Hi,

I had similar problem with Debian Sid with Tailscale, NetworkManager and systemd-resolved where the MagicDNS stopped working after a while.

I found out that the NetworkManager in Debian detects that systemd-resolved is used if the /etc/resolv.conf is a link to /run/systemd/resolve/stub-resolv.conf. When Tailscale comes up it recreates the /etc/resolv.conf as a file and when the DHCP-renew happens NetworkManager thinks it should handle /etc/resolv.conf since it's a file and not a link and overwrites Tailscale settings.

I fixed this on my system setting NetworkManager.conf dns and rc-manager options.

https://manpages.debian.org/unstable/network-manager/NetworkManager.conf.5.en.html

**Comment by DentonGentry** [comment]
For those experiencing a problem with /etc/resolv.conf and detecting systemd-resolved, could you try installing from the unstable track https://pkgs.tailscale.com/unstable/ build 1.21.73 or later?

[#3905](https://github.com/tailscale/tailscale/pull/3905) reorders some of the steps in tailscaled's startup process to try to ensure that systemd-resolved is initialized and ready to respond before tailscaled checks it.

**Comment by nodakai** [comment]
Sorry for not being able to add much info, I didn't experience the original problem in the last couple of weeks. I've been using the official stable releases only, just installed 1.22.0

**Comment by DentonGentry** [comment]
Since it appears to have gone away in 1.22, we'll assume the changes to better detect systemd-resolved fixed it.
