### ISSUE TITLE
x86_64 DSM 7 package missing for 1.20 + 1.20.1 release

### ISSUE THREAD

**Issue by traktuner** [tailscale/tailscale#3743]
### What are you trying to do?

The DSM 7 package (x86_x64) is missing on the tailscale-synology release page. For 1.20.1 only source code was released.

### How should we solve this?

Please add the missing package(s)

### What is the impact of not solving this?

Can not upgrade to the latest Tailscale version on all my Synology DSM 7 devices

### Anything else?

Thank you very much :)

**Comment by DentonGentry** [comment]
We do intend to. The SPKs are built by a GitHub runner, and the upload of the x86_64 SPK keeps failing for reasons we don't fully understand yet. When we get that resolved, the SPKs will be uploaded.

**Comment by traktuner** [comment]
Thank you very much for the clarification!
