### ISSUE TITLE
exit-node-allow-lan-access doesn't handle VLANs

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3750]
Did we break `--exit-node-allow-lan-access`? It's not working on Linux in 1.20.1.

Sorry, screenshot, as I'm console'd into a remote machine I lost ssh to:

<img width="1321" alt="Screen Shot 2022-01-17 at 8 54 55 AM" src="https://user-images.githubusercontent.com/2621/149810220-2a316380-a4ff-47b9-b718-061ffeae4f95.png">

/cc @danderson @maisem

**Comment by DentonGentry** [comment]
I remember testing it in 1.20.0 (which is painful because I lose ssh access and have to go to Proxmox console to allow LAN access again).

**Comment by bradfitz** [comment]
```
root@tsbi:~# tailscale bugreport
BUG-d40ccddffe4093520a6706c81dbf5d8c885af1a63907f826999d418b63098d0c-20220117170012Z-e76045a017531775
root@tsbi:~# tailscale debug prefs
{
        "ControlURL": "https://controlplane.tailscale.com",
        "RouteAll": false,
        "AllowSingleHosts": true,
        "ExitNodeID": "nSxiPT1CNTRL",
        "ExitNodeIP": "",
        "ExitNodeAllowLANAccess": true,
        "CorpDNS": true,
        "WantRunning": true,
        "LoggedOut": false,
        "ShieldsUp": false,
        "AdvertiseTags": null,
        "Hostname": "",
        "NotepadURLs": false,
        "AdvertiseRoutes": [],
        "NoSNAT": false,
        "NetfilterMode": 2,
...
```

**Comment by bradfitz** [comment]
Well here's the problem from the logs:

```
2022-01-17 09:00:13.692679808 -0800 PST: allowing exit node access to internal IPs: [127.0.0.0/8]
```

It's just not finding the LAN IPs at all.

My addresses, with global IPv6s removed:

```
root@tsbi:~# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    altname enp0s3
    inet 10.15.25.235/24 brd 10.15.25.255 scope global dynamic ens3
       valid_lft 487sec preferred_lft 487sec
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    inet 100.108.65.105/32 scope global tailscale0
       valid_lft forever preferred_lft forever
```

**Comment by bradfitz** [comment]
Code is:

```go
                internalIPs, externalIPs, err := internalAndExternalInterfaces()
                if err != nil {
                        b.logf("failed to discover interface ips: %v", err)
                }
                if runtime.GOOS == "linux" || runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
                        rs.LocalRoutes = internalIPs // unconditionally allow access to guest VM networks 
                        if prefs.ExitNodeAllowLANAccess {
                                rs.LocalRoutes = append(rs.LocalRoutes, externalIPs...)
                                if len(externalIPs) != 0 {
                                        b.logf("allowing exit node access to internal IPs: %v", internalIPs)
                                }
                        } else {
```

And I'm not seeing that `failed to discover interface ips` line in my logs.  So `internalAndExternalInterfaces` just isn't working.

**Comment by bradfitz** [comment]
Pulled out `internalAndExternalInterfaces` into a manual debug test and I see that my LAN IP is getting detected as an external IP:

```
root@tsbi:~# ./ipnlocal.test -test.run=Manual -test.v
=== RUN   TestIssue3750Manual
    local_test.go:619: int=1, ext=3, err=<nil>
    local_test.go:621: int[0] = 127.0.0.0/8
    local_test.go:624: ext[0] = 10.15.25.0/24
    local_test.go:624: ext[1] = 2xxx::/64
    local_test.go:624: ext[2] = fe80::/64
--- PASS: TestIssue3750Manual (0.00s)
PASS

```

**Comment by bradfitz** [comment]
oh! `internalAndExternalInterfaces` isn't what I thought it was. It's the WSL thingy about LANs that are actually localhost things that aren't obviously localhost things.

Hahaha this log print is backwards and misleading:

```go
rs.LocalRoutes = append(rs.LocalRoutes, externalIPs...)
if len(externalIPs) != 0 {
        b.logf("allowing exit node access to internal IPs: %v", internalIPs)
}
```

Notice how it appends `externalIPs` but then logs `internalIPs`. Whoops.

**Comment by bradfitz** [comment]
This is still broken for me.

I got cut off from my dev VM.

**Comment by bradfitz** [comment]
Ah, it's replying to my pings out the wrong interface. But because it doesn't know the ping from 10.15.25.0/24 is a different one of my VLANs (as only its router nows about that), so it assumes it's "the internet" and routes it over the exit node.

<img width="901" alt="Screen Shot 2022-02-20 at 10 21 59 AM" src="https://user-images.githubusercontent.com/2621/154857792-2f2d81c8-f8b5-4bb7-9609-a62367093891.png">

/cc @danderson

**Comment by maisem** [comment]
Yeah this is a known limitation with `exit-node-allow-lan-access`. As you said, it doesn't know that `10.15.25.0/24` is a different VLAN accessible from your local network. What happens if you `--advertise-routes=10.15.25.0/24` but don't approve it from the admin panel?

**Comment by DentonGentry** [comment]
Related, regarding routed local LAN subnets: https://github.com/tailscale/tailscale/issues/3646

**Comment by DentonGentry** [comment]
I think this ends up being the same feature request as https://github.com/tailscale/tailscale/issues/3646
