### ISSUE TITLE
cmd/tailscale: disable up's revert protector on `--exit-node-allow-lan-access` when disabling exit node?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3752]
This is always annoying, disabling an exit node:

```
root@tsbi:~# tailscale up --exit-node=
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --exit-node= --exit-node-allow-lan-access

```

It's very verbose to have to specify `--exit-node-allow-lan-access=false` whenever I'm disabling an exit node.  (And you can't write `--exit-node-allow-lan-access` because then it complains that you can't use that option along with an empty `--exit-node=` value)

I think we might want to make an exception to our "no silent flag changes" rule and permit an implicit `--exit-node-allow-lan-access=true` => its flag default value of `false` here, but only when `--exit-node=` (blank, off).

/cc @maisem @danderson

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/5718 was closed with the note that we may no longer need this given `tailscale set --exit-node=...`

Barring further comment, we'll expect to close this durig the next regular bug scrub.

**Comment by bradfitz** [comment]
Or now :)
