### ISSUE TITLE
Exit node with ACL seems to not work as intended

### ISSUE THREAD

**Issue by codyro** [tailscale/tailscale#3755]
### What is the issue?

When using an exit node an ACL rule utilizing a `tag` doesn't work causing traffic to not pass through the exit node.

### Steps to reproduce

1. Configure a node  as an `exit node`
2. Configure `tagOwners` & tag the `Exit Node`
3. Configure an ACL using the newly created tag allowing all traffic to pass through. [1]
4. Connect to the `exit node` and traffic will not pass through

[1] Example ACL rule:

```
<snip>
    {
      "action": "accept",
      "users": ["group:admins"],
      "ports": [
        "tag:exitnodes:*",
      ],
    }
</snip>
```

When using the special `autogroup:internet` tag / keyword this works as intended:

```
    {
      "action": "accept",
      "users": ["group:admins"],
      "ports": [
        "autogroup:internet:*",
      ],
    }
```

### OS

Linux, macOS, Windows

### OS version

macOS Monteray 12.1 / EL7

### Tailscale version

1.18.2 (macOS), 1.20.1 (EL7)

### Bug report

BUG-8e65cb25dcef80cde366f9ac457c51570bd8893ff0651211baf20a36825ba67c-20220118191743Z-8468b74b395f0c9e

**Comment by maisem** [comment]
That is working as intended. The two ACL rules you mentioned give different permissions on the network

- This rule allows `group:admins` to talk to any service on the internet (i.e. use an exit node). But they won't be able to access the exit node itself (e.g. they won't be able to ssh to the exit node)
```
    {
      "action": "accept",
      "users": ["group:admins"],
      "ports": [
        "autogroup:internet:*",
      ],
    }
```

- This rule allows `group:admins` to access nodes tagged with `tag:exitnodes` (e.g. ssh to the node itself) but it doesn't allow them to route traffic via that node.

```
    {
      "action": "accept",
      "users": ["group:admins"],
      "ports": [
        "tag:exitnodes:*",
      ],
    }
```

**Comment by codyro** [comment]
Thank you for the clarification. Upon reading the ACL documentation again the verbiage seems to reiterate what you said but I parsed it differently.

> Access to the internet through exit nodes

Thanks for the clarification. I'll close this out. Hopefully my mistake will help someone else in the future.
