### ISSUE TITLE
No connectivity after connecting to exit node

### ISSUE THREAD

**Issue by Kan-El** [tailscale/tailscale#3757]
### What is the issue?

After connecting to an exit node there is no network connectivity.

I connect to my exit node with `sudo tailscale up --exit-node=100.113.86.119 --accept-routes --exit-node-allow-lan-access` and then if i for example run `ping 8.8.8.8`  i don't get any response.
If i disconnect from the exit node with `sudo tailscale up --exit-node= --accept-routes=false --exit-node-allow-lan-access=false` `ping 8.8.8.8` returns `connect: Network is unreachable`.

![IMG_20220119_074552](https://user-images.githubusercontent.com/63242013/150078623-85736c52-0682-4fd2-8995-6bb3b02230e8.png) 

Only after reboot internet starts working again.

### OS

Linux

### OS version

Debian 10 / Chrome OS Linux VM

### Tailscale version

1.20.1

### Bug report

BUG-9dfe9b2a92959e29bba059bcb948f5fb5cd8982ed99b343a4c1dffba8d14c02c-20220118205233Z-902c40cc50f85e3c

**Comment by bradfitz** [comment]
@Kan-El, we think this is now fixed in the unstable track (where we do development work before making new releases or cherry-picking fixes back to the stable release).

See https://github.com/tailscale/tailscale/issues/3842#issuecomment-1026302275

Can you try that build out and see if it fixes it for you? You only need to update your exit node's Tailscale, not the clients.

Thanks!

**Comment by Kan-El** [comment]
I updated my exit node but it still didn't work, so I tried updating the client but i got the same result.

**Comment by meinside** [comment]
Any update on this issue?

I do too have exit nodes on two linux machines, and updated one of them to unstable version: 1.21.50
but the problem doesn't go away.

I have tested with macOS and Android devices but all of them lose connection after connecting to the exit nodes.

(BUG-a399c60be7e9d7dc2fa133187ba9e109ba3869afb263612fdc2de2d811607ab9-20220204070020Z-5f3d1848686808cf)

**Comment by DentonGentry** [comment]
Possibly relevant: https://github.com/tailscale/tailscale/issues/3310, if the exit node is an Alpine derivative.

**Comment by 0q2** [comment]
Any update?

**Comment by DentonGentry** [comment]
To make progress we'll need a fresh `tailscale bugreport` at a time when a node has no connectivity while it is connected to an exit node.

**Comment by Kan-El** [comment]
Unfortunately I don't have the chrome book any more, so I can't test if it still doesn't work

**Comment by DentonGentry** [comment]
I don't expect to resolve the originally reported issue at this point.
