### ISSUE TITLE
iodéOS (Android derivative) - No Internet Access when Tailscale VPN connected

### ISSUE THREAD

**Issue by tokenwizard** [tailscale/tailscale#3758]
### What is the issue?

When I updated to the most recent version of Tailscale on Android (via F-Droid, v. 1.19.190) I no longer have internet connectivity when I connect the Tailscale VPN. 

If I turn off the Tailscale VPN, I can access any website as usual. As soon as I connect Tailscale, I can no longer browse any websites or even ping (fast.com, google.com, etc). 

I downgraded to the previous version (1.18.2) and Internet works fine with Tailscale installed.

I am not using any devices as exit nodes. 

My device is a Xiaomi Mi 9 running IOde' OS (Android 10) and never had any problems with Tailscale on this device up until this most recent version.  

I can connect/ping to other devices connected to my Tailscale network, just not the Internet. 

FWIW, When connected to Tailscale using the latest version, I cannot ping google.com come but I can ping them via IP (64.233.177.113) so it seems like there is something different with the DNS in the 1.19.190 version that breaks Internet connectivity for normal use (at least for me). 

### Steps to reproduce

1) Install latest version via F-Droid
2) Sign In and Connect via my GitHub account
3) Toggle the "on" switch to connect to Tailscale VPN
4) Open a Web Browser on the device and try to go to any website. 

### Are there any recent changes that introduced the issue?

The only change on my device was just updating to the latest version of the Tailscale app. 

### OS

Android

### OS version

IOde' OS (Android 10)

### Tailscale version

1.19.190

### Bug report

BUG-6fe19ba29e2c9878d76eb4101949e8249c198d7cefbdd7eb1920315c9f9ec75b-20220118211408Z-cef8abf6e8d9f10a

**Comment by DentonGentry** [comment]
Indeed, one of the main changes in 1.20 for Android is changing how the DNS configuration is handled: https://github.com/tailscale/tailscale/issues/2116

From that bugreport we see all three of the mechanisms to retrieve the current DNS config returned an empty list:
```
2022-01-18 21:04:42.589303877 +0000 UTC: 6.0M/152.3M dns: Set: {DefaultResolvers:[] Routes:{example.beta.tailscale.net.:[] ts.net.:[]}+65arpa SearchDomains:[tails-scales.ts.net. example.beta.tailscale.net.] Hosts:19}
2022-01-18 21:04:42.59214695 +0000 UTC: getDnsConfigFromLinkProperties:
2022-01-18 21:04:42.592911169 +0000 UTC: getDnsServersFromSystemProperties:
2022-01-18 21:04:42.593824867 +0000 UTC: getDnsServersFromNetworkInfo:
```

However we also see: `2022-01-18 21:04:43.252591689 +0000 UTC: interfaces: found Android default route 192.0.0.1`

192.0.0.1 is used for IPSec support. Is IPSec in use? The code to find DNS configuration skips over all VPN interfaces, as we need to make sure we don't unintentionally read out our own DNS config. If there is a second VPN on the device, the new DNS config handling will never find its DNS servers.

**Comment by tokenwizard** [comment]
I don't have any other sort of VPN on the device. IOde' OS does have a firewall built-in, but I would not expect that to be related? I have never adjusted any of those Firewall settings.

**Comment by DentonGentry** [comment]
I had missed the note that it is running iodéOS.

From https://iode.tech/en/iodeos-installation/
- To provide a new and powerful way of blocking ads, malwares, data leaks of all kinds to many intrusive servers. We are developing an analyzer, tightly integrated into the system, that captures all DNS requests and network traffic, as well as a user interface (the iodé app).
- Being independent of the kind of DNS server used by the system or set by an independent app: classical DNS on UDP port 53 or any other one, DNS over TLS (DoT), DNS over HTTPS (DoH), …, as we capture the DNS requests before they are transmitted to the system function that emits the DNS request. What we do not support, is DoH when it is natively built into applications, i.e. when an app communicates directly with a DoH server, without asking name resolution to the system. It would require to decrypt HTTPS packets between such an app and the DoH server, which may create a big security hole.

Yeah, this is why it isn't working. The DNS config in this system is different.

**Comment by DentonGentry** [comment]
Looking at https://iode.tech/en/iodeos-installation/, I don't have any device which iodéOS could be installed on. If we ever do get a way to try to accommodate iodéOS, the mechanisms by which we try to figure out the DNS config are in https://github.com/tailscale/tailscale-android/blob/main/android/src/main/java/com/tailscale/ipn/DnsConfig.java

In the meantime I'd recommend either:
1. In https://login.tailscale.com/admin/dns, enabled "Override local DNS". This will apply to all devices in the tailnet not just Android, but will mean it doesn't need to read out the current DNS config at all.
1. Since you're using the F-Droid package, you could downgrade to 1.17.x which doesn't even attempt to make the non "Override local DNS" option work.

**Comment by tokenwizard** [comment]
Odd, I have not updated my iodeOS recently. That feature must be baked into the older versions as well and I guess just doesn't play well with the changes in the recent version of Tailscale. 
I had already downgraded to version 1.18.2 via F-Droid and that was enough to resolve the issues. It seems that version is fine with iodeOS.

**Comment by weirdal3333** [comment]
I'm on android 12, I have a Motorola G stylus 2022. I also have an android 10 OnePlus Nord n200 device. I'm having the same exact issue here.
