### ISSUE TITLE
FR: support exposing single targets 

### ISSUE THREAD

**Issue by hazcod** [tailscale/tailscale#3760]
### What are you trying to do?

It would be nice to be able to expose a single application (protocol + port) combination over the tailnet instead of connecting a full device. e.g. when we want to connect a single application on a server.

### How should we solve this?

Support a filter/whitelist in the `tailscale up` command to filter on port.

e.g.

```shell
# expose a local webserver to the tailnet
% tailscale up --whitelist='tcp://127.0.0.1:8080'

# expose another webserver
% tailscale up --whitelist='tcp://10.10.1.3:8080'
```

### What is the impact of not solving this?

Some use cases might not want to connect itself fully to the tailnet.

**Comment by DentonGentry** [comment]
I believe ACLs could meet this need: https://tailscale.com/kb/1018/acls/
An ACL could allow exposing only one port to the tailnet.

The way Tailscale is implemented, even if a feature request like this were implemented it would internally be a wireguard tunnel with an ACL that only allows the one port to be contacted.

**Comment by hazcod** [comment]
@DentonGentry While I agree, I have a use case where I could ask customers to install tailscale to securely connect a single device to my tailnet so I can reach that service. The customer has no insight in the ACL applied, and ACLs are prone to change.

**Comment by DentonGentry** [comment]
Two other notes, then:
- Another alternative would be to have them use their own tailnet, and share the node to yours: https://tailscale.com/kb/1084/sharing/ The ACLs are then under their own control.
- There may eventually be features to allow public access with a minimal surface area, like exposing a webhook on one port: https://github.com/tailscale/tailscale/issues/972

**Comment by bradfitz** [comment]
Basically this is the existing `--shields-up` plus adding something like `--allow=tcp/8080`.

**Comment by hazcod** [comment]
@bradfitz Don't forget an (optional) target ip, this could make the `tailscale` cli work as a reverse tunnel to the tailnet!

e.g.
`--allow=tcp/8080` would mean the same as `--allow=tcp://localhost:8080` but not as `--allow=tcp://10.10.1.10:8080`.

**Comment by bradfitz** [comment]
You're conflating different features here. There are vague plans for rinetd-like functionality in tailscaled but that's almost certainly not how we'd express it.

**Comment by DentonGentry** [comment]
One other relevant possibility is tsnet, which allows Tailscale to run as a library within a single process.
https://github.com/tailscale/tailscale/tree/main/tsnet

**Comment by DentonGentry** [comment]
More about tsnet: https://tailscale.com/blog/tsnet-virtual-private-services/

**Comment by DentonGentry** [comment]
>It would be nice to be able to expose a single application (protocol + port) combination over the tailnet instead of connecting a full device. e.g. when we want to connect a single application on a server.

At this point I believe tsnet addresses the original feature request.
- https://github.com/tailscale/tailscale/tree/main/tsnet
- https://tailscale.com/blog/tsnet-virtual-private-services/
- The Tailscale Up conference this week had a session by @Xe titled "The subtle magic of embedding Tailscale into your services" which covered tsnet. The video of this session will be posted eventually, and will be findable in Internet searches.
