### ISSUE TITLE
Synology Outbound Connections not Persistent After Reboot (DSM 7 / 

### ISSUE THREAD

**Issue by rncole** [tailscale/tailscale#3761]
### What is the issue?

After following the instructions at [https://tailscale.com/kb/1152/synology-outbound/](https://tailscale.com/kb/1152/synology-outbound/), outbound connections are not persistent after restarting the synology device.  Re-running the setcap (below) command and restarting the Tailscale service are required to re-enable.

setcap command:
`sudo setcap cap_net_admin+eip /var/packages/Tailscale/target/bin/tailscaled`

### Steps to reproduce

Restarted Synology

### OS

Synology

### OS version

Synology DSM 7 (DSM 7.0.1-42218)

### Tailscale version

1.20.1-2017

**Comment by bradfitz** [comment]
Huh, weird. I thought that was persistent and was previously working. Does DSM proactively remove that bit from disk at boot or does it never make it to to disk? Is that in-memory only?

DSM7 has systemd. We should probably make our instructions be about installing a start-up unit that fixes things. Perhaps just making the unit be `/var/packages/Tailscale/target/bin/tailscaled synoinit` or something so we can add new startup items over time.

cc @maisem, @danderson, @Xe

**Comment by rncole** [comment]
I did some more testing and it doesn't appear to be the cap.  **Apologies for mis-identifying the initial problem.**  The actual problem is that the `tun` device permissions are getting reset on reboot on DSM7.

Background: I use Tailscale for a Synology-Synology sync where one is behind a T-Mobile CGN rendering most other VPN solutions non-starters.

Here's the getcap output while working:
> $ sudo getcap /var/packages/Tailscale/target/bin/tailscaled
> /var/packages/Tailscale/target/bin/tailscaled = cap_net_admin+eip

After a reboot, here's the same:
> $ sudo getcap /var/packages/Tailscale/target/bin/tailscaled
> /var/packages/Tailscale/target/bin/tailscaled = cap_net_admin+eip

So that part is persistent, however, outbound connections were now no longer functioning.  Re-setting the cap with setcap and restarting Tailscale alone still did not allow outbound.

I re-ran the rest of the commands (placed into a shell script):
> tailscale-outbound-enable.sh 
> mknod: /dev/net/tun: File exists

At this point (now operating correctly) the following is the status as expected:
>/dev$ ls -lah | grep net
>drwxr-xr-x  2 root root        60 Jan 19 11:10 net

> /dev$ ls -lah net
> crw-rw-rw-  1 root root 10, 200 Jan 19 11:10 tun

After a reboot, the following is found:
> /dev$ ls -lah |grep net
> drwxr-xr-x  2 root root        60 Jan 19 11:23 net

> /dev$ ls -lah net
> crw-------  1 root root 10, 200 Jan 19 11:23 tun

So it appears the tun device permissions are being reset to root.  At this point I ran only `sudo chmod 0666 /dev/net/tun` and restarted Tailscale, with expected outbound connections working again.

**Comment by gitmk1** [comment]
My friend and I have a ShareSync connection on DSM 8, and we also try to keep this up via Tailscale and got the same problem.
@rncole : Thanks for your investigation. Do you already found out how to bypass this problem with a script or smth.? Maybe you could share your further improvements?
Thx in Advance.

**Comment by rncole** [comment]
I considered putting a startup script to update the permissions prior to tailscale starting, but since rebooting is so infrequent and I'm optimistic that this will be resolved I didn't pursue.  That would be the quick and dirty fix though.

**Comment by pfriedrich84** [comment]
For me the chmod was not working, i had to create /dev/net/tun again.
anyway after this and and restart everything is up an running again! 

@gitmk1 connected ;-)

**Comment by kohms** [comment]
I had that problem before, I attached it in https://github.com/tailscale/tailscale/issues/1995#issuecomment-1006023578 last time. The last time running a scheduled task via the task scheduler fixed it.
After installing DSM 7.0.1-42218 Update 2 on ds918+ it suddenly stopped working.

**Comment by kohms** [comment]
Ah, one comment regarding https://tailscale.com/kb/1152/synology-outbound/. 
Restarting tailscale via Web ui can be a problem if you are not doing that for a local NAS. If connected via quickconnect, I am not allowed to manage the Tailscale package. If I connect to it via Tailscale's IP, I can only stop and start the service, but once it is stopped, the connection to my remote NAS is gone as well. 

My workaround so far is to connect to the remote NAS via ssh and use synology's systemctl wrapper to restart in a single command, that seem to work, I would be only screwed, if the tailscale service would not come back online again. 😅
```
sudo synosystemctl restart pkgctl-Tailscale.service
```

**Comment by daneroo** [comment]
I have both a DS1821+, and DS920+, both running DSM7.

capability is preserved across reboots:
```
$ sudo getcap /var/packages/Tailscale/target/bin/tailscaled
/var/packages/Tailscale/target/bin/tailscaled = cap_net_admin+eip
```

But the `/dev/net/tun` device needs to be recreated (as in the [instructions](https://tailscale.com/kb/1152/synology-outbound/)) **after every reboot** (which contradicts the comment in said instructions - at least for me).

Luckily tailscale does come up with (`--tun=userspace-networking`) allowing me to ssh into the remote unit, and recreate the device with proper permissions.

The missing piece of information for a workaround (thanks @kohms) was how to remotely restart the service 
```
sudo synosystemctl restart pkgctl-Tailscale.service
```

Perhaps this could be added to the [instructions](https://tailscale.com/kb/1152/synology-outbound/)

**Comment by bradfitz** [comment]
@daneroo, the next builds (greater than 1.21.50) will have a new `tailscale configure-host` command, so you can go into Synology > Control Panel > Task Scheduler and "Create > Triggered Task" as User `root` and Event `Boot-up` and in the `User Defined Script` section, write:

```
/var/packages/Tailscale/target/bin/tailscale configure-host
```

Then it'll fix things up on each boot.

**Comment by daneroo** [comment]
Thanks for the update @bradfitz 
Do you know how/when **Synology Package Center** pulls new releases from upstream tailscale repos?
_current release in Package Center is `v1.16.2` from Oct 29, 2021_

And thanks for all the amazing work!

**Comment by DentonGentry** [comment]
> Do you know how/when Synology Package Center pulls new releases from upstream tailscale repos?

Nominally monthly, but we regularly have months where a release doesn't go out and we have no visibility into why. At this point, if you want features from recent development it is best to sideload the package from https://pkgs.tailscale.com/stable/ or, if you want to really live on the edge, from https://pkgs.tailscale.com/unstable/

**Comment by JBLeung** [comment]
> I did some more testing and it doesn't appear to be the cap. **Apologies for mis-identifying the initial problem.** The actual problem is that the `tun` device permissions are getting reset on reboot on DSM7.
> 
> Background: I use Tailscale for a Synology-Synology sync where one is behind a T-Mobile CGN rendering most other VPN solutions non-starters.
> 
> Here's the getcap output while working:
> 
> > $ sudo getcap /var/packages/Tailscale/target/bin/tailscaled
> > /var/packages/Tailscale/target/bin/tailscaled = cap_net_admin+eip
> 
> After a reboot, here's the same:
> 
> > $ sudo getcap /var/packages/Tailscale/target/bin/tailscaled
> > /var/packages/Tailscale/target/bin/tailscaled = cap_net_admin+eip
> 
> So that part is persistent, however, outbound connections were now no longer functioning. Re-setting the cap with setcap and restarting Tailscale alone still did not allow outbound.
> 
> I re-ran the rest of the commands (placed into a shell script):
> 
> > tailscale-outbound-enable.sh
> > mknod: /dev/net/tun: File exists
> 
> At this point (now operating correctly) the following is the status as expected:
> 
> > /dev$ ls -lah | grep net
> > drwxr-xr-x  2 root root        60 Jan 19 11:10 net
> 
> > /dev$ ls -lah net
> > crw-rw-rw-  1 root root 10, 200 Jan 19 11:10 tun
> 
> After a reboot, the following is found:
> 
> > /dev$ ls -lah |grep net
> > drwxr-xr-x  2 root root        60 Jan 19 11:23 net
> 
> > /dev$ ls -lah net
> > crw-------  1 root root 10, 200 Jan 19 11:23 tun
> 
> So it appears the `tun` device permissions are being reset to root. At this point I ran only `sudo chmod 0666 /dev/net/tun` and restarted Tailscale, with expected outbound connections working again.


I followed the steps and my net and tun look like this, but seem cannot use my synology exit node still cannot access to the internet, any idea? or how should I troubshoot?

```
drwxr-xr-x  2 root root        60 Feb  9 00:23 net
crw-rw-rw-  1 root root 10, 200 Feb  9 00:23 tun
```

**Comment by DentonGentry** [comment]
Please paste the output of `tailscale bugreport` from the Synology device while trying to use it as an exit node. We can get a lot more information from a bugreport.

**Comment by JBLeung** [comment]
> Please paste the output of `tailscale bugreport` from the Synology device while trying to use it as an exit node. We can get a lot more information from a bugreport.

🙇🏻‍♂️

BUG-afb6b8c70985e5238fd0d261d0e6cd7fdc38c6d2330eea09268603f09775465d-20220209033748Z-f4fffbec1f6c8a21

**Comment by bradfitz** [comment]
@JBLeung, you're running 1.16.2. You'll want to use a newer version: https://pkgs.tailscale.com/unstable/#spks

Unfortunately Synology hasn't updated the Package Center in some time.

**Comment by bradfitz** [comment]
A new Synology build with `tailscale configure-host` is building now.

Details on use: https://github.com/tailscale/tailscale/issues/3761#issuecomment-1033000684

Or, in screenshot form:

<img width="1040" alt="Screen Shot 2022-02-08 at 8 16 20 PM" src="https://user-images.githubusercontent.com/2621/153120963-7140cabc-4d11-40e5-b67b-487f70792dc6.png">

<img width="560" alt="Screen Shot 2022-02-08 at 8 16 25 PM" src="https://user-images.githubusercontent.com/2621/153120979-52606a2c-224c-4082-bc1f-741954ef0dfc.png">

**Comment by JBLeung** [comment]
I am using DS220+ which build I should download?

**Comment by rncole** [comment]
Great news! I’ll give it a try if it’s posted tomorrrow!

**Comment by JBLeung** [comment]
Seem the synology exit node working again~
but seem the client IP didn't change when I connected to the synology exit node...

**Comment by bradfitz** [comment]
We upload new Tailscale builds to Synology via a shared Google Drive folder and at some point in the future they magically appear updated in the Synology Package Center. (Assuming they pass Synology's review)

Or you can side load our builds.

**Comment by rncole** [comment]
Confirmed! Installed 1.21.56 and rebooted and everything is functional!  Closing.

Thanks @bradfitz!
