### ISSUE TITLE
No build binaries for latest synology release

### ISSUE THREAD

**Issue by ProfDrYoMan** [tailscale/tailscale#3763]
### What is the issue?

https://github.com/tailscale/tailscale-synology/releases/tag/v1.20.1
Binaries are missing for this latest release.

**Comment by bradfitz** [comment]
There was an upload error. Our release infrastructure needs to be taught to retry on those failures. @maisem is on it.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale-synology/releases/ is not going to host the Synology release SPKs any more.

Please use https://pkgs.tailscale.com/stable/#spks from now on. The 1.20.2 SPKs are there now.
