### ISSUE TITLE
wireguard-go memory pooling doesn't seem to work

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3765]
At 166fe3fb1220cc3cc35e65719d17d33d4d9e6bd5 .... and profiling tailscaled while sending ~13GB file through it ...

```
$ go tool pprof --alloc_space http://localhost:8383/debug/pprof/heap
Fetching profile over HTTP from http://localhost:8383/debug/pprof/heap
Saved profile in /home/bradfitz/pprof/pprof.tailscaled.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz
File: tailscaled
Type: alloc_space
Time: Jan 19, 2022 at 9:56am (PST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 39.13GB, 98.02% of 39.92GB total
Dropped 319 nodes (cum <= 0.20GB)
Showing top 10 nodes out of 54
      flat  flat%   sum%        cum   cum%
   12.73GB 31.90% 31.90%    12.73GB 31.90%  golang.zx2c4.com/wireguard/device.(*Device).PopulatePools.func1
```

Why is Wireguard allocating 1:1 with data passed through it?

The wireguard-go code looks like it's really trying hard to pool stuff. Is that not working?

cc @josharian

**Comment by josharian** [comment]
Do you have the full profile file still? Can you reproduce as needed?

**Comment by bradfitz** [comment]
I don't. I just ran a userspace tailscaled, run `nc -l -p 12345 | wc -c` and from another machine, `cat huge-file | nc $TAILSCALEIP 12345` and profiled it while it transferred data.

**Comment by bradfitz** [comment]
I did it again for you:

[heap.pprof.gz](https://github.com/tailscale/tailscale/files/7900349/heap.pprof.gz)

Numbers are smaller because I didn't wait for all the 13 GB file to pipe through nc.

**Comment by josharian** [comment]
I just re-discovered this in my inbox and looked into it. Here's what's happening. This line is allocating proportional to the amount of traffic passing through it:

https://github.com/tailscale/tailscale/blob/1e12a29806ec9b3aca4fb32b376bb2fa650e0770/wgengine/netstack/netstack.go#L573

The rampant allocation for netstack triggers the GC repeatedly. wireguard-go's buffers are stored in a sync.Pool. The GC starts emptying out the sync.Pool, so wireguard-go allocates new buffers, further aggravating GC pressure.

It is an accident that the wireguard-go allocations happen to approximately equal the traffic volume.

You can confirm this by running with GOGC=off.

The best fix here is to make netstack allocate less. wireguard-go could use something other than sync.Pool, but then we're stuck with an allocation strategy that is not responsive to GC in the ways one would want.

**Comment by bradfitz** [comment]
That is #2741. I spoke with @raggi about it the other day too.

The netstack folk in the recent community meeting said it should be possible to do without allocating but I couldn't figure out the lifetime of the packet buffers from the API/docs.

**Comment by DentonGentry** [comment]
Since this bug was filed we've updated to a later netstack which includes much of the performance work in the aforementioned community meeting, including reducing allocations.

**Comment by DentonGentry** [comment]
At this point I don't believe this issue is tracking anything further to do. We updated to a netstack release which addresses most of what was talked about in the 3/2022 community meeting.
