### ISSUE TITLE
FR: Add a QR code for mobile app downloads

### ISSUE THREAD

**Issue by mayakacz** [tailscale/tailscale#3776]
### What are you trying to do?

If I'm on a desktop, to install the iOS app, I navigate to a link for the app store but then can't download the app (though this might require me to be signed in?). On Android, I can trigger a download to my device if it's the same account I intend to use.
I have to separately open the app store on my device to find the app.

### How should we solve this?

We could use a QR code to direct users on their mobile devices to the app store page.

### Anything else?

Here's a terrible PM mockup

<img width="1026" alt="Screen Shot 2022-01-20 at 12 17 44" src="https://user-images.githubusercontent.com/15946341/150415958-8f83d3d5-8088-477b-a970-d7fd1ed46ee3.png">

**Comment by soniaappasamy** [comment]
We've got QR codes in the admin panel onboarding already, would be good to use them here too.

**Comment by rosszurowski** [comment]
We added this feature to the downloads page! Check it out on tailscale.com/download

**Comment by Cdaprod** [comment]
The ability to set QR to preform an action.

**Comment by DentonGentry** [comment]
@Cdaprod This issue is closed as completed. If you'd like to suggest a different feature which would use QR codes, please open a new feature request.
