### ISSUE TITLE
tailscale-synology v1.20.1 package installation blocked on DSM7 due to root privilege denial

### ISSUE THREAD

**Issue by herbygillot** [tailscale/tailscale#3782]
### What is the issue?

`tailscale-synology` package build for v1.20.1 for DSM7 works fine, but when attempting to install in DSM 7, the installation is blocked by this message:

<img width="685" alt="Screen Shot 2022-01-21 at 1 05 06 PM" src="https://user-images.githubusercontent.com/618376/150578833-21e7b4f4-a029-4bfa-a331-40fa9714c917.png">

### Steps to reproduce

1. Checkout https://github.com/tailscale/tailscale-synology
2. `make tailscale-release-amd64`
3. Attempt to install resulting DSM 7 package

### Are there any recent changes that introduced the issue?

🤷🏾‍♂️

### OS

Synology

### OS version

DSM 7.0.1-42218

### Tailscale version

1.20.1

**Comment by maisem** [comment]
@herbygillot `make tailscale-release-amd64` builds the release that is only installable via the Synology store. You should use `make tailscale-amd64` instead

**Comment by maisem** [comment]
We are actively working on having the Synology SPKs appear on https://pkgs.tailscale.com so that users don't have to manually generate these.

**Comment by herbygillot** [comment]
> @herbygillot `make tailscale-release-amd64` builds the release that is only installable via the Synology store. You should use `make tailscale-amd64` instead

Thank you @maisem - `make tailscale-amd64` indeed did the trick.

**Comment by herbygillot** [comment]
> We are actively working on having the Synology SPKs appear on https://pkgs.tailscale.com so that users don't have to manually generate these.

Nice, definitely looking forward to that.
