### ISSUE TITLE
ssh extremely slow after upgrade to 1.20.x

### ISSUE THREAD

**Issue by holongate** [tailscale/tailscale#3785]
### What is the issue?

After month of mostly seamless use, ssh connections became unresponsive after upgrading to 1.20.x from 1.18.2.
Connection appears to freeze for a minute at least, not even echoing typed characters nor honoring the ssh ~. escape command.

### Steps to reproduce

Update to latest tailscale version 1.20.
Downgrade to 1.18.2 restores its nominal behavior

### Are there any recent changes that introduced the issue?

Update of tailscale, no other change in the conf / os / DNS.

### OS

Linux

### OS version

Ubuntu 20.04.2

### Tailscale version

1.20.2

**Comment by bradfitz** [comment]
Without the "tailscale bugreport" output there's not much we can look at here.

**Comment by holongate** [comment]
Ah, sorry, didn't know that.
I uninstalled tailscale from all the nodes, so I guess you can close this issue.
