### ISSUE TITLE
Some applications very slow to launch after 'tailscale up'

### ISSUE THREAD

**Issue by holongate** [tailscale/tailscale#3786]
### What is the issue?

Following a downgrade to 1.18.2 from 1.20 because of #3785, I found some apps where very slow to launch (between 10-20s) instead of the normal sub-second delay.
Apps with the largest delay:
- firefox
- zotero
Kconsole seems ok, but a 'sudo -i' have a 10s delay before asking for a password...

Addition:

I now got lots of 'dns: error: context deadline exceeded' after a up --reset:
```
janv. 22 10:36:28 monolith tailscaled[976]: magicsock: disco: node [IoN2Z] d:5811341164003687 now using xx.xx.xx.xx:41641
janv. 22 10:43:57 monolith tailscaled[976]: dns: error: context deadline exceeded
janv. 22 10:43:57 monolith tailscaled[976]: dns: error: context deadline exceeded
janv. 22 10:44:02 monolith tailscaled[976]: dns: error: context deadline exceeded
janv. 22 10:44:02 monolith tailscaled[976]: dns: error: context deadline exceeded
janv. 22 10:44:02 monolith tailscaled[976]: [RATELIMIT] format("dns: error: %v")
janv. 22 10:44:13 monolith tailscaled[976]: [RATELIMIT] format("dns: error: %v") (2 dropped)
janv. 22 10:44:13 monolith tailscaled[976]: dns: error: context deadline exceeded
janv. 22 10:44:13 monolith tailscaled[976]: dns: error: context deadline exceeded
janv. 22 10:44:13 monolith tailscaled[976]: [RATELIMIT] format("dns: error: %v")
janv. 22 10:44:23 monolith tailscaled[976]: [RATELIMIT] format("dns: error: %v") (2 dropped)
janv. 22 10:44:23 monolith tailscaled[976]: dns: error: context deadline exceeded
...
```

Followed by:
```
janv. 22 10:38:30 monolith tailscaled[976]: magicsock: want call-me-maybe but endpoints stale; restunning
janv. 22 10:38:30 monolith tailscaled[976]: magicsock: STUN done; sending call-me-maybe to d:5811341164003687 [IoN2Z]
```
### Steps to reproduce

Not sure this is reproducible but after:
- upgrade from 1.18.2 to 1.20.x: apt install tailscale
- downgrade from 1.20.x back to 1.18.2: apt purge tailscale / apt install tailscale=1.18.2
- tailscale up

No purge / reboot / re-install solved the problem.
Only `tailscale down` restores the normal launch delay...

### Are there any recent changes that introduced the issue?

Not experienced on identical machines (OS/HW) that have not been upgraded to 1.20.

Possible configuration specific to this machine, this is the only one I ran `tailscale --operator myusername up` on to give it a try.
I since then issued a `--operator root` in an attempt to revert it.

### OS

Linux

### OS version

LTS 20.04.02

### Tailscale version

>1.18

**Comment by DentonGentry** [comment]
`janv. 22 10:44:13 monolith tailscaled[976]: dns: error: context deadline exceeded`
indicates that something went wrong in DNS config. You'd need to provide a `tailscale bugreport` at a time the problem was happening to be able to make progress on this.

**Comment by DentonGentry** [comment]
ETIMEDOUT
