### ISSUE TITLE
Tailscale on iOS and Android lost connection when using exit node after updating latest tailscale on VPS server.  

### ISSUE THREAD

**Issue by timmyvo** [tailscale/tailscale#3787]
### What is the issue?

Tailscale on iOS and Android lost connection when using exit node after updating latest tailscale on VPS server. Tailscale on windows computer works properly. 

### Steps to reproduce

Easily check with the current version app on Android 1.20.0 and iOS 1.20.1

### Are there any recent changes that introduced the issue?

Yes after updating tailscale on linux server to 1.20.2

### OS

Linux, iOS, Android

### OS version

Ubuntu

**Comment by timmyvo** [comment]
Update to this version version 1.21.43, Confirm It works again. But it still doesn't work when using private dns on Android. I have to turn private dns off. Compare to the old version 1.18, I think it still works with private dns turned on.

**Comment by DentonGentry** [comment]
> Compare to the old version 1.18, I think it still works with private dns turned on.

Private DNS did not work in 1.18 either, Android sets a StrictMode filter to block any socket contacting port 53.
https://github.com/tailscale/tailscale/issues/915#issuecomment-751706094

**Comment by bradfitz** [comment]
> Update to this version version 1.21.43, Confirm It works again.

Great, thanks! I'll close this bug.

Private DNS can be/is tracked elsewhere.
