### ISSUE TITLE
FR: Sort columns on machine listing on Admin page

### ISSUE THREAD

**Issue by gabefair** [tailscale/tailscale#3789]
### What are you trying to do?

I would like to sort the  devices by the column showing last seen online.

**Comment by DentonGentry** [comment]
Could I ask the goal of sorting by time last seen online?
To identify machines which have dropped out of contact?

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2537

Note in particular https://github.com/tailscale/tailscale/issues/2537#issuecomment-888442297
