### ISSUE TITLE
FR: Add Installation instructions for Alpine Linux

### ISSUE THREAD

**Issue by thiagowfx** [tailscale/tailscale#3790]
### What are you trying to do?

FR: Add "Alpine Linux" to https://tailscale.com/download/linux.

I would send a PR however I couldn't find the repository for your website, I am assuming it's private.

### How should we solve this?

Alpine Linux has a `tailscale` package: https://pkgs.alpinelinux.org/packages?name=tailscale

Instructions are:

1. Install Tailscale on Alpine Linux

```
# apk add tailscale
```

2. Use OpenRC to enable and start the service

```
rc-update add tailscale
rc-service tailscale start
```

3. Authenticate and connect your machine to your Tailscale network

```
tailscale up
```

4. You’re connected! You can find your Tailscale IPv4 address by running:

```
tailscale ip -4
```

### What is the impact of not solving this?

Users would have to figure this out by themselves.

Resolving this improves documentation.

### Anything else?

I confirm and have tested the instructions provided above work on Alpine Linux 3.15.

**Comment by thiagowfx** [comment]
For completeness: This is a follow-up of https://github.com/tailscale/tailscale/issues/230

**Comment by DentonGentry** [comment]
Thus far Tailscale has only documented the packages provided directly by Tailscale. For example the install process for FreeBSD / OpenBSD / macOS homebrew / OpenWRT / Enigma set top boxes / etc are not in Tailscale's knowledgebase because those projects supply their own packaging and the documentation for it.

At this point, as stated in #230, we are not planning to implement separate packages from those which Alpine supplies. It would just add confusion of which to use.

**Comment by DentonGentry** [comment]
Closing this as the tailscale package used on alpine is packaged by the Alpine project.

**Comment by FlorianHeigl** [comment]
An addendum for others like me - for LBU / diskless mode you need to __at the very least do an__ `# lbu ci /var/lib/tailscale/tailscaled.state`

I don't know tailscale well (now) and can't tell you if this will expire or cause any other auth issues. I can tell you that without you won't make it over the next reboot, and I can reboot and end up logged in.
Others can hopefully provide updates, and at some point there should be a doc page on the alpine wiki, then this issue would best point to it.
