### ISSUE TITLE
Tailscale server timeout when Ubuntu 20.04 desktop suspend

### ISSUE THREAD

**Issue by shingjan** [tailscale/tailscale#3791]
### What is the issue?

Ping/SSH to tailscale server on Ubuntu 20.04 desktop while it is suspended times out. Connections can be resumed after ubuntu wakes up. It seems similar to [issue@2458](https://github.com/tailscale/tailscale/issues/2458) but turned out not to be the case. Is this behavior expected as I understand tailscale should be run on Ubuntu server?

### Steps to reproduce

As mentioned above

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.20.2

### Bug report

BUG-a8c12f5fc4f81f7c130af606dcf94c76d351ebe42d2d5db9b2a699adfdf934d1-20220123083024Z-2fdc6731ed758183

**Comment by DentonGentry** [comment]
If the desktop system is suspended, I would not expect Tailscale to get a response from it. I mean, how could it?

There are technologies like Wake-on-LAN which can unsuspend a sleeping system, but they require the sender to be on the local LAN. They don't work over a wide area network, which is how Tailscale works.
