### ISSUE TITLE
System Freezes when AirVPN and Tailscale simultaneously running

### ISSUE THREAD

**Issue by truthsword** [tailscale/tailscale#3795]
I just updated to tailscale-ipn-setup-1.20.2 on a Win10 x64 machine, and I am getting network lockups that only resolve by restarting the PC. Here's what I am doing,

Fresh PC start with Tailscale running in tray and PC connected to router via Wi-Fi.
I start AirVPN client (Eddie) and connect.
Then I surf with browser for 10-15 minutes, after which, I select an alternate VPN server through Eddie.

When I do that, my network icon reverts to a globe, having lost connection to the router. When I right-click that to "Open Network & Internet settings", the settings window opens up and is blank. I can do nothing. Forcing a shutdown of the Tailscale service does not work.

I wish I had more specific info. The has occurred 4-5 times after updating to 1.20.2.
I see nothing in Event Viewer. 

I rolled back to 1.20.1 and will recheck.

**Comment by DentonGentry** [comment]
I'm sorry but having multiple VPN products installed and active at the same time is just not going to work well. Even if a stable configuration is found, a subsequent update of either product can break it. They fight over every resource: routing table, firewall rules, DNS settings, etc.

**Comment by DentonGentry** [comment]
I think this issue when closed will be as discoverable for people searching for AirVPN and Tailscale as it is while open. I don't expect to be able to resolve this, closing.
