### ISSUE TITLE
FR: Add key type to the key keys API call

### ISSUE THREAD

**Issue by lewisstevens1** [tailscale/tailscale#3796]
### What are you trying to do?

Delete the old Auth keys using the tail scale API key.

Currently, if I make the call to delete the keys by looping over the list-keys API call, there is no visible way to filter if they are API keys or Auth keys.

### How should we solve this?

Return whether a key is an Auth key or an API key I think it should be ordered in such a way that index 0 is the newest, this way we can use it for rotating keys easier.

https://github.com/tailscale/tailscale/blob/main/api.md#get-apiv2tailnettailnetkeys---list-the-keys-for-a-tailnet

### What is the impact of not solving this?

I am not, we are just leaving the keys building up.

**Comment by DentonGentry** [comment]
Keys now have a prefix identifying what they are:
- tskey-auth-... for an authkey
- tskey-api-... for an API key

This went live on September 30, 2022. Older keys with the undifferentiated `tskey-...` prefix will exist for up to 90 days after that date, so about 60 days left. After that, you can use the prefix.
