### ISSUE TITLE
FR: list subnets advertised in API device list

### ISSUE THREAD

**Issue by lewisstevens1** [tailscale/tailscale#3797]
### What are you trying to do?

I would like to be able to list all the devices and maybe return a value such as a hostname / if it's advertising subnets.
This way I will be able to pass the device to the second command.

Also, I would like to be able to disable key expiry, via the API with the output of the first command.

### How should we solve this?

Add this via the API

### What is the impact of not solving this?

The server will keep expiring (everything has to be automated)

**Comment by DentonGentry** [comment]
Setting a device to never expire using the API is being tracked in https://github.com/tailscale/tailscale/issues/2418 (and is currently being worked on).

> I would like to be able to list all the devices and maybe return a value such as a hostname / if it's advertising subnets.
This way I will be able to pass the device to the second command.

You're asking for a different API call to return the hostname and whether it is advertising subnets? Something more than https://github.com/tailscale/tailscale/blob/main/api.md#device-get ?

**Comment by lewisstevens1** [comment]
Hello @DentonGentry, thankyou #2418 will cover that side of this. 

In regards to whether it is advertising subnets, yes, we need to be able to find which is the latest Tailscale instance that has been created that is currently active.

We don't seem to have a way to tell that:

- Filter if the computer is currently online (we have to take current time and iterate if any were active in the last 5 mins etc which can get quite confusing, so when we do launches of new instances we are not 100% sure if someone is using Tailscale at all).

- Whether it is the tailscale instance other than our computers (which the only way I can think of checking if if its advertising subnets) I have tried taking `advertisedRoutes` and trying to convert the list into a boolean, but I guess if there is a way to maybe filter by tags that may be a better solution.


![Screenshot 2022-01-26 at 11 25 57](https://user-images.githubusercontent.com/10538348/151155443-2d9a7ef6-d02a-48ea-9d8b-52c3691a5c7b.jpg)

**Comment by DentonGentry** [comment]
@lewisstevens1 you might also look at the output of `tailscale status --json` on the device.

**Comment by DentonGentry** [comment]
Regarding subnets advertised: does https://github.com/tailscale/tailscale/blob/main/api.md#device-routes-get do what is needed?

**Comment by DentonGentry** [comment]
Closing as https://github.com/tailscale/tailscale/blob/main/api.md#device-routes-get appears to provide the needed functionality, please reopen if not.
