### ISSUE TITLE
Routes not added on Ubuntu 18.04

### ISSUE THREAD

**Issue by mausch** [tailscale/tailscale#3798]
### What is the issue?

A coworker running Ubuntu 18.04 isn't getting the advertised routes added when starting Tailscale with `sudo tailscale up --accept-routes`.

According to the logs tailscale apparently recognises the routes, not sure if if tries to add them?
```
Jan 24 12:16:45 bart-Precision-Tower-5810 tailscaled[1828]: monitor: RTM_NEWROUTE: src=, dst=172.16.0.0/16, gw=, outif=4, table=52
Jan 24 12:16:45 bart-Precision-Tower-5810 tailscaled[1828]: monitor: RTM_NEWROUTE: src=, dst=10.1.0.0/16, gw=, outif=4, table=52
Jan 24 12:16:45 bart-Precision-Tower-5810 tailscaled[1828]: monitor: RTM_NEWROUTE: src=100.108.243.107/0, dst=100.108.243.107/32, gw=, outif=4, table=255
```

(the route I'm interested in is for 172.16.0.0/16)

but then the route doesn't seem to be added:

```
$ ip route

default via 192.168.1.254 dev eth1 proto dhcp metric 100 
169.254.0.0/16 dev eth1 scope link metric 1000 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.248 metric 100 
```

whereas on my working Ubuntu 20.04 box:

```
$ ip route

default via 192.168.0.1 dev enp0s25 proto dhcp metric 100 
10.1.0.0/16 via 172.16.21.129 dev tun0 metric 101 
52.211.66.2 via 192.168.0.1 dev enp0s25 
169.254.0.0/16 dev enp0s25 scope link metric 1000 
172.16.0.0/16 via 172.16.21.129 dev tun0 metric 101 
172.16.21.128/25 dev tun0 proto kernel scope link src 172.16.21.225 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.18.0.0/16 dev br-efd3f64f3a84 proto kernel scope link src 172.18.0.1 
172.19.0.0/16 dev br-b01d9080db9c proto kernel scope link src 172.19.0.1 
172.31.0.0/16 via 172.16.21.129 dev tun0 metric 101 
192.168.0.0/24 dev enp0s25 proto kernel scope link src 192.168.0.3 metric 100 
```

both boxes running the same version:

```
$ tailscale version

1.20.2
  tailscale commit: 312750ddd288cf4073cfaef56a45102b9c1e8421
  other commit: 2c164d9c7443e2f3014fa54ea45e946b35152680
  go version: go1.17.6-tse44d304e54
```

I tried downgrading to 1.18.0 but no joy.

Other boxes running Windows work fine.

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.20.2

### Bug report

BUG-96f66b276119ce1c2befee123f39677b0fe49047df8bbba55cec8af0204e2710-20220124124347Z-055931942d8bc88f

**Comment by DentonGentry** [comment]
Just to check: was the 1.18.x box started with `tailscale up --accept-routes`
(I think so, or you wouldn't have seen the RTM_NEWROUTE messages)

**Comment by mausch** [comment]
Hi, the logs I included above are for 1.20.2

But anyway yes I always start it with `--accept-routes`

**Comment by DentonGentry** [comment]
A bit later we see:
```
2022-01-24 10:06:21.317678197 +0000 UTC: monitor: RTM_NEWROUTE: src=, dst=, gw=192.168.1.254, outif=2, table=254
2022-01-24 10:06:21.318967488 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=, gw=192.168.1.254, outif=2, table=254
2022-01-24 10:06:21.319157541 +0000 UTC: monitor: RTM_NEWROUTE: src=, dst=, gw=fe80::628d:26ff:fe35:7396, outif=2, table=254
2022-01-24 10:06:21.319240728 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=, gw=fe80::628d:26ff:fe35:7396, outif=2, table=254
```

as well as:
```
2022-01-24 10:04:59.616745101 +0000 UTC: router: disabling tunneled IPv6 due to system IPv6 config: disable_ipv6 is set
```

So this may be a case where the IPv4 routes are being removed on a failure which is IPv6 specific.

**Comment by mausch** [comment]
Thanks! I enabled ipv6 and upgraded again to 1.20.2 and it seems to work now. Kinda weird no?

However when I run `ip route` I still don't see a route for 172.16.0.0/16... shouldn't it appear there?

Also the logs don't say anything about RTM_NEWROUTE now... 🤷‍♂️

**Comment by bradfitz** [comment]
ip route show table all

**Comment by mausch** [comment]
Thanks, feel free to close this.
