### ISSUE TITLE
OpenBSD cannot use non-tunX names for tun interfaces

### ISSUE THREAD

**Issue by paulsmith** [tailscale/tailscale#38]
On a Debian stretch box, Tailscale failed to start after installing following [the .deb instructions](https://tailscale.com/kb/1026/install-deb).

Specifically, it failed after running the `systemctl start` step (which silently succeeds), when `relaynode` doesn't appear in the process list per `ps`.

Looking at log output, saw:

```
CreateTUN: invalid argument
Error starting wireguard engine: invalid argument 
```

On this machine, there is already a `wg0` interface from a previous Wireguard non-Tailscale installation.

Upon manually running `relaynode` (i.e., not through systemctl) with `--tun=wg1` (picked arbitrary unused name), Tailscale starts up successfully.

It appears that the systemd service file hard-codes `wg0` in the invocation; I edited the file but am conscious that a future update will clobber it.

**Comment by bradfitz** [comment]
We'd previously discussed naming the interface `tailscale0` or something. I forget whether anybody had arguments against that. Perhaps just that it would look less like WireGuard?

@apenwarr, @crawshaw, @danderson?

**Comment by crawshaw** [comment]
We should definitely name it something other than wg0. `tailscale0` works for me.

**Comment by danderson** [comment]
tailscaled already calls it `ts0`, so this'll get fixed once we get rid of relaynode.

**Comment by bradfitz** [comment]
Should we make it longer (like we did the CLI/daemon names) for explicitness? If users are typing them by hand, things have already gone very poorly.

**Comment by danderson** [comment]
Fine by me. The openbsd support PR #36 contains a flagification of the interface name too, but we can default it to tailscale0 if we want.

**Comment by martinbaillie** [comment]
I'm not entirely sure you can influence the name of TUN/TAP devices on OpenBSD. I couldn't when I tried the other day which is why I went for the flagification in the PR. 

FreeBSD it looks possible to rename with a syscall post-creation but may be more hassle than it's worth.

**Comment by martinbaillie** [comment]
Bit more digging and yeh I think OpenBSD will be the one that makes the standard `tsN`/`tailscaleN` interface naming hard:
https://github.com/tailscale/wireguard-go/blob/master/tun/tun_openbsd.go#L117

The WireGuard tun code _does_ use that rename syscall for FreeBSD mind you:
https://github.com/tailscale/wireguard-go/blob/master/tun/tun_freebsd.go#L356

**Comment by danderson** [comment]
Renamed this to reflect that OpenBSD is the remaining problem OS. On linux and freebsd, we now default to tailscale0, which should be conflict-free.

For OpenBSD, I think we have two basic choices: stick to the flag we have now and just tell openbsd users "hey, set this to something that doesn't conflict for your system", or have a fallback where we let the kernel assign us a tun interface name, and then plumb that through to all the places that care about the interface name (which I think we already do anyway).

@martinbaillie WDYT? Is "you have to configure this yourself" acceptable to openbsd users, or should we try doing something that works autonomously?

**Comment by martinbaillie** [comment]
I think BSD users are comfortable with a bit of up front config, but autonomously is more in-keeping with Tailscale's "just works" feeling. I don't mind looking at this in the coming days to try to make the latter happen.

-------- Original Message --------
