### ISSUE TITLE
SSH over Tailscale

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3802]
Since all packets sent over Tailscale have an associated identity thanks to Tailscale, a lot of authentication work can be simplified. Notably, SSH could be made much less tedious by taking advantage of your TCP connection's identity. The [cmd/tsshd](https://github.com/tailscale/tailscale/tree/main/cmd/tsshd) was the start of these experiments.

This is a tracking bug for more such SSH work.

**Comment by DentonGentry** [comment]
Tailscale SSH feature launched: https://tailscale.com/blog/tailscale-ssh/

I imagine we should have new issues tracking future feature additions.
