### ISSUE TITLE
using CLI on macOS

### ISSUE THREAD

**Issue by errordeveloper** [tailscale/tailscale#3805]
### What is the issue?

I have installed the Tailscale app from the App Store, and wanted to use a CLI with it also. I tried installing it from Homebrew, which kind of worked, but I was getting version mismatch warnings (and errors in some cases), albeit Homebrew was ahead by just one patch release.

I did quickly find out that `/Applications/Tailscale.app/Contents/MacOS/Tailscale` can be used quite easily, however I wish it was somehow easier to discover, e.g. a menu option that either installs CLI or tells you how to do it (in case alias is the only way) could be quite helpful!

Setting an alias worked for me, but I tend to prefer symlinks over aliases normally. Is this something to do with how signed binaries work on macOS?

### Steps to reproduce

This works:
```
$ /Applications/Tailscale.app//Contents/MacOS/Tailscale status
100.108.82.126  wroom4               errordeveloper@ macOS   -
100.73.99.10    wroom3               errordeveloper@ macOS   offline
$
```
But this weirdly blocks without any error or anything:
```
$ sudo ln -s /Applications/Tailscale.app//Contents/MacOS/Tailscale /usr/local/bin/tailscale
$ /usr/local/bin/tailscale
^C
$
```

### OS

macOS

### OS version

macOS Big Sur

### Tailscale version

1.20.1

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2553

Though it would be appreciated, isn't really feasible for the macOS app: it is run as a Network Extension which means it is restricted to a sandbox, it cannot access the wider filesystem.

**Comment by errordeveloper** [comment]
thanks @DentonGentry, I looked for 'macOS CLI' but got several pages of results...

**Comment by herbygillot** [comment]
If you'd like, you can also install Tailscale through [MacPorts](https://ports.macports.org/port/tailscale/).  This is **not** an official channel, but a 3rd-party package manager in the same way as Homebrew.  That will give you Tailscale as a directly accessible CLI:

```bash
$ port info tailscale
tailscale @1.20.2 (net)

Description:          The easiest, most secure way to use WireGuard and 2FA. A secure network that just works. Zero config VPN. Installs on any device in minutes, manages firewall rules for you, and works from anywhere.
Homepage:             https://tailscale.com

...

$ which tailscale
/opt/local/bin/tailscale

$ tailscale status
...
100.101.102.103 ("hello")            services@    linux   -
...
```

**Comment by 3bars** [comment]
creating an alias for tailscale may provide the results you're looking for. 
`alias tailscale='/Applications/Tailscale.app/Contents/MacOS/Tailscale'`

**Comment by jfima** [comment]
> creating an alias for tailscale may provide the results you're looking for. `alias tailscale='/Applications/Tailscale.app/Contents/MacOS/Tailscale'`

best solution for me! thanks

**Comment by corneliusroemer** [comment]
I installed using `brew install --cask tailscale` on a headless M2 mini but the above alias doesn't work. I get:

```
$ /Applications/Tailscale.app/Contents/MacOS/Tailscale
To run the Tailscale macOS GUI, use "Tailscale rungui"


```

And this hangs indefinitely

```
$ /Applications/Tailscale.app/Contents/MacOS/Tailscale status
^C

```

**Comment by aaomidi** [comment]
If you've installed it with brew, then you don't need the alias at all.

**Comment by hotzen** [comment]
I put this into my dotfiles `.zshrc`, to use e.g. `tailscale status`

```
if [[ "$OSTYPE" == "darwin"* ]]; then
  alias tailscale='/Applications/Tailscale.app/Contents/MacOS/Tailscale'
fi
```
