### ISSUE TITLE
RDP doesn't work on tailscale network

### ISSUE THREAD

**Issue by olamrg** [tailscale/tailscale#3806]
### What is the issue?

LK"I

Hi There

I'm using tailscale 1.20.1.
installed it on two windows desktop. (windows 10 both)
i can ping between these two machines using the new VPN network
BUT , i cant connect with RDP.
turned off firewall on both machines. (and i can connect in RDP to one machine within the target network)

please help

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.20.1

**Comment by DentonGentry** [comment]
You'd need to supply some kind of information to let us pull up the account, ideally a bugreport right after you try to connect to RDP: hold shift and right-click on the Tailscale icon in the taskbar, select "Debug > Bug Report"

**Comment by olamrg** [comment]
Bugreport marker created:

	BUG-924782650a56efa807bd1e0b10bfc01fcfc388d4fff37ce457673bf610dd91ae-20220126113707Z-7b351e0962800536

Email that to support@tailscale.com with a description of the problem.

**Comment by HarelAshwal** [comment]
any news on this? did you figured it out?

**Comment by bradfitz** [comment]
You have two machines. One is in state "NeedsLogin" so you'll need to finish setting that one up. And the other is connected to the control plane but can't reach any DERP server. It seems like something is preventing it from reaching the internet. Is it behind some firewall?

**Comment by DentonGentry** [comment]
No actionable information.
