### ISSUE TITLE
Can't ping peer back

### ISSUE THREAD

**Issue by estimadarocha** [tailscale/tailscale#3807]
### What is the issue?

Finally we have a package working on enigma2 devices #1291. But now we are facing a routing problem if i am seing things right!

If we bring tailscale up on one of those devices i can acess it from my PC but the contrary is not possible! any help will be very appreciated!

thanks

### OS

Linux

### OS version

enigma2

### Tailscale version

1.20.2

**Comment by DentonGentry** [comment]
You'll need to provide information to let us troubleshoot, we can't guess just based on this. Ideally this would be trying to ping, seeing it fail, and immediately running "tailscale bugreport"

**Comment by estimadarocha** [comment]
BUG-9fe76f8e60218fcc552af87c2ad4bc6c206ddc4ae67ea35574e516ea25d556c6-20220125153610Z-9b8c0699ef942f3a

**Comment by DentonGentry** [comment]
The enigma keeps seeing a DELROUTE originating from Linux, and responding to it.

```
2022-01-25 15:52:23.253363455 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=, gw=192.168.1.254, outif=2, table=254
2022-01-25 15:52:23.254890913 +0000 UTC: LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={eth0:[192.168.x.y/24 2001:8a0:g:h:i:j:k:l/64]} v4=true v6=true}
2022-01-25 15:52:23.25569033 +0000 UTC: Rebind; defIf="", ips=[]
2022-01-25 15:52:23.255785122 +0000 UTC: magicsock: closing connection to derp-8 (rebind-default-route-change), age 16m59s
2022-01-25 15:52:23.255898705 +0000 UTC: magicsock: 0 active derp conns
2022-01-25 15:52:23.255950913 +0000 UTC: magicsock: starting endpoint update (link-change-major)
2022-01-25 15:52:23.256047372 +0000 UTC: health("overall"): error: not connected to home DERP region 8
2022-01-25 15:52:23.25615683 +0000 UTC: magicsock: adding connection to derp-8 for home-keep-alive
2022-01-25 15:52:23.256300163 +0000 UTC: magicsock: 1 active derp conns: derp-8=cr0s,wr0s
2022-01-25 15:52:23.256472288 +0000 UTC: derphttp.Client.Recv: connecting to derp-8 (lhr)
```

**Comment by estimadarocha** [comment]
anyway to solve this? what could it be?

**Comment by estimadarocha** [comment]
root@gbue4k:~# ip route
default via 192.168.1.254 dev eth0
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.70
root@gbue4k:~# ip rule
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default

root@gbue4k:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 90:98:64:01:5A:AB
          inet addr:192.168.1.70  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1398 errors:0 dropped:171 overruns:0 frame:0
          TX packets:523 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:443918 (433.5 KiB)  TX bytes:90738 (88.6 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:43 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5540 (5.4 KiB)  TX bytes:5540 (5.4 KiB)

**Comment by estimadarocha** [comment]
Just a few more details about running environment:

Linux/arm 4.1.20-1.9

Since i can't see any routes/rules created by tailscale could this be related to any missing module on kernel build?

https://github.com/oe-alliance/oe-alliance-core/blob/5.0/meta-brands/meta-gigablue/recipes-linux/linux-gigablue-4.1.20/gb7252/defconfig

**Comment by estimadarocha** [comment]
this is the starting lines from the command line:

root@gbue4k:~# tailscaled -port 4434 -tun userspace-networking
logtail started
Program starting: v1.20.2-t312750ddd-g2c164d9c7, Go 1.17.6-tse44d304e54: []string{"tailscaled", "-port", "4434", "-tun", "userspace-networking"}
LogID: fd0754968161328c12f1e89df33106f0c82e41bfdcec17a7e964529463140aa5
logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.Read /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
wgengine.NewUserspaceEngine(tun "userspace-networking") ...
dns: using dns.noopManager
link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[192.168.1.70/24 2001:8a0:de65:ea00:9298:64ff:fe01:5aab/64]} v4=true v6=true}
magicsock: disco key = d:e737bfe82dd4cd71
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
Clearing router settings...
Starting link monitor...
Engine created.
netmap packet filter: (not ready yet)
Start
using backend prefs
created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
got initial portlist info in 0s
control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"fd0754968161328c12f1e89df33106f0c82e41bfdcec17a7e964529463140aa5","OS":"linux","OSVersion":"Other; kernel=4.1.20-1.9","DeviceModel":"gbue4k","Hostname":"gbue4k","GoArch":"arm","Services":[{"Proto":"tcp","Port":21,"Description":"vsftpd"},{"Proto":"tcp","Port":22,"Description":"dropbear"},{"Proto":"tcp","Port":23,"Description":"telnetd"},{"Proto":"tcp","Port":80,"Description":"enigma2"},{"Proto":"tcp","Port":111,"Description":"rpcbind"},{"Proto":"tcp","Port":445,"Description":"smbd"},{"Proto":"tcp","Port":2049},{"Proto":"tcp","Port":3702,"Description":"wsdd"},{"Proto":"tcp","Port":8001,"Description":"enigma2"},{"Proto":"tcp","Port":8002,"Description":"inetd"},{"Proto":"tcp","Port":8554,"Description":"enigma2"},{"Proto":"tcp","Port":33317},{"Proto":"tcp","Port":34748,"Description":"rpc.mountd"},{"Proto":"tcp","Port":35518,"Description":"rpc.mountd"},{"Proto":"tcp","Port":38717,"Description":"rpc.mountd"},{"Proto":"tcp","Port":40061,"Description":"rpc.statd"},{"Proto":"tcp","Port":46044,"Description":"rpc.mountd"},{"Proto":"tcp","Port":46692,"Description":"rpc.statd"},{"Proto":"tcp","Port":54547,"Description":"rpc.mountd"},{"Proto":"tcp","Port":58003,"Description":"rpc.mountd"},{"Proto":"tcp","Port":58968}]}
Backend: logs: be:fd0754968161328c12f1e89df33106f0c82e41bfdcec17a7e964529463140aa5 fe:
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
health("overall"): error: state=NeedsLogin, wantRunning=false
wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
monitor: RTM_NEWROUTE: src=, dst=2600:1f14:436:d604:5997:401e:422:edae/128, gw=fe80::ce19:a8ff:fead:2dff, outif=2, table=254
netmap packet filter: (not ready yet)
logtail: dialed "log.tailscale.io:443" in 229ms
control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"fd0754968161328c12f1e89df33106f0c82e41bfdcec17a7e964529463140aa5","OS":"linux","OSVersion":"Other; kernel=4.1.20-1.9","DeviceModel":"gbue4k","Hostname":"gbue4k","GoArch":"arm","Services":[{"Proto":"peerapi-dns-proxy","Port":1}]}
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:new
monitor: RTM_DELROUTE: src=, dst=2001:8a0:de65:ea00::1/128, gw=, outif=2, table=254

**Comment by DentonGentry** [comment]
What `tailscaled` cannot tell us is where did this come from:
```
monitor: RTM_DELROUTE: src=, dst=2001:8a0:de65:ea00::1/128, gw=, outif=2, table=254
```

Something, somewhere on the system deleted the 2001:8a0:de65:ea00::1/128 route. We've also seen the IPv4 nexthop route being removed:
```
2022-01-25 15:52:23.253363455 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=, gw=192.168.1.254, outif=2, table=254
```

Identifying where that is coming from would be the next step.

**Comment by estimadarocha** [comment]
@DentonGentry what can i do to identify it?

Don't you think thats not normal can't see routes or rules or anything related to tailscale0 anywhere?

The possibility of missing kernel modules os out off equation?

**Comment by estimadarocha** [comment]
new update:

i was using -tun userspace-networking on tailscaled args with that option removed now i can ping machine to machine. is this normal?

**Comment by bradfitz** [comment]
> i was using -tun userspace-networking on tailscaled args with that option removed now i can ping machine to machine. is this normal?

Yes. In userspace mode, the kernel & the kernel's routing tables are completely unaware of Tailscale, so you can't use the Tailscale network through the kernel.

**Comment by DentonGentry** [comment]
I think this is resolved.
