### ISSUE TITLE
cmd/tailscale: tailscale up --operator= doesn't reset operator

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3808]
The `up --operator=` flag was meant to be a little implicit to be less annoying, but it's too magic right now.

Even explicitly mentioning it and setting it to an empty value doesn't reset it. Likewise `--reset`:

```
$ go run ./cmd/tailscale up --operator=
$ go run ./cmd/tailscale up --reset
$ go run ./cmd/tailscale debug prefs
{
....
        "OperatorUser": "bradfitz",
        "Config": {
```

**Comment by bradfitz** [comment]
Use your actual username to see.

It does seem that `--reset` got fixed, but the explicitly-empty bug remains:

```
bradfitz@tsdev:~/src/tailscale.com$ go run ./cmd/tailscale debug prefs | jq .OperatorUser
"bradfitz"
bradfitz@tsdev:~/src/tailscale.com$ go run ./cmd/tailscale up --operator=
bradfitz@tsdev:~/src/tailscale.com$ go run ./cmd/tailscale debug prefs | jq .OperatorUser
"bradfitz"
bradfitz@tsdev:~/src/tailscale.com$ go run ./cmd/tailscale up --reset
bradfitz@tsdev:~/src/tailscale.com$ go run ./cmd/tailscale debug prefs | jq .OperatorUser
null
```

(Tested at 69b535c01fe.)

**Comment by Soypete** [comment]
As it stands if ```--reset``` is not called and the operator is blank then it defaults to the user
https://github.com/tailscale/tailscale/blame/69b535c01feb1066a92670d400afe870aca02b20/cmd/tailscale/cli/up.go#L853

**Comment by Soypete** [comment]
https://github.com/tailscale/tailscale/pull/4795
adding tests to capture fix

**Comment by Soypete** [comment]
let comment in the PR. I find that we need to change cli flag functionality to address this issue

**Comment by bradfitz** [comment]
@Soypete, I've added a failing test you can use in your PR to test your fix:

https://github.com/tailscale/tailscale/commit/64bd0fc320fcd7a708bc290991def919895e53db

No other test changes or flag default changes should be required.

You should only need to modify `applyImplicitPrefs`, probably passing in a `flag.FlagSet` and having it check whether `--operator` was explicit set in the flagset.
