### ISSUE TITLE
Synology 1.20.2 doesn’t have working options page

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#3811]
### What is the issue?

On my Synology DS918+, I side-loaded 1.18 and was able to successfully log in and configure it to be an exit node.

I side-loaded 1.20.2 and assumed it worked. Earlier today it wasn’t responding to pings so I went into the Package Manager and manually stopped and restarted it, and it started responding to pings. I then clicked the “Open” button, intending to check the configuration and got to the url

synologyhost:5000/webman/3rdparty/Tailscale/

which gave me a Synology 404.

Given that I could configure a side-loaded 1.18, I don’t think this is a side-load vs non-side-load issue.

In any case, I can’t configure Tailscale on my Synology.

### Steps to reproduce

Side-load 1.20.2 on top of 1.18?

### Are there any recent changes that introduced the issue?

It’s hard to say.

The history here is:

- Have the Synology on 7.0.1-42218
- Install Tailscale 1.18, and configure it, so the configuration definitely worked
- Install Tailscale 1.20.2 (though I didn’t fully check it)
- Install Synology Version: 7.0.1-42218 Update 2 which caused a reboot I’m sure
- Still don’t verify Tailscale working
- Realize Tailscale isn’t responding via LTE but is responding when I’m inside my house
- Manually stop and restart Tailscale
- Realize that the config page is 404

### OS

Synology

### OS version

Version: 7.0.1-42218 Update 2

### Tailscale version

1.20.2

**Comment by bradfitz** [comment]
This was a bug in our recent Synology packaging. The permissions are wrong on the `index.cgi` file. Meanwhile you can use the unstable builds (https://pkgs.tailscale.com/unstable/) until we release new stable builds.

**Comment by avidrissman** [comment]
I can confirm that 1.21.26-210267 does correctly allow the options page to be accessed.

**Comment by DentonGentry** [comment]
1.20.3 should appear at https://pkgs.tailscale.com/stable/#spks shortly
https://github.com/tailscale/tailscale/releases/tag/v1.20.3
