### ISSUE TITLE
DNS Stuck on 100.100.100.100

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#3817]
### What is the issue?

I'm using custom DNS and not magic DNS, why is the /etc/resolv.conf stuck at 100.100.100.100? It used to show the IP address of the servers set.

### Steps to reproduce

Set custom DNS. Go on Tailnet, see that /etc/resolv.conf is set to 100.100.100.100 instead of the 192.168.2.100.

### OS

MacOS

### OS version

Monterey

### Tailscale version

1.20.2

**Comment by iluvatyr** [comment]
I dont know the answer.. have a question myself:

"see that /etc/resolv.conf is set to 100.100.100.100 instead of the 192.168.2.100"

the local /etc/resolv.conf on your machine?

**Comment by vysecurity** [comment]
No, the custom DNS servers I set.

**Comment by Kinghack** [comment]
same issue here and observed from android/iPad/Mac .

**Comment by hendryque** [comment]
Same issue, Tailscale is ignoring DNS servers on all devices (iOS, Mac) and uses 100.100.100.100 to resolve DNS queries.

**Comment by DentonGentry** [comment]
To fix a number of issues with exit nodes and DNS, the 1.20 release will forward DNS queries to the exit node via DNS-over-HTTPS. To do that, it needs to be in the path of DNS queries and this likely is what resulted in seeing 100.100.100.100 as the DNS server.

If you are sure you always want 192.168.2.100 as the DNS server, it seems like the Tailscale DNS features could be turned off altogether in https://login.tailscale.com/admin/dns and just leave DNS set locally.

**Comment by vysecurity** [comment]
What it doesn’t solve is that we want everyone to use 1.1.1.1 when using
Tailscale, and when it’s not using Tailscale we want everyone to use their
local DNS.

**Comment by bradfitz** [comment]
Without the exact DNS settings or the account details (a Tailscale IP or a `tailscale bugreport`), there's not much we can do to help here.

It all depends on your system (OS/version, etc) & specific DNS settings & whether an exit node is in use or not.

**Comment by vysecurity** [comment]
It only used to use 100.100.100.100 when MagicDNS was on. But now it sticks
that as DNS regardless. I think what everyone’s saying is the old version
where you could push any DNS to all servers connected to Tailscale was
better. They don’t prefer a 100.100.100.100 to proxy traffic to the defined
DNS servers.


Maybe there can be an option to use 100.100.100.100 if you want. If you
don’t want, it’ll just use whatever DNS you specify, directly over an exit
node it set, or direct from the network or exit node isn’t set.

**Comment by bradfitz** [comment]
Again, without account details or a bug report, we can't look into what's happening.

But it's quite likely this is all by design. The decision on how to configure the host operating system's DNS settings vary based on a bunch of things that are configured on your tailnet, on the node, and the version of the host OS.

There are many more tailnet DNS settings than just "MagicDNS on". e.g. Override Local DNS, Split DNS, etc.

Feel free to write in to support with account details and a bug report. For now I'm going to close this until there's something actionable for us to do. There's nothing for me to investigate or fix at this point.

**Comment by luna-ts** [comment]
Bump. I also have my DNS resolver behind a tailscale subnet, and use an exit node. This used to work, but now I can reach any internal services while using the exit node. Please change the behavior back or add a function to manually overwrite this new behavior!

**Comment by sanfx** [comment]
I am also facing this issue. i.e. not Magic DNS, even if I add custom dns , and I try to override dns the /etc/resolv.conf is still set to `nameserver 100.100.100.100`

**Comment by ctermiii** [comment]
same issus, magic dns set to false but the /etc/resolv.conf is still set to nameserver 100.100.100.100

**Comment by bradfitz** [comment]
We don't track closed bugs. Please open new bugs with details or email support@.
