### ISSUE TITLE
Lots of "[unexpected] duplicate HostInfo" in logs

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#382]
Our duplicate hostinfo filtering seems to not be working terribly well. We're generating so many duplicates at HEAD that the logger rate-limiting kicks in and shuts it up.

**Comment by apenwarr** [comment]
See, this is why I usually write panic() instead of [unexpected] :)

On Wed, May 13, 2020 at 6:42 PM Dave Anderson <notifications@github.com> wrote:
>
> Our duplicate hostinfo filtering seems to not be working terribly well. We're generating so many duplicates at HEAD that the logger rate-limiting kicks in and shuts it up.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by bradfitz** [comment]
Fixed by 91d95dafd2dfec537ff12628630fea732a8c910c
