### ISSUE TITLE
Try to open the host firewall for magicsock on linux

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3824]
### What is the issue?

On linux, we don't try to open port 41641 for magicsock, partly because it's unnecessary for easy<>easy NAT traversal, and partly because the magicsock port can roam on rebind to another number, so we'd have to play some dicey firewall whackamole.

However, not opening the firewall breaks one NAT traversal case that should be a slam dunk:
 - server behind a Hard NAT
 - client behind a NAT with UPnP support
 - client machine has a stateful host firewall (e.g. ufw)

This should be a trivial<>hard combination, because UPnP makes the client side NAT disappear. But, the host firewall is still there, and will eat disco probes coming from the hard side, because they come from a surprising source port that the client hasn't communicated with. It _would_ communicate with it if the disco probe made it to tailscaled, and that would immediately get a working p2p link, but we can't get past the stateful firewall, so we never discover that trivially feasible path.

This makes what should be a trivial<>hard NAT case degrade back into easy<>hard, which you'll recall has no easy solutions for us right now (the bday paradox is infeasible in practice because of shallow session tables on routers). IOW, something that really ought to work amazingly well, doesn't :(

This _does_ work on Windows, because on Windows we talk to the WFP (firewall framework), and tell it to allow all UDP to our cryptographically strong process identity, so all inbound traffic just works regardless of how we rebind over time.

On linux, we can't do that, because netfilter has no way to ask what process is about to receive the packet, if it's allowed to proceed. The only thing we could implement would be to open up the specific port numbers we're using, and dynamically reconfigure the firewall every time we rebind magicsock and roam to a new port.

This is possible, but risky: if tailscaled crashes or stops without the opportunity for cleanup, that open port will stick around for ever. We have `tailscaled --cleanup` running for this automatically on stop for systemd-based distros, maybe that's enough?...

A more horrible alternative, for situations where we have network admin powers on the system (which we need anyway for firewall opening), would be to listen on a raw socket and attach an ebpf program to it that filters only traffic destined to tailscaled, and whose header contains the disco magic number. That would give us an extra receive funnel of all inbound disco traffic, before it ever hits netfilter. That way, we could grab those disco packets, use them to learn of a new usable endpoint, and punch our way out without having to imprecisely open the host firewall.

Neither option is particularly pleasant to contemplate, but getting trivial<>hard NAT cases to work would be a pretty big deal to double digit %age of our fleet, based on our portmapping stats.

**Comment by bradfitz** [comment]
> A more horrible alternative, for situations where we have network admin powers on the system (which we need anyway for firewall opening), would be to listen on a raw socket and attach an ebpf program to it that filters only traffic destined to tailscaled, and whose header contains the disco magic number. That would give us an extra receive funnel of all inbound disco traffic, before it ever hits netfilter. That way, we could grab those disco packets, use them to learn of a new usable endpoint, and punch our way out without having to imprecisely open the host firewall.

That SGTM. :)

**Comment by DentonGentry** [comment]
eBPF has waited its entire life for this moment.

**Comment by bradfitz** [comment]
OTOH we don't necessarily _need_ eBPF here.

We could also use `iptables -m u32 --u32` to match bytes in the UDP packets to see whether they're disco. Then even if we'd opened up a port and get killed without cleanup, it's harmless to leave the rule until we recognize & clean it up on next startup.

But admittedly eBPF would be more fun.

**Comment by bradfitz** [comment]
This seems like as easy (but ugly) as this:

```
iptables -I ts-input 1 -p udp \! -f -m u32 --u32 "0>>22&0x3C@8=0x5453f09f && 0>>22&0x3C@10&0xffff=0x92ac" -m comment --comment "Allow Tailscale NAT traversal" -j ACCEPT
```

Seems to work! It's matching packets and counting:

```
root@tsdev:/home/bradfitz/bin# iptables -L ts-input -v 
Chain ts-input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    6   870 ACCEPT     udp  !f  any    any     anywhere             anywhere             u32 "0x0>>0x16&0x3c@0x8=0x5453f09f&&0x0>>0x16&0x3c@0xa&0xffff=0x92ac" /* Allow Tailscale NAT traversal */
    0     0 ACCEPT     all  --  lo     any     tsdev.corp.ts.net    anywhere            
    0     0 RETURN     all  --  !tailscale0 any     100.115.92.0/23      anywhere            
    0     0 DROP       all  --  !tailscale0 any     100.64.0.0/10        anywhere            
```

**Comment by bradfitz** [comment]
(See discussion in closed #5474)

**Comment by DentonGentry** [comment]
So far as I know this was done in 1.32.0 by https://github.com/tailscale/tailscale/commit/c72caa6672c83a981e7b9ffcaa2f12fd9351d17e, but that commit only says it updates this bug not fixes this bug.

**Comment by DentonGentry** [comment]
Eh, I'm calling this fixed in 1.32.0. Please reopen if there is more to do.

**Comment by amluto** [comment]
FYI, Linux behaves quite poorly in the default mode here.  When receiving /any/ IPv4 packet (and I think the code is analogous for v6), Linux does, annotated by me:

```c
static int raw_v4_input(struct net *net, struct sk_buff *skb,
			const struct iphdr *iph, int hash)
{
	int sdif = inet_sdif(skb);
	struct hlist_head *hlist;
	int dif = inet_iif(skb);
	int delivered = 0;
	struct sock *sk;

	hlist = &raw_v4_hashinfo.ht[hash];
	rcu_read_lock();
	sk_for_each_rcu(sk, hlist) {
		if (!raw_v4_match(net, sk, iph->protocol,
				  iph->saddr, iph->daddr, dif, sdif))
			continue;

                // <-- raw_v4_match returns true for *every* UDP packet when tailscaled is running,
                // so this code executes.

		delivered = 1;
		if ((iph->protocol != IPPROTO_ICMP || !icmp_filter(sk, skb)) &&
		    ip_mc_sf_allow(sk, iph->daddr, iph->saddr,
				   skb->dev->ifindex, sdif)) {
			struct sk_buff *clone = skb_clone(skb, GFP_ATOMIC);  // <-- OUCH

			/* Not releasing hash table! */
			if (clone)
				raw_rcv(sk, clone);
		}
	}
	rcu_read_unlock();
	return delivered;
}
```
And now every single incoming UDP packet gets copied and goes into a rather slow path despite not matching the BPF filter.  If you run dropwatch with tailscaled running and any other UDP traffic on the system, you can see the absurdity of this yourself :)

Setting `TS_FORCE_LINUX_BIND_TO_DEVICE=1` works around this issue, and I haven't dug into why.  I'll separately email netdev, but it would be nice to mitigate this in tailscaled somehow.

**Comment by amluto** [comment]
See https://lore.kernel.org/netdev/CALCETrVJqj1JJmHJhMoZ3Fuj685Unf=DYsiEY1uEfnJq3H+Tzg@mail.gmail.com/T/#u
