### ISSUE TITLE
Devices of tailnet not shown:

### ISSUE THREAD

**Issue by iluvatyr** [tailscale/tailscale#3826]
### What is the issue?

When using the command "tailscale status". I should get the list of all the devices in my tailnet. I have 4 devices. 2 vps in different countries, configured with tailscale and 2 in my home lan behind a router, which both have tailscale installed. 
On both VPS (external) tailscale status shows all 4 devices.

On either lan device, it shows only 3 devices, consisting of itself and the 2 VPS-devices. I also cannot use tailscale ping between the two lan devices that cannot see each other.

### Steps to reproduce

Have minimum 3 devices.
Have 2 in the same lan network behind a router
Have 1 that is not in the same lan network

Check if tailscale status shows the other device from the same lan network
Check if tailscale status shows both devices from the lan network
Check if tailscale ping is possible between the devices that cannot find each other

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Ubuntu, Debian, 

### Tailscale version

1.20.2

### Bug report

BUG-0ae9e566d618ff17ab447d12ea6378da81c96d68977be172c64e9c44d88556a0-20220127181307Z-799e5e4710cd8ef8

**Comment by bradfitz** [comment]
Which Tailscale IP can't see which Tailscale IP in tailscale status?

Looks like your bug report was from 100.113.203.74 (Linux Mint). I see 4 machines in your tailnet. Which Ubuntu or Debian machine of yours didn't show up in status?

**Comment by iluvatyr** [comment]
the Linux-pc cannot see the openmediavault and vice versa

**Comment by bradfitz** [comment]
Thanks! I'm not sure what's going on yet, but something definitely seems wrong. I'm still investigating.

**Comment by bradfitz** [comment]
Oh! This is because you have "Shields Up" enabled on both of those nodes.

Whenever your ACL config and/or Shields Up config prevent two nodes from reaching each other in both directions, they're removed from the netmap to each other.

(e.g. so in a large company, every employee doesn't see every other employee's devices if they can't connect to each other anyway)

So this is all working as intended. When I was confused earlier it was because I'd looked at your ACLs but overlooked your Shields Up setting.

**Comment by iluvatyr** [comment]
Okay, Thank you for looking into it. The thing that I am confused about is though that I saw a reddit post where the official answer of tailscale support was following ( see link [:](https://www.reddit.com/r/Tailscale/comments/s8n3qn/block_incoming_connections_doesnt_work/hth8czm/?utm_source=reddit&utm_medium=web2x&context=3)

> 


JWS_TS
·
8 days ago
Tailscale Support

Expected behaviour is that `tailscale ping` will work, but ping will not.
You should not be able to connect to any port/service on the machine running --shields-up

If that is not how it is behaving, please run `tailscale bugreport` on the machine and email the code to support@tailscale.com

**Comment by bradfitz** [comment]
That answer is still correct, but omits the additional detail I added here: if all IP traffic is blocked in both directions, we just pretend that node doesn't exist.

But if it were only blocked one way (only one of the two nodes had shields up), then one side could ping the other, but not vice versa. But both sides could `tailscale ping` each other (which is a lower level mechanism) than regular `ping`.
