### ISSUE TITLE
FR: Login Link on Any Client

### ISSUE THREAD

**Issue by cwilliams5** [tailscale/tailscale#3827]
### What are you trying to do?

Login additional clients by URL only. On a linux host when I sudo tailscale up I am given a url that I can use to login on another device. It would be very useful to have this feature on all clients. 

Example 1:
Had to login to tailscale on a temporary laptop. My google auth requires a security token. My token is USB-A. Laptop has only USB-C. So I can't login. 

Example 2:
Adding tailscale to my wifes android phone. It takes it through the Android flow to add my entire Google account to her phone, not just auth. I had to add entire google account, which then started syncing, and then later remove it. I don't want to add my account to the phone. I just want to auth.

### How should we solve this?

There should be a way to get a linux style login link off any client. This would allow me authenticate on a device I can do so easily without running into issues with missing USB ports, odd OS login flows, or whatever. 

### What is the impact of not solving this?

Nothing's broken, just a pain in the ass, and seems simple to address.

### Anything else?

Awesome product, big fan. Keep up the good work. Thank you for generous free option.

**Comment by bradfitz** [comment]
You can copy/paste the URL from any client and use it on another machine.

You can also use the Tailscale CLI on Mac or Windows: https://tailscale.com/kb/1080/cli/ and then run `tailscale up` for a URL or `tailscale up --qr` for a QR code.

On Android/iOS you can copy/paste the URL from the webview, or click the "QR code" link on the login screen to log in from a different device (e.g. I log in to my Android phone using my iPhone to scan the QR code from Android)

Which particular OS->OS pair are you interested in?

**Comment by cwilliams5** [comment]
> You can copy/paste the URL from any client and use it on another machine.
> 

I....I have no excuse for me not trying that. I suppose I thought it needed to be on the same device. That's probably an instant solve of the Windows use case. 

> You can also use the Tailscale CLI on Mac or Windows: https://tailscale.com/kb/1080/cli/ and then run `tailscale up` for a URL or `tailscale up --qr` for a QR code.
> 
Another instant solve for the Windows use case!

> On Android/iOS you can copy/paste the URL from the webview, or click the "QR code" link on the login screen to log in from a different device (e.g. I log in to my Android phone using my iPhone to scan the QR code from Android)
> 

Let me go uninstall and recreate this issue from Android, because unfortunately this is from memory from a few weeks back but from memory (1) the webview opened in a window that had no URL or no way I could find to copy it and (2) the QR code wouldn't load.  

> Which particular OS->OS pair are you interested in?

Just a Windows an Android login that I wishing would just show me a URL. 

I suppose I'll close this until I can provide more detail.
