### ISSUE TITLE
Opt-in default route to non-tailscale wireguard nodes: send all Internet traffic

### ISSUE THREAD

**Issue by seertenedos** [tailscale/tailscale#383]
**Is your feature request related to a problem? Please describe.**

There are a number of times where it is helpful to be able to route all traffic or some traffic via a normal wireguard node that is external to tailscale. A few examples would be if you use a VPN provider ( AzireVpn or TorGuard ) that use unmodified wireguard or if you have a router at a location that had wireguard built in but not tailscale. My use case is to use TorGuard or AzireVpn and say all traffic on this node that does not meet a rule should be routed out to TorGuard or AzireVpn. Ideally it would be great to be able to ticka  box to apply to multi nodes but i suspect i will need a different config or something per concurrent node connecting or something

**Describe the solution you'd like**

In tailscale UI i would be able to configure one or more external normal wire-guard nodes and the routes they handle or process. Then in the UI i could either specify the node they apply to if it can only be applied to a single node or maybe an ACL if it could be applied to multiple nodes. I suspect that would be controlled by the restrictions of wire-guard itself.

**Describe alternatives you've considered**

Having a single node centrally configured with the external vpn/wireguard node and routing all traffic there but this is not ideal for home use as i would either need a cloud server with a lot of bandwidth that everything routes though or manually try to configure each node where tailscale is installed.

**Additional context**

This would be especially useful for docker networks where you would like the networks to be able to talk to each other over wireguard but for it to route anything else out over a VPN provider. The other use case would be mobile devices that want to access say a home network but route anything else over a VPN provider instead of over an insecure network.

**Comment by DentonGentry** [comment]
At this point, I don't expect to directly adopt wireguard tunnels created outside of Tailscale. Our preferred method of internetworking with wireguard tunnels is IP routing, allowing a packet to egress from the Tailscale network and ingress into the wireguard tunnel.
