### ISSUE TITLE
FR: make --reset remove all flags when called with no other arguments

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#3830]
### What are you trying to do?

currently, `tailscale up --reset ` does not have an effect when called on it's own. It is intended to be used with other arguments to reset all non-specified flags to default. 

The intuitive behaviour would be to have it reset all flags to default when called with no other arguments. 

### How should we solve this?

make `tailscale up --reset` set all flags to default values

### What is the impact of not solving this?

confusing UX

**Comment by bradfitz** [comment]
Looking into this, e6626366a2b80d215c0a94bfd97f18d9efa5e4ab introduced the current behavior in response to #3702 filed by a familiar person.

I guess that fix is wrong. With `--reset` we should also populate the `ipn.MaskedPrefs` based on implicit flag changes, not only the explicitly set flags as it does now:

```go
        if justEdit {
                justEditMP = new(ipn.MaskedPrefs)
                justEditMP.WantRunningSet = true
                justEditMP.Prefs = *prefs
                env.flagSet.Visit(func(f *flag.Flag) {
                        updateMaskedPrefsFromUpFlag(justEditMP, f.Name)
                })
        }
```
