### ISSUE TITLE
FR: Multiple virtual networks per team

### ISSUE THREAD

**Issue by joehacksalot** [tailscale/tailscale#3850]
### What are you trying to do?

Allow team to login to tail scale once, and be able to select which multiple virtual networks to have enabled. This can currently be achieved now by logging into tail scale with one set of credentials, then logging off and logging back in with a different set of credentials. This is obviously less than desirable.

Having only one network forces users to lay out one large flat virtual network and configure it through the use of ACLs which doesn't always provide the flexibility needed.

Specifically, our development team runs a number of environments which mirror each other and are behind several firewalls. We cannot deploy subnet routers into the environments because the IP addresses are identical, and installing tail scale on every instance in the environment was undesirable.

### How should we solve this?

Client software meant to run on interactive environments, such as team laptops etc. could have a right click option listing the networks available, and allows user to enable/disable networks individually. Each of the virtual networks would have a different virtual network space making routing between the different environments solvable. 

Client software meant to run on non-interactive environments, such as containers or infrastructure as code etc., could work the same as is it today, except that the tokens that are generated by a user in the web UI and then handed off to the installer software would only link to one of the networks within the team's set of networks. When a user is generating the token, they would select which network(s) this token would provide access to.

### What is the impact of not solving this?

We currently worked around this by installing tail scale on a single instance within each of the environments and use SOCAT to forward traffic to the different instances in the environment. This is definitely a hack but its getting us by. 

### Anything else?

Many of us on my team have personal accounts as well as our work account. There is another issue here where laptops/iPads are having to be logged out and back in to access personal networks. Though this could be its own feature request, it is related and it is possible that the way this one is implemented could either resolve this, or at least be done so in a way to facilitate implementing the other, should it be handled as a separate feature request.

**Comment by ron-spree** [comment]
See also https://github.com/tailscale/tailscale/issues/183

**Comment by DentonGentry** [comment]
> We cannot deploy subnet routers into the environments because the IP addresses are identical

[issues/826](https://github.com/tailscale/tailscale/issues/826#issuecomment-1120251404) describes a potential way to do this.

**Comment by DentonGentry** [comment]
I believe the overlapping subnet issue is resolved by 4via6 subnet routers https://tailscale.com/kb/1201/4via6-subnets/

If there are additional things which would make this use-case more tractable using 4via6 please feel free to open new feature requests.
