### ISSUE TITLE
tsnet: use proper log ID

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#3866]
### What is the issue?

I noticed a log ID conflict for multiple of my nodes. It's coming from inside the house:

https://github.com/tailscale/tailscale/blob/d7962e3bcf80c4d0837ac565f1cd17f87be3d07e/tsnet/tsnet.go#L174

If nothing else, we should generate a new log ID each time to use; better than a hard-coded string.

**Comment by bradfitz** [comment]
Eh, it seems fine.

It's untrusted input anyway, so what's the harm? We should be tolerant of bogus values anyway.

**Comment by josharian** [comment]
We are, but we do have (best effort) internal alerting of duplicate values, to help with support, and this guarantees duplicate values. If we generate a random value, we will at least not pointlessly and intentionally generate duplicates.

**Comment by bradfitz** [comment]
The alerting of duplicate values should ignore malformed ones.

I'd rather do that than have every start of a tsnet binary create a new log instance for now.

**Comment by bradfitz** [comment]
(We fixed the alerting of duplicating values in https://github.com/tailscale/corp/commit/290c22f7962db402fb403b456e9a6fae845925c2)
