### ISSUE TITLE
Error ignored when `tailscale ip [peername]` gets a invalid peer name.

### ISSUE THREAD

**Issue by matutter** [tailscale/tailscale#3867]
### What is the issue?

**What happened?**
The command `tailscale ip [peername]`, when `[peername]` is a peer that doesn't exist shows the address of the current host and exits with code `0`. 

**What did you expect to happen?**
The command should write an error message to `stderr` and exit with `2`; ENOENT idiomatically meaning something is not found.

### Steps to reproduce

1. Run `tailscale ip [peername]` replacing `[peername]` with a peer that doesn't exist.
2. You get the output of `tailscale ip` ( like it was run with no peer name ).

### Are there any recent changes that introduced the issue?

Unsure.

### OS

Linux

### OS version

Ubuntu 21.1

### Tailscale version

1.20.1

**Comment by bradfitz** [comment]
It actually does a DNS lookup of [peername] if it doesn't find an exact match, and tries to match/expand on that.

e.g.

```
$ tailscale ip mon.ts.tailscale.com
100.88.178.64
fd7a:115c:a1e0:ab12:4843:cd96:6258:b240
```

Do you have a wildcard DNS that's returning your local IP for all queries, or... ?

**Comment by matutter** [comment]
@bradfitz It does not appear that I have a wildcard DNS doing that.

```
tailscale ip xxx
100.91.133.113
fd7a:115c:a1e0:ab12:4843:cd96:625b:8571
```

```
dig xxx

; <<>> DiG 9.16.15-Ubuntu <<>> xxx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 46481
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;xxx.                           IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Feb 02 19:30:44 EST 2022
;; MSG SIZE  rcvd: 32
```

**Comment by bradfitz** [comment]
dig won't expand your `/etc/resolv.conf`'s `search` directive.

Try `ping`.

**Comment by matutter** [comment]
I see. Yes it does appear to be hitting one of the DNS servers we've setup with Split-DNS. I wasn't aware those DNS server's would receive queries that didn't end with the search-domain for those server.
