### ISSUE TITLE
Linux taildrop: can't send files to other devices owned by same user on single-user tailnet

### ISSUE THREAD

**Issue by ajhalili2006** [tailscale/tailscale#3871]
### What is the issue?

When attempting to send an file to my iPhone on Linux via command line, I got the error message `can't send  to <insert-device-name-here> owned by different user, can only send files to your own devices`, even through I'm on my single-user tailnet (hint: my tailnet is `ajhalili2006.github` for context).

### Steps to reproduce

1. Upgrade both devices to 1.20.2, then switch to single-user tailnet.
2. Attempt to send file via command line.

### Additional Debugging Info

* **Source IP**:  `100.113.94.115`
* **Destination IP**: `100.118.223.2`

### OS

Linux, iOS

### OS version

Debian unstable on sending end; iOS 12.5.5 on receiving end

### Tailscale version

1.20.2 on both devices

### Bug report

BUG-b5351494c6395feed523353efbcdfd0c27715d4ee7f5191171e790b5a093e865-20220204035145Z-bad7c2ee29817e3f

**Comment by DentonGentry** [comment]
100.113.94.115 is Tagged, which means it isn't owned by any user.

**Comment by ajhalili2006** [comment]
> 100.113.94.115 is Tagged, which means it isn't owned by any user.

@DentomGentry Maybe that's the cause. By the way, here's my ACL policy for help:

```jsonc
{
  // Declare static groups of users beyond those in the identity service.
  "groups": {
    "group:family": [ "ajhalili2006@github" ],
  },
  "tagOwners": {
    "tag:windows": [
      "ajhalili2006@github",
    ],
    "tag:ios": [
      "ajhalili2006@github",
    ],
    "tag:macos": [
      "ajhalili2006@github",
    ],
    "tag:linux": [
      "ajhalili2006@github",
    ],
    "tag:ssh": [
      "ajhalili2006@github",
    ],
    "tag:rdp": [
      "ajhalili2006@github",
    ],
    "tag:podman": [
      "ajhalili2006@github",
    ],
    "tag:docker": [
      "ajhalili2006@github",
    ],
    "tag:virtualbox": [
      "ajhalili2006@github",
    ],
    "tag:wsl2": [
      "ajhalili2006@github",
    ],
    "tag:family": [
      "group:family",
    ],
  },
  // Access control lists.
  "acls": [
    // Match absolutely everything. Comment out this section if you want
    // to define specific ACL restrictions.
    { "action": "accept", "users": ["*"], "ports": ["*:*"] },
  ]
}
```

**Comment by DentonGentry** [comment]
It really is the root cause: Taildrop is currently only able to send files to devices owned by the same user.
100.118.223.2 is owned by your User, but 100.113.94.115 is not.

**Comment by Techman** [comment]
Stumbled across this thread when running into a similar issue. Not being able to use Taildrop between tagged devices is a crippling limitation. Anyone serious about device management will be using tags to control traffic.

**Comment by mug-book-droid** [comment]
@Techman Agreed, this is a poor choice.

**Comment by zfogg** [comment]
same issue
