### ISSUE TITLE
FR: Add support for Okta dashboard, Okta Mobile app, or other custom URLs.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3872]
### What are you trying to do?

 Add support for Okta dashboard, Okta Mobile app, or other custom URLs.

### How should we solve this?

Adding support for Okta dashboard, Okta Mobile app, or other custom URLs.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4e9sh)

**Comment by DentonGentry** [comment]
Front link doesn't work for me, just an empty list of email messages.

**Comment by bradfitz** [comment]
Same.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/4287
