### ISSUE TITLE
Handle peerapi in netstack on Windows too

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3874]
f3c0023addc13ea4212db9daf04fd317585d28c3 passed in LocalBackend to netstack on all platforms but Windows, as tailscaled_windows.go still has a slightly different startup path.

But that means that the netstack interception of peerapi in bd90781b34d2558f27196194ba871f1cda60ffe6 doesn't get handled on Windows probably.

**Comment by bradfitz** [comment]
(of course, this matters less on Windows as we program the Windows firewall to allow our application to get traffic in)

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/4783 in 1.26.0
