### ISSUE TITLE
investigate our TCP MSS in our use of netstack

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3878]
I don't recall ever telling netstack about our MTU.

I worry that our TCP MSS is currently too high in netstack modes and we're fragmenting IP packets.

Reminder bug to look at netstack flows and see what the MSS currently is and whether it's ideal.

**Comment by crawshaw** [comment]
oh there's already a PR, I missed that

**Comment by DentonGentry** [comment]
I don't know what is left to be done after https://github.com/tailscale/tailscale/commit/1336fb740b7fc1a19674b44b36e9e63f815f45ba

**Comment by DentonGentry** [comment]
I believe this was resolved by https://github.com/tailscale/tailscale/commit/1336fb740b7fc1a19674b44b36e9e63f815f45ba

The more general issue of Path MTU Discovery support is tracked in https://github.com/tailscale/tailscale/issues/311
