### ISSUE TITLE
Add DERP region support

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#388]
We currently have one 1 VM per DERP region.

For both scalability and high availability, that's a bit scary. It's not super scary because we're only using super cheap VMs and we can scale vertically a bunch, and worst case clients fall over to another region with more latency for a few minutes (or hours, depending on how bad the outage is).

But we can do better.

Plan is to run N VMs per region and do inter-VM routing within a region, but minimize that by having domains prefer a certain VM in that region. But if it's down, they'll also quickly fail over to another.

Then the control server will give each consistently hash domains onto the available DERP nodes per region.

**Comment by bradfitz** [comment]
Forgot to reference it, but also: https://github.com/tailscale/tailscale/commit/3fa58303d0dd206609362d68736f1039801ffd8d

**Comment by bradfitz** [comment]
This is sufficiently done.

We're at least running two nodes in all the major regions for HA purposes now and intra-region packet forwarding works. We're not load balancing yet but that's just a config tweak we can do when needed.

**Comment by kylecarbs** [comment]
@bradfitz what small tweak would be necessary? We're trying to DERP in a Kubernetes cluster where there are numerous dynamic replicas with internal IPs, load-balanced under a single external IP.

**Comment by DentonGentry** [comment]
@kylecarbs I think getting DERP working within an environment like that is well beyond what can just be answered in a quick update on this bug. The current custom derp feature is considered done: it works, as a single node, in a straightforward hosting environment like EC2.

If you really want to discuss it you're welcome to contact support@tailscale.com.

If I may ask: why do you want to run your own DERP server?

**Comment by bradfitz** [comment]
Short answer, see these `cmd/derper` flags:

```
  -mesh-psk-file string
    	if non-empty, path to file containing the mesh pre-shared key file. It should contain some hex string; whitespace is trimmed.
  -mesh-with string
    	optional comma-separated list of hostnames to mesh with; the server's own hostname can be in the list
```

Happy to discuss more elsewhere.
