### ISSUE TITLE
FR: Customize logging

### ISSUE THREAD

**Issue by altyne** [tailscale/tailscale#3885]
### What are you trying to do?

Write know, every seconds tailscale node create a massive log for normal operation. 

### How should we solve this?

Add command arguments on how the log should be written by error level.

### What is the impact of not solving this?

It consumes a lot of I/O resources

### Anything else?

Current log:
2022/02/07 07:34:30 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:34:30 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 40 ok out
2022/02/07 07:34:45 Accept: TCP{100.111.111.11:56068 > 100.999.99.99:36715} 41 tcp non-syn
2022/02/07 07:34:45 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 52 ok out
2022/02/07 07:34:54 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:34:54 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:35:01 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 40 ok out
2022/02/07 07:35:15 Accept: TCP{100.111.111.11:56068 > 100.999.99.99:36715} 41 tcp non-syn
2022/02/07 07:35:15 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 52 ok out
2022/02/07 07:35:19 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:35:30 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 40 ok out
2022/02/07 07:35:43 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:35:46 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 40 ok out
2022/02/07 07:35:46 Accept: TCP{100.111.111.11:56068 > 100.999.99.99:36715} 40 tcp non-syn
2022/02/07 07:36:01 Accept: TCP{100.111.111.11:56026 > 100.999.99.99:36715} 41 tcp non-syn
2022/02/07 07:36:03 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:36:03 portmapper: saw UPnP type WANIPConnection1 at http://192.168.1.1:49152/rootDesc.xml; my-test-modem-router
2022/02/07 07:36:16 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56068} 40 ok out
2022/02/07 07:36:16 Accept: TCP{100.999.99.99:36715 > 100.111.111.11:56026} 40 ok out
....
...
(remove for brevity)

**Comment by bradfitz** [comment]
Dup of #1548 which is an ongoing effort.
