### ISSUE TITLE
autogroup:self:* not working on Windows 11

### ISSUE THREAD

**Issue by jdgiddings** [tailscale/tailscale#3895]
### What is the issue?

![image](https://user-images.githubusercontent.com/79322633/153238618-daf396fb-448c-48e3-8a2b-505ba2ba46a6.png)

Using the above ACL, my Windows 11 devices do not show my phone or tablet in the Network devices menu. However, on my phone (Samsung Galaxy A52 5G) it works great

![image](https://user-images.githubusercontent.com/79322633/153242550-f677c47b-d925-4398-840f-7c39492e3225.png)

![tempFileForShare_20220209-100021](https://user-images.githubusercontent.com/79322633/153240273-d0d9bc7f-21a9-4410-ac65-3ea8d7947fc7.jpg)

UPDATE:

Even with my desktop being unable to access my phone, the following ACL test passes
![image](https://user-images.githubusercontent.com/79322633/153245083-bfdab456-31d6-4f0e-9fbf-4ffec29d4f18.png)

This makes me believe it is an issue with the client rather than an issue with the control plane

### Steps to reproduce

Add this ACL to your ACL rules:

```
{
     "action": "accept", 
     "users": ["*"], 
     "ports": ["autogroup:self:*"] 
},
```

And check for your devices on a Windows 11 machine

### Are there any recent changes that introduced the issue?

No, this issue has existed for several months

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.20.2

### Bug report

BUG-607682d70a6eaea90b60d6598c3640f2e9dfe61da7c29a20cb5d00856c5b7d6c-20220209161508Z-b0047e0bd7d20ac9

**Comment by jdgiddings** [comment]
Wow! Disabling Shields Up fixed it!

But that leaves me with a question: why is

```
{
     "action": "accept", 
     "users": ["myemail@gmail.com"], 
     "ports": ["myemail@gmail.com:*"] 
},
```

different from 

```
{
     "action": "accept", 
     "users": ["*"], 
     "ports": ["autogroup:self:*"] 
},
```

It seems like these two should be exactly the same?

**Comment by JayWStapleton** [comment]
@jdgiddings  - did you delete a tag during this process? I am able to reproduce in limited circumstances, but that seems to be a necessary step for me. If that happened on your network, that could narrow it down for us.

**Comment by maisem** [comment]
@jdgiddings you did actually uncover a real issue. We had a bug in the way we were handling Shields Up and `autogroup:self`, this has been fixed and deployed! Thanks for the bug report!

**Comment by jdgiddings** [comment]
@maisem thanks! It looks like the bug is fixed on my personal Tailnet and for all but one of the users on my work's Tailnet. Here's a bug report from the affected user's PC:

BUG-9c3bc8934ec7d01fe25e4d468a6d43d87f5bca721b3b7f80a42c42544c8fe144-20220211164624Z-35c3810112fb2067

autogroup:self:* was active at the time but this user couldn't access his own devices

**Comment by maisem** [comment]
@jdgiddings were they trying to reach a tagged node? Tagged nodes are not tied to users, so they don't work with `autogroup:self`

**Comment by jdgiddings** [comment]
@maisem No, both machines are under the user's ID
