### ISSUE TITLE
FR: Apple Ecosystem / Application Store Updates

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#3906]
### What are you trying to do?

Get faster Apple App Store Updates.

For iOS there is testflight which helps to speed up updates. But for MacOS it is horrid.

### How should we solve this?

1. Consider OTA updates?
2. Or in-place application updates?
3. Or Tailscale Application file download from Website? 

### What is the impact of not solving this?

1. Users are not obtaining the latest and best updates from Tailscale in a timely manner.
2. Users are stuck in Tailscale admin portal staring at the "out of date" device message for most of their life.

### Anything else?

You'd probably just say: "We cannot control Apple's speed", or "You can build it yourself", but just from an honest user's feedback who loves Tailscale, it'd be good if we can always get the latest and greatest fast.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/718
