### ISSUE TITLE
High CPU due to DNS problems

### ISSUE THREAD

**Issue by kusold** [tailscale/tailscale#3909]
### What is the issue?

Occasionally, on my 8GB RPi4, Tailscale will peg my CPU until I restart the service. I remembered to grab a log dump this time.

The RPi4 runs OctoPi (pi distro for Octoprint, a 3D Printer manager), and is connected via WiFi.

Another potentially important fact is that I run CoreDNS to remap `int.example.com` to my Tailscale DNS (`example.gmail.com....`), and I have the dns server's Tailscale network ip set as the Custom DNS Resolver.

## Logs
[tailscale.txt](https://github.com/tailscale/tailscale/files/8051379/tailscale.txt)

### Steps to reproduce

I haven't figured out the root cause yet. My best guess is that it's flaky wifi combined with using the tailscale ip for DNS.

### Are there any recent changes that introduced the issue?

No, this has happened on previous versions as well.

### OS

Linux

### OS version

Raspbian 10

### Tailscale version

1.20.2

### Bug report

BUG-c6bee0db7f451c94a6e64a9e052fd6f695d42850b5ee677ccd910d2a3166bb9f-20220211202026Z-acab8feada1d0412

**Comment by DentonGentry** [comment]
I think this may be an instance of [#5879](https://github.com/tailscale/tailscale/issues/5879), which was fixed in Tailscale 1.32.1.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
This was a symptom of https://github.com/tailscale/tailscale/issues/5879

**Comment by kusold** [comment]
Very possible. I think an Octoprint plugin (spaghetti detective/obico) I had installed opened up a remote tunnel. I've since switched my 3d printing stack so I won't be able to validate the fix.

Thanks for following this report. I'm looking forward to putting tailscale back on my printer.
