### ISSUE TITLE
Reauthing a tagged node without being the tagOwner of the assigned tags creates a new node

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3913]
### What is the issue?

If you have tagged node and node key is expired, when you reauth yourself and if you are not tagOwner it will create the duplicate node with nodename-1.

![image](https://user-images.githubusercontent.com/75628398/153672683-5907e316-25aa-405d-bde5-f14e7e344280.png)

As the previous behaviour was not duplicating nodes on reauth with node key expiry.

### Steps to reproduce

1. log into a node
2. tag it in the admin panel
3. log into the node again (eg. if it expired because you forget to set it to never expire)

### Are there any recent changes that introduced the issue?

ACL-Tags 

### Tailscale version

1.20.4

**Comment by bradfitz** [comment]
cc @maisem
