### ISSUE TITLE
Drop privileges after establishing a Wireguard tunnel

### ISSUE THREAD

**Issue by egtann** [tailscale/tailscale#393]
**Is your feature request related to a problem? Please describe.**

Running the networked daemon `tailscaled` as root increases risk from unknown vulnerabilities.

**Describe the solution you'd like**

Use privsep and privdrop: fork+exec after creating the wireguard tunnel, dropping root privileges. At the same time, adding Pledge/Unveil under an OpenBSD build tag would go a long way to reducing risk in an environment where external systemd/AppArmor/SELinux defenses are unavailable.

**Comment by DentonGentry** [comment]
tailscaled needs to establish new tunnels as nodes come and go, I don't expect to be able to do this.

**Comment by DentonGentry** [comment]
Not likely to be pursued.
