### ISSUE TITLE
tailscale0 interface exposes wrong speed to kernel

### ISSUE THREAD

**Issue by BirkhoffLee** [tailscale/tailscale#3933]
### What is the issue?

I'm using Prometheus to monitor network interfaces saturation by node_network_speed_bytes. There has been a lot of alerts regarding `tailscale0` interface only. I looked into the traffics on the interface, and there's little traffic that would never trigger such alert. Looking into `/sys/class/net/tailscale0/speed`, apparently Tailscale interface speed is set to a wrong value.

### Steps to reproduce

1. Value of `/sys/class/net/tailscale0/speed`: `10`
2. Output of `ethtool tailscale0`:
```
$ ethtool tailscale0
Settings for tailscale0:
        Supported ports: [  ]
        Supported link modes:   Not reported
        Supported pause frame use: No
        Supports auto-negotiation: No
        Supported FEC modes: Not reported
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Advertised FEC modes: Not reported
        Speed: 10Mb/s
        Duplex: Full
        Auto-negotiation: off
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: internal
        MDI-X: Unknown
        Current message level: 0x00007fa1 (32673)
                               drv ifup tx_err tx_queued intr tx_done rx_status pktdata hw wol
        Link detected: yes
```

### OS

Linux

### OS version

CentOS 8 / 4.18.0-348.2.1.el8_5.x86_64

### Tailscale version

1.20.2-t312750ddd-g2c164d9c7

**Comment by bradfitz** [comment]
What would be a good speed?

**Comment by BirkhoffLee** [comment]
> What would be a good speed?

Since it's a virtual interface, I reckon that setting it to a common high value is more sensible. 1Gbps seems to be reasonable at this point. What do you think?

**Comment by bradfitz** [comment]
Sure, feel free to send a patch. Seems like ethtool uses the netlink API. Looks like LINKINFO_SET with ETHTOOL_A_LINKMODES_SPEED?
