### ISSUE TITLE
Masgisk module

### ISSUE THREAD

**Issue by anoop-b** [tailscale/tailscale#394]
Any plans on providing a masgisk module? So that tailscale can be mounted systemless-ly on boot.

**Comment by bradfitz** [comment]
Do you mean Magisk? https://github.com/topjohnwu/Magisk ... that's what Google pointed me to, at least.

In any case, no plans.

Can you back up and explain what this would enable and for whom? What are the use cases?

**Comment by JayDoubleu** [comment]
Since there is no information about android app yet, some might believe the tailscale for android might require root or are already running tailscale binaries on android and asking for systemless solution (magisk) so there is no need to install it in /system partition.

I'm personally curious about android app development and how will it look in general.

**Comment by bradfitz** [comment]
The Android app doesn't require root. Just a normal app. It'll be public in the Play store soon.

**Comment by anoop-b** [comment]
hey @bradfitz , as @JayDoubleu pointed out, installing Tailscale on android can be done by pushing the binary directly into /system, and magisk allows to do the same but without any need for pushing binaries to /system partition and also achieveing root at the same time, if the app/binary demands it. But as you already mentioned that root is not required, I don't think magisk will be useful here, except for maybe running Tailscale on system startup automatically.

**Comment by JayDoubleu** [comment]
So now there is two things worth waiting for .. the spacex crew program demo flight and tailscale android app ;)

**Comment by anoop-b** [comment]
Good thing golang can spit out binaries for Android on the fly, this makes it much easier for development I guess 😅

**Comment by apenwarr** [comment]
For notifications about android native app availability, follow this bug: https://github.com/tailscale/tailscale/issues/285

**Comment by 1orz** [comment]
> Do you mean Magisk? https://github.com/topjohnwu/Magisk ... that's what Google pointed me to, at least.
> 
> In any case, no plans.
> 
> Can you back up and explain what this would enable and for whom? What are the use cases?

Here is an actual use case to prove the necessity of developing a magisk module. Of course, this requirement may be a rare requirement. I hope to evaluate comprehensively whether this function is necessary to implement based on the actual situation of the community:
 As far as I know, the method of using tailscale to join the tailnet on Android requires the use of the system's vpn. And this will make other software that **uses the vpn service not enabled at the same time**.
 For example: I cannot use openvpn and tailscale at the same time on Android. Once I have them both occupy the system's vpn service. And they cannot be opened at the same time.
 Of course, the solution is to make tailscale as a magisk module and as a background daemon. After my simple test, I compiled the tailscaled binary on termux, and successfully joined the tailnet through tailscale login, communicating with other devices in the tailnet. **The important thing is that this will not have any conflict with the openvpn I am running. Both can be run at the same time rather than only one of them.**

**Comment by anasfanani** [comment]
> Any plans on providing a masgisk module? So that tailscale can be mounted systemless-ly on boot.

Hi, i create magisk module for tailscale, tested and work.

**Comment by kxxt** [comment]
Not a magisk module, but you could run full featured tailscale daemon on rooted Android (without userspace-networking, Tailscale SSH works, the only thing that currently does not work is MagicDNS).

See my blog post for more details: https://www.kxxt.dev/blog/full-tailscale-on-android-and-remote-unlocking/

(Of course someone could write a magisk moulde equivalent to the Android init service I made)

**Comment by anasfanani** [comment]
> Not a magisk module, but you could run full featured tailscale daemon on rooted Android (without userspace-networking, Tailscale SSH works, the only thing that currently does not work is MagicDNS).
> 
> See my blog post for more details: https://www.kxxt.dev/blog/full-tailscale-on-android-and-remote-unlocking/
> 
> (Of course someone could write a magisk moulde equivalent to the Android init service I made)

Thankyou, me also trying to modify the source https://github.com/anasfanani/tailscale-magisk-build

For magic dns maybe need include some coredns code into the source, but i dont know how to do it.
Last problem is make exit node work, any idea to make it work ?

**Comment by kxxt** [comment]
> > Not a magisk module, but you could run full featured tailscale daemon on rooted Android (without userspace-networking, Tailscale SSH works, the only thing that currently does not work is MagicDNS).
> > See my blog post for more details: https://www.kxxt.dev/blog/full-tailscale-on-android-and-remote-unlocking/
> > (Of course someone could write a magisk moulde equivalent to the Android init service I made)
> 
> Thankyou, me also trying to modify the source https://github.com/anasfanani/tailscale-magisk-build
> 
> For magic dns maybe need include some coredns code into the source, but i dont know how to do it. Last problem is make exit node work, any idea to make it work ?

Personally I am using subnet routers instead of exit node, but I think they are implemented in almost the same way. Subnet routers are mostly working for me after `echo 1 | sudo tee /proc/sys/net/ipv4/conf/all/forwarding` but I got `Destination Net Unreachable` so I think there are still some routing problems to be debugged. (Probably because most Android ip rules are guarded with `iif lo` so incoming packets from `tailscale0` matched `from all unreachable` in the end.

**Comment by anasfanani** [comment]
> Personally I am using subnet routers instead of exit node, but I think they are implemented in almost the same way. Subnet routers are mostly working for me after `echo 1 | sudo tee /proc/sys/net/ipv4/conf/all/forwarding` but I got `Destination Net Unreachable` so I think there are still some routing problems to be debugged. (Probably because most Android ip rules are guarded with `iif lo` so incoming packets from `tailscale0` matched `from all unreachable` in the end.

As far as I know, when android runs as an exit node client, it is directly setup to the main table then this would break the whole internet in the android. 
I still search for the hacky way to make it work.

**Comment by kxxt** [comment]
> > Personally I am using subnet routers instead of exit node, but I think they are implemented in almost the same way. Subnet routers are mostly working for me after `echo 1 | sudo tee /proc/sys/net/ipv4/conf/all/forwarding` but I got `Destination Net Unreachable` so I think there are still some routing problems to be debugged. (Probably because most Android ip rules are guarded with `iif lo` so incoming packets from `tailscale0` matched `from all unreachable` in the end.
> 
> As far as I know, when android runs as an exit node client, it is directly setup to the main table then this would break the whole internet in the android. I still search for the hacky way to make it work.

I am considering directly patching Android netd to fix it. Directly adding more ip rules in tailscale code doesn't work well because in Android many tables are dynamically created and named (like wlan0, wlan1_local). But clearly this approach is non-portable.

**Comment by anasfanani** [comment]
> > > Personally I am using subnet routers instead of exit node, but I think they are implemented in almost the same way. Subnet routers are mostly working for me after `echo 1 | sudo tee /proc/sys/net/ipv4/conf/all/forwarding` but I got `Destination Net Unreachable` so I think there are still some routing problems to be debugged. (Probably because most Android ip rules are guarded with `iif lo` so incoming packets from `tailscale0` matched `from all unreachable` in the end.
> > 
> > As far as I know, when android runs as an exit node client, it is directly setup to the main table then this would break the whole internet in the android. I still search for the hacky way to make it work.
> 
> I am considering directly patching Android netd to fix it. Directly adding more ip rules in tailscale code doesn't work well because in Android many tables are dynamically created and named (like wlan0, wlan1_local). But clearly this approach is non-portable. 

Interesting, if you have free time, can you update the article on your blog?
By patching netd, does it will support various versions of Android?

**Comment by kxxt** [comment]
> > > > Personally I am using subnet routers instead of exit node, but I think they are implemented in almost the same way. Subnet routers are mostly working for me after `echo 1 | sudo tee /proc/sys/net/ipv4/conf/all/forwarding` but I got `Destination Net Unreachable` so I think there are still some routing problems to be debugged. (Probably because most Android ip rules are guarded with `iif lo` so incoming packets from `tailscale0` matched `from all unreachable` in the end.
> > > 
> > > 
> > > As far as I know, when android runs as an exit node client, it is directly setup to the main table then this would break the whole internet in the android. I still search for the hacky way to make it work.
> > 
> > 
> > I am considering directly patching Android netd to fix it. Directly adding more ip rules in tailscale code doesn't work well because in Android many tables are dynamically created and named (like wlan0, wlan1_local). But clearly this approach is non-portable.
> 
> Interesting, if you have free time, can you update the article on your blog? By patching netd, does it will support various versions of Android?

Sure. From source level it surely supports various versions of Android. But I am less certain about doing binary patching in Magisk.

Here at `RouteController.cpp`(https://android.googlesource.com/platform/system/netd/+/master/server/RouteController.cpp#1150), the code controls the rule(hard coded priority 31000) for default routing table on Android:

```
31000:  from all fwmark 0xc0000/0xcffff iif lo lookup rmnet_data3 
```

Patching it to remove `iif lo` and using iptables to add `0xc0000` fwmarks for packets from `tailscale0` probably could at least make the subnet router work.
But my quick test yields negative result. Maybe I set the fwmarks the wrong way.
If I remove `fwmark 0xc0000/0xcffff` from this rule it indeed works.

**Comment by kxxt** [comment]
> As far as I know, when android runs as an exit node client, it is directly setup to the main table then this would break the whole internet in the android. I still search for the hacky way to make it work.

I didn't experience internet problem in android when setting it up as exit node. But other clients using this exit node won't work. The following steps could fix it:

- Patch tailscale to mark traffic with Android system permission fwmark bits in `PREROUTING`: https://github.com/android-kxxt/external_tailscale/commit/b5ca22c204ebe2545c9845ae35df6fd25aa5f8db
- Remove `iif lo` restriction from Android DEFAULT_NETWORK rule(the one with priority `30000` in `ip rule`): https://github.com/android-kxxt/android_patches/commit/b2dc49dd8cb74c29530df906a0868ceefa95e82e

So now I have working subnet routers and exit node on Android.
