### ISSUE TITLE
cannot access shared node

### ISSUE THREAD

**Issue by rogpeppe** [tailscale/tailscale#3940]
### What is the issue?

I have a Raspberry pi on Tailscale that's on one account (call it A1) and shared with another account (A2).
When logged in (on a Linux machine) as A1, I can access the Pi just fine. When I log out and log in as A2,
I cannot access the machine. The pi is on my local network currently.

### Steps to reproduce

Share machine from one account.
Try to access from another account.

I'm sure this has worked OK for me before, so there must be some other issue!

Here's a transcript of when this was happening:

```
% sudo tailscale logout
% sudo tailscale up

To authenticate, visit:

	https://login.tailscale.com/a/86a357cc24ac

#### Logged in as A1

Success.
%  ping 100.111.113.7
PING 100.111.113.7 (100.111.113.7) 56(84) bytes of data.
64 bytes from 100.111.113.7: icmp_seq=1 ttl=64 time=72.9 ms
64 bytes from 100.111.113.7: icmp_seq=2 ttl=64 time=13.5 ms
^?
--- 100.111.113.7 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 13.461/43.195/72.930/29.734 ms
% sudo tailscale logout
% sudo tailscale up

To authenticate, visit:

	https://login.tailscale.com/a/c3a979c5060a

####  Logged in as A2

Success.
% tailscale status
100.65.18.97    snazzy2              rogpeppe@    linux   -
100.111.113.7   hydro1.glendrynoch.gmail.com.beta.tailscale.net glendrynoch@ linux   -
100.119.82.117  roger                rogpeppe@    android offline
% ping 100.111.113.7
PING 100.111.113.7 (100.111.113.7) 56(84) bytes of data.
^?
--- 100.111.113.7 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1016ms

### Cannot access machine
```

### Are there any recent changes that introduced the issue?

I recently upgraded my Linux tailscale to

```
1.20.4
  tailscale commit: 8c6cb1cea699b9d5249aec958af7f5d9e2baf1e9
  other commit: 2accf24a573179086cb800800243b3bace0eacfd
  go version: go1.17.6-tse44d304e54
```

### OS

Linux

### OS version

Ubuntu 20.04.3, Rasbpian Bullseye

### Tailscale version

1.20.2 (on the pi), 1.20.4 (on the laptop)

### Bug report

BUG-65a6b8c33f9ed1672aed2707399d7f34651c6cce3dc0d7dc8b7feb36d067f94a-20220214203020Z-2b1bf1d6dc8416c5

**Comment by bradfitz** [comment]
cc @maisem

**Comment by bradfitz** [comment]
Does `tailscale ping 100.111.113.7` work?

**Comment by bradfitz** [comment]
@rogpeppe, I'm in https://meet.google.com/qto-ttpt-cua for a bit if you want to debug together.

**Comment by bradfitz** [comment]
That Pi's logs say:

```
2022-02-14 20:42:15.25214026 +0000 UTC: tailscaled got signal terminated; shutting down
2022-02-14 20:42:15.253167081 +0000 UTC: control: client.Shutdown()
2022-02-14 20:42:15.255229315 +0000 UTC: control: client.Shutdown: inSendStatus=0
```

Was that intentional or did something else do that?

**Comment by rogpeppe** [comment]
> Was that intentional or did something else do that?

Hmm, good question. I don't remember doing that intentionally, but I was hitting a bunch of stuff trying to see if something worked.

> @rogpeppe, I'm in https://meet.google.com/qto-ttpt-cua for a bit if you want to debug together.

Sorry, I didn't see that response in time. And now the pi is in the post back to its working home.  When it gets there and is plugged in, I'll ping you if the issue is still present.
