### ISSUE TITLE
--advertise-tags cannot be supplied on restart

### ISSUE THREAD

**Issue by shousper** [tailscale/tailscale#3945]
### What is the issue?

Context: We're running kubernetes (AWS EKS) clusters for all our environments. I wanted to run a subnet router in each cluster to provide access to the local AWS VPC. Following the [reference material](https://github.com/tailscale/tailscale/tree/main/docs/k8s) for a kubernetes deployment, I ran into this issue.

Pods aren't aware of the current tags associated with a subnet router device, running `tailscale up` with `--advertised-tags` appears to only work the first time this command is run for a given device. Every subsequent execution (e.g. when the pod restarts) yields the follow error logs that crashes the pod:

```
2022/02/15 04:20:48 Received error: requested tags [tag:division-dabble tag:environment-staging tag:department-technology tag:subdivision-internal] are invalid or not permitted
backend error: requested tags [tag:division-dabble tag:environment-staging tag:department-technology tag:subdivision-internal] are invalid or not permitted
```

What would I like to happen? I'd like the tags to be accepted, potentially replaced on the device if possible, no matter how many times `tailscale up` is executed with said tags. I'm also open to other methods of running tailscale in k8s 🙏🏻

### Steps to reproduce

1. Start `tailscaled`
2. Run `tailscale up --advertise-tags=tag:hello`
3. Terminate `tailscaled`
4. Run `tailscale up --advertise-tags=tag:hello` again, see error.

### OS

Linux

### OS version

N/A

### Tailscale version

1.20.4

**Comment by DentonGentry** [comment]
I'd recommend adding the Tags to the authkey instead of using `--advertise-tags=...` with `tailscale up`.
https://tailscale.com/blog/acl-tags-ga/

We're still accommodating `--advertise-tags=...` for the benefit of scripts which were already using it, but tagging via the authkey is strongly preferred.

**Comment by shousper** [comment]
Love this. Makes total sense! Thank you kindly @DentonGentry 🙏🏻
