### ISSUE TITLE
FR: end tailscale up after returning the url, don't wait for the user to login

### ISSUE THREAD

**Issue by mchaver** [tailscale/tailscale#3950]
### What are you trying to do?

I am trying to remotely add a device to tailscale. I thought I could use `sudo tailscale up --json=true`, read the URL and pass it to the frontend, then the user can login, but calling `sudo tailscale up --json=true` in a program waits for the user to visit the url before returning anything. You can see a similar effect by doing `sudo tailscale up --json=true | cat`. It won't print anything until it timeouts or is canceld. I couldn't find an option to not wait for the user to visit the .

### How should we solve this?

Add an option for `up` to not wait for the user to login or for it to timeout.

### What is the impact of not solving this?

This is my current solution:

```
sudo tailscale up --json=true >  tmp.txt 2>&1
```

then parse the json from tmp.txt

Edit: added current solution.

**Comment by DentonGentry** [comment]
The `--json` argument was added recently to handle a similar case, and that use also does `sudo tailscale up --json=true >  tmp.txt &` as you suggest.

The trouble we have is that there wasn't a straightforward way to make a pair of commands where the first starts the tailscale up process and the second can then, at some later time, block until the operation started by the first command completes. So we made `tailscale up --json` print two separate JSON structures and read out the temporary file to find the status after the first has been printed.

**Comment by DentonGentry** [comment]
I am declining to implement this feature request. I believe `tailscale up --json` can be used to meet this need.

**Comment by mchaver** [comment]
`sudo tailscale up --json=true > tmp.txt &` works, but when you to use that in a program, it requires an awkward work around. You have to watch the the output file for changes, then read and parse it and include some timeout. Whereas if there was a `--nowait` flag, you would just need to wait for the response from the command line call and parse the output.

**Comment by boonedoggle** [comment]
@DentonGentry what is your recommendation for doing the same thing in powershell < 6.0 (where you cannot use & after a command)?

**Comment by dannydulai** [comment]
i found that tailscale status says:
```
Logged out.
Log in at: https://login.tailscale.com/a/XXXXXXXXXX
```

and it exits like a well behaved commandline.
