### ISSUE TITLE
FR: Add APT deb repository for Ubuntu 22.04 (LTS) that's almost ready for public release

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#3952]
### What are you trying to do?

Have tailcsale auto-update on Ubuntu 22.04 LTS release. 

### How should we solve this?

Add official apt deb repository.

### What is the impact of not solving this?

Lots of Ubuntu 22.04 upgrades will fail to retrieve new version in the coming months.

**Comment by DentonGentry** [comment]
Ah. Guess it's that time of year. Winter, Spring, Ubuntu season, Summer, Fall, Ubuntu season.

**Comment by DentonGentry** [comment]
https://pkgs.tailscale.com/stable/ has an Ubuntu 22.04 entry now, and the install.sh script handles it.

**Comment by Simonk007** [comment]
Morning,
im trying to install tailscale on a ubuntu jammy, but im gettting open ssl_connect error
Anyone got a solution for this

 curl -fsSL http://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg | sudo tee /usr/share/ke                                      yrings/tailscale-archive-keyring.gpg >/dev/null
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to pkgs.tailscale.com:443

**Comment by DentonGentry** [comment]
pkgs.tailscale.com is not down. Presumably there is a connectivity problem or firewall restriction somewhere between you and it.
