### ISSUE TITLE
FR: Support YAML for ACL definition

### ISSUE THREAD

**Issue by thewilli** [tailscale/tailscale#3953]
### What are you trying to do?

Create complex ACL set with many redundant components, which is cumbersome using JSON

### How should we solve this?

Use YAML instead of JSON. As it is a superset of JSON, all existing ACLs would remain valid.

### What is the impact of not solving this?

copy & paste, external templating

**Comment by DentonGentry** [comment]
Do you have a specific use which cannot be accommodated using JSON?

**Comment by thewilli** [comment]
@DentonGentry it's not especially about something I *cannot* do, but more about simplification, clean code and don't-repeat-yourself.

YAML was introduced especially to further simplify working with JSON-like structures for humans who cannot deal with redundancy very well ("copy&paste errors"). Consider the following ACL example, where YAML and JSON are compared, producing the same output:

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1206639/154477706-e360781e-4c78-4825-a591-497375591edf.png">

You can see, that tasks like defining tags the same way would be simplified, and the need for copy & paste would be drastically reduced.  Additionally, `huJSON` (which is used by tailscale to extend JSON with e.g. comments) isn't a standard, while `YAML` is. Automating and using additional toolchains would therefore be simplified when a switch was considered.

**Comment by thewilli** [comment]
Consider YAML an evolution - the same way JSON was embraced by all those who had to deal with XML before

**Comment by DentonGentry** [comment]
The API for working with the ACL file is a POST containing the complete ACL content: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-acl-post

The intent is that tooling would store ACLs in some kind of version control and POST to the control server to deploy an update. You're welcome to store the ACLs as YAML, and convert to JSON just before the POST.

I don't see sufficient value in converting the ACL definition to YAML in control to be worth the disruption. We might consider adding YAML as an alternate, but realistically this isn't something we'd ever actually get to. So I'm going to close this and decline to implement this feature request.
