### ISSUE TITLE
Exit Node on Android partially works

### ISSUE THREAD

**Issue by zt4** [tailscale/tailscale#3961]
### What is the issue?

Enabled an Exit Node on Android. Most web sites load correctly. However some sites always fail to load the entire page (progress bar gets part way across and hangs) or some functionality breaks (likely content hasn't fully loaded, and something is waiting for a timeout). 

### Steps to reproduce

Enable magic DNS, override local DNS, and use an Exit node. If I disable the override local DNS setting, the issue appears to go away. I use my own DNS servers that have tailscale on them. They block ads via DNS of 0.0.0.0. This is possibly related. However if I specifically try to go to a blocked domain, the browser immediately returns a DNS failure and doesn't "hang".

### Are there any recent changes that introduced the issue?

No. Has never worked properly.

### OS

Android

### OS version

Android 12

### Tailscale version

1.20.2

### Bug report

BUG-b5f7a91b83caf28aafe6843a6b08e696cb437b0bd181837d884699296015b552-20220217084850Z-623e3a4720e0c7f6

**Comment by SaphireLattice** [comment]
Having a somewhat similar issue when using an exit node with all routing. On my Linux machine, it just sets DNS to `100.100.100.100` in resolv.conf and somehow ignores the "Global Nameservers" setting from the Admin UI. I end up adding `1.1.1.1` and `8.8.8.8` manually.
Desktop has `Feb 18 11:36:38 cinnabar tailscaled[89598]: dns: error: context deadline exceeded` in recent journal logs for tailscale after changing DNS settings a bit in admin. Also has `Feb 18 11:59:48 cinnabar tailscaled[951919]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[] MatchDomains:[]}` there, even though I set DNS server overrides.

On phone (Android 9, Linux 4.4.146, Tailscale 1.20.3-t8e643357d-ge1751fa2802 from Google Play, BUG-08575da2e6c9c9f35dd30c66feebf8128595b5894e60a46ad9b1f85c6917619c-20220218044438Z-5d0fbe2a8e8d7eba), I can't even edit any DNS settings and resolv.conf stuff, so tailscale... *probably* sets it to `100.100.100.100` and walks away? Not sure if this net settings app only lists one DNS server or not, but yeah...

Actually on desktop

**Comment by bradfitz** [comment]
When you're using an exit node, it's intentional that DNS is overridden to be 100.100.100.100. Then 100.100.100.100 forwards your DNS queries over WireGuard to the exit node for that exit node's DNS server to handle.

**Comment by DentonGentry** [comment]
Looking at the original bugreport BUG-b5f7a91b83caf28aafe6843a6b08e696cb437b0bd181837d884699296015b552-20220217084850Z-623e3a4720e0c7f6, we see:

```
2022-02-17 08:48:49.550414023 +0000 UTC: 12.9M/203.8M open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:w:x:y:z]:50454 => [2600:q:r::s]:443) to node [GUlDI]; online=yes, lastRecv=8s
2022-02-17 08:48:49.74330119 +0000 UTC: 12.9M/203.8M open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:w:x:y:z]:50478 => [2600:q:r::s]:443) to node [GUlDI]; online=yes, lastRecv=8s
2022-02-17 08:48:49.839828574 +0000 UTC: 12.9M/203.8M open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:w:x:y:z]:50486 => [2600:q:r::s]:443) to node [GUlDI]; online=yes, lastRecv=8s
2022-02-17 08:48:50.031461672 +0000 UTC: 12.9M/203.8M open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:w:x:y:z]:37388 => [2600:q:r::s]:443) to node [GUlDI]; online=yes, lastRecv=8s
2022-02-17 08:48:50.062582603 +0000 UTC: 12.9M/203.8M open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:w:x:y:z]:50514 => [2600:q:r::s]:443) to node [GUlDI]; online=yes, lastRecv=8s
```

where [GUlDI] is the exit node.

Shortly before those open-conn-track timeouts start, we see:
```
2022-02-17 08:37:48.021104293 +0000 UTC: 14.9M/196.4M Received invalid response message from 1949432021056804ef9d8abbce3fa42d0c0e5560e0199b244bb4031ffefbb53c
```
I don't immediately know what this is.

--------

One other thing I noticed but don't think is the root cause is that there is not a default route in the endpoint. This might actually be normal for Android, I just haven't noticed it before. 
`2022-02-17 08:39:02.918686279 +0000 UTC: 15.2M/196.4M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={rmnet0:[2605:REDACTED/64] rmnet1:[2605:REDACTED/64] tun0:[w.x.y.z/32 fd7a:115c:a1e0:ab12:REDACTED/128] v4-rmnet0:[192.0.0.4/32] wlan0:[192.168.x.y/24]} v4=true v6=true}`

**Comment by zt4** [comment]
@DentonGentry Is there anything I can do to further debug? I can reproduce the issue every time. Thanks.

**Comment by nsauk** [comment]
I have weird DNS issues for which the expression 'partially works' is perfectly suitable, but I'm not sure that this is the same problem. @zt4 could you clarify please: do you use Android as an exit node or as a client connected to an exit node?

**Comment by zt4** [comment]
@nsauk I use Android as the client connected to a Raspberry Pi as the Exit node.

I no longer have this issue. It should be closed. I don't know what fixed it. Either a new Tailscale version or a new Android version. Either way, I can no longer reproduce the issue.
