### ISSUE TITLE
Preference for "Use Tailscale subnets" is reset to `on` upon macOS app launch

### ISSUE THREAD

**Issue by adamfeldman** [tailscale/tailscale#3962]
### What is the issue?

Anytime the Tailscale macOS app is quit and reopened, the "Use Tailscale subnets" setting is turned back `on`, even if it was `off` when the app was quit.

App version: 1.20.4
macOS 12.2.1, was observed in all prior macOS 12 versions (maybe macOS 11.x too...).

I keep the "Use Tailscale subnets" setting `off` except when needed. This appears to prevent a problem where ~100mbits of "unknown" traffic would flow from my machine out through Tailscale. 

That "unknown" traffic is possibly related to enabling macOS "Content Caching" on my machine, but that's just a reasonable guess – if that was the case, the "unknown" traffic is macOS and iOS clients at other locations pulling from my machine's cache.

![ts prefs@2x](https://user-images.githubusercontent.com/133385/154566817-651cd0c1-9b1e-4693-9e0c-0cf6ab4b8cef.png)

### Steps to reproduce

1. Disable "Use Tailscale subnets"
2. Quit app
3. Reopen app and observe that the setting is enabled

### OS

macOS

### OS version

macOS 12.x

### Tailscale version

1.20.4

### Bug report

BUG-c88a14e311ea486c26bab018068d32b91a62585b53605b4b1571f23a9bf957ec-20220217212510Z-18de9d30be6a4daa

**Comment by adamfeldman** [comment]
This setting also sets itself back on after updating the macOS App Store version of the app – that's in addition to after "normal" app launches.

**Comment by bradfitz** [comment]
FYI: worst case this'll be in 1.26.0 in about a month unless we decide to cherry-pick it a point release but I'd guess that's unlikely.
