### ISSUE TITLE
CentOS7: missing tailscaled.sock after server restart

### ISSUE THREAD

**Issue by lukasa1993** [tailscale/tailscale#397]
running on centos 7, after force restart of server `/var/run/tailscale/tailscaled.sock` this is missing and reinstall doesn't help so i am out of options not sure if its bug but don't know where to ask

**Comment by bradfitz** [comment]
tailscaled.sock is created by running tailscaled.

Are you running tailscaled?

What did you do & how did you see that error message?

Can you flesh out this bug report a bit?

**Comment by lukasa1993** [comment]
i was using it for like 3 days everything was good today server stuck and i had to force restart it.
i am seeing this when i run `sudo tailscale up`

**Comment by bradfitz** [comment]
@danderson, does the CentOS 7 package not mark tailscaled as starting on boot?

**Comment by lukasa1993** [comment]
@bradfitz it was working tho… can i check anything extra on server to more inform you ?

**Comment by bradfitz** [comment]
@lukasa1993, I was theorizing that the package might started tailscaled post-install, but not in a way that survives a reboot. I don't know CentOS. That's why I asked @danderson.

Can you run `sudo systemctl start tailscaled`? And `sudo systemctl status tailscaled`? And then does it work?

**Comment by lukasa1993** [comment]
```

**Comment by lukasa1993** [comment]
@bradfitz if i dont disable tailscaled service it hangs ssh and even mosh and you cant login to server without hard restart…

**Comment by bradfitz** [comment]
Are you saying that you disabled the tailscaled service then?

If so, that might've been interesting information to start with. :-)

**Comment by lukasa1993** [comment]
i disabled after all this… because it halts ssh and i cant login to server anymore

**Comment by apenwarr** [comment]
Luka, do you have automatic updates enabled? Are you using the
tailscale stable or unstable track? Unstable has been changing its
firewall behaviour lately, so if you've been using that track, it's
possible you've found a bug.

On Thu, May 21, 2020 at 12:02 PM luka dodelia <notifications@github.com> wrote:
>
> i disabled after all this… because it halts ssh and i cant login to server anymore
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by lukasa1993** [comment]
@apenwarr https://www.tailscale.com/kb/1048/install-centos-7 i followed this 3 days ago was very happy and today it started acting out :)

**Comment by bradfitz** [comment]
Can you give us a complete series of events? You installed it, then did you reboot before it stopped working?

**Comment by lukasa1993** [comment]
i installed for 3 days it was ok, today i wanted to login with ssh with taislcale ip  100.x.x.x it was timming me out i tried to login directly it was still timing me out, then i force restarted it i coudn't start tailscale up was saying this error and if i dont disable tailscaled service it again blocks ssh somehow and i cant login anymore

**Comment by DentonGentry** [comment]
It has been a year since this was reported, with no further occurrences. There are quite a few users running CentOS7. I think this problem has been resolved some time ago.
