### ISSUE TITLE
Using exit node seems to break DNS

### ISSUE THREAD

**Issue by SaphireLattice** [tailscale/tailscale#3971]
### What is the issue?

I have a tailnet set up with exit nodes, always on more or less.

Tailnet DNS has 1.1.1.1 and 8.8.8.8, breaks with either Magic DNS or not, overriden or not... guessing due to exit node setup?

- **Exit node**:NixOS, `anguis`, config without Nginx stuff https://gist.github.com/SaphireLattice/d404c87f09e1b1e8fa7e1b0754633d4c
  - Tailscale 1.20.3 (go1.17.6)
- Phone: Cosmo Communicator, Android 9
  - Tailscale 1.20.3-t8e643357d-ge1751fa2802 from Google Play
  - Linux 4.4.146, 
  - `BUG-08575da2e6c9c9f35dd30c66feebf8128595b5894e60a46ad9b1f85c6917619c-20220218044438Z-5d0fbe2a8e8d7eba`
- Desktop: Archlinux, `cinnabar`, updated somewhere a week or two ago
  - Tailscale 1.20.2 (8e643357dc806ad10adbd833abbc5181c99ce305, go1.17.6)
  -  `Linux cinnabar 5.16.7-arch1-1 #1 SMP PREEMPT Sun, 06 Feb 2022 16:47:29 +0000 x86_64 GNU/Linux`
  - Network manager, *also* seems to bork Docker connectivity when Tailscale is up but should look into that later

Thanks for the comment explaining how this works so I can provide better info ^^ https://github.com/tailscale/tailscale/issues/3961#issuecomment-1043901132

Ping (from `cinnabar`, Archlinux machine) works:
```
PING 100.100.100.100 (100.100.100.100) 56(84) bytes of data.
64 bytes from 100.100.100.100: icmp_seq=1 ttl=64 time=0.126 ms
64 bytes from 100.100.100.100: icmp_seq=2 ttl=64 time=0.135 ms
64 bytes from 100.100.100.100: icmp_seq=3 ttl=64 time=0.280 ms
64 bytes from 100.100.100.100: icmp_seq=4 ttl=64 time=0.155 ms
```
But `dig @100.100.100.100 google.com`:
```
; <<>> DiG 9.16.25 <<>> @100.100.100.100 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

### Steps to reproduce

1. Have a tailnet with a NixOS server node, a "generic" network-manager arch install, and a generic Android 9 phone with not that many updates or support
2. Update NixOS to latest (Roughly 2021-11-30 -> 2022-02-13)

### Are there any recent changes that introduced the issue?

I have updated NixOS (`sudo nixos-rebuild switch --upgrade`) from how it was at 2021-11-30, to 2022-02-13

### OS

Linux, Android

### OS version

NixOS

### Tailscale version

1.20.3

### Bug report

BUG-28ed48998595b821a0e55511c813d4539d0bccbc44f48a446bb6ff7483653fa3-20220218060520Z-8d656f5f4d21632c

**Comment by DentonGentry** [comment]
Please install 1.20.4 on the exit node. The rest of the nodes can stay on 1.20.3 or whatever.

**Comment by SaphireLattice** [comment]
Ah, that might need some percussive maintenance on my nix config, or poking their package repository. Will try to do that, thanks!

**Comment by SaphireLattice** [comment]
Thanks, this worked, though had to mess with my packaging stuff a bit, but that's what I get for using `unstable` nix. Thank you so much for basically telling to update xD Definitely resolved now!
