### ISSUE TITLE
FR: net/dns: integration with dnsmasq

### ISSUE THREAD

**Issue by wildy** [tailscale/tailscale#3980]
### What are you trying to do?

Hi.

It would be really nice if there was an option to tell Tailscale to integrate into running local dnsmasq instead of trying to mangle  resolv.conf.

For example, I have lots of domains I need to route to different resolvers (since I run VPNs to two different companies, and have a domain in my home LAN, etc...). I'm using dnsmasq on my Linux machines as a DNS cache and DNS router.

Currently, I just use static zone mapping for each of my tailscale devices, but it's less than ideal.

### How should we solve this?

Probably add a switch to generate `servers-file` for dnsmasq, or add its DNS servers to somewhere in `/etc/dnsmasq/conf.d`.

**Comment by DentonGentry** [comment]
The ways to do this:
- as Maisem mentioned, use `--accept-dns=false` and configure dnsmasq however you like. 100.100.100.100 should still respond to queries it is directly sent, so dnsmasq could send it `*.example.com.beta.tailscale.net` for example.
- Set up a node running dnsmasq somewhere on your tailnet, and configure its Tailscale IP address as the global DNS server for your tailnet.

**Comment by DentonGentry** [comment]
I believe configuring dnsmasq to consult 100.100.100.100 for example.com.beta.tailscale.net is a workable solution.

**Comment by shulinwz** [comment]
> Have you considered making '100.100.100.100' an upstream server to dnsmasq and setting 'tailscale up --accept-dns=false'?

This doesn't work. With "tailscale up --accept-dns=false", Tailscale DNS server is not able to resolve any name.

Log messages in tailscaled.service journal
```
dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:6}
dns: Resolvercfg: {Routes:{} Hosts:6 LocalDomains:[]}
dns: resolver: forward: no upstream resolvers set, returning SERVFAIL

```

**Comment by DentonGentry** [comment]
The suggestion is to use dnsmasq **instead of** relying on tailscale to propagate DNS settings, if that is what you want to do.

The key point is that 100.100.100.100 will still answer queries sent to it for example.com.beta.tailscale.net. If you set up dnsmasq and have dnsmasq forward queries to 100.100.100.100, dnsmasq will get an answer back from the local tailscaled.

**Comment by shulinwz** [comment]
Yeah, just realized 100.100.100.100 was still able to handle queries for MagicDNS domains in beta.tailscale.net. It's not able to handle queries for Split DNS domains though.

**Comment by ben-xD** [comment]
@DentonGentry, would you how to get it working with using the fully qualified domain name (e.g. `example.com.beta.tailscale.net`)?

100.100.100.100 only replies with `device_name.tailnet_name`, not `device_name`. I can't see a config for dnsmasq that allows for search domains (see `search` on https://linux.die.net/man/5/resolv.conf and https://superuser.com/questions/570082/in-etc-resolv-conf-what-exactly-does-the-search-configuration-option-do).

**Comment by DentonGentry** [comment]
> @DentonGentry, do you know how to get it working without using the fully qualified domain name (e.g. device_name.tailnet_name.ts.net), and just use device_name?

search domains are a concept within the local resolver in the operating system. Once you send a DNS query to a DNS server, it is always an FQDN. MagicDNS will respond to FQDNs for which it is authoritative, example.com.beta.tailscale.net or ts0123456.ts.net or tails-scales.ts.net.
