### ISSUE TITLE
Unable to ping to or from Linux Fedora 34 on immers.cloud

### ISSUE THREAD

**Issue by larryqiann** [tailscale/tailscale#3982]
### What is the issue?

The Tailscale client is installed on a Fedora 34 (Cloud Edition) server VM on immers.cloud. All ports are opened. Tailscale is started and the Tailscale IP can be seen in tailscale ip, and tailscale down/up cycle has been performed. 

However, tailscale ping cannot reach any other devices in the tailnet. All other devices are able to connect to each other, and this node shows up in the Tailscale apps on other devices. 

The bugreport id is BUG-664ba98015fc8575cd58e64a939fe74cbdc283821530c986f32fc1654f26c29e-20220219095306Z-db9c4a76adc4365f

tailscale netcheck:

Report:
	* UDP: true
	* IPv4: yes, 109.248.xxx.xxx:38034
	* IPv6: no
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping: 
	* Nearest DERP: Frankfurt
	* DERP latency:
		- fra: 41.6ms  (Frankfurt)
		- lhr: 51.1ms  (London)
		- nyc: 110.7ms (New York City)
		- ord: 122ms   (Chicago)
		- dfw: 141.8ms (Dallas)
		- tok: 169.9ms (Tokyo)
		- sfo: 175ms   (San Francisco)
		- sea: 183.1ms (Seattle)
		- sin: 190.4ms (Singapore)
		- blr: 209.4ms (Bangalore)
		- sao: 225.9ms (São Paulo)
		- syd: 311.8ms (Sydney)
[fedora@server-test ~]$ 

Thank you for any assistance!

### OS version

Fedora 34

### Tailscale version

1.20.4

### Bug report

BUG-664ba98015fc8575cd58e64a939fe74cbdc283821530c986f32fc1654f26c29e-20220219095306Z-db9c4a76adc4365f

**Comment by larryqiann** [comment]
Edit: Pinging is now working using tailscale ping from the server, but SSH is not working, and pinging the server does not work

**Comment by DentonGentry** [comment]
Having outgoing ping work but incoming ping not work sounds like there is a stateful firewall somewhere which is set to block even incoming ICMP. A firewall able to block packets on tailscale0 must be running on the node itself (firewalld?), a firewall in immers.cloud wouldn't see the Tailscale packets at all.

**Comment by wale** [comment]
This is also a problem with Fedora 35 [Workstation], where I can't ping to, let alone access an external Tailscale IP that was provided to me. 

`tailscale netcheck`:
```
2022/02/24 13:53:27 portmap: [v1] UPnP reply {Location:http://192.168.20.1:5431/dyndev/uuid:18f145e6-1add-dd1a-e645-f118f1e6dd0000 Server:Custom/1.0 UPnP/1.0 Proc/Ver USN:uuid:18f145e6-1add-dd1a-e645-f118f1e6dd0000::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nServer: Custom/1.0 UPnP/1.0 Proc/Ver\r\nEXT:\r\nLocation: http://192.168.20.1:5431/dyndev/uuid:18f145e6-1add-dd1a-e645-f118f1e6dd0000\r\nCache-Control:max-age=1800\r\nST:urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN:uuid:18f145e6-1add-dd1a-e645-f118f1e6dd0000::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
2022/02/24 13:53:27 portmap: UPnP meta changed: {Location:http://192.168.20.1:5431/dyndev/uuid:18f145e6-1add-dd1a-e645-f118f1e6dd0000 Server:Custom/1.0 UPnP/1.0 Proc/Ver USN:uuid:18f145e6-1add-dd1a-e645-f118f1e6dd0000::urn:schemas-upnp-org:device:InternetGatewayDevice:1}

Report:
        * UDP: true
        * IPv4: yes, 121.200.4.60:57273
        * IPv6: no
        * MappingVariesByDestIP: true
        * HairPinning: false
        * PortMapping: UPnP
        * Nearest DERP: Sydney
        * DERP latency:
                - syd: 24.9ms  (Sydney)
                - sin: 93.1ms  (Singapore)
                - sfo: 169.1ms (San Francisco)
                - tok: 176.9ms (Tokyo)
                - sea: 183.4ms (Seattle)
                - ord: 218.1ms (Chicago)
                - nyc: 219ms   (New York City)
                - dfw: 224.7ms (Dallas)
                - fra: 236.7ms (Frankfurt)
                - lhr: 253.7ms (London)
                - blr: 259.4ms (Bangalore)
                - sao: 348.3ms (São Paulo)
```

**Comment by DentonGentry** [comment]
ETIMEDOUT. This appears to be a firewall issue allowing only outgoing connections, and listening on the tailscale0 interface.
