### ISSUE TITLE
FR: iOS Shortcuts Support

### ISSUE THREAD

**Issue by emilytrau** [tailscale/tailscale#3984]
### What are you trying to do?

I’d love to be able to toggle Tailscale on/off more easily without opening the app as I can’t leave it on all the time yet with the battery life.

### How should we solve this?

One way might be to add a Control Centre widget. Even more flexible might be integration into the Shortcuts app.

### What is the impact of not solving this?

It’s a minor inconvenience

### Anything else?

<3

**Comment by danielresnick** [comment]
+1 this would be super helpful to me - I thought about prepping a PR but then realised the iOS client isn't open source at this stage.

**Comment by stevetrease** [comment]
+1 from me.

**Comment by bradfitz** [comment]
Please don't +1 things. That just sends email spam to people who've subscribed to issues. Use the GitHub emoji reactions in the top right corner instead, thanks.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2504
