### ISSUE TITLE
Android Exit Node not passing traffic

### ISSUE THREAD

**Issue by cyrus104** [tailscale/tailscale#3986]
### What is the issue?

I'm testing Tailscale in my homelab and have several subnets. The VMs are able to talk via a firewall rule / route on an OPNsense router. One device is an Pixel 6 Pro that I want to use as the exit node (using the debug secret function). The other device is an Ubuntu VM on a different VLAN.

After making my first mistake, I enabled the exit node in the web interface which got me to here.

I have tested a tailscale ping of 8.8.8.8 and a local network accessible to the Android only `10.*.40.4` and `10.*.10.4` (a different subnet but only accessible from the vlan the phone is on. It's blocked on the vlan the vm is on. I'm using this as a test. The output for both are the same:
pong from pixel via DERP(sea) in 535ms (normal for me right) 
Interesting when I regular ping the time is 3 times 

Android Setup:
VLAN: 10.*.40.157/24

Ubuntu VM Setup:
192.168.*.19/24

tailscale ping 100.100.100.100
pong from pixel via DERP(sea) in 535ms (normal for me right)

dig@100.100.100.100 google.com
1 server found
global options; +cmd
connection timed out; no servers could be reached

### OS

Linux, Android

### OS version

Ubuntu 21.04, Android 12

### Tailscale version

1.20.4, 1.20.2

### Bug report

BUG-4ab0854226c742e3d4ca193566696dc1ac8d667175807e29f0706ed8a7657da1-20220220023919Z-49240ffdcfa6270f

**Comment by bradfitz** [comment]
> tailscale ping 100.100.100.100

That command doesn't make sense, as 100.100.100.100 doesn't exist anywhere on the network. It's a virtual IP that runs on every Tailscale node. Did you really run that, or did you make that up while trying to redact your Tailscale IP?

Your Tailscale IPs are safe to share publicly. Nobody can do anything with them. Yours are 100.123.6.37 (Ubuntu) and 100.114.213.119 (Android). What does `tailscale ping 100.114.213.119` from your Ubuntu box say? I suspect it'll still use DERP because your router doesn't seem to support hairpinning.

Your Android phone seems to be changing DERP homes all the time. Is there some other VPN/proxy involved here?

**Comment by cyrus104** [comment]
Whether it makes sense or not, tailscale is generating the response. When I do the ping on my phone for 100.100.100.100, it times out. So something inside tailscale is responding. Here is a screen shot of it. The first line is with the pixel tailscale, deactivated so there is no reply on the exit node. The second line is 5 second later after I activated the pixel.
![image](https://user-images.githubusercontent.com/1534067/154829877-c4880325-6af6-42e6-aa16-b7788a25b348.png)

Not sure what determines if something supports hairpinning. The router supports routing of internal and external IPs but there's no way upnp is being enabled on it.

My ISP is slow and routes it traffic back to the US. Not something I can controll.

**Comment by bradfitz** [comment]
k, let's check sometime. First, from Ubuntu, get the peerapi port of pixel-6-pro-1, like:

```
$ tailscale ping --tsmp 100.114.213.119
```

It'll say something like:

```
pong from pixel-6-pro-1 (100.114.213.119, 52462) via TSMP in 43ms
```

That `52462` or whatever is the port number.

Then run:

```
$ curl http://100.114.213.119:$THAT_PORT/dns-query?q=google.com
```

What does that say?

That will test whether the DNS proxy in Tailscale on your Android is working.

**Comment by cyrus104** [comment]
I was able to test this and the response is:
["172.217.14.206"]

**Comment by bradfitz** [comment]
https://github.com/tailscale/tailscale/pull/4465 is submitted for 1.24.0 and will likely help make this more reliable. Keeping open until confirmed.

**Comment by DentonGentry** [comment]
The node which sent the bugreport (4ab0854226c742e3d4ca193566696dc1ac8d667175807e29f0706ed8a7657da1) is now running 1.24.0. Did it make a difference?

**Comment by DentonGentry** [comment]
We'll assume 1.24 resolved this issue.
return -ETIMEDOUT
