### ISSUE TITLE
100.100.100.100 route disappeared

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#3989]
### What is the issue?

My DNS server which has an upstream for `ts.net` to `100.100.100.100` stopped responding to `ts.net` queries. I finally figured out that the route for `100.100.100.100` had somehow been dropped on the machine.

```
 maisem@nix: ip r s t 52 | grep 100.100.100.100
 maisem@nix: echo $?
 1
```

Running `tailscale down && tailscale up` fixed it

### Steps to reproduce

No clue, just want to track it for now.

### OS

Linux

### OS version

NixOS

### Tailscale version

1.18.2

### Bug report

BUG-82b9c8199f276ca5a42b3969f517c4217c955deb07a7bc063481ebece2e6ffaa-20220220201852Z-18db74e5f899ce94

**Comment by DentonGentry** [comment]
There used to be a problem where systemd-networkd was removing route entries: https://github.com/tailscale/tailscale/issues/1591

**Comment by DentonGentry** [comment]
At this point I don't expect to diagnose the original reported issue, too long ago.
