### ISSUE TITLE
option typo at https://hub.docker.com/r/tailscale/tailscale

### ISSUE THREAD

**Issue by mpl** [tailscale/tailscale#3990]
### What is the issue?

At the bottom of the page there's the instruction:

```
docker exec tailscaled tailscale up --auth-key=$KEY
```

and as far as I can tell (and at least with the image tailscale/tailscale:latest), the option should be `--authkey` instead of `--auth-key`.

### Steps to reproduce

I tried running the given command, which returned the error : 

```
flag provided but not defined: -auth-key
```

### OS

macOS

### OS version

macOS Monterey

### Tailscale version

1.20.4

**Comment by DentonGentry** [comment]
This typo comes up often enough that in 1.22 we're making `--auth-key=` and `--authkey=` both work: https://github.com/tailscale/tailscale/pull/3958

However for the benefit of using older releases in containers, we can update the dockerhub description.

**Comment by mpl** [comment]
ah, good to know, thanks.
Do you want me to close the the issue?

**Comment by DentonGentry** [comment]
`--authkey` and `--auth-key` both work now.

**Comment by mayakacz** [comment]
This is now also updated on Docker Hub to use `--authkey` instead of `--auth-key`.
