### ISSUE TITLE
Android Client Relay/Direct Flopping

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#3993]
### What is the issue?

Accessing  my Los Angeles Tailscale exit node via China/Shanghai over mobile 4g/5g  is exhibiting strange behavior:

1) Location Shanghai, 5G Unicom. Tailscale flip/flops during direct or relay via singapore "sin" relay every few second during fast.com speed test causing complete connection breakage.

2) Location Shanghai, 4G Unicom. Tailscale flip/flops during direct or relay via san fran "sfo" relay every few second during fast.com speed test causing complete connection breakage.

3) Location Shanghai, fiber, China telecom, stable direct connection. No issues observed. 

Is there any way for me to manually disable RELAYS via ACL? Any relay from China as source is guaranteed disaster. 

For whatever reason, connecting to my exit node using tailscale on 4g/5g is causing some kind of relay/direct flopping. 

### OS

Server: Ubuntu 22.04
Client: Android 11

### Tailscale version

Server: Tailscale 
`1.21.112
  tailscale commit: d19a63ddf631a2ef1080e3314a2b34456508a119
  other commit: efeeee5c00a6c8cabc6ce45c6b83fc4b58bc64c6
  go version: go1.17.7-tsfd6b85b80f
`
Client:  Android Client 1.21.112-tdxxxx4

### Bug report

Server/Exit-Node: 

`BUG-5492e664978e1156a93fedc9715eeefbc802144e9414fa961c765a11ebe0477a-20220221102131Z-3ccdeae4e2eff520`

Android Client:

`BUG-d894421f2aee32d25eb8682d0b922fb2b149bc20da7b9416954e4c79f4b0cd66-20220221102838Z-f6642711d91cf15c`

**Comment by diegomontoya** [comment]
I have worked around the issue by completely disabling ALL Tailscale DERP regions via ACL per doc. Now Android from China 4G/5G has no issue establishing direct connection to my LA tailscale exit node via direct:

https://tailscale.com/kb/1118/custom-derp-servers/

`
{
  // ... other parts of ACL
  "derpMap": { "Regions": { "1": null }}
}
`

**Comment by bradfitz** [comment]
Sorry, but we can't provide support for non-commercial customers in China. If you have a support contract, you can email support@tailscale, though. Fighting the Great Firewall is not a good use of our time. This might not be a China issue at all, but historically we've spent too much time fighting issues where it was. If there's a mobile issue here, we'll address it as part of debugging a similar issue elsewhere that doesn't involve the GFW.

For now I'd recommend bringing this to a forum outside of the bug tracker.
