### ISSUE TITLE
~3h+ Delay before able to connect to/from one device in network

### ISSUE THREAD

**Issue by x10an14** [tailscale/tailscale#3994]
### What is the issue?

To be able to connect to my "deadalus" server (see paste).
Neither `tailscale`'s own ping nor SSH works... =/

https://paste.sr.ht/~x10an14/c56f7469c662049f60af291a4d000a88cbd7d23f

### Steps to reproduce

https://paste.sr.ht/~x10an14/c56f7469c662049f60af291a4d000a88cbd7d23f

<details>
<summary>Machine details</summary>

```
[2022-02-21 14:00:33] 0 x10an14@home-desktop:~
-> $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```
[2022-02-21 14:02:10] 0 x10an14@deadalus:~
-> $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

</details>

<details>
<summary>NixOS tailscale config</summary>

```
{config, ...}:
  networking.firewall = {
    enable = true;
    trustedInterfaces = ["tailscale0"];
    allowedUDPPorts = [config.services.tailscale.port];
  };
  services.tailscale.enable = true;
}
```
</details>

### OS

Linux

### OS version

See above

### Tailscale version

1.20.4

### Bug report

BUG-6e0d8436d6f81dc5ff0c994a93d991b93b06a4fc39e8018347110e954d03fbb9-20220221130755Z-c049c92a14f4f87d

**Comment by x10an14** [comment]
An hour ago or so, it suddenly worked. 

None of the config changed though, which is simple enough to confirm seeing as this is NixOS.

Feel free to leave this issue open or closed, will re-name it to fit situation better.

**Comment by DentonGentry** [comment]
Seems to be resolved now.
