### ISSUE TITLE
missing ip6tables in docker

### ISSUE THREAD

**Issue by riverscn** [tailscale/tailscale#3996]
### What is the issue?

```# Health check:
#     - router: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.7 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.```

and subnet is unreachable.

### Steps to reproduce

run tailscale in docker with subnets enabled.

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

tailscale official dockerfile

### Tailscale version

1.20.4

### Bug report

BUG-9f39faf218b82b2cc6824be4245a4ca1ad20fa5920525600345c6b842e6466c4-20220221132657Z-b9243ea5d5c7c3bc

**Comment by bradfitz** [comment]
What's the host OS distro & version you're running Docker on?

What does `readlink -m $(which ip6tables)` say as root?

**Comment by riverscn** [comment]
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-100-generic x86_64)

```
# readlink -m $(which ip6tables)
/usr/sbin/xtables-legacy-multi
```

**Comment by bradfitz** [comment]
For debugging: does Tailscale work if you run it on your host directly, without Docker?

From the host, what does `lsmod` say? And `sudo iptables-save`?

**Comment by riverscn** [comment]
> For debugging: does Tailscale work if you run it on your host directly, without Docker?

No

> From the host, what does `lsmod` say? And `sudo iptables-save`?

```
$ sudo lsmod | grep table
ip6table_nat           16384  1
ip6table_filter        16384  1
ip6_tables             32768  2 ip6table_filter,ip6table_nat
iptable_filter         16384  1
iptable_nat            16384  7
nf_nat                 45056  4 ip6table_nat,xt_nat,iptable_nat,xt_MASQUERADE
ip_tables              32768  2 iptable_filter,iptable_nat
x_tables               40960  11 ip6table_filter,xt_conntrack,iptable_filter,xt_tcpudp,xt_addrtype,xt_nat,xt_comment,ip6_tables,ip_tables,xt_MASQUERADE,xt_mark```
```
$ sudo iptables-save
# Generated by iptables-save v1.8.4 on Tue Mar  1 11:56:51 2022
*filter
:INPUT ACCEPT [5497:811422]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [5236:2311623]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
:ts-forward - [0:0]
:ts-input - [0:0]
-A INPUT -j ts-input
-A FORWARD -j ts-forward
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o br-cde5a72fb0bf -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-cde5a72fb0bf -j DOCKER
-A FORWARD -i br-cde5a72fb0bf ! -o br-cde5a72fb0bf -j ACCEPT
-A FORWARD -i br-cde5a72fb0bf -o br-cde5a72fb0bf -j ACCEPT
-A FORWARD -o br-98d97ab46f88 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-98d97ab46f88 -j DOCKER
-A FORWARD -i br-98d97ab46f88 ! -o br-98d97ab46f88 -j ACCEPT
-A FORWARD -i br-98d97ab46f88 -o br-98d97ab46f88 -j ACCEPT
-A DOCKER -d 172.19.0.2/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 6880 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 9443 -j ACCEPT
-A DOCKER -d 172.19.0.3/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 8080 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 8000 -j ACCEPT
-A DOCKER -d 172.19.0.3/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 6800 -j ACCEPT
-A DOCKER -d 172.19.0.3/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.19.0.3/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 3001 -j ACCEPT
-A DOCKER -d 172.19.0.4/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 6888 -j ACCEPT
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 3000 -j ACCEPT
-A DOCKER -d 172.19.0.4/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p udp -m udp --dport 6888 -j ACCEPT
-A DOCKER -d 172.19.0.4/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 6800 -j ACCEPT
-A DOCKER -d 172.19.0.7/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 8080 -j ACCEPT
-A DOCKER -d 172.19.0.5/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 55797 -j ACCEPT
-A DOCKER -d 172.19.0.5/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p udp -m udp --dport 55797 -j ACCEPT
-A DOCKER -d 172.19.0.5/32 ! -i br-cde5a72fb0bf -o br-cde5a72fb0bf -p tcp -m tcp --dport 8082 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-cde5a72fb0bf ! -o br-cde5a72fb0bf -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-98d97ab46f88 ! -o br-98d97ab46f88 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-cde5a72fb0bf -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-98d97ab46f88 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
-A ts-forward -i tailscale0 -j MARK --set-xmark 0x40000/0xffffffff
-A ts-forward -m mark --mark 0x40000 -j ACCEPT
-A ts-forward -s 100.64.0.0/10 -o tailscale0 -j DROP
-A ts-forward -o tailscale0 -j ACCEPT
-A ts-input -s 100.88.82.102/32 -i lo -j ACCEPT
-A ts-input -s 100.115.92.0/23 ! -i tailscale0 -j RETURN
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
COMMIT
# Completed on Tue Mar  1 11:56:51 2022
# Generated by iptables-save v1.8.4 on Tue Mar  1 11:56:51 2022
*nat
:PREROUTING ACCEPT [737:69117]
:INPUT ACCEPT [230:28656]
:OUTPUT ACCEPT [503:35004]
:POSTROUTING ACCEPT [508:35408]
:DOCKER - [0:0]
:ts-postrouting - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -j ts-postrouting
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.19.0.0/16 ! -o br-cde5a72fb0bf -j MASQUERADE
-A POSTROUTING -s 172.21.0.0/16 ! -o br-98d97ab46f88 -j MASQUERADE
-A POSTROUTING -s 172.19.0.2/32 -d 172.19.0.2/32 -p tcp -m tcp --dport 6880 -j MASQUERADE
-A POSTROUTING -s 172.17.0.3/32 -d 172.17.0.3/32 -p tcp -m tcp --dport 9443 -j MASQUERADE
-A POSTROUTING -s 172.19.0.3/32 -d 172.19.0.3/32 -p tcp -m tcp --dport 8080 -j MASQUERADE
-A POSTROUTING -s 172.17.0.3/32 -d 172.17.0.3/32 -p tcp -m tcp --dport 8000 -j MASQUERADE
-A POSTROUTING -s 172.19.0.3/32 -d 172.19.0.3/32 -p tcp -m tcp --dport 6800 -j MASQUERADE
-A POSTROUTING -s 172.19.0.3/32 -d 172.19.0.3/32 -p tcp -m tcp --dport 443 -j MASQUERADE
-A POSTROUTING -s 172.19.0.3/32 -d 172.19.0.3/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A POSTROUTING -s 172.17.0.4/32 -d 172.17.0.4/32 -p tcp -m tcp --dport 3001 -j MASQUERADE
-A POSTROUTING -s 172.19.0.4/32 -d 172.19.0.4/32 -p tcp -m tcp --dport 6888 -j MASQUERADE
-A POSTROUTING -s 172.17.0.4/32 -d 172.17.0.4/32 -p tcp -m tcp --dport 3000 -j MASQUERADE
-A POSTROUTING -s 172.19.0.4/32 -d 172.19.0.4/32 -p udp -m udp --dport 6888 -j MASQUERADE
-A POSTROUTING -s 172.19.0.4/32 -d 172.19.0.4/32 -p tcp -m tcp --dport 6800 -j MASQUERADE
-A POSTROUTING -s 172.19.0.7/32 -d 172.19.0.7/32 -p tcp -m tcp --dport 8080 -j MASQUERADE
-A POSTROUTING -s 172.19.0.5/32 -d 172.19.0.5/32 -p tcp -m tcp --dport 55797 -j MASQUERADE
-A POSTROUTING -s 172.19.0.5/32 -d 172.19.0.5/32 -p udp -m udp --dport 55797 -j MASQUERADE
-A POSTROUTING -s 172.19.0.5/32 -d 172.19.0.5/32 -p tcp -m tcp --dport 8082 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER -i br-cde5a72fb0bf -j RETURN
-A DOCKER -i br-98d97ab46f88 -j RETURN
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 6880 -j DNAT --to-destination 172.19.0.2:6880
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 9443 -j DNAT --to-destination 172.17.0.3:9443
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.19.0.3:8080
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8000 -j DNAT --to-destination 172.17.0.3:8000
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 6800 -j DNAT --to-destination 172.19.0.3:6800
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 443 -j DNAT --to-destination 172.19.0.3:443
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.19.0.3:80
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 3001 -j DNAT --to-destination 172.17.0.4:3001
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 6888 -j DNAT --to-destination 172.19.0.4:6888
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 3000 -j DNAT --to-destination 172.17.0.4:3000
-A DOCKER ! -i br-cde5a72fb0bf -p udp -m udp --dport 6888 -j DNAT --to-destination 172.19.0.4:6888
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 6801 -j DNAT --to-destination 172.19.0.4:6800
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 8081 -j DNAT --to-destination 172.19.0.7:8080
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 55797 -j DNAT --to-destination 172.19.0.5:55797
-A DOCKER ! -i br-cde5a72fb0bf -p udp -m udp --dport 55797 -j DNAT --to-destination 172.19.0.5:55797
-A DOCKER ! -i br-cde5a72fb0bf -p tcp -m tcp --dport 8082 -j DNAT --to-destination 172.19.0.5:8082
-A ts-postrouting -m mark --mark 0x40000 -j MASQUERADE
COMMIT
# Completed on Tue Mar  1 11:56:51 2022
```

**Comment by riverscn** [comment]
> For debugging: does Tailscale work if you run it on your host directly, without Docker?

Yes!

With docker: No!

**Comment by bradfitz** [comment]
And what does `nft list tables` say on your host?

**Comment by riverscn** [comment]
> And what does `nft list tables` say on your host?

```
$ nft list tables

Command 'nft' not found, but can be installed with:

sudo apt install nftables
```

**Comment by 190n** [comment]
I have the same issue on Arch Linux. All the commands give the same results as they do for @riverscn, except the last one:

```
# nft list tables
table ip nat
table ip filter
table ip6 filter
table ip6 nat
```

If I mount my host's `/lib/modules` inside the container, I get a different error:

```
# Health check:
#     - router: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
ip6tables v1.8.7 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
```

which seems like something to do with the Zstandard compression (`.ko.zst`). I'm not sure if that should be a separate issue, or if it wouldn't matter if this issue itself were fixed, but it's also weird since the module works just fine on my host kernel.

**Comment by DentonGentry** [comment]
Barring further comment, we'll expect to close this as a duplicate of https://github.com/tailscale/tailscale/issues/391 during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/391

**Comment by zhj9709** [comment]
![image](https://github.com/tailscale/tailscale/assets/13991774/3b0599c2-bcbb-44eb-97fa-6262988f22ce)

```
docker exec -it tailscaled sh
rm -f /sbin/ip6tables && ln -s /sbin/ip6tables-nft /sbin/ip6tables
```
![image](https://github.com/tailscale/tailscale/assets/13991774/c011c778-44df-4d02-8936-d15d0d140f80)


```
docker restart tailscaled
docker exec tailscaled status
```
![image](https://github.com/tailscale/tailscale/assets/13991774/4c5ae487-2cb4-4b3a-bfde-00519f5cd477)
```
docker exec -it tailscaled sh
ip6tables -S
```
![image](https://github.com/tailscale/tailscale/assets/13991774/ca8a5200-e336-4aea-9d25-46378fed2309)

**Comment by DentonGentry** [comment]
@zhj9709 I don't know what this is intended to convey. If the steps to set auto-detection in https://github.com/tailscale/tailscale/issues/391 don't work for you, please file a new issue.
