### ISSUE TITLE
Broken github links on KB 1048 documentation page

### ISSUE THREAD

**Issue by hlovdal** [tailscale/tailscale#3997]
<https://tailscale.com/kb/1048/install-centos-7/> contains two links, <https://github.com/tailscale/corp/issues/1800> and <https://github.com/tailscale/corp/issues/1800#issuecomment-844290260> and this repository no longer exists.

I guess the corresponding issue/comment in this repo is <https://github.com/tailscale/tailscale/issues/2654#issuecomment-987752532>.

Same for <https://tailscale.com/kb/1051/install-centos-8/>.

**Comment by DentonGentry** [comment]
We need to pull the relevant material into the KB article.

**Comment by bradfitz** [comment]
Looks like @rosszurowski added those links in www's 2c5587e32 on May 18, 2021.

Took almost a year for somebody to notice! :)
