### ISSUE TITLE
Adapt to changing network environments better

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#4]
Overall tracking bug for network change reactivity.

When the network environment changes (e.g. switch from LTE to wifi, NAT gateway reboots and loses all its mappings), nodes should reestablish connectivity gracefully.

We currently adapt in some cases, but not others. We should always notice changes to connectivity, and adapt gracefully to them.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687424845760) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
Bug scrub.

What remains here, @danderson, @crawshaw?
