### ISSUE TITLE
Subnet Route not working

### ISSUE THREAD

**Issue by yetser77** [tailscale/tailscale#4000]
Hi, I've recently discovered Tailscale and I'm extremely happy with it but when I try to make a subnet route it does not work. Can someone tell me what I have done wrong? I've done sudo tailscale up --advertise-routes=192.168.1.0/24. My access point is 192.168.1.1, but my modem's web panel is 192.168.254.254. Should I use 192.168.254.254?

**Comment by DentonGentry** [comment]
Can you start with explaining what you're trying to accomplish?

You also deleted everything from the bug template, like what Tailscale version you're using and, most importantly, to add a bug report so we'll have something we can actually act on.

**Comment by yetser77** [comment]
I have an old Intel NUC running Jellyfin on one network and my NAS and CCTV on another. I want to access all of them when I'm not at home. Tailscale version is 1.20.4.

**Comment by DentonGentry** [comment]
Let's assume:
- the access point LAN address is 192.168.1.1
- the Jullyfin NUC is 192.168.1.2
- the NAS is 192.168.1.3
- the CCTV is 192.168.1.4

In that situation you'd want to use `--advertise-routes=192.168.1.0/24`

Be sure to approve the routes in the admin panel, or they won't actually work. https://tailscale.com/kb/1019/subnets/

**Comment by yetser77** [comment]
I did those. Screenshot for reference:
![image](https://user-images.githubusercontent.com/89842253/155056208-ca112e00-c9df-41ce-a7d6-4807689c14f1.png)

**Comment by DentonGentry** [comment]
At this rate we're going to go back and forth on this bug dozens of times.

Please describe:
- What happens when you try to use the subnet route? Does it time out, does it say destination unreachable?
- Are you outside of this LAN when you try to access it?
- Attach the output of `tailscale bugreport` from a node, immediately after trying to access the remote subnet.

**Comment by yetser77** [comment]
It says destination unreachable, I'm outside of the LAN but the NUC is not, tailscale bugreport gives this:BUG-bae5ab765ebcf03d217e184fd0b2c57302e9d4222061de12651410fa531b41bc-20220222031628Z-5074ee7ce740f76c

**Comment by DentonGentry** [comment]
We do see the subnet router reporting that it has received some connections from the remote node for the 192.168.1.0/24 subnet:
```
2022-02-22 11:15:40.882606521 +0800 +0800: Accept: TCP{100.92.x.y:33740 > 192.168.1.z:80} 60 tcp ok
```

However from the remote node we see timeouts:
```
2022-02-22 11:16:30.448370887 +0800 +0800: open-conn-track: timeout opening (TCP 100.92.x.y:33746 => 192.168.1.z:80) to node [3S/7n]; online=yes, lastRecv=11s
2022-02-22 11:16:30.448590417 +0800 +0800: open-conn-track: timeout opening (TCP 100.92.x.y:33748 => 192.168.1.z:80) to node [3S/7n]; online=yes, lastRecv=11s
2022-02-22 11:16:30.455171884 +0800 +0800: open-conn-track: timeout opening (TCP 100.92.x.y:33750 => 192.168.1.z:80) to node [3S/7n]; online=yes, lastRecv=11s
```

and the subnet router doesn't report seeing the connections with source ports 33746, 33748, 33750.

**Comment by yetser77** [comment]
Are you saying I should port forward those ports? The reason why I found Tailscale is because I'm behind CGNAT.

**Comment by DentonGentry** [comment]
You don't need to open those ports. I just need somewhere to put findings in looking into it.

**Comment by yetser77** [comment]
Is this something that occurs normally or is this new?

**Comment by DentonGentry** [comment]
Is there some other VPN installed on the remote node trying to access the subnet router? It is printing messages about trying to reach IP addresses which should not be going through the tailscale0 interface.

```
2022-02-22 10:02:56.142272167 +0800 +0800: open-conn-track: timeout opening (TCP 100.92.x.y:51404 => 13.212.w.x:80); no associated peer node
2022-02-22 10:02:57.138473762 +0800 +0800: open-conn-track: timeout opening (TCP 100.92.x.y:35296 => 38.145.w.x:80); no associated peer node
```

This looks like something is messing with the routing table. This could also explain why the subnet became unreachable and the subnet router stopped seeing traffic, if the route to 192.168.1.0/24 got removed.

**Comment by yetser77** [comment]
Well, I've previously tried to install Wireguard on Docker but it's removed now.

**Comment by DentonGentry** [comment]
I don't expect to be able to diagnose this from telemetry we have access to from here: something is strange with the routing table on the remote system. It is trying to reach several dozen different public IP addresses via the tailscale0 interface. I think the subnet route not working all the time is part of it.

**Comment by yetser77** [comment]
So, no solution as of now?

**Comment by DentonGentry** [comment]
I am saying that there is something happening on that system which is directing public IP addresses to the tailscale0 interface. You need to figure out what that is, it is messing with the routing table in that system.

**Comment by yetser77** [comment]
I'll try to reinstall the whole OS.

**Comment by yetser77** [comment]
I've reinstalled the whole OS, doesn't seem to work still. Here's the ouput of tailscale bugreport:
BUG-9ebee55cacf242efc30e9bfee3e74378bbe800f4cc6f18b5e79d2ea4f036a336-20220223002835Z-1f8d6a8a9bdcbee8

**Comment by willzhang** [comment]
> 好吧，我之前曾尝试在 Docker 上安装 Wireguard，但现在已将其删除。

is docker install have problems fro ip forward?

**Comment by DentonGentry** [comment]
There is something happening on that system which is directing public IP addresses to the tailscale0 interface. You need to figure out what that is, it is messing with the routing table in that system. I don't expect to be able to further diagnose it from here.
