### ISSUE TITLE
FR: UI messaging for errors when macOS notifications were not approved

### ISSUE THREAD

**Issue by mdeeks** [tailscale/tailscale#4006]
### What are you trying to do?

When users first install the app the first time on macOS Monterey, there is a non-obvious popup that they must approve in order to receive popup notifications from an app (this isn't specific to Tailscale). 
![image](https://user-images.githubusercontent.com/2966467/155188506-34e0e62b-13a3-47df-be45-087a1a6c006e.png)
If they don't click and and select "allow", Tailscale won't be allowed to show popups.
![image](https://user-images.githubusercontent.com/2966467/155188653-10857289-11b8-422c-b01b-ccdd1d8d4a07.png)

The problem here is that users most of the time do not realize they have to allow that and the Tailscale macOS app uses popups to explain to users that they need to reauth, for example. This unfortunately leaves a lot of our users confused at what is wrong with Tailscale when their key expires and they must reauthenticate. Example quote from a user: `it's just showing a little error triangle. Where can i find the logs about what it's mad about?`

### How should we solve this?

Adding some additional UI in the macOS app to tell users what is wrong. Unfortunately popup notifications can't be trusted to always be enabled.

### What is the impact of not solving this?

Obviously not a critical problem but it adds to confusion and increases our Q&A support load while rolling out Tailscale to large groups of people. I would be surprised if 20% of our users notice it and enable it.

**Comment by DentonGentry** [comment]
In 1.24 we're removing the current notification mechanism on macOS, in expectation of coming back to it when we have a better mechanism. There are two main reasons:
1. It is easy to miss the initial request for permission to post notification, so the majority of macOS users never actually see any notifications.
1. Therefore, the notification logic was often broken because even most Tailscale developers never see the notifications.

We need to rethink how this works. Signaling the need for re-authentication using just the menubar icon is expected to be better overall than the current experience.

As such, I'm going to close this as addressed: we're not keeping the notification mechanism as it exists today.

**Comment by jorhett** [comment]
There's a lot more to the notification problems than just this. I say the notification request and approved it. But notifications are coming through repeatedly and randomly. For example, at the 1-day until expiration I get a dozen or more of that notification. Once when I was doing a live demo, it was popping up so often that the audience starting counting how many times it appeared... and it went over 20 that time.

Then I see nothing, no other mention of expiration until it expires. At which point I receive 3-5 notifications that it will shortly expire, followed by a notification that it has expired -- all within the same second.

Finally, the wording of the notices is not helpful. The notifications tell you to reauthenticate to preserve your session, which invariably leads to a help desk call saying they can't find an option to reauthenticate.  Either provide a "reauthenticate" menu item, or reword your notification to include followable instructions.

**Comment by DentonGentry** [comment]
In 1.24 we're removing the current notification mechanism on macOS, in expectation of coming back to it when we have a better mechanism.

**Comment by mdeeks** [comment]
I discovered Jamf has support for setting notification preferences for apps. Companies that use Jamf to manage their Macs can add a notifications settings payload that enables Tailscale macOS notifications without requiring user approval. 

There is an example doc on how to do it for Microsoft Office that can be used as a template for Tailscale. Replace the bundle id with `io.tailscale.ipn.macos` plus any other applicable values: https://docs.jamf.com/technical-papers/jamf-pro/microsoft-office/10.18.0/Example_Notifications_Settings.html

I believe native macOS are currently disabled in Tailscale 1.28.x, but one day when they come back this can be an option for Jamf rollouts.
