### ISSUE TITLE
Need to logout and login again after 1.20.4 update on raspberry pi

### ISSUE THREAD

**Issue by Gnafu** [tailscale/tailscale#4011]
### What is the issue?

Updated from 1.20.1 to 1.20.4 and cannot connect to host IP anymore.
I was able to reach the services again after "sudo tailscale logout",  "sudo tailscale up"

To clarify, I wasn't able to reach the raspberry via its tailscale IP, but I was able to reach it via LAN to re-login.

Happened on both raspberry machines I have (2B and 3B+)

### Steps to reproduce

sudo apt update
sudo apt upgrade

### Are there any recent changes that introduced the issue?

Updated from 1.20.1 to 1.20.4

### OS

Linux, Other

### OS version

Raspbian 10 Buster

### Tailscale version

1.20.4

### Bug report

BUG-82418b57fc67d3dd57d53ab6987d068dc077fb5c7f5d619f2a37d5c01b6ce799-20220223111924Z-0b4aa2711347e460

**Comment by DentonGentry** [comment]
The node key had expired:
```
2022-02-23 12:18:41.621722585 +0100 +0100: control: server reports new node key [CkDNB] has expired
```
Logging out and back in also refreshed its node key. If you want it to never expire, in the three dot menu to the right of the entry in https://login.tailscale.com/admin/machines is a "Disable key expiry" option.
