### ISSUE TITLE
ACL File not saving, not giving error for some invalid syntax.

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4016]
### What is the issue?

Some invalid syntax entered into the ACL editor appears to save, but changes are reverted when the page is refreshed. 

### Steps to reproduce

On a standard allow-all line: 
```
"ACLs": [
    {
        "Action": "accept",
        "Users": ["*"],
        "Ports": ["*:*"],
    },
```
If you change `  "Ports": ["*:*"],` to `  "Ports": ["*:"],` and hit save you get the "Saved ACL Settings" response. 

Press F5, and the changes revert, but there is an error being returned in the Network Inspector: `{"status":"error","error":"ports=\"*:\": invalid port list: \"\"","data":null}`

**Comment by bradfitz** [comment]
What's the HTTP status code on that returned JSON error?

/cc @soniaappasamy

**Comment by rosszurowski** [comment]
@bradfitz status code is 400

<img width="564" alt="image" src="https://user-images.githubusercontent.com/303731/155356163-b7a053b0-515b-42c4-bdf1-1eebf3bf997d.png">

**Comment by bradfitz** [comment]
I can reproduce. We return a 400 with that JSON error but the UI is happy with that:

<img width="1286" alt="Screen Shot 2022-02-23 at 7 54 34 AM" src="https://user-images.githubusercontent.com/2621/155356142-b3f069a4-7c33-4cb5-9fad-08bd9d205722.png">

**Comment by rnhurt** [comment]
Yup, I found the same problem and was able to use the browser devtools to see that the server was returning the proper information and even had a helpful error message.  However, the front end GUI was ignoring it and saying that everything worked fine.  🤦

**Comment by rosszurowski** [comment]
This is my bad 😅 

We pushed a fix for some CSRF woes a few users have been facing, but in making that fix, I incorrectly set up an [Axios interceptor](https://axios-http.com/docs/interceptors) which was swallowing all errors, including errors in edits to ACL files.

We just merged a fix for this which should be deployed shortly. Thanks for your patience!

**Comment by rosszurowski** [comment]
Ok, the fix is deployed, and I've confirmed that ACLs do indeed error once again! Feel free to make all the mistakes you'd like, and we'll catch 'em again :)

<img width="745" alt="image" src="https://user-images.githubusercontent.com/303731/155362426-6837cc16-65a8-43a4-b762-5bcb8c51cc5c.png">
