### ISSUE TITLE
Synology DSM7 in weird state, always using relay but not pingable

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4017]
So, I can see my Synology DSM7 (named "ds916") running, but oddly it's going over a relay and not direct, even though it's on the same LAN as the client. That's mystery 1.

```
$ tailscale  status
100.70.208.69   dev                  bradfitz@    linux   -
...
100.83.132.98   ds916                bradfitz@    linux   active; offers exit node; relay "sea"; offline, tx 6648 rx 4920
```

I can TSMP ping it...

```
$ tailscale ping -tsmp 100.83.132.98
pong from ds916 (100.83.132.98, 38080) via TSMP in 20ms
```

But I can't disco ping it...

```
$ tailscale ping 100.83.132.98
timeout waiting for ping reply
^Cread unix @->/run/tailscale/tailscaled.sock: use of closed network connection (tailscaled stopped running?)
```

But I can ICMP ping it...

```
$ ping 100.83.132.98
PING 100.83.132.98 (100.83.132.98) 56(84) bytes of data.
64 bytes from 100.83.132.98: icmp_seq=1 ttl=64 time=8.25 ms
^C
--- 100.83.132.98 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 8.247/8.247/8.247/0.000 ms
```

And I can curl it, hitting both its Synology port 80 and peerapi....

```
$ curl 100.83.132.98:38080
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>
<h1>Hello, Brad Fitzpatrick (100.70.208.69)</h1>
This is my Tailscale device. Your device is dev.
<p>You are the owner of this node.
```

Trying to Taildrop to it says that it "is offline":

```
$ tailscale file cp Makefile 100.83.132.98:
# warning: 100.83.132.98 is offline
```

Bug report from the Synology: `BUG-eb048df9d29e67600863d33c2394da6f8e6f0072732f83b14b9bc92098bc3e3a-20220223164122Z-8d235e146263eb0d`

Some logs from that:

```
2022-02-23 08:37:54.292733529 -0800 PST: control: controlclient: restarting map request for "dns-os" health change to new state: writing to "/etc/resolv.pre-tailscale-backup.conf" in rename of "/etc/resolv.conf": open /etc/resolv.pre-tailscale-backup.conf: permission denied
```

But it's both in a map poll & connected to the right DERP.

No clue what's going on yet.

/cc @maisem @DentonGentry

**Comment by bradfitz** [comment]
Yeah, I think `--accept-dns=true` just can't work on DSM7:

```
root@ds916:~# tailscale up --accept-dns=true 
root@ds916:~# tailscale status
# Health check:
#     - dns-os: writing to "/etc/resolv.pre-tailscale-backup.conf" in rename of "/etc/resolv.conf": open /etc/resolv.pre-tailscale-backup.conf: permission denied
#     - dns: writing to "/etc/resolv.pre-tailscale-backup.conf" in rename of "/etc/resolv.conf": open /etc/resolv.pre-tailscale-backup.conf: permission denied

100.83.132.98   ds916                bradfitz@    linux   -
...


root@ds916:~# tailscale up --accept-dns=false
root@ds916:~# tailscale status
100.83.132.98   ds916                bradfitz@    linux   -
...

root@ds916:~# ls -l /etc/resolv.conf
-rw-r--r-- 1 root root 33 Feb 22 19:49 /etc/resolv.conf
```

Even if we gave ourselves permissions to write to that file, it's not clear that's the right way to manage DNS on Synology. It's probably owned by some Synology settings daemon.

Maybe we should make the web UI default to `CorpDNS: false` on DSM7?

/cc @crawshaw @DentonGentry @maisem

**Comment by DentonGentry** [comment]
> #     - dns: writing to "/etc/resolv.pre-tailscale-backup.conf" in rename of "/etc/resolv.conf": open /etc/resolv.pre-tailscale-backup.conf: permission denied

We had at one point made this work, because gitpod has the same situation. /etc/resolv.conf is bind-mounted from the host and therefore not in the same filesystem so we can't rename it.

We do have an open bug about resolv.conf in gitpod now: https://github.com/gitpod-io/gitpod/issues/8049
In looking at it, I thought the problem wasn't related to writing the /etc/resolv.conf file but maybe that was incorrect. Maybe we broke the handling of cases where /etc/resolv.conf cannot be renamed.

**Comment by DentonGentry** [comment]
https://github.com/gitpod-io/gitpod/issues/8049 was something else entirely, lack of ip6tables.

**Comment by bradfitz** [comment]
IIRC, the problem on this bug was that health check changes cause map polls to abort so the node ends up constantly going on/offline.

**Comment by DentonGentry** [comment]
> IIRC, the problem on this bug was that health check changes cause map polls to abort so the node ends up constantly going on/offline.

This means it is resolved now?

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Fixed.
