### ISSUE TITLE
FR: Open Authentication URL in Default Browser on Linux

### ISSUE THREAD

**Issue by billypurdue** [tailscale/tailscale#4023]
### What are you trying to do?

When I authenticate in the Linux client, I'm given a URL (e.g. To authenticate, visit: https://login.tailscale.com/a/900mixalot) - it'd be convenient if this were to open in the default browser, assuming the user had a desktop environment running.  Detecting the desktop environment running might be a challenge I suppose, given the different options that are out there.

### How should we solve this?

When passing along the URL for authentication, it could be passed to a default browser via xdg-open.

### What is the impact of not solving this?

Nothing really - I continue clicking the link in my terminal window.

### Anything else?

Perhaps instead of doing this automatically it could be an optional flag to pass to the tailscale binary.

**Comment by DentonGentry** [comment]
Detecting the desktop environment is indeed the hard part, as Tailscale on Linux is so often used for servers.

Unfortunately I think it is an intractable problem: for example if one is SSHd into a remote Raspberry Pi which happens to have the desktop running on the HDMI port that nobody is currently looking at.

**Comment by billypurdue** [comment]
> Detecting the desktop environment is indeed the hard part, as Tailscale on Linux is so often used for servers.
> 
> Unfortunately I think it is an intractable problem: for example if one is SSHd into a remote Raspberry Pi which happens to have the desktop running on the HDMI port that nobody is currently looking at.

Yeah, I almost removed all of that and just left in the bit about the optional flag, but I didn't.  Optional flag is probably the way to go.

**Comment by bradfitz** [comment]
> Unfortunately I think it is an intractable problem: for example if one is SSHd into a remote Raspberry Pi which happens to have the desktop running on the HDMI port that nobody is currently looking at.

I think between various environment variables and the process tree we could figure it out and do it by default, erring on the conservative side of not doing it (e.g. if you're in screen or tmux).

But I also think it's just low value: almost all the Linux terminal programs let you click a link to open it, which isn't much work. Certainly easier than looking up and passing a new flag to do it for you.

More valuable would be just having an official Linux GUI app, like the other platforms, where we could show notifications, status, health, etc.

**Comment by DentonGentry** [comment]
I am declining to implement this feature request.
We'd instead focus on a full GUI for desktop Linux environments.

**Comment by JoeDupuis** [comment]
Using an environment variable specific to Tailscale would save a lot of headaches for certain workflows.

I am deploying with Kamal through Tailscale SSH. Kamal uses SSHKit, and SSHKit cannot display the authentication prompt.

It would be great if I could set an environment variable and have Tailscale send the URL to that process.

For example: `TAILSCALE_BROWSER=$BROWSER bin/kamal deploy`
