### ISSUE TITLE
Win 10 Unattended doesn't get IP after reboot

### ISSUE THREAD

**Issue by 12nick12** [tailscale/tailscale#4040]
### What is the issue?

Win 10 Unattended with custom server URL doesn't get IP after reboot

I'm using headscale for the server-url

### Steps to reproduce

1. Install MSI from https://pkgs.tailscale.com/stable/#windows
2. cd "C:\Program Files\Tailscale"
3. tailscale.exe up --auth-key AUTH_KEY--accept-routes --unattended --advertise-tags "tag:admin" --login-server https://SERVER_URL
4. Machine gets IP
5. Disable autostart of tailscale GUI since I don't need/want it
6. Reboot machine
7. No IP, (Just shows the  169.254.83.107)

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.22.0   tailscale commit: b76d21c3af5a33d64beaddf8400762fcf843aa6e   other commit: 4784a730477d34bdac862e5717bc6eefc1a803b5   go version: go1.17.7-tsfd6b85b80f

### Bug report

BUG-15cc01f9fd52e9e1f93ac1afbaf5fa20dd2c944c6d48237f57a2fdb844a3e241-20220228150325Z-d8eda8476a8bf017

**Comment by juanfont** [comment]
@12nick12 I reckon you should raise this one to https://github.com/juanfont/headscale

**Comment by bradfitz** [comment]
Yeah, what @juanfont said. We can't help with Headscale issues.
