### ISSUE TITLE
FR: Adding OTP for connecting the accound

### ISSUE THREAD

**Issue by MembershipExcel** [tailscale/tailscale#4047]
### What are you trying to do?

Did you plan to add OTP for the profile connection

**Comment by DentonGentry** [comment]
Multi factor authentication would be handled in the identity provider.
If you're using Google SSO, or Microsoft SSO, or Github or Okta or whatever, the requirement for an OTP or 2factor to authenticate would be handled there.

**Comment by DentonGentry** [comment]
Nothing to followup on
