### ISSUE TITLE
Internet not working when enabling tailscale exit node

### ISSUE THREAD

**Issue by phumberdroz** [tailscale/tailscale#4049]
### What is the issue?

After enabling exit node (pop os machine) on my MacBook (or any other device other than the pop os machine) the internet is not working this is observed via `ping 8.8.8.8` and timeouts

### Steps to reproduce

1. on machine a (pop os):
❯ sudo tailscale up --accept-routes=true --advertise-exit-node
2. accept and enable exit node in web interface
3. select exit node in mac os toolbar

### OS

Linux, macOS, iOS

### OS version

macOS Monterey 12.2.1; Pop!_OS 21.10

### Tailscale version

Pop!OS: 1.22.0 Mac: 1.20.4

### Bug report

BUG-7438541fb9c35674d10587da808f9edffb88e2d8f49051b22de433786e23f105-20220301234142Z-202fd67a9dfd136f

**Comment by phumberdroz** [comment]
So I added advertising the subnet but it seems only ipv6 is working which for now is initially good enough for me. 

But I am wondering why ipv4 is not working.
New Bug:
`BUG-7438541fb9c35674d10587da808f9edffb88e2d8f49051b22de433786e23f105-20220302000200Z-75b09a9251e646ba`

**Comment by phumberdroz** [comment]
Are you accessing ipv4 subnet hosts by ip or by hostname?
ip. I am running ping 8.8.8.8 in one window and as soon as I enable the exit node in the mac os bar it times out.
Are you able to ping a public ip while using the exit node?
no.
What is the response to scutil --dns?
https://gist.github.com/phumberdroz/1338c42f4f0db27d533c608a3a3e0469

**Comment by phumberdroz** [comment]
Seems like either docker or microk8s caused issues on the host (pop is) which resulted in subnets and exit node features not working after purging both from the host it seems to be working

**Comment by JayWStapleton** [comment]
Great. I will keep an eye on that
