### ISSUE TITLE
FR: Document how to show support for an already filed feature

### ISSUE THREAD

**Issue by jtdressel** [tailscale/tailscale#4059]
### What are you trying to do?

I would like to show support for an existing feature request, in the most effective way possible. 

This form asks users to check for already suggested feature requests. It does not say what to do if a feature request already exists. It appears that some method is being used to gauge interest, with labels like `L3 Some users` and `L1 Very few`. It is not clear to me what factors influence those labels.

Some projects use "me too" comment on the issues, or emoji reactions.

### How should we solve this?

Update the form on this page https://github.com/tailscale/tailscale/issues/new?assignees=&labels=needs-triage%2Cfr&template=feature_request.yml&title=FR%3A+ 

Change 

> Please check if your feature request is [already filed](https://github.com/tailscale/tailscale/issues).

To something like

> Please check if your feature request is [already filed](https://github.com/tailscale/tailscale/issues). If already exists comment | add a reaction | subscribe

**Comment by bradfitz** [comment]
The short answer is same as most GitHub projects: emoji reactions. New "me too" comments just spam all parties. Only leave comments if there's new information to add that an emoji reaction doesn't cover.
