### ISSUE TITLE
www: link to OS-specific docs

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4061]
https://tailscale.com/kb/1069/uninstall/ has tabs/buttons for:

> Windows macOS iOS Android Linux Synology NAS

And clicking them changes the docs, but it doesn't change the #fragment of the URL, so I can't easily send the right OS-specific docs to users.

/cc @rosszurowski @mayakacz @WalterHub

**Comment by rosszurowski** [comment]
The platform picker auto detects the client's OS and will automatically select that.

We could introduce a way to default it to a given value. I'm curious how you think we should do that. URL fragments already refer to headers on the page — what if you're trying to link to a header with a particular OS? I'm wary about overloading URL fragments in this way.

**Comment by DentonGentry** [comment]
The URL changes now in all of the cases I looked at:

For articles using the platform picker:
https://tailscale.com/kb/1069/uninstall/?tab=android

For the download link:
https://tailscale.com/download/ios
https://tailscale.com/download/windows

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Next bug scrub; closing.
