### ISSUE TITLE
tailscale-synology on 1.20.x still needs the new --statedir update

### ISSUE THREAD

**Issue by davidosomething** [tailscale/tailscale#4065]
`BUG-dab8fad08821eea9935540111ef6661f09a5f7aa4fecab95d1de466d85dd2501-20220304045649Z-9b2a702003d22d41`

tailscale-synology v1.22.x is not released yet

tailscale-synology on 1.20.x still needs the new --statedir update i think, it only provides STATE_DIR environment variable

```
% sudo tailscale version
1.20.0
tailscale commit: 15e59830527efd8db1c26091afbf5d57f610ef0e
other commit: decc1907c5c0f715c6794ba2b7923ad74e04d018
go version: go1.17.6-tse44d304e54

% sudo tailscale cert mydomain.alpha-beta.ts.net # yes i changed this
HTTP 500 Internal Server Error: failed to get cert dir
(expected 200)
```

_Originally posted by @davidosomething in https://github.com/tailscale/tailscale/issues/2927#issuecomment-1058102988_

**Comment by DentonGentry** [comment]
https://pkgs.tailscale.com/stable/#spks

**Comment by davidosomething** [comment]
1.22.x no longer throws 500
but remaining synology issue tracked here: https://github.com/tailscale/tailscale/issues/4060
