### ISSUE TITLE
magicsock logspam/infinite loop?

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#407]
From troubleshooting a node going nuts and spamming us with logs ingest:

```
magicsock: rx [REDACTED-PUBKEY] from low-pri REDACTED-IPPORT (2), keeping current REDACTED-IPPORT (3)
```

This message repeats hundreds of times per second, exactly the same one each time. It kinda seems like we're reprocessing the same packet over and over, or there's a priority inversion in the two peers's magicsocks, and we're ending up with asymetric routing (one side over v6, the other over v4).

We have a rate-limiter in the codebase now, so this wouldn't spam us on a newer release... But it is pointing at something gone wrong either way.

I've seen this happening to a couple of nodes now, this is not an isolated occurrence.

**Comment by danderson** [comment]
The logspam seems to come and go on a regular basis, which suggests this occasionally fixes itself at tunnel renegotiation time.

**Comment by bradfitz** [comment]
I can take this if you'd like.

It seems that's the only case that both logs and doesn't update any state:

```go
switch {
case index == -1:
        if a.roamAddr == nil {
                a.logf("magicsock: rx %s from roaming address %s, set as new priority", pk, new)
        } else {
                a.logf("magicsock: rx %s from roaming address %s, replaces roaming address %s", pk, new, a.roamAddr)
        }
        a.roamAddr = new

case a.roamAddr != nil:
        a.logf("magicsock: rx %s from known %s (%d), replaces roaming address %s", pk, new, index, a.roamAddr)
        a.roamAddr = nil
        a.curAddr = index

case a.curAddr == -1:
        a.logf("magicsock: rx %s from %s (%d/%d), set as new priority", pk, new, index, len(a.addrs))
        a.curAddr = index

case index < a.curAddr:
        a.logf("magicsock: rx %s from low-pri %s (%d), keeping current %s (%d)", pk, new, index, old, a.curAddr)

default: // index > a.curAddr                                                                                                                                                                                                                              
        a.logf("magicsock: rx %s from %s (%d/%d), replaces old priority %s", pk, new, index, len(a.addrs), old)
        a.curAddr = index
}
```

**Comment by bradfitz** [comment]
(If you're already working on it, feel free to assign it to yourself and I'll ignore.)

**Comment by danderson** [comment]
Not working on it, I filed to not forget about it but I'm already too many yaks deep to look now. I looked only as far as verifying that this is not expected, and that it's not threatening the health of logs ingest right now.
