### ISSUE TITLE
FR: Provide entrypoint for the Docker container

### ISSUE THREAD

**Issue by danielcompton** [tailscale/tailscale#4071]
### What are you trying to do?

I'm trying to run a Tailscale subnet router on ECS Fargate.

Currently I have this entrypoint, cribbed from https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh. It's a bit awkward running `tailscaled` and `tailscale` in the same container.

```
entrypoint = ["/bin/sh", "-c", "tailscaled --tun=userspace-networking & PID=$!; tailscale up --authkey $TAILSCALE_AUTHKEY --advertise-routes=10.30.0.0/16,10.31.0.0/16,10.32.0.0/16 --accept-dns=false && wait $PID"]
```

### How should we solve this?

I would imagine providing something similar to the [run.sh](https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh) would work pretty well and be generally useful. It would let users provide flags for `tailscaled` and `tailscale` and reliably handle failures from both.

### What is the impact of not solving this?

If I want to get a more robust script my options are (I think):

1. Create and publish a new Docker image which adds a script to the built-in container. This is fine but adds more maintenance cost to update it.
2. Source the full script in the entrypoint (if it would fit)

### Anything else?

Here's part of my Terraform config for this:

<details>

```terraform
resource "aws_ecs_task_definition" "tailscale" {
  # ...
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"

  container_definitions = jsonencode([
    {
      name       = "tailscale"
      image      = "tailscale/tailscale:v1.22.0"
      entrypoint = ["/bin/sh", "-c", "tailscaled --tun=userspace-networking & PID=$!; tailscale up --authkey $TAILSCALE_AUTHKEY --advertise-routes=10.30.0.0/16,10.31.0.0/16,10.32.0.0/16 --accept-dns=false && wait $PID"]

      essential = true
      secrets = [{
        "name" : "TAILSCALE_AUTHKEY",
        "valueFrom" : local.ts_subnet_router_authkey
      }]
    }
  ])
}
```

</details>

**Comment by evilhamsterman** [comment]
I'm not sure why run.sh isn't just part of the default image, or at least publish a second image including run.sh
