### ISSUE TITLE
FR: Use nginx as proxy when running DERP

### ISSUE THREAD

**Issue by tlsalex** [tailscale/tailscale#4072]
### What are you trying to do?

Use nginx as proxy when running DERP , let's say DERP is listen on 127.0.0.1:3333 at server , and nginx is running a website www.xxx.com , but it will pass all traffic back to 127.0.0.1:3333 when it receive request from a specify url like www.xxx.com/tailscale . and the client node will connect to www.xxx.com/tailscale to connect DERP, something like tailscale over https/tls . not sure if I am right for this.

### How should we solve this?

I don't know

### What is the impact of not solving this?

it will occupy 443 port for web service -- I don't want to use non https port for communication between nodes and DERP

### Anything else?

N/A

**Comment by DentonGentry** [comment]
You're welcome to configure nginx as a front-end for derper. What would you need derper to do differently?

**Comment by danderson** [comment]
The code for the derper is open source, so you can see exactly what derper needs to receive in order to function: https://github.com/tailscale/tailscale/blob/main/cmd/derper/derper.go . nginx has to route /derp and /bootstrap-dns to derper, and allow long-running (eternal) connections as well as allow HTTP 101 protocol switches.

We don't support altering the URLs that tailscale clients request, so you can't pick what the URLs are, it has to be the above two.

**Comment by bradfitz** [comment]
You'll also need to get the UDP STUN queries in to `derper`, otherwise the client won't select it.

**Comment by 12nick12** [comment]
I use headscale which recently was updated to add a built in derp server. I was able to get the derp server working with NGiNX by enabling websockets. Add the following to your server {}

        #Websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

**Comment by DentonGentry** [comment]
I think the configuration examples posted in this bug are sufficient to do this.

**Comment by zhijun** [comment]
It's fine that Derper is not supposed to run behind Nginx, however it's arguable that it strongly require port 443 and 80.  Usually users run multiple applications besides Derp on their hosts, such like their websites.  Please, make 443 and 80 optional.
