### ISSUE TITLE
fail to install DERP server

### ISSUE THREAD

**Issue by tlsalex** [tailscale/tailscale#4075]
### What is the issue?

fail to install DERP server

### Steps to reproduce

```
go install tailscale.com/cmd/derper@main
[root@xxx ~]# go install tailscale.com/cmd/derper@main
go install: tailscale.com/cmd/derper@main: tailscale.com/cmd/derper@main: invalid version: Get "https://proxy.golang.org/tailscale.com/cmd/derper/@v/main.info": dial tcp 172.217.163.49:443: i/o timeout
```
Access https://proxy.golang.org/tailscale.com/cmd/derper/@v/main.info in browser, I will get below error:
`not found: tailscale.com/cmd/derper@v0.0.0-20220305230557-0e62a7d1a247: invalid version: missing tailscale.com/cmd/derper/go.mod at revision 0e62a7d1a247`

### Are there any recent changes that introduced the issue?

don't know

### OS

Linux

### OS version

CentOS Linux release 8.4.2105

**Comment by DentonGentry** [comment]
> dial tcp 172.217.163.49:443: i/o timeout

You need to figure out why this happened.

**Comment by DentonGentry** [comment]
172.217.163.49 is a Google CDN IP address (1e100.net). The timeout is your workstation trying to fetch information from proxy.golang.org. We can't really help with that.

You're welcome to `git clone https://github.com/tailscale/tailscale.git` and look in `cmd/derper` if you want.

**Comment by tanshiqi** [comment]
![CleanShot 2022-05-11 at 16 55 48](https://user-images.githubusercontent.com/1159607/167811257-bafb9497-d560-4f11-9203-bf12a196b3a4.png)
same problem

**Comment by ChenghuiS** [comment]
you can try to set GOPROXY, like:
`export GOPROXY=https://goproxy.io` or `export GOPROXY=https://goproxy.cn`.
