### ISSUE TITLE
Derper TLS handshake error in China: remote error: tls: internal error

### ISSUE THREAD

**Issue by StarSkyZheng** [tailscale/tailscale#4082]
### What is the issue?

It is very strange, i build an custom derper server but it always randomly broken after some times of running.
It usually be 1~6 days depends on usage. High pressure broken it sooner.
even if the option '-verify-clients' is enable, derper might broken within one hour.

Go version i used is 1.17.1 and derper server we build follow the official manual.

Then it was broken, syslog will has dozens of error logs like:
`Mar  7 11:59:52 localhost derper[268829]: 2022/03/07 11:59:52 http: TLS handshake error from 111.12.xx.xx:51574: remote error: tls: internal error`

and after about 5-10 minus then will start to generated tons of error like:
`Mar  7 12:05:00 localhost derper[268829]: 2022/03/07 21:52:56 http: TLS handshake error from 42.90.xx.xx:34461: write tcp 172.xx.xx.xx:12341->42.90.xx.xx:34461: write: connection reset by peer`

When the derper server broken, i can still see that derper marked as available in `tailscale netcheck` but actually it cannot be used, so i lost connection with many devices.

### Steps to reproduce

Use letsencrypt to generate a cert.
Build a derper server using that cert and with option: `-stun -a :12345 -certmode manual -verify-clients --certdir /xxx/derper-certs -http-port -1 -hostname xx.xxx.com` 
Wait hours or days until broken.

### OS

Linux

### OS version

centos8

### Tailscale version

derper@v1.1.1-0.20220225000201 & tailscale@1.22.0

### Bug report

derper has no bugreport option

**Comment by DentonGentry** [comment]
Are `111.12.xx.xx:51574` and `42.90.xx.xx:34461` your addresses? For example, do you have Tailscale devices behind a firewall at those IP addresses?

**Comment by bradfitz** [comment]
My first guess is that this is the Great Firewall of China (or one of the lesser internal firewalls) interfering.

**Comment by StarSkyZheng** [comment]
Sure im in China. But both that derper server and my android phone were in China, do you mean the block bewteen tailscale.com and custom derper server may lead this issue? 
As far as i know, tailscale.com hasn't been blocked in China. Maybe is caused by temporarily package lost? Can we resend that package if it were lost? That may be more  tolerant to the network of derper server.

**Comment by bradfitz** [comment]
tailscale.com doesn't talk to your custom DERP servers.

I suspect there's some interference between your Android in China and your DERP server in China. The Great Firewall is not purely about cross-border traffic.

**Comment by StarSkyZheng** [comment]
My phone and derper-vps can talk with each other, I think this may not be the core issue. Even when I login to the VPS and I still cannot curl and got the https response with `This is a derper server`. 
I just reboot derper server. When it broken next time I can upload the `curl -vvv` logs. The response of server shakehand is abnormal.

**Comment by StarSkyZheng** [comment]
It broken again. Here are the curl test:
`curl -vvv https://BROKEN.derper_server.com:12345 2>&1 | less` : 
```
* Rebuilt URL to: https://BROKEN.derper_server.com:12345/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 103.47.xx.xx...
* TCP_NODELAY set
* Connected to BROKEN.derper_server.com (103.47.xx.xx) port 12345 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (OUT), TLS alert, illegal parameter (559):
} [2 bytes data]
* error:14160098:SSL routines:read_state_machine:excessive message size
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) error:14160098:SSL routines:read_state_machine:excessive message size
```
=================================================
For normal derper server:

```
* Rebuilt URL to: https://normal.derper_server.com:12345/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 106.15.xx.xx...
* TCP_NODELAY set
* Connected to normal.derper_server.com (106.15.xx.xx) port 12345 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [21527 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, [no content] (0):
..............
..............
```

It seems like server shakehand response is abnormal.

**Comment by StarSkyZheng** [comment]
new error log:

```
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: 2022/03/14 14:15:15 http: panic serving 106.15.xx.xx:49106: cryptobyte: pending child length 17223319 exceeds 3-byte length prefix
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: goroutine 49805 [running]:
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: net/http.(*conn).serve.func1()
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/net/http/server.go:1802 +0xb9
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: panic({0x7dd5c0, 0xc000102160})
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/runtime/panic.go:1047 +0x266
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: vendor/golang.org/x/crypto/cryptobyte.(*Builder).BytesOrPanic(...)
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/vendor/golang.org/x/crypto/cryptobyte/builder.go:72
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: crypto/tls.(*certificateMsgTLS13).marshal(0xc0001177e8)
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/crypto/tls/handshake_messages.go:1307 +0x253
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: crypto/tls.(*serverHandshakeStateTLS13).sendServerCertificate(0xc000117990)
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/crypto/tls/handshake_server_tls13.go:603 +0x24a
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc000117990)
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/crypto/tls/handshake_server_tls13.go:61 +0x85
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: crypto/tls.(*Conn).serverHandshake(0xc00007a000, {0x8e7f38, 0xc00044e000})
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/crypto/tls/handshake_server.go:54 +0xd0
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: crypto/tls.(*Conn).handshakeContext(0xc00007a000, {0x8e7fe0, 0xc00044a090})
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/crypto/tls/conn.go:1445 +0x3d1
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: crypto/tls.(*Conn).HandshakeContext(...)
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/crypto/tls/conn.go:1395
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: net/http.(*conn).serve(0xc000128280, {0x8e7fe0, 0xc0000ff140})
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/net/http/server.go:1818 +0x230
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: created by net/http.(*Server).Serve
Mar 14 14:15:15 iZuf6hew62f61om8ki9uvlZ derper[325063]: #011/data/00/user/user101/software/dependent/GO/src/net/http/server.go:3034 +0x4e8
```


And curl log:
```
####  curl -vvv -k https://derper.xxx.com:12345 2>&1 ####
* Rebuilt URL to: https://derper.xxx.com:12345/
*   Trying 106.15.xx.xx...
* TCP_NODELAY set
* Connected to ali.zhengnet.xyz (106.15.xx.xx) port 12345 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to derper.xxx.com:12345
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to derper.xxx.com:12345
```

**Comment by HeIsPirate** [comment]
same problem😖

**Comment by bradfitz** [comment]
@HeIsPirate, are you also in China?

**Comment by HeIsPirate** [comment]
Yes😟, so I applied for the certificate of TrustAsia, but still
`TLS handshake error from xx.xx.xx.xx:36052: remote error: tls: internal error`

**Comment by bradfitz** [comment]
This is probably a question for your ISP. I'm not sure we can help you here.

**Comment by HeIsPirate** [comment]
Ok, Thanks for your reply💕, I will keep trying

**Comment by StarSkyZheng** [comment]
Here is a watchdog script you can have a try @HeIsPirate 

derper_watchdog.pl:
```
#!/usr/bin/env perl
use warnings;
use strict;
use v5.10;

my $web = 'https://derper.xxx.com:12345/';
my $restart_cmd = 'service derper restart';
my $sleeptime = 60;

($sleeptime) = @ARGV;

while(1) {
        my $test_cmd = "curl $web 2>&1";
        my $test = `$test_cmd`;
        unless ($test=~/This is a/) {
                say STDERR "=========================================";
                say STDERR "=========================================";
                print STDERR "Warn: restart derper server! : " . `date`;
                system($restart_cmd);
                say STDERR "=========================================";
                redo;
        }
        sleep $sleeptime;
}
```



/usr/lib/systemd/system/derper.service:
```
[Unit]
Description=Derper

[Service]
ExecStart=/root/.cache/tailscale/derper -stun -a :12345 -certmode manual --certdir /root/.cache/tailscale/derper-certs -http-port -1 -hostname derper.xxx.com
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
```

**Comment by HeIsPirate** [comment]
Found this: https://forum.tailscale.com/t/ipados-unable-to-connect-to-custom-derp-tls-bad-certificate/1107
So far so good 👍 (24 hous)

**Comment by HeIsPirate** [comment]
@StarSkyZheng 试了下正常了

**Comment by zouyq** [comment]
same with me，so I run derper in a docker container and add docker restart derper cron job every hour.

**Comment by bbhxwl** [comment]
> same with me，so I run derper in a docker container and add docker restart derper cron job every hour.

I read your blog and don't know how to solve the custom port

**Comment by kstreee-furiosa** [comment]
I've experiencing this issue too, and I run our custom DERP server on k8s cluster. We are restarting the DERP server periodically. Guess docker container environment somehow trigger the 'connection reset by peer'.

**Comment by Creling** [comment]
IMHO, it is a Custom Port related problem instead of a GFW related problem.

Firstly, I mitigate this error by changing the port **from 10000 to 443** of a derper instance running on a China VPS.

![图片](https://user-images.githubusercontent.com/43109504/179954064-70f96462-5d0e-49a7-8179-58abdb29f6cb.png)

Then, I successfully **re-produce this error on a USA VPS** by running a derper instance on **port 10000**.

![图片](https://user-images.githubusercontent.com/43109504/179954935-d3272733-7026-466f-8562-da8ff4df4be5.png)

**Comment by bbhxwl** [comment]
> IMHO, it is a Custom Port related problem instead of a GFW related problem. @bradfitz
> 
> Firstly, I mitigate this error by changing the port **from 10000 to 443** of a derper instance running on a China VPS.
> 
> ![图片](https://user-images.githubusercontent.com/43109504/179954064-70f96462-5d0e-49a7-8179-58abdb29f6cb.png)
> 
> Then, I successfully **re-produce** this error on an **American VPS** by running a derper instance on **port 10000**.
> 
> ![图片](https://user-images.githubusercontent.com/43109504/179956413-f34c7046-aea7-44bc-bd72-2d98295452b1.png)
> 
> All curl commands are invoked from the VPS that DERP instances run on.
> 
> DERP Version: 1.29.0 ( by `cat VERSION.txt`)

你是哪里的？有qq么？交流一下。

**Comment by Creling** [comment]
> 你是哪里的？有qq么？交流一下。

@bbhxwl Here is my QQ ID: https://pastebin.com/hNfn2Xr4, which will be destroyed after you fetch it.

**Comment by frankli0324** [comment]
@bradfitz derper panics, then it's a derper issue, not isp. ***even if*** it's triggered by isp's strange behavior, which seems not to be the case.

**Comment by gouku** [comment]
@frankli0324 can you share how you configure nginx to reverse proxy derper server?

**Comment by zouyq** [comment]
貌似是国内vps没备案的原因，会进行tls阻断

**Comment by frankli0324** [comment]
> "It seems that the reason is that the domestic VPS has not been filed, and TLS blocking will be performed."

not with non-standard ports.

**Comment by frankli0324** [comment]
> > "It seems that the reason is that the domestic VPS has not been filed, and TLS blocking will be performed."
> 
> not with non-standard ports.

> @frankli0324 can you share how you configure nginx to reverse proxy derper server?

I just reverse proxied the http probe server, not the stun server.

**Comment by Creling** [comment]
> "It seems that the reason is that the domestic VPS has not been filed, and TLS blocking will be performed."

As I mentioned above, this problem could be reproduced in servers in USA, so this is not a China-only problem.

**Comment by bradfitz** [comment]
The Go security team points out that the cmd/derper code's manual cert mode is at fault. It's returning the same `*tls.Certificate` value on each call, but the GetCertificate wrapper around it appends to it on each call:

https://github.com/tailscale/tailscale/blob/9996d94b3c281e537bc3ef51a694c43ebee79c2c/cmd/derper/derper.go#L234-L241

Not only is that a data race, but eventually the cert gets so big that it can't marshal anymore.

The normal LetsEncrypt mode doesn't have this problem its GetCertificate call (the one we wrap) always returns a new *tls.Certificate value.

So the fix for that panic is fixing the `manualCertManager`'s `TLSConfig` method to return a `GetCertificate` that's unique each time. Looks like this has been a problem since it was added in d8c5d00ecbaf2352f50ae3f26f795621a6e7972f. @SilverBut, interested in fixing?

**Comment by bradfitz** [comment]
I've submitted a fix. Please rebuild your `derper` binaries and try again.

**Comment by seaeaeagle** [comment]
> /usr/lib/systemd/system/derper.service:

怎么能联系到您呢？这是我的qq252255269，方便的话加一下，请教一下headscale的问题。谢谢

**Comment by kstreee-furiosa** [comment]
I still have a same issue, but I'm not located on China. After run derp server, likely saying, 1~3 hours, all connections are failed with the log on derp "write: connection reset by peer". My derp server runs on Kubernetes pod. Any clue about the connection failure?

**Comment by DentonGentry** [comment]
@kstreee-furiosa This issue has been closed, and the symptoms you've described bear no resemblance to the rest of this issue. Please open a new issue.

Note that a derper running within Kubernetes is very different from the environment in which the Tailscale derpers operate, the amount of help we can provide is limited.

**Comment by bradfitz** [comment]
See https://github.com/tailscale/tailscale/issues/11776 for the latest updates on all this.
