### ISSUE TITLE
Tailscale not creating tables for NFTables

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#4086]
### What is the issue?

Tailscale is not creating `ts-postrouting` table in nftables on ARM64 Linux 
```
sudo /usr/sbin/iptables -t nat -N ts-postrouting --wait
iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
```

```
# Health check:
#     - router: setting up nat/ts-postrouting: running [/usr/sbin/iptables -t nat -N ts-postrouting --wait]: exit status 4: iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
```

### Steps to reproduce

Restart tailscaled and tailscale up on arm64

### OS

Linux

### OS version

Debian Mendel GNU/Linux 4 (Day)

### Tailscale version

1.21.120

### Bug report

BUG-194419985916c781c32d5d902089092d9f1b2f9f723c92c64729b1b6af243fd3-20220307161953Z-b3585fc7d802000f

**Comment by bradfitz** [comment]
Doesn't look like you're running this in Docker or anything, which is usually what we see when there are iptables issues.

I see you're missing `xt_comment` and `IP_MULTIPLE_TABLES` (so IPv6 support is disabled). Both of those should be harmless, but it makes me wonder what else your kernel (4.14.98-imx) might be missing.

I don't suppose you can get a newer distro/kernel on there?

**Comment by charlieporth1** [comment]
@bradfitz I, unfortunately, cannot upgrade the device

**Comment by charlieporth1** [comment]
Do you mind explaining to me what isn't working here? I want to know if I can investigate more and fix it with a posted solution

**Comment by charlieporth1** [comment]
This is the same device as was in #3351 and seems to be related since we talked about `IP_MULTIPLE_TABLES` in both

**Comment by DentonGentry** [comment]
Please try it.

I know you want a diagnosis and fix, but we really don't know what is present or missing on this system nor why it is failing. `CHAIN_ADD failed (No such file or directory)` is not a lot to go on.

**Comment by charlieporth1** [comment]
https://github.com/netblue30/firejail/issues/2232#:~:text=update-alternatives%20--set%20iptables%20%2Fusr%2Fsbin%2Fiptables-legacy%20 would apear to be a temp work around

**Comment by routerino** [comment]
Note that As of OpenWRT 22.03 (the first version to natively use nftables), tailscale seems broken for *all* OpenWRT installations.

Installing `iptables-nft` will get tailscale going, but advertised routes appears to fail with the log saying connections passed, but in reality all attempts get refused.

Also we get this fun message now after tailscale is installed (and accurately so it appears)

![image](https://user-images.githubusercontent.com/45954722/189634577-eb23f6a8-b98b-43c5-aae0-38d3e4349f58.png)

**Comment by believerd** [comment]
> Note that As of OpenWRT 22.03 (the first version to natively use nftables), tailscale seems broken for _all_ OpenWRT installations.
> 
> Installing `iptables-nft` will get tailscale going, but advertised routes appears to fail with the log saying connections passed, but in reality all attempts get refused.
> 
> Also we get this fun message now after tailscale is installed (and accurately so it appears)
> 
> ![image](https://user-images.githubusercontent.com/45954722/189634577-eb23f6a8-b98b-43c5-aae0-38d3e4349f58.png)

same problem on Openwrt 22.03 using nft and iptables-nft, subnets and exit-node don't work.

**Comment by MrSuicideParrot** [comment]
Is there any plan to support nftables? The majority of the distributions is changing to them.

I'm having the same issues reported above with openwrt 22.03.

**Comment by DentonGentry** [comment]
We expect to handle nftables by removing use of the `iptables` command altogether as described in https://github.com/tailscale/tailscale/issues/391

We may also formalize the most recent discussion in that bug about automatically determining if `iptables-nft` is present. That is tracked in https://github.com/tailscale/tailscale/issues/5621

**Comment by DentonGentry** [comment]
At this point, ongoing work regarding nftables and the `iptables` command is tracked in:
- https://github.com/tailscale/tailscale/issues/391 to not use `iptables` at all
- https://github.com/tailscale/tailscale/issues/5621 to automatically figure out whether to use nftables

We'll track the work in those issues, and close this one.

**Comment by Marerc** [comment]
From openwrt forum. https://forum.openwrt.org/t/tailscale-and-nf-tables/143213

> install `kmod-ipt-nat` resolve this.

**Comment by ttimasdf** [comment]
> From openwrt forum. https://forum.openwrt.org/t/tailscale-and-nf-tables/143213
> 
> > install `kmod-ipt-nat` resolve this.

installing this kmod do add iptables rules for tailscale, but not for tailscaled to work correctly on openwrt 22.03. it mess up the firewall rules just like @routerino shows and neither does the router connect to my tailnet.
