### ISSUE TITLE
Data going throught DERP

### ISSUE THREAD

**Issue by estimadarocha** [tailscale/tailscale#4090]
### What is the issue?

Cannot make direct communication between peers.

Using exact machines with zerotier i get them to connect directly, any ideas?

### Steps to reproduce

machine1
tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 188.83.77.85:34272
        * IPv6: yes, [2001:8a0:de49:4900:9298:64ff:fe01:5aab]:57710
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: London
        * DERP latency:
                - lhr: 45.8ms  (London)
                - fra: 56ms    (Frankfurt)
                - nyc: 95.1ms  (New York City)
                - ord: 108.1ms (Chicago)
                - dfw: 115.9ms (Dallas)
                - sea: 153.5ms (Seattle)
                - sfo: 169.7ms (San Francisco)
                - blr: 174.7ms (Bangalore)
                - sin: 186.1ms (Singapore)
                - sao: 216.1ms (São Paulo)
                - tok: 246.1ms (Tokyo)
                - syd: 291.4ms (Sydney)

machine2
tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 80.243.86.183:42199
        * IPv6: no
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: London
        * DERP latency:
                - lhr: 41.8ms  (London)
                - fra: 53.8ms  (Frankfurt)
                - nyc: 103.5ms (New York City)
                - dfw: 134.6ms (Dallas)
                - sfo: 170.9ms (San Francisco)
                - sea: 172.1ms (Seattle)
                - ord: 178.3ms (Chicago)
                - sin: 178.4ms (Singapore)
                - sao: 199.9ms (São Paulo)
                - blr: 241ms   (Bangalore)
                - tok: 245.7ms (Tokyo)
                - syd: 255.9ms (Sydney

tailscale ping 100.100.106.43
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 287ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 99ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 98ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 96ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 96ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 101ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 98ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 95ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 98ms
pong from gbue4k-1 (100.100.106.43) via DERP(lhr) in 104ms
direct connection not established

tailscale ping 100.101.182.83
pong from gbue4k (100.101.182.83) via DERP(fra) in 96ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 96ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 95ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 96ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 97ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 96ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 103ms
pong from gbue4k (100.101.182.83) via DERP(lhr) in 97ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 96ms
pong from gbue4k (100.101.182.83) via DERP(fra) in 99ms
direct connection not established

### OS

Linux

### OS version

other

### Tailscale version

1.22.0

### Bug report

BUG-d606ec1c6f47f877f9080d05854cd565416a1021cf057ab9e424bbb43ae3ea57-20220307182508Z-90dd5db16bf3c31c

**Comment by DentonGentry** [comment]
Please send this to support@tailscale.com, going through a bug report is not an efficient way to handle this.
