### ISSUE TITLE
FR: automatically bill me for the right number of seats

### ISSUE THREAD

**Issue by zenazn** [tailscale/tailscale#4093]
### What are you trying to do?

I am trying to use Tailscale in a rapidly-scaling organization, and want to pay you for your valuable services, but want to think less about billing. Ideally, I would never think about billing.

### How should we solve this?

I want to be able to instruct Tailscale to automatically increase or decrease the number of seats in my account to correspond to my organization's actual usage.

For inspiration, I quite enjoy the way Slack bills me!

### What is the impact of not solving this?

I work around this issue by periodically bumping the number of seats on my account. I don't enjoy it! I will probably forget to do this at some point. I don't know what happens to my account if I forget, and I don't want to learn the answer.

**Comment by dfcarney** [comment]
Hi @zenazn! Metered billing is something we've been discussing internally. We don't have a timeline yet, but I agree that it would be nice for customers not to worry about adjusting the seat count.

**Comment by zenazn** [comment]
thank you @dfcarney! let me know if you need beta testers :)

**Comment by zenazn** [comment]
I was recently reminded of this feature request as I bumped the number of seats my organization pays for (to ~10% over our current usage, so I don't need to think about it for a while! I also figure it karmically balances the soft limits, which I have apparently been making use of).

I don't want to be that obnoxious user that repeatedly bumps old feature requests, so I'll let this serve as my one and only "this is still top-of-mind for me" reminder!

**Comment by mayakacz** [comment]
> I want to be able to instruct Tailscale to automatically increase or decrease the number of seats in my account to correspond to my organization's actual usage.

We released new pricing plans today that use usage-based billing: https://tailscale.com/blog/pricing-v3/. On these new plans, you check billed retrospectively each month for the number of users who actively used Tailscale (i.e., exchanged bytes of data over your tailnet).
If you are on an existing legacy plan and want to switch to a new plan, follow these instructions: https://tailscale.com/kb/1182/billing-information/#upgrading-a-plan.

**Comment by DentonGentry** [comment]
I believe this was addressed by https://tailscale.com/blog/pricing-v3/
