### ISSUE TITLE
FR: net/netns: add FreeBSD, etc support

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4120]
### What are you trying to do?

Add functionality to FreeBSD to allow exit nodes, subnet routers, etc to be more consistent. 

### What is the impact of not solving this?

FreeBSD exit nodes may have DNS issues, and don't have interface binding enabled.

**Comment by DentonGentry** [comment]
Related: https://github.com/tailscale/tailscale/issues/5573

**Comment by DentonGentry** [comment]
At this point I think FreeBSD support for kernel subnet routing is better tracked using https://github.com/tailscale/tailscale/issues/5573
