### ISSUE TITLE
FR: API to edit device hostname

### ISSUE THREAD

**Issue by jessemyers** [tailscale/tailscale#4121]
### What are you trying to do?

We run Tailscale on EC2 machines that we periodically recreate (e.g. when an AMI changes). We use a "vanity" hostname on each machine, both to identify it to end users (via Magic DNS) and to admins (via Tailscale UI/API). When we recreate a machine, it's common for the new machine to overlap with the previous machine's name; if we're not careful we end up with a `foo` and `foo-1`, which breaks our naming scheme.

At the moment, the only way to remedy this situation is to use the web console to rename machines. It'd be nice to use the API to do the same so we can automate this repair process.

### How should we solve this?

Extend the admin API to support renaming devices.

### What is the impact of not solving this?

We will continue to have to do manual work in the web console. At some scale, this manual process will be untenable.

**Comment by soniaappasamy** [comment]
Hi @jessemyers, thanks for reporting! We recently did a revamp of our API endpoints to bring it a bit closer to feature parity with the admin panel. There's now an API endpoint to edit machine names: https://tailscale.com/api#tag/devices/POST/device/{deviceId}/name
