### ISSUE TITLE
FR: CLI option to replace existing device hostname

### ISSUE THREAD

**Issue by jessemyers** [tailscale/tailscale#4122]
### What are you trying to do?

We run Tailscale on EC2 machines that we periodically recreate (e.g. when an AMI changes). We use a "vanity" hostname on each machine, both to identify it to end users (via Magic DNS) and to admins (via Tailscale UI/API). When we recreate a machine, it's common for the new machine to overlap with the previous machine's name; if we're not careful we end up with a `foo` and `foo-1`, which breaks our naming scheme.

We currently use a manual process to fix this issue after the fact. We've filed #4121 to request a way to automate this manual process. But it'd be even nicer if there was no need for this process. We'd like to be able to run `tailscale up --hostname foo` and have this do the right thing.

### How should we solve this?

The obvious thing would be to have an addition `--force-hostname` flag that influences the renaming behavior such that the new device takes over the hostname and the existing device is renamed. It'd be acceptable to us if this only worked if this only worked if the existing device was offline.

### What is the impact of not solving this?

We currently perform a manual repair process after-the-fact. This is annoying, but non-fatal, except that it requires an admin to remember to run the process. (And the repair process is currently manual, but we've filed a separate FR for that.)

At some scale, we likely will have to revisit using hostnames in this way.

### Anything else?

Related: https://github.com/tailscale/tailscale/issues/4121

**Comment by DentonGentry** [comment]
Same request as https://github.com/tailscale/tailscale/issues/4778 (which has some discussion)
