### ISSUE TITLE
Subnet routes seemingly apply on Windows even when Exit Node not in use

### ISSUE THREAD

**Issue by anaisbetts** [tailscale/tailscale#4123]
### What is the issue?

I have a relatively simple home network and I had one of my machines set up as an Exit Node with a Subnet route set up for my local network (192.168.4.0/24). Today, I've been having trouble accessing any local IP address - they would all time out but normal Internet access was unaffected. After some debugging, I got this output:

```sh
PS C:\Users\ani> Find-NetRoute -RemoteIPAddress "192.168.4.10"

IPAddress         : 100.95.164.68
InterfaceIndex    : 6
InterfaceAlias    : Tailscale
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 32
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore


Caption            :
Description        :
ElementName        :
InstanceID         : ;C<8;@B8>8:9<>55@55:8:8:8:55;
AdminDistance      :
DestinationAddress :
IsStatic           :
RouteMetric        : 0
TypeOfRoute        : 3
AddressFamily      : IPv4
CompartmentId      : 1
DestinationPrefix  : 192.168.4.0/24
InterfaceAlias     : Tailscale
InterfaceIndex     : 6
InterfaceMetric    : 5
NextHop            : 0.0.0.0
PreferredLifetime  : 10675199.02:48:05.4775807
Protocol           : NetMgmt
Publish            : No
State              : Alive
Store              : ActiveStore
ValidLifetime      : 10675199.02:48:05.4775807
PSComputerName     :
ifIndex            : 6
```

Indicating that the Tailscale adapter is claiming this route, despite my device not having the Exit Node in use! This of course broke local networking. 

### Steps to reproduce

Not sure, but I'd guess it is:

1. Set up an Exit node with a Subnet route which covers your local network
2. Attempt to access a local network address with Tailscale running but without using an Exit Node

### Are there any recent changes that introduced the issue?

I am on Windows 11 Dev Channel which may be the cause! 

### OS

Windows

### OS version

Windows 11 Dev Channel, Build 22567

### Tailscale version

1.22.0

**Comment by anaisbetts** [comment]
Hm, I guess I misunderstand how Subnet routes work - I was under the impression that Subnet routes should only apply if you have selected the Exit Node on a client. Are Subnet routes now independent of whether you have the computer providing route set as the Exit node? Has it always been that way? Am I just bad at networking / reading documentation? (yes. definitely that last one.) 😅

**Comment by DentonGentry** [comment]
Subnet routes are always applied whether or not an exit node is in use.
A device can ignore subnet routes using `--accept-routes=false` on Linux, or deselecting "Use Tailscale subnets" on macOS or WIndows.
