### ISSUE TITLE
FR: Inverse machine search in the admin console.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#4124]
### What are you trying to do?

With having ACL-tag  in use , Customers frequently only want to see user's personal devices and any of the following searches would get what they are most frequently looking for:

"NOT: (tag:teradici-windows OR tag:teradici OR tag:servers)"

"(tag:null)"      #untagged, all user personal devices are untagged because it would be too much trouble to define and maintain everyone as tag owners of a tag:user-device, all of their auth keys devices are tagged

"NOT:([cloudadmin@example.com](mailto:cloudadmin@example.com))"   # all auth keys are generated by cloudadmin account, exclude that and we'll see all user devices

"NOT:<key-based-auth>"

### How should we solve this?

By introducing the inverse search in the admin console machine search.

### What is the impact of not solving this?

Difficult to manage the machines while using lots of ephemeral nodes.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5hu4x)

**Comment by darshinimashar** [comment]
From customer: As an alternative to an inverse search, being able to search for untagged or by auth-method (eg. key-based vs non-key-based) would also do the trick.

**Comment by DentonGentry** [comment]
I'm going to lump this in with https://github.com/tailscale/tailscale/issues/2540, we'd consider it at the same time.
