### ISSUE TITLE
FR: Allow admins to set default policy to block incoming connections

### ISSUE THREAD

**Issue by danielcompton** [tailscale/tailscale#4137]
### What are you trying to do?

We're rolling out Tailscale to our org. By default we don't want any user devices (MacBooks) to get connections made to them. We're happy to let users control this setting themselves if they want to share something with a coworker, but that should ideally be a choice that they make.

### How should we solve this?

Wording is a bit awkward, but we'd like to be able to set a policy in our dashboard like this for new devices:

![CleanShot 2022-03-11 at 09 43 03@2x](https://user-images.githubusercontent.com/811954/157751131-d9cf4796-b412-4604-9217-33ebf550be2a.png)

Not sure how this would interact with machine accounts though...

### What is the impact of not solving this?

We can point people to https://tailscale.com/kb/1072/incoming-connections/ and tell them they can disable incoming connections. That works ok, but may scare them a little bit, and is a manual step each employee has to do.

**Comment by bradfitz** [comment]
The answer is to use the ACLs.

The user-provided checkbox to block incoming connections is for users to add _additional_ restrictions beyond the restrictions defined in the Tailnet ACL defined at https://login.tailscale.com/admin/acls

**Comment by bradfitz** [comment]
I filed #4138 to make the GUIs make it more clear when the Tailnet ACLs preclude any incoming traffic anyway.

**Comment by bradfitz** [comment]
> We're happy to let users control this setting themselves if they want to share something with a coworker, but that should ideally be a choice that they make.

I guess that's the key point here. You want them to have that power on their own without contacting an admin.

@maisem, do tags help here? If the user's in a group that's a tag owner, they could tag their own node? But then their node becomes userless, I guess?

So maybe this is just another MDM-ish "defaults ..." option we could add.

/cc @nickoneill @DentonGentry

**Comment by bradfitz** [comment]
Also regarding the non-admin end user choosing: is all or nothing sufficient granularity? Or do they want per proto/port controls? (e.g. TCP/8080)

**Comment by DentonGentry** [comment]
`autogroup:self` seemed applicable right up to the point about letting users share something with a coworker if they choose.

**Comment by danielcompton** [comment]
Thinking about it more, for our initial rollout we could just deny incoming connections to user computers in our ACL. If employees have a need to connect to each other's machines we could then look at adding something to the ACL. My preference is for this kind of thing to be self-service but we don't actually have a concrete use-case for developer-developer connections at the moment.

Having #4138 would make things even better because employees could see that incoming connections weren't a possibility.

> Also regarding the non-admin end user choosing: is all or nothing sufficient granularity?

That seems reasonable to me.

**Comment by DentonGentry** [comment]
> Thinking about it more, for our initial rollout we could just deny incoming connections to user computers in our ACL. If employees have a need to connect to each other's machines we could then look at adding something to the ACL.

I'd recommend looking into `autogroup:self` to allow a user to connect amongst their own devices.

I think the rest will be handled on #4138
