### ISSUE TITLE
Using exit node drops all traffic

### ISSUE THREAD

**Issue by mholt** [tailscale/tailscale#4141]
### What is the issue?

I have enabled an exit node on my Ubuntu Linux machine following these instructions: https://tailscale.com/kb/1103/exit-nodes/ -- I run Tailscale in a way that advertises it is an exit node, and I enabled it from the Tailscale admin panel UI as well. It confirms that I have the machine configured as an exit node.

But when I go to use the exit node from another device, all traffic seems blocked. Nothing can connect thru:

```
% curl -v https://google.com/
*   Trying 172.217.7.110:443...
*   Trying 2607:f8b0:4025:800::200e:443...
* connect to 2607:f8b0:4025:800::200e port 443 failed: Network is unreachable
* connect to 172.217.7.110 port 443 failed: Operation timed out
* Failed to connect to google.com port 443: Operation timed out
* Closing connection 0
curl: (28) Failed to connect to google.com port 443: Operation timed out
```

(My ISP is not IPv6-enabled, unfortunately. So that error is expected.)

### Steps to reproduce

As described above:

- Configure an exit node following the documentation: https://tailscale.com/kb/1103/exit-nodes/ (I did this on Ubuntu Linux)
- Try to use the exit node from another device. I've tried both a macOS laptop and an Android phone, and both lose connectivity.

### Are there any recent changes that introduced the issue?

Not that I know of, I've never been able to get exit nodes to work.

I'm very new to Tailscale still, so I may have totally missed something obvious. Sorry if so, just let me know...

### OS

Linux

### OS version

Ubuntu 21.10 (Linux 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

### Tailscale version

1.22.0

### Bug report

BUG-767a80b6fb1f655728965f9e7e34161c2266c423fe5d74ebaa7a63c97db515c8-20220310225659Z-765c268bb6b5ef07

**Comment by JayWStapleton** [comment]
Based on that bug report it is adding and then deleting the route. 
Did you enable ip forwarding? 
https://tailscale.com/kb/1104/enable-ip-forwarding/

**Comment by mholt** [comment]
Ah, wait, is that different from running `sudo tailscale up --advertise-exit-node`? Because I didn't see any errors about IP forwarding. 🤔 

But sure enough, after running those commands, it is working now.

Thank you! I did not realize that was required even without errors.
