### ISSUE TITLE
Exit node is not added into route

### ISSUE THREAD

**Issue by linsui** [tailscale/tailscale#4145]
### What is the issue?

The ip of the exit node is not added into the route so that traffic to the exit node is routed through tailscale. So the network is not available at all.

### Steps to reproduce

I enabled exit node and the network was not accessable.

### OS

Linux

### OS version

NixOS 21.11

### Tailscale version

1.20.1

### Bug report

BUG-f9c416d8bebb7576bebae336359d5eae96feb29fad67c1274463ee563f8d5484-20220311145733Z-6e83695354b1f685

**Comment by bradfitz** [comment]
Sorry, there's not enough information here. An exit node involves two machines. Which two? What do you see?

If you think you know the problem, please elaborate.

**Comment by linsui** [comment]
I set one node as the exit node. It's ip is x.x.x.x. I run `sudo tailscale up --exit-node x.x.x.x` on another device and the nexwork is not accessible anymore. Then I found that all traffic to x.x.x.x is routed via tailscale. Finally I added a rule to route those traffic, i.e. all outbound triffic  via the gateway (`sudo ip route add x.x.x.x table 52 dev wlp0s20f3 via 192.168.255.254`). Then it works again.

**Comment by DentonGentry** [comment]
> It's ip is x.x.x.x. I run sudo tailscale up --exit-node x.x.x.x on another device and the nexwork is not accessible anymore.

x.x.x.x is the Tailscale IP address of another node on your tailnet?

Around the time of the bugreport we see:
```
2022-03-11 22:24:25.458339949 +0800 +0800: authReconfig: ra=false dns=true 0x01: adding [-i tailscale0 -j MARK --set-mark 0x40000] in v4/filter/ts-forward: running [/nix/store/z9pjb1vlr207bw8j00nhzqmplxyvnxhw-iptables-1.8.7/bin/iptables -t filter -A ts-forward -i tailscale0 -j MARK --set-mark 0x40000 --wait]: exit status 2: iptables v1.8.7 (nf_tables): unknown option "--set-mark"
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by linsui** [comment]
> x.x.x.x is the Tailscale IP address of another node on your tailnet?

Yes.  Sorry, I made a mistake. It's the 100.x.x.x ip address. The problem is that the traffic to the real ip of the exit node is also routed via tailscale.

**Comment by DentonGentry** [comment]
Nonetheless, this is a problem: `iptables v1.8.7 (nf_tables): unknown option "--set-mark"`
iptables is failing, which is leading to incorrect behavior.

set-mark is usually built in to iptables, not an optional package to be installed.

**Comment by linsui** [comment]
It seems that xt_mark is needed for that function. Adding it fix the iptables problem. Thanks for your help!
