### ISSUE TITLE
Make basic logs API and quota available to all users

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#415]
Several users have requested access to our logs API. We haven't made it publicly available to all yet because it tends to require some tech support to get rolling.

This is a placeholder for making it easy enough that end users can start to investigate their own node logs (eg. to find connectivity problems) without our help. Once that works more smoothly, we can open up basic logs access to everyone.

**Comment by DentonGentry** [comment]
The pan at this point is to make somewhat more processed logs available, for events where the coordination server makes a change to a tailnet for example.

**Comment by DentonGentry** [comment]
[Configuration Audit Logging](https://tailscale.com/kb/1203/audit-logging/) is [generally available as of Jan 31, 2023](https://tailscale.com/blog/config-audit-logging-ga/).

The current set of log information available is described in https://tailscale.com/kb/1011/log-mesh-traffic/

**Comment by DentonGentry** [comment]
https://tailscale.com/kb/log-events/ describes the set of logging facilities available, including:
- [Configuration audit logging](https://tailscale.com/kb/1203/audit-logging/)
- [Network flow logs](https://tailscale.com/kb/1219/network-flow-logs/)
- [Log streaming](https://tailscale.com/kb/1255/log-streaming/)
- [Webhooks](https://tailscale.com/kb/1213/webhooks/)
- [SSH session recording](https://tailscale.com/kb/1246/tailscale-ssh-session-recording/)

At this point I think the original feature request has been addressed by producing processed logs for particular views of information from the product. Closing as completed.
