### ISSUE TITLE
No ghcr packages published for release v1.22.1

### ISSUE THREAD

**Issue by jtcressy** [tailscale/tailscale#4150]
### What is the issue?

v1.22.1 was released a couple days ago but it appears we're unable to pull the docker image for it from ghcr.io.

### Steps to reproduce

```
❯ docker pull ghcr.io/tailscale/tailscale:v1.22.1
Error response from daemon: manifest unknown
```

### Are there any recent changes that introduced the issue?

Release v1.22.1

### OS

Linux

### Tailscale version

v1.22.1

**Comment by DentonGentry** [comment]
The builder had filled its disk. We cleaned it up and restarted the other builds, but maybe didn't restart the container build.

**Comment by jtcressy** [comment]
I gave a good look around but I hope this isn't a duplicate issue.

---

Also i'm expecting v1.22.1 to contain a fix for #4038 and I was going to evaluate the release on my relevant hardware, but I require a docker manifest.

**Comment by DentonGentry** [comment]
`2022/03/10 11:55:12 starting builds for [containers]`

I guess we did restart it. Need to look more into what happened there.

**Comment by maisem** [comment]
Sorry, we actually did forget to restart the container builds. Should be there now.

**Comment by jtcressy** [comment]
I see it now! Thank you!
