### ISSUE TITLE
Android app fails in locales with Indian-Arabic numerals

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#4156]
### What is the issue?

In the [Java code where we assemble the list of interfaces](https://github.com/tailscale/tailscale-android/blob/a8f017ddf6c85978fbe3f58e6579a76022c5d604/android/src/main/java/com/tailscale/ipn/App.java#L376) we have:
```
sb.append(String.format("%s %d %d %b %b %b %b %b |", nif.getName(),
               nif.getIndex(), nif.getMTU(), nif.isUp(), nif.supportsMulticast(),
               nif.isLoopback(), nif.isPointToPoint(), nif.supportsMulticast()));
```

In a locale using Indian-Arabic numerals: ۰	۱	۲	۳	۴	۵	۶	۷	۸	۹
the Java code will format the string as: `lo ١ ٦٥٥٣٦ true false true false false |`

In the [Go code which parses this string](https://github.com/tailscale/tailscale-android/blob/a8f017ddf6c85978fbe3f58e6579a76022c5d604/cmd/tailscale/main.go#L1320), we have:
```
_, err := fmt.Sscanf(fields[0], "%s %d %d %t %t %t %t %t",
	&name, &index, &mtu, &up, &broadcast, &loopback, &pointToPoint, &multicast)
```
which does not handle these numerals: `unable to parse "lo ١ ٦٥٥٣٦ true false true false false |": expected integer`

--------

As these strings are purely internal to pass information between the Java runtime and Go environment, they will never be visible to the user. I think the best fix is to set a specific locale in the Java code to format the string.

### OS

Android

### OS version

Android 10

### Tailscale version

1.22

**Comment by bradfitz** [comment]
Awesome bug!

**Comment by DentonGentry** [comment]
_"Passing data from Java to Go is hard. I know, I'll use strings! What can possibly go wrong with strings?"_
^ me, last year.
