### ISSUE TITLE
Magic DNS: automatic DNS name registration and interception

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#416]
The planned magic DNS feature is discussed briefly here: 
https://tailscale.com/kb/1054/dns

And we've started work on it, eg here:
https://github.com/tailscale/tailscale/pull/396

This bug is a placeholder for the finished magic DNS feature.

**Comment by rosszurowski** [comment]
Since we've launched this feature, I assume this bug can be closed.
