### ISSUE TITLE
Connected but impossible to access

### ISSUE THREAD

**Issue by WilliamPrvz** [tailscale/tailscale#4163]
### What is the issue?

I tried to ssh to my Synology ds218+ from my mac but it timed out.

### Steps to reproduce

tailscale ping "nas_name" 
pong from "nas_name" "nas_ip" via DERP(fra) in 94ms

ping "nas_ip"
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

### Are there any recent changes that introduced the issue?

changed from windows pc to mac

### OS

macOS

### OS version

Monterey 12.2.1 

### Tailscale version

1.22.1

### Bug report

BUG-f469c536bdc2c9f80e0233b17854dbce95b5f6f443bee392e434911070f923fd-20220313220749Z-b1bf67210b9c390f

**Comment by bradfitz** [comment]
What's your NAS?

**Comment by WilliamPrvz** [comment]
DS 218+ pinging work from windows pc

**Comment by stevetrease** [comment]
Both my DSM 7 Synologies stopped working recently.
Eventually fixed it by /var/packages/Tailscale/target/bin/tailscale configure-host using Tailscale 1.22 as documented at [https://github.com/tailscale/tailscale/wiki/Tailscale-1.22].

To be honest the documentation could be more clear about the purpose of this option, why it is needed and when to use it.

**Comment by WilliamPrvz** [comment]
The problem actually came from the Synology nas, not the MacBook. Rebooting tailscale on the nas actually solved this issue.
