### ISSUE TITLE
"Tailscale backend error: TUN: Error creating interface: The system cannot find the file specified"

### ISSUE THREAD

**Issue by komocode** [tailscale/tailscale#4164]
### What is the issue?

Updated to latest version of Tailscale. Tailscale says to "Please restart the Tailscale Window Service". About 1 minute later, this error message pops up
![Screen Shot 2022-03-13 at 4 02 49 PM](https://user-images.githubusercontent.com/226526/158083041-a22d036a-2fd0-4b41-84a8-a20ca8120666.png)

### Steps to reproduce

Update Tailscale from an old version (possibly 1.16 IIRC)
Launch Tailscale
Wait 1 minute.
Error message appears.

### OS

Windows

### OS version

10.0.19044 Build 19044

### Tailscale version

1.22.1

### Bug report

Post "http://local-tailscaled.sock/localapi/v0/bugreport?note=": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "Error"

**Comment by DentonGentry** [comment]
`wintun` is a library used to provide the type of TUN network interface which the Tailscale client needs. It looks like the older version got wedged and won't unload. If you haven't already, rebooting the Windows system is likely to resolve it.

If rebooting alone doesn't work, uninstalling and reinstalling would be the next thing I'd recommend.

To completely remove Tailscale and reinstall you'd do the following. The device will lose its Tailscale IP address, and be issued a different IP address after reinstall:
1. Uninstall tailscale
1. Remove the machine from your admin panel https://login.tailscale.com/admin/machines 
1. Delete c:\Program Files (x86)\Tailscale IPN
1. Remove c:\Users\XXX\AppData\Local\Tailscale (where XXX is each user of the machine)
1. Remove c:\ProgramData\Tailscale
1. Run Device Manager, expand Network Adapters, delete Tailscale Tunnel
1. Reinstall the latest version from https://tailscale.com/download
1. Log in

**Comment by komocode** [comment]
Thanks. The machine is currently running a long processing job. Will try after that is finished in a few days.

**Comment by komocode** [comment]
I rebooted and tailscale is working. Closing

**Comment by nmambre** [comment]
> `wintun` is a library used to provide the type of TUN network interface which the Tailscale client needs. It looks like the older version got wedged and won't unload. If you haven't already, rebooting the Windows system is likely to resolve it.
> 
> If rebooting alone doesn't work, uninstalling and reinstalling would be the next thing I'd recommend.
> 
> To completely remove Tailscale and reinstall you'd do the following. The device will lose its Tailscale IP address, and be issued a different IP address after reinstall:
> 
>     1. Uninstall tailscale
> 
>     2. Remove the machine from your admin panel https://login.tailscale.com/admin/machines
> 
>     3. Delete c:\Program Files (x86)\Tailscale IPN
> 
>     4. Remove c:\Users\XXX\AppData\Local\Tailscale (where XXX is each user of the machine)
> 
>     5. Remove c:\ProgramData\Tailscale
> 
>     6. Run Device Manager, expand Network Adapters, delete Tailscale Tunnel
> 
>     7. Reinstall the latest version from https://tailscale.com/download
> 
>     8. Log in


I followed the above steps, but still getting the error. I'm using tailscale-ipn-setup-1.22.2.exe

Windows 10 Pro 
Version 21H2 
OS build	19044.1620
![tailscale error](https://user-images.githubusercontent.com/15265357/163448576-5ccfcb54-c1c4-4de7-a30f-bf8075e3761f.jpg)
