### ISSUE TITLE
Running  /Applications/Tailscale.app/Contents/MacOS/Tailscale --help resulted in losing connection

### ISSUE THREAD

**Issue by torarnv** [tailscale/tailscale#4167]
### What is the issue?

I was running `/Applications/Tailscale.app/Contents/MacOS/Tailscale --help` one one of the nodes in the network. A few seconds after I lost the SSH connection, and the node is no longer online in the network. 

The node was on 1.20.4

### OS

macOS

### OS version

12.x

### Tailscale version

1.20.4

**Comment by torarnv** [comment]
After gaining access to the node again outside of Tailscale I had to press "Log in..." again. Now the node is back.

But running `/Applications/Tailscale.app/Contents/MacOS/Tailscale --help` again causes the same exact issue.

Also tested with 1.22.1

**Comment by torarnv** [comment]
Same issue with `/Applications/Tailscale.app/Contents/MacOS/Tailscale version`:

```
❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale version
1.22.1
  tailscale commit: 0bc2caf8ce8fd4c471a3226ec1877ae0564429b1
  other commit: 988e8ad4342582d6d729bb2242cc062776b6b9fe-dirty
  go version: go1.17.8-tsdce70b6d32

❯ Shared connection to mymachine closed.
```

**Comment by DentonGentry** [comment]
I've tried to reproduce this but haven't been able to, the service doesn't die when I run `/Applications/Tailscale.app/Contents/MacOS/Tailscale --help` or version.

**Comment by mdeeks** [comment]
@DentonGentry I saw this a couple of weeks ago on my machine. I filed a bugreport right after. 
`BUG-16caa413956b85d5e0dd5aad1eda14772074eb15343bebe720d2e781945c183b-20220321171725Z-9abd300efc4d3639`

It gave me an exclamation mark and only showed an option to "Log in". Clicking Log in did nothing. Only moments prior I had run `/Applications/Tailscale.app/Contents/MacOS/Tailscale -h`. When I looked up I saw the error. I tried running bugreport and it said it couldn't connect to the Tailscale daemon. I restarted the app and was able to file a bug report
```
❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport
2022/03/21 10:16:42 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial tcp [::1]:61711: connect: connection refused
```

Log of my CLI
```
❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale -h
USAGE
  tailscale [flags] <subcommand> [command flags]

For help on subcommands, add --help after: "tailscale status --help".

This CLI is still under active development. Commands and flags will
change in the future.

SUBCOMMANDS
  up         Connect to Tailscale, logging in if needed
  down       Disconnect from Tailscale
  logout     Disconnect from Tailscale and expire current node key
  netcheck   Print an analysis of local network conditions
  ip         Show Tailscale IP addresses
  status     Show state of tailscaled and its connections
  ping       Ping a host at the Tailscale layer, see how it routed
  version    Print Tailscale version
  web        Run a web server for controlling Tailscale
  file       Send or receive files
  bugreport  Print a shareable identifier to help diagnose issues
  cert       get TLS certs

FLAGS
  --socket string
    	path to tailscaled's unix socket (default /var/run/tailscaled.socket)

❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport
2022/03/21 10:16:42 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial tcp [::1]:61711: connect: connection refused

❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport
BUG-16caa413956b85d5e0dd5aad1eda14772074eb15343bebe720d2e781945c183b-20220321171725Z-9abd300efc4d3639

```

**Comment by bradfitz** [comment]
@nickoneill moved the CLI check much earlier in the lifetime of the macOS Tailscale binary, before `NSApplicationMain`.

(we previously called it from `applicationDidFinishLaunching`)

Seems like that fixes this. Fingers crossed.

It'll be in the upcoming 1.24.0 build.

**Comment by torarnv** [comment]
Thanks @bradfitz!

I can not reproduce this at the moment, with the same Trailscale version as before, so I don't know exactly what's going on, but let's see! 👍🏻

**Comment by bradfitz** [comment]
> I can not reproduce this anymore, with the same Trailscale version as before (1.22.1), so I don't know exactly what's going on, but let's see! 👍🏻

We think it was a race between different GUI threads that had already been started (because we started the CLI too late, before the GUI started doing its various things). If you ran a CLI command that happened to be really fast you often got lucky and it worked. But if you ran a long-running CLI command, boom.

**Comment by torarnv** [comment]
Ah, I see, makes sense. Thanks for fixing! 🏅
