### ISSUE TITLE
MSI/exe installer missmatch when update notice appear

### ISSUE THREAD

**Issue by ajnadox** [tailscale/tailscale#4175]
### What is the issue?

The issue is when user rightclicks the tailscale client taskbar and see "Update Tailscale (update available)" , clicks the text and download is fetching the .exe instead of the .msi package.
The user starts the installation from .exe and get the error "This installer cannot be used to update an existing MSI-based Tailscaled installation. Please use the Tailscale MSI package"
Well since it´s not easy to find the users just ignore to update and continue to run an old version.
The best way would be that client checks if .msi or .exe is used for installation and download link is corrected against the .msi/.exe

### Steps to reproduce

Install 1.22 .MSI package https://pkgs.tailscale.com/stable/tailscale-setup-1.22-amd64.msi then try to use the Update function frpm tailscale client.

### OS

Windows

### OS version

windows 11, windows 10, server 2022

### Tailscale version

1.22

### Bug report

BUG-9c8937e11879b38a69231a49a9975119b87a3d9d604c4bb2e249f18b5e3b095f-20220315071803Z-93f84de7fe296f87

**Comment by dblohm7** [comment]
Works in 1.24.
