### ISSUE TITLE
issue about ios VPN conflict

### ISSUE THREAD

**Issue by fangod123** [tailscale/tailscale#4176]
### What is the issue?

In some region where can't get in google directly because of GFW, so we need another vpn app to make me log in gmail.
so i choose another vpn to log in my google mail, and the web tell me success and can close this web(window), but in ios setting about VPN the tailscale is being unchoose and choose another vpn app, so when i close the web, the app is stuck in origin view,if i switch VPN to tailscale in setting, the tailscale tell me to log in my mail again.

there is no problem when i open another VPN app like V2rayNG when i log in gmail in tailscale in my android device.

and i also try to use vpn in router not in ios phone and it works well, but my friends do not have router with this function.

all in all, i want to know how to slove this problem log in gmail in tailscale with another VPN app is openning in ios phone.

Thanks!

### OS

iOS

### Tailscale version

1.20

**Comment by DentonGentry** [comment]
iOS only allows one VPN to be active at a time. Tailscale cannot change that.

**Comment by DentonGentry** [comment]
I don't expect to be able to address having Tailscale send its traffic via a different VPN. iOS only allows one VPN to be active at a time.

Users in China frequently use an SSO source other than Google, like Microsoft or Okta, for precisely this reason.
