### ISSUE TITLE
STUN server address

### ISSUE THREAD

**Issue by monken** [tailscale/tailscale#4177]
### What is the issue?

I'm unable to identify the STUN servers that tailscale is using. I tried to use `derp1.tailscale.com` with stuntman, but it is unable to open a connection and I'm not getting any responses on port 3478 (UDP). Could you please share the domain name of the tailscale STUN servers?

### Steps to reproduce

`stunclient --mode filtering derp1.tailscale.com`

**Comment by DentonGentry** [comment]
The DERP servers are the STUN servers, on port 3478. I don't understand why stunclient is not getting a response.

The list of DERP servers can be seen at https://login.tailscale.com/derpmap/default

**Comment by monken** [comment]
Yea that's what I thought. I'll keep debugging this but it would be great if you could confirm the problem with a STUN client other than the tailscale client.

**Comment by bradfitz** [comment]
What's the real problem that led to this line of debugging?

**Comment by monken** [comment]
OK, just found that you require the SOFTWARE and FINGERPRINT attribute in the binding request (https://github.com/tailscale/tailscale/blob/670838c45f232f2355c9f2ea587cbcef348410f4/net/stun/stun.go#L100). I was trying to implement a NAT probing script in NodeJS and wanted to use tailscale's STUN servers because they are globally distributed and reliable.
