### ISSUE TITLE
Android: Android TV needs a 320x180px banner for TV home screen

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4179]
https://github.com/tailscale/tailscale-android/pull/38#issuecomment-1068231101 says:

> albeit with the wrong icon, since android:banner is still missing
>
> The specs are here: https://developer.android.com/training/tv/start/start#banner
>
> The banner should be an xhdpi resource with a size of 320 x 180 px.

/cc @tmm1 @tailscale/frontend

**Comment by tmm1** [comment]
Note also:

> Text must be included in the image

If the app "banner" doesn't say Tailscale, it may be rejected during the special Android TV review process on the Play store

**Comment by bradfitz** [comment]
Hey @rosszurowski, I made this in Figma... 🤷‍♂️ 

![tv-banner](https://user-images.githubusercontent.com/2621/158507846-b5225a8e-2090-4428-80e0-641fe365997e.png)

**Comment by tmm1** [comment]
You will need a higher res version of the same image for the play store.

>Displayed on Android TV devices. The image should be PNG or JPEG, up to 8MB, and 1,280 px by 720 px

**Comment by rosszurowski** [comment]
So we need:

- A 320x180 PNG of the app icon
- A 1280x720 PNG of the app icon

Are these both going in the location shown in @tmm1's screenshot?

**Comment by rosszurowski** [comment]
So we need:

- A 320x180 PNG of the app icon
- A 1280x720 PNG of the app icon

Are these both going in the location shown in @tmm1's screenshot? If so, these graphics should work.

![Banner-1280](https://user-images.githubusercontent.com/303731/158632229-54aac3b8-d675-42bd-b124-409ded4ba9fc.png)
![Banner-320](https://user-images.githubusercontent.com/303731/158632233-d8d26c85-4cad-4961-9cee-524abc812305.png)

**Comment by DentonGentry** [comment]
I think this is done and checked in with the Android TV support.
