### ISSUE TITLE
net/tshttpproxy: winhttp: Open: The parameter is incorrect.

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#4201]
### What is the issue?

We're passing `WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY` as the `dwAccessType` argument to [`WinHttpOpen`](https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpopen). Unfortunately that value is not yet supported pre-Windows 8.1, where we should be using the deprecated `WINHTTP_ACCESS_TYPE_DEFAULT_PROXY` flag instead.

### OS

Windows

**Comment by bradfitz** [comment]
Another cherry-pick candidate?

/cc @DentonGentry
