### ISSUE TITLE
State machine stuck at "Starting"

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#421]
Now that DERP starts later, the state machine that transitions from Starting to Running on the first DERP connection no longer runs.

I assumed that's because I moved DERP connection later with server-controlled DERP maps, but it turns out LiveDERPs is never assigned anymore.

Looks like it was removed in c97c45f2681c73d826ea5dee6e4fef88f080f0fd. @danderson, I assume that wasn't intentional?

**Comment by bradfitz** [comment]
Notably, this line is now gone:

```
  LiveDERPs: s.DERPs,
```

That was the only assignment to LiveDERPs.

Currently at HEAD that field is only ever declared & read, never written:

```
dev:tailscale.com $ git grep LiveDERPs
ipn/backend.go: LiveDERPs      int // number of active DERP connections
ipn/local.go:           if st := b.getEngineStatus(); st.NumLive > 0 || st.LiveDERPs > 0 {
```

**Comment by danderson** [comment]
Yes, mistake. At a glance, I think this was a 3-way merge screwup when I synced before submitting. Sorry :(

**Comment by bradfitz** [comment]
Seems happy on iPhone and iOS now. Closing.
