### ISSUE TITLE
Zerotier interfaces not ignored on macOS

### ISSUE THREAD

**Issue by tzhao11** [tailscale/tailscale#4210]
### What is the issue?

https://github.com/tailscale/tailscale/issues/1208 says tailscale would ignore interfaces beginning with `zt`. But on macOS zerotier interfaces begin with `feth` because of [a feth pair hack](https://www.zerotier.com/2019/08/21/how-zerotier-eliminated-kernel-extensions-on-macos/) used by zerotier to support layer 2 traffic. These interfaces look like these on my machine:
```
feth5340: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 2800
	ether 66:65:74:68:14:dc 
	peer: feth340
	media: autoselect
	status: active
feth340: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
	ether 82:64:e3:df:bd:dc 
	inet 10.242.202.231 netmask 0xffff0000 broadcast 10.242.255.255
	inet6 fe80::8064:e3ff:fedf:bddc%feth340 prefixlen 64 scopeid 0x15 
	inet6 fcfb:661b:d0c8:4928:ef6b::1 prefixlen 40 
	inet6 fd0c:ccb7:52f7:aaac:8299:93c8:4928:ef6b prefixlen 88 
	peer: feth5340
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

Sometimes tailscale picks them as the best route, resulting in traffic being routed through zerotier.

### Steps to reproduce

Run tailscale and zerotier 1.8.6 on the same macOS machine.

### Are there any recent changes that introduced the issue?

N/A

### OS

macOS

### OS version

macOS 12.2

### Tailscale version

1.22.1

### Bug report

BUG-b7d2154b49dccab44182c8903eea48e7759f47a983881689d1bbafd4d40b6f38-20220318045113Z-42b3cde1361d402e

**Comment by bradfitz** [comment]
More ignoring is easy enough, but does it cause any problems, though?

Are you seeing infinite routing loops or anything?

Ideally we don't want to special case any interfaces. We just use all of them and see what works.

**Comment by tzhao11** [comment]
> Are you seeing infinite routing loops or anything?

Not currently, other than tailscale traffic being routed through zerotier. But as mentioned in https://github.com/tailscale/tailscale/issues/1208, if zerotier also select tailscale interface as the best route, theoretically  there is chance of infinite routing loops. I'll report here if that happens. Feel free to close this issue for now.

**Comment by DentonGentry** [comment]
Closing until there is a specific harm.
