### ISSUE TITLE
tailscale ping works but not system ping, sys firewall has been disabled already 

### ISSUE THREAD

**Issue by fredshentu** [tailscale/tailscale#4211]
### What is the issue?

I can login to the tailscale and I can see other devices. My friend can access other machines with no issue so the problem should be on my side. 
```
(base) fred@Freds-MacBook-Pro-2 ~ % tailscale ping 100.88.70.76
pong from cirra-gpu-01 (100.88.70.76) via DERP(use1b) in 1.007s
pong from cirra-gpu-01 (100.88.70.76) via DERP(use1b) in 266ms
pong from cirra-gpu-01 (100.88.70.76) via DERP(use1b) in 286ms
pong from cirra-gpu-01 (100.88.70.76) via DERP(use1b) in 266ms
pong from cirra-gpu-01 (100.88.70.76) via DERP(use1b) in 268ms

(base)fred@Freds-MacBook-Pro-2 ~ % ping 100.88.70.76
PING 100.88.70.76 (100.88.70.76): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
````

But my friend can ping/ssh 100.88.70.76 with no issue.
From my friend's `tailscale status` it seems my machine's status is idle, but I don't know what should I do to avoid this situation.
Any help will be great!
 

### Steps to reproduce

I just got tailscale installed and it never works. 

### Are there any recent changes that introduced the issue?

no, it never works on my machine 

### OS

macOS

### OS version

12.2.1 (21D62)  M1max

### Tailscale version

12.2.1 (21D62)  M1max
Should I try older version? However, app store does now allow users downloading history versions. 

### Bug report

BUG-1f1eea7398f745839f04395ab648a006a6a970343ed3d3f83ad28a28c0953106-20220318085815Z-0e1dc8c5f9400991

**Comment by stevenwudi** [comment]
I think it's an very eminent problem worth investigating instead of `L1` @DentonGentry maybe you could help to assist for the productivity?

**Comment by DentonGentry** [comment]
A common reason for this is the presence of other active VPN software. Though the firewall may not be configured at the OS level, VPNs frequently block traffic on other interfaces in order to ensure all traffic goes via their VPN.

**Comment by DentonGentry** [comment]
At this point I don't expect to figure out the original issue. If it is still happening, please send another bugreport. On macOS this is done by holding Option while clicking on the Tailscale icon in the menubar, then selecting Debug > Bug report.

**Comment by monkey-jsun** [comment]
I may have the same issue.  My tailscale server runs on AWS EC2.  It will run well for quite a while.  Then it seems it will go to idle by itself (presumably when no one is using it for a while), and other machines can no longer use it as exist nodes. 

What makes its state to go from active to idle?  Can we prevent that?
