### ISSUE TITLE
routing is broken when enabling exit node on Android client

### ISSUE THREAD

**Issue by OwnageIsMagic** [tailscale/tailscale#4228]
### What is the issue?

```
~ $ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4095ms

~ $ ping 100.96.193.125
PING 100.96.193.125 (100.96.193.125) 56(84) bytes of data.

^C--- 100.96.193.125 ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 10214ms
```

On other clients (not android) or without exit node it works ok. Exit node is linux userspace-net.

### OS

Android

### OS version

11 (MIUI 12.5.5)

### Tailscale version

1.22

### Bug report

BUG-2d67a4a24bdaf02f05e48b81c363736f1aa5015e78ac49a74fa6cd057281ddea-20220319193455Z-3539095670f12d02

**Comment by OwnageIsMagic** [comment]
After restarting exit node it works ok on all clients

**Comment by DentonGentry** [comment]
Seems to be resolved.

**Comment by OwnageIsMagic** [comment]
@DentonGentry it reappears time to time, but restart helps every time
