### ISSUE TITLE
./build_dist.sh & friends (tools/go) do not work out of the box on NixOS

### ISSUE THREAD

**Issue by twitchyliquid64** [tailscale/tailscale#4231]
### What is the issue?

The installed `tailscale-go` does not have its dynamic-linker paths adjusted for a destination NixOS system.

A mildly-terrifying (but would work until you update glibc) fix is:

```diff
diff --git a/tool/go b/tool/go
index 8f7485f9..96c68d7a 100755
--- a/tool/go
+++ b/tool/go
@@ -74,6 +74,15 @@ get_cached() {
     mkdir -p "$TOOLCHAIN"
     (cd "$TOOLCHAIN" && tar --strip-components=1 -xf "$archive")
     echo "$REV" >$mark
+
+    # NixOS installations do not have glibc in the default location on the filesystem,
+    # however tailscale-go expects it. As such we patch the dynamic linker paths to
+    # Make this work.
+    if [[ $(uname -v) == *"NixOS"* ]]; then
+      PATCHELF=$(nix eval --raw nixpkgs.patchelf)/bin/patchelf
+      $PATHELF --set-rpath $(nix eval --raw nixpkgs.glibc)/lib $TOOLCHAIN_GO
+      $PATHELF --set-interpreter $(nix eval --raw nixpkgs.glibc)/lib/ld-linux-x86-64.so.2 $TOOLCHAIN_GO
+    fi
 }

 if [ "${REV}" = "SKIP" ] ||
```

### Steps to reproduce

1. Be on NixOS or a derivative
2. `git clone https://github.com/tailscale/tailscale && cd tailscale`
3. `nix-shell`
4. `./build_dist.sh tailscale.com/cmd/tailscale`

You'll get the error:

```
bash: /home/xxx/.cache/tailscale-go/bin/go: No such file or directory
```

### OS

Linux, Other

### OS version

Linux xxx 5.10.106 #1-NixOS SMP Wed Mar 16 13:16:03 UTC 2022 x86_64 GNU/Linux

### Tailscale version

main

**Comment by bradfitz** [comment]
I'm not sure it's a goal for us to support NixOS in that script. We (well, @danderson) maintain Tailscale's NixOS packaging already and empirically we haven't needed `./tool/go`'s help to do so.

**Comment by maisem** [comment]
I was grumbling about this earlier today, I would love to have it work on my NixOS machine too! 

I don't fully understand this patch though. Maybe we should have a tailscale-go derivation in `shell.nix`.

One workaround that I typically end up using is setting `go.toolchain.rev` to `SKIP`. That circumvents tailscale-go though.

**Comment by twitchyliquid64** [comment]
Yeppers, at a guess doing this properly either looks like:

1. Using the `nixpkgs` variant, in particular using `nix-shell` targeting that derivation
2. Updating `shell.nix` in this repo to setup `tailscale-go` and add it to the environment
