### ISSUE TITLE
Android: add Dockerfile

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#424]
Installing the Android SDK & NDK is pretty invasive & tedious.

Let's include a Dockerfile in the tailscale-android root that includes everything necessary.

Then the Makefile can include a target to optionally build in Docker. (And use `docker run -v` to output the final apk on the caller's filesystem)

The Dockerfile should be like:

```
FROM golang:1.14-buster
...
... whole bunch of Java & Android SDK & NDK deps
...
RUN mkdir /usr/local/src/tailscale-android
WORKDIR /usr/local/src/tailscale-android

ADD go.mod .
ADD go.sum .
RUN go mod download
ADD . .
RUN ./build.sh
```

(We can get fancier later)

I tried to make one and quickly got lost & realized I don't know Android tooling anymore.

**Comment by bradfitz** [comment]
Actually, I remembered we build Perkeep's Android app in Docker, so I'm trying to start from that now.

**Comment by bradfitz** [comment]
Okay, I pushed a basic one. It needs some love to be more incremental, though. Currently too much happens in the build.sh step that should happen once and be cached in an earlier layer (like downloading Gradle and some SDK Build-Tools versions).

**Comment by eliasnaur** [comment]
I removed redundant SDK packages, addressed Dockerfile TODOs and added a `dockershell` Makefile target. Let me know if there's more.
