### ISSUE TITLE
Android client reduced speed with exit node

### ISSUE THREAD

**Issue by akashkj** [tailscale/tailscale#4244]
### What is the issue?

Using a tailscale exit node(ubuntu) for two devices but getting a lot of difference in internet speed.

1. MacOS - speed with or without exit node is similar
2. Android - speed is drastically decreased with exit node enabled. Reduction by 80% 

### Steps to reproduce

Install apps on mentioned OS and use exit node

### OS

Linux, macOS, Android

### OS version

Monterey, Android 10, Ubuntu 20

**Comment by diegomontoya** [comment]
@DentonGentry The fact that Android/IOS client has no way to showing any readable debug info on wether using RELAY (if so, which node) or DIRECT is resulting in users, us included, having to guess why the connection speed is slow.

**Comment by ashishjullia** [comment]
Any solution to this?

**Comment by DentonGentry** [comment]
One possibility if the exit node is using userspace-networking:
- macOS or Windows
- Linux with no TUN device, with `tailscaled --tun=userspace-networking`
- Another Android device serving as the exit node

In Tailscale releases prior to 1.32.1, `userspace-networking` did not handle TCP selective acknowledgement and suffered large performance loss from moderate packet loss. If your exit node is impacted, it may be that a macOS client is just better able to cope even in cases where SACK is not available.

**Comment by ashishjullia** [comment]
I'm using android to android, not sure but the speed is not that good.

**Comment by DentonGentry** [comment]
> I'm using android to android

You need to use the Tailscale Android app version 1.32.2, because of the selective app issue mentioned.

**Comment by ashishjullia** [comment]
I have the same version on both of my devices.

**Comment by DentonGentry** [comment]
@ashishjullia if you want us to look at it then open a bug and provide details of the devices so we can look at telemetry.

**Comment by ashishjullia** [comment]
Sure, I'll do that and make a pointer here as well.

Thanks.

**Comment by ashishjullia** [comment]
[here](https://github.com/tailscale/tailscale/issues/6263) @DentonGentry

**Comment by pmnlla** [comment]
Happens to me on linux and android as well, but 150mbps with windows... weird

**Comment by bradfitz** [comment]
I'm assuming the majority of this was fixed by a471681e285ba22ab1975e4c2ab92768156e4162

Since there haven't been any concrete details provided since that, I'm going to close this for now. The overall bandwidth tracking bug is #414.

If there are specific combinations that are abnormally slow then new issues (with `tailscale bugreport` telemetry markers) can be files.
