### ISSUE TITLE
Subnet routes not visible on Ubuntu 20.04

### ISSUE THREAD

**Issue by dcelasun** [tailscale/tailscale#4246]
### What is the issue?

Our Tailscale network has three subnets enabled: `10.30.0.0/16`, `10.40.0.0/16` and `10.50.0.0/16`. On one of our Ubuntu desktop machines, these routes are not reachable:
```sh
$ ip route show table 52
100.70.202.22 dev tailscale0 
100.73.147.25 dev tailscale0 
100.75.55.116 dev tailscale0 
100.77.246.38 dev tailscale0 
100.80.245.71 dev tailscale0 
100.82.219.86 dev tailscale0 
100.86.60.118 dev tailscale0 
100.100.100.100 dev tailscale0 
100.102.207.121 dev tailscale0 
100.108.85.123 dev tailscale0 
100.123.219.58 dev tailscale0 
100.126.66.119 dev tailscale0 
```
The problem seems to be limited to that machine.  `tailscale status` shows the machines that advertise these routes, but they are not on the route table for some reason.

### Steps to reproduce

N/A

### Are there any recent changes that introduced the issue?

No recent changes.

### OS

Linux

### OS version

Ubuntu 20.04.1 LTS

### Tailscale version

1.22.2

### Bug report

BUG-52d316cc2b76e3c2d998a8a20f5b64062ba39d2f8ef383cbea555b8c76d15c46-20220321143836Z-11095e93998cd7ab

**Comment by maisem** [comment]
Did you do `tailscale up --accept-routes` on the Ubuntu desktop machine?

**Comment by dcelasun** [comment]
Ah, that's what we forgot! Thanks for the quick reply :)
