### ISSUE TITLE
Private DNS on Android with Tailscale Breaks Internet

### ISSUE THREAD

**Issue by gregg098** [tailscale/tailscale#4252]
### What is the issue?

I have been testing out NextDNS for DNS services at home and on mobile devices.  For my Tailscale setup, I also have MagicDNS hand out NextDNS DNS servers with force override set to ON. Now devices are connected to those DNS servers just by connecting to Tailscale. 

I also tried adding the NextDNS server to my phone's Private DNS options. This works great until I connect to Tailscale. Then, all network connectivity stops and I get a pop up saying "Network has no internet access. Private DNS server cannot be accessed." I CAN connect by IP to other devices if on the same network, but DNS stops working, period.

If I disconnect from Tailscale OR change Private DNS to automatic, everything works again.

I tried connecting to a number of other VPN services (Home OpenVPN, Home Wireguard, Private Internet Access), all with full internet redirection turned on, and nothing broke on any of those.

I suspect Private DNS and Tailascale Magic DNS force override are fighting each other, so I'm not sure there is a fix. This does seem to be an issue that pops up on other forums for some VPN services, so definitely not entirely Tailscale, but I know you guys  are clever at work arounds.

### Steps to reproduce

On my Samsung Galaxy S21+, I went to the Private DNS settings and set "Private DNS provider hostname" to the address given by NextDNS for my account (xxxxxxx.dns.nextdns.io). Hit save.

Check internet - Works
Goto NextDNS website - Detects proper DNS settings being used.
Enable Tailscale - All DNS stops, get error messages mentioned above. Direct IP connections only.
Turn off Private DNS OR disconnect from Tailscale - everything works as expected.

### Are there any recent changes that introduced the issue?

Did not used to have an Android Private DNS server setup. Used to be Automatic.

### OS

Android

### OS version

12

### Tailscale version

1.23.53-t012098ec3-gb0f1428443

### Bug report

BUG-8dd4ea6cea51806722166c345916f663b8e6bf9e64a82e4501f6d214ab034ce2-20220321232924Z-98551623d602e07c

**Comment by gregg098** [comment]
Looks like this is already reported. Missed it on my first search.

https://github.com/tailscale/tailscale/issues/915

Can close.

**Comment by bluegizmo83** [comment]
I'm having this same issue as well. I have Private DNS enabled at all times on my Galaxy S23 Ultra, and as soon as I connect to Tailscale in the app I immediately lose internet connection. If I go into the phone settings and disable Private DNS before connecting to Tailscale, or while Tailscale is already connected, the internet starts working again, but will immediately stop working if I re-enable Private DNS while Tailscale is connected.

**Comment by monitor22** [comment]
Is there any fix for this? Mobile data does not connect to interent while using NextDNS + Tailscale VPN.

**Comment by TinyWorkshopDesign** [comment]
I have the same issue, no collection of I turn on private DNS while using tailacale.

**Comment by monitor22** [comment]
> I have the same issue, no connection of I turn on private DNS while using tailacale.

Turn off MagicDns in your Tailscale dashboard, it worked for me if i use the ips and not the domain names

**Comment by TinyWorkshopDesign** [comment]
> > I have the same issue, no connection of I turn on private DNS while using tailacale.
> 
> Turn off MagicDns in your Tailscale dashboard, it worked for me if i use the ips and not the domain names

Whoked :) 

many many thanks

**Comment by DallasBelt** [comment]
> Turn off MagicDns in your Tailscale dashboard, it worked for me if i use the ips and not the domain names
This gives me internet access, but the private DNS can't connect.

**Comment by EldrinSMP** [comment]
Same bug 2 years later that completely breaks the functionality of Tailscale. I am getting the error with NextDNS and I have it set to use NextDNS in the Tailscale settings. This really is inexcusable.

**Comment by DallasBelt** [comment]
> Same bug 2 years later that completely breaks the functionality of Tailscale. I am getting the error with NextDNS and I have it set to use NextDNS in the Tailscale settings. Disabling MagicDNS DOES NOT WORK and does not fix the problem. This really is inexcusable.

I found that now Tailscale has an option to disable the use of Tailscale DNS. That seemed to resolve the issue for me.

**Comment by smlx** [comment]
Here's a workaround that lets you keep magic DNS enabled. It's not scalable, but it works for small tailnets:

1. Set up an exit node in your tailnet.
2. Configure your android device to route through the exit node. This will allow you to reach the private DNS server.
4. Add the magic DNS entries you need to your private DNS server. Tailnet IPs are static, so these won't change.

**Comment by JasonKeirstead** [comment]
Just commenting here, this is not a Tailscale issue, it's an Android issue, and happens with all Private DNS if you use Android Auto Wireless. I will be trying to report this to Google and will link back here when I do

**Comment by TinyWorkshopDesign** [comment]
> Just commenting here, this is not a Tailscale issue, it's an Android issue, and happens with all Private DNS if you use Android Auto Wireless. I will be trying to report this to Google and will link back here when I do

I know,I've moved back to iOS since  lol
