### ISSUE TITLE
Large (10x) throughput penalty at high data rates (10G+)

### ISSUE THREAD

**Issue by djmarcin** [tailscale/tailscale#4253]
### What is the issue?

Our machines are connected with 10-25Gbps links, but we can only sustain 500-1000Mbps transfers over Tailscale. This seems similar to #414, but our servers are Intel Xeon machines, not ARM.

We need to be able to use much more of the high link speed on these machines for them to be viable for us. I can probably figure out how to connect them directly, but Tailscale has spoiled me -- I really don't want to figure out how to do the networking without it! 😂 

### Steps to reproduce

Create two high networking speed AWS instances in the same availability zone with tailscale and iperf installed.

Test across a direct connection:
```
# Server side
$ iperf -s

# Client side
$ iperf -c 10.40.5.25 -P 3
------------------------------------------------------------
Client connecting to 10.40.5.25, TCP port 5001
TCP window size: 1.08 MByte (default)
------------------------------------------------------------
[  3] local 10.40.5.95 port 52292 connected with 10.40.5.25 port 5001
[  5] local 10.40.5.95 port 52296 connected with 10.40.5.25 port 5001
[  4] local 10.40.5.95 port 52294 connected with 10.40.5.25 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  3.49 GBytes  3.00 Gbits/sec
[  5]  0.0-10.0 sec  3.49 GBytes  3.00 Gbits/sec
[  4]  0.0-10.0 sec  6.88 GBytes  5.91 Gbits/sec
[SUM]  0.0-10.0 sec  13.9 GBytes  11.9 Gbits/sec
```

Then try over Tailscale:
```
# Server side
$ iperf -s

# Client side
$ iperf -c 100.83.184.155 -P 3
------------------------------------------------------------
Client connecting to 100.83.184.155, TCP port 5001
TCP window size:  356 KByte (default)
------------------------------------------------------------
[  5] local 100.75.151.219 port 56306 connected with 100.83.184.155 port 5001
[  4] local 100.75.151.219 port 56304 connected with 100.83.184.155 port 5001
[  3] local 100.75.151.219 port 56302 connected with 100.83.184.155 port 5001
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-10.0 sec   329 MBytes   276 Mbits/sec
[  4]  0.0-10.0 sec   319 MBytes   267 Mbits/sec
[  3]  0.0-10.0 sec   314 MBytes   264 Mbits/sec
[SUM]  0.0-10.0 sec   962 MBytes   806 Mbits/sec
```

Tailscale is over 10x slower. During this time, tailscale is consuming about 3.5 cores worth of CPU, but this is a 64 core machine so it seems like it should have plenty of headroom.

### OS

Linux

### OS version

Linux ip-10-40-5-95 5.11.0-1023-aws #24~20.04.1-Ubuntu SMP Fri Dec 3 13:46:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Tailscale version

1.22.2

### Bug report

BUG-3ba1204a6d9f53de58f077a54f5c6ecfc88a44ffe25da143ab5cc6c60cc8e470-20220322001900Z-2fa2c0e497cf86f1

**Comment by bradfitz** [comment]
I'm not sure we'd do anything differently for this bug over #414. That's the general performance tracking bug.

There's also #426 and #3264 for kernel-accelerated Tailscale on Linux.

It's definitely on our radar. I think I'll close this bug rather than spreading updates haphazardly across very similar bugs.
