### ISSUE TITLE
tailscaled crashes (SIGILL) on macOS

### ISSUE THREAD

**Issue by djmarcin** [tailscale/tailscale#4255]
### What is the issue?

I installed tailscale via the instructions here: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

After authing with a tagged api key, tailscaled crashes. Attempting to run it manually shows the following log. Clearing `/Library/Tailscale` and reauthing causes it to crash again reliably.

Log was too big for github issue comment, so copied to here: https://gist.github.com/djmarcin/2ec55f21f8b06fc8edff7e1f0908b14d

### Steps to reproduce

Install v1.22.2 with https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS on macOS Big Sur. Authenticate with a tagged key. I have not tried with untagged keys or password authentication.

### OS

macOS

### OS version

Darwin buildkite-macos-x86-64-230eff.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Tailscale version

1.22.2

### Bug report

daemon is not running so cannot generate a bug report

**Comment by bradfitz** [comment]
Dup of https://github.com/golang/go/issues/51759

Use Go 1.17.x for now (which is still supported on Tailscale 1.22.x branch) until Go 1.18.1 is out.

**Comment by bradfitz** [comment]
We've worked around this server-side. You can use Go 1.18.0 on macOS now.
