### ISSUE TITLE
hostinfo: add bool for tsnet?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4256]
Do we track whether a node is tsnet?

We probably should.

/cc @DentonGentry @maisem

**Comment by DentonGentry** [comment]
Would we want it to also report the rest of the stuff in HostInfo? I guess we would.

**Comment by bradfitz** [comment]
Well, it already reports all the stuff in Hostinfo. It says it's Linux, the kernel version, etc, but no `env=tsnet` or anything.
