### ISSUE TITLE
New devices seem to not get the ACLs

### ISSUE THREAD

**Issue by MatMaul** [tailscale/tailscale#4264]
### What is the issue?

When registering a new device, the ACLs seem to not be applied and everything is closed (no access).

### Steps to reproduce

Restarting the daemon or even the computer doesn't help.

Changing the ACL file (commenting a line, save, uncomment, save) in the admin interface makes it work.

I was able to reproduce pretty reliably with both my personal and pro account.

### OS

Linux

### OS version

Fedora 35

### Tailscale version

1.22.2

**Comment by MatMaul** [comment]
Well I can't reproduce anymore on my work tailscale network. I'll try again later on on my personal one.

**Comment by bradfitz** [comment]
Well, if you come up with a repro, reopen this bug with a `tailscale bugreport` output so we can look what's happening.
