### ISSUE TITLE
cant run command tailscaled up

### ISSUE THREAD

**Issue by rayqusa** [tailscale/tailscale#4269]
### What is the issue?

I have tried install tailscaled as follow on https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

Installing golang 1.18
tailscaled 1.23.0-dev

running command
go install tailscale.com/cmd/tailscale{,d}@main

sudo $HOME/go/bin/tailscaled install-system-daemon

but I cant run tailscaled up

it said
rayqusa@Rayqusas-Mac ~ % tailscaled up
2022/03/24 13:15:44 tailscaled does not take non-flag arguments: ["up"]

I think the main problem is my terminal use "%"
how to return use "$"

thank you

### Steps to reproduce

install golang

go install tailscale.com/cmd/tailscale{,d}@main

sudo $HOME/go/bin/tailscaled install-system-daemon

rayqusa@Rayqusas-Mac ~ % tailscaled up
2022/03/24 13:15:44 tailscaled does not take non-flag arguments: ["up"]

### OS

macOS

### OS version

Monterey 12.2

### Tailscale version

1.23.0-dev

**Comment by rayqusa** [comment]
<img width="522" alt="Screen Shot 2022-03-24 at 13 20 44" src="https://user-images.githubusercontent.com/9047814/159854659-ae4e04d9-811d-4918-9f84-e659a16ac22b.png">

**Comment by maisem** [comment]
The command you're looking for is `tailscale up` not **`tailscaled`**`up`
https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS#use-the-tailscale-cli-tool

**Comment by rayqusa** [comment]
<img width="522" alt="Screen Shot 2022-03-24 at 13 20 44" src="https://user-images.githubusercontent.com/9047814/159857145-f7d9df28-2c16-4475-ab76-daf1f96a0f8f.png">

**Comment by rayqusa** [comment]
<img width="571" alt="Screen Shot 2022-03-24 at 13 38 24" src="https://user-images.githubusercontent.com/9047814/159857216-f8a45eb3-76ae-469d-b2a8-bafa31f2893f.png">

**Comment by rayqusa** [comment]
<img width="512" alt="Screen Shot 2022-03-24 at 13 42 06" src="https://user-images.githubusercontent.com/9047814/159857641-477e0a1d-bece-4682-a423-27d9665917d2.png">

**Comment by bradfitz** [comment]
You have to compile the `tailscale` tool also. The docs show how to compile both:

https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS#compile-tailscale

```
$ go install tailscale.com/cmd/tailscale{,d}@main
```

**Comment by rayqusa** [comment]
<img width="466" alt="Screen Shot 2022-03-25 at 04 13 21" src="https://user-images.githubusercontent.com/9047814/160011292-d75cf344-0a5b-4ec3-ba75-c7e9550eecde.png">

still nothing happened

**Comment by rayqusa** [comment]
<img width="465" alt="Screen Shot 2022-03-25 at 04 15 15" src="https://user-images.githubusercontent.com/9047814/160011461-58c5a845-2cec-4a0e-bf25-2b81502940f5.png">

still nothing happened

**Comment by rayqusa** [comment]
ah, I found the problem. how to completely delete tailscale back end and front end? where is the folder for back end and front end?
![Uploading Screen Shot 2022-03-25 at 04.17.59.png…]()

**Comment by rayqusa** [comment]
ah, I found the problem. how to completely delete tailscale back end and front end? where is the folder for back end and front end?
<img width="471" alt="Screen Shot 2022-03-25 at 04 17 59" src="https://user-images.githubusercontent.com/9047814/160012097-62ff2063-4b0a-4fff-b450-0bdf2c324e2f.png">

**Comment by bradfitz** [comment]
`which tailscale`

**Comment by rayqusa** [comment]
all of it, I want to install from scratch

**Comment by joostschriek** [comment]
> all of it, I want to install from scratch

`which tailscale` will return the location of the binary `tailscale`, meaning the install location. So you can delete the folder.
