### ISSUE TITLE
Intermittent DNS resolution failure on macOS using open source installation

### ISSUE THREAD

**Issue by djmarcin** [tailscale/tailscale#4276]
### What is the issue?

We get intermittent failures to resolve a DNS name via Magic DNS. This occurs both when using the short name and FQDN.

### Steps to reproduce

Our setup is:
- Install via https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS. We use networksetup commands to set the dns servers and search domains. We also have an additional search domain for our internal services.
```
TAILSCALE_VERSION=v1.22.2
go install -v tailscale.com/cmd/tailscale{,d}@"$TAILSCALE_VERSION"
sudo tailscaled install-system-daemon
tailscale up --authkey "$AUTH_KEY" --accept-routes
sudo networksetup -setdnsservers Ethernet 100.100.100.100 8.8.8.8 8.8.4.4
sudo networksetup -setsearchdomains Ethernet metawork.com.beta.tailscale.net some.internal.domain
```

CI jobs run on these machines and they frequently (several times a day) fail with an error indicating they cannot resolve another tailscale host:
```
ERROR: java.io.IOException: io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host buildkite-macos-x86-64-230eff.metawork.com.beta.tailscale.net.
```

This happens whether we use a hostname that should be found on the search domain like `buildkite-macos-x86-64-230eff` or a FQDN like `buildkite-macos-x86-64-230eff.metawork.com.beta.tailscale.net.`. This only seems to happen on our macOS hosts though, we have never seen this error on linux hosts. This happens on both arm64 and x86_64 machines.

The tailscale bugreport is from a machine that failed DNS resolution, but about 20 minutes prior to the `tailscale bugreport` command. The approximate times of failure was 10:48PT and 10:52PT

### Are there any recent changes that introduced the issue?

We recently updated from 1.14.4 where we were not having this issue to 1.22.2. I am not certain this was the only change to our systems in this time, though.

### OS

macOS

### OS version

Darwin buildkite-macos-arm64-8f2450.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

### Tailscale version

1.22.2

### Bug report

BUG-b6988d256a23f56d08e24c4d114dea3daf3baf83c48b044b6e3f90fcd51bb646-20220324181031Z-ad74b72828abe3c2

**Comment by djmarcin** [comment]
Another bugreport from within 5 minutes of the failure: BUG-a450e8f8fb6a4570990e7bdb15f7674958157e367bfba8ae87ef65e16db2917b-20220324212159Z-7e6f69c69feabfa7

**Comment by djmarcin** [comment]
We think this is because we had been setting multiple dns servers in this line
```
sudo networksetup -setdnsservers Ethernet 100.100.100.100 8.8.8.8 8.8.4.4
```

Changing it to this tentatively seems to have improved things. I'll keep an eye on it and update if we don't see this again over the next day or so.
```
sudo networksetup -setdnsservers Ethernet 100.100.100.100
```

**Comment by DentonGentry** [comment]
Most likely yes, macOS was racing all three DNS servers and using whichever one responded first.

**Comment by djmarcin** [comment]
We have not observed any failures since making this DNS change. It would be great if instructions on how to achieve the appropriate DNS config could be added to the Tailscaled on macOS page where it currently says:
> MagicDNS works, but you need to set 100.100.100.100 as your DNS server yourself. It doesn't yet change your DNS config.

**Comment by DentonGentry** [comment]
I think the original issue in this is understood, that the multiple DNS servers were being raced and the first to respond was used. Since then we've used it to track work on a DNSmanager for Tailscaled-on-macOS. However there is a feature request specifically about that in https://github.com/tailscale/tailscale/issues/1338, so I'm going to close this as resolved and try to use https://github.com/tailscale/tailscale/issues/1338 for remaining work.
