### ISSUE TITLE
Cannot mount Synology SMB over tailscale

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#4280]
### What is the issue?

Cannot mount Synology SMB over tailscale over the internet on Ubuntu 20.04 on a GCP instance. 
(PS. I can see if it is a VM thing which I don't believe it would be)

I get 
`mount error(111): could not connect to IP Address Unable to find suitable address.`

Using cmd 

```
export MNT_DIR=/mnt/$ARHCIVE_NAME
export CURRENT_PIHOLE_DB_DIR=$MNT_DIR/current_version
export PIHOLE_ARCHIVE_DIR=$MNT_DIR/archive
! [[ -d $MNT_DIR ]] && mkdir -p $MNT_DIR
sudo` mount -t cifs -o username=$user,password=$PSSWD //$IP_ADDRESS/$ARHCIVE_NAME $MNT_DIR
```

It should be noted that neither NFS SMB nor FTP have worked over Tailscale with Synology but have worked over Tailscale using a subnet router and a WD Ultra NAS. 
In most cases it seams the host machine cannot find a router to Synology's IP address across protocols 
### Steps to reproduce

Synology 1.16.2 showing no update
Mounting machine running 1.23.123

### Are there any recent changes that introduced the issue?

Has been this way for a while 

### OS version

Linux ctp-vpn 5.13.0-1021-gcp #25~20.04.1-Ubuntu SMP Thu Mar 17 04:09:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Tailscale version

1.23.123

### Bug report

BUG-9a0f06ad3517060a0a3e9d3beddb0519e1a064510316b5e7636aa31649e3b249-20220324212253Z-c25e10fcf6f92aff

**Comment by DentonGentry** [comment]
> Synology 1.16.2 showing no update

The Synology Package Center lags substantially behind https://pkgs.tailscale.com/stable/#spks
I'd recommend installing 1.22.x before debugging further.

**Comment by charlieporth1** [comment]
Sounds good!

**Comment by charlieporth1** [comment]
That seems to fix it
