### ISSUE TITLE
Minor: sysctl issue with interfaces with "." in the name

### ISSUE THREAD

**Issue by vvuk** [tailscale/tailscale#4300]
### What is the issue?

I've got some interfaces that have a period in their name, e.g. "vlan.130".  tailscale seems to use `sysctl` to check for forwarding status, which doesn't work.  Tailscale reports:

```
Warning: Couldn't check system's IP forwarding configuration, subnet routing/exit nodes may not work: couldn't check net.ipv4.conf.vlan.130.forwarding (exit status 255)

# sysctl net.ipv4.conf.vlan.130.forwarding
sysctl: cannot stat /proc/sys/net/ipv4/conf/vlan/130/forwarding: No such file or directory
# ls /proc/sys/net/ipv4/conf/vlan.130/forwarding
forwarding
```

Note that the directory node name should be "vlan.130" but sysctl interprets everything with a period as a delimiter.

### OS

Linux

**Comment by maisem** [comment]
Can you specify which OS and version you are running on and what the output of `sysctl -V` is?

**Comment by bradfitz** [comment]
I saw this too on machine of mine. The replacement character in the sysctl was something strange but I forget what. Have it handy?

**Comment by DentonGentry** [comment]
Here, I guess:
https://github.com/tailscale/tailscale/blob/6fecc16c3b49b3b0cb1d71cae541823c1c038807/ipn/ipnlocal/local.go#L3096

In controlclient we check /proc first, then fallback to systctl, and don't check the individual interfaces at all:
https://github.com/tailscale/tailscale/blob/f3b13604b3dd2ed5875528999873ada3aff06111/control/controlclient/direct.go#L1195

There should probably be a utility function to do this consistently, and check /proc first.
It looks like sysctl can handle slash as a separator as well, so maybe it could be made to handle the vlan.130 interfaces.

**Comment by bradfitz** [comment]
It's a slash:

```
4: ens6f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
5: ens6f1: <BROADCAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
30: ens6f1.2@ens6f1: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
31: ens6f1.3@ens6f1: <BROADCAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
....
# sysctl -a | ...
net.ipv6.conf.ens6f1/2.accept_ra = 0
net.ipv6.conf.ens6f1/2.accept_ra_defrtr = 1
net.ipv6.conf.ens6f1/2.accept_ra_from_local = 0
net.ipv6.conf.ens6f1/2.accept_ra_min_hop_limit = 1
```

**Comment by maisem** [comment]
can you also try `sysctl -n net/ipv6/conf/ens6f1.2/forwarding`

**Comment by MarkSteadAus** [comment]
> I saw this too on machine of mine. The replacement character in the sysctl was something strange but I forget what. Have it handy?

The syntax is to use "eth0/10" in the sysctl command (perhaps the system call is the same).
That will then translate to say:
/proc/sys/net/ipv4/conf/**eth0.10**/rp_filter

It's definitely counterintuitive.
