### ISSUE TITLE
Android client thought there is no Internet while there is

### ISSUE THREAD

**Issue by linsui** [tailscale/tailscale#4303]
### What is the issue?

Sometimes the Android client refuses to connect due to there is no Internet while there is. I have to shut down the app and restart it.

### OS version

Android 11

### Tailscale version

1.22.0

### Bug report

BUG-f32c7dcf9e667c808c7401507f0e99d53a1416158566c46c59d9c2457a238c8d-20220328070203Z-7bdfb663abdb05e6

**Comment by DentonGentry** [comment]
Is this what you saw in the app?

![145515168-455c1162-c929-441e-86f0-13ef9ea54c82](https://user-images.githubusercontent.com/1140756/160433805-d749d40e-95de-492f-857b-4ef1d84fbbe9.jpeg)

Could you tell that devices on the tailnet definitely were not working? Or just that the app said it had paused itself?

**Comment by linsui** [comment]
The devices doesn't work. I can't connect to other nodes unless I restart tailscale app.

**Comment by DentonGentry** [comment]
In 1.30 we're removing the LostInternet function via [tailscale/tailscale-android#57](https://github.com/tailscale/tailscale-android/pull/57)

The Android client was the only platform which tried to do this, and it didn't work very well.

**Comment by linsui** [comment]
Thanks!
