### ISSUE TITLE
FR: Button to prettify ACL rules

### ISSUE THREAD

**Issue by skorokithakis** [tailscale/tailscale#4304]
### What are you trying to do?

It would be nice if the ACL rule JSON were prettified when saving (or with a manual "prettify" button).

### How should we solve this?

Add a "prettify" button or do it on save.

### What is the impact of not solving this?

Uglier JSON, as we don't tend to prettify by hand.

### Anything else?

Nope! Thanks.

**Comment by DentonGentry** [comment]
It is unlikely we would automatically prettify the ACL rules once submitted. The [API](https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-acl-post) allows ACLs to be POSTed, such as from git, such that local changes made within Tailscale's systems would be unknown to the submitter.

A button seems more tractable.

**Comment by bradfitz** [comment]
cc @dsnet for JSON pretty-printing with comments in our hujson fork :)

**Comment by DentonGentry** [comment]
Autoprettification of ACLs on save was added 18 May 2022.
https://tailscale.com/changelog/#2022-05-18-service
