### ISSUE TITLE
Forbidden: CSRF token invalid IOS iPhone unable to autheticate

### ISSUE THREAD

**Issue by swapnilsagarwal** [tailscale/tailscale#4307]
Hi,
I am getting the error 
Forbidden: CSRF token invalid
On iphone SE (Version 2) 
iOS version is 15.4

Thus unable to authenticate.
There is earlier github case : https://github.com/tailscale/tailscale/issues/3225
Which marks as resolved on rebooting ipad.
I have tried deleting and reinstalling app, rebooting phone.
Still stuck at same place.

**Comment by rosszurowski** [comment]
Hi! I'd be happy to help with more details. You're using the iOS app and trying to authenticate a device with a network, and when you try to sign in from the iOS app, it gives you a CSRF error? Can you share a screenshot of the error and URL where you're seeing it?

**Comment by RanveerRB** [comment]
@rosszurowski
I think I have a similar problem. When trying to log in through the mobile app for the first time. 
![123](https://user-images.githubusercontent.com/81791031/164505979-126864fb-7634-4850-b489-3369675bb868.jpeg)

**Comment by yasoob** [comment]
I am facing the same problem on Pixel 3. Tried to log in but every login option results in this error. :/ It worked perfectly fine on my Mac and iOS devices though.

**Comment by hkjasf687261gh** [comment]
i resolved the issue by going to my iOS Safari Settings, and turning off 'Block all cookies'

**Comment by svaliv49** [comment]
I have the same problems; iPhoneSE 2, iOS15.7.1; tried all options from #3225; 
I can login through Firefox app, but it looks like the Tailscale app always opens Safari. Although Firefox is the default browser. 
It worked fine on an iPhone 8 and on the iphone 14.

**Comment by agottardo** [comment]
Closing this as it appears to be a stale issue
