### ISSUE TITLE
tsnet: doesn't work on fly.io out of the box

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#4310]
I have a "hello world" of tsnet integrated into a server running on fly.io. I was unable to connect to it, until I added TS_DEBUG_ALWAYS_USE_DERP=1.

fly.io has some weird requirements to use UDP: https://fly.io/docs/app-guides/udp-and-tcp/. In particular:

> The UDP side of your application needs to bind to the special fly-global-services address.

You can detect that you are running in a fly.io environment by the env var FLY_APP_NAME being set.

And no, I don't plan to send a PR. :) But this might be a good first issue for someone. 😉 

...and on a second look just now, I'd also need to configure fly.io to open up the relevant UDP ports, I think. Which means that tsnet should have a way to configure which UDP ports to use.

**Comment by kotx** [comment]
Just open the [required ports](https://tailscale.com/kb/1082/firewall-ports/).
Add the following in fly.toml (just 41641 is usually enough):
```toml
[[services]]
  internal_port = 41641
  protocol = "udp"

  [[services.ports]]
    port = "41641"
```

Maybe also run `tailscaled` with `--port 41641`.

**Comment by josharian** [comment]
That worked. I had my fly toml messed up.

There is no `--port` for tsnet, but that's OK enough. :)
