### ISSUE TITLE
tsnet: interactive auth didn't happen(?)

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#4313]
### What are you trying to do?

When I first tried using tsnet, I couldn't find the interactive auth prompt amidst the right of the logging noise. That's OK--almost everyone using tsnet is going to want TS_AUTHKEY anyway.

Discovering the requirement to set TAILSCALE_USE_WIP_CODE was easy. I think it should be just as easy to discover the auth options.

One idea: Add a tsnet.Server method that returns an auth URL, and one to provide an auth key. (tsnet.Server is the obvious place to look for how to hold tsnet.) If you attempt to use tsnet.Server without calling either of those methods, or having TS_AUTHKEY envvar set, then it fails just as loudly as if  TAILSCALE_USE_WIP_CODE is not set.

**Comment by bradfitz** [comment]
Sounds like you weren't using the latest code.

**Comment by josharian** [comment]
go.mod says tailscale.com v1.22.2.

**Comment by bradfitz** [comment]
Yup, tsnet is much improved since then. Check it out!
