### ISSUE TITLE
control: let me add notes to my auth keys

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#4314]
### What are you trying to do?

It'd be really useful if I could have a freeform text field associated with each auth key, so I can remind myself why it exists.

**Comment by josharian** [comment]
I think ACL comments probably already fall into this category.

**Comment by DentonGentry** [comment]
>I think ACL comments probably already fall into this category.

Yes, but I think people are less likely to put their RDP password into the ACLs. I could totally see them using authkey notes as the modern equivalent of the password post-it note stuck to the monitor.

**Comment by samlinville** [comment]
@josharian We added a Description field to auth keys, API access tokens, and OAuth clients on Friday. More here: https://tailscale.com/changelog/
