### ISSUE TITLE
Can't issue certificate in unraid docker install

### ISSUE THREAD

**Issue by deasmi** [tailscale/tailscale#4322]
### What is the issue?

If you try and issue a certificate for https the following happens

```
/app # ./tailscale cert 'mynas.**.ts.net
unexpected output: no delimiter
```

Looking at #4060 I tried the curl command

```
/app # curl -v --unix-socket /run/tailscale/tailscaled.sock http://foo/localapi/v0/cert/mynas.**.ts.net?type=pair
*   Trying /run/tailscale/tailscaled.sock:0...
* Connected to foo (/var/run/tailscale/tailscaled.sock) port 80 (#0)
> GET /localapi/v0/cert/mynas.saga-frog.ts.net?type=pair HTTP/1.1
> Host: foo
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Tailscale-Version: 1.22.2-t60b671955-gecc5d9846
< X-Content-Type-Options: nosniff
< Date: Tue, 29 Mar 2022 21:49:23 GMT
< Content-Length: 23
< 
failed to get cert dir
* Connection #0 to host foo left intact
```
I am the maintainer for the unraid docker container.

### Steps to reproduce

```
/app # ./tailscale cert 'mynas.**.ts.net
unexpected output: no delimiter
```

### OS

Other

### OS version

Unraid 6.10.0-rc3

### Tailscale version

1.22.2

### Bug report

BUG-49538552486b5a55787adcba5938a0d3acb460f371cc3582511301060c02e650-20220329215551Z-9ba4e0703564c71d

**Comment by hvddrift** [comment]
@deasmi and @DentonGentry Hi, just seeing if there are any updates on this. Would be great to get this working.

**Comment by iangelov** [comment]
I don't remember what the issue was, and I'm using a different container-based setup, but I know I fixed it by setting both `--state` and `--statedir`. So if that's something that you can override, that might be a way to work around it.

**Comment by hvddrift** [comment]
@deasmi does that help in the unraid version? 

` I fixed it by setting both --state and --statedir`
