### ISSUE TITLE
debug: make DERP send frame (framePeerGone) as limited reply as "nobody's here"

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4326]
Imagine node A is trying to reach node B.

Node A thinks that Node B was last homed at DERP region, say, 5.

But let's say that either Node B disappeared or the control server's broken or Node A's client is broken or... whatever. Assume that Node A can connect to DERP-5 and send frame type `frameSendPacket` to send to B, but then...

_nothing_

Currently we just do nothing (besides increment some varz in `(*Server).recordDrop`), and Node A is none the wiser that Node B isn't in that region.

It'd be nice to send a message (rate-limited) telling Node A that Node B's not there so Node A can locally log "oh, well that's messed up.", which would be useful during debugging connectivity problems.

But we already have `framePeerGone` used for DRPO (#150) that's very close to what we want. We could probably just reuse it, perhaps with a reason byte (reasons being: because they disconnected (the current use, when not listed), or because you tried to send to them, thinking they were here).

/cc @DentonGentry @crawshaw @danderson @maisem

**Comment by danderson** [comment]
Only question I have is what happens during startup race conditions.
 - Client B starts up, locates home derp, reports derp5 as home to control
 - Client A gets told B is at derp5
 - A connects to derp5, sends frame, receives peerGone
 - B connects to derp5
 - ???

If the client doesn't alter its behavior upon receiving peerGone, I guess it's fine and becomes just a debugging aid. Is there anything actionable and inexpensive we'd want to do upon receiving a peerGone?

**Comment by bradfitz** [comment]
Your race is #212 which I'm still unhappy about :)

But yeah, I was thinking this would be purely for debugging and it wouldn't alter the behavior. Except it'd still clear the DRPO route mapping if set, but that's why the frame exists.
