### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by Hannu-5FN** [tailscale/tailscale#4334]
### What are you trying to do?

Enterprise VPN solutions (and SD-WAN later) are strongly moving to the ZTN model but at the application level. (application session). Traditional "trusted" device / IP address or TCP port ACL is not considered sufficient (30-year-old model).

TailScale is a brilliant solution, but many clients stumble upon this ACL management (which is also complex vs. firewall policy management).

### How should we solve this?

Take your time and review how traditional FW Policy management (like CheckPoint) works, then look at native Cloud SASE vendors like Zscaler, Netskope and end it with 128 Technologies (now Juniper Session Smart Router).

After that, create your own vision about it and just do it.

### What is the impact of not solving this?

You will stay the last generation VPN solution vendor forever for micro-companies ;-)

**Comment by bradfitz** [comment]
This isn't quite how we use GitHub so I'm going to close this now as it lacks anything concretely actionable.
