### ISSUE TITLE
Debian sid install instructions should follow new key management approach.

### ISSUE THREAD

**Issue by ianloic** [tailscale/tailscale#4338]
### What is the issue?

When I `apt update` I get a warning line:
```
W: https://pkgs.tailscale.com/stable/debian/dists/sid/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
because using apt-key to manage keys for apt is [deprecated](https://manpages.debian.org/unstable/apt/apt-key.8.en.html#DEPRECATION).

This is easy to fix locally with a command like:
```
curl -fsSL https://pkgs.tailscale.com/stable/debian/sid.noarmor.gpg | sudo tee /etc/apt/trusted.gpg.d/tailscale.gpg > /dev/null
```
but it would be great to have the [instructions for Debian sid](https://tailscale.com/download/linux/debian-sid) updated too. Over time this new approach to key management will spread to stabler versions of Debian and other distros that use apt like Ubuntu.

While it appears that this new version of apt isn't in Debian testing yet, at least back through bullseye `/etc/apt/trusted.gpg.d` is [supported](https://manpages.debian.org/bullseye/apt/apt-key.8.en.html), so those instructions could be updated too.

Note: my one-liner is kind of gross. Some [other instructions](https://bazel.build/install/ubuntu#install-on-ubuntu) do a separate `curl` and `sudo mv`.

### OS

Linux

### OS version

Debian sid

### Tailscale version

n/a

**Comment by awfulcooking** [comment]
The server has umask 0027. Doing `chmod o+r tailscale-archive-keyring.gpg` makes `apt update` succeed.

**Comment by dnwe** [comment]
This warning now also appears on Ubuntu 22.04 (LTS).

Aside: rather than putting the keyring in /etc/apt/trusted.gpg.d where it can apply to any apt repository, it might be preferable to install it into /usr/share/keyrings and specify the location in the `signed-by` attribute of the sources.list entry so it is only trusted for tailscale packages. This is what (e.g.,) Docker do:
```
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/$(lsb_release -cs).gpg \
    | sudo gpg --dearmor -o /usr/share/keyrings/tailscale-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/tailscale-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu \
  $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/tailscale.list > /dev/null
```

**Comment by guss77** [comment]
Installing to `/etc/apt/keyrings` would be a much better idea because `/etc` is site-specific and is expected to be modified by the user while `/usr/share/keyrings` is supposed to be a system installation that is managed by packages and/or is immutable.

**Comment by zhajingwen** [comment]
> The server has umask 0027. Doing `chmod o+r tailscale-archive-keyring.gpg` makes `apt update` succeed.

感谢，这个方案解决了我的问题
