### ISSUE TITLE
tailscaled crashloops on netgear ReadyNAS 312

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#434]
0.99.0 crashloops on Netgear ReadyNAS 312 with:

```
wgengine.New: running "ip rule del pref 10000 table main" failed: exit status 254
RTNETLINK answers: No such file or directory
```

Kernel is `Linux nas 4.4.190.x86_64.1 #1 SMP`. `ip rule` outputs stuff, so it _appears_ that policy routing does exist on the box.

0.98 worked, this is clearly a result of our router improvements, and yet another corner case of a system behaving slightly differently.

**Comment by danderson** [comment]
Looks like this particular iproute2 exits with 254 if you delete a rule that doesn't exist. On other systems we tested, it exists with exit code 2, so our logic to ignore safe errors doesn't fire correctly :(

**Comment by apenwarr** [comment]
The good news is 254 is apparently not used by other versions of 'ip rule' to mean other things, at least.

**Comment by danderson** [comment]
Got access to the NAS in question. I verified that policy routing is enabled, so this is purely an odd quirk of iproute2 3.16.0 compared to the other OSes we've tried.

**Comment by danderson** [comment]
Okay, well that helped in that tailscaled starts and somewhat comes up, but there's other incompatibilities that are preventing wgengine from coming up cleanly. Digging.

**Comment by danderson** [comment]
Different new thing I've never seen before: netfilter works in general, but doesn't know about the `nat` table.

`iptables -L -n -v` works fine.
`iptables -t nat -L -n -v` says "can't initialize iptables table `nat': Table does not exist"

**Comment by danderson** [comment]
Words on the Netgear forums seem to indicate that yes, Netgear deliberately enabled Netfilter but disabled NAT support in their kernel. The relevant module isn't available (completely monolithic kernel), so we're at Netgear's mercy to fix that.

What we could do is make router_linux.go delay configuration of the nat table until it receives a configuration that does subnet routing. We only need to touch the nat table if the configuration requested masquerading of subnet routes _and_ subnet routes are present.

**Comment by danderson** [comment]
Deployed a quick hack to check if that would work... And this NAS kernel also doesn't support the MARK target or match modules, so other bits of configuration also don't work right. Those are also bits of config that we could delay installing until subnet routes are requested, however...

**Comment by danderson** [comment]
Correction: we can't make the forward rules conditional, because they're required for container scenarios like Docker and Kubernetes.

So, for this particular kernel, the options are basically downgrade to 0.98 and the terrible config it came with, or run tailscaled with --netfilter-mode=off and hand-configure the relevant pieces of the firewall. I'm recommending the latter, so there's nothing more to do here in terms of code changes.

**Comment by darribas** [comment]
Does anyone have an update on whether Tailscale is viable in NETGEAR ReadyNAS?

**Comment by DentonGentry** [comment]
There is not currently a package for the ReadyNAS. Work on this is tracked in https://github.com/tailscale/tailscale/issues/882.
