### ISSUE TITLE
设备注册的疑问

### ISSUE THREAD

**Issue by jenarlion** [tailscale/tailscale#4340]
按照官方教程，在自建的服务器上进行设备注册，显示成功，为什么查看服务器list中没有节点，客户端也显示没有虚拟IP，防火墙都是关闭状态，麻烦帮忙指教下，谢谢

**Comment by DentonGentry** [comment]
"According to the official tutorial, the device is registered on the self-built server, and the display is successful. Why is there no node in the server list, the client also shows that there is no virtual IP, and the firewall is closed. Please help me, thank you"

Please email: support@tailscale.com
