### ISSUE TITLE
FR: macOS command line

### ISSUE THREAD

**Issue by at0mat** [tailscale/tailscale#4342]
### What are you trying to do?

I'd like the same cli API as on linux on mac terminal.

**Comment by DentonGentry** [comment]
Please try: `/Applications/Tailscale.app/Contents/MacOS/Tailscale status`

**Comment by at0mat** [comment]
Great, I'll add it to path thank you for the tip.

Thinking for convenience a menu dropdown that adds the necessary path changes / alias in the same sort of experience as with visual studio code you can have `code` alias on terminal.

This is a great project btw, great solution to a vexing problem!

**Comment by bradfitz** [comment]
The App Store GUI variant is sandboxed and doesn't have permission to do that.

We'll be able to do better in the upcoming standalone version, though.
