### ISSUE TITLE
Running Tailscale in Docker with Subnet Routes not work

### ISSUE THREAD

**Issue by willzhang** [tailscale/tailscale#4343]
### What is the issue?

Running Tailscale in Docker with Subnet Routes not work,

can not ping 192.168.72.0/24

### Steps to reproduce

step1:
```
docker run -d --name=tailscaled \
  -v /var/lib:/var/lib \
  -v /dev/net/tun:/dev/net/tun \
  --network=host \
  --privileged \
  tailscale/tailscale tailscaled
```
step2:
```
docker exec tailscaled tailscale up --advertise-routes=192.168.72.0/24
```

### OS

Linux

### OS version
```
root@ubuntu:~# cat /etc/os-release  NAME="Ubuntu" VERSION="20.04.4 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.4 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal
```
### Tailscale version

latest

**Comment by DentonGentry** [comment]
Please include a "tailscale bugreport", as the template asked for, so we can look into what is going wrong. Subnet routes do work in docker containers.

**Comment by DentonGentry** [comment]
Timed out.

**Comment by sparanoid** [comment]
@DentonGentry I also ran into this issue with similar setup. I tried it on a Synology NAS and a raspberry pi with no luck. Could you please took a look into this?

BUG-8b0c4ce520170f9db517c87331ca89f9c0307c82a42123fb7098ef42d7323fb0-20220804201109Z-fa733546ee812044

**Comment by sparanoid** [comment]
@DentonGentry I also ran into this issue with similar setup. I tried it on a Synology NAS and a raspberry pi with no luck. Could you please take a look into this?

BUG-8b0c4ce520170f9db517c87331ca89f9c0307c82a42123fb7098ef42d7323fb0-20220804201109Z-fa733546ee812044

**Comment by willzhang** [comment]
aliyun dns have 100.x.x and Caused by network conflicts with tailscale
