### ISSUE TITLE
Netmap updates with shared nodes

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4351]
### What is the issue?

When a shared node changes keys, it can take some time for the netmap update to propagate .

### Steps to reproduce

Share from tailnet B to tailnet A 
ping from host.A to host2.B
reauth host.A
ping host2.B 

`magicsock: DERP packet from unknown key: [xxxxx]`

host2.B saw the change 3h later.
​
BUG-ebafd3b4e66c650e3d4f48961acbfc73223b1e0cc38f6c07866a2d4cb42a829d-20220404085756Z-4b06363f5673ac94
xref 773fe6c629b4c6602bf92a7622ff3920be7f4b61f024a26b545297c33f7ae141

### OS

Windows

### OS version

10

### Tailscale version

1.22.2

### Bug report

BUG-ebafd3b4e66c650e3d4f48961acbfc73223b1e0cc38f6c07866a2d4cb42a829d-20220404085756Z-4b06363f5673ac94

**Comment by nitzanm** [comment]
Is there anything I can do via the client or console to work around this issue when it occurs, other than waiting? Disconnecting/reconnecting or reauthenticating the client doesn't seem to help.

**Comment by DentonGentry** [comment]
There is a pull request in the private repo which is relevant for this https://github.com/tailscale/corp/pull/4260

**Comment by DentonGentry** [comment]
Tracking in https://github.com/tailscale/corp/issues/5562 (which y'all won't be able to see, sorry)

**Comment by DentonGentry** [comment]
This was fixed by a control server deployment in early June.
