### ISSUE TITLE
Search domains are left in config (on macOS) even after disabling Magic DNS

### ISSUE THREAD

**Issue by djc** [tailscale/tailscale#4355]
### What is the issue?

While Magic DNS was disabled, Tailscale left a search domain in my machine's network configuration.

A while ago, I experimented with Magic DNS in order to make various interfaces in our Google Cloud environment more easily accessible from our development machines. To that end, I also set up a search domain for "internal", to see if we could resolve Google's internal metadata server from our dev machines. After setting it up I concluded that Magic DNS wasn't quite as magic as I had hoped and I disabled it again, to avoid messing with everyone's configuration unnecessarily.

However, recently I became aware that some processes had become suspiciously slow, including `gcloud auth print-access-token` (which is also used for our internal services when starting up in a development environment). Some searching turned up https://stackoverflow.com/questions/62960914/gcloud-auth-print-access-token-to-get-refresh-token-runs-slow-on-my-mac-os-x which notes that gcloud might be trying to access the internal metadata server. This should not be an issue if it fails fast, but apparently caused substantial latency when "internal" is configured as a search domain without the network service actually being available.

I finally noticed that `internal` was listed in `/etc/resolv.conf` on my macOS machine. Of course this file is just a transcript of internal system configuration on macOS, so the search domain configuration can be more directly reviewed with `scutil --dns`, which showed:

```
resolver #2
  search domain[0] : internal
  nameserver[0] : 169.254.169.254
  if_index : 21 (utun3)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
```

Reenabling a global name server in the DNS tab of the Admin console so that I could remove the search domain there, then disabling Magic DNS again changed my local configuration to remove the search domain from `scutil --new`. My system does not appear to have rewritten `/etc/resolv.conf` to exclude the search domain, but that apparently does not have much impact.

### Steps to reproduce

1. Enable Magic DNS for testing, including setting a search domain
2. Disable Magic DNS again after testing did not result in the desired results

### OS

macOS

### OS version

macOS Monterey 12.3

### Tailscale version

1.22.1

### Bug report

BUG-827b6a8f57f028b54453c860968888343f3228366677fb123da787bba5bbb8ec-20220405120737Z-ab6ed0105c6dd597

**Comment by DentonGentry** [comment]
MagicDNS is specifically the 100.100.100.100 server which can answer Tailscale hostnames. If MagicDNS is Disabled but a Split DNS server configuration has been left in place, the Split DNS config will still be applied. Removing the Split DNS server was the way to remove that configuration.

Similarly, if MagicDNS is disabled but global nameservers have been left configured and "Override local DNS" is checked, the global DNS servers will still be configured on devices.

**Comment by djc** [comment]
Hmm, that's fair. I may even have left the configuration in place intentionally, I no longer remember.
