### ISSUE TITLE
FR: give more fine grained control over node key expiry

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4357]
### What are you trying to do?

For some devices, such as laptops and phones, a short key expiry time is prudent. For other nodes, such as on-prem servers, that is less ideal. Currently, we only offer a tailnet-wide expiry.

### How should we solve this?

Allow admins to set max_key_duration either by machine, or by user

### What is the impact of not solving this?

Increased risk of long expiry times for machines which may be lost or stolen vs. increased workload of reauthenticating frequently for nodes for which this is less of a concern.

**Comment by maisem** [comment]
We made tagged nodes not expire by default https://tailscale.com/blog/tagged-key-expiry/.
Does that address this concern, or is the ask different?

**Comment by JayWStapleton** [comment]
> We made tagged nodes not expire by default https://tailscale.com/blog/tagged-key-expiry/. Does that address this concern, or is the ask different?

That is the solution I will be offering for now. I will keep this up to allow users to + if it will solve issues for them.

**Comment by DentonGentry** [comment]
Since I think we addressed the original issue by making tagged nodes not expire by default, I'm going to close this. We should open new issues if there are new use-cases to address.
