### ISSUE TITLE
Cannot build the sourcecode from new clone

### ISSUE THREAD

**Issue by phathuynh5519** [tailscale/tailscale#4358]

**Comment by DentonGentry** [comment]
> gogio: /usr/bin/javac -target 1.8 -source 1.8 -sourcepath /usr/local/go/pkg/mod/gioui.org@v0.0.0-20220228171706-79bfd3adbd32/app -bootclasspath /opt/Android/platforms/android-30/android.jar -d /tmp/gogio-3468601085/classes /usr/local/go/pkg/mod/gioui.org@v0.0.0-20220228171706-79bfd3adbd32/app/Gio.java /usr/local/go/pkg/mod/gioui.org@v0.0.0-20220228171706-79bfd3adbd32/app/GioActivity.java /usr/local/go/pkg/mod/gioui.org@v0.0.0-20220228171706-79bfd3adbd32/app/GioView.java failed: /usr/local/go/pkg/mod/gioui.org@v0.0.0-20220228171706-79bfd3adbd32/app/GioView.java:50: error: cannot find symbol
import android.view.inputmethod.SurroundingText;

I believe you need to install Android SDK 31.
