### ISSUE TITLE
FR: Android: Exit node button without opening menu

### ISSUE THREAD

**Issue by Lesmiscore** [tailscale/tailscale#4383]
### What are you trying to do?

I frequently change between multiple exit nodes, or even disabling it.
When I want to enable EN from disabled state, I need two extra taps to do that, while I need just two taps to disable.

### How should we solve this?

I'd like you to add "Enable exit node" button at app's initial page, when there's any configured exit node.
I think it can be thinner than current "Using exit node" banner.

### What is the impact of not solving this?

Explained at "What are you trying to do?"

**Comment by m4ha7m4** [comment]
Please implement this for all apps.  I enable/disable my exit note on 4 devices at LEAST 4-5 times a day EACH as I change networks often and need to test/bypass various network configurations but keep Tailscale active.  

Enabling/disabling a default exit node on Android and iOS should only take 1-2 seconds to perform via a shortcut, a notification button, etc. just like activating/deactivating Tailscale itself.  

The current process is just cumbersome enough that it is easier to just disable/exit Tailscale entirely and I often lose remote access to that device if I forget to enable again.

**Comment by mayakacz** [comment]
We have a mobile app redesign that addresses this.
We don't yet have a timeline on when this will be released.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/4642 links to a repo containing an implementation (albeit with drawbacks, described in the issue).

**Comment by DentonGentry** [comment]
The link in https://github.com/tailscale/tailscale/issues/4642 no longer work, unfortunately.

**Comment by Lesmiscore** [comment]
maybe: https://github.com/praneetloke/tailscale-android

**Comment by sonovawolf** [comment]
Closing out because this is likely fixed by this "Enable" button here that has been part of all the mobile app redesigns.

![CleanShot 2024-08-29 at 17 22 44@2x](https://github.com/user-attachments/assets/9e65fa0c-8d41-4228-b80c-60a98f892f18)
