### ISSUE TITLE
Tailscale doesn't use local DNS settings when disconnected

### ISSUE THREAD

**Issue by kotx** [tailscale/tailscale#4387]
### What is the issue?

On macOS, when Tailscale is disconnected, the "Tailscale Tunnel" in the Network panel of System Preferences shows as still connected. Only when Tailscale is completely quit (along with tailscaled) does the tunnel disconnect. While the tunnel is disconnected and/or the "Use local DNS settings" setting is on, Tailscale seems to use 8.8.8.8 to resolve DNS, instead of the local DNS.

### Steps to reproduce

1. Install Tailscale on macOS
2. Set DNS settings (e.g. [with a NextDNS apple configuration profile](https://apple.nextdns.io))
3. Disconnect from Tailscale or enable Local DNS option
4. Check https://my.nextdns.io or whatever other method you use to check what DNS server you are using. 

### OS

macOS

### OS version

macOS Monterey 12.3.1

### Tailscale version

1.22.1

### Bug report

BUG-fd5a8eb0c144ef26bfddeebe8d11b18e6463467e20fc3d99c1af93d0a0f3d6f5-20220409011050Z-ca16ded88abc2874

**Comment by mihaip** [comment]
From what I can tell this is may a bug/quirk in the macOS `NETunnelProvider` DNS settings (not the first, as @danderson can attest). Given this setup:

1. Network interface set to 1.1.1.1 (Cloudflare DNS)
2. Tailnet set to 8.8.8.8 (Google DNS) (and "Override local DNS" enabled)
3. NextDNS configuration profile installed

With Tailscale running and "Use Tailscale DNS Settings" enabled in its preferences, Google DNS ends up as the resolver (as shown by my.nextdns.io), which is expected.

When I turn off "Use Tailscale DNS Settings" I see Cloudflare as the resolver, so though we're not having Tailscale override it, macOS is for some reason skipping over the profile and going straight to the network interface's config.

If I make some code changes to the Tailscale macOS client to truly return an empty `NEDNSSettings` in the off case (we were still adding an array with `[""]` to `matchDomains`) then it behaves as expected in Safari and Firefox, which use the native DNS resolving capabilities. Chrome must be doing something custom, and even disabling DoH (Security -> Use seecure DNS) does not help.

So this may not be fixable in Chrome (where I see the buggy behavior even when Tailscale is not running), but I will send out a PR that should help with other browsers.

**Comment by mihaip** [comment]
Fix will be in 1.32 (and in the next 1.31 [unstable release](https://tailscale.com/kb/1083/install-unstable/)).
