### ISSUE TITLE
Node logged "map response long-poll timed out" and forgot peers?

### ISSUE THREAD

**Issue by mnordhoff** [tailscale/tailscale#4388]
### What is the issue?

This is vague, but one of my nodes, "flash", suddenly forgot all its peers for no apparent reason. I pasted a log line from before it broke into the issue title, but I don't really know if it's related.

It was apparently still connected to control -- for example, "`tailscale netcheck`" worked, and https://login.tailscale.com/admin/machines showed it was active -- but its "`tailscale status`" didn't show any other nodes and e.g. "`ping`" and UDP traffic didn't work. (On other nodes, "`tailscale status`" still listed it.)

I ran "`tailscale down`" and "`tailscale up`" and it recovered.

syslog events that may or may not be related (in UTC):

```
Apr  8 22:15:05 flash tailscaled[1680825]: Received error: PollNetMap: http2: server sent GOAWAY and closed the connection; LastStreamID=29, ErrCode=NO_ERROR, debug=""
Apr  8 22:15:28 flash tailscaled[1680825]: health("overall"): error: not in map poll
Apr  8 22:15:31 flash tailscaled[1680825]: Received error: PollNetMap: Post "https://login.tailscale.com/machine/[redacted]/map": dial tcp [2a05:d014:386:203:f8b4:1d5a:f163:e187]:443: connect: connection refused
Apr  8 22:15:54 flash tailscaled[1680825]: magicsock: closing connection to derp-12 (idle), age 1m15s
Apr  8 22:15:54 flash tailscaled[1680825]: magicsock: 1 active derp conns: derp-1=cr219h22m0s,wr14m0s
Apr  8 22:15:59 flash tailscaled[1680825]: health("overall"): ok
```
(I redacted the URL, but don't know if it's necessary.)
```
Apr  8 23:35:11 flash tailscaled[1680825]: control: map response long-poll timed out!
Apr  8 23:35:11 flash tailscaled[1680825]: Received error: PollNetMap: context canceled
Apr  8 23:35:28 flash tailscaled[1680825]: health("overall"): error: not in map poll
```
```
Apr  8 23:36:09 flash tailscaled[1680825]: wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
Apr  8 23:36:09 flash tailscaled[1680825]: wgengine: Reconfig: configuring router
Apr  8 23:36:09 flash tailscaled[1680825]: wgengine: Reconfig: configuring DNS
Apr  8 23:36:09 flash tailscaled[1680825]: dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:1}
Apr  8 23:36:09 flash tailscaled[1680825]: dns: Resolvercfg: {Routes:{} Hosts:1 LocalDomains:[]}
Apr  8 23:36:09 flash tailscaled[1680825]: dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
Apr  8 23:36:58 flash tailscaled[1680825]: magicsock: closing connection to derp-12 (idle), age 1m15s
Apr  8 23:36:58 flash tailscaled[1680825]: magicsock: 2 active derp conns: derp-1=cr220h43m0s,wr57s derp-9=cr55s,wr55s
Apr  8 23:37:13 flash tailscaled[1680825]: magicsock: closing connection to derp-9 (idle), age 1m10s
Apr  8 23:37:13 flash tailscaled[1680825]: magicsock: 1 active derp conns: derp-1=cr220h43m0s,wr1m0s
```

From the other stuff in the log, it seemed to be working normally up until 23:36, but I'm not sure. I _noticed_ it was broken a few minutes later.

### Steps to reproduce

I don't know.

### Are there any recent changes that introduced the issue?

Not that I know of.

### OS

Linux

### OS version

Ubuntu 20.04 (amd64)

### Tailscale version

1.22.2

### Bug report

BUG-96a6c309cea2be4f3f98bd647cc8ffac56a256884728f1730f9ce698dbf7c640-20220408235519Z-7ded582092883ac1

**Comment by DentonGentry** [comment]
That does correspond with the timestamp when a new coordination server was deployed: `Server control restarted at 2022-04-08T22:15:07Z.`

Generally though, while there may be a delay or broken connection the result of the server restarting isn't supposed to be noticeable in a behavior change.

**Comment by mnordhoff** [comment]
Running 1.24.2 now (and therefore using controlplane.tailscale.com). Curiously, most of the errors mentioned in this issue still get logged sometimes, but it hasn't fallen over again.

I guess it makes sense. If the bug that caused this happened often, there would be more than one report. :/

```
May 12 00:09:39 flash tailscaled[2930747]: control: map response long-poll timed out!
May 12 00:09:39 flash tailscaled[2930747]: Received error: PollNetMap: context canceled
May 12 00:09:48 flash tailscaled[2930747]: health("overall"): error: no map response in 2m8s
May 12 00:09:48 flash tailscaled[2930747]: health("overall"): ok
```

```
May 12 00:16:54 flash tailscaled[2930747]: control: map response long-poll timed out!
May 12 00:16:54 flash tailscaled[2930747]: Received error: PollNetMap: context canceled
May 12 00:17:05 flash tailscaled[2930747]: health("overall"): error: not in map poll
May 12 00:17:05 flash tailscaled[2930747]: health("overall"): ok
```

**Comment by DentonGentry** [comment]
Not reproducible, I don't expect to make progress figuring out what happened here.
