### ISSUE TITLE
iOS: After starting a Tailscale VPN session and stopping it, the VPN still shows as Connected in iOS VPN settings

### ISSUE THREAD

**Issue by zivagolee** [tailscale/tailscale#439]
**Describe the bug**
After stopping a Tailscale VPN session, the VPN still shows active in iOS VPN settings. Go to Settings -> VPN, and it still shows as Connected Status.

**To Reproduce**
1. Start Tailscale Session from Stopped status
2. Wait until Tailscale VPN is connected and VPN is active
3. Stop Tailscale Session from Active status
4. VPN still shows active from iOS VPN settings

**Expected behavior**
VPN should be Not Connected from iOS settings after stopping Tailscale VPN session.

**Version information:**
 - Device: iPhone 8
 - OS: iOS
 - OS version: 13.5.1
 - Tailscale version: 0.98.159

**Comment by apenwarr** [comment]
Let's merge this into bug #334.
