### ISSUE TITLE
Synology client does not use proxy configuration

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#4395]
### What is the issue?

A customer reports that the Synology package does not use the proxy server set in the Synology configuration [HS issue 506].

### Steps to reproduce

1. Set up a Synology device on a network that blocks outgoing port 80 and 443 but has a proxy server
2. Configure Synology device to use the proxy server
3. Install Tailscale package

### OS

Synology

**Comment by bradfitz** [comment]
Previously: #2605

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/4563 went into Tailscale release 1.24. If anyone produces this issue using 1.24 or later, please reopen the bug.
