### ISSUE TITLE
Tailscale Crash When 'Connect'

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#4407]
### What is the issue?

When I click the connect button on the Tailscale MacOS client, it causes my whole system to kernel panic when it successfully connects.

I've reliably reproduced it by restarting my machine multiple times and starting tailscale at various times to rule out any other software. I've also tried to use other VPN adapters such as IKE and LT2P VPN connections and those work. As far as the VPN adapter is concerned, Tailscale is established and doesn't crash until I click the 'connect' button.

If I can provide any further information please let me know. There were rumours of Little Snitch causing a Kernel Panic, but I've since updated LS and it doesn't seem to be causing the crash. The most reliable crash causer I have found was when I click 'connect' on Tailscale.

OS & Kernel:

Darwin m1max 21.5.0 Darwin Kernel Version 21.5.0: Mon Mar 28 19:53:15 PDT 2022; root:xnu-8020.120.43.111.1~1/RELEASE_ARM64_T6000 arm64

Latest Monterey Beta updated on 28 March.

### Steps to reproduce

Click on the Tailscale connect button.
Observe Crash

### Are there any recent changes that introduced the issue?

Updated to Latest Monterey Beta updated on 28 March.

### OS

macOS

### OS version

21.5.0

### Tailscale version

1.22.1

I haven't been able to submit a Bug report because the moment I open Tailscale, the machine crashes now. If I run the CLI, it won't let me because the Tailscale Daemon is offline.

**Comment by DentonGentry** [comment]
Could you provide any detail about the kernel panic? Otherwise there is nothing we can do here.

I will express skepticism that Tailscale is the actual root cause of a kernel panic when it has no kernel code running. I get that "Connect" is the trigger, that doesn't mean Tailscale is the cause.

**Comment by vysecurity** [comment]
Exactly, you are correct. However, I've been trying to cause the same kernel panic using other VPN connections and adapters and it doesn't trigger.

The only reliable trigger is when I click on Tailscale and connect to the mesh, in which it immediately crashes.

I could make a video, or supply logs to support?

**Comment by DentonGentry** [comment]
You could supply the backtrace of the panic, for a start.

**Comment by vysecurity** [comment]
I'll close this issue, it'll probably get solved when Apple updates.
