### ISSUE TITLE
Linux tailscale node registration via CLI can hang and never timeout

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#4414]
### What is the issue?

Execute `tailscale up --authkey tskey-xxx`

Expectation: Success or Error after reasonable timeout.

Actual: Never timed out. Command has been hanging for over 2+ hour and two different linux vm on US/Los Angeles and  Europe/UK location. 

There appears to be broken timeout code in tailscale client authkey activation code. 

### Are there any recent changes that introduced the issue?

New linux vm install. 

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.22.2

**Comment by DentonGentry** [comment]
"tailscale up" has no timeout. That is deliberate, in case it is running remotely and unattended.

**Comment by diegomontoya** [comment]
> "tailscale up" has no timeout. That is deliberate, in case it is running remotely and unattended.

We checked the logs and while the command `up --authkey` hangs, there are problems with tailscale control nodes:

`Apr 15 06:40:07 dns-la-1 tailscaled[150653]: control: RegisterReq: onode= node=[fVJLD] fup=false
Apr 15 06:40:07 dns-la-1 tailscaled[150653]: Received error: register request: http 500: internal server error
`

Perhaps tailscale up should timeout when it is dealing with `authekey`. Or is it supposed to retry forever?

**Comment by diegomontoya** [comment]
@DentonGentry  Btw, is there a temp outage of Tailcsale Control/DERP nodes at the moment? We are experiencing inability to register new nodes, "API key invalid" or hanging errors (this issue) and some existing nodes having issues with traffic over tailscale DERP servers.

**Comment by diegomontoya** [comment]
After conversation with @DentonGentry, the core issue was found. Caused by linux vm tailscale retaining previous cloned disk state, despite `apt remove tailscale` was used to remove/reinstall tailscale. The failed linux nodes had been disk cloned from a previous tailscale node. 

So the bug in question is actually tailscale pkg removal hooks need to remove `/var/lib/tailscale/tailscaled.state
` file automatically or any future attempt to register will result in hanging `tailscale up --authkey` command with http 500 errors logged to syslog by tailscaled daemon.

**Comment by DentonGentry** [comment]
> So the bug in question is actually tailscale pkg removal hooks need to remove /var/lib/tailscale/tailscaled.state file

I understand that this would have made the situation you ran into quietly work, however removing the state file would break other workflows. For example, switching between the [stable](https://pkgs.tailscale.com/stable/) and [unstable](https://pkgs.tailscale.com/unstable/) release tracks would destroy the node state.

The bug in this which we might be able to address is tailscale up could better distinguish fatal errors from transient. If there is no change that the `tailscale up` will ever succeed on a future retry, then it might as well exit.

We want it to keep trying even in some cases like this one:
- two nodes are in conflict over a node key
- we'd prefer that if you manually fix one of them, the other would then proceed to join the tailnet
- if there isn't a way that either can succeed, both of them should exit with an error

**Comment by diegomontoya** [comment]
How about a documented tailscale cli command that clears all known states/internal files would be a better alternative? Similar to `--reset`. 

`tailscale --unregister`
`tailscale --reset-node`
`tailscale --reset-state`

The cli would remove the state file and logout the machine and perhaps at the same time remove the machine from tailscale control node db. This would check all the usablity boxes. Allow user to cleanly exit all known tailscale state without understanding the details of tailscale inner workings.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/134 discusses such a possibility.

**Comment by mnordhoff** [comment]
FWIW:

"`apt purge tailscale`" will wipe `/var/lib/tailscale`.

"`apt remove`" does not delete "configuration files". (But I don't know precisely how Debian defines that.)

**Comment by wpcarro** [comment]
I'm pretty sure I'm encountering the same issue (but on NixOS).

`tailscale up -authkey file:/path/to/secret` hangs indefinitely. I tracked the issue down to `tailscale-autoconnect` ([from the Tailscale docs](https://tailscale.com/kb/1096/nixos-minecraft/)).

## What happened?
**Background**: I wanted to test new NixOS secrets management using `agenix`.

- This is running on a previously authenticated node that I manually "removed" from the tailnet:

![image](https://user-images.githubusercontent.com/13058701/165155514-1bc3ad32-39ac-44a0-bc5b-14ccc1927c4a.png)

- I tried to rebuild NixOS on that machine, but it hangs indefinitely.

What's the recommended path forward?

**Comment by wpcarro** [comment]
Looks like the following worked for me:

```shell
$ tailscale logout
$ systemctl restart tailscale-autoconnect
```

**Comment by DentonGentry** [comment]
Remaining work is covered in https://github.com/tailscale/tailscale/issues/134
