### ISSUE TITLE
Android: Disabling and Re-enabling quickly enough on S10+ crashes App

### ISSUE THREAD

**Issue by leflambeur** [tailscale/tailscale#442]
**Describe the bug**
I disabled the connection but then realised I had something else to look at

I re-enabled the connection and my routes weren't available and originally when I launched the app toggling repopulated the routes 

When I disabled it again to try this the app crashed

My perception is it was likely trying to set up the interface or routes and I did not give it enough time to do this gracefully 

I noticed I did not have the usual generic android VPN status bar I normally see when I had re-enabled which adds credence to this

Force closing and reopening resolved it

I have sent feedback via the Playstore related to my comment in #431 

**To Reproduce**

Disable, Renable, Disable

Perhaps disbale if the interface isn't setup properly during the re-enable step

**Expected behavior**

It doesn't crash the app, the interface can be gracefully shutdown if it hasn't started properly

**Version information:**
 - Device: [e.g. iPhone X, laptop] Samsung S10+
 - OS: [e.g. Windows, MacOS] Android
 - OS version: [e.g. Windows 10, Ubuntu 18.04]  Android 10 - kernel version 4.14.113 - SE for Android is Enforcing - VPN PP-MOD v2.1 R3.0 - 1 March Security Patch
 - Tailscale version: [e.g. 0.95-0] 0.1 (Playstore Beta)

**Comment by eliasnaur** [comment]
I've yet to reproduce this crash. Can you please try the newly released v0.1.6 and see if the toggle crash persists?

**Comment by leflambeur** [comment]
It behaves a lot better in the most recent release, now it goes to 'Stopped' and resets to that state if I toggle quickly without freezing up, it's not optimal but it's much more user friendly

**Comment by eliasnaur** [comment]
Can you elaborate your description of what's not optimal about the newer behaviour? I don't know what you mean by "...and resets to that state if I toggle quickly".

**Comment by bradfitz** [comment]
Timeout, closing.

@eliasnaur just released v0.1.16 to the beta channel (https://play.google.com/apps/testing/com.tailscale.ipn).

If there are still problems with that, please file a new issue.
