### ISSUE TITLE
Android app cant connect internet correctly

### ISSUE THREAD

**Issue by alphayxc** [tailscale/tailscale#4420]
### What is the issue?

[root@Dv7zuf9w7q ~]# tailscale status
100.123.120.88  90yun-hk2-yxc7700    alphayxc1003@ linux   -
100.68.218.54   90yun-hk1-yxc4790    alphayxc1003@ linux   idle; offers exit node
100.64.7.30     90yun-hk3-san7700    alphayxc1003@ linux   idle; offers exit node
100.114.205.44  meizu-18s-pro        alphayxc1003@ android active; relay "tok", tx 50728 rx 20236
100.85.120.79   san7700              alphayxc1003@ windows active; direct 123.246.200.44:25229, tx 2885704 rx 3399788
100.67.245.20   tencent-mengmai-1    alphayxc1003@ linux   idle; offers exit node
100.98.62.62    windev2202eval       alphayxc1003@ windows offline
100.99.11.16    yxc4790              alphayxc1003@ windows active; direct 223.102.38.131:7407, tx 320192 rx 724752
100.125.228.28  yxc7700              alphayxc1003@ windows active; direct 223.102.38.131:7168, tx 11954376 rx 3282696
status command from centos7 shell interface has been listed above
my android cellphone tailscale app's machine name is meizu-18s-pro
i wanna use any exit node to connect proxy
it didn't work,but every win10 device is working correctly
CLI display 【relay "tok", tx 50728 rx 20236】turn off and on again,it become【 relay "sfo", tx 188 rx 372
】 what does this means?
anyone handsome help

### Steps to reproduce

turn off and on the switch of top left button "stoped/active"
use exit node→"allow lan access","none or other exit node that proofed working by win10 client"
Quit V2rayng and any VPN programs and reboot tailscale android app and turn on again

### OS

Android

### Tailscale version

1.22.0 from google play store

**Comment by DentonGentry** [comment]
Please send this as an email to support@tailscale.com, we need to know your account and information which shouldn't be on a public bug.
