### ISSUE TITLE
tailscale 0.99.1 no longer installs advertised routes

### ISSUE THREAD

**Issue by abreis** [tailscale/tailscale#444]
I upgraded tailscale from `0.98.0` to `0.99.1` (ubuntu18.04, amd64) today and routes from other nodes are no longer showing up.

On one of the endpoints:
```sh
$ tailscale up -advertise-routes=10.0.0.0/26 -accept-routes
$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.0.0.1        0.0.0.0         UG        0 0          0 eth0
10.0.0.0        0.0.0.0         255.255.255.192 U         0 0          0 eth0
```

On another endpoint:
```sh
$ tailscale up -advertise-routes=10.0.3.0/27 -accept-routes
$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.0.3.1        0.0.0.0         UG        0 0          0 eth0
10.0.3.0        0.0.0.0         255.255.255.224 U         0 0          0 eth0
```

Nothing seems out of place on the admin panel:
<img width="847" alt="ts20200605" src="https://user-images.githubusercontent.com/95046/83906786-1dfa6380-a75c-11ea-9159-3db54cb91e9b.png">

Any ideas? Thank you

**Comment by abreis** [comment]
Forgot to mention: 
1. The point-to-point links were working fine (it's how I connected to the machines).

2. Downgrading to 0.98.0 fixes the issue:
```sh
# ...
Setting up tailscale (0.98.0~0) ...
$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.0.0.1        0.0.0.0         UG        0 0          0 eth0
10.0.0.0        0.0.0.0         255.255.255.192 U         0 0          0 eth0
10.0.3.0        100.70.249.13   255.255.255.224 UG        0 0          0 tailscale0
100.64.0.0      0.0.0.0         255.192.0.0     U         0 0          0 tailscale0
100.102.24.48   100.70.249.13   255.255.255.255 UGH       0 0          0 tailscale0
100.113.222.97  100.70.249.13   255.255.255.255 UGH       0 0          0 tailscale0
```

So, likely a regression in `0.99.1`.

**Comment by danderson** [comment]
In 0.99, Tailscale routes moved into a separate routing table (to enable us to avoid routing loops in subnet routing), which the legacy `netstat` tool doesn't display.

To see the routes installed by Tailscale, use `ip route show table 88` or `ip route show table all` (the latter will also print other esoteric routes that are present by default on linux systems).

Can you switch back to 0.99.1 and verify that the routes exist, and that you can reach the subnets? I've tried reproducing on our test network, and my linux node can both advertise and receive routes correctly.

**Comment by abreis** [comment]
Well, it works fine now... go figure. 

I'm baffled, I only went looking for an issue because we lost all traffic between sites the moment I upgraded.

Anyway, thanks for the explanation!

**Comment by jeromegn** [comment]
That does fix it. My bad.
