### ISSUE TITLE
FR: DNS aliases for machine names

### ISSUE THREAD

**Issue by wpcarro** [tailscale/tailscale#4457]
### What are you trying to do?

I'd like to support short-name domains like http://docs/, http://cs/, http://logs/ that all point to one machine in my tailnet. That machine is running nginx to reverse-proxy these to the correct service.

### How should we solve this?

I think if DNS supported additional machine names or aliases it would solve this for us.

### What is the impact of not solving this?

Without this (afaik) I will need N hosts to support N domains.

**Comment by DentonGentry** [comment]
One does this using DNS search domains. When your browser tries to lookup "monitoring" it will append each search domain in its list. If "example.com" is a search domain it will try "monitoring.example.com", get a result back from DNS, and connect.

If using [MagicDNS](https://tailscale.com/kb/1081/magicdns/), the search domain would be example.com.beta.tailscale.net. If you have a node named "monitoring" and type "http://monitoring/" into the browser, it should automatically expand to monitoring.example.com.beta.tailscale.net.

If using [TLS certificates](https://tailscale.com/blog/tls-certs/), the search domain would be tails-scales.ts.net. If you have a node named "monitoring" and type "https://monitoring/" into the browser, it should automatically expand to monitoring.tails-scales.ts.net.

**Comment by wpcarro** [comment]
Thanks for getting back to me! **Warning**: I'm a bit of a networking newbie, so here goes nothing...

We're using MagicDNS, so in the interim, how would you recommend that we support resolving URLs like `docs/`, `cs/`, `logs/` to (eg) `monitoring.example.com.beta.tailscale.net`?

Should we run our own private DNS with CNAME mappings like so:

```
docs monitoring.example.com.beta.tailscale.net
cs   monitoring.example.com.beta.tailscale.net
logs montoring.example.com.beta.tailscale.net
```

I'm struggling to see how DNS search domains would allow us to map `cs/` to `monitoring.example.com.beta.tailscale.net`.

**Comment by DentonGentry** [comment]
I think this would work:

Say you set up a DNS server like https://www.knot-dns.cz/ on a system with Tailscale IP address 100.x.y.z. Choose an arbitrary domain to use like `mydomain.internal`

Set up Knot with a bunch of CNAMES:
docs.mydomain.internal CNAME monitoring.example.com.beta.tailscale.net
cs.mydomain.internal CNAME monitoring.example.com.beta.tailscale.net
logs.mydomain.internal CNAME monitoring.example.com.beta.tailscale.net

Add a Split DNS server to https://login.tailscale.com/admin/dns for domain mydomain.internal pointing to 100.x.y.z. This will also add mydomain.internal as a DNS Search domain.

I think you can now go to http://cs/ and have it end up at http://monitoring.example.com.beta.tailscale.net

**Comment by wpcarro** [comment]
Okay great. Everything is working as expected. Thank you!

For any curious onlookers, I used the following NixOS nginx configuration to reverse-proxy:

```nix
services.nginx.virtualHosts = {
  "cs.hadrian.internal" = {
    serverAliases = [ "cs" ];
    locations."/".proxyPass = "http://localhost:3000";
  };

  "logs.hadrian.internal" = {
    serverAliases = [ "logs" ];
    locations."/".proxyPass = "http://localhost:3001";
  };
};
```

**Comment by thoschworks** [comment]
@DentonGentry 
A solution within Tailscale would be great. The "solution" above is only a workaround for the missing alias feature within Tailscale and it is too complex for many users. I use Tailscale because I don't want to fiddle around.

Reopen the FR, please.

**Comment by sword-jin** [comment]
Is it possible to reopen it, when we developing the systems relys on the subdomain systems, this is very helpful

**Comment by tianon** [comment]
It honestly seems like https://github.com/tailscale/tailscale/issues/1543 would be a nice way to _implement_ this feature, but it looks like rolling it out is blocked because exposing that much "custom" functionality in a general way is a risk -- this is a much smaller ask (very targeted `CNAME` records), that seems like it might be less difficult to support? :thinking:
