### ISSUE TITLE
FR: Display name for exit nodes

### ISSUE THREAD

**Issue by sylr** [tailscale/tailscale#4458]
### What are you trying to do?

I've received complaints about my exit node names being too barbaric for regular users.

In my company we use the following pattern `<purpose>-<location>-<env>-##` for machine names (including tailscale exit node) which translate to `tailscale-euc1a-infra-01`, `tailscale-euw2a-infra-01` ... etc.

The location is a short code for AWS regions and availability zones and that is what confuses my non IT people.

They wish they could select `london-01`, `frankfurt-01` ... etc in the tailscale client.

### How should we solve this?

They wish they could select something that looks like this in the tailscale client: `london-01`, `frankfurt-01` ... etc.

### What is the impact of not solving this?

Happy non IT people.

**Comment by DentonGentry** [comment]
The exit nodes can have their hostnames set using `tailscale up --hostname=london-01` and so on, it doesn't have to be tied to the hostname of the underlying EC2 instance.

**Comment by sylr** [comment]
Yes, but on my side (the IT side) I wish I could keep the machine hostname in MagicDNS.

**Comment by DentonGentry** [comment]
To set expectations: we're more likely to assist with choosing an appropriate exit node, such as choosing the closest one, than to implement a concept of display names separate from hostnames.
