### ISSUE TITLE
Auto-approved routes not reflected by GET device routes API call

### ISSUE THREAD

**Issue by Shadow6363** [tailscale/tailscale#4502]
### What is the issue?

Auto-approved routes for a device don't show up under `enabledRoutes` when calling the GET device routes API endpoint.
The routes do show up as approved in the Tailscale UI.
I would expect any calls to the GET device routes API endpoint would reflect the same state as the UI.

### Steps to reproduce

1. Permit a device's tags to auto-approve a given route.
```json
  "autoApprovers": {
    "routes": {
      "10.0.0.0/29": [
        "tag:gcp-enterprise-uat"
      ],
    }
  }
```
2. Start a device with that tag that advertises the specified route.
3. Check the approved routes in the UI. They should be approved.
4. Call the GET device routes API endpoint. The `advertisedRoutes` are correct; however, `enabledRoutes` is empty or inaccurate.

**Note:** Disabling the route through the UI and then re-enabling the route through the UI results in the API call returning the correct results.

**Comment by DentonGentry** [comment]
Can you tell if the routes are actually working at the point when enabledRoutes is empty?

**Comment by maisem** [comment]
This is will be picked up as part of the next deployment.

**Comment by Shadow6363** [comment]
Thank you!!
