### ISSUE TITLE
Can't use custom StateStore with tsnet

### ISSUE THREAD

**Issue by jlelse** [tailscale/tailscale#4506]
### What is the issue?

I tried to implement a custom database-based ipn.StateStore for use with tsnet. But when I try to run it, it reports "in-memory store is only supported for Ephemeral nodes".

I found this code:

```go
if s.Store != nil && !s.Ephemeral {
  if _, ok := s.Store.(*mem.Store); !ok {
    return fmt.Errorf("in-memory store is only supported for Ephemeral nodes")
  }
}
```

That looks like custom StateStores aren't supported?

### OS

Linux

### Tailscale version

1.24.0

**Comment by maisem** [comment]
Whoops! That looks like a typo.
