### ISSUE TITLE
Android TV NVidia Shield cannot select exit node using standard remote

### ISSUE THREAD

**Issue by csp5me** [tailscale/tailscale#4509]
Android TV used - Nvidia Android v11. Tailscale v1.24.0.
Standard remote can access all of the user interface controls, except the menu to choose and apply the exit node.
I can choose the exit node, however it cannot be applied. Only using a air mouse remote allows me to apply the exit node change.

**Comment by DentonGentry** [comment]
So you cannot use the select button to activate the exit node?

Does the select button work anywhere else in the UI? If you are in the machines list and push the button on one of the entries, does it say it has copied the machine's IP address?

![PXL_20220425_124727450](https://user-images.githubusercontent.com/1140756/165093137-3df9b542-834f-481e-8f9c-2df47924f679.jpg)

**Comment by DentonGentry** [comment]
ETIMEDOUT.

**Comment by soleous** [comment]
Did we ever figure out a fix for this?  I am getting hit by this and I'm needing to change the server
