### ISSUE TITLE
Android TV v9.0 - Tailscale v1.24.0, Tailscale does not work on Android TV v9

### ISSUE THREAD

**Issue by csp5me** [tailscale/tailscale#4510]
After succesfully installing Tailscale on Android TV v9.0, Tailscale starts with a white screen, then black screen and will exit. 
Clearing data and cache does not solve the issue.

Tailscale does not have problem with Android [TV] v10+.

**Comment by DentonGentry** [comment]
We see similar behavior on an NVideia Shield with Android 8, but haven't figured out how to fix it yet: https://github.com/tailscale/tailscale/issues/4332

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/4332
