### ISSUE TITLE
Installation fails in Ubuntu server 22.04 (Public key is not available)

### ISSUE THREAD

**Issue by lordraiden** [tailscale/tailscale#4514]
### What is the issue?

I followed this and the installation failed
https://tailscale.com/kb/1172/install-ubuntu-2110/
Public key is not available

### Steps to reproduce

![imagen](https://user-images.githubusercontent.com/17175395/165085271-12fbd4bb-0888-4662-b18d-e3b84d93e3a3.png)

### Are there any recent changes that introduced the issue?

Fresh install on ubuntu server 22.04 minimal

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

N/A

**Comment by DentonGentry** [comment]
Could you `apt update` once and try again? We have seen this happen at least once before, but not always, on a freshly installed system.

**Comment by lordraiden** [comment]
https://pkgs.tailscale.com/stable/#ubuntu-jammy
