### ISSUE TITLE
Tailscale CLI command with invalid tags cause on Linux causes device to logout inaccessible out and be inaccessible.

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#4516]
### What is the issue?

Tailscale CLI command with invalid tags cause on Linux causes a device to logout and be inaccessible. CLI tags may include typos and not currently valid tags in the Admin interface. This is the cause for this issue #4445.
The scenario this happens is cron job with tailscale up auto feature automation with a timeout that causes tailscale to show the login URL and logs the device out prematurely. The script should thru an error saying invalid tag,.

### Steps to reproduce

Ubuntu 20.04 and a tag that does not exist

### Are there any recent changes that introduced the issue?

No

### OS

Linux, macOS

### OS version

Ubuntu 20.04

### Tailscale version

1.25.0   tailscale commit: d819bb3bb0435d88c8c8f22bd76878b6c1bf650f   other commit: 19bb65b318113bce5a3536c89b4f10b9aa4929f9   go version: go1.18.1-ts710a0d8610

**Comment by charlieporth1** [comment]
To clarify the device is already logged in

**Comment by DentonGentry** [comment]
The issue occurs because the node is logged out first, then the new authkey applied. If that new authkey fails, the node is left with no working tailnet authentication.

One relevant alternative: the tags can be set on the authkey, to avoid the chance of typo: https://tailscale.com/blog/acl-tags-ga/

**Comment by charlieporth1** [comment]
Interesting

**Comment by DentonGentry** [comment]
I think the solution to this is tagging the authkey instead of using the CLI with typos.
