### ISSUE TITLE
macOS: "write: can't assign requested address"

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#452]
This was happening to me for a while (macOS 10.14.6), but then went away again:
- Stop tailscale macOS app (already logged in)
- Start tailscale macOS app
- After ~1 second, it switches to connected state
- This message starts appearing periodically (and triggering the netmap backoff timer):

`7.4M/33.5M Received error: PollNetMap: Post "https://login.tailscale.com/machine/ccbbd9bf064ac3c84bae2f576cbed8aed3ddc52256132d84e1d789f4bf2fb362/map": write tcp 192.168.0.47:53180->3.121.18.47:443: write: can't assign requested address`

- It seems like tailscale can no longer talk to login.tailscale.com after that.

What's weird is it clearly could talk to login.tailscale.com at least once (to get the initial netmap, because everything connected correctly and kept working), but then stopped working. Internet searches suggest that this might be because of a macOS bug, but it seemed too consistent. That said, the problem suddenly went away for me (without rebooting, but after restarting the app a bunch of times) and hasn't recurred yet.

Logid: 6ad6deaf2a46a0a3c1e1ee9136b18be2088ec7fcdf5ae7ff760342e65beed51a

Note: this is seemingly *not* the same error as: `TryLogin: fetch control key: Get "https://login.tailscale.com/key": dial tcp 3.121.18.47:443: connect: can't assign requested address`. That error happened to several users who were having trouble with virus scanners, possibly ESET. But "connect: can't assign requested address" is different from "write: can't assign requested address."

Since this prevents us from getting netmap updates, it causes Tailscale to need to be restarted, which would be pretty serious once it occurs.

**Comment by DentonGentry** [comment]
It has been nearly a year since this happened, with no additional occurrences noted. In the next bug scrub if barring further updates, I'd expect to close this.

**Comment by DentonGentry** [comment]
ETIMEDOUT after a year.
