### ISSUE TITLE
Android: broken connection over cell

### ISSUE THREAD

**Issue by maxhawkins** [tailscale/tailscale#453]
**Describe the bug**
Enabling Tailscale while connected to cellular (tmobile) makes all internet connections fail with "address unreachable"

**To Reproduce**
1. Acticate the VPN while connected to wifi
2. Visit google.com (loads)
3. Disable wifi and switch to cell
4. Visit google.com
5. The connection fails (unreachable)
6. Disabling the VPN makes it work again
7. Enabling the VPN makes it fail again
8. After force-restarting the app it still fails

**Version information:**
 - Device: Pixel 3a
 - OS: Android
 - OS version: 10
 - Tailscale version: 0.1

**Network info**
Cellular:
network: MOBILE subnetwork: LTE
T-Mobile

NAT:
Port Restricted Nat - random port no hairpin

**Comment by apenwarr** [comment]
Do you have a DNS IP address and search domain set in your tailscale settings at login.tailscale.com/admin? If not, please try filling in those settings to see if it helps.

**Comment by maxhawkins** [comment]
I just added both a DNS address and a search path, then restarted Tailscale. Doesn't seem to help.

**Comment by eliasnaur** [comment]
"address unreachable" sounds like a routing problem, not a DNS problem. Can you please identify your phone's IP address when not connected to a VPN? I found my IP address in Settings -> About Phone.

**Comment by maxhawkins** [comment]
Is there a way I can send it privately rather than posting on this public channel?

One interesting note: T-Mobile IPs are IPv6, whereas my home router uses IPv4.

**Comment by eliasnaur** [comment]
Sure, you can send the address to the email address listed on my profile. Are you saying that your device has no IPv4 address while on the T-Mobile cell connection?

**Comment by maxhawkins** [comment]
Sent.

Yes, it is only IPv6. One network utility I tried does list an IPv4 but it is a 172. which I believe is self-assigned.

**Comment by maxhawkins** [comment]
I managed to install a terminal emulator so I could get some more familiar Linux error codes instead of the ambiguous Chrome "address unreachable"

All of these commands were executed while connected to the T-Mobile connection with Tailscale enabled.

![Screenshot_20200615-090454](https://user-images.githubusercontent.com/28565/84680349-63026080-aee7-11ea-89ca-0aaa47f20db9.png)

**Comment by eliasnaur** [comment]
The just released v0.1.6 beta contains a potential fix for this issue. Please let me know how it fares.

**Comment by maxhawkins** [comment]
The update doesn't seem to fix the issue for me.

`curl google.com` still returns "could not resolve host" but now it pauses for ~10 seconds before timing out with that message.

**Comment by rajveermalviya** [comment]
+1

I am experiencing same issue, but via any network (wifi / cellular) on my android phone (Oneplus 7 - Android 10).
BTW tailscale on linux laptop works great via both networks (cellular tested via hotspot).

**Comment by eliasnaur** [comment]
I just released v0.1.7 with another potential fix for the DNS issue. Let me know if it makes any difference.

**Comment by maxhawkins** [comment]
I'm still seeing the same issue on 0.1.7

**Comment by maxhawkins** [comment]
I wonder if this issue is related to #302 (both use tmobile)

**Comment by maxhawkins** [comment]
Fixed in 0.1.8. Thank you!
