### ISSUE TITLE
Setting a custom DERP map for a tailnet doesn't immediately update clients

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#4545]
### What is the issue?

Added a test DERP region to our tailnet, but the client didn't pick up on its existence until I restarted it. This is a problem because it means some clients on the tailnet might register at a custom DERP region that other nodes aren't aware of, even though they should all be in sync.

### Steps to reproduce

Add a custom DERP region to your ACL file, hit save. Run `tailscale netcheck` (which runs off the currently active DERP map in tailscaled). Observe your custom region isn't present. Restart tailscaled, run `tailscale netcheck` again, notice the DERP map is now up to date.

### Tailscale version

1.24.0

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/corp/pull/5076, deployed in May.

Verified that when adding a custom DERP in the policy JSON, the new region shows up immediately in `tailscale netcheck`
