### ISSUE TITLE
iOS app uses cellular data when MagicDNS is turned on

### ISSUE THREAD

**Issue by citadella** [tailscale/tailscale#4546]
Unfortunately it's hard to pin down the exact specifics, but I was able to confirm last night that, when MagicDNS is enabled (though perhaps only when running through an exit node), all my data goes out via cellular data and not via wifi. I am able to fix this by turning off cellular data and it works fine, but this is not what I would expect at all. Unless this is as-designed, I would expect, when connected to Tailscale AND when connected to an exit-node on my phone, data goes out wifi first and cellular data only when wifi isn't available, regardless of whether MagicDNS is enabled. It appears to fool apps as well, as I have multiple apps which will only download things when connected to wifi, but they have ended up using my cellular data because they see a wifi connection but Tailscale sends that traffic out my cellular connection instead.

Device: iPhone 12 Pro
iOS version: 15.4.1
Tailscale iOS version: 1.22.0
Symptoms: when connected to Tailscale (perhaps only to an exit-node) with MagicDNS enabled all my data goes out cellular even when connected to wifi. 
Temporary fix: disable MagicDNS

**Comment by bradfitz** [comment]
@maisem noticed that too the other day. He's started looking at it.

**Comment by citadella** [comment]
Not sure if this was an issue historically or not-I only noticed it in the past few days but that might be due to an update or to an increase in my usage of exit-nodes

**Comment by bradfitz** [comment]
We think it's always been an issue, but 1.24.0 is better at reusing a backend TCP connection to our control plane for a long period of time so it can now stay in a broken state for longer whereas in the past it would "fix" itself more regularly when that TCP connection broke.

**Comment by citadella** [comment]
To be clear, though, I'm running 1.22.0 (the latest version in the App Store)

**Comment by bradfitz** [comment]
Should be fixed by https://github.com/tailscale/tailscale/commit/5a1ef1bbb9b67f11d625c543f16005c8c4ac41ba and be in the upcoming 1.24.1 on the App Store.

**Comment by citadella** [comment]
This has become an issue again. Running the newest version which was supposed to have fixed it but my data just drained out overnight again...

**Comment by Stooovie** [comment]
Same in iOS 16 beta 7. Cellular data used even while on Wifi.
