### ISSUE TITLE
Re-authenticating an existing node with an ephemeral key does not make node ephemeral

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4547]
### What is the issue?

Existing nodes don't become ephemeral when re-authenticated with an ephemeral key unless you stop tailscaled, and delete the state file first. 

It is reasonable to expect that this would be able to shift a node from regular to ephemeral.

### Steps to reproduce

Authenticate machine interactively as normal
Generate an ephemeral key
`tailscale up --force-reauth --auth-key<ephemeral-key>`
Has no noticeable effect. 

### OS

Linux

### Tailscale version

1.24

**Comment by DentonGentry** [comment]
>Existing nodes don't become ephemeral when re-authenticated with an ephemeral key unless you stop tailscaled, and delete the state file first.

I bet it is ephemeral even without deleting the state file, but it will take about an hour after the node drops out of contact with the coordination server before it gets deleted.

When ephemeral nodes use `--state=mem:` they will be deleted the moment they exit, which can make people think they are supposed to always be deleted when they exit.

**Comment by ephsiung** [comment]
Thanks for the info, Denton. This was an issue when we were cutting our
fleet over to ephemeral keys but it is not a problem any more. I don't
recall any situations where we waited an hour but you're likely right that
this would have worked.


Eric

**Comment by DentonGentry** [comment]
Closing as noted in last comment.
