### ISSUE TITLE
macOS menu dropdown shows blank user list

### ISSUE THREAD

**Issue by thehilll** [tailscale/tailscale#455]
**Describe the bug**
On macOS (10.15.4 and 10.15.5) using Tailscale 0.98.197, the sub-menu for "Network devices" shows rows of blanks with a disclosure triangle where the user names should be.  Selecting a row gives a further sub-menu of each user's devices, but you can't see who they are without cycling through the list of blanks (see screenshot).  This is happening for multiple users (all I have polled, haven't found one where it doesn't).

**To Reproduce**
1. Go to menubar item
2. Select Network devices
3. List will have a blank row for each user

**Expected behavior**
See a list of users

**Version information:**
 - Device: MacBook Pro
 - OS: macOS
 - OS version: 10.15.4 and 10.15.5
 - Tailscale version: 0.98.197

![Screen Shot 2020-06-11 at 1 13 58 PM](https://user-images.githubusercontent.com/3237800/84419550-c427ec80-abe6-11ea-917e-7eeba54a6b24.png)

**Comment by bradfitz** [comment]
There should be a human-readable name there there's a bug or misconfiguration with your domain's auth provider integration. We'll fix that.

In the meantime we can probably just modify the server to at least populate email addresses in place of those missing names as a short-term fix.

**Comment by bradfitz** [comment]
@thehilll, server is updated. Try again? (I think you may not even have to log out & back in but try to if it's not fixed.)

**Comment by thehilll** [comment]
Works great, no logout required.  Thanks a lot.

**Comment by bradfitz** [comment]
Great! I assume you only see the email address usernames there for now. We'll fix that to show actual names later, but that might take a bit longer.

**Comment by thehilll** [comment]
Actually I just see the name part (before the @) which is fine

**Comment by bradfitz** [comment]
> Actually I just see the name part (before the @) which is fine

Yeah, that's what I meant by "email address usernames". I almost said `local-part` but figured that was too specific. :-)

**Comment by bradfitz** [comment]
Reopening for @crawshaw to fix properly in the backend.

**Comment by DentonGentry** [comment]
I'm not clear on what we'd do in the backend for this, at this point.

**Comment by DentonGentry** [comment]
Barring further updates or comments, we'll expect to close this during the next bug scrub.
