### ISSUE TITLE
Split DNS behavior changes when using multiple hostnames

### ISSUE THREAD

**Issue by tmitchell** [tailscale/tailscale#4560]
### What is the issue?

Split DNS resolution works correctly with a single hostname, however fails when we add a second hostname.  

Single DNS hostname sets up the configured DNS resolver and everything works fine.
```
$ scutil --dns
...
resolver #2
  search domain[0] : dev.example.com
  nameserver[0] : 172.16.0.2
  if_index : 17 (utun3)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)

$ dscacheutil -q host -a name login.cluster.dev.example.com
name: cluster-XXXXXXXX.elb.us-east-1.amazonaws.com
alias: login.cluster.dev.example.com
ip_address: 172.16.41.165
ip_address: 172.16.16.205
```

When we add a second hostname and DNS server, it instead points us at `100.100.100.100` for both, which fails to resolve anything under either domain. 
```
$ scutil --dns
...
resolver #2
  search domain[0] : dev.example.com
  search domain[1] : staging.example.com
  nameserver[0] : 100.100.100.100
  if_index : 17 (utun3)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)

$ dscacheutil -q host -a name login.cluster.dev.example.com
$
```

The `100.100.100.100` endpoint does succeed at resolving MagicDNS names (which we don't use and doesn't help but shows things are not totally broken) if we enable that:

```
$ scutil --dns
...
resolver #2
  search domain[0] : example.com.beta.tailscale.net
  search domain[1] : dev.example.com
  search domain[2] : staging.example.com
  search domain[3] : x.x.x.x.x.x.x.ip6.arpa
  search domain[4] : 100.100.in-addr.arpa
  search domain[5] : 101.100.in-addr.arpa
  search domain[6] : 102.100.in-addr.arpa
...

$ dscacheutil -q host -a name my-computer.example.com.beta.tailscale.net
name: my-computer.example.com.beta.tailscale.net
ip_address: 100.82.1.5
```

### Steps to reproduce

In Tailscale console, add nameservers for two different subnets, with different hostnames for Split DNS.

Optional - Enable the Global Nameservers and turn on `Override local DNS`, it makes no difference to the behavior.  

Optional - MagicDNS enable/disable similarly does not affect the behavior

### OS

macOS

### OS version

Monterey 12.2.1

### Tailscale version

1.22.1

### Bug report

BUG-b8e640fe76d1c27c8048286c6c6af3b250ac4b5fcb8b873f4fc54e1d811090e6-20220428154235Z-6973a0664bc9996f

**Comment by HunterDG** [comment]
+1.  This is new behavior/regression.  Worked fine a month ago.

**Comment by HunterDG** [comment]
Edit: I started seeing this issue when I switched from a personal account to a GitHub "team" account.  Just tested reverting to personal account and scutil --dns shows the correct search domain/DNS server IP (not 100.100.100.100)

hope this helps.

**Comment by HunterDG** [comment]
I've noticed that multiple split dns domains **pointing to the same ip** still works (even with global DNS disabled) on macOS, so I let my "middleman" upstream DNS perform the split lookups for now as a workaround.

but now a domain-joined windows 11 client (on one of the split domains) can't resolve anything on the other split domain when querying 100.100.100.100, however querying the "middleman" upstream dns directly works fine.  Something's up with 100.100.100.100 resolution and I don't think it's just Mac clients.

**Comment by mihaip** [comment]
@tmitchell are you still experiencing this? I have replicated your setup as closely as I can, and I'm not able to reproduce this (albeit I am running Tailscale 1.26). 

The resolver being set to 100.100.100.100 is expected -- due to limitations in the mac OS APIs we are not able to specify split DNS settings that point to different resolvers, therefore we point everything at Tailscale itself and do the split there (100.100.100.100 is handled internally by the Tailscale daemon).

How are you running Tailscale on the Mac (there are three possibilities: https://tailscale.com/kb/1065/macos-variants/)? If you can generate a bug report ID (option click on the Tailscale menu icon and choose "Debug" > "Bug Report…") after attempting the DNS lookup that would also help with investigating this further.

**Comment by TCC-Systems** [comment]
For what it's worth, Mac users can specify split DNS via CLI - Guess the API is less capable?

**Comment by bradfitz** [comment]
Yes, the `/etc/resolver` hierarchy of files (as used by the open source non-GUI `tailscaled` on macOS) and `scutil` are more powerful than the sandboxed network extension API.

**Comment by TCC-Systems** [comment]
Not OP, but just tested and can confirm split DNS resolution with separate DNS servers appears to be working for me now, when App Store Tailscale  sets the DNS server to 100.100.100.100

**Comment by HunterDG** [comment]
Not OP, but just tested and can confirm split DNS resolution with 2 domains pointing to separate DNS servers appears to be working on Mac for me now (with a public global nameserver set), when latest App Store Tailscale sets the DNS server to 100.100.100.100. I no longer need a middleman/upstream DNS server to handle the split resolution.

Previously I was using an internal DNS server as the "global" name server, (but it forwarded to public).

**Comment by tmitchell** [comment]
@mihaip Tested and confirmed that split resolution is now working using the 100.100.100.100 servers.  Thanks for following up and to the team for addressing this.
