### ISSUE TITLE
FR: Access to the 'pre-authorized' flag on auth keys

### ISSUE THREAD

**Issue by lincolnmantracer** [tailscale/tailscale#4571]
### What are you trying to do?

It would be great to generate pre-authorized keys. Currently neither `GET /api/v2/tailnet/:tailnet/keys/:keyid` (for keys created in the admin interface) or `POST /api/v2/tailnet/:tailnet/keys` has any contemplation of whether the key is pre-authorized. This would be very useful for automatic machine provisioning.

### How should we solve this?

Please add `preauthorized` to `capabilities` on the keys API object. ([While you're at it, maybe `expiry` too?](https://github.com/tailscale/tailscale/issues/4570))

**Comment by bradfitz** [comment]
I verified the fix is live, but we need to do docs still.

**Comment by lincolnmantracer** [comment]
Thank you for the rapid movement on this! I just checked and `POST` with preauthorized also works, but I think that's missing from the docs.
