### ISSUE TITLE
Android: no internet connection/exit node stopped working

### ISSUE THREAD

**Issue by northys** [tailscale/tailscale#4584]
### What is the issue?

Tailscale says "No internet connection" randomly. When it happens it doesn't matter whether I toggle reconnect or turn off exit node feature. My phone is connected actually and there is no exclamation mark shown by android itself.

It can by fixed by killing the tailscale app. The no internet connection isn't shoen anymore but tailscale still doesn't work. When I reboot my phone it gets fixed.

### Are there any recent changes that introduced the issue?

No

### OS version

Android 12

### Tailscale version

1.24.0

### Bug report

BUG-25f11399cad08e7f1b52705c3c62cab63af5d160a6faecdff32523f414149b8e-20220430010847Z-81baf7f849c81836

**Comment by northys** [comment]
It even gets to state where I have tailscale disabled and I can't access the internet. When I go to settings and kill tailscale (VPN connected icon wasn't showed before killing) it gets fixed. It feels like DNS is screwed or something. I have magicdns turned on.

**Comment by northys** [comment]
Ok now I'm it state when enabling my exit node breaks the internet on my phone.  I don't think there is a problem with my exit node though because I use it 24/7 on my homelab server (same LAN as phone) and it works like a charm.

**Comment by northys** [comment]
I've rebooted my phone and my exit node still doesn't work. No internet connection isn't reported and my tailscale private network works.

The homelab is connected to my exit node with no issue. Also my phone was connected about an hour ago. This already happened once yesterday and my phone reboot fixed it :(

```
exitnode  linux   active; exit node; direct xxx.yyy.zzz.133:41641, tx 4722769420 rx 21245102932
```

**Comment by DentonGentry** [comment]
The main problem is that the mobile carrier is also using CGNAT. Near the point of the bugreport we see it reporting an LTE radio with a CGNAT IP address: rmnet1:[100.96.126.244/32]

We also see some looping back in tstun which isn't expected. It might not be related to the connection failure, but is notable because it isn't supposed to happen.
```
2022-04-30 01:08:14.836705159 +0000 UTC: 26.6M/171.9M tstun: [unexpected] received self disco out packet over tstun; dropping
2022-04-30 01:08:14.837119588 +0000 UTC: 26.6M/171.9M tstun: [RATELIMIT] format("[unexpected] received self disco out packet over tstun; dropping")
```

**Comment by northys** [comment]
I'm connected to Wi-Fi using my home ISP. Also I've been using tailscale and exit node with no issue also over LTE.

Maybe when I posted the issue I disabled the wi-fi or something but I'm on WiFi.

Can you please look at this one? I don't know how those string works but I'm 100% sure I'm connected through  WiFi right now.

BUG-25f11399cad08e7f1b52705c3c62cab63af5d160a6faecdff32523f414149b8e-20220430013614Z-e894638fee3b13e7

**Comment by northys** [comment]
My home ISP uses 10.0.0.0/8 subnet. I'm not sure if it's relevant but when I dig something without being connected through tailscale it goes through that subnet.

**Comment by northys** [comment]
Okay, maybe you are right. I've disabled my eSIM and it started to work. Interesting. Do you have any idea why it used to work for me for a few weeks and now it suddenly has problems more than before?

**Comment by northys** [comment]
If the cgnat problem is under the hood I shouldn't forget to mention that I've been using wireguard as the only VPN on this same phone with same provider for about 2 years without even noticing it's running. There were no problem on LTE or any Wi-Fi.

My wireguard endpoint used to be the same server which now serves as exit node.

**Comment by northys** [comment]
It also works right now with tailscale + exit node enabled. It got fixed by disabling and enabling my eSIM. It just doesn't make sence to me.

Sorry for spamming new posts all the time. I'm just writing info as I dig into it.

**Comment by DentonGentry** [comment]
In 1.30 we're removing the LostInternet function via [tailscale/tailscale-android#57](https://github.com/tailscale/tailscale-android/pull/57)

The Android client was the only platform which tried to do this, and it didn't work very well.
