### ISSUE TITLE
Squid blocking `HTTP 101 Switching Protocols` for ts2021 control protocol

### ISSUE THREAD

**Issue by lmariscal** [tailscale/tailscale#4593]
### What is the issue?

Upgrading to `1.24.0` makes my Arch Linux machine fail all register requests.
Manual downgrade to `1.22.2` fixes all issues.

The logs show this peculiar issue:
```
tailscaled[11197]: control: LoginInteractive -> regen=true
tailscaled[11197]: control: doLogin(regen=true, hasUrl=false)
tailscaled[11197]: control: Generating a new nodekey.
tailscaled[11197]: control: RegisterReq: onode= node=[PmpRR] fup=false
tailscaled[11197]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
```

It tries to bootstrap multiple DNS, but fails with the error shown above.

Something that comes to my notice, is that the given DNS query returns IPv6 ips, and my connection does not have IPv6 support.

```
tailscaled[11197]: trying bootstrapDNS("derp2.tailscale.com", "167.172.206.31") for "controlplane.tailscale.com" ...
tailscaled[11197]: trying bootstrapDNS("derp1e.tailscale.com", "64.225.56.166") for "controlplane.tailscale.com" ...
tailscaled[11197]: bootstrapDNS("derp1e.tailscale.com", "64.225.56.166") for "controlplane.tailscale.com" = [2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:203:4535:c15c:9ab:8258 18.193.143.177 52.29.8.43 18.>
tailscaled[11197]: bootstrapDNS("derp2.tailscale.com", "167.172.206.31") for "controlplane.tailscale.com" = [2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:203:4535:c15c:9ab:8258 2a05:d014:386:201:7200:6340:b22f:7df6 18.193.255.254 18.193.143.177>
```

### Are there any recent changes that introduced the issue?

Upgrade to version `1.24.0`

### OS

Linux

### OS version

Arch Linux

### Tailscale version

1.24.2

### Bug report

BUG-5d5755c6999f2ac53b3b3db41c858b0c268afe62045e8f3e53871c649fa3de6c-20220501134214Z-a37f237258c7a5b2

**Comment by DentonGentry** [comment]
1.24.0 contains a new implementation of the control protocol. There were several issues about connecting using the new protocol with MITM, ports blocked, or IPv6 connectivity issues which were resolved in 1.24.2. I'd recommend staying with 1.22.x until Arch updates to 1.24.2, and try it then.

**Comment by lmariscal** [comment]
This issue is occurring in version `1.24.2`.
https://archlinux.org/packages/community/x86_64/tailscale/

**Comment by DentonGentry** [comment]
Near

```
2022-05-01 14:39:48.703706178 +0100 +0100: Program starting: v1.24.2, Go 1.18.1: []string{"/usr/sbin/tailscaled", "--sta
te=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "41641"}
...
2022-05-01 14:40:12.72709539 +0100 +0100: trying bootstrapDNS("derp9.tailscale.com", "207.148.3.137") for "controlplane.tailscale.com" ...
2022-05-01 14:40:13.222997674 +0100 +0100: bootstrapDNS("derp9.tailscale.com", "207.148.3.137") for "controlplane.tailscale.com" = [2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:203:4535:c15c:9ab:8258 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 18.193.143.177 52.29.8.43 18.193.255.254]
2022-05-01 14:40:13.305200138 +0100 +0100: control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
...
2022-05-01 14:40:23.306850421 +0100 +0100: control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
2022-05-01 14:40:23.306976689 +0100 +0100: control: sendStatus: authRoutine-report: state:authenticating
2022-05-01 14:40:23.307060173 +0100 +0100: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
...
2022-05-01 14:42:14.329577727 +0100 +0100: user bugreport: BUG-5d5755c6999f2ac53b3b3db41c858b0c268afe62045e8f3e53871c649fa3de6c-20220501134214Z-a37f237258c7a5b2
```

**Comment by bradfitz** [comment]
Are you behind a firewall or some network security device? We know Snort has a bug for instance that was reported to them.

In any case, we'd like to fix this for you once we can see what's happening. Are you able to email us a packet capture?

**Comment by lmariscal** [comment]
I am most likely behind a firewall, and do not have access to the router settings.  
Happy to provide you with the needed information if you give me the steps to properly capture it.

**Comment by DentonGentry** [comment]
For example to use tcpdump to get a packet capture:
- `sudo apt install tcpdump`
- `sudo systemctl stop tailscaled`
- `sudo tcpdump -i eth0 -w /tmp/out.pcap host controlplane.tailscale.com`
- (in another shell) `sudo systemctl start tailscaled`

Leave the tcpdump running for about a minute after starting tailscaled, then hit control-C. You should see /tmp/out.pcap is larger than zero bytes. You can attach it to the bug here, or if not comfortable making it public you can email it to support@tailscale.com and mention this bug.

**Comment by normanr** [comment]
Does the new control protocol use https_proxy correctly? I upgrade my constrained environment to 1.24.2, and it's failing to connect at start up. Downgrading to 1.22.2 didn't fix it :-/

**Comment by pguinet** [comment]
Have the same problem on CentOS 7. Did the packet capture and sent it to support by mail.

**Comment by bradfitz** [comment]
> Does the new control protocol use https_proxy correctly? 

@normanr, it sure is supposed to. @danderson wrote a bunch of tests to verify that it does, even:

https://github.com/tailscale/tailscale/blob/main/control/controlhttp/http_test.go#L37

But maybe it's not picking up `$https_proxy`? @danderson, you remember?

**Comment by danderson** [comment]
We delegate almost all the proxy machinery to net/http. We pick the proxy with net/tshttpproxy, but on non-synology linux that just turns into http.ProxyFromEnvironment, which presumably handles https_proxy correctly?

IOW, yes, we should be handling https_proxy correctly, or at least as correctly as net/http generally.

**Comment by danderson** [comment]
@normanr what is the value of https_proxy that you're setting? And, is https_proxy being set on the tailscaled service? That's the one that's trying to dial out.

**Comment by normanr** [comment]
I'm setting `https_proxy="http://192.168.1.11:3129/"` in `/etc/default/tailscaled`, #4377 has more details about full configuration of my test network.

It looks like the request for https://controlplane.tailscale.com/machine/register is using `http_proxy`, is that expected? When it makes the connection to the proxy it's actually asking for http://controlplane.tailscale.com:80/ts2021 (which makes sense why it would use `http_proxy` then), but then squid is rejecting the connection:

tailscaled --> squid
```
POST http://controlplane.tailscale.com:80/ts2021 HTTP/1.1                  
Host: controlplane.tailscale.com:80
User-Agent: Go-http-client/1.1
Content-Length: 0
Connection: upgrade
Upgrade: tailscale-control-protocol
X-Tailscale-Handshake: $base64_encoded_data
```

squid --> tailscaled
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 27 May 2022 22:29:14 GMT
Content-Length: 22
X-Cache: MISS from $hostname
X-Cache-Lookup: MISS from $hostname:3129
Via: 1.1 $hostname (squid/5.5)
Connection: keep-alive

missing next protocol
```

**Comment by normanr** [comment]
I added `http_proxy="http://192.168.1.11:3129/"` to `/etc/default/tailscaled`, and
```
http_upgrade_request_protocols tailscale-control-protocol allow all
```
to my squid configuration (I already had an entry for `DERP`), and that fixed the connection for me.

It obviously doesn't fix anything for @pguinet or @lmariscal

**Comment by normanr** [comment]
ahh, reading [main/control/controlhttp/client.go](https://github.com/tailscale/tailscale/blob/main/control/controlhttp/client.go) it looks like port 80 and port 443 are raced. In my case the fallback to port 443 doesn't seem to have been working though (I was testing with 1.24.2 which is supposed to have the latest fixes). Note that: similar to #4452 the client can't just rely on `err` and needs to check `resp.StatusCode` as well, otherwise a connection that's rejected by the proxy won't be discarded correctly.

**Comment by JayWStapleton** [comment]
Looking at the pcap from @lmariscal 

We're seeing a RST on the connection from the client: 

`32	0.047133	<LAN IP>	18.193.143.177	TCP	54	44612 → 443 [RST] Seq=577 Win=0 Len=0`

**Comment by mihaip** [comment]
> Note that: similar to #4452 the client can't just rely on `err` and needs to check `resp.StatusCode` as well, otherwise a connection that's rejected by the proxy won't be discarded correctly.

@normanr: Unless I'm misunderstanding, there is an explicit check for non-101 responses: https://github.com/tailscale/tailscale/blob/a9f32656f53e4dbe7248852a616af75072f89000/control/controlhttp/client.go#L262-L264

**Comment by normanr** [comment]
yea, agreed. It's probably worth testing with 1.26 as it looks like the code has changed a bit more since 1.24.2.

**Comment by bradfitz** [comment]
@pguinet, @lmariscal, if Tailscale 1.26.0 doesn't work and you have Go 1.18 installed on your machine, can you run:

```
$ go run tailscale.com/cmd/tailscale@main debug ts2021
09:59:50.416170 Fetching keys from https://controlplane.tailscale.com/key?v=32 ...
09:59:50.893381 Dial("tcp", "18.193.255.254:80") ...
09:59:51.045692 Dial("tcp", "18.193.255.254:80") = 10.0.0.52:40052 / 18.193.255.254:80
09:59:51.197578 controlhttp.Dial = 0xc000342000, <nil>
09:59:51.197602 did noise handshake
09:59:51.197612 final underlying conn: 10.0.0.52:40052 / 18.193.255.254:80
```

That's a new debug command to do the connection + protocol upgrade to our control plane.

That'd confirm at least you're hitting the HTTP upgrade interception issue.

**Comment by lmariscal** [comment]
Just updated to Tailscale `1.26.0` and it solved the issue.
