### ISSUE TITLE
ssh not working through tailscale

### ISSUE THREAD

**Issue by plutocrat** [tailscale/tailscale#4594]
### What is the issue?

Server is running ssh on a non-standard port, 224, using ssh key. 
Client can connect via ssh on server public IP. 
Both client and server reported UP on tailscale status
tailscale ping tailscaleIP works. 
ping tailscaleip works
ssh -p 224 -i keyfile name@tailscaleIP times out. 
putting values into .ssh/config, same result. 

On the server tried restarting tailscale and ssh. Checked binding of sshd, which is on 0.0.0.0
No ACLs in place on Tailscale. 
Service monitor on tailscale tells me ssh connection is ssh -p 224 tailscaleIP 

I've run out of things to check. 

### Are there any recent changes that introduced the issue?

No, never tried to connect via ssh before. 

### OS

Linux

### OS version

Ubuntu 20 on both ends

**Comment by DentonGentry** [comment]
Please provide a "tailscale bugreport" shortly after attempting to ssh to port 224, so we have something to go on.

**Comment by plutocrat** [comment]
tailscale bugreport
BUG-d4bb25cb90963d8adb2ee1e676e2cdfb4529fab1049852404154f2ef0a8718bf-20220502054741Z-71d850eb388f58a2

nmap scan on server through the 100.x.x.x IP also not showing ports I'd expect to be open. 80, 443 etc.

**Comment by plutocrat** [comment]
Further info. I am able to ssh into another machine on my tailscale network. This is on the same LAN as the first one. 
LAN1 -> server no
LAN2 -> server no
LAN1 -> LAN2 yes. 
LAN2/LAN1 -> server public IP yes.

**Comment by DentonGentry** [comment]
Shortly before BUG-d4bb25cb90963d8adb2ee1e676e2cdfb4529fab1049852404154f2ef0a8718bf-20220502054741Z-71d850eb388f58a2 we see the attempt to SSH, which establishes a wireguard tunnel and allows the packet through ACLs, but then times out before getting a response from port 224:

```
2022-05-02 13:46:25.49040614 +0800 +0800: magicsock: disco: d:1967647e514932f9<-d:771f159c988145ab ([pW7cK], derp-3)  got call-me-maybe, 1 endpoints
2022-05-02 13:46:25.490657784 +0800 +0800: magicsock: disco: d:1967647e514932f9->d:771f159c988145ab ([pW7cK], 62.171.x.y:41641) sent ping tx=7f379aa1735d
2022-05-02 13:46:25.750990124 +0800 +0800: magicsock: disco: d:1967647e514932f9<-d:771f159c988145ab ([pW7cK], 62.171.x.y:41641)  got pong tx=7f379aa1735d latency=260ms pong.src=112.207.x.y:41641
2022-05-02 13:46:28.79741259 +0800 +0800: Accept: TCP{100.96.x.y:52632 > 100.84.x.y:224} 60 ok out
2022-05-02 13:46:33.798686639 +0800 +0800: open-conn-track: timeout opening (TCP 100.96.x.y:52632 => 100.84.x.y:224) to node [pW7cK]; online=yes, lastRecv=27s
```

On the destination machine we see the wireguard tunnel coming up and the packet to port 224 being allowed via ACLs:
```
2022-05-02 13:46:25.391202098 +0800 +0800: magicsock: disco: send, starting discovery for [LepHo] (d:1967647e514932f9)
2022-05-02 13:46:25.391436776 +0800 +0800: magicsock: disco: d:771f159c988145ab->d:1967647e514932f9 ([LepHo], derp-3) sent call-me-maybe
2022-05-02 13:46:25.391460726 +0800 +0800: magicsock: disco: d:771f159c988145ab->d:1967647e514932f9 ([LepHo], 10.11.x.y:41641) sent ping tx=f6814a3bcd18
2022-05-02 13:46:28.951217651 +0800 +0800: Accept: TCP{100.96.x.y:52632 > 100.84.x.y:224} 60 tcp ok
2022-05-02 13:46:36.259481084 +0800 +0800: magicsock: starting endpoint update (periodic)
```

Can you ssh to the LAN IP of that system on port 224?

**Comment by plutocrat** [comment]
No, the server is in a datacentre, not on my local LAN. 
I CAN ssh into another machine on my LAN, on both its LAN IP and tailscale IP. 
I CAN ssh into the datacentre server via its regular IP, but not its tailscale IP. From both machines on the local LAN. 
I CAN ssh from the datacentre server back to either machine on the LAN over tailscale IP. 

There are no ACLs set up in tailscale, as you suggest above. Server in DC is using iptables. Looks like iptables is bound to all interfaces. Have tried restarting both iptables and tailscale in different orders. 

Mysterious.

**Comment by plutocrat** [comment]
Did apt purge on servers tailscale, reinstalled from script. Re-registered. Got new IP. Still same situation.

**Comment by plutocrat** [comment]
My only suggestion at this point: is it possible that the fact that the server has IPv6 disabled, whereas the two LAN machines have IPv6 enabled have anything to do with it.

**Comment by plutocrat** [comment]
If it helps I can provide iptables output, via a private channel, and I turned on TRACE debugging for ssh connections to the tailscale IP. I can't see anything wrong so far, but maybe you're more used to looking at iptables rules than me.

**Comment by plutocrat** [comment]
Some good news. The culprit was an ipset blacklist applied on the server (in fact both of the affected servers). While I had checked the blacklist for any relevant IP addresses, although there were a few starting with 100.x.x.x there was no match for my tailscale IPs or even in the correct /24 or /16 subnets, so I discounted this as the cause. 
Of course, disabling the rule allowed me to connect. And writing a specific ALLOW rule for 100.0.0.0/8 allows me to connect with the blacklist enabled. 

I haven't solved the problem of why the blacklist is blocking an IP which doesn't exist on the blacklist yet, but it does at least seem to be unrelated to tailscale. 

Is there a list of possible tailscale IPs available? Or can I assume that the IP assigned to each client will never change, and can just be added to an allow list. [Or, if it does change, what are the circumstances under which it might?]

**Comment by DentonGentry** [comment]
Once assigned, the 100.64.0.0/10 IP address assigned to a node will not change.

If the node loses its state (such as having its disk wiped), or is deliberately removed from https://login.tailscale.com/admin/machines, then it will get a new IP address when it joins again.

I'll point out that this is what https://login.tailscale.com/admin/acls are for, to control access based on who the User is or what Tag has been applied and not the specific numeric IP address.

**Comment by plutocrat** [comment]
Useful information. Have now noted the distinction between IP address and ACL. 

I think, case closed on this one. Thanks for your forebearance.

**Comment by luongdangvp2000** [comment]
I can't use SSH after upgrade, my bugreport: 
BUG-956f0707560dc1ac7e59a9238db3f862609a11801bc56c817eb15bd13c161399-20220820085312Z-1a238db51433f008

Can someone help me??

**Comment by luongdangvp2000** [comment]
I still see my machine with `tailscale status`, but when I use SSH `ssh myuser@mymachine`, it show "ssh: Could not resolve hostname ailab01: Temporary failure in name resolution"

**Comment by bradfitz** [comment]
Please open new bugs for new issues rather than repurposing old, tangentially related ones.
