### ISSUE TITLE
Windows Connection Problems

### ISSUE THREAD

**Issue by Serrvosky** [tailscale/tailscale#46]
Hello guys,

I'm trying to deploy Tailscale on Windows, but at this moment I have three machines (machine 1 with linux, machine 2 and 3 with windows), and I can't have connection from/to machine 3.

I'm debuging with ping, machine 2 and 3 have the same ICMP Firewall Rule:
```
Rule Name:                            Allow ICMP
----------------------------------------------------------------------
Enabled:                              Yes
Direction:                            In
Profiles:                             Domain,Private,Public
Grouping:
LocalIP:                              Any
RemoteIP:                             Any
Protocol:                             ICMPv4
                                      Type    Code
                                      Any     Any
Edge traversal:                       No
Action:                               Allow
Ok.
```

but machine 3 it' not working.

How can I debug it? No ping output, no traceroute, no tcpdump output....

In machine 3 I can only ping 100.101.102.103. 
This is my route table on machine 3:
```
administrator@machine3 C:\Users\administrator> route print -4
...
machine2ip           255.255.255.255   machine3ip   machine3ip      5
100.101.102.103  255.255.255.255   machine3ip   machine3ip      5
machine1ip           255.255.255.255   machine3ip   machine3ip      5
...
```

There are only one difference between them. Local network is different. Machine 1 and 2 are in the same local network, and machine 3 are in another, but I this that's not the problem...

Any suggestion?

**Comment by bradfitz** [comment]
Can you email more details to support@tailscale.com? Then you don't have to redact IPs or other details. (Not that it should matter anyway, as nobody else can access those IPs)

**Comment by Serrvosky** [comment]
Ok, I will contact you by there.

**Comment by JPUnD** [comment]
How did you fix this issue? I want something dead simple to send to my friends, and right now i have to ask them to disable their firewall in order to play LAN games with them.
