### ISSUE TITLE
FR: tagged devices & auth via localapi whois

### ISSUE THREAD

**Issue by icing** [tailscale/tailscale#4605]
### What is the issue?

Similar to `nginx-auth` I have written an [authentication/authorization module](https://github.com/icing/mod_authnz_tailscale) for Apache httpd.

When validating users, e.g. extracting the "UserInfo"/"LoginName" from a whois JSON response, this works fine for a default tailscape configuration. But as soon as one `tags` a machine, the LoginName is reported as `tagged-devices`.

I think allowing access to "users" for "tagged-devices" would be a surprise to many people.

There are several possible ways to address this, but those depend on tailscale's view on it. I am asking for guidance here.

Possible ways to address this:

* Keep a list of non-user login names in the auth code. Fragile, not future-change proof.
* Only accept LoginName as user if it contains an `@`
* add a field in the whois JSON indicating that this user should be treated as a human user

### Steps to reproduce

Add a tag to a machine and inspect the whois?addr=n.n.n.n:port response from the local tailscale daemon. It looks similar to this:

```
	"UserProfile": {
		"ID": 30504053928343272,
		"LoginName": "tagged-devices",
		"DisplayName": "Tagged Devices",
		"ProfilePicURL": "",
		"Roles": []
	}
```

### Are there any recent changes that introduced the issue?

-

### OS

Linux

### OS version

Debian sid

### Tailscale version

Tailscale-Version: 1.24.0-t82b460255-g100961435

**Comment by DentonGentry** [comment]
I imagine we should make the `tailscale status --json` clearly indicate that the userid is for tags, not an SSO user.

**Comment by DentonGentry** [comment]
I think this will also be fixed by https://github.com/tailscale/tailscale/pull/6112, making the tags available in the output of `tailscale status --json`.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/6112
