### ISSUE TITLE
problem with HTTPS with Nginx Proxy Manager

### ISSUE THREAD

**Issue by hvddrift** [tailscale/tailscale#4612]
### What is the issue?

I have tailscale setup so I can access most of my docker containers without opening a port on my router. But then there is Bitwarden.

I have been able to generate within Tailscale a SLL certificate and been able to configure HTTPS.

When I go to the "https://machine-name.domain-alias.ts.net/" I get a

"This site can’t be reached" error

But with HTTP it will resolve correctly.

My end goal is to point the https://machine-name.domain-alias.ts.net/ to my local bitwarden instance and have it pass the HTTPS check.

Any help would be appreciated.

### Steps to reproduce

Enter in "https://machine-name.domain-alias.ts.net/" (With my details) and I get 
This site can’t be reached

But I enter "http://machine-name.domain-alias.ts.net/" it will work. But, the site is deemed Not secure.

### OS

Linux

### OS version

Unraid

### Tailscale version

1.24.2

### Bug report

BUG-5705b5b9019536cf8d0524ff8c187f6f7f27692a5d48ff76967a3850ecb145c3-20220505012733Z-5d0c420fab191bbf

**Comment by bradfitz** [comment]
Are you running an HTTPS server? Which? How did you configure it to use your Tailscale TLS cert? You used `tailscale cert` to get it successfully?

**Comment by hvddrift** [comment]
I have Nginx Proxy Manager, but from what you have asked I assume that will not be enough...

**Comment by hvddrift** [comment]
> 

And yes, I did  `tailscale cert` and it produced both a Cert and a Key. I have them both in Ngix as my Custom SSL certificate.

**Comment by bradfitz** [comment]
I'm not familiar with Nginx Proxy Manager. Can you share your config?

cc @Xe who might know.

**Comment by hvddrift** [comment]
FYI.. I am not committed to Nginx. I only use it (and it works) to point a duckDNS url to my local bitwarden instance. But it is the only port I have open on my router. I ultimately would like close the port and access bitwarden via tailscale, but it requires an HTTPS connection. So, (ignore my lack of understanding) I am looking to somehow have a local https.

For what its worth, here are my settings. They are (other than the ssl, which I selected as custom and pointed to the key and cert that tailscale created) identical to the duckdns settings. 
![chrome_uu6zlYSvgS](https://user-images.githubusercontent.com/972926/167036649-8707cf83-313e-485a-b8c2-8ca479ce803c.png)
![chrome_9OkAdeJXE0](https://user-images.githubusercontent.com/972926/167036660-ae8a7894-9cc9-44ca-ae8e-ff58510a7bdf.png)

**Comment by Xe** [comment]
I am off for the rest of the week, but I can take a look on Monday.

**Comment by DentonGentry** [comment]
At this point I think issue is in the NGINX config https://github.com/tailscale/tailscale/issues/4612#issuecomment-1296422435
Please reopen if there is more to be done within Tailscale.
