### ISSUE TITLE
MacOS Update appears to be broken

### ISSUE THREAD

**Issue by jdf** [tailscale/tailscale#4618]
### What is the issue?

<img width="516" alt="image" src="https://user-images.githubusercontent.com/55948/166982600-e5744499-fcae-4b84-a5ee-2de629d45a80.png">

### OS

macOS

### Bug report

BUG-d5d60215777045a1eb8577216bf10898d5509d75d97519298ac0fd60a5b8a423-20220505174923Z-8ab2734680534681

**Comment by bradfitz** [comment]
35% of Mac users have already updated to 1.24.2 in the App Store and have successfully connected to the control plane with it.

Maybe download got corrupted? Try again?

**Comment by jdf** [comment]
Yeah, I tried a few times. Happy to provide logs if anyone knows where to look.

**Comment by jdf** [comment]
Meh, I tried a few times more while trying to find relevant logs, and it worked after a few.

**Comment by DentonGentry** [comment]
Looking for it collapsed the bug's wave function and fortunately it settled into the working eigenstate.
