### ISSUE TITLE
FR: Add to "tailscale status --json" if a client is using an exit node, and if so.

### ISSUE THREAD

**Issue by baandab** [tailscale/tailscale#4619]
### What are you trying to do?

I am writing a script to ensure that my clients are using an exit mode.   When I parse "tailscale status --json", I cannot tell from the .Self portion of the JSON if the client is using an exit mode.  

```
    "Online": true,
    "KeepAlive": false,
    "ExitNode": false,
    "ExitNodeOption": false,
    "Active": false,
```

### How should we solve this?

Add to the "tailscale status --json" two new parameters to the .Self:

ExitNodeUsage:  true or false
ExitNodeHostaname:  <name of host>

### What is the impact of not solving this?

Currently just forcing the use of the exit node, but would prefer to be more surgical and only force it when it is not on:

`Tailscale up --accept-routes --exit-node=100.XXX.XX.XX --exit-node-allow-lan-access=true --reset`

**Comment by nyghtowl** [comment]
PR #4761 Addresses this issue by including ExitNodeStatus in the json output when an exit node is enabled in the net and set for usage.
