### ISSUE TITLE
FR: official unraid plugin/docker

### ISSUE THREAD

**Issue by jerydfans** [tailscale/tailscale#4624]
### What are you trying to do?

I would like an official unraid plugin (or docker) build. I'm currently relying on community built tailscale docker - which is out of date and does not look like it is updating.

### How should we solve this?

Build / publish an unraid plugin (or docker) to the unraid community.

### What is the impact of not solving this?

People are stuck using unofficial and out of date software

### Anything else?

please and thank you!

**Comment by jeryd** [comment]
Someone made an unraid / community app. Thanks!

**Comment by jeryd** [comment]
I dont know why I closed this. I really like an official plugin for unraid.

**Comment by bradfitz** [comment]
> I'm currently relying on community built tailscale docker - which is out of date and does not look like it is updating.

https://hub.docker.com/r/tailscale/tailscale says "By [tailscale](https://hub.docker.com/u/tailscale) • Updated 3 days ago"

<img width="751" alt="Screen Shot 2022-09-11 at 8 53 12 AM" src="https://user-images.githubusercontent.com/2621/189537021-138994ac-87f3-4d41-bc26-7ccf42ad4417.png">

What does "official" mean in the context of Unraid?

**Comment by bradfitz** [comment]
Oh, is it https://github.com/deasmi/unraid-tailscale that you're using?

**Comment by bradfitz** [comment]
It's surprisingly hard to find documentation on how to write Unraid plugins/add-ons/containers/Docker images.

https://wiki.unraid.net/Manual/Applications#Community_Applications_.28CA.29 is something, but doesn't have much detail.

**Comment by jeryd** [comment]
I have no problem launching my own container, but I can't find instructions on what flags do what. Every time I launch one I get the ephemeral flag to show up, which is not my goal.

For reference, I am used to seeing something like linuxserver containers - which has enough details and options for me to launch my own stuff (For example https://github.com/linuxserver/docker-wireguard - look at all the Parameters to choose from).

**Comment by dkaser** [comment]
FYI -- I've since developed a community plugin that installs Tailscale at the OS level instead of running in Docker: https://github.com/dkaser/unraid-tailscale

**Comment by DentonGentry** [comment]
[Tailscale 1.42.0 added specific support for Unraid](https://github.com/tailscale/tailscale/releases/tag/v1.42.0) in Taildrop and the web UI, via pull requests submitted by @dkaser 👍 
- https://github.com/tailscale/tailscale/pull/8062
- https://github.com/tailscale/tailscale/pull/8029

At this point I think the community plugin in https://github.com/dkaser/unraid-tailscale addresses this feature request.
