### ISSUE TITLE
FR: Support nftables for new OpenWrt coming release 22.03

### ISSUE THREAD

**Issue by csrutil** [tailscale/tailscale#4638]
### What are you trying to do?

Thank you for all the hard work!

There is a [new release ](https://github.com/openwrt/openwrt/issues/9248)from OpenWrt that will change iptables to nftables. And tailscale does not support nftables right now(but we can use userspace implementation 

```bash
root@main:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.0-rc1'
DISTRIB_REVISION='r19302-df622768da'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 22.03.0-rc1 r19302-df622768da'
DISTRIB_TAINTS=''

root@main:~# uname -a
Linux main 5.10.111 #0 SMP Wed Apr 20 10:37:37 2022 x86_64 GNU/Linux
```

```bash
root@main:~# tailscaled --version
1.24.2
  tailscale commit: 9d6867fb0ab30a33cbdfc8e583f5d39169dbb2e6
  other commit: 2d0f7ddc35aa4149e67e27d11ea317669cccdd94
  go version: go1.18.1-ts710a0d8610

root@main:~# tailscaled
createEngine: creating router: exec: "iptables": executable file not found in $PATH
```

### How should we solve this?

Do some refactor on https://github.com/tailscale/tailscale/blob/main/wgengine/router/router_linux.go for supporting `nft`.

### What is the impact of not solving this?

There are a lot linux distros are changing iptables to nftables, it will impact a lot of users in the future.

### Anything else?

No, thank you!

**Comment by bradfitz** [comment]
This is basically a dup of #391.

We don't plan to shell out to the `nft` binary; instead, we plan to just do the netlink to the kernel to program nftables when safe.

Closing this one as a dup but will leave a comment there.

/cc @raggi

**Comment by csrutil** [comment]
@bradfitz Thank you!
