### ISSUE TITLE
Machine identity conflict after Time Machine backup restore in macOS

### ISSUE THREAD

**Issue by jiaminghe** [tailscale/tailscale#4641]
### What is the issue?

After setting up a new macOS device (Mac mini) and restore the Time Machine backup from a different device (MacBook Pro), two devices would appears to be the same to tailscale, the IP assigned are the same and the hostname will change based on the device hostname of last successful connection.

At first, the admin console will show "duplicated key" error under the device IP, after removing the said device and uninstall/reinstall tailscale, the problem persists. The newly assigned IP address will be shared by both devices.

### Steps to reproduce

1. Setup tailscale on one Mac (mac1), obtain an IP address.
2. Complete Time Machine backup of (mac1)
3. Setup a new Mac (mac2), in the migration assistant screen, select "From a Mac, Time Machine backup or startup disk", select mac1 as the source of the migration.
4. After setting up (mac2), reauthenticate tailscale, in the admin console, the IP address of mac1 will show "duplicate key" error.
5. Delete the device in the tailscale admin console, uninstall tailscale from both devices, reinstall tailscale.
6. Setup tailscale on Mac1, obtain an IP address, the hostname will be Mac1
7. Setup tailscale on Mac2, the IP address will appears to be the same as IP address in step 6, the hostname is changed to Mac2.

### OS

macOS

### OS version

macOS Monterey 12.3.1 (21E258)

### Tailscale version

1.24.2

**Comment by DentonGentry** [comment]
The various keys for Tailscale are stored in the keychain, and the new device duplicated the keychain. If you plan to continue using both devices, you can clear the keys on one of them. Tailscale.app will create new keys the next time it starts up.

1. On one of the Macs, the one you wish to get a different IP address, quit Tailscale using the menubar icon and then run `/Applications/Utilities/Keychain Access`
1. Search for "tailscale". There should be at least 3: tailscale-logdata, tailscale-machinekey, and tailscale-preferences. Depending on how long ago the original Mac started using Tailscale, there may be a fourth.
1. Delete all three (or four) keys
1. Start `/Applications/Tailscale` again

**Comment by jiaminghe** [comment]
Thank you so much for your prompted response. This indeed fixed this issue. I should have thought of keychain items first and I am bit embarrassed :)
