### ISSUE TITLE
Login with Synology DS does not work anymore

### ISSUE THREAD

**Issue by Ciruman** [tailscale/tailscale#4648]
### What is the issue?

I have installed Tailscale in Synology for months and it was working fine. At some point, I have to re-login all my devices, and since then, the Tailscale login does not work. 

### Steps to reproduce

Open in Synology the Tailscale application and open the Tailscale page with the "Log in" button
I press to open the Tailscale login

What happens:
The "Log in" button does nothing.

What I expect:
I expect to get a Tailscale login dialog( as it does here: https://youtu.be/u2Qp1BM8Qi8?t=62) and come back to Synology logged in.

### OS version

DSM 7

### Tailscale version

1.16.2-2013

### Bug report

BUG-0b59bc625a5f80332ca83ed2900ac7b31c19334fd4181803dc3aa6ce93b6c607-20220509183044Z-a8c8cca05fc40829

**Comment by bEMmTEWDz0elpu1w** [comment]
I have the same issue.

**Comment by markusweimer** [comment]
Confirmed for me too.

**Comment by markusweimer** [comment]
Update: I enabled SSH on my NAS, logged in and executed `sudo tailscale up`. That sent me to a login page and my NAS is now connected to the Tailscale network.

**Comment by Ciruman** [comment]
@markusweimer, thank you very much. It also worked for me.

**Comment by ctaque** [comment]
Also broken for me, DSM 6

**Comment by josharian** [comment]
I just hit the exact same issue. I was using DSM 6, upgraded to 7 in the hopes that it'd work, same result.

The SSH workaround above works. For those who want to log in w/o sudo, you can run `tailscale status`, which will print out an authorization URL that you can use.

**Comment by waltz** [comment]
@josharian Using `tailscale status` worked perfectly for me, thanks for that!

NB, I didn't see anything in the Chrome network inspector after clicking the button. Kinda funky, but maybe that helps debug this.

**Comment by DentonGentry** [comment]
Likely fixed by https://github.com/tailscale/tailscale/pull/5395 in Tailscale 1.30.0 and later.
If you still have a problem logging in to a synology device: please open a new bug. This one will be conflated with symptoms from https://github.com/tailscale/tailscale/pull/5395

**Comment by Tetra84** [comment]
> I just hit the exact same issue. I was using DSM 6, upgraded to 7 in the hopes that it'd work, same result.
> 
> The SSH workaround above works. For those who want to log in w/o sudo, you can run `tailscale status`, which will print out an authorization URL that you can use.

I'm sort of new with this, can you tell me where/how I enter/run 'tailscale status' to get that authorization url?

**Comment by DentonGentry** [comment]
@Tetra84 Please open a new issue and describe the problem you are having. If Tailscale ever worked on the device, please include its IP address (like 100.x.y.z) so we can try to find any telemetry it has sent.

Synology should use the WebUI, by clicking on the icon in the Package Center. It shouldn't be necessary to get a shell and use `tailscale status`

<img width="572" alt="Screenshot 2023-06-17 at 6 23 53 AM" src="https://github.com/tailscale/tailscale/assets/1140756/36c0e6f0-330e-4525-bf1c-5d540bcb075c">

**Comment by Tetra84** [comment]
I got it figured out, thanks. I had to open an SSH connection to my NAS but entering 'tailscale status' gave me the login URL I was looking for, and now I'm back to good.

**Comment by Heliosmaster** [comment]
> I had originally tried to log in that way through Synology's UI, but when it opened a new window and I got to the login screen the 'log in' button didn't do anything for me. But I got it figured out, thanks. I did have to open an SSH connection to my NAS but entering 'tailscale status' gave me the login URL I was looking for, and now I'm back to good.

@Tetra84  thanks! I solved the same issue in the same way
