### ISSUE TITLE
ACLs allow for invalid rule to save without error

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4649]
### What is the issue?

You can omit a port when specifying a protocol, but it does not allow the traffic in the tailnet. 

### Steps to reproduce

` [{"Action": "accept", "src": ["*"], "proto": "icmp", "dst": ["crunchy"],},], `

This rule will save, but does not allow ICMP traffic 

` [{"Action": "accept", "src": ["*"], "proto": "icmp", "dst": ["crunchy:*"],},], `
 
 This rule does work as expected.

**Comment by DentonGentry** [comment]
Somewhere along the way, we fixed this.

<img width="732" alt="Screenshot 2023-05-18 at 11 58 19 PM" src="https://github.com/tailscale/tailscale/assets/1140756/92bdd69d-6bb7-48a7-9f09-69cf44a60bad">
