### ISSUE TITLE
FreeBSD jail not working due to lack of TUN device

### ISSUE THREAD

**Issue by Viper780** [tailscale/tailscale#4653]
### What is the issue?

After installation tailscale the service tailscaled doesn't start

Same problem is decribed in https://github.com/tailscale/tailscale/issues/4101

can't reopen the Issue so I've created this one

### Steps to reproduce

install tailscale

start the deamon with `service tailscaled start`

see if it ist runnint with `tailscale status`

### OS

Other

### OS version

FreeBSD 12.3 p5 in a Jail

### Tailscale version

1.24.2

**Comment by danderson** [comment]
Your issue seems unrelated to that bug. From the logs you shared over there:

`createEngine: tstun.New("tailscale0"): open /dev/tun: no such file or directory`

Your system seems to be missing the tuntap device driver, so we can't create the VPN's network interface.

**Comment by DentonGentry** [comment]
FreeBSD jails can work in `--tun=userspace-networking` mode, and I think that is the main issue here. Make sure to use 1.22 or later, as https://github.com/tailscale/tailscale/issues/2858 also impacts FreeBSD jails.

**Comment by DentonGentry** [comment]
I think needing `--tun=userspace-networking` was the main issue here.
