### ISSUE TITLE
A Sendgrid URL fails to resolve when using Tailscale

### ISSUE THREAD

**Issue by mettler** [tailscale/tailscale#4656]
### What is the issue?

A marketing redirect URL fails to load. I'm not sure if this is a problem with my machine, or with Tailscale, but I can reproduce consistently. See below for more details. 

### Steps to reproduce

1. Connect to Tailscale 
2. Load https://u23036105.ct.sendgrid.net/ls/click: Chrome refuses to connect
3. Disconnect from Tailscale
4. Load https://u23036105.ct.sendgrid.net/ls/click: Chrome connects successfully (page displays a "Wrong Link" message)

### Are there any recent changes that introduced the issue?

Not sure. 

### OS

macOS

### OS version

12.3

### Tailscale version

1.24.2

**Comment by DentonGentry** [comment]
Are you using an exit node? (just to know whether the traffic to sendgrid.com was likely to be going over the tailnet at all)

Have you enabled IP Access Management in your sendgrid account? https://sendgrid.com/blog/introducing-ip-access-management/

**Comment by mettler** [comment]
I am not using an exit node. And IP access management is not enabled (AFAIK I don't have a sendgrid account. My user journey is clicking on an email link in gmail, and getting redirected through sendgrid on the way to my final destination). I've noticed this behavior happens as well with other analytics/marketing URLs. Will try to locate and add them to the issue here for further troubleshooting.

**Comment by bradfitz** [comment]
something something MTU?

**Comment by mettler** [comment]
Other examples, hopefully reproducible for you, where the page fails to resolve when connected but seems to work fine when disconnected: 
- https://nate-the-house-whisperer.ck.page/1786fbdf5a
- http://click.alchemistaccelerator.com/ls/click?upn=[removed] (sendgrid again?)
If these examples are useful, I can add more.

**Comment by DentonGentry** [comment]
Both of these links work for me, with Tailscale running.
- https://nate-the-house-whisperer.ck.page/1786fbdf5a
- [http://click.alchemistaccelerator.com/ls/click?upn=[removed]](http://click.alchemistaccelerator.com/ls/click?upn=%5Bremoved%5D)

If you can click on one of the links, see it fail, and generate a bugreport, we can look into it.

If you're not using an exit node, I don't see why Tailscale is getting involved in fetching from public websites. So that would be the first thing we'd want to look into.

**Comment by mettler** [comment]
Glad it seems to be an L1 :)

Reproduced: 
1. Connected to Tailscale, verified no exit node. 
2. Clicked on https://nate-the-house-whisperer.ck.page/1786fbdf5a & http://click.alchemistaccelerator.com/ls/click?upn=[removed]; both failed to load. 
3. Generated bugreport: BUG-c73863b5a7459e505976b84fd7a1f6d9942afd059fcbb3efaf6a5f5cfa6afdc0-20220513173238Z-a2c868c033470a3c

Ooh, a clue: failure appears to be account-dependent. 
* My mike@righthandgreen.com corp Tailscale account says it's not running an exit node (according to the menu bar: Exit Node -> No exit nodes available), but fails to load. 
* My mettler@gmail.com Tailscale account also says it's not running an exit node, but loads both URLs just fine! 
Error on my part somehow?

**Comment by DentonGentry** [comment]
One thing I note is that the corp account has DNS servers configured but only IPv4 addresses. Google DNS does vary what it returns by default based on whether it is contacted using IPv4 or IPv6, it makes the assumption that an IPv4 query is somewhat more likely to have broken IPv6.

The GMail account has no DNS servers configured via Tailscale, and uses whatever it is getting via DHCP.

It may be that while connected to the GMail tailnet you're getting DNS responses back which end up using IPv6, and corp does not. That would imply difficulty reaching those sites via IPv4.

**Comment by DentonGentry** [comment]
I think this is likely related to the DNS configurations between the two tailnets, one where there are IPv6 nameservers present and the other not.

Barring further comment, we'll expect to close this during the next regular bug scrub.
