### ISSUE TITLE
openwrt package needs iptables dep

### ISSUE THREAD

**Issue by dave-andersen** [tailscale/tailscale#4665]
### What is the issue?

The openwrt package: https://openwrt.org/packages/pkgdata/tailscaled

Does not have a dependency on iptables. Not all openwrt installs have it installed already, so just installing the package generates an error when launching tailscaled until you install iptables manually.

### OS

Other

### OS version

OpenWRT 21.02

### Tailscale version

1.18.2-date.20211101

**Comment by DentonGentry** [comment]
As we don't maintain the openwrt repo, I'll focus on what Tailscale might do in the longer term.
I believe this would be handled via https://github.com/tailscale/tailscale/issues/391 to not need the iptables binary.
Duplicate of https://github.com/tailscale/tailscale/issues/391
