### ISSUE TITLE
macOS: Login button doesn't do anything

### ISSUE THREAD

**Issue by Mehuge** [tailscale/tailscale#4667]
### What is the issue?

New install, from App Store.
After clicking Get Started it prompts to log in.

Clicking Sign in to your network button does nothing. Nor does the Login... button from the menu bar icon.

There is a Tailscale Tunnel in Network preferences, that is showing as connected.
The Account Name: field is blank (in case thats relevant)

### Steps to reproduce

1. Install client
(I was prompted to allow VPN which I allowed)
2. Click Get Started
3. Click Sign in to your network

https://user-images.githubusercontent.com/99895/168279065-8b78ecba-03ec-4195-9dcd-8985e3ec7afd.mov

### Are there any recent changes that introduced the issue?

Brand new installation.

### OS

macOS

### OS version

12.0.1

### Tailscale version

1.24.2

### Bug report

BUG-ba0a64402bda08593f3bbe78190b253c5fdfcfd099bb257a893cc3aa6e0a35da-20220513115703Z-31941bf3d9da845b

**Comment by DentonGentry** [comment]
The most common cause of behavior such as this is an incompatible system extension like Avast, Bitdefender, Adguard, or Crowdstrike Falcon. Do you know of any such software installed on the Mac?
​
​Does "systemextensionsctl list" show other extensions present?
​
​Descriptions of a number of such conflicts and some solutions of how to resolve them are in https://github.com/tailscale/tailscale/issues/3192

**Comment by Mehuge** [comment]
I do have Avast installed. I disabled the web shield now I can log in. Will close this and check other ticket.
