### ISSUE TITLE
Possibility to regain to server access to locked down server after upgrade

### ISSUE THREAD

**Issue by olbrew** [tailscale/tailscale#4668]
### What is the issue?

Hi Tailscale team,
I love using your product and used it successfully on a local server until I upgraded the server's Ubuntu operating system which caused me to lose access. After locking down the server with UFW according to [your guide](https://tailscale.com/kb/1077/secure-server-ubuntu-18-04/) everything worked perfectly until I recently upgraded to the newest Ubuntu Server LTS 22.04. In hindsight I should have disabled the firewall before starting the upgrade in case something went wrong with the Tailscale service. Unfortunately I didn't think of it at the time and am afraid that the service is not starting properly which causes me to be unable to access it anymore over SSH. It's difficult to find with network scanning tools such as Nmap as well since it doesn't seem to use the old IPv4 (in DHCP) address anymore.
Is there any way you know how I could regain access except for wiping the whole drive and starting over?
Thank you.

### Steps to reproduce

1. Install and setup Tailscale on Ubuntu server machine
2. Lock down server according with UFW to only allow Tailscale access following [article steps](https://tailscale.com/kb/1077/secure-server-ubuntu-18-04/)
3. Successfully access server through SSH over Tailscale
4. Upgrade Ubuntu server to 22.04 Jammy Jellyfish
5. Try to access server through SSH over Tailscale after upgrade which doesn't work anymore.

### Are there any recent changes that introduced the issue?

Upgrading server to newest Ubuntu LTS version caused me to be unable to access the server anymore after closing it down for other connections with UFW.

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.22.2

**Comment by DentonGentry** [comment]
We'll handle this via support@tailscale.com.

**Comment by doesnotexist** [comment]
It appears that on Ubuntu 22.04, if you follow the guide at https://tailscale.com/kb/1077/secure-server-ubuntu-18-04/ then I believe you can be locked out from your host after a reboot.  Which seems to happen after unattended-upgrades updates nftables packages.  Something about these packages getting updated breaks the previously configured ufw rules. In my case, despite allowing port 22 on all interfaces (not just tailscale0) after this upgrade and a reboot the host rejected all connections to port 22.   To test, I restored to a previous "known to work" snapshot and then did the apt update and reboot myself resulting in the locked out state.

```
$sudo apt list --upgradeable
Listing... Done
libnftables1/jammy-updates 1.0.2-1ubuntu3 amd64 [upgradable from: 1.0.2-1ubuntu2]
nftables/jammy-updates 1.0.2-1ubuntu3 amd64 [upgradable from: 1.0.2-1ubuntu2]
```

My current solution has been to remove the libnftables and nftables packages.
