### ISSUE TITLE
hello.ts.net is missing from my tailnet

### ISSUE THREAD

**Issue by normanr** [tailscale/tailscale#4669]
### What is the issue?

Noticed as part of #1233, but I'm splitting it out to it's own bug.

https://login.tailscale.com/admin/machines shows `hello`:

| MACHINE | IP | OS | LAST SEEN |    |
| ------- | -- | -- | --------- | --- |
| hello (?) |  100.101.102.103 | Linux | Connected | ... |
| services@tailscale.com |  |  1.18.2 | |
| [External] [No expiry] |

but I can not access it. It is not in the output of `tailscale status` of any of the nodes in my tailnet, nor is it in the kernel routing table for tailscale (`ip route ls table 52). If I try adding it manually and using `tailscale ping`, `ping` and `socat` to connect, then I see:
```
ping(100.101.102.103): no matching peer
Accept: ICMPv4{100.93.62.55:0 > 100.101.102.103:0} 84 ok out
Accept: ICMPv4{100.93.62.55:0 > 100.101.102.103:0} 84 ok out
Accept: ICMPv4{100.93.62.55:0 > 100.101.102.103:0} 84 ok out
Accept: TCP{100.93.62.55:60416 > 100.101.102.103:80} 60 ok out
open-conn-track: timeout opening (TCP 100.93.62.55:60416 => 100.101.102.103:80); no associated peer node
```

I have tried removing it, and re-adding it via https://login.tailscale.com/admin/invite/hello.ts.net, but that doesn't seem to change anything.

### OS

Linux

### OS version

Debian testing (bookworm), Raspberry Pi with Debian 11 (bullseye)

### Tailscale version

1.24.2

### Bug report

BUG-54838b594ceee0c96e93a9af1141b6ad0d8ac169018ee32176f2c9533b5be982-20220513174315Z-f1d276883ef9df8f

**Comment by normanr** [comment]
I also tried `systemctl restart tailscaled.service` and `tailscale down && tailscale up` (from #2713), but didn't make a difference.

**Comment by bradfitz** [comment]
This was a regression from a recent control plane optimization. @maisem just fixed it but we probably won't deploy the fix this weekend.

**Comment by seh** [comment]
It's the same for me. I've never been able to reach the "hello" service via its _100.101.102.103_ IP address, whether by _ping_, HTTP, or HTTPS. It appears as a known service, but I can't get macOS to find a route reach it.

**Comment by normanr** [comment]
It seems to be working again. https://hello.ts.net/ shows a "You're connected over Tailscale!" message.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/corp/commit/7beed2a29683110a58a9feba593a1c5845bb0908 (which you can't see, sorry)

**Comment by bradfitz** [comment]
I think you mean https://github.com/tailscale/corp/commit/4f8bd4e4a1ade049ef633e89e384fcb406ae7921 (which is actually on a branch)
