### ISSUE TITLE
Windows 11 Build 22621 and Taildrop

### ISSUE THREAD

**Issue by d5aqoep** [tailscale/tailscale#4679]
### What is the issue?

Taildrop stops working on Windows 11 Build 22621

### Steps to reproduce

In the latest Windows Build 22621 rumored to be 22H2 RTM, Tailscale install sets itself as Public under Network. So this machine cannot receive files via Taildrop. However, if we change Tailscale settings from Windows Firewall and set to Public, the machine starts receiving Taidrop files sent via other machines. However, after reboot, Tailscale again sets itself as Public and Taildrop stops working.

In short there is a mismatch on Tailscale network set to Public, but in Firewall, its set to Private.
The issue can be fixed by either setting Tailscale network to Private by default

Running this command in elevated powershell fixes the issue and Taildrop starts working consistently across all devices.
`Set-NetConnectionProfile -Name "Tailscale" -NetworkCategory Private`

### Are there any recent changes that introduced the issue?

Issue is present in latest Windows 22H2 build 22621

### OS

Windows

### OS version

Windows 11 build 22621

### Tailscale version

1.24.2

### Bug report

BUG-f3274b9192e8855016ffac69c8f086a62f20a1ce6b9b98959e438d76a99dbbb3-20220515074133Z-da122a0f8972a2e9

**Comment by dblohm7** [comment]
Not sure how that's being changed right now, but AFAICT for future reference, this is the API for explicitly changing that stuff:
https://docs.microsoft.com/en-us/windows/win32/api/mbnapi/nn-mbnapi-imbnconnectionprofilemanager

**Comment by kourbou** [comment]
This seems to be an issue with all incoming connections on Windows, not just Taildrop. I also had a mismatch between the Tailscale adapter being set to "Public" and Windows Firewall only accepting incoming Tailscale connections on "Private" networks.

Switching the adapter to "Private" fixed SMB shares and RDP for me:
```powershell
Set-NetConnectionProfile -InterfaceAlias "Tailscale" -NetworkCategory Private
```
I'm running Windows 11 Pro 22H2 (build 22621.521) and Tailscale 1.30.2. Not sure when the issue appeared.

**Comment by DentonGentry** [comment]
With Windows 11 Build 22000 I'm able to receive Taildrop files. Something broke between 22000 and 22621.521, I guess.

**Comment by DentonGentry** [comment]
We have not managed to produce this, nor received other reports of the issue.

**Comment by DentonGentry** [comment]
If this is seen again, please reopen. We tried several times to reproduce.
