### ISSUE TITLE
tailscale down

### ISSUE THREAD

**Issue by matti** [tailscale/tailscale#4681]
### What is the issue?

login.tailscale.com down, etc

**Comment by caraar12345** [comment]
Seeing the same here - typical - I haven't had a use for Tailscale in months until right now 😂

**Comment by steenstra** [comment]
Yes, I was just telling someone how great it is and after installing it on the first machine we got this issue...

**Comment by bradfitz** [comment]
We're having a server issue at the moment. Working on it.

**Comment by caraar12345** [comment]
Cheers @bradfitz! Best of luck with getting it sorted 😊

**Comment by steenstra** [comment]
It is working again for me.

**Comment by caraar12345** [comment]
And me - authed and set up a new device on my tailnet 👍

**Comment by bradfitz** [comment]
Should be back now. We had a bad server deploy.

**Comment by deltamualpha** [comment]
Yep, working again for me now.

**Comment by matti** [comment]
works.
