### ISSUE TITLE
Does not work properly on windows server

### ISSUE THREAD

**Issue by MistyMoonR** [tailscale/tailscale#4682]
### What is the issue?

Installing Tailscale on win server 2019, clicking on log in is unresponsive, I'm stuck at this step. Normally, the browser is opened automatically and the account is verified. So I can't use it on win server. And having tested it on two computers with the same system, I can confirm that it is not my computer's problem.

![image](https://user-images.githubusercontent.com/33083971/168484809-f8843b91-4625-4653-b0f3-a3ef13bafd3e.png)

### Steps to reproduce

- Installation
- Right click on the icon
- log in

### OS

Windows

### OS version

Windows Server 2019 Datacenter

### Tailscale version

1.24.2

**Comment by caraar12345** [comment]
➡️ #4681 - there's an outage at the mo so `Log in...` won't work. Not just you (or Windows Server!) 😊

**Comment by bradfitz** [comment]
Yeah, dup of #4681. We had a bad server deploy. Try again?
