### ISSUE TITLE
Standalone Version of Tailscale for Mac OS (not App Store)

### ISSUE THREAD

**Issue by cegit55** [tailscale/tailscale#4687]
### What are you trying to do?

The documentation says there is a standalone (DMG/ZIP) version of Tailscale for Mac.
How can I get hold of a copy?
Many thanks.

### How should we solve this?

Please could you send me a link to download it?

**Comment by bradfitz** [comment]
Coming soon. It'll be at https://pkgs.tailscale.com/unstable/ first and then hopefully if all goes well we'll start building stable builds for the next stable build.
