### ISSUE TITLE
Problems with using OpenVPN and Tailscale

### ISSUE THREAD

**Issue by MistyMoonR** [tailscale/tailscale#4691]
### What is the issue?

Admittedly Tailscale has performed much better than OpenVPN in my tests (Speed) , but I can't completely abandon OpenVPN just yet. It will take some time to transition.  

I set up direct on the two sides of the network, without using relays. In other words OpenVPN and Tailscale are both interconnected on a peer-to-peer basis in my network structure. The latency is almost identical for both VPNs.

During my testing I found that Tailscale would sometimes use the OpenVPN line, which was rather confusing. If I cut off OpenVPN at this point, Tailscale will use the Internet to connect to each other, and it  will be much faster.

Tailscale seems to find the shortest path through the delay. The path that does not use the optimal solution correctly (Internet, not OpenVPN).

What can I do to make the two VPNs go their separate ways without changing the structure of the original network?

**Comment by DentonGentry** [comment]
Not actionable.
