### ISSUE TITLE
Github tailscale action is failing b/c github actions cannot curl from pkgs.tailscale.com

### ISSUE THREAD

**Issue by dave-andersen** [tailscale/tailscale#4699]
### What is the issue?

This command fails when run from a github workflow:

    curl "https://pkgs.tailscale.com/stable/tailscale_1.18.0_amd64.tgz" -o tailscale.tgz
    
But works properly when run from any other location I am able to try from (home + a GCP VM).

The connection to the IPv4 address/port 167.172.11.40:443 times out. The ipv6 address for pkgs.tailscale.com is not reachable (fails instantly but this is likely not the problem - it's the timing out ipv4 connection that's supposed to be working and that works from elsewhere).

I'm unable to determine if this is tailscale or github's fault or that of some routing provider somewhere else. Changing pkgs.tailscale.com to one of my own machines at GCP causes the command to work properly:

    Run curl "https://www.angio.net/tailscale_1.18.0_amd64.tgz" -o tailscale.tgz
    
But something, somewhere, is unhappy - maybe routing, maybe gh, maybe some kind of ddos protection gone wrong on ts's side?

**Comment by dave-andersen** [comment]
I should add - this workflow was working properly this morning (eastern time) and had been stable for months. This may simply be - probably is - some ephemeral breakage somewhere. But it's breaking me, so... :-)

**Comment by DentonGentry** [comment]
> The connection to the IPv4 address/port 167.172.11.40:443 times out.

It isn't globally down, our monitoring prober and my house (at least) are still able to reach it.

> The ipv6 address for pkgs.tailscale.com is not reachable

It does work from some locations, at least: https://geekflare.com/tools/tests/xc90wpd6x

and from California:
```
% ping6 2604:a880:2:d0::61c:d001
PING6(56=40+8+8 bytes) 2602:248:7b4a:ff60:c0f6:3d19:8f30:6b68 --> 2604:a880:2:d0::61c:d001
16 bytes from 2604:a880:2:d0::61c:d001, icmp_seq=0 hlim=53 time=12.084 ms
16 bytes from 2604:a880:2:d0::61c:d001, icmp_seq=1 hlim=53 time=9.543 ms
```

**Comment by dave-andersen** [comment]
Yeah, the curl command works properly from everywhere _else_ that I can test it...

> But works properly when run from any other location I am able to try from (home + a GCP VM).

Github is the only place the failure is occurring.

Github -> pkgs.tailscale.com : No
Github -> www.angio.net : Yes  (same file)
My house -> pkgs.tailscale.com: Yes
GCP -> pkgs.tailscale.com: Yes

**Comment by dave-andersen** [comment]
(This is a trivial test github worker that exercises the bug: https://github.com/brdg-ai/testworkflow/blob/main/.github/workflows/main.yml )

**Comment by dave-andersen** [comment]
Further digging makes this look like a likely GitHub issue: https://twitter.com/earthlingworks/status/1526639132067344385

So perhaps the only tailscale-related thing is to turn this into a feature request: Possibly some redundancy in the packages.tailscale.com server. :-)

**Comment by dave-andersen** [comment]
Clarifying briefly, it was actually a DigitalOcean problem: https://status.digitalocean.com/incidents/82xnb04903pf

With the same effect.
