### ISSUE TITLE
FR: First seen/connected field in admin UI

### ISSUE THREAD

**Issue by thawthorn** [tailscale/tailscale#4701]
### What are you trying to do?

I would like to know when a machine first connected. We have autonomous devices that send into the field and wait for them to connect, and then they are available for our use. Knowing when they first connect would be helpful on the device detail page. For example, we'd like to know "Oh wow, that box has been online for a week and we didn't notice." Right now we have to manually check and mentally keep track.

### How should we solve this?

Add an additional field to the device's page under the "Machine Details" section. 

### What is the impact of not solving this?

For large deployments it's helpful to know when a device first connected. This allows the user to understand how long a device has been part of the network. It helps us in our use case understand how new or old a device is. 

### Anything else?

It seems like this might be a field already captured in some way within a given customer's data and exposing it in the UI seems low-cost since it's a static value.

**Comment by morpig** [comment]
I was looking for this too and checked that they have the "created" field in the GET machine request on the dashboard page, but it's not displayed in the UI.

<img width="399" alt="Screen Shot 2022-05-18 at 15 52 23" src="https://user-images.githubusercontent.com/4915643/168999260-3de7ec5f-14e6-4a62-93bc-83aca79a5352.png">

Maybe team can add this field to the details page?

<img width="1164" alt="Screen Shot 2022-05-18 at 15 50 34" src="https://user-images.githubusercontent.com/4915643/168999081-3dbe6e85-b24d-4179-8559-4a62c7de6b08.png">
