### ISSUE TITLE
Error starting tailscale service on Archlinux 

### ISSUE THREAD

**Issue by nixfreak** [tailscale/tailscale#4706]
### What is the issue?

Tailscale errors out when trying to enable systemd service 

### Steps to reproduce

`sudo systemctl enable --now tailscaled.service`
Job for tailscaled.service failed because the control process exited with error code.
See "systemctl status tailscaled.service" and "journalctl -xeu tailscaled.service" for details.
[nixfreak@chaosArch tailscale-git]$ journalctl -xeu tailscaled.service
░░ 
░░ The unit tailscaled.service has entered the 'failed' state with result 'exit-code'.
May 19 08:36:01 chaosArch systemd[1]: Failed to start Tailscale node agent.
░░ Subject: A start job for unit tailscaled.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit tailscaled.service has finished with a failure.
░░ 
░░ The job identifier is 22016 and the job result is failed.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit tailscaled.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
May 19 08:36:01 chaosArch systemd[1]: Stopped Tailscale node agent.
░░ Subject: A stop job for unit tailscaled.service has finished
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A stop job for unit tailscaled.service has finished.
░░ 
░░ The job identifier is 22094 and the job result is done.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Start request repeated too quickly.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit tailscaled.service has entered the 'failed' state with result 'exit-code'.
May 19 08:36:01 chaosArch systemd[1]: Failed to start Tailscale node agent.
░░ Subject: A start job for unit tailscaled.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit tailscaled.service has finished with a failure.
░░ 
░░ The job identifier is 22094 and the job result is failed.`

### OS

Linux

### OS version

 5.17.4-arch1-1

### Tailscale version

1.25.84

**Comment by DentonGentry** [comment]
The error output suggests that you run `journalctl -xeu tailscaled.service` to get information about the failure. Did you do that?

**Comment by nixfreak** [comment]
Yes I can post again if you want 

journalctl -xeu tailscaled.service
░░ 
░░ The unit tailscaled.service has entered the 'failed' state with result 'exit-code'.
May 19 08:36:01 chaosArch systemd[1]: Failed to start Tailscale node agent.
░░ Subject: A start job for unit tailscaled.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit tailscaled.service has finished with a failure.
░░ 
░░ The job identifier is 22016 and the job result is failed.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit tailscaled.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
May 19 08:36:01 chaosArch systemd[1]: Stopped Tailscale node agent.
░░ Subject: A stop job for unit tailscaled.service has finished
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A stop job for unit tailscaled.service has finished.
░░ 
░░ The job identifier is 22094 and the job result is done.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Start request repeated too quickly.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit tailscaled.service has entered the 'failed' state with result 'exit-code'.
May 19 08:36:01 chaosArch systemd[1]: Failed to start Tailscale node agent.
░░ Subject: A start job for unit tailscaled.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit tailscaled.service has finished with a failure.
░░ 
░░ The job identifier is 22094 and the job result is failed.

### I will also post the systemctl status 

`sudo systemctl status tailscaled.service`
× tailscaled.service - Tailscale node agent
     Loaded: loaded (/usr/lib/systemd/system/tailscaled.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-05-19 08:36:01 CDT; 9min ago
       Docs: https://tailscale.com/kb/
    Process: 611048 ExecStartPre=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
    Process: 611056 ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port $PORT $FLAGS (code=exited, status=1/FAILURE)
    Process: 611066 ExecStopPost=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
   Main PID: 611056 (code=exited, status=1/FAILURE)
        CPU: 158ms

May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
May 19 08:36:01 chaosArch systemd[1]: Stopped Tailscale node agent.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Start request repeated too quickly.
May 19 08:36:01 chaosArch systemd[1]: tailscaled.service: Failed with result 'exit-code'.
May 19 08:36:01 chaosArch systemd[1]: Failed to start Tailscale node agent.

**Comment by DentonGentry** [comment]
Please run it in a shell as root and see what it complains about:
`/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641`

**Comment by nixfreak** [comment]
So installed via arch package and AUR package

**Comment by DentonGentry** [comment]
> So installed via arch package and AUR package

I don't know what this means: you installed Tailscale via the arch package?

In any case: there is no /dev/net/tun device, which Tailscale needs. The default arch kernel includes TUN, but if you've compiled your own you need to include CONFIG_TUN.

If you're running arch inside a container, the container needs to have a tun device:
`docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged tailscale/tailscale tailscaled`

**Comment by nixfreak** [comment]
I'm not running in a container , I have archlinux installed on a laptop. 
The installer doesn't work 
`curl -fsSL https://tailscale.com/install.sh | sh`

So I had to used the aur package tailscale-git  

https://aur.archlinux.org/packages?O=0&K=tailscale-git

**Comment by DentonGentry** [comment]
I'm going to ask that you spend a bit more time looking into it, step by step debugging in GitHub issue comments is not a good way to proceed.

Your arch system does not have a /dev/net/tun device. You need to fix that.
