### ISSUE TITLE
FR: Hellō (hello.coop) IdP support?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4707]
Tracking bug for investigating supporting https://www.hello.coop/ as an identity provider.

**Comment by dickhardt** [comment]
I think this is a great idea! Let me know how we can help. =)

docs: https://hello.dev

**Comment by DentonGentry** [comment]
Since this issue was filed, support for Custom OIDC providers has been added: https://tailscale.com/kb/1240/sso-custom-oidc/

**Comment by catzkorn** [comment]
This should be supported by our Custom OIDC feature.
