### ISSUE TITLE
Can I build a tailscale system by myself? Because I may need more subnet rules.FR: 

### ISSUE THREAD

**Issue by bbhxwl** [tailscale/tailscale#4712]
### What are you trying to do?

Can I build a tailscale system by myself? Because I may need more subnet rules.FR: 
I paid for the personal professional edition, which may not meet my needs.

**Comment by DentonGentry** [comment]
All of the code needed to build the Linux client is in this repository https://github.com/tailscale/tailscale
It is compiled using the usual `go build` tools.

I'm going to close this issue: you'll need to have enough programming expertise and Go expertise to be able to do so, we're not able to offer step by step support for doing so.
