### ISSUE TITLE
I am a personal professional user. How do I restrict one device from accessing another? I think the tutorial can only limit one user? I think the tutorial can only limit a certain user name? Instead of one of your own devices?

### ISSUE THREAD

**Issue by bbhxwl** [tailscale/tailscale#4713]
https://tailscale.com/kb/1192/acl-samples/#monitoring-access-to-applications
I am a personal professional user. How do I restrict one device from accessing another? I think the tutorial can only limit one user? I think the tutorial can only limit a certain user name? Instead of one of your own devices?

**Comment by DentonGentry** [comment]
If there is one device you'd like to be treated differently, I suspect that device should probably be Tagged for its role like `tag:server`: https://tailscale.com/blog/acl-tags-ga/

Once tagged, you can apply ACLs to the Tag:
```
{
    "Action": "accept",
    "Users":  ["autogroup:members"],
    "Ports": ["tag:server:*"],
},
```

This will allow all non-tag Users to access `tag:server` but doesn't allow `tag:server` to access anything.

If you really don't want to use a Tag, it is possible to apply an ACL on the IP address:
```
    "Hosts": {
        "host1":            "100.101.1.1",
    },
    {
        "Action": "accept",
        "Users":  ["autogroup:members"],
        "Ports": ["host1:*"],
    },
```

Filing GitHub issues is not a good way to handle consulting on ACLs, as we cannot reference the devices on your account nor the contents of the ACL file for your tailnet. I'd suggest contacting support@tailscale.com for any followups.

**Comment by bbhxwl** [comment]
> support@tailscale.com



> If there is one device you'd like to be treated differently, I suspect that device should probably be Tagged for its role like `tag:server`: https://tailscale.com/blog/acl-tags-ga/
> 
> Once tagged, you can apply ACLs to the Tag:
> 
> ```
> {
>     "Action": "accept",
>     "Users":  ["autogroup:members"],
>     "Ports": ["tag:server:*"],
> },
> ```
> 
> This will allow all non-tag Users to access `tag:server` but doesn't allow `tag:server` to access anything.
> 
> If you really don't want to use a Tag, it is possible to apply an ACL on the IP address:
> 
> ```
>     "Hosts": {
>         "host1":            "100.101.1.1",
>     },
>     {
>         "Action": "accept",
>         "Users":  ["autogroup:members"],
>         "Ports": ["host1:*"],
>     },
> ```
> 
> Filing GitHub issues is not a good way to handle consulting on ACLs, as we cannot reference the devices on your account nor the contents of the ACL file for your tailnet. I'd suggest contacting [support@tailscale.com](mailto:support@tailscale.com) for any followups.

Are there any communication groups? The technical support reply basically takes 24 hours. Although I have bought it. I don't understand what this sentence means?

··
"Users":  ["autogroup:members"],
··

**Comment by DentonGentry** [comment]
> The technical support reply basically takes 24 hours.

You need to make allowances for timezones. It is 2am here.
