### ISSUE TITLE
FR: Auto login with key

### ISSUE THREAD

**Issue by YBAAC** [tailscale/tailscale#4714]
### What are you trying to do?

I'm trying to run a script that would automaticly login to the tailscale network so ssh is allowed as soon as the script is run.

### How should we solve this?

Provide a login key that allows the user to run tailscale up -key value

### What is the impact of not solving this?

I run multiple servers per day if this isn't implemented I create server > ssh in > install tailscale and auth > add firewall.
If this is implemented I could set a script to autorun on server creation allowing me to create server and add to firewall before it is created.

### Anything else?

The reason I can't add the firewall before is because one of the firewall rules is ssh over tailscale only. Obviously things like key expiry and such will still be in place, but having to change the script once a month with a different key is less time consuming then having to auth every machine seperately before adding a firewall.

**Comment by DentonGentry** [comment]
Do authkeys work for this use? https://tailscale.com/kb/1085/auth-keys/

**Comment by DentonGentry** [comment]
Barring further comment we'll assume that [authkeys](https://tailscale.com/kb/1085/auth-keys/) can fill this need and close this issue in the next bug scrub.

**Comment by DentonGentry** [comment]
Fixed by using authkeys.
