### ISSUE TITLE
FR: Support Codeberg as an identity provider

### ISSUE THREAD

**Issue by 6543** [tailscale/tailscale#4717]
### What are you trying to do?

Add [Codeberg](https://codeberg.org/) as identity provider

[Codeberg](https://codeberg.org/) is an alternative for Gitlab & Github, completly founded as NGO
to help FOSS development in mind.

But the most interesting part is, it's one of the few not hosted in US
but EU, more specific in Germany ...

### How should we solve this?

To add CB should be not to hard, as it does serve as normal Oauth2
Provider ... (https://docs.gitea.io/en-us/oauth2-provider/)

### What is the impact of not solving this?

only big non foss login options

**Comment by 6543** [comment]
tldr: since you use go and Codeberg uses [gitea](https://github.com/go-gitea/gitea)  you could use github.com/markbates/goth as lib that should make oauth integration easy ...

**Comment by DentonGentry** [comment]
Since this issue was filed, support for Custom OIDC providers has been added: https://tailscale.com/kb/1240/sso-custom-oidc/

**Comment by catzkorn** [comment]
Closing this issue as both Gitea and Codeberg work with our [custom OIDC](https://tailscale.com/kb/1240/sso-custom-oidc/) feature.

**Comment by marek22k** [comment]
What is the OIDC E-Mail address for CodeBerg?

**Comment by catzkorn** [comment]
You need your own domain to use Custom OIDC.

**Comment by marek22k** [comment]
And how can I use CodeBerg with it?
