### ISSUE TITLE
install.sh: add RHEL9

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4718]
### What is the issue?

OS=rhel

VERSION=9

PACKAGETYPE=dnf

UNAME=Linux ansible 5.14.0-70.13.1.el9_0.x86_64 #1 SMP PREEMPT Thu Apr 14 12:42:38 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

NAME="Red Hat Enterprise Linux"

VERSION="9.0 (Plow)"

ID="rhel"

ID_LIKE="fedora"

VERSION_ID="9.0"

PLATFORM_ID="platform:el9"

PRETTY_NAME="Red Hat Enterprise Linux 9.0 (Plow)"

ANSI_COLOR="0;31"

LOGO="fedora-logo-icon"

CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"

HOME_URL="https://www.redhat.com/"

DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"

BUG_REPORT_URL="https://bugzilla.redhat.com/"

**Comment by DentonGentry** [comment]
Important safety tip when installing an RHEL9 VM within Proxmox: a kvm64 CPU type doesn't work. Setting the CPU type to "host" and letting RHEL deal with whatever it finds works better.

<img width="837" alt="Screen Shot 2022-05-20 at 7 48 47 AM" src="https://user-images.githubusercontent.com/1140756/169554054-d869ec26-6ee6-426d-a1fd-632dc60599b4.png">
