### ISSUE TITLE
Android app keeps phone awake and drains battery

### ISSUE THREAD

**Issue by zombiezen** [tailscale/tailscale#472]
**Describe the bug**
Whenever I enable Tailscale on my phone, it rapidly depletes the battery.

**To Reproduce**
1. Activate Tailscale Android app
2. Wait several hours. Don't even have to use Tailscale resources.

**Expected behavior**
Tailscale should have a minimal impact on battery.

**Screenshots**
<img src="https://user-images.githubusercontent.com/181535/85030639-8bca6600-b132-11ea-9694-90f3cb373b31.png" width="300"> <img src="https://user-images.githubusercontent.com/181535/85030656-938a0a80-b132-11ea-8d06-a6608925f3ab.png" width="300">

**Version information:**
 - Device: Pixel 3
 - OS: Android
 - OS version: Android 10, build QQ3A.200605.001
 - Tailscale version: v0.1.6

**Comment by bradfitz** [comment]
Whoops:

```go
        // If a mobile device is involved, disable keepalives to save on                                                                                                                                                                          
        // battery. DERP still ensures reachability while the tunnel comes                                                                                                                                                                        
        // up when there's activity.                                                                                                                                                                                                              
        if isMobileOS(node) || isMobileOS(peer) {
                peer.KeepAlive = false
        }

// ...

func isMobileOS(n *tailcfg.Node) bool {
        return n.Hostinfo.OS == "iOS"
}
```

Fixing.

**Comment by bradfitz** [comment]
We're also just turning off all keepalives globally today probably. Either alone would help a bunch here.

There is still a regular every-[20,27] second STUN packet that gets sent even on mobile that we'll be removing, especially on mobile, making it lazy. So the battery drain won't go away completely today, but a lot probably.

**Comment by bradfitz** [comment]
This is deployed.

I'm going to close this for now because other bugs (some internal) track the cross-platform issues involved that'll use less CPU/network when idle.
