### ISSUE TITLE
IPv6 only accepted in `Hosts` block of ACL file

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#4727]
### What is the issue?

We previously shipped a fix for this ([Issue #1584](https://github.com/tailscale/tailscale/issues/1584)) which accepts IPv6 hosts, but IPv6 still returns an error message when adding the address/range directly to the ACL. Adding the IPv6 address/range to a host first, then adding the host to the ACL, is the current workaround.

I also noticed that I can save IPv4 addresses successfully in IPv6 format in ACLs:
`"dst":    ["::ffff:192.168.1.150/96:*"],`

### Steps to reproduce

1. Add IPv6 address to ACL and save:
`{"Action": "accept", "src": ["*"], "dst": ["2002::1234:abcd:ffff:c0a8:101/64:*"]}`

**Expected:** IPv6 address/range is saved successfully

**Reality:** IPv4 error message is shown:

>  `Error: ports="2002::1234:abcd:ffff:c0a8:101/64:*": "2002::1234:abcd:ffff:c0a8:101": invalid IPv4 address`

**Comment by der-eismann** [comment]
This has been open for almost 9 months now, are there any news? I wanted to add a subnet router for an IPv6 range, but if I can't add any ACLs that's pretty useless :/

**Comment by DentonGentry** [comment]
You can act on IPv6 addresses, but right now only through the Hosts block:
```
	"Hosts": {
		"4via6":  "fd7a:115c:a1e0:b1a:0::/64",
	},
	"ACLs": [
		{
			"action": "accept",
			"users":  ["autogroup:members"],
			"ports":  ["4via6:*"],
		},
```

What does not work right now is instantiating directly in the ACL block, because the parser doesn't handle it:
```
	"ACLs": [
		{
			"action": "accept",
			"users":  ["autogroup:members"],
			"ports":  ["fd7a:115c:a1e0:b1a:0::/64:*"],
		},
```

**Comment by der-eismann** [comment]
Thanks for the great example! I wasn't sure what was meant in the first post, but with that I could easily make it work.
