### ISSUE TITLE
FR: Secondary Webauth with 2FA

### ISSUE THREAD

**Issue by BirdInFire** [tailscale/tailscale#4728]
### What are you trying to do?

Have a security to protect us from the "Social login"

### How should we solve this?

Add webauth as optional 2FA (on top on the one git/microsoft, etc) provide, like that with the "autorise every new connection" you already provide, even if someone take the control of our account git/microsoft etc) they won't be able to reach our admin panel without this webauth key.

### What is the impact of not solving this?

If the services we choose is breached and our account is usable by other, they can access our network

### Anything else?

Since you already do E2E on the network itself further increase the lock on the admin account panel can be really useful for everyone

For the paid (multi user) option it can be cool to have a way (as admin) to force other user to enroll this key.

**Comment by DentonGentry** [comment]
The identity providers like Microsoft, Google, Okta, etc can be set to require 2FA for login.

I don't understand what is being proposed here.

**Comment by BirdInFire** [comment]
> The identity providers like Microsoft, Google, Okta, etc can be set to require 2FA for login.
> 
> I don't understand what is being proposed here.

When the Oauth is sucessfull, having tailscal adding Asking for webauth to verify the user, so like that

Microsoft etc > Connection.
Webauth > user verification.

**Comment by DentonGentry** [comment]
To set expectations: it is unlikely that we will run an entirely separate identity provider and use it as a second layer of authentication.

In the future Tailscale might enroll 2FA tokens to verify authentication in certain circumstances, like accessing highly restricted nodes or something.

**Comment by DentonGentry** [comment]
Related: support for Passkeys has been added.
https://tailscale.com/kb/1269/passkeys/

**Comment by BirdInFire** [comment]
> Related: support for Passkeys has been added. https://tailscale.com/kb/1269/passkeys/

Indeed all you (tailscale) need to do it's to reuse this passkey way of work, and let an admin assign one to himself, and tailscale first connect him (with let's say github), once done check the passkey (with an emergency key to bypass the passkey if something go wrong ?)

Because some provider (aka github), propose weak 2FA (aka sms) or phishing one (otp), so until your alpha feature tailock is released, having a sort of advanced security mode (this second layers) can prevent (like lockdown for apple) people who consider themselves at high risk (and so use you since they don't trust normal vpn) have a more powerfull protection.

**Comment by DentonGentry** [comment]
> Because some provider (aka github), propose weak 2FA (aka sms) or phishing one (otp)

People especially concerned about this can supply their own identity provider: https://tailscale.com/kb/1240/sso-custom-oidc/

**Comment by BirdInFire** [comment]
> > Because some provider (aka github), propose weak 2FA (aka sms) or phishing one (otp)
> 
> People especially concerned about this can supply their own identity provider: https://tailscale.com/kb/1240/sso-custom-oidc/

Witch immediately exclude less tech savy people, and last time i've checked tailscale was about to make wireguard easy, if i must put my hand in the engine to fix that, why use you in the first place ? (not a true question it's more to make you understand why i think the custom way is not a proper way for normal people)
