### ISSUE TITLE
FR: Add knob to hide "Preferences" from the GUI

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4730]
### What are you trying to do?

Similar to how we can hide Network Devices, it would stop users from casually changing preferences. 

### How should we solve this?

Add a registry key or command line switch to disable that part of the menu

### What is the impact of not solving this?

In certain enterprise environments, end users changing preferences is not desirable. 

### Anything else?

HS #2134

**Comment by DentonGentry** [comment]
We're likely to do this as part of adding more MDM support for fleet deployments. The macOS app has a couple settings via MDM now, but could add similar capabilities to what the Windows client implements using registry keys settable via Microsoft Intune or SCCM.

**Comment by kelivel** [comment]
HS # 8342 — another +1 for editing/hiding GUI options, specifically the Exit Node section if there's no exit nodes available.

**Comment by JayWStapleton** [comment]
HS # 10952 also has a +1 for hiding GUI options in MacOS.

**Comment by DentonGentry** [comment]
In March 2023 the Windows client added a boolean PreferencesMenu registry key to suppress the Preferences menu. That would be in the 1.38 and 1.40 releases.

**Comment by agottardo** [comment]
Most GUI options can now be hidden in the macOS and iOS clients as well: https://tailscale.com/kb/1315/mdm-keys/#change-the-visibility-of-ui-items

@DentonGentry we can probably close this?

**Comment by agottardo** [comment]
Closing because the PreferencesMenu system policies achieves this.
