### ISSUE TITLE
Tailnet with only External devices doesn't show anything in Network Devices menu

### ISSUE THREAD

**Issue by na0x2c6** [tailscale/tailscale#4731]
### What is the issue?

Hi, thank you for the awesome product, that make my life very happy everyday.

On MacOS, I met the issue is that a sub menu of "Network devices" is not appeared.
The devices are shown in my admin console:

<img width="1095" alt="Tailscale client menu and the admin console" src="https://user-images.githubusercontent.com/15692034/170062829-81beb615-d5d3-411f-8a82-73f5bdf55a88.png">

I can confirm the ping response to the other devices with the IP assigned from Tailscale (that is 100.X.X.X).

Tailscale client version is 1.24.2,

Thanks.

### Steps to reproduce

All the others are external devices except for the own device.

I have tried re-install the Tailscale client app, login, and logout, but the issue hadn't been resolved.

I've NOT unchecked _Allow incoming connections_.
(I have seen similar issue https://github.com/tailscale/tailscale/issues/3826, but I stay with the default settings.)

### Are there any recent changes that introduced the issue?

I have met this issue since the initial setup on this device (and accepted the shared link to connect the external devices).

### OS

macOS

### OS version

12.3 and 12.4 (I met at 12.3 at the first and upgraded to 12.4 later)

### Tailscale version

1.24.2

### Bug report

BUG-55bf2acb1da82b40cd4d95e7439a4a5fe347a488590342404535a5f8b5102032-20220524150545Z-b8e51a4d70ef9158

**Comment by durind** [comment]
Hi,

That menu shows only your own devices and not shared by someone else

**Comment by uedder** [comment]
@durind 
Thank you for your reply!

> That menu shows only your own devices and not shared by someone else

In my other device, I can see shared devices, can't I?

<img width="584" alt="on the other device" src="https://user-images.githubusercontent.com/15692034/170249052-36546dd5-cce1-40b2-a8e7-4e76ef30ed2e.png">


`tailscale bugreport` output in above device:
BUG-26924f34e412f16cde2b108a279b6e5239f4472b9d624d56891ae854dd75acdb-20220525111625Z-a924c15d6afd4211

**Comment by durind** [comment]
I did some testing and the shared device appeared in to the menu when I shared one of my devices to the other user.

**Comment by uedder** [comment]
@durind 
Thank you.

I would like the Tailscale app to be fixed this issue.
Or should I register a dummy device in a workaround like you said or something for this problem? Should I make else issue?

**Comment by DentonGentry** [comment]
Near BUG-55bf2acb1da82b40cd4d95e7439a4a5fe347a488590342404535a5f8b5102032-20220524150545Z-b8e51a4d70ef9158

```
2022-05-24 22:00:09.771271 +0900 +0900: [RATELIMIT] format("netmap diff: (none)") (2 dropped)
2022-05-24 22:00:09.771282 +0900 +0900: netmap diff: (none)
```

**Comment by uedder** [comment]
@DentonGentry 
Thank you for updating this issue!

**Comment by juev** [comment]
I can confirm issue with latest version Tailscale.

One more, if I shared exit node, I can connect to this device, but can't use it as exit node.

**Comment by DentonGentry** [comment]
Were the external devices shared with your user?
If not, I wouldn't expect to see them in the devices list.

**Comment by DentonGentry** [comment]
You don't need to share it in both directions.
I'm asking if:
- the X node was shared with User A
- User A does not see the X node in the device list

The symptoms match what we would expect if the node were shared with User C. User A would not see it in the device list.

**Comment by DentonGentry** [comment]
As far as I can tell, this is working as intended. Shared nodes only appear to the user they are shared with. Sharing a node to userA@tailnet1 does not make the shared node visible to userB@tailnet1.

**Comment by na0x2c6** [comment]
@DentonGentry 

My apologies for the late reply. I recently changed jobs and devices, so I cannot immediately confirm the current behavior. However, the issue was initially raised because:

> Shared nodes only appear to the user they are shared with.

This behavior was not ensured. The issue occurs when a shared user has only a single node.

(Please note that my English may not be perfect, so I apologize if I have caused any confusion.)
