### ISSUE TITLE
Domain name resolution fails from LXC containers run by Proxmox

### ISSUE THREAD

**Issue by chuanhhoang** [tailscale/tailscale#4746]
### What is the issue?

I have this configuration:
1. A proxmox server (7.x) host with Tailscale installed.
2. A Debian 11 LXC container running on that proxmox server with Tailscale installed too.

/etc/resolv.cnf on both computer (the host and the container) looks like this:

nameserver 100.100.100.100
search xxx.gmail.com.beta.tailscale.net xxx.beta.tailscale.net

DNS for local domains (MagicDNS..) works on both computers. But for external domains like google.com, DNS failed on the LXC container.

### OS

Linux

### OS version

Debian 11.0 (Proxmox 7.x)

### Tailscale version

1.24.2

### Bug report

BUG-5e396aac486b6cda8df991094b3c77605693463a3ec02ea5c42e5b5e505e2859-20220527061921Z-19bc626c7df3efc1

**Comment by DentonGentry** [comment]
From shortly before BUG-5e396aac486b6cda8df991094b3c77605693463a3ec02ea5c42e5b5e505e2859-20220527061921Z-19bc626c7df3efc1:

```
2022-05-27 06:17:32.094185202 +0000 UTC: dns: enqueue: request queue full
2022-05-27 06:17:32.094216811 +0000 UTC: dns: enqueue: request queue full
```

This will be fixed by https://github.com/tailscale/tailscale/pull/4690, which will be included in the next release build (either 1.24.3 or 1.26.0, whichever happens first).

Until then, `systemctl restart tailscaled` will get it out of the failing state.

**Comment by chuanhhoang** [comment]
> 

Restarting tailscaled (on both the host and the container) doesn't seem to resolve the problem. This is the new bug report:
BUG-5e396aac486b6cda8df991094b3c77605693463a3ec02ea5c42e5b5e505e2859-20220527064246Z-943669045c70df59

**Comment by bradfitz** [comment]
@chuanhhoang, can you try an dev build? https://pkgs.tailscale.com/unstable/

**Comment by icing** [comment]
Seeing the same issue on my debian sid installation. SPF check for incoming mails time out on dns queries. Everything working again after uninstalling tailscale.

If you want me to check some logs (where?) or try a candidate, let me know.

**Comment by chuanhhoang** [comment]
> @chuanhhoang, can you try an dev build? https://pkgs.tailscale.com/unstable/

I have tried with the latest dev build and it didn't work. This is the bug report ID:
BUG-e58de408804d2efb292a39f1d370e183ef9078cb54d64c48fc9664697f5cf9b9-20220612172745Z-2774660aa4f50ee9
![tailscale_problem](https://user-images.githubusercontent.com/19351207/173245603-5a1944df-5f59-4644-852b-18cd3d17100c.png)

**Comment by DentonGentry** [comment]
Shortly before the BUG it is still saying
```
2022-06-12 17:27:34.92917337 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:34.929182608 +0000 UTC: dns udp query: request queue full
```

https://github.com/tailscale/tailscale/pull/4690 fixed a common cause of this error but apparently there are more.

Is it possible there is just a very very high rate of DNS queries being sent?
- `tailscale debug metrics` has some metrics (everything starting with "dns")
- `tcpdump -i tailscale0 port 53` would show DNS packets

**Comment by chuanhhoang** [comment]
> 

That was just a fresh LXC container with nothing installed. DNS resolution works well on the host which runs Tailscale too.

**Comment by DentonGentry** [comment]
I don't really understand what that means: did BUG-e58de408804d2efb292a39f1d370e183ef9078cb54d64c48fc9664697f5cf9b9-20220612172745Z-2774660aa4f50ee9 come from the new LXC, or from the Proxmox host?

For completeness, the guides we have about both are:
- https://tailscale.com/kb/1133/proxmox/
- https://tailscale.com/kb/1130/lxc-unprivileged/

**Comment by chuanhhoang** [comment]
> I don't really understand what that means: did BUG-e58de408804d2efb292a39f1d370e183ef9078cb54d64c48fc9664697f5cf9b9-20220612172745Z-2774660aa4f50ee9 come from the new LXC, or from the Proxmox host?
> 
> For completeness, the guides we have about both are:
> 
> * https://tailscale.com/kb/1133/proxmox/
> * https://tailscale.com/kb/1130/lxc-unprivileged/

All the bug reports I submitted were from LXC containers. Of course, I carefully followed the guides on tailscale.com.

**Comment by DentonGentry** [comment]
It would be best to generate fresh bugreports using 1.30 when it is released next week. The bugreports from June 12 just show:
```
2022-06-12 17:27:17.432733724 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:17.432798035 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:22.334937419 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:22.334998684 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:24.924702288 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:24.924761169 +0000 UTC: dns udp query: request queue full
2022-06-12 17:27:24.924876595 +0000 UTC: [RATELIMIT] format("dns udp query: %v")
2022-06-12 17:27:29.034188165 +0000 UTC: [RATELIMIT] format("magicsock: starting endpoint update (%s)") (1 dropped)
```

**Comment by DentonGentry** [comment]
ETIMEDOUT. If this is still a problem, please generate fresh bugreports from inside the LXC container while DNS is failing.

We have a number of sites using various distributions within LXCs hosted within Proxmox, it definitely can work.
