### ISSUE TITLE
exit-node: CreateEndpoint error "connection was refused"

### ISSUE THREAD

**Issue by wpcarro** [tailscale/tailscale#4747]
### What is the issue?

Whenever I use the `--exit-node` feature, I lose internet access. 

```
λ tailscale up --exit-node foo
λ ping google.com # unreachable
λ tailscale up --reset
λ ping google.com # works
```

The logs on the exit node indicate that somethings failing

```
λ journalctl -lfu tailscaled
May 27 11:29:32 foo tailscaled[8235]: CreateEndpoint error for 100.x.x.x:45762 -> 100.x.x.x:50677: connection was refused
```

### Steps to reproduce

- foo is an advertised exit node (authorized in the admin UI)
- bar calls `tailscale up --exit-node=<foo's ip>
- `ping google.com` fails

I also have the following configuration on the exit node:

```
  # Support IP forwarding to use this device as a Tailscale exit node.
  boot.kernel.sysctl."net.ipv4.ip_forward" = true;
  boot.kernel.sysctl."net.ipv6.conf.all.forwarding" = true;
  # Additionall exit node settings that Tailscale recommends.
  networking.firewall.checkReversePath = "loose";
```

Confirmed by:

```
λ cat /etc/sysctl.d/* | egrep '(ipv4.ip_forward|ipv6.*forwarding)'
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
```

### Are there any recent changes that introduced the issue?

Nothing that I'm aware of. I'm not sure I've been able to successfully use `--exit-node` feature.

### OS

Linux

### OS version

NixOS 21.11

### Tailscale version

1.24.2

### Bug report

BUG-5e23772b5f29865b40893743dab2768b76dc703d863ce630ae8842fb246520d5-20220527183426Z-b3c9b59646c064a4

**Comment by DentonGentry** [comment]
> connection was refused

Implies there is a firewall policing tailscale0.

**Comment by DentonGentry** [comment]
I'm assuming this was a local firewall problem.
