### ISSUE TITLE
Kubernetes Sidecar unable to interact with tailscaled

### ISSUE THREAD

**Issue by shadycuz** [tailscale/tailscale#4757]
### What is the issue?

```
/ # tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 9). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

### Steps to reproduce

I followed the steps in the documentation to create a sidecar next to my application.

### OS

Other

### Tailscale version

```
/ # tailscale --version
1.24.2
  tailscale commit: dce2409b15837f30885405b8b1d27e7b7fd6bf7a
  go version: go1.18.1-ts710a0d8610
  ```

**Comment by shadycuz** [comment]
part of cleanup of the k8 experience #4537

**Comment by shadycuz** [comment]
This is because the k8 sidecar example uses a non default socket location? 

https://github.com/tailscale/tailscale/blob/928530a1122b5b9bc9880bd2940923f7cd448a59/docs/k8s/run.sh#L18

So you need to pass `--socket=/tmp/tailscaled.sock` to `tailscale`, which as far as I can tell is an undocumented flag https://tailscale.com/kb/1080/cli/. 

I can raise a PR to fix the sidecar container, but I'm not sure about the docs for the missing CLI flag for `--socket`.

**Comment by jerrywoo96** [comment]
Having the same issue as well in Synology docker.
Here is my docker config as well.


![image](https://user-images.githubusercontent.com/26324139/174749813-a649d955-4610-42f7-9ba0-9bbfc59f7b26.png)


![image](https://user-images.githubusercontent.com/26324139/174749276-0dc6035a-00d8-4d3e-9596-af92a1e54013.png)

**Comment by shadycuz** [comment]
@jerrywoo96 I haven't fixed this in the Dockerfile yet... But I will today.

For now try `tailscale --socket=/tmp/tailscaled.sock up`

**Comment by jerrywoo96** [comment]
Here's another solution.

https://forum.tailscale.com/t/unable-to-run-tailscale-in-synology-docker-dsm7/2536/3

**Comment by shadycuz** [comment]
I went to fix this and they had released a new updated image. I have it deployed for testing but I have not checked to see if it has the same problem. I'm guessing it does because it still has the same socket location.

**Comment by c11umw** [comment]
It is the same.
I was in the same situation this morning and saw the latest release was only a 2 days old.
Tested and it failed as before.

That's when I spotted the .sock path was incorrect (as per the forum post above)

**Comment by shadycuz** [comment]
I posted the fix 28 days ago 🤔 



> This is because the k8 sidecar example uses a non default socket location?
> 
> https://github.com/tailscale/tailscale/blob/928530a1122b5b9bc9880bd2940923f7cd448a59/docs/k8s/run.sh#L18
> 
> So you need to pass `--socket=/tmp/tailscaled.sock` to `tailscale`, which as far as I can tell is an undocumented flag https://tailscale.com/kb/1080/cli/.
> 
> I can raise a PR to fix the sidecar container, but I'm not sure about the docs for the missing CLI flag for `--socket`.

**Comment by c11umw** [comment]
Ah, yes that worked.
Once the container was up...
`docker exec tailscaled tailscale --socket=/tmp/tailscaled.sock up`

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/5620 added a way to add `/tmp/tailscaled.sock` as a socket path. I think that was the resolution here.
