### ISSUE TITLE
Android on ChromeOS can't Sign In

### ISSUE THREAD

**Issue by rspier** [tailscale/tailscale#476]
**Describe the bug**
The Sign In button doesn't do anything on the Android app on Chrome OS.

**To Reproduce**
1. Install Android Beta app on ChromeOS.
2. Launch App
3. Click "Sign In"
4. Nothing happens.  (Although the button runs the click animation.)

**Expected behavior**
Taken through sign in flow.

**Version information:**
 - Device: Google Pixelbook (Eve)
 - OS: ChromeOS
 - OS version: 83.0.4103.112 (Official Build) (64-bit)
 - Tailscale version: 0.1.7

**Additional context**
@apenwarr filed another bug where this worked for him... but that may have been an different version of the app, or some other difference.

**Comment by bradfitz** [comment]
Closing as dup of #470 for now. I doubt there's anything ChromeOS-specific here but we can reopen if so.
