### ISSUE TITLE
Windows TUN interface is only recreated upon service start

### ISSUE THREAD

**Issue by raggi** [tailscale/tailscale#4762]
### What is the issue?

If the Tailscale interface is gone for some reason, such as being removed/disabled in the windows networking panel, there should be a way via the GUI for the software to heal.

### Steps to reproduce

Stop Tailscale.
Open Windows networking panel.
Right click the Tailscale interface, select disable.
Start Tailscale again.
Observe no functioning connectivity, and no error reported in the GUI.

`tailscale netcheck` appears happy
`tailscale status` reports an error above the peer list, which may be off-screen on larger tailnets.

### OS version

Windows

### Tailscale version

1.25.98

**Comment by raggi** [comment]
Restarting the Tailscale service does recreate the interface.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2591
