### ISSUE TITLE
Frequent dns: error: context deadline exceeded

### ISSUE THREAD

**Issue by wpcarro** [tailscale/tailscale#4769]
### What is the issue?

We're seeing a lot of errors that look like this:

```
2022-06-01 09:33:10 | [RATELIMIT] format("dns: error: %v")
2022-06-01 09:33:10 | dns: error: context deadline exceeded
```

We're also seeing a spike in tailscale CPU usage alongside climbing `postgres` RAM consumption.

### Are there any recent changes that introduced the issue?

I configured 2x new monitoring services yesterday:
- prometheus exporter (process-exporter)
- timescale+promscale (running inside docker containers) for distributed tracing collection

### OS

Linux

### OS version

NixOS 21.11

### Tailscale version

1.22.2

### Bug report

BUG-48873a9ffa23c3c8789f4f4cd757cfd72e3d62e70a27c47b15805e7bf60bb2bf-20220601163559Z-a3dde1b0f2c3bc84

**Comment by bradfitz** [comment]
We've (mostly @twitchyliquid64) fixed a bunch of DNS stuff recently since 1.22.x. 1.26.0 is coming out soon. Perhaps Monday.

This sounds a lot like something that was recently fixed.

**Comment by DentonGentry** [comment]
1.26.0 makes several changes related to DNS:
- uses netstack to receive packets, allowing DNS-over-TCP and UDP-fragmentation to both work
- fixes a queue leak which can result in breaking DNS until tailscaled is restarted

**Comment by DentonGentry** [comment]
The changes in 1.26 to use netstack (a userspace TCP/IP stack) changes much of this behavior. Does the problem still occur with Tailscale 1.28.0 or later, and can you attach another `tailscale bugreport` while you're seeing the `context deadline exceeded` log messages?

**Comment by DentonGentry** [comment]
ETIMEDOUT, believed fixed in 1.26. Please reopen if not.

**Comment by dvtkrlbs** [comment]
# Health check:
#     - dns-os: setLinkDNS: context deadline exceeded
#     - dns: setLinkDNS: context deadline exceeded

BUG-3c24b77040dab87aba693b63970cd9a7149de8e89a382425ab7be685953d3690-20221122193328Z-f42826c93267f5b5

**Comment by twitchyliquid64** [comment]
I believe this is different: `setLinkDNS` is how tailscaled tells the resolved daemon about DNS configuration, whereas `dns: error: context deadline exceeded` is more about servicing a DNS request.

**Comment by dvtkrlbs** [comment]
should I be concerned about this warning ?

**Comment by twitchyliquid64** [comment]
Yes, it indicates that resolved is not responding to requests to configure DNS, and hence I expect a lot of DNS-related functionality to be broken.

Could you file another issue for `setLinkDNS: context deadline exceeded` or [open a ticket](https://tailscale.com/contact/support/) with our support team? If you do the latter, please link to this comment so they know to route it to me.
