### ISSUE TITLE
tailscale status missing localhost info

### ISSUE THREAD

**Issue by mabels** [tailscale/tailscale#477]
I use tailscale cmd to get the complete network status and i discovered that all "machine" are reported expect the local one.

So i digged in to the source an thought to add this and found that: 
```
func (b *LocalBackend) UpdateStatus(sb *ipnstate.StatusBuilder) {
	b.e.UpdateStatus(sb)

	b.mu.Lock()
	defer b.mu.Unlock()

	// TODO: hostinfo, and its networkinfo
	// TODO: EngineStatus copy (and deprecate it?)
```
is this TODO related to my wish?
If yes? I would try to make a initial implementation. 
I would be nice if you confirm adding the local host info to the status should be happend in UpdateState in local.go?

**Comment by bradfitz** [comment]
Those TODOs are slightly different, but you're in the right general place.

`tailscale status` shows peers currently, and there's no peer for yourself. But I suppose the tool/status could synthesize one so you could see your own DERP/endpoints status.

General idea sounds fine to me.

The three `PeerStatus` fields `InNetworkMap`, `InMagicSock`, `InEngine` would all be false then, and we'd probably want a new `IsSelf bool` field. And `Peer` and `Peers` should be documented to include self.

Do you want to do it?

**Comment by mabels** [comment]
Yes that sounds great. Give me a week please. Have a lot other things todo.
Thx for your helpful response.
