### ISSUE TITLE
The android app doesn't work

### ISSUE THREAD

**Issue by srijanshetty** [tailscale/tailscale#479]
I'm probably one of the early testers and hence the issue is understandable.

I'm running Android 10, and the app is frozen on the sign in screen. On clicking `Sign In`, it does nothing and just sits there.

Would be great to get hands on the bleeding edge working edition :smile:

**Comment by bradfitz** [comment]
Closing as dup of #470

**Comment by srijanshetty** [comment]
Thanks for pointing it out, shall follow the issue there.
