### ISSUE TITLE
Delays of 2-10 seconds with MagicDNS on Windows

### ISSUE THREAD

**Issue by bdr99** [tailscale/tailscale#4791]
### What is the issue?

I recently started using Tailscale, and I'm having a performance issue where MagicDNS is rather slow to resolve a machine name into an IP address on Windows. For example, one of my Tailscale devices is named `home-server`, and if I run `ping home-server`, the DNS resolution takes anywhere from 2-10 seconds. But if I use the full domain name like `ping home-server.myemail.beta.tailscale.net`, it is instant. The issue is not specific to `ping`, it also happens with `curl`, `ssh`, or when navigating in a web browser.

I can easily reproduce it on multiple Windows 11 machines. I do not see this issue on my Linux devices, only on Windows. Please let me know if any other info is needed.

### Are there any recent changes that introduced the issue?

None - I have always experienced this issue

### OS

Windows

### OS version

Windows 11 21H2 22000.675

### Tailscale version

1.24.2

### Bug report

BUG-40ef9166166bc922f14993e992282bda550951c4e986dcd40518b42496d81d44-20220605223317Z-cd6b31f2386d7c96

**Comment by DentonGentry** [comment]
At this point there are several fixes addressing DNS speed in Windows hosts coming in Tailscale 1.26, including:
- https://github.com/tailscale/tailscale/issues/4647
- https://github.com/tailscale/tailscale/issues/4686

Early access to what will be the 1.26 release can be had at https://pkgs.tailscale.com/unstable/, where the 1.25.x builds are almost final. It is worth trying 1.25.121 to see if the performance improves.

**Comment by bdr99** [comment]
@DentonGentry Thanks for the reply. I just updated to 1.25.121 and restarted, but the issue still persists.

I'm happy to do any other testing/troubleshooting, so please let me know if there is anything I can do to help.

**Comment by DentonGentry** [comment]
Possible duplicate of https://github.com/tailscale/tailscale/issues/1659

**Comment by DentonGentry** [comment]
This is almost certainly a duplicate of https://github.com/tailscale/tailscale/issues/1659, which has a great deal of explanation of the issue and the steps tried to resolve it.

**Comment by gpion** [comment]
Huge delay indeed:

```
PS7 ${USERPROFILE}\ > Measure-Command { ssh <user>@<Tail net FQDN } | select TotalSeconds

TotalSeconds
------------
       21,52

PS7 ${USERPROFILE}\ > Measure-Command { ssh  <tailnet IP> } | select TotalSeconds
gilles@100.111.132.116: Permission denied (publickey).

TotalSeconds
------------
        0,35
```
