### ISSUE TITLE
FR: Give Control over Ephemeral Key Instance Removal Duration

### ISSUE THREAD

**Issue by MIKEPArA** [tailscale/tailscale#4798]
### What are you trying to do?

I would like the ephemeral key instances to be removed immediately from tailscale network or at least provide an option for this rather than the within hour deletion duration.

### How should we solve this?

Provide option/config for how long it will take for ephemeral key instance to be removed.

### What is the impact of not solving this?

Host name conflict with magic dns. If you are deploying ts to pods in kube cluster and relying on ts hostname it will change due to kube scaling configuration being faster than the ephemeral key removal.

**Comment by DentonGentry** [comment]
There is a delete device API which can delete a node: https://github.com/tailscale/tailscale/blob/main/api.md#device-delete

To set expectations: ephemeral node deletions are batched to reduce load on the coordination server from having so many of them. Even were the lifetime made controllable as suggested here, under load the coordination server would delay these as needed such that one couldn't depend on it for proper behavior when creating the new node. If one needs to be sure the old one has been deleted, the API provides a synchronous way to do so.

**Comment by DentonGentry** [comment]
As of Thursday, `tailscale logout` on an ephemeral node will clean it up immediately: https://tailscale.com/blog/ephemeral-logout/

This releases the hostname and makes it available for the next ephemeral node to grab.
I think this addresses the initial feature request.
