### ISSUE TITLE
Make Synology package

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#48]
We've had a few requests for a Tailscale Synology package.

From Perkeep: see https://github.com/perkeep/perkeep/blob/master/doc/synology.md and https://github.com/perkeep/perkeep/tree/master/misc/docker/synology and its build_syno.go which spits out the *.spk file

**Comment by pazaan** [comment]
Would the simplest option be to create a Tailscale account on either Docker Hub or Quay.io, and create a project Action to push official Docker images up to it? That would also cover other NASes, like QNAP.

**Comment by bradfitz** [comment]
There's a report that the lack of /dev/net/tun might be a problem.

Perhaps we'll need a root-less tailscaled that can do HTTP proxying/TCP forwarding/subnet routing all in Go (probably using gVisor's netstack).

/cc @danderson @crawshaw

**Comment by bradfitz** [comment]
(Likewise, there are requests for QNAP NAS.)

**Comment by goncalopereira** [comment]
Hello, I got around this for my openvpn/transmission set up on Synology with this tutorial, hope that might be informative.

It is working with latest DSM for me personally. 

http://haugene.github.io/docker-transmission-openvpn/synology-nas/

Regards 

```#!/bin/sh

# Create the necessary file structure for /dev/net/tun
if ( [ ! -c /dev/net/tun ] ); then
  if ( [ ! -d /dev/net ] ); then
    mkdir -m 755 /dev/net
  fi
  mknod /dev/net/tun c 10 200
  chmod 0755 /dev/net/tun
fi

# Load the tun module if not already loaded
if ( !(lsmod | grep -q "^tun\s") ); then
  insmod /lib/modules/tun.ko
fi```

**Comment by ronny** [comment]
Nice one, @goncalopereira - that's working for me as well 👍 Thank you!

**Comment by nirev** [comment]
Hey, everyone! 
Thank you for the reference here with the `/dev/net/tun` thing.

I created a Synology package building repo here: 
https://github.com/nirev/synology-tailscale

Successfully running in my Synology DS218+

Right now there are still some manual steps, but I'm seeing if there's a way to automate those.

Let me know if you test it and if it works alright for you :)

**Comment by danderson** [comment]
This is great! Thank you for doing this.

All my Synology NASes are down right now with hardware issues, but this looks like something we could add to our endless collection of packages - with appropriate caveats about manual installation, until we can figure out if getting into the Synology app store is plausible. Would it be okay if I tried importing your work to serve SPKs from pkgs.tailscale.com ? (Not right this second, but something for my backlog)

**Comment by miolini** [comment]
Great! Thank you! 

Do you have plans to add some UI for this package?

**Comment by nirev** [comment]
@danderson That would be amazing! This was my first time building a package for Synology, but it was fun making it so I could have tailscale running :)

Regarding the official Synology app store, there are some instructions [in the dev guide](https://help.synology.com/developer-guide/publish_package/get_start.html). Looks like the bureaucratic type of simple :)
Perhaps an unofficial repository that can be added as another "Package Source" would be a good intermediate step?

@miolini I'd like to, yes. At least something basic that can run `tailscale up` and retrieving the auth url.
Still need to figure out how to do that, though.

**Comment by danderson** [comment]
Yeah, it's probably "simple" in that someone needs to spend a week to make it happen. Unfortunately we have a lot of things to do that just need a week to make it happen ;).

I'll at least try to get spk serving on pkgs.tailscale.com, so that we automatically build new versions with each release. That gets us one step closer to something better.

**Comment by nirev** [comment]
Exactly, although I was thinking more of a couple weeks of emails. Definitely doesn't sound like something that should be a priority ;)

Also, just realized that #282 will happen with my package as well.
I haven't figured out how to properly handle logs on Synology (that's my next todo). 
If anyone has some reference on that, I'd appreciate.

**Comment by olofj** [comment]
> Regarding the official Synology app store, there are some instructions [in the dev guide](https://help.synology.com/developer-guide/publish_package/get_start.html). Looks like the bureaucratic type of simple :)
> Perhaps an unofficial repository that can be added as another "Package Source" would be a good intermediate step?

There seems to be a community-based app repo too, maybe that's a good start https://github.com/SynoCommunity

Thanks for doing this -- I got it going both on my 3.2.10-based(!) DS214+ and the 1812+, per my pull request yesterday. It was slightly clunky to run tailscale up manually to get the authentication URL, but it worked!

-Olof

**Comment by jmcelwain** [comment]
A QNAP package would be very helpful! I have tailscale running fine but having a bit of trouble getting it to play nice with QNAP init scripts. If anyone else has advice for QNAP systems, please drop me a line.

**Comment by ivokub** [comment]
> A QNAP package would be very helpful! I have tailscale running fine but having a bit of trouble getting it to play nice with QNAP init scripts. If anyone else has advice for QNAP systems, please drop me a line.

I have prepared a build-script for building Tailscale for QNAP. See https://github.com/ivokub/tailscale-qpkg.
It is still very rough but mostly works. You need to SSH into your QNAP to initialize the private key and authorize, but after that the init scripts should work fine. The tailscaled state file is currently stored globally (at /var/lib/tailscale) which does not survive QNAP firmware updates for now.
In order to be able install Tailscale, you need to install QVPN package as it installs necessary tun modules for wireguard to work. I tried setting it as a setup requirement, but haven't been able to test it out.

**Comment by jucor** [comment]
Flagging that @nirev 's fantastic work is currently being blocked by #451. Thanks for having a look there @bradfitz  :)

**Comment by DentonGentry** [comment]
For those following along, work on this is mostly handled in https://github.com/tailscale/tailscale-synology

**Comment by DentonGentry** [comment]
As of 1.12 I think it is time to close this. There will always be more to do, but Synology packages are being delivered in releases.

Barring further comments, we'll expect to close this during the next bug scrub.

**Comment by jucor** [comment]
Definitely :) thanks @nirev and the Tailscale team!

**Comment by DentonGentry** [comment]
The Tailscale package is now available in the Synology package center.
https://www.synology.com/en-us/dsm/packages/Tailscale

**Comment by apenwarr** [comment]
New synology kb article: https://tailscale.com/kb/1131/synology/
