### ISSUE TITLE
Domain name resolution 

### ISSUE THREAD

**Issue by cculkin-pronto** [tailscale/tailscale#4800]
### What is the issue?

I am able to ping tailscale devices by IP address, but DNS name resolution is not working.

My `/etc/resolv.conf` looks like this:
```
# Generated by NetworkManager
nameserver 127.0.0.53
```

I know this file is auto-generated, but if I manually add the line `search <name>.beta.tailscale.net` to `/etc/resolv.conf`, it will temporarily fix the DNS resolution. This line used to be added automatically. Bouncing tailscale down and back up does not fix the DNS resolution.

* Has something changed in the `resolv.conf` generation, and is it on the tailscale side?
* Is there somewhere else that is supposed to be handling DNS resolution that is not properly working?

### OS

Linux

### OS version

Ubuntu 18

### Tailscale version

1.24.2

### Bug report

BUG-51efbe533c8d483ef1412f83a2836e0a4af56cab6e31101d59dd94446aa20d83-20220606182953Z-88b561248e4e8a1d

**Comment by DentonGentry** [comment]
We're almost immediately going to need to look at private details of the tailnet to dig into this, which we cannot paste into a public bug. Could you send email to support@tailscale.com and we'll handle it there?
