### ISSUE TITLE
Unable to determine a node's actual hostname

### ISSUE THREAD

**Issue by ananthb** [tailscale/tailscale#4808]
### What is the issue?

I'm creating ephemeral nodes and supplying hostnames for them via `tailscale up --hostname xyz`. If the hostname is already taken, then tailscale suffixes a `-x` where x is a number starting at 1 and trending upwards. I need the actual hostname for requesting TLS certificates. `tailscale status` gives me the hostname I chose and not the actual hostname that tailscale registered. How can I get the real one?

### Steps to reproduce

```bash
tailscaled -state mem: &
tailscale up --authkey=... --hostname=xyz                                        # xyz is already taken so this node is actually xyz-1
actualHostName=$(tailscale status --json --peers=false | jq -r .Self.HostName)   # this should be xyz-1 but is xyz
tailscale cert "$actualHostName"                                                 # fails with  an error about incorrect hostname
```

### OS

Linux

### OS version

Fedora 36, Debian 11

### Tailscale version

1.24.2

### Bug report

BUG-521e1219212130e8f24ded2a5bba7fdd2a22519df8d93159d441c0ed16dfac0b-20220607082802Z-67303d9e19a4a951

**Comment by ananthb** [comment]
CertDomains makes sense thanks. But how do I determine the actual hostname according to the control plane? I can't find that in the docs.

**Comment by bradfitz** [comment]
You could check whether `lower(DNSName)` has `lower(HostName + ".")` as a prefix, or match it against `/-\d+\b/`? But I'm still not sure what your ultimate goal is because this started off being about `tailscale cert`.

**Comment by ananthb** [comment]
I hate to be that guy, but the issue is clearly titled: "Unable to determine a node's actual hostname". I'm just puzzled by the fact that the node thinks that it has a hostname while the control plane has its own view about this. I solved my issue by appending a random string to the node's hostname to avoid clashes. 

My original query is straightforward, and remains unanswered. If for example, I run `tailscale up --hostname=xyz` and xyz is taken already in my tailnet, the command could fail with an error. The fact that it completes successfully without any indication that the hostname I choose may not be the actual one used in my tailnet is puzzling.

**Comment by ananthb** [comment]
I'm using the API for up to date info.
