### ISSUE TITLE
Services page doesn't handle lots of servers/services

### ISSUE THREAD

**Issue by jhawk28** [tailscale/tailscale#4809]
### What is the issue?

When we add Tailscale to many servers, the service tab just hangs on Safari.

### OS

macOS

### Bug report

BUG-e788f1602941ac0db46f906c1e1c5510557d072a075d15a7be50bc0e3606fbd1-20220607171113Z-95f49108bf9c6575

**Comment by bradfitz** [comment]
cc @mihaip

**Comment by jhawk28** [comment]
we have 900+ machines. same version of safari

**Comment by mihaip** [comment]
There may be many services per machine, what does the count on the Services tab say?

![image](https://user-images.githubusercontent.com/513813/172442799-ea25bdd4-e3ec-499b-884c-900fd397e25d.png)
vs
![image](https://user-images.githubusercontent.com/513813/172442830-f296d9ef-bbc2-4af1-9a28-cd93132ae714.png)

**Comment by jhawk28** [comment]
I had disabled the service collection because it would just hang. I re-enabled it. It is still chugging away adding them all. Its starting to get laggy over 1600.

**Comment by DentonGentry** [comment]
Pagination for the Services tab in the presence of a large number of discovered services was deployed 13 Sep 2022. The Services tab should be much more performant now.
