### ISSUE TITLE
http proxy not working since 1.22.x

### ISSUE THREAD

**Issue by steom** [tailscale/tailscale#4811]
just to inform that 
Improved HTTPS proxy handling for windows client from 1.24.0, 124.2 and still today 1.26.0
broke support for http proxy.

version 1.22.2 works great instead!

control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
control: RegisterReq: onode= node=[25gj+] fup=false
tshttpproxy: winhttp: GetProxyForURL("http://controlplane.tailscale.com:80/ts2021"): ERROR_INVALID_PARAMETER [unexpected]

logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: 
Received error: PollNetMap: Post "https://controlplane.tailscale.com/machine/map": connection attempts aborted by context: context deadline exceeded
trying bootstrapDNS("derp9b.tailscale.com", "144.202.67.195") for "log.tailscal.io" ...
bootstrapDNS("derp9b.tailscale.com", "144.202.67.195") for "log.tailscale.io" eror: Get "https://derp9b.tailscale.com/bootstrap-dns?q=log.tailscale.io": dialcp 144.202.67.195:443: 
trying bootstrapDNS("derp8b.tailscale.com", "2a03:b0c0:1:d0::ec1:e001") for "lo.tailscale.io" ...
bootstrapDNS("derp8b.tailscale.com", "2a03:b0c0:1:d0::ec1:e001") for "log.tailsale.io" error: Get "https://derp8b.tailscale.com/bootstrap-dns?q=log.tailscale.
o": dial tcp [2a03:b0c0:1:d0::ec1:e001]:443: 
trying bootstrapDNS("derp8c.tailscale.com", "206.189.16.32") for "log.tailscaleio" ...

**Comment by bradfitz** [comment]
cc @sailorfrag @dblohm7

**Comment by steom** [comment]
bug still present in 1.28.0
version 1.22.2 works great instead!

**Comment by dblohm7** [comment]
@steom What do your logs look like in 1.28.0? Are there still proxy errors in them? Can you post a snippet or send a bug report ID?

**Comment by steom** [comment]
tshttpproxy: CONNECT response from http://proxy.lan.org:80 for target "controlplane.tailscale.com:443" (auth "Basic xxxxxxxxxxxxxxxxxx...
(34 total bytes)"): 200 Connection established
control: control server key from https://controlplane.tailscale.com: ts2021=[fSe
S+], legacy=[nlFWp]
control: RegisterReq: onode= node=[WRyC8] fup=false
tshttpproxy: winhttp: GetProxyForURL("http://controlplane.tailscale.com:80/ts202
1"): ERROR_INVALID_PARAMETER [unexpected]
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=Ethernet (LAN) (Realtek PCIe GBE Family Controller) ifs={Ethernet (LAN):[192.168.1.190/24]} v4=true v6=false}
Start: Prefs{ra=true dns=false want=true server=true Persist{lm=, o=, n=[WRyC8]
u="12345"}}
control: client.Shutdown()
control: client.Shutdown: inSendStatus=0
Rebind; defIf="Ethernet (LAN)", ips=[192.168.1.190/24 fe80::8
4:d67b:e681:340d/64]
magicsock: 0 active derp conns
setPrivateNetwork(try=1): not found
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=Ethernet (LAN) (Realtek PCIe GBE Family Controller) ifs={Ethernet (LAN):[192.168.1.190/24]} httpproxy=http://proxy.lan.org:80 v4=true v6=false}
Rebind; defIf="Ethernet (LAN)", ips=[192.168.1.190/24 fe80::8
4:d67b:e681:340d/64]
magicsock: 0 active derp conns
tshttpproxy: CONNECT response from http://proxy.lan.org:80 for target "controlplane.tailscale.com:443" (auth "Basic xxxxxxxxxxxxxxxxxx...
(34 total bytes)"): 200 Connection established
control: mapRoutine: quit
control: Client.Shutdown done.
using frontend prefs: Prefs{ra=true dns=false want=true server=true Persist{lm=,
 o=, n=[WRyC8] u="12345"}}
Start: serverMode=true
Backend: logs: be:befcc69f0e1b61e51bc34f73847a92f12c44e24f967df65d4e348e0aaf26ec
1e fe:6e8abdd8b6e588d56c3cc8c73519d88764e49545bf71b445e2526d2b9e977b73
control: client.Login(false, 0)
control: doLogin(regen=false, hasUrl=false)
tshttpproxy: CONNECT response from http://proxy.lan.org:80 for target "controlplane.tailscale.com:443" (auth "Basic xxxxxxxxxxxxxxxxxx...
(34 total bytes)"): 200 Connection established
control: control server key from https://controlplane.tailscale.com: ts2021=[fSe
S+], legacy=[nlFWp]
control: RegisterReq: onode= node=[WRyC8] fup=false
tshttpproxy: winhttp: GetProxyForURL("http://controlplane.tailscale.com:80/ts202
1"): ERROR_INVALID_PARAMETER [unexpected]
[RATELIMIT] format("tshttpproxy: winhttp: GetProxyForURL(%q): ERROR_INVALID_PARA
METER [unexpected]")
setPrivateNetwork(try=2): not found
setPrivateNetwork(try=3): not found
setPrivateNetwork(try=4): not found
setPrivateNetwork(try=5): success
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=Ethernet (LAN) (Realtek PCIe GBE Family Controller) ifs={Ethernet (LAN):[192.168.1.190/24]} v4=true v6=false}
Rebind; defIf="Ethernet (LAN)", ips=[192.168.1.190/24 fe80::8
4:d67b:e681:340d/64]
magicsock: 0 active derp conns
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=Ethernet (LAN) (Realtek PCIe GBE Family Controller) ifs={Ethernet (LAN):[192.168.1.190/24]} httpproxy=http://proxy.lan.org:80 v4=true v6=false}
Rebind; defIf="Ethernet (LAN)", ips=[192.168.1.190/24 fe80::8
4:d67b:e681:340d/64]
magicsock: 0 active derp conns
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[WRyC8] fup=false
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[WRyC8] fup=false
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: connect
ex: Unable to establish connection. Incorrect answer from connsposta dall'host collegato. (in
 21.057s), trying bootstrap...
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[WRyC8] fup=false
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[WRyC8] fup=false
trying bootstrapDNS("derp4c.tailscale.com", "134.122.77.138") for "log.tailscale
.io" ...
bootstrapDNS("derp4c.tailscale.com", "134.122.77.138") for "log.tailscale.io" er
ror: Get "https://derp4c.tailscale.com/bootstrap-dns?q=log.tailscale.io": contex
t deadline exceeded
logtail: upload: log upload of 331 bytes compressed failed: Post "https://log.ta
ilscale.io/c/tailnode.log.tailscale.io/c073923eaf4eb578bfa5291f0e85ae182d7554b78
9b5588ec394ead86a2e4f4c": context deadline exceeded
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded

**Comment by steom** [comment]
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[ke2Jh] fup=false
trying bootstrapDNS("derp10.tailscale.com", "137.220.36.168") for "log.tailscale
.io" ...
bootstrapDNS("derp10.tailscale.com", "137.220.36.168") for "log.tailscale.io" er
ror: Get "https://derp10.tailscale.com/bootstrap-dns?q=log.tailscale.io": contex
t deadline exceeded
logtail: upload: log upload of 331 bytes compressed failed: Post "https://log.ta
ilscale.io/c/tailnode.log.tailscale.io/08f5711d02619a9a3f6987d7f800d08c485843f0b
e36da419d9562b939408666": context deadline exceeded
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[ke2Jh] fup=false
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[ke2Jh] fup=false
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: connect
ex: Unable to establish connection. Incorrect answer
after the time interval or no response from the connected host. (in
 21.014s), trying bootstrap...
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[ke2Jh] fup=false
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode= node=[ke2Jh] fup=false
trying bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "log.tailscale.
io" ...
bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "log.tailscale.io" err
or: Get "https://derp1c.tailscale.com/bootstrap-dns?q=log.tailscale.io": context
 deadline exceeded
logtail: upload: log upload of 331 bytes compressed failed: Post "https://log.ta
ilscale.io/c/tailnode.log.tailscale.io/08f5711d02619a9a3f6987d7f800d08c485843f0b
e36da419d9562b939408666": context deadline exceeded
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded

**Comment by dblohm7** [comment]
@steom Which version of Windows are you running?

**Comment by steom** [comment]
any,
i made test with win7 32-bit, win 8.1 64bit, win 10 21h2 64bit

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/commit/4dbdb19c2658e458325e30afec0e80b818b13b22 is an attempt to fix this, which will be in the 1.30 client to be released next week.

**Comment by steom** [comment]
1.30 the same, don't connect. 1.22.2 still works okay.

**Comment by dblohm7** [comment]
@steom can you tell me a bit more about your environment? Are your machines members of a domain?

**Comment by steom** [comment]
It's indifferent, also happens in workgroups pc. 
I need to revert to 1.22.2 to be able to connect with http proxy. 
Socks5 connections instead work always fine with any version.

**Comment by steom** [comment]
1.32.0 the same, don't connect. 1.22.2 still works okay.

**Comment by steom** [comment]
1.32.2 the same, don't connect. 1.22.2 still works okay.

bootstrapDNS("derp5.tailscale.com", "103.43.75.49") for "log.tailscale.io" error
: Get "https://derp5.tailscale.com/bootstrap-dns?q=log.tailscale.io": context de
adline exceeded
logtail: upload: log upload of 355 bytes compressed failed: Post "https://log.ta
ilscale.io/c/tailnode.log.tailscale.io/": context deadline exceeded
logtail: [v1] backoff: 7955 msec
control: doLogin(regen=false, hasUrl=false)

trying bootstrapDNS("derp2e.tailscale.com", "192.73.252.134") for "controlplane.
tailscale.com" ...
bootstrapDNS("derp2e.tailscale.com", "192.73.252.134") for "controlplane.tailsca
le.com" error: Get "https://derp2e.tailscale.com/bootstrap-dns?q=controlplane.ta
ilscale.com": context deadline exceeded
Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded

bootstrapDNS("derp4e.tailscale.com", "134.122.74.153") for "log.tailscale.io" er
ror: Get "https://derp4e.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial t
cp 134.122.74.153:443: i/o timeout

logtail: upload: log upload of 355 bytes compressed failed: Post "https://log.ta
ilscale.io/c/tailnode.log.tailscale.io/": context deadline exceeded
logtail: [v1] backoff: 10914 msec

Received error: register request: Post "https://controlplane.tailscale.com/machi
ne/register": connection attempts aborted by context: context deadline exceeded

**Comment by marquis-pprefontaine** [comment]
I’m encountering a similar issue. It had been preventing from deploying Windows services on the tailnet until I figured out the specific dance I needed to do. We’d been deploying Linux “servers” up until now.

It’s happened on Windows Server 2008 R2, Windows Server 2016 and Windows 10 22H2. From a Windows local administrator profile, using an elevated command line, I am able to run `tailscale up`, copy the URL and authenticate and authorize the machine elsewhere. Immediately after authorizing, I run `status` on the machine, and it tells me Tailscale is stopped. `netcheck` will sometimes successfully analyse things. I have never gotten things working using the CLI. We see:

- `tshttpproxy: winhttp: GetProxyForURL("https://log.tailscale.io/c/tailnode.log.tailscale.io/[snip]"): ERROR_INVALID_PARAMETER [unexpected]`
- `tshttpproxy: winhttp: GetProxyForURL("https://controlplane.tailscale.com/"): ERROR_INVALID_PARAMETER [unexpected]`
- `[RATELIMIT] format("tshttpproxy: winhttp: GetProxyForURL(%q): ERROR_INVALID_PARAMETER [unexpected]")`

If instead, I authenticate using the GUI (`tailscale-idn.exe`) the default browser is launched, I copy the URL and authenticate and authorize the machine elsewhere. Tailscale notifies me that all is good. Things appear ok. If I reboot the computer, the machine is never available again over the tailnet. I log back in to the user profile I used to authenticate, I run the Tailscale GUI again, the machine comes back online on the tailnet. I reboot the computer a second time, and shortly after boot, the machine is now available on the tailnet, without any manual intervention. I’m currently using version 1.32.2.

Short output of what happens with the CLI:
```
C:\ProgramData>tailscale up

To authenticate, visit:

        https://login.tailscale.com/a/6c8dd6f596f7


To authorize your machine, visit (as admin):

        https://login.tailscale.com/admin/machines

Success.

C:\ProgramData>tailscale status
# Health check:
#     - state=Stopped, wantRunning=false

Tailscale is stopped.
```

This seems unrelated to whether things are working or not, but seems in the same class of issues so I’m reporting it here: once things are all working after the dance I specified above, I still get this error from the CLI running `netcheck` on Windows Server 2008 R2 and Server 2016, but not (only tested on two machines) on Windows 10 22H2:
```
C:\>tailscale netcheck
2022/10/27 17:09:21 No DERP map from tailscaled; using default.
2022/10/27 17:09:22 tshttpproxy: winhttp: GetProxyForURL("https://controlplane.tailscale.com/"): ERROR_INVALID_PARAMETER [unexpected]

[real netcheck details]
```

I know this isn’t the most useful writeup, but I wanted to point it out and ask how I can better help debug the issue. We’re not doing any kind of proxying or SSL/TLS interception on these machines. Please let me know what more useful information I can provide privately, or anything else I can do to help.

Thanks!

**Comment by marquis-pprefontaine** [comment]
Forgot to mention a key piece of information: we are doing are installations using a remote management tool that runs the following command as the local SYSTEM account:

`"%SystemRoot%\System32\msiexec.exe" TS_ADMINCONSOLE="hide" TS_ALLOWINCOMINGCONNECTIONS="always" TS_NETWORKDEVICES="hide" TS_TESTMENU="hide" TS_NOLAUNCH="nolaunch" TS_UNATTENDEDMODE="always" TS_UPDATEMENU="hide" /qn /log tailscale-setup-1.32.2-amd64.log /package tailscale-setup-1.32.2-amd64.msi`

This is exactly the same command we have been rolling out for “client” installs, with the difference of setting `TS_ALLOWINCOMINGCONNECTIONS` to `"never"`.

**Comment by DentonGentry** [comment]
Possibly related: https://github.com/tailscale/tailscale/issues/4394

**Comment by bradfitz** [comment]
I can reproduce this.

I put a Windows VM on a VLAN without internet access and ran a [little CONNECT proxy](https://gist.github.com/bradfitz/4b9d08087221e1820bbac18c474d372f) on the LAN that Windows could reach and configured Windows to use it:

<img width="1134" alt="Screen Shot 2022-11-06 at 3 44 07 PM" src="https://user-images.githubusercontent.com/2621/200201986-e6f03c39-c4e6-4ac1-a77f-2ea5d5f56134.png">

Browsing the web in Edge/etc works fine through it, but Tailscale doesn't start:

<img width="1192" alt="Screen Shot 2022-11-06 at 3 48 15 PM" src="https://user-images.githubusercontent.com/2621/200202176-53a3a85b-5fbc-423d-a24e-91bf67d3de72.png">

<img width="1196" alt="Screen Shot 2022-11-06 at 3 47 05 PM" src="https://user-images.githubusercontent.com/2621/200202127-58a8d79f-c491-4f21-8cf9-3ead9b187132.png">

**Comment by bradfitz** [comment]
Debugging.

The path I'm hitting is:

```go
		if err == syscall.Errno(ERROR_WINHTTP_AUTODETECTION_FAILED) {
			metricErrDetectionFailed.Add(1)
			setNoProxyUntil(10 * time.Second)
			return nil, nil
		}
```

**Comment by bradfitz** [comment]
Hah, of course. We're dealing with two (at least) different Window proxying settings/layers.

The one I set in settings (which works in Edge, etc) isn't apparently winhttp (per `netsh winhttp show proxy`) nor the `WinHttpGetProxyForUrl` call we're using.

So, uh, I guess there are different APIs we need to get the Proxy as set by `Settings > Network & Internet > Proxy`?

<img width="1269" alt="Screen Shot 2022-11-06 at 8 46 01 PM" src="https://user-images.githubusercontent.com/2621/200228463-907563c3-a7db-47a1-9ccf-bb95a228b2b7.png">

**Comment by bradfitz** [comment]
`WinHttpGetIEProxyConfigForCurrentUser` maybe?
https://learn.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpgetieproxyconfigforcurrentuser

**Comment by bradfitz** [comment]
Okay, I confirmed that `WinHttpGetIEProxyConfigForCurrentUser` returns "http://10.2.0.1:8123" matching my screenshot above, using the following code. And it works for both an admin user & regular user. But I only checked running in the foreground, not as a service yet.

```go
var kernel32 = windows.NewLazySystemDLL("kernel32.dll")
var globalFree = kernel32.NewProc("GlobalFree")

func globalFreeMaybe(ptr *uint16) {
	if ptr != nil {
		_, _, _ = globalFree.Call(uintptr(unsafe.Pointer(ptr)))
	}
}

var winHttp = windows.NewLazySystemDLL("winhttp.dll")
var winHttpGetIEProxyConfigForCurrentUser = winHttp.NewProc("WinHttpGetIEProxyConfigForCurrentUser")

type tWINHTTP_CURRENT_USER_IE_PROXY_CONFIG struct {
	fAutoDetect       int32 // BOOL
	lpszAutoConfigUrl *uint16
	lpszProxy         *uint16
	lpszProxyBypass   *uint16
}

func WinHttpGetIEProxyConfigForCurrentUser() (string, error) {
	if err := winHttpGetIEProxyConfigForCurrentUser.Find(); err != nil {
		return "", err
	}
	p := new(tWINHTTP_CURRENT_USER_IE_PROXY_CONFIG)
	r, _, err := winHttpGetIEProxyConfigForCurrentUser.Call(uintptr(unsafe.Pointer(p)))
	if r == 1 {
		defer globalFreeMaybe(p.lpszProxy)
		defer globalFreeMaybe(p.lpszProxyBypass)
		return windows.UTF16PtrToString(p.lpszProxy), nil
	}
	return "", err
}
```

**Comment by bradfitz** [comment]
But @steom, where in Windows do you configure your proxy? And what type?

I don't yet understand how it ever worked for you, assuming you're setting the proxy in the same place I just found that doesn't work.

So I suspect you're setting it elsewhere.

**Comment by sailorfrag** [comment]
Environment variables were working at some point, sort of (logs didn't use the proxy, and it could make the GUI unable to talk to the service)

**Comment by steom** [comment]
> But @steom, where in Windows do you configure your proxy? And what type?
> 
> I don't yet understand how it ever worked for you, assuming you're setting the proxy in the same place I just found that doesn't work.
> 
> So I suspect you're setting it elsewhere.

![image](https://user-images.githubusercontent.com/5721593/200250953-8186b90a-881a-4504-bdfc-e4afaeeaabf5.png)

**Comment by bradfitz** [comment]
@steom, can you answer my question? 

Where are you configuring your proxy, and how?

**Comment by steom** [comment]
From the GUI - Control Panel | System | Environment | System/User Variables
Or it's the same from cmd set/setx https_proxy=http://10.2.0.1:8123

**Comment by steom** [comment]
1.34.0 finally works.

I've notice that the last seen information from the website it's not update in realtime anymore, like in 1.22.2

![Screenshot_20221205_225346](https://user-images.githubusercontent.com/5721593/205750779-fa21d5c5-60c9-41bc-8cfd-64e452f90517.jpg)

**Comment by bradfitz** [comment]
Good to hear! Closing this.

@steom, can you file a separate bug about the "Last seen"? That "Last seen" value is only relevant when the node is offline. While the node is actively connected, we account for it differently. The UI should probably just say "Now" or something when it's already connected. (cc @tailscale/frontend)
