### ISSUE TITLE
Per-client throughput drops when multiple clients try to access shared files on a windows machine

### ISSUE THREAD

**Issue by charlesbizindavyi** [tailscale/tailscale#4820]
### What is the issue?

We have shared files that multiple clients want to access and work on at the same time. The files are stored on a windows 10 machine. We do not have any problem if one client access these files on windows machine or if multiple clients access them without using Tailscale. However, As long as (something we want to do ) multiple clients try to access the files through Tailscale, the connection remarkably slows down.

We highly would like your support as we do not want clients to access this windows 10  machine without Tailscale.

Please, let me know in case you need further information, I am happy to answer any questions. Thank you in Advance

### Steps to reproduce

Step1: Create a shared folder on Windows 10 Home
Step2: Connect multiple (2) clients (Windows or Ubuntu) to the windows 10 machine 
Step3: File copying slows down, copying from the windows 10 machine shared folder to the client;

This happens - only - when the connection is established through Tailscale VPN; Otherwise, no issue. We tried to setup this on Azure, and google Virtual Machine, we get the same issue

### Are there any recent changes that introduced the issue?

No, it is a new setup

### OS

Windows

### OS version

Windows 10 Home

### Tailscale version

Windows machine with shared files: 1.22.2;    Client: 1.26.0

### Bug report

no response

**Comment by DentonGentry** [comment]
That throughput per client drops as more clients connect, while aggregate throughput increases, doesn't seem surprising. There is only so much CPU available for encryption and copying data around.

**Comment by DentonGentry** [comment]
Barring further comment on why this behavior is unexpected, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
return -ETIMEDOUT
