### ISSUE TITLE
UDM pro fall on relay every time it come from external ip

### ISSUE THREAD

**Issue by BirdInFire** [tailscale/tailscale#4828]
### What is the issue?

When a connection come from external on UDM (with threat enabled) it fail and pass by relay (even with port 41641 open and redirected to the exit node).

This post is to ask to add the solution to the documentation (since after some long debug i have found out why and how to fix it without disabling the threat protection).

We must go to the settings -> Firewall & Security -> Edit threat categories -> Uncheck peer to peer traffic.

After that the connection append when using my 4G connection (from external) with direct connection instead of relay one.

### OS

Other

### OS version

ALL

### Tailscale version

LAST

**Comment by DentonGentry** [comment]
A section on UniFi gateways has been added to https://tailscale.com/kb/1181/firewalls/
