### ISSUE TITLE
FR: Use ExitNode as gateway only for specific destinations.

### ISSUE THREAD

**Issue by gabricc** [tailscale/tailscale#4830]
### What are you trying to do?

I'd like to use the ExitNode as gateway only for specific destinations, is that possible?

**Comment by DentonGentry** [comment]
This often comes up when working with an external service provider who asks for your static IP address to add to their allowlist to access a service. Those sorts of service providers in turn will often provide their own IP addresses to add to their customer's allowlists.

A common solution is to use a [subnet router](https://tailscale.com/kb/1019/subnets/). A subnet router can advertise any IP address; it doesn't have to be **your** IP address. For example if the vendor says they use IP addresses q.r.s.t and w.x.y.z, you can set up a subnet router with:
`tailscale up --advertise-routes=q.r.s.t/32,w.x.y.z/32`

Devices on your tailnet will go via the VPN for connections to the IP addresses of the service provider. You can set the subnet router with its own static public IP address, for example an Elastic IP address, and give the service provider your Elastic IP to add to their allowlist.

**Comment by gabricc** [comment]
Thanks @DentonGentry , I’ve just done some tests and this solution worked for me!
