### ISSUE TITLE
FR: Official Discord server for community

### ISSUE THREAD

**Issue by wolf-yuan-6115** [tailscale/tailscale#4834]
### What are you trying to do?

N/A

### How should we solve this?

Tailscale internal members should have a Discord account and one official Discord server.

Discord is a great place for chatting and collaborating with team members. It's also a wonderful place for the community.

### What is the impact of not solving this?

N/A

**Comment by DentonGentry** [comment]
There is a community server at https://forum.tailscale.com/
(a Discourse server)

**Comment by wolf-yuan-6115** [comment]
Uh, I mean "Discord" not "Discourse", it's different

**Comment by DentonGentry** [comment]
I understand that Discourse is not Discord.
I am saying that there is already a community forum at https://forum.tailscale.com/

**Comment by wolf-yuan-6115** [comment]
> I understand that Discourse is not Discord.
> I am saying that there is already a community forum at https://forum.tailscale.com/

Oh, thanks, I'll check that fourm

**Comment by tm-sanjay** [comment]
The site is showing read only mode, not allowing to login

**Comment by bradfitz** [comment]
Yes, we've since decided to just use the Tailscale Reddit as out main forum, rather than splitting discussion across too many places:

https://www.reddit.com/r/tailscale/
