### ISSUE TITLE
Max number of pings to send is broken

### ISSUE THREAD

**Issue by R-omk** [tailscale/tailscale#4836]
### What is the issue?

Ping attempts don't stop if the host is unavailable, so the next option (`--c`  why not `-c` ?) doesn't work and the default behavior doesn't work either.

```
FLAGS
  --c int
    	max number of pings to send (default 10)

```
it seems that the degradation occurred when updating to version 1.26.0

---

as a workaround now I use something like this

`/usr/bin/timeout 7s  /usr/bin/tailscale ping  --timeout=3s  ${IP}` 

### Steps to reproduce

1. stop tailscale on host with ip XXX
2. run `tailscale ping XXX` or `tailscale ping -c 2 XXX` or `tailscale ping --c 2 XXX` or `tailscale ping --c=2 XXX`

### Are there any recent changes that introduced the issue?

Update to 1.26.0

### OS

Linux

### Tailscale version

1.26.0

**Comment by R-omk** [comment]
Degradation appeared in this commit
https://github.com/tailscale/tailscale/commit/3e1f2d01f7790dc0458a7ff70c405c0c5f5e458c


This place does not count the number of attempts. 
https://github.com/tailscale/tailscale/blame/v1.26.0/cmd/tailscale/cli/ping.go#L123-L124


I think it's better to move the limit check to the beginning of the loop.
https://github.com/tailscale/tailscale/blame/v1.26.0/cmd/tailscale/cli/ping.go#L163

**Comment by bradfitz** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/4838
