### ISSUE TITLE
duplicate node id/config during kubernetes deployment

### ISSUE THREAD

**Issue by morpig** [tailscale/tailscale#4837]
### What is the issue?

I have a pod running two containers (main app & tailscale sidecar), and deployment is done using the "RollingUpdate" strategy.

Every deploy, new pod is created, health check is executed, when all is OK, old pod is terminated.

The issue is, both the old pod & new pod uses the same "TS_KUBE_SECRET", so the new pod will spit out error:

```
2022/06/11 17:39:16 health("overall"): error: Tailscale machine key cloning detected; this machine won't work. See https://tailscale.com/s/clone
```

Any ideas on how to fix this? Is it possible to temporarily save the config/state on the container rather than using secrets? Or am I using the wrong deployment guide?

### Steps to reproduce

Deploy a test app with RollingUpdate strategy together with tailscale sidecar

### Tailscale version

1.26.0

**Comment by zlepper** [comment]
The same sort of problem also occurs if you try to scale out a deployment. In this case, the pods really need some non-conflicting way of storing their state. `:mem:` store can be used for this, however that means you need to give Kubernetes an updated auth key quite often, as the deployment can't stay authorized.

**Comment by DentonGentry** [comment]
Fundamentally I think the choices are:
1. `--state=mem:`
1. Use a `TS_KUBE_SECRET`
1. persistent storage somewhere for each pod

**Comment by DentonGentry** [comment]
>you need to give Kubernetes an updated auth key quite often, as the deployment can't stay authorized.

https://github.com/tailscale/tailscale/issues/3243#issuecomment-1253946534 describes a mechanism coming soon to help provision authkeys.

**Comment by OGKevin** [comment]
I used to run the following sidecar: 

```
  ts-sidecar:
    Container ID:   containerd://e87205e22c690d9011c4d52166dcd26632d02ce92cc77cfac69701e76dea58cc
    Image:          ghcr.io/tailscale/tailscale:v1.33.132@sha256:766629890b2ce668b78ab880d813ea3059f85d634ec6ba079014bcb2d9d1316a
    Image ID:       ghcr.io/tailscale/tailscale@sha256:766629890b2ce668b78ab880d813ea3059f85d634ec6ba079014bcb2d9d1316a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sun, 06 Nov 2022 10:53:52 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      TS_TAILSCALED_EXTRA_ARGS:  --state=mem
      TS_USERSPACE:              false
      TS_AUTH_KEY:               <set to the key 'TS_AUTH_KEY' in secret 'tailscale-auth'>  Optional: false
```

Which ran fine, until upgrading to ` v1.33.141`. 

```
2022/11/06 09:39:23 Program starting: v1.33.141-tbb2cba0cd, Go 1.19.2-ts3fd24dee31: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:tailscale", "--statedir=/tmp", "--state=mem"}
```

Would still try to store the state in k8s secret, while `v1.33.132` seemed to ignore the first appearance of `--state` arg. 
Unfortunately this is hardcoded https://github.com/tailscale/tailscale/blob/da8def8e13d44df0c4183300c826523ba933cb37/cmd/containerboot/main.go#L265 😔 

I did not check the changelog between these 2 versions though.
But worst case, I would need to create a fork and remove the hardcoded state arg.

**Comment by DentonGentry** [comment]
Moved the `containerboot` comment into its own issue https://github.com/tailscale/tailscale/issues/6211

**Comment by DentonGentry** [comment]
Related: the Kubernetes Operator is available in alpha: https://github.com/tailscale/tailscale/issues/502#issuecomment-1414522795

**Comment by DentonGentry** [comment]
At this point I do not believe there is more to do. Having two pods both trying to use the same TS_KUBE_SECRET is never going to work, that makes them fight over which one gets to be the Tailscale node.

Alternatives are:
- a Kubernetes Operator is available: https://github.com/tailscale/tailscale/issues/502#issuecomment-1414522795
- the [OAuth API client is available](https://tailscale.com/kb/1215/oauth-clients/) and can be used to create authkeys on demand
