### ISSUE TITLE
Can't log in after installing standalone Mac app

### ISSUE THREAD

**Issue by lincolnmantracer** [tailscale/tailscale#4839]
### What is the issue?

My tailscale is stuck at "VPN Starting..."
<img width="480" alt="Screen Shot 2022-06-11 at 10 19 44 PM" src="https://user-images.githubusercontent.com/102976597/173203644-60914c8c-c9ea-49ad-ab3d-c045451a9c70.png">

### Steps to reproduce

I was using the app store version before. I uninstalled that by dragging it out of /Applications, then installed from the standalone installer.

### OS

macOS

### OS version

monterey 12.3.1

### Tailscale version

v1.26.0

**Comment by lincolnmantracer** [comment]
Found this in my `dmesg`, in case it's helpful: 
```
Sandbox apply: Tailscale[1515] <bytes>2 duplicate reports for Sandbox: com.apple.Safari(1144) deny(1) file-read-data /Library/Preferences/com.apple.security.plistALF, old data swfs_pid_entry <ptr>, updaterules_msg <ptr>, updaterules_state <ptr>ALF, hash_free: found kext_info <ptr> [SPI][HIDSPI]
```

**Comment by lincolnmantracer** [comment]
I deleted/reinstalled and it worked. Feel free to close 🤷

**Comment by DentonGentry** [comment]
Yeah, I doubt we'll figure out what was in /Library/Preferences/com.apple.security.plist which caused a problem.

**Comment by louwers** [comment]
In my case, I got a popup asking me for some permissions, but then the app closed (or I closed it).

It's not asking for it again.

```
[ 1016.953346]: 1 duplicate report for Sandbox: trustd(747) deny(1) mach-lookup com.apple.usymptomsdSandbox: locationd(380) deny(1) mach-lookup com.apple.systemstatus.publisherSandbox apply: Tailscale[1246] <bytes>Sandbox: contentlinkingd(1129) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox apply: SiriTTSSynthesizerAU[1248] <bytes>arm64e_plugin_host: running binary "com.apple.audio.SandboxHelper" in keys-off mode due to entitlement: com.apple.security.cs.disable-library-validationSandbox apply: com.apple.audio.[1249] <bytes>LQM-WIFI:  (HighBand) rxToss=0 rxLastTossRsn=0 rxNoFrag=0 rxNoCmplId=0 rxNoHaddr=0 rxMulti=4 rxUndec=0
```

**Comment by DentonGentry** [comment]
@louwers Please open a new issue and include a bugreport (hold option while clicking the Tailscale icon in the menubar and choose Debug > Bugreport)

**Comment by aaomidi** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/1465785/225995178-f24f469c-e969-451f-a0cf-4dc84f4b6cf2.png">

So when this happens, this is effectively what you need to do.

**Comment by rex** [comment]
And you were right @aaomidi 😎 Thanks for the simple, common-sense fix I was about to spend hours pulling my hair over.
