### ISSUE TITLE
Android: Sign in button doesn't do anything

### ISSUE THREAD

**Issue by fserb** [tailscale/tailscale#484]
**Describe the bug**
Just downloaded my Tailscale Android. 
After opening the app, it shows "Needs Authentication" in the top and a "Sign in" button. 

When I press "Sign in", I can see the little UI effect of the button press, but nothing happens after that.

**Version information:**
 - Device: Pixel 3a
 - OS: Android
 - OS version: Android 10
 - Tailscale version: v0.1.7 (?)

**Comment by bradfitz** [comment]
Dup of #470, just fixed.

**Comment by bradfitz** [comment]
FWIW, I saw the same on my Pixel 3a, but it worked if I pressed the button once and waited 5-10 seconds.

But apparently it's now fixed in 0.1.8; I haven't yet verified.

**Comment by fserb** [comment]
Ahn, my bad. I searched the open issues instead of all issues. :/ 

The press once and wait didn't work for me.

I'll wait for 0.1.8 to show up, no stress.

**Comment by sigmev** [comment]
The same issue on Samsung Galaxy S24 with the latest version.
