### ISSUE TITLE
FR: windows实现访问局域网

### ISSUE THREAD

**Issue by Aimei2008** [tailscale/tailscale#4847]
### What are you trying to do?

windows实现访问局域网

**Comment by bradfitz** [comment]
Translation: "Windows implements access to local area network"

I'm not sure what that means, though.

**Comment by DentonGentry** [comment]
If the request is for Windows to be a subnet router https://tailscale.com/kb/1019/subnets/

Windows can be a subnet router, but not from the GUI. From a cmd.exe you can use the same command as Linux:
`tailscale up --advertise-routes=192.168.0.0/24`

**Comment by DentonGentry** [comment]
I believe the intent of this feature request is to add Windows support for being a subnet router, but this was done some time ago.
