### ISSUE TITLE
macOS GUI doesn't show anything about key expiration, or options to renew

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#4852]
### What is the issue?

Via https://twitter.com/QuinnyPig/status/1536838838705786881 : when key expiry is on, the macOS GUI doesn't notify the user that expiry is coming up, or that expiry has happened. Consequently, it also doesn't offer the UI to trigger reauth, so you seemingly have to let the key expire and fall off the tailnet before you can renew.

### Steps to reproduce

Connect a mac client to a tailnet, then use debug magic to force its key to expire soon. You'd expect to get a notification if the key expires within 24h, then again 10min before expiry, then a persistent one with a prompt to reauth after expiry. Instead you get none of those.

### Are there any recent changes that introduced the issue?

I _think_ we've always missed this functionality. Spelunking through the GUI code, I see @nickoneill noting that we deliberately don't notify on macOS (as opposed to iOS), because the API was problematic in a way I don't quite follow.

If notifications are indeed a problem, we should at least do what the Windows GUI does, and add a context menu item showing the upcoming expiration, and a way to trigger renewal. It's probably not as clean as plumbing through notifications, but it at least offers some way out prior to the machine falling off the network.

### OS version

macOS current

### Tailscale version

1.26.0

**Comment by danderson** [comment]
Ah, I misread Nick's comment: the problem is specifically that we still support macOS 10.13, and so end up using the oldest notifications API, which works on 10.13, but is somewhat borked on later releases. But there's a more modern API available for macOS 11+, which we could use there at least. I think.

**Comment by nickoneill** [comment]
We did recently-ish remove the older notification type from macOS, it was heavily over-notifying right before expiry. Adding a readable expiry time somewhere in the menu is a good fallback too, it's really easy to miss your once chance to allow notifications for an app on modern macOS versions.

**Comment by DentonGentry** [comment]
Since this bug was filed webhooks have been added: https://tailscale.com/blog/webhooks/
which can provide a notification of keys expiring soon.

**Comment by mihaip** [comment]
Starting in 1.28 also show the key expiration (https://github.com/tailscale/corp/commit/db1ced1d32be5a84a02858890e60da49d8d6a36d). By default it's hidden (you need to option-click the menu bar icon), but if it's within a week (or expired) it will be shown by default.

![image](https://user-images.githubusercontent.com/513813/199344739-efcbf8d3-b25b-472b-8ee4-c0a7d0ab79e5.png)

**Comment by nyetwurk** [comment]
It isn't clear what the user is supposed to do about it still...

**Comment by agottardo** [comment]
I'm closing this because there have been several improvements made in this area recently on macOS (and iOS too).

The upcoming key expiry is displayed prominently in the app menu, and we also have notifications. NSAlerts are delivered if notifications are disabled.
