### ISSUE TITLE
FR:  Multi-arch Docker images

### ISSUE THREAD

**Issue by mayakacz** [tailscale/tailscale#4856]
### How should we solve this?

e.g., ARM build

### Anything else?

See https://github.com/tailscale/tailscale/issues/295#issuecomment-944874831

**Comment by Semmu** [comment]
Would love to see this!

In the meantime there is an unofficial solution: https://github.com/function61/tailscale-dockerimage

**Comment by Semmu** [comment]
Well I may have been mistaken because it seems the official containers are multi-arch already: https://hub.docker.com/r/tailscale/tailscale/tags

**Comment by maisem** [comment]
Right, this was fixed some time ago.
