### ISSUE TITLE
Internal server error on login when not assigned the Tailscale app in Okta

### ISSUE THREAD

**Issue by mdeeks** [tailscale/tailscale#4861]
### What is the issue?

When users try to login to Tailscale but they aren't assigned to the app in Okta, they get an internal server error rather than the error message in the URL indicating what the problem is "User is not assigned to the client application".

![image](https://user-images.githubusercontent.com/2966467/173882883-562a0c1c-df0e-487d-9cc5-c16b14305138.png)

### Steps to reproduce

Setup a tailscale account with Okta auth. Try to login as a user that isn't assigned to the Tailscale application in okta

### OS

macOS

### Tailscale version

1.26.0

**Comment by mihaip** [comment]
Looks like we get ~50 of these a day, so perhaps worth fixing. AFAICT we don't do anything with the `"error"` parameter in the `/a/oauth_response` handler? @raggi is this something that we we should be handling? Log entries look something like:

```
{
  "logtail": {
    "client_time": "2022-07-20T20:18:47.436245525Z",
    "server_time": "2022-07-20T20:18:47.548405497Z"
  },
  "bytes": 0,
  "code": 500,
  "duration": 0.167526472,
  "err": "oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"The authorization code is invalid or has expired.\"}",
  "host": "login.tailscale.com",
  "method": "GET",
  "proto": "HTTP/2.0",
  "referer": "",
  "remote_addr": "47.198.28.105:51825",
  "request_uri": "/a/oauth_response?state=REDACTED&error=access_denied&error_description=User+is+not+assigned+to+the+client+application.",
  "tls": true,
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36",
  "when": "2022-07-20T20:18:47.268699808Z"
}
```

**Comment by raggi** [comment]
Yes. We gained a good amount of the bits we need recently, I just need to plumb some more safety rails so we can do it with both polish and safety.

**Comment by psigen** [comment]
Is there an ETA on this feature?  Agree it is a non-blocker, but it would make my org's helpdesk a little less cluttered.

**Comment by mdeeks** [comment]
Thanks for the fix! Cuts down on our confused support requests a lot.

![image](https://user-images.githubusercontent.com/2966467/214924517-b4a4dc6b-98ca-4336-9ec9-bd92b78c24a3.png)
