### ISSUE TITLE
Tailscale doesn't run in parallels on M1 Macs

### ISSUE THREAD

**Issue by gabefair** [tailscale/tailscale#4867]
### What is the issue?

When running Tailscale on a windows VM (using parallels) the windows service fails to start.

The report: **BUG-a8b3f01acb6e0b17bd745430836e04fb9f7464abb32b02dfc33fc4fff4cf390b-20220616162930Z-20a488231c4f298e**

But maybe this is a result of tailscale running on my host machine as well. An M1 mac running Monterey. Here is the debug report for the host machine which isn't having any issues: BUG-2f41a36f17e6743e116d2821af142736205639fb2d53095365cdca0e2103af51-20220616163949Z-ab5594bda5ad846e

### Steps to reproduce

Run tailscale on the windows vm.

### OS

macOS, Windows

### OS version

Monterey

### Tailscale version

1.26

### Bug report

BUG-a8b3f01acb6e0b17bd745430836e04fb9f7464abb32b02dfc33fc4fff4cf390b-20220616162930Z-20a488231c4f298e

**Comment by DentonGentry** [comment]
Around the time of `BUG-a8b3f01acb6e0b17bd745430836e04fb9f7464abb32b02dfc33fc4fff4cf390b-20220616162930Z-20a488231c4f298e`:

`2022-06-16 13:25:59.9766509 -0400 -0400: control: TryLogin: register request: http 403: node nodekey:09ab6c2...95562035 bad machine key mkey:493f4c5089...4baebfee73`

**Comment by DentonGentry** [comment]
> But maybe this is a result of tailscale running on my host machine as well.

The two shouldn't interfere with each other.

**Comment by DentonGentry** [comment]
At this point I do not expect to diagnose the original issue reported a year ago. Something bad happened to the machine key. If a similar issue happens again, please open a new bug.
