### ISSUE TITLE
util/deephash: add (and fix!) fuzz tests

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#4871]
### What is the issue?

As penance for https://github.com/tailscale/tailscale/commit/36ea837736a07ad3a0ab8fe5735be124aa200202 (yes, even beyond my employment...it's embarrassing!), I threw together a very simple fuzz test:

```
func TestQuick(t *testing.T) {
	seed := time.Now().UnixNano()
	err := quick.Check(func(v, w map[string]string) bool {
		return (Hash(v) == Hash(w)) == reflect.DeepEqual(v, w)
	}, &quick.Config{MaxCount: 1000, Rand: rand.New(rand.NewSource(seed))})
	if err != nil {
		t.Fatalf("seed=%d err=%v", seed, err)
	}
}
```

It fails pretty quickly (about 2% of runs). Two sample failures:

```
    deephash_test.go:384: seed=1655417800030464000 err=#916: failed on input map[string]string{}, map[string]string{"𩘍\U000ffb03":"", "\U000992c3\U000963f7\U00051bf0\U00064db0\U0006045a\U0007f602\U0001a6ad\U0004d51a\U001061d9Ⰸ\U00096796\U000f9360\U0004558f\U0005507e\U000893b9승𪜗\U000647ba\U0003f6c8𬎝彧𪪾\U0001d259\U001096c3\U000f4112\U0005380b𗺬\U0010f1b3属𬠜\U000f9730\U0010bc25\U000d4b67\U000fead5\U000633ed\U000ac5c4𮧌\U0003b85e\U000556c1\U00076020\U0008f9c1\U0006a0ee𢗉\U000d6558\U0008ff10\U000561ee\U000b6a52\U000d1bfe\U00036b41":""}
    deephash_test.go:384: seed=1655417802803361000 err=#361: failed on input map[string]string{}, map[string]string{"\U0001d3ec\U0010b657\U000fc252\U000c6512\U000b0969\U00045e34\U000c0feb\U000f242a𡻸\U000f7fab\U0006479b\U0006b47b\U0004b8b7\U00043f4a\U00038d57\U000d2ff0𫐂𪤲\U000584e8\U00107032\U00088837\U000f0b80\U0009b45f\U000c6639\U0006d018\U0001167c\U000c28bf\U000e4375\U0005a7e0\U0007060c\U000de387":"", "\U000bf691齪\U00094f79\U000888e3\U00064b44\U000c933d\U0010318a\U000c5c31\U000bdbf0\U000686b7\U0010707c\U00076b19\U000934cd\U001066a4\U000999b1\U00100a85\U00103e7c\U000bb926\U00099c39\U000dbbee\U000df3b5\U0010174f𰃲\U00019e3d\U00105747\U000479fb\U00016cd8瞸\U000befd5\U000bc765\U0005aa3f𥐴\U000149bb\U0010171f":""}
```

Some fancier tests would probably be even better...but this is a start. :)

I don't plan to investigate further.

cc @bradfitz @dsnet 

### Steps to reproduce

Opened my text messages this morning.

### Are there any recent changes that introduced the issue?

No. There have never been any bugs in this package. Certainly never any bugs for which I am responsible. And definitely not two bugs each of which had a significant client impact. Nope.

### OS

macOS

### Tailscale version

36ea837736a07ad3a0ab8fe5735be124aa200202

**Comment by bradfitz** [comment]
```
seed := time.Now().UnixNano()
```

I meant to print deephash's internal per-process seed.  (similar to how hash/maphash works)

But I can add that. Thanks!

**Comment by bradfitz** [comment]
Minimal repro:

```go
func TestIssue4871(t *testing.T) {
	m1 := map[string]string{"": "", "foo": ""}
	m2 := map[string]string{}
	if h1, h2 := Hash(m1), Hash(m2); h1 == h2 {
		t.Errorf("bogus: h1=%x, h2=%x", h1, h2)
	}
}
```

**Comment by bradfitz** [comment]
@josharian, you're going to love the source of this bug!

It only happens when the key and value type are the same. Then they end up using the same scratch `reflect.Value` value due to this commit: 09afb8e35b56c1150ae9872d781c7ae3c151b848

**Comment by dsnet** [comment]
Fortunately we never exercised this bug since we don't have maps with the same key and value types, right?

**Comment by dsnet** [comment]
Fail.

**Comment by josharian** [comment]
Three! And counting…
