### ISSUE TITLE
Android: font scaling

### ISSUE THREAD

**Issue by evelynmitchell** [tailscale/tailscale#488]
**Describe the bug**
If the font size on Android is set to large or largest, the initial screen shows the text, but not the button, and does not allow for a scroll to see and use the button. It is visible and usable at default or small font.

**To Reproduce**
1. Go to Settings
2. Click on Accessibility>Font Size; set to Large
3. Install Tailscale
4. Can't see the acceptance button.

**Expected behavior**
When the font is large or largest, the screen scrolls to allow use of the button.

**Screenshots**

**Version information:**
 - Device: [e.g. iPhone X, laptop]
 - OS: [e.g. Windows, MacOS]
 - OS version: [e.g. Windows 10, Ubuntu 18.04]
 - Tailscale version: [e.g. 0.95-0]

**Additional context**

**Comment by eliasnaur** [comment]
Fixed on Android in the next release.

**Comment by eliasnaur** [comment]
Oh, I didn't realize the Device section was just boilerplate. Closing.

**Comment by DentonGentry** [comment]
Based on next-to-last comment, closing this issue.
