### ISSUE TITLE
Android: On Pixel 4 XL, can't sign in - nothing happens.

### ISSUE THREAD

**Issue by archon810** [tailscale/tailscale#489]
Tapping on `Sign in` does nothing. I tried on and off Wi-Fi, FCed it - nothing happens.

Also the toggle above doesn't make sense - it's enabled (right position) but just says "Needs Authentication." Toggling it doesn't do anything - it toggles but nothing changes and it still says "Needs Authentication."

![Screenshot_20200619-154003](https://user-images.githubusercontent.com/469543/85184068-36ca4500-b243-11ea-9b5e-ba4f983653f8.jpg)

App version: v0.1.7

**Comment by zombiezen** [comment]
I'm getting the same thing on Android under ChromeOS. Pixel Slate, Version 84.0.4147.51 (Official Build) beta (64-bit).

**Comment by jkuzma07** [comment]
I'm seeing the same symptoms on Android 9, Galaxy S8, build PPR1.180610.011.G950U1UES7DTC1

**Comment by bradfitz** [comment]
Dup of #470, fixed and released earlier today
