### ISSUE TITLE
Linux: portmapper still consumes CPU after tailscaled disconnects

### ISSUE THREAD

**Issue by Qubitium** [tailscale/tailscale#4891]
### What is the issue?

Did not expect tailscaled to have so many interrupt/events ~17-40/s even when tailscale status=off and even when entire system is airplane mode (wifi off).

Tailscaled daemon should be less "active" when it is on but with zero link states or with no active netlinks.

### Steps to reproduce

1. start tailscaled
2. connect to tailscale (tailscale up)
3. disconnect tailscale (tailscale down)
4. monitor interrupts/events via powertop

Kernel: 5.18.5-200.fc36.x86_64

Attached are two random powertop captures
1. Tailscale=off Wifi=on https://pasteboard.co/kZTLt99Oq9YN.png
2. Tailscale=off Wifi=off https://pasteboard.co/P45QqpjRVKrk.png

### OS

Linux

### OS version

Fedora 36

### Tailscale version

1.26.1

**Comment by bradfitz** [comment]
Can you include a "tailscale bugreport" output when it's in this state so we can see what it's doing?

**Comment by bradfitz** [comment]
> BUG-19e9beec282638e6a430b5a48c4f967a80172f66ac7ac73663ad2961ecf19a61-20220620144029Z-085d107f9bc8fea5

You had just stopped Tailscale at that point.

If your complaint is that Tailscale is doing too much work when stopped, let's look at a long period of it being stopped and see what it's doing.

Please take one bug report right after stopping it, then wait a couple hours (or in the morning after sleeping) and take another bug report, and then we can look at the time period between those bug reports to see what it was doing.

So far the only thing I see is that we don't stop subscribing to netlink events about link changes.

But those `powertop` dumps don't really say anything useful. `0.0 pkts/s` isn't very damning. 😄

**Comment by diegomontoya** [comment]
I have to disagree. My expecation is that the daemon should do nothing to wake the cpu up when tailscale is offline state. Here is the capture when wifi is off and tailscaled is restarted. It actively wakes up the cpu more often than my UI konsole which is very strange for an offline state. Unless, tailscale client offline != daemon offline? 

Another easy test is to just watch the tailscaled daemon chew up cpu time when state is down and laptop is airplane (wifi/net disabled) mode. What is it doing? It should be doing almost nothing, or nothing in the perfect world. At 400mhz (lowest idle) ryzen 3+ 6850hs cpu, tailscaled continues to chew up to 1% cpu time. 

```
The battery reports a discharge rate of 6.00 W
The energy consumed was 113 J
The estimated remaining time is 8 hours, 40 minutes

Summary: 1062.6 wakeups/second,  0.0 GPU ops/seconds, 0.0 VFS ops/sec and 8.5% CPU use

Power est.              Usage       Events/s    Category       Description
  1.48 W      0.0 pkts/s                Device         nic:tailscale0
  575 mW      3.9 ms/s     355.5        Timer          tick_sched_timer
  332 mW      3.6 ms/s     204.8        Interrupt      [10] AMDI0010:00
 98.1 mW     10.2 ms/s      59.2        Process        [PID 2320] /usr/bin/kwin_wayland --wayland-fd 5 --socket wayland-0 --xwayland-fd 6 --xwayland-fd 7 --xwayland-display :1 --xway
 97.4 mW      4.2 ms/s      59.7        Interrupt      [70] amdgpu
 82.9 mW      1.4 ms/s      51.2        Process        [PID 497] [irq/49-ELAN0768]
 68.4 mW      8.0 ms/s      41.1        Process        [PID 43858] /usr/bin/konsole
 64.6 mW    429.8 µs/s      40.0        Process        [PID 63037] /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 416
 53.1 mW      3.6 ms/s      32.3        Interrupt      [7] sched(softirq)
 52.4 mW    459.1 µs/s      32.4        Process        [PID 16] [rcu_preempt]
 26.1 mW      8.3 ms/s      14.9        Process        [PID 2559] /usr/bin/ksystemstats
 25.1 mW    551.5 µs/s      15.4        Interrupt      [7] pinctrl_amd
 24.4 mW    166.6 µs/s      15.1        kWork          psi_avgs_work
 23.3 mW      5.7 ms/s      13.6        Process        [PID 2467] /usr/bin/plasmashell --no-respawn
 15.5 mW     46.4 µs/s       9.6        kWork          toggle_allocation_gate
 11.1 mW      0.0 µs/s       6.9        kWork          commit_work
 10.5 mW      4.2 ms/s       5.9        Process        [PID 63039] /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 416
 10.4 mW    435.1 µs/s       6.4        kWork          kcryptd_crypt
 9.46 mW     17.1 µs/s       5.9        kWork          mix_interrupt_randomness
 8.28 mW      3.3 ms/s       4.6        Process        [PID 63437] /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 416
 7.66 mW    167.9 µs/s       4.7        kWork          amd_sfh_work_buffer
 7.54 mW      9.1 µs/s       4.7        kWork          flush_to_ldisc
```

**Comment by bradfitz** [comment]
I agree with you that Tailscale shouldn't waste power/CPU when it's off.

I want to find out why, but I need the information I requested in order to help you.

The information that you think is helpful to repeatedly paste on this bug is not the information that will help us fix the issue.

**Comment by diegomontoya** [comment]
Just had a very strange 100% tailscaled cpu spke, which lasted around 30s causing laptop to throttle from 6w to 30w. During this time, it was using 100% cpu. Thought it was caused by browser until I checked htop and found tailscaled as casue.

The bug report was taken about ~45s after the incidient.  At the exact momemnt of the 100% cpu spike, the wifi network was only showing about 35KB/s in traffic.  

BUG-19e9beec282638e6a430b5a48c4f967a80172f66ac7ac73663ad2961ecf19a61-20220621112743Z-aff9d220888a0f92

**Comment by diegomontoya** [comment]
@bradfitz 

1) systemctl start tailscaled
2) tailscale down 
3) systemctl restart tailscaled 

tailscaled daemon is now active and tailscale is offline state


--- about 40 minutes later ---

BUG-19e9beec282638e6a430b5a48c4f967a80172f66ac7ac73663ad2961ecf19a61-20220621153807Z-5ecc090331c716b0

observations:

1) tailscaled spawns 22 threads but only about 3 are cpu active in offline state. 2 are very active. 1 is extremely active chewing up cpu non-stop at a rate of 0.6% with frequent spikes >1.2% and seldom spikes to >4%
2) tailscaled process is using 1% cpu resource on-avg according to atop
3) according to powertop, 2 threads of tailscaled most active threads is waking up cpu (events) at a rate of around ~3-6/s for each of the two threads. There is a 3rd tailscaled thread that has wakeup events at a high rate of 20-40/s but each event appears to be very brief as to consume almost no cpu. The 2 most active threads has tangle cpu usage. The high wakeup 3rd thead does not.

**Comment by bradfitz** [comment]
With clientmetrics,

```
2022-06-21 23:09:29.597840262 +0800 +0800: control: cancelMapSafely: channel was full
2022-06-21 23:38:07.356598408 +0800 +0800: user bugreport: BUG-19e9beec282638e6a430b5a48c4f967a80172f66ac7ac73663ad2961ecf19a61-20220621153807Z-5ecc090331c716b0
        portmap_pxp_response: 2
        portmap_pcp_sent: 1
        portmap_pcp_ok: 1
        portmap_pmp_sent: 1
        portmap_pmp_ok: 1
        portmap_upnp_sent: 1
        portmap_upnp_response: 4
        portmap_upnp_ok: 1
        portmap_upnp_updated_meta: 1
        controlclient_map_requests: 1
        controlclient_map_requests_poll: 1
        controlclient_map_response_message: 1
        controlclient_map_response_map: 1
        tstun_out_to_wg: 12
        tstun_out_to_wg_drop: 12
        tstun_out_to_wg_drop_filter: 10
        netcheck_report: 1
        netcheck_report_full: 1
        netcheck_stun_send_ipv4: 12
        netcheck_stun_recv_ipv4: 8
        gauge_magicsock_netmap_num_peers: 107
        magicsock_restun_calls: 3
        magicsock_update_endpoints: 3
        wgengine_minor_changes: 1
```

So looks like the portmapper client isn't shutting down on stop.

**Comment by diegomontoya** [comment]
Just tested booting system with ipv6 completedly disabled via `ipv6.disable=1` kernel param and tailscaled cpu 1% leech issue appears to be gone. 

With ipv6 off, tailscaled (daemon running, status=off) cpu usage for tailscaled daemon is now much closer to 0% than 1% perviously.

**Comment by diegomontoya** [comment]
Does this commit resolve this issue where portmapper is not shutdown on stop?  @bradfitz 
https://github.com/tailscale/tailscale/commit/9280d396789015cfb3dc68c57d1daa44eaee6572

**Comment by bradfitz** [comment]
@diegomontoya, no, that's unrelated.

**Comment by JustinAzoff** [comment]
FWIW, there seems to be at least one bug with PowerTOP version 2.15 on my laptop where it reports that nic:tailscale0 uses 4w even with tailscale down and 0.0 pkts/s on the interface.  This is 100% nonsense, as completely stopping tailscale at this point doesn't change the overall usage by .1w, let alone 4w.  It's almost like powertop is attributing all the remaining unaccounted for power usage to nic:tailscale0 for some reason.

So, I wouldn't necessarily trust anything powertop says.

**Comment by Qubitium** [comment]
@JustinAzoff  "mW" power estimation is fairly bogus from my observation as well. But interrupts/events are accurate.

**Comment by noahfraiture** [comment]
Hello I have the same problem, tailscaled have big power consumption when down on idle computer. Is there any fix ? Or have I to stop the service every time to save battery?
