### ISSUE TITLE
Changing primary email on microsft account Causes a new account to be created

### ISSUE THREAD

**Issue by ollyroo** [tailscale/tailscale#4894]
### What is the issue?

When a tailscale account that uses microsoft as its login choice a change in the primary email of said microsoft account results in a new tailscale account being created. This also locks out the original account from being logged into

### Steps to reproduce

1. Use Microsoft as login type
2. Change primary email on Microsoft account
3. Sign in again to tailscale
4. Notice new account created

### OS

Linux, macOS, Windows, iOS, Android, Synology, Other

**Comment by DentonGentry** [comment]
If you send the domain names to support@tailscale.com, we can help get it sorted out.

**Comment by DentonGentry** [comment]
I think this was a result of refactoring done on OIDC over the summer.
