### ISSUE TITLE
Synology DSM7: Docker. Tailscale process does not come up following install

### ISSUE THREAD

**Issue by c11umw** [tailscale/tailscale#4903]
### What is the issue?

Creating a Docker install within Synology DSM7 - the container starts, but am unable to start up tailscaled

Others are seeing this also: [https://forum.tailscale.com](https://forum.tailscale.com/t/unable-to-run-tailscale-in-synology-docker-dsm7/2536)

### Steps to reproduce

All actions run as root...

Prior to install, created a macvlan:
```
docker network create -d macvlan \
--subnet=192.168.0.0/24 \
--ip-range=192.168.0.201/28 \
--gateway=192.168.0.1 \
-o parent=ovs_bond0 mycustommacvlan
```
Pulled down the latest tailscale image and start the container
```
docker run -d \
--name=tailscaled \
--network=host \
-v /my/full/local/path/to/lib:/var/lib \
-v /dev/net/tun:/dev/net/tun \
--privileged \
tailscale/tailscale:latest
```
Installed fine, but when I try to start tailscale from within the container (**docker exec tailscaled tailscale up**) I get this error:
`failed to connect to local tailscaled (which appears to be running as tailscaled, pid 7). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory`

I confirmed that /dev/net/tun exists (just in case)

### Are there any recent changes that introduced the issue?

Fist time trying this, so none that I'm aware of

### OS

Synology

### OS version

synology_apollolake_918+ (4.4.180+ #42661)

### Tailscale version

tailscale/tailscale:latest as of 17 June 2022

### Bug report

Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running?

**Comment by c11umw** [comment]
Addendum - I found the solution to the error: "/var/run/tailscale/tailscaled.sock does not exist"

Checking the processes inside the container I see:

```
/usr/local/bin # ps -ef | grep -i tailscale
    1 root      0:00 /bin/sh /tailscale/run.sh
    7 root      0:00 tailscaled --socket=/tmp/tailscaled.sock --state=mem: --tun=userspace-networking
    8 root      0:00 tailscale --socket=/tmp/tailscaled.sock up --accept-dns=false
```

The _.sock_ is there, just not in _/var/run_

So I created a symbolic link from the _/tmp_ folder to the _/var_ by typing the following:
```
mkdir tailscale
ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock
```

Now when I run **tailscale up** I get the URL to authenticate

**Comment by jerrywoo96** [comment]
linking to another similar issue.
https://github.com/tailscale/tailscale/issues/4757
#4757

**Comment by bradfitz** [comment]
I think the real problem here is that all our conditional code paths in `tailscaled` for Synology (for DSM6 vs DSM7 etc) are all assuming it's being built for the Synology package, not the Docker image.

I think we all assumed the Docker image wouldn't detect the distro as Synology and would follow the normal Debian/etc paths. Sounds like that's not the case perhaps.

/cc @DentonGentry

**Comment by DentonGentry** [comment]
As far as I can tell, tailscaled installed inside a Docker container on DSM7 detects itself as Ubuntu or Arch or whatever, not DSM7.

The original issue report says `docker exec tailscaled tailscale up` where the "tailscaled" is the name of the container and "tailscale up" is the command to be run. With no arguments, the `tailscale` CLI command does assume /run/tailscale/tailscaled.sock. To exec it within this container I think that needs to be `docker exec tailscaled tailscale --socket=/tmp/tailscale.sock up`

**Comment by jerrywoo96** [comment]
> As far as I can tell, tailscaled installed inside a Docker container on DSM7 detects itself as Ubuntu or Arch or whatever, not DSM7.
> 
> The original issue report says `docker exec tailscaled tailscale up` where the "tailscaled" is the name of the container and "tailscale up" is the command to be run. With no arguments, the `tailscale` CLI command does assume /run/tailscale/tailscaled.sock. To exec it within this container I think that needs to be `docker exec tailscaled tailscale --socket=/tmp/tailscale.sock up`

so can we make `--socket=/tmp/tailscale.sock` the default for docker containers?

**Comment by standin000** [comment]
> > As far as I can tell, tailscaled installed inside a Docker container on DSM7 detects itself as Ubuntu or Arch or whatever, not DSM7.
> > The original issue report says `docker exec tailscaled tailscale up` where the "tailscaled" is the name of the container and "tailscale up" is the command to be run. With no arguments, the `tailscale` CLI command does assume /run/tailscale/tailscaled.sock. To exec it within this container I think that needs to be `docker exec tailscaled tailscale --socket=/tmp/tailscale.sock up`
> 
> so can we make `--socket=/tmp/tailscale.sock` the default for docker containers?

I put TS_SOCKET=/var/run/tailscale/tailscaled.sock into docker-compose.yaml, it works, no need --socket=/tmp/tailscale.sock now

**Comment by Shohan-Sarker** [comment]
Thank you everyone, especially standin000! Finally got it working.

**Comment by Nothend** [comment]
> > > As far as I can tell, tailscaled installed inside a Docker container on DSM7 detects itself as Ubuntu or Arch or whatever, not DSM7.
> > > The original issue report says `docker exec tailscaled tailscale up` where the "tailscaled" is the name of the container and "tailscale up" is the command to be run. With no arguments, the `tailscale` CLI command does assume /run/tailscale/tailscaled.sock. To exec it within this container I think that needs to be `docker exec tailscaled tailscale --socket=/tmp/tailscale.sock up`
> > 
> > 
> > so can we make `--socket=/tmp/tailscale.sock` the default for docker containers?
> 
> I put TS_SOCKET=/var/run/tailscale/tailscaled.sock into docker-compose.yaml, it works, no need --socket=/tmp/tailscale.sock now

This is great,it’s works!!!
