### ISSUE TITLE
FR: easy way to "regenerate" keys

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#4904]
Some of my auth keys are set to expire.

I need to generate some new keys to replace them.

In order to do that, I need to carefully recreate the exact settings of the old keys: Reusable? Ephemeral? Which tags?

It'd be nice if there was a way to say "make me a new authkey configured just like this old authkey".

GitHub has this; they call it "regenerating" a key. It's a nice experience; less clicking, less stress.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/3243#issuecomment-1253946534 describes a mechanism whereby an app can get a long-lived OAuth token which can be used to programmatically create API keys and authkeys. The authkey settings would be in code, not a human entering settings on a web page.

**Comment by DentonGentry** [comment]
The OAuth API support is now available:
- https://tailscale.com/blog/oauth/
- https://tailscale.com/kb/1215/oauth-clients/

**Comment by DentonGentry** [comment]
I think the programatic way to allocate an authkey using the OAuth API implements the goal of this feature request.
