### ISSUE TITLE
[MagicDNS] wrong hostname auto-generated

### ISSUE THREAD

**Issue by LollipopKit** [tailscale/tailscale#4910]
### What is the issue?

Tailscale automatically changes its value to `jl.lollipopkit.github`.

- tailscale console:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/10864310/175191781-00d2ca64-cd8a-470c-bdcb-22e538274f3d.png">

- tailscale status on machine `hk` `sz`: display `jl.lollipopkit.github`
<img width="409" alt="image" src="https://user-images.githubusercontent.com/10864310/175193154-12dbe28f-810b-498f-8c6d-54745b0f8043.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/10864310/175192821-1b107b66-2c7f-4310-b9ce-209638d4c8d6.png">

- tailscale status on machine `jl`: display `jl`
![image](https://user-images.githubusercontent.com/10864310/175193389-5d46119f-b2d4-4e09-a5b5-40f1fa7e12a2.png)

### Steps to reproduce

No special steps. Just `sudo tailscale up`, wait for a period of time to run on its own.

Turning off setting `Auto-generate from OS hostname`, it will be back to normal(`jl`).

After about half an hour, it will be reset again to `jl.lollipopkit.github`.

### Are there any recent changes that introduced the issue?

Maybe due to update to 1.26.1?
No problems before the update.

### OS

Linux

### OS version

Debian 10.8

### Tailscale version

1.26.1

### Bug report

BUG-a2291e56a5fefecc1819ac3f633355af68d8c4ac5be736e0588ec2a66220b5b3-20220623022906Z-3b023567ca49f467

**Comment by ztmr** [comment]
Exactly the same here! Interesting thing is that it is intermittent, and randomly changing from `hostname` to `hostname.account.name`. If I disable automatic naming feature and hardcode the name, it does not help.

Also, if I run `tailscale status` on multiple nodes, the results are not consistent. I have tried updating those nodes that are not on autoupdate subscription, didn't help either.

**Comment by bradfitz** [comment]
This was a server bug. Sorry about that!

**Comment by DentonGentry** [comment]
The server communicates netmaps to clients containing the IP addresses and MagicDNS hostnames of other nodes on the tailnet. MagicDNS hostnames can come from `hostname` on the device, unless overridden by `tailscale up --hostname=name`, unless that is overridden by setting the name in https://login.tailscale.com/admin/machines. The bug was in not arbitrating correctly between the different sources of hostnames.
