### ISSUE TITLE
dns: support Google Cloud (GCP) DNS forwarding by default

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4911]
Hacker News [comment](https://news.ycombinator.com/item?id=31844996):

> Consistently I’m unable to use Tailscale on a GCP instance and also use GCP services cleanly, because it messes with the DNS route to the metadata server. Otherwise, it’s a great product.

We should detect when we're running on GCP (https://pkg.go.dev/cloud.google.com/go/compute/metadata) and automatically add its service resolver hierarchy as a fallback resolver split DNS route.

So even if the distro being run on GCP doesn't have systemd-resolved or something reasonable, we can still do the expected thing.

/cc @danderson @twitchyliquid64

**Comment by danderson** [comment]
SGTM. Does GCP publish the DNS suffixes they claim for internal stuff? I presume so.

**Comment by DentonGentry** [comment]
Apparently `.internal`, at least at the time we wrote up KB articles: https://tailscale.com/kb/1147/cloud-gce/
