### ISSUE TITLE
Installation fails on Ubuntu 20.04 focal NO_PUBKEY

### ISSUE THREAD

**Issue by ismith** [tailscale/tailscale#4912]
### What is the issue?

Looks superficially similar to https://github.com/tailscale/tailscale/issues/4389, but not enough detail in that issue to be sure we ran into the same bug.

### Steps to reproduce

```
$ curl -fsSL https://tailscale.com/install.sh | sh
Installing Tailscale for ubuntu focal, using method apt
+ sudo mkdir -p --mode=0755 /usr/share/keyrings
+ curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg
+ sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg
+ curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.tailscale-keyring.list
+ sudo tee /etc/apt/sources.list.d/tailscale.list
# Tailscale packages for ubuntu focal
deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu focal main

+ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Get:3 https://pkgs.tailscale.com/stable/ubuntu focal InRelease                 
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]     
Hit:5 https://cli.github.com/packages focal InRelease                          
Get:6 http://archive.ubuntu.com/ubuntu focal-proposed InRelease [267 kB]       
Hit:7 http://ppa.launchpad.net/berglh/pulseaudio-a2dp/ubuntu focal InRelease   
Get:8 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Ign:9 http://linux.dropbox.com/ubuntu disco InRelease                          
Hit:10 http://linux.dropbox.com/ubuntu disco Release                           
Err:3 https://pkgs.tailscale.com/stable/ubuntu focal InRelease                 
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 458CA832957F5868
Get:11 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]  
Hit:12 http://ppa.launchpad.net/linuxuprising/apps/ubuntu focal InRelease      
Hit:13 http://dell.archive.canonical.com focal InRelease                       
Hit:15 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu focal InRelease   
Get:16 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,935 kB]
Hit:17 http://ppa.launchpad.net/rael-gc/rvm/ubuntu focal InRelease             
Get:18 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [685 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [278 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [677 kB]
Hit:21 http://ppa.launchpad.net/yubico/stable/ubuntu focal InRelease           
Get:22 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [40.7 kB]
Get:23 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [924 kB]
Hit:24 https://www.linux-projects.org/listing/uv4l_repo/xenial xenial InRelease
Get:25 http://archive.ubuntu.com/ubuntu focal-proposed/main amd64 DEP-11 Metadata [14.3 kB]
Get:26 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [390 kB]
Get:27 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:28 http://us.archive.ubuntu.com/ubuntu focal-backports/main amd64 DEP-11 Metadata [8,000 B]
Get:29 http://us.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [30.5 kB]
Get:30 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [66.6 kB]
Get:31 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [2,464 B]
Get:32 http://archive.ubuntu.com/ubuntu focal-proposed/universe amd64 DEP-11 Metadata [9,392 B]
Reading package lists... Done                                          
W: GPG error: https://pkgs.tailscale.com/stable/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 458CA832957F5868
E: The repository 'https://pkgs.tailscale.com/stable/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Got a working tailscale installation by installing the key the old-fashioned (now deprecated in favor of /usr/share/keyrings, I know) way: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 458CA832957F5868`, remove `[signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]` from `/etc/apt/sources.list.d/tailscale.list`  and then `sudo apt update && sudo apt install tailscale && sudo tailscale up`.

I wondered if my apt might be too old for the `[signed-by ...]` to be supported, but it seems to be up-to-date - apt 2.0.9 (amd64).

I thought maybe my version of apt didn't

### OS

Linux

### OS version

Ubuntu 20.04.4 LTS

### Tailscale version

n/a; install script at https://tailscale.com/install.sh. sha256 of that file is aa8635176892ffbcdbaf376bebc37149a5ab8e4486b8e7edfb5712228f54f51b

### Bug report

BUG-788174691d2b35f695ea581855ade8a9f05bc3365926eb2464415c76326b2704-20220623043704Z-fd8db6559696c246

**Comment by DentonGentry** [comment]
Was the server originally installed with an older Ubuntu and later updated to 20.04?
I'm struggling to figure out how its `apt` doesn't seem to be looking in `/usr/share/keyrings/`

**Comment by ismith** [comment]
No, it's an XPS 13, of an edition that shipped with 20.04. I do see other files written to `/usr/share/keyrings`, though I'm unsure if they're in use or not. (`ubuntu-*.gpg`, nothing that looks 3rd party or associated with a PPA.)

**Comment by TubbyCat** [comment]
what are the permissions on the actual gpg key in /usr/share/keyring ? 

ls -ll /usr/share/keyring
making the gpg key in question readable by others e.g. chmod 644 444 usually fixes this issue. 

please forgive me if I missed something

**Comment by wormstood** [comment]
hey there.
did you manage to solve that bug? i ran into it too

**Comment by cgevans** [comment]
What are the permissions on files in /usr/share/keyrings?  I ran into this because the script resulted in tailscale's keyring file being 640 and root.root, while everything else was 644.  Changing a+r on the tailscale file fixed the problem.

**Comment by wormstood** [comment]
Thanks for your Answers. I managed to solve the problem in the meantime by following this:  #4338 
My server has umask and i had to chmod the key: `chmod o+r tailscale-archive-keyring.gpg`

**Comment by gmlewis** [comment]
Yes, it looks readable by all:

$ ls -ll /usr/share/keyrings
total 48
-rw-r--r-- 1 root root 3116 May 26  2016 linuxmint-keyring.gpg
-rw-r--r-- 1 root root 2299 Jul  5 13:52
nvidia-container-toolkit-keyring.gpg
-rw-r--r-- 1 root root 2289 Jul 16 19:13 tailscale-archive-keyring.gpg
-rw-r--r-- 1 root root 7399 Sep 17  2018 ubuntu-archive-keyring.gpg
-rw-r--r-- 1 root root 6713 Oct 27  2016 ubuntu-archive-removed-keys.gpg
-rw-r--r-- 1 root root 4097 Feb  6  2018 ubuntu-cloudimage-keyring.gpg
-rw-r--r-- 1 root root    0 Jan 17  2018 ubuntu-cloudimage-removed-keys.gpg
-rw-r--r-- 1 root root 2483 Mar 29  2021 ubuntu-dbgsym-keyring.gpg
-rw-r--r-- 1 root root 1681 Feb  1  2018 ubuntu-dbgsym-removed-keys.gpg
-rw-r--r-- 1 root root 1227 May 27  2010 ubuntu-master-keyring.gpg

**Comment by ignasio** [comment]
ubuntu bionic can't fix 'apt-get update' broken

Err:10 https://pkgs.tailscale.com/stable/ubuntu bionic InRelease                                                                                  
  451  Unavailable For Legal Reasons [IP: 199.38.181.239 443]
Hit:9 https://packagecloud.io/ookla/speedtest-cli/ubuntu bionic InRelease
Reading package lists... Done
E: Failed to fetch https://pkgs.tailscale.com/stable/ubuntu/dists/bionic/InRelease  451  Unavailable For Legal Reasons [IP: 199.38.181.239 443]
E: The repository 'https://pkgs.tailscale.com/stable/ubuntu bionic InRelease' is no longer signed.

**Comment by sikala** [comment]
3 years on and this saved a plex lxc install thank you so much I was had missed removing the line from tailscale.list. for anyone else that encounters this you may need to also do the following first if gnupg is missing also

apt-get install gnupg

> Not a solve, but a workaround:
> 
> > Got a working tailscale installation by installing the key the old-fashioned (now deprecated in favor of /usr/share/keyrings, I know) way: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 458CA832957F5868`, remove `[signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]` from `/etc/apt/sources.list.d/tailscale.list` and then `sudo apt update && sudo apt install tailscale && sudo tailscale up`.
