### ISSUE TITLE
FR: Run non-Ephemeral docker container

### ISSUE THREAD

**Issue by jerrywoo96** [tailscale/tailscale#4913]
### What are you trying to do?

keep static tailscale ip and remain authorised after updating docker image.

### How should we solve this?

save tailscale configuration file so it does not need to re-authenticate again?

### What is the impact of not solving this?

unable to connect to device because ip has changed and needs re-authentication.

**Comment by jerrywoo96** [comment]
@DentonGentry I restarted the container, i checked the logs it requires re-authentication again.

Previously before restarting the container, i generated and used a pre-authorised non-ephemeral key to log in. It registers in the admin dashboard as non-ephemeral.

i followed this to map the /var/lib.
![image](https://user-images.githubusercontent.com/26324139/175480860-628e824e-b6e8-45bc-8d5e-72dc0d05d789.png)

These are the files that were generated after logging in.
![image](https://user-images.githubusercontent.com/26324139/175480968-3271e7e9-c358-4160-a518-4173f323783e.png)

This is my docker-compose
![image](https://user-images.githubusercontent.com/26324139/175479745-e9e40fec-cdd7-41f3-8417-1083d2dbee23.png)

**Comment by DentonGentry** [comment]
The files generated in /var/lib/tailscale: `tailscaled.log.conf`, `tailscaled.log1.txt`, `tailscaled.log2.txt`
There should be a `tailscaled.state` file, and that is the important one which holds the node's identity.

If you passed a `--state` or `--statedir` argument to tailscaled, that moves tailscaled.state to a different location. For this to work you'd probably want it to put its state in the default `/var/lib/tailscale`, by removing the `--state` or `--statedir` argument.

**Comment by jerrywoo96** [comment]
@DentonGentry Thanks for the info. It wasn't in the docker tailscale documentation, so i didn't know about it. i'll try it later.

**Comment by jerrywoo96** [comment]
@DentonGentry you stated that the tailscaled.state is stored in /var/lib/tailscale by default. i've mapped that directory in the container. so shouldn't it be inside? but it isnt somehow.

**Comment by DentonGentry** [comment]
There should be a `/var/lib/tailscale/tailscaled.state` file. If you passed a `--state` or `--statedir` argument to tailscaled, that moves tailscaled.state to a different location. For example a `--state=mem:` argument would store the state file only in memory.

**Comment by jerrywoo96** [comment]
@DentonGentry I did not specify any state switch or argument. must be a bug or something.

![image](https://user-images.githubusercontent.com/26324139/175854335-b31b3832-cabc-471c-8071-e0de24779102.png)

**Comment by ussjoin** [comment]
Had the same issue, annoyed the *heck* out of me, finally found the cause:

https://github.com/tailscale/tailscale/blob/main/docs/k8s/run.sh#L27-L31

Screenshot of `ps aux` inside the container showing that this code does indeed cause an automatic ephemeral container:
<img width="798" alt="Screen Shot 2022-07-16 at 10 01 39 PM" src="https://user-images.githubusercontent.com/32540/179384729-1b6e5171-4798-43f1-bdf7-4924ed257c11.png">

I would *strongly* suggest either (preferably) changing this default, or (if that ship has sailed, which, having dealt with Enterprise, I get!) at least documenting it.

@jerrywoo96 in the meantime, add an environment variable to your invocation of the container. I'm using docker compose, so mine looks like this:

```
...
  tailscaled:
    image: tailscale/tailscale
    hostname: calibre
    container_name: tailscaled
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscaledata:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
volumes:
  tailscaledata:

```

**Comment by DentonGentry** [comment]
Do you mean `--state=mem:`? run.sh doesn't have anywhere persistent to store its state unless it is told where to store it. I don't see a way to make it have persistent storage somewhere by default.

**Comment by jerrywoo96** [comment]
> Do you mean `--state=mem:`? run.sh doesn't have anywhere persistent to store its state unless it is told where to store it. I don't see a way to make it have persistent storage somewhere by default.

@DentonGentry 
I don't think you quite get it. The environment variable TS_STATE_DIR is not documented. There is no documentation on how make the state persistent after every tailscale image update. We want to store the state in a persistent storage on docker-compose up / docker run. We do not want to manually docker exec into the container every time to do a tailscale up --state/--statedir manually, after updating the tailscale image.

Thanks to @ussjoin , he found out we can actually store the state in a persistent storage using the docker environment variables without running tailscale up --state in the container every time after updating the tailscale image.

**Comment by jerrywoo96** [comment]
By specifying the TS_STATE_DIR environment variable, the state files are now stored in a persistent storage.

![image](https://user-images.githubusercontent.com/26324139/179390919-b48773b0-94f9-4ab2-af27-7ee2c3abcea6.png)

**Comment by jerrywoo96** [comment]
@ussjoin 
We are almost there. I recreated the container simulating a tailscale image update, but it failed to run the tailscale up command after i added more switches before updating.

![image](https://user-images.githubusercontent.com/26324139/179391387-bde70b43-7d95-41e4-a872-b2866d30cde8.png)

**Comment by ussjoin** [comment]
@DentonGentry The issue I see is that Tailscale documentation says "if you see that it's ephemeral and you aren't sure why, mount a Docker volume as the `/var/lib/tailscale` state directory and that'll fix it." What is undocumented (anywhere I can find, at least) is "unless you're using the Docker container we provide, in which case you need to pass an environment variable too." That's the issue that I think should *at least* be documented (honestly, a page on Docker-specific Tailscale stuff would just be great) if it can't be changed in its default.

@jerrywoo96 I'm not sure where you're going or what you're trying to achieve, so I can't assist you. My hope is just to suggest an improvement to the Tailscale documentation to help other weirdos trying to use persistent Docker Tailscale sidecars.

**Comment by DentonGentry** [comment]
> The environment variable TS_STATE_DIR is not documented. There is no documentation on how to make the state persistent after every tailscale image update.

TS_STATE_DIR and the other settings are now documented in https://hub.docker.com/r/tailscale/tailscale

**Comment by ussjoin** [comment]
Thanks, @DentonGentry! Much appreciated.

**Comment by DentonGentry** [comment]
Documentation was added to DockerHub.

**Comment by lucasrangit** [comment]
> Documentation was added to DockerHub.

Thanks @DentonGentry , although I think it could use more details. Such as from the `main.go`. It will make searching for the key terms possible. Otherwise, this ticket can continues to serve as documentation. 

```
//   - TS_STATE_DIR: the directory in which to store tailscaled
//     state. The data should persist across container
//     restarts.
```

**Comment by DentonGentry** [comment]
Added more detail to https://hub.docker.com/r/tailscale/tailscale
