### ISSUE TITLE
SSH doesn't work on Fedora due to SELinux policies

### ISSUE THREAD

**Issue by Will-W** [tailscale/tailscale#4914]
### What is the issue?

I set up tailscale ssh on a Fedora 36 machine. On attempting to connect I got "no shell: Permission denied".
If I run `sudo setenforce 0` on the machine then the connection completes succesfully.

This is the audit.log line that seems to be the relevant one:
type=AVC msg=audit(1655975587.820:2480): avc:  denied  { transition } for  pid=1205607 comm="login" path="/usr/bin/bash" dev="sda3" ino=3670141 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0 tclass=process permissive=0

### Steps to reproduce

Set up a fresh tailnet.
Install and authenticate on a Windows (client).
Install and authenticate on a Fedora 36 workstation (server). Installed via repo (sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo)
Run `tailscale up --ssh` on the server
Leave ACLs in the default state (see below)
Attempt ssh to the server tailscale IP from client machine
Receive error "no shell: Permission denied"
Run `setenforce 0`
Attempt ssh again - success.

### ACLs

	// Access control lists.
	"acls": [
		// Match absolutely everything.
		// Comment this section out if you want to define specific restrictions.
		{"action": "accept", "users": ["*"], "ports": ["*:*"]},
	],
	"ssh": [
		// Allow all users to SSH into their own devices in check mode.
		// Comment this section out if you want to define specific restrictions.
		{
			"action": "check",
			"src":    ["autogroup:members"],
			"dst":    ["autogroup:self"],
			"users":  ["autogroup:nonroot", "root"],
		},
	],

### OS

Linux, Windows

### OS version

Fedora 36

### Tailscale version

1.26.1

### Bug report

BUG-e1c84ada97960c4380fe78c1a607dd67d523dd072979008cfca69656fb546406-20220623093403Z-4d23d8e380d5d001

**Comment by bradfitz** [comment]
Thanks for the info! I'll reference this bug from the previous one, #4908.

**Comment by Will-W** [comment]
I did *try* to look for duplicates. Clearly not well!

Thanks :)
