### ISSUE TITLE
Make tailscale ssh work from local connection

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4923]
If we ssh to the tailscale ip address of the local machine, it gives us a regular OpenSSH connection rather than a Tailscale SSH connection. Can we have netstack interruption work for port 22 to grab locally generated SSH connections?

**Comment by DentonGentry** [comment]
This is probably not feasible: when Linux sees a connection to its own IP address it automatically turns it into a 127.0.0.1 loopback connection instead. tailscaled doesn't get involved.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/4475
