### ISSUE TITLE
Synology DSM7 Cant ping External (already ran steps)

### ISSUE THREAD

**Issue by nthomsonaus** [tailscale/tailscale#4928]
### What is the issue?

Installed either the 1.16 or the latest 1.26 and get the same result. 

sudo ping <<tailscale ip>> no response. When running tailscale status it shows two hosts like it should. tailscale is up and "working" as other machines in the network can communicate with the NAS, but the NAS cant communicate with anything in the tailscale network. 

ip route does not show a tailscale route, only the main route. 

Running: DSM 7.1-42661 Update 2
The only major thing is I have it installed on /volume2/ as /volume1/ doesn't exist.

I followed the steps in https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections and ran the following commands then restarted tailscale using the UI in DSM. 

udo setcap cap_net_admin+eip /var/packages/Tailscale/target/bin/tailscaled

sudo mkdir -p /dev/net
sudo mknod /dev/net/tun c 10 200
sudo chmod 0666 /dev/net/tun

BUG-2e591ffd8808b7d2b416d5e32107e920221359c0dcf36f5571d692741683f9d1-20220624225117Z-3800996985c31cbc

The devices tailscale ip is 100.103.23.57
fd7a:115c:a1e0:ab12:4843:cd96:6267:1739

### Steps to reproduce

sudo ping <<taIlscaleip>> no responses

### OS

Synology

### OS version

DSM 7.1-42661 Update 2

### Tailscale version

26.1-260017

### Bug report

BUG-2e591ffd8808b7d2b416d5e32107e920221359c0dcf36f5571d692741683f9d1-20220624225117Z-3800996985c31cbc

**Comment by DentonGentry** [comment]
On Tailscale-Synology builds past 1.22.x, we recommend this command:
sudo /var/packages/Tailscale/target/bin/tailscale configure-host
You can also then set that up in Task Manager to run automatically at boot (which doesn't need "sudo" since it runs as root)

**Comment by nthomsonaus** [comment]
Ran the sudo synosystemctl restart pkgctl-Tailscale.service and then sudo synosystemctl restart pkgctl-Tailscale.service

Same issues. New bugreport

BUG-2e591ffd8808b7d2b416d5e32107e920221359c0dcf36f5571d692741683f9d1-20220624230419Z-94409c3e74ca79c7

**Comment by DentonGentry** [comment]
The most recent program startup before the most recent bug report still says `--tun=userspace-networking`.

After running `sudo /var/packages/Tailscale/target/bin/tailscale configure-host` we'd expect it to start in TUN mode. Does /dev/net/tun exist?

**Comment by nthomsonaus** [comment]
Yes it exists. Thank you for helping me with this, starting to pull my hair out. Another Synology which should be roughly the same (apart from volume2) it all ran fine on. Created the interface etc.

sudo ls /dev/net/tun -ltr
crw-rw-rw- 1 root root 10, 200 Jun 25 08:38 /dev/net/tun

Stopped and started again (using DSM UI) just in case. New Bugreport - BUG-2e591ffd8808b7d2b416d5e32107e920221359c0dcf36f5571d692741683f9d1-20220624233519Z-2e1eeaa89c7d0435

**Comment by DentonGentry** [comment]
It is still starting up with `--tun=userspace-networking`, which means it isn't using /dev/net/tun and isn't going to be able to make outgoing connections from most of the Synology apps.

The start-stop-status script is https://github.com/tailscale/tailscale-synology/blob/main/src/scripts/start-stop-status. It doesn't know anything about volume1 or volume2, it uses the PKGVAR environment variable which DSM7 passes in.

I don't see a way that rebooting the Synology would help, but at this point I think it wouldn't hurt. Universal troubleshooting step, reboot it.

**Comment by nthomsonaus** [comment]
Unfortunately even with a reboot still the same issue. 

Cant seem to get it in to the correct tun mode, always has --tun=userspace-networking in the stdout log. 

BUG-2e591ffd8808b7d2b416d5e32107e920221359c0dcf36f5571d692741683f9d1-20220625074654Z-179551f59d006e66

Tried removing /dev/net/tun and /dev/net and re-running those steps. Same issue :(

At this stage I am looking at wiping the entire nas and starting fresh,  might have to wait so i can move data off to then move back.

**Comment by deviant77** [comment]
Check the permissions of `/dev/net/` by running `ls -ld /dev/net/`
If it's `drwx------` and the owner/group is `root` then Tailscale can't access `/dev/net/tun` because it doesn't run as root on DSM 7.

Do `chmod 755 /dev/net/` to make the directory `drwxr-xr-x` and restart Tailscale.

I hope you haven't wiped your NAS yet!

**Comment by nthomsonaus** [comment]
Thank you so much! was away for a week, saw this post, was excited to check / test. 

Arrived back, and it is now all working. 

A quick summary fro anyone else. 

It seems i had previously created /dev/net/ (maybe for docker?) as root. This meant that tailscale couldnt access the /dev/net/tun correctly and was starting in the wrong mode. 

root@FILES5:~# ls -ld /dev/net/
drwx------ 2 root root 60 Jun 25 17:42 /dev/net/
root@FILES5:~# chmod 755 /dev/net/
root@FILES5:~# ls -ld /dev/net/
drwxr-xr-x 2 root root 60 Jun 25 17:42 /dev/net/

root@FILES5:~# sudo ping 100.103.23.XX
PING 100.103.23.XX (100.103.23.XX) 56(84) bytes of data.
64 bytes from 100.103.23.XX: icmp_seq=1 ttl=64 time=0.042 ms

All fixed. Thank you again!

**Comment by rumblemumble** [comment]
sudo /var/packages/Tailscale/target/bin/tailscale configure-host
sudo chmod 755 /dev/net/
sudo synosystemctl restart pkgctl-Tailscale.service

the three steps above helped me on my Synology as well, but I have to reapply these after every boot.

I can see that the client is shown as online in Tailscale admin page, but can't ping/communicate between the DSM clients until the three steps are done.

**Comment by imonlygitting** [comment]
having problem hyper backup on original destination as well as new upgraded destination (have 1 => 2 site backups)
also ran above routine from Nov 15, 2022, and searched high and low  but seems hyper backup won't link up to destination:
![image](https://github.com/tailscale/tailscale/assets/57381651/66508af6-1a7f-4501-a46b-4d25bdda3d63)
one sign this is happening is the 'shared folder' menu does not allow me to make selection

all locations are running tailscale and main location and all set to exit node as well... everything worked perfectly last week so puzzled why ... any suggestions?

**Comment by antonselukh** [comment]
> sudo /var/packages/Tailscale/target/bin/tailscale configure-host
> sudo chmod 755 /dev/net/
> sudo synosystemctl restart pkgctl-Tailscale.service

Unfortunately, this resets during the restart of Synology NAS.

It was somewhat solved by the Tailscale team in documentation, [here](https://tailscale.com/kb/1131/synology#enable-outbound-connections), and there is also a description of why this happens and how a TUN Device is related to it.
