### ISSUE TITLE
MagicDNS search domain order changes

### ISSUE THREAD

**Issue by davidemyers** [tailscale/tailscale#4929]
### What is the issue?

This has happened to me twice so it might be easily reproducible.

On my Tailnet I have MagicDNS enabled with "Split DNS" configured and "Override local DNS" enabled.

When I create a new instance of Ubuntu Server 22.04 in an LXD container and install Tailscale, the `search` option in `/etc/resolv.conf` lists my domain first and the MagicDNS domain second. After a reboot or two the order switches and the MagicDNS domain comes before my domain (which I believe is the intended order). I have not seen the order switch back.

The output of `resolvectl` is the same regardless of which `search` domain comes first.

### OS

Linux

### OS version

Ubuntu Server 22.04

### Tailscale version

1.26.1

### Bug report

BUG-d16ecb4abc542d948797a3063b7aa1f2001064876d8fe05696d3d4bd7ee004f7-20220624233704Z-a6faa013e436899a

**Comment by davidemyers** [comment]
I just rebooted the physical server where I have three containers that are Tailscale clients and one of the three had my domain first while the other two had the MagicDNS domain first, so the issue is more random than I previously thought.

Toggling between `--accept-dns=false` and `--accept-dns=true` did not correct the issue, nor did toggling between `down` and `up`, but rebooting the instance worked.

**Comment by davidemyers** [comment]
Another data point. Looking at the logs, at startup Tailscale always tells `systemd-resolved` the correct search order, but it doesn't always end up that way in `/etc/resolv.conf`.

```
Jun 28 07:20:17 tailgate systemd-resolved[220]: tailscale0: Bus client set DNS server list to: 100.100.100.100
Jun 28 07:20:17 tailgate systemd-resolved[220]: tailscale0: Bus client set search domain list to: mydomain.com.beta.tailscale.net., mydomain.com., ~.
Jun 28 07:20:17 tailgate systemd-resolved[220]: tailscale0: Bus client set default route setting: yes
Jun 28 07:20:17 tailgate systemd-resolved[220]: tailscale0: Bus client set LLMNR setting: no
Jun 28 07:20:17 tailgate systemd-resolved[220]: tailscale0: Bus client set DNSSEC setting: no
Jun 28 07:20:17 tailgate systemd-resolved[220]: tailscale0: Bus client set DNSOverTLS setting: no
Jun 28 07:20:17 tailgate systemd-resolved[220]: Flushed all caches.
```

**Comment by davidemyers** [comment]
Yet another data point. As you can see in the screenshot below the search order can change simply by restarting `systemd-resolved`, so this doesn't look like a bug in Tailscale.

<img width="832" alt="Screen Shot 2022-07-23 at 9 38 27 AM" src="https://user-images.githubusercontent.com/26753976/180607675-dac6dfa5-7d9d-4fb1-adf7-c49a1f18e7d9.png">

**Comment by beningodfrey4** [comment]
Indeed it isn't. Quoting the [systemd-resolved.service](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Protocols%20and%20Routing) manpage at point 3 under Protocols and Routing:

> Queries for the address records (A and AAAA) of single-label non-synthesized names are resolved via unicast DNS using search domains. For any interface which defines search domains, such look-ups are routed to the servers defined for that interface, suffixed with each of those search domains. 

All search domains are tried in turn / parallel. Nothing to worry as the fastest response is cached anyway and would not lead to any noticeable delay. I've routinely seen the tailscale route preferred over my lan interface :smile:.

**Comment by sharvil** [comment]
Running into the same issue on Ubuntu 20.04.4. Also tracked it down to `systemd-resolved` dumping out the wrong search order in `resolv.conf`. I've verified that `systemd-resolved` has the correct order by a) checking the service logs; and b) by noticing discrepancy between the results of `resolvectl query` and `nslookup`.

I can also confirm that `systemd-resolved` wrote out a correct `resolv.conf` after a service restart.

**Comment by DentonGentry** [comment]
I think the conclusion is that the behaviors seen are `systemd-resolved`?

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Behaviors are `systemd-resolved`
