### ISSUE TITLE
Port forwarding over IPv6 fails

### ISSUE THREAD

**Issue by kroese** [tailscale/tailscale#4930]
### What is the issue?

When I port forward using firewalld/nftables to another Tailscale machine using its IPv4 address, it works fine.

When I do the same but with it's IPv6 address, the traffic doesn't arrive.

I can make a telnet connection to that Tailscale IPv6 and port just fine. So the destination is reachable. And I can also forward to non-Tailscale IPv6 addresses just fine. 

### Steps to reproduce

This works:

`sudo firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" forward-port port="80" protocol="tcp" to-port="80" to-addr="xxx.xxx.xxx.xxx"'`

This doesnt work:

`sudo firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv6" forward-port port="80" protocol="tcp" to-port="80" to-addr="xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx"'`

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.26.1

### Bug report

BUG-01f173494e22c373b404d5d60dd4e2ee695746f2882b0e5d821b48484d022dba-20220625044746Z-ab63dd5c29d4ff74

**Comment by DentonGentry** [comment]
Near the bugreport we see:
```
2022-06-25 05:38:34.352134644 +0200 +0200: [RATELIMIT] format("open-conn-track: flow TCP %v got RST by peer") (119 dropped)
2022-06-25 05:38:34.352353524 +0200 +0200: open-conn-track: flow TCP (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:60490 => [fd7a:115c:a1e0:ab12:w:x:y:z]:9735) got RST by peer
```

tailscaled never sends a TCP reset. I think it is hitting some other firewall rule which is blocking and sending an RST.

**Comment by DentonGentry** [comment]
`ip6tables -S` and `sudo ip6tables -L -v -n` maybe?

**Comment by DentonGentry** [comment]
We're not likely to make more progress, there is no visibility into what is sending the TCP Reset:
`2022-06-25 05:38:34.352134644 +0200 +0200: [RATELIMIT] format("open-conn-track: flow TCP %v got RST by peer") (119 dropped)`

Tailscale never sends a TCP RST. Something else is doing this.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Issue is related to whatever is sending the TCP Reset.
