### ISSUE TITLE
MagicDNS breaks if systemd-resolved.service starts after tailscaled.service holds /etc/resolv.conf

### ISSUE THREAD

**Issue by aofei** [tailscale/tailscale#4934]
### What is the issue?

Not able to `ping` [machine names or full domain names](https://tailscale.com/kb/1081/magicdns/#full-domain-names-vs-machine-names). And `resolvectl` reports that `tailscale0` doesn't have any DNS server nor DNS domain name. And no matter how many reboots the problem persists.

```bash
$ resolvectl
Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: foreign
  Current DNS Server: 8.8.8.8
         DNS Servers: 8.8.8.8 8.8.4.4
Fallback DNS Servers: 1.1.1.1 1.0.0.1

Link 2 (eth0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (tailscale0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

### Steps to reproduce

```bash
$ sudo systemctl stop tailscaled.service systemd-resolved.service
$ sudo rm /etc/resolv.conf
$ sudo systemctl start tailscaled.service
$ # Wait a second for /etc/resolv.conf to be generated by tailscaled.
$ sudo systemctl start systemd-resolved.service
```

### Are there any recent changes that introduced the issue?

Not sure.

### OS

Linux

### OS version

Arch Linux x86_64 with kernel 5.18.6-arch1-1

### Tailscale version

1.26.1

### Bug report

N/A

**Comment by aofei** [comment]
Here's a quick fix in case anyone is interested and stuck:

```bash
$ sudo rm /etc/resolv.conf
$ sudo ln -s /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
$ sudo systemctl restart systemd-resolved.service tailscaled.service
```

**Comment by bradfitz** [comment]
So is our `After=` line in `tailscaled.service` not sufficient? (https://github.com/tailscale/tailscale/blob/v1.26.1/cmd/tailscaled/tailscaled.service#L5)

/cc @danderson @Xe @twitchyliquid64

**Comment by aofei** [comment]
I don't know if it has something to do with the `After=` line. I had this problem because `systemd-resolved.service` was disabled on my machine (a GCE instance built using [this image](https://github.com/GoogleCloudPlatform/compute-archlinux-image-builder)) at first boot. Maybe not just my machine. I'm not sure, it seems that `systemd-resolved.service` is **disabled by default** in Arch Linux.

> To use systemd-resolved [start](https://wiki.archlinux.org/title/Start) and [enable](https://wiki.archlinux.org/title/Enable) systemd-resolved.service.
>
> -- https://wiki.archlinux.org/title/systemd-resolved

**Comment by DentonGentry** [comment]
I think this is another instance of https://github.com/tailscale/tailscale/issues/3956
