### ISSUE TITLE
Synology:Docker container is not reachable when using Host network (using MACVLAN)

### ISSUE THREAD

**Issue by yabdali** [tailscale/tailscale#4935]
### What is the issue?

Hi,
I have few docker containers which are attached to the host network, these containers are not reachable via tailscale. 
I am using tailscale latest package for Synology, I can reach the host (Synology DSM via 192.168.100.4:5000) but I can't reach containers attached to the network with the same IP but different port (example 192.168.100.4:9000). I can reach other network devices in the same subnet and other subnets (not hosted on Synology, example route:192.168.0.1). I have macvlan setup and all other containers that use the macvlan (separate IP addresses) with a link to route traffic are just working fine.

### Steps to reproduce

- Install tailscale for Synology (tailscale-x86_64-1.26.1-260017-dsm7.spk), configure and add routes, startup scripts, exit node etc..
- Create docker network type macvlan with IP range and auxiliary address, gateway.
- create a network interface with an IP address matching the auxiliary address, bring it up add route for docker network range to be routed through the link IP address
- Configure containers using the docker network (working fine)
- Configure containers (and run them) using the host network with a port exposed: with VPN I can access the containers connected to the host network, with tailscale I can not connect!

### OS

Synology

### OS version

Synology DSM 7

### Tailscale version

1.26

**Comment by DentonGentry** [comment]
Isn't this because the docker containers are listening on (for example) `172.17.0.1:9000`, not `192.168.100.4:9000` ?

**Comment by DentonGentry** [comment]
As stated earlier I believe this is due to the listen address of the container.

**Comment by nsar1907** [comment]
i have same problem, any news ?
