### ISSUE TITLE
ssh/tailssh: do setgroups on darwin properly

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4939]
See #4938 from @aeijdenberg.

There's a darwin-specific setgroups dance. See comments in https://opensource.apple.com/source/samba/samba-187.8/patches/support-darwin-initgroups-syscall.auto.html

https://github.com/tailscale/tailscale/commit/9294a14a376e44d68087af40c97918431073276a is a workaround but not the ideal fix.

**Comment by aeijdenberg** [comment]
Thanks @bradfitz , I'm still having a poke around - even with those other bits, I still don't have my use-case quite working.

e.g. I want the Mac to say things - this works:

```bash
$ ssh xxx@yyy
Last login: Sun Jun 26 15:25:32 on tty??
xxx@Adams-iMac ~ % say hi
# works, computer says "hi" out loud
```

This doesn't work:

```bash
$ ssh xxx@yyy say hi
Open speech channel failed: -915
exit status 1
```

Interestingly if I run `tailscaled` with `sudo tailscaled` (vs letting it start via Launchd), then frustratingly it does work again. There's clearly some cleverness re Mac login processes we need to overcome.

I'm going to have a play to see if running the command as: `/usr/bin/login -fpq xxx say hi`  will work, `man login` on Mac shows a 2nd form:

```
     login [-pq] [-h hostname] [user]
     login -f [-lpq] [-h hostname] [user [prog [args...]]]
```

(this is a fun weekend project - I can't pretend the use-case is important: https://github.com/continusec/timedcomputershutdown#timedcomputershutdown)

**Comment by DentonGentry** [comment]
Was this fixed by https://github.com/tailscale/tailscale/commit/0582829e00271a63c3abcb9e12700d9b223d386d ?

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/commit/0582829e00271a63c3abcb9e12700d9b223d386d
