### ISSUE TITLE
ssh: new session shows warning over setlocale

### ISSUE THREAD

**Issue by wilsonehusin** [tailscale/tailscale#4940]
### What is the issue?

I have set up Tailscale SSH on a headless machine running NixOS. I expect the behavior should be consistent / the same as regular SSH, but somehow a warning on setlocale seem to be present only when accessing through Tailscale SSH.

```bash
# Using Tailscale SSH
❯ ssh myheadlessmachine
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[wilson@myheadlessmachine] $

# Using local network
❯ ssh myheadlessmachine.lan
[wilson@myheadlessmachine] $
```

I have a fairly vanilla configuration of NixOS, although I am on unstable channel. It is likely that this is misconfiguration on my part, though I'm somewhat lost on where to troubleshoot as I don't manually override locales.

One thing that I happen to notice is that the environment variables between Tailscale SSH session are different from the regular session, specifically:

- `TMUX_TMPDIR` seem unevaluated on Tailscale session
- `XDG_*` variables are missing

(other expected diffs such as TTY numbers were omitted)

```
❯ diff /tmp/env.lan /tmp/env.tailscale
12,13d11
< LOGNAME=wilson
< XDG_SESSION_TYPE=tty
20c18
< TMUX_TMPDIR=/run/user/1000
---
> TMUX_TMPDIR=/run/user/$(id -u)
28d25
< XDG_SESSION_CLASS=user
38d34
< XDG_SESSION_ID=8
43d39
< XDG_RUNTIME_DIR=/run/user/1000
```

Any clues on what is happening / where I should look into? Thank you!

### Steps to reproduce

SSH over Tailscale to a Linux machine.

### Are there any recent changes that introduced the issue?

Regular OS update (NixOS unstable) and enabling Tailscale SSH.

### OS

Linux

### OS version

NixOS Unstable (Linux 5.18.6)

### Tailscale version

1.26.1

### Bug report

BUG-4d2f413a5dc3267728a94b3e5cfeb9fc698ebde70f1f6be9a9e7dd7524fbad7e-20220626064538Z-b7ec9892db34f246

**Comment by matshch** [comment]
The same issue is present on NixOS 22.05 with Tailscale 1.24.2:
```
[matshch@Artem-HP:~]$ ssh artem-pc
bash: warning: setlocale: LC_NUMERIC: cannot change locale (ru_RU.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (ru_RU.UTF-8): No such file or directory

[matshch@Artem-PC:~]$ 
```

**Comment by maisem** [comment]
The Tailscale NixOS package is missing a few dependencies (namely `getent` and `shadow`) so it's not able to configure the user env correctly. Potential upstream fix https://github.com/NixOS/nixpkgs/pull/180364

**Comment by wilsonehusin** [comment]
I think the fix worked! Thanks @maisem
