### ISSUE TITLE
Lots and lots of wintun connections

### ISSUE THREAD

**Issue by raggi** [tailscale/tailscale#4944]
### What is the issue?

I wasn't getting any internet in my WSL today. I just started trying to diagnose that, and found this:

![image](https://user-images.githubusercontent.com/348/175835107-3ccd4cee-29c8-4bbb-9639-f06c803b5755.png)

### Steps to reproduce

Unclear so far. This might be related to local dev builds.

### OS version

Windows 11

**Comment by raggi** [comment]
Helpful snippet for removing the excess objects:

```
Get-PnpDevice  | Where-Object { $_.Description -like "Wintun*" } | foreach { pnputil /remove-device $_.InstanceId; }
```

**Comment by bradfitz** [comment]
When you filed this, I thought it was from the person who'd just tweeted the same image: https://twitter.com/pastaraspberry/status/1540798608051957761

**Comment by cepera-ang** [comment]
I’m the guy from twitter. My interfaces appeared after something with windows, (updates, maybe) and I tried to update Tailscale to 1.26.1 which was the last version at the time. After that Tailscale stopped working (icon in the tray disappeared after click). I haven’t time to diagnose and just left it as is and discovered flood of wintun adapters several days later.

**Comment by cepera-ang** [comment]
After running the helpful snipped above (thanks, @raggi) Tailscale managed to create another interface and now working fine and all happen even without restart. Looks like hitting the infinite wintun creation somewhere in the code limited by maximum number of adapters in system (looks like 256 is the limit).

**Comment by dblohm7** [comment]
Closing this as a dup in favour of https://github.com/tailscale/tailscale/issues/5678 (there's more info in there).
