### ISSUE TITLE
[ios][1.26.1] bug reporter doesnt work when tailscale is stuck in Loading

### ISSUE THREAD

**Issue by wizzard0** [tailscale/tailscale#4947]
### What is the issue?

**What happened?**

1. Tried to 'send a bug report' when #3439 was occurring on my iPhone (app stuck in Loading... state)
2. Observed the 'Your bug report could not be sent at this time, please try again later' message
3. Verified that I have internet access, toggled airplane mode, wifi, cellular, restarted the app, restarted the iphone, tried to collect logs via Console.app, to click Reathenticate, reset network settings, etc
4. After `reset privacy settings` > another iphone reboot the app started working and then the Bug report button also worked. See
`BUG-58df9986f60469daad2a3c5ce62915a61221dd1d8660188427285b4bb3929ac9-20220627070845Z-b5dc4cc01515a148`

**What did you expect to happen?**

Bug report button works/breaks independently from main app

### Steps to reproduce

0. Observed #3439
1. Confirmed via ifconfig.co that both wifi and cellular connections are working
2. Confirmed that openvpn and speedify work fine too.
3. Confirmed that my laptop can connect to my tailnet from the same wifi
4. Tried to 'send a bug report' when #3439 was occurring on my iPhone (app stuck in Loading... state)
5. Tried to toggle/reset various network-related settings. The app did not connect after `reset network settings` + reboot, but did connect after `reset privacy settings` + reboot.

### Are there any recent changes that introduced the issue?

Updated to 1.26.1
Used an exit node

### OS

iOS

### OS version

iOS 15.5 on iPhone 11 Pro Max

### Tailscale version

1.26.1

### Bug report

BUG-58df9986f60469daad2a3c5ce62915a61221dd1d8660188427285b4bb3929ac9-20220627070845Z-b5dc4cc01515a148

**Comment by DentonGentry** [comment]
To set expectations: getting some of the app functions to work while the app is stuck is not likely to succeed.

**Comment by mihaip** [comment]
While we can't make the bug report functionality work in all states, we can still do a better job of disabling it when it can't do anything, and make sure that it handles all error code paths. Will take a look at this.

**Comment by wizzard0** [comment]
> getting some of the app functions to work while the app is stuck is not likely to succeed

Umm… I don’t know what’s so special about your bug report function that ties it with other app functionality but it seems wrong. 

Shouldn’t the bug reporter be as separate as possible? I mean, the whole point of a bug reporter is to work when a bug occurs i.e. an app is /not/ working 🤷🏼

**Comment by DentonGentry** [comment]
> Umm… I don’t know what’s so special about your bug report function that ties it with other app functionality but it seems wrong.

In most cases the bugs people are interested in are with connectivity: cannot reach a node, throughput is slow, connections are relayed not direct, DNS issues, etc. The bugreport function puts a marker into the telemetry the app sends about its connectivity. If the app isn't working at all and has no connectivity, the telemetry is often not working either.

For App-specific bugs like it crashes or glitches, we use the normal reporting framework in iOS and Android which works whether the rest of the app is working or not. This is fine, but is not what people most often want to report.

**Comment by mihaip** [comment]
Starting with version 1.28 the bug report command will be disabled in cases where we cannot send the data.
