### ISSUE TITLE
Taildrop into macOS machine doesn't work

### ISSUE THREAD

**Issue by wizzard0** [tailscale/tailscale#4948]
### What is the issue?

1. Clicked 'share' > tailscale on iOS
2. Selected my laptop as the target
3. Observed the red exclamation mark and the error message 'reconnect (laptop) to Tailscale and try again'.
4. UPD: from Win10 to macOS: 
```An error was encountered transferring the file:

Put "http://****:56019/v0/put/****": dial tcp ****:56019: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**What did you expect to happen?**
Some activity on macOS machine (never tried to receive files on the laptop previously, only send 'from' the laptop)

Also, W10 doesn't show the error immediately but only about ~1min after the progress bar silently disappears.

### Steps to reproduce

1. Tried to receive files on the laptop (sending from laptop works)

Bugreport from iOS after retrying: `BUG-58df9986f60469daad2a3c5ce62915a61221dd1d8660188427285b4bb3929ac9-20220627074338Z-af42d66ba501eb62`
Bugreport from macOS: `zsh: command not found: tailscale` / `BUG-01e231b7ce2898b4f72dea4c2a81009184af47707215e2bf3bb67c88f7e4d9d0-20220627131513Z-1b08eb8d86538f5d
` from menu
Bugreport from Win10: `BUG-0a35d92e273576351d405240bcc44be71baa9750c59571e57c70f39d069b2ba9-20220627075259Z-e73cfb2adfe7fe12`

### Are there any recent changes that introduced the issue?

No changes. Never tried to receive files on the laptop previously.

### OS

macOS, iOS, Win10

### OS version

Monterey 12.0.1 (21A559); iOS 15.5; Win10 x64 21H1

### Tailscale version

1.26.0 App Store laptop, 1.26.1 mobile, 1.24.2 w10

### Bug report

zsh: command not found: tailscale
from menu:
```
BUG-01e231b7ce2898b4f72dea4c2a81009184af47707215e2bf3bb67c88f7e4d9d0-20220627131513Z-1b08eb8d86538f5d
```

**Comment by DentonGentry** [comment]
Shortly before the bugreport we see something weird in telemetry:
```
2022-06-27 16:15:10.714749 +0300 +0300: magicsock: disco: failed to send *disco.Ping to 136.243.x.y:50237: write udp4 0.0.0.0:41641->136.243.4.48:50237: sendto: operation not permitted
2022-06-27 16:15:10.824121 +0300 +0300: magicsock: disco: failed to send *disco.Ping to 136.243.x.y:50237: write udp4 0.0.0.0:41641->136.243.4.48:50237: sendto: operation not permitted
```

It is sending from source address `0.0.0.0`? I haven't seen that in telemetry before.

**Comment by DentonGentry** [comment]
If this is still happening, we'd need a fresh bugreport shortly after attempting taildrop.

**Comment by DentonGentry** [comment]
At this point I do not expect to diagnose the original issue from a year ago. If it happens again please reopen the bug with a fresh bugreport.

**Comment by pycke** [comment]
I experience the same issue. Taildrop from my MacMini desktop to MacBook Air does NOT work. Taildrop from MacMini to other machines works. Taildrop from MacBook Air to MacMini (and to all other machines) work. Both Macs use same OS (venture 14.0) and after some checking I cannot find any difference in OS configuration/settings. Also same version of Tailscale on both machines 1.50.1. Any ideas what I could check / investigate ?

**Comment by DentonGentry** [comment]
Please open a new issue and include a Tailscale bugreport — hold the option key while selecting the Tailscale icon in the menubar and choose Debug > bugreport.

Please generate the bugreport shortly after attempting to taildrop a file.

I'm going to lock this issue for further comments, we generally don't notice when a closed issue is commented upon.
