### ISSUE TITLE
Taildrop transfer speeds reduced to half in 1.26.1 compared to 1.24.2

### ISSUE THREAD

**Issue by d5aqoep** [tailscale/tailscale#4949]
### What is the issue?

Earlier, I used to get 300 Mbps transfer speeds between two PCs on 1.24.2. This was maxing out my connection. But once I upgraded to 1.26 and 1.26.1, transfer speeds took a hit and are inconsistent. They keep fluctuating between 50 Mbps to 150 Mbps. 

Downgrading back to 1.24.2 fixed the transfer speed issue.

### Steps to reproduce

Mentioned above

### Are there any recent changes that introduced the issue?

Upgrading to 1.26 caused this issue.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.26.1

### Bug report

On 1.24.2
BUG-5305aedbbbc9255b23e09fc7293f6fc49d88997cfac2f0db7c6e97013ac6fe27-20220628033322Z-b205959ff5e208cb

On 1.26.1
BUG-5305aedbbbc9255b23e09fc7293f6fc49d88997cfac2f0db7c6e97013ac6fe27-20220628033441Z-ca9da69afabbaaeb

**Comment by d5aqoep** [comment]
Can you guide me how to generate a bug report for this issue?

**Comment by DentonGentry** [comment]
Ideally:
- reboot or restart the Tailscale service. The things we need to look at would be at startup of the service.
- hold shift and right-click on the Tailscale icon in the taskbar. There will be a Debug menu item, with a bugreport selection.

**Comment by d5aqoep** [comment]
On 1.24.2
BUG-5305aedbbbc9255b23e09fc7293f6fc49d88997cfac2f0db7c6e97013ac6fe27-20220628033322Z-b205959ff5e208cb

On 1.26.1
BUG-5305aedbbbc9255b23e09fc7293f6fc49d88997cfac2f0db7c6e97013ac6fe27-20220628033441Z-ca9da69afabbaaeb

**Comment by d5aqoep** [comment]
Hello any progress on this issue?

**Comment by DentonGentry** [comment]
On 1.24.2:
```
2022-06-28 09:03:16.0761527 +0530 +0530: peerapi: serving on http://100.96.x.y:58620
2022-06-28 09:03:16.0761527 +0530 +0530: peerapi: serving on http://[fd7a:115c:a1e0:ab12:q:r:s:t]:58620
```

On 1.26.1:
```
2022-06-28 09:04:34.6152837 +0530 +0530: peerapi: serving on http://100.96.x.y:58620
2022-06-28 09:04:34.6157839 +0530 +0530: peerapi: serving on http://[fd7a:115c:a1e0:ab12:q:r:s:t]:58620
```

I think this means both are using the Windows stack not netstack, if I understood it correctly netstack would always bind to port 1.

**Comment by d5aqoep** [comment]
But why is there a reduction in speed on 1.26.1 ?

**Comment by DentonGentry** [comment]
I make notes on findings as we go along. I understand that you want an answer.

**Comment by bradfitz** [comment]
I'm pretty sure the netstack path happens regardless on windows, independent of what the listen was able to do. This lets us avoid aggressive firewalls etc.

But we've done that for several releases IIRC so that wouldn't explain speed changes.

**Comment by DentonGentry** [comment]
In Tailscale releases prior to 1.32.1, the netstack implementation did not handle TCP selective acknowledgement and suffered large performance loss from moderate packet loss. Release 1.32.1 and later substantially improves netstack throughput.

**Comment by d5aqoep** [comment]
What I am seeing is from 1.32.1 on wards, transfer speed maxes my 300Mbps connection for 5 seconds, then drops to 10 Mbps for 2 seconds then again jumps to 300 Mbps for another 5 seconds then again drops to 10 Mbps. It's not a continuous stable transfer speed.

**Comment by bradfitz** [comment]
Closing this as done, assuming this was the SACK issue.

Plenty of other meta issues track performance overall, notably #414.
