### ISSUE TITLE
FR: add Member authkeys

### ISSUE THREAD

**Issue by dunmatt** [tailscale/tailscale#4951]
### What are you trying to do?

We make autonomous lawnmowers, which means we (will) have assembly lines for getting them built.  So the idea is that the assembly line / provisioning laptops are all tagged the same, and that tag has tagOwner for the mower tag.  That way the assembly techs don't get admin access to our tailnet, but they can still add mowers to it.  

The trouble is, in Jay Stapleton's words, "Only administrators can generate auth keys."

### How should we solve this?

Ideally for me there would be a Member level API, so calls to the API coming from a machine with a given tag can create auth keys for tags which they are tagOwner of.

### What is the impact of not solving this?

Right now I'm just starting to work around it, but it's seeming like the best approach is going to be spinning up a web service whose backend gets an admin API key and whose only job is to request and return tagged auth keys, and to allow only provisioning laptops to route to it.

### Anything else?

Our firmware guy has to remote into windows machines in various parts of the country, and he comments on how much he loves Tailscale something like once a week.  Keep up the great work!

**Comment by DentonGentry** [comment]
You're looking to generate an authkey which carries tags, allowing the contract manufacturer to use it within the factory. The authkey is a string, and one doesn't have to be logged in as the admin account to use the authkey to authenticate a device.

I guess I don't understand why having an admin generate the authkey for the factory is not workable. Why is it important that a non-admin User be able to generate an authkey?

**Comment by dunmatt** [comment]
... ah.  It's because when I was first reading the docs I saw the warning to "Be very careful with reusable keys!" my brain interpreted it as "then there's no reason to remember about reusable keys", but now that you point it out that does seem to be a much simpler solution, thank you!
