### ISSUE TITLE
FR: Support manually adding endpoints

### ISSUE THREAD

**Issue by ceballosiker** [tailscale/tailscale#4958]
### What are you trying to do?

I'm not sure if this is already possible. If so please let me know how to do it!

I'm trying to connect two Tailscale devices through a private network.
The private network has UDP ports open where Tailscale could try to setup a direct channel, however the address of the server in this network does not appear on the Endpoints list, and so Tailscale doesn't even try to reach through it.

I'd like to be able to manually add these IPs to the devices Endpoints list and force Tailscale to try that endpoint if the rest fail.

![screenshot](https://user-images.githubusercontent.com/31108511/176177029-37a4d7df-0022-4ebd-bdff-ae4e92b06f31.jpg)

### How should we solve this?

Add an option to manually include endpoints you'd like your device to advertise.
So other nodes on your Tailscale network can try that endpoint if they get no response on the usual ones.

### What is the impact of not solving this?

Right now if the private network is not identified by Tailscale and not added to the device's endpoints, all communication will go through a DERP relay.

**Comment by DentonGentry** [comment]
I'd be interested in helping it automatically figure out that those endpoints exist. tailscaled sends STUN packets (UDP packets on port 3478) to our own DERP servers. After the STUN packets go through NAT, the DERP server receives the public IP address of the node and can send back a response telling the node what its public IP address is.

Do you know of a reason why UDP port 3478 might not be making it through?

**Comment by DentonGentry** [comment]
I imagine the solution we want to pursue is advertising the IP addresses of all interfaces as endpoints, not just the interface with the default route as tailscaled currently does.

This comes up in cloud environments where there is often one address with the default route (often with a non-routable address like 169.254.x.y and NATed to the outside world), and an entirely separate interface with a private IP address on a VPC within the cloud provider.

**Comment by danderson** [comment]
We already do this though, endpoints are already the list of all possible addresses on all interfaces. The only case where this wouldn't work is if the private IP is somehow unknown to the node, but I don't think that's the case on clouds or in the original report.

@ceballosiker Can you describe your network topology more? We already exchange all potentially workable addresses on all interfaces for peers to try, so I'm not understanding why you would need to do anything manual.
