### ISSUE TITLE
FR: Support for Android 4

### ISSUE THREAD

**Issue by davidhaley** [tailscale/tailscale#4964]
We have client devices that run Android 4 (Zebra TC8000 / Zebra TC70), and I am wondering if it possible to support this.

It looks like support for Android 5.1 was added back in in 2020, here: https://github.com/tailscale/tailscale/issues/577

**Comment by bradfitz** [comment]
Anything's possible for a large enough sum of money!

I'm guessing you'd be much better off using said sum of money to upgrade your devices to ones that still get security updates.

**Comment by bradfitz** [comment]
Also, if you're unaware, the Tailscale Android client is open source and pretty easy to build: https://github.com/tailscale/tailscale-android

So even if it's not a priority for us, you or somebody at your organization might be able to do it.

**Comment by DentonGentry** [comment]
Zebra TC8000 apparently runs Android 4.4.3. Making this change in https://github.com/tailscale/tailscale-android/blob/main/android/build.gradle

```
$ git diff
diff --git a/android/build.gradle b/android/build.gradle
index fda7dcb..6c20694 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -24,7 +24,7 @@ android {
     ndkVersion "23.1.7779620"
     compileSdkVersion 30
     defaultConfig {
-        minSdkVersion 22
+        minSdkVersion 19
         targetSdkVersion 30
         versionCode 107
         versionName "1.27.24-t467eb2eca-g0c11377ca10"
```

Fails to build due to `androidx.security:security-crypto`, which apparently doesn't exist prior to Android 5.1.

```
$ make tailscale-debug.apk
> Task :processPlayDebugMainManifest FAILED
/home/dgentry/Documents/Code/tailscale/tailscale-android/android/src/main/AndroidManifest.xml Warning:
        Package name 'com.tailscale.ipn' used in: AndroidManifest.xml, :ipn:.
/home/dgentry/Documents/Code/tailscale/tailscale-android/android/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [androidx.security:security-crypto:1.1.0-alpha03] /home/dgentry/.gradle/caches/transforms-2/files-2.1/126274d2267db3229ff8446325c7b35c/security-crypto-1.1.0-alpha03/AndroidManifest.xml as the library might be using APIs not available in 19
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.
```

**Comment by davidhaley** [comment]
> If I recall, we had a good reason to support Android 5.1 for #577, even though it was only 4% of the market at the time. Android 5.1 is down to 1.5% at this point. Android 4's so old I can't even find usage stats. Last security update was over 4 or 5 years ago?
> 
> Is there a good story at least about the Android 4 devices?

@bradfitz, thank you very much for the reply. Our customer is phasing them out (although not as quickly as we would like).



> Zebra TC8000 apparently runs Android 4.4.3. Making this change in https://github.com/tailscale/tailscale-android/blob/main/android/build.gradle
> 
> ```
> $ git diff
> diff --git a/android/build.gradle b/android/build.gradle
> index fda7dcb..6c20694 100644
> --- a/android/build.gradle
> +++ b/android/build.gradle
> @@ -24,7 +24,7 @@ android {
>      ndkVersion "23.1.7779620"
>      compileSdkVersion 30
>      defaultConfig {
> -        minSdkVersion 22
> +        minSdkVersion 19
>          targetSdkVersion 30
>          versionCode 107
>          versionName "1.27.24-t467eb2eca-g0c11377ca10"
> ```
> 
> Fails to build due to `androidx.security:security-crypto`, which apparently doesn't exist prior to Android 5.1.
> 
> ```
> $ make tailscale-debug.apk
> > Task :processPlayDebugMainManifest FAILED
> /home/dgentry/Documents/Code/tailscale/tailscale-android/android/src/main/AndroidManifest.xml Warning:
>         Package name 'com.tailscale.ipn' used in: AndroidManifest.xml, :ipn:.
> /home/dgentry/Documents/Code/tailscale/tailscale-android/android/src/main/AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [androidx.security:security-crypto:1.1.0-alpha03] /home/dgentry/.gradle/caches/transforms-2/files-2.1/126274d2267db3229ff8446325c7b35c/security-crypto-1.1.0-alpha03/AndroidManifest.xml as the library might be using APIs not available in 19
>         Suggestion: use a compatible library with a minSdk of at most 19,
>                 or increase this project's minSdk version to at least 21,
>                 or use tools:overrideLibrary="androidx.security" to force usage (may lead to runtime failures)
> 
> FAILURE: Build failed with an exception.
> ```

@DentonGentry, that is unfortunate. Thank you very much for discovering that.

**Comment by bradfitz** [comment]
I don't think we always used androidx.security:security-crypto though. IIRC that's just for storing keys better. Previously we just stored them on disk. You can probably just revert that old commit.

**Comment by bradfitz** [comment]
> I don't think we always used androidx.security:security-crypto though. IIRC that's just for storing keys better. Previously we just stored them on disk. You can probably just revert that old commit.

Nevermind, I was thinking about https://github.com/tailscale/tailscale-android/commit/39cb01da425bb001036b847e59dbab46be3cc8dc which moved from midSdkVersion 23 to 22. The repo's first commit started at minSdkVersion 23.

But you could probably just rip that out and use normal SharedPreferences rather than EncryptedSharedPreferences.

**Comment by DentonGentry** [comment]
Closing as not feasible, I don't think we want to reimplement the app to not use `androidx.security:security-crypto`
