### ISSUE TITLE
FR: Advertise Tailscale SSH on the host via Tailscale web 

### ISSUE THREAD

**Issue by mlangenberg** [tailscale/tailscale#4966]
### What are you trying to do?

I'm trying to use Tailscale SSH on my Synology NAS and Home Assistant box using the packages available for those platforms. As I am unable to control the parameters to `tailscale up`, I can't run `tailscale up --ssh` to advertise Tailscale SSH on these hosts.   

### How should we solve this?

Both the Synology and Home Assistant packages already offer an easy way to visit the built-in `tailscale web` server to control the `tailscaled` daemon. Currently this only allows me to start or stop advertising this host as exit node.

I would expect to advertise Tailscale SSH by pressing a button in the `tailscale web` interface.

### What is the impact of not solving this?

A workaround could be to modify both the Synology and the Home Assistant packages to pass arbitrary command line options to `tailscale up`, but that can easily lead to configuration errors and broken installations.

As there is already a fully functional web interface that allows control of the `tailscaled` daemon, extending this page seems the appropriate place for me.

Personally, for now I'll just stay using 'regular' SSH keys to access these hosts.

### Anything else?

With Tailscale SSH being a beta feature, we might not want to prominently display this on the Tailscale web server. But, this could be indicated in the copy or hidden behind a checkbox (with other beta features) so people who are interested in Tailscale SSH could at least try it out.

**Comment by KevinCathcart** [comment]
While conceptually I don't mind the idea of `tailscale web` exposing some form of toggle for this, I will say that for the Home Assistant (OS/Supervisor) Community add-on, it won't do what you want.

The Home Assistant add-on runs in a separate container, and it does not have access to everything set up like the SSH add-ons do. While theoretically @frenck could set the add-on up in that way, I'm guessing he would prefer not to. 

I'm not familiar enough with the Synology packaging to know if things are similar there, or if it actually runs in the correct environment for running an SSH server.

**Comment by DentonGentry** [comment]
On a Synology DSM7 system, attempting to use Tailscale SSH fails with "can't switch user" because tailscaled does not run as root on that platform. `tailscale up --ssh` is not implemented for Synology systems, and to be honest I doubt there will be a way to do so without being root.

**Comment by mlangenberg** [comment]
@KevinCathcart clearly I had the wrong mental model of how Tailscale integrates on Synology and Home Assistant. Thank you for pointing that out. Since I am able to connect to 'regular' SSH over the Tailscale network, even though Tailscale is running in a container, I simply assumed Tailscale SSH would allow me to do the same, but without manually managing SSH keys.

Now that I know that this will not be the case, this feature request is no longer relevant to me. I will close this issue and expect it to be reopened if someone finds any real world benefits of implementing it.
