### ISSUE TITLE
dns: add AWS DNS support 

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4980]
Like #4911/#4979 did for GCP, we could also add AWS support:

https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html

> The Amazon DNS server does not reside within a specific subnet or Availability Zone in a VPC. It's located at the address 169.254.169.253 (and the reserved IP address at the base of the VPC IPv4 network range, plus two) and fd00:ec2::253. For example, the Amazon DNS Server on a 10.0.0.0/16 network is located at 10.0.0.2. For VPCs with multiple IPv4 CIDR blocks, the DNS server IP address is located in the primary CIDR block.

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver.html

> When you create a VPC using Amazon VPC, Route 53 Resolver automatically uses a Resolver on the VPC to answer DNS queries for local Amazon VPC domain names for EC2 instances (ec2-192-0-2-44.compute-1.amazonaws.com) and records in private hosted zones (acme.example.com). For all other domain names, Resolver performs recursive lookups against public name servers.
>
> When you create a VPC, the Route 53 Resolver that is created by default, maps to a DNS server that runs on a reserved IP address for the VPC network range, plus 2. For example, the DNS Server on a 10.0.0.0/16 network is located at 10.0.0.2.

/cc @maisem

**Comment by bradfitz** [comment]
Misc notes:

```
$ TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN"  http://169.254.169.254/latest/meta-data/
```

**Comment by bradfitz** [comment]
EC2 also uses *.internal:

```
$ dig +short @169.254.169.253 i-005f5598a44594cd9.us-west-2.compute.internal
172.31.32.100
```

**Comment by danielcompton** [comment]
Do the DNS changes here change the recommendations for https://tailscale.com/kb/1141/aws-rds/#step-3-add-aws-dns-for-your-tailnet?

**Comment by DentonGentry** [comment]
That recommendation allows other tailscale nodes outside of AWS to access the VPC private names and IP addresses within AWS.

This PR makes the nodes within AWS add Amazon's DNS servers locally, which some AWS services require (like NFS mounting of EBS). This PR does not make AWS DNS servers available to the rest of the tailnet.
