### ISSUE TITLE
net/dns: rework how GCP DNS fallback for *.internal works

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4981]
As I went to do the AWS variant, I realized the fix in #4979 for #4911 for GCP is probably not ideal.

The GCP VM I was testing on (the default from their instance creation wizard) doesn't have systemd-resolved, so I was using Tailscale's DNS direct mode for testing.

But my AWS vanilla VM does have systemd-resolved, and I realize we don't want to register an explicit `*.internal` split DNS route with systemd-resolved if one already exists.

The change in #4979 on a machine with systemd-resolved will add a new *.internal route to 100.100.100.100 (which will then proxy to the right place) rather than just hitting the right place directly (well, from systemd-resolved).

I think instead we just want to modify the forwarder code to pretend it had a *.internal route there, but never actually tell the DNS Manager & OSConfigurator about it.

Thoughts, @danderson?

**Comment by danderson** [comment]
Hmm. I could mostly go either way. The extra indirection for resolved users isn't ideal, but also not terrible. On the flip side, putting more magic in the forwarder means you can no longer get a complete picture of how DNS is being configured purely from the 3 DNS config structs that the manager manipulates, which is a nice property of the thing as it exists today.

So... eh? I don't think I particularly care either way, both are kinda sub-optimal in their own way.

**Comment by bradfitz** [comment]
See what you think of https://github.com/tailscale/tailscale/pull/4982

> On the flip side, putting more magic in the forwarder means you can no longer get a complete picture of how DNS is being configured purely from the 3 DNS config structs that the manager manipulates, which is a nice property of the thing as it exists today.

Well, we also didn't quite have that property with the change as-submitted.

We could make a new dns.Config field for that, though, and make sure it stringifies in the log prints?

**Comment by danderson** [comment]
The change as-submitted adds a route to the high-level intent config, so it doesn't exactly match what control sent, but it does match the "compiled" forwarder/OS configs, and fully describes how we expect tailscaled+OS to behave with that config. That's the property I'm somewhat (not hugely) worried about losing, because it makes debugging DNS complaints harder if you have to remember a bunch of exceptions to what the logs say.

Looking at PR shortly.

**Comment by danderson** [comment]
nvm, I see what you meant by it not always being as I wanted it already, I forgot about the bit of fallthrough logic in forwarder.go.
