### ISSUE TITLE
net/dns: add Azure DNS support

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4983]
Like GCP (#4911) and AWS (#4980), also do Azure-specific DNS stuff.

Notes:
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances

> Access to the recursive resolvers in Azure is provided via the virtual IP 168.63.129.16.

And looks like the suffix is `.internal.cloudapp.net` ?

**Comment by DentonGentry** [comment]
I think https://github.com/tailscale/tailscale/pull/4986 implemented this.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/4986
