### ISSUE TITLE
FR: Expose --socks5-server , --outbound-http-proxy-listen flags in run.sh used in entrypoint for Docker container

### ISSUE THREAD

**Issue by rodrigc** [tailscale/tailscale#4985]
### What are you trying to do?

In https://tailscale.com/kb/1112/userspace-networking/ ,
these two tailscaled flags are documented:

--socks5-server
--outbound-http-proxy-listen

It would be nice if these flags could be exposed in the run.sh used as the entrypoint for the tailscale docker container.

### How should we solve this?

This would allow using tailscale over a socks5 or http proxy , in more restrictive container environments
where creating a tun device is not possible.

**Comment by maisem** [comment]
You should be able to use TS_EXTRA_ARGS for this, no?

**Comment by maisem** [comment]
Oh, whoops. Those are for tailscale up and not for tailscaled. Yeah we could add something like TS_TAILSCALED_EXTRA_ARGS

**Comment by rodrigc** [comment]
@maisem I tried something here: https://github.com/tailscale/tailscale/pull/4987
