### ISSUE TITLE
FR: Stop spamming syslog!

### ISSUE THREAD

**Issue by tomwhipple** [tailscale/tailscale#5003]
### What are you trying to do?

I am trying to debug other stuff on my Linux machine, but the overwhelming majority of the syslog messages come from tailscaled.

I would like to either eliminate Tailscale logging or put it in it's own logfile. 

Part of the issue is that I'm on a Starlink connection with imperfect coverage, so the network is intermittently available. 

### How should we solve this?

It seems to me simplest thing to do would be to add a "--logfile=" argument to the Tailscale executable.

### What is the impact of not solving this?

I'll need to turn off Tailscale when debugging things via syslog.

**Comment by bradfitz** [comment]
> It seems to me simplest thing to do would be to add a "--logfile=" argument to the Tailscale executable.

The `tailscaled` binary doesn't even use syslog, so it can't be spamming syslog. You must be running `tailscaled` under something else that's then writing to syslog. You can almost certainly already configure that something else to write to alternate files or syslog facilities/etc. I don't know what you're using, though, as you don't note your distro/version.

**Comment by tomwhipple** [comment]
Interesting. Thanks for the quick response. I'm using RaspberryPi OS "Bullseye" with the following versions:
```
pi@sunflowerpi:~$ tailscale --version
1.24.2
  tailscale commit: 9d6867fb0ab30a33cbdfc8e583f5d39169dbb2e6
  other commit: 2d0f7ddc35aa4149e67e27d11ea317669cccdd94
  go version: go1.18.1-ts710a0d8610
16:30:18
pi@sunflowerpi:~$ uname -a
Linux sunflowerpi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

I installed it by following the manual steps in the quickstart: https://tailscale.com/download/linux/rpi-bullseye

I also spent some time trying to convince rsyslogd to put these messages in their own (and only their own) logfile, but I don't seem to have the right incantation of configuration yet.

**Comment by tomwhipple** [comment]
Yep, that did the trick. Thanks for pointing it out.

**Comment by n0valis** [comment]
I sumbled across this post having th esame issue. tailscaled started by systemd is spamming my deamon.log and systemlog. I don't know anything about internals. Can someone please explain to me why that happens and how to stop it?

Getting t hese messages:
`Nov 29 23:00:09 RaspiD1 tailscaled[501]: Accept: TCP{100.10.0.8:54966 > 100.10.0.6:9100} 60 ok out
Nov 29 23:00:09 RaspiD1 tailscaled[501]: [unexpected] magicsock: derp-4 does not know about peer [/SLM3], removing route
Nov 29 23:00:10 RaspiD1 tailscaled[501]: [unexpected] magicsock: derp-4 does not know about peer [mywuf], removing route
Nov 29 23:00:10 RaspiD1 tailscaled[501]: [RATELIMIT] format("[unexpected] magicsock: derp-%d does not know about peer %s, removing route")
Nov 29 23:00:14 RaspiD1 tailscaled[501]: [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v") (1 dropped)
Nov 29 23:00:14 RaspiD1 tailscaled[501]: open-conn-track: timeout opening (TCP 100.10.0.8:48426 => 100.10.0.9:9100) to node [mywuf]; online=no, lastseen=4520h9m25s, lastRecv=never
Nov 29 23:00:19 RaspiD1 tailscaled[501]: Accept: TCP{100.10.0.8:42768 > 100.10.0.9:9100} 60 ok out
Nov 29 23:00:19 RaspiD1 tailscaled[501]: [RATELIMIT] format("[unexpected] magicsock: derp-%d does not know about peer %s, removing route") (2 dropped)
Nov 29 23:00:19 RaspiD1 tailscaled[501]: [unexpected] magicsock: derp-4 does not know about peer [/SLM3], removing route
Nov 29 23:00:20 RaspiD1 tailscaled[501]: [unexpected] magicsock: derp-4 does not know about peer [mywuf], removing route
Nov 29 23:00:20 RaspiD1 tailscaled[501]: [RATELIMIT] format("[unexpected] magicsock: derp-%d does not know about peer %s, removing route")
Nov 29 23:00:21 RaspiD1 tailscaled[501]: open-conn-track: timeout opening (TCP 100.10.0.8:54980 => 100.10.0.6:9100) to node [/SLM3]; online=no, lastseen=160h31m55s, lastRecv=149h25m2s
Nov 29 23:00:21 RaspiD1 tailscaled[501]: portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router
Nov 29 23:00:21 RaspiD1 tailscaled[501]: portmapper: failed to get PCP mapping: PCP is implemented but not enabled in the router
Nov 29 23:00:23 RaspiD1 tailscaled[501]: open-conn-track: timeout opening (TCP 100.10.0.8:42768 => 100.10.0.9:9100) to node [mywuf]; online=no, lastseen=4520h9m34s, lastRecv=never
Nov 29 23:00:23 RaspiD1 tailscaled[501]: [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v")
Nov 29 23:00:24 RaspiD1 tailscaled[501]: open-conn-track: flow TCP (TCP 100.10.0.8:42318 => 100.10.0.3:9586) got RST by peer
Nov 29 23:00:29 RaspiD1 tailscaled[501]: Accept: TCP{100.10.0.5:53798 > 100.10.0.8:8086} 60 tcp ok
Nov 29 23:00:30 RaspiD1 tailscaled[501]: [RATELIMIT] format("[unexpected] magicsock: derp-%d does not know about peer %s, removing route") (2 dropped)
Nov 29 23:00:30 RaspiD1 tailscaled[501]: [unexpected] magicsock: derp-4 does not know about peer [/SLM3], removing route
Nov 29 23:00:30 RaspiD1 tailscaled[501]: [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v") (1 dropped)
Nov 29 23:00:30 RaspiD1 tailscaled[501]: open-conn-track: timeout opening (TCP 100.10.0.8:42768 => 100.10.0.9:9100) to node [mywuf]; online=no, lastseen=4520h9m41s, lastRecv=never
Nov 29 23:00:30 RaspiD1 tailscaled[501]: [unexpected] magicsock: derp-4 does not know about peer [mywuf], removing route
Nov 29 23:00:30 RaspiD1 tailscaled[501]: [RATELIMIT] format("[unexpected] magicsock: derp-%d does not know about peer %s, removing route")
Nov 29 23:00:36 RaspiD1 tailscaled[501]: open-conn-track: timeout opening (TCP 100.10.0.8:33670 => 100.10.0.6:9100) to node [/SLM3]; online=no, lastseen=160h32m10s, lastRecv=149h25m17s
Nov 29 23:00:39 RaspiD1 tailscaled[501]: open-conn-track: timeout opening (TCP 100.10.0.8:58468 => 100.10.0.9:9100) to node [mywuf]; online=no, lastseen=4520h9m49s, lastRecv=never`
