### ISSUE TITLE
Can't login on Windows 11

### ISSUE THREAD

**Issue by Milo123459** [tailscale/tailscale#5004]
### What is the issue?

i have tried to login by right clicking the context menu multiple times, only to find it does nothing. tailscale up does nothing. tailscale web opens a web page but when clicking login, nothing happens.

### Steps to reproduce

be on windows

### Are there any recent changes that introduced the issue?

doubt it

ps: ever since i downloaded tailscale, i have had this issue. my friends who use tailscale on windows don't have this issue.

### OS

Windows

### OS version

11

### Tailscale version

1.26.1

### Bug report

BUG-0a3c1019aec7738e3a4fb45e434fcd9e873f5d50e504612ae9de9bd2df6cba45-20220703213929Z-6ea9a7fea0989ff8

**Comment by bradfitz** [comment]
Don't hold us in suspense! What was it?

**Comment by Milo123459** [comment]
ExpressVPN was blocking it or something. Turning it off worked.
