### ISSUE TITLE
FR: Add command hook to `tailscale cert`

### ISSUE THREAD

**Issue by durind** [tailscale/tailscale#5011]
### What are you trying to do?

I'm trying to automate certificate renewal for Proxmox PVE and now I have to create a daily cronjob to update the Tailscale certificate with running `pvenode cert set /root/[hostname].ts.net.crt /root/[hostname].ts.net.key --force --restart`

### How should we solve this?

If the `tailscale cert` command had an `-run` argument it could be used to run server specific commands to install and reload the renewed certificates when they are created.

`tailscale cert -run "pvenode cert set /root/[hostname].ts.net.crt /root/[hostname].ts.net.key --force --restart"`

**Comment by durind** [comment]
I've understood that I don't have to run `tailscale cert` every time the certificate needs to be renewed in cron job since tailscale would do that automatically.

But when Tailscale renews the certificate it will save the certificates to --cert-file/key location but won't instruct the service to reload it (proxmox, nginx, apache, etc.)

**Comment by DentonGentry** [comment]
`tailscale cert` runs once. It does not do some kind of background process to periodically update the certificates. In a few months when the certificates expire they just stop working.

If you want to keep the certificates refreshed you need to periodically re-run `tailscale cert`

**Comment by DentonGentry** [comment]
> Currently I'm going to setup a daily cronjob to re-create plex.tailnet-0000.ts.net.p12 and restart Plex, which should catch any certs renewals most of the time, but having a deterministic way of doing this via tailscale cert is preferred.

A cronjob is what I would expect. Maybe once a week, request an updated certificate and install it.

**Comment by Omeryl** [comment]
@DentonGentry this seems like a good opportunity to at least clarify the docs, the way they are worded makes it sound like the certificate is kept in a tailscale config and automatically renewed without re-running the command. Maybe a section on adding it to a crontab?

**Comment by DentonGentry** [comment]
https://tailscale.com/kb/1153/enabling-https/ removed the statement about renewing certificates earlier this week.
