### ISSUE TITLE
FR: Define fixed inbound UDP port

### ISSUE THREAD

**Issue by madhavajay** [tailscale/tailscale#5015]
### What are you trying to do?

I want to run tailscale in a container on a vm which itself has an IPSec tunnel through to a custom DERP server which is part of a headscale tailnet, for NIST reasons. The headscale key server would be accessible over the same link but that part is easily controlled by passing in `-login-server` to the client.

I don't seem to be able to control which ports get opened in UDP to receive traffic back in. I know that part of the STUN process is to try a bunch of ports is it possible to tell tailscale: just use this port and this port only and don't try to open anything else?

Using `-port 41641` doesn't seem to provide a reliable port on any of the interfaces but perhaps thats due to the extra container layer and still seems to cause the STUN connections to occur.

I am sure im just doing something wrong or lack the understanding but any pointers on how this can be achieved would be greatly appreciated as the thing preventing adoption is this requirement, and if possible our software could simply use this configuration in situations where it is required and leave the default behavior everywhere else.

### How should we solve this?

Provide more command line arguments to control the clients networking behavior.

### What is the impact of not solving this?

Providing low levels of network noise, control ports and the ability for network admins to log traffic (Even if it is encrypted) allows them to feel confident that there is nothing "unexpected" going on other than traffic between several IPs over one or two ports (key exchange server and DERP server(s).

### Anything else?

There seems to be some concern about utilising wireguard and i'm hoping to solve it this way:
https://news.ycombinator.com/item?id=21742790

https://twitter.com/matthew_d_green/status/1443558648878350339?s=20&t=VMB2wSmuKOHVkJvVstyB_A

**Comment by DentonGentry** [comment]
I think you are seeing a layer of NAT somewhere in there which is remapping to a different port. `tailscaled port 41641` results in listening on UDP port 41641 within the container.

tailscaled uses STUN to find its public IP address and also figure out if the NAT is "easy NAT" where a given UDP port maps to the same public UDP port to all destinations. "hard NAT" is when every destination gets a different source port.

tailscaled can also use portmapping (NAT-PMP, PCP, or UPnP) to acquire a public port number. This doesn't help in your situation, Docker doesn't implement any portmapping algorithm.

**Comment by DentonGentry** [comment]
Closing because `tailscaled --port=41641` does provide a fixed inbound UDP port. The behavior noted with Docker is due to an extra layer of NAT external to tailscaled.

**Comment by madhavajay** [comment]
@DentonGentry yes, thank you for the information I will try to work around this and figure out a solution but im glad I can understand the issue. Does the NAT busting happen automatically because nothing comes through on the expected port?
