### ISSUE TITLE
cmd/proxy-to-grafana can no longer generate TLS certificates

### ISSUE THREAD

**Issue by raggi** [tailscale/tailscale#5023]
### What is the issue?

Sometime between v1.24.2 and now, it is now attempting to open the host tailscaled.sock to reach the cert API, rather than using an internal transport.

Example log output:

```
2022/07/08 10:51:25 http: TLS handshake error from 100.112.41.64:54637: Failed to connect to local Tailscale daemon for /localapi/v0/cert/james-grafana; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

### Steps to reproduce

```
go run ./cmd/proxy-to-grafana --use-https=true --hostname proxy-test --backend-addr=foo

curl https://proxy-test
```

### Are there any recent changes that introduced the issue?

Since v1.24.2, I have not bisected yet.

### OS

Linux

**Comment by bradfitz** [comment]
tsnet API change when it exited WIP stage. Need to use tsnet.Server.LocalClient now. It no longer monkeypatches another package's dialer.

**Comment by DentonGentry** [comment]
Related to https://github.com/tailscale/tailscale/issues/4973 ?
