### ISSUE TITLE
hujson (when parsing ACL json) fails to throw an error when given extra terminating brace

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#503]
Steps:

1. Paste this into the tailscale ACL admin panel (this is the complete text):
```
{}}}
```
2. Click Save

Expected:
A syntax error message. There are two extra terminating braces.

Actual:
No error. The ACL saves correctly, but parsers other than hujson fail to process it (of course).

On the other hand, this syntax error is detected correctly:
```
{"ACLs":[]]}
```

**Comment by bradfitz** [comment]
@apenwarr, there's a (by-design) difference between Decoder.Decode and Unmarshal: https://play.golang.org/p/1D2hDeHWgtW

In the Decoder.Decode case, it's a stream of JSON values (https://play.golang.org/p/R-ieKLNP2JM).

**Comment by apenwarr** [comment]
So does that just mean we're calling the wrong one?

**Comment by bradfitz** [comment]
That's my guess but I haven't looked at the calling code or read the hujson code. But if it's forked from encoding/json, that'd be what I assume is going on.
