### ISSUE TITLE
Caddy on macOS: sock file not found

### ISSUE THREAD

**Issue by omnibs** [tailscale/tailscale#5038]
[x-post from forum.tailscale.com](https://forum.tailscale.com/t/caddy-and-macos-tailscale-from-app-store/2715)

tscert is looking for `/var/run/tailscaled.socket` but it doesn't exist on my install.

I think this might be related to how the App Store install works, but I don't know enough to tell.

The forum post lined above tells the whole story, but the details are:

### Tailscale version

1.26.2

### Caddy version

2.5.1

### Caddyfile

```
{
	debug
	log {
		output file log/caddy.log {
			roll_keep 1
		}
	}
}

my-host-name.turkey-snapper.ts.net {
	reverse_proxy /* localhost:9000
	tls {
		get_certificate tailscale
	}
}
```

### Caddy logs

From running caddy with sudo:

```
2022/07/11 15:49:10.645	debug	tls.handshake	no matching certificates and no custom selection logic	{"identifier": "my-host-name.turkey-snapper.ts.net"}
2022/07/11 15:49:10.645	debug	tls.handshake	no matching certificates and no custom selection logic	{"identifier": "*.turkey-snapper.ts.net"}
2022/07/11 15:49:10.645	debug	tls.handshake	no matching certificates and no custom selection logic	{"identifier": "*.*.ts.net"}
2022/07/11 15:49:10.645	debug	tls.handshake	no matching certificates and no custom selection logic	{"identifier": "*.*.*.net"}
2022/07/11 15:49:10.645	debug	tls.handshake	no matching certificates and no custom selection logic	{"identifier": "*.*.*.*"}
2022/07/11 15:49:10.654	warn	tls.get_certificate.tailscale	could not get status; will try to get certificate anyway	{"error": "Get \"http://local-tailscaled.sock/localapi/v0/status\": dial unix /var/run/tailscaled.socket: connect: no such file or directory"}
2022/07/11 15:49:10.661	error	tls.handshake	getting certificate from external certificate manager	{"sni": "my-host-name.turkey-snapper.ts.net", "cert_manager": 0, "error": "Get \"http://local-tailscaled.sock/localapi/v0/cert/my-host-name.turkey-snapper.ts.net?type=pair\": dial unix /var/run/tailscaled.socket: connect: no such file or directory"}
2022/07/11 15:49:10.661	debug	tls.handshake	all external certificate managers yielded no certificates and no errors	{"sni": "my-host-name.turkey-snapper.ts.net"}
2022/07/11 15:49:10.661	debug	tls.handshake	no certificate matching TLS ClientHello	{"server_name": "my-host-name.turkey-snapper.ts.net", "remote": "100.91.187.48:61404", "identifier": "my-host-name.turkey-snapper.ts.net", "cipher_suites": [4866, 4867, 4865, 49196, 49200, 159, 52393, 52392, 52394, 49195, 49199, 158, 49188, 49192, 107, 49187, 49191, 103, 49162, 49172, 57, 49161, 49171, 51, 157, 156, 61, 60, 53, 47, 255], "cert_cache_fill": 0, "load_if_necessary": true, "obtain_if_necessary": true, "on_demand": false}
```

What stands out here is:

```
dial unix /var/run/tailscaled.socket: connect: no such file or directory
```

I haven't found the socket file at all on my system, no idea where it lives, but I figure y'all might know and I guess, regardless, it might require a patch in this library to account for that.

**Comment by omnibs** [comment]
Interesting!

> Does `lsof -n -a -u`id -u` -cIPNExtension -F | grep .tailscale.ipn.macos/sameuserproof-` output anything?

It does:

```
n/Users/juliano/Library/Group Containers/W5364U7YZB.group.io.tailscale.ipn.macos/sameuserproof-49397-6317ee580659149f803a
```

I also don't see the `failed to find sandboxed sameuserproof-* file in TS_MACOS_CLI_SHARED_DIR` error, unless I need to give caddy some extra flag to be able to see it.

**Comment by omnibs** [comment]
> What user is Caddy running as and what user is Tailscale running as?
> Running it as the same user as the Tailscale process shows a successful result, running it as another user (even as root) gives the same error

BINGO! I was running Caddy as sudo and thinking "if it doesn't work as sudo ...". It works now! Tysm!

**Comment by mihaip** [comment]
Glad to help. Will see about updating the docs to mention this gotcha.
