### ISSUE TITLE
FR: Support SecureAuth as an identity provider

### ISSUE THREAD

**Issue by chrisckchang** [tailscale/tailscale#5042]
A large government agency is using this IdP and is not currently open to using other solutions for SSO.

**Comment by bradfitz** [comment]
https://www.secureauth.com/

**Comment by DentonGentry** [comment]
OIDC support: https://docs.secureauth.com/1907/en/openid-connect-and-oauth-2-0-configuration.html

**Comment by DentonGentry** [comment]
Since this issue was filed, support for Custom OIDC providers has been added: https://tailscale.com/kb/1240/sso-custom-oidc/

**Comment by catzkorn** [comment]
This should be supported by our Custom OIDC feature.
