### ISSUE TITLE
Unusual rate limit errors with interpolated values missing

### ISSUE THREAD

**Issue by kingdonb** [tailscale/tailscale#5043]
### What is the issue?

I was using a subnet-router in my Kubernetes cluster to bring in clients across the tailnet, and I noticed alongside of what seemed to be slow DNS performance, a number of these messages queueing up in the tailscale pod logs:

```
[RATELIMIT] format("netstack: UDP session between %s and %s timed out")
2022/07/12 19:51:36 [RATELIMIT] format("netstack: UDP session between %s and %s timed out") (7 dropped)
2022/07/12 19:51:36 netstack: UDP session between 0.0.0.0:57210 and 10.17.12.118:53 timed out
2022/07/12 19:51:36 Accept: TCP{100.124.221.91:49256 > 10.110.104.230:443} 52 tcp non-syn
2022/07/12 19:51:36 netstack: UDP session between 0.0.0.0:57095 and 10.17.12.118:53 timed out
2022/07/12 19:51:36 [RATELIMIT] format("netstack: UDP session between %s and %s timed out")
2022/07/12 19:51:46 [RATELIMIT] format("netstack: UDP session between %s and %s timed out") (5 dropped)
2022/07/12 19:51:46 netstack: UDP session between 0.0.0.0:64936 and 10.17.12.118:53 timed out
2022/07/12 19:51:46 Accept: TCP{100.124.221.91:49256 > 10.110.104.230:443} 52 tcp non-syn
2022/07/12 19:51:46 netstack: UDP session between 0.0.0.0:59083 and 10.17.12.118:53 timed out
2022/07/12 19:51:46 [RATELIMIT] format("netstack: UDP session between %s and %s timed out")
2022/07/12 19:51:57 Accept: TCP{100.124.221.91:65494 > 10.107.170.121:80} 52 tcp non-syn
2022/07/12 19:52:01 [RATELIMIT] format("netstack: UDP session between %s and %s timed out") (1 dropped)
2022/07/12 19:52:01 netstack: UDP session between 0.0.0.0:64131 and 10.17.12.118:53 timed out
```

The literal strings `%s` were in the log message and this seems like an error to me. Should they be interpolated with some IP addresses and ports, or something? I was unable to find the root cause of this issue in the source code.

### Steps to reproduce

I've mostly followed the tailscale-k8s guide from https://tailscale.com/kb/1185/kubernetes/

The topology of my network was a local private network hosting the Kubernetes cluster, with tailnet adding routes to LAN subnet, cluster pod subnet, and cluster service subnet; 10.17.12.118:53 was a pi-hole that runs outside of the Kubernetes cluster on the LAN – there is a DHCP server at 10.17.12.1:53 which answers for the non-cluster local network `turkey.local`, and coredns pod service is answering for `cluster.local` in a split-dns configuration, with "Override Local DNS" enabled.

I am not sure what configuration would have worked for me, but I wound up putting Google DNS back in charge at the Global Namespaces setting and immediately noticed the `[RATELIMIT]` session timed out warnings disappeared.

I built my images with the latest `ghcr.io/tailscale/tailscale:1.26.2` as the base, to ensure I am not reporting an issue that has already been fixed.

I was using the pi-hole to block traffic to undesirable domains, but I had to remove it from the head position in my DNS set ("Global Nameservers") 

My network issue is not the issue I'm reporting (although I'd be interested in some advice if there's a simple tweak that will make this work better, like perhaps dropping the configuration out of userspace mode and setting the pod as privileged)

### Are there any recent changes that introduced the issue?

Not sure, if so I did not find any

### OS version

Most nodes are Debian Sid, one Fedora 23 mixed in, MacOS client

### Tailscale version

1.26.1 (mac client), 1.26.2 (linux kubernetes pod servers)

### Bug report

BUG-b76dd1ebdf2dd188128316701ef322e683be4a6c1d89867454043d2b735753ed-20220712201613Z-d518fb42135efa96

**Comment by DentonGentry** [comment]
RATELIMIT means "too many log lines. Log fewer."
It logs the literal format string, coalesced with a count of how many such lines were dropped, as a way to identify where within the code is logging too much.
