### ISSUE TITLE
Cannot make outgoing connections from Synology

### ISSUE THREAD

**Issue by KayLEvans** [tailscale/tailscale#5048]
### What is the issue?

Can't make outgoing connections from the Synology. Followed the instructions here: https://tailscale.com/kb/1131/synology/
Incoming connections are fine. Same instructions in another NAS work fine and can make outgoing connections. Not in this one, which is the main one, where it needs outgoing connections. It looks like the Synology OS itself is not letting the packets out. Tried with firewall disabled (same problem when enabled) and don't see any routes, but think it's because you are using userspace networking.

### Steps to reproduce

Followed the documentation steps, see below. Still can't ping from the OS, only via tailscale internal command.
sh-4.4# sudo setcap cap_net_admin+eip /var/packages/Tailscale/target/bin/tailscaled
sh-4.4# sudo mkdir -p /dev/net
sh-4.4# sudo mknod /dev/net/tun c 10 200
mknod: /dev/net/tun: File exists
sh-4.4# sudo chmod 0666 /dev/net/tun
sh-4.4# sudo /var/packages/Tailscale/target/bin/tailscale configure-host
Done. To restart Tailscale to use the new permissions, run:

sudo synosystemctl restart pkgctl-Tailscale.service

sh-4.4# sudo synosystemctl restart pkgctl-Tailscale.service
[pkgctl-Tailscale.service] restarted.
sh-4.4# tailscale ping 100.x.y.z
pong from 5950x (100.x.y.z) via 192.168.x.x:41641 in 3ms
sh-4.4# ping 100.x.y.z
PING 100.x.y.z (100.x.y.z) 56(84) bytes of data.
^C
--- 100.1x.y.z ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 1005ms

### Are there any recent changes that introduced the issue?

This was working fine in DSM 7. I reinstalled the whole DSM OS in the NAS and this started to happen.

### OS

Other

### OS version

Synology DSM 7.1

### Tailscale version

1.26.0

### Bug report

BUG-6d0afd22c1d910456bc2150b44e785aeebaefa1dd4b77d078ad42bd2a493465d-20220626172939Z-eb703d214ec4b4d4

**Comment by ShadowPeo** [comment]
I can confirm this is not working on 1.28 on both an x86-64 package (DS2416+) and a Marvel Armarda 385 powered device (DS218j).

### What is the issue?

I have installed both the store packages (1.22.2) and the package repo (1.28.0) and attempted both the manual (utilising the commands for adding the capabilities and tunnel manually) and the script (tailscale configure-host) rebooting the devices between attempts to clear any potential issues, and neither of them can perform outbound connections with Ping let alone anything else.

tailscale ping <other tailscale IP> works ping <other tailscale IP> does not (yes using sudo)

### Are there any recent changes that introduced the issue?
Not Applicable, not tried to install this on Synology's for outbound connections before

### OS
Other

### OS version
Synology DSM 7.1

### Tailscale version
1.22.2/1.28.0

**Comment by DentonGentry** [comment]
We had a similar issue recently where the problem was the permissions on the /dev/net/ directory — which configure-host doesn't set, because it was assumed it wouldn't be necessary.

The permissions on the directory should be 755:

admin@dsm7:/$ ls -ld /dev/net
drwxr-xr-x 2 root root 60 Jun 4 19:43 /dev/net

**Comment by ShadowPeo** [comment]
> We had a similar issue recently where the problem was the permissions on the /dev/net/ directory — which configure-host doesn't set, because it was assumed it wouldn't be necessary.
> 
> The permissions on the directory should be 755:
> 
> admin@dsm7:/$ ls -ld /dev/net drwxr-xr-x 2 root root 60 Jun 4 19:43 /dev/net

Thanks for this one mate, this was 100% the issue
