### ISSUE TITLE
Distribute macOS GUI app builds outside the app store

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#505]
Previously, it was impossible to distribute macOS apps using the NetworkExtension API except via the app store. Rumour has it that this has been possible since early 2020:

> To add this entitlement to a macOS app distributed outside of the Mac App Store, perform the following steps: [...]

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_networkextension

This is a separate question from #177, which requested a command-line app that can be installed from Homebrew. That works, but has a separate problem (it requires root access on the machine, doesn't have a GUI, etc).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2as9d)

**Comment by apenwarr** [comment]
Note: one problem that comes up with NetworkExtension-using apps is if you have more than one copy on your filesystem, the frontend can get out of sync with the NetworkExtension. This appears to be caused by a set of bugs in macOS (which don't happen in iOS only because you can never have more than one app with the same appid). Likely almost all the work of resolving this issue will be to figure out how to keep this macOS bug from triggering.

**Comment by bradfitz** [comment]
Update: @crawshaw has found instructions on how to do this now, but we're waiting on a coworker to be back from vacation so we can generate some new signing keys, or waiting on Apple to approve a developer account "Account Holder" transition request. But we should probably be able to make progress on this next week. (And then we'll discover the next problem, surely, but new problems are progress.)

**Comment by bradfitz** [comment]
Ping @crawshaw @dfcarney, now that Carney's back from vacation.

**Comment by DentonGentry** [comment]
Also relevant: https://github.com/tailscale/tailscale/issues/177 for homebrew.

(though this issue is different, to build an installer which can be downloaded outside of the Mac app store)

**Comment by DentonGentry** [comment]
I think this is the same as https://github.com/tailscale/tailscale/issues/718 (which I think has more of the current state in its comments)
Next time thus bug is scrubbed I'm planning to close this unless there are comments to the contrary.

**Comment by bradfitz** [comment]
Somewhat tangential, but instructions are now available for running `tailscaled` on macOS: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

**Comment by DentonGentry** [comment]
#718 tracks this same issue, and though it was filed later it has the most current state. I'm closing this one in favor of #718.
