### ISSUE TITLE
Meshed DERP servers can't talk to each other when `-verify-clients` is enabled

### ISSUE THREAD

**Issue by w1ndy** [tailscale/tailscale#5052]
### What is the issue?

I have set up two DERP servers and attempted to mesh them together following the docs [here](https://tailscale.com/kb/1118/custom-derp-servers/#multiple-nodes-in-a-region). So basically what I do is adding ``-mesh-with B.com --mesh-psk-file /root/mesh.psk`` to the DERP on server A and adding ``-mesh-with A.com --mesh-psk-file /root/mesh.psk`` to the DERP on server B.

However, two servers won't talk to each other. The log on server A repeatedly shows (similar log messages also appear in server B):

```
2022/07/14 10:55:49 mesh("B.com"): derphttp.Client.WatchConnectionChanges: connecting to https://B.com/derp
2022/07/14 10:55:49 mesh("B.com"): Recv: derp.Recv: EOF
```

while the log on server B repeatedly shows (similar log messages also appear in server A):
```
2022/07/14 10:57:53 derp: A_IP:PORT: client xxx rejected: client nodekey:xxx not in set of peers
```

Turning off client verification can resolve this issue, as now the log on server A correctly shows:
```
2022/07/14 10:58:03 mesh("B.com"): 1 peers
```

### Steps to reproduce

1. Set up two DERP servers
2. Enable client verification on these two servers
3. Mesh them together following the [docs](https://tailscale.com/kb/1118/custom-derp-servers/#multiple-nodes-in-a-region)

### OS

Linux

### OS version

Ubuntu 20.04.4 LTS

### Tailscale version

1.26.2

### Bug report

BUG-75957e052d8530b0f7b1eed2aa79269313c0ac8cd9be2e61be8055982cd76bce-20220714031148Z-a53f22c1cd3e89fc

**Comment by DentonGentry** [comment]
May I ask why you not only are using a custom DERP, but trying to use meshed operation?

We use meshed DERP in the public servers, which do not use verify-clients as they are public.

**Comment by w1ndy** [comment]
> May I ask why you not only are using a custom DERP, but trying to use meshed operation?
> 
> We use meshed DERP in the public servers, which do not use verify-clients as they are public.

I've got two servers in different city and I travel a lot, so I'm trying to set up DERP on both servers to relay traffic between the peers connecting to the different DERP servers (I guess meshed DERPs can do this, but correct me if I'm wrong)

**Comment by DentonGentry** [comment]
Meshed DERP is intended for servers which are colocated and where the load is too great to be handled by a single system. Meshing between cities is likely to perform poorly:
- the RTT estimation algorithm assumes that meshed DERPs will have the same speed-of-light delay
- the meshing algorithm is fairly chatty and works best over a local VPC network, not over the Internet

For the situation described I think you'd be better off with two regions, 900 and 901, for each city and one DERP server in each. When you travel your device will figure out that the other region has lower latency and switch to it. It will switch back when you return.

**Comment by w1ndy** [comment]
> Meshed DERP is intended for servers which are colocated in one region and where the load is too great to be handled by a single system. Meshing between cities is likely to perform poorly:
> 
>     * the RTT estimation algorithm assumes that meshed DERPs will have the same speed-of-light delay
> 
>     * the meshing algorithm is fairly chatty and works best over a local VPC network, not over the Internet
> 
> 
> For the situation described I think you'd be better off with two regions, 900 and 901, one region for each city and one DERP server in each. When you travel your device will figure out that the other region has lower latency and switch to it. It will switch back when you return.

Thanks a lot for the clear explanation! I'll close this issue then :)
