### ISSUE TITLE
FR: kubectl support for zero trust

### ISSUE THREAD

**Issue by johnathon-b** [tailscale/tailscale#5055]
### What are you trying to do?

Use `kubectl` across all different clusters with a similar user experience as Tailscale SSH.

### What is the impact of not solving this?

I'm still managing contexts across different clouds via VPN and creds.

### Anything else?

It would be the bee's knees if this were to be implemented.

**Comment by maisem** [comment]
Are you managing your own k8s clusters or are you using a managed service like GKE?

**Comment by johnathon-b** [comment]
I'm using managed services such as:
- Azure Kubernetes Services
- Digital Ocean Managed Kubernetes

As well as a self-hosted cluster.

**Comment by axsgitty** [comment]
This would be a significant improvement to our workflow. We mostly manage remote clusters on bare metal in colocations. We are also doing some testing with Platform9.

**Comment by johnathon-b** [comment]
> This would be a significant improvement to our workflow. We mostly manage remote clusters on bare metal in colocations. We are also doing some testing with Platform9.

I agree. It would allow us to offload most our RBAC. 🤤

**Comment by guitmz** [comment]
this is a killer feature to have :)

**Comment by rohannair** [comment]
Would love this. We have multi-cloud K8S setups, mostly on GKE.

**Comment by mayakacz** [comment]
We have a **Tailscale Kubernetes operator with an auth proxy** now available in [alpha](https://tailscale.com/kb/1167/release-stages/#alpha) for testing. 🎉

The Tailscale Kubernetes operator allows you to, among other things, access the Kubernetes control plane (kube-apiserver) over Tailscale. When a user tries to access the Kubernetes control plane, they will access it with the same user identity that they have in Tailscale.
To set this up, you need to deploy the Tailscale Kubernetes operator, update your kubeconfig locally, and ensure that the user has a cluster role that grants access to the Kubernetes control plane.

See the [documentation on the Kubernetes operator to getting this set up and running](https://tailscale.com/kb/1236/kubernetes-operator/#enabling-an-auth-proxy).

Specific areas we’d like feedback on:
* There is no way to define Tailscale ACLs that restrict Kubernetes RBAC, or map Tailscale ACLs to RBAC. How do you expect to handle user permissions in Kubernetes RBAC if accessing over Tailscale?
* Do you need the ability to record kubectl sessions?
* This operator only allows user@example.com to authenticate as themselves, not impersonate another user, like sre-service-account@example.com or just `sre`. Is impersonation something you need?

We look forward to hearing any feedback you have. Please add feedback to this GitHub issue. See the broader issue for the K8s operator: https://github.com/tailscale/tailscale/issues/502

Thank you for your ongoing support and feedback on Tailscale!

**Comment by DentonGentry** [comment]
I think the original intent of this feature request was met via the auth proxy described in https://github.com/tailscale/tailscale/issues/5055#issuecomment-1487738764

I'm sure there are additional features one might want or issues to report, but please do so as new issues. This one is already long and was used to track development of the auth proxy feature.
