### ISSUE TITLE
FR: Allow everyone to see *something* on the admin panel

### ISSUE THREAD

**Issue by jhawk28** [tailscale/tailscale#5065]
### What are you trying to do?

Users that first log in are given a `Member` role by default. It would be useful to be able to set the default role a user is given.

For example, we don't find `Member` to be very useful as the base role. `Auditor` lets them see the admin website.

### How should we solve this?

Add the ability to configure the default role for a new user.

**Comment by bradfitz** [comment]
cc @mayakacz

**Comment by DentonGentry** [comment]
We expect to make the Member role have some visibility into the admin panel. At a minimum to be able to find out who the admin of their tailnet is, and possibly see the list of their own devices.

**Comment by DentonGentry** [comment]
Whatever is implemented for https://github.com/tailscale/tailscale/issues/3858 will take the form of a limited subset of the admin panel for different roles.

Dup of https://github.com/tailscale/tailscale/issues/3858
