### ISSUE TITLE
FR: Package for OPNsense

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#5067]
### What are you trying to do?

Create an OPNsense plugin for Tailscale, allowing it to appear as an Interface for use with other features and to be configured using the UI.

**Comment by stewag** [comment]
A plugin makes updates easier using the build-in OPNsense update machanism.

**Comment by txr13** [comment]
A plugin for OPNsense would definitely be an excellent thing, as it would avoid the process of having to manually update the ports tree, deinstall, clean, and then install the new version.

**Comment by DentonGentry** [comment]
For anyone reading this who has experience building plugins for OPNsense: we'd love to write a contract to develop a Tailscale plugin. Please contact dgentry at tailscale.

**Comment by juliocbc** [comment]
Hi @DentonGentry, we (at [Cloudfence](https://cloudfence.com.br)) have some experience. We'll be glad to help.

**Comment by fichtner** [comment]
We're already talking to @DentonGentry at the moment about how to approach this structurally.


Cheers,
Franco

**Comment by noseshimself** [comment]
Would it be possible (as quick fix) to include the tailscaled pkg into the OPNSense repository? It would be necessary for a plugin anyway.

**Comment by ellnic** [comment]
> Would it be possible (as quick fix) to include the tailscaled pkg into the OPNSense repository? It would be necessary for a plugin anyway.
> 
> 

But it's already in ports? :)

**Comment by fichtner** [comment]
it's in mimugmail's community repo

**Comment by noseshimself** [comment]
> > Would it be possible (as quick fix) to include the tailscaled pkg into the OPNSense repository? It would be necessary for a plugin anyway.
> 
> But it's already in ports? :)

Sure -- how do you think I installed it? But I do not really want a development environment on production routers.

**Comment by noseshimself** [comment]
> > Sure -- how do you think I installed it? But I do not really want a development environment on production routers.
> 
> Right... but when you say "development environment", you're not talking about actively developing / coding something exposing the box to memory leaks and kps, are you?

You need the ports support infrastructure on the machine you want to install it on.

Having anything not provided by the vendor on a production machine usually does not comply with basic gocernance rules so: No. Not in serious production.

**Comment by fichtner** [comment]
We provide the ports tree and therefore you have my vendor blessing. 😉

**Comment by noseshimself** [comment]
Just for my understanding: How "bad" (in terms of future work for keeping it there) would be adding the port to the precompiled packages in the OPNSense repository? Compiling the package on a rather weak older appliance will be an adventure in itself...

**Comment by fichtner** [comment]
I've made a comment a while back here...

https://github.com/opnsense/tools/pull/331#issuecomment-1655264552

So you can also use the FreeBSD package without an issue I think (just use `pkg-add`) so adding it to our build really doesn't change much at the moment if we are not progressing on a plugin. The way forward is very much tied to https://github.com/tailscale/tailscale/issues/5067#issuecomment-1708030918

**Comment by ellnic** [comment]
Awesome news. Thanks to all those involved. 🥳

**Comment by bradfitz** [comment]
Looks like it's in: https://github.com/opnsense/plugins/tree/master/security/tailscale

From https://github.com/opnsense/plugins/pull/4386

**Comment by 42Network** [comment]
If there is now an official OPNsense plugin for Tailscale, why is it not mentioned in the Tailscale KB [article](https://tailscale.com/kb/1097/install-opnsense)? It is still recommending the manual ports method.

I am running tailscale on my OPNsense firewall using the ports method and would like to know how to correctly/safely migrate to the official OPNsense plugin.

Thank you

**Comment by noseshimself** [comment]
Read https://github.com/opnsense/tools/pull/331#issuecomment-1811939215 again...

To be honest, the Tailscale project is suffering from having more on their plate than they can chew. They can't even find the time to develop some pricing models for large customers with specific needs (e. g. as secure communication channels for low traffic/high volume OT not-Internet-of-things architectures where OpenXiti just does not cut it).

**Comment by bradfitz** [comment]
I copied the docs comment from @42Network to https://github.com/tailscale/tailscale/issues/15153
