### ISSUE TITLE
FR: Sidecar Port Forward

### ISSUE THREAD

**Issue by rhjensen79** [tailscale/tailscale#5068]
### What are you trying to do?

Sometimes it's not possible to install Tailscale into the container, you want to connect to. 
Also separating duties, also says you should separate each service/function.
I would love, a Tailscale container image, that could port forward, specifics ports, defined in the configuration of the container, that allows me to forward all traffic, to the inside of the container environment.
Just like I can do today, with http traffic, by installing a reverse proxy, inside the Tailscale container image, but without the hassle, og maintaining another reverse proxy, and allowing me to specify any port, and not just http traffic.

### How should we solve this?

imho you already have all the tools you need.
The Tailscale Exit node, does exactly this, but it does it for a whole subnet. I would love, to use this functionality, but just for 1 or more ports.

### What is the impact of not solving this?

A solutions is building this my self, or using a wider solution, like the Tailscale K8S operator, I can see is also being looked at.

I think the Operator is great, is I could see myself use that, but the use case her is a bit different.
Also providing this, would enable me to present services, to my Tailscale network,  on both K8S, or docker-compose hosts's seamless. 

### Anything else?

I think you got all the tools you needs to create this, and it would greatly enhance the capability's of Tailscale in micro service environments.

**Comment by DentonGentry** [comment]
`tailscaled --tun=userspace-networking` will forward incoming connections to TailscaleIP:port to localhost:port, which is often used to provide connectivity to containers.

**Comment by rhjensen79** [comment]
Finally got around to test it. This is exactly what i am looking for.
I must say, that your official docker image tailscale/tailscale don't make it easy to deploy and add this setting. 
I got it working, by using an example from here : https://github.com/lpasselin/tailscale-docker
