### ISSUE TITLE
Android: Can't connect

### ISSUE THREAD

**Issue by sckemu** [tailscale/tailscale#507]
**Describe the bug**
Can't connect to Tailscale's network.
**To Reproduce**
1. Switch to "Starting..."
2. Can't connect and immediately go back to "Stopped".

**Expected behavior**
Successful connection.

**Screenshots**
![output](https://user-images.githubusercontent.com/49110580/85635265-6ac8be80-b6b8-11ea-807b-afd49c56abd2.gif)

**Version information:**
 - Device: Google Pixel 3
 - OS: Android
 - OS version: 10
 - Tailscale version: 0.1.10-0-g676447a

**Additional context**
* I get "Connecting..." in the notification, but it disappears after about 5 seconds.

* Only the immediate post-installation connection works properly. Once stop Tailscale, this will happen until you reinstall it.

I use machine translation, so if you find something strange, please point it out.

**Comment by bradfitz** [comment]
Can you email info@tailscale.com with your email address where this is happening? Perhaps we can see something in our logs.

**Comment by sckemu** [comment]
Over the past few days, the phenomenon I described in the issue has stopped happening.
