### ISSUE TITLE
Docker image doesn't let tailscale cert work by default

### ISSUE THREAD

**Issue by ussjoin** [tailscale/tailscale#5072]
### What is the issue?

Running `tailscale cert` on the Tailscale docker container causes a "failed to connect" error.

```
$ docker exec tailscaled-${SERVICE_NAME} tailscale cert ${MY_HOSTNAME}.${MY_TS_TLS_DOMAIN}
Failed to connect to local Tailscale daemon for /localapi/v0/cert/<REDACTED>; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

The same result occurs when running the command from a Bourne shell inside the Docker container, via a `docker exec -ti tailscaled-${SERVICE_NAME} /bin/sh` shell.

Passing the `tailscale --socket /tmp/tailscaled.sock` flag did not fix the issue. (`/tmp/tailscaled.sock` is where the Docker image keeps the socket, which I discovered looking at `ps aux` inside the container.)

What *did* fix the issue was the following:
```
docker exec tailscaled-${SERVICE_NAME} mkdir -p /var/run/tailscale
docker exec tailscaled-${SERVICE_NAME} ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock
```
and then proceeding as above.

I'm no Gopher, so I can't provide a PR to your code, but I suspect that there's a code path specific to the `tailscale cert` operation that doesn't respect the `--socket` flag.

### Steps to reproduce

```
$ docker exec tailscaled-${SERVICE_NAME} tailscale cert ${MY_HOSTNAME}.${MY_TS_TLS_DOMAIN}
Failed to connect to local Tailscale daemon for /localapi/v0/cert/<REDACTED>; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

The same result occurs when running the command from a Bourne shell inside the Docker container, via a `docker exec -ti tailscaled-${SERVICE_NAME} /bin/sh` shell.

### Are there any recent changes that introduced the issue?

Not aware of any.

### OS

Linux, Other

### OS version

Tailscale Docker Image 5893a761d97d (on an Ubuntu 22.04 host)

### Tailscale version

1.26.2

### Bug report

BUG-7c9551bc0141a20c21e15a3219f7668a542e90a5ad4780bf961abca0293dd312-20220717185939Z-75b0a05381a538d0

**Comment by ussjoin** [comment]
@maisem Thank you! Any info on what version to look for this fix in, so that once it shows up in Docker I can drop my workaround script?

**Comment by DentonGentry** [comment]
It will appear in 1.28.0, expected this coming week.

**Comment by ussjoin** [comment]
Thank you both very much!

**Comment by maisem** [comment]
@ussjoin you can also try out the unstable at `tailscale/tailscale:v1.27`

**Comment by ussjoin** [comment]
@DentonGentry @maisem Unfortunately, I pulled the new Tailscale Docker image today and have the same problem. Confirmed that `Docker exec tailscaled tailscale version` returns 1.28.0.

**Comment by yidongw** [comment]
I'm having the same issue in `1.28.0`

**Comment by jinyu121** [comment]
I also meet the same issue in `1.29`. Add

‘’‘yaml
command: sh -c "mkdir -p /var/run/tailscale && ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock && tailscaled"
’‘’

to the tail of the `docker-compose.yaml` saved my life.

**Comment by Knufle** [comment]
@maisem @DentonGentry Can we please reopen this? It still doesn't work out of the box by just following the official guide available here https://hub.docker.com/r/tailscale/tailscale

Also as you can see from the history, it has been mentioned in other repos' issues.

**Comment by bradfitz** [comment]
@Knufle, feel free to open a new bug with complete details of the problem you're hitting.
