### ISSUE TITLE
Windows Server 2016 Domain Controller DNS errors 404, 407, 408 immediately after install

### ISSUE THREAD

**Issue by axsms** [tailscale/tailscale#5075]
### What is the issue?

A Windows Server 2016 Domain Controller stopped functioning and became unavailable to Tailscale shortly after install. DNS server errors 404, 407, 408 were logged within a few minutes. A restart of the DNS Server service seems to have resolved the issue, so far. 

A second DC built on Win Server 2019 did not have this issue. I do not have the environment to see if this is reproducable.

![Screenshot 2022-07-17 162002](https://user-images.githubusercontent.com/83303625/179423489-a833ff1f-6f84-4aa6-8614-712ef6700aaa.png)

### Steps to reproduce

1. Install Tailscale with provided Windows exe on a Windows Server 2016 Domain Controller
2. Authenticate
3. Server will be added to Tailscale Admin
4. Within a few minutes the server will disconnect
5. Logs should show 404, 407, and 408 IDs in DNS Server logs
6. RDP from LAN and restart DNS to reconnect Tailscale services to the server

### Are there any recent changes that introduced the issue?

First and only Tailscale install on the machine. 

### OS

Windows

### OS version

Microsoft Windows Server 2016 Standard

### Tailscale version

1.26.2

### Bug report

BUG-0f95ec9406d04a671a07e649629d028ad14845c645e55786d2bc55bf0ee9a579-20220717203719Z-5b63b2136c3962b3

**Comment by DentonGentry** [comment]
Unfortunately I don't see anything particularly suspicious around BUG-0f95ec9406d04a671a07e649629d028ad14845c645e55786d2bc55bf0ee9a579-20220717203719Z-5b63b2136c3962b3. Which is not that surprising, whatever interaction was going on was presumably deeper in the system and involved the DNS Service.

Possibly related is BUG-0f95ec9406d04a671a07e649629d028ad14845c645e55786d2bc55bf0ee9a579-20220717203719Z-5b63b2136c3962b3, which has a fix in the tree expected to be delivered in the 1.28 release this coming week. One can get early access to the fix by installing the current unstable build: https://pkgs.tailscale.com/unstable/#windows

**Comment by axsms** [comment]
@DentonGentry, #4829 fits the general experience. Though I don't see specific Event IDs called out, the fix looks promising.  Happy to close this as related.
