### ISSUE TITLE
--exit-node-allow-lan-access doesn't seem to work when CloudFlare Warp is configured

### ISSUE THREAD

**Issue by gotlougit** [tailscale/tailscale#5088]
### What is the issue?

I use Tailscale as a homemade VPN to connect to the Internet through my home network's Internet connection. I also need to access certain services on my home network that are hosted locally, so the VPN "server" in this case acts as a subnet relay and an exit node.

I connect to my home network through a network that uses a web-based captive-portal to authenticate users, and the authentication server is hosted on our local network.

However, even after using tailscale with the --exit-node-allow-lan-access option, I cannot access the authentication server and I have to turn off Tailscale to do so. I am not sure why this is happening. My local network is configured to hand out IP addresses in the ```172.16.0.0/16``` range.

### Steps to reproduce

1. Turn on tailscale with --exit-node-allow-lan-access
2. Try to ping local network servers
3. It will never respond back

### OS

Linux

### OS version

Fedora 36

### Tailscale version

1.26.2

### Bug report

BUG-22a2d04a6303315043baecb3691e6e373fc9150d2a071306ed74dfae82d65870-20220719021437Z-bdf6d018aa0cf4a4

**Comment by DentonGentry** [comment]
`--exit-node-allow-lan-access` applies to the client connecting to the exit node, not the exit node itself.

For example if you are sitting in an office and connecting to an exit node back at your house, `--exit-node-allow-lan-access` issued to the machine in your office will allow it to connect to the LAN in the office in addition to connecting to the Internet via the exit node at the house.

If you want to be able to use the node back at the house to connect to the LAN in the house, on the exit node you'd additionally use `--advertise-routes=w.x.y.z/q` for the LAN subnet of the house network.

**Comment by gotlougit** [comment]
> For example if you are sitting in an office and connecting to an exit
> node back at your house, |--exit-node-allow-lan-access| issued to the
> machine in your office will allow it to connect to the LAN in the office
> in addition to connecting to the Internet via the exit node at the house.

That is the problem though, I am not able to connect to local devices on
the office network.

I have the machine at home advertising my home network's local route
(192.168.30.0/24) and my office network uses 172.16.0.0/16. I am able to
ping 192.168.30.0/24 but not 172.16.0.0/16 when Tailscale is up. From my
understanding of the --exit-node-allow-lan-access and your explanation,
this shouldn't be happening, right?

**Comment by DentonGentry** [comment]
From around the time of the bugreport:

`2022-07-19 07:42:54.556594105 +0530 +0530: LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=enp2s0 ifs={CloudflareWARP:[172.16.0.2/32 fd01:5ca1:ab1e:8d44
:q:r:s:t/128] enp2s0:[172.16.168.x/23] lo:[fd01:y:z::2/128 fd01:y:z::3/128]} v4=true v6=true}`

I think there are two things happening:

1) The local LAN is not 172.16.0.0/16, the local LAN is 172.16.168.0/23. 172.16.0.x is CloudFlare WARP.

2) CloudFlare WARP and Tailscale are fighting over routing table and iptables entries:
`2022-07-19 07:42:14.050416142 +0530 +0530: router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's`

**Comment by gotlougit** [comment]
> I think there are two things happening:
> 
>  1.
> 
>     The local LAN is not 172.16.0.0/16, the local LAN is
>     172.16.168.0/23. 172.16.0.x is CloudFlare WARP.
>  2.
> 
>     CloudFlare WARP and Tailscale are fighting over routing table and
>     iptables entries:
>     |2022-07-19 07:42:14.050416142 +0530 +0530: router: somebody (likely
>     systemd-networkd) deleted ip rules; restoring Tailscale's|
> 

Hmm, so if they are in conflict, should I try disabling Warp entirely
and see if Tailscale works as usual?

**Comment by DentonGentry** [comment]
> ...should I try disabling Warp entirely and see if Tailscale works as usual?

You should try disabling Warp entirely and see if Tailscale works as usual.

**Comment by DentonGentry** [comment]
I think it is fairly clear that the two VPNs are fighting over the routing table and iptables.
`2022-07-19 07:42:14.050416142 +0530 +0530: router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's`

Please reopen if there is something which we could actually do about this.
