### ISSUE TITLE
Tailscale SSH doesn't allow port forwarding unless a command is executed

### ISSUE THREAD

**Issue by jakob** [tailscale/tailscale#5091]
### What is the issue?

It seems like Tailscale SSH requires me execute a command or open a shell on the server before allowing port forwarding.

### Steps to reproduce

I try to set up port forwarding with the following command:

```bash
ssh root@100.x.x.x -N -L5432:examplehost:5432
```

The connection is established successfully.

Then I try to open a connection (from a different Terminal):

```bash
nc localhost:5432
```

This fails, and an error message is printed:
`channel 2: open failed: administratively prohibited: port forwarding is disabled`

If I connect without the `-N` flag, it works.

### OS

Linux, macOS

### OS version

Server is Ubuntu 20.04 LTS, Client is macOS 12.4

### Tailscale version

1.28.0

**Comment by bradfitz** [comment]
Ooooh, fun one. Whoops.

cc @maisem
