### ISSUE TITLE
Option to autostart Tailscale after Android system restart

### ISSUE THREAD

**Issue by palesz** [tailscale/tailscale#510]
**Is your feature request related to a problem? Please describe.**

I would like to be able to connect to/from my Android device after system restart without any extra steps. My super non-critical use case: I am running rtsp server on an older Android phone that I would like to be able to access with the steps to be taken after a restart. 

**Describe the solution you'd like**

I would like to have an "Auto-start after system reboot" option in the Android Tailscale app.

**Describe alternatives you've considered**

Alternative is to simply just use a separate startup manager app, although less convenient.

**Additional context**

Nope.

**Comment by bradfitz** [comment]
Interesting use case! What RTSP server are you running? For some remote camera, or ....?

**Comment by palesz** [comment]
I am running this app: https://play.google.com/store/apps/details?id=com.miv.rtspcamera

Currently it is used as an adhoc/portable babycam. Above app ± tailscale + vlc does the trick, no matter where/which network we are, the cam is accessible.

**Comment by palesz** [comment]
... without having to share stuff with "the cloud".

**Comment by JayDoubleu** [comment]
@palesz navigate to VPN settings > Tailscale > Toggle "Always-on VPN" > reboot.

**Comment by palesz** [comment]
That's awesome! Did not know about this option, problem solved.
Brad Fitzpatrick <notifications@github.com> wrote:
“@palesz navigate to VPN settings > Tailscale > Toggle "Always-on VPN" > reboot.”

**Comment by palesz** [comment]
When I use the "Always-on VPN" option, after restart Android shows more often than not the "Tailscale is not responding" message. Starting Tailscale manually still works like a charm.
Not sure what causes the "unresponsiveness in case of auto-start"

**Comment by palesz** [comment]
Seems like the "Always-on VPN" option works, Tailscale starts properly after restarts. Closing.

**Comment by SGprooo** [comment]
I currently use an Android TV as my home wifi hotspot (it's janky, I know), and all my home devices are connected to it... Although Tailscale functions if launched, it does not when the Android TV is rebooted, and the VPN settings are not visible in the slimmed down version of the TV settings app.
It would be great if Tailscale services could be implemented to autostart at devices boot.

**Comment by Heib386** [comment]
i would also appreciate autostart on android. need it for my shieldtv because it has no autostart-vpn setting

**Comment by Quintasan** [comment]
This is a nonsolution because it doesn't work. At least it doesn't work on my Pixel 6 Pro because after a reboot all I can see is a notification and after I click it I get the following dialog

![Screenshot_20230925-181331](https://github.com/tailscale/tailscale/assets/6539261/0b734286-ba1f-4364-bb86-edbf84d4f18f)

**Comment by ellnic** [comment]
+1 for Nvidia shield autostart support. No VPN autostart settings in the stripped down ATV OS, so would have to come from the TS app.

**Comment by derekcentrico** [comment]
+1 auto start for all mobile platforms

**Comment by ellnic** [comment]
> +1 auto start for all mobile platforms

If you have any iOS devices, this has just been implemented and it works really well.

**Comment by sbkg0002** [comment]
@palesz I don't think this is implemented; on Android TV it doesn't start.

**Comment by hzexe** [comment]
Not implemented on android tv box...
checked the "Always-on VPN",not run after reboot,and not actived if open app

**Comment by zannas88** [comment]
I tried lot of work around but I still can't run tailscale on Android after a reboot

**Comment by bobmarley2021** [comment]
I have been following various topics here for some time and it’s clear that there is a trend here. TS focus more on back end and infrastructure improvements but severely neglect app quality of life. SEVERELY. 

IMHO, this has got to change - or at least become a bit more balanced. 

I note 3 major issues that I have come across which are total deal breakers for me:

1. the Android app (especially TV app) is shocking. Absolutely SHOCKING. The TV app quits when pressing the back button and neither app have autostart. The TV app is crude and basic with little to no attention recently. 
2. The iOS app (and maybe android too) have severe battery drain issues that the TS Team have said they plan to fix but aren’t making good on that. Maybe it’s because @bradfitz is on paternity leave right now (congrats btw) but has he assigned @agottardo  - can we have an update? 
3. There is a logging issue that causes the syslog’s in a Linux system to become spammed so much they can reach multi-gigabyte sizes in a couple of months. The workarounds to disable logging do not work and are crippling for those who need logs, requiring something like cron to delete them. 

I really wish TS devs would take these issues seriously and sort them out as they are preventing what could be an amazing service from being so.

They need to seriously look at their tagging too. This is labelled “very few” and “nuisance”. This is FAR from the truth. How about many [all?] and crippling?

Now I’ll get off my soap box.

**Comment by tripplehelix** [comment]
> They need to seriously look at their tagging too. This is labelled “very few” and “nuisance”. This is FAR from the truth. How about many [all?] and crippling?

No, This thread is marked as closed, so fixed. ;)

I also struggle with the app as it doesn't autostart, and even sometimes disconnects so it shows as being connected to a local VPN, but I end up with no network. 

There's a great Magisk module that makes tailscale work as if on Linux, but it runs in userspace-networking mode so you lose access to the reason you'd use a tailscale network in the first place.

I love the Linux CLI version of tailscale, just wish I could connect other devices with the same efficiency.

All I want is a zero config android app. Whether that requires root or not.

**Comment by jgibson02** [comment]
+1, I am trying to privatize a lot of selfhosted services for my home and have them be accessible by my family members on their phones, our TVs, tablets, etc. and having to tell them they have to remember to manually go and connect to Tailscale every time they need to access those services is a big pain.

**Comment by Heib386** [comment]
I messed really a lot with this. I can only really recommend using another device as a subnet router. 
In my case i bought a glinet router and use it a subnet router for tailscale and zero tier. Cant be happier.

**Comment by bobmarley2021** [comment]
> I messed really a lot with this. I can only really recommend using another device as a subnet router. In my case i bought a glinet router and use it a subnet router for tailscale and zero tier. Cant be happier. Raspberry pi should also work

Thanks for the suggest and please excuse me if I am incorrect but subnet routers are for incoming traffic are they not? Ie. You’re on a Tailscale connected device, and you want to connect to a device _without_ Tailscale installed on it. What if you are using that device without Tailscale and you want to connect to a remote machine on the tailnet? So I fire up my Nvidia shield and I want to connect to a remote Jellyfin server. How can I do this with no Tailscale client installed? Getting the wife and kids to traverse the appalling ATV app isn’t going to happen and I can’t be there to do it for them all the time. I don’t see how a subnet router would help. In @jgibson02’s case, he needs auto start on the family’s android phones, presumably?

**Comment by agottardo** [comment]
Just a heads-up that this issue has been fixed in our new Android app. You can try it by joining our [beta testing track](https://play.google.com/apps/testing/com.tailscale.ipn) on the Play Store. If you're still experiencing this issue, please let us know.

**Comment by derekcentrico** [comment]
Where is the auto start option? Just installed beta. Slick new design but I
don't see such a toggle. Auto start and VPN on demand for Android as is
available for iOS will be gold.

**Comment by agottardo** [comment]
> Where is the auto start option?

On Android, it's a system-wide setting. Go to the Settings app > Network & internet > VPN > Tailscale > Always-on VPN.

**Comment by derekcentrico** [comment]
> > Where is the auto start option?
> 
> @derekcentrico  On Android, it's a system-wide setting. Go to the Settings app > Network & internet > VPN > Tailscale > Always-on VPN.

Duh. I forgot about that setting. Was looking on the app similar to iOS. Now to pray for VPN on demand options so specific wifi can disable this like iOS.

**Comment by Heib386** [comment]
> > I messed really a lot with this. I can only really recommend using another device as a subnet router. In my case i bought a glinet router and use it a subnet router for tailscale and zero tier. Cant be happier. Raspberry pi should also work
> 
> Thanks for the suggestion and please excuse me if I am incorrect but subnet routers are for incoming traffic are they not? Ie. You’re on a Tailscale connected device, and you want to connect to a device _without_ Tailscale installed on it. What if you are using that device without Tailscale and you want to connect to a remote machine on the tailnet? So I fire up my Nvidia shield and I want to connect to a remote Jellyfin server. How can I do this with no Tailscale client installed? Getting the wife and kids to traverse the appalling ATV app isn’t going to happen and I can’t be there to do it for them all the time. I don’t see how a subnet router would help. In @jgibson02’s case, he needs auto start on the family’s android phones, presumably?

I am no expert by any means, just wanted to share what works for me :) . I have nvidia shield with plex server. Autostart does not work like i want it on shield tv. But now with mi glinet router also acting as a tailscale subnet router i can access my plex and smb share from anywhere with my android phone. I think you could also connect two networks (lets say mine and my girlfriends home) each having their subnet router and act as one network. All clients on these networks act like their on one single network without having tailscale on each device. Am i wrong

**Comment by bobmarley2021** [comment]
> Just a heads-up that this issue has been fixed in our new Android app. Tailscale will automatically restart upon a system restart when set to always-on. You can try the new version by joining the [beta testing track](https://play.google.com/apps/testing/com.tailscale.ipn) on the Play Store.
> 
> If you're still experiencing this issue, please let us know.

This is great, thank you. I’ll take a look. 👍

**Comment by Heib386** [comment]
> > Just a heads-up that this issue has been fixed in our new Android app. Tailscale will automatically restart upon a system restart when set to always-on. You can try the new version by joining the [beta testing track](https://play.google.com/apps/testing/com.tailscale.ipn) on the Play Store.
> > If you're still experiencing this issue, please let us know.
> 
> This is great, thank you. I’ll take a look. 👍
> 
> > I am no expert by any means, just wanted to share what works for me :) . I have nvidia shield with plex server. Autostart does not work like i want it on shield tv. But now with mi glinet router also acting as a tailscale subnet router i can access my plex and smb share from anywhere with my android phone. I think you could also connect two networks (lets say mine and my girlfriends home) each having their subnet router and act as one network. All clients on these networks act like their on one single network without having tailscale on each device. Am i wrong
> 
> But the problem I am describing is how do you initiate a connection from a device when autostart wasn’t working - thus essentially without TS installed? You can’t. You can access your plex server because:
> 
> mobile dev with TS enabled > TS subnet router at home > plex server without TS
> 
> this would not work for:
> 
> ATV without TS > remote plex server with TS
> 
> Unless I am totally wrong? Anyway, it seems this is quite soon to be moot ;-)

Yes i think you are totally right with what you described :)

**Comment by agottardo** [comment]
> Ahhhh so is this is not for ATV, only android? I enrolled to the beta and now get the message:
> 
> `Tailscale by Tailscale Inc. isn’t available on Google Play for this device`
> 
> @agottardo are there plans to follow with ATV for us Nvidia Shield users?

Yes, very soon. It's actually already supported and fully working if you build from sources. We simply had a submission issue with the Play Store so ATV support couldn't make it into the APK that was released today.

**Comment by bobmarley2021** [comment]
> Yes, very soon. It's actually already supported and fully working if you build from sources. We simply had a submission issue with the Play Store so ATV support couldn't make it into the APK that was released today.

Thank you for the prompt reply and excellent news. I’ll wait for the next update. Thank you for giving this issue your time. 👍

**Comment by trogau** [comment]
> Just a heads-up that this issue has been fixed in our new Android app. Tailscale will automatically restart upon a system restart when set to always-on. You can try the new version by joining the [beta testing track](https://play.google.com/apps/testing/com.tailscale.ipn) on the Play Store.
> 
> If you're still experiencing this issue, please let us know.

This is great on Android but (sorry to be a hassle) it doesn't appear to provide similar functionality for the Android application when used on a Chromebook device. I assume this is simply because the VPN functionality on a Chromebook is different to that in Android.  We're in a Google Workspace environment and it looks like there is an "Always on VPN" policy which might be relevant here (https://support.google.com/chrome/a/answer/10038919?sjid=17232837176206662315-AP) although it looks like it might require Tailscale to be force-installed to all users (it's not currently in our environment).

**Comment by JasonHK** [comment]
> > Ahhhh so is this is not for ATV, only android? I enrolled to the beta and now get the message:
> > 
> > `Tailscale by Tailscale Inc. isn’t available on Google Play for this device`
> > 
> > @agottardo are there plans to follow with ATV for us Nvidia Shield users?
> 
> Yes, very soon. It's actually already supported and fully working if you build from sources. We simply had a submission issue with the Play Store so ATV support couldn't make it into the APK that was released today.

@agottardo Hello, has the update for Android TV landed? Because Android TV doesn't feature a VPN settings page on Settings, I have no way enabling it through there.

**Comment by Pawloland** [comment]
If the Android TV version is new enough it most probably will have the same always on VPN functionality as the equivalent mobile version of Android (provided the manufacturer haven't removed it explicitly, but most of the haven't). On Android TV there just isn't a gui to enable it in the settings like with the accessibility settings. It can be done inside adb shell.
1. Enter adb shell.
2. While inside execute:
```
settings put secure always_on_vpn_app com.tailscale.ipn

settings put secure always_on_vpn_lockdown 0

settings put secure always_on_vpn_lockdown_whitelist
```
After this open tailscale app, connect and reboot TV. After this tailscale should connect automatically.

This could be automated in the tailscale app when it detects that it is run on tv. The user would enable USB debugging in the tv settings, the app would then connect to 127.0.0.1:5555 and run those commands.

It could also be done by requesting Write secure settings Android permission, but it would also need to be granted from the adb shell by the user for tailscale app, so the first approach seams less janky, as all the user would need to do is enable developer options in the settings.

Then it would work similarly to [https://xdaforums.com/t/app-firetv-accessibility-permissions-manager-for-firetv-devices.4144057/]() that manages accessibility settings.

At last it could be documented somewhere on the tailscale page, so the advanced users could fix it themselves.

**Comment by tripplehelix** [comment]
> ```
> settings put secure always_on_vpn_app com.tailscale.ipn
> 
> settings put secure always_on_vpn_lockdown 0
> 
> settings put secure always_on_vpn_lockdown_whitelist
> ```

Everything here works except the last argument `settings put secure always_on_vpn_lockdown_whitelist` the TV spits back `Bad arguments`.

**Comment by Pawloland** [comment]
> > ```
> > settings put secure always_on_vpn_app com.tailscale.ipn
> > 
> > settings put secure always_on_vpn_lockdown 0
> > 
> > settings put secure always_on_vpn_lockdown_whitelist
> > ```
> 
> Everything here works except the last argument `settings put secure always_on_vpn_lockdown_whitelist` the TV spits back `Bad arguments`.
> 
> Guessing it should be `settings put secure always_on_vpn_lockdown whitelist`
> 
> 

Sorry I missed empty string `''` it should be
```
settings put secure always_on_vpn_lockdown_whitelist ''
``` 
I will edit previous comment. Thanks for the info.

**Comment by ellnic** [comment]
@Pawloland thanks for this. 

However, I am getting an error “unknown command settings”. This is on an Nvidia shield. I would be interested to know if anyone else with a shield can get this working. I know that I am interfaced with adb properly because I use “adb reboot -p” all the time from Home Assistant to gracefully shut down before killing power. 

Any ideas?

**Comment by Pawloland** [comment]
> @Pawloland thanks for this. 
> 
> However, I am getting an error “unknown command settings”. This is on an Nvidia shield. I would be interested to know if anyone else with a shield can get this working. I know that I am interfaced with adb properly because I use “adb reboot -p” all the time from Home Assistant to gracefully shut down before killing power. 
> 
> Any ideas?

My guess is that you aren executing this command from adb shell but from local shell or on the PC that you try to connect from to the tv. You need to run `adb connect _IPv4:port_` to connect to the tv, then type `adb shell` to enter, well, adb shell, and from there execute those commands.

You could also do it like `adb connect _IPv4:port_`  and then 3 times pass execution of those commands to adb shell like `adb shell "setting put secure _x_ _y_"` and if `_y_` is empty string it will have to be passed like `''`, to properly escape the quotes. 

Make sure that any `&& || ;; |` shell special words are also in the correct quotes, if you use those.

**Comment by ellnic** [comment]
@Pawloland ahh yes, it was an error on my end. I had connected to the device (adb connect x.x.x.x) but then had not entered the shell before typing commands. Thanks! I’m not predominantly an android user so occasionally these things trip me up. Out of interest, if we should want to disable this, any idea what commands we would issue?

**Comment by bobmarley2021** [comment]
@agottardo I recently updated to the latest beta but there is still no auto connect so I am using the workaround provided by @Pawloland - is there any chance of this being integrated into the app?

**Comment by Pawloland** [comment]
> @Pawloland ahh yes, it was an error on my end. I had connected to the device (adb connect x.x.x.x) but then had not entered the shell before typing commands. Thanks! That works nicely now :-) 
> 
> I’m not predominantly an android user so occasionally these things trip me up. 
> 
> Out of interest, if we should want to disable this, any idea what commands we would issue?

settings delete secure always_on_vpn_app

settings delete secure always_on_vpn_lockdown

settings delete secure always_on_vpn_lockdown_whitelist

**Comment by ellnic** [comment]
> > @Pawloland ahh yes, it was an error on my end. I had connected to the device (adb connect x.x.x.x) but then had not entered the shell before typing commands. Thanks! That works nicely now :-)
> > I’m not predominantly an android user so occasionally these things trip me up.
> > Out of interest, if we should want to disable this, any idea what commands we would issue?
> 
> settings delete secure always_on_vpn_app
> 
> settings delete secure always_on_vpn_lockdown
> 
> settings delete secure always_on_vpn_lockdown_whitelist

Great, thanks 👍

**Comment by casperfrx** [comment]
> If the Android TV version is new enough it most probably will have the same always on VPN functionality as the equivalent mobile version of Android (provided the manufacturer haven't removed it explicitly, but most of the haven't). On Android TV there just isn't a gui to enable it in the settings like with the accessibility settings. It can be done inside adb shell.
> 
> 1. Enter adb shell.
> 2. While inside execute:
> 
> ```
> settings put secure always_on_vpn_app com.tailscale.ipn
> 
> settings put secure always_on_vpn_lockdown 0
> 
> settings put secure always_on_vpn_lockdown_whitelist ''
> ```
> 
> After this open tailscale app, connect and reboot TV. After this tailscale should connect automatically.

This is great, thanks so much for sharing this workaround!

**Comment by githubfan1960** [comment]
Yes, my thanks also!

I used the commands on 2 TV boxes and they both restart now with Tailscale connected :)

If you're using Scrcpy on Windows you can enter the commands like this in powershell:
./adb connect LAN_IP_or_Tailscale_IP
./adb shell settings put secure always_on_vpn_app com.tailscale.ipn
./adb shell settings put secure always_on_vpn_lockdown 0
./adb shell "settings put secure always_on_vpn_lockdown_whitelist ''"

I also learned that I can put the devices in standby/wakeup mode with adb commands: 
./adb shell input keyevent KEYCODE_SLEEP
./adb shell input keyevent KEYCODE_WAKEUP

**Comment by flynut** [comment]
I am trying this on my Firestick 4K.   All goes well but after a reboot Tailscale gets stuck when loading.    If i clear the app data and cash it will work again but hangs up again on reboot.    Any ideas of what is going on and how to fix it.    Thanks, Jason

**Comment by ghost** [comment]
For those who don't want to do this with adb, a simple method is by using a custom launcher like projectivity. Click on app > start on boot.

**Comment by whitedavidp** [comment]
> > If the Android TV version is new enough it most probably will have the same always on VPN functionality as the equivalent mobile version of Android (provided the manufacturer haven't removed it explicitly, but most of the haven't). On Android TV there just isn't a gui to enable it in the settings like with the accessibility settings. It can be done inside adb shell.
> > 
> > 1. Enter adb shell.
> > 2. While inside execute:
> > 
> > ```
> > settings put secure always_on_vpn_app com.tailscale.ipn
> > 
> > settings put secure always_on_vpn_lockdown 0
> > 
> > settings put secure always_on_vpn_lockdown_whitelist ''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this open tailscale app, connect and reboot TV. After this tailscale should connect automatically.
> 
> This is great, thanks so much for sharing this workaround!

Yeah! This works on my Android x86 (v9) in a virtual box. Thanks!
