### ISSUE TITLE
`tailscale ssh` on ubuntu closes tmux panes on disconnection

### ISSUE THREAD

**Issue by mfrw** [tailscale/tailscale#5103]
### What is the issue?
Using `tailscale ssh` & getting disconnected closes the active tmux pane.

I did not expect my tmux panes to die.

I started to notice after upgrade to `1.28.0`

### Steps to reproduce

enable tailscale ssh on ubuntu 18.04
`tailscale up --ssh`

Fire up tmux.

Disconnect from ssh.

Reconnect & try to attach. Ideally the tmux session with a single pane should be still present, but for some reason its gone.
I verified by disabling `tailscale ssh`

### Are there any recent changes that introduced the issue?

NA

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.28.0

### Bug report

BUG-1bfedc1b9a338c83d8f5092933f540398470ac81a87f02a4826acde140b9acfa-20220720171034Z-a88c4435ea736436

**Comment by bradfitz** [comment]
Can you include more steps in what you did?

Which SSH client did you use? How did you invoke it? By typing `ssh` or `tailscale ssh`? From which OS?

/cc @maisem

**Comment by mfrw** [comment]
Ahh, sure;

The exact steps are ..
ssh to an archlinux box from windows using `Tabby/WIndows Terminal`. From the archlinux box `ssh ubuntu`.
I tried `tailscale ssh ubuntu` as well;
Once I am logged in the ubuntu box; I fire up tmux.
If at this point I close the `terminal` (simulate disconnection); it seems to close the tmux pane. Logging back in and reattching tmux fails. If there are more than 1 panes in a tmux window; disconnection kills the active window.
The only change I can think of is upgrading to `1.28.0`, rest nothing apparently changed in my system.
Also my ubuntu version is `18.04.6 LTS` with no pending updates as of today :)

I hope this information is sufficient.

**Comment by samabsalom** [comment]
Just to add in that I have also upgraded to 1.28.0 and am having the same behaviour. 

I have used MacOS Terminal and Termius from mac/android to ssh to my UnRAID server running tmux. 

As above what happens is that on disconnect from ssh session it seems to close whatever is active on my tmux. If i create a pane inside a page then it closes only one of them and persists the other. This only seems to happen when i suddenly disconnect or lose a connection. if i dettach from tmux first this doesnt happen. 

regular ssh to a local ip does not do this. If i ssh to a tailscale IP or using the tailscale ssh command then it does.

Thanks

**Comment by bradfitz** [comment]
@maisem, @raggi, is this because of the new EOT write to stdin? https://github.com/tailscale/tailscale/blob/90ccba673083c8b6f1a2aabb60527069fe63bfa5/ssh/tailssh/tailssh.go#L1045

**Comment by bradfitz** [comment]
I can repro with `screen`.

If I ssh over Tailscale and run `screen -S foo` and then type `echo hi` + `<enter>` and `~.` to kill my SSH session, if I ssh back in over Tailscale and `screen -S foo -d -r`, that named screen session's gone.

If I ssh without Tailscale SSH, it doesn't even recognize the `~.` command. So something something termcap also.

But back to reproducing, if I ssh without Tailsacle and do the same above but then instead of `~.` kill my ssh client process locally and reconnect, the `foo` screen session is still alive.

**Comment by DentonGentry** [comment]
I can reproduce this with tmux.

**Comment by IsaacKhor** [comment]
Reproduced with tmux 2.6 on 1.30.2 with ubuntu 18.04 server and client macos 12.6 client. Non-tailscale SSH behaves as expected with tmux not affected by a disconnected client, so the workaround is just to use `--ssh=false`.
