### ISSUE TITLE
ssh/tailssh: nil ptr crash in evaluatePolicy during OnPolicyChange

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5110]
Tailscale SSH bug crashed tailscaled... (running at dev build at HEAD, d8cb5aae1720c3edc5e30f77b5fc7634e940a252)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0a2e8]

goroutine 11621 [running]:
tailscale.com/ssh/tailssh.(*conn).matchRule(0xc0004d4210, 0xc000623f50, {0x0, 0x0})
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:1129 +0x88
tailscale.com/ssh/tailssh.(*conn).evalSSHPolicy(0xc0004d4210?, 0x970aa8f3345b3978?, {0x0, 0x0})
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:1099 +0x76
tailscale.com/ssh/tailssh.(*conn).evaluatePolicy(0x25c52f371966900c?, {0x0, 0x0})
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:432 +0x47
tailscale.com/ssh/tailssh.(*conn).isStillValid(0xc0004d4210)
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:764 +0x26
tailscale.com/ssh/tailssh.(*conn).checkStillValid(0xc0004d4210)
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:777 +0x25
created by tailscale.com/ssh/tailssh.(*server).OnPolicyChange
        /home/bradfitz/src/tailscale.com/ssh/tailssh/tailssh.go:144 +0xd0
```

/cc @maisem

**Comment by maisem** [comment]
I don't see how yet.
It's saying something is `nil` here, and the only thing that can be `nil` is `c.info`

https://github.com/tailscale/tailscale/blob/43f3a969ca71c5769aeca6c2ee6bc283a504acd1/ssh/tailssh/tailssh.go#L1129

But `c.info` is set very early on when the client initiates the connection and is never modified.

https://github.com/tailscale/tailscale/blob/43f3a969ca71c5769aeca6c2ee6bc283a504acd1/ssh/tailssh/tailssh.go#L201-L210

https://github.com/tailscale/tailscale/blob/43f3a969ca71c5769aeca6c2ee6bc283a504acd1/ssh/tailssh/tailssh.go#L401-L423

**Comment by maisem** [comment]
Oh, I guess if a client initiates a connection but never goes through `none` auth we could get in a weird state.
