### ISSUE TITLE
FR: Make it easier for tailscaled to set --port at startup

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#5114]
### What are you trying to do?

This came out of a support issue. The user has an uncooperative firewall and ended up running `tailscaled --port` manually. They would like `tailscaled` to use the `--port` option every time it starts.

This is not very intuitive to set up on Windows (though entirely possible if you know the right commands).

### How should we solve this?

Their feature request is to be able to save the `--port` setting persistently (either via command line, GUI, or both) so that tailscaled always uses that preferred setting when it starts.

### What is the impact of not solving this?

In this case, the user disabled `tailscaled`'s entry in the service control manager and is instead using the Windows Task Scheduler to start `tailscaled` automatically with their preferred port configuration.

**Comment by DentonGentry** [comment]
I think it doesn't store the port in the config now because the config is opened too late. We could try to open the config earlier, or maybe close and reopen the port in question after we've read the config.

Or I guess add a registry key for the Windows Service port number, though that seems oddly platform specific.

**Comment by bradfitz** [comment]
I thought we already had support for reading a file of env vars or flags from disk for Windows and/or macOS to approximate the Linux `/etc/default/tailscaled` story. But I sure can't find it. Maybe we'd just talked about it.

**Comment by bradfitz** [comment]
> I thought we already had support for reading a file of env vars or flags from disk for Windows and/or macOS to approximate the Linux /etc/default/tailscaled story. But I sure can't find it. Maybe we'd just talked about it.

Ah, yes, I'd done a lot of this already in b03170b901b1bb89f815e589750a76ea4a2254bf for #3688

But I guess it doesn't work with the envknob package globals, so I'll tie that and 74674b110daeb2cdda6f76ad3d69ef4cfba6e5b9 together.

/cc @andrew-d

**Comment by bradfitz** [comment]
Seems like this happened in 1.32.0.

Put `PORT=1234` in `C:\ProgramData\Tailscale\tailscaled-env.txt` and restart the Tailscale service (`net stop Tailscale`, `net start Tailscale`)

**Comment by misaligar** [comment]
https://tailscale.com/kb/1011/log-mesh-traffic?tab=macos this page links here for disabling logs using Tailscale on macOS. I don't understand what I should be doing here. Can someone please help?

**Comment by vickunwu** [comment]
> https://tailscale.com/kb/1011/log-mesh-traffic?tab=macos this page links here for disabling logs using Tailscale on macOS. I don't understand what I should be doing here. Can someone please help?

@meminens I looked into the code base and found out to right location to put the env file on MacOS. You can check this [link](https://github.com/tailscale/tailscale/blob/86f273d930df52440641ef2397f0f7ebca648d7c/envknob/envknob.go#L494-L511)
