### ISSUE TITLE
OpenAPI specification

### ISSUE THREAD

**Issue by toonsevrin** [tailscale/tailscale#513]
I've started an [OpenAPI](https://github.com/kubescale/server-openapi) specification to help myself and others understand how the client communicates with the control plane.

Currently the specification is pretty bad. For example: I wrongly assumed how json.Marshal encoded field names (I'd assume it would lowercase the first letter in fields). All contributions are thus more then welcome.

If the Tailscale team is interested in this, we can move the repository under /tailscale.

**Comment by bradfitz** [comment]
Be warned that we dislike our current control plane protocol at the moment, which is a big part of why we haven't documented it. We plan to change basically all of it. (It's a little too verbose and inefficient right now.)

So you're welcome to proceed, but we don't want you to feel like you wasted a bunch of time on it when you're surprised by a big change later.

**Comment by toonsevrin** [comment]
That's very good to know: Luckily I didn't waste that much time on this (if you take a look at the spec, it's actually pretty bad). Anyways, I'll leave the specification as it is for now and others should thus not contribute further.

A stable API for the essentials would be very much appreciated. My company is interested in using tailscale as the networking component for a product we have been thinking about developing for a while. Fyi: It's basically the tailscale philosophy but instead of a VPN control plane, we provide a kubernetes control plane, and you can type "kubescale up" on any node, making that node a worker in the cluster as by magic). In my opinion plain awesome and definitely worth buying out at some point :smile:

Anyways, at least for the discovery protocol (the request an already authorized node makes to get a sense of the network map), some protocol stability would be very much appreciated!
