### ISSUE TITLE
cmd/tsconnect: Allow auth key to be passed in

### ISSUE THREAD

**Issue by mihaip** [tailscale/tailscale#5144]
Allow `AuthKey` for the `ipn.Options` at https://github.com/tailscale/tailscale/blob/898695e312ddbe670ac9e35c5b1ea0f4df6ab797/cmd/tsconnect/wasm/wasm_js.go#L209-L221 to be passed in.

May want to allow reading it from a query parameter in dev mode, but in prod mode we should probably have it be passed in via JS/`postMessage`, so that it doesn't get logged or otherwise leak too easily.

**Comment by mihaip** [comment]
In dev mode, reading it from the query string on the JS side and then adding it to the `IPNConfig` that gets passed to `newIPN` would be a good start.

**Comment by catzkorn** [comment]
Ty! Going to work on this tomorrow

**Comment by mihaip** [comment]
This is done.
