### ISSUE TITLE
FR: Add RHEL9 to the "Download" page

### ISSUE THREAD

**Issue by eugene1g** [tailscale/tailscale#5158]
### What are you trying to do?

While installing Tailscale on RHEL9, I found out that the Download page at https://tailscale.com/download/linux/rhel-8 only has RHEL8 as an option. 

### How should we solve this?

Tailscale already officially supports RHEL9 with the package repository at `https://pkgs.tailscale.com/stable/rhel/8/tailscale.repo`. All that's required is to update the Downloads page to show the option for this repository.

### What is the impact of not solving this?

Users might assume RHEL9 is not supported because it's relatively new.

**Comment by DentonGentry** [comment]
I brought this up in a different tracking system for the website.

<img width="615" alt="Screen Shot 2022-07-24 at 8 38 18 AM" src="https://user-images.githubusercontent.com/1140756/180655048-28936e04-8357-4cc9-86c2-f05f0bf58833.png">
