### ISSUE TITLE
FR: automatically disable Ubuntu NetworkManager connectivity check to 35.232.111.17 over tailscale0

### ISSUE THREAD

**Issue by ldemailly** [tailscale/tailscale#5175]
### What is the issue?

lots of periodic error messages in /var/log/syslog

Jul 25 20:53:57 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:38702 => 34.122.121.32:80); no associated peer node
Jul 25 20:57:58 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54518 => 35.232.111.17:80); no associated peer node
Jul 25 20:58:01 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54518 => 35.232.111.17:80); no associated peer node
Jul 25 20:58:13 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54518 => 35.232.111.17:80); no associated peer node
Jul 25 21:02:58 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54520 => 35.232.111.17:80); no associated peer node
Jul 25 21:03:01 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54520 => 35.232.111.17:80); no associated peer node
Jul 25 21:03:13 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54520 => 35.232.111.17:80); no associated peer node
Jul 25 21:07:58 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54526 => 35.232.111.17:80); no associated peer node
Jul 25 21:08:01 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54526 => 35.232.111.17:80); no associated peer node
Jul 25 21:08:13 moorea-S3 tailscaled[966]: open-conn-track: timeout opening (TCP 100.96.229.119:54526 => 35.232.111.17:80); no associated peer node

$ tailscale bugreport
BUG-c9d7704c0e74f53149810f3fe5f3f8bf603aa4f6f8340effbf528c359eafe361-20220726041549Z-a2db05f7da4c6140

$ host connectivity-check.ubuntu.com
connectivity-check.ubuntu.com has address 35.224.170.84
connectivity-check.ubuntu.com has address 34.122.121.32
connectivity-check.ubuntu.com has address 35.232.111.17

### Steps to reproduce

ubuntu 22.04 seems like it's doing some check for net access and failing (on the tailscale interface maybe?)

### OS

Linux

### OS version

5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Tailscale version

1.28.0   tailscale commit: 80313cdee14dee22452ea2b278e7bbcfe4af1a9c   other commit: d26dd4a68f4c18686b003051acd7e44d8788a4b7   go version: go1.18.4-ts149f7d88f1

### Bug report

BUG-c9d7704c0e74f53149810f3fe5f3f8bf603aa4f6f8340effbf528c359eafe361-20220726041549Z-a2db05f7da4c6140

**Comment by bradfitz** [comment]
Apple does something similar we had to work around.

@danderson, @xe, @twitchyliquid64, know how to prevent NetworkManager or whatever from doing that on an interface?

**Comment by DentonGentry** [comment]
Network test environments also frown on NetworkManager sending these test probes, so: https://support.qacafe.com/knowledge-base/how-do-i-prevent-network-manager-from-controlling-an-interface/

**Comment by DentonGentry** [comment]
NetworkManager VPN DBus API https://developer-old.gnome.org/NetworkManager/stable/vpn-plugins.html
Oriented around connecting and disconnecting traditional-shaped VPNs. No mention of the connectivity check.

**Comment by DentonGentry** [comment]
Unfortunately I don't think there is a way to turn off the Connectivity Check for just one specific interface, it is either globally on or off.

I wouldn't really want tailscaled to turn it off globally. That is making a choice for the sysadmin that I don't think we should make. The connectivity check messages are annoying but essentially harmless.

**Comment by DentonGentry** [comment]
At this point I do not believe this feature request is feasible. We would have to turn off the Connectivity Check for all interfaces, which seems undesirable and is not something we would do automatically.

The log messages about timeouts to 34.122.121.32 and 35.232.111.17 are annoying, but ultimately harmless.
