### ISSUE TITLE
MacOS route of `100.64/10` can break niche setups

### ISSUE THREAD

**Issue by tkyocum** [tailscale/tailscale#5184]
### What is the issue?

My environment is admittedly weird, but as a means to have access to two Tailscale networks simultaneously, the below configuration used to work:

- MacOS Tailscale client connects to `Account A`
- Home router (EdgeRouter4) runs Tailscale client to connect to `Account B`

Clients behind the EdgeRouter could reach `Account B` nodes and the workstation(s) with MacOS client installed could access `Account A` via the tunnel on the workstation itself or nodes on `Account B` via the EdgeRouter.

It appears that the addition of the `100.64/10` route in 1.28.0 will cause this type of setup to fail: MacOS clients will have access to the Tailnet they connect to, but not Tailnets routed elsewhere (or for that matter, any other CGNAT space). 

My curiosity leads me to ask if the routes installed could be modified to be more specific to account for scenarios where CGNAT space is used but not routed directly at the workstation level.

### Steps to reproduce

- Started tailscale client on MacOS
- Observed connectivity to Tailnet that I've logged into on MacOS to succeed
- Observed simultaneously traffic to Tailnet logged into and reached via gateway router stops
- Stopped tailscale client on MacOS
- Observed traffic to Tailnet reached by router resume

The above is expected as the 100.64/10 route gets removed.

### Are there any recent changes that introduced the issue?

Per changelog:

> Use one large 100.64.0.0/10 route entry if there are no other interfaces using CGNAT, to avoid Network Changed errors in browsers where possible

### OS

macOS, Other

### OS version

macOS 12.4

### Tailscale version

1.28.0

**Comment by bradfitz** [comment]
Could we change the heuristic in a way that would accomodate you?

**Comment by mihaip** [comment]
@tkyocum We attempt to detect other interfaces may be be handling CGNAT addresses (see heuristic from https://github.com/tailscale/tailscale/commit/ec649e707f2f111fd01ca649f3e0b5fe867fde99). Could you include the output of `ifconfig` to see if there is anything that we missed?

**Comment by tkyocum** [comment]
Hmm. The rub is that the router handling the other address space isn’t on the local Mac, so I don’t know how that would be detected so that the client avoids an over-broad route.

**Comment by DentonGentry** [comment]
The App Store doesn't allow downgrades back to 1.26.x, but you could switch to the macsys version of the app if you need to get this setup working again: https://pkgs.tailscale.com/stable/Tailscale-1.26.2-macos.zip

Note that this setup can break eventually even if you stay with 1.26.2: there is no guarantee that the same 100.x.y.z address won't be used on the two tailnets (albeit statistically unlikely). Even using /32 routes as 1.26.2 does, you can end up with a conflict between the two tailnets. The one with the local /32 on the Mac will win.

**Comment by mihaip** [comment]
We do have a mechanism to allow overriding the CGNAT route behavior via an ACL JSON key, though currently it can only used to always enable it (via `OneCGNATRoute": "mac-always"`). We could also extend it to allow disabling it (this would be a control-only change).

**Comment by tkyocum** [comment]
> We could also extend it to allow disabling it

This would be super useful for my use case and others who use that IP space, especially in cases where the non-Tailscale CGNAT network will not show up in the local host's route table.

**Comment by mihaip** [comment]
@tkyocum This is now implemented, you should be able to add a `"OneCGNATRoute": "mac-never"` option to your ACL JSON to force it to use fine-grained routes.

**Comment by DentonGentry** [comment]
I'm going to close this as fixed. If there is still a problem, please reopen it.

If you come across this issue in the future, please don't comment on the closed bug as we are likely not to notice. If setting `"OneCGNATRoute": "mac-never"` in https://login.tailscale.com/admin/acls works for you then great, otherwise please open a new  issue describing the situation.

**Comment by tkyocum** [comment]
Thank you very much, @mihaip -- this worked as expected. I understand that it's suboptimal given the reason this was put in place to begin with, but it's a good compromise until account sharing functionality gets to where simultaneous tailnets are accessible (e.g., sharing an exit node or similar).

**Comment by DentonGentry** [comment]
Note that sharing exit nodes between tailnets does work: https://tailscale.com/kb/1084/sharing/#sharing--exit-nodes

**Comment by tkyocum** [comment]
You are correct as always. I misspoke -- I meant subnet-relayed traffic (https://tailscale.com/kb/1084/sharing/#sharing--subnets-subnet-routers) not exit nodes.
