### ISSUE TITLE
util/deephash: make genTypeHasher func fail fast on unsupported types

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5191]
https://github.com/tailscale/corp/issues/6311 led me to rediscover something I'd noticed and forgotten earlier:

`genTypeHasher` returns a `typeHasherFunc` that reports whether it handled the value at runtime:

```
// returns ok if it was handled; else slow path runs
type typeHasherFunc func(h *hasher, v reflect.Value) (ok bool)
```

There are two reasons it can return false:

* the data structure at runtime is found to not be supported by the fast paths (e.g. can't Addr or Interface)
* the types itself aren't supported (e.g. maps or interfaces or pointers to recursive structures)

Consider a case like generating a hasher for `*struct{ a, b, c, d, e, f, g string; foo map[string]string }`: we return a func that hashes `a, b, c, d, e, f, g` only then to fail (return false) at runtime on `foo`, even though we could've known we would've gone into the slow path earlier.

We should try to return false as early as possible to avoid doing redundant hashing work in both the fast & slow paths.

/cc @dsnet @maisem

**Comment by dsnet** [comment]
I propose we do the opposite and make these always addressible and use unsafe and forcibly export fields so that the interface value is always obtainable. If you'd like, I can do that work.

**Comment by bradfitz** [comment]
Pointer cycles and interfaces and maps remain unhandled in the fast path.

Forcing addressability doesn't help that.

**Comment by dsnet** [comment]
How hard would it be to implement cycle-detection logic in the fast path such that there is no concept of "slow path" anywhere?

**Comment by dsnet** [comment]
This is done. The `genTypeHasher` function no longer exists.
