### ISSUE TITLE
FR: install.sh - Add ARM Arch

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5192]
### What are you trying to do?

Add Arch/Manjaro Linux for ARM architecture

### How should we solve this?

packages already exist in pacman, need to recognize the OS.

**Comment by JayWStapleton** [comment]
NAME="Manjaro-ARM"
ID="manjaro-arm"
ID_LIKE="manjaro arch"
PRETTY_NAME="Manjaro ARM"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/c/arm/"
LOGO=manjarolinux

**Comment by bowmanjc** [comment]
Thanks Jay & Denton!
