### ISSUE TITLE
Android: crashes some Chromebooks upon opening

### ISSUE THREAD

**Issue by Smittyvb** [tailscale/tailscale#521]
**Describe the bug**
Upon opening the Tailscale app, my Chromebook crashes (not the app, my entire system restarts).

**To Reproduce**
1. Open the Tailscale app.

**Expected behavior**
It opens, and my system doesn't crash.

**Screenshots**
Video (I couldn't do a screen recording since there's no way to screen record in software through a crash in software): https://www.youtube.com/watch?v=Mkjk7E_NIOg

**Version information:**
 - Device: Acer Chromebook Spin 11
 - OS: Chrome OS
 - OS version: 83.0.4103.119 (Official Build) (64-bit)
 - Tailscale version: 0.1.10-g676447a

**Additional context**
This didn't start occuring for me until recently. This actually started on an earlier version (I am using the Play Store beta), but it persisted through an update. I _am_ able to run other Android apps on Cros. I'm also able to run Tailscale correctly on other Chromebooks.

I don't know if this is relevent to the issue, but I found lines similar to the following repeated ~20k times in my ARC log file:
```
log/audit/audit.log:type=AVC msg=audit(1593207465.064:7608): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="4768" dev="proc" ino=713829 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:wificond:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.064:7609): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="4769" dev="proc" ino=713830 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:hal_audio_default:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.064:7610): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="7592" dev="proc" ino=713831 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:zygote:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.065:7611): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="7593" dev="proc" ino=713832 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:audioserver:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.065:7612): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="7594" dev="proc" ino=713833 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:cameraserver:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.066:7613): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="7595" dev="proc" ino=713834 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:netd:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.066:7614): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="7596" dev="proc" ino=713835 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:netd:s0 tclass=dir permissive=0
log/audit/audit.log:type=AVC msg=audit(1593207465.067:7615): avc:  denied  { search } for  pid=4426 comm="m.tailscale.ipn" name="7597" dev="proc" ino=713836 scontext=u:r:untrusted_app:s0:c70,c256,c512,c768 tcontext=u:r:netd:s0 tclass=dir permissive=0
```

**Comment by bradfitz** [comment]
We should have no access to crash your Chromebook even if we wanted to. This seems like a bug that Google and/or Acer should work on.

I suppose we could try to avoid it, though, but that's not the real fix.

/cc @eliasnaur

**Comment by bradfitz** [comment]
We've ordered that laptop. Should have it tomorrow.

We'll likely escalate to the Chrome team as well.

But I can at least fix those permission errors.

**Comment by Smittyvb** [comment]
I've done some more testing and was able to resolve the issue by deleting all of Tailscale's storage and re-authenticating. Clearing just the cache made no impact. (battery discharging/charging/fully charged state also made no impact) I have no idea why that resolved the issue, though

**Comment by bradfitz** [comment]
Between 77cad13c70830392cccc100af0c59e18f68c2c21 and 33a748bec14eb38c6a46e49560096611ab17a3b8 I think the audit violation log entries are gone now. Let us know if you see more!
