### ISSUE TITLE
FR: Install x64 version on ARM64 devices when possible

### ISSUE THREAD

**Issue by conioh** [tailscale/tailscale#5218]
### What are you trying to do?

Trying to install Tailscale on a Windows ARM64 device. I get the Intel x86 version.
I want to get the AMD64 version.
It is reported that the x64 emulation has better performance than the x86 emulation, so that's what I want, at least until a native ARM64 version is available.

### How should we solve this?

The EXE installer should install the x64 binaries on ARM64 devices running Windows 11 instead of the x86 binaries.

### What is the impact of not solving this?

I have to find the x64 MSI installer and use it.
Not terrible, but the fix on your side isn't too hard either and might benefit others.

### Anything else?

The text on https://pkgs.tailscale.com/stable/#windows should probably be changed to say something like:

> - [tailscale-ipn-setup-1.28.0.exe](https://pkgs.tailscale.com/stable/tailscale-ipn-setup-1.28.0.exe)
> - [tailscale-setup-1.28.0-amd64.msi](https://pkgs.tailscale.com/stable/tailscale-setup-1.28.0-amd64.msi): 64-bit x86 (amd64) **and ARM64 only when running Windows 11**
> - [tailscale-setup-1.28.0-x86.msi](https://pkgs.tailscale.com/stable/tailscale-setup-1.28.0-x86.msi): 32-bit x86 and ARM64 **when running Windows 10 or Windows 11**

You can phrase it otherwise, but don't say or imply that only the x86 version works on ARM64.

You can say nothing at all and count on the users knowing which binaries can run on which platform and Windows version.
You can also help them with that, but in that case it's better to be precise rather than misleading, especially since the cost is so minor.

**Comment by DentonGentry** [comment]
[#2606](https://github.com/tailscale/tailscale/issues/2606) documents the effort to get native arm64 support building.

**Comment by DentonGentry** [comment]
The 1.30 release added an ARM64 native backend Windows Service in the NSIS installer tailscale-ipn-setup-1.30.0.exe.

The [unstable track](https://pkgs.tailscale.com/unstable/#windows) (and what will turn into the 1.32 release) adds a tailscale-setup-1.31.6-arm64.msi

**Comment by DentonGentry** [comment]
Tailscale 1.32 supplies an arm64 MSI: https://pkgs.tailscale.com/stable/#windows

I think that meets the intent of this issue, to improve support for Windows arm64.
