### ISSUE TITLE
FR: Print a QR code on the tailscale login screen

### ISSUE THREAD

**Issue by kevmo314** [tailscale/tailscale#5223]
### What are you trying to do?

I use tailscale to connect test embedded linux devices to a dev machine. Tailscale works great! I find that I often have to authenticate every time I reset the board and this gets a bit tedious to type in the URL manually. 

### How should we solve this?

Could you add a QR code to the terminal printout? That way I can scan it with my phone and it's a little slicker.

### What is the impact of not solving this?

Just manually typing in the URL.

**Comment by DentonGentry** [comment]
Does this do what you want: `tailscale up --qr` ?

**Comment by kevmo314** [comment]
> Does this do what you want: `tailscale up --qr` ?

Ohhhh neat! Didn't know that was a thing, is there a reason it's not the default?

**Comment by DentonGentry** [comment]
The set of people who really need a QR code is limited, but putting one on the screen by default would make all users wonder if they are supposed to use it. Descriptions of the experience of installing Tailscale would shift to looking for the phone.

Closing issue as addressed.

**Comment by bradfitz** [comment]
And there's already a link to a QR code on the login screen too:

<img width="641" alt="Screen Shot 2022-07-29 at 7 19 10 AM" src="https://user-images.githubusercontent.com/2621/181780067-074ced76-1336-4869-8bf9-b8a8a1b2e925.png">
