### ISSUE TITLE
Contribute instructions to tailscaled wiki page for installing a specific release tag

### ISSUE THREAD

**Issue by adamfeldman** [tailscale/tailscale#5225]
### What are you trying to do?

I recently learned how to install a release version of `tailscaled`, instead of HEAD as shown on [the wiki page]( https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS). I have contributed a proposed addition to the wiki page with this information.

For my use of `tailscaled`, it's strongly preferable to use a release rather than whatever is at the HEAD at installation time.

### How should we solve this?

Currently the [Tailscaled-on-macOS instructions]( https://github.com/tailscale/tailscale/wiki/) contain the following install command, which installs HEAD: 

>```$ go install tailscale.com/cmd/tailscale{,d}@main```

After that line on the wiki page, I propose adding the following:

> You may also install a specific tagged release:
>
>```$ go install tailscale.com/cmd/tailscale{,d}vX.Y.Z```

**Comment by DentonGentry** [comment]
We've updated https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS with a note about release versions.

One can also use homebrew: https://formulae.brew.sh/formula/tailscale

**Comment by hahacold** [comment]
> We've updated https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS with a note about release versions.
> 
> One can also use homebrew: https://formulae.brew.sh/formula/tailscale

hi DentonGentry I followed this page
https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS
after I ran
$ go install tailscale.com/cmd/tailscale{,d}@main
and
$ sudo $HOME/go/bin/tailscaled install-system-daemon

And commands below didn't work
$ tailscale up       # (any optional arguments)
$ tailscale status

I thought I should do brew install tailscale too, after few days using, I realized I was misunderstanding , I. downloaded two tailscale.

But as I said, commands didn't work.

**Comment by bradfitz** [comment]
This issue is long closed. If you have a bug to report, open a new one please.
