### ISSUE TITLE
openssh not working in tailscale/tailscale image with userspace networking

### ISSUE THREAD

**Issue by Starttoaster** [tailscale/tailscale#5233]
### What is the issue?

Running the `tailscale/tailscale` container with userspace networking, tailscale ssh only works using the `tailscale ssh` subcommand. Using a system package manager installed openssh does not work.

### Steps to reproduce

Run a shell inside a tailscale container:

```
docker container run --rm -it tailscale/tailscale /bin/sh
```

Now inside a shell in the tailscale image, set up tailscale:

```
tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055 &
tailscale up --authkey=${TAILSCALE_AUTH_KEY}
```

Install openssh:

```
apk update
apk add openssh
```

Now run any ssh command to a tailscale host (via tailnet IP or hostname):

```
ssh user@host
user@host: Permission denied (tailscale).
```

Weirdly, it works using tailscale's bundled ssh subcommand:

```
tailscale ssh user@host
user@host:~$
```

### Are there any recent changes that introduced the issue?

I was kind of hoping somebody would tell me.

### OS

Linux

### OS version

Ubuntu 22.04, Ubuntu 20.04

### Tailscale version

1.28.0 (on both the SSH clients and servers)

**Comment by Starttoaster** [comment]
Here's some verbose output in case it helps:

```
/ # ssh bb@nuc1 -v
OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to nuc1 [100.85.216.39] port 22.
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
debug1: Remote protocol version 2.0, remote software version Tailscale
debug1: compat_banner: no match: Tailscale
debug1: Authenticating to nuc1:22 as 'bb'
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:U9wIJRUGn/A4mIFizbyOIkmSb/IBPPrht9zPANmIwGc
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'nuc1' is known and matches the ED25519 host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /root/.ssh/id_rsa
debug1: Will attempt key: /root/.ssh/id_ecdsa
debug1: Will attempt key: /root/.ssh/id_ecdsa_sk
debug1: Will attempt key: /root/.ssh/id_ed25519
debug1: Will attempt key: /root/.ssh/id_ed25519_sk
debug1: Will attempt key: /root/.ssh/id_xmss
debug1: Will attempt key: /root/.ssh/id_dsa
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: tailscale
debug1: No more authentication methods to try.
bb@nuc1: Permission denied (tailscale).
/ #
```

Worth noting that this happens whether or not I use an auth key or do the browser login flow.

**Comment by bradfitz** [comment]
It's not clear to me in your example(s) above which machines and/or containers are the source and the destination.

Can you elaborate?

**Comment by bradfitz** [comment]
Also, please include some `tailscale bugreport` lines from both sides right after it happens.

**Comment by Starttoaster** [comment]
> It's not clear to me in your example(s) above which machines and/or containers are the source and the destination.
> 
> Can you elaborate?

The source, as described in the reproduce instructions, is a docker container. The official tailscale/tailscale image hosted on Docker Hub.

The destination is any baremetal Linux server with Tailscale installed.

**Comment by Starttoaster** [comment]
Just started another container and followed the steps described in my reproduce instructions to make a bugreport :)
```
/ # tailscale bugreport
user bugreport: BUG-8136c335699ff0e2c9096397fe3dd88048ff4ebd0b730defd648ad55a02b2d4a-20220730051451Z-2dd83abfaec9a325
BUG-8136c335699ff0e2c9096397fe3dd88048ff4ebd0b730defd648ad55a02b2d4a-20220730051451Z-2dd83abfaec9a325
```

**Comment by bradfitz** [comment]
If you're ssh'ing _from_ a container that's using `userspace-networking`, you can't just connect to anything you want directly with `ping` or `curl` or `ssh` or anything not using your SOCK5 and/or HTTP proxy that you're running with ` --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055`.

So that's why `tailscale ssh` works: it sets the OpenSSH client's `ProxyCommand` to dial through your container's `tailscaled`.

So this is expected.

The only reason you're probably able to resolve `host` at all from within the container is that I bet your docker container's host is running Tailscale as well, and passing its DNS config & routes into your container, depending on how you're running it.

**Comment by Starttoaster** [comment]
> If you're ssh'ing _from_ a container that's using `userspace-networking`, you can't just connect to anything you want directly with `ping` or `curl` or `ssh` or anything not using your SOCK5 and/or HTTP proxy that you're running with ` --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055`.
> 
> 
> 
> So that's why `tailscale ssh` works: it sets the OpenSSH client's `ProxyCommand` to dial through your container's `tailscaled`.
> 
> 
> 
> So this is expected.
> 
> 
> 
> The only reason you're probably able to resolve `host` at all from within the container is that I bet your docker container's host is running Tailscale as well, and passing its DNS config & routes into your container, depending on how you're running it.
> 
> 
> 
> 

Hey, long time no talk. My bad for leaving you hanging. I was waiting on a response for the other side of my problem here which is basically a k8s deployment tool that operates over SSH, named k0sctl. I think I'm good with closing this Issue as you explained perfectly why it works with `tailscale ssh`, so now I just need to figure out how to make k0sctl work with userspace networking, which is totally not your problem. Have a nice week!
