### ISSUE TITLE
macOS: switch to /32 routes if CGNAT endpoints are added via portmapping

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#5236]
### What is the issue?

There exist combinations of residential gateway and ISP using CGNAT which can return a CGNAT address in response to a portmapping request:
```
2022-07-30 17:53:58.031682 +0300 +0300: portmapper: Got PMP response; IP: 100.125.87.73, epoch: 356049
```

One such system at the time of this writing is 9e9edaec84b862cabac8b4439bc4e02e4b78474ce330aba283afe001a4b8755e, a macOS machine.

This turns into advertising a CGNAT address as an endpoint:
`2022-07-30 18:00:57.544102 +0300 +0300: magicsock: endpoints changed: 100.125.87.73:41641 (portmap), 5.x.y.z:49935 (stun), 5.x.y.z:41641 (stun4localport), 192.168.50.212:41641 (local)`

I'm not sure how much difficulty this really causes, but clearly the CGNAT endpoint isn't going to work for DISCO.

### Bug report

9e9edaec84b862cabac8b4439bc4e02e4b78474ce330aba283afe001a4b8755e

**Comment by bradfitz** [comment]
Hah. I mean, it _might_ work between two nodes on, say, the same mobile network. But more likely there's a better path (like IPv6) anyway.

But yeah, easy enough to ignore those.

**Comment by danderson** [comment]
Yeah, the CGNAT endpoint can work, for two customers of the same CGNAT-using ISP. It's one of a few days to get through double NAT. We should propagate those endpoints and let the peers try, it's no more harm than any other candidate endpoint.

**Comment by DentonGentry** [comment]
This is a case which we could detect for macOS when deciding whether to use a /10 or/32 route entries.

**Comment by danderson** [comment]
This shouldn't matter though. Executing in the NetworkExtension, traffic automatically bypasses Tailscale's routes unless we explicitly opt a socket into using Tailscale routes. So, the presence of CGNAT addrs at the tunnel-forming layer should have no interference at all on connectivity within Tailscale, or vice versa.
