### ISSUE TITLE
Tailscale connected, but network traffic doesn't reach destination on linux

### ISSUE THREAD

**Issue by fuergaosi233** [tailscale/tailscale#5238]
### What is the issue?

I’m using tailscale and flannel to run my k8s cluster, but after running for a while, the worker node can’t connect to the master node, after testing I can’t ping the master node in the worker node, but if I use tailscale ping I can ping through.
![image](https://user-images.githubusercontent.com/22197568/181935472-fa9ed9b8-62bb-4a26-b627-d4c1db2f1fd7.png)

### Steps to reproduce

I don't know how to trigger it, and how to reproduce it

### Are there any recent changes that introduced the issue?

I ran flannel and specified tailscale0 for iface

### OS

Linux

### OS version

Linux node1 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Tailscale version

1.28.0

**Comment by bradfitz** [comment]
There's not really enough information here to help debug anything.

> but after running for a while

Are these nodes in mainland China? You might be hitting the Great Firewall.

**Comment by fuergaosi233** [comment]
> There's not really enough information here to help debug anything.
> 
> > but after running for a while
> 
> Are these nodes in mainland China? You might be hitting the Great Firewall.

Yes, I'm in China, but after I tried to uninstall the k8s cluster, he's back to normal, and I don't think it's related to GFW.

**Comment by fuergaosi233** [comment]
> > There's not really enough information here to help debug anything.
> > > but after running for a while
> > 
> > 
> > Are these nodes in mainland China? You might be hitting the Great Firewall.
> 
> Yes, I'm in China, but after I tried to uninstall the k8s cluster, he's back to normal, and I don't think it's related to GFW.

Can you provide me with some ideas for further Debug? I can only find the problem by constantly modifying the parameters.

**Comment by bradfitz** [comment]
"modifying the parameters"? Which parameters?

Unless there's a specific bug, we're unlikely able to help.

**Comment by fuergaosi233** [comment]
> "modifying the parameters"? Which parameters?
> 
> Unless there's a specific bug, we're unlikely able to help.

I'm constantly tweaking Flannel parameters, such as Vxlan mode or host-gw mode, and I'm having trouble connecting after a while.
I think there might be a conflict between the CNI of K8s and some configuration of Tailscale, but I don't know how to find the conflicting part.

**Comment by bradfitz** [comment]
I'm not sure anybody at Tailscale knows Flannel well enough to help debug this.

But if it works for a bit and then stops working, it's either a China GFW issue or we'd need a `tailscale bugreport` line just about the time it stops working to see if Tailscale did anything.

/cc @maisem

**Comment by fuergaosi233** [comment]
> I'm not sure anybody at Tailscale knows Flannel well enough to help debug this.
> 
> But if it works for a bit and then stops working, it's either a China GFW issue or we'd need a `tailscale bugreport` line just about the time it stops working to see if Tailscale did anything.
> 
> /cc @maisem

In my screenshot, I am using tailscale ping which is working fine, while in another device on the same LAN with Talscale installed, ping and tailscale ping are working fine.

**Comment by fuergaosi233** [comment]
> I'm not sure anybody at Tailscale knows Flannel well enough to help debug this.
> 
> But if it works for a bit and then stops working, it's either a China GFW issue or we'd need a `tailscale bugreport` line just about the time it stops working to see if Tailscale did anything.
> 
> /cc @maisem

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/22197568/181936368-19ae0b31-9ce0-424d-be79-cf88bce19a42.png">
I'll try to draw a diagram to illustrate the problem I'm currently experiencing

**Comment by fuergaosi233** [comment]
As a side note, when I first finished the deployment, the worker and master were accessible to each other.

**Comment by fuergaosi233** [comment]
```
tailscale bugreport
BUG-1c7240621359499a29d3bc22f791cc6919bd4f171c0af3f200ec904465c87a15-20220730181904Z-eef83aeb792eb5e8
```

**Comment by fuergaosi233** [comment]
Resolved by reset the network configuration
