### ISSUE TITLE
Unable to install system daemon m2 backbook pro

### ISSUE THREAD

**Issue by johntdyer** [tailscale/tailscale#5240]
### What is the issue?

```
> sudo tailscaled install-system-daemon

W0731 08:45:57.362977    5176 native_arm64.go:52] Could not read /proc/cpuinfo: open /proc/cpuinfo: no such file or directory
W0731 08:45:57.363068    5176 native_arm64.go:177] Could not read /proc/self/auxv: open /proc/self/auxv: no such file or directory

 ~                                                                                                          08:45:57
>

```

### Steps to reproduce

```
> sudo tailscaled install-system-daemon
```

### Are there any recent changes that introduced the issue?

No, new computer

### OS

macOS

### OS version

12.6

### Tailscale version

1.29.0-dev

### Bug report

BUG-26de087b31ccb2ab3e446d956932453125f7273b4affe7d5652a8667aa072349-20220731134651Z-57f7c6ebeb8a81c8

**Comment by bradfitz** [comment]
How'd you build the binary?

**Comment by johntdyer** [comment]
go did a go install 

go install ***@***.***

**Comment by bradfitz** [comment]
Sure it didn't work? Those are warnings. Dumb warnings we should get removed but warnings.

What's echo $? say after you run that again?

**Comment by bradfitz** [comment]
I filed a bug about the warning: https://github.com/google/gvisor/issues/7849

**Comment by bradfitz** [comment]
> Bug report
> BUG-26de087b31ccb2ab3e446d956932453125f7273b4affe7d5652a8667aa072349-20220731134651Z-57f7c6ebeb8a81c8

That bug report is from a `macsys` (GUI, non-App Store) build. I suspect the system `tailscaled` installed fine but your `tailscale` CLI is talking to the GUI you're running. You need to run the matching `tailscale` binary to talk to your `tailscaled`.

I'm going to close this for now, as I don't see any concrete problem for us to fix.
