### ISSUE TITLE
FR: For the paid personal pro account have a way to have seperate accounts for machines

### ISSUE THREAD

**Issue by a30t** [tailscale/tailscale#5241]
### What are you trying to do?

I am trying not to use the administrator account to add in machines and have the log in on them. If used on a Lab/access machine this could compromise the network. After install on windows I rebooted the machine and was able to click the user in the Tailscal menu option and access the online network setup. Also a bit silly to use the admin account on the machine the use the same account to approve the node. Yes I just opened the browser and clicked appove.

### How should we solve this?

It appears you are aliening features to have people upgrade to a paid plan which is fair and probably your business model. Just think out how it will be used. If used on an "untrusted:" lab pc I would not want to use the keys to the kingdom to onboard it. Maybe all the interface to use the machine key and tags that are used for non interactive onboarding. This is the easy way. I only used it for one day, so I need to dig more, but it looks like you will be interfacing with user authentication systems rather than storing internally. Not sure, but then I would need to add users in a free tier of duo or similar system could be a solution.

### What is the impact of not solving this?

Possibly drop to the free tier. I have very few machines, wanted to support the project $50 a year was not bad if it solves some of the pain points I am having. Next question could be how to I drop to the free tier and remove my CC. I would probable join again, since WOW, this is such an easy system to onboard. Just don't want the availability of admin creds on lab, test, trying for fun, learning pcs and vms, etc into my real home network. I did not play with the ACLs yet but I assume the traffic/access can be filtered by json.

### Anything else?

Pretty neat solution for wireguard.

**Comment by DentonGentry** [comment]
I believe the feature request is probably best met using Tags: https://tailscale.com/blog/acl-tags-ga/
The systems you don't want to have associated with the User can instead be tagged.

Please do drop to the free tier. Personal use of the service is not intended to generate revenue, it is intended to generate awareness and goodwill: https://tailscale.com/blog/free-plan/

**Comment by a30t** [comment]
Thanks for the super fast response ! 
Overall the product solves some typical pain points in the VPN space and pretty cool implementation. Will continue to work on it given the suggestions your response. 

Thanks again.
