### ISSUE TITLE
Android Bug: all IP Address being showen as invalid

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#5243]
### What is the issue?

`invalid ip` being displayed instead of an IP address

![Screenshot_20220731-210206](https://user-images.githubusercontent.com/13573364/182058832-46ee99d8-32e1-4ea0-9f51-67b0f001513c.jpg)

### Steps to reproduce

Just update

### Are there any recent changes that introduced the issue?

The latest update

### OS

Android

### OS version

9,10,11,12

### Tailscale version

1.29.70-tc06758c83-g34ae6109d03

**Comment by DentonGentry** [comment]
Weird. I would have sworn it didn't do that when I first tried it, but now my 1.29.70 device also shows "Invalid IP" for all of the nodes. It should be straightforward to fix, the most recent import of the VPN code did change one of the datatypes which handles IP addresses.

**Comment by bradfitz** [comment]
Fix incoming.
