### ISSUE TITLE
ubuntu 20.04, command  "tailscale up" return nothing

### ISSUE THREAD

**Issue by dimanno** [tailscale/tailscale#5245]
### What is the issue?

Command `sudo tailscale up` doing nothing and return nothing

Expected behavior
Login URL should be displayed

### Steps to reproduce

1. Add Tailscale’s package signing key and repository:

```
`curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null`
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
Install Tailscale:
```
2. Install Tailscale:
```
sudo apt-get update
sudo apt-get install tailscale
```
3. Connect your machine to your Tailscale network and authenticate in your browser:

`sudo tailscale up`

4. Command doing nothing and return nothing

Screenshots

![screenshort1](https://user-images.githubusercontent.com/86560070/182094020-c758eef6-8cdd-48c1-a7d6-9bafe822a671.jpg)

Verifying that `tailscaled` service is up and running:

```
logtail started
Program starting: v1.28.0-t80313cdee-gd26dd4a68, Go 1.18.4-ts149f7d88f1: []string{"tailscaled"}
LogID: 9e6dc14285f255bb1b03356d46910a36fb9cd379acef1ec97fab7f2dec447fa1
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
TUN device tailscale0 is busy; another process probably still has it open (from old version of Tailscale that had a bug)
To fix, kill the process that has it open. Find with:

$ sudo lsof -n /dev/net/tun

... and then kill those PID(s)
wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): device or resource busy
flushing log.
logger closing down
createEngine: tstun.New("tailscale0"): device or resource busy
```
When killed the process that has it open - another appears.

### OS

Linux

### OS version

Ubuntu 20.0.4

### Tailscale version

1.28.0

### Bug report

BUG-9e6dc14285f255bb1b03356d46910a36fb9cd379acef1ec97fab7f2dec447fa1-20220801063602Z-19fb3f2ee8b9eb72

**Comment by DentonGentry** [comment]
(original bug said 1.18.4 but this is the Go version, the Tailscale version is 1.28.0)

`2022-08-02 15:06:58.868644826 +0300 +0300: Program starting: v1.28.0-t80313cdee-gd26dd4a68, Go 1.18.4-ts149f7d88f1: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "41641"}`

That system is up and in contact with the coordination server. When it is already up, `tailscale up` exits with a success code (you wanted it up, it is up).

If your goal is to make it authenticate again with a different user, you can use: `tailscale up --force-reauth`

**Comment by dimanno** [comment]
Thank you, now becomes more clear. But I still cannot open the page on the IP available to me. In the browser I get this `This site can’t be reached            10.0.64.58 took too long to respond.`  

this problem is only in Ubuntu, it works fine in other OS

**Comment by DentonGentry** [comment]
The macOS, Windows, and other Tailscale clients accept routes advertised by subnet routers by default.

The Linux client, as the first developed and also the one most likely to be used as a subnet router itself, does not. To accept routes one would use: `tailscale up --accept-routes=true`
