### ISSUE TITLE
linux: `192.168.0.100` mysteriously assigned to `tailscale0`, breaks everything

### ISSUE THREAD

**Issue by natrys** [tailscale/tailscale#5255]
### What is the issue?

`tailscale ping` works but not actual ping or netcat or anything (they indefinitely hang, and fwiw peers have no problem talking to this machine).

I think this is a routing problem due to the fact that tailscale0 interface has default IP address of my actual network interface. So right when I start tailscaled daemon, it looks like:

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 18:c0:4d:c3:b5:d4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.100/24 brd 192.168.0.255 scope global noprefixroute enp4s0
       valid_lft forever preferred_lft forever
    inet6 fe80::5233:40f5:e528:b2d7/64 scope link 
       valid_lft forever preferred_lft forever
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 192.168.0.100/24 brd 192.168.0.255 scope global noprefixroute tailscale0
       valid_lft forever preferred_lft forever
```

And after I connect with `sudo tailscale up --reset --authkey xxxx`, the tailscale0 interface looks like:

```
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 192.168.0.100/24 brd 192.168.0.255 scope global noprefixroute tailscale0
       valid_lft forever preferred_lft forever
    inet 100.119.199.43/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:4843:cd96:6277:c72b/128 scope global 
       valid_lft forever preferred_lft forever
```

Question: should the tailscale0 interface have the `192.168.0.100/24` IP? The machines that don't have this problem, also don't have this (they have only have tailscale IP in the tailscale0 interface).

While `ip route show table 52` shows an entry like: `100.101.102.103 dev tailscale0`, `ip route get` shows:

```
$ ip route get 100.101.102.103
100.101.102.103 dev tailscale0 table 52 src 192.168.0.100 uid 1000 
    cache 
```

So it's trying to talk to tailscale peer using that 192.168.0.100 instead of tailscale IP (100.119.199.43). In fact if I do:

```
$ sudo ip addr del 192.168.0.100/32 dev tailscale0
```

then the problem goes away and I can actually ping/talk to the peers.

### OS

Linux

### OS version

Void Linux

### Tailscale version

1.28.0 go version: go1.18.3

### Bug report

BUG-a62453d633a1a5ac2b6b3231ffe2bd8ed74ccdf1974391246738e5d3f2bc9d70-20220802070901Z-e82a0f74345bb57f

**Comment by DentonGentry** [comment]
Tailscale didn't add `192.168.0.100` to tailscale0, something else in the system must have. As you say, this led to the other problems described.

**Comment by natrys** [comment]
@DentonGentry , you were right, I didn't think of that. Looks like it's a combination of things I missed:

- System dhcpcd is running for all interfaces.
- In my `dhcpcd.conf` file I had "request 192.168.0.100" for my router for port forwarding reasons.

The result is indeed dhcpcd adding that to tailscale:

```
dhcpcd-9.4.1 starting
dev: loaded udev
DUID 00:04:03:c0:02:18:04:4d:05:c3:b5:06:d4:07:00:08:00:09
enp4s0: IAID 4d:c3:b5:d4
enp4s0: soliciting a DHCP lease (requesting 192.168.0.100)
enp4s0: soliciting an IPv6 router
enp4s0: offered 192.168.0.100 from 192.168.0.1
enp4s0: leased 192.168.0.100 for infinity
enp4s0: adding route to 192.168.0.0/24
enp4s0: adding default route via 192.168.0.1
enp4s0: no IPv6 Routers available
tailscale0: waiting for carrier
tailscale0: carrier acquired
tailscale0: IAID 00:00:00:03
tailscale0: using static address 192.168.0.100/24
tailscale0: adding route to 192.168.0.0/24
tailscale0: soliciting an IPv6 router
```

I am going to use `--denyinterfaces "tailscale*"` with dhcpcd to prevent this from happening. Apologies for the noise. I do wonder if tailscale could add some more checks on its end.
