### ISSUE TITLE
FR: MacOS - Surface --host-routes option in GUI

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5256]
### What are you trying to do?

Would like to be able to toggle --host-routes from the debug menu in the GUI on MacOS

### What is the impact of not solving this?

The host routes default behaviour is different on MacOS than other platforms, which solves a certain set of problems, but can cause difficulty if the node is directly on a CGNAT network. It can be toggled by command-line, but I think this should be surfaced to the GUI.

**Comment by DentonGentry** [comment]
I suspect this refers to the use of a `100.64.0.0/10` route in macOS if we're sure that no other interface is using CGNAT, which is not the same as `--host-routes` in the CLI. The macOS behavior for `--host-routes` is the same as other platforms.

There is a setting in the ACL JSON which can control this:
`"OneCGNATRoute": "mac-always"`

**Comment by DentonGentry** [comment]
I'm going to close this, in that `"OneCGNATRoute": "mac-always"` is the best option rather than making each Mac user adjust the setting.
