### ISSUE TITLE
Tailscale doesn't detect woken-up computer

### ISSUE THREAD

**Issue by Shadlock0133** [tailscale/tailscale#5257]
### What is the issue?

After waking up computer B, computer A doesn't see it as online, even after few hours. This is especially annoying with taildrop, since it just greys out the target, without an option to "refresh".

### Steps to reproduce

1. Put computer B to sleep.
2. Start computer A.
3. Wake up computer B.
4. Computer A doesn't see computer B.

### OS

Windows

### OS version

Windows 8.1, 10

### Tailscale version

1.28.0

**Comment by DentonGentry** [comment]
We'll need a bugreport from the system which is unable to see the woken up computer, taken during a time when it thinks the woken-up computer is offline but you're sure the remote computer has been woken up.

We'll also need the Tailscale IP address of the woken up computer, to be able to see what it is reporting during the same timeframe.

**Comment by Shadlock0133** [comment]
BUG-ce851d4278dd581880e6213ebb39325af9998a72c917ab0ba380d4e36f22d3d2-20220802142835Z-5a0a319d150ef071

100.73.132.17

**Comment by DentonGentry** [comment]
I don't immediately see what is wrong. After waking, it is reporting in with the coordination server:
```
2022-08-02 17:04:20.8301634 +0200 +0200: control: mapRoutine: netmap received: state:synchronized
2022-08-02 17:04:20.8301634 +0200 +0200: control: sendStatus: mapRoutine-got-netmap: state:synchronized
```

**Comment by DentonGentry** [comment]
At this point I don't expect to figure out what was happening in 8/2022. If the problem happens again please reopen or file a new bug. We'll need a bugreport from the system which cannot see the newly woken device.
