### ISSUE TITLE
FR: JSON Linting for the ACL editor

### ISSUE THREAD

**Issue by kgleason** [tailscale/tailscale#5261]
### What are you trying to do?

Editing ACLs in the web editor doesn't show when there is a syntax error. And the errors that are displayed when one tries to save is not entirely telling. It doesn't provide a line number, or anyway to figure out exactly where to start debugging.

### How should we solve this?

Add some sort of linter to the editor to verify the syntax on the fly, and provide clues towards resolving any issues.

### What is the impact of not solving this?

Debugging ACLs in the web editor is an arduous process, resulting in lots of "Saves" without knowing if the problem is resolved. It could potentially result in someone breaking their ACLs inadvertently.

**Comment by DentonGentry** [comment]
```
{
	"RandomizeClientPort": true,
	//"DisableIPv4":         true,
    this is an invalid literal
```

Save button says: `Error: line 4, column 5: invalid literal: this`

--------

```
{
	"RandomizeClientPort": true,
	//"DisableIPv4":         true,
	"Unknownfield": {},
```

Save button says: `Error: json: unknown field "Unknownfield"`

--------

>Editing ACLs in the web editor doesn't show when there is a syntax error. And the errors that are displayed when one tries to save is not entirely telling. It doesn't provide a line number, or anyway to figure out exactly where to start debugging.

Could you provide some examples of the types of errors where this is the case?

**Comment by DentonGentry** [comment]
timed out. The ACL editor shows specific errors for each case quoted, so far as I can see.
