### ISSUE TITLE
Tailscale ssh lacks $PATH for non-interactive sessions (VSCode, Xpra, etc)

### ISSUE THREAD

**Issue by dapirian** [tailscale/tailscale#5285]
### What is the issue?

When I connect to a remote machine using VSCode Remote SSH, my $PATH gets stomped with a VSCode path which is supposed to be appended, not overwrite my entire path.

This may be a VSCode bug ([here](https://github.com/microsoft/vscode-remote-release/issues/6975)) but I'm posting here because there's definitely some interaction with tailscale. This _only_ occurs via tailscale ssh.

Works:
- SSH in terminal not via tailscale
- SSH in terminal via tailscale (tailscale up --ssh)
- SSH via VSCode Remote SSH not via tailscale

Stomps $PATH:
- SSH via VSCode Remote SSH via tailscale

### Steps to reproduce

- `tailscale up --ssh`
- In VSCode, connect to that remote host (disconnect and reconnect several times)

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.28.0

**Comment by AlekSi** [comment]
Interesting. VSCode Remote SSH does not work for me at all, see #5295.

**Comment by dapirian** [comment]
Several people on my team are all independently hitting this

**Comment by zackify** [comment]
seeing this as well, so weird

**Comment by bradfitz** [comment]
As @mattbdc pointed out in dup #6667, this is purely about non-interactive sessions. I can reproduce:

```
bradfitz@book1pro ~ % ssh tsdev env | grep ^PATH
bradfitz@book1pro ~ % ssh 10.0.0.52 env | grep ^PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
```

cc @maisem

**Comment by ShadowJonathan** [comment]
@bradfitz that solution seems to hardcode some seemingly-default PATH variables, but this might not work when people edit /etc/profile and the likes.

See [this blog post](https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html) for more information on that stuff.

I'm just noting this here as this solution might result in a future bug, one that's even more subtle than this.

**Comment by bradfitz** [comment]
@ShadowJonathan, `/etc/profile` empirically isn't used by OpenSSH when running a command without a session.

I modified my `/etc/profile` with `/bradtest/` entries at the end like:

```
if [ "$(id -u)" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bradtest/foo"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/bradtest/bar"
fi
export PATH
```

But then:

```
bradfitz@book1pro ~ % ssh 10.0.0.52 env | grep ^PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
bradfitz@book1pro ~ % ssh root@10.0.0.52 env | grep ^PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

.... it's not used.

/cc @andrew-d

**Comment by andrew-d** [comment]
For future reference, here's some links to what OpenSSH does:
* Uses hardcoded paths set by flags passed to `./configure`: https://github.com/openssh/openssh-portable/blob/5f93c4836527d9fda05de8944a1c7b4a205080c7/session.c#L1030-L1052
  * Default paths are hard-coded, if none are passed to `./configure`: https://github.com/openssh/openssh-portable/blob/5f93c4836527d9fda05de8944a1c7b4a205080c7/defines.h#L438-L451
* Fetch environment variables from PAM: https://github.com/openssh/openssh-portable/blob/5f93c4836527d9fda05de8944a1c7b4a205080c7/session.c#L1128-L1151
  * More docs: https://man7.org/linux/man-pages/man5/pam_env.conf.5.html
* Apply variables set by the `SetEnv` option in `sshd_config`: https://github.com/openssh/openssh-portable/blob/5f93c4836527d9fda05de8944a1c7b4a205080c7/session.c#L1128-L1151

**Comment by bradfitz** [comment]
But I'm super curious about all this, so let me know what we're missing! (this is all fascinatingly horrible)

**Comment by ShadowJonathan** [comment]
Intuitively to me it seems that hardcoding these path values wouldn't respect the system's source of truth on some of those same path values, and so i'm just poking at it to maybeperhaps find another (dynamic/changable) local source of truth to add onto it, like andrew posted.

**Comment by bradfitz** [comment]
But do you see how many other distros build OpenSSH to hard-code values?

Keep in mind this is only for the very early environment before your shell initializes it further. So if your `bashrc` file(s) depended on $PATH including /usr/bin or something, it used to fail but now it works.

**Comment by akirak** [comment]
Hello, I am a Nix user, and `nix store ping` doesn't work over Tailscale SSH if the destination host is non-NixOS (with a released version of Tailscale). This means `nix copy-closure` to non-NixOS doesn't work. It would be nice if PATH were configurable.

How to reproduce:

> nix store ping --store ssh://$builder && echo ok
Store URL: ssh://user@xxx.xxxxxxx.ts.net
zsh:1: command not found: nix-store
exit status 127

**Comment by bradfitz** [comment]
The fixes haven't been released yet.

**Comment by akirak** [comment]
@bradfitz Yes, I know. It's a feature request. Thank you.
