### ISSUE TITLE
unaligned atomic load on arm

### ISSUE THREAD

**Issue by reusee** [tailscale/tailscale#529]
**Describe the bug**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ce8]

goroutine 59 [running]:
runtime/internal/atomic.goLoad64(0x27da00c, 0x1, 0x1)
	/Users/reus/gotip/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
tailscale.com/wgengine/tstun.(*TUN).IdleDuration(0x27da000, 0x1, 0x2517201)
	/Users/reus/github/tailscale/wgengine/tstun/tun.go:250 +0x24
tailscale.com/wgengine/magicsock.(*Conn).shouldDoPeriodicReSTUN(0x253a280, 0x27d2f00)
	/Users/reus/github/tailscale/wgengine/magicsock/magicsock.go:1905 +0xe0
tailscale.com/wgengine/magicsock.(*Conn).periodicReSTUN(0x253a280)
	/Users/reus/github/tailscale/wgengine/magicsock/magicsock.go:1932 +0x290
created by tailscale.com/wgengine/magicsock.(*Conn).Start
	/Users/reus/github/tailscale/wgengine/magicsock/magicsock.go:310 +0x84
```

**To Reproduce**
run 0.100 or master tailscaled on 32-bit arm 

**Expected behavior**
no crash

**Version information:**
os: 32-bit arm linux router
tailscale version: both 0.100 or master crash

**Additional context**
I think the wgengine/tstun.TUN.lastActivityAtomic field is not 64-bit aligned, so a call to atomic.LoadInt64 on that field caused the crash. It's a known bug of the atomic package: https://pkg.go.dev/sync/atomic?tab=doc#pkg-note-BUG

**Comment by bradfitz** [comment]
@reusee, there will be updated unstable packages momentarily at https://pkgs.tailscale.com/unstable/ ... look for version 0.100.0-8. Thanks!

**Comment by reusee** [comment]
@bradfitz I've built the binary from master branch and it's running without crash now.
