### ISSUE TITLE
Make tailscale ignore certain IP/Subnets from 100.x.x.x

### ISSUE THREAD

**Issue by Oujiii** [tailscale/tailscale#530]
**Is your feature request related to a problem? Please describe.**

Currently Tailscale works in my corporate network, but I just found out today that one of the most used websites I use, is running locally on a 100.x.x.x IP address and after installing Tailscale, that DNS name does not resolve anymore (and I can't access via the direct IP either)

**Describe the solution you'd like**

#466 could be a solution (I'm running this on a Linux client), although mostly as placeholder.

I'd like to have a way to make Tailscale ignore that specific IP so it can be routed by the corporate network 

**Describe alternatives you've considered**

Tried editing /etc/hosts (not sure why I thought that would work).
Also uninstalled, but that is not really an alternative, but that is the way stuff is running right now.

**Additional context**

I'm not sure if this out of the scope of the project. ZeroTier solves this by allowing me to choose a different subnet to assign IPs from, but at the same time, they do not work at my corporate network.

Thank you.

**Comment by Oujiii** [comment]
Just found #320 and I guess there is not option other than removing the BLOCK rules? Does it affect anything?

**Comment by DentonGentry** [comment]
Will track this on https://github.com/tailscale/tailscale/issues/1381
