### ISSUE TITLE
Cannot tailscale ssh as non-local user

### ISSUE THREAD

**Issue by ephemient** [tailscale/tailscale#5332]
### What is the issue?

I have a system with no local users; instead, [sssd](https://sssd.io/) is used (which is configured to forward to and cache LDAP).

```
# /etc/nsswitch.conf
passwd: files sss
# etc.
```

`tailscale ssh` is unable to log into that machine, reporting `$USER@$HOST: Permission denied (tailscale).` on the client and `failed to lookup $USER: user: unknown user $USER` in `journalctl -u tailscaled` on the server.

### Steps to reproduce

1. `tailscale up --ssh` on a machine with remote users (probably any of {ldap, nisplus, sssd} would work)
2. Try to `tailscale ssh` to that machine.

### OS

Linux

### OS version

CentOS 7.9

### Tailscale version

1.28.0

### Bug report

BUG-d72fc3f853c38b8fd206553c2c859cec53ee00585b1b36a6808ec7a155cc871d-20220810041344Z-3fdf2aa6519f73f5

**Comment by DentonGentry** [comment]
Around the time of the BUG line there are a series of log messages of the form:
```
2022-08-09 23:58:50.127418483 -0400 -0400: conn-20220810T035846-46b6e88e3e: handling conn: 100.117.x.y:49488->dlin@100.111.x.y:22
2022-08-09 23:58:50.127571965 -0400 -0400: conn-20220810T035846-46b6e88e3e: failed to lookup REDACTED: user: unknown user REDACTED
```

**Comment by bradfitz** [comment]
Dup of #4945?

**Comment by ephemient** [comment]
Oh yes, it does look like #4945.
