### ISSUE TITLE
Tailscale backend error: Version mismatch! frontend="" backend="0.95-0"

### ISSUE THREAD

**Issue by faruqisan** [tailscale/tailscale#535]
**Describe the bug**
Error dialog occurred after login

**To Reproduce**
1. Login to Windows user

**Expected behavior**
There is no error dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/9929145/86934591-161c4d80-c166-11ea-8ec4-689978426a5a.png)

**Version information:**
 - Device: PC
 - OS: Windows
 - OS version: Windows 10
 - Tailscale version: 0.95-0

**Additional context**

I have two user in my PC

**Comment by bradfitz** [comment]
0.95 is pretty old at this point. Could you update to 0.99.0 or 0.100.0-9 and try again?

From either:
https://pkgs.tailscale.com/stable/
https://pkgs.tailscale.com/unstable/

**Comment by bradfitz** [comment]
Alternatively, 0.100.0-17 is now available from https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-0.100.0-17.exe

**Comment by faruqisan** [comment]
Thanks, @bradfitz , I will try to update my Tailscale version to 0.99 and will let you know if the issue is resolved.

**Comment by faruqisan** [comment]
Issue resolved after upgrading to 0.99 👍
