### ISSUE TITLE
FR: When using ip or MagicDNS, please support self-signed certificate for https in tailnet

### ISSUE THREAD

**Issue by dacapoday** [tailscale/tailscale#5350]
### What are you trying to do?

Want the server in tailnet will have https support automatically.
Or tailscale can auto install self-signed CA to all node in the tailnet.

**Comment by maisem** [comment]
Tailscale already provides TLS certs. https://tailscale.com/blog/tls-certs/

**Comment by DentonGentry** [comment]
I think this feature request is addressed by https://tailscale.com/blog/tls-certs/

**Comment by DentonGentry** [comment]
Installing a self-signed root certificate would resemble the behavior of a rootkit. Though justifiable in some circumstances, it would require careful thought before incorporating such a feature into a security product.

To set expectations: I do not expect to implement this feature request as stated, I expect instead to build upon the LetsEncrypt support in https://tailscale.com/blog/tls-certs/

You are welcome to install a root CA certificate on your own machines.
