### ISSUE TITLE
FR: [Tailscaled-on-macOS] check for existence before overwriting /usr/local/bin/tailscaled

### ISSUE THREAD

**Issue by frankli0324** [tailscale/tailscale#5353]
### What are you trying to do?

https://github.com/tailscale/tailscale/blob/1f7479466ef21396ee569d89c23c30f25cc9c84f/cmd/tailscaled/install_darwin.go#L98

tailscale writes itself to `/usr/local/bin/tailscaled` when doing `tailscaled install-system-daemon`.

However homebrew links the binary to `/usr/local/bin/tailscaled` when installing.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/20221896/184308923-b95e044c-1088-4529-884a-9599351a39fe.png">

### How should we solve this?

check for existence before overwriting /usr/local/bin/tailscale

### What is the impact of not solving this?

<img width="651" alt="image" src="https://user-images.githubusercontent.com/20221896/184309189-074e5981-eb3a-4b5e-9715-f9cd2e07ed67.png">

**Comment by frankli0324** [comment]
another option is:

```
if (realpath(targetbin) == realpath(selfbin)) dont_overwrite();
elif(realpath(selfbin) != targetbin) ln -s targetbin selfbin;
else warn_user();
```

**Comment by DentonGentry** [comment]
Do I understand correctly that the problem is:
1. used `brew install tailscale`
1. used `tailscaled install-system-daemon`  (of the homebrew tailscaled, not some other tailscaled somewhere)
1. tailscaled stopped working altogether

Is that correct?

**Comment by frankli0324** [comment]
yes

**Comment by frankli0324** [comment]
for anyone that ends up being here, a temporary workaround would be

`sudo /usr/local/opt/tailscale/bin/tailscaled install-system-daemon`

and you would have to `brew link --overwrite tailscale` on every `brew upgrade`

**Comment by frankli0324** [comment]
is this issue among the tailscale milestones?

**Comment by DentonGentry** [comment]
Work on this hasn't been scheduled yet. We understand that it is important, but it isn't at the top of the project list yet.
