### ISSUE TITLE
Wrong error message when not connected to the Internet

### ISSUE THREAD

**Issue by conioh** [tailscale/tailscale#5369]
### What is the issue?

When not connected to the Internet the Tailscale GUI control programs says "Please restart the Tailscale Windows Service" when this is not the issue.

### Steps to reproduce

Scenario 1:
1. Set your computer in advance to not connect to not connect to Wi-Fi networks automatically / disable network adapters / disconnect from Ethernet / etc.
2. Turn on computer.
3. Log on.

Scenario 2:
1. Disconnect from networks.
2. Close Tailscale GUI control programs.
3. Launch Tailscale GUI control program.

The first scenario is what actually happened to me, but the second one is obviously a more useful reproduction.

### OS

Windows

### OS version

Windows 11 Enterprise x64 build 22000.856, Windows 10 Enterprise x64 19044.1889, Windows 11 Pro ARM64 Insider build 25179, but that's obviously not version-specific.

### Tailscale version

1.26.2 (t9e47908f1-g27ee7cf2f), 1.28.0 (t80313cdee-gd26dd4a68)

**Comment by DentonGentry** [comment]
We'll handle this on https://github.com/tailscale/tailscale/issues/7305

Dup of https://github.com/tailscale/tailscale/issues/7305
