### ISSUE TITLE
Systemd cannot launch tailscaled on read-only filesystem, even with a r/w --statedir

### ISSUE THREAD

**Issue by jodavaho** [tailscale/tailscale#5399]
### What is the issue?

I installed tailscale clean on a raspberry pi.

My root filesystem is read only, except for a `storage` partition
```
proc                  /proc     proc            defaults             0    0
PARTUUID=83c4223d-01  /boot     vfat            defaults,ro          0    2
PARTUUID=83c4223d-02  /         ext4            defaults,noatime,ro  0    1
PARTUUID=83c4223d-03  /storage  ext4            defaults,noatime,rw  0    2
tmpfs                 /tmp      tmpfs           nosuid,nodev         0    0
tmpfs                 /var/tmp  tmpfs           nosuid,nodev         0    0
tmpfs                 /var/log  tmpfs           nosuid,nodev         0    0
```

Launching `systemctl start tailscaled` yields error `238/STATE_DIRECTORY`

I can launch it as follows: `tailscaled --statedir=/storage/tailscale` and all is well. I can open another terminal, use `tailscale up`, connect it and so on. I even ran `tailscale bugreport` this way. 

So, I edited the `/lib/systemd/system/tailscaled.service` as follows, changing this line:

```
ExecStart=/usr/sbin/tailscaled --statedir=/storage/tailscale --socket=/run/tailscale/tailscaled.sock --port $PORT $FLAGS
```

But `systemctl daemon-reload` and then `systemctl start tailscaled` yield:

```
 tailscaled.service - Tailscale node agent
   Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-08-18 22:20:01 BST; 1min 16s ago
     Docs: https://tailscale.com/kb/
  Process: 1493 ExecStart=/usr/sbin/tailscaled --statedir=/storage/tailscale --socket=/run/tailscale/tailscaled.sock --port $PORT $FLAGS (code=exited, status=238/STATE_DIRECTORY)
```

I expected it to start normally. Somewhere, systemd is borking the config, or I have made a config error that is not obvious. 

Contents of `/etc/default/tailscaled` are:

```
# Set the port to listen on for incoming VPN packets.
# Remote nodes will automatically be informed about the new port number,
# but you might want to configure this in order to set external firewall
# settings.
PORT="41641"

# Extra flags you might want to pass to tailscaled.
FLAGS=""
```

(and oh by the way, setting flags here didn't help either).

I can remount the whole root dir as r/w, and suddenly it works. But that's not an option for general use.

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

Unclear

### OS

Linux

### OS version

No LSB modules are available. Distributor ID:	Raspbian Description:	Raspbian GNU/Linux 10 (buster) Release:	10 Codename:	buster

### Tailscale version

1.28.0   tailscale commit: 80313cdee14dee22452ea2b278e7bbcfe4af1a9c   other commit: d26dd4a68f4c18686b003051acd7e44d8788a4b7   go version: go1.18.4-ts149f7d88f1

### Bug report

BUG-3e916928e1c370753e0d6e8d09c87ab4a8569c7f4a27db941c77ec3e587474e6-20220818212651Z-e88fa46bde0c84eb

**Comment by DentonGentry** [comment]
I think this happens because systemd tries to create a `StateDirectory=tailscale` directory. It looks like you could set up an override.cnf file using `systemctl edit tailscaled` to tell it not to do that. Clearly, this would need to be done in the base image while it is writable.

Populate it with:
```
[Service]
StateDirectory=
```

**Comment by DentonGentry** [comment]
I think the StateDirectory would resolve this.
