### ISSUE TITLE
FR: Add ability to (automatically) overwrite a previously defined hostname of an ephemeral node

### ISSUE THREAD

**Issue by ratorx** [tailscale/tailscale#5400]
### What are you trying to do?

I am using Tailscale with Magic DNS and fly.io. When I do a deploy, it creates a new Tailscale node and stops the old one. However, since this happens within a period of ~1 min, the old node has not expired before the new one appears. This means that the new node receives a suffixed hostname (e.g. `foo-1`) rather than `foo`, even after the old node has disconnected and will never reconnect again.

This is annoying since I want `foo` to point to the newest (and only accessible) node, rather than need to remember to check for the suffix or manually clean up after a deploy.

### How should we solve this?

I think the way to do this would be to either:

1) Expose last-registration-wins semantics for the hostname in some way. This seems tricky and a niche feature, but would directly solve my issue. However, it's not without precedent, since that's how Dynamic DNS typically works.

2) Add the ability to manually expire an ephemeral node (rather than waiting for an automatic timeout). What I'm looking for is an explicit CLI command so that I can run it whilst the previous node is being stopped. This would be a nice way to disambiguate between "node is unreachable because of intermittent network issue" and "node is unreachable and will never be reachable again (without a restart)".

### What is the impact of not solving this?

Ephemeral nodes + stable Magic DNS requires manual toil on every node restart.

I've tried running `tailscale logout` before the old node shuts down, but that doesn't seem to fix my issue.

**Comment by DentonGentry** [comment]
There are two ways that this is often handled:
- the fly.toml can use a persistent volume for /var/lib/tailscale, which will store the node key and result in each new deployment coming back up with the same IP address (*).
- `tailscale logout` as the last step on the prior deployment before it exits will have it give up its node key and release the hostname. The new version would be able to take over the hostname when it comes up.

(*) To set up a persistent volume for fly.io use: `flyctl volumes create data --region sjc --size 1` (where size is in Gigabytes). Then in fly.toml:
```
[mounts]
  destination = "/root"
  source = "data"
```

**Comment by ratorx** [comment]
Thanks! The volume idea is nice.

I tried `tailscale logout` on exit, but that didn't seem to work. But if that's expected to work, it's possibly my configuration that's broken.

**Comment by DentonGentry** [comment]
`tailscale logout` does work in other contexts, I suspect it isn't actually being run on the old deployment before it exits, for some reason.

If you go with the persistent volume, you'll also want to make sure only one instance runs at a time. If fly tries to scale up automatically based on some spike in load, they'd all try to use the same node key. You can do this using `flyctl scale count 1`

**Comment by DentonGentry** [comment]
I am informed that deletion of the node on `logout` is currently feature flagged and will be available to all users "soon" but not yet. This would explain why it didn't work, it depends on which tailnet.

**Comment by maisem** [comment]
And it's out! https://tailscale.com/blog/ephemeral-logout/

**Comment by Haarolean** [comment]
For the ones wondering how to achieve this:
My tailscale exit node container runs a startup bash script, I've adjusted it to trap SIGINT/SIGTERM (based on what you have in your fly.toml) signal and run tailscale logout there. The startup script should look like this:
```sh
#!/usr/bin/env sh

logout() {
    echo "Tailscale: Logging out"
    /app/tailscale logout
}

trap 'logout' SIGINT
trap 'logout' SIGTERM

#tailscaled and tailscale up here

echo "Tailscale started. "

sleep infinity &
wait $! # this is gonna trigger the trap
```
