### ISSUE TITLE
Can't connect to Tailscale with Go on MacOS 12.5.1

### ISSUE THREAD

**Issue by jasmineAnthropic** [tailscale/tailscale#5403]
### What is the issue?

(py39) my-MacBook-Pro ~ % ~/go/bin/tailscale up --accept-routes --accept-dns
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 1886). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp [::1]:62110: connect: connection refused

### Steps to reproduce

(py39) my-MacBook-Pro ~ % ~/go/bin/tailscale up --accept-routes --accept-dns
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 1886). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp [::1]:62110: connect: connection refused

tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 1886). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp [::1]:62110: connect: connection refused

### OS

macOS

### OS version

12.5.1

### Tailscale version

1.28.0,  go version: go1.18.4

**Comment by jasmineAnthropic** [comment]
I have no firewalls running or anything like that

**Comment by DentonGentry** [comment]
If you ever ran the App Store version, can you try removing `/Library/Tailscale` ?

**Comment by jasmineAnthropic** [comment]
then i got this 
Warning: client version "1.28.0-dev-t" != tailscaled server version "1.29.0-dev-t"
2022/08/20 13:34:12 GotNotify: Version mismatch! frontend="1.28.0-dev-t" backend="1.29.0-dev-t"

**Comment by DentonGentry** [comment]
The version of the `tailscale` command doesn't match `tailscaled`. This likely means that there are several versions of the binaries on disk.

`which tailscale` and `which tailscaled` will show which binaries would run. I suspect they will be in two different directories from two different compilations of Tailscale.

**Comment by jasmineAnthropic** [comment]
Hi, I followed the install guide exactly, If something is wrong here then the install guide needs to be updated.
Which tailscale
tailscale not found

which tailscaled
/usr/local/bin/tailscaled

It is my understanding that this is correct. It said in the install guide tailscaled would be moved to this location. How do I fix this?

**Comment by jasmineAnthropic** [comment]
tailscaled -version
1.29.0-dev
  go version: go1.19

**Comment by jasmineAnthropic** [comment]
tailscale --version
1.28.0-dev
  go version: go1.19

**Comment by DentonGentry** [comment]
I suspect that `/Users//go/bin/tailscale` was built some time ago, as it is still 1.28.0 while tailscaled is 1.29.0.

To rebuild both `tailscale` and `tailscaled` afresh, you'd repeat these two steps:
`go install tailscale.com/cmd/tailscale{,d}@main`
`sudo $HOME/go/bin/tailscaled install-system-daemon`

**Comment by jasmineAnthropic** [comment]
Hi Denton,
I ran those steps today and the result is version conflicting. I don't believe this is a user side error. Something in the software is wrong and needs to be fixed here.

**Comment by jasmineAnthropic** [comment]
Well I reran both of those commands a second time and everything is fixed. Thanks for your help Denton

**Comment by DentonGentry** [comment]
Great, glad it is working.

**Comment by jasmineAnthropic** [comment]
Hi Denton,
I ran those steps today and the result is version conflicting. I don't
believe this is a user side error. Something in the software is wrong and
needs to be fixed here.
