### ISSUE TITLE
FR: Better support for cloned deployments

### ISSUE THREAD

**Issue by augustz** [tailscale/tailscale#5405]
### What are you trying to do?

In many golden image or other cloned deployments, its a HUGE help if the software does something reasonable (or can be passed a flag to do something reasonable). For example, can we set the cloned image to detect a mac address change. Or a vmware generation. 

Or just a quick way to script a refresh of the machine key. Right now it seems the only way to avoid duplicate machine ip's is to uninstall and reinstall tailscale. This feels a bit weird. tailscale reset maybe could be added? 

### What is the impact of not solving this?

It's frustrating to deploy tailscale on a larger scale, or use tailscale as part of a bootstrap process. 

My situation I'd love to have a new machine waiting for approval in my tailscale interface. Then I could approve, and jump right into it. Now I have to fallback to a sonicwall firewall to get into the machine to configure by uninstalling and reinstalling tailscale.

**Comment by DentonGentry** [comment]
This usually means that tailscale was installed and actually brought up on the initial system, before creating the golden image. It stored its node key in `/var/lib/tailscale/tailscaled.state`, which resulted in all of the cloned fighting over one Tailscale IP address.

I believe that removing `/var/lib/tailscale/` in the golden image will do what you want: the tailscale binaries will be installed in the cloned nodes, but each node will need to authenticate itself and get a unique IP address and node key.

**Comment by DentonGentry** [comment]
I think removal of `/var/lib/tailscale/tailscaled.state` is the solution we'd suggest, it avoids propagating the machine and node keys.

Relatively soon the admin panel will add a Duplicate node key badge in these cases, to help diagnose it.
