### ISSUE TITLE
How to disable active login information in tailscale client logs

### ISSUE THREAD

**Issue by ilanni2460** [tailscale/tailscale#5407]
### What is the issue?

How to disable active login login information in tailscale client logs

I am using tailscale running in kubernetes mode and found that the logged in user name is output in the log

**Comment by DentonGentry** [comment]
The telemetry is uploaded to a backend service for use by Tailscale support. It includes enough details to resolve support queries, including endpoint addresses and the active user.

There isn't a function to redact portions of the telemetry, but one could block uploads to https://log.tailscale.io/ if desired. Please don't file support questions if you block uploads.

**Comment by mayakacz** [comment]
See these instructions for blocking logging: https://tailscale.com/kb/1011/log-mesh-traffic/#opting-out-of-client-logging

**Comment by ilanni2460** [comment]
@mayakacz @DentonGentry 
Thank you very much for your answer, but after testing, it is found that the` --no-logs-no-support` parameter is invalid, and the user's information can still be displayed in the log

**Comment by mayakacz** [comment]
> the user's information can still be displayed in the log

What logs? That _should_ disable any client logging.

Configuration audit logs ([admin console](https://login.tailscale.com/admin/logs), [docs](https://tailscale.com/kb/1203/audit-logging/)) are server-side, and cannot be disabled.
