### ISSUE TITLE
Internal server error with test

### ISSUE THREAD

**Issue by joneskoo** [tailscale/tailscale#5408]
### What is the issue?

I noticed that when I add this test, saving the ACL fails.

As I understand https://tailscale.com/kb/1018/acls/#tests ; host (subnet CIDR) should be valid for src, and deny should be host:port and user is valid as host in the deny.

It would be useful to get request id for internal server errors so it'd be easier to reference them when reporting bugs. Consider adding request id header that you log and showing it with the error message to user?

### Steps to reproduce

When I add this test to my ACL that works when this is commented out, I get internal server error.

```json
{
	// Tests check functionality of ACL rules
	"tests": [
		// internal server error
		{ "src": "subnet-m7",
		  "allow": ["unifi-controller-01:443"],
		  "deny": ["joneskoo@github:22" ]
		}
	]
}
```

<img width="589" alt="image" src="https://user-images.githubusercontent.com/305104/185681361-20a186b2-f91a-442f-80ed-16f27a888a39.png">

### Are there any recent changes that introduced the issue?

No this has been there for many months or always. I had it commented out and was hoping it'd get fixed on its own but it wasn't yet so I'm creating this ticket.

### OS

macOS

**Comment by mihaip** [comment]
Though a close reading might suggest that subnets are supported for tests, the intent is to only support actual (single) hosts that are mapped. I do agree that the error message is not great (it's a Go panic on our side), will look into fixing that.

**Comment by mihaip** [comment]
I've made the fix, but it has not been deployed yet. Will close once it's live.

**Comment by mihaip** [comment]
This is now deployed, the UI should now correctly flag this as an invalid user.

**Comment by joneskoo** [comment]
To make this completely clear, can you add a note to the host section in doc that only single IP not CIDR is allowed in tests?

Thanks. I confirm the error is now better (although non-specific why not valid, at least clear where the problem is):


Error: test(s) failed
test(s) failed for user: subnet-m7
user is invalid

**Comment by mihaip** [comment]
@joneskoo fair enough, [the docs](https://tailscale.com/kb/1018/acls/#tests) now say "...or a host that maps to an IP address".
