### ISSUE TITLE
Tailscale favicon is almost invisible on light-themed browser tabs

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#543]
Reported by a customer, but it's also true in my Chrome with default theming:
![tailscale-favicon](https://user-images.githubusercontent.com/1918/87212179-15082f00-c2d2-11ea-8989-e2d277e9af5e.png)

It looks even more invisible on Safari, where the tab background is closer to white.

Maybe we should include our black frame in the favicon, rather than have it mostly transparent? cc @rosszurowski

**Comment by ashishgandhi** [comment]
That was me. 👋

Here are the Safari ones I had emailed.

![image](https://user-images.githubusercontent.com/970540/87214742-2c501800-c2e4-11ea-898c-74d75d482ba4.png)

![image](https://user-images.githubusercontent.com/970540/87214745-307c3580-c2e4-11ea-9a62-32813334b0e9.png)

**Comment by rosszurowski** [comment]
Thanks for reporting @ashishgandhi. I just pushed a fix for this, so you should see proper favicons for both light and dark modes now.
