### ISSUE TITLE
FR: add CLI commands to manage DNS

### ISSUE THREAD

**Issue by KFearsoff** [tailscale/tailscale#5430]
### What are you trying to do?

I'm currently in the process of setting up a Tailscale network with 4 devices: 3 Linux machines and 1 Android machine. I would like all of my Linux machines to host CoreDNS servers, and I'd like to advertise them on my Tailscale network. The process is very similar to a very well-documented Pi-hole guide:
https://tailscale.com/kb/1114/pi-hole/
That said, I'd like my CoreDNS nodes to add themselves as a DNS option automatically, instead of writing IP addresses in Web UI by hand.

### How should we solve this?

It would be nice to have CLI commands to manage DNS servers, since then I'd be able to automate the process of updating the DNS server IPs. I'd just need to create a systemd service and a small script.
I'm imagining an API like this:
`tailscale dns add <IP> [--tls|--https] [--port int] [URL]`
`tailscale dns remove <IP>`
`tailscale dns set url <IP> <URL>`
`tailscale dns set type <IP> <udp|tls|https>`
`tailscale dns set port <IP> <port>`
`tailscale dns magic enable`
`tailscale dns magic disable`
`tailscale dns override enable`
`tailscale dns override disable`
All options related to DoT and DoH would come in handy once #74 hits.
Also, it's probably where DNS record and domain management will go if #1543 and #4515 are merged.

### What is the impact of not solving this?

There are two options:
1. Add IP addresses manually in the Web UI every time the key has expired or the new DNS node is added.
2. Disable key expiry on all DNS nodes, write down their IP addresses once. It would lower overall security.

**Comment by DentonGentry** [comment]
To set expectations, we're highly unlikely to add commands to the `tailscale` CLI which modify the entire tailnet.

We're much more likely to add an API in https://github.com/tailscale/tailscale/blob/main/api.md.
The API for DNS configuration had been kept in the private portion of the API only used by the admin panel because of the complexity in handling FallbackResolvers. We removed the [requirement for Fallback Resolvers](https://github.com/tailscale/tailscale/issues/1743) two days ago, after a long effort. I'd expect to be able to add a DNS configuration API endpoint at this point.

**Comment by KFearsoff** [comment]
I guess it's fair that DNS settings will be API-exclusive.

I see there already are API endpoints for completely replacing the list of DNS servers. I guess that could work for me with some heavy hackery, but I'd still prefer to have an endpoint that would just append a DNS server. Should I expect it to be implemented?

**Comment by DentonGentry** [comment]
> I'd still prefer to have an endpoint that would just append a DNS server. Should I expect it to be implemented?

Likely some day, but this is not currently being worked on.

**Comment by DentonGentry** [comment]
I think the main point of this feature request is covered in https://github.com/tailscale/tailscale/issues/2661
Closing as a duplicate.
