### ISSUE TITLE
FR: Allow to change the login server on iOS

### ISSUE THREAD

**Issue by HyptexPvP** [tailscale/tailscale#5431]
### What are you trying to do?

Im attempting to use my own login server for tailscale

### How should we solve this?

The same way it works on Android.

**Comment by DentonGentry** [comment]
On iOS the login server will be set via an API, available to MDMs and perhaps other mechanisms. The App Store review process frowns on "tap N times" functionality in the way it was done in the Android app.

**Comment by Stetsed** [comment]
@DentonGentry Hey, I wanted to ask if the app store review process is so against tap N functionality why not make it a default accessible option instead of having to hide it. 

I assume there has been consideration of this but this was decided against for reasons so may I ask what these are if this suggestion has come past before?

**Comment by DentonGentry** [comment]
As a percentage, very few users of the app will set an alternate control server URL. The mobile UI has very few functions in its menu. Centering functionality in the UI which will not make sense to the large majority of users, and make them wonder if they are supposed to set something there, is not a reasonable choice for the product.

**Comment by JulienMalka** [comment]
Hello,
I have another suggestion that may be worth considering. As I understand the matter Tailscale doesn't want the option for a custom control server to be too obvious in the UI (not to confuse the users), while we (the self-hosted community) want the option to be accessible without complicated machinery like MDMs.
What about adding a switch in the settings (not the settings of the app, the general settings of the device, in the "Tailscale" section)? There is already a "Reset Keychain" switch here, we could have a "Custom control server" switch as well. Then, when the switch is on, the menu in the app would allow for specifying the url of the control server.
This to me feels like a good compromise because now the setting will be hidden but still easily findable if you are looking for it.

**Comment by JulienMalka** [comment]
@coelho That's very true, I wasn't really thinking about an enterprise setting. My usecase is more like :
I want to give to my non tech parents/friends an access to let's say my cloud which is not exposed to the internet and I want it to be dead simple.

**Comment by DentonGentry** [comment]
> I want to give to my non tech parents/friends an access to let's say my cloud which is not exposed to the internet and I want it to be dead simple.

You might consider using Tailscale.

**Comment by coelho** [comment]
@JulienMalka I'd say this is more of a UI issue with certain "third party servers" to be resolved there.
They could the Web UI be a good "how-to" for each platform & a convenient link to the MDM profile. This would solve your concern as well :)

**Comment by coelho** [comment]
@DentonGentry Some users have great reasons for running on-prem login servers for specific workloads (besides cost). That's a whole box of worms though to get into! 

Off-topic 2c: Official on-prem solution + client support for multiple login servers? Would definitely turn some of these users into paying customers.

Either way, multiple login servers (on iOS) will allow some orgs to dip their feet in Tailscale's tech. That's a start & a win :)

**Comment by JulienMalka** [comment]
> > I want to give to my non tech parents/friends an access to let's say my cloud which is not exposed to the internet and I want it to be dead simple.
> 
> You might consider using Tailscale.

Well I'm also an enthusiast that likes to self-host the software I use.

**Comment by angussidney** [comment]
Just to confirm the status of this issue, is it currently possible to set the login server using MDMs, or is that a feature still in progress or waiting for app store review?

**Comment by inickt** [comment]
Throwing out another UX idea, if you want a custom server setting page without having UI in the app, you could implement a URL scheme that opens to the URL settings screen. Something like `tailscale://login-server`. Should be pretty easy to handle in the AppDelegate, and then any documentation you have for this feature could directly link to the URL scheme if you click it on the device. Easy enough to type manually in a browser as well.

Not sure if that is getting around the spirit of the "tap N times to reveal" (which I have seen used as debug panels in numerous apps on the App Store), but maybe that is something more in line with what the maintainers want.

**Comment by Schokobecher** [comment]
Yeah, sadly the profile has no effect so far as it's not implemented correctly (yet)

**Comment by maltegrosse** [comment]
@DentonGentry Is there any news regarding this feature on ios? Is there any way to support this feature?

**Comment by DentonGentry** [comment]
When we have news to report we will update this issue.
I understand that there is interest in this feature request.

**Comment by mihaip** [comment]
This is now available in v1.38.1, which was released on the App Store today. It is somewhat buried, but in the iOS Settings app's Tailscale section, there is now a "Alternate Coordination Server URL" field:

![image](https://user-images.githubusercontent.com/513813/225477049-0b1c9f99-2cd3-493e-927e-b72d663a9670.png)

If you're already signed in you'll need to sign out and sign back in for the setting to take effect.

**Comment by FrankUn** [comment]
> This is now available in v1.38.1, which was released on the App Store today. It is somewhat buried, but in the iOS Settings app's Tailscale section, there is now a "Alternate Coordination Server URL" field:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/513813/225477049-0b1c9f99-2cd3-493e-927e-b72d663a9670.png)
> 
> 
> 
> If you're already signed in you'll need to sign out and sign back in for the setting to take effect.


This feature is a bit buggy. If a wrong url being input once, the apps become completely unusable, removing the app and data can't help either

**Comment by bradfitz** [comment]
@FrankUn, we don't track closed issues. They don't show up on our dashboards, etc. Please open a new issue with details. Thanks.
