### ISSUE TITLE
Internal Server Error on log in for 1 specific user

### ISSUE THREAD

**Issue by jdgiddings** [tailscale/tailscale#5432]
### What is the issue?

I have a user who is trying to log in to Tailscale using Microsoft SSO. When she tries to log in, login.tailscale.com returns a 500 internal server error

We have tried different browsers, clearing the cache, incognito mode, reinstalling, etc. Nothing seems to fix the issue

![unknown](https://user-images.githubusercontent.com/79322633/186719691-e3728638-636f-4bc6-993a-3d52989c2b35.png)

### Steps to reproduce

Attempt to log in to Tailscale using Microsoft SSO

### Are there any recent changes that introduced the issue?

Unknown

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.28.0

### Bug report

BUG-57e3ce3d80e31db3d32b25918aa0d912cfaa75e83b21e2a3e73c7b78087abdb0-20220825162234Z-ff867bf0a825b575

**Comment by DentonGentry** [comment]
We can't really correspond about the details of an individual user on a public bug.
Please file this same request using https://tailscale.com/contact/support/ so we can email privately.
