### ISSUE TITLE
Android FireStick running as an exit node can't serve DNS

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#5468]
### What is the issue?

Testing with FireStick and the latest version on F-Droid, it looks like the latest version does not support being used as an Exit Node.

TailScale: https://f-droid.org/repo/com.tailscale.ipn_117.apk
FireOS 7.2.9.2

### Steps to reproduce

Tap the three dots and select "Run exit node"

### OS version

FireOS 7.2.9.2

### Tailscale version

1.29.72-tb905db7a5-g9e6ef85d269 (117)

### Bug report

(Cannot paste bug report URL on the fire stick...sorry!)

**Comment by bradfitz** [comment]
So what happens instead?

**Comment by wingcomm** [comment]
Can’t get any traffic through from clients trying to use the fire stick. The fire stick can use exit nodes but other nodes trying to use the fire stick as an exit node cannot pass any internet bound traffic through it.

**Comment by bradfitz** [comment]
Does only DNS not work? Can you ping via it? Can you do TCP? E.g. curl 8.8.8.8

**Comment by wingcomm** [comment]
@bradfitz

Looks like you are right! 

```
user@computer ~ % ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: icmp_seq=0 ttl=64 time=77.799 ms
64 bytes from 1.1.1.1: icmp_seq=1 ttl=64 time=287.461 ms
^C
--- 1.1.1.1 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 77.799/182.630/287.461/104.831 ms
user@computer ~ % curl 1.1.1.1
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
user@computer ~ %
```

**Comment by bradfitz** [comment]
(You might be hitting #5425 fixed by pending change #5503. Does your FireStick location have IPv6 connectivity?)

**Comment by wingcomm** [comment]
@bradfitz We ended up giving up on the fire stick for a few other reasons so I'm afraid I cannot test it again. That said, I did try some DNS lookups back when I was testing before and the did fail. The FireStick did have IPv6.

**Comment by DentonGentry** [comment]
I think this is probably https://github.com/tailscale/tailscale/issues/5425, closing as a duplicate.
