### ISSUE TITLE
Tailscale backend error on Windows Server 2012 R2

### ISSUE THREAD

**Issue by dmarcsift** [tailscale/tailscale#547]
**Describe the bug**
Installing 0.100.0-17 on Windows 2012 R2 in AWS causes the following error when installing:
<img width="512" alt="Screen Shot 2020-07-12 at 3 51 47 PM" src="https://user-images.githubusercontent.com/41596894/87258379-f2078780-c457-11ea-90fa-05ea5e50d3e1.png">

Initially I had installed the exe from the downloads page (0.99.1). That was causing an error so I Googled around and came to the post from a few days ago linking the new installer 0.100.0-17. 

**To Reproduce**
1. Install 0.99.1 to a Windows 2012 R2 machine. 
2. Uninstall.
3. Install 0.100.0-17.
4. Error pops up at the end of the installer.

**Expected behavior**
The application should install and be available for logging in.

**Version information:**
 - Device: AWS m4.2xlarge
 - OS: Windows
 - OS version: Windows 2012 R2
 - Tailscale version: 0.100.0-17

**Comment by bradfitz** [comment]
I can't reproduce this.

@dmarcsift, can you install 0.100.0 again and paste your installer logs?

If you click "Show Details" then right click you can copy the entire log to the clipboard.

<img width="431" alt="Screen Shot 2020-07-13 at 11 18 21 AM" src="https://user-images.githubusercontent.com/2621/87338939-bbcf1400-c4fa-11ea-9158-8c99530bdc76.png">
<img width="432" alt="Screen Shot 2020-07-13 at 11 18 50 AM" src="https://user-images.githubusercontent.com/2621/87338946-bd98d780-c4fa-11ea-8e5e-592f722ea82e.png">

**Comment by dmarcsift** [comment]
InitDriverSetup: 
Output folder: C:\Program Files (x86)\Tailscale IPN
Extract: tailscale-ipn-new.exe... 100%
MakeDead: 93.1
Uninstalling service
logtail started
Program starting: v0.100.0-17-g2a375c438, Go 1.14.4-ts56db765: []string{"C:\\Program Files (x86)\\Tailscale IPN/tailscale-ipn-new.exe", "/uninstall"}
LogID: f34215de2dcba01345ace150c062bf753c9f507d5208fb171485dcb28b332698
stdout ok.
stderr ok.
printf ok.
log ok.
Uninstalling service...
flushing log.
logger closing down
logtail: upload: log upload of 428 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/d854f7ef27c2e004a184a495ae823fd550c1f2807d2d47c4f34fd8c1a97cd266": context canceled
UninstallService: 0
Killing old wireguard.exe...
Kill: 603
Find: 603
Killing old tailscale-ipn.exe...
Kill: 603
Find: 603
Rename: tailscale-ipn-new.exe->tailscale-ipn.exe
Windows major version: 
Using 64-bit dev signing.
Extract: wintun.inf... 100%
Extract: wintun.sys... 100%
Extract: wintun.cat... 100%
Extract: drvinst.exe... 100%
Extract: RunFromProcess.exe... 100%
Removing old driver.
Uninstalling driver for 'Wintun'
Deleting devices for 'Wintun'
Installing device driver
0 matching device(s) exist already.
Creating device 'Wintun'
Created. (Wintun, ROOT\WINTUN\0001)
Installing driver 'Wintun' from 'C:\Program Files (x86)\Tailscale IPN/wintun.inf'
UpdateDriverForPlugAndPlayDevices returned e0000247 (The Unicode character is not defined in the Unicode character set installed on the system.)
Deleting devices for 'Wintun'
Deleting device 'ROOT\WINTUN\0001'
SetupDiCallClassInstaller returned e0000204
FormatMessage returned error code 0000013d
CreateDevice: 1
Created uninstaller: C:\Program Files (x86)\Tailscale IPN\Uninstall.exe
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tailscale.lnk
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Tailscale.lnk
Installing IPN service
logtail started
Program starting: v0.100.0-17-g2a375c438, Go 1.14.4-ts56db765: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe", "/install"}
LogID: f34215de2dcba01345ace150c062bf753c9f507d5208fb171485dcb28b332698
stdout ok.
stderr ok.
printf ok.
log ok.
Installing service...
flushing log.
logger closing down
logtail: dial "log.tailscale.io:443" failed: dial tcp <redacted IP>:443: operation was canceled (in 32ms)
logtail: upload: log upload of 335 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/d854f7ef27c2e004a184a495ae823fd550c1f2807d2d47c4f34fd8c1a97cd266": context canceled
Starting client
Completed

**Comment by bradfitz** [comment]
Ooooh, this is interesting:

```
UpdateDriverForPlugAndPlayDevices returned e0000247 (The Unicode character is not defined in the Unicode character set installed on the system.)
```

**Comment by bradfitz** [comment]
@apenwarr, any ideas?

**Comment by cpatulea** [comment]
Can user reproduce while running ProcMon (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and upload the trace?

**Comment by dmarcsift** [comment]
@cpatulea I invited you to a private repo in my account with the PML. Just for security peace of mind. Does that format work? Or should I export as CSV or XML?

**Comment by bradfitz** [comment]
@dmarcsift, can you share it with me too?

**Comment by dmarcsift** [comment]
I added you @bradfitz

**Comment by bradfitz** [comment]
@dmarcsift, where? I don't see any invitation in email or github notifications.

**Comment by dmarcsift** [comment]
I invited you from my other personal account. However I just set up a new repo on my work account and invited the two of you. I also forgot to hit the commit button when I uploaded the logs.

**Comment by cpatulea** [comment]
PML format is fine. I see events for processes "tailscale-ipn-setup-0.100.0-17.exe", "tailscale-ipn-new.exe", and similar, but no traces for "drvinst.exe". I suspect you used a filter on process name "*tailscale*". Could you re-record a trace which also includes "drvinst.exe"?

**Comment by cpatulea** [comment]
I also noticed that the latest tailscale download is 0.100.0-107, while you are attempting to install -17. Does the issue also reproduce with -107?

**Comment by dmarcsift** [comment]
OK. So I installed 107 and it's working. I would consider this resolved. Thank you both.

**Comment by bradfitz** [comment]
@dmarcsift, well, we haven't fixed it yet. It's just that it happens somewhat randomly and you must've gottten lucky with the most recent run.

But we have other bugs tracking the general problems so it's also fine to keep this one closed.
