### ISSUE TITLE
drastic reduction in network bandwidth when routing traffic via exit node 

### ISSUE THREAD

**Issue by sanilcredcore** [tailscale/tailscale#5476]
### What is the issue?

I have a Exit node setup in AWS N.virgina(US_east-1) region. Its a t2.micro(Amazon Linux) which allows for speeds upto 1GBPS.
Seeing drastic reduction in network bandwidth when routing traffic via the same. I am located in New york
please guide on some of the possible reasons for the issue 

![image (2)](https://user-images.githubusercontent.com/106259068/187134865-e191797a-e382-47bc-a36d-2ed78008b7ba.png)

![image (3)](https://user-images.githubusercontent.com/106259068/187134871-a81332d0-358c-4213-bcd7-9a41b32d1fbd.png)

### OS version

Amazon linux 2

### Tailscale version

1.28.0

**Comment by sylr** [comment]
Don't use bustable instances if you care about bandwidth. The more data you proxy via tailscale, the more CPU you'll need and tX instances will degrade quite rapidly.

**Comment by sanilcredcore** [comment]
The same issue was also seen with a C5.large instance. When a speedtest(https://www.speedtest.net/apps/cli) was run on the node itself I got 4700+ mbps upload and download speeds. But the same drastically reduces, when we  use the machine as an exit node. 

What do your performance benchmarking tests indicate? Can you publish some guidelines around what kind of AWS instances we should use as exit nodes

**Comment by amanjuman** [comment]
I have the same issue. The server I'm using as Tailscale exit node and WireGuard server when I use Tailscale as the exit node, I get around 45Mbps, and when I use WireGuard, I get around 87Mbps when the server bandwidth cap is 120Mbps.

**Comment by DentonGentry** [comment]
If the exit node is using `--tun=userspace-networking`:
In Tailscale releases prior to 1.32.1, userspace-networking did not handle TCP selective acknowledgement and suffered large performance loss from moderate packet loss. If your exit node is impacted, it may be that a macOS client is just better able to cope even in cases where SACK is not available.

**Comment by sanilcredcore** [comment]
the issue seems to be irrespective of the client we run it from. we used windows and mac clients. Is the issue resolved in the latest version of tailscale?

**Comment by DentonGentry** [comment]
If the exit node is using --tun=userspace-networking, you should update the exit node to 1.32.1 or later.

**Comment by sanilcredcore** [comment]
we followed the instructions provided below for linux as is. so looks like we aren't using the above option
https://tailscale.com/kb/1103/exit-nodes/?tab=linux

**Comment by DentonGentry** [comment]
Tailscale 1.36 included substantial performance improvements: https://tailscale.com/blog/throughput-improvements/

**Comment by DentonGentry** [comment]
The 1.40 release contained additional throughput improvements described in [Surpassing 10Gb/s over Tailscale](https://tailscale.com/blog/more-throughput/)

**Comment by sanilcredcore** [comment]
thanks. we did notice significant improvements. Closing this bug
