### ISSUE TITLE
slowness for 4/54 users because of maybe more relay connections

### ISSUE THREAD

**Issue by pkolbevfx** [tailscale/tailscale#5480]
### What is the issue?

We're noticing more relay (rather than direct) connections this morning than usual. (4/54)
Users are using windows/mac and running all assortment of versions. :) (sorry, not useful)

**Comment by bradfitz** [comment]
There's no information here on which we can act so I suppose we can only apologize and empathize? That must be frustrating.

What would you like from us?

**Comment by pkolbevfx** [comment]
Thx Brad. Nothing. But I thought it might be related to https://github.com/tailscale/tailscale/issues/5476 and I just was hoping it might help triangulate the issue. 
Thx for the reply.

**Comment by DentonGentry** [comment]
At this point I think I'll close this. We do not see sign of a widespread issue with direct connections in fleetwide metrics. The specific use of relay versus direct can vary depending on the state of intervening NAT engines (whether they have any open slots, for example) or when multiple nodes all try to use the same port at the same time and the NAT engine can only handle some of them.

`randomizeClientPort` can help with firewalls with this behavior, described in https://tailscale.com/kb/1181/firewalls/

**Comment by pkolbevfx** [comment]
thank you
