### ISSUE TITLE
Cannot establish tailnet connections due to "Received invalid initiation message"

### ISSUE THREAD

**Issue by lifejw** [tailscale/tailscale#5481]
### What is the issue?

Since the update to iOS 15.6.1 on iPhone X, no connection can be established to any of the devices on the tailnet (local and external), EXCEPT when exit node is enabled. And in this case only the exit node can be reached. 
I also have a subnet router in use, which obviously is also not reachable as well as the clients behind.
I've been reinstalling the app and the VPN profile without success.
I'll help with more info as good as I can :)

### Steps to reproduce

Simple iOS Update. 
Reopen app.
Tadaa.

### Are there any recent changes that introduced the issue?

iOS Update to 15.6.1

### OS

iOS

### OS version

15.6.1

### Tailscale version

1.28.0

### Bug report

BUG-e42a0f7bea6cabeee19c2ea617577c785ed9df3789f291696222fcab8570fbd0-20220829152101Z-18f0c29c6c1fcd1d

**Comment by wingcomm** [comment]
Can you share the output of the following from another system running tailscale?

`tailscale ping <iphoneip>`
`tailscale status`

**Comment by DentonGentry** [comment]
On the iPhone around the time of the bugreport :
`2022-08-29 15:15:53.624615 +0000 UTC: Received invalid initiation message from 3982a39bf45b00e69c750daca0a8641108384656b3a9595ae18f1eddae90df5a`

The messages concern the exit node.

The last known issue which resulted in "Received invalid initiation message" errors was https://github.com/tailscale/tailscale/issues/3088 and fixed in 1.18. This appears to be something else.

**Comment by lifejw** [comment]
@wingcomm 
Sorry for my late reply. 
Ping gives a normal response with name (tailscale ip) [real ip]:port time.
Status also shows all the devices and their direct connection.

@DentonGentry 
Is there a way I can support you?
I'm running the exit node on a Ubuntu 22.04.1 (Kernel 5.15.0-47-generic) system.

(Interestingly it only appears to be not working when using the iPhone. All other devices are working flawlessly.)

**Comment by DentonGentry** [comment]
I no longer see `Received invalid initiation message` telemetry from that iPhone, is the issue still happening?

**Comment by lifejw** [comment]
Sorry for my late reply.
Unfortunately yes.
I will try to reinstall the server and iOS application.
Let's see.

**Comment by DentonGentry** [comment]
At this point I don't expect to be able to diagnose what was happening last August.
If it happens again please reopen the bug and attach a fresh bugreport.
