### ISSUE TITLE
The Slack invite link in Community wiki page doesn't work

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#5518]
### What is the issue?

When I tried to signup with my gmail account, it complains about "The email address must match one of the domains listed below. Please try another email."  

![image](https://user-images.githubusercontent.com/787544/187880396-15e8b02e-6a0a-4883-8d5e-73c8cd8df4ee.png)

### Steps to reproduce

N/A

### Are there any recent changes that introduced the issue?

N/A

**Comment by DentonGentry** [comment]
Ah: the Community Slack was discontinued a long time ago, replaced with a Discourse server at https://forum.tailscale.com/
I've updated the Community Wiki, didn't realize the Slack was still listed there.
