### ISSUE TITLE
FR: Exposing endpoint on Public Internet

### ISSUE THREAD

**Issue by rishabmehta7** [tailscale/tailscale#5520]
### What are you trying to do?

Connect and access Home Assistant on Public Internet.

### How should we solve this?

Allow for the magicDNS values to be optionally resolvable on Public Internet.

**Comment by DentonGentry** [comment]
Your goal is to access a Home Assistant remotely, but not go over the tailnet to do so?

**Comment by bennycornelissen** [comment]
@rishabmehta7 have you looked into Ngrok? (https://ngrok.com)

I've been using Ngrok to expose arbitrary endpoints (temporarily) on the internet, and Ngrok is great for that. If Tailscale would happen to do the basic functionality of Ngrok (without the weird limitations), I would love that. I could get rid of another subscription 😉 

But until that's the case, if you want to arbitrarily expose things on the internet without dealing with port-forwarding, DNS, TLS, or firewalls, Ngrok might be worth considering. 

(full disclosure: I have no affiliation whatsoever with Ngrok)

**Comment by DentonGentry** [comment]
I think the request is to make Home Assistant be reachable on the tailnet. The main gotcha is that the [integration on home-assistant.io](https://www.home-assistant.io/integrations/tailscale/) does NOT provide Tailscale connectivity. It monitors the tailnet, it doesn't join the tailnet.

There is a community add-on to join the tailnet: https://github.com/hassio-addons/addon-tailscale
