### ISSUE TITLE
FR: Control Plane Compromise Mitigations

### ISSUE THREAD

**Issue by kabirbenepass** [tailscale/tailscale#5523]
### What are you trying to do?

I'd like to be able to add an additional safeguard in the event that Tailscale's control plane is compromised, so that even in the worst case, an attacker can't connect arbitrary nodes to my Tailnet. 

### How should we solve this?

I could imagine solving this issue by one of:
- Allowing a custom (user controlled) CA to sign machine certs (w/ the CA being provided to tailscaled during setup)
- Allowing a custom (user controlled) CA to sign ACLs (w/ the CA being provided to tailscaled during setup)
- Adding an option for tailscaled to run an external command upon receiving a new peer and only accept the peer if the command exits successfully (the classic Unix "just run a shell script" approach :)

### What is the impact of not solving this?

This is pretty much the only impediment right now to my deploying Tailscale throughout our AWS infrastructure and user endpoints.

### Anything else?

I'm a HUGE, HUGE, HUGE fan of Tailscale in general and more than happy to write the initial version of something like this and contribute a PR if that's of interest :)

**Comment by crawshaw** [comment]
Hi @kabirbenepass! Are you an existing customer? We have some work in this space I could chat about with you on a call if you're interested, want to send me an email? crawshaw@tailscale.com

**Comment by kabirbenepass** [comment]
I am! Will do :)

**Comment by DentonGentry** [comment]
In December Tailnet Lock became available as an alpha release.
https://tailscale.com/blog/tailnet-lock/
