### ISSUE TITLE
wgengine/magicsock: disco broken on Linux with new BPF fanciness

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5536]
magicsock disco is broken on Linux since c72caa6672c83a981e7b9ffcaa2f12fd9351d17e

Tracking bug with more info to come.

/cc @raggi @danderson @andrew-d

**Comment by bradfitz** [comment]
workaround is setting `TS_DEBUG_DISABLE_RAW_DISCO=1` (ignore the old knob name in the linked commit message above)

**Comment by raggi** [comment]
## Symptom

A BPF enabled node that has just rebound one of its UDP ports (by restart or rebind) that has an existing Disco session with a peer becomes "stuck" where Disco traffic between the peers continues to flow (e.g. with TS_DEBUG_DISCO=1 ping/pongs are observed), however the sending node has bound the disco session to an old port number (observable from the disco "now using" log line).

## Cause

The BPF filter passes all packets with Disco data headers to a family specific port 17. As there is no check against the destination port, incoming disco ping messages to any port, such as old ports that are no longer bound are responded to. In one reproduction condition, a peer node sends a disco ping to the BPF enabled receiver, destined for an old port number. The BPF enabled node replies causing the sending node to assume that the port to which it sent the ping is usable to flow traffic. Further ping/pong exchanges to this port continue to work, however WireGuard traffic to this port does not reach the BPF enabled node, as it is not listening on that port.

**Comment by bradfitz** [comment]
> family specific port 17

That's just the UDP protocol number. That's not a port number?

**Comment by raggi** [comment]
> > family specific port 17
> 
> That's just the UDP protocol number. That's not a port number?

```
udp   UNCONN   0      0                                         0.0.0.0:17                  0.0.0.0:*      users:(("tailscaled-bpfd",pid=87283,fd=12))
udp   UNCONN   0      0                                               *:17                        *:*      users:(("tailscaled-bpfd",pid=87283,fd=13))```
