### ISSUE TITLE
FR: make table columns on https://login.tailscale.com/admin sortable

### ISSUE THREAD

**Issue by whysthatso** [tailscale/tailscale#5540]
### What are you trying to do?

in order to focus on certain machine attributes on the admin dashboard, it would be helpful to make the columns of the all the tables sortable.

### How should we solve this?

simple client-side html element ordering maybe? switchable between possibly alphabetical/numerical ascending and descending.

### What is the impact of not solving this?

ctrl-f and hope that all the important attributes get highlighted :D

### Anything else?

this should be considered for these views:
https://login.tailscale.com/admin/machines
https://login.tailscale.com/admin/services
https://login.tailscale.com/admin/users

**Comment by mihaip** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2537#issuecomment-888442297

**Comment by whysthatso** [comment]
i very much like @rosszurowski comment over there and would be happy if the filtering through ui would be implemented at one point. closing this for now.
