### ISSUE TITLE
FR:  Add an alternative method to connect tailscale and tailscaled on systems without unix socket support

### ISSUE THREAD

**Issue by diyism** [tailscale/tailscale#5546]
### What are you trying to do?

I want to run arm64 tailscaled and tailscale in android adb command lines:

`./tailscaled --tun=userspace-networking --state=./tailscaled.state --socket=./tailscaled.sock --port 41641 --socks5-server 0.0.0.0:8080`

it says: listen unix ./tailscaled.sock: bind: permission denied

### How should we solve this?

Maybe, we can add an alternative method (for example a tcp port 127.0.0.1:9999) to manage tailscaled without using the unix domain socket

### What is the impact of not solving this?

I'm naive about this problem, maybe a foolish feature request.

**Comment by DentonGentry** [comment]
You're trying to run tailscaled+tailscale on Android?

Lack of unix sockets is only the first blocker you'll encounter. Android may use a Linux kernel, but its userland is entirely different from a regular Linux distribution. Even its kernel has an array of additional restrictions, trying to keep miscreat apps in check. As just a couple examples:
1. `tailscaled` DNS for Linux supports `/etc/resolv.conf`, `systemd-resolved`, and `NetworkManager`. Android uses none of these, instead we implemented an [entirely separate mechanism using Android Frameworks](https://github.com/tailscale/tailscale-android/blob/main/android/src/main/java/com/tailscale/ipn/DnsConfig.java).
1. Android doesn't allow apps to use RTM_GETLINK, which Go for Linux uses. We [implemented alternate support using Android Frameworks](https://github.com/tailscale/tailscale-android/pull/21).

`tailscaled` compiled for Linux implements none of this. https://github.com/tailscale/tailscale-android implements the needed support to run on Android.

**Comment by DentonGentry** [comment]
Since you have a solution I'll close this.
