### ISSUE TITLE
Ability to enable subnet routes without server interaction 

### ISSUE THREAD

**Issue by jaxxstorm** [tailscale/tailscale#555]
**Describe the solution you'd like**

I'm creating a bastion host in AWS with an autoscaling group of min size/max size 1, so it gets replace when it's unhealthy. Unfortunately, every time it gets restarted, I have to go into the tailscale admin console and allow the subnet routes again, which means automation isn't fun.

It would be great if there was an API we could use (I suspect there is, but it isn't public?) where I can make a request to the console to allow subnet routes on the machine

**Comment by dkerwin** [comment]
I have a similar case: A keepalived cluster that advertises a subnet that can be on one of the two nodes. When there is a failover we have to enable/disable subnet routes in the admin interface. Being able to do that (limited to a defined set of machines) automatically would be really awesome.

**Comment by apenwarr** [comment]
Most likely we shouldn't have an API for this exactly, but instead do
something with ACL tags that let certain tags have auto-approval
rights for certain subnets.

On Fri, Jul 17, 2020 at 3:31 AM Daniel Kerwin <notifications@github.com> wrote:
>
> I have a similar case: A keepalived cluster that advertises a subnet that can be on one of the two nodes. When there is a failover we have to enable/disable subnet routes in the admin interface. Being able to do that (limited to a defined set of machines) automatically would be really awesome.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by dkerwin** [comment]
Sounds good to me. I like the idea to tie it to labels and the ACL

**Comment by jaxxstorm** [comment]
Would love to know if there's anything planned here!

**Comment by DentonGentry** [comment]
Subnet routes can be approved using the API now: https://github.com/tailscale/tailscale/blob/main/api.md#post-apiv2devicedeviceidroutes---set-the-subnet-routes-that-are-enabled-for-a-device

I'm going to close this as fixed, please reopen if something doesn't work or is not clear.
