### ISSUE TITLE
ACL editor indicates "unknown error" when an undefined tag is mentioned

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#5551]
### What is the issue?

An ACL with an undefined tag produces the following error:

> An unknown error occurred while saving your policy file. Please copy your changes and try again later. If the error persists, please contact us for support.

### Steps to reproduce

Try to save the following ACL:

```json
{
	"TagOwners": {
		"tag:a": []
	},
	"ACLs": [
		{
			"Action": "accept",
			"src": [
				"*"
			],
			"dst": [
				"tag:a:*",
				"tag:b:*"
			]
		}
	]
}
```

Removing the `"tag:b:*"` line results in success.

**Comment by bradfitz** [comment]
cc @maisem

**Comment by mihaip** [comment]
31bf3eb1010382acedd74b4b634dfa0a9207b455 ends up fixing this too

**Comment by mihaip** [comment]
@dsnet this seems like a bug with go-json-experiment. Given this response: `&{Status:error Error:ports: tag not found: "tag:b" ErrorCode: Data:[]}` it gets marshaled as `"{\"status\":\"error\",\"error\":}"`, which is malformed JSON.

**Comment by dsnet** [comment]
Looking. What's the Go data type  of this?

**Comment by mihaip** [comment]
It's `response`, generated by https://github.com/tailscale/corp/blob/31bf3eb1010382acedd74b4b634dfa0a9207b455/control/adminhttp/api.go#L2925-L2929

**Comment by dsnet** [comment]
Was the malformed JSON in https://github.com/tailscale/tailscale/issues/5551#issuecomment-1239819013 obtained before or after https://github.com/tailscale/corp/commit/31bf3eb1010382acedd74b4b634dfa0a9207b455?

**Comment by mihaip** [comment]
Before

**Comment by dsnet** [comment]
I suspect that this is a bug that has been fixed upstream in https://github.com/go-json-experiment/json/commit/920431bcabd0ac53771f75be105b841273c0332e.

I think we just need to update the `go-json-experiment` module.

**Comment by mihaip** [comment]
Yes, verified that updating the module fixes this. Will send a PR.

**Comment by dsnet** [comment]
Nice. I love it when the fix is just to update a version.
