### ISSUE TITLE
FR: Quick link to go to admin console on android phone

### ISSUE THREAD

**Issue by KayLEvans** [tailscale/tailscale#5557]
### What are you trying to do?

I would like to be able to get to the admin console quickly on my android phone without having to stop what I'm doing, separately open a browser and type "login.tailscale.com". :(

### How should we solve this?

Add it to the 3 dot menu with the other stuff

### What is the impact of not solving this?

:(

**Comment by agottardo** [comment]
Added in the Settings menu of the new Android app, closing.
