### ISSUE TITLE
macOS: Fix tense for device key expiry

### ISSUE THREAD

**Issue by danielcompton** [tailscale/tailscale#5559]
### What is the issue?

The tense of the device expiry is wrong once the key expires:

<img width="287" alt="Screenshot of Safari (7-09-22, 11-59-10 AM)" src="https://user-images.githubusercontent.com/811954/188764775-1a281dbb-92de-4048-b87a-2feb4f5b4b72.png">

It should be "Device key expired 18 minutes ago".

### Steps to reproduce

Let your key expire

### OS

macOS

### OS version

macOS 12.5.1

### Tailscale version

1.28.0

### Bug report

BUG-445938c11d97c1773af606856dd49ce37c15f2323fc6164090cfb54c3b9cb196-20220907004941Z-93e2ab8a1537314a

**Comment by mihaip** [comment]
Thanks for noticing this, the fix will be in Tailscale 1.32 (or the next [unstable release](https://tailscale.com/kb/1083/install-unstable/) of 1.31).
