### ISSUE TITLE
Scrolling on mobile causes the header to scroll as well

### ISSUE THREAD

**Issue by ericswpark** [tailscale/tailscale#5561]
### What is the issue?

When scrolling the list of clients on mobile, the scrollview extends to the header, causing it to be scrolled as well. Ideally the header (containing the on/off button and the current device hostname/IP) should stay pinned at the top and should not be scrollable.

### Steps to reproduce

Scroll by dragging your fingers across the main screen once authenticated.

### Are there any recent changes that introduced the issue?

Not that I know of; it had always behaved like this and it is kind of annoying when you want to enable/disable Tailscale quickly and the header is out of the viewport.

### OS

iOS, Android

### OS version

N/A

### Tailscale version

N/A

**Comment by agottardo** [comment]
Major UI changes in v1.46 have addressed this.
