### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by sascha-andres** [tailscale/tailscale#5564]
### What is the issue?

Can't access machines on my tailscale with error no route to host

### Steps to reproduce

`ssh user@machine` or `tailscale ssh machine`

Output of the latter:

```
Dial("sascha-laptop-kde.briefbote.gmail.com.beta.tailscale.net.", 22): unexpected HTTP response: 502 Bad Gateway, dial failure: dial tcp 100.76.53.78:22: connect: no route to host

kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

### OS

Linux

### OS version

Manjaro latest

### Tailscale version

1.28.0

### Bug report

BUG-143ff8f39827fa2619343e0516fdc40f1e6296a2e618c58f72e517ca32578afc-20220907195622Z-a4dde6bc4621239c

**Comment by bradfitz** [comment]
Looks like the machine is up fine, but not replying to port 22:

```
open-conn-track: timeout opening (TCP 100.83.86.60:36516 => 100.76.53.78:22) to node [fCF5G]; online=yes, lastRecv=5s
```

Looks like the target machine isn't using Tailscale SSH, so you don't want `tailscale ssh`. You just want regular `ssh`. But seems like your target machine's firewall is blocking port 22. (Your Tailscale ACL permits it)

I see nothing obviously wrong with Tailscale itself.

If you turn use Tailscale SSH instead you won't have that host firewall problem on your Ubuntu machine.

**Comment by sascha-andres** [comment]
You're right. Had nothing to do with tailscale here.

Solution: 
(1) configured firewall rule for incoming SSH was non permanent and dropped after a reboot

The error message no route to host (also with standard ssh) was leading me on the wrong path here
