### ISSUE TITLE
Connecting to Xpra session via Tailscale SSH seems to miss PATH initialization

### ISSUE THREAD

**Issue by ShadowJonathan** [tailscale/tailscale#5572]
### What is the issue?

When I start a new xpra session (`xpra start ssh://server/ --start=xeyes`), over Tailscale SSH, it seems to miss initialising a `PATH` variable;
- `[Errno 2] No such file or directory: 'python3.6': 'python3.6'`
- `[Errno 2] No such file or directory: 'xeyes': 'xeyes'`

However, when i connect it via LAN, it seems to correctly initialise this.

### Steps to reproduce

1. Install xpra on client and server
  - Note, for debian/ubuntu installs, install the latest version from the xpra repository directly, instructions [here](https://askubuntu.com/a/1203771)
2. Install tailscale (with `--ssh`)
3. Start xpra session over tailscale IP (`xpra start ssh://1XX.XXX.XXX.XXX/ --start=xeyes`)
4. Expect it to work normally

Location of server logs are found in the terminal, but usually its `/run/user/1000/xpra/0/server.log`

### OS

Linux

### OS version

Ubuntu 18

### Tailscale version

1.30.0

### Bug report

BUG-2bf13179fe651a7dff1e64a531c4d3cc7c7dbac292339c149f66ef8b132211db-20220908102522Z-88f062e5e2221533

**Comment by ShadowJonathan** [comment]
Note that this only pertains to creating new sessions over xpra, doing `xpra attach` to an existing session via tailscale connects successfully, which is a successful workaround for my usecase.

**Comment by DentonGentry** [comment]
Related: https://github.com/tailscale/tailscale/issues/5285

**Comment by bradfitz** [comment]
Closing as dup of #5285 which now has more details.
