### ISSUE TITLE
Rewrite the nginx auth code to not parse beta.tailscale.net domains

### ISSUE THREAD

**Issue by nyghtowl** [tailscale/tailscale#5576]
Part of this was solved with #5516

Following up on Will's idea to add Tailnet prefix to [tailcfg.Node](https://github.com/tailscale/tailscale/blob/cfbbcf6d071dd13addbc1b38ef993a08d557ba22/tailcfg/tailcfg.go#L166), and then remove/move parsing logic.

**Comment by DentonGentry** [comment]
I think we did this in a `tailscale-nginx-auth-0.1.2` release last week.
