### ISSUE TITLE
FR: Callback for login URL for tsnet.Server

### ISSUE THREAD

**Issue by eric** [tailscale/tailscale#5591]
### What are you trying to do?

I would like to integrate `tsnet.Server` and provide the URL-based login flow to users. Right now the interactive login URL is [only logged](https://github.com/tailscale/tailscale/blob/f3ce1e2536e79677da52baade5e9757caea12780/tsnet/tsnet.go#L409). It would be nice to have a callback that could be registered for to receive that URL instead.

### How should we solve this?

Provide a callback function with the `st.AuthURL`

### What is the impact of not solving this?

We would require the user to pre-generate an authkey or would have to sniff the logs to find the URL.

**Comment by DentonGentry** [comment]
We can probably provide a callback with similar information as what [`tailscale up --json` provides](https://github.com/tailscale/tailscale/blob/d5e7e3093d569d5e51cda3d5dcdf3f5b496b3ee9/cmd/tailscale/cli/up.go#L191)
- the AuthURL
- a QR code, encoded as a DataURL
- the current BackEnd state
- any errors

**Comment by eric** [comment]
As I was experimenting more, I figured out how to get the information I need to be able to poll for the state, and get the `AuthURL`:

``` go
        server := new(tsnet.Server)
	lc, err := server.LocalClient()
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	log.Printf("status = %#v", lc.Status(context.Background()))
```

I'm not sure if this is the best or only way to handle this, but it's a good start.

**Comment by eric** [comment]
This is good enough.
