### ISSUE TITLE
`tailscale up` on second use of tagged auth key additionally requires `--advertise-tags=...`

### ISSUE THREAD

**Issue by ericsampson** [tailscale/tailscale#5597]
### What is the issue?

The following behavior makes it more clumsy to use tools like Ansible for provisioning nodes.
It can be worked around, but it feels to me like I should be able to use tagged auth keys with `tailscale up` in an idempotent fashion.

### Steps to reproduce

```
tailscale up --auth-key=tskey-BLAH # works fine. The auth key has a FOO tag, and it's applied succesfully.
tailscale up --auth-key=tskey-BLAH
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

	tailscale up --auth-key=tskey-BLAH --advertise-tags=tag:FOO
```

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.30.1

### Bug report

BUG-c91f44a8898d693137ea45570f0747a5b2b0a3cba3a6adef4c8801a03425c5df-20220912033515Z-26da041f48a1c271

**Comment by ericsampson** [comment]
I'll try to reproduce again and post my results, thanks!

**Comment by ericsampson** [comment]
@s-aia I just had a thought; at the time, I may have been using the OSS tailscale version, rather than the GUI one--I flipped back and forth, so I'm not sure which one I was using at the time unfortunately.

 I'm not sure if the CLI binary varies between them, but just thought that I'd throw that out there just in case.
 I'll still try reproducing on my end. cheers

**Comment by DentonGentry** [comment]
We've not been able to produce this issue here. Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by ericsampson** [comment]
@DentonGentry sorry, Haven't been able to take the time to sufficiently reproduce the situation.
I suspect that it might have been something else going on.

Let's close this, and in the future if it comes up again or another customer reports it, they can reopen this issue.

Cheers
