### ISSUE TITLE
"Tailscale Up" not working with Debian Preseed; tailscaled not running during install

### ISSUE THREAD

**Issue by DLopezJr** [tailscale/tailscale#5598]
### What is the issue?

**Details:** Debian .iso's support "preseed" configuration files that allow to unattended installs with predetermined configurations. 

**Expected behavior:** Ability to authorize an _unattended_ Debian install with tailscale authkey/ssh.

**Current behavior:** "_tailscale up --authkey \<key> --ssh_" fails during the unattended install. 

**Debugging:** Once the machine reboots, entering the **same** command will provide the expected behavior.

**Error output:** "failed with exit code 127"

### Steps to reproduce

All steps below but "tailscale up" function correctly:

```
d-i preseed/late_command string \
    wget -q -O /target/usr/share/keyrings/tailscale-archive-keyring.gpg https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg ; \
    wget -q -O /target/etc/apt/sources.list.d/tailscale.list https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list ; \
    in-target apt-get update ; \
    in-target apt-get install -y tailscale ; \
    tailscale up --authkey <key> --ssh ; 
```

### OS

Linux

### OS version

Debian Buster

### Tailscale version

1.30.0

**EDIT:** Corrected github quoting that prevented "\<key>" from being showed.

**Comment by bradfitz** [comment]
`--authkey` takes a parameter. You didn't provide one?

You probably lost stderr somewhere, but it will say:

```
flag needs an argument: -auth-key
```

... and print the USAGE help.

**Comment by DLopezJr** [comment]
My apologizes but it seems that the quoting system inside of github erased my parameter. 

"tailscale up --authkey <KEY> --ssh" is the proper formatting and what I am using.

Will also attempt to enter a shell after the failure and enter "tailscale bugreport".

**Comment by bradfitz** [comment]
Ah, I've done that too.

Any way to get the output from `tailscale up` before it exits with 127?

**Comment by DLopezJr** [comment]
Unfortunately preseeding will just provide a graphical red warning popup with only the commands you provide it and an exit code error.

The only method I've gotten to work is a cronjob that starts on reboot. I tested that in a separate preseed configuration file and that works:

```
d-i preseed/late_command string \
    mkdir -p /target/root/scripts ; \
    echo -e "#!/usr/bin/sh\n\ntailscale up --authkey <KEY> --ssh" > /target/root/scripts/ts-auth.sh ; \
    chmod +x /target/root/scripts/ts-auth.sh ; \
    echo -e "\n@reboot\troot\t/root/scripts/ts-auth.sh" >> /target/etc/crontab ; \
    wget -q -O /target/usr/share/keyrings/tailscale-archive-keyring.gpg https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg ; \
    wget -q -O /target/etc/apt/sources.list.d/tailscale.list https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list ; \
    in-target apt-get update ; \
    in-target apt-get install -y tailscale ;
```

**Comment by kurtraschke** [comment]
I'll admit to having never done a preseeded Debian installation before, so this may be completely off-base, but wouldn't  `tailscale` need to be invoked with `in-target` (same as the `apt-get` invocations in the preseed script) so it gets run in the context of the target installation (that is, `chroot`ed), not the installer itself?

In other words, try `in-target tailscale up --authkey <key> --ssh`?

**Comment by DLopezJr** [comment]
@kurtraschke Just tested `in-target tailscale up --authkey <key> --ssh `. Sadly it still fails.

**Comment by knyar** [comment]
> Unfortunately preseeding will just provide a graphical red warning popup with only the commands you provide it and an exit code error.

Note that even though installer does not provide any details except for the exit code, you can use one of the text ttys to debug: press Ctrl-Alt-F2 and you'll get a shell that can be used to examine the logs or the contents of the target partition. Ctrl-Alt-F5 returns back to the installer GUI.

In terms of running `tailscale up` from the installer, note that `tailscaled` will not actually be running after the package has been installed. So I suspect you will either need to manually start `tailscaled` before running `tailscale up`, or run `tailscale up` on the first boot after `tailscaled` has been started by systemd (your cron-based approach is one of the ways to achieve this).

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/5598#issuecomment-1272302793 lays out the options, I think the current behavior is working as intended.
