### ISSUE TITLE
FR: Opt out of client log upload

### ISSUE THREAD

**Issue by tribut** [tailscale/tailscale#5617]
### What are you trying to do?

I'm trying to disable the upload of client logs to log.tailscale.io

### How should we solve this?

Provide an option to disable remote logging

### What is the impact of not solving this?

Currently there is no way to effectively opt-out of log uploads. On https://tailscale.com/security/ you say:

> You can block [log.tailscale.io](https://tailscale.com/kb/1011/log-mesh-traffic/) on your clients to prevent logging client logs. If you do so, Tailscale may not be able to provide technical support.

However, since https://github.com/tailscale/tailscale/pull/3333 was merged, this is no longer possible using DNS. Blocking IPs is even more brittle.

**Comment by bradfitz** [comment]
What's your motivation? I can imagine several answers but you didn't specify what yours is.

**Comment by bradfitz** [comment]
@tribut, Tailscale 1.32.0 (and the next Tailscale 1.31.x unstable build) will have a `--no-logs-no-support` flag to `tailscaled` to disable log uploads. Or you can set `TS_NO_LOGS_NO_SUPPORT=true` in `/etc/defaults/tailscaled`.

I realize you didn't say what platform you're using. #5114 tracks adding a way to set flags/env for other platforms more easily.
