### ISSUE TITLE
tailscaled doesn't start under WSL; no systemd

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#562]
Several people have reported now that installing our deb packages on Ubuntu on WSL (Windows Subsystem for Linux) doesn't work because WSL doesn't have or use or start systemd, but the deb packages assume it's there.

Tracking bug for others to share their workarounds or tell us how to fix it.

**Comment by bradfitz** [comment]
Also reported:

> There is a bug with WSL2 that prevents the addition
> of your repository to Ubuntu20.04 under WSL2
>
> I had to use this command to add the repository
> 
> curl https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/tailscale.gpg
>
> and only then could I update and add tailscale to the VM

**Comment by marksteve** [comment]
Got it to run with [genie](https://github.com/arkane-systems/genie) but still can't use the tailscale address to access services within WSL2. I tried disabling the firewall but still doesn't work.

**Comment by kellytrinh** [comment]
Yet another reason to push MS to fix WSL2 networking.... Things work in WSL1 fine...

**Comment by kommserv** [comment]
Ubuntu 20.04 on WSL2, [Tailscale's instructions](https://tailscale.com/download/linux/ubuntu-2004) work fine up until `sudo tailscale up`, which returns:
```
$ sudo tailscale up
Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)
```
As others mentioned, it seems WSL2 does not use systemd. Indeed:
```
$ systemctl status tailscaled.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
Putting this here just for reference. Cheers!

**Comment by dweekly** [comment]
Also seeing this - would really love to be able to connect to my at-home beefy Windows box with a GPU running Ubuntu 20 on WSL2 via tailscale SSH.

**Comment by adonese** [comment]
I used to be able to run tailscale quite very well with wsl2, with support of genie. But recent versions of wsl2 (or tailscale) are not working with that workaround.

**Comment by bradfitz** [comment]
@dweekly, can you elaborate? Does the native Windows version of Tailscale not work for you? Or does it just not work that ssh'ing to it doesn't connect to your WSL's sshd? (so thus you're trying to run tailscaled inside WSL instead?)

When you say "tailscale SSH", you just mean "ssh over Tailscale", not the Tailscale SSH server, right?

**Comment by rqbacktrace** [comment]
I am experiencing this issue as well on WSL2

**Comment by jboelter** [comment]
I was able to get tailscale working in WSL on Ubuntu 20.04 after disabling ipv6 in the wsl environment.  I haven't dug further yet, but there's a discrepancy between what ip families the `ip` command supports and how ipv6 is enabled in the WSL setup.

From bug #831 - 
> 5.1M/28.4M wgengine.New: running "ip -6 rule add pref 5210 fwmark 0x80000 table main" failed: exit status 2
Error: Rule family not supported.

**workaround**
```
# disable ipv6; only have to do this once
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

# run the tailscale daemon
sudo tailscaled
```

**versions**
  - tailscale 1.2.10; installed via apt ([instructions](https://tailscale.com/kb/1039/install-ubuntu-2004))
  - WSL2 w/ Ubuntu 20.04 and the latest [5.4.72](https://www.catalog.update.microsoft.com/Search.aspx?q=wsl) kernel.

```
Linux hostname 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AKTheKnight** [comment]
If people are on W10 Insider, or once this is public, you should be able to add tailscaled to the WSL Startup: https://twitter.com/craigaloewen/status/1346886703261253632

**Comment by janegilring** [comment]
I'm on Windows 10 and WSL2 using Ubuntu 20.04, but can't seem to get the workaround to work:

```
jan@NUC-JR-01:/$ sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory
jan@NUC-JR-01:/$ sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl: cannot stat /proc/sys/net/ipv6/conf/default/disable_ipv6: No such file or directory
```

Does it still work for others?

**Comment by Oujiii** [comment]
Same issue as above.

**Comment by bradfitz** [comment]
@janegilring, @Oujiii, the IPv6 workaround isn't needed anymore. (as of https://github.com/tailscale/tailscale/commit/0d94fe5f692d0af3054812f9a9919544536843fa)

What is "as above" in "Same issue as above"?

That WSL doesn't use systemd so it doesn't auto-start?

**Comment by Oujiii** [comment]
The issue with the commands to disable IPv6. I think this specifically is kernel related as I have a newer WSL2 that works.

I'm still unable to start tailscale on my WSL2

```bash
:~$ sudo tailscale up
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

```bash
:~$ tailscale version
1.8.5
  tailscale commit: 118cf0cd75f92bbe3d994a5b1587c9ea3553221b
  other commit: c6fd9c9d5657e82c2d7888804ebce0e8bd6a4556
  go version: go1.16.4-ts1b677aa
```

**Comment by bradfitz** [comment]
`sudo tailscale up` doesn't start `tailscaled`; it tells an existing `tailscaled` to bring up the interface.

You have to run `tailscaled` first. Normally our Linux packages do that for you, but WSL doesn't use systemd.

**Comment by janegilring** [comment]
Thanks @bradfitz 

However, when I run tailscaled from WSL (Ubuntu 20.04), I get this:

```
logtail started
Program starting: v1.8.5-t118cf0cd7-gc6fd9c9d5, Go 1.16.4-ts1b677aa: []string{"tailscaled"}
LogID: fee30ebcb77d64b34e1ca0e4e9c23ff72b7fc54e8b16f177d37f741f4810e607
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 4.4.0-19041-Microsoft
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 279ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 7 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 8ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 34 msec
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: FATAL: Module tun not found in directory /lib/modules/4.4.0-19041-Microsoft
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 8ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 110 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 7ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 133 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 7ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 336 msec
tun module not loaded nor found on disk
wgengine.NewUserspaceEngine(tun "tailscale0") error: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
wgengine.New: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 9ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 495 msec
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available (in 7ms)
logtail: upload: log upload of 921 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/4047e41786955d18f3bec197e90fcbfc976007161a8b0fca0ca06432c3259f62": dial tcp 34.210.105.16:443: setting SO_BINDTODEVICE: protocol not available
logtail: backoff: 575 msec
```

**Comment by janegilring** [comment]
My bad, WSL wasn`t upgraded to WSL for the distro I was testing on. Looks better after upgrading:

```
logtail started
Program starting: v1.8.5-t118cf0cd7-gc6fd9c9d5, Go 1.16.4-ts1b677aa: []string{"tailscaled"}
LogID: fee30ebcb77d64b34e1ca0e4e9c23ff72b7fc54e8b16f177d37f741f4810e607
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: disabling tunneled IPv6 due to system IPv6 config: kernel doesn't support IPv6 policy routing: ip -6 rule failed: Error: Rule family not supported.
dns: [rc=unknown ret=dns.directManager]
dns: using dns.directManager
link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[172.28.215.10/20]} v4=true v6global=false}
Creating wireguard device...
Bringing wireguard device up...
external route: up
Bringing router up...
Clearing router settings...
Starting link monitor...
Starting magicsock...
Engine created.
monitor: RTM_NEWROUTE: src=, dst=ff00::/8, gw=, outif=6, table=254
monitor: RTM_NEWROUTE: src=, dst=fe80::/64, gw=, outif=6, table=254
monitor: RTM_NEWROUTE: src=, dst=fe80::8455:828c:a30a:ebd8/128, gw=, outif=6, table=254
Listening on /var/run/tailscale/tailscaled.sock
netmap packet filter: (not ready yet)
Start
using backend prefs
created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
got initial portlist info in 0s
magicsock: disco key = d:f79da6b7bf3aa803
control: HostInfo: {"IPNVersion":"1.8.5-t118cf0cd7-gc6fd9c9d5","BackendLogID":"fee30ebcb77d64b34e1ca0e4e9c23ff72b7fc54e8b16f177d37f741f4810e607","OS":"linux","OSVersion":"Ubuntu 20.04.2 LTS (Focal Fossa); kernel=5.4.72-microsoft-standard-WSL2","Hostname":"NUC-JR-01","GoArch":"amd64","Services":[{"Proto":"tcp","Port":8123}]}
Backend: logs: be:fee30ebcb77d64b34e1ca0e4e9c23ff72b7fc54e8b16f177d37f741f4810e607 fe:
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
health("overall"): error: state=NeedsLogin, wantRunning=false
wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:map[] SearchDomains:[] Hosts:map[] AuthoritativeSuffixes:[]}
dns: Resolvercfg: {Routes:map[] Hosts:map[] LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
logtail: dialed "log.tailscale.io:443" in 170ms
netmap packet filter: (not ready yet)
control: HostInfo: {"IPNVersion":"1.8.5-t118cf0cd7-gc6fd9c9d5","BackendLogID":"fee30ebcb77d64b34e1ca0e4e9c23ff72b7fc54e8b16f177d37f741f4810e607","OS":"linux","OSVersion":"Ubuntu 20.04.2 LTS (Focal Fossa); kernel=5.4.72-microsoft-standard-WSL2","Hostname":"NUC-JR-01","GoArch":"amd64"}
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:new
```

**Comment by ChamMach** [comment]
Hello, anything new for support of tailscale on WSL2 ? 

Its seems also to not work on container with WSL2 backend : 

```
logtail started
Program starting: v1.16.2-tf44911179-g3853a3b92, Go 1.17.1-ts097d1284f9: []string{"tailscaled"}
LogID: bdafe4dce4bd62d1b3212cd6354a7d3d8cb2d29a09bef46214ed5d7deae85126
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 5.10.16.3-microsoft-standard-WSL2
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: 
tun module not loaded nor found on disk
wgengine.NewUserspaceEngine(tun "tailscale0") error: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
wgengine.New: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
logtail: dialed "log.tailscale.io:443" in 211ms
```

**Comment by Oujiii** [comment]
Try `sudo tailscaled` instead at least it works for me.

**Comment by namansood** [comment]
As an alternative to running a separate terminal window just for tailscaled, this works for me: https://kumekay.com/wsl2-and-systemd/

There are a number of caveats with this approach so be sure to read systemd-genie's readme and wiki, and do this at your own risk: https://github.com/arkane-systems/genie

**Comment by swoodcoc** [comment]
A simple alternative could be to add this to your `~/.bashrc` file.
(re-login required, or `source ~/.bashrc`)

```
# Starting Tailscale daemon automatically if not running...
RUNNING=`ps aux | grep tailscaled | grep -v grep`
if [ -z "$RUNNING" ]; then
    sudo tailscaled > /dev/null 2>&1 &
    disown
fi
```

I also use this approach for starting Docker (without Docker-Desktop).

**Comment by mhlakhani** [comment]
In case this helps anyone else:

WSL2 now supports running commands on boot (https://docs.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings)

I was able to configure it to call an `/etc/init-wsl` script which among other things shells out to the script mentioned by @spwoodcock above.

The nice thing about it is that I now have my WSL configured to start up on windows boot (via docker desktop) and this ensures that tailscale gets started when my windows machine boots, without me ever having to log in to the machine. I'm not sure if that happens with the `.bashrc` solution above.

Would it be possible to have tailscale automatically "hijack" this file (preserving existing behavior if the user has a custom command) to make this seamless?

**Comment by mhlakhani** [comment]
FYI WSL2 now has systemd: https://twitter.com/craigaloewen/status/1572631931157901312?s=46&t=nsyMez4Ytv-EUTN9ZpN3iA

**Comment by sjansen1** [comment]
I just got WSL 0.70.0 on my Windows 11 machine, if you enable systemd in /etc/wsl.conf you can install and start tailscale. So far pinging other hosts works fine but ssh fails, i did look any further, maybe an issue with packet size.

**Comment by wjr1985** [comment]
Having the same problem as sjansen1 - after installing WSL 0.70.0 and enabling systemd in /etc/wsl.conf, I can't ssh to a machine on the tailscale network. I can ssh directly to that machine though, so it's definitely something with tailscale.

**Comment by mhlakhani** [comment]
@sjansen1 @wjr1985  I don't work at tailscale, but maybe the workarounds at the bottom of https://github.com/tailscale/tailscale/issues/4833 may help?

**Comment by wjr1985** [comment]
Thanks for that @mhlakhani, that fixed it!

**Comment by sjansen1** [comment]
> @sjansen1 @wjr1985 I don't work at tailscale, but maybe the workarounds at the bottom of #4833 may help? I've been able to reliably use it and disable my other workarounds since I moved over to that one.

yes "sudo ip link set dev eth0 mtu 1500" did the trick.

@mhlakhani Thank you :)

**Comment by Mandelag** [comment]
> yes "sudo ip link set dev eth0 mtu 1500" did the trick.
I have different problem, but solved using above commands. Thankyou @mhlakhani .

My use case is, 
I used magic DNS for one of my host to serve simple HTTP API (for testing) inside internal Tailscale network (connecting my development laptop with my android phone).

When my API data are small, it is running well.
But when my API data are large, it hangs. 

Besides API, I also run a web development server, (the data of course larger than API). It always hang when accessed from phone.

**Comment by DentonGentry** [comment]
`systemd` works in WSL2 now: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

I think this issue has accumulated a few distinct problems, but almost all related to considerably older version of both WSL and Tailscale and many concerning MTU size and PMTU discovery. With the [MTU size also resolved in current WSL2](https://github.com/tailscale/tailscale/issues/4833#issuecomment-1414625309), I'm going to close this.

Please open new issues for topics in current WSL2, don't reopen this one.

**Comment by sudoHub** [comment]
WSL and Tailscale

This workaround is on Ubuntu 22.04 WSL. I got WSL on my tailscale network by changing the hostname of my WSL instance.

I currently have to have a terminal open running `sudo tailscaled` and another to run `sudo tailscale up`

Change hostname
`sudo hostname NewHostName`

Close and reopen WSL terminal.

Then run: `sudo tailscaled`

Open another WSL terminal run: `sudo tailscale up`

At this point, WSL should be connected to your tailscale network.


I think in my case the hostname was the same as the hostname of my windows machine and it could not tell the difference.

Hope this helps.

**Comment by vpc-globalcitizen** [comment]
You will need to edit the [wsl.conf](https://docs.microsoft.com/windows/wsl/wsl-config#wslconf) file to ensure systemd starts up on boot.

Add these lines to the /etc/wsl.conf (note you will need to run your editor with sudo privileges, e.g: sudo nano /etc/wsl.conf):

[boot]
systemd=true

in powershell

wsl.exe -l -v
wsl.exe --shutdown

getback to wsl ubuntu and you will see tailscale is up

**Comment by kyaky** [comment]
You will need to edit the [wsl.conf](https://docs.microsoft.com/windows/wsl/wsl-config#wslconf) file to ensure systemd starts up on boot.

Add these lines to the /etc/wsl.conf (note you will need to run your editor with sudo privileges, e.g: sudo nano /etc/wsl.conf):

[boot]
systemd=true

in powershell

wsl.exe -l -v
wsl.exe --shutdown

getback to wsl ubuntu and you will see tailscale is up
