### ISSUE TITLE
Add Tailscale on SRM Synology routers (after DSM)

### ISSUE THREAD

**Issue by farika** [tailscale/tailscale#5623]
### What are you trying to do?

All vpn solution (openvpn , vpn ssl) are slow on synology routers

### How should we solve this?

Add tailscale to SRM Synology routers system. 
Tailscale is already implemented on DSM Synology NAS.

### What is the impact of not solving this?

No wireguard solution on synology routers

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/5455
