### ISSUE TITLE
'No exit nodes available' in macOS GUI when using a custom control server

### ISSUE THREAD

**Issue by nsauk** [tailscale/tailscale#5628]
### What is the issue?

I use self-hosted tailscale-compatible software ([headscale](https://github.com/juanfont/headscale)) as a control server and an official Tailscale client from the App Store as a client, and I can't choose exit node from the client's GUI, list of exit nodes available is empty.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/3472119/190027761-74035e06-46f1-4fce-a7de-84cd92a454ec.png">

At the same time, I can see the list of exit nodes available and can choose an exit node using CLI:
```bash
/Applications/Tailscale.app/Contents/MacOS/Tailscale up --login-server=https://my-headscale --exit-node=apx
```
As a result, it works great! But in GUI I can see only the chosen exit node and it shown as offline, despite it works correctly:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/3472119/190024880-f7ebb55c-1bac-4922-a83c-0cb4c382bf08.png">
In my opinion, the issue isn't related to particular third-party control server, but to macOS client only. I also use official client on Android and it displays exit node list without problems.

### Steps to reproduce

1. Install and configure headscale on a remote server (this step may be omitted, please [contact me](mailto:me@nsauk.in) if you'd like to reproduce this using my headscale instance).
2. Install a Tailscale client on macOS machine.
3. Configure the Tailscale client using .mobileprofile or a CLI command:
```bash
defaults write io.tailscale.ipn.macos ControlURL https://my-headscale
```
4. Login to control server and ensure you can see enabled exit nodes using a CLI command:
```bash
/Applications/Tailscale.app/Contents/MacOS/Tailscale status
```
5. Check the list of exit nodes in GUI.

**Actual result**
List in GUI is empty.

**Expected result**
List in GUI contains the same exit nodes as in console.

### OS

macOS

### OS version

12.5.1 (21G83)

### Tailscale version

1.30.1

### Bug report

BUG-3a0675fc2debb3c04719fa5bd6657bc482d5d84e0bb0407a35d4ffdc81686cc0-20220913230750Z-3da8a9cece99e426

**Comment by bradfitz** [comment]
I bet Headscale isn't setting the online/offline bits or something.

I don't think this is something we can help with here. The macOS client does what we want against Tailscale's control plane.

I think you should file a headscale bug.

**Comment by nsauk** [comment]
@bradfitz but Tailscale's CLI show exit nodes and Tailscale on Android also show exit nodes.

**Comment by bradfitz** [comment]
CLI is a power tool. We should make Android act like macOS. Nobody's worked on our Android client recently. The macOS graying out feature is new.

**Comment by bradfitz** [comment]
Thanks for filing https://github.com/juanfont/headscale/issues/804. I've subscribed to that. If it turns out something that Headscale is unable to fix I can jump in there to help. The quick fix is to just modify Headscale to lie in your MapResponse Peer Nodes and say that all your nodes are always connected to the control plane.
