### ISSUE TITLE
FR: install.sh add SLE Micro on SUSE Rancher

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5633]
### What are you trying to do?

SLE Micro being run on the SUSE virtualization platform Rancher is not detected by install.sh

### Anything else?

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux mh01 5.3.18-150300.59.87-default #1 SMP Thu Jul 21 14:31:28 UTC 2022 (cc90276) x86_64 x86_64 x86_64 GNU/Linux

NAME="SLE Micro"
VERSION="5.2"
VERSION_ID="5.2"
PRETTY_NAME="Harvester v1.0.3"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.2"
VARIANT="Harvester"
VARIANT_ID="Harvester-20220802"
GRUB_ENTRY_NAME="Harvester v1.0.3"

**Comment by DentonGentry** [comment]
Request was initiated from HS5116

I found sle-micro at https://www.suse.com/download/sle-micro/, which I hope is the same thing as `sle-micro-rancher`
I have to sign up for a SuSE account to download it.

However the request says VARIANT="Harvester", which looks like https://github.com/harvester/harvester

sle-micro is generally packaged as an immutable base layer in a container. I'm not sure that adding support for it in install.sh is applicable, versus making sure that one can docker-compose an sle-micro image with https://hub.docker.com/r/tailscale/tailscale

**Comment by DentonGentry** [comment]
I don't think I can reasonably test this. I put what I think will work in https://raw.githubusercontent.com/tailscale/tailscale/dgentry/sle-micro/scripts/installer.sh for someone with a functioning Harvester+SLE-Micro environment to try.

**Comment by DentonGentry** [comment]
Optimistically sent https://github.com/tailscale/tailscale/pull/8264 to commit the changes for sle-micro-rancher. We reached out to the original requestor on Feb 18 and haven't received a response, so the installer update to add `sle-micro-rancher` is untested.
