### ISSUE TITLE
Update instructions for outbound connections on Synology

### ISSUE THREAD

**Issue by brandjon** [tailscale/tailscale#5635]
The [instructions](https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections) for working around the permission issues on Synology give a recipe of commands to follow. One thing missing is that you may need to chmod 755 the /dev/net directory. See #5048. You could also mention that the current version available on Synology's package manager doesn't perform that step as part of configure-hosts.

**Comment by DentonGentry** [comment]
Correcting the permissions of /dev/net was added to `configure-host` in 1.30.0 in https://github.com/tailscale/tailscale/pull/5395

The Package Center version of the Synology package doesn't use `configure-host` as it requires root permission to add it to the Task Manager. People loading the SPKs from https://pkgs.tailscale.com/stable/ will at this point be getting a version which sets /dev/net permissions correctly.

**Comment by brandjon** [comment]
Yes, I know the underlying issue was fixed in a more recent version. I filed this issue for updating the [instructions](https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections), specifically the code snippet that includes the other shell commands:

```sh
sudo mkdir -p /dev/net
sudo mknod /dev/net/tun c 10 200
sudo chmod 0666 /dev/net/tun
```

This could mention the chmod 755 step.
