### ISSUE TITLE
FR: Netflow / Traffic Mirroring

### ISSUE THREAD

**Issue by ngrvdx** [tailscale/tailscale#5641]
### What are you trying to do?

Identify flows (not the payload itself) for devices using the Exit Node.

### How should we solve this?

Allow Exit Node to capture IP header information and dump / report into a local log directory.

### What is the impact of not solving this?

Unable to identify traffic for troubleshooting and traffic flows

**Comment by ngrvdx** [comment]
OK - Let me try to probe this. Thanks.

**Comment by DentonGentry** [comment]
If other difficulties are found after setting up https://www.ntop.org/products/netflow/nprobe/ please open new issues for them.
