### ISSUE TITLE
FR: Reliable mechanism to retain same machine name across Tailscale sidecar lifecycle

### ISSUE THREAD

**Issue by dcarrion87** [tailscale/tailscale#5643]
### What are you trying to do?

Trying to run tailscale sidecar on Kubernetes pod containing a service being provided to users.

I've been trying a combination of auth key options and cannot get to a reliable state during pod lifecycle. Ideally I can generate a key, set the node to not expire, set a hostname, and it will keep with the state being stored in the kubernetes secret. This does not seem to be the case and it just creates a new machine name if I kill it and I need to go through that process again. If I don't select a re-usable API key and I kill it just doesn't come up at all. Doesn't seem to be reading the last state from the Kubernetes secret.

I have read through this: https://tailscale.com/kb/1185/kubernetes/. Ephemeral nodes are not reliable mechanism and I don't regard the tailscale machine ephemeral. I've had scenario where nodes have come up with a suffixed name even though the pod has gone.

### How should we solve this?

Provide a reliable mechanism to allow users to pass an auth key to a sidecar and when the pod is deleted and comes back up gets the same machine name without relying on ephemeral nodes.

### What is the impact of not solving this?

Frustration working with tailscale sidecars with permanent machine names. Lot's of manual admin to fix things up.

**Comment by DentonGentry** [comment]
> Doesn't seem to be reading the last state from the Kubernetes secret.

This seems like the problem to solve, everything else described is a consequence of not having persistent state.

If you're able to run `tailscale bugreport` on one of the instances while it is alive, we can look into what is happening with its state.

**Comment by dcarrion87** [comment]
Running instance:

BUG-30772d7039907886505c1e391ffc744e9c362005bb2427cfa360bfefcc486320-20220915134912Z-d00509c14d4456c0

It looks like the tailscaled is running like this:

`tailscaled --socket=/tmp/tailscaled.sock --state=kube:coder --statedir=/tmp --tun=userspace-networking`

Should it be specifying a statedir as /tmp by default?

I can see it's adding _machinekey, _nl-node-key, _daemon in the secret but if I remove the deployment for a minute and then add it back it complains about the auth key not being valid.

**Comment by dcarrion87** [comment]
Actually I just realised when I started it the second time around it's inserted / overwrote the _machinekey and _nl-node-key that was already there in the "coder" secret.

**Comment by DentonGentry** [comment]
When tailscaled starts it usually checks its node key, and doesn't use the authkey to try to authenticate itself again. That mechanism may be broken when using a Kubernetes secret.

There are two things I could imagine are happening:
- If you start the sidecar once to let it authenticate itself, then remove the authkey from its environment (so `tailscale up` does not include a `--authkey=...` argument) it might avoid the problem you're seeing. We want to get tailscaled to fetch its state from the Secrets Manager.
- The presence of the `--statedir=/tmp` argument might be interacting poorly with `--state=kube:coder`, like maybe tailscaled looks for /tmp/tailscaled.state and decides it needs to authenticate itself. If you don't need --statedir for other reasons (like issuing certificates https://tailscale.com/blog/tls-certs/), removig that argument might change the behavior you see.

**Comment by dcarrion87** [comment]
I believe I've worked out the issue with state that was causing the keys that it was adding to the secret to be removed.

Ended up being my issue! Thanks
