### ISSUE TITLE
Modify ipn to receive and understand data plane log IDs

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#5650]
Once https://github.com/tailscale/corp/issues/6991 is done, we need to handle this on the client side.

**Comment by DentonGentry** [comment]
I imagine this is done now?

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/corp/issues/6991
