### ISSUE TITLE
Android 13: continues using DNS servers from inactive link

### ISSUE THREAD

**Issue by telotortium** [tailscale/tailscale#5659]
### What is the issue?

See title.

It worked briefly yesterday morning, but not anytime since then. I've tried on both various airport WiFis and mobile networks. 

### Steps to reproduce

Activate Tailscale. Try to connect to https://news.ycombinator.com etc

### OS

Android

### OS version

13 (TP1A.220624.021)

### Tailscale version

1.30.1-t949c40030-gda453c0f676

### Bug report

BUG-8378a67b01f1e3c45eec375f8060633f3e976b577616f30638538339b93bca50-20220916125110Z-8fa7f42cbd356f0d

**Comment by telotortium** [comment]
Chrome shows DNS_PROBE_FINISHED_BAD_CONFIG

**Comment by telotortium** [comment]
Yes, disabling Private DNS works. Is there a workaround besides disabling Private DNS (I can't dig through the whole thread in #915 on my phone)?

**Comment by DentonGentry** [comment]
PrivateDNS in automatic mode, where it tries DNS-over-TLS but falls back to UDP if it fails, does work.
Turning PrivateDNS On all the time, where you enter a hostname like dns.google, does not work.

The trouble we have:
- we'd need to issue a certificate for the little MagicDNS server inside Tailscale to use. We have a way to do that: https://tailscale.com/blog/tls-certs/, but it is an optional feature which tailnets might not have enabled.
- all certificates are public, in the Certificate Transparency Log. If we automatically create a certificate for every Android device, it would be public information how many Android devices a particular site has.

So there needs to be a more thoughtful approach with more configurability, and that will take longer to develop.

**Comment by telotortium** [comment]
That's interesting, I'm pretty sure I was using Automatic mode (but I had entered a hostname before, then decided to use automatic mode instead).

**Comment by telotortium** [comment]
BUG-8378a67b01f1e3c45eec375f8060633f3e976b577616f30638538339b93bca50-20221001031802Z-5889b2560242ed00

This is still happening to me often, especially on mobile network. I have disabled all Private DNS in the android network settings

**Comment by telotortium** [comment]
#5666 seems similar

**Comment by telotortium** [comment]
Turning "Override local DNS" on fixes the issue. So it seems like the Tailscale client continues to use the DNS servers from the WiFi network even after switching to mobile, until I deactivate Tailscale. Sometimes it works if I reactivate Tailscale immediately after deactivating it, but other times Tailscale continues to break Internet for a while.

**Comment by seowalex** [comment]
FWIW, I seem to be facing this issue as well, but on Android 12, so I'm unsure if its the same issue. Any logs I could provide to help?

**Comment by DentonGentry** [comment]
@seowalex Please file a new issue.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/5783 has more context and brainstorming about solutions.

Dup of https://github.com/tailscale/tailscale/issues/5783
