### ISSUE TITLE
FR: subnet remapping

### ISSUE THREAD

**Issue by DeedleFake** [tailscale/tailscale#5664]
### What are you trying to do?

Expose a subnet comprised of on IP block as a different IP block from the tailnet's point-of-view. In other words, the router sees the subnet that it's exposing as, for example, `10.0.0.0/24`, but I want other machines through the tailnet to see it as `10.0.1.0/24`. Ideally, this should be possible from either end so that I can access the subnet through the tailnet without stepping on any local IPs that happen to overlap.

### How should we solve this?

It probably only makes sense if the subnet masks are the same at each end so that it can simply replace some of the bits of the IP address with other ones without requiring anything too complicated. Well, I say 'simply' but I don't know for sure if this'll work as I'm imagining it.

### What is the impact of not solving this?

Let's say that I want to expose my router's config page over Tailscale. My router is at, for example, `172.16.0.1`, so I do `--advertise-routes 172.16.0.1/32` on the machine on the LAN with it, and then `--accept-routes` on, say, my laptop. I then connect my laptop to another network which _also_ has a router with an IP of `172.16.0.1`. My laptop now loses the ability to connect to the internet because it gets confused about where to send packets meant for the local network's gateway.

### Anything else?

It's possible that this is covered by some existing feature, but I haven't been able to find any info on it. If it is, then at the very least [the page on subnet routers](https://tailscale.com/kb/1019/subnets/) should be updated to explain how to do this.

It also kind of looks like this might be a more generalized case of what [4via6 subnet routing](https://tailscale.com/kb/1201/4via6-subnets/) is designed for, but I'm not 100% sure how feasible it is compared to that.

**Comment by DentonGentry** [comment]
Overlapping IPv4 addresses is the case that 4via6 routing is designed for. https://tailscale.com/kb/1201/4via6-subnets/

**Comment by DeedleFake** [comment]
Oh, you're right. That completely covers my use case. For some reason when I read the intro to that page I thought that it was for handling the case of addressing IPv4 subnets with IPv6 not for the sake of disambiguating them but rather to fix issues with networks that didn't have proper IPv6 support. I thought it was quite a bit more esoteric than what I wanted.

Thanks. I'll just close this then, I guess.

**Comment by DeedleFake** [comment]
Actually, this doesn't quite cover it 100%. Is there any way to adjust the address from the client's end, not the subnet router's?

**Comment by DentonGentry** [comment]
For 4via6 as currently defined, the subnet router decides what IPv6 route it advertises. The client just adjusts its addressing, using an IPv6 socket and sending to the 4via6prefix + IPv4 suffix.

If you can describe what the remaining issue is, we can look into it.
