### ISSUE TITLE
Broken internet connection while Tailscale is active on Android 13 (Pixel 6 Pro) with a competing VPN using the CGNAT range

### ISSUE THREAD

**Issue by KayLEvans** [tailscale/tailscale#5666]
### What is the issue?

When user turns on Tailscale on Android Pixel , internet connection (both cellular and wifi) is lost. Setting Private DNS in Android settings to automatic or off did not fix this issue, nor did disabling MagicDNS. Both the Android and Tailscale are up-to-date. User has also disable exit-node feature and connection remains broken whether in use or not.

### Are there any recent changes that introduced the issue?

Worked when using beta version of Tailscale and stopped working after installing standard version.

### OS

Android

### OS version

13

### Tailscale version

1.30.1

### Bug report

BUG-1f16e49a0eba91f0f891b7ac2c6a5c12b177da782436945466c479d4a1ac7cca-20220915003608Z-50c6759ddd534da0

**Comment by DentonGentry** [comment]
Around the time of the bug report, there is a competing IPsec=based VPN active which is also trying to use the `100.64.0.0/10` CGNAT range:

`2022-09-15 00:30:13.701613284 +0000 UTC: 27.2M/221.9M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={ipsec8:[100.82.99.x/32 2605:ef80:q:r::s:t/64] rmnet1:[2607:fb90:q:r:0:s:t:u/64] rmnet2:[2607:fc20:q:r:s:t:u:v/64] v4-rmnet1:[192.0.0.4/32] wlan0:[10.0.0.x/24]} v4=true v6=true}`

That isn't going to work.

**Comment by DentonGentry** [comment]
I don't think we can fix having two VPNs active on Android at the same time. Android VpnBuilder only allows one.

**Comment by elektrinis** [comment]
I have the same issue on Pixel 7 Pro.
Sorry I did not quite understood how to fix it from responses above. Can someone spoonfeed me?
