### ISSUE TITLE
FR: Connect to multiple tailnets at the same time.

### ISSUE THREAD

**Issue by matchcom-cahors** [tailscale/tailscale#5674]
### What are you trying to do?

I have a private tailnet that I use for backups and remote servers. For my customers, as an IT engineer, I also have a tailnets. It would be extremely convenient if I didn't have to change the account every time and just be able to connect to additional tailnets. 

### How should we solve this?

In the gui the possibility to add multiple accounts and a connect button for each account/tailnet. 

As version one of the feature it would also be cool to build the gui for the multiple accounts where you can then switch between the networks. In a second step allow the use of multiple networks at the same time.
![Screenshot](https://user-images.githubusercontent.com/113764421/190849481-bfdce3d3-04da-4757-b27f-1d843fc0d947.png)

### What is the impact of not solving this?

When I work I have to use multiple pcs/vms and I lose time.

### I love Tailscale and I look forward to every release like a child for christmas. ❤️

**Comment by DentonGentry** [comment]
> build the gui for the multiple accounts where you can then switch between the networks.

Tracked in https://github.com/tailscale/tailscale/issues/713

> In a second step allow the use of multiple networks at the same time.

Tracked in https://github.com/tailscale/tailscale/issues/183
