### ISSUE TITLE
On Windows 7, every reboot creates a new numbered network and prompts to "Set Network Location"

### ISSUE THREAD

**Issue by nyanpasu64** [tailscale/tailscale#5678]
### What is the issue?

After installing Tailscale 1.30.1 (and 1.30.2) on Windows 7 (dual-booted using GRUB with Void Linux), every time I reboot, Windows creates a new "network" type for the "Tailscale" network adapter, with sequential numbers like `Tailscale`, `Tailscale  2` (with two spaces verified using https://ramensoftware.com/textify)... now up to `Tailscale  14`, then asks me whether to mark it as Home, Work, or Public.

This does not occur on Windows 10 Ameliorated, where Tailscale doesn't even appear in Settings's connection list. I've found other people reporting this at https://www.reddit.com/r/Tailscale/comments/uo7d2f/windows_asks_if_tailscale_is_home_or_public_each/.

IIRC switching some other network drivers, and updating Tailscale from 1.30.1 to 1.30.2, *also* caused the number to increment without rebooting.

Interestingly, disabling the Tailscale adapter in "Network Connections" makes it vanish from the list. Exiting and restarting Tailscale does not help. Rebooting restores the adapter and creates a new network name as usual.

I do wonder if you're planning on dropping Windows 7 support at this point. It's understandable given the declining userbase, but still makes me sad.

### Steps to reproduce

- Install Tailscale on Windows 7.
- Reboot.

### OS

Windows

### OS version

Windows 7 x64

### Tailscale version

1.30.2

### Bug report

BUG-3b0966d5a294546e9ee887ad9ac1473f64488f05fce88e8379b11961a096b18b-20220917151228Z-2afa291ab9cd3d7e

**Comment by bradfitz** [comment]
cc @dblohm7

**Comment by nyanpasu64** [comment]
I decided to do a bit of poking to locate the bug.

The adapter is called "Tailscale Tunnel" on both Windows 7 and 10. https://github.com/tailscale/tailscale/blob/9bd9f37d295d2a91f1ef2561f67b16714dc7ac5c/net/interfaces/interfaces_windows.go tests for (but does not pass around) `const WintunInterfaceDesc = "Tailscale Tunnel"`. Where does this name get defined then?

Tailscale on Windows uses `wireguard/windows`, which go.sum says is located at `golang.zx2c4.com/wireguard/windows`. Cloning and searching that repo, `api\adapter.c` mentions `L"%s Tunnel"` and appears to manage the network device, so I decided to dig deeper there.

https://git.zx2c4.com/wireguard-nt/tree/api/adapter.c seems to special-case Windows 7 (`#if NTDDI_VERSION == NTDDI_WIN7` and `if (IsWindows7)`, `AdapterCleanupOrphanedDevices` -> `AdapterCleanupOrphanedDevicesWin7`).

## Theory

On both Windows 10 Ameliorated `BUG-2c9799e60dd0512d0eeca6b645ff24005e0a36f3d8e3a04000f3f86fdeb5477d-20220918191603Z-0d80efd71c31db1f` and Windows 7, disabling the Tailscale adapter in "Network Connections" makes it vanish from the list. I'm guessing this is caused by `AdapterCleanupOrphanedDevices` but I don't know for sure. So I'm assuming on all OSes, every reboot creates a new {"Tailscale", "Tailscale  #", "Tailscale Tunnel"} adapter from scratch.

Perhaps the bug is in `WireGuardCreateAdapter`, which branches to `CreateAdapterWin7` (lol). However I don't actually know Windows's TUN/NDIS APIs, to know why physical Ethernet adapters have a network location/profile (don't know the proper name, see https://www.tenforums.com/tutorials/6815-set-network-location-private-public-domain-windows-10-a.html) on Windows 10 but WireGuard doesn't.

Windows 7's Network and Sharing Center marks Tailscale as Ethernet, like my wired and unlike my wireless connection:

![explorer_vq7pkAbgJZ](https://user-images.githubusercontent.com/913957/190924975-b4a933d9-fc21-4044-bd0a-ecf42a972325.png)

Windows 10 hides Tailscale entirely:

![ApplicationFrameHost_hzEvpYKS6i](https://user-images.githubusercontent.com/913957/190925023-00afd84a-e5e1-45b4-96ad-15777b6d8bfa.png)

It would be understandable if Tailscale or wireguard-nt dropped Windows 7, given its declining userbase, and WireGuard having to maintain a separate codepath on Windows 7 with unique bugs. But I'm still sad to see my favorite Windows version falling behind modern APIs, when its user interface and non-user-hostile design has been abandoned by successors.

**Comment by DentonGentry** [comment]
It isn't just Wireguard support for Windows 7, Go 1.21 also plans to drop support:
- Windows 7 https://github.com/golang/go/issues/57003
- Windows 8 https://github.com/golang/go/issues/57004 

We are approaching the day when it just won't be feasible to continue providing a Windows 7 or 8 installer.

**Comment by DentonGentry** [comment]
Tailscale 1.42 is the last release which will support Windows 7: https://tailscale.com/changelog/#2023-05-24-client

At this point, I do not expect to resolve this issue.

**Comment by daliangdaliang** [comment]
thank u
