### ISSUE TITLE
Doesnt work on android 13

### ISSUE THREAD

**Issue by rightsaidfred99** [tailscale/tailscale#5683]
### What is the issue?

Says DNS can't be found and no internet connection is possible.

### Steps to reproduce

Install app
Connect
Internet doesn't work.....

### OS

Android

**Comment by bradfitz** [comment]
There's a lot of information missing from this bug that could be helpful. Foremost: which phone?

**Comment by rightsaidfred99** [comment]
It's the Synology package, I think it is also do with ipv6 but also I ended up moving it over to the raspberry pi and has been flawless.

**Comment by DentonGentry** [comment]
If the Synology was running 1.30.1 it might have been https://github.com/tailscale/tailscale/issues/5425
Glad that it is working now.
