### ISSUE TITLE
SSH permission denied on one node

### ISSUE THREAD

**Issue by sharvil** [tailscale/tailscale#5692]
### What is the issue?

I'm not able to ssh into any other machines in my tailscale network from one particular node. I get `Permission denied (tailscale)`. Others seem to be [running into the same issue](https://forum.tailscale.com/t/permission-denied-tailscale/2898). My SSH client output is essentially the same as [kgleason's](https://forum.tailscale.com/t/permission-denied-tailscale/2898/6).

I have 3 nodes, A, B, and C. All three are running with `tailscale up --ssh`. Node A is acting funny:

`A ssh to B`: permission denied
`A ssh to C`: permission denied
`B ssh to A`: ok
`B ssh to C`: ok
`C ssh to A`: ok
`C ssh to B`: ok

My ACL config is permissive:
```
	"acls": [
		// Match absolutely everything.
		// Comment this section out if you want to define specific restrictions.
		{"action": "accept", "users": ["*"], "ports": ["*:*"]},
	],
	"ssh": [
		// Allow all users to SSH into their own devices in check mode.
		// Comment this section out if you want to define specific restrictions.
		{
			"action": "accept",
			"src":    ["autogroup:members", "group:shared"],
			"dst":    ["autogroup:self", "tag:ssh-access"],
			"users":  ["autogroup:nonroot", "root"],
		},
	],
```

### Steps to reproduce

100% reproducible whenever I try to ssh from A to any other machine on my tailscale network. I've rebooted A, restarted the tailscale daemon (`tailscale down; tailscale up --ssh`), removed all ssh client keys, and made superficial changes to the ACL config to force push it to all nodes. None of those steps have helped.

### Are there any recent changes that introduced the issue?

Had a drive failure on node A and lost the tailscale machine/node keys. Replaced drive, installed Ubuntu (22.04 instead of the previous 20.04) and tailscale. Gave node A the same hostname as before, noticed that the machine was named `hostname-1` in the tailscale admin console because `hostname` was already taken. So renamed `hostname` to `hostname-old`, and `hostname-1` to `hostname`.

I should mention that I had no issues on node A before the drive failure / reinstall.

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.30.2

### Bug report

BUG-6cd915a4a7be6c7ef4cec6ed7f41e35de7b9e6423c6fd9c36f0883c27d312149-20220919185020Z-be5bd846995295f1

**Comment by DentonGentry** [comment]
The node which sent BUG-6cd915a4a7be6c7ef4cec6ed7f41e35de7b9e6423c6fd9c36f0883c27d312149-20220919185020Z-be5bd846995295f1 is tagged. Was it tagged prior to the hard drive failure as well?

**Comment by sharvil** [comment]
Yes, it was -- with the same tag.

**Comment by DentonGentry** [comment]
> Yes, it was -- with the same tag.

Given this:
```
		{
			"action": "accept",
			"src":    ["autogroup:members", "group:shared"],
			"dst":    ["autogroup:self", "tag:ssh-access"],
			"users":  ["autogroup:nonroot", "root"],
		},
```

A tagged node isn't part of `autogroup:members`, tagged nodes are not associated with a User.

**Comment by DentonGentry** [comment]
I believe the ACL described in https://github.com/tailscale/tailscale/issues/5692#issuecomment-1298447249 is the reason for this behavior.
