### ISSUE TITLE
FR: add Ubuntu flatpack for Steamdeck support

### ISSUE THREAD

**Issue by Hime0698** [tailscale/tailscale#5702]
### What are you trying to do?

Id like to install and run tailscale on my steamdeck.

### How should we solve this?

If y'all could release a flatpack version of tailscale on the plasma flatpack store on the steamdeck.

SteamOS is based on Ubuntu, but does not have apt installed and uses flatpacks.

**Comment by DentonGentry** [comment]
There is a blogpost with steps: https://tailscale.com/blog/steam-deck/

**Comment by danderson** [comment]
Yeah, unfortunately Flatpak's sandboxing means we can't ship Tailscale like that and have it work. The blog post describes how to construct a systemd OS overlay that survives Deck OS updates. I'm using it on my Deck and it works fine, though it would definitely be nice to streamline the installation more.

**Comment by DentonGentry** [comment]
Since a flatpack wouldn't be sufficient to work on the Steam Deck, closing this.
