### ISSUE TITLE
Arch: update AUR package

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#571]
https://twitter.com/tux21b/status/1285296086853341185 reports that the AUR package is out of date.

**Comment by tux21b** [comment]
Any updates on this? I really would like to test the new version and I am already considering building my own package... Btw, the Github release is also missing (it's tagged but not marked as release).

**Comment by danderson** [comment]
Done just now, both unstable and stable AUR packages. Thanks for the reminder!

Also fixed up the git releases.
