### ISSUE TITLE
Prevent attempts to both be & use an exit node at the same time.

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5710]
(I thought we had a bug about this but I can't find it)

We currently let you configure a node to both be & use an exit node, but it doesn't really work. It kinda works but differently and incompletely on different platforms.

It's not a supported configuration.

Rather than let people be disappointed later, we should fail fast early and say it's not a supported configuration.

/cc @maisem @KayLEvans @JayWStapleton @DentonGentry

**Comment by mihaip** [comment]
Duplicate of #3569?

**Comment by bradfitz** [comment]
> Duplicate of https://github.com/tailscale/tailscale/issues/3569?

There it is! Thanks. Not sure how I missed that.
