### ISSUE TITLE
Steam Login/Game doesn't work when exit node is used

### ISSUE THREAD

**Issue by amanjuman** [tailscale/tailscale#5711]
### What is the issue?

In Windows 11 Pro, I installed Steam, and it works fine when I don't use any exit node of Tailscale. Steam Community works fine, and I can chat with friends. However, when I start using any exit node, Steam Community Login doesn't work. Also, I can't be able to connect to Dota 2 server when the exit node is used. If I turn off the exit node, I can join Dota 2 competitive server. I believe CS Go also has the same issue with Tailscale.

I tried with 8 different exit nodes, each of which had the same issue. However, when I use regular WireGuard VPN of those exit node servers that case it works totally fine.

### Steps to reproduce

Open Tailscale from Taskbar > Exit Node > Select an exit Node | Allow Local Network Access (Checked)

### Are there any recent changes that introduced the issue?

No

### OS

Windows

### OS version

Windows 11 Pro

### Tailscale version

1.30.2

### Bug report

BUG-a86ce84c4cf34f69e895be52caee2cabf97e9153075d1076dd7f8798684a9770-20220921202515Z-e9585225abd3c9a7

**Comment by raggi** [comment]
Looks like an MTU issue, some steam networking code appears to assume that 1300 byte packets will flow. Tailscale currently uses an MTU of 1280.

A very temporary fix would be to run `netsh interface ipv4 set subinterface Tailscale mtu=1400` in an administrator command prompt. This will be sufficient for the games to work, but will reset whenever Tailscale reconfigures the interface.

**Comment by amanjuman** [comment]
> Looks like an MTU issue, some steam networking code appears to assume that 1300 byte packets will flow. Tailscale currently uses an MTU of 1280.
> 
> A very temporary fix would be to run `netsh interface ipv4 set subinterface Tailscale mtu=1400` in an administrator command prompt. This will be sufficient for the games to work, but will reset whenever Tailscale reconfigures the interface.

Tried that solution but it didn't work.

```
C:\Windows\system32>netsh interface ipv4 show subinterface

       MTU  MediaSenseState      Bytes In     Bytes Out  Interface
----------  ---------------  ------------  ------------  -------------
4294967295                1             0         72372  Loopback Pseudo-Interface 1
      1400                1     116634565       9330216  Tailscale
      1500                5             0             0  Wi-Fi
      1500                5             0             0  Local Area Connection* 8
      1500                5             0             0  Local Area Connection* 9
      1500                1     138715981      20871852  Ethernet
```
Not able to connect any match.

New Bugreport: `BUG-a86ce84c4cf34f69e895be52caee2cabf97e9153075d1076dd7f8798684a9770-20220922205654Z-789b99dbdb2f1e02`

**Comment by raggi** [comment]
Two changes will have affected this:

4ec6d41682c7daa1e4b983e6d02d28c5f5ba1b29
146f51ce768b9f4f002b78a26178d7896ab0d247

I believe with those two patches, this issue should be addressed - both of which are in the current stable releases. Please reopen if you can still reproduce the issue.

**Comment by Undeadhunter** [comment]
This issue still exists on Linux, when changing MTU on the tailscale0 interface from 1280 to 1400 steam features work again.

**Comment by nottheboss** [comment]
For people still having the problem that says "Ping failed" for all regions, at least on Windows, this works:

First, find your network interface name by opening PowerShell as administrator and running:

`Get-NetAdapter | Select-Object Name, InterfaceDescription`

Look for your active network connection (it might be called "Wi-Fi", "Ethernet", "Wi-Fi 2", etc.)

Then run the following commands, replacing "Wi-Fi" in the last line with your actual interface name:
```
netsh interface ipv4 set subinterface "Tailscale" mtu=1420 store=persistent
Set-NetIPInterface -InterfaceAlias "Tailscale" -AutomaticMetric Enabled
Set-NetIPInterface -InterfaceAlias "Wi-Fi" -AutomaticMetric Enabled
```

PS: My advice is to automate this by creating a .ps1 script and running it as a schedule task at logon
