### ISSUE TITLE
Log message that doesn't respect (*tsnet.Server).LogF

### ISSUE THREAD

**Issue by eric** [tailscale/tailscale#5743]
### What is the issue?

I've seen this log message in my standard logs when using `tsnet.Server` despite overriding `LogF`:

```
2022/09/24 20:07:50.906900 [unexpected] netns: DefaultRouteInterfaceIndex: ambiguous gateway interfaces found: map[24:1 27:1]
```

### Steps to reproduce

I have it happening on my local system but don't know how I'm making it happen.

### OS

macOS

### OS version

macOS 12.6

### Tailscale version

1.30.2

**Comment by bradfitz** [comment]
(for others: this is from the tailscaled-on-macOS variant, not the GUI builds)

**Comment by eric** [comment]
Found a few more messages:

```
bootstrapDNS("derp4c.tailscale.com", "134.122.77.138") for "controlplane.tailscale.com" error: Get "https://derp4c.tailscale.com/bootstrap-dns?q=controlplane.tailscale.com": dial tcp 134.122.77.138:443: connect: network is unreachable
```

```
trying bootstrapDNS("derp9c.tailscale.com", "2001:19f0:6401:fe7:5400:3ff:fe8d:6d9c") for "controlplane.tailscale.com" ...
```

```
[unexpected] netns: DefaultRouteInterfaceIndex: no gateway index found
```

**Comment by eric** [comment]
Thanks!

**Comment by eric** [comment]
I noticed we're still seeing those messages referenced in https://github.com/tailscale/tailscale/issues/5743#issuecomment-1262966680 in the standard go log.

**Comment by eric** [comment]
It appears that `tsnet` doesn't call `dnsfallback.SetLogger()`, which is required to handle those messages.

**Comment by bradfitz** [comment]
Please open a new bug. Closed bugs aren't tracked.
