### ISSUE TITLE
FR: DER

### ISSUE THREAD

**Issue by publicarray** [tailscale/tailscale#5744]
### What are you trying to do?

Use a different HTTPS (443) port for my self-hosted derper instance. In my case the port is already in use.

**Comment by DentonGentry** [comment]
You can set custom port numbers using DERPPort and STUNPort: https://tailscale.com/kb/1118/custom-derp-servers/#required-ports

If you run HTTPS on anything other than port 443, the automatic Let's Encrypt certificate support won't work and you'll need to supply certificates manually.

**Comment by publicarray** [comment]
Thanks i think i worked it out
