### ISSUE TITLE
Android cannot connect to exit node

### ISSUE THREAD

**Issue by llllllllqq** [tailscale/tailscale#5749]
### What is the issue?

After connecting to an exit node (both win & Linux exit node as server tried), all traffic died. I can't visit any website or ping my devices. 
But after disabling exit node, all works fine.
Subnet (as client) function can work well on this devices (Linux as subnet server) without turning on exit node.

### Steps to reproduce

Turn on vpn, turn on exit node and choose a server.

### Are there any recent changes that introduced the issue?

No, I've tried a fresh reinstall but it didn't help.
Meanwhile, other devices (win as client) can use exit node servers without problem.

### OS

Android

### OS version

Android12, MIUI13

### Tailscale version

1.30.2

### Bug report

BUG-668690cb86a2d54ffe8adeffb0075777d71f1b22edcb5300fd7e92052d1aa2f8-20220926102628Z-371b958f02d8acec

**Comment by DentonGentry** [comment]
Something is going wrong in reaching DNS on the exit node:
```
2022-09-26 10:26:26.498334285 +0000 UTC: 22.0M/202.9M dns udp query: Post "http://100.101.x.y:50126/dns-query": dial tcp 100.101.225.3:50126: connect: software caused connection abort
```

**Comment by Quintasan** [comment]
I can replicate this. My exit node is a Linux server running on a DigitalOcean droplet. Whenever I enable it as an exit node in the Tailscale app, all network connectivity goes down.

BUG-e3182861ba51ed076d489d8d04caf74323d6ced0fcbab0fc49053575986a361c-20221014083645Z-db64e23173ac51a6

**Comment by DentonGentry** [comment]
@Quintasan your issue has a different root cause, the mobile carrier uses CGNAT.

`2022-10-14 08:31:11.242247729 +0000 UTC: 21.1M/206.1M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={rmnet1:[100.109.x.y/32] tun0:[100.70.x.y/32 fd7a:115c:a1e0:ab12:q:r:s:t/128] wlan0:[10.101.1.191/22]} v4=true v6=false}`

The rmnet1 CGNAT address is the carrier's.

**Comment by Quintasan** [comment]
> @Quintasan your issue has a different root cause, the mobile carrier uses CGNAT.
> 
> `2022-10-14 08:31:11.242247729 +0000 UTC: 21.1M/206.1M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute= ifs={rmnet1:[100.109.x.y/32] tun0:[100.70.x.y/32 fd7a:115c:a1e0:ab12:q:r:s:t/128] wlan0:[10.101.1.191/22]} v4=true v6=false}`
> 
> The rmnet1 CGNAT address is the carrier's.

Okay, so this means I can't use an exit node over my 4G connection at all, correct?

**Comment by DentonGentry** [comment]
At this point I don't expect to diagnose what was happening last September. If it still happens please reopen the issue with a fresh bugreport.
