### ISSUE TITLE
Tailscale Win10 Client. Login does not open Browser Window after setting LoginURL

### ISSUE THREAD

**Issue by dakonga** [tailscale/tailscale#5752]
After setting a custom LoginURL in registry, the Login button in client does not open any browser window.
Nothing happend after klick on login.
(Before setting LoginURL in registry, MS Edge opens official Login Page.)
Versions tested: 1.30.2 and 1.22.2
maybe someone has the same issue?

**Comment by DentonGentry** [comment]
You deleted everything from the bug template, there is nothing we can followup on here. If you want this to be looked at, please file a new bug and provide a bugreport.
