### ISSUE TITLE
2nd hop upstream network change can break established connections. 

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5754]
### What is the issue?

If a machine is connected to a router, and that router's upstream is moved between networks, Tailscale does not get a network change event, so connections can break. 

### Steps to reproduce

unplug router from modem #1, plug in to modem #2 on a separate network.

**Comment by DentonGentry** [comment]
I would think that the next re-STUN would detect this.

**Comment by DentonGentry** [comment]
We could really use a `tailscale bugreport` from one of the nodes which is downstream of the WAN router, shortly after the failover event between their two WAN interfaces. We'd look at what STUN detected right around the time of the failover, and whether it reported the change in STUN result to the coordination server.

**Comment by DentonGentry** [comment]
ETIMEDOUT. We need some indication of what STUN was doing.
