### ISSUE TITLE
Subnet routers not showing up in Billing

### ISSUE THREAD

**Issue by sopeters** [tailscale/tailscale#5762]
### What is the issue?

We have Subnet routers that use API Keys that are

Reusable, Ephemeral, Pre-authorized

If the subnet router boots up it registers and works fine - but on the Billing page it's not counted.
If I disable and re-enable the router subnet it gets counted.

While it's good for my billing it might not be the best for Tailscale revenue :-) 

### Steps to reproduce

Setup a Subnet router that boots with API Key that is Reusable, Ephemeral, Pre-authorized
Check Billing page

### OS

Linux

### OS version

AMZ Linux 2

### Tailscale version

1.30.0 and 1.30.1

**Comment by DentonGentry** [comment]
We could look into what is happening on this tailnet and how it got into a state where the subnet router isn't being counted, but a public bug is not the right way to do that. I'm moving this to a private repo where we can put additional information, however you won't be able to see the bug any more.

**Comment by DentonGentry** [comment]
Changed my mind, not going to move this issue itself but I've opened another instead.
