### ISSUE TITLE
FR: trim exit nodes which do not have a permitted route

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5764]
### What are you trying to do?

If a machine does not have ACL access to use an exit node, the exit node should not appear in the Machines UI or in the output of `tailscale status`

### How should we solve this?

Allowing the netmap trimming to remove these devices as they would other devices with no access permitted. 

### What is the impact of not solving this?

Confusion when end users see machines they are not permitted to use.

**Comment by creachadair** [comment]
This sounds like possibly a duplicate or close relative of #1567?

**Comment by JayWStapleton** [comment]
Closing as duplicate
