### ISSUE TITLE
FR: Ability to configure client without bringing it 'up'

### ISSUE THREAD

**Issue by kpfleming** [tailscale/tailscale#5767]
### What are you trying to do?

I have Tailscale installed on a pair of border router machines, and am using HA tooling (Pacemaker) to ensure that only one node runs Tailscale at a time. This way the running instance of Tailscale can provide subnet routes efficiently (it is running on the same router that services the ISP uplink) and I do not have to use SNAT for remote client connections because I can route the LAN return traffic back to the 'active' router.

Unfortunately this means that when I want to make configuration changes to the Tailscale client (e.g. adding/removing a subnet route), I have to temporarily bring it 'up' on the standby router since `tailscale up` is the only method available to modify the configuration. Doing this causes routing confusion on my network, so I have to do it manually and during otherwise-idle times in order to avoid creating problems.

I would really like a less-obfuscated way to manage the client configuration; a simple text file containing JSON or something similar, with a documented structure, would be just fine :-) YAML, TOML, INI, or any other common format would be fine too.

### How should we solve this?

I'm not sure I can suggest anything, as I'm not familiar with the inner workings of the client software.

### What is the impact of not solving this?

I'll have to continue manually updating the Tailscale configuration my routers instead of using a configuration management tool (like Ansible). This is less-convenient in a number of ways and is error-prone (as noted in other open issues, each time a configuration change is desired `tailscale up` has to be provided the *entire* configuration).

**Comment by DentonGentry** [comment]
> each time a configuration change is desired tailscale up has to be provided the entire configuration

Related: [#2096](https://github.com/tailscale/tailscale/issues/2096)

**Comment by bradfitz** [comment]
I think `tailscale set`, done in 1.34.0 addresses this. Demo:

```
$ tailscale up
Some peers are advertising routes but --accept-routes is false
$ tailscale down
$ tailscale set --accept-routes=true
$ tailscale up
$ 
```
