### ISSUE TITLE
ssh/tailssh: SELinux makes it slightly annoying to SSH in as `root`

### ISSUE THREAD

**Issue by DilumAluthge** [tailscale/tailscale#5769]
### What is the issue?

When SELinux is in "enforcing" mode, I cannot do `ssh root@HOST`. However, `ssh -t root@HOST bash` works perfectly fine. When SELinux is in "permissive" mode, both `ssh root@HOST` and `ssh -t root@HOST bash` work fine.

### Steps to reproduce

```
me@localmachine$ ssh root@HOST
Last login: Tue Sep 27 20:09:42 from 100.xx.xxx.x
root: no shell: Permission denied
Connection to HOST closed.
me@localmachine$ ssh -t root@HOST bash
[root@HOST ~]# exit
exit
Connection to HOST closed.
```

Now go into `/etc/selinux/config` and change "enforcing" to "permissive". Then reboot the machine.

```
me@localmachine$ ssh root@HOST
Last login: Tue Sep 27 20:18:58 from 100.xx.xxx.x
[root@HOST ~]# exit
logout
Connection to HOST closed.
me@localmachine$ ssh -t root@HOST bash
[root@HOST ~]# exit
exit
Connection to HOST closed.
```

Now go into `/etc/selinux/config` and change "permissive" to "enforcing". Then reboot the machine.

```
me@localmachine$ ssh root@HOST
Last login: Tue Sep 27 20:13:33 from 100.xx.xxx.x
root: no shell: Permission denied
Connection to HOST closed.
me@localmachine$ ssh -t root@HOST bash
[root@HOST ~]# exit
exit
Connection to HOST closed.
```

### Are there any recent changes that introduced the issue?

No.

### OS

Linux

### OS version

CentOS Linux release 7.9.2009 (Core)

### Tailscale version

1.30.2

### Bug report

BUG-7d0147da63c4c4b9979e0d76216d8ea8e7b12614a546ce6dd23acaee52b267f0-20220928002135Z-e71a73441ecb530c

### Other information

```
[root@HOST ~]# tailscale --version
1.30.2
  tailscale commit: 24c524c7853b15ca4b33d085e6c5253bd4cd508e
  other commit: c399ae6fad6583b332f17e081f40667c055e9149
  go version: go1.19.1-tsb13188dd36
```

**Comment by bradfitz** [comment]
Dup of #4908 probably?

**Comment by DilumAluthge** [comment]
Duplicate of #4908
