### ISSUE TITLE
FR: SSO login does create automatically the account

### ISSUE THREAD

**Issue by shyim** [tailscale/tailscale#5774]
### What are you trying to do?

I always log in with my wrong login provider as I forgot always was it Github or Google. 

So I create always A new account which I have to delete, because used wrong login method.

### How should we solve this?

Add a register screen, they looks like you don't have an account and let me decide to create one or login with another method

### What is the impact of not solving this?

- Bad DX
- Me beeing annoyed by using Tailscale always

**Comment by DentonGentry** [comment]
> So I create always A new account which I have to delete, because used wrong login method.

Could I ask why it is important to delete the account right away? It is free, it could be left unused.

**Comment by shyim** [comment]
Yea thats annoying because it's empty then.

The better thing is I bought now for that account Tailscale Pro and contacted now the support to migrate it 😂

**Comment by DentonGentry** [comment]
To set expectations: though I sympathize, i don't expect to add friction to every user signup in order to address this.

**Comment by catzkorn** [comment]
Hi,

As previously iterated, this is not something we are planning to do. I'm going to close the FR.
