### ISSUE TITLE
FR: Just a friendly note about download docs for MacOS

### ISSUE THREAD

**Issue by ryanofrivia** [tailscale/tailscale#5776]
### What are you trying to do?

https://tailscale.com/download/mac

You can also install Tailscale using the mas command

`mas install 1475387142`

### How should we solve this?

Add this into the downloads docs for MacOS

### What is the impact of not solving this?

None. Its just nice to have.

**Comment by bradfitz** [comment]
FWIW, it's documented at https://tailscale.com/kb/1065/macos-variants/ already

But maybe we can link to that KB from the download page. cc @WalterHub.

**Comment by DentonGentry** [comment]
I've moved this to a documentation repository to be addressed.
