### ISSUE TITLE
tsweb: varz aren't sorted

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5778]
Our tsweb prometheus metrics text output sorts, but it sorts before stripping the type prefix.

So if you have "counter_foo_a" and "gauge_foo_b", then "foo_a" and "foo_b" aren't next to each other as expected.

**Comment by mhlakhani** [comment]
Whoops: I was playing around with go and did not realize this would send a notification :)

Any objections if I submit a PR for this in a day or two after having looked at it with fresh eyes to make sure I understood the issue correctly?

**Comment by DentonGentry** [comment]
By all means, feel free to send a PR.

Also just so you know: github doesn't notify anyone via email or push notification in their app when a PR in a fork references an issue like this. The link appeared in this issue, but doesn't generate any active notification.

**Comment by bradfitz** [comment]
@mhlakhani, #5778 addresses structs, but not top-level expvars.

Also, #5778 looks like it adds garbage per ServeHTTP. The sorted keys should be cacheable.

The thing we still need to do is this bit:

```
var expvarDo = expvar.Do // pulled out for tests
```

The standard library maintains a sorted list of published expvars without regard to the type prefixes. We need to maintain our own sorted list.

**Comment by bradfitz** [comment]
> By garbage, I assume you're referring to this: https://github.com/tailscale/tailscale/blob/main/tsweb/tsweb.go#L669-L674 

No, that doesn't allocate. It's the slices & maps that were to sort.

I changed that to only do it once per reflect.Type in #5889
