### ISSUE TITLE
MagicDNS Errors in Windows 10

### ISSUE THREAD

**Issue by rweirtbg** [tailscale/tailscale#5784]
### What is the issue?

I started getting the following when trying to:

`tailscale ping <hostname>`

results in:

`error looking up IP of "<hostname>": lookup <hostname> on 127.0.0.53:53: server misbehaving"`

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

No

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.30.2

### Bug report

BUG-5bcb9f25068536af215714ab47b2f340657da85c5e16504071378d0d1bf04ad4-20220929051754Z-9a003960d690d480

**Comment by pilif** [comment]
probably the same as my #5773 which I have reported yesterday

**Comment by rweirtbg** [comment]
@pilif It is not related as far as I can see.

This issue can probably be closed since it appears that MagicDNS will only resolve hostnames for servers that share tags. We like this behavior.

**Comment by DentonGentry** [comment]
> This issue can probably be closed since it appears that MagicDNS will only resolve hostnames for servers that share tags.

More specifically:
- MagicDNS creates DNS names from the netmap, which is the list of all devices present on the tailnet. The coordination server sends the netmap.
- if two devices are completely blocked from each other in the ACLs, neither can connect to the other, then a feature called netmap trimming will remote them from each other's netmap. This makes them disappear from each other's MagicDNS.
