### ISSUE TITLE
MagicDNS: DNS Server frequently unconfigured on tailscale link

### ISSUE THREAD

**Issue by pvanagtmaal** [tailscale/tailscale#5792]
### What is the issue?

On our Linux server we have Tailscale running with a DNS name fetched using MagicDNS. This works fine most of the time, however, on a daily basis, the DNS Server configured for the tailscale network link is lost. To fix it, I have to:

```
$ sudo resolvectl query some-pc.tailnet-some-id.ts.net
some-pc.tailnet-some-id.net: resolve call failed: 'some-pc.tailnet-some-id.net' not found

$ sudo resolvectl dns tailscale0 100.100.100.100

$ sudo resolvectl query some-pc.tailnet-some-id.net
some-pc.tailnet-some-id.net: 100.xxx.xxx.xxx -- link: tailscale0
```

A `tailscaled` restart does always help, adding the DNS server manually to the link always helps.

### Steps to reproduce

Unknown

### OS

Linux

### OS version

Ubuntu 21.10

### Tailscale version

1.18.1

### Bug report

BUG-edde7397fd51a93792f362f06d832da93e7513630ac1f409a17a8589f5eb9564-20220930073550Z-79d34c5f53ad9e92

**Comment by bradfitz** [comment]
I imagine you have something else on your machine reconfiguring the network/DNS that isn't interacting well.

Can you share a process list?

Does that server use DHCP or how's its network configured?

**Comment by bradfitz** [comment]
cc @danderson

**Comment by pvanagtmaal** [comment]
Attached a redacted processlist. Applications with possibly sensitive information in the startup command have been removed.

It's Ubuntu, so I imagine it uses NetworkManager to manage its network. It uses a static IP in the LAN.
[processlist.log](https://github.com/tailscale/tailscale/files/9685134/processlist.log)

**Comment by bradfitz** [comment]
`wpa_supplicant` .. is this server on wifi?

**Comment by pvanagtmaal** [comment]
No, it's not. Should I disable the service?

**Comment by DentonGentry** [comment]
I doubt that `wpa_supplicant` is interfering, I know of no cases where it tries to write out /etc/resolv.conf.

However: Tailscale version 1.18.1 is from almost a year ago. We've made a number of DNS fixes since then, and none of us will really remember what was an issue a year ago. Can you update the system to 1.30.2?

**Comment by DentonGentry** [comment]
We can look into this again with a more recent Tailscale version.
