### ISSUE TITLE
Reduced speed when connected to an exit node

### ISSUE THREAD

**Issue by pmnlla** [tailscale/tailscale#5795]
### What is the issue?

While my normal network connection is around 350mbps in terms of speed, when I connect to my tailscale network and use a digitalocean droplet as an exit relay, the speeds drop down to 12mbps on a good day, according to a speed test, and usually most sites take 10-20 seconds to load (github included). 

### Steps to reproduce

1. Create a tailnet
2. Configure two devices, one running any OS and another digitalocean droplet running Rocky Linux 
3. Configure the DO droplet as an exit node through the guide on the tailscale wiki
4. Use the DO droplet as an exit node on the other machine
5. Run `tailscale status` and ensure you have a **direct connection** to the droplet
6. Enjoy reduced speeds!

- Note that speedtest-cli reports speeds of 1999mbps upload and 3800mbps download on the DO droplet

### Are there any recent changes that introduced the issue?

Not that I'm aware of

### OS

Linux

### OS version

Garuda Linux (Rolling Release)

### Tailscale version

1.30.2

### Bug report

BUG-4af46e8fb51ddb5d3df89cb8ba7fd4eb4045d65e123dfb9b501cf7a19be0f572-20220930151935Z-65be86294047aeef

**Comment by bradfitz** [comment]
Dup of #5476, #414, etc.

**Comment by pmnlla** [comment]
Sorry for the dumb question, but I'm having a bit of issue navigating #414. Is there a known solution for this? Or will I just have to wait until something else is implemented?
