### ISSUE TITLE
FR: Please add a comparison to OpenZiti in your product comparison doc

### ISSUE THREAD

**Issue by johnalotoski** [tailscale/tailscale#5797]
### What are you trying to do?

Evaluate Tailscale vs. alternative products in the same product niche to make an informed decision on the best software to meet our particular set of requirements.

### How should we solve this?

Please add [OpenZiti](https://github.com/openziti) to your comparison list here: https://tailscale.com/compare/

### What is the impact of not solving this?

More independent analysis between products to draw up our own comparison matrix for evaluation.

### Anything else?

Thank you for providing the comparison matrix -- it's very informative and quite helpful!

**Comment by ignoramous** [comment]
Also missing: netbird, netmaker, and innernet.

**Comment by DentonGentry** [comment]
Reflected this to an internal forum for consideration. I don't think a public bug tracking it is necessary.
