### ISSUE TITLE
Huge traffic increase and CPU usage starting around September 20th

### ISSUE THREAD

**Issue by faceshape** [tailscale/tailscale#5798]
### What is the issue?

Recently got hit with a large data transfer bill from AWS, while I was debugging it with `nethogs`, I noticed that some tailscaled instances on some machines are sending/receiving large amount of traffic. Not sure how to go about debugging tailscaled, but I was able to pull up some logs using journalctl and found lots of these:

> 
> Sep 30 18:42:39 fsfe-ap-south-1-6971 tailscaled[27778]: wgengine: Reconfig: [Nk/I/] changed from "discokey:6bc0f6d6c8d5b087eb5a89ea7e1ad14e9b775d5f3803c24d3d40ed6f959e4705" to "discokey:ebee>
> Sep 30 18:42:41 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:42:51 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 414 ok
> Sep 30 18:43:01 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 414 ok out
> Sep 30 18:43:08 fsfe-ap-south-1-6971 tailscaled[27778]: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:2: too many DERP packets queued; dropping
> Sep 30 18:43:11 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 414 ok out
> Sep 30 18:43:21 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 414 ok out
> Sep 30 18:43:31 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 526 ok out
> Sep 30 18:43:41 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:43:51 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 638 ok
> Sep 30 18:44:01 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:44:02 fsfe-ap-south-1-6971 tailscaled[27778]: open-conn-track: timeout opening (TCP 100.122.181.91:54670 => 100.83.209.126:4240) to node [7MwaB]; online=yes, lastRecv=9s
> Sep 30 18:44:05 fsfe-ap-south-1-6971 tailscaled[27778]: open-conn-track: timeout opening (TCP 100.122.181.91:54670 => 100.83.209.126:4240) to node [7MwaB]; online=yes, lastRecv=2s
> Sep 30 18:44:11 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:44:21 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:44:31 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 638 ok
> Sep 30 18:44:41 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 974 ok out
> Sep 30 18:44:49 fsfe-ap-south-1-6971 tailscaled[27778]: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:2: too many DERP packets queued; dropping
> Sep 30 18:44:51 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 638 ok
> Sep 30 18:45:01 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 222 ok
> Sep 30 18:45:11 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:45:16 fsfe-ap-south-1-6971 tailscaled[27778]: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:2: too many DERP packets queued; dropping
> Sep 30 18:45:21 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 414 ok
> Sep 30 18:45:31 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 1278 ok out
> Sep 30 18:45:41 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42102 > 100.122.181.91:8472} 182 ok
> Sep 30 18:45:51 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 526 ok
> Sep 30 18:46:01 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 782 ok out
> Sep 30 18:46:07 fsfe-ap-south-1-6971 tailscaled[27778]: open-conn-track: timeout opening (TCP 100.122.181.91:43868 => 100.83.209.126:4240) to node [7MwaB]; online=yes, lastRecv=8s
> Sep 30 18:46:10 fsfe-ap-south-1-6971 tailscaled[27778]: open-conn-track: timeout opening (TCP 100.122.181.91:43868 => 100.83.209.126:4240) to node [7MwaB]; online=yes, lastRecv=1s
> Sep 30 18:46:11 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50118 > 100.83.209.126:8472} 182 ok out
> Sep 30 18:46:18 fsfe-ap-south-1-6971 tailscaled[27778]: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:2: too many DERP packets queued; dropping
> Sep 30 18:46:21 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.83.209.126:42382 > 100.122.181.91:8472} 862 ok
> Sep 30 18:46:25 fsfe-ap-south-1-6971 tailscaled[27778]: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:2: too many DERP packets queued; dropping
> Sep 30 18:46:31 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 414 ok out
> Sep 30 18:46:35 fsfe-ap-south-1-6971 tailscaled[27778]: magicsock: disco: failed to send *disco.CallMeMaybe to 127.3.3.40:2: too many DERP packets queued; dropping
> Sep 30 18:46:41 fsfe-ap-south-1-6971 tailscaled[27778]: Accept: UDP{100.122.181.91:50223 > 100.83.209.126:8472} 334 ok out
> 

Not sure if this is the cause, but it seems to me that it's not able to connect to the relay servers somehow (?), is there a way of disabling that? Another thing I noticed is, I have some instances running 1.28.0 and the problematic ones are the ones with 1.30.2 (not all of them), is it possible that there was a regression or a potential mismatch between those versions? I'm updating all of the tailscale instances to latest version hoping it would solve the issue, but still curious.

And I see ~100% CPU usage coming from tailscaled on some instances running both the older version or newer version.
Thanks!

### Are there any recent changes that introduced the issue?

It started around September 19-20th.
![network](https://user-images.githubusercontent.com/55064770/193337616-71514990-2aaf-4a44-850f-b3913fe108f8.jpg)

### OS

Linux

### OS version

Ubuntu/AWS

### Tailscale version

1.30.2

**Comment by DentonGentry** [comment]
September 20 is roughly near the end of a changeover in the DERP servers and addition of a number of new regions, described in https://tailscale.com/blog/more-derp/

There was not a widespread change in the amount of traffic going through DERP, nor other change in fleetwide metrics. The new DERP servers are at different IP addresses than the original, if there were security group settings in AWS controlling outgoing packets.

**Comment by DentonGentry** [comment]
DERP is used to rendezvous between nodes even when they go on to find a direct path, exchanging endpoint information and relaying a call-me-maybe message telling the peer to start probing. The packets continue traversing DERP if no direct path can be found. There isn't a way to disable the use of DERP altogether.

**Comment by vysecurity** [comment]
Doesn't disabling the DERP Regions in the ACL allow you to disable DERP?

**Comment by DentonGentry** [comment]
One can disable individual regions if desired: https://tailscale.com/kb/1118/custom-derp-servers/#optional-removing-tailscales-derp-regions
I don't recommend it, but one can.

Disabling all DERP regions results in a service which doesn't work.

**Comment by DentonGentry** [comment]
Has this persisted? The timing lining up with deployment of new DERP servers is the main clue at this point.

`tailscale ping 100.x.y.z` will say whether your nodes are able to find a direct connection or go through DERP

**Comment by DentonGentry** [comment]
At this point I don't expect to diagnose what happened last September.
