### ISSUE TITLE
FR: support Gentoo building from source

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5802]
### What are you trying to do?

Tailscale could support Gentoo "The Gentoo Way": compiled from scratch, with proper dependencies

### What is the impact of not solving this?

Current binary releases do work, but are not consistent with the philosophy of the distro.

**Comment by DentonGentry** [comment]
To set expectations: we're not likely to work on this ourselves. https://github.com/tailscale/tailscale is public and contains the complete Linux client. Someone could write the configuration for Gentoo to build it from source.

**Comment by wolfwood** [comment]
you can close this. i saw some copy somewhere asking for feedback about
platforms to support, i wasn't really expecting this to become a ticket.
mostly wanted to let you know folks are using it on gentoo.

for the record the gentoo install *is* from source. i misunderstood what
was going on with the dependencies, but it's downloading a cache of all the
go modules, probably to avoid a leftpad scenario. typical system package
manager vs language package manager shenanigans.

thanks for making tailscale opensource!
