### ISSUE TITLE
Kubernetes getting started docs don't work on EKS

### ISSUE THREAD

**Issue by marccampbell** [tailscale/tailscale#5805]
### What is the issue?

It looks like the Tailscale on Kubernetes doc might be out date?

https://tailscale.com/kb/1185/kubernetes/

I'm running an EKS cluster  (created with eksctl) using K8s 1.22.

On the docs, it mentions to run `make push` to create your images. That target is not in the Makefile in the docs/k8s directory. So I assume we can just use the standard, tailscale published images?

Going on, when I get to the proxy setup (https://tailscale.com/kb/1185/kubernetes/#sample-proxy), using an existing service, the pod does not start:

```
 % kubectl get pods
NAME    READY   STATUS       RESTARTS     AGE
proxy   0/1     Init:Error   1 (2s ago)   3s
```

I checked the logs and it has:
```
sysctl: error: '-w' must be of the form name=value
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
```

I'm not sure how to proceed at this point to get tailscale to connect to an existing service in a k8s cluster.

### Steps to reproduce

Just following the proxy setup doc linked above.

### OS

Linux, macOS

### Tailscale version

unknown, this is the "latest" image

**Comment by maisem** [comment]
>So I assume we can just use the standard, tailscale published images?

yes those should work. thanks for pointing out that the docs are out of date. You can also find a version at https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md.

>sysctl: error: '-w' must be of the form name=value
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1

That is a bug, the fix is to replace the command in the `proxy.yaml` file.
```diff
-      - sysctl -w net.ipv4.ip_forward=1 -w net.ipv6.conf.all.forwarding=1
+      - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
```

I also sent #5806 to fix the file
