### ISSUE TITLE
Admin UI: Filtering returns unrelated machine

### ISSUE THREAD

**Issue by dkerwin** [tailscale/tailscale#581]
**Describe the bug**

Filtering by email address returns 1 additional machine that doesn't belong there. See screenshot for details.

**To Reproduce**
1. Go to 'Users'
2. Click on 'Account of the owner'
3. Scroll down
4. There's one machine that doesn't match the filter.

**Expected behavior**
I would expect to only see machine that match the filter.

**Screenshots**
<img width="725" alt="Screenshot 2020-07-21 at 22 43 41" src="https://user-images.githubusercontent.com/168948/88105550-64890d80-cba4-11ea-8664-0f59720f9c88.png">

**Comment by rosszurowski** [comment]
We're using a fuzzy search algorithm to match a few different properties on devices, and this seems we're being a little too loose in some of the properties. Here it's likely matching "dani**el[at]ginit.net**" with "pav**el[at]gini.net**".

Long-term, we're hoping to implement a proper filter/search system with autocomplete for things like user names. But in the meantime we shouldn't be matching names this far apart. I'll tighten that up.

**Comment by dkerwin** [comment]
That makes sense. Thank you!

**Comment by rosszurowski** [comment]
This is an older issue, but I'm closing it out since we've restricted the machine filtering to only use substring matching. This should now be addressed.
