### ISSUE TITLE
FR: Subnet setup guide for containerized installation

### ISSUE THREAD

**Issue by INPoppoRTUNE** [tailscale/tailscale#5810]
### What are you trying to do?

I successfully [installed Tailscale through Docker](https://hub.docker.com/r/tailscale/tailscale) on my system: I'm able to remotely reach the SMB folders hosted on the system.

I'd like now to transform this node into a subnet router: following [this guide](https://tailscale.com/kb/1019/subnets/) I was able to successfully reach the step 3 (commands executed through [docker exec](https://docs.docker.com/engine/reference/commandline/exec/)), approving both subnet routes, but I'm not able to reach any of my other devices locally connected. I'm not an expert in Docker networking, but I suspect it enabled the subnet router functionality only within the container space.

### How should we solve this?

Update [this guide](https://hub.docker.com/r/tailscale/tailscale) adding the instructions needed to enable the subnet router functionality or provide a ready-to-use container.

### What is the impact of not solving this?

Not solving this means I'd remain with the [Wireguard from Linuxserver](https://docs.linuxserver.io/images/docker-wireguard) install, as it can enable the subnet router functionality within a ready-to-use container.
### Anything else?

I'd like to switch from Wireguard to Tailscale for the convenience of its interface, but I need subnet router to work in order to do so. I'd prefer not to take the local installation route, as docker make managing and updating apps so much easier.

**Comment by DentonGentry** [comment]
The existing instructions do work inside a Docker container, other sites are able to do so. If you can [contact support](https://tailscale.com/contact/support/) with a `tailscale bugreport` from inside the container, we can look into why it isn't forwarding.

**Comment by DentonGentry** [comment]
We can handle this as a support ticket. We cannot handle this as a public bug.
