### ISSUE TITLE
resolvconf: Error: Command not recognized

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#583]
Seen in user logs: (Ubuntu 16.04, v0.100.0-190-g1831b07f8, a0a055f2f1e4e1ec8fa240bc96c2551c26d126645b46a9c6fb244620c654e7df)

```
2020-07-22 17:23:16.547570201 +0300 +0300: 9.2M/21.5M router: dns up: resolvconf: running /sbin/resolvconf -m 0 -x -a tailscale0.inet: resolvconf: Error: Command not recognized
Usage: resolvconf (-d IFACE|-a IFACE|-u|--enable-updates|--disable-updates|--updates-are-enabled)
```

/cc @dshynkev @danderson

**Comment by dshynkev** [comment]
Unfortunately, the resolvconf binary on Ubuntu does bear little resemblance to the one my distro uses. In particular, it does not support exclusive mode, which is a problem for us. This doesn't really come up on 18.04+, as those systems use systemd-resolved by default.

What I think we should do is:
1. Detect unsupported flags in resolvconf (the Ubuntu binary exits with code `99` on unsupported flags).
2. Only use the basic invocation (`resolvconf -a tailscale0.inet`) on Ubuntu. This result in our nameservers merely being added to the list, without the other ones going away. This is sufficient for Magic DNS to work, but leaks requests to other nameservers. This is on par with Windows, though, and better than the current state.
3. Implement something more invasive at a later point. This situation is analogous to Windows, where we also cannot ask the system to make our nameservers globally exclusive. What we might do for such cases is back up and erase nameserver information from other interfaces and disable updates in `resolvconf`. That is extremely invasive and requires our cleanup to _really_ work every time, which I'm not comfortable saying it does yet. Disabling updates also has subtleties (what if the device switches networks and old fallback nameservers become inaccessible in Magic DNS?).
