### ISSUE TITLE
Centos+WHM/Cpanel Server has no /dev/net/tun

### ISSUE THREAD

**Issue by barajasfernando** [tailscale/tailscale#5831]
Hi!  I'm trying to install Tailscale on a CentOS v7.9.2009 STANDARD vzcontainer running Cpanel/WHM Version 106.0.7.

In OTHER computers running CPanel+Centos 7, Tailscale works correctly, but when I try to start it in this server, I get this error:

[root@server:tailscale]$ sudo systemctl enable --now tailscaled
Job for tailscaled.service failed because the control process exited with error code. See "systemctl status tailscaled.service" and "journalctl -xe" for details.

If I try that (systemctl status...) I get the following:

Oct 04 13:22:14 server.afs.mx systemd[1]: Failed to start Tailscale node agent.
Oct 04 13:22:14 server.afs.mx systemd[1]: Unit tailscaled.service entered failed state.
Oct 04 13:22:14 server.afs.mx systemd[1]: tailscaled.service failed.
Oct 04 13:22:14 server.afs.mx systemd[1]: tailscaled.service holdoff time over, scheduling restart.
Oct 04 13:22:14 server.afs.mx systemd[1]: Stopped Tailscale node agent.
Oct 04 13:22:14 server.afs.mx systemd[1]: start request repeated too quickly for tailscaled.service
Oct 04 13:22:14 server.afs.mx systemd[1]: Failed to start Tailscale node agent.
Oct 04 13:22:14 server.afs.mx systemd[1]: Unit tailscaled.service entered failed state.
Oct 04 13:22:14 server.afs.mx systemd[1]: tailscaled.service failed.

What can I do or check to fix it?

Thanks!

**Comment by DentonGentry** [comment]
`journalctl -xe` is likely to print whatever error occurred, or run `/usr/sbin/tailscaled` and see what it complains about.

**Comment by barajasfernando** [comment]
OK, maybe it's a virtualization problem:

```
# /usr/sbin/tailscaled
logtail started
Program starting: v1.30.2-t24c524c78-gc399ae6fa, Go 1.19.1-tsb13188dd36: []string{"/usr/sbin/tailscaled"}
LogID: 562719e267a49d02883b840c8b2a19a8f4c0eb8f7ceb6611cc047ce662ce386e
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 3.10.0
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with:
wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
createEngine: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
```

Is there anything I can do?

**Comment by DentonGentry** [comment]
Usually you can allow the container to access /dev/net/tun of the host.

For example for an LXC in Proxmox: https://tailscale.com/kb/1130/lxc-unprivileged/

For Docker you would use: `docker run --cap-add=NET_ADMIN --cap-add=SYS_MODULE -v /dev/net/tun:/dev/net/tun ...`

**Comment by DentonGentry** [comment]
Going to assume that `docker run --cap-add=NET_ADMIN --cap-add=SYS_MODULE -v /dev/net/tun:/dev/net/tun ...` resolved it.
