### ISSUE TITLE
Duplicate command line flags clobber previous values

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#5832]
### What is the issue?

Consider the following invocations:
```
tailscale up --advertise-routes=192.168.0.192/26 --advertise-routes=172.20.0.0/16
```
and
```
tailscale up --advertise-routes=192.168.0.192/26,172.20.0.0/16
```

At face value, it appears that they should be semantically identical. However, the behavior is that the last listed `--advertise-routes` takes precedence and overwrites the previous one. At the very least, I would expect an error.

\cc @dblohm7 

### OS

Linux

**Comment by DentonGentry** [comment]
Related: https://github.com/tailscale/tailscale/issues/2096

**Comment by DentonGentry** [comment]
At this point I think the feature is met by `tailscale set`.
