### ISSUE TITLE
FR: combine multiple identity providers for log in to the same account if email address is the same

### ISSUE THREAD

**Issue by buzag** [tailscale/tailscale#5841]
### What are you trying to do?

From my desktop I use GitHub, as login. From my phone I prefer Google login. From a random server or device email/PW would be better. On each account the email address is the same. (So my Google, GitHub..etc. use the same email address.)

### How should we solve this?

It would be awsesome to log in with different identities to the same account, if they use the same email address.

### What is the impact of not solving this?

For the first time I logged in with Google, just to try out the service. Now I should have to log in on different devices with my Google account, but I don't want to expose my account. So I do not use the service on those devices.

### Anything else?

Really good job, guys! Tailscale is awseome!

**Comment by DentonGentry** [comment]
We may eventually have a way to combine logins from different IdPs into a single tailnet. This isn't coming soon, and one can accomplish something similar by using Okta as a frontend for several backend IdPs.

We're not likely to automatically associate GitHub accounts via their email addresses, for two reasons:
- We don't ask for the permission to see private email addresses on the account, we only see public emails.
- Seeing the email in GitHub isn't sufficient authentication. As just one example, I have email addresses from several prior employers in my GitHub account which worked at the time that I added them and let my account show authorship of public code I wrote while there. That doesn't mean I should be able to log into their tailnets now.

**Comment by DentonGentry** [comment]
Since this issue was filed, support for Custom OIDC providers has been added: https://tailscale.com/kb/1240/sso-custom-oidc/

One could operate their own OIDC IdP.

**Comment by catzkorn** [comment]
Hi,

This would be possible using some identity providers who we support through our Custom OIDC offering. You would have to maintain this yourself (there are hosted and self hosted options available) but you would be able to authenticate to that IDP using your chosen methods, and Tailscale would only have knowledge about the authentication provider that responds to us.

However, we are highly unlikely to support directly allowing multiple authentication providers for a singular user account so I'm going to close this issue out.

**Comment by danielo515** [comment]
This should be at least documented. I have been confused about why 90% of my tailnet was gone
