### ISSUE TITLE
Raspberry Pi Libreelec does not login after reboot

### ISSUE THREAD

**Issue by Baytro** [tailscale/tailscale#5844]
### What is the issue?

I have installed Tailscale on Libreelec manually and I don't know if it's working correctly. To install I downloaded the arm64 static binary, unpacked it and made this service to automatically start tailscale on startup:
```
[Unit]
Description=Tailscale node agent
Documentation=https://tailscale.com/kb/
Wants=network-pre.target
After=network-pre.target
StartLimitIntervalSec=0
StartLimitBurst=0

[Service]
EnvironmentFile=/storage/tailscale/tailscaled.defaults
ExecStartPre=/storage/tailscale/tailscaled --cleanup
ExecStart=/storage/tailscale/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port $PORT $FLAGS
ExecStopPost=/storage/tailscale/tailscaled --cleanup

Restart=on-failure

RuntimeDirectory=tailscale
RuntimeDirectoryMode=0777
StateDirectory=tailscale
StateDirectoryMode=0777
CacheDirectory=tailscale
CacheDirectoryMode=0777
Type=notify

[Install]
WantedBy=multi-user.target
```

Now when I try to login for the first time with `tailscale up` and authorize in the browser it is successful and there seems to be something safed to `/var/lib/tailscale/` as a new folder "files", tailscaled.state and two empty log files are created.
However, when the Pi is rebooted the service runs fine but it seems like it is unable to login as the Pi is not connected. Running `tailscale up` again needs reauthentication and the IP changes which I try to avoid because I want to use a DNS. I tried to authorize with a timeout and a reuseable key at start, this works but it is also always a new IP. What I hope is that it can behave like on a laptop where I can disconnect and connect again without reauthorization, keeping the same IP.
This is the log after rebooting:

[log.txt](https://github.com/tailscale/tailscale/files/9717796/log.txt)

### OS

Linux

### OS version

Libreelec 10.2

### Tailscale version

1.30.2

### Bug report

BUG-a42c55eaa2754c6172171faab53e660ad278bb51e7f4c1ccf001b2343be12370-20221005174348Z-499137b2ec467d14

**Comment by DentonGentry** [comment]
>What I hope is that it can behave like on a laptop where I can disconnect and connect again without reauthorization, keeping the same IP.

This means the /var/libtailscale/tailscaled.state file is being lost. The node key is stored there, which gives the device its IP address.

**Comment by nealdb** [comment]
On Libreelec the /var filesystem is read only. 
Only the /storage filesystem is persistent after reboots. 

In the ExecStart section of your systemd service file change --state=/var/lib/tailscale/tailscaled.state  to --state=/storage/tailscale/tailscaled.state  and logins will persist after reboots

**Comment by Baytro** [comment]
Thanks so much this solved the problem immediately... Good to know for future things, I thought I tried switching the place to /storage but apparently not.
