### ISSUE TITLE
magicsock test isn't using active discovery

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#586]
It should be using active discovery, so we can test our latest and greatest NAT traversal code.

Currently causes the (unsubmitted) natlab test with two actual NATs to fail.

**Comment by bradfitz** [comment]
why isn't it? DiscoKeys not plumbed enough?

**Comment by danderson** [comment]
Likely so. Finding what I think are different bugs, so stomping those first. But the natlab tests aren't causing any discovery messages to happen.

**Comment by danderson** [comment]
Okay, down to just magicsock not getting set up for success in the first place. IOW, the test needs a rewrite of the device setup so that it passes the network map to magicsock, and whatever synthetic config is needed to wireguard-go.

**Comment by danderson** [comment]
We have magicsock tests using disco now.
