### ISSUE TITLE
FR: Support for Apple Shortcuts App

### ISSUE THREAD

**Issue by DaLuggi** [tailscale/tailscale#5862]
### What are you trying to do?

I would like to create automations on my iPhone Shortcuts app that enable or disable Tailscale depending on various circumstances.

### Anything else?

It would be great to add support for the Apple Shortcuts app on the iPhone version of Tailscale:
Automations to turn the Tailscale Tunnel on and off and stuff like that.

That way, on an iPhone you could save a shortcut as a widget on the Home Screen or set up a custom automation for when the tunnel should be activated - for example based on location, and so on.
A more detailed example scenario - if you use an app as a file browser for let's say your NAS in your home network, you could set it up for example like that:

Automation triggers when app "File Explorer" gets opened:
If not connected to WIFI "HOME", then
Activate Tailscale Tunnel and connect
end if

Automation triggers when app "File Explorer" gets closed:
If Tailscale tunnel active
disconnect and stop Tailscale tunnel
end if

I think, there is a great potential there for different custom use-cases that make it much easier to use Tailscale more efficient.

**Comment by DaLuggi** [comment]
Ok, I realized that there are a few similar feature requests, so sorry for posting another one.. :P 

But it would be AWESOME! :D

**Comment by DaLuggi** [comment]
Ok, I realized that there are a few similar feature requests, so sorry for posting another one.. :P

But it would be AWESOME! :D

**Comment by bradfitz** [comment]
Dup of #2504
