### ISSUE TITLE
FR: Set exit node in tailscale cli

### ISSUE THREAD

**Issue by flatypus** [tailscale/tailscale#5863]
### What are you trying to do?

I'm trying to set the exit node in the arch linux tailscale cli, but I don't see it as a command. On the Windows widget gui, there's a 'exit node' feature, but I don't have that widget in linux.

### How should we solve this?

Please add a 'tailscale exit-node [device-name/ip]' function to the tailscale cli.

**Comment by DentonGentry** [comment]
```
$ tailscale up --help
USAGE
  up [flags]
...

FLAGS
...
  --exit-node string
        Tailscale exit node (IP or base name) for internet traffic, or empty string to not use an exit node
  --exit-node-allow-lan-access, --exit-node-allow-lan-access=false
        Allow direct access to the local network when routing traffic via an exit node (default false)
```

**Comment by flatypus** [comment]
Sorry, just checked the documentation, thank you very much.
