### ISSUE TITLE
keep login when docker container restart

### ISSUE THREAD

**Issue by styxiik** [tailscale/tailscale#5868]
### What are you trying to do?

when I reboot my linux, my tailscale in docker container can keep login status and will not register as a new device

### How should we solve this?

Improve the user information preservation of the docker file, restart the machine and container should not be a log out condition

### What is the impact of not solving this?

 I use the automatic tailscale up --authkey command will cause re-registration as a new device so I have to go to the admin panel to delete original device information and re-allow

**Comment by DentonGentry** [comment]
You need to have persistent storage for the container, mounted so that /var/lib/tailscale is persisted.

**Comment by styxiik** [comment]
> You need to have persistent storage for the container, mounted so that /var/lib/tailscale is persisted.

SO much sorry I found out my system setting /var/lib will be clear every time when reboot,  misunderstand and thank you for your great job
