### ISSUE TITLE
"true" tailscale remote socket address for clients inaccessible using userspace-networking

### ISSUE THREAD

**Issue by patrickod** [tailscale/tailscale#5870]
### What is the issue?

I'm currently developing an authentication middleware for internal web applications that uses the "localapi" `whois` method to identify the user behind a connecting Tailscale peer and enforce authn/authz requirements using that identity. This works fine on hosts using the default `tailscale0` tunnel interface such as my local Linux environment, but breaks when deployed in a container environment where `userspace-networking` must be used. In this deployment the remote IP for all TCP connections will be `127.0.0.1` preventing use of whois identification.

### Steps to reproduce

1. run tailscale on a host with `-tun userspace-networking`
2. run TCP server on this host.
3. accept inbound TCP connection from proxied Tailscale peer.
4. observe that the remote address for the connection is `127.0.0.1`

### OS

Linux

### OS version

Debian

### Tailscale version

1.31.101

**Comment by danderson** [comment]
I think we should be able to fix this. When netstack is proxying a connection in userspace mode, it knows the source ip:port for the connection, so it should be able to translate 127.0.0.0:1234 back to the correct Tailscale identity.

cc @bradfitz not sure how much plumbing is involved though.

**Comment by bradfitz** [comment]
This should already work. You need to send the `IP:port` to the whois service, not just the IP.

**Comment by DentonGentry** [comment]
Sending `IP:port` should work, please reopen if it doesn't.
