### ISSUE TITLE
Global DNS settings not cleared from systemd resolver when shutting down tailscale

### ISSUE THREAD

**Issue by taisph** [tailscale/tailscale#588]
**Describe the bug**
Shutting down tailscaled with `systemctl stop tailscaled` doesn't clear global DNS settings.

**To Reproduce**
1. Make sure tailscaled is running with DNS enabled and global DNS settings have been changed by tailscale.
2. Run `systemctl stop tailscaled`
3. Check `systemd-resolve --status`.

**Expected behavior**
Settings should be reverted to pre-tailscale changes.

**Version information:**
 - Device: desktop
 - OS: Linux
 - OS version: Ubuntu 20.04
 - Tailscale version: 0.100.0-153-gc6c838785

**Comment by danderson** [comment]
cc @dshynkev not sure what the status is for the DNS cleanup logic

**Comment by dshynkev** [comment]
DNS cleanup should work, and works on a Ubuntu 20.04 VM for me. Investigating.

**Comment by taisph** [comment]
> DNS cleanup should work, and works on a Ubuntu 20.04 VM for me. Investigating.

It seems when replacing the `resolv.conf` the contents is picked up by systemd-resolve automatically. Reverting the conf as tailscale does on shutdown does not remove the previous contents. Instead I now see the nameserver and search entries added in the systemd linked resolv.conf file (`/run/systemd/resolve/resolv.conf`).

**Comment by danderson** [comment]
Our DNS configuration logic tries quite hard to figure out which of the 3-4 different kinds of DNS setups exist (pure resolv.conf, systemd-resolved, resolvconf, ...), and tries to play nicely with the currently-active one. But regardless, every config mode we have has a cleanup that should correctly restore the previous settings on exit, so there's definitely something wrong here.

@taisph could you provide the email you use to connect to tailscale, and the name of the machine this happened on, so we can look at what happened in more detail? If you prefer to not post publicly, you can send them to support@tailscale.com or danderson@tailscale.com instead.
