### ISSUE TITLE
FR: tailscale without tailscale-ipn.exe on windows

### ISSUE THREAD

**Issue by sukidesuka** [tailscale/tailscale#5880]
### What is the issue?

I'm working to a custom VPN GUI program for my company, so I wrapped tailscale and tailscaled. It working good on Mac and Linux, but not working on Windows. 

On Windows, `tailscale up` then `tailscale ip` is normal, but `tailscale status` and `tailscale down` not working.
```
PS C:\Users\srauni> tailscale up

To authenticate, visit:

        ******************

Success.
PS C:\Users\srauni> tailscale status
# Health check:
#     - state=Stopped, wantRunning=false

Tailscale is stopped.
PS C:\Users\srauni> tailscale ip
fd7a:115c:a1e0::7
100.64.0.7
PS C:\Users\srauni> tailscale down
Tailscale was already stopped.
```

If I running `tailscale-ipn.exe`, everything will be normal.

so, how running tailscaled without `tailscale-ipn.exe`.

### Steps to reproduce

1. install tailscale
2. close gui program
3. exec tailscale on shell

### OS

Windows

### OS version

Windows 11 21H2

### Tailscale version

1.30.2

**Comment by DentonGentry** [comment]
How are you running `tailscaled`?

**Comment by sukidesuka** [comment]
> How are you running `tailscaled`?

It's running as a service after install `tailscale-setup-1.30.2-amd64.msi`, I didn't run it manually.

**Comment by sukidesuka** [comment]
> How are you running `tailscaled`?

I also self build and run `tailscaled` or `tailscaled install-system-daemon` but got same result.

**Comment by sukidesuka** [comment]
I used `tailscale up --unattended` on Windows, It's running good now :)

**Comment by timwsuqld** [comment]
@sukidesuka are you able to share a bit about how you got tailscaled running on windows without the rest of the UI etc? I'd love to be able to write a tailscaled installer that just installs the daemon, and uses an auth-key to get connected. Been having heaps of issues with the install running as a different user to the daemon etc.

**Comment by QZAiXH** [comment]
@sukidesuka Did you run tailscale-ipn.exe? I tested and found that not running tailscale-ipn.exe will produce errors
