### ISSUE TITLE
MagicDNS not working on Linux "server misbehaving"

### ISSUE THREAD

**Issue by rweirtbg** [tailscale/tailscale#5895]
### What is the issue?

MagicDNS is not working on Linux hosts. We get a "server misbehaving".

root@host:~# tailscale ping server01
error looking up IP of "server01": lookup server01 on 127.0.0.53:53: server misbehaving

### Steps to reproduce

root@host:~# tailscale ping server01
error looking up IP of "server01": lookup server01 on 127.0.0.53:53: server misbehaving

### Are there any recent changes that introduced the issue?

No

### OS version

Ubuntu 20.04

### Tailscale version

1.30.2

### Bug report

BUG-5bcb9f25068536af215714ab47b2f340657da85c5e16504071378d0d1bf04ad4-20221011162507Z-3720b42cc96ab47a

**Comment by rweirtbg** [comment]
So it would appear that this is expected behavior in Linux? MagicDNS cannot lookup hostnames for devices that do not share tags or ACLs that permit access?

**Comment by bradfitz** [comment]
Is the device visible to you in `tailscale status`? If not, MagicDNS won't have a name for it.

**Comment by DentonGentry** [comment]
- MagicDNS creates DNS names from the netmap, which is the list of all devices present on the tailnet. The coordination server sends the netmap.
- If two devices are completely blocked from each other in the ACLs, neither can connect to the other, then a feature called netmap trimming will remove them from each other's netmap. This makes them disappear from each other's MagicDNS.

**Comment by DentonGentry** [comment]
I think this is working as intended, two nodes which cannot see each other in ACLs do not have entries in each other's netmaps.
