### ISSUE TITLE
`go mod download` returns unknown revision for wireguard-go

### ISSUE THREAD

**Issue by trung** [tailscale/tailscale#59]
After cloning the repo in a non-GOPATH location, running `go mod download` returns an error:
```
go: finding github.com/tailscale/wireguard-go v0.0.0-20200211020303-f39bc8eeee1b
go: github.com/tailscale/wireguard-go@v0.0.0-20200211020303-f39bc8eeee1b: unknown revision f39bc8eeee1b
go: error loading module requirements
```
I tried both go 1.13.5 and 1.13.8 giving the same error. Commit `f39bc8eeee1b` seems to be appeared in the `wireguard-go` repo.

Not sure if i'm doing anything wrong here.

**Comment by bradfitz** [comment]
Whoops, fixed. Not sure how that happened.
