### ISSUE TITLE
FR: Historic view of machine/user activity

### ISSUE THREAD

**Issue by CouncilWise** [tailscale/tailscale#5900]
### What are you trying to do?

I'm looking to use Tailscale as a replacement for our development team at my workplace, and one key feature that looks to be holding me back is the lack of historic information about user login activity.
As a bit of background, we create software that stores a lot of sensitive data in customer databases that we host solely in Microsoft Azure, that our offices are connected to via a VPN so staff can access them. This solution works well, but lacks who is connected, and when. This also becomes an issue when staff have to work from home for whatever reason, as they then need to VPN back into our office, and then back out again to get to Azure.

Tailscale would solve this for us as we could simply run a subnet machine in Azure and solely have the routes in place for only database traffic to go over it. With that in place, I can have everyone connect to that eliminating all bottlenecks and with AAD authentication would make sure that if any staff member was to leave we could stop the network access by simply disabling their account.
In addition to this, it would help solve compliance issues in relation to gaining ISO accreditations for our company, and would make investigating data breaches (hopefully that never occur) considerably easier as all devices are connected the same way irrespective of work from home or the office.

### How should we solve this?

What would be a **substantial** benefit would be simply viewing the history of a machine &/or user account.

So when looking at a user account, you could see just a raw table view of:
- DateTime when a thing happened
- What they were doing, so for example
  |- Logged into the tailscale web portal
  |- Connected machine to the network
- From what external IP
- What was the tailscale IP (if any)

And when looking at a machine it would essentially be the same as above however without web portal log entries.

### What is the impact of not solving this?

At the moment it's stopping me from pulling the trigger of purchasing this service.
We'll be looking at going for ISO 27001 at our company shortly and one of the key things is around how staff access data and how is it logged.

**Comment by mayakacz** [comment]
> DateTime when a thing happened
> Logged into the tailscale web portal
> Connected machine to the network

I think some of this might be addressed by a feature launch we had yesterday, for Configuration audit logs.
Admin console: https://login.tailscale.com/admin/logs
Docs: https://tailscale.com/kb/1203/audit-logging/
Blog post: https://tailscale.com/blog/config-audit-logging/

> From what external IP

This isn't captured in our configuration audit logs but is likely captured by your identity provider.

**Comment by DentonGentry** [comment]
Please reopen if the [configuration audit log](https://tailscale.com/blog/config-audit-logging/) is not sufficient.
