### ISSUE TITLE
FR: Assist with creating subnet routes

### ISSUE THREAD

**Issue by CouncilWise** [tailscale/tailscale#5901]
### What are you trying to do?

We currently have a Tailscale VM running in Microsoft Azure to route all our database traffic over the tailscale network.
Luckily Microsoft lists their IP's on the internet so it was easy to add those routes into the VM in Azure and have our machines go out that path if they wanted to access any database, however, there was an issue.
As with all things Microsoft, the documentation was not completely correct, and some IP's were missing meaning that some traffic was not going over the tailscale network and our connections were failing.
The way we fixed this was by running the tool TCPview and monitoring traffic attempting to go out that was not going out via tailscale and then narrowing it down to a good handful of IP's that needed to be added to our routes.

However, each time this was done required a bunch of mucking around to change the routes on the VM.

### How should we solve this?

What would be **amazing** is one or both of the following.

- A network monitoring tool as part of the Windows client (similar to TCPview) that shows your machine's network traffic. You could then drill down to some traffic and add a route to have that traffic go via Tailscale. Fully understand this would be quite difficult to do, but my goodness would it be nice.
- A much simpler thing to do would be to add routes via the admin web interface. When the machine connects to the network it pulls down that list and applies them, instead of being set on the machine itself. This would have been exceptionally easier especially when it came to running up the tailscale container in Azure instead of a VM as every time I had to change the routes I would need to delete the container itself, and then start again.

### What is the impact of not solving this?

The impact of not having this feature is not really anything.
It would simply say that it would make things much nicer, and would give your users that feeling of "OHHhhh yeah, that's cool, how many is that!" kind of thing.

**Comment by CouncilWise** [comment]
Oh and also, looks like someone (not sure if a random person or a staff member) has created a deploy with Azure button.
https://github.com/cocallaw/azure-tailscale-aci-deploy
You might want to pop that into your docco or something, as it made things pretty easy to spin up.

**Comment by DentonGentry** [comment]
> A much simpler thing to do would be to add routes via the admin web interface.

This one is unlikely. We made the policy decision that a tailnet admin cannot add access to local routes without the participation of the person who owns the machine. This is accomplished by requiring both the CLI and the admin panel in order to add a route.

> A network monitoring tool as part of the Windows client (similar to TCPview) that shows your machine's network traffic.

It isn't built into the Tailscale client as it is enormous, but Wireshark 3.5 and later support Tailscale interfaces.
https://github.com/tailscale/tailscale/issues/1660

**Comment by DentonGentry** [comment]
> A network monitoring tool as part of the Windows client (similar to TCPview) that shows your machine's network traffic.

Tailscale 1.38.1 adds `tailscale debug capture` to assist with this.

**Comment by DentonGentry** [comment]
I believe `tailscale debug capture` in 1.38.1 implements the first requested item.

The second requested item, to add subnet routes solely from the admin panel, was discussed in https://github.com/tailscale/tailscale/issues/5901#issuecomment-1435727912
