### ISSUE TITLE
FR: Retrieve hardware identifiers as part of agent payload

### ISSUE THREAD

**Issue by corelight-louisgardner** [tailscale/tailscale#5902]
### What are you trying to do?

Have system serial number or mac addresses retrieved and sent to Tailscale as part of the agent's data payload.

### How should we solve this?

My initial suggestions would be to retrieve hardware identifiers using IOkit for macOS, WMI for Windows, and from the DMI table in linux. Then add them as another data point for host information. This data can be surfaced via the device APIs and the web interface.

### What is the impact of not solving this?

Currently we aren't doing anything to work around this; neither hostname or ip address are anywhere near unique enough to rely on for data correlation to ensure only systems with known provenance are able to connect to the tailnet. The lack of this functionality is preventing us from implementing a zero-trust style of network access system using Tailscale as the backbone.

### Anything else?

Make identifier collection optional for any folks who don't want that data being tracked by the service.

**Comment by DentonGentry** [comment]
@knyar FYI

**Comment by icio** [comment]
Hi @corelight-louisgardner, thank you for your input on this topic.

Yesterday we announced the [device posture beta](https://tailscale.com/blog/device-posture) which, among other things, includes support for collecting serial numbers from devices. These serial numbers are available through the UI and API on Enterprise plans, but they also drive our integration with Crowdstrike (also available on Free plan) where we use the serial numbers to match machines and pull `falcon:ztaScores` attributes for use in Tailscale ACLs.

The collection of this data requires enabling the feature both in the Tailnet settings and on the device, as you suggested.

More info: [Device Identity Collection](https://tailscale.com/kb/1326/device-identity)

> The lack of this functionality is preventing us from implementing a zero-trust style of network access system using Tailscale as the backbone.

Could you tell us more about what you would like to see from Tailscale for us to fully cover your zero-trust needs?

I'll leave this ticket open for you to respond. 

Paul

**Comment by knyar** [comment]
> Our plan is to set Device Approval to manual and use an internally-developed service to approve systems pulled from our company-owned inventory. 

This should work! Note that you can also keep auto approval on, and use your internally developed service to [set custom device posture attributes](https://tailscale.com/kb/1288/device-posture#set-custom-posture-attributes-via-api) for devices that are present in the inventory system. This will allow you to still provide some services over Tailscale for less trusted devices (e.g. BYOD), while restricting access to sensitive services just to the trusted ones.

If you'd like all access to be gated by the inventory system, you can use [default source posture](https://tailscale.com/kb/1288/device-posture#default-source-posture) conditions. This provides a more flexible way to manage access, and also permits connectivity _to_ untrusted devices over Tailscale, even if they don't get permitted to access anything themselves.

> I'm curious is if there are log messages for when an Unapproved device is logged into by a user account. If not, that would be a handy indicator for security detections to use.

As far as I know, a new [audit log](https://tailscale.com/kb/1203/audit-logging) entry should be written when a node gets created, even if the node has not been approved. We also have a corresponding [webhook event](https://tailscale.com/kb/1213/webhooks). I hope this helps!

**Comment by knyar** [comment]
We have implemented device identity collection as part of our initial [Device Posture release](https://tailscale.com/blog/device-posture), so barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by icio** [comment]
Closing now that we've got serial numbers and I think answered your follow-up questions, but please do reach out with any further requests.
