### ISSUE TITLE
FR: Gitlab Gitops

### ISSUE THREAD

**Issue by jonathan-wondereur** [tailscale/tailscale#5905]
### What are you trying to do?

I would like to manage my ACL using GitLab and Gitops

### How should we solve this?

Allow/create a Gitlab CI/CD Pipeline to sync ACL changes to Tailscale.

### What is the impact of not solving this?

Not being able to use Gitops for ACL auto management with Git and history.

**Comment by DentonGentry** [comment]
We should be able to do this, nothing in the Tailscale backend is tied to GitHub.

**Comment by BijanJohn** [comment]
We too would like to use this as we run a Gitlab shop and not Github, any update on if this can be pulled in?

**Comment by osocode** [comment]
We want to adopt tailscale enterprise but we have a requirement to manage config in code and we use GitLab.

**Comment by marwan-at-work** [comment]
Hi all 👋🏼 

Tailscale now publishes a GitLab Template you can use in your CI/CD pipeline. You can use the following docs as a guide: https://tailscale.com/kb/1254/gitops-acls-gitlab/

Thanks, and please report any issues you might encounter!
