### ISSUE TITLE
cmd/tsconnect: derper WebSocket frequently reconnects

### ISSUE THREAD

**Issue by mihaip** [tailscale/tailscale#5921]
SSH feel laggy due to this. [WebVM also reported disconnects every 10 seconds](https://roamresearch.com/#/app/ts-corp/page/jqbr0D-fh).

```
magicsock: [0xcf02d0] derp.Recv(derp-2): derp.Recv: failed to read: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
netcheck: running HTTP-only netcheck against 23 regions
health("overall"): error: not connected to home DERP region 2
derphttp.Client.Recv: connecting websocket to https://derp2e.tailscale.com/derp
2022/10/12 17:54:56 websocket: connected to https://derp2e.tailscale.com/derp
magicsock: derp-2 connected; connGen=53
health("overall"): ok
magicsock: [0xcf02d0] derp.Recv(derp-2): derp.Recv: failed to read: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
```

![Image](https://user-images.githubusercontent.com/513813/195641365-8e8d2a57-c2e6-4ecf-8731-2d0b42386746.png)

**Comment by bradfitz** [comment]
well that's no good. I don't remember seeing that originally when we first added websocket support to derper. But maybe I wasn't paying enough attention.

**Comment by mihaip** [comment]
I rolled back a derper to the previous version and it works as expected:
```
Version: 1.25.13-tc88506caa-g00ab1359e
Was:      1.31.71-t1ce0e558a-gcc8a7fc31
```

Most likely culprit is https://github.com/tailscale/tailscale/commit/edc90ebc612e9e68316c1c9c1b2d1ddf86079c88, but will bisect.

**Comment by mihaip** [comment]
Yep, https://github.com/tailscale/tailscale/commit/edc90ebc612e9e68316c1c9c1b2d1ddf86079c88 is almost certainly it. A derper deploy as of https://github.com/tailscale/corp/commit/c1eb6a5943e02ddcdef264fb589c28cae76a22e5 worked, but as of https://github.com/tailscale/corp/commit/9b20be265377dd72f910f7973248565c554a4e4d it did not.

**Comment by mihaip** [comment]
The material difference is that our homegrown websocket -> `net.Conn` wrapper had a no-op `SetWriteDeadline` implementation, while the one from nhooyr.io/websocket actually does something: https://github.com/nhooyr/websocket/blob/8dee580a7f74cf1713400307b4eee514b927870f/netconn.go#L150-L157

Unfortunately it's a bit buggy, in that if you set a deadline, do a write, but then don't do another (or change the deadline) before the deadline expires, the timer fires and the context is canceled. Will look into upstreaming a fix.

**Comment by mihaip** [comment]
Deployed derpers with https://github.com/tailscale/tailscale/commit/9d04ffc7823dbd5fb18d5e5e9dea462846128969, things appear to be working better.
