### ISSUE TITLE
Tailscale Windows client should save files to Downloads folder, not Desktop

### ISSUE THREAD

**Issue by BlackHoleFox** [tailscale/tailscale#5934]
### What is the issue?

The Tailscale GUI clients are reasonably consistent with where files are saved via Taildrop, except on Windows. Looking at all of them together:

| Platform OS | Save Location        |
|-------------|---------------------|
| Android      |  Downloads             |
| macOS        | ~/Downloads          |
| iOS             |  App sandbox folder (But could be a picker automatically pointing at Downloads) |
| Linux          |  [Unsupported](https://github.com/tailscale/tailscale/issues/2312) | 
| Windows    |   ~/Desktop             |

Generally the platforms that _do_ have a Downloads folder somewhere and aren't unsupported use it, but on Windows it uses the `Desktop` for one reason or another. This behavior isn't consistent with any other Windows application I've used including browsers, file transfer utils, etc.

I tried using the feature for the first time on Windows today and thought it was broken at first since I had a full screen app covering my desktop and there was no visual notification. I had expected them to be in the downloads folder, so I first checked there and only got more confused afterwards. Eventually I read the support article and found them but it remained odd imo.

I'd like to request the download location on Windows is aligned with the other similar platforms, please. I debated if this was a feature request or a bug report but the bug report seemed like it fit better. If that's wrong, sorry my bad D:

### Steps to reproduce

1. Install Tailscale on a Windows system 
2. Using another device, send it a file
3. Observe the file appear on your desktop

### OS version

Windows 10

### Tailscale version

1.32.0

**Comment by bradfitz** [comment]
I think I probably just picked Desktop arbitrarily during development to make a demo obvious but then forgot about the choice, or didn't even know Windows had Downloads.

Any objections against changing it, @dblohm7 @DentonGentry @JayWStapleton?

**Comment by DentonGentry** [comment]
I'd say to change it to Downloads.

**Comment by bradfitz** [comment]
This is done for the next release (1.34.0).

**Comment by nrtkin** [comment]
Hi, is it possible to set own specified path in the windows version for received files?
Or like in ios in own Tailscale Folder with own icon.

You install in User Context to %APPDATA% there when not exist create new Folder Tailscale with specified icon and then the User can better find all Tailescale files and can add to quickaccess in file explorer.

Maybe when some users want to sync with onedrive or something the can add the tailscale folder for sync in the onedrive app
