### ISSUE TITLE
Tailscale console indicates my macOS machine needs upgrade from 1.30.2 to 1.32.0 but App Store has no such update

### ISSUE THREAD

**Issue by ldemailly** [tailscale/tailscale#5936]
### What is the issue?

Tailscale console indicates my macOS machine needs upgrade from 1.30.2 to 1.32.0 but App Store has no such update

I expect the faq to say it happens (slow roll?) or to not have the up arrow icon on the console

### Steps to reproduce

see above

### Are there any recent changes that introduced the issue?

no

### OS

macOS

### OS version

12.6

### Tailscale version

1.30.2   tailscale commit: 24c524c7853b15ca4b33d085e6c5253bd4cd508e   other commit: c399ae6fad6583b332f17e081f40667c055e9149   go version: go1.19.1-tsb13188dd36

### Bug report

BUG-0b3e07e8182fb142f2d213f142cc2a74aaf6ec7b16ccd12fb0c2ca091b2000ef-20221014055753Z-270c4941bebeb8c2

**Comment by nmcc1212** [comment]
for me, refreshing the App Store fixed it. press on updates, then store in the menu bar, then press refresh

**Comment by DentonGentry** [comment]
We do set the App Store to a 7 day rollout, yes. 1% of machines are notified about the update on the first day, 5% on the second, and so on. However going to the specific App Store page for Tailscale is supposed to show the new version for anyone who visits, the 7 day rollout is just whether the App Store will actively prompt the user to update.

**Comment by DentonGentry** [comment]
I think this issue should be rectified by Thursday, one week from when we told the App Store to start its rollout. It should reach 100% by then.
