### ISSUE TITLE
Tailscale fails to connect, says "context deadline exceeded"

### ISSUE THREAD

**Issue by mfat** [tailscale/tailscale#5937]
### What is the issue?

I'm getting this error message on one of my linux machines:

fetch control key: Get "https://controlplane.tailscale.com/key?v=41": context deadline exceeded

### Steps to reproduce

type tailscale up

### OS

Linux

### OS version

Ubuntu 22.04

### Bug report

BUG-65d1cbcea006a19e2ee651e046fda698dea8ef97d4134064ec6d4e2dada32a79-20221014104913Z-f9699fd443261e9e

**Comment by bradfitz** [comment]
You also filed #5938 with your iPhone, suggesting there's something on your home network interfering with the traffic.

On the other bug you mentioned a "proxy server". What is this proxy you're going through?

**Comment by mfat** [comment]
This is a remote VPS and is unaffected by my wifi network and proxy server.

**Comment by bradfitz** [comment]
What do you see if you run:

```
$ tailscale debug ts2021
```

**Comment by bradfitz** [comment]
And also: `ip r show table all`.

**Comment by bradfitz** [comment]
Which VPS provider?

**Comment by mfat** [comment]
```
~# tailscale debug ts2021
00:54:00.804255 Fetching keys from https://controlplane.tailscale.com/key?v=41 ...
00:54:10.987132 Do: Get "https://controlplane.tailscale.com/key?v=41": net/http: TLS handshake timeout
Get "https://controlplane.tailscale.com/key?v=41": net/http: TLS handshake timeout
```

Also it's not a well-known vps provider.

**Comment by bradfitz** [comment]
Copying your comment from #5938 ...

> Yes I live somewhere with very restricted internet censorship and dns is heavily manipulated.

Indeed, it looks like your VPS is also blocking Tailscale.

Not sure we can do much here. Circumventing network restrictions isn't really what Tailscale does. We don't try to hide our existence from the network, only the underlying data once connected. To the extent that we bypass some network restrictions is more of a side effect and not an explicit goal.

**Comment by DentonGentry** [comment]
Looking at the devices on the tailnet:
- the machines located in the VPS have only IPv4 addresses as endpoints, and are not able to contact the coordination server
- all of the machines with IPv6 addresses in their endpoints are able to contact the coordination server
- there are two machines which have only IPv4 address and are in contact, but their IP addresses differ substantially from the VPS IPv4 addresses.

I would speculate that whatever is blocking IP connectivity might only handle IPv4. If you can establish IPv6 connectivity to the machines in the VPS somehow, such as https://tunnelbroker.net/, it might help. I can't tell that for certain from here.

**Comment by DentonGentry** [comment]
Glad to hear that it is working. We're relaying the idea to a few others who have contacted us that IPv6 may be a way to avoid being blocked.

I'll close this issue.

**Comment by waihankan** [comment]
> Looking at the devices on the tailnet:
> 
> * the machines located in the VPS have only IPv4 addresses as endpoints, and are not able to contact the coordination server
> * all of the machines with IPv6 addresses in their endpoints are able to contact the coordination server
> * there are two machines which have only IPv4 address and are in contact, but their IP addresses differ substantially from the VPS IPv4 addresses.
> 
> I would speculate that whatever is blocking IP connectivity might only handle IPv4. If you can establish IPv6 connectivity to the machines in the VPS somehow, such as https://tunnelbroker.net/, it might help. I can't tell that for certain from here.

I'm having the same issue. It can connect on PC and Android but cannot on IOS apps. It says the context deadline exceeded. Any tips to fix this?

**Comment by waihankan** [comment]
> > Looking at the devices on the tailnet:
> > 
> > * the machines located in the VPS have only IPv4 addresses as endpoints, and are not able to contact the coordination server
> > * all of the machines with IPv6 addresses in their endpoints are able to contact the coordination server
> > * there are two machines which have only IPv4 address and are in contact, but their IP addresses differ substantially from the VPS IPv4 addresses.
> > 
> > I would speculate that whatever is blocking IP connectivity might only handle IPv4. If you can establish IPv6 connectivity to the machines in the VPS somehow, such as https://tunnelbroker.net/, it might help. I can't tell that for certain from here.
> 
> I can confirm this worked. Many thanks @DentonGentry I just created an IPv6 tunnel using Tunnelbroker, configured the VPS and rebooted. Now tailscale works.

Can you explain how you did this? I am having same issue on ios apps. The government does a lot of blocking + DNS manipulation. Can you help me bypass it as well? thank you!

**Comment by acidvegas** [comment]
Issue persists for me aswell on Void linux....would be nice if someone would address this as it has been affecting users since last year....

For me, tailscale dns queries work but all non-tailscale queries fail and cause these log lines.

Anyone have a work around? Restarting tailscale does nothing to fix this for me.

What I am gathering is this likely has to do with resolvconf or something....all the normies who have systemd dont have this issue. Likely another classioc case of developers expecting a systemd based system and not realizing NOT EVERYONE USES SYSTEMD Lol...incus has had issues just like this and many other packages.

Just spit ballin my theory to help. No offense here.

fwiw im on a residential home ip having the same issues. I HIGHLY doubt the VPS provider was blocking tailscale lol....

**Comment by mrsaraiva** [comment]
The problem here is the UX. All the errors in this issue have the same underlying cause: Tailscale not being able to reach the control plane. This should be informed to the user in the UI instead of buried in the console logs on macOS. The user will know straight away that there's a network issue, instead of being unaware of the real cause.
