### ISSUE TITLE
Container image for v1.32.0 was not published

### ISSUE THREAD

**Issue by dghubble** [tailscale/tailscale#5941]
### What is the issue?

Tailscale [v1.32.0](https://github.com/tailscale/tailscale/releases/tag/v1.32.0) release doesn't have a corresponding container image published. https://hub.docker.com/r/tailscale/tailscale/tags?page=1&name=1.32 (empty as of this writing).

### Tailscale version

v1.32.0

**Comment by dghubble** [comment]
Alright, I'll sit tight. Fwiw, when a Tailscale release is created, that starts our infra automations to keep things updated.

**Comment by DentonGentry** [comment]
The 1.32 container image is published now.

**Comment by CrushTide** [comment]
> The release process is still underway: the iOS app is in review, the Synology release is not out yet, and we have not built the container image.
Synology release is still not out

**Comment by DentonGentry** [comment]
1.32.0 DSM7 in /dev/net/tun mode is not passing one of the tests, we're working on it.

**Comment by CrushTide** [comment]
> 1.32.0 DSM7 in /dev/net/tun mode is not passing one of the tests, we're working on it.

thx
