### ISSUE TITLE
FR: ACL tests for non-user objects

### ISSUE THREAD

**Issue by bobbyl140** [tailscale/tailscale#5954]
### What are you trying to do?

As mentioned at the bottom of #3673, I am just now realizing upon trying to write a test against a tag that it is currently impossible. 

### How should we solve this?

Allow tags (and probably also groups/autogroups and hosts) in ACL tests, instead of just users.

### What is the impact of not solving this?

I have a tag for isolated devices that should have access into them allowed, but very restricted allowances for outgoing connections. I was hoping to write a test to ensure these devices don't accidentally gain access to the rest of my Tailnet. 

### Anything else?

If this is not a planned feature or implementing it is low priority, that's understandable, I simply wanted to get it on the table after encountering the other issue. Thank you!

**Comment by mayakacz** [comment]
I believe ACL tests for tags, groups, and hosts work today. ACL tests currently support: users, groups, tags, and hosts.
ACL tests do not currently support autogroups.

**Comment by bobbyl140** [comment]
Hmm, strange. It kept saying that “tag:isolated” was an invalid user. When I get a chance I will try again.

**Comment by bobbyl140** [comment]
Nope. Still giving the error. 
> Error: test(s) failed
test(s) failed for user: tag:isolated
user is invalid

**Comment by grelland** [comment]
Also struggling with this: ACL tests don't work when providing a tag as the `src`, getting result:
```json
    {
      "user": "tag:some-tag",
      "errors": [
        "user is invalid"
      ]
    },
```

**Comment by grelland** [comment]
👋 Any updates?

**Comment by DentonGentry** [comment]
I promise we will update the bug when there is news to report.

**Comment by maisem** [comment]
I just verified and tags, groups and hosts work in tests.
```json
{
	"tests": [
		{
			"src":    "tag:some-tag",
			"accept": ["1.1.1.1:80"],
		},
		{
			"src":    "some-host",
			"accept": ["1.1.1.1:80"],
		},
		{
			"src":    "group:some-group",
			"accept": ["1.1.1.1:80"],
		},
	],
	"groups": {
		"group:some-group": ["maisem@github"],
	},
	"hosts": {
		"some-host": "1.2.3.4",
	},
	"tagOwners": {
		"tag:some-tag": ["maisem@github"],
	},
	"acls": [
		{
			"action": "accept",
			"users":  ["group:some-group", "tag:some-tag", "some-host"],
			"ports":  ["1.1.1.1:80"],
		},
	],
}
```

If it is not working for you please feel free to reopen with a sample ACL.

**Comment by grelland** [comment]
Still not working - so please re-open this issue. 

Here's a sample ACL that mirrors what I'm trying to do:
```json
{
  "hosts": {
    "foo": "10.10.10.10/15",
    "bar": "12.12.12.12"
  },
  "groups": {
    "group:a": ["test@example.org"]
  },
  "tagOwners": {
    "tag:f": ["group:a"],
    "tag:b": ["group:a"]
  },
  "acls": [
    {
      "action": "accept",
      "src": ["group:a"],
      "dst": ["foo:*"]
    },
    {
      "action": "accept",
      "src": ["tag:f"],
      "dst": ["foo:*"]
    },
    {
      "action": "accept",
      "src": ["tag:f"],
      "dst": ["bar:*"]
    },
    {
      "action": "accept",
      "src": ["tag:f"],
      "dst": ["tag:b:*"]
    }
  ],
  "tests": [
    {
      "src": "group:a",
      "accept": ["foo:22"]
    },
    {
      "src": "group:a",
      "accept": ["10.10.10.10:22"]
    },
    {
      "src": "group:a",
      "accept": ["10.10.10.10/15:22"]
    },
    {
      "src": "tag:f",
      "accept": ["bar:22"]
    },
    {
      "src": "tag:f",
      "accept": ["tag:b:443"]
    }
  ]
}
```

Output
```
Error: test(s) failed

test(s) failed for user: group:a
    [acl test error]: user or host is invalid: unknown user or host: "foo"

test(s) failed for user: group:a
    [acl test error]: user or host is invalid: unknown user or host: "10.10.10.10/15"
```

Seems like it fails whenever the host is given as CIDR notation, but works otherwise.

**Comment by DentonGentry** [comment]
CIDR ranges aren't expected to work: https://tailscale.com/kb/1018/acls/#tests

A test evaluates an ACL as though a packet were arriving, a packet cannot arrive at 10.10.10.10/15. One could construct the test for 10.10.10.10, or 10.10.128.1, or some random IP within the range.

**Comment by grelland** [comment]
Right. That does make sense, thanks for clearing it up!

When I know what to look for I suppose it's reflected in the docs too:
> The src field specifies the user identity being tested, which can be a [user’s email address](https://tailscale.com/kb/1018/acls/#users), a [group](https://tailscale.com/kb/1018/acls/#groups), an [ACL tag](https://tailscale.com/kb/1068/acl-tags/), or a [host](https://tailscale.com/kb/1018/acls/#hosts) **that maps to an IP address**.

Regardless I think it'd be a good idea to make that a little clearer, as the docs also list to a definition of `host` that is exemplified by a CIDR range. :)
