### ISSUE TITLE
Official stance on Terraform provider vs Github Actions GitOps mechanism

### ISSUE THREAD

**Issue by dcarrion87** [tailscale/tailscale#5955]
I noticed that the Terraform provider is now officially under the Tailscale org. 

We have had mixed success with the [existing GitOps process described here](https://tailscale.com/kb/1204/gitops-acls/) and managing the JSONL format directly is a bit of a pain.

Wondering if we should switch over to the Terraform provider for managing ACLs: https://registry.terraform.io/providers/tailscale/tailscale/latest/docs/resources/acl

Can we expect the current GitOps process using `tailscale/gitops-acl-action@v1` to be deprecated in favour of Terraform?

**Comment by bradfitz** [comment]
Neither is deprecated. People have different preferences.

**Comment by DentonGentry** [comment]
>We have had mixed success with the [existing GitOps process described here](https://tailscale.com/kb/1204/gitops-acls/)

If you can file issues about things which can be improved, we can try to make the GitOps experience better.

As Brad says though, we have no intention of deprecating either GitOps or Terraform and intend to keep supporting and extending both. I'll close this issue.
