### ISSUE TITLE
panic when connecting to tailscale ssh using nautilus (sftp)

### ISSUE THREAD

**Issue by mkhl** [tailscale/tailscale#5957]
### What is the issue?

tailscale panics and restarts

from the log:
```
panic: dup idH

goroutine 12265 [running]:
tailscale.com/ssh/tailssh.(*server).startSession(0xc0001140f0, 0xc000698370)
	/home/buildozer/aports/community/tailscale/src/src/github.com/tailscale/tailscale/ssh/tailssh/tailssh.go:730 +0x258
tailscale.com/ssh/tailssh.(*sshSession).run(0xc000698370)
	/home/buildozer/aports/community/tailscale/src/src/github.com/tailscale/tailscale/ssh/tailssh/tailssh.go:806 +0x4c
tailscale.com/ssh/tailssh.(*conn).handleConnPostSSHAuth(0xc000113200, {0xe81668, 0xc0002e88f0})
	/home/buildozer/aports/community/tailscale/src/src/github.com/tailscale/tailscale/ssh/tailssh/tailssh.go:513 +0x3a5
tailscale.com/tempfork/gliderlabs/ssh.(*session).handleRequests.func2()
	/home/buildozer/aports/community/tailscale/src/src/github.com/tailscale/tailscale/tempfork/gliderlabs/ssh/session.go:308 +0x2d
created by tailscale.com/tempfork/gliderlabs/ssh.(*session).handleRequests
	/home/buildozer/aports/community/tailscale/src/src/github.com/tailscale/tailscale/tempfork/gliderlabs/ssh/session.go:307 +0xc73
```

### Steps to reproduce

* enable tailscale ssh
* from another host, use nautilus (the gnome file browser) to connect via sftp

### OS

Linux

### OS version

Alpine Linux 3.16.2

### Tailscale version

1.24.2 

### Bug report

BUG-d915709bacee676b8823b7c885aab5bd941e94fd94edb4f9e8d2e94a1b7cf665-20221016135622Z-003b35e527caad17

**Comment by DentonGentry** [comment]
Tailscale version 1.24.2 does contain the beginnings of the SSH feature, but substantial work on it has been done since then. I don't immediately recognize this backtrace, but is it possible to update to Tailscale 1.32 to try it?

**Comment by mkhl** [comment]
the most recent alpine package is 1.30.2, i could try that if it helps (and when i remember how to update a package from edge)?

**Comment by mkhl** [comment]
it just works in 1.30.2

sorry for the noise!
