### ISSUE TITLE
High CPU consumption on Raspberry Pi 1B even while idle

### ISSUE THREAD

**Issue by lutfor-diu** [tailscale/tailscale#5958]
[cpu.out.txt](https://github.com/tailscale/tailscale/files/9801639/cpu.out.txt)
[cpu.out.txt](https://github.com/tailscale/tailscale/files/9801644/cpu.out.txt)
### What is the issue?

Resources hungry! Usage lots of cpu in ideal mode on raspberry pi. Please update it and make it more light

### Steps to reproduce

When using it raspberry pi 1b it consume 20% of cpu when in tailscale ideal mode. 

### Are there any recent changes that introduced the issue?

Yes, after recent update

### OS

Linux

### OS version

Bullsey

### Tailscale version

Tailscale latest version

**Comment by bradfitz** [comment]
Without a bug report or profile or even version number there's little we can do here.

"Tailscale latest version" doesn't age well in bug reports.

**Comment by DentonGentry** [comment]
- Is the Raspberry Pi being used as an exit node?
- Can you run "tailscale bugreport" on the Raspberry Pi during a time when its CPU is 20% and paste it here?

**Comment by unnatural** [comment]
> Without a bug report or profile or even version number there's little we can do here.
> 
> "Tailscale latest version" doesn't age well in bug reports.

1.32.0

**Comment by unnatural** [comment]
![IMG_20221016_211105](https://user-images.githubusercontent.com/32225836/196043241-865b7013-cf77-4379-a50d-84b5d0b4e36c.jpg)

**Comment by DentonGentry** [comment]
Please run "tailscale bugreport" on the Raspberry Pi and paste it here.
A screenshot of the top output doesn't really help.

**Comment by unnatural** [comment]
> Please run "tailscale bugreport" on the Raspberry Pi and paste it here. A screenshot of the top output doesn't really help.

Ok brother, previous tailscaled just consume 4-8% when in use.

**Comment by unnatural** [comment]
root@DietPi:~# tailscale bugreport
BUG-2403f7f1b20fb1122c0ad05d6540ac4d0a45782d8ba3aa9c107d7bf0c0420d45-20221016152223Z-ebb88c91ca253a25

**Comment by DentonGentry** [comment]
On the Raspberry Pi can you run:
tailscale debug -cpu-profile=/tmp/cpu.out --profile-seconds=60

and attach the /tmp/cpu.out file here?

**Comment by bradfitz** [comment]
I see no smoking gun.

I do see a lot of DNS errors, though. And on start it complains that systemd-resolved isn't configured correctly:

> 2022-10-15 10:17:28.018534 +0000 UTC: dns: resolvedIsActuallyResolver error: resolv.conf doesn't point to systemd-resolved; points to [192.168.31.2]

So that's not great, but shouldn't be consuming lots of CPU.

I'd also be interested in seeing that CPU profile.

**Comment by unnatural** [comment]
> I see no smoking gun.
> 
> I do see a lot of DNS errors, though. And on start it complains that systemd-resolved isn't configured correctly:
> 
> > 2022-10-15 10:17:28.018534 +0000 UTC: dns: resolvedIsActuallyResolver error: resolv.conf doesn't point to systemd-resolved; points to [192.168.31.2]
> 
> So that's not great, but shouldn't be consuming lots of CPU.
> 
> I'd also be interested in seeing that CPU profile.

Don't know why but after latest android update it seems cpu usage decrease a bit. I have attached the cpu. Out file.  See the first report

**Comment by bradfitz** [comment]
Where's the CPU profile? I see no attachment here.

**Comment by DentonGentry** [comment]
There are two cpu.out.txt links edited into the original report, the first comment.

**Comment by DentonGentry** [comment]
The two profile files appear to be the same. pprof output:

[cpu.pdf](https://github.com/tailscale/tailscale/files/9805003/cpu.pdf)

**Comment by unnatural** [comment]
> The two profile files appear to be the same. pprof output:
> 
> [cpu.pdf](https://github.com/tailscale/tailscale/files/9805003/cpu.pdf)

Yes, same.

**Comment by bradfitz** [comment]
I guess portlist.GetList could use another round of garbage reductions:

```
bradfitz@tsdev:~/src/tailscale.com/portlist$ go test -v -run=XXX -bench=GetList
goos: linux
goarch: amd64
pkg: tailscale.com/portlist
cpu: Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz
BenchmarkGetList
BenchmarkGetList-8           121           9770540 ns/op           99821 B/op       3062 allocs/op
PASS
ok      tailscale.com/portlist  2.187s
```

**Comment by bradfitz** [comment]
cc @andrew-d for the interface enumeration bit in netcheck

**Comment by lutfor-diu** [comment]
After recent 1.3.2 update cpu usage high again.

**Comment by DentonGentry** [comment]
The work done on portList earlier in the bug is not in 1.32.x, it will be in 1.34.
If 1.30 was working well for your purposes you can go back to it until then:
`apt install tailscale=1.30.2`

**Comment by DentonGentry** [comment]
The portList fixes will not be in any 1.32.x update.
They are aimed at the next major release, 1.34.0.

Until then, I'd recommend using 1.30.2.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/6032 was delivered in 1.34.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by Milo123459** [comment]
I'm also experiencing this. I'm seeing tailscaled running on 25% CPU. Here is the BUGREPORT and a CPU profile:
BUG-e0e55e6b472c64559b4206c0bb28accaa1e6a6393c356dadfa4116017ea33a9b-20230412102659Z-e0ffa9fa624fd703
https://pastebin.com/2jhVyik5

**Comment by DentonGentry** [comment]
@Milo123459 That system is experiencing a different issue. It appears to have been set up with `tailscale serve` and is logging that it cannot listen on the requested address approximately 24,000 times per second. The CPU consumption is due to the time spent generating and throwing away the logs.

If this is still ongoing, please file a new issue for it.

```
2023-04-12 11:19:18.995942716 +0000 UTC: [RATELIMIT] format("serve failed to listen on %v, backing off: %v") (241774 dropped)
2023-04-12 11:19:18.996070363 +0000 UTC: serve failed to listen on 100.x.y.z:3001, backing off: listen tcp4 100.x.y.z:3001: bind: address already in use
2023-04-12 11:19:18.99621851 +0000 UTC: serve failed to listen on 100.x.y.z:3001, backing off: listen tcp4 100.x.y.z:3001: bind: address already in use
2023-04-12 11:19:18.996248769 +0000 UTC: [RATELIMIT] format("serve failed to listen on %v, backing off: %v")
2023-04-12 11:19:28.996286149 +0000 UTC: [RATELIMIT] format("serve failed to listen on %v, backing off: %v") (239122 dropped)
2023-04-12 11:19:28.997243086 +0000 UTC: serve failed to listen on 100.x.y.z:3001, backing off: listen tcp4 100.x.y.z:3001: bind: address already in use
2023-04-12 11:19:28.997699916 +0000 UTC: serve failed to listen on 100.x.y.z:3001, backing off: listen tcp4 100.x.y.z:3001: bind: address already in use
2023-04-12 11:19:28.998321966 +0000 UTC: [RATELIMIT] format("serve failed to listen on %v, backing off: %v")
2023-04-12 11:19:38.994997831 +0000 UTC: [RATELIMIT] format("serve failed to listen on %v, backing off: %v") (242387 dropped)
2023-04-12 11:19:38.995164681 +0000 UTC: serve failed to listen on 100.x.y.z:3001, backing off: listen tcp4 100.x.y.z:3001: bind: address already in use
2023-04-12 11:19:38.995254644 +0000 UTC: serve failed to listen on 100.x.y.z:3001, backing off: listen tcp4 100.x.y.z:3001: bind: address already in use
```
