### ISSUE TITLE
Tailscale status shows TOR relay.

### ISSUE THREAD

**Issue by bulgin** [tailscale/tailscale#5960]
Tailscale version 1.28.0
Your operating system & version
PRETTY_NAME=“Raspbian GNU/Linux 11 (bullseye)”
NAME=“Raspbian GNU/Linux”
VERSION_ID=“11”
VERSION=“11 (bullseye)”
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debianexit point

When running trailscale status I am seeing:

linux active; relay “tor”, tx 888 rx 0

Does tailscale interact by itself with Tor?

It’s not always there but just sometimes shows up.

I am not running any tor exit nodes or otherwise connecting intentionally to Tor.

**Comment by bradfitz** [comment]
Toronto.

**Comment by bulgin** [comment]
Ah!  Thank you!!!!!
