### ISSUE TITLE
Login to headscale server with authkey doesn't set LoginName

### ISSUE THREAD

**Issue by sukidesuka** [tailscale/tailscale#5964]
### What is the issue?

On mac and linux, I connect tailscale via exec

`tailscale up --reset --accept-routes --advertise-tags=tag:developer --login-server [delete] --auth-key=[delete]`

then `tailscale down` to disconnect tailscale. If I want to reconnect tailscale, just exec `tailscale up`

---

but on windows, I connect tailscale via 

`tailscale up --reset --accept-routes --advertise-tags=tag:developer --login-server [delete] --auth-key=[delete] --unattended`

then `tailscale down` to disconnect tailscale

but when I exec `tailscale up --unattended`, it tell me
```
PS C:\Users\srauni> tailscale up --unattended
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --unattended --advertise-tags=tag:developer --login-server=[delete]

```

If I exec `tailscale up --unattended --advertise-tags=tag:developer --login-server=[delete]`, it tell me 

```
To authenticate, visit:

       https://[delete]/register/[delete]

```

### Steps to reproduce
1. close tailscale GUI program
2. exec `tailscale up --reset --accept-routes --advertise-tags=tag:developer --login-server [delete] --auth-key=[delete] --unattended` to connect tailscale
3. exec `tailscale down` to disconnect tailscale
4. exec `tailscale up --unattended` or `tailscale up` to reconnect

### OS

Windows

### OS version

Windows 11 21H2

### Tailscale version

1.30.2

### Bug report

BUG-65469fa23a9546418d17f997da6f6996dd565fd90fef49fc0a1968f9535158ed-20221017104618Z-ff7d9ac88203af48

**Comment by sukidesuka** [comment]
I'm guessing the reason is `down` command doesn't have the --unattended flag. I'm trying edit code to let `down` command pass a `forceDaemon` flag

**Comment by sukidesuka** [comment]
I passed `ForceDaemon` as true but still not working.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/63297045/196328684-2f1bdaff-8827-4f03-b854-d2cd5f4c630f.png">

```
PS C:\Users\srauni> tailscale status
# Health check:
#     - dns-os: The system cannot find the file specified.
#     - dns: The system cannot find the file specified.

fd7a:115c:a1e0::c [delete]    developer    windows -
fd7a:115c:a1e0::6 [delete] server       linux   active; direct [delete]:41641, tx 328 rx 272
PS C:\Users\srauni> tailscale down
ForceDaemon is true
PS C:\Users\srauni> tailscale up

To authenticate, visit:

        https://login.tailscale.com/a/[delete]

```

---

I noticed comment of `updatePrefs` 
```
// It returns simpleUp if we're running a simple "tailscale up" to
// transition to running from a previously-logged-in but down state,
// without changing any settings.
```

Maybe reason is `--unattended` prevented `updatePrefs`  recongnize it as `simpleUp`

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/63297045/196329116-c741108b-e339-4a0e-8713-92d7851966db.png">

**Comment by DentonGentry** [comment]
Did this system ever connect to login.tailscale.com, or was it always used with Headscale?

> tailscale have some bug on authkey login method (register method is normal)

I don't understand what this means. You are by no means the only person to use authkeys, they do work.

**Comment by DentonGentry** [comment]
Appears to be resolved now, and doesn't involve the Tailscale service.
