### ISSUE TITLE
FR: Support DNS over TLS or DNS over HTTPS

### ISSUE THREAD

**Issue by xspliff** [tailscale/tailscale#5979]

**Comment by DentonGentry** [comment]
Currently, the IP addresses for Google Public DNS, Cloudflare DNS, and NextDNS are recognized and automatically turn into DNS-over-HTTPS requests to those providers.

**Comment by xspliff** [comment]
I see that, however I'm using controld which requires you enter your own custom resolver as such: 

https://dns.controld.com/xxxxxxxxx
xxxxxxxxx.dns.controld.com

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/74
