### ISSUE TITLE
with incorrect WAN MTU tailscale goes offline while websites open fine in the browser

### ISSUE THREAD

**Issue by wizzard0** [tailscale/tailscale#5980]
### What is the issue?

`tailscale status` shows offline, and machine is unreachable. 

was working but went offline 45 minutes ago (upd: when WAN MTU was autodetected too high)

**tried:**
- tailscale up 
- router reboot, switch to different ISP
- machine reboot

**at the same time:**
- all this time websites continue to work in Firefox on this machine
- tailscale works on other machines in the same LAN

`tailscale bugreport` seems to work. ping and `tailscale ping` to local tailnet ip works. 
no other tailnet machine can reach this machine, and vice-versa.
`journalctl -f -u tailscaled` shows something weird

```
Received error: PollNetMap: Post "https://controlplane.tailscale.com/machine/map": unexpected EOF
Oct 18 07:56:48 * tailscaled[1160]: Received error: PollNetMap: Post "https://controlplane.tailscale.com/machine/map": unexpected EOF
Oct 18 07:56:53 * tailscaled[1160]: logtail: upload: log upload of 5421 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/b09d03a71e3577612376b3cee1c807cb6dceefd74ea504504d29b868e67bad7c": remote error: tls: bad record MAC
```

### Steps to reproduce

~~no idea. worked 45 minutes ago.~~
1. route the WAN interface thru network with MTU of 1324
2. `ifconfig eth0 mtu 1500`
3. restart tailscale

### Workaround (numbers might be different for you)

```
ifconfig eth0 mtu 1300
ifconfig tailscale0 mtu 1200
```

### Are there any recent changes that introduced the issue?

OS MTU discovery reset the MTU on the WAN interface too high

### OS

Linux

### OS version

Ubuntu 22.04.1 LTS 5.15.0-50-generic #56-Ubuntu

### Tailscale version

1.32.0

### Bug report

BUG-91cd5ca9c84a983c6231d1e7b82d82e88e9aad92611c4a64b27d33c06e701984-20221018080135Z-7e25b926d5ab24b3

**Comment by wizzard0** [comment]
UPD lowering MTU on the WAN interface helped. 
still:
- why does web browsing continue to work?
- i'd expect DERP to continue to work when I can watch youtube 🤔 
- any chance tailscale can detect this somehow?

**Comment by DentonGentry** [comment]
I really don't understand all of the different MTUs listed. The MTU of the WAN interface is supposed to be 1324? It was autodetected to 1800, then you set it to 1500?

**Comment by wizzard0** [comment]
@DentonGentry Supposed to be 1324, Autodetected to 1500 -> Tailscale offline

WAN set to 1300 manually -> Tailscale connects but drops large packets

WAN set to 1300 and Tailscale to 1200 -> Everything works great

I’ll remove the line about 1800 as that was a hypothesis and it seems it only causes confusion.

PS: The issue persists (i.e. I have to set both MTU again after each reboot)

**Comment by DentonGentry** [comment]
Tailscale only controls its own MTU, which is 1280 bytes. In that 1280 bytes will be the inner IP header for the 100.64.0.0/10 IP addresses, plus the inner UDP/TCP/etc headers and data.

There needs to be enough room in the packets for eth0 for the outer IPv4 or IPv6 header, plus a UDP header, plus Wireguard. IPv4 is 20 bytes, IPv6 is 40 bytes, and UDP is 8 bytes. Wireguard header size varies.

A 1324 byte MTU isn't enough to carry a maximum size packet on the tailnet if the remote end is reached by IPv6, that would require a 1280 + 40 + 8 + <wireguard header> payload which won't fit.

Even IPv4 only barely works, any key negotiation or other extra bytes in the Wireguard header pushes it over the 1324 byte limit.

> PS: The issue persists (i.e. I have to set both MTU again after each reboot)

I guess I'm not surprised that the issue persists, but I don't think there is anything Tailscale can do here. 1280 bytes is the minimum IPv6 MTU. We can't make the MTU smaller and still be IPv6 compliant.

As described above 1324 isn't really large enough to work even in the best case, and having the system come up with a wrong MTU size isn't helping either.

**Comment by DentonGentry** [comment]
If you're looking for a workaround, you can set TS_DEBUG_MTU=1100 to reduce the MTU. That is less than the IPv6 minimum but will probably work, and likely work better than whatever is going on now.

To do this: `sudo systemctl edit tailscaled.service`

This will start an editor for `/etc/systemd/system/tailscaled.service.d/override.conf`
You would add this:

```
[Service]
Environment=TS_DEBUG_MTU=1100
```

Then run these commands:
```
sudo systemctl daemon-reload
sudo systemctl restart tailscaled
```

**Comment by wizzard0** [comment]
> I don't think there is anything Tailscale can do here. 
I don’t expect WireGuard to work reliably with this MTU, indeed. 

But

1) Why can’t Tailscale reach the control plane? TCP works fine as far as I can see

2) I run my own DERP server for these types of situations, but it seems Tailscale still prefers direct UDP even when large packets get lost. 

Is it possible to extend connectivity checks with large packets? There are already quite a lot of checks as I can see in the control plane

**Comment by wizzard0** [comment]
> you can set TS_DEBUG_MTU=1100 to reduce the MTU

Great, will try later today! Thanks.

**Comment by DentonGentry** [comment]
I don't expect to do more here, for cases where the MTU is otherwise unworkable the TS_DEBUG_MTU environment variable in a systemd override can be used.
