### ISSUE TITLE
Request for clarification re: ephemeral keys being revoked

### ISSUE THREAD

**Issue by dhess** [tailscale/tailscale#5982]
Hi, I'd like to attach a long-running (but occasionally re-deployed) Fly.io application to our Tailnet. I'm following the integration documentation here: https://tailscale.com/kb/1132/flydotio/

My initial attempt had a few bugs in the entrypoint script which caused the application to crash and restart. The Tailscale bit initially worked fine and seemed to connect to the Tailnet. However, I noticed in the logs, after several application restart attempts, that Tailscale was complaining that the ephemeral auth key I'd created was invalid. I checked my Tailscale admin console and confirmed that the key had been revoked. I created another, replaced the Fly.io secret containing the key, and kept debugging. However, every time the deployment fails, the Tailscale auth key keeps getting revoked.

I've seen https://github.com/tailscale/tailscale/issues/5400 and read https://tailscale.com/blog/ephemeral-logout/, but I don't think those apply in my case, as my entrypoint script doesn't run `tailscale logout`: this application is meant to run indefinitely until it's killed and replaced by a new deployment of the same app. In fact, at the moment, while I debug this issue, the script is simply this:

```sh
      if [ -z ''${TAILSCALE_AUTHKEY+x} ]; then
        echo "TAILSCALE_AUTHKEY is not set, exiting." >&2
        exit 1
      fi
      tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &
      tailscale up --authkey="$TAILSCALE_AUTHKEY" --hostname=my-app-name
      while true; do sleep 10 ; done
```

FTR, the Tailscale version I'm running is `1.32.0`, I'm enabling the "Ephemeral" and "Pre-authorized" flags on the auth token in question, and I'm setting one ACL tag.

I doubt this is a Tailscale bug, so I'm just asking for a clarification on the intended behavior. Why is my ephemeral auth key being automatically revoked when this application is killed? From my read of the documentation, that should not be happening.

**Comment by DentonGentry** [comment]
From the description it sounds like the Reusable flag is not set. Is that correct? That means the authkey works exactly once, to authorize one node. If that node is ephemeral and deletes itself when the fly app restarts, the authkey won't work again.

<img width="516" alt="Screen Shot 2022-10-18 at 6 27 20 AM" src="https://user-images.githubusercontent.com/1140756/196443142-bd37e15d-376a-4bb4-9fe5-ffac6a90f9c3.png">

**Comment by dhess** [comment]
Hi @DentonGentry, thanks for the explanation and the quick reply. 

Indeed, the "Reusable" flag is not set for this key. The Fly.io integration doc I referenced above doesn't mention that flag at all, and what I inferred from the more generic documentation about it was that it was only necessary if you expect more than one *concurrent* instance to use the same auth key, so I didn't think it was necessary in my case. (The Fly.io `scale` for this app is not expected to exceed `1`.)

Now that you mention it, though, based on my observations of our other Fly.io application deployments, Fly.io will deploy a new instance of the app, check its health, and then delete the old one, so it seems inevitable that for a case like ours where an application is expected to be redeployed, the "Reusable" flag will need to be set, regardless of whether `scale` is > `1`.

Assuming I'm correct, I think it would be helpful to cover this case in the Fly.io integration documentation.

**Comment by DentonGentry** [comment]
We've updated https://tailscale.com/kb/1132/flydotio/ to call for a reusable key.

**Comment by mziwisky** [comment]
Thanks for the question and answer here, helped me out with a deployment on AWS Lambda.  A similar update would make sense for https://tailscale.com/kb/1113/aws-lambda, which currently does not advise the use of a reusable key, and features a screenshot of a non-reusable one being generated.
