### ISSUE TITLE
How to use Magic DNS in host when I apply tailscale in a docker container?

### ISSUE THREAD

**Issue by Coolmifi** [tailscale/tailscale#5984]
Hi, All,

I've applied the tailscale network in a docker container.   It's good.

When I try to ping the tailscale domain names thru Magic DNS function within the container it works fine.  
I can also ping 100.100.100.100 in the host environment.   But when I ping the tailscale domain names, it dosn't work. 
I've tried to update the /etc/resolv.conf, made it point to the DNS 100.100.100.100, it didn't work either.  
I've tried to use the command NSLOOKUP, and changed the server to 100.100.100.100.  When I tried to resolve the domain names in the internet (ie, google.com), it worked.  But when I tried to resolve the names in tailscale network.  It didn't either. 

What should I do, or what I missed?   Please advise. 

Thanks!

**Comment by DentonGentry** [comment]
The issue template requested the output of `tailscale bugreport`, which would let us look up what tailscaled is doing. You've deleted the entire template so we don't have anything to go on.

**Comment by Coolmifi** [comment]
I will try to submit the issue with the bugreport template, thanks!
