### ISSUE TITLE
MagicDNS (machine name) does not work in host when I apply tailscale in a docker container

### ISSUE THREAD

**Issue by Coolmifi** [tailscale/tailscale#5985]
### What is the issue?

I deployed the tailscale network in a docker container, it works fine within the container.    But I can't use MagicDNS in the host environment. 

### Steps to reproduce

I deployed the tailscale network in a docker container, it works fine within the container.    The MagicDNS function works fine within the container too.  (docker exec -it container /bin/sh)  When I try to ping the tailnet machine names within the container it works fine.    (docker exec -it container_name /bin/sh, ping abc)

In the host environment.   The tailscale IP works fine.  I can ping other nodes tailscale IPs successfully.    I can also ping the 100.100.100.100 DNS address too.    I can ping the full tailnet domain names, like  abc.servername.github.test.tailscale.net, But when I ping the tailnet machine names, ie ping abc, it doesn't work. 

I've tried to add an entry the /etc/resolv.conf, made it point to the DNS 100.100.100.100, the ping to the tailnet machine names didn't work either.
I've also tried to use the command NSLOOKUP, then changed the server to 100.100.100.100. When I tried to resolve the public domains in the internet (ie, google.com), it worked. But when I tried to resolve the machine names in tailnet. It didn't either.   (full domain name works.)

### OS

Linux

### OS version

Debian GNU/Linux 11

### Tailscale version

1.30.2

**Comment by DentonGentry** [comment]
To be honest I'm surprised that pinging `100.100.100.100` from the host works. The host wouldn't usually have a route for 100.64.0.0/10 pointing to anything.

`tailscaled` running in the container cannot change the DNS settings of the host, I don't think this is going to be feasible to support.

**Comment by DentonGentry** [comment]
A container cannot modify /etc/resolv.conf on the host, closing as infeasible.
