### ISSUE TITLE
Tailscale on Heroku, no DNS Resolution

### ISSUE THREAD

**Issue by lincolnmantracer** [tailscale/tailscale#5986]
### What is the issue?

We're in the unfortunate position of using the tailscaled sock5 proxy in Heroku to support getting a legacy app onto our network. I followed the tutorial:

```
/app/.apt/usr/sbin/tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --socket="/app/tailscaled.sock" &
until tailscale up --authkey="$TAILSCALE_AUTHKEY" --accept-routes --accept-dns; do
	sleep 1
done
tailscale status

ALL_PROXY=socks5://localhost:1055/ my-app-server
```

Tailscale comes up just fine, and the node is listed in the admin panel. However, making HTTP requests to domains which only resolve on the network are failing at during resolution:

```
dial tcp: lookup private.example.com on 10.1.0.2:53: server misbehaving
```

We're using `http.DefaultTransport` to make the HTTP request, and I'm pretty sure it's setting `Proxy` correctly. What's not clear to me at all is whether this is a general issue with the golang HTTP stack - is DNS resolution actually supposed to run over sock5 in this situation? I tried reproducing the issue on my laptop and didn't get anywhere.

In case it helps, we're using a custom resolver, set up with split DNS. The resolver is accessible via a subnet router (hence `--accept-routes`).

### OS

Linux

### OS version

Some heroku-specific thing

### Tailscale version

latest available with apt

### Bug report

BUG-beeb61f2c7675c37eed3fc1620c04be9cbcfc4a05ea7d8675daad3110d57edd0-20221019122802Z-071e979392b5900

**Comment by bradfitz** [comment]
Did you try `socks5h://` instead of `socks5://` ?

The `h`, whatever it stands for (hostnames?), means to resolve via SOCKS.

**Comment by DentonGentry** [comment]
Please reopen if `socks5h:// ` did not resolve the issue.

**Comment by fabiopedrosa** [comment]
@bradfitz @DentonGentry the use of `socks5h` stopped working in the last few days. Anything got released that would make that?

**Comment by DentonGentry** [comment]
socks5h and DNS lookups are handled entirely within `tailscaled`. The 1.42.0 release went out last Wednesday May 24, 2023 https://github.com/tailscale/tailscale/releases/tag/v1.42.0

There wasn't anything in it which looks suspicious with respect to SOCKS5h, but if you note it working with 1.40 and not with 1.42 then it presumably regressed somehow. Please open a new issue if that is the case, concerning the regression. Ideally this would include:
- what DNS lookup was being done (in particular: was it a [MagicDNS](https://tailscale.com/kb/1081/magicdns/) name, a Global DNS name, or in a [Split DNS domain](https://tailscale.com/learn/why-split-dns/))
- a `tailscale bugreport` shortly after trying to do something using `socks5h` and noting it not working.

**Comment by fabiopedrosa** [comment]
@DentonGentry any easy way to install a older version of tailscale if you're using the one-line installer?

**Comment by DentonGentry** [comment]
`curl -fsSL https://tailscale.com/install.sh | sh` always installs the current release.
One can use `apt install tailscale=1.40.1` after running the one-liner.
