### ISSUE TITLE
dns-os: setLinkDNS: Failed to activate service 'org.freedesktop.resolve1': timed out

### ISSUE THREAD

**Issue by jdgiddings** [tailscale/tailscale#5990]
### What is the issue?

When running `sudo tailscale up --ssh --accept-routes` on one of my user's Ubuntu machines, I get the following error:

```
.# Health check:
    - dns-os: setLinkDNS: Failed to activate service 'org.freedesktop.resolve1': timed out (service_start_timeout=25000ms)
    - dns: setLinkDNS: Failed to activate service 'org.freedesktop.resolve1': timed out (service_start_timeout=25000ms)
```

DNS is this machine barely works at all. It resolves some addresses but not others, mainly failing to resolve the a public DNS record if the domain is also a private DNS domain. I assume this is a package conflict, however I haven't been able to check yet as the machine is in constant use

This happens across several Tailscale versions, though this is the first time I've actually gotten an error from `tailscale up` on this machine

### Steps to reproduce

Run `sudo tailscale up --ssh --accept-routes` on Ubuntu

### Are there any recent changes that introduced the issue?

Not that I am aware of

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.30.2

### Bug report

BUG-f81af8f83b09a4394ab99ba892a40abc5d0b7b8972c340a30ee812c4d4aee92a-20221019183939Z-3eb6ea73ce738ee4

**Comment by bradfitz** [comment]
cc @andrew-d

**Comment by danderson** [comment]
From the healthcheck, looks like systemd-resolved is failing to start up on this machine, which would definitely cause pretty much all of its DNS woes. IOW, the system is configured to use resolved for DNS (which is what tailscale detected and is trying to do), but when trying to talk to resolved, systemd is reporting back that it's unable to start it.

What does `systemctl status systemd-resolved` say?

**Comment by DentonGentry** [comment]
Please reopen the bug if the problem turns out to not be related to `systemd-resolved` not running.
