### ISSUE TITLE
Blank screen after using different VPN

### ISSUE THREAD

**Issue by sdf121234** [tailscale/tailscale#5993]
### What is the issue?

After starting other VPN, it seems, that tailscale crush and needs to be uninstalled. Even bugreport is unavailable

### Steps to reproduce

1. Start Tailscale
2. Start the Service 
3. -> Everything ok
4. Stop the Service
5. Connect to another VPN
6. Disconnect from other VPN 
7. Go back to Tailscale App
8. -> blank screen 

Edit:
Figured out: to prevent uninstalling Tailscale app: 
9. go to iPhone options -> vpn -> unmark the previous vpn and mark Tailscale tunnel but don't press connect
10. Go back to Tailscale App
11. Reconnect possible

Edit 2: Also reported here https://github.com/tailscale/tailscale/issues/3189 

### Are there any recent changes that introduced the issue?

no

### OS version

16.02

### Tailscale version

1.32.

**Comment by DentonGentry** [comment]
We'll need to look for this in Apple's CrashReporter.

**Comment by DentonGentry** [comment]
I think we'll handle this on https://github.com/tailscale/tailscale/issues/3189

Duplicate of https://github.com/tailscale/tailscale/issues/3189
