### ISSUE TITLE
Legacy dns breaks

### ISSUE THREAD

**Issue by harukodi** [tailscale/tailscale#6005]
When trying to override the dns with legacy dns resolvers Internet breaks. When using nextdns and forcing the use of nextdns it seems to work over DoH. Why does legacy breaks? Is this a bug? Only if i override it stops to resolve dns names on my nodes.

**Comment by harukodi** [comment]
![image](https://user-images.githubusercontent.com/48220443/197306056-6b6bbda2-4388-4301-b800-0b0afddb65dd.png)

when using DNS with DoH and not over IP it seems to work with Nextdns in my case, but it was breaking name resolution on my nodes when forcing clients to use Nextdns when i added the resolver as 45.90.28.113. If I use the DoH from nextdns seems to work. Legacy seems to break for me. If I turn on this option (Override local dns) if I turn if off the connectivity starts to work again.
Now am using nextdns over DoH and then enforcing the option (Override local dns)

**Comment by DentonGentry** [comment]
If you want this to be looked at, please:
1. re-create the condition where DNS is broken
1. Run "tailscale bugreport"
1. paste it here

That gives us something we can look into.

**Comment by bradfitz** [comment]
We do not support "legacy DNS" with Linked IPs on NextDNS. NextDNS will only use DoH.

NextDNS's Linked IPs do not work with multiple devices so they don't make sense for Tailscale which is fundamentally about using multiple devices together.

Do not enter the NextDNS IPv4 addresses into Tailscale. It won't do what you expect. It'll degraded into a config-free NextDNS profile still using DoH.

**Comment by harukodi** [comment]
Thank you for the heads up. Seemed to work before but i can understand what you mean that the filter gets downgraded because the IP isn't propagated to nextdns. Worked on one of my nodes because it was behind the IP that was propagated to nextdns second didn't work. Well this is sorted with nextdns over https and it works really well. Thanks for the help.

**Comment by DentonGentry** [comment]
Closing as resolved.
