### ISSUE TITLE
Support NS records from DNS config

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#6008]
_Originally posted by @anaman in https://github.com/tailscale/tailscale/issues/4515#issuecomment-1274374373_

In DNSmanagement it is possible to set a NS value to assign a sub domain to different NS (Name Servers) in order to be able to host services on different platforms.

E.g. web services on web.xyc.net on cloudflare but have vpn.xyc.net on
digital ocean.

would there be a way to do that with tailscale where a sub domain could be assigned to the machines in the private network so they can be assigned certs with their machine names in talscale?

**Comment by danderson** [comment]
This is roughly the same request as #4515, in that an NS delegation would be the obvious implementation of BYOD: user delegates a subdomain to a DNS server of ours, and from that server we handle LetsEncrypt issuance and anything else that requires public DNS records.

**Comment by DentonGentry** [comment]
Ok. I can unhide this comment in #4515 and close this new issue created from it.
