### ISSUE TITLE
FR: allow split DNS domains to not set search domains

### ISSUE THREAD

**Issue by wknapik** [tailscale/tailscale#6010]
### What is the issue?

We use a custom DNS server for some domains (some of which we don't own, or control). This causes Tailscale to push search domains to clients for each of those domains. This is not desirable and can't be switched off.

To make matters worse, one of those domains will respond with an IP to queries for any subdomain, so it becomes a catch-all.

### Steps to reproduce

Use split DNS.

### Are there any recent changes that introduced the issue?

No.

### OS

macOS

### OS version

n/a

### Tailscale version

any

### Bug report

n/a

**Comment by DentonGentry** [comment]
> We use a custom DNS server for some domains (some of which we don't own, or control).

Could I ask the purpose of this server? Was it set up as part of the Tailscale deployment, or previously existed and Split DNS is a way to make it work over the tailnet?

I ask because this is how the feature was originally specced to work, and isn't universally unwelcome behavior across all users as a clear bug to be fixed. Additionally for macOS, one cannot have a match domain which is not a search domain.

**Comment by wknapik** [comment]
> Could I ask the purpose of this server? Was it set up as part of the Tailscale deployment, or previously existed and Split DNS is a way to make it work over the tailnet?

This was set up for a previous VPN, but we use it with Tailscale as well, to enable routing only traffic to specific domains through the VPN (see: https://github.com/tailscale/tailscale/issues/1748#issuecomment-1150959222).

> I ask because this is how the feature was originally specced to work, and isn't universally unwelcome behavior across all users as a clear bug to be fixed. Additionally for macOS, one cannot have a match domain which is not a search domain.

This affects all platforms. The behavior is the same for me on Linux.

We'd prefer to use our custom DNS for only some domains, but if we had to, we could use it to resolve all domain names.

**Comment by DentonGentry** [comment]
> This affects all platforms. The behavior is the same for me on Linux.

What I mean is: when we tried to set SplitDNS domains in macOS to be MatchDomains without also making them be SearchDomains, macOS didn't treat them as MatchDomains either and the SplitDNS feature didn't work at all.

**Comment by henricook** [comment]
I'd love a workaround for this, the catch all search domain breaks resolution for some TLDs as well, for instance any `.aws` domains get caught by my catch all search domain now.

It's weird.

In the meantime I'm running a cron every 60 seconds to `sed` the search domains out of my resolv.conf as tailscale seems to update them at unpredictable intervals.

**Comment by kabirsikand** [comment]
The team here at Tailscale are testing functionality to allow Split DNS without forcing a Search Domain to be added. If you'd like to be a part of the testing process, please reach out to `product@tailscale.com` or DM me on Twitter. 

cc @henricook / @wknapik

**Comment by henricook** [comment]
@kabirsikand unfortunately my email from last week just bounced

![image](https://user-images.githubusercontent.com/82004/231701845-6d4151da-3146-4f54-a416-de03f580b3d3.png)

**Comment by DentonGentry** [comment]
Feature to decouple search domains from match domains launched today:
https://tailscale.com/changelog/#2023-04-28-service
