### ISSUE TITLE
Sometimes advertised subnet routes are not propagated to control server

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#6012]
### What is the issue?

Two customers now have reported an issue where they try to add subnet routes to an existing device and the routes do not appear in the admin panel. I did a bit more digging with the [most recent instance](https://secure.helpscout.net/conversation/1989766436/4646) (which was a 4via6 route, if that happens to be relevant) and they were not shown in our support tools or in the database, but I do see them in the client logs.

Advertising the same route on my workstation worked fine. Restarting tailscaled on the customer's device did not help. This needs further investigation.

One customer [reported this on OPNSense](https://secure.helpscout.net/conversation/2032964026/5844/), the other on Linux.

### Steps to reproduce

`tailscale up --advertise-routes=fd7a:115c:a1e0:b1a:0:8:c0a9:0/120`
It does not reproduce on my devices.

### OS

Linux, Other

### Tailscale version

1.32.0

**Comment by DentonGentry** [comment]
To my knowledge this has not recurred recently.

**Comment by DentonGentry** [comment]
At this point I do not expect to diagnose what happened in October. If a similar symptom is seen, please reopen.
