### ISSUE TITLE
FR: Add documentation for correct vnc setup

### ISSUE THREAD

**Issue by dhdevdk** [tailscale/tailscale#6016]
### What are you trying to do?

It is advertised that tailscale works with vnc, but I haven't found a good solution to set it up. 
All solutions I have found so for wrap vnc in a ssh session which adds a lot of latency. e.g. 
https://www.lukemillermakes.com/2022/04/vpn-remote-desktop-with-tailscale-and-x11vnc/.
What worked for me was
```
tailscale up --ssh
ssh -L 5900:localhost:5900 <my_user>@<my_tailscale_ip>
vncviewer localhost:5900
```
I consider this a workaround. How do I directly access port 5900 inside the tailscale network rather than wrapping the connection in a ssh tunnel?
From the documentation (https://tailscale.com/kb/1017/install/?q=vnc)

"Even historically insecure protocols like Telnet, VNC, FTP, HTTP, etc. are protected with Tailscale, since all traffic is encrypted under the hood using [WireGuard](https://www.wireguard.com/)."

So how do I set this up? Wrapping vnc in a ssh session is encryption without using tailscale.

### How should we solve this?

Add a small example in the documentation how to expose ports in the tailscale network.

**Comment by DentonGentry** [comment]
What vnc server are you using?

**Comment by bradfitz** [comment]
This is probably Issue #1121 again.

@dhdevdk, your VNC server is probably only listening on localhost:5900.

You can check with `netstat --inet -n --listen` on the VNC server side.

If you make it listen more widely then you can use `vncviewer TAILSCALE-IP:5900` on the client side.

But really this is something I'd like Tailscale to detect and offer to fix it for you.

**Comment by dhdevdk** [comment]
> What vnc server are you using?

https://github.com/QubesOS-contrib/qubes-remote-desktop

> This is probably Issue #1121 again.
> 
> @dhdevdk, your VNC server is probably only listening on localhost:5900.
> 
> You can check with `netstat --inet -n --listen` on the VNC server side.
> 
> If you make it listen more widely then you can use `vncviewer TAILSCALE-IP:5900` on the client side.
> 
> But really this is something I'd like Tailscale to detect and offer to fix it for you.

Here is my output:

user@remote-admin:~$ netstat --inet -n --listen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp        0      0 my-tailscale-ip:41001    0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
udp        0      0 0.0.0.0:41641           0.0.0.0:*                          
raw        0      0 0.0.0.0:17              0.0.0.0:*               7   

So the vnc sever is not listening on the tailscale ip?

**Comment by DentonGentry** [comment]
> So the vnc sever is not listening on the tailscale ip?

`tcp 0 0 0.0.0.0:5900 0.0.0.0:* LISTEN`
means it is listening on all ips, which should be fine.

The next most likely blocking issue would be a local firewall. Does `ufw status` show the firewall is on?
If so, and if you're willing to let Tailscale ACLs control access to tailscale0, you could use: `ufw allow in on tailscale0`

**Comment by dhdevdk** [comment]
Here is my output of ufw
```
user@remote-admin:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
5900                       ALLOW       Anywhere                  
22                         ALLOW       Anywhere                  
Anywhere on tailscale0     ALLOW       Anywhere                  
5900 (v6)                  ALLOW       Anywhere (v6)             
22 (v6)                    ALLOW       Anywhere (v6)             
Anywhere (v6) on tailscale0 ALLOW       Anywhere (v6)             

user@remote-admin:~$ 

```

This does not solve the issue.

**Comment by DentonGentry** [comment]
At this point we're having to just guess because we don't know your tailnet and cannot look at configuration nor telemetry. VNC does work via Tailscale and people do use it. That `ssh -L 5900:localhost:5900 <my_user>@<my_tailscale_ip>` works means the remote VNC can only be reached on its localhost for some reason.

If you'd either:
- include the output of `tailscale bugreport` from the remote system shortly after attempting to VNC to my_tailscale_ip:5900, or
- [submit to support](https://tailscale.com/contact/support/) instead so they can know what tailnet to look at.

We'll have a better chance of seeing what is going wrong.

**Comment by DentonGentry** [comment]
Nothing more to do here.
