### ISSUE TITLE
magicdns breaks local connectivity

### ISSUE THREAD

**Issue by pshirshov** [tailscale/tailscale#6030]
### What is the issue?

I have several hosts in my local network, like vmhost1.local1.org, vmhost2.local1.org, vmhost3.local2.org, etc.

Some of these machines has running tailscale. So, in my own DNS the short names of the hosts (vmhost1, vmhost2, vmhost3) are the same as the short host names in my tailscale dns.

When I enable tailscale DNS it overwrites `/etc/resolve.conf` and removes my local dns from there. So, there are two problems:

1.  Machines running tailscale with magicdns enabled aren't able to resolve non-tailscale hostnames using short names (FQDN still works because tailscale preserves search domains)
2. Two tailscale-enabled machines always use tailscale even for communication over local network when short hostnames are used. That increases the pings tenfold - from 2ms to about 24ms.

I think it should be a good idea to allow user to NOT resolve short hostnames through tailscale.

`dnsmasq` can forward queries for specific domains to specific servers, maybe tailscale should remember what was in `resolv.conf` before it overwrites it and forward all queries for non-tailscale domains there.

```
server=/muy.domain/192.168.x.y
server=/x.168.192.in-addr.arpa/192.168.x.y
```

### OS

Linux, macOS

**Comment by bradfitz** [comment]
Tailscale only modifies `/etc/resolv.conf` as a last resort if you're not running a DNS configuration on Linux that supports cooperation. (see https://tailscale.com/blog/sisyphean-dns-client-linux/; basically you want `systemd-resolved` which is the best Linux implementation of DNS)

Or, if you want to be in control of all DNS, then use `tailscale up --accept-dns=false` and it'll step out of the way and you can do whatever you want. The 100.100.100.100 local resolver will still run and respond to full names if you want to delegate a suffix to that.

**Comment by pshirshov** [comment]
Actually I'm using a pretty standard networkmanager+dnsmasq combination on my machines running libvirt VMs and `systemd-resolved` on my VMs, but **the second issue affects macOS too**: when I connect to a host using its short name (`vmhost1`) the connection always happens to tailscale IP and the latency is lot higher than with direct connection

Thanks for the idea, I didn't know that `100.100.100.100` is accessible regardless of `--accept-dns` value.

**Comment by bradfitz** [comment]
I don't think there's anything we'll end up doing here. It's our intention that MagicDNS resolves short names. That's kinda its main point.

And the macOS network sandbox doesn't let us program split DNS suffix routes separately from DNS search domains (even though macOS itself supports that). So if we want to be in the macOS App Store, the least common denominator we have to assume across all platforms is the macOS sandbox rules, so we can't provide an option for MagicDNS-without-search-domains.

Given that you can wire this up yourself and we can't provide any config knobs, I'll just close this for now. But let us know if there's something else we could do.

(Performance issues are tracked elsewhere already)

**Comment by pshirshov** [comment]
You may add an option to disallow short name resolution.

**Comment by bradfitz** [comment]
> You may add an option to disallow short name resolution.

Not really, per above.

> Also you may distribute two versions with different capabilities.

That's a support nightmare.

We don't like a policy of "sometimes it works on some types of machines, sometimes, if you do it just right". Because then people get used to it working one way and add a new OS and find that it can't work on that OS that way.

So we tend to only distribute things we can make work the same everywhere.

That said, you can set `--accept-dns=false` and then do unofficial things yourself. Sounds like you've got that covered on Linux. On macOS, see `scutil` and `man 5 resolver`.

**Comment by pshirshov** [comment]
> That's a support nightmare.

Many applications do that, even indie application like The Unarchiver. Probably it may even be possible to have the same binary and add capabilities dynamically.

> We don't like a policy of "sometimes it works on some types of machines, sometimes, if you do it just right".

Well, currently it works "somehow" and slightly breaks things in completely regular setups.

Another way may be an option to automatically add a prefix to every TS hostname. Like "myhost1" would become "ts-myhost1"

**Comment by bradfitz** [comment]
You can certainly name all your hosts with a `ts-` prefix. From the web admin console you can force a device name so the node's reported hostname isn't used.

**Comment by pshirshov** [comment]
It would be very nice if I can do that automatically.
