### ISSUE TITLE
FR: Only selected device will use "Global nameservers" use "adguard DNS" server

### ISSUE THREAD

**Issue by lutfor-diu** [tailscale/tailscale#6035]
### What are you trying to do?

Is there any option where only selected device will use Global nameserver and other use the default one. 

### How should we solve this?

don't know

### What is the impact of not solving this?

Benefit for user with local dns server. without this option my local device uses the local dns for queries thus making the dns server log false querry. 

### Anything else?

it would be a great feature o have. thank you in advance.

**Comment by DentonGentry** [comment]
On Linux you would use: `tailscale up --accept-dns=false`

On Windows and macOS in the menu for the Tailscale app there is a "Preferences > Use Tailscale DNS" which can be toggled off.

**Comment by lutfor-diu** [comment]
> On Linux you would use: `tailscale up --accept-dns=false`
> 
> On Windows and macOS in the menu for the Tailscale app there is a "Preferences > Use Tailscale DNS" which can be toggled off.

thank you so much!
