### ISSUE TITLE
Line with concatenated email addresses isn't caught by ACL parser. 

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#6040]
### What is the issue?

```
			"action": "accept",
			"src":    ["user1@gmail.com, user2@gmail.com"],
			"dst":    ["tag:servers"],
			"users":  ["autogroup:nonroot"],
```
was allowed to be saved, but obviously doesn't work, because each email address 

### Steps to reproduce

skip closing and opening quotes in a `src` line in the ssh section when there's multiple objects in the rule.

**Comment by DentonGentry** [comment]
The difficulty we'll run into is while "user1@gmail.com, user2@gmail.com" is an obvious error to a human, the parser allows most strings as they might be valid GitHub profile names. We could check for the existence of invalid characters in a profile name, like a space.

**Comment by JayWStapleton** [comment]
@phirework - You've been nominated to look at this

**Comment by DentonGentry** [comment]
There were a number of pull requests linked to this bug, and one of them resolved the issue. Attempting to add the SSH policy quoted at the beginning of this issue now fails to validate.

`Error: invalid username: "user1@gmail.com, user2@gmail.com": needs '@domain', 'group:' or 'tag:': ParseAddr("user1@gmail.com, user2@gmail.com"): unexpected character (at "user1@gmail.com, user2@gmail.com")`
