### ISSUE TITLE
macOS Catalina: Can't log in

### ISSUE THREAD

**Issue by smorkin** [tailscale/tailscale#6046]
### What is the issue?

A few weeks ago Tailscale stopped working on my Catalina Mac mini. It simply won't log in, and selecting "Log in…" from menu, nothing happens.

Additionally, in Network settings, Tailscale Tunnel connection is jumping up/down, as if it is trying to connect, maybe succeeds for a really short time, then disconnects.

Console logs when starting Tailscale.app:

default	01:15:18.885898+0200	Finder	LAUNCHING:0x0-0xbf0bf Tailscale foreground=0 bringForward=0 seed=191 userActivityCount=0
default	01:15:18.910854+0200	runningboardd	Resolved pid 99650 to [executable<Tailscale(501)>:99650]
default	01:15:18.915220+0200	runningboardd	[executable<Tailscale(501)>:99650] This process will not be managed.
default	01:15:18.915286+0200	runningboardd	Now tracking process: [executable<Tailscale(501)>:99650]
default	01:15:18.917135+0200	runningboardd	Acquiring assertion targeting executable<Tailscale(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:138] with description <RBSAssertionDescriptor; uielement:99650; ID: 355-138-474; target: 99650> attributes = {
    <RBSDomainAttribute: 0x7fa099d23f30; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
default	01:15:18.918036+0200	runningboardd	Assertion 355-138-474 (target:executable<Tailscale(501)>) will be created as active
default	01:15:18.910578+0200	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Tailscale
default	01:15:18.919275+0200	runningboardd	[executable<Tailscale(501)>:99650] Ignoring jetsam update because this process is not memory-managed
default	01:15:18.919331+0200	runningboardd	[executable<Tailscale(501)>:99650] Ignoring resume because this process is not lifecycle managed
default	01:15:18.919369+0200	runningboardd	Finished acquiring assertion 355-138-474 (target:executable<Tailscale(501)>)
default	01:15:18.919393+0200	runningboardd	[executable<Tailscale(501)>:99650] Set darwin role to: UserInteractive
default	01:15:18.919573+0200	runningboardd	[executable<Tailscale(501)>:99650] Ignoring GPU update because this process is not GPU managed
default	01:15:18.921032+0200	runningboardd	Acquiring assertion targeting executable<Tailscale(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:138] with description <RBSAssertionDescriptor; uielement:99650; ID: 355-138-475; target: 99650> attributes = {
    <RBSDomainAttribute: 0x7fa099e1b030; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
default	01:15:18.921329+0200	runningboardd	Assertion 355-138-475 (target:executable<Tailscale(501)>) will be created as active
default	01:15:18.959505+0200	secinitd	Tailscale[99650]: root path for bundle "<private>" of main executable "<private>"
default	01:15:18.996006+0200	runningboardd	Finished acquiring assertion 355-138-475 (target:executable<Tailscale(501)>)
default	01:15:18.997360+0200	secinitd	Tailscale[99650]: AppSandbox request successful
default	01:15:19.012809+0200	runningboardd	Invalidating assertion 355-138-474 (target:executable<Tailscale(501)>) from originator 138
default	01:15:19.035880+0200	Tailscale	FRONTLOGGING: version 1
default	01:15:19.035931+0200	Tailscale	Registering, pid=99650
default	01:15:19.038769+0200	Tailscale	CHECKIN: pid=99650
default	01:15:19.065968+0200	launchservicesd	CHECKIN:0x0-0xbf0bf 99650 io.tailscale.ipn.macos
default	01:15:19.066363+0200	Tailscale	CHECKEDIN: pid=99650 asn=0x0-0xbf0bf foreground=0
default	01:15:19.070808+0200	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Tailscale
default	01:15:19.102644+0200	Tailscale	Registered, pid=99650 ASN=0x0,0xbf0bf
default	01:15:19.102953+0200	Tailscale	Registered, pid=99650 cgConnectionID=59637
default	01:15:19.105743+0200	Tailscale	BringForward: pid=99650 asn=0x0-0xbf0bf bringForward=0 foreground=0 uiElement=1 launchedByLS=1 modifiersCount=1 allDisabled=0
default	01:15:19.105866+0200	Tailscale	BringFrontModifier: pid=99650 asn=0x0-0xbf0bf Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	01:15:19.107429+0200	Tailscale	Current system appearance, (HLTB: 1), (SLS: 0)
default	01:15:19.115767+0200	Tailscale	Post-registration system appearance: (HLTB: 1)
default	01:15:19.148432+0200	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: io.tailscale.ipn.macos token: f4268 pid: 99650
default	01:15:19.162977+0200	Tailscale	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001e65180
 (
    "<NSAquaAppearance: 0x600001e65000>",
    "<NSSystemAppearance: 0x600001e65080>"
)>
default	01:15:19.198122+0200	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: io.tailscale.ipn.macos token: f4273 pid: 99650
fault	01:15:19.236432+0200	Tailscale	<private>
default	01:15:19.237833+0200	Tailscale	Registering for test daemon availability notify post.
default	01:15:19.238137+0200	Tailscale	notify_get_state check indicated test daemon not ready.
default	01:15:19.246018+0200	Tailscale	SignalReady: pid=99650 asn=0x0-0xbf0bf
default	01:15:19.247558+0200	Tailscale	SIGNAL: pid=99650 asn=0x0x-0x782527
default	01:15:19.356394+0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier io.tailscale.ipn.macos, type: 0: 0x7f95c643c460 at /Applications/Tailscale.app
default	01:15:19.400991+0200	Tailscale	NOGO-LOG: BackendClient.create
default	01:15:19.428303+0200	nesessionmanager	Got a new session client connection from Tailscale(99650)
default	01:15:19.428612+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Adding a connection for client Tailscale[99650]
default	01:15:19.429555+0200	Tailscale	Last disconnect error for Tailscale Tunnel changed from "none" to "VPN-sessionen misslyckades eftersom ett internt fel inträffade."
default	01:15:19.430092+0200	Tailscale	Current bundle (/Applications/Tailscale.app) does not have a SystemExtensions directory
default	01:15:19.435604+0200	Tailscale	 Saving configuration Tailscale Tunnel with existing signature {length = 20, bytes = 0xfe6780f25faa1a36c08b36b79d0385f7e969f3a3}
default	01:15:19.443088+0200	Finder	Requested application <private> has policy 0, associated category:DH1005 associated sites:(null) equivalent bundle identifiers:io.tailscale.ipn.macos
default	01:15:19.450804+0200	Tailscale	Received a com.apple.neconfigurationchanged notification with token 44
default	01:15:19.451144+0200	Tailscale	 Successfully saved configuration Tailscale Tunnel
default	01:15:19.458182+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Received a start command from Tailscale[99650]
default	01:15:19.456599+0200	Tailscale	Last disconnect error for Tailscale Tunnel changed from "none" to "VPN-sessionen misslyckades eftersom ett internt fel inträffade."
default	01:15:19.457866+0200	Tailscale	NOGO-LOG: BackendClient.go; state=<disconnected>
default	01:15:19.458287+0200	nesessionmanager	Registering session NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]
default	01:15:19.459918+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Resetting VPN On Demand
default	01:15:19.460179+0200	nesessionmanager	Found 0 (0 active) registrations for io.tailscale.ipn.macos.network-extension (com.apple.networkextension.packet-tunnel)
default	01:15:19.460619+0200	nesessionmanager	Found 0 (0 active) registrations for io.tailscale.ipn.macos.network-extension (com.apple.networkextension.packet-tunnel)
default	01:15:19.460992+0200	nesessionmanager	io.tailscale.ipn.macos[inactive]: starting
default	01:15:19.461639+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)] in state NESMVPNSessionStateIdle: update configuration
default	01:15:19.461806+0200	nesessionmanager	<NESMServer: 0x7fc512c04380>: Register Enterprise VPN Session: NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]
default	01:15:19.462207+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Successfully registered
default	01:15:19.462943+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Changing pause level 1 -> 0
default	01:15:19.465708+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: status changed to connecting
default	01:15:19.466303+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)] in state NESMVPNSessionStateIdle: received start message
default	01:15:19.466394+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Leaving state NESMVPNSessionStateIdle
default	01:15:19.466475+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Entering state NESMVPNSessionStatePreparingNetwork
default	01:15:19.466958+0200	nesessionmanager	Found 0 (0 active) registrations for io.tailscale.ipn.macos.network-extension (com.apple.networkextension.packet-tunnel)
default	01:15:19.467242+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Leaving state NESMVPNSessionStatePreparingNetwork
default	01:15:19.467312+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Entering state NESMVPNSessionStateStarting
default	01:15:19.467448+0200	nesessionmanager	NEVPNTunnelPlugin(io.tailscale.ipn.macos[inactive]): Sending start command
default	01:15:19.467493+0200	nesessionmanager	io.tailscale.ipn.macos[inactive]: starting
default	01:15:19.468420+0200	Tailscale	Last disconnect error for Tailscale Tunnel changed from "VPN-sessionen misslyckades eftersom ett internt fel inträffade." to "none"
default	01:15:19.468559+0200	Tailscale	NOGO-LOG: tunnel connection status changed to '<connecting>'
default	01:15:19.468708+0200	Tailscale	Last disconnect error changed from "VPN-sessionen misslyckades eftersom ett internt fel inträffade." to "none"
default	01:15:19.476383+0200	nesessionmanager	io.tailscale.ipn.macos[564]: disposing
default	01:15:19.476937+0200	nesessionmanager	io.tailscale.ipn.macos[564]: Tearing down agent connection
default	01:15:19.477051+0200	nesessionmanager	NESMVPNSession[Primary Tunnel:Tailscale Tunnel:647F2E86-3FA8-42CC-AD32-C736611367C5:(null)]: Plugin is installed
default	01:15:19.477300+0200	nesessionmanager	io.tailscale.ipn.macos[564]: XPC connection went away
default	01:15:19.564064+0200	IPNExtension	Hello, I'm launching as euid = 501, uid = 501, (persona not available)
error	01:15:19.583887+0200	IPNExtension	Bootstrapping; external subsystem UIKit_PKSubsystem refused setup
default	01:15:19.583992+0200	IPNExtension	Bootstrapping; Bootstrap complete. Ready for handshake from host.
default	01:15:19.585357+0200	IPNExtension	[u C8044C66-2966-49F9-8DFC-4C7785495CEB] [(null)((null))] Prepare received as euid = 501, uid = 501, (persona not available)
default	01:15:19.586165+0200	IPNExtension	[u 83B9DE9D-4E2B-4C7F-9408-74FBF645185C] [<private>(<private>)] Set sole personality.
default	01:15:19.587362+0200	IPNExtension	[u 83B9DE9D-4E2B-4C7F-9408-74FBF645185C] [<private>(<private>)] Begin using received as euid = 501, uid = 501, (persona not available)
error	01:15:19.597973+0200	IPNExtension	cannot open file at line 43354 of [378230ae7f]
…

(not sure how many log rows are needed; console continuously adds logs as long as Tailscale is running).

### Are there any recent changes that introduced the issue?

No changes on my side, I just discovered one day that Tailscale no longer was logged in and that trying to login was not possible.

### OS version

macOS Catalina 10.15.7

### Tailscale version

1.32.1 (App Store)

### Bug report

Running /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport gives: 2022/10/25 01:07:35 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial tcp [::1]:61781: connect: connection refused

**Comment by charlieporth1** [comment]
I've got this same issue on two different Macs running Monterey. It is due to complete failure of DNS and the tailscale daemon

**Comment by DentonGentry** [comment]
Unfortunately I can't tell if that last line of log is actually important or just another weird thing that happens while starting up a macOS application:
`error 01:15:19.597973+0200 IPNExtension cannot open file at line 43354 of [378230ae7f]`

I imagine the most likely problem is that something bad happened in the Keychain entries for Tailscale and it can no longer start. https://tailscale.com/kb/1069/uninstall/ (the macOS pane) shows the steps to fully uninstall the app including all of its keys in the keychain. You can then authenticate it again.

It will lose its old IP address. I'd recommend fully removing Tailscale from the Mac, choosing Remove from https://login.tailscale.com/admin/machines to free up the hostname, and then authenticating again.

**Comment by DentonGentry** [comment]
@charlieporth1 though it is possible you're seeing the same issue, it is more likely that you're seeing some other bug which manifests as DNS failing. If you'll file a new issue and include `/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport`, we can look into it.

**Comment by DentonGentry** [comment]
The screenshot in https://github.com/tailscale/tailscale/issues/6046#issuecomment-1290129036 appears to be what one gets by starting from the Settings > Network > Tailscale Tunnel, is that right?

Could you run /Applications/Tailscale and choose "Log in" from the Tailscale icon in the menubar? The flow through the login process is slightly different.

**Comment by smorkin** [comment]
No, that screen appears after starting Tailscale.app the first time (after uninstalling). The menubar item also appears at the same time, and the item in the Network list. Closing the screen and quitting Tailscale, trying to login from menubar fails as it did before. 26 okt. 2022 kl. 16:56 skrev Denton Gentry ***@***.***>:﻿
The screenshot in #6046 (comment) appears to be what one gets by starting from the Settings > Network > Tailscale Tunnel, is that right?
Could you run /Applications/Tailscale and choose "Log in" from the Tailscale icon in the menubar? The flow through the login process is slightly different.

**Comment by lavir** [comment]
It looks like my problem relates to this issue https://github.com/tailscale/tailscale/issues/3192 as I use AdGuard on Mac

But none of the recommendations to fix do not work for me.

**Comment by agottardo** [comment]
Closing because this is stale. If the issue is still occurring, please mention me and I'll re-open.
