### ISSUE TITLE
Google TV crashes when a USB Ethernet adaptor is added and Tailscale is running 

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#6047]
### What is the issue?

Tailsale is broken when running Google TV is broken on Android TV 12. Causes a crash of the os which in turn causes a reboot when hotplugging a USB 3.0 to an ethernet adaptor. No network connectivity is being reported to the os. Disconnecting the VPN before hotplugging the ethernet device fixes that reboot. On a reboot, the app crashes and will not open from startup. A reboot fixes that.
Chromecast with Google TV is the device this happens on

### Are there any recent changes that introduced the issue?

New OS

### OS

Android

### OS version

Android TV 12

### Tailscale version

1.33.21

**Comment by DentonGentry** [comment]
Google TV with Chromecast is one of the devices we test. This is the one?

![PXL_20221024_235031987](https://user-images.githubusercontent.com/1140756/197651585-794b8c4e-7294-48be-970d-9851f53de7aa.jpg)

The Ethernet adaptor I have is built into the power supply, which connects to the sole USB port on the Google TV. How does one hotplug it without powercycling the whole device? Do you mean plugging in an RJ45 Ethernet cable while the device is running?

**Comment by charlieporth1** [comment]
The 4K one. By using a Anker USB C PD device and a Amazon basic USB 3.0 to ethernet

**Comment by charlieporth1** [comment]
PS. The only reason I started hotplugging the USB ethernet while running tailscale was because the USB ethernet was not autoconfiguring on boot for an IP address. Hotplugging it would fix that but cause these issues with tailscale

**Comment by DentonGentry** [comment]
I'm having trouble accepting that something which makes Android reboot is somehow a bug in a userspace app.

**Comment by charlieporth1** [comment]
Truth be told so am I. But the thing that I found peculiar was the fact that tailscale wouldn't open after the reboot. And that tailscale turned off as a VPN would not cause it to reboot when hot plugging

**Comment by charlieporth1** [comment]
So it would seem that any usb ethernet adapter would cause a hotplug issue when tailscale is running. I'll let you know if its a VPN thing later
