### ISSUE TITLE
FR: Work with PatchMyPC to add Tailscale to their supported apps

### ISSUE THREAD

**Issue by fedbwas** [tailscale/tailscale#6053]
### What are you trying to do?

Tailscale updates frequently and PatchMyPC would help reliability by automatically installing the updates

### How should we solve this?

there's already a vote started on the patchmypc app request page by a different user  - can go vote there https://ideas.patchmypc.com/ideas/PATCHMYPC-I-2465

but if the devs worked with each other i'm sure things would move much quicker at that level!

**Comment by DentonGentry** [comment]
I think this need is better met via https://github.com/tailscale/tailscale/issues/755
