### ISSUE TITLE
Machines Tags getting removed when logging in

### ISSUE THREAD

**Issue by baandab** [tailscale/tailscale#6058]
### What is the issue?

In the ACL, I have several tags created (see below).

For each Machine, I assign the tag appropriately.   I can visually see them assigned on the Machines view.

If quit the TailScale clinet and log back in, the Tags are removed.   I have to reapply them. See logs below.

```
"tagOwners": {

		"tag:allow-dns-advertisements": ["EMAIL"],
		"tag:block-dns-advertisements": ["EMAIL"],
		"tag:ipad":                     ["EMAIL"],
		"tag:desktop":                  ["EMAIL"],
		"tag:laptop":                   ["EMAIL"],
		"tag:nas":                      ["EMAIL"],
		"tag:phone":                    ["EMAIL"],
	},
```

Logs:

```
Timestamp	Action	Actor	Target
Oct 25, 2022 9:26:47 AM	Update ACL tags for node	USERNAME [XXXXX.tailedXXXX.ts.net](https://login.tailscale.com/admin/machines/100.123.X.XX)
Oct 25, 2022 9:24:29 AM	Update policy file for tailnet	USERNAME     EMAIL
Oct 25, 2022 9:23:37 AM	Update policy file for tailnet	USERNAME	EMAIL
Oct 25, 2022 9:23:07 AM	Update policy file for tailnet	USERNAME	EMAIL
Oct 25, 2022 9:22:40 AM	Update policy file for tailnet	USERNAME	EMAIL
Oct 25, 2022 9:21:30 AM	Log in node	USERNAME	[XXXXX.tailedXXX.ts.net](https://login.tailscale.com/admin/machines/100.123.X.XX)
Oct 25, 2022 9:21:30 AM	Update key expiry time for node	USERNAME	[COMPUTER.tailedXXX.ts.net](https://login.tailscale.com/admin/machines/100.123.6.19)
Oct 25, 2022 9:19:39 AM	Update policy file for tailnet	USERNAME 	EMAIL
```

### Steps to reproduce

1. Quit the Client
2. Launch the Client and login

### Are there any recent changes that introduced the issue?

Yes, added NextDNS as a global nameserver.  Added this to my ACLs:

```
	"nodeAttrs": [
		{
			"target": ["allow-dns-advertisements"],
			"attr": [
				"nextdns:XXXXXX",
			],
		},
		{
			"target": ["block-dns-advertisements"],
			"attr": [
				"nextdns:XXXXXX",
			],
		},
	]
```

### OS

macOS

### OS version

12.6.1

### Tailscale version

1.32.0 (App Store)

### Bug report

BUG-a17da3583079402d7d5f673c88edf307c128c40c923fb521aef3ba353b6dfb88-20221025163908Z-594507a97982da61

**Comment by eugene1g** [comment]
As I understand Tailscale identity, a single machine is _either_ owned by a user, _OR_ is identified by ACL tags. These methods are mutually exclusive, so you cannot combine them to define one device as "$user's computer, with a tag `tag:laptop`". If true, that explains why re-authenticating the machine as a named user will take over that device as clear out all tags.

**Comment by DentonGentry** [comment]
As described: logging back in will authenticate the node as the User.

If you really want the macOS system to be a server and carry a tag, https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS may be a better way to go.
