### ISSUE TITLE
Provide better messaging about IP forwarding

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#606]
A few users have written in, confused by an error about IP forwarding not being enabled when they try to [set up a subnet](https://tailscale.com/kb/1019/subnets).

I've updated our documentation [to include instructions on how to enable IP forwarding](https://tailscale.com/kb/1023/troubleshooting#why-do-i-get-an-error-about-ip-forwarding-when-using-advertise-routes), but it'd be nice if we could identify this error and give people the needed steps right in the CLI.

In short, they need to run these lines:

```
echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p /etc/sysctl.conf
```

Maybe we could say:

```
$ tailscale up --advertise-routes=<routes>

Error: IP forwarding is not enabled, but is needed for --advertise-routes.
You can enable IP forwarding by editing /etc/sysctl.conf and trying again:

    echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf
    sudo sysctl -p /etc/sysctl.conf

```

Having the documentation built-in would be a much better experience.

Also a valid fix, but more risky: maybe we should manage this setting on behalf of users?

**Comment by apenwarr** [comment]
In theory there is already a warning from `tailscale up` when forwarding is disabled, but people might be missing it, and it's not treated as an error, just a warning. Also, if forwarding was once enabled but becomes disabled, there's no interaction point where we can print the message, unfortunately. We might need to plumb it through to the admin panel somehow instead.

**Comment by bradfitz** [comment]
The current warning output is this:

```go
func (b *LocalBackend) CheckIPForwarding() error {
        if wgengine.IsNetstackRouter(b.e) {
                return nil
        }
        if isBSD(runtime.GOOS) {
                //lint:ignore ST1005 output to users as is
                return fmt.Errorf("Subnet routing and exit nodes only work with additional manual configuration on %v, and is not currently officially supported.", runtime.GOOS)
        }

        var keys []string

        if runtime.GOOS == "linux" {
                keys = append(keys, "net.ipv4.ip_forward", "net.ipv6.conf.all.forwarding")
        } else if isBSD(runtime.GOOS) {
                keys = append(keys, "net.inet.ip.forwarding")
        } else {
                return nil
        }

        for _, key := range keys {
                bs, err := exec.Command("sysctl", "-n", key).Output()
                if err != nil {
                        //lint:ignore ST1005 output to users as is
                        return fmt.Errorf("couldn't check %s (%v).\nSubnet routes won't work without IP forwarding.", key, err)
                }
                on, err := strconv.ParseBool(string(bytes.TrimSpace(bs)))
                if err != nil {
                        //lint:ignore ST1005 output to users as is
                        return fmt.Errorf("couldn't parse %s (%v).\nSubnet routes won't work without IP forwarding.", key, err)
                }
                if !on {
                        //lint:ignore ST1005 output to users as is
                        return fmt.Errorf("%s is disabled. Subnet routes won't work.", key)
                }
        }
        return nil
}
```

I'd be reluctant to give exact instructions as it might vary by distro, but including a URL to tailscale.com docs would be work.

@rosszurowski, should we link to https://tailscale.com/kb/1104/enable-ip-forwarding/ ?

That'd bake that URL into the binary, so even more important to make sure we never 404 that URL.

**Comment by rosszurowski** [comment]
Yeah, linking to a KB URL is a great option.

We want to avoid 404s in general, but they're always a risk. I like what Vercel does here, where they use a dedicated URL (or domain) solely for error redirects. So if you run into an error with a project of theirs, you'll see:

```
For more details, see: https://err.sh/micro/path-missing
```

We could set up `tailscale.com/err/ip-forwarding` and ensure anything under the `err` path never breaks.

But maybe that's too complicated and we should just link to kb/1104 :)

**Comment by bradfitz** [comment]
Added the /kb/ URL to the error message. Let's not break them. :)

Leaving bug open to track plumbing this more to the admin panel (we plumb it to control already) and showing the brokeness is `tailscale status` (which is really #2528), and also maybe just fixing this for users automatically.

**Comment by rosszurowski** [comment]
> Leaving bug open to track plumbing this more to the admin panel

We already warn when IP forwarding is disabled in the admin panel, if that's what you mean.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/303731/127361429-3707d9bf-b13e-4b26-a6f0-9abc5d3fdc94.png">

**Comment by bradfitz** [comment]
Oh, right. Great, let's call this fixed.
