### ISSUE TITLE
Last update (1.32.1) broke the ability to use protonvpn and tailscale at the same time

### ISSUE THREAD

**Issue by dysphone** [tailscale/tailscale#6064]
### What is the issue?

Hello, 

following the last update it is impossible for me to use my configuration (either on ios or macos): protonvpn and tailscale. 

Before the last update (with tailscale 1.32) I was using protonvpn via the IKEV2 protocol and at the same time I was using tailscale as a personal vpn server (iOs) and it worked perfectly. Same thing on Macos. 

Now I can't use tailscale and proton vpn at the same time on iOs and MacOS and I can't connect to my other devices like before. In short, an update that has completely broken my use - I have to disconnect one to use the another.

Any idea please?

Thanks, 

Regards,

### Are there any recent changes that introduced the issue?

Updated tailscale from 1.32 to 1.32.1

### OS

macOS, iOS

### OS version

macOs mojave , iOS 15.7 and iOS 16.0.1

### Tailscale version

1.32.1

**Comment by dysphone** [comment]
Hello, with the last update on ios and macos - everything works fine - bug has been resolved - I can use both proton vpn and tailscale at the same time! 

Thank you very much !!!!

**Comment by ScamBuster** [comment]
Interesting. How does Tailscale find the network whet the IP address has been masked by Proton VPN ?     I trust Tailscale will be OK with Pi-Hole, as the IP address will be consistent across the network.
