### ISSUE TITLE
obscure Failed To Update DNS message in UI due to error in existing data, not modified data

### ISSUE THREAD

**Issue by jonseymour** [tailscale/tailscale#6070]
### What is the issue?

- I had an existing Split DNS entry with the name 10.2.0.02.  I was not aware of this corrupt name.
- At the time of the problem I was trying to add a valid Split DNS entry with the name 10.2.0.2 (but a different name)
- the update was failing in UI, without explaining why - the edit I thought I was making was actually fine - the problem was in the existing data but this was not obvious from the limited information available in the message visible in the UI
- once I opened the developers console of the browser and inspecting the network traffic I was able to see that one of the existing entries was corrupt
- deleting that entry solved my issue

The problem is that message produced by the UI did not contain enough information to diagnose the issue and I had to drop down into developer mode to discover what the root cause of the problem was.

### Steps to reproduce

Arrange for a Split DNS entry  to contain invalid data. This probably can no longer be done through UI because of improved validation and may require a backend edit to effect.

Then, try to add a new, valid Split DNS entry and observe the "Failed To Update DNS" message.

Then, delete the invalid Split DNS entry and observe that the original can now proceed unmolested by the error.

### Are there any recent changes that introduced the issue?

Presumably this issue occurred after validation of DNS entries was tightened.

### OS

macOS

### OS version

12.6.1

### Tailscale version

Web UI

**Comment by jonseymour** [comment]
I am not really expecting a fix, but I wanted to log the issue for the information of others.

**Comment by DentonGentry** [comment]
Could you attach a tailscale bugreport? This will allow us to identify the tailnet, to consult a backup from a week ago and see what was in the DNS config, to check if there are any other tailnets who would run into the same issue.

**Comment by DentonGentry** [comment]
ETIMEDOUT. Without being able to identify the tailnet to consult backups, nothing to followup on.
