### ISSUE TITLE
FR: NextDNS profile name next to the ID

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#6071]
### What are you trying to do?

Figure out what NextDNS profile an ID is referring to, on the Tailscale DNS panel.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/18581859/197926857-2641810c-4508-4ff4-93f5-1ef128e3005a.png">

### How should we solve this?

Displaying the NextDNS profile name next to the ID would be great.

### What is the impact of not solving this?

Clicking on the ID which redirects to the NextDNS website.

**Comment by DentonGentry** [comment]
We don't have access to your NextDNS account settings, it isn't clear we can even know what the profile names are.

**Comment by arunsathiya** [comment]
Happy for this issue to be closed as well if [the NextDNS API approach](https://github.com/tailscale/tailscale/issues/6072#issuecomment-1291455830) isn't something Tailscale team would want to explore.

**Comment by DentonGentry** [comment]
To set expectations: I doubt that we'll want to ask people for their NextDNS API key. None of the primary functionality for NextDNS requires an API key.

**Comment by DentonGentry** [comment]
Closing as infeasible, we don't have (and don't want) the user's NextDNS API key.
