### ISSUE TITLE
FR: Support for NextDNS' Bootstrap IPs feature

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#6072]
### What are you trying to do?

Trying to use NextDNS on my university WiFi which seems to block NextDNS/encrypted DNS in general.

### How should we solve this?

Support NextDNS' bootstrap IPs feature which is available [when generating an Apple config](https://apple.nextdns.io/).

<img width="499" alt="image" src="https://user-images.githubusercontent.com/18581859/197927097-5e2d1ada-d496-4c03-8f6d-a8a27e47a9b0.png">

### What is the impact of not solving this?

No workaround. I use university's WiFi/turn off Tailscale DNS.

**Comment by DentonGentry** [comment]
The device side of supporting the Bootstrap IPs is pretty straightforward, to add the two IPv4 addresses:
- 45.90.28.53
- 45.90.30.53

However doing only that results in a generic DNS service. To actually make it find your profile settings you have to add your source IPv4 addresses, fixed IP addresses of your home and so on. Tailscale does not have access to the settings of your NextDNS account to be able to do this automatically.

**Comment by arunsathiya** [comment]
Possibly something that can be [obtained using NextDNS API](https://nextdns.github.io/api/#nested-objects-and-arrays)? User can supply the NextDNS API token to Tailscale. 

I'll leave this issue open but if this isn't something Tailscale would want to explore further, please feel free to close this issue!

**Comment by DentonGentry** [comment]
To set expectations: I doubt that we'll want to ask people for their NextDNS API key. None of the primary functionality for NextDNS requires an API key.

**Comment by bradfitz** [comment]
Also the NextDNS IPv4 IP linking feature only works on a single device so it doesn't make sense for Tailscale which is fundamentally about using multiple devices. 

What else is your university blocking? Might be time for an exit node!

**Comment by DentonGentry** [comment]
Closing as infeasible, we don't have (and don't want) the user's NextDNS API key.
