### ISSUE TITLE
Kaspersky detecting Tailscale 1.32.1 as Trojan

### ISSUE THREAD

**Issue by BlueTeam3r** [tailscale/tailscale#6073]
### What is the issue?

Can't use Tailscale VPN

### Steps to reproduce

Download and install Tailscale 1.32.1

### Are there any recent changes that introduced the issue?

Before the update, In Tailscale 1.32, there was no issue

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.32.1

**Comment by BlueTeam3r** [comment]
I have downgraded the tailscale windows client to version 1.30.2 as a workaround for now

**Comment by DentonGentry** [comment]
This happens periodically: using the Go language for a Windows app is not a common choice, but several widespread strains of malware are written in Go. Machine learning antivirus scanners periodically decide that some portion of the Go runtime is a malware signature.

We'll be releasing 1.32.2 in the near future, which is likely to not be detected by the same signature.

**Comment by DentonGentry** [comment]
We're corresponding with Kaspersky: could I ask for a screenshot from the Kaspersky software flagging 1.32.1 as malware?

We also released 1.32.2 yesterday, which will hopefully not be flagged and could be installed after trying 1.32.1 again.

**Comment by BlueTeam3r** [comment]
Kaspersky's System Watch module, which is responsable for ML scanning, has flagged the executable as trojan as you have explained above.

Also, I have noticed it only flags it after I try to access some resource across the VPN.

Here's the screenshots:

![kaspersky_system_watch_tailscale_1](https://user-images.githubusercontent.com/51140160/198301489-6d2c1cf5-5212-4c48-a18d-90ea25af921d.png)

![kaspersky_system_watch_tailscale_2](https://user-images.githubusercontent.com/51140160/198301423-6dfc6bac-6523-4dca-8eaa-840b7db62161.png)

**Comment by BlueTeam3r** [comment]
I have updated the software package to version 1.32.2 and now it works without being detected as trojan from Kaspersky.

Though I noticed the local DNS is not working as it used to in older version.

Right now I can access my local resources through the VPN using the IPs only but not hostnames.

**Comment by DentonGentry** [comment]
We're attempting to add the Tailscale installer to a Kaspersky signed allowlist, and 1.32.2 doesn't suffer the same issue. Will close this as sufficiently resolved.
