### ISSUE TITLE
When behind a firewall which blocks external DNS's, using an Exit-node does not work (On linux only)

### ISSUE THREAD

**Issue by Yohello1** [tailscale/tailscale#6074]
### What is the issue?

When I'm behind a strict firewall which blocks external dns's, and is overall quite strict, using an exit node does not work. By 'does not work', I mean I cannot access the internet when it's active. However on iOS when I use the exit node, it works perfectly fine, and I can access the internet. 
If I'm connected to the exit node and I run `tailscale status` it normally tells me `not in map poll`.

### Are there any recent changes that introduced the issue?

None from tailscale, the only changes have been to the firewall and I do not know what they are.

### OS

Linux

### OS version

Debian 11.5 (on host & client)

### Tailscale version

1.32.0

### Bug report

BUG-2136ff9c2ebdac3683716d62f6a9c12beaf44c0865e79f97f7b11bde63099e6a-20221026144548Z-2fcd04f082849dc0

**Comment by DentonGentry** [comment]
If the firewall is blocking UDP port 53, a couple options might be:
- in https://login.tailscale.com/admin/dns configure a global nameserver of 8.8.8.8 or 1.1.1.1, Google or Cloudflare. Those should get turned into DNS-over-HTTPS at the exit node, which has a better chance of getting through.
- use NextDNS, which also gets turned into DNS-over-HTTPS: https://tailscale.com/blog/nextdns/

**Comment by Yohello1** [comment]
I'll try that out, just give me a bit to figure it all out. 
Thank you

**Comment by Yohello1** [comment]
Yup it works, thank you.
