### ISSUE TITLE
FR: Machine's own tags should be available in Self field when running `tailscale up --json`

### ISSUE THREAD

**Issue by jtcressy** [tailscale/tailscale#6076]
### What are you trying to do?

I'm trying to install some automation script on my servers that discovers what its capabilities are on my tailnet based on what ACL tags are assigned to the node it's running on. It also should not have to directly contact tailscale control api for this information, as that would require distributing API keys which is less than ideal.

### How should we solve this?

Populate Self.Tags when querying local-api for Status

### What is the impact of not solving this?

I have to manually signal my script with capabilities information on a machine after it connects to the tailnet, which gets tedious when onboarding new devices to my network.

**Comment by DentonGentry** [comment]
This seems plausible.

The place where the output from `tailscale up --json` has access to the ipn.Notify: https://github.com/tailscale/tailscale/blob/81fd259133f510be35114c456cb927f7ef7537ec/cmd/tailscale/cli/up.go#L574

The ipn.Notify contains a NetworkMap: https://github.com/tailscale/tailscale/blob/9f39c3b10f7f0f9b995c396da7a0c84ad62b53be/ipn/backend.go#L60

The NetworkMap contains a SelfNode struct: https://github.com/tailscale/tailscale/blob/9f39c3b10f7f0f9b995c396da7a0c84ad62b53be/types/netmap/netmap.go#L29

The struct contains the tags: https://github.com/tailscale/tailscale/blob/9f39c3b10f7f0f9b995c396da7a0c84ad62b53be/tailcfg/tailcfg.go#L204

**Comment by knyar** [comment]
Looking at the linked task, it seems that this is about `tailscale status` rather than `tailscale up`, right?

**Comment by DentonGentry** [comment]
We expect this fix to be delivered in release 1.34.
