### ISSUE TITLE
"Sign in with Google" doesn't work in emulator

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#608]
I installed Android studio, downloaded all the various SDK & NDKs, did `make tailscale-debug.apk` (built at master: c70669986207), started an AVD emulator, `adb install tailscale-debug.apk`

* clicked Tailscale in the emulator
* clicked "Sign in with Google" in the emulator,
* logged in to my gmail test account,
* "Choose an account" .... click my test account gmail.com
* ... nothing .... 

It's stuck at:

<img width="516" alt="Screen Shot 2020-07-27 at 3 43 48 PM" src="https://user-images.githubusercontent.com/2621/88599166-f74fff00-d01f-11ea-9535-fa3a401f5d77.png">

As a test, I tried logging in with it to the web site first, thinking that maybe the Android auth path didn't create a new account if it didn't already exist, but didn't seem to work.

* `adb shell am force-stop com.tailscale.ipn`
* try again...
* same

Ultimately I was able to log in with *"Sign in with other"* and using the same account.

When I click *"Sign in with Google"*, all I see in `adb logcat` is:

```
07-27 15:46:27.949   594  1926 I ActivityTaskManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.tailscale.ipn cmp=com.tailscale.ipn/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras)} from uid 10152
07-27 15:46:27.949   594   635 W EventSequenceValidator: IntentStarted during UNKNOWN. Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.tailscale.ipn cmp=com.tailscale.ipn/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras) }
07-27 15:46:27.949   462   738 D iorapd  : Cannot find compiled trace in sqlite for package_name: com.tailscale.ipn activity_name: com.google.android.gms.auth.api.signin.internal.SignInHubActivity
07-27 15:46:27.949   462   738 D iorapd  : Prebuilt compiled trace doesn't exists. file_path: /product/iorap-trace/com.tailscale.ipn.compiled_trace.pb
```

But not sure what those mean, if anything.

**Comment by bradfitz** [comment]
Also, that widget to the left of "Needs Authentication" in the header bar should probably be disabled in this state. You can't disable the need to authenticate.

**Comment by eliasnaur** [comment]
> Also, that widget to the left of "Needs Authentication" in the header bar should probably be disabled in this state. You can't disable the need to authenticate.

I suggested disabling it in https://github.com/tailscale/tailscale/issues/420#issuecomment-637813246, but chose to follow the iOS behaviour described in https://github.com/tailscale/tailscale/issues/420#issuecomment-637827355. I'm happy to reverse that decision (and the iOS may have changed in the meantime).

**Comment by priyanshnama** [comment]
can i work on this

**Comment by eliasnaur** [comment]
Sure, but I'm not sure what the way forward is. @bradfitz did you get Google Sign-In to work? Do you want the toggle widget changed?

**Comment by bradfitz** [comment]
I haven't tried again, but I have your email explaining the steps I never took, so I assume that's sufficient. Maybe you could document it in the repo in the README or somewhere?

And, yeah, let's get rid of the toggle. It's a weird first experience.

Maybe replace it with "Sign in to Tailscale" at the top bar (and without the toggler) instead of nerdy "Needs authentication" ?

Or just "Tailscale" at top, since the two "Sign in with ..." already scream that sign-in is required.
