### ISSUE TITLE
Windows system assigning 169.254.x.y to Tailscale interface

### ISSUE THREAD

**Issue by shanyan-wcx** [tailscale/tailscale#6084]
### What is the issue?

After upgrading to 1.32.2, I cannot use tailscale and clash at the same time.This problem did not exist in previous versions.
![屏幕截图_20221027_011551](https://user-images.githubusercontent.com/58252651/198198634-fdd2ed9b-c2aa-42dc-a9c2-a55d89e232e5.png)

### Steps to reproduce

1. Turn on the computer
2. Clash starts automatically
3. The tailscale starts automatically
4. Tailscale fault

### Are there any recent changes that introduced the issue?

Upgrade to 1.32.2

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.32.2

### Bug report

BUG-74125bd68196d21869f61957f8a397b52da29f72d25d05139c8442854120384d-20221027051956Z-f9b252de146014e9

**Comment by DentonGentry** [comment]
Something is enabling DHCP on the Tailscale interface, timing out, and assigning a link-local address:
`"Tailscale":["169.254.83.107/16","fe80::d8ff:5060:f230:9168/64"]`

This breaks Tailscale.

**Comment by DentonGentry** [comment]
At this point I don't expect to diagnose what happened last October, however I will note the finding of "There are several other VPN products installed at the same time" and that other VPN products have repeatedly futzed with Tailscale's network interface.
