### ISSUE TITLE
Browser SSH in firefox has the last line half out of view

### ISSUE THREAD

**Issue by zellyn** [tailscale/tailscale#6091]
### What is the issue?

![image](https://user-images.githubusercontent.com/33625/198366697-582a83e6-2252-4754-b833-90702e5def1c.png)

### Steps to reproduce

Click the ssh button in admin

### OS

macOS

### OS version

MacOS 12.6

### Tailscale version

1.32.0 on my mac, 1.32.1 on the linux target I'm ssh'ing to

### Bug report

BUG-81de7171c9e0067342e4f496695f36375a66716b746a105ef7adbc1a3cb0677f-20221027181352Z-b3060292e917e7d5

**Comment by zellyn** [comment]
Safari seems to work fine. Chrome made the last line just a couple pixels too narrow, but didn't cut it in half.

**Comment by mihaip** [comment]
Thank you for reporting this. A fix for this has been deployed, please let us know if this is still an issue after reloading the admin console.
