### ISSUE TITLE
Tailscale Client is Not Configuring MagicDNS on Windows Machine

### ISSUE THREAD

**Issue by BlueTeam3r** [tailscale/tailscale#6093]
### What is the issue?

**In Version 1.30.2**
MagicDNS is configured in Windows.

**In Version 1.32.2**
Windows DNS configuration is untouched, making access to resources across the VPN only possible with IP addresses but not hostnames.

**Screenshots**
![tailscale_dns_settings_enabled](https://user-images.githubusercontent.com/51140160/198388654-d856342f-0066-4614-80ac-1e2ce44908e7.png)
![dns_configuration](https://user-images.githubusercontent.com/51140160/198388698-e013df29-8a7c-4553-803c-d7ecc0726bfc.png)

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.32.2

### Bug report

BUG-696d62c629258c9e76c6e98eb1ebe1b484a858f777e90a02d7ef3cef68c56f05-20221028075757Z-1d31c2f280d38fd9

**Comment by DentonGentry** [comment]
On a Windows system running Tailscale 1.32.2:

```
C:\Users\dgentry>nslookup
Default Server:  magicdns.localhost-tailscale-daemon
Address:  100.100.100.100
```

So there is something more going on than just 1.32.2 on a Windows system. The issue template asks for a bug report to let us look up telemetry. Without that, we won't be able to make progress on this issue.

**Comment by BlueTeam3r** [comment]
Here's the bug report:

BUG-696d62c629258c9e76c6e98eb1ebe1b484a858f777e90a02d7ef3cef68c56f05-20221028075757Z-1d31c2f280d38fd9

**Comment by DentonGentry** [comment]
Just noting from investigation: it does receive a DNS config.
```
2022-10-28 07:54:23.4744878 +0000 UTC: dns: Set: {DefaultResolvers:[192.168.x.y] Routes:{tail00000.ts.net.:[] ts.net.:[]}+65arpa SearchDomains:[tail00000.ts.net.] Hosts:4}
2022-10-28 07:54:23.4744878 +0000 UTC: dns: Resolvercfg: {Routes:{.:[192.168.x.y]} Hosts:4 LocalDomains:[ts.net. tail00000.ts.net.]+65arpa}
```

**Comment by BlueTeam3r** [comment]
Few days after that log,  i have disconnected and reconnected the machine to Tailscale, and Windows was pointing to the MagicDNS as expected.

The configration persisted through system reboot. 

I tried the same steps on a different machine and it solved it there as well.
