### ISSUE TITLE
FR: Support OpenSUSE stable

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#6095]
### What are you trying to do?

OS=opensuse
VERSION=leap/15.4
PACKAGETYPE=zypper
UNAME=Linux vilya 5.14.21-150400.24.21-default #1 SMP PREEMPT_DYNAMIC Wed Sep 7 06:51:18 UTC 2022 (974d0aa) x86_64 x86_64 x86_64 GNU/Linux

NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

**Comment by zimmski** [comment]
OpenSUSE 15.3 is maintained until November 2022. See https://en.opensuse.org/Lifetime. That is in a few days :alarm_clock:  All people will (at least the should because they do not receive any updates then) migrate to 15.4.
