### ISSUE TITLE
Windows: New local user creates a "new" machine in Tailscale

### ISSUE THREAD

**Issue by dkerwin** [tailscale/tailscale#610]
**Describe the bug**
One of our developers has 2 user accounts on his windows machine and I have approved the system in the past. He has now switched the local user and started tailscale and the system is now considered new and has to be approved additionally.

**To Reproduce**
1. Start tailscale on the windows system
2. Authorize the machine in the admin UI
3. Switch to a different user account on windows
4. Start Tailscale
5. Machine needs approval in the admin UI again

**Expected behavior**
I would expect that the machine certificate is bound to the machine and not to the user account.

**Screenshots**
This is the same machine.
<img width="208" alt="Screenshot 2020-07-28 at 21 10 27" src="https://user-images.githubusercontent.com/168948/88710330-cb637500-d116-11ea-9ec0-f291a64fa460.png">

**Comment by bradfitz** [comment]
@apenwarr and I just discovered this the other day too. (Machine keys aren't handled properly on Windows. They should be per-machine rather than per-user.)

We need to fix this anyway as part of Windows headless service support so hopefully it'll be fixed soonish.
