### ISSUE TITLE
Tailscale doesn't update `known_hosts` file on windows

### ISSUE THREAD

**Issue by StraightfaceStudios** [tailscale/tailscale#6100]
### What is the issue?

Tailscale doesn't modify the known_hosts file.  Default strict policies result in blocked connections if you attempt to connect with and without Tailscale enabled. 

### Steps to reproduce

1) Connect to %ComputerName% (192.168.1.100)
2) Install Tailscale on %ComputerName%
3) Connect to %ComputerName% (100.1.1.1)

ecdsa signature error. 

Fix: Open C:\users\%Username%\.ssh\known_hosts and delete 192.168.1.100 entry. 

### OS

Windows

### OS version

Windows 10 

### Tailscale version

1.32.2

### Bug report

BUG-abe60bc8b1abd0726ea544870bee0abd58cdb1440bc6745885c49c557ab8431a-20221027235631Z-e78520d821434bf8

**Comment by DentonGentry** [comment]
Are you using `tailscale up --ssh` to enable the Tailscale SSH server, or you have the regular Microsoft-supplied SSH server running?

**Comment by StraightfaceStudios** [comment]
Tailscale up --ssh on the linux machines.  (To my knowledge windows does not yet support tailscale up --ssh)

**Comment by DentonGentry** [comment]
By default Windows has `StrictHostKeyChecking` off
```
C:\Users\dgentry>ssh root@10.1.10.12
The authenticity of host '10.1.10.12 (10.1.10.12)' can't be established.
ECDSA key fingerprint is SHA256:T2nnn6NyvMEPa5hs0NbqOJ6jREvr8SjM/AKxn9LvO4Q.
...

C:\Users\dgentry>ssh root@100.104.59.4
The authenticity of host '100.104.59.4 (100.104.59.4)' can't be established.
ECDSA key fingerprint is SHA256:T2nnn6NyvMEPa5hs0NbqOJ6jREvr8SjM/AKxn9LvO4Q.
...
```

--------

With `StrictHostKeyChecking` on, the Windows SSH client is unperturbed that 10.1.10.12 and 100.104.59.4 have the same fingerprint.
```
C:\Users\dgentry>ssh -o StrictHostKeyChecking=yes root@100.104.59.4
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.13.19-2-pve x86_64)

#
```

--------

If I remove 100.104.59.4 from C:\Users\dgentry\.ssh\known_hosts, ssh fails... but I don't see what tailscaled is supposed to do about that. Strict key checking is strict.
```
C:\Users\dgentry>ssh -o StrictHostKeyChecking=yes root@100.104.59.4
No ECDSA host key is known for 100.104.59.4 and you have requested strict checking.
Host key verification failed.
```

**Comment by bradfitz** [comment]
If you're using Tailscale SSH on the Linux side, did you try the `tailscale ssh` client side on Windows? It sets the known hosts file automatically so there are no warnings.

**Comment by StraightfaceStudios** [comment]
In the grand tradition of being unable to break things when they need to be broken... I can no longer reproduce today😂. It was a different error though from StrictHostKeyChecking, it was the DNS Spoofing error. 

I could connect once, and then if I connected or disconnected from tailscale and attempted to connect directly over LAN\Tailscale it would error. 


```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The ECDSA host key for TailNode has changed,
and the key for the corresponding IP address 192.168.1.100
is unchanged. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
```

**Comment by StraightfaceStudios** [comment]
Oh this is probably a result of enabling the --ssh flag at some point between the last good connection and last night.  Would that have re-rolled the ECDSA keys for non-tailscale ssh connections?

**Comment by bradfitz** [comment]
Yes, turning on/off `--ssh` changes SSH servers effectively with different host keys.

**Comment by DentonGentry** [comment]
I think this is resolved now, by enabling Tailscale SSH.
