### ISSUE TITLE
SSH Console terminal size exceeds windows size when maximized

### ISSUE THREAD

**Issue by DazWilkin** [tailscale/tailscale#6103]
### What is the issue?

Console SSH is a good addition to an excellent product, thanks!

I tried it today on a Chromebook against two different hosts.

When I manually resize the screen, the terminal is correctly displayed within the window.

If I maximize the screen, the terminal size exceeds the window size and the most recent line is slightly off the bottom of the screen and hidden behind the window's chrome.

### Steps to reproduce

1. Use Console SSH to connect to a host
2. Resize manually without issue
3. Maximize results in a terminal that exceeds the window

### OS

Other

### OS version

ChromeOS (Chromebook) Version 106.0.5249.134 (Official Build) (64-bit)

### Tailscale version

N/A

**Comment by DazWilkin** [comment]
![Screenshot 2022-10-27 17 40 52](https://user-images.githubusercontent.com/1022400/198423634-0791b5f8-f4ba-44fd-a229-aec818648a9a.png)

**Comment by DentonGentry** [comment]
Symptom similar to https://github.com/tailscale/tailscale/issues/6091

**Comment by DazWilkin** [comment]
I looked for similar but didn't find... That's it. Feel free to close this dup.

**Comment by mihaip** [comment]
Thank you for reporting this. A fix for this has been deployed, please let us know if this is still an issue after reloading the admin console.

**Comment by DazWilkin** [comment]
LGTM! Thank you.
