### ISSUE TITLE
FR: Siri Shortcuts integration

### ISSUE THREAD

**Issue by dvcrn** [tailscale/tailscale#6106]
### What are you trying to do?

- Connect Tailscale when iPhone is connected to power
- Disconnect tailscale when battery is low (it's a battery hog)
- The OS sometimes disconnects tailscale, so I want to automate reconnecting it if that happens before I run stuff that needs my tailnet

### How should we solve this?

Provide Siri Shortcut integration to: 

- Connect tailscale
- Disconnect tailscale
- Get current connection status

### What is the impact of not solving this?

- Tailscale randomly getting disconnected on iOS (reliability)
- Less control over when the network is up

**Comment by mihaip** [comment]
Duplicate of #2504
