### ISSUE TITLE
Tailscale hangs indefinitely on misbehaving DNS

### ISSUE THREAD

**Issue by siikanen** [tailscale/tailscale#6110]
### What is the issue?

Sometimes when I try to go log into tailscale, I get this weird behaviour where running `sudo tailscale up` freezes. Seems like the login flow goes ok until `control: creating new noise client` comes up and then fails with `Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded`

See logs below

```Oct 28 13:51:27 carbon tailscaled[7554]: ipnserver: conn2: connection from userid 0; root has access
Oct 28 13:51:27 carbon tailscaled[7554]: Start
Oct 28 13:51:27 carbon tailscaled[7554]: control: client.Shutdown()
Oct 28 13:51:27 carbon tailscaled[7554]: control: client.Shutdown: inSendStatus=0
Oct 28 13:51:27 carbon tailscaled[7554]: control: mapRoutine: quit
Oct 28 13:51:27 carbon tailscaled[7554]: control: Client.Shutdown done.
Oct 28 13:51:27 carbon tailscaled[7554]: using backend prefs for "_daemon": Prefs{ra=false dns=true want=true routes=[] nf=on Persist=nil}
Oct 28 13:51:27 carbon tailscaled[7554]: Backend: logs: be:495a217121ba33adf5c90d17c7138fb21263e9d8d9900b113a00357307310882 fe:
Oct 28 13:51:27 carbon tailscaled[7554]: Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
Oct 28 13:51:27 carbon tailscaled[7554]: blockEngineUpdates(true)
Oct 28 13:51:27 carbon tailscaled[7554]: Reconfig(down): no changes made to Engine config
Oct 28 13:51:27 carbon tailscaled[7554]: StartLoginInteractive: url=false
Oct 28 13:51:27 carbon tailscaled[7554]: control: client.Login(false, 2)
Oct 28 13:51:27 carbon tailscaled[7554]: control: LoginInteractive -> regen=true
Oct 28 13:51:27 carbon tailscaled[7554]: control: doLogin(regen=true, hasUrl=false)
Oct 28 13:51:37 carbon tailscaled[7554]: trying bootstrapDNS("derp12c.tailscale.com", "149.28.119.105") for "controlplane.tailscale.com" ...
Oct 28 13:51:37 carbon tailscaled[7554]: bootstrapDNS("derp12c.tailscale.com", "149.28.119.105") for "controlplane.tailscale.com" = [2a05:d014:386:202:24dd:46aa:f98e:9997 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:202:a3e1:5be6:cbb1:1ac9 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:203:4535:c15c:9ab:8258 2a05:d014:386:202:6dd4:fc68:35ae:2b80 18.193.143.177 18.156.90.224 18.193.255.254 3.121.104.141 52.29.8.43 18.157.173.201]
Oct 28 13:51:37 carbon tailscaled[7554]: control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
Oct 28 13:51:37 carbon tailscaled[7554]: control: Generating a new nodekey.
Oct 28 13:51:37 carbon tailscaled[7554]: control: RegisterReq: onode= node=[at8y+] fup=false
Oct 28 13:51:37 carbon tailscaled[7554]: control: creating new noise client
Oct 28 13:51:47 carbon tailscaled[7554]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
Oct 28 13:51:47 carbon tailscaled[7554]: trying bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "controlplane.tailscale.com" ...
Oct 28 13:51:47 carbon tailscaled[7554]: trying bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "controlplane.tailscale.com" ...
Oct 28 13:51:47 carbon tailscaled[7554]: control: LoginInteractive -> regen=true
Oct 28 13:51:47 carbon tailscaled[7554]: control: doLogin(regen=true, hasUrl=false)
Oct 28 13:51:47 carbon tailscaled[7554]: control: Generating a new nodekey.
Oct 28 13:51:47 carbon tailscaled[7554]: control: RegisterReq: onode= node=[v3v4A] fup=false
Oct 28 13:51:48 carbon tailscaled[7554]: bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "controlplane.tailscale.com" = [2a05:d014:386:202:6dd4:fc68:35ae:2b80 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:202:24dd:46aa:f98e:9997 2a05:d014:386:202:a3e1:5be6:cbb1:1ac9 2a05:d014:386:203:4535:c15c:9ab:8258 18.156.90.224 18.193.255.254 52.29.8.43 3.121.104.141 18.157.173.201 18.193.143.177]
Oct 28 13:51:48 carbon tailscaled[7554]: bootstrapDNS("derp1c.tailscale.com", "104.248.8.210") for "controlplane.tailscale.com" = [2a05:d014:386:202:6dd4:fc68:35ae:2b80 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:202:24dd:46aa:f98e:9997 2a05:d014:386:202:a3e1:5be6:cbb1:1ac9 2a05:d014:386:203:4535:c15c:9ab:8258 18.156.90.224 18.193.255.254 52.29.8.43 3.121.104.141 18.157.173.201 18.193.143.177]
Oct 28 13:51:57 carbon tailscaled[7554]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
Oct 28 13:51:57 carbon tailscaled[7554]: trying bootstrapDNS("derp11.tailscale.com", "18.230.97.74") for "controlplane.tailscale.com" ...
Oct 28 13:51:57 carbon tailscaled[7554]: trying bootstrapDNS("derp4e.tailscale.com", "134.122.74.153") for "controlplane.tailscale.com" ...
Oct 28 13:51:57 carbon tailscaled[7554]: control: LoginInteractive -> regen=true
Oct 28 13:51:57 carbon tailscaled[7554]: control: doLogin(regen=true, hasUrl=false)
Oct 28 13:51:57 carbon tailscaled[7554]: control: Generating a new nodekey.
Oct 28 13:51:57 carbon tailscaled[7554]: control: RegisterReq: onode= node=[p2yph] fup=false
Oct 28 13:51:57 carbon tailscaled[7554]: bootstrapDNS("derp4e.tailscale.com", "134.122.74.153") for "controlplane.tailscale.com" = [2a05:d014:386:202:6dd4:fc68:35ae:2b80 2a05:d014:386:202:a3e1:5be6:cbb1:1ac9 2a05:d014:386:202:24dd:46aa:f98e:9997 2a05:d014:386:203:4535:c15c:9ab:8258 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 18.193.255.254 18.157.173.201 52.29.8.43 3.121.104.141 18.156.90.224 18.193.143.177]
Oct 28 13:51:58 carbon tailscaled[7554]: bootstrapDNS("derp11.tailscale.com", "18.230.97.74") for "controlplane.tailscale.com" = [2a05:d014:386:202:24dd:46aa:f98e:9997 2a05:d014:386:202:6dd4:fc68:35ae:2b80 2a05:d014:386:203:4535:c15c:9ab:8258 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:202:a3e1:5be6:cbb1:1ac9 18.193.255.254 18.156.90.224 3.121.104.141 18.193.143.177 18.157.173.201 52.29.8.43]
Oct 28 13:52:07 carbon tailscaled[7554]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
```

### Steps to reproduce

Run `tailscale down` or `tailscale logout` and try to login again

I have tried resetting the tailscale client and reinstalling the package. I have also cleared `/var/lib/tailscale/` manually to get rid of old state

### Are there any recent changes that introduced the issue?

No, this behaviour seems completely random

### OS

Linux

### OS version

Arch Linux  kernel 6.0.2-arch

### Tailscale version

1.32.1

### Bug report

BUG-495a217121ba33adf5c90d17c7138fb21263e9d8d9900b113a00357307310882-20221028105730Z-fb4af2b507a9d037

**Comment by siikanen** [comment]
Okay, seems like this behaviour is caused by having stale DNS entry in `/etc/resolv.conf`. Does tailscale rely on resolvconf for bootsrtapping the login process? I'm using systemd-resolved on my system and browser etc function normally, but the tailscale login cannot get the url.

This was fixed by updating `/etc/resolv.conf` to linking correctly to the systemd-resolved at `/run/systemd/resolve/stub-resolv.conf`

**Comment by siikanen** [comment]
However, I think Tailscale could fail here with some error, instead of polling loginserver forever (see the log above)

**Comment by DentonGentry** [comment]
> Does tailscale rely on resolvconf for bootsrtapping the login process? 

It will try using regular DNS first. If it cannot get connected to the coordination server that way it will try bootstrapDNS next:

`Oct 28 13:51:37 carbon tailscaled[7554]: bootstrapDNS("derp12c.tailscale.com", "149.28.119.105") for "controlplane.tailscale.com" = [2a05:d014:386:202:24dd:46aa:f98e:9997 2a05:d014:386:203:b7ba:b7d4:9703:6f8a 2a05:d014:386:202:a3e1:5be6:cbb1:1ac9 2a05:d014:386:201:7200:6340:b22f:7df6 2a05:d014:386:203:4535:c15c:9ab:8258 2a05:d014:386:202:6dd4:fc68:35ae:2b80 18.193.143.177 18.156.90.224 18.193.255.254 3.121.104.141 52.29.8.43 18.157.173.201]`

bootstrapDNS has the client ask the Tailscale DERP servers to resolve a DNS name. The bootstrapDNS succeeded and the client was able to connect to the coordination server. However the connection then closed unexpectedly:
```
Oct 28 13:51:37 carbon tailscaled[7554]: control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
...
Oct 28 13:51:47 carbon tailscaled[7554]: Received error: register request: Post "https://controlplane.tailscale.com/machine/register": connection attempts aborted by context: context deadline exceeded
```

There was more going on there than just `/etc/resolv.conf`. Something like a proxy or a firewall was actively closing the connection.

**Comment by siikanen** [comment]
> There was more going on there than just `/etc/resolv.conf`. Something like a proxy or a firewall was actively closing the connection.

There was nothing else blocking the connection, just wrong DNS address. Obviously, when trying to connect to DNS at 192.168.x.x subnet (remains of old DHCP) while being at 10.x.x.x network might not work very well. 

However the lead cause of confusion was that every other application on my machine could handle this gracefully and continued to work without an issue (Firefox, Spotify, Slack, git etc). I only noticed the issue, because of tailscale was acting weird. So I definitely think there's likely something that can be done

**Comment by darkrain42** [comment]
This is a regression introduced in tailscale 1.23.0 (ts2021 protocol?).

* In tailscale 1.22.2 and earlier (I tested various versions between 1.20.0 and 1.40.0), the bootstrapping works as expected with broken/non-existent DNS in `/etc/resolv.conf`.
* It fails in all the higher/more recent versions I tested.

Like siikanen, I can confirm there's no other network issues in play _beyond_ DNS servers that never respond to requests; network traces on my test VM generally show that the client establishes a single connection to one of the controlplane.tailscale.com IPs (fetching the control server key), but then never _attempts_ to establish another connection.

I would _guess_ that the use of fallback DNS is working properly with the 'Direct' client's httpc (which is how the control server key is retrieved), but is broken with the NoiseClient.

(See also #4845)


One interesting data-point I found while trying to reproduce this is that it only occurs if the DNS requests are entirely blackholed.  If tailscale receives an ICMP error back (promptly), that's sufficient for tailscale to actually move on to using the values from bootstrapDNS.

The ways I've encountered this:

* Put an unresponsive DNS server in /etc/resolv.conf (e.g. `echo 'nameserver 192.0.2.1' | sudo tee /etc/resolv.conf`)
* Remove /etc/resolv.conf and ensure you have no DNS resolver running on ::1 or 127.0.0.1, and then either bring down lo (`ip link set lo down`) or drop ICMP errors (`iptables -I INPUT -i lo -p icmp -j DROP -m comment --comment "Here be dragons"`)

   (That latter situation is rather pathological, but it's how I first ran into this issue.  In a Debian initramfs environment, there's no resolv.conf and 'lo' isn't brought up.)

**Comment by andrew-d** [comment]
@darkrain42 - the most recent [unstable build of Tailscale](https://pkgs.tailscale.com/unstable/#windows)–version 1.41.12 or later–contains a potential fix for this issue; would you mind testing it out when you get a moment? I was able to reproduce your issue with unresponsive DNS servers on a throwaway VM, and the fix in #8008 appears to have resolved it in my testing.

**Comment by darkrain42** [comment]
@andrew-d, yep, 1.41.12 appears to work for me.  Thanks!

I tested various situations and tailscale was able to connect to the control server in a reasonable period of time.

**Comment by DentonGentry** [comment]
Tailscale 1.42.0 contains https://github.com/tailscale/tailscale/pull/8008
I believe this is resolved now.
