### ISSUE TITLE
Menubar icon not appearing on MacBook Air M2 running Ventura

### ISSUE THREAD

**Issue by abrantley** [tailscale/tailscale#6115]
### What is the issue?

I have migrated over and have TailScale running beautifully across my home machines. I recently added an M2 MacBook Air to the mix running Ventura. As the camera notch is in the middle of the menubar, most apps move the icons to the other side of the cameras. TailScale doesn't seem to load the menubar control.

### Steps to reproduce

Download and install on M2 MacBook Air.
No menubar icon loads.

### OS

macOS

### OS version

Ventura (MacOS 13.0)

### Tailscale version

1.32.0

### Bug report

BUG-0f09caa2320e61ef83c02ab3fc08c904a604f971dd5ceeba321cce213be990b2-20221028213828Z-69321a3b6bd80196

**Comment by bradfitz** [comment]
I don't think we ask macOS to put our menu bar anywhere in particular. We just create one and macOS chooses where it goes, no? @nickoneill @mihaip?

**Comment by abrantley** [comment]
Perhaps MacOS 13.0 on M2 won't run the code or the code to create it is not completing. Where in the source do I find that coding?

**Comment by mihaip** [comment]
@abrantley the macOS client is not open source, thus there is no source for you examine. 

That being said, we're using the standard `NSStatusBar` API to draw the menu bar icon. We are not aware of any Ventura regressions with that API (@nickoneill has tested Tailscale on Ventura).

**Comment by cyandterry** [comment]
Same here with M1 Macbook Pro, after upgrading to Ventura, I cannot see the menu bar icon anymore.

**Comment by nickoneill** [comment]
Ventura seems to enjoy hiding menu items more than its predecessor. Unfortunately it doesn't seem like there's an easy way to see a list of menu items that are hidden.

You can mitigate this by either making more screen space by using a higher scaled resolution setting, or by hiding items in the menu bar that you don't use (System Settings > Control Center gives you a list of system items to hide and show). There are third-party tools to manage hiding infrequently used menu bar items as well.

**Comment by DentonGentry** [comment]
Believed to be macOS hiding menubar icons, description in https://github.com/tailscale/tailscale/issues/6115#issuecomment-1329503376

**Comment by lukeholder** [comment]
Changed my Mac OS resolution and the tailscale icon appeared back in the menubar.

**Comment by jaysqvl** [comment]
> Changed my Mac OS resolution and the tailscale icon appeared back in the menubar.

This worked for me on MacOS M2. Thanks!

**Comment by chrishanfernando** [comment]
thanks @lukeholder, worked for me also
