### ISSUE TITLE
Android: default to 8.8.8.8 if we can't detect DNS and Google Play Services (Play Store) present?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6120]
Sometimes, for whatever reason, we can't detect the DNS configuration on Android devices.

In general, we avoid using well-known DNS servers like 8.8.8.8 or 1.1.1.1 automatically, but we do in some cases already:

* if we're running on Google Cloud, we default to 8.8.8.8 (effectively; it has a different IP)
* on Azure, theirs
* on AWS, theirs
* on ChromeOS, 8.8.8.8

We could do the same thing on Android, at least in the non-F-Droid build (the one that requires that Google Play Services (Play Store) is present. In that case, defaulting to Google's DNS seems pretty reasonable, considering the user's already in that whole ecosystem.

We'd only do this if the underlying DNS can't be detected.

This would addresses failure modes like https://github.com/tailscale/tailscale/issues/6119#issuecomment-1295699856

/cc @DentonGentry @danderson @maisem

**Comment by DentonGentry** [comment]
Discussed today.
