### ISSUE TITLE
MagicDNS breaks Windows Network File and Folder Sharing

### ISSUE THREAD

**Issue by jaredlt** [tailscale/tailscale#6122]
### What is the issue?

I share a folder via Windows Network File and Folder Sharing to another Windows device on my local network. I access this via Windows File Explorer using the path `\\COMPUTERNAME\foldername`.

Once I added this computer to Tailscale I can no longer access the shared folder from the second device. I assume it's because `COMPUTERNAME` is being intercepted by MagicDNS and doesn't do it's thing?

### Steps to reproduce

- 2x Windows PCs (I'm using Windows 10 for both)
- Both connected to Tailscale
- MagicDNS enabled
- 1st PC name `SHARER`
  - Create a folder somewhere eg. `C:\share`
  - And a test file inside eg. `C:\share\test.txt`
  - Visit the directory above the `share` folder ie `C:\`
  - Right-click on the `share` folder > Properties
  - Sharing tab > Network File and Folder Sharing > Share button
  - Select your relevant user or add Everyone for easier testing
  - Share
- 2nd PC name `READER`
  - Ensure same WORKGROUP as PC 1
  - Open File Explorer and visit path `\\SHARER\share`

It will eventually time out saying it can't access.

- Disable MagicDNS
- Restart both PCs
- 2nd PC name `READER`
  - Open File Explorer and visit path `\\SHARER\share`
  - Can see `test.txt`

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.32.2

**Comment by StraightfaceStudios** [comment]
What happens if you try to ping each other using Windows ping and using tailscale ping? or Tracert? 

Also check your C:\Windows\System32\drivers\etc\hosts

I've noticed some very inconsistent host resolution after the addition of the windows hosts file changes. 

If you browse to \\Sharer'sIP\share\ does it work?

**Comment by jaredlt** [comment]
Thanks for the follow up questions.

When I created this issue I could reliably reproduce it. I've since uninstalled Tailscale on that device. Now, re-installing it and trying to reproduce again I can't even get ping to work... I do have Mullvad VPN running on the device which I disabled and closed for testing but I do wonder if something is conflicting. Through lots of restarting I managed to be able to ping one of my other devices, but not my main laptop weirdly. I did manage to get the network sharing to stop working but I'm not sure how 🤷‍♂️

I'll try and have another tinker later on to see if I can reproduce something reliably or not.

**Comment by DentonGentry** [comment]
Using Mullvad and Tailscale at the same time definitely doesn't work, and I'd agree that some sort of conflict (even disabled) is possible.

To be able to investigate we'd need a bugreport from the Windows machine at a time when Tailscale is working but File/Folder sharing is not. This is generated by holding shift while right-clicking on the Tailscale icon in the menubar and choosing Debug > Bugreport.

**Comment by DentonGentry** [comment]
At this point I don't expect to diagnose what was happening last October. An interaction with Mullvad seems likely.
