### ISSUE TITLE
Tailscale on pfSense drops packets/resets connections when used as an Exit Node

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#6127]
### What is the issue?

Connections keep getting reset/dropped when pfSense is used as an exit node from macOS.

<img width="788" alt="Screen Shot 2022-10-30 at 3 03 27 AM" src="https://user-images.githubusercontent.com/9159510/198866857-f4d366a6-fd13-48d4-be48-197a5cc78eb5.png">

### Steps to reproduce

Install tailscale on pfSense
Add One Advertised Route
Enable Advertise Exit Node
Use pfSense as an exit node from macOS 12.6.1

See these errors repeatedly:
<img width="788" alt="Screen Shot 2022-10-30 at 3 03 27 AM" src="https://user-images.githubusercontent.com/9159510/198866768-0a8c3a85-544f-4855-b8e1-45dae5a464d6.png">

### Are there any recent changes that introduced the issue?

No, has always been an issue.

### OS

macOS

### OS version

pfSense 22.05-RELEASE, macOS 12.6.1

### Tailscale version

pfSense tailscale-1.26.2, macOS 1.32.2

### Bug report

BUG-01deeb523b3f156423d6c2bef9f667b8000f4a39bb42f4f8e1d457b5fc1dedaa-20221030071204Z-fbd1c629776ea5f0

**Comment by DentonGentry** [comment]
Is this mostly with Chrome on macOS, or Safari?
https://github.com/tailscale/tailscale/issues/5425 concerns an issue which mostly impacted Chrome through a userspace-networking Tailscale exit node (which pfSense is). It is fixed in Tailscale 1.32.1 and later.

Does the pfSense plugin allow the Tailscale package within it to be updated?

**Comment by wingcomm** [comment]
@DentonGentry Yes, but it doesn't appear that there are any updated builds for FreeBSD 12.3 which is what pfSense uses.

https://forum.netgate.com/post/1059913
https://www.freshports.org/security/tailscale/

Does tailscale plan to build for FreeBSD/pfSense? I didn't see any releases here:

https://pkgs.tailscale.com/stable/

**Comment by bradfitz** [comment]
We don't do FreeBSD builds.

**Comment by wingcomm** [comment]
It looks like someone else has picked this issue apart:
https://forum.netgate.com/topic/175721/using-pfsense-as-tailscale-exit-node-only-partially-works

...and filed an issue.
https://redmine.pfsense.org/issues/13489

As it turns out @bradfitz, someone at FreeBSD is maintaining these packages, perhaps you get get his recipe for building Tailscale on FreeBSD to align your build versions across platforms on your pkgs.tailscale.com?

https://freebsd.pkgs.org/12/freebsd-aarch64/tailscale-1.32.2.pkg.html
https://freebsd.pkgs.org/12/freebsd-amd64/tailscale-1.32.2.pkg.html

**Comment by wingcomm** [comment]
This has been resolved!

https://forum.netgate.com/post/1082275
