### ISSUE TITLE
FR:  Traceroute for both ts ip addresses and subnet routes

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#6134]
### What are you trying to do?

Debug where the connection goes thru with a subnet route.
This could also be useful for finding the NAT-T path of a device with tailscale IP address 

### How should we solve this?

`tailscale traceroute` cmd

### What is the impact of not solving this?

Debugging subnet routes as well as offline clients is very hard

**Comment by bradfitz** [comment]
This is really under the purview of "tailscale ping" which already shows which Tailscale node handled an address that goes via a subnet router.

So I think this is already done?

**Comment by DentonGentry** [comment]
When sending UDP probes looking for a direct path, I suppose we could send them with small incrementing TTLs and try to do an old-school traceroute.

**Comment by charlieporth1** [comment]
> When sending UDP probes looking for a direct path, I suppose we could send them with small incrementing TTLs and try to do an old-school traceroute.

That is more so what I was looking for like it takes goes from 100.x.y.z to 100.z.y.x to 192.168.a.b which would be a TTL type

**Comment by charlieporth1** [comment]
> This is really under the purview of "tailscale ping" which already shows which Tailscale node handled an address that goes via a subnet router.
> 
> So I think this is already done?

I was unaware of that but yes it is the feature I was talking about. I'm good if this needs to be closed

**Comment by DentonGentry** [comment]
I think we'll leave it with `tailscale ping`, traceroute isn't really possible to do reliably on the modern internet.
