### ISSUE TITLE
Fedora don't received last update.

### ISSUE THREAD

**Issue by BirdInFire** [tailscale/tailscale#6139]
### What is the issue?

Despite having tried on Fedora 36 server, fedora 36 workstation and fedora 37 the last update don't appear on all these 3 device.

### Steps to reproduce

Try to update from 1.32.1 to 1.32.2 on a fedora installed device.

### Are there any recent changes that introduced the issue?

1.32.2 out

### OS

Linux

### OS version

Fedora 36 & Fedora 37

### Tailscale version

1.32.1

### Bug report

don't relevant since the fedora repo aren't liked to the app.

**Comment by elarsson1** [comment]
This appears to be the case for the Amazon Linux 2 repos as well.

**Comment by DentonGentry** [comment]
Could you try again? I just refreshed pkgs.tailscale.com's RPM packages.

**Comment by dangen-effy** [comment]
This appears to be the case for the Amazon Linux 2 repos as well.

```
[   84.663648] cloud-init[5986]: adding repo from: https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo
[   84.663994] cloud-init[5986]: grabbing file https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo to /etc/yum.repos.d/tailscale.repo
[   84.664991] cloud-init[5986]: Could not fetch/save url https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo to file /etc/yum.repos.d/tailscale.repo: [Errno 14] curl#7 - "Failed to connect to pkgs.tailscale.com port 443 after 0 ms: Connection refused"
```

**Comment by DentonGentry** [comment]
`"Failed to connect to pkgs.tailscale.com port 443 after 0 ms: Connection refused"` is something else, possibly the AWS security group blocking outbound connection?

I can fetch from https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo and get the following:
```
[tailscale-stable]
name=Tailscale stable
baseurl=https://pkgs.tailscale.com/stable/amazon-linux/2/$basearch
enabled=1
type=rpm
repo_gpgcheck=1
gpgcheck=0
gpgkey=https://pkgs.tailscale.com/stable/amazon-linux/2/repo.gpg
```

**Comment by elarsson1** [comment]
Confirmed. My Amazon Linux 2 system was able to be updated to 1.32.2. Many thanks!
