### ISSUE TITLE
Kaspersky detecting Tailscale 1.32.2 as Trojan

### ISSUE THREAD

**Issue by BlueTeam3r** [tailscale/tailscale#6146]
### What is the issue?

Can't use Tailscale VPN.

Screenshots of Kasprersky's System Watcher flagging Tailscale 1.32.2 as Trojan:
<img width="300" alt="tailscale_1_32_2_kasperskpy" src="https://user-images.githubusercontent.com/51140160/199043756-d7105dbf-65ce-44d7-ba8a-03193d4a75ca.png">

### Steps to reproduce

Download and install Tailscale 1.32.2

### Are there any recent changes that introduced the issue?

Upgraded Tailscale to version 1.32.2

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.32.2

### Bug report

BUG-c878cc2d724dd1f132b496408c4da0d6d13b708b30c77b8c8bfdb463c7c3ee8b-20221031151349Z-a84b225a280f0be8

**Comment by DentonGentry** [comment]
Our application for the Kaspersky allowlist program should be decided in about two weeks.

Regarding the malware detection of the 1.32.1 installer, they said:
> Regarding your file: We were unable to reproduce the detection. Please update your antivirus bases.
> If the problem persists, please send the screenshots showing both the filename and the verdict.
> Also please send us the trace log of the product. Here are the instructions for how to obtain trace logs https://support.kaspersky.com/common/diagnostics/12797

If you can send any of that to support@tailscale.com, we'll forward it to Kaspersky.

**Comment by BlueTeam3r** [comment]
I have chosen disinfect without reboot option.

The installer got deleted, but I was able to continue using the Tailscale version that was installed by using the executable detected and deleted by Kaspersky.
