### ISSUE TITLE
Can't login on android 9

### ISSUE THREAD

**Issue by Ebiram** [tailscale/tailscale#6149]
Hi 
On android 9 login screen not opens.
No way to connect.
Please help.

**Comment by DentonGentry** [comment]
What model of device is it?

What happens when you start the Tailscale app? Do you see the app open? Do you get a black screen?

Are you using the Play Store version of the app, or F-Droid?

**Comment by Ebiram** [comment]
I use samsung galaxy note 8 with android 9 stock.
When I start Tailscale it shows me the sign in button but when i click on it, nothing happens. just a spinner shows up and nothing.
I tried both playstore and fdroid versions.

**Comment by DentonGentry** [comment]
When you first get to a login page with "Login with Google" and "Login with Other" buttons:
- "Login with Google" will use the local Android accounts to log in
- "Login with Other" will launch a web browser, which can use any logged in accounts in your browser. Notably, Google is also one of the options.

Which one are you using? Try the other one.

If using "Login with Other", what web browser is on the device?

**Comment by Ebiram** [comment]
The problem is, when i click on "Sign in" button, nothing happens. I mean the login page with "Login with Google" and "Login with Other" buttons not showing up.
I can't see the login page with "Login with Google" and "Login with Other" buttons because it won't open.
The app will stuck when i click "Sign in" button.
There is no way to reach the login page with "Login with Google" and "Login with Other" buttons.

**Comment by DentonGentry** [comment]
Unfortunately that means it doesn't get to the point of sending telemetry we can look at to see what problem may be happening.

>only 1.6.x worked for 2 weeks and now the 1.6.x also not works.

Do you happen to know the Tailscale IP address from the two weeks where it was working?

> On android 13 (AOSP) there is no problem.

If you're able to run Android 13 on the device, that may be the most workable option. Android 9 is failing at a point where we get no information to know what it is doing.

**Comment by Ebiram** [comment]
My Tailscale IP that worked: 100.74.57.63
Unfortunately the Android 13 device is not mine.

**Comment by DentonGentry** [comment]
From the device in question:
`active login: <FIRST_NAME> ([unexpected] corp#461, not %!s(MISSING))`

When you log in on the Android device, do you:
- click the Sign in with Google button on that first screen? (which uses the Android account credentials)
- click Sign in with Other and log in via a browser? What browser?
- click Sign in with Other and log in using the GitHub Android app?

**Comment by Ebiram** [comment]
I don't know why or how but only versions 134 and 135 from fdroid worked.

> When you log in on the Android device, do you:

I use "click Sign in with Other and log in via a browser"
Chrome Browser version 106 and Chrome Dev version 108 as "Android Device Web View".

**Comment by DentonGentry** [comment]
F-Droid version 134 is what the Play Store lists as 1.32.2.
F-Droid version 135 is what the Play Store lists as 1.33.97.

These both work? You can log in?

**Comment by Ebiram** [comment]
Yes, version 1.33.97 from fdroid is now working.

**Comment by DentonGentry** [comment]
Great. I'm not sure what fixed it, but great.

**Comment by Ebiram** [comment]
Me Too!
But thank you.

**Comment by Meganium97** [comment]
I'm having this issue on 1.72 on android 14
