### ISSUE TITLE
Cannot start Tailscale on Synology DSM 7

### ISSUE THREAD

**Issue by andy47** [tailscale/tailscale#6153]
### What is the issue?

I upgraded to DSM 7 on my Synology DS920+ and the Tailscale package no longer works. I can't access it via the web or the command line and the control panel says that my NAS is offline.

### Steps to reproduce

I have manually installed the latest Tailscale package (1.32.2) onto my NAS. 

![image](https://user-images.githubusercontent.com/782758/199123627-a18e0ee8-0940-42e8-9053-1481261ea941.png)

When I click the 'Open' button a new browser tab is opened and the standard Synology 404 page is displayed.

![image](https://user-images.githubusercontent.com/782758/199123740-3141d352-3e0b-4ac1-b9cf-812e8c26b4fb.png)

I have enabled SSH access to my NAS and when I attempt any command line controls I get error messages. e.g.

```
sh-4.4$ sudo /var/packages/Tailscale/target/bin/tailscale up
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 20887). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/packages/Tailscale/etc/tailscaled.sock: connect: connection refused
```

### Are there any recent changes that introduced the issue?

Upgrade to DSM7. See https://github.com/tailscale/tailscale/issues/4648

### OS

Synology

### OS version

Synology DSM 7

### Tailscale version

1.32.2-320027

**Comment by andy47** [comment]
Specific O/S version is DSM 7.1.1-42962 Update 1

**Comment by DentonGentry** [comment]
> Upgrade to DSM7

A Tailscale package installed in DSM6 needs to be uninstalled and reinstalled before it will work in DSM7. The installer has to do various things differently between the two versions.

**Comment by andy47** [comment]
Thanks for the response. Sorry I wasn't clearer in my problem report - this problem has been present since I upgraded to DSM 7. Since that I upgrade I have removed and re-installed Tailscale several times. The last time was yesterday. I uninstalled the prior package, rebooted my NAS and installed the latest package (from https://pkgs.tailscale.com/stable/tailscale-x86_64-1.32.2-320027-dsm7.spk) using the manual file upload option. Still can't authenticate/login.

**Comment by frog158** [comment]
try - https://brutha.home.arpa.5001

**Comment by andy47** [comment]
Same response on https://brutha.home.arpa:5001

**Comment by tbc0309** [comment]
SSH or Task run the code，then reinstall.

rm -rf /usr/syno/etc/packages/Tailscale

**Comment by andy47** [comment]
Thanks, that worked like a dream. I removed the directory, re-installed the package and then I was able to authenticate and join my tailnet.

**Comment by hnk** [comment]
I am running into the same issue and have performed the steps provided by tbc0309.
Sadly still running into the same error.

I am on DSM7 (DSM 7.1.1-42962 Update 2) on a DS214play and newly installed Tailscale 1.32.2-320027 (I used the tailscale-i686-1.32.2-320027-dsm7.spk file).

@DentonGentry should I go ahead and open a new issue or should we re-open this one?

**Comment by DentonGentry** [comment]
Please open a new issue, no reason to conflate it with something that might not be the same.

**Comment by Daxh64** [comment]
> uninstall package, SSH or Task(root) run the code，then reinstall. You can also use this to solve the problem of not being able to login
> 
> DSM7 `sudo rm -rf /volume1/@appdata/Tailscale` DSM6 `sudo rm -rf /usr/syno/etc/packages/Tailscale`

Thanks that worked for me !
