### ISSUE TITLE
Nameservers don't update when renaming Tailnet

### ISSUE THREAD

**Issue by bronson** [tailscale/tailscale#6159]
### What is the issue?

When you select a new Tailnet, the page showing your DNS settings doesn't update. It's still showing the old name.

Easiest fix might be to refresh the page when the user accepts the "Rename Tailnet "dialog.

### Steps to reproduce

1. Go to https://login.tailscale.com/admin/dns and click Rename Tailnet
2. Choose a new name
3. Notice the first Nameserver in the "Nameservers" section is still showing the old name

### OS

Linux, macOS

### OS version

NixOS, MacOS

### Tailscale version

1.30.2

### Bug report

BUG-83ab1a638881123f46d914a07d227fd35b5505343044e95fcb3706086c2bf261-20221101131746Z-8afd7a7fa56c5859

**Comment by bradfitz** [comment]
cc @catzkorn @maisem
