### ISSUE TITLE
Tailscale allows hostname to be "localhost"

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#6161]
### What is the issue?

If a hostname is not specified in some distros, `/etc/hostname` is set to `localhost` which leads to the default MagicDNS name being `localhost`. We would never want this. 

I recommend adding a condition that if the hostname is `localhost` set it to something unique. Either username-XX where XX is an incremented number, or distro-XX since either `jay-01` or `fedora-01` are more descriptive. 

Alternatively, if someone can think of a case where this would be intentional, we should at least warn on `tailscale up` that the user *should* specify a hostname, as things will not work as expected. 

### OS

Linux

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/corp/pull/9098
