### ISSUE TITLE
Exit node expiry incorrectly displayed

### ISSUE THREAD

**Issue by FocusedOne** [tailscale/tailscale#6169]
### What is the issue?

In the Mac client, exit nodes which are set to 'Expiry Disabled' are marked as (expired) and greyed out / unable to select.

After selecting 'Enable Key Expiry' for a node in the web portal, it is no longer marked as expired in the Mac client and I'm able to select it as an exit node.

Changing Key Expiry for an exit node has no immediate impact in the iOS, Windows or Android clients.

### Steps to reproduce

Set an exit node to '**Expiry Disabled**'.  Then try and select it as an exit node in the Mac client.  It will appear as **(expired)** and you're unable to select it.

![tsbug1](https://user-images.githubusercontent.com/6776101/199510913-aa29808d-5e63-4e3c-a6f4-7c970eb61614.png)

Set the an exit node to **'Enable Key Expiry'**.  You're now able to select that exit node.   It's no longer **(expired)**

![tsbug2](https://user-images.githubusercontent.com/6776101/199510925-b487b8f6-ca50-4189-8779-5381aeb41542.png)

Bug report ID from a Linux exit node.

### OS version

10.13.6

### Tailscale version

1.32.2

### Bug report

BUG-11eefd995362937c751423d69e4420cc7aa3c042185fa0bb6e27e413f6a8b6df-20221102141927Z-f348607678acf2ea

**Comment by bradfitz** [comment]
Aside: the macOS client should probably ideally not be doing its own logic for graying things out and letting tailscaled do it so the logic is shared between the various clients (notably Windows)

**Comment by FocusedOne** [comment]
I just tried this on a machine running 12.6.1 (Monterey) and the Exit Node selector is functioning like it should.  This may be related to the older version of MacOS I tried it on before (10.13.6) and may not be worth fixing.

**Comment by nickoneill** [comment]
@FocusedOne that was my thought as well, we have some tests around parsing these expiration dates that are passing but perhaps they behave differently on 10.13. I'll see if I can find a VM to run them on.

**Comment by mihaip** [comment]
I wonder if the value of `Date.distantPast` changed, that is how the iOS and Mac clients decide if expiry is disabled: https://github.com/tailscale/corp/blob/9ea6766a6c25d40aef185806e51b234ed1f52b7a/xcode/Shared/IPN.swift. We should probably switch it to comparing against an explicit date.

@bradfitz there really isn't logic in `tailscaled` for this (at least that I can find), as far as I can tell the Mac and iOS clients are the only ones that check key expiration for exit nodes.

**Comment by mihaip** [comment]
Yeah, it's different.

Give this Swift snippet:

```swift
print("Date.distantPast is \(Date.distantPast)")
print("Date.distantFuture is \(Date.distantFuture)")
```

On 12.6 (and others) it outputs:

```
Date.distantPast is 0001-01-01 00:00:00 +0000
Date.distantFuture is 4001-01-01 00:00:00 +0000
```

But on 10.13 it's:

```
Date.distantPast is 0000-12-30 00:00:00 +0000
Date.distantFuture is 4001-01-01 00:00:00 +0000
```

**Comment by mihaip** [comment]
Fix will be included in the 1.34 stable release.

**Comment by kelivel** [comment]
Tailscale support— 
HS # 8397 is reporting this behavior is still happening on macOS 10.13.6 with version 1.34.2. IP: 100.65.209.117

**Comment by mihaip** [comment]
Looks like the date comparison is still not correct on macOS 10.13, investigating.

**Comment by mihaip** [comment]
Given this Swift snippet:

```swift
let GoZeroTime1 = Date(timeIntervalSince1970: -62135769600.0)
let GoZeroTime2 = String.iso8601DateFormatter.date(from: "0001-01-01T00:00:00Z")!

let dateStr = "0001-01-01T00:00:00Z"
if let date = dateStr.iso8601Date() {
    print("Parsed date: \(date)")
    print("GoZeroTime1: \(GoZeroTime1)")
    print("GoZeroTime2: \(GoZeroTime2)")
    print("==GoZeroTime1: \(date == GoZeroTime1)")
    print("==GoZeroTime2: \(date == GoZeroTime2)")
}
```

Output on macOS 12.6.2 is:
```
Parsed date: 0001-01-01 00:00:00 +0000
GoZeroTime1: 0001-01-01 00:00:00 +0000
GoZeroTime2: 0001-01-01 00:00:00 +0000
==GoZeroTime1: true
==GoZeroTime2: true
```

But on 10.13 it's:
```
Date.distantPast is 0000-12-30 00:00:00 +0000
Date.distantFuture is 4001-01-01 00:00:00 +0000
Parsed date: 0001-01-01 00:00:00 +0000
GoZeroTime1: 0000-12-30 00:00:00 +0000
GoZeroTime2: 0001-01-01 00:00:00 +0000
==GoZeroTime1: false
==GoZeroTime2: true
```

Clearly there's still some weirdness with creating of the 1/1/1 date with `timeIntervalSince1970`, will switch to more explicitly parsing the stringified version (which is what we end up comparing with)

**Comment by mihaip** [comment]
Attempt number 2 at fixing this will be in 1.36.
