### ISSUE TITLE
Client chooses suboptimal DERP region when lacking UDP connectivity

### ISSUE THREAD

**Issue by CocoXiaoLong** [tailscale/tailscale#6187]
### What are you trying to do?

There is a massive delay (Ping), when connecting to a server because tailscale routes it to a relay server around half the world.
I don't know if exit-nodes would be a tackle for that problem, but it didn't seem to get better.

### How should we solve this?

For example with an extra `--up` argument like `--use-relay [tor, ams, etc.]` <br/> 
and a context menu in windows `Relay` with a list of relay server and an extra entry with `Random` for those who want it that way.

### What is the impact of not solving this?

I don't have a workaround. <br/>
It's just taking really long to do stuff over ssh (when not scripting) and http|s

**Comment by DentonGentry** [comment]
Can you supply the `tailscale netstat` and `tailscale bugreport` output on the system which made a sub-optimal choice of relay?

**Comment by CocoXiaoLong** [comment]
You mean `netcheck`?

`Report`:
        * UDP: false
        * IPv4: (no addr found)
        * IPv6: no, but OS has support
        * MappingVariesByDestIP:
        * HairPinning:
        * PortMapping:
        * CaptivePortal: true
        * Nearest DERP: Frankfurt
        * DERP latency:
                -- fra: 8.3ms   (Frankfurt)
                -- ams: 13.3ms  (Amsterdam)
                -- lhr: 20.5ms  (London)
                -- par: 23.2ms  (Paris)
                -- waw: 26.2ms  (Warsaw)
                -- mad: 34.2ms  (Madrid)
                -- nyc: 87.1ms  (New York City)
                -- tor: 95.4ms  (Toronto)
                -- ord: 99.2ms  (Chicago)
                -- dfw: 124ms   (Dallas)
                -- mia: 125.6ms (Miami)
                -- den: 127.1ms (Denver)
                -- dbi: 127.5ms (Dubai)
                -- blr: 147ms   (Bangalore)
                -- sfo: 151.8ms (San Francisco)
                -- sea: 155.3ms (Seattle)
                -- lax: 160ms   (Los Angeles)
                -- sin: 165.5ms (Singapore)
                -- jnb: 175.8ms (Johannesburg)
                -- sao: 195.1ms (São Paulo)
                -- hnl: 205.2ms (Honolulu)
                -- tok: 242.7ms (Tokyo)
                -- syd: 259.7ms (Sydney)
                -- hkg: 262.4ms (Hong Kong)
 `bugreport`: BUG-c8819c4dbb36de7de5c9d887bdbeddc46dff3d8e8c1f2632f6ffc21181195ecf-20221103203650Z-2fa223fdb68b87b2

`machine in question (tailscale status)`: 100.122.190.64 tanso CocoXiaoLong@ linux   active; offers exit node; relay `"tor"`, tx 9016 rx 11208

**Comment by DentonGentry** [comment]
We see it shifting between DERPs, and it never picks the Frankfurt DERP which `netcheck` suggests would be optimal.

```
2022-11-03 09:44:58.012355775 +0000 UTC: magicsock: home is now derp-7 (tok)
2022-11-03 13:59:41.881925112 +0000 UTC: magicsock: home is now derp-5 (syd)
2022-11-03 14:29:04.214934457 +0000 UTC: magicsock: home is now derp-21 (tor)
```

**Comment by CocoXiaoLong** [comment]
That's why I wanted to set the DERP manually, especially if the machine in question is stationary.

**Comment by DentonGentry** [comment]
I understand that is the initial request. I'm making notes in the issue trying to determine why it picks the non-optimal derp in the first place.

**Comment by Kvoo** [comment]
So was this ever solved? I have exactly the same problem.. The Node I'm connecting to uses "hkg", the node I'm connecting from uses "fra".

Why Hong Kong?? That's nowhere NEAR where I live.

**Comment by DentonGentry** [comment]
Can you paste the output of `tailscale netcheck` ?

**Comment by Kvoo** [comment]
Of course. Do note that I have fra blocked now, Client 2 seems to be using mad instead of hkg too.

Client 1:
`Report:
        * UDP: true
        * IPv4: yes, <publicIP>:51256
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: Amsterdam
        * DERP latency:
                - ams: 16.6ms  (Amsterdam)
                - par: 24.7ms  (Paris)
                - lhr: 25.2ms  (London)
                - waw: 31.3ms  (Warsaw)
                - mad: 36.5ms  (Madrid)
                - mia: 122.8ms (Miami)
                - nyc: 125.5ms (New York City)
                - tor: 125.6ms (Toronto)
                - dbi: 125.6ms (Dubai)
                - ord: 125.6ms (Chicago)
                - dfw: 137ms   (Dallas)
                - den: 142ms   (Denver)
                - sin: 151.1ms (Singapore)
                - lax: 151.6ms (Los Angeles)
                - sea: 160ms   (Seattle)
                - sfo: 165ms   (San Francisco)
                - blr: 165.5ms (Bangalore)
                - jnb: 180.1ms (Johannesburg)
                - sao: 210.7ms (São Paulo)
                - hnl: 212.1ms (Honolulu)
                - hkg: 244.4ms (Hong Kong)
                - tok: 247.9ms (Tokyo)
                - syd:         (Sydney)

Client 2:
`Report:
        * UDP: true
        * IPv4: yes, 212.95.29.214:55708
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP: Amsterdam
        * DERP latency:
                - ams: 42.5ms  (Amsterdam)
                - lhr: 54.7ms  (London)
                - mad: 58.2ms  (Madrid)
                - waw: 62.7ms  (Warsaw)
                - nyc: 121.1ms (New York City)
                - tor: 125ms   (Toronto)
                - dbi: 140.5ms (Dubai)
                - ord: 142ms   (Chicago)
                - mia: 150.8ms (Miami)
                - dfw: 156ms   (Dallas)
                - den: 161.8ms (Denver)
                - blr: 164.8ms (Bangalore)
                - lax: 187.3ms (Los Angeles)
                - sfo: 188.3ms (San Francisco)
                - sin: 189.8ms (Singapore)
                - sea: 192.3ms (Seattle)
                - jnb: 206.9ms (Johannesburg)
                - sao: 228.4ms (São Paulo)
                - hnl: 238.4ms (Honolulu)
                - hkg: 270.2ms (Hong Kong)
                - tok: 280.6ms (Tokyo)
                - syd:         (Sydney)
                - par:         (Paris)`

**Comment by Kvoo** [comment]
That is weird.. it seems to have gone back to a direct connection now.

I've been having problems for hours, now it's suddenly fine again.

**Comment by CocoXiaoLong** [comment]
The problem still applies to me, though... It still chooses unnecessary far away derps.
```fra``` or ```ams``` would be nearer and I end up in random places like ```tok```, ```hkg``` or ```mia```.
I'm still for a manual way to choose a derp on device. Or maybe a list of "allowed derps" on the web interface.

**Comment by DentonGentry** [comment]
@CocoXiaoLong I'm looking at telemetry from nodes on your tailnet, including one which has current chosen Chicago as its home DERP. I assume that is a poor choice, the rest of the nodes on the tailnet chose a DERP in Europe.

Looking at what that node reports in its periodic assessment of what DERP to use:
```
2023-06-03 22:56:56.746992311 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:57:19.461171115 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:57:44.29473308 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:58:11.094172892 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:58:39.056573086 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:59:05.586998895 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:59:30.372791486 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
2023-06-03 22:59:57.770957818 +0000 UTC: netcheck: report: udp=false v4=false icmpv4=false v6=false v6os=true mapvarydest= hair= portmap= derp=0
```

The things to note are:
- `v4=false`, `v6=false` : it isn't able to find any of its own public IP addresses
- `derp=0` : it has no timing information about any derp server, so it picked one at random: Chicago.

--------

This is one of my nodes:
```
2023-05-31 06:23:39.090940563 +0000 UTC: netcheck: report: udp=true v6=true mapvarydest=false hair=false portmap=UMC v4a=192.184.x.y:41642 v6a=[2602:24c:x:y::]:54343 derp=2 derpdist=1v4:105ms,1v6:105ms,2v4:5ms,2v6:6ms,3v4:183ms,3v6:181ms,4v4:165ms,4v6:169ms,5v4:184ms,7v4:107ms,7v6:112ms,8v4:135ms,8v6:136ms,9v4:50ms,9v6:54ms,10v4:22ms,10v6:23ms,11v4:191ms,12v4:52ms,12v6:53ms,13v4:29ms,13v6:29ms,14v4:147ms,14v6:153ms,16v4:106ms,16v6:105ms,17v4:17ms,17v6:18ms,18v4:141ms,18v6:143ms,19v4:147ms,19v6:148ms,20v4:163ms,20v6:162ms,21v4:65ms,21v6:66ms,22v4:167ms,22v6:172ms,23v4:246ms,23v6:240ms,24v4:64ms,24v6:65ms
2023-05-31 06:23:39.344902083 +0000 UTC: netcheck: report: udp=true v6=true mapvarydest=false hair=false portmap=UMC v4a=192.184.x.y:41642 v6a=[2602:24c:x:y::]:54343 derp=2 derpdist=2v4:5ms,2v6:6ms,10v4:23ms,17v4:18ms,17v6:19ms
2023-05-31 06:23:40.068122837 +0000 UTC: netcheck: report: udp=true v6=true mapvarydest=false hair=false portmap=UMC v4a=192.184.x.y:41642 v6a=[2602:24c:x:y::]:54343 derp=2 derpdist=2v4:5ms,2v6:6ms,10v4:23ms,17v4:17ms,17v6:21ms
2023-05-31 06:23:40.440130186 +0000 UTC: netcheck: report: udp=true v6=true mapvarydest=false hair=false portmap=UMC v4a=192.184.x.y:41642 v6a=[2602:24c:x:y::]:54343 derp=2 derpdist=2v4:6ms,2v6:6ms,10v4:23ms,17v4:18ms,17v6:19ms
2023-05-31 06:23:40.691576173 +0000 UTC: netcheck: report: udp=true v6=true mapvarydest=false hair=false portmap=UMC v4a=192.184.x.y:41642 v6a=[2602:24c:x:y::]:54343 derp=2 derpdist=2v4:5ms,2v6:6ms,10v4:23ms,17v4:17ms,17v6:19ms
```

Every few minutes it exhaustively tries all DERP regions. That is the first log line, where it prints a bunch of `derpdist` results for most derp regions, with both IPv4 and IPv6.

It re-evaluates the best three regions more frequently. For me that is derp-2 (San Francisco), derp-10 (Seattle), and derp-17 (Los Angeles).

--------

We need to figure out why the node isn't able to get any information to let it pick a DERP.

**Comment by CocoXiaoLong** [comment]
That looks like a local network problem to me. My friend has the same issue and the same output on his machine, except he has his machine in `waw`. The network is sadly managed by a bunch of idiotic laymen so there is no changing settings on the firewall (which for example, has no functioning DNS and prevents icmp to the outside for every client on the network; one of the reasons I love Tailscale, eventhough it has some problems with performance on our network).

```
Report:
        * UDP: false
        * IPv4: (no addr found)
        * IPv6: no, but OS has support
        * MappingVariesByDestIP:
        * HairPinning:
        * PortMapping:
        * CaptivePortal: false
        * Nearest DERP: Frankfurt
        * DERP latency:
                - fra: 9.4ms   (Frankfurt)
                - ams: 10.8ms  (Amsterdam)
                - lhr: 18.5ms  (London)
                - par: 21.1ms  (Paris)
                - waw: 22.4ms  (Warsaw)
                - mad: 36.7ms  (Madrid)
                - nyc: 88.9ms  (New York City)
                - tor: 110.5ms (Toronto)
                - ord: 114.9ms (Chicago)
                - dbi: 125ms   (Dubai)
                - mia: 138.9ms (Miami)
                - den: 139.1ms (Denver)
                - dfw: 139.1ms (Dallas)
                - sea: 156.6ms (Seattle)
                - blr: 160.4ms (Bangalore)
                - lax: 163.6ms (Los Angeles)
                - sfo: 164ms   (San Francisco)
                - sin: 168.5ms (Singapore)
                - jnb: 175ms   (Johannesburg)
                - sao: 204ms   (São Paulo)
                - hkg: 218.7ms (Hong Kong)
                - hnl: 219.3ms (Honolulu)
                - tok: 237.9ms (Tokyo)
                - syd: 323.4ms (Sydney)
```

**Comment by CocoXiaoLong** [comment]
1. You could disable every last DERP on you Tailnet, except the one you want the node to be in. 
2.  After that you `force-reauth` so it again randomizes it location, but this time only one location is on the derpmap. After that it should have it's home DERP at that location. 

- But I don't know:  If you change DERP-Map settings back to normal, do the nodes again look for a new home? Because if not, that could be a plausible workaround, even though it's not pretty.

**Comment by Hommus** [comment]
@CocoXiaoLong How do you disable a DERP on your tailnet? I'm encountering the same issue.

**Comment by CocoXiaoLong** [comment]
# I'm sorry, *unfortunately this workaround doesn't work anymore, as Tailscale decided to block their servers from being used as custom derp server*, but here's how it would've worked

tailscale default derpmap [here](https://login.tailscale.com/derpmap/default)

## Fetch your regions nodes
You insert a custom derpmap in your acl at your [controlpanel](https://login.tailscale.com/admin/acls/file)
Here an example for Frankfurt
```json
"derpMap:Regions":
{
  "4": {
      "RegionID": 4,
      "RegionCode": "fra",
      "RegionName": "Frankfurt",
      "Nodes": [
        {
          "Name": "4f",
          "RegionID": 4,
          "HostName": "derp4f.tailscale.com",
          "IPv4": "185.40.234.219",
          "IPv6": "2a00:dd80:20::a25"
        },
        {
          "Name": "4g",
          "RegionID": 4,
          "HostName": "derp4g.tailscale.com",
          "IPv4": "185.40.234.113",
          "IPv6": "2a00:dd80:20::8f"
        },
        {
          "Name": "4h",
          "RegionID": 4,
          "HostName": "derp4h.tailscale.com",
          "IPv4": "185.40.234.77",
          "IPv6": "2a00:dd80:20::bcf"
        }
      ]
    },
}
```
## Replacing the Values
Now you replace the `RegionID` and the `JsonKey` of the whole thing with a `900`
```json
"derpMap:Regions":
{
  "900": {
      "RegionID": 900,
      "RegionCode": "fra",
      "RegionName": "Frankfurt",
      "Nodes": [
        {
          "Name": "4f",
          "RegionID": 900,
          "HostName": "derp4f.tailscale.com",
          "IPv4": "185.40.234.219",
          "IPv6": "2a00:dd80:20::a25"
        },
        {
          "Name": "4g",
          "RegionID": 900,
          "HostName": "derp4g.tailscale.com",
          "IPv4": "185.40.234.113",
          "IPv6": "2a00:dd80:20::8f"
        },
        {
          "Name": "4h",
          "RegionID": 900,
          "HostName": "derp4h.tailscale.com",
          "IPv4": "185.40.234.77",
          "IPv6": "2a00:dd80:20::bcf"
        }
      ]
    },
}
```
## Only connect with this region
You archive that by setting [`derpMap:OmitDefaultRegions`](https://tailscale.com/kb/1118/custom-derp-servers/) to `true`. this prevents your clients from connecting to any other host.

```json
{
  // ... other parts of ACL
  "derpMap": {
    "OmitDefaultRegions": true
    "Regions": {...}
  }
}
```

**Comment by CocoXiaoLong** [comment]
## This is what it tells me:
<img width="762" alt="Bildschirmfoto 2023-11-14 um 10 33 52" src="https://github.com/tailscale/tailscale/assets/51422232/a6f5adfc-4a6f-4b5f-89b6-2d20cbfda3e8">

**Comment by Hommus** [comment]
Ah no worries.
@DentonGentry Any alternative quick fixes available for this issue?

**Comment by ferox-mike** [comment]
Wanted to throw my hat in as we are also facing this same problem. Our clients seem to be randomly choosing South Africa as a DERP relay, even though we are in the upper midwest US. We geoblock on our firewall, and as the IT guy I'm not interested in opening traffic to SA permanently. The ping times are horrendous anyway, so it's not very usable. We tried to do the block DERP regions as well, but had the same problem as CocoZiaoLong did, "DERP Region 900"... etc.

**Comment by jmqd** [comment]
I have a laptop on my residential network at my home in Tokyo, and an EC2 box in NRT. Tailscale selects Amsterdam as the `DERP`, which is ~600ms latency for ssh (approximately unusable for, e.g. emacs over TRAMP).

(Both hosts show `tok` as best via `tailscale netcheck`.)

```
	* UDP: true
	* IPv4: yes, REDACTED
	* IPv6: yes, REDACTED
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping: UPnP, NAT-PMP, PCP
	* CaptivePortal: false
	* Nearest DERP: Tokyo
	* DERP latency:
		- tok: 12.7ms  (Tokyo)
		- hkg: 64.5ms  (Hong Kong)
		- sin: 92.7ms  (Singapore)
		- lax: 112.4ms (Los Angeles)
		- sfo: 114ms   (San Francisco)
		- syd: 118.4ms (Sydney)
		- sea: 133.5ms (Seattle)
		- den: 137.1ms (Denver)
		- dfw: 137.2ms (Dallas)
		- ord: 153.6ms (Chicago)
		- hnl: 155.6ms (Honolulu)
		- blr: 159ms   (Bangalore)
		- nyc: 161.2ms (New York City)
		- tor: 162.8ms (Toronto)
		- mia: 172.9ms (Miami)
		- jnb: 190.9ms (Johannesburg)
		- par: 236.3ms (Paris)
		- lhr: 243.2ms (London)
		- ams: 244.2ms (Amsterdam)
		- mad: 246.9ms (Madrid)
		- dbi: 258.5ms (Dubai)
		- waw: 258.6ms (Warsaw)
		- fra: 261.6ms (Frankfurt)
		- sao: 274.1ms (São Paulo)
		- nai: 370.2ms (Nairobi)
```

If I repeatedly `systemctl restart tailscaled` on both hosts, I can sometimes get it to choose a more favorable DERP. But once the connection goes idle, it seems to fairly reliably choose a derpy DERP and Ferdinand Magellan my packets around the globe again.

I understand the appeal of wanting to hide the choice of manually selecting a DERP region and doing it all automagically, but at this point any workaround to effectively do so would be greatly appreciated. I just want to force `tok` for my clients.

**Comment by jmqd** [comment]
I went a bit further with an experiment. I resolved the ipv4 and ipv6 for all DNS hostnames `derp*.tailscale.com`, and put an `iptable REJECT` entry for `INPUT` and `OUTPUT` for all tailscale DERP servers, except the ones I wanted (I believe `derp7*.tailscale.com` is `tokyo`, based on latency analysis.)

I got a pleasing and promising output of `tailscale netcheck`:

```
	* UDP: true
	* IPv4: yes, REDACTED
	* IPv6: yes, REDACTED
	* MappingVariesByDestIP:
	* HairPinning: false
	* PortMapping: UPnP, NAT-PMP, PCP
	* Nearest DERP: Tokyo
	* DERP latency:
		- tok: 6.7ms   (Tokyo)
		- nyc:         (New York City)
		- sfo:         (San Francisco)
		- sin:         (Singapore)
		- fra:         (Frankfurt)
		- syd:         (Sydney)
		- blr:         (Bangalore)
		- lhr:         (London)
		- dfw:         (Dallas)
		- sea:         (Seattle)
		- sao:         (São Paulo)
		- ord:         (Chicago)
		- den:         (Denver)
		- ams:         (Amsterdam)
		- jnb:         (Johannesburg)
		- mia:         (Miami)
		- lax:         (Los Angeles)
		- par:         (Paris)
		- mad:         (Madrid)
		- hkg:         (Hong Kong)
		- tor:         (Toronto)
		- waw:         (Warsaw)
		- dbi:         (Dubai)
		- hnl:         (Honolulu)
		- nai:         (Nairobi)
```

Surprisingly, when I tried to `ssh` into my ec2 box, it's still trying to use a relay that I have blocked in my iptables. Interesting, it seems to always try to use `blr` with this configuration.

```
tailscale status
```

```
REDACT OTHER DEVICE
REDACT OTHER DEVICE
REDACT OTHER DEVICE
REDACT_IP   REDACT_DEVICENAME           REDACT_USER           linux   active; relay "blr", tx 1036 rx 0
```

Obviously, the `ssh` hangs and `tailscale ping` etc. to the device timeout.

**Comment by CocoXiaoLong** [comment]
Solved it with the `derpmap`
```jsonc
{
     [...]
     "derpMap": {
		"Regions": {
			"1": null, // New York
			"2": null, // San Francisco
			"3": null, // Singapore
			// "4":  null, // Frankfurt
			"5": null, // Sydney
			"6": null, // Bangalore
			"7": null, // Tokyo
			"8":  null, // London
			"9":  null, // Dallas
			"10": null, // Seattle
			"11": null, // Sao Paulo
			"12": null, // Chicago
			"13": null, // Denver
			"14": null, // Amsterdam
			"15": null, // Johannesburg
			"16": null, // Miami
			"17": null, // Los Angeles
			"18": null, // Paris
			"19": null, // Madrid
			"20": null, // Hong Kong
			"21": null, // Toronto
			"22": null, // Warsaw
			"23": null, // Dubai
			"24": null, // Honolulu
			"25": null, // Nairobi
		},
	},
}
```
Copy the derpmap from above, and comment out the relays you want to use.
This will only enable the preferred relays for the tailnet, while setting the other regions to `null` and thus disabling them.

**Comment by CocoXiaoLong** [comment]
Agreed, I'm still for original option of adding an `--use-relay(s)` option on the client side.
Furthermore, say we have clients only in Europe, then this solution will work. 
But as soon as we have two of the clients in say North America and two in Europe, you would have to enable the relays in both regions, thus giving the nodes the freedom to select a wrong relay. (For example EU > USA > EU)

> This feels like more of a workaround then a fix. We ended up just punching holes in the firewalls which isn't great. It seems like automatic DERP selection still isn't working correctly.

As said, totally agree with workaround part and probably evenly frustrated about that.
But I'm not sure what you mean by punching holes in firewalls. I mean, I just copied every regions id and blocked them manually. To me, that feels like closing holes rather than opening them.

That said, it is in fact not an easy solution to the problem and not everyone is able to apply it (e.g. normal members of a tailscale), so I think you're right, this issue wasn't fixed for everyone.

**Comment by knaabco** [comment]
Any update on this? Our servers like to handle their connections halfway around the globe instead of choosing any of the sub 20ms european relays.

**Comment by laqua-stack** [comment]
There is an undocumented functionality in 
[dermap.go](https://github.com/tailscale/tailscale/blob/main/tailcfg/derpmap.go).
```// RegionScore scales latencies of DERP regions by a given scaling
	// factor when determining which region to use as the home
	// ("preferred") DERP. Scores in the range (0, 1) will cause this
	// region to be proportionally more preferred, and scores in the range
	// (1, ∞) will penalize a region.
	//
	// If a region is not present in this map, it is treated as having a
	// score of 1.0.
	//
	// Scores should not be 0 or negative; such scores will be ignored.
	//
	// A nil map means no change from the previous value (if any); an empty
	// non-nil map can be sent to reset all scores back to 1.0.
	RegionScore map[int]float64 `json:",omitempty"`
```
So i assume, that supplying `HomeParams` with `RegionScore`s below 1 for preferred and above 1 for unwanted regions to the ACL file could help finding the appropriate HomeDERP.
I tested it and i felt that it had some effects on the choice of DERPs. But it could of course be by accident. And still, this does not solve the issue that some machines would need DERPs in the US, while others need some in Europe.

**Comment by abdulkrim12** [comment]
> Solved it with the `derpmap`
> 
> ```js
> {
>      [...]
>      "derpMap": {
> 		"Regions": {
> 			"1": null, // New York
> 			"2": null, // San Francisco
> 			"3": null, // Singapore
> 			// "4":  null, // Frankfurt
> 			"5": null, // Sydney
> 			"6": null, // Bangalore
> 			"7": null, // Tokyo
> 			"8":  null, // London
> 			"9":  null, // Dallas
> 			"10": null, // Seattle
> 			"11": null, // Sao Paulo
> 			"12": null, // Chicago
> 			"13": null, // Denver
> 			"14": null, // Amsterdam
> 			"15": null, // Johannesburg
> 			"16": null, // Miami
> 			"17": null, // Los Angeles
> 			"18": null, // Paris
> 			"19": null, // Madrid
> 			"20": null, // Hong Kong
> 			"21": null, // Toronto
> 			"22": null, // Warsaw
> 			"23": null, // Dubai
> 			"24": null, // Honolulu
> 			"25": null, // Nairobi
> 		},
> 	},
> }
> ```
> 
> Copy the derpmap from above, and comment out the relays you want to use. This will only enable the preferred relays for the tailnet, while setting the other regions to `null` and thus disabling them.

Your the best of the best of the best many thanks to you bro this solved many problems that i have 
Big love with respect

**Comment by rgroenewoudt** [comment]
We are running into the same issue. Sao Paolo is used, even though Amsterdam is much closer.

```
P:\>tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 193.187.191.132:53495
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * PortMapping:
        * Nearest DERP: Amsterdam
        * DERP latency:
                - ams: 8.2ms   (Amsterdam)
                - lhr: 13.9ms  (London)
                - par: 18.4ms  (Paris)
                - waw: 27.3ms  (Warsaw)
                - mad: 32.8ms  (Madrid)
                - fra: 41.2ms  (Frankfurt)
                - nyc: 87.4ms  (New York City)
                - tor: 91.7ms  (Toronto)
                - ord: 106.8ms (Chicago)
                - mia: 120.8ms (Miami)
                - den: 124ms   (Denver)
                - dfw: 128.8ms (Dallas)
                - dbi: 132.3ms (Dubai)
                - sfo: 146.3ms (San Francisco)
                - blr: 153.7ms (Bangalore)
                - sea: 155.5ms (Seattle)
                - lax: 159.6ms (Los Angeles)
                - jnb: 175.6ms (Johannesburg)
                - hnl: 200ms   (Honolulu)
                - sao: 213.9ms (São Paulo)
```

**Comment by imcatwhocode** [comment]
Howdy, folks!
I faced the same issue – Tailscale always prefers Miami despite RTT to Amsterdam being four times less. Thanks, @CocoXiaoLong, for an ACL workaround!

I wrote a quick and dirty script to filter out preferred proxies so you don't have to manually write a `derpMap`. 

Check it out: https://gist.github.com/imcatwhocode/43fe66c8b4456edea1b51495bbc58629

**Comment by edran** [comment]
I'm just seeing the same issue. Closest DERP servers are `sfo` and `ord`, but tailscale decided to pick `sin` as DERP.

```
# src
Report:
	* UDP: true
	* IPv4: yes, <redacted>:10953
	* IPv6: no, but OS has support
	* MappingVariesByDestIP: true
	* PortMapping:
	* Nearest DERP: San Francisco
	* DERP latency:
		- sfo: 24.8ms  (San Francisco)
		- lax: 35.4ms  (Los Angeles)
		- sea: 40ms    (Seattle)
		- den: 53.5ms  (Denver)
		- dfw: 62ms    (Dallas)
		- mia: 87.6ms  (Miami)
		- ord: 87.7ms  (Chicago)
		- tor: 87.8ms  (Toronto)
		- hnl: 87.8ms  (Honolulu)
		- nyc: 88.5ms  (New York City)
		- tok: 122.1ms (Tokyo)
		- lhr: 157.1ms (London)
		- par: 161.9ms (Paris)
		- fra: 171.1ms (Frankfurt)
		- mad: 173.6ms (Madrid)
		- ams: 182.4ms (Amsterdam)
		- hkg: 182.6ms (Hong Kong)
		- waw: 186.6ms (Warsaw)
		- syd: 201.6ms (Sydney)
		- sin: 212.4ms (Singapore)
		- sao: 221.6ms (São Paulo)
		- blr:         (Bangalore)
		- jnb:         (Johannesburg)
		- dbi:         (Dubai)
		- nai:         (Nairobi)
		
# dst

Report:
	* UDP: false
	* IPv4: (no addr found) (note: !?)
	* IPv6: no, but OS has support
	* MappingVariesByDestIP:
	* PortMapping:
	* CaptivePortal: false
	* Nearest DERP: Chicago
	* DERP latency:
		- ord: 13.9ms  (Chicago)
		- nyc: 19.5ms  (New York City)
		- tor: 20.3ms  (Toronto)
		- dfw: 29.1ms  (Dallas)
		- den: 34.2ms  (Denver)
		- mia: 37.9ms  (Miami)
		- lax: 51.9ms  (Los Angeles)
		- sea: 62.6ms  (Seattle)
		- sfo: 63.7ms  (San Francisco)
		- par: 87.9ms  (Paris)
		- hnl: 96.9ms  (Honolulu)
		- lhr: 99.5ms  (London)
		- ams: 102.5ms (Amsterdam)
		- mad: 103.8ms (Madrid)
		- waw: 111.1ms (Warsaw)
		- sao: 135.2ms (São Paulo)
		- tok: 147.7ms (Tokyo)
		- dbi: 199.4ms (Dubai)
		- blr: 217.3ms (Bangalore)
		- hkg: 226.7ms (Hong Kong)
		- sin: 230.6ms (Singapore)
		- fra: 246.5ms (Frankfurt)
		- jnb: 262.1ms (Johannesburg)
		- syd: 269.5ms (Sydney)
		- nai: 293.6ms (Nairobi)
```

**Comment by jwhited** [comment]
[Unstable (1.75.12+)](https://tailscale.com/kb/1083/install-unstable) has a number of fixes for clients lacking UDP connectivity (`UDP: false` in netcheck output) that was leading to suboptimal DERP home region selection.

**Comment by jwhited** [comment]
1.76+ greatly improves DERP home region selection when the client is lacking UDP connectivity:

https://tailscale.com/changelog#2024-10-10
> Clients lacking UDP connectivity no longer skip performing fallback latency measurements with [DERP servers](https://tailscale.com/kb/1232/derp-servers).

Please open a new issue if you are running a client version >= 1.76 and still believe home region selection is suboptimal.

**Comment by Steven52065** [comment]
> There is an undocumented functionality in [dermap.go](https://github.com/tailscale/tailscale/blob/main/tailcfg/derpmap.go).
> 
> ```
> 	// RegionScore scales latencies of DERP regions by a given scaling
> 	// factor when determining which region to use as the home
> 	// ("preferred") DERP. Scores in the range (0, 1) will cause this
> 	// region to be proportionally more preferred, and scores in the range
> 	// (1, ∞) will penalize a region.
> 	//
> 	// If a region is not present in this map, it is treated as having a
> 	// score of 1.0.
> 	//
> 	// Scores should not be 0 or negative; such scores will be ignored.
> 	//
> 	// A nil map means no change from the previous value (if any); an empty
> 	// non-nil map can be sent to reset all scores back to 1.0.
> 	RegionScore map[int]float64 `json:",omitempty"`
> ```
> 
> So i assume, that supplying `HomeParams` with `RegionScore`s below 1 for preferred and above 1 for unwanted regions to the ACL file could help finding the appropriate HomeDERP. I tested it and i felt that it had some effects on the choice of DERPs. But it could of course be by accident. And still, this does not solve the issue that some machines would need DERPs in the US, while others need some in Europe.

Hello, how do I set RegionScore?
I set it in Access Controls, but it prompts
`Error: json: unknown field "RegionScore"`
This is my configuration, I hope you can give me some advice
```
"derpMap": {
		"Regions": {
			"900": {
				"RegionID":   900,
				"RegionCode": "aa",
				"RegionName": "JP IIJ",
				"RegionScore": 0.1,
				"Nodes": [
					{
						"Name":             "JP IIJ",
						"RegionID":         900,
						"HostName":         "a.com",
						"DERPPort":         11000,
						"STUNPort":         3478,
						"InsecureForTests": true,
					},
				],
			},
		},
	},
```
