### ISSUE TITLE
FR: MagicDNS Advanced Configuration (+Additional Questions)

### ISSUE THREAD

**Issue by jtcressy** [tailscale/tailscale#6204]
### What are you trying to do?

A question about MagicDNS prefaces this entire FR:

Are queries to 100.100.100.100 evaluated _locally_ in the tailscaled daemon against the map of peers? If so, this proposal may make some sense. 

---
So, there have been LOTS of other issues filed about the ability to create dns entries for all kinds of stuff on our tailnets, such as ones usually closed with the solution "use split dns with search domains". There's also been lots of issues concerning load-balancing services that are exposed internally to the tailnet, of which tsnet is covering many of these use cases.

However I think I may have a rare/edge use case that isn't easily resolved with split dns +search or tsnet. My requirements include fast round-robin to multiple replicas of a service using a single stable dns name _instead of_ laggy failover (such as HA subnet routers).

<details><summary>Long-winded context lies here</summary>
If I'm running common off-the-shelf software as services in my tailnet that may or may not be written in golang, it's not trivial to use tsnet to expose that service. I'd have to run a sidecar proxy with tsnet baked in, or run a tertiary DNS server to point to as a split dns server. 

If I want to round-robin several replicas of this service on my tailnet, the tertiary DNS could help with this by returning a multi-answer DNS query with the A records randomized. But this tertiary DNS server is now, annoyingly, a pet amongst my cattle service replicas.

If I tried to use tsnet in multiple servers, they can't all identify as the same device on the tailnet. each one has to have its own hostname, so this does not satisfy the requirement of a single stable dns name. It would have to be one instance tsnet that has to migrate between replicas of my service, reacting to failures. because it has to stop and start, there is a significant period of time that the service is now unavailable. Additionally, traffic was only ever going to one replica instead of actually being load-balanced.
</details>

### How should we solve this?

Here comes the crazy proposal:

What if we embed CoreDNS in tailscaled to serve queries sent to quad100? Any existing MagicDNS functionally could be combined, AND this grants us the opportunity to expose a Corefile-like configuration interface so that tailscale users can implement advanced DNS configurations alongside MagicDNS. Much like the tailnet ACL file, a single Corefile in the MagicDNS tab on the tailscale admin portal could enable users with advanced configuration options.

### What is the impact of not solving this?

see the "Anything else?" section

### Anything else?

Some community projects that combine CoreDNS and Tailscale already:

https://github.com/damomurf/coredns-tailscale (and my fork: https://github.com/jtcressy-home/coredns-tailscale)

My fork of the above project enables dns-loadbalancing in CoreDNS by tagging multiple nodes with the same tag and having CoreDNS reply with a multi-answer with A records from each node tagged with the same tag _and randomizing the list of IP's_

This, so far, is enough to get the desired results but this only works if i'm running CoreDNS as a tertiary server (or as a local daemon exposed as 127.0.0.1:53 on every machine)

Example Corefile below:
```
tailscale.internal:53 {
  errors
  log
  tailscale tailscale.internal {
    poll_interval 15s
  }
  loadbalance
}

.:53 {
  errors
  log
  health :8053
  prometheus localhost:9153
  forward ts.net 100.100.100.100
  forward tailscale.net 100.100.100.100
  forward . 100.100.100.100 9.9.9.9 8.8.8.8 1.1.1.1
  cache 30
}
```

**Comment by bradfitz** [comment]
Yes, MagicDNS is resolved locally.

There have been a number of requests like this. There's a lot of related stuff we'd like to do, injecting names into MagicDNS, synthesizing names from other things (client-directed load balancing for nearest replica, etc), service names (everything with same tag, etc). We're starting to work towards some of that.

Pretty sure we have existing bugs open tracking those things already, though. I'll see if we can find them and cross-reference them here.

(I'm ignoring the implementation detail of embedding CoreDNS because that's a bit of a distraction; I'd prefer the bug focus on the problem/use case instead)

**Comment by jtcressy** [comment]
> (I'm ignoring the implementation detail of embedding CoreDNS because that's a bit of a distraction; I'd prefer the bug focus on the problem/use case instead)

My ticket may be redundant then. I didn't mean to open yet another "dns isn't working for me because X" issue. I just wanted to see if an embedded CoreDNS was relevant, or if it's a non-starter from a licensing or complexity standpoint.

**Comment by DentonGentry** [comment]
I think at this point the issue will still be discoverable if closed, for people looking for context.
