### ISSUE TITLE
Admin Console: When creating an ACL-Tag for port 53, the Services (alpha) ACL-Information page breaks

### ISSUE THREAD

**Issue by SaturnHafen** [tailscale/tailscale#6205]
### What is the issue?

When hovering over the ACL information in the *Services (alpha)* section, the page crashes:
![image](https://user-images.githubusercontent.com/37272151/200143557-e1259096-03e4-470b-8860-977925de7879.png)
![image](https://user-images.githubusercontent.com/37272151/200143600-6096e3cd-e278-4bad-b672-ddb7cc7ff1d1.png)

I would expect that the page displays a popout with (correct) acl information.

Screencast:
![bug-tailscale](https://user-images.githubusercontent.com/37272151/200143777-21dcce31-f771-4ea9-8c62-0c8add331b3c.gif)

(Note: DNS works without any problem even with this bug)
(Another Note: All the other ACL-Information popouts work without a problem)

### Steps to reproduce

1. Enable *services collection*
2. Create an acl-tag to allow access to port 53 e.g. `{"action": "accept", "dst": ["tag:dns-access:53"]},`
3. Apply this tag to a machine
4. On the maschine-specific page in the *services (alpha)* section hover over the **(i)** next to *systemd-resolved* *DNS*
5. The page crashes

(Without the acl-tag everything works as expected)

### OS

Linux, Other

### Bug report

BUG-1d41451bafbaae94645641b01603c8bfc74ebc1a3c171ad9522b62d7289abf04-20221105223447Z-c145345c202cf9f9

**Comment by bradfitz** [comment]
cc @tailscale/frontend

**Comment by mihaip** [comment]
Looks like this corresponds to these reports in Sentry: https://sentry.io/organizations/tailscale/issues/3721778167

**Comment by phirework** [comment]
I'm not able to replicate this. What do you see if you go to http://localhost:31544/admin/acls, click on "Preview Rules", and select `tag:dns-accept` from the list?

**Comment by SaturnHafen** [comment]
You probably mean <https://login.tailscale.com/admin/acls> right?
It shows

> **No ACL rules matched**
> tag:dns-access cannot access any ports on the network.

To be fair: I was just experimenting with the acl rules.

**Comment by mihaip** [comment]
This turns out be because the ACL rule was not fully populated (`{"action": "accept", "dst": ["tag:dns-access:53"]}` was missing a `src`) and it turned into a `null` value that the code was not expected. Will add some more guards to make sure the `null`s don't happen.
