### ISSUE TITLE
containerboot doesn't handle `--state=` and `--statedir=` simultaneously

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#6211]
Some sites use `run.sh` with a `--statedir=` argument to handle where to store TLS certificates and a `--state=` argument to put the tailscaled.state in the k8s secrets manager.

--------

_Originally posted by @OGKevin in https://github.com/tailscale/tailscale/issues/4837#issuecomment-1304764069_

I run the following sidecar: 

```
  ts-sidecar:
    Container ID:   containerd://e87205e22c690d9011c4d52166dcd26632d02ce92cc77cfac69701e76dea58cc
    Image:          ghcr.io/tailscale/tailscale:v1.33.132@sha256:766629890b2ce668b78ab880d813ea3059f85d634ec6ba079014bcb2d9d1316a
    Image ID:       ghcr.io/tailscale/tailscale@sha256:766629890b2ce668b78ab880d813ea3059f85d634ec6ba079014bcb2d9d1316a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sun, 06 Nov 2022 10:53:52 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      TS_TAILSCALED_EXTRA_ARGS:  --state=mem
      TS_USERSPACE:              false
      TS_AUTH_KEY:               <set to the key 'TS_AUTH_KEY' in secret 'tailscale-auth'>  Optional: false
```

Which ran fine, until upgrading to ` v1.33.141`. 

```
2022/11/06 09:39:23 Program starting: v1.33.141-tbb2cba0cd, Go 1.19.2-ts3fd24dee31: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:tailscale", "--statedir=/tmp", "--state=mem"}
```

Would still try to store the state in k8s secret, while `v1.33.132` seemed to ignore the first appearance of `--state` arg. 
Unfortunately this is hardcoded https://github.com/tailscale/tailscale/blob/da8def8e13d44df0c4183300c826523ba933cb37/cmd/containerboot/main.go#L265 😔 

I did not check the changelog between these 2 versions though.
But worst case, I would need to create a fork and remove the hardcoded state arg.

**Comment by danderson** [comment]
Woops, my mistake. Containerboot intends to be feature-for-feature/bug-for-bug compatible with the old shell script. I just didn't know that we'd somehow ended up with this hybrid universe of storing some stuff in secrets and some stuff outside.

**Comment by danderson** [comment]
Hmm, I'm not immediately seeing where the behavior change happened. Both run.sh and containerboot end up passing the same two --state args to tailscaled, in the same order. That _should_ result in the same behavior, but somehow doesn't...

**Comment by danderson** [comment]
I kicked off a new unstable build, a fixed container image should show up in the next ~1h or so. Thanks for the report @OGKevin!
