### ISSUE TITLE
containerboot panics outside of kubernetes

### ISSUE THREAD

**Issue by e-nikolov** [tailscale/tailscale#6218]
### What is the issue?

I tried running tailscale as a container using docker-compose
```yaml
version: "3"
services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.33.141
    volumes:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    environment:
      - TS_AUTH_KEY=...
```

and got this panic:

```
docker-tailscale-1  | boot: 2022/11/07 18:30:01 Starting tailscaled
docker-tailscale-1  | boot: 2022/11/07 18:30:01 Waiting for tailscaled socket
docker-tailscale-1  | boot: 2022/11/07 18:30:01 Running 'tailscale up'
docker-tailscale-1  | 2022/11/07 18:30:01 logtail started
docker-tailscale-1  | 2022/11/07 18:30:01 Program starting: v1.33.141-tbb2cba0cd, Go 1.19.2-ts3fd24dee31: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=mem:", "--statedir=/tmp", "--tun=userspace-networking"}
docker-tailscale-1  | 2022/11/07 18:30:01 LogID: 35d5de41c61a05e4caca14b48bc8dcf0c25816efc5b09d2f1325ad9ba13f6b30
docker-tailscale-1  | 2022/11/07 18:30:01 logpolicy: using system state directory "/var/lib/tailscale"
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine.NewUserspaceEngine(tun "userspace-networking") ...
docker-tailscale-1  | 2022/11/07 18:30:01 dns: using dns.noopManager
docker-tailscale-1  | 2022/11/07 18:30:01 link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[172.18.0.2/16]} v4=true v6=false}
docker-tailscale-1  | 2022/11/07 18:30:01 magicsock: disco key = d:16a433a2fd8dacc2
docker-tailscale-1  | 2022/11/07 18:30:01 Creating WireGuard device...
docker-tailscale-1  | 2022/11/07 18:30:01 Bringing WireGuard device up...
docker-tailscale-1  | 2022/11/07 18:30:01 Bringing router up...
docker-tailscale-1  | 2022/11/07 18:30:01 Clearing router settings...
docker-tailscale-1  | 2022/11/07 18:30:01 Starting link monitor...
docker-tailscale-1  | 2022/11/07 18:30:01 Engine created.
docker-tailscale-1  | 2022/11/07 18:30:01 Start
docker-tailscale-1  | 2022/11/07 18:30:01 using backend prefs; created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
docker-tailscale-1  | 2022/11/07 18:30:01 generating new network-lock key
docker-tailscale-1  | 2022/11/07 18:30:01 network-lock key written to store
docker-tailscale-1  | 2022/11/07 18:30:01 Backend: logs: be:35d5de41c61a05e4caca14b48bc8dcf0c25816efc5b09d2f1325ad9ba13f6b30 fe:
docker-tailscale-1  | 2022/11/07 18:30:01 Switching ipn state NoState -> NeedsLogin (WantRunning=0xac8720, nm=false)
docker-tailscale-1  | 2022/11/07 18:30:01 blockEngineUpdates(true)
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine: Reconfig: configuring router
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine: Reconfig: configuring DNS
docker-tailscale-1  | 2022/11/07 18:30:01 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
docker-tailscale-1  | 2022/11/07 18:30:01 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
docker-tailscale-1  | 2022/11/07 18:30:01 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
docker-tailscale-1  | 2022/11/07 18:30:01 health("overall"): error: state=NeedsLogin, wantRunning=false
docker-tailscale-1  | 2022/11/07 18:30:01 ipnserver: conn2: connection from userid 0; root has access
docker-tailscale-1  | 2022/11/07 18:30:01 Start
docker-tailscale-1  | 2022/11/07 18:30:01 control: client.Shutdown()
docker-tailscale-1  | 2022/11/07 18:30:01 control: client.Shutdown: inSendStatus=0
docker-tailscale-1  | 2022/11/07 18:30:01 control: mapRoutine: quit
docker-tailscale-1  | 2022/11/07 18:30:01 control: Client.Shutdown done.
docker-tailscale-1  | 2022/11/07 18:30:01 using backend prefs; created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
docker-tailscale-1  | 2022/11/07 18:30:01 generating new machine key
docker-tailscale-1  | 2022/11/07 18:30:01 machine key written to store
docker-tailscale-1  | 2022/11/07 18:30:01 Backend: logs: be:35d5de41c61a05e4caca14b48bc8dcf0c25816efc5b09d2f1325ad9ba13f6b30 fe:
docker-tailscale-1  | 2022/11/07 18:30:01 Switching ipn state NoState -> NeedsLogin (WantRunning=0xac8720, nm=false)
docker-tailscale-1  | 2022/11/07 18:30:01 blockEngineUpdates(true)
docker-tailscale-1  | 2022/11/07 18:30:01 StartLoginInteractive: url=false
docker-tailscale-1  | 2022/11/07 18:30:01 control: client.Login(false, 6)
docker-tailscale-1  | 2022/11/07 18:30:01 control: LoginInteractive -> regen=true
docker-tailscale-1  | 2022/11/07 18:30:01 control: doLogin(regen=true, hasUrl=false)
docker-tailscale-1  | 2022/11/07 18:30:01 control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
docker-tailscale-1  | 2022/11/07 18:30:01 control: Generating a new nodekey.
docker-tailscale-1  | 2022/11/07 18:30:01 control: RegisterReq: onode= node=[KY8Am] fup=false nks=false
docker-tailscale-1  | 2022/11/07 18:30:01 control: creating new noise client
docker-tailscale-1  | 2022/11/07 18:30:01 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
docker-tailscale-1  | 2022/11/07 18:30:01 blockEngineUpdates(false)
docker-tailscale-1  | 2022/11/07 18:30:01 control: netmap: got new dial plan from control
docker-tailscale-1  | 2022/11/07 18:30:01 active login: de60bcd5169b-2.tail1ff4d.ts.net
docker-tailscale-1  | 2022/11/07 18:30:01 Switching ipn state NeedsLogin -> Starting (WantRunning=0xac8720, nm=true)
docker-tailscale-1  | 2022/11/07 18:30:01 magicsock: SetPrivateKey called (init)
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine: Reconfig: configuring userspace WireGuard config (with 0/14 peers)
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine: Reconfig: configuring router
docker-tailscale-1  | 2022/11/07 18:30:01 wgengine: Reconfig: configuring DNS
docker-tailscale-1  | 2022/11/07 18:30:01 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:29}
docker-tailscale-1  | 2022/11/07 18:30:01 dns: Resolvercfg: {Routes:{} Hosts:29 LocalDomains:[]}
docker-tailscale-1  | 2022/11/07 18:30:01 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
docker-tailscale-1  | 2022/11/07 18:30:01 peerapi: serving on http://100.93.165.246:64372
docker-tailscale-1  | 2022/11/07 18:30:01 peerapi: serving on http://[fd7a:115c:a1e0:efe3::645d:a5f6]:64372
docker-tailscale-1  | 2022/11/07 18:30:02 magicsock: home is now derp-14 (ams)
docker-tailscale-1  | 2022/11/07 18:30:02 magicsock: adding connection to derp-14 for home-keep-alive
docker-tailscale-1  | 2022/11/07 18:30:02 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false ipv6os=false udp=true icmpv4=false derp=#14 portmap= link=""}
docker-tailscale-1  | 2022/11/07 18:30:02 magicsock: 1 active derp conns: derp-14=cr0s,wr0s
docker-tailscale-1  | 2022/11/07 18:30:02 magicsock: endpoints changed: 31.201.251.88:45623 (stun), 172.18.0.2:45623 (local)
docker-tailscale-1  | 2022/11/07 18:30:02 derphttp.Client.Connect: connecting to derp-14 (ams)
docker-tailscale-1  | 2022/11/07 18:30:02 Switching ipn state Starting -> Running (WantRunning=0xac8720, nm=true)
docker-tailscale-1  | 2022/11/07 18:30:02 ipnserver: conn2: ReadMsg: read unix /tmp/tailscaled.sock->@: read: connection reset by peer
docker-tailscale-1  | panic: not in kubernetes
docker-tailscale-1  | 
docker-tailscale-1  | goroutine 1 [running]:
docker-tailscale-1  | main.doKubeRequest({0x6bd240?, 0xc0000a0a50?}, 0xc00022e000)
docker-tailscale-1  |   tailscale.com/cmd/containerboot/kube.go:174 +0x2fe
docker-tailscale-1  | main.storeDeviceID({0x7629c8, 0xc0001021e0}, {0x6dfe43, 0x9}, {0xc0000aee80, 0xc})
docker-tailscale-1  |   tailscale.com/cmd/containerboot/kube.go:87 +0x30f
docker-tailscale-1  | main.main()
docker-tailscale-1  |   tailscale.com/cmd/containerboot/main.go:138 +0x814
```

Could it be because cfg.KubeSecret  has a default value?
https://github.com/tailscale/tailscale/blob/da8def8e13d44df0c4183300c826523ba933cb37/cmd/containerboot/main.go#L79

Which is then checked and it tries to do some kube related stuff regardless if it's inside k8s or not:
https://github.com/tailscale/tailscale/blob/da8def8e13d44df0c4183300c826523ba933cb37/cmd/containerboot/main.go#L136-L139

**Comment by danderson** [comment]
Thanks for the report. Yes, the codepath you pointed at is missing a conditional for being in k8s before attempting this. I'll get a fix out shortly, in the meantime using tag `v1.33.132` will revert to a working image (or use the `stable` tag to pin the latest stable, odd-numbered versions like 1.33.x are unstable builds).

**Comment by Ornias1993** [comment]
> Thanks for the report. Yes, the codepath you pointed at is missing a conditional for being in k8s before attempting this. I'll get a fix out shortly, in the meantime using tag `v1.33.132` will revert to a working image (or use the `stable` tag to pin the latest stable, odd-numbered versions like 1.33.x are unstable builds).


this versioning is weird and super non-standard... definately not semver or calver... Might I suggest using some sort of standard here?

To be fair, i've seen worse... but stilll...

**Comment by Ornias1993** [comment]
> Thanks for the report. Yes, the codepath you pointed at is missing a conditional for being in k8s before attempting this. I'll get a fix out shortly, in the meantime using tag `v1.33.132` will revert to a working image (or use the `stable` tag to pin the latest stable, odd-numbered versions like 1.33.x are unstable builds).


this versioning is weird and super non-standard... definately not semver or calver... Might I suggest using some sort of standard here?

To be fair, i've seen worse... but stilll...

**Comment by DentonGentry** [comment]
>this versioning is weird and super non-standard... definately not semver or calver... Might I suggest using some sort of standard here?

If you're referring to `1.33.132`, it is intended to resemble Linux kernel version numbering with odd numbered dev releases and even numbered stable releases.

**Comment by Ornias1993** [comment]
> > this versioning is weird and super non-standard... definately not semver or calver... Might I suggest using some sort of standard here?
> 
> If you're referring to `1.33.132`, it is intended to resemble Linux kernel version numbering with odd numbered dev releases and even numbered stable releases.

Okey, that's... an odd choice indeed...
Like: this versioning is almost never used outside of the linux kernel and in the container world basically totally unheard off.

Simply put: No one grabbing the contain is going to realise that this is a dev version and all available auto-update tools like renovate are going to assume it's semver.

**Comment by DentonGentry** [comment]
https://hub.docker.com/r/tailscale/tailscale
`stable` and `latest` retrieve the most recent released tailscale version, not dev versions.

`unstable` will retrieve the latest dev version. If you specify a specific version you'll get whatever version you specify, stable or dev as appropriate.

> Simply put: No one grabbing the contain is going to realise that this is a dev version and all available auto-update tools like renovate are going to assume it's semver.

Using `latest` does what people expect. You get the most recent released software version.

**Comment by Ornias1993** [comment]
"Friends do not let friends use latest"
(same goes for stable)

Basically you've a "bad" versioning practice (lets assume , for a second that, non-standard, unique among thousands of pieces of software is bad) and in response... advice picking the even worse practice of using latest tags for containers...

People are expecting something like semver, calver, single-increasing0digit or maybe even "collabora-ver" (which is, in fact far worse than your practice btw, but less so on the "user expects" front).

But I would like to stay open minded on this though, so:
Who came up with the idea to use a versioning scheme that has been not-really-in-use (outside of the kernel) since the 90's and why? Like, what's so great about this, to ignore best practices and generally accepted versioning schemes?

The "who" question here, is not intended to shame anyone. More like: Is it someone that has no development experience outside of the Linux kernel or something, because that would make it more understandable... for example....

**Comment by DentonGentry** [comment]
> Who came up with the idea

This is proceeding in a direction which I do not believe is productive, and which I am not willing to entertain discussion of.

If you'd like to talk about what Tailscale might change, you can email info@tailscale.com and I'll respond with a calendly link to set up a time to talk.

**Comment by Ornias1993** [comment]
> > Who came up with the idea
> 
> This is proceeding in a direction which I do not believe is productive, and which I am not willing to entertain discussion of.
> 
> If you'd like to talk about what Tailscale might change, you can email [info@tailscale.com](mailto:info@tailscale.com) and I'll respond with a calendly link to set up a time to talk.

The direction I want this to go, is making clear that this choice is just _super_ weird.

Within 15(!) minutes of looking into the versioning, me and my fellow maintainers came across a multitude of users confused by this versioning scheme.

I, sadly enough, don't have time to plan talks about basic development best-practices. Above is all you need to know. Including the consequences for downstreams like us.

I just **_HEAVILY_** suggest you to reconsider and picking semver, calver or similair instead.
Byond that it's up to you.
