### ISSUE TITLE
Update Available 1.0.0 Windows?

### ISSUE THREAD

**Issue by pomazanbohdan** [tailscale/tailscale#622]
Admin console  write "Update Available" for windows pc.
Now 0.100.0-107

**Comment by crawshaw** [comment]
The 1.0 release was temporarily unreleased due to some bugs. A new version will be out in a couple days.

**Comment by pomazanbohdan** [comment]
https://github.com/tailscale/tailscale/issues/610

**Comment by bradfitz** [comment]
The release-and-unrelease confused the admin dashboard's caching of which releases are available.

But the cache expired and it's correct now, not recommending the errant release anymore.
