### ISSUE TITLE
cmd/containerboot - provide flag to disable IPv6 on container.

### ISSUE THREAD

**Issue by stavros-k** [tailscale/tailscale#6221]
### What is the issue?

With the new containerboot, users of tailscale container are forced to have `net.ipv6.conf.all.forwarding` set, even if they don't use ipv6 in their systems.

Please provide a flag to disable ipv6.
Or don't fail, just print a warning.

```
022-11-07 22:27:57.988637+00:00boot: 2022/11/07 22:27:57 Failed to enable IP forwarding: enabling "/proc/sys/net/ipv6/conf/all/forwarding": open /proc/sys/net/ipv6/conf/all/forwarding: read-only file system
2022-11-07 22:27:57.988657+00:00boot: 2022/11/07 22:27:57 To run tailscale as a proxy or router container, IP forwarding must be enabled.
2022-11-07 22:27:57.988661+00:00boot: 2022/11/07 22:27:57 You can either set the sysctls as a privileged initContainer, or run the tailscale container with privileged=true.
```

### Steps to reproduce

Install tailscale with auth key and routes env set

### Are there any recent changes that introduced the issue?

containerboot binary introduced

### OS

Other

### OS version

TrueNAS Scale / K3S

### Tailscale version

1.33.141

**Comment by danderson** [comment]
Thanks for the report. I've made the check more specific in a way that the container will still fail to start if subnets/proxying would be actually broken without the sysctls, but that should address the case you have. I'm building a new container image now, it should show up shortly. In the meantime, you can use the `v1.33.132` tag as a workaround, or the `stable` tag whch is pinned to the latest stable release (1.33.x are unstable builds).
