### ISSUE TITLE
docs/k8s/role.yaml requires `patch` verb as well

### ISSUE THREAD

**Issue by stavros-k** [tailscale/tailscale#6225]
### What is the issue?

Container boot does a `PATCH` request to k8s api, which according to k8s docs requires the `patch` verb on the role

https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-the-request-verb

https://github.com/tailscale/tailscale/blob/5bb7e0307c2e6c7c7e676fb3acaf54c98aa190cc/cmd/containerboot/kube.go#L98

https://github.com/tailscale/tailscale/blob/5bb7e0307c2e6c7c7e676fb3acaf54c98aa190cc/docs/k8s/role.yaml#L16

### OS

Other

### OS version

TrueNAS Scale / K3S

### Tailscale version

1.33.148

**Comment by danderson** [comment]
Hmm, strange. I've been testing with the role.yaml in our repo, and patching the secret worked fine... Maybe `update` implicitly includes patching in practice? Either way, should make it explicit.

**Comment by stavros-k** [comment]
> Hmm, strange. I've been testing with the role.yaml in our repo, and patching the secret worked fine... Maybe `update` implicitly includes patching in practice? Either way, should make it explicit.

I thought that too, but was getting 403's until I added `patch` aswell.

Thanks for the quick fixes
