### ISSUE TITLE
Admin panel reports "update available" even after that update is removed

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#623]
Steps:
1. Release v1.0.0 to stable and regenerate the pkgs.tailscale.com index
2. Notice that admin panel tells people to upgrade to v1.0.0
3. Find a serious bug in v1.0.0
4. Unrelease v1.0.0 and regenerate the pkgs.tailscale.com index

Expected:
Admin panel no longer says 0.100.0-153 nodes are outdated.

Actual:

Bug 1: Admin panel says 0.100.0-153 nodes are outdated even though they no longer are

Bug 2: the mouseover message tells you the version you *are* running, but what you want to know is the version it *thinks* you should be running.

**Comment by apenwarr** [comment]
This is affecting customers who are already concerned about the misleading "update available" tag.

**Comment by rosszurowski** [comment]
This is because we cache version information for [5 hours](https://github.com/tailscale/corp/blob/main/control/adminhttp/adminhttp.go#L185), because our Apple/iOS checks are a little expensive. If you look now, it's up-to-date. We can lower that cache value if this feels too high, but this seems like a one-off issue of our release to stable than an admin panel bug.

The "hover over the badge" probably isn't being noticed by many, but I'll update the text to include the latest expected stable version.

**Comment by bradfitz** [comment]
Yeah, probably nothing to do here, as un-releasing released builds shouldn't be a common thing we do.

If we do it again in the future, we can restart control.

**Comment by apenwarr** [comment]
We could ping a refresh URL the same way we do with the pkgs.tailscale.com server, right?

"shouldn't be a common thing we do" isn't very satisfying when you have 5 hours of every single user getting pestered to do nonexistent upgrades. It makes us look dumb.

**Comment by bradfitz** [comment]
I'd rather just reduce 5 hours to 5 minutes for all but the Apple checks.

Easier than building a new handler & figuring out auth for it & building a client for it (or having users furiously remembering curl flags during an emergency rollback)

**Comment by apenwarr** [comment]
Sure, sounds fine. Apple won't let us go backwards anyway (sigh)

On Thu, Jul 30, 2020 at 2:54 PM Brad Fitzpatrick
<notifications@github.com> wrote:
>
> I'd rather just reduce 5 hours to 5 minutes for all but the Apple checks.
>
> Easier than building a new handler & figuring out auth for it & building a client for it (or having users furiously remembering curl flags during an emergency rollback)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale
