### ISSUE TITLE
FR: ubuntu 22.10 support in install.sh

### ISSUE THREAD

**Issue by phelix001** [tailscale/tailscale#6234]
### What are you trying to do?

Trying to install using curl -fsSL https://tailscale.com/install.sh | sh  

on 22.10 Ubuntu Kinetic

### How should we solve this?

I'd like it to install.

### What is the impact of not solving this?

Needed update.

**Comment by DentonGentry** [comment]
The script does support Ubuntu kinetic:
```
		ubuntu)
			if [ "$VERSION" != "xenial" ] && \
			   [ "$VERSION" != "bionic" ] && \
			   [ "$VERSION" != "eoan" ] && \
			   [ "$VERSION" != "focal" ] && \
			   [ "$VERSION" != "groovy" ] && \
			   [ "$VERSION" != "hirsute" ] && \
			   [ "$VERSION" != "impish" ] && \
			   [ "$VERSION" != "jammy" ] && \
			   [ "$VERSION" != "kinetic" ]
			then
				OS_UNSUPPORTED=1
			fi
		;;
```

When install.sh doesn't recognize the distribution it prints a number of environment variables, what does it say on your system?

**Comment by phelix001** [comment]
User error
