### ISSUE TITLE
MagicDNS not working on macOS

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#6238]
### What is the issue?

MagicDNS is not working on macOS anymore as of ~1.32.2

ssh user@host times out since host does not resolve properly.

### OS

macOS

### OS version

macOS 12.6.1

### Tailscale version

1.32.2

### Bug report

BUG-01deeb523b3f156423d6c2bef9f667b8000f4a39bb42f4f8e1d457b5fc1dedaa-20221108211021Z-9dd48edfe753963a

**Comment by mihaip** [comment]
This may be better suited to a support@tailscale.com email with additional details (output of `scutil --dns` on the Mac, Tailscale IPs of the Mac and machine you are trying to SSH to).

**Comment by wingcomm** [comment]
@mihaip E-mail sent. Thank you for following up.

**Comment by mihaip** [comment]
Moved to http://go/hs/6757
