### ISSUE TITLE
tailscale asks for machine reauthorization upon reboot 

### ISSUE THREAD

**Issue by awb99** [tailscale/tailscale#6241]
### What is the issue?

this is a new ticket for a similar issue as with #496

on every reboot tailscale asks to login.
this is with 1.32.2

on every reboot it creates a new machine id and a new node key.
this happens on guix os using the binary tar file.

### OS

Linux

### OS version

guix

### Tailscale version

1.32.2

### Bug report

BUG-5aaec7bbc53a90561008d40ce83222dd0c9a3298c7abdfdbfc1f24d25e4f8df9-20221109010652Z-ddf3046e97e29bcd

**Comment by bradfitz** [comment]
This is almost surely a guix config error but we don't have anyone who uses guix. You probably don't have /var/lib/tailscale on persist storage.

**Comment by awb99** [comment]
Guix has packaged tailscale. It only dos not have a service config. I did add it here: 
https://github.com/clojure-quant/infra-guix/blob/main/modules/awb99/services/tailscale.scm

**Comment by awb99** [comment]
``` 
sudo ls /var/lib/tailscale/ -alfgh
total 4.0K
drwx------ 1 root 114 Nov  4 22:53 .
drwxr-xr-x 1 root 208 Nov  7 01:47 ..
-rw------- 1 root 209 Nov  4 22:53 tailscaled.log.conf
-rw------- 1 root   0 Nov  9 00:24 tailscaled.log1.txt
-rw------- 1 root   0 Nov  9 00:24 tailscaled.log2.txt
``` 
seems to be persisted normally.

**Comment by awb99** [comment]
```
ls /var/run
cups         gdm             resolvconf  syslog.pid        wpa_supplicant.pid
dbus         minidlna        samba       tailscale
docker       NetworkManager  shepherd    tailscaled.state
docker.pid   nscd            sshd        udisks2
docker.sock  ntpd            sudo        utmpx
```

**Comment by DentonGentry** [comment]
`tailscaled.state` needs to persist across reboots, and is supposed to be in /var/lib/tailscale/
It is instead in /var/run, where it is lost upon reboot.

This is why it asks to authenticate again after every reboot.

**Comment by awb99** [comment]
This is copied from the nix configuration of tailscale
``` 
    wrapProgram $out/bin/tailscaled --prefix PATH : ${lib.makeBinPath [ iproute2 iptables getent shadow ]}
    wrapProgram $out/bin/tailscale --suffix PATH : ${lib.makeBinPath [ procps ]}
``` 

Could it be that tailscale shells out to external programs, so that it can determine the machine correcty?

**Comment by DentonGentry** [comment]
Seriously: the node needs to be reauthenticated again on every reboot because the `tailscaled.state` file is being lost.
You need to store the `tailscaled.state` file somewhere that it will persist. Usually this is `/var/lib/tailscale/`

**Comment by awb99** [comment]
Updated tailscale package and service definition here:
https://github.com/clojure-quant/infra-guix/blob/main/modules/awb99/package/tailscale.scm
https://github.com/clojure-quant/infra-guix/blob/main/modules/awb99/services/tailscale.scm

my config uses binary download which will only be accepted in nonguix. but I think it should not
be too difficult to submit a package to gnu guix that compiles the go files...

rebooting now to see if this does the trick. its a shame that I am the first to run tailscale on guix :-(
fingers crossed.

**Comment by awb99** [comment]
Updated tailscale package and service definition here:
https://github.com/clojure-quant/infra-guix/blob/main/modules/awb99/package/tailscale.scm
https://github.com/clojure-quant/infra-guix/blob/main/modules/awb99/services/tailscale.scm
https://github.com/clojure-quant/infra-guix/blob/main/modules/awb99/services/tailscaleup.scm

**Comment by awb99** [comment]
It works beautifully now!  I added a tailscaleup service also, so that my 
machines reconnect on startup.
I will write something.

**Comment by awb99** [comment]
https://github.com/clojure-quant/infra-guix/blob/main/DOC/SETUP/tailscale-with-guix.md

**Comment by awb99** [comment]
I hope this md file will be enough explaination to allow any guix user to use tailscale

**Comment by awb99** [comment]
It really should be possible to get tsilscale added to guix main packages.
This requires building the go project from source. I only use the binary download.
That should be not complicated .. but I dont use go .. sl not fsmiliar wkth the build tool.

And for the service I fire it up giving it all binaries in the search path. But perhaps we can
Reduce it to the guix equivalent of nix packaged "iproute2 iptables getent shadow".
Then to use tailscale becomes just two lines of config code.
