### ISSUE TITLE
Cannot connect to databases using Postico

### ISSUE THREAD

**Issue by jack-fireworkhq** [tailscale/tailscale#6244]
### What is the issue?

I tried with tailscale 1.32.2, 1.32.0, 1.26.0, unfortunately none of them can log me in on my Macbook pro.

I'm living inside China mainland, so I'm using [clash_for_windows](https://github.com/Fndroid/clash_for_windows_pkg) to climb out of the great firewall.

I also have a Windows laptop, and tailscale-1.32.2 works well with the same clash config on it.

### Steps to reproduce

1. brew install --cask tailscale
2. open tailscale and click the "log in".
3. nothing happens(can't log in).

Here's a screenshot for macbook:

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/80802145/200737605-a360fc7d-1799-4ee2-a895-2a1324462c51.png">

You can see it stuck at vpn starting, and no response after clicked the log in button.

Here's a screenshot for Windows:

![image](https://user-images.githubusercontent.com/80802145/200738715-51a7db77-24f7-4a10-b172-871129f2ccd4.png)

And everything works on Windows. But I really don't want to use two systems on two laptops while working😂

### OS

macOS

### OS version

Ventura 13.0

### Tailscale version

1.32.2

### Bug report

2022/11/09 12:16:18 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscaled.socket: connect: no such file or directory

**Comment by DentonGentry** [comment]
`2022/11/09 12:16:18 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscaled.socket: connect: no such file or directory`

This is also the reason that connectivity isn't working, `tailscaled` is the main daemon which connects to the VPN. In `/Applications/Utilities/Console.app` if you search for 'tailscale' does it find errors in the logs?

You can also run tailscaled from a local shell just to see if it prints something useful: `sudo /usr/sbin/tailscaled`
If it prints that /usr/sbin/tailscaled is not found, please use `which tailscaled` to figure out where homebrew installed it.

**Comment by jack-fireworkhq** [comment]
There is no `tailscaled` after `brew install --cask tailscale`.
I ran `brew install tailscale` to install it.
After I ran `sudo tailscaled`, `tailscale bugreport` shows:
`tailscale bugreport                                                                                                                                               ─╯
Warning: client version "1.32.2-t2f1a945ad-g07d934fd1" != tailscaled server version "1.32.2-t54e8fa172"
BUG-68390d62136efd966635d62387240cc15fc10ab8f98551531576c1f89ffb67b7-20221109043531Z-3e581cdd4b372762
`

**Comment by bradfitz** [comment]
Your `tailscale` looks like it's an alias to the GUI binary in `/Applications/`, not the homebrew `tailscale`.

You're running a mix of stuff.

**Comment by jack-fireworkhq** [comment]
Okay, I deleted the "cask tailscale" and installed it with `brew install tailscale`. It's looking good:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/80802145/200755507-b7463790-75e6-41d5-84d7-f3bbd54c4f46.png">


Here's the `tailscale bugreport` output:
`BUG-68390d62136efd966635d62387240cc15fc10ab8f98551531576c1f89ffb67b7-20221109062350Z-254bd27a3587a867`

I found an error when I tried to connect to database with Postico and Clash for Windows Tun mode on:
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/80802145/200756888-61559d9b-5879-4670-8421-f3b941e9693c.png">

**Comment by DentonGentry** [comment]
I don't see what error you're referring to. What specifically doesn't work?

**Comment by jack-fireworkhq** [comment]
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/80802145/200775855-d2d5ecd0-2363-4672-a4e0-9e5c7fc668e6.png">
Here, I pointed it out.

**Comment by rpicciotti** [comment]
I seem to be having the same issue. I decided to try out Tailscale and it worked on my iPhone and linux box without issue. However the macOS Tailscale app does nothing when I hit the login button. I'm in the US and shouldn't have any firewall issues (the phone and linux machine are on the same network).

**Comment by DentonGentry** [comment]
@jack-fireworkhq in the screenshot with the red arrow, what specifically doesn't work? Can you still not log in? I see what appears to be normal activity, so it seems like the machine was at least able to join the tailnet.

I get that you found the word "error" in logs but there are various errors all the time in real networks. We're not going to followup on every log message.

**Comment by jack-fireworkhq** [comment]
The `tailscale ip -4` can show the IP, but still doesn't work, I can't connect to any databases with Postico.

**Comment by skhaz** [comment]
I have the same issue. Installed tailscale using brew cask; it gets stuck forever on "VPN Starting..."

**Comment by DentonGentry** [comment]
To make progress we need the following:
- connect to Tailscale
- try to connect to a database using Postico
- get another bugreport from the macOS system

**Comment by jack-fireworkhq** [comment]
BUG-68390d62136efd966635d62387240cc15fc10ab8f98551531576c1f89ffb67b7-20230531082824Z-441517e994f6d061

Sorry for the delay, here's the bugreport after tailscale was up and tried to connect a database using Postico

**Comment by DentonGentry** [comment]
Is the Postico database on a machine running Tailscale, or is it reached via a subnet router?

The Mac which produced the bugreport has Settings > Use Tailscale Subnets turned off:
`wgcfg: did not accept subnet routes: 172.25.x.y/20 from "prod" ([0NiWd]), 172.31.x.y/16 from "prod" ([0NiWd]), 172.16.x.y/16 from "prod" ([0NiWd]), 10.10.x.y/16 from "staging" ([hlRxy]), 172.25.x.y/20 from "staging" ([hlRxy])`

The reason I think subnet routes might be the issue is that you should see ACL evaluations in the log from trying to connect to the Postico database. For example, this is from one of my devices:
`May 30 19:03:08 OPNsense tailscaled[8388]: 2022/05/30 19:03:08 Accept: TCP{100.102.2.96:50820 > 100.92.61.18:22} 60 tcp ok`

I don't see any ACL evaluations around the time of the bugreport. I think the packets to Postico are not trying to use Tailscale to reach the Postico database, they're being sent to the default route.

**Comment by jack-fireworkhq** [comment]
> Is the Postico database on a machine running Tailscale, or is it reached via a subnet router?
> 
> The Mac which produced the bugreport has Settings > Use Tailscale Subnets turned off: `wgcfg: did not accept subnet routes: 172.25.x.y/20 from "prod" ([0NiWd]), 172.31.x.y/16 from "prod" ([0NiWd]), 172.16.x.y/16 from "prod" ([0NiWd]), 10.10.x.y/16 from "staging" ([hlRxy]), 172.25.x.y/20 from "staging" ([hlRxy])`
> 
> The reason I think subnet routes might be the issue is that you should see ACL evaluations in the log from trying to connect to the Postico database. For example, this is from one of my devices: `May 30 19:03:08 OPNsense tailscaled[8388]: 2022/05/30 19:03:08 Accept: TCP{100.102.2.96:50820 > 100.92.61.18:22} 60 tcp ok`
> 
> I don't see any ACL evaluations around the time of the bugreport. I think the packets to Postico are not trying to use Tailscale to reach the Postico database, they're being sent to the default route.

The database is supposed to be reached via a subnet router. I tried both Tailscale commandline and standalone versions, none of them works. The App Store version is not allowed in my region.

**Comment by DentonGentry** [comment]
> The database is supposed to be reached via a subnet router. 

That means that this: `wgcfg: did not accept subnet routes: 172.25.x.y/20 from "prod" ([0NiWd]),  ...`
is the root cause of the problem. The Mac is ignoring subnet routes.

If using the commandline version, you need to use: `tailscale up --accept-routes`

If using the Standalone version, look in Settings and make sure Use Tailscale Subnets is enabled.
<img width="622" alt="Screenshot 2023-06-04 at 11 23 53 PM" src="https://github.com/tailscale/tailscale/assets/1140756/7035c608-b0d2-48d6-9d8e-1474d7399f7a">
