### ISSUE TITLE
Report local subnet routes to control

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#625]
For the admin panel to be able to give tips & show free IPv4 private subnets across a team, we want to be also upload client subnet routes to control. (We already necessarily include the local interface IP addresses for peer discovery reasons.... so this would effectively just be including those interface's networks too)

**Comment by crawshaw** [comment]
One thing I noticed when helping out a few people with their routing tables is a surprising number of machines have virtual network interfaces with various 192.168.x subnets. These are for virtualbox/docker/etc. It would be nice to give some visual hint as to whether a subnet is on a virtual device. (I usually want to ignore them.)

**Comment by bradfitz** [comment]
@crawshaw, totally. Can include the name/context for each interface.

**Comment by bradfitz** [comment]
We at least log some of this now. (the interfaces, as part of interfaces.State)

But we don't log the routes.

**Comment by bradfitz** [comment]
Example of what we currently log:

```
link state: interfaces.State{defaultRoute=ens18 ifs={docker0:[172.17.0.1/16] ens18:[10.0.0.52/16 2602:d1:b4cf:c100:xxxx:4148/64]} v4=true v6=true}
```

That at least tells us the default route and the interfaces subnet sizes, which is usually enough.

This can probably be closed. It's hard for me to think of cases where more precise route information would've been helpful while debugging.

**Comment by DentonGentry** [comment]
I can't think of cases where more information about local routes would have helped either.
