### ISSUE TITLE
Using --exit-node= on rocky linux doesn't work

### ISSUE THREAD

**Issue by jahanson** [tailscale/tailscale#6251]
### What is the issue?

After a fresh install of either Rocky Linux 8 or 9 I cannot use an exit node exclusively for outbound traffic. It cuts off all inbound or outbound traffic as soon as I run `tailscale up --exit-node=100.69.87.93` I can use the exit node with a fresh install of fedora 36 server with no issue. I can't seem to find what's wrong. Traffic resumes when I run `talescale up --reset`.

### Steps to reproduce

Fresh install of Rocky Linux 8/9

`tailscale up --exit-node=100.69.87.93` 

### OS

Linux

### OS version

Rocky Linux 9

### Tailscale version

1.32.2

### Bug report

BUG-b45a4a89345f69734a2e0212a3b73e3f1cb3f3c0612b86ab9f2ff4bb9552e04e-20221109175240Z-9de363b809c1df94

**Comment by Ci7rix** [comment]
I have the same issue on a fresh install of Rocky Linux 9 (Cloud image).
The subnet router is also not working.

**Comment by jahanson** [comment]
Not a workaround, but I was eventually able to get wireguard working directly on rocky linux 8 by installing kmod-wireguard. But it seems you'll need a compatible kernel (>= 4.18.0) since the default main kernel of 8 is 4.18 now it should work. (11/15/22).

**Comment by jahanson** [comment]
The above no longer works on Rocky Linux 8 and doesn't work on 9.1 either. Any advice anyone can provide? I'm stumped.

**Comment by DentonGentry** [comment]
Possibly related: https://github.com/tailscale/tailscale/issues/3310

If so, this may resolve the issue:
`sysctl -w net.ipv4.conf.eth0.rp_filter=2`
(replace "eth0" with the name of the LAN interface)

**Comment by jahanson** [comment]
> Possibly related: #3310
> 
> If so, this may resolve the issue: `sysctl -w net.ipv4.conf.eth0.rp_filter=2` (replace "eth0" with the name of the LAN interface)

This fixed it for me on Rocky Linux 8.7 and Rocky Linux 9.1.
