### ISSUE TITLE
FR: Support for openWRT routers

### ISSUE THREAD

**Issue by KayLEvans** [tailscale/tailscale#6252]
### What are you trying to do?

Per user issue: 

> I have installed tailscale on my Oracle server but then when I wanted to connect it from my router which runs on the OpenWRT. Somehow my router's traffic is not routing through my oracle server even though I specifically used CLI command to use exit node

Reproduction steps:

> Install Tailscale using OpenWRT addons. Then authenticate with your acct and move forward with tailscale up command with --exit-node=(MyOracleServerIP) which I have marked as Exit node.

**Comment by DentonGentry** [comment]
Likely prerequisite: https://github.com/tailscale/tailscale/issues/391

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/724
