### ISSUE TITLE
Android client very low speed using exit node

### ISSUE THREAD

**Issue by ashishjullia** [tailscale/tailscale#6263]
### What is the issue?

I've 2 tailscale clients on two separate Android Phones, one is in India and another is in Canada.

I'm trying to use the client in India as an `exit node` for my client in Canada.

But the speed is too slow.

### OS

Android

### OS version

Android 12 and Android 10

### Tailscale version

1.32.2

**Comment by ashishjullia** [comment]
[Reference issue](https://github.com/tailscale/tailscale/issues/4244)

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/4244

**Comment by ashishjullia** [comment]
> Duplicate of https://github.com/tailscale/tailscale/issues/4244

Why you closed this? You specifically mentioned that we can look into the logs, [here](https://github.com/tailscale/tailscale/issues/4244#issuecomment-1296487402).

**Comment by DentonGentry** [comment]
Please add a bugreport shortly after using the exit node and noting low throughput.

**Comment by DentonGentry** [comment]
The point was to provide a bug report and a new issue on which to investigate. Without a bugreport shortly after noting low throughput through the exit node, having this issue open is not useful to further investigate.

Barring further comment including a bugreport, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Would need a bugreport or anything to go on.
