### ISSUE TITLE
FR: Exit node failover

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#6264]
### What are you trying to do?

Exit node fail over. Basically if one exit node dies, the machine using the exit node can no longer be accessed from Tailscale. I wasn't able to RDP or ping the tailscale node as it completely couldn't access the machine.

### How should we solve this?

Add exit node fail over so it can try another node to reach the internet.

### What is the impact of not solving this?

Lost access to certain nodes remotely especially in a server scenario.

### Anything else?

This may be invalid, I would rather the Tailscale team can confirm if this is the case.

Perhaps there is already failover?

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2598
