### ISSUE TITLE
FR: Make the need for the --accept-routes flag explict in the Linux download page, under certain conditions

### ISSUE THREAD

**Issue by umm0n** [tailscale/tailscale#6266]
### What are you trying to do?

The [Linux download page](https://tailscale.com/download/linux) for Tailscale should have a small disclaimer about the need for the `--accept-routes` flag when you need to accept subnet routes from other nodes in the network, as explained in the [troubleshooting guide](https://tailscale.com/kb/1023/troubleshooting/#linux).

### How should we solve this?

Add the disclaimer to the Linux download page.

### What is the impact of not solving this?

When trying to make Tailscale as self-service as possible (but aimed at a technical audience) it would be useful to have this. Not having this disclaimer outright can lead to some confusion for users, when their connections fail while using `tailscale up` and nothing more. It would be simpler to include it in the download page, rather than have users hunt for it in the troubleshooting guide. I imagine it's a pretty common requirement (to accept subnet routes from other nodes).

**Comment by DentonGentry** [comment]
We've added a warning to `tailscale up` and a health check to `tailscale status`, which I think is more likely to be at the moment one is likely to act on it. 

```
root@ubuntu:~# tailscale up
Some peers are advertising routes but --accept-routes is false
```

Closing as sufficiently addressed.

**Comment by umm0n** [comment]
Excellent, thanks!
