### ISSUE TITLE
FR: add tailnet name to `tailscale status`

### ISSUE THREAD

**Issue by petteja** [tailscale/tailscale#6286]
### What are you trying to do?

It could be nice to have a fast way of getting the tailnet name from cli.

### How should we solve this?

By letting the `tailscale status` command output tailnet name as well.

### What is the impact of not solving this?

Learn the tailnet name by heart.

**Comment by DentonGentry** [comment]
I believe this will provide the needed information: `tailscale status --json | jq .CurrentTailnet`
