### ISSUE TITLE
Logged out daily since 1.32.2 on macOS

### ISSUE THREAD

**Issue by jameshochadel** [tailscale/tailscale#6305]
### What is the issue?

My macOS client, installed from the App Store, is authenticated with GitHub. A few days ago, I think when 1.32.2 was installed, I started getting logged out every day. I wish I had more detail or repro steps but that's the entire behavior. When I click the toolbar icon > Log in, it logs into the Tailnet with no further interaction.

### Are there any recent changes that introduced the issue?

Installed the latest Tailscale update from the App Store on November 4, and updated to Ventura a few weeks ago.

FWIW `tailscale bugreport` outputs the warning

```
Warning: client version "1.32.2-t54e8fa172" != tailscaled server version "1.32.2-t2f1a945ad-g07d934fd1"
```

### OS

macOS

### OS version

13.0 (22A380)

### Tailscale version

1.32.2

### Bug report

BUG-fbe4031e1a4de71a221bd93f91fba1d58be78053221441f292e95eb68efbe11d-20221113040716Z-b7c0930b03e61440

**Comment by bradfitz** [comment]
There are three Mac Variants: https://tailscale.com/kb/1065/macos-variants/

Your CLI (`tailscale` binary) is the homebrew/open source binary (it has no `-g` part in the version).

Your Tailscale daemon's logs have this right before they go offline:

```
2022-11-12 02:48:29.76625 +0000 UTC: stopTunnel: "userLogout"
```

Do you just sleep the machine, or do you switch users, or ... ?

/cc @nickoneill @mihaip

**Comment by jameshochadel** [comment]
Aha. I'm doing a fast user switch, and I didn't realize that caused a logout. The client version upgrade was a red herring — I set up user switching on this machine around the same time. Many thanks @bradfitz.

**Comment by bradfitz** [comment]
Yeah, that's a macOS thing.

If you don't want that behavior, you can use the tailscaled version.
