### ISSUE TITLE
Windows MagicDNS doesn't work after boot until I turn it off and on

### ISSUE THREAD

**Issue by andor44** [tailscale/tailscale#6319]
### What is the issue?

I have one Windows 10 host in particular where Magic DNS will not work after boot, even though it is enabled for my tailnet and it's turned on locally. If I try to resolve a "bare" hostname of a host in the tailnet it is answered by my local DNS server, rather than Magic DNS doing its thing.

Sometimes, it is fixed by simply clicking "disconnect" followed by "connect" in the Windows tray agent, but more often than not this isn't enough. If this doesn't work I typically try turning off Magic DNS locally (toggling tray agent -> preferences -> use Tailscale DNS), if that doesn't help either I try stopping the service and starting it again.

Once it works it will continue to work until the next boot.

### Steps to reproduce

I am not sure. This only occurs on one specific Windows 10 host (I have other Windows 10 hosts in this tailnet where no such problem occurs). Therefore I believe the problem is more likely to be with my local setup than tailscale itself, but given that I have no idea how Magic DNS hijacks regular DNS resolution I don't know how to troubleshoot it myself.

### Are there any recent changes that introduced the issue?

This started several versions ago, I just recently got annoyed enough to report it.

### OS

Windows

### OS version

Windows 10 21H2

### Tailscale version

1.32.2

### Bug report

BUG-b42110789e297ef8c861faf32762520611d0556915f0af4e932e20b04087e493-20221114205804Z-4cbac55504b957e4

**Comment by MelMti** [comment]
I have a few servers running 24/7 and it seems that DNS majic is losing resolution at variable intervals. The only way to get it to resolve to IP is by disabling DNSMajic and reenabling. We have tested IP during down times and IP addresses are resolving correctly.

**Comment by andor44** [comment]
Update: it seems that turning Magic DNS off and then back on reliably fixes the issue. It's annoying, but at least I have a workaround for the time being.

**Comment by DentonGentry** [comment]
Shortly before the BUG-* line:
```
2022-11-14 20:56:06.5375223 +0000 UTC: health("dns"): error: rename C:\WINDOWS\system32\drivers\etc\hosts.tmp715397190 C:\WINDOWS\system32\drivers\etc\hosts: Access is denied.
2022-11-14 20:56:06.5375223 +0000 UTC: health("overall"): error: dns-os: rename C:\WINDOWS\system32\drivers\etc\hosts.tmp715397190 C:\WINDOWS\system32\drivers\etc\hosts: Access is denied.
2022-11-14 20:56:06.5375223 +0000 UTC: health("dns-os"): error: rename C:\WINDOWS\system32\drivers\etc\hosts.tmp715397190 C:\WINDOWS\system32\drivers\etc\hosts: Access is denied.
```
which is a symptom of https://github.com/tailscale/tailscale/issues/5753

I wouldn't expect this to break MagicDNS altogether, as writing to the hosts file is an optimization introduced in https://github.com/tailscale/tailscale/pull/5371

**Comment by DentonGentry** [comment]
I think this is likely a symptom of [#4845](https://github.com/tailscale/tailscale/issues/4845) and [#6110](https://github.com/tailscale/tailscale/issues/6110)

Tailscale 1.42.0 contains [#8008](https://github.com/tailscale/tailscale/pull/8008), which is believed to resolve it.
Please post if you see further occurrences using Tailscale 1.42.0 or later.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by andor44** [comment]
The issue does seem resolved, I haven't had DNS hiccups in a while, will mark resolved!
