### ISSUE TITLE
Use via docker cannot access host server

### ISSUE THREAD

**Issue by skret028** [tailscale/tailscale#6327]
### What is the issue?

I deployed tailscale in docker,the server's ip is 192.168.1.1,the docker's ip is 192.168.1.4.
I executed 
`docker run -d --name=tailscaled --net=br0 --ip=192.168.1.4 --restart=always -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --privileged tailscale/tailscale:latest tailscaled`
`docker exec tailscaled tailscale up --accept-routes --advertise-routes=192.168.1.0/24`

When I excute `docker exec tailscaled ping -c 2 192.168.1.1` , it responses fine.

But if I do the same via tailscale logged in remotely,it responses 'Request timed out'.
I know the tailscale works fine , cause pinging other ip like gataway router '192.168.1.254', or other computers' ip,even a container on the server which ip is '192.168.1.11',they both response fine.
The only ip I cannot access is the host server's.

How can I resolve this?

### Steps to reproduce

`docker run -d --name=tailscaled --net=br0 --ip=192.168.1.4 --restart=always -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --privileged tailscale/tailscale:latest tailscaled`
`docker exec tailscaled tailscale up --accept-routes --advertise-routes=192.168.1.0/24`

### OS

Linux

### OS version

Anolis 8.6(Centos 8)

### Tailscale version

1.32.2

**Comment by DentonGentry** [comment]
I don't really see what involvement tailscale has here. The container and the host are not communicating.
