### ISSUE TITLE
Routing table changed from 88 to 52

### ISSUE THREAD

**Issue by dkerwin** [tailscale/tailscale#635]
**Describe the bug**
I'm not sure if this is a bug or some outdated documentation but it seems that the routing table in linux changed from 88 to 52. 

**To Reproduce**
1. `ip r s t 88`
2. There are no routes
3. `ip r s t 52`
4. Tailscale related routes are found

**Comment by bradfitz** [comment]
Intentional (https://github.com/tailscale/tailscale/commit/189d86cce586a6be5aa48af02f604808e01f534f).

Is this a problem?

**Comment by bradfitz** [comment]
Did we document this somewhere?

**Comment by dkerwin** [comment]
Not really a problem but it should be reflected in the docs. If I follow the troubleshooting guide I would potentially dive into the wrong rabbit hole ;-) Given the other meaning of `88` I'm totally fine with the move to `52`.

**Comment by dkerwin** [comment]
> Did we document this somewhere?

https://tailscale.com/kb/1023/troubleshooting?q=88#how-can-i-see-the-ip-routes-tailscale-installs

**Comment by bradfitz** [comment]
Thanks, updated! (haven't deployed it yet)
