### ISSUE TITLE
ipn/ipnlocal: local machine serve listener fails on mac GUI sandbox

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6364]
```
2022-11-17 07:05:33.189454 +0000 UTC: serve failed to listen on 100.126.185.78:443, backing off: listen tcp 100.126.185.78:443: bind: permission denied
2022-11-17 07:05:54.822975 +0000 UTC: serve failed to listen on 100.126.185.78:443, backing off: listen tcp 100.126.185.78:443: bind: permission denied
2022-11-17 07:06:22.08098 +0000 UTC: serve failed to listen on 100.126.185.78:443, backing off: listen tcp 100.126.185.78:443: bind: permission denied
2022-11-17 07:06:48.602011 +0000 UTC: serve failed to listen on 100.126.185.78:443, backing off: listen tcp 100.126.185.78:443: bind: permission denied
```

cc @shayne @maisem

**Comment by shayne** [comment]
Doesn't look like Mac App's can listen on privileged ports. I can change the default to 8443 and error out in the for 443.

**Comment by bradfitz** [comment]
@nickoneill @mihaip is there some entitlement for this?

**Comment by mihaip** [comment]
As far as I can tell this should work -- we have the `com.apple.security.network.server` entitlement and as Shayne observed starting with 10.14 [you no longer need to be root](https://developer.apple.com/forums/thread/674179) to bind to privileged ports.

**Comment by bradfitz** [comment]
Oh I bet we're missing the ioctl on the listener to get outside the sandbox. We do that for peerapiserver etc.

**Comment by mihaip** [comment]
You can check to see if it's sandboxing-related by looking for `Sandbox``deny` messages in Console.app (https://github.com/tailscale/tailscale/issues/4518#issuecomment-1170656652 has an example of what it looks like for `ioctl`, https://developer.apple.com/forums/thread/705461?answerId=712659022#712659022 has an example for port binding.

**Comment by shayne** [comment]
In researching this a bit more, I'm currently challenging the assumption that interface specific binding of privileged is still borked in macOS:
https://developer.apple.com/forums/thread/674179

I was able to hard-code `net.Listen(":443")` and alas, it works. 
![image](https://user-images.githubusercontent.com/79330/202779172-9ca50f8f-54b2-403c-b403-ee76b2149ad8.png)

**Comment by shayne** [comment]
For reference, here's the relevant lines of peerAPIServer.listen:
https://github.com/tailscale/tailscale/blob/dd50dcd06768bc54112a9acc5229d9b9ef63832c/ipn/ipnlocal/peerapi.go#L404-L418

**Comment by shayne** [comment]
@bradfitz do we want to go ahead with `":<serve-port"` as the listen addr for macOS?

**Comment by bradfitz** [comment]
I'd hope we wouldn't have to do that. I don't really want to interfere with other stuff on the machine. But OTOH, I doubt there's other stuff on a Mac. So... sure? Leave a TODO about it not being right and reference this bug?

**Comment by shayne** [comment]
I'm unable to get serve to work whatsoever in macOS sandboxed. The listener is failing to listen on some interfaces and even interfaces it can listen on, it's never able to Accept a connection. More investigation is needed. Work in #6771

**Comment by shayne** [comment]
PR up that fixes local listeners on macOS. Concession: we listen to all-interfaces serve is running on a privileged port.
