### ISSUE TITLE
Can't authenticate on iPhone

### ISSUE THREAD

**Issue by conorhub** [tailscale/tailscale#6366]
### What is the issue?

I'm running Tailscale on a Pi and iPhone. Pi always worked without issue, iPhone (after mostly working for months) just shows an infinite spinning icon and no listing of any other client. Toggling the switch doesn't appear to do anything and, if I log in to my tailscale account online, it suggests no connection was established.

- I tried resetting keychain via the settings
- I tried deleting and reinstalling Tailscale
- I had another VPN config. I've tried deleting it so that Tailscale is the only VPN config on the phone

All attempts presented the same blank list and infinite loading.

I deleted iPhone from the Tailscale settings on the website. iPhone now shows the same infinite loading but says "needs authentication" and provides no way to do so. Clicking reauthenticate appears to do nothing.

**Possibly worth noting**

Every few weeks the iPhone client would show a blank list and I'd force quit the app, wait a while, then reopen it and it would show the Pi.

### Steps to reproduce

Run IOS 16.1
Install Tailscale fresh
Confirm you want it to add VPN config
Wait for infinite "needs authentication" message

### Are there any recent changes that introduced the issue?

The iPhone worked most of the time up until a few weeks ago. It may be coincidental timing but the Pi said its cert expired and needed reauthnetication, which I did and it reauthetnicated ok and is showing as connected.

### OS

iOS

### OS version

16.1

### Tailscale version

Where is Tailscale showing this? It's the latest iOS release of of Nov 17 2022

### Bug report

BUG-e8feae9c4b1bc594790bc343b0d8a64b71f6c21e920186fc3301f180c9b46f08-20221117130830Z-2277e44d511e86fa

**Comment by mihaip** [comment]
The bug report did not appear to get uploaded to our logging system (it's an asynchronous process, you may need to leave the app running for a while after initiating it, could you try again?

Do you have any other VPN software (or networking-related features, like iCloud Private Relay) enabled?

**Comment by conorhub** [comment]
Thanks for getting back.

After several days of nothing, I opened the app today and received a prompt to sign in, and now the ios client is functioning fine again.

As far as I know, I changed nothing else so I unfortunately can't explain the reason the app was able to provide me with a way to authenticate today.

But to answer your questions:

- As mentioned above, I had another VPN config. There was VPN software to control but I hadn't used it in months. That particular VPN was disabled during this whole period and I also completely removed the software and the config while trying to figure out what was wrong, which didn't improve things.
- I have iCloud Private Relay attempting to work but unable to on my main network as I am using PiHole as a DNS, which disables the PR functionality.
- Nonetheless, I manually deactivated both the PR and PiHole while testing and neither improved the situation. I have easy access to four different networks (including my cellular network) and none were allowing Tailscale to authenticate or progress until yesterday, whereas all had been doing so fine before. So my gut feeling is that it's not any combination on my main network.

**A suggestion:**

Can there be some sort of UX communication to the user in scenarios where a Tailscale client doesn't reach a certain target point necessary to function? The blank UI confused me as to what to do next. I wasn't sure if, under the hood, Tailscale was attempting something and I should leave it. Or whether it failed. Or if there was a suggestion of what I could do next.

In all the scenarios where it wouldn't work, the toggle remained in the top left corner and switching it back and forth appeared to do nothing. If it's not possible to authenticate the user, perhaps the toggle can be disabled to communicate it's not possible to progress further.

In a similar vein, when I generated a bug report, it told me that the report was sent ant to copy the ID. If the app needs to be open longer for this to have relevance, could this be communicated to the user?

Thanks for providing all the work so far with Tailscale. It's helped me immensely with day-to-day tasks.

**Comment by DentonGentry** [comment]
Symptoms resemble https://github.com/tailscale/tailscale/issues/6706, did that issue also impact iOS?

If so: it was a race condition, and if you happened to be lucky the network interfaces would come up before Tailscale tried to use them.

A proper fix went into 1.36.1.

**Comment by DentonGentry** [comment]
At this point I'll assume this was fixed by 1.36.1.
