### ISSUE TITLE
Should be able to hide, deactivate, or delete users from the admin panel

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#638]
Steps:
1. Log into your domain with several different user accounts
2. Try to remove a user from your domain, eg. by deleting their account in the identity system, deleting all their notes from the /admin/machines page, etc.

Expected:
The user disappears or appears differently in the /admin/users page, or at least there's a "delete" button in the /admin/users page.

Actual:
The user is there forever and there's no way to remove them.

Several users have complained about this being confusing. For example, is the user account counting toward the subscription? If the user is deleted from the identity system and still shows up, does that mean they can still login, making a security issue?

The truth is the extra users showing up is harmless (they can't log in unless the identity system lets them, and users without nodes aren't counted toward a subscription), but the UI doesn't make this clear at all.

**Comment by bradfitz** [comment]
Should we have both "Delete" and "Delete & Ban"? Seems like a ban list to prevent users from coming back might be desirable or comforting. (The Tailscale admins might not be the identity provider admins for a domain?)

**Comment by apenwarr** [comment]
I'm tempted to think of it more like a "disable" bin that people get
dumped into when needed, and users in that bin don't get shown by
default.

Probably we should also do the same for nodes. Nodes disappearing
forever when someone presses delete or a key expires is a) mysterious
to end users, especially when there's more than one admin and b) hard
to undo, and c) hard to audit later.

On Wed, Aug 5, 2020 at 12:49 AM Brad Fitzpatrick
<notifications@github.com> wrote:
>
> Should we have both "Delete" and "Delete & Ban"? Seems like a ban list to prevent users from coming back might be desirable or comforting. (The Tailscale admins might not be the identity provider admins for a domain?)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by apenwarr** [comment]
This was more or less resolved earlier. We now hide users without active nodes.
