### ISSUE TITLE
FR: Allow https in funnel

### ISSUE THREAD

**Issue by julianfairfax** [tailscale/tailscale#6394]
### What are you trying to do?

Funnel currently only supports serving a page on http://127.0.0.1

### How should we solve this?

It should support serving a page on https://127.0.0.1

### What is the impact of not solving this?

When visiting a page through the Funnel, this error is shown:
```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
```

### Anything else?

You tell me

**Comment by knyar** [comment]
If you would like to terminate the TLS connection yourself, you should be able to configure TCP proxying using `tailscale serve tcp`. Note that you might need to remove all of the web routes first (e.g. `tailscale serve --remove /`).

**Comment by bradfitz** [comment]
> but is there any number given on what these limits are?

We're not publishing a number yet. We're going to do some experiments and gather some data first before deciding what the limits will be.
