### ISSUE TITLE
ipn/ipnlocal: allow serve of empty Text() handler

### ISSUE THREAD

**Issue by shayne** [tailscale/tailscale#6405]
In writing up the CLI docs KB I thought of the use case `tailscale serve / text ""` which would be useful for creating a clean blank page for the root of your serve/funnel.

If you don't specify the mount point `/` you are served an `http.NotFound(...)`, if you do the mount as above...

Currently we check against `!= ""`
https://github.com/tailscale/tailscale/blob/063eeefdca01ac110a8ae0e76e90c70e6eb6d1fe/ipn/ipnlocal/serve.go#L398-L402

Serving a 500 with the text "empty handler"
https://github.com/tailscale/tailscale/blob/063eeefdca01ac110a8ae0e76e90c70e6eb6d1fe/ipn/ipnlocal/serve.go#L428

This seem reasonable?

cc/ @bradfitz

**Comment by bradfitz** [comment]
I'm not sure this is worth fixing. Or maybe we map `""` to `" "` (a single space) in the CLI, or U+200B ZERO WIDTH SPACE.

But I don't think we need to do anything in the backend or change types.

**Comment by shayne** [comment]
I like the idea of mapping "" to some sentinel like U+200B. We wouldn't have to change the backend but it'd work as expected for the user.
