### ISSUE TITLE
ipn: prefs_save failing on macOS, unable to create StateKey dir/file for serve

### ISSUE THREAD

**Issue by shayne** [tailscale/tailscale#6409]
@twitchyliquid64 reported the issue on Slack.

macOS unstable version 1.33.269

![image](https://user-images.githubusercontent.com/79330/202875860-252c1f7c-be2a-434d-9808-c507208eda91.png)

https://github.com/tailscale/tailscale/blob/039ea51ca687d9034eff4388753d68c7c28e8a0a/ipn/serve.go#L9-L11

**Comment by twitchyliquid64** [comment]
@squishykid

**Comment by shayne** [comment]
Did some research and my current theory is that the StateKey for serve is causing an issue. It has a `/` which translates into a directory path which fails when WriteState is called.
https://github.com/tailscale/tailscale/blob/039ea51ca687d9034eff4388753d68c7c28e8a0a/ipn/serve.go#L7-L11

I am assuming this implementation of WriteState:
https://github.com/tailscale/tailscale/blob/039ea51ca687d9034eff4388753d68c7c28e8a0a/ipn/store/stores.go#L176-L189

I was able to work around the issue by creating the parent directory (see below). I don't recommend doing this as a solution to the problem.
```
$ sudo mkdir /Library/Tailscale/tailscale-serve
```
I can't build the IPN-macsys version of the macOS app due to special signing requirements. I will have to connect with @mihaip to figure out how to test a fix before the next unstable release.

cc/ @bradfitz @maisem 

The only other StateKey with a `/` in it is below. The macOS (IPN-macsys) app creates the `CurrentProfileStateKey` file suggesting `userID == ""` on L66. 

https://github.com/tailscale/tailscale/blob/039ea51ca687d9034eff4388753d68c7c28e8a0a/ipn/store.go#L60-L69


Some options include:
- Change the key
- Perform an `os.Mkdir`
- Replace the `/` as not to use a directory for this WriteState implementation

**Comment by mihaip** [comment]
I haven't done macsys development locally, I think @nickoneill is the only one. https://github.com/tailscale/corp/blob/680d381bb173bd36586c0b1ca26f069956e27ae3/xcode/README.md#L88 describes what it takes to run locally.

I think having SecureStorage-File.swift escape `/`s is the way to go. `userID == ""` is always the case (it's only non-empty on Windows)

**Comment by nickoneill** [comment]
macsys setup is a pain, but this fix seems reasonable so you probably don't need the ability to build development builds of the macsys target. Install the profiles -> do an archive build of macsys -> manually developer id sign -> move to applications and see if it works (or I can build one from a branch if you want).
