### ISSUE TITLE
FR: Offer Tailscale on the Microsoft Store

### ISSUE THREAD

**Issue by lectrician1** [tailscale/tailscale#6410]
### What are you trying to do?

I would like to install Tailscale from the Microsoft Store

### How should we solve this?

Add Tailscale to the Microsoft Store

### What is the impact of not solving this?

Installation is not as easy or convenient. I'd also like to install apps from the Microsoft Store because then they are backed up to my Microsoft account and then I can easily reinstall them on other devices.

**Comment by arunsathiya** [comment]
Doesn't look like it's a priority; previously addressed here: https://github.com/tailscale/tailscale/issues/2969#issuecomment-931322934

**Comment by bradfitz** [comment]
Work is ongoing for this, actually. I reopened #2969. We'd been tracking it in a different repo's issue tracker, but I'll leave #2969 open too and close this one as a dup.
