### ISSUE TITLE
dns: dbus connection error

### ISSUE THREAD

**Issue by koalang** [tailscale/tailscale#6411]
### What is the issue?

i use docker to run tailscale
cat the logs，it shows dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory

logs：
`2022/11/20 03:33:19 logtail started
2022/11/20 03:33:19 Program starting: v1.32.2-t54e8fa172, Go 1.19.2-ts3fd24dee31: []string{"tailscaled"}
2022/11/20 03:33:19 LogID: 709fbf58142a0ba4111528e8b18cbd25e4943a6effdcf1c3e99b77b381af4003
2022/11/20 03:33:19 logpolicy: using system state directory "/var/lib/tailscale"
2022/11/20 03:33:19 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2022/11/20 03:33:19 setting link attributes: netlink receive: no such file or directory
2022/11/20 03:33:19 router: v6nat = true
2022/11/20 03:33:19 dns: [rc=resolved nm=no ret=systemd-resolved]
2022/11/20 03:33:19 dns: using *dns.resolvedManager
2022/11/20 03:33:19 link state: interfaces.State{defaultRoute=eth0 ifs={br-285170fc6424:[172.18.0.1/16] br-c7d00bbe9c41:[172.19.0.1/16] docker0:[172.17.0.1/16] eth0:[10.0.0.2/16]} v4=true v6=false}
2022/11/20 03:33:19 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:19 magicsock: disco key = d:c33468d17dc86081
2022/11/20 03:33:19 Creating WireGuard device...
2022/11/20 03:33:19 Bringing WireGuard device up...
2022/11/20 03:33:19 Bringing router up...
2022/11/20 03:33:19 external route: up
2022/11/20 03:33:19 Clearing router settings...
2022/11/20 03:33:19 Starting link monitor...
2022/11/20 03:33:19 Engine created.
2022/11/20 03:33:19 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:19 Start
2022/11/20 03:33:19 using backend prefs; created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
2022/11/20 03:33:19 Backend: logs: be:709fbf58142a0ba4111528e8b18cbd25e4943a6effdcf1c3e99b77b381af4003 fe:
2022/11/20 03:33:19 Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
2022/11/20 03:33:19 blockEngineUpdates(true)
2022/11/20 03:33:19 wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
2022/11/20 03:33:19 wgengine: Reconfig: configuring router
2022/11/20 03:33:19 wgengine: Reconfig: configuring DNS
2022/11/20 03:33:19 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2022/11/20 03:33:19 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
2022/11/20 03:33:19 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
2022/11/20 03:33:19 dns: failed to configure resolved: resolved DBus does not have a connection
2022/11/20 03:33:19 Reconfig(down): resolved DBus does not have a connection
2022/11/20 03:33:19 health("overall"): error: state=NeedsLogin, wantRunning=false
2022/11/20 03:33:19 health("dns-os"): error: resolved DBus does not have a connection
2022/11/20 03:33:19 health("dns"): error: resolved DBus does not have a connection
2022/11/20 03:33:19 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:19 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:19 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:19 [RATELIMIT] format("dns: dbus connection error: %v")
2022/11/20 03:33:30 [RATELIMIT] format("dns: dbus connection error: %v") (9 dropped)
2022/11/20 03:33:30 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:33 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:33 [RATELIMIT] format("dns: dbus connection error: %v")
2022/11/20 03:33:40 [RATELIMIT] format("dns: dbus connection error: %v") (1 dropped)
2022/11/20 03:33:40 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:43 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:43 [RATELIMIT] format("dns: dbus connection error: %v")
2022/11/20 03:33:49 [RATELIMIT] format("dns: dbus connection error: %v") (1 dropped)
2022/11/20 03:33:49 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:33:55 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:02 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:05 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:09 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:16 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:20 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:30 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:37 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2022/11/20 03:34:47 dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory`

### Steps to reproduce

use docker compose to create n run tailscale

### OS

Linux

### OS version

Ubuntu 20.04.5 LTS x86_64

### Tailscale version

1.32.2

### Bug report

BUG-709fbf58142a0ba4111528e8b18cbd25e4943a6effdcf1c3e99b77b381af4003-20221120040004Z-e224a36685a40ac4

**Comment by DentonGentry** [comment]
`tailscaled` thinks it should use resolved to configure DNS:
```
2022-11-20 04:21:44.794277872 +0000 UTC: dns: using *dns.resolvedManager
```

When it tries to use DBus to configure resolved, there is no DBus daemon:
```
2022-11-20 04:21:44.797827663 +0000 UTC: dns: dbus connection error: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
```

You should either hook up DBus within the container, or remove resolved and let `tailscaled` decide to overwrite /etc/resolv.conf instead.

**Comment by koalang** [comment]
> 

thanks for your reply. I think I don't need to use the tailscaled to manage DNS. So shall I need to remove /etc/resolv.conf in my host or container?

**Comment by DentonGentry** [comment]
You can use: `tailscale up --accept-dns=false` if you don't want `tailscaled` to apply DNS settings.

**Comment by koalang** [comment]
thanks!
I modified my docker-compose.yaml to share dbus socket with host, it fixed it.
here is my yaml file
`version: '3.3'
services:
    tailscaled:
        container_name: tailscaled
        image: tailscale/tailscale
        network_mode: host
        privileged: true
        restart: always
        cap_add:
            - net_admin
            - sys_module
        volumes:
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            - /var/run/tailscale:/var/run/tailscale
            - ./lib:/var/lib
            - /dev/net/tun:/dev/net/tun
        command: sh -c "mkdir -p /var/run/tailscale && ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock && tailscaled"`

**Comment by cubimol** [comment]
This additional parameter fixes the error for me when I create the tailscale container:

...
-v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro \
...
