### ISSUE TITLE
ipn: get rid of IPN wire protocol, finish migration to HTTP everywhere

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6417]
The ipnserver has two protocols: the "IPN message bus" (streaming 4 byte length + JSON) ipn.Notify / ipn.Commands, and HTTP.

We almost entirely use HTTP these days, but some IPN message bus users remain.
 
Tracking bug to completely migrate to HTTP to simplify code.

/cc @maisem @mihaip

**Comment by mihaip** [comment]
Closing this out, all clients have migrated to LocalAPI/watch-ipn-bus, and the old wire protocol is gone. Followup work is being tracked separately (e.g. tailscale/corp#8983).
