### ISSUE TITLE
Tailscale doesn't remove its Ethernet Adapter and Windows cannot remove it either

### ISSUE THREAD

**Issue by MickPBduece** [tailscale/tailscale#6433]
### What is the issue?

Uninstalled Tailscale app and experience network issues on device software was removed from,  Tried to remove adaper and was not able to errir 0x00071779.  Tried reinstalling to remove the connection but no  joy,  I was able to disable it from powershell but still unable to remove it. 

Windows 10  
Reference "Tailscale installer not installing interface once interface got uninstalled manually (on Windows 10) #1327"

### OS

Windows

### Tailscale version

The leaky one

**Comment by bradfitz** [comment]
Can you include a version or bug report or Tailscale IP? And this is windows 10? Which exact version?

Cc @dblohm7

**Comment by bradfitz** [comment]
Dup of #3834, #4944, etc?

**Comment by MickPBduece** [comment]
Def not like 4944.  Maybe 3834 but a lot more like  6433.

I've moved on for now.  I'll be back when the clients are a bit more sorted
so no screaming will happen if it's closed - Just want to note that there
was a gap in the removal process.

**Comment by MickPBduece** [comment]
Win 10.

Tailscale v1.32.1 to the best of my knowledge. I removed it before sending
the email and removed it from Tailscale.com as well.
