### ISSUE TITLE
Tailscale SSH: LocalForward to unix socket does not work

### ISSUE THREAD

**Issue by jakob** [tailscale/tailscale#6441]
### What is the issue?

I'm trying to open a tunnel to a PostgreSQL server listening on a unix socket.

This is probably related to #6232 (RemoteForward does not work for unix socket)

### Steps to reproduce

Open an SSH tunnel with Tailscale SSH to the PostgreSQL server

```bash
ssh -L1234:/var/run/postgresql/.s.PGSQL.5432 postgres@100.x.x.x
```

Then try to connect to that server:

```bash
psql -h localhost -p 1234
```

Doesn't work, SSH says:
```
channel 3: open failed: unknown channel type: unsupported channel type
```

### OS

Linux, macOS

### Tailscale version

1.32.3

**Comment by DentonGentry** [comment]
I think we'll cover this case in https://github.com/tailscale/tailscale/issues/6232 as well, both would be resolved by port forwarding to unix sockets.

Dup of https://github.com/tailscale/tailscale/issues/6232
