### ISSUE TITLE
FR: Update ACL to forbid clients to connect tailnet when they don't match security policies

### ISSUE THREAD

**Issue by gpoudrel** [tailscale/tailscale#6455]
### What are you trying to do?

For example : 
os:windows version:<1.32.3
I would like to forbid all machines matching this version to use the tailnet to comply to our security policies.
I could delete all machines manually and approve them one by one manually but it is a tedious process.

### How should we solve this?

Add some ACL rules to filter machines that violates security policies.

### What is the impact of not solving this?

Ask the users to update themselves, or in the worst case deleting all machines and approve them again one by one.

**Comment by stevetrease** [comment]
Having worked in enterprises where we blocked users running outdated software (for security and compliance reasons), I'd like to second this request.

I would imagine an ACL option that would allow a minimum version of the Tailscale client to be specified along with a date deadline. 
Clients attempting to connect with older clients than the specified versions after the date would not be able to connect to the tailnet. Ideally a message would be shown to the user along the lines of "you must be running version X of Tailscale to be able to connect - please update".

**Comment by icio** [comment]
Hi @gpoudrel, yesterday we launched a [device posture beta](https://tailscale.com/blog/device-posture) which, among other things, allows you to configure device posture ACLs rules which permit connections according to your own rules. 

I believe the following would fit your needs:

```js
{
	// ... ACL file ...
	"postures": {
		"posture:notWin": ["node:os != 'windows'"],
		"posture:win": ["node:os == 'windows'", "node:tsVersion >= '1.33'"],
	},
	"defaultSrcPosture": ["posture:notWin", "posture:win"],
}
```

Or can define `srcPosture` on a per-ACL basis (or [per-grant](https://tailscale.com/blog/acl-grants)). For example:

```js
{
	// ... ACL file ...
	"postures": {
		"posture:notWin": ["node:os != 'windows'"],
		"posture:win": ["node:os == 'windows'", "node:tsVersion >= '1.33'"],
	},
	"acls": [
		// Allow all connections (except insecure windows TS versions)
		{
			"action":     "accept",
			"users":      ["autogroup:member"],
			"srcPosture": ["posture:notWin", "posture:win"],
			"ports":      ["*:*"],
		},
	],
}
```

For more information (including which other attributes can be used in posture conditions), please see: [Device Posture Management](https://tailscale.com/kb/1288/device-posture).

I hope this helps, and please do let us know how you get on. I'll close this ticket for now, but please feel free to re-open if you have any further questions or sticking points -- we'll try to assist.
