### ISSUE TITLE
Tailscale on macOS App Store Update does not appear

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#6456]
### What is the issue?

We have found that when Tailscale releases an update to the App Store, it does not appear as an available update. We need to search for Tailscale and the click on the app in the search results to get the UPDATE text to appear.

### Steps to reproduce

Wait for Tailscale update, check for update in App Store, find that Tailscale update is not available.

### OS

macOS

### OS version

macOS Ventura 13.0.1

### Tailscale version

Any recent.

**Comment by DentonGentry** [comment]
The App Store is set to a 7 day rollout. It offers the update to 1% of devices on the first day, 2% on the second, then 5%, 10%, 20%, 50%, and finally to all devices on the 7th day after the rollout starts.

If you search for the app in the App Store deliberately, it will offer the current version regardless of where it is in the rollout schedule.

**Comment by stevetrease** [comment]
In the MacOS App Store app, you can use the Store -> Reload Page menu item to show all pending updates even if partially though the rollout mentioned above.

**Comment by DentonGentry** [comment]
At this point I think this is just expected behavior in the App Store.
