### ISSUE TITLE
Client restart can't connect to other clients if coordination server is down

### ISSUE THREAD

**Issue by joaofrf** [tailscale/tailscale#6458]
### What is the issue?

If I turn off the coordination server while my clients can communicate It works perfectly.
However if a client restarts his computer he can no longer communicate with the other clients until the server is back online.

### Steps to reproduce

- Install 2 tailscale clients (I used 2 windows computers)
- Connect them to the coordination server.
- Ping one another to verify connection (should be ok)
- Turn server off
- Ping one another to verify connection (should be ok)
- Restart one of the clients (server still off)
- We can no longer ping (it should have "resumed" last "session" ?)

### OS

Windows

### OS version

windows 10 pro | 10.0.19044 Build 19044

### Tailscale version

1.32.2

### Bug report

BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

**Comment by DentonGentry** [comment]
This is fairly fundamental to the design of the service: the coordination server sends updates, called netmaps, to all nodes on the tailnet communicating the public node keys, home DERP server, and other information. Once a node has a netmap update cached it can continue to function, at least for a while, even if the coordination server becomes unavailable. Nodes can make connections and negotiate wireguard sessions and so on.

If a node becomes active and there is no coordination server, it doesn't know about other nodes on the tailnet.

**Comment by DentonGentry** [comment]
Closing as not planned.

**Comment by ghost** [comment]
I experienced a loss of tailnet reachability during a long Internet outage.  One of the issues I noted is that when nodes restart they come back up not logged in and then from there nothing works for that node.  Why wouldn't we want nodes to start with the last known map (saved as part of the tailscaled state), and then try to refresh it from the coordination server?
