### ISSUE TITLE
Failed to setup adapter

### ISSUE THREAD

**Issue by cewei** [tailscale/tailscale#6461]
### What is the issue?

Unable to create adapter

logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.32.3-ta07555f43-g093d1e978, Go 1.19.2-ts3fd24dee31: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe"}
LogID: f73301be6449409dc0e7f189717bdfcdcb9b802efe68ccd0131387910c962940
logpolicy: using dir C:\ProgramData\Tailscale
wgengine.NewUserspaceEngine(tun "Tailscale") ...
Installing driver 0.14
Extracting driver
Installing driver
Creating adapter
Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
Failed to setup adapter (problem code: 0x1C, ntstatus: 0xC0000490): There was no match for the specified key in the index. (Code 0x00000491)
no TUN failure diagnostics for OS "windows"
wgengine.NewUserspaceEngine(tun "Tailscale") error: tstun.New("Tailscale"): Error creating interface: There was no match for the specified key in the index.
flushing log.
logger closing down
createEngine: tstun.New("Tailscale"): Error creating interface: There was no match for the specified key in the index.

### Steps to reproduce

Updated to the latest version of tailscale

Have uninstalled and reinstalled tailscale

### Are there any recent changes that introduced the issue?

Update to the latest version of tailscale

### OS

Windows

### OS version

Windows 10 Pro 22H2

### Tailscale version

1.32.3

**Comment by cewei** [comment]
The issue was due to wintun drivers not being removed after uninstallation.

To resolve the issue, the following was done.
1) Export the list of drivers in the table form to a text file using the command:
dism /online /get-drivers /format:table > c:\drivers.txt

2) Find wintun or wireguard from the list, and note the "Published Name", oemNN.inf

3) Remove the driver using the command:
pnputil.exe /d oemNN.inf

**Comment by metorm** [comment]
> The issue was due to wintun drivers not being removed after uninstallation.
> 
> To resolve the issue, the following was done.
> 
> 1. Export the list of drivers in the table form to a text file using the command:
>    dism /online /get-drivers /format:table > c:\drivers.txt
> 2. Find wintun or wireguard from the list, and note the "Published Name", oemNN.inf
> 3. Remove the driver using the command:
>    pnputil.exe /d oemNN.inf

Thanks a lot, this saved my day!

**Comment by ctracerpp** [comment]
> The issue was due to wintun drivers not being removed after uninstallation.
> 
> To resolve the issue, the following was done.
> 
> 1. Export the list of drivers in the table form to a text file using the command:
>    dism /online /get-drivers /format:table > c:\drivers.txt
> 2. Find wintun or wireguard from the list, and note the "Published Name", oemNN.inf
> 3. Remove the driver using the command:
>    pnputil.exe /d oemNN.inf

tks

**Comment by Morrigan-Ship** [comment]
> The issue was due to wintun drivers not being removed after uninstallation.
> 
> To resolve the issue, the following was done.
> 
> 1. Export the list of drivers in the table form to a text file using the command:
>    dism /online /get-drivers /format:table > c:\drivers.txt
> 2. Find wintun or wireguard from the list, and note the "Published Name", oemNN.inf
> 3. Remove the driver using the command:
>    pnputil.exe /d oemNN.inf

not work for me
success removed and i rebooted my windows
i checked and im sure it removed.
but same error again
