### ISSUE TITLE
FR: Local proxy server

### ISSUE THREAD

**Issue by juev** [tailscale/tailscale#6463]
### What are you trying to do?

Currently we have option for use exit-node. All traffic should go to exit node.

### How should we solve this?

But I need setup socks5 or http proxy server for using one of my node to exit. All other traffic should go directly.
Can we run socks5 proxy server for use exit node?

### What is the impact of not solving this?

I know we can run Tailscale on Linux to use usermode and run socks5. But how we can use it on Macos? And when Tailscale run in normal mode?

**Comment by DentonGentry** [comment]
You can compile the same tailscale client for macOS as runs on Linux: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

It can be started with the `--tun=userspace-networking` option and for SOCKS5 and/or HTTP proxying, so your app can connect to the tailnet by using the proxy.

--------

Depending on your app, https://github.com/tailscale/tailscale/tree/main/tsnet might also be useful. It is a way to embed a Tailscale client within a single process, so your app would get its own IP address on the tailnet independent of the machine it is running on.

**Comment by juev** [comment]
@DentonGentry thank you! 

One more, can I use MacOS Tailscale client from App Store and additional Tailscale client, which I can compile? Is it possible?

I need to use my tailnet directly as most, and one exit-node for several Internet addresses.

**Comment by DentonGentry** [comment]
Yes, you can run the App Store client for most macOS use and additionally run a `tailscaled --tun=userspace-networking` which will allow outgoing connections for clients which use it as a SOCKS5 or HTTP proxy.

Really though: please try it. We won't have specific answers for every aspect of whatever it is you are developing, please try it.

**Comment by juev** [comment]
Thank you very much!
