### ISSUE TITLE
 Tailscale on Mac constantly opening OAuth/login page

### ISSUE THREAD

**Issue by Vorror** [tailscale/tailscale#6464]
### What is the issue?

Every 30 seconds, Tailscale constantly and automatically opens my browser to the Tailscale login page. I'm the sole/singular user of my Tailscale, and this issue happens even when I'm not at my computer(so I'm not the one accidentally triggering this issue). After login, the issue will go away for a few hours/day but then come back.

My browser then looks like this after 2-3 minutes:
![CleanShot 2022-11-23 at 12 05 45@2x](https://user-images.githubusercontent.com/3613230/203607135-ef265e68-4b0b-43d1-802b-36017d81be26.png)

### Steps to reproduce

Install the mac app store version

### Are there any recent changes that introduced the issue?

none

### OS

macOS

### OS version

12.3.1

### Tailscale version

1.32.3

### Bug report

BUG-7f65e4d10cfcb419de5edd03816c85ecb4893830059b5101a20f30111d1adb52-20221123171332Z-056c26ee9d0f9fe4

**Comment by mihaip** [comment]
Do you by any chance have a Tailscale SSH session open via VSCode remote development (or similar tooling). The default for Tailscale SSH is to use check mode every 12 hours, and we have a known issue (#6086) where if the client keeps trying to reconnect (the way VSCode does) then we keep triggering the check mode auth window.

**Comment by Vorror** [comment]
> Do you by any chance have a Tailscale SSH session open via VSCode remote development (or similar tooling). The default for Tailscale SSH is to use check mode every 12 hours, and we have a known issue (#6086) where if the client keeps trying to reconnect (the way VSCode does) then we keep triggering the check mode auth window.

I'm not no.

**Comment by mihaip** [comment]
I do see that there's a node running Tailscale SSH on your tailnet (IP 100.103.6.4), and your Mac attempts to SSH to it before every login URL open request. Is there another process running on your machine that could be doing that?

**Comment by Vorror** [comment]
> I do see that there's a node running Tailscale SSH on your tailnet (IP 100.103.6.4), and your Mac attempts to SSH to it before every login URL open request. Is there another process running on your machine that could be doing that?

Now that you mention it, I'm using [Cloud Mounter](https://cloudmounter.net/). If Tailscale SSH is the issue, then I'll disable it.

**Comment by DentonGentry** [comment]
>Now that you mention it, I'm using [Cloud Mounter](https://cloudmounter.net/). If Tailscale SSH is the issue, then I'll disable it.

Or change from `check` mode to `accept` for destinations where you don't want to have to re-approve every 12 hours.

**Comment by DentonGentry** [comment]
I think this was the interaction of Cloud Mounter with Tailscale SSH and a `check` policy which would need a new approval every N hours.
