### ISSUE TITLE
FR: Router Client

### ISSUE THREAD

**Issue by adminy** [tailscale/tailscale#6474]
### What are you trying to do?

Trying to Simplify the steps for users connected to the home network.
Instead of going to every device and installing the tailscale app, I could just install it on the router, since the router is a linux box. However this does not have the ability of registering each individual user's machine, only the router machine itself.

### How should we solve this?

Can tailscale client specify devices if its the router lets say.

### What is the impact of not solving this?

Complicated setup and downloading the tailscale app many many times, lots of manual work.
Also the devices don't have to have VPN software running, meaning less resource utilisation.

### Anything else?

I found something relevant perhaps to this, which is [setting tailscale client as a subnet router](https://tailscale.com/kb/1019/subnets/#setting-up-a-subnet-router)

**Comment by DentonGentry** [comment]
Would the subnet router feature do what you're looking for?
https://tailscale.com/kb/1019/subnets/

**Comment by adminy** [comment]
Does it add every device on that subnet to tailscale list of devices? how does it ensure the uniqueness of each device?

**Comment by DentonGentry** [comment]
It is a router. If your LAN is 172.16.0.0/24, it lets you reach devices by their 172.16.0.1 IP address.

**Comment by adminy** [comment]
What about hostnames? can the tailscale client also resolve them too?

**Comment by DentonGentry** [comment]
MagicDNS supplies hostnames for Tailscale 100.x.y.z IPs. The intent for the subnet router would be to add whatever DNS server handles that subnet as a [Split DNS resolver](https://tailscale.com/learn/why-split-dns/).

For example when exporting VPC addresses for an AWS subnet, one adds the AWS Route53 DNS server: https://tailscale.com/kb/1021/install-aws/

For a home LAN, one would likely point to the Tailscale IP address of the router and rely on its dynamic DNS entries when it hands out a DHCP lease to LAN clients.

**Comment by adminy** [comment]
So then the tailscale client acts as a DHCP server and leases tailscale ips to LAN clients?

**Comment by DentonGentry** [comment]
LAN clients get their IP addresses from a router on your LAN, like the Wi-Fi AP. Many Wi-fi APs will dynamically add a hostname when they give out an address.

If your Wifi AP is 192.168.1.1 and is set to have its search domain be example.com, one could add a [Split DNS resolver](https://tailscale.com/learn/why-split-dns/) for example.com pointing to 192.168.1.1 as its DNS server. This lets nodes on the tailnet get DNS lookups for devices on the LAN.

**Comment by augustz** [comment]
This overlaps with #6184 potentially a bit.

**Comment by DentonGentry** [comment]
I believe this is fundamentally the same request as https://github.com/tailscale/tailscale/issues/6184, marking as duplicate.
