### ISSUE TITLE
Mac 13.0.1 can't log in.

### ISSUE THREAD

**Issue by Joy0934** [tailscale/tailscale#6483]
### What is the issue?

1.I can't log in with tailscale, and after installing from app stroe, I can't get any response when I click to log in to your network.
2.I exported the debug file using the tailscale bugreport, but I can't find the file locally.

### Steps to reproduce

<img width="413" alt="image" src="https://user-images.githubusercontent.com/102337639/203710532-9b32aaf2-212f-4d9a-b400-c07d3d21c42d.png">

### OS

macOS M1

### OS version

Ventura 13.0.1

### Tailscale version

1.32.3

### Bug report
BUG-aa8fcba04e8f2f1481cc11fdf4019c21f64d700ca51638cf9741c9f3292acd58-20221124063539Z-e676fe00107d8863

**Comment by DentonGentry** [comment]
Does this mean it ultimately worked, or not?
https://tailscale.com/contact/support/ is a way to get more immediate attention to a specific case, GitHub issues are periodically triaged but often not responded to immediately upon filing.
