### ISSUE TITLE
Dead link from incident response-policy to incident response process

### ISSUE THREAD

**Issue by alf** [tailscale/tailscale#6484]
### What is the issue?

The link is dead. It's dangling. It's not bringing joy.

https://github.com/tailscale/policies/blob/dc8c847f5192df07adb3671c4fa821aa3b9c0280/incident-response/index.md?plain=1#L43

### Steps to reproduce

I browsed your web looking for information. Then suddenly, disaster struck.

**Comment by bradfitz** [comment]
Cc @mayakacz @twitchyliquid64

**Comment by mayakacz** [comment]
These are to internal documents that are not public. Since these are our source of truth policies, they still need to link to some internal content, even if the policies themselves are public.
See https://github.com/tailscale/policies#why-are-some-links-broken-like-to-the-code-of-conduct
