### ISSUE TITLE
tshello: HTTPS broken due to wrong fqdn

### ISSUE THREAD

**Issue by andig** [tailscale/tailscale#6485]
### What is the issue?

HTTPS access doesn't work, even in `tshello`:

```
curl -v https://tshello.tail7b846.ts.net
*   Trying 100.86.202.95:443...
* Connected to tshello.tail7b846.ts.net (100.86.202.95) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
* Closing connection 0
curl: (35) error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
```

Log:

```
2022/11/24 09:57:18 http: TLS handshake error from 100.98.84.106:61084: 500 Internal Server Error: invalid domain "tshello.tail7b846.ts.net"; must be one of ["skynetm1.tail7b846.ts.net" "skynetm1.tail7b846.ts.net"]
2022/11/24 09:57:20 http: TLS handshake error from 100.98.84.106:61090: 500 Internal Server Error: invalid domain "tshello.tail7b846.ts.net"; must be one of ["skynetm1.tail7b846.ts.net" "skynetm1.tail7b846.ts.net"]
```

It seems that the cert is requested for the wrong domain name, i.e. the fqdn of the host machine instead of the running `tshello` application.

Note: also the docs are wrong, the mention "HTTP Settings" which don't exist in the tailscale admin ui.

### Steps to reproduce

    go run tailscale.com/tsnet/example/tshello -addr :443

### Are there any recent changes that introduced the issue?

No

### OS

macOS

### OS version

macOS 13

### Tailscale version

main

**Comment by andig** [comment]
Nvm, local error. Example needs update to use `lc.GetCertificates`.

**Comment by bradfitz** [comment]
Reopening. Valid bug. We'll fix the example. Cc @maisem for honor of touching that code last. :)

**Comment by andig** [comment]
If you want to fix that you may want to touch https://tailscale.com/kb/1153/enabling-https/?q=http#configure-https, too:

> 3) Under HTTPS Certificates, click Configure HTTPS.

There is no such setting.
