### ISSUE TITLE
FR: Limit route advertisement to certain members of the tailnet

### ISSUE THREAD

**Issue by henricook** [tailscale/tailscale#6486]
### What are you trying to do?

Given a tailnet of machines A,B,C,D with machine A advertising routes to 10.1.x.x

It would be nice to be able to limit/permission/firewall which machines can use the routes being advertised by machine A

i.e. "Allow machine B only to use routes advertised by A"

At the moment I think the only option is to have all machines on the tailnet see and use by default the routes that A is advertising.

**Comment by adminy** [comment]
Isn't that an exit node's function? you can create groups and specify which groups use which exit node or which don't.

**Comment by henricook** [comment]
Hmm @adminy - I can advertise routes on Machine A and use those routes from Machine B without making Machine A an exit node. I don't want to route all of B's traffic through A, just particular routes.

**Comment by adminy** [comment]
So you want machine B to belong to multiple subnets then? @henricook

**Comment by henricook** [comment]
Machine B can access the internet via its own interfaces, but any connections to 10.1.x.x I route via Machine A

**Comment by adminy** [comment]
So in that case you just need a subnet mask.
Tailscale routes traffic over the shortest path possible so If you just make it so that the path is not accessible for the node, it will route it directly rather than through tailscale.

**Comment by henricook** [comment]
Sure, so i could go to every node and add a route for 10.1.x.x that would stop them using Machine A.. but that's pretty manual. I was requesting here tailscale add something like an "advertise routes **for machines** where you can limit the machines that'll set the advertised routes"

**Comment by DentonGentry** [comment]
> i.e. "Allow machine B only to use routes advertised by A"

This would typically be handled using ACLs: anything not allowed is denied. If one removes the accept for `\*:\*` which new tailnets are populated with in https://login.tailscale.com/admin/acls, one can then write an ACL of what sources are allowed to access the subnet route, for example tags or or the specific IP address of a node:

```
	"Hosts": {
		"machineB":                 "100.99.98.97",
        },
	"ACLs": [
		{
			"Action": "accept",
			"Users":  ["tag:allowthese", "machineB"],
			"Ports":  ["10.1.0.0/16:*"],
		},
```

**Comment by DentonGentry** [comment]
Closing as addressed by ACLs.
