### ISSUE TITLE
Windows: IPv4 connection doesn't work after client update to 1.32.3, IPv6 still works.

### ISSUE THREAD

**Issue by mkrautz** [tailscale/tailscale#6487]
### What is the issue?

User on our tailnet upgraded to Windows client 1.32.3. The user was already connected using the older client.

After the upgrade, IPv4 connections couldn't be made inside the tailnet.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/36527/203808455-9e1c3605-4c63-43a4-a108-9688b370c3f7.png)

IPv6 connections did still work, however:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/36527/203808869-de512028-93d4-4a3c-9c42-3c4016e5d4bd.png)

After rebooting the computer, the issue was fixed.

### Steps to reproduce

1. Upgrade to 1.32.3
2. User can't connect to the internal service via DNS: https://gitea.XXXXXX-XXXXXX.ts.net.
3. Manually using curl to fetch the page via IPv6 does work.
4. Manually using curl to fetch the page via IPv4 does not work.
5. Rebooting fixes the problem.

### Are there any recent changes that introduced the issue?

User upgraded to 1.32.3.

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.32.3

### Bug report

BUG-61dc3fa56be7af3d8413e9ee12a4daf431f28e5314754ac08c1d04992d55cc2e-20221124142735Z-0154bf681f17879b

**Comment by DentonGentry** [comment]
Oddly, around the time of the bugreport we don't see any attempts to access port 80 only port 443 (which does work):
```
2022-11-24 14:24:25.9500869 +0000 UTC: Accept: TCP{100.80.246.x:56765 > 100.97.28.122:443} 52 ok out
2022-11-24 14:25:15.6559572 +0000 UTC: Accept: TCP{100.80.246.x:56812 > 100.97.28.122:443} 52 ok out
2022-11-24 14:25:15.6913951 +0000 UTC: Accept: TCP{100.97.28.122:443 > 100.80.246.x:56812} 52 tcp non-syn
2022-11-24 14:25:15.6913951 +0000 UTC: Accept: TCP{100.80.246.x:56812 > 100.97.28.122:443} 40 ok out
2022-11-24 14:26:39.4966428 +0000 UTC: Accept: TCP{100.80.246.x:57304 > 100.97.28.122:443} 52 ok out
```

I believe that curl prints "bad access" when it gets a TCP RST, and Tailscale never sends an RST. Might something else be blocking access, like Kaspersky or other antivirus?

**Comment by DentonGentry** [comment]
> I believe that curl prints "bad access" when it gets a TCP RST, and Tailscale never sends an RST. Might something else be blocking access, like Kaspersky or other antivirus?

Barring further update, we'll assume that the RST was sent by other software on the device and close this during the next regular bug scrub.

**Comment by mkrautz** [comment]
We haven't encountered it since, so it was probably some kind of anti-virus that triggered it. I'll close. Thanks!
