### ISSUE TITLE
Group Policy Administrative Templates for Windows

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#6495]
Admins can import these into the group policy editor for their domain.

https://learn.microsoft.com/en-us/windows/client-management/understanding-admx-backed-policies
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753471(v=ws.10)

**Comment by sailorfrag** [comment]
This still needs some packaging to distribute it, I filed #10767 for that.

In the meantime, you can find the administrative template in https://github.com/tailscale/tailscale/tree/main/docs/windows/policy

**Comment by boonedoggle** [comment]
Amazing. Thanks @sailorfrag. It imported just fine on my end and I'm able to control the settings.

**Comment by sailorfrag** [comment]
If you run into any problems, feel free to file an issue about it; I'm pretty sure I got it mostly right but this is my first time writing one of these. I'll probably notice a comment on here but any changes will work better attached to a fresh issue.
