### ISSUE TITLE
FR: Family Plan

### ISSUE THREAD

**Issue by LeaderbotX400** [tailscale/tailscale#6501]
### What are you trying to do?

I am trying to share my tailnet with my family who all have emails on the same domain ([lastname]family.[tld]) which means they are added to my tailnet. This would be fine, but I am concerned I will eventually hit some hard limit by doing this.

### How should we solve this?

Either a family plan that could be just a personal plan but with the user count bumped up or it could be like the GitHub Community Plan, but can accept other auth providers (in my case it would be Microsoft)

### What is the impact of not solving this?

I simply will just use OpenVPN for those who need closer access and cloudflare tunnels/zero trust for everyone else

**Comment by DentonGentry** [comment]
The Community plan is free and suitable for friends and family use. https://tailscale.com/blog/community-github-pricing/#:~:text=This%20plan%20is%20also%20available%20to%20families%20and%20friends

Sign up at https://tailscale.com/pricing/, search for Community.

**Comment by LeaderbotX400** [comment]
@DentonGentry 
to quote tailscales own site 
> "The GitHub Community plan is not available to non-GitHub organization Tailscale domains."

as our emails are through Microsoft being <lastname>family.<tld> tailscale does not accept that as valid.

It is possible that I have not done this correctly in which case I would love to here how to do this properly

**Comment by DentonGentry** [comment]
Please contact support https://tailscale.com/contact/support/, we can't handle details of accounts on public bugs.

**Comment by mayakacz** [comment]
Suggest re-opening this FR as "Community plan for non-GitHub orgs / Family plan". We hear that request.
Agree re: no details of accounts.
