### ISSUE TITLE
FR: Show app icon in System Settings/VPN (MacOS Ventura)

### ISSUE THREAD

**Issue by labac-p** [tailscale/tailscale#6503]
### What are you trying to do?

Show app icon in System Settings/VPN (MacOS Ventura)

<img width="500" alt="Screenshot 2022-11-25 at 10 55 39" src="https://user-images.githubusercontent.com/100670919/203898543-593677cf-80d0-4d7e-a7b8-ec19203161ce.png">

**Comment by nickoneill** [comment]
In this screenshot the macsys app shows the icon, but the App Store one does not. These are built with the same Xcode version which would be my first guess, I'll have to look at the asset used in more detail.

<img width="479" alt="Screenshot 2022-11-28 at 9 54 42 AM" src="https://user-images.githubusercontent.com/49688/204347448-adeb6843-14e5-4f14-b380-bbf9a3858d92.png">

**Comment by agottardo** [comment]
This appears to be fixed as of today on macOS Sonoma. Please leave a comment if you are still hitting this.
