### ISSUE TITLE
AMD Geode support?

### ISSUE THREAD

**Issue by ivomarino** [tailscale/tailscale#651]
Hi all, currently running OpenWrt on an Alix board, specifically:

```
dmesg | grep -i geode
[    0.065969] CPU: Geode(TM) Integrated Processor by AMD PCS (family: 0x5, model: 0xa, stepping: 0x2)
[    0.469734] AMD Geode RNG detected
[    7.040199] Geode LX AES 0000:00:01.2: GEODE AES engine enabled.
```

any chance to get tailscale running on this CPU? Actually none of the static bins from https://pkgs.tailscale.com/stable/#static seem to run. Thanks in advance for feedback on this;)

**Comment by bradfitz** [comment]
https://blog.nella.org/golang-on-the-geode-processor/ says you need to build it with `GO386=387 GOARCH=386`.

So on your main desktop, build it (https://github.com/tailscale/tailscale#building) like:

```
$ cd /wherever/src/tailscale
$ GO386=387 GOARCH=386 go build -o tailscaled.geode tailscale.com/cmd/tailscaled
$ GO386=387 GOARCH=386 go build -o tailscale.geode tailscale.com/cmd/tailscale
```

@danderson, should we add this type of binary to the static binary page? (pre-SSE 386)  Note that Go is likely dropping compiler support for these in the next release (https://github.com/golang/go/issues/40255), but gccgo will continue to work. It does mean that if we start shipping these, we'll need to switch our build to use gccgo later just for this port.

**Comment by ivomarino** [comment]
thanks for this great info, yes a pre built bin would be super great;) think many folks out there would like to run it on Geode!;)

**Comment by bradfitz** [comment]
"many" might be pushing it. :)

**Comment by bradfitz** [comment]
Update on this. It's not going away in the main Go compiler. In Go 1.16 you do `GO386=softfloat` instead:

https://tip.golang.org/doc/go1.16#386

So we could distribute these binaries.

**Comment by bradfitz** [comment]
Reopening until they're available at https://pkgs.tailscale.com/unstable/#static

**Comment by DentonGentry** [comment]
Still not present on https://pkgs.tailscale.com/unstable/#static
I don't understand what is left to be done.

**Comment by DentonGentry** [comment]
The packages server now serves up a specific Geode tarfile: https://pkgs.tailscale.com/stable/#static
