### ISSUE TITLE
Install `tailscale` CLI on macOS

### ISSUE THREAD

**Issue by mrhappyma** [tailscale/tailscale#6524]
Hello, I was trying to install tailscale using the instructions [on the wiki page](https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS). It worked to install the `tailscaled` process, but the `tailscale` command still seems missing. How can I install it?

I am running quite an old version of macOS, version 10.13.6

**Comment by DentonGentry** [comment]
That will place the `tailscale` binary in (most likely) $HOME/go/bin, which may not be in your shell's $PATH. You could:
- add ~/go/bin to PATH, or
- copy ~/go/bin to /usr/local/bin/tailscale which most likely is in your $PATH

**Comment by bradfitz** [comment]
Or use the Tailscale CLI that comes bundled with the App Store GUI client:

https://tailscale.com/kb/1080/cli/?tab=macos

It's at `/Applications/Tailscale.app/Contents/MacOS/Tailscale`

**Comment by mrhappyma** [comment]
thanks!
