### ISSUE TITLE
WebSSH, safari, first connection after reauth always ends up with blank window

### ISSUE THREAD

**Issue by ldemailly** [tailscale/tailscale#6536]
### What is the issue?

From admin console; click "SSH" pick user; prompted for google auth; success... blank window
(no visible error when inspecting)
<img width="675" alt="Screenshot 2022-11-27 at 4 02 44 PM" src="https://user-images.githubusercontent.com/3664595/204167005-248cae2f-36bf-4e2f-88cb-389599593696.png">

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

It's been happening since first release of webssh I used and started to bother me enough to report finally today
(safari and macOS upgraded a few times but still happening)

Safari Version 16.1 (18614.2.9.1.12)

### OS

macOS

### OS version

ventura 13.0.1

### Tailscale version

1.32.3

### Bug report

BUG-eb189efb6533cbf227afd00b6e6eae57cac3c810e0051bf9c644e1c7d30f0c77-20221128000523Z-bc517502f465a482

**Comment by mihaip** [comment]
Thank you for reporting this. Looks like Safari does not consistently fire an `unload` event after the auth flow completes, will attempt to work around it.

**Comment by mihaip** [comment]
Fix expected to be deployed later today.

**Comment by mihaip** [comment]
@ldemailly the fix has been deployed, I'm no longer able to reproduce this.

**Comment by ldemailly** [comment]
confirmed it's fixed for me now, thanks
