### ISSUE TITLE
cmd/tailscale/cli: docs don't specify that "serve" is unavailable in the stable CLI version

### ISSUE THREAD

**Issue by mvdan** [tailscale/tailscale#6540]
### What is the issue?

I'm trying to set up Funnel per https://tailscale.com/kb/1223/tailscale-funnel/, which told me to run commands like:

```
$ tailscale serve status
USAGE
  tailscale [flags] <subcommand> [command flags]
[...]
```

I was really confused for a solid fifteen minutes, to the point that I started digging into the source to see if the `serve` command was somehow broken. Only later I found https://tailscale.com/blog/introducing-tailscale-funnel/, which says:

> The functionality will be available in a stable release starting in Tailscale v1.34.0 but meanwhile you’ll need to be running a recent [unstable build](https://pkgs.tailscale.com/unstable/) (v1.33.257 or later) to try it out.

I think you should clarify this in the docs page above; it says nothing about running an unstable version of the CLI. Arguably you could say I should have read the blog post before I read the docs, but I happened to find the docs first, and I think that page should be enough for me to set up Funnel.

For what it's worth, I solved this via `go install tailscale.com/cmd/tailscale@main`.

### OS

Linux

### Tailscale version

1.32.3

### Bug report

BUG-819bb4055bd569aa8efa72d1b77e98ebba7caf6fb891c8f7ac97803abde84513-20221128134039Z-0cfc7dac7e75f28e

**Comment by bradfitz** [comment]
Your first link to the KB says:

"Tailscale Funnel is currently [in alpha](https://tailscale.com/kb/1167/release-stages/#alpha). To try it, follow the steps below to enable it for your network using Tailscale v1.33.257 or later."

**Comment by mvdan** [comment]
Oh, that does say "v1.33.257 or later". I missed that as I immediately thought "I'm already in the alpha, so I'm good". I didn't think about an alpha _version of the software_ as well. I think I wouldn't have missed it if it said "unstable build", as that immediately jumped out to me from the blog post :)

**Comment by DentonGentry** [comment]
This should resolve itself in the relatively near future when we release 1.34.0. The next stable release will contain everything that was in 1.33.x.

**Comment by mvdan** [comment]
Oh for sure - feel free to close. My only input is that alpha/unstable warnings in the docs shouldn't be easy to overlook :) I assume there will be others in the future.

**Comment by DentonGentry** [comment]
1.34.0 shipped today.
