### ISSUE TITLE
FR: Tailscale Docker container should not require priviledged, and run without additional command.

### ISSUE THREAD

**Issue by icsy7867** [tailscale/tailscale#6544]
### What are you trying to do?

I love tailscale and the use case.  So I thought I would offer a couple of things that I observed which may or may not be helpful...

I think the **--privileged** flag is unnecessary and gives the container way more privileges than requires on the docker host.

I would recommend updating your documentation to use:
`--cap-add=NET_ADMIN`
instead of the overkill --privileged.

And perhaps this is by design, but needing to run a second docker exec command also seems superfluous.  I think this command should be integrating into the run command and controlled with the proper flags.

I run a build that I made: (Currently just has flags for Route and Authkey, but very easy to add others)
https://hub.docker.com/repository/docker/icsy7867/tailscale
https://github.com/icsy7867/tailscale

Instead of trying to build the go package, just grab it from a URL and use alpine:latest (or a static version if preferred.)
I simple start script seems to work well for me.  This should make the builld simpler, and not require a second command.  However I do see the benefit and customizability of using docker-compose or kubernetes to manually run a second command.  But I dont think it's necessary.

### How should we solve this?

Modify hub.docker.com pages to implement the net_admin capability and removed priviledges.  Also to take a look at other suggestions if applicable.

### What is the impact of not solving this?

the --privileged flag gives access to MANY (Actually all of them...) different capabilities.
https://www.trendmicro.com/en_us/research/19/l/why-running-a-privileged-container-in-docker-is-a-bad-idea.html

It should be heavily discouraged to use unless absolutely necessary.  This opens several potential threat vectors if not used properly.

### Anything else?

Just my other suggestions on automatically issuing the exec command in your documentation in the container intead of needing to run this second command.  I think this overcomplicates things and shouldnt be needed.  I provided a solution/example as well.  Simple in nature, but some might find it useful.

**Comment by bradfitz** [comment]
cc @maisem @danderson

**Comment by maisem** [comment]
Thanks, will verify and update docs.

**Comment by DentonGentry** [comment]
Verified that `--cap-add=NET_ADMIN --cap-add=NET_RAW` is able to join the tailnet and operate even without setting `--privileged`

Updated DockerHub README: https://hub.docker.com/repository/docker/tailscale/tailscale

**Comment by MrParzival13** [comment]
But i have an issue,some times i need my tailscale to be connected to an exit node, and without --privileged it doesnt work at all.  is there any solution to do it without --privilege?

**Comment by icsy7867** [comment]
Are you trying to run the tailscale as an exit node within the container?  I'm not sure if that's what you mean...  But I am doing this currently (though using podman, not docker.)

```
podman run \
        --rm \
        --replace \
        -d \
        --name=tailscaled \
        -h docker-new \
        -v /My/Path/To/data:/var/lib/tailscale:z \
        -v /dev/net/tun:/dev/net/tun:z \
        -e TS_ROUTES=192.168.1.0/24,192.168.2.0/24 \
        -e TS_STATE_DIR=/var/lib/tailscale \
        --cap-add=NET_ADMIN tailscale/tailscale
```

And you have to approve the routes in the web interface obviously.

**Comment by MrParzival13** [comment]
Im running tailscalein docker. 

Here is my compose at the moment

`name: compassionate_jason
services:
    tailscale:
        cpu_shares: 90
        command: []
        container_name: tailscaled
        deploy:
            resources:
                limits:
                    memory: "4094689280"
        environment:
            TS_AUTHKEY: tskey-auth-****************************************************
            TS_EXTRA_ARGS: --exit-node=100.64.0.2 --exit-node-allow-lan-access
            TS_HOSTNAME: Tiny-NAS
            TS_STATE_DIR: /var/lib/tailscale
            TS_USERSPACE: "false"
        hostname: tailscaled
        image: tailscale/tailscale:latest
        labels:
            icon: https://i.postimg.cc/50pXspRq/7a2af65d5b4d03e85908eaddc6fbdad9.png
        network_mode: host
        privileged: true
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/tailscale/state
              target: /var/lib/tailscale
            - type: bind
              source: /dev/net/tun
              target: /dev/net/tun
            - type: bind
              source: /DATA/AppData/tailscale/config
              target: /config
networks:
    default:
        name: compassionate_jason_default
x-casaos:
    author: self
    category: self
    hostname: ""
    icon: https://i.postimg.cc/50pXspRq/7a2af65d5b4d03e85908eaddc6fbdad9.png
    index: /
    is_uncontrolled: false
    port_map: ""
    scheme: http
    store_app_id: compassionate_jason
    title:
        custom: tailscale`
        
  Only whith "privileged: true" and "TS_USERSPACE: "false"" i am able to connect from it to other exit node
  
  Im noob to all this stuff so i dont really know what you are meaning about routes
