### ISSUE TITLE
FR: update to gvisor `v0.0.0-20221129015920-2aaad2204dda` or later

### ISSUE THREAD

**Issue by andig** [tailscale/tailscale#6554]
### What is the issue?

I had to upgrade gvisor due to https://github.com/google/gvisor/issues/8149:

```
go get -u gvisor.dev/gvisor@go
go: upgraded gvisor.dev/gvisor v0.0.0-20220817001344-846276b3dbc5 => v0.0.0-20221129015920-2aaad2204dda
```

Now build fails:

```
# tailscale.com/net/tstun
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:186:16: undefined: stack.PacketBuffer
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:534:19: invalid operation: res.packet != nil (operator != not defined on untyped nil)
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:728:56: undefined: stack.PacketBuffer
../../go/pkg/mod/tailscale.com@v1.32.3/net/tstun/wrap.go:827:60: undefined: stack.PacketBuffer

```

It would be great to be able to compile and debug tailscale again.

### Steps to reproduce

See above

### Are there any recent changes that introduced the issue?

gvisor upgrade

### OS

macOS

### OS version

13.0

### Tailscale version

1.32.3

**Comment by bradfitz** [comment]
I'm confused. google/gvisor#814 is from 2020/2021. Tailscale was already using gvisor.dev/gvisor v0.0.0-20220817001344-846276b3dbc5 that should include any fixes for that gvisor issue.

Which exact commit(s) from gvisor are you hoping to get into your build?

**Comment by andig** [comment]
Not 814, https://github.com/google/gvisor/issues/8149, sorry!

**Comment by bradfitz** [comment]
Ah, phew. That makes more sense. :)
