### ISSUE TITLE
Can't access shared node consistently. Inconsistent behaviour of `tailscale status`

### ISSUE THREAD

**Issue by Biepa** [tailscale/tailscale#6570]
### What is the issue?

First time using shared nodes. So there may be a mistake on my side.

Are ACLs applied immediately? Do I need to reconnect? Logout and login?

### Steps to reproduce

Two accounts:
Account "Sharer"
1. Node with client version 1.32.3 (Synology NAS, but also tried with a Windows machine)
2. Used this article on how to share: https://tailscale.com/kb/1084/sharing/
3. ACL config:
```
{
	"acls": [
		{"action": "accept", "src": ["*"], "dst": ["*:*"]},
	],
}
```
5. Can see the device in the admin panel of "Receiver"

Account "Receiver"
1. Linux with tailscale running.
2. ACL config:
```
{
	"ACLs": [
		{"action": "accept", "src": ["*"], "dst": ["*:*"]},
	],
}

```
4. `tailscale status` only shows the device currently used. `tailscale down` and up again didn't change anything.
5. Logged out and in again via CLI.
6. `tailscale status` shows the shared node (but one of the Receivers nodes is missing, while being shows "Connected" in the admin panel). Can ping shared node.
7. Wanted to setup ACLs. Changed the ACL above to `{"action": "accept", "src": ["tag:categoryA"], "dst": ["*:*"]}`
8. A node without that tag can still ping the shared node. Why?
9. `tailscale down` and `tailscale up`. Still the same
10.  Added the device using the "categoryA" tag. Instanly can't ping the shared node anymore.

All in all it feels very inconsistent to me.
I would appreciate any help or explanations.

If there is any info needed, please tell me.

### OS

Linux, Synology

### OS version

PopOS! 22.04 / DSM 7

### Tailscale version

1.32.3 on both

### Bug report

BUG-ce6a8c226b7a0ed78d7967fe55539d38c038fa27f9812532a2fec01543984c14-20221130150220Z-6ea761b3a8448ca8

**Comment by kelivel** [comment]
Working with @Biepa at HS #7656.

**Comment by DentonGentry** [comment]
> Are ACLs applied immediately? Do I need to reconnect? Logout and login?

ACLs should be applied more-or-less instantly after being entered.

**Comment by joserebelo** [comment]
> 10. Added the device using the "categoryA" tag. Instanly can't ping the shared node anymore.

I believe this is caused by #5321

**Comment by Biepa** [comment]
Hey @joserebelo ,
Thanks for the reply. This was fixed in the mentioned support ticket.
Indeed it is intended, as I understood the intention of tags wrong.
