### ISSUE TITLE
Trying to run Tailscale in Docker or Kubernetes fails to connect: "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by eldada** [tailscale/tailscale#6589]
### What is the issue?

- Following guide in https://tailscale.com/kb/1185/kubernetes/
- Configurations all seem fine (as expected)
- Using an auth key I created in my account
- Container comes up with the following error in the log
```
2022/12/01 15:32:05 control: LoginInteractive -> regen=true
2022/12/01 15:32:05 control: doLogin(regen=true, hasUrl=false)
2022/12/01 15:32:06 Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=46": x509: certificate signed by unknown authority
2022/12/01 15:32:09 logtail: upload: log upload of 432 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/7835...": x509: certificate signed by unknown authority
2022/12/01 15:32:09 logtail: [v1] backoff: 12142 msec
```

### Steps to reproduce

Follow instructions in https://tailscale.com/kb/1185/kubernetes/ on local Docker desktop Kubernetes.

### OS

macOS

### OS version

13.0.1 (22A400)

### Tailscale version

Latest (as of Dec 1st, 2022)

**Comment by DentonGentry** [comment]
`x509: certificate signed by unknown authority`
There is an MITM between the container and the Internet. This might be:
- a captive portal
- a security product like Fortinet, configured to issue its own self-signed certificates
- the network really has been compromised by an attacker
- etc

**Comment by eldada** [comment]
Thx for the quick response!
Could it be related to a VPN? I'll try on another compute I have that is without a VPN and update here.

**Comment by eldada** [comment]
Indeed, without the VPN it worked as expected! Thx 😄
