### ISSUE TITLE
FR: MacOS build instructions

### ISSUE THREAD

**Issue by awhitepl** [tailscale/tailscale#6591]
### What are you trying to do?

Use the client without the App Store.

### How should we solve this?

Provide instructions on building the client from source.

### What is the impact of not solving this?

I cannot use the software because I refuse to use the App Store.

### Anything else?

Using M1 Mac.

**Comment by DentonGentry** [comment]
There is a version of the Mac binary with a UI in the menubar available for download at: https://pkgs.tailscale.com/stable/#macos

If you are comfortable using a CLI, you can build from source: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

**Comment by DentonGentry** [comment]
I think the downloadable Mac app or the CLI executable meets this need.
