### ISSUE TITLE
Unable to ping node when not on same LAN

### ISSUE THREAD

**Issue by adumelie** [tailscale/tailscale#6601]
## Problem: 
* Tailescale node (my NAS) is unreachable (timeout with both `tailscale ping` and `ping` when I am not on the same local network as the NAS.

* The node is perfectly reachable when I am connected to my LAN (both `tailscale ping` and `ping` work without issue). (Both with and without the firewall and regular vpn enabled.)

When on LAN:
```
tailscale ping 100.64.112.8
pong from nas64 (100.64.112.8) via 192.168.8.207:41641 in 26ms
```
When **not** on LAN:
```
tailscale ping 100.64.112.8
ping "100.64.112.8" timed out
```
I tried disabling my firewall (ufw) and turning off my regular vpn. Neither solved the problem.

I use ProtonVPN on both my machine and the NAS. This has no effect when connected to the LAN, but was a source of potential concern for this issue. However, disabling it on both machines did *not* solve this issue.

My ufw rules are as follows:
```
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
22000/tcp                  ALLOW IN    Anywhere                  
22000/udp                  ALLOW IN    Anywhere                  
21027/udp                  ALLOW IN    Anywhere                  
mysshport/tcp                  ALLOW IN    Anywhere                  
Anywhere                   ALLOW IN    192.168.8.0/24            
Anywhere on tailscale0     ALLOW IN    Anywhere                  
22000/tcp (v6)             ALLOW IN    Anywhere (v6)             
22000/udp (v6)             ALLOW IN    Anywhere (v6)             
21027/udp (v6)             ALLOW IN    Anywhere (v6)             
mysshport/tcp (v6)             ALLOW IN    Anywhere (v6)             
Anywhere (v6) on tailscale0 ALLOW IN    Anywhere (v6)             

Anywhere                   ALLOW OUT   Anywhere on tailscale0    
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on tailscale0
```

Already when through the steps in [the troubleshooting guide](https://tailscale.com/kb/1023/troubleshooting/), to no avail. 

I also notice that on the NAS `tailscale status` does not list a third newly added device. Which is visible in `tailscale status` on my other machine. I do not know if this is related to the issue.

The status (run on the NAS) :
```
$ sudo tailscale status
# Health check:
#     - not in map poll

100.64.112.8    nas64                user@    linux   offline
100.81.126.23   pop-os               user@    linux   idle, tx 34775088 rx 926544
```
Lists my NAS as offline. However, this is also the case when being on the LAN, and despite this "offline" status the node responds correctly and is accessible.

The status (run on my machine):
```
sudo tailscale status
100.81.126.23   pop-os               user@    linux   -
100.64.112.8    nas64                user@    linux   idle; offline, tx 162920 rx 2121924
100.111.118.110 machineC       user@    android offline
```

### Steps to reproduce

Fresh install of tailscale on both machines.
Steps from documentation to allow traffic through ufw.
Connection (direct) works from LAN.
Stops working when no longer on the LAN.

## Expected behavior:
Should be able to ping correctly.

### OS

Linux

### OS version

Ubuntu 22.04, Debian 10 (armbian)

### Tailscale version

1.32.3

### Bug report

BUG-07655b445630d3f997351d2e4a9eb1f98c4438d1883d2f266019b1ceffba36e9-20221202190936Z-0eac440a123c9465

**Comment by raggi** [comment]
The default tailscale port on Linux is 41641 (see https://tailscale.com/kb/1082/firewall-ports/#my-devices-are-using-a-relay-what-can-i-do-to-help-them-connect-peer-to-peer). If this is applied it should result in a line from ufw containing:

```
41641/udp                  ALLOW IN    Anywhere                  
```

The reason that Tailscale was able to accept a LAN link is that the rule `Anywhere                   ALLOW IN    192.168.8.0/24  ` allows traffic from the LAN to flow - but there are no rules in the list you provided that would allow Tailscale to receive traffic from the internet.

---

```
# Health check:
#     - not in map poll
```

This status indicates that tailscaled is unable to establish or hold open an HTTPS connection with control, and without this, it will be unable to learn of new nodes on your network, and eventually the historical information about known peer nodes will become sufficiently stale that it will no longer be able to accept or make peer connections (including on the LAN).

Your NAS appears to be unable to reach the internet - all outbound connections are receiving no response and timing out.

**Comment by raggi** [comment]
We can provide additional help via support@tailscale.com if needed, where myself or others on the team will be very happy to assist you with more specific or personal details.

**Comment by adumelie** [comment]
Installing tailscale had somehow overwritten my resolv.conf and broken name resolution on my NAS, hence :
> Your NAS appears to be unable to reach the internet - all outbound connections are receiving no response and timing out. 
I think this may have been the cause of my issue. 
I have restored a functioning resolv.conf file and am now able to use `tailscale ping` successfully from either my LAN or another network. 
(But still cannot use regular `ping` with tailscale IPs)

**Comment by raggi** [comment]
I was able to see successful ICMP pings between two of your nodes in the logs. I also noticed that your nas lost internet access again.

I don't want to provide more details about your hosts in a public ticket. If you would like more detailed assistance, please do reach out to support@tailscale.com.
