### ISSUE TITLE
FR: Expose tailscale up flags without modification to the running service

### ISSUE THREAD

**Issue by mhameed** [tailscale/tailscale#6608]
### What are you trying to do?

Hi,
Thanks for a great project.

It would be useful for the purposes of configuration management systems, to be able to query tailscale up flags, without potentially modifying the running tailscale.

At the moment, I run tailscale up --accept-dns=false which I know that on my systems should always be set to false, this prints:

```
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

        tailscale up --accept-dns=false --accept-routes --advertise-routes=10.77.7.0/24 --netfilter-mode=off --snat-subnet-routes=false
```

Depending on what settings were used, the system may or may not be reconfigured.

Hence, it would be useful to expose what flags were used for the running system without potential modification.

**Comment by DentonGentry** [comment]
`tailscale debug prefs` may do what you're looking for.

**Comment by DentonGentry** [comment]
I think `tailscale debug prefs` will handle this, please reopen if not.

**Comment by bradfitz** [comment]
There's also "tailscale set" now in the upcoming 1.34

**Comment by davidemyers** [comment]
Being able to dump out the current configuration as a command line would be convenient for things like documenting how a machine is configured and duplicating a configuration onto a different machine via copy and paste.

**Comment by mhameed** [comment]
Hi,

I just received v1.34.0, tailscale set seems to be able to modify running flags, but I can't see how I would use it to query the settings of the running instance.

tailscale debug prefs is more like it, but it it would mean I would need to implement a mapping between up flags, and their corresponding json output from debug prefs.

It feels that the cleanest would be if tailscale could dump the current flags and their values.
 
This would mean less hacks within puppet/cdist/whatever, and we wouldn't have to worry about what new flags tailscale introduces from version to version.

Please consider reopening.

Thanks.
