### ISSUE TITLE
Windows locally compiled `tailscaled.exe` exits when `tailscale.exe` exits

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#6610]
### What is the issue?

I compiled tailscale.exe/tailscaled.exe from latest source and manually run on Windows command line. Login was reported sucessful, but status still shows "unexpected state: NoState"

### Steps to reproduce

1. remove folder C:\ProgramData\Tailscale
2. run `tailscaled` as admin
3. run `tailscale up` and follow the login steps
4. run `tailscale status`

1.33.0-dev20221203
  tailscale commit: 86b6ff61e6de60e3ab6b671fe177e5b85e5d561a
  go version: go1.19.2-ts3fd24de

<img width="732" alt="image" src="https://user-images.githubusercontent.com/787544/205443359-87be5dba-ac5b-462d-8acc-580e9dd1cc8d.png">

relavent tailscaled logs:
[error.log](https://github.com/tailscale/tailscale/files/10146479/error.log)

### OS

Windows

### OS version

windows 10

### Tailscale version

1.33.0-dev20221203

### Bug report

BUG-7d13d04fdeec0a02157f6f0be9e4bddd0a2acf4b7fb76ce39e43191e440cee28-20221203132658Z-259c40ce3edfd1e6

**Comment by DentonGentry** [comment]
`tailscaled` is exiting because the last localclient disconnected. This is the default behavior on Windows, where the background service exits if the frontend GUI exits. You can change this by running `tailscaled.exe --unattended`, and before running `tailscale.exe up` in a different cmd shell.

```
Switching ipn state Starting -> Running (WantRunning=true, nm=true)
derphttp.Client.Connect: connecting to derp-20 (hkg)
client disconnected; stopping server
LocalBackend.ResetForClientDisconnect
active login:
client disconnected; stopping server
control: client.Shutdown()
Switching ipn state Running -> Stopped (WantRunning=false, nm=false)
LocalBackend.ResetForClientDisconnect
control: client.Shutdown: inSendStatus=0
```

**Comment by bradfitz** [comment]
> You can change this by running `tailscaled.exe --unattended`

Actually `unattended` is a flag to `tailscale up`, not `tailscaled`. But maybe it should also be! Filed #6611

**Comment by awsong** [comment]
> > You can change this by running `tailscaled.exe --unattended`
> 
> Actually `unattended` is a flag to `tailscale up`, not `tailscaled`. But maybe it should also be! Filed #6611

Yes that flag solves the problem. Sorry that I didn't notice the difference between windows client and Linux client. Now it works fine.
