### ISSUE TITLE
FR: Community plan for non-GitHub orgs / Family plan

### ISSUE THREAD

**Issue by LeaderbotX400** [tailscale/tailscale#6614]
### What are you trying to do?

Share tailnet with family members without a github org.

### How should we solve this?

remove the restriction of needing a GitHub org or have a seperate plan for families

### What is the impact of not solving this?

Few issues as tailscale as I am yet to hit any hard limits on my tailnet users wise

**Comment by DentonGentry** [comment]
The intent of focussing on GitHub is to provide a free option for people who don't have a domain + identity provider. We were frequently being asked to assemble a group of N GMail addresses into a multiuser tailnet for friends/family use, which we don't currently have a way to do.

**Comment by DentonGentry** [comment]
The Free plan now allows three users: https://tailscale.com/kb/1154/free-plans-discounts/
