### ISSUE TITLE
On Windows, allow multiple users to use tailscale simultaneously

### ISSUE THREAD

**Issue by carleeto** [tailscale/tailscale#662]
**Is your feature request related to a problem? Please describe.**

I have a windows PC that I use for home and work. I find it frustrating when I log into my work account and try to reach a work machine only to realise that my Tailscale client is using my home credentials. 

**Describe the solution you'd like**

My ideal solution:

Complete isolation of tailscale networks between Windows user accounts, if possible.

When using my work account, I only have access to the tailscale network that uses my work login.
When using my home account, I only have access to the tailscale network that uses my home login.
If I remain signed in on my home account, but switch to my work account, then a program that's running under my home account still has access to my home tailscale network, but not to my work tailscale network. 
Similarly, a program I start in my work account, can only access my work tailscale network.

**Describe alternatives you've considered**

I have not considered any other alternatives.

**Additional context**

None.

**Comment by DentonGentry** [comment]
At this point I think this can be best addressed by https://github.com/tailscale/tailscale/issues/713
