### ISSUE TITLE
Forever on VPN starting...

### ISSUE THREAD

**Issue by skhaz** [tailscale/tailscale#6623]
### What is the issue?

<img width="394" alt="Screenshot 2022-12-05 at 14 18 31" src="https://user-images.githubusercontent.com/46259/205701027-63b14a80-4394-491e-873d-edbd8a84020c.png">

### Steps to reproduce

```shell
brew install --cask tailscale
```

Accept all prompts and see "VPN starting..." 

```shell
tailscale bugreport
2022/12/05 14:22:04 Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscaled.socket: connect: no such file or directory
```

### OS

macOS

### OS version

macOS Ventura

### Tailscale version

1.32.3

### Bug report

N/A

**Comment by bradfitz** [comment]
I think you're running a mix of Tailscale packages.

The `brew install --cask` installs our "macsys" GUI build but it looks like its CLI is `tailscale.wrapper.sh` and not `tailscale`?

What is that `tailscale` binary you're running? What does `type tailscale` and/or `which tailscale` say?

**Comment by skhaz** [comment]
@bradfitz I only have the cask installed

```shell
$ brew install --cask tailscale
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
grantlee

You have 1 outdated formula installed.
You can upgrade it with brew upgrade
or list it with brew outdated.

==> Downloading https://pkgs.tailscale.com/stable/Tailscale-1.34.0-macos.zip
######################################################################## 100.0%
==> Installing Cask tailscale
==> Moving App 'Tailscale.app' to '/Applications/Tailscale.app'
==> Linking Binary 'tailscale.wrapper.sh' to '/opt/homebrew/bin/tailscale'
🍺  tailscale was successfully installed!
```

After installing, I have this binary

```shell
$ which tailscale
/opt/homebrew/bin/tailscale
```

**Comment by bradfitz** [comment]
Sorry, no idea. We don't maintain the Homebrew packages. Maybe ask the maintainers of it to see if it works for them?

Can you try removing Tailscale from Homebrew and installing it manually and see if that works first?

**Comment by DentonGentry** [comment]
You can also run /Applications/Utilities/Console.app, and look for logs for "tailscale"

**Comment by skhaz** [comment]
Installing the App Store version worked 

`mas install 1475387142`
