### ISSUE TITLE
https://tailscale.com/download/windows does not list the new release immediately after update

### ISSUE THREAD

**Issue by bogosj** [tailscale/tailscale#6627]
### What is the issue?

Despite the machines page showing an update is available.

**Comment by DentonGentry** [comment]
1.34.0 is available for direct download: https://pkgs.tailscale.com/stable/#windows

The update check within the client caches the most recent version for a while, to avoid a thundering herd of clients all trying to update immediately. The update will go out over the course of today.

**Comment by bradfitz** [comment]
I think he's talking about https://tailscale.com/download/windows which used to auto-update but then @rosszurowski removed 😜

**Comment by bogosj** [comment]
The update link here: https://login.tailscale.com/admin/machines

Leads to here: https://tailscale.com/kb/1067/update/?tab=windows

**Comment by DentonGentry** [comment]
I started a process to make https://tailscale.com/download/windows link to https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe instead of a specific version.

**Comment by rosszurowski** [comment]
A few months back we made an update to the web server to auto-refresh version data every 5 minutes, though we can change that TTL down to 1 minute if we'd like. [The relevant lines are here](https://github.com/tailscale/tailscale-www/blob/main/tsweb/tsweb.go#L405-L431) in case anyone wants to make changes.

That might be enough to consider this issue fixed?
