### ISSUE TITLE
[chocolatey] Is there a way to pass AuthKey during the install?

### ISSUE THREAD

**Issue by random82** [tailscale/tailscale#6631]
I want to automate deployment to a server farm, and passing the authKey on the installation would streamline the process.

Is there a way to do it?

At this stage, I use following

```powershell
& 'choco' install tailscale -y
& 'resfreshenv.cmd'
& 'tailscale.exe' up --auth-key=$tsAuthToken --unattended --accept-routes=true
```

but unfortunately, the last line fails sometimes

**Comment by bradfitz** [comment]
> but unfortunately, the last line fails sometimes

How does it sometimes fail?

And with which Tailscale version?

**Comment by random82** [comment]
The approach that Azure DevOps choco package uses with passing params is a good example of passing auth credentials in one go during `choco install` command

[https://github.com/flcdrg/au-packages/blob/master/azure-pipelines-agent/README.md](https://github.com/flcdrg/au-packages/blob/master/azure-pipelines-agent/README.md)

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/4862 would handle this.
Marking as a duplicate of https://github.com/tailscale/tailscale/issues/4862
