### ISSUE TITLE
"Install with one command" untouchable Ubuntu 22.04.1 restart services text UI menu

### ISSUE THREAD

**Issue by rcpao** [tailscale/tailscale#6638]
'curl -fsSL https://tailscale.com/install.sh | sh' pops up a text menu which cannot be interacted with.  I had to Ctrl-C and re-run the command to continue without restarting any services.  I'll login and reboot later.
![Screenshot from 2022-12-06 10-01-12-cropped](https://user-images.githubusercontent.com/3468574/205990008-1e91bf45-8eed-4146-afb8-95f95857bb84.png)

**Comment by DentonGentry** [comment]
Interestingly, we already set `DEBIAN_FRONTEND=noninteractive` so apparently that is not enough.
https://github.com/tailscale/tailscale/blob/da53b1347bf0762d3fc7553f5df4e59e5c290c25/scripts/installer.sh#L471

We don't run `apt upgrade` in install.sh. I suspect that whatever updated libraries it is looking at for `open-vm-tools` and `packagekit` and so on were already in that pending state when install.sh was run, perhaps from a previous (failed?) `apt upgrade`

**Comment by DentonGentry** [comment]
So far as I can see, the packages which asked about updating libraries were already in that state before install.sh was run, and I don't see a way that install.sh could avoid having that dialog come up. Closing as not feasible.
