### ISSUE TITLE
Discrepancy in how containerboot and run.sh handle TS_STATE_DIR

### ISSUE THREAD

**Issue by guest42069** [tailscale/tailscale#6644]
### What is the issue?

When upgrading from 1.32 branch (`run.sh`) to 1.34 (`containerboot`) the way the `TS_STATE_DIR` environment variable differs.

Specifically, containerboot passes it as the argument for `--state` which points to a specific state file, while run.sh passed it as the argument for `--statedir` which points to a directory.

```
Program starting: v1.32.3-t9dd89b8c2, Go 1.19.3: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--statedir=/var/lib/tailscale"}
```

So a direct upgrade to 1.34 for the above container using TS_STATE_DIR results in the following error

```
Program starting: v1.34.0-t988801d5d, Go 1.19.3: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=/var/lib/tailscale"}
getLocalBackend error: store.New: read /var/lib/tailscale: is a directory
```

Instead I had to manually update the TS_STATE_DIR variable to be the complete state file path to resume normal operation.

### Steps to reproduce

Run a 1.32 container using a state dir (I.E. with a mounted volume for persistent state) defined by env var in the container.

Then perform a direct upgrade of the container to a 1.34 image, attempting to use the same configuration.

### Are there any recent changes that introduced the issue?

The relevant changes from 1.32 to 1.34:

[1.32 run.sh](https://github.com/tailscale/tailscale/blob/release-branch/1.32/docs/k8s/run.sh#L29)

[1.34 containerboot](https://github.com/tailscale/tailscale/blob/release-branch/1.34/cmd/containerboot/main.go#L278)

### OS

Linux

### OS version

Fedora Host, Alpine Container.

### Tailscale version

v1.34.0-t988801d5d

**Comment by danderson** [comment]
Thanks for the report. This was an accidental regression, sorry. I believe https://github.com/tailscale/tailscale/pull/6636 fixes things to match the old behavior. I'll kick off an unstable build shortly, in the meantime if you need the old behavior back you can pin `:v1.32.3` as the container image tag to get the previous build.
