### ISSUE TITLE
K8s node with tailscale transiently breaks dns inside containers

### ISSUE THREAD

**Issue by asg0451** [tailscale/tailscale#6651]
### What is the issue?

see title :(

I have a Linux machine running tailscale and acting as a k8s node/host. the kube distro is latest k3s. 

example:

```
root@rbot-85fc96b69d-vkgbq:/app# while nslookup s3.us-east-1.amazonaws.com; do sleep 1; done
Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find s3.us-east-1.amazonaws.com.beagle-chickadee.ts.net: No answer

Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find s3.us-east-1.amazonaws.com.beagle-chickadee.ts.net: No answer

Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find s3.us-east-1.amazonaws.com.beagle-chickadee.ts.net: No answer

Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find s3.us-east-1.amazonaws.com.beagle-chickadee.ts.net: No answer

Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find s3.us-east-1.amazonaws.com.beagle-chickadee.ts.net: No answer

Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   s3.us-east-1.amazonaws.com
Address: 52.217.111.102
Name:   s3.us-east-1.amazonaws.com
Address: 52.217.133.112
Name:   s3.us-east-1.amazonaws.com
Address: 52.216.153.158
Name:   s3.us-east-1.amazonaws.com
Address: 54.231.131.72
Name:   s3.us-east-1.amazonaws.com
Address: 54.231.163.16
Name:   s3.us-east-1.amazonaws.com
Address: 52.216.83.59
Name:   s3.us-east-1.amazonaws.com
Address: 52.216.39.16
Name:   s3.us-east-1.amazonaws.com
Address: 52.216.228.67

```

as you can see, it sometimes can't reach amazon / chooses the wrong name to lookup? i'm not a dns expert tbh. 

it's not just aws s3 either, this happens with multiple domains.

this seems similar to https://github.com/tailscale/tailscale/issues/1003 but that's marked as fixed and this clearly isnt.

note that `beagle-chickadee.ts.net` is my magicdns tailnet name, and i have magicdns enabled.

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

on the host:

$ tailscale --version
1.32.3
  tailscale commit: a07555f434843c2d049bfb04b0b17b61dd362824
  other commit: 093d1e978538b249ab628c721e2f49d97b2cd16d
  go version: go1.19.2-ts3fd24dee31

### Bug report

BUG-8da09730460803ece064ddc8b074cceff76d3adac875110f37a839d8eac46c36-20221207044352Z-a1bfef9102edc35e

**Comment by bradfitz** [comment]
Got a `tailscale bugreport`?

**Comment by asg0451** [comment]
> Got a `tailscale bugreport`?

~$ tailscale bugreport
BUG-8da09730460803ece064ddc8b074cceff76d3adac875110f37a839d8eac46c36-20221207044352Z-a1bfef9102edc35e

**Comment by asg0451** [comment]
this is really hurting me... @bradfitz do you know of any remediation steps? this is the container's resolv.conf btw:

```
search apps.svc.cluster.local svc.cluster.local cluster.local beagle-chickadee.ts.net
nameserver 10.43.0.10
options ndots:5
```

**Comment by coffenbacher** [comment]
I think I'm running into this as well. My host can access the Internet fine, but from inside the k3s pods, the Tailscale DNS seems to be dominating. 

From inside a pod:
```
wget google.com
--2022-12-14 04:33:18--  http://google.com/
Resolving google.com (google.com)... 103.84.155.153, 209.177.145.137, 185.40.234.37, ...
Connecting to google.com (google.com)|103.84.155.153|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://google.com/ [following]
--2022-12-14 04:33:18--  https://google.com/
Connecting to google.com (google.com)|103.84.155.153|:443... connected.
GnuTLS: The TLS connection was non-properly terminated.
Unable to establish SSL connection.
```

I can't install any better tools inside the pod at the moment because it can't get to the Internet, so I will come back and update this when I have a bit more time to debug. But this is causing a minor production issue for me.

**Comment by bradfitz** [comment]
Cc @danderson @maisem

**Comment by DentonGentry** [comment]
>this is really hurting me... @bradfitz do you know of any remediation steps? this is the container's resolv.conf btw:

If you need to turn off Tailscale DNS to let the cluster's normal DNS take over, this can be done with `tailscale up --accept-dns=false`

**Comment by coffenbacher** [comment]
Thanks @DentonGentry ! Oddly, upgrading to Tailscale 1.34.1 fixed it for most of my containers, but not all. No matter how many times I deleted the remaining error pod it still had name resolution issues. 

`tailscale up --accept-dns=false` immediately resolved the final error, and is effective for fixing my production issue, thank you!

**Comment by asg0451** [comment]
@DentonGentry @coffenbacher `tailscale up --accept-dns=false` seems to have immediately resolved my issues too, thanks!

however, now i can't access any other machines on the tailnet from this server. this is definitely an improvement, but is not ideal.

any thoughts on what the root cause is? and perhaps this advice should go to in some troubleshooting documentation.

thanks again!

**Comment by DentonGentry** [comment]
>any thoughts on what the root cause is?

We'd need another bugreport from the system in the failing state.

Alternately, [the Kubernetes Operator is available in alpha](https://github.com/tailscale/tailscale/issues/502#issuecomment-1414522795)
It has proven very difficult to debug individual k8s deployments, packaging the operator is an effort to get to a more supportable Kubernetes environment.

**Comment by asg0451** [comment]
fwiw i just encountered this issue again on another node, except it doesnt look like i can --accept-dns=false my way out of it 😢

**Comment by asg0451** [comment]
@DentonGentry i ran into this again on a fresh machine. i really don't want to have to disable dns again. can i give you any info to help resolve this issue? basically i'm trying to run a non-cloud k8s cluster where the nodes are tailscale'd together. but i keep running into pods running on those nodes not being able to resolve tailscale dns.

**Comment by DentonGentry** [comment]
We have repeatedly asked for a `tailscale bugreport` from a system recently experiencing the problem.

**Comment by asg0451** [comment]
apologies, here you go
`BUG-1f624a23d400c03e00f0572fd856f6ecd57969ea0099ab80d40950f92a01cc2d-20231119024143Z-325eb85cf0adcc7e`

**Comment by asg0451** [comment]
example:
on the node:
```
$ nslookup hex2.beagle-chickadee.ts.net
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	hex2.beagle-chickadee.ts.net
Address: 100.80.164.23

```

in a pod:

```
# nslookup hex2.beagle-chickadee.ts.net
Server:		10.43.0.10
Address:	10.43.0.10#53

** server can't find hex2.beagle-chickadee.ts.net: NXDOMAIN
```

**Comment by DentonGentry** [comment]
`10.43.0.10#53` is not a Tailscale DNS server, it is some other server somewhere which doesn't know about the `beagle-chickadee.ts.net` MagicDNS domain. We would expect to see either:
- `127.0.0.53` if the node is using `systemd-resolved`
- `100.100.100.100` if it is not using `systemd-resolved`

--------

Looking at that node which generated the bugreport right as it is starting Tailscale we see it decide that it is using `systemd-resolved` and receive a DNS config:
```
2023-11-19 02:15:49.57765653 +0000 UTC: Program starting: v1.54.0-t42cae6916-g2458acf00, Go 1.21.4: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41641"}
2023-11-19 02:15:49.586068111 +0000 UTC: dns: [resolved-ping=yes rc=resolved resolved=file nm=no resolv-conf-mode=stub ret=systemd-resolved]
2023-11-19 02:15:49.58608643 +0000 UTC: dns: using "systemd-resolved" mode
2023-11-19 02:15:49.587113715 +0000 UTC: dns: dbus connected
2023-11-19 02:15:49.588203799 +0000 UTC: dns: using *dns.resolvedManager
...
2023-11-19 02:15:50.460810534 +0000 UTC: dns: Set: {DefaultResolvers:[] Routes:{beagle-chickadee.ts.net.:[] ts.net.:[...]}+65arpa SearchDomains:[beagle-chickadee.ts.net.] Hosts:19}
2023-11-19 02:15:50.460834527 +0000 UTC: dns: Resolvercfg: {Routes:{ts.net.:[...]} Hosts:19 LocalDomains:[beagle-chickadee.ts.net.]+65arpa}
2023-11-19 02:15:50.460841969 +0000 UTC: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[beagle-chickadee.ts.net.] SearchDomains:[beagle-chickadee.ts.net. ts.net.]+65arpa}
```

I believe this DNS config from the coordination server would result in sending a DBus event to `systemd-resolved` to configure the domain `beagle-chickadee.ts.net` to use `100.100.100.100` as its DNS server.

--------

However instead of the `127.0.0.53` one would expect for `systemd-resolved`, `/etc/resolv.conf` apparently instead contains `10.43.0.10`.

We get a report of the interfaces present:
```
2023-11-19 02:15:49.588255761 +0000 UTC: link state: interfaces.State{defaultRoute=enx00 ifs={cni0:[10.42.0.1/24 llu6] enx00:[192.168.0.52/24 llu6] flannel.1:[10.42.0.0/32 llu6]} v4=true v6=false}
```

I note the Ethernet interface has a 192.168.x.x address, but that there is a `cni0` interface with an IP address suspiciously close to the `10.43.0.10` we see for the DNS server.

Is there a CNI overwriting `/etc/resolv.conf`? It is breaking `systemd-resolved`.

**Comment by asg0451** [comment]
thanks for the quick reply @DentonGentry. The node's resolv.conf does indeed have the ip you expect:
```
$ cat /etc/resolv.conf 
# ...long comment...
nameserver 127.0.0.53
options edns0 trust-ad
search beagle-chickadee.ts.net
```

i've been doing some digging myself however. shelling into the coredns container, ITS /etc/resolv.conf looks like this:
```
# cat /etc/resolv.conf 
search beagle-chickadee.ts.net
nameserver 192.168.0.108 # this is a dns server on my lan (pi hole) which the router advertises as should be the default
nameserver 192.168.0.1 # this is my router
```

**Comment by asg0451** [comment]
based on the above, with some luck, i have a workaround:

```
# see https://blog.differentpla.net/blog/2022/02/25/coredns-custom/
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  beagle-chickadee.ts.net.server: |
    beagle-chickadee.ts.net {
      forward . 100.100.100.100
    }

```

this adds a new coredns "server block" handling my tailnet. this works around the fact that coredns for Some Reason is using my network's configured dns server instead of the node's. this will break for other tailnets, but for me, for now, it should work

thanks for the help @DentonGentry, especially on a saturday night <3

**Comment by knyar** [comment]
Based on the last comment this seems to have been resolved.

**Comment by asg0451** [comment]
@knyar the above is a workaround, i think the root issue is that sometimes, somehow, tailscale's resolv.conf rewrites arent picked up by k8s / coredns / whatever. that does sound tricky to debug though, so i'll leave it up to you 🤷

**Comment by Ultradark** [comment]
Thank you @asg0451, I had a similar situation with my kubernetes cluster, headscale and tailscale-client w/magic dns and managed to resolve it with a minor change in your manifest:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-tailnet
  namespace: kube-system
data:
  <user>.<tailnet domain>.server: |
    <user>.<tailnet domain> {
      search .
    }
```

with above applied, my pods can connect to internet without tls handshake errors.

**Comment by asg0451** [comment]
glad to be of help @Ultradark !

**Comment by doctorpangloss** [comment]
`tailscale` will always break cluster dns resolution in the following conditions:
 - you use coredns with a typical corefile:
```
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          ttl 30
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
 - tailscale is installed on the same node where coredns is running
 - the node links /etc/resolv.conf to systemd's resolv

you should uninstall tailscale then restart the node to resolve the issue

**Comment by mcfedr** [comment]
this is an old issue, and fixed a bit

i solved it a bit differently - by disabling magic dns, `tailscale set --accept-dns=false` on the host
