### ISSUE TITLE
iOS 1.34.0 can't ping / ssh devices on tailnet

### ISSUE THREAD

**Issue by ay18** [tailscale/tailscale#6652]
### What is the issue?

**What works**
iOS device appears to be connected to tailnet because I'm able to access certain host/ports exposed through subnet routes. I am also able to ssh from iOS device into other devices on tailnet using MagicDNS ip addresses.

**What does not work**
- pinging from iOS device to other tailnet devices receives no response, regardless of whether I use MagicDNS IP or their local ones (exposed through subnet route).
- SSH from iOS device using subnet routes also fails

### Steps to reproduce

- enable tailscale on iOS device.
- Using termius (iOS terminal emulator), SSH to a tailnet device (mac mini) using their MagicDNS IP Addr. Connects ✅.
- Log into synology (also on tailnet) from iOS using subnet route. Connects ✅.
- Using termius (iOS terminal emulator), SSH to a device (mac mini) using their subnet route. Fails ❌.
- From iOS, ping tailnet device (mac mini) using subnet route. No packets received ❌.
- From iOS, ping tailnet device (mac mini) using MagicDNS. No packets received ❌.

### OS

macOS, iOS, Synology

### OS version

iOS 16.2, macOS Montery 12.4, Synology DSM 7

### Tailscale version

1.34.0

### Bug report

BUG-881a83a6caccb29eb6d0a7af51c43fb53c6e94aced8ccb64dfcc60a38116222a-20221207031137Z-a1d7a90cf2f3e4c3

**Comment by DrJosh9000** [comment]
I'm having a very similar issue. Seemingly no outbound connectivity at all from my iOS 16.1.1 device running app v1.34.0 to my tailnet. 

BUG-6c8f6ec53dce6efd1dfbd3d3a1c4462f4a0c0b80d897190acfce1ee0bde1411b-20221208201226Z-7fa1768311dc99f3

**Comment by DrJosh9000** [comment]
I reset device network settings, then removed and reinstalled the app, then put the new IP in my ACLs, and it works again

**Comment by DentonGentry** [comment]
Shortly before the bugreport:
```
2022-12-07 02:53:55.120436 +0000 UTC: ^40.0M control: lite map update after 4ms: Post "https://controlplane.tailscale.com/machine/map": read tcp [2607:fb90:q:r:s:t:u:v]:50134->[2a05:d014:386:203:4535:c15c:9ab:8258]:80: use of closed network connection
2022-12-07 02:53:55.120539 +0000 UTC: ^40.0M getDNSServers: OS DNS servers: [fd00:976a::9 fd00:976a::10]
```

fd00:976a::9 and fd00:976a::10 are DNS servers hosted by Apple for PrivateLink. I think the device is trying to simultaneously use Tailscale and PrivateLink, and they are interfering.

**Comment by DentonGentry** [comment]
ETIMEDOUT. Believed to be two VPNs fighting for VPN supremacy.
