### ISSUE TITLE
FR: add subscription-style interface for LocalClient/connection status

### ISSUE THREAD

**Issue by andig** [tailscale/tailscale#6655]
### What are you trying to do?

Trying to start a tailscale connection, various things can go wrong (machine auth, client auth, any type of other issue). I'm currently busy-polling `LocalClient.Status()`:

	for {
		status, err = lc.Status(ctx)
		if err != nil {
			return "", err
		}

		switch status.BackendState {
		case NeedsMachineAuth:
			logr.INFO.Printf("needs machine auth: %+v", status)
			break LOOP

		case NeedsLogin:
			if status.AuthURL == "" {
				time.Sleep(10 * time.Millisecond)
				continue
			}

			logr.INFO.Printf("needs login: %s", status.AuthURL)
			break LOOP
            ...
    }

### How should we solve this?

If feasible, it would be great if there was a subscription mechanism for client (or tailnet or...) status updates, maybe using channels. That said I have no understanding if that's feasible from point of the internal architecture.

### What is the impact of not solving this?

Busy-polling status when needed

### Anything else?

Would be great if this mechanism could also round-trip successful client authentication (`AuthUrl` emptied).

**Comment by bradfitz** [comment]
I think you're looking for https://pkg.go.dev/tailscale.com/client/tailscale#LocalClient.WatchIPNBus

**Comment by andig** [comment]
Great, thank you! It took me a bit to figure it out for sake of future readers:

- [LocalClient.WatchIPNBus](https://pkg.go.dev/tailscale.com/client/tailscale#LocalClient.WatchIPNBus) will consume a stream of JSON messages and provide them one at a time using `Next()`
- if `n.State` is non-Nil, it can return `NeedsLogin` once but nut return any more state unless it changes
- on Login, `LoginFinished != nil` is also returned once

**Comment by andig** [comment]
Need to come back once more. When I use the watcher and wait for `NeedsLogin` it's not obvious how to obtain the `AuthURL`:

				switch *n.State {
				case ipn.NeedsLogin:
					needsLogin = true

					status, err = lc.Status(ctx)
					if err != nil {
						return
					}

					logr.INFO.Printf(status.AuthURL)

Using `lc.Status()` here returns a status that does not have the URL set:

    &{Version:1.33.0-dev-t BackendState:NeedsLogin AuthURL: TailscaleIPs:[] Self:0x14000e15ba0 ExitNodeStatus:<nil> Health:[not in map poll This is an unstable (development) version of Tailscale; frequent updates and bugs are likely] MagicDNSSuffix: CurrentTailnet:<nil> CertDomains:[] Peer:map[] User:map[]}

So what is a reliable way to obtain the `AuthUrl` when login is needed in case of using the watcher?

**Comment by danderson** [comment]
`n.BrowseToURL` is non-nil when the backend needs the user to navigate to a URL for something.

**Comment by danderson** [comment]
That said, you'll also need to actually drive the login state machine depending on your goals. You may need to either call Start or StartLoginInteractive, depending on how you're bringing things up. See cmd/tailscale/cli/up.go for the full state machine you have to navigate. It's currently quite complex if you need to handle many possible configurations.

**Comment by andig** [comment]
Took me a bit to figure out `n.BrowseToURL`:

- it shows up as `URL` when printf'ing the struct
- it is first returned non-nil but empty

**Comment by danderson** [comment]
Hmm, non-nil but empty is a bit weird, that's probably a small bug somewhere in the state machine that our code happens to avoid because it always does a != nil && != "" check. This whole state machine is quite old and has grown in interesting ways, and I believe bradfitz was starting on another round of cleanups for it. So, uh, pardon the sawdust I guess :)

**Comment by danderson** [comment]
Also because I'm curious: what are you working on? Just wondering if we have better options for you than forcing you to make your own frontend.

**Comment by andig** [comment]
I'm working on https://evcc.io, trying to make internet access to user's home installation as easy as possible using tailscale. Idea is to have tailscale bundled with https://github.com/evcc-io/evcc so users don't have to run a tailscale client in addition. To allow that they should just "enable" tailscale (and maybe provide a key). Login is then handled via GUI, same as we can OAuth-login to e.g. their vehicle account. Or that's the idea...

**Comment by danderson** [comment]
Oh, nice! Have you seen https://pkg.go.dev/tailscale.com/tsnet for embedding a Tailscale node in another process? If you can restrict the UI to purely "give me an authkey to log into tailscale" instead of supporting the full interactive login flow, tsnet should let you skip all of the IPN bus complexity. Currently it doesn't help as much if you want to do the interactive OAuth login flow though, for that you're still stuck with the approach you're taking, for now.

**Comment by andig** [comment]
Already using tsnet, thank you!
