### ISSUE TITLE
PATH env var missing from tailscale ssh non-interactive sessions

### ISSUE THREAD

**Issue by mattbdc** [tailscale/tailscale#6667]
### What is the issue?

PATH env var not present

### Steps to reproduce

ssh tailscale-node env

### Expect

ssh openssh-sshd-node env 

shows PATH

### Unknown

How is PATH sourced and why is it different (absent) vs opensshd on same box? Configuration.

### OS

Linux

### OS version

Ubuntu 22.04 LTS

### Tailscale version

Latest

**Comment by bradfitz** [comment]
I can reproduce! Thanks for the clue.

Closing as dup of #5285. I copied some info to that bug.
