### ISSUE TITLE
v1.34.0 on Windows seems to now always reconnect to TS on startup

### ISSUE THREAD

**Issue by nicholashead** [tailscale/tailscale#6668]
### What is the issue?

In previous builds of TS, if I'm remembering correctly - if I disconnected from the network, that setting would be remembered/persisted across restarts of the app and my PC. Now with the latest v1.34.0 update, TS appears to always connect on startup, and not respect the previous state.

If this isn't really a bug and more of an unintentional side effect that's been changed now - it would be really nice if the behavior could be a setting or something - I often disconnect my main PC from TS (unless needed) because of NETBIOS/SMB slowness to local machines.

### Steps to reproduce

Disconnect from TS within the app - then restart computer. On restart, TS reconnects.

### OS

Windows

### OS version

Windows 11 22H2

### Tailscale version

1.34.0

**Comment by mews-se** [comment]
+1 on this, very frustrating (if it is intentionally)

**Comment by DentonGentry** [comment]
This wasn't an intentional change, likely a side-effect to changes made in how preferences are stored to support Fast User Switching: https://tailscale.com/blog/fast-user-switching/

**Comment by Snackhole** [comment]
This bug is still present in 1.56.1.  Has any work been done on it?

**Comment by nickkhyl** [comment]
The fix for this issue is available in the 1.73.69 [unstable build](https://pkgs.tailscale.com/unstable/#windows) and will be included in the 1.74 release planned for September.
