### ISSUE TITLE
Android Client change server functionality broken after v1.34.0

### ISSUE THREAD

**Issue by rbangert** [tailscale/tailscale#6671]
### What is the issue?

Verified issue with 2 others running headscale servers. 

v1.33.97 is the last version that we have found this function to not be broken. 

Starting with v1.34.0, we are able to tap the hamburger icon several times to add the change server option, select it, enter the new address, and press restart the app, at which point it closes and never reopens, all of which mirrors the previous version's behavior.

After reopening, the change server option is still available, and the address to the new server is still in the input box, but pressing the button loads the tailscale login, and no connection attempts show on the server. 

### Steps to reproduce

Upgrade to v1.34.0 or above.

### OS

Android

### OS version

Andriod 13

### Tailscale version

1.34.0

**Comment by rbangert** [comment]
It appears to have happened in this commit. 

https://github.com/tailscale/tailscale-android/blob/7cdd9abc964b1bbecf1f2134387b6416b8c15b6b/cmd/tailscale/main.go#L441-L446

**Comment by mihaip** [comment]
@maisem I think this is due to the fast user switching refactoring. When the app is in the initial state (with a new profile) we don't persist any data until there's a login. The `os.Exit` at https://github.com/tailscale/tailscale-android/blob/7f11150cb6a3df6a1c36125f187b6892024fe46f/cmd/tailscale/main.go is resulting in the `ControlURL` URL pref being lost.

I think the fix here would be to do something like that what we do for the Mac app with tailscale/corp#8137 where we do the `EditPrefs` before we call `StartLoginInteractive`. Or possibly it's closer to what we do in the CLI at https://github.com/tailscale/tailscale/blob/c084c7d7edf425fa661e7543298c14a93f867c81/cmd/tailscale/cli/up.go#L657-L659, where we can provide the ControlURL as part of the `UpdatePrefs` when starting.

**Comment by rbangert** [comment]
This is the block of code in main.go you are speaking of. 
https://github.com/tailscale/tailscale-android/blob/7cdd9abc964b1bbecf1f2134387b6416b8c15b6b/cmd/tailscale/main.go#L441-L446

It was added with this commit to add this functionality, and had been functioning until v1.34.0.
https://github.com/tailscale/tailscale-android/commit/d8aedf721ae17326561fa12b2699bdb19cc677f9

So the new ControlURL was getting picked up by main.go in after reopening, until these two commits: 

https://github.com/tailscale/tailscale-android/commit/26e72f15efe798eb1a4c7acf082eb97e243b6644
https://github.com/tailscale/tailscale-android/commit/1181155b7d19df26efd2b2cfedce5d21ec125c2b


The UI retains the custom URL through the restart of the app, and shows the debug menu, because the URL gets passed into main.go in `ui.store` as `customLoginServerPrefKey`

Then we land back at the code you suspect is dropping it right after it gets set to `state.Prefs.ControlURL`  before setting the exit code to 0, to fool it's self into believing it was connected when the app closed. 

I can't find any changes that would have broken the URL being stored in `*stateStore`, and I think it ends up there both as `Prefs.ControlURL` and `store.customLoginServerPrefKey` before the app closes. 

Because ends up back in the UI here after being imported from `*stateStore`: 
https://github.com/rbangert/tailscale-android/blob/7f11150cb6a3df6a1c36125f187b6892024fe46f/cmd/tailscale/ui.go#L265-L267

And I think it's making it all the way to line 354, where this line of code was taking it from `p.prefs` to `state.prefs.`
`state.Prefs = p.Clone()`

But now `p.AsStruct` grabs the underlying value, which is set to the Default URL by ipnlocal. 
`state.Prefs = p.AsStruct()`

**Comment by rbangert** [comment]
I was wrong in the comment above, and I think this was actually broken with changes within ipnlocal. 

The functionality was introduced with this commit:
https://github.com/tailscale/tailscale-android/commit/d8aedf721ae17326561fa12b2699bdb19cc677f9?diff=split

Where the little hack involving `os.exit(0)` had been working until the v1.34.0 release. The custom control URL still persists within the UI after the app restarts, because this works. However it only ends up back in the UI because it's stored in two locations within *stateStore while the app is closed. 

When the app opens, it inserts data from *stateStore into ipnlocal in the localBackend structure which enabled it to be injected into start() before it gets initialized. 

Where I think @maisem rolled through and wrecked this patchy work around by removing ServerURL from localBackend in this commit:
https://github.com/tailscale/tailscale/commit/8d841788845488c18512f1835ba7178c0dc82fa1

Go didn't even exist the last time I wrote a line of code so I'm pretty rusty. But I'll figure out how to make go.mod do what I want later this evening, and build an apk to confirm this.

**Comment by megamorf** [comment]
I just wanted finished setting up a headscale instance for the first time and was confused why I wasn't able to sign in with the Android app. This explains it. How fast do you think you can ship a bugfix? Unfortunately I'm not a good coder but I can help with testing the fix.

**Comment by DentonGentry** [comment]
We have not released 1.34.1 for Android yet, working on a fix. Unfortunately we may need a change in https://github.com/tailscale/tailscale to do so which means it would need a 1.34.2 release.

**Comment by DentonGentry** [comment]
Current effort is in https://github.com/tailscale/tailscale-android/compare/main...serverurl :
- doesn't exit the App, instead calls `b.backend.Start()` to make it generate the loginURL again.
- removes the "...and restart" text from the UI

It still isn't working though. I can see Start() being called, and it looks like it stops the backend and never restarts it:
```
12-17 15:32:42.703 22250 22277 I com.tailscale.ipn: 15.5M/119.6M SetPrefs: Prefs{ra=true dns=true want=false url="https://login.example.com" host="Pixel 3a XL" Persist=nil}
12-17 15:32:42.704 22250 22277 I com.tailscale.ipn: 15.5M/119.6M Start
12-17 15:32:42.704 22250 22272 I com.tailscale.ipn: 15.5M/119.6M control: client.Shutdown()
12-17 15:32:42.705 22250 22272 I com.tailscale.ipn: 15.5M/119.6M control: client.Shutdown: inSendStatus=0
12-17 15:32:42.706 22250 22290 I com.tailscale.ipn: 15.6M/119.6M control: mapRoutine: quit
12-17 15:32:42.707 22250 22281 I com.tailscale.ipn: 15.6M/119.6M control: Client.Shutdown done.
12-17 15:32:42.707 22250 22277 I com.tailscale.ipn: 15.6M/119.6M Backend: logs: be:5fdbf3026b207075092f06c6096a3c91dc28fae2513828042b8f033af126d26a fe:
... hangs forever...
```

Clicking on "Sign in with other" just sits there, never launching a browser window.

WantRunning is `false` but I'd still expect the backend to start up and sit in the `NeedsLogin` state.
Setting WantRunning=true in the struct passed to `SetPrefs` makes no difference.

I also tried using EditPrefs in case there is some side-effect, but no difference.

**Comment by DentonGentry** [comment]
Figured out the deadlock and got past that point, testing some more.

**Comment by philipmnelson** [comment]
Appreciate the work on this @DentonGentry

**Comment by DentonGentry** [comment]
I believe this is fixed in 1.34.1, which is in review for the Play Store release.

**Comment by philipmnelson** [comment]
@DentonGentry I can confirm that it is fixed. I just built it with the latest commits and it worked as expected. 🥇

**Comment by geekscrapy** [comment]
I just downloaded the latest Android version but can't activate the Change Server option. It doesn't appear after many attempts 

![Screenshot_20230507_161324](https://user-images.githubusercontent.com/11225502/236676822-f40158e6-ed69-41f0-a4b8-704ec4ced0fe.jpg)
![Screenshot_20230507_161414_Google Play Store](https://user-images.githubusercontent.com/11225502/236676825-f8fd57d7-ca52-4754-8cd5-1ac8c200b6a5.jpg)

**Comment by DentonGentry** [comment]
Not that menu. Click log out, then click the menu on the authentication screen. On the fourth click, the Change Server URL item will appear.

![Screenshot_20230507-051608](https://user-images.githubusercontent.com/1140756/236677026-e649c4e7-659a-46ff-9697-d0dad144dceb.png)

**Comment by axxonadmin** [comment]
Android tailscale client 1.48.2

Although I was able to enable "custom server", and it worked with my headscale, but 
every time I'm trying to log in after restart or logout with "sign in with other" 
it gets me to "login.tailscale.com" untill I go in "change sarver" and press "save" button again.

**Comment by cracknel** [comment]
I can confirm what @axxonadmin is saying.

**Comment by travisdj** [comment]
This is still an issue.  I've even reinstalled my headscale server to make sure it wasn't an issue there. Very frustrating since at one point I could have tasker connect me to my headscale server when I left the house since I'm behind cgnat. Hope to see a fix.
