### ISSUE TITLE
`tailscale ssh` on Windows regression, socket path is invalid

### ISSUE THREAD

**Issue by raggi** [tailscale/tailscale#6672]
### What is the issue?

When running `tailscale ssh` I receive an error:

```
failed to connect to local tailscaled (which appears to be running as tailscaled.exe, pid 16464). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": open \\\\.\\pipe\\ProtectedPrefix\\Administrators\\Tailscale\\tailscaled: The specified path is invalid.
```

### Steps to reproduce

`tailscale ssh <nodename>`

### Are there any recent changes that introduced the issue?

The switch to named pipes is the likely cause, which changed the shape of the socket address.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.34.0

**Comment by raggi** [comment]
from @maisem likely path escaping from:

```go
argv = append(argv,
    "-o", fmt.Sprintf("ProxyCommand %q --socket=%q nc %%h %%p",
    tailscaleBin,
    rootArgs.socket,
))
```

**Comment by bradfitz** [comment]
Dup of #6639

**Comment by raggi** [comment]
Whoops, thanks Brad!
