### ISSUE TITLE
The terminal stops responding after starting tailscale

### ISSUE THREAD

**Issue by qiuxiangling** [tailscale/tailscale#6676]
### What is the issue?

root@debian:~# tailscaled 
logtail started
Program starting: v1.34.0-tbb6e746f3-g8d1edab6f, Go 1.19.2-ts3fd24dee31: []string{"tailscaled"}
LogID: 1b2551293b0646f16682497dace8e37656db9c6cb3ffdcafdf086add4d26cd2e
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: disabling tunneled IPv6 due to system IPv6 config: disable_ipv6 is set
dns: [rc=unknown ret=direct]
dns: using "direct" mode
dns: using *dns.directManager
link state: interfaces.State{defaultRoute=ppp0 ifs={enp1s0:[172.20.3.1/24] ppp0:[10.198.1.8/32]} v4=true v6=false}
magicsock: disco key = d:198a5e1fcdcf451e
Creating WireGuard device...
Bringing WireGuard device up...
external route: up
Bringing router up...
Clearing router settings...
Starting link monitor...
Engine created.
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5210 Table:254 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5230 Table:253 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5250 Table:0 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5270 Table:52 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
pm: using backend prefs for "profile-769e": Prefs{ra=true dns=false want=true routes=[172.20.3.0/24] snat=true nf=on url="http://domain:8080" Persist{lm=, o=, n=[1nYAF] u="default"}}
got LocalBackend in 40ms
Start
Backend: logs: be:1b2551293b0646f16682497dace8e37656db9c6cb3ffdcafdf086add4d26cd2e fe:
control: client.Login(false, 0)
control: doLogin(regen=false, hasUrl=false)
health("overall"): error: not in map poll
router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's
control: control server key from http://domain:8080: ts2021=, legacy=[2gr2g]
control: RegisterReq: onode= node=[1nYAF] fup=false nks=false
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
active login: default
Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
magicsock: SetPrivateKey called (init)
wgengine: Reconfig: configuring userspace WireGuard config (with 3/5 peers)
magicsock: adding connection to derp-7 for [l05Lf]
magicsock: 1 active derp conns: derp-7=cr0s,wr0s
derphttp.Client.Connect: connecting to derp-7 (tok)
magicsock: disco: failed to send *disco.Ping to [::ffff:xxxx]:1234: write udp6 [::]:57424->[::ffff:xxxx]:1234: sendto: network is unreachable
wgengine: Reconfig: configuring router
magicsock: disco: failed to send *disco.Ping to [::ffff:xxxxx]:43677: write udp6 [::]:57424->[::ffff::xxxxx]:43677: sendto: network is unreachable
monitor: RTM_NEWROUTE: src=, dst=172.20.1.0/24, gw=, outif=9, table=52
monitor: RTM_NEWROUTE: src=, dst=192.168.0.0/16, gw=, outif=9, table=52
monitor: RTM_NEWROUTE: src=, dst=10.0.0.0/16, gw=, outif=9, table=52

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

### Steps to reproduce

Use tailscaled to run directly, and then this problem will occur in a specific environment

### Are there any recent changes that introduced the issue?

Not available between networks

### OS

Linux

### OS version

debian 11

### Tailscale version

1.34.0

**Comment by bradfitz** [comment]
Looks like due to accepted routes shadowing the route you're connected over. And not running under a procedure manager so it probably then dies. Disable those routes or run in --tun=userspace-networking mode to bring it up without configuring host routing table entries.

**Comment by qiuxiangling** [comment]
> 
After the route is cancelled, it can be started successfully. The tailscale network can be accessed, but the external network is blocked

root@debian:~# ip rule
0:	from all lookup local
5210:	from all fwmark 0x80000 lookup main
5230:	from all fwmark 0x80000 lookup default
5250:	from all fwmark 0x80000 unreachable
5270:	from all lookup 52
32765:	from all fwmark 0x1 lookup 100
32766:	from all lookup main
32767:	from all lookup default

root@debian:~# ip route list table 52
100.100.100.100 dev tailscale0 
172.20.0.1 dev tailscale0 
172.20.0.2 dev tailscale0 
172.20.0.3 dev tailscale0 
172.20.0.4 dev tailscale0 
172.20.0.5 dev tailscale0 

nat table:
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
ts-postrouting  all  --  0.0.0.0/0            0.0.0.0/0           
MASQUERADE  all  --  172.20.3.0/24        0.0.0.0/0           

Chain ts-postrouting (1 references)
target     prot opt source               destination         
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            mark match 0x40000

filter table：
root@debian:~# iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ts-input   all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ts-forward  all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain ts-forward (1 references)
target     prot opt source               destination         
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            mark match 0x40000
DROP       all  --  100.64.0.0/10        0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain ts-input (1 references)
target     prot opt source               destination         
ACCEPT     all  --  172.20.0.6           0.0.0.0/0           
RETURN     all  --  100.115.92.0/23      0.0.0.0/0           
DROP       all  --  100.64.0.0/10        0.0.0.0/0 root@debian:~# iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ts-input   all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ts-forward  all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain ts-forward (1 references)
target     prot opt source               destination         
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x40000
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            mark match 0x40000
DROP       all  --  100.64.0.0/10        0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain ts-input (1 references)
target     prot opt source               destination         
ACCEPT     all  --  172.20.0.6           0.0.0.0/0           
RETURN     all  --  100.115.92.0/23      0.0.0.0/0           
DROP       all  --  100.64.0.0/10        0.0.0.0/0 

Is this the reason for the rule?

> Looks like due to accepted routes shadowing the route you're connected over. And not running under a procedure manager so it probably then dies. Disable those routes or run in --tun=userspace-networking mode to bring it up without configuring host routing table entries.

**Comment by qiuxiangling** [comment]
Already normal
