### ISSUE TITLE
The command tailscale status is reporting network issues.

### ISSUE THREAD

**Issue by fnfontana** [tailscale/tailscale#6681]
### What is the issue?

The command `tailscale status` is returning the following output:
```
# Health check:
#     - network-category: GetNetwork: Element not found.
```

### Steps to reproduce

Just type `tailscale status` at the terminal

### Are there any recent changes that introduced the issue?

I don't know exactly what it could be, maybe it's because I used this software recently: https://www.speedguide.net/downloads.php
But I'm almost sure that I have seen this error before I used it. 

### OS

Windows

### OS version

20H2 19045.2311

### Tailscale version

1.32.3

### Bug report

BUG-72cb7611e9ecbc7f670db97b0edab98053f1b6a50c4f4b67497203dd2ab95974-20221209162617Z-7e21a4f36ae85050

**Comment by bradfitz** [comment]
We think this was fixed in 1.34.0. Update and try again?

**Comment by fnfontana** [comment]
> We think this was fixed in 1.34.0. Update and try again?

Hello! I'm trying to update to `1.34.0` but I have installed Tailscale using Chocolatey, and seems that the update is not yet available at there, take a look: https://community.chocolatey.org/packages?q=tailscale

**Comment by bradfitz** [comment]
@fnfontana, pushed. (We're working on automating chocolatey updates in https://github.com/tailscale/tailscale/issues/303#issuecomment-1345042111)

**Comment by bradfitz** [comment]
You might need to wait an hour or two, thought. Updates don't appear right away.

**Comment by DentonGentry** [comment]
Closing as fixed
