### ISSUE TITLE
`DstIP` panics when called by wireguard-go

### ISSUE THREAD

**Issue by mihaip** [tailscale/tailscale#6686]
https://github.com/tailscale/tailscale/blob/c084c7d7edf425fa661e7543298c14a93f867c81/wgengine/magicsock/magicsock.go#L3524 implements `DstIP()` as `panic("unused")`, but at some point wireguard-go started to use it:

```
18:08:43 | panic: unused
18:08:43 | goroutine 58 [running]:
18:08:43 | tailscale.com/wgengine/magicsock.(*endpoint).DstIP(0x1301bf2e8?)
18:08:43 | tailscale.com@v1.34.0/wgengine/magicsock/magicsock.go:3524 +0x2c
18:08:43 | golang.zx2c4.com/wireguard/device.(*Device).RoutineHandshake(0x1301bf180, 0x4)
18:08:43 | golang.zx2c4.com/wireguard@v0.0.0-20220920152132-bb719d3a6e2c/device/receive.go:301 +0x3fc
18:08:43 | created by golang.zx2c4.com/wireguard/device.NewDevice
18:08:43 | golang.zx2c4.com/wireguard@v0.0.0-20220920152132-bb719d3a6e2c/device/device.go:314 +0x2cc
```
(From http://logz.ts.tailscale.com:9431/logs?start=2022-12-07T18%3A07%3A43Z&end=now&instances=e7ff75ea20ab049d1045aa3556d86094340f74ceeb952870c5a51acdadd2e4e1&match=)

Per http://go/panics there are ~90 occurrences of this per day.

**Comment by andrew-d** [comment]
Looks like it's called by this codepath:
https://github.com/WireGuard/wireguard-go/blob/bb719d3a6e2cd20ec00f26d65c0073c1dde6b529/device/receive.go#L299-L303

**Comment by bradfitz** [comment]
Old bug is old. Dates back to a975e86bb8a42f0be9faf16067ee55a6da55d767.
