### ISSUE TITLE
Suggestion: optimize GitHub workflows

### ISSUE THREAD

**Issue by talal** [tailscale/tailscale#669]
**Is your feature request related to a problem? Please describe.**

Not related to a problem. Just a few suggestions I would like to leave. Feel free to ignore :) 

**Describe the solution you'd like**

1. Cache your Go Modules inside your GitHub actions. This will speed up each run of your workflow since you won't need to download all the necessary dependencies everytime. [More info here](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows).

2. Use build matrix for all your `amd64` builds: linux, darwin, etc. From what I see, there is no difference in the individual workflows for these `GOOS`. This way you will only maintain 1 workflow file instead of 5 individual ones. [More info here](https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix).

**Describe alternatives you've considered**

N/A

**Additional context**

I'm happy to make a PR, if you prefer :)

**Comment by DentonGentry** [comment]
We added caching in https://github.com/tailscale/tailscale/blob/main/.github/workflows/coverage.yml and it has worked out.

We're likely to keep the platform build files separate, many plans for the future will make them diverge.
