### ISSUE TITLE
macsys: add `SUEnableAutomaticChecks` and `SUScheduledCheckInterval`, plumb tailcfg.ClientVersion

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6695]
Currently (I believe?) the only way to check for an update on the macOS macsys build is to stop it and restart it for Sparkle to do its thing.

We should do like the Windows client does and proactively check in the background and/or wire up the control->tailscaled tailcfg.ClientVersion push notifications (which can then optionally notify, if very important like a security update).

/cc @nickoneill @mihaip

**Comment by avidrissman** [comment]
In https://tailscale.com/changelog/#2023-03-22-client it says:
> Sparkle automatically checks [updates for the standalone package](https://pkgs.tailscale.com/stable/#macos).

Does this address this issue?

**Comment by DentonGentry** [comment]
Fixed in 1.38.2

**Comment by mihaip** [comment]
I had kept this open because the `tailcfg.ClientVersion` bit was not yet implemented. @bradfitz do you still want that, or should that be a separate issue?

**Comment by bradfitz** [comment]
Opened #7672
