### ISSUE TITLE
Tailscale DNS fails to resolve funnels

### ISSUE THREAD

**Issue by octylFractal** [tailscale/tailscale#6698]
### What is the issue?

A tailscale tunnel that isn't my own, e. g. https://pneuma.shark-harmonic.ts.net/, cannot be resolved while my device is connected to Tailscale. I expect it to work as if I was not connected. 

### Steps to reproduce

1. Connect to Tailscale.
2. Try to visit the URL given.
3. Get NXDOMAIN. 

### OS

Android

### OS version

Android 11

### Tailscale version

1.32.3

### Bug report

BUG-300cafbdd7b7ca8925f1468c16ca62031fe3d3fa85588234714a60134726e469-20221210195214Z-2109c98c88a9e605

**Comment by shayne** [comment]
We've rolled out a change to make all Funnels immediately resolvable via DNS wildcard. We follow up by adding geo-specific records optimized based on the location of the Funnel node.

**Comment by DentonGentry** [comment]
I believe this was resolved on Thursday by reducing the negative cache interval in the ts.net SOA record. Please reopen if still seen.

If reading this months from now: don't reopen this one, open a new issue. You're encountering something different.

**Comment by octylFractal** [comment]
Works for me, thanks!
