### ISSUE TITLE
Where is the logtail error caused

### ISSUE THREAD

**Issue by qiuxiangling** [tailscale/tailscale#6702]
### What is the issue?

● tailscaled.service - Tailscale node agent
     Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-12-08 10:36:37 CST; 2 days ago
       Docs: https://tailscale.com/kb/
   Main PID: 511 (tailscaled)
     Status: "Connected; default; 172.20.0.1"
      Tasks: 14 (limit: 4524)
     Memory: 45.1M
        CPU: 1h 14min 8.869s
     CGroup: /system.slice/tailscaled.service
             └─511 /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641

Dec 11 09:28:19 deb-arm64 tailscaled[511]: logtail: [v1] backoff: 27119 msec
Dec 11 09:29:16 deb-arm64 tailscaled[511]: logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: i/o timeout (in 30.001s), trying bootstrap...
Dec 11 09:29:31 deb-arm64 tailscaled[511]: logtail: upload: log upload of 30582 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10d4feb74dfbf0bf9ef0a123c4364aecb4267545207930>
Dec 11 09:29:31 deb-arm64 tailscaled[511]: logtail: [v1] backoff: 32177 msec
Dec 11 09:30:33 deb-arm64 tailscaled[511]: logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: i/o timeout (in 30.002s), trying bootstrap...
Dec 11 09:30:48 deb-arm64 tailscaled[511]: logtail: upload: log upload of 30582 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10d4feb74dfbf0bf9ef0a123c4364aecb4267545207930>
Dec 11 09:30:48 deb-arm64 tailscaled[511]: logtail: [v1] backoff: 35702 msec
Dec 11 09:31:54 deb-arm64 tailscaled[511]: logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: i/o timeout (in 30.001s), trying bootstrap...
Dec 11 09:32:09 deb-arm64 tailscaled[511]: logtail: upload: log upload of 30582 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/10d4feb74dfbf0bf9ef0a123c4364aecb4267545207930>
Dec 11 09:32:09 deb-arm64 tailscaled[511]: logtail: [v1] backoff: 43670 msec

### OS

Linux

### OS version

debian 11

### Tailscale version

1.30.1

**Comment by bradfitz** [comment]
Are you in a country that blocks the internet and/or LetsEncrypt?

**Comment by DentonGentry** [comment]
You're saying it works and is able to connect now?

The logs usually go to journalctl. If you're running tailscaled in a terminal with the logs appearing in the terminal, you're welcome to redirect to /dev/null instead.

**Comment by qiuxiangling** [comment]
> You're saying it works and is able to connect now?
> 
> The logs usually go to journalctl. If you're running tailscaled in a terminal with the logs appearing in the terminal, you're welcome to redirect to /dev/null instead.

Sorry, tailscaled is run using systemd. Modify tailscaled Unable to resolve after service

ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS &>/dev/null

**Comment by DentonGentry** [comment]
Great, it sounds like it is working.

**Comment by qiuxiangling** [comment]
> Modify tailscaled Unable to resolve after service



> Great, it sounds like it is working.



> Great, it sounds like it is working.

No, they still report errors if they are not resolved
