### ISSUE TITLE
FR:  TS_KUBE_SECRET cannot be unset. As it defaults to `tailscale` if it's `""`

### ISSUE THREAD

**Issue by stavros-k** [tailscale/tailscale#6704]
### What are you trying to do?

Run ts in a kube environment, without the use of TS_KUBE_SECRET

### How should we solve this?

In the case that someone runs tailscale in a pod with other container(s), you can't give access to the secret to a single container on that pod, service account binds to the whole pod.

Please allow having empty TS_KUBE_SECRET, so people can set a TS_STATE_DIR of their liking and also pass TS_AUTH_KEY as they please too.

Thanks.

https://github.com/tailscale/tailscale/blob/7b65b7f85c6484cc852c201423ac577d9a4ceebf/cmd/containerboot/main.go#L40-L41

### What is the impact of not solving this?

When using it in a pod with other containers, you are force to bind a Service account to tall the containers inside that pod.

**Comment by danderson** [comment]
Hmm, looks like we never supported this, even in the old run.sh PID 1. I'm surprised it's taken this long for someone to need it.

I can definitely adjust containerboot so that an explicit TS_KUBE_SECRET="" disables secret storage. The question will be if all the regression tests of other combos of settings will still pass...

**Comment by stavros-k** [comment]
> Hmm, looks like we never supported this, even in the old run.sh PID 1. I'm surprised it's taken this long for someone to need it.
> 
> 
> 
> I can definitely adjust containerboot so that an explicit TS_KUBE_SECRET="" disables secret storage. The question will be if all the regression tests of other combos of settings will still pass...


No idea if GO can do that. I guess it can. Check if env key exists, if exists and it's empty, disable the secret storage. (Check the it does not being set in any dockerfile as well).
If does not exist at all, default to "tailscale". So it's backwards compatible.

An easy solution might be to check for "ignore" or "disabled".
But then again it might look hacky.

**Comment by danderson** [comment]
Yeah Go can distinguish between an unset and an empty envvar, our container image just didn't. The question is more if changing the semantics of `TS_KUBE_SECRET=""` breaks any other possible configurations of the container.

Good news though, I just implemented it and the answer is: it's fine, all our regression tests still pass with the new behavior. Sending PR shortly.

**Comment by danderson** [comment]
Fixed at head. I think it's benign enough to get out in a patch release, so I'll try to get it into 1.34.2 some time next week.

**Comment by adyanth** [comment]
@danderson is this part of the 1.34.2 release? I do not see the commit c89875f416ca7e9ec89dc17bb0af6ce7a84c9159 here: https://github.com/tailscale/tailscale/compare/v1.34.0...v1.34.2

**Comment by adyanth** [comment]
@danderson is this in 1.34.2? I do not see the commit/PR c89875f / #6767  here: https://github.com/tailscale/tailscale/compare/v1.34.0...v1.34.2

**Comment by DentonGentry** [comment]
No, it was missed when cherry-picks for 1.34.2 were being done.

1.36.0 will be a new branch from `main` and definitely contain the commit. Until then, the `unstable-1.35.*` containers can be used.

**Comment by Ornias1993** [comment]
> No, it was missed when cherry-picks for 1.34.2 were being done.
> 
> 1.36.0 will be a new branch from `main` and definitely contain the commit. Until then, the `unstable-1.35.*` containers can be used.

For any serieus use, it cannot be used. So we basically have broken TrueNAS SCALE Apps for the time being for example, as we cannot start shipping unstable containers.

**Comment by DentonGentry** [comment]
If Tailscale 1.32.x worked for TrueNAS SCALE in Kubernetes deployments, you're welcome to keep using it and skip 1.34. We're expecting 1.36 to be delivered in weeks, not months.

**Comment by stavros-k** [comment]
Tbf, we would have sticked to v1.32 if it wasn't this issue https://github.com/tailscale/tailscale/issues/6613
That caused the bots to update to v1.33 without knowing that it was an unstable tag and we have since adapted the deployment to use the new containerboot in go.

Sorry, I'm not going to spent time reverting it. 
I'll let oru users know that will expect a fix when 1.36 is out then.

**Comment by DentonGentry** [comment]
The 1.36.0 container has been released.
