### ISSUE TITLE
Tailscale SSH does not work properly with fish shell

### ISSUE THREAD

**Issue by aohorodnyk** [tailscale/tailscale#6705]
### What is the issue?

When I try to connect through Tailscale SSH to my remote hosts from fish shell it generates me this error
```
ssh my_host
fish: Unsupported use of '='. In fish, please use 'set hook $(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/316\", \"user\": \"%s\", \"machine\": \"%s\", \"remote_shell\": \"%s\"}}" $(whoami) $(hostname) ${SHELL##*/} | command od -An -v -tx1 | command tr -d " \n")'.

exit status 123
Connection to my_host closed.
```

When I switch to ZSH or BASH everything works well.

### Steps to reproduce

1. Install fish shell
2. Install Tailscale
3. Connect to SSH host through Tailscale
4. See the error

### Are there any recent changes that introduced the issue?

It worked before, so looks like it's some newly introduced bug.

### OS

macOS

### OS version

13.0.1

### Tailscale version

1.32.3 (App Store)

### Bug report

BUG-948af1eb3d95e091460c657a37f726d1afe5b5fb9ab13ec9b506c3057debeb8b-20221211221139Z-2fc400c62c09b3e5

**Comment by bradfitz** [comment]
Are you sure it's fish, or is it some start-up scripts that fish is execution, and those start-up scripts are expanding to something invalid, perhaps because of environment differences?

What are your fish startup scripts?

cc @maisem

**Comment by bradfitz** [comment]
What version of Tailscale are you running on the remote Linux side?

**Comment by aohorodnyk** [comment]
@bradfitz Thanks for help 🥇 You are right, the error is related to WARP terminal.

**Comment by cap10morgan** [comment]
@aohorodnyk Running into this too. Did you open an issue w/ Warp? If so, can you link to it here? Thanks!

**Comment by aohorodnyk** [comment]
@cap10morgan no, I have not created an issue in their repo. I don't use Warp anymore, I have moved to standard Terminal.
