### ISSUE TITLE
Android 11 Support

### ISSUE THREAD

**Issue by EverydayPineapple** [tailscale/tailscale#671]
**Describe the bug**
Android 11 devices don't seem to be able to authenticate. I've only got Google Auth to go from but when clicking "Sign in with Google" a blank view animates from top to bottom. If I choose "Sign in with other" the webview gets stuck after signing in with my Google account. 

**To Reproduce**
1. Open app
2. Click on 'sign in with google'
3. See that it doesn't sign in

**Expected behavior**
Should be able to auth. 

**Version information:**
 - Device: Pixel 4XL
 - OS: Android 11 beta3
 - Tailscale version: 0.1.16-0-g1003774

**Comment by bradfitz** [comment]
Any chance you can share the adb logcat or adb bugreport?

**Comment by EverydayPineapple** [comment]
Weird - as I went to take the logs it's successfully logged in. I'd imagine there's some other issue as I've been reported this by another Android 11 user too.

**Comment by EverydayPineapple** [comment]
I'll close this for now unless I can get more info

**Comment by bradfitz** [comment]
We were just having a login server problem. It was probably that.

**Comment by EverydayPineapple** [comment]
OK makes sense. Thanks!
