### ISSUE TITLE
FR: Add key expiry time to status

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#6712]
### What are you trying to do?

I would like a mechanism to find the key expiry time from the CLI

### How should we solve this?

add a line to `tailscale status --json` with the expiry time of the current key.

### What is the impact of not solving this?

The information is only available in the API currently.

**Comment by DentonGentry** [comment]
I'm not sure we will want to do this:
- the node doesn't know its own expiry time, deliberately. This is how the "Temporarily Extend Key" function in the admin panel works, for example
- the API is the source of truth for key expiry information, giving a tailnet-wide view. Adding it to the CLI output encourages nodes to cache and act on it, which is not the right thing to do and something we do not want to encourage.

**Comment by mihaip** [comment]
> the node doesn't know its own expiry time

It's included in the netmap ([Node.KeyExpiry](https://github.com/tailscale/tailscale/blob/835a73cc1fa6e31703047b09a22c0a3a27f28bdd/tailcfg/tailcfg.go#L190)) and the Mac and Windows GUI clients do display it, especially when it's imminent.

**Comment by mplough-kobold** [comment]
Given that the client and server disagree as to when the key expires (see https://github.com/tailscale/tailscale/issues/7022, https://github.com/tailscale/tailscale/issues/6740), I think that it's important to be able to get at this information from the CLI.  If nothing else it would empower users to help troubleshoot the issue.
