### ISSUE TITLE
v1.34 macOS client (macOS 10.14.6) no enable button

### ISSUE THREAD

**Issue by megane999** [tailscale/tailscale#6721]
### What is the issue?

Can't see enable (turn on) button (switch).

![Снимок экрана 2022-12-13 в 12 47 33](https://user-images.githubusercontent.com/2047240/207285025-67e04b80-ce73-4ef0-b262-a156d4abe4bd.png)

### OS

macOS

### OS version

macOS 10.14.6

### Tailscale version

1.34.0

**Comment by bradfitz** [comment]
Is this a dup of #6707?

cc @mihaip

**Comment by mihaip** [comment]
Yes, now that I see that it's not actually a VoiceOver issue, I agree that it's a dupe.
