### ISSUE TITLE
Latest windows installer installing 32 bit version/Program Files (x86) on 64 bit systems

### ISSUE THREAD

**Issue by hj-collab** [tailscale/tailscale#6726]
### What is the issue?

Latest windows installer installing 32 bit version/Program Files (x86) on 64 bit systems.

### Steps to reproduce

1) Visit Tailscale Website.
2) Download Windows Installer.
3) Install on a 64 bit system.
4) Notice the installation location.

### Are there any recent changes that introduced the issue?

Not sure. May be recent updates. I am coming back to Tailscale after a few months. So not sure.

### OS

Windows

### OS version

Windows 11 22H2

### Tailscale version

1.34.0

**Comment by bradfitz** [comment]
Which installer? MSI or NSIS (exe)?

cc @dblohm7

**Comment by DentonGentry** [comment]
I understand that you want a fix. Current efforts are going in to the MSI installer. This is the first report we have of issues with Windows Defender; you're not able to install the MSI at all?

**Comment by DentonGentry** [comment]
We have not been able to reproduce an issue with Windows Defender, after looking into it during https://github.com/tailscale/tailscale/pull/6996

**Comment by DentonGentry** [comment]
I believe the 32bit / 64bit issue was fixed by https://github.com/tailscale/corp/pull/10889 (which you won't be able to see, sorry) in Tailscale release 1.40 and later.

Barring further comment, we'll expect to close this during the next regular bug scrub.
