### ISSUE TITLE
FR: Windows installer automatically update non-default install path

### ISSUE THREAD

**Issue by Kicend** [tailscale/tailscale#6731]
### What are you trying to do?

Update Tailscale on Windows installed in a nonstandard location, without having to specify a path manually each time.
The idea is to add a function in the Tailscale installer that, when updating the programme, pulls out the current path where the tailscale ipn files are located. 

### How should we solve this?

The registry key that is created when the programme is installed for the first time can be used. The key is located under this path: HKEY_LOCAL_MACHINE\SOFTWARE\Tailscale IPN

### What is the impact of not solving this?

This is not a critical feature, but it adds convenience to the programme update process.

**Comment by DentonGentry** [comment]
Last week I installed Tailscale 1.37.101 to a non-default location in `C:\Program Files (x86)\Tailscale IPN b1904`.

Today I updated to 1.37.135 using the MSI installer from https://pkgs.tailscale.com/unstable/#windows

The update retained the non-standard location, updating the binaries in place.

```
C:\Users\dgentry>dir "c:\Program Files (x86)\Tailscale IPN b1904"
 Volume in drive C has no label.
 Volume Serial Number is AA73-648A

 Directory of c:\Program Files (x86)\Tailscale IPN b1904

02/12/2023  06:53 AM    <DIR>          .
02/12/2023  06:53 AM    <DIR>          ..
02/11/2023  01:11 AM        12,418,592 tailscale-ipn.exe
02/11/2023  01:12 AM        10,600,992 tailscale.exe
02/11/2023  01:13 AM        15,501,344 tailscaled.exe
02/11/2023  01:10 AM           427,552 wintun.dll
               4 File(s)     38,948,480 bytes
               2 Dir(s)  173,694,439,424 bytes free

C:\Users\dgentry>dir "c:\Program Files (x86)\Tailscale IPN b1904"
 Volume in drive C has no label.
 Volume Serial Number is AA73-648A

 Directory of c:\Program Files (x86)\Tailscale IPN b1904

02/18/2023  03:47 PM    <DIR>          .
02/18/2023  03:47 PM    <DIR>          ..
02/17/2023  02:46 AM        12,453,408 tailscale-ipn.exe
02/17/2023  02:46 AM        11,074,080 tailscale.exe
02/17/2023  02:46 AM        15,347,232 tailscaled.exe
02/17/2023  02:46 AM           427,552 wintun.dll
               4 File(s)     39,302,272 bytes
               2 Dir(s)  173,651,845,120 bytes free

C:\Users\dgentry>
```

Marking as fixed in the MSI installer.
