### ISSUE TITLE
container state file being lost on restart

### ISSUE THREAD

**Issue by MekayelAnik** [tailscale/tailscale#6733]
### What is the issue?

Everytime the tailscale docker container restarts it addes new machine with new name (i.e. if the previous before restart was 'tailscaled' it would create 'tailscaled-1' then again after restart 'tailscale-2' and so on), though the AUTH_KEY is not changed. Also the subnet route is turned off if it was on before restart. In short the docker container version of 'tailscale' completely losses the previous state after a restart. But it should restart with all the previous settings as it was before the restart.

### Steps to reproduce

1. Deploy a 'tailscale' docker container with AUTH_KEY.
2. Enable 'subnet route' in the admin panel.
3. Restart the docker container.
4. Look at the admin panel.

### OS

Linux

### OS version

Dietpi arm64 v8.11.2,  Raspberry Pi4B, docker: 20.10.21

### Tailscale version

1.34.1 (docker container)

**Comment by DentonGentry** [comment]
This means the tailscaled.state file is not being stored in persistent state. The usual way to accomplish this is to mount persistent storage on /var/lib/tailscale.

**Comment by MekayelAnik** [comment]
Thanks for the quick reply, but no '/var/lib/tailscale' is in a presistant  storage. I can see there are multiple log files created in the volume, named as the machines created on restarts.

![Screenshot_20221214_070754_JuiceSSH](https://user-images.githubusercontent.com/32511246/207480083-9c4b1221-93f9-4b05-980e-18190ddefb8c.jpg)

**Comment by DentonGentry** [comment]
There is supposed to be a tailscaled.state file in that directory, so it is instead being stored somewhere that it is being lost when the container shuts down (which matches the reported symptoms).

A TS_STATE environment variable would specify where the tailscaled.state file is stored, if that is being set.
A TS_STATEDIR environment variable would specify a directory path other than /var/lib/tailscale, if that is being set.

**Comment by MekayelAnik** [comment]
> 

Didn't solve the issue. Perhaps if a volume option is added in the container in the future (i.e. as it is now for "/var/lib")
![Screenshot_20221214_074039_JuiceSSH](https://user-images.githubusercontent.com/32511246/207485094-8e0765d4-041b-4174-8c28-8357776eb80d.jpg)
![Screenshot_20221214_074142_Brave](https://user-images.githubusercontent.com/32511246/207485100-1324933c-bbea-4684-9f8d-7d85e09c3208.jpg)
![Screenshot_20221214_071540_Brave](https://user-images.githubusercontent.com/32511246/207485104-9b0ad788-1ca0-4cac-91e5-dd02ec1479dc.jpg)
, this can be easily averted. Also a request, PLEASE add detailed documentation on the hub.docker.com for tailscale container deployment.

**Comment by MekayelAnik** [comment]
> 
Doesn't solve the issue. Perhaps if a volume option is added in the future as it is now for the "/var/lib", this can easily be averted.
REQUEST: 1. Add proper detailed documentation on hub.docker.com for 'tailscale' container deployment.
2. Add Advertise-Exit-Node option in container. (Does not work what ever is done)
![Screenshot_20221214_071540_Brave](https://user-images.githubusercontent.com/32511246/207485857-4be1ee3f-bab1-4038-8792-edf3cea99301.jpg)
![Screenshot_20221214_074039_JuiceSSH](https://user-images.githubusercontent.com/32511246/207485864-a0d636fa-090b-4adf-8620-ec9f640c82dc.jpg)
![Screenshot_20221214_074142_Brave](https://user-images.githubusercontent.com/32511246/207485866-1c470485-a8c0-4931-a1bf-bfff3f280683.jpg)

**Comment by DentonGentry** [comment]
> Doesn't solve the issue.

I don't really understand what this means, but to be clear: the root cause here is that `tailscaled.state` is being stored in volatile storage which is being lost when the container shuts down. There isn't another problem.

> Perhaps if a volume option is added in the future as it is now for the "/var/lib", this can easily be averted.

https://hub.docker.com/r/tailscale/tailscale calls for `/var/lib:/var/lib`, but if you want to do something else you're welcome to.
```
docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged tailscale/tailscale tailscaled
```

If you have non-volatile storage mounted somewhere else, like /opt/tailscale within the container, you can set `TS_STATEDIR=/opt/tailscale` to have `tailscaled` store its state in that directory instead of `/var/lib/tailscale`

**Comment by MekayelAnik** [comment]
RE: If you have non-volatile storage mounted somewhere else, like /opt/tailscale within the container, you can set TS_STATEDIR=/opt/tailscale to have tailscaled store its state in that directory instead of /var/lib/tailscale

With due respect sir, I am doing what you are telling me to do, but no tailscale.state file is being saved at that non-volatile location. IT IS NOT WORKING as your are saying it should be. That's why i have provided the screenshots. Anyways thanks for the help, but didn't solve the issue.

**Comment by Mansarde** [comment]
I've just tried it myself, followed the instructions of the dockerhub page and everything seems to work as expected.

The only times tailscale adds another machine to the admin console is when I had "**Reusable**" enabled for the auth-key and the contents of `/var/lib/tailscale` got deleted.

The latter only happens if I...
... deleted either the container-volume (which contained the state in `/var/lib/tailscale`)
... or deleted the `/var/lib/tailscale` folder of the host when I mapped it (instead of using a volume)
... or deleted the temporary volume that is created if you don't specify any volume or mapping.

Mabye it would help if you tell us the exact settings you chose for the auth-key.

**Comment by MekayelAnik** [comment]
YES - I have set the `Reusable` enabled for the auth key in the Admin Panel. I didn't know it would create this havoc.
I can assure you the `/var/lib/tailscale` was mapped to a specific non-volatile directory.
I will set `Reusable` to disabled for the auth key and give it a try today. If the problem is resolved, Inshallah will close the issue.
P.S.: Please give a clear warning the documentation and/or in the Admin Panel what the `Reusable` option of the auth key will yeld. This will save some pulling-hair-out moments for noobs like me (expecting there are at least a few like me). 
Cheers!

**Comment by DentonGentry** [comment]
`tailscale up --auth-key=tskey-...` won't use the authkey, whether reusable or not, if it already has a state file with a node key.

If one uses `tailscale up --auth-key=tskey-... --force-reauth` one can force it to throw away the old node key and create a new one, but that does not appear to be the case here.

**Comment by MekayelAnik** [comment]
Note: What I was trying to achieve was possible without TS_AUTH_KEY. The container can be run (and should be run without auth key for normal use cases).
Auth key is not required  for normal user use cases. 
Tailscale is working prefetly. 
Tailscale is a phenomenal and must have tool for server admins!
Thanks Tailsacle team specially @DentonGentry @Mansarde
