### ISSUE TITLE
Need a way to force update with Mac standalone GUI version

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#6736]
### What is the issue?

The Mac standalone GUI version uses Sparkle for updates. If you quit and restart it, the Sparkle check runs and you’re offered the update. However, there’s no way to force Sparkle to check for an update (AFAICT) without quitting.

### Steps to reproduce

Wait for an update.

Want to force an update immediately.

### OS

macOS

**Comment by DentonGentry** [comment]
One could download the installer to install an update: https://pkgs.tailscale.com/stable/#macos

**Comment by avidrissman** [comment]
Right, but that’s not this bug. This particular issue is that you ship that version with Sparkle as an updater, but there’s no way that I can find to tickle Sparkle to do the update.

This is especially a problem remotely. If an update is kicked off with Sparkle, Sparkle will run the download, replace, and restart cycle automatically, so it’s suitable for remote updates. Requiring a manual quit/restart means that you’re disconnected from your remote session, unable to connect. Same with a manual installer download.

You ship Sparkle; please set up a “check for update now” button.

**Comment by bradfitz** [comment]
Dup of #6695
