### ISSUE TITLE
FR: Duplicate nodes block

### ISSUE THREAD

**Issue by elpaxel** [tailscale/tailscale#6738]
### What are you trying to do?

I will say right away I have not used Tailscale yet. All assumptions are based on information that I found on the Internet and in this repository.

Let's say I install Tailscale on a "rogue" vps provider. This provider is cloning my VM to access my Tailscale network.
Do both VMs now have full access to my Tailscale network or will they both fail ?
The only sign that my VM is "stolen" will be the “Duplicate node key” badge ?

### How should we solve this?

I understand that this problem is not directly related to Tailscale and that the best way is not to install Tailscale to a shady host.
But it would be nice to have additional protection.

You can, for example, deauthorize both devices until measures are taken to eliminate duplicates.

### What is the impact of not solving this?

Unauthorized access to my private network.

### Anything else?

I have seen "One-off" auth keys in the documentation. But if I understand correctly, after connecting to the network with an auth key, Tailscale generates a private key file that can be duplicated.

**Comment by DentonGentry** [comment]
> Do both VMs now have full access to my Tailscale network or will they both fail ?
> The only sign that my VM is "stolen" will be the “Duplicate node key” badge ?

They will both be trying to use the same node key. Only one will work at any given time, but they will repeatedly prompt hosts they are trying to communicate with to shift their wireguard tunnels from one IP address to the other. To the coordination server and to other nodes on the tailnet it looks like the node has highly unreliable connectivity and is failing back and forth between two IP addresses.

Removing the node from https://login.tailscale.com/admin/machines will revoke the key that both are using.

**Comment by DentonGentry** [comment]
Nothing more to add.
