### ISSUE TITLE
macOS: menu loses username & link to admin console when device is tagged

### ISSUE THREAD

**Issue by jamesez** [tailscale/tailscale#6741]
### What is the issue?

I have an ACL where I tag devices I expect to ssh _from_, to try to limit lateral movement between different constellations of systems. This may be misguided.

Upon authenticating to Tailscale, the macOS menu shows my username and GitHub picture, and the pop-out menu includes the "admin panel" menu item.

When I change the device to `tag:controller`, the menu changes to hostname.domain.ts.net, loses the picture, and drops the link to the admin web app.

### Steps to reproduce

1. Join the Talent as an admin user.
2. Observe the macOS menu has the username and pop-out menu
3. Tag the device in Tailscale
4. Observe the menu has now changed.

### OS

macOS

### OS version

macOS Ventura 13.1

### Tailscale version

1.34.0 (App Store)

### Bug report

BUG-fe68becce41003afa4500c6f48a50a419ea0a9ffccc7ad16f0cbb50985d98520-20221214173921Z-6121f94e52465c88

**Comment by DentonGentry** [comment]
That is the intent of the Tag feature: the device is no longer owned by a particular User, it is now owned by the Tag.

So for example:
- when a User leaves and is removed from the tailnet, all of their devices are revoked. Tagged nodes they happen to have created live on, so all of the servers don't disappear when an IT person departs.
- the access control is determined by the Tag, not the User who might have originally created the node.

https://tailscale.com/kb/1068/acl-tags/

**Comment by jamesez** [comment]
Hey thanks for the fast response. The KB makes it clear, I just didn't expect it and so didn't go looking. 

Closing!
