### ISSUE TITLE
mobile: support auth via authkey

### ISSUE THREAD

**Issue by MDrollette** [tailscale/tailscale#675]
**Is your feature request related to a problem? Please describe.**

I have devices running android that I would like to connect to Tailscale but that I don't want/am unable to log into GSuite from.

**Describe the solution you'd like**

I would like to be able to generate a one-time use authkey and be able to enter that on the android device to authenticate. Or, similar to the cli, receive a URL that I can use to authorize the device from another machine.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3xm4x)

**Comment by bradfitz** [comment]
What about scanning a QR code from your desktop? (ala 1password, etc)

**Comment by MDrollette** [comment]
> What about scanning a QR code from your desktop? (ala 1password, etc)

That would be even easier. I suppose in could work either direction? Scanning an authkey from the new device, or scanning the generated auth url from the logged-in device?

**Comment by DentonGentry** [comment]
In case it is useful: when running an android device on AOSP using the (very rudimentary) supplied browser, google.com would not support that browser for login but Microsoft did. I used Microsoft authentication for that device.

**Comment by arunsathiya** [comment]
I remember being able to login into Google using a browser, but these keys, it appears I have to add that Google account to phone as well. Would be great to avoid that, for situations where I am sharing my Tailscale with friends and family. Easier to give auth keys than share my Google password.

**Comment by conorpwr** [comment]
Do the Auth Keys available in the admin console help with this use case? I've generated one as a test but I can't see any obvious way in the iOS sign in flow to use this instead of having to try sign into my Github account on my phone.

**Comment by DentonGentry** [comment]
The iOS and Android user interfaces are relatively minimal and there isn't currently a way to use an authkey to authorize them.

One note about logging in to a GSuite / Microsoft / Github account: once Tailscale has authenticated, you don't have to leave the account logged in elsewhere within the mobile. You can log out and remove the account from the Settings and the browser.

**Comment by adamyi** [comment]
+1 on this please. It's hard to sign in to my gsuite account on my iOS device

**Comment by DentonGentry** [comment]
If you don't normally have your account logged in on the iOS device, when the Tailscale app opens a browser to authenticate you can copy the URL and send it over to some other device where you are logged in. Once authenticated on that other device, the iOS device will proceed to join the tailnet.

**Comment by wwqgtxx** [comment]
> If you don't normally have your account logged in on the iOS device, when the Tailscale app opens a browser to authenticate you can copy the URL and send it over to some other device where you are logged in. Once authenticated on that other device, the iOS device will proceed to join the tailnet.

I tried more times but couldn't find a way to copy the verification link under the iPad.

**Comment by dweinstein** [comment]
I figured out a workaround for this in case it helps other folks:

I set an HTTP(S) proxy between the mobile device and the internet and captured the HTTPS traffic (after installing my CA to the device). Used mitmproxy (https://mitmproxy.org/) and in my case for iOS https://docs.mitmproxy.org/stable/concepts-certificates/. I then set an intercept on the url (access to `login.tailscale.com`):

<img width="459" alt="image" src="https://user-images.githubusercontent.com/794478/147503272-b4522b6a-6a41-4200-9ca0-d46233905621.png">

and copied the URL `login.tailscale.com /login?refresh=true&next_url=<RANDOM CODES>` from the network flow and then loaded that in my non-iOS device browser where I was already logged into (in my case) Google. Then the app just handled the rest.

**Comment by Omeryl** [comment]
> > If you don't normally have your account logged in on the iOS device, when the Tailscale app opens a browser to authenticate you can copy the URL and send it over to some other device where you are logged in. Once authenticated on that other device, the iOS device will proceed to join the tailnet.
> 
> I tried more times but couldn't find a way to copy the verification link under the iPad.



> > If you don't normally have your account logged in on the iOS device, when the Tailscale app opens a browser to authenticate you can copy the URL and send it over to some other device where you are logged in. Once authenticated on that other device, the iOS device will proceed to join the tailnet.
> 
> In my case I couldn't get the URL because it wouldn't open the browser rather it was an embedded webview that didn't let me copy anything out.

For the next person to come around to this, you can copy links from embedded browsers (like used by Tailscale) by long-holding the domain at the top of view, and then tapping copy. This is an iOS UX thing, not Tailscale, and we all know how much Apple likes to hide features sometimes.

**Comment by DentonGentry** [comment]
Another option has become available since the issue was initially filed: the mobile device can generate a QR code to allow some other device to authenticate it.

![QR-code](https://user-images.githubusercontent.com/1140756/187040895-6237b9df-8984-4fbd-a0e6-482e8010f777.png)

**Comment by nikitakuklev** [comment]
There is still a bit of chicken and egg problem with setting up first camera-capable device in the chain. 

Is there a fundamental roadblock to having a standard QR scan workflow? Namely, as discussed above, a button on the web admin page (or CLI terminal, or another tailscale app instance) to generate a QR code that can then be scanned by new Tailscale app instance on login screen.

**Comment by kpfleming** [comment]
I just used the QR Code workflow, scanned it using my existing phone which does have the tailnet's Google account and it worked fine.

**Comment by DentonGentry** [comment]
At this point I believe this use-case is sufficiently met by using the QR code to finish authentication using a separate device where one is already logged in. Barring further comment we'll expect to close this during the next regular bug scrub.
