### ISSUE TITLE
MagicDNS mv resolv.conf when etc is read only ... failed and resolv.conf is not updated

### ISSUE THREAD

**Issue by father-mande** [tailscale/tailscale#6774]
### What is the issue?

On a system using a **squashfs** for root / and /etc, **resolv.conf is a link to a writable place**
when magicDNS is used ... tailscale display message that it's not possible to mv /etc/resolv.conf (normal for a read only fs)
AND resolv.conf is not updated.

do you think it's possible to workaround this (at this time, I rewrite resolv.conf manually using a short shell script launched after tailscaled is up)
for ex. do : 
if resolv.conf is a link ... cd to dirname of the realpath and do change at this place
other solution can exist ...
ex. save resolv.conf in a tailscale folder (like /var/lib/tailscale) under a directory (dns for ex.) or directly.
... and other good idea from you (100% better than my suggestion)

Philippe.

### Steps to reproduce

get a system with a root folder read only and /etc/resolv.conf is a link
install and run tailscale (other download) or Entware on some openwrt and other router.
configure magicDNS.

do tailscale status to see the error (one time) or in the log

### Are there any recent changes that introduced the issue?

Don't know ... I just add this system to use it as a subnet router.

### OS

Linux, Windows, Android, Other

### OS version

Keenetic OS 3.9.1 (Linux based on mips arch)

### Tailscale version

1.32 (from Entware delivery)

### Bug report

BUG-a98f4eb4407b8752c346debdd269709d3ce5eecd6bfe2d77538a5ff3a2d4c5fa-20221217163303Z-32b11445800e6171

**Comment by bradfitz** [comment]
If you want to manage DNS, start tailscale with `tailscale up --accept-dns=false` and then tailscaled won't try to configure your OS at all. Then you can do whatever you want with `/etc/resolv.conf`.

(Related reading: https://tailscale.com/blog/sisyphean-dns-client-linux/)

**Comment by father-mande** [comment]
Hi,

Thanks ... I know this ... but I don't want to manage myself ... MagicDNS is a good solution for all my system and I prefer to have a solution as for other .
but, as I write, I know how using mMagicDNS by modding myself resolv.conf

so you can reject this ... up to if no luck ... problem will exist also on other palatiform.

Thanks.
Best regards.

**Comment by bradfitz** [comment]
MagicDNS will still answer on 100.100.100.100 if you point your resolv.conf at it.
