### ISSUE TITLE
tailscale(d) don't update iptables after start (go-iptables or iptables problem)

### ISSUE THREAD

**Issue by father-mande** [tailscale/tailscale#6775]
### What is the issue?

When tailscaled start  ...
run tailscale status return this error : 
x Health check:
x     - router: adding [-m mark --mark 0x40000/0xff0000 -j MASQUERADE] in v6/nat/ts-postrouting: running [/opt/sbin/ip6tables -t nat -A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE --wait]: exit status 1: ip6tables: No chain/target/match by that name.

NO iptables are created ? EXCEPT the nat one (ts-postrouting as hereafter.
BUT  using iptables 1.4.21 doing it (apply rules adapted from an another system) run as well

workaround ... launch a shell script to cerate tables and rules and restart tailscale ...
result is (it works) : 
~ # iptables -S | grep "ts-"
-N ts-forward
-N ts-input
-A INPUT -j ts-input
-A FORWARD -j ts-forward
-A ts-forward -i tailscale0 -j MARK --set-xmark 0x40000/0xff0000
-A ts-forward -m mark --mark 0x40000/0xff0000 -j ACCEPT
-A ts-forward -s 100.64.0.0/10 -o tailscale0 -j DROP
-A ts-forward -o tailscale0 -j ACCEPT
-A ts-input -s 100.9xx.yy/32 -i lo -j ACCEPT
-A ts-input -s 100.115.92.0/23 ! -i tailscale0 -j RETURN
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
~ # iptables -S -t nat | grep "ts-"
-N ts-postrouting
-A POSTROUTING -j ts-postrouting
-A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE

All seems to work as expected ....

### Steps to reproduce

No idea, because it's specific to the system (a router with Entware support used as switch and access point ... trageted to be a subnet router for tailscale.
router is a Keenetic Giga mips architecture .

### Are there any recent changes that introduced the issue?

No, just starting test on this router.

### OS

Linux, Windows, Android, Other

### OS version

Keenetic OS 3.9.1 (Linux based on mips arch)

### Tailscale version

1.32 (from Entware delivery)

### Bug report

BUG-a98f4eb4407b8752c346debdd269709d3ce5eecd6bfe2d77538a5ff3a2d4c5fa-20221217163303Z-32b11445800e6171

**Comment by bradfitz** [comment]
Your kernel is probably missing some IPv6 kernel options. Note that the error was about `ip6tables`, not `iptables`.

/cc @andrew-d @danderson

**Comment by father-mande** [comment]
I will check ... even all run as well when using directly iptables or ip6tables or real xtables-multi

Philippe.
