### ISSUE TITLE
Taildrop doesn't receive files on Windows when using Onedrive

### ISSUE THREAD

**Issue by Mahas1** [tailscale/tailscale#6776]
### What is the issue?

Taildrop doesn't save received files in Windows. 
[Documentation](https://tailscale.com/kb/1106/taildrop/?tab=windows#receiving-files-with-taildrop) says the files will be in my `C:\users\mahas\desktop` folder. However, since I use onedrive, my desktop folder is in `C:\users\mahas\onedrive\desktop` and the former folder doesn't exist.
```
PowerShell 7.3.1
PS C:\Users\mahas> ls c:/users/mahas/desktop
Get-ChildItem: Cannot find path 'C:\users\mahas\desktop' because it does not exist.
PS C:\Users\mahas>
```
![image](https://user-images.githubusercontent.com/82939599/208254054-59c2310b-02b5-4348-aad5-53de96999d01.png)

I am suspecting that Onedrive might be the cause for this issue, but I'm not 100% sure.

### Steps to reproduce

1. Turn on Onedrive sync
2. Share file from Android to Windows 
3. File is not received

### OS

Windows

### OS version

Windows 11 build 22621.963

### Tailscale version

1.34.1

### Bug report

BUG-6f0ae741c385bc4c186023fc04928790ed70e35e8688576b75c8807f5db12211-20221217173136Z-a63587003b00a5c0

**Comment by DentonGentry** [comment]
We missed updating that documentation: starting in 1.34, files are written to the Windows Downloads folder. Do they appear there?

**Comment by Mahas1** [comment]
Yup, they appear there. Thanks for clarifying.

Suggestion: in a future release maybe, could you add support for choosing the destination folder?
