### ISSUE TITLE
Illegal instruction on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by andreimatei** [tailscale/tailscale#6778]
### What is the issue?

`tailscale ssh` crashes every time on RPI Zero W.

```
tailscale ssh <host>
Illegal instruction
```
Other than `tailscale ssh`, `tailscale` seems to be running fine.

My binary came from: `tailscale_1.34.1_armhf.deb`

I think I should get a goroutine dump, but I can't figure out how. FWIW, `strace` shows an address:
```
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x1e79c} ---
```

Details of my machine's architecture.
```
cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 997.08
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 000000006d6af124
Model           : Raspberry Pi Zero W Rev 1.1
```

Possibly the same as #5793 ?

### Steps to reproduce

Run `tailscale ssh <host>`

### OS

Linux

### OS version

Raspbian 10

### Tailscale version

1.34.1

same thing happened with 1.32.

### Bug report

BUG-784ad8c725fc7654bc50ad2ea77b16de906e92aa507978c0996795ae03ae24e9-20221217223357Z-0038e22beb0e28be

**Comment by bradfitz** [comment]
I don't think this is the same. It's in a different process (tailscale vs tailscaled).

Does normal "ssh" work on that Pi? Because `tailscale ssh` doesn't do much more than just run the ssh binary.

**Comment by andreimatei** [comment]
You're right; `ssh` itself is crashing with `Illegal instruction`. Seems bizarre, since `ssh` is coming from Raspbian's package.
Sorry for the noise; closing.
