### ISSUE TITLE
Synology Cannot Start outbound on DS418

### ISSUE THREAD

**Issue by kjohnson044** [tailscale/tailscale#6779]
Hello I have spent the last couple of days trying to figure out my issue with a remote DS418 (currently not remote). I had Tailscale installed previously and working properly. I updated it and everything fell apart on this NAS, works fine on my DS920+. However the latest Package Center version (1.30.2-300027) seems to have broken for my DS418. I am able to install it and authenticate my NAS, but when I follow the instructions for outbound connections everything fall apart and the NAS is no longer connected. When I click "Run" then "Open", it says "Sorry, the page you are looking for is not found" and when I return to the Package Center it is "Manually Stopped". I have tried restarting my NAS and that does not help. I have tried uninstalling and installing the application and it still does not work. I have tried installing the non Package Center version (1.34.1-340017) and it still does not work. I have reset my NAS, reinstalled, done the above and it does not work. The version prior to what was released around 12/12 on the package center was stable for my DS418. Any help would be greatly appreciated.

**Comment by lkroeker** [comment]
I have a similar issue.  I had it set up and working with Hyper Backup for a few weeks, and after updating to the latest release (1.30.2-300027) it appears to have broken something.  Restarting both my local and the remote units didn't help.  Hopefully we can get a patch soon!  I'm not sure where to begin with troubleshooting this.

**Comment by DentonGentry** [comment]
In https://github.com/tailscale/tailscale/issues/5793 we've been investigating an illegal instruction error occurring on some Synology devices. We have not narrowed down exactly what the factors are in seeing it, but it might be what is happening on your device.

We've yet to make it happen on any Synology device we have here. For example I have a DS218 running `DSM 7.1.1-42962 Update 1`, which uses the same quad core Realtek RTD1296 as is used in the DS418, and I don't see any problem.

I'd suggest subscribing to https://github.com/tailscale/tailscale/issues/5793 for updates.

**Comment by lkroeker** [comment]
> In #5793 we've been investigating an illegal instruction error occurring on some Synology devices. We have not narrowed down exactly what the factors are in seeing it, but it might be what is happening on your device.
> 
> We've yet to make it happen on any Synology device we have here. For example I have a DS218 running `DSM 7.1.1-42962 Update 1`, which uses the same quad core Realtek RTD1296 as is used in the DS418, and I don't see any problem.
> 
> I'd suggest subscribing to #5793 for updates.

I don't see any obvious crashing from the UI, but I haven't tried to look in the logs yet.  I'm trying to push a backup from a DS918+ to a DS220J (7.1-42661 on both).   I can ping the DS220J from my android phone running TS.

**Comment by bradfitz** [comment]
Dup of #5793

**Comment by kjohnson044** [comment]
Thanks all I will give that thread a proper read and try. Wish my Google searching has been a bit better.
