### ISSUE TITLE
build: build tailscale/go toolchain with fixed Ubuntu release

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6799]
Our tailscale/go repo builds with `ubuntu-latest`:

https://github.com/tailscale/go/blob/e6ce5b50036022c91783161890eabecfddc5ae79/.github/workflows/build.yml#L18

But GitHub just changed "latest":

https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

And one of our builders has an OS image with an older libc so we get a build failure:

```
/home/ubuntu/.cache/tailscale-go/bin/go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/ubuntu/.cache/tailscale-go/bin/go)
/home/ubuntu/.cache/tailscale-go/bin/go: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/ubuntu/.cache/tailscale-go/bin/go)
```

We should use a specific (and old) version of Ubuntu to build tailscale/go for now.

/cc @maisem @jwhited @DentonGentry @andrew-d @dsnet

**Comment by DentonGentry** [comment]
I can't tell if there is more to do for this.

**Comment by danderson** [comment]
Should be unnecessary now, I think. We switched to a statically linked Go toolchain, so libc incompatibilities should no longer be an issue.
