### ISSUE TITLE
wgengine/netstack: support GSO in netstack mode

### ISSUE THREAD

**Issue by jwhited** [tailscale/tailscale#6816]
outbound path:
https://github.com/tailscale/tailscale/blob/8aac77aa191878495a1539da28180a3756c2d30d/wgengine/netstack/netstack.go#L164
https://github.com/tailscale/tailscale/blob/8aac77aa191878495a1539da28180a3756c2d30d/wgengine/netstack/netstack.go#L453
https://github.com/google/gvisor/blob/846276b3dbc5/pkg/tcpip/link/channel/channel.go#L142
https://github.com/google/gvisor/blob/846276b3dbc52dcb35587df8fa996e46adb4823e/pkg/tcpip/stack/registration.go#L1350

inbound path:
https://github.com/tailscale/tailscale/blob/8aac77aa191878495a1539da28180a3756c2d30d/net/tstun/wrap.go#L736
https://github.com/tailscale/tailscale/blob/8aac77aa191878495a1539da28180a3756c2d30d/net/tstun/wrap.go#L718
https://github.com/tailscale/tailscale/blob/8aac77aa191878495a1539da28180a3756c2d30d/wgengine/netstack/netstack.go#L699

cc @raggi

**Comment by ignoramous** [comment]
Believe Netstack can plumb inbound ([TCP GRO](https://github.com/google/gvisor/blob/5ba35f516b5cf4065d14f9276d0feaf9ce4d97e2/pkg/tcpip/stack/nic.go#L755)) and outbound ([TCP GSO](https://github.com/google/gvisor/blob/5ba35f516b5cf4065d14f9276d0feaf9ce4d97e2/pkg/tcpip/stack/registration.go#L1332)) already (requires `LinkEndpoint` to support "hardware" GSO ([ex](https://github.com/google/gvisor/blob/5ba35f516b5cf4065d14f9276d0feaf9ce4d97e2/pkg/tcpip/link/fdbased/endpoint.go#L551)), but "Software" GSO seems like it might work as-is).

**Comment by jwhited** [comment]
gVisor GSO & GRO have been enabled/implemented for Linux across the following commits:

https://github.com/tailscale/tailscale/commit/df6014f1d7bf437adf239b75a62fd4c2f389ea2a
https://github.com/tailscale/tailscale/commit/7bc2ddaedc2ac5965f02a76453147e23d58687bd

The framework is now in place for other platforms to use. Windows support is being tracked in tailscale/corp#21874
