### ISSUE TITLE
UPnP support

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#682]
We should support UPnP. This is a dumping ground of notes for how to speak UPnP right.

- Send UDP SSDP discovery request to :1900 on the default gateway. One of the responses will be for ServiceType `urn:schemas-upnp-org:device:InternetGatewayDevice:1` and will point to the service description URL, e.g. http://192.168.1.1:5000/Public_UPNP_gatedesc.xml .
- Read service description XML. Look for either WANIPConnection (preferentially) or WANPPPConnection (fallback, older devices). Remember its service type and control URL.
- Things you should technically do, to verify that the gateway actually has an internet connection - but you can also just skip that and handle errors in portmap requests.
  - Hit the Connection's control URL with a GetStatus SOAP request. Proceed with port mapping if state==1 (IGD connected). state==2 (not connected) or 3 (unknown) will error out if you ask for a port mapping (maybe just try anyway and handle the error instead of discovering conn status?)
  - Hit the Connection's control URL with a GetExternalIP request. If no external IP is returned, don't ask for a port mapping.
- Hit the Connection's control URL with a AddAnyPortMapping request, with params that are either the port we would like, or the port we were last allocated, and some short-ish lease. We'll get back a public ip:port, which we should feed to control.
  - AddAnyPortMapping is only in UPnP IGD 2.0. If it's not present (we can check the WAN{PPP,IP}Connection schema URL to find out), we have to use AddPortMapping instead. We have to pick random ports and repeatedly ask until we find a free one, unlike AddAnyPortMapping which will pick a free port if the one we request is infeasible.
- Keep hitting the Connection with GetListOfPortMappings, to check that our portmap is still there, and eagerly refresh ahead of schedule if it vanishes (e.g. gateway reboots).
  - Technically I think we can also subscribe to multicast announcements to discover state changes, but ugh multicast, ugh HTTP over UDP, etc. Given that active discovery will fall back on failure, a periodic re-query seems better? Need to balance mapping correctness with battery usage on phone.
- Refresh the mapping with AddAnyPortMapping/AddPortMapping as needed before the lease expires. UPnP suggests a 1h lease time, but in this age of very mobile devices that roam networks, something shorter feels more polite?...
- Handle errors gracefully - AFAICT there are no errors that we should consider permanent, as the admin may reconfigure the gateway at any point to make things succeed. We should instead continue retrying with increasing backoff, and just let wgengine/magicsock/ipn et al. know when we've discovered a new potential endpoint for ourselves.

All the above is full on SOAP and XML goop, but aside from having to walk from the SSDP request to find out what the control URL is, it's all pretty boilerplate and we can probably get away with fmt.Sprintf for writing, and some basic encoding/xml stuff for reading.

**Comment by danderson** [comment]
Quick research: a random consumer gateway purchased this year only support UPnP IGD 1.0, meaning empirically we can't expect AddAnyPortMapping to exist everywhere, we do actually have to implement the fallback where we try to map ports at random until something works.

Given that, there's also the risk that these older UPnP devices will fail anyway, because some early implementations apparently rejected requests where WANPort != LANPort, so we can only map 41641 to 41641 on the internet, and nothing else. Bah. Oh well, that'll be handled by the backoff/retry logic.

**Comment by vielmetti** [comment]
The little media player I found (miniDLNA) that works pretty well expects to use UPnP to stream music, so that might be a good test case for this feature.

(I'm willing to try some other music streaming system if there's a better way, but it seems like this is a good testbed).

**Comment by bradfitz** [comment]
I removed this from the 1.6.0 project, considering the freeze. Also, PMP made its way in anyway, so that takes some pressure off this. (But it'd still be a nice win numbers-wise.)
