### ISSUE TITLE
Android: broken Chinese characters with shared devices 

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#6824]
### What is the issue?

When a device from a user with Chinese characters is shared, Android doesn't know how to display those characters, instead showing as "☒"

![Screenshot_20221221-152128](https://user-images.githubusercontent.com/110842475/208976366-8572ca1b-03e3-4e08-a513-a2e68705c0cd.jpg)

### OS

Android

**Comment by bradfitz** [comment]
Hey @eliasnaur, is this a known issue? (or something that's since been fixed and we're using something old?)

**Comment by eliasnaur** [comment]
Indeed, font fallback has been implemented in recent Gio versions.

**Comment by DentonGentry** [comment]
Tailscale 1.37.108 contains the Gio `HEAD` as of 11 Feb 2023, which should resolve this. Please reopen if not.
