### ISSUE TITLE
Funnel cannot be turned on

### ISSUE THREAD

**Issue by sterbeN27** [tailscale/tailscale#6827]
### What is the issue?

I tried to turn on Funnel on my tailscale network but I stuck at turning on the Funnel. I have followed all the steps from:
https://tailscale.com/kb/1223/tailscale-funnel/

When I tried to run `tailscale serve funnel on` it gave me this error message:
`Funnel not available; "funnel" node attribute not set. See https://tailscale.com/kb/1223/tailscale-funnel/.`

I had put 
```
"nodeAttrs": [
    {
        "target": ["autogroup:members"],
	"attr":   ["funnel"],
    },
],
```
![image](https://user-images.githubusercontent.com/57295193/209078160-3d8ff9f3-d656-4489-bd16-523502be2590.png)
in my Access Control config file.

I suspect it can't detect the Access Control config file changes.

### OS

Linux

### Tailscale version

1.34.1

**Comment by bradfitz** [comment]
Sure you're in the right tailnet? You didn't include a "tailscale bugreport" so it's hard to help debug.

**Comment by wksantiago** [comment]
Having the same exact issue

**Comment by sterbeN27** [comment]
> Sure you're in the right tailnet? You didn't include a "tailscale bugreport" so it's hard to help debug.

Hi, thanks for the response.

Yes, I'm in the right tailnet and sorry for not including a `tailscale bugreport`.

**Update**: After tried a lot of things, it works by changing the target using `tag` instead of `autogroup` so it looks like this:
```
"nodeAttrs": [
    {
        "target": ["tag:user"],
	"attr":   ["funnel"],
    },
],
```

**Note**: I found a few typos in Funnel documentation (`NodeAttrs` and `nodeAttrs`) which might confused others. Maybr you can fix it later.

Thanks

**Comment by bradfitz** [comment]
cc @shayne @WalterHub to file bugs elsewhere as needed.

**Comment by wksantiago** [comment]
> You also didn't include a `tailscale bugreport`, though, @wksantiago :)

sorry
BUG-9a993b845e26de616b1dbe5805bb04b23538095935a8fb3e5297120c6b0c9a6f-20221223005838Z-f6d444112add5d5b

**Comment by shayne** [comment]
We'll take a look at the documentation, thanks!

I am pretty sure that having `"target": "autogroup:members"` `didn't work because you were trying a tagged node. When you tag a node, it acquires a different set of network permissions than the user account and is no longer a part of the user's devices from a security perspective.

We have more information on ACLs and [specifically tags ](https://tailscale.com/kb/1068/acl-tags/#authentication-and-authorization) as well as [autogroups ](https://tailscale.com/kb/1018/acls/#autogroups) in our knowledge base.

**Comment by sterbeN27** [comment]
> We'll take a look at the documentation, thanks!
> 
> I am pretty sure that having `"target": "autogroup:members"` `didn't work because you were trying a tagged node. When you tag a node, it acquires a different set of network permissions than the user account and is no longer a part of the user's devices from a security perspective.
> 
> We have more information on ACLs and [specifically tags ](https://tailscale.com/kb/1068/acl-tags/#authentication-and-authorization) as well as [autogroups ](https://tailscale.com/kb/1018/acls/#autogroups) in our knowledge base.

I see. I tried creating a new account without any tagged nodes also cannot run. I think it's better to mention this `target` attribute details at documentation there to guide future users. Thanks
