### ISSUE TITLE
Cannot restore Tailscale connection after using another VPN on iOS

### ISSUE THREAD

**Issue by kharitonovAL** [tailscale/tailscale#6829]
### What is the issue?

Hi there!

I’m using Tailscale on iOS. But some times I need to switch to another VPN (WireGuard air OpenVPN). And if I open another VPN app and turn in on, then stop it and back to Tailscale, the connection to my mesh won’t be restored. The only thing that helps is delete the Tailscale VPN profile in iOS settings, then open Tailscale app again, tap Get started and allow to add the profile again.

### Steps to reproduce

- Open Tailscale and connect to network.
- (Optional) stop Tailscale connection in app.
- Open another VPN app and enable connection.
- (Optional) stop another VPN connection.
- Open the Tailscale app - there will be loading indicator, connection switch doesn’t work, reauthenticating doesn’t work.
- Open VPN seating in iOS Settings app and delete Tailscale profile.
- Swipe off the Tailscale app from memory.
- Open Tailscale app, tap Get started and allow to add VPN profile.
- Connect to Tailscale network.

### Are there any recent changes that introduced the issue?

No

### OS

iOS

### OS version

iOS 16.2 (20C65)

### Tailscale version

1.34.1

### Bug report

BUG-08583cb35afc2c51ee7c5f87519d3e06e3ad94c271475d8ba14db95cc042a376-20221222165326Z-08fd0f4fdc346e59

**Comment by DentonGentry** [comment]
Around the time of the bugreport we see Tailscale private IP addresses trying to connect to public IPs. This is an exit node, and appears to have become unreachable somehow (presumably a result of the other VPN app somehow).

```
2022-12-22 16:56:54.120058 +0000 UTC: open-conn-track: timeout opening (TCP 100.124.x.y:54904 => 17.248.x.y:443) to node [koQ7J]; online=yes, lastRecv=9s
2022-12-22 16:56:57.620016 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:50808 => [2a00:1450::q:r:s::t]:443) to node [koQ7J]; online=yes, lastRecv=1s
2022-12-22 16:56:58.136988 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:50809 => [2a01:b740::q:r:s::t]:443) to node [koQ7J]; online=yes, lastRecv=2s
```

**Comment by agottardo** [comment]
@kharitonovAL are you still hitting this on the latest app version, v1.48.1?

**Comment by kharitonovAL** [comment]
> @kharitonovAL are you still hitting this on the latest app version, v1.48.1?

Well, not so strong. You see, I am using now beta version of Tailscale from TestFlight, and now I just trying to Reconnect few times, and on the third or fourth try it connects.

And did you solve battery drain issue?

**Comment by kharitonovAL** [comment]
Hey! Did someone fixed this?

**Comment by agottardo** [comment]
See https://tailscale.com/kb/1105/other-vpns. 

The best way to know is to test this again yourself, are you still hitting the problem? We made a lot of changes since August 2023 when you last updated this issue.

**Comment by kharitonovAL** [comment]
Tested, working. Thanks!

**Comment by hgain** [comment]
The issue is still reproducible. Tested with Tailscale 1.72.2 und Surfshark 3.20.0.
Can other users confirm this?
