### ISSUE TITLE
DNS Support breaks resolving for SNAP on Ubuntu

### ISSUE THREAD

**Issue by xXorAa** [tailscale/tailscale#683]
Replacing /etc/resolv.conf with a tailscale specific version breaks any snaps on Ubuntu as the tailscale version of the resolv.conf file is not allowed to be accessed inside the snap.

A better way to do this if systemd-resolvd is running is to use resolvectl to add/remove the DNS domains/servers like the following.

resolvectl dns tailscale0 XX.XX.XX.XX
resolvectl domain tailscale0 example.com

and

resolvectl revert tailscale0

when the interface is taken down again.

**Comment by dshynkev** [comment]
This is part of a more general change that is in progress right now (setting nameservers for specified search domains only and not globally). The reason this depends on that is the following.

It does not seem like systemd-resolved supports forcing the exclusive use of supplied nameservers without changing other interfaces' settings, as the interface with the default route (say `eth0`) will always receive the "DNS default route". It will be considered during the resolution of all DNS queries. If we also set the DNS default route on `tailscale0`, then we will be _another_ interface considered, but we cannot require than we be the _only_ such interface without modifying the configuration of `eth0`. As a result, if another interface's responds first, their response will be used. Also, the very fact that DNS queries leak can be undesirable for privacy reasons.

All other Linux DNS modes support setting nameservers globally (i.e. to be used for all DNS queries). In some modes that is the only option, such as when none of {systemd-resolved, NetworkManager, resolvconf} is in use and we must overwrite `/etc/resolv.conf`. The option to enforce this should probably remain, but an option to relax this requirement, which would allow the use of `systemd-resolved`, is definitely desirable and is being worked on.

**Comment by joonas-fi** [comment]
I'm hitting this as well. After installing Tailscale and configuring magic DNS, I was left scratching my head why Firefox and other internet-using software works, but Brave and Spotify stopped working. (they former two are installed as Snaps)

I fixed it by disabling magic DNS:

```console
$ tailscale up --accept-dns=false
```

It'd be great if before this gets fixed, if there were instructions for using magic DNS and Snaps at the same time :)

**Comment by felicianotech** [comment]
This affects me too. Just an FYI that Chromium on Ubuntu was switched from a .deb install to a snap a few releases ago. So anyone using Chromium on recent Ubuntu versions (including the latest LTS release) will be affected by this as well.

**Comment by danderson** [comment]
Figured out the proximal cause: Snaps do clever things to inject the system's /etc/resolv.conf into the containerized environment... But in most cases with tailscale DNS, /etc/resolv.conf is a symlink to /etc/resolv.tailscale.conf. Snap injects the symlink into the container, but not its target, so /etc/resolv.conf is effectively missing, and all DNS resolution fails.

We'll need to either find a way to tell Snap about additional files to inject, or rework how we take over /etc/resolv.conf.

**Comment by bradfitz** [comment]
Why'd we do the symlink thing originally? I assume we were copying something else already doing? If so, why doesn't that other thing also not break snaps?

**Comment by tdalbo92** [comment]
This may be different enough to warrant a separate issue entirely, but in my situation, the symlink is causing issues with Plex Media Server's snap apparmor profiles.  Apparmor is throwing DENIED when Plex tries to open the file.  It's following the symlink just fine though.

I can temporarily work around this by adding this in `/var/lib/snapd/apparmor/profiles/snap.plexmediaserver.plexmediaserver`
`/etc/resolv.tailscale.conf r,`

But at some point that file gets refreshed/rewritten by Snap and stuff starts breaking again.

**Comment by lightrush** [comment]
I have to disable Tailscale when I want to use Signal. Would be great if I didn't have to.

**Comment by danderson** [comment]
This should be fixed at HEAD, and will roll out in Tailscale 1.8.

**Comment by danderson** [comment]
Correction - one part is fixed, which is that we don't make /etc/resolv.conf a symlink when managing it directly, so sandboxing won't get confused. However, we don't yet work fully correctly with resolved and NetworkManager-based systems due to bugs in the configuration detection. Still working on those, also targeting 1.8.

**Comment by danderson** [comment]
Should now be fixed entirely, and will roll out in Tailscale 1.8. You can test-drive things with the unstable package on linux, or building from source on macOS/windows. We're still working on applying the polish and shipping the split-DNS configuration UI, but specifically snap DNS should work okay now.
