### ISSUE TITLE
UPnP not working for Technicolor CGA4233

### ISSUE THREAD

**Issue by Schokobecher** [tailscale/tailscale#6833]
### What is the issue?

Tailscale is unable to detect that UPnP is available/activated on  a Technicolor CGA4233(DE)

`tailscale netcheck` reports

> Report:
> 	* UDP: true
> 	* IPv4: yes, 77.20.XXX.XXX:39425
> 	* IPv6: no, but OS has support
> 	* MappingVariesByDestIP: false
> 	* HairPinning: false
> 	* PortMapping:
> 	* Nearest DERP: Frankfurt
> 	* DERP latency:
> 		- fra: 23ms    (Frankfurt)
> 		- ams: 27.2ms  (Amsterdam)
> 		- par: 31.1ms  (Paris)
> 		- lhr: 33.2ms  (London)
> 		- mad: 46.6ms  (Madrid)
> 		- waw: 48.2ms  (Warsaw)
> 		- nyc: 112.8ms (New York City)
> 		- tor: 123.9ms (Toronto)
> 		- ord: 124.1ms (Chicago)
> 		- mia: 140.3ms (Miami)
> 		- dfw: 140.7ms (Dallas)
> 		- dbi: 141.5ms (Dubai)
> 		- blr: 165ms   (Bangalore)
> 		- den: 170.5ms (Denver)
> 		- lax: 177.7ms (Los Angeles)
> 		- sfo: 177.7ms (San Francisco)
> 		- sea: 177.8ms (Seattle)
> 		- jnb: 193.3ms (Johannesburg)
> 		- sao: 226.2ms (São Paulo)
> 		- hnl: 231.1ms (Honolulu)
> 		- sin:         (Singapore)
> 		- syd:         (Sydney)
> 		- tok:         (Tokyo)
> 		- hkg:         (Hong Kong)

UPnP is enabled in the web interface, and `upnpc -s` reports no issues:

> upnpc : miniupnpc library test client, version 2.1.
>  (c) 2005-2019 Thomas Bernard.
> Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
> for more information.
> List of UPNP devices found on the network :
>  desc: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml
>  st: urn:schemas-upnp-org:device:InternetGatewayDevice:1
> 
> Found valid IGD : http://192.168.0.1:49152/upnp/control/WANIPConnection0
> Local LAN ip address : 192.168.0.5
> Connection Type : IP_Routed
> Status : Connected, uptime=0s, LastConnectionError : ERROR_NONE
> MaxBitRateDown : 100000000 bps (100.0 Mbps)   MaxBitRateUp 100000000 bps (100.0 Mbps)
> ExternalIPAddress = 77.20.XXX.XXX
> Bytes:   Sent: 654918750	Recv: 2147483647
> Packets: Sent:  7036526	Recv: 52617461

According to `nmap 192.168.0.1` the router does not use port **1900** but **49152**:

> PORT      STATE    SERVICE
> 22/tcp    filtered ssh
> 23/tcp    filtered telnet
> 53/tcp    open     domain
> 80/tcp    open     http
> 111/tcp   filtered rpcbind
> 443/tcp   filtered https
> 1026/tcp  filtered LSA-or-nterm
> 1027/tcp  filtered IIS
> 1028/tcp  filtered unknown
> 1029/tcp  filtered ms-lsa
> 2222/tcp  filtered EtherNetIP-1
> 9000/tcp  filtered cslistener
> 49152/tcp open     unknown

I've captured SSDP packets using `tcpdump -vv -A -s 0 'host 239.255.255.250 and udp' -i any -w CGA4233.pcap`
while doing `tailscale netcheck`, and `upnpc -s`, `upnpc -l`
[CGA4233.pcap.zip](https://github.com/tailscale/tailscale/files/10295048/CGA4233.pcap.zip)

Happy to do more tests :)

### Steps to reproduce

1. Enable UPnP for LAN clients in the web interface
2. Check with `tailscale netcheck`

### Are there any recent changes that introduced the issue?

None

### OS

Linux

### OS version

Ubuntu 20.04.5 LTS

### Tailscale version

1.32.3

### Bug report

N/A - due to different control server

**Comment by DentonGentry** [comment]
> 49152/tcp open unknown

I can see how port 49152 would be used for the actual UPnP operations, but there should be a UDP port for SSDP discovery packets. The pcap only shows packets being sent to UDP port 1900, and doesn't show any responses coming back. When you run `upnpc -s`, what do the responses back from the CGA4233 look like.

--------

Some notes:
+ According to https://www.technicolor.com/sites/default/files/medialib/document/Downloads/CGA4233%20v1.0%20OSS%20Publication.pdf, CGA4233 uses miniupnp 1.8.

**Comment by Schokobecher** [comment]
This is what I get (filtered with `(udp contains "HTTP/1.1")` from all UDP traffic of the node)
[CGA4233_Response.pcapng.zip](https://github.com/tailscale/tailscale/files/10295959/CGA4233_Response.pcapng.zip)

Is that correct? Only done a few packet captures before tbh...

**Comment by andrew-d** [comment]
@Schokobecher - If you're able to install an unstable build, 1.37.221 and later contain a variety of fixes for UPnP; would it be possible to test and see if one of those fixes works for you? I believe that the specific fix in your case is https://github.com/tailscale/tailscale/pull/7459, since your packet capture shows that the UPnP response is coming from a port other than the 1900 UPnP port.
https://pkgs.tailscale.com/unstable/

**Comment by Schokobecher** [comment]
@andrew-d I installed 1.37.241, and it seems to work:

> Setting up tailscale (1.37.241) ...
> tailscale netcheck
> 2023/03/08 22:32:00 portmap: UPnP discovery response from non-UPnP port 37565
> 2023/03/08 22:32:00 portmap: [v1] UPnP reply {Location:http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml Server:Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22 USN:uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 08 Mar 2023 22:32:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: b02d6f88-b0b2-11ed-b996-ff455aed3043\r\nSERVER: Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22\r\nX-User-Agent: redsonic\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
> 2023/03/08 22:32:00 portmap: UPnP meta changed: {Location:http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml Server:Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22 USN:uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1}
> 2023/03/08 22:32:00 portmap: UPnP discovery response from non-UPnP port 55693
> 2023/03/08 22:32:00 portmap: [v1] UPnP reply {Location:http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml Server:Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22 USN:uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 08 Mar 2023 22:32:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: b02d6f88-b0b2-11ed-b996-ff455aed3043\r\nSERVER: Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22\r\nX-User-Agent: redsonic\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
> 2023/03/08 22:32:00 portmap: UPnP discovery response from non-UPnP port 34890
> 2023/03/08 22:32:00 portmap: [v1] UPnP reply {Location:http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml Server:Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22 USN:uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 08 Mar 2023 22:32:00 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:49152/IGDdevicedesc_brlan0.xml\r\nOPT: \"http://schemas.upnp.org/upnp/1/0/\"; ns=01\r\n01-NLS: b02d6f88-b0b2-11ed-b996-ff455aed3043\r\nSERVER: Linux/4.9.135-Prod_19.3, UPnP/1.0, Portable SDK for UPnP devices/1.6.22\r\nX-User-Agent: redsonic\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:ebf5a0a0-1dd1-11b2-a90f-021018f320f4::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
> 
> Report:
> 	*** UDP: true**
> 	* IPv4: yes, 77.20.95.21:35997
> 	* IPv6: no, but OS has support
> 	* MappingVariesByDestIP: false
> 	* HairPinning: false
> 	* PortMapping: UPnP
> 	* Nearest DERP: Frankfurt
> 	* DERP latency:
> 		- fra: 22.9ms  (Frankfurt)
> 		- ams: 24.6ms  (Amsterdam)
> 		- par: 29.6ms  (Paris)
> 		- lhr: 35.7ms  (London)
> 		- mad: 41.1ms  (Madrid)
> 		- waw: 42.5ms  (Warsaw)
> 		- nyc: 102.4ms (New York City)
> 		- ord: 117.2ms (Chicago)
> 		- tor: 117.3ms (Toronto)
> 		- mia: 129.6ms (Miami)
> 		- dbi: 133.2ms (Dubai)
> 		- dfw: 140.7ms (Dallas)
> 		- blr: 162.4ms (Bangalore)
> 		- den: 169.2ms (Denver)
> 		- lax: 173.2ms (Los Angeles)
> 		- sfo: 174.1ms (San Francisco)
> 		- sea: 176.9ms (Seattle)
> 		- jnb: 188.9ms (Johannesburg)
> 		- hnl: 212ms   (Honolulu)
> 		- tok: 221.9ms (Tokyo)
> 		- sin:         (Singapore)
> 		- syd:         (Sydney)
> 		- sao:         (São Paulo)
> 		- hkg:         (Hong Kong)

**Comment by andrew-d** [comment]
Great, thanks for confirming!
