### ISSUE TITLE
DNS issues with Pi zero 

### ISSUE THREAD

**Issue by slvrscoobie** [tailscale/tailscale#6839]
### What is the issue?

Tailscale works for a few days but always ends up killing the DNS of my remote Pi device. 
Ive been using the Tailscale  up -accept-dns=false but it still seems to have issues with dns resolution 
I can SSH into the device so I know the network is up, but resolve.conf is not found, and I can't even create it. 
I can't ping any dns required device as it says ping: google.com: Temporary failure in name resolution
I tried to edit / create the resolv.conf but it now refuses.

sudo sh -c 'echo "nameserver 8.8.8.8" >> /etc/resolv.conf'
sh: 1: cannot create /etc/resolv.conf: Directory nonexistent

### Steps to reproduce

install Tailscale and wait a couple days. 

### Are there any recent changes that introduced the issue?

none 

### OS version

Raspberry Bullseye

### Tailscale version

1.34.1

### Bug report

BUG-f27cb03bee654a2a37ef4aa70ca4817f4c44b391785ad82ced1621483a11dcbd-20221224023917Z-5f81a81669c74492

**Comment by DentonGentry** [comment]
```
sudo sh -c 'echo "nameserver 8.8.8.8" >> /etc/resolv.conf'
sh: 1: cannot create /etc/resolv.conf: Directory nonexistent
```

`/etc` not existing looks more like filesystem corruption than anything about tailscaled.

**Comment by slvrscoobie** [comment]
cd /etc/ is there
/etc $ ls
adduser.conf            group            mkshrc            rpc
alternatives            group-           modprobe.d        rpi-issue
apparmor.d              gshadow          modules           rsyslog.conf
apt                     gshadow-         modules-load.d    rsyslog.d
avahi                   gss              motd              runit
bash.bashrc             host.conf        mtab              security
bash_completion         hostname         nanorc            selinux
bash_completion.d       hosts            netconfig         services
bindresvport.blacklist  hosts.allow      network           shadow
binfmt.d                hosts.deny       networks          shadow-
bluetooth               idmapd.conf      nftables.conf     shells
ca-certificates         ifplugd          nsswitch.conf     skel
ca-certificates.conf    init             opt               ssh
cifs-utils              init.d           os-release        ssl
collectd                initramfs-tools  pam.conf          subgid
console-setup           inputrc          pam.d             subuid
cron.d                  insserv.conf.d   passwd            sudo.conf
cron.daily              iproute2         passwd-           sudoers
cron.hourly             issue            paxctld.conf      sudoers.d
cron.monthly            issue.net        perl              sudo_logsrvd.conf
crontab                 kernel           piaware.conf      sv
cron.weekly             ld.so.cache      pip.conf          sysctl.conf
dbus-1                  ld.so.conf       polkit-1          sysctl.d
debconf.conf            ld.so.conf.d     ppp               systemd
debian_version          ld.so.preload    profile           terminfo
default                 libaudit.conf    profile.d         timezone
deluser.conf            libblockdev      protocols         tmpfiles.d
dhcp                    libnl-3          python3           triggerhappy
dhcpcd.conf             lighttpd         python3.9         ucf.conf
dnsmasq.conf            locale.alias     rc0.d             udev
dphys-swapfile          locale.gen       rc1.d             udisks2
dpkg                    localtime        rc2.d             ufw
e2scrub.conf            logcheck         rc3.d             unbound
environment             login.defs       rc4.d             update-motd.d
ethertypes              logrotate.conf   rc5.d             usb_modeswitch.conf
fake-hwclock.data       logrotate.d      rc6.d             usb_modeswitch.d
fb.modes                machine-id       rc.local          vim
fonts                   magic            rcS.d             wgetrc
fr24feed.ini            magic.mime       request-key.conf  wpa_supplicant
fstab                   mailcap          request-key.d     X11
fuse.conf               mailcap.order    resolv.conf       xattr.conf
gai.conf                manpath.config   resolv.conf.bak   xdg
gdb                     mime.types       resolvconf.conf
groff                   mke2fs.conf      rmt
Its just resolv.conf is not there
I recall Tailscale re-writes that file to 'take over' the DNS to make it work

**Comment by bradfitz** [comment]
Tailscaled on your device noted upon startup that the /etc/resolv.conf file didn't even exit:

```
2022-12-23 19:01:48.413776165 +0000 UTC: dns: [rc=missing ret=direct]
2022-12-23 19:01:48.41432153 +0000 UTC: dns: using "direct" mode
2022-12-23 19:01:48.414859082 +0000 UTC: dns: using *dns.directManager
```

You turned off `--accept-dns` at:

```
2022-12-19 13:59:20.544249362 +0000 UTC: EditPrefs: MaskedPrefs{CorpDNS=false WantRunning=true}
```

But even after that point, I still see DNS errors because something is querying 100.100.100.100 and it can't resolve:

```
2022-12-20 20:56:07.498295596 +0000 UTC: dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2022-12-20 20:56:12.503873186 +0000 UTC: dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2022-12-20 20:56:17.507849467 +0000 UTC: dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2022-12-20 20:56:34.558836487 +0000 UTC: dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2022-12-20 20:56:39.563217755 +0000 UTC: dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
```

Do you have something configured to point to 100.100.100.100?

I recommend you:

* stop tailscaled
* configure your /etc/resolv.conf to something (making sure the file exists). Ideally use systemd-resolved, which is the only good Linux DNS manager
* start tailscaled.service

**Comment by slvrscoobie** [comment]
Do you have something configured to point to 100.100.100.100?
nothing that I have set up - its a basic Pi install with Flightaware installed on it remotely. 
when I try to edit /etc/resolv.conf I get [ Error writing /etc/resolv.conf: No such file or directory ]

**Comment by bradfitz** [comment]
Sounds like your Pi is kinda screwed up and like @DentonGentry says, sounds like you don't have an `/etc` directory.

What does `ls -l /` say?

**Comment by slvrscoobie** [comment]
total 8
-rw-r--r-- 1 pi pi 6564 Mar 11  2022 piaware-repository_7.2_all.deb
is that what you're asking for?

**Comment by bradfitz** [comment]
> total 8
> -rw-r--r-- 1 pi pi 6564 Mar 11 2022 piaware-repository_7.2_all.deb
> is that what you're asking for?

If you only have one file, a deb, in your root directory, then your Pi's even more screwed up than I imagined.

I'm afraid fixing that is outside of the scope of this forum. This really isn't a Tailscale question. Personally, I would nuke it and start over.

The fact that Tailscale is able to operate at all in that environment is actually impressive!

**Comment by slvrscoobie** [comment]
flightaware, and flightradar24 are also still running and its rebooting without issue other than this DNS issue so im not sure what's up

**Comment by slvrscoobie** [comment]
Well until I can get there to fix it, I used my exit node to re-fix my DNS issues lol

**Comment by slvrscoobie** [comment]
so I guess I didn't do the ls -l properly. 
I did a cd first, then did ls -l and 
pi@raspberry:~ $ ls -l
total 9996
drwxr-xr-x  2 pi   pi      4096 Jul  4 14:53 Bookshelf
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Desktop
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Documents
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Downloads
drwxr-xr-x 15 root root    4096 Jul  4 15:40 dump1090
-rw-r--r--  1 pi   pi   3778128 Aug 10  2020 fr24feed_1.0.25-3_i386.deb
-rw-r--r--  1 pi   pi      1515 Jul  4 15:38 install-dump1090-fa.sh
-rw-r--r--  1 pi   pi      3156 Jul  4 15:46 install-piaware.sh
-rw-r--r--  1 pi   pi      3164 Jul  4 15:46 install-piaware.sh.1
-rw-r--r--  1 pi   pi      1155 Jul  4 15:18 install-piaware-web.sh
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Music
-rw-r--r--  1 pi   pi   1566910 Feb 23  2021 pfclient_5.0.161_armhf.deb
-rw-r--r--  1 pi   pi   1583924 Feb 25  2021 pfclient_5.0.161_i386.deb
-rw-r--r--  1 pi   pi   1583924 Feb 25  2021 pfclient_5.0.161_i386.deb.1
-rw-r--r--  1 pi   pi   1646274 Mar 29  2021 pfclient_5.0.162_amd64.deb
drwxr-xr-x  8 root root    4096 Jul  4 15:53 piaware_builder
drwxr-xr-x  7 root root    4096 Jul  4 15:20 piaware-web
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Pictures
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Public
drwxr-xr-x  6 root root    4096 Jul  4 15:49 tcltls-rebuild
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Templates
drwxr-xr-x  2 pi   pi      4096 Jul  4 15:08 Videos

**Comment by slvrscoobie** [comment]
@bradfitz 
Needed to cd / 
Files are there, its not ‘screwed up’
Thanks
pi@raspberrypi:~ $ cd /
pi@raspberrypi:/ $ ls -l
total 60
lrwxrwxrwx   1 root root     7 Apr  4  2022 bin -> usr/bin
drwxr-xr-x   5 root root  4096 Dec 31  1969 boot
drwxr-xr-x  15 root root  3380 Dec 23 22:16 dev
drwxr-xr-x  83 root root  4096 Dec 28 09:10 etc
drwxr-xr-x   3 root root  4096 Apr  4  2022 home
lrwxrwxrwx   1 root root     7 Apr  4  2022 lib -> usr/lib
drwx------   2 root root 16384 Apr  4  2022 lost+found
drwxr-xr-x   2 root root  4096 Apr  4  2022 media
drwxr-xr-x   2 root root  4096 Apr  4  2022 mnt
drwxr-xr-x   2 root root  4096 Apr  4  2022 opt
dr-xr-xr-x 179 root root     0 Dec 31  1969 proc
drwx------   3 root root  4096 May 16  2022 root
drwxr-xr-x  36 root root  1040 Dec 28 23:25 run
lrwxrwxrwx   1 root root     8 Apr  4  2022 sbin -> usr/sbin
drwxr-xr-x   2 root root  4096 Apr  4  2022 srv
dr-xr-xr-x  12 root root     0 Dec 31  1969 sys
drwxrwxrwt   9 root root  4096 Dec 28 23:25 tmp
drwxr-xr-x  11 root root  4096 Apr  4  2022 usr
drwxr-xr-x  12 root root  4096 May 16  2022 var

**Comment by DentonGentry** [comment]
Linux filesystems do not require you to cd into the directory before seeing the files. That the files were missing until then is a symptom of a problem.
Best of luck, the previous update sounded like you got something working.
