### ISSUE TITLE
TailScale Docker Exit Node not working with any other TailScale enabled device

### ISSUE THREAD

**Issue by amanjuman** [tailscale/tailscale#6842]
### What is the issue?

Deployed TailScale docker container on Debian 11 server while enabled IPv4 and IPv6 traffic forwarding but Tailscale docker exit node is not working.

Followed this link and having same issue: 

https://forum.tailscale.com/t/tailscale-running-in-a-container-cannot-use-as-an-exit-node/1848/2

https://github.com/tailscale/tailscale/issues/5237

https://www.reddit.com/r/Tailscale/comments/z32d2h/tailscale_container_exit_node_questionissue/

### Steps to reproduce

```
docker pull tailscale/tailscale

docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --privileged tailscale/tailscale tailscaled

docker exec tailscaled tailscale up --accept-dns=false --advertise-exit-node

ip -a

4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:d2:80:40:74 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
7: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 100.105.56.100/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:4843:cd96:6269:3864/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::52b0:4dd4:15f7:c215/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

### OS

Windows

### OS version

Windows 11 x64 22H2

### Tailscale version

1.34.1

### Bug report

BUG-403af15b6800ffc226dcc7a601f74602ba0de98aa1e158b40957045c6b27b78d-20221224093251Z-7f6d64e3f85994ee

**Comment by kiraitachi** [comment]
I'm interested in this, Imm having the same issue, and this has been mentioned several times. Im starting to consider to run a Linux VM only for Tailscale exit node, given that windows Exit Node is not very reliable either.

**Comment by amanjuman** [comment]
> I'm interested in this, Imm having the same issue, and this has been mentioned several times. Im starting to consider to run a Linux VM only for Tailscale exit node, given that windows Exit Node is not very reliable either.

I tried it on Linux Docker and have that issue. Exit node doesn't work on any device.

**Comment by kiraitachi** [comment]
> > I'm interested in this, Imm having the same issue, and this has been mentioned several times. Im starting to consider to run a Linux VM only for Tailscale exit node, given that windows Exit Node is not very reliable either.
> 
> I tried it on Linux Docker and have that issue. Exit node doesn't work on any device.

Native Linux package works without docker for exit nodes. For Windows implementation also works, but its unreliable for too many connections. For Docker, as you pointed I think this just is not an option, but it would be good if Tailscale could openly address it.

**Comment by amanjuman** [comment]
> > > I'm interested in this, Imm having the same issue, and this has been mentioned several times. Im starting to consider to run a Linux VM only for Tailscale exit node, given that windows Exit Node is not very reliable either.
> > 
> > 
> > I tried it on Linux Docker and have that issue. Exit node doesn't work on any device.
> 
> Native Linux package works without docker for exit nodes. For Windows implementation also works, but its unreliable for too many connections. For Docker, as you pointed I think this just is not an option, but it would be good if Tailscale could openly address it.

I have some limitations in that I can't put TailScale directly on VM instead I must put it on Linux Docker and this is where problem started, the Linux exit node doesn't work on any device.

**Comment by aanzolaavila** [comment]
Don't know if it helps, but I had trouble executing it since docker `tailscale` command was expecting the `tailscaled` socket to be at `/var/run/tailscale/tailscaled.sock`, but in docker is it being set to `/tmp/tailscaled.sock` like
```sh
docker exec tailscaled tailscale --socket /tmp/tailscaled.sock up --accept-dns=false --advertise-exit-node
```
And it starts to report the node as an exit note in the tailscale page.

**Comment by amanjuman** [comment]
> docker exec tailscaled tailscale up --accept-dns=false --advertise-exit-node

```
# docker exec tailscaled tailscale --socket /tmp/tailscaled.sock up --accept-dns=false --advertise-exit-node
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 1). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /tmp/tailscaled.sock: connect: no such file or directory
```

**Comment by amanjuman** [comment]
After checking 
`docker exec tailscaled tailscale status`
I got this

100.120.xx.xx   xxx-laptop         xxxx @ windows offline
100.68.xx.xx   xx  xxxx @ linux   idle; offers exit node
100.97.x.xx   xx            xxxx @ linux   idle; offers exit node

```
# Health check:
#     - router: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.8 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.


```
Could be something with Firewall? No ufw or any other firewall.

**Comment by DentonGentry** [comment]
> Could be something with Firewall? No ufw or any other firewall.

`/sbin/ip6tables -t filter -N ts-input --wait` is failing in a way which firewalld is unlikely to explain. Looking into IPv6 in the container is a better way to proceed.

**Comment by DentonGentry** [comment]
> router: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.8 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)

Both of these concern the base container image, which does not have a working iptables.

**Comment by DentonGentry** [comment]
The problem is with the ip6tables in the base container image, I don't see more to be done.
