### ISSUE TITLE
FR:  auto update tailscale client

### ISSUE THREAD

**Issue by bighamx** [tailscale/tailscale#6843]
### What are you trying to do?

update client is not easy when you have so many machines

### How should we solve this?

add feature to update  client software on web admin console with simple click 

### What is the impact of not solving this?

update so much machines' client with RDP manually

**Comment by DentonGentry** [comment]
An autoupdate mechanism for the Windows app is planned, but not implemented yet.

Dup of https://github.com/tailscale/tailscale/issues/755
