### ISSUE TITLE
Change default socket path in containers

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#6849]
The default socket path when running in a container is /tmp/tailscaled.sock, however this differs from the default expected by the tailscale binary (/var/run/tailscale/tailscaled.sock) so users have to pass in the socket explicitly when running tailscale commands inside the container

It would be nice to either teach safesocket about the different default socket path when run inside the container, or to change the default socket path used by tailscaled inside the container to be the standard path on Linux

cc @danderson

**Comment by budius** [comment]
I came to file a new bug report but this does seem to be my problem.
It was working fine on the ':latest' I started some months ago, but since update I only got this message:
```
$ docker exec tailscaled tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 14). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

For reference running `$ docker exec tailscaled tailscale vesion` shows the version, and ping, or accessing the services in the Docker via HTTP using hostname and domain works fine.

**Comment by budius** [comment]
I just found out there's a `--flag` for the binary.
So running things like `docker exec tailscaled tailscale --socket /tmp/tailscaled.sock status` will work.

I agree that probably the best way is to just change the containers to use the same path as the normal binary, but maybe, at the very least better document in https://hub.docker.com/r/tailscale/tailscale that `docker exec tailscaled tailscale status` doesn't really work should be `docker exec tailscaled tailscale --socket /tmp/tailscaled.sock status` instead.

**Comment by guest42069** [comment]
> I just found out there's a `--flag` for the binary. So running things like `docker exec tailscaled tailscale --socket /tmp/tailscaled.sock status` will work.
> 
> I agree that probably the best way is to just change the containers to use the same path as the normal binary, but maybe, at the very least better document in https://hub.docker.com/r/tailscale/tailscale that `docker exec tailscaled tailscale status` doesn't really work should be `docker exec tailscaled tailscale --socket /tmp/tailscaled.sock status` instead.

There also already exists for containers a `TS_SOCKET` environment variable that you can set to create this behaviour, e.g.

```
$ docker run -d tailscale/tailscale
5e4e9769f74b54c3276fba573d1c7451b72559c9a1f52448db41ed04fa504f5c
$ docker exec 5e4e9769f74b tailscale status
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 14). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

$ docker run -d --env TS_SOCKET=/var/run/tailscale/tailscaled.sock tailscale/tailscale
08a4b564f594918385700047be200aa17d7ca5b995d6758ebb0e71d2edb0fd16
$ docker exec 08a4b564f594 tailscale status
Logged out.
Log in at: https://login.tailscale.com/a/8394cec059e
```

Perhaps changing the default in [`containerboot`](https://github.com/tailscale/tailscale/blob/c5ef9103d92b9b0a2932f869db56fbd7344ad417/cmd/containerboot/main.go#L15-L38) would be the simplest approach but setting the environment variable for your containers should also produce the result you're looking for.

**Comment by SergeantSerk** [comment]
Can confirm, previously this was just fine as I ran an exit node on my server using Tailscale container but I had to remake the container with a new image. Now I cannot connect to the Tailscale socket plus my instance comes up as ephemeral (even when I don't want it to).
![image](https://user-images.githubusercontent.com/14278530/220681298-0739027a-5d05-43a3-ad70-4ee30ca88327.png)

**Comment by budius** [comment]
> my instance comes up as ephemeral (even when I don't want it to). ![image](https://user-images.githubusercontent.com/14278530/220681298-0739027a-5d05-43a3-ad70-4ee30ca88327.png)

that was also a pain point for me but I solved it, you have to attach an extra storage to your instance, I found the answer on reddit with a full docker compose if you want to take a look https://www.reddit.com/r/Tailscale/comments/104y6nq/docker_tailscale_and_caddy_with_https_a_love_story/

The key there is the `TS_STATE_DIR`
