### ISSUE TITLE
Add health check for Netskope

### ISSUE THREAD

**Issue by Bursade** [tailscale/tailscale#6851]
### What is the issue?

I tried to log into Tailscale from my Macbook (OS Monterey 12.5.1) via browser but after authenticating with my Google account I received the following error: 

> Error 500
> tailscale-authstate2 cookie does not match

I also tried to log in using the CLI.
I ran the following command:
`sudo tailscale login --authkey=tskey-auth-<my-key> --accept-routes`
And nothing happens. I never got my prompt back.
So, I checked the logs printed to stdout by tailscaled and I found the following error:

> control: LoginInteractive -> regen=true
> control: doLogin(regen=true, hasUrl=false)
> control: Generating a new nodekey.
> control: RegisterReq: onode= node=[Lp7eB] fup=false nks=false
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF

This message is repeated ad infinitum.

I'm not sure how to see what's being posted to https://controlplane.tailscale.com/machine/register to understand why there is an unexpected end of file.

### Steps to reproduce

1 - start the tailscale demon
`sudo $HOME/go/bin/tailscaled
`

2- login using the CLI with a previously generated key
`sudo tailscale login --authkey=tskey-auth-<my-key> --accept-route
`

### Are there any recent changes that introduced the issue?

No, this is the first time I installed Tailscale on my Macbook. I had no issues so far with Tailscale on my Windows 11 computer, my Android phone, my Raspberry Pi and my Linux computer. Every other device is properly connected to the VPN.

### OS

macOS

### OS version

Monterey 12.5.1

### Tailscale version

1.35.0-dev

### Bug report

BUG-fac3deddceb2419e7fe71f8b6aad556afb1b286992e7a70fcafa48294dff4d9e-20221226175110Z-a2110202d4bf1b8e

**Comment by Bursade** [comment]
I also tried using version 1.34.1 of Tailscale but I still have the same error.
This is logged when the demon starts:

> logtail started
> Program starting: v1.34.1-dev-t, Go 1.19.3: []string{"/Users/REDACTED/go/bin/tailscaled"}
> LogID: fac3deddceb2419e7fe71f8b6aad556afb1b286992e7a70fcafa48294dff4d9e
> logpolicy: using system state directory "/Library/Tailscale"
> wgengine.NewUserspaceEngine(tun "utun") ...
> dns: using *dns.darwinConfigurator
> link state: interfaces.State{defaultRoute=en0 ifs={en0:[192.168.0.39/24 fd00:bc3e:71c:661a:1409:83ea:fbfa:22d3/64]} v4=true v6=true}
> magicsock: disco key = d:9d86da1c55d2c75e
> Creating WireGuard device...
> Bringing WireGuard device up...
> Bringing router up...
> external route: up
> Clearing router settings...
> Starting link monitor...
> Engine created.
> pm: using backend prefs for "profile-d062": Prefs{ra=true dns=true want=true Persist{lm=, o=, n=[gK9yw] u="REDACTED"}}
> got LocalBackend in 79ms
> Start
> Backend: logs: be:fac3deddceb2419e7fe71f8b6aad556afb1b286992e7a70fcafa48294dff4d9e fe:
> control: client.Login(false, 0)
> health("overall"): error: not in map poll
> control: doLogin(regen=false, hasUrl=false)
> control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
> control: RegisterReq: onode= node=[gK9yw] fup=false nks=false
> control: creating new noise client
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> control: doLogin(regen=false, hasUrl=false)
> control: RegisterReq: onode= node=[gK9yw] fup=false nks=false
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> control: doLogin(regen=false, hasUrl=false)
> control: RegisterReq: onode= node=[gK9yw] fup=false nks=false
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> control: doLogin(regen=false, hasUrl=false)
> control: RegisterReq: onode= node=[gK9yw] fup=false nks=false
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> control: doLogin(regen=false, hasUrl=false)
> [RATELIMIT] format("control: doLogin(regen=%v, hasUrl=%v)")
> control: RegisterReq: onode= node=[gK9yw] fup=false nks=false
> [RATELIMIT] format("control: RegisterReq: onode=%v node=%v fup=%v nks=%v")
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> [RATELIMIT] format("Received error: %v")
> [RATELIMIT] format("control: doLogin(regen=%v, hasUrl=%v)") (5 dropped)
> control: doLogin(regen=false, hasUrl=false)
> [RATELIMIT] format("control: RegisterReq: onode=%v node=%v fup=%v nks=%v") (5 dropped)
> control: RegisterReq: onode= node=[gK9yw] fup=false nks=false

And when I try to login using the CLI, this is logged by the demon:

> Start
> control: client.Shutdown()
> control: client.Shutdown: inSendStatus=0
> Backend: logs: be:fac3deddceb2419e7fe71f8b6aad556afb1b286992e7a70fcafa48294dff4d9e fe:
> control: mapRoutine: quit
> control: Client.Shutdown done.
> Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
> blockEngineUpdates(true)
> wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
> wgengine: Reconfig: configuring router
> wgengine: Reconfig: configuring DNS
> dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
> dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
> dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
> Start
> control: client.Shutdown()
> control: client.Shutdown: inSendStatus=0
> Backend: logs: be:fac3deddceb2419e7fe71f8b6aad556afb1b286992e7a70fcafa48294dff4d9e fe:
> control: mapRoutine: quit
> control: Client.Shutdown done.
> Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
> blockEngineUpdates(true)
> StartLoginInteractive: url=false
> control: client.Login(false, 2)
> control: LoginInteractive -> regen=true
> control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
> control: Generating a new nodekey.
> control: creating new noise client
> control: LoginInteractive -> regen=true
> control: Generating a new nodekey.
> control: LoginInteractive -> regen=true
> control: Generating a new nodekey.
> control: LoginInteractive -> regen=true
> control: Generating a new nodekey.
> control: LoginInteractive -> regen=true
> [RATELIMIT] format("control: LoginInteractive -> regen=true")
> [RATELIMIT] format("control: doLogin(regen=%v, hasUrl=%v)") (5 dropped)
> control: doLogin(regen=true, hasUrl=false)
> control: Generating a new nodekey.
> [RATELIMIT] format("control: Generating a new nodekey.")
> control: doLogin(regen=true, hasUrl=false)
> [RATELIMIT] format("control: doLogin(regen=%v, hasUrl=%v)")
> [RATELIMIT] format("control: RegisterReq: onode=%v node=%v fup=%v nks=%v") (6 dropped)
> control: RegisterReq: onode= node=[3UDvc] fup=false nks=false
> [RATELIMIT] format("Received error: %v") (6 dropped)
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> control: RegisterReq: onode= node=[FUPvL] fup=false nks=false
> [RATELIMIT] format("control: RegisterReq: onode=%v node=%v fup=%v nks=%v")
> Received error: register request: Post "https://controlplane.tailscale.com/machine/register": unexpected EOF
> [RATELIMIT] format("Received error: %v")
> [RATELIMIT] format("control: LoginInteractive -> regen=true") (5 dropped)
> control: LoginInteractive -> regen=true
> ^Ctailscaled got signal interrupt; shutting down
> control: client.Shutdown()
> control: client.Shutdown: inSendStatus=0
> control: mapRoutine: quit
> control: Client.Shutdown done.
> flushing log.
> logger closing down

**Comment by Bursade** [comment]
> Packet size limits can also cause connection problems on certain types of networks.
> 
> Tailscale uses a MTU of 1280. If there are other interfaces which might send a packets larger than this, those packets might get dropped silently. These can be verified by using tcpdump.
> 
> In order to solve this, we can set the MTU at the LAN level to a lower value, or use MSS (Maxiumum Segment Size) clamping.

I found that in the troubleshooting documentation -> https://tailscale.com/kb/1023/troubleshooting/

How can I set the MTU size for Tailscale to a lower value? It's only mentioned but I couldn't find any explanation on how to do this.

**Comment by DentonGentry** [comment]
The situation described in that doc is about subnet routers. It is saying that on the Ethernet beyond the subnet router, 1500 byte packets can be sent which cannot traverse the 1280 byte MTU of the wireguard tunnel behind the subnet router. Path MTU Discovery is supposed to handle this, but if PMTU is not working then packets can be dropped. The advice is to lower the MTU of the **Ethernet** to 1280 bytes. This would typically be done using `ip link set`

----

If you do need to adjust the MTU of the tailscale interface, `tailscaled` will look for a TS_DEBUG_MTU environment variable.

`TS_DEBUG_MTU=1350 tailscaled ...`

You can't set the tunnel MTU greater than about 1460 bytes. The Wireguard headers are variable size, but need some amount of room to be left for them.

**Comment by bradfitz** [comment]
That said, the issue isn't MTU for this bug. That's all a bit of a tangent. (I didn't finish debugging what the actual issue exactly is, though. But it's not MTU.)

@Bursade, any reason why you're not using the GUI version on macOS? Using `tailscaled` directly on macOS is relatively uncommon. But I verified there are still a bunch of users currently connected on macOS using tailscaled using 1.34, so it's not broken for everybody at least.

@Bursade, you using any other VPNs or network interception software at the same time? Like macOS Screen Time Content restrictions, TunnelBear, Apple Private Relay, Cloudflare Warp, Mullvad, Wireguard, ZeroTier, PIA, Avast, Norton, Crowdstrike Falcon, VMWare Carbon Black, etc?

**Comment by Bursade** [comment]
@DentonGentry , @bradfitz Thanks for the quick response.

I already adjusted the MTU of my Ethernet interface to 1280 and also adjusted the MTU of the Tailscale interface to the same size.

@bradfitz as you said, that wasn't the issue. I'm still seeing the "unexpected EOF" error when trying to register my machine.
I have GlobalProtect VPN installed but it's currently disabled. I also disable macOS Screen Time completely, just to be sure. But nothing changed.
I'll thoroughly check if I have another network interception software installed and get back to you.

About your first question: while using the GUI version found in the Apple Store (and also the standalone package) I wasn't able to sign in to the network. But, worst of all, I didn't get any errors. I simply clicked on "Sign in to the network" and nothing happened.

**Comment by bradfitz** [comment]
Many VPNs still have side effects when they're installed but "disabled". We just debugged one on macOS the other day that said it was off but once uninstalled, then Tailscale started working.

**Comment by Bursade** [comment]
@bradfitz I've finally found the culprit. I have a Netskope client installed (required for SSL/TLS traffic inspection at work) and it seems that it messing with the packages send to Tailscale registering server (https://controlplane.tailscale.com/machine/register). After disabling it, I was able to register my machine properly.
Thank you for your help!

Since it wasn't an issue with macOS nor tailscale, should I edit the issue before closing it?

**Comment by bradfitz** [comment]
Great! I've added Netskope to our internal list of known-interferers. We plan to add more detection of such programs to give you better warnings, but unfortunately only one of the 3 macOS builds (the `tailscaled` variant) doesn't run in a sandbox, so for most users (using GUI builds) we can't even detect who's messing with us.

When it's running, what's the Netskope process name, btw? And what does `systemextensionsctl list` say? That will help us add detections for it.

**Comment by Bursade** [comment]
hey @bradfitz , sorry for the delay. I wasn't able to get back to you yesterday.
the process name (as shown in the Activity Monitor) is "Netskope Client".
And this is the output of `systemextensionsctl list`

> *	*	24W52P9M7W	com.netskope.client.Netskope-Client.NetskopeClientMacAppProxy (99.0.6.1100/7)	NetskopeClientMacAppProxy	[activated enabled]

**Comment by mihaip** [comment]
@DentonGentry I assume by "health check" you mean include this in the bug report note, similar to how we detect other possibly conflicting apps.
