### ISSUE TITLE
single-label DNS queries via an exit node intended for split DNS are refused if the tailnet has the legacy beta.tailscale.net name enabled

### ISSUE THREAD

**Issue by iliana** [tailscale/tailscale#6852]
### What is the issue?

In an environment where:

* MagicDNS is enabled
* A split DNS zone is configured
* The legacy `beta.tailscale.net` domain is enabled on the tailnet
* The client has an exit node enabled

Single-label queries such as `ping service` fail if `service` is not a registered Tailscale machine, even if it's a valid name in the split DNS zone. I'm able to reproduce this on both a Linux and macOS client.

This appears to be because the exit node's resolver is responding with `REFUSED` for the beta.tailscale.net name, which I think prevents the local resolver from attempting the next search path. This issue does not occur if the client is not routing traffic through an exit node.

I would expect the same behavior whether an exit node is enabled or not; that is, I would expect the exit node's resolver to return something that lets the client fail to the next search path (e.g. a split DNS zone).

<details>
<summary>Full example with lots of `dig` output</summary>

In this example, the record I am trying to resolve is `nitter` from the `iliana.home.arpa` zone I have configured in my account.

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ tailscale version
1.34.1
  tailscale commit: 328b49c4d69bd7fe1cbc8474ee36854dc52eb22c
  other commit: 921b59a2ebc3eb4a703d93f504fc9e10fddf64f6
  go version: go1.19.2-ts3fd24dee31

$ ssh pancake cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ ssh pancake tailscale version
1.34.1
  tailscale commit: 328b49c4d69bd7fe1cbc8474ee36854dc52eb22c
  other commit: 921b59a2ebc3eb4a703d93f504fc9e10fddf64f6
  go version: go1.19.2-ts3fd24dee31

$ cat /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search cat-herring.ts.net iliana.github.beta.tailscale.net iliana.home.arpa

$ sudo tailscale set --exit-node ''

$ ping -c 1 nitter
PING nitter.iliana.home.arpa (100.102.136.119) 56(84) bytes of data.
64 bytes from hydrangea.iliana.github.beta.tailscale.net (100.102.136.119): icmp_seq=1 ttl=64 time=13.0 ms

--- nitter.iliana.home.arpa ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 13.004/13.004/13.004/0.000 ms

$ dig @100.100.100.100 nitter.cat-herring.ts.net

; <<>> DiG 9.16.33-Debian <<>> @100.100.100.100 nitter.cat-herring.ts.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23342
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nitter.cat-herring.ts.net.     IN      A

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Dec 27 02:59:41 UTC 2022
;; MSG SIZE  rcvd: 43


$ dig @100.100.100.100 nitter.iliana.github.beta.tailscale.net

; <<>> DiG 9.16.33-Debian <<>> @100.100.100.100 nitter.iliana.github.beta.tailscale.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7410
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nitter.iliana.github.beta.tailscale.net. IN A

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Dec 27 02:59:49 UTC 2022
;; MSG SIZE  rcvd: 57


$ dig @100.100.100.100 nitter.iliana.home.arpa

; <<>> DiG 9.16.33-Debian <<>> @100.100.100.100 nitter.iliana.home.arpa
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20119
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nitter.iliana.home.arpa.       IN      A

;; ANSWER SECTION:
nitter.iliana.home.arpa. 900    IN      A       100.102.136.119

;; Query time: 4 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Dec 27 02:59:55 UTC 2022
;; MSG SIZE  rcvd: 68


$ sudo tailscale set --exit-node pancake

$ ping -c 1 nitter
ping: nitter: Name or service not known

$ dig @100.100.100.100 nitter.cat-herring.ts.net

; <<>> DiG 9.16.33-Debian <<>> @100.100.100.100 nitter.cat-herring.ts.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35797
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nitter.cat-herring.ts.net.     IN      A

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Dec 27 03:00:09 UTC 2022
;; MSG SIZE  rcvd: 43


$ dig @100.100.100.100 nitter.iliana.github.beta.tailscale.net

; <<>> DiG 9.16.33-Debian <<>> @100.100.100.100 nitter.iliana.github.beta.tailscale.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 60117
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nitter.iliana.github.beta.tailscale.net. IN A

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Dec 27 03:00:13 UTC 2022
;; MSG SIZE  rcvd: 57


$ dig @100.100.100.100 nitter.iliana.home.arpa

; <<>> DiG 9.16.33-Debian <<>> @100.100.100.100 nitter.iliana.home.arpa
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54553
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nitter.iliana.home.arpa.       IN      A

;; ANSWER SECTION:
nitter.iliana.home.arpa. 900    IN      A       100.102.136.119

;; Query time: 16 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Dec 27 03:00:17 UTC 2022
;; MSG SIZE  rcvd: 68
```

</details>

### Steps to reproduce

1. Have an old enough tailnet with `beta.tailscale.net` enabled
2. Create an authoritative DNS zone somewhere with a `service` record (or whatever other name) and set it up in the DNS tab of the admin console
3. Run `ping service` on a client without an exit node enabled; it should work at this point
4. Enable an exit node
5. Run `ping service`; DNS lookup should fail

### OS

Linux, macOS

### OS version

Debian 11; macOS 12.6.2

### Tailscale version

1.34.1

### Bug report

BUG-ea0d04cdcd2290807b4e3c49d457b109ccce1e0cb81df9b5c8d62445a2365c87-20221227031013Z-c45dd504d485d054

**Comment by iliana** [comment]
I think this is the relevant code resulting in the problem:

https://github.com/tailscale/tailscale/blob/c86d9f2ab1a87f3ce565457b4cb47d9c01c98c4e/ipn/ipnlocal/local.go#L2934-L2961

On my tailnet when the exit node is unset, we see this log message:

`dns: Resolvercfg: {Routes:{.:[8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844] ts.net.:[199.247.155.53 2620:111:8007::53]}+1arpa Hosts:42 LocalDomains:[beta.tailscale.net. cat-herring.ts.net.]+65arpa}`

When an exit node is set, we see:

`dns: Resolvercfg: {Routes:{.:[http://100.108.35.69:43304/dns-query]} Hosts:42 LocalDomains:[cat-herring.ts.net.]+65arpa}`

that is, `beta.tailscale.net.` is missing from LocalDomains, which prevents the local Tailscale daemon from responding to the query, instead sending it up to the exit node which [seems to not perform local resolution in the peer API DoH endpoint](https://github.com/tailscale/tailscale/blob/c86d9f2ab1a87f3ce565457b4cb47d9c01c98c4e/net/dns/resolver/tsdns.go#L327); the function doesn't call `resolveLocal` and also marks the response as refused if `allowName` fails (which I think just checks if the record ends in ts.net or tailscale.net?).

Because we are exiting early from this function if we're using an exit node, the DNS route with no resolvers for `beta.tailscale.net.` never gets added.

Not sure there's a clean solution here; could move the for loop in the snippet above before the early return if we have an exit node, but that would be a behavior change: it would leak DNS queries for split DNS instead of proxying them to the exit node. Or we could only add suffixes that have no resolvers before early return, which seems like a mess. Or tsdns's `HandleExitNodeDNSQuery` could process local queries, which feels like an ugly hack since the local daemon should be the one responding NXDOMAIN.

**Comment by iliana** [comment]
I am now able to (permanently) work around this issue: https://tailscale.com/kb/1081/magicdns/#removing-the-betatailscalenet-nameserver

**Comment by DentonGentry** [comment]
I still don't fully understand the nature of the failure, but with the percentage of tailnets with beta.tailscale.net names getting smaller every day and less likely to be a problem, at this point we'll call it fixed by https://tailscale.com/changelog/#2023-01-18-service
