### ISSUE TITLE
`tailscaled` doesn't start if $PORT exists but is empty

### ISSUE THREAD

**Issue by orh17** [tailscale/tailscale#6854]
### What is the issue?

Hey, from some reasons when I install Tailscale in my server I getting this message :

" tailscaled.service is a disabled or a static unit not running, not starting it.
+ [ false = true ]
+ set +x
Installation complete! Log in to start using Tailscale by running:

tailscale up "

when I try to start the service I getting : 
" failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?) "

And the output of systemctl status tailscaled.service is: 
" tailscaled.service - Tailscale node agent
   Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-12-28 11:00:40 IST; 5s ago
     Docs: https://tailscale.com/kb/
  Process: 32501 ExecStopPost=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
  Process: 32495 ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/ta
  Process: 32469 ExecStartPre=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
 Main PID: 32495 (code=exited, status=2)

Dec 28 11:00:40 servername systemd[1]: tailscaled.service: Service hold-off time over, scheduling restart.
Dec 28 11:00:40 servername systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
Dec 28 11:00:40 servername systemd[1]: Stopped Tailscale node agent.
Dec 28 11:00:40 servername systemd[1]: tailscaled.service: Start request repeated too quickly.
Dec 28 11:00:40 aservernamesystemd[1]: tailscaled.service: Failed with result 'exit-code'.
Dec 28 11:00:40 servername systemd[1]: Failed to start Tailscale node agent. "

I tried to do everything I found in google but nothing helped me.
The server is ubuntu 18.04.5

p.s  I have lot of same server that working perfect and the Tailscale installation was simple.

Thanks

### OS

Linux

### OS version

Ubuntu 18.04.5

### Tailscale version

1.34.1

**Comment by bradfitz** [comment]
> Main PID: 32495 (code=exited, status=2)

Well, it's crashing, but `systemctl status` doesn't say why.

Can you watch `journalctl -f` while you restart the service and try to capture the actual crash?

Ubuntu 18.04 should still work, in any case.

**Comment by orh17** [comment]
@bradfitz 
this is the log of journalctl -f :

Jan 09 13:25:41 ald1beast1 systemd[1]: Starting Tailscale node agent...
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: logtail started
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: Program starting: v1.34.2-t1f0817693-g56304b539, Go 1.19.4-tse6ce5b5003: []string{"/usr/sbin/tailscaled", "--cleanup"}
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: LogID: b6cef3e34b4e855caed18686965b3a954673cd71409d7187b3588ad8e971b92b
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: logpolicy: using system state directory "/var/lib/tailscale"
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: dns: [resolved-ping=yes rc=unknown ret=direct]
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: dns: using "direct" mode
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: dns: using *dns.directManager
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: flushing log.
Jan 09 13:25:41 ald1beast1 tailscaled[1873]: logger closing down
Jan 09 13:25:41 ald1beast1 tailscaled[1944]: invalid value "" for flag -port: can't be the empty string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]: Usage of /usr/sbin/tailscaled:
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -bird-socket string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             path of the bird unix socket
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -cleanup
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             clean up system state and exit
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -debug string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             listen address ([ip]:port) of optional debug server
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -no-logs-no-support
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             disable log uploads; this also disables any technical support
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -outbound-http-proxy-listen string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             optional [ip]:port to run an outbound HTTP proxy (e.g. "localhost:8080")
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -port value
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             UDP port to listen on for WireGuard and peer-to-peer traffic; 0 means automatically select (default 0)
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -socket string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             path of the service unix socket (default "/var/run/tailscale/tailscaled.sock")
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -socks5-server string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             optional [ip]:port to run a SOCK5 server (e.g. "localhost:1080")
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -state string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             absolute path of state file; use 'kube:<secret-name>' to use Kubernetes secrets or 'arn:aws:ssm:...' to store in AWS SSM; use 'mem:' to not store state and register as an ephemeral node. If empty and --statedir is provided, the default is <statedir>/tailscaled.state. Default: /var/lib/tailscale/tailscaled.state
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -statedir string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             path to directory for storage of config state, TLS certs, temporary incoming Taildrop files, etc. If empty, it's derived from --state when possible.
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -tun string
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             tunnel interface name; use "userspace-networking" (beta) to not use TUN (default "tailscale0")
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -verbose int
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             log verbosity level; 0 is default, 1 or higher are increasingly verbose
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:   -version
Jan 09 13:25:41 ald1beast1 tailscaled[1944]:             print version information and exit
Jan 09 13:25:41 ald1beast1 systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: logtail started
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: Program starting: v1.34.2-t1f0817693-g56304b539, Go 1.19.4-tse6ce5b5003: []string{"/usr/sbin/tailscaled", "--cleanup"}
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: LogID: b6cef3e34b4e855caed18686965b3a954673cd71409d7187b3588ad8e971b92b
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: logpolicy: using system state directory "/var/lib/tailscale"
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: dns: [resolved-ping=yes rc=unknown ret=direct]
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: dns: using "direct" mode
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: dns: using *dns.directManager
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: flushing log.
Jan 09 13:25:41 ald1beast1 tailscaled[1954]: logger closing down
Jan 09 13:25:41 ald1beast1 systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Jan 09 13:25:41 ald1beast1 systemd[1]: Failed to start Tailscale node agent.
Jan 09 13:25:42 ald1beast1 systemd[1]: tailscaled.service: Service hold-off time over, scheduling restart.
Jan 09 13:25:42 ald1beast1 systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 1.
Jan 09 13:25:42 ald1beast1 systemd[1]: Stopped Tailscale node agent.

**Comment by orh17** [comment]
@DentonGentry even when I try to set it manually I getting the same line of the empty string, any idea?

**Comment by DentonGentry** [comment]
If you run this from the shell, it should not give an error about an empty string:

`/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641`

--------

> @DentonGentry even when I try to set it manually I getting the same line of the empty string, any idea?

Something on your system has set a PORT environment variable, probably very early in boot and passed to all processes as they start. You need to fix that, we cannot help figure out where it is being set.

**Comment by DentonGentry** [comment]
I think this is working as intended: $PORT exists, but is empty.
