### ISSUE TITLE
FR: Target machines without any tags in the src/dst

### ISSUE THREAD

**Issue by rakheshster** [tailscale/tailscale#6859]
### What are you trying to do?

Hi,

I am trying to write ACL rules such that the untagged machines can communicate to each other and to tagged machines, but the tagged machines can't communicate to any untagged machines. Since the default state is to block everything, I think what I need is ACLs like these:

```
"acls": [
	// Everything can talk to machines tagged with vps
	{
		"action": "accept",
		"src":    ["*"],
		"dst":    ["tag:vps:*"],
	},
	
	// Everything with no tags can talk to every other thing with no tags
	{
		"action": "accept",
		"src":    ["!tag:*"],
		"dst":    ["!tag:*:*"],
	}
	
	// Everything else is blocked (default)
]
```

Of course I can't create something like this as there's no way of targetting machines without a tag. Is it possible to create something that captures such machines? The `!tag` syntax is just something I came up with as an example, but it could be an autogroup too maybe.

The alternative of course is to tag every machine and create ACLs, but I don't want to risk forgetting to tag a machine and realize it can't communicate. 

Thanks,
Rakhesh

**Comment by DentonGentry** [comment]
Devices which are not tagged are associated with a User. Allowing any untagged device owned by a User to communicate with any device tagged or untagged could be represented as:

```
	{
		"action": "accept",
		"src":    ["autogroup:members"],
		"dst":    ["*:*"],
	},
```
`autogroup:members` is described in https://tailscale.com/kb/1018/acls/#autogroups

There isn't an autogroup for all machines carrying any tag. If there are a small number of tags, rules could be instantiated allowing each tag to communicate with the other tags:
```
	{
		"action": "accept",
		"src":    ["tag:vps", "tag:other"],
		"dst":    ["tag:vps:*", "tag:other:*"],
	},
```

**Comment by rakheshster** [comment]
Thanks @DentonGentry. In my case both machines are owned by the same user. I guess I'll just tag every machine for now so I can make the appropriate rules.

**Comment by DentonGentry** [comment]
I don't understand why it would be necessary to tag the machines currently owned by a user.

From the original description:
- untagged machines can communicate to each other and to tagged machines
- tagged machines can communicate with other tagged machines
- tagged machines can't communicate to any untagged machines

I think this can be implemented via:
```
"acls": [
	// Everything can talk to machines tagged with vps
	{
		"action": "accept",
		"src":    ["*"],
		"dst":    ["tag:vps:*"],
	},
	
	// Everything with no tags can talk to every other thing
	{
		"action": "accept",
		"src":    ["autogroup:members"],
		"dst":    ["*:*"],
	}
	
	// Everything else is blocked (default)
]
```

If you had multiple users and wanted a user's machines to be able to communicate amongst themselves, but not to machines owned by other users, that would be:
```
	{
		"action": "accept",
		"src":    ["autogroup:members"],
		"dst":    ["autogroup:self:*"],
	}
```

**Comment by rakheshster** [comment]
Thanks again for the reply! :) Wouldn't "autogroup:members" also include the tagged machine though and thus result in it being able to talk to all other machines?

**Comment by DentonGentry** [comment]
autogroup:members is described in https://tailscale.com/kb/1018/acls/#autogroups
_Used to allow access for any user who is a direct member (not a shared user) of the tailnet._

Tagged machines are not owned by a User, they are owned by the Tag, and will not be part of autogroup:members

**Comment by rakheshster** [comment]
Ah!💡didn't realise tagged machines were owned by the tag. Thanks @DentonGentry!

**Comment by poofygummy** [comment]
> autogroup:members is described in https://tailscale.com/kb/1018/acls/#autogroups _Used to allow access for any user who is a direct member (not a shared user) of the tailnet._
> 
> Tagged machines are not owned by a User, they are owned by the Tag, and will not be part of autogroup:members

@DentonGentry 

This should really be made more clear in the documentation if possible. The fact that "members" refers to only human users and not tagged machines, is currently not clear at all!
