### ISSUE TITLE
docker start failed

### ISSUE THREAD

**Issue by cooltnt** [tailscale/tailscale#6862]
### What is the issue?

Please help me. Every time start, there is an error.

error logs:
.............
To authenticate, visit:
	https://login.tailscale.com/a/f5c28fc........
2022/12/31 03:22:55 logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: i/o timeout (in 30.001s), trying bootstrap...
2022/12/31 03:23:10 logtail: upload: log upload of 3375 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/d8b911b44e3a4dd11e1eff2cd4e4a40c003fb253b89c640009b396d913daf05b": context deadline exceeded
2022/12/31 03:23:10 logtail: [v1] backoff: 9 msec
boot: 2022/12/31 03:23:23 failed to auth tailscale: couldn't log in: tailscale up failed: signal: killed

### OS

Other

### OS version

qnap qts5.0.1.2248

### Tailscale version

docker-hub  tailscale/tailscale:latest

**Comment by DentonGentry** [comment]
> 2022/12/31 03:22:55 logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: i/o timeout (in 30.001s), trying bootstrap...

The docker container has no connectivity, it cannot reach the Internet.

https://hub.docker.com/r/tailscale/tailscale suggests a command line of:
`docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW tailscale/tailscale`

The `--network=host` says for the host to use NAT to let the container reach the Internet.

**Comment by cooltnt** [comment]
> > 2022/12/31 03：22：55 对数：拨号“log.tailscale.io:443”失败：拨打TCP 34.229.201.48：443：I/O超时（30.001秒），尝试引导...
> 
> docker 容器没有连接，它无法访问互联网。
> 
> https://hub.docker.com/r/tailscale/tailscale 建议使用命令行： `docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW tailscale/tailscale`
> 
> 主机使用 NAT 让容器到达互联网的说法。`--network=host`




> > 2022/12/31 03:22:55 logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: i/o timeout (in 30.001s), trying bootstrap...
> 
> The docker container has no connectivity, it cannot reach the Internet.
> 
> https://hub.docker.com/r/tailscale/tailscale suggests a command line of: `docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW tailscale/tailscale`
> 
> The `--network=host` says for the host to use NAT to let the container reach the Internet.


First of all, thank you for your reply. 

Previously, it has been generated using the container station of qnap, but this error has occurred since a while ago

**Comment by DentonGentry** [comment]
> Previously, it has been generated using the container station of qnap, but this error has occurred since a while ago

I don't understand what that means, but: your Docker host is not providing Internet connectivity to the containers. You need to fix that.

I don't think there is a Tailscale problem to be resolved.
