### ISSUE TITLE
High CPU usage for IPNExtension on Intel mac, macOS Ventura 13.1

### ISSUE THREAD

**Issue by offbyone** [tailscale/tailscale#6868]
### What is the issue?

More or less what it says on the tin:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/181693/210196284-27180ad1-0a4c-43e4-bc8a-ff77403ac514.png">

On an 8-core intel macbook pro, IPNExtension is taking close to 4 complete cores to itself.

I can see some previous bugs in this vein: #3252 and #2051

From the troubleshooting steps in #3252: 

```
❯ systemextensionsctl list
2 extension(s)
--- com.apple.system_extension.driver_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	G43BCU2T37	org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.6.0/1.6.0)	org.pqrs.Karabiner-DriverKit-VirtualHIDDevice	[activated enabled]
--- com.apple.system_extension.cmio
enabled	active	teamID	bundleID (version)	name	[state]
*	*	97Z3HJWCRT	com.opalcamera.OpalCamera.opalCameraExtension (1.4/9)	opalCameraExtension	[activated enabled]
```

### Steps to reproduce

Just.. running tailscale. 

### Are there any recent changes that introduced the issue?

The only thing I've done recently is tried out Funnel. Currently that is on, but no proxies are running: 

```
❯ tailscale serve status
WARNING: funnel=on for void.camel-tortoise.ts.net:443, but no serve config
```

### OS version

macOS Ventura 13.1

### Tailscale version

1.34.1

### Bug report

BUG-42b3fcc4c8eda420cb4e6deea027750e053580e35b79bb91f2c3c1a27b3d971d-20230102045815Z-75452740e2e2c201

**Comment by bradfitz** [comment]
We keep seeing occasional reports about this but we've never been able to nail down details or been able to reproduce it.

Is there massive network activity during this time too, or just CPU?

Is this correlated with sleeping+resuming the laptop?

Any other antivirus/firewall/vpn/security software installed, even if not running?

Using an exit node? Being an exit node?

**Comment by offbyone** [comment]
Re: network activity, hard to say; it's possible that my cloud backup is moving data, but I don't know, and I'm not doing anything _intentionally_ to schlep bits in bulk at the time.

Re: sleeping + resuming... maybe? Certainly not 100% of the time; I just resumed now, for example, and I'm not seeing it. But I open/close this laptop all the time, so I don't know if I'd have noticed.

Re: antivirus/firewall/vpn/security software... not on this computer. I don't even have an OpenVPN client on it.

I am not currently using an exit node, nor is this machine acting as one.

**Comment by bradfitz** [comment]
> Re: network activity, hard to say; it's possible that my cloud backup is moving data, but I don't know, and I'm not doing anything intentionally to schlep bits in bulk at the time.

Mostly I meant to ask whether there's some infinite packet loop going on where Tailscale is sending and it's looping back in to Tailscale via the OS back to Tailscale and Tailscale is responding, forever. That'd happened in a few other older issues. I'd be curious if you see some ridiculous level of Network activity in Activity Monitor.

> Re: sleeping + resuming... maybe? Certainly not 100% of the time; I just resumed now, for example, and I'm not seeing it. But I open/close this laptop all the time, so I don't know if I'd have noticed.

So I take it you're not able to reproduce this easily?

If you kill IPNExtension does it stay good for a while?

**Comment by offbyone** [comment]
Yep. Actually, my solution is to just "quit tailscale and restart it"

Next time it happens I'll look at the network pane and see; hopefully there'll be something in there.

If there's any debugging / telemetry that would help, I have no problem enabling it.

**Comment by bradfitz** [comment]
> Actually, my solution is to just "quit tailscale and restart it"

Tailscale is two processes: the IPNExtension and the GUI. Normally when the GUI quits we try to stop the IPNExtension, but if it's spinning and there's already some bug, I'm not 100% confident stopping the GUI will stop the extension. But it should be pretty obvious from CPU usage whether it did.

If it happens again, run `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug --cpu-profile=- > cpu.pprof` and attach that `cpu.pprof` file? (GitHub might require you zip it first)

**Comment by kdrag0n** [comment]
I've ran into this issue several times recently on M1, macOS 13.1. It seems to be correlated with losing internet connectivity and going out of range of Wi-Fi during sleep, but it happens regardless of whether I'm using Amphetamine to inhibit sleep. IPNExtension is using 150% CPU every time this happens, seemingly in a busy loop of sending UDP packets. Quitting the GUI successfully stops the extension.

For what it's worth, I'm using an exit node and it ends up connecting over DERP sometimes.

```
(pprof) top
Showing nodes accounting for 20.73s, 97.46% of 21.27s total
Dropped 151 nodes (cum <= 0.11s)
Showing top 10 nodes out of 65
      flat  flat%   sum%        cum   cum%
     9.72s 45.70% 45.70%      9.72s 45.70%  syscall.syscall
     8.51s 40.01% 85.71%      8.51s 40.01%  syscall.syscall6
     1.83s  8.60% 94.31%      1.83s  8.60%  runtime.kevent
     0.27s  1.27% 95.58%      0.27s  1.27%  runtime.pthread_cond_wait
     0.18s  0.85% 96.43%      0.18s  0.85%  runtime.pthread_cond_signal
     0.15s  0.71% 97.13%      0.15s  0.71%  runtime.usleep
     0.02s 0.094% 97.23%      8.67s 40.76%  golang.zx2c4.com/wireguard/device.(*Peer).SendBuffer
     0.02s 0.094% 97.32%      2.32s 10.91%  runtime.schedule
     0.02s 0.094% 97.41%      0.15s  0.71%  runtime.stealWork
     0.01s 0.047% 97.46%      0.15s  0.71%  golang.zx2c4.com/wireguard/device.(*Device).RoutineReadFromTUN
```

<img width="1058" alt="Screenshot 2023-01-04 at 2 46 19 PM" src="https://user-images.githubusercontent.com/7930239/210664271-c0ae78dc-45fc-491d-b139-d3062abf5993.png">

[goroutine dump](https://github.com/tailscale/tailscale/files/10348009/goroutines.log)
[pprof](https://github.com/tailscale/tailscale/files/10348011/ts.prof.zip)
Let me know if anything else would be helpful.

**Comment by bradfitz** [comment]
@kdrag0n, thanks! Looking at that profile cumulatively,

```
(pprof) top 20 --cum
Showing nodes accounting for 18.26s, 85.85% of 21.27s total
Dropped 151 nodes (cum <= 0.11s)
Showing top 20 nodes out of 65
      flat  flat%   sum%        cum   cum%
         0     0%     0%      9.72s 45.70%  internal/poll.ignoringEINTRIO (inline)
     9.72s 45.70% 45.70%      9.72s 45.70%  syscall.syscall
         0     0% 45.70%      9.29s 43.68%  internal/poll.(*FD).Read
         0     0% 45.70%      9.29s 43.68%  syscall.Read (inline)
         0     0% 45.70%      9.29s 43.68%  syscall.read
         0     0% 45.70%      9.29s 43.68%  tailscale.com/net/tstun.(*Wrapper).poll
         0     0% 45.70%      9.28s 43.63%  golang.zx2c4.com/wireguard/tun.(*NativeTun).Read
         0     0% 45.70%      9.28s 43.63%  os.(*File).Read
         0     0% 45.70%      9.28s 43.63%  os.(*File).read (inline)
         0     0% 45.70%      8.68s 40.81%  golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialSender
     0.02s 0.094% 45.79%      8.67s 40.76%  golang.zx2c4.com/wireguard/device.(*Peer).SendBuffer
         0     0% 45.79%      8.65s 40.67%  tailscale.com/wgengine/magicsock.(*Conn).Send
         0     0% 45.79%      8.65s 40.67%  tailscale.com/wgengine/magicsock.(*endpoint).send
     0.01s 0.047% 45.84%      8.63s 40.57%  tailscale.com/wgengine/magicsock.(*Conn).sendAddr
         0     0% 45.84%      8.51s 40.01%  net.(*UDPConn).WriteToUDPAddrPort
         0     0% 45.84%      8.51s 40.01%  net.(*UDPConn).writeToAddrPort
         0     0% 45.84%      8.51s 40.01%  net.(*netFD).writeToInet4
     8.51s 40.01% 85.85%      8.51s 40.01%  syscall.syscall6
         0     0% 85.85%      8.51s 40.01%  tailscale.com/wgengine/magicsock.(*Conn).sendUDP
         0     0% 85.85%      8.51s 40.01%  tailscale.com/wgengine/magicsock.(*Conn).sendUDPStd
```

Next time this happens can you also grab a `tailscale bugreport` so we can look at the metric counters?

And if you want to look at them too, see:

```
$ tailscale debug local-creds
curl -u:xxxx http://localhost:52320/localapi/v0/status
```

.... to find the credentials. Then change that `status` to `metrics`, like:

```
$ curl --silent  -u:xxxx http://localhost:52320/localapi/v0/metrics
....
# TYPE tstun_in_from_wg counter
tstun_in_from_wg 944717
# TYPE tstun_in_from_wg_drop counter
tstun_in_from_wg_drop 10
# TYPE tstun_in_from_wg_drop_filter counter
tstun_in_from_wg_drop_filter 10
# TYPE tstun_in_from_wg_drop_self_disco counter
tstun_in_from_wg_drop_self_disco 0
# TYPE tstun_out_to_wg counter
tstun_out_to_wg 3652953
# TYPE tstun_out_to_wg_drop counter
tstun_out_to_wg_drop 2885678
# TYPE tstun_out_to_wg_drop_filter counter
tstun_out_to_wg_drop_filter 38406
# TYPE tstun_out_to_wg_drop_self_disco counter
tstun_out_to_wg_drop_self_disco 0
# TYPE wgengine_major_changes counter
wgengine_major_changes 3697
# TYPE wgengine_minor_changes counter
wgengine_minor_changes 6161
```

Taking a couple snapshots of that while it's spinning might be interesting too.

**Comment by kdrag0n** [comment]
I actually grabbed metrics with `tailscale debug metrics` but cleared my terminal history already :/

Will do next time.

**Comment by bradfitz** [comment]
Oh, right, that's the easier way.

But @mihaip points out that this looks identical to #5156 so let's dup this into that one. Can you reply on #5156 with things you learn?

Note his comment there: https://github.com/tailscale/tailscale/issues/5156#issuecomment-1344542656

If you can repro this easily, we'd be curious if that change helps.

**Comment by kdrag0n** [comment]
Sure. It seems to be happening every few days for me but unfortunately I can't reproduce it on demand.
