### ISSUE TITLE
FR: Report IPv6 LL address (fe80::/10) to control and broadcast packets for certain multicast addresses

### ISSUE THREAD

**Issue by SilverBut** [tailscale/tailscale#6870]
### What are you trying to do?

I'm trying to use tailscale as the overlay network, and run [babeld](https://www.irif.fr/~jch/software/babel/) as routing daemon.

Babel is a pretty promising routing protocol due to following reasons:
* Whole network connectivity with pretty fast routing convergence
* Dynamic metric by design, based on *latency* between nodes
* Lightweight protocol design based on full-IPv6

This makes it a good choice to build mesh network, especially among devices in mobile network. More specifically, this makes nodes can communicate with each other, even if they can't see each other directly and DERP is totally down. This is the scenario described in #2632.

However I failed because Babel have those requirements:
* Nodes can be reached by using the link local address (`fe80::/10`), which is not in `AllowedIPs` and `Address` of Tailscale wireguard settings, because they are [ignored](net/interfaces/interfaces.go#L134)
* Nodes are discovered using a multicast address `ff02::1:6`. Neither Tailscale nor standard Wireguard would allow using multicast in the network. In 2020, Jason have [explained](https://lore.kernel.org/all/878sd3qwp3.fsf@toke.dk/T/#m280ad2e337daac70093508f063f2c1d84d9c1723) why it doesn't fit into WIreGuard's model, but I think there are some spaces for discussion in Tailscale.

### How should we solve this?

Considering this feature needs lots of additional setup, I think they should only be configured via arguments for `tailscaled`. I recommend add following arguments:

* `--allow-link-local` would:
  * Report the  IPv6 LL address of `tailscale0` to the control.
  * Ensure `Address` and `AllowedIPs` have the peer's LL address, so packets with it as dest address could reach the peer.
* `--allow-multicast-address=[v6address],[v6address]...` would:
  * Add addresses above to all peer's `AllowedIPs` config
  * When the interface received a packet with this destination:
    * If comes from local process, duplicate and send a copy to all peers.
    * If comes from another peer, deliver to the OS.
    * If comes by routed from another interface, ignore to prevent loop.

### What is the impact of not solving this?

For Bable, the impact is severe.

The best possible working around would be using VXLAN and [add multiple unicast addresses in Tailnet](https://joejulian.name/post/how-to-configure-linux-vxlans-with-multiple-unicast-endpoints/) to it. However, the additional layer is hurting performance, and make debugging complex by adding additional layer (Real Internet -> Tailnet -> VXLAN). 

Another working around is [R.A.I.T.](https://gitlab.com/NickCao/RAIT). This achieved multicast by creating one interface for each peer. Obviously Tailscale can save this effort.

### Anything else?

Here is another introduction about Babel: https://witestlab.poly.edu/blog/babel-a-loop-avoiding-distance-vector-routing-protocol/

**Comment by SilverBut** [comment]
No, I still don't think this issue is having a right description. And after reviewing the code again I still have no idea. The general idea is make link-local address working in Tailnet, so it looks like a real working layer 2 network. But I can't see the best way to implement it.

Let me just draft this.

**Comment by DentonGentry** [comment]
I really would rather discuss it in an issue before you send a PR.

At this point we only advertise link-local addresses as endpoints if there is no better alternative. That happens in
https://github.com/tailscale/tailscale/blob/692eac23adf62f979dddb5b9694d084142036f10/net/interfaces/interfaces.go#L90

Various serverless environments like AWS Lambda and Google Cloud Run have linklocal IP assignments which we need to be able to use.

Though I understand why one might propose an `--allow-link-local` flag, to set expectations: we are unlikely to accept a pull request adding a command line argument which is only useful in extraordinarily limited circumstances. We strive for the product to automatically figure out how to function in environments in common use. We also strive to not load the product up with obscure options which will be likely to conflict and add to the complexity of the codebase.

You're welcome to fork the repository and implement it for your own use, but we may not accept it upstream.

**Comment by SilverBut** [comment]
> I really would rather discuss it in an issue before you send a PR.
> 
> We also strive to not load the product up with obscure options which will be likely to conflict and add to the complexity of the codebase.

Thanks @DentonGentry and I surely can see the importance of well communication before sending the PR. I've never wrote code about this feature yet.

The purpose of my reviewing the code is (yet) not sending a PR. It's just for a quick assessment to check if this feature is technically possible and reasonable. And it's the review leading to the decision of my closing this issue. I think a PR should only be made after having preliminary consensus on the issue. 

After reviewed the code I fully agree with your opinion. Even if it should be implemented, it should not be a flag. 

Link-local addresses are designed for making different machines on the same link operatable without configuration, and it's a part of IPv6's zero conf concept. If Tailscale is going to support link-local addressing (which means not only advertising LL addresses, but also process other `ff02::` multicast addresses), the best way is to implement it directly, not adding a flag.

I think I should reword this whole issue, and focus on implementing proper functions about link-local routing, so all nodes in the same Tailnet can be recognized as on the same *link* (or, connect on the same switch). Do you think this is a good start point for future discussion?

---

BTW I think you mixed up *LL* address and *ULA* address. Link local addresses (`FE80::/10`) are generated automatically so machines on the same *link* have different address, which sounds like `169.254.0.0/16` (but much more important in IPv6). While the Unique Local Addresses (`FC00::/7`), being used by GCP for IPv6 routing, is just some other form of `10.0.0.0/8`. ULA addresses should only be routed within certain network border, while ordinary IPv6 addresses can be routed anywhere.

**Comment by SilverBut** [comment]
Few words so anyone want to run routing daemon on Tailscale can save their time.

This issue itself was intended to route link-local address, and make the multicast address work. Link local address can be easily dealt with, but multicast is hard. Multicast is designed for devices connected through link layer, so delivering a packet to multiple devices can have same cost comparing delivering to a single device. Mesh network is not good at this. So seems it's highly unlikely being (should be?) supported.

Also, Tailscale is designed like an overlay network, means route between nodes is not decided by kernel, but by Tailscale. Considering a 3 node network, mesh connected via Tailscale, and in node A a route goes like this:

```
fd7a::c via fd7a::b dev tailscale0 onlink
```

Packets will never routed through node B, because the tailscale daemon don't know this route table exists. Actually Tailscale itself acts like some routing protocol.

If anyone still wants a routing daemon, currently the only option is to add another overlay network (like VXLAN or mGRE) above Tailscale.

(but make sure you can solve MTU issues correctly by [yourself](https://github.com/tailscale/tailscale/net/tstun/tun.go#L51) ).
