### ISSUE TITLE
FR: I want to add a Custom Identity Provider using OIDC or SAML protocol.

### ISSUE THREAD

**Issue by ujji8055** [tailscale/tailscale#6871]
### What are you trying to do?

I want to add a custom Identity Provider using OIDC and SAML protocol.
Can you please suggest how can I add one?
Thanks

### How should we solve this?

Enable custom Identity Provider Feature.

**Comment by DentonGentry** [comment]
We do expect to do this, but the functionality is not yet available.
Duplicate of https://github.com/tailscale/tailscale/issues/823
