### ISSUE TITLE
FR: Exit Node automatic disable on trusted Wi-Fi

### ISSUE THREAD

**Issue by ukanuk** [tailscale/tailscale#6872]
### What are you trying to do?

On my Android phone and Windows laptop, I like enabling exit node when I visit the coffee shop and disabling exit node when I'm at home. As far as I can tell this is recommended use per https://tailscale.com/kb/1103/exit-nodes/. However because it's a manual process and Tailscale mostly runs silently in the background, I frequently forget to toggle the exit node connection on/off.

### How should we solve this?

I would like a feature to let Tailscale automatically disable the exit node when at home (whitelist of home Wi-Fi 2.4Ghz and 5GHz and wired networks, and/or maybe some type of geofence for phones), and automatically enable the exit node when roaming.

### What is the impact of not solving this?

Subconsciously I know I have a VPN, so I'm safe checking my bank account and doing other things while on public Wi-Fi at the café. But I frequently forget to toggle the exit node connection on/off, which means I am already logged into my bank before I remember I have to manually toggle the VPN.

**Comment by DentonGentry** [comment]
Duplicate (stated in reverse) of https://github.com/tailscale/tailscale/issues/3302
