### ISSUE TITLE
Android development release v1.36.0 looks broken when an exit node is active

### ISSUE THREAD

**Issue by praneetloke** [tailscale/tailscale#6873]
### What is the issue?

My Android (Pixel) device is enrolled in to the Beta track and received the development release v1.36.0. When an exit node is active, the app looks broken. But VPN connectivity functions as expected through the exit node. It looks like a visual bug more than anything. I've tried to restart the app, as well as the phone and it's easily reproducible right now. If I choose `None` as the exit node, the layout goes back to normal.

<details>

<summary>Screenshot</summary>

![Screenshot_20230102-092724](https://user-images.githubusercontent.com/1466314/210267705-e20b7512-8320-4359-aae9-6acf56564d27.png)

</details>

### Steps to reproduce

I am not sure if the issue is specific to Android 12 or my Pixel device version. The bug report hopefully has my device info for you to try and reproduce this. Having said that, install the 1.36.0 from the Beta track and choose an exit node to see the layout corruption.

### OS

Android

### OS version

12

### Tailscale version

1.36.0

### Bug report

BUG-73a8bc0485d90b538032df6389e2ce1e0d685f410366f8885f6b3b4a9321d92a-20230102183044Z-aa8b01f92f1dc8d8

**Comment by DentonGentry** [comment]
Well, that's unfortunate.

This is almost certainly related to https://github.com/tailscale/tailscale-android/pull/73.
I tested a number of UI interactions but it didn't occur to me to turn an exit node on.
I can reproduce it here, it should be fixable.

**Comment by praneetloke** [comment]
Ah yes. Indeed. From what I can tell it looks to be a clipping/offset issue. That is, the controls that are supposed to be there are indeed there behind the green background. For example, I can toggle the service state using the toggle switch control in the top-left corner, as well as tap on my device's IP address to copy it, both of which are visible when there is no exit node selected.

**Comment by DentonGentry** [comment]
A fixed version will be available in Open testing soon. It will have a release date of January 2.

**Comment by praneetloke** [comment]
I just got it on my device and your fix works great! Thank you for the speedy turnaround.
