### ISSUE TITLE
tailscale pfsense - no access from behind pfsense to tailscale clients

### ISSUE THREAD

**Issue by xadonxander** [tailscale/tailscale#6874]
I set up my pfsense firewall with tailscale. Everything works fine remotely to connect to all the devices on my local network. however if I try to access any of the remote devices from my local network it does not work,

I can ping my local addresses 192.168.1.* through any tailscale connected device. I can not ping any tailscale device from any of my local devices through the pfsense firewall. 

under diagnostic/routes I see the destinations listed for the tailscale addresses which show interface tailscale0 but all the uses are 0.

**Comment by DentonGentry** [comment]
This would be done using "tailscale up --snat-subnet-routes=false" to make the 100.x.y.z addresses visible on the local LAN. However I don't think the --snat-subnet-routes argument works on FreeBSD at present.

![snat](https://user-images.githubusercontent.com/1140756/210283187-52e4f989-2f11-4dab-9e95-1136dac04d60.png)

**Comment by xadonxander** [comment]
That does not make much sense. I am trying to use tailscale site 2 site. None of the devices can communicate with devices from the other site, the only communication is from devices directly attached to tailscale. The other subnets are listed in the pfsens routing table but there is a failure during the reouting somewhere. Whats the point of tailscale for pfsense if this does not work?

**Comment by xadonxander** [comment]
I had to create a outbound map rule to connect to the remote devices. I did not realize it was not automatically done since its in the routing table already,

**Comment by bradfitz** [comment]
@xadonxander, sounds like you got it working. I'm going to close this one.

#5573 tracks `snat-subnet-routes=false` on FreeBSD.

**Comment by hassanmohsin** [comment]
> I had to create a outbound map rule to connect to the remote devices. I did not realize it was not automatically done since its in the routing table already,

Would you mind sharing how did you create the outbound map rule? Thanks.
