### ISSUE TITLE
FR: tailscale cli option to print out tailscale cert domain name

### ISSUE THREAD

**Issue by tonyg** [tailscale/tailscale#6878]
### What are you trying to do?

Working with `tailscale cert` for local dev, I want to be able to discover the domain name from `tailscale` so that I can choose the correct cert file to point my dev service at.

### How should we solve this?

Running `tailscale cert` does print "`For domain, use "...".`", so I *could* just parse the output, but it'd be nice if there were some way of getting the domain name nicely printed on a line of its own.

### What is the impact of not solving this?

I'm hardcoding the domain name in my wee dev startup scripts. This is fine enough, it'd just be a little nicer with it automated.

### Anything else?

Many thanks for tailscale! It's just great.

**Comment by maisem** [comment]
You should be able to use `tailscale status --json | jq ".CertDomains[0]"`

**Comment by tonyg** [comment]
Many thanks @maisem, that does the job perfectly. I wish I'd looked harder for the `--json` option before filing this :-)
