### ISSUE TITLE
Windows client - custom "LoginURL" in registry ignored

### ISSUE THREAD

**Issue by m-kratochvil** [tailscale/tailscale#6879]
Team, looking for help with possible bug I ran into.

I have just installed Tailscale 1.34 on Windows 11. We are using custom login URL. 
I have therefore added following into my Windows registry:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Tailscale IPN]
"LoginURL"="https://tailscale.custom.url"
```

When I click on "Login" in the client app, Tailscale opens a browser at the default login URL `https://login.tailscale.com/login?refresh=true&next_url=%2Fa%2F9a0b1a6270ce`, instead the one configured in the Windows registry.

I restarted the Tailscale client, rebooted the laptop few times, to no success.

It's important to mention, that from CLI the login works fine (with `tailscale up --login-server=https://tailscale.custom.url/`), it's just the GUI client that is misbehaving..

I will appreciate your help, thanks. Please let me know if/what additional info I should provide.

**Comment by DentonGentry** [comment]
We think this broke in the work done for [fast user switching](https://tailscale.com/blog/fast-user-switching/). As you note, `tailscale up --login-server=https://tailscale.custom.url/` does work and the accounts set up for fast user switching can each be on different control servers. One can switch between the Tailscale public server and a Headscale instance, for example.

**Comment by czzonet** [comment]
broken after 1.32

**Comment by czzonet** [comment]
Also how to add no-log flags to tailscaled in win?

**Comment by mihaip** [comment]
@kradalby's #6803 should this this, it was picked up in the [1.34.2 release](https://tailscale.com/changelog/#2023-01-04-client) that went out today.
