### ISSUE TITLE
pkgs.tailscale.com: mention that mips is MSB, not LSB

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#688]
User reports: we don't specify right now and it was confusing.

Also: ubiquiti gear is all mipsle, so maybe we should build that binary too (`GOARCH=mipsle`)

**Comment by danderson** [comment]
Hm, I vaguely recall I didn't build it because none of the package repositories ship mipsle in any sensible way (debian has an on-off project to ship stuff, but it's more broken than not afaict).

That said, not much reason to not build static binaries at least.

**Comment by jzelinskie** [comment]
stripping the binaries would be nice, too. mips platforms usually don't have much in the way of space.
[nextdns](https://github.com/nextdns/nextdns/releases/tag/v1.7.1) seems to nail the crossplatform ux

**Comment by danderson** [comment]
Not sure how much Go binaries like being stripped, I recall some early issues with that where the runtime was relying on some stuff. Will dig.

**Comment by jzelinskie** [comment]
I believe they declared those issues to be bugs which they fixed many versions ago.

https://twitter.com/_rsc/status/847095473391521792

![Screen Shot 2020-08-14 at 9 22 41 PM](https://user-images.githubusercontent.com/343539/90302464-4b5a4080-de74-11ea-82cb-53c657eb8163.png)

**Comment by jzelinskie** [comment]
I'm running `git checkout v1.0.5 && GOOS=linux GOARCH=mipsle go build -ldflags="-s -w" ./cmd/tailscaled` on my EdgeRouter X SFP and it's working perfect! 👍 The only awkwardness is that I didn't set the ldflag for the version.

**Comment by bradfitz** [comment]
https://pkgs.tailscale.com/unstable/#static now includes mipsle binaries. They're not stripped yet, though.

**Comment by bradfitz** [comment]
I think having both files next to each other is probably sufficient to close this bug.
