### ISSUE TITLE
FR: Add support Synology DSM7.1

### ISSUE THREAD

**Issue by root-T2** [tailscale/tailscale#6887]
### What are you trying to do?

I am unable to install tailscale 1.34 on DSM7.1.   

The tailscale provided by the package center is version 1.30. I want to update to the latest version because of problems caused by the old version in my environment.
However, when I try to manually install the latest version, v.1.34, I am told that it requires an OS older than DSM 7.0-40000 and cannot install it.

Is there any workaround?

![image](https://user-images.githubusercontent.com/25367033/210472949-4225432f-9051-4a89-a75b-5949e941fee9.png)

my environment
- Synology DS920+ (amd64)
- DSM 7.1.1-42962 Update 1
- tailscale 1.30.2-300027

**Comment by bradfitz** [comment]
Note how the Synology section has both a DSM6 and DSM7 (7+) subsection: 

https://pkgs.tailscale.com/stable/#spks

<img width="547" alt="Screenshot 2023-01-03 at 7 12 15 PM" src="https://user-images.githubusercontent.com/2621/210477425-c8c215b2-2460-4b97-868d-e0e5260af580.png">

**Comment by root-T2** [comment]
You are right!!  
I guess I assumed that the one on top was the newer one.   
Thank you for your quick response. It was very helpful.

**Comment by bradfitz** [comment]
> I guess I assumed that the one on top was the newer one.

We made that page when there was only DSM6, and then DSM7 later was only a tiny fraction of users, but now DSM6 is only a tiny fraction of users. Maybe it's time to hide it a bit more. Or reformat it. I'll file a separate bug about that!

**Comment by bradfitz** [comment]
Filed #6889
