### ISSUE TITLE
Tailscale ssh "operation not permitted"

### ISSUE THREAD

**Issue by OwnageIsMagic** [tailscale/tailscale#6888]
### What is the issue?

Trying to connect with ssh to some docker container. Js console closes after auth with vague error message.
Logs:
```log
2023/01/04 03:16:49 ssh-conn-20230104T031648-11f5ffdc27: handling conn: 100.100.77.230:28391->app@100.93.116.135:22
2023/01/04 03:16:50 ssh-conn-20230104T031648-11f5ffdc27: starting session: sess-20230104T031650-053ff6822d
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): handling new SSH connection from OwnageIsMagic@github (100.100.77.230) to ssh-user "app"
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): access granted to OwnageIsMagic@github as ssh-user "app"
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): starting pty command: [/app/tailscale_1.34.1_amd64/tailscaled be-child ssh --uid=1000 --gid=1000 --groups=1000 --local-user=app --remote-user=OwnageIsMagic@github --remote-ip=100.100.77.230 --has-tty=true --tty-name=pts/1 --shell --login-cmd=/bin/login --cmd=/bin/bash -- -l]
2023/01/04 03:16:50 ssh-session(sess-20230104T031650-053ff6822d): Wait: code=1
```
Running manually
```
$ ls -l /bin/login && ls -l /bin/bash
-rwxr-xr-x 1 root root 48128 Mar 26  2019 /bin/login
-rwxr-xr-x 1 root root 1037528 Jul 12  2019 /bin/bash

$ id
uid=1000(app) gid=1000(app) groups=1000(app)

$ tailscale_1.34.1_amd64/tailscaled be-child ssh --uid=1000 --gid=1000 --groups=1000 --local-user=app --remote-user=OwnageIsMagic@github --remote-ip=100.100.77.230 --has-tty=true --tty-name=pts/1 --shell --login-cmd=/bin/login --cmd=/bin/bash -- -l
operation not permitted
```

### OS

Linux

### OS version

Ubuntu 16.04.7 LTS

### Tailscale version

1.34.1_amd64

**Comment by DentonGentry** [comment]
> Ubuntu 16.04.7 LTS

Is it really Ubuntu 16? If so, lack of `DynamicUser` support in the systemd config is a login-related problem we have run into in other contexts: https://github.com/tailscale/tailscale/issues/4817

**Comment by OwnageIsMagic** [comment]
`tailscaled` not running as root in my setup. So actually I don't need it (DynamicUser)

**Comment by DentonGentry** [comment]
> tailscaled not running as root in my setup. So actually I don't need it (DynamicUser)

Do you think that not running it as root might be related to why it is getting "operation not permitted" errors?

**Comment by OwnageIsMagic** [comment]
I meant that my setup doesn't involve systemd. I manually running tailscaled from user shell, so `DynamicUser` config value is unrelated.
> not running it as root might be related to why it is getting "operation not permitted" errors?

I think spawning new process in another user context demands some privileges (i.e. [setuid](https://man7.org/linux/man-pages/man2/setuid.2.html)), but you can probably enable my setup by checking that target user is the same as current user of `tailscaled be-child ssh` and avoid using priveleged api on that path.

**Comment by bradfitz** [comment]
I sent https://github.com/tailscale/tailscale/pull/6904 with a fix.
