### ISSUE TITLE
Last seen not accurate (linux 1.0.4)

### ISSUE THREAD

**Issue by kellytrinh** [tailscale/tailscale#689]
**Describe the bug**

The 'last seen' column in `https://login.tailscale.com/admin/machines` is not accurate.

**To Reproduce**
1. From VPS ping a computer in my local network.  From computer in local network ping VPS.  Both work fine.
2. Look at `https://login.tailscale.com/admin/machines` and the `last seen` for the VPS is 2 hours ago.

**Expected behavior**
The last seen should update to `less than a minute ago` like my other computers.

**Screenshots**

https://imgbox.com/4CGK6o3P

**Version information:**
 - Device: laptop / VPS
 - OS: Linux
 - OS version: Ubuntu 18.04
 - Tailscale version: 1.0.4

**Comment by bradfitz** [comment]
I see all 7 of your devices have a LastSeen time in the past minute.

Is it still showing wrong?

/cc @rosszurowski

**Comment by kellytrinh** [comment]
It seems fine now; not sure what twig I did in this afternoon but discrepancy mysteriously went away.  Perhaps close for now and reopen if resurfaces.
