### ISSUE TITLE
FR: Auth keys from non-person user(service account)

### ISSUE THREAD

**Issue by wsmlby** [tailscale/tailscale#6901]
### What are you trying to do?

We are using tailscale to connect 2 server clusters, and having to rely on a user's auth key is dangerous.

### How should we solve this?

allow auth key to be not linked to one user, created and managable by admins.

### What is the impact of not solving this?

Not able to use this for servers in production.

**Comment by DentonGentry** [comment]
Giving server machines their own identity not tied to a human user is handled using tags:
- https://tailscale.com/kb/1068/acl-tags/
- https://tailscale.com/blog/acl-tags-ga/

**Comment by DentonGentry** [comment]
I believe this feature request is met by using authkeys with tags.
