### ISSUE TITLE
windows: not showing an update (on 1.34.1, 1.34.2 is available)

### ISSUE THREAD

**Issue by colemickens** [tailscale/tailscale#6905]
### What is the issue?

Normally I'm used to right-clicking on the TS tray icon to see if there's an update.

Today, it does not say there's an update, like it might normally... even though the client is aware its behind:

![image](https://user-images.githubusercontent.com/327028/211110129-1dd1dacd-9bd9-4c3f-8049-3a3549793a25.png)

(While I'm here, it would be nice to get notifications for updates without needing to check the context menu, etc)

### OS

Windows

### OS version

Win 11

### Tailscale version

1.34.1

### Bug report

BUG-c3822dd1e578f696f7e9d8419a6e96cae38cc297d8634d86b5ed6b02663f0f9e-20230106222518Z-6cbad75d01c0a35e

**Comment by bradfitz** [comment]
> While I'm here, it would be nice to get notifications for updates without needing to check the context menu, etc

1.34.0+ does actually include that support but we haven't used it yet. It's mostly there for emergencies and 1.34.1 to 1.34.2 is not an emergency.

But the "Update" context menu not showing up is definitely a bug. Probably a regression from a bunch of our Windows UI work in the previous release.

**Comment by bradfitz** [comment]
I can reproduce:

```
C:\WINDOWS\system32>logtail started
Program starting: v1.34.1-t328b49c4d-g921b59a2e, Go 1.19.2-ts3fd24dee31: []string{"tailscale-ipn"}
LogID: 76745561c2f3d03d381fd84189aa4d43abe35ac2168fb6226b30b0fad57ad8b3
logpolicy: using LocalAppData dir C:\Users\winuser\AppData\Local\Tailscale
stdout ok.
stderr ok.
log ok.
Running UI client...
ui: creating mainWindow
ui: Failed to explicitly start tailscaled: An instance of the service is already running.
ui: creating tray
ui: watchBackend: connected.
ui: stateChanged: NoState -> Running
ui: Handle: logs: be:8a7972f40870ce1f761e7d572c7afeaf4fe94b91e13411c5ddad754eb8e7dfc2 fe:76745561c2f3d03d381fd84189aa4d43abe35ac2168fb6226b30b0fad57ad8b3
ui: latest version check: "1.34.2", <nil>
ui: stateChanged: Running -> Starting
ui: stateChanged: Starting -> Running
```

**Comment by bradfitz** [comment]
Ah, I see... we're missing a call to `(*app).uiRefreshUpdateMenuVisibility` in the path where the client checks for updates on its own.

But fortunately we can fix this server-side meanwhile by pushing down a `tailcfg.ClientVersion` message to the client (without the `Notify` bit set).

**Comment by bradfitz** [comment]
The two fixes have been checked in (to the Windows GUI client and to the coordination server). When we redeploy the coordination server, a message should be sent to your existing Windows GUI client that tells it the new latest version and the menu item should become visible, even for the affected Windows GUI version. A restart shouldn't even be necessary.
