### ISSUE TITLE
FR: Updating clients remotely

### ISSUE THREAD

**Issue by LunchBoxC** [tailscale/tailscale#6907]
### What are you trying to do?

I'm using Tailscale to connect to clients remotely using remote desktop software.  

When an update for the Tailscale software exists I must manually visit these clients to update them as installing the new package over remote desktop disconnects the client and it can't be reconnected to until the setup process is fully completed and the installer exits.

### How should we solve this?

It could be solved by the following:

1) Allow clients to be updates from the admin console

OR

2) allow for automatic updating of the clients

OR

3) Change the installer so that it briefly disconnects to do the install and then reconnects all clients before the installer exits as there is no way to click on "Finish" when tailscale is now in the disconnected state and preventing the remote desktop software from making a connection.

### What is the impact of not solving this?

Waste of resources driving to clients to update their Tailscale application version.  

It also means that clients run on outdated versions for longer.

### Anything else?

It would also be great if we could pre-configure the installer and send it out with all options like "run unattended" and with the credentials already installed so the installer would make the connection after the install.  

This would make sending it to someone to install a snap, rather than needing to configure it thereafter with novice users that don't understand what to click on.

Again to aid remote connection environments.

**Comment by bradfitz** [comment]
Much of this is currently underway.

**Comment by SilverBut** [comment]
Great feature I'm waiting for. 

Also, it would be great if the remote updating will failsafe, so that if a server is lockdown (for example, only allowing login from other devices in the `tailnet`) and client update failed, the old client process can still working.

cc @bradfitz

**Comment by DentonGentry** [comment]
The initial step in this is `tailscale update`

**Comment by noncombatant** [comment]
News on this bug: Proposed solution (2) is done; see [the Beta release of auto-updates](https://tailscale.com/blog/auto-update-beta/) if you haven't already.

Proposed solution (1) is in development now. We provide a guarantee of when it will land, but it is a key part of our plan for taking auto-updates out of Beta, and we are working on it now.
