### ISSUE TITLE
tailscale need an option to close the derp completely

### ISSUE THREAD

**Issue by herotheo** [tailscale/tailscale#6908]
### What are you trying to do?

in my Intranet，i jsut want to close the derp，to protect my Intranet network traffic with tailscale. because  there isn't NAT device.

**Comment by bradfitz** [comment]
Even if your node doesn't need NAT, your peers or future peers might need NAT traversal.

>  to protect my Intranet network traffic

DERP is just an outgoing HTTPS connection, like any browsing you'd do in a web browser. It doesn't open anything on your LAN to the world.

https://tailscale.com/blog/how-tailscale-works/ says more about all this.

But turning off DERP will not end well. You can certainly try and see what happens, though. See https://tailscale.com/kb/1118/custom-derp-servers/ for how to turn them off. It's not recommended.

**Comment by DentonGentry** [comment]
(was composing this when Brad responded)

Two Tailscale nodes try to make direct connections: they send UDP frames to every IP address they know for the other, trying to find a way which will make it through. If they find a working path, they send Wireguard.

DERP is the connectivity of last resort, if they cannot find a direct path they will relay through DERP.

DERP also facilitates probing for a direct path. When one node decides it wants to connect, it starts sending UDP frames to probe for a direct path and it also sends a call-me-maybe message via DERP to the other node. The other node will start probing from the other end.
