### ISSUE TITLE
funnel not resolving 

### ISSUE THREAD

**Issue by unnimona** [tailscale/tailscale#6910]
### What is the issue?

i am unable to access http ports like 80 and 443 through
i also checked dig CNAME and i cannot find any CNAME or A record pointing to the tailscale

how to fix 

sudo tailscale serve status -json

{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "REDACTED.REDACTED.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:80"
        }
      }
    }
  },
  "AllowFunnel": {
    "REDACTED.REDACTED.ts.net:443": true
  }
}

**Comment by DentonGentry** [comment]
> REDACTED.REDACTED.ts.net

If you don't want to put the hostname in a public bug report you can use https://tailscale.com/contact/support/ to submit a support ticket privately.

We can't do anything with a bugreport lacking any information to debug.
