### ISSUE TITLE
funnel not resolving in public 

### ISSUE THREAD

**Issue by unnimona** [tailscale/tailscale#6911]
### What is the issue?

am unable to access http ports like 80 and 443 through
i also checked dig CNAME and i cannot find any CNAME or A record pointing to the tailscale

how to fix

sudo tailscale serve status -json

{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "raspberry-adguard.tailcc040.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:80"
        }
      }
    }
  },
  "AllowFunnel": {
    "raspberry-adguard.tailcc040.ts.net:443": true
  }
}

### OS version

Ubuntu 22.04

### Tailscale version

latest

**Comment by bradfitz** [comment]
Looks like it's working now. I see a redirect to /login.html.

We're still working on productionizing the Funnel DNS infrastructure. It'll improve before Funnel is out of alpha.
