### ISSUE TITLE
Linux problem with tailnet/subnet cohabitation  (complex (a little) network configuration)

### ISSUE THREAD

**Issue by father-mande** [tailscale/tailscale#6913]
### What is the issue?

Hi,
can't access a Linux box using LAN IP address when tailnet AND LAN IP are configured **AND** a router (subnet route) is defined
all tailnet node accept route ... using only tailnet works as well ...
all node (for this test) use 1.34.2 tailscale version (Linux use "other" delivery (static)) or Ubuntu delivery
... no docker, no containers, no chroot ... just tailscale delivery programs and internal integration when no official delivery exist (NAS Asustor, Qnap, others ... )
no problem with windows box only for Linux ....

No sure it's a real bug, perhaps putting in subnet node with tailscale also generate bug (for ex. with mark packet)
... it's just to don't change client configuration (from LAN IP to tailnet IP) ... but using only tailscale is a workaround.

### Steps to reproduce

LAN : 
1 pc windows 11 client with tailscale and LAN IP (100.x.x.x and 192.168.1.y
1 pc windows 11 server (RDP for ex.) with ONLY LAN IP 192.168.1.z
1 Linux box AA with tailscale and LAN IP
1 Linux box BB with tailscale and LAN IP
1 Linux box CC with ONLY LAN IP
external (Internet) : 
1 pc windows 11 client with tailscale and LAN IP 192.168.111.x

**without --advertise-routes** ... connection between ANY node to ANY other works (LAN IP or tailnet IP), only external PC can used tailnet only and don't have access to NON tailnet node (normal).
**with --advertise-routes 192.168.1.0/24 on node AA (Linux)**
external PC can access node using tailnet IP (for system with), througt subnet router (AA) can access windows pc server with tailnet IP or LAN IP
AA node (subnet router) can be acceded using tailnet IP or LAN IP
**BUT** other server (BB) **can't be acceded** using LAN IP ... ONLY tailnet IP works
CC (without tailnet) can be acceded using LAN IP

Internally to the LAN 192.168.1.0  **no connection using LAN IP between Linux LAN node works** ... only tailnet works ...

So difference exist if target is Linux or Windows (working in all cases)

### Are there any recent changes that introduced the issue?

No ... just adding test with --advertise-routes for testing access to NON tailnet node.

### OS

Linux, Windows, Other

### OS version

Linux Asustor ... ADM 4.2 (Linux level Ubuntu 18.04+) 

### Tailscale version

1.34.2

### Bug report

BUG-d7a95b8db9e6e7dd0d81b25cb7e1eda4fbfc7ed56fcc3fa28f5a2fae8c69f788-20230108134754Z-62f5602f87ec1907

**Comment by DentonGentry** [comment]
I'm having a hard time following the described network topology, but:
- The Windows client accepts routes by default, with a menu item to disable accepting routes
- The Linux client, as the first client developed and the one most often used as a subnet router itself, does not accept routes by default. It has to be told to do so.

For the Linux machines which cannot currently access the LAN IP addresses, please make sure:
`tailscale up --accept-routes`
has been run.

----

> Linux Asustor

The [static binaries](https://pkgs.tailscale.com/stable/#static) do run on ASUS devices, but note that no `iptables` binary is present so the platform is not completely functional. We hope to have an ASUS package eventually, but for now these devices are best-effort support.

**Comment by father-mande** [comment]
Hi,

I can redo a verification, but I have use tailscale up --accept-routes on all (or use tailscale set --accept-routes for some one (all rebooted) ... if I remember it's also in the base64 encoded profile in tailscale.state file ...

Asustor Package (I am a package integrator ... my own available on Asustor forum and in few time I hope in Asustor AppCentral) integrate all components including missing iptables modules ... so all (reported to the documentation) run as expected, iptables, mark, masquerade and others ...
I suppose you speak for other package just a container for docker but without integration in specific Asustor architecture and Linux choice. ... my own integrate lot of options including a specific WebUI to manage APKG (Asustor package) and tailscale itself (including auto-update mechanism)

Philippe.

**Comment by father-mande** [comment]
Hi,

After new tests to be sure tailscale up --accept-routes is used (no change) ... and re reading all document and new search ... I think it's possible that I fall in the case developed in troubleshooting guide (seem I don't make the relation between my problem and an existing problem) ... : 
https://tailscale.com/kb/1023/troubleshooting/#how-to-prioritize-lan-traffic-with-overlapping-subnet-routes

I will run tests A.S.A.P. to test using priority rule to solve my problem.

I will be back after new tests.

Philippe.

**Comment by father-mande** [comment]
Hi,

After verification and more tests, **I can confirm that the problem is the priority of LAN traffic** in case of node having **LAN IP and Tailnet IP inside a subnet** with another router

**Solution** (base on troubleshooting guide) : 
**ip rule add to 192.168.X.0/24 priority 2000 lookup main**  ... for ex. to Linux box in subnet and tailnet ... solve the connection problem.

I have solved the problem by adding a flag to add this rule, now I have to search if it's possible to automatize the process : 
... identify if a subnet router exist and is enable for the subnet, then verify if Linux box is a node not the router, then apply the rule ...

Philippe.
NB I close this issue .

**Comment by father-mande** [comment]
Closed
