### ISSUE TITLE
syslog spammed with "kex_exchange_identification" errors

### ISSUE THREAD

**Issue by karan** [tailscale/tailscale#6916]
### What is the issue?

I have 2 systems - server1 and server2 - both running TS.

### On server1

```
srvr@srvr:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:  Ubuntu 22.04.1 LTS
Release:  22.04
Codename: jammy
```

```
1.35.115
  tailscale commit: b2b8e62476d54b2cbc929241390ffa9ede6b4cce
  other commit: 19daff399d66ed3db530f59b5772e02d6771a0b1
  go version: go1.19.4-tsdc0ce6324d
```

```
$ tailscale status
$SERVER1_IP  srvr                 karan@       linux   idle; offers exit node
$SERVER2_IP    unraid               karan@       linux   idle; offers exit node, tx 2216536 rx 1962648

# Health check:
#     - This is an unstable (development) version of Tailscale; frequent updates and bugs are likely
```

### On server2

Unraid version 6.11.5
Tailscale running using Docker image `deasmi/unraid-tailscale:latest`.

```
/app # ./tailscale version
1.34.1
  tailscale commit: 328b49c4d69bd7fe1cbc8474ee36854dc52eb22c
  other commit: 921b59a2ebc3eb4a703d93f504fc9e10fddf64f6
  go version: go1.19.2-ts3fd24dee31
```

```
/app # ./tailscale status
$SERVER2_IP    unraid               karan@       linux   idle; offers exit node
$SERVER1_IP  srvr                 karan@       linux   active; offers exit node; direct $SERVER1_LAN_IP:41641, tx 1964300 rx 2217380

# Health check:
#     - Some peers are advertising routes but --accept-routes is false
```

## The issue

On server2, I'm seeing A TON of syslog spam of the following form:

```
$SERVER1_IP port 39670 on $SERVER2_IP port 22 rdomain ""
Jan  8 14:39:56 Tower  sshd[29958]: error: kex_exchange_identification: Connection closed by remote host
$SERVER1_IP port 39670
$SERVER1_IP port 39938 on $SERVER2_IP port 22 rdomain ""
Jan  8 14:40:56 Tower  sshd[31384]: error: kex_exchange_identification: Connection closed by remote host
$SERVER1_IP port 39938
$SERVER1_IP port 40214 on $SERVER2_IP port 22 rdomain ""
Jan  8 14:41:56 Tower  sshd[310]: error: kex_exchange_identification: Connection closed by remote host
$SERVER1_IP port 40214
$SERVER1_IP port 40486 on $SERVER2_IP port 22 rdomain ""
Jan  8 14:42:56 Tower  sshd[1885]: error: kex_exchange_identification: Connection closed by remote host
$SERVER1_IP port 40486
```

Notice that it's every minute. `server1` runs only 1 job every minute but that seems to be executing a few seconds after the logs above (and it doesn't actually touch server2 via tailscale or otherwise).

The ports being used are high enough as well that I don't _this_ this is an application I'm running. Almost everything running on `server1` uses port numbers < 10000.

I've searched and searched and can't really figure out what's going on. I just can't seem to correlate any logs I see on the two devices. I also don't see the spam in server1's syslog:

```
$ grep "kex_exchange_identification" /var/log/syslog | wc -l
0
```

Further, on `server1` I don't see any connections to `server2`:

```
$ netstat -a | grep $SERVER2_IP
```

This has been happening for a while and I've just been too lazy to investigate until now. I've filed a bug report from both systems:

- From server1: `BUG-5b731bbefdc71d1ad493765d666427d604a949402a0938b0e1ae63ac60fb015f-20230108230019Z-d83bbeedd6c0d7b2`
- From server2: `BUG-e901cea74aa85b3157e555fb51f0a7f56f20e82a5a21544c76a783b1b635fbdc-20230108225749Z-ec66c8dd6b20f9f8`

I'd appreciate any help in figuring out what is opening these SSH connections, why it's failing, and how to stop it.

**Comment by DentonGentry** [comment]
I'm not clear on what this issue is requesting: we don't have visibility into what processes are sending packets traversing the tailnet. Since the log message is from `sshd` that means [Tailscale SSH](https://tailscale.com/blog/tailscale-ssh/) is not in use: the packets might be traversing the tailnet but they are being delivered to OpenSSH.

`journalctl -u tailscaled | grep Accept` would show all of the ACL evaluations allowing connections to the server. `tailscaled` doesn't have more visibility than that into what application is sending the SSH sessions.

**Comment by karan** [comment]
I guess what would help might be to understand how these ports are selected. For eg `54456`, `54186`, `53932` are the most recent ports used for connecting to `server2:22` from what I can tell. Is tailscaled on server1 picking these ports to forward packets to server2? Is an application on server1 picking these ports?

I tried looking at `netstat -a` on both and didn't see any connections to/from these ports.

Further, there isn't anything on server1 that uses tailscale (other than tailscaled itself) - my SSH connection between the two servers uses LAN IP. So I'm truly baffled by what is causing these connections.

**Comment by DentonGentry** [comment]
An application on server1 is making an SSH connection to server2. It is apparently choosing a random ephemeral port as its source port — likely it is an `ssh` command being run by a shell script. It is connecting to the 100.x.y.z address of server2, so its SSH packets end up traversing the tailnet.

> Is tailscaled on server1 picking these ports to forward packets to server2?

`tailscaled` on server1 is almost certainly not involved in this at all. `tailscaled` itself does not initiate SSH connections. Something on server1 is likely forking an SSH command and connecting to 100.x.y.z.

**Comment by karan** [comment]
That was helpful @DentonGentry. Thanks!

I figured it out. I have an uptime monitoring tool that checks if my servers are accessible in the tailnet, and it does so by attempting to SSH every minute. I disabled that and now no more spam.

It's odd though because my uptime monitoring tool isn't using the ports that tailscaled logs to syslog. Regardless, this isn't a tailscale bug so I'll close it.
