### ISSUE TITLE
tailscaled can't manipulate the routing table in a FreeBSD jail

### ISSUE THREAD

**Issue by sehang** [tailscale/tailscale#6917]
### What is the issue?

The tailscale client is installed in a jail of FreeBSD (tun allowed). 

The tailscale client is able to ping the exit node.
```
root@jail:~ # tailscale ping x.x.x.x
pong from x.x.x.x via DERP(fra) in 671ms
pong from x.x.x.x via DERP(fra) in 229ms
pong from x.x.x.x via DERP(fra) in 231ms
```

However, when I use the curl to get the information of exit node. It returns the original IP.  Did I make a wrong configuration?

Thanks a lot!

### Steps to reproduce

```
tailscale up --accept-routes --exit-node-allow-lan-access --exit-node="x.x.x.x"
curl ifconfig.co
```

The version of tailescale is:
```
tailscale version: 1.34.1
go version: go1.19.4
```

### OS

Other

### OS version

FreeBSD jail 12.2-RELEASE-p14 FreeBSD 12.2-RELEASE-p14 325282c09a5(HEAD) TRUENAS  amd64

### Tailscale version

1.34.1

### Bug report

BUG-4ce7d15537ef08cf6c74a753c23fd35a4ad1653defd93e833ae97c7425aa9011-20230109045600Z-6e72fbe18a87c776

**Comment by DentonGentry** [comment]
Adding routes is failing inside the jail:
```
2023-01-09 04:50:18.299785857 +0000 UTC: router: addr add failed: [route -q -n add -inet 0.0.0.0/0 -iface tailscale0]: exit status 1
```

**Comment by sehang** [comment]
Thanks for prompt reply.  It seems that the jail of FreeBSD somehow doesn't work on routing.

I login the jail using SSH and execute the command

`router: addr add failed: [route -q -n add -inet 0.0.0.0/0 -iface tailscale0`

No error prompts. Moreover, I double check the routing table, I don't see the route was added to the interface tailscale0.

`root@p7zip:~ # netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            192.168.1.1        UGS     epair0b
****/32    tailscale0         US     tailscal
****/32  tailscale0         US     tailscal
****       link#4             UHS         lo0
****/32    link#4             U      tailscal
***/32   tailscale0         US     tailscal
****/32   tailscale0         US     tailscal
****/32   tailscale0         US     tailscal
****/32   tailscale0         US     tailscal
100.100.100.100/32 tailscale0         US     tailscal
****/32 tailscale0         US     tailscal
127.0.0.1          link#1             UH          lo0
192.168.1.0/24     link#3             U       epair0b
192.168.1.12       link#3             UHS         lo0
`

**Comment by bradfitz** [comment]
> I login the jail using SSH 

Maybe logging in via SSH doesn't make you as jailed as you think you are.

**Comment by bradfitz** [comment]
I'm not sure there's anything we can do here so closing this for now.

Some background reading: https://forums.freebsd.org/threads/understanding-routing-table-in-a-jail.69906/ which includes a user `tokred` saying:

> If you require a full network stack inside a jail, including dedicated routing table, have a look at [vnet(9)](https://www.freebsd.org/cgi/man.cgi?query=vnet&sektion=9&manpath=freebsd-release-ports).
