### ISSUE TITLE
"funnel" node attribute not set with autogroup:members

### ISSUE THREAD

**Issue by FiloSottile** [tailscale/tailscale#6922]
### What is the issue?

Despite having added the default tag with the button in Access controls, I get

```
/Applications/Tailscale.app/Contents/MacOS/Tailscale serve funnel on
2023/01/09 22:57:15 Funnel not available; "funnel" node attribute not set. See https://tailscale.com/kb/1223/tailscale-funnel/.
```

from an untagged node.

### OS

macOS

### OS version

macOS Ventura 13.1

### Tailscale version

1.34.2

### Bug report

BUG-78902bdfaf724fdf4c1dd793ee86605b16b8d9226361f5cceff79dd02ede7d38-20230109215725Z-61114d0c38aae41a

**Comment by danderson** [comment]
cc @bradfitz @maisem is autogroup expansion in nodeattrs a known thing?

**Comment by Milo123459** [comment]
also happening for me.

**Comment by bradfitz** [comment]
@danderson, yes, we discussed it elsewhere. And corp bug is https://github.com/tailscale/corp/issues/8519

@maisem, can you take this?
