### ISSUE TITLE
Tailscale creating network interface without initialising `ifa_addr`

### ISSUE THREAD

**Issue by arumugamramaswamy** [tailscale/tailscale#6924]
### What is the issue?

Tailscale creates a network interface with `ifa_addr = null`. This causes a null pointer dereference in another program causing a Segmentation fault.

### Steps to reproduce

1. Install tailscale
2. make sure the daemon is running
3. list the network interfaces with this short C program.
```
#include <arpa/inet.h>
#include <sys/socket.h>
#include <ifaddrs.h>
#include <stdio.h>

int main ()
{
    struct ifaddrs *ifap, *ifa;
    struct sockaddr_in *sa;
    char *addr;

    getifaddrs (&ifap);
    for (ifa = ifap; ifa; ifa = ifa->ifa_next) {
        printf("%s, %p\n", ifa->ifa_name, ifa->ifa_addr);
    }

    freeifaddrs(ifap);
    return 0;
}
```
4. Verify that one of the network interfaces created corresponds to `tailscale0, (nil)`

### Are there any recent changes that introduced the issue?

I'm a new user, so I am not sure.

### OS

Linux

### OS version

Ubuntu 22.04.1 LTS

### Tailscale version

1.34.2

### Bug report

BUG-05609af30c6358eae024d8e5d515ff9e407121e446295d6dfc3bd47530667cfa-20230110085537Z-f327f21e789671cd

**Comment by arumugamramaswamy** [comment]
Thank you for the clarification! I will proceed to contact the creators of the other software.

**Comment by arumugamramaswamy** [comment]
Is there anyway in which we can force this interface to be assigned an address?

**Comment by DentonGentry** [comment]
The tun device is created during initialization, and `tailscaled` begins the node registration process. The coordination server assigns an IP address after authentication. Authentication unavoidably takes time: if a human is logging in, they visit https://login.tailscale.com in a browser and get redirected through their identity provider.

This is not so very different from an Ethernet or Wi-fi interface which is created prior to DHCP assigning an IP address. There is an unavoidable delay between when the interface netdev is created and when DHCP returns the IP address to use.

Interfaces do not get IP addresses at the time of their creation.

**Comment by arumugamramaswamy** [comment]
> The coordination server assigns an IP address after authentication. Authentication unavoidably takes time: if a human is logging in, they visit https://login.tailscale.com in a browser and get redirected through their identity provider.

Can I check if in this case, authenticating using `tailscale login` will assign an address to the `tun` interface?

**Comment by bradfitz** [comment]
What program is crashing?

**Comment by arumugamramaswamy** [comment]
We're using Omron's `StViewer`

**Comment by bradfitz** [comment]
Thanks for the info. I don't think there's anything we want to change right now, but we'll keep that in mind if others hit similar problems.

It really sounds like a bug in StViewer.

I'm going to close this for now but we can revisit if we find that this problem is more widespread.
