### ISSUE TITLE
Funnel TCP doesn't work locally from macOS

### ISSUE THREAD

**Issue by FiloSottile** [tailscale/tailscale#6930]
### What is the issue?

I have a shiny TCP Funnel that's reachable from the outside world, but if I try to connect to it from the machine where it's served, or from iOS with Tailscale on, it doesn't work.

Arguably, I can just bind to 0.0.0.0 and connect to the local port instead, but that's marginally less magical and requires switching addresses between environments, which is not necessarily trivial with some protocols.

### Steps to reproduce

* `tailscale serve funnel on`
* start a server at `localhost:8443`
* `tailscale serve tcp 8443`
* `curl https://$NODE.$TSNET.ts.net/` from the local machine fails
* loading `https://$NODE.$TSNET.ts.net/` from iOS with Tailscale on fails
* loading `https://$NODE.$TSNET.ts.net/` from iOS with Tailscale off works

### OS

macOS

### OS version

macOS Ventura 13.1

### Tailscale version

1.34.2

### Bug report

BUG-78902bdfaf724fdf4c1dd793ee86605b16b8d9226361f5cceff79dd02ede7d38-20230110191137Z-7f81aa22b0fb97a4

**Comment by bradfitz** [comment]
This is what the "works best on Linux" comment at https://tailscale.com/kb/1223/tailscale-funnel/#limitations is referring to.

We try to run an extra listener for local traffic but the macOS sandbox is annoying in this regard. @shayne was fighting it a bit and trying to convince macOS to do what we want but we were getting permission errors, even with our various network server entitlements enabled.

We need to try fighting it more.

**Comment by shayne** [comment]
I have https://github.com/tailscale/tailscale/pull/6771, which would bring the magic back by working around platform limitations. It's silly, but we can listen on all interfaces, but strangely the system fails on a specific interface. This PR makes an exception for privileged ports when running in the macOS sandbox and listens on all interfaces.

**Comment by shayne** [comment]
@FiloSottile https://github.com/tailscale/tailscale/pull/6771 was merged! This should make it into the v1.36 release.

**Comment by shayne** [comment]
@FiloSottile v1.36 was released, and you should be able to access your Funnel URL locally now. LMK

If you have yet to receive the update, check the [App Store](https://apps.apple.com/us/app/tailscale/id1475387142?mt=12).

**Comment by FiloSottile** [comment]
It works! Thank you @shayne.

**Comment by Multiply** [comment]
@shayne following up from my off-topic comment here: https://github.com/tailscale/tailscale/pull/7334#issuecomment-1496895163

Some of our devices cannot access their own funnel locally.

**Device that don't work now**
MacBook Pro 2019 (i9)
macOS: Ventura 13.3
tailscale: 1.39.110 (macsys)

- The device didn't work when funnel got released (alpha)
- Started working in March (might have been earlier, but I didn't test it again until start of March I believe)
- No longer works after upgrading or rebooting (within last week)
- Nothing seems to listen on port 443
- Tried using netcat as suggested (with tailscale stopped)
  - When binding without defining the interface: `Address already in use`
  - When binding with any interface: `Permission denied`
  - When using sudo, it seems to bind to both just fine.
  
**Device that works now**
MacBook Pro 2021 (M1 Max)
macOS: Ventura 13.3
tailscale: 1.38.3 (App Store)

- We've only just started testing on this device, and it just seemed to work out of the box.
- Worth noting IPNExtension is actively listening on port 443

**Comment by Multiply** [comment]
@shayne We're only going by the hostname you mentioned, yes.

it's definitely because we have other things listening on :443, but on specific interfaces, not everything.
They are listening on unrelated interfaces created purely for our internal dev tools.

I'm working with the team to address our old setup running on `docker` and `kind` to move away from that port and maybe reuse the new caddy proxy we set up.
