### ISSUE TITLE
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)

### ISSUE THREAD

**Issue by ParsouaArabshahi** [tailscale/tailscale#6941]
I've searched alot in the community but couldnt find any way to fix this!

anybody can help me with this?

root:~# systemctl status tailscaled.service
× tailscaled.service - Tailscale node agent
     Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-01-12 13:05:30 UTC; 17min ago
       Docs: https://tailscale.com/kb/
   Main PID: 1393 (code=exited, status=1/FAILURE)

Jan 12 13:05:30 Ipn.server systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
Jan 12 13:05:30 Ipn.server systemd[1]: Stopped Tailscale node agent.
Jan 12 13:05:30 Ipn.server systemd[1]: tailscaled.service: Start request repeated too quickly.
Jan 12 13:05:30 Ipn.server systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Jan 12 13:05:30 Ipn.server systemd[1]: Failed to start Tailscale node agent.

root@Ipn:~# /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641
logtail started
Program starting: v1.34.2-t1f0817693-g56304b539, Go 1.19.4-tse6ce5b5003: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41641"}
LogID: faa96bd6d9ea8cb5f291dc6f86e22f10b68293048554d6db900c0469dadd163d
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
Linux kernel version: 5.2.0
is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: FATAL: Module tun not found in directory /lib/modules/5.2.0
tun module not loaded nor found on disk
wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist
flushing log.
logger closing down
getLocalBackend error: createEngine: tstun.New("tailscale0"): CreateTUN("tailscale0") failed; /dev/net/tun does not exist

**Comment by knyar** [comment]
Tailscale client on Linux needs access to `/dev/net/tun` to be able to create a `tun` network device. What Linux distro are you using? If you are running in a container, you might need to explicitly pass `/dev/net/tun` to the container, or use [userspace networking mode](https://tailscale.com/kb/1112/userspace-networking/).

**Comment by ParsouaArabshahi** [comment]
you are right, the problem was my access to tun folder!

but that socks option is frustrating!

**Comment by bradfitz** [comment]
Glad you got it resolved. In the future, please include lots more information in GitHub issues. There was almost nothing here from which to help you or debug.

**Comment by ParsouaArabshahi** [comment]
sure, Thank you, I'm bigginer in linux, i will listen to your advice next time :)

can you please help me on one more thing?
how can i add this command to run at start so i don't exeute this command everytime i do reboot?

tailscaled --tun=userspace-networking --socks5-server=localhost:54355 --outbound-http-proxy-listen=localhost:54355 & ...

**Comment by bradfitz** [comment]
This isn't really the right forum for general Linux help but I'm excited for you. It's fun stuff to learn.

Answering your question would require context you haven't provided like your distro, etc. But the supported way of running Tailscale on Linux is via our dozens of distro packages. If you're doing it by hand like that we assume you know what you're doing.

**Comment by ParsouaArabshahi** [comment]
Thank you so much :)
i really appreciate your help

My Ubuntu version is 20.04.5 LTS (GNU/Linux 5.4.0 x86_64)

**Comment by Polv89** [comment]
Installing tailscale follow official guide (https://tailscale.com/download/linux/debian-bookworm) on debian 12 gives me the same error

i have this error on my client, running Mx Linux 23.3 (Debian based) and the same trying to install it on a lxc container running debian 12. 

I solved on the client, but on the server running Debian 12, after running one command script "curl -fsSL https://tailscale.com/install.sh | sh"

and try to run tailscale up i have this error:

failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)

root@Nextcloud ~# systemctl status tailscaled
x tailscaled.service - Tailscale node agent
     Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-08-20 14:54:25 UTC; 1min 32s ago
   Duration: 432ms
       Docs: https://tailscale.com/kb/
    Process: 1053 ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS (cod>
    Process: 1081 ExecStopPost=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
   Main PID: 1053 (code=exited, status=1/FAILURE)
        CPU: 110ms

Aug 20 14:54:24 Nextcloud systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Aug 20 14:54:25 Nextcloud systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 6.
Aug 20 14:54:25 Nextcloud systemd[1]: Stopped tailscaled.service - Tailscale node agent.
Aug 20 14:54:25 Nextcloud systemd[1]: tailscaled.service: Start request repeated too quickly.
Aug 20 14:54:25 Nextcloud systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Aug 20 14:54:25 Nextcloud systemd[1]: Failed to start tailscaled.service - Tailscale node agent.
lines 1-16/16 (END)

**Comment by pbassut** [comment]
@Polv89 Solved it for me, thanks! Also using proxmox.

**Comment by wzm2256** [comment]
> Installing tailscale follow official guide (https://tailscale.com/download/linux/debian-bookworm) on debian 12 gives me the same error
> 
> i have this error on my client, running Mx Linux 23.3 (Debian based) and the same trying to install it on a lxc container running debian 12.
> 
> I solved on the client, but on the server running Debian 12, after running one command script "curl -fsSL https://tailscale.com/install.sh | sh"
> 
> and try to run tailscale up i have this error:
> 
> failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
> 
> root@Nextcloud ~# systemctl status tailscaled x tailscaled.service - Tailscale node agent Loaded: loaded (/lib/systemd/system/tailscaled.service; enabled; preset: enabled) Active: failed (Result: exit-code) since Tue 2024-08-20 14:54:25 UTC; 1min 32s ago Duration: 432ms Docs: https://tailscale.com/kb/ Process: 1053 ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS (cod> Process: 1081 ExecStopPost=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS) Main PID: 1053 (code=exited, status=1/FAILURE) CPU: 110ms
> 
> Aug 20 14:54:24 Nextcloud systemd[1]: tailscaled.service: Failed with result 'exit-code'. Aug 20 14:54:25 Nextcloud systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 6. Aug 20 14:54:25 Nextcloud systemd[1]: Stopped tailscaled.service - Tailscale node agent. Aug 20 14:54:25 Nextcloud systemd[1]: tailscaled.service: Start request repeated too quickly. Aug 20 14:54:25 Nextcloud systemd[1]: tailscaled.service: Failed with result 'exit-code'. Aug 20 14:54:25 Nextcloud systemd[1]: Failed to start tailscaled.service - Tailscale node agent. lines 1-16/16 (END)
> 
> I solved adding these lines to the container.conf file
> 
> lxc.cgroup2.devices.allow: c 10:200 rwm lxc.mount.entry: /dev/net dev/net none bind,create=dir

Hi, do you mind sharing how to solve this in a Debian system (your client)?

**Comment by nelsonpecora** [comment]
@Polv89 or @pbassut silly linux question, but I'm having the same issues running Pop! OS (basically Ubuntu) and I'm not sure where to go looking for the `container.conf` mentioned. Do either of you have pointers?

**Comment by radiogena** [comment]
> container.conf

Usually /etc/pve/nodes/xxx/xxx.conf

**Comment by vintalie** [comment]
the @Polv89 solution work in my proxmox, this script makes tasks easy
echo "lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir" >> /etc/pve/nodes/{node-name}/lxc/{container-name}.conf

example:
```
echo "lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir" >> /etc/pve/nodes/cortex/lxc/100.conf
```

thats appear to be a extra configuration required by the lxc's containers, but tailsacle do not quote in anyone article (or i dont found...)

**Comment by donnimsipa** [comment]
> I solved adding these lines to the container.conf file
> 
> lxc.cgroup2.devices.allow: c 10:200 rwm
> lxc.mount.entry: /dev/net dev/net none bind,create=dir

Hi, just wanted to chime in—I'm experiencing the same issue in 2026, but thankfully I found the solution posted by @Polv89 which worked perfectly for my setup. Thanks !
