### ISSUE TITLE
FR: Tailscale subcommand hostname

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#6943]
### What are you trying to do?

CMD: `tailscale host` && `tailscale hostname`

For some devices, I have a repetitive hostname e.g. raspberrypi3bplus. While that is not supposed to happen on a physical network - and in my case it does - my networks spend more than 1 physical network and one tailnet. The purpose of this command is the reverse of the `tailscale ip` cmd. While the device's hostname may be raspberrypi3bplus the tailnet auto-hostname would be raspberrypi3bplus-1 and so forth. This hostname (raspberrypi3bplus-1) would be returned for use in scripts in my case but can be used elsewhere. The idea being I want a script deployed on my devices and to run on specific hosts even though they have the same physical hostname but different tailscale hostnames. So in the end this is useful for device management and automation on a scripting level.

  

### What is the impact of not solving this?

`tailscale status  | head -1 | awk '{print $2}'` which is subject to change

**Comment by bradfitz** [comment]
This is not subject to change:

```
$ tailscale status --json | jq -r .Self.DNSName
you.foo.ts.net.
```

Does that work?

**Comment by charlieporth1** [comment]
It does
