### ISSUE TITLE
FR: Add GUI for linux

### ISSUE THREAD

**Issue by NickCarneiro** [tailscale/tailscale#6947]
### What are you trying to do?

I want to know if I'm connected by glancing at an icon in the system tray. I don't want to have to type a command.

### How should we solve this?

Copy the mac GUI functionality to Ubuntu.

### What is the impact of not solving this?

I have to run a command several times per day to connect and disconnect.

**Comment by bradfitz** [comment]
There are a few out there:

* GNOME Shell: https://extensions.gnome.org/extension/5112/tailscale-status/
* https://github.com/mattn/tailscale-systray

Which desktop environment do you use?

**Comment by NickCarneiro** [comment]
Thanks, Brad. Will give the first one a spin. Running GNOME on Ubuntu 22.04.
