### ISSUE TITLE
Delta Airlines New Topology

### ISSUE THREAD

**Issue by gabefair** [tailscale/tailscale#6949]
### What is the issue?

Delta Airlines is rolling out free WiFi to it's USA Domestic flights. When using this WiFi tailscale is able to connect to the hello service and authenticate however traffic to devices will time out.

### Steps to reproduce

Fly Delta, new free WiFi is available to all seats. Open and try to use Tailscale.

### OS

macOS, Android

### OS version

Ventura Version 13.1 (22C65), Android 12

### Tailscale version

1.34.2

### Bug report

-Android-
BUG-1045746989f37b6ef177ee093e4f981ec2b8ea20492e4bcfb99a664677d6f823-20230113133237Z-0231180d62142994

-MacOS-
BUG-2f41a36f17e6743e116d2821af142736205639fb2d53095365cdca0e2103af51-20230113134314Z-315572e970ebd0f3

**Comment by DentonGentry** [comment]
Without Tailscale, is there a captive portal where it asks you to agree to terms and click a button or something?

**Comment by gabefair** [comment]
Yes. I'm an idiot. lol. Sorry to bother ya'll

**Comment by DentonGentry** [comment]
Oh, we definitely want Tailscale to better handle captive portal interstitials. Right now it ends up hiding them altogether. We've added a `/generate_204` handler in the DERP servers, resembling the mechanism which Chrome uses, but it isn't fully working yet. The effort is being tracked in https://github.com/tailscale/tailscale/issues/1634.

Dup of https://github.com/tailscale/tailscale/issues/1634
