### ISSUE TITLE
serve: add user identity header when used as an HTTP server

### ISSUE THREAD

**Issue by shayne** [tailscale/tailscale#6954]
When running using `serve` as an HTTP server we should add a header (name/value TBD) that passes along user identity.

This was discussed internally (https://tailscale.slack.com/archives/CQ5SPRTV4/p1672864924006679?thread_ts=1672855409.699419&cid=CQ5SPRTV4).

**Comment by Xe** [comment]
Bikeshed:

```http
Server: tailscaled
```

**Comment by soniaappasamy** [comment]
[e1cdcf7](https://github.com/tailscale/tailscale/commit/e1cdcf770803090d1dd451e4c748792082eb1fec) added two new headers
* `Tailscale-User-Login`: Filled with requester's login name.
* `Tailscale-User-Name`: Filled with requester's display name.

Follow-up coming to include a `Tailscale-Headers-Info` disclaimer header with link to docs explaining these headers, their values, and security considerations around usage.

**Comment by soniaappasamy** [comment]
Closing this out, new headers released in 1.44. https://tailscale.com/s/serve-headers
