### ISSUE TITLE
[macOS][UI] Exit Nodes - Tapping None Does Not Deselect Exit Node

### ISSUE THREAD

**Issue by gabekassel** [tailscale/tailscale#6962]
### What is the issue?

Tapping `None` in list of exit nodes does not de-select the currently selected exit node. Instead, re-clicking on the current exit node de-selects it. 

### Steps to reproduce

Set node as exit node. Tap `None` to de-select exit node. 

### OS version

Ventura 13.1

### Tailscale version

1.34.2

**Comment by bradfitz** [comment]
cc @mihaip

**Comment by mihaip** [comment]
I'm not able to reproduce this. Could you record a video of the behavior and send a bug report (option-click on the Tailscale menu and then Debug -> Bug Report…)?

**Comment by DentonGentry** [comment]
ETIMEDOUT. If this is still a problem please reopen the bug.
