### ISSUE TITLE
Split DNS not working reliably on macOS after resume from sleep

### ISSUE THREAD

**Issue by rhjensen79** [tailscale/tailscale#6963]
### What is the issue?

I used to be able to run my Tailscale connection, alongside my corporate VPN, without them interfering with each others.
This has stopped working.
So now i have to run my Tailscale disconnected, until i need it. 

### Steps to reproduce

With tailscale not connected : ping fqdn on corp network.
See it responds

connect Tailscale.
Ping again, and see it returns "cannot resolve fqdn: Unknown host"

### Are there any recent changes that introduced the issue?

Latest version of Tailscale. 
Might have been there for a couple of minor versions.

### OS

macOS

### OS version

Latest

### Tailscale version

1.34.2

**Comment by bradfitz** [comment]
There's no information here from which we can debug or help.

Which VPN? Got a "tailscale bugreport"?

**Comment by rhjensen79** [comment]
@bradfitz you are 100% correct.  I made quite a few assumptions, and did not provide enough details. Sorry about that.

Bugreport : BUG-e94099020045c6c21e1bc322865451322b5ea0806d4cb527561e62fc10e94451-20230114204056Z-83f98a8ac9cadd3f

The VPN i'm currently using for work, is a Globalprotect v 5.2.12-26.

It looks like, that when enabling Tailscale, that the local DNS server, does not resolve any requests from the DNS servers, provided by the GlobalConnect VPN.

I just did another test. 
Note i have replaced the dns name with xxx, since it's an internal work name

1. With tailscale enabled :
`╰─ nslookup xxx                                                                                                                                                  ─╯
Server:		100.100.100.100
Address:	100.100.100.100#53

Non-authoritative answer:
*** Can't find xxx: No answer`

2. With Tailscale disconnected (still running):
`╰─ nslookup xxx                                                                                                                                                  ─╯
Server:		10.93.9.100
Address:	10.93.9.100#53

Non-authoritative answer:
Name:	xxx
Address: 10.187.65.64`

3. An external url, outside Tailscale and VPN for referrence.
`╰─ nslookup www.dr.dk                                                                                                                                                       ─╯
Server:		100.100.100.100
Address:	100.100.100.100#53

Non-authoritative answer:
www.dr.dk	canonical name = www.dr.dk-v1.edgekey.net.
www.dr.dk-v1.edgekey.net	canonical name = e117571.dscb.akamaiedge.net.
Name:	e117571.dscb.akamaiedge.net
Address: 88.221.104.144
Name:	e117571.dscb.akamaiedge.net
Address: 88.221.104.82`

Hope this provides enough info to start trubleshooting/debugging.

**Comment by zcutlip** [comment]
I'm experiencing the same thing.

In addition, even without a second VPN connected, Tailscale now takes over all VPN resolution which is a privacy issue.

This may be a related issue:
https://github.com/tailscale/tailscale/issues/6734

**Comment by rhjensen79** [comment]
Just tested with latest version of the OSX client 1.36.0
And now the problem seam have disappeared. 

Before i close this, can anybody confirm, that there has been a change ?

**Comment by rhjensen79** [comment]
I take it back. It worked for some time, but now it stopped again. 
Could be related to putting my macbook to sleep and waking up, since it's not always happeling to begin with.

**Comment by andrewmzhang** [comment]
I appear to have the same issue.

**Comment by rhjensen79** [comment]
Just found out, that my collegaue running version 1.28 on his Mac, does not have the same problem.
He has the same settings as me. Only difference is the tailscale version.

I have upgraded to 1.40 and the problem stil persist.

**Comment by miroslavbucek** [comment]
I have a similar problem. I use a local .mb domain and a dnsmasq server. But Split DNS after waking up Mac mini which is on 10GbE LAN is not working. I just have to manually restart Tailscale and then everything works without any problems.

cat dnsmasq.conf

#Define Port
port=53
domain-needed
bogus-priv

# platnost TTL je 6 hodin
#max-cache-ttl=21600

#dont use hosts nameservers
no-resolv

# zkouším, jestli je potřeba, ale asi není
#expand-hosts

strict-order
#Use the default nameservers
server=1.1.1.1
server=9.9.9.11

#explicitly define host-ip mappings
address=/.mb/100.96.56.13

**Comment by MitchTalmadge** [comment]
I am having the same issue on MacOS Sequoia on a MacBook Pro M2 Max. Very often when I wake my computer from sleep, all DNS stops working until I disconnect and re-connect Tailscale. I am using 1.74.0 from the App Store. Please let me know what debugging info would be helpful and I will provide it.

**Comment by agottardo** [comment]
@MitchTalmadge please update to v1.76.0 released yesterday. A bug fix went in that could have solved this (see the changelog for more details).

**Comment by MitchTalmadge** [comment]
@agottardo Thank you, I didn't realize it was not updated. I moved to the standalone (not App Store) version on 1.76.0 and have had no more issues. Thanks again!

**Comment by agottardo** [comment]
I'll be closing this because we're fairly confident that v1.76.0 has addressed the issue. If you still notice issues with sleep-related behaviors and DNS, please mention me here.
