### ISSUE TITLE
network speed is low when tailscale is on

### ISSUE THREAD

**Issue by sharicov** [tailscale/tailscale#6966]
### What is the issue?

when tailscale is on network speed is only up to 20MBps, without tailscale speed is 160MBps+ (2.5Gbps network).
Testing by copying file in home network.
Tailscale version 1.34.2 on both ends.
Exit node is off on both sides.
It is sufficient to exit tailscale on one of the sides to get the full speed.

**Comment by DentonGentry** [comment]
If you are connecting to the LAN IP like 192.168.x.y: is there a Tailscale subnet router with `--advertise-route=192.168.0.0/24` (or similar)? If so, the packets are traversing the tailnet and could potentially be going through relays if something unusual is going on.

----

There is a substantial throughput increase coming for the 1.36 release: https://tailscale.com/blog/throughput-improvements/
The largest gain is for Linux, but other platforms benefit to lesser extent.
It can be tried today using the unstable track: https://pkgs.tailscale.com/unstable/
This is expected to benefit subnet router performance as well, though not as much as direct connections over the tailnet.

**Comment by bradfitz** [comment]
There isn't anything specifically actionable in this issue (not even the OSes, nor bugreports), so closing it in favor of the overall meta throughput issue, #414. That's the place to subscribe to get updates on the overall performance efforts.
