### ISSUE TITLE
tsnet doesn't reconnect on restart on Windows due to `readAutoStartKey`

### ISSUE THREAD

**Issue by qur** [tailscale/tailscale#6973]
### What is the issue?

I have been working on introducing tsnet to provide provide communication for a distributed system (makes for a neat setup, thanks for creating tsnet). This has been working fine on Linux, however when running on Windows the tsnet connection is not re-established on restart - it tries to create a new connection instead of using the state to resume the initial connection, which fails because the auth key has already been used.

The issue comes down to special profile behaviour for Windows. During startup, the code below is used to get the name of the profile to load:
```go
func readAutoStartKey(store ipn.StateStore, goos string) (ipn.StateKey, error) {
        startKey := ipn.CurrentProfileStateKey
        if goos == "windows" {
                // When tailscaled runs on Windows it is not typically run unattended.
                // So we can't use the profile mechanism to load the profile at startup.
                startKey = ipn.ServerModeStartKey
        }       
        autoStartKey, err := store.ReadState(startKey)
        if err != nil && err != ipn.ErrStateNotExist {
                return "", fmt.Errorf("calling ReadState on state store: %w", err)
        }
        return ipn.StateKey(autoStartKey), nil
}
```

This then doesn't find a profile on Windows, because `CurrentProfileStateKey` has been set, but `ServerModeStartKey` hasn't. So the profile isn't loaded, and the original node key therefore is not found which then triggers the attempt to reuse the auth key to connect with the controlplane.

I have been able to work around this issue by having the application update the state file to copy the profile name from `CurrentProfileStateKey` to `ServerModeStartKey` before starting the tsnet server, but it would be nice if it would just work.

### Steps to reproduce

Happens every time the application is restarted (without the workaround), after the first time (since the first time a new connection is established using the auth key instead of reconnection from the saved profile state).

### OS

Windows

### OS version

Windows Server 2016

### Tailscale version

1.34.2

### Bug report

n/a

**Comment by Zaba** [comment]
I’ve run into this issue too while trying to use https://github.com/tailscale/caddy-tailscale on Windows.

**Comment by bradfitz** [comment]
Cc @maisem

**Comment by eric** [comment]
We've also run into this with Channels and just realized it was related to this.

@qur: Could you point to an example of how you're working around this?

**Comment by eric** [comment]
Looking at this further, if [`ForceDaemon`](https://github.com/tailscale/tailscale/blob/3e298e93804757904211e195fce97a7e6b7756d0/ipn/prefs.go#L152-L162) was set to `true` here:

https://github.com/tailscale/tailscale/blob/3e298e93804757904211e195fce97a7e6b7756d0/tsnet/tsnet.go#L557-L560

I believe it would solve this.

https://github.com/tailscale/tailscale/blob/3e298e93804757904211e195fce97a7e6b7756d0/ipn/prefs.go#L152-L162

**Comment by eric** [comment]
We figured out a workaround here:

``` go
        s := new(tsnet.Server)
        # s.Dir = ...
        # s.Logf = ...
        # ...
	if runtime.GOOS == "windows" {
		var err error
		stateFile := filepath.Join(s.Dir, "tailscaled.state")
		s.Store, err = store.New(s.Logf, stateFile)

		currentProfileKey, err := s.Store.ReadState(ipn.CurrentProfileStateKey)
		if err == nil {
			s.Store.WriteState(ipn.ServerModeStartKey, []byte(currentProfileKey))
		}
	}
```
