### ISSUE TITLE
Tailscale prevents monitor on Windows from going into standby?

### ISSUE THREAD

**Issue by Sawtaytoes** [tailscale/tailscale#6974]
### What is the issue?

I have Tailscale on two Windows machines, and on one of them, it prevents it from going into power-save. Even closing the app doesn't let power-save occur anymore.

Both machines are on Windows 11 64-bit 22H2 running the latest Tailscale client `1.34.2`, but this issue also occurred in `1.34.1`.

One of them is a desktop, the other is a tablet.

With my desktop, I lock it and leave it. That's where I notice the issue as the monitor always shows the lock screen and never goes into power-save or standby mode.

The tablet is put in standby when not in use, so I haven't seen the issue there.

If I don't open Tailscale, everything works normally. As soon as Tailscale is opened, that's when I notice the issue.

### Steps to reproduce

1. Download Tailscale.
2. Install Tailscale.
3. Connect Tailscale to network.
4. Lock Windows `[WIN][L]`.
5. Leave for longer than the 1min it takes for the monitor to into standby.
6. Monitor is still on the Lock screen and hasn't gone into standby.

### Are there any recent changes that introduced the issue?

Nothing recent. I only just recently installed Tailscale when it was `1.34.1`, and the `1.34.2` update hasn't fixed it.

### OS

Windows

### OS version

Windows 11 64-bit 22H2

### Tailscale version

1.34.2

### Bug report

BUG-f328ba4a480773538dfa469046f82ef72781b98af7c84a55182141028be8700a-20230116022328Z-38e693efca20a7c4

**Comment by DentonGentry** [comment]
I'm having trouble seeing how Tailscale could be keeping the monitor on. Is there an indirect path, like more network traffic leading to more power consumption leading Windows to decide that the workstation isn't idle?

**Comment by Sawtaytoes** [comment]
As far as I've seen, I have nothing running but the Tailscale app. Maybe a browser window to my NAS (local). I thought it was weird too. At first, I thought it was because I installed Resilio-Sync, but it's been uninstalled.

After much testing, it was Tailscale. So long as I don't open it, everything's fine.

It's not setup as an Exit Node either:
![image](https://user-images.githubusercontent.com/3948069/212588046-2392dd66-50fd-47bc-8dec-39a7cdfdad42.png)

Is there anything I could check?

**Comment by bradfitz** [comment]
I also don't see how we could be doing that. We're certainly not trying (which is why #3574 is open, to consider trying to add support for doing it intentionally)

As Administrator, what do you see when you run in cmd.exe:

```
C:\WINDOWS\system32>powercfg /requests
DISPLAY:
None.

SYSTEM:
None.

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.


C:\WINDOWS\system32>powercfg /waketimers
There are no active wake timers in the system.
```

Any changes to that or similar queries when Tailscale is on vs off?

If so, we should figure out which process is responsible: the system tray GUI or the Windows service.

As admin, you can run "net stop Tailscale" to stop the Tailscale service and see if your things sleep again with just the GUI running.

Then "net start Tailscale" to bring it back.

Then you can enable "Unattended mode" in the GUI and then quit the GUI to only test the service running without the GUI.

**Comment by Sawtaytoes** [comment]
This Signal one showed, but hasn't shown since.
```sh
C:\Windows\System32>powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume3\Users\satur\AppData\Local\Programs\signal-desktop\Signal.exe
Electron
[PROCESS] \Device\HarddiskVolume3\Users\satur\AppData\Local\Programs\signal-desktop\Signal.exe
Video Wake Lock

SYSTEM:
[DRIVER] Legacy Kernel Caller
[DRIVER] Legacy Kernel Caller

AWAYMODE:
None.

EXECUTION:
[PROCESS] \Device\HarddiskVolume3\Users\satur\AppData\Local\Programs\signal-desktop\Signal.exe
Playing audio

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```

This is what it looks like now.
```sh
C:\Windows\System32>powercfg /requests
DISPLAY:
None.

SYSTEM:
None.

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```
```sh
C:\Windows\System32>powercfg /waketimers
Timer set by [SERVICE] \Device\HarddiskVolume3\Windows\System32\svchost.exe (SystemEventsBroker) expires at 11:08:08 AM on 1/17/2023.
  Reason: Windows will execute 'NT TASK\HP\HP Print Scan Doctor\Printer Health Monitor' scheduled task that requested waking the computer.
```

I just removed the HP drivers and Windows Store app as I no longer have an HP printer, but that's still showing. Might go away after a restart.

---

I had uninstalled Tailscale for a few weeks and reinstalled it a few days ago. After doing so, I noticed this monitor standby issue again. That's why I decided to file a bug report.

Yet, last night, the monitors went into standby.

What I did last night:
1. Left Tailscale on.
2. Connected to the Dashboard of two TrueNAS systems and left the web GUI open. One of them was using a Tailscale DNS address. If I kill Tailscale, it immediately loses the Dashboard, so I know this is keeping an active connection open.

Not sure why everything was fine last night. When I've noticed this problem in the past, I _didn't_ leave the web GUI open, but that could be coincidence.

**Comment by bradfitz** [comment]
I'm not seeing any smoking guns here.

@dblohm7, any ideas for debugging options?

**Comment by dblohm7** [comment]
No smoking guns. I did read [this document](https://learn.microsoft.com/en-us/windows/win32/power/system-sleep-criteria) about sleep criteria and noticed the following (emphasis mine):

> As long as the system determines that there is user or application activity, it will not enter sleep. The system can detect certain activities, such as user input or **network communications**.

Of course, the next question is how that works and whether it is configurable. That part is proving to be more elusive.

**Comment by dblohm7** [comment]
I can't rule out a wintun bug either. I'm wading into that a bit to see if I can figure out what's going on.

**Comment by Sawtaytoes** [comment]
It happened again today. Did `powercfg /requests` and got `"None."` for everything.

I do have a backup robocopy task that runs on idle, but as far as I know, once it's done, it's done. And when there are no changes (like today), the task takes 5-10 seconds to complete.

**Comment by Sawtaytoes** [comment]
Looks like Tailscale isn't even open today. Gonna close this issue.

Maybe it was coincidence that it happened before only with Tailscale.
