### ISSUE TITLE
Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=51": context deadline exceeded

### ISSUE THREAD

**Issue by aaddame** [tailscale/tailscale#6976]
### What is the issue?

tailscale fails to start

### Steps to reproduce

I have two docker instances running tailscale.
One has version 1.26.0 and runs without problems
The other has version 1.34.2 and gives above error

### OS

Linux

### OS version

alpine 3.17.0

### Tailscale version

1.34.2

### Bug report

BUG-49de1ec26cc88380f07a5563a7b270d3fda16364d5c4e954990bc7cb7c9db046-20230116115851Z-27a14e4b7360a583

**Comment by DentonGentry** [comment]
It cannot reach controlplane.tailscale.com, and times out. You'll need to fix that.

**Comment by aaddame** [comment]
But it works in the other container

**Comment by bradfitz** [comment]
Any other HTTP proxies or VPNs involved?

That `tailscale bugreport`'s telemetry never made it to us. How did you generate it?

Can you share the docker container logs of both the working and non-working versions?

**Comment by aaddame** [comment]
No proxies or vpn involved
generated by **tailscale  bugreport**
regenerated BUG-3bd4b626fe052062c6f72ef1d42ce9c26f51ffad654915416559962b2a3071a2-20230117074758Z-c0d5b0f00c300bc1
[tailscale_fails_logs.txt](https://github.com/tailscale/tailscale/files/10432533/tailscale_fails_logs.txt)
[tailscale_starts_logs.txt](https://github.com/tailscale/tailscale/files/10432534/tailscale_starts_logs.txt)

**Comment by OrganicKobze** [comment]
I am also getting the same error message on 1.34.2 running on Windows, no VPN or proxy involved. Not sure if that's helpful!

**Comment by aaddame** [comment]
The file I uploaded to show the failing one wasn't complete . Here is a new one

**Comment by aaddame** [comment]
In the failing file I see the following msg:


**2023/01/18 12:37:02 pm: migrating "_daemon" profile to new format**

After that the logs difffer much

**Comment by paulhybryant** [comment]
I ran into the same issue and I am using vpn (because tailscale.com is blocked from my location)

**Comment by DentonGentry** [comment]
I think this might be a symptom of [#4845](https://github.com/tailscale/tailscale/issues/4845) and [#6110](https://github.com/tailscale/tailscale/issues/6110)

Tailscale 1.42.0 contains [#8008](https://github.com/tailscale/tailscale/pull/8008), which is believed to resolve it.
Please post if you see further occurrences using Tailscale 1.42.0 or later.
