### ISSUE TITLE
hostinfo: add support for detecting Scoop installations

### ISSUE THREAD

**Issue by shayne** [tailscale/tailscale#6988]
We should be able to look at the installation directory since [Scoop](https://scoop.sh) installs everything in `%userprofile%\scoop`.

_Scoop is a command-line installer for Windows_

**Comment by bradfitz** [comment]
Want to get this into 1.36.0 since https://tailscale.com/changelog/#2023-01-17-service (https://github.com/ScoopInstaller/Extras/blob/master/bucket/tailscale.json) is in?

Should be a few lines very similar to Chocolatey detection.
