### ISSUE TITLE
Local Network not accessible w/ exit node?

### ISSUE THREAD

**Issue by fisdpwn** [tailscale/tailscale#6994]
### What is the issue?

Currently trying to run an exit node on a Ubuntu machine. Machine is able to ping 10.133.1.180 (local address for a class A network). I am attempting to make an exit node with the following command but none of my vpn clients seem to be able to access 10.133.1.180.
```
C:\Windows\System32>ping 10.133.1.181

Pinging 10.133.1.181 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 10.133.1.181:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```
Node creation command:
```bash
sudo tailscale up  --ssh --reset --advertise-exit-node
```
Node is up with all routes approved, and ssh works perfectly. Outside internet traffic is correct with my Ip the same as the target network. Allow local network traffic on the client is on. What am I missing and why is the connection not working correctly with network internal Ip's?

### OS

Linux, Windows

### OS version

Ubuntu 18.04

### Tailscale version

1.34.2

### Bug report

BUG-388c8da7141ac08d9ab3af7d869f87a0947b4bd2712cb01a70e372c38594fbdb-20230118033605Z-e6c2b19abd817a84

**Comment by DentonGentry** [comment]
Exit nodes advertise their connection to the Internet to public IP addresses. They do not advertise their local LAN, it is expected that remote Tailscale clients will not be able to connect to LAN addresses.

**Comment by scratchmex** [comment]
is this still the case? even though the exit node it's expected to advertise `0.0.0.0`? I suppose the tailscaled is dropping packets not to public internet, cause the client is sending them to the exit node. Will be nice that we have a way of using the exit node fully, as if you were the exit node, network wise; basically accepting every packet from the client -> exit node path
