### ISSUE TITLE
ACL tags are removed upon reauthentication

### ISSUE THREAD

**Issue by Maffsie** [tailscale/tailscale#6997]
### What is the issue?

When a machine which has previously been assigned ACL tags through the admin interface has its key expire and is reauthenticated, all assigned tags are lost, and must be manually reassigned.

### Steps to reproduce

* Join a machine to a tailnet
* Assign any tag to that machine
* Wait for the machine's key to expire
* Reauthenticate through tailscale
* Observe that the assigned tag has been lost

### OS

Linux, macOS, Windows, iOS, Other

### OS version

iOS 16.3, macOS 12.5.1, Windows 10, Windows 11, QNAP QTS (version unknown), Alpine Linux 3.17.1, FreeBSD 13.1-RELEASE-p2, OpenWRT 19.x thru 21.x

### Tailscale version

1.32 & 1.34

### Bug report

BUG-daea840118716b6ebfffbe1135d9a77e7221a615e9d633f58b26bd7f84276522-20230118124725Z-b1bbaf4fff3e5df6

**Comment by DentonGentry** [comment]
As described, this is working as intended. It is possible to reauthenticate a formerly tagged machine to turn it back into a user-owned machine. To renew the node key of a tagged machine one can:
- from the cli: `tailscale up --force-reauth --advertise-tags=tag1,tag2`
    For Linux and Windows, the `tailscale` CLI command is installed in the PATH. For macOS, use `/Applications/Tailscale.app/Contents/MacOS/Tailscale up --force-reauth --advertise-tags=tag1,tag2`
- use an [authkey](https://tailscale.com/kb/1085/auth-keys/) with the tags populated: `tailscale up --force-reauth --authkey=tskey-...`
    FYI: as tagged machines are generally servers, nodes created using an authkey with Tags are set to never expire their node keys by default.
- reauthenticate as a user and apply the tags again in the admin panel.
