### ISSUE TITLE
module name "tailscale.com" ?

### ISSUE THREAD

**Issue by sylr** [tailscale/tailscale#7]
https://github.com/tailscale/tailscale/blob/d539a950ca4a668101940269139a1557cf5cbb0a/go.mod#L1

Is that on purpose ?

Shouldn't it rather be `module github.com/tailscale/tailscale` ?

**Comment by bradfitz** [comment]
It's intentional.

The import path is "tailscale.com" and the Go <meta> tags are present at https://tailscale.com/?go-get=1

**Comment by bradfitz** [comment]
I added import comments in https://github.com/tailscale/tailscale/commit/516a15ee588090221fabfa3c6eeadf36665a7e26
