### ISSUE TITLE
Tailscale + PiHole not working

### ISSUE THREAD

**Issue by Slopz** [tailscale/tailscale#7001]
### What is the issue?

I've tried everything I could think of. Googled like crazy. 
I set up tailscale and connected all of my devices including 2 PiHole installs on 2 VPSes.
I set the DNS addresses to those 2 PiHoles in tailscale admin settings and on my devices.
I port forwarded 41641 UDP on both VPSes.
Set UFW/iptables to allow all traffic from and to tailscale0.

My Android phone will work most of the time with tailscale + pihole, but if I leave it alone for a couple of minutes and then try browsing the internet, it will take a few seconds before it starts getting DNS replies from PiHole...I'm guessing it has to do something with connection timeout and handshakes? 

The Windows machine on the other hand will not work at all.
```
nslookup google.com

Server:  pi.hole
Address:  100.79.73.47

Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:4001:80e::200e
          142.250.186.78
```

pihole.log
```
Jan 18 19:43:21: query[A] google.com from 100.117.182.117
Jan 18 19:43:21: cached google.com is 142.250.186.78
Jan 18 19:43:21: query[AAAA] google.com from 100.117.182.117
Jan 18 19:43:21: cached google.com is 2a00:1450:4001:80e::200e
```

```
ping google.com
Ping request could not find host google.com. Please check the name and try again.
```

That's about it. 
I have tried with both Magic DNS enabled and disabled (currently disabled)
I set the both DNS addresses in Windows settings to both PiHoles, and set the both PiHoles as DNS servers in tailscale admin settings.
Previously I used Wireguard to connect to those same PiHoles and it worked fine. I also reconfigured both PiHoles with tailscale0 as the interface and even set "Permit all origins" but still no dice. 
If I disable tailscale and turn back on the old Wireguard tunnel to a 3rd PiHole on a 3rd VPS, it works just fine.
I really don't know what to do anymore. Help!

### Steps to reproduce

Install Tailscale on all devices
Install PiHole and set interface to tailscale0, set permit all origins and set UFW and iptables to allow all traffic from and to tailscale0
Set DNS servers in tailscale admin settings to PiHole addresses
Set DNS servers on Android and Windows to PiHole addresses

### OS

Windows, Android

### OS version

Windows 11 22H2, Android 12

### Tailscale version

1.34.2

### Bug report

BUG-09e503d50672acab87e2603f26f540a5893cdb6687a34134d16f2e8d7a30b7eb-20230118200737Z-6cd8d6e3c9cb9604

**Comment by DentonGentry** [comment]
Around the time of the bugreport, the Windows system receives an empty DNS config:

```
2023-01-18 20:23:17.0629373 +0000 UTC: dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2023-01-18 20:23:17.0629373 +0000 UTC: dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
2023-01-18 20:23:17.0629373 +0000 UTC: dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
```

It isn't immediately clear why, but does match the reported symptom of not using the PiHole for DNS.

**Comment by kelivel** [comment]
> Install PiHole and set interface to tailscale0

@Slopz Can you share a bit more about what you set up here? Is the Windows machine remote or on the same local network as the Pi?

**Comment by kelivel** [comment]
Closing this one as there has been no reply in a few weeks. If this issue returns, please reach out to our support team using our [contact form](http://www.tailscale.com/support) and include a bugreport. We can take a closer look togther. Thanks!
