### ISSUE TITLE
Running tailscale with '--accept-routes' results in Abuse Message by ISP

### ISSUE THREAD

**Issue by Schokobecher** [tailscale/tailscale#7002]
### What is the issue?

After doing a fresh tailscale installation on a Debian 10 Buster bare-metal server (Proxmox host), I received an Abuse Message from my ISP (Hetzner.de) labeled as `Netscan detected`

All the _scanned_ hosts are indeed hosts of my tailnet (due to the number of subnet routers, I'm using headscale); the _scan_ originated with the public IPv4, and the tailscale port

> ##########################################################################
> #               Netscan detected from host    49.XX.XXX.XX4               #
> ##########################################################################
> 
> time                protocol src_ip src_port          dest_ip dest_port
> ---------------------------------------------------------------------------
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.61.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.62.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.63.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.64.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.65.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.66.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.67.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.68.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.69.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.70.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.71.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.72.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.2.73.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.2.218.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.5.37.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.5.224.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.6.184.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>        10.9.8.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.11.12.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.14.14.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.14.26.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.15.12.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.17.150.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.18.108.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.19.125.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.21.169.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.30.7.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.30.8.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.33.90.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.34.10.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.34.182.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.37.101.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.50.102.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.53.232.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.58.97.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.59.183.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.70.79.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.72.7.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.74.127.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.78.36.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.80.66.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.83.81.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.87.235.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.88.253.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.91.193.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.94.133.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.95.203.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>       10.97.2.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.97.54.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      10.98.78.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.102.17.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.105.71.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.117.26.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.117.145.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.120.91.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.122.222.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.123.46.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.128.127.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.140.126.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.149.247.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.151.50.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.157.149.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.158.21.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.158.85.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.160.243.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.167.203.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.167.213.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.175.150.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.177.65.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.177.254.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.178.161.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.178.182.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.178.252.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.182.164.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.184.176.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.184.232.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.188.232.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.189.14.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.193.11.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.195.113.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.196.252.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.201.104.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.205.205.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.210.19.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.210.163.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.216.197.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.217.15.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.219.81.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.219.195.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.220.237.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.229.56.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     10.233.61.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.235.160.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    10.238.238.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>      172.16.2.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     172.16.35.2 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     192.168.0.5 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>     192.168.3.9 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    192.168.3.10 41641
> Wed Jan 18 16:06:09 2023 UDP    49.XX.XXX.XX4 41641 =>    192.168.3.14 41641

I would like to know why those private sub-nets would leave via the default route/nic and not use the tailscale interface.

### Steps to reproduce

1. Install Debian Buster
2. Install Proxmox
3. Setup routing similar to the attached config (additional subnets from Hetzner + private IPs):
4. Run `tailscale up --login-server=https://custom.server.tld --accept-routes` 
5. Wait for the Hetzner monitoring to trigger
[interfaces.txt](https://github.com/tailscale/tailscale/files/10450304/interfaces.txt)

### Are there any recent changes that introduced the issue?

None

### OS

Linux

### OS version

Debian 10

### Tailscale version

1.34.2

### Bug report

BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

**Comment by bradfitz** [comment]
> BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

Sorry, but running with `--no-logs-no-support` means we can't provide support.

If you're a customer, please reach out to support@tailscale.com and provide your account info.

But otherwise there's no information in this bug report from which we can help you.

**Comment by Schokobecher** [comment]
> maybe because you're using Headscale 
Correct. Otherwise, I would be happy to create a bug report. But Running a high number of subnet routers (>50) is sadly not feasible.

So the behavior of looking for the RFC1918 addresses via the default route is expected? I've added hosts on Linode, DigitalOcean, and OVH to my tailnet before and none of the sent me an Abuse Message about this.
I had to remove the one at Hetzner since they otherwise would terminate the server.


> Please make sure that packages with private sub-nets as destination do not leave your external interface as those addresses are not allowed to be routed on the Internet. Here is a brief list of all private sub nets

**Comment by bradfitz** [comment]
> So the behavior of looking for the RFC1918 addresses via the default route is expected? 

That's a totally valid and not uncommon thing to do.

Imagine two corporate offices with different RFC1918 ranges per office. Each computer in that office has a default route to their office router, and the two office routers route to each other.

I think the real problem is that Hetzner cares and puts you on a VLAN with other customers. They should drop/ignore packets to RFC1918 addresses out that interface if they're not for your own VLAN.

**Comment by bradfitz** [comment]
Meanwhile your best option is to do your own filtering on the machine with a new iptables/etc rule that blocks some outgoing traffic to certain ranges on certain interfaces.

**Comment by Schokobecher** [comment]
Yep, I figured so much; if anyone finds this issue:


```
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 0.0.0.0/8 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 10.0.0.0/8 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 100.64.0.0/10 -j DROP
iptables -A OUTPUT- o $publiciface -p udp -s 0/0 -d 169.254.0.0/16 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 172.16.0.0/12 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 192.0.0.0/24 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 192.0.2.0/24 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 192.88.99.0/24 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 192.168.0.0/16 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 198.18.0.0/15 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 198.51.100.0/24 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 203.0.113.0/24 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 224.0.0.0/4 -j DROP
iptables -A OUTPUT -o $publiciface -p udp -s 0/0 -d 240.0.0.0/4 -j DROP
```

Should block all reserved ranges on your WAN-facing interface.

Thanks @bradfitz, for clearing things up :)

**Comment by hashworks** [comment]
It would be useful if this was configurable. But yeah, firewall block works just as well. Same thing for nftables:

```
table inet filter {
	set RFC1918v4 {
		type ipv4_addr
		flags interval
		elements = { 10.0.0.0/8, 169.254.0.0/16,
			    172.16.0.0/12, 192.0.0.0/24,
			    192.0.2.0/24, 192.88.99.0/24,
			    192.168.0.0/16, 198.18.0.0/15,
			    198.51.100.0/24, 203.0.113.0/24,
			    224.0.0.0/4, 240.0.0.0/4 }
	}
		
	# [...]

	chain output {
		type filter hook output priority filter
		
		# [...]

		oif "wan0" ip daddr @RFC1918v4 drop comment "Drop traffic to private addresses over wan interface"
		oif "wan0" ip daddr 100.64.0.0/10 drop comment "Drop traffic to tailscale addresses over wan interface"
	}
}
