### ISSUE TITLE
FR: Taildrop should de-duplicate files

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#7013]
### What are you trying to do?

I sent a large number of photos from iPhone to Windows desktop, partway through it failed (unsure why; phone fell asleep or I walked out of WiFi range).

Rather than figure out which ones were sent, I resent the entire list of photos again. This resulted in duplicate files being stored (e.g., "IMG_9316.jpg" and "IMG_9316 (2).jpg").

### How should we solve this?

The client should check if a file already exists with the same name. If the contents of the file are identical to the file being received, ignore the file.

Alternatively, the transmitter could send a manifest of file names and content hashes, the receiver responds with which ones it already has, and the transmitter elides those from being sent.

### What is the impact of not solving this?

Manual effort deleting duplicated files.

**Comment by rhealitycheck** [comment]
https://github.com/tailscale/tailscale/pull/9515 completes this request.
