### ISSUE TITLE
macOS client and admin console don't believe the key expires at the same time

### ISSUE THREAD

**Issue by mplough-kobold** [tailscale/tailscale#7022]
### What is the issue?

Relates to https://github.com/tailscale/tailscale/issues/6740 - possibly the cause, possibly a different issue.

This somewhat redacted screenshot shows the admin console saying that the key expired 12 minutes ago and the client saying that the key expires in 38 minutes.

<img width="941" alt="Screenshot 2023-01-20 at 10 21 51 AM" src="https://user-images.githubusercontent.com/69480843/213737438-4bd86487-292c-49c9-a544-da5b5fe85c1a.png">

### Steps to reproduce

1. Connect to Tailscale.
1. Wait for the key to almost expire according to the desktop client.
1. View the admin console's opinion of the key expiry.

Notice that the key supposedly expires at two different times.

### Are there any recent changes that introduced the issue?

No.

### OS

macOS

### OS version

13.1

### Tailscale version

Version 1.34.2 (App Store)

### Bug report

BUG-0ee3dcf9a95b668a1d586dab90adcd3c364ad353b8c5505bae40dd03b3db96ec-20230120152543Z-c47d8cabc3f1c8e2

**Comment by bradfitz** [comment]
Is your clock off?

**Comment by mplough-kobold** [comment]
If only it were, then things would be easy -- my clock is correct, though.

**Comment by bradfitz** [comment]
cc @mihaip @nickoneill ... when does the GUI refresh that label?

**Comment by mihaip** [comment]
As far as I can tell the Mac client only refreshes this when the "self node" changes, so there's no timer to keep the relative date up to date: https://github.com/tailscale/corp/blob/546485891b2823df199ee62d57b1c05d0eff6655/xcode/IPN/UI/macOS/MenuGroups/ConnectSection.swift#L39-L74

**Comment by bradfitz** [comment]
Oh, well, that's a problem then. :)

That string should be recomputed whenever the menu is opened (or even ideally live, while the menu is open). We shouldn't need to push anything from either the server to tailscaled or even over the local IPN bus.

**Comment by mihaip** [comment]
We've changed it to recompute the relative time whenever the menu is open, the change should be picked up in the next stable release (1.36).

**Comment by mplough-kobold** [comment]
🎉 Things look good on 1.36.0.  The additions to `tailscale status --json` make it easy to confirm that the client and console agree on when the key will expire.  I also did a few cycles of running a `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug set-expire --in=<duration>` command and opening the menu.  The menu now also agrees with the client and console.
