### ISSUE TITLE
FR: Easier CLI tooling for script use

### ISSUE THREAD

**Issue by fabiopedrosa** [tailscale/tailscale#7023]
### What are you trying to do?

I'm trying to log into tailscale from a docker container, and wish it was simpler.

```
tailscaled --tun=userspace-networking --socks5-server=localhost:1055 2>~/tailscaled.log 1>&2 &

echo "Waiting for Tailscale to start..."
sleep 20

echo "Authenticating tailscale..."

tailscale up --authkey="$TAILSCALE_AUTHKEY"
```

### How should we solve this?

- why can't I run tailscaled in a way that I get control back once its running on the background? (`--background` maybe?)
- is there a way i can get `tailscale` to block until the daemon is running?

### What is the impact of not solving this?

just tooling that's too hard to work with

**Comment by bradfitz** [comment]
The `tailscale` command has supported waiting for `tailscaled`'s socket to come up for quite some time but was recently broken in a refactor that went into 1.34.0.

You didn't specify the version you're using.

It's been fixed and will be in the next release.

Fixed by eec734a5787214abb98d5af3421094e56280e6ed

**Comment by bradfitz** [comment]
(Then you won't need the sleep)

**Comment by fabiopedrosa** [comment]
@bradfitz Maybe I'm missing something, but it does look like `tailscale` doesn't wait for `tailscaled` to be up?

I'm running on the latest version (1.36.0) and I can't get my unattended scripts to work flawlessly without some sleeping in between:

```bash
tailscaled --tun=userspace-networking --socks5-server=localhost:1055 2>~/tailscaled.log 1>&2 &
tailscale up --hostname=deepnote --authkey="$TAILSCALE_AUTHKEY"

<ssh into some machine>
... paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

<repeat>
... paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

<repeat>
... success


```
