### ISSUE TITLE
FR: Make signup for teams as easy as sign up for 1

### ISSUE THREAD

**Issue by freekvh** [tailscale/tailscale#7038]
### What are you trying to do?

Set up a VPN with a team

### How should we solve this?

Just let me couple all the people together I need, I don't even understand what is happening now, what does "The Team plan is not available to personal Tailscale domains." mean? I don't even want to use it for my personal domain? I feel stuck on some loop here.

### What is the impact of not solving this?

I would pay you for a great VPN service

**Comment by freekvh** [comment]
Ok, does this: "Tailscale networks are based on your email address domain name." really mean I need the same domain for my email as my client? I don't want MS365, I have partner from another company, do we really all need to sign up for MS365 to share a Tailnet? I can hardly believe it.

**Comment by DentonGentry** [comment]
gmail.com and outlook.com and hotmail.com are handled as service provider domains. Each individual user@gmail.com account gets its own tailnet. The message you're seeing sounds like trying to sign up for a multi-user tailnet using GMail.Outlook/etc. We do not currently have a way to combine multiple GMail accounts into a tailnet together.

user1@example.com and user2@example.com are two users on a multi-user tailnet. If you have a Google Workplace or Microsoft 365 or Okta identity provider, those can be used to create a multi-user tailnet.

GitHub Organizations can also be used to make a multi-user tailnet, and have the advantage of being:
- free from GitHub
- free for friends and family use for Tailscale: https://tailscale.com/blog/community-github-pricing/
- don't require everyone to share one common domain

**Comment by freekvh** [comment]
Thank you for your response. My company and all partners are for profit but if I understand you correctly I can create a free GH organization to get everyone in the same tailnet?

Or what would be the easiest to achieve this?

Right now the flow is kind of broken btw, you hook me on your great product for free, I want to start paying so I can have a tailnet with multiple people (I need a synology nas on it, an Ubuntu Nuc, 2 laptops). But then I hit a lot of "this is not possible" messages.

I just need several people (actually 2 for now) on a tailnet, they are not part of the same company so they don't have email on the same domain.

**Comment by freekvh** [comment]
Ok, I have made a GH organization, still, if I click support -> pricing -> Try the team plan, it still says "The Team plan is not available to personal Tailscale domains." 

How can I let Tailscale know I waht to use the GH organization?

**Comment by freekvh** [comment]
I just found this:

We know not all teams have shared email address domains. We’re building features to let families, friends, contractors, and companies with multiple domains to connect their devices. In the meantime, check out [machine sharing](https://tailscale.com/kb/1084/sharing). Feel free to [contact us](mailto:info@tailscale.com) if you need any help.

I guess I'll be waiting for that then. Thanx for the fast reply at least.

**Comment by freekvh** [comment]
A yes it works! Great! (Switching accounts could be made a little easier though ;) or perhaps it could be nicely integrated, like GH orgs themselves are on GH.)

I'll probably get prompted to pay as I add users i assume? I'll start doing that soon.

Thank you!
