### ISSUE TITLE
Provide a way to specify hostname from iOS app

### ISSUE THREAD

**Issue by chris-araman** [tailscale/tailscale#704]
**Is your feature request related to a problem? Please describe.**

I have configured public DNS records for each of my Tailscale nodes:
- `linux.foo.tld`
- `mac.foo.tld`
- `pi.foo.tld`
- `phone.foo.tld`

I can configure each of the Linux and macOS hosts to use their `foo.tld` hostname with Tailscale. However, the iOS app doesn't provide a way to specify its hostname. When I run `tailscale status`, I see:
```
[...] linux 100.x.x.x linux.foo.tld ...
[...] linux 100.x.x.x pi.foo.tld ...
[...] macOS 100.x.x.x mac.foo.tld ...
[...] iOS 100.x.x.x *Chriss-iPhone* ...
```

**Describe the solution you'd like**

I realize it's a small thing, and only cosmetic, but I'd prefer to see these listed using the names I've assigned to them. If the hostname at the top of the iOS app could be edited in-place, that'd be 👌🏼

**Describe alternatives you've considered**

Modifying the hostnames on the Admin Console would be a fine solution as well.

**Additional context**

N/A

**Comment by rosszurowski** [comment]
A while back we launched the ability for network admins to [edit machine names from the admin panel](https://tailscale.com/kb/1098/machine-names), which should be able to help here. Does that address this issue?

**Comment by chris-araman** [comment]
Yes. It's not exactly what I had in mind, but it meets my needs. Thanks, @rosszurowski.
