### ISSUE TITLE
FR: Android automated connect and disconnect ability

### ISSUE THREAD

**Issue by gottaloveit** [tailscale/tailscale#7048]
### What are you trying to do?

As others have submitted, automating connect and disconnect the VPN via Tasker (public access to Tailscale intents), or even home screen widgets to allow for setting up automation.  Yes, there are at least 2 previously submitted FR about this, and it seems they have been ignored.  A very significant number of VPN apps already offer this.

### How should we solve this?

I'm not by any means an expert android dev, but maybe these could be a place to start?

1. Create 2 intents that can be called externally
    1. connect intent that fires `android.net.VpnManager.startProvisionedVpnProfileSession()`
    2. disconnect intent that fires `android.net.VpnManager.stopProvisionedVpnProfile()`
2. Create widget for Home Screen
3. Tasker integration by implementing [tasker plugin](https://tasker.joaoapps.com/pluginslibrary.html) in the Tailscale app 

### What is the impact of not solving this?

manually connecting / disconnecting based on location or battery saving preferences, losing ability to have safe connection if user forgets to change connection state.

**Comment by bradfitz** [comment]
Dup of #3547. Let's just use that bug. Two open bugs for the same thing doesn't really help and is actually bad in that it splits user and developer attention.

**Comment by MohitDeshwal** [comment]
@bradfitz why #3547 is locked? 

> locked as off-topic and limited conversation to collaborators

**Comment by DentonGentry** [comment]
There were too many posts asking for status updates. We will update the bug when work begins in earnest.
