### ISSUE TITLE
FR:  The ability to install TailScale on Arch Linux that uses pacman for the package manager

### ISSUE THREAD

**Issue by wrhowell** [tailscale/tailscale#7062]
### What are you trying to do?

I run RF nodes of which some use the "HamVoip software to run.

I can't install your TailScale on it because HamVoip says that their software uses Arch Linux and uses pacman for the package manager. I haven't found a way to install it from your website.

### How should we solve this?

Develop a install method

### What is the impact of not solving this?

Losing out to the many Node operators like myself.....

**Comment by wrhowell** [comment]
So what is the method used to install this on a Raspberry Pi? Is the script located on the website available for download?


William R. Howell Sr.     Remember, Life's unexpected obstacles today are only challenges to having a better life tomorrow, William Howell, Sr. 

    On Wednesday, January 25, 2023 at 09:05:10 AM CST, Denton Gentry ***@***.***> wrote:  
 
 


The install.sh script uses pacman to install on Arch Linux.
curl -fsSL https://tailscale.com/install.sh | sh

The lines of the script which handle pacman are: https://github.com/tailscale/tailscale/blob/2adbb4863282d85f07a7d07e462a4ce87c4e4c01/scripts/installer.sh#L520

**Comment by DentonGentry** [comment]
As root on the Raspberry Pi, one would use: `curl -fsSL https://tailscale.com/install.sh | sh`

**Comment by wrhowell** [comment]
Thank you sir, I will give that a try...

William R. Howell Sr.     Remember, Life's unexpected obstacles today are only challenges to having a better life tomorrow, William Howell, Sr. 

    On Wednesday, January 25, 2023 at 07:42:32 PM CST, Denton Gentry ***@***.***> wrote:  
 
 


As root on the Raspberry Pi, one would use: curl -fsSL https://tailscale.com/install.sh | sh

**Comment by DentonGentry** [comment]
Addressed using install.sh.
