### ISSUE TITLE
iOS shortcuts - "Get status" automatically connects tunnel

### ISSUE THREAD

**Issue by Juggler00** [tailscale/tailscale#7063]
### What is the issue?

Trying the Tailscale actions in the iOS Shortcuts app. When I use the intent "Get status", Tailscale automatically connects the tunnel before providing the current status.

### Steps to reproduce

In Shortcuts app:

```
Get status

If "Connected" is 1
  Show "Tailscale is currently connected"
Otherwise
  Show "TTailscale is not connected"
End If
```
### Are there any recent changes that introduced the issue?

Introduction of Shortcuts actions.

### OS

iOS

### OS version

iOS 16.3

**Comment by mihaip** [comment]
Thanks for noticing this. I've made a fix for this, it should be picked up in the 1.36.1 maintenance release in the next week or two.
