### ISSUE TITLE
non-ephemeral Key for docker container

### ISSUE THREAD

**Issue by jshep321** [tailscale/tailscale#7070]
### What are you trying to do?

I would like to avoid key expiry after 90 days.  I configured the persistent storage but it appears that the only way to have a > 90 day docker container access is to use the URL to authenticate.  

I can set Expiry Disabled from the machine list page, but the key page states that it will expire after 90 days.  In that way this might be considered a BUG, not a feature request?

### How should we solve this?

Enable keys to persist indefinitely.

### What is the impact of not solving this?

Each docker container will need to be restarted with a new key every 90 days.

**Comment by DentonGentry** [comment]
A reusable authkey allows one to authenticate new nodes. Each new node creates a node key the first time it contacts the coordination server.

Node keys by default last 6 months but can be set to never expire. A node key set to never expire will be able to connect to the tailnet forever and never need to be re-authenticated again.

The authkey, on the other hand, expires 90 days after its creation. It will no longer be able to create new nodes after 90 days. Any nodes it has already created live on, until whenever their node key expires, but the authkey will not be able to create more nodes.

We're expecting to provide a different way to produce authkeys and API keys, described in https://github.com/tailscale/tailscale/issues/3243#issuecomment-1253946534

**Comment by jshep321** [comment]
Aha, I was conflating these two.  So in summary if I have 1) persistent storage on the docker container for the states (I do) 2) expiry disabled on the docker container and then kick it off with an auth key, the node key should last forever -- across restarts of the container/host machine.  

Testing soon...

**Comment by jshep321** [comment]
Confirmed.  Thanks for the clarification.  Interesting note that even though the docker-compose.yaml had a revoked key, it started fine after the first launch.  My assumption is that tailscale checks first for the node key and if that exists it doesn't attempt to (re-) authenticate, so that is ignored as long as a valid node key exists?

**Comment by Cp0204** [comment]
https://github.com/tailscale/tailscale/issues/4913

Use it `TS_STATE_DIR`
```
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscaledata:/var/lib/tailscale
```
