### ISSUE TITLE
FR: --snat-subnet-routes=false support for FreeBSD (pfSense/OPNsense)

### ISSUE THREAD

**Issue by tijjjy** [tailscale/tailscale#7073]
### What are you trying to do?

Currently --snat-subnet-routes=false is only available for Linux binaries, Support for FreeBSD will allow users using pfSense or OPNsense to disable snat when configuring site-to-site connections to allow for greater and fine-tuned firewall controls.

### What is the impact of not solving this?

It is not a big issue for small networks with simple site-to-site connections. People will larger networks behind each subnet router won't be able to finely tune firewall rules and ACLs and each device will only see the subnet router IP address.

### Anything else?

Support for the GUI button to disable/enable this option for pfSense is currently in the devel build but has been commented out as it is awaiting support for FreeBSD regarding snat. 
https://github.com/pfsense/FreeBSD-ports/commit/6b581861c33a622498e75f3e90482ef12a21bacf

**Comment by bradfitz** [comment]
Dup of #5573
