### ISSUE TITLE
tailscale ssh is broken

### ISSUE THREAD

**Issue by asg0451** [tailscale/tailscale#7087]
### What is the issue?

click on ssh on tailscale.com/admin/machines

get this

![image](https://user-images.githubusercontent.com/4358545/215149703-737c1d39-47b5-4ba1-ada9-ddaaebc42653.png)

**Comment by asg0451** [comment]
clearing browser cache fixed it.

**Comment by mihaip** [comment]
Re-opening, per @raggi this is still happening

**Comment by mihaip** [comment]
Fix is deployed (internal issue is tailscale/corp#8918)
