### ISSUE TITLE
net/stun: STUN attribute padding calculation incorrect in foreachAttr()

### ISSUE THREAD

**Issue by renthraysk** [tailscale/tailscale#709]
https://github.com/tailscale/tailscale/blob/9be1917c5bbdd21e44287a8850e01e383efabc15/net/stun/stun.go#L140-L148

**Comment by bradfitz** [comment]
What's the problem?

You're filing a bug so it's in your head presumably, so perhaps you can save us some re-reading/re-learning of this code/spec and just mention the problem in the bug report too?

**Comment by bradfitz** [comment]
I'm guessing this is about the pad? should be `(4 - (attrLen % 4))`?

**Comment by renthraysk** [comment]
It's not rounding up to next 32 bit boundary. Think the easiest way is... 

```
		attrLenPad := (attrLen + 3) &^ 3
		b = b[4:]
		if attrLenPad > len(b) {
			return ErrMalformedAttrs
		}
		if err := fn(attrType, b[:attrLen]); err != nil {
			return err
		}
		b = b[attrLenPad:]
```

**Comment by renthraysk** [comment]
Here's the PR

https://github.com/tailscale/tailscale/pull/710
