### ISSUE TITLE
Funnel DNS record does not exist

### ISSUE THREAD

**Issue by fjleon1980** [tailscale/tailscale#7103]
same as https://github.com/tailscale/tailscale/issues/6911 and https://github.com/tailscale/tailscale/issues/6923

i can only resolve my endpoint funnel dns if connected to tailscale, which beats the purpose of funnel. i created the funnel about 2 hours ago, and attempted to query both ipv4 and ipv6 records directly to the authoritative nameserver

i understand the alpha status but on 6923 it was commented that this should be working now.

my domain is raptor-vibes.ts.net

**Comment by bradfitz** [comment]
@fjleon1980, we'll probably need more info from you. Tailscale version, tailscale status, Tailscale IP, etc.

cc @shayne to handle.

**Comment by fjleon1980** [comment]
i am running the latest version 1.3.6 on a raspberry pi. it has 100.91.16.53

tailscale serve status
https://raspbeer.raptor-vibes.ts.net (Funnel on)
|-- / proxy http://127.0.0.1:22

tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, <omitted>
        * IPv6: yes, <omitted> 
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * CaptivePortal: false
        * Nearest DERP: Dallas
        * DERP latency:
                - dfw: 56.4ms  (Dallas)
                - 
if it helps i just disabled funnel and reenabled it

**Comment by shayne** [comment]
Thanks, @fjleon1980! Do you mind running `tailscale down` followed by `tailscale up`? I believe this is a bug we just identified on the backend (https://github.com/tailscale/corp/pull/8934). It happens before a DNS zone is created. cc/ @maisem

**Comment by fjleon1980** [comment]
i ran sudo tailscale down --accept-risk=lose-ssh; sudo tailscale up

hope that works. i can also reboot it if needed

**Comment by fjleon1980** [comment]
nslookup raspbeer.raptor-vibes.ts.net ns1.dnsimple.com returns records now. thanks

unfortunately it does not look like the proxying worked. supposedly i proxied port 22 as i have ssh running. 

maybe i need to tweak some additional settings in tailscale to allow the traffic? 

note that tnc raspbeer.raptor-vibes.ts.net -port 443 reports success so now gotta figure out if the proxy part of the funnel is working. any log i can check?

**Comment by shayne** [comment]
Based on the `serve status` above, it looks like it's set up to proxy to an HTTP server. We will release a revamp of the CLI soon to improve usability.

If you want to Funnel SSH over port 443, you'll want to use TCP forwarding: `tailscale serve tcp 22`. However, SSH doesn't use TLS, and we depend on SNI for Funnel to work. There are [ways to make it work](https://iyzico.engineering/proxy-ssh-using-tls-sni-and-nginx-8a18f93f709), but it's not something I have tried myself.

For logs, run `tailscale debug daemon-logs`.
Bonus, to reset things and clear your serve config you can run `echo {} | tailscale serve set-raw`.

**Comment by fjleon1980** [comment]
ah thanks. my actual intended purpose with funnel is to see if i can download files from passive ftp servers or passive  irc servers. the reason is that i can't port forward with my isp (tmobile) as they are an ipv6 only isp with zero port forwarding features. tried to use cloudflare tunnel but could not get it work (i could get http to work if i launched a mini python web server), hence trying with tailscale as i was already using it.

i would also like to get ssh to work with the funnel but it's not a huge priority as ssh already works when using tailscale on the client node as well (as expected)

I believe we should revamp the doc https://tailscale.com/kb/1223/tailscale-funnel/ to clarify that the default proxy is http and to actually mention the tcp parameter usage.

**Comment by shayne** [comment]
Thanks! We appreciate the feedback, it's especially useful during this alpha stage. 

If you're looking for more info take a look at the CLI docs for `serve`:

https://tailscale.com/kb/1080/cli/#serve

**Comment by fjleon1980** [comment]
thanks, you wouldn't believe how many users want a [port forwarding solution](https://www.reddit.com/r/tmobileisp/search?q=port+forwarding&restrict_sr=on) can use with tmobile home internet (which is becoming increasingly popular around the country, and in some cases giving comcast and other isp a run for their money)

funnel has the possibility of becoming a killer feature for us. once again thanks for assisting and on a sunday! enjoy the rest of your day
