### ISSUE TITLE
SSH on TailScale 1.36 breaks ssh based git pulls on gitea.

### ISSUE THREAD

**Issue by srijanshetty** [tailscale/tailscale#7113]
### What is the issue?

Till TailScale 1.36 push/pull worfklow over ssh for gitea worked perfectly.

Post the update, SSH pull fail with the error

```
fatal: 'org/repo.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

This is solved by disabling TailScale SSH on the host.

### Steps to reproduce

1. Install `gitea` on the host
2. Enable TailScale SSH on the host
3. Try to clone a repository using SSH.

### Are there any recent changes that introduced the issue?

TailScale v1.36

### OS

Other

### OS version

Raspbery Pi

### Tailscale version

1.36

**Comment by bradfitz** [comment]
Are you saying it worked in 1.34 but broke in 1.36?

Can you verify that for us, downgrading to 1.34 for a bit to repro?

**Comment by srijanshetty** [comment]
Will definitely do that @bradfitz!

**Comment by DentonGentry** [comment]
Downgrading for Debian-based systems would be: `apt install tailscale=1.34.2`

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/releases/tag/v1.36.0 does list several SSH-related changes:
- Tailscale SSH: [ssh to tailscaled as a non-root user now works again, as long as you only ssh to the same user that tailscaled is running as](https://github.com/tailscale/tailscale/pull/6904)
- [Tailscale SSH now runs on OpenBSD](https://github.com/tailscale/tailscale/pull/6909)

**Comment by evanrichter** [comment]
@srijanshetty can you confirm whether this works for you currently? Are you stuck on v1.34?

**Comment by srijanshetty** [comment]
No! Just updated to the latest version and don't see any issues.

**Comment by evanrichter** [comment]
thanks for the data point! I'm experiencing similar problems as this issue unfortunately. My bug report is #8730, but I'm glad it's working for you
