### ISSUE TITLE
Tailscale in Docker always renews IP

### ISSUE THREAD

**Issue by MatteoN82** [tailscale/tailscale#7119]
### What is the issue?

Good evening.

I have a container for Tailscale running on my Raspberry pi. Everything works fine, except that on every reboot of the machine or restarting of the container, the IP changes and a new machine is registered on my Tailnet (I am using a reusable auth key for testing purposes).

I have read the fix posted here https://github.com/tailscale/tailscale/issues/3780 and created a persistent volume in Portainer for /var/lib/tailscale, however the problem persists.

I need someone's help.

Thanks.

### Steps to reproduce

Install a docker container for Tailscale, authenticate with auth_key (preferably with pre-authorization), restart machine and/or container.

### OS

Linux

**Comment by maisem** [comment]
Are you using an ephemeral key by any chance? How are you launching the container?

**Comment by MatteoN82** [comment]
> Are you using an ephemeral key by any chance? How are you launching the container?

Hi, thanks for replying. 

Not using ephemeral key and the system does not behave in that way insofar as it does not delete the "old" instances of my machine from my Tailnet, as an ephemeral key does.

Right now I am using Portainer GUI to stop/restart, stop/redeploy or restart the container. All of these result in a new machine being created in Tailnet, as does of course rebooting my server (i.e. the RPI4).

**Comment by DentonGentry** [comment]
The main thing I'd say is that it is behaving as though the persistent storage is not working. `tailscaled` starts up, finds no `/var/lib/tailscale/tailscaled.state`, and makes a new node key for itself using the auth key passed in.

**Comment by MatteoN82** [comment]
I have tested the persistent storage by creating a file from within the running container and checking its persistence after stopping and restarting the container (and also rebooting my physical machine).

Both while the container runs and when it is not, I can only see three files in the /var/lib/tailscale folder:
1. tailscaled.log.conf
2. tailscaled.log1.txt
3. tailscaled.log2.txt

**Comment by DentonGentry** [comment]
That sounds like `TS_STATE_DIR` has been set and is pointing to somewhere which is not persisted, or maybe that  `TS_TAILSCALED_EXTRA_ARGS` includes a `--state=...` or `--statedir=...` argument pointing somewhere that is not persisted.

**Comment by MatteoN82** [comment]
> That sounds like `TS_STATE_DIR` has been set and is pointing to somewhere which is not persisted, or maybe that `TS_TAILSCALED_EXTRA_ARGS` includes a `--state=...` or `--statedir=...` argument pointing somewhere that is not persisted.

Will check both. Thanks.

**Comment by MatteoN82** [comment]
Properly specifying TS_STATE_DIR fixed the issue. Thank you.

**Comment by koalaeagle** [comment]
Setting `TS_STATE_DIR=/var/lib/tailscale` helped me sort this out. It would be a nice quality of life improvement if the docker container used this default as is easily assumed, or else the docker default was documented on dockerhub.

**Comment by xautofzx** [comment]
https://hub.docker.com/r/tailscale/tailscale
docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW --env TS_AUTHKEY=tskey-auth-ab1CDE2CNTRL-0123456789abcdef tailscale/tailscale
has forgot this:
--env TS_STATE_DIR=/var/lib/tailscale

**Comment by rihadik** [comment]
When changing auth key and restarting tailscaled it always assigns a new IP address. Is there a way to keep using the assigned IP address? Merely restarting tailscaled or the machine doesn't change the address, it changes only when changing the auth key (because of the 90 day limit).

**Comment by DentonGentry** [comment]
> Merely restarting tailscaled or the machine doesn't change the address, it changes only when changing the auth key (because of the 90 day limit).

The authkey exists to create the node. Once the node has been created, it creates its own machine-key and node-key and everything else it needs. It no longer needs an authkey, at all.

By default, the node-key for a new node expires after 6 months but can be set to never expire. Nodes created with Tags are set by default to not expire. With the node key set to not expire, the Tailscale node will operate forever and never change its IP address.

**Comment by rihadik** [comment]
@DentonGentry thanks for the quick reply! Yes, I'm using tags so the node is marked as "no expiration". So, in essence, does this mean I can create the node, then if the auth key expires in 90 days and the tailscaled daemon or the machine restarts, or if it's offline for a day or two and then comes back online, as long as its own /var/db/tailscaled/* data is left intact it will be able to log in and get assigned the same IP address?

My startup scripts pass the `--auth-key=file:/path/to/tailscale.key`, I hope this flag doesn't break the normal rules and force it to re-authenticate (and fail with the old key) or something.

**Comment by DentonGentry** [comment]
> I hope this flag doesn't break the normal rules and force it to re-authenticate (and fail with the old key) or something.

tailscaled will only use the authkey if it doesn't have a node-key or if the `--force-reauth` flag is passed to `tailscale up`. You can continue passing in the `--authkey=...` argument if convenient, and it won't be used if it isn't needed.

**Comment by rihadik** [comment]
Thank you very very much!

**Comment by rihadik** [comment]
Also, for some reason existing keys I see by visiting `https://api.tailscale.com/api/v2/tailnet/-/keys`, authenticated by a short-lived key obtained from `https://api.tailscale.com/api/v2/oauth/token`, in turn authenticated by credentials given in the web panel after creating an OAuth Client there, aren't listed in the mentioned web panel under `Settings->Keys`. Obviously the keys I created on the aforementioned endpoints are linked to the account via the OAuth Client, but yet, nothing there.
