### ISSUE TITLE
cmd/tailscale: status shows all peers when disconnected

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#714]
`tailscale status` on Mac and Windows shows all peers when disconnected, which is slightly odd.

It should probably return an empty list and an exit code in text mode.

And `tailscale status --json` mode should probably set a new field on the returned JSON object saying the state. It actually has `BackendState: ""` now for both connected & disconnected.

**Comment by bradfitz** [comment]
@lzjluzijie, perhaps you have time for this bug too?

**Comment by lzjluzijie** [comment]
Should I do it together with #466?

**Comment by bradfitz** [comment]
Separate is probably best, unless it's easier to do them together.
