### ISSUE TITLE
iOS 16.3 Battery Drain

### ISSUE THREAD

**Issue by allendcross** [tailscale/tailscale#7144]
### What is the issue?

My iPhone 14 pro max battery is draining all night to the point my charger cannot keep up. Looking at battery health it shows Tailscale is using lots of background drain.

### Steps to reproduce

Phone is connected to wifi and connected to my tail net.

### Are there any recent changes that introduced the issue?

Unknown.

### OS

iOS

### OS version

16.3

### Tailscale version

1.36

### Bug report

BUG-7f09169b155c1a73104af537c8e6504107e9fa62e43ed06cde8e3b2c2eb2a991-20230201170040Z-c3f00ad61346a93e

**Comment by bradfitz** [comment]
There's a bunch of work currently being done on this which is overall tracked in #3363 so I'm going to close this one.
