### ISSUE TITLE
API Docs Look Incorrect

### ISSUE THREAD

**Issue by charles-d-burton** [tailscale/tailscale#7145]
### What is the issue?

When generating a key I get the following error:
```bash
{"message":"json: unknown field \"reusable:\""}
```

### Steps to reproduce

Try to generate a key using the API like this:
```bash
curl -s -X POST -H "Authorization: Bearer ${TS_ACCESS_TOKEN}" -d '{"capabilities": {"devices":{"create":{"reusable:":false,"ephemeral":true,"preauthorized":true}}}}' "https://api.tailscale.com/api/v2/tailnet/<yourtailnethere>/keys"
```

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

latest

**Comment by bradfitz** [comment]
You have an errant colon in the string:

<img width="340" alt="Screenshot 2023-02-01 at 9 58 24 AM" src="https://user-images.githubusercontent.com/2621/216124682-b94c4ffc-eb07-41d6-b7d5-7ede32204c0e.png">
