### ISSUE TITLE
Tailscale update subcommand not found in help

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#7162]
### What is the issue?

![image](https://user-images.githubusercontent.com/13573364/216413591-780b2b3f-87c0-4f53-989f-5a44ebe91ca8.png)
https://tailscale.com/changelog/#:~:text=tailscale%20update%20command%20to%20update%20client

### Steps to reproduce

sudo tailscale

### OS

Linux

**Comment by bradfitz** [comment]
That's intentional. CLI features in alpha are hidden until they're done.
