### ISSUE TITLE
Tailscale Kubernetes sidecar works, but not proxy

### ISSUE THREAD

**Issue by jorgnyg** [tailscale/tailscale#7165]
### What is the issue?

The sample sidecar example works just as expected: https://tailscale.com/kb/1185/kubernetes/#sample-sidecar
Trying the proxy example, does not work. Not able to ping the tailnet "machine" representing the proxy after `make proxy` and authentication. https://tailscale.com/kb/1185/kubernetes/#sample-proxy

Used the examples provided here, so no files are edited: https://github.com/tailscale/tailscale/tree/main/docs/k8s

### Steps to reproduce

Follow steps to set up proxy for the nginx deployment https://tailscale.com/kb/1185/kubernetes/#sample-proxy

**Comment by DentonGentry** [comment]
The Kubernetes operator is available now and may be better suited for your purposes.
https://github.com/tailscale/tailscale/issues/502

**Comment by jorgnyg** [comment]
@DentonGentry didn't know about that. Thanks! Will check it out
