### ISSUE TITLE
TS_AUTHKEY doesnt work in a sidecar with containerboot on tailscale/tailscale:latest

### ISSUE THREAD

**Issue by cdturnerRCP** [tailscale/tailscale#7166]
### What is the issue?

building a k8s pod with tailscale as a sidecar failed to auth.

all the docs and the scripts refer to TS_AUTHKEY.
including the docs in tailscale/docs/k8

if you rename TS_AUTHKEY to TS_AUTH_KEY it does work. 

### Steps to reproduce

you can add command: ["/bin/sh", "-c", "env"] to your k8 pod
to see the env vars are set, yet if you let the image run containerboot as normal it fails to find the auth key and asks you to login manually.

IF you change the env var definition in your k8s pod to 
TS_AUTH_KEY then it works like a charm.

### OS version

ubuntu on WSL, docker desktop k8s enabled. Windows 10. 

### Tailscale version

latest. as of 2/2/2023

### Other software

using a tailscale auth key generated as
- multi use,
- ephemeral
- tagged

**Comment by DentonGentry** [comment]
What Tailscale version was that at the time you tried?

With 1.36.0 and later, both TS_AUTH_KEY and TS_AUTHKEY are checked. Setting either one should work.
https://github.com/tailscale/tailscale/blob/2eb25686d79af0bd3ebbbef7e470aaae0933fb67/cmd/containerboot/main.go#L76

**Comment by DentonGentry** [comment]
Possibly related:
- ghcr.io `latest` and `stable` were stuck at 1.34.1 until 11 Feb 2023 at 8:20pm Pacific time.
- DockerHub `latest` and `stable` were 1.36.1.
https://github.com/tailscale/tailscale/issues/7251

**Comment by cdturnerRCP** [comment]
we were pulling from
ghcr.io/tailscale/tailscale:latest

on the date I filed the issue.

Testing with latest this morning, it doesnt repro anymore. both TS_AUTHKEY and TS_AUTH_KEY appear to work fine today.


________________________________

**Comment by DentonGentry** [comment]
Fixed in 1.36 by https://github.com/tailscale/tailscale/pull/6885
