### ISSUE TITLE
Log in button not working

### ISSUE THREAD

**Issue by JerryBerry12** [tailscale/tailscale#7172]
### What is the issue?

When I try to click the button to log in the menu, it does nothing. I tried quitting the tailscaled.exe and reopening it so that I could see the log and this is what happens when I click it.
StartLoginInteractive: url=false
control: client.Login(false, 2)
control: LoginInteractive -> regen=true
control: doLogin(regen=true, hasUrl=false)
Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=57": read tcp [::1]:64367->[2a05:d014:386:202:24dd:46aa:f98e:9997]:443: wsarecv: An established connection was aborted by the software in your host machine.

### Steps to reproduce

Install Tailscale Client for Windows 1.37.32
Try to Log In

### Are there any recent changes that introduced the issue?

No

### OS

Windows

### OS version

Windows 11 64-Bit

### Tailscale version

1.37.32

### Other software

Mc Afee Live Safe
Windows Defender Firewall
VirtualBox
VMWare

### Bug report

BUG-20f2f893f7695884f50d853637d26067e9c887bd0c972647fb3ea6b637ec180a-20230203161925Z-d7e18cb0e67c3b69

**Comment by bradfitz** [comment]
In a command prompt, what does it say when you run:

`tailscale debug ts2021`

**Comment by JerryBerry12** [comment]
11:33:21.358731 Fetching keys from https://controlplane.tailscale.com/key?v=57 ...
11:33:22.846787 Dial("tcp", "[2a05:d014:386:201:7200:6340:b22f:7df6]:80") ...
11:33:22.848885 Dial("tcp", "[2a05:d014:386:201:7200:6340:b22f:7df6]:80") = [::1]:49335 / [2a05:d014:386:201:7200:6340:b22f:7df6]:80
11:33:22.867099 Dial("tcp", "[2a05:d014:386:202:6dd4:fc68:35ae:2b80]:443") ...
11:33:22.868100 Dial("tcp", "[2a05:d014:386:202:6dd4:fc68:35ae:2b80]:443") = [::1]:49337 / [2a05:d014:386:202:6dd4:fc68:35ae:2b80]:443
11:33:22.870290 controlhttp.Dial = 0x0, all connection attempts failed (HTTP: EOF, HTTPS: read tcp [::1]:49337->[2a05:d014:386:202:6dd4:fc68:35ae:2b80]:443: wsarecv: An established connection was aborted by the software in your host machine.)
all connection attempts failed (HTTP: EOF, HTTPS: read tcp [::1]:49337->[2a05:d014:386:202:6dd4:fc68:35ae:2b80]:443: wsarecv: An established connection was aborted by the software in your host machine.)

I have to go but I'll be back at 3

**Comment by bradfitz** [comment]
Something on your machine is interfering and breaking the connection. Of the software you listed, I'd guess McAfee LiveSafe is the most likely culprit. It might be keeping you too safe. Can you try disabling it?

**Comment by JerryBerry12** [comment]
OK, I’ll be in front of my computer in like an hour, so I’ll try it out and get back to you. Thanks so much. (you’re right. It might be keeping me to safe…🤣🤣🤣🤣


On Feb 3, 2023, at 3:02 PM, Brad Fitzpatrick ***@***.***> wrote:

﻿

Something on your machine is interfering and breaking the connection. Of the software you listed, I'd guess McAfee LiveSafe is the most likely culprit. It might be keeping you too safe. Can you try disabling it?

**Comment by bradfitz** [comment]
Keepin' us in suspense! 😅

**Comment by JerryBerry12** [comment]
SO SORRY! I ment to reply sooner, but it just slipped off my head. When I tried allowing it to all ports in McAfee (Not just designated ports) Nothing happened. When I turned off firewall completely, it were these two errors. (I think number 2 is old)
1. 
```
control: LoginInteractive -> regen=true
control: doLogin(regen=true, hasUrl=false)
Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=57": read tcp [::1]:56862->[2a05:d014:386:201:7200:6340:b22f:7df6]:443: wsarecv: An existing connection was forcibly closed by the remote host.
```
2. 
```
control: LoginInteractive -> regen=true
control: doLogin(regen=true, hasUrl=false)
Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=57": read tcp [::1]:56856->[2a05:d014:386:201:7200:6340:b22f:7df6]:443: wsarecv: An established connection was aborted by the software in your host machine.
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: connectex: The requested address is not valid in its context. (in 35ms), trying bootstrap...
logtail: bootstrap dial succeeded
logtail: upload: log upload of 25714 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/a072fae0288dc1cc1fc90523eacf40f2a57e7d1bcfd25cd997ad1f5ea93e5863": read tcp [::1]:56860->[2600:1f18:429f:9305:4043:217b:512c:f8d4]:443: wsarecv: An established connection was aborted by the software in your host machine.
logtail: [v1] backoff: 9197 msec
```
Thanks!

**Comment by bradfitz** [comment]
That basically just says something is blocking it. I don't know what.

I don't think we'll be able to help more without knowing what else is running on your machine.

**Comment by JerryBerry12** [comment]
I've tried opening ports 443 as it says here:
```
                                            ⬇️                                                 ⬇️    
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: connectex: The requested address is not valid in its context. (in 35ms), trying bootstrap...
```
But didn't do anything. I'm gonna try vmware next because I don't use it, then VirtualBox. Thanks!

**Comment by JerryBerry12** [comment]
I'm sorry, but nothing seems to be working. I'm gonna try using something else. I may try to use wireguard. I don't mean to say I don't like your project, but I don't think its working for me. Thank you for all your time, and if this ever gets fixed, I'll come back.
-Jerry

**Comment by JerryBerry12** [comment]
I even tried disabling all the wireless adapters except for ethernet and Bluetooth, and It still didn't work

**Comment by apigban** [comment]
@JerryBerry12 were you able to successfully use the tailscale client on windows? Same thing's happening on my machine.

If not, what were you able to use as a client?

**Comment by DentonGentry** [comment]
@apigban please open a new issue. You might feel very strongly that you are seeing the same problem, but it would be better to let us start afresh.

I'm going to lock this issue to prevent further correspondence on it.
