### ISSUE TITLE
Tailscale stops connecting to tailnet on iPhone

### ISSUE THREAD

**Issue by rgregg** [tailscale/tailscale#7182]
### What is the issue?

I've been using Tailscale for a while on my phone to access a range of devices and love it. But lately I've been having an issue where my iPhone drops off the tailnet and can't access anything. After a lot of work to narrow down the problem, I've found that it's triggered by using the Home Assistant app and connecting over my tailnet to my Home Assistant server.

Once the connection is broken, it does not reconnect until I manually disconnect from the tailnet and reconnect. I've reinstalled Tailscale, reauthenticated, and tried to narrow down the issue and this is a 100% repo for me now.

I'm not sure if there are logs or something else I can pull off the phone to help figure out what's going on in more detail.

### Steps to reproduce

1. Connect to Tailnet via the tailscale app
2. Verify the connection is working - ping devices on tailnet from iPhone, ping iPhone from tailnet. Everything is responsive.
3. Launch the Home Assistant app and connect to HA server via tailnet.
4. Use the app for ~30 seconds until the app stops being able to load data. Pinging the iPhone via the tailnet stops responding at the same time.
5. Try to ping other devices on the tailnet from the iPhone, see that the connection is dead.

### OS

iOS

### OS version

iOS 16.2

### Tailscale version

1.36.0

### Bug report

BUG-705854a001bae22d4fded6f6b24f92558d3a3479be1bba58959cbe9f3fee94e2-20230204180915Z-1f5d043aed5aaf38

**Comment by DentonGentry** [comment]
Well, that is fascinating. This is the Home Assistant app on the iPhone: https://apps.apple.com/us/app/home-assistant/id1099568401 ?

Around the time of the bugreport from the iPhone, we see it reporting:
```
2023-02-04 18:06:11.012152 +0000 UTC: wg: [UHbD7] - Sending handshake initiation
2023-02-04 18:06:11.013251 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.013286 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.01451 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.014569 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.015029 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.015063 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.015949 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.015971 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.01669 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.01671 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.016974 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.016991 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.017385 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.017403 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
2023-02-04 18:06:11.018163 +0000 UTC: wg: [M5e5u] - ConsumeMessageInitiation: handshake flood
2023-02-04 18:06:11.018193 +0000 UTC: wg: Received invalid initiation message from 3397b9bab9...
```

The node M5e5u has Tailscale IP address 100.69.228.x, is that the Home Assistant server?

**Comment by rgregg** [comment]
Yep, that's the app and that is the IP address of the home assistant server.

**Comment by knyar** [comment]
I tried reproducing this on my iPhone (iOS 16.2, Tailscale 1.36.0, Home Assistant 2023.2) but even after using the Home Assistant app for a few minutes my phone remained connected and reachable on the tailnet.

Taking a closer look at the bugreport logs, it seems that the Tailscale client on the phone reports loss of external network connectivity and cannot even reach the DERP relays.

What I would probably suggest as next steps for investigating this:
- checking whether the same issue appears on another internet connection (cell coverage vs wifi, or on another wifi network)
- examining the iPhone logs while this happens. You can do this by connecting the phone to a macOS computer and streaming the logs via the Console app.

**Comment by rgregg** [comment]
Thanks for the follow up @knyar. I've had this occur on multiple network connections, but I'll work through a more detailed repro and grab the logs off the iPhone at the same time and get back to this thread.

**Comment by rgregg** [comment]
OK - did more investigating and the Home Assistant app is not part of the issue. When connected to both WiFi and Cellular, the Tailnet connection regularly drops after about 15-30 seconds, even if I'm still in the Tailscale app. Once the connection drops, it does not return (15+ minutes waiting) unless I disconnect and reconnect in Tailscale.

When i switched to cellular only, I found the connection to be much more reliable, but still had issues where it would disconnect from the Tailnet for long periods of time (minutes), but in this case it would usually reconnect automatically.

**Comment by wizzard0** [comment]
Can confirm the same. It gets much more stable at the cost of huge battery consumption if you continuously ping the iPhone from inside the tailnet. Another workaround is to schedule reconnects via Shortcuts.

**Comment by unphased** [comment]
I think I also see this issue. I'm out and about on cellular and only have my iPhone, I try to do some work over SSH on my workstation or MacBook. If I connect via Tailscale it will sometimes work for up to a few minutes but reliably hangs. 

Tailscale works so perfectly in every other scenario. It's very sad as the connection has to be managed much more manually otherwise.

**Comment by agottardo** [comment]
A long time has passed since this issue was opened, and we fixed a number of issues related to network transitions. I'll close this. 

@unphased if any issue is still occurring, please open a new issue **attaching a bug report identifier** (I cannot diagnose anything based on your description alone).

**Comment by denveronly** [comment]
I have same issue on ios 26 now
Open HA app and tailscale connection is gone

**Comment by eric-schleicher** [comment]
Can confirm this is still very much an issue (feb 2026) Quite frustrating.   iOS 18.6.2 with Tailscale 1.94.1

I’ve had some luck on networks where I can disable ipv6 as the lord intended, but one of my key networks I can’t disable. 

Would be please to get some guidance/capture some logs to help nails down what the issue is. 

Have this problem with 0 other applications

**Comment by unphased** [comment]
I moved from my iphone 13 pro max to an iphone air and have never experienced this issue on this new device, for what it's worth. Tailscale is critical to my self hosting workflows. You might try upgrading your iOS to 26.

**Comment by denveronly** [comment]
Im on iphone 16 pro max with ios26
Still an issue

**Comment by eric-schleicher** [comment]
> I moved from my iphone 13 pro max to an iphone air and have never experienced this issue on this new device, for what it's worth. Tailscale is critical to my self hosting workflows. You might try upgrading your iOS to 26.

The issue is the same in a browser as outside the app, so understanding more on whether it's a bad interaction caused by an iOS or Home Assistant quirk remains to be seen.   The fact that no other application i have that uses tailscale seems to exhibit the same behavior strongly implies that it's the latter.  

is there a section/block in the logs would be expected to provide insight into see what's going on?

**Comment by unphased** [comment]
when i had the issue i definitely experienced it on both ssh and http for home assistant across multiple target machines on my tailnet fwiw.
