### ISSUE TITLE
Tailscale on = no cellular Internet

### ISSUE THREAD

**Issue by antgiant** [tailscale/tailscale#7184]
Over the past few days I’ve been having an issue where turning on tailscale on my iPhone results in no cellular Internet or tailscale network. I am not aware of any changes to my config, and this bug is not happening when I use wireless on my phone. I’ve tried turning the active switch off and on, force restarting the app, cycling airplane mode, and completely rebooting my phone. None made any difference.
If it helps here is a bug id.

BUG-fc43f800d65de659824423a8c60156ce018ce2c91077b49c757807cd6ecd353f-20230204224633Z-6ff0a265b04d66d9

**Comment by mihaip** [comment]
Do you happen to have multiple eSIM cards in your phone or multiple cell data plans? We made a change in Tailscale v1.36 (to fix #6565) where we more specifically request Wi-Fi or cell data networking from iOS. Looking at the logs for your phone, with v1.34 it would pick the `pdp_ip0` when using cell data, but it now picks `pdp_ip1`, and so perhaps it's trying to use the wrong cell plan.

**Comment by antgiant** [comment]
No, I only have one cell plan and one sim. However, I do have an Apple Watch with a cell plan. Could that perhaps be related?

**Comment by mihaip** [comment]
I don't believe the Apple Watch cell plan is visible to the phone. Based on some more digging, `pdp_ip0` should be the standard cell interface, and `pdp_ip1` is the one used by VoLTE (voice-over-LTE), which is not something that Tailscale should be trying to do.

A long shot, but are you aware of any non-standard cell data configurations on your phone (either done by you or your carrier)?

**Comment by mihaip** [comment]
We released a build to TestFlight that we believe should fix this problem. If you'd like to try it out, you can install version 1.37.101 using the instructions at https://tailscale.com/kb/1083/install-unstable/.

**Comment by antgiant** [comment]
Hey that fixed it for me! Thank you so much! So, nice to have it working in both Cell and WiFi again!

**Comment by mihaip** [comment]
Thank you for conforming, the fix was picked up in the recently-released 1.36.2 stable release.

**Comment by henrikstroem** [comment]
I have problems with Tailscale on iOS since last update: when activated, Apple Car Play no longer has internet access. Disabling Tailscale solves the problem.
I don't know if this is important, but reading the posts above, I just want to add that I have two SIMs in my phone: a physical card and an eSIM. Both have a data plan, and iOS is set up to use both.
