### ISSUE TITLE
Installing TS on Windows in Parallels?

### ISSUE THREAD

**Issue by chernipeski** [tailscale/tailscale#7186]
At the start of the install, manually select the target installation directory, otherwise TS tries to refer to a disk volume that doesn't exist and gives you "out of space" error (sorry I didn't record actual wording)

**Comment by DentonGentry** [comment]
The installer is supposed to install in `c:\Program Files`. You're saying it tried to install somewhere else in Parallels?

**Comment by wizzard0** [comment]
data point: TS in Parallels worked for me previously, though that was about a year ago and Parallels 17

**Comment by chernipeski** [comment]
Ok, I’ll try again. During the install process in Windows on Parallels, do not accept the default install path — even though it seems correct.  Instead, select the disk manually to avoid the installer error.  

On Mar 20, 2023, at 07:48, Denton Gentry ***@***.***> wrote:

﻿
DuckDuckGo removed 1 tracker.
 
More →
Yes I’m sorry i didn’t document the error this causes better. I suppose this has everything to do with how I have parallels configured, but the easy workaround might be found useful.

I don't understand what this means.

This issue doesn't have enough information to followup on. Barring further comment about where Parallels tried to install Tailscale, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
> During the install process in Windows on Parallels, do not accept the default install path — even though it seems correct.  Instead, select the disk manually to avoid the installer error.

So far as I can tell the difficulty with installing `C:\Program Files` is limited to your one system and how the disks were partitioned. We have a number of other users who have installed Tailscale within a VM in Parallels.

I do not believe it is appropriate to make the installer favor a location other than `C:\Program Files`
