### ISSUE TITLE
FR: High availability with subnet router deployment on Kubernetes

### ISSUE THREAD

**Issue by omerlh** [tailscale/tailscale#7189]
### What are you trying to do?

We have multiple subnet routers running on Kubernetes, which works perfectly. But, if one of the pods is down for some reason, the subnet router will not work until the pod is starting again. We would like to leverage Kubernetes HA features by deploying more than one pod, using pod disruption budget etc.

### How should we solve this?

Is it possible to run more than one pod of tailscale subnet router with the same route?

### What is the impact of not solving this?

Just wait for tailscale to start

**Comment by knyar** [comment]
Hi! I believe you should be able to use the [subnet router failover](https://tailscale.com/kb/1115/subnet-failover/) feature for this.

**Comment by zetaab** [comment]
@omerlh did you get it working? At least it works like in this way https://gist.github.com/zetaab/b5b82fcece338d3103a5497f76b16a3c

However, it would be nice to have that in single deployment. If I try that it just says "duplicate node with same key"

**Comment by zetaab** [comment]
@omerlh check this gist https://gist.github.com/zetaab/8543e58b175dc30ee97290d3d23e201d got it working with statefulsets

**Comment by omerlh** [comment]
Sorry - not yet :)
