### ISSUE TITLE
Tailscale seem to allow `localhost` as a valid node name

### ISSUE THREAD

**Issue by rx294** [tailscale/tailscale#7191]
### What is the issue?

Tailscale seems to allow `localhost` as a valid node name. 

This caused all the enrolled nodes to resolve `localhost` as the tailscale client node on all enrolled nodes.

This caused issues with our infra...

This feels like a giant pothole with a chance of taking down a lot of infra.

**Comment by bradfitz** [comment]
Thanks for the reminder and bug! I saw this happen months ago and was going to disallow it then but got distracted apparently.

**Comment by rx294** [comment]
Given the disaster potential.. plz expedite a fix.

**Comment by bradfitz** [comment]
Yes, sir!
