### ISSUE TITLE
Infinite netmap reload loop due to client-side expiry handling

### ISSUE THREAD

**Issue by mihaip** [tailscale/tailscale#7193]
There's CPU profile from a user ([ticket](http://go/hs/9322)) that shows a lot of time spent doing netmap updates:

![image](https://user-images.githubusercontent.com/513813/217104414-eec3303e-0b35-45a0-9164-8b58473d0912.png)

Based on logs, it appears to be related to client-side expiration handling (#6937), e.g. there so many logs that they're getting throttled:

```
2023-01-31 23:38:38.729611 +0000 UTC: [RATELIMIT] format("setClientStatus: netmap expiry timer triggered after %v") (48618 dropped)
```

**Comment by andrew-d** [comment]
This is now released in an unstable build of Tailscale - v1.37.74
