### ISSUE TITLE
device registration: tailnet-owned auth keys always create new device

### ISSUE THREAD

**Issue by willnorris** [tailscale/tailscale#7201]
Originally reported by @kellegous [on Twitter](https://twitter.com/kellegous/status/1621312789494087681) with an [excellent reproduction case here](https://github.com/kellegous/tsnet-confusion).  When an OAuth-derived auth key is used to register a device, it always recreates the device on restart (even with the same client state).

I can reliably reproduce using [these instructions](https://github.com/kellegous/tsnet-confusion).  That OAuth code generates a new auth key on every run, so I also tried manually creating an OAuth-derived auth key and reusing that same key multiple times.  The same behavior is present... each run registers a new device.  I'm guessing this is going to be similar to 0fd2f71a1e8c3c943864f9c066075cf5ee43c112 where we assume a UserID is present (and/or valid), which isn't the case for these tailnet-owned keys.

**Comment by willnorris** [comment]
huh okay... this isn't *similar* to https://github.com/tailscale/tailscale/commit/0fd2f71a1e8c3c943864f9c066075cf5ee43c112, this is actually the same issue.  Working with tailscale/tailscale@HEAD resolves the problem for me.  @kellegous, could you try on your side to confirm?

**Comment by kellegous** [comment]
@willnorris can confirm. HEAD resolves the issue for me. Thank you.
