### ISSUE TITLE
ipn/ipnlocal: certificates and keys are both written to the same file

### ISSUE THREAD

**Issue by creachadair** [tailscale/tailscale#7202]
See: https://github.com/tailscale/tailscale/blob/main/ipn/ipnlocal/cert.go#L179

This should be using `certFile` instead (was modified in #7142). I believe this is the underlying cause of internal issue https://github.com/tailscale/corp/issues/9090)

**Comment by bradfitz** [comment]
cc @maisem

**Comment by bradfitz** [comment]
This wasn't released in a stable version yet, right?

**Comment by creachadair** [comment]
> This wasn't released in a stable version yet, right?

I was trying to figure this out, but some of the OSS imports don't include the bot-generated commit range so I think we have to work backward from the hash in go.sum.

**Comment by bradfitz** [comment]
> I was trying to figure this out, but some of the OSS imports don't include the bot-generated commit range so I think we have to work backward from the hash in go.sum.

No need for all that. Just look at https://github.com/tailscale/tailscale/commit/6bae55e351fce19314d3da319eee0582f8c3943c where it says which branches it's in. Not in a release branch. Only main:

<img width="466" alt="Screenshot 2023-02-07 at 2 10 03 PM" src="https://user-images.githubusercontent.com/2621/217378192-c3c61070-7a5f-4ff6-8906-e84f4b1f5b88.png">
