### ISSUE TITLE
FR: Logging in via GitHub without organization scope

### ISSUE THREAD

**Issue by gBasil** [tailscale/tailscale#7207]
### What are you trying to do?

I am trying to log in to Tailscale via GitHub without authorizing Tailscale to view the organizations I am in due to security and paranoia.

### How should we solve this?

Not require the `read+orgs` scope. It doesn't have to in the UI explicitly.

### What is the impact of not solving this?

<img width="297" alt="image" src="https://user-images.githubusercontent.com/57513430/217432502-35b1171c-9d03-41cc-ad1c-2b4b88b1b98f.png">
I know it's a minor thing, but it would give me some peace of mind.

### Anything else?

I don't know if just having the `user.email` scope prevents you from reading organization data. Also, this isn't something the vast majority of users would care about.

**Comment by DentonGentry** [comment]
Not requesting the orgs scope would make multi-user GitHub tailnets impossible, for example https://tailscale.com/blog/community-github-pricing/

**Comment by gBasil** [comment]
Gotcha. Oh well. Thank you for your time!
