### ISSUE TITLE
cannot run tailscale command after installation on Windows

### ISSUE THREAD

**Issue by alexbrainman** [tailscale/tailscale#721]
**Describe the bug**

I just installed tailscale - I followed these steps

https://tailscale.com/kb/1022/install-windows?q=windows

After I finished, everything works OK. Except I cannot run tailscale command.

```
C:\Users\Alex>tailscale.exe
'tailscale.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Alex>
```

I can run tailscale command, if I change to tailscale direcotry

```
C:\Users\Alex>cd C:\Program Files (x86)\Tailscale IPN

C:\Program Files (x86)\Tailscale IPN>tailscale.exe /?
USAGE
  tailscale subcommand [flags]

This CLI is still under active development. Commands and flags will
change in the future.

SUBCOMMANDS
  up        Connect to your Tailscale network
  netcheck  Print an analysis of local network conditions
  status    Show state of tailscaled and its connections
  version   Print Tailscale version

FLAGS
  -socket ...  path to tailscaled's unix socket

C:\Program Files (x86)\Tailscale IPN>
```

If you expect users to be able to run tailscale command, you should change installer to add this directory to user PATH.

**To Reproduce**
I described repro above.

**Expected behavior**
I should be able to run tailscale command.

**Screenshots**
Not needed.

**Version information:**
 - OS version: Windows 10
 - Tailscale version: 1.0.4-ge256174d6

**Additional context**
Nothing further.

Thank you.

Alex

**Comment by bradfitz** [comment]
That feature was added after 1.0.4. Try the unstable track.

**Comment by bradfitz** [comment]
It's in 1.1.176 or later.
