### ISSUE TITLE
Tailscale 1.36.0 on Windows connects automatically

### ISSUE THREAD

**Issue by thomasvochten** [tailscale/tailscale#7212]
### What is the issue?

Since upgrading to 1.36.0 on Windows, the Tailscale client automatically connects after Windows login. This was not the case previously.

### OS

Windows

### OS version

Windows 11 22H2

### Tailscale version

1.36.0

**Comment by bradfitz** [comment]
Seems like 1.34.0 actually. Dup of #6668.
