### ISSUE TITLE
Prompt certificate error during installation

### ISSUE THREAD

**Issue by MilkTeaNo7** [tailscale/tailscale#7226]
I followed the official installation via script
https://tailscale.com/download/linux/centos-7

The script used
curl -fsSL https://tailscale.com/install.sh | sh

The operating system is
CentOS7

When I run the script it gives me the following error, certificate expired? I don't know what to do

```
`
[root@localhost ~]# curl -fsSL https://tailscale.com/install.sh --insecure | sh
Installing Tailscale for centos 7, using method yum
+ yum install yum-utils -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
Nothing to do
+ yum-config-manager -y --add-repo https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
Loaded plugins: fastestmirror
adding repo from: https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
grabbing file https://pkgs.tailscale.com/stable/centos/7/tailscale.repo to /etc/yum.repos.d/tailscale.repo
Could not fetch/save url https://pkgs.tailscale.com/stable/centos/7/tailscale.repo to file /etc/yum.repos.d/tailscale.repo: [Errno 14] curl#60 - "Peer's Certificate has expired."
`
```

**Comment by bradfitz** [comment]
What does `curl -v -I https://pkgs.tailscale.com/` say?

**Comment by MilkTeaNo7** [comment]
> ### What is the issue?
> 我按照官方的安装方式，通过脚本进行安装 https://tailscale.com/download/linux/centos-7
> 
> 使用的脚本 curl -fsSL https://tailscale.com/install.sh | sh
> 
> 操作系统为 CentOS7
> 
> 当我运行脚本时他提示如下错误，证书过期？？我不知道该怎么办
> 
> `[root@localhost ~]# curl -fsSL https://tailscale.com/install.sh --insecure | sh Installing Tailscale for centos 7, using method yum
> 
> * yum install yum-utils -y
>   Loaded plugins: fastestmirror
>   Loading mirror speeds from cached hostfile
>   Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
>   Nothing to do
> * yum-config-manager -y --add-repo https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
>   Loaded plugins: fastestmirror
>   adding repo from: https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
>   grabbing file https://pkgs.tailscale.com/stable/centos/7/tailscale.repo to /etc/yum.repos.d/tailscale.repo
>   Could not fetch/save url https://pkgs.tailscale.com/stable/centos/7/tailscale.repo to file /etc/yum.repos.d/tailscale.repo: [Errno 14] curl#60 - "Peer's Certificate has expired."`
> 
> ### Steps to reproduce
> _No response_
> 
> ### Are there any recent changes that introduced the issue?
> _No response_
> 
> ### OS
> _No response_
> 
> ### OS version
> CentOS7
> 
> ### Tailscale version
> 最新版本
> 
> ### Other software
> _No response_
> 
> ### Bug report
> _No response_



> What does `curl -v -I https://pkgs.tailscale.com/` say?

Thanks, I'll give it a try

**Comment by MilkTeaNo7** [comment]
> What does `curl -v -I https://pkgs.tailscale.com/` say?

He prompted a certificate error, I tried adding --insecure to skip, but it didn't work

```
[root@localhost ~]# curl -v -I https://pkgs.tailscale.com/ 
* About to connect() to pkgs.tailscale.com port 443 (#0)
*   Trying 167.172.11.40...
* Connected to pkgs.tailscale.com (167.172.11.40) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=pkgs.tailscale.com
*       start date: Jan 23 21:37:36 2023 GMT
*       expire date: Apr 23 21:37:35 2023 GMT
*       common name: pkgs.tailscale.com
*       issuer: CN=R3,O=Let's Encrypt,C=US
* NSS error -8181 (SEC_ERROR_EXPIRED_CERTIFICATE)
* Peer's Certificate has expired.
* Closing connection 0
curl: (60) Peer's Certificate has expired.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
[root@localhost ~]# 
[root@localhost ~]# curl -fsSL https://tailscale.com/install.sh --insecure | sh
Installing Tailscale for centos 7, using method yum
+ yum install yum-utils -y

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
Nothing to do
+ yum-config-manager -y --add-repo https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
Loaded plugins: fastestmirror
adding repo from: https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
grabbing file https://pkgs.tailscale.com/stable/centos/7/tailscale.repo to /etc/yum.repos.d/tailscale.repo
Could not fetch/save url https://pkgs.tailscale.com/stable/centos/7/tailscale.repo to file /etc/yum.repos.d/tailscale.repo: [Errno 14] curl#60 - "Peer's Certificate has expired."
```
