### ISSUE TITLE
Funnel occupying https port and can't run other server.

### ISSUE THREAD

**Issue by dingdang66686** [tailscale/tailscale#7227]
### What is the issue?

Tailscale is occupying https port when funnel is enabled. I can't start other web server.

### OS

Linux

### OS version

ubuntu server 22.04

### Tailscale version

1.36.1

### Other software

caddy

**Comment by bradfitz** [comment]
It does that so you can access it locally. But maybe it's binding too widely.

What address do you want Caddy to listen on? ":443" or "other-IP:443" or "tailscale-IP:443" ?

cc @shayne

**Comment by dingdang66686** [comment]
*:443, can we reuse caddy as the web server for funnel?

**Comment by bradfitz** [comment]
What's your Funnel config? If it's a straight TCP forward and Caddy is doing the TLS termination, we probably shouldn't run the local listener.

**Comment by dingdang66686** [comment]
I enabled funnel and added a proxy for a http applicatio on a high port.

**Comment by dingdang66686** [comment]
> What's your Funnel config? If it's a straight TCP forward and Caddy is doing the TLS termination, we probably shouldn't run the local listener.

If I only enable funnel, I can't connect to my web server.

**Comment by bradfitz** [comment]
What's your `tailscale serve status --json` say?

**Comment by dingdang66686** [comment]
I have solved my problem by adding a TCP forward. Thanks. BTW you didn't mention it in your documentation.

**Comment by dingdang66686** [comment]
Sorry, my problem is not solved. I only want to use the funnel provided by tailscale on https port, so I can use caddy to manage my web server.

**Comment by shayne** [comment]
_You'll want to both configure TCP forwarding and enable Funnel._

There are two options for using Funnel to forward traffic to Caddy:



1) If you'd like Tailscale to manage the HTTPS certificate and terminate traffic to plain HTTP:
      > **Note**
      > The following assumes Caddy is running an HTTP server on port `80` on the server, change accordingly.
      
      ```console
      $ tailscale serve tcp --terminate-tls 80
      $ tailscale serve funnel on
      ```

2)  If you'd like to [use Caddy to manage the Tailscale HTTPS certificate](https://tailscale.com/blog/caddy/):
    > **Note**
    > The following assumes Caddy is running an HTTPS server on port `443` on the server, change accordingly.

    ```console
    $ tailscale serve tcp 443
    $ tailscale serve funnel on
    ```

Incoming traffic to your Funnel URL will be forwarded directly to Caddy. 🎉

**Comment by DentonGentry** [comment]
I'll assume the details in https://github.com/tailscale/tailscale/issues/7227#issuecomment-1437803145 are sufficient to resolve the issue. If not, please reopen the bug.

**Comment by kid1412621** [comment]
> _You'll want to both configure TCP forwarding and enable Funnel._
> 
> There are two options for using Funnel to forward traffic to Caddy:
> 
> 
> 
> 1) If you'd like Tailscale to manage the HTTPS certificate and terminate traffic to plain HTTP:
>       > **Note**
>       > The following assumes Caddy is running an HTTP server on port `80` on the server, change accordingly.
>       
>       ```console
>       $ tailscale serve tcp --terminate-tls 80
>       $ tailscale serve funnel on
>       ```
> 
> 2)  If you'd like to [use Caddy to manage the Tailscale HTTPS certificate](https://tailscale.com/blog/caddy/):
>     > **Note**
>     > The following assumes Caddy is running an HTTPS server on port `443` on the server, change accordingly.
> 
>     ```console
>     $ tailscale serve tcp 443
>     $ tailscale serve funnel on
>     ```
> 
> Incoming traffic to your Funnel URL will be forwarded directly to Caddy. 🎉

Seems the cli updated

**Comment by mk12** [comment]
Can this be reopened? The problem has not been solved. If you run a Tailscale funnel then it listens on port 443 and you can't run anything there yourself. I want to do both of these at once:

* Run a server on :443 which I can access locally and from other devices in my tailnet.
* Use a Tailscale funnel to expose some other port as https://mydevice.mytailnet.ts.net.

It seems the only way around this is to use another port like `--https 8443` but then the URL becomes https://mydevice.mytailnet.ts.net:8443 which I don't want.

Maybe there is some fundamental reason why it has to be this way, but I don't see why exposing port A via a funnel URL using port B (preferably 443 so there is no port in the URL) has to occupy port B locally.
