### ISSUE TITLE
Add ts_small build tag in addition to ts_omitfoo tags

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#7230]
Keep ts_omit* tags,
Add `ts_small` too (which implies all omits)
Add CI coverage that builds work with each omit separately and ts_small,
Update https://tailscale.com/kb/1207/small-tailscale/

**Comment by bradfitz** [comment]
We decided not to do `ts_small`, and instead just document the `build_dist.sh` `--extra-small` flag.

**Comment by bradfitz** [comment]
cc @WalterHub @maisem

**Comment by DentonGentry** [comment]
Replaced with 2442 in the www repo.
