### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by LordMerlin** [tailscale/tailscale#7237]
### What is the issue?

Good afternoon.
The situation is as follows. On the windows server 2008 R2 server, there was a tailscale from version 1.30 and worked normally. Then, when upgrading to the next version, it stopped showing the availability of the update in the program information.
I had to do it manually.
And since the next version 1.34.2, it stopped connecting. The service is running and the virtual adapter receives the 169.254.х.х address, but it is not possible to create a login. The browser does not open.
When trying to manipulate the console, it turned out that the problem is encryption.

C:\Program Files\Tailscale>tailscale debug ts2021
12:53:48.956455 Fetching keys from https://controlplane.tailscale.com/key?v=56 ...
12:53:59.176039 Do: Get "https://controlplane.tailscale.com/key?v=56": net/http: TLS handshake timeout
Get "https://controlplane.tailscale.com/key?v=56": net/http: TLS handshake timeout

C:\Program Files\Tailscale>tailscale update
Get "https://pkgs.tailscale.com/stable/?mode=json&os=windows": net/http: TLS handshake timeout

C:\Program Files\Tailscale>tailscale netcheck
2023/02/10 14:50:11 No DERP map from tailscaled; using default.
fetch prodDERPMap failed: Get "https://controlplane.tailscale.com/derpmap/default": net/http: TLS handshake timeout

When I execute the tailscale up command, the console hangs on this command forever.

### OS

Windows

### OS version

Windows Server 2008 R2 PS1

### Tailscale version

1.34.2, 1.36.0, 1.36.1

### Bug report

BUG-fa7ea62f7ef9614e254aa443aa857a41701e4d0d4098927316be16abe7803e13-20230210080814Z-8b412045954d5436

**Comment by DentonGentry** [comment]
At this point, I do not expect to address issues impacting Windows Server 2008. Tailscale 1.42 is the last version which will support Windows 7 and 8, and Windows Server 2008 and 2012. https://github.com/tailscale/tailscale/releases/tag/v1.42.0
