### ISSUE TITLE
FR: embed Tailscale in app/binary for api request routing & auth

### ISSUE THREAD

**Issue by voldyman** [tailscale/tailscale#7240]
### What are you trying to do?

I want to make my mobile app talk to the backend service through the tailnet.
The backend service is hosted in my home server and is exposed to the tailnet.

I **don't** want the mobile phone to run the Tailscale app, just my app.

context: I have a few self hosted services that run on my home servers and I want to give friends/family access to them but setting up Tailscale and having it be running when they use my app is too cumbersome for them.
If I could update my app to use Tailscale as a routing (+ maybe auth) layer then it’ll improve the user experience a lot for them.

### How should we solve this?

1. HTTP Client implementations for iOS, Android & Go which route tailnet connection requests and let non-tailnet requires go directly.

2. Ability to authenticate as an “app” to tailscale. This is fuzzy for me, maybe something like API key embedded in the app or oauth or <insert auth system of preference>

### What is the impact of not solving this?

People who want to access resources in a tailnet have to run the Tailscale VPN independently on their phones. While this works for tech friendly people, it makes it harder for less tech friendly people to use it.

### Anything else?

I can see this as a valuable feature for organizations developing apps as they can have an additional layer of security and potentially use Tailscale for auth instead of other third party services.

but it’ll be very nice to have for home users on the free tier too 🥹

**Comment by DentonGentry** [comment]
Does `tsnet` provide what you need for this?
- https://tailscale.com/blog/tsnet-virtual-private-services/
- https://pkg.go.dev/tailscale.com/tsnet

**Comment by voldyman** [comment]
ooh interesting, looks like the Go version already exists. 
Are there bindings for Swift/Obj-c and Java/Kotlin too?

**Comment by DentonGentry** [comment]
tsnet at present only exists for Go.

A common pattern for other environments is to use `tailscaled --tun=userspace-networking` and write the app to use SOCKS5: https://tailscale.com/kb/1112/userspace-networking/

**Comment by DentonGentry** [comment]
Closing as one of `tsnet` or SOCKS5 should work.
