### ISSUE TITLE
FR: Please update the docs to answer a couple questions (below)

### ISSUE THREAD

**Issue by emchristiansen** [tailscale/tailscale#7243]
### How should we solve this?

In the docs, can you please make it clear:

1. Which network protocols Tailscale bridges in the virtual LAN. Does it allow virtual "direct" connections for TCP, UDP, and ICMP, or just a subset of those?
2. How to tell if traffic is being routed through Tailscale DERPs. Alternatively, how to tell if a network is working fully as intended or if it is falling back to something less-than-ideal. (I have a bunch of machines behind various NATS, and I don't see how WireGuard UDP traffic could possibly be getting to the correct hosts, unless there's some really deep magic y'all are doing.)

### What is the impact of not solving this?

It'll make is clearer what Tailscale can and cannot do and how to tell if it's not properly set up.

**Comment by emchristiansen** [comment]
So, [this doc](https://tailscale.com/kb/1082/firewall-ports/) answers 2), though I had to pass `--json` to `tailscale status` to see whether relays were being used.

**Comment by bradfitz** [comment]
https://tailscale.com/kb/1018/acls/#acl-rules answers (1) ... any IP protocol that you permit.

**Comment by emchristiansen** [comment]
Thanks, I'd skipped that section because I didn't want to create any ACLs.

**Comment by bradfitz** [comment]
Most people don't care about anything other than TCP, UDP, ICMP, and ICMPv6, so those are the default allowed IP protocols. If you want to use SCTP or something weird, then you need to allow it explicitly.

**Comment by bradfitz** [comment]
You don't need `--json`, btw. `tailscale status` itself will tell you for active peers whether it's direct or relayed.
