### ISSUE TITLE
windows: iphlpapi.CreateIpForwardEntry2: The object already exists

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#725]
A user from a company with many nodes+routes is seeing:

```
2020-08-29 18:39:33.053232 -0600 -0600: setroutes: &{{10.33.64.0 ffffe000} 100.113.106.29 0}: iphlpapi.CreateIpForwardEntry2: The object already exists.
```

**Comment by apenwarr** [comment]
Specific things to look into:

1) Is it possible for tailcontrol to return multiple nodes that offer
the same subnet? (Probably yes, I suspect, and maybe it should,
depending how we want to do #299)

2) Does wgengine try to dedupe the routes before sending them along to
router? I thought it did, but maybe not. I think it should, as a
safety measure.

3) Does the Windows router abort after the first route failure, or
just skip the routes that fail to add? Sounds like the former, should
be the latter.

On Mon, Aug 31, 2020 at 3:25 PM Brad Fitzpatrick
<notifications@github.com> wrote:
>
> A user from a company with many nodes+routes is seeing:
>
> 2020-08-29 18:39:33.053232 -0600 -0600: setroutes: &{{10.33.64.0 ffffe000} 100.113.106.29 0}: iphlpapi.CreateIpForwardEntry2: The object already exists.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by bradfitz** [comment]
User reported:

> Removing the duplicate from my side, seems to fix the problem!!!
>
> ...
>
> Based on the error message you sent, I compared all my advertised subnets, and there were quite a few duplicates, so I cleaned them up. And it seems to fix the issue with all routes not being applied :)

So, yeah, sounds like we need to de-dup before handing it to Windows.

@danderson, any preferences where, given that you were recently working on intentional dups?

**Comment by apenwarr** [comment]
I really think we should check at least #2 and #3. For this to be a
bug requires all of #1, #2, and #3 to do the wrong thing. Let's not
just fix it once.

On Tue, Sep 1, 2020 at 12:01 AM Brad Fitzpatrick
<notifications@github.com> wrote:
>
> User reported:
>
> Removing the duplicate from my side, seems to fix the problem!!!
>
> ...
>
> Based on the error message you sent, I compared all my advertised subnets, and there were quite a few duplicates, so I cleaned them up. And it seems to fix the issue with all routes not being applied :)
>
> So, yeah, sounds like we need to de-dup before handing it to Windows.
>
> @danderson, any preferences where, given that you were recently working on intentional dups?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale

**Comment by bradfitz** [comment]
`wgengine/router/ifconfig_windows.go` certainly looks like it's trying to de-dup:

```go
        sort.Slice(routes, func(i, j int) bool {
                return (bytes.Compare(routes[i].Destination.IP, routes[j].Destination.IP) == -1 ||
                        // Narrower masks first                                                                                                                           
                        bytes.Compare(routes[i].Destination.Mask, routes[j].Destination.Mask) == 1 ||
                        // No nexthop before non-empty nexthop                                                                                                            
                        bytes.Compare(routes[i].NextHop, routes[j].NextHop) == -1 ||
                        // Lower metrics first                                                                                                                            
                        routes[i].Metric < routes[j].Metric)
        })

        deduplicatedRoutes := []*winipcfg.RouteData{}
        for i := 0; i < len(routes); i++ {
                // There's only one way to get to a given IP+Mask, so delete                                                                                              
                // all matches after the first.                                                                                                                           
                if i > 0 &&
                        bytes.Equal(routes[i].Destination.IP, routes[i-1].Destination.IP) &&
                        bytes.Equal(routes[i].Destination.Mask, routes[i-1].Destination.Mask) {
                        continue
                }
                deduplicatedRoutes = append(deduplicatedRoutes, &routes[i])
        }
        log.Printf("routes: %v\n", routes)

        var errAcc error
        err = iface.SyncRoutes(deduplicatedRoutes)
```

Not that there are any tests for that.

That slice sorting looks wrong.

Re 3), it does the former and aborts at the first failure in `winipcfg-go/interface.go`:

```go
// Adds multiple routes to the interface.                                                                                                                                 
func (ifc *Interface) AddRoutes(routesData []*RouteData) error {

        for _, rd := range routesData {

                err := ifc.AddRoute(rd)

                if err != nil {
                        return fmt.Errorf("%v: %v", rd, err)
                }
        }

        return nil
}
```

**Comment by bradfitz** [comment]
Yeah, fuzzed it:

```
X:\>router.test.exe -test.v
=== RUN   TestRouteLess
    ifconfig_windows_test.go:37: both compare less to each other:
                &winipcfg.RouteData{Destination:net.IPNet{IP:net.IP{0x1, 0x1, 0x1, 0x1}, Mask:net.IPMask{0x80, 0x0, 0x0, 0x0}}, NextHop:net.IP{0x2, 0x2, 0x2, 0x2}, Metric:0x1}
        and
                &winipcfg.RouteData{Destination:net.IPNet{IP:net.IP{0x0, 0x0, 0x0, 0x0}, Mask:net.IPMask{0xe0, 0x0, 0x0, 0x0}}, NextHop:net.IP{0x1, 0x1, 0x1, 0x1}, Metric:0x2}
--- FAIL: TestRouteLess (0.01s)
FAIL
```

**Comment by bradfitz** [comment]
Both 2) and 3) are done. Closing this.

Pushing unstable build 1.1.231.
