### ISSUE TITLE
sync-containers does not update `latest` and `stable` tags

### ISSUE THREAD

**Issue by ItalyPaleAle** [tailscale/tailscale#7251]
### What is the issue?

![image](https://user-images.githubusercontent.com/43508/218227880-96aa25b4-0522-44e1-a984-165179654ed0.png)

In GitHub Packages, the "latest" and "stable" tags are outdated and refer to an older build of Tailscale. Could you please make sure the tags are updated there too?

PS: Lots of people like me prefer GitHub Packages because Docker Hub is severely rate-limiting requests :(

**Comment by DentonGentry** [comment]
I think this means we need to enhance https://github.com/tailscale/tailscale/tree/main/cmd/sync-containers to move the `latest` and `stable` tags. It is pushing new versions like `v1.36.1` but the `latest` and `stable` tags still point to `v1.34.1`, the last one before we switched to using sync-containers.

**Comment by DentonGentry** [comment]
The code change to do this is in, but has not run yet.

**Comment by DentonGentry** [comment]
I just triggered the workflow manually and it updated `latest` and `stable` to 1.36.1.

**Comment by ItalyPaleAle** [comment]
Can confirm it's working, thank you!
