### ISSUE TITLE
umbrel node not connecting

### ISSUE THREAD

**Issue by 3nricomaz** [tailscale/tailscale#7256]
### What is the issue?

Good morning yesterday I wanted to try Tailscale on my Rasberry P4 on my Umbrel but after installation the icon remains in starting.
I also tried restarting but nothing changed.
how can i solve?
Thank you

### OS version

raspberry p4 whit umbrel

**Comment by DentonGentry** [comment]
We would need at bugreport to make any progress.
If Umbrel has a CLI, `tailscale bugreport` will generate one.

**Comment by 3nricomaz** [comment]
available to do what is needed but you have to help me step by step because I'm not very practical.

**Comment by DentonGentry** [comment]
Do you have a way to get a shell prompt on the Umbrel? Like SSH? If so, run: `tailscale bugreport`

Otherwise, you may need to get help on Umbrel forums for how to get a shell.

**Comment by 3nricomaz** [comment]
this what i get:
umbrel@umbrel:~ $ tailscale bugreport
-bash: tailscale: command not found
umbrel@umbrel:~ $

**Comment by 3nricomaz** [comment]
maybe solved the problem is using tor network. if you access my network with ip it works

**Comment by DentonGentry** [comment]
Based on https://community.getumbrel.com/t/setup-tailscale-subnet-router/11153 I guess this would be:
`~/umbrel/scripts/app compose tailscale exec web tailscale bugreport`

**Comment by mjschmidt** [comment]
~/umbrel/scripts/app compose tailscale exec web tailscale bugreport
BUG-7ddd2066e9a0e5b29e7830afdf733d8099ee2cce30aea5dfd217afd3977ae33c-20230306003607Z-a07ba6c7fe99c192

The issue appears to be in the get umbrel tor connector to tailscale 
```
ar 06 00:34:30.557 [notice] Tor 0.4.7.8 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
Mar 06 00:34:30.557 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Mar 06 00:34:30.557 [notice] Read configuration file "/tmp/torrc".
Mar 06 00:34:30.564 [warn] Unparseable address in hidden service port configuration.
Mar 06 00:34:30.564 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Mar 06 00:34:30.564 [err] Reading config failed--see warnings above.
Mar 06 00:35:32.014 [notice] Tor 0.4.7.8 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
Mar 06 00:35:32.014 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Mar 06 00:35:32.014 [notice] Read configuration file "/tmp/torrc".
Mar 06 00:35:32.046 [warn] Unparseable address in hidden service port configuration.
Mar 06 00:35:32.046 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Mar 06 00:35:32.046 [err] Reading config failed--see warnings above.
Mar 06 00:36:33.226 [notice] Tor 0.4.7.8 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
Mar 06 00:36:33.226 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Mar 06 00:36:33.226 [notice] Read configuration file "/tmp/torrc".
Mar 06 00:36:33.233 [warn] Unparseable address in hidden service port configuration.
Mar 06 00:36:33.234 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Mar 06 00:36:33.234 [err] Reading config failed--see warnings above.
```

**Comment by mjschmidt** [comment]
https://github.com/getumbrel/umbrel/issues/1365 offered to help here.

**Comment by DentonGentry** [comment]
There is some other process on that device creating and destroying network interfaces about once per second. I think the connectivity issues with the underlying device are the root cause.

```
2023-03-06 01:27:28.390234327 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=289, table=254
2023-03-06 01:27:28.390951471 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=289, table=255
2023-03-06 01:27:28.458496005 +0000 UTC: LinkChange: minor
2023-03-06 01:27:28.728412054 +0000 UTC: LinkChange: minor
2023-03-06 01:28:29.454900601 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=291, table=254
2023-03-06 01:28:29.455148395 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=291, table=255
2023-03-06 01:28:29.49366252 +0000 UTC: LinkChange: minor
2023-03-06 01:28:29.763450613 +0000 UTC: LinkChange: minor
2023-03-06 01:29:30.544190447 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=293, table=254
2023-03-06 01:29:30.544782091 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=293, table=255
2023-03-06 01:29:30.608406804 +0000 UTC: LinkChange: minor
2023-03-06 01:29:30.893002654 +0000 UTC: LinkChange: minor
```

**Comment by WaysideRewlz** [comment]
same, same - only different... was having problems with tailscale working... turns out after I disabled a net barrier type of anti malware/virus/intruder software, and another VPN type of thang - got it working... so be careful if you have one of those pesky critters running as although they protect you against ISIS/Hamas/Russian/N Korean/etc NoGoodNiks - they can fuque with your tailscale running smoothly...

**Comment by bradfitz** [comment]
Timeout.
