### ISSUE TITLE
FR: Can we see Tailscale on Endless OS in the near future?

### ISSUE THREAD

**Issue by wongjtf99** [tailscale/tailscale#7264]
### What are you trying to do?

Noticed that Podman is supported on Endless OS. So was wondering if a port of Tailscale to a Podman container is possible for Endless OS sometime in the future. Or a Flatpak package? Thanks

**Comment by DentonGentry** [comment]
Flatpak's sandboxing wouldn't let us ship Tailscale like that and have it work. It would only be able to provide the network within its container.

Similarly for a Podman container: Tailscale within a container provides connectivity in the container.

**Comment by wongjtf99** [comment]
Dear Denton,

Thought I'd ask anyway. Because I don't want to hack Endless OS if at all
possible. Thanks.

Best Regards,
Jeffrey Wong
