### ISSUE TITLE
Custom DERP Server Not working on 'some' mashines

### ISSUE THREAD

**Issue by curtisrecords** [tailscale/tailscale#7276]
### What is the issue?

- I have customized a DERP server, which works fine on my other nodes. However, I have added a new device that runs the common Proxmox 7.x version based on Debian 11.x (freshly installed using tailscale.com/install.sh).

- After running the "tailscale netcheck" command, I found that the official DERP server of tailscale can display latency and work as a normal relay, but when I checked on the problematic machine, I found that the latency column of the customized DERP server was empty. I cannot find the cause of the problem.

- Therefore, please help me locate the bug report and provide me with a general direction to solve the problem.

### OS

Linux

### OS version

Debian 11 (Proxmox Control Plane)

### Tailscale version

latest

### Other software

none

### Bug report

BUG-1a3e67a1e962a5dede37c46d1938da0c2b999c9e3db96727d19a40dd83c5d314-20230214054451Z-be19ef633a29867f

**Comment by bradfitz** [comment]
Sounds like your UDP isn't working. You should check your firewall rules, etc.

I see no uploaded logs for that BUG marker, though, so we won't be able to help more.

**Comment by curtisrecords** [comment]
i see `client nodekey xxxxxx not in set of peers tailscale` log in my derp server.

**Comment by curtisrecords** [comment]
> Sounds like your UDP isn't working. You should check your firewall rules, etc.
> 
> I see no uploaded logs for that BUG marker, though, so we won't be able to help more.

i see client nodekey xxxxxx not in set of peers tailscale log in my derp server.
