### ISSUE TITLE
Unable to connect or ping to Tailscale client

### ISSUE THREAD

**Issue by elisterr** [tailscale/tailscale#7279]
### What is the issue?

As this is the second time of asking, Im filing a bug report on the issue. 
Tailscale daemon in the status bar indicates that Tailscale is connected. But pinging tailscale IPs from command line (or connecting via ssh) doesn't work.

I want to reach 100.98.207.58 (and its subs at 192.168.8.0/24). 

### Steps to reproduce

Make sure Tailscale is connected.
Open powershell, type "tailscale status", output is something like:
100.102.184.123 mb16                 elisterr@    macOS   -
100.98.207.58   gl-a1300             elisterr@    linux   idle, tx 7284 rx 316

tailscale ping 100.98.207.58
pong from gl-a1300 (100.98.207.58) via DERP(par) in 206ms

ping 100.98.207.58
PING 100.98.207.58 (100.98.207.58): 56 data bytes
Request timeout for icmp_seq 0

ssh 100.98.207.58
ssh: connect to host 100.98.207.58 port 22: Operation timed out

Expected behavior

ping and connect to other hosts via tailscale should succeed

### Are there any recent changes that introduced the issue?

There were no changes applied. 
This is the second time it has happened. And in kind of in the same time frame. 

1) I set up the system and it all works. Its rechable from all of my devices in all of the platforms. 

2) After some shut-downs and restarts of the system, suddenly it is no longer reachable. All while the device is connected to the internet and is sending packets 24/7 (its streaming content from security videocam encoder).

### OS

Linux, Other

### OS version

OpenWrt

### Tailscale version

1.12.3-1 (OpenWrt)

### Other software

None. 

I also removed all firewall rules from the WAN router. Every port for incoming and outcoming UDP/TCP port is open. Had no effect. 

Also added every port to ACLs rules per each device IP. 

### Bug report

BUG-a7ab19314e0b42b723c2e242e6f35175f947b10cba1f1dd96d5ea99d4220d238-20230214130435Z-5256c1f4aaf4bb92

**Comment by DentonGentry** [comment]
Around the time of the bugreport:
```
2023-02-14 12:57:27.433511 +0000 UTC: open-conn-track: flow TCP 100.102.184.123:60285 > 100.98.207.58:22 rejected due to acl
2023-02-14 12:57:28.396204 +0000 UTC: open-conn-track: flow TCP 100.102.184.123:60285 > 100.98.207.58:22 rejected due to acl
```

The ACL for the tailnet lists a long series of address+port pairs, but 100.98.207.58:22 is not one of them.

**Comment by DentonGentry** [comment]
The root cause is ACLs blocking the connection.
You need to change the ACLs https://tailscale.com/kb/1018/acls/
