### ISSUE TITLE
FR: opening up the WireGuard information for a specific node

### ISSUE THREAD

**Issue by lincolnguang** [tailscale/tailscale#7286]
### What are you trying to do?

Dear Tailscale Inc,

I am writing to request a new feature for your product. As a user of Tailscale, I would like to request that you consider opening up the WireGuard information for a specific node in the future.

In many countries, users are unable to access the internet freely, and therefore, they often use other VPN software to bypass the restrictions. Tailscale is hardly compatible with other VPN software on mobile devices. 

### How should we solve this?

By providing the WireGuard information for a specific node, it would be much easier for them to connect other VPN devices and enjoy the benefits of Tailscale. I believe this feature would be highly appreciated by many users. 

### Anything else?

WireGuard can be used in many third-party software, including but not limited to: [Clash](https://github.com/Dreamacro/clash), [Surge](https://nssurge.com) and other tools.

**Comment by DentonGentry** [comment]
It is likely that at some point, Tailscale will support importing a Wireguard config to be able to connect to a node https://github.com/tailscale/tailscale/issues/3852

It is not likely that exporting a Wireguard config would work. Tailscale uses a Discovery protocol to find direct paths through NAT, which is not part of a regular Wireguard client. Exporting the Wireguard keys is not sufficient for some other Wireguard node to be able to connect to the tailnet.

**Comment by DentonGentry** [comment]
Closing as not feasible.

Going the other direction and importing a wireguard config is tracked in https://github.com/tailscale/tailscale/issues/3852
