### ISSUE TITLE
can't find approved machines

### ISSUE THREAD

**Issue by dengshenkk** [tailscale/tailscale#7289]
### What is the issue?

one account has multiple device, when i add new device and approved, after to look device list not include the new device.

what do i find this bug? when i reinstall tailscale. I got a error (duplicate nodekey) on console, 
and I remove the tailscale with brew (brew uninstall tailscale), then renew install tailscale, this is the reason

### Steps to reproduce

macos brew

1. install
```
brew install tailscale
sudo tailscaled install-system-daemon
tailscale status
tailscale login
```

2. uninstall
```
echo "setp 1. stop service"
brew services stop tailscale
sodu brew services stop tailscale
brew uninstall tailscale

echo "setp 2. remove file"
sudo rm -rf ~/Library/Containers/io.tailscale.ipn.macos
sudo rm -rf ~/Library/Containers/io.tailscale.ipn.macos.login-item-helper
sudo rm -rf ~/Library/Containers/io.tailscale.ipn.macos.network-extension
sudo rm -rf ~/Library/Containers/io.tailscale.ipn.macos.share-extension
sudo rm -rf /Library/LaunchDaemons/com.tailscale.tailscaled.plist

clear keys on Keychain include *tailscale*
```

3. install [1]

### Are there any recent changes that introduced the issue?

I have no idea

### OS

macOS

### OS version

monterey 11.6.6 (20G624)

### Tailscale version

1.36.1

### Bug report

BUG-c64e95b2439e9d16d55580a220256de602302373485dcbdfc483412ff713301e-20230215091037Z-d1a7a8eb8b7d160a

**Comment by DentonGentry** [comment]
> one account has multiple device, when i add new device and approved, after to look device list not include the new device.

What would be most useful would be anything about the new node: its hostname, its Tailscale IP address, or anything we could look up. If you're not comfortable putting this in a public bug, please contact support instead: https://tailscale.com/contact/support/

**Comment by dengshenkk** [comment]
ok, I will do this
