### ISSUE TITLE
MagicDNS name resolution fails on Windows clients

### ISSUE THREAD

**Issue by Tom7320** [tailscale/tailscale#7290]
### What is the issue?

MagicDNS name resolution fails on Windows clients:

```
PS C:\Users\ts> nslookup heise.de 100.100.100.100
Server:  magicdns.localhost-tailscale-daemon
Address:  100.100.100.100

*** heise.de wurde von magicdns.localhost-tailscale-daemon nicht gefunden: Server failed.

PS C:\Users\ts> nslookup heise.de
Server:  dns.google
Address:  8.8.8.8

Nicht autorisierende Antwort:
Name:    heise.de
Addresses:  2a02:2e0:3fe:1001:302::
          193.99.144.80

PS C:\Users\ts> tailscale version
1.36.1
  tailscale commit: 12fc975413493ea4c5b8bc87961d34eb52e9d61d
  other commit: 84afcfe6d7872304a956d8aa9f9cf63bfdd1cbe9
  go version: go1.19.4-tsdc0ce6324d
```

It does work on a Linux client (the client is also configured as an exit node):

```
ts@debian:~$ nslookup heise.de
Server:         100.100.100.100
Address:        100.100.100.100#53

Non-authoritative answer:
Name:   heise.de
Address: 193.99.144.80
Name:   heise.de
Address: 2a02:2e0:3fe:1001:302::

ts@debian:~$ nslookup heise.de 100.100.100.100
Server:         100.100.100.100
Address:        100.100.100.100#53

Non-authoritative answer:
Name:   heise.de
Address: 193.99.144.80
Name:   heise.de
Address: 2a02:2e0:3fe:1001:302::

ts@debian:~$ tailscale version
1.36.1
  tailscale commit: 12fc975413493ea4c5b8bc87961d34eb52e9d61d
  other commit: 84afcfe6d7872304a956d8aa9f9cf63bfdd1cbe9
  go version: go1.19.4-tsdc0ce6324d
```

It also does work on iOS.

MagicDNS is enabled:

![image](https://user-images.githubusercontent.com/19165864/219019472-9419947d-8885-46a8-93fb-521c6f285827.png)

### OS

Linux, Windows, iOS, Synology DSM

### OS version

Windows 11, Debian 11, iOS, DSM 7

### Tailscale version

1.36.1

### Other software

Pi-Hole (Docker container on Synology)

### Bug report

BUG-1ad3bbcf8adbcca4b4cb461cbaa2d5a736202b3fee65f30c2ec8e1480bdc8c31-20230215114345Z-4fe5d6582a3e1c91

**Comment by DentonGentry** [comment]
The issue being reported is that on Windows, this works: `nslookup heise.de`
and this does not work: `nslookup heise.de 100.100.100.100`
?

If so: I wouldn't consider this to be a bug. On Windows, the DNS configuration is pushed to the Windows resolver. DNS lookups are performed by Windows.

On Linux, [DNS is much more complex](https://tailscale.com/blog/sisyphean-dns-client-linux/) and 100.100.100.100 has to be able to handle queries for any destination.
- On Linux systems using `systemd-resolved` we mostly push the config into the platform and let `systemd-resolved` handle DNS lookups.
- On other Linux systems we put `100.100.100.100` into `/etc/resolv.conf` and handle all name resolution within tailscaled.

**Comment by Tom7320** [comment]
Ah, ok, thanks a lot for your comment! To be honest, I was not aware of the fact, that DNS resolution differs so much between a Linux and a Windows System. In my case, I think I had a different DNS problem related with Pihole. Unfortunately, I am still not absolutely sure what the issue is. I am still in investigation. But probably my DNS problem is not related with TS....
