### ISSUE TITLE
Can't connect to node in GNOME

### ISSUE THREAD

**Issue by ByteSeb** [tailscale/tailscale#7292]
### What is the issue?

I'm trying to add my Nextcloud server hosted on one of my Tailscale nodes to GNOME to be able to mount it. However, it never works. 

I already registered all my devices to the Tailscale net. In the web browser, ssh, Linux and Android Nextcloud app, I can use the private IP or device name given to my server to access it, and it works fine. However, when I try to add the Nextcloud account to GNOME from the settings app, it just freezes and never loads.

![image](https://user-images.githubusercontent.com/85042318/219124199-5a2d35d2-c011-456e-8e29-59682854f5ae.png)

If I try to mount it directly from Nautilus, with `davs://server/nextcloud` , `davs://192.168.0.92/nextcloud` (The Tailscale Private IP), or `server.tailnetname/nextcloud`, I get this error:

![image](https://user-images.githubusercontent.com/85042318/219124220-2ad1ca34-3d38-4b2a-9648-60b7929192a6.png)

Using other file browser like Caja or Nemo doesn't seem to work either:

![image](https://user-images.githubusercontent.com/85042318/219124331-41188e62-3c6d-4aff-b84a-af12305acfd0.png)

Not using Tailscale, and using another DDNS provider to access my server makes it work, so I'm guessing is an issue with Tailscale.

### Steps to reproduce

1. Register a node that hosts a Nextcloud server to the Tailnet (ex, "server")
2. Add a second Linux device running GNOME (ex, "linuxpc")

3. Try to add your Nextcloud server to GNOME from the Settings App (from linuxpc, type in the server's address)
![image](https://user-images.githubusercontent.com/85042318/219125083-ce68f25e-a7b4-4a10-8c4d-17ea79cfa884.png)

Alternatively, you can try to mount directly "server" from Nautilus (GNOME's default file browser):
![image](https://user-images.githubusercontent.com/85042318/219125944-b3501f80-8202-4de8-9ba8-e18a953a5485.png)

### OS

Linux

### OS version

Fedora 37

### Tailscale version

1.36.0

### Bug report

BUG-5a0556a333bc022001c5c6b36ea73360b937a4e022a26f7ba7f38d58a09dcf4e-20230215185916Z-f6caf21f05b4109a

**Comment by DentonGentry** [comment]
> davs://192.168.0.92/nextcloud (The Tailscale Private IP)

The Tailscale Private IP would be something in the 100.64.0.0/10 space, like 100.101.102.103.
The expectation is that 192.168.0.92 should be reachable via Tailscale somehow?

**Comment by ByteSeb** [comment]
> 
I mean, I don't really use the Private IP, I just use instead `davs://server/nextcloud` or `http://server/nextcloud`, which seems to work fine if I try it from the web browser and Nextcloud Clients

**Comment by DentonGentry** [comment]
> I just use instead davs://server/nextcloud or http://server/nextcloud, which seems to work fine if I try it from the web browser and Nextcloud Clients

Since the browser and Nextcloud client work using http://server/nextcloud, that means that MagicDNS and Tailscale connectivity are working.

`tailscale ip` will provide the Tailscale address:
```
me@ubuntu:$ tailscale ip -4
100.101.102.103
```

Does that work in the GNOME Settings app? If so, it means that something about GNOME's use of DNS isn't working.

**Comment by ByteSeb** [comment]
Trying that shows me an error:

> Error connecting to Nextcloud server: Connection refused

**Comment by DentonGentry** [comment]
"Connection refused" is interesting. It means that a TCP RST was sent back. Tailscale itself never sends an RST, so something else did:
- an intervening firewall like ufw
- nextcloud itself, possibly because it has bound to an interface like `eth0` and refusing packets from `tailscale0`

**Comment by DentonGentry** [comment]
Tailscale never sends an RST. The root cause is something else in the path blocking the connection.
