### ISSUE TITLE
Tailscale 1.36.1 on Macos 13.2 unable to login

### ISSUE THREAD

**Issue by solomon-b** [tailscale/tailscale#7298]
### What is the issue?

I am unable to turn on or add an account to Tailscale on Macos 13.2. I initially logged in when I first installed the application but have not been able to connect. No accounts show up in the "Logged In" menu and the "Add Another Account" button does nothing. Pressing the toggle switch to turn on Tailscale visually toggles to the on state but if I close and reopen the menu it is back to the off state.

I have tried rebooting the machine and reinstalling Tailscale.

Tailscale 1.36.1 was installed via the Apple App Store.

### Steps to reproduce

This happens on a fresh install of Tailscale.

### OS

macOS

### OS version

13.2

### Tailscale version

1.36.1

**Comment by DentonGentry** [comment]
We released a build to TestFlight that we believe should fix this problem. If you'd like to try it out, you can install version 1.37.101 using the instructions at https://tailscale.com/kb/1083/install-unstable/.

**Comment by solomon-b** [comment]
Thank you. I just installed `1.37.101` via TestFlight. The menu says `Loading...` and gives no options to login or add an account.

**Comment by mihaip** [comment]
Could you generate a bug report (https://tailscale.com/kb/1227/bug-report/) and include its ID here?

**Comment by bigfeetneedbigboots** [comment]
BUG-42da074e8ef7a230c1d080de664ea9d23a9bab1c11895699b60026f8ea43c72c-20230228043211Z-e304360b31df7630

**Comment by bigfeetneedbigboots** [comment]
It appears as though Tailscale is unable to launch the browser (Safari in my case) to allow the user to login.

**Comment by mihaip** [comment]
@bigfeetneedbigboots In your case I'm seeing that Tailscale is not able to complete the handshake with the coordination server, and thus doesn't get an auth URL (that it would then open your browser):

```
04:38:31 | control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": context canceled
04:38:32 | control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": context canceled
04:38:33 | control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": context canceled
04:38:34 | control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": context canceled
04:38:34 | control: TryLogin: register request: Post "https://controlplane.tailscale.com/machine/register": context canceled
```

Are you running any other VPN, firewall or content filtering software? Can you also include the output of `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021 --verbose` and `/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport --diagnose`?

**Comment by OakmontWillowVale** [comment]
@mewil thank you for looking into my bug report. It is working again now so maybe there was some sort of communications error with the coordination server at the time.  No point giving logs now I presume. 

For the record, no, I am not running any other VPN, firewall or content filtering - the services and settings on my Mac are exactly the same as they normally are when Tailscale works.

**Comment by brucealdridge** [comment]
I'm having this same issue on mac running `1.4.0`. Or at least it appears to be the same issue.  I have some other network stuff running but shouldn't be an issue, turning these off didn't fix it.

`BUG-9635870250def4e3217b165e8d4f3480b37fc4e973ef0ae99939100e2082e664-20230508043323Z-466a5f7abe4741fe`

```
16:33:06.367355 HTTP proxy env: (none)
16:33:06.367514 tshttpproxy.ProxyFromEnvironment = (<nil>, <nil>)
16:33:06.367525 Fetching keys from https://controlplane.tailscale.com/key?v=61 ...
16:33:07.839935 got public key: mkey:7d2792f9c98d753d2042471536801949104c247f95eac770f8fb321595e2173b
16:33:07.842341 Dial("tcp", "[2a05:d014:386:201:7200:6340:b22f:7df6]:80") ...
16:33:07.882989 Dial("tcp", "[2a05:d014:386:201:7200:6340:b22f:7df6]:80") = [2606:4700:110:8809:88f3:bb3e:cee3:45ff]:57831 / [2a05:d014:386:201:7200:6340:b22f:7df6]:80
16:33:08.347371 Dial("tcp", "[2a05:d014:386:202:24dd:46aa:f98e:9997]:443") ...
16:33:08.380066 Dial("tcp", "[2a05:d014:386:202:24dd:46aa:f98e:9997]:443") = [2606:4700:110:8809:88f3:bb3e:cee3:45ff]:57836 / [2a05:d014:386:202:24dd:46aa:f98e:9997]:443
16:33:08.470076 controlhttp.Dial = 0x140002ac050, <nil>
16:33:08.470100 did noise handshake
16:33:08.470111 final underlying conn: [2606:4700:110:8809:88f3:bb3e:cee3:45ff]:57831 / [2a05:d014:386:201:7200:6340:b22f:7df6]:80
```

**Comment by gingerbeardman** [comment]
Also getting this

BUG-785125f42b00ae239e98781383355bd83400ecbd607bab5d40f43e2ac48dd2d2-20230601223822Z-ebf3ff011d4081a6

**Comment by DentonGentry** [comment]
@brucealdridge I see little in common in the logs you posted with the logs elsewhere in this bug. Please file a new issue if it is still a problem.

**Comment by LLLavinia** [comment]
There was a time when I couldn't log in. I thought it was a software bug, but later I realized it was a network issue. I was able to log in smoothly using the cellular network on my phone (by connecting my Mac to iphone's hotspot)."

**Comment by rayzhudev** [comment]
I am having this issue as well. Macos 12.7 Nothing happens when I click log in

**Comment by MoritzLaurer** [comment]
Having the same issue with version 1.66.4

**Comment by PetrBrabec** [comment]
I had the same problem on public network - the log in button just was not doing anything. 

There should be some callout about this in the UI, non responsive button is very bad UX, I had to reinstall twice until I found @MoritzLaurer comment that helped...
