### ISSUE TITLE
Nameservers are not shown in admin console

### ISSUE THREAD

**Issue by gberenice** [tailscale/tailscale#7299]
### What is the issue?

We use Terraform resource [`dns_search_paths`](https://registry.terraform.io/providers/davidsbond/tailscale/latest/docs/resources/dns_search_paths) to add a list of search paths. It was successfully applied, and tested via `dscacheutil` - all the paths work correclty.

But there are no Split DNS entries shown in the web admin console:
<img width="712" alt="Screenshot 2023-02-17 at 13 27 31" src="https://user-images.githubusercontent.com/30597968/219639791-a32ddee4-a807-441f-b25e-aca28d5fbd2c.png">

### Steps to reproduce

1. Apply search paths terraform resource :
```
resource "tailscale_dns_search_paths" "default" {
  search_paths = ["dev.example.com"]
}
```
2. Check `Nameservers` in the admin console https://login.tailscale.com/admin/dns - it wasn't updated.

### OS

macOS

### OS version

Ventura 13.1

### Tailscale version

1.36.1

### Other software

[tailscale/tailscale](https://registry.terraform.io/providers/tailscale/tailscale/latest/docs) terraform provider v0.13.6

### Bug report

BUG-608d7d658e3af16bff7f3125a727ec509afe1710d6cc4b345a3dc8bc4e91fc00-20230217113707Z-e76115806ba38413

**Comment by DentonGentry** [comment]
We removed support for standalone search paths not tied to a nameserver about a year ago, the admin panel no longer renders search paths.

https://github.com/tailscale/tailscale/issues/2661 tracks the feature request to add SplitDNS entries with nameserver IP and domain name, which we would expect to additionally make available via terraform.

**Comment by gberenice** [comment]
Got you, thanks.
