### ISSUE TITLE
wireguard-go/wgcfg: write good implementation of CIDR.Contains

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#73]
(Using tailscale/tailscale's bug tracker instead of wireguard-go's)

I saw this code in https://github.com/tailscale/wireguard-go/blob/master/wgcfg/ip.go#L109 ....

```go
func (r *CIDR) Contains(ip *IP) bool {
	if r == nil || ip == nil {
		return false
	}
	// TODO: this isn't hard, write a more efficient implementation.
	return r.IPNet().Contains(ip.IP())
}
```

This bug is for that TODO. The current version allocates and does a lot of work.

Then again, I don't see anything calling it, so low priority.

**Comment by kroppt** [comment]
I was going to give this a shot - how would I do that? The GitHub for that repo is a bit hectic.

**Comment by crawshaw** [comment]
If you send a PR and I rebase it out from under you, I'll rebase your commit for you (and I'll make sure to preserve it as a separate commit from anything we do).

I'm going through a lot of rebasing in preparation for reviewing commits and sending them upstream. It's not pain I want anyone else to be subject to.
