### ISSUE TITLE
Tailscale not allowing RDP

### ISSUE THREAD

**Issue by btagomes** [tailscale/tailscale#730]
Hi, 

First of all, let me salut all the team that is developing Tailscale, its a great solution, i just love it!

I'm not very familiarized with the concept beind Tailscale, i've tried to narrow the sintoms but i'm not 100% sure of the real cause of the problem.
The issue that i'm facing is that i have an unraid server at home that runs Guacamole container and couple of VM's.
Some of those VM's are running Windows 10 with BitDefender Firewall and Tailscale app.
When Tailscale is not connected (on those machines) i can start an RDP session as much times as i want, i can close the browser, connect again, log out of windows, close de browser, login again, no trouble at all.
With Tailscale running, i can only establish the first RDP connection to those VMs. If i ever close the browser window without loging out of windows i cannot connect again, 
If i log out of windows before closing the browser everything is ok, but if i close the browser before loging out i stay locked outside.
I tried very possibilities, with/without firewall and the result is allways the same, everytime Tailscale is running on the remote machine i cannot forget to log out. 
Is this normal, is it a bug, can i change this behaviour?
Sorry about my english.
Thanks!

**Comment by bradfitz** [comment]
You want "server" or "headless" mode. That is #275.

Currently Tailscale on Windows requires that a user be logged in to the GUI. That is, Tailscale on Windows always runs in "client mode". We're working on adding opt-in "server mode" in #275.

**Comment by btagomes** [comment]
HI bradfitz, first lf all thanks for the quick reply.
Now i sort of understand what is happening.
Is there any way to force Tailscale to automaticaly disconnect whenever a rdp session is established to that machine?? These machines are not headless, at home they are used with display, keyboard and mouse, thats why i have tailscale instaled. When i'm away i connect trough Guacamole.

Thanks

**Comment by bradfitz** [comment]
Sorry, nothing to report yet. We're working on more options for Windows.

**Comment by btagomes** [comment]
Ok, thanks any way an keep on the good work!
My best regards
