### ISSUE TITLE
FR: Add tags to `client/tailscale/devices.go`

### ISSUE THREAD

**Issue by nicolasbernard** [tailscale/tailscale#7302]
### What are you trying to do?

I want to know all tags a device have in the API responses.

### How should we solve this?

- Adding a field in the `Device` struct (https://github.com/tailscale/tailscale/blob/main/client/tailscale/devices.go#L38)
- Updating the API backend to add this information (both in "GET device" and "GET tailnet devices")
- Update the doc (https://github.com/tailscale/tailscale/blob/main/api.md)

### What is the impact of not solving this?

I currently use https://login.tailscale.com/admin/machines and filter by tags.
With the API, I could make better tools.

### Anything else?

I think Tailscale is awesome.

**Comment by DentonGentry** [comment]
From: https://github.com/tailscale/tailscale/blob/main/api.md
`curl 'https://api.tailscale.com/api/v2/tailnet/example.com/devices'  -u "tskey-yourapikey123:"`

response:
```
{
  "devices": [
    {
      "addresses": [
         ...
      ],
      ...
      "os": "linux",
      "tags": [
        "tag:server"
      ],
      ...
    },

**Comment by nicolasbernard** [comment]
Thanks!

I went ahead and made a PR, my understanding is that the field just need to be here to be populated, let me know if something more is needed.
