### ISSUE TITLE
Android: stuck on 'loading' after welcome screen

### ISSUE THREAD

**Issue by IngCr3at1on** [tailscale/tailscale#732]
**Describe the bug**
App sticks on 'loading' after opening welcome screen.

**To Reproduce**
1. Open tailscale app after a fresh install
2. Click 'Get Started'
3. App is stuck on loading

**Expected behavior**
Login prompt

**Screenshots**
![Screenshot_20200902-170034](https://user-images.githubusercontent.com/922158/92042145-2c4a2280-ed3f-11ea-9500-336e5e23e2a2.jpg)

**Version information:**
 - Device: Pixel 4a
 - OS: Android
 - OS version: 10
 - Tailscale version: 0.2.20-0-gdfbfd2a

**Additional context**
I just got this phone today and transferred all my accounts from a Pixel XL onto it.

**Comment by bradfitz** [comment]
So Tailscale used to work on a different phone and you saw this after transferring your data to it? That is, this is state from a backup?

Does it work if you wipe the app's storage and log in from scratch?

/cc @eliasnaur

**Comment by IngCr3at1on** [comment]
@bradfitz not 'backup' but rather the 'transfer' function they built into newer android versions; the apps are basically just reinstalled login is usually required anyway... That said interestingly enough that does appear to have worked, thanks.

**Comment by jedduff** [comment]
Hi, 

I had the same issue when I uninstalled and reinstalled Tailscale.

Clearing data directly on the phone did nothing. I used ADB GUI Tool and cleared the data of com.tailscale.ipn and it worked!

![Snag_3820161a](https://user-images.githubusercontent.com/7997849/93120506-744b3c80-f691-11ea-81ec-cedd651706fb.png)



[tailscale.txt](https://github.com/tailscale/tailscale/files/5220100/tailscale.txt)
[tailscale cleardata.txt](https://github.com/tailscale/tailscale/files/5220108/tailscale.cleardata.txt)

**Comment by Gamms** [comment]
I have the same symptoms samsung galaxy s22 device 
I have installed the client, but it does not go further than this window. I tried to clear cache and reinstall - no help.

**Comment by DentonGentry** [comment]
This issue was resolved three years ago. I don't doubt you are seeing similar symptoms but it has a different cause.

Please open a new issue. If you are using an alternate web browser, please include that.
