### ISSUE TITLE
FR: Give a bit more detail on how to use tailscale pod as a K8s API proxy for local network, cross machine development

### ISSUE THREAD

**Issue by bayeslearner** [tailscale/tailscale#7322]
### What are you trying to do?
It seems like this should be straightforward, but I'm not a Linux or K8s guru, so any help is greatly appreciated. I think the documentation regarding K8s has already covered quite a few use cases, so this one may already be covered under the proxy mode.

### Why?
This would simplify the workflow of developers who use a different machine for development than the one that is running the Kubernetes cluster (minikube or microk8s, etc.).

###. How should we solve this?
How:

1. The Tailscale pod already has access from inside to the K8s API.
2. The documentation says:

```
export TS_DEST_IP="$(kubectl get svc <SVC_NAME> -o=jsonpath='{.spec.clusterIP}')"
```
So the SVC_NAME would be kubernetes.default.svc? 

3. Give an example of KUBECONFIG for the Tailscale proxy, such as:

```
- cluster:
  name: my-cluster
    insecure-skip-tls-verify: true
    server: http://proxy:(80?)
```

### Anything else?
Does this seem to be already available for inlets, another paid tunnel (vs VPN) solution?  
But I really like tailscale, as it is mostly free for personal use and works so well as a  personal private mesh network.

**Comment by DentonGentry** [comment]
I'd suggest using the operator, it is likely easier to get working for your purposes: https://github.com/tailscale/tailscale/issues/502#issuecomment-1414522795

**Comment by bayeslearner** [comment]
It says Creating an access proxy for apiserver. is something they are still working on?

**Comment by DentonGentry** [comment]
What exists now is an operator to handle incoming connections.
More may be coming in the future.

**Comment by uhthomas** [comment]
https://github.com/tailscale/tailscale/pull/7178 ?

**Comment by bayeslearner** [comment]
I get it working with existing operator.  Caveat: 
* you have to use the user credentials from your original kubectl setup.  The current operator doesn't generate know anything about it; 
* You need to rename the machine name representing the kubernetes service to "kubernetes". 
Otherwise you get this error (minikube):
```
E0302 16:38:17.752450   12366 memcache.go:238] couldn't get current server API group list: Get "https://default-kubernetes/api?timeout=32s": x509: certificate is valid for minikubeCA, control-plane.minikube.internal, kubernetes.default.svc.cluster.local, kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not default-kubernetes
```

Steps: 
1. default operator. 
2. add annotations to kubernetes.default.svc according to the doc. 
3. make a copy of existing kube config and modify the server to be `https://kubernetes`

**Comment by uhthomas** [comment]
I believe this issue can be closed @DentonGentry given https://tailscale.com/kb/1236/kubernetes-operator/#enabling-an-auth-proxy.
