### ISSUE TITLE
FR: Kubernetes namespace Tailscale routing and DNS lookups

### ISSUE THREAD

**Issue by dcarrion87** [tailscale/tailscale#7324]
### What are you trying to do?

I was going to raise this as a support request but thought this would be more appropriate here and might be able to get some ideas from the community.

We have centralised tenanted services within k8s namespace in one cluster. These services live in a k8s pod alongside tailscale and caddy sidecars. We have namespace tenanted interactive user pods in another k8s cluster. These pods access the central services via a tailscale proxy sitting in the same namespace using http_proxy mechanism.

<img width="922" alt="Screenshot 2023-02-19 at 3 02 25 pm" src="https://user-images.githubusercontent.com/2899172/219920241-3994cdb1-9f1d-4696-927a-3c0e8d48e06e.png">

We are wanting to get rid of the proxy mechanism because it's causing other issues for users accidentally routing traffic that isn't bypassed by no_proxy environment variable. Instead, we would like to route 100.64.0.0/10 traffic and split DNS lookups via a tailscale pod so when a user hits *.ourdomain.ts.net it makes its way via the tailscale pod. E.g. something like this?

<img width="919" alt="Screenshot 2023-02-19 at 3 09 41 pm" src="https://user-images.githubusercontent.com/2899172/219921658-16b46fe6-481a-4601-a4e2-bc2c03672e46.png">

Looking for ideas to go about doing this without over privileging a pod and whilst supporting multiple tenants. We need the routing and lookups to be namespaced as we have multiple of these tenants within the tailnet with separate labels.

### How should we solve this?

At this stage I'm not sure. Looking for ideas.

### What is the impact of not solving this?

Continuing to use proxy feature.

**Comment by DentonGentry** [comment]
![left](https://user-images.githubusercontent.com/1140756/221390923-d2d2ab15-6b15-4cf7-a4de-0960fd6139a5.jpg)

For the ingress portion on the left, the proxy you're referring to is the [SOCKS5 or HTTP Proxy used with `userspace-networking`](https://tailscale.com/kb/1112/userspace-networking/)?

An alternative is `--snat-subnet-routes=false`, described in https://tailscale.com/kb/1214/site-to-site/. It would allow the services on the right hand side of the diagram to see the source IP addresses of the originating clients.

**Comment by DentonGentry** [comment]
> when a user hits *.ourdomain.ts.net it makes its way via the tailscale pod.

This will need some extra effort: clients on the LAN subnets on the left don't have a way to get answers from MagicDNS. People have used https://github.com/damomurf/coredns-tailscale to do similar things, though, and it is worth a look.

**Comment by dcarrion87** [comment]
Thanks @DentonGentry for your input on this one. We'll see how those bits can potentially help us in this situation.

**Comment by DentonGentry** [comment]
At the moment I don't have anything else to respond with, closing for now. Reopen if needed.
