### ISSUE TITLE
FR: Port forwarding through exit nodes

### ISSUE THREAD

**Issue by qwe304** [tailscale/tailscale#7327]
### What are you trying to do?

I feel it would be helpful to allow an easy way to expose selected services on machines running inside a tailscale network to the internet through a specified port on an exit node.

**Comment by DentonGentry** [comment]
[Tailscale Funnel](https://tailscale.com/blog/introducing-tailscale-funnel/), currently available in an Alpha release, is a way to allow a public service to connect to the tailnet via ingress nodes which Tailscale provides — so it doesn't require an exit node.

If you do operate an exit node on your tailnet, it is a machine on the Internet like any other. You might choose to run a service on it, like [Caddy](https://caddyserver.com/), and allow public connections to it. Caddy running on the exit node can in turn make connections to nodes on your tailnet to provide backend services.

**Comment by DentonGentry** [comment]
Please reopen if that isn't sufficient.

**Comment by CMCDragonkai** [comment]
I tried using both funnel and exit node and there's something missing about the 2.

Tailscale funnel doesn't appear to allow me to run a P2P application that doesn't have NAT-busting capabilities on a CGNAT network (like a mobile internet).

Funnel exposes some ports and routes ingress (not even sure it can do UDP atm). Exit nodes provides an egress route. But to run a P2P app behind a CGNAT network I need something that route both ingress and egress.

So something convenient like an exit node plus port forwarding seems exactly what I need. Or perhaps enable the ability to combine the funnel feature with an existing exit node. But it's not clear how to do this.

**Comment by jnoxon** [comment]
@CMCDragonkai all you have to do is enable DNAT port forwarding on your exit node to a node inside your tailnet.

Example:

```
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport YOUR_PORT -j DNAT --to-destination YOUR_DEST_IP
```

**Comment by CMCDragonkai** [comment]
Will that mean the exit node's IP becomes the IP of the P2P app running in one of the hosts in the tailnet?

**Comment by jnoxon** [comment]
> Will that mean the exit node's IP becomes the IP of the P2P app running in one of the hosts in the tailnet?

Enabling the exit node does that.
