### ISSUE TITLE
FR: Include date of key expirey in `tailscale status --json --self`

### ISSUE THREAD

**Issue by papamoose** [tailscale/tailscale#7330]
### What are you trying to do?

https://tailscale.com/kb/1028/key-expiry/

I'd like a client to be able to report when it's key will expire. tailscale status --self --json currently does not report this information.

### How should we solve this?

Ideally, I'd like to be able to access it something like this so I can script getting notifications to send it wherever I wish.
```
tailscale status --json --self=true --peers=false | jq .Self.KeyExpire
```
Feel free to use whatever keyword you wish to use or tell me why the client doesn't provide this information already (maybe there's a good reason).

### What is the impact of not solving this?

I have no way of automating notifications to let me know when keys will expire. I'm aware of the webhook capability however, I do not wish to setup more infrastructure to ingest this information. My home network is minimal and I'd like to push a notification to discord/slack/etc.

**Comment by DentonGentry** [comment]
Does this work?
```
$ tailscale status --json --self=true --peers=false  | jq .Self.KeyExpiry
"2023-05-31T04:15:40Z"
```

--------

> I'm aware of the webhook capability however, I do not wish to setup more infrastructure to ingest this information. My home network is minimal and I'd like to push a notification to discord/slack/etc.

I don't really understand this as one can deliver the webhook to `https://hooks.slack.com/services/ABCDEF0123456789` without needing other infrastructure. It is the most common destination for [Tailscale Webhooks](https://tailscale.com/kb/1213/webhooks/)

**Comment by papamoose** [comment]
Sigh... my mistake. The key `.Self.KeyExpirey` doesn't exist if you disable key expirey.

Discord's slack compatible webhook doesn't receive a message when testing the end point: https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook
