### ISSUE TITLE
FR: Detect and report when ufw blocks `tailscale0`

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#7332]
### What are you trying to do?

https://github.com/tailscale/tailscale/issues/4917#issuecomment-1437684843 reports an exit node not working because ufw blocked it. `tailscaled` could detect when ufw is blocking, and:
- report it as a health check in `tailscale status`
- report it to the coordination server to turn into a warning

**Comment by raggi** [comment]
ufw programs rules via `iptables`, which may be either `iptables-legacy` or `iptables-nft`.

Somewhat common hand rolled ufw rules will block:

- UDP traffic to tailscale itself that does not match an existing flow
- Subnet router traffic to _local ip addresses_ (non-local addresses work fine)
- Exit node traffic to a _local ip address_ (non-local addresses work fine)

This is typically configured with `sudo ufw enable` when the distro has no other standard rules applied.

---

One option would be to use an application profile, unfortunately application profiles only appear to be able to solve for port unblocking, not unblocking tun traffic flows. Furthermore it becomes necessary to call the ufw CLI each time we update the application profile, so there's no advantage to this strategy.

---

### What we should do:

Explicitly add a rule to the firewall that enables $currentPort/udp then that would address the UDP issue, and if we insert the rule as we do our jump rules for routing, then they will take precedence over other rules, and users would no longer need to do `ufw allow 41641/udp` and similar, as seen in https://tailscale.com/kb/1082/firewall-ports/#my-devices-are-using-a-relay-what-can-i-do-to-help-them-connect-peer-to-peer

Explicitly add a rule to the firewall that allows "in" traffic on tailscale0, again inserted at the top of the chains, then users will no longer need to do `ufw allow in on tailscale0` as in https://tailscale.com/kb/1077/secure-server-ubuntu-18-04/?q=sudo%20ufw#step-4-allow-access-over-tailscale

Finally cleanup our KB articles on the topic, as referenced above, none of the locations describing interactions with ufw contain complete guidance for the necessary changes. Once the aforementioned changes are performed as part of our firewall configuration, no manual steps would be required by users in normal operation anymore.
