### ISSUE TITLE
Synology Outbound Access does not work as documented

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#7351]
### What is the issue?

Following this documentation, I setup an at-boot task: https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections

However, it appears that this task/script does not work properly. I cannot ping any other tailscale hosts. Firewall is not enabled and this is a brand new Synology appliance.

Tailscale 1.36.1
Synology DSM 7.1.1-42962 Update 4

Screenshots:

<img width="532" alt="Screenshot 2023-02-23 at 2 08 14 AM" src="https://user-images.githubusercontent.com/9159510/220840438-df700ae2-a643-451a-9847-e6e2cdc392d0.png">
<img width="534" alt="Screenshot 2023-02-23 at 2 08 07 AM" src="https://user-images.githubusercontent.com/9159510/220840440-9d988948-6e1e-475c-893a-d3140a4e42da.png">

### Steps to reproduce

Install Tailscale
Join to Tailnet
Follow these instructions: https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections

### OS

Synology

### OS version

DSM 7.1.1-42962 Update 4

### Tailscale version

1.36.1

### Bug report

BUG-4a51fe0c41e244ee9c88a0fa947cf10cf6c57f84367e97a3f0df4a15500c0cf7-20230223071016Z-9f597fa4b4b64749

**Comment by DentonGentry** [comment]
The node the Synology is trying to ping to is dropping the frames because ACLs do not allow access.

```
2023-02-23 07:00:23.342582305 +0000 UTC: Drop: ICMPv4{100.110.70.x:0 > 100.69.162.x:0} 84 no rules matched
```

I believe there are IP addresses in the Hosts block intended to allow this, but the IP address does not match the current Synology device. We'd recommend using tags for access control instead of IP addresses, for this reason.

**Comment by wingcomm** [comment]
@DentonGentry Good catch! Looks like this is not the issue after all.
