### ISSUE TITLE
Tailcale doesn't control traffic between servers in the same LAN

### ISSUE THREAD

**Issue by josedev-union** [tailscale/tailscale#7353]
### What is the issue?

I have installed tailscale on multiple servers running in the same LAN.
Then I tagged servers into 2 classes, tag:A and tag:B. Also I defined 2 user groups in ACLs, users-A and users-B. 
I allowed user-A to access tag:A servers and user-B to access tag:B servers. And I only allowed traffic between same tagged servers. i.e. tag:A cannot communicate with tag:B servers.

But I noticed that once user-A login to tag:A server, he can access to tag:B servers from A tagged server using LAN IP. LAN traffic is not controlled by tailscale ACLs.

How can I deny traffic between servers in the same LAN?

### OS

Windows

### OS version

10

### Tailscale version

1.36.1

**Comment by wingcomm** [comment]
Network traffic is always controlled by your device's routing table, not tailscale. Tailscale policies only affect to traffic destined for subnets in your Tailnet.

You should consider using a firewall with VLANS and network policies.

**Comment by DentonGentry** [comment]
> How can I deny traffic between servers in the same LAN?

You can use a subnet router if you wish, advertising the LAN CIDR. https://tailscale.com/kb/1019/subnets/

However I suspect it will be more productive to use local firewall rules if you want to control LAN traffic between LAN peers.

**Comment by DentonGentry** [comment]
Local firewalling like ufw should resolve this.
