### ISSUE TITLE
iOS: No connection via ssh

### ISSUE THREAD

**Issue by juev** [tailscale/tailscale#7360]
### What is the issue?

I use tailscale on multiple devices on my network. Several computers are configured to receive connections via ssh.

One of these computers is rpi.

I can connect to it from my laptop and to the usual address on the local network and Tailscale.

But on iOS, I can only connect to rpi at the local network address. The Tailscale address cannot be used.

To connect, I use ShellFish with identical connection parameters, only the ip address changes.

With one of the previous versions of Tailscale, I could connect from my phone to my computers. Now no.

What's the reason?

### OS

iOS

### OS version

16.3.1

### Tailscale version

1.36.2

### Bug report

BUG-753775b0a0c9533e1f047c7c8f9e6fd44487240c6234beb9fe77c23a78ee7004-20230224002156Z-53e700dc01435970

**Comment by juev** [comment]
One more. I can ping my rpi from iOS with local address. But not Tailscale address. For this I use Blink console. 

```
blink> ping 192.168.1.67
PING 192.168.1.67 (192.168.1.67): 56 data bytes
64 bytes from 192.168.1.67: icmp_seq=0 ttl=64 time=10.663 ms
64 bytes from 192.168.1.67: icmp_seq=1 ttl=64 time=10.531 ms
64 bytes from 192.168.1.67: icmp_seq=2 ttl=64 time=13.813 ms
64 bytes from 192.168.1.67: icmp_seq=3 ttl=64 time=9.230 ms
64 bytes from 192.168.1.67: icmp_seq=4 ttl=64 time=11.410 ms
64 bytes from 192.168.1.67: icmp_seq=5 ttl=64 time=10.361 ms
64 bytes from 192.168.1.67: icmp_seq=6 ttl=64 time=14.385 ms
64 bytes from 192.168.1.67: icmp_seq=7 ttl=64 time=4.941 ms
64 bytes from 192.168.1.67: icmp_seq=8 ttl=64 time=11.542 ms

--- 192.168.1.67 ping statistics ---
9 packets transmitted, 9 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.941/10.764/14.385/2.580 ms
blink> ping 100.99.253.13
PING 100.99.253.13 (100.99.253.13): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6

--- 100.99.253.13 ping statistics ---
8 packets transmitted, 0 packets received, 100.0% packet loss
blink> 
```

Report after ping:

BUG-753775b0a0c9533e1f047c7c8f9e6fd44487240c6234beb9fe77c23a78ee7004-20230224004949Z-0af10b68db959d45

**Comment by juev** [comment]
At the same time, I can use the exit-node from my other computer. Report after connecting and checking availability:

BUG-753775b0a0c9533e1f047c7c8f9e6fd44487240c6234beb9fe77c23a78ee7004-20230224005355Z-f44bd9c637ca04aa

**Comment by juev** [comment]
I tried disabling ssh in tailscale on rpi through the command:

```
sudo tailscale up --reset
```

But the result is the same.

BUG-753775b0a0c9533e1f047c7c8f9e6fd44487240c6234beb9fe77c23a78ee7004-20230224012025Z-ba56911794070327

**Comment by DentonGentry** [comment]
Shortly before the bug report about ping to 100.99.253.13 failing:

`2023-02-24 00:52:59.362914 +0000 UTC: ^38.5M wgcfg: skipped node IPs: 100.90.x.y from "mbp-REDACTED" ([D7X9T]), fd7a:115c:a1e0:ab12:q:r:s:t from "mbp-REDACTED" ([D7X9T]), 100.90.x.y from "REDACTED" ([IQzBg]), ... , 100.99.253.13 from "raspberrypi" ([J8Eb/]), ...`

I think this might be normal for iOS when it decides it can add a single route for 100.64.0.0/10, but it needs to be confirmed.

**Comment by juev** [comment]
I updated Tailscale to 1.38.2, after that I still can use my exit nodes, but I cant connect to my servers via ssh.

New reports:
BUG-753775b0a0c9533e1f047c7c8f9e6fd44487240c6234beb9fe77c23a78ee7004-20230329093421Z-39b4741c292f028e

**Comment by juev** [comment]
I tried reinstalling Tail scale many times, tried connecting to different servers. All to no avail.

I noticed that the rotation of keys for my phone is disabled in the control panel. And after reinstalling, I always had a phone already connected to the network. 

Today I tried to manually logout and reauthorize. After that, the connection began to work.

**Comment by DentonGentry** [comment]
So, something wrong in the saved preferences presumably.
I doubt we'll figure out what that was.
