### ISSUE TITLE
Tailscale client 

### ISSUE THREAD

**Issue by PowershellScripter** [tailscale/tailscale#7367]
### What is the issue?

I authenticated and activated a node in unattended mode and for testing purposes I expired the node using the API, which did not disconnect the node. So, I went to the client system and told it to logout and it shows logged out but the node is still able to connect to the network and send ping requests to other nodes. I did a tailscale down and then a tailscale status and the node is showing logged out but still sending packets, even with new ping requests.

### Steps to reproduce

1 - Authenticated node in unattended mode
2 - Started continuous ping request
3 - Expired node using API (which should have offlined the connection with the node)
4 - Expired node directly on the system using (Tailscale logout) - didnt offline it
5 - Used (Tailscale down) and verified logged out - still able to send requests.

Extra - Cant run tailscale bugreport as tailscale showing logged out

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.36.1

**Comment by PowershellScripter** [comment]
Uninstalled tailscale client and turned off DERP and it is still connecting to nodes. Re-installed using 1.36.2 and connected with and without using --unattended mode and then used tailscale logout and tailscale down and it is still connecting to nodes and not taking down the tailscale service.

**Comment by DentonGentry** [comment]
Can you provide the Tailscale IP address, or a `tailscale bugreport` during the time it is active? Without some ability to get telemetry we won't make much progress.

**Comment by PowershellScripter** [comment]
> Can you provide the Tailscale IP address, or a `tailscale bugreport` during the time it is active? Without some ability to get telemetry we won't make much progress.

Says: BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

not sure how to get logging on the node

**Comment by DentonGentry** [comment]
Are you using a Headscale control server?

--no-logs-no-support is an option which can be passed to `tailscaled`. Headscale automatically adds it.

**Comment by PowershellScripter** [comment]
> Are you using a Headscale control server?
> 
> --no-logs-no-support is an option which can be passed to `tailscaled`. Headscale automatically adds it.

yes, headscale control server. I also reported the issue to headscale as I wasnt sure who i should be reporting this issue too.
I took the headscale server down and the connections stay alive which is why i thought it may be a windows client issue

**Comment by bradfitz** [comment]
The Tailscale data plane can keep working even if the control plane (the "Headscale server" or whatever) isn't running. That's a feature. Packets don't pass through the Headscale server.

Sounds like this is working as intended?

**Comment by PowershellScripter** [comment]
> The Tailscale data plane can keep working even if the control plane (the "Headscale server" or whatever) isn't running. That's a feature. Packets don't pass through the Headscale server.
> 
> Sounds like this is working as intended?

Okay, good to know. But what about the tailscale client still connecting to other nodes even when using tailscale logout and tailscale down?

**Comment by DentonGentry** [comment]
> But what about the tailscale client still connecting to other nodes even when using tailscale logout and tailscale down?

The control plane handles revocation of node keys when clients leave. The Headscale project issue is the right place to handle that.

**Comment by PowershellScripter** [comment]
> > But what about the tailscale client still connecting to other nodes even when using tailscale logout and tailscale down?
> 
> The control plane handles revocation of node keys when clients leave. The Headscale project issue is the right place to handle that.

@DentonGentry is still still true even if you expire the node directly from the client using (tailscale logout)? Sorry, still kinda new to the tailscale / headscale framework.
