### ISSUE TITLE
Windows connecting to exit node loses IPv6 with 1.36.2

### ISSUE THREAD

**Issue by meagarow** [tailscale/tailscale#7378]
### What is the issue?

window10启用exit node 模式后笔记本插电状态下IPV6地址消失，断电后却显示ipv6地址

### Steps to reproduce

启动软件，exit node 远程一台服务器，cmd中原本直连的ipv6地址消失，变为relay状态，非充电状态ipv6地址又出现

### Are there any recent changes that introduced the issue?

版本更新 1.36.1还可以使用，1.36.2就出现了这个bug

### OS

1.36.2

### OS version

1.36.2

### Tailscale version

1.36.2

**Comment by DentonGentry** [comment]
> What is the issue?

After Windows 10 enables exit node mode, the IPV6 address disappears when the notebook is plugged in, and the IPv6 address is displayed after the power is turned off.

> Steps to reproduce

Start the software, exit node to a remote server, the original directly connected ipv6 address in cmd disappears, and changes to the relay state, and the non-charging state ipv6 address appears again

> Are there any recent changes that introduced the issue?

The version update 1.36.1 can still be used, and this bug appeared in 1.36.2

**Comment by DentonGentry** [comment]
Can you run `tailscale bugreport` in `cmd.exe`?

Google:
你能在 `cmd.exe` 中运行 `tailscale bugreport` 吗

**Comment by meagarow** [comment]
> Can you run `tailscale bugreport` in `cmd.exe`?
> 
> Google: 你能在 `cmd.exe` 中运行 `tailscale bugreport` 吗

谢谢你的回复，tailscale bugreport可以运行，但我已经因为这个bug重装系统了，重装后不再出现问题，导致这个问题的原因大概率是我之前安装了VALORANT: Riot，它的安全检测删除了一些重要文件
Thank you for your reply. The tailscale bugreport can run, but I have reinstalled the win10 system because of this bug. There are no problem after reinstallation. The reason for this problem is probably that I installed VALORANT: Riot before, and its security detection deleted some important files
