### ISSUE TITLE
FR: Allow gitops-pusher to use the OAuth token retrieval

### ISSUE THREAD

**Issue by farcaller** [tailscale/tailscale#7394]
### What are you trying to do?

I want to use the [oauth](https://tailscale.com/kb/1215/oauth-clients/) with a scoped api key for the gitops-pusher.

### How should we solve this?

https://github.com/tailscale/tailscale/pull/7393

### What is the impact of not solving this?

gitops-pusher requires manual key rotation and that sucks.

**Comment by DentonGentry** [comment]
Merged https://github.com/tailscale/tailscale/pull/7393
