### ISSUE TITLE
Provision for allowing a different dns port in web admin view 

### ISSUE THREAD

**Issue by beyondszine** [tailscale/tailscale#740]
Hi there,

Can someone please tell me if there is a way to use other than standard (53) port for dns name resolution.  In the dns pane, when it allows user to enter IP address of dns server, if its possible to supply port number also.

My Scenario:
I am running a few VMs on one of my machines and programs like libvirtd are already running dnsmasq on standard port.  I want to use this machine as a dns server for the name resolution. so that I can run one more instance of dnsmasq with another port.  This can enable me to use tailscale without affecting my current setup at all.

Kindly suggest if something entirely different & more appropriate should be done here.

**Comment by DentonGentry** [comment]
I don't think we have a way to do this right now, the admin panel doesn't support things like "8.8.8.8:1053" and we don't have it plumbed all the way through to the clients in any case. Every client has different ways to add DNS servers: MacOS and windows have their APIs, Android has an API on VpnServiceBuilder, Linux has several flavors of /etc/resolv.conf and systemd.

TBH: I think it is unlikely we'll add support for alternate ports given the amount of effort in clients and the possibility that one or more client platforms may just not have a way to do this. We're likely to add support for things like DNS-over-TLS, which implies using a different port, but probably not alternate ports for regular DNS.

**Comment by beyondszine** [comment]
Thanks @DentonGentry for your reply.  I understand your point & appreciate your clear statement.
AFAIR, I had to manually copy my entries for name resolution (for all my devices) & add to current server to get my work done.

P.S. I also thought at that time, may be if possible, a free dns service like [duckdns](https://www.duckdns.org/) can be somehow introduced to the ecosystem, to give another level of abstraction & ease of name resolution for cases like mine, so that if name resolution requests are not being able to satisfy from one NS, then it can be resolve by 2nd open one.
For example: I added `shandylaptop.duckdns.org` for my laptop where I was not able to modify things to my server because of already existing complicated settings of VMs.

**Comment by DentonGentry** [comment]
One can certainly add a duckdns instance as a DNS server in https://login.tailscale.com/admin/dns

As of the Tailscale 1.8 release, one can make an entry of a DNS server to use for a specific domain, for example to direct queries for *.example.com to a duckdns instance and use one's choice of global nameservers for all other domains.

At this point I'm going to close this issue, I don't think there is more which could really be addressed.
