### ISSUE TITLE
Printer ping works after setting up subnet router but while giving print command to esc pos printer it cannot establish print connection

### ISSUE THREAD

**Issue by immortalsantee** [tailscale/tailscale#7406]
### What is the issue?

I am trying to print in ESC/POS printer from a flutter app.

I am able to ping my printer ip address by `ping 192.168.1.100`. `.100` is my printer. But when i try to give print command using 4g from flutter app from iPhone, it cannot establish a printer connection.

I cannot understand what is going wrong here. When i connect to wifi, it can give print command. but when switching back to 4g, it cannot give print command.

Any help would be appreciated.

Thanks

### Steps to reproduce

- Subnet router configure as `192.168.1.0/24`
- In tailscale console admin I enabled Subnet router as well.
- Now i `ping` to `192.168.1.100` from my mobile using network application on 4G network. It shows green signal.
- Now I try to give print command. It cannot establish connection and fails the print command.

I am [this](https://pub.dev/packages/esc_pos_printer) flutter library for giving print command.

### OS

Linux

### OS version

Ubuntu

### Tailscale version

1.36.1

### Other software

https://pub.dev/packages/esc_pos_printer

### Bug report

BUG-ec04d8311814a2301b75f7cc27e93683ae1a715b7bdf493ce27e3fb9b6a666d9-20230301122202Z-5065d714e5dc49ce

**Comment by DentonGentry** [comment]
We see ACL evaluations that the iPhone is able to connect to the printer:
```
2023-02-28 10:08:58.144948066 +0000 UTC: Accept: TCP{100.121.x.y:64715 > 192.168.1.100:9100} 64 tcp ok
2023-02-28 10:11:25.767104962 +0000 UTC: Accept: TCP{100.121.x.y:64753 > 192.168.1.100:9100} 64 tcp ok
2023-02-28 10:57:48.341868968 +0000 UTC: Accept: TCP{100.121.x.y:50520 > 192.168.1.100:9100} 64 tcp ok
2023-02-28 10:57:48.342043803 +0000 UTC: Accept: TCP{100.121.x.y:50521 > 192.168.1.100:9100} 64 tcp ok
```

I think it is managing to get connectivity, but then something else goes wrong.

One thing to note is that the Tailscale link MTU is 1280 bytes, while Wifi is 1500 bytes. Since the iOS app is running directly on the Tailscale network it should know that and only offer an MSS of 1280 bytes, but if there is any kind of packet size setting which says 1500 it would be best to set it to 1280 instead.

**Comment by DentonGentry** [comment]
Problem believed to be MTU, please reopen if not.
