### ISSUE TITLE
FR: Provide static link to the latest Windows installer.

### ISSUE THREAD

**Issue by straeb** [tailscale/tailscale#7408]
### What are you trying to do?

We're rolling out Tailscale on new Windows Servers via Script. Among other things, it downloads the .msi installer from https://pkgs.tailscale.com/stable/. Therefore it would be nice to have a static link to the latest stable version of the .msi/.exe installers in place. Right now the links are bound to a fixed version.

### How should we solve this?

Provide static link to the latest Windows installer on `pkgs.tailscale.com` like `https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi`

### What is the impact of not solving this?

Re-Check the current version and adapting the script before every install.

**Comment by DentonGentry** [comment]
These links all work:
https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe
https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi
https://pkgs.tailscale.com/stable/tailscale-setup-latest-arm64.msi
https://pkgs.tailscale.com/stable/tailscale-setup-latest-x86.msi

**Comment by DentonGentry** [comment]
Closing as already done.
