### ISSUE TITLE
FR: install.sh - Add support for PureOS

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#7410]
### What are you trying to do?

Customer wrote in:

> Since PureOS is a rebranded/slightly modified Debian (PureOS 10 "byzantium" release, based on Bullseye), would it be possible to add support to the [tailscale.com/install.sh](http://tailscale.com/install.sh) script for this OS? There are versions for both x86-64 (for the Desktops/Laptops) and ARM64 (for the Librem 5). Here's the info (from the phone):

```
OS=other-linux

VERSION=

PACKAGETYPE=

UNAME=Linux pureos 6.1.0-1-librem5 #1 SMP PREEMPT Mon Feb 20 03:51:00 UTC 2023 aarch64 GNU/Linux

ID=pureos

NAME=PureOS

PRETTY_NAME=PureOS

VERSION_ID=10.0

VERSION_CODENAME=byzantium

HOME_URL="https://pureos.net/"

SUPPORT_URL="https://puri.sm/faq/#faq-WherecanIfindoutmoreaboutPureOS"

BUG_REPORT_URL="https://tracker.pureos.net/"
```

**Comment by patrixl** [comment]
Thanks!
