### ISSUE TITLE
FR: More Subnet Routers on Personal Pro

### ISSUE THREAD

**Issue by tasi333** [tailscale/tailscale#7420]
### What are you trying to do?

Add more subnet routers to personal pro plan

### How should we solve this?

Add an option to the pro plan to add more subnet routers to the personal pro plan, I'd be willing to pay extra for that add-on.

### What is the impact of not solving this?

I have 3 out of 2 subnet routers hitting the "soft limit", I would like to add more but not move from the personal pro plan.

**Comment by DentonGentry** [comment]
To set expectations: this is the issue tracker for the open source components used in Tailscale. Though you're welcome to make requests about how the business operates, they are unlikely to be treated like bugs to be fixed.

**Comment by tasi333** [comment]
> To set expectations: this is the issue tracker for the open source components used in Tailscale. Though you're welcome to make requests about how the business operates, they may not be treated like bugs to be fixed.

Thanks @DentonGentry, so what's the best way to make this suggestion? I wasn't sure and just used the Feature Request option.

**Comment by zhaofengli** [comment]
This can be closed since [the new pricing scheme](https://tailscale.com/blog/pricing-v3) has removed the subnet router limit :tada:

**Comment by DentonGentry** [comment]
https://tailscale.com/kb/1154/free-plans-discounts/
