### ISSUE TITLE
Subnet routes do not work when using `go/bin/tailscaled`

### ISSUE THREAD

**Issue by ScubaDrew** [tailscale/tailscale#7424]
### What is the issue?

When I use `go/bin/tailscaled` on macos, endpoints exposed via subnet router do not work.

The same routes work via the app store app.

### Steps to reproduce

Setup a subnet router, try and access the exposed subnet routes via the App store app (will work) and via the `go/bin/tailscaled` (will not work)

### Are there any recent changes that introduced the issue?

None.

### OS

macOS

### Tailscale version

13.2.1 (22D68)

### Bug report

BUG-606cea925d83fb77eee87becb48f506f1510a24dd278d33c27678984fc67f361-20230302041756Z-94c93a54aa779cea

**Comment by DentonGentry** [comment]
The App Store version of the Tailscale app, and the Windows client, and the iOS and Android clients, all accept subnet routes by default. As the earliest client and the one most often itself used as a subnet router, he CLI client used on Linux — and [Tailscaled-on-macOS](https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS) — does not. It has to be told to accept routes:
`tailscale up --accept-routes`

Telemetry from around the time of the bugreport:
`2023-03-02 04:15:24.095268 +0000 UTC: authReconfig: ra=false dns=true 0x01: <nil>`

The ra=false means it isn't accepting routes. Adding `--accept-routes` to the command should resolve the problem.
