### ISSUE TITLE
FR: how to build a lib for ios ui client

### ISSUE THREAD

**Issue by starup** [tailscale/tailscale#7461]
### What are you trying to do?

i am trying to develop a ios client to connect my headscale control server.

### How should we solve this?

give me some suggestion to compile the ios lib for the swift code to invoke.

### What is the impact of not solving this?

i can't connect headscale server from the appstore ui client.

### Anything else?

i can build the wireguard ios client, it is build the wireguard-go static lib. so how to build tailscale static lib?

**Comment by crawshaw** [comment]
Hello. We don't provide user support for headscale (just engineering time working on the project), and we don't open source our clients for closed-source platforms. So I am closing this issue.
