### ISSUE TITLE
FR: Auto-Updater on Windows

### ISSUE THREAD

**Issue by Stephen988** [tailscale/tailscale#7463]
### What are you trying to do?

Hello Tailscale Team, need a feature for update version on Windows automatically

### How should we solve this?

Integrate an internal updater without download from browser new .exe or preferably auto updater feature.

### What is the impact of not solving this?

Tailscale remains at the same version.

### Anything else?

For example I not access frequently on RDP to my Windows Server, so it remain with old version until I update it manually.

**Comment by Stephen988** [comment]
> Duplicate of #755
> 
> `tailscale update --yes` is implemented in Tailscale 1.36 and might be useful for your purposes.

I'm not so practice, how to use this command?

**Comment by DentonGentry** [comment]
In a Windows cmd.exe, run: `tailscale update --yes`

It does not yet run automatically, but is the basis of how we will do so.
