### ISSUE TITLE
FR: documentation typo

### ISSUE THREAD

**Issue by iraklis10** [tailscale/tailscale#7475]
### What are you trying to do?

https://tailscale.com/kb/1226/tailnet-lock/
Peer nodes **can then can** verify the signature before allowing connections. In this manner, you control which nodes are trusted to be in your tailnet, as well as which nodes are trusted to sign other nodes.

### How should we solve this?

Fix grammar error above

### What is the impact of not solving this?

None

**Comment by WalterHub** [comment]
Fixed at https://tailscale.com/kb/1226/tailnet-lock/.

Thank you for noting the issue!
