### ISSUE TITLE
Not starting the tray icon on windows 7 SP1

### ISSUE THREAD

**Issue by aneeshvahini** [tailscale/tailscale#7486]
### What is the issue?

Not starting the tray icon on windows 7 SP1

### OS

Windows

### OS version

Win 7 SP1

### Tailscale version

1.36

**Comment by DentonGentry** [comment]
We won't make any progress on this, there is no information of what happens. We test Win7 SP1 as part of our release process, so it isn't broken on all Win7 systems.

Note that Go 1.21 is dropping support for Windows 7 and 8, which we expect within 6 months. The Tailscale 1.38.1 release earlier today still supports Windows 7. but not many more releases will. We'd recommend updating to a newer OS.

**Comment by prairiewolf11** [comment]
Can you please offer one link to download tailscale1.38.1?there is no download link tailscale official website. I also search other web,but no found .

**Comment by DentonGentry** [comment]
The final release of 1.38 was 1.38.4: https://pkgs.tailscale.com/stable/tailscale-setup-1.38.4.exe
