### ISSUE TITLE
Tailscale on macOS fails to auto-login - hangs on silicon mac

### ISSUE THREAD

**Issue by quartermarsh** [tailscale/tailscale#7497]
### What is the issue?

Tailscale is set to start at login after reboot. Instead, it keeps attempting but never succeeds. Tailscale must be quit and restarted, then it logs in instantly.

### Steps to reproduce

Reboot the machine with 'start at login' enabled for Tailscale.

### Are there any recent changes that introduced the issue?

none known

### OS

macOS

### OS version

13.2

### Tailscale version

1.36.2 (App Store)

### Other software

Little Snitch, LuLu, two Proton VPN profiles (disabled)

### Bug report

 BUG-884d808aecbdfba6204cafaf91513e9e33c6f4abaaae04d2a7ce26b1df074135-20230307235946Z-1e949aabdc2f7521

**Comment by quartermarsh** [comment]
Second bug report. Taken after quitting Tailscale and manually logging in.

BUG-884d808aecbdfba6204cafaf91513e9e33c6f4abaaae04d2a7ce26b1df074135-20230307235946Z-1e949aabdc2f7521

(double check the timestamps on these bug reports - I may have submitted them backwards :/)

**Comment by quartermarsh** [comment]
Oh drat. It’s intermittent. :/

I toggled Start On Login off, then on again before doing a restart. This time Tailscale logged in successfully after a few seconds. It does come up very early in the boot sequence it seems.

Still, there might be something of interest in the first bug report.

**Comment by wingcomm** [comment]
I had a similar issue in 1.36.0, 1.36.1. 1.36.2 fixed it for me. Strange that its causing issues for you.

**Comment by wingcomm** [comment]
Why do you have both Little Snitch and LuLu? I'd try disabling both to see if the issue recurs.

**Comment by quartermarsh** [comment]
@wingcomm 

> Why do you have both Little Snitch and LuLu?

I find the alerts from LuLu kinda handy. And it plays nicely with LS. 😊

**Comment by quartermarsh** [comment]
@mihaip I’ve rebooted several times now and the issue hasn’t reoccoured. I’d still be curious to know if there’s anything of interest in that first bug report if you have a moment to take a look. Thx!

**Comment by mihaip** [comment]
Not seeing anything in the initial attempt logs -- it was able to connect to the coordination server successfully, but it never got a netmap (the list of all the machines in your tailnet). As far as I can tell the coordination server was operating correctly at the time though, so no clues as to why it never heard anything.

**Comment by quartermarsh** [comment]
@mihaip Thanks for checking. :)
