### ISSUE TITLE
tailscale0 has no mac address and cannot run

### ISSUE THREAD

**Issue by lmq8267** [tailscale/tailscale#7500]
uname -a
Linux Newifi3 3.4.113 #2 SMP Fri Feb 24 17:29:47 +09 2023 mips GNU/Linux

Running tailscale shows：`Program starting: v1.36.2, Go 1.20.1: []string{"/tmp/tailscaled/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/var/run/tailscale/tailscaled.sock"}
LogID: 73e09bb6d3acdb95cb3e0dff51850484dc21016c3f7d4a5ad7f336299bfb7b67
logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/cmd.log.conf: open /var/lib/tailscale/cmd.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/cmd.log.conf: config is nil
wgengine.NewUserspaceEngine(tun "tailscale0") ...
setting link attributes: setsockopt: protocol not available
router: disabling tunneled IPv6 due to system IPv6 config: disable_ipv6 is set
dns: [rc=unknown ret=direct]
dns: using "direct" mode
dns: using *dns.directManager
link state: interfaces.State{defaultRoute=eth2.2 ifs={br0:[192.168.20.1/24 dc00:101:101::1/64] eth2.2:[192.168.30.10/24 2409:7d57:ce56:77e0:8846:46gf:bf67:b/64 2409:7d57:ce56:77e0:8846:93ff:fe41:b/64 fd4f:d5ff:10d1:0:2276:93ff:fe41:b/64] ztvr58oya6:[192.168.191.20/24 fcfb:6o79:aa08:cb3:f113::1/40]} v4=true v6=true}
magicsock: disco key = d:da54fc4bbc75346f
Creating WireGuard device...
Bringing WireGuard device up...
Bringing router up...
Clearing router settings...
Starting link monitor...
Engine created.
external route: up
pm: migrating "_daemon" profile to new format
got LocalBackend in 315ms
Start
Backend: logs: be:73e09bb6d3acdb95cb3e0dff51850484dc21016c3f7d4a5ad7f336299bfb7b67 fe:
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
health("overall"): error: state=NeedsLogin, wantRunning=false
wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
monitor: RTM_NEWROUTE: src=, dst=2600:1f18:429f:9305:4043:217b:512c:f8d4/128, gw=fe80::6295:ceff:fe9c:90f4, outif=7, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1/128, gw=ff02::1, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=7, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=8, table=254`

keeps showing, can't run
![tailscale](https://user-images.githubusercontent.com/119713693/223614900-7becc1eb-33e5-483d-9d0f-d8f09c7dc7dc.PNG)

### OS

Linux

### OS version

padavan

### Tailscale version

1.36.2  go 1.20.1

### Other software

zerotier

**Comment by DentonGentry** [comment]
`tailscale0` isn't supposed to have a MAC address. It is a TUN device, meaning there isn't an L2 interface the way one might be used to.

I don't immediately see a reason in the output shown. Please run `tailscale bugreport` and paste the output here, as it may nonetheless be uploading telemetry which we can look into.

Also:
> zerotier

Running multiple VPNs simultaneously rarely works. They fight over every resource: routing table, firewall rules, DNS settings.

**Comment by DentonGentry** [comment]
`state=NeedsLogin`

Did `tailscale up` print out a URL to use to authenticate?
https://tailscale.com/kb/1017/install/

**Comment by lmq8267** [comment]
> `state=NeedsLogin`
> 
> 是否`tailscale up`打印出用于身份验证的 URL？ https://tailscale.com/kb/1017/install/

user bugreport: BUG-73e09bb6d3acdb95cb3e0dff51850484dc21016c3f7d4a5ad7f336299bfb7b67-20230308035625Z-0b7892fb356c935d
user bugreport hostinfo: {"IPNVersion":"1.36.2","OS":"linux","OSVersion":"3.4.113","Container":false,"Desktop":false,"Hostname":"Newifi3","Machine":"mips","GoArch":"mipsle","GoArchVar":"softfloat","GoVersion":"go1.20.1"}
user bugreport health: state=NeedsLogin, wantRunning=false

**Comment by lmq8267** [comment]
> `state=NeedsLogin`
> 
> 是否`tailscale up`打印出用于身份验证的URL？ https://tailscale.com/kb/1017/install/
Yes, the URL is output

**Comment by lmq8267** [comment]
> `tailscale0` isn't supposed to have a MAC address. It is a TUN device, meaning there isn't an L2 interface the way one might be used to.
> 
> I don't immediately see a reason in the output shown. Please run `tailscale bugreport` and paste the output here, as it may nonetheless be uploading telemetry which we can look into.
> 
> Also:
> 
> > zerotier
> 
> Running multiple VPNs simultaneously rarely works. They fight over every resource: routing table, firewall rules, DNS settings.

When it is normal, there is a display of mac, and when it is abnormal, there is no mac address

**Comment by DentonGentry** [comment]
Please exit zerotier, I think the two VPNs are fighting over the routing table.

```
2023-03-08 04:32:29.104428903 +0000 UTC: monitor: RTM_NEWROUTE: src=, dst=240e:380:af9b:r:q:r:s:t/128, gw=fe80::6295:ceff:fe9c:90f4, outif=7, table=254
2023-03-08 04:32:29.118974718 +0000 UTC: LinkChange: minor
2023-03-08 04:32:30.106207621 +0000 UTC: monitor: RTM_NEWROUTE: src=, dst=dc00:w:x::1/128, gw=fe80::6295:w:x:y, outif=7, table=254
2023-03-08 04:32:30.123907234 +0000 UTC: LinkChange: minor
2023-03-08 04:32:31.841709811 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff05::q/128, gw=ff05::c, outif=8, table=254
2023-03-08 04:32:31.842750195 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff0e::q/128, gw=ff0e::c, outif=8, table=254
2023-03-08 04:32:31.853443468 +0000 UTC: LinkChange: minor
2023-03-08 04:32:32.116748841 +0000 UTC: LinkChange: minor
2023-03-08 04:33:01.857294002 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=240e:380:af9b:r:q:r:s:t/128, gw=fe80::q:r:s:t, outif=7, table=254
2023-03-08 04:33:01.857976365 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=dc00:101:101::1/128, gw=fe80::q:r:s:t, outif=7, table=254
2023-03-08 04:33:01.858343124 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=7, table=254
2023-03-08 04:33:01.869096559 +0000 UTC: LinkChange: minor
2023-03-08 04:33:02.131855406 +0000 UTC: LinkChange: minor
2023-03-08 04:33:31.873422671 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff02::1/128, gw=ff02::1, outif=8, table=254
2023-03-08 04:33:31.874479579 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff05::q/128, gw=ff05::c, outif=8, table=254
2023-03-08 04:33:31.875235684 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff0e::q/128, gw=ff0e::c, outif=8, table=254
2023-03-08 04:33:31.88753112 +0000 UTC: LinkChange: minor
2023-03-08 04:33:32.151791031 +0000 UTC: LinkChange: minor
2023-03-08 04:34:29.227025462 +0000 UTC: monitor: RTM_NEWROUTE: src=, dst=240e:380:af9b:r:q:r:s:t/128, gw=fe80::q:r:s:t, outif=7, table=254
2023-03-08 04:34:29.242693675 +0000 UTC: LinkChange: minor
2023-03-08 04:34:30.253067164 +0000 UTC: monitor: RTM_NEWROUTE: src=, dst=dc00:w:x::1/128, gw=fe80::q:r:s:t, outif=7, table=254
2023-03-08 04:34:30.267857073 +0000 UTC: LinkChange: minor
2023-03-08 04:34:31.905617194 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=8, table=254
2023-03-08 04:34:31.906448582 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff05::q/128, gw=ff05::c, outif=8, table=254
2023-03-08 04:34:31.90723998 +0000 UTC: monitor: RTM_DELROUTE: src=, dst=ff0e::q/128, gw=ff0e::c, outif=8, table=254
```

--------

> When it is normal, there is a display of mac, and when it is abnormal, there is no mac address

No. `tailscale0` does not have a MAC address. An interface functioning normally lists all zeros.

```
tailscale0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 100.119.x.y  netmask 255.255.255.255  destination 100.119.x.y
        inet6 fd7a:115c:a1e0:ab12:q:r:s:t  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::q:r:s:t  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
```

**Comment by lmq8267** [comment]
关闭了zerotier还是一直显示`Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
health("overall"): error: state=NeedsLogin, wantRunning=false
blockEngineUpdates(true)
wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=7, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::fb/128, gw=ff02::fb, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1/128, gw=ff02::1, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::2/128, gw=ff02::2, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=7, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::fb/128, gw=ff02::fb, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1:ff5d:789a/128, gw=ff02::1:ff5d:789a, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1/128, gw=ff02::1, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff02::1:2/128, gw=ff02::1:2, outif=7, table=254
monitor: RTM_DELROUTE: src=, dst=ff05::c/128, gw=ff05::c, outif=8, table=254
monitor: RTM_DELROUTE: src=, dst=ff0e::c/128, gw=ff0e::c, outif=8, table=254`

can't run successfully

**Comment by DentonGentry** [comment]
**Something** is fighting over routes in the routing table. You shouldn't see constant RTM_NEWROUTE + RTM_DELROUTE every few seconds.

We don't have the visibility to help you figure out what that is. If you're trying to piece together VPN and networking products to get through a firewall, you're gong to need to work on that yourself.

**Comment by lmq8267** [comment]
OK，
Thank u
answer patiently
