### ISSUE TITLE
authRoutine for-loop backoff is not working proerly

### ISSUE THREAD

**Issue by win-t** [tailscale/tailscale#7501]
https://github.com/tailscale/tailscale/blob/48f6c1eba4e29fdac9b0f807ee50dcefa387471d/control/controlclient/auto.go#L409

the `err` will be nil here, because we already check `err != nil`
https://github.com/tailscale/tailscale/blob/48f6c1eba4e29fdac9b0f807ee50dcefa387471d/control/controlclient/auto.go#L388

**Comment by bradfitz** [comment]
That resets it.

**Comment by win-t** [comment]
I realize this issue from this problem https://github.com/juanfont/headscale/pull/1256, 
tailscale keeps hitting headscale without back-off

**Comment by win-t** [comment]
> That resets it.

is it the proper behavior?

**Comment by bradfitz** [comment]
Sure looks like it's intentional.

Could you back up and explain the problem in full, without linking to another PR which similarly lacks context?

**Comment by win-t** [comment]
from the comment here https://github.com/tailscale/tailscale/blob/48f6c1eba4e29fdac9b0f807ee50dcefa387471d/control/controlclient/auto.go#L395-L397

It tells us that some control servers don't get it right (including headscale), and I think the author's intention of `bo.Backoff(ctx, err)` line is to do the backoff.
But they forgot that err is nil here, so instead of backoff, they reset the backoff
