### ISSUE TITLE
This error happened after updating OS on Rasbian Buster

### ISSUE THREAD

**Issue by DiamondDemon669** [tailscale/tailscale#7535]
### What is the issue?

After running the tailscaled daemon this happens. I think some IP rules were deleted but I cant tell what

```
Starting link monitor...
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5210 Table:254 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5230 Table:253 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5250 Table:0 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5270 Table:52 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
Engine created.
LinkChange: minor
flushing log.
logger closing down
2023/03/12 02:16:47 logtail: dialed "log.tailscale.io:443" in 126ms
router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's
getLocalBackend error: store.New: invalid character 'd' looking for beginning of value
```

### Steps to reproduce

Installing any version of tailscale and running `sudo tailscaled` or starting with systemd causes this issue

### Are there any recent changes that introduced the issue?

I recently updated to the latest version of raspbian buster

### OS

Linux

### OS version

Debian buster

### Tailscale version

1.33.370-1.36.2

### Other software

The problem seems to be with systemd-networkd, but it references ip rules, which wireguard interfaces with

**Comment by maisem** [comment]
The last line in the log points to something corrupting the tailscaled state file

It also looks like you are running a really old unstable release, which can have bugs as the name suggests.

**Comment by DentonGentry** [comment]
deleting /var/lib/tailscale and removing the device from https://login.tailscale.com/admin/machines will allow it to authenticate afresh.

**Comment by DiamondDemon669** [comment]
Thanks for pointing me to the issue! apparently tailscale was writing logs to the state file... somehow... and it got corrupted.
