### ISSUE TITLE
Cannot use more than one nic

### ISSUE THREAD

**Issue by mengxifl** [tailscale/tailscale#7536]
### What is the issue?

I had 2 nic to access network .  

nic1  can access tailscale server  .  nic2 cannot access .

when I  start  client  I can not use service 

next  I delete nic2  It work . but some time I need nic2 to do something 

I think  client  only use  nic2 to find server . when I use client  Is there any way to use more than 1 nic  ?  

### OS

Windows

### OS version

11

### Tailscale version

1.34.2

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/2331
