### ISSUE TITLE
Why tailscale send this HTTPS localhost DNS query?

### ISSUE THREAD

**Issue by ngocphamm** [tailscale/tailscale#7556]
### What is the issue?

Maybe not an issue but a design? I don't know, but I'm curious on why it needs to do that.

I use Adguard Home for my home network, and I noticed recently (it looks like it's more frequent lately) that there are those queries for `localhost` of type `HTTPS` (I didn't even know about this type of DNS query before at that point). 

![image](https://user-images.githubusercontent.com/395123/224864056-64f33d80-3b1d-43fb-b809-2faf964955c0.png)

After some time, I have been able to identify which app sending those queries, and it's Tailscale.

What is the reason for those DNS queries from Tailscale?

### Steps to reproduce

1. Find a way to capture DNS queries for your system
2. Install and run Tailscale on a machine
3. Will see those queries after a bit. It could be a few hours. I think I saw the queries being sent at pretty random times.
4. Turn off/quit Tailscale. The DNS queries will stop too.

### OS

macOS

### OS version

macOS Ventura 13.2.1

### Tailscale version

1.36.2

### Other software

* Little Snitch
* Wireguard
* VMWare Fusion

### Bug report

BUG-66adb3f3c2f8fd9a3932d14ae3864bcae52817bb29a21b549fa84e6c597f9830-20230314005613Z-cda8b9e9d499a43b

**Comment by bradfitz** [comment]
I would argue you haven't yet done step 1 ("Find a way to capture DNS queries for your system") if that's all your tool shows you. :)

But if you've got a pcap file you can email it to support@tailscale and reference this bug and we'll let you know what it is.

But otherwise there's not enough to go on here so I'll close this in the meantime.

**Comment by ngocphamm** [comment]
I put it that way because there're many ways to do so, and for me it's Adguard Home, but I don't think it's practical to tell anyone else to set that up just for that purpose.

I actually have pcap file for those queries so I will send an email.

**Comment by DentonGentry** [comment]
We received the pcap file to support@tailscale.com, and yes it is indeed sending "localhost" in a Question.

I don't immediately know why: whether it is an internal lookup for something `tailscaled` is doing, or whether something else on the box is looking up "localhost" and `tailscaled` sends it upstream.

**Comment by ngocphamm** [comment]
@DentonGentry Thank you for having a look. Please let me know if you need more information on how I have Tailscale set up, and its settings on my machines.

**Comment by DentonGentry** [comment]
Is this causing an actual problem?
We quite deliberately do not get telemetry about specific DNS lookups, it is difficult to say why the lookup is happening.

--------

Almost all occurrences of "localhost" in code are in unit tests. The ones I can find which could conceivably be turning into DNS lookups in a running instance are:
- tailscale web, which I'd expect only on platforms like Synology or pfSense
https://github.com/tailscale/tailscale/blob/b4d3e2928b6b389ed3ac320143bf863f550ba237/cmd/tailscale/cli/web.go#L89
- net/interfaces/interfaces.go:HTTPOfListener() which I don't immediately know when it would be called https://github.com/tailscale/tailscale/blob/b4d3e2928b6b389ed3ac320143bf863f550ba237/net/interfaces/interfaces.go#L594
- client/tailscale/localclient.go, which would get called reasonably often https://github.com/tailscale/tailscale/blob/b4d3e2928b6b389ed3ac320143bf863f550ba237/client/tailscale/localclient.go#L100

I guess it is possible that the localclient lookup is not being resolved locally by /etc/hosts (or equivalent) and ending up as a DNS query.

**Comment by ngocphamm** [comment]
@DentonGentry I don't really notice any issues as an end user. I'm gonna let you know, in general, my setup.

1. I have 2 macs, 1 ios, 1 Raspberry Pi (which also hosts AdguardHome), and one remote PC
2. 1 mac is permanently on my home network, which uses AdguardHome (DNS pointed to the Raspberry Pi via DHCP). This one is the first one I notice sending those DNS queries.
3. The other mac, and the ios sometimes on the network (at that point will point to Raspberry Pi for DNS, the same with with the mac above), and whenever they are on, after some time, I see DNS queries from those too (in AdguardHome).
4. On the macs, where I have the UI to control Tailscale settings, I leave it like below. Except for that permanent home mac, which has `Allow Incoming Connections` enabled. AFAIK, there is no Exit Node in my Tailscale network.
   * So from my understanding, I'm not using Tailscale DNS, so there should be no need for Tailscale to listen to my DNS queries and send it upstream? 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/395123/225022153-bb9dcfc7-111c-46e5-b8f5-cf31ffa0beb3.png">
