### ISSUE TITLE
Server reports offline, but it is not

### ISSUE THREAD

**Issue by Raltrwx** [tailscale/tailscale#7567]
### What is the issue?

A machine of mine has been reporting the past few days that it is offline. This is incorrect, the machine responds to pings, and I am SSH'ed into it currently, can access via VNC, all using the tailscale network to do so. 

### Steps to reproduce

None, I simply noticed a machine that is working in production but reported as offline in tailscale. 

### Are there any recent changes that introduced the issue?

Not that I know of. My tailsale devices are deployed into disparate and seperate networks that I have no control over. They may have modified their network. 

When investigating myself, I first updated from 1.34 -> 1.36.2 but all that did was refresh the "last online time" in the admin page, and still shows as solidly offline. Then I ran an `apt update && apt upgrade`, rebooted, and still showing offline in status & the admin page, but still 100% accessible/reachable. 

### OS

Linux

### OS version

Ubuntu 18.04

### Tailscale version

1.36.2

### Other software

1. Our own custom software that is packaged in docker containers
2. Netdata for HW monitoring
3. VNC server for accessing over tailscale (Also works, despite the server being "offline", and I specifically use the tailscale network to reach it)

### Bug report

BUG-bd200f35d1496cdea84b357879f5f5f6d2fcb82aad106f958f98ace2700ceb4e-20230314210901Z-66a1a63d7121ef55

**Comment by bradfitz** [comment]
"offline" means it's not connected to the control plane getting updates about peers.

But Tailscale's data plane (packets) keeps working for the most part even when it's not connected to the control plane, as long as peers don't move around too much.

**Comment by MattGeale** [comment]
Just wondering if this issue is still going on or is in the process of being investigated/rectified? I've found this bug on two separate OS's; Debian and Arch.

Server reports offline but is still reachable by the end devices.

**Comment by DentonGentry** [comment]
As described, this isn't even a bug:
- Tailscale is a mesh. Nodes establish direct Wireguard tunnels between themselves, sending packets to all known IP addresses of the other until they get a response.
- The coordination server is not involved in the moment-to-moment operation of the tailnet. Clients exchange endpoint information using DERP relays, without needing the coordination server.
- Therefore a node can be out of contact with the coordination server yet still establish new Wireguard tunnels with peers and exchange data.

If you need to determine whether a node is reachable, you need to try to reach it. The coordination server state is not a reasonable indication for whether a node can transfer data to peers on the tailnet.

**Comment by MattGeale** [comment]
Ah thanks for clarification.

Turns out my ISP had inadvertantly turned on CGNAT in the past few days on my network by accident.

Since got them to revert that and the container is playing nice.

Cheers!

**Comment by huyz** [comment]
This is quite confusing. I'm sure most people would make the same mistake. How about renaming "offline" to something else. How about "uncoordinated" 😄  ?

**Comment by tsmoneta** [comment]
I'm curious why all other nodes would not have the offline status in a stable tailnet then? I'm currently seeing this offline state for an Android device (at home, not switching networks), while all other devices (including Android devices) are not 'offline'.

**Comment by StarryFire** [comment]
I am not able to use the server as an exit node because of this...

**Comment by boybatak07** [comment]
> I am not able to use the server as an exit node because of this...

Me too :(

**Comment by Phoenix616** [comment]
> I am not able to use the server as an exit node because of this...

Facing the same problem now too, did anyone ever find a solution for this issue?

**Comment by boybatak07** [comment]
I connect all my user devices to the exit node server before running starting heavy services in it. I find it that the user devices remain attached to the exit node server even if they get the notification that the exit node server is offline.


> > I am not able to use the server as an exit node because of this...
> 
> Facing the same problem now too, did anyone ever find a solution for this issue?

**Comment by Tunji17** [comment]
I have the same issue, Also i can no longer use the `tailscale serve` url

**Comment by CptCurk** [comment]
Hey, 

Got the same issue here. 
Would love to know if I have to do something to get it online and being able to use is as exit node. 

Btw I could advertise it in the control panel. That means it's connected to the control panel.
