### ISSUE TITLE
Entire tailnet suddenly stops working, out of nowhere, nothing was changed to cause this

### ISSUE THREAD

**Issue by Funtimes909** [tailscale/tailscale#7569]
### What is the issue?

a few days ago my entire tailnet stopped working, when connecting to any exit node within the tailnet, all internet from the device stops working until the exit node connection is dropped, this happens on any and all devices. Strangely I can use OpenSSH client (NOT tailscale ssh) to connect to the exit node, but not other clients connected

### Steps to reproduce

try connecting to your tailnet

### Are there any recent changes that introduced the issue?

I moved my Debian 12 desktop to arch linux, the day after I did that everything stopped working, that desktop was an exit node and nothing else, using other exit nodes still doesn't work

### OS

Linux

### OS version

Arch Linux  (Kernel 6.2.6-arch1-1)

### Tailscale version

1.36.2

### Other software

I have a pihole running on my raspberry pi, but I've disabled that entirely and the problem still persists.

### Bug report

BUG-456ac33eed68b13fe7ec87bfdc857679ff0972c3cfffb6101cacfeffe2caaadc-20230314224523Z-f96a818478dfa946

**Comment by DentonGentry** [comment]
We cannot reasonably work on this in a public bug, too much private information.
The issue needs to stay on the support ticket.
