### ISSUE TITLE
FR: Expose Operating System Version in Machines Web UI

### ISSUE THREAD

**Issue by cablespaghetti** [tailscale/tailscale#7573]
### What are you trying to do?

The latest client release makes note of support being dropped for a few different versions of Windows and MacOS. However I have no way of seeing in the admin console whether I have any users still using these old versions. It would be really useful if the client could pick up the OS version and expose this information to admins.

### How should we solve this?

Add an extra field on the machines detail page and preferably make it visible and filterable in the overall machines list.

### What is the impact of not solving this?

Finding out from users when they can't upgrade their Tailscale client to the latest. I acknowledge we probably should have some external device management solution to solve this, but that is unfortunately not that case for all devices at the moment.

**Comment by zofrex** [comment]
Exposing the OS version is relatively easy, being able to filter by it will be more involved. In light of that I have created [a new ticket to track the feature request to filter the machines list by OS version](https://github.com/tailscale/tailscale/issues/7633), and I'll keep this one for exposing the OS version only.

One note: I don't think exposing it in the overall machines list is easy, there isn't a mechanism to choose which information is exposed, and there's only room for so many fields on that screen. If that is a particular requirement I would recommend filing a separate ticket for that too, as I think it's likely to be more work than exposing the information on the machine detail page.

I'll update this ticket with progress on exposing the OS version.

**Comment by icio** [comment]
Thank you for your suggestion, @cablespaghetti. We've just deployed our first pass at the OS and OS Version filters. Please do let us know how you get on!

You can, for example, apply filters like "macOS older than 13.5" as `os:macos osversion:<13.5`: https://login.tailscale.com/admin/machines?q=os%3Amacos+osversion%3A%3C13.5
