### ISSUE TITLE
FR: Ability to create grouping for hosts in ACL

### ISSUE THREAD

**Issue by ProfFrnswrth** [tailscale/tailscale#7587]
### What are you trying to do?

When working with a long list of host entries, instead of explicitly defining every host in an ACL entry it would be nicer and cleaner to be able to group specific hosts together and reference that group in the ACL

### How should we solve this?

Create something like:

`host-group {
    "host-group:alpha": [ "host1", "host2"],
    "host-group:beta": ["host3, "host4"],
}`

 to define a list of hosts to be referenced in an ACL

### What is the impact of not solving this?

No impact, just ease of writing ACL's without having to copy and past a long list of hosts

**Comment by maisem** [comment]
The usual way to do that is to use ACL tags, do those not work for your use case?

This is tracked in #2556, I'm going to close this as a duple and we can continue discussion there.
