### ISSUE TITLE
Tailscale on Google TV can not quit after select About menu 

### ISSUE THREAD

**Issue by darren** [tailscale/tailscale#7591]
### What is the issue?

![IMG_1730](https://user-images.githubusercontent.com/12817/225951108-5c37cd51-a105-4c67-95b3-e655da5c41a0.jpg)

### Steps to reproduce

click on the up left menu and select about, then the about window can not exit

### OS

Android

### Tailscale version

1.38.1

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/7211
