### ISSUE TITLE
linux下安装tailscale无法访问子网路由下的设备，而windows和mac就没问题

### ISSUE THREAD

**Issue by githubgeekrabbit** [tailscale/tailscale#7595]
### What is the issue?

linux下安装tailscale无法访问子网路由下的设备，而windows和mac就没问题

### Steps to reproduce

我通过指定虚拟网卡去 ping -I tailscale0 192.168.9.1  ，192.168.9.1是我的子网路由![image](https://user-images.githubusercontent.com/45820964/226096842-de8c90f8-3be5-4b7f-b846-5c744b89f93f.png)

而我用windows就可以
![image](https://user-images.githubusercontent.com/45820964/226096996-1ffde884-0815-4d28-ba80-3de324db03ab.png)

centos7.6 ubuntu20.04 试了这两个都不行

### OS

Linux, macOS, Windows, Android

### OS version

win10 macos 13.6  

### Tailscale version

1.38.1

**Comment by DentonGentry** [comment]
Linux: `tailscale up --accept-routes=true`

**Comment by githubgeekrabbit** [comment]
非常感谢您的帮助，问题解决了

> Linux：`tailscale up --accept-routes=true`

**Comment by lqqhd** [comment]
Android下无法访问子网下的设备呢？
