### ISSUE TITLE
Android Application Heavy Battery Drain

### ISSUE THREAD

**Issue by kycfree1** [tailscale/tailscale#7598]
Leaving the Tailscale application operating as a primary "always on" VPN, connected to a personal exit node, seems to be heavily draining battery. After a 10 hour period of phone usage tailscale was accountable for 36% of my devices battery drain in that period.
This seems to be very heavy for a VPN application and is causing a dramatic drop to my typical charge to charge period and much higher than the wireguard application and other VPN applications that I have used.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/3363
