### ISSUE TITLE
1.38.1 macOS shows "Welcome to Tailscale" even if logged in

### ISSUE THREAD

**Issue by wizzard0** [tailscale/tailscale#7599]
### What is the issue?

"Welcome to Tailscale" window does not go away when Tailscale is working fine (shows after each reboot)

What expected to happen:
- "Welcome to Tailscale" no longer shows up once logged in

### Steps to reproduce

1. Wiped the machine, installed Tailscale as the first app (yay!)
2. Connected the machine to my tailnet
3. VPN works, taildrop works, etc etc
4. Reboot the machine
5. Wonder why the window appears again
6. Confirm the machine is on the tailnet etc etc, close the window
7. Reboot
8. The window reappears

### Are there any recent changes that introduced the issue?

Factory reset the machine

### OS

macOS

### OS version

macOS Ventura 13.2.1

### Tailscale version

1.38.1

### Other software

Clean macOS Ventura 13.2.1. Literally zero apps.

### Bug report

BUG-1fec50b8155075c8a45afa1e698186309c9d6eda845904e66c7985284182cce9-20230319005521Z-8787685f8bd40cf1

**Comment by bradfitz** [comment]
cc @mihaip @nickoneill

**Comment by wizzard0** [comment]
UPD: 2 of 3 new machines also show as offline in Tailscale admin panel. Maybe this is why Taildrop considers them offline in #7610 

But they can ping each other and access files just fine

**Comment by mihaip** [comment]
The "Welcome to Tailscale" onboarding flow is controlled by a `TailscaleOnboardingSeen` `defaults` key. It looks like the client is using the standalone/"macsys" build, what does the output of `defaults read io.tailscale.ipn.macsys` show?

**Comment by wizzard0** [comment]
@mihaip 
```
{
    SULastCheckTime = "2023-03-21 08:06:14 +0000";
    SUUpdateGroupIdentifier = 867051516;
    TailscaleStartOnLogin = 1;
}
```
I indeed didn't watch the onboarding, I just used the authkey :) way faster

**Comment by mihaip** [comment]
In the next stable release (1.40.x) the welcome screen will be skipped if the VPN tunnel is already set up.

**Comment by DentonGentry** [comment]
This is believed to be fixed.
