### ISSUE TITLE
windows: update winipcfg fork, upstream changes

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#760]
We have a very old fork of winipcfg-go that we've made a few local changes to but they were never upstreamed, as upstream moved:

https://godoc.org/golang.zx2c4.com/wireguard/windows/tunnel/winipcfg

... and we never sent them there.

We should upstream our changes and switch to using the `golang.zx2c4.com/wireguard/windows` module.

/cc @alexbrainman

**Comment by alexbrainman** [comment]
Also before we close this issue, we should

- disable or archive repo https://github.com/tailscale/winipcfg-go

- remove replace github.com/tailscale/winipcfg-go in winmin go.mod

- remove winipcfg-go submodule in winmin

Alex

**Comment by alexbrainman** [comment]
I think we should also

- remove github.com/tailscale/winipcfg-go package from winmin go.mod
- remove github.com/tailscale/winipcfg-go from winmin submodule list
- mark github.com/tailscale/winipcfg-go repo as archived or read-only - or delete altogehter

Thank you.

Alex
