### ISSUE TITLE
Tailscale SSH truncates streams at multiples of 32768

### ISSUE THREAD

**Issue by randomnetcat** [tailscale/tailscale#7601]
### What is the issue?

When transferring data over stdout on an SSH connection using Tailscale SSH, the stream can be incorrectly truncated.

### Steps to reproduce

On a server:
```
[root@leon:~]# cat /dev/random | head -c 4000000 > /run/rand

[root@leon:~]# wc -c /run/rand
4000000 /run/rand

[root@leon:~]# sha256sum rand
0394c6312d9ea5ebb10db46b190616fd67a27f153d1cd6f42faa5a9f13f00e75  rand

[root@leon:~]# head -c 3964928 rand > rand-trunc

[root@leon:~]# sha256sum rand-trunc
6d0b715d29c8067cd3d038fb0b3d553f87c804a34c8430de804e5f892e13ac94  rand-trunc
```

On a client:
```
[randomcat@groves:~]$ ssh -vvv root@leon 'cat /root/rand' > rand 2> ssh_out.txt; wc -c rand
3964928 rand

[randomcat@groves:~]$ sha256sum rand
6d0b715d29c8067cd3d038fb0b3d553f87c804a34c8430de804e5f892e13ac94  rand
```

[ssh_out.txt](https://github.com/tailscale/tailscale/files/11010469/ssh_out.txt)

The exact number of bytes that are properly transferred varies from run to run, but (at least with this file size) is always a multiple of 32768.

I am unable to reproduce this using normal SSH over the pubilc internet or by using an SSH (but not Tailscale SSH) connection with a normal keypair over Tailscale.

### OS

Linux

### OS version

NixOS 23.05.20230312.5a1dc8a (Stoat)

### Tailscale version

1.36.2

### Other software

None that should be relevant.

### Bug report

BUG-a5a749adeecdbeebd3da59f158fcdf69ec0fde2f96161a43f4b57db26d1094c4-20230319075559Z-498daae6a7fdea28

**Comment by DentonGentry** [comment]
Can reproduce here.
```
root@dgentry-sfo1:~# cat /dev/random | head -c 4000000 > /tmp/rand
root@dgentry-sfo1:~# wc -c /tmp/rand
4000000 /tmp/rand
```

```
$ ssh -vvv root@dgentry-sfo1 'cat /tmp/rand' > /tmp/rand 2> /tmp/ssh_out.txt; wc -c /tmp/rand
3964928 /tmp/rand
```

**Comment by dsnet** [comment]
I just want to comment that 32k is suspiciously identical to the default buffer size used by [io.Copy](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/io/io.go;l=416).

**Comment by dsnet** [comment]
Furthermore, the effect is racy. I'm fairly certain it's due to incorrect termination signals between various goroutines.
