### ISSUE TITLE
FR: Allow a Windows Hosts file to be downloaded from the admin panel

### ISSUE THREAD

**Issue by linolunter** [tailscale/tailscale#7602]
### What are you trying to do?

see "anything else"

### Anything else?

Dear All,
every now and then the IPs of the nodes change, then everything possible has to be adjusted. Have you ever thought about summarising the contents of the admin console, e.g. for a Windows hosts sample file? In the admin console you can find everything you need, the IP, the machine name and a comment. I think your coders would easily be able to put such a tailscale_based_hosts_snippet on the clipboard on demand.  You could then set up a TaleScale exchange area in your own hosts file for more easy maintenance.
Best regards
Lino

**Comment by DentonGentry** [comment]
Are you familiar with MagicDNS? https://tailscale.com/kb/1081/magicdns/

It creates a DNS server to let hostnames map to Tailscale IP addresses.

**Comment by linolunter** [comment]
... don't know yet, I'll get into it.

**Comment by DentonGentry** [comment]
I think that MagicDNS is the right direction to pursue rather than automating Hosts file distribution.
