### ISSUE TITLE
Docs Synology Outbound Link Bad - Fill Name Changed

### ISSUE THREAD

**Issue by war59312** [tailscale/tailscale#7607]
### What is the issue?

On https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections step 6, the link for `[read the configure-host code](https://github.com/tailscale/tailscale/blob/main/cmd/tailscale/cli/configure-host.go))` has changed.

The file was renamed to `configure-synology.go`

Correct link: `https://github.com/tailscale/tailscale/blob/main/cmd/tailscale/cli/configure-synology.go`

You should probably check all docs for 404. Hell, don't let the page save if has broken links.

**Comment by DentonGentry** [comment]
Brought up as a www issue, which will be tracked elsewhere.
