### ISSUE TITLE
add reverse DNS records for your relay servers

### ISSUE THREAD

**Issue by 33b5e5** [tailscale/tailscale#761]
**Is your feature request related to a problem? Please describe.**

My IDS triggered a bunch of INFO level alerts like "Session Traversal Utilities for NAT (STUN Binding Request)" and "Session Traversal Utilities for NAT (STUN Binding Response)". I suspected Tailscale, but it took me a while to confirm because the IP addresses of your STUN servers don't have reverse DNS. I eventually found a list of your IPs at:

https://github.com/tailscale/tailscale/blob/main/derp/derpmap/derpmap.go

**Describe the solution you'd like**

I'd like it if your STUN and other relay servers had reverse DNS records. Like "sea01.relay.tailscale.com" (or whatever, as long as we can tell they belong to Tailscale). This will make it easier for admins to troubleshoot issues in a variety of scenarios.

I know this may not be trivial on every hosting platform, but I noticed at least some of the relays are on Vultr, and they do allow you to easily specify a reverse DNS record.

**Describe alternatives you've considered**

Manually checking the list of IPs using the file above works for now. Alternatively, a list of your relay IPs on a support doc would be fine.

This is definitely a "nice to have" type of request. Thanks for listening. :)

**Comment by dorkmatt** [comment]
Strangely AWS doesn't seem to offer an API call for this _(assuming elastic IP's)_ but a form to request PTR records, see https://aws-portal.amazon.com/gp/aws/html-forms-controller/contactus/ec2-email-limit-rdns-request This would require the use of Elastic IP's, which may not be in the design criteria of Tailscale.

**Comment by bradfitz** [comment]
Well, we don't use AWS for DERP relays. (With the exception perhaps of some upcoming South America and Middle East regions, where there aren't any other choices besides AWS)

We primarily use Digital Ocean and Vultr for DERP relays.

Digital Ocean's docs say:

https://www.digitalocean.com/docs/networking/dns/how-to/manage-records/#ptr-rdns-records

> We automatically create PTR records for Droplets based on the name you give that Droplet in the control panel. The name must be a valid FQDN, so using example.com as the Droplet name will create a PTR record, but ubuntu-s-4vcpu-8gb-fra1-01 or my-droplet will not. 

As a test, I renamed our "derp4b-de" droplet to "derp4b.tailscale.com" and we'll see if `host 157.230.25.0` works in a bit here.

/cc @danderson

**Comment by 33b5e5** [comment]
It worked. 😃 `0.25.230.157.in-addr.arpa domain name pointer derp4b.tailscale.com.`

**Comment by dorkmatt** [comment]
_Wow, you guys are FAST with responses_. Doh, I only did a minor bit of packet sniffing - guess the AWS stuff was for command and control - not the DERP relaying.

A slight bonus would including a geographical identifer in the FQDN, like an IANA airport code or whatever the cloud provider calls their region/availability zone/marketing term.

**Comment by danderson** [comment]
I've been angling to use IATA airport codes for a while, maybe now's the time :p. So far we've used made up abbreviations that are less confusing than some airport codes, so I think we'll stick with those. Seems fine to have records that indicate general location though, I'll set that up.

**Comment by bradfitz** [comment]
@danderson, if you make the PTR records map to e.g. `derp4b-fra.tailscale.com` or `derp4b-de.tailscale.com`, we should probably have the other direction too (otherwise some tools get pissy, IIRC?).

But we wouldn't ever really use the `derp4b-xxx.tailscale.com` lookup direction, per https://github.com/tailscale/tailscale/blob/main/derp/derpmap/derpmap.go#L41 so ... meh.

We could just have https://derp2.tailscale.com/ say where it is too? But that doesn't help `mtr` output be pretty.

**Comment by bradfitz** [comment]
IATA airport codes are so random for some places.

How about 2 letters == ISO 3166 country code, 3 letters == IATA? Then for random airports we could use the country instead. 😛

**Comment by dorkmatt** [comment]
The authoritative names like `derp4b` could be CNAMEs, where the actual A/AAAA + PTR is a more geographical name (to make `mtr` and other friends happy).

**Comment by danderson** [comment]
I was planning on keeping the simple `derpN[ab]?` names anyway, because they're nicer when I need to connect to the machine to poke at stuff. But I agree that we should have matching forward and reverse records, otherwise things get angry.

Based on that, I'm going to create `derpNb?.tailscale.com` and `derpNb?-(CC|IATA).tailscale.com`, and make the latter the reverse DNS entries on DigitalOcean. I'll have to figure out if our other provider lets us set reverse DNS, hopefully they do.

**Comment by dorkmatt** [comment]
@danderson [Vultr](https://www.vultr.com/docs/how-to-create-reverse-dns-or-ptr-records-in-the-vultr-control-panel) does _(even with API support, sweet)_. Assuming ya all are using Terraform, Ansible, etc some sort of wrapper to manage these instances?

**Comment by danderson** [comment]
Okay, all DERP servers have matching forward and reverse names now (modulo API and DNS propagation, which may take a couple hours, or so Vultr warns me). Names are (all suffixes tailscale.com)

derp1-nyc, derp1b-nyc (New York)
derp2-sfo, derp2b-sfo (San Francisco)
derp3-sin (Singapore)
derp4-fra, derp4b-fra (Frankfurt)
derp5-syd (Sydney)
derp6-blr (Bangalore)
derp7-tok (Tokyo)
derp8-lon (London)
derp9-dfw (Dallas)
derp10-sea (Seattle)

**Comment by danderson** [comment]
All records are propagated and happy.
