### ISSUE TITLE
FR: ability to visualize the ACL 

### ISSUE THREAD

**Issue by rojomisin** [tailscale/tailscale#7620]
### What are you trying to do?

simlar to terraform's graph function, display a visual of the ACL groups and connection rules

  graph         Generate a Graphviz graph of the steps in an operation

### How should we solve this?

in the tabs that show Preview, and Edit, add a Visualize, or Graph, which displays a dynamic svg diagram representing the acl json relationships

**Comment by wizzard0** [comment]
Oooh that would be cyberpunk-level greatness. Matrix (table) view would be less cinematic but no less useful, especially if one can hover and cross-highlight between rows/columns and the diagram.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/7006
