### ISSUE TITLE
Android device `lastSeen` updated without connecting to tailnet

### ISSUE THREAD

**Issue by tyler-lloyd** [tailscale/tailscale#7627]
Both via API and on admin console my android phone's last seen time is inexplicably updated without actually being connected to the tailnet. 

I've confirmed that my toggle in the Android app is "stopped".

One way to repro is just restart the phone and when I unlock it, the last seen time is updated to the current time even though the Tailscale app hasn't been opened or seemingly been connected to.

```
OS
Android
Tailscale version
1.38.1
```

**Comment by DentonGentry** [comment]
The bug report template requests information and a bugreport because without it, we will make no progress. Please supply a bugreport.

**Comment by DentonGentry** [comment]
ETIMEDOUT
