### ISSUE TITLE
FR: Support port forwarding in k8s-operator

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#7645]
### What is the issue?

Port forwarding with `kubectl` doesn't work.

https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

### Steps to reproduce

```
❯ k -n vault port-forward svc/vault 8080:8200
error: error upgrading connection:
```

### Are there any recent changes that introduced the issue?

https://hub.docker.com/layers/tailscale/k8s-operator/unstable-v1.37.260/images/sha256-9a4fbab6bd5d849e6300f3116c3457956a3c6f923bc4faee088bda356747c697?context=explore

### OS

Linux, Other

### OS version

Kubernetes v1.26.2

### Tailscale version

k8s-operator/unstable-v1.37.260

**Comment by DentonGentry** [comment]
> Are there any recent changes that introduced the issue?
> https://hub.docker.com/layers/tailscale/k8s-operator/unstable-v1.37.260/images/sha256-9a4fbab6bd5d849e6300f3116c3457956a3c6f923bc4faee088bda356747c697?context=explore

What prior version did work?

**Comment by uhthomas** [comment]
Should I create a new issue for `kubectl exec` or edit the title for this one?

**Comment by DentonGentry** [comment]
It isn't obvious that they have the same root cause, so please open a separate issue.
