### ISSUE TITLE
FR: network debug with libtailscale

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#7648]
### What are you trying to do?

libtailscale is nice, it could be easily integrated with my application.

I'm wondering, other than reading logs, am I still able to use Tailscale CLI to check all the information as normal? I searched around and didn't find a clue how to hook CLI. Can't find a socket file on my system.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/libtailscale is much more akin to [tsnet](https://tailscale.com/blog/tsnet-virtual-private-services/), not a full tailscaled running within the application. There isn't a local socket to open, but there is a localAPI.

**Comment by awsong** [comment]
Thanks for your answer. Is there any document that I can read to know how to use localAPI?

**Comment by DentonGentry** [comment]
The methods are in https://github.com/tailscale/tailscale/blob/main/client/tailscale/localclient.go

**Comment by awsong** [comment]
Thanks, I also see some useful info in libtailscale/tailscale.h .
