### ISSUE TITLE
FR: install.sh - Add Support for VMware Photon OS

### ISSUE THREAD

**Issue by auanasgheps** [tailscale/tailscale#7651]
### What are you trying to do?

Attempting to install Tailscale on [Photon OS ](https://vmware.github.io/photon/) using install.sh results in an unsupported OS. 
It was already reported [here](https://github.com/tailscale/tailscale/issues/2915#issuecomment-1005872944), but it has not been added.

Here's the output of the script

```
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux photon-machine 5.10.168-2.ph4-esx #1-photon SMP Thu Mar 2 03:44:00 UTC 2023 x86_64 GNU/Linux

NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```

### How should we solve this?

Please add support for this OS.

**Comment by DentonGentry** [comment]
Photon uses `tdnf`, "Tiny Dandified Yum," which is similar to `dnf` except when it isn't. In particular, it lacks a `dnf config-manager --add-repo` command so we'll need to implement support to write the repo information to a file in `/etc/yum.repos.d/`

**Comment by auanasgheps** [comment]
There's kinda a way to do it, not great like a command though.
It is documented here [Adding a New Repository](https://vmware.github.io/photon/docs/administration-guide/managing-packages-with-tdnf/adding-a-new-repository/) using the following command

```
cat > /etc/yum.repos.d/apps.repo << "EOF"
[localapps]
name=Local In-House Applications(x86_64)
baseurl=file:///appserver/apps
enabled=1
skip_if_unavailable=True
EOF

```

**Comment by DentonGentry** [comment]
I understand. I'm making notes of current status in order to come back to it later.

`dnf config-manager --add-repo` fetches the contents from (for example) https://pkgs.tailscale.com/stable/oracle/7/tailscale.repo and writes them to a file.
