### ISSUE TITLE
Latest version not available in Synology Package Center

### ISSUE THREAD

**Issue by rolisz** [tailscale/tailscale#7653]
### What is the issue?

In the Synology Package Center I see as the latest available version 1.30.2, but in the pkgs repository I see that the latest is 1.38.1.

Could you please push a newer version to the Package Center? 

### OS

Synology

### OS version

DSM7

**Comment by bradfitz** [comment]
> Could you please push a newer version to the Package Center?

It's not like the iOS or Android app stores where it shows up ~immediately. We can send updates but Synology chooses when to test & publish, which is sometimes as long as every 3 months.

So if you want to stay current, you'll have to sideload for now.

We're working on some auto-update mechanisms for sideloaded Synology packages, though.
