### ISSUE TITLE
tailscale cert should not overwrite device special files

### ISSUE THREAD

**Issue by n0ot** [tailscale/tailscale#7658]
### What is the issue?

I created a cron job to try and fetch a new TLS certificate once per day. Since `tailscale cert` writes the certificate and key to /var/lib/tailscale/certs on my machine (CentOS 7), I tried using `--cert-file /dev/null --key-file /dev/null`, so I wouldn't get a second copy of those artifacts.

I then realized sshd wouldn't start, because it was trying to access`/dev/null`, and was getting a "permission denied." When I ran `ls -l /dev/null`, I realized it was replaced with a regular file.

My fix was to set both `--cert-file` and `--key-file` to `-`, and then redirect STDOUT to `/dev/null`, but this behavior is probably not what should occur.

### Steps to reproduce

- Run `ls -l /dev/null`. Verify the first character is 'c' (character special)
- Assuming HTTPS certificates are enabled for your tailnet, run `tailscale cert --cert-file - --key-file /dev/null`
- Run `ls -l /dev/null` again. This time, the first character should be `-` (regular file), with permissions `rw-------`.
- To fix this, run `rm -f /dev/null; mknod -m 666 /dev/null c 1 3`
- Run `ls -l /dev/null` again to verify that it's a character special file again.

### OS version

CentOS 7

### Tailscale version

1.38.1

### Bug report

BUG-ee3f8ac1e022c750f2d7c3db21225f6c55bfc05d1060bfdaaa7d26f38f173122-20230323155040Z-55427e97074fa6ea

**Comment by DentonGentry** [comment]
> I tried using --cert-file /dev/null --key-file /dev/null, so I wouldn't get a second copy of those artifacts.

Could I ask the intent of fetching a new certificate every day in order to discard it?

**Comment by n0ot** [comment]
I don't need a new cert every day. In fact, when I tested this, I'm pretty sure the certificate in /var/lib/tailscale/certs was not updated after rerunning tailscale cert. I wanted to run that command via a cron job to ensure my certificate would be renewed before it expires, just like you'd do with an ACME client like Certbot or crt.sh. How and whether tailscale automatically renews certificates wasn't clear to me.
