### ISSUE TITLE
FR: ipn/store/kubestore: cache state in memory

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#7671]
_I'm not sure as to all the times it needs to go off to the kube store to check certificate but is there any performance impact on just relying on kube secret directly? If there is some level of caching happening in memory I guess that's fine._

_Originally posted by @dcarrion87 in https://github.com/tailscale/tailscale/issues/7669#issuecomment-1481951239_

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/7673
