### ISSUE TITLE
Docker image build for 1.38.2 not available

### ISSUE THREAD

**Issue by hollie** [tailscale/tailscale#7680]
Hello,

I see the docker image on docker hub is still reporting 1.38.1 to be the latest version.

Could it be that the automatic build process for the 1.38.2 image has failed? Could somebody please take a look so that we can update our containers to the latest Tailscale version?

Thanks,
 Lieven

**Comment by DentonGentry** [comment]
We've been working on a different platform which had a problem in its release. I skipped ahead to start the container release.
