### ISSUE TITLE
Machines created with OAuth shows as created by a deleted user

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#7687]
### What is the issue?

![image](https://user-images.githubusercontent.com/9749173/227621361-ea540738-bee8-4164-8d8c-1916413395a1.png)

### Steps to reproduce

Create a machine using OAuth.

### OS

Linux, Other

### OS version

Kubernetes v1.26.2

### Tailscale version

1.38.1

**Comment by DentonGentry** [comment]
Once tagged, the machine is owned by the tag. It does still show the creator, for auditing purposes mainly, but isn't affected if the creating user is deleted.

<img width="236" alt="Screenshot 2023-03-25 at 6 41 19 AM" src="https://user-images.githubusercontent.com/1140756/227720801-26acf02e-28de-462e-b41d-70b06d01c118.png">

--------

If created by [an OAuth client](https://tailscale.com/kb/1215/oauth-clients/), which isn't owned by a particular user, I believe it has nothing to display.
