### ISSUE TITLE
Tailscale on synology stops running after Creating Outbound Connections

### ISSUE THREAD

**Issue by tranman329** [tailscale/tailscale#7692]
Installed tailscale on synology DSM 7.1.1-42962 Update 4 and connected just fine.  Once I try to create outbound connection using the user define script to run on boot up, the app fails to start.  It keeps on manually stopping.  I have tried uninstalling and reinstalling but it stops working after creating they outbound connection using the information provided here. 

https://tailscale.com/kb/1131/synology/

**Comment by DentonGentry** [comment]
The template asks for a bug report because we have no visibility to diagnose anything. Even the Tailscale IP address or name of the account would let us look up telemetry for the device.

**Comment by tranman329** [comment]
> The template asks for a bug report because otherwise we have no visibility to diagnose anything. Even the Tailscale IP address or name of the account would let us look up telemetry for the device.

How do I get a bug report from synology and is it safe to post my tailscale ip here?  After running script tailscale does not start up

**Comment by DentonGentry** [comment]
Please handle this as a support request instead: https://tailscale.com/contact/support/

The support form will include the tailnet you are logged into when the form is submitted.
