### ISSUE TITLE
Windows Client App: Right click menu disappears when using RDP

### ISSUE THREAD

**Issue by wietscheb** [tailscale/tailscale#7698]
The Tailscale client right click menu on Windows 10 taskbar does not display anymore once you log into that computer with Windows Remote Desktop Connection. If you then kill the client and load it again, while you are in the RDP session, the menu works again. If you then exit the session and create a new RDP session, the menu is again not available. All other taskbar apps have no issues with their menus. It is isolated to the Tailscale taskbar app.

**Comment by deltamualpha** [comment]
I thought I was going nuts: I have the same problem. Right-click everywhere else works just fine, but the tailscale task-bar nubbin doesn't respond to right-clicks for me over RDP anymore.

I'm on a mac, using the official Microsoft RDP client to connect to Windows 11, fully updated on both ends.

**Comment by wietscheb** [comment]
> I thought I was going nuts: I have the same problem. Right-click everywhere else works just fine, but the tailscale task-bar nubbin doesn't respond to right-clicks for me over RDP anymore.
> 
> I'm on a mac, using the official Microsoft RDP client to connect to Windows 11, fully updated on both ends.

Thank you for confirming the issue. Another side effect of this is when you have selected an exit node on this particular remote machine, there is no way to get the right click menu back since the RDP connection breaks for a moment after you have reloaded the applet, rendering the right click menu unavailable again. You have to change Tailscale settings with terminal commands or kill the exit node as a workaround.

**Comment by ahxxm** [comment]
my right-click menu is gone too, I'm using it on a laptop(connect to 1 external monitor over HDMI, the built-in display is off), not over RDP though

**Comment by DentonGentry** [comment]
@ahxxm you are encountering something else. Please file a new issue and include a bugreport — usually that would be generated from the Debug > bug report menu by right clicking on the taskbar icon, but can also be generated from cmd.exe by running `tailscale.exe bugreport`

**Comment by DentonGentry** [comment]
Release 1.38.2 handles right click on the taskbar icon with RDP, 1.38.3 and later do not. This is possibly related to an update of https://github.com/tailscale/walk from https://github.com/tailscale/walk/commit/31689615ddb4c0df178e96974984c668079c07c6 to https://github.com/tailscale/walk/commit/b86d3486f9f2aa3ba33fec692e3e382a140fc7bd in 1.38.3.

**Comment by DentonGentry** [comment]
For those who need to do so, 1.38.2 can be found at https://pkgs.tailscale.com/stable/tailscale-setup-1.38.2.exe

You'll need to use Add/Remove Programs to remove 1.38.3 before the 1.38.2 installer will proceed.

**Comment by dblohm7** [comment]
Would any of you mind trying out the latest [unstable build](https://pkgs.tailscale.com/unstable/#windows) (1.39.110 or newer)?

I haven't been able to reproduce this issue myself, but I have landed a speculative fix in unstable.

@wietscheb @deltamualpha

**Comment by deltamualpha** [comment]
Just installed it; no change, unfortunately.

> tailscale --version
1.39.110
  track: unstable (dev); frequent updates and bugs are likely
  tailscale commit: b0ed863d55d6b51569ce5c6bd0b7021338ce6a82
  other commit: 841f59885446d739a8bffb5a6502ca4fbba6a780
  go version: go1.20.1-ts568add9

**Comment by deltamualpha** [comment]
Actually, that's perhaps a useful datapoint: I connected _over tailscale_ to do the upgrade, so I never had the "installed during an existing session" state that Denton did. (The connection drops and reconnects during install, for obvious reasons, so upon reconnection I was unable to get right-click to work.)

**Comment by dblohm7** [comment]
Yeah, I was now able to finally get this by connecting over RDP from my Mac. I couldn't get it to happen when connecting from a Windows RDP client!

I did get some message traces, so I do have more to work with now...

**Comment by wietscheb** [comment]
> Yeah, I was now able to finally get this by connecting over RDP from my Mac. I couldn't get it to happen when connecting from a Windows RDP client!
> 
> I did get some message traces, so I do have more to work with now...

Hi. Thank you very much for looking into this. I use Windows 11 RDP to connect to Windows 10 PC. The Windows 10 PC has Tailscale set to start unattended. Not sure if that helps. I still have the same issue.

**Comment by dblohm7** [comment]
Based on my repro, it looks to me like the real problem is when the primary display density changes. When that happens, Windows re-creates the taskbar at the new resolution. This could happen, for example, if a desktop is running at 100% dpi, but then a user connects over RDP from a device with a higher display density. Another example would be (un)plugging a laptop to/from an external monitor with a different pixel density from the builtin screen.

Our handling of this looks reasonable in code, but the Windows taskbar isn't having any of it. This gives me enough to figure out a fix, at least...

**Comment by dblohm7** [comment]
Alright @wietscheb @deltamualpha, please try the unstable that's now up on the package server. I've verified this one locally.

**Comment by deltamualpha** [comment]
Interestingly, installing it over RDP didn't seem to change anything, but after a reboot and reconnect, the right-click menu worked.

Then, to make _really_ sure, I disconnected and reconnected... and right-click no longer worked. So you're getting closer. Are there any logs I can try and pull to assist from my side?

**Comment by dblohm7** [comment]
Great, thanks!
