### ISSUE TITLE
Windows: "tailscale service is not running" 

### ISSUE THREAD

**Issue by jucor** [tailscale/tailscale#770]
**Describe the bug**
At startup, Tailscale on Windows throws this error:
![image](https://user-images.githubusercontent.com/660037/93527768-4421c900-f931-11ea-821b-3102589c3a9e.png)
Then I am not able to ping any machine on Tailscale (when I had a tailscale instance already logged in) nor, now that I updated and been logged out, am I able to log-in: clicking on "Log in" doesn't do anything.

Note1: if I exit Tailscale and restart it, without rebooting the laptop, the error message of step 2 is not displayed, but the behaviour of step 5 is still there.

Note2: weird thing is, Tailscale 1.0.4 used to work happily for a while. Just today I can't reach any node. Yet the admin console kept seeing my laptop. Now that I tried to debug by updating to 1.1.372 and am therefore logged out, of course, the admin console doesn't see my laptop anymore.

**To Reproduce**
1. Boot my laptop, with Tailscale starting at boot
2. See error
3. Click on tailscale system tray icon
4. Click on "log in"
5. Nothing happens

**Expected behavior**
No error at launch, and when clicking on "Log in", the ability to log into my tailscale network.

**Screenshots**
![image](https://user-images.githubusercontent.com/660037/93527989-95ca5380-f931-11ea-8680-1ed8f7e50ddd.png)

Tailscale service is shown as running, in spite of what the error says:
![image](https://user-images.githubusercontent.com/660037/93528662-944d5b00-f932-11ea-8763-4c630af73028.png)

**Version information:**
 - Device: Laptop Thinkpad Carbon X1 6th gen
 - OS: Windows 
- OS version: Windows 10 Pro version 2004 build 19041.508
 - Tailscale version: first experienced the problem with 1.0.4 (I was already logged in, problem was no traffic going through), then updated to 1.1.372 (g6f5783c32)  which logged me out and now can't even log in.

**Comment by bradfitz** [comment]
That's a bummer. 1.1.372 has fixed a bunch of Windows issues but apparently not all of them.

Can you share the latest log file from `C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs`? You can email it to support@tailscale.com if you prefer, referencing this bug.

**Comment by jucor** [comment]
Thanks! I've just send them to support@. Note that I've included all the latest logs, because weirdly, today the log-in is working (I rebooted and was logged in, go figure). However, traffic doesn't go through at all :(

**Comment by bradfitz** [comment]
@jucor, thanks for the logs. I've confirmed you're also hitting #474 so I'll close this one as a dup. You can subscribe to that issue, though.

I'm looking into it now.

**Comment by jucor** [comment]
Awesome, thank you!
