### ISSUE TITLE
derp: allow development/testing without internet connection

### ISSUE THREAD

**Issue by valscale** [tailscale/tailscale#7700]
### What is the issue?

Running a live DERP server requires valid TLS certs in at least some configurations does not allow self-signed certs. It would be nice to be able to develop and run end-to-end tests on a local machine without internet connectivity. One option to make this happen is mkcert:

https://words.filippo.io/mkcert-valid-https-certificates-for-localhost/

**Comment by mihaip** [comment]
I did some light-weight DERP hacking last year, and the easiest path was to change all of the `https://.*derp` references (e.g. at https://github.com/tailscale/tailscale/blob/946451b43ecdf4d73e973f9aad4f67870273c7fb/derp/derphttp/derphttp_client.go#L203) to be `http`. We could perhaps have an envknob to control what protocol is used.

**Comment by catzkorn** [comment]
I also worked on derp a bit last year and did the same as Mihai! It worked for what I needed.

**Comment by valscale** [comment]
Some other suggestions:

Use the Tailscale TLS cert feature to get a valid cert, add a matching entry for it with 127.0.0.1 to /etc/hosts, specify the cert location and hostname when starting derper, and use a local control server to serve the derp map.

Use a self-signed cert (many reports of this not working).

My preference would be an analogue to the existing "-login-server=HOSTNAME" argument to tailscaled, but I started by hacking up the envknob solution with TS_DEBUG_DERP_USE_HTTP.
