### ISSUE TITLE
uploading sockstat logs results in infinite upload loop

### ISSUE THREAD

**Issue by willnorris** [tailscale/tailscale#7719]
Whenever triggering upload of sockstat logs, uploads continue seemingly forever.  This can be seen at http://go/logs/BUG-276722f7c2d07cfe13681d9d8181db6b0a6149efa4acc70337e6b8ee8de3dbd7-20230329014701Z-adfa92486dd47764

```
01:44:44 | {"c":1,"d":99,"s":{"3":[672,97]},"t":1680054284508}
01:44:44 | {"c":1,"d":100,"s":{"3":[289,194]},"t":1680054284608}
01:44:44 | {"c":1,"d":100,"s":{"3":[291,97]},"t":1680054284808}
01:44:45 | {"c":1,"d":100,"s":{"3":[290,97]},"t":1680054284908}
01:44:45 | {"c":1,"d":99,"s":{"3":[290,97]},"t":1680054285108}
01:44:45 | {"c":1,"d":100,"s":{"3":[289,97]},"t":1680054285208}
01:44:45 | {"c":1,"d":100,"s":{"3":[289,97]},"t":1680054285308}
01:44:45 | {"c":1,"d":99,"s":{"3":[290,97]},"t":1680054285608}
01:44:45 | {"c":1,"d":100,"s":{"3":[288,97]},"t":1680054285708}
01:44:45 | {"c":1,"d":99,"s":{"3":[290,97]},"t":1680054285808}
```

The constant stream of these small events with label 3 ([LogtailLogger](https://github.com/tailscale/tailscale/blob/840d69e1ebfc39c6a58ae38a7bf4aae321e7720a/net/sockstats/sockstats.go#L44)) indicates the problem. Logtail reads from the local logs one line at a time until it can't read anymore, uploading them in batches to logcatcher.  This upload itself results in network traffic which is itself captured by sockstat logs.  The events are written to disk more frequently (10hz) than they can be uploaded to logcatcher, so logtail never finishes reading from the log file.

This problem wasn't observed during development because I was uploading to a dev logcatcher on localhost, and it WAS able to upload fast enough that it got ahead of the sockstat poll.

One simple solution (which I've coded up, and will submit shortly) is to delay writing events to disk, giving the logtail uploader time to upload and finish before the sockstats for that upload are captured and written back out to disk.

**Comment by DentonGentry** [comment]
If we need to, we can hold 1.38.3 until later in the day tomorrow to let this get in.

**Comment by willnorris** [comment]
no need.  sockstats is [only enabled on unstable builds](https://github.com/tailscale/tailscale/blob/524f53de89f7669098175f1bed87fb2b1638e52a/ipn/ipnlocal/local.go#L312-L321).

**Comment by DentonGentry** [comment]
I think https://github.com/tailscale/tailscale/pull/7936 should have resolved this.

Barring further comment, we'll expect to close this during the next regular bug scrub.
