### ISSUE TITLE
problem of run and authenticate in tailscale

### ISSUE THREAD

**Issue by jjventura** [tailscale/tailscale#7729]
### What is the issue?

Hello, i installed tailscale and i when give tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &  i get me the nex issue, someone  can i help me please:

Program starting: v1.38.2-t22b8d09d6-g1c4d8e1f5, Go 1.20.1-tsdb4dc90: []string{"tailscaled", "--tun=userspace-networking", "--socks5-server=localhost:1055"}
LogID: 771f54ea04b3b9febc662c9312a4be36476ad486169d2567d019d92a095fe34c
logpolicy: using system state directory "/var/lib/tailscale"
flushing log.
logger closing down
logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: connect: connection refused (in 1ms), trying bootstrap...
trying bootstrapDNS("derp12.tailscale.com", "216.128.144.130") for "log.tailscale.io" ...
bootstrapDNS("derp12.tailscale.com", "216.128.144.130") for "log.tailscale.io" error: Get "https://derp12.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp 216.128.144.130:443: connect: connection refused
trying bootstrapDNS("derp4c.tailscale.com", "2a03:b0c0:3:d0::1501:6001") for "log.tailscale.io" ...
bootstrapDNS("derp4c.tailscale.com", "2a03:b0c0:3:d0::1501:6001") for "log.tailscale.io" error: Get "https://derp4c.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp [2a03:b0c0:3:d0::1501:6001]:443: connect: network is unreachable
trying bootstrapDNS("derp8d.tailscale.com", "178.62.44.132") for "log.tailscale.io" ...
bootstrapDNS("derp8d.tailscale.com", "178.62.44.132") for "log.tailscale.io" error: Get "https://derp8d.tailscale.com/bootstrap-dns?q=log.tailscale.io": dial tcp 178.62.44.132:443: connect: connection refused

### OS version

Debian 11

### Tailscale version

1.38.2

**Comment by raggi** [comment]
It looks as though your machine does not have any internet connectivity.

**Comment by DentonGentry** [comment]
In particular: `logtail: dial "log.tailscale.io:443" failed: dial tcp 34.229.201.48:443: connect: connection refused (in 1ms), trying bootstrap...`

something is actively blocking access to websites and sending a TCP RST.

**Comment by DentonGentry** [comment]
No connectivity
