### ISSUE TITLE
MagicDNS doesn't contain an entry for self

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#774]
Steps:
- Install 1.1.424 on Linux
- Enable MagicDNS for my domain
- ping <node1>   # where <node1> is the name of some other node
- Notice that it works (MagicDNS name lookup works)
- ping <mynode>   # where <mynode> is the name of the local node in MagicDNS

Expected:
- <mynode> looks up in MagicDNS like any other node

Actual:
- ping: <mynode>: Name or service not known

Note that the DNS lookup might not be attempted if your local hostname is in /etc/hosts, so you might need to remove it first.

This could get in the way of people trying to access the same URL on both a host machine and other machines.

**Comment by danderson** [comment]
Fixed long ago, we forgot to close the bug. At least since 1.6, possibly in 1.4 also.
