### ISSUE TITLE
cmd/tailscale/cli: [serve] support paths for proxy targets

### ISSUE THREAD

**Issue by shayne** [tailscale/tailscale#7743]
A [comment](https://github.com/tailscale/tailscale/issues/6571#issuecomment-1489902493) in #6571 mentions the following use case:

```console
$ tailscale serve https / https://127.0.0.1:3123/foo/bar

$ curl https://my-node.my-tcd.ts.net/baz

# The backend receives.
GET /foo/bar/baz HTTP/1.1
...
```

We don't support paths for proxy targets, but I don't see why we shouldn't.

**Comment by Milo123459** [comment]
Thank you for implementing this functionality!
