### ISSUE TITLE
FR: add plain HTTP support to custom derp servers

### ISSUE THREAD

**Issue by qingyunha** [tailscale/tailscale#7745]
### What are you trying to do?

Derp servers can run on HTTP, but there seems no way to make tailscaled use HTTP.

**Comment by DentonGentry** [comment]
Can you explain why you would want to do this?

**Comment by qingyunha** [comment]
If I use HTTPS, I will need a domain name. In particular, in China, the domain name must be filed for record-keeping before it can be used.

**Comment by qingyunha** [comment]
https://github.com/tailscale/tailscale/issues/7700

**Comment by DentonGentry** [comment]
#7700 is intended for testing, not production use.

Wireguard tunnels distribute AllowedIPs for each node, and will only accept Wireguard frames from an allowed source. To encapsulate Wireguard through the DERP relay, we rely on TLS to prove the identity of the DERP server and perform the function of the AllowedIPs. DERP hasn't supported running over plain HTTP in production use for that reason.

**Comment by qingyunha** [comment]
Perhaps this is a trivial inquiry, why is it necessary to identify the DERP server that just blindly forwards already-encrypted traffic from one node to another.

**Comment by qingyunha** [comment]
Can we make the client determine the need for HTTPS based on the port number, just like the server does?
https://github.com/tailscale/tailscale/blob/38bbb30aaf8fbf2452cda2054bfff45b2d1cb418/derp/derphttp/derphttp_client.go#L184-L189
https://github.com/tailscale/tailscale/blob/38bbb30aaf8fbf2452cda2054bfff45b2d1cb418/cmd/derper/derper.go#L150

**Comment by gy6221** [comment]
Hi,
For the other reason to run DERP server in plain http is setting up a DERP server behind a reverse proxy. The reverse proxy (such as nginx, traefik, caddy etc) can manage the certs and perform SSL termination. So the DERP server only need to handle plian http traffics. In this scenario, TLS is still enforced on the client side, and the server identity is able to be verified via the SSL cert

**Comment by SoulEater45** [comment]
Having derp behind a reverse proxy would be a good addition, since not everyone has the resources to spin up a machine with ports `80` and `443` just for a DERP server.

**Comment by bradfitz** [comment]
One thing we plan to do in the future is use Noise instead of TLS for DERP connections as we do with the control plane already. 

We don't want to use just HTTP because some of the messages (NAT traversal stuff) over DERP aren't wireguard messages.

(But note this won't magically solve China problems; it'd just shift the problems. You wouldn't need a cert but your Noise traffic over port 80 would certainly look odd to onlookers and likely get RST)

Anyway, I'm going to close this. I believe other bugs already track the Noise work.

**Comment by betamos** [comment]
> You wouldn't need a cert but your Noise traffic over port 80 would certainly look odd to onlookers and likely get RST

I'm doing an HTTP-based protocol similar to DERP with https://github.com/betamos/rdv which can run either with TLS or not. With TLS, you end up double-encrypting the p2p data. The benefit of skipping TLS is fewer RTT for establishment and less CPU usage, so it has some theoretical benefits in the general case.

Anyway, I worry that middleboxes will think traffic is suspicious or unusual, or will try to cache or be clever in some way. Thus, TLS would be safer against "onlookers". Does anyone know from experience how much of a problem this is? Is "messing with http" a commonly-seen middlebox behavior? Are there other workarounds than wrapping in TLS?

Hopefully this can be useful to others as well, and for post-hoc documentation. Thanks, and apologies for the noise.
