### ISSUE TITLE
Alpine: tailscale version returns "ERR-buildinfo"

### ISSUE THREAD

**Issue by wwng2333** [tailscale/tailscale#7746]
### What is the issue?

tailscale version got ERR-BuildInfo on alpine linux since 1.38

### Steps to reproduce
Use apk to install tailscale, and run `tailscale version`
```bash
crazy:~# apk add tailscale
OK: 180 MiB in 182 packages
crazy:~# tailscale version
1.38.3-ERR-BuildInfo
  go version: go1.20.2
```

### Are there any recent changes that introduced the issue?

1.36 works fine, since 1.38 it reports 'ERR-BuildInfo'

### OS

Linux

### OS version

Alpine linux 3.17

### Tailscale version

1.38.3-ERR-BuildInfo

### Other software

nothing

### Bug report

BUG-f2896bda18161cab91b244680f560bf7928f4c1c4ba02f7ee2ca9c41a2ab4054-20230331090504Z-97a765a2a4106134

**Comment by DentonGentry** [comment]
The Alpine builder doesn't use [build_dist.sh](https://github.com/tailscale/tailscale/blob/main/build_dist.sh)

https://git.alpinelinux.org/aports/tree/community/tailscale/APKBUILD

It will need very similar updates to what was done in the Android build: https://github.com/tailscale/tailscale-android/commit/52a0509a5d5ce73cbf71ad190514ae393676f75f

**Comment by DentonGentry** [comment]
Filed https://gitlab.alpinelinux.org/alpine/aports/-/issues/14775

**Comment by DentonGentry** [comment]
Should be fixed by https://gitlab.alpinelinux.org/alpine/aports/-/commit/9e2186d078d8136ac09502581e91dfa243e6c1f9
