### ISSUE TITLE
Update `tailscale up --help` to recommend --authkey instead of --auth-key

### ISSUE THREAD

**Issue by samlinville** [tailscale/tailscale#7750]
When you look at `tailscale up --help`, we say that the proper auth key flag is `--auth-key`. However, all of our docs specify `--authkey`, and the CLI will take either.

Based on https://github.com/tailscale/tailscale/issues/6321, it seems the direction we're moving is to use `$TS_AUTHKEY` and `--authkey` over `$TS_AUTH_KEY` and `--auth-key`.

Thus, we should update the output of `tailscale up --help` to use `--authkey`

**Comment by DentonGentry** [comment]
This is harder than it looks. The compatibility handling to accept either `--authkey` or `--auth-key` is https://github.com/tailscale/tailscale/blob/38bbb30aaf8fbf2452cda2054bfff45b2d1cb418/cmd/tailscale/cli/cli.go#L61

It rewrites an `--authkey` argument to be `--auth-key`, meaning that the actual argument is `--authkey`. It isn't that the helptext is wrong: the helptext correctly describes the actual argument as being `--auth-key`.

**Comment by bradfitz** [comment]
The intention was to move to `--auth-key` as canonical and make `--authkey` be the legacy way.

**Comment by uhthomas** [comment]
> The intention was to move to `--auth-key` as canonical and make `--authkey` be the legacy way.

Ah, I see. So should this issue be closed then as the current behaviour of `--help` is correct?

**Comment by bradfitz** [comment]
I don't know what's up with this issue. We originally had only `--authkey` and changed it to `--auth-key` on purpose to migrate to `--auth-key` as canonical and keeping the old alias but apparently there's now discussion of reverting that decision? I'm not current on whatever's being discussed.

**Comment by uhthomas** [comment]
I agree, there seems to be conflicting information on what the intention here is. Though I do recognise the environment variable `TS_AUTH_KEY` has been replaced with the canonical form `TS_AUTHKEY` which does conflict with the `--auth-key` flag semantically.

**Comment by samlinville** [comment]
@uhthomas Let me get some alignment internally on what we want to move forward with and I'll post an update here.

**Comment by samlinville** [comment]
@uhthomas I apologize for the churn on this, but we're going to go with --auth-key and TS_AUTH_KEY.

**Comment by uhthomas** [comment]
> @uhthomas I apologize for the churn on this, but we're going to go with --auth-key and TS_AUTH_KEY.

Should there be a new issue to revert https://github.com/tailscale/tailscale/issues/6321?

**Comment by samlinville** [comment]
@uhthomas In some form, yes. I will do this on Monday.

**Comment by aviau** [comment]
@samlinville Would it make sense to update docs to use `TS_AUTH_KEY` everywhere?

I was confused by this more than once, and different gitlab issues say different things...
