### ISSUE TITLE
Windows: Right click menu stops working after a while

### ISSUE THREAD

**Issue by ahxxm** [tailscale/tailscale#7753]
### What is the issue?

right click the tray icon, the menu doesn't pop up as expected

### Steps to reproduce

I can't tell exactly how to reproduce it, but when I killed the GUI client without restarting the service and start it again, the menu will pop up, seems the connections aren't disrupted at all

But the menu will stop working after a while, presumably overnight, or hibernate and wakeup

### Are there any recent changes that introduced the issue?

Upgraded from 1.36 to 1.38.2, the symptom appeared, upgrading to 1.38.3 doesn't solve it

### OS

Windows

### OS version

Windows 11

(connected to 1 external monitor over HDMI, the built-in display is off, it that might help)

### Tailscale version

1.38.3

### Bug report

BUG-2473ea2843dcccbb3873269844c794f370fe842a25b15a0588ee666a7604005e-20230401093840Z-603bf5ebdc961505

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/7698

**Comment by ahxxm** [comment]
@DentonGentry You [just said](https://github.com/tailscale/tailscale/issues/7698#issuecomment-1492882921) I got another issue, and you mark this as a duplicate... ?

**Comment by DentonGentry** [comment]
Around the time of the bugreport there isn't a clear reason in telemetry why the menu stopped responding.

**Comment by ahxxm** [comment]
Thanks! That's a fast investigation, I can wait, as people are going to upgrade to the new version over time

**Comment by ahxxm** [comment]
As discussions happened in another issue, I tried unstable build 1.39.111, and now I can reproduce:
- upgraded it with the built-in display, right-click menu works
- then connected to an external one(the built-in display was off, DPI indeed changed), the right-click menu was immediately lost

**Comment by ahxxm** [comment]
with 1.39.115(1.39.111 hasn't merge the fix) the menu works after changing DPI
