### ISSUE TITLE
Improving exit node throughput

### ISSUE THREAD

**Issue by Onlinevpn** [tailscale/tailscale#7755]
### What are you trying to do?

one o

**Comment by Onlinevpn** [comment]
machine details:
Nanode 1 GB

**Comment by DentonGentry** [comment]
The first thing is to ensure you are able to connect directly. After connecting to the exit node, `tailscale status` will show whether the connection is direct or relayed.

Going through a relay will limit throughput.

```
$ tailscale status
100.102.2.1    ubuntu               dgentry@       linux   -
100.100.254.1  dentons-air          dgentry@       macOS   active; direct 10.1.10.170:60659, tx 404 rx 348
100.127.188.1  dgentry-tor1         dgentry@       linux   active; relay "tor", tx 276 rx 220
```

**Comment by DentonGentry** [comment]
ETIMEDOUT
