### ISSUE TITLE
Tailscale funnel unable to connect

### ISSUE THREAD

**Issue by DiamondDemon669** [tailscale/tailscale#7758]
### What is the issue?

When connecting to the tailscale funnel port 10000, using TLS terminated TCP, the socket will return a broken pipe error

On the server side, I have my raspberry pi configured with the server config listed in steps produced and an Ncat server listening on the correct port (2222)

I tested first on my laptop whilst inside the tailnet, and on the same physical wifi network and the name resolved to the tailscale IP of the device and the connection worked first time, but I couldnt exchange messages using Ncat (although the connection was listed in the server side)

Then I disabled tailscale on the laptop and remained on the same physical network. the name resolved to a tailscale ingress server and Ncat did connect, however no messages could be exchanged and the connection did not show up on the server side.

Finally I tried testing on a public computer (which was incredibly difficult to find) but I settled on using a virtual browser service to connect because even though the server is not a HTTP server, it would still send a GET request. It said that the server didnt send any data, and the server log confirmed this, since no connection message appeared and no data transferred

### Steps to reproduce

Tailscale funnel configuration:
```json
{
  "TCP": {
    "10000": {
      "TCPForward": "127.0.0.1:2222",
      "TerminateTLS": "server.tail2d5b3.ts.net"
    }
  },
  "AllowFunnel": {
    "server.tail2d5b3.ts.net:10000": true
  }
}
```

### OS

Linux

### OS version

Debian buster, raspberry pi armhf

### Tailscale version

1.38.3

### Bug report

BUG-bbe54014ec8aed2b3f70cbb09c37bdb81842bcc4545fbff5cf7cc9faef288c55-20230401221312Z-b663876878a45813

**Comment by shayne** [comment]
Hi there, I hope I can help you out!

What request are you sending on the Funnel serve port (`10000` in your example)? The traffic going over the Funnel needs to be TLS to work.

**Comment by DiamondDemon669** [comment]
Raw TCP traffic in tests 1 and 2 and HTTP traffic in test 3

**Comment by shayne** [comment]
Funnel only supports TLS traffic from the Internet. This is because we depend on SNI for routing requests based on hostname. To read more on how it works, we have [a blog post ](https://tailscale.com/blog/introducing-tailscale-funnel/)introducing the feature.

We recently published some use cases in the docs. I'd recommend looking at those and trying one of our example configurations. Let me know how that goes.

https://tailscale.com/kb/1247/funnel-serve-use-cases/

**Comment by DiamondDemon669** [comment]
What does the TLS-terminated option do then

**Comment by shayne** [comment]
Suppose you aim to utilize a nearby server such as Nginx or Caddy but prefer your local `tailscaled` process to oversee the encryption of TLS and transform it into unencrypted HTTP to relay to Nginx or Caddy for handling.

You could execute the following command:

```console
$ tailscale serve tls-terminated-tcp:443 tcp://localhost:80
```

Requests made to `https://your-node.your-net.ts.net` would have a valid TLS certificate, be encrypted with encryption terminated on your box, and finally relayed into your backend service. Again, it doesn't have to be HTTP, it could be any TCP protocol, but the client/server should support TLS-wrapped connections.

**Comment by DentonGentry** [comment]
We'll assume that https://github.com/tailscale/tailscale/issues/7758#issuecomment-1513727040 is sufficient to resolve this, please reopen if not.
