### ISSUE TITLE
tailscale serve cannot be disabled even after disabling funnel

### ISSUE THREAD

**Issue by felixg3** [tailscale/tailscale#7763]
### What is the issue?

I enabled tailscale on my server like this:
https://server.random-word.ts.net (tailnet only)
|-- / proxy http://127.0.0.1:9090
After a restart, even with funnel serving at 443 disabled, tailscaled binds to the 443 port and therefore blocks nginx on the server.
Since I enabled ssh only via tailscale I couldn't just kill the tailscaled process without losing ssh.
With a bit of tinkering I got it fixed. I am not a professional and a bit incompetent, but I wasnt sure hence I rather wanted to post it here.

### Steps to reproduce

Serve a random port at /,
enable funnel at 443,
nginx refuses to start after reboot or service restart.
disable funnel at 443,
couldnt find documentation to disable the serve command,
nginx still refuses to launch. it was necessary to kill tailscaled even after tailscale down.

### Are there any recent changes that introduced the issue?

1.38.3 introduced the issue with the funnel beta.

### OS

Linux

### OS version

Linux 6.1.0-0.deb11.5-cloud-arm64 #1 SMP Debian 6.1.12-1~bpo11+1 (2023-03-05) aarch64 GNU/Linux

### Tailscale version

1.38.3

### Other software

nginx, iptables

### Bug report

BUG-476a2ea4fe7478d29508becf78b7396f9615c92dd08e9f1947f32f6f9ed05b42-20230402214136Z-ed44de3d0ffcda15

**Comment by shayne** [comment]
`$ sudo tailscale serve https / off` to turn off the local server which is by default bound to 443. 

A shortcut to clear everything is:
`& echo {} | sudo tailscale serve set-raw`

I'll file an issue to improve docs.

**Comment by felixg3** [comment]
@shayne I can't thank you enough for the prompt reply. Indeed, it seems to be “only” a documentation issue.

**Comment by jaknz** [comment]
> `$ sudo tailscale serve https / off` to turn off the local server which is by default bound to 443.
> 
> A shortcut to clear everything is: `& echo {} | sudo tailscale serve set-raw`
> 
> I'll file an issue to improve docs.

I'm having this same issue, and your shortcut has not resolved the issue for me. Is this potentially a regression? I'm no longer able to bind my own service to 443 since tailscale is still bound to it.

```
$ echo {} | sudo tailscale serve set-raw
$ sudo tailscale serve status --json
{}
$ sudo netstat -tulpen | grep ":443 "
tcp6       0      0 fd7a:115c:a1e0:ab12:443 :::*                    LISTEN      0          4248830356 1621473/tailscaled
```

**Comment by SoulReaver-SS** [comment]
> `$ sudo tailscale serve https / off` to turn off the local server which is by default bound to 443.
> 
> A shortcut to clear everything is: `& echo {} | sudo tailscale serve set-raw`
> 
> I'll file an issue to improve docs.

I'm having the same issue currently. "sudo tailscale serve https / off" results in "CLI for serve and funnel has changed..." error.
Can I get the current command to kill it for good, please?

**Comment by marcwestermann** [comment]
I'm still running into this issue with Tailscale as a docker container. Going into the docker container to execute the mentioned commands still publicly exposes the docker container and host network. Any help would be appreciated as this is a security risk. Is the only solution wiping the config of the docker container and reconfigure? Thank you!
