### ISSUE TITLE
FR: Share subnet relayed traffic...

### ISSUE THREAD

**Issue by michconn** [tailscale/tailscale#7775]
### What are you trying to do?

I'd like to be able to share an exit node that behaves as a relay. Your documentation outlines that you may add this functionality via an opt-in process here: https://tailscale.com/kb/1084/sharing/#sharing--subnets-subnet-routers. Does the feature exist yet? 

### How should we solve this?

I'd like to opt in. If the feature hasn't been built yet, I'd like to +1 it's creation.

### What is the impact of not solving this?

Auth through a federated IDP scheme.

**Comment by DentonGentry** [comment]
This feature is in the plan but has not been developed. Subscribing to https://github.com/tailscale/tailscale/issues/1390 will provide updates on its status.

Dup of https://github.com/tailscale/tailscale/issues/1390
