### ISSUE TITLE
WatchIPNBus in the localapi permission denied

### ISSUE THREAD

**Issue by DomBlack** [tailscale/tailscale#7797]
### What is the issue?

When using the `tailscale.LocalClient` from another process (which isn't running as root), you can call `client.Status(ctx)` to get the current status and peer information.

However if you want to then watch for changes using `client.WatchIPNBus(ctx,  ipn.NotifyNoPrivateKeys)` you get an AccessDenied;

I think this is due to these lines checking for `h.PermitWrite` instead of `h.PermitRead`:
```go
func (h *Handler) serveWatchIPNBus(w http.ResponseWriter, r *http.Request) {
	if !h.PermitWrite {
		http.Error(w, "denied", http.StatusForbidden)
		return
	}
```
(see https://github.com/tailscale/tailscale/blob/main/ipn/localapi/localapi.go#L930-L933)

I don't see why the watch command needs to have write permissions as it reads the same information as present in the status request.

The workaround for now is to poll the Status request - which isn't ideal.

### OS

Linux

### OS version

Ubuntu 20.04.5 LTS

### Tailscale version

1.38.3

### Bug report

BUG-4e6684dc7a17f465ea18479788f758414cf8fa07605ac0f535abe3609544b031-20230405083114Z-0263ffd417c361a5

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/7798 is waiting for requested changes in the commit message.
