### ISSUE TITLE
Unable to Enable Exit Node on the admin console

### ISSUE THREAD

**Issue by ABUCKY0** [tailscale/tailscale#7807]
### What is the issue?

I logged into the tailscale web interface to enable a Ephemiral Exit Node on my tailnet, and it says:
![image](https://user-images.githubusercontent.com/81783950/230263525-8a03074d-addb-4edf-a72e-ed8d8f1aca43.png)

### Steps to reproduce

1. Login to Tailscale
2. Attempt to enable an exit node for a device that is advertising it, or disable one that is enabled.
3. Failure

### OS

Windows

### OS version

Windows 11

### Tailscale version

Web

**Comment by DentonGentry** [comment]
The template asks for a bug report because without it, we have no way to investigate.

**Comment by DentonGentry** [comment]
Replaced by https://github.com/tailscale/tailscale/issues/7808
