### ISSUE TITLE
Unable to Enable or Disable Exit Nodes on the admin console

### ISSUE THREAD

**Issue by ABUCKY0** [tailscale/tailscale#7808]
### What is the issue?

I logged into the tailscale web interface to enable a Ephemiral Exit Node on my tailnet, and it says:
![image](https://user-images.githubusercontent.com/81783950/230263525-8a03074d-addb-4edf-a72e-ed8d8f1aca43.png)

Additional INFO:
`{"status":"error","error":"missing field AllowedIPs"}` appears in the Developer Console, along with a HTTP 400 Error

### Steps to reproduce

1. Login to Tailscale
2. Attempt to enable an exit node for a device that is advertising it, or disable one that is enabled.
3. Failure

### OS

Windows

### OS version

Windows 11

### Tailscale version

Web

### Other software

Chrome

**Comment by ABUCKY0** [comment]
I think I accidentally opened a new tab that submitted the other bug report for some reason.

**Comment by DentonGentry** [comment]
Approximately how long ago did this happen?

**Comment by ABUCKY0** [comment]
Today, it's been going on for a few hours

**Comment by no1warr1or** [comment]
I'm having the same issue. Tried using both synology and an android device as an exit node. Both return the error in the admin console when trying to enable exit node.

**Comment by mihaip** [comment]
This was a bug that we accidentally deployed to the admin console earlier today. We have deployed a fix, exit node enabling/disabling should once again work (you may need to reload the page to pick up the update).
