### ISSUE TITLE
Can I deploy my own Funnel server?

### ISSUE THREAD

**Issue by lizhengaas** [tailscale/tailscale#7815]

**Comment by DentonGentry** [comment]
[Funnel ](https://tailscale.com/blog/introducing-tailscale-funnel/) provides a publicly resolvable name on the Internet, which accepts incoming TLS sessions and uses the SNI in the ClientHello to identify where the connection should go. Tailscale operates the funnel servers, as we need to have the ability to create public DNS records for `node.tail0123456.ts.net`. The domain `ts.net` is operated by Tailscale. 

There is not a way to operate your own Funnel server, it would not have the ability to manipulate `ts.net` DNS entries. As an alternative, I'd recommend allowing port 443 on the desired node to be reachable from the public Internet and set up DNS for a domain to point to it.

**Comment by herotheo** [comment]
> [Funnel ](https://tailscale.com/blog/introducing-tailscale-funnel/) provides a publicly resolvable name on the Internet, which accepts incoming TLS sessions and uses the SNI in the ClientHello to identify where the connection should go. Tailscale operates the funnel servers, as we need to have the ability to create public DNS records for `node.tail0123456.ts.net`. The domain `ts.net` is operated by Tailscale.
> 
> There is not a way to operate your own Funnel server, it would not have the ability to manipulate `ts.net` DNS entries. As an alternative, I'd recommend allowing port 443 on the desired node to be reachable from the public Internet and set up DNS for a domain to point to it.

Will this feature be open sourced?
