### ISSUE TITLE
Cannot proxy uptime kuma with serve + funnel

### ISSUE THREAD

**Issue by Milo123459** [tailscale/tailscale#7823]
### What is the issue?

I have an uptime kuma instance running on port 3001. I served it like this:
`sudo tailscale serve https /uptime http://127.0.0.1:3001` and expected to see the web app get proxied:
When visiting the tailnet URL, I saw these errors in the developer console:
```
to load resource: the server responded with a status of 404 ()
dashboard:18 Refused to apply style from 'https://******ts.net/assets/index.2b7c584d.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
/icon.svg:1     Failed to load resource: the server responded with a status of 404 ()
/icon.svg:1     Failed to load resource: the server responded with a status of 404 ()
/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
/manifest.json:1 Manifest: Line: 1, column: 5, Unexpected data after root element.
dashboard:1 Refused to apply style from 'https://******ts.net/assets/index.2b7c584d.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
```
This caused the page to not load. Another bug, is that if you just visited /uptime, the app tries to redirect you to /uptime/dashboard (as it should) but instead redirects you to <tailnet>/dashboard. cc @shayne?

### Steps to reproduce

Host uptime kuma (or any app?)
Serve it with tailscale serve and funnel
Watch errors in the console

### OS

Linux

### OS version

Debian 11 aarch64

### Tailscale version

1.38.4

### Other software

Uptime Kuma 1.21.2

### Bug report

BUG-e0e55e6b472c64559b4206c0bb28accaa1e6a6393c356dadfa4116017ea33a9b-20230408100956Z-e994caf556cc2d3d

**Comment by bradfitz** [comment]
> I have an uptime kuma instance running on port 3001. I served it like this:
> `sudo tailscale serve https /uptime http://127.0.0.1`

Did you mean `http://127.0.0.1:3001` then?

**Comment by Milo123459** [comment]
Oops, copied wrong command. That was a mistake (I have tried with :3001 and no luck)

**Comment by shayne** [comment]
Hey there 👋 From what I gather in your description, you're running the app at `/uptime`. Unfortunately, uptime-kuma is unaware of the mount-point, hence the redirection to `/dashboard`. 

The project has [an issue filed](https://github.com/louislam/uptime-kuma/issues/147) asking for path-prefix support.

I recommend mounting it at the `/` (root) mount point. Some folks in the issue have jumped through several hoops to get it to work using various layers in front of the app. Their recommendations might help you.

You can use another port to host uptime-kuma too. You might want this if you use the default HTTPS (port 443) server for another app. On your tailnet, you can serve on any port you'd like (i.e., `tailscale serve https:8123 / http://127.0.0.1:3001`). With Funnel, you can use the default `443`, ' 8443`, and `10000`.

I hope this helps! 😄

**Comment by shayne** [comment]
I am closing since I believe this bug is uptime-kuma does not support a path prefix, thus needs to be mounted at `/`.

**Comment by Milo123459** [comment]
Ah, cheers! Really appreciate your work with serve and funnel :)
