### ISSUE TITLE
Win 10 “Log In” button not work

### ISSUE THREAD

**Issue by glIrving** [tailscale/tailscale#7830]
### What is the issue?

On Windows 10 system, clicking the log in button does nothing. Also, using the tailscale web command and opening the link shown in the command line, the page does not respond when I click it

### OS

Windows

### OS version

windows 10

### Tailscale version

1.38.4

**Comment by glIrving** [comment]
when i set the another ipv4 ip to auto get  it look effect

**Comment by DentonGentry** [comment]
Without a bugreport at the time this was happening, we're not likely to diagnose the root cause.

**Comment by LazerDickMcCheese** [comment]
I have the same issue. A Windows update killed Tailscale, so I did a clean install. Now I can't log in, and no method of manually authenticating my machine works. Seeing as how this issue has been popping up [for](https://github.com/tailscale/tailscale/issues/8408) [a](https://github.com/tailscale/tailscale/issues/7172) [few](https://forum.tailscale.com/t/win-10-log-in-button-not-doing-anything/655) [years](https://github.com/tailscale/tailscale/issues/2282), I'd love to help however I can.

[Tailscale_20230913091613.log](https://github.com/tailscale/tailscale/files/12598094/Tailscale_20230913091613.log)
