### ISSUE TITLE
Missing TUN closes in error paths

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#784]
NewUserspaceEngineAdvanced is missing a few places that it doesn't close its tun dev in its error paths.

https://github.com/tailscale/tailscale/commit/b7e0ff598ad72fa6c48afa0beeae211aad60164f removes a defensive close from the caller because the tun dev's Close isn't safe to call multiple times. 

Ideally we'd:

* make wgengine.NewUserspaceEngineAdvanced close things
* make TUN.Close safe for double close
* document some of this

/cc @danderson

**Comment by DentonGentry** [comment]
`NewUserspaceEngineAdvanced` no longer exists, and [NewUserspaceEngine now](https://github.com/tailscale/tailscale/blob/e8f09d24c77ab4239783ea5d886402b38aeb6a3c/wgengine/userspace.go#L271) barely resembles [NewUserspaceEngine then](https://github.com/tailscale/tailscale/blob/b7e0ff598ad72fa6c48afa0beeae211aad60164f/wgengine/userspace.go#L167).

In particular, the code now adds the TUN device to a closePool:
```
        closePool.add(tsTUNDev)
``` 

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by bradfitz** [comment]
Done enough. Can close now.
