### ISSUE TITLE
Use matching address families for LocalAPI localhost dials on macOS

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#7851]
Summarizing an issue that @nickoneill was debugging elsewhere.

LocalAPI on macOS (from the GUI builds) does a `net.Listen("tcp", "127.0.0.1:0")` to run its HTTP server on (which then requires an HTTP basic auth token distributed such that only the GUI process's user can read it)

But the client side (in two places) does a dial to that listen just using the name "localhost", once in Go, and once in Swift. In some cases (which we don't really understand yet) the client can resolve "localhost" to the IPv6 localhost `::1` and then it fails.

We can't use the `IPV6_V6ONLY` sockopt on the listener because that only works on the wildcard address, which we can't use for firewall pop-up warning reasons. We could have two listeners, but then we'd need a little retry loop to get the ephemeral port numbers lined up, making sure the v6 port is free that corresponds to the ephemeral v4 (or complicate the port number distribution to the GUI and have per-family port numbers).

So easiest is probably just to hard-code "127.0.0.1" on the dialing side in both Swift and Go.

**Comment by nickoneill** [comment]
released in 1.40
