### ISSUE TITLE
Panic in tsnet *Server.ListenFunnel()

### ISSUE THREAD

**Issue by aidansteele** [tailscale/tailscale#7860]
I am trying out the `tsnet` funnel functionality and I am getting a panic when running the example application (also available in [this blog](https://tailscale.dev/blog/embedded-funnel)). Steps:

1. I created an auth key and set it as `TS_AUTHKEY` env var
2. I enabled HTTPS certificates for my tailnet
3. I enabled funnels in my tailnet policy file
4. I ran the example app
5. I get a panic

This line of the example app calls `(*Server).ListenFunnel()`:

https://github.com/tailscale/tailscale/blob/64bbf1738e17dcc5cc74807a338606c9ebcfb687/tsnet/example/tsnet-funnel/tsnet-funnel.go#L31

That function panics on this line because the slice is nil:

https://github.com/tailscale/tailscale/blob/043a34500dd2bb07c34e3b28a56cdbc8b5434454/tsnet/tsnet.go#L912

The rest of the `*ipnstate.Status` seems to be okay (from my limited knowledge), i.e. the `BackendState` is `"Running"`, other fields are populated, etc.

I know this issue isn't much to go by, please let me know what else I can provide to help reproduce this issue. I am guessing this is user error on my part, but it might end up being worthwhile checking `if len(st.CertDomains) == 0` and returning a more useful error message than a panic.

**Comment by DentonGentry** [comment]
`st.CertDomains[0]` refers to Tailscale certificates: https://tailscale.com/blog/tls-certs/
Enabling certificate generation will likely resolve the panic and unblock your development.

We should make tsnet not panic and print a better error in cases like this.

**Comment by aidansteele** [comment]
Aha! I got it working just a moment before I saw your response. It turns out I needed to enable MagicDNS for my tailnet. As soon as I had done that, it started working.

For context, I was following [this how-to guide](https://tailscale.com/kb/1223/tailscale-funnel/) on Tailscale Funnels. It says:

> To enable Tailscale Funnel, you must:
> 
> * Ensure you have [HTTPS certificates](https://tailscale.com/kb/1153/enabling-https/) enabled for your tailnet in the admin console.
> * Add a new funnel attribute under nodeAttrs in your tailnet policy file.
> * Enable Funnel on a specific node with tailscale funnel <port> on.

I had followed the first step (enabled HTTPS certificates), but that was insufficient. After opening this issue, I found on the [Enabling HTTPS how-to guide](https://tailscale.com/kb/1153/enabling-https/) that MagicDNS needs to be enabled for HTTPS certificates to work. So maybe enabling HTTPS certificates from the [admin panel](https://login.tailscale.com/admin/dns) should only be permitted once MagicDNS has first been enabled?

**Comment by bradfitz** [comment]
Looks like this was fixed by @soniaappasamy already in 7815fbe17a68eb033267bc18aad348b638a8ffde and a few following changes.

It could have an explicit check for CertDomains being non-empty too to be extra defensive but the original reported bug should never happen at this point.
