### ISSUE TITLE
Taildrop replaces spaces with %20 in file names sent from macOS->{Windows, Synology, QNAP}

### ISSUE THREAD

**Issue by NewsGuyTor** [tailscale/tailscale#7874]
### What is the issue?

Taildrop replaces spaces with %20 in file names for no good reason when I send files from macOS to Windows, which makes it really annoying to use. 

The file 
"01. The first file of Many Remux (USA, Europe) (Rev A).7z"
becomes
"01.%20The%20first%20file%20of%20Many%20Remux%20(USA,%20Europe)%20(Rev%20A).7z"

It does not happen the opposite direction, from Windows to macOS.

### Steps to reproduce

Find a file with spaces in macOS and Taildrop it to Windows. The spaces will now have been replaced with %20.

### OS

macOS, Windows

### OS version

macOS 13.3, Windows 11

### Tailscale version

1.38.4 (on both)

**Comment by SuperKenVery** [comment]
Same. Additionally, Chinese characters in filename are changed to `%...`S. Maybe you forgot to do URL decode?

**Comment by stevennyman** [comment]
I also have this bug going from iOS 16 to Windows 10

**Comment by gingerbeardman** [comment]
+1 going from macOS to Synology (haven't tried the other way)

**Comment by icio** [comment]
While running App Store tailscaled, `go run ./cmd/tailscale file cp hello\ world.txt windows-recipient:` will successfully create "hello world.txt" on windows without the past escaping. So the issue here appears to be somewhere within the MacOS share extension.

**Comment by icio** [comment]
We've merged a change to the Mac client which I believe fixes this. It should be included in the next update.

**Comment by icio** [comment]
The newly released macOS 1.50 client is available in the App Store and contains this fix. Please let us know how you get on, and if you have any further issues please let us know in a new ticket. Thank you again for bringing this to our attention.

**Comment by gingerbeardman** [comment]
Confirmed foxed for me macOS to Synology.
