### ISSUE TITLE
Failed to update DNS settings

### ISSUE THREAD

**Issue by bitsn1per** [tailscale/tailscale#7886]
I'm using TS for a long time now. Almost all the stuff was fine, until today I've noticed, that I cannot connect to Proton.me through exit node in Germany and using my custom set of DNS. 

I thought that it looks like that DNS may not work correctly and tried to change them. But seems like I cannot change any of DNS settings anymore. When I'm trying to add/remove/change any settings in admin panel I'm recieving following pop-up text:

Failed to update DNS settings: policy file is invalid: host names cannot include an @, please change the name for "server@ntw.com"
![Screenshot_20230415_151903](https://user-images.githubusercontent.com/96927534/232223456-2c5ee93c-1471-4b2e-a5bd-86f4ea4f6a49.png)

**Comment by DentonGentry** [comment]
If you go directly to https://login.tailscale.com/admin/dns, are you able to change the DNS settings?

server@ntw.com cannot work as a DNS server, and though an earlier version of the control server allowed it to be saved to the DB there has been more input validation added since.

**Comment by bitsn1per** [comment]
"If you go directly to https://login.tailscale.com/admin/dns, are you able to change the DNS settings?" - man, when I wrote, that I cannot change them I meant that I did the thing you mean.

**Comment by DentonGentry** [comment]
Though the problem is in handling the DNS settings, the error it is complaining about is in https://login.tailscale.com/admin/acls. There is a `Hosts` entry where the hostname contains an "@", and this is the thing which an earlier version of the coordination server allowed but which now has stronger input validation.

Are you able to remove that Hosts entry and save the ACLs in https://login.tailscale.com/admin/acls ?

**Comment by bitsn1per** [comment]
Unfortunately I'm not able to find any host with @ in its name. I was trying to find it, but there is no anything like this in my devices list. I know them all, but have nothing similar to it. 

So, now I see only two bad ways to solve this problem:
* Get a new Tailnet for my 10+ devices and set up each of them again
* Deauthenticate one-by-one and check if the "@" device removed and then authorize kicked devices again

But I hope there is a better way.

**Comment by bitsn1per** [comment]
Now I see that there is strange "server@ntw.com" that is supposed to be one of my devices, right? But I cannot remember anything like this in my Tailnet. And I'm absolutely sure that I have not this device now. Looks VERY strange.

**Comment by bitsn1per** [comment]
I've never edited tab "Access controls"... And now I see weird stuff there. VERY weird. Maybe someone have any suggestions what could it mean and how it could appear there? Here is my code from there, that I supposed to find default, but seems it is not:

// Example/default ACLs for unrestricted connections.
{
	// Declare static groups of users beyond those in the identity service.
	"groups": {
		"group:group": ["user1@example.com", "user2@example.com"],
	},
	// Declare convenient hostname aliases to use in place of IP addresses.
	"hosts": {
		"server@ntw.com": "100.100.100.100",
	},
	// Access control lists.
	"acls": [
		// Match absolutely everything. Comment out this section if you want
		// to define specific ACL restrictions.
		{"action": "accept", "users": ["*"], "ports": ["*:*"]},
	],
}

**Comment by DentonGentry** [comment]
> that is supposed to be one of my devices

The `Hosts` entries in ACLs are manually added. It was not the hostname of one of the devices on the tailnet, it is just a text string.

Checking backups from some time ago: that Hosts entry has been present since near the creation of the tailnet.

Are you able to remove it? The ACLs and DNS settings should be able to save if it can be removed and allow validation to succeed.

**Comment by DentonGentry** [comment]
> I've never edited tab "Access controls"... And now I see weird stuff there. VERY weird. Maybe someone have any suggestions what could it mean and how it could appear there? Here is my code from there, that I supposed to find default, but seems it is not

That is the default text except that `example-host-1` has been replaced by `server@ntw.com`. It happened long enough ago that the current validation on hostnames was not present, allowing it to be saved.

**Comment by bitsn1per** [comment]
As far as today I've created new Tailnet for another person, I've just copypasted his default settings to that net with problems and problem was solved.

But this is cannot explain the way that strange server@ntw.com stuff appeared in my ACLs. Felling like pwned some way.

**Comment by masonhuemmer** [comment]
I am experiencing this same issue after upgrading to the Starter Plan.

**Comment by PepaonDrugs** [comment]
maxiiii
