### ISSUE TITLE
tailscale serve can't provide tls termination for grpc

### ISSUE THREAD

**Issue by asg0451** [tailscale/tailscale#7893]
### What is the issue?

i have a grpc service on kubernetes with a tailscale sidecar, and i want to expose it to the internet with a Funnel. 

This is the serving setup;
```
# tailscale --socket=/tmp/tailscaled.sock serve https:443 / http://127.0.0.1:8080; tailscale --socket=/tmp/tailscaled.sock funnel 443 on
...
 # tailscale --socket=/tmp/tailscaled.sock serve status

# Funnel on:
#     - https://XX.XXXXX.ts.net

https://XX.XXXXX.ts.net (Funnel on)
|-- / proxy http://127.0.0.1:8080
```
(if i do a `serve` with regular tcp, or if i connect through tailscale directly to port 8080, the service works fine)

on my client, when i try and send a request, it returns:
```
Error: status: Unavailable, message: "grpc-status header missing, mapped from HTTP status code 502", details: [], metadata: MetadataMap { headers: {"content-length": "0", "date": "Sun, 16 Apr 2023 18:27:57 GMT"} }
```

and i see in the sidecar logs:

```
 2023/04/16 18:27:57 http: proxy error: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x04\x00\x10\x00\ │
│ x00\x00\x05\x00\x00@\x00\x00\x06\x01\x00\x00\x00"        
```

does tailscale serve https termination break with grpc/http2?

### OS

Linux

### OS version

Kubernetes/Ubuntu

### Tailscale version

1.38.4   tailscale commit: 043a34500dd2bb07c34e3b28a56cdbc8b5434454-dirty   go version: go1.20.3-tsddff070

### Bug report

BUG-8563b715f0eed5a6fdcff86867a434981502c65eb5a5071bb0693bb8e3f38793-20230416183258Z-2c89c5881f07d89d

**Comment by shayne** [comment]
We have a `$ tailscale cert` command. Here is a link to those docs:
https://tailscale.com/kb/1153/enabling-https/#provision-tls-certificates-for-your-devices

**Comment by shayne** [comment]
@asg0451, were you able to sort things out? I believe this was an issue in using a non-TLS protocol over Funnel.

**Comment by asg0451** [comment]
I actually ended up going in a different direction to unblock myself and
never looked back. There was also an issue where I couldn't guarantee the
k8s ts sidecar would get the name I gave it - - even though the machine was
ephemeral, the old one would hang around and on restart it would choose
NAME-1,-2 etc. I notice you've fixed this issue in the new ssh session
recorder however..

**Comment by shayne** [comment]
Thanks for the feedback. I'll close this, but if there's an outstanding bug, please comment! 😄
