### ISSUE TITLE
Figure out tailscale{,d} file paths for non-linux unixes

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#79]
tailscale{,d} is shaping up, and as part of that I'm moving a bunch of paths around:
 - tailscaled state is in /var/lib/tailscale/*
 - tailscaled's unix socket is in /run/tailscale/tailscaled.sock
 - tailscaled's logs buffer (buffering crash dumps for future upload) will is in /var/log/tailscale
 - tailscale CLI's logs config is in ~/.config/tailscale
 - tailscale CLI's logs buffers are in ~/.cache/tailscale

The tailscaled paths are managed by systemd, so they're guaranteed to always exist on daemon startup, and /run/tailscale is guaranteed to be cleaned up on daemon exit.

What's the right place to put these files on *BSD? I'm guessing most of them are already correct, with the possible exception of /run/tailscale -> /var/run/tailscale ?

cc @wardn @martinbaillie as our resident BSD knowers.

**Comment by martinbaillie** [comment]
Hi @danderson, I think you're on the money with `/var/run/tailscale` for the BSDs and indeed `/var/run/wireguard` is where I have my current wireguard socket sit on my OpenBSD router.

`/var/lib/` is not so much of a thing though. Here's`hier(7)` on each platform for reference:
- https://man.openbsd.org/hier
- https://www.freebsd.org/cgi/man.cgi?hier(7)
- https://linux.die.net/man/7/hier

`/var/cache` may be appropriate if the state persists between daemon executions, `/var/run` if just for runtime flushing to disk? 🤔

**Comment by danderson** [comment]
Huh, weird. I guess /var/lib is a linux-ism from the FHS. TIL.

/var/lib on linux is for state that should persist "for ever", between daemon restarts and until you uninstall the service.

Looking at `hier(7)` for FreeBSD and OpenBSD, I can't see any obvious equivalent. `/var/cache` seems to behave like on linux, i.e. "it's okay to delete this data". Our state is definitely not like that, because it contains private keys for the machine. If you delete that state, you have to re-enroll your machine.

We're going to use `/var/cache` for some stuff (temp log buffers), but I don't think it's correct to use it for our "precious" state.

I guess it's still an open question then... Where do we store daemon-internal state (i.e. not /etc files) that must not be deleted?...

**Comment by martinbaillie** [comment]
I did a little more digging into some other OpenBSD daemons and my survey points at using something like `/var/db/tailscale/`. Most of these stock install daemon manpages highlight some use of either `/var/db/<file>` or `/var/db/<daemon>/<files...>` for persistent state store:

```shell
zuul% apropos -s8 any=/var/db
acpidump(8) - dump ACPI tables
bulk(8) - building OpenBSD packages in bulk
daily, monthly, weekly(8) - periodic system maintenance
dhclient(8) - Dynamic Host Configuration Protocol (DHCP) client
dhcpd(8) - Dynamic Host Configuration Protocol (DHCP) server
kvm_mkdb(8) - create kernel database
ldapctl(8) - LDAP daemon control program
ldapd(8) - Lightweight Directory Access Protocol daemon
locate.updatedb(8) - update locate database
login_yubikey(8) - provide YubiKey authentication type
mountd(8) - service remote NFS mount requests
ntpd(8) - Network Time Protocol daemon
pkg_check(8) - check consistency of installed packages
rpc.statd(8) - host status monitoring daemon
spamd(8) - spam deferral daemon
spamdb(8) - spamd database tool
spamlogd(8) - spamd whitelist updating daemon
sysmerge(8) - update system configuration files
unwind(8) - validating DNS resolver
```

**Comment by danderson** [comment]
Thanks for looking into this @martinbaillie ! With your findings, I was able to find a tiny footnote in the linux FHS that says /var/lib/misc on linux should contain the stuff that's in /var/db on BSD.

So, /var/db/tailscale/* seems to be correct on BSD. Annoying that linux had to be special again, but we can work with that.

**Comment by simonlbn** [comment]
FWIW from a long time FreeBSD user, /var/db/tailscale/ for state and some file in /var/run/tailscale* for unix socket sounds correct / resonable to me for FreeBSD.

Random example, I also have /var/db/samba4/ with a bunch of Samba database files.

There do seem to be a bit less consitency for file extension (or not) for a socket in /var/run (I see e.g. devd.pipe, local_unbound.ctl, and "log"). FreeBSD generally has a bunch of pid files in /var/run too so that may be worth taking into account?

**Comment by debovema** [comment]
> The tailscaled paths are managed by systemd

Is there any instruction to create those paths when testing binaries without systemd ?

**Comment by danderson** [comment]
tailscaled will create directories as needed if they don't already exist, so running standalone or with legacy init should work okay (you'll have to BYO pidfiles or other process management, if you want those things).

I'll implement /var/db and /var/run as defaults for the BSDs.
