### ISSUE TITLE
FR: Openwrt and Alpine offical support

### ISSUE THREAD

**Issue by xrain0610** [tailscale/tailscale#7916]
### What are you trying to do?

this is only third-party package found,but it not always the latest version.

**Comment by DentonGentry** [comment]
OpenWRT support is tracked in https://github.com/tailscale/tailscale/issues/6252

Alpine maintains its own package, and keeps it reasonably up to date:
https://pkgs.alpinelinux.org/package/edge/community/x86/tailscale

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/6252
