### ISSUE TITLE
tailscale windows service does not start after reboot

### ISSUE THREAD

**Issue by alexbrainman** [tailscale/tailscale#793]
**Describe the bug**

My Tailscale service does not run.

**To Reproduce**

1. I stopped `Tailscale IPN` Windows service in `Service` app
2. I deleted all files in `C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs`
3. I shut down my PC
4. I switched my PC back on
5. Waited for a bit

Tailscale GUI says

![image](https://user-images.githubusercontent.com/9796621/94353811-b6747500-00b8-11eb-85e6-662c6b83f7dd.png)

Tailscale Windows service is not running

![image](https://user-images.githubusercontent.com/9796621/94353820-cab87200-00b8-11eb-9624-a2a48ac93f98.png)

My log directory is empty

![image](https://user-images.githubusercontent.com/9796621/94353829-e58ae680-00b8-11eb-95c9-f18c08441361.png)

**Expected behavior**

I expected Tailscale GUI and Windows service to be running once my PC starts.

**Version information:**

 - Device: laptop
 - OS: Windows
 - OS version: Windows 10
![image](https://user-images.githubusercontent.com/9796621/94353877-3f8bac00-00b9-11eb-9fa4-708d0c931be9.png)
 - Tailscale version: 1.1.441
downloaded from https://pkgs.tailscale.com/unstable/tailscale-ipn-setup-1.1.441.exe

**Additional context**

If I start Tailscale service in `Services` app, everything runs as normal. GUI works and log file gets written.

/cc @bradfitz 

Alex

**Comment by bradfitz** [comment]
This seems like working as expected. If somebody stops the Tailscale service, that seems like they're getting what they wanted. What's the bug?

**Comment by alexbrainman** [comment]
> This seems like working as expected. If somebody stops the Tailscale service, that seems like they're getting what they wanted. What's the bug?

Windows service is configure to started automatically on reboot. It does not start automatically. It does not matter weather service is stopped or started before reboot.

And this bug reproduces even if service is not stopped before reboot. I stopped the service before reboot, so I can delete all logs files, so I can show still no log files after reboot.

Alex

**Comment by bradfitz** [comment]
Oh, so stop/start are temporary actions that shouldn't persist across reboots? I don't know Windows services well.

But from this part of your screenshot, it seems there are at least 3 types of "Automatic":

<img width="114" alt="Screen Shot 2020-09-27 at 9 23 56 PM" src="https://user-images.githubusercontent.com/2621/94390516-c10a2b00-0107-11eb-8a99-f567f55ce23f.png">

So maybe we're using the wrong type of "Automatic", eh?

**Comment by alexbrainman** [comment]
> Oh, so stop/start are temporary actions that shouldn't persist across reboots?

Correct. Windows service can be stopped or started or paused or whatever when computer is rebooted. It does not affect what happens to the service when computer is started again. It is the `Startup type` that decides what happens to the service when computer is booted. And `Tailscale` service has `Startup type` set to `Automatic` by installer (grep for `StartAutomatic`).

![image](https://user-images.githubusercontent.com/9796621/94430033-9b982280-01d6-11eb-8b98-f9b2a14d35e7.png)

> But from this part of your screenshot, it seems there are at least 3 types of "Automatic":

Apparently so

![image](https://user-images.githubusercontent.com/9796621/94430229-e7e36280-01d6-11eb-8000-cc39e27ffd76.png)

> So maybe we're using the wrong type of "Automatic", eh?

No, `Tailscale` service is configured to correct "Automatic" - `mgr.StartAutomatic`.

I just need to debug this. It does not happens every single time. For example, it did not happen now - I just switched my PC on, and Tailscale service is running. I will try it when I have time.

But, assuming it does not happen to you, it is something specific to my computer.

Alex

**Comment by alexbrainman** [comment]
I cannot reproduce this anymore. I tried reinstalling both

```
---------------------------
About Tailscale
---------------------------
Version 0.1.2766 (g3d9054098)

Latest stable: 1.0.4
---------------------------
OK   
---------------------------
```

and

tailscale-ipn-setup-1.1.441.exe

and they work.

I will leave this alone for now. Maybe it will start happening again.

Alex

**Comment by alexbrainman** [comment]
I have not seen this happen even once since https://github.com/tailscale/tailscale/issues/793#issuecomment-700565644. Maybe I made some mistake  when I installed Tailscale before. I really don't know why I cannot reproduce this anymore.

Closing this. Will reopen if it happens again.

Alex
