### ISSUE TITLE
FR: Add Control D as a DNS option

### ISSUE THREAD

**Issue by Glenta** [tailscale/tailscale#7946]
### What are you trying to do?

Incorporate Control D as an available DNS option.

### How should we solve this?

Similar to the inclusion of NextDNS, I propose the addition of Control D as an alternative option.

### What is the impact of not solving this?

Users are limited in their ability to customize Tailscale, as certain features, such as using Control D with the platform, require workarounds. For example, users must manually input four DNS addresses in the Tailscale console and register their IP address with Control D to authenticate themselves. This can be particularly onerous for users with dynamic IP addresses, which are common in mobile networks. Although secure DNS options are available that do not require this workaround, Tailscale does not currently support features such as DNS over HTTPS/TLS/DoQ.

### Anything else?

[Control D's API documentation](https://docs.controld.com/reference/get-started)
[Why you need to register your IP with Control D for the service to work](https://docs.controld.com/docs/ip-not-authorized)

**Comment by trollybusman** [comment]
+1 I would love this as I recently switched from NextDNS and prefer Control D.

**Comment by yegors** [comment]
One of the devs here, would love to get this integration done.

**Comment by Aureyl** [comment]
Would love to Tailscale ;-)

**Comment by Ginder-Singh** [comment]
It would be great to see Control D as option.

**Comment by bradfitz** [comment]
Please use GitHub reactions instead of duplicate comments unless you have something unique to say.

**Comment by bradfitz** [comment]
@yegors, here's what we'd want: a way to send an HTTP header or URL parameter to your DoH endpoint to specify the profile ID to use.

And your DoH endpoint should have a well-known anycast IP (v4 and v6) and not require bootstrap DNS, ideally.

**Comment by yegors** [comment]
Hey @bradfitz, 

The DNS-over-HTTPS endpoint is indeed anycast and supports IPv4/IPv6 is: https://dns.controld.com/xxxxxxxxx

- All 3 versions of HTTP are supported, including H3 / QUIC
- `xxxxxxxxx` is where the Resolver ID goes, which is unique to every "Device": https://docs.controld.com/docs/devices

Control D is different from NextDNS in a sense that Resolvers (Devices) enforce Policies (Profiles), as opposed to being "Profiles" themselves. This allows for a Profile to be swapped (or rotated on a schedule) on an existing Device. 

Additionally, for a more useful integration the following DOH headers can be supplied along with every DNS query. 
- `x-cd-mac` - MAC address of the client
- `x-cd-ip` - Local/internal tailscale IP address
- `x-cd-host` - hostname of the client 

This will allow Control D to track each Tailscale client separately, and enforce a unique DNS policy if desired, as opposed to all clients being subject to the rules of a common Profile. Our router utility (which has access to view DHCP leases) works [exactly like this](https://github.com/Control-D-Inc/ctrld/blob/d7a38363e6b74fe2a87b023a0ff1d6e4caa674ce/doh.go#L98). See general docs here: https://docs.controld.com/docs/device-clients

If DOH headers are not feasible to supply, the DOH URI can be modified like so:
- https://dns.controld.com/xxxxxxxxx/MACHINE-HOSTNAME-HERE

This would allow for enforcement of a unique Profile on chosen client, just without any other metadata (MAC, IP). 

If you have any questions, let me know. 

Thanks!

**Comment by bradfitz** [comment]
@yegors, can we hard-code `76.76.2.22` and `2606:1a40::22` in the client, then?

**Comment by yegors** [comment]
@bradfitz Yes, they will not change.

**Comment by jamesg226** [comment]
Is there any update on this feature?

**Comment by gniting** [comment]
@bradfitz @DentonGentry any updates on this please?

**Comment by DentonGentry** [comment]
I promise we will update the bug when there is something to report.

The best way to express interest is to upvote the first comment, we have tooling to sort & prioritize issues which takes upvotes into account.

**Comment by bradfitz** [comment]
The @alexelisenko change (https://github.com/tailscale/tailscale/pull/8417 / https://github.com/tailscale/tailscale/pull/11659) is now merged.

It means Control D IPs will be upgraded to DoH by the client, but there's no server-side support for selecting Control D yet.

And there's no extra headers yet. I removed those from the PR (there were TODOs wondering the right way to do it, so I figured it could come later).

The next step is probably for somebody from Control D to arrange a call with @kabirsikand to figure out next steps.

**Comment by alexelisenko** [comment]
@bradfitz Thanks for cleaning up the rebase. Let me know what the proper method is for adding tailscale client metadata to the DoH requests, as I know this will be a highly requested feature.

@kabirsikand Please let me know what you need to continue the integration 🙏

**Comment by maxexcloo** [comment]
In terms of using this the same way I use nextdns - is this ready to go now? Apologies if it’s answered above but I didn’t fully understand what has been merged and if there’s anything else to go.

**Comment by dmd** [comment]
> In terms of using this the same way I use nextdns - is this ready to go now? Apologies if it’s answered above but I didn’t fully understand what has been merged and if there’s anything else to go.

No, it still needs integration. Presumably this issue will be closed when it's ready.

**Comment by gniting** [comment]
I see [this](https://docs.controld.com/docs/tailscale-integration) in the controld docs, so am assuming this is coming soon. 

Can someone from the tailscale team confirm? (@bradfitz @kabirsikand)

**Comment by tomdh76** [comment]
I have controlD now setup in Tailscale as global name server and it is working fine. Would it also be possible to use different endpoints in controlD for different clients? In Nextdns I used the nodeattrs variable in the ACL to redirect the phones of my kids to another profile in nextdns. I tried to do the same with controld (ie. 

"nodeAttrs": [
		{
			"target": ["tag:kids"],
			"attr": [
				"controld:xxxxxx",
			],

but this does not seem to work

**Comment by kabirsikand** [comment]
This [feature is now available for all customers](https://tailscale.com/blog/controld) with a Control D account. For more information, take a look at our [documentation](https://tailscale.com/kb/1403/control-d).

**Comment by 0xFFA500** [comment]
Please may we get the Control D public servers added?

https://controld.com/free-dns

I personally use https://freedns.controld.com/x-oisd

Would it be as simple as adding the IPs and corresponding DoH addresses here? https://github.com/tailscale/tailscale/blob/15b2c674bff3cfc17d1d77c09105bf818428a238/net/dns/publicdns/publicdns.go#L192-L208
