### ISSUE TITLE
Running netcheck results in a runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bramnet** [tailscale/tailscale#7949]
### What is the issue?

When running tailscale netcheck in cmd, the following error occurs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x93c5b3]

goroutine 50 [running]:
tailscale.com/net/netcheck.(*reportState).runProbe(0xc00027c000, {0xbc9690, 0xc000273810}, 0x0?, {0x0, {0xc00020a570, 0x2}, 0x1, 0x0}, 0xc000228420)
        tailscale.com@v1.1.1-0.20230422043621-e3b2250e2654/net/netcheck/netcheck.go:1569 +0x653
created by tailscale.com/net/netcheck.(*Client).GetReport.func6
        tailscale.com@v1.1.1-0.20230422043621-e3b2250e2654/net/netcheck/netcheck.go:998 +0x76
```

### Steps to reproduce

Open cmd.exe, run the command ``tailscale netcheck``, it fails.

### Are there any recent changes that introduced the issue?

This is a fairly new install, I didn't make any changes after install as far as I recall.

### OS

Windows

### OS version

Win10 22H2

### Tailscale version

1.39.194

### Other software

I'm running NordVPN which might potentially be causing the issue. I added tailscaled.exe, tailscale.exe and the Tailscale GUI client to the split tunneling list to try and avoid issues.

### Bug report

BUG-4fab5752eefc5f1b4358829341a442f10e86e1519ee9cca7f78d398eb07048ca-20230422212303Z-48106b53f4cbf11b

**Comment by DentonGentry** [comment]
Trying `tailscale netcheck` on a Win10 system with 1.39.194 I don't get a panic, so indeed there must be a little more to it.

net/netcheck/netcheck.go:998: https://github.com/tailscale/tailscale/blob/7778d708a6a443dc03f8afc342f1b310b019b662/net/netcheck/netcheck.go#L998

net/netcheck/netcheck.go:1569: https://github.com/tailscale/tailscale/blob/7778d708a6a443dc03f8afc342f1b310b019b662/net/netcheck/netcheck.go#L1569

**Comment by DentonGentry** [comment]
pc6 is https://github.com/tailscale/tailscale/blob/7778d708a6a443dc03f8afc342f1b310b019b662/net/netcheck/netcheck.go#L566:
```
type reportState struct {
	c           *Client
	hairTX      stun.TxID
	gotHairSTUN chan netip.AddrPort
	hairTimeout chan struct{} // closed on timeout
	pc4         STUNConn
	pc6         STUNConn
```

Does the main Ethernet or Wi-Fi interface on that Windows system have an IPv6 address assigned in `ipconfig`?

**Comment by bramnet** [comment]
It does not, a long time ago I was running into issues with NordVPN and I was told by their team to disable IPv6. I can try re-enabling it.

**Comment by DentonGentry** [comment]
Do you recall how IPv6 was disabled on that system? If I go into the network device properties and disable Internet Protocol version 6, I still don't get this crash.

<img width="366" alt="Screenshot 2023-04-22 at 3 00 25 PM" src="https://user-images.githubusercontent.com/1140756/233808285-76d207c7-c875-44f9-b195-0d554caeda2e.png">

**Comment by bramnet** [comment]
That's how I disabled it, so I'm confused as well.
I just re-enabled it and I suddenly had network issues. Ran Windows' built-in network troubleshooter on my primary network switch and it says there was a problem with my gateway settings. It reset and after getting everything re-established, I'm still encountering the same fatal error.

**Comment by DentonGentry** [comment]
This is the important line in the traceback, is it still the same?
```
created by tailscale.com/net/netcheck.(*Client).GetReport.func6
        tailscale.com@v1.1.1-0.20230422043621-e3b2250e2654/net/netcheck/netcheck.go:998 +0x76
```

`func6` is the function to probe using IPv6.

**Comment by bramnet** [comment]
Yes, it is still indicating that it's an issue with func6.
