### ISSUE TITLE
admin: add a way to edit a machines DNS name

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#795]
For network admins managing many devices, it can be helpful to assign more semantic names to devices. For example, if you're running a DigitalOcean droplet, your machine might be named `ubuntu-s-1vcpu-1gb-tor1-01`, but as an admin, you may want to see something more meaningful, such as `production-tor1-01`.

This is even more important with [Magic DNS](https://tailscale.com/kb/1081/magic-dns), where we want devices to have unique names that become DNS addresses e.g. _production-tor1-01.smallhouse.co_.

Admins should be able to assign DNS names to devices from the admin panel. These DNS names should default to the device's hostname, which users control (via their settings or the `--hostname` flag), but admins can override them in the panel to manage their devices better.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2g1zl)

**Comment by tosie** [comment]
👍

This would be really nice as changing hostnames is sometimes not easy or possible (e.g. a Windows primary domain controller that has been in use for some time).

**Comment by soniaappasamy** [comment]
Ability to edit a machine's name from the admin panel has been deployed! For information about how to rename the machine see https://tailscale.com/kb/1098/machine-names
