### ISSUE TITLE
Tailscale on Synology can not connect to custom derper with an invalid certificate

### ISSUE THREAD

**Issue by donargreys** [tailscale/tailscale#7952]
### What is the issue?

Tailscale 1.38.3 on my Synology DSM 7.1.1-42962 Update 4 can not connect to my custom derper,  with 
`tailscacle status`
it shows like
`# Health check:`
`#     - not connected to home DERP region 900`
but my macbook under same network can work properly
by the way, official relays work fine on both Synology and macbook
ACL looks like
```
"derpMap": {
		"OmitDefaultRegions": true,
		"Regions": {"900": {
			"RegionID":   900,
			"RegionCode": "myderp",
			"Nodes": [{
				"Name":     "1",
				"RegionID": 900,
				"HostName": "xxxx.xxxxx",
				"DERPPort": xxxx,
			}],
		}},
	},
```

### OS

Synology

### OS version

DSM 7.1.1-42962 Update 4

### Tailscale version

1.38.3

**Comment by FlintyLemming** [comment]
Same as you, my derper works fine days ago, but can not connect these days.

**Comment by DentonGentry** [comment]
We would need one of the following to find telemetry from the device to make progress:
- a bugreport, generated by SSHinf to the device and running `tailscale bugreport`, or
- the Tailscale IP of the Synology device, 100.x.y.z, or
- the tailnet name tail0123456.ts.net, or
- the domain name or GitHub profile/organization name associated with the tailnet.

If not comfortable putting this in a public bug, you're welcome to send information to support@tailscale.com and reference https://github.com/tailscale/tailscale/issues/7952

**Comment by donargreys** [comment]
BUG-5703ff6febbadb534ec3ca10c7d743a2c010536911aba8a27a539ab39d49ebe8-20230426045915Z-3cae9634fa649ede

**Comment by DentonGentry** [comment]
`2023-04-26 04:54:20.256854893 +0000 UTC: magicsock: [0xc0038e20f0] derp.Recv(derp-900): derphttp.Client.Recv connect to region 900 (myderp): x509: certificate signed by unknown authority`

**Comment by donargreys** [comment]
i am actually using a Let's Encrypt Cert
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:af:1b:43:32:31:11:a6:88:55:db:07:ee:54:6c:0f:7b:39
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=R3
        Validity
            Not Before: Mar 30 01:46:35 2023 GMT
            Not After : Jun 28 01:46:34 2023 GMT
```

**Comment by DentonGentry** [comment]
If you use `openssl s_client -showcerts -connect derp20b.tailscale.com:443 </dev/null | sed -n -e '/-.BEGIN/,/-.END/ p'` you'll see four certificates.

If you use that same command on the custom derper, do you see four?

I suspect it is not serving one of the intermediate certificates, perhaps one which the Macbook has installed in its own cert store but the Synology does not.

**Comment by DentonGentry** [comment]
return -ETIMEDOUT;
