### ISSUE TITLE
Gitops Comment not Recognized

### ISSUE THREAD

**Issue by jonathan-wondereur** [tailscale/tailscale#7953]
### What is the issue?

When implementing Gitops with my self-hosted Gitlab instance, the comment does not seem to be recognized by the Tailscale ACL page, and this page does not show a warning about editing the ACLs directly.

### Steps to reproduce

Add the comment to your ACL file using a custom GitLab domain:

```
// This tailnet's ACLs are maintained in: https://gitlab.example.com/group/project
```

### Are there any recent changes that introduced the issue?

#5905

**Comment by marwan-at-work** [comment]
@jonathan-wondereur thanks for opening the issue :) 

The gitops comment's rules are a bit strict which requires you to put a space after the last word and not `:` so the change you need to make is:

```diff
- // This tailnet's ACLs are maintained in: https://gitlab.example.com/group/project
+ // This tailnet's ACLs are maintained in https://gitlab.example.com/group/project
```


@DentonGentry let me know if we should make the comment a little less strict, thanks

**Comment by DentonGentry** [comment]
> let me know if we should make the comment a little less strict, thanks

I think that would be a good idea, sure. That would be done in the coordination server.

**Comment by jonathan-wondereur** [comment]
@marwan-at-work Thank you for letting me know. I will try that now.

@DentonGentry I don't think you need to change it to be less strict, but I would suggest you correct the documentation to include the `:` here: https://tailscale.com/kb/1254/gitops-acls-gitlab/

**Comment by jonathan-wondereur** [comment]
@marwan-at-work I in fact did have the `:` in my ACL.

I tried removing the path to the file that I did have at the end of the GitLab URL `/-/edit/main/policy.hujson` but it still did not work.

Are you sure it is working for subdomains? Or does it only work for top-level domains right now (such as `example.com` but not `gitlab.example.com`)?

**Comment by jonathan-wondereur** [comment]
That change worked. Thanks.
