### ISSUE TITLE
handshake message of length 3647366 bytes exceeds maximum of 65536 bytes

### ISSUE THREAD

**Issue by IT-dragon** [tailscale/tailscale#7961]
### What is the issue?

when i exec "systemctl status tailscaled -l " the output is:
magicsock: [0xc0041183c0] derp.Recv(xxx): derphttp.Client.Recv connect to region xxx: tls: handshake message of length 3647366 bytes exceeds maximum of 65536 bytes

note:i use personal derp.i can not connect my server

### OS

CentOS

### Tailscale version

1.32

**Comment by DentonGentry** [comment]
> tls: handshake message of length 3647366 bytes exceeds maximum of 65536 bytes

Are you connecting through the great firewall?

**Comment by IT-dragon** [comment]
@DentonGentry yes,but i have a headscale server and custom derper in my server.

**Comment by DentonGentry** [comment]
That is all fine, but we're not going to be able to help in getting connections through the great firewall.

I don't know why other platforms work while the Synology does not, but I don't expect to be able to figure out why there is a difference.

**Comment by IT-dragon** [comment]
I mean I deployed the headscale control server myself, and customized the derp server. My service only provides peer-to-peer communication for nodes that are behind a great firewall. Although I am behind the Great Firewall, I will not go through the Great Firewall. I don't know if I understand this right

**Comment by IT-dragon** [comment]
I can describe the situation in more detail: I have a headscale control server and a relay server, they are located in the same virtual machine on the same server, and this appeared when I provided other virtual machines in the server to the host outside the server problem, and according to my observation, this problem occurs after the linux system is powered off and restarted. And at present, the nodes outside the server can normally provide point-to-point communication through the relay, and the virtual machines in the server can also communicate normally through stun.

**Comment by IT-dragon** [comment]
![image](https://user-images.githubusercontent.com/49020985/234468986-810d82da-691e-4b74-b7f5-f4f2c9ebbb8f.png)
i deploy another derp server to create this problem.
tailscale netcheck is normal.
![image](https://user-images.githubusercontent.com/49020985/234469191-8500284f-35c1-43bf-a60d-ffdd5e19bb41.png)
tailscale status:direct way is normal.
![image](https://user-images.githubusercontent.com/49020985/234469422-805d0f2e-e6c0-43ab-a021-12d0b0005b39.png)
i make sure i close the firewalld.
![image](https://user-images.githubusercontent.com/49020985/234469534-255c6a0a-bf4b-4e09-8a9f-eed41e1836da.png)

**Comment by IT-dragon** [comment]
even some machines is normal:
![image](https://user-images.githubusercontent.com/49020985/234469878-13184164-5120-4d35-8b93-8ee4f5585cce.png)

**Comment by DentonGentry** [comment]
There is something in front of the derp interfering with its connections. That might be a firewall, or a load balancer, or something. We won't be able to see that from here, it is something you will need to figure out.

You are asking us to debug your Headscale installation. You're welcome to self-host, but self-hosting means debugging it yourself.
