### ISSUE TITLE
magicsock: derp.Send(127.3.3.40:900): derphttp.Client.Send connect to region 900 (xxx): EOF

### ISSUE THREAD

**Issue by IT-dragon** [tailscale/tailscale#7962]
### What is the issue?

tailscaled can not connect derp
![image](https://user-images.githubusercontent.com/49020985/234275739-0c6d6f7f-e1fc-4860-b6eb-aa995ec3e8cc.png)
anyone know this problem?

### OS

Linux

### Tailscale version

1.30.2

**Comment by DentonGentry** [comment]
Please don't open more issues regarding connectivity to this DERP server, continue to use https://github.com/tailscale/tailscale/issues/7961
1. There is clearly a problem connecting to it, likely an intervening firewall or load balancer.
1. You're asking us to debug your Headscale installation.
