### ISSUE TITLE
tailscale.dev RSS feed throwing error

### ISSUE THREAD

**Issue by j5155** [tailscale/tailscale#7968]
### What is the issue?

The Tailscale.dev RSS feed at https://tailscale.dev/feed.xml has `error on line 67 at column 108: EntityRef: expecting ';'
` at the top of the page, making it unreadable by feed readers.

### Steps to reproduce

1. Open https://tailscale.dev/feed.xml in a web browser or feed reader.
2. See thrown error

**Comment by shayne** [comment]
Moved over to tailscale-dev/tailscale-dev#203
