### ISSUE TITLE
Update api.md to reflect the network-logs endpoint

### ISSUE THREAD

**Issue by joshuabalduff** [tailscale/tailscale#7970]
I found a reference to this endpoint in the documentation, but it was challenging to reproduce it. When I tried, I received a 404 error, which might be due to it still being in beta. I reached out here to confirm the endpoint's validity, but unfortunately, I was unable to locate it.

**Comment by DentonGentry** [comment]
Um. Thanks, but not yet.

![penguin-hide](https://user-images.githubusercontent.com/1140756/234445710-e2cbdc5c-5359-432c-b2ad-50f9fd82fddd.gif)
