### ISSUE TITLE
FR: Connection from PC/Laptop/Client to tailscale server is slow due to broken oversea fiber optic cable.

### ISSUE THREAD

**Issue by nguyenbinh95** [tailscale/tailscale#7972]
### What are you trying to do?

Hi team,

As I described, I now have a problem when connecting from PC/Laptop/Client to tailscale server is slow due to broken oversea fiber optic cable. It's make the connection between my two servers depends on oversea connection (high ping latency, low bandwidth, drop packages...).

### How should we solve this?

I'm write this messenger to ask if I public one my tailscale node, can it improve the connection? 
I have an idea that the Tailscale server will action as DNS server and the connection does not need to go through the tailscale server.

### What is the impact of not solving this?

Hmm, My connection between two PC very slow and high ping latency. It's depend on internet from my country to oversea and to Tailscale server

### Anything else?

It would be better if you could guide me in detail about connection. If I public port on the tailscale node to the internet and related configurations

**Comment by knyar** [comment]
Tailscale nodes will always attempt to establish a direct connection to each other, and in vast majority of cases the traffic will not be relayed through a Tailscale server. In some cases (for example, when both devices are behind particular implementations of NAT), a direct connection cannot be established, and devices will use one of [our secure relays](https://tailscale.com/kb/1232/derp-servers/) to send traffic to one another.

You can run `tailscale status` to check if your devices have been able to establish a direct connection or if they are using a relay.  If you are able to change firewall settings for your devices, allowing connections to UDP port 41641 via a public IP will typically help establish a direct connection.

Please see [Firewalls](https://tailscale.com/kb/1181/firewalls/) and [Firewall ports](https://tailscale.com/kb/1082/firewall-ports/) pages in our knowledge base for more details.
