### ISSUE TITLE
ipn/ipnlocal: peer usage log lines printing incorrectly

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#7976]
The "grinder" log lines have been printing incorrectly since 8b2ae47c31c9574d, printing like:

```
2023-04-26 16:57:30.515595 +0000 UTC: v0x10d1e6740 peers: 0/0 0/0 0/0 0/0
```

Because the argument to "v%v" is now a func and not a string.

**Comment by bradfitz** [comment]
Seen in 1.38.4.  Introduced in 1.38.0.

**Comment by maisem** [comment]
We should figure out a way to test these

**Comment by creachadair** [comment]
> We should figure out a way to test these

FWIW there are already [some tests](https://github.com/tailscale/corp/blob/main/logstore/chompservice/logparser/lineinfo_test.go#L41) for the code that parses these log lines, so we're not entirely bare to the wind. (Ideally we shouldn't be leaning quite so much on exact log message formatting, but I realize it's not trivial to get rid of that now)
