### ISSUE TITLE
Througput rate 

### ISSUE THREAD

**Issue by GGitboy** [tailscale/tailscale#7989]
### What are you trying to do?

In direct connection mode, the scp transmission rate is 10MB/S, and the relay mode  remote transmission rate is about 1MB/S. What factors affect the transmission rate of TalilScale, and how to improve the local-to-remote transmission bandwidth?

**Comment by DentonGentry** [comment]
Looking into throughput usually involves IP addresses and other information which should not be put in public bugs. Please file a support ticket at https://tailscale.com/contact/support/, not a bug.
