### ISSUE TITLE
How can I run tailscale with another user?

### ISSUE THREAD

**Issue by 1984admin** [tailscale/tailscale#7990]
### What are you trying to do?

How can I run tailscale with another user?
Because I want to mark the output traffic of tailscale so that it goes through a different interface.

### How should we solve this?

Create a new user tailscale, and run it with the tailscale user.

### What is the impact of not solving this?

I'm in China, if I don't mark the output of tailscale traffic, tailscale will output through a Japanese proxy server

**Comment by DentonGentry** [comment]
The request is:
- there are multiple network interfaces
- you want to make Tailscale traffic use one specific interface
?
