### ISSUE TITLE
Set up issue labels

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#8]
We should configure this project's labels:

https://github.com/tailscale/tailscale/labels

Ideas:

* by client type / OS
* "connectivity"

What else?

/cc @danderson @apenwarr @crawshaw @dfcarney

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687699060969) by [Unito](https://www.unito.io/learn-more)

**Comment by apenwarr** [comment]
I added labels based on https://lostgarden.home.blog/2008/05/20/improving-bug-triage-with-user-pain/ which is a system that seems to work pretty well. We can add more later as needed of course, but I'll mark this as done.
