### ISSUE TITLE
Debian/RPM packages for MIPS stopped after 1.36

### ISSUE THREAD

**Issue by kevinisageek** [tailscale/tailscale#8005]
### What is the issue?

Hey folks,

I know that EdgeOS isn't officially supported, however it has worked fine up until recently, following [jamesog's guide](https://github.com/jamesog/tailscale-edgeos). The machines page says there is an update available to 1.40.0 but SSH'ing into the edgerouter and upgrading says everything is up to date. I'm wondering if the Stretch repository needs the new version added to it? 

### Steps to reproduce

Standard `sudo apt update` and `sudo apt upgrade`

### Are there any recent changes that introduced the issue?

New tailscale version released

### OS

Linux

### OS version

EdgeOS v2.0.9-hotfix.6

### Tailscale version

1.36.2

### Other software

N/A

### Bug report

BUG-d817bfcb0a57e8b22b3df24fdd8799d186220f46b3924273e1f41e1a2c305f2c-20230429063528Z-def693c9d64b89fe

**Comment by DentonGentry** [comment]
Was `apt install tailscale=1.36.2` ever done, locking it to a particular version?

The stretch repository does get updated for each release.

**Comment by tgies** [comment]
Can confirm that the stretch repo, at least for mipsel, only has up to 1.36.2. This can be seen by examining the Packages manifest directly: https://pkgs.tailscale.com/stable/debian/dists/stretch/main/binary-mipsel/Packages

**Comment by DentonGentry** [comment]
I think the MIPS support didn't get properly converted when the release/dist tooling was open sourced.
I believe the support needs to go here: https://github.com/tailscale/tailscale/blob/979d29b5f59fcf67d96d2dfd3bcc91c6fd912dc7/release/dist/unixpkgs/pkgs.go#L344

**Comment by DentonGentry** [comment]
We are currently at the "how did this ever work?" stage of debugging. Even the prior distribution builder, which was in a private repo, doesn't look like it should have built deb/RPM packages for MIPS. Yet, apparently, it did.

**Comment by danderson** [comment]
It ever worked because we accidentally started shipping MIPS debian packages at some point. When building cmd/dist, I stopped building them because I was pretty sure they weren't being built right (e.g. wrong architecture constants) : https://github.com/tailscale/tailscale/blob/979d29b5f59fcf67d96d2dfd3bcc91c6fd912dc7/release/dist/unixpkgs/targets.go#L90

I guess now we know the answer: at least some of these variants do work! Uncommenting should be all that's needed, though possibly some go<>deb arch name conversion funcs need updating too, not sure.

**Comment by DentonGentry** [comment]
@tgies
> If we're thinking that the Go arch to deb arch mapping there is all that's needed, I can submit a PR to add the missing ones back in?

Please send the mappings you are using or otherwise know to have worked with 1.36. We can at least add the ones which were working.

**Comment by tmn** [comment]
Experiencing the same thing using EdgeOS 😄  Here's mine:

```
Linux EdgeRouter-Pro-8-Port 4.9.79-UBNT #1 SMP Thu Oct 20 07:48:35 UTC 2022 mips64 GNU/Linux
```
