### ISSUE TITLE
log.tailscale.io should have a brief explanatory page

### ISSUE THREAD

**Issue by odeke-em** [tailscale/tailscale#801]
**To Reproduce**
Go to https://github.com/tailscale/tailscale/blob/e1596d655a15c5d5bc402e5bff18f56402ae07f6/logtail/example/logreprocess/demo.sh#L17
And try to visit that link https://log.tailscale.io

**Expected behavior**
I should be able to see a page with information about the logs service 

**Screenshots**
![A81D8DF3-D506-4EE0-9550-FA57C4146A5D](https://user-images.githubusercontent.com/4898263/94849296-06fe1200-03da-11eb-88a9-b7f994520dd0.jpeg)

**Comment by bradfitz** [comment]
Well, there's no service, but I suppose we can put a sentence there at least.

Or just redirect to https://tailscale.com/ perhaps?

@crawshaw, @danderson, preferences?
