### ISSUE TITLE
FR: Allow MDM configuration of Tailscale tenant to go to a specific login page

### ISSUE THREAD

**Issue by wegotoeleven** [tailscale/tailscale#8010]
### What are you trying to do?

Presently, when a user attempts to log into Tailscale via the "Log in..." option in Tailscale, the user is redirected to https://login.tailscale.com/login. Ideally, it would be useful if the user could be automatically redirected to their Tailscale tenant (or idP, if one is setup).

### How should we solve this?

Other vendors/services accomplish this by allowing an admin to push configuration to each device which automatically points them to their tenant/idP, (for an example, see https://slack.com/intl/en-gb/help/articles/11906214948755-Manage-desktop-app-configurations#mac-1, specifically the `DefaultSignInTeam` key)

### What is the impact of not solving this?

- The login experience is clunky and requires more clicks than necessary
- There are chances of login errors
    - for example, if an admin has connected Okta to Tailscale, and the org is also a Google apps user, then there may be situations where a user within the org selects "Signin with Google" instead of typing in their e-mail address

**Comment by DentonGentry** [comment]
I believe the intent is to go straight to a login page for a given tailnet, without extra Google / Microsoft / GitHub / etc buttons.

**Comment by agottardo** [comment]
Tailscale 1.52.0 [adds a `Tailnet` system policy](https://tailscale.com/kb/1315/mdm-keys/#set-a-suggested-or-required-tailnet) which provides this option:

> The `Tailnet` policy allows the organization to specify a tailnet, its identity provider will be used on the login page. If the policy value is prefixed with `required:`, Tailscale will force that identity provider to be used and won’t allow logging in with anything else.
> 
> - Supported platforms: Windows, macOS, iOS, tvOS
> - Possible values: a tailnet name, for example: `example.com` or `required:example.com`
