### ISSUE TITLE
`tailscale netcheck`: nil pointer when there are no DERP responses

### ISSUE THREAD

**Issue by ateixeirag** [tailscale/tailscale#8016]
### What is the issue?

C:\Users\aleja>tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 45.238.177.116:54882
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x102c25f]

goroutine 1 [running]:
tailscale.com/cmd/tailscale/cli.printReport(0xc0001da0d0, 0xc000336160)
        tailscale.com@v1.40.0/cmd/tailscale/cli/netcheck.go:151 +0x53f
tailscale.com/cmd/tailscale/cli.runNetcheck({0x1251828, 0xc0000240d8}, {0x0?, 0x0?, 0xc00006bf40?})
        tailscale.com@v1.40.0/cmd/tailscale/cli/netcheck.go:91 +0x494
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0x0?, {0x1251828?, 0xc0000240d8?})
        github.com/peterbourgon/ff/v3@v3.1.2/ffcli/command.go:153 +0x16c
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc000144630?, {0x1251828?, 0xc0000240d8?})
        github.com/peterbourgon/ff/v3@v3.1.2/ffcli/command.go:157 +0x113
tailscale.com/cmd/tailscale/cli.Run({0xc00006c3d0?, 0xc00007c000?, 0xc00005e000?})
        tailscale.com@v1.40.0/cmd/tailscale/cli/cli.go:173 +0x905
main.main()
        tailscale.com@v1.40.0/cmd/tailscale/tailscale.go:22 +0xfb

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.40.0   tailscale commit: 105be684dd04727a58ed213ec9499d071a377ece   other commit: 4c70014a47f1816e1573a8cef58cdaf96f78a264   go version: go1.20.3-tsddff070

**Comment by DentonGentry** [comment]
We solved a different issue in `tailscale netcheck` shortly before 1.40, relating to a system with a non-functional IPv6 stack: https://github.com/tailscale/tailscale/issues/7949

The backtrace here doesn't resemble that one, though. This looks different.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/blob/9bdaece3d7c3c83aae01e0736ba54e833f4aea51/cmd/tailscale/cli/netcheck.go#L151

**Comment by DentonGentry** [comment]
The template asks for a bugreport so we can look up telemetry from the node. Could you add one?

**Comment by ateixeirag** [comment]
How can I get the bugreport?

**Comment by ateixeirag** [comment]
BUG-036413e9bb17a902a4f428d2f88af8f440e0d8b288b6332694c2dcf6a4c708c3-20230502012823Z-668b5cc1e008fed7

**Comment by ateixeirag** [comment]
I guess the error was related with a bad configuration in the custom derp server. I fix the JSON in https://login.tailscale.com/admin/acls and then it works OK.
Regards.

C:\Users\aleja>tailscale netcheck

Report:
        * UDP: true
        * IPv4: yes, 45.238.177.116:51469
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping:
        * Nearest DERP:
        * DERP latency:
                - 901: 11.2ms  ()
                - 902: 15.6ms  ()

**Comment by DentonGentry** [comment]
The crash appears to be because `report.PreferredDERP` is nil.

The tailnet has two custom DERPs, neither of which appears to work, and has removed all of the default DERP regions. Could I ask why you removed all of the normal DERPs?

**Comment by ateixeirag** [comment]
The default DERPs in Tailscale have a very high latency of 300ms round-trip time between hosts on the network. This is particularly noticeable in Chile.

**Comment by peter17ji** [comment]
This bug resurfaces in latest 1.76.0 release for ARM devices. Pls check.
OS: Asuswrt Merlin 388.8 on Asus RT-AX68U

```
peter22ji@RT-AX68U-BA50:/tmp/home/root# uname -a
Linux RT-AX68U-BA50 4.1.52 #2 SMP PREEMPT Fri Oct 4 15:01:08 CST 2024 aarch64 ASUSWRT-Merlin-KoolShare
peter22ji@RT-AX68U-BA50:/tmp/home/root# tailscale netcheck
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x542f4c]

goroutine 1 [running]:
tailscale.com/net/netcheck.(*Client).GetReport(0x147fd40, {0x7f6f60, 0xb6ae98}, 0x140cea0, 0x0)
        tailscale.com@v1.76.0/net/netcheck/netcheck.go:943 +0xef8
tailscale.com/cmd/tailscale/cli.runNetcheck({0x7f6f60, 0xb6ae98}, {0x1430690, 0x0, 0x0})
        tailscale.com@v1.76.0/cmd/tailscale/cli/netcheck.go:99 +0x590
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xb58810, {0x7f6f60, 0xb6ae98})
        github.com/peterbourgon/ff/v3@v3.4.0/ffcli/command.go:153 +0x168
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0x147f920, {0x7f6f60, 0xb6ae98})
        github.com/peterbourgon/ff/v3@v3.4.0/ffcli/command.go:157 +0x10c
tailscale.com/cmd/tailscale/cli.Run({0x1484028, 0x1, 0x1})
        tailscale.com@v1.76.0/cmd/tailscale/cli/cli.go:151 +0x46c
main.main()
        tailscale.com@v1.76.0/cmd/tailscale/tailscale.go:22 +0x104
peter22ji@RT-AX68U-BA50:/tmp/home/root# which tailscale
/koolshare/bin/tailscale
peter22ji@RT-AX68U-BA50:/tmp/home/root# tailscale version
1.76.0
  tailscale commit: 6d996464ad4ce520b165c0fd3a1213876e55df5a
  other commit: d75b8cb4b03020da974de7154d6e668a36349078
  go version: go1.23.1
```
