### ISSUE TITLE
FR: Unraid: Detection and Taildrop Behavior

### ISSUE THREAD

**Issue by dkaser** [tailscale/tailscale#8025]
### What are you trying to do?

Tailscale should use the "NAS behavior" when running on Unraid, placing files into a designated folder instead of being held for pickup with the tailscale CLI.

### How should we solve this?

- Add ability for Tailscale to detect Unraid as a platform (/etc/unraid-version)
- Add configuration option to select Taildrop destination when running on Unraid
- Disable Taildrop on Unraid if a valid destination is not set.

### What is the impact of not solving this?

The community Unraid plugin currently has to "simulate" being a QNAP NAS in order for Taildrop to use the NAS-style functionality (i.e., placing taildropped files directly into a folder on the device). This limits further development of the plugin, however. since other QNAP-specific behavior does not work properly with Unraid (e.g., `tailscale web` cannot be used since it invokes QNAP authentication). 

### Anything else?

The community plugin is located at https://github.com/dkaser/unraid-tailscale

Adding detection of Unraid to Tailscale will permit further integration between Tailscale and the Unraid web UI. Once Unraid can be detected, additional FRs/PRs can be created for functionality that cannot currently be implemented within the plugin.

**Comment by bradfitz** [comment]
@dkaser, sounds good to me. Especially since you're running it natively now (https://github.com/tailscale/tailscale/issues/4624#issuecomment-1532126994) and not in a container, right?

**Comment by dkaser** [comment]
Yes, the plugin runs natively.

And to add some context: disabling Taildrop is specific behavior needed for Unraid because of how it runs from memory. If a user doesn't specify a location for Taildrop files, they would have to accumulate on either the flash drive used to boot the system or on the in-memory filesystem (so filling up either one is bad). Currently, the plugin uses TS_DISABLE_TAILDROP to prevent that from happening, but that's also an undocumented variable.

**Comment by DentonGentry** [comment]
Could you post a sample `/etc/unraid-version` file, redacted if necessary?

**Comment by dkaser** [comment]
[unraid-version.txt](https://github.com/tailscale/tailscale/files/11378001/unraid-version.txt)

(.txt added to make GitHub happy)

**Comment by bradfitz** [comment]
@dkaser, do you plan to send the change?
