### ISSUE TITLE
Tailscale Windows Service Won't Start (on corp-managed laptop)

### ISSUE THREAD

**Issue by MrBuddyCasino** [tailscale/tailscale#803]
I just installed Tailscale, but the service won't start. Running in an elevated command prompt:

```
>"C:\Program Files (x86)\Tailscale IPN\tailscale-ipn.exe" /runservice

>logtail started
Program starting: v1.0.4-ge256174d6, Go 1.14.4-ts56db765: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe", "/runservice"}
LogID: 34f1ca1f3eee2ed3705e4e0e395f57396b703d221a54cb2784dcf12711d51ca0
logpolicy: using UserCacheDir, "C:\\Users\\user\\AppData\\Local\\Tailscale"
stdout ok.
stderr ok.
printf ok.
log ok.
Running service...
runservice: The service process could not connect to the service controller.
flushing log.
logger closing down
logtail: upload: log upload of 1445 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/48e42bb84f625faff13963109a1c7fb641424ba5098011953a4c41766e05cb47": context canceled
```
Running Windows 10 1909

**Comment by bradfitz** [comment]
Hm, "The service process could not connect to the service controller" is an error we haven't seen before.

Is there something unique about your machine that's enforcing different sets of security policies than normal? Is this a work laptop with various corporate management software on it?

In any case, try the unstable branch which has 2 months of Windows fixes since 1.0.4: https://pkgs.tailscale.com/unstable/#windows

But I don't recall fixing anything in this area.

/cc @alexbrainman

**Comment by MrBuddyCasino** [comment]
> Is this a work laptop with various corporate management software on it?

That is indeed the case.

> In any case, try the unstable branch which has 2 months of Windows fixes

Will do, thanks.

**Comment by bradfitz** [comment]
> That is indeed the case.

Sadly you might just be getting blocked from running any non-corp-approved software from your company's allowlist of services that can run.

**Comment by alexbrainman** [comment]
> Hm, "The service process could not connect to the service controller" is an error we haven't seen before.

I can reproduce it here

```
C:\Users\Alex>"C:\Program Files (x86)\Tailscale IPN\tailscale-ipn.exe" /runservice

C:\Users\Alex>logtail started
Program starting: v1.1.441-gd81532327, Go 1.15-tsc099eea: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscale-ipn.exe", "/runservice"}
LogID: f1c51c720381f4a4138b878af22a47ef0febb925b50412dce2b57c42c5aaa514
logpolicy: using UserCacheDir, "C:\\Users\\Alex\\AppData\\Local\\Tailscale"
stdout ok.
stderr ok.
log ok.
Running service...
runservice: The service process could not connect to the service controller.
flushing log.
logger closing down
tshttpproxy: winhttp: GetProxyForURL("https://log.tailscale.io/c/tailnode.log.tailscale.io/b082eb54b6d6ba60ca830beb5bde33ad132e75bf2fdbb7eeaa79b80752f24542"): timeout; using cached proxy <nil>
logtail: upload: log upload of 99 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/b082eb54b6d6ba60ca830beb5bde33ad132e75bf2fdbb7eeaa79b80752f24542": context canceled


C:\Users\Alex>
```

@MrBuddyCasino you cannot use `/runservice` `tailscale-ipn.exe` parameter in command prompt. The parameter is intended to only be used in a Windows service.

Please try latest version from

https://pkgs.tailscale.com/unstable/#windows

as @bradfitz suggested, and report the problem you see.

I assume you run the installer, and you expected tailscale service to be running, like this

![image](https://user-images.githubusercontent.com/9796621/94977674-27a2a500-055d-11eb-8818-f657bbb3c2c1.png)

and it is not running. Correct?

If so, please, see log files in

`C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs\`

directory. Perhaps it will give us some clues.

Thank you.

Alex

**Comment by DentonGentry** [comment]
Hopefully https://github.com/tailscale/tailscale/issues/803#issuecomment-703004081 resolved it, please reopen if not.

**Comment by Oujiii** [comment]
Similar issue here, found this and decided not to open a new one. I'm on a corp managed computer as well and facing the error "Please restart the Tailscale Windows Service.", but on my end it was working a few hours ago.
 I decided to update from 2004 to 21H1 and after the reboot, I started facing this issue. 
Already tried rebooting the service, tried reinstalling the client, also installed the unstable build and the problem continues.
My Tailscale service shows as running, not sure what else I can do to troubleshoot.

**Comment by DentonGentry** [comment]
This issue was resolved 7 months ago, and though you're seeing some similar symptoms it is almost certainly a different problem. I split it out into a new issue in https://github.com/tailscale/tailscale/issues/2031
