### ISSUE TITLE
All exit node disabled on macOS client GUI

### ISSUE THREAD

**Issue by morpig** [tailscale/tailscale#8030]
### What is the issue?

This issue started after upgrading to 1.40 from 1.3x

Exit nodes are all disabled/darked out, clicking on it (well, it doesn't work.)

<img width="605" alt="Screenshot 2023-05-03 at 22 25 57" src="https://user-images.githubusercontent.com/4915643/235964183-44d27be6-b8f3-4ebb-b235-6fff053a6177.png">

### Steps to reproduce

- Upgrade from 1.3x to 1.40
- Have exit nodes enabled on admin UI
- Open client GUI and check exit nodes

### Are there any recent changes that introduced the issue?

Upgrade to 1.40

### OS

macOS

### OS version

13.3.1

### Tailscale version

1.40

### Bug report

BUG-a91f0735315f00bce148c5bb0050d060a01b8d4b9e4bf8374a1560ae9f6e5ab8-20230503153054Z-913cd8f2aa95a195

**Comment by DentonGentry** [comment]
Around the time of the bugreport we see it reporting the various exit nodes, but no indication of why they are considered disabled.
`2023-05-03 15:26:17.57922 +0000 UTC: wgcfg: skipped unselected default routes from: "REDACTED" ([ZEhU2]), "REDACTED" ([Q2Xif]), "REDACTED" ([msE0Z]), "REDACTED" ([U2KaL]), "REDACTED" ([xphuy]), "REDACTED" ([gIgIf]), "REDACTED" ([sG2Sv]), "REDACTED" ([aRWhf])`

**Comment by bradfitz** [comment]
@DentonGentry, "skipped unselected default routes from" means those are the other exit nodes that aren't currently selected:

```go
		for _, allowedIP := range peer.AllowedIPs {
			if allowedIP.Bits() == 0 && peer.StableID != exitNode {
```

Looks like the node is an exit node itself. I think this is just bad UI not explaining that you can't be both an exit node and use an exit node.

**Comment by morpig** [comment]
> Looks like the node is an exit node itself. I think this is just bad UI not explaining that you can't be both an exit node and use an exit node.

Just checked and apparently yes. Is this a behavior change in 1.4x or it's been like this before? 

https://user-images.githubusercontent.com/4915643/236378748-aa4c8006-0a15-49ad-b314-2f68b11a6deb.mov

**Comment by bradfitz** [comment]
It's never officially been supported and used to kinda work in broken ways on some OSes but it was never intentional or tested.

A few releases back we started making the CLI and GUI warn you away from it a bit.

**Comment by DentonGentry** [comment]
I think this is working as intended: one cannot simultaneously be an exit node and use an exit node.

Prior releases might have allowed this combination of settings but it never worked well and resulted in a neverending series of bugs and support tickets. Current releases decline to do so.
