### ISSUE TITLE
cmd/tailscale: `configure kubeconfig` assigns non deterministic user when using tokens

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#8032]
### What is the issue?

Locally, `tailscale configure kubeconfig tailscale-operator` will create a kubeconfig associated with the tailscale user. In my case this is `thomas@example.com`. However the username is instead associated with the hostname when using reusable, ephemeral tokens (e.g `github-fv-az551-62.tailnet-fbec.ts.net`).

See [this GitHub workflow](https://github.com/uhthomas/automata/blob/4a6b23e26e25d5dac8ca2df24003966e16dd25b6/.github/workflows/k8s.yaml#L11-L17) for an example of usage.

So, this means that is impossible to assign users in Kubernetes without a static hostname.

```sh
Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io "clusterissuers.cert-manager.io" is forbidden: User "github-fv-az551-62.tailnet-fbec.ts.net" cannot patch resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

However, even _with_ a static hostname this is still a problem as duplicate hosts will be suffixed with a number (e.g `-1`).

```sh
Error from server (Forbidden): customresourcedefinitions.apiextensions.k8s.io "clusterissuers.cert-manager.io" is forbidden: User "github-automata-unwind-k8s-apply-1.tailnet-fbec.ts.net" cannot patch resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

I don't have a proposed solution unfortunately. Maybe a concept of Tailscale Service Accounts would be applicable? Maybe the behaviour here is actually incorrect and should be associated with Tailscale users instead of hostnames.

### Steps to reproduce

1. Create a reusable, ephemeral auth key.
2. Create a GitHub workflow which logs into tailscale and Kubernetes ([example](https://github.com/uhthomas/automata/blob/4a6b23e26e25d5dac8ca2df24003966e16dd25b6/.github/workflows/k8s.yaml#L11-L17)).
3. Run the workflow a couple of times.
4. Observe the username is not the same as what it would be with a local tailscale instance (not `user@example.com`). Observe the username is either random, or with a static hostname suffixed with a number (e.g `-1`).

### OS

Linux, Other

### Tailscale version

0.140.0

**Comment by maisem** [comment]
It looks like you are connecting from a tagged device. If so, the tagged device is not going to have your identity associated with it and instead would expectedly show up as the node itself.

**Comment by uhthomas** [comment]
I see - so the problem is the token assigns a tag and this therefore causes the change in behaviour where the username is instead associated with the hostname of the node. I think that makes sense, thanks. Though, this was unexpected. Is there a better way to communicate this?

Additionally, is there a way to create a node with a label which is still associated with a user? I found the `ci` tag to be helpful to filter them out when needed.

Lastly, is there any sort of concept of service accounts within Tailscale, and is there appetite for this? I can think of a few situations where an account which isn't associated with my user would be beneficial.

**Comment by maisem** [comment]
> Lastly, is there any sort of concept of service accounts within Tailscale, and is there appetite for this? I can think of a few situations where an account which isn't associated with my user would be beneficial.

[ACL Tags](https://tailscale.com/kb/1068/acl-tags/) are meant to be the service account equivalent for Tailscale

>Additionally, is there a way to create a node with a label which is still associated with a user? I found the ci tag to be helpful to filter them out when needed.

Not at the moment, however for your use case I would recommend you leave the CI machines tagged with `tag:ci` and then create [RBAC rules](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-binding-examples) for `tag:ci`. 

something like
```
subjects:
- kind: Group
  name: "tag:ci"
  apiGroup: rbac.authorization.k8s.io
```

**Comment by uhthomas** [comment]
Ah, I see. This makes sense. I didn't know it was possible to specify Tailscale tags as RBAC subjects. Is this documented anywhere?

**Comment by uhthomas** [comment]
Seemed to work exactly as expected, thank you. I guess I'll close this.

https://github.com/uhthomas/automata/commit/f8a4b649c2bc7a1315adae7a4ffe9ef7ca4a68c5

**Comment by uhthomas** [comment]
@maisem Let me know if you'd like to reopen this as a documentation issue? I'm sure there are some articles which could use this knowledge.

**Comment by maisem** [comment]
I've filed a docs issue, thanks!
