### ISSUE TITLE
FR: Provide macOS Network Extension .mobileconfig

### ISSUE THREAD

**Issue by chedge** [tailscale/tailscale#8033]
### What are you trying to do?

When installing Tailscale on macOS via App Store or VPP/MDM deployment, it prompts the user to allow Tailscale to add a VPN configuration. I'd like to have this pre-enabled by means of a Configuration Profile so the prompt doesn't appear to the user.

Palo Alto provides similar for their GlobalProtect software: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u000000HAW8 (specifically the bit about Network Extensions)

### How should we solve this?

It would be great to be able to have this profile available for smoother deployments to client systems on macOS.

### What is the impact of not solving this?

It's mostly just an inconvenience, but when deploying this out to many users at once, these prompts tend to cause confusion.

**Comment by hazcod** [comment]
This is documented here: https://tailscale.com/kb/1286/macos-mdm/

**Comment by agottardo** [comment]
@chedge hi! can you please check the link posted above and let us know if we can close this? We also announced [several improvements](https://tailscale.com/kb/1315/mdm-keys/) for configuration profile users.
