### ISSUE TITLE
failed to connect tailscale service on windows 10

### ISSUE THREAD

**Issue by zhy2634153** [tailscale/tailscale#8045]
### What is the issue?

I have got the following error when I click "Login" on tailscale GUI on Windows 10  21H2 :

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.
Version 1.40.0 (t105be684d-g4c70014a4)
LogID: 9e77eeb0b4285ccc81d06f47b7500688258b26759158c2057a2492b80a794b39
(Ctrl-C to copy this text)
---------------------------
确定   
---------------------------

Please help to fix it.
Thanks very much!

### OS

Windows

### OS version

21H2

### Tailscale version

1.40.0

**Comment by zhy2634153** [comment]
I ensure the tailscale service is running, when the error occured.

**Comment by bradfitz** [comment]
Dup of #7889 at least as far as UI confusion goes.

**Comment by zhy2634153** [comment]
Thank you very much!
