### ISSUE TITLE
Make DNS lookups (for HTTP dials) use netns

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#805]
From another issue, it seems we're not using net/netns for HTTP Transport DNS lookups.

/cc @danderson @crawshaw @josharian

**Comment by josharian** [comment]
Went to go fix this, but I'm not entirely sure what you're referring to. Which HTTP Transport?

**Comment by bradfitz** [comment]
> Went to go fix this, but I'm not entirely sure what you're referring to. Which HTTP Transport?

log.tailscale.io (`logpolicy`'s `newLogtailTransport`)
login.tailscale.com (`control/controlclient`)

Also connecting to an HTTP proxy as determined by PAC/WPAD. (In that case, local DNS in a corp network might be the only DNS server able to return the corp HTTP proxy's IP)

We just had a customer report that, on Windows with subnets shadowing the DNS server, we can get into a situation where nothing works. I haven't looked at logs, but from what I've heard, I suspect we're getting into a situation where we've configured Windows' DNS + routes, but then login.tailscale.com can't be reached in a subsequent HTTP request because it does a DNS lookup which then needs to use Tailscale. (DERP, though, doesn't need DNS, so not sure why the connection to the subnet router hosting the DNS doesn't work)

In addition to using netns for DNS lookups, we should also be caching those two names' IPs in case future lookups time out. (as previously discussed elsewhere)

I need to actually look at the customer logs and see what's happening, though.

**Comment by danderson** [comment]
I believe this is fixed now. We have a bootstrap DNS resolver to bring Tailscale itself up, and we correctly do _not_ use netns sockets for the tailscale-configured DNS resolver (since it may need to forward to a Tailscale peer).
