### ISSUE TITLE
ipn/ipnlocal: cert fetching sometimes hangs+fails on macsys

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#8067]
@marwan-at-work reports that LetsEncrypt cert fetching sometimes hangs+fails on macsys and debugged it down to LookupTXT hanging.

Marwan can elaborate.

Tracking bug.

**Comment by bradfitz** [comment]
To @marwan-at-work to verify the fix. We'll need an unstable build first, or you'll need to build the mac client yourself.

**Comment by marwan-at-work** [comment]
I can confirm it works (I deleted the certs to verify a few times).

However, a couple of times I got: 

```
cert("marwan-tsmac.corp.ts.net"): getCertPEM: SetDNS "_acme-challenge.marwan-tsmac.corp.ts.net" => "xxx-xxx": read tcp [2603:7000:2103:2d11:d171:dd23:19a3:80f2]:57904->[2a05:d014:386:202:24dd:46aa:f98e:9997]:80: read: connection reset by peer
```

**Comment by bradfitz** [comment]
We'll call it good then. :) 

If we see that more we can open a new bug.
