### ISSUE TITLE
On macOS/iOS, the "Get Status" shortcut action only returns text "Tailscale Status"

### ISSUE THREAD

**Issue by kylefmohr** [tailscale/tailscale#8075]
### What is the issue?

I first noticed this on iOS, regardless of whether or not I was connected to my tailnet, the shortcut from the Tailscale app called "Get Status" only ever returns a string that says "Tailscale Status". This behavior is identical on macOS - this screenshot shows the issue, side-by-side with the properly working "tailscale status" command line option. 

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/6644803/236609404-113ac921-4de3-44d6-8966-8671ac1a3a58.png">

### Steps to reproduce

Use the "Get status" action in the Shortcuts app on macOS or iOS

### OS

macOS, iOS

### OS version

macOS 13.3.1 (a), iOS 16.4.1 (a)

### Tailscale version

1.39.0

### Bug report

BUG-cb4faaf1e961ff6500cda4f0a55ea531bfd47475c0b6444aa0d2d7c04acad62c-20230506072000Z-af9f7b8ffdacf36a

**Comment by chrisbrownie** [comment]
I’m seeing the same behaviour on iOS. My use case is to check if I am connected to my Tailnet, and only connect if I’m not already when the shortcut runs, as well as to save that status for later so I know whether to disconnect or not at the termination of the shortcut.

**Comment by relink2013** [comment]
First time ever trying to make a shortcut for Tailscale and I thought it was something I was doing wrong. Needless to say I’m having the same issue.

**Comment by chrisbrownie** [comment]
Okay I kinda got there. I blame Shortcuts (probably) for not making this obvious. `Connected` is emitted as a property as expected, it’s just hard to consume. Easiest way I’ve found is to set a variable off the back of this. See here:

![IMG_3671](https://github.com/tailscale/tailscale/assets/5036744/ec83f027-cdec-4e21-8197-ca92d46997cc)

**Comment by kylefmohr** [comment]
> Okay I kinda got there. I blame Shortcuts (probably) for not making this obvious. `Connected` is emitted as a property as expected, it’s just hard to consume. Easiest way I’ve found is to set a variable off the back of this. See here:
> 
> 
> 
> ![IMG_3671](https://github.com/tailscale/tailscale/assets/5036744/ec83f027-cdec-4e21-8197-ca92d46997cc)
> 
> 

Oh hey, nice find! Can confirm this is working for me too. But yeah, definitely an odd way to consume that data. I'll close this since it's not actually an issue, somebody can open a feature request if they wish. 

Thanks again Chris!

**Comment by kylefmohr** [comment]
Very cool that this works now. My Home Assistant server is only accessible via Tailscale, and now it'll auto connect when I launch the Home Assistant app. Very useful. ![image](https://github.com/tailscale/tailscale/assets/6644803/be5913c0-6716-4882-804b-4cdb8625f9a4)
![image](https://github.com/tailscale/tailscale/assets/6644803/f59138c0-056b-4961-a50a-8186a783a3fe)
