### ISSUE TITLE
2023/05/06 16:51:48 http: TLS handshake error from xxxxxxxxx:17431: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by IT-dragon** [tailscale/tailscale#8076]
### What is the issue?

There is a problem when tailscale uses custom derper: bad certificate
![image](https://user-images.githubusercontent.com/49020985/236614594-aee3db52-5c87-4c43-883e-85bca0adde99.png)

However, I can access the certificate normally from the browser
![image](https://user-images.githubusercontent.com/49020985/236614120-165f62a9-db6a-4dff-83bb-070c450ac9f6.png)

note:more info
certificate info:
![image](https://user-images.githubusercontent.com/49020985/236614363-2602671d-c9f6-4538-965c-d7d3194131d5.png)
tailscale error info:
![image](https://user-images.githubusercontent.com/49020985/236614503-cbda33cf-f7c0-4b33-883e-b42893d339aa.png)

### OS

Linux

### OS version

CentOS7

### Tailscale version

1.40.0

**Comment by IT-dragon** [comment]
It is normal when I use the windows client of taiscale in the same network environment (in the same local area network) And the derp server does not generate any errors
![image](https://user-images.githubusercontent.com/49020985/236614893-55124e09-a0eb-4c53-8d7f-814be5f7cca7.png)

**Comment by DentonGentry** [comment]
> It is normal when I use the windows client of taiscale in the same network environment (in the same local area network) And the derp server does not generate any errors

As we said in https://github.com/tailscale/tailscale/issues/7961, which you also filed: it looks like there is something in front of the derp interfering with its connections. That might be a firewall, or a load balancer, or something. We won't be able to see that from here, it is something you will need to figure out.

That you see different behavior on the LAN next to the DERP from what is seen remotely is also consistent with something being between the DERP and the Internet.

**Comment by IT-dragon** [comment]
thank you. I have solved this problem.It was because of something wrong with my ssl certificate configuration. Here I give the link of my reference to solve this problem(https://forum.tailscale.com/t/ipados-unable-to-connect-to-custom-derp-tls-bad-certificate/1107/7 ), hoping to give some help to people who also encounter this problem. In addition, it is worth noting that the error message of tailscale is too vague.

**Comment by IT-dragon** [comment]
you can close this bug.
