### ISSUE TITLE
Tailscale 1.40.0 for MacOS refuses to load on High Sierra

### ISSUE THREAD

**Issue by frakman1** [tailscale/tailscale#8079]
### What is the issue?

The standalone Mac Application linked from Documentation page:

![image](https://user-images.githubusercontent.com/5826484/236632731-3f81ff26-0317-458c-87ec-a6e05aa493f9.png)

Which points to this:
![image](https://user-images.githubusercontent.com/5826484/236632752-57138702-68c6-4441-abd2-0652ae1bd084.png)

https://pkgs.tailscale.com/stable/Tailscale-1.40.0-macos.zip

When unzipped and moved to /Applications, refuses to run:

![image](https://user-images.githubusercontent.com/5826484/236632692-b2c85b1b-8aef-4687-a8a0-9679d947f3bb.png)

### Steps to reproduce

See above.
I moved the application bundle and 'copied over' the existing one in /Applications

### Are there any recent changes that introduced the issue?

I wanted to upgrade from my old 1.22 version.

### OS

macOS

### Tailscale version

10.13.6 High Sierra

**Comment by frakman1** [comment]
The workaround was to install it from the App Store.

At first, it wasn't working and the 'Update' button would keep re-appearing, but then I found a Github issue saying to quit Tailscale first, then update. That worked for me.

**Comment by DentonGentry** [comment]
The downloadable macOS application uses a System Extension, which is a macOS feature that Apple added in macOS 10.15.

The App Store version of the app uses a Network Extension, the same interface as is used by the iOS app. Network Extensions have been around longer, supporting back to macOS 10.13 (maybe earlier).

The table in https://tailscale.com/kb/1065/macos-variants/ shows this, the App Store and tailscaled-on-macOS versions can support back to 10.13, the Standalone version supports macOS 10.15 and later.

**Comment by frakman1** [comment]
Thank you for the detailed explanation. I guess I should have continued reading the Documentation page :)
I thought there was just one GUI installation file and when I saw that the App Store supported 10.13, and when it didn't work, I set out searching for the installation file to use manually and came across the Standalone version.

Is there any chance you can also provide the App Store installation file for cases where the App Store can not be accessed or is failing to install for whatever reason? Not all Mac users want to have their Apple ID/iCloud account enabled.

**Comment by DentonGentry** [comment]
> Is there any chance you can also provide the App Store installation file

System Extensions and Network Extensions grant extra privileges to the application in configuring routes and DNS and networking. Apple also imposes some requirements on them, such as that they must run within a sandbox with limited access to the rest of the system.

Apple also requires:
- System Extension apps must be signed
- Network Extension apps must be signed _by Apple_

We can't distribute the Network Extension version of the app outside of the App Store. macOS will only run a Network Extension if it was signed by Apple as part of installing it from the App Store.
