### ISSUE TITLE
How to use exit node on iphone?

### ISSUE THREAD

**Issue by Fantasy9619** [tailscale/tailscale#8089]
### What is the issue?

How to use exit node on iphone?

### OS

iOS

### OS version

16.1.0

**Comment by DentonGentry** [comment]
Click the three dots to open the menu:
![IMG_0096](https://user-images.githubusercontent.com/1140756/236736203-6f57e983-3ab3-4332-bc68-841e708e9685.PNG)

--------

Then select Use exit node:
![IMG_0097](https://user-images.githubusercontent.com/1140756/236736216-10e276cb-74b3-4718-95cc-f67ba85c1621.PNG)

**Comment by Fantasy9619** [comment]
![IMG_7910](https://user-images.githubusercontent.com/127948967/236769208-2fbc5cae-da9e-4d2b-a459-0e4460504138.PNG)
Why my iPhone does not have the option?
tailscale version is already 1.40.0
![IMG_7911](https://user-images.githubusercontent.com/127948967/236769706-9d0f9c97-82b5-4ac6-ac14-7aaf5414e186.PNG)

**Comment by bradfitz** [comment]
You have to run an exit node. We don't provide them. Are you running one?

**Comment by Fantasy9619** [comment]
> You have to run an exit node. We don't provide them. Are you running one?

why Denton Gentry's phone has the button？ I want my PC can share my iPhone's VPN when connect iPhone'hotspot。

**Comment by Fantasy9619** [comment]
> > why Denton Gentry's phone has the button？
> 
> 
> 
> I have a node on my tailnet, which I set up, and which is configured to be an exit node.
> 
> https://tailscale.com/kb/1103/exit-nodes/
> 
> 
> 
> Tailscale does not provide the exit node, you have to set one up for your own tailnet.
> 
> 
> 
> > I want my PC can share my iPhone's VPN when connect iPhone' hotspot。
> 
> 
> 
> An iPhone isn't going to be able to do that: the iOS Tailscale app does not yet support operating as an exit node. Additionally, most phones handle tethered traffic in a way which would not send the traffic through the VPN.

thank you
