### ISSUE TITLE
Please clarify whether reported netcheck latency is one-way or a round-trip time

### ISSUE THREAD

**Issue by ruuda** [tailscale/tailscale#8093]
### What is the issue?

* `tailscale netcheck` outputs a “DERP latency” in milliseconds, but it is unclear whether “latency” is the time it takes for a packet to travel one way, or a round-trip time.
* This number is also displayed in the admin panel without clarification.
* https://tailscale.com/kb/1080/cli/?q=netcheck#netcheck also does not document what “latency” means.
* For `tailscale ping`, it says “pong received in ...ms”, so that is a round-trip time. (Consistent with the classic iputils `ping`, which also reports rtt.)
* From what I can tell, it is slightly more common to use “latency” to refer to one-way time, and “round-trip time” for two-way. In general you can only observe the round-trip-time, as the one-way time may be asymmetric.
* But the numbers I get from `tailscale ping`ing some servers are very close to the latency numbers I get for nearby DERP servers, which suggests that the “DERP latency” is a round-trip time.

### Steps to reproduce

* Run `tailscale netcheck`.
* Read https://tailscale.com/kb/1080/cli/?q=netcheck#netcheck.

### Are there any recent changes that introduced the issue?

Not as far as I am aware.

### OS

Linux

### Tailscale version

1.40.0

### Bug report

BUG-ab7c9b77330a7251d3b9c6d470d6b83910b41487718f3e1f3121523b651b4816-20230508130018Z-5454edc5d22e7c78

**Comment by DentonGentry** [comment]
It is a round trip time. We don't have globally synchronized clocks or sufficient precision to determine one-way transit time.

**Comment by ruuda** [comment]
Yeah I suspected as much, thanks for the clarification. It might make sense to add something like “(rtt)” to the output to clarify.
