### ISSUE TITLE
Admin Console link from the System Tray icon in Windows missing

### ISSUE THREAD

**Issue by ericreiss** [tailscale/tailscale#8094]
### What is the issue?

I recently upgraded from 1.38 to 1.40 and I thought there was a link in the System Tray icon in Windows to launch the Admin Console.  Now I cannot find it.  There are not that many items when you right click on the Tailscale icon.

Was this ability removed with the update?

### Are there any recent changes that introduced the issue?

upgraded from 1.38 to 1.40.

### OS

Windows

### OS version

10

### Tailscale version

1.40.0

**Comment by bradfitz** [comment]
Are you logged in as an admin?

**Comment by ericreiss** [comment]
I am the only user.  I am the Owner and believe I should be the Admin.

**Comment by ericreiss** [comment]
I think I now see what happened.  I had been looking into running unattended and using an ACL Tag.  I created the TAG with a name for the windows machine.  Under the Disconnect menu option, it had been showing the machine name rather than my email account.  I had created the tag a few days ago and decided after noticing the Admin Console link missing, that something I did may have changed it, not jkust the upgrade from 1.38 to 1.40.  I removed the ACL tag and disconnected and even quit the program and restarted.  Just now I "Logged out" and when I logged back in so that it shows my email below the "Disconnect" menu item, I now see the Admin Console link when I expand the menu tree for my email account.  So apparently you can't have both.

**Comment by DentonGentry** [comment]
When a machine is Tagged, it becomes owned by the Tag and not the User who created it.
https://tailscale.com/kb/1068/acl-tags/
