### ISSUE TITLE
FR: Support for BlendOS

### ISSUE THREAD

**Issue by deandre** [tailscale/tailscale#8100]
### What are you trying to do?

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux blend 6.3.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000 x86_64 GNU/Linux

NAME="blendOS"
PRETTY_NAME="blendOS"
ID=blendos
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://blendos.co/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL=""
BUG_REPORT_URL=""
LOGO=blendos-logo
IMAGE_ID=blendOS
IMAGE_VERSION=2023.05.01

**Comment by fr3nchalp4a** [comment]
What is this OS 😂 I think I will try it
(and if I stick to it I will need Tailscale so +1 for this feature)

**Comment by DentonGentry** [comment]
I imagine we'd handle blendos like Arch and choose the pacman package.

However I've tried several times to install `blendOS-2023.04.22-x86_64-gnome.iso` as a VM in Proxmox and the installation hangs at 9% or 16% each time. We need a way to test the installer support.

**Comment by DentonGentry** [comment]
I cannot get a BlendOS VM working. If someone with a BlendOS system would like to try it:
`curl -fsSL https://raw.githubusercontent.com/tailscale/tailscale/installer/scripts/installer.sh | sh`

Please let us know if it works.

**Comment by DentonGentry** [comment]
Optimistically sent https://github.com/tailscale/tailscale/pull/8265
