### ISSUE TITLE
admin: make it easier to reorder DNS servers

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#812]
User bug report about https://login.tailscale.com/admin/dns :

> The only way to insert a new dns server at the head of the list is to delete and re add all the other servers. It would be much nicer if these could be dragged & dropped into place. 

![image (4)](https://user-images.githubusercontent.com/2621/95532721-0fd08400-0996-11eb-837d-692a0db54850.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2c2mp)

**Comment by rosszurowski** [comment]
For anyone following, it's now possible to reorder DNS servers via drag-and-drop on the new DNS panel UI: [login.tailscale.com/admin/dns](https://login.tailscale.com/admin/dns).
