### ISSUE TITLE
[Docs] Tailscale K8s docs are out of date for `make push`

### ISSUE THREAD

**Issue by lukehsiao** [tailscale/tailscale#8127]
### What is the issue?

The tailscale kubernetes docs: https://tailscale.com/kb/1185/kubernetes/ mention to use `make push` during the setup.

However, there is to `push` target in the Makefile: https://github.com/tailscale/tailscale/blob/main/docs/k8s/Makefile

Resulting in

```
❯ make push
make: *** No rule to make target 'push'.  Stop.
```

### Steps to reproduce

```
gh repo clone tailscale/tailscale
cd tailscale/docs/k8s
make push
```

### Are there any recent changes that introduced the issue?

The `push` target was removed in commit 3b55bf93062c ("build_docker.sh: add run.sh as an entrypoint to the docker image")

### OS version

N/A

### Tailscale version

N/A

### Bug report

N/A

**Comment by DentonGentry** [comment]
I'd expect to remove those steps when we add the k8s Operator documentation to it.
