### ISSUE TITLE
MagicDNS on linux in some configurations can break DNS on forced reboot

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#813]
On a system using MagicDNS in "replace /etc/resolv.conf" mode, `tailscaled --cleanup` has to run to put resolv.conf back the way it was. We run this as a systemd post-stop action, which means DNS gets fixed up on normal tailscaled shutdown and normal system shutdown/reboot.

However, if you hard powercycle a machine while MagicDNS is configured, the machine will boot with a /etc/resolv.conf pointing to 100.100.100.100, whereas tailscaled isn't up and configured yet. This will cause all DNS resolution on the machine to fail, including tailscaled itself trying to connect to login.tailscale.com to get its configuration (which would fix DNS).

Restarting tailscaled fixes this, since doing so runs --cleanup.

We should probably run --cleanup as a pre-start action as well as post-stop, to deal with this case. /cc @bradfitz

**Comment by bradfitz** [comment]
This breaks me every time I use my laptop (which I invariably forget to charge, so it's always booting fresh)

**Comment by danderson** [comment]
Also backported to release-branch/1.2, for the next release.
