### ISSUE TITLE
The account registered from 88.com email cannot be the administrator after login

### ISSUE THREAD

**Issue by Capre-git** [tailscale/tailscale#8137]
### What is the issue?

The email address from 88.com seems to have been registered by someone for an organization, which means I cannot manage my node in Tailscale, and several strange devices show up in the device list. However, 88.com is built for personal email service.

When I try to enter the admin console, I receive the following error message:
'You don’t have access to the admin console. Your account is not an administrator for the 88.com network. You can access this network using the Tailscale app, but you’re not allowed to manage network settings.

### Steps to reproduce

Just login to Tailscale by using any email from 88.com

### Are there any recent changes that introduced the issue?

None

### OS version

Windows 11

### Tailscale version

1.40.0

### Other software

None

### Bug report

None

**Comment by DentonGentry** [comment]
Indeed, it had been misclassified as a corporate domain when it is definitely a service provider. We've corrected that now.

**Comment by xXBubbamannXx** [comment]
I think I have exactly the same problem with "ewe.net" Mail Accounts. I set up a Tailscale account and I get the same Error message. @DentonGentry I think the ewe.net Mails have also been classified as a corporate domain, but its nomally used by private customers from the EWE ISP, as far as i know. In comparison the old "ewetel.net" Mail Accounts work perfectly fine for Tailscale.
