### ISSUE TITLE
Win10 GUI Client not visible

### ISSUE THREAD

**Issue by SeriousM** [tailscale/tailscale#8138]
### What is the issue?

No window shows up when opening the Tailscale GUI App. Interestingly the login flow after setup started flawlessly and my device is connected. Also the automatic service start after reboot works well.

### Steps to reproduce

Open the app, wait, no window is visible.
When running the `tailscale-ipn.exe` in the console I see this:

```log
.\tailscale-ipn.exe
PS C:\Program Files\Tailscale> logtail started
Program starting: v1.40.1-t3589beb7b-gc88a4b678, Go 1.20.3-tsddff070: []string{"C:\\Program Files\\Tailscale\\tailscale-ipn.exe"}
LogID: b873d21b551bbe0db499f94601cbc9bbcdf09ac40e349ac2aa2e8518c9edb936
logpolicy: using LocalAppData dir C:\Users\USER\AppData\Local\Tailscale
stdout ok.
stderr ok.
log ok.
Running UI client...
ui: creating mainWindow
ui: Failed to explicitly start tailscaled: openServiceForReadExecute: Access is denied.
ui: creating tray
ui: watchBackend: connected.
ui: Handle: logs: be:38496f772c8190579551b9a7583b3cf911fdc5105e10b9189218c43f6c89ab39 fe:b873d21b551bbe0db499f94601cbc9bbcdf09ac40e349ac2aa2e8518c9edb936
ui: latest version check: "1.40.1", <nil>
ui: ui: Notify: running latest version
ui: ui: setLatestVersion("1.40.1", "")
ui: stateChanged: NoState -> Starting
ui: Beginning to watch engine updates
ui: stateChanged: Starting -> Running
```

### OS

Windows

### OS version

Win10 22H2 19045.2965

### Tailscale version

1.40.1

### Bug report

BUG-38496f772c8190579551b9a7583b3cf911fdc5105e10b9189218c43f6c89ab39-20230515112643Z-c46c0bbf9d6ba132

**Comment by LeeTeng2001** [comment]
Same issue

**Comment by DentonGentry** [comment]
The usual flow would be to run the application:
<img width="357" alt="Screenshot 2023-06-04 at 9 12 49 AM" src="https://github.com/tailscale/tailscale/assets/1140756/1826cf1f-840a-476b-9fff-14762254eaee">

The icon appears in the taskbar:
<img width="205" alt="Screenshot 2023-06-04 at 9 12 56 AM" src="https://github.com/tailscale/tailscale/assets/1140756/b509a239-4274-444b-8402-7d1dd06eba66">

Right clicking on the taskbar makes the menu appear:
![Screenshot 2023-06-04 at 9 13 09 AM](https://github.com/tailscale/tailscale/assets/1140756/4efdcbf8-ee3e-4618-86cd-c4152d0a5baf)

What happens instead?

**Comment by SeriousM** [comment]
Hi @DentonGentry, thanks for your clarification!
At the time I was writing the issue I didn't had a task icon and was expecting a UI.
For some reason after a few days the task icon appeared and (since the last version?) a tooltip hints the functionality behind a right click.
![image](https://github.com/tailscale/tailscale/assets/462013/e8555bf2-bc06-4632-af60-c4d3209e189e)

I'll close the issue. Thanks.

**Comment by AcrossForest** [comment]
It is astonishing for new users as we expect a window to pump out. We didn't notice the small icon appearing at the corner of the system status bar and thought that the software was broken, so we uninstalled/installed it over and over again.

I think it would be more friendly to add a default behavior just like music players. When the software is already running  (hidden in the system bar), and the user starts the software again, display something to let the user know it is already there.
