### ISSUE TITLE
FR: see other computers in Windows Explorer > Network via LLMNR

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#814]
User request from email, paraphrasing:

> It should be possible to see your other Windows devices using Windows Explorer's Network view.

I'm not sure how that discovery works (Layer 2? Multicast?).

If it's multicast, then perhaps we'll get this for free later. But let's keep this open until we confirm that it works (or that it's not possible, if it's a layer 2 thing)

**Comment by chrisbrownie** [comment]
Multicast, using [LLMNR](https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution).

**Comment by bradfitz** [comment]
Thanks, @chrisbrownie!

**Comment by DentonGentry** [comment]
We'll track this effort in https://github.com/tailscale/tailscale/issues/1482

Closing as a dup of https://github.com/tailscale/tailscale/issues/1482
