### ISSUE TITLE
FR: Switch from coreos/go-iptables to google/nftables

### ISSUE THREAD

**Issue by mochaaP** [tailscale/tailscale#8152]
### What are you trying to do?

CoreOS's `go-iptables`[1] library uses the `iptables` command line interface to interact with `netfilter` in the kernel.

This doesn't work well on systems that don't have a `iptables` utility, or just dropped support for `iptables`.

### How should we solve this?

Switch to google/nftables[2] Either by:

* a) rolling optional subsequential changes in main branch with optional go build tags
* b) expose this as a command line switch to end users (so it gets included in the official build, but doing so may pollute the codebase)
* c) open a new branch and replace the current iptables logic until it's ready to merge

### What is the impact of not solving this?

The problem here is that some modern distros already started ditching `iptables` by default. 

OpenWrt's firewall3 already switched to nftables for their routing rules and we currently have to include a patch[3] to set `netfilter-mode` to disabled by default and provide a stub `iptables` to make `go-iptables` happy.

### Anything else?

[1]: https://github.com/coreos/go-iptables
[2]: https://github.com/google/nftables
[3]: https://github.com/openwrt/packages/blob/master/net/tailscale/Makefile

**Comment by mochaaP** [comment]
Dup of #391

**Comment by bradfitz** [comment]
@mochaaP, FYI, work has begun on this recently.
