### ISSUE TITLE
Hide server mode option for versions of Windows that do not support Remote Desktop?

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#816]
**Describe the bug**

I came across a new Windows build that supports Windows Remote Desktop (RDP):

- https://github.com/tailscale/tailscale/issues/275#issuecomment-707360568
- https://twitter.com/Tailscale/status/1315778622091751424

On trying to set that up though, I learned that Remote Desktop is not available for my version of Windows, which is Windows 10 Home.

Would it be helpful to show that server mode option only for Windows 10 Pro users?

**To Reproduce**

- Install 1.1.535 or higher on Windows: https://github.com/tailscale/tailscale/issues/275#issuecomment-707360568
- Login into Tailscale
- Enable "Server mode" from the Tailscale menu on bottom right menu of Windows/next to clock

**~Expected~ Suggested behavior**

Hide the server mode option if Windows is not Windows 10 PRo

**Version information:**
 - Device: Laptop
 - OS: Windows
 - OS version: Windows 10 Home
 - Tailscale version: 1.1.535

**Additional context**

https://support.microsoft.com/en-us/windows/how-to-use-remote-desktop-5fe128d5-8fb1-7a23-3b8a-41e636865e8c -- as seen here Windows 10 Home needs to be upgraded to Windows 10 Pro to support Remote Desktop.

**Comment by bradfitz** [comment]
RDP is but one protocol you might wish to speak to your Windows machine.

You can run servers on Windows 10 Home, etc.

**Comment by arunsathiya** [comment]
Interesting, I wasn't aware of that! In this case, let me go ahead and close this issue..
