### ISSUE TITLE
Windows: Choosing "no" on "confirm server mode" dialog box doesn't work; proceeds to enable server mode

### ISSUE THREAD

**Issue by arunsathiya** [tailscale/tailscale#817]
**Describe the bug**

On using Tailscale 1.1.535 on Windows (brings server mode functionality https://github.com/tailscale/tailscale/issues/275#issuecomment-707360568), clicking on the "Server mode" option on the menu brings up a popup. Choosing "no" on the popup is not supposed to enable server mode functionality, but it proceeds to enable that functionality.

**To Reproduce**

- Install 1.1.535 or higher, from https://github.com/tailscale/tailscale/issues/275#issuecomment-707360568
- Login into Tailscale
- Use the menu at bottom right menu, and click on "server mode"
- When a popup appears, choose "no"
- Check status of "server mode" using the same menu
- Notice that server mode appears to be enabled

**Expected behavior**

Choosing no must not enable server mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/18581859/95813577-ceddc400-0d35-11eb-8b30-fb6d27de5fd6.png)

![image](https://user-images.githubusercontent.com/18581859/95813481-9e962580-0d35-11eb-877f-165109b8794f.png)

**Version information:**
 - Device: Laptop
 - OS: Windows
 - OS version: Windows 10 Pro
- Tailscale version: 1.1.535

**Additional context**

I am not sure if server mode is actually enabled or if this is just a UI/display bug on the menu.

**Comment by bradfitz** [comment]
@arunsathiya, whoops, fixed! Looks like it was just a UI bug, but fixed. Will be out in the next build.
