### ISSUE TITLE
portlist: allow to receive updates for loopback addresses

### ISSUE THREAD

**Issue by marwan-at-work** [tailscale/tailscale#8171]
After an internal discussion, there are use cases (such as using `tailscale serve`) where loopback addresses are of interest from within the portlist package. 

Ideally we can use a param to switch the behavior on off based on the caller.

**Comment by bradfitz** [comment]
I'd like to see this fleshed out more, as I don't remember or missed the "internal discussion".

Can you elaborate here?

**Comment by marwan-at-work** [comment]
Re-opening as the last PR did not account for the constructor
