### ISSUE TITLE
Kubernetes-operator - Cannot remove machine

### ISSUE THREAD

**Issue by cwiggs** [tailscale/tailscale#8192]
### What is the issue?

I have the k8s tailscale-operator setup in a cluster and am having trouble removing a machine and it's `ts-*` pods from tailscale/k8s.

I annotated the `default.kubernetes.svc` resource in order to talk to the k8s cluster via kubectl over tailscale.  This method worked, but I then removed the annotations so I could try the [auth proxy](https://tailscale.com/kb/1236/kubernetes-operator/#enabling-an-auth-proxy) method.  Removing the annotations did not remove the machine from tailscale and did not remove the `ts-*` pods that were created. When I delete the `ts-*` pods they just get created again automatically.

Another thing I tried was adding the annotations back but setting `tailscale.com/expose` to `"false"` but that does not seem to work.  In fact when I do that the operator pod throws this error:

```
{"level":"error","ts":"2023-05-23T18:42:16Z","msg":"Reconciler error","controller":"service","controllerGroup":"","controllerKind":"Service","Service":"name":"kubernetes","namespace":"default"},"namespace":"default","name":"kubernetes","reconcileID":"d5826b40-f63f-4c97-8f86-ae12f0f231ce","error":"getting statefulset: found multiple matching *v1.StatefulSet objects","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

So, how do I correctly remove a k8s service from the tailscale-operator?

Thanks.

### Steps to reproduce

* Deploy tailscale operator to k8s.
* Annotate the `default.kubernetes.svc` with `tailscale.com/expose: "true"`.
* Remove the `tailscale.com/expose` annotation from `default.kubernetes.svc`.
* Witness that the machine is still in the tailscale admin interface and the `ts-*` pod still exists.

### OS

Linux

### OS version

Linux (5.15.0-8.91.4.1.el8uek.x86_64)

### Tailscale version

1.41.55

### Other software

OKE, Oracle linux as workers.

**Comment by maisem** [comment]
> Deploy tailscale operator to k8s.
Annotate the default.kubernetes.svc with tailscale.com/expose: "true".
Remove the tailscale.com/expose annotation from default.kubernetes.svc.
Witness that the machine is still in the tailscale admin interface and the ts-* pod still exists.

These steps do not repro for me.
When I remove the annotation, the pods/statefulset from the `tailscale` namespace and the machines in tailscale are removed.

>{"level":"error","ts":"2023-05-23T18:42:16Z","msg":"Reconciler error","controller":"service","controllerGroup":"","controllerKind":"Service","Service":"name":"kubernetes","namespace":"default"},"namespace":"default","name":"kubernetes","reconcileID":"d5826b40-f63f-4c97-8f86-ae12f0f231ce","error":"getting statefulset: found multiple matching *v1.StatefulSet objects","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}

I believe you have got the operator into a weird state after you attempted to delete internal state in the tailscale namespace.
In order to fix this, I recommend you delete the StatefulSets in the `tailscale` namespace that match the labels
```
      tailscale.com/managed: "true"
      tailscale.com/parent-resource: kubernetes
      tailscale.com/parent-resource-ns: default
      tailscale.com/parent-resource-type: svc
```


Having said that, this shouldn't have happened but without a repro its going to be hard to figure out how to automatically recover from this state.

**Comment by cwiggs** [comment]
I was able to delete the statefulset and the pods did not come back.  A few interesting things with this though:

* The StatefulSet was not annotated with any of the `tailscale.com` annotations.
* There was a svc that WAS annotated with the correct `tailscale.com` annotations in the tailscale namespace.  After I deleted that is when I actually lost access to the tailscale node.
* I added the annotations back to see if tailscale would work correctly and nothing happens.
* I enabled debug logging on the tailscale operator and after doing so I notice that it is saying the API key I'm using is invalid.
  * I checked the secret the operator is using, and verified the secret mounted in the container is correct, but it is in fact a different api key than the log is complaining about.

My suspicion is that the operator is still using an old API key, because I rotated the API key recently.  I already restarted the operator deployment and it is still picking up the wrong API key.  Also you shouldn't have to enable debug logging for the operator to throw an error that the API key is invalid.

Currently I'm grepping the entire container's filesystem for the old API key.  I'll also continue to do some debugging on the operator container to see if I can find out more info.

Thanks!

**Comment by DentonGentry** [comment]
> I already restarted the operator deployment and it is still picking up the wrong API key. 

This seems like the key point. I agree that logging can be added for the case where the API operation fails, to not need debug logging in order to diagnose it.

**Comment by cwiggs** [comment]
After grepping the container I can't see where the old api key is.  @DentonGentry Any additional ideas on how to debug, perhaps where the api key should be located (other than the k8s secret?)

Thanks.

**Comment by cwiggs** [comment]
Here is the snippet from the logs with the error:

```
{"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: [v1] authRoutine: state:authenticating; wantLoggedIn=true"}                                                {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: [v1] direct.TryLogin(token=false, flags=0)"}                                                               {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: doLogin(regen=false, hasUrl=false)"}                                                                       {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: RegisterReq: onode= node=[z3lub] fup=false nks=false"}                                                     {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=false; authURL=false"}                  {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: [v1] TryLogin: invalid key: API key does not exist"}                                                       {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: [v1] sendStatus: authRoutine-report: state:authenticating"}                                                {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"Received error: invalid key: API key does not exist"}                                                               {"level":"debug","ts":"2023-06-28T08:18:18Z","logger":"tailscaled","msg":"control: authRoutine: [v1] backoff: 18716 msec"}      
```

Previously I think the api key that it was trying to use was actually printed to the logs and now it seems to no longer do that.  I'm going to verify the api key in the k8s secret and that mounted secret is valid.  Next I'm going to just redeploy the entire workload to see if that fixes the issue.

**Comment by rhealitycheck** [comment]
Ok that's definitely helpful. Yeah I think it's the key the machine/pod is registered with has somehow gotten into a weird state.

I also haven't been able to repro following the steps you'd outlined above but I'm trying a few new things and at least with these log lines maybe I can get into a state where I can simulate something similar enough.

**Comment by cwiggs** [comment]
> Yeah I think it's the key the machine/pod is registered with has somehow gotten into a weird state.

Is this key the same as the oauth key?  Can I re-create the key and see if that fixes the issue?

**Comment by cwiggs** [comment]
In an attempt to fix this I deleted the operator deployment today and noticed that now in the logs it shows this error:

```
"logger":"tailscaled","msg":"Received error: invalid key: API key <api_key_secret_removed>"}
```

So now it's actually printing out the api key that it says invalid to the console.  Is there someone in tailscale that can validate that the api key that it is saying is invalid actually belongs to my account?

**Comment by cwiggs** [comment]
I got the "invalid api key" error to go away by deleting the secret named `operator` and restarting the operator deployment.  Looks like now the operator is able to connection to tailscale properly.

After fixing the api key issue I annotated `default.kubernetes.svc` with `tailscale.com/hostname: example` however nothing seemed to happen.  I then added the annotation `tailscale.com/expose: "true"` and that created the `ts-kubernetes-*****` service and created the machine in tailscale.

When I created the `tailscale.com/hostname` annotation for the `default.kubernetes.svc` service I named it the same as the `OPERATOR_HOSTNAME` Environment variable for the operator deployment.  I think this is causing a conflict.  When the tailscale machine comes online after the changes I did in the previous paragraph it comes up with a `-1` on the end.

**Comment by cwiggs** [comment]
Some more findings:

I removed all annotations from `default.kubernetes.svc` and the `ts-kubernetes-*****` pod went away like it should.  I then added just the `tailscale.com/hostname: example.com` back to the service, however this time I made sure it was different than the `OPERATOR_HOSTNAME` environment variable value on the operator deployment.  The `ts-kubernetes-*****` pod comes up however it doesn't seem to actually work.  The only error I see in the log is:

```
2023/07/11 18:45:28 health("overall"): error: not in map poll
```

The pod eventually goes into an error state.

I then tried to change the `tailscale.com/hostname` annotation value back to match the `OPERATOR_HOSTNAME` environment variable value on the operator and now it no longer works, throwing the same error above.  I'm now in a state where I don't see how I can add the `default.kubernetes.svc` to tailscale.  I'm going to try and delete the operator secret and deployment and try a few more things.

@rhealitycheck Yes I'll get the operator.yaml over to you.

**Comment by rhealitycheck** [comment]
So going back to your original post, did you actually want to use the auth proxy or do you need to use the operator with annotations? I'm just trying to understand what your ideal end state to this issue is.

**Comment by cwiggs** [comment]
> I removed all annotations from `default.kubernetes.svc` and the `ts-kubernetes-*****` pod went away like it should. I then added just the `tailscale.com/hostname: example.com` back to the service, however this time I made sure it was different than the `OPERATOR_HOSTNAME` environment variable value on the operator deployment. The `ts-kubernetes-*****` pod comes up however it doesn't seem to actually work. The only error I see in the log is:
> 
> ```
> 2023/07/11 18:45:28 health("overall"): error: not in map poll
> ```
> 
> The pod eventually goes into an error state.
> 
> I then tried to change the `tailscale.com/hostname` annotation value back to match the `OPERATOR_HOSTNAME` environment variable value on the operator and now it no longer works, throwing the same error above. I'm now in a state where I don't see how I can add the `default.kubernetes.svc` to tailscale. I'm going to try and delete the operator secret and deployment and try a few more things.
> 
> EDIT: I restarted the operator deployment, and removed all tailscale.com annotations from `default.kubernetes.svc`, and did find some errors in the logs:

I was able to get the tailscale operator to create the machine for `default.kubernetes.svc` again by deleting the `ts-kubernetes-*****` secrets that were left behind.  Updating the `tailscale.com/hostname` value also worked.

To sum up everything, I'm not 100% sure what caused the issue but I suspect it was a few things.

* One issue was related to the api key error, which was resolved by deleting the `operator` secret and restarting the operator deployment.
* Another issue is that you shouldn't have to enable debug mode for the operator to print that the api key is invalid.
* Another issue seems to be that when you annotate `default.kubernetes.svc` with `tailscale.com/hostname` it doesn't add the machine to tailscale, you also have to add the `tailscale.com/expose` annotation.
* Another issue is that tailscale doesn't seem to clean up the `ts-${service_name}-*****` secrets when an annotation is removed from a svc.
* It also would be nice if there was a document from tailscale that explained the best way to get access to the kubernetes api-server via the tailscale operator without having to use the auth proxy.  It seems like a pretty common scenrio that people are going to get into and it doesn't seem like my method of annotating `default.kubernetes.svc` is the best path.

Hopefully this helps make the tailscale operator better.
