### ISSUE TITLE
autogroup:admin not a valid group for ssh

### ISSUE THREAD

**Issue by jeroenjacobs79** [tailscale/tailscale#8194]
### What is the issue?

My exit-nodes have a specific tag, and I only want admins to use tailscale ssh-feature to connect to this machines.

I have the following in my policy:

```
		{
			"action": "check",
			"src":    ["autogroup:admin"],
			"dst":    ["tag:exitnode"],
			"users":  ["autogroup:nonroot"],
		},
```

However, when I try to save in the web-console, I get the error: `Error: "autogroup:admin" is not allowed in src`

When I replace it with `autogroup:members`, I don't get an issue. This saves fine:

```
		{
			"action": "check",
			"src":    ["autogroup:members"],
			"dst":    ["tag:exitnode"],
			"users":  ["autogroup:nonroot"],
		},
```

Restricting certain ssh destinations based on the user makes sense from a security point of view. I don't understand why this limitation is there.

PS: Yes, I can work around it by the `acls` setting, and only allow `autogroup:admin` to `tag:exitnode`, and block it for all other members.  However, this seems a bit counter-intuitive.

### Steps to reproduce

See above.

### OS

Other

**Comment by KamalAman** [comment]
This is true for the other autogroups as well

**Comment by fernandoflorez** [comment]
+1 .

Tried setting autogroup:admin on ssh unsucessfully too. This should be clarified on the docs IMO.

**Comment by signed-log** [comment]
Can reproduce

**Comment by reesericci** [comment]
Ran into this today

**Comment by shellhazard** [comment]
Hit this as well - was unable to find any explanation [in the related KB article](https://tailscale.com/kb/1193/tailscale-ssh#)

**Comment by geekodour** [comment]
@DentonGentry facing similar issue

![image](https://github.com/tailscale/tailscale/assets/12918431/39a20ef9-f7ac-42e9-afea-b92872b994d8)

**Comment by garry-t** [comment]
omg, still is not fixed..

**Comment by albttx** [comment]
Facing same issue.

**Comment by awly** [comment]
All autogroups should now be available on `src` for SSH rules.
