### ISSUE TITLE
FR: Manage tailscaled socket in Docker environment

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#8195]
### What are you trying to do?

Currently, to run tailscale commands in our Docker image, you will need to specify the location of the socket file.  For instance: `tailscale --socket /tmp/tailscaled.sock status`

We should be able to find the socket. 

### How should we solve this?

`TS_SOCKET` in our container script changes the default only for `tailscaled`

### What is the impact of not solving this?

Usage friction.

**Comment by irbekrm** [comment]
Maisem fixed this in https://github.com/tailscale/tailscale/pull/10518 - tailscale commands in container now don't need explicit socket path
