### ISSUE TITLE
Admin Console UI - ACL Preview does not render preview display for tags

### ISSUE THREAD

**Issue by swatson2** [tailscale/tailscale#8196]
### What is the issue?

Not sure if I should create a new issue or if this is already detailed/covered elsewhere/user error.

When I go to preview rules, all user based ACLs render correctly, but previewing tag ACL rules displays nothing. Seems to be a purely UI issue, all ACLs are functioning as expected. Overall a minor issue.

Hard refreshing the page/clearing cache, logout/login has not resolved the issue. I first observed the issue sometime last week (?) and this functionality has been broken since then. I can provide more details as needed.

I can reproduce this error in:
Chromium Version 113.0.5672.63 (Official Build) (64-bit)
Firefox 113.0 (64-bit)

### Steps to reproduce

In the admin console:

Go to Access Controls -> Preview Rules -> Select a tag from the drop down -> No preview is rendered

### OS

Linux

### OS version

Void Linux

### Tailscale version

N/A

**Comment by phirework** [comment]
Thanks for reporting! This was a regression and should now be fixed.

**Comment by swatson2** [comment]
@phirework I am seeing the fix on my end. Thank you very much for the rapid resolution!
