### ISSUE TITLE
Website: Can't navigate back to the homepage after clicking on "Get Started" while logged in

### ISSUE THREAD

**Issue by nnja** [tailscale/tailscale#820]
**Describe the bug**
Can't navigate back to the homepage after clicking on "Get Started" while logged in

**To Reproduce**
1. Log in to tailscale.com
2. Click on the blue Get Started button, which redirects from /start to /downloads
3. Click the back button in the browser from /downloads

**Expected behavior**
Go back to the homepage

**Actual behavior**
The back button doesn't work because of the redirect

cc/ @rosszurowski

**Comment by rosszurowski** [comment]
Our recent changes to the website have fixed this.
