### ISSUE TITLE
HTTPS certificate renewal is based on hard-coded time until expiry

### ISSUE THREAD

**Issue by aarongable** [tailscale/tailscale#8204]
### What is the issue?

When tailscale [retrieves an SSL certificate](https://github.com/tailscale/tailscale/blob/66f97f4bea043230e4e0bc30a0124a1eae3208cc/ipn/ipnlocal/cert.go#L84), it [checks to see if it should renew the cert](https://github.com/tailscale/tailscale/blob/66f97f4bea043230e4e0bc30a0124a1eae3208cc/ipn/ipnlocal/cert.go#L105), and if so, does so in the background. This is great.

However, the only heuristic used for this check is [whether the cert will be expired](https://github.com/tailscale/tailscale/blob/66f97f4bea043230e4e0bc30a0124a1eae3208cc/ipn/ipnlocal/cert.go#L132) at a point in time [14 days in the future](https://github.com/tailscale/tailscale/blob/66f97f4bea043230e4e0bc30a0124a1eae3208cc/ipn/ipnlocal/cert.go#L104).

This has two problems:
1) If Let's Encrypt (or any other CA that Tailscale uses in the future) begins issuing short-lived certificates (e.g. 10-day certs which are likely to be [encouraged by the Baseline Requirements](https://github.com/cabforum/servercert/pull/414) in the near future), then this heuristic will result in attempting to renew the certificate after _every retrieval_.
2) If the certificate is revoked, Tailscale will continue using it until it expires.

The first of these can be rectified by changing the heuristic to "2/3rds of the way through the certificate's validity period", rather than "14 days before expiry". This will scale well to any certificate lifetime, and is the [officially recommended best practice](https://letsencrypt.org/docs/integration-guide/#when-to-renew) by Let's Encrypt.

But an even better overall solution, which also rectifies the second problem, would be to [query Let's Encrypt's ARI](https://letsencrypt.org/2023/03/23/improving-resliiency-and-reliability-with-ari.html) (ACME Renewal Info) [endpoint](https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/). This endpoint, specified by [draft-ietf-acme-ari](https://datatracker.ietf.org/doc/draft-ietf-acme-ari/), returns a window of time which is optimal for renewing the cert in question. If the current time is within or after the suggested window, it's time to renew! Let's Encrypt's implementation will also always tell the client to renew right now when the certificate is no longer usable, for example because it has been revoked or has been impacted by an incident.

### Steps to reproduce

1) [Enable HTTPS](https://tailscale.com/kb/1153/enabling-https/)
2) Get a certificate with a lifetime of less than 14 days
3) Tailscale will attempt renewal on every request

### Tailscale version

1.42.0

**Comment by DentonGentry** [comment]
I imagine we'll implement the "2/3rds of the way through the certificate's validity period" first, as that can be done almost immediately.

**Comment by aarongable** [comment]
Makes sense. I strongly encourage adopting ARI in the reasonably-near future, as it allows for much more agile certificate replacement. Every ARI response comes with a Retry-After header indicating the next time the client should query for an updated renewal window, so ARI responses can be cached until that time and don't have to be queried every time.

**Comment by mholt** [comment]
In the genuine interest of improving the situation here and making things more reliable/maintainable, could Tailscale use a lib like [CertMagic](https://github.com/caddyserver/certmagic) to manage its certificates? (Disclaimer: I'm the author)

**Comment by DentonGentry** [comment]
Tailscale 1.44 will include https://github.com/tailscale/tailscale/pull/8258

**Comment by johnvick** [comment]
Just updated to v 1.44 and tried to renew cert for Proxmox Backup Server VM that is due to expire on 25 June, but I get the same cert.

**Comment by DentonGentry** [comment]
@johnvick when was the certificate issued? Admittedly, as we're almost exactly 4 days from the end of June 25 UTC, I'd expect even a 14 day certificate to be 2/3rds of the way through its lifetime now.

**Comment by johnvick** [comment]
It's been valid since 27 March.

**Comment by johnvick** [comment]
I just renewed cert a minute before expiry (or maybe it was just after given time zone difference) having failed an hour or two ago. New cert valid until 23 September.

**Comment by awly** [comment]
https://github.com/tailscale/tailscale/pull/8599 adds support for ARI (with a fallback to the current expiry-based check). It should be available in the next release of tailscale.
@DentonGentry @aarongable anything else we should improve around renewal or can this issue be closed?

**Comment by DentonGentry** [comment]
I think that meets the feature request described here. I don't know of other immediate things about certificate renewal, and would want us to track them as separate issues anyway.

I'd say this can be closed as completed.

**Comment by johnvick** [comment]
Not sure if this is the right place to mention this as I note the matter is closed, but I just tried to update a three month cert 5 days out from expiry and received the same cert again.

**Comment by awly** [comment]
@johnvick which version of tailscale are you running (the output of `tailscale version --daemon`)?
If it's older than 1.46, you might just need to upgrade.
If it's 1.46, could you restart `tailscaled` with `TS_DEBUG_ACME="true"` and search for any log lines with `acme` in them and paste them here?

**Comment by johnvick** [comment]
Its v 1.46.1. 
I'm not sure how to restart tailscaled with TS_DEBUG_ACME="true" - can you please advise the exact command?

**Comment by DentonGentry** [comment]
`sudo systemctl edit tailscaled.service`

This will start an editor for /etc/systemd/system/tailscaled.service.d/override.conf
You would add this:

```
[Service]
Environment=TS_DEBUG_ACME="true"
```

Then run these commands:

```
sudo systemctl daemon-reload
sudo systemctl restart tailscaled
```

**Comment by johnvick** [comment]
Thanks for the assistance here.
Did as you asked, this appears in syslog:

Jul 27 14:42:17 omv-2 tailscaled[9105]: acme: ARI response: &{SuggestedWindow:{Start:2023-07-02 04:31:12 +0000 UTC End:2023-07-04 04:31:12 +0000 UTC} ExplanationURL:}
Jul 27 14:42:17 omv-2 tailscaled[9105]: cert("omv-2.rooster-frog.ts.net"): starting async renewal

**Comment by awly** [comment]
Ahh, looks like @kurtraschke tracked down the bug correctly in https://github.com/tailscale/tailscale/issues/8725
The renewal logic is indeed flawed, it re-checks later whether a cert is still valid and aborts renewal.

Part of the problem is that this cert management is shared between `tailscale cert` (which should always wait for renewal) and what appear to be parts of Tailscale Funnel logic (where it's preferable to return still-valid-but-pending-renewal cert for inbound connections).

I'll work on the fix tomorrow. Let's keep discussion in https://github.com/tailscale/tailscale/issues/8725 since that nails down the problem description.

**Comment by awly** [comment]
@johnvick to close the loop here, the fix was merged and release on the unstable track.
If you'd like, you can grab the unstable version from https://pkgs.tailscale.com/unstable/#static to test it out.
Otherwise, the current stable version of tailscale (1.46.1) will only update expired certs :/

**Comment by johnvick** [comment]
Works perfect thanks very much.

**Comment by johnvick** [comment]
I have noticed recently that it takes two runs to get a new cert - first run pulls the existing cert, second a new one.
This is seven days out from cert expiry.

**Comment by DentonGentry** [comment]
I think this is normal. The old certificate is still good, so it is returned immediately but schedules a background task to renew it. The next time `tailscale cert` is run, it finds the renewed cert.

**Comment by awly** [comment]
@johnvick how often do you run the cronjob?
If it runs daily, it should have plenty of time to grab the new cert.
If it runs weekly, then it can definitely cause problems.

I believe the behavior was changed in https://github.com/tailscale/tailscale/commit/24f322bc43cd0aa6f9492c2d03b3c0d330b0cc3b, to avoid blocking on renewal while serving traffic with `tailscale serve` or `tailscale funnel`.
The current behavior of `tailscale cert` is still technically correct, as we never return an expired certificate. However, we may end up returning a certificate with a very short expiry.
