### ISSUE TITLE
FR: Periodically send NAT-PMP request

### ISSUE THREAD

**Issue by t0ny-peng** [tailscale/tailscale#8214]
### What are you trying to do?

I'm deploying Tailscale after pfSense firewall. It worked well when NAT-PMP is enabled. However, after the firewall restarts or simply after running for 24hr, the NAT-PMP entries are lost due to the restart or simply expire, therefore the traffic has to go through relay rather than direct connection.

### How should we solve this?

Tailscale can periodically send NAT-PMP request to config the firewall

### What is the impact of not solving this?

Have to restart Tailscale after the firewall restarts

**Comment by t0ny-peng** [comment]
It seems that after the NAT-PMP mapping expires, the next time I connect to Tailscale client behind the firewall, the first several tries will be proxied by DERP server, but NAT-PMP will show up after several seconds in pfSense portal. Perhaps this is an on-demand NAT-PMP?

**Comment by DentonGentry** [comment]
> No luck. Not able to reproduce this again.

The intent is certainly that NAT-PMP requests are periodically sent, they aren't supposed to stop. I'm not sure what happened that they stopped in the initial report.

**Comment by DentonGentry** [comment]
I doubt we will figure out what was happening when the initial report was sent.
