### ISSUE TITLE
ACL Rules Preview breaks if comments after final closing brackets

### ISSUE THREAD

**Issue by timtailscale** [tailscale/tailscale#8215]
### What is the issue?

When editing ACLs, adding comments after the final closing bracket causes the rules parsing preview to break with the error `An error occurred line {#}, column 1: parsing comment: unexpected EOF` with the error line being the comment after the bracket.

### Steps to reproduce

Add a comment after the final bracket in the ACL file.

**Comment by dsnet** [comment]
I submitted a fix for this on our control server. The issue was not due to the admin UI being unable to parse it, but some legacy code doing incorrect JSON munging, which simply needed to be removed. The fix will be effective upon the next deployment of our control server.

**Comment by dsnet** [comment]
Verified to be fixed.
