### ISSUE TITLE
Make cmd/dist build synology packages

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#8217]
Now that we have cmd/dist, it can build synology packages as well as other things, rather than having a separate build process for those.

**Comment by DentonGentry** [comment]
Note one subtlety: Synology requires that version numbers be in a specific format.
https://github.com/tailscale/tailscale-synology/commit/250e8cfd471d1111003ef3237897e12007f257c7

Builds with version numbers which do not start with "60" or "70" will be rejected by the Package Center.

--------

Implementing Synology support in cmd/dist may also fix https://github.com/tailscale/corp/issues/7959 (which most of y'all won't be able to see, sorry).

**Comment by danderson** [comment]
I missed @DentonGentry's comment originally, but for the record: I ported synology builds to cmd/dist, and verified that the new build produces bit-identical outputs to the old, except for some minor diffs in what version information gets embedded into binaries, and slightly different file sizes due to different compression settings. But all the important package metadata, binaries and version numbers behave the same as they did before, including the `60` and `70` prefixes.

**Comment by danderson** [comment]
Also for the record: I verified that www.tailscale.com doesn't need any updates. The one pointer to the tailscale-synology repo is appropriate (crediting the original creator of the package, prior to us taking on its maintenance), everything else points to either the official Synology software center, or pkgs.tailscale.com for sideloading.
