### ISSUE TITLE
Sharing: allow sharing nodes with other users

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#822]
Placeholder for sharing feature, which would let people share their individual nodes between domains and users. For example, someone could start a Minecraft server and share with their friends.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2cw5t)

**Comment by rosszurowski** [comment]
Closing this out because we launched sharing publicly on January 26th, 2021.
