### ISSUE TITLE
FR: Latest tag for each arch

### ISSUE THREAD

**Issue by arunoruto** [tailscale/tailscale#8221]
### What are you trying to do?

Currently I have some IoT devices like my Valetudo vacuum or OpenTV box which have tailscale binaries running on them. It would be nice to have a URL which points at the latest release for each arch, so we can automate updates with scripts.

### How should we solve this?

Currently the newest version is  `1.42.0` and a URL for arm64 is https://pkgs.tailscale.com/stable/tailscale_1.42.0_arm64.tgz
You could introduce an URL, for example https://pkgs.tailscale.com/stable/tailscale_arm64.tgz, which always points to the newest version.

### What is the impact of not solving this?

Currently I am always changing the version number in my scripts before running it.

**Comment by DentonGentry** [comment]
https://pkgs.tailscale.com/stable/tailscale_latest_386.tgz
https://pkgs.tailscale.com/stable/tailscale_latest_mips.tgz
https://pkgs.tailscale.com/stable/tailscale_latest_arm64.tgz
etc.
