### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by oloho** [tailscale/tailscale#8228]
### What is the issue?

Hi

I'm using my android phones as VPN server with Tailscale,:

1/ my phone android 4G IP (ISP SFR) is set up as exit node
2/ my pc home ip (ISP Orange) connected to the Tailscale network and use my phone android as exit node.
3/ my pc has the SFR IP but the dns is ISP Orange.

How to fix that? Can some help me to set up a DNS that would match with my IP exit node?

**Comment by bradfitz** [comment]
You omitted too much of the requested bug template to help. There's just not enough information here to be considered a bug.
