### ISSUE TITLE
OIDC: Support arbitrary OpenID Connect auth endpoints

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#823]
Placeholder for generic OIDC support requested by customers.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2cw7l)

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/379
https://github.com/tailscale/tailscale/issues/794

SAML, though not as nice as OIDC, may also be an option. It looks like it will be easier to implement a self-service flow for adding a new SAML auth provider.

**Comment by DentonGentry** [comment]
A note on GitHub OAuth: if you request the 'user:email' scope you get email addresses, but you have to request it. The default ("no scope") only gives you their GitHub username and very limited profile information.

**Comment by DentonGentry** [comment]
We don't have a specific issue tracking Azure Active Directory support, but as it supports OIDC we can likely support it here as well.

**Comment by patmaddox** [comment]
I'd like to be able to auth with GitHub.

**Comment by bradfitz** [comment]
@patmaddox, that's https://github.com/tailscale/tailscale/issues/446

**Comment by dvtkrlbs** [comment]
How much work this requires I particularly want Keycloak or iCloud logins for personal usage. I would try to do a band aid solution and try to self host it but the biggest problem is self hosting the mobile applications themselves. I did not see that iCloud was listed here as well and seems interesting since i use custom domains with iCloud+ so if there are any pointers you can give me I would like to work on that.

**Comment by dvtkrlbs** [comment]
I am open to getting a really small summary on what should be done to add iCloud login. I am willing to try to contribute to the project.

**Comment by garrett-ts** [comment]
adding new request
#5345 (Rippling)

**Comment by sanilcredcore** [comment]
where can i find the list of identity providers tested and supported. I am specifically looking for JumpCloud support

**Comment by diogopms** [comment]
> where can i find the list of identity providers tested and supported. I am specifically looking for JumpCloud support
https://tailscale.com/kb/1240/sso-custom-oidc/

I'm looking for the way to configure the auth0 using OIDB using tailscale.

**Comment by mayakacz** [comment]
> where can i find the list of identity providers tested and supported

The full list of IdPs supported, including those tested for custom OIDC is listed here: https://tailscale.com/kb/1013/sso-providers/

> I am specifically looking for JumpCloud support
> I'm looking for the way to configure the auth0 using OIDB using tailscale.

See https://tailscale.com/kb/1240/sso-custom-oidc/#additional-provider-configurations

**Comment by DentonGentry** [comment]
I believe the intent of this feature request has been met by https://tailscale.com/kb/1240/sso-custom-oidc/
Closing as completed.
