### ISSUE TITLE
Weird Behavior in restrictive Network

### ISSUE THREAD

**Issue by eldadh** [tailscale/tailscale#8236]
### What is the issue?

When trying to connect within the campus network, it wont connect after reboot.
( shows need to restart windows service)
Apparently if an initial connection is made ( my guess to the controller) over unrestricted network, the data plane can mange via the derp servers over a restricted network.

However, i dont see why the controler traffic cant be such that will mimic HTTP like the DERP traffic.

### Steps to reproduce

In order to connect i need to:
1. disconnect from the network
2. connect to public unrestictive wifi / AP 
3. once connected to tailscale , switch back to the restrictive network.
once back on the restrictive network, everything works as expected via derp relay.

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.42

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/7305, I think.
