### ISSUE TITLE
Trim netmap based on ACL settings

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#824]
If ACLs specify that two nodes are never able to access each other, then there's also no reason for them to be able to know about each other at all. We should automatically remove such nodes from each others' network maps.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2cwb5)

**Comment by bradfitz** [comment]
I guess I should reopen this until it's fully deployed to everybody.

Currently it's limited to just `tailscale.com` and we haven't validated it in prod.

**Comment by gdtv** [comment]
Does this feature work in the latest version 1.88.3 please?
I set the ACL to:
```
{
"acls": [].
"tests": []
}
```
But using the "tailscale status" command on the client, I can still see all the other devices.

**Comment by erlendwtf** [comment]
Still waiting for this feature, it is indeed a must-have. Any updates, @bradfitz?

I have 8 Tailscale-connected devices, signed in with my user account.
I have a server in Azure, connected to my tailnet via an authkey and assigned to tag:server

I have no ACL, and the following grants policy:

```
	"grants": [
		{
			"src": ["my@user.tld"],
			"dst": ["tag:nuc", "tag:someOtherMachine"],
			"ip":  ["*"],
		},
		{
			"src": ["my@user.tld"],
			"dst": ["tag:server"],
			"ip":  ["*"],
		},
	],
```

Running `tailscale status` on the server lists all the devices in my tailnet. My expectation is that no other devices besides the server itself should be listed.

**Comment by gdtv** [comment]
> no other devices besides the server itself should be listed

If "no other devices besides the server itself should be listed",  this would cause this server to be unable to access any other devices, and no other devices would be able to access this server. What's the point then?

**Comment by erlendwtf** [comment]
> > no other devices besides the server itself should be listed
> 
> If "no other devices besides the server itself should be listed", this would cause this server to be unable to access any other devices, and no other devices would be able to access this server. What's the point then?

There’s a difference between what the control plane must know and what a local CLI needs to reveal. My concern is only about `tailscale status` which currently serves as a convenient visibility tool, but also becomes a data‑exfiltration surface if the endpoint is compromised. Minimizing status output aligns with:

- Principle of least privilege & information minimization.

- ACL symmetry: If ACLs disallow initiating traffic from a device to most peers, the status view shouldn’t list those peers.

- Threat model & blast radius: On high‑risk or untrusted endpoints, the operator may not be trusted, or the device may be seized. Especially when adding devices which are physically located in areas of geopolotical instability to our tailnet, which sadly happens regularly. 

A local CLI should not reveal tailnet topology, hostnames, or user identities beyond what’s necessary - or this visibility setting should at the very least be controlled by an administrator.
