### ISSUE TITLE
FR: Custom Tailnet Name

### ISSUE THREAD

**Issue by thewilli** [tailscale/tailscale#8240]
### What are you trying to do?

Neither the default tailnet name, nor the "fun" ones are easy to remember. It would be great if we had the option to use a "custom" one - and may it be the organization name - without any fun words or numeric suffices. 

### How should we solve this?

Provide an option to choose a custom tailnet name in addition to the generation of "fun" ones.

### What is the impact of not solving this?

Remembering random `tailXXXXX.ts.net` or `horse-battery-staple.ts.net` is not straightforward and prone to errors. Unifying DNS names and keeping them according to a central convention simplifies an admin's life.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/4221
