### ISSUE TITLE
PROXMOX LXC - Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

### ISSUE THREAD

**Issue by openaspace** [tailscale/tailscale#825]
Hello.

I have tried to install tailscale on two proxmox lxc containers with privilege enabled, one ubuntu and one debian.. with the same problem.

Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

Installing tailscale in a normal proxmox vps with full virtualized hardware, it works correectly.

**Comment by openaspace** [comment]
Looking this interesting post https://nixvsevil.com/posts/wireguard-in-proxmox-lxc/
I mean that need to be enabled at host level first....also I need to run tailscale in the main proxmox hypervisor.

Exist a procedure for a debian hypervisor like proxmox? it's safe?

Please help, it will revolute the host hypervisors management!

**Comment by openaspace** [comment]
I have installed tailscale for test in a proxmox host .. apparently without problems, 
also create a test container trying to install tailscale, but even with the tailscale installed in the main host, the proxmox container continue to  can't execute tailscale: 

2020/10/18 10:18:46 Failed to connect to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

**Comment by bradfitz** [comment]
Few notes:
* We don't use the kernel wireguard module
* we do need /dev/net/tun from tailscaled (so an LXC container would need special access to it)
* the tailscaled daemon (as root) and the `tailscale` CLI should generally be run in the same world, not split between host/guest or different VMs
* if the CLI says `dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory` and you're running the CLI from the same environment that `tailscaled` is running in, the real issue is likely that `tailscaled` is failing to start up. Look at `journalctl -fu tailscaled.service` while you `systemctl restart tailscaled`, etc.

**Comment by bradfitz** [comment]
Actually, I'm not sure there's anything actionable here to do, so I'll close this in a couple days unless there's a concrete bug we can help out with. Let us know.

If you just want to share & discuss you progress running Tailscale on Proxmox, https://forum.tailscale.com/ also exists.

(FWIW, three of us working at Tailscale also run Proxmox at home)

**Comment by NiklasMerz** [comment]
I tried to get tailscale running in one of my containers in Proxmox, too.

`tailscaled` indeed crashes. Any ideas what I could try? I can move this to a forum thread as well if this the better place.

My logs: 
```
root@stuff:~# journalctl -fu tailscaled.service
-- Logs begin at Sat 2020-11-14 11:25:38 UTC. --
Nov 21 19:50:22 stuff systemd[1]: Stopped Tailscale node agent.
Nov 21 19:50:22 stuff systemd[1]: tailscaled.service: Failed to reset devices.list: Operation not permitted
Nov 21 19:50:22 stuff systemd[1]: Starting Tailscale node agent...
Nov 21 19:50:22 stuff tailscaled[3863]: logtail started
Nov 21 19:50:22 stuff tailscaled[3863]: Program starting: v1.2.8-tcde3a23b6-g1f7ecb611, Go 1.15.4-tsf9db43b: []string{"/usr/sbin/tailscaled", "--cleanup"}
Nov 21 19:50:22 stuff tailscaled[3863]: LogID: 50f2d3137153064f276390fe85a2e5b70266f773dff3c6b2d7c00159346ce42f
Nov 21 19:50:22 stuff tailscaled[3863]: logpolicy: using system state directory "/var/lib/tailscale"
Nov 21 19:50:22 stuff tailscaled[3863]: dns: using dns.directManager
Nov 21 19:50:22 stuff tailscaled[3863]: flushing log.
Nov 21 19:50:22 stuff tailscaled[3863]: logger closing down
Nov 21 19:50:23 stuff tailscaled[3863]: logtail: dial "log.tailscale.io:443" failed: dial tcp: operation was canceled (in 999ms)
Nov 21 19:50:23 stuff tailscaled[3863]: logtail: upload: log upload of 434 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/7008bfbf2f762683a7540aab70a7b37aa076eb49531968b19522deefb172ba56": context canceled
Nov 21 19:50:23 stuff systemd[1]: Started Tailscale node agent.
Nov 21 19:50:23 stuff tailscaled[3870]: logtail started
Nov 21 19:50:23 stuff tailscaled[3870]: Program starting: v1.2.8-tcde3a23b6-g1f7ecb611, Go 1.15.4-tsf9db43b: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "41641"}
Nov 21 19:50:23 stuff tailscaled[3870]: LogID: 50f2d3137153064f276390fe85a2e5b70266f773dff3c6b2d7c00159346ce42f
Nov 21 19:50:23 stuff tailscaled[3870]: logpolicy: using system state directory "/var/lib/tailscale"
Nov 21 19:50:23 stuff tailscaled[3870]: Starting userspace wireguard engine with tun device "tailscale0"
Nov 21 19:50:23 stuff tailscaled[3870]: Linux kernel version: 5.4.65-1-pve
Nov 21 19:50:23 stuff tailscaled[3870]: is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.4.65-1-pve/modules.dep.bin'
Nov 21 19:50:23 stuff tailscaled[3870]: modprobe: FATAL: Module tun not found in directory /lib/modules/5.4.65-1-pve
Nov 21 19:50:23 stuff tailscaled[3870]: tun module not loaded nor found on disk
Nov 21 19:50:23 stuff tailscaled[3870]: CreateTUN: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
Nov 21 19:50:23 stuff tailscaled[3870]: wgengine.New: CreateTUN("tailscale0") failed; /dev/net/tun does not exist
Nov 21 19:50:23 stuff tailscaled[3870]: flushing log.
Nov 21 19:50:23 stuff tailscaled[3870]: logger closing down
Nov 21 19:50:24 stuff tailscaled[3870]: logtail: dial "log.tailscale.io:443" failed: dial tcp: operation was canceled (in 1.019s)
Nov 21 19:50:24 stuff tailscaled[3870]: logtail: upload: log upload of 459 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/7008bfbf2f762683a7540aab70a7b37aa076eb49531968b19522deefb172ba56": context canceled
Nov 21 19:50:24 stuff systemd[1]: tailscaled.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 19:50:25 stuff tailscaled[3878]: logtail started
Nov 21 19:50:25 stuff tailscaled[3878]: Program starting: v1.2.8-tcde3a23b6-g1f7ecb611, Go 1.15.4-tsf9db43b: []string{"/usr/sbin/tailscaled", "--cleanup"}
```

**Comment by bradfitz** [comment]
@NiklasMerz, Tailscale requires /dev/net/tun (the error message you pasted has some details).

But Proxmox LXC containers can't load kernel modules; the host needs to do that.

Try `sudo lxc config edit YOUR_CONTAINER` and modify the `config`'s `linux.kernel_modules` line and add `tun`.

**Comment by bradfitz** [comment]
Or just `modprobe tun` on the host and add `tun` to `/etc/modules` perhaps.

**Comment by openaspace** [comment]
> @NiklasMerz, Tailscale requires /dev/net/tun (the error message you pasted has some details).
> 
> But Proxmox LXC containers can't load kernel modules; the host needs to do that.
> 
> Try `sudo lxc config edit YOUR_CONTAINER` and modify the `config`'s `linux.kernel_modules` line and add `tun`.

Thank you @bradfitz ,
but I'm not sure to do this on the kernel host.

**Comment by DentonGentry** [comment]
(As I also use proxmox)
On the proxmox host look in /etc/pve/lxc/, for the ID of the LXC you want to use Tailscale in. For example in my case for LXC ID=112, I edit /etc/pve/lxc/112.conf:
```
lxc.cgroup.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
```

This allows the container to have access to /dev/tun. In my case at least, this allows even an unprivileged LXC to run Tailscale. I'm using it to allow connections to a Minecraft server, clearly mission critical.

I'm going to close this as proxmox isn't actually an environment we offer support for, we just happen to be happy users of it. https://forum.tailscale.com/ would be a good resource.

**Comment by bradfitz** [comment]
A blog post on this topic: https://dustri.org/b/running-tailscale-inside-of-a-proxmox-container.html

**Comment by william-bohannan** [comment]
Just a note the newer Promox has a slight change

**kb articale**

kb article: https://tailscale.com/kb/1130/lxc-unprivileged

**Proxmox 6 or earlier**

lxc.cgroup.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file

**Proxmox 7 or later**

lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file

**Comment by ffuhrnew** [comment]
Thank You DentonGentry & william-bohannan.
Your comments helped me a lot to understand
why it was so hard for me to start tailscale in my lxc container.
Thank You so very much ...
