### ISSUE TITLE
macOS, application closes when network device is selected 

### ISSUE THREAD

**Issue by vitormicillo** [tailscale/tailscale#8256]
### What is the issue?

When I select one of the network devices to copy the ip using the apple desktop client, the application suddenly closes.

### Steps to reproduce

Click in the trail icon >> Network Devices >> select one device from the list

### Are there any recent changes that introduced the issue?

This started to happen after the last update made through the App Store.

### OS

macOS

### OS version

Ventura 13.4

### Tailscale version

1.42.0

### Other software

none, just the standard software that comes with the operating system.

### Bug report

BUG-971c4325d95bce534fcb5687e8cb9579d5c9c2e10a6f516830bfe48a7df187e9-20230602124833Z-db608cedce87b597

**Comment by bradfitz** [comment]
cc @agottardo

**Comment by vitormicillo** [comment]
Hi Andrea, how can I get this crash report for you ?
Can i have some guidance please, thanks.

**Comment by agottardo** [comment]
Open the Console app on your Mac (Applications > Utilities > Console.app). Click on "Crash Reports" in the "Reports" section of the left sidebar. Scroll the list that appears. If you see a report with the "Tailscale" process name, right-click on it, click "Reveal in Finder" and then attach the file here. Let me know if you need any help.

**Comment by vitormicillo** [comment]
Thanks for the guidance, here is the report file


[Tailscale-2023-06-01-084118.ips.zip](https://github.com/tailscale/tailscale/files/11650599/Tailscale-2023-06-01-084118.ips.zip)

**Comment by agottardo** [comment]
Thanks, will take a look.

**Comment by agottardo** [comment]
@vitormicillo thanks for the report, we now have a fix for this. A quick workaround for you at the moment is to enable notifications for Tailscale in the notifications settings of your Mac. That should make the issue go away until you get the fix in our next update.

**Comment by vitormicillo** [comment]
Yes, this work around fixes the problem 😂😂😂
Thanks guys.
