### ISSUE TITLE
FR: Introduce QR codes for mobile apps 

### ISSUE THREAD

**Issue by mritunjaymusale** [tailscale/tailscale#8267]
### What are you trying to do?

I am trying to get authkeys to work with android but there is no option to do so. 

### How should we solve this?

In the webui when generating auth keys in settings add an option to display that key as qr code which will open tailscale and add that device to that network sort of like how discord and steam lets you authenticate using their apps. So end users in their camera app can just point to the qr code and they are automatically added to the tailnet.

### What is the impact of not solving this?

Currently subnet sharing doesn work but I can add trusted devices like my family's computers to my tailnet using authkeys so that I don't have to login my email on those PCs. Similarly this qr code way of adding mobile devices will let me and others have the same functionality to add devices without having to login on each device. Even though these devices are trusted and should have access to the family tailnet, not exposing your admin account whilst giving them access to my tailnet is the biggest selling point of this app.

**Comment by DentonGentry** [comment]
On the screen where you can click on an identity provider, look for the QR code link under the other buttons.

![Screenshot_20230604-071408](https://github.com/tailscale/tailscale/assets/1140756/9e7b0c3c-1cf3-472c-a67f-268899620f8d)

**Comment by mritunjaymusale** [comment]
it worked lol
additionally I would suggest you guys need to make the hint more obvious, as in when clicking the link a pop up should tell me to use this qr code from an already logged in device beyond that it works flawlessly

**Comment by DentonGentry** [comment]
We'll work on surfacing it more clearly.

**Comment by aadityabhatia** [comment]
Been using tailscale for a while and I have definitely done this before, but had to search the Internet for it. Even the [official documentation](https://tailscale.com/kb/1079/install-android) does not mention QR code. Also not sure there is a way to use auth keys at all.

More specific documentation will certain help!
