### ISSUE TITLE
Tyrannosarus Carp or Tyrannosaurus Carp?

### ISSUE THREAD

**Issue by DJRHails** [tailscale/tailscale#8269]
### What is the issue?

When rolling tailnet names I came across `tyrannosarus-carp.ts.net`, while I love the name, I did realise that tyrannosaurus is misspelled - a quick check of the wordlist confirms and shows that trex is duplicated anyway.

Wouldn't have filed an issue, but already did the work of double checking for my sanity if nothing else.

**Comment by catzkorn** [comment]
![giphy](https://github.com/tailscale/tailscale/assets/46385858/50198b13-c694-41c3-afdd-df3f15fc5404)
