### ISSUE TITLE
Android network stops working after going through subway

### ISSUE THREAD

**Issue by jglamine** [tailscale/tailscale#8274]
This is an odd one, but I'm able to consistently reproduce it and it seems like tailscale is the cause.

I have a Pixel 7 phone with tailscale set as the vpn. I'm not using an exit node. When I go though the subway and loose cellular connection, internet won't work once my phone re-connects to the cell tower. It shows full bars but web pages don't load. Rebooting the phone fixes the problem.

The odd thing is this only happens if I have tailscale enabled. If I disconnect from tailscale, going through subway tunnels works fine - it reconnects once I'm out of the tunnel and I don't need to reboot the phone.

**Comment by DentonGentry** [comment]
The issue template asks for information about the platform+OS and for a bugreport because without those, we have no hope of making progress on a diagnosis.

**Comment by danielzfranklin** [comment]
I've experience something similar. I filed a new issue so I'd get the bug report template: #8283

**Comment by jglamine** [comment]
Sorry about that, it didn't show me an issue template - maybe templates don't work on mobile? Here's a new issue using the template: https://github.com/tailscale/tailscale/issues/8312
