### ISSUE TITLE
Tailscale Exit node does not work with Oracle Linux/CentOS

### ISSUE THREAD

**Issue by lembq** [tailscale/tailscale#8276]
### What is the issue?

Oracle Linux 8 and CentOS 7 can not use the exit node functionality of tailscale. The previously mentioned two systems can set up a connection with the exit node (not using its exit node functionality), but using this node as exit node can cause undefined behavior. CentOS 7 tries to connect, without interruption it would probably try to connect forever. Oracle connects to the exit node but it does not have internet access through the exit node.  

### Steps to reproduce

Install Oracle Linux 8 and try to use the exit node functionality.
Command: sudo tailscale up --exit-node=... --exit-node-allow-lan-access=true --accept-dns=false --accept-routes --advertise-routes=... --login-server=...

### OS

Linux, CentOS

### OS version

Oracle 8

### Tailscale version

1.42.0

**Comment by DentonGentry** [comment]
Possibly related: https://github.com/tailscale/tailscale/issues/3310

If so, this may resolve the issue:
`sysctl -w net.ipv4.conf.eth0.rp_filter=2`
(replace "eth0" with the name of the LAN interface)

**Comment by lembq** [comment]
Thank you it solved our problem!
