### ISSUE TITLE
Configuring exit node conflicts with guestVM networking

### ISSUE THREAD

**Issue by johnnyfleet** [tailscale/tailscale#8279]
### What is the issue?

I have a set up where I have guest VMs running via QEMU with simple NAT network setup.  I noticed that when running tailscale normally that all the networking on the guest is uninterrupted. 

However, if I configure to go via an exit node (for example, when working away from my home/office and want to route back via home) I see the networking for the guest is blocked. 

### Steps to reproduce

Configure two machines for example: 
- LAPTOP is a device which will relocate. This will also be running guest VMs in question
- SERVER is a machine at home which will be set up as an exit node. 

1. Install Tailscale on both LAPTOP and SERVER. 
2. Configure SERVER as an exit node. 
3. Create a simple VM for testing via vagrant with the following simple vagrant file: 
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
end
```
4. Spin up the guest vm `vagrant up`
5. Log into VM `vagrant ssh` and perform a simple ping `ping www.google.com`
6. Confirm ping still successful. 
7. Connect tailscale on LAPTOP: `sudo tailscale up --exit-node=`
8. Confirm ping still successful.
9. Connect tailscale via exit-node on LAPTOP `sudo tailscale up --exit-node=<SERVER-TAILSCALE-IP>
10. Observe that pings now stop on guest VM. Unable to reach anything on network. 
11. Switch back to tailscale not via exit-node (or stop completely) `sudo tailscale up --exit-node=`
12. Confirm ping successful again.

This issue also appears to be true on a Windows 10 guest vm - but using this example for a quicker test to replcicate. 

### OS

Linux

### OS version

Manjaro

### Tailscale version

1.40.1-dev20230510

### Other software

Following instructions [here](https://tailscale.com/s/dns-fight) to install systemd-resolved as well as NetworkManager. 

I had the issue before and this change doesn't seem to have helped.  

### Bug report

BUG-46fbe76db11015205f3745a14274dbf490ec168808be5f237a9cc73c9820f363-20230606023606Z-d4f824565ff2f486

**Comment by DentonGentry** [comment]
I would suggest `sudo tailscale up --exit-node=______  --exit-node-allow-lan-access`

The exemplar use case for an exit node is when using a public wifi network like a coffee shop, where the LAN interface is untrusted. Tailscale blocks access to the LAN when the exit node is enabled.

If the LAN is actually safe, like one's home or office or something, `--exit-node-allow-lan-access` can be used.

Unfortunately I'm not sure if this will actually work since the interface to the vagrant VM won't be the interface with the default route. It is worth a try.

**Comment by johnnyfleet** [comment]
Thanks @DentonGentry - My intention was to have a scenario similar to the exemplar. I want to be in a coffee shop and run tailscale on the host to route out via an exit node with the local lan access disabled. 

I think I'm assuming that when applied by tailscale that the networking set up by vagrant automatically routes via tailscale network vs. other routes if all managed by networkManager/systemd?

**Comment by DentonGentry** [comment]
> I think I'm assuming that when applied by tailscale that the networking set up by vagrant automatically routes via tailscale network vs. other routes if all managed by networkManager/systemd?

No, it wouldn't. Tailscale installs a default route pointing to the exit node in an alternate table, and blocks access to other interfaces and bridge devices.

**Comment by johnnyfleet** [comment]
Ah right ok. So it sounds like it's working as advertised then.

Is there any means where I could configure to have other networks route via the tailscale network? 

Any documentation anyone could recommend I go down to look at?

Given the above I'll look to close this issue shortly as sounds like things working as expected, just my use case wanting a little more(which hopefully I can self configure with some help towards some docs)

**Comment by johnnyfleet** [comment]
Marking as closed based on above. I'll need to do some exploring to see if there is any way to generate what I want (guest VM networking routing through tailscale network when exit node is configured).
