### ISSUE TITLE
iOS Shortcuts: 'If' function treats 'Connected' smart variable as a number, preventing its use in conditional logic

### ISSUE THREAD

**Issue by Enstrayed** [tailscale/tailscale#8281]
### What is the issue?

Inside iOS Shortcuts, when Tailscale's 'Get Status' block is placed then passed to a 'If' block and the 'Connected' type is set, the 'If' block will treat the smart variable as only a number, which prevents it's usage, as the smart variable will only return 'Yes' or 'No'. Unfortunately, there isn't a way to override this and put text in the number field that just says 'Yes' or 'No'.

![2023-06-05%2022 27 47](https://github.com/tailscale/tailscale/assets/48845980/58485e54-ed8e-4df2-b813-09c60448cfff)

The expected scenario is that this smart variable can be treated as a Boolean, where the logic would be `if ( Connected == true ) { stuff to do }`. 

### Steps to reproduce

1. Create a new shortcut in the Shortcuts app
2. Insert Tailscale's 'Get Status' block
3. Insert a 'If' block with the smart variable set to the output of Tailscale's 'Get Status' block.
4. Choose 'is' as the operator
5. Observe how shortcuts asks for a number instead of True or False or just a keyboard input.

### OS

iOS

### OS version

iOS 16.5 (20F66)

### Tailscale version

1.42.0

### Bug report

BUG-37f73e9569969c7c069bba3b6ad9fa122d1cf1c1224607efe2cb5bd71476a681-20230606053938Z-64acdf95898e8d1b

**Comment by agottardo** [comment]
Thanks for the report @Enstrayed, I am investigating.

**Comment by agottardo** [comment]
Fixed in 1.49.191, now available on TestFlight. The fix will make it into 1.50 when it ships.
