### ISSUE TITLE
FR: Add Apple TV (tvOS) support

### ISSUE THREAD

**Issue by aofei** [tailscale/tailscale#8282]
With [NEPacketTunnelProvider](https://developer.apple.com/documentation/networkextension/nepackettunnelprovider) support in tvOS 17, it's time to bring Tailscale to Apple TV! 🎉

> ### tvOS enhancements
>
> #### VPN
> Now you can build virtual private network apps on Apple TV, making it easier for people and organizations to access content on their own private networks.
>
> -- https://developer.apple.com/whats-new/

**Comment by bradfitz** [comment]
cc @agottardo

**Comment by samlinville** [comment]
If you're interested in this feature, shoot me an email: sam [at] tailscale [dot] com

**Comment by 0dragosh** [comment]
Is this being worked on? Would love to test it out on TestFlight

**Comment by nmcc1212** [comment]
> Is this being worked on? Would love to test it out on TestFlight

you can, there is currently a tvos 17 compatible build on testflight

**Comment by zkuzmic** [comment]
> https://tailscale.com/kb/1083/install-unstable/

I just tried to join the tvOS TestFlight, but it looks like the link on that page actually goes to the iOS TestFlight.

I also won't rule out the possibility I'm doing something wrong 😅

**Comment by agottardo** [comment]
**[Apple TV, now with more Tailscale](https://tailscale.com/blog/apple-tv/)**

🎉 🎉 🎉

**Comment by traian658** [comment]
okay seems like is working now vpn on apple tv 
I need find a way to select only some apps to be routed in vpn not all apps with [Tailscale]

**Comment by nmcc1212** [comment]
> okay seems like is working now vpn on apple tv I need find a way to select only some apps to be routed in vpn not all apps with [Tailscale]

Why would you want to do that?

**Comment by traian658** [comment]
> > okay seems like is working now vpn on apple tv I need find a way to select only some apps to be routed in vpn not all apps with [Tailscale]
> 
> Why would you want to do that?

I encounter an issue where several apps are IP-blocked in my home country, necessitating the use of a VPN to access their content. However, there are specific apps that I prefer to use without a VPN to maintain optimal connection speeds, such as YouTube and Netflix. The constant need to switch my VPN on and off is quite inconvenient, and I believe there should be a more efficient solution. Is there a way to keep the VPN active and designate only certain apps to utilize it, while allowing others to connect directly? can also be usefull to access local home country cameras from your vacation home and many other functionalities.
