### ISSUE TITLE
"Disable mesh" setting, so most nodes can only see subnet relay nodes, not their peers

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#829]
Right now, every node can see any other node in your network, even if they are blocked by ACLs.

With #824 (Trim netmap based on ACLs), this will be mitigated, but some administrators would like more of a sledgehammer solution that looks more like a traditional VPN: route traffic only through subnet relay nodes, never directly peer-to-peer. In particular, this will let people keep usng their existing DLP, IDS, and SIEM systems to log all traffic in the corporate network, if they don't trust Tailscale's logging layers to be sufficient. It also makes it harder for domain members to see which other users and devices are in the network.

This will look like a simple domain-wide toggle. When set, it will have the effective of hiding all but subnet relays from any node which is not itself a subnet relay. Subnet relays will still need to see all nodes in their netmap.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2cxqp)

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/824 is implemented now, so the main problem has been mitigated. This bug will remain open to track the "get a bigger hammer" solution of disabling mesh altogether.

**Comment by apenwarr** [comment]
Not a lot of interest in this now that we have netmap trimming, so I'll close it.
