### ISSUE TITLE
Can't get correct hostname on iOS 17 & macOS 14.0 (Sonoma)

### ISSUE THREAD

**Issue by gps949** [tailscale/tailscale#8293]
### What is the issue?

Devices with iOS 17 will show hostname as "localhost".

### Steps to reproduce

Update the iPhone or iPad to the iOS/iPadOS 17.0 (21A5248v). 

### OS

iOS

### OS version

iOS 17.0

### Tailscale version

1.42.0

### Bug report

BUG-51cf48c05788f16c59f7713602df8a73f54d7c1d8138bc537e6aa31ef24561e4-20230607131330Z-c553a45d8afd3b25

**Comment by bradfitz** [comment]
@agottardo, I imagine iOS network extensions don't have access to hostname anymore? Or new entitlement or API? Or need to IPC it in from the GUI?

**Comment by agottardo** [comment]
thanks @DentonGentry! telemetry from this node indicates all data sources _but one_ now return either "localhost" or "iPhone". We need to pick the right one for devices running iOS 17+.

**Comment by davidchalifoux** [comment]
Here is a [Reddit thread](https://www.reddit.com/r/Tailscale/comments/143xosh/my_devices_were_given_new_localhost_hostnames/) of other people experiencing this issue including myself.

Interestingly, this appears to be happening to some people on Android as well.

**Comment by DentonGentry** [comment]
> Interestingly, this appears to be happening to some people on Android as well.

Android has a similar symptom but very different root cause: https://github.com/tailscale/corp/issues/8260

**Comment by agottardo** [comment]
I investigated this a bit today, at least on iOS. We'll most likely have to send down a value from the GUI to solve this.

**Comment by awsong** [comment]
See [this](https://developer.apple.com/forums/thread/731988)
It would be tough. Apple intentionally doesn't want us to get a meaningful (recognizable) hostname for privacy reasons.

**Comment by agottardo** [comment]
> See [this](https://developer.apple.com/forums/thread/731988) It would be tough. Apple intentionally doesn't want us to get a meaningful (recognizable) hostname for privacy reasons.

Yeah, we are aware of the limitation Apple introduced. We did find a workaround. However, we are still in the process of investigating its reliability. We are also considering alternative solutions, such as allowing iOS users to enter a hostname directly from the app, or generating one by using a combination of your username and device model.

For now as a workaround, you can set a hostname in the Tailscale admin console which will override the value the iOS client is providing. I will update this issue once we have a solution available for you to test as part of [our TestFlight builds](https://testflight.apple.com/join/tLcYLZJV).

**Comment by mattieb** [comment]
@gps949 

> After v1.46.0, macOS client has the same problem.

I’m not seeing it with 1.48.1 and Sonoma beta 6. One was an upgrade, another a clean install.

**Comment by gps949** [comment]
> @gps949
> 
> > After v1.46.0, macOS client has the same problem.
> 
> I’m not seeing it with 1.48.1 and Sonoma beta 6. One was an upgrade, another a clean install.

Yes. It's OK on macOS now. Thanks for your reply.

**Comment by qzydustin** [comment]
I met the same problem. My iPhone upgraded to iOS 17 today, and the tailscale console shows localhost-0 now.

**Comment by agottardo** [comment]
We are actively working on a number of fixes for this, but our options are limited given this is a restriction introduced by Apple. An easy workaround for now is to manually set your hostname in the admin console, so that the coordination server will ignore whatever value the iOS client is sending.

**Comment by mattieb** [comment]
Just wanted to report that, since version 1.49.307 hit TestFlight with the Device Name setting, I was able to use that to specify a name and then turn “auto-generate” back on in admin.

Out of curiosity, I uninstalled and reinstalled to see if I’d get prompted for a device name during onboarding (that’d be a nice feature!) and didn’t—but I did see that my iPad got a better default device name, in this case “ipad-pro-12-9-6th-gen-wifi”.

**Comment by megaroeny** [comment]
My knowledge is limited, but I installed the public macOS Sonoma beta yesterday and noticed that my Tailscale won't "connect' now. I uninstalled/reinstalled it, and it won't show the "Log in" menu option in the menu bar. Is this related?

![image](https://github.com/tailscale/tailscale/assets/1559447/c240b9a2-58f5-4987-a6e3-ea6a64ba3f6c)

**Comment by xfoxfu** [comment]
@megaroeny I do not think it is related. I also upgraded to Sonoma beta yesterday, and has seen Tailscale working properly.

**Comment by agottardo** [comment]
Tailscale 1.50 ([changelog](https://tailscale.com/changelog/#2023-09-25-client)) is rolling out on the App Store as we speak. It adds the ability for iOS 17+ users to customize the device name from the app settings. This is the best workaround we can offer, at least for now, given the restrictions imposed by Apple. Closing.

**Comment by temp140801** [comment]
Same issue here after installing iPadOS 17 public beta. Reported bug to Apple. Not fixed in iPadOS 17 final. Upgraded straight from iOS 16.7.4 to iOS 17 final, and no such issue on the phone. Besides Tailscale, [iSH](https://github.com/ish-app/ish) also shows incorrect hostname 'localhost' since iPadOS 17 public beta,.

**Comment by gustavohellwig** [comment]
Hi. This is still happening, showing localhost. Is there a solution or what should i do? Thank You!
