### ISSUE TITLE
Ephemeral nodes not being deleted in a timely fashion

### ISSUE THREAD

**Issue by colemickens** [tailscale/tailscale#8306]
### What are you trying to do?

My goal is to be slightly less overwhelmed when I view my Tailscale admin dashboard.

Right now I have quite a litany of ephemeral nodes, including some from yesterday. I'm not quite sure I understand the benefit of having such long expiration times - presumably the user is done with the node when it goes offline.

Particularly in cases where the key is re-used, it feels like the default could be much quicker to evict expired ephemeral nodes.

Making this configurable at key creation time would be a nice option.

### How should we solve this?

Allow the user to customize the eviction timeout for an ephemeral node at it's authkey creation time.

**Comment by DentonGentry** [comment]
Ephemeral nodes which use `tailscale logout` as their last step, or which use `tailscaled --state=mem:` and get a chance to shut down, should be deleted immediately.

Ephemeral nodes which do not get a chance to cleanly shut down should be deleted in about an hour.

Ephemeral nodes which stick around for days is not normal. If you can generate a `tailscale bugreport` from any of these ephemeral nodes, we can look into why they are not being deleted.

**Comment by colemickens** [comment]
I'll reprovision the key, ensure it's ephemeral and update here.

**Comment by colemickens** [comment]
Oh, the admin panel DOES list if the key is ephemeral, but only if it is...

![screenshot-1686205307](https://github.com/tailscale/tailscale/assets/327028/f262eab4-d725-4800-9f5d-9573a03442d4)

Really sorry about this, I guess I missed checking the box the first time around.
