### ISSUE TITLE
Tailscale daemon can't start up in WSL2

### ISSUE THREAD

**Issue by mmcc** [tailscale/tailscale#831]
**Describe the bug**
I used to be able to start up Tailscale in WSL2 by simply [manually starting the daemon](493). However, I came back to it today after a while, updated things, and now the daemon won't start at all.

 ```
mmcc@kickpuncher ~ sudo tailscaled
logtail started
Program starting: v1.1.540-gce66dfebd, Go 1.15-tsc099eea: []string{"tailscaled"}
logpolicy: using system state directory "/var/lib/tailscale"
3.4M/27.4M Starting userspace wireguard engine with tun device "tailscale0"
3.8M/27.4M CreateTUN ok.
4.0M/27.4M link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[***]} v4=true v6global=false}
4.1M/27.4M Creating wireguard device...
4.2M/27.4M Routine: event worker - started
4.2M/27.4M Interface set up
4.7M/27.4M UDP bind has been updated
4.8M/27.4M Creating router...
4.6M/27.4M router: dns: using dns.directManager
4.6M/27.4M Bringing wireguard device up...
4.6M/27.4M Bringing router up...
4.7M/27.4M Device closing
4.7M/27.4M Routine: event worker - stopped
logtail: dialed "log.tailscale.io:443" in 47ms
5.1M/28.4M [RATE LIMITED] %s
5.1M/28.4M wgengine.New: running "ip -6 rule add pref 5210 fwmark 0x80000 table main" failed: exit status 2
Error: Rule family not supported.
flushing log.
logger closing down
```

Running that same command on its own also errors out:

```
mmcc@kickpuncher ~ ip -6 rule add pref 5210 fwmark 0x80000 table main 
RTNETLINK answers: Operation not permitted
```

**To Reproduce**
1. Install Tailscale in Ubuntu 20 on WSL2
2. `sudo tailscaled` 

**Version information:**
 - OS: Ubuntu (running in WSL2)
 - OS version: Ubuntu 20.04.1 LTS
 - Tailscale version: 1.1.540-gce66dfebd

**Comment by bradfitz** [comment]
This seems like a dup of #562, so folding it into that one.

In general Microsoft has said elsewhere that it's their job to fix WSL to actually act like Linux, rather than every Linux program trying to work around their bugs. But we can keep #562 open at least for people to share notes. If there are easy workarounds, that's fine, but I don't want to spend too much time on it considering we have a Windows version of Tailscale anyway.
