### ISSUE TITLE
Getting a "tsnet: Executable not implemented for js" when running tsnet app in the browser (wasm)

### ISSUE THREAD

**Issue by drio** [tailscale/tailscale#8315]
### What is the issue?

I have a very simple tsnet app that runs correctly standalone but when I cross-compile it to wasm and run it in the browser I get the following js browser console error: `tsnet: Executable not implemented for js`. The error comes from the js code that loads the wasm bytecode (`console.log`):

```js
			writeSync(fd, buf) {
				outputBuf += decoder.decode(buf);
				const nl = outputBuf.lastIndexOf("\n");
				if (nl != -1) {
					console.log(outputBuf.substring(0, nl));
					outputBuf = outputBuf.substring(nl + 1);
				}
				return buf.length;
			},

```

### Steps to reproduce

Here is the makefile I use to copy the wasm js loader `wasm_exec.js` and to cross-compile the go code to wasm:

```Makefile
G=/opt/homebrew/bin/go

.PHONY: serve tidy glue clean
serve: glue
	cd cmd/server; go run main.go 

cmd/go.mod:
	cd cmd; go mod init "github.com/drio/wasm-hello"

tidy: cmd/go.mod
	cd cmd; go mod tidy

glue: assets/wasm_exec.js

assets/wasm_exec.js: assets/main.wasm tidy
	cp "$$(go env GOROOT)/misc/wasm/wasm_exec.js" $@

assets/main.wasm: tidy
	cd cmd/wasm/ ; GOOS=js GOARCH=wasm $(G) build -o  ../../$@

clean:
	rm -f assets/*.wasm cmd/go.* assets/wasm_exec.js
```

The tsnet code (the go code I xcompile to wasm):

```go
package main

import (
	"fmt"
	"log"
	"syscall/js"

	"tailscale.com/tsnet"
)

func main() {
	authKey := "tskey-auth-xxxxxxx"
	s := &tsnet.Server{
		Hostname:  "ts-hello",
		AuthKey:   authKey,
		Ephemeral: false,
	}
	defer s.Close()
	ln, err := s.Listen("tcp", ":80")
	if err != nil {
		log.Fatal(err)
	}
	defer ln.Close()

	report := func() js.Func {
		jsonFunc := js.FuncOf(func(this js.Value, args []js.Value) any {
			return "here we go!"
		})
		return jsonFunc
	}

	fmt.Println("Go Web Assembly (2)")
	js.Global().Set("drioHelloWasm", report())
	<-make(chan bool)
}
```

And here is the webserver that servers the assets to the browser:

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	fmt.Println("listening http://127.0.0.1:9090 ...")
	err := http.ListenAndServe(":9090", http.FileServer(http.Dir("../../assets")))
	if err != nil {
		fmt.Println("failed to start server", err)
		return
	}
}
```

### OS

macOS

### OS version

Ventura 13.4

### Tailscale version

1.42.0

**Comment by DentonGentry** [comment]
You could use https://github.com/tailscale/tailscale/tree/main/cmd/tsconnect as an example of what would need to be done.

https://github.com/tailscale/tailscale/tree/main/tsnet doesn't have any example apps set up for WASM.

**Comment by bradfitz** [comment]
I just hit this same issue for wasipi1/wasm. Will fix.

**Comment by drio** [comment]
@bradfitz Thank you for the fix.

I hit the following error (js console) when testing with your latest changes:

`tsnet: neither $XDG_CONFIG_HOME nor $HOME are defined`

**Comment by hatf0** [comment]
@drio If you're still interested in this, I got this to work via patching up tsnet some more. You can see my work here: https://github.com/hatf0/tailscale. 
<img width="941" alt="CleanShot 2023-11-13 at 16 23 56@2x" src="https://github.com/tailscale/tailscale/assets/15710074/c9e555ea-3976-4074-a889-f85ee3bd1e12">

**Comment by drio** [comment]
@hatf0 This is fantastic! Yes, I am still interested. I will check your repo, try it out and report back. Good work and thank you again!

**Comment by hatf0** [comment]
https://github.com/tailscale/tailscale/assets/15710074/0f52687b-3d1e-4cdb-98f9-f524a2df2130

Working on some real shenanigans over here with this new-found power...
