### ISSUE TITLE
FR: Allow `Authorization` header passthrough for kubernetes operator `auth-proxy`

### ISSUE THREAD

**Issue by samdyzon** [tailscale/tailscale#8317]
### What are you trying to do?

We are really keen to use the Kubernetes operator to allow access to internal services (non-public facing) in our cluster via Tailscale. We are also really excited about the prospect of using the operator to enable proxying requests to the k8s API (which are all explicitly not publicly accessible) with the same mechanism. However, we do not use Tailscale for managing AuthN/AuthZ to our k8s clusters - this is handled by an external OIDC provider that K8s can communicate with. The current implementation of the operator auth-proxy explicitly removes all Auth headers applied to the request by the client.

We are humbly requesting the ability to disable the stripping of client-provided auth headers during the request proxy, perhaps via an environment variable. This variable could be provided such that the default behaviour is the current behaviour, and the operator must explicitly be configured to allow it. This would allow us to utilise existing techniques for handling AuthN + AuthZ to k8s clusters, but also provide private connectivity to the k8s APIs.

### How should we solve this?

The logic for implementing this is trivial, a simple conditional check within the request handler [(tailscale/cmd/k8s-operator/proxy.go)](https://github.com/tailscale/tailscale/blob/f077b672e4a399f4dcafdfe4f15c75d5a580c7cb/cmd/k8s-operator/proxy.go#L77) to determine if request headers should be replaced. Passing the configuration down to the server is less trivial - I do not know enough about golang to propose how to get the required context into the request/response cycle.

### What is the impact of not solving this?

We, and anyone who has an established OIDC provider for their K8s cluster, would be unable to use the auth-proxy component of the k8s operator with their auth provider. This would mean that the use-case we have in mind for the k8s operator would no longer be viable.

The solution we would continue using is a "bastion host" on the same network as the cluster (not publicly accessible), running Tailscale and a reverse-proxy (Caddy) which forwards requests to our private services (private ingress controller) and the k8s API. This solution is less than ideal due to the fact that Caddy does not support SPDY, so we cannot run `kubectl exec ...` commands using the reverse-proxy (we have to SSH into the node and run these commands, which defeats the whole purpose of this design).

### Anything else?

I realise that the k8s operator #502 is still in early stages, but we are extremely excited to use it. The reverse proxy code here is really simple, so I can't imagine this proposal would require heavy engineering to accommodate. I also realize that as a third-party I may be missing some context about why this particular decision was made in the first place. Happy to provide more context as required. We are on the premium plan with ~20 users.

Cheers!

**Comment by DentonGentry** [comment]
I guess I don't understand why one would enable the proxy at all in this circumstance https://tailscale.com/kb/1236/kubernetes-operator/#enabling-an-auth-proxy

If the existing authentication mechanism is preferable, one doesn't have to use the Tailscale operator's auth proxy.

**Comment by samdyzon** [comment]
The value proposition for us is that we can enable access to the k8s API server over tailscale. The name `auth-proxy` is a bit of a mislead, because this service is a proxy to the k8s API - which is what we really want (sans the tailscale auth).

**Comment by maisem** [comment]
@samdyzon you should be able to expose the default kubernetes service over Tailscale using the `tailscale.com/expose=true` annotation. Does that not work for you?

**Comment by maisem** [comment]
You can also do something like this now as of [unstable-v1.49.121](https://hub.docker.com/layers/tailscale/k8s-operator/unstable-v1.49.121/images/sha256-c389cc3e383c6a383da83819cb9e90c91e1e97d70ed6899711fcf9961093fa1c?context=explore)
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-ts-ingress
  namespace: default
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kubernetes
      port:
        number: 443
  tls:
  - hosts:
    - kube-ts-ingress
```

**Comment by mayakacz** [comment]
This is now supported: https://tailscale.com/kb/1236/kubernetes-operator/#disabling-authentication-headers
