### ISSUE TITLE
Tailscale breaks Mullvad

### ISSUE THREAD

**Issue by edap** [tailscale/tailscale#8318]
### What is the issue?

After installing tailscale Mullvad stops to work.

### Steps to reproduce

- Install Mullvad VPN
- Double click on the icon and connect to the Mullvad VPN. Open a website in the browser, it works.
- Install tailscale
- tailscale up
- Mullvad stop to work, the app launches but you can't connect to any website

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.42.0

### Other software

Mullvad VPN  2023.3

**Comment by edap** [comment]
Also, I have added the following rules to nft, but this did not solve the issue:

```
table inet mullvad {
	chain input {
		iifname "tailscale*" accept
	}

	chain output {
		oifname "tailscale*" accept
	}
}

```

**Comment by DentonGentry** [comment]
Having multiple VPN products simultaneously active rarely works at all. They fight over every resource: routing table, firewall rules, etc.

For Mullvad specifically, where we think we understand the potential interactions well enough to be able to accommodate them, there is a separate issue in [#2880](https://github.com/tailscale/tailscale/issues/2880) which is more tractable. It wouldn't take the form of having both clients installed and trying to operate at the same time.

**Comment by bradfitz** [comment]
https://tailscale.com/blog/mullvad-integration/ launched today.

**Comment by edap** [comment]
you're the best ;)
