### ISSUE TITLE
FR: Support for Dynamic Routing with Hostnames in Tailscale

### ISSUE THREAD

**Issue by vsychov** [tailscale/tailscale#8334]
### What are you trying to do?

I want to implement dynamic routing to a specific website, such as `example.com`, through Tailscale. Currently, this requires resolving the IP address of `example.com` == `93.184.216.34` and adding it to `--advertise-routes=93.184.216.34/32`. However, the issue is that the IP of `example.com` may change over time, and it needs to be continually monitored, updating the value in `--advertise-routes`. 

### How should we solve this?

I propose to either add a new parameter `--advertise-hostname-routes` or use the `hostname` prefix in `--advertise-routes`, for instance: 
`--advertise-routes=hostname:example.com,10.10.0.0/24,10.11.0.0/24` (remember to also consider IPv6 addresses).

This might potentially cause problems with websites operating via Amazon CloudFront, where the IP list updates every 60 seconds. An example of such a "complex" website is `registry.terraform.io`.

But as an initial solution to this complex problem, I think it could be done like this.

### What is the impact of not solving this?

Implementing this feature is essential for the following reasons:

1. **Dynamic IP Addresses:** Given that many websites have dynamic IP addresses that change over time, it would be a considerable improvement to provide a more flexible solution that doesn't require continual manual updating of `--advertise-routes`.

2. **Ease of Use:** By allowing for the use of hostnames in place of IP addresses, the process becomes more user-friendly and intuitive, especially for those not as well-versed in networking.

In summary, this enhancement would boost Tailscale's functionality, making it more versatile and easier to use for a wider range of applications.

### Anything else?

Example of bash script that can do same (providing arguments to `--advertise-routes=`)
```bash
#!/bin/bash

DYNAMIC_DOMAINS="example.com"
RESOLVER="1.1.1.1"

is_ipv4_address() {
  [[ $1 =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]
}

is_ipv6_address() {
  [[ $1 =~ ^([0-9a-fA-F]{0,4}:){0,7}[0-9a-fA-F]{1,4}$ ]]
}

ROUTES=""
for domain in ${DYNAMIC_DOMAINS};
do
    for ipv4 in `dig +short $domain @$RESOLVER`
    do
        ROUTES="$ROUTES$(is_ipv4_address "$ipv4" && echo ,$ipv4/32 || echo '')"
    done

    for ipv6 in `dig +short -t AAAA $domain @$RESOLVER`
    do
        ROUTES="$ROUTES$(is_ipv6_address "$ipv6" && echo ,$ipv6/128 || echo '')"
    done
done

echo ${ROUTES:1}
```

**Comment by DentonGentry** [comment]
I suspect that https://github.com/tailscale/tailscale/issues/1748 would provide the desired functionality.

**Comment by vsychov** [comment]
@DentonGentry , thanks, #1748 definitely will solve this issue.
