### ISSUE TITLE
Tailscale crash and logout on MacOS (when low on disk space)

### ISSUE THREAD

**Issue by mrjware** [tailscale/tailscale#8349]
### What is the issue?

Tailscale with exit node in use to remote location logged out/disconnected when a high amount of data is transferred ( https transfer over 1GB and SMB transfer over 1GB).

MacOS 13.4 on 2020 Intel Air
App store install

### OS

macOS

### OS version

13.4

### Tailscale version

1.42.0

### Bug report

BUG-2e045e5404d69dc5c856946dd9fb8bf3386b681d6587c2fd7284bb79014a8cfc-20230614184134Z-354b414106c6d982

**Comment by maleadt** [comment]
I'm encountering this as well. Relevant bits in the log:

> runningboardd[399]: (RunningBoard) [com.apple.runningboard:connection] Received termination request from [osservice<com.apple.cache_delete(501)>:72597] on <RBSProcessPredicate <RBSProcessBundleIdentifierPredicate "io.tailscale.ipn.macos">> with context <RBSTerminateContext| code:0xBADDD15C explanation:CacheDeleteAppContainerCaches requesting termination assertion for io.tailscale.ipn.macos reportType:None maxTerminationResistance:NonInteractive attrs:[

**Comment by pmaene** [comment]
I seem to be running into similar issues where Tailscale on macOS started crashing quite often recently. The macOS application does seem to remain active, but I'm prompted to login. Specifically, it seems to be happening when running a remote nixOS build through Tailscale SSH.

**Comment by maleadt** [comment]
This keeps happening. I'm pretty sure it's related to low disk space; at least that's what other resources have to tell on `CacheDeleteAppContainerCaches`, and indeed I only ever notice Tailscale getting killed here when I'm low on disk space.

**Comment by pmaene** [comment]
> This keeps happening. I'm pretty sure it's related to low disk space; at least that's what other resources have to tell on `CacheDeleteAppContainerCaches`, and indeed I only ever notice Tailscale getting killed here when I'm low on disk space.

That actually matches my situation! Tailscale has been rock-solid again the past week or so, but I also cleared out a large chunk of disk space since.

**Comment by mrjware** [comment]
Same here, although I had several gig free, uninstalling boot camp to clear a huge chunk seems to have stopped the problem.

**Comment by matshch** [comment]
One of our users faced the same problem, CacheDelete (deleted) was killing Tailscale network extension in less than several minutes after Tailscale restart. The problem is gone after he freed up some disk space.

**Comment by kelivel** [comment]
Likely related to https://github.com/tailscale/tailscale/issues/8220
