### ISSUE TITLE
FR: Webhooks for Node status

### ISSUE THREAD

**Issue by CocoXiaoLong** [tailscale/tailscale#8351]
### What are you trying to do?

For network monitoring i'd suggest webhooks for `nodeConnected`, `nodeDisconnected`, `nodeDirtyDisconnected` and `nodeConnectedAfterDirtyDisconnect`
So for example if my server goes offline ungracefully, i know instantly, as well as knowing if my server comes back online thereafter.

### How should we solve this?

`nodeConnected`: A node comes online
`nodeDisconnected`: A node goes offline
`nodeDirtyDisconnect`: A node goes offline without properly logging off
`nodeConnectedAfterDirtyDisconnect`: A node comes online after a `nodeDirtyDisconnect`

**Comment by DentonGentry** [comment]
The difficulty we have with a feature like this is the mismatch in what people want versus what the coordination server knows.
- What people want: "notification when a node changes reachability from other nodes on the tailnet."
- What the coordination server knows: "whether the node is in contact with the coordination server."

The design of the system is such that the coordination server is not necessary for moment-to-moment operation of the tailnet. There are deployments where devices are out of contact for long periods of time, and nonetheless manage to set up Wireguard tunnels to peers during that entire time.

This feature request is tracked in https://github.com/tailscale/tailscale/issues/5967, closing as a duplicate.
