### ISSUE TITLE
Locking github issue prevents reactions from being submitted

### ISSUE THREAD

**Issue by abueide** [tailscale/tailscale#8374]
### What is the issue?

On [this issue ](https://github.com/tailscale/tailscale/issues/4221) Denton mentioned that reactions should be used instead of comments to express interest for feature prioritization. I whole-heartedly agree with this - but I think something that was missed was that locking the thread doesn't allow for reactions. I love tailscale and would love to have this feature - just wanted to make sure it isn't frozen in time :D

**Comment by bradfitz** [comment]
Unlocked.
