### ISSUE TITLE
[unexpected] lazy endpoint not created

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#838]
This looks like a bug in lazy endpoint creation. It's probably a release blocker for v1.2.0 since, if the pattern holds, it'll probably happen especially on long-running relaynodes with lots of peers who come and go.

Machines:
A - linux machine which has been running a long time, logid c47d60f6773d12ff1e11d1094a5af5225acc49da707582fe43dd56bbe8e71744
B - newly activated macOS 10.13 machine, logid ae0be91db1dbd956931c61949b61ae5c051b12f769f3c94a61bfa0f8e31dfbae

Steps:
- Ping from B (newly activated machine, which happens to be macOS 10.13) to A (machine which has been running a long time, Linux)

Expected:
- ping works right away

Actual:
- it didn't work, giving the following messages on A (corresponding to repeated disco message attempts on B)

```
10-20,04:34:19.075 8.4M/25.2M magicsock: [unexpected] lazy endpoint not created for [p4ssJ], d:800a49977e2f1224
10-20,04:34:19.075 8.4M/25.2M magicsock: DERP packet received from idle peer [p4ssJ]; created=false
10-20,04:34:19.075 8.4M/25.2M magicsock: DERP packet from unknown key: [p4ssJ]
```

(How is it both an idle peer *and* an unknown key?)

- after some idle time, something changed on A and it was able to start working. I think it might have been that I restarted Tailscale on my iPhone (unrelated to this test but on the same network), since the logs show a netmap update right before this:

```
10-20,04:43:01.324 8.9M/25.2M magicsock: got disco message from idle peer, starting lazy conf for [p4ssJ], d:800a49977e2f1224
10-20,04:43:01.411 8.9M/25.2M device.Reconfig: new peer [p4ssJ]
10-20,04:43:01.411 8.9M/25.2M [p4ssJ] - Starting...
```

**Comment by bradfitz** [comment]
You're running 1.1.487. This was already fixed in 1.1.540 (with tests!)

I was going to make control disable lazy configs for people running affected builds (via the `MapResponse.Debug.TrimWGConfig` experiment knob) but I didn't want to add more version parsing logic to control. That was part of my motivation for yesterday's `MapRequest.Version` changes.
