### ISSUE TITLE
ACL makes Windows client fail but works with Linux clients

### ISSUE THREAD

**Issue by dcgsteve** [tailscale/tailscale#8387]
### What is the issue?

I am the admin/owner of a TS net and if I use the following ACL then I can ping any IP on the network from my Windows machine

{"action": "accept", "src": ["*"], "dst": ["*:*"]},

However, if I change the ACL to the one below (which in theory should make no difference to me) then I can no longer access any IP :frowning:

{"action": "accept","src":["autogroup:owner", "autogroup:admin"],"dst":["*:*"]},

If I try from a Linux server to another Linux server the ACL works fine - it’s just from a Windows machine to other IP’s that doesn’t.

### Steps to reproduce

Amended the ACL online in the GUI as per above

### Are there any recent changes that introduced the issue?

Clean install across all servers

### OS

Linux, Windows

### OS version

Windows 11 Pro 22H2 (OS build 22621.1848) plus various Ubuntu 20.04/22.04 (all Ubuntu work)

### Tailscale version

1.42.0

### Other software

Nothing specific that I can think is relevant - and deliberately no third-party firewalls or anti-virus etc. (while I am testing anyway!)

### Bug report

BUG-0b872d87c842591b8a5d80ea096ba7cbe139d7e771767b804675a7ac537d8478-20230619195418Z-15d073137f3e94c4

**Comment by DentonGentry** [comment]
The machine which sent the bugreport is tagged: https://tailscale.com/kb/1068/acl-tags/

That means it is not owned by you as a User, it is owned by the Tag. Therefore ACLs like `autogroup:owner` and `autogroup:admin`, which apply to you as a User, will not include the Tagged machine.

**Comment by dcgsteve** [comment]
This was driving me nuts lol! Thanks for pointing me in the right place - I'd definitely misunderstood the use of Tags - they are much more than a simple grouping mechanism :)

Much appreciated.
