### ISSUE TITLE
macOS app no longer reports "wait for the admin to authorize your device" in the menu

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#840]
Steps:
- Get a domain that requires machine authorization
- Install v1.1 on macOS
- Log in successfully
- Get the "admin must authorize your device" web page

Expected:
- A popup notification and menu item entry to the effect "you can't do anything useful until the admin authorizes your computer"

Actual:
- Connect and Disconnect are dimmed out, but no message.

This definitely used to work. I don't know what happened to it or when.

**Comment by DentonGentry** [comment]
Adding to Onboarding Improvements project.

I think the plan now is somewhat different than the notification which used to be in the MacOS client.

**Comment by DentonGentry** [comment]
Closing this as obsolete, the machine approval functionality this used to pertain to is off by default and the plan for better onboarding guidance isn't going to do exactly this.
