### ISSUE TITLE
FR: support conditional access based on posture check

### ISSUE THREAD

**Issue by xtmw0007** [tailscale/tailscale#8402]
### What are you trying to do?

Trying to ensure laptop clients have antivirus and disk encryption prior to successful authentication.

### How should we solve this?

Allow conditional access and provide a script for adding this.

### What is the impact of not solving this?

Common ask for SOC2 and ISO audit certification

**Comment by knyar** [comment]
Hi @xtmw0007, last week we announced [device posture beta](https://tailscale.com/blog/device-posture) which allows you to restrict access based on device attributes.

If you have an existing system that already contains information that you'd like to use as part of your network policy, you can attach this information to your Tailscale devices as [custom attributes](https://tailscale.com/kb/1288/device-posture#set-custom-posture-attributes-via-api) and then use these attributes as part of your ACL.

We also built our [first integration](https://tailscale.com/kb/1289/crowdstrike-zta) in this space, allowing you to use zero trust scores reported by Crowdstrike Falcon as part of your ACLs.

Please let us know what you think.
