### ISSUE TITLE
extra-small not work

### ISSUE THREAD

**Issue by carlsue** [tailscale/tailscale#8406]
### What is the issue?

alpine:/go/tailscale# ./build_dist.sh --extra-small
flag provided but not defined: -extra-small
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
alpine:/go/tailscale#

### OS

Linux

### OS version

alpine 3.18.2

### Tailscale version

1.42.0

### Other software

golang 1.25

**Comment by willnorris** [comment]
you need to also specify the go package you want to build...

```
$ ./build_dist.sh --extra-small ./cmd/tailscaled
$ ./build_dist.sh --extra-small ./cmd/tailscale
```

**Comment by carlsue** [comment]
> you need to also specify the go package you want to build...
> 
> ```
> $ ./build_dist.sh --extra-small tailscale.com/cmd/tailscaled
> $ ./build_dist.sh --extra-small tailscale.com/cmd/tailscale
> ```
> 
> See more at https://github.com/tailscale/tailscale#building

thanks it is worked,but alpine can run, router can not:
[root@xxx:/tmp]#./tailscale version
./tailscale: line 1:ELF: not found
./tailscale: line 2: @ not found
./tailscale: line 3: : not found
./tailscale: line 4: ▒: not found
./tailscale: line 4: can't open u▒t▒: no such file
./tailscale: line 4:k▒▒▒▒▒t▒: not found
./tailscale: line 5: syntax error: unexpected ")"

**Comment by willnorris** [comment]
sounds like you're compiling on a different architecture?  You'd need to set GOOS and GOARCH environment variables appropriately to cross compile for the target OS and architecture.
