### ISSUE TITLE
docker版本的tailscale如何启用exit-node？？

### ISSUE THREAD

**Issue by kof8855** [tailscale/tailscale#8424]
### What is the issue?

docker版本的tailscale如何启用exit-node？？

**Comment by DentonGentry** [comment]
docker版本的tailscale如何启用exit-node？
== How does the docker version of tailscale enable exit-node

`--env TS_EXTRA_ARGS=--advertise-exit-node`

Ex:
`docker run -d --name=tailscaled -v /var/lib:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW --env TS_AUTHKEY=tskey-auth-ab1CDE2CNTRL-0123456789abcdef --env TS_EXTRA_ARGS=--advertise-exit-node tailscale/tailscale`

**Comment by kof8855** [comment]
非常感谢， 这个变量TS_EXTRA_ARGS=可以正常工作

Denton Gentry ***@***.***> 于2023年6月24日周六 00:03写道：

**Comment by DentonGentry** [comment]
非常感谢， 这个变量TS_EXTRA_ARGS=可以正常工作
Thanks a lot, this variable TS_EXTRA_ARGS= works fine

----

closing as fixed.
