### ISSUE TITLE
gocross's shell wrapper doesn't understand pre-release Go toolchains

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#8425]
```
> ./tool/go build ./cmd/hello
/home/dave/tail/oss/tool/../tool/gocross/gocross-wrapper.sh: line 36: [: 21rc2
time 2023-06-21T02:00:01Z: integer expression expected
```

Pre-release toolchains seem to have >1 line in their VERSION file, as well as an `rcN` suffix on the version number. Gocross's shell wrapper chokes on this when evaluating whether the cached toolchain is recent enough to build gocross.

**Comment by danderson** [comment]
Annoyingly, there doesn't seem to be a way to make sh/bash fail on an invalid numeric comparison. A test of `if [[ "20" -lt "21rc2" ]]` will make bash complain that `21rc2` is not a valid number in base 10, but it'll just make that arithmetic comparison evaluate to false and keep on trucking. Failure to do arithmetic comparison doesn't seem to be in scope for `errexit`, so... Ugh. Well, at least as it happens skipping the particular comparison in question when stuff goes wrong degrades mostly gracefully, it'll only matter in a corner case of machine config vs. toolchain config.

Anyway, I can fix this one instance, but apparently can't make the shell script stricter. Sigh.

**Comment by creachadair** [comment]
I suppose one kludge we could use is to pass the version through `tr -dC '0-9'`. That would at least ensure the result is either empty or numeric.
