### ISSUE TITLE
Improve download curl instructions

### ISSUE THREAD

**Issue by dorkmatt** [tailscale/tailscale#843]
The current documentation _(I couldn't find a public repo for the website)_  https://tailscale.com/download/linux/raspbian-buster documents curl without any command line arguments. The default curl call does a stdout download _progress bar_.

This is a confusing for users, as the sudo password prompt may occur prior to the stdout of curl download process and not by obvious that as password is required.

Suggest changing _(adjust as needed)_
```curl``` to instead ``` curl -fsSL```, this translates to
- Fail silently on HTTP errors
- Silent mode _(don't show download progress)_
- Show error
- Follow redirects

**Comment by danderson** [comment]
Thanks for the suggestion! I've made the change to the site source, it'll go live shortly.
