### ISSUE TITLE
tailscale 1.44.0 can't connect to other node 

### ISSUE THREAD

**Issue by linxd** [tailscale/tailscale#8431]
### What is the issue?

update to newest tailscale, (I have an headscale server), but can't  ping other tailscale client node. 

### Steps to reproduce

update to 1.44

### OS

Linux, Windows

### OS version

centos 7.6

### Tailscale version

1.44

### Other software

headscale 1.22

**Comment by DentonGentry** [comment]
There is literally nothing for us to go on here.
