### ISSUE TITLE
Clarify usage of RFC 6598 IP space with known limitations

### ISSUE THREAD

**Issue by dorkmatt** [tailscale/tailscale#844]
_Suggestion for appending KB article https://tailscale.com/kb/1033/ip-and-dns-addresses_

My home network already uses RFC 6598 _(100.64.0.0/10)_ IP space, this is to allow testing of various RFC 1918 devices and avoid any obvious conflicts _(curse of being a network engineer type)_. A prior network I helped build at an infamous desert week long event also used 6598 space too _(for a similar reason too, avoid 1918 misconfiguration issues)_. This problem will also likely manifest itself for another more traditional CG-NAT deployments too, see #530 and #320.

On a fresh Raspberry Pi OS install, where the wired eth0 port is receiving a 100.64.42.0/24 IP lease - Tailscale installs and operates fine. However the device no longer responds to local LAN traffic once the daemon is brought online. It took a bit of digging to realize that namespaces were being used, as the usual `ip route` output didn't show anything obvious on how the Tailscale routing was setup.

I would suggest more clarity that _"there be dragons"_ for those who attempt to use Tailscale in an existing RFC 6598 network. I didn't see this documented anywhere, only a mention of this is the space used - not incompatibilities.

**Comment by bradfitz** [comment]
FWIW, we'll be supporting IPv6 inside the tunnel (#19) soon-ish, with a Tailscale [ULA](https://en.wikipedia.org/wiki/Unique_local_address). (Unrelated to #18, which we already do: using IPv6 outside the tunnel)

We'll probably let you configure your network as v4-only (CGNAT range), v6-only, or mixed.

I assume you'd be happy with v6-only for internal Tailscale addresses? (IPv4+IPv6 would both be used as needed/available outside the tunnel)

**Comment by dorkmatt** [comment]
Hey @bradfitz _(long time!)_ Yes, a v6 only approach (of the internal Tailscale addresses) would be a perfect compromise. Thank you for considering v6 first class in 2020.
 
I wonder if a detection warning _(maybe in the admin dashboard?)_ could be added as part of this too, to notify users of a possible limitation in Tailscale v4 reachability when present on an existing CGNAT range?

My only wish for this ticket is an update in documentation to make other folks aware, not necessarily the feature request itself - though glad to hear a workaround is already planned.

**Comment by DentonGentry** [comment]
IPv6 support inside the tunnel was added in release 1.6, several months ago.

I think this bug can serve as sufficient documentation for other users searching for resolution, going to close it now.
