### ISSUE TITLE
Android: Tailscale Android client no longer compatible with Android TV

### ISSUE THREAD

**Issue by mlabrecquejessen-tailscale** [tailscale/tailscale#8450]
### What is the issue?

We list Android TV compatibility here: https://tailscale.com/kb/1079/install-android/

Multiple user reports indicate that the app is no longer found in the Google Play store for the device, and using another device to get to the listing grays out the device, saying "This item is not compatible with your device”.

Android TV support was added explicitly, and was working. Users report having downloaded it in the past, but can't now on a new device.

### OS

Android

**Comment by bradfitz** [comment]
I think @willnorris fixed this the other day. There were some new Google things to go click in the Play console.

**Comment by pr00se** [comment]
![Screenshot 2023-06-26 at 7 07 08 PM](https://github.com/tailscale/tailscale/assets/1776320/c0c61477-3789-48dd-9088-70ef4a66262d)

can confirm that Android TV devices show up in the listing today. thank you!

**Comment by bradfitz** [comment]
Sounds like this is fixed. Thanks for confirming, @pr00se.

**Comment by MATN92** [comment]
on Xiaomi MiBox S still nothing - can't install Android client
