### ISSUE TITLE
Unable to delete invited users when user and group sync enabled: "cannot_delete_user"

### ISSUE THREAD

**Issue by turbohoje** [tailscale/tailscale#8452]
### What is the issue?

We are able to use an invite link to add external users to our tailnet, however we are unable to delete or disable them once they are added.  

The error message `Provisioning from Okta. Deactivating users from Tailscale is disabled. To deactivate users, use the Okta admin console or disable provisioning` is displayed in the Users tab.  I expect this to be true for users that are created via Okta, but users that are invited into the tailnet should be removable or at the very least disable-able. 

Users are not able to leave the tailnet either.  `cannot_delete_user` error 500 is displayed.
![image (2)](https://github.com/tailscale/tailscale/assets/438210/15bff7c5-3729-483b-a1e0-228964780c3b)

### Steps to reproduce

1. Create a tailnet provision users via Okta
2. invite a non-org user via link
3. attempt to delete or disable the user.

### OS

macOS

### OS version

ventura 13.4

### Tailscale version

1.42.0

### Bug report

BUG-98b6d66939aef61840583cfe9c7a663326217ca2f7ff03d02c9d3a8f5479dd7f-20230627015328Z-0093a1611ffd0782

**Comment by DentonGentry** [comment]
User invite to a tailnet with user and group synchronization enabled.

**Comment by willnorris** [comment]
I believe this is one of the issues fixed by tailscale/corp#13321 (deployed July 18th)?

@turbohoje, could you confirm if this is still an issue?

**Comment by turbohoje** [comment]
thank you for checking, i am no longer using okta-tailscale group sync so i cannot
