### ISSUE TITLE
magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key

### ISSUE THREAD

**Issue by Cha0sJ** [tailscale/tailscale#8453]
### What is the issue?

>tailscale.exe up

tailscaled.exe:
xxxxxx
xxxxx
magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key

### Steps to reproduce

>tailscale.exe up [key]

### OS

Windows

### Tailscale version

1.44

**Comment by bradfitz** [comment]
On Windows you need to --unattended flag to up if you're not using the GUI.

**Comment by Cha0sJ** [comment]
> On Windows you need to --unattended flag to up if you're not using the GUI.

Awesome! Thank you for your help!!!
