### ISSUE TITLE
IPv6 NAT doesn't work in a containerized Tailscale

### ISSUE THREAD

**Issue by beenum22** [tailscale/tailscale#8454]
### What is the issue?

IPv6 connectivity doesn't work when the Tailscale configured as exit node is running in a container with `userspace networking` disabled. The required iptables rules for IPv6 NAT are missing and the container tried to forward the client traffic without SNATing the client IP. This results in failure as the underlying machine running the exit-node container is unaware of the client IP.
As part of the process to check support for IPv6 NAT in the Kernel, Tailscale first checks the `/proc/net/ip6_tables_names` file for `nat` keyword which doesn't work for nftables mode as mentioned [here](https://github.com/tailscale/tailscale/blob/1377618dbc92b98f7098fa173ef7696417bd7a43/wgengine/router/router_linux.go#L1702) and then tries to execute the `modprobe ip6table_nat` [command](https://github.com/tailscale/tailscale/blob/1377618dbc92b98f7098fa173ef7696417bd7a43/wgengine/router/router_linux.go#L1703). This command fails in a containerized/less privileged environments as it doesn't have the permission to load any Kernel modules. This failed check results in Tailscale to not add any iptables rules for IPv6 NAT even if the Kernel has `ip6table_nat` module enabled.

Apart from that, the check should only check for enabled Kernel modules rather than trying to enable the module.

### Steps to reproduce

Run a container using official Tailscale container image with `userspace-networking` disabled, `NET_ADMIN` Linux capability and exit-node configuration. Connect to this exit node and try to ping any public IPv6 endpoint.
Also check the IPv6 NAT iptables rules by executing `ip6tables -nvL -t nat` inside the container and it will be empty. 

### OS

Linux

### OS version

Oracle Linux Server 9.1

### Tailscale version

1.44.0

### Bug report

BUG-fdbd997c389a28cfc3c022251d416b2f59390a3e8c4e39d5d9b148004a85e960-20230627131824Z-d5db01a6dfe21f38

**Comment by Tomo-9925** [comment]
@beenum22, thank you for raising this issue.

I also encountered the same problem with Tailscale running on Proxmox LXC.
In my part of Japan, IPv6 communication is often more stable than IPv4 one.
So, I would be very happy if this problem can be fixed.

For other users who encounter this problem, I share a temporary solution that puts a command or shell script named modprobe in the PATH that returns only the normal exit.

**Comment by EloItsMee** [comment]
I have also discovered this issue whilst using Tailscale in an LXC container.

@Tomo-9925 what is your temp solution?

**Comment by irbekrm** [comment]
This should have been fixed in https://github.com/tailscale/tailscale/pull/11353

Latest unstable tags have the fix https://github.com/tailscale/tailscale/issues/11344#issuecomment-1981881445

Please let us know if you see further issues

**Comment by irbekrm** [comment]
Closing as should be fixed in #11353
