### ISSUE TITLE
with resolved set to use unbound on 127.0.0.1, tailscale dns manager sets Nameservers=[]

### ISSUE THREAD

**Issue by nothingmuch** [tailscale/tailscale#8468]
### What is the issue?

Upon switching to systemd-resolved, MagicDNS hosts no longer get resolved by the OS, but can be resolved with e.g. the host command using 100.100.100.100.

The `resolvectl` lists `tailscale0` interface as having no DNS servers configured, but it does have search domains, etc.

The OScfg values in the tailscale logs indicate `Nameservers=[]`, and IIUC tailscale is effectively clearing it. Since this is periodic, although using `resolvectl dns tailscale0 100.100.100.1000` restores magicdns resolution, it's only a temporary fix.

Before switching to networkd, and IIRC with resolved and split DNS, 100.100.100.100 was configured in resolvectl. I believe I was using network manager throughout, but it took me a few days to notice this issue.

I tried to find the origin of this empty slice, it appears to be coming from saved configuration, but I didn't have enough time to track down why it was set that way in the first place, and with a fresh state file I see the same behavior.

I'm using the following hacky workaround for now:

```diff
diff --git a/net/dns/manager.go b/net/dns/manager.go
index d1aa73ca..9b26f412 100644
--- a/net/dns/manager.go
+++ b/net/dns/manager.go
@@ -227,6 +227,10 @@ func (m *Manager) compileConfig(cfg Config) (rcfg resolver.Config, ocfg OSConfig
 		// Split DNS configuration requested, where all split domains
 		// go to the same resolvers. We can let the OS do it.
 		ocfg.Nameservers = toIPsOnly(cfg.singleResolverSet())
+		if len(ocfg.Nameservers) == 0 {
+			ocfg.Nameservers = []netip.Addr{cfg.serviceIP()}
+			m.logf("FIXME replaced Nameservers=[] with %+v", ocfg.Nameservers)
+		}
 		ocfg.MatchDomains = cfg.matchDomains()
 		return rcfg, ocfg, nil
 	}
```

### Steps to reproduce

This is extracted from my NixOS configuration:

```nix
  services.tailscale.enable = true;
  systemd.services.tailscaled.serviceConfig.Environment =
    [ "TS_NO_LOGS_NO_SUPPORT=true" ];

  # Disable wait online as it's causing trouble during nixos-rebuild switch
  # See: https://github.com/NixOS/nixpkgs/issues/180175
  systemd.services.NetworkManager-wait-online.enable = false;
  systemd.network.wait-online.ignoredInterfaces = [ "tailscale0" ];

  networking.networkmanager = {
    enable = true;
    dns = lib.mkForce "systemd-resolved";
  };

  networking.useNetworkd = true;

  services.resolved.enable = true; # i think this is what breaks tailscale DNS

  # This does not fix it, because it keeps getting cleared:
  systemd.network.networks."tailscale-dns" = {
    matchConfig.Name = "tailscale0";
    dns = [ "100.100.100.100" ]; # tailscale resets this to [], so it's effectively ignored
  };

  services.unbound.enable = true;

  systemd.network.networks."wlan-dns" = {
    matchConfig.Name = "wlp3s0";
    dns = [ "127.0.0.1" ]; # this is unbound
    dhcpV4Config.UseDNS = false;
    dhcpV6Config.UseDNS = false;
  };
```

With this setup, starting tailscaled and logging in works but MagicDNS does not.

### Are there any recent changes that introduced the issue?

Not that I'm aware of, I switched to resolved because I couldn't get a recursive resolver & mdns working together without it, although it broke MagicDNS that was much easier to work around.

### OS

Linux

### OS version

NixOS unstable

### Tailscale version

1.44.0, and also: 1.45.0-dev20230624   track: unstable (dev); frequent updates and bugs are likely   tailscale commit: 1f57088cbd7ea9c03033c4d4cd0285927e55861f-dirty   go version: go1.20rc3

### Other software

headscale v0.22.3, and nixos configuration above

### Bug report

TS_NO_LOGS_NO_SUPPORT=true is set...

**Comment by arag00rn** [comment]
Same issue here.

MacOS 13.4
Tailscale client 1.44.0

I'm using MagicDNS with Split DNS.

dns name resoltion on Windows clients is working fine.

**Comment by nothingmuch** [comment]
> I observe kind of the same behaviour on MacOS.
...
> Worked well until a few days (1.42.x and 1.44.x clients affected), now for some reason, applications regularly fails to resolve **SOME** DNS entries but MacOS host command always succeeds.

That sounds like a different issue than mine, for using the `host` command fails, unless I explicitly do e.g. `host $hostname 100.100.100.100`.

Resolving with `127.0.0.53` (systemd resolved) as the server also fails, which I believe the same as what `host` does with no server argument for my setup.

Resolved is behaving correctly it's just misconfigured to have an empty list of nameserers for `tailscale0` interface, instead of listing `100.100.100.100`.

**Comment by DentonGentry** [comment]
@sylr @arag00rn and @nothingmuch 
I see no indication that you are all seeing the same issue on four different platforms, the only similarity is that there is a problem with DNS. If you want us to look at the issues please file a separate issue or [contact support](https://tailscale.com/contact/support/).

**Comment by 999eagle** [comment]
I have the same issue as @nothingmuch where a `resolvectl status` doesn't list any nameservers for the `tailscale0` interface. Logs (with the hacky patch given in the OP applied):

```
Jul 15 13:35:15 yuno tailscaled[1656423]: dns: Set: {DefaultResolvers:[] Routes:{default.tailnet.999eagle.moe.:[]}+65arpa SearchDomains:[default.tailnet.999eagle.moe.] Hosts:3}
Jul 15 13:35:15 yuno tailscaled[1656423]: dns: FIXME replaced Nameservers=[] with [100.100.100.100]
Jul 15 13:35:15 yuno tailscaled[1656423]: dns: Resolvercfg: {Routes:{} Hosts:3 LocalDomains:[default.tailnet.999eagle.moe.]+65arpa}
Jul 15 13:35:15 yuno tailscaled[1656423]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[default.tailnet.999eagle.moe.] MatchDomains:[0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa. 100.100.in-addr.arpa. 101.100.i
n-addr.arpa. 102.100.in-addr.arpa. 103.100.in-addr.arpa. 104.100.in-addr.arpa. 105.100.in-addr.arpa. 106.100.in-addr.arpa. 107.100.in-addr.arpa. 108.100.in-addr.arpa. 109.100.in-addr.arpa. 110.100.in-addr.arpa.
 111.100.in-addr.arpa. 112.100.in-addr.arpa. 113.100.in-addr.arpa. 114.100.in-addr.arpa. 115.100.in-addr.arpa. 116.100.in-addr.arpa. 117.100.in-addr.arpa. 118.100.in-addr.arpa. 119.100.in-addr.arpa. 120.100.in-
addr.arpa. 121.100.in-addr.arpa. 122.100.in-addr.arpa. 123.100.in-addr.arpa. 124.100.in-addr.arpa. 125.100.in-addr.arpa. 126.100.in-addr.arpa. 127.100.in-addr.arpa. 64.100.in-addr.arpa. 65.100.in-addr.arpa. 66.
100.in-addr.arpa. 67.100.in-addr.arpa. 68.100.in-addr.arpa. 69.100.in-addr.arpa. 70.100.in-addr.arpa. 71.100.in-addr.arpa. 72.100.in-addr.arpa. 73.100.in-addr.arpa. 74.100.in-addr.arpa. 75.100.in-addr.arpa. 76.
100.in-addr.arpa. 77.100.in-addr.arpa. 78.100.in-addr.arpa. 79.100.in-addr.arpa. 80.100.in-addr.arpa. 81.100.in-addr.arpa. 82.100.in-addr.arpa. 83.100.in-addr.arpa. 84.100.in-addr.arpa. 85.100.in-addr.arpa. 86.
100.in-addr.arpa. 87.100.in-addr.arpa. 88.100.in-addr.arpa. 89.100.in-addr.arpa. 90.100.in-addr.arpa. 91.100.in-addr.arpa. 92.100.in-addr.arpa. 93.100.in-addr.arpa. 94.100.in-addr.arpa. 95.100.in-addr.arpa. 96.
100.in-addr.arpa. 97.100.in-addr.arpa. 98.100.in-addr.arpa. 99.100.in-addr.arpa. default.tailnet.999eagle.moe.] Hosts:[]}
```

**Comment by arag00rn** [comment]
> @sylr and @arag00rn I see no indication that you are all seeing the same issue on three different platforms, the only similarity is that there is a problem with DNS. If you want us to look at the issues please file a separate issue or [contact support](https://tailscale.com/contact/support/).

After further investigation my issue was due to a miss configuration of my zone resolver.

**Comment by vinszent** [comment]
I'm having this exact issue as well, same log output as @999eagle. I just have a vanilla NetworkManager + systemd-resolved and not using unbound or anything similar.

**Comment by DentonGentry** [comment]
> I just have a vanilla NetworkManager + systemd-resolved and not using unbound or anything similar.

I see no indication that you are seeing the same issue. If you want us to look at it please file a separate issue or [contact support](https://tailscale.com/contact/support/).
