### ISSUE TITLE
Windows: call it something other than "server mode"

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#847]
Early testing has suggested that people both inside and outside the company don't know what "server mode" means, and this will probably lead to ongoing confusion. We should rename the option before the first stable release that includes it, so we can avoid the additional confusion of renaming the option in the future.

There have been various proposed new names, but unfortunately we haven't really settled on a great one yet.

**Comment by bradfitz** [comment]
Decision after much discussion: "Run unattended".
