### ISSUE TITLE
Tailscale client fails to launch browser for interactive login - win server 2022

### ISSUE THREAD

**Issue by UnifiedArray** [tailscale/tailscale#8484]
### What is the issue?

Tailscale client fails to launch browser for interactive login
![c9rg91ue4v8b1](https://github.com/tailscale/tailscale/assets/93094074/3f38acdf-5528-4cbf-a2bf-442e6aba1a61)

I tried restarting/uninstalling(full uninstall w deletion of reg keys)/latest version update(1.44.0)/creating new user in AD... all to no avail

Some other similar issues perhaps: 
https://github.com/tailscale/tailscale/issues/8386
https://github.com/tailscale/tailscale/issues/2707
https://answers.microsoft.com/en-us/windows/forum/all/notifications-wont-open-when-i-click-on-them-on/5a8517a7-0550-4bb8-9415-0a2268b08618
https://forum.tailscale.com/t/win-10-log-in-button-not-doing-anything/655

### Steps to reproduce

Updated tailscale to 1.44 and after trying to login 

### Are there any recent changes that introduced the issue?

Update...but went back to previous versions...same issue

### OS

Windows

### OS version

Win Server 2022

### Tailscale version

1.44

### Other software

Disabled all other software/antivirus

### Bug report

BUG-d2c7121eef74acb7faead5c9c96dbcd88e8bb0710a39840d08898b2bd3518a33-20230629020817Z-6a95820dcd093db5

**Comment by UnifiedArray** [comment]
All good...we had 2 internet connections - Verizon & a cell provider as backup...the  Verizon one was cut and went down...as soon as I disabled the ethernet adapter from Verizon all was good...had no idea that can mess with the VPN...

**Comment by taziobaker** [comment]
If it is safe, try this:
[#8550](https://github.com/tailscale/tailscale/issues/#8550)
