### ISSUE TITLE
Improve Funnel UX with new foreground mode and improved CLI

### ISSUE THREAD

**Issue by soniaappasamy** [tailscale/tailscale#8489]
This is a parent issue.

We're looking at improving the CLI to conform to this space's existing mental models and established norms. We have also received feedback from users and internally regarding confusion and friction in 1) establishing a Funnel, 2) understanding the differences between Serve and Funnel, and 3) understanding when a Funnel is running and remembering to turn it off.

The CLI work aims to create a more straightforward set of commands for the typical case, starting an internet Funnel targeting a local web server.

In addition, we will introduce the concept of a foreground mode with two primary goals: 1) provide the user with feedback when the Funnel is established; 2) provide a log or TUI to view requests in real-time.

The foreground mode also establishes a typical pattern of closing the tunnel (Funnel or Serve) when the command exits, which addresses feedback and concerns that servers are left running in the background or general confusion about the state of Serve/Funnel.

CLI change design doc: https://docs.google.com/document/d/180hvH5D1l0381X4SdQYUKneRGMvfGP3irzb0Vuowgxk/edit
Linear: https://linear.app/tailscale/issue/ENG-2054/funnel-cli-evolution

```[tasklist]
- [ ] https://github.com/tailscale/tailscale/issues/9292
```

**Comment by tylersmalley** [comment]
This has shipped
