### ISSUE TITLE
MagicDNS server address is not pingable

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#849]
```
$ ping 100.100.100.100
PING 100.100.100.100 (100.100.100.100) 56(84) bytes of data.
^C
--- 100.100.100.100 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7004ms
```

We should add our ping responder to ICMP packets for port 53, but only when MagicDNS is enabled, in order to make diagnostics easier.

**Comment by DentonGentry** [comment]
May be questionable whether this should really be labeled with "dns", but the next time we open up MagicDNS for something like DNS-over-TLS support we should be able to address this at the same time.
