### ISSUE TITLE
IOS Connection Issues??

### ISSUE THREAD

**Issue by AVLNCH-PRO** [tailscale/tailscale#8499]
### What is the issue?

I have been trying to log into my network through the iPhone app and it continues to crash after I type in my account information.. The VPN says it is connected in settings, but I cant see anything in the app.  Its a super simple setup, not really running anything else, I have my two macs on the network and I'm just trying to connect my phone so I have access to the files on the computer at home form my phone.

### OS

iOS

### Bug report

Edited to remove authkey

**Comment by agottardo** [comment]
What version of iOS and Tailscale are you running? 

Have you tried uninstalling Tailscale, rebooting your device and reinstalling the app again?

**Comment by DentonGentry** [comment]
There isn't enough to go on in this issue. Please send a support ticket https://tailscale.com/contact/support/, they can look up the tailnet and look at telemetry.
