### ISSUE TITLE
Windows 7: in some cases, Tailscale icon is blank

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#850]
I think this happens when the backend fails to start. The icon is completely blank, which suggests we're probably choosing an invalid icon id:

![image](https://user-images.githubusercontent.com/20592/96837036-c95a3b00-1413-11eb-88bb-0e236174ca63.png)

I was able to reproduce this in 1.0.4 as well.

I'm guessing this bug appeared when we added light/dark mode support earlier. Since Windows 7 doesn't support those sorts of themes, it's possible our fallback mode is broken. I wasn't able to reproduce the missing icon on Windows 10 in either light or dark mode.

**Comment by apenwarr** [comment]
Oops, it turned out I was able to reproduce this in 0.100.0-107 also, by reproducing a backend crash using tailscale/corp#732. So the icon bug is older than 0.100.0-107.

**Comment by apenwarr** [comment]
Also happens in Windows 8.1, apparently.

**Comment by sailorfrag** [comment]
Confirmed this happens on both windows 7 and 8.1 when starting up. Once it connects to the backend it seems to set up a proper icon.

**Comment by bradfitz** [comment]
Looks like this is the problem:

```
func (ti *themedIcon) UpdateTrayIcon(state ipn.State, tray *walk.NotifyIcon) error {
        // We read the registry key to detect LightTheme or DarkTheme.                                                                                                                                                                           
        // Unfortunately, this flag is only set on Windows 10 and up, so for older                                                                                                                                                               
        // versions of Windows, we fallback to UnknownTheme, and show an icon that has                                                                                                                                                           
        // a background, so it can be visible on any color theme.                                                                                                                                                                                
        systemTheme := getSystemTheme()
        if state == ti.oldIconState && systemTheme == ti.oldSystemTheme {
                // If the system theme key and state haven't changed, don't make any                                                                                                                                                             
                // updates. This avoids flickering.                                                                                                                                                                                              
                return nil
        }
```

That fast exit path is firing at start-up when you're in dark mode (because the dark theme's value is 0.... unknown is 9). And ipn.NoState is also 0, so both sides of && are true and it never sets the icon.

The "old" value it should remember instead is the icon pointer.

On it, unless you already are.

**Comment by sailorfrag** [comment]
Yes, I have a patch now

**Comment by bradfitz** [comment]
Cool. All yours.
