### ISSUE TITLE
FR: Restrict access based on node's current geographic location

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#8506]
### What are you trying to do?

HS 14524

Add dynamic route/connection restrictions based on the node's current geo location. Example use case: A node can connect to an EU-based subnet router as long as they're in the EU, and should lose that access dynamically when they travel to and connect to Tailscale from the USA.

**Comment by attruv2023** [comment]
Any news?

**Comment by knyar** [comment]
Now when we have [device posture attributes](https://tailscale.com/kb/1288/device-posture#device-posture-attributes), we could expose the result of IP geolocation lookup for a node's public IP address as posture attribute(s). For anyone interested in this, we'd like to hear more details about your use cases:
1. What level of detail would you like to see? Just a country code? More granular details, like ASN or city name? 
2. We are unlikely to have resources to maintain our own IP geolocation database. Any preferences with respect to existing databases that we could use?
3. IP geolocation databases are known to have inaccuracies and mistakes. What would be the impact to your deployment when that happens? How would you like to be able to handle it?
