### ISSUE TITLE
issues use 100% proc time at one ubuntu 

### ISSUE THREAD

**Issue by attid** [tailscale/tailscale#8515]
### What is the issue?

issues use 100% proc time at one ubuntu what can i check  ?

![изображение](https://github.com/tailscale/tailscale/assets/93135385/286f4bf9-a947-400a-b70c-215c0ab19d1d)

netstat -natep say something strange 

![изображение](https://github.com/tailscale/tailscale/assets/93135385/da9e457b-5cca-44c0-972c-22c24f6739ef)

### OS

Linux

### OS version

Ubuntu 22.04.2 LTS

### Tailscale version

1.44.0

### Other software

nginx

### Bug report
BUG-ff0137d3e3b4c745b597cb0b3b76b8e4f31bac3dbcc6b1067181e9da77cbfe08-20230710151526Z-accce2cec6991a33

**Comment by DentonGentry** [comment]
The template asks for a `tailscale bugreport` because without it, we're unlikely to be able to diagnose anything. Please add a bugreport.

**Comment by attid** [comment]
> The template asks for a `tailscale bugreport` because without it, we're unlikely to be able to diagnose anything. Please add a bugreport.

BUG-ff0137d3e3b4c745b597cb0b3b76b8e4f31bac3dbcc6b1067181e9da77cbfe08-20230710151526Z-accce2cec6991a33

**Comment by bradfitz** [comment]
Dup of #10630 it seems.
