### ISSUE TITLE
Windows: tailscale-ipn backend puts log files in different places depending who starts it

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#852]
Steps:
- Install tailscale 1.1.556 on Windows 7 (or probably any version)
- Look for tailscale-service-*.txt 
- Find it in \windows\system32\config\systemprofile\appdata\local\tailscale\logs
- Stop the windows service
- Open an admin-mode command prompt
- Run `start /w tailscale-ipn.exe /subproc a`

Expected:
- Log file is in the same place as before

Actual:
- A log file is written to \users\ieuser (or some other currently-logged-in user) instead, even though we started it as an admin.

This will cause confusion during diagnostics (as it did for me in #851) when there are log files in both locations.

Since tailscale only runs in server mode as some kind of administrator, I think we should pick a location for the log just once (perhaps in the nsis installer) and write its location to the registry so that we don't lose track.

Since the log files are new in v1.1, I think this should be a blocker for the next stable release, so that we don't leave files lying around in unexpected places for people on the stable track.

**Comment by bradfitz** [comment]
This isn't a release blocker. Nobody but us do this, and our internal cmd/tswin already sets up the environment such that this doesn't happen.

**Comment by DentonGentry** [comment]
Fixed as a side-effect of moving to C:\ProgramData, log files are always in C:\ProgramData\Tailscale\Logs
