### ISSUE TITLE
System has two versions of tailscale installed

### ISSUE THREAD

**Issue by ElTarget** [tailscale/tailscale#8525]
### What is the issue?

I followed the instructions on the official website for installation, but it displayed 
‘Warning: client version "1.44.0-t5d008cd83-g6dac82fa0" != tailscaled server version "1.28.0-taabca3a4c"’.
![image](https://github.com/tailscale/tailscale/assets/41426791/db54a94e-bfec-4352-9533-3a1cf72833e0)
After replacing with version 1.28.0, it still shows as incompatible.
![image](https://github.com/tailscale/tailscale/assets/41426791/90f28194-788a-479d-8670-7b6f184e811f)

### Steps to reproduce

curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
sudo apt-get update
sudo apt-get install tailscale
sudo tailscale up

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

 Ubuntu 20.04.5 LTS

### Tailscale version

1.44.0/1.28.0

**Comment by DentonGentry** [comment]
> ‘Warning: client version "1.44.0-t5d008cd83-g6dac82fa0" != tailscaled server version "1.28.0-taabca3a4c"’.

You have two versions installed. `ps auxw | grep tailscaled` should show where the 1.28.0 version of `tailscaled` is coming from. It likely is not being started by systemd, or the update to 1.44 would have stopped the older version.
