### ISSUE TITLE
Windows 7 and 8.1: DNS server IP is set, but not DNS search domain

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#853]
Steps:
- Boot a Windows 7 or 8.1 VM
- Install Tailscale 1.1.556
- Log in
- Make sure a corp DNS IP is set, as well as a DNS search domain, and MagicDNS is checked, in the admin panel
- ping x.tailscale.com.beta.tailscale.net
- it works
- ping x

Expected:
- it automatically looks up x.tailscale.com.beta.tailscale.net because tailscale.com.beta.tailscale.net is a search suffix.

Actual:
- That works in Windows 10, but not Windows 8.1 or Windows 7.
- Non-MagicDNS search domains in the corp DNS config also don't work in Windows 7/8.1. For example, 'ping log' does not automatically expand to log.tailscale.com. It does on Windows 10.

**Comment by apenwarr** [comment]
Hmm, I was also able to reproduce probably-related bugs on Windows 10.

Steps:
- set corp DNS domain to include tailscale.com
- ping log - it works, as expected (log.tailscale.com)
- Shift-Right-Click menu on the Tailscale icon, and disable corp DNS
- ping log - it still works, but shouldn't!  -- BUG1
- Right-Click menu and Disconnect
- ping log - now it doesn't work, as expected.
- Re-connect
- ping log - still doesn't work, as expected (corp DNS is still disabled in the menu)
- Shift-Right-Click and enable corp DNS
- ping log - still doesn't work! -- BUG2
- disconnect and then reconnect - that doesn't fix it either
- restart the Tailscale client - that doesn't fix it either
- restart the Tailscale service - that fixes it.

By comparison, DNS search domains don't seem to work *at all* in 1.0.4. or 0.100.0-107. I tested releases all the way back to 0.97 and couldn't get it to work. Maybe they never did, and only DNS server IPs were working on Windows. Customers may have worked around it by forcing the DNS settings globally in their windows configs, if they cared.

Anyway, MagicDNS needs DNS search domains to work reliably. I suspect the Windows 10 problem may be some kind of race condition, and that race condition is just triggering more reliably on Windows 7 and 8.1, so I'm considering them the same bug for now.

**Comment by apenwarr** [comment]
Here's what the adapter DNS settings look like when things are working correctly:
![image](https://user-images.githubusercontent.com/20592/96852256-ea785700-1426-11eb-9983-dac8825e101a.png)

and when it's broken:
![image](https://user-images.githubusercontent.com/20592/96852421-1bf12280-1427-11eb-8adc-8e2cde72b43d.png)

**Comment by danderson** [comment]
Debugging notes: rewrote the DNS implementation on Windows to be much simpler. Now when toggling corpdns off `ipconfig /all` says that DNS configuration got removed, and names stop resolving as expected.

Toggling corpdns back on, `ipconfig /all` shows the DNS configuration getting restored correctly. However, once restored I still can't resolve anything, even though based on ipconfig we've told it the right things :/

**Comment by bradfitz** [comment]
Do we need to do something to poke windows into noticing those registry values were updated?

**Comment by danderson** [comment]
We don't seem to need it on the first couple rounds of configuration, but that's what I suspect, yes. My guess is that other bringup events cause windows to notice the configuration. I wish there were a way to ask it what its effective config is.

**Comment by danderson** [comment]
I seem to be able to get racy results in both directions: sometimes, removing our DNS configuration isn't noticed, and sometimes adding isn't noticed.

In both cases, running `ipconfig /registerdns` as administrator makes windows notice changes. However, it also takes a couple seconds to run, and its output suggests that it's doing something completely different which happens to trigger the refresh we actually want. Digging.

**Comment by danderson** [comment]
registerdns's actual purpose is to update the host's DNS records in an Active Directory setup, which seems to confirm that whatever it's doing to the DNS config is happening incidentally.

**Comment by danderson** [comment]
Also checked that `ipconfig /flushdns`, another incantation recommended without justification in various windows forums, is not sufficient. `ipconfig /renew` (which renews the DHCP lease of the main network adapter) is sufficient to resync the DNS state. Allegedly, `ipconfig /renew` is a subset of what `ipconfig /registerdns` does.

**Comment by bradfitz** [comment]
If we have to shell out to programs, why not just run `netsh` at that point?

**Comment by bradfitz** [comment]
(That is, and avoiding all the registry shenanigans.)

**Comment by danderson** [comment]
According to various sources, including https://stackoverflow.com/questions/55369254/changes-to-the-registry-do-not-take-effect , the fundamental thing that needs to happen is a call to `DhcpNotifyConfigChange`, which is an undocumented function in some DLL. Despite the name, it appears to force Windows to notice that adapter settings have changed, and do the right thing with them.

So, our choices are call the undocumented API that seemingly everyone calls (how do you invoke a DLL function from Go?), or as you say, use netsh to control adapter settings.

**Comment by danderson** [comment]
Separate wrinkle: `The Netsh utility has no command to set or to change the domain suffix search list.`

Sigh.

**Comment by danderson** [comment]
Put out a PR with the DNS manager rewrite at least, which makes it reliably set/clear DNS settings per `ipconfig /all`. I also threw in `ipconfig /registerdns`, because without invoking undocumented APIs that's the thing that most reliably causes Windows to notice DNS settings. With those changes, DNS settings appear to toggle correctly through the various permutations I've tried.

**Comment by bradfitz** [comment]
> how do you invoke a DLL function from Go?

Our code is full of them. git grep LazyDLL

**Comment by apenwarr** [comment]
The above PR works on Windows 10 and fixes the problems with disabling then re-enabling the corpdns flag. This makes it at least as good as on v1.0.5, which makes it non-blocking for our v1.2.0 release.

However, it doesn't fix the installation of DNS resolvers on Windows 7, so I'll reopen.

**Comment by danderson** [comment]
Drat. I'll grab a 7 VM and figure it out.

**Comment by alexbrainman** [comment]
Another link to `DhcpNotifyConfigChange`

https://www.codeproject.com/Articles/20639/Setting-DNS-using-iphelp-and-register-DhcpNotifyCo

(I googled for it). So it works for some people. Note the article is only 13 years old. But I would not be surprised if his programs still works on Windows 10.

And @bradfitz is correct. It is not difficult to call DLL function like `DhcpNotifyConfigChange`. Let me know, if you want me to write Go function that calls `DhcpNotifyConfigChange`.

Alex

**Comment by rosszurowski** [comment]
Had a user [report something similar on Windows 10](https://forum.tailscale.com/t/internal-name-resolution/220/11), but just with the name servers. They had the same left and middle screenshot as the top set in [Avery's comment](https://github.com/tailscale/tailscale/issues/853#issuecomment-714360917), but the final screenshot was missing the name servers.

Might be unrelated, but posting here as a possible report.

**Comment by danderson** [comment]
I think this is fixed? I tested the brand new DNS manager code on Windows 7, and search domains worked as advertised.
