### ISSUE TITLE
Tailscale isn't routing traffic past exit node

### ISSUE THREAD

**Issue by Tanchwa** [tailscale/tailscale#8533]
### What is the issue?

I cannot for the life of me get Tailscale exit node to route traffic past itself. I have an exit node on an Ubuntu 22.04.2 LTS box running as an exit node. Other devices on the tailnet can connenct to the exit node and other devices on the tailnet, but nothing past that. 
It is also advertising the local 192.168.0.0/16 LAN, but those are not connecting either. 

### Steps to reproduce

Installed Tailscale 1.44.0 on all devices (android, windows, linux machine) 
added the necessary ipv4 forwarding rules for the kernel module using the commands 
```echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
sudo sysctl -p /etc/sysctl.d/99-tailscale.conf```

ran `tailscale up --advertise-exit-node --advertise-routes=192.168.0.0/16`
and enabled the node in the admin console to become an exit node and advertise the routes, and allowed the various devices to use the exit node as an exit node. 

A traceroute from my devices to google.com shows it hits the exit node at its tailnet address, and then nothing. I can SSH into the exit node and ping google from there, but cannot do it directly from the device. 

### Are there any recent changes that introduced the issue?

None 

### OS

Linux, Windows, Android

### OS version

_No response_

### Tailscale version

1.44.0

### Other software

the only other configuration changes that I've made were for running microk8s on my server. This included turning on ip forwarding for that service, as well as a few custom UFW rules that it added for the calico CNI

Anywhere on vxlan.calico   ALLOW       Anywhere
Anywhere on cali+          ALLOW       Anywhere
22 on tailscale0           ALLOW       Anywhere
Nginx Full (v6)            ALLOW       Anywhere (v6)
Anywhere (v6) on vxlan.calico ALLOW       Anywhere (v6)
Anywhere (v6) on cali+     ALLOW       Anywhere (v6)

Anywhere                   ALLOW OUT   Anywhere on vxlan.calico
Anywhere                   ALLOW OUT   Anywhere on cali+
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on vxlan.calico
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on cali+

### Bug report

BUG-100e7a780bd3dcf776db7d4214af69c0294a3f737fd2a902c6a65c67b8f73559-20230705002154Z-c7ea6cde08699a47

**Comment by DentonGentry** [comment]
Possibly related: https://github.com/tailscale/tailscale/issues/3310, if Calico set that.

If so, this may resolve the issue:
sysctl -w net.ipv4.conf.eth0.rp_filter=2
(replace "eth0" with the name of the LAN interface)

**Comment by Tanchwa** [comment]
That's a no go. Are there any kernel parameters in particular you need to see?

**Comment by Tanchwa** [comment]
I tried adding the UFW rules someone used in issue #4917
```ufw allow in on tailscale0 to any
ufw allow out on tailscale0 to any
```
still nothing.

**Comment by Tanchwa** [comment]
Manually adding the routing rules did resolve, which means this issue is the same as #4917

**Comment by knyar** [comment]
> Manually adding the routing rules did resolve, which means this issue is the same as https://github.com/tailscale/tailscale/issues/4917

I am closing this one to avoid duplicates. Thank you!
