### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by yanxke** [tailscale/tailscale#8538]
### What is the issue?

It's showing about 150% usage on Ubuntu Jammy, Tailscale 1.44.0

### Are there any recent changes that introduced the issue?

Might be related to Magic DNS.  The high CPU issue appeared after I enabled it and disappeared after I disabled it.

### OS

Linux

### OS version

Jammy

### Tailscale version

1.44.0

**Comment by bradfitz** [comment]
Not much information to go on here. We might have to close this as non-actionable if there are no clues or repros or profiles or crashes or logs, etc.

A `tailscale bugreport` when it's doing it would help.

What's your DNS configuration on your machine? systemd-resolved, resolvconf, NetworkManager, other?

**Comment by yanxke** [comment]
BUG-5e74705aeb7a02c6e3c99f85836642824bc91b283822398b24eed13c15216373-20230707022848Z-638eccba184ac275

This is the default install of Ubuntu Jammy.  Not sure what the DNS configuration is.  How do I get profiles, logs, etc.?

**Comment by darcien** [comment]
I have a similar issue on:
- NixOS (22.11) running on a DO droplet
- Tailscale version: 1.42.0

Bug report, second one use --diagnose:
- BUG-7c2cf78f9375c41b9a50ef4249c4ed2af698d9069306e3bf9a8620ae25b30317-20230707174128Z-9cf94cda196c9158
- BUG-7c2cf78f9375c41b9a50ef4249c4ed2af698d9069306e3bf9a8620ae25b30317-20230707184411Z-5df822bf4d653242

DNS configured using resolveconf, `cat /etc/resolv.conf` output:
```
# Generated by resolvconf
search capybara-panga.ts.net
nameserver 100.100.100.100
options edns0
```

tailscaled runs with systemd on mine, partial `sudo systemctl status tailscaled` output:
```
● tailscaled.service - Tailscale node agent
     Loaded: loaded (/etc/systemd/system/tailscaled.service; enabled; preset: enabled)
    Drop-In: /nix/store/i88g1q21yn3bj0rh6lngfhpqdpkv0q7d-system-units/tailscaled.service.d
             └─overrides.conf
     Active: active (running) since Fri 2023-07-07 18:30:38 UTC; 16min ago
       Docs: https://tailscale.com/kb/
   Main PID: 2034 (.tailscaled-wra)
     Status: "Connected; darcien@github; 100.98.3.85 fd7a:115c:a1e0:ab12:4843:cd96:6262:355"
         IP: 784.5M in, 564.7M out
         IO: 0B read, 40.0K written
      Tasks: 11 (limit: 2361)
     Memory: 78.2M
        CPU: 10min 3.158s
     CGroup: /system.slice/tailscaled.service
             └─2034 /nix/store/jkrilvc6k61bnf99gzhjx6a60x4jwaa1-tailscale-1.42.0/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641 --tun tailscale0

...
```

I've attached the full service log with `journalctl -u tailscaled >> tailscaled_full.log`:
[tailscaled_full.log](https://github.com/tailscale/tailscale/files/11985064/tailscaled_full.log)

There's a lot of udp connection refused error, which looks suspicious:
```log
Jul 06 15:09:40 shigure tailscaled[49418]: dns udp read: read udp 100.100.100.100:53: connection was refused
Jul 06 15:10:18 shigure tailscaled[49418]: dns udp read: read udp 100.100.100.100:53: connection was refused
Jul 06 15:28:55 shigure tailscaled[49418]: dns udp read: read udp 100.100.100.100:53: connection was refused
Jul 06 15:30:33 shigure tailscaled[49418]: dns udp read: read udp 100.100.100.100:53: connection was refused
```

Also, I doubt this will help that much but here's my [NixOS networking config](https://github.com/darcien/nixos-config/blob/f18b466756f0d43bd2f7c3717a74fabf9b0cf71c/nixos/networking.nix)

Please do tell me if any additional infos are needed.

**Comment by DentonGentry** [comment]
Moved @darcien 's issue to https://github.com/tailscale/tailscale/issues/8563

**Comment by DentonGentry** [comment]
Around the time of the bugreport:
`2023-07-07 02:26:27.71983937 +0000 UTC: dns: Resolvercfg: {Routes:{.:[1.1.1.1 1.0.0.1 127.0.0.53] ts.net.:[199.247.155.53 2620:111:8007::53]} Hosts:14 LocalDomains:[tailad37d.ts.net.]+65arpa}`

127.0.0.53 is the address generally used by systemd-resolved. That 127.0.0.53 was sent down as an upstream DNS server likely resulted in a loop:
- `systemd-resolved` likely read in 100.100.100.100 from `/etc/resolv.conf` to forward its queries to
- 100.100.100.100 would forward queries to 127.0.0.53 back to `systemd-resolved`

So we'll need to figure out why 127.0.0.53 was sent as an upstream DNS resolver.

**Comment by bluet** [comment]
Do you have systemd-resolved on your system? When tailscale's consuming lots of CPU on my laptop, systemd-resolved is getting busy, too. https://github.com/tailscale/tailscale/issues/10630

**Comment by bradfitz** [comment]
Closing as likely dup of https://github.com/tailscale/tailscale/issues/8563 / https://github.com/tailscale/tailscale/issues/10630
