### ISSUE TITLE
Problems accessing a Windows machine using ping and Remote Desktop

### ISSUE THREAD

**Issue by vsajip** [tailscale/tailscale#854]
From #454:
> If anybody continues to have Windows issues with 1.1.432+ that's not the one ping issue, please file a separate bug.

I'm running 1.1.556 on Windows 7. Tailscale has added a firewall rule for incoming requests (all ports allowed when connecting to the machine's Tailscale IP) but I still can't access the machine using either ping or Remote Desktop to that IP.

The target machine responds to ping and Remote Desktop access via the local network IP without any issue. When accessing via the Tailscale IP, after a short pause I get the "machine is offline or doesn't accept remote connections" dialog box.

Setting the "Allow edge traversal" on the rule made no difference.

**Version information:**

client - Laptop, Windows 8.1, running Tailscale 1.1.556.
target - Desktop, Windows 7 Service Pack 1, running Tailscale 1.1.556

I also tried accessing the same machine from a Windows 10 client running Tailscale 1.0.4 - that also failed.

**Comment by w0rkrb** [comment]
Hi vsajip, I've had similar issues on Windows 10 machines. I found that I needed to go into the advanced firewall settings and allow the Tailscale executables ( see screenshot ). I don't have a Windows 7 machine around to test with but expect something similar.
![image](https://user-images.githubusercontent.com/25584634/98229930-74a9da80-1f52-11eb-96d2-751e7bbd548a.png)

**Comment by bradfitz** [comment]
@vsajip, could you try again with Tailscale 1.2.1?

**Comment by vsajip** [comment]
OK, ping works for me with Tailscale 1.2.9 on Windows 7, 8 and 10 machines as destinations from both Windows and Linux client machines. Remote Desktop is still not working, but that could be due to other reasons so I'll close this issue. Thanks!
