### ISSUE TITLE
Support Ubuntu 20.10 Groovy

### ISSUE THREAD

**Issue by artis3n** [tailscale/tailscale#855]
**Is your feature request related to a problem? Please describe.**

Didn't see an issue yet so figured I'd create this for tracking purposes - please add support for Ubuntu 20.10.

**Describe the solution you'd like**

Following the docs for 19.10 and 20.04, I am pretty sure the only thing that is needed is to get a `groovy.gpg` key and groovy repository set up -

```bash
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/groovy.gpg | sudo apt-key add -
curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/groovy.list | sudo tee /etc/apt/sources.list.d/tailscale.list
```

**Describe alternatives you've considered**

Being patient

**Comment by danderson** [comment]
Thanks for the report! I simply missed that Groovy had been released :) The 20.04 package should work fine in the meantime, but I'll get a groovy repo set up.

**Comment by artis3n** [comment]
Yeah, no rush - was going to add it to the Ansible role and realized it's only been out for half a minute, might as well throw up a ticket.

**Comment by artis3n** [comment]
Looks to be set up now - https://github.com/artis3n/ansible-role-tailscale/runs/1334378957?check_suite_focus=true#step:9:8

**Comment by danderson** [comment]
Yes, sorry - I added a groovy repo while I was doing other work on the package server, and forgot to follow up. Should be all good now!

**Comment by Sinderan** [comment]
20.10 (Groovy) is still not listed on the download page of the website. I had to look it up here on github to confirm there was a repo.
