### ISSUE TITLE
Hide machines/instances from tailscale status (trim netmap) if you are not allowed to access them

### ISSUE THREAD

**Issue by bramevo** [tailscale/tailscale#856]
**Is your feature request related to a problem? Please describe.**

We use Tailscale for multiple use cases which we want to keep separated. We can do this using ACLs, to prevent that a machine of one group can connect to another machine. But apparently they still show up using "tailscale status". On the linux servers, this is an issue.

**Describe the solution you'd like**

Hide the clients from the list which do not have access to this machine and the machine itself cannot access.

**Describe alternatives you've considered**

Do not think that there is an alternative. Currently a blocking issue for us. (Privacy leakage)

**Comment by bradfitz** [comment]
We plan to do this soon-ish. We deployed some related work today, to send each node only the packet filters they need, not packet filters that any node in the network might need.

**Comment by bramevo** [comment]
@bradfitz That's good to hear! As it is currently a blocker for us as we want to use Tailscale to access VMs which are managed by our customers. And it's a big no-no that customers can see VMs from another customers.

But we want to support your neat product so maybe we can already use it for a single customer for now.

**Comment by bradfitz** [comment]
This is now done and deployed, but only enabled for our domain as a test. We confirm it's working, though. We'll start rolling it out to everybody soon.

**Comment by bradfitz** [comment]
@danderson, @crawshaw, I think this is ready to turn on for everybody now?

**Comment by bramevo** [comment]
I'm open to do some additional validation if needed.

**Comment by bradfitz** [comment]
If you set environment variable `TS_DEBUG_CONTROL_FLAGS=minimize-netmap` for the tailscaled server process then it'll turn it on for just your one node.

On Linux, you can add that to /etc/default/tailscaled and `sudo systemctl restart tailscaled`.

**Comment by bramevo** [comment]
> If you set environment variable `TS_DEBUG_CONTROL_FLAGS=minimize-netmap` for the tailscaled server process then it'll turn it on for just your one node.
> 
> On Linux, you can add that to /etc/default/tailscaled and `sudo systemctl restart tailscaled`.

Validated it and seems that it has some effect. Although the client is still able to see every machine that is able to connect to that single machine, even though that client cannot access those machines. But still hides machines from other clients so that's already a big improvement.

Will it be possible to overwrite this behaviour in the client itself later on using that environment variable? Because that would still be an issue in our use case.

**Comment by danderson** [comment]
I've been running it for some days on a couple of networks, and didn't see any connectivity problems, so I think we're ready to roll it out.

@bramevo given how WireGuard works, authorized traffic in _either_ direction means both have to know about each other in order to form a tunnel. There are potentially some (very invasive) things we could do about that in the future, but for now that means the netmap will show anything that a machine can talk to, and anything that can talk to that machine.

**Comment by bramevo** [comment]
@danderson  Got it. Maybe allowing custom device names would already solve the "hostname leakage" issue. Not a big issue at this time though.

**Comment by danderson** [comment]
Yeah, we have some ideas in that direction, but for this bug the main thing is that machines that can't talk to each other at all can't see each other.

**Comment by DentonGentry** [comment]
I think this is the same request as https://github.com/tailscale/tailscale/issues/824 (Trim netmap based on ACL settings), which has been implemented and deployed.

**Comment by DentonGentry** [comment]
I'm going to close this because it looks like it has been addressed in #824. Please reopen if there is more to be done.
