### ISSUE TITLE
Cleanup: s/LONG/Long/ and s/SHORT/Short/ in version.

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#857]
Go's convention is to not shout variable names, even if they're #define-ish constants.

Mildly annoying to execute, because use of those vars span 3 repositories, including the android one which I'm not sure I know how to update safely. Leaving a note to myself to clean this up someday.

**Comment by bradfitz** [comment]
Can do it in stages: temporarily have both, with SHORT and LONG defined in terms of Short and Long, and then go clean up the other repos async.

**Comment by DentonGentry** [comment]
Use of the build vars has spread:
- Android did not use it before but does now (https://github.com/tailscale/tailscale-android/pull/15/files added it, only recently)
- Arch Linux: https://github.com/tailscale/tailscale/issues/2058
- several Ansible and Terraform scripts

I suspect Hyrum's Law has taken over at this point.

**Comment by bradfitz** [comment]
This was fixed in 5bf65c580d9fc9102c644c6432bf4ada41b5b512. (this was about the all caps constants in Go, not the shell variables)
