### ISSUE TITLE
FR: user can choose 0.x.y.z instead of 100.x.y.z

### ISSUE THREAD

**Issue by rmrf** [tailscale/tailscale#8581]
### What are you trying to do?

Some Cloud vendor (alibabacloud) use 100.x.y.z network for internal production endpoint, such as [object storage](https://www.alibabacloud.com/help/en/object-storage-service/latest/oss-internal-endpoints-and-vip-ranges), it will be greate if  tailscale allow user to chose [0.x.y.z as this kb](https://tailscale.com/kb/1015/100.x-addresses/) said. 

### How should we solve this?

support [0.x.y.z](https://tailscale.com/kb/1015/100.x-addresses/)

### What is the impact of not solving this?

can't use tailscale inside some cloud vendors or if user have internal route conflict with 100.x.y.z

### Anything else?

Love Tailscale :)

**Comment by bradfitz** [comment]
Dup of #7472

**Comment by bradfitz** [comment]
And #1381

**Comment by bradfitz** [comment]
(And previously #8229 before it was folded into #1381 as well)
