### ISSUE TITLE
ACLs and exit nodes ignored in container with userspace networking 

### ISSUE THREAD

**Issue by vortinen** [tailscale/tailscale#8591]
### What is the issue?

I have this network setup with three nodes, one of which is a docker container:

```
----------------------
| host               |
| user@email         |
|                    |
|   ---------------  |            ---------------
|   | container   |  |            | other       |
|   | tag:isolate |  |            | tag:isolate |
|   |             |  |            |             |
|   ---------------  |            ---------------
|                    |
----------------------
```

With this portion of a policy file:

```
	"tagOwners": {
		"tag:isolate": [],
	},
	"acls": [
		{
			"action": "accept",
			"src":    ["user@email"],
			"dst":    ["*:*"],
		},
	],
```

The `container` node is `alpine:latest` running unprivileged on its host, with tailscale started like so:

```
tailscaled --tun=userspace-networking &
tailscale up \
  --authkey="$AUTHKEY" \
  --advertise-tags=tag:isolate \
  --hostname "$HOSTNAME"
```

There seem to be two issues with this setup:

1. `curl other` should not work, but does.
2. If the container's tailscale is up'd with `--exit-node other`, no traffic goes through the exit node.

Note that for all commands above, I've written them with short host names, but used tailnet IPs for testing,.

### OS

Linux

### OS version

alpine:latest

### Tailscale version

1.44.0 on `host` and `other`, 1.32.3-AlpineLinux on `container`

### Bug report

BUG-b5935266a4f84b9452f17773aee69bad43f7a93930f514162d194d98b5cad540-20230706021110Z-795792a26c3696fe BUG-b5935266a4f84b9452f17773aee69bad43f7a93930f514162d194d98b5cad540-20230706021122Z-c73925fec882a8f1

**Comment by knyar** [comment]
Are you sure that connections from the container actually go via Tailscale client in the container itself, and not via the host owned by `user@email`?

Note that in [userspace mode](https://tailscale.com/kb/1112/userspace-networking/) Tailscale client does not own a separate network interface and does not make any changes to routing configuration on the system. Instead, it provides a SOCKS and HTTP proxy that other processes in the container can connect through.

**Comment by DentonGentry** [comment]
https://tailscale.com/kb/1112/userspace-networking/ describes the limitations of userspace mode: applications must use a SOCKS5 or HTTP proxy in order to make outgoing connections. Regular Linux socket apps without a proxy configured are just going straight to the network.
