### ISSUE TITLE
Connected Nodes Disappearing from iOS

### ISSUE THREAD

**Issue by jason-riddle** [tailscale/tailscale#8600]
### What is the issue?

Connected nodes dissappear randomly from the iOS client. I've attached 2 screenshots, the first is my iPhone showing only 2 clients, the second is from https://login.tailscale.com showing all the clients.

![IMG_1307](https://github.com/tailscale/tailscale/assets/2156866/e08807d8-7d3e-4c5b-8790-599def7ca398)

<img width="1600" alt="Screenshot 2023-07-12 at 6 31 03 PM" src="https://github.com/tailscale/tailscale/assets/2156866/22fdb1e8-22f8-423b-8430-ce7b1b828e97">

### Steps to reproduce

I haven't found a way to reproduce this.

### Are there any recent changes that introduced the issue?

Not sure. I believe this first started happening around 2 weeks ago.

### OS

iOS

### OS version

16.5.1

### Tailscale version

1.42.0

### Bug report

BUG-36b5590cecc32bab941723a0465cf3af7267f5a45e265a4565c08ec190b69e08-20230713012248Z-99f7cda3e757604b

**Comment by agottardo** [comment]
Hi Jason,

Do you know if this still happens on the latest version of the app available in [TestFlight](https://testflight.apple.com/join/tLcYLZJV)? 

We have made several improvements in this area recently and there’s a chance we might have already fixed this in the beta. Let me know!

**Comment by jason-riddle** [comment]
I just installed the TestFlight app, but it's still not showing all Tailscale clients. It's still only showing 3 out of my 6 clients.

![IMG_1308](https://github.com/tailscale/tailscale/assets/2156866/596d4a55-95e8-4f3f-8d98-cce6221887c4)

BUG-36b5590cecc32bab941723a0465cf3af7267f5a45e265a4565c08ec190b69e08-20230713090021Z-1c097ad2bc9c9bb0

**Comment by bradfitz** [comment]
You tagged your iPhone. So your iPhone is no longer running as the "group:admin" you think it is... it's not running as _you_, a human. It's running as "tag:iphone".

See https://tailscale.com/kb/1068/acl-tags/
