### ISSUE TITLE
armada375-1.44.0 on Synology NAS DS115: client-version != server-version

### ISSUE THREAD

**Issue by MightySlaytanic** [tailscale/tailscale#8608]
### What is the issue?

Today I've installed tailscale package for armada375 version 1.44.0 over my 1.38.4 version already installed on Synology DS115 NAS and I've seen from the GUI that it was not in a running state.

tailscale status showed this from cli:

```
tailscale status
Warning: client version "1.44.0-t5d008cd83-g6dac82fa0" != tailscaled server version "1.38.4-t043a34500"
```

So, I've tried uninstalling current version and then I've installed 1.44.0 again but it keeps showing a version mismatch. 

My DS115 is running 
[Install log 1.44.0 over 1.38.4.txt](https://github.com/tailscale/tailscale/files/12044207/Install.log.1.44.0.over.1.38.4.txt)
[Install log 1.44.0 after uninstalling 1.38.4.txt](https://github.com/tailscale/tailscale/files/12044206/Install.log.1.44.0.after.uninstalling.1.38.4.txt)

### Steps to reproduce

Install tailscale-armada375-1.44.0-6000044000-dsm6.spk on DS115

### Are there any recent changes that introduced the issue?

Upgrade from 1.38.4 to 1.44.0

### OS

Synology

### OS version

DSM 6.2.4-25556 Update 7 

### Tailscale version

1.38.4

### Bug report

BUG-9b0e88c33e96ce9cb2c95a962550c54e4168f6baae7543d529105c96503e0a9c-20230713202709Z-b11b0377b1c666d5

**Comment by MightySlaytanic** [comment]
I've tested an upgrade to 1.44.2 and it keeps saying that the client is at 1.44.2 while tailscaled server is at 1.38.4-t043a34500. The tailscale tunnel works, I can use it, but the Synology Package tailscale is stopped and a synopkg start tailscale fails. "Tailscale Machines" web page still shows the synology NAS at 1.38.4.

**Comment by MightySlaytanic** [comment]
Today I've completely uninstalled tail scale from the NAS, then I've uploaded 1.46.1, problem persists:

```
# tailscale status
Warning: client version "1.46.1-te42e60103-g4cea91365" != tailscaled server version "1.38.4-t043a34500"
[...]
```

Here is what appears in the logs.. I don't know why there is a "tailscale 1.8.3" that appears in the logs along with 1.44.2...:

```
2023/07/27 20:28:20	uninstall tailscale 1.8.3 Begin /bin/rm -rf /volume1/@appstore/tailscale
2023/07/27 20:28:21	uninstall tailscale 1.8.3 End /bin/rm -rf /volume1/@appstore/tailscale ret=[0]
2023/07/27 20:28:22	uninstall tailscale 1.8.3 Begin postuninst
2023/07/27 20:28:22	uninstall tailscale 1.8.3 End postuninst ret=[0]
2023/07/27 20:28:22	uninstall tailscale: Uninstall 1.8.3 successfully
2023/07/27 20:29:01	uninstall Tailscale: begin to stop version 1.44.2-6000044002
2023/07/27 20:29:04	uninstall Tailscale 1.44.2-6000044002 Begin start-stop-status stop
2023/07/27 20:29:04	uninstall Tailscale 1.44.2-6000044002 End start-stop-status stop ret=[0]
2023/07/27 20:29:04	uninstall Tailscale 1.44.2-6000044002 Begin unload apparmor
2023/07/27 20:29:05	uninstall Tailscale 1.44.2-6000044002 End unload apparmor ret=[0]
2023/07/27 20:29:05	uninstall Tailscale: stop version 1.44.2-6000044002 successfully, result 0
2023/07/27 20:29:25	uninstall Tailscale 1.44.2-6000044002 Begin /bin/rm -rf /volume1/@appstore/Tailscale
2023/07/27 20:29:26	uninstall Tailscale 1.44.2-6000044002 End /bin/rm -rf /volume1/@appstore/Tailscale ret=[0]
2023/07/27 20:29:28	uninstall Tailscale: Uninstall 1.44.2-6000044002 successfully
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 Begin /bin/rm -rf /volume1/@appstore/Tailscale
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 End /bin/rm -rf /volume1/@appstore/Tailscale ret=[0]
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/Tailscale
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/Tailscale ret=[0]
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 Begin /bin/rm -rf /var/packages/Tailscale
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 End /bin/rm -rf /var/packages/Tailscale ret=[0]
2023/07/27 20:31:04	install Tailscale 1.46.1-6000046001 Begin /bin/mkdir -p /var/packages/Tailscale
2023/07/27 20:31:05	install Tailscale 1.46.1-6000046001 End /bin/mkdir -p /var/packages/Tailscale ret=[0]
2023/07/27 20:31:05	install Tailscale 1.46.1-6000046001 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/Tailscale/INFO
2023/07/27 20:31:05	install Tailscale 1.46.1-6000046001 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/Tailscale/INFO ret=[0]
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 Begin /bin/rm -rf /var/packages/Tailscale/scripts
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 End /bin/rm -rf /var/packages/Tailscale/scripts ret=[0]
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/Tailscale/scripts
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/Tailscale/scripts ret=[0]
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 Begin /bin/rm -rf /var/packages/Tailscale/conf
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 End /bin/rm -rf /var/packages/Tailscale/conf ret=[0]
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/Tailscale/conf
2023/07/27 20:31:06	install Tailscale 1.46.1-6000046001 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/Tailscale/conf ret=[0]
2023/07/27 20:31:19	install Tailscale 1.46.1-6000046001 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2023/07/27 20:31:19	install Tailscale 1.46.1-6000046001 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2023/07/27 20:31:19	install Tailscale 1.46.1-6000046001 successfully
2023/07/27 20:31:27	install Tailscale: begin to start version 1.46.1-6000046001
2023/07/27 20:31:28	install Tailscale 1.46.1-6000046001 Begin pre-load apparmor
2023/07/27 20:31:29	install Tailscale 1.46.1-6000046001 End pre-load apparmor ret=[0]
2023/07/27 20:31:29	install Tailscale 1.46.1-6000046001 Begin start-stop-status start
2023/07/27 20:31:29	install Tailscale 1.46.1-6000046001 End start-stop-status start ret=[0]
2023/07/27 20:31:30	install Tailscale: start version 1.46.1-6000046001 successfully, result 0
```

Then tail scale works, but the DSM Package Manager keep showing it as stopped.
<img width="498" alt="Screenshot 2023-07-27 alle 20 37 41" src="https://github.com/tailscale/tailscale/assets/16508544/5b0da9bc-92c5-4d6e-b650-f23044de2a5f">

**Comment by DentonGentry** [comment]
Does `ps auxw | grep tailscale` show a tailscaled running? What path?
Either:
1. There is another `tailscaled` installed at a different path somehow, or:
1. The install script didn't kill the old daemon.

I think the second item is likely. We fixed an issue very much like that in May with https://github.com/tailscale/tailscale-synology/pull/114, but the 1.38.4 release is older than that.

If so, killing the `tailscaled` process from the shell and then Stopping and Starting the Tailscale service in the Package Center should start the 1.46.1 `tailscaled`.

**Comment by MightySlaytanic** [comment]
Thank you very much @DentonGentry, I don't know why I didn't try to kill the process... sometimes we forget the easy way :) Now everything is fine, thank you for the support and this great piece of software.
