### ISSUE TITLE
FR: Option to disable mesh on mobile devices to decrease power usage

### ISSUE THREAD

**Issue by jbschooley** [tailscale/tailscale#8612]
### What are you trying to do?

Tailscale cuts battery life in half on my iPhone and iPad. I set up a wireguard server as a relay to my tailnet, and this allows me to stay connected to my tailnet at all times with a negligible impact on battery. Having this functionality built into Tailscale might be a good solution to the power usage issue.

### How should we solve this?

An option to disable mesh networking on an individual device and choose another node to relay traffic through.

### What is the impact of not solving this?

Users who want to stay connected to their devices from a mobile device and still have their device last all day will have to find another solution, whether that be using a different VPN solution or hosting services publicly.

### Anything else?

I understand there’s been a lot of work to reduce battery usage on mobile. But I feel like Tailscale only started draining battery like crazy once I expanded my tailnet. I wonder how much power usage is caused by extra layers on top of wireguard and how much of it is trying to keep 18 separate tunnels open at all times.

**Comment by bradfitz** [comment]
Other bugs are open tracking battery work so I'm going to close this as a duplicate. (This isn't the real problem.)
