### ISSUE TITLE
When replacing a 64GB memory module, Tailscale is likely to cause a Blue screen of death?

### ISSUE THREAD

**Issue by OuOumm** [tailscale/tailscale#8618]
### What is the issue?

When I replaced a 32GB memory module with a frequency of 3200, I inserted it into channels 2 and 4 of the motherboard, which were 3200x32G and 3200x32GB respectively, totaling 64GB. Sometimes I can enter the system normally, and sometimes the blue screen prevents me from starting. Later, after providing feedback to the Microsoft platform, I received a response informing me to uninstall Tailscale and see if it returned to normal. I prohibited the Tailscale driver from starting and the system started normally without any errors.

I did not encounter this error when using a 16GB memory module, which is 8+8. Please check for this error.

### Steps to reproduce

The automatic start of the drive is disabled

### Are there any recent changes that introduced the issue?

Replaced more memory
Upgraded from 16GB to 64GB

### OS version

Windows 11 Pro Insider Preview 22H2  25309.1000

### Tailscale version

1.44.0

### Other software

not in use

**Comment by DentonGentry** [comment]
This seems likely to be bad RAM, doesn't it?

**Comment by OuOumm** [comment]
> 这似乎可能是坏的RAM，不是吗？



> This seems likely to be bad RAM, doesn't it?

I initially thought the same, but I switched to two different memory manufacturers for testing, and both tested with the same result. However, switching to 16GB did not have this issue, emmm, which needs to be investigated because the dmp file shows a driver issue with Tailscale.

**Comment by bradfitz** [comment]
This isn't a Tailscale issue.
