### ISSUE TITLE
Taildrop replaces spaces with %20 in filenames

### ISSUE THREAD

**Issue by gingerbeardman** [tailscale/tailscale#8621]
### What is the issue?

- Taildrop replaces spaces with %20 in filenames

### Steps to reproduce

1. Taildrop a local file with spaces in the name, eg. "This is a test.txt"
2. Check filename of received file

### Are there any recent changes that introduced the issue?

- n/a

### OS

macOS, Synology

### OS version

macOS 12.6.7, Synology 6.2.3

### Tailscale version

1.44.0 (macOS), 1.38.4 (Synology)

**Comment by d5aqoep** [comment]
This happens on QNAP too

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/7874
