### ISSUE TITLE
DNS console UI accepts 0.0.0.0 but backend refuses

### ISSUE THREAD

**Issue by hdhoang** [tailscale/tailscale#8625]
### What is the issue?

hello!

previously, i set split-dns for some domains to `0.0.0.0` as a crude blocking method for the tailnet.

today, i went to change some settings at https://login.tailscale.com/admin/dns, but all updates are denied with http 400, notification saying:

> Failed to update DNS settings: error validating request body: invalid resolver "0.0.0.0" for route "abc.def"

i can't delete such entries one-by-one, because the other entries hit the issue too.

currently [DNS API](https://github.com/tailscale/tailscale/blob/main/api.md#dns) doesn't support changing `routes`, so i can't update there.

as a workaround, i used browser edit-and-resend on the bad request to erase all settings, and i will put back only valid ones.

please update FE to refuse 0.0.0.0, or return previous behaviour of backend. thanks!

### Steps to reproduce

Enter new split DNS entry with nameserver `0.0.0.0`, FE accepts it (unlike eg `0.0.0.`), but saving fails.

```json
"routes":{
"abc.def":["0.0.0.0"]
}
```

### Are there any recent changes that introduced the issue?

backend accepted `0.0.0.0` previously

### OS

Windows

### OS version

windows 11

### Tailscale version

1.44

### Other software

firefox 115

**Comment by bradfitz** [comment]
cc @clairew
