### ISSUE TITLE
Tailscale drops connection when PIA is active, even when using split tunneling (Windows)

### ISSUE THREAD

**Issue by TheColorman** [tailscale/tailscale#8647]
### What is the issue?

Starting both [PIA](https://www.privateinternetaccess.com/) and Tailscale on Windows 11 works if using split tunneling as desrcibed in [Tailscale other VPNs FAQ](https://tailscale.com/kb/1105/other-vpns/), but the connection stops working after a couple of minutes.

Turning on Tailscale enables Tailscale features, and shows device as "Connected" on the admin panel. Turning on PIA causes the device to go offline on the admin panel, but other Tailscale machines can still connect to it. After a couple of minutes, other devices are unable to connect.

If both devices are on the same network, they are still able to reach eachother using Tailscales IP and DNS however.

The interesting part here is that there's a brief window where the admin panel reports the device as offline despite it still being reachable by other machines. Maybe something is blocking its communication with the central server? Or maybe it's some keepalive settings?

### Steps to reproduce

1. Set up split tunneling in PIA and let the following IP ranges bypass the VPN:
```
100.64.0.0/10
fd7a:115c:a1e0::/48
```
2. Connect to the tailnet. The device is now "Connected" on the admin panel.
3. Connect the VPN. The device is now offline on the admin panel, but still reachable by other machines on the tailnet.
4. After a few minutes, the other machines on the tailnet can no longer reach the device.

### Are there any recent changes that introduced the issue?

Not to my knowledge, but I haven't used Tailscale for long enough to be sure.

### OS

Windows

### OS version

Microsoft Windows 11 Pro, version 10.0.22621 Build 22621

### Tailscale version

1.44.2

### Other software

PrivateInternetAccess VPN using OpenVPN with port forwarding and split tunneling for the previusly specified ranges.

### Bug report

BUG-92e7f80bc2c8085340488c2dee70b4e75819ebc8836cf3b5df070750cb933fd4-20230719131252Z-ebde3d2adb044d61

**Comment by DentonGentry** [comment]
Having multiple VPN products simultaneously active rarely works at all. They fight over every resource: routing table, firewall rules, etc. Even if a stable configuration is found, a subsequent update of either product can introduce a new conflict.

**Comment by TheColorman** [comment]
Closing this as I'm no longer using Windows and there are better solutions out there (e.g. container networking).
