### ISSUE TITLE
Add "unstable" to odd-numbered version strings.

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#865]
I think the even/odd numbering for stable/unstable versions (1.0 stable, 1.1 unstable, 1.2 stable again, 1.3 unstable) is generally good, but a couple of things have caused user confusion.

Here's someone who built specifically v1.1.0, which is a very bad idea but it's not obvious why: https://forum.tailscale.com/t/using-tailscale-from-docker-containers/127

I've seen a couple of other questions recently (eg. a twitter conversation today) where people get confused when we say they can try a feature in 1.1, but it won't be public until 1.2 (which is really the same as 1.1 but with a stable tag).

I think a quick fix would be to just change our tags to include "unstable" in the odd-numbered tags. For example, v1.1-unstable instead of tagging v1.1.0. Then have the version number generator strip the -unstable when building.

cc: @danderson @bradfitz

**Comment by danderson** [comment]
I think this is a no-op now: we no longer tag unstable builds, only stable ones. So the rule is simply: build from HEAD to get something unstable, or from a release branch for something stable.

We could add the words "unstable" to the output of "tailscale version", but AFAICT the source of confusion was the existence of git tags, so I'd be equally happy to close this with no further action. Thoughts @apenwarr @DentonGentry ?

**Comment by DentonGentry** [comment]
I think we could close it, at this point essentially all of the updates to stable releases for all supported platforms come through channels which won't mix up and install an unstable. The source of confusion has been removed.

**Comment by bradfitz** [comment]
OTOH this is easy to do now that we embed VERSION.txt. We can at least say "unstable" in the "Tailscale version" output and in GUIs. We do on Mac already actually.

**Comment by DentonGentry** [comment]
macsys doesn't do this yet. Maybe the Network Extension macOS build does.

<img width="284" alt="Screen Shot 2021-11-25 at 2 09 42 PM" src="https://user-images.githubusercontent.com/1140756/143503786-41e44117-236e-4a3c-8dd3-79cf4fccd2cc.png">

**Comment by bradfitz** [comment]
@DentonGentry, the code's still present in the tree at least:

```
bradfitz@tsdev:~/src/tailscale.io/xcode$ git grep -i likely
IPN/UI/macOS/MenuGroups/ClientSection.swift:           appVersionString += "\n\nWarning: development version of Tailscale; likely out of date"
```

**Comment by bradfitz** [comment]
Hahahah:

```
        if appVersion.hasPrefix("1.7.") || appVersion.hasPrefix("1.9.") || appVersion.hasPrefix("1.11.") ||
           appVersion.hasPrefix("1.13.") || appVersion.hasPrefix("1.15.") {
           // TODO(bradfitz): parse semver and see if minor is odd rather than string prefixes.
           appVersionString += "\n\nWarning: development version of Tailscale; likely out of date"
        }
```

**Comment by DentonGentry** [comment]
macSys has an unstable notation in its about box now:
<img width="288" alt="Screen Shot 2022-07-31 at 10 33 38 AM" src="https://user-images.githubusercontent.com/1140756/182038509-21dfd4aa-b284-4f02-abfd-7bff4b5dee6b.png">

So does Windows:
<img width="308" alt="Screen Shot 2022-07-31 at 10 37 16 AM" src="https://user-images.githubusercontent.com/1140756/182038606-acfb51c2-ad4c-41f8-bc15-168bea3406aa.png">

Linux does not indicate stable vs unstable:
```
# tailscale version
1.29.62
  tailscale commit: f541e00db2e52c0b6166256bfd17bba6a0a11322
  other commit: deacf9a5e814f1c19b86d7f471210aec08afa474
  go version: go1.19rc25-tsfabd769a37
```

Android and iOS don't have a way of showing you the version number at all, so... yay.

**Comment by DentonGentry** [comment]
The App Store version of the Mac app identifies itself as the unstable build (and also labels itself as the App Store variant):

<img width="289" alt="Screen Shot 2022-08-27 at 10 39 30 AM" src="https://user-images.githubusercontent.com/1140756/187041726-6052a20a-1564-4c3e-a7c6-3e574e623c14.png">

Only the CLI version output remains to be addressed:
```
# tailscale version
1.29.164
  tailscale commit: 9197dd14cc2439d8e3daa4fac5b3a3d293dffd27
  other commit: 5a12c9327dbe032813e68dc48aead0410944950b
  go version: go1.19-ts6dca83b256
#
```
