### ISSUE TITLE
FR: Tailscale (™) SMTP / 2FA Relay? (Generally - More Consumable Common Services!)

### ISSUE THREAD

**Issue by rhrpr** [tailscale/tailscale#8659]
### What are you trying to do?

Hi , I started using tailscale today and firstly, thank you for building something excellent. 

Whilst I look into trying to get an SMTP provider that can give me an IP address for subnet routing , I wondered if as you have begun to offer HTTPS , that some solution to make SMTP service within tailscale simple is on the roadmap?

This would enable things like 2FA via email, App notifications and so on . 

2FA also springs to mind when thinking about Yubikey or Duo for 2FA in self hosted or development Applications - i.e 2FA for Apps entirely within a user's Tailscale network. 

I am happy to write a similar Feature Request for 2FA if I am not barking up the wrong tree entirely and please let me know if I just need to get a subnet router for both of these external services (and if there happens to be a known SMTP provider that will give a shared IP (I'm attempting this via my provider at the moment but no dice so far).  

### How should we solve this?

Not much by way of technical implementation here - I'd considered re-use of the aptly named DERP relay infrastructure you hold already but given the encrypted nature of traffic through them and with limited knowledge (I'm new!) I'm not confident of how that'd sit together. 

I think the user experience of this would involve an opt-in mechanism by which a user can accept that tailscale will relay outbound SMTP tailnet wide (or based on user defined policy) , where SMTP service provider config parameters can be made in tailscale's UI (to an SMTP service provider). 

I know that you offer an SSH mechanism that can use a pubic identity provider  - perhaps a similar concept could be adopted for other common services (SMTP, WebApp 2FA, etc). Tailscale could even partner with a third party to make the setup of this super easy and perhaps help generate some sweet referral or B2B revenue in the process. 

If you read '2FA' everywhere it says 'SMTP' in the second paragraph above - similar logic applies - easily consuming common services and making common tasks secure and simple can only be of benefit to Tailscale's offering. 

### What is the impact of not solving this?

Currently - I'm scratching my head to find a way to do this - perhaps the answer omits tailscale entirely and requires use of a proxy / relay that I self host.

### Anything else?

Happy to be corrected if I can use or allow traffic to Yubikey OTP server, Duo's API server & a well known SMTP service for select devices via a Subnet router.

**Comment by bradfitz** [comment]
This issue's kinda all over the place.

Can you start with your problem without mixing in a half dozen possible solutions and business ideas? I'm not sure which of those words is your actual problem.

Like, is SMTP your actual problem (unlikely?) or just a means of solving your actual problem?

**Comment by rhrpr** [comment]
Fair enough , it is a bit scattered. 

I had a site wide DNS problem yesterday that is now resolved - I assume this was the reason for the SMTP issue I was having with my app so now is resolved as is YubiKey OTP due to my misconfiguration. 

The next item on the list is to try and enable Duo 2FA - but that isn't functioning at the moment per screenshot. If you happen to have any experience of using it within a tailnet hosted app please let me know. 

![image](https://github.com/tailscale/tailscale/assets/2528092/03c76cc4-4b3d-4d0e-a662-dd630d808e2f)
