### ISSUE TITLE
Error 0x81f40001: Bundle condition evaluated to false: WixBundleAction <> 5 OR InstalledBundleVersion <> WixBundleVersion

### ISSUE THREAD

**Issue by pascutc98** [tailscale/tailscale#8663]

**Comment by pascutc98** [comment]
It was not an installation error at all. Tailscale was correctly installed, it simply didn't work the authentication key to access to the cluster.

**Comment by xsxsm** [comment]
> It was not an installation error at all. Tailscale was correctly installed, it simply didn't work the authentication key to access to the cluster.

I also encountered the same problem, and based on the feedback from the developers, I still don't know what to do. If the software is already installed, how do I start it and how do I uninstall and reinstall it? If it simply didn't work the authentication key to access to the cluster Under what network conditions can I access it? My computer can access the internet.

**Comment by DentonGentry** [comment]
@xsxsm It is not at all clear to me that you are seeing the same problem. The original report was about an authkey, confounded by not-so-helpful log messages from the installer.

Please open a new bug and include a bugreport if possible.
