### ISSUE TITLE
FR: tailscale version in machine readable/json format

### ISSUE THREAD

**Issue by robmarkoski** [tailscale/tailscale#8669]
### What are you trying to do?

Trying to write some automation scripts, it would be great to be able to provide tailscale version installed locally, and version latest version available in json format.

### How should we solve this?

either under tailscale version --json provide local and latest keys

alternatively under tailscale update --json

### What is the impact of not solving this?

harder to write automation scripts and deployments.

**Comment by bradfitz** [comment]
Do you know about https://pkgs.tailscale.com/stable/?mode=json ?

**Comment by awly** [comment]
We already have some code in `tailscale update` for fetching the latest version from `pkgs.tailscale.com`.
Should be trivial to add `tailscale version --json` with output like:
```json
{
  "Installed": "1.44.2",
  "Latest": "1.46.0"
}
```

I'll add that this week.

**Comment by robmarkoski** [comment]
> Do you know about https://pkgs.tailscale.com/stable/?mode=json ?

I didnt. But thats incredibly useful thanks for that!



> We already have some code in `tailscale update` for fetching the latest version from `pkgs.tailscale.com`. Should be trivial to add `tailscale version --json` with output like:
> 
> ```json
> {
>   "Installed": "1.44.2",
>   "Latest": "1.46.0"
> }
> ```
> 
> I'll add that this week.

Thats awesome. Right now im parsing the tailscale update --dry-run, but would be nice to have something a bit more machine readable.

Cheers mate!
