### ISSUE TITLE
tailscale break my ipv4 tproxy transparent proxy

### ISSUE THREAD

**Issue by heygo1345678** [tailscale/tailscale#8683]
### What is the issue?

I have a ipv4&ipv6 tproxy transparent  proxy on my openwrt home router,  before intsalling tailscale , this  transparent  proxy works   normally.Once I installed a tailscale  docker container on openwrt. it will break openwrt's  ipv4 tproxy transparent proxy. then i  docker stop tailscaled container.openwrt's  ipv4 tproxy transparent proxy will be rescued.
I tested this by httping .There is no problem on openwrt's ipv6 tproxy transparent proxy. I also test lan device ,There is no problem on lan device's ipv4&ipv6 tproxy transparent proxy.if i change tproxy  to tun2socks transparent  proxy ,there is no this issue,too

### Steps to reproduce

this website www.wsj.com blocked on china, i visit it via tproxy

openwrt home router:
root@OpenWrt:~# httping -6 www.wsj.com
PING www.wsj.com:80 (/):
connected to [2600:9000:2066:2000:3:4b0:de80:93a1]:80 (393 bytes), seq=0 time=116.11 ms 
connected to [2600:9000:2066:f000:3:4b0:de80:93a1]:80 (393 bytes), seq=1 time=115.91 ms

root@OpenWrt:~# httping www.wsj.com
PING www.wsj.com:80 (/):
connect time out

^CGot signal 2
--- http://www.wsj.com/ ping statistics ---
2 connects, 0 ok, 50.00% failed, time 40535ms

lan device:

root@debian:~# httping www.wsj.com
PING www.wsj.com:80 (/):
connected to 65.9.42.99:80 (393 bytes), seq=0 time=116.37 ms 
connected to 65.9.42.26:80 (393 bytes), seq=1 time=114.30 ms 
^CGot signal 2
--- http://www.wsj.com/ ping statistics ---
2 connects, 2 ok, 0.00% failed, time 1495ms
round-trip min/avg/max = 114.3/115.3/116.4 ms
root@debian:~# httping -6 www.wsj.com
PING www.wsj.com:80 (/):
connected to [2600:9000:2066:2a00:3:4b0:de80:93a1]:80 (393 bytes), seq=0 time=119.17 ms 
connected to [2600:9000:2066:ee00:3:4b0:de80:93a1]:80 (393 bytes), seq=1 time=117.44 ms 
^CGot signal 2
--- http://www.wsj.com/ ping statistics ---
2 connects, 2 ok, 0.00% failed, time 1480ms
round-trip min/avg/max = 117.4/118.3/119.2 ms

### OS

Linux

### OS version

openwrt21.02

### Tailscale version

v1.44.0

**Comment by heygo1345678** [comment]
I waste a few day to check this issue and found tailscale will generate a iptables rule:
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
when i del it, my .openwrt's ipv4 tproxy transparent proxy will be rescued.
Any one knows why ts have this rule? why this rule break v4 tproxy?

**Comment by tataue** [comment]
any update?
