### ISSUE TITLE
windows: failed to look up user from userid: No mapping between account names and security IDs was done.

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#869]
User reports, with 1.1.556:

![image (5)](https://user-images.githubusercontent.com/2621/97598813-93ddc080-19c4-11eb-8c18-4516ea2de7d4.png)

Internet says:
* https://docs.microsoft.com/en-us/troubleshoot/windows-server/group-policy/scecli-1202-events
* https://www.rebeladmin.com/2016/01/how-to-fix-error-no-mapping-between-account-names-and-security-ids-in-active-directory/

/cc @alexbrainman

**Comment by bradfitz** [comment]
Sent https://github.com/tailscale/tailscale/pull/871

**Comment by bradfitz** [comment]
Good enough for now.

**Comment by DentonGentry** [comment]
Does still happen in the wild: `2021-11-05 18:02:06.1458677 -0500 -0500: 2021/11/05 18:02:06 [warning] issue 869: os/user.LookupId failed; ignoring`

**Comment by bradfitz** [comment]
Reopening for @dblohm7 to investigate properly, as my earlier fix was a band-aid at best.

**Comment by dblohm7** [comment]
For starters, I filed https://github.com/golang/go/issues/49509
