### ISSUE TITLE
1.46.0 issue with Asahi 16kb page size and gvisor.

### ISSUE THREAD

**Issue by wcatz** [tailscale/tailscale#8703]
### What is the issue?

panic: Only 4K page size is supported on arm64!

goroutine 1 [running]:
gvisor.dev/gvisor/pkg/hostarch.init.0()
	/build/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/hostarch/hostarch_arm64.go:59 +0x44

### Steps to reproduce

Asahi Linux on Apple M1 chip with Tailscale 1.46.0

### OS

Linux

### OS version

Asahi Arch Linux with 16kb page size

### Tailscale version

1.46.0

### Other software

Downgrading to an older version fixes the issue.

### Bug report

I'm not reinstalling it.

**Comment by bradfitz** [comment]
Dup of #8658. It's been fixed in the tree but a point release isn't out yet. It'll probably be done in the next day or two.
