### ISSUE TITLE
Tailscale app drains iPhone battery even while disconnected

### ISSUE THREAD

**Issue by lichtzeichner** [tailscale/tailscale#8704]
### What is the issue?

After the latest update to 1.46.0 (with the new, nicer UI), I noticed a huge battery drain, even if Tailscale is disconnected. It's the second most battery draining app in the list, and it's almost all background activity.

The previous app versions only consumed noticeable amounts of battery when the phone was connected to the tailnet.

### Steps to reproduce

Updating the app via App Store

### Are there any recent changes that introduced the issue?

The issue started to appear with 1.46.0

### OS

iOS

### OS version

iOS 16.5.1 (c) on an iPhone 13 Pro Max

### Tailscale version

1.46.0

### Bug report

BUG-42ee3d39f5fed8c1f2809e58291e64434bc0f52b527dd50523dfb45de113e396-20230725104943Z-a1e4e9079c6370e0

**Comment by KSDBYWB** [comment]
Same issue, only option is to remove the app install. 

![IMG_5825](https://github.com/tailscale/tailscale/assets/140513463/fa23c6eb-3d63-44e8-8b22-de5ad642d099)

With Tailscale installed over 24 hours:
![IMG_5823](https://github.com/tailscale/tailscale/assets/140513463/f06f3341-5ec5-47b1-b21b-facb5794126c)

With Tailscale removed over same 24 hours:
![IMG_5824](https://github.com/tailscale/tailscale/assets/140513463/ee8479a6-efab-4b55-9871-536acb695a92)

**Comment by agottardo** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/1734.
