### ISSUE TITLE
FR: add Disconnect toggle at top of iOS app

### ISSUE THREAD

**Issue by mrjware** [tailscale/tailscale#8713]
IOS 1.46. Introduced the requirement to click on two buttons verses one to disconnect.  I disconnect and reconnect Tailscale about 40 to 50 times a day depending on which office location I need to connect to. I do like the new slider for the exit now, but please add the connect/disconnect slider button back to the top. Not hidden in a drop down.

**Comment by agottardo** [comment]
This has been fixed in 1.48, available on the App Store.
