### ISSUE TITLE
TLS certificate issued with tailscale cert does not renew before expiry

### ISSUE THREAD

**Issue by kurtraschke** [tailscale/tailscale#8725]
### What is the issue?

Requesting a TLS certificate with `tailscale cert` that is due for renewal (whether by the original 'expiry-within-14-days' logic, the new '2/3 of lifetime' logic, or using ARI) results in the `starting async renewal` message being logged, but the cert is not actually renewed, and subsequent calls to `tailscale cert` return the same certificate, _until_ the certificate has actually expired.

### Steps to reproduce

1. Observe that a TLS certificate issued with `tailscale cert` is expiring (according to the logic relevant to that version of the Tailscale client).
2. Call `tailscale cert`.
3. Observe the `starting async renewal` log entry.
4. Wait a suitable period of time for the async renewal process that we presume is happening to complete.
5. Call `tailscale cert` again and observe that the certificate has not, in fact, been renewed. Further observe that there are no relevant log entries following `starting async renewal`, implying that the async renewal process did not, in fact, happen.

### Are there any recent changes that introduced the issue?

This _doesn't_ seem to have been triggered by #8204, although that issue appears to have shed light on this problem (there are several comments there reporting this behavior as well).  My amateur diagnosis, after a few minutes perusing `cert.go`, is that the problem lies [in the `getCertPEM()` function](https://github.com/tailscale/tailscale/blob/b3138a71ad0b2fb7d99f0dcecc5e4bc85483bb4f/ipn/ipnlocal/cert.go#L321) (which is what is called in a goroutine immediately after the `starting async renewal` message), which in turn calls `getCertPEMCached()` early in its execution, _passing the current time as the time for the validity test_ (which winds up coming from [here](https://github.com/tailscale/tailscale/blob/35bdbeda9fa149bd6caf93b30d71dd767d16d4b6/ipn/ipnlocal/cert.go#L90C3-L90C3)).  Thus even if `getCertPEM()` has been called explicitly for the purpose of renewing the certificate, if that certificate is still valid, it will return the cached certificate and do no more.

Still in the realm of amateur diagnosis, it seems like this could be addressed by adding a flag to `getCertPEM()` to bypass the cache when it has been called for the explicit purpose of performing a renewal, or, passing a manifestly invalid (e.g. far future or past) `now` time, so that the cache test cannot succeed in those cases and a new certificate will always be fetched.

(Arguably `getCertPEM()` should _never_ look for a cached certificate, since `GetCertPEM()` (the public API) already [looks for a cached certificate](https://github.com/tailscale/tailscale/blob/b3138a71ad0b2fb7d99f0dcecc5e4bc85483bb4f/ipn/ipnlocal/cert.go#L103C22-L103C22) first.)

### OS

Linux, Synology

### OS version

Debian 11

### Tailscale version

1.46.0

### Bug report

BUG-6af6aba81615e09513ecb877765b58b71235444a83b4614a5fc5f63525bdfdfd-20230727033840Z-c13db33870051c71

**Comment by kurtraschke** [comment]
Thanks for the quick fix, @awly!

**Comment by arirangz** [comment]
Hello!

I know this is closed but I have the same issue with the windows client (latest version 1.64.0).

My certificate will expire the 15th of April and when I am running the command tail cert, I am getting the same certificate with same expiration day.

Is it normal? I am running a cron daily so I hope to get a new certificate few days before to avoid DNS cache issue.

Thanks

**Comment by johnvick** [comment]
Have you tried running it a second time? This works for me.

**Comment by awly** [comment]
@arirangz did it eventually renew before expiry?

**Comment by arirangz** [comment]
thanks for your answers.

Yes when I tried again it did renew. So it did renew 3 days before.

Do you know what is the rule? How many days before we could expect for a new certificate?

Thanks

**Comment by awly** [comment]
> Do you know what is the rule? How many days before we could expect for a new certificate?

We use something called [ARI](https://letsencrypt.org/2023/03/23/improving-resliiency-and-reliability-with-ari.html). Effectively, Let's Encrypt tells us when to renew a specific cert and they can change their criteria at any time. Which means that the behavior is not deterministic.

**Comment by arirangz** [comment]
> > Do you know what is the rule? How many days before we could expect for a new certificate?
> 
> We use something called [ARI](https://letsencrypt.org/2023/03/23/improving-resliiency-and-reliability-with-ari.html). Effectively, Let's Encrypt tells us when to renew a specific cert and they can change their criteria at any time. Which means that the behavior is not deterministic.

Thank you for this information.

By experience, do you know what is the average number of days we can expect?

**Comment by awly** [comment]
I don't have any real data, but https://github.com/letsencrypt/boulder/blob/2b8dea9821233bf4dd185e69f322f20abb8f2017/core/objects.go#L515-L529 suggests that for most certs it should renew at 2/3rds of lifetime. So assuming a regular 90-day cert, it should renew around 30 days before expiry.

I don't know why in your case renewal happened 3 days before. You could try searching your tailscaled logs for "acme", or reach out to [support](https://tailscale.com/contact/support) with the details including your node name so we can look from our end.

**Comment by pgcudahy** [comment]
Hi, to add to this, I have renewal set up as a systemd timer set to run every 30 days. However a check at less than 48 hours to expiry did not renew the certificate. The timer calls this script which runs `tailscale cert` and then the proxmox tool `pvenode`

```
#!/usr/bin/env bash
/usr/bin/tailscale cert \
    --cert-file '/etc/ssl/private/xxx.ts.net.crt' \
    --key-file '/etc/ssl/private/xxx.ts.net.key' \
    xxx.ts.net && \
pvenode cert set \
    /etc/ssl/private/xxx.ts.net.crt \
    /etc/ssl/private/xxx.ts.net.key \
    --force 1 --restart 1
```
The nice thing is that `pvenode` prints the key details to the log so that you can see that it was run on May 22 on a key set to expire May 24 but did not trigger a renewal

```
May 22 13:52:47 systemd[1]: Starting tailscale-cert.service - Tailscale Certificate Renewal Service...
May 22 13:52:47 tailscale_cert_update.sh[2870499]: Public cert unchanged at /etc/ssl/private/xxx.ts.net.crt
May 22 13:52:47 tailscale_cert_update.sh[2870499]: Private key unchanged at /etc/ssl/private/xxx.ts.net.key
May 22 13:52:48 tailscale_cert_update.sh[2870504]: Setting custom certificate files
May 22 13:52:48 tailscale_cert_update.sh[2870504]: Restarting pveproxy
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ┌─────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┐
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ filename        │ pveproxy-ssl.pem                                                                                │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ fingerprint     │ redacted │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ subject         │ /CN=xxx.ts.net                                                             │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ issuer          │ /C=US/O=Let's Encrypt/CN=R3                                                                     │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ notbefore       │ 2024-02-24 07:32:09                                                                             │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ notafter        │ 2024-05-24 07:32:08                                                                             │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ public-key-type │ id-ecPublicKey                                                                                  │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ public-key-bits │ 256                                                                                             │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: ├─────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────┤
May 22 13:52:48 tailscale_cert_update.sh[2870504]: │ san             │ - xxx.ts.net                                                               │
May 22 13:52:48 tailscale_cert_update.sh[2870504]: └─────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────┘
May 22 13:52:48 systemd[1]: tailscale-cert.service: Deactivated successfully.
```

**Comment by awly** [comment]
@pgcudahy did it rotate on the next run? (I assume you had to run it manually to fix).
Running every 30 days might be risky in general, because Let's Encrypt certificates are valid for 90 days, so you get 2-3 rotation attempts before they expire. Checking at least daily would be safer.

Alternatively, [tailscale serve](https://tailscale.com/kb/1242/tailscale-serve) might work better here, as it handles rotation automatically.

**Comment by arirangz** [comment]
I there,

A quick update on my tests.

I have my cron running daily and it did not renew the certificate which was expiring on the 11th of July.

So I ran manually tailscale cert, but it did not generate new certificate. I ran one more time the command in the same terminal at this time it renew with a 3 month validity:
![image](https://github.com/tailscale/tailscale/assets/1193727/88772a08-8111-4903-9bbf-04e5c0b1e572)

Is this helping on fixing the issue?

Thanks

**Comment by awly** [comment]
@arirangz can you show your cron job definition and logs, if you have them?

**Comment by arirangz** [comment]
Hello @awly and thanks for your reply.

I am on windows and I am running a bat file with the followin:
`cd C:\Users\xxx\
del xxx-server.tail97ec8.ts.net.crt
del xxx-server.tail97ec8.ts.net.key
tailscale cert xxx-server.tail97ec8.ts.net
net stop Tailscale
net start Tailscale
cd C:\Apache24\bin
httpd -k restart`

But as I previously said, even without considering the cron task, I had to run twice the command to have the certificate generated again.

Thanks

**Comment by awly** [comment]
@arirangz this appears to be a regression introduced last October.
https://github.com/tailscale/tailscale/pull/12822 should make `tailscale cert` rotate synchronously on the first try.

**Comment by arirangz** [comment]
@awly thanks for the update.

So it's going to be fixed in a future version?

**Comment by awly** [comment]
@arirangz yep, likely in 1.72.0, since I just missed the 1.70.0 release train :sweat_smile:

**Comment by arirangz** [comment]
@awly ok great, thanks!

Do you think it's possible to ping us here when 1.72.0 is ready?

**Comment by awly** [comment]
I'll try to remember (it'll be a month from now), but you can also subscribe to https://tailscale.com/changelog#client

**Comment by awly** [comment]
@arirangz 1.72 is now released and has a `tailscale cert --min-validity=...` flag which you should use in scheduled rotation jobs: https://tailscale.com/kb/1080/cli#cert

**Comment by arirangz** [comment]
@awly Awesome! Thanks for the ping
