### ISSUE TITLE
Tagged server can access subnet routes when ACL should deny it, if admin group is given access

### ISSUE THREAD

**Issue by jackv24** [tailscale/tailscale#8726]
### What is the issue?

If I spin up a new node using an auth key with a tag that should only have access to one server, it still gets full access to my subnet router.

I have the ACL set up to allow group:admin access to specific subnet IPs, if I remove "192.168.0.212:*" from the "dst" for admins then the tag:tester-machine can no longer access it, as if it is in the admin group.

Additionally I have a tests section setup to verify the deny rules, which incorrectly pass even though this machine can actually access what's in the deny test list.

My ACL file is set up like so (synobro is the subnet router):

```
{
	"groups": {
		"group:admin": ["email@example.com"],
	},
	"hosts": {
		"cherry-office": "<ip>",
		"cherry-svn":    "<ip>",
		"synobro":       "<ip>",
	},
	"acls": [
		{
			"action": "accept",
			"src":    ["autogroup:members"],
			"dst":    ["autogroup:self:*"],
		},
		{
			"action": "accept",
			"src":    ["group:admin"],
			"dst": [
				"tag:server:*",
				"192.168.0.1:*",
				"192.168.0.58:*",
				"192.168.0.212:*",
				"192.168.0.12:*",
			],
		},
		{
			"action": "accept",
			"src":    ["tag:tester-machine"],
			"dst":    ["cherry-office:8080"],
		},
	],
	"tagOwners": {
		"tag:server":             ["group:admin"],
		"tag:tester-machine":     ["group:admin"],
	},
	"ssh": [
		// Allow all users to SSH into their own devices in check mode.
		// Comment this section out if you want to define specific restrictions.
		{
			"action": "check",
			"src":    ["autogroup:members"],
			"dst":    ["autogroup:self"],
			"users":  ["autogroup:nonroot", "root"],
		},
		// Admins can SSH into servers
		{
			"action": "check",
			"src":    ["group:admin"],
			"dst":    ["tag:server"],
			"users":  ["autogroup:nonroot", "root"],
		},
	],
	"tests": [
		{
			"src":    "tag:tester-machine",
			"accept": ["cherry-office:8080"],
			"deny":   ["cherry-office:22", "synobro:7100", "192.168.0.212:80"],
		},
	],
}
```

### Steps to reproduce

Running `tailscale status` shows cherry-office and synobro in the list, when only cherry-office should be visible.

Running `wget -O - 'http://192.168.0.212'` returns the web page content, when it should not have access. Removing access to that IP from the admin group and then running this again will not work, as if this tag is getting the same access as an admin.

### OS

Linux

### OS version

Ubuntu 22.04 using Docker

### Tailscale version

1.46.1 (docker latest)

### Bug report

BUG-08d89af6dca6db048b25e8237b809b2fcfed2c45b7aaefdc3b9bfdf2e86856e7-20230727073036Z-4912e9eb859e9ff3

**Comment by knyar** [comment]
The Tailscale client that the bug report has been produced from is owned by a user, not by a tag. There currently seem to be no devices in your Tailnet owned by `tag:tester-machine`.

Seeing Docker mentioned, I am curious if you are running the Docker container on a machine that has access to your Tailnet via a user identity. If that's the case, perhaps network traffic from the container goes to the Tailnet via the host machine rather than directly?

**Comment by jackv24** [comment]
Ahh, you might be right! I'll have to test tomorrow, but yes the host machine is signed in as my tailscale user.

I was maybe confused because the server is also an exit node, which apparently isn't affected by ACLs and is appearing in the status list for the container because of that?

**Comment by jackv24** [comment]
Yep, that was it. Sorry for the trouble, and thanks for the help!
