### ISSUE TITLE
Tailscale ssh allow login to root account...

### ISSUE THREAD

**Issue by moljnir** [tailscale/tailscale#8738]
### What is the issue?

Having enabled tailscale ssh on nodes, an authenticated user is able to ssh into the node using any provisioned account, including the root account.

The existing ssh configuration prohibits login as root. Running the tailscale ssh daemon permits login as root, without validation.

### Steps to reproduce

Create a tailnet of 4 hosts, create 2 groups (engineering, security) and tag one host as security, the other three as engineering. Update the ACL to permit engineering instances to communicate, accessible by members of the engineering group.

invoke ssh to one of the nodes , with "root" as the account. Once one has authenticated via the external provider, if one can access the node, then one can access as root.

### OS

Linux

### OS version

Oracle Linux Server 9.2

### Tailscale version

1.46.0

### Bug report

BUG-9547d56176ddd59c9c909e963515606263e88365cbacc45337b9b3b7eec9b414-20230728141718Z-16506f35217cc872

**Comment by maisem** [comment]
Please provide your ACL file. Does it allow access as "root" in the ssh section?

**Comment by moljnir** [comment]
> Please provide a snippet of your ACL file. Does it allow access as "root" in the ssh section?

I think I need to learn more about the ACLs.... just reading your documentation... I have "root" allowed (right?). I need to remove "root" ... right?

> {
> 			"action":          "check",
> 			"src":             ["group:engineering"],
> 			"dst":             ["tag:engineering"],
> 			"users":           ["autogroup:nonroot", "root"],
> 			"recorder":        ["tag:session-recorder"], // optional field; specify the tag attached to your recorder node.
> 			"enforceRecorder": false, // optional field; defaults to false; if session recorder node is unavailable, should the session be denied?
> 		},

**Comment by moljnir** [comment]
User error; ACL had "root" in users attribute.
