### ISSUE TITLE
wireguard-go/device: testrace failure

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#875]
**Describe the bug**
CI reported a testrace failure in wireguard-go/device:
```
--- FAIL: TestSimultaneousHandshake (0.03s)
    testing.go:1023: race detected during execution of test
FAIL
FAIL	github.com/tailscale/wireguard-go/device	0.863s
FAIL
redo    wireguard-go/device/testrace (exit 1)
redo  testrace (exit 123)
Error: Process completed with exit code 1.
```

**To Reproduce**
This happened during checks from tailscale/corp#793 but did not happen when re-running the checks.

**Comment by sailorfrag** [comment]
https://github.com/tailscale/corp/runs/1329971758

**Comment by DentonGentry** [comment]
The logs for this have expired, and we've now deforked wireguard-go.
