### ISSUE TITLE
tailscale status --json mismatch between user ids and object keys

### ISSUE THREAD

**Issue by MobiusHorizons** [tailscale/tailscale#8769]
### What is the issue?

I am running tailscale on a freebsd arm SBC
```
$ uname -a
FreeBSD <redacted> 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC arm64

$ tailscale -V
1.44.0
go version: go1.20.3
```

When running `tailscale status --json` the User object keys don't match the ID field on each object (two of them are off by one)

for example my users object looks sort of like this:
```
{
  "3***************5": {
    "ID": 3***************4,
    ...
  },
  "5***************5": {
    "ID": 5***************6,
    ...
  },
  "7**************7": {
    "ID": 7**************7,
    ...
  }
}
```

### Steps to reproduce

```
tailscale status --json | jq '.User | to_entries | map({ key: .key, value: .value.ID})'
```

### OS

Other

### OS version

FreeBSD 13.1-RELEASE-p3

### Tailscale version

1.44.0

### Bug report

BUG-8e82ed77ed26b07ad02a7bdb6649f835e81479ae31a51a658985de3d6b80a6f6-20230802032650Z-4066826eb3a3bb78 BUG-8e82ed77ed26b07ad02a7bdb6649f835e81479ae31a51a658985de3d6b80a6f6-20230802032657Z-25fec73a990006e9

**Comment by bradfitz** [comment]
That's actually `jq` lying to you, not `tailscale status --json`. Look at the raw output of `tailscale status --json` and you'll see the real values.

`jq` treats all numbers as float64, like JavaScript. See https://github.com/jqlang/jq/issues/369#issuecomment-44079103 etc.

As a short term workaround if you really want to use jq, https://github.com/itchyny/gojq is another jq implementation that says:

> gojq supports arbitrary-precision integer calculation while jq does not; jq loses the precision of large integers when calculation is involved.

So I assume it also doesn't lose large integers without calculation.

We plan to do something about this, though, but we have to do it carefully without breaking people assuming the current format.

We'll likely be changing things to strings.

We'll probably need to version our local API.

**Comment by MobiusHorizons** [comment]
got it, thanks for the fast response! I should have noticed that. I don't actually intend on using jq, but the data was larger than my terminal so I used it to more easily view the output before writing code that uses it.
