### ISSUE TITLE
FR: Replace default Go user-agent when calling custom OIDC provider's endpoints

### ISSUE THREAD

**Issue by vherrlein** [tailscale/tailscale#8770]
### What are you trying to do?

Statements: 
- Tailscale authentication proces make some calls on several endpoints (Webfinger, Issuer WellKnonwn Urls, ...). 
- Most of on-premises and Cloud OIDC Providers are exposed on internet behind a Web Application Firewall

Issue: 
- As Tailscale authentication is initiated server side with a Go service, it uses the default user agent and trigger an OSWAP Rule which identify queries called by an untrusted bot.

### How should we solve this?

Replacing the default Go user agent (Go-http-client) by something which doesn't trigger any OSWAP Rules and identify calls are legitimate and made from a Tailscale Service.

### What is the impact of not solving this?

Most companies can't disable WAF rules based on that UserAgent as it's too generic.
In addition Tailscale uses Amazon Cloud services which IP ranges or ASN is way too large to put in place exceptions based on IP rules.
Meaning, Tailscale at corporate level become useless as it can not reach company's IDP.

**Comment by bradfitz** [comment]
I sent out a review changing it to "Tailscale/1.0" but it's in a private repo. When this PR is auto-closed it's not necessarily deployed & live but should be in a few days.

**Comment by vherrlein** [comment]
Thank you allot.
I’ll check that within my lab this week.

**Comment by vherrlein** [comment]
I confirm, it's working fine.
thank allot.
