### ISSUE TITLE
User autogroup membership not populated

### ISSUE THREAD

**Issue by kiweezi** [tailscale/tailscale#8773]
### What is the issue?

# Issue
My autogroups do not seem to be populated, despite showing users as being members of them on the users tab.
When adding an autogroup to ACL rules, the user does not show successful tests or previews.

In the [Tailscale ACL documentation](https://tailscale.com/kb/1018/acls/#autogroups), it is said that autogroups are available on all plans.
I feel like I'm going mad and have completely missed the autogroup purpose.

# Proof
You can see that my account `Rhys.Jones@kbtech.co.uk` is a member of `autogroup:admin`
![image](https://github.com/tailscale/tailscale/assets/46600706/92de289b-40bd-4638-af00-48a5f0eef145)

## Failure
Here you can see that the tests and preview fail for `autogroup:admin` and `autogroup:member`:
![image](https://github.com/tailscale/tailscale/assets/46600706/8329936e-7b08-488f-a897-765dbb7af5b3)
![image](https://github.com/tailscale/tailscale/assets/46600706/6fe3843e-69a9-42bb-a9ff-3b1798a02d7e)

## Pass
If I change the autogroups to be direct user emails, tests and previews succeed:
![image](https://github.com/tailscale/tailscale/assets/46600706/09b3db92-4b75-471b-aad7-4ed35ffca801)
![image](https://github.com/tailscale/tailscale/assets/46600706/35633842-289f-449a-8e62-3bd5d0ca7a62)

## Sample
Using a sample from the [documentation of Tailscale](https://tailscale.com/kb/1192/acl-samples/#remote-access-to-corp-and-prod-devices-recommended-initial-acl), I get the same problem.
![image](https://github.com/tailscale/tailscale/assets/46600706/61b3e323-0e2d-4e99-8820-d99216abd6b7)

### Steps to reproduce

I think it might be effecting only my Tailnet, as this would mean the documentation is otherwise incorrect.

Despite this, you can replicate with these ACLs:
```jsonc
// Example/default ACLs for unrestricted connections.
{
	// Define access control lists for users, groups, autogroups, tags,
	// Tailscale IP addresses, and subnet ranges.
	"acls": [
		// All employees can access dev environments.
		{
			"action": "accept",
			"src":    ["autogroup:member"],
			"dst":    ["10.0.0.0/8:*"],
		},
	],

	// Test access rules every time they're saved.
	"tests": [
		// Test member has access to advertised routes.
		{
			"src":    "bob@kbtech.co.uk",
			"accept": ["10.100.0.1:443"],
		},
	],
}
```

### Are there any recent changes that introduced the issue?

No, I've just made an account.
I've added another user since encountering the issue, which hasn't changed things.

### OS

Windows

### OS version

11

### Tailscale version

1.46.1

### Other software

N/A

### Bug report

N/A

**Comment by mayakacz** [comment]
> When adding an autogroup to ACL rules, the user does not show successful tests or previews.

I'm guessing that the autogroups are working as expected (i.e. the users are part of the autogroups), but the tests are not working with the autogroups. Can you confirm if the users have access, and just the tests are not working?

**Comment by kiweezi** [comment]
Sorry for the delay. I tested this today and got the results you suggested.
So it just seems that the autogroups are not taken into account during previews or tests?

I guess at the very least it would be good to make this clear in the documentation.
Although I would really prefer if autogroups would work in previews and tests as our ACLs are primarily using autogroups.

**Comment by kiweezi** [comment]
Sorry! I just realized this is still open. Please feel free to close it :).

I know now after some research that the autogroups do not work in ACL tests. This doesn't effect the real ACL rules being processed, only that you cannot test their effectiveness. 
It is frustrating that this isn't a feature, since basically all our ACLs use them, so we can't really test any of them.
As I said before, I feel a note should be added to the documentation. It should hopefully help people unfamiliar, like me!

For anyone coming across this, there is a feature request open for this at the moment: #4416 
It also has some advice on a workaround for `autogroup:members`, but this only works for me if the user **does** exist.
