### ISSUE TITLE
windows: in server mode, switching users gives an error dialog

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#878]
Steps:
1. Start tailscale
2. Enable server mode / run unattended
3. Log out of Windows
4. Log in
5. Note that the Tailscale GUI works fine
6. Log into Windows as a different user

Expected:
No Tailscale GUI appears, because the Tailscale session doesn't belong to you.

Actual:
A popup appears: `"Tailscale backend error: Tailscale already in use by <username>, pid <pid>"`

This is awkward for a common expected use case, which is Windows Terminal Server, where we install Tailscale once as an admin and then other users log in via RDP. There's no reason to print error messages for them, or for them to even know Tailscale is in use.

As a workaround, the admin could remove Tailscale from the "run on startup" settings, but this will be undone on every upgrade.

Instead, we should add a new command line flag, /quiet-autostart or something, that will silently skip starting the GUI if the backend is already in use. We'll provide this option in the "run on startup" version of the app. If a user manually tries to start the Tailscale GUI, we won't provide this option, and they'll get the informative error message.

**Comment by bradfitz** [comment]
> but I guess github ate them. The values were correct.

Oh, they were interpreted as HTML. I fixed the comment above.

> I assumed you knew this bug already - just writing it down.

I knew about this *feature*. It's working as originally designed and implemented! 😄 

But yes, I knew about how this was annoying for multi-user machines. (What I didn't know was that the Start-Up Items shortcut was for all users)

**Comment by bradfitz** [comment]
Fixed by https://github.com/tailscale/tailscale/commit/20a357b38618c296272e857772d75d836452e7d8; forgot to reference this bug from its commit message.
