### ISSUE TITLE
systemd-resolved stub file being overwritten(?)

### ISSUE THREAD

**Issue by Raltrwx** [tailscale/tailscale#8790]
### What is the issue?

I have been testing out upgrading 5 of my servers from Debian 11 to Debian 12. I am upgrading for many reasons, but definitely one of the main reasons I was excited to do so was so that I could use ```systemd-resolved``` for DNS.

4 out of 5 are working fine with systemd-resolved in stub mode. 

One of my servers however, still was having tailscaled overwrite ```/etc/resolv.conf```. After checking things out, I realized for whatever reason ```/etc/resolv.conf``` was not a symlink to ```/run/systemd/resolve/stub-resolv.conf``` as I expected after installing systemd-resolved, as simply installing/activating ```systemd-resolved``` on my other machines caused the symlinking to happen.

So I did:
```
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
sudo systemctl restart tailscaled
```

It works for a few minutes and I can see this configuration in the symlinked /etc/resolv.conf:

```
nameserver 127.0.0.53
options edns0 trust-ad
search whale-mountain.ts.net
```

This is is what is in all my other servers that aren't having any issues as well, so it seems correct. 

However, after a few minutes or a reboot, I find this in the stub file on my problem server:

```
nameserver 10.20.253.1
nameserver 8.8.8.8
nameserver 208.67.220.222
```

I've been considering ```chattr +i``` on the stub file after I disable/re-enable ```systemd-resolved```'s service, as it does put the correct values in there initially, but I think NetworkManager is overwriting the stub file (Guess/Assumption). 

### Steps to reproduce

I can't properly reproduce this on any of my other servers. 

On the problem server, I just wait or reboot, and eventually no matter what my ```/run/systemd/resolve/stub-resolv.conf``` will no longer have the correct values, DNS completely breaks, and I cannot resolve anything at all. 

I have tried stopping the services ```tailscaled``` & ``systemd-resolved``` and then symlinking the file, and then start them back up, but after a small amount of time, say 5 to 10 minutes, it will be broken again. 

### Are there any recent changes that introduced the issue?

Upgraded Debian 11 to 12. 

### OS

Linux

### OS version

Debian 12.1

### Tailscale version

1.46.1 (Auto-upgrades)

### Other software

Netdata for monitoring, and a few docker containers. 

### Bug report

BUG-9eebfe1c028e6d3521da3a2445923190f6a1494b15c4cf22b16085146af21099-20230803213553Z-ef85991fbfd683be

**Comment by bradfitz** [comment]
Your bug report says it's going into systemd-resolved mode:
 
```
2023-08-03 22:12:41.505606135 +0000 UTC: dns: [resolved-ping=yes rc=resolved nm=yes nm-resolved=yes nm-safe=no resolv-conf-mode=stub ret=systemd-resolved]
2023-08-03 22:12:41.505616492 +0000 UTC: dns: using "systemd-resolved" mode
2023-08-03 22:12:41.505878189 +0000 UTC: dns: dbus connected
2023-08-03 22:12:41.506897394 +0000 UTC: dns: using *dns.resolvedManager
```

So we're not overwriting that file. You must have something else on your machine that's not cooperating nicely. It's probably your DHCP client.

**Comment by shantanugadgil** [comment]
_Searching for my AWS AL2023 error has landed me here, maybe it is related._

On my AWS AL2023 machine, the file `/usr/lib/systemd/resolved.conf.d/resolved-disable-stub-listener.conf` gets overwritten whenever the package `systemd-resolved` gets updated.

If I overwrite this file with custom data, I except `rpm` to not overwrite the file with the usual warning (paraphrasing)
"file modified outside of `rpm` and save a file with the extension `.rpmnew`)

This doesn't work!!!

If system-resolved is upgraded, then the file comes back with original content.
