### ISSUE TITLE
iOS VPN On-Demand settings not saved / UX flow uncertain

### ISSUE THREAD

**Issue by tkyocum** [tailscale/tailscale#8791]
### What is the issue?

Settings made to VPN On-Demand are not saved, and it is unclear what a user should do after tapping "Save"

### Steps to reproduce

* Open the VPN On-Demand settings window
* Toggle VPN On-Demand on
* Under "Connect Automatically On", toggle WiFi and/or Cellular to "Do Nothing"
* Under "MagicDNS" toggle "Detect MagicDNS hostnames" to the on position (note: skipping this step yields the same behavior)
* Tap Save
* Dismiss the window by swiping it down
* Tap VPN On-Demand

You'll see that the interfaces for which "Do Nothing" was selected are now back to "Always"

Setting both interfaces to "Do Nothing" is done to enable MagicDNS hostname detection and automatic connection per the text below the "Detect MagicDNS hostnames" toggle. 

Aside from the actual bug behavior, there are a few UX flow issues on this screen:

* I would expect not to need to set the interfaces to "Do Nothing" in the first place but rather keep the "Always" default. Logically I would expect "Do Nothing" to be just that, regardless of whether I have MagicDNS detection enabled.
* Once tapping Save, I would expect the window to be dismissed and be returned to the settings window or the main display. Without a Back button or other navigation prompt, it's not clear whether the settings were saved or not. This occurs when you access VPN On-Demand settings from the main screen by tapping "yourdomain.com Connected" instead of via the Settings menu.
* The "Learn more" link at the top of the "VPN On-Demand" screen goes to tailscale.com. I presume because an appropriate docs page is yet to exist, but I wanted to point it out anyway.

### OS

iOS

### OS version

16.6

### Tailscale version

1.47.67

### Bug report

BUG-8f6fc51d7412fa308cb51a6121e0e11ba78cc15c7445ed3edf87c6377443b357-20230803232805Z-4b4d50fece3927dd

**Comment by agottardo** [comment]
Thanks for taking the time to write this! You are using the very first iteration of this feature and I already have a few improvements on the way, including fixes for "Do Nothing" sometimes not sticking.

As for the UI, it is not final. The final flow will be a bit different (removing that Save button for starters). Keep watching TestFlight for more coming soon.

**Comment by agottardo** [comment]
TestFlight version 1.47.100 has been submitted to Apple for review. From the change log: 

> This version includes some improvements to the VPN On Demand configuration UI based on your feedback.
> 
> - Removed the 'Save' button from the VPN On Demand configuration view.
> - Any character can now be used in the SSID textfield when setting up a 'Only On' or 'Except On' connection rule.
> - Fixed an issue that could cause 'Do Nothing' connection rules to not be persisted.

The broken link will be fixed soon. If you see further issues, feel free to reach out. Thanks for your feedback!
