### ISSUE TITLE
When I try to register on QNAP, it prompts me that it is not running."

### ISSUE THREAD

**Issue by MilkTeaNo7** [tailscale/tailscale#8792]
### What is the issue?

# Problem

I am using version 1.31. The specific installation file name is Tailscale_v1.32.0_arm_64.qpkg. If I try to use an installation package with a different file name but the same version, the installation will fail. My QNAP model is TS231 and it cannot install the QNAP operating system version 5.0.

When I try to run the program and register, it prompts me that it is not running.
```
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./tailscale up
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # 
```

```
./tailscale -socket var/run/tailscale/tailscaled.sock tailscale up                     
USAGE
  tailscale [flags] <subcommand> [command flags]

For help on subcommands, add --help after: "tailscale status --help".

This CLI is still under active development. Commands and flags will
change in the future.
```

"I tried many methods, but none of them explained how to solve the problem. The program was working fine before, but I encountered these issues after restoring my QNAP to factory settings and reinstalling it."

**Comment by DentonGentry** [comment]
> My QNAP model is TS231 and it cannot install the QNAP operating system version 5.0.

The current https://github.com/tailscale/tailscale-qpkg does not run on QTS 4. It needs a /dev/net/tun device, which QTS 5 provides.

**Comment by MilkTeaNo7** [comment]
> > 我的 QNAP 型号为 TS231，无法安装 QNAP 操作系统版本 5.0。
> 
> 当前的https://github.com/tailscale/tailscale-qpkg无法在 QTS 4 上运行。它需要 QTS 5 提供的 /dev/net/tun 设备。

"Thank you for your reply. I understand that vgs and vgdisplay are both commands used to display LVM volume group information in Linux systems. vgs displays a summary of all volume groups in the system, including the group name, size, and free space, while vgdisplay provides more detailed information about the physical and logical volumes, as well as group properties. However, I previously installed Tailscale successfully on a QNAP device running version 4.0, and I'm not sure if using an older version could solve the current problem. I appreciate your help very much."

**Comment by MilkTeaNo7** [comment]
> > My QNAP model is TS231 and it cannot install the QNAP operating system version 5.0.
> 
> The current https://github.com/tailscale/tailscale-qpkg does not run on QTS 4. It needs a /dev/net/tun device, which QTS 5 provides.

"Thank you for your reply. I understand that vgs and vgdisplay are both commands used to display LVM volume group information in Linux systems. vgs displays a summary of all volume groups in the system, including the group name, size, and free space, while vgdisplay provides more detailed information about the physical and logical volumes, as well as group properties. However, I previously installed Tailscale successfully on a QNAP device running version 4.0, and I'm not sure if using an older version could solve the current problem. I appreciate your help very much."

**Comment by bradfitz** [comment]
Why are you talking about LVM (vgs, vgdisplay)? What does that have to do with Tailscale?

Tailscale the company doesn't support QTS4. Some people in the community used to run Tailscale on QTS4 but nobody's updated in a long time to run on QTS4. Tailscale (the company) only tests on QTS5, as you can't even buy QTS4 hardware anymore these days to test. We tried and it auto-updated itself to QTS5.

So, sorry, I don't think there's anything we can do here.
