### ISSUE TITLE
Tailscale SSH via web interface not working within corporate network

### ISSUE THREAD

**Issue by mh166** [tailscale/tailscale#8805]
### What is the issue?

I cannot use the web client for Tailscale SSH when I'm using any browser on my corporate laptop. Testing at the same time using my private laptop (that is *not* connected to our company VPN) it works flawlessly.

### Steps to reproduce

1. Open https://login.tailscale.com/admin/machines
2. For the desired machine, click "..." > "SSH"
3. Select the username and click on "SSH" to open the connection
4. A new window pops up where the terminal should appear. But instead it stays black.
5. Now go back to the main window, open the Dev-Tools console and find many errors regarding CORS:

![Error logs](https://github.com/tailscale/tailscale/assets/3167596/c4e06028-8e7c-4c5a-bd38-39a798ddaf7f)

It does *not* matter what machine or browser I use on my corporate notebook. So I guess it's a problem in connection with our VPN+Proxy that my employer uses.

### Are there any recent changes that introduced the issue?

Not that I know of...

### OS

Windows

### OS version

Windows 11 22H2 (Build 22621.1992)

### Tailscale version

Tailscale web interface

### Other software

Screenshots created from surfing with Firefox 115.0.2

**Comment by bradfitz** [comment]
Yeah, this seems to be your network doing a MITM and messing with our HTTPS traffic. I just double-checked our codebase and there's no place we ever send a HTTP 407 response code as shown in your screenshot. That 407 is coming from within your company somewhere.

Talk to your IT team I guess?

**Comment by mh166** [comment]
Thanks for the confirmation. I was afraid this would be the case, as there hasn't been any other issue regarding CORS and Tailnet SSH.

As you are more familiar with the inner workings: can you think of a way to further debug or inspect this kind of error? Any other logs that I could gather?

I think it would help my cause with the IT department if I could provide them with further details... 😬

**Comment by mh166** [comment]
Ugh... nevermind. 🙄 I just tried something: I used [`px`](https://github.com/genotrance/px) as (another) proxy in the middle, allowing me to debug the requests on a more basic level than what modern browsers allow (`px --debug` and then looking at `debug-Process-1.log`).

The interesting part from this log:
```
 Curl info: Establish HTTP proxy tunnel to controlplane.tailscale.com:443
 Curl info: Proxy auth using Negotiate with user sanitized len(2)
 Sent header => CONNECT controlplane.tailscale.com:443 HTTP/1.1
 Sent header => Host: controlplane.tailscale.com:443
 Sent header => Proxy-Authorization: Negotiate sanitized len(3208)
 Sent header => User-Agent: curl/8.0.1
 Sent header => Proxy-Connection: Keep-Alive
 Received header <= HTTP/1.1 403 URLBlocked
 Received header <= Content-Type: text/html
 Received header <= Cache-Control: no-cache
 Received header <= Content-Length: 4606
 Received header <= X-Frame-Options: deny
 Received header <= Proxy-Connection: Keep-Alive
 Curl info: Received HTTP code 403 from proxy after CONNECT
 Curl info: CONNECT phase completed
 Curl info: Closing connection 1
```

Okayyy... `403 URLBlocked` doesn't sound good. This reminded me, that our company uses a firewall service bought from... I don't know where. Out of curiosity, I then proceeded to open the URL in question only using HTTP, without SSL. The result:

> **Blocked by URL Filter Database**
> Your requested URL has been blocked. The URL is listed in categories that are not allowed.
> **URL:** http://controlplane.tailscale.com/key?v=58
> **URL Categories:** Anonymizing Utilities, Internet Services
> **Reputation:** Minimal Risk
> 
> URL was blocked due to a local database or cloud cache lookup.

So yeah... SSL encrypted connections simply drop, HTTP-only provide more details. The more you know...

Anyway, thanks for taking your time and sorry for bothering you.
