### ISSUE TITLE
 TLS-terminated TCP service / ALPN issue 

### ISSUE THREAD

**Issue by gawi** [tailscale/tailscale#8809]
### What is the issue?

I'm exposing to the tailnet a plain text gRPC service with TLS termination:

`tailscale serve tls-terminated-tcp:443 tcp://localhost:10000`

```
$ tailscale serve status
|-- tcp://burton.tail464f.ts.net:443 (TLS terminated, tailnet only)
|-- tcp://100.68.174.82:443
|-- tcp://[fd7a:115c:a1e0:ab12:4843:cd96:6244:ae52]:443
|--> tcp://127.0.0.1:10000
```

During handshake, the client is requesting HTTP 2 (`h2`) in the application layer protocol negotiation field. When connecting to the endpoint (i.e. `burton.tail464f.ts.net:443`), the ALPN fails.  

Client behavior can be simulated using `openssl`:

```
$ openssl s_client -connect burton.tail464f.ts.net:443 -alpn h2
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = burton.tail464f.ts.net
verify return:1
---
Certificate chain
[--removed--]
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4125 bytes and written 397 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

The interesting line here is: `No ALPN negotiated`.

When connecting to a public server (not using tailscale), the ALPN outcome is as expected:

```
$ openssl s_client -connect northamerica-northeast1-dialogflow.googleapis.com:443 -alpn h2 
CONNECTED(00000003)
depth=2 C = US, O = Google Trust Services LLC, CN = GTS Root R1
verify return:1
depth=1 C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
verify return:1
depth=0 CN = upload.video.google.com
verify return:1
---
Certificate chain
[ --removed--]
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4696 bytes and written 440 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
ALPN protocol: h2
Early data was not sent
Verify return code: 0 (ok)
---
```

Here: `ALPN protocol: h2`.

### Steps to reproduce

see above

### Are there any recent changes that introduced the issue?

None that I'm aware of.

### OS

Linux

### OS version

Ubuntu 22.04.3 LTS

### Tailscale version

1.46.1   tailscale commit: e42e60103b1ea58d9d06d5a0c77500e44c44f202   other commit: 4cea91365e4754902270ab4a751a897f960b9a18   go version: go1.21rc3

### Bug report

BUG-fe2a27430de325594f22e1586e00aa1bce0c3426f502bc885293dc7035e55ff5-20230807180351Z-db89fa619b8e3b0b

**Comment by bradfitz** [comment]
The `tailscaled`-terminated TLS server doesn't expose any options to let you set your ALPN proto(s). So it's getting lost in the step from TLS termination to the localhost:10000 TCP forwarding.

If you need to negotiate an ALPN protocol, you can pass the TLS TCP connection through `tailscaled` (unterminated) and terminate the TLS yourself in another program, using the cert from `LocalClient.GetCertificate`.

**Comment by gawi** [comment]
Ok. Thanks.

BTW, I see you've added the "funnel" label. This issue is not funnel-specific (even if I have first encountered this problem on a funnel).  Though it might be helpful for others to find the information until it's in the documentation.
