### ISSUE TITLE
FR: Organisation level or global auth keys (machine keys)

### ISSUE THREAD

**Issue by pmcenery-bl** [tailscale/tailscale#8825]
### What are you trying to do?

Scenario: The administrator who created an auth key has left the organisation. Security have deleted the user. All knowledge of how the key was setup including tagging is lost.

The current solution is to then go through the whole process again - as a different user who could also be deleted.

### How should we solve this?

Users are non-permanent entities. They come and go. It should be possible to create keys which are tied to the organisation.

### What is the impact of not solving this?

Connectivity problems when users are deleted. Furthermore, the routers appear to continue to function quite well after the user has been deleted. This could be seen as a security risk in its own right. Only after restarting the router can one discover that the key is no longer valid.

### Anything else?

Related issue:

https://github.com/tailscale/tailscale/issues/6901

**Comment by pmcenery-bl** [comment]
Thanks @DentonGentry

In summary for anyone else running into this issue, the solution appears to be:

- Create an OAuth Client with `Devices` scope (`read` and `write`).
- Use the generated secret key in the `tailscale up ... --authkey=`

I think there are so many different use cases for tailscale that this scenario might not be as obvious when the documentation is first read.

Thank you for pointing it out!

**Comment by DentonGentry** [comment]
Marked as addressed by using an OAuth client. The issue will be as discoverable closed as it is open.
