### ISSUE TITLE
FR: More informative error message when login.tailscale.com not visible

### ISSUE THREAD

**Issue by mareising** [tailscale/tailscale#8855]
### What are you trying to do?

For example certain business wifi systems block VPN access.  We found one today at a doctor's office that blocks login.tailscale.com.  The error message thrown by Tailscale GUI is "tailscale service needs to be restarted".   This led us down the rabbit hole on this troubleshooting thread: https://github.com/tailscale/tailscale/issues/2282 because this happened right after August patch Tuesday for Windows. We tried re-installing, deleting various folders, etc. per the thread, nothing helped.  Eventually we tried a ping and it failed and we figured it out. 

### How should we solve this?

if login.tailscale.com it not reachable error message should say something like "Tailscale server no reachable, verify it is not being blocked by another service or firewall" rather than "Tailscale service needs to be restarted" which implies an installation, registry issue, or some other such problem. 

### What is the impact of not solving this?

We put out a guide to our users to look for this error and if so have them check out a portable cell hot spot to get around the issue, but business time and money can be wasted chasing down the wrong issue.

**Comment by bradfitz** [comment]
I think this is a dup of #7889

Initial planning work is underway now on overhauling all that state machinery.

/cc @dblohm7

**Comment by mareising** [comment]
> I think this is a dup of #7889
> 
> Initial planning work is underway now on overhauling all that state machinery.
> 
> /cc @dblohm7

I see that now, thank you for your efforts!
