### ISSUE TITLE
FR: Self-hosted Funnel/ingress gateway

### ISSUE THREAD

**Issue by renne** [tailscale/tailscale#8867]
### What are you trying to do?

We want to expose services on Tailscale nodes to the public using custom IP addresses, domains and any needed ports.
The specific use-case is we have dynamic IP addresses at our location and an unstable landline connection which has to fall back to cellular service on outages. So we want to set up Tailscale nodes on small virtual private servers as ingress gateways to the Tailscale network.

### How should we solve this?

A Tailscale node should be able to listen on public IPv4/IPv6 IP addresses and forward ports or route full IP addresses to other Tailscale nodes with services for the public.

### What is the impact of not solving this?

Administrators have to fiddle around with port-forwarding/routing on ingress gateway nodes and firewall configurations on service nodes.

**Comment by bradfitz** [comment]
As I wrote in https://tailscale.com/blog/introducing-tailscale-funnel/, doing this by hand is 1 line of config in your `rinetd.conf` file. (that is, run a small VPS with tailscaled + rinetd and you're done). But everybody will want something slightly different. It doesn't seem worth putting it in a supported product as there would be too many configuration knobs for too few of users.

So we seem unlikely to work on this ourselves. Others are welcome to build such a tool externally. IIRC, @saljam built a small tsnet-based rinetd which might be what you want, at least if you're Go-inclined. Otherwise rinetd seems easier.

**Comment by renne** [comment]
@bradfitz
We cannot use rinetd as rinetd forges the sender address to the address of the Tailscale gateway node. That way e.g. a web-server does not get the origin sender address. Instead we want to set `--exit-node=<gateway>` on the Tailscale node with the server.
I'm considering port-forwarding with IPTables, but I don't know how this conflicts with the IPTables rules set by tailscaled.

Is there any documentation what to consider when setting IPTables rules to avoid conflicts with tailscaled subnet-router/exit-node mode?

**Comment by renne** [comment]
@bradfitz 
Network situation:

Location WHM
- fd:0:0:178::0/64
- 192.168.178.0/24
- Landline uplink
  - Dual-Stack
  - dynamic public IPv4 address + NAT
  - dynamic public IPv6 /64-subnet
- RaspberryPi 2B
  -  Subnet-router
- Clients only

Location FFM
- fd:0:0:1::0/64
- 192.168.1.0/24
- Landline uplink
  - Dual-Stack
  - dynamic public IPv4 address + NAT
  - dynamic public IPv6 /64-subnet
  - unstable
- Cellular uplink as backup
  - Dual-Stack Lite
  - dynamic public IPv4 address + CGNAT
  - dynamic public IPv6 /64-subnet
- Proxmox VE host
  - Subnet-router
  - Exit-node
  - VMs (ensure outgoing connections via Data-Center IP-addresses.)
    - Web-server
    - Mail-server
    - Primary nameserver
    - Docker

Location Data-Center:
- LXD-container
- Landline uplink
  - Dual-Stack
  - 2a02:180:6:1::xxxx/128
  - 91.143.88.yyy/32
-  Tailscale exit-node as ingress (DNAT/SNAT)?

Multiple mobile clients

**Comment by renne** [comment]
@skedastically I dropped Tailscale as it does not support Bring-Your-Own-Domain. Now I'm back to port-forwarding and Wireguard on the router.
