### ISSUE TITLE
Admin UI has overlapping text with IPv6 addresses

### ISSUE THREAD

**Issue by jtdowney** [tailscale/tailscale#8881]
### What is the issue?

Not sure if this is where bugs for the admin console go but I figured I'd start here. I have `disableIPv4` set for my tailnet to test a transition where the existing VPN uses the 100.64.0.0/10 IP space. The Admin UI has a CSS glitch where the IP address overlaps the client version.

<img width="1582" alt="Screenshot_2023-08-14_at_9_10_05_PM" src="https://github.com/tailscale/tailscale/assets/44654/c69dee4c-6601-4abb-8f7d-045ed3915542">

### Steps to reproduce

1. Set `disableIPv4` in the ACL for the account.
2. Visit https://login.tailscale.com/admin/machines in a browser.

### OS

macOS

**Comment by bradfitz** [comment]
cc @tailscale/frontend
