### ISSUE TITLE
tvOS: TS will continuously reconnect after manually disconnecting

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#8883]
### What is the issue?

If I click on disconnect, TS automatically reconnects, but not all the time

Or is the expected action when wanting to disconnect ATV is to logout?

TS: 1.47.114 (102)
ATV4Kg2, 17b5 (21J5330e)

### Steps to reproduce

1. Install previous TS on ATV (not sure if this is relevant)
2. Login/connect ATV to Tailnet
3. Upgrade to new TS version on ATV
4. Connect ATV to Tailnet
5. Disconnect ATV from Tailnet

### Are there any recent changes that introduced the issue?

Upgraded to TS: 1.47.114 (102)

### OS

Other

### OS version

tvOS 17b5 (21J5330e)

### Tailscale version

1.47.114 (102)

### Other software

na

**Comment by agottardo** [comment]
Thanks for filing this! And congrats on the first issue related to our tvOS app 😆 

The update to the tvOS app you just installed uses a VPN On Demand configuration to ensure tvOS will automatically restart the tunnel whenever the Apple TV reboots or the VPN gets terminated for any reason. This is meant to provide reliability if you're using the Apple TV as an exit node, for instance.

When you tap the disconnect button in the app, in theory we should be disabling the on-demand logic to allow the tunnel to terminate. Based on your report, looks like there might be some issue in this logic that is causing the tunnel to restart.

I wasn't able to reproduce this issue on my device immediately but I need to investigate further. Will keep you posted.

**Comment by elvisimprsntr** [comment]
@agottardo 

Thanks for the update. Glad to help

Not sure if VPN connect on demand is supposed to work the same way on ATV as iPhone, but I have employer sponsored apps on my iPhone which uses VPN connect on demand.   There is list of very specific apps which are included under the VPN config.  

![IMG_1954](https://github.com/tailscale/tailscale/assets/1215508/4d479074-dba1-4eda-b3be-d06bc5f47cd9)

Should Tailscale on ATV work in a similar away?  Should there be a master switch for all installed apps or a way to pick from the list of installed apps to be included in VPN connect on demand, so only specific apps are using a particular exit node?  

For that matter, should Tailscale on iOS/iPadOS (maybe macOS) be extended the same way?  Or is it all or nothing for Tailscale?

**Comment by agottardo** [comment]
Tailscale is not a per-app VPN, neither on iOS, macOS, or tvOS. All apps can use it, and there is no need to choose any apps.

I'll post here once I have more to share. :)

**Comment by agottardo** [comment]
This has since been addressed. Please let us know if it is still verifying.
