### ISSUE TITLE
FR: Allow setting Taildrop download location

### ISSUE THREAD

**Issue by jrrdmchls** [tailscale/tailscale#8893]
### What are you trying to do?

I currently use Traildrop to send video files from my android device to my Windows machine. Default storage location is 
C:\Users\(username)\Downloads.
The issue I am running into is that the downloads folder is on my boot drive which is significantly smaller than a my raid array. I would like to be able to define a folder other than "Downloads" as my storage in the drive is very limited. 

### How should we solve this?

Allow user to define DRIVE and FOLDER of Traildrop files on the receiving end.

### What is the impact of not solving this?

OS drive running out of space. 

I am able to get around this by moving files from my OS drive to the drive. However If I do not have physical access to my pc this is kind of a headache.

**Comment by bradfitz** [comment]
Seems like you can do this OS-wide? https://www.c-sharpcorner.com/article/how-to-change-the-download-location-in-windows-10/

I think if you do that, we'll respect the OS setting.

Have you tried that already?

cc @dblohm7

**Comment by DentonGentry** [comment]
I believe https://www.c-sharpcorner.com/article/how-to-change-the-download-location-in-windows-10/ is the way to accomplish this.

**Comment by albino1** [comment]
I would like to see this reconsidered for several reasons:

1) Changing a default Windows folder system-wide to accommodate for a single feature of a single app seems unnecessary and overkill.  Particularly considering almost every single app I've ever used allows you to configure folders, something I think most would consider a basic low level function.

2) Not everyone is even allowed by their work to change default system folders.

3) Once you change this folder in the system using the link provided by @DentonGentry, Windows completely co-ops that folder and turns it into your system Downloads folder, meaning whatever that folder was before is now changed.  For me it changed my Work folder into a new folder including renaming it, changing the icon, and moving files.  Trying to change it back leaves it still with the changed folder name and changed icon meaning you have to modify all of that to get it back to normal.  This is messy for sure, but potentially disastrous depending on what location you change it to.

This is all way too much effort with too many downsides for something as simple as trying to send a picture from your phone or sending an excel file to your work computer and have it be placed in your work files.

**Comment by kitgxrl** [comment]
Would definitely love to see this implemented. Often times when I'm using taildrop I'm needing the file immediately and it can be frustrating to sift through all my downloads especially if I don't recall the filename
