### ISSUE TITLE
panic: Tried to generate emptyPrivateKey.Public()

### ISSUE THREAD

**Issue by simonlbn** [tailscale/tailscale#89]
**Describe the bug**
After running for a short-ish while (overnight), tailscaled crashed with a panic this morning:

panic: Tried to generate emptyPrivateKey.Public()

I don't think there was significant traffic - if any just background traffic as I was asleep.

I'm not really sure what other information you need to debug. Happy to answer questions.

**To Reproduce**
Don't know yet at this point.

**Expected behavior**
Not to panic :-)

**Screenshots**

**Version information:**
 - Device: Server, amd64
 - OS: FreeBSD
 - OS version: 12.1-RELEASE-p2
 - Tailscale version: git c47f907a27fd636df1aadee6abcb6059c4f751f8

[simon@fsrv0:tailscale] git rev-parse  HEAD
c47f907a27fd636df1aadee6abcb6059c4f751f8

(Not experienced git user, so I hope this identifies the version. I cloned repo last evening 2020-02-20)

**Additional context**
Had been started with:
~simon/go/bin/tailscaled --state /var/db/tailscaled.state

Terminal output:

91.1M/59.6M netmap packet filter: [*=>*:*]
91.1M/59.6M Configuring wireguard connection.
91.1M/59.6M reconfig: ra=false dns=true 0x01
91.1M/59.6M Reconfig(): configuring userspace wireguard engine.
91.1M/59.6M ...unchanged config, skipping.
91.1M/59.6M SetPrefs: Prefs{ra=false mesh=true dns=true want=true notepad=false pf=true routes=[] Persist{m=[pub:_/iWz], o=[empty], n=[pub:_0koN] u="REDACTED"}}
91.1M/59.6M Switching ipn state Running -> NeedsLogin (WantRunning=true)
91.1M/59.6M blockEngineUpdates(true)
91.1M/59.6M Reconfig(): configuring userspace wireguard engine.
91.1M/59.6M [nCr2_ciUA] - Stopping...
91.1M/59.6M [EDlz_xXjU] - Stopping...
91.1M/59.6M [I2nU_mekE] - Stopping...
panic: Tried to generate emptyPrivateKey.Public()

goroutine 1306 [running]:
github.com/tailscale/wireguard-go/wgcfg.(*PrivateKey).Public(0xc0019e54f8, 0x0, 0x0, 0x0, 0x0)
        /home/simon/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20200219153015-ff5ce9e55c86/wgcfg/key.go:158 +0x12b
github.com/tailscale/wireguard-go/device.(*Device).SetPrivateKey(0xc0000ce580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/simon/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20200219153015-ff5ce9e55c86/device/device.go:269 +0x3c3
github.com/tailscale/wireguard-go/device.(*Device).Reconfig(0xc0000ce580, 0xc00010eb00, 0x0, 0x0)
        /home/simon/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20200219153015-ff5ce9e55c86/device/config.go:82 +0xd14
tailscale.com/wgengine.(*userspaceEngine).Reconfig(0xc000172000, 0xc00010eb00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/simon/src/tailscale/wgengine/userspace.go:234 +0x2f5
tailscale.com/wgengine.(*watchdogEngine).Reconfig.func1(0x80420a768, 0xc00019fe00)
        /home/simon/src/tailscale/wgengine/watchdog.go:64 +0x56
tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func1(0xc00016c1e0, 0xc0005bcba0)
        /home/simon/src/tailscale/wgengine/watchdog.go:40 +0x27
created by tailscale.com/wgengine.(*watchdogEngine).watchdogErr
        /home/simon/src/tailscale/wgengine/watchdog.go:39 +0x77

**Comment by crawshaw** [comment]
Thanks for the bug report. Do you happen to have the full panic message with all the goroutine stacks?

**Comment by simonlbn** [comment]
Unfortunately I don't think so, at least it's not on stdout/stderr and I don't see any log files etc.

My interaction with debugging Go programs have been a bit minimal, but poking a bit around the internet it seems like setting the environment variable "GOTRACEBACK=all" should do the trick in the future, so I started tailscaled up with that variable set, so if it happens again I hope I should get more logs.

**Comment by simonlbn** [comment]
As I had "hoped" it happened again, and it got the more full stack trace this time.
[crash-2020-02-22.txt](https://github.com/tailscale/tailscale/files/4239041/crash-2020-02-22.txt)

I would suspect something around re-auth based on the timing of some time later while mostly idle, but that's pure guess.

**Comment by simonlbn** [comment]
Just relalized I hadn't included go version. Don't know if it's important, but:

go version go1.13.5 freebsd/amd64

**Comment by crawshaw** [comment]
I believe this was fixed in https://github.com/tailscale/wireguard-go/commit/cb9c6e7e6

**Comment by simonlbn** [comment]
Hey,

Confirmed - at least tailscaled not crash for ~24h for me. Thanks!
