### ISSUE TITLE
FR: Visit one container with userspace-networking tailscale from another container with userspace-networking

### ISSUE THREAD

**Issue by diyism** [tailscale/tailscale#8908]
I have one cloud container "A" with "/usr/bin/tailscaled --tun=userspace-networking --port 41641", the tailscale ip of "A" is 100.0.0.1,
and there's redis-server listening on 0.0.0.0:6379 in "A",

I have another cloud container "B" with "/usr/bin/tailscaled --tun=userspace-networking --port 41641", the tailscale ip of "B" is 100.0.0.2,

I can "tcping 100.0.0.1 6379" from my home linux "C"(100.0.0.3), the result:
Ping tcp://100.0.0.1:6379(100.0.0.1:6379) - Connected - time=204.90225ms

but I can't "tcping 100.0.0.1 6379" from "B"(100.0.0.2), the result:
Ping tcp://100.0.0.1:6379 - failed: dial tcp 100.0.0.1:6379: i/o timeout

Is there any way to visit A from B through tailscale?

**Comment by bradfitz** [comment]
See https://tailscale.com/kb/1112/userspace-networking/

If your OS kernel isn't aware of the routes (in userspace networking mode) then applications need to connect out via a proxy, either SOCK5 or HTTP.

**Comment by diyism** [comment]
Thanks for your quick answer, but my test failed:

modified tailscaled in B:
`/usr/bin/tailscaled --tun=userspace-networking --socks5-server=localhost:8085 --port 41641`

installed proxychains4 in B, and the /etc/proxychains4.conf:
`socks5	127.0.0.1 8085`

and tested in B:
```
$ proxychains4 curl https://myip.ipip.net
your ip 34.82.0.12 cloud.google.com

$ proxychains4 tcping 100.0.0.1 6379
Ping tcp://100.0.0.1:6379 - failed: dial tcp 100.0.0.1:6379: i/o timeout
```

What's wrong with my test?

**Comment by bradfitz** [comment]
Is the tcping you're using https://github.com/cloverstd/tcping ?

That's written in Go, which doesn't use libc. Your proxychains4 program looks like it tries to do SOCKS5 using libc interception (LD_PRELOAD), which isn't a 100% reliable approach. It won't work for Go programs.

**Comment by bradfitz** [comment]
Try using e.g. https://nmap.org/ncat/guide/ncat-proxy.html 

Or `curl` has SOCKS5 support too if your port 6379 is something curl supports (HTTP, etc)

**Comment by diyism** [comment]
Cool,  it works just with the redis-cli:
```
$ proxychains4 redis-cli -h 100.0.0.1
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:8085  ...  100.0.0.1:6379  ...  OK
100.0.0.1:6379>
```

Thanks for your help!
