### ISSUE TITLE
command ping higher than command Tailscale ping

### ISSUE THREAD

**Issue by arrow2012** [tailscale/tailscale#8928]
### What is the issue?

tailscale-macos IP : 10.66.0.1
tailscale-linux IP : 10.66.0.2

on tailscale-macos
% ./Tailscale ping 10.66.0.2 ping is 18

but direct ping 10.66.0.2 ping is 40 - 50
% ping 10.66.0.2
![image](https://github.com/tailscale/tailscale/assets/46478986/0eb73abf-3708-464c-8a93-edaa00695192)

![image](https://github.com/tailscale/tailscale/assets/46478986/ece7be90-28a7-485a-888b-4fc2547a4b6b)

### OS

Linux, macOS

### OS version

ubuntu 22.04.02   macos 12

### Tailscale version

1.46.1

### Other software

derp 1.46.1

**Comment by DentonGentry** [comment]
`tailscale ping` stays within the tailnet: it pings the subnet router responsible for 10.66.0.2, and does not leave the subnet router.

**Comment by DentonGentry** [comment]
The routing hop is the reason for the difference in RTT.
