### ISSUE TITLE
FR: tvOS - Subnet Router

### ISSUE THREAD

**Issue by donpiekarz** [tailscale/tailscale#8929]
### What are you trying to do?

I have Tailscale on Apple TV at home LAN, I'd like to connect to other devices on the same network as Apple TV. 

### How should we solve this?

Implement Subnet Router feature for tvOS/iOS

### What is the impact of not solving this?

That's mainly for home users. Many people have Apple TV already at home running all day long, so it would save a lot of electricity and hardware costs compared to running dedicated PC/laptop/RaspPi only for tailscale.

**Comment by michalw2-alt** [comment]
it would be great to have this feature. Any chances for implementation anytime soon?

**Comment by DentonGentry** [comment]
We understand that people want this feature. The best way to express support for it is clicking the reaction emoji in the first post, which feeds into prioritization tools we have built.

I promise we will update the bug when there is something to report.

**Comment by agottardo** [comment]
Tailscale 1.55.54 for tvOS has been submitted to TestFlight for review, and will hopefully be available for install shortly. This update includes subnet routing for Apple TV. 

If you experience any issues with this feature, please open a new issue.

**Comment by agottardo** [comment]
Tailscale 1.56.0 is now rolling out to all users, and contains this feature.
