### ISSUE TITLE
Add Tailscale support for UniFi Dream Machine Pro (UDMP)

### ISSUE THREAD

**Issue by dfcarney** [tailscale/tailscale#894]
i.e. https://store.ui.com/collections/unifi-network-routing-switching/products/udm-pro

Perhaps bundled with https://github.com/boostchicken/udm-utilities

**Comment by bradfitz** [comment]
Dup of #735 I think?

**Comment by dfcarney** [comment]
I think so? Might be nice to put some of the keywords and a link to the udm-utilities repo in #735. Let me know and I can handle that (and close this one).
