### ISSUE TITLE
Exit Node Feature failed after updating to v1.48.0

### ISSUE THREAD

**Issue by ronfischler** [tailscale/tailscale#8942]
### What is the issue?

After upgrading, I found that my exit node, a VPS running Ubuntu 22.04, no longer worked as an exit node. I downgraded back to 1.46.1, restarted the tailscaled daemon, and it was back to functioning normally.

I duplicated the issue using a local server on my LAN, also running Ubuntu 22.04. I tried using this local exit node from devices running various versions of Linux and Android ... no difference: access to the Internet is blocked.

Disabled various features such as Tailnet Lock, Send Files, to no effect. Tailnet SSH enabled or not made, no difference either.

I am using a stock ACL, no tags. There is an ACL entry that was made for Funnel, but have yet to enable this feature on any device.

When using a device upgraded to v1.48.0 as an exit node, ping (ICMP) still works. Anything using TCP/UDP does not, so even a DNS lookup such as: “dig www.google.com @9.9.9.9” will time out.

I have the Tailscale HTTPS feature enabled, and I make heavy use of that in my Tailnet, so I am hesitant to disable it, as I expect “unexpected” problems to occur if I do so.

I looked at journalctl output for tailscaled, and did not see anything different between working and non-working exit nodes: lots of “accept” message in both cases.

Regardless of the exit node issue, all my Tailnet devices reliably communicate with each other, it is only the exit node feature that fails with v1.48.0, and works fine when downgrading back to 1.46.1.

For now my Tailnet exit node has to remain fixed at v1.46.1.

### Steps to reproduce

Upgrade Tailscale from v1.46.1 to v1.48.0, using apt.

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.48.0

### Bug report

BUG-39e013266edb1021979722d7ffa2fe12d301e43476338c63af12ba80b496ffce-20230817215532Z-1f57abe1d9c5a0cd

**Comment by raggi** [comment]
This issue has been addressed with https://github.com/tailscale/tailscale/commit/b040094b908cff76f63d2f81b93397706e2e4605 and https://github.com/tailscale/tailscale/commit/93cab562772fdd1719546d4c54b5ba09452eb411 which will be included in the 1.48.1 release.

**Comment by joaoportela** [comment]
Had the same problem.

Did you try disabling ufw? (just for debugging of course). If that works, I think this could be the solution:

Run: `ufw route allow in on tailscale0`.

Might be worth a shot if someone is having trouble downgrading.

**Comment by bradfitz** [comment]
This was a regression in 1.48.0 and why we withrew it from the download servers. It should be fixed in the upcoming 1.48.1.

**Comment by ronfischler** [comment]
> Had the same problem.
> 
> Did you try disabling ufw? (just for debugging of course). If that works, I think this could be the solution:
> 
> Run: `ufw route allow in on tailscale0`.
> 
> Might be worth a shot if someone is having trouble downgrading.

Tested on my server running Ubuntu 22.04 system, this solution indeed works for me: either disabling ufw or adding the forwarding rule for tailscale0.

**Comment by raggi** [comment]
1.48.1 has been released and will now default to iptables again.

You can test out the newer "detection" which will pick between nftables and iptables based on usage, by setting: TS_DEBUG_FIREWALL_MODE=auto for example in /etc/default/tailscaled.

There is additionally a fix in 1.48.1 that resolves the conflict with ufw that lead to forwarding traffic (subnet routers and exit nodes) from functioning properly.

We plan to re-enable auto-detection in a future release.
