### ISSUE TITLE
FR: SSID persistence in VPN on demand (iOS)

### ISSUE THREAD

**Issue by ellnic** [tailscale/tailscale#8956]
### What is the issue?

This relates to the new VPN on demand in iOS. If you type out a list of SSIDs in the except on / only on settings page, then disable the VPN on demand feature, they do not persist when re-enabled. 

@agottardo this isn’t urgent - just something I’ve noticed. I hope you don’t mind me opening the issue. I don’t want to come across as unappreciative after you’ve just released the feature!

### Steps to reproduce

1. Enable VPN on demand
2. Add a list of SSIDs under only on or except on
3. Come back out into settings and return to VPN on demand - still see the list of SSIDs
4. Disable VPN on demand
5. Re-enable VPN on demand
6. List of SSIDs gone

### Are there any recent changes that introduced the issue?

New feature, so no. 

### OS

iOS

### OS version

16.1

### Tailscale version

1.48.0

### Other software

Test device - none.

**Comment by agottardo** [comment]
This is an issue in our logic. We are needlessly clearing out all on-demand rules when disabling the feature, whereas we can just toggle its state without touching the rules. Should be straightforward to fix.

**Comment by ellnic** [comment]
Thanks 🙏

**Comment by jareds** [comment]
I'm glad this appears to be a simple fix. As another data point for someone using this not saving the SSID settings makes the VPN on demand feature slightly more difficult for my setup. My home internet has limited upload bandwidth so I run an exit node in the cloud. By default I have my configuration set to always use the VPN when on cellular. This isn't a problem unless I want to watch Netflix or similar video services which block obvious VPN's. Currently I have to go into the on-demand settings and adjust the cellular options if I don't want to lose my trusted wifi networks. I know it's only a reduction of a couple steps but it would be quicker to disable and enable vpn on demand

**Comment by agottardo** [comment]
@jareds quick workaround for you: if you turn off "Connect On Demand" from the Settings app instead of the Tailscale app, it should allow you to disable the feature without losing the configuration.

**Comment by jareds** [comment]
@agottardo  Thanks for the work around, this was a big help.

**Comment by agottardo** [comment]
We have a fix up for this, it will land in the next app update.
