### ISSUE TITLE
Docker Hub docs appear to have an error

### ISSUE THREAD

**Issue by cmsj** [tailscale/tailscale#8960]
### What is the issue?

The Docker Hub [docs](https://hub.docker.com/r/tailscale/tailscale) for the official Tailscale image say:

`TS_ROUTES: Accept [subnet routes](https://tailscale.com/kb/1019/subnets/) that other nodes advertise.`

but `TS_ROUTES` actually seems to be for *advertising* routes.

**Comment by DentonGentry** [comment]
DockerHub docs have been updated:
TS_ROUTES: Advertises [subnet routes](https://tailscale.com/kb/1019/subnets/). Equivalent to tailscale set --advertise-routes=. To accept advertised routes, use TS_EXTRA_ARGS to pass in --accept-routes.
