### ISSUE TITLE
Exit node preferences do not persist when app is closed

### ISSUE THREAD

**Issue by cy1der** [tailscale/tailscale#8964]
**OS:** GrapheneOS (Android) 13 TQ3A.230805.001.2023080800
**Tailscale Version:** 1.48.0-t77c732357-g388b71affe8

Since 1.48.0 I noticed that the settings under "use exit node" do not save, only when closing the app while _disconnected_ from the tailnet. This did not happen on earlier versions.

**Replicating:**
1. Have an exit node on your tailnet
2. Point to that exit node on the app
3. Close the app while not connected to the tailnet (by swiping it up on the apps list or force stopping it)
4. The setting should go back to "None" and "Allow LAN access" off

**Comment by luizfeliperc** [comment]
Any news? I noticed this recently on my devices. When turning on the device, the app starts but without connecting, I need to click manually, even choosing the VPN option always active on the device.

**Comment by DentonGentry** [comment]
When there is something to report, we'll post it here.

**Comment by newzj82** [comment]
Same problem.
 Every phone I've tried it with has this issue.
 Pixel 5, Pixel 6, Pixel 7, Pixel 8 Pro.
 None remember the exit node selection under any circumstance after the app is restarted.

**Comment by ORIOLESFan02** [comment]
Still happening on Android 14.

**Comment by Immanuel31** [comment]
I'm a Tailscale fan, but this is annoying ;) Is there a recommended workaround?

**Comment by cy1der** [comment]
Appears to be fixed with the UI revamp
