### ISSUE TITLE
Cannot disassociate device from Tailnet

### ISSUE THREAD

**Issue by mtiller** [tailscale/tailscale#8965]
### What is the issue?

I was using Tailscale at work and I was using it to connect to the work Tailnet.  However, I no longer work at that place and I want to use Tailscale to access my home Tailnet.  I can clear my keychain, but that only erases my authentication from the phone.  Every time I re-authenticate, it wants to connect me to my work Tailnet.  I'm sure this is not an issue with my user identity because all my other devices (using the same Google identity to authenticate) work fine.  It is just my phone that associates my user identity with the wrong Tailnet and I cannot figure out how to clear that.  Things I've tried:

1. Deleting and re-installing the app
2. Deleting the app and its data (from Settings -> Storage)
3. Clearing all browser history for Safari
4. Reset Keychain (from Settings -> Tailscale)

After each of these, I authenticate and it asks me if I want to connect to my work Tailnet.  How can I remove the association between this device and that network **without having access to that network**?  In fact, we stopped using Tailscale (it was just an evaluation) so I don't think we can even access the access panel (I certainly cannot, I don't even work there anymore).

### Steps to reproduce

Fresh install of Tailscale, Login, Authenticate with Google and then the "Reconnect" dialog says "Do you want connect the device <my phone> to the <Work> tailnet?"

### OS

iOS

### OS version

iOS 16.6

### Tailscale version

1.48.0

**Comment by mtiller** [comment]
I should add that it doesn't matter what I use for authentication (I've tried both Google and Github), it always asks me if I want to connect to my work Tailnet.  Further evidence that the device itself is somehow permanently associated with the wrong network.

**Comment by bradfitz** [comment]
There is no information here we can start to debug from.

If you can't share a bugreport or Tailscale IP or bugreport or account names/domains, email them to support@tailscale.com and handle this as a support ticket instead?

**Comment by mtiller** [comment]
Just to be clear, the issue not my willingness to share information (publicly or privately) but rather that I cannot access any of that information to share.  I could not generate a bug report id (the app wouldn't let me click the button) and I couldn't get an IP address because I couldn't join a Tailnet.

However, the good news is that the issue went away.  It seems to coincide with the release of version 1.48.1 of the iOS client.  I can't help but notice there is now a "Tailnet Lock" option in the app (and it is currently set to disabled).  Not sure what that does, but perhaps it is relevant?

My main reason for reporting what I did was that it certainly appeared that Tailscale itself was keeping some kind of record locking my device to a specific Tailnet and that I didn't seem to have any ability to delete that record.  I'm just speculating here.  But, as I said, it seems to be a moot point now because that association seems to have vanished on its own now.

I'll close the ticket.  Thanks.
