### ISSUE TITLE
SSH connection hangs, even when ping is reachable 

### ISSUE THREAD

**Issue by SijmenHuizenga** [tailscale/tailscale#8985]
### What is the issue?

Tailscale has been working flawlessly at most of our laptops, but at 1 laptop we have this super weird issue. `tailscale ssh <tailscale-hostname>` or `ssh <tailscale-hostname>` sometimes hangs for 5+ minutes to indefinably. Then, after some time the ssh connection is established OR the connection is not established at all. When the `ssh` hangs, the target device can still be reached using `ping <tailscale-hostname>`. 

This issue occurs often at one of our employee's laptops. It happens more often at night then during the day in (CEST). When this issue happens, another laptop at another location _does_ work and ssh through the web-interface also works fine. So my guess is that this is an issue in tailscaled on this particular laptop.

Sometimes an ssh connection is successfully opened from this particular device and stays open. But then when on said laptop in a new terminal a new ssh command is executed, it could get stuck like described above.
 
We have also tried doing ssh using the tailscale ip instead of the tailscale hostname, but it still hangs.

### Steps to reproduce

1) Around midnight, on this specific laptop, try to `ssh` into one of our robots
2) The ssh (often) hangs for at 5+ minutes.
3) Connection fails to establish, or if we're luck it successfully connects.

Next time this happens we will run ` tailscale bugreport` to help investigation. Any ideas to further debug would be greatly appreciated. Thanks!

### OS

Linux

### OS version

Ubuntu 22.04.3

### Tailscale version

1.46.1

### Other software

Target device is on tailscale `1.44.0`

Laptop ssh client: `OpenSSH_8.9p1 Ubuntu-3ubuntu0.3, OpenSSL 3.0.2`

**Comment by SijmenHuizenga** [comment]
We discovered that this only happens on a certain wifi network. We now work-around the problem by having the laptop connected to a smartphone 4g wifi hotspot.

**Comment by blaugi** [comment]
Hey there @SijmenHuizenga, how you doing?

I'm running into a very similar issue, where I can ping but can't connect via ssh on wifi, only with 4G. 
Did you end up figuring out a cause?

**Comment by SijmenHuizenga** [comment]
Hi @blaugi, no, we never figured it out what was going on. At some point it magically went away. Now we sometimes still have cases where tailscale won't connect from ubuntu, in those cases `tailscale down` followed by `tailscale up` resolves the issue. Good luck!

**Comment by 0tulpari** [comment]
Hi, little late to the party but i was having same problem, and "sudo ip link set tailscale0 mtu 1200" this solved my problem. Maybe could help people like me who gets there because of same problem. Os debian trixe.

**Comment by harshavmb** [comment]
I have observed this quite often on my Mac pro (intel one), only when its' connected with a Tailscale agent. I also have tailscale installed on my Pfsense, so I could ssh directly without the agent on Mac.

I did ping with larger mtu sizes upto `1200`. Although tailscale says they lock mtu size to `1280`, at my home I couldn't ping packets larger than `1190`. Below that all ping packets had responses. 

Surprisingly, when I turn off tailscale agent, packets as big as 1260 bytes were processed without fragmentation.

Somewhere when using agent, something is eating packet headers above 1190. I didn't spend much time on this as I got it working without agent (I don't need on my mac until I am outside home).

**Comment by hunterboerner** [comment]
I'm having this same issue on macOS (arm)

**Comment by FedeCuci** [comment]
Having the same issue still

**Comment by ansysic** [comment]
Check ~/.ssh/config for a HostName override. SSH may use a private IP while ping uses the Tailscale IP. An existing ControlMaster connection can hide this; close it with ssh -O exit .
