### ISSUE TITLE
Load-balancing across multiple internet uplinks

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#901]
Request from a customer. We're planning to support failover among uplinks, but this request is to use all available uplinks at once, to get all available bandwidth out of a constrained host.

Filing to keep track of the request, though it's not on our immediate roadmap.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/2256 is more recent but has substantially more discussion.

Dup of https://github.com/tailscale/tailscale/issues/2256
