### ISSUE TITLE
Site-to-Site VPN with Subnet Routers does not work

### ISSUE THREAD

**Issue by alexanderniebuhr** [tailscale/tailscale#9044]
### What is the issue?

Setting up everything as described in the Guide on the Website.
Using the VMs running the subnet router, the connection works, however as soon as I try to connect from another VM in the network (which does not have tailscale installed), with uses static route to the subnet router as next hop, I'll get timeouts. Can you look into it, & let me know if you have more detailed logs?

### OS

Linux

### OS version

Debian 12.0

### Tailscale version

 1.48.1

### Bug report

BUG-fd9c82032a4921840aca6e5adbfbe8267a52431ac5dce11f6647101468f82286-20230823190252Z-c7dc14fa4b7a2282

**Comment by NotLazy** [comment]
I'm having the same issue, started happening in the last 24ish hours for me.

BUG-8af1046007c6fdc048d0636acb60eb7468e437741df9d86294e1deb984e60d5b-20230823230432Z-904374438cc0b7df

**Comment by kelivel** [comment]
@alexanderniebuhr Happy to take a look— this is likely to involve personal information about the tailnet, and I'd suggest handling it as a support ticket instead. Emailing support@tailscale.com or using our [contact form](https://tailscale.com/contact/support/) will get you to the right place. We'll troubleshoot from there- thanks! 

@NotLazy I don't see a site-to-site setup on your tailnet. What specifically are you seeing on your side?

**Comment by NotLazy** [comment]
> @NotLazy I don't see a site-to-site setup on your tailnet. What specifically are you seeing on your side?

Maybe I'm not using site-to-site, I'm getting a little mixed up with that terminology. I'm using subnets to connect to lan remotely.

Connecting to 10.0.0.0/8 doesn't work for any device on the lan except the host which is running Tailscale. This was working through when I first setup Tailscale with subnets.

**Comment by kelivel** [comment]
@NotLazy No worries! Let's get a support ticket created for you as well, and we can come back and update this issue later if we find it's related. Drop me a line using the [contact form](https://tailscale.com/contact/support/) while logged into your tailnet and mention my name (Keli), and we'll take a closer look from there to see what's happening with your routes.

**Comment by kelivel** [comment]
Closing this one out for now, and we can reopen later if we find there's a bug lurking. If other folks are having a similar issue, definitely reach out to us at http://www.tailscale.com/support and refer to this issue so we can dig in together!
