### ISSUE TITLE
Tailscale shows 'Waiting for Admin Signing...' on Tailnet that don't use Tailnet lock on Mac OS

### ISSUE THREAD

**Issue by faultables** [tailscale/tailscale#9063]
### What is the issue?

I've logged on to 2 tailnets and used [Fast user switching](https://tailscale.com/kb/1225/fast-user-switching/) features frequently. One of my Tailnet uses [Tailnet lock (beta)](https://tailscale.com/kb/1226/tailnet-lock/) while the other doesn't.

Under normal circumstances it looks like this (Tailnet with Tailnet lock enabled): 

![CleanShot 2023-08-24 at 14 21 19@2x](https://github.com/tailscale/tailscale/assets/6561394/5b01e64b-273e-4478-a380-aa5ab7b1c4f2)

And this is how it looks when I switch to a Tailnet that doesn't use Tailnet lock:

![CleanShot 2023-08-24 at 14 08 52@2x](https://github.com/tailscale/tailscale/assets/6561394/82e519a8-5e9b-4419-8e62-67ce197985ad)

### Steps to reproduce

1. Login to two Tailnet with different accounts
2. Enable Tailnet lock on one of the Tailnet
3. Switch to an account that doesn't use Tailnet lock

The device I'm using (in the previous screenshot) is not the "Signing node"

### OS

macOS

### OS version

Mac OS Sonoma 14.0

### Tailscale version

1.48.1 (App Store)

### Bug report

BUG-474140427c89d33962931742e7a86e1fc9577071779e08589d89490a547655ba-20230824071323Z-93940a39b4a80ec0

**Comment by damien-reyre** [comment]
It seems linked to Tailnet lock on macOS.

We have the same issue from macOS using Tailnet lock.

**Comment by agottardo** [comment]
@damien-reyre are you still hitting this on the latest macOS release?

**Comment by damien-reyre** [comment]
@agottardo 

It seems to be fixed. Thanks.
