### ISSUE TITLE
macOS: adjust DNS via both /etc/resolv.conf and system resolver

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#907]
Customer bug report, not yet reproduced.

MagicDNS on macOS teaches the system resolver about Tailscale DNS entries. It does not modify /etc/resolv.conf.

Some macOS applications read /etc/resolv.conf for DNS instead of consulting the system resolver. Perhaps most notably, this includes Go applications build with cgo disabled, which means it affects docker, kubernetes, etc.

MagicDNS should probably adjust /etc/resolv.conf too.

This should probably block MagicDNS coming out of beta on macOS.

**Comment by bradfitz** [comment]
Do we even have the ability to do that from within the Network Extension App Store sandbox?

Might be an argument in favor of going the System Extension route instead (#718) 

/cc @crawshaw

**Comment by crawshaw** [comment]
What macos apps read resolv.conf?

```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search localdomain
nameserver 192.168.1.1
```

We certainly cannot edit it from inside the sandbox.

**Comment by josharian** [comment]
> What macos apps read resolv.conf?

Go applications build with cgo disabled, which means it affects docker, kubernetes, etc.

Relevant upstream issues:

https://github.com/golang/go/issues/12524
https://github.com/golang/go/issues/16345

**Comment by crawshaw** [comment]
This is fixed in Big Sur, our NetworkExtension automatically updates /etc/resolv.conf with no changes from us.

**Comment by j3th9n** [comment]
I think what I tweeted here in response to a split DNS and search domain issue is related, just FYI:

https://twitter.com/j3th9n/status/1381171835920875523

What I say in the tweets:

"You'll need split DNS (also a DNS resolver for *.tailscale.com inside the tunnel) for this. At least on macOS, as DNS queries for the interface's searchDomains are unable to resolve outside of the tunnel. It prevents DNS leaking. Windows simply falls back to the physical adapter."

And: 

"You might want to check "man 5 resolver" too and the possibilities of adding configs under the (not by default existing) /etc/resolver/ directory, for example a file containing: 
search http://tailscale.com
nameserver 1.1.1.1

scutil --dns will show this above scoped queries."
