### ISSUE TITLE
DNS not working on iOS client

### ISSUE THREAD

**Issue by t0ny-peng** [tailscale/tailscale#9072]
### What is the issue?

I'm on 5G network and I'd like to connect to other devices on my Tailscale network. However, after enabling the Tailscale VPN, I cannot even visit any website. 8.8.8.8 is available via ping so it seems to be a DNS issue.
![IMG_2645](https://github.com/tailscale/tailscale/assets/4816327/b23ff33f-0c64-4479-9542-4d463543c11e)

### Steps to reproduce

Install Tailscale and login with my account.

### Are there any recent changes that introduced the issue?

Update Tailscale

### OS

iOS

### OS version

16.5.1

### Tailscale version

1.48.0

**Comment by DentonGentry** [comment]
The template asks for a bugreport because without it, there is really nothing we can investigate.
I think this is likely to involve personal information about the tailnet, and I would suggest handling it as a support ticket instead: https://tailscale.com/contact/support/
