### ISSUE TITLE
Cannot Remove Deleted Tag from device

### ISSUE THREAD

**Issue by Hiekki4** [tailscale/tailscale#9107]
### What is the issue?

After i deleted a tag, i was unable to remove it from the device.

### Steps to reproduce

Create Tag
Allocate to Device
Remove Tag
Remove Tag from device

### OS

Other

### Bug report

`BUG-65120be1a39e83fea5d07943a89cd35b22f9524fcfe8e2c0d5461d54204b1b6f-20230828133540Z-d87190567eba49a5`

**Comment by DentonGentry** [comment]
The template asks for a bugreport because without it, we cannot look up any telemetry nor information about the tailnet and are unlikely to make progress on it.

**Comment by Hiekki4** [comment]
Because it was on the UI, i thinked that it was not needed.

**Comment by maisem** [comment]
This should be fixed now.
