### ISSUE TITLE
Tailnet lock not properly disabled with disablement secret

### ISSUE THREAD

**Issue by zhiyuan-lin** [tailscale/tailscale#9123]
### What is the issue?

I have configured Tailnet lock (a beta feature) with `Send disablement secret to Tailscale support` disabled.
After some days of usage, I decided to disable it via one of my disablement secret on a signing node, the command was completed without any error. The web interface shows the Tailnet lock is disabled.

However days later, I registered a new device in my Tailnet, it shows up in the Tailscale web admin without issue, but it cannot ping nor receive ping for other existing devices. After a weekend of debugging, I discovered that all the existing devices, except the signing node that I used to sent disablement secret, they all still have the Tailnet lock active locally, without anything showing in the web admin interface.

I have to do signout then signin manually on all affected nodes to remove the lock.

### OS

Linux, Windows, iOS, Synology

### OS version

Ubuntu 22.04, Synology DSM 7, Windows 10, Windows 11, iOS 16

### Tailscale version

1.48.1

### Bug report

BUG-bb39c2bd419fe7048b8b5fcf5453a80559397912af9148078c793be7a32f2035-20230829031129Z-48163f03a6a080e2

**Comment by twitchyliquid64** [comment]
`1.48.1` & late august was around the time that we had a bug that would halt processing of tailnet lock state, since fixed in both new versions and in Control. Have you / anyone been able to repro since?

**Comment by zhiyuan-lin** [comment]
> `1.48.1` & late august was around the time that we had a bug that would halt processing of tailnet lock state, since fixed in both new versions and in the coordination server. Have you / anyone been able to repro since?

I cannot reproduce in newer version, I think we can close this one.
