### ISSUE TITLE
github.com/tailscale/wireguard-go: run tests on GitHub Actions

### ISSUE THREAD

**Issue by alexbrainman** [tailscale/tailscale#913]
While debugging issue https://github.com/tailscale/tailscale/issues/474#issuecomment-721612218, I though it might be useful to ask user to run some tests on their machine to uncover problems with Tailscale code or user machine misconfigured.

And we run tests on github.com/tailscale/tailscale.

I tried running tests on github.com/tailscale/wireguard-go. And they pass on Linux, but they don't even compile on Windows.

```
# github.com/tailscale/wireguard-go/tun/wintun/registry
tun\wintun\registry\registry_windows.go:186:11: undefined: "golang.org/x/sys/windows".UTF16PtrToString
FAIL    github.com/tailscale/wireguard-go/device [build failed]
ok      github.com/tailscale/wireguard-go/device/tokenbucket    0.036s
ok      github.com/tailscale/wireguard-go/ratelimiter   0.036s
ok      github.com/tailscale/wireguard-go/replay        0.034s
# github.com/tailscale/wireguard-go/tun/wintun/registry [github.com/tailscale/wireguard-go/tun/wintun/registry.test]
tun\wintun\registry\registry_windows.go:186:11: undefined: "golang.org/x/sys/windows".UTF16PtrToString
ok      github.com/tailscale/wireguard-go/tai64n        0.040s
FAIL    github.com/tailscale/wireguard-go/tun/wintun/registry [build failed]
ok      github.com/tailscale/wireguard-go/tun/wintun/setupapi   1.674s
ok      github.com/tailscale/wireguard-go/wgcfg 0.041s
```

I used `go version devel +5ca43acdb3 Wed Nov 4 06:14:02 2020 +0000 windows/amd64` to run tests.

Perhaps we should make github.com/tailscale/wireguard-go tests run on every PR, like we do with github.com/tailscale/tailscale.

Alex

**Comment by bradfitz** [comment]
Ah, the go.mod file is not updated there.

It works for us in our parent meta repo because the meta repo's go.mod has a newer golang.org/x/sys version.

But yeah, getting it working in CI sounds good.

**Comment by veera83372** [comment]
if we are doing this as compatibility check, shouldn't this be running every time regardless of OS. 
I would like work on this ticket

**Comment by alexbrainman** [comment]
@veera83372 

> if we are doing this as compatibility check, shouldn't this be running every time regardless of OS.

It should be running for every OS that Tailscale supports.

> Anyways,I would like work on this ticket

Sure, go ahead. You can, probably, copy some code from

https://github.com/tailscale/tailscale/tree/main/.github/workflows

I would just run all Go tests. Perhaps you can combine all workflows into single file (for all OSes).

Alex

**Comment by alexbrainman** [comment]
@bradfitz I tried pushing go.mod change to https://github.com/tailscale/wireguard-go, but I get this error

```
$ git push --set-upstream origin alexbrainman/update_go_mod
ERROR: Permission to tailscale/wireguard-go.git denied to alexbrainman.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$
```

Is that something you can help me with?

Thank you.

Alex

**Comment by bradfitz** [comment]
@alexbrainman, I think @josharian and @crawshaw are trying to keep that repo a bit more locked down (PRs only) so they can keep track of how we're forked from upstream and work to minimize it. Feel free to send @josharian a PR for it.

**Comment by alexbrainman** [comment]
> Feel free to send @josharian a PR for it.

Done. https://github.com/tailscale/wireguard-go/pull/25

Alex
