### ISSUE TITLE
FR: Map Impersonate-Group header with ACL groups

### ISSUE THREAD

**Issue by mrkwtz** [tailscale/tailscale#9130]
### What are you trying to do?

We would like to give Kubernetes API access via the Kubernetes operator auth proxy. If I understand the documentation / code correctly you can do RBAC based on user (the eMail address of the Tailscale user) or group (the tag(s) of the device calling the Kubernetes API). 

We would like to use the ACL groups property with Kubernetes RBAC. It's also IMHO counter intuitive that the tags map to groups and not the groups map to groups. 

### How should we solve this?

I've no actual ideas about the practical implementation.

### What is the impact of not solving this?

The workaround would be using device tags but that would mean we have to maintain the "groups" twice. Once with tags added to the devices and additionally put the user into groups to use them inside the ACL policy. 

### Anything else?

If you have any other, more elegant, workaround, we would love to hear about it :)

**Comment by irbekrm** [comment]
Thanks for opening the issue @mrkwtz .

I believe this has now been implemented, see https://tailscale.com/kb/1236/kubernetes-operator#impersonating-kubernetes-groups-with-acl-grants
Let us know if this works for you.

**Comment by mrkwtz** [comment]
Hi @irbekrm thanks for providing the update :) It sure seems like the thing we wanted. Because it was not there at the time we went with a different solution. Will try that out once we see the need :)
