### ISSUE TITLE
windows: sspi panic failed to fetch Negotiate package info: The requested security package does not exist

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#9131]
One of the top Windows crash in 1.48.x ...

```
08:18:31 | local disk logdir: C:\ProgramData\Tailscale\Logs
08:18:31 | Program starting: v1.48.1-t528f95da6-gc4e4acad7, Go 1.21.0: []string{"C:\\Program Files\\Tailscale\\tailscaled.exe"}
08:18:31 | cleaning log files; number of files 51 > 50
08:18:31 | cleaned log file C:\ProgramData\Tailscale\Logs\tailscale-service-20230714T000000-1689318000.txt (size 436385); new bytes=18851328, files=50
08:18:31 | LogID: e0e35ae00378af2bde773e73159d54c25a8f0fd2fba619f80d745ff0bcf5984d
08:18:31 | logpolicy: using dir C:\ProgramData\Tailscale
08:18:31 | Running service...
08:18:32 | Support Info: {"registry":{"HKLM\\SOFTWARE\\Tailscale IPN":{"":"C:\\Program Files\\Tailscale\\","MSI":1}}}
08:18:32 | exec: "C:\\Program Files\\Tailscale\\tailscaled.exe" [/subproc e0e35ae00378af2bde773e73159d54c25a8f0fd2fba619f80d745ff0bcf5984d]
08:18:33 | panic: failed to fetch Negotiate package info: The requested security package does not exist
08:18:33 |  
08:18:33 | goroutine 1 [running]:
08:18:33 | github.com/alexbrainman/sspi/negotiate.init.0()
08:18:33 | github.com/alexbrainman/sspi@v0.0.0-20210105120005-909beea2cc74/negotiate/negotiate.go:30 +0x89
08:18:33 | subprocess exited: exit status 2
08:18:33 | babysitProc: backoff: 6 msec
```

/cc @dblohm7

**Comment by dblohm7** [comment]
[Bad syscall definition](https://github.com/alexbrainman/sspi/blob/909beea2cc7490802e4be2af0600202db533536b/zsyscall_windows.go#L58)

[Docs](https://learn.microsoft.com/en-us/windows/win32/api/sspi/nf-sspi-querysecuritypackageinfow) say the package name is a `*SECURITY_STRING`, not a `*uint16`.

**Comment by alexbrainman** [comment]
> [Bad syscall definition](https://github.com/alexbrainman/sspi/blob/909beea2cc7490802e4be2af0600202db533536b/zsyscall_windows.go#L58)
> 
> [Docs](https://learn.microsoft.com/en-us/windows/win32/api/sspi/nf-sspi-querysecuritypackageinfow) say the package name is a `*SECURITY_STRING`, not a `*uint16`.

Indeed.

@dblohm7 do you want to send a PR for the fix?

I am currently travelling so I will be slow to reply.

Thank you.

Alex

**Comment by dblohm7** [comment]
Oh wow, the mystery deepens!

Looking directly at the relevant C headers, `QuerySecurityPackageInfoW` is declared with different prototypes depending on whether the SDK is configured for user mode or kernel mode. The user mode variant does in fact use a normal null-terminated string, while the kernel mode variant uses `PSECURITY_STRING`.

Unfortunately whatever documentation tooling that Microsoft switched to does an absolutely terrible job of dealing with C preproceessor goop, and in this case it chose the wrong variant for the user mode docs. IOW, the `sspi` package is actually doing the right thing.

Which I guess brings us straight back to the original problem: why the hell is the OS failing with the `Negotiate` package?

**Comment by bradfitz** [comment]
As a short term fix, should we just ignore that error (rather than panicking) and instead log an [unexpected] line and proceed without that tshttpproxy functionality?

**Comment by alexbrainman** [comment]
> Looking directly at the relevant C headers, `QuerySecurityPackageInfoW` is declared with a different signature depending on whether the SDK is configured for user mode or kernel mode.

You are correct. I also looked at Mingw /usr/share/mingw-w64/include/sspi.h and `pszPackageName` parameter is `WCHAR` for `SECURITY_WIN32` define. So `github.com/alexbrainman/sspi` code is correct.

> Which I guess brings us straight back to the original problem: why the hell is the OS failing with the `Negotiate` package?

I looked at the error message again:

> 08:18:33 | panic: failed to fetch Negotiate package info: The requested security package does not exist

And I guess that the Negotiate SSPI package was not loaded at the time your program run. Just a guess. Maybe Windows loads SSPI dlls and shit as it boots. If you are able to reproduce the problem, I suggest you just try to call `QueryPackageInfoW` again after some time.

> As a short term fix, should we just ignore that error (rather than panicking) and instead log an [unexpected] line and proceed without that tshttpproxy functionality?

I should have had

```
func PackageInfo() *sspi.PackageInfo
```

instead of

```
var PackageInfo *sspi.PackageInfo
```

here
 https://github.com/alexbrainman/sspi/blob/909beea2cc7490802e4be2af0600202db533536b/negotiate/negotiate.go#L23-L24 and in all other packages. Then I could have called `QueryPackageInfoW` from that function (once) and returned the error instead of panicking.

If my suggestion suits you, you are welcome to send a PR with the changes. This will break all existing code, so we would need to update the version of the package.

Alex

**Comment by bradfitz** [comment]
I sent https://github.com/alexbrainman/sspi/pull/13

**Comment by alexbrainman** [comment]
> I sent [alexbrainman/sspi#13](https://github.com/alexbrainman/sspi/pull/13)

Just merged your PR. Thank you.

Alex
