### ISSUE TITLE
FR: Add Google Chat as a Webhook Destination

### ISSUE THREAD

**Issue by filviu** [tailscale/tailscale#9154]
### What are you trying to do?

Currently if I want webhook alerts in google chat I need to setup an endpoint that translate to something google chat understands. 

There are a lot of Google shops around and many of unfortunate us use Google Chat because it's already included and deemed "good enough, no reason to pay for Slack" by managment 😉 

### How should we solve this?

Add Google Chat as a destination besides Slack, Discord and Mattermost.

Documentation is here: https://developers.google.com/chat/how-tos/webhooks

Should be simple enough, I was able to do it from nagios with bash, I'm sure you guys can handle it 🤣 

### What is the impact of not solving this?

I need to run something like n8n or even worse some duct tape and wire api endpoint written by me.

**Comment by DentonGentry** [comment]
From https://developers.google.com/chat/how-tos/webhooks, it appears that the JSON posted to Google has only a single field:
```
    app_message = {'text': 'Hello from a Python script!'}
```

**Comment by icio** [comment]
Hi @filviu, we'll now identify and format webhooks for Google Chat webhook URLs. Just create a webhook according to [Google Chat's webhook instructions](https://developers.google.com/chat/how-tos/webhooks) then in your [tailnet webhook settings](https://login.tailscale.com/admin/settings/webhooks), click Add Endpoint... and paste that URL into the dialog, select which webhook notifications you want, and Add Endpoint to finish. Let us know how you get on 😄

**Comment by filviu** [comment]
Whoa that was fast. Cool ! 

But something is still not working. I can see Google Chat in the list of destinations. And when I paste the url it autodetects that it's google chat but clicking "Test endpoint..." doesn't send anything. I tested my url using the following:

```bash
#! /usr/bin/env bash
curl -s -4 -X POST "https://chat.googleapis.com/v1/spaces/xxxxxxxxxxx/messages?key=aaaaaaaaaaaaaaaaaaaaaaaaaaaa&token=bbbbbbbbbbbbbbbbbbbbbbbbbbb" \
  -H 'Content-Type: text/json; charset=utf-8' \
  -d '{
    "text": "Test message 123",
}'

```

and it works.

**Comment by icio** [comment]
Ah! I've jumped the gun. There's actually one more bit I need to deploy 🙈 Apologies for the confusion, @filviu. _brb_

**Comment by icio** [comment]
The last moving part that does the webhook formatting has been deployed now, and I've just successfully received a webhook into Google Chat for my personal tailnet. So you should be good to go now!

Thanks for checking that so quickly.

**Comment by filviu** [comment]
Confirmed on my side too. I just tested and it sends the test event just fine. Also added a comment to the policy and I get the notification and the diff (which is really cool, didn't expect it 🎉 )

Thanks !!

**Comment by icio** [comment]
Same. I learned about the diff in the process of adding Google chat support and really liked it 😄

I'm glad this was useful, @filviu. Please do let us know if you have any further requests or bump into issues.
