### ISSUE TITLE
tailscale is down in our entire country

### ISSUE THREAD

**Issue by AlirezaKhodaei** [tailscale/tailscale#9158]
### What is the issue?

hi
it's about 3 days that tailscale is completely down in IRAN
we cant login
or even we cant see the admin page
This alert shows up:
Service unavailable for legal reasons

as you know people in IRAN are limited by heavy internet filtering by the government, so we use tailscale to reach freedom of information 

in this 3 day we can't even reach to instagram, facebook, CNN, telegram, watsapp and ...
because their all blocked in Iran

we need tailscale for this bizarre situation

**Comment by alamal1950** [comment]
Greetings. Please help. There is a problem with the connection
This is the message that appears to me
![لقطة الشاشة 2023-08-30 150536](https://github.com/tailscale/tailscale/assets/143606152/f84355b9-fd0d-42ea-8096-8dd726e40a6b)

Service unavailable for legal reasons
Please contact me via email to solve the problem
hama.aacc@gmail.com

**Comment by DentonGentry** [comment]
We are legally required to deny service to clients in certain countries and regions.

**Comment by DentonGentry** [comment]
We are legally required to deny service to clients in certain countries and regions.
