### ISSUE TITLE
API authentication behaviors

### ISSUE THREAD

**Issue by xinmans** [tailscale/tailscale#9180]
### What is the issue?

use # passing token with basic auth model to access api failure
but
change to # passing token as bearer token, success! why?

### Steps to reproduce

https://github.com/tailscale/tailscale/blob/main/api.md

Authentication
Requests to the Tailscale API are authenticated with an API access token (sometimes called an API key). Access tokens can be supplied as the username portion of HTTP Basic authentication (leave the password blank) or as an OAuth Bearer token:
# passing token with basic auth
curl -u "tskey-api-xxxxx:" https://api.tailscale.com/api/v2/...

# passing token as bearer token
curl -H "Authorization: Bearer tskey-api-xxxxx" [https://api.tailscale.com/api/v2/...](https://api.tailscale.com/api/v2/)

but, 

root@d4aa23849605:/# curl -u "tskey-api-xx-xx"  https://api.tailscale.com/api/v2/tailnet/xinmans@gmail.com/devices
Enter host password for user 'tskey-api-xx-xx':

change to # passing token as bearer token, success! why?

root@d4aa23849605:/# curl -H "Authorization: Bearer tskey-api-xx-xx" https://api.tailscale.com/api/v2/tailnet/xinmans@gmail.com/devices
{"devices":[{"addresses":["11.11.11.11","fd7a:xxx:ab12:4843:xxx:xx:eb4a"],"a

### OS

Linux

### OS version

ubuntu20.04

**Comment by DentonGentry** [comment]
You're saying that these work:
- `curl -u "tskey-api-xxxxx:" https://api.tailscale.com/api/v2/...`
- `curl -H "Authorization: Bearer tskey-api-xxxxx" https://api.tailscale.com/api/v2/...`

But this doesn't:
```
# curl -u "tskey-api-xx-xx" https://api.tailscale.com/api/v2/...
Enter host password for user 'tskey-api-xx-xx':
```

?

**Comment by willnorris** [comment]
It's prompting for a password because you are missing the trailing `:` in the `-u` value which indicates that there is no password.

From the curl man page:

```
-u, --user <user:password>
              If you simply specify the user name, curl will prompt for a password.
```
