### ISSUE TITLE
no package for Arch linux found

### ISSUE THREAD

**Issue by pratikbalar** [tailscale/tailscale#919]
**Describe the bug**
try to build package using `pamac build tailscale` Arch linux Manjaro but 404 

**To Reproduce**
`pamac build tailscale` in archlinux

**Expected behavior**
should install successful 

**Screenshots**
![image](https://user-images.githubusercontent.com/68642400/98938243-9c2e1380-250d-11eb-9c42-90f17abbbb04.png)

**Version information:**
 - OS: Arch linux - Manjaro 
 - OS version: 20 Gnome 
 - Tailscale version: 1.2.2-1

**Additional context**

**Comment by danderson** [comment]
Looks like you need to update your package indexes. Assuming Manjaro works like Arch, `pacman -Sy` will update your indexes, then the download of go's deps will work.

**Comment by pratikbalar** [comment]
@danderson it was not index problem anyway It's working now,

1. update index `pacman -Syu`
2. download tailscale `PKGBUILD` file from AUR(https://aur.archlinux.org/packages/tailscale/)
3. run `makepkg` in same directory as `PKGBUILD` file as user (it will not run on `root`), which will generate `tailscale-xxxxx.pkg.tar.xz`
4. install that package via `pacman -U tailscale-xxxxx.pkg.tar.xz`, tailscale installed in your arch.
> **NOTE**:  make sure you have satisfied dependency for tailscale before installation.

**Comment by pratikbalar** [comment]
@danderson it was not index problem anyway It's working now,

1. update index `pacman -Syu`
2. download tailscale `PKGBUILD` file from AUR(https://aur.archlinux.org/packages/tailscale/)
3. run `makepkg` in same directory as `PKGBUILD` file as user (it will not run on `root`), which will generate `tailscale-xxxxx.pkg.tar.xz`
4. install that package via `pacman -U tailscale-xxxxx.pkg.tar.xz`, tailscale installed in your arch.
> **NOTE**:  make sure you have satisfied dependency for tailscale before installation.

**Comment by danderson** [comment]
You might want to check out tools like [aura](https://aur.archlinux.org/packages/aura-bin), which makes AUR packages as easy to install as regular Arch packages.
