### ISSUE TITLE
Magicsock refuses to downgrade from LAN to DERP

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#92]
## Steps to reproduce

Be on bradfitz's LAN.
Block all UDP traffic to/from bradfitz's dev box.
Run tailscaled.
Tailscaled peers with bradfitz's dev box over DERP, because LAN doesn't work.
Remove UDP blocks. Direct LAN connectivity now available.
Tailscaled notices this on the next handshake cycle, upgrades from DERP to LAN \o/
Put UDP blocks back. Direct LAN connectivity is broken.
Notice that tailscaled never downgrades from LAN back to DERP. Connectivity remains broken until you restart tailscaled.

During the outage, tailscaled periodically logs:

Feb 21 15:02:12 vega tailscaled[2996756]: 2020/02/21 15:02:12 magicsock: rx [pub:…xg0R] from low-pri 127.3.3.40:1 (0), keeping current 10.0.128.103:41641 (2)

So it's receiving nothing from LAN, and receiving handshakes from DERP, but refusing to downgrade.

**Comment by crawshaw** [comment]
FWIW I don't think this failure to downgrade to DERP should block us rolling out DERP, because it's still strictly better than what we have today.

As to this particular bug, one workaround would be an AddrSet keeping a `lastSeen time.Time` for the current priority, and if X seconds have passed since then, reset the priority to nothing.

**Comment by bradfitz** [comment]
@crawshaw, yup, that was basically our conclusion. Or every new WireGuard handshake, we set the AddrSet curIndex back to -1 and let it re-upgrade back to the best it can.

**Comment by crawshaw** [comment]
I like that, you can condition on just outbound handshake{init,response}. Very lightweight.

**Comment by bradfitz** [comment]
This seems reasonably fixed now by the latest change.  I saw it upgrade & downgrade both ways reliably the other day when I blocked LAN UDP.

Closing.
