### ISSUE TITLE
failed to connect to local tailscaled

### ISSUE THREAD

**Issue by NS-FDF** [tailscale/tailscale#9220]
### What is the issue?

i have start the tailscaled, but use the  'tailscale status' is error

#tailscaled start info
> logtail started
Program starting: v1.46.0-ERR-BuildInfo, Go 1.21.0: []string{"tailscaled"}
LogID: dd30f733dd3af5cc8ce9751f96e32033ec0dca6f322095e185380521bcf62630
logpolicy: using system state directory "/Library/Tailscale"
wgengine.NewUserspaceEngine(tun "utun") ...
dns: using *dns.darwinConfigurator
link state: interfaces.State{defaultRoute=en1 ifs={en1:[192.168.3.112/24] utun1:[26.26.26.1/29]} v4=true v6=false}
magicsock: disco key = d:6a3ef21ee64290fb
Creating WireGuard device...
Bringing WireGuard device up...
Bringing router up...
external route: up
Clearing router settings...
Starting network monitor...
Engine created.
pm: migrating "_daemon" profile to new format
logpolicy: using system state directory "/Library/Tailscale"
got LocalBackend in 6ms
Start
Backend: logs: be:dd30f733dd3af5cc8ce9751f96e32033ec0dca6f322095e185380521bcf62630 fe:
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
health("overall"): error: state=NeedsLogin, wantRunning=false
wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}

#error info
> error fetching current status: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp 127.0.0.1:49163: connect: connection refused

### OS

macOS

### OS version

13.1

### Tailscale version

1.48.1

**Comment by bradfitz** [comment]
You say 1.48.1 but your snippet of logs says 1.46.0.

It's likely you're running a mix of versions and that's the problem.

**Comment by clo4** [comment]
Ah, this fixed it for me -- `sudo rm -rf /Library/tailscaled` was solution.
https://github.com/tailscale/tailscale/issues/5761#issuecomment-1635129629

**Comment by catzkorn** [comment]
We are going to mark this as closed seeing as there has not been further discussion.

**Comment by gachikuku** [comment]
for me it didn't

```
mac:~$ tailscale --version
1.81.0-ERR-BuildInfo
  track: unstable (dev); frequent updates and bugs are likely
  go version: go1.24.0
mac:~$ tailscaled --version
1.81.0-ERR-BuildInfo
  track: unstable (dev); frequent updates and bugs are likely
  go version: go1.24.0
mac:~$ which tailscale
/Users/gachikuku/go/bin/tailscale
mac:~$ tailscale up
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 1497). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp 127.0.0.1:0: connect: can't assign requested address
mac:~$ sudo rm -rf /Library/Tailscale
mac:~$ tailscale up
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 1497). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial tcp 127.0.0.1:0: connect: can't assign requested address
mac:~$

```

**Comment by DontBreakAlex** [comment]
I had the same issue, the docs prompt you to build tailscale from master, which produces this error (at lease for me). I was able to fix it by deleting everything and installing with the current stable version:
```
go install tailscale.com/cmd/tailscale{,d}@v1.80.2
```
