### ISSUE TITLE
FR: Helm Chart for k8s-operator

### ISSUE THREAD

**Issue by jakedgy** [tailscale/tailscale#9222]
### What are you trying to do?

I'd like to simplify the installation of the [k8s-operator manifests](https://github.com/tailscale/tailscale/tree/main/cmd/k8s-operator/manifests).

### How should we solve this?

Create a tailscale-operator Helm chart to support the installation and customization of the k8s-operator via Helm.

### What is the impact of not solving this?

Users have to edit and apply the [example manifests](https://github.com/tailscale/tailscale/tree/main/cmd/k8s-operator/manifests).

### Anything else?

This came up in a discussion about specifying a custom nodeSelector in the proxy StatefulSet template in #9062.

**Comment by jakedgy** [comment]
I've started working on a Helm chart that we can use to get this started -- I'll open a WIP PR and link it to this issue.

There's some [additional discussion](https://github.com/tailscale/tailscale/issues/9062#issuecomment-1703089626) about making some minor changes to the operator to support customizing the proxy template.  I'll go ahead and include that ConfigMap in the initial draft with a flag to enable/disable the ConfigMap for now.

This raises a couple other questions that I'm not going to address just yet.

1. What repository do we use for publishing the Helm chart?  I've used [chart-releaser](https://github.com/helm/chart-releaser-action) before and just packaged it as a GitHub release.
1. Additional CI concerns (helm-test, automated documentation, etc.)

**Comment by Valien** [comment]
Another idea: Add the operator info to -- https://operatorhub.io -- a central place to find different kinds of operators.

**Comment by irbekrm** [comment]
We have now published the Tailscale Kubernetes Operator Helm chart, see the updated installation instructions in https://tailscale.com/kb/1236/kubernetes-operator#helm.

This does not include more advanced proxy configuration options- we are working on that. It will have to be a mechanism that works for both helm and static manifests users, so will likely not be very helm specific (also folks might want to be able to specifiy different configuration options for different proxies).

@jakedgy thank you for starting to work on this and raising the proxy configuration issue.

Any feedback on the Helm chart is very welcome.

**Comment by irbekrm** [comment]
I have created a separate issue for proxy configuration mechanism https://github.com/tailscale/tailscale/issues/10709, feedback is very welcome.

I am going to close this issue as we do now have a Helm chart.
