### ISSUE TITLE
Connecting Tailscale via Shortcut on macOS will fail

### ISSUE THREAD

**Issue by le0-VV** [tailscale/tailscale#9223]
### What is the issue?

When using a shortcut command on macOS to connect Tailscale, Tailscale won't connect (sometimes Tailscale will logout the account altogether) and the Shortcut will stall.

### Steps to reproduce

1. Create a shortcut that includes a step to connect Tailscale
2. Run the shortcut
3. Observe tail scale's behaviour (tailscale does not connect OR tailscale will logout)
4. The shortcut will stuck on "connect Tailscale" and doesn't progress, manually connect Tailscale doesn't fix the shortcut

### Are there any recent changes that introduced the issue?

No recent changes that may have affected this to my knowledg

### OS

macOS

### OS version

macOS Ventura 13.5.1

### Tailscale version

1.48.1 (App Store)

### Other software

Shortcut on macOS

### Bug report

BUG-3136ac3edb5b9c76508174723d254f2336e5b4326bf91cb05ebca9e2600e634d-20230904044238Z-66ff391e4944e09b

**Comment by agottardo** [comment]
We have a fix for this landing in 1.50. (Unstable builds should already include it.)
