### ISSUE TITLE
SSO error Microsoft 

### ISSUE THREAD

**Issue by privacyguy123** [tailscale/tailscale#9225]
### What is the issue?

Failed to login
Authentication failed while retrieving details from your SSO provider

Some CSRF token missing error - is this known? Tried multiple browsers and connections.

### Steps to reproduce

Try to sign up/log in with Microsoft SSO

### OS

Android

### OS version

13

### Tailscale version

1.48.1

**Comment by DentonGentry** [comment]
There is not really anything we can go on here. Microsoft login is not globally broken for everyone, there is something about your specific login or tailnet. Please submit a support ticket https://tailscale.com/contact/support/ instead, which lets us know who you are and look up information about the tailnet.

**Comment by mycanaletto** [comment]
Hello,

I can no longer access my account.

When I log in with my Microsoft 365 account, it asks me to log in again with my Microsoft 365 account and it goes round and round.
![image](https://github.com/tailscale/tailscale/assets/45459269/cdea141e-f3d0-464c-9e4b-1e1d7d75c7e0)

I made a support request but I haven't heard anything, so I can't use this account anymore.

lionel
