### ISSUE TITLE
Name resolution broken in 1.0.5 when upgrading to Big Sur

### ISSUE THREAD

**Issue by davidpoblador** [tailscale/tailscale#923]
**Describe the bug**
After upgrading my Mac to Big Sur, DNS resolution is broken when the option "Use corporate DNS" is enabled in the Tailscale menu (version 1.0.5)

**To Reproduce**
1. Upgrade to Big Sur
2. Make sure the "Use corporate DNS" option is enabled
3. Go to your terminal and try to resolve any hostname.
4. DNS resolution does not work (does not seem to timeout).
(Disabling the "Use corporate DNS" option fixes the problem immediately)

**Expected behavior**
I would expect DNS names to resolve.

**Version information:**
 - Device: Macbook Pro 13
 - OS: MacOS
 - OS version: Big Sur
 - Tailscale version: 1.0.5

**Additional context**
Disabling the "Use corporate DNS" option fixes the problem immediately. I've tried to investigate if this is connected with the OCSP problems Apple has suffered after the Big Sur release, but it seems unrelated (blackholing the OCSP host, didn't make this problem go away).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2jw9d)

**Comment by bradfitz** [comment]
@rosszurowski, you also upgraded to Big Sur yesterday. Do you also see this?

**Comment by bradfitz** [comment]
@davidpoblador, are you using Magic DNS? (That is, is the top checkbox at https://login.tailscale.com/admin/dns checked ans also accompanied by at least one DNS server on that page)

**Comment by davidpoblador** [comment]
> @davidpoblador, are you using Magic DNS? (That is, is the top checkbox at https://login.tailscale.com/admin/dns checked ans also accompanied by at least one DNS server on that page)

Yes! With 1.1.1.1 as upstream

**Comment by rosszurowski** [comment]
I was able to reproduce. Tried our tailscale.com network on my device and having "Use Corporate DNS" enabled made me unable to reach internal hostnames and public internet domains like github.com. Disabling "Use Corporate DNS" fixed it immediately.

**Comment by crawshaw** [comment]
The problem appears to be that macOS 10.16 (Big Sur) has changed the binding semantics for DNS. Now the name server provided by Tailscale is scoped to the Tailscale network interface. That means if you type in `8.8.8.8`, your mac will try to route traffic to 8.8.8.8 out the Tailscale interface. But we don't have a default route, so the traffic is lost.

Fortunately there is an immediate workaround: enable magic dns. This sets the nameserver to 100.100.100.100 and does the routing inside our NetworkExtension. As that is an IP you can reach on the Tailscale interface, it works.

**Comment by crawshaw** [comment]
@davidpoblador the reason setting magicdns didn't fix your problem earlier is we had magicdns disabled on our server for an unrelated reason. Could you please try setting it on and setting a DNS server again and see if it works?

**Comment by crawshaw** [comment]
Assuming this work, it raises the question: should we instruct big sur clients to turn on magicdns by default, even if it isn't enabled in the admin panel?

**Comment by davidpoblador** [comment]
> @davidpoblador the reason setting magicdns didn't fix your problem earlier is we had magicdns disabled on our server for an unrelated reason. Could you please try setting it on and setting a DNS server again and see if it works?

Still having the same issue as soon as I enable "Use corporate DNS". If I disable that, it works perfectly fine with Magic DNS.

Here is the config that does not work:

<img width="820" alt="Screenshot 2020-11-13 at 22 28 13" src="https://user-images.githubusercontent.com/128501/99123012-ab8d8980-25ff-11eb-9711-7325a6823e53.png">
<img width="324" alt="Screenshot 2020-11-13 at 22 28 07" src="https://user-images.githubusercontent.com/128501/99123032-b516f180-25ff-11eb-9803-8d0b29178c2e.png">

**Comment by davidpoblador** [comment]
(BTW, thanks for the responsiveness! You are great!)

**Comment by crawshaw** [comment]
Oh right, the problem is we don't have MagicDNS rolled out in 1.0. I'm using the beta.

I guess we should get that rolled out sometime soon. :)

**Comment by crawshaw** [comment]
We just released 1.2.4 to macOS. It will probably take a few hours to propagate.

**Comment by veyalla** [comment]
1.2.4 broke this even more :( 

With the old version, I could get it work on Big Sur by turning off Corporate DNS, with the new version that option is gone and enabling Magic DNS (with 1.1.1.1 or 100.100.100.100) doesn't help. Any ideas?

**Comment by bradfitz** [comment]
@veyalla, option click the Tailscale menu bar icon to see that and other lesser-used options.

**Comment by veyalla** [comment]
Thanks for the tip! 

I had to uncheck "Corporate DNS", "Route subnets" and "Magic DNS" (from Admin console) for it to work with Big Sur on my setup.

**Comment by davidpoblador** [comment]
I can confirm after updating to 1.2.4 and option-clicking the menu and reenabling "Use Corporate DNS" does not break name resolution. So from my perspective this is solved! Thank you very much for your work.

**Comment by rosszurowski** [comment]
We've had a few reports that upgrading to the latest macOS Big Sur release, 11.0.1, also helps resolves things without requiring "Use Corporate DNS" to be disabled or Magic DNS to be turned on. If you run into this issue, please try upgrading.

**Comment by creachadair** [comment]
I found this issue because I just upgraded to Big Sur 11.1, and found that name resolution failed with Tailscale enabled. Re-enabling it with "Use Corporate DNS" turned off _does_ work for me. I don't really know what that setting does, but I don't have a corp DNS so I think this is fine.

FWIW: macOS 11.1 (20C69) on MacBook Pro (15-inch, 2018), Tailscale 1.2.4. I'm happy to provide additional diagnostics if you think it would help.

**Comment by rosszurowski** [comment]
Checking in a month later, I don't seem to be able to reproduce this any more. We also haven't received any new reports of this in a while. It's possible a patch update to Big Sur fixed this behavior for us.

I'm running Big Sur 11.1 and no matter my network settings (Magic DNS on or off, with or without custom DNS servers) I can't break my name resolution any more. Is someone else able to confirm whether they still have this issue or not?

**Comment by davidpoblador** [comment]
The issue is gone for me, I can confirm. Should I close the bug myself or will you do it?

**Comment by rosszurowski** [comment]
Thanks for confirming @davidpoblador. We'll consider this fixed then.
