### ISSUE TITLE
FR: debian package: move iptables from Depends to Recommends

### ISSUE THREAD

**Issue by oliverpool** [tailscale/tailscale#9236]
### What are you trying to do?

I have debian with nftables configured.
Currently, when I install tailscale following the [official guide](https://tailscale.com/kb/1174/install-debian-bookworm/) `iptables` gets installed as well.

I would like to install tailscale without having to install `iptables` (I adjusted the `TS_DEBUG_FIREWALL_MODE` in `/etc/default/tailscaled`, according to https://tailscale.com/kb/1294/firewall-mode/#how-to-set-the-firewall-mode).

### How should we solve this?

Adjust https://github.com/tailscale/tailscale/blob/3280c81c959e59052e0639d4de97128748a03827/release/dist/unixpkgs/pkgs.go#L253-L254

```go
 Depends:    []string{"iproute2"}, 
 Recommends: []string{"iptables", "tailscale-archive-keyring (>= 1.35.181)"}, 
```

### What is the impact of not solving this?

iptables gets uselessly installed.

**Comment by oliverpool** [comment]
Related to https://github.com/tailscale/tailscale/issues/391

**Comment by bradfitz** [comment]
Realistically we won't be able to do this for a long time as many people use iptables and will continue to do so even after our nftables support is complete.

Is your main concern disk space? Is it causing any other problems?

**Comment by bradfitz** [comment]
Actually, nevermind. Recommends are still installed by default, huh? You need --no-install-recommends to skip them? So this is probably fine. Technically we run fine already in userspace mode without iptables so it's not strictly a dependency.

Cc @danderson

**Comment by rodrigc** [comment]
@KevinLiang10 @raggi  Is the iptables CLI still used inside tailscale, or has it all been replaced by direct netlink socket via https://github.com/tailscale/tailscale/issues/391 ?

**Comment by MichaIng** [comment]
What do you think about defining the dependency as `iptables | nftables` instead, to assure that any of both is installed?

**Comment by knyar** [comment]
> What do you think about defining the dependency as iptables | nftables (OR) instead, to assure that any of both is installed?

That's certainly something we'd want to do, but only when automatic selection of `iptables` vs `nftables` [firewall mode](https://tailscale.com/kb/1294/firewall-mode/) in the Tailscale client becomes the default. At the moment the client expects to be able to use `iptables`, and automatic selection is an experimental feature that needs to be explicitly enabled (`TS_DEBUG_FIREWALL_MODE=auto`).

**Comment by oliverpool** [comment]
According to https://docs.software-univention.de/developer-reference/5.0/en/appendix/debian-packaging.html#debian-control

> In addition to specifying a single package as a dependency, multiple packages can be separated by using the pipe symbol (|). At least one of those packages must be installed to satisfy the dependency. If none of them is installed, the first package is chosen as the default.

So specifying `Depends: iptables | nftables` would be better aligned with @knyar's comment.

I would recommend the following change:
```go
			Depends: []string{
				// Install iptables by default, except if nftables is installed.
				// Using nftables requires manual configuration for now
				//  (tailscaled will not start otherwise).
				// See https://github.com/tailscale/tailscale/issues/9236.
				"iptables | nftables",
			},
			Recommends: []string{
				"tailscale-archive-keyring (>= 1.35.181)",
```

**Comment by DentonGentry** [comment]
As things are right now, a system with only nftables installed would pass that dependency check but tailscaled would not work. Right now one has to manually tell tailscaled to use nftables, the auto-detection doesn't fully work. We need tailscaled to use auto-detection by default before we relax the dependency on iptables.

**Comment by oliverpool** [comment]
> before we relax the dependency on iptables.

The dependency has already been relaxed (too much - by my fault, because of this issue) in #9287. This is causing problems, as documented in https://github.com/MichaIng/DietPi/issues/6649 and https://github.com/tailscale/tailscale/issues/9630

Making `Depends: iptables | nftables` would make the dependency stronger (it is currently under `Recommends`) and resolve all issues (the two previously linked one and my initial post).
