### ISSUE TITLE
Disco logging still more verbose than desired

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#924]
Version: approximately 1.2.5

Steps:
- Start a node on macOS, [EnFA2], several days ago. Eventually this node was shut down.
- Start a node on Linux on the same domain, around the same time. This node is still running.
- Leave a ping running in a background window, pinging 100.93.115.123 ([EnFA2]) repeatedly.

As of today, 2020-11-13, 15:00 ET, my Linux node 100.122.98.51 is printing endless messages (about one event per second or two, producing 5+ lines each) trying to connect to [EnFA2] even though that node has been missing for a long time.

It might make some sense to continue trying to disco ping a node we're actively trying to connect to, just so we can reconnect the moment it comes back. But the ~one packet we need to send through DERP is dwarfed by the numerous messages we send to the logs.

**Comment by apenwarr** [comment]
Relatedly: is there any point sending the call-me-maybe request more than one time through DERP, for any given outgoing packet? Even after killing the ping request, we continue sending call-me-maybe requests for several seconds.

**Comment by bradfitz** [comment]
>  though that node has been missing for a long time.
 
The node [EnFA2] still exists as of now.

By "missing" do you mean its last seen time should influence whether we attempt a connection?

Or do you just want to see less log output?

**Comment by bradfitz** [comment]
> Relatedly: is there any point sending the call-me-maybe request more than one time through DERP, for any given outgoing packet?

The NAT mapping expires after an unknown number of seconds. 30 seconds is common, but for new UDP traffic that has never seen a reply it can be much less.

**Comment by apenwarr** [comment]
> > though that node has been missing for a long time.
> 
> The node [EnFA2] still exists as of now.
> 
> By "missing" do you mean its last seen time should influence whether we attempt a connection?

The node itself has been offline for a long time (> 1 day). But this was mostly a note about why the logs are happening in the first place (if the node were online, we wouldn't see the ongoing logs).



> > Relatedly: is there any point sending the call-me-maybe request more than one time through DERP, for any given outgoing packet?
> 
> The NAT mapping expires after an unknown number of seconds. 30 seconds is common, but for new UDP traffic that has never seen a reply it can be much less.

What I mean by this is, call-me-maybe is carried over a supposedly reliable channel. If it doesn't make it through the first time, it means the node isn't there at all to receive it. I think the packet inside the tunnel should receive the same experience (no node exists right now, follow your usual retry cycle). We don't need to hide it.

This seems different from the actual wireguard negotiation once a DERP link is certain; we don't want to drop packets just because we're still negotiating a link, so negotiation retries can be appropriate.

**Comment by bradfitz** [comment]
The DERP link hasn't always been necessarily certain; seeing the call-me-maybe on one side but not the other has helped me debug issues were one side had flapped to a different DERP server and the other side was sending to the wrong place. (good ol' 1f7a7a4ffe7c0b4540413874fd8dac2c782c91ee)

I'm not particularly concerned about this bug. I already did one pass de-spamming the disco logging after previous complaints and I think what we're left with still pays for itself in debugging utility. I'd worry that removing more would just hurt debugging. Since I'm not the one that does most this debugging, I think we should leave it. There are much bigger problems at the moment.
