### ISSUE TITLE
Tailscale doesn't work with other VPNs (on macOS)

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#925]
**Describe the bug**
Users of [Mullvad VPN](https://mullvad.net/) have reported that their Tailscale connections don't work while running Mullvad. They need to disable the Mullvad tunnel before they're able to even log in to Tailscale.

**To Reproduce**
1. Install Mullvad VPN
2. Log in with your account number
3. Turn on VPN
4. Unable to reach any devices over Tailscale. If I quit and re-open Tailscale, I can't even log in. The macOS menu bar item stays grayed out.

**Expected behavior**
Tailscale should be able to connect. Or, if it's not able to connect, it should be able to tell me why and what to do about it.

**Screenshots**
<img width="335" alt="image" src="https://user-images.githubusercontent.com/303731/99124771-c7c60200-25d0-11eb-8721-03a1348b96d7.png">

**Version information:**
Tested with:
 - OS: macOS
 - OS version: Big Sur
 - Tailscale version: 1.0.5

**Comment by danderson** [comment]
macOS only lets you have one VPN extension at a time, I believe. So, these are the symptoms of "we can't start IPNExtension because another one is already running".

Unless apple provides better APIs, afaik all we can do is have friendlier errors.

**Comment by rosszurowski** [comment]
Hmm. A separate test with ExpressVPN shows that you seem to be right. I see all the same symptoms: loss of connectivity to devices and failure to log in on restart. I'll change the title — even just friendlier error messages would help here.

**Comment by rosszurowski** [comment]
@danderson I believe we've gotten reports of the same behavior with Mullvad on other platforms. Is there anything about Mullvad being a WireGuard-based VPN that might be causing this on other platforms?

**Comment by narensankar0529** [comment]
I have tailscale working with PIA. My PIA setup is based on Wireguard. The first requirement is that PIA needs to enable split-tunnel and the IP addresses of the Tailscale network bypassed. And the second requirement is that Tailscale tunnel be connected after the PIA tunnel is connected and similarly disconnected before the PIA tunnel is disconnected.

**Comment by pendulm** [comment]
zero-tier and tailscale works with each other In my MacOS

**Comment by danieljin** [comment]
> I have tailscale working with PIA. My PIA setup is based on Wireguard. The first requirement is that PIA needs to enable split-tunnel and the IP addresses of the Tailscale network bypassed. And the second requirement is that Tailscale tunnel be connected after the PIA tunnel is connected and similarly disconnected before the PIA tunnel is disconnected.

When you say the IP address of the tailscale network, are you talking about the 100.x.y.z IP address that is assigned automatically?

**Comment by narensankar0529** [comment]
Yes. That is correct.

**Comment by danieljin** [comment]
> Yes. That is correct.

Turns out all I was missing was restarting the Tailscale IPN service.

**Comment by juddus** [comment]
For linux, using nftables, running these commands makes mullvad and tailscale work for me:
```
nft insert rule inet mullvad output oifname "tailscale*" accept
nft insert rule inet mullvad input iifname "tailscale*" accept
```

**Comment by nordicdyno** [comment]
the same issue on Catalina, I click «Log in…» and nothing happens

**Comment by floft** [comment]
In case someone finds this useful, I had to do one additional thing on Linux to get PIA and Tailscale to work together (both with Wireguard, have not tried PIA with OpenVPN and Tailscale). Using their split tunnel setting I set 100.64.0.0/10 to bypass the VPN. Then, I also had to adjust the route table preferences. Otherwise, the packets would "bypass" the VPN and get sent on my ethernet interface rather than the tailscale0 interface, though I could receive packets from other tailscale devices just not respond to them.

sudo systemctl edit tailscaled.service

    [Service]
    ExecStartPost=/usr/bin/ip rule add pref 65 table 52
    ExecStopPost=/usr/bin/ip rule del pref 65 table 52

Then ``systemctl daemon-reload`` and ``systemctl restart tailscaled``. Below is what ``ip rule list`` looked like without this, so I just picked a preference of 65 since it's less than the lowest preference of the "piavpn" rules. Note table 52 is tailscale's.

    0:      from all lookup local
    50:     from all lookup main suppress_prefixlength 1
    70:     from all fwmark 0x3214 lookup piavpnFwdrt
    100:    from all fwmark 0x3212 lookup piavpnOnlyrt
    101:    from all fwmark 0x3211 lookup piavpnrt
    102:    from 10.218.64.160 lookup piavpnrt
    102:    not from all fwmark 0x3213 lookup piavpnWgrt
    102:    from 10.1.137.116 lookup piavpnOnlyrt
    5210:   from all fwmark 0x80000 lookup main
    5230:   from all fwmark 0x80000 lookup default
    5250:   from all fwmark 0x80000 unreachable
    5270:   from all lookup 52
    32766:  from all lookup main
    32767:  from all lookup default

Not really sure if this is the right way to do this -- I stared at the iptables rules and routing tables for a while but didn't fully follow what they were doing. Then searched this repo for 5270 and found the following line (and changed the pref and apparently my version of iproute2 doesn't like "-4" or "-6"): https://github.com/tailscale/tailscale/blob/2d96215d977e9dd823034ff000adbfd1268a4c2b/wgengine/router/router_linux_test.go#L44

**Comment by kotx** [comment]
I also encounter this issue on Windows.

**Comment by kotx** [comment]
Possibly related: #2231

**Comment by apfsx** [comment]
> 
> 
> I also encounter this issue on Windows.

Did you ever find a way to use these 2 on Windows?

**Comment by Auros** [comment]
For people using Private Internet Access, the **VPN Kill Switch** needs to be turned off. It overrides split tunnels and will not let any data pass through.

**Comment by apfsx** [comment]
> 
> 
> I also encounter this issue on Windows.

Were you able to find a solution to this on Windows (mullvad + tailscale)? @kotx

**Comment by taibhse-designs** [comment]
Encountering this issue on windows also with no resolution, cant get tailscale and mullvad vpn to work nicely, even with all tailscale exe files added to mullvads split tunneling

**Comment by aeonlei** [comment]
Same issue on windows

**Comment by schickling** [comment]
Is there any progress on this issue? It's very unfortunate that I can't use Mullvad and Tailscale at the same time on macOS.

**Comment by DentonGentry** [comment]
Having multiple VPN products simultaneously active rarely works at all. They fight over every resource: routing table, firewall rules, etc. I promise that if there are developments there will be comments here, but to set expectations I do not expect to resolve this issue.

For Mullvad specifically, where we think we understand the potential interactions well enough to be able to accommodate them, there is a separate issue in https://github.com/tailscale/tailscale/issues/2880 which is more tractable.

**Comment by adworacz** [comment]
After much trial and error, I got everything working with Mullvad + Tailscale + docker containers hosting services on my NAS.

I had to use a combination of the above commands posted @floft  and @juddus but it all seems to work using `mullvad-exclude` and nftables on Debian 11 Bullseye.

Using `systemctl edit tailscaled`, the following seems to work great:

```
[Unit]
Requisite=mullvad-daemon.service
After=mullvad-daemon.service

[Service]
ExecStart=
ExecStart=/usr/bin/mullvad-exclude /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port $PORT $FLAGS
ExecStartPost=ip rule add pref 65 table 52
ExecStartPost=nft insert rule inet mullvad output oifname "tailscale*" accept
ExecStartPost=nft insert rule inet mullvad input iifname "tailscale*" accept
ExecStartPost=nft insert rule inet mullvad forward oifname "tailscale*" accept
ExecStopPost=ip rule del pref 65 table 52
```

Note the use of the `mullvad-exclude` command to enable the `tailscaled` to split out of the normal Mullvad tunnel. Also note the `forward` `nft` command, which was required for me to access services hosted using podman (via docker compose) properly.

**Comment by adworacz** [comment]
It should be noted that mullvad supports split-tunneling using traffic marks - https://mullvad.net/fr/help/split-tunneling-with-linux-advanced/#allow-ip

This might be a way to automatically enable tailscale traffic to bypass Mullvad, and should work across Mullvad's reconnections.

Granted, I haven't tested this behavior just yet

**Comment by 1player** [comment]
I've made a script to set up a Mullvad VPN from Wireguard config files, with support for Tailscale (by updating the routing table after the tunnel goes up): https://gist.github.com/1player/e9cadfef833d5eb5a23c30223f560147

**Comment by xrishox** [comment]
> I've made a script to set up a Mullvad VPN from Wireguard config files, with support for Tailscale (by updating the routing table after the tunnel goes up): https://gist.github.com/1player/e9cadfef833d5eb5a23c30223f560147

i tried running that script on an ubuntu 22.04 box. i installed resolveconf and the wiregaurd-tools stuff. it appears to modify all of the rules correctly, but once i activate it my network stops functioning. i can't ping 8.8.8.8 and i can't ping my tailscale via magic dns. when i run the down command everything appears to fix itself. i'm wondering if i'm doing something wrong or maybe your script doesn't work with ubuntu's latest lts. it's also possible that mullvad produces new wireguard config files that are no longer compatible or something.

**Comment by ajgrf** [comment]
I wasn't able to get the routing table approach to work, but I did manage to get Mullvad and Tailscale to play nice by using the following nftables rules:

    table inet mullvad-ts {
      chain exclude-outgoing {
        type route hook output priority 0; policy accept;
        ip daddr 100.64.0.0/10 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
        ip6 daddr fd7a:115c:a1e0::/48 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
      }

      chain allow-incoming {
        type filter hook input priority -100; policy accept;
        iifname "tailscale0" ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
      }
    }

By marking the incoming and outgoing Tailscale traffic like this, Mullvad lets it through the rest of the routing table without blocking it or directing it to their servers (see [Mullvad's split tunneling docs](https://mullvad.net/en/help/split-tunneling-with-linux-advanced/)).

**Comment by r3nor** [comment]
Are there any plans on solving this? Trying to use Mullvad along with Tailscale but it is a nightmare. Tried almost everything but nothing works.

**Comment by npajkovsky** [comment]
@r3nor This is probably Mullvad issue because I have tried ProtonVPN with Tailscale and it works like charm.

**Comment by r3nor** [comment]
I created this repo with a solution that is perfectly working for me right now:
https://github.com/r3nor/mullvad-tailscale

**Comment by r3nor** [comment]
@npajkovsky Yes, mullvad sets very restrictive rules so no connections can scape the VPN if I'm not wrong. As I have seen, ProtonVPN is less restrictive with the rules and Tailscale does not go through such rules.

**Comment by solzard** [comment]
Would you please open a new issue to discuss workarounds for Linux? Although the title and issue label are `on macOS` / `OS-macos`, recent replies are not for macOS as I far as understand.

**Comment by BassemKaroui** [comment]
I have multiple machines using Mullvad and when using tailscale it simply doesn't work. The only way I found to SSH to another machine, say machine 2, from machine 1 is to disconnect from Mullvad on machine 2 and add split-tunneling rules on machine 1 without the need to disconnect from Mullvad on that machine. But if all the machines are connected to Mullvad I didn't find any way to make this work even if I add split-tunneling rules on all of them.
I tried **ZeroTier** and it worked out of the box for me. I like Tailscale's features more but for now I'll be just using ZeroTier until this issue is resolved I guess.

**Comment by azuline** [comment]
> @ajgrf I wasn't able to get the routing table approach to work, but I did manage to get Mullvad and Tailscale to play nice by using the following nftables rules:

Thanks a ton: this helped me get mullvad and tailscale to play nicely together, however Magic DNS is finicky. Sometimes it works, sometimes it doesn't 🤔. Usually after a computer reboot, Magic DNS works. After cycling my internet connection, it stops working.

**Comment by DentonGentry** [comment]
> After cycling my internet connection, it stops working.

That could mean that dhcpclient is overwriting /etc/resolv.conf.

**Comment by azuline** [comment]
I'm using systemd-resolved and `/etc/resolv.conf` continues to point to the systemd-resolved daemon. systemd-resolved continues to route the appropriate DNS requests to `100.100.100.100`, but:

```bash
$ nslookup zen 100.100.100.100
;; communications error to 100.100.100.100#53: connection refused
;; communications error to 100.100.100.100#53: connection refused
;; communications error to 100.100.100.100#53: connection refused
;; no servers could be reached
```

**Comment by iGerman00** [comment]
Not sure how helpful this is, but I was able to set it up and it seems to work fine. Your VPN service has to support downloading WireGuard configs. In my case it's IVPN. 
1. Obtain the config file
2. Import it to the WireGuard app. Me running macOS I used the one available on the Mac App Store
3. Edit the config file (optional?)
I ticked the "exclude private IPs" checkbox in the WireGuard config edit dialog. I also had to remove one IP range as it conflicted with IVPN's internal DNS servers.

Before:
```
AllowedIPs = ::/0, 0.0.0.0/0
```

After:
```
AllowedIPs = ::/0, 1.0.0.0/8, 2.0.0.0/8, 3.0.0.0/8, 4.0.0.0/6, 8.0.0.0/7, 11.0.0.0/8, 12.0.0.0/6, 16.0.0.0/4, 32.0.0.0/3, 64.0.0.0/2, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4
```

I found during writing this that `0.0.0.0/0, ::/0` also allows tailscale to work, weirdly. My guess is that the WG app respects the routing table better? Regardless, I don't exactly know how good of a solution this is, but it worked.

**Comment by UnsterblichMedic** [comment]
Disabling the VPN kill switch solved this issue for me.  I also have the IP addresses for Tailscale on the split tunnel bypassing the VPN.

**Comment by DentonGentry** [comment]
Having multiple VPN products simultaneously active rarely works at all. They fight over every resource: routing table, firewall rules, etc.

If progress is made on this we'll post updates here, but I suspect https://github.com/tailscale/tailscale/issues/2880 is more likely to make progress than directly working out conflicts on a device.

**Comment by sdht0** [comment]
Here's how I got it working on linux, taking ideas from the other comments here.

Verify that the routing rules have the tailscale (`52*`) before mullvad (`32*`). This happens automatically for me just by starting tailscale after mullvad, and I did not have to add any extra rule manually.
```
$ ip rule
0:      from all lookup local
5210:   from all fwmark 0x80000/0xff0000 lookup main
5230:   from all fwmark 0x80000/0xff0000 lookup default
5250:   from all fwmark 0x80000/0xff0000 unreachable
5270:   from all lookup 52
32764:  from all lookup main suppress_prefixlength 0
32765:  not from all fwmark 0x6d6f6c65 lookup 1836018789
32766:  from all lookup main
32767:  from all lookup default
```

Then punch holes for tailscale in the mullvad firewall. `/opt/mullvad.rules`:
```
flush table inet mullvad-ts;

table inet mullvad-ts {                                                                                                                                                                                                                       
  chain exclude-outgoing {
    type route hook output priority -100; policy accept;
    meta mark 0x80000 ct mark set 0x00000f41 meta mark set 0x6d6f6c65; #new
    oif "tailscale0" ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }

  chain allow-incoming {
    type filter hook input priority -100; policy accept;
    iif "tailscale0" ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }
}
```

Most of the tailscale connections now work. I did need an additional rule to connect to the exposed ports from docker: `nft insert rule inet mullvad forward oifname "tailscale0" accept`. Unfortunately I can't see a way to do this without directly editing the mullvad firewall table (unlike the rules above), and might be removed by mullvad anytime. Hasn't happened to me yet though.

Consolidating into the systemd service:

```
$ sudo systemctl edit tailscaled
[Unit]
Requisite=mullvad-daemon.service
After=mullvad-daemon.service

[Service]
ExecStartPre=nft -f '/opt/mullvad.rules'
ExecStartPre=nft insert rule inet mullvad forward oifname "tailscale0" accept

ExecStopPost=nft delete table inet mullvad-ts
```

Remote tailscale connections have been working okay for me with these changes. The only thing that does not work is `tailscale netcheck` and needs `mullvad-exclude tailscale netcheck`.

**Comment by Jonher937** [comment]
The comment above from @sdht0 was very helpful.

If the company is using Tailscale to tunnel Public IP's as well, those showed up in `ip route show table 52 | awk '{print $1}'` for me.

I added `/32` to the IP's that didn't already have a CIDR and then comma separated them.
nft allows multiple CIDR's to be specified if wrapped in `{}` like so:
```
ip saddr { 100.64.0.0/10, 1.1.1.1/32, 8.8.8.8/32 } ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
```
Repeat for the `daddr` in the outgoing chain.

Since this is my first two hours of using Tailscale I'm not 100% all of the IP's from the `ip route show table 52` should be added to the nftables exclude, but so far it enabled me to reach services I couldn't before I added them.

**Comment by ford-prefect** [comment]
Just chiming in here based on what people seem to be hitting, and what I found on my setup: I've got tailscale setup + wg-quick for another VPN, and am trying to set up a split tunnel with this. This seems to be a common enough setup (tailscale for the "internal" VPN, and something else WireGuard-based for the "external" VPN).

In my case the main problem was that tailscale routing rules always turned up after the wg-quick rules, which meant all the unmarked packets that should have hit the tailscale table went to the wg table and were misdirected/lost thereafter. I'm not sure how these priorities get picked, but moving the rule at `5209` to after `5270` made things correct for my setup (where the other VPN is the default route). It's a bit janky because there is no "move", of course, just an `ip rule del` followed by an `ip rule add`.

```
$ ip rule
        5208:	from all lookup main suppress_prefixlength 0
--wg->  5209:	not from all fwmark 0xca6c lookup 51820
--ts->  5210:	from all fwmark 0x80000/0xff0000 lookup main
--ts->  5230:	from all fwmark 0x80000/0xff0000 lookup default
--ts->  5250:	from all fwmark 0x80000/0xff0000 unreachable
--ts->  5270:	from all lookup 52
```

What I'm asking for is likely too in-the-weeds, but having a way to customise the base priority on these rules might making tuning interop with other VPNs a lot easier (arguably this configuration could also belong in wg-quick or other tools -- something needs to provide a knob to specify the desired priority order).

**Comment by sdht0** [comment]
@ford-prefect if you use mark based exceptions like in my [earlier comment](https://github.com/tailscale/tailscale/issues/925#issuecomment-1616354736), the order of the routing tables shouldn't matter anymore. The wg-quick packets need to have a mark of course.

Note that forwarded packets, such as docker traffic, still needs a hacky change (2nd ExecStartPre) of the mullvad rules, that can be removed after a new mullvad release with https://github.com/mullvad/mullvadvpn-app/pull/5011 included.

**Comment by ford-prefect** [comment]
@sdht0 ah, interesting. I'm not using Mullvad (or nftables), but I'll take a look to see if I can adapt this.

**Comment by shervinsahba** [comment]
@sdht0 Thanks. This seems to work well for me to ssh into remote devices while having mullvad up. Question about the systemd service write up:

What is `ExecStartPre=nft insert rule inet mullvad forward ip daddr 100.64.0.0/10 accept` doing here that isn't being done in either nft file? Did you mean to put `nft insert rule inet mullvad forward oifname "tailscale0" accept`?

**Comment by sdht0** [comment]
@shervinsahba It was inserting a rule into a mullvad nft table to let through docker <-> tailscale packets. With the latest version of Mullvad containing https://github.com/mullvad/mullvadvpn-app/pull/5011, this is not needed anymore. I've edited the above post.

**Comment by likeshumidity** [comment]
FYI, BitDefender VPN allows split tunneling on macOS... but not sure how secure it is compared to others... in general most of these companies are trying to do too much and engage in what I consider crappy marketing practices and make it hard to cancel auto-renewal, etc.

**Comment by agottardo** [comment]
Closing this issue as it is not actionable. We published information about VPN interoperability at https://tailscale.com/kb/1105/other-vpns.
