### ISSUE TITLE
Limited Access in Certain Countries

### ISSUE THREAD

**Issue by FarzanT** [tailscale/tailscale#9263]
### What is the issue?

Within the past 2 weeks, Tailscale suddenly has decided to comply with unspecified (perhaps non-existent) legal requirements to block usage in certain countries (see #9158). This is rather confusing, because it goes against Tailscale's primary use cases.
For example, as a Canadian citizen, I will travel in other countries, including Iran, and will need to have a secure access to my personal devices in Toronto, Canada. This does not count as "providing services to Iran without a license" as specified in USA and Canada's sanctions, but rather provides a means for individuals to securely connect to their personal devices without exposing their internet traffic while travelling.
It's still possible to setup a private wireguard-based tunnel, so I can simply stop using Tailscale. I don't understand why Tailscale would choose to limit their own users. Perhaps your legal team should reconsider whether allowing private connections will have legal repercussions for your company, because it doesn't seem like that it will, e.g. the same as many VPN providers based in the USA that are functional in sanctioned countries.

### Are there any recent changes that introduced the issue?

Sudden decisions by Tailscale's legal team.

### OS

macOS

**Comment by DentonGentry** [comment]
We are legally required to deny service to clients in certain countries and regions.
