### ISSUE TITLE
Build: Web client 

### ISSUE THREAD

**Issue by dkaser** [tailscale/tailscale#9269]
### What is the issue?

After following the instructions in README to build Tailscale with the web client, the web client reports:

> Tailscale was built without the web client. See [Building the web client](https://github.com/tailscale/tailscale#building-the-web-client) for more information.

I am currently testing the updated web client as part of dkaser/unraid-tailscale#86.

### Steps to reproduce

1. Clone repository
2. Install the web client build environment (note: this step isn't in README, but needed for next step to succeed): `./tool/yarn --cwd client/web`
3. Build web client: `./tool/yarn --cwd client/web build`
4. Build tailscale: `go install tailscale.com/cmd/tailscale{,d}`

### OS

Linux

### OS version

Ubuntu 

### Tailscale version

1.49.0-dev20230906

**Comment by DentonGentry** [comment]
Does that mean it builds now?

**Comment by dkaser** [comment]
It builds correctly, this was actually a web server problem (the error is confusing though, since it says that the build doesn't have the web client, even though it actually does).
