### ISSUE TITLE
Access Controls file  bug

### ISSUE THREAD

**Issue by dg9999cn** [tailscale/tailscale#927]
**Describe the bug**
I can visit my server at http://100.80.188.38 . It works. But when I try to visiti my server at http://k8sm, it doesn't work. Why?
I have change the Access Controls file as follow: 
// Declare convenient hostname aliases to use in place of IP addresses.
  "Hosts": {
    "k8sm": "100.80.188.38",
  },

**Comment by danderson** [comment]
The aliases don't define DNS names, they're just aliases you can reference in the ACL file. Have you enabled magic DNS at https://login.tailscale.com/admin/dns ? That's the feature to handle DNS resolution.

**Comment by DentonGentry** [comment]
We'll plan to close this the next time bugs are scrubbed, barring further comments.

**Comment by DentonGentry** [comment]
No further comments, closing.
