### ISSUE TITLE
E: Failed to fetch https://pkgs.tailscale.com

### ISSUE THREAD

**Issue by rsockanc** [tailscale/tailscale#9270]
### What is the issue?

Several globally deployed tailscale clients are connected to tailscale and working correctly however we are no longer able to update certain clients in certain countries as of the past week.  Access to the tailscale website admin page functions fine on the same clients.

E: Failed to fetch https://pkgs.tailscale.com/stable/raspbian/dists/bullseye/InRelease  451  Unavailable For Legal Reasons [IP: 199.38.181.239 443]

I have seen many other posts over the past 6 days from other users with the same issue in different countries.  Is there a published list of countries that Tailscale has now blocked from a specific function like updated and new installs?  

### Steps to reproduce

apt-get update

### OS

Linux

### OS version

Raspberry Pi OS

### Tailscale version

1.48.1

**Comment by DentonGentry** [comment]
We are legally required to restrict software distribution in certain countries and regions. Unfortunately this means you will not be able to download Tailscale packages from your current location.
