### ISSUE TITLE
localapi: add support for conditional writes on SetServeConfig, with "etag" from GetServeConfig

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#9273]
It should be possible to do a read-modify-write on ServeConfig safely.

We could add a new `ServeConfig` etag response on Get (e.g. the sha256 of the JSON of the ServeConfig) and then let callers do a SetServeConfig with HTTP If-Match semantics, failing if the hash has changed. Then callers can loop on a race. Or just fail and the user and re-run the command. But at least we wouldn't silently blow something else away.

/cc @marwan-at-work @maisem

**Comment by marwan-at-work** [comment]
@bradfitz without breaking the Go client, I see three ways of implementing this: 

1. Adding an ETag field to ipn.ServeConfig, maybe with `json:"-"` and just letting the Go client get/set it via HTTP Headers. 
2. Passing the ETag via `context.Context` and adding some APIs to get/set the if-match headers on the context.
3. Adding a new GetServeConfig SetServeConfig APIs, which might not be worth just for the sake of a single http header, but maybe worth it if we added new APIs for setting a partial config so the client wouldn't need to get the whole config and manipulate it, but just tells the API to set what it wants to set. 

Either of the 3 works for me, or others if I missed another way.

**Comment by marwan-at-work** [comment]
Fixed by #9327
