### ISSUE TITLE
BUG: Mullvad Exit Node and Linked Git Repo, documentation is missing ACL rules required.

### ISSUE THREAD

**Issue by jason-riddle** [tailscale/tailscale#9283]
### What is the issue?

When managing ACL rules via a linked Git Repo and trying to add a Mullvad Exit node, the following message is shown on the "Configure Mullvad VPN" page (https://login.tailscale.com/admin/settings/general/mullvad)

> Your tailnet's ACL file is managed via a linked Git repository. Mullvad configuration must be specified manually. [Learn more →](https://tailscale.com/kb/1258/mullvad-exit-nodes/)

After clicking the "Learn more →" link, it does not mention what ACL rules need to be added into the linked Git repo.

<img width="1920" alt="Screenshot 2023-09-07 at 12 11 28 PM" src="https://github.com/tailscale/tailscale/assets/2156866/719e9ee2-f8cf-4163-8c9f-9c4ee0531ace">

### Steps to reproduce

1. Manage ACL rules in a linked Git repo.
2. Navigate to the "Configure Mullvad VPN" page (https://login.tailscale.com/admin/settings/general/mullvad).
3. Shows the following message:
> Your tailnet's ACL file is managed via a linked Git repository. Mullvad configuration must be specified manually. [Learn more →](https://tailscale.com/kb/1258/mullvad-exit-nodes/)

### OS

macOS

### OS version

Ventura 13.2.1

### Tailscale version

N/A

**Comment by eugene1g** [comment]
This also applies when managing ACL rules manually within Tailscale UI (`Access Controls`). I'm trying to activate Mullvad exit nodes, and on the checkout screen the process fails with the error `Failed to write Mullvad configuration into ACL: test(s) failed`:

<img width="537" alt="screenshot 230907-4722" src="https://github.com/tailscale/tailscale/assets/147496/f3626eaf-d657-4a7a-be59-31b0bd97eb2b">

**Comment by raggi** [comment]
Quite right @jason-riddle, thank you for the report! I've updated the linked KB article, it now has https://tailscale.com/kb/1258/mullvad-exit-nodes/#acl-based-configuration covering this!

**Comment by raggi** [comment]
@eugene1g that may be a slightly different issue. If you're still experiencing that reach out to support and we'd love to dig in to whatever is getting stuck!
