### ISSUE TITLE
Unable to Complete "Configure Mullvad VPN" Checkout Flow

### ISSUE THREAD

**Issue by jason-riddle** [tailscale/tailscale#9295]
### What is the issue?

I've added the following ACL block to my ACLs

```json
"nodeAttrs": [
    {
        "target": ["my-email@gmail.com"],
        "attr": [
            "mullvad",
        ],
    },
]
```

where `target` contains my actual email, but something is still preventing me from completing the checkout flow. I'm not able to click the "continue to checkout" button. What else is needed to enable the checkout flow?

<img width="1920" alt="Screenshot 2023-09-07 at 4 54 28 PM" src="https://github.com/tailscale/tailscale/assets/2156866/8d2f3ab8-63ed-4d79-aa93-f8a0cf52dfbb">

### Steps to reproduce

1. Add to ACLs

```json
"nodeAttrs": [
    {
        "target": ["my-email@gmail.com"],
        "attr": [
            "mullvad",
        ],
    },
]
```

2. Visit https://login.tailscale.com/admin/settings/general/mullvad
3. Can't click "continue to checkout"

### OS

macOS

### OS version

Ventura 13.2.1

### Tailscale version

1.46.1

### Other software

N/A

### Bug report

BUG-6d602b8f323a43cbaa0311db9c5bf7463417ab2e36729bf0e9a64a9dd91a450d-20230908000054Z-8c22f2163a77357c

**Comment by catzkorn** [comment]
As detailed in your first screenshot - it looks like your tailnets ACLs are managed by a git repo. You will have to manually configure your devices, and can use the 'Manage add-ons' checkout flow that is found on the billing page to purchase your device packs. [Docs here](
https://tailscale.com/kb/1258/mullvad-exit-nodes/#what-should-i-know-about-using-mullvad-with-gitops-managed-acls).
