### ISSUE TITLE
How to use Android or iOS app with using --accept-routes=true args？

### ISSUE THREAD

**Issue by lcuwx2016** [tailscale/tailscale#9303]
### What is the issue?

These apps can't input some args like --accept-routes=true, at least I didn't find a way. Can anyone help?

### OS

iOS, Android

**Comment by DentonGentry** [comment]
Android, iOS, macOS, and Windows accept routes by default. Only Linux, the first client developed, has its default as false.

However: what problem are you actually running into? Is Android not able to access subnets advertised over the tailnet?

**Comment by lcuwx2016** [comment]
No problem. Thanks
