### ISSUE TITLE
Android: stalls in network throughput when using Mullvad exit node

### ISSUE THREAD

**Issue by bradclawsie** [tailscale/tailscale#9305]
### What is the issue?

This may or may not be a less-intelligently explained dup of https://github.com/tailscale/tailscale/issues/9299, but here goes.

Purchased Mullvad add-on and immediately tried it out on Samsung Tab S7 tablet and S20 phone, all up to date, both using Dallas exit hosts close to me in Texas.

As advertised, there is an initial lag where network operations seem stalled, but this kept coming back for me in any situation where I undertook operations that hit a new host during the VPN session (i.e. hit a new website, use Play Store, etc). Refreshing resources on a particular site in a short time frame yielded satisfactory results (i.e. move around inside HackerNews links etc), but even then, there were periodic stalls that would produce browser timeouts. The stalls always resolved, but only after significant delays that render the VPN too frustrating for real use.

FYI I also use NextDNS enabled in the Tailscale console...I don't believe this is the issue but just adding this.

### Steps to reproduce

Use Mullvad VPN option and just try regular internet use.

### OS

Android

### OS version

Android 13

### Tailscale version

latest Android version

### Other software

Tailscale NextDNS integration

**Comment by gbraad** [comment]
I am not sure that it is related, but seen this also on my Android device, but also on a Linux node. At first it takes a while to establish the connection (shows direct from status) and the page loads, but after a short time the connection is not actively used, and it seems to have lost the direct connection. it needs to re-establish and this takes time. Besides, it also looks when video plays back the connection shows a roof-tile like pattern of buffering, I do not see this with other VPN solutions I regularly use.

**Comment by raggi** [comment]
I believe this is indeed the same as #9299, and should be addressed in 1.48.2. If you find this recurs with 1.48.2, please open a bug with a [bug report](https://tailscale.com/kb/1227/bug-report/) reference or reach out to support and we'll dig in to find out what's wrong.
