### ISSUE TITLE
Tailscale Operator does not pass TS_DEBUG_FIREWALL_MODE to pods that it creates

### ISSUE THREAD

**Issue by rodrigc** [tailscale/tailscale#9310]
### What is the issue?

Relates to #391 
Relates to #7895

Tailscale Operator does not pass TS_DEBUG_FIREWALL_MODE to pods that it creates

In the Oracle Kubernetes (OKE) environment used by QuickNode, I recently tested
the latest Tailscale Operator.  I used this:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - env:
        - name: PROXY_IMAGE
          value: docker.io/tailscale/tailscale:unstable-v1.49.197
        - name: TS_DEBUG_FIREWALL_MODE
          value: nftables
        - name: AUTH_PROXY
          value: "true"
        - name: OPERATOR_LOGGING
          value: info
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_TAGS
          value: tag:k8s
        image: docker.io/tailscale/k8s-operator:unstable-v1.49.197
        name: operator
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
        volumeMounts:
        - mountPath: /oauth
          name: oauth
          readOnly: true
      serviceAccountName: operator
      volumes:
      - name: oauth
        secret:
          secretName: operator-oauth
```

The operator successfully deployed.  I was also able to successfully creates
an ingress which uses funnel, as I mentioned here: 

However, I also have a service which uses LoadBalancer, and is annotated like this:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: myargocdserver
  finalizers:
  - tailscale.com/finalizer
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: tailscale
  ports:
  - name: http
    nodePort: 31514
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30761
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: myargocdserver.xxx.ts.net
```

In this case the pod that the operator creates comes up
but it does not use TS_DEBUG_FIREWALL_MODE , and instead
tries to use the "old" iptables logic.

This results in errors that look like this:

```
boot: 2023/09/08 19:00:58 No authkey found in kube secret and TS_AUTHKEY not provided, login will be interactive if needed.
boot: 2023/09/08 19:00:58 Starting tailscaled
boot: 2023/09/08 19:00:58 Waiting for tailscaled socket
2023/09/08 19:00:58 logtail started
2023/09/08 19:00:58 Program starting: v1.49.197-t3280c81c9, Go 1.21.0: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:ts-victoria-metrics-cluster-vminsert-7f5ml-0", "--statedir=/tmp"}
2023/09/08 19:00:58 LogID: 45f47924847605de89fb765b2db56e0d12b46189b3de4fc8d08193541f0ae37e
2023/09/08 19:00:58 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
2023/09/08 19:00:58 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2023/09/08 19:00:58 router: default choosing iptables
2023/09/08 19:00:58 router: using iptables
2023/09/08 19:00:58 router: v6nat = false
2023/09/08 19:00:58 dns: [rc=unknown ret=direct]
2023/09/08 19:00:58 dns: using "direct" mode
2023/09/08 19:00:58 dns: using *dns.directManager
2023/09/08 19:00:58 link state: interfaces.State{defaultRoute=eth0 ifs={eth0:[XXXX llu6]} v4=true v6=false}
2023/09/08 19:00:58 magicsock: disco key = XXXXX
2023/09/08 19:00:58 Creating WireGuard device...
2023/09/08 19:00:58 Bringing WireGuard device up...
2023/09/08 19:00:58 Bringing router up...
2023/09/08 19:00:58 external route: up
2023/09/08 19:00:58 Clearing router settings...
2023/09/08 19:00:58 Starting network monitor...
2023/09/08 19:00:58 Engine created.
2023/09/08 19:00:58 monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5210 Table:254 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
2023/09/08 19:00:58 monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5230 Table:253 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
2023/09/08 19:00:58 monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5250 Table:0 Mark:16711680 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
2023/09/08 19:00:58 monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5270 Table:52 Mark:0 Pref:<nil> Expires:<nil> Metrics:<nil> Multipath:[]}}
2023/09/08 19:00:58 pm: using backend prefs for "profile-c02b": Prefs{ra=false dns=false want=true routes=[] nf=on host="monitoring-vminsert-dev-k8s" update=check Persist{lm=, o=, n=[0lmAA] u="monitoring-vminsert-dev-k8s.taild857f.ts.net"}}
2023/09/08 19:00:58 logpolicy: using system state directory "/var/lib/tailscale"
2023/09/08 19:00:58 got LocalBackend in 68ms
2023/09/08 19:00:58 Start
2023/09/08 19:00:58 Backend: logs: be:45f47924847605de89fb765b2db56e0d12b46189b3de4fc8d08193541f0ae37e fe:
2023/09/08 19:00:58 control: client.Login(false, 0)
2023/09/08 19:00:58 health("overall"): error: not in map poll
2023/09/08 19:00:58 control: doLogin(regen=false, hasUrl=false)
boot: 2023/09/08 19:00:58 tailscaled in state "NoState", waiting
2023/09/08 19:00:59 router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's
2023/09/08 19:00:59 control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
2023/09/08 19:00:59 control: RegisterReq: onode= node=[0lmAA] fup=false nks=false
2023/09/08 19:00:59 control: creating new noise client
2023/09/08 19:00:59 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2023/09/08 19:01:02 control: netmap: got new dial plan from control
2023/09/08 19:01:02 active login: yyy.xxx.ts.net
2023/09/08 19:01:02 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
2023/09/08 19:01:02 magicsock: SetPrivateKey called (init)
2023/09/08 19:01:02 wgengine: Reconfig: configuring userspace WireGuard config (with 0/1569 peers)
2023/09/08 19:01:02 wgengine: Reconfig: starting up network logger (node:xxx tailnet:xxx)
2023/09/08 19:01:02 wgengine: Reconfig: configuring router
2023/09/08 19:01:02 health("router"): error: setting up filter/ts-input: running [/sbin/iptables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.8 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
2023/09/08 19:01:02 peerapi: serving on http://xxx.xxx.xxx
2023/09/08 19:01:02 peerapi: serving on http://[xxx]:33847
boot: 2023/09/08 19:01:02 tailscaled in state "Starting", waiting
2023/09/08 19:01:02 magicsock: home is now derp-1 (nyc)
2023/09/08 19:01:02 magicsock: adding connection to derp-1 for home-keep-alive
2023/09/08 19:01:02 magicsock: 1 active derp conns: derp-1=cr0s,wr0s
2023/09/08 19:01:02 magicsock: endpoints changed: xxx:42829 (stun), 10.244.6.179:60681 (local)
2023/09/08 19:01:02 control: NetInfo: NetInfo{varies=true hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#1 portmap= link="" firewallmode="ipt-default"}
2023/09/08 19:01:02 derphttp.Client.Connect: connecting to derp-1 (nyc)
2023/09/08 19:01:02 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
boot: 2023/09/08 19:01:02 Running 'tailscale set'
2023/09/08 19:01:02 magicsock: derp-1 connected; connGen=1
boot: 2023/09/08 19:01:02 Deleting authkey from kube secret
boot: 2023/09/08 19:01:02 Installing proxy rules
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
boot: 2023/09/08 19:01:02 installing ingress proxy rules: executing iptables failed: exit status 3
```

The operator needs to be able to pass `TS_DEBUG_FIREWALL_MODE`
to the pods that are spun up in this case, so that we can force using nftables.

### Steps to reproduce

Deploy Tailscale operator using config I listed above in an Oracle Kubernetes environment

### OS

Linux

### OS version

Oracle Linux Server 8.8  , https://docs.oracle.com/en-us/iaas/images/image/7e68ad9b-2109-4cc2-a7af-2f47e8900817/

### Tailscale version

unstable-v1.49.197

### Bug report

BUG-3f7fc157b0949c712ce2ee441e83d2869cdf7282bc253adc827ec04eefc02a02-20230908205306Z-e7929ed9cfaa8cff

**Comment by rodrigc** [comment]
Ideally in the long term `TS_DEBUG_FIREWALL_MODE` is a temporary knob which will go away once the iptables detection logic is fully productionized.  But until then, it would be good if there was somehow a way to pass it down into the operator so that the [startReconcilers()](https://github.com/tailscale/tailscale/blob/1eadb2b608067f49f5691e5006bca946619938b0/cmd/k8s-operator/operator.go#L185) function which I think is part of what starts the tailscale image per pod, can honor `TS_DEBUG_FIREWALL_MODE`

**Comment by rodrigc** [comment]
Looking in the code, I think that [func (a *tailscaleSTSReconciler) reconcileSTS()](https://github.com/tailscale/tailscale/blob/1eadb2b608067f49f5691e5006bca946619938b0/cmd/k8s-operator/sts.go#L299) is where you would need to add a hook for `TS_DEBUG_FIREWALL_MODE`, since that is the function which creates the tailscale container which is the  proxy and sets a bunch of environment variables that are passed down to the container

**Comment by rodrigc** [comment]
Something like this might do the trick.
It would require you to specify the TS_DEBUG_FIREWALL_MODE as an environment variable in the `Deployment` used for specifying how the operator is started.

```
diff --git a/cmd/k8s-operator/ingress.go b/cmd/k8s-operator/ingress.go
index 72291afe..c79407f0 100644
--- a/cmd/k8s-operator/ingress.go
+++ b/cmd/k8s-operator/ingress.go
@@ -219,6 +219,7 @@ func (a *IngressReconciler) maybeProvision(ctx context.Context, logger *zap.Suga
                ServeConfig:         sc,
                Tags:                tags,
                ChildResourceLabels: crl,
+               TSDebugFirewallMode: defaultEnv("TS_DEBUG_FIREWALL_MODE", ""),
        }

        if _, err := a.ssr.Provision(ctx, logger, sts); err != nil {
diff --git a/cmd/k8s-operator/sts.go b/cmd/k8s-operator/sts.go
index 31aa6bad..ad61c4a6 100644
--- a/cmd/k8s-operator/sts.go
+++ b/cmd/k8s-operator/sts.go
@@ -66,6 +66,9 @@ type tailscaleSTSConfig struct {
        // Tailscale IP of a Tailscale service we are setting up egress for
        TailnetTargetIP string

+       // Knob to force the type of firewall used (iptables / nftables)
+       TSDebugFirewallMode string
+
        Hostname string
        Tags     []string // if empty, use defaultTags
 }
@@ -352,6 +355,13 @@ func (a *tailscaleSTSReconciler) reconcileSTS(ctx context.Context, logger *zap.S
                        },
                })
        }
+       if sts.TSDebugFirewallMode != "" {
+               container.Env = append(container.Env, corev1.EnvVar{
+                       Name:  "TS_DEBUG_FIREWALL_MODE",
+                       Value: sts.TSDebugFirewallMode,
+               })
+       }
+
        ss.ObjectMeta = metav1.ObjectMeta{
                Name:      headlessSvc.Name,
                Namespace: a.operatorNamespace,
```

**Comment by irbekrm** [comment]
Hi @rodrigc thanks for opening the issue and the PR.

The proxy pods that the operator creates [use iptables for the actual proxy logic](https://github.com/tailscale/tailscale/blob/v1.48.1/cmd/containerboot/main.go#L521) and that part is not controlled by the `TS_DEBUG_FIREWALL_MODE` env var, so just passing the var will not make them not use iptables. We should probably make that configurable, but it will require a bit more work.

Do you happen to know why iptables don't work on Oracle Kubernetes? Looking at the error in the log that you posted, I'm wondering whether it's not a caps issue same as with #9281

**Comment by irbekrm** [comment]
>  Table does not exist (do you need to insmod?)

Hmm, I guess this is to do with OKE nodes missing some kernel modules required to run iptables

**Comment by rodrigc** [comment]
I think this is an iptables vs. nftables issue with the OKE image ( https://docs.oracle.com/en-us/iaas/images/image/7e68ad9b-2109-4cc2-a7af-2f47e8900817/ ) which is run as part of Oracle Kubernetes clusters.

At QuickNode, we have a workaround where we forcibly replace `iptables` with `nftables`:

```
FROM --platform=linux/amd64 tailscale/tailscale:unstable

RUN apk update && apk add nftables

RUN rm -f /sbin/iptables && \
  ln -s /sbin/xtables-nft-multi /sbin/iptables && \
  rm -f /sbin/ip6tables && \
  ln -s /sbin/xtables-nft-multi /sbin/ip6tables
```

It would be good if we didn't have to apply this hack to the tailscale image, and could just use the tailscale image directly for our PROXY_IMAGE installed by the operator.

**Comment by rodrigc** [comment]
@irbekrm The link you posted to `installIPTablesRule` only applies to tailscale 1.48.1.
In the mainline of the tailscale code, the logic has changed a little.   Looks like `installIPTablesRule()` function is now gone, replaced by [installIngressForwardingRule()](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/cmd/containerboot/main.go#L702).

However `installIngressForwardingRule()` still directly calls the iptables binary.  So probably it would be good to refactor this function and make it honor `TS_DEBUG_FIREWALL_MODE=nftables`, so that it doesn't need to call the `iptables` binary directly?

**Comment by rodrigc** [comment]
Does [netfilterRunner](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/wgengine/router/router_linux.go#L42) have enough interfaces to replace the call to the iptables CLI in by [installIngressForwardingRule()](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/cmd/containerboot/main.go#L702)?

**Comment by irbekrm** [comment]
> @irbekrm The link you posted to installIPTablesRule only applies to tailscale 1.48.1

We still use iptables binary as before, this hasn't changed. I spent a bit of time looking at swapping iptables with nftables, but discovered that on some managed k8s, nodes don't have kernel modules to support nftables.. so I guess we can't avoid trying to dynamically discover which one needs running.


> Does [netfilterRunner](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/wgengine/router/router_linux.go#L42) have enough interfaces to replace the call to the iptables CLI in by [installIngressForwardingRule()](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/cmd/containerboot/main.go#L702)?

I need to take a look at this. There is also [an egress rule](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/cmd/containerboot/main.go#L685-L693) that uses iptables + we'd need to add nft CLI to the proxy image.

**Comment by irbekrm** [comment]
> Does [netfilterRunner](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/wgengine/router/router_linux.go#L42) have enough interfaces to replace the call to the iptables CLI in by [installIngressForwardingRule()](https://github.com/tailscale/tailscale/blob/70ea0734787450a618e504de0e2b929cfb2f06ff/cmd/containerboot/main.go#L702)?

I had a brief look, I don't think the neftilterRunner interface will be suited for this, it is very tailscaled specific. But we should be able to reuse the functionality, i.e to detect whether iptables or nftables should be used. I'll see if I can put together a quick prototype.

**Comment by rodrigc** [comment]
Yes this fix will be tricky since the combinations of iptables (legacy) vs. nftables are 
plentiful.
In addition to Oracle Kubernetes using nftables which I have found,

@clarkezone found that Azure AKS uses nftables here: https://github.com/tailscale/tailscale/issues/8111#issuecomment-1657235953

@zyclonite found that CoreOS uses nftables here: 
https://github.com/tailscale/tailscale/issues/5621#issuecomment-1707599073

**Comment by irbekrm** [comment]
Something along these lines could potentially work https://github.com/tailscale/tailscale/tree/irbekrm/k8sipnft
@maisem do you think this is the right way to go?

I don't have infra to test with any of the managed Kubernetes that folks have reported don't support iptables.

Not sure yet if we need to add anything to the [logic that automatically determines whether iptables or nftables should be used](https://github.com/tailscale/tailscale/blob/93cab562772fdd1719546d4c54b5ba09452eb411/wgengine/router/router_linux.go#L77-L124) to make it work on kube or whether we'll have to rely on folks setting the env var, I've only tested with the env var.

**Comment by irbekrm** [comment]
> Not sure yet if we need to add anything to the [logic that automatically determines whether iptables or nftables should be used](https://github.com/tailscale/tailscale/blob/93cab562772fdd1719546d4c54b5ba09452eb411/wgengine/router/router_linux.go#L77-L124) to make it work on kube or whether we'll have to rely on folks setting the env var, I've only tested with the env var.

Took a look at the [logic used to detect if iptables/nftables should be used](https://github.com/tailscale/tailscale/blob/v1.48.2/util/linuxfw/iptables.go#L26-L70)- it won't be sufficient to correctly auto-detect whether iptables/nftables _can_ be used. In a pod there will never be any default rules and whether either can be used depends on what kernel modules are loaded/built-in on host. We could either try to discover the modules from within the proxy container or try to create some fake rules. Or we might need to rely on users always setting the right value

**Comment by Protozoan1369** [comment]
This might be fixed in https://github.com/tailscale/tailscale/pull/9769

**Comment by irbekrm** [comment]
> This might be fixed in https://github.com/tailscale/tailscale/pull/9769

This has indeed been fixed. The proxy will now by default attempt to auto-discover whether the host supports iptables or nftables (preferring nftables) so users shouldn't need to configure it manually.
If required however, it can be set via `PROXY_FIREWALL_MODE` env var on the operator deployment manifest or `.proxyConfig.firewallMode` helm value.
