### ISSUE TITLE
FR: Allow some really privacy-preserving login method other then SSO/OCID, e.g. Mullvad's way.

### ISSUE THREAD

**Issue by gzqx** [tailscale/tailscale#9319]
### What are you trying to do?

Really having a service that respects user's privacy which at least allow user to login without information been shared or associated with other services. 

Given that you refuse Email method, the passphrase method used by Mullvad which you just cooperated with sounds a good idea.

### How should we solve this?

Allow other method to login other than SSO provided by tech giants or OIDC which is not private at all by its design.

### What is the impact of not solving this?

Your advertising of how much tailscale cares about privacy is **self-contradictory and lying**.

**Comment by bradfitz** [comment]
> Your advertising of how much tailscale cares about privacy is self-contradictory and lying.

I feel like this issue isn't off to a good start.

I'm going to close this.

But FWIW we support Passkeys (https://tailscale.com/blog/passkeys/) and bringing your own OIDC server that you can run (https://tailscale.com/blog/custom-oidc/).
