### ISSUE TITLE
OpenSUSE Tumbleweed - No internet after install and enable

### ISSUE THREAD

**Issue by smsegal** [tailscale/tailscale#932]
**Describe the bug**
After installing and enabling Tailscale on OpenSUSE Tumbleweed according to the instructions from [here](https://tailscale.com/kb/1047/install-opensuse-tumbleweed), I'm unable to access the internet. 

**To Reproduce**
1. Install Tailscale on OpenSUSE Tumbleweed
2. Enable the systemd service
3. Enable the tailscale device (`sudo tailscale up`)
4. No internet acccess

**Expected behavior**
I expect to have internet access after following the installation instructions for my platform. 

**Version information:**
 - Device: Desktop
 - OS: OpenSUSE Tumbleweed
 - OS version: 20201114
 - Tailscale version: Happens with both latest stable: 1.2.6 and unstable: 1.3.46

**Additional context**
~I had to add the `tailscale0` device to my home zone in `firewalld`. Maybe this is obvious to an experienced OpenSUSE user or network admin, but I'm neither :) I've been successfully using this on other distros and macOS just by following the instructions on the website, so I would expect the same experience on Tumbleweed as well. I think probably a small update to the instructions is all that is necessary.~

Turns out the above paragraph didn't work. I have no internet access when tailscale is running, but it comes back when I run `sudo tailscale down`. I'm able to access other connected tailscale devices, but that's it.

**Comment by DentonGentry** [comment]
Can you tell if the issue is not being able to reach DNS servers, or not being able to reach the Internet at all?

For example, "ping 8.8.8.8" would check if the Google DNS servers can be reached without needing DNS to succeed.

**Comment by smsegal** [comment]
Sorry, I experienced this bug while trying to find a distro to unify my different machines on. I've since moved on to running Fedora on all my linux boxes and haven't been able to reproduce this there.

**Comment by DentonGentry** [comment]
We've added an OpenSUSE client in an integration test, at this point I don't think there is a problem remaining to be addressed.
