### ISSUE TITLE
No internet connection when selecting a Mullvad exit node

### ISSUE THREAD

**Issue by gaetanoe** [tailscale/tailscale#9339]
### What is the issue?

Paid the Mullvad add-in. I try to select any exit node from Tailscale's selector. As soon as I select a Mullvad exit node from the app, the laptop stops connecting to the internet. I don't even know how to start diagnosing what is going on, as my knowledge in networking is basic. 

### Steps to reproduce

Tailscale tray icon -> Exit Node -> _any_exit_node_

### Are there any recent changes that introduced the issue?

I used to run Mullvad and Tailscale on this laptop. I was never able to get them to work together. I still have Mullvad app, without any credit now. I activated the Mullvad add-in. This is all too similar to what used to happen before. I wonder if there is a setting somewhere I need to find out and fix. 

### OS

macOS

### OS version

Ventura 13.5.2

### Tailscale version

1.48.1

### Bug report

BUG-24ccfecc8b55c88e61534332c27237963bd3787f3922b3780b223c0b890a79f3-20230911094310Z-8ccbd9662ae8c285

**Comment by demiise** [comment]
Just want to add that I have the same issue on Mac OS and iOS. Works fine when using my own exit node, but trying to use Mullvad just cuts all internet access. I understand this is beta, but without it working at all I'm going to need to consider asking for a refund since I need the access and will have to switch back to Mullvad.

**Comment by 0adapter** [comment]
Same issue on my end. 

macOS
Ventura 13.5.2
1.48.1

**Comment by raggi** [comment]
v1.48.2 is now rolling out, and you can get the build from https://pkgs.tailscale.com/stable/ if you want to get ahead of app store rollouts. This should significantly improve stability for this case.

**Comment by gaetanoe** [comment]
v1.48.2 did not change the behavior.

**Comment by 0adapter** [comment]
It's no better for me either. I still lose all internet connectivity.

**Comment by demiise** [comment]
I had a brief period where it worked, but it's now not again.

Have tried using v1.48.2 from the link above, and also v1.49.238 from TestFlight.

**Comment by raggi** [comment]
Hi @gaetanoe apologies that this took a little while to track down. I have updated the documentation here: [important dns considerations](https://tailscale.com/kb/1258/mullvad-exit-nodes/#important-dns-considerations) to detail a configuration step that is currently necessary. We should have a solution in place for 1.50 or 1.52 that will then avoid the need for this, but in the meantime please try applying one of the configurations as documented there, and let us know if that does not work.

**Comment by gaetanoe** [comment]
The section added to the documentation solves the issue, I just enabled overriding the local dns.  Thanks for the prompt response and documentation update. 

Btw, I did figure I should have customized the DNS settings, and went as far as add global nameservers, however I completely missed the "Override local DNS" setting.

**Comment by geoffeg** [comment]
This is still occurring for me. When I select any Mullvad exit node, I lose internet connectivity. I can still ping other machines on my tailscale network but not 8.8.8.8, 1.1.1.1, etc. MacOS 13.5.2, tailscale 1.48.2

**Comment by raggi** [comment]
> This is still occurring for me. When I select any Mullvad exit node, I lose internet connectivity. I can still ping other machines on my tailscale network but not 8.8.8.8, 1.1.1.1, etc. MacOS 13.5.2, tailscale 1.48.2

Hi @geoffeg, would you mind filing a new issue with a https://tailscale.com/kb/1227/bug-report/ or opening a [support ticket](https://tailscale.com/contact/support/). I would like to help and I will need more information in order to do so.

**Comment by den-kim** [comment]
Same problem here, might consider to reopen?
