### ISSUE TITLE
HA Pair - subnet Relay Node

### ISSUE THREAD

**Issue by rancod99** [tailscale/tailscale#934]
**Describe the bug**

- Only 1 of 2 Relay Nodes work at a time.

**To Reproduce**

- Configured two Linux clients and set up as Relays. Both are advertising the same subnet.
- Both respond to ping to each other, but when using Tailscale Status, only 1 will show flowing traffic at a time.
- Re-booting one, or both, does not fail-over to the second one. 
- Issuing command also does not help: sudo tailscale up --advertise-routes=10.0.0.0/16
- Disabling / Enabling Subnets in GUI also to no effect.

** Question **
- Is having a HA Relay Node pair behind the same WAN, on the same account possible?
- Can they be failed over, if only 1 can work at a time? ( active-standby)

**Comment by bradfitz** [comment]
I think this is a dup of issue #299.

**Comment by rancod99** [comment]
@bradfitz Brad thanks for the quick reply. Despite my initial search I didn't see that thread.

Nice job with the project. Hope you guys keep the Solo option long-term. Who knows, we may be able to pitch this at work one day..
