### ISSUE TITLE
FR: Support UPnP gateways without lease duration

### ISSUE THREAD

**Issue by mcheshkov** [tailscale/tailscale#9343]
### What are you trying to do?

I'm trying to setup direct connections to Tailscale on my laptop. 
My home router does not support UPnP with lease duration.
Because of this tailscale could not setup port forwarding, did not tell me about that, and every connection to laptop is DERPed, when other UPnP apps are working just fine.

More details in extra section

### How should we solve this?

One approach could be to add fallback to permanent lease, similar to Syncthing: if port mapping failed with specific error, retry with adjusted lease duration.
Another is to allow user to specify lease time explicitly (either number of seconds, boolean with "permanent lease" semantic, or even boolean with "MikroTik quirks mode" semantic), to be able to "opt-out" from RFC recommendation.
Both of approaches would require a bit of hacking around `GoodUntil` and `RenewAfter` for `upnpMapping`.

Also it would be a bit helpful if `tailscale netcheck` would report not only presence of UPnP gateway, but status of port forwarding attempts.

### What is the impact of not solving this?

For now I just don't use direct connections, since most of the time both machines are either in home network, or have persistent IPs.
I could setup static port forwarding on router, but since it's a laptop I would rather not.
Main issue for me is when I'm trying to access my laptop sitting at home from my phone from external network.

### Anything else?

Laptop is running tailscale 1.48.1 on Fedora Silverblue 38.
My home router is MikroTik hAP AC3 (model RBD53iG-5HacD2HnD), running RouterOS 7.11.2.
Router has UPnP enabled, and some of apps working just fine with it, e.g. Synthing and Transmission.
`tailscale netcheck` shows UPnP replies, and reports `PortMapping: UPnP`
There are `portmapper: saw UPnP type WANIPConnection1 at http://192.168.88.1:2828/gateway.xml; MikroTik Router (MikroTik)` in system journal.
But all connections to laptop ends up DERPed, and there's no NAT rules in router for tailscale.

After a bit of debugging I've discovered that MikroTik didn't implement support for lease duration; only unlimited permanent leases are supported.

Here's part of UPnP exchange for tailscale just after `systemctl restart tailscaled.service`, observed with `tcpdump -A port 2828`  on laptop:

Request
```
POST /upnp/control/mbmmiboxom/wanipconn-3 HTTP/1.1
Host: 192.168.88.1:2828
User-Agent: Go-http-client/1.1
Content-Length: 620
CONTENT-TYPE: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
Accept-Encoding: gzip

<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"><NewRemoteHost></NewRemoteHost><NewExternalPort>12308</NewExternalPort><NewProtocol>UDP</NewProtocol><NewInternalPort>41641</NewInternalPort><NewInternalClient>192.168.88.228</NewInternalClient><NewEnabled>1</NewEnabled><NewPortMappingDescription>tailscale-portmap</NewPortMappingDescription><NewLeaseDuration>7200</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>
```

Response
```
HTTP/1.1 500 Internal Server Error
CONTENT-LENGTH: 512
CONTENT-TYPE: text/xml; charset="utf-8"
DATE: Mon, 11 Sep 2023 13:31:52 GMT
EXT:
SERVER: RouterOS/7.11.2UPnP/1.0 MikroTik UPnP/1.0

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <s:Fault>
      <faultCode>s:Client</faultCode>
      <faultString>UPnPError</faultString>
      <detail>
        <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
          <errorCode>725</errorCode>
          <errorDescription>OnlyPermanentLeasesSupported</errorDescription>
        </UPnPError>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>
```

For example, syncthing in case of this specific failure just tries to recreate port mapping, but with duration of 0.

Code that does that is here:
https://github.com/syncthing/syncthing/blob/5ff11ce142d7fa417a9030e3d297911d5cebc925/lib/upnp/igd_service.go#L56-L82

Here's successful exchange for syncthing from tcpdump:

Request
```
POST /upnp/control/mbmmiboxom/wanipconn-3 HTTP/1.1
Host: 192.168.88.1:2828
User-Agent: syncthing/1.0
Content-Length: 623
Cache-Control: no-cache
Connection: Close
Content-Type: text/xml; charset="utf-8"
Pragma: no-cache
SOAPAction: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
Accept-Encoding: gzip

<?xml version="1.0" ?>
        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
        <NewRemoteHost></NewRemoteHost>
        <NewExternalPort>31870</NewExternalPort>
        <NewProtocol>TCP</NewProtocol>
        <NewInternalPort>22000</NewInternalPort>
        <NewInternalClient>192.168.88.228</NewInternalClient>
        <NewEnabled>1</NewEnabled>
        <NewPortMappingDescription>syncthing-31870</NewPortMappingDescription>
        <NewLeaseDuration>0</NewLeaseDuration>
        </u:AddPortMapping></s:Body>
        </s:Envelope>
```

Response
```
HTTP/1.1 200 OK
CONTENT-LENGTH: 282
CONTENT-TYPE: text/xml; charset="utf-8"
DATE: Mon, 11 Sep 2023 13:41:43 GMT
EXT:
SERVER: RouterOS/7.11.2UPnP/1.0 MikroTik UPnP/1.0

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:AddPortMappingResponse xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"></u:AddPortMappingResponse>
  </s:Body>
</s:Envelope>
```

Just in case, here's my current `tailscale version`

```
$ tailscale version
1.48.1
  tailscale commit: 528f95da6a5e12961b36a39bb3fa512c093d2330
  other commit: c4e4acad7220e23eb6f835e2b846c0378612d43a
  go version: go1.21.0
```

**Comment by bradfitz** [comment]
cc @andrew-d

**Comment by andrew-d** [comment]
@mcheshkov As of https://github.com/tailscale/tailscale/pull/9354 `tailscaled` should fall back to a permanent lease if leases with durations aren't supported. This will be included in the next Tailscale release, 1.50. Thanks for the detailed bug report!

**Comment by mcheshkov** [comment]
Thanks for a quick response!

**Comment by mcheshkov** [comment]
I've just updated to 1.50.0 and checked again, looks like it's working on a first glance: I can see new `tailscale-portmap` firewall rules on my router, and `tailscale status` report direct connections.

```
$ tailscale version
1.50.0
  tailscale commit: a920f02311d00d9bf8ba09503ec78fe6b054ca75
  other commit: eb5b0beea22407ee7208e60ed96927dc582a73a1
  go version: go1.21.1
```

**Comment by andrew-d** [comment]
Awesome! Glad to hear it 👍 If you run into any more issues, please let us know.
