### ISSUE TITLE
FR: Add MullvadDNS to Tailscale Nameservers dropdown

### ISSUE THREAD

**Issue by garrett-ts** [tailscale/tailscale#9345]
### What are you trying to do?

Creating this FR for tracking of interest. We should consider adding Mullvad's DNS as a preset dropdown option in the admin console.

![CleanShot 2023-09-11 at 12 30 18](https://github.com/tailscale/tailscale/assets/110842475/7fdf96b3-0c65-4a34-acc4-d5b68cc12e79)

**Comment by garrett-ts** [comment]
Thanks for mentioning that @bradfitz Will defer to the team for your question re: those endpoints.

I think in this case, agree, we should consider this FR related specifically to adding a prebuilt dropdown item.

**Comment by raggi** [comment]
These addresses are now in the Web UI!
