### ISSUE TITLE
'tailscale update' not working on Synology NAS

### ISSUE THREAD

**Issue by Smultie** [tailscale/tailscale#9361]
### What is the issue?

1.48.1 introduced CPU architecture detection (https://github.com/tailscale/tailscale/issues/8927) 
1.48.2 has just been released, so I was eager to update with the newly introduced 'tailscale update' command via SSH on my Synology NAS. 

Below the output

xxxxxxx@Diskstation:/$ sudo tailscale update
Password: 
This will update Tailscale from 1.48.1 to 1.48.2. Continue? [y/n] y
Download size: 23846912
Downloaded 32768/23846912 (0.1%)
Downloaded 8028160/23846912 (33.7%)
Downloaded 19054592/23846912 (79.9%)
Downloaded 23846912/23846912 (100.0%)
hash matched
synopkg install failed: exit status 1
output:
Failed to install package /tmp/tailscale-update1377942038/tailscale-88f6282-1.48.2-6000048002-dsm6.spk, error = [290]

### Steps to reproduce

1) SSH log in into NAS
2) 'sudo tailscale update'
3) enter password

### Are there any recent changes that introduced the issue?

Not to my knowledge

### OS

Synology

### OS version

Synology DSM 6.2.4

### Tailscale version

1.48.1

**Comment by Smultie** [comment]
Update:
You need to update the settings within DSM

After logging in to the DiskStation and clicking on "Package Center" -> Settings -> Allow Installation of packages published by: -> Anyone the package installed successfully.

Note: the package doesn't restart automatically, which is a bit of a bummer, since that does require you to sign into DSM to Run the package.

**Comment by awly** [comment]
Thanks for the report. This looks specific to DSM6. On DSM7 the package restarts automatically and there is no setting in Package Center for package publishers.

I'll look into forcing a restart and adding a better error message on DSM6.
