### ISSUE TITLE
windows: logtail uploads fail with "invalid JSON message" sometimes

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#937]
**Describe the bug**
On the Windows client, sometimes log message uploads fail with HTTP error 400 due to "invalid JSON message\n":

**To Reproduce**
It seems to happen every few seconds on Windows when logs are being generated

**Expected behavior**
No logtail errors

**Actual behavior**
With a slightly modified Windows client that saves the request data before it is compressed, this is an example of what is occurring:

logtail: upload: log upload of 176 bytes compressed failed 400: "invalid JSON message\n"
"{\"text\": \"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{\\\"logtail\\\": {\\\"client_time\\\": \\\"2020-11-17T11:31:58.3596196-08:00\\\"}, \\\"text\\\": \\\"magicsock: ignoring pre-DERP map, STUN-less endpoint update: [10.0.2.15:41641]\\\\n\\\"}\\n\"}\n"
logtail: backoff: 7 msec

The number of \x00 bytes at the start varies in length, possibly proportional to the length of the log message. It does not seem to be specific to any particular log message.

**Version information:**
 - Device: Windows 10 VM, seen on other versions and on a Windows desktop
 - OS: Windows. I haven't checked for this on other OSes.
 - OS version: Windows 10
 - Tailscale version: 1.2.x for sure, many 1.1 versions too

**Comment by josharian** [comment]
@bradfitz knows why this is happening. I forget the details, something about shared state between multiple clients on windows due to shared env vars (?), so two clients fight over the filch buffers.

**Comment by bradfitz** [comment]
This happens when tailscaled.exe is run in the foreground (as with the `tswin.exe` dev tool) alongside the GUI. Both use the same logtail/filch files.

**Comment by DentonGentry** [comment]
I believe we've now avoided the worst part of the problem, logs with large numbers of zero bytes are suppressed now.

**Comment by DentonGentry** [comment]
As a fix to drop log messages consisting of long sequences of NUL bytes went in a year ago, I don't think there is more to be done here. Barring further comment we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT, believed fixed.
