### ISSUE TITLE
FR: Provide JSON output option for 'exit-node list'

### ISSUE THREAD

**Issue by geoffeg** [tailscale/tailscale#9378]
### What are you trying to do?

I'm trying to write a SwiftBar plugin to display the hostname of the exit node I'm using, as well as a list of available exit nodes when I select the menubar item. 'exit-node list' does not provide an option for JSON output like some other tailscale subcommands do.

### How should we solve this?

Provide a JSON output option for tailscale exit-node list

### What is the impact of not solving this?

Writing a regex to parse the column-based output of exit-node list

### Anything else?

Currently using tailscale 1.48.1

**Comment by bradfitz** [comment]
Both the `tailscale status` and `tailscale exit-node list` textual output formats are just getting their data from `tailscale status --json`. So this feature request is already done: run `tailscale status --json` or https://pkg.go.dev/tailscale.com/client/tailscale#Status if you're using Go.

**Comment by bradfitz** [comment]
For example:

```
% tailscale status --json | jq -r '.Peer[] | select(.ExitNodeOption == true) | (.DNSName + "   " + .Location.City)' | head -10
gb-mnc-wg-007.mullvad.ts.net.   Manchester
jp-tyo-wg-001.mullvad.ts.net.   Tokyo
de-fra-wg-401.mullvad.ts.net.   Frankfurt
us-lax-wg-303.mullvad.ts.net.   Los Angeles, CA
ch-zrh-wg-503.mullvad.ts.net.   Zurich
se-got-wg-002.mullvad.ts.net.   Gothenburg
us-den-wg-103.mullvad.ts.net.   Denver, CO
de-fra-wg-302.mullvad.ts.net.   Frankfurt
nl-ams-wg-202.mullvad.ts.net.   Amsterdam
se-got-wg-003.mullvad.ts.net.   Gothenburg
```

**Comment by geoffeg** [comment]
That works great, thanks!
