### ISSUE TITLE
[Synology] tailscale configure-host does not create tun device

### ISSUE THREAD

**Issue by Tom7320** [tailscale/tailscale#9383]
### What is the issue?

I tried to enable Synology outbound connections as explained [here](https://tailscale.com/kb/1131/synology/#enabling-synology-outbound-connections). But tailscale configure-host does not create the tun device. There are no error messages when I run the scrip on the console.

Tailscale debug info says tun=true. But there is no tun device visible in the output of ip a?!

### Are there any recent changes that introduced the issue?

I think it stopped working with the latest TS update. I was able to see the tun device with ip a earlier.

### OS version

DSM 7.2-64570 Update 1

### Tailscale version

Debug info: Tailscale 1.48.2, tun=true, DSM7

### Bug report

BUG-1b2d4b1c5e74eaaa43f7800080cc1e71a2ebf44b8921bd8f5c51ff83c270838c-20230913105636Z-50b460bd4f7d401b

**Comment by Tom7320** [comment]
Addendum: maybe I am confused. What I am supposed to see in the output of ip a? A tun device? A tailscale device? Or both?
What I am supposed to see in the output of ls -l /dev/net? There is a tun device without running tailscale configure-host?! Please excuse my confusion.....

**Comment by DentonGentry** [comment]
The `/dev/net/tun` device in the filesystem should already exist, it is part of the image which Synology ships. `tailscale configure-host` sets the permissions on it, to allow a non-root process to use it.

In `ip addr show` you should see a `tailscale0` device. This is a TUN device, renamed.

**Comment by Tom7320** [comment]
Thx for clarification! I was falsely looking for a tun device all the time....
