### ISSUE TITLE
Mullvad exit nodes need tailnet lock signing to work

### ISSUE THREAD

**Issue by virtualm2000** [tailscale/tailscale#9387]
### What is the issue?

I have activated the Mullvad plugin but the exit nodes didn't appear in the clients.
I have the tailnet lock active and all the mullvad nodes are locked out.

```
The following nodes are locked out by tailnet lock and cannot connect to other nodes:
	hk-hkg-wg-102.mullvad.ts.net.	100.93.104.36,fd7a:115c:a1e0:ab12:4843:cd96:625d:6824	nDYmJP3CNTRL	nodekey:e64713d45bbc896bcfb965b38b732a96a0f88a62e14bf2b115f9aedcf39d6822
	us-bos-wg-102.mullvad.ts.net.	100.89.129.123,fd7a:115c:a1e0:ab12:4843:cd96:6259:817b	nBxKea2CNTRL	nodekey:c1c9a669d24e6eec76ffad844be41b20edb506453ba76234b3a9f858d659816d
	jp-tyo-wg-001.mullvad.ts.net.	100.100.131.39,fd7a:115c:a1e0:ab12:4843:cd96:6264:8327	nBuUct2CNTRL	nodekey:014a36ce1434c020f2dff8e666039ee103277165aaadd304ec16d8d949648322
	us-qas-wg-001.mullvad.ts.net.	100.121.87.35,fd7a:115c:a1e0:ab12:4843:cd96:6279:5723	nqoDmt5CNTRL	nodekey:50a34b0a29a47b9e11a91763e9417222e04eea7bf6555a434f7bccf4ddb95722
	ch-zrh-wg-005.mullvad.ts.net.	100.113.157.26,fd7a:115c:a1e0:ab12:4843:cd96:6271:9d1a	nJMqgQ3CNTRL	nodekey:755fda1e1c06d1f9a9d17baf4afadd5a30ad77284f0c316213f9eebffd719d13
	au-syd-wg-002.mullvad.ts.net.	100.67.91.114,fd7a:115c:a1e0:ab12:4843:cd96:6243:5b72	n9jS4K4CNTRL	nodekey:95478300ecbe8808590eecf9fbace1d02a3cc1972cdda85dbb68dfa90a035b71
	us-atl-wg-203.mullvad.ts.net.	100.74.210.123,fd7a:115c:a1e0:ab12:4843:cd96:624a:d27b	ncfSyp4CNTRL	nodekey:9d942f23ed99cc30b6b62b6892359ca236e3be7e1bc47ae153383550afcad277
	gb-mnc-wg-001.mullvad.ts.net.	100.104.54.116,fd7a:115c:a1e0:ab12:4843:cd96:6268:3674	nXfGuh5CNTRL	nodekey:43692124b6d3485c66a693c61e0ab61ddc4c431ec27333d90a05696193283673
	se-sto-wg-002.mullvad.ts.net.	100.122.174.102,fd7a:115c:a1e0:ab12:4843:cd96:627a:ae66	nFAa8J1CNTRL	nodekey:ab66593dfba63da4559780c97f335d405fc61df7ba0580334361996476faae62
	us-lax-wg-102.mullvad.ts.net.	100.108.108.45,fd7a:115c:a1e0:ab12:4843:cd96:626c:6c2d	nE3zFD4CNTRL	nodekey:2ddc2f6ecea63b111ba572d103767faa6132268db0553750f78fafdd416c6c1c
...

```

After I've signed one exit node it appeared in the list and I could use it.

### Steps to reproduce

Activate mullvad plugin with tailscale lock enabled.

### OS

Linux, macOS, Windows, iOS, Android, Synology, Other

### OS version

Ventura 13.5.2, iOS 17

### Tailscale version

1.48.2

**Comment by virtualm2000** [comment]
So do I need to sign all the mullvad nodes I want to use? There are several hundred.

Thank you!

**Comment by raggi** [comment]
Network Lock as a feature is there so that you have cryptographic assurance that the control server can not add nodes to your tailnet without your cryptographic proof that this is ok.

The feature request here seems to be to request to reverse that security posture - which is a feature we already offer, you can operate without network lock.

Am I misunderstanding your request?

**Comment by virtualm2000** [comment]
I was thinking for a way to sign all the mullvad exit nodes at once. Also there is the issue when the mullvad servers are offline and new ones are available. You have to keep signing the exit nodes before using. 


> The feature request here seems to be to request to reverse that security posture - which is a feature we already offer, you can operate without network lock.

This is what I ended up doing. 

Thank you!

**Comment by lemisieur** [comment]
Just came across this issue while searching why the mullvad nodes were not showing in my tailscale client. Maybe having a quick note or popup on the client to "warn" about this would be enough? Just to give a bit more visibility.

I do agree that if you'd op in for network lock, you'd want to keep the mechanism in place to "manually" authorize new nodes

**Comment by virtualm2000** [comment]
> I do agree that if you'd op in for network lock, you'd want to keep the mechanism in place to "manually" authorize new nodes

Yes, it makes sense. And for the signing part, I think a script would do the job nicely.

**Comment by virtualm2000** [comment]
Here is a zsh script to sign the nodes in bulk:

```
#!/bin/zsh

# Define the tailscale alias
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"

# Define signing node tlpub
tlpub="insert your signing node public key tlpub:......"

grep_output=$(tailscale lock status | grep -E 'gb-.*nodekey') #modify the gb- with the location you need

# echo "$grep_output"

echo "$grep_output" | while IFS= read -r line; do
    echo "$line"

    if [[ "$line" =~ "nodekey:"[[:space:]]*(.*) ]]; then
        matched_string="nodekey:${match[1]}"
        # echo "$matched_string"
        
        tailscale lock sign "$matched_string" "$tlpub"
        # Sleep for 5 seconds
        sleep 5
    fi
done
```

**Comment by catzkorn** [comment]
This is working as intended, but we have updated our [Mullvad documentation](https://tailscale.com/kb/1258/mullvad-exit-nodes/?q=mullvad#what-should-i-know-about-using-mullvad-with-tailnet-lock) to flag that tailnets using tailnet lock will need to sign Mullvad exit nodes in order for them to be usable.

**Comment by catzkorn** [comment]
This is working as intended, but we have updated our [Mullvad documentation](https://tailscale.com/kb/1258/mullvad-exit-nodes/?q=mullvad#what-should-i-know-about-using-mullvad-with-tailnet-lock) to flag that tailnets using tailnet lock will need to sign Mullvad exit nodes in order for them to be usable.

**Comment by Rogue-Git-Dev** [comment]
There must be a way to make the lock sign command take an unlimited quantity of exit node node keys, viz. several hundred Mullvad VPN keys. With regards to batch signing in the CLI, I propose the lock sign command be able to take in an unlimited number of node keys separated by spaces followed by the trusted signing  key. Perhaps that is more complicated than I realise but why cannot it take in and validate each key at time of execution?

With regards to the ZSH script this is super cool! I will definitely give this a go if it seems feasible. Currently, I launch a text editor, paste the copied output from Terminal, then clean each and every line to include just the node key only to wrap that with tailscale lock sign before the node key then the trusted signing key after. I even made TextExpander snippets to make it more efficient but it is ridiculous withal. If someone has got all of the 400+ nodes ready to be signed using the script I would appreciate a copy. If I decide to disable Tailnet Lock and use this then I must do it myself and save it for future.

**Comment by Rogue-Git-Dev** [comment]
Also, is it feasible to include all country codes in the script instead of modifying the script for each individually? If yes then what is the syntax for that? I wish to use the script without modification for each time I need sign exit nodes different in country code.

**Comment by Rogue-Git-Dev** [comment]
I asked if the script can be modified for all country codes. After I refreshed my brain on the grep syntax I modified the script to use the following line. I had to copy and paste the ‘.*nodekey’ string thirty-nine times. My line worked. The script took 39m31s502ms to run. Interestingly the nodes were not signed in order of country code as organised in the script. Sometimes it went slowly and sometimes it went quickly. For the script to sign every Mullvad VPN exit node online currently one must replace the relevant line with the following line and of course either remove or modify the comment.
    grep_output=$(tailscale lock status | grep -E 'al-.*nodekey|at-.*nodekey|au-.*nodekey|be-.*nodekey|bg-.*nodekey|br-.*nodekey|ca-.*nodekey|ch-.*nodekey|co-.*nodekey|cz-.*nodekey|de-.*nodekey|dk-.*nodekey|ee-.*nodekey|es-.*nodekey|fi-.*nodekey|fr-.*nodekey|gb-.*nodekey|gr-.*nodekey|hk-.*nodekey|hr-.*nodekey|hu-.*nodekey|ie-.*nodekey|il-.*nodekey|it-.*nodekey|jp-.*nodekey|lv-.*nodekey|mx-.*nodekey|nl-.*nodekey|no-.*nodekey|nz-.*nodekey|pl-.*nodekey|pt-.*nodekey|ro-.*nodekey|rs-.*nodekey|se-.*nodekey|sg-.*nodekey|sk-.*nodekey|ua-.*nodekey|us-.*nodekey|za-.*nodekey')

**Comment by abkslm** [comment]
> grep_output=$(tailscale lock status | grep -E 'al-.*nodekey|at-.*nodekey|au-.*nodekey|be-.*nodekey|bg-.*nodekey|br-.*nodekey|ca-.*nodekey|ch-.*nodekey|co-.*nodekey|cz-.*nodekey|de-.*nodekey|dk-.*nodekey|ee-.*nodekey|es-.*nodekey|fi-.*nodekey|fr-.*nodekey|gb-.*nodekey|gr-.*nodekey|hk-.*nodekey|hr-.*nodekey|hu-.*nodekey|ie-.*nodekey|il-.*nodekey|it-.*nodekey|jp-.*nodekey|lv-.*nodekey|mx-.*nodekey|nl-.*nodekey|no-.*nodekey|nz-.*nodekey|pl-.*nodekey|pt-.*nodekey|ro-.*nodekey|rs-.*nodekey|se-.*nodekey|sg-.*nodekey|sk-.*nodekey|ua-.*nodekey|us-.*nodekey|za-.*nodekey')

Wanted to chime in for anyone else that tries this to say this chunk isn't necessary to approve all Mullvad nodes. Instead, replace `grep -E 'uk-.*nodekey'` (on line 9) with `grep -E 'mullvad.*nodekey'`.  I also changed `sleep 5` to `sleep 1`, since I can't see benefit to waiting 5 seconds before sending another signature.

**Comment by Rogue-Git-Dev** [comment]
Having been writ by Andrew Blakeslee Moore on Friday 12 January 2024 at 17:19:32 -0600 ⬇️

> Wanted to chime in for anyone else that tries this to say this chunk isn't necessary to approve all Mullvad nodes. Instead, replace `grep -E 'uk-.*nodekey'` (on line 9) with `grep -E 'mullvad.*nodekey'`.
I did it the messy way but revised it to
> grep_output=$(tailscale lock status | grep -E '[a-z]{2}-.*nodekey')
Is your mullvad.*nodekey part more efficient than my '[a-z]{2}-.*nodekey part?
> I also changed `sleep 5` to `sleep 1`, since I can't see benefit to waiting 5 seconds before sending another signature.
I erased the entire sleep code for it is not necessary.

-- 
Brother J.

**Comment by abkslm** [comment]
> I did it the messy way but revised it to
> grep_output=$(tailscale lock status | grep -E '[a-z]{2}-.*nodekey')
> Is your mullvad.*nodekey part more efficient than my '[a-z]{2}-.*nodekey part?

My concern with `[a-z]{2}` is that it will match *all* hosts that contain two letters followed by a '-', but doesn't specify `mullvad`, so it could inadvertently approve non-Mullvad/unexpected nodes (eg it matches `malicious-node.ts.net`. Even better (/s), if your tailnet uses the 'Fun DNS' naming scheme, this will match *every* node that's locked out of your tailnet.

(Technically, my `mullvad.*nodekey` solution is also vulnerable to hostnames with `mullvad` in them (eg `malicious-mullvad.fun-dns.ts.net` (the true mullvad hosts are of format `country-datacenter-proto-node.mullvad.ts.net`), so still run with caution)

> I erased the entire sleep code for it is not necessary.

I figured the same, but wanted to be careful just in case the rapid sequence of connections triggered rate-limiting/DoS protection (either on Tailscale's end or my work's).

Thanks for your reply! I appreciate the discussion :)

**Comment by felschr** [comment]
For anyone interested, I've adapted this as a [nushell](https://www.nushell.sh/) script that uses `tailscale lock status --json` to parse the output:
https://gist.github.com/felschr/fb18163924bbe748a6226b891ef44427

**Comment by Rogue-Git-Dev** [comment]
What happened? Something was changed in version 1.61.64 and it actually fixed the biggest complaint I had since I began to use Tailscale March 2023. Since version 1.61.64 Little Snitch does not prompt me to allow connexions both TCP and UDP; it connects automatically and works as intended. Something must have changed in the network extension for that particular binary is the one Little Snitch references. I am quite interested to know details for I have wondered why exactly Little Snitch prompted me every single time I launched Tailscale even if the same exact version without upgrading. This is such a huge positive change I doubt most persons will appreciate.

-- 
Brother J.

**Comment by Rogue-Git-Dev** [comment]
Having been writ by Brother J. on Friday 01 March 2024 at 06:52:27 -0600 ⬇️

> What happened? Something was changed in version 1.61.64 and it actually fixed the biggest complaint I had since I began to use Tailscale March 2023. Since version 1.61.64 Little Snitch does not prompt me to allow connexions both TCP and UDP; it connects automatically and works as intended. Something must have changed in the network extension for that particular binary is the one Little Snitch references. I am quite interested to know details for I have wondered why exactly Little Snitch prompted me every single time I launched Tailscale even if the same exact version without upgrading. This is such a huge positive change I doubt most persons will appreciate.
>
> -- 
> Brother J.
I wrote in too soon. Version 1.61.69 makes Little Snitch prompt again.

-- 
Brother J.

**Comment by the-xentropy** [comment]
For those with Windows nodes, here's a powershell one-liner to add all nodes:
```
foreach ( $nodekey in (tailscale lock | Select-string -Pattern ".mullvad.ts.net.\t" | Select-Object -ExpandProperty Line | Select-String -Pattern "(nodekey:[0-9A-Za-z]+)" | Select-Object -ExpandProperty Matches).Value) { tailscale lock sign $nodekey }
```

It just grabs all the nodes matching ".mullvad.ts.net.\t" - the tab character is to make sure it ENDS with the known FQDN suffix rather than it being some arbitrary substring - then grabs the `nodekey` and runs it through `tailscale lock sign <nodekey>`

Personally I modified the regex to be: ` "\tus-[^\.]*.mullvad.ts.net.\t"` because I don't care about other exit nodes than the ones in the US.

**Comment by zackify** [comment]
I'm surprised this is closed. Just because you *can* go sign the nodes, doesn't make this user friendly.

A small footnote that says you need to sign nodes isn't helpful when you pay for something and nothing appears in your exit node list.

Providing a lock sign command for a region of mullvad nodes would help.

Even better would be a providing a list of the node names, it's hard to find the ones you want to sign in that mega list because there is no page with a mapping of location -> .ts.net node values either.

**Comment by Rogue-Git-Dev** [comment]
Having been writ by Zach Silveira on Tuesday 02 April 2024 at 12:50:37 -0500 ⬇️

> I'm surprised this is closed. Just because you *can* go sign the nodes, doesn't make this user friendly.
I concur; it is a frustrating workaround.
> A small footnote that says you need to sign nodes isn't helpful when you pay for something and nothing appears in your exit node list.
I missed that footnote and disabled Tailnet Lock because I knew not what was wrong. I knew I did not understand something, re-enabled it, and found the footnote. Before I found the original script I signed each individually and it took days.
> Providing a lock sign command for a region of mullvad nodes would help.
A more universal solution would be better.
> Even better would be a providing a list of the node names, it's hard to find the ones you want to sign in that mega list because there is no page with a mapping of location -> .ts.net node values either.
That list is dynamic however. To sign the nodes en masse shall be available in clients that have such authority to sign nodes regardless if they have got a terminal. For example, iOS clients can be added as signing nodes but they lack consoles thus it is actually pointless to make them able to sign nodes. To add a GUI to sign nodes such as Mullvad nodes after background verification that x client possesses such authority to sign nodes will take time but will be the answer to this fiasco.

-- 
Brother J.

**Comment by the-xentropy** [comment]
I definitely don't want gaps in my network protections just for the sake of
saving myself a one-time churn of 10 minutes. Maybe we should have separate
signing for exit nodes and normal nodes to further drive least privilege
though.

**Comment by rtlong** [comment]
I struggled with this too, after reading the docs and missing that little note at the very bottom. I think it would be ideal if this were called out a bit more prominently when describing the initial setup.

**Comment by GienKu** [comment]
Hello, I am struggling with same problem, but now signing mullvad nodes doesn't even work from my terminal it says:
`error: 500 Internal Server Error: signing failed: request returned (404): node not found`
even if I can clearly see and copy signing nodekey from the list that was returned by 
`tailscale lock status --json`

I paid for that addon but to be honest if this is the state of that feature I will resign.
Just an official website with all mullvad exit-nodes with ready to copy command could be enough even for beta.
