### ISSUE TITLE
tailscale-nignix-auth v0.1.3 Ubuntu packages missing

### ISSUE THREAD

**Issue by sitic** [tailscale/tailscale#9399]
### What is the issue?

In
- #7323 

tailscale-nignix-auth was updated to v0.1.3, however no .deb files were pushed to https://pkgs.tailscale.com.

I checked both the stable and unstable branch, the unstable branch seems to be missing `tailscale-nginx-auth` completely.

### Steps to reproduce

```
works:
$ curl -I https://pkgs.tailscale.com/stable/tailscale-nginx-auth-0.1.2-amd64.deb

doesn't (404s):
$ curl -I https://pkgs.tailscale.com/stable/tailscale-nginx-auth-0.1.3-amd64.deb
$ curl -I https://pkgs.tailscale.com/stable/tailscale-nginx-auth-0.1.3-arm64.deb
```

**Comment by DentonGentry** [comment]
Packages uploaded.
