### ISSUE TITLE
Streaming to ElsaticSearch not working

### ISSUE THREAD

**Issue by Churator** [tailscale/tailscale#9403]
### What is the issue?

Streaming to ES configured, and looks like it should be working.
However, no logs appear to be arriving at the ES cluster.

![image](https://github.com/tailscale/tailscale/assets/62523824/169818af-9cfd-4aa1-9097-ad6ee48a3d71)

### Steps to reproduce

Configure Elastic Search, check logs

**Comment by DentonGentry** [comment]
There is not enough information here to do anything. Please file a support ticket instead: https://tailscale.com/contact/support/

We need to be able to look at the log streaming configuration of the tailnet.
