### ISSUE TITLE
Missing installation instructions for OpenSuse Leap 15.3, 15.4, and 15.5

### ISSUE THREAD

**Issue by MrGaribaldi** [tailscale/tailscale#9404]
### What is the issue?

On the [setup page for Linux](https://tailscale.com/kb/1031/install-linux/) you only list support for OpenSuse Leap 15.1 and 15.2, whereas you actually support [15.3](https://pkgs.tailscale.com/stable/opensuse/leap/15.3/tailscale.repo)., [15.4](https://pkgs.tailscale.com/stable/opensuse/leap/15.4/tailscale.repo) and [15.5](https://pkgs.tailscale.com/stable/opensuse/leap/15.5/tailscale.repo).

Perhaps you could update the docs to show this? And maybe just have a single page for OpenSuse Leap and a pull-down menu to select version, which then updates the URL? Since all the other instructions are identical.

Might make it both tidier and easier to update when you add support for 15.6 when it is released.

Sorry if this is posted the wrong place.

### Steps to reproduce
Go to https://tailscale.com/kb/1031/install-linux/ and scroll down to OpenSuse Leap. Find that there are no instructions for 15.3, 15.4, nor 15.5.  

Visiting https://tailscale.com/kb/1049/install-opensuse-leap-15.2/ you can see that it is listing the repository to add at https://pkgs.tailscale.com/stable/opensuse/leap/15.2/tailscale.repo

Copy the link and paste into an empty tab, and chance the 2 to 3, 4 or 5 and see that there are repositories for those versions.

### OS

Linux

### OS version

OpenSuse Leap 15.5

**Comment by noncombatant** [comment]
Thanks for reporting this bug! :)

**Comment by FroggyFlox** [comment]
It seems this issue is still present (own experience + https://github.com/tailscale/tailscale/issues/12541). Maybe this issue could be reopened?

**Comment by MrGaribaldi** [comment]
It was fixed for a while, but then reverted back to broken :-( 

Really strange, since the repos are actually there.. 

And on mobile it even references the variables from the fixed version, but doesn't expose the select version drop down...

**Comment by FroggyFlox** [comment]
Thanks for the additional context and information, @MrGaribaldi ... It didn't cross my mind that could have been the case, my apologies.
Should this be reopened or a new issue created, do you think?

**Comment by MrGaribaldi** [comment]
No need to apologize to me :-) 

It's probably easier to get attention with the new issues, so I'd go with that. And you've already referenced this one, so it should be easy for them to fix.


My guess to what happened is that the drop down didn't match styling rules or similar and therefore was dropped, instead of having the design reworked. But I could be completely wrong as well..
