### ISSUE TITLE
Unable to authenticate machine and unable to access network "bad tailscale-authstate2 cookie"

### ISSUE THREAD

**Issue by LazerDickMcCheese** [tailscale/tailscale#9417]
### What is the issue?

I was suddenly unable to connect my devices to my Tailscale network. It has been set up for about a month now, and it has been working flawlessly for a few weeks until a couple days ago. The error I saw in my browser when trying to log in isn't specific enough for a novice like myself to self-diagnose and fix it, but I saw an update from 1.48.1 to 1.48.2 so I updated. Now I have to "restart the Tailscale Windows Service" which doesn't change when the service is restarted.

If I use to the tray icon to try to access the admin dashboard the login leads to the subject error.

### Steps to reproduce

Similar to another issue, but I'm using Firefox: https://github.com/tailscale/tailscale/issues/4835#issue-1268284036

The tray icon usually doesn't try to open my browser, but even if it does I get the error in the title. If I'm lucky and get the login screen, I'm still unable to login via my email (which requires two email addresses) or through GitHub. 

As a sidenote: while I understand there's an issue with GitHub-Tailscale connectivity specifically, shouldn't that be reason enough to rethink having it as an option until it is fixed?

### Are there any recent changes that introduced the issue?

The issue popped up spontaneously, the update to 1.48.2 made it seemingly worse.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.48.2

### Bug report

BUG-558f263c6542a2db1be27a60f61b431bf972e84b78e5324b5120c9a7fe7f4442-20230915000114Z-61f9ee7300c0ec23

**Comment by kelivel** [comment]
What happens when you type `tailscale up` in cmd.exe — can you describe the behavior? Seeing a copy of your logs from `%ProgramData%\Tailscale\` would be helpful as well. Feel free to email those to us directly at support@tailscale.com and mention my name (Keli) and this GH issue so I can take a look. 

>  while I understand there's an issue with GitHub-Tailscale connectivity specifically, shouldn't that be reason enough to rethink having it as an option until it is fixed?

Hm I'm not sure I follow here, as the issue linked is Android-app specific. Can you share a few more details?

**Comment by derkrasseleo** [comment]
Just if anyone stumbles upon this issue: My issue was that I opened the link from cli in the default Firefox profile but opened the github link in my personal container, which led to this error message. When I opened the tailscale login link in my personal container, it worked.

**Comment by xizheyin** [comment]
Thanks, I can connect to controlplane.tailscale.com correctly. but still stuck when sudo tailscale up.

**Comment by bilbags** [comment]
@derkrasseleo Thank you so much for posting the Firefox container issue - I was banging my head against the wall trying to figure out what was happening, but switching containers fixed my issue immediately.

**Comment by anishre** [comment]
Literally had the same issue and scrolled down to find @derkrasseleo giving the perfect reason for this. Switched containers and all good to go now. Cheers!
