### ISSUE TITLE
Problem with always on vpn



### ISSUE THREAD

**Issue by makinen2009** [tailscale/tailscale#9418]
Hi I have lg k8 g4.
I use tailscale to run exit node and I need to put it on always on vpn.
But when I press always on vpn I get pop up window to select vpn but it doesn't show tailscale.
I have android 6.0 Marshmallow and root.

​

**Comment by DentonGentry** [comment]
The template asks for a bug report because it allows us to look at telemetry for the tailnet. This issue deleted the entire template, and there is nothing to act on.

Please file this as a support ticket instead, so we can followup about the account: https://tailscale.com/contact/support/
