### ISSUE TITLE
Unable to go install derpprobe

### ISSUE THREAD

**Issue by MikeBishop** [tailscale/tailscale#9422]
### What is the issue?

https://tailscale.com/kb/1118/custom-derp-servers/ points to `go install tailscale.com/cmd/derper@main` as the mechanism to install the binary for a DERP server, and `cmd/derpprobe` as the testing mechanism for DERP servers.

I tried a `go install tailscale.com/cmd/derpprobe@main` by parallel construction, but that fails with the following error:

```
go/pkg/mod/tailscale.com@v1.1.1-0.20230915141818-335a5aaf9a25/tailcfg/tailcfg_clone.go:9:2: package maps is not in GOROOT (/usr/lib/go-1.18/src/maps)
go/pkg/mod/tailscale.com@v1.1.1-0.20230915141818-335a5aaf9a25/types/views/views.go:13:2: package slices is not in GOROOT (/usr/lib/go-1.18/src/slices)
```

While I'm by no means a go expert, I can see that those source files import those modules without providing a path to them.  Does a path need to be updated so that these modules are findable by `go install`, or am I missing an install step?

### Steps to reproduce

`go install tailscale.com/cmd/derpprobe@main` on a clean install of go 1.18.1.

### OS

Linux

### OS version

Ubuntu 22.04

**Comment by creachadair** [comment]
It appears you may be attempting to build with an older Go toolchain (1.18). You'll want to update to version 1.21 to build these packages from source.

**Comment by MikeBishop** [comment]
Ah -- that appears to be it.  Silly me, assuming apt would be sufficiently up-to-date.....
