### ISSUE TITLE
Denying services in certain countries and regions

### ISSUE THREAD

**Issue by FarzanT** [tailscale/tailscale#9424]
### What is the issue?

As previously mentioned in issues #9158 and #9263, the Tailscale team has recently decided to limit access to certain countries and regions due to legal obligations. This does make sense but does not apply to all US-sanctioned countries equally. In particular, for Iran, I wanted to emphasize that restrictions on tools and software related to more open internet access were mostly lifted by executive order and by The Office of Foreign Assets Control on September 23, 2022, in Iran General License (GL) D-2, which specifically permits certain internet-based tools used for communications of different kinds, mainly to support the freedom of expression of the Iranian people. Obviously, this includes VPNs and related technology, and I quote: 
`
"GL D-2 continues to authorize anti-virus and anti-malware software; anti-tracking software; mobile operating systems and related software; anti-censorship tools and related software; Virtual Private Network (VPN) client software; and related software. These tools protect the ability of Iranians to engage in free expression and bravely resist regime oppression".
`
Even recently, the Biden administration voiced support on the anniversary of Mahsa Amini's death which sparked nationwide protests and internet shutdown in Iran. I find Tailscale's suspension of service so close to this anniversary somewhat strange, and urge the Tailscale team, in particular @DentonGentry, to reconsider their suspension of service in Iran.
For more information, you can check the following official links that summarize changes to GL D-2, which supersedes GL D-1:
1) https://home.treasury.gov/news/press-releases/jy0974
2) https://ofac.treasury.gov/faqs/1110#:~:text=On%20September%2023%2C%202022%2C%20OFAC,deployed%20by%20the%20Iranian%20government.
3) (PDF) https://ofac.treasury.gov/media/928096/download?inline

I hope this issue doesn't simply get locked like previous ones.

Thank you for your time!

**Comment by MiliAxe** [comment]
Agreed. As a student, I constantly need access to my home PC and I cannot easily do this with the limitations imposed.

**Comment by ignoramous** [comment]
> As a student, I constantly need access to my home PC and I cannot easily do this with the limitations imposed.

While WireGuard isn't censorship resistant (https://github.com/net4people/bbs/issues/88), it is still useful for *back-to-my-home* scenarios. There are quite few other FOSS alternatives to this, and the one that I know which is as simple to setup as Tailscale is: https://github.com/pojntfx/weron (though, it may not be as good as traversing NATs).

**Comment by DentonGentry** [comment]
Thank you for the heartfelt input. We are following the guidance from our legal counsel, which can evolve over time but which does take time. We will include the contents of this issue as an observation and input into that process.

For now the answer is the same as the last time: We are legally required to deny service to clients in certain countries and regions.

**Comment by catzkorn** [comment]
Hi,

We are going to close this because there is nothing actionable we can do in this issue tracker, which is engineering focused, but rest assured, the right people are aware of this issue.
