### ISSUE TITLE
FR: Support tailscale cert for docker container

### ISSUE THREAD

**Issue by ElectroTiger** [tailscale/tailscale#9425]
### What are you trying to do?

I have the following "sidecarI am trying to run tailscale in a docker container with the "--network host" option, rather than installing tailscale directly on my server (i.e. I have the sidecar container use case as described in https://tailscale.com/blog/kubecon-21/). I am doing this because I am using Google Cloud's "Container-Optimized OS", which is an immutable operating system that does not allow custom packages to be installed, but it does allow docker packages to run.

With the above configuration, I am successfully able to have tailscale up & running to connect me to any container instance running on the server. 

However, I notice that there is no option to use "tailscale cert" to set up HTTPS certificates, unlike a typical server install. 

### How should we solve this?

Support the equivalent of the "tailscale cert" command in the official docker image: https://hub.docker.com/r/tailscale/tailscale

### What is the impact of not solving this?

Tailscale as a sidecar container cannot terminate https connections for workloads that it proxies.

### Anything else?

I "sh"'d into the container to try to run "tailscale cert" manually. The command executed successfully, but chrome gives me a ERR_SSL_PROTOCOL_ERROR anyways.

**Comment by ElectroTiger** [comment]
Hi, I'm running my workload via Docker, not Kubernetes!

**Comment by maisem** [comment]
@ElectroTiger you need to set the TS_STATE_DIR env var so that the certs are stored somewhere retrievable.

**Comment by bradfitz** [comment]
> I "sh"'d into the container to try to run "tailscale cert" manually. The command executed successfully, but chrome gives me a ERR_SSL_PROTOCOL_ERROR anyways.

Did you do anything with the cert it produced? You have to then configure a webserver to use it.

I'm going to close this issue because I'm not sure what remains to do here. Feel free to reach out to Tailscale Support if you need further help, though.
