### ISSUE TITLE
Android: Mullvad Tunnels appear as regular nodes within the app UI 

### ISSUE THREAD

**Issue by insert-usernamehere** [tailscale/tailscale#9438]
### What is the issue?

Within the App ui under tagged nodes every mullvad tunnel appears as a valid node with an IP address to copy etc, I believe this isn’t expected behavior as the IOS and Linux clients do not experience this behavior.

### Steps to reproduce

1. Add Mullvad Addon to account
2. Authorize android node to use Mullvad
3. Open android app
4. Observe as every Mullvad tunnel appears as a node

### OS

Android

### OS version

Android 13 build TQ3A.230705.001

### Tailscale version

1.48.2

**Comment by catzkorn** [comment]
Hi,

Are you still able to reproduce this? Could you provide a screenshot if so?

Thanks!

**Comment by catzkorn** [comment]
Hi! Thanks - I have been able to reproduce this issue. I will chat with the team internally about this.

**Comment by catzkorn** [comment]
Hi!

I've rolled out a fix for this which you can use in our current unstable release (https://tailscale.com/kb/1083/install-unstable), and it will be included in our next stable android release.

Thanks again for the report!
