### ISSUE TITLE
Since 1.48.1 Mac TailScale does not work

### ISSUE THREAD

**Issue by brentcrammond** [tailscale/tailscale#9450]
### What is the issue?

It appears that tailscale for Mac does not work anymore since I upgraded to 1.48.1 and 1.48.2. 

I have another Mac with 1.46.1, which still works fine.

It appears correctly on the admin and the exit nodes appear on my configuration in the menubar, just it will not route traffic from the mac. Also Magic DNS still appears to be working.

### Steps to reproduce

Run 1.48.1 or 1.48.2 on Mac M1.

### Are there any recent changes that introduced the issue?

Upgrade to 1.48.1

### OS

macOS

### OS version

13.5.2 (22G91)

### Tailscale version

1.48.1 and 1.48.2

### Bug report

BUG-ce9c7ffb3e064910801dbf8c31837e34334f9d282fec051ff37179d201492563-20230918192655Z-bc477ab9509a5d70

**Comment by brentcrammond** [comment]
Also note I have uninstalled and reinstalled Tailscale on the Mac, to no avail.

**Comment by brentcrammond** [comment]
It appears my Linux servers are working as I have two linux server that seem to be communicating.  I also tested my Windows 11 machine and it is also working, so the problem appears to be solely tied to MacOS and iOS.

**Comment by raggi** [comment]
Thank you for sending the bugreport link. I was able to see in the logs that some connections are being rejected due to ACL configuration. If you need any assistance with the ACLs we can provide more specific information via support at https://tailscale.com/contact/support/

**Comment by brentcrammond** [comment]
Hi James

I have been using the same ACL for quite a few months.  I suspect the
rejection(s) was me trying to PING the servers incorrectly.

As mentioned the only devices not working are from my Mac and iOS the Linux
and Windows Servers are working correctly.

Kind Regards
---
Brent Crammond
*MBA, BSc(Comp. Sci.)*
email:     ***@***.*** ***@***.***>
*mobile:*   +64 21 228 5366



*“Live as if you were to die tomorrow. Learn as if you were to live
forever”* - *Gandhi*

**Comment by brentcrammond** [comment]
I think I have found the issue, it appears that the tailscale update has
removed the Tag from the machine.  I have corrected this and we are now
working.

Kind Regards
---
Brent Crammond
*MBA, BSc(Comp. Sci.)*
email:     ***@***.*** ***@***.***>
*mobile:*   +64 21 228 5366



*“Live as if you were to die tomorrow. Learn as if you were to live
forever”* - *Gandhi*
