### ISSUE TITLE
Unable to access certain sites on Chrome using Exit Nodes

### ISSUE THREAD

**Issue by Gowdham09** [tailscale/tailscale#9468]
### What is the issue?

I am using Tailscale's Exit Nodes my macOS device. 
While using the Exit Nodes I am unable to access certain websites. I am getting an ERR_CONNECTION_RESET error on Chrome. 

<img width="762" alt="Screenshot 2023-09-19 at 4 02 32 PM" src="https://github.com/tailscale/tailscale/assets/81134108/71a35672-6cf8-4d8f-a835-621213c3074b">

This error only occurs on Chrome and the same website can be accessed over Safari. Few others use Tailscale in our company and they do not seem to have this problem. It selectively occurs on certain devices is my suspicion. 

Bug report - BUG-6d2218208b897581dbf3fbb18f1df079c6904f36c5046d770be2e42a4199d3a4-20230919210540Z-903996c7ac93c724

### Steps to reproduce

I am not certain as this could be related to Tailscale-Chrome settings. 

### Are there any recent changes that introduced the issue?

This is my first time using Exit Nodes. 

### OS

macOS

### OS version

Ventura 13.5.2

### Tailscale version

Version 1.48.2 (macsys)

### Other software

Avast AV

### Bug report

BUG-6d2218208b897581dbf3fbb18f1df079c6904f36c5046d770be2e42a4199d3a4-20230919210540Z-903996c7ac93c724

**Comment by DentonGentry** [comment]
Around the time of the bugreport we notice IPv6 connections timing out.
```
2023-09-19 21:00:57.470791 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:64839 => [2607:q:r:s:t::53]:443) to node [+7/Uc]; online=yes, lastRecv=9s
2023-09-19 21:00:57.612709 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:64841 => [2607:q:r:s:t::5f]:443) to node [+7/Uc]; online=yes, lastRecv=9s
```

The destination IPv6 address ends in :0000:0000:0000:0053, which means these are almost certainly DNS-over-HTTPS connections to some DNS server. The full IPv6 address doesn't match a DNS service I am familiar with.

**Comment by DentonGentry** [comment]
> This error only occurs on Chrome and the same website can be accessed over Safari

So far as I can tell:
- Chrome is using its built in DNS resolver. The IPv6 DNS server address it is sending to reverse resolves to a *.1e100.net name, so it is a Google DNS server. I assume it is a non-publicized set of IP addresses which Chrome uses.
- Chrome is not falling back to try IPv4.

Can I ask what the exit node is, and in particular is it a Linux system with a TUN interface or is it something else?
https://tailscale.com/kb/1177/kernel-vs-userspace-routers/ means that an exit node running macOS/Windows/Android/etc is terminating the TCP connection on the tailnet and making a new outgoing TCP connection. This might be fooling Chrome into thinking that IPv6 works, when it only actually works to reach the exit node and fails on the public side of the exit node.

**Comment by Gowdham09** [comment]
Hi Denton,

I have created the exit node on an Ubuntu based instance which allows all
inbound and outbound traffic.

Thanks,
Gowtham.

**Comment by DentonGentry** [comment]
For the benefit of people finding this issue later:
- Linux with a /dev/net/tun device is able to do kernel forwarding.
- Linux with no TUN interface, as is often the case with containers, is started with `tailscale --tun=userspace-networking` and performs routing functions in userspace, so the limitations in https://tailscale.com/kb/1177/kernel-vs-userspace-routers/ apply.

----

We also have an internal support ticket, so I was able to look up the exit nodes. They are running Linux with a /dev/net/tun device, so they are doing packet routing.

We're still looking, but what we know so far is that Chrome is sending the DNS queries to an IPv6 address and it never falls back to IPv4. Usually it will fall back to IPv4 if IPv6 times out, so something is convincing Chrome to stick with IPv6.

**Comment by DentonGentry** [comment]
> While using the Exit Nodes I am unable to access certain websites.

Are you able to say any of the website which don't work? I can try them from here.

If you aren't able to say because of confidentiality that is fine, we'll keep looking for reasons.

If not comfortable posting publicly but the support ticket would be ok, please feel free to send a followup to the support ticket.

**Comment by Gowdham09** [comment]
I would appreciate a solution for this sooner because we want to migrate
all our users to Tailscale before 15th of october and this Exit Node issue
is very critical for us to get it resolved before that. I would be happy to
assist you in any way I can. Please keep me posted.

Thanks,
Gowtham.

**Comment by Gowdham09** [comment]
It is mostly the google sites (Gmail, Youtube, G Drive, etc) I have not
tried other sites but the ones that I can access are like AWS (this too
partly works and fails other times) I am unable to give out exact sites
because I do not know which ones are exactly failing. But Google sites are
failing continuously.

Thanks,
Gowtham.

**Comment by bradfitz** [comment]
Is it only happening on devices running Avast perhaps?

**Comment by DentonGentry** [comment]
I may have jumped to a conclusion that the ::53 address was DNS-over-HTTPS. There are a number of similar Google addresses timing out:
```
2023-09-19 21:03:15.932487 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:65064 => [2607:f8b0:4023:1004::8a]:443) to node [+7/Uc]; online=yes, lastRecv=4s
2023-09-19 21:03:16.752898 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:65066 => [2607:f8b0:4023:1002::63]:443) to node [+7/Uc]; online=yes, lastRecv=5s
2023-09-19 21:03:19.987667 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:65068 => [2607:f8b0:4023:1004::8a]:443) to node [+7/Uc]; online=yes, lastRecv=8s
2023-09-19 21:05:17.037366 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:65138 => [2607:f8b0:4004:c08::6a]:443) to node [+7/Uc]; online=yes, lastRecv=9s
2023-09-19 21:05:28.72771 +0000 UTC: open-conn-track: timeout opening (TCP [fd7a:115c:a1e0:ab12:q:r:s:t]:65160 => [2600:1901:0:47fc::]:443) to node [+7/Uc]; online=yes, lastRecv=10s
```

These may just be accesses to Google sites, always using IPv6. I would expect Chrome to fall back to IPv4, but it doesn't.

**Comment by DentonGentry** [comment]
> Is it only happening on devices running Avast perhaps?

That is possible, but I'd expect it to manifest differently than Chrome only using IPv6.

----

https://www.reddit.com/r/ipv6/comments/11c9j78/chromiumbased_browsers_preferring_ipv6_ula_with/ claims that Chrome with ULA addresses like `tailscale0` uses prefers IPv6. Honestly this is the opposite of what we've previously observed, where it seemed like Chrome preferred IPv4 if its only IPv6 address was ULA.

**Comment by DentonGentry** [comment]
I've tried to reproduce this by deliberately breaking IPv6 on the exit node, but so far have only been able to break the exit node altogether (had to reboot it to recover).

**Comment by DentonGentry** [comment]
I broke IPv6 on the exit node in a different way, using `ip addr del 2604:a880:q:r::s:t/64 dev eth0` to remove the public IPv6 address, and verified using https://test-ipv6.com/ that IPv6 was completely broken.

This doesn't reproduce the reported symptoms, Google sites are reachable without issue.

**Comment by DentonGentry** [comment]
@Gowdham09 are you comfortable running Wireshark to get a packet capture? This would be:
1. Activate the exit node
1. Run Wireshark, and start capture on the Tailscale interface (named utun#)
1. visit a google site
1. stop the capture
1. Mail it to support@tailscale.com, and mention bug 9468.

Thus far we have not reproduced this issue.

**Comment by Gowdham09** [comment]
I was able to break the IPv6 on the ExitNode but still no progress. The
error still persists.

[image: Screenshot 2023-09-27 at 9.06.28 AM.png]

Additionally, I have captured the packets as instructed using Wireshark. I
will send it to ***@***.***

Thanks,
Gowtham.

**Comment by DentonGentry** [comment]
Looking at the pcap file shows:
- There is some traffic being sent to the IPv4 addresses of Google properties. I don't immediately know if those packets were sent by Chrome or by something else. The flows to IPv4 addresses work and get responses.
- There are flows to the IPv6 addresses of Google properties, every one of which gets an ICMPv6 Destination Unreachable back from the Tailscale IPv6 address of the exit node.

Nonetheless, the pcap just shows more flows initiated to the Google IP6 address. Chrome doesn't give up and fallback to IPv4.

However this doesn't match what I see in pcaps when using the exit node where I removed its IPv6 address. I don't see Destination Unreachable ICMPv6 messages, just a timeout and Chrome gives up on IPv6.

**Comment by DentonGentry** [comment]
To confirm: the pcap was gathered from the Mac? Not from the exit node?

I don't see anything to the contrary but we're wondering about whether the Destination Unreachable is actually making it to Chrome, and whether that matters.

**Comment by Gowdham09** [comment]
You are right. The pcap was gathered from the Mac which is where I am using
Google Chrome.

**Comment by bradfitz** [comment]
(For Tailscale employees: http://go/issue9468-pcap)

**Comment by DentonGentry** [comment]
To me the mysteries are:
1. issue9468-pcap is sending back ICMPv6 Destination Unreachable packets, which I cannot reproduce. Disabling IPv6 on my exit node results in silent timeouts for IPv6 connections.
1. issue9468-pcap keeps trying IPv6 and never gives up. Mine tries IPv6 1-2 times and never again, it switches to IPv4.

**Comment by Valien** [comment]
Could this be a MacOS Sonoma issue or related? 

> Few users (for whom the Chrome browser was working using the Exit Node) who have updated their macOS to Sonoma 14.0 (23A344) are now having this issue of not being able to use the Chrome Browser. 

Safari seems to still be working fine though.

**Comment by jwhited** [comment]
> To me the mysteries are:
> 
>     1. issue9468-pcap is sending back ICMPv6 Destination Unreachable packets, which I cannot reproduce. Disabling IPv6 on my exit node results in silent timeouts for IPv6 connections.

IIUC you removed the IPv6 global unicast address, but the default route remained since there's probably a link local bound still. If you remove the IPv6 default route you should see the destination unreachable replies.

`ip -6 route ls`
`ip -6 route del default`

> 
>     2. issue9468-pcap keeps trying IPv6 and never gives up. Mine tries IPv6 1-2 times and never again, it switches to IPv4.

With IPv6 routing broken I can get destination unreachable responses, but chrome still falls back to IPv4. I haven't yet been unable to reproduce any Google sites failing to fallback. This is with 1.50.1 on Monterey and 1.50.1 on the exit node.

**Comment by jwhited** [comment]
> Could this be a MacOS Sonoma issue or related?
> 
> > Few users (for whom the Chrome browser was working using the Exit Node) who have updated their macOS to Sonoma 14.0 (23A344) are now having this issue of not being able to use the Chrome Browser.
> 
> Safari seems to still be working fine though.

What's the source of this comment? Is it related to this thread or a different issue?

**Comment by jwhited** [comment]
> You are right. The pcap was gathered from the Mac which is where I am using Google Chrome.

The `ERR_CONNECTION_RESET` error in Chrome is typically correlated with a TCP connection being reset by a TCP packet with the RST flag set. The packet capture on the Mac doesn't show any such TCP packet, and there's no QUIC/UDP packets in play either, besides DNS.

@Gowdham09 can you double check your Chrome network settings and confirm there's no proxy settings configured that could be interfering?

Can you confirm the packet capture was performed during a time you encountered `ERR_CONNECTION_RESET`?

**Comment by Gowdham09** [comment]
I can confirm that there are no proxy settings enabled and the packets were
captured while I encountered the ERR_CONNECTION_RESET using Exit Node.

I am adding the pcap file that I recently captured for your reference.

**Comment by jwhited** [comment]
> I can confirm that there are no proxy settings enabled and the packets were captured while I encountered the ERR_CONNECTION_RESET using Exit Node. I am adding the pcap file that I recently captured for your reference.

Thanks, can you attach the second pcap in reply to the support email?

There are reports of Avast causing ERR_CONNECTION_RESET w/Chrome. Can you try disabling Avast to see if the behavior changes?

**Comment by Gowdham09** [comment]
I already attached the second pcap file to the email but I am
attaching again FYR.

Avast has been disabled on my machine for a long time now.

**Comment by jwhited** [comment]
> I already attached the second pcap file to the email but I am attaching again FYR. Avast has been disabled on my machine for a long time now.

Thank you for confirming Avast is disabled. The pcap needs to be sent to support@tailscale.com in order for us to analyze it, with a reference to this GitHub issue.

**Comment by Gowdham09** [comment]
Got it. Just sent.

**Comment by jwhited** [comment]
The second pcap looks similar to the first in that we see IPv6 destination unreachable responses from the exit node. This is to be expected as it looks like the exit node does not have external IPv6 connectivity. What's more interesting about the second pcap is that there are DNS queries for Google properties, so we can infer what Chrome is trying to connect with. 

Chrome is querying for both IPv4 (A) and IPv6 (AAAA) records simultaneously, and there are valid, well-formed answers arriving for both within the same millisecond. For the domain where IPv6 is failing, Chrome is sometimes communicating via (IPv4) QUIC/UDP, or not at all post-DNS response. Due to the encrypted nature of QUIC we can't understand when a QUIC connection is "reset".

Working under the assumption that the IPv4 QUIC connections are being reset, and not falling back to IPv4 TCP, can you try disabling QUIC in Chrome and report back on if the issue persists? Navigate to chrome://flags/ and change `Experimental QUIC protocol` from Default/Enabled => Disabled. I wouldn't consider this a fix, but it tests my current theory.

**Comment by Gowdham09** [comment]
Interesting! I applied the changes and it almost worked for a while. Everything was working fine for 10 minutes and soon after I relaunched my browser the issue was back again. I checked if the flags were set to disabled still after the Chrome re launch and it was disabled. 

Not sure how it was working one min and failed after I re launched Chrome.

**Comment by jwhited** [comment]
Establishing IPv6 connectivity through the exit node resolved the issue. Chrome was preferring IPv6, and seemingly able to establish a TCP stream via 3-way, so it deemed IPv6 was healthy/functional. There was a proxy in play that appeared to handshake with Chrome before it had successfully opened a stream with the true destination. So, Chrome would see an open stream, then it would be closed shortly after, but it wouldn't fall back to IPv4.

Very similar to https://github.com/tailscale/tailscale/issues/5425#issuecomment-1232259971, except we were not the problematic proxy this time.
