### ISSUE TITLE
ipn/ipnlocal: cannot lookup self

### ISSUE THREAD

**Issue by dsnet** [tailscale/tailscale#9470]
If you try to access your own peerapi, it no longer works because [`LocalBackend.WhoIs`](https://github.com/tailscale/tailscale/blob/ed50f360dbc76ca2969694ee604d2385a776ef07/ipn/ipnlocal/local.go#L853C35-L853C35) can no longer find itself.

When it used to work:
```
$ curl http://100.109.51.95:43060
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>
<h1>Hello, Joe Tsai (100.109.51.95)</h1>
This is my Tailscale device. Your device is carbonite.
<p>You are the owner of this node.
```

When it stopped working:
```
curl: (56) Recv failure: Connection reset by peer
```

This is what it printed in journalctl:
```
peerapi: unknown peer 100.109.51.95:36058
```

This broke with https://github.com/tailscale/tailscale/commit/9538e9f97035ce7a382d2b395db3368bd0326113

\cc @bradfitz @maisem @rhealitycheck

**Comment by bradfitz** [comment]
Thanks for debugging & the fix! 😬
