### ISSUE TITLE
tailscale.deb does not print a note about how to start the service

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#95]
I ran:

```
sudo dpkg -i ./out/x86_64-linux/packages/tailscale.deb
```

...on Ubuntu. It installed everything, but did not print the systemd magic commands to install and start the service, as many other packages do. (You probably don't forget them as much as I do, the pointers are really helpful for me.)

**Comment by danderson** [comment]
You've actually identified a slightly different problem: on Debian based systems, the convention is to enable and start the service that's just been installed. The packaging I did doesn't do that, so I need to just fix that :)

**Comment by danderson** [comment]
The debian package now starts the service automatically, as is conventional on debian-based distros.
