### ISSUE TITLE
FR: Auth Key Role

### ISSUE THREAD

**Issue by DarrenWhiteley** [tailscale/tailscale#9501]
### What are you trying to do?

Allow certain people in the company to have access to the Auth key generation section of the settings.

At the same time full admins should have the ability to review and revoke all active Auth Keys.

### How should we solve this?

Create a new role for Auth Key generation only.

Create a section to view all active auth keys for admins

### What is the impact of not solving this?

It's not really a massive impact, however we use a lot of Auth keys and it would just cut down on certain types of tickets.

### Anything else?

Nothing else, but thank you for taking the time to read this.

**Comment by laurate** [comment]
Just want to add a +1 on this. 
Regarding impact: we are currently using auth keys to set up machines in our lab and if only one admin can review and revoke the keys there is some risk in case that person is not available. It would add some redundancy to our operations if we could share access to a specific auth key or all auth keys between admins.

**Comment by knyar** [comment]
I believe this is close enough to #6782 that I will close it as a duplicate.

As a workaround, if you need to delegate creation of auth keys for a particular tag, you can create an OAuth client with a "devices" [scope](https://tailscale.com/kb/1215/oauth-clients/#scopes) and assign that tag to it. This will allow that OAuth client to generate auth keys for that tag via the [API](https://github.com/tailscale/tailscale/blob/main/api.md#create-auth-key).

**Comment by torenzunza** [comment]
Hi Anton,

We would like an admin user to be able to revoke keys generated by any
other user, including admin role users.

The suggested workaround may address the first part of the request, but I
can't see how could it solve the second one.

Thanks for your time,

   Aitor

**Comment by knyar** [comment]
> We would like an admin user to be able to revoke keys generated by any other user, including admin role users.

Oh right, apologies for missing that. It might be better to create a separate issue per feature request.

I am curious what are you aiming to achieve by allowing admins to review and revoke other users' auth keys? Even if you revoke all auth keys from a user, they can still add new machines to the network by manually authorizing them.
