### ISSUE TITLE
BUG: Failed to write Mullvad configuration into ACL

### ISSUE THREAD

**Issue by asselinpaul** [tailscale/tailscale#9504]
### What is the issue?

Can't complete checkout for mullvad: "Failed to write Mullvad configuration into ACL."
<img width="1790" alt="Screenshot 2023-09-21 at 14 03 47" src="https://github.com/tailscale/tailscale/assets/868249/575256e0-cb0f-489c-bf8b-738ab87a45c5">

### OS

macOS

**Comment by raggi** [comment]
cc @twitchyliquid64

**Comment by br4yd** [comment]
Can confirm the same behavior when trying to add any of my devices. Regardless of the OS (Windows, Linux, MacOS)

**Comment by asselinpaul** [comment]
This is resolved for me!

**Comment by andrew-morris** [comment]
Sorry to be "that guy" but I'm having this issue as well. Anything I can do to troubleshoot?
