### ISSUE TITLE
admin panel: anticipate that XHRs cause network change events

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#951]
Admins are generally running Tailscale on the machine that they're using to access the Tailscale admin panel.

When they then tweak various settings, the changes are sent to their local machine instantly and the local machine's network stack reconfigures itself, causing some browsers/platforms to abort HTTP requests, including the one(s) that the Tailscale admin panel's web app are making.

A user says:

> - Each time I have added or removed an entry to the Search Paths or DNS Server sections in the admin console, I get a JS error but the operation succeeds (?):

<img width="1023" alt="Screen Shot 2020-11-18 at 9 34 55 PM (1)" src="https://user-images.githubusercontent.com/2621/99819408-4c021300-2b04-11eb-9ccf-cf1561b4579c.png">

We should make the admin panel frontend code particularly paranoid about this and not pop up network error dialogs when it's somewhat expected. And if the network change is so fast that it's interrupting the HTTP response of the request that caused the change, then we could either have the server delay the MapResponse to tailscaled, or ideally we could do a second XHR/Fetch/etc whenever we get an error to see if the first one actually worked. (assuming all the calls are idempotent)

/cc @rosszurowski @soniaappasamy

**Comment by rosszurowski** [comment]
Ah, yes. @apenwarr pointed this out in tailscale/corp#510. From testing on macOS, it seems only Chrome is affected by this network stack reconfiguration.

The solution we discussed was implementing an exponential request retry for POST requests across all API endpoints. Our XHR client, axios, should make this relatively simple [by using an interceptor](https://github.com/axios/axios/issues/164#issuecomment-166621106).

**Comment by rosszurowski** [comment]
This should now be fixed. As of today we now retry failed API requests up to three times with exponential back-off. That prevents this issue by retrying the request after the network stack has been rebuilt. We might have to play around with the timing if users are still seeing this, but the machinery we need is in.
