### ISSUE TITLE
2nd tailscale accout (identical setup?) MacOS dns no workie.  vistigal resolvers?

### ISSUE THREAD

**Issue by bhyde** [tailscale/tailscale#952]
**Describe the bug**
I'm attempting move a solo tailscale vpn from one domain
to another, as if from d.io -> d.net.  Why? Becaise I
can then be mores strick about who and how the <persona>@d2.net
emails are managed.

So I setup the d.net solo tailscale vpn. Sadly it doesn't work right.
I can ping things just fine, but the dns isn't working for me.

I the two dns configuration reported out by `scutil --dns` are
identical.  But they look weird, as if some thing about the resolvers
are removed when logging out?  Here's what scutil reports:

```
DNS configuration

resolver #1
  search domain[0] : d.com
  nameserver[0] : 172.33.66.13
  nameserver[1] : 172.33.66.12
  nameserver[2] : 172.33.66.11
  if_index : 17 (utun2)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101400

resolver #2
  nameserver[0] : 172.22.22.1
  nameserver[1] : 2002:d106:7acc:0:deef:9ff:fea8:39e
  if_index : 5 (en0)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000

resolver #3
  domain   : d.com
  nameserver[0] : 172.33.66.13
  nameserver[1] : 172.33.66.12
  nameserver[2] : 172.33.66.11
  if_index : 17 (utun2)
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)
  order    : 101401

resolver #4
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #5
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #6
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #7
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #8
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #9
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

resolver #10
  domain   : d.com
  nameserver[0] : 172.33.66.11
  nameserver[1] : 172.33.66.12
  nameserver[2] : 172.33.66.13
  flags    : Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)

resolver #11
  domain   : d.com
  nameserver[0] : 172.33.66.11
  nameserver[1] : 172.33.66.12
  nameserver[2] : 172.33.66.13
  flags    : Request A records, Request AAAA records
  reach    : 0x00000003 (Reachable,Transient Connection)

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 172.22.22.1
  nameserver[1] : 2002:d106:7acc:0:deef:9ff:fea8:39e
  if_index : 5 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  search domain[0] : d.com
  nameserver[0] : 172.33.66.13
  nameserver[1] : 172.33.66.12
  nameserver[2] : 172.33.66.11
  if_index : 17 (utun2)
  flags    : Scoped, Request A records
  reach    : 0x00000003 (Reachable,Transient Connection)
```

That seems like an abundance of reolvers for d.com, I
suspect some of those are vistigal?

Is tailscale leaving behind as the vistigal resolvers when configurations
change?  For example if you move from one tailscale account to anohter.

You may be curious about the order of the nameservers 172.33.66.1{1,2,3}.
For historical reasons we always configure these in this order 172.33.66.1{3,2,1}.
Hearsay is that long ago 172.33.66.1 had an outage.  It's fine now, thanks
for asking.

At his instant who both the d.io and d.net tailscale vpns are configured
in this order: 172.33.66.1{3,2,1}.

As i was working on this I tinkered withe the ordering, and so
I suspect that meerly reordering the order of the nameservers may
create vistgal resolvers.

Suggestions?  Absent any sage advice, I guess my next step is to logout of tailscale
and manually use scutil to remove all the resolvers using 172.33.66.*
nameservers.

**To Reproduce**
Create two solo vpn with a subnet containing nameservers.
Configure those, along with a search domain.  On MacOS
join that network; first with one account and then with the
other.  Note that one of them can't resolve names known
only to the internal nameservers.

**Expected behavior**
The two accounts name looks can both resolve internal
names.

**Version information:**
everything is uptodate, at least the admin page thinks so.
 - MacOS Catalina Tailscale App version: 1.2.4
 
**Additional context**
It's sunny and 55F in Boston this morning. Meanwhile episode 1 of "Because This Is My First Life" has a brief by excellent depiction of a software release at timestamp 44:10.

**Comment by apenwarr** [comment]
DNS was massively overhauled in v1.8 for macOS. Chances are excellent that this problem is gone now.
