### ISSUE TITLE
DERP server IPV4 STUN/UDP detection not work inside LXD even with public ips

### ISSUE THREAD

**Issue by alexl4321** [tailscale/tailscale#9525]
### What is the issue?

LXD 5.1.7
Tailscale 1.48.2
ubuntu 22.04 host
ubuntu 22.04 lxd container using bridged network

public ipv4 + ipv6 attached to bridge network
no firewalls on host, container or provider (tested with hetzner, ovh baremetal)

connectivity tested for both tcp as well as udp on both ipv4 + ipv6 (telnet, curl, netcat server client for udp) from outside tailscale clients - working perfectly

derp works fine if directly installed on host0

###

If the derp is being run inside the lxd container which has a public ipv4 + ipv6 attached to it (as well as set as the outgoing ip - no other containers, whatsoever on the bridge, no firewalls) other tailscale clients will not receive the IPV4 STUN requests back from the derp server - even though udp ipv4 works fine by testing with netcat server/client.

udp/stun on ipv6 will work fine.

it will still route traffic through the derp (probably using http/https backup since it also works from ipv4 only clients)

### OS

Linux

### OS version

ubuntu 22.04

### Tailscale version

1.48.2

### Other software

LXD 5.1.7

**Comment by bradfitz** [comment]
How is this a Tailscale issue? Sounds like you're asking for help configuring LXD networking?

**Comment by alexl4321** [comment]
networking is working. tailscale derp not. all ports are reachable, tcp, udp etc.  tested with telnet, curl, netcat for all protocols / ports.

**Comment by bradfitz** [comment]
derper is an extremely simple little program. It doesn't do any complicated networking. So if it's not working, I suspect you have an LXD/networking misconfiguration.

Unfortunately we don't have the resources to help everybody set up their custom DERPs, unless it's blocking a sales deal in which case a sales engineer can be assigned to assist. If that's the case, see https://tailscale.com/contact/sales/

Unless/until there's a concrete bug the engineers here can work on, I'm going to have to close this for now.
