### ISSUE TITLE
FR: Tailscale cannot ping itself

### ISSUE THREAD

**Issue by MilkTeaNo7** [tailscale/tailscale#9537]
### What are you trying to do?

# Fault phenomenon
1. I am unable to ping my Tailscale local address 100.64.0.1
2. Other Tailscale nodes are also unable to ping 100.64.0.1
3. ACL access policy restrictions have not been enabled
4. I am able to ping 100.64.0.1 through Tailscale and receive replies
5. Only direct ping commands do not work
6. Accessing services on other nodes through 100.64.0.1 works without any issues
7. Plain ICMP ping is the only thing that doesn't work, all other traffic through Tailscale proxy works fine

# Invalid operation has been attempted
1. The local Windows Firewall has been turned off
2. The problem persists after reinstalling the Windows operating system

### How should we solve this?

# Fault phenomenon
1. I am unable to ping my Tailscale local address 100.64.0.1
2. Other Tailscale nodes are also unable to ping 100.64.0.1
3. ACL access policy restrictions have not been enabled
4. I am able to ping 100.64.0.1 through Tailscale and receive replies
5. Only direct ping commands do not work
6. Accessing services on other nodes through 100.64.0.1 works without any issues
7. Plain ICMP ping is the only thing that doesn't work, all other traffic through Tailscale proxy works fine

# Invalid operation has been attempted
1. The local Windows Firewall has been turned off
2. The problem persists after reinstalling the Windows operating system

**Comment by DentonGentry** [comment]
```
C:\Users\dgentry>ipconfig

Windows IP Configuration


Unknown adapter Tailscale:

   Connection-specific DNS Suffix  . : tails-scales.ts.net
   IPv6 Address. . . . . . . . . . . : fd7a:115c:a1e0:ab12:4843:cd96:6248:df48
   Link-local IPv6 Address . . . . . : fe80::d8ff:5060:f230:9168%25
   IPv4 Address. . . . . . . . . . . : 100.72.223.72
   Subnet Mask . . . . . . . . . . . : 255.255.255.255
   Default Gateway . . . . . . . . . :


C:\Users\dgentry>ping 100.72.223.72

Pinging 100.72.223.72 with 32 bytes of data:
Reply from 100.72.223.72: bytes=32 time<1ms TTL=128
Reply from 100.72.223.72: bytes=32 time<1ms TTL=128

Ping statistics for 100.72.223.72:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

**Comment by DentonGentry** [comment]
The template asks for a bugreport because without it, we cannot look up information about the tailnet and we are unlikely to be able to help determine the root cause of the issue.

Since the IP address quoted is 100.64.0.1, I assume you are using Headscale?

**Comment by MilkTeaNo7** [comment]
`C:\Users\Administrator>ipconfig

Windows IP configuration


Unknown adapter Tailscale:

    Connection specific DNS suffix . . . . . . . : zq-admin.example.com
    Link-local IPv6 address. . . . . . . . : fe80::d8ff:5060:f230:9168%29
    IPv4 address . . . . . . . . . . . . . : 100.64.0.1
    Subnet mask . . . . . . . . . . . . . : 255.255.255.255
    Default gateway . . . . . . . . . . . . . . :

Wireless LAN Adapter Local Area Connection* 9:

    Media Status . . . . . . . . . . . . . : Media is disconnected
    Connection specific DNS suffix . . . . . . . :

Wireless LAN Adapter Local Area Connection* 10:

    Media Status . . . . . . . . . . . . . : Media is disconnected
    Connection specific DNS suffix . . . . . . . :

Ethernet Adapter VMware Network Adapter VMnet1:

    Connection specific DNS suffix . . . . . . . :
    Link-local IPv6 address. . . . . . . . : fe80::3f54:ac17:1f00:3db3%3
    IPv4 address . . . . . . . . . . . . . : 192.168.244.1
    Subnet mask . . . . . . . . . . . . . : 255.255.255.0
    Default gateway . . . . . . . . . . . . . . :

Ethernet Adapter VMware Network Adapter VMnet8:

    Connection specific DNS suffix . . . . . . . :
    Link-local IPv6 address. . . . . . . . : fe80::f5a:3be2:3469:fdd1%18
    IPv4 address . . . . . . . . . . . . . : 192.168.157.1
    Subnet mask . . . . . . . . . . . . . : 255.255.255.0
    Default gateway . . . . . . . . . . . . . . :

Wireless LAN adapter WLAN:

    Connection specific DNS suffix . . . . . . . :
    Link-local IPv6 address. . . . . . . . : fe80::aceb:737a:be7d:f41%17
    IPv4 address . . . . . . . . . . . . . : 192.168.10.123
    Subnet mask . . . . . . . . . . . . . : 255.255.255.0
    Default gateway . . . . . . . . . . . . . . . : 192.168.10.1

Ethernet adapter Bluetooth network connection:

    Media Status . . . . . . . . . . . . . : Media is disconnected
    Connection specific DNS suffix . . . . . . . :

C:\Users\Administrator>ping 100.64.0.1

Pinging 100.64.0.1 with 32 bytes of data:
Reply from 100.64.0.1: Bytes=32 Time<1ms TTL=128
Reply from 100.64.0.1: Bytes=32 Time<1ms TTL=128
Reply from 100.64.0.1: Bytes=32 Time<1ms TTL=128
Reply from 100.64.0.1: Bytes=32 Time<1ms TTL=128

Ping statistics for 100.64.0.1:
     Packets: Sent = 4, Received = 4, Lost = 0 (0% lost),
Estimated round trip time in milliseconds:
     Shortest = 0ms, Longest = 0ms, Average = 0ms`


Now I have reinstalled the client, and he can actually ping himself, but other nodes cannot ping.
I also don't know whether to use Headscale


Thank you for your help

**Comment by MilkTeaNo7** [comment]
`ubuntu@Jumpserver:~$ tailscale ping 100.64.0.1
pong from will (100.64.0.1) via 192.168.10.123:55824 in 2m`

**Comment by DentonGentry** [comment]
```
Connection specific DNS suffix . . . . . . . : zq-admin.example.com
```
With Tailscale this would be a name of the form tails-scales.ts.net. It would not be example.com.

```
IPv4 address . . . . . . . . . . . . . : 100.64.0.1
```
100.64.0.1 is not your Tailscale IP address.

We have to have something to go on:
- either attach a `tailscale bugreport`, or
- attach the **actual** Tailscale IP address, or
- contact support instead: https://tailscale.com/contact/support/

**Comment by DentonGentry** [comment]
You are using Headscale, and as demonstrated above we do not see the same symptoms when using the Tailscale control server.
