### ISSUE TITLE
sharing not enabled by admin

### ISSUE THREAD

**Issue by lineargraphics** [tailscale/tailscale#9538]
### What is the issue?

seeing this error when sending a file from windows to android tailscale "403 forbidden file sharing not enabled by admin" Any ideas?

### OS

Windows, Android

### OS version

win 10 android

### Tailscale version

1.50

**Comment by DentonGentry** [comment]
In https://login.tailscale.com/admin/settings/general
<img width="815" alt="Screenshot 2023-09-25 at 10 07 23 PM" src="https://github.com/tailscale/tailscale/assets/1140756/5d1912ae-ee89-406c-9846-d114b20c09c5">

**Comment by maisem** [comment]
This was an issue in the coordination server impacting clients 1.48.X and 1.49.X. This should be resolved now.
