### ISSUE TITLE
[macOS 1.50.0] Low contrast in dark mode 

### ISSUE THREAD

**Issue by gingerbeardman** [tailscale/tailscale#9543]
### What is the issue?

- The device selection screen is very low contrast in dark mode since 1.50.0 macOS

### Steps to reproduce

- Use Share sheet to send a file to Tailscale 

### Are there any recent changes that introduced the issue?

macOS 1.50.0

macOS 1.44.0 was much more readable.

### OS

macOS

### OS version

12.7

### Tailscale version

1.50.0

### Screenshots

![Screen shot 2023-09-26 at 20 43 09](https://github.com/tailscale/tailscale/assets/49612/b833eef3-7fb6-4199-ae2c-161d23bb2094)

![Screen shot 2023-09-26 at 20 43 01](https://github.com/tailscale/tailscale/assets/49612/1585b5a9-ba50-464f-8844-1a607a4de806)

**Comment by agottardo** [comment]
Fix identified, iOS is affected too.

**Comment by agottardo** [comment]
Fix will land in the next build. Thanks for reporting!
