### ISSUE TITLE
Subnet routing enabled results in network failures

### ISSUE THREAD

**Issue by shakeel** [tailscale/tailscale#955]
**Describe the bug**
I have a few machines on my home network with tailscale client installed. One of my machines on that network had subnet routes enabled. This machine was running Linux Ubuntu OS.

Starting some time last week, I noticed all of my other machines with tailscale client installed resulting in network failures, Chrome would give errors about firewalls and proxies setup on my machine. I first noticed it only on one of my Mac OS machines.

I disconnected Tailscale on that machine and my network connection was reestablished. I did not have to reboot or log out of Tailscale.

At this time my windows machines were not misbehaving. However after some time they started exhibiting the same behavior. 

**To Reproduce**
1. Enable Subnet Routes on a machine
2. Install Tailscale on other machines on the same network with subnet routes enabled.
3. Network connection fails on the other machines.
4. Disconnect in Tailscale client.
5. Network connection is reestablished.

**Expected behavior**
With subnet routes established, other machines in the same subnetwork should not result in network failures.

**Version information:**
 - Device: iMac, Windows Laptop, Linux Server
 - OS: Linux, Windows, MacOS
 - OS version: Windows 10, Ubuntu 18.04]
 - Tailscale version: Failures started around releases beginning around Friday November 13 2020. Current versions of Tailscale are Windows 1.2.8 macOS 1.2.4 Linux 1.2.8

**Additional context**
I did not upgrade one of my Windows machines, it is still at Windows 1.0.4 and it did not seem to be affected by this bug.

On one of my other Windows machines, on which I upgraded to Tailscale 1.2.8, it resulted in network failures. I had to disconnect tailscale for networking to work. I just noticed that on Tailscale Admin console, this machine appears twice, with the same name, but with different IP address and different versions of the OS. I need to open another bug report for it.

**Comment by apenwarr** [comment]
Major changes to subnet routing since tailscale v1.2. I'm guessing this is fixed already. If not, please reopen, and sorry for the slow response.
