### ISSUE TITLE
Windows Machine appears twice in admin console

### ISSUE THREAD

**Issue by shakeel** [tailscale/tailscale#956]
**Describe the bug**
One of my Windows 10 machine appears twice on the admin console. 

**To Reproduce**
1. Upgrade Tailscale on Windows 10 machine
2. The previous version of Tailscale was 1.0.4
3. The new version of Tailscale is 1.2.8
4. During the install, network connection has to be disrupted somehow, see my previous bug report about Subnet Routes.
5. Visit Tailscale admin console and you will see two machines reported.

**Expected behavior**
Upgrading Tailscale should result in only one machine appearing in the windows console.

**Screenshots**
![Screen Shot 2020-11-21 at 7 57 37 AM](https://user-images.githubusercontent.com/19921/99877876-43c2da00-2bcf-11eb-8b7b-b1cd4134b964.png)

**Version information:**
 - Device: [Windows Laptop]
 - OS: [Windows]
 - OS version: [Windows 10]
 - Tailscale version: [1.0.4 and 1.2.8]

**Additional context**
This problem is related to multiple machines on the same network with tailscale clients and one of the machines has subnetwork routes enabled.

**Comment by DentonGentry** [comment]
It looks like it generated a new key after update from 1.0.4 to 1.2.8

**Comment by bradfitz** [comment]
The transition from frontend-owned machine keys to service-owned machine keys was a bit complicated. Not surprised we might've had a bug back then. (in particular, this bug could've occurred on any multi-user Windows machine where two different users had used Tailscale: we'd end up picking one of their machine keys arbitrarily) 

But closing, as 1.0 is long gone, and we've been at service-owned machine keys for a while, so the worst of the transition is behind us.
