### ISSUE TITLE
[iOS 17.0.2] Tailscale 1.50.0 Unable to Connect to Network

### ISSUE THREAD

**Issue by john-jz** [tailscale/tailscale#9564]
### What is the issue?

There unfortunately appears to be a compatibility bug with Tailscale 1.50.0 and the latest iOS 17.0.2 update patch. Prior to updating the OS, I was able to connect to my Tailscale network, post iOS 17.0.2 update however, I receive the following error:

<img src="https://github.com/tailscale/tailscale/assets/9100635/dfe616ed-d0ba-4d4c-a891-18b323f2d045" width="25%" />

Unfortunately, the issue persists after performing a restart as instructed in the error message.

When I attempt to view the bug report, I am presented only with the following information:

<img src="https://github.com/tailscale/tailscale/assets/9100635/5a14c6e1-bb05-4511-96da-4b728f430b67" width="25%" />

Any guidance is welcome and appreciated, the versions are Tailscale 1.50.0 and iOS 17.0.2, as shown in the following screenshots:

<img src="https://github.com/tailscale/tailscale/assets/9100635/0577023a-8442-4bd7-9afe-63ec30563808" width="25%" />
<img src="https://github.com/tailscale/tailscale/assets/9100635/50b55dd8-8e60-4534-a326-4213f6418b8f" width="25%" />

### Steps to reproduce

Run Tailscale and try connecting to network after updating to iOS 17.0.2

### OS

iOS

### OS version

17.0.2

### Tailscale version

1.50.0

**Comment by agottardo** [comment]
There is nothing peculiar in 17.0.2 compared to 17.0.1 or 17.0 that would cause this. I have the same combo of app and iOS versions on my iPhone, and Tailscale works properly.

Have you tried removing the Tailscale VPN configuration, and then removing and reinstalling the app? If that's not enough, we are going to need a sysdiagnose from your device to investigate further.

**Comment by john-jz** [comment]
Hey @agottardo,

Thanks for helping out. I've just tried removing the Tailscale VPN profile, which didn't work, then removed the VPN profile and remove and reinstall the Tailscale app, which unfortunately didn't work either.

I noticed that when I reinstall the app, my account data automatically reloads on the Tailscale app, I'm wondering if clearing this data will help, I believe it's stored on iCloud, but can't seem to delete it with the option under device backup. Do we have any ideas on how to accomplish this?

**Comment by agottardo** [comment]
Oof. Can't suggest any other investigation steps without a sysdiagnose from the device unfortunately. You can email it to Andrea at Tailscale.com.

What you want to use for a full reset is the Reset Keychain toggle in the Settings app > Tailscale.

**Comment by john-jz** [comment]
This has since been resolved, many thanks for the amazing work being done!
