### ISSUE TITLE
tsnet: ListenFunnel does not work on 1.50.0

### ISSUE THREAD

**Issue by maisem** [tailscale/tailscale#9566]
### What is the issue?

when i do `go run ./tsnet/example/tsnet-funnel` I get an error that HTTPS is not enabled.

```
2023/09/27 23:03:12 Funnel not available; HTTPS must be enabled. See https://tailscale.com/s/https.
```

### Are there any recent changes that introduced the issue?

This was regressed by the introduction of `tailcfg.NodeCapMap` 

### Tailscale version

1.50.0

**Comment by DentonGentry** [comment]
This should be resolved in 1.50.1, released earlier today.
