### ISSUE TITLE
FR: Release Tailscale 1.50 for QNAP

### ISSUE THREAD

**Issue by niktheblak** [tailscale/tailscale#9568]
### What are you trying to do?

I use the QNAP version of Tailscale at my home NAS for my exit node. However, the version of Tailscale offered for QNAP is getting pretty old, 1.40.

### How should we solve this?

Create an updated release of the Tailscale package for QNAP and push it into the QNAP repository.

### What is the impact of not solving this?

I'm using a Raspberry Pi at home with a newer version of Tailscale to act as a backup exit node.

**Comment by d5aqoep** [comment]
1.48.2 is the latest signed version for QNAP. 
https://github.com/tailscale/tailscale-qpkg

1.50 is not available yet.

**Comment by DentonGentry** [comment]
We're not done with 1.50.0 release yet, there are two issues which need resolution before we proceed further.
I understand the desire to see the release, but having this issue open is not going to help with that.
