### ISSUE TITLE
How should I set it up so that it is set to direct connection in the OpenClash proxy configuration?

### ISSUE THREAD

**Issue by Goldenbeef** [tailscale/tailscale#9569]
### What is the issue?

At home, I use OpenWrt as a gateway and OpenClash to proxy the traffic. This resulted in my computer at home, after installing Tailscale, using the closest DERP server for proxying. So when I access devices at home from outside through Tailscale, there is significant latency. I want to know how Tailscale determines which DERP to choose and how should I set up the OpenClash rules to bypass Tailscale so that it doesn't use the proxy.

### Steps to reproduce

For example, when I turn off the OpenClash proxy, all my services will be directed to HongKong DERP and the access speed is very fast. However, once I open OpenClash, the devices at home will be directed to London instead, resulting in increased latency between devices.

### Are there any recent changes that introduced the issue?

no

### OS

Linux, macOS, Windows, iOS, Other

### OS version

Ubuntu22、ios17、win11、omv...

### Tailscale version

1.48.1

### Other software

no

### Bug report

BUG-3d657d75a634da06dacc7e17034faf1b10f2f1d8c69a1e74e2d77d36e4566053-20230928091950Z-c32ca3b933f9c88b

**Comment by DentonGentry** [comment]
> I want to know how Tailscale determines which DERP to choose

It chooses the region with the lowest round trip time.

```
$ tailscale netcheck
Report:
        * UDP: true
        * IPv4: yes, w.x.y.z:29941
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: true
        * HairPinning: false
        * PortMapping: UPnP, NAT-PMP, PCP
        * Nearest DERP: San Francisco
        * DERP latency:
                - sfo: 5.7ms   (San Francisco)
                - lax: 17.7ms  (Los Angeles)
                - sea: 23.2ms  (Seattle)
                - den: 30.3ms  (Denver)
                - dfw: 51ms    (Dallas)
                - tor: 65.8ms  (Toronto)
                - hnl: 65.8ms  (Honolulu)
                - ord: 67.2ms  (Chicago)
```

> how should I set up the OpenClash rules to bypass Tailscale so that it doesn't use the proxy.

We cannot help with configuration of other software on the system.
