### ISSUE TITLE
Tailscale docker container documentation for `TS_EXTRA_ARGS` not applying when `TS_AUTH_ONCE` is set (undocumented)

### ISSUE THREAD

**Issue by lgo** [tailscale/tailscale#9593]
### What is the issue?

The documentation for `TS_EXTRA_ARGS` states that it takes the same settings as `tailscale set`. While trying to add a new option on boot for a container, I found the settings were not being applied at all due to having `TS_AUTH_ONCE` set.

On the [Docker container page](https://hub.docker.com/r/tailscale/tailscale) the documentation states
> TS_EXTRA_ARGS: any other CLI flags for tailscale set

And on the [Tailscale documentation reference](https://tailscale.com/kb/1282/docker/#ts_extra_args) for the container image,  it says
> Any other flags to pass in to the [Tailscale CLI](https://tailscale.com/kb/1080/cli/) in a [tailscale set](https://tailscale.com/kb/1080/cli/#set) command.

On the contrary, the [code comments](https://github.com/tailscale/tailscale/blob/32c0156311fdef2fc068d4b04ba3733527e972ec/cmd/containerboot/main.go#L22C1-L23) indicate the arguments are actually fed into `tailscale login`. While the options appear to be the similar based on Tailscale's documentation, none of these locations actually note that `TS_EXTRA_ARGS` is actualy fed into `tailscale login` and that it is not run when `TS_AUTH_ONCE` is true.

It would be great to either document this nuance or actually run `tailscale set` to permit changed settings while `TS_AUTH_ONCE` is set.

**Comment by NLZ** [comment]
And since 1.50.1 `TS_AUTH_ONCE=true` by default
https://github.com/tailscale/tailscale/blob/v1.50.1/cmd/containerboot/main.go#L46

So I have to explicitly set TS_AUTH_ONCE to false if I want to use TS_EXTRA_ARGS to set --advertise-exit-node, and then set it back to true.

**Comment by MitchTalmadge** [comment]
Just ran into this on my first time using this container -- very confusing. Thank you for posting about this!

**Comment by lgo** [comment]
This is probably resolved by the reverts in #9814, which bring back the original behaviour.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/9814, which will be in 1.52.
