### ISSUE TITLE
The document of Docker Image is incorrect in the description of the 'TS_ROUTES' parameter!

### ISSUE THREAD

**Issue by OneLostCat** [tailscale/tailscale#9605]
### What is the issue?

Description of "TS_ROUTES" in https://hub.docker.com/r/tailscale/tailscale:

> "TS_ROUTES: Accept [subnet routes](https://tailscale.com/kb/1019/subnets/) that other nodes advertise. Linux devices default to not accepting routes."

In https://tailscale.com/kb/1282/docker/#ts_routes:

> "Accept [subnet routes](https://tailscale.com/kb/1019/subnets/) that other nodes advertise. Linux devices default to not accepting routes. This is equivalent to [tailscale set --accept-routes=](https://tailscale.com/kb/1080/cli/#set)."

Actrally, in code https://github.com/tailscale/tailscale/blob/ab810f1f6d6fcb57068738b2212ff101cc3ac1c5/cmd/containerboot/main.go#L551-L575

On line 562, it is obvious that "TS_ROUTES" is used to set "--advertise-routes", not "--accept-route"

This has caused me a lot of trouble. When I set 'TS_ROUTES' to true, I got an error in the log saying "'true' is not a valid IP address or CIDR prefix", and I don't know what I did wrong.

Hope to be corrected.

### OS

Linux

### OS version

Ubuntu Server 23

### Tailscale version

1.50.0

**Comment by Kianda** [comment]
I think this is why I'm getting "_Some peers are advertising routes but --accept-routes is false_" on the _health check_.
(Ubuntu 22.04 with Docker Tailscale 1.50.0)

**cfg.Routes should set also --accept-routes ?**

From this:
```
	if cfg.Routes != "" { 
 		args = append(args, "--advertise-routes="+cfg.Routes) 
 	} 
```

To this:
```
 	if cfg.Routes != "" { 
 		args = append(args, "--advertise-routes="+cfg.Routes, "--accept-routes") 
 	} 
```

**Comment by OneLostCat** [comment]
Because Outlook treated this email as spam, I apologize for taking so long to reply.

It's not like this.  Because the comment at the top of this code<https://github.com/tailscale/tailscale/blob/ab810f1f6d6fcb57068738b2212ff101cc3ac1c5/cmd/containerboot/main.go#L16C7-L16C46> is written:
TS_ROUTES: subnet routes to advertise.
that means there's no problem with the code.  The code works according to the designer's expectations.

The problem lies in the document. Just like this<https://hub.docker.com/r/tailscale/tailscale>
TS_ROUTES: Accept subnet routes that other nodes advertise. Linux devices default to not accepting routes.
The description of the code in the document is incorrect. This is an error made by the person who wrote this document. So I said it was a "document error". The code actually has no issues.

________________________________
发件人: Kianda ***@***.***>
发送时间: 2023年10月1日 3:13
收件人: tailscale/tailscale ***@***.***>
抄送: OneLostCat ***@***.***>; Author ***@***.***>
主题: Re: [tailscale/tailscale] The document of Docker Image is incorrect in the description of the 'TS_ROUTES' parameter! (Issue #9605)


I think this is why I'm getting "Some peers are advertising routes but --accept-routes is false" on the health check.
(Ubuntu 22.04 with Docker Tailscale 1.50.0)

cfg.Routes should set also --accept-routes ?

From this:

        if cfg.Routes != "" {
                args = append(args, "--advertise-routes="+cfg.Routes)
        }


To this:

        if cfg.Routes != "" {
                args = append(args, "--advertise-routes="+cfg.Routes, "--accept-routes")
        }


―

**Comment by clairew** [comment]
Thanks! Updated documentation.
