### ISSUE TITLE
Compose: getLocalBackend error: createEngine: tstun.New("tailscale0"): is a directory

### ISSUE THREAD

**Issue by 5olu7ion** [tailscale/tailscale#9608]
### What is the issue?

The Tailscale Container works perfectly fine when started via cmd:
`docker run --name=tailscaled -v /root/container/tailscale:/var/lib -v /dev/net/tun:/dev/net/tun --network=host --cap-add=NET_ADMIN --cap-add=NET_RAW --env TS_AUTHKEY=tskey-auth-blablablalbalbalba --env TS_ROUTES=192.168.4.0/24 --env TS_EXTRA_ARGS=--advertise-exit-node --env TS_STATE_DIR=/var/lib/tailscale --env TS_HOSTNAME=docker tailscale/tailscale`

But unfortunately it's not working, when started vi docker compose:
<code>tailscaled:
    container_name: tailscaled
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    volumes:
      - '/root/container/tailscale:/var/lib'
      - '/dev/net/tun:/dev/net/tun'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - TS_AUTHKEY=tskey-auth-blablablalbalbalba
      - TS_ROUTES=192.168.4.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_USERSPACE=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=docker
    network_mode: host
    image: tailscale/tailscale:latest
    restart: "unless-stopped"
    command:
      - tailscaled
</code>

This is the error:
<code>tailscaled  | 2023/09/30 20:44:18 logtail started
tailscaled  | 2023/09/30 20:44:18 Program starting: v1.50.0-ta30a7198b, Go 1.21.1: []string{"tailscaled"}
tailscaled  | 2023/09/30 20:44:18 LogID: 88ddd1863f067b2e3a37blablablabla3791c7e9ed6f4f7c07d7f0f
tailscaled  | 2023/09/30 20:44:18 logpolicy: using system state directory "/var/lib/tailscale"
tailscaled  | 2023/09/30 20:44:18 wgengine.NewUserspaceEngine(tun "tailscale0") ...
tailscaled  | 2023/09/30 20:44:18 Linux kernel version: 6.1.55-0-virt
tailscaled  | 2023/09/30 20:44:18 'modprobe tun' successful
tailscaled  | 2023/09/30 20:44:18 /dev/net/tun: drw-rw-rw-
tailscaled  | 2023/09/30 20:44:18 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): is a directory
tailscaled  | 2023/09/30 20:44:18 flushing log.
tailscaled  | 2023/09/30 20:44:18 logger closing down
tailscaled  | 2023/09/30 20:44:18 getLocalBackend error: createEngine: tstun.New("tailscale0"): is a directory
</code>

I suspect that it has something to do with privileges, and so I tried playing around with the privileged, cap_add, user (0:0) and TS_USERSPACE flags. None of it was successful. I also had no Luck with searching for the "is a directory" error. 

### Steps to reproduce

Start the compose snippet.

### OS

Linux

### OS version

Alpine

### Tailscale version

1.50.0

**Comment by bradfitz** [comment]
Maybe compose doesn't like mapping single files. Try just /dev/net:/dev/net?

**Comment by guest42069** [comment]
on docker-compose.yml you've added a command, which isn't reflected in the command line `docker run ...` equivalent.
```yaml
command:
- tailscaled
```

one way to reproduce this error message, is it to have a host system not already have the `tun` module loaded or no device file created, so when the docker container is started it will create a folder at /dev/net/tun because it doesn't already exist, and then mount it inside the container, which will already exist when tailscale later loads the module.

```
$ docker run ... -v /dev/net/nottun:/dev/net/tun ...
...
2023/10/01 12:57:47 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): is a directory
...
$ stat /dev/net/nottun
...
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
```

You could also consider using `--device` to pass device files in to containers, if /dev/net/tun didn't exist or weren't a device file, you'd get a relevant error message when trying to instantiate the container.

```
$ docker run ... --device /dev/net/nottun ...
docker: Error response from daemon: error gathering device information while adding custom device "/dev/net/nottun": not a device node.
```

or via docker-compose

```yml
devices:
  - "/dev/net/tun"
```

**Comment by 5olu7ion** [comment]
> on docker-compose.yml you've added a command, which isn't reflected in the command line `docker run ...` equivalent.
> 
> ```yaml
> command:
> - tailscaled
> ```
> 
> one way to reproduce this error message, is it to have a host system not already have the `tun` module loaded or no device file created, so when the docker container is started it will create a folder at /dev/net/tun because it doesn't already exist, and then mount it inside the container, which will already exist when tailscale later loads the module.
> 
> ```
> $ docker run ... -v /dev/net/nottun:/dev/net/tun ...
> ...
> 2023/10/01 12:57:47 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): is a directory
> ...
> $ stat /dev/net/nottun
> ...
> Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
> ```
> 
> You could also consider using `--device` to pass device files in to containers, if /dev/net/tun didn't exist or weren't a device file, you'd get a relevant error message when trying to instantiate the container.
> 
> ```
> $ docker run ... --device /dev/net/nottun ...
> docker: Error response from daemon: error gathering device information while adding custom device "/dev/net/nottun": not a device node.
> ```
> 
> or via docker-compose
> 
> ```yaml
> devices:
>   - "/dev/net/tun"
> ```

Wow, I didn't realized this. Thank you very much, your analysis is absolutely correct, and it works perfectly after removing the `command` . Here is my final compose yaml:

```tailscaled:
    container_name: tailscaled
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/root/container/tailscale:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - TS_AUTHKEY=tskey-auth-kuXGVB3blablablabla4vGnoBL6kFi
      - TS_ROUTES=192.168.4.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=docker
    network_mode: host
    image: tailscale/tailscale:latest
    restart: unless-stopped
