### ISSUE TITLE
after recent update i can't connect

### ISSUE THREAD

**Issue by lutfor-diu** [tailscale/tailscale#9613]
After recent update in Linux dietic, i can't connect to my dietpi or adguard or another server that running on dietpi. 
i can't connect from my wifi nor from tailscale vpn from android phone. 

previously everything was running smooth and working.

**Comment by DentonGentry** [comment]
There is no information here which would let us identify the tailnet or diagnose it. Please send this as a support ticket instead, the support team can look up your information and try to help.
https://tailscale.com/contact/support/
