### ISSUE TITLE
500s from `/api/v2/device/{deviceId}`

### ISSUE THREAD

**Issue by matthewgrossman** [tailscale/tailscale#9618]
### What is the issue?

I receive a 500 when hitting either the `GET` or `DELETE` methods of `/api/v2/device/{deviceId}` ([apidocs](https://github.com/tailscale/tailscale/blob/main/api.md#get-device))

I'm not sure if this is something particular to my account or a wider-spread outage with this API. Without the ability to validate with another account, I'm pessimistically assuming the latter and raising here first. However, if this ends up being something strange with my account in particular, I'll be sure to move the conversation to a support ticket (where we can discuss tailnets/deviceIds/etc).

https://status.tailscale.com/ at time of posting isn't showing any issues either

### Steps to reproduce

```
» curl -H "Authorization: Bearer tskey-api-xx" "https://api.tailscale.com/api/v2/device/YOURDEVICEHERE"
{"message":"internal server error"}%                                                                                                                                                                    
```

A more concrete example:
```bash

# validate this device exists, and show that `/tailnet/` APIs  *do* work
» curl -s -H "Authorization: Bearer tskey-api-REDACTED" "https://api.tailscale.com/api/v2/tailnet/-/devices" | jq '.devices[7].hostname'
"vps"

» curl -H "Authorization: Bearer tskey-api-REDACTED" "https://api.tailscale.com/api/v2/device/vps"                                      
{"message":"internal server error"}%                                                                                                                                                                    
```

### OS

macOS

### OS version

macOS 13.5.2 (22G91)

### Tailscale version

1.50.0

**Comment by DentonGentry** [comment]
The shape of the metrics about API responses looks the same right now as it always does. I see no sign of a widespread problem, there are no alerts, and we are not currently aware of any problem.

I cannot pursue it further with information in this bug, without a way to identify the tailnet where this is occurring. I would suggest filing a support request at https://tailscale.com/contact/support/.

**Comment by matthewgrossman** [comment]
Thanks for the prompt response, I just followed up by creating a "Other - sev3" support ticket
