### ISSUE TITLE
connectivity broken after upgrade to MacOS Sonoma

### ISSUE THREAD

**Issue by rocketdv** [tailscale/tailscale#9620]
### What is the issue?

I just updated to Sonoma and tailscale isn't working at all. The menu items don't seem to have any action when I click. When running `debug ts2021` it fails and says connections were reset by peer.

### Steps to reproduce

Update to MacOS Sonoma, and try using tailscale

### Are there any recent changes that introduced the issue?

MacOS Update

### OS

macOS

### OS version

macOS Sonoma 14.0

### Tailscale version

1.50

**Comment by rocketdv** [comment]
Manually building and running `tailscaled`, and using the `tailscale` CLI tool works as a temporary fix

**Comment by bradfitz** [comment]
Running any of the things listed at https://tailscale.com/kb/1023/troubleshooting/#interoperability-with-other-software or similar?

**Comment by bradfitz** [comment]
Per our stats, more Tailscale macOS users are running Sonoma than any other macOS version, by far. (Tailscale users are especially nerdy+security-conscious and upgrade to new OS releases quickly). So this isn't a Sonoma-wide issue at least. Something particular about your machine configuration is likely involved. Hence the question about other software running on the machine.

**Comment by rocketdv** [comment]
Doesn't look like any of those are running. Also, not sure that's the issue, because when I manually build and run locally, everything is fine (for the most part):

**Comment by rocketdv** [comment]
Restart seems to have fixed it all!
