### ISSUE TITLE
State is lost (again) in tailscale docker container TS v1.50

### ISSUE THREAD

**Issue by MekayelAnik** [tailscale/tailscale#9623]
### What is the issue?

The state is lost on every restart. Thus have to re-authenticate every time. This has been introduced again on v1.50
Downgraded to using v1.48...Voilà, the Problem is gone. 
Please solve.
Love TS
Keep up the good work. TY

### Steps to reproduce

Recreate the container with v1.50 or "latest" tag

### Are there any recent changes that introduced the issue?

Yes, v1.50 introduced the problem in docker. The problem is no present in TS v1.48

### OS

Linux

### OS version

Debian 12 (dietpi) on Raspberry Pi4B

### Tailscale version

1.50

### Other software

Docker version 24.0.6, build ed223bc

**Comment by DentonGentry** [comment]
This should be fixed by https://github.com/tailscale/tailscale/commit/d9e8f6b59294a79b3419a45c227eda61ff51e86d, which was incorporated into the Tailscale 1.50.1 release earlier today.
