### ISSUE TITLE
Support systemd custom statuses

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#964]
A user's key expired and they checked `systemctl status tailscaled` and didn't see anything amiss.

They requested that we include high-level status messages in `systemctl status`.

See:
* https://www.freedesktop.org/software/systemd/man/systemd-notify.html
* https://unix.stackexchange.com/questions/212059/systemd-custom-status-message/396645

etc

/cc @danderson

**Comment by bradfitz** [comment]
And of course @mdlayher wrote https://godoc.org/github.com/mdlayher/sdnotify

**Comment by mdlayher** [comment]
Yep, it works like a charm and degrades gracefully when not running under systemd/the appropriate unit type. Enjoy!

**Comment by mselh** [comment]
Is there any further work to do? Seems done.
