### ISSUE TITLE
Severe battery usage

### ISSUE THREAD

**Issue by Grem135** [tailscale/tailscale#9642]
### What is the issue?

The only other reports I found were from 2021 or IOS so I decided it I should post here.  I'm new to Github so if I am wrong let me know,  
Adroid Oneplus 9 Pro running android 13 using tailscale to stream from autobookshelf container on my Synology NAS.
Audiobookshelf app used 3% but tailscale used 25% of battery useage last charge.  This is more than the next 5 Apps combined.
Is there something I need to do or is it an App issue.  
This is the first time I have used Tailscale and love how it works for Audiobookshelf when away from home.

Thanks.

### Steps to reproduce

Just being Active.

### Are there any recent changes that introduced the issue?

Noticed it on previous phone but only used maybe a day before getting the oneplus 9 pro.
New setup on 9 pro and noticed high battery drain.  I am not a gamer or extreme phone user.

### OS

Android

### OS version

Android Version 13

### Tailscale version

1.48.2

### Other software

No security or networking apps.  Audiobookshelf to stream books.  

### Bug report

BUG-381968b53ec27467b5dd5ba933be2537d470ae94dfa0478c5815a22afe7d870d-20231003221417Z-376586caba3decc0

**Comment by bradfitz** [comment]
We're aware of the issues and working on them.

Closing this as a dup of #3363.
