### ISSUE TITLE
Public Tailscale API

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#965]
We're working on an API.

This is a tracking bug for updates & subscribing to updates.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2i4lt)

**Comment by kavirajk** [comment]
+1 for public API

my basic use-case is connect to devices via local network if inside the network or via Tailscale if outside via some sort of script.

**Comment by maxwellb** [comment]
Posting an observation about the API. I see that this is a tracking bug.

The API is not respecting quality factors in the Accept header. The following request returned HUJSON, for example.

```http
### Get Tailnet ACL
GET /api/v2/tailnet/{{tailnet}}/acl
Accept: application/hujson;q=0.2, application/json, text/plain
Authorization: {{TS_AUTH}}
```

**Comment by bradfitz** [comment]
@maxwellb, good find! Could you open a new bug to track that specifically? We can then link it from here.

For that bug, you can note https://github.com/golang/go/issues/19307 which links to a number of implementations. I haven't evaluated which is best yet.

**Comment by maxwellb** [comment]
Opening new bug...

**Comment by DentonGentry** [comment]
I don't believe this bug is tracking anything further, we're likely to open a new bug for major extensions to the API.
