### ISSUE TITLE
1.50.0 macsys no longer checks for update when selecting “About Tailscale”

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#9651]
### What is the issue?

With versions of macsys < 1.50.0, selecting “About Tailscale” was enough to trigger an update notification. You could pick it remotely, and click to apply the update, and it would restart Tailscale with the new version.

With 1.50.0, that doesn’t happen. If I quit and restart Tailscale, it seems to have applied the update, but that’s not something I can do over a Tailscale connection.

This means I have to update Tailscale by being physically at the machine which is a regression.

### Steps to reproduce

Select “About Tailscale”.

### Are there any recent changes that introduced the issue?

Dunno, started with 1.50.0 macsys.

### OS

macOS

### Tailscale version

13.5.2 (22G91)

**Comment by bradfitz** [comment]
cc @awly @noncombatant @agottardo

**Comment by avidrissman** [comment]
Hm. On my personal laptop it did appear, but with my personal desktop and work laptop it didn’t.

**Comment by agottardo** [comment]
We are releasing a fix for this in the next app update. For now, you can use `tailscale update` in the CLI.
