### ISSUE TITLE
Failed to connect to Tailscale service (503 Service Unavailable: no backend)

### ISSUE THREAD

**Issue by skurbanmagomedov** [tailscale/tailscale#9653]
### What is the issue?

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.
Version 1.50.1 (tf45c02bfc-g36a20760a)
LogID: d7e62a7debc903efc0738f1b57aa9de5af0d3478830217023543db8710ba2513
(Ctrl-C to copy this text)
---------------------------
ОК
---------------------------

### Steps to reproduce

1) download the new version package.
2) install Tailscale.
3) icon is gray for about 30s.
4) error pops up.

After reinstalling TS and rebooting the computer, the error is still active.

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.40.0, 1.50.1

**Comment by bradfitz** [comment]
cc @dblohm7

**Comment by skurbanmagomedov** [comment]
Is there anything on this issue?

**Comment by DentonGentry** [comment]
Amongst the last bits of telemetry seen from this machine:
`2023-10-04 11:35:02.4933831 +0000 UTC: ui: Failed to explicitly start tailscaled: openServiceForReadExecute: Access is denied.`

Was the upgrade or reinstall done from a different user? Is the MSI being set to install to a location other than the default?
Something has gone wrong in the permissions for `tailscaled.exe`

**Comment by skurbanmagomedov** [comment]
Thanks for the update.
I'll check it locally on user's PC.

**Comment by DentonGentry** [comment]
Because it concerns what appears to be a single device, it would be best to handle this as a support ticket, rather than a bug: https://tailscale.com/contact/support/

There is a team who can look up details of the account and help resolve it.
