### ISSUE TITLE
FR: Unable to open login interface when installing Tailscale

### ISSUE THREAD

**Issue by cfcce** [tailscale/tailscale#9654]
### What are you trying to do?

Warning: client version "1.50.1-tf45c02bfc-g36a20760a" != tailscaled server version "1.28.0-taabca3a4c"
404 Not Found

Linux Ubuntu 20.04.5 LTS    
Attempting to restart has no effect
Reinstallation is also invalid

**Comment by bradfitz** [comment]
You didn't even say which OS you're using. Linux? Windows? Did it used to work prior to this upgrade? I assume you upgraded from that error message.

Have you tried rebooting?

**Comment by cfcce** [comment]
Linux Ubuntu 20.04.5 LTS    
Attempting to restart has no effect
Reinstallation is also invalid

> 你甚至没有说你正在使用哪个操作系统。Linux？窗户？在此升级之前，它是否曾经工作过？我假设您从该错误消息升级。
> 
> 您是否尝试过重新启动？

**Comment by cfcce** [comment]
> You didn't even say which OS you're using. Linux? Windows? Did it used to work prior to this upgrade? I assume you upgraded from that error message.
> 
> Have you tried rebooting?
Linux Ubuntu 20.04.5 LTS
Attempting to restart has no effect
Reinstallation is also invalid

**Comment by bradfitz** [comment]
If rebooting didn't help then you almost certainly have two different versions of Tailscale installed at the same time in different locations and conflicting.

I'd recommend removing them both, verify tailscaled is no longer running, then reinstalling.
