### ISSUE TITLE
Tailscale infinitely loads on MacOS Sonoma

### ISSUE THREAD

**Issue by sloraris** [tailscale/tailscale#9658]
### What is the issue?

Tailscale presents as "loading" after updating to Sonoma. Expected behavior: load, then connect.

### Steps to reproduce

Upgraded to MacOS Sonoma. Every few reboots tailscale will successfully connect, but quitting and reopening the service does not reproduce this. If it fails on startup, it will continuously fail.

### Are there any recent changes that introduced the issue?

Upgraded to MacOS Sonoma.

### Other software

N/A

**Comment by sloraris** [comment]
Sorry about that, it appears it may have been a fluke, getting it to work. I haven't been able to reproduce that and gain access to the bugreport menu. This is on the App Store version, I've reinstalled it and attempted logging out/revoking the device from the admin console but that doesn't seem to be affecting it.

I'm happy to try out the CLI and Downloadable versions as well.

**Comment by DeepakTivari** [comment]
Infinitely loads for me too, Sonoma

**Comment by sloraris** [comment]
I've uninstalled, removed ALL related files, rebooted, and reinstalled. Now clicking login does nothing.

Downloadable version got stuck on "setting up VPN" and never opened the login page, now it is also stuck on loading.

**Comment by jstr** [comment]
Having the very similar problem here. Going throught the full uninstall instructions then reinstalling does not help. On a fresh install the 'Sign in to your network' / 'Log in' buttons do nothing, and after a reboot Tailscale is stuck on 'Loading...'. 

In Console.app I have a bunch of entries like this

```
default	11:28:51.938023+1300	io.tailscale.ipn.macsys.network-extension	control: recursive: querying IPv4 addresses for: "controlplane.tailscale.com"
default	11:28:51.940570+1300	io.tailscale.ipn.macsys.network-extension	Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=74": failed to resolve "controlplane.tailscale.com": no DNS fallback candidates remain for "controlplane.tailscale.com"
default	11:28:51.961839+1300	io.tailscale.ipn.macsys.network-extension	control: recursive: querying IPv6 addresses for: "controlplane.tailscale.com"
default	11:28:51.962328+1300	io.tailscale.ipn.macsys.network-extension	control: recursive: error using recursive resolver: no responses to query
default	11:28:52.308732+1300	io.tailscale.ipn.macsys.network-extension	control: recursive: querying IPv6 addresses for: "controlplane.tailscale.com"
default	11:28:53.548058+1300	io.tailscale.ipn.macsys.network-extension	control: LoginInteractive -> regen=true
default	11:28:53.548460+1300	io.tailscale.ipn.macsys.network-extension	control: doLogin(regen=true, hasUrl=false)
```

This is the package from https://pkgs.tailscale.com/stable/Tailscale-1.50.1-macos.zip. App Store has the same symptoms.

**Comment by jstr** [comment]
Just FYI - these issues make Tailscale impossible for me to install and use on my Mac running MacOS Sonoma 14.0. Neither installing directly from the latest package or via the App Store yields a functional install. To the best of my knowledge this is a new issue in Sonoma. Prior to upgrading MacOS I had installed and used Tailscale with no issue.

**Comment by bradfitz** [comment]
Any other networking software on your machine that might be conflicting? See the list at https://github.com/tailscale/tailscale/wiki/OtherSoftwareInterop to jog your memory for those or similar.

**Comment by sloraris** [comment]
I didn't have anything else running at the time. Previously I had private relay and screen time both on, but after the update they were disabled and I manually made sure of that while testing. As stated above by others, the app store version and manually installed package are both non-functioning at the application level -- login isn't available, nor is the debug menu. I've moved to twingate in the meantime.

**Comment by jstr** [comment]
> Any other networking software on your machine that might be conflicting? See the list at https://github.com/tailscale/tailscale/wiki/OtherSoftwareInterop to jog your memory for those or similar.

I have been running Cloudflare Warp, however I uninstalled that prior to testing because I wanted to rule it out as a problem. 

My uninstall method was dragging Cloudflare warp into the recycle bin. However, I just note that their uninstall instructions include running a script from inside their installation. Running this has fixed the problem.

So, I guess Cloudflare is leaving some junk behind that this causing interop issues when uninstalled the macos-intuitive way.

**Comment by DentonGentry** [comment]
@sloraris Did you also have CloudFlare Warp installed at one time?

**Comment by sloraris** [comment]
> @sloraris Did you also have CloudFlare Warp installed at one time? 

I have not. I had OpenVPN installed at one point, but that was removed long ago and tailscale is what replaced it. Never had any issues until updating to Sonoma.

**Comment by travischambers** [comment]
I am seeing this issue as well after upgrading to Sonoma this morning.

here's my output when i run `tailscale debug ts2021`:

```
➜  ~ tailscale debug ts2021
09:58:09.992435 Fetching keys from https://controlplane.tailscale.com/key?v=74 ...
09:58:10.925149 Dial("tcp", "[2a05:d014:386:202:f041:44b6:9559:668]:80") ...
09:58:10.928588 Dial("tcp", "[2a05:d014:386:202:f041:44b6:9559:668]:80") = [::1]:50010 / [::1]:10011
09:58:10.932296 Dial("tcp", "[2a05:d014:386:202:f041:44b6:9559:668]:443") ...
09:58:10.932925 Dial("tcp", "[2a05:d014:386:202:f041:44b6:9559:668]:443") = [::1]:50012 / [::1]:10011
09:58:10.933774 controlhttp.Dial = 0x0, all connection attempts failed (HTTP: read tcp [::1]:50010->[::1]:10011: read: connection reset by peer, HTTPS: read tcp [::1]:50012->[::1]:10011: read: connection reset by peer)
09:58:10.933816 all connection attempts failed (HTTP: read tcp [::1]:50010->[::1]:10011: read: connection reset by peer, HTTPS: read tcp [::1]:50012->[::1]:10011: read: connection reset by peer)
```

A coworker, who can still successfully connect, runs this and sees the same failure with ipv6, but then his switches to ipv4 and successfully connects afterward.

**Comment by bradfitz** [comment]
Something about your machines are different than most the userbase (which statistically is fine). We need to figure out what that difference is so we can repro and investigate how to work around the issue.

Usually it's other networking software you forgot you installed or enabled or thought you disabled but it actually is still running/grubbing around in OS config.

Apple Private Relay? Other DNS tools? Other VPNs?

We want to help work around so please let us know everything that might've altered your machine in the past.

**Comment by sloraris** [comment]
@bradfitz Here's an exhaustive list of all the networking stuff I've had on my machine, in order:
- Private relay
- OpenVPN
- Tailscale
- Docker desktop
- Twingate (this is what has replaced tailscale, was not installed prior to this issue)

Here's the list of troubleshooting steps I've followed up to this point:
- Rebooted
- Uninstalled, reinstalled, and rebooted (this means clearing out all VPN configs, all hidden application files related to all VPN applications including tailscale, and actually uninstalling instead of just moving the app to the trash)
- Installed from package download instead of App Store

Tailscale isn't infinitely loading anymore, it's just not launching the login page so no VPN profile is ever installed. It's behaving as if it has no internet access, though I'm at a loss as to what would be preventing that. Once again, all the previous applications have been disabled and/or removed entirely for this testing. Private relay is disabled. Any additional troubleshooting advice is welcome.

**Comment by travischambers** [comment]
I don't have any other networking software on my machine. I _do_ have Docker desktop installed, but it's not running and hasn't run in ages.

I did find a solution, though!

I explicitly added a DNS server to my wifi network. I used 8.8.8.8, though I assume any of the public ones would work (e.g. 1.1.1.1 for cloudflare, 8.8.8.8 for google).

![image](https://github.com/tailscale/tailscale/assets/2482630/7c490634-57a6-413c-9da9-9ef06dc084d9)

**Comment by wongjustin99** [comment]
Seeing the same console logs as @travischambers 

I also don't have anything odd with my network -- no other VPNs installed or running. No little snitch.

**Comment by selimsandal** [comment]
Similar problem here, when Cloudflare WARP is running Tailscale does not connect, when Tailscale is running Cloudflare WARP DNS lookup fails and cannot connect. MacOS Sonoma, Tailscale App Store latest

**Comment by selimsandal** [comment]
Turning off use tailscale DNS settings in the tailscale menu bar fixes the problem.

**Comment by BernardMC** [comment]
I have same issue, started right after I upgraded to Sonoma
On reboot it will connect, but Chrome then fails DNS requests for most websites
Safari however works fine
If I quit tailscale Chrome starts working but then any future attempt to start Tailscale will constantly fail login
Seems 100% reproducible

**Comment by DentonGentry** [comment]
> On reboot it will connect, but Chrome then fails DNS requests for most websites. Safari however works fine.

That could be https://github.com/tailscale/tailscale/issues/9468
Recent Chrome versions try much harder to use IPv6, and in some conditions keep trying even if IPv4 would work better.

An exit node with broken IPv6, any any confounding factor like a proxy, will likely break Chrome but leave Safari unaffected. Non-Linux exit nodes are especially likely to trigger this https://tailscale.com/kb/1177/kernel-vs-userspace-routers/

**Comment by Pierozi** [comment]
Hey there, I got the same problem.
Already run through pretty much everything:
- Clean install
- Network check & Switch over 5G hotspot
- DNS Change
- Disabling IPv6
- Multiple reboot

For whatsoever reason it does not switch to ipv4.

```
❯ tailscale debug ts2021
22:00:33.053500 Fetching keys from https://controlplane.tailscale.com/key?v=79 ...
22:00:33.199015 Dial("tcp", "[2a05:d014:386:202:256c:6ede:f4f9:a51b]:80") ...
22:00:33.199562 Dial("tcp", "[2a05:d014:386:202:256c:6ede:f4f9:a51b]:80") = [::1]:51178 / [::1]:10011
22:00:33.202134 Dial("tcp", "[2a05:d014:386:202:256c:6ede:f4f9:a51b]:443") ...
22:00:33.202359 Dial("tcp", "[2a05:d014:386:202:256c:6ede:f4f9:a51b]:443") = [::1]:51180 / [::1]:10011
22:00:33.202655 controlhttp.Dial = 0x0, all connection attempts failed (HTTP: read tcp [::1]:51178->[::1]:10011: read: connection reset by peer, HTTPS: read tcp [::1]:51180->[::1]:10011: read: connection reset by peer)
all connection attempts failed (HTTP: read tcp [::1]:51178->[::1]:10011: read: connection reset by peer, HTTPS: read tcp [::1]:51180->[::1]:10011: read: connection reset by peer)
```

**Comment by icio** [comment]
> and i can't run the commandline tools: `tailscale debug ts2021`
> it show me the error log `zsh: command not found: tailscale` 

@ To confirm you're encountering the same issue you can run `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021` or configure an alias. See https://tailscale.com/kb/1080/cli?tab=macos

**Comment by wuwentao** [comment]
> > and i can't run the commandline tools: `tailscale debug ts2021`
> > it show me the error log `zsh: command not found: tailscale`
> 
> @wuwentao To confirm you're encountering the same issue you can run `/Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021` or configure an alias. See https://tailscale.com/kb/1080/cli?tab=macos#using-the-cli

thank you very much for your help, this command can run, and I still can't login....

```
❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021
10:53:28.098928 Fetching keys from https://controlplane.tailscale.com/key?v=85 ...
10:53:29.280402 Dial("tcp", "[2a05:d014:386:202:30f5:de62:8eed:5c47]:80") ...
10:53:29.280684 Dial("tcp", "[2a05:d014:386:202:30f5:de62:8eed:5c47]:80") = dial tcp [2a05:d014:386:202:30f5:de62:8eed:5c47]:80: connect: no route to host
10:53:29.280721 Dial("tcp", "3.125.149.81:80") ...
10:53:29.281023 Dial("tcp", "3.125.149.81:80") = 198.18.0.1:53419 / 3.125.149.81:80
10:53:29.780154 Dial("tcp", "[2a05:d014:386:202:b1ee:6525:7c95:d0f3]:443") ...
10:53:29.780372 Dial("tcp", "[2a05:d014:386:202:b1ee:6525:7c95:d0f3]:443") = dial tcp [2a05:d014:386:202:b1ee:6525:7c95:d0f3]:443: connect: no route to host
10:53:29.780414 Dial("tcp", "3.125.149.81:443") ...
10:53:29.780909 Dial("tcp", "3.125.149.81:443") = 198.18.0.1:53424 / 3.125.149.81:443
10:53:29.983305 controlhttp.Dial = 0xc000386010, <nil>
10:53:29.983326 did noise handshake
10:53:29.983329 final underlying conn: 198.18.0.1:53419 / 3.125.149.81:80
❯
❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021
10:54:47.136116 Fetching keys from https://controlplane.tailscale.com/key?v=85 ...
10:54:47.293904 Do: Get "https://controlplane.tailscale.com/key?v=85": read tcp 10.100.228.82:53618->18.194.180.142:443: read: connection reset by peer
10:54:47.294009 Get "https://controlplane.tailscale.com/key?v=85": read tcp 10.100.228.82:53618->18.194.180.142:443: read: connection reset by peer
❯ /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021
10:55:13.052819 Fetching keys from https://controlplane.tailscale.com/key?v=85 ...
10:55:13.200600 Do: Get "https://controlplane.tailscale.com/key?v=85": read tcp 10.100.228.82:53672->18.194.180.142:443: read: connection reset by peer
10:55:13.200687 Get "https://controlplane.tailscale.com/key?v=85": read tcp 10.100.228.82:53672->18.194.180.142:443: read: connection reset by peer
```

In additional, I have approve the app in setting, Private/Security  tab.
and also accepted the vpn config add to VPN tab, I can found an tailscale profile under VPN tab, but the status is always connected, and the Tailscale.app have a ! in the logo, once I click it and continue click [Login], there is no any popup info or browser webpage to login.
I know it will redirect to a website with sso login, but there is no any window or webbrowser open.

command line login will be hang and can't retrun:

```
❯ tailscale status
Logged out.
❯ tailscale version
1.58.2
  tailscale commit: 6a2a8457f0d62c775bfee3e350d2b34d85eda0f5
  other commit: 8c7d4563e46a1856053912ac067fc5036c2d2b3e
  go version: go1.21.5
❯ tailscale login
^C2024/01/25 11:14:43 context canceled
❯ time tailscale login
^@^C2024/01/25 11:16:33 context canceled
real	104.94s
user	0.09s
sys	0.07s
❯ time tailscale login





^C2024/01/25 11:17:46 context canceled
real	71.02s
user	0.09s
sys	0.07s
 ~ 
```

**Comment by wuwentao** [comment]
@Pierozi 
thank you very much for your help and support, ,seems it still can't work.

I have tried to use brew install command line tools to run it with my macos sonoma v14.2.1 with Intel CPU, not ARM64 cpu

got the same result , it hang at [tailscale up] command

my install and run command log as below:

```
❯ brew install --formula tailscale
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
c3c                    helm-ls                libnsgif               limesuite              openjph                rattler-build          scnlib                 steamguard-cli         tfautomv               zigmod
git-grab               icloudpd               libspelling            nowplaying-cli         rathole                rsyncy                 senpai                 terrapin-scanner       tomlplusplus           zipkin
==> New Casks
aqua                         bugdom2                      domzilla-caffeine            insomnium                    markedit                     shadow-bot                   theiaide                     znote
bitbox                       cleanupbuddy                 easydevo                     lyricsfinder                 nightshade                   taccy                        ttu-base-suite

You have 2 outdated formulae installed.

==> Downloading https://ghcr.io/v2/homebrew/core/tailscale/manifests/1.58.2
############################################################################################################################################################################################################################### 100.0%
==> Fetching tailscale
==> Downloading https://ghcr.io/v2/homebrew/core/tailscale/blobs/sha256:fdb31085c53afc854c3f24fb982ad4b5b16f1ab1c86636faef6d3d7ab5e19ee0
############################################################################################################################################################################################################################### 100.0%
==> Pouring tailscale--1.58.2.sonoma.bottle.tar.gz
==> Caveats
To start tailscale now and restart at login:
  brew services start tailscale
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/tailscale/bin/tailscaled
==> Summary
🍺  /usr/local/Cellar/tailscale/1.58.2: 9 files, 29.5MB
==> Running `brew cleanup tailscale`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> `brew cleanup` has not been run in the last 30 days, running now...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/wuwentao/Library/Caches/Homebrew/libidn2--2.3.4_1... (322.1KB)
Removing: /Users/wuwentao/Library/Caches/Homebrew/openssl@3--3.2.0_1... (8.6MB)
Removing: /Users/wuwentao/Library/Logs/Homebrew/openssl@3... (64B)
Removing: /Users/wuwentao/Library/Logs/Homebrew/ca-certificates... (64B)
Pruned 0 symbolic links and 2 directories from /usr/local
❯ sudo brew services start tailscale
Password:
==> Tapping homebrew/services
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 2640, done.
remote: Counting objects: 100% (2640/2640), done.
remote: Compressing objects: 100% (1181/1181), done.
remote: Total 2640 (delta 1282), reused 2556 (delta 1263), pack-reused 0
Receiving objects: 100% (2640/2640), 690.85 KiB | 825.00 KiB/s, done.
Resolving deltas: 100% (1282/1282), done.
Tapped 1 command (47 files, 865.5KB).
Warning: Taking root:admin ownership of some tailscale paths:
  /usr/local/Cellar/tailscale/1.58.2/bin
  /usr/local/Cellar/tailscale/1.58.2/bin/tailscaled
  /usr/local/opt/tailscale
  /usr/local/opt/tailscale/bin
  /usr/local/var/homebrew/linked/tailscale
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Warning: tailscale must be run as non-root to start at user login!
==> Successfully started `tailscale` (label: homebrew.mxcl.tailscale)
❯ sudo tailscale up
^@^@^@^@^@^@^@^@^@
```

I can't continue to run and exit this command ,it hang and can't quit or exit or timeout to exit.

so it's not the brew install issue, **it should be tailscale command line issue** 
and the root cause may be the `tailscale up` command can't work anymore in my MacOS
**maybe it causes by Intel CPU and ARM64 CPU？**

**Comment by kaiwu-astro** [comment]
Same problem here, on MacOS Sonoma 14.5 . I cannot solve it anyhow, but I post my debug log here for reference

```
 ✘  ~  /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021
15:15:15.240249 Fetching keys from https://controlplane.tailscale.com/key?v=85 ...
15:15:45.238983 Do: Get "https://controlplane.tailscale.com/key?v=85": dial tcp 208.91.112.55:443: i/o timeout
15:15:45.239054 Get "https://controlplane.tailscale.com/key?v=85": dial tcp 208.91.112.55:443: i/o timeout
 ✘  ~  /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021
15:15:56.240200 Fetching keys from https://controlplane.tailscale.com/key?v=85 ...
15:15:57.583616 Dial("tcp", "208.91.112.55:80") ...
15:15:58.084029 Dial("tcp", "208.91.112.55:443") ...
15:17:12.585018 Dial("tcp", "208.91.112.55:80") = dial tcp 208.91.112.55:80: connect: operation timed out
15:17:12.585067 Dial("tcp", "[2a05:d014:386:202:6089:6a93:59a4:920a]:80") ...
15:17:13.026288 Dial("tcp", "[2a05:d014:386:202:6089:6a93:59a4:920a]:80") = [2001:250:500f:3ec:c7f1:44df:2b9a:b473]:57575 / [2a05:d014:386:202:6089:6a93:59a4:920a]:80
15:17:13.084221 Dial("tcp", "208.91.112.55:443") = dial tcp 208.91.112.55:443: connect: operation timed out
15:17:13.084241 Dial("tcp", "[2a05:d014:386:202:6089:6a93:59a4:920a]:443") ...
15:17:13.357214 controlhttp.Dial = 0xc0001d4070, <nil>
15:17:13.357229 did noise handshake
15:17:13.357235 final underlying conn: [2001:250:500f:3ec:c7f1:44df:2b9a:b473]:57575 / [2a05:d014:386:202:6089:6a93:59a4:920a]:80
15:17:13.357321 Dial("tcp", "[2a05:d014:386:202:6089:6a93:59a4:920a]:443") = dial tcp [2a05:d014:386:202:6089:6a93:59a4:920a]:443: operation was canceled
 ~  /Applications/Tailscale.app/Contents/MacOS/Tailscale debug ts2021
15:43:13.836608 Fetching keys from https://controlplane.tailscale.com/key?v=85 ...
15:43:18.094995 Dial("tcp", "208.91.112.55:80") ...
15:43:18.596015 Dial("tcp", "208.91.112.55:443") ...
15:44:33.096645 Dial("tcp", "208.91.112.55:80") = dial tcp 208.91.112.55:80: connect: operation timed out
15:44:33.096683 Dial("tcp", "[2a05:d014:386:202:9a01:a6fe:4251:8db8]:80") ...
15:44:33.459039 Dial("tcp", "[2a05:d014:386:202:9a01:a6fe:4251:8db8]:80") = [2001:250:500f:3ec:c7f1:44df:2b9a:b473]:59421 / [2a05:d014:386:202:9a01:a6fe:4251:8db8]:80
15:44:33.598050 Dial("tcp", "208.91.112.55:443") = dial tcp 208.91.112.55:443: connect: operation timed out
15:44:33.598089 Dial("tcp", "[2a05:d014:386:202:9a01:a6fe:4251:8db8]:443") ...
15:44:33.796809 controlhttp.Dial = 0xc0003ae038, <nil>
15:44:33.796824 did noise handshake
15:44:33.796835 final underlying conn: [2001:250:500f:3ec:c7f1:44df:2b9a:b473]:59421 / [2a05:d014:386:202:9a01:a6fe:4251:8db8]:80
```

**Comment by agottardo** [comment]
@Pierozi @travischambers adding this for posterity: your logs indicate that the issue was caused by the macOS Content Filter blocking traffic meant for Tailscale servers. Switching to the Standalone variant should have fixed the issue.

**Comment by kelivel** [comment]
We believe this has been fixed. If you're still encountering similar behavior, please create a new issue and include a [bug report](https://tailscale.com/kb/1227/bug-report/) after reproducing the behavior, and we can take another look.
