### ISSUE TITLE
Internal server error when adding an ACL between two tags, with the action 'check'

### ISSUE THREAD

**Issue by deanpcmad** [tailscale/tailscale#9660]
### What is the issue?

While trying to setup Tailscale SSH to lockdown access between 2 tags, I kept getting an internal server error. When changing `action` to `accept` it saves fine.

For an example, this is what I was using:

```
{
	"action":      "check",
	"src":         ["tag:ci"],
	"dst":         ["tag:prod"],
	"users":     ["autogroup:nonroot"],
	"checkPeriod": "1h"
},
```

It should show an error instead to say that `action: check` isn't supported when between 2 tags

**Comment by phirework** [comment]
This is working as intended. Check mode isn't supported for [connections between tagged devices](https://tailscale.com/kb/1193/tailscale-ssh/#ensure-tailscale-ssh-is-permitted-in-acls): 

> From a tagged device to another tagged device, for any tags. Note that an SSH access rule from a tagged device cannot be in check mode.

A device's tags take over the identity of the device and its permissions are then no longer associated with the user. They're more like [service accounts](https://tailscale.com/kb/1068/acl-tags/) than metadata. Check mode asks you to verify your identity by authenticating, and it doesn't really make sense to authenticate _as_ a tag.
