### ISSUE TITLE
High memory usage on tailscale win 11

### ISSUE THREAD

**Issue by stevenxi** [tailscale/tailscale#9664]
### What is the issue?

High memory usage. 1,153MB memory usaged.

### Steps to reproduce

Leave tailscale open.

### OS version

Win 11 22H2

### Tailscale version

1.50.1

**Comment by bradfitz** [comment]
There's nothing here from which we can debug.

**Comment by DentonGentry** [comment]
The template asks for a bug report because it allows us to look at telemetry for the tailnet. This issue has nothing to act on.

Please file this as a support ticket instead, so we can followup about the account: https://tailscale.com/contact/support/
