### ISSUE TITLE
wgengine: rate limiter in `wgengine.RequestStatus`

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#97]
This gets called too frequently on hello.ipn.dev, eating CPU time.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687664500683) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
I profiled CPU on Hello recently and don't remember this. This is old, closing.
