### ISSUE TITLE
admin consol login option in tailscale menu missing

### ISSUE THREAD

**Issue by quartermarsh** [tailscale/tailscale#9706]
### What is the issue?

The tailscale menu option to select admin consol login no longer appears in the dropdown menu on macos.

<img width="665" alt="Screenshot 2" src="https://github.com/tailscale/tailscale/assets/75918994/00992b5d-bc6e-4502-8a59-3a0dd6cb9f6d">

### Steps to reproduce

Click on Tailscale menu bar item, scroll to admin account, observe lack of option to login to admin consol.

### Are there any recent changes that introduced the issue?

Between your recent changes and various macos security updates it’s very hard to say what introduced this issue. I believe it was not happening until v1.50.0. It does not appear to have effected v1.44.0

On my main machine (M1 Mac on 13.6) the option was available today until I logged out of the admin consol but it had disappeared when I logged back in. I was testing to see if that would happen, which it did. Prior to that I had a tab open with the admin consol for about 12 days.

NB I have five macs on three os-es and two ios devices (which I haven’t checked). Three of the macs are on 1.50.1, two are on 1.44.0. All have owner access.

### OS

macOS

### OS version

13.6 (owner) 10.15.7 & 10.14.6

### Tailscale version

1.50.1 & 1.44.0

### Other software

Little Snitch has Tailscale outgoing connection allowed to Tailscale domain and githubusercontent. IPNextension allowed incoming and outgoing.

Of course, I use Safari and macos password manager.

### Bug report

BUG-884d808aecbdfba6204cafaf91513e9e33c6f4abaaae04d2a7ce26b1df074135-20231007221155Z-9b9f5f926992bcec

**Comment by bradfitz** [comment]
It's since been fixed and will reappear in the next release.

**Comment by quartermarsh** [comment]
Thank you! You guys are great. Thank heavens for bookmarks 0_o
