### ISSUE TITLE
MagicDNS: hostname.home converted to hostname-home instead of just hostname

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#971]
Automatic MagicDNS name assignment doesn't seem to be working quite like we'd hope, and a user just ran into this.

I think maybe we're only stripping .local from the hostname, and not other suffixes. I don't see any reason to keep anything after the dot on an imported hostname, upon generating the MagicDNS name; it will probably always be the wrong thing to do.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2io9d)

**Comment by danderson** [comment]
We are indeed only trimming common suffixes: .local, .localdomain, .lan.

We could add .home to the common suffixes, or always trim down to just the first part of the name.

I don't have strong feelings either way, other than to note that I believe /etc/hostname is specified as being a single DNS label, despite people using it in other ways.

@apenwarr still feel strongly that stripping all but the first component is the right call? I'm neutral, so will happily implement whatever.

**Comment by danderson** [comment]
Going to go with "yes" and call it a day. Shout if you object :)
