### ISSUE TITLE
Tailscale cannot identify the clone of a windows OS

### ISSUE THREAD

**Issue by ZM-Kimu** [tailscale/tailscale#9723]
### What is the issue?

Hello, there's some bug when I using the Tailscale. I have 2 machines, one in home and another one in workplace. In the past few days, I tried to use ghost copier to clone the OS in home then put the OS to workplace machine. It working well, but when I using the Tailscale, it shows has been login. After work, I using my home computer, Tailscale warning me need re-login to use. 

### Resolution

I tried to rename the work machine, full uninstall then reinstall, delete register value, and remove the machine from tailscale admin console. As result, it doesn't work, Tailscale consider 2 machines is same. But I final solve it, delete all file in C:\ about Tailscale. I don't know how Tailscale identify each machine. So I think it maybe a bug. Because the uninstall application cannot delete all the config files.

### OS

Windows

### OS version

Microsoft Windows 11 Professional Insider Preview 10.0.23560 ver 23560

### Tailscale version

1.50.1

**Comment by Enzo018** [comment]
Hello Kimu, I just ran into this exact same problem. Would you be able to tell me by any chance which folders you deleted related to Tailscale in C:\ and to which register value you are referring?

**Comment by nickkhyl** [comment]
@Enzo018: Tailscale saves its settings, profiles, and other information in `%programdata%\Tailscale`. We intentionally retain this information during uninstalls to accommodate app downgrades and other scenarios, but plan to offer the option for full removal of this data in the future. We also plan on supporting scenarios that require [generalization of a Windows installation](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation?view=windows-11), but do not have a specific timeline to share at this time.

In the meantime, if you need to clone your machine, please uninstall Tailscale from the new device, manually delete `%programdata%\Tailscale%`, then reinstall Tailscale. This will prompt you to log in again on the new device.
