### ISSUE TITLE
gRPC with Kubernetes Operator L7 Ingress

### ISSUE THREAD

**Issue by timtailscale** [tailscale/tailscale#9725]
### What is the issue?

The Tailscale Operator allows exposing a gRPC service as a L3 Service, but not as a L7 Ingress due to the way that `tailscaled` handles HTTP/2 connections in the serve proxy. Allowing a L7 Ingress path as well as the L3 Service path allows for a wider use case of the Operator.

http://go/hs/21385

### Steps to reproduce

Try to access a gRPC service using a L7 Ingress as explained here: https://tailscale.com/kb/1236/kubernetes-operator/#exposing-a-service-using-ingress.

**Comment by irbekrm** [comment]
Thank you for opening the issue @timtailscale .

This was fixed by #9884 (and some followup PRs)-  `tailscale/tailscale:v1.52.0` and later tags will have the fix.
