### ISSUE TITLE
Installation or Updating from Turkey doesn't work anymore

### ISSUE THREAD

**Issue by metronetweb** [tailscale/tailscale#9738]
### What is the issue?

Existing, previously working Tailscale installations from inside Turkey have stopped working & new installations or upgrades fail with either:

curl: (22) The requested URL returned error: 451

or with apt:

Unavailable For Legal Reasons

Is Tailscale now banned from Turkish IP's - if so why? It was previously working for a long time.

### Steps to reproduce

Upgrade via apt dist-upgrade or install via script or manual installation.

### OS

Linux

### OS version

Debian 11, 12, Ubuntu 22.04

**Comment by DentonGentry** [comment]
Could you contact support https://tailscale.com/contact/support/ with:
- the name of the ISP in Turkey
- the public IP address of your home

**Comment by DentonGentry** [comment]
If you can supply the name of the ISP and a public IP address, for example of your home, it will allow us to look up information about that ISP and IP and what we might be able to do.

https://tailscale.com/contact/support/, or email support@tailscale.com and reference bug 9738.
