### ISSUE TITLE
wg-quick breaks Tailscale?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#975]
I was doing some benchmarking of kernel wireguard against Tailscale for a separate bug and found that wg-quick breaks Tailscale (at least on Debian buster).

DNS works, but pinging login.tailscale.com doesn't work until I down the wg0 interface:

```
root@tsdev:~# ping login.tailscale.com
PING login.tailscale.com (3.121.18.47) 56(84) bytes of data.
^C
--- login.tailscale.com ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 82ms

root@tsdev:~# wg-quick  down wg0
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
[#] nft -f /dev/fd/63

root@tsdev:~# ping login.tailscale.com
PING login.tailscale.com (3.121.18.47) 56(84) bytes of data.
64 bytes from ts-login-v4 (3.121.18.47): icmp_seq=1 ttl=42 time=153 ms
64 bytes from ts-login-v4 (3.121.18.47): icmp_seq=2 ttl=42 time=154 ms
64 bytes from ts-login-v4 (3.121.18.47): icmp_seq=3 ttl=42 time=153 ms
^C
--- login.tailscale.com ping statistics ---
```

You know offhand what's happening, @danderson?

**Comment by bradfitz** [comment]
Closing until I see this again and take more notes.

**Comment by tombh** [comment]
I noticed this too

**Comment by karlgrz** [comment]
@bradfitz I'm encountering this now still. Let me know what I can provide to help diagnose it or open a new issue, happy to help resolve it.

**Comment by bradfitz** [comment]
@karlgrz, feel free to file a new issue with details, `tailscale bugreport`, etc. And then reference this one.

**Comment by karlgrz** [comment]
@bradfitz will do later this afternoon!
