### ISSUE TITLE
FR: Tailscale for RaspianOS Bookworm (debian12) based

### ISSUE THREAD

**Issue by corasaniti** [tailscale/tailscale#9767]
### What are you trying to do?

When will Tailscale be available for RaspianOS based on Bookworm (Debian12)?
Thank you

![Immagine](https://github.com/tailscale/tailscale/assets/5001932/205f597e-1796-4a92-8773-1cf6dcdd648a)

**Comment by DentonGentry** [comment]
It already is, we need to update the knowledgebase.
https://pkgs.tailscale.com/stable/#raspbian-bookworm

**Comment by corasaniti** [comment]
@DentonGentry 
Thanks
