### ISSUE TITLE
Android 10 app crash immediately after Microsoft Login sucess

### ISSUE THREAD

**Issue by diegomontoya** [tailscale/tailscale#977]
**Describe the bug**
Android 10 app crash immediately after Microsoft Login sucess

**To Reproduce**
1. Login to app via Microsoft login 
2. Success
3. Please "x" to close Login window
4. for a brief micro second, the UI shows list of devices, then crash
5. Relaunch App,for a brief micro second, the UI shows list of devices, then crash

**Expected behavior**
No crash. List devices

**Version information:**
 - Device: Vivo X50Pro+
 - OS:  Android
 - OS version: 10
 - Tailscale version: 1.2.2-t76c2982d8-g39dfd8495

EDIT: update app version to actual version

**Comment by bradfitz** [comment]
> Tailscale version: LATEST from Google Play

Can you clarify what that is, at least for posterity? The latest changes over time.

/cc @eliasnaur

**Comment by diegomontoya** [comment]
@bradfitz  @eliasnaur 

Android App Version: 1.2.2-t76c2982d8-g39dfd8495

**Comment by diegomontoya** [comment]
We have 2 different users able to login successful and use tailscale on Android 10. 

1) OnePlus 7T, Android 10, microsoft login.
2) Huawei V10, Android 10, microsoft login.

The only difference between them and me is that I am the admin user and they are sub-users.  Crash may be related to admin user code on android.

**Comment by bradfitz** [comment]
What's your Tailscale IP on the crashing device? Does it get far enough to allocate one that you see in the Tailscale admin console at https://login.tailscale.com/admin/machines ?

**Comment by diegomontoya** [comment]
@bradfitz  @eliasnaur 

My app post-login issue exists also with IOS. I am able to login but nothing happens on IOS v1.2.8 app on iPhone X ios 14.2. 

I can confirm that BOTH devices are correctly REGISTERED on the tailscale device dash board after login. So android crashes after login. ios just does nothing, stays on the "needs authentication screen" forever. Restarting ios app causes it to request a new login. 

My Device IP:
1) Android: 100.81.248.73
2) IOS: 100.118.85.70

So yes, the dashboard is able to register both ios and android device correctly but non of the ios/android app is usable to me.

**Comment by diegomontoya** [comment]
@bradfitz  @eliasnaur 

I have emailed screencapture video of my android 10 device to @danderson. His is the only one I have email to.

Slow down the video to the 18s-19s mark and you will clearly see that UI was able to successfully render a partial list of my tailscale account devices before it eats dirt.

**Comment by eliasnaur** [comment]
@diegomontoya it would help a lot if you have a chance to send an `adb logcat` dump of the crash.

**Comment by diegomontoya** [comment]
@eliasnaur 

Tailscale is issuing an intent to system for non-existing system ```com.android.vpndialogs```. Strange. 

For reference, this phone is un-rooted but I did freeze some bloat apps. Also, this phone also has two other 3rd party VPN apps installed and running without issue and one of them is the official WireGuard app. 

```
12-02 17:42:24.648 14226 14226 E AndroidRuntime: FATAL EXCEPTION: main
12-02 17:42:24.648 14226 14226 E AndroidRuntime: Process: com.tailscale.ipn, PID: 14226
12-02 17:42:24.648 14226 14226 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}; have you declared this activity in your AndroidManifest.xml?
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2103)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1903)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5961)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Activity.startActivityFromFragment(Activity.java:5936)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:8717)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Fragment.startActivityForResult(Fragment.java:1121)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.Fragment.startActivityForResult(Fragment.java:1110)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at com.tailscale.ipn.App.startActivityForResult(App.java:206)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at com.tailscale.ipn.App.access$100(App.java:43)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at com.tailscale.ipn.App$4.run(App.java:198)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:230)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7836)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
12-02 17:42:24.648 14226 14226 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by diegomontoya** [comment]
@eliasnaur 

Turned out it was my fault. Geez. 

Fixed Tailscale crash by restoring vpndialogs app. Turns out my non-root debloat soft-uninstalled it. 

```
adb shell
pm install-existing com.android.vpndialogs
```

**Comment by eliasnaur** [comment]
Thank you for debugging the issue.
