### ISSUE TITLE
Mullvad Exit Nodes don't work after update to macOS 14.1

### ISSUE THREAD

**Issue by bobbyl140** [tailscale/tailscale#9770]
### What is the issue?

Mullvad Exit Nodes worked fine on 14.0, but since I updated my Mac to 14.1, when a Mullvad Exit Node is selected, the internet is inaccessible. 

### Steps to reproduce

- Select any Mullvad Exit Node
- Try to load a website

### Are there any recent changes that introduced the issue?

Updating macOS to 14.1 (specifically build 23B5056e if it matters)

### OS

macOS

### OS version

macOS Sonoma (14.1 build 23B5056e)

### Tailscale version

1.50.0

### Other software

(I have tested with these completely disabled with the same result):
- macOS's builtin firewall
- Little Snitch
- iCloud Private Relay (should be off by itself anyways since there is a VPN active)

### Bug report

BUG-b1f16baec17bb8e258976d39ab6c0cc7e6272d92a629e3413650776c2d8b3c68-20231012062405Z-a6a9b6a40640d1987

**Comment by bobbyl140** [comment]
Also happens on Tailscale 1.50.1

**Comment by pppaapp** [comment]
Is Tailscale DNS disabled?

I'm having the same problem

**Comment by bobbyl140** [comment]
> Is Tailscale DNS disabled?
> 
> 
> 
> I'm having the same problem

I have it enabled. Does disabling fix it?

**Comment by pppaapp** [comment]
> > Is Tailscale DNS disabled?
> > I'm having the same problem
> 
> I have it enabled. Does disabling fix it?

I have a problem when it is disabled

**Comment by bobbyl140** [comment]
@pppaapp I just cancelled the Mullvad subscription and got the refund for the rest of the month, I mean this issue hasn't even been labeled yet... I understand that it may not be first priority but I don't wanna pay for something I can't use either

**Comment by bobbyl140** [comment]
@pppaapp With no explanation, the latest App Store version fixes this issue. Thank you Tailscale team for fixing!

**Comment by xanderio** [comment]
I'm still experiencing this problem. None of the Mullvad exit nodes work, while a personal exit node works just fine.

**Comment by Sciencentistguy** [comment]
I am also experiencing this issue

**Comment by charlestephen** [comment]
I also have this issue on Tailscale 1.64 App Store version
