### ISSUE TITLE
k8s operator does not seem to tolerate device being deleted manually from admin panel

### ISSUE THREAD

**Issue by alexkuklin** [tailscale/tailscale#9773]
### What is the issue?

Annotated existing ingress with ingressClassName.
Got wrong machine name.
Removed it with tailscale admin panen.
Tried to remove ingress.
Got persisting 
```
{"level":"error","ts":"2023-10-12T07:57:38Z","msg":"Reconciler error","controller":"ingress","controllerGroup":"networking.k8s.io","controllerKind":"Ingress","Ingress":{"name":"tailscale-ingress","namespace":"default"},"namespace":"default","name":"tailscale-ingress","reconcileID":"55a5bc49-e334-4da2-aebf-4ff0fb0bc4d1","error":"failed to cleanup: deleting device: tailscale.DeleteDevice: Status: 500, Message: \"internal server error\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}
```
in the operator log.
Ingress is not deleting.

### Steps to reproduce

1. Modify existing ingress with `ingressClassName: tailscale`
2. Delete machine created for that ingress from tailscale admin panel
3. Try deleting ingress.
4. Ingress is stuck (in finaliser, I suppose)

### OS

Linux, Other

### OS version

k8s

### Tailscale version

1.51.117

### Bug report

BUG-ecfba9b0a374c198a8db8df8ca795cb57d9a02953ad599600d9c40b6ee6bacfc-20231012084322Z-19d34b80f2990ad1

**Comment by irbekrm** [comment]
Thank you for opening the issue!

Generally, proxies created by the operator should be deleted from the kube cluster first, not by deleting the device in the admin panel.

However, we should fix the issue where they can't be deleted from cluster after deleting from admin panel.
This will be fixable once we get in a small change to the API to ensure that we can detect that the device no longer exists from cluster https://github.com/tailscale/corp/pull/15318 (private link)

**Comment by irbekrm** [comment]
Thank you for opening the issue @alexkuklin .

This is now fixed in the latest operator version `tailscale/k8s-operator:unstable-v1.53.100`.
The recommended way of cleaning up resources is still by [deleting/updating cluster resources](https://tailscale.com/kb/1236/kubernetes-operator/?q=operator#removing-a-service), which will ensure that the associated proxy node will get deleted from control plane, however if you have already deleted the node from Tailscale control plane, cleaning up cluster resources no longer gets stuck.
