### ISSUE TITLE
Android app forgets login/keys after stopped

### ISSUE THREAD

**Issue by rmoreRojoli** [tailscale/tailscale#9788]
### What is the issue?

After installing the app from the Play Store, I changed the server to a custom one, logged in with it and the app works. After closing and forcefully stopping it I try to start the app again and I am logged out partially. It still has the same menu buttons on the right but I only have a login screen after turning on.
Looks like my login if forgot or the keys are gone.

### Steps to reproduce

Install app form Play Store (I am in the beta program but the app version is not beta) - 1.48.2
Open app
Change server to custom
Log in with other after app restart
Connect
Disconnect
Close app
Force close app
Open
You will see turned off so turn Tailscale on
Login screen will appear where Login with Other will not be your custom server's login

### OS

Android

### OS version

13

### Tailscale version

1.48.2

### Bug report

BUG-7fdb354f9707f43cda473ab5d89b71fa59693c3305c421c865bc2a4c2ac10a8f-20231013082211Z-e3d7682536682226

**Comment by agottardo** [comment]
Fixed in the new Android app (v1.66 or later).
