### ISSUE TITLE
FR: ability to change busybox image for proxy initContainer

### ISSUE THREAD

**Issue by Protozoan1369** [tailscale/tailscale#9819]
### What are you trying to do?

We would like to use a busybox image that isn't on docker hub for the proxy pod that has a busybox initContainer.  In general it would be nice to be able to override all the images in the operator.

### How should we solve this?

Allow us to pass in an env variable to overwrite the container images?

### What is the impact of not solving this?

The impact we are dealing with is being rated limited by docker hub when we could just use a different registry.

**Comment by irbekrm** [comment]
Closing as fixed by https://github.com/tailscale/tailscale/pull/9839
