### ISSUE TITLE
Too easy to permanently delete a node. Undelete feature?

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#984]
Steps:
- Create a node
- Accidentally delete it when you meant to do something else (oops)

Expected:
- A warning message or undo button

Actual:
- The node is gone forever and you have to reauth it again - if you are still able to reach it.

Much like we discussed with key expiry, it would be nice to be able to centrally extend the lifetime of a node after shutting it down. To make this work, I think we could mark a node as "deleted at time X" when we delete it, and then allow undoing it for an extra N hours after X. Thus, a node marked as deleted should presumably act exactly like a node with an expired key. (I'm not sure which of the two behaviours needs to change for that to work smoothly.)

**Comment by DentonGentry** [comment]
We have a warning message or undo button now. I'm going to close this as I think the need has been addressed, feel free to reopen if disagree.
