### ISSUE TITLE
Black screen & can't run on some Android TV Model (even stick and Set-Top Boxes)

### ISSUE THREAD

**Issue by Hanasunflower** [tailscale/tailscale#9849]
### What is the issue?

Tailscale can't run on Android TV 9 version of Stick and Set-Top Boxes (Excluding Nvidia Shield) because the app did not start anything. The app are simply showing nothing (black screen) for really long time.

The app is already uninstalled, reinstalled and even remove caches & data. still not working and only black screen are showed.
This is not also my issues, it's a widespread issues on google play store reviews (TV Version) said if they can't run especially on Xiaomi brand (Mi Box, Mi TV Stick, etc.)

The app that I used is already latest version (1.48.2-tab970fe55-g52607bf35ef)
[Device detail]
Xiaomi Mi TV Stick [Model: MiTV-AESP0]
Android TV version 9

### Steps to reproduce

Only launching on MiTV-AESP0 [Stick model], installed normally on Google Play Store, then nothing instead of black screen.

### OS

Android

### OS version

Android TV 9

### Tailscale version

1.48.2

**Comment by bradfitz** [comment]
Dup of #4332
