### ISSUE TITLE
macOS: Cannot disconnect without quitting TS app first.  

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#9880]
### What is the issue?

Previous macOS and TS builds, I could reliably use the VPN menu bar pull down to disconnect from TS.  That option no longer works on Sonoma 14.1 RC

### Steps to reproduce

1. Install macOS 14.1 RC
2. Install TS
3. Launch app to connect to Tailnet
4. Use menu bar to disconnect from Tailnet
5. Observe TS automatically re-connects

### Are there any recent changes that introduced the issue?

TS 1.51.178
Sonoma 14.1 RC

### OS

macOS

### OS version

Sonoma 14.1 RC

### Tailscale version

TS 1.51.178

### Screen Record

https://github.com/tailscale/tailscale/assets/1215508/4cfa164c-ff30-4ced-8750-a9c7b3319ad0

**Comment by agottardo** [comment]
Thanks for the report, a fix for this is on the way.

**Comment by agottardo** [comment]
A fix for this issue has been merged, will ping when available in unstable.
