### ISSUE TITLE
mac tailscaled wiki need to update

### ISSUE THREAD

**Issue by hahacold** [tailscale/tailscale#9909]
### What is the issue?

I followed this page
https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS
after I ran
$ go install tailscale.com/cmd/tailscale{,d}@main
and
$ sudo $HOME/go/bin/tailscaled install-system-daemon

And commands below didn't work
$ tailscale up # (any optional arguments)
$ tailscale status

I thought I should do brew install tailscale too, after few days using, I realized I was misunderstanding , I downloaded two tailscale.

But as I said, commands didn't work.

update:
I found that I should do /Users/test/go/bin/tailscale up 
to run
% which /Users/test/go/bin/tailscale
/Users/test/go/bin/tailscale
% which tailscale
/opt/homebrew/bin/tailscale

### Steps to reproduce

I followed this page
https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS
after I ran
$ go install tailscale.com/cmd/tailscale{,d}@main
and
$ sudo $HOME/go/bin/tailscaled install-system-daemon

And commands below didn't work
$ tailscale up # (any optional arguments)
$ tailscale status

### OS

macOS

**Comment by bradfitz** [comment]
You didn't say how they didn't work. What'd they say?

Did you not read this part of that page? ...

> That'll put the binaries in $(go env GOPATH)/bin, so likely $HOME/go/bin. You can copy or symlink those binaries into your $PATH, or make your $PATH include that directory.

**Comment by hahacold** [comment]
I’m sorry
