### ISSUE TITLE
ACL validate API should accept a comment on the first line

### ISSUE THREAD

**Issue by dsymonds** [tailscale/tailscale#9910]
### What is the issue?

The `/api/v2/tailnet/{tailnet}/acl/validate` endpoint does not appear to accept HuJSON (it barfs on comments, at least), whereas the adjacent `/api/v2/tailnet/{tailnet}/acl` endpoint supports HuJSON. It doesn't seem right to not be able to validate in the same format as you're able to apply.

**Comment by DentonGentry** [comment]
Comments do work, and a comma after the last element of a list (which is rejected by regular JSON) does work:
```
curl "https://api.tailscale.com/api/v2/tailnet/example.com/acl/validate" \
  -u "$(cat ~/keys/tskey):" \
  --data-binary '
  {
    // testing that a comment works
    "acls": [
     { "action": "accept", "src": ["100.105.106.107"], "dst": ["1.2.3.4:*"] },
    ],
  }'

{}%
```

Can you provide an example which doesn't validate?

**Comment by dsymonds** [comment]
I'll try to whittle back my real ACL, which I copied down from the admin console verbatim (so it validates there just fine). The HTTP 400 response is only `{"message":"invalid character '/' looking for beginning of value"}`, so it'll take a little to narrow down what part is failing.

**Comment by dsymonds** [comment]
Ah! If the input _starts_ with a comment, it fails. If I drop the first line (which in my ACL file is a line comment), it works against the validation API.

**Comment by DentonGentry** [comment]
Indeed, a comment as the first character fails:
```
curl "https://api.tailscale.com/api/v2/tailnet/example.com/acl/validate" -u "$(cat ./tskey):" \
  --data-binary '
  // testing that a comment on the first line fails
  {
    "acls": [
     { "action": "accept", "src": ["100.105.106.107"], "dst": ["1.2.3.4:*"] },
    ],
  }'
{"message":"invalid character '/' looking for beginning of value"}%
```

**Comment by dsymonds** [comment]
Could it be due to the cleverness of the API supporting both a JSON object and a JSON array as inputs? And it is the detection tripping things up?

**Comment by dsymonds** [comment]
When this gets fixed, https://github.com/tailscale/tailscale/blob/main/api.md#validate-and-test-policy-file should be updated to mention that HuJSON is supported; it only states JSON right now, where the nearby https://github.com/tailscale/tailscale/blob/main/api.md#validate-and-test-policy-file doc explicitly states that both JSON and HuJSON are accepted.

**Comment by DentonGentry** [comment]
I think this was resolved about 3 weeks ago, the validate endpoint should accept a leading comment now.
