### ISSUE TITLE
sharing: devices appear as the owner, not necessarily who shared them

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#992]
**Describe the bug**

@apenwarr shared @danderson's device to Sophi, and it appeared in her client under "Dave Anderson." This is confusing for both sharer and sharee, who might not understand where that name is coming from. Sophi had no interaction with Dave Anderson, so why would his name appear in her Tailscale client.

**Possible Solutions**

* We could rename shared devices to appear as the _domain_ they're from rather than the individual user. So a device shared from example.com would appear in your menu bar as "example.com > device name". This is awkward for long domains like my.fullname.username@gmail.com, but would get better if we offered the ability to name tailnets later on.
* We could rename shared devices to appear as the _sharer_ rather than the owner. This solves the problem of expectations. I worry it might cause confusion down the line with devices appearing as one user in one place, and another user in others.

**Comment by crawshaw** [comment]
Conclusion: we show the device as the person who shared it.

**Comment by rosszurowski** [comment]
If you already have a share with the same device to the same network, you shouldn't be able to accept it again. It needs to restrict multiple shares of one device between two tailnets.

**Comment by bradfitz** [comment]
Implementation detail nodes:

* add new Node field like 'SharerUserID', used if non-zero
* scrub the UserProfile of the real Owner UserID on Nodes to have no profile image and fake name ("Shared Devices"), for old (pre-1.4) clients
* update Mac and Windows (and tailscale CLI) clients to use Node.SharerUserID instead when non-zero

Sound right, @rosszurowski @danderson @crawshaw @apenwarr?

**Comment by bradfitz** [comment]
@rosszurowski, @soniaappasamy, I just noticed the admin panel also needs to be updated for this.

I shared the corp `monitoring` node to my gmail account and the admin panel shows me `danderson@tailscale.com` in the list.

I'll work on the macOS and Windows clients.

And `tailscale status` I guess.

**Comment by soniaappasamy** [comment]
@rosszurowski unless you're already doing this in your current round of updates, I'm happy to own this for the admin panel

**Comment by rosszurowski** [comment]
@soniaappasamy and I just met and figured it be best for her to own this one, so I'm leaving her as the assignee.
