### ISSUE TITLE
FR: Enable Mullvad for AUSTRALIA regaion

### ISSUE THREAD

**Issue by marvin8** [tailscale/tailscale#9938]
### What are you trying to do?

I am trying to use Mullvad as an exit node in my tailnet.

### How should we solve this?

Please add the Australia region to your Mullvad VPN service

### What is the impact of not solving this?

Needing to run a selfhosted exit node (with all risks involved)

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/9314

**Comment by Tompennyau** [comment]
also need this
