### ISSUE TITLE
Windows: Failed to write packet to TUN device: file already closed

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#994]
A user had this problem, which seems to have prevented all tailscale communications on their device. Interestingly, it persisted even after upgrading from v1.0.4 to v1.2.9, even though Tailscale was obviously working before.

12-05,01:09:04.366 srv: 14.0M/0.0M Failed to write packet to TUN device: file already closed
12-05,01:09:06.046 srv: 14.0M/0.0M v1.0.4-ge256174d6 peers: 16308/5752
...
[upgraded]
12-05,01:11:11.065 Failed to write packet to TUN device: file already closed
12-05,01:11:11.320 router: dns: ran ipconfig /registerdns in 0s
12-05,01:11:11.536 monitor: got windows change event after 1.4992498s: evt=route-o
12-05,01:11:11.636 monitor: got windows change event after 1.0019ms: evt=addr-o
12-05,01:11:11.636 monitor: got windows change event after 8.9997ms: evt=addr-o
12-05,01:11:11.988 v1.2.9-tdaebded28-g17e332346 peers: 348/404

logid: ec86a3c817e63f9561b9c10d0bdea23e62d3b79602160c7e3c10b0e8d9d5c58a

The "file already closed" message for this person appears to have only started this evening, if I look back through the last ~5 days of logs.

**Comment by apenwarr** [comment]
This doesn't seem super common, but not completely rare either:

./greplogs --days=7 --shard=0/20 -T 'file already closed' | cut -d' ' -f1 | sort | uniq -c
    397 02190df05ea4
      1 03aa60ba3b07
      1 060c89e267e0
      1 08166f2daed9
     50 09585b4cb1cf
    322 0a51f3d1f492
      1 0b8b13c1541f

So, 7 unique instances in 1/20th of our nodes over 7 days, which means ~140 people have experienced this error in a week.

**Comment by apenwarr** [comment]
One thing I previously noticed with a similar error on Linux before, is that there are no log messages produced when we decide to close a tun device, and even more importantly, no explanation of *why* we are closing the tun device, and furthermore, there's little point continuing to run if the tun device is closed. We should probably fix all three of those problems.

**Comment by bradfitz** [comment]
Dup of #780. I verified the logid in question is also using WSL.
