### ISSUE TITLE
FR: 

### ISSUE THREAD

**Issue by Stephan0203** [tailscale/tailscale#9940]
### What are you trying to do?

I'm tryin to connect remotely to my Synology NAS with Tailscale. I have downloaded Tailscale both to my Synology NAS and to my Mac mini. Than I copied the address of the Synology NAS, I went on my desktop, clicked on "go", "connect to the server", I pasted the address and clicked on "connect". After that a popup asked me to insert the name and the password of my Synology NAS account but when I insert them it tells me the those are incorrect and I can't access to my account.
I tried both the name and the password on quickconnect and both where right.
How can I access remotely to my Synology NAS account through Tailscale?

**Comment by DentonGentry** [comment]
This isn't something we can reasonably handle as a GitHub issue, please contact support: https://tailscale.com/contact/support/
