### ISSUE TITLE
Tailscale iOS - account appear duplicated when adding the same account for the second time

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [tailscale/tailscale#9975]
### What is the issue?

![IMG_3759](https://github.com/tailscale/tailscale/assets/73286927/85e6de8a-90b5-4800-8d47-229346bd67ff)

### Steps to reproduce

- Login with your current account
- Go into the new account switcher (fast user switch in Settings) and add the same account again
- The same account should appear duplicated

### Are there any recent changes that introduced the issue?

Probably the new account switcher on Tailscale iOS

### OS version

iOS 17.1

### Tailscale version

1.52.0 Release Candidate on TestFlight, but happens to the App Store version as well.

### Bug report

BUG-8ee0a7aece27b68ad52f5cd3836258aa0f8add722e291fa549e39c6b1a3311b6-20231026032619Z-4620217a0af91aab

**Comment by SinonCute** [comment]
Can also reproduce
![IMG_6592](https://github.com/tailscale/tailscale/assets/81401485/13afaeef-ae38-4aee-a9cf-d73a39aa6787)

**Comment by QuanTrieuPCYT** [comment]
Update on the issue: Seems to be fixed!

Also, the latest build of Tailscale added the ability to remove account, which you can use to remove duplicated accounts as well.

@SinonCute You might want to join the TestFlight as well and test that out.
