### ISSUE TITLE
admin: accepting a share invite causes a network error

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#998]
**Describe the bug**
Accepting a share invite causes a network error in the admin panel that isn't recoverable until you refresh the page.

**Expected behavior**
Accepting an invite shouldn't cause a network error. And if it does, it should be recoverable.

**Screenshots**
<img src="https://user-images.githubusercontent.com/303731/101397288-80165b80-389a-11eb-8dc2-6f24fb8e6a8a.gif" width="300" />

**Comment by bradfitz** [comment]
> Expected behavior
> Accepting an invite shouldn't cause a network error. And if it does, it should be recoverable.

Phrased differently: the web UI shouldn't show that there was a network error, even transiently. It might simply be inevitable that there's actually a network error while the local Tailscale daemon reconfigures the host's routes and such, but we should anticipate and hide it, unless it persists for N retries or M seconds or something.

**Comment by rosszurowski** [comment]
Agreed. Javascript doesn't make it easy to specifically filter for network errors here.

What's even more odd is that our retry logic should be catching this, so something is amiss…

**Comment by rosszurowski** [comment]
@dfcarney reported seeing the same thing on desktop Chrome when deleting a device. Seems we haven't really fixed the network errors yet…
