### ISSUE TITLE
Generate OAuth Client:  Tag section not displaying under "Devices" when selecting All:Write

### ISSUE THREAD

**Issue by jsoyland** [tailscale/tailscale#9980]
### What is the issue?

When generating a new OAuth client, I selected the "All:Write" scope - That correctly selected all other scopes, but the dialogue for tags under Devices didn't show up.

I would expect the "tags" section to show under Devices:Write whether it is selected on its own or via the "All:Write".

The tag is required when using the OAuth client to create a new auth key, so it should be required when selecting the "All:Write" scope.

### Selecting All:Write
![image](https://github.com/tailscale/tailscale/assets/16296224/300b34b8-8a9b-4611-8fe2-cd9b28b08199)

### Selecting Devices:Write
<img width="532" alt="image" src="https://github.com/tailscale/tailscale/assets/16296224/70c15cd5-f570-4a3c-8483-5578f404a78d">

### Steps to reproduce

1. Navigate on UI to Settings->OAuth Clients
2. Click "Generate OAuth Client"
3. Click either "All:Write" or "Devices:Write" to see the differences.

Also when "Devices:Write" is checked and the "tags" dialogue is visible, subsequently clicking "All:Write" will render the tags dialogue invisible.

**Comment by timtailscale** [comment]
The OAuth **all** scope gives the OAuth token access to all tags. If needed, you can down-scope the API token to just the tags needed when calling the OAuth token endpoint. More details in #8299, and at https://tailscale.com/kb/1215/oauth-clients/#tailscale-oauth-token-endpoint.
