### ISSUE TITLE
net/dns/recursive: b.root-servers.net IP addresses will change 2023-11-27

### ISSUE THREAD

**Issue by mnordhoff** [tailscale/tailscale#9994]
### What is the issue?

`net/dns/recursive/recursive.go` includes the root DNS server IP addresses, to wit:

https://github.com/tailscale/tailscale/blob/9107b5eadf92c5a3ed5702f03f87ae9e05fd6e89/net/dns/recursive/recursive.go#L67

https://github.com/tailscale/tailscale/blob/9107b5eadf92c5a3ed5702f03f87ae9e05fd6e89/net/dns/recursive/recursive.go#L83

You may already have this on your to-do list, but if not, FYI, the `b.root-servers.net` IP addresses will change 2023-11-27:

https://b.root-servers.org/news/2023/05/16/new-addresses.html

> USC/ISI is renumbering both its IPv4 and IPv6 addresses for b.root-servers.net on 2023-11-27. Our new IPv4 address will be 170.247.170.2 and our new IPv6 address will be 2801:1b8:10::b. USC/ISI will continue to support root service over our current IPv4 and IPv6 addresses for at least one year (until 2024-11-27) in order to provide a stable transition period while new root hints files are distributed in software and operating system packages.

(They actually activated the new IPs already, but the official changeover is a month from now.)

**Comment by andrew-d** [comment]
@mnordhoff Thank you! I hadn't yet see this news, so I just opened #9998 to change these IPs. I'll merge it after we release the next Tailscale client version.
